INET Framework for OMNeT++/OMNEST: Changes-20051129.txt File Reference
Changes-20051129.txt File Reference
Functions
Changes from Pascal conn retransmitOneSegment ()
recalculateSlowStartThreshold ()
if (cwndVector) cwndVector -> record(state->snd_cwnd)
Variables
Changes from Pascal Rouseau
state snd_cwnd = 3*state->snd_mss
tcpEV<< "Reno on dupAck> __pad0__
Function Documentation
if()
if (cwndVector) -> record(state->snd_cwnd)
Referenced by inet::eigrp::EigrpMetricHelper::computeClassicMetric(), inet::eigrp::EigrpMetricHelper::computeWideMetric(), inet::IntervalTree::deleteNode(), inet::QosClassifier::getUserPriority(), inet::SctpNatServer::handleMessage(), inet::Udp::handleUpperPacket(), inet::Igmpv3::multicastSourceListChanged(), inet::tcp::pbuf_header(), inet::tcp::TcpLwip::refreshDisplay(), inet::tcp::TcpConnection::sendData(), inet::sctp::SctpAssociation::sendOnPath(), and inet::tcp::TcpConnection::sendSegment().
recalculateSlowStartThreshold()
recalculateSlowStartThreshold ()
retransmitOneSegment()
Changes from Pascal conn retransmitOneSegment ()
Variable Documentation
__pad0__
tcpEV<< "Reno on dupAck> __pad0__
Rouseau
Changes from Pascal Rouseau
snd_cwnd
state snd_cwnd = 3*state->snd_mss