INET Framework for OMNeT++/OMNEST: inet::physicallayer::WirelessSignal Class Reference
inet::physicallayer::WirelessSignal Class Reference
#include <WirelessSignal.h>
Public Member Functions
WirelessSignal (const ITransmission *transmission)
WirelessSignal (const WirelessSignal &other)
virtual WirelessSignal * dup () const override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IRadio * getTransmitter () const
virtual const IRadio * getReceiver () const
virtual const ITransmission * getTransmission () const override
Returns the radio signal transmission that this signal represents.
virtual const IArrival * getArrival () const override
This function may return nullptr if this is not yet computed.
virtual const IListening * getListening () const override
This function may return nullptr if this is not yet computed.
virtual const IReception * getReception () const override
This function may return nullptr if this is not yet computed.
Public Member Functions inherited from inet::physicallayer::Signal
Signal (const char *name=nullptr, short kind=0, int64_t bitLength=0)
Signal (const Signal &other)
virtual const char * getFullName () const override
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::IPhysicalLayerFrame
virtual ~IPhysicalLayerFrame ()
Protected Member Functions
bool isDup () const
Protected Attributes
const int transmissionId
const ITransmission * transmission
const IRadioMedium * radioMedium
const IRadio * receiver = nullptr
const IArrival * arrival = nullptr
const IListening * listening = nullptr
const IReception * reception = nullptr
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
WirelessSignal() [1/2]
inet::physicallayer::WirelessSignal::WirelessSignal (const ITransmission * transmission)
                                                                 :
     transmissionId(transmission->getId()),
     transmission(transmission),
     radioMedium(transmission->getTransmitter()->getMedium())
 {
 }
WirelessSignal() [2/2]
inet::physicallayer::WirelessSignal::WirelessSignal (const WirelessSignal & other)
                                                           :
     Signal(other),
     transmissionId(other.transmissionId),
     transmission(nullptr),
     radioMedium(other.radioMedium)
 {
 }
Member Function Documentation
dup()
virtual WirelessSignal* inet::physicallayer::WirelessSignal::dup () const inline override virtual
Reimplemented from inet::physicallayer::Signal.
 { return new WirelessSignal(*this); }
getArrival()
const IArrival * inet::physicallayer::WirelessSignal::getArrival () const override virtual
This function may return nullptr if this is not yet computed.
Implements inet::physicallayer::IWirelessSignal.
 {
     if (!isDup()) {
         if (arrival == nullptr)
             arrival = radioMedium->getArrival(getReceiver(), transmission);
         return arrival;
     }
     else {
         auto transmission = getTransmission();
         return transmission != nullptr ? radioMedium->getArrival(getReceiver(), transmission) : nullptr;
     }
 }
Referenced by inet::physicallayer::Radio::continueReception(), inet::physicallayer::Radio::endReception(), and inet::physicallayer::Radio::startReception().
getListening()
const IListening * inet::physicallayer::WirelessSignal::getListening () const override virtual
This function may return nullptr if this is not yet computed.
Implements inet::physicallayer::IWirelessSignal.
 {
     if (!isDup()) {
         if (listening == nullptr)
             listening = radioMedium->getListening(getReceiver(), transmission);
         return listening;
     }
     else {
         auto transmission = getTransmission();
         return transmission != nullptr ? radioMedium->getListening(getReceiver(), transmission) : nullptr;
     }
 }
getReceiver()
const IRadio * inet::physicallayer::WirelessSignal::getReceiver () const virtual
 {
     if (receiver == nullptr)
         receiver = check_and_cast<const IRadio *>(getArrivalModule());
     return receiver;
 }
Referenced by getArrival(), getListening(), and getReception().
getReception()
const IReception * inet::physicallayer::WirelessSignal::getReception () const override virtual
This function may return nullptr if this is not yet computed.
Implements inet::physicallayer::IWirelessSignal.
 {
     if (!isDup()) {
         if (reception == nullptr)
             reception = radioMedium->getReception(getReceiver(), transmission);
         return reception;
     }
     else {
         auto transmission = getTransmission();
         return transmission != nullptr ? radioMedium->getReception(getReceiver(), transmission) : nullptr;
     }
 }
Referenced by inet::physicallayer::Radio::abortReception().
getTransmission()
const ITransmission * inet::physicallayer::WirelessSignal::getTransmission () const override virtual
Returns the radio signal transmission that this signal represents.
This function never returns nullptr.
Implements inet::physicallayer::IWirelessSignal.
 {
     if (!isDup())
         return transmission;
     else
         return radioMedium->getTransmission(transmissionId);
 }
Referenced by inet::physicallayer::Radio::abortTransmission(), inet::physicallayer::Radio::continueTransmission(), inet::physicallayer::Radio::endTransmission(), getArrival(), getListening(), getReception(), getTransmitter(), and inet::physicallayer::NoiseSource::startTransmission().
getTransmitter()
const IRadio * inet::physicallayer::WirelessSignal::getTransmitter () const virtual
 {
     auto transmission = getTransmission();
     return transmission != nullptr ? transmission->getTransmitter() : nullptr;
 }
isDup()
bool inet::physicallayer::WirelessSignal::isDup () const inline protected
 { return transmission == nullptr; }
Referenced by getArrival(), getListening(), getReception(), and getTransmission().
printToStream()
std::ostream & inet::physicallayer::WirelessSignal::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::Signal.
 {
     return stream << (cPacket *)this;
 }
Member Data Documentation
arrival
const IArrival* inet::physicallayer::WirelessSignal::arrival = nullptr mutable protected
Referenced by getArrival().
listening
const IListening* inet::physicallayer::WirelessSignal::listening = nullptr mutable protected
Referenced by getListening().
radioMedium
const IRadioMedium* inet::physicallayer::WirelessSignal::radioMedium protected
Referenced by getArrival(), getListening(), getReception(), and getTransmission().
receiver
const IRadio* inet::physicallayer::WirelessSignal::receiver = nullptr mutable protected
Referenced by getReceiver().
reception
const IReception* inet::physicallayer::WirelessSignal::reception = nullptr mutable protected
Referenced by getReception().
transmission
const ITransmission* inet::physicallayer::WirelessSignal::transmission protected
Referenced by getArrival(), getListening(), getReception(), getTransmission(), and getTransmitter().
transmissionId
const int inet::physicallayer::WirelessSignal::transmissionId protected
Referenced by getTransmission().
The documentation for this class was generated from the following files:
WirelessSignal.h
WirelessSignal.cc