INET Framework for OMNeT++/OMNEST: inet::TosTagBase Class Reference
inet::TosTagBase Class Reference
Class generated from inet/networklayer/common/TosTag.msg:16 by opp_msgtool.
#include <TosTag_m.h>
Public Member Functions
TosTagBase ()
TosTagBase (const TosTagBase &other)
virtual ~TosTagBase ()
TosTagBase & operator= (const TosTagBase &other)
virtual TosTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getTos () const
virtual void setTos (int tos)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const TosTagBase &)=delete
Protected Attributes
int tos = -1
Private Member Functions
void copy (const TosTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/networklayer/common/TosTag.msg:16 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class TosTagBase extends TagBase
{
    int tos = -1; // differentiated services code point
}
Constructor & Destructor Documentation
TosTagBase() [1/2]
inet::TosTagBase::TosTagBase ()
TosTagBase() [2/2]
inet::TosTagBase::TosTagBase (const TosTagBase & other)
~TosTagBase()
virtual inet::TosTagBase::~TosTagBase () virtual
Member Function Documentation
copy()
void inet::TosTagBase::copy (const TosTagBase & other) private
dup()
virtual TosTagBase* inet::TosTagBase::dup () const inline override virtual
Reimplemented in inet::TosInd, and inet::TosReq.
 {return new TosTagBase(*this);}
getTos()
virtual int inet::TosTagBase::getTos () const virtual
operator=()
TosTagBase& inet::TosTagBase::operator= (const TosTagBase & other)
operator==()
bool inet::TosTagBase::operator== (const TosTagBase &) protected delete
parsimPack()
virtual void inet::TosTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::TosInd, and inet::TosReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TosTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::TosInd, and inet::TosReq.
Referenced by inet::doParsimUnpacking().
setTos()
virtual void inet::TosTagBase::setTos (int tos) virtual
Referenced by inet::tcp::TcpConnection::sendToIP().
Member Data Documentation
tos
int inet::TosTagBase::tos = -1 protected
The documentation for this class was generated from the following file:
TosTag_m.h