INET Framework for OMNeT++/OMNEST: inet::Ipv6ExtensionHeader Class Reference
inet::Ipv6ExtensionHeader Class Reference
Class generated from inet/networklayer/ipv6/Ipv6Header.msg:32 by opp_msgtool.
#include <Ipv6Header_m.h>
Public Member Functions
Ipv6ExtensionHeader ()
Ipv6ExtensionHeader (const Ipv6ExtensionHeader &other)
virtual ~Ipv6ExtensionHeader ()
Ipv6ExtensionHeader & operator= (const Ipv6ExtensionHeader &other)
virtual Ipv6ExtensionHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getExtensionType () const
virtual void setExtensionType (uint8_t extensionType)
virtual B getByteLength () const
virtual void setByteLength (B byteLength)
int getOrder () const
Protected Member Functions
bool operator== (const Ipv6ExtensionHeader &)=delete
Protected Attributes
uint8_t extensionType = 0
B byteLength = B(0)
Private Member Functions
void copy (const Ipv6ExtensionHeader &other)
Detailed Description
Class generated from inet/networklayer/ipv6/Ipv6Header.msg:32 by opp_msgtool.
//
// This serves as the base class for all the Ipv6 extension headers.
//
class Ipv6ExtensionHeader extends cObject
{
    @packetData;
    uint8_t extensionType;
    B byteLength = B(0);   // byteLength = n * 8;
}
Constructor & Destructor Documentation
Ipv6ExtensionHeader() [1/2]
inet::Ipv6ExtensionHeader::Ipv6ExtensionHeader ()
Ipv6ExtensionHeader() [2/2]
inet::Ipv6ExtensionHeader::Ipv6ExtensionHeader (const Ipv6ExtensionHeader & other)
~Ipv6ExtensionHeader()
virtual inet::Ipv6ExtensionHeader::~Ipv6ExtensionHeader () virtual
Member Function Documentation
copy()
void inet::Ipv6ExtensionHeader::copy (const Ipv6ExtensionHeader & other) private
dup()
virtual Ipv6ExtensionHeader* inet::Ipv6ExtensionHeader::dup () const inline override virtual
Reimplemented in inet::HomeAddressOption, inet::Ipv6EncapsulatingSecurityPayloadHeader, inet::Ipv6AuthenticationHeader, inet::Ipv6DestinationOptionsHeader, inet::Ipv6FragmentHeader, inet::Ipv6RoutingHeader, and inet::Ipv6HopByHopOptionsHeader.
 {return new Ipv6ExtensionHeader(*this);}
getByteLength()
virtual B inet::Ipv6ExtensionHeader::getByteLength () const virtual
Referenced by inet::Ipv6Header::addExtensionHeader(), inet::Ipv6Header::calculateFragmentLength(), and inet::Ipv6HeaderSerializer::serialize().
getExtensionType()
virtual uint8_t inet::Ipv6ExtensionHeader::getExtensionType () const virtual
Referenced by inet::Ipv6Header::addExtensionHeader(), inet::Ipv6Header::calculateUnfragmentableHeaderByteLength(), and inet::Ipv6HeaderSerializer::serialize().
getOrder()
int inet::Ipv6ExtensionHeader::getOrder () const
 {
     switch (extensionType) {
         case IP_PROT_IPv6EXT_HOP:
             return 0;
         case IP_PROT_IPv6EXT_DEST:
             return 1;
         case IP_PROT_IPv6EXT_ROUTING:
             return 2;
         case IP_PROT_IPv6EXT_FRAGMENT:
             return 3;
         case IP_PROT_IPv6EXT_AUTH:
             return 4;
         case IP_PROT_IPv6EXT_ESP:
             return 5;
         // second IP_PROT_IPv6EXT_DEST has order 6
         case IP_PROT_IPv6EXT_MOB:
             return 7;
         default:
             return -1;
     }
 }
Referenced by inet::Ipv6Header::addExtensionHeader().
operator=()
Ipv6ExtensionHeader& inet::Ipv6ExtensionHeader::operator= (const Ipv6ExtensionHeader & other)
operator==()
bool inet::Ipv6ExtensionHeader::operator== (const Ipv6ExtensionHeader &) protected delete
parsimPack()
virtual void inet::Ipv6ExtensionHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::HomeAddressOption, inet::Ipv6EncapsulatingSecurityPayloadHeader, inet::Ipv6AuthenticationHeader, inet::Ipv6DestinationOptionsHeader, inet::Ipv6FragmentHeader, inet::Ipv6RoutingHeader, and inet::Ipv6HopByHopOptionsHeader.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6ExtensionHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::HomeAddressOption, inet::Ipv6EncapsulatingSecurityPayloadHeader, inet::Ipv6AuthenticationHeader, inet::Ipv6DestinationOptionsHeader, inet::Ipv6FragmentHeader, inet::Ipv6RoutingHeader, and inet::Ipv6HopByHopOptionsHeader.
Referenced by inet::doParsimUnpacking().
setByteLength()
virtual void inet::Ipv6ExtensionHeader::setByteLength (B byteLength) virtual
Referenced by inet::Ipv6HeaderSerializer::deserialize(), inet::Ipv6Tunneling::encapsulateDatagram(), and inet::Gpsr::setGpsrOptionOnNetworkDatagram().
setExtensionType()
virtual void inet::Ipv6ExtensionHeader::setExtensionType (uint8_t extensionType) virtual
Referenced by inet::Ipv6HeaderSerializer::deserialize().
Member Data Documentation
byteLength
B inet::Ipv6ExtensionHeader::byteLength = B(0) protected
extensionType
uint8_t inet::Ipv6ExtensionHeader::extensionType = 0 protected
Referenced by getOrder().
The documentation for this class was generated from the following files:
Ipv6Header_m.h
Ipv6Header.cc