INET Framework for OMNeT++/OMNEST: inet::rtp::ReceptionReport Class Reference
inet::rtp::ReceptionReport Class Reference
Class generated from inet/transportlayer/rtp/Reports.msg:48 by opp_msgtool.
#include <Reports_m.h>
Public Member Functions
ReceptionReport ()
ReceptionReport (const ReceptionReport &other)
virtual ~ReceptionReport ()
ReceptionReport & operator= (const ReceptionReport &other)
virtual ReceptionReport * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
virtual uint8_t getFractionLost () const
virtual void setFractionLost (uint8_t fractionLost)
virtual int getPacketsLostCumulative () const
virtual void setPacketsLostCumulative (int packetsLostCumulative)
virtual uint32_t getSequenceNumber () const
virtual void setSequenceNumber (uint32_t sequenceNumber)
virtual int getJitter () const
virtual void setJitter (int jitter)
virtual int getLastSR () const
virtual void setLastSR (int lastSR)
virtual int getDelaySinceLastSR () const
virtual void setDelaySinceLastSR (int delaySinceLastSR)
virtual std::string str () const override
Writes a short info about this ReceptionReport into the given string.
virtual void dump (std::ostream &os) const
Writes a longer info about this ReceptionReport into the given stream.
Protected Member Functions
bool operator== (const ReceptionReport &)=delete
Protected Attributes
uint32_t ssrc = 0
uint8_t fractionLost = 0
int packetsLostCumulative = 0
uint32_t sequenceNumber = 0
int jitter = 0
int lastSR = 0
int delaySinceLastSR = 0
Private Member Functions
void copy (const ReceptionReport &other)
Detailed Description
Class generated from inet/transportlayer/rtp/Reports.msg:48 by opp_msgtool.
//
// Rrepresents an RTP receiver report stored
// in an RTPSenderReportPacket or RTPReceiverReport.
//
class ReceptionReport extends cObject
{
    // The ssrc identifier of the sender this ~ReceptionReport is for.
    uint32_t ssrc;
    // The fraction lost.
    uint8_t fractionLost;
    // The number of packets expected minus the number of packets received.
    int packetsLostCumulative;
    // The extended highest sequence number received.
    uint32_t sequenceNumber;
    // The interarrival jitter.
    int jitter;
    // The rtp time stamp of the last ~SenderReport received from this source.
    int lastSR;
    // The delay since the last ~SenderReport from this sender has been
    // received in units of 1/65536 seconds.
    int delaySinceLastSR;
}
Constructor & Destructor Documentation
ReceptionReport() [1/2]
inet::rtp::ReceptionReport::ReceptionReport ()
ReceptionReport() [2/2]
inet::rtp::ReceptionReport::ReceptionReport (const ReceptionReport & other)
~ReceptionReport()
virtual inet::rtp::ReceptionReport::~ReceptionReport () virtual
Member Function Documentation
copy()
void inet::rtp::ReceptionReport::copy (const ReceptionReport & other) private
dump()
void inet::rtp::ReceptionReport::dump (std::ostream & os) const virtual
Writes a longer info about this ReceptionReport into the given stream.
 {
     os << "ReceptionReport:" << endl;
     os << "  ssrc = " << getSsrc() << endl;
     os << "  fractionLost = " << (int)getFractionLost() << endl;
     os << "  packetsLostCumulative = " << getPacketsLostCumulative() << endl;
     os << "  extendedHighestSequenceNumber = " << getSequenceNumber() << endl;
     os << "  jitter = " << getJitter() << endl;
     os << "  lastSR = " << getLastSR() << endl;
     os << "  delaySinceLastSR = " << getDelaySinceLastSR() << endl;
 }
dup()
virtual ReceptionReport* inet::rtp::ReceptionReport::dup () const inline override virtual
 {return new ReceptionReport(*this);}
getDelaySinceLastSR()
virtual int inet::rtp::ReceptionReport::getDelaySinceLastSR () const virtual
Referenced by dump().
getFractionLost()
virtual uint8_t inet::rtp::ReceptionReport::getFractionLost () const virtual
Referenced by dump().
getJitter()
virtual int inet::rtp::ReceptionReport::getJitter () const virtual
Referenced by dump().
getLastSR()
virtual int inet::rtp::ReceptionReport::getLastSR () const virtual
Referenced by dump().
getPacketsLostCumulative()
virtual int inet::rtp::ReceptionReport::getPacketsLostCumulative () const virtual
Referenced by dump().
getSequenceNumber()
virtual uint32_t inet::rtp::ReceptionReport::getSequenceNumber () const virtual
Referenced by dump().
getSsrc()
virtual uint32_t inet::rtp::ReceptionReport::getSsrc () const virtual
Referenced by dump(), inet::rtp::Rtcp::processIncomingRTCPReceiverReportPacket(), inet::rtp::Rtcp::processIncomingRTCPSenderReportPacket(), and str().
operator=()
ReceptionReport& inet::rtp::ReceptionReport::operator= (const ReceptionReport & other)
operator==()
bool inet::rtp::ReceptionReport::operator== (const ReceptionReport &) protected delete
parsimPack()
virtual void inet::rtp::ReceptionReport::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::ReceptionReport::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::rtp::doParsimUnpacking().
setDelaySinceLastSR()
virtual void inet::rtp::ReceptionReport::setDelaySinceLastSR (int delaySinceLastSR) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
setFractionLost()
virtual void inet::rtp::ReceptionReport::setFractionLost (uint8_t fractionLost) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
setJitter()
virtual void inet::rtp::ReceptionReport::setJitter (int jitter) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
setLastSR()
virtual void inet::rtp::ReceptionReport::setLastSR (int lastSR) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
setPacketsLostCumulative()
virtual void inet::rtp::ReceptionReport::setPacketsLostCumulative (int packetsLostCumulative) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
setSequenceNumber()
virtual void inet::rtp::ReceptionReport::setSequenceNumber (uint32_t sequenceNumber) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
setSsrc()
virtual void inet::rtp::ReceptionReport::setSsrc (uint32_t ssrc) virtual
Referenced by inet::rtp::RtpReceiverInfo::receptionReport().
str()
std::string inet::rtp::ReceptionReport::str () const override virtual
Writes a short info about this ReceptionReport into the given string.
 {
     std::stringstream out;
     out << "ReceptionReport.ssrc=" << getSsrc();
     return out.str();
 }
Member Data Documentation
delaySinceLastSR
int inet::rtp::ReceptionReport::delaySinceLastSR = 0 protected
fractionLost
uint8_t inet::rtp::ReceptionReport::fractionLost = 0 protected
jitter
int inet::rtp::ReceptionReport::jitter = 0 protected
lastSR
int inet::rtp::ReceptionReport::lastSR = 0 protected
packetsLostCumulative
int inet::rtp::ReceptionReport::packetsLostCumulative = 0 protected
sequenceNumber
uint32_t inet::rtp::ReceptionReport::sequenceNumber = 0 protected
ssrc
uint32_t inet::rtp::ReceptionReport::ssrc = 0 protected
The documentation for this class was generated from the following files:
Reports_m.h
Reports.cc