INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211Htmcs Class Reference
inet::physicallayer::Ieee80211Htmcs Class Reference
#include <Ieee80211HtMode.h>
Public Member Functions
Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211HtCode *code, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation)
Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
virtual ~Ieee80211Htmcs ()
const Ieee80211HtCode * getCode () const
unsigned int getMcsIndex () const
virtual const Ieee80211OfdmModulation * getModulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension1Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension2Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension3Modulation () const
virtual Hz getBandwidth () const
Protected Attributes
const unsigned int mcsIndex
const Ieee80211OfdmModulation * stream1Modulation
const Ieee80211OfdmModulation * stream2Modulation
const Ieee80211OfdmModulation * stream3Modulation
const Ieee80211OfdmModulation * stream4Modulation
const Ieee80211HtCode * code
const Hz bandwidth
Constructor & Destructor Documentation
Ieee80211Htmcs() [1/5]
inet::physicallayer::Ieee80211Htmcs::Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211HtCode * code, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation)
                                                                                                                                                                                                                                                                                          :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     code(code)
 {
 }
Ieee80211Htmcs() [2/5]
inet::physicallayer::Ieee80211Htmcs::Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     code(Ieee80211HtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Htmcs() [3/5]
inet::physicallayer::Ieee80211Htmcs::Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                              :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(nullptr),
     code(Ieee80211HtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Htmcs() [4/5]
inet::physicallayer::Ieee80211Htmcs::Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                            :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(nullptr),
     stream4Modulation(nullptr),
     code(Ieee80211HtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Htmcs() [5/5]
inet::physicallayer::Ieee80211Htmcs::Ieee80211Htmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                          :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(nullptr),
     stream3Modulation(nullptr),
     stream4Modulation(nullptr),
     code(Ieee80211HtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
~Ieee80211Htmcs()
inet::physicallayer::Ieee80211Htmcs::~Ieee80211Htmcs () virtual
 {
     delete code;
 }
Member Function Documentation
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211Htmcs::getBandwidth () const inline virtual
 { return bandwidth; }
Referenced by inet::physicallayer::Ieee80211HtCompliantModes::getCompliantMode().
getCode()
const Ieee80211HtCode* inet::physicallayer::Ieee80211Htmcs::getCode () const inline
 { return code; }
Referenced by inet::physicallayer::Ieee80211HtDataMode::getCode().
getMcsIndex()
unsigned int inet::physicallayer::Ieee80211Htmcs::getMcsIndex () const inline
 { return mcsIndex; }
Referenced by inet::physicallayer::Ieee80211HtCompliantModes::getCompliantMode().
getModulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::getModulation () const inline virtual
 { return stream1Modulation; }
Referenced by inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum(), and inet::physicallayer::Ieee80211HtDataMode::getModulation().
getStreamExtension1Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::getStreamExtension1Modulation () const inline virtual
 { return stream2Modulation; }
Referenced by inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension2Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::getStreamExtension2Modulation () const inline virtual
 { return stream3Modulation; }
Referenced by inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension3Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::getStreamExtension3Modulation () const inline virtual
 { return stream4Modulation; }
Referenced by inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
Member Data Documentation
bandwidth
const Hz inet::physicallayer::Ieee80211Htmcs::bandwidth protected
code
const Ieee80211HtCode* inet::physicallayer::Ieee80211Htmcs::code protected
Referenced by ~Ieee80211Htmcs().
mcsIndex
const unsigned int inet::physicallayer::Ieee80211Htmcs::mcsIndex protected
stream1Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::stream1Modulation protected
stream2Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::stream2Modulation protected
stream3Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::stream3Modulation protected
stream4Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Htmcs::stream4Modulation protected
The documentation for this class was generated from the following files:
Ieee80211HtMode.h
Ieee80211HtMode.cc