INET Framework for OMNeT++/OMNEST: inet::StreamingTransmitter Class Reference
inet::StreamingTransmitter Class Reference
#include <StreamingTransmitter.h>
Public Member Functions
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::StreamingTransmitterBase
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::PacketTransmitterBase
virtual ~PacketTransmitterBase ()
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::ClockUserModuleMixin< OperationalMixin< PacketProcessorBase > >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Protected Member Functions
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual void startTx (Packet *packet)
virtual void endTx ()
virtual void abortTx () override
Protected Member Functions inherited from inet::StreamingTransmitterBase
virtual void initialize (int stage) override
virtual void scheduleAt (simtime_t t, cMessage *message) override
virtual void scheduleTxEndTimer (Signal *signal)
Protected Member Functions inherited from inet::PacketTransmitterBase
virtual void finish () override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual Signal * encodePacket (Packet *packet)
virtual void prepareSignal (Signal *signal)
virtual void sendSignalStart (Signal *signal, int transmissionId)
virtual void sendSignalProgress (Signal *signal, int transmissionId, b bitPosition, clocktime_t timePosition)
virtual void sendSignalEnd (Signal *signal, int transmissionId)
virtual clocktime_t calculateClockTimeDuration (const Packet *packet) const
virtual simtime_t calculateDuration (clocktime_t clockTimeDuration) const
virtual bool isTransmitting () const
Protected Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< PacketProcessorBase >
enum State
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Protected Attributes inherited from inet::StreamingTransmitterBase
cChannel * transmissionChannel = nullptr
Protected Attributes inherited from inet::PacketTransmitterBase
cPar * dataratePar = nullptr
cGate * inputGate = nullptr
cGate * outputGate = nullptr
ModuleRef< IActivePacketSource > producer
bps txDatarate = bps(NaN)
Signal * txSignal = nullptr
ClockEvent * txEndTimer = nullptr
simtime_t txStartTime = -1
clocktime_t txStartClockTime = -1
clocktime_t txDurationClockTime = -1
Protected Attributes inherited from inet::OperationalMixin< PacketProcessorBase >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Member Function Documentation
abortTx()
void inet::StreamingTransmitter::abortTx () override protected virtual
Implements inet::StreamingTransmitterBase.
 {
     // 1. check current state
     ASSERT(isTransmitting());
     // 2. create new truncated signal
     auto packet = check_and_cast<Packet *>(txSignal->decapsulate());
     // TODO we can't just simply cut the packet proportionally with time because it's not always the case (modulation, scrambling, etc.)
     simtime_t timePosition = simTime() - txStartTime;
     b dataPosition = b(std::floor(txDatarate.get() * timePosition.dbl()));
     packet->eraseAtBack(packet->getTotalLength() - dataPosition);
     packet->setBitError(true);
     auto signal = encodePacket(packet);
     signal->setDuration(timePosition);
     // 3. send signal end to receiver and notify subscribers
     EV_INFO << "Aborting transmission" << EV_FIELD(packet) << EV_FIELD(txDatarate) << EV_ENDL;
     handlePacketProcessed(packet);
     emit(transmissionEndedSignal, signal);
     sendSignalEnd(signal, txSignal->getId());
     // 4. delete old signal
     delete txSignal;
     txSignal = nullptr;
     // 5. clear internal state
     txStartTime = -1;
     txStartClockTime = -1;
     // 6. notify producer
     auto gate = inputGate->getPathStartGate();
     if (producer != nullptr) {
         producer->handlePushPacketProcessed(packet, gate, true);
         producer->handleCanPushPacketChanged(gate);
     }
 }
Referenced by handleCrashOperation(), and handleStopOperation().
endTx()
void inet::StreamingTransmitter::endTx () protected virtual
 {
     // 1. check current state
     ASSERT(isTransmitting());
     // 2. send signal end to receiver and notify subscribers
     auto packet = check_and_cast<Packet *>(txSignal->getEncapsulatedPacket());
     EV_INFO << "Ending transmission" << EV_FIELD(packet) << EV_FIELD(txDatarate) << EV_ENDL;
     handlePacketProcessed(packet);
     emit(transmissionEndedSignal, txSignal);
     sendSignalEnd(txSignal, txSignal->getId());
     // 3. clear internal state
     txSignal = nullptr;
     txStartTime = -1;
     txStartClockTime = -1;
     // 4. notify producer
     auto gate = inputGate->getPathStartGate();
     if (producer != nullptr) {
         producer->handlePushPacketProcessed(packet, gate, true);
         producer->handleCanPushPacketChanged(gate);
     }
 }
Referenced by handleMessageWhenUp().
handleCrashOperation()
void inet::StreamingTransmitter::handleCrashOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 {
     if (isTransmitting())
         abortTx();
 }
handleMessageWhenUp()
void inet::StreamingTransmitter::handleMessageWhenUp (cMessage * message) override protected virtual
Reimplemented from inet::PacketTransmitterBase.
 {
     if (message == txEndTimer)
         endTx();
     else
         PacketTransmitterBase::handleMessageWhenUp(message);
     updateDisplayString();
 }
handleStopOperation()
void inet::StreamingTransmitter::handleStopOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 {
     if (isTransmitting())
         abortTx();
 }
pushPacket()
void inet::StreamingTransmitter::pushPacket (Packet * packet, cGate * gate) override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacket");
     take(packet);
     startTx(packet);
     updateDisplayString();
 }
startTx()
void inet::StreamingTransmitter::startTx (Packet * packet) protected virtual
 {
     // 1. check current state
     ASSERT(!isTransmitting());
     // 2. store transmission progress
     txDatarate = bps(*dataratePar);
     txStartTime = simTime();
     txStartClockTime = getClockTime();
     // 3. create signal
     auto signal = encodePacket(packet);
     txSignal = signal->dup();
     // 5. send signal start and notify subscribers
     EV_INFO << "Starting transmission" << EV_FIELD(packet) << EV_FIELD(txDatarate) << EV_ENDL;
     emit(transmissionStartedSignal, signal);
     sendSignalStart(signal, txSignal->getId());
     // 6. schedule transmission end
     scheduleTxEndTimer(txSignal);
 }
Referenced by pushPacket().
supportsPacketStreaming()
virtual bool inet::StreamingTransmitter::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return gate == outputGate; }
The documentation for this class was generated from the following files:
StreamingTransmitter.h
StreamingTransmitter.cc