INET Framework for OMNeT++/OMNEST: inet::PacketDissector Class Reference
inet::PacketDissector Class Reference
This class provides efficient general purpose packet dissection.
#include <PacketDissector.h>
Classes
class ChunkBuilder
class ICallback
class PduTreeBuilder
class ProtocolDataUnit
class ProtocolDissectorCallback
Public Member Functions
PacketDissector (const ProtocolDissectorRegistry &protocolDissectorRegistry, ICallback &callback)
void dissectPacket (Packet *packet) const
Dissects the given packet according to the attached PacketProtocolTag.
void dissectPacket (Packet *packet, const Protocol *protocol, b extraFrontOffset=b(0), b extraBackOffset=b(0)) const
Dissects the given packet of the provided protocol.
Protected Member Functions
void doDissectPacket (Packet *packet, const Protocol *protocol) const
Protected Attributes
const ProtocolDissectorRegistry & protocolDissectorRegistry
ICallback & callback
Detailed Description
This class provides efficient general purpose packet dissection.
Packet dissection may be useful for printing packet details, filter packets, finding information in a packet deep down.
The supported protocols are provided by a ProtocolDissectorRegistry. The packet dissection algorithm calls the visitChunk() method of the provided PacketDissector::ICallback for each protocol specific chunk found in the packet. The chunks are passed to the method in the order they appear in the packet from left to right using their most specific protocol dependent form.
Constructor & Destructor Documentation
PacketDissector()
inet::PacketDissector::PacketDissector (const ProtocolDissectorRegistry & protocolDissectorRegistry, ICallback & callback)
                                                                                                                 :
     protocolDissectorRegistry(protocolDissectorRegistry),
     callback(callback)
 {
 }
Member Function Documentation
dissectPacket() [1/2]
void inet::PacketDissector::dissectPacket (Packet * packet) const
Dissects the given packet according to the attached PacketProtocolTag.
 {
     const auto& packetProtocolTag = packet->findTag<PacketProtocolTag>();
     auto protocol = packetProtocolTag != nullptr ? packetProtocolTag->getProtocol() : nullptr;
     if (packetProtocolTag != nullptr)
         dissectPacket(packet, protocol, packetProtocolTag->getFrontOffset(), packetProtocolTag->getBackOffset());
     else
         dissectPacket(packet, protocol);
 }
Referenced by inet::Packet::getDissection(), inet::BehaviorAggregateClassifier::PacketDissectorCallback::matches(), inet::MultiFieldClassifier::PacketDissectorCallback::matches(), inet::PacketFilter::matches(), inet::PacketPrinter::printPacket(), and inet::PacketDeserializer::processPacket().
dissectPacket() [2/2]
void inet::PacketDissector::dissectPacket (Packet * packet, const Protocol * protocol, b extraFrontOffset = b(0), b extraBackOffset = b(0)) const
Dissects the given packet of the provided protocol.
The packet dissection algorithm calls the visitChunk() method of the provided callback for each protocol specific chunk found in the packet.
 {
     auto frontOffset = packet->getFrontOffset();
     auto backOffset = packet->getBackOffset();
     packet->setFrontOffset(frontOffset + extraFrontOffset);
     packet->setBackOffset(backOffset + extraBackOffset);
     // dissect packet data part according to protocol
     doDissectPacket(packet, protocol);
     // dissect remaining junk in packet without protocol (e.g. ethernet padding at IP level)
     if (packet->getDataLength() != b(0))
         doDissectPacket(packet, nullptr);
     ASSERT(packet->getDataLength() == b(0));
     packet->setFrontOffset(frontOffset);
     packet->setBackOffset(backOffset);
 }
doDissectPacket()
void inet::PacketDissector::doDissectPacket (Packet * packet, const Protocol * protocol) const protected
 {
     auto protocolDissector = callback.shouldDissectProtocolDataUnit(protocol) ? protocolDissectorRegistry.findProtocolDissector(protocol) : nullptr;
     if (protocolDissector == nullptr)
         protocolDissector = protocolDissectorRegistry.getProtocolDissector(nullptr);
     ProtocolDissectorCallback callback(*this);
     protocolDissector->dissect(packet, protocol, callback);
 }
Referenced by dissectPacket().
Member Data Documentation
callback
ICallback& inet::PacketDissector::callback protected
Referenced by doDissectPacket().
protocolDissectorRegistry
const ProtocolDissectorRegistry& inet::PacketDissector::protocolDissectorRegistry protected
Referenced by doDissectPacket().
The documentation for this class was generated from the following files:
PacketDissector.h
PacketDissector.cc