INET Framework for OMNeT++/OMNEST: inet::rtp::SdesItem Class Reference
inet::rtp::SdesItem Class Reference
The class SdesItem is used for storing a source description item (type of description, description string) for an Rtp end system.
#include <Sdes.h>
Public Types
enum SdesItemType {
SDES_UNDEF = 0, SDES_CNAME = 1, SDES_NAME = 2, SDES_EMAIL = 3,
SDES_PHONE = 4, SDES_LOC = 5, SDES_TOOL = 6, SDES_NOTE = 7,
SDES_PRIV = 8
}
This enumeration holds the types of source description items as defined in the RFC.
Public Member Functions
SdesItem ()
Default constructor.
SdesItem (SdesItemType type, const char *content)
Constructor which sets the entry.
SdesItem (const SdesItem &sdesItem)
Copy constructor.
virtual ~SdesItem ()
Destructor.
SdesItem & operator= (const SdesItem &sdesItem)
Assignment operator.
virtual SdesItem * dup () const override
Duplicates theis SdesItem by calling the copy constructor.
virtual std::string str () const override
Writes a short info about this SdesItem into the given string.
virtual void dump (std::ostream &os) const
Writes an info about this SdesItem into the give output stream.
virtual SdesItemType getType () const
Returns the type of this sdes item.
virtual const char * getContent () const
Returns the stored sdes string.
virtual int getLengthField () const
This method returns the length of Value part.
virtual int getSdesTotalLength () const
This method returns the size of this SdesItem in bytes as it would be in the real world.
Protected Attributes
SdesItemType _type
The type of this SdesItem.
int _length
The length of this SdesItem.
std::string _content
The sdes string.
Private Member Functions
void copy (const SdesItem &other)
void clean ()
Detailed Description
The class SdesItem is used for storing a source description item (type of description, description string) for an Rtp end system.
Member Enumeration Documentation
SdesItemType
enum inet::rtp::SdesItem::SdesItemType
This enumeration holds the types of source description items as defined in the RFC.
In this implementation only SDES_UNDEF and SDES_CNAME are usable.
Enumerator
SDES_UNDEF
SDES_CNAME
SDES_NAME
SDES_EMAIL
SDES_PHONE
SDES_LOC
SDES_TOOL
SDES_NOTE
SDES_PRIV
                       {
         SDES_UNDEF = 0,
         SDES_CNAME = 1,
         SDES_NAME  = 2,
         SDES_EMAIL = 3,
         SDES_PHONE = 4,
         SDES_LOC   = 5,
         SDES_TOOL  = 6,
         SDES_NOTE  = 7,
         SDES_PRIV  = 8
     };
Constructor & Destructor Documentation
SdesItem() [1/3]
inet::rtp::SdesItem::SdesItem ()
Default constructor.
                    : cObject()
 {
     _type = SDES_UNDEF;
     _length = 0;
     _content = "";
 }
Referenced by dup().
SdesItem() [2/3]
inet::rtp::SdesItem::SdesItem (SdesItemType type, const char * content)
Constructor which sets the entry.
                                                          : cObject()
 {
     if (nullptr == content)
         throw cRuntimeError("The content parameter must be a valid pointer.");
     _type = type;
     _content = content;
     // an sdes item requires one byte for the type field,
     // one byte for the length field and bytes for
     // the content string
     _length = _content.length();
 }
SdesItem() [3/3]
inet::rtp::SdesItem::SdesItem (const SdesItem & sdesItem)
Copy constructor.
                                            : cObject(sdesItem)
 {
     copy(sdesItem);
 }
~SdesItem()
inet::rtp::SdesItem::~SdesItem () virtual
Destructor.
 {
     clean();
 }
Member Function Documentation
clean()
void inet::rtp::SdesItem::clean () inline private
 {} // FIXME The `_content' sometimes allocated, sometimes not allocated pointer.
Referenced by operator=(), and ~SdesItem().
copy()
void inet::rtp::SdesItem::copy (const SdesItem & other) private
 {
     _type = sdesItem._type;
     _length = sdesItem._length;
     _content = sdesItem._content;
 }
Referenced by operator=(), and SdesItem().
dump()
void inet::rtp::SdesItem::dump (std::ostream & os) const virtual
Writes an info about this SdesItem into the give output stream.
 {
     os << "SdesItem:" << endl;
     os << "  type = " << _type << endl;
     os << "  content = " << _content << endl;
 }
dup()
SdesItem * inet::rtp::SdesItem::dup () const override virtual
Duplicates theis SdesItem by calling the copy constructor.
 {
     return new SdesItem(*this);
 }
Referenced by inet::rtp::RtpParticipantInfo::processSDESChunk().
getContent()
const char * inet::rtp::SdesItem::getContent () const virtual
Returns the stored sdes string.
 {
     return _content.c_str();
 }
getLengthField()
int inet::rtp::SdesItem::getLengthField () const virtual
This method returns the length of Value part.
 {
     // _length contains the length of value without length of Type and Length fields
     return _length;
 }
getSdesTotalLength()
int inet::rtp::SdesItem::getSdesTotalLength () const virtual
This method returns the size of this SdesItem in bytes as it would be in the real world.
 {
     // bytes needed for this sdes item are
     // one byte for type, one for length
     // and the string
     return _length + 2;
 }
Referenced by inet::rtp::SdesChunk::addSDESItem().
getType()
SdesItem::SdesItemType inet::rtp::SdesItem::getType () const virtual
Returns the type of this sdes item.
 {
     return _type;
 }
Referenced by inet::rtp::SdesChunk::addSDESItem().
operator=()
SdesItem & inet::rtp::SdesItem::operator= (const SdesItem & sdesItem)
Assignment operator.
 {
     if (this == &sdesItem)
         return *this;
     clean();
     cObject::operator=(sdesItem);
     copy(sdesItem);
     return *this;
 }
str()
std::string inet::rtp::SdesItem::str () const override virtual
Writes a short info about this SdesItem into the given string.
 {
     std::stringstream out;
     out << "SdesItem=" << _content;
     return out.str();
 }
Member Data Documentation
_content
std::string inet::rtp::SdesItem::_content protected
The sdes string.
Referenced by copy(), dump(), getContent(), SdesItem(), and str().
_length
int inet::rtp::SdesItem::_length protected
The length of this SdesItem.
Referenced by copy(), getLengthField(), getSdesTotalLength(), and SdesItem().
_type
SdesItemType inet::rtp::SdesItem::_type protected
The type of this SdesItem.
Referenced by copy(), dump(), getType(), and SdesItem().
The documentation for this class was generated from the following files:
Sdes.h
Sdes.cc