INET Framework for OMNeT++/OMNEST: inet::ieee80211::BlockAckRecord Class Reference
inet::ieee80211::BlockAckRecord Class Reference
#include <BlockAckRecord.h>
Public Member Functions
BlockAckRecord (MacAddress originatorAddress, Tid tid)
virtual ~BlockAckRecord ()
void blockAckPolicyFrameReceived (const Ptr< const Ieee80211DataHeader > &header)
bool getAckState (SequenceNumberCyclic sequenceNumber, FragmentNumber fragmentNumber)
void removeAckStates (SequenceNumberCyclic sequenceNumber)
MacAddress getOriginatorAddress ()
Tid getTid ()
Protected Attributes
MacAddress originatorAddress = MacAddress::UNSPECIFIED_ADDRESS
Tid tid = -1
std::map< SequenceControlField, bool > acknowledgmentState
Constructor & Destructor Documentation
BlockAckRecord()
inet::ieee80211::BlockAckRecord::BlockAckRecord (MacAddress originatorAddress, Tid tid)
                                                                     :
     originatorAddress(originatorAddress),
     tid(tid)
 {
 }
~BlockAckRecord()
virtual inet::ieee80211::BlockAckRecord::~BlockAckRecord () inline virtual
 {}
Member Function Documentation
blockAckPolicyFrameReceived()
void inet::ieee80211::BlockAckRecord::blockAckPolicyFrameReceived (const Ptr< const Ieee80211DataHeader > & header)
 {
     SequenceNumberCyclic sequenceNumber = header->getSequenceNumber();
     FragmentNumber fragmentNumber = header->getFragmentNumber();
     acknowledgmentState[SequenceControlField(sequenceNumber.get(), fragmentNumber)] = true;
 }
Referenced by inet::ieee80211::RecipientBlockAckAgreement::blockAckPolicyFrameReceived().
getAckState()
bool inet::ieee80211::BlockAckRecord::getAckState (SequenceNumberCyclic sequenceNumber, FragmentNumber fragmentNumber)
 {
     // The status of MPDUs that are considered “old” and prior to the sequence number
     // range for which the receiver maintains status shall be reported as successfully
     // received (i.e., the corresponding bit in the bitmap shall be set to 1).
     if (containsKey(acknowledgmentState, SequenceControlField(sequenceNumber.get(), fragmentNumber))) {
         return true;
     }
     else if (acknowledgmentState.size() == 0) {
         return true; // TODO old?
     }
     else {
         auto earliest = acknowledgmentState.begin();
         return SequenceNumberCyclic(earliest->first.getSequenceNumber()) > sequenceNumber; // old = true
     }
 }
Referenced by inet::ieee80211::RecipientBlockAckProcedure::buildBlockAck().
getOriginatorAddress()
MacAddress inet::ieee80211::BlockAckRecord::getOriginatorAddress () inline
 { return originatorAddress; }
Referenced by inet::ieee80211::BlockAckReordering::createReceiveBufferIfNecessary(), and inet::ieee80211::operator<<().
getTid()
Tid inet::ieee80211::BlockAckRecord::getTid () inline
 { return tid; }
Referenced by inet::ieee80211::BlockAckReordering::createReceiveBufferIfNecessary(), and inet::ieee80211::operator<<().
removeAckStates()
void inet::ieee80211::BlockAckRecord::removeAckStates (SequenceNumberCyclic sequenceNumber)
 {
     auto it = acknowledgmentState.begin();
     while (it != acknowledgmentState.end()) {
         if (SequenceNumberCyclic(it->first.getSequenceNumber()) < sequenceNumber)
             it = acknowledgmentState.erase(it);
         else
             it++;
     }
 }
Referenced by inet::ieee80211::BlockAckReordering::passedUp().
Member Data Documentation
acknowledgmentState
std::map<SequenceControlField, bool> inet::ieee80211::BlockAckRecord::acknowledgmentState protected
Referenced by blockAckPolicyFrameReceived(), getAckState(), and removeAckStates().
originatorAddress
MacAddress inet::ieee80211::BlockAckRecord::originatorAddress = MacAddress::UNSPECIFIED_ADDRESS protected
tid
Tid inet::ieee80211::BlockAckRecord::tid = -1 protected
The documentation for this class was generated from the following files:
BlockAckRecord.h
BlockAckRecord.cc