INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211ModeTagBase Class Reference
inet::physicallayer::Ieee80211ModeTagBase Class Reference
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:18 by opp_msgtool.
#include <Ieee80211Tag_m.h>
Public Member Functions
Ieee80211ModeTagBase ()
Ieee80211ModeTagBase (const Ieee80211ModeTagBase &other)
virtual ~Ieee80211ModeTagBase ()
Ieee80211ModeTagBase & operator= (const Ieee80211ModeTagBase &other)
virtual Ieee80211ModeTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const IIeee80211Mode * getMode () const
virtual void setMode (const IIeee80211Mode *mode)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ieee80211ModeTagBase &)=delete
Protected Attributes
const IIeee80211Mode * mode = nullptr
Private Member Functions
void copy (const Ieee80211ModeTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:18 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class Ieee80211ModeTagBase extends TagBase
{
    const IIeee80211Mode *mode; // IEEE 802.11 transmission mode
}
Constructor & Destructor Documentation
Ieee80211ModeTagBase() [1/2]
inet::physicallayer::Ieee80211ModeTagBase::Ieee80211ModeTagBase ()
Ieee80211ModeTagBase() [2/2]
inet::physicallayer::Ieee80211ModeTagBase::Ieee80211ModeTagBase (const Ieee80211ModeTagBase & other)
~Ieee80211ModeTagBase()
virtual inet::physicallayer::Ieee80211ModeTagBase::~Ieee80211ModeTagBase () virtual
Member Function Documentation
copy()
void inet::physicallayer::Ieee80211ModeTagBase::copy (const Ieee80211ModeTagBase & other) private
dup()
virtual Ieee80211ModeTagBase* inet::physicallayer::Ieee80211ModeTagBase::dup () const inline override virtual
Reimplemented in inet::physicallayer::Ieee80211ModeInd, and inet::physicallayer::Ieee80211ModeReq.
 {return new Ieee80211ModeTagBase(*this);}
getMode()
virtual const IIeee80211Mode* inet::physicallayer::Ieee80211ModeTagBase::getMode () const virtual
Referenced by inet::ieee80211::RateSelection::getMode(), and inet::ieee80211::QosRateSelection::getMode().
operator=()
Ieee80211ModeTagBase& inet::physicallayer::Ieee80211ModeTagBase::operator= (const Ieee80211ModeTagBase & other)
operator==()
bool inet::physicallayer::Ieee80211ModeTagBase::operator== (const Ieee80211ModeTagBase &) protected delete
parsimPack()
virtual void inet::physicallayer::Ieee80211ModeTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::physicallayer::Ieee80211ModeInd, and inet::physicallayer::Ieee80211ModeReq.
Referenced by inet::physicallayer::doParsimPacking().
parsimUnpack()
virtual void inet::physicallayer::Ieee80211ModeTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::physicallayer::Ieee80211ModeInd, and inet::physicallayer::Ieee80211ModeReq.
Referenced by inet::physicallayer::doParsimUnpacking().
setMode()
virtual void inet::physicallayer::Ieee80211ModeTagBase::setMode (const IIeee80211Mode * mode) virtual
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
Member Data Documentation
mode
const IIeee80211Mode* inet::physicallayer::Ieee80211ModeTagBase::mode = nullptr protected
The documentation for this class was generated from the following file:
Ieee80211Tag_m.h