INET Framework for OMNeT++/OMNEST: inet::queueing::PacketSourceBase Class Reference
inet::queueing::PacketSourceBase Class Reference
#include <PacketSourceBase.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual const char * createPacketName (const Ptr< const Chunk > &data) const
virtual Ptr< Chunk > createPacketContent () const
virtual Packet * createPacket ()
virtual const cModule * findContainingApplication () const
virtual const cModule * getContainingApplication () const
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
const char * packetNameFormat = nullptr
const char * packetRepresentation = nullptr
cPar * packetLengthParameter = nullptr
cPar * packetDataParameter = nullptr
bool attachCreationTimeTag = false
bool attachIdentityTag = false
bool attachDirectionTag = false
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
virtual bool supportsPacketPushing (cGate *gate) const =0
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const =0
Returns true if the processor supports pulling packets at the given gate.
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
createPacket()
Packet * inet::queueing::PacketSourceBase::createPacket () protected virtual
 {
     auto packetContent = createPacketContent();
     if (attachCreationTimeTag)
         packetContent->addTag<CreationTimeTag>()->setCreationTime(simTime());
     if (attachIdentityTag) {
         auto identityStart = IdentityTag::getNextIdentityStart(packetContent->getChunkLength());
         packetContent->addTag<IdentityTag>()->setIdentityStart(identityStart);
     }
     auto packetName = createPacketName(packetContent);
     auto packet = new Packet(packetName, packetContent);
     if (attachDirectionTag)
         packet->addTagIfAbsent<DirectionTag>()->setDirection(DIRECTION_OUTBOUND);
     numProcessedPackets++;
     processedTotalLength += packet->getDataLength();
     emit(packetCreatedSignal, packet);
     return packet;
 }
Referenced by inet::queueing::PassivePacketSource::canPullPacket(), inet::queueing::ActivePacketSource::producePacket(), and inet::queueing::PassivePacketSource::providePacket().
createPacketContent()
Ptr< Chunk > inet::queueing::PacketSourceBase::createPacketContent () const protected virtual
 {
     auto packetLength = b(packetLengthParameter->intValue());
     if (!strcmp(packetRepresentation, "bitCount")) {
         int packetData = packetDataParameter->intValue();
         return packetData == -1 ? makeShared<BitCountChunk>(packetLength) : makeShared<BitCountChunk>(packetLength, packetData);
     }
     else if (!strcmp(packetRepresentation, "bits")) {
         static int total = 0;
         const auto& packetContent = makeShared<BitsChunk>();
         std::vector<bool> bits;
         bits.resize(b(packetLength).get());
         for (int i = 0; i < (int)bits.size(); i++) {
             int packetData = packetDataParameter->intValue();
             bits[i] = packetData == -1 ? (total + i) % 2 == 0 : packetData;
         }
         total += bits.size();
         packetContent->setBits(bits);
         return packetContent;
     }
     else if (!strcmp(packetRepresentation, "byteCount")) {
         int packetData = packetDataParameter->intValue();
         return packetData == -1 ? makeShared<ByteCountChunk>(packetLength) : makeShared<ByteCountChunk>(packetLength, packetData);
     }
     else if (!strcmp(packetRepresentation, "bytes")) {
         static int total = 0;
         const auto& packetContent = makeShared<BytesChunk>();
         std::vector<uint8_t> bytes;
         bytes.resize(B(packetLength).get());
         for (int i = 0; i < (int)bytes.size(); i++) {
             int packetData = packetDataParameter->intValue();
             bytes[i] = packetData == -1 ? (total + i) % 256 : packetData;
         }
         total += bytes.size();
         packetContent->setBytes(bytes);
         return packetContent;
     }
     else if (!strcmp(packetRepresentation, "applicationPacket")) {
         const auto& packetContent = makeShared<ApplicationPacket>();
         packetContent->setChunkLength(B(packetLength));
         packetContent->setSequenceNumber(numProcessedPackets);
         return packetContent;
     }
     else
         throw cRuntimeError("Unknown representation");
 }
Referenced by createPacket().
createPacketName()
const char * inet::queueing::PacketSourceBase::createPacketName (const Ptr< const Chunk > & data) const protected virtual
 {
     return StringFormat::formatString(packetNameFormat, [&] (char directive) {
         static std::string result;
         switch (directive) {
             case 'a': {
                 auto application = findContainingApplication();
                 if (application != nullptr)
                     result = application->getDisplayName() != nullptr ? application->getDisplayName() : application->getFullName();
                 else
                     result = getDisplayName() != nullptr ? getDisplayName() :  getFullName();
                 break;
             }
             case 'n':
                 result = getDisplayName() != nullptr ? getDisplayName() : getFullName();
                 break;
             case 'm': {
                 auto application = getContainingApplication();
                 result = application->getDisplayName() != nullptr ? application->getDisplayName() : application->getFullName();
                 break;
             }
             case 'M': {
                 auto networkNode = getContainingNode(this);
                 result = networkNode->getDisplayName() != nullptr ? networkNode->getDisplayName() : networkNode->getFullName();
                 break;
             }
             case 'p':
                 result = getFullPath();
                 break;
             case 'h':
                 result = getContainingApplication()->getFullPath();
                 break;
             case 'H':
                 result = getContainingNode(this)->getFullPath();
                 break;
             case 'c':
                 result = std::to_string(numProcessedPackets);
                 break;
             case 'l':
                 result = data->getChunkLength().str();
                 break;
             case 'd':
                 if (auto byteCountChunk = dynamicPtrCast<const ByteCountChunk>(data))
                     result = std::to_string(byteCountChunk->getData());
                 else if (auto bitCountChunk = dynamicPtrCast<const BitCountChunk>(data))
                     result = std::to_string(bitCountChunk->getData());
                 break;
             case 't':
                 result = simTime().str();
                 break;
             case 'e':
                 result = std::to_string(getSimulation()->getEventNumber());
                 break;
             default:
                 throw cRuntimeError("Unknown directive: %c", directive);
         }
         return result.c_str();
     });
 }
Referenced by createPacket().
findContainingApplication()
const cModule * inet::queueing::PacketSourceBase::findContainingApplication () const protected virtual
 {
     for (const cModule *module = this; module != nullptr; module = module->getParentModule()) {
         if (isApplication(module))
             return module;
     }
     return nullptr;
 }
Referenced by createPacketName(), and getContainingApplication().
getContainingApplication()
const cModule * inet::queueing::PacketSourceBase::getContainingApplication () const protected virtual
 {
     auto application = findContainingApplication();
     if (application == nullptr)
         throw cRuntimeError("Application not found");
     else
         return application;
 }
Referenced by createPacketName().
initialize()
void inet::queueing::PacketSourceBase::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
Reimplemented in inet::queueing::PassivePacketSource, inet::queueing::PassivePacketSourceBase, inet::queueing::ActivePacketSource, inet::queueing::ActivePacketSourceBase, and inet::queueing::PcapFilePacketProducer.
 {
     PacketProcessorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         packetNameFormat = par("packetNameFormat");
         packetRepresentation = par("packetRepresentation");
         packetLengthParameter = &par("packetLength");
         packetDataParameter = &par("packetData");
         attachCreationTimeTag = par("attachCreationTimeTag");
         attachIdentityTag = par("attachIdentityTag");
         attachDirectionTag = par("attachDirectionTag");
     }
 }
Referenced by inet::queueing::ActivePacketSourceBase::initialize(), and inet::queueing::PassivePacketSourceBase::initialize().
Member Data Documentation
attachCreationTimeTag
bool inet::queueing::PacketSourceBase::attachCreationTimeTag = false protected
Referenced by createPacket(), and initialize().
attachDirectionTag
bool inet::queueing::PacketSourceBase::attachDirectionTag = false protected
Referenced by createPacket(), and initialize().
attachIdentityTag
bool inet::queueing::PacketSourceBase::attachIdentityTag = false protected
Referenced by createPacket(), and initialize().
packetDataParameter
cPar* inet::queueing::PacketSourceBase::packetDataParameter = nullptr protected
Referenced by createPacketContent(), and initialize().
packetLengthParameter
cPar* inet::queueing::PacketSourceBase::packetLengthParameter = nullptr protected
Referenced by createPacketContent(), and initialize().
packetNameFormat
const char* inet::queueing::PacketSourceBase::packetNameFormat = nullptr protected
Referenced by createPacketName(), and initialize().
packetRepresentation
const char* inet::queueing::PacketSourceBase::packetRepresentation = nullptr protected
Referenced by createPacketContent(), and initialize().
The documentation for this class was generated from the following files:
PacketSourceBase.h
PacketSourceBase.cc