INET Framework for OMNeT++/OMNEST: inet::UdpSocket::ICallback Class Reference
inet::UdpSocket::ICallback Class Reference abstract
#include <UdpSocket.h>
Public Member Functions
virtual ~ICallback ()
virtual void socketDataArrived (UdpSocket *socket, Packet *packet)=0
Notifies about data arrival, packet ownership is transferred to the callee.
virtual void socketErrorArrived (UdpSocket *socket, Indication *indication)=0
Notifies about error indication arrival, indication ownership is transferred to the callee.
virtual void socketClosed (UdpSocket *socket)=0
Notifies about socket closed, indication ownership is transferred to the callee.
Constructor & Destructor Documentation
~ICallback()
virtual inet::UdpSocket::ICallback::~ICallback () inline virtual
 {}
Member Function Documentation
socketClosed()
virtual void inet::UdpSocket::ICallback::socketClosed (UdpSocket * socket) pure virtual
Notifies about socket closed, indication ownership is transferred to the callee.
Implemented in inet::Ldp, inet::aodv::Aodv, inet::DhcpClient, inet::DhcpServer, inet::SimpleVoipReceiver, inet::UdpBasicBurst, inet::UdpVideoStreamServer, inet::UdpBasicApp, inet::VoipStreamReceiver, inet::UdpSink, inet::UdpVideoStreamClient, inet::TunnelApp, inet::UdpEchoApp, and inet::UdpSocketIo.
Referenced by inet::UdpSocket::processMessage().
socketDataArrived()
virtual void inet::UdpSocket::ICallback::socketDataArrived (UdpSocket * socket, Packet * packet) pure virtual
Notifies about data arrival, packet ownership is transferred to the callee.
Implemented in inet::Ldp, inet::aodv::Aodv, inet::DhcpClient, inet::DhcpServer, inet::SimpleVoipReceiver, inet::UdpBasicBurst, inet::UdpVideoStreamServer, inet::UdpBasicApp, inet::VoipStreamReceiver, inet::UdpSink, inet::UdpVideoStreamClient, inet::TunnelApp, inet::UdpEchoApp, and inet::UdpSocketIo.
Referenced by inet::UdpSocket::processMessage().
socketErrorArrived()
virtual void inet::UdpSocket::ICallback::socketErrorArrived (UdpSocket * socket, Indication * indication) pure virtual
Notifies about error indication arrival, indication ownership is transferred to the callee.
Implemented in inet::Ldp, inet::aodv::Aodv, inet::DhcpClient, inet::DhcpServer, inet::SimpleVoipReceiver, inet::UdpBasicBurst, inet::UdpVideoStreamServer, inet::UdpBasicApp, inet::VoipStreamReceiver, inet::UdpSink, inet::UdpVideoStreamClient, inet::TunnelApp, inet::UdpEchoApp, and inet::UdpSocketIo.
Referenced by inet::UdpSocket::processMessage().
The documentation for this class was generated from the following file:
UdpSocket.h