INET Framework for OMNeT++/OMNEST: inet::Ipv4MulticastRoute Class Reference
inet::Ipv4MulticastRoute Class Reference
Ipv4 multicast route in IIpv4RoutingTable.
#include <Ipv4Route.h>
Public Types
enum {
F_ORIGIN, F_ORIGINMASK, F_MULTICASTGROUP, F_IN,
F_OUT, F_SOURCE, F_METRIC, F_LAST
}
Public Types inherited from inet::IMulticastRoute
enum SourceType { MANUAL, DVMRP, PIM_DM, PIM_SM }
Specifies where the route comes from.
typedef std::vector< OutInterface * > OutInterfaceVector
Public Member Functions
Ipv4MulticastRoute ()
virtual ~Ipv4MulticastRoute ()
virtual std::string str () const override
virtual std::string detailedInfo () const
virtual void setRoutingTable (IIpv4RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
IIpv4RoutingTable * getRoutingTable () const
virtual bool isValid () const
test validity of route entry, e.g.
virtual bool matches (const Ipv4Address &origin, const Ipv4Address &group) const
virtual void setOrigin (Ipv4Address _origin)
virtual void setOriginNetmask (Ipv4Address _netmask)
virtual void setMulticastGroup (Ipv4Address _group)
virtual void setInInterface (InInterface *_inInterface) override
virtual void clearOutInterfaces () override
virtual void addOutInterface (OutInterface *outInterface) override
virtual bool removeOutInterface (const NetworkInterface *ie) override
virtual void removeOutInterface (unsigned int i) override
virtual void setSourceType (SourceType _source) override
virtual void setMetric (int _metric) override
Ipv4Address getOrigin () const
Source address prefix to match.
Ipv4Address getOriginNetmask () const
Represents length of prefix to match.
Ipv4Address getMulticastGroup () const
Multicast group address.
InInterface * getInInterface () const
In interface.
unsigned int getNumOutInterfaces () const
Number of out interfaces.
OutInterface * getOutInterface (unsigned int k) const
The kth out interface.
SourceType getSourceType () const override
Source of route.
int getMetric () const override
"Cost" to reach the destination
void setSource (cObject *_source) override
cObject * getSource () const override
Source of route.
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setEnabled (bool enabled) override
virtual void setOrigin (const L3Address &origin) override
virtual void setPrefixLength (int len) override
virtual void setMulticastGroup (const L3Address &group) override
virtual bool isEnabled () const override
Disabled entries are ignored by routing until the became enabled again.
virtual bool isExpired () const override
Expired entries are ignored by routing, and may be periodically purged.
virtual L3Address getOriginAsGeneric () const override
Source address prefix to match.
virtual int getPrefixLength () const override
Prefix length to match.
virtual L3Address getMulticastGroupAsGeneric () const override
Multicast group address.
Public Member Functions inherited from inet::IMulticastRoute
virtual ~IMulticastRoute ()
virtual void setInInterface (InInterface *_inInterface)=0
virtual void setSourceType (SourceType type)=0
Protected Member Functions
void changed (int fieldCode)
Private Member Functions
Ipv4MulticastRoute (const Ipv4MulticastRoute &obj)
Ipv4MulticastRoute & operator= (const Ipv4MulticastRoute &obj)
Private Attributes
IIpv4RoutingTable * rt
the routing table in which this route is inserted, or nullptr
Ipv4Address origin
Source network.
Ipv4Address originNetmask
Source network mask.
Ipv4Address group
Multicast group, if unspecified then matches any.
InInterface * inInterface
In interface (upstream)
OutInterfaceVector outInterfaces
Out interfaces (downstream)
SourceType sourceType
manual, routing prot, etc.
cObject * source
Object identifying the source.
int metric
Metric ("cost" to reach the source)
Additional Inherited Members
Static Public Member Functions inherited from inet::IMulticastRoute
static const char * sourceTypeName (SourceType sourceType)
Detailed Description
Ipv4 multicast route in IIpv4RoutingTable.
Multicast routing protocols may extend this class to store protocol specific fields.
Multicast datagrams are forwarded along the edges of a multicast tree. The tree might depend on the multicast group and the source (origin) of the multicast datagram.
The forwarding algorithm chooses the route according the to origin (source address) and multicast group (destination address) of the received datagram. The route might specify a prefix of the origin and a multicast group to be matched.
Then the forwarding algorithm copies the datagrams arrived on the parent (upstream) interface to the child interfaces (downstream). If there are no downstream routers on a child interface (i.e. it is a leaf in the multicast routing tree), then the datagram is forwarded only if there are listeners of the multicast group on that link (TRPB routing).
See also
IIpv4RoutingTable, Ipv4RoutingTable
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
F_ORIGIN
F_ORIGINMASK
F_MULTICASTGROUP
F_IN
F_OUT
F_SOURCE
F_METRIC
F_LAST
 { F_ORIGIN, F_ORIGINMASK, F_MULTICASTGROUP, F_IN, F_OUT, F_SOURCE, F_METRIC, F_LAST };
Constructor & Destructor Documentation
Ipv4MulticastRoute() [1/2]
inet::Ipv4MulticastRoute::Ipv4MulticastRoute (const Ipv4MulticastRoute & obj) private
Ipv4MulticastRoute() [2/2]
inet::Ipv4MulticastRoute::Ipv4MulticastRoute () inline
 : rt(nullptr), inInterface(nullptr), sourceType(MANUAL), source(nullptr), metric(0) {}
~Ipv4MulticastRoute()
inet::Ipv4MulticastRoute::~Ipv4MulticastRoute () virtual
 {
     delete inInterface;
     for (auto& elem : outInterfaces)
         delete elem;
     outInterfaces.clear();
 }
Member Function Documentation
addOutInterface()
void inet::Ipv4MulticastRoute::addOutInterface (OutInterface * outInterface) override virtual
Implements inet::IMulticastRoute.
 {
     ASSERT(outInterface);
     auto it = outInterfaces.begin();
     for (; it != outInterfaces.end(); ++it) {
         if ((*it)->getInterface() == outInterface->getInterface()) {
             delete *it;
             *it = outInterface;
             changed(F_OUT);
             return;
         }
     }
     outInterfaces.push_back(outInterface);
     changed(F_OUT);
 }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), inet::PimDm::multicastReceiverAdded(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::PimDm::rpfInterfaceHasChanged(), and inet::PimDm::unroutableMulticastPacketArrived().
changed()
void inet::Ipv4MulticastRoute::changed (int fieldCode) protected
 {
     if (rt)
         rt->multicastRouteChanged(this, fieldCode);
 }
Referenced by addOutInterface(), clearOutInterfaces(), removeOutInterface(), and setInInterface().
clearOutInterfaces()
void inet::Ipv4MulticastRoute::clearOutInterfaces () override virtual
Implements inet::IMulticastRoute.
 {
     if (!outInterfaces.empty()) {
         for (auto& elem : outInterfaces)
             delete elem;
         outInterfaces.clear();
         changed(F_OUT);
     }
 }
detailedInfo()
std::string inet::Ipv4MulticastRoute::detailedInfo () const virtual
 {
     return str();
 }
getInInterface()
InInterface* inet::Ipv4MulticastRoute::getInInterface () const inline
In interface.
 { return inInterface; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4RoutingTable::deleteInterfaceRoutes(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::Ipv4RoutingTable::printMulticastRoutingTable(), inet::PimDm::receiveSignal(), and inet::PimDm::rpfInterfaceHasChanged().
getMetric()
int inet::Ipv4MulticastRoute::getMetric () const inline override virtual
"Cost" to reach the destination
Implements inet::IMulticastRoute.
 { return metric; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ipv4RoutingTable::multicastRouteLessThan(), and inet::Ipv4RoutingTable::printMulticastRoutingTable().
getMulticastGroup()
Ipv4Address inet::Ipv4MulticastRoute::getMulticastGroup () const inline
Multicast group address.
 { return group; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::PimDm::findIpv4MulticastRoute(), inet::PimSm::findIpv4Route(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), inet::Ipv4RoutingTable::multicastRouteLessThan(), inet::Ipv4RoutingTable::printMulticastRoutingTable(), and inet::PimDm::rpfInterfaceHasChanged().
getMulticastGroupAsGeneric()
virtual L3Address inet::Ipv4MulticastRoute::getMulticastGroupAsGeneric () const inline override virtual
Multicast group address.
Implements inet::IMulticastRoute.
 { return getMulticastGroup(); }
getNumOutInterfaces()
unsigned int inet::Ipv4MulticastRoute::getNumOutInterfaces () const inline
Number of out interfaces.
 { return outInterfaces.size(); }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), and inet::Ipv4RoutingTable::printMulticastRoutingTable().
getOrigin()
Ipv4Address inet::Ipv4MulticastRoute::getOrigin () const inline
Source address prefix to match.
 { return origin; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::PimDm::findIpv4MulticastRoute(), inet::PimSm::findIpv4Route(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), inet::Ipv4RoutingTable::multicastRouteLessThan(), inet::Ipv4RoutingTable::printMulticastRoutingTable(), inet::PimDm::receiveSignal(), and inet::PimDm::rpfInterfaceHasChanged().
getOriginAsGeneric()
virtual L3Address inet::Ipv4MulticastRoute::getOriginAsGeneric () const inline override virtual
Source address prefix to match.
Implements inet::IMulticastRoute.
 { return getOrigin(); }
getOriginNetmask()
Ipv4Address inet::Ipv4MulticastRoute::getOriginNetmask () const inline
Represents length of prefix to match.
 { return originNetmask; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::Ipv4RoutingTable::multicastRouteLessThan(), and inet::Ipv4RoutingTable::printMulticastRoutingTable().
getOutInterface()
OutInterface* inet::Ipv4MulticastRoute::getOutInterface (unsigned int k) const inline
The kth out interface.
 { return outInterfaces.at(k); }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), and inet::Ipv4RoutingTable::printMulticastRoutingTable().
getPrefixLength()
virtual int inet::Ipv4MulticastRoute::getPrefixLength () const inline override virtual
Prefix length to match.
Implements inet::IMulticastRoute.
 { return getOriginNetmask().getNetmaskLength(); } // TODO inconsistent naming
getRoutingTable()
IIpv4RoutingTable* inet::Ipv4MulticastRoute::getRoutingTable () const inline
 { return rt; }
Referenced by inet::Ipv4RoutingTable::deleteInterfaceRoutes(), inet::Ipv4RoutingTable::deleteMulticastRoute(), getRoutingTableAsGeneric(), inet::Ipv4RoutingTable::purge(), and inet::Ipv4RoutingTable::removeMulticastRoute().
getRoutingTableAsGeneric()
IRoutingTable * inet::Ipv4MulticastRoute::getRoutingTableAsGeneric () const override virtual
The routing table in which this route is inserted, or nullptr.
Implements inet::IMulticastRoute.
 {
     return getRoutingTable();
 }
getSource()
cObject* inet::Ipv4MulticastRoute::getSource () const inline override virtual
Source of route.
Implements inet::IMulticastRoute.
 { return source; }
Referenced by inet::PimDm::clearRoutes(), inet::PimSm::clearRoutes(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimDm::findIpv4MulticastRoute(), inet::PimSm::findIpv4Route(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), and inet::PimDm::receiveSignal().
getSourceType()
SourceType inet::Ipv4MulticastRoute::getSourceType () const inline override virtual
Source of route.
MANUAL (read from file), from routing protocol, etc
Implements inet::IMulticastRoute.
 { return sourceType; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable().
isEnabled()
virtual bool inet::Ipv4MulticastRoute::isEnabled () const inline override virtual
Disabled entries are ignored by routing until the became enabled again.
Implements inet::IMulticastRoute.
 { return true; /*TODO isEnabled();*/ }
isExpired()
virtual bool inet::Ipv4MulticastRoute::isExpired () const inline override virtual
Expired entries are ignored by routing, and may be periodically purged.
Implements inet::IMulticastRoute.
 { return !isValid(); } // TODO rename Ipv4 method
isValid()
virtual bool inet::Ipv4MulticastRoute::isValid () const inline virtual
test validity of route entry, e.g.
check expiry
 { return true; }
Referenced by inet::Ipv4RoutingTable::purge().
matches()
virtual bool inet::Ipv4MulticastRoute::matches (const Ipv4Address & origin, const Ipv4Address & group) const inline virtual
     {
         return (this->group.isUnspecified() || this->group == group) &&
                Ipv4Address::maskedAddrAreEqual(origin, this->origin, this->originNetmask);
     }
operator=()
Ipv4MulticastRoute& inet::Ipv4MulticastRoute::operator= (const Ipv4MulticastRoute & obj) private
removeOutInterface() [1/2]
bool inet::Ipv4MulticastRoute::removeOutInterface (const NetworkInterface * ie) override virtual
Implements inet::IMulticastRoute.
 {
     for (auto it = outInterfaces.begin(); it != outInterfaces.end(); ++it) {
         if ((*it)->getInterface() == ie) {
             delete *it;
             outInterfaces.erase(it);
             changed(F_OUT);
             return true;
         }
     }
     return false;
 }
Referenced by inet::Ipv4RoutingTable::deleteInterfaceRoutes(), inet::PimSm::Route::removeDownstreamInterface(), and inet::PimDm::rpfInterfaceHasChanged().
removeOutInterface() [2/2]
void inet::Ipv4MulticastRoute::removeOutInterface (unsigned int i) override virtual
Implements inet::IMulticastRoute.
 {
     OutInterface *outInterface = outInterfaces.at(i);
     delete outInterface;
     outInterfaces.erase(outInterfaces.begin() + i);
     changed(F_OUT);
 }
setEnabled()
virtual void inet::Ipv4MulticastRoute::setEnabled (bool enabled) inline override virtual
Implements inet::IMulticastRoute.
 { /*TODO setEnabled(enabled);*/ }
setInInterface()
void inet::Ipv4MulticastRoute::setInInterface (InInterface * _inInterface) override virtual
 {
     if (inInterface != _inInterface) {
         delete inInterface;
         inInterface = _inInterface;
         changed(F_IN);
     }
 }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::PimDm::rpfInterfaceHasChanged(), and inet::PimDm::unroutableMulticastPacketArrived().
setMetric()
virtual void inet::Ipv4MulticastRoute::setMetric (int _metric) inline override virtual
Implements inet::IMulticastRoute.
 { if (metric != _metric) { metric = _metric; changed(F_METRIC); } }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), and inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration().
setMulticastGroup() [1/2]
virtual void inet::Ipv4MulticastRoute::setMulticastGroup (const L3Address & group) inline override virtual
Implements inet::IMulticastRoute.
 { setMulticastGroup(group.toIpv4()); }
Referenced by setMulticastGroup().
setMulticastGroup() [2/2]
virtual void inet::Ipv4MulticastRoute::setMulticastGroup (Ipv4Address _group) inline virtual
 { if (group != _group) { group = _group; changed(F_MULTICASTGROUP); } }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), and inet::PimDm::unroutableMulticastPacketArrived().
setOrigin() [1/2]
virtual void inet::Ipv4MulticastRoute::setOrigin (const L3Address & origin) inline override virtual
Implements inet::IMulticastRoute.
 { setOrigin(origin.toIpv4()); }
Referenced by setOrigin().
setOrigin() [2/2]
virtual void inet::Ipv4MulticastRoute::setOrigin (Ipv4Address _origin) inline virtual
 { if (origin != _origin) { origin = _origin; changed(F_ORIGIN); } }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), and inet::PimDm::unroutableMulticastPacketArrived().
setOriginNetmask()
virtual void inet::Ipv4MulticastRoute::setOriginNetmask (Ipv4Address _netmask) inline virtual
 { if (originNetmask != _netmask) { originNetmask = _netmask; changed(F_ORIGINMASK); } }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), and inet::PimDm::unroutableMulticastPacketArrived().
setPrefixLength()
virtual void inet::Ipv4MulticastRoute::setPrefixLength (int len) inline override virtual
Implements inet::IMulticastRoute.
 { setOriginNetmask(Ipv4Address::makeNetmask(len)); } // TODO inconsistent naming
setRoutingTable()
virtual void inet::Ipv4MulticastRoute::setRoutingTable (IIpv4RoutingTable * rt) inline virtual
To be called by the routing table when this route is added or removed from it.
 { this->rt = rt; }
Referenced by inet::Ipv4RoutingTable::internalAddMulticastRoute(), and inet::Ipv4RoutingTable::removeMulticastRoute().
setSource()
void inet::Ipv4MulticastRoute::setSource (cObject * _source) inline override virtual
Implements inet::IMulticastRoute.
 { source = _source; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), and inet::PimDm::unroutableMulticastPacketArrived().
setSourceType()
virtual void inet::Ipv4MulticastRoute::setSourceType (SourceType _source) inline override virtual
 { if (sourceType != _source) { sourceType = _source; changed(F_SOURCE); } }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::PimSm::createIpv4Route(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), and inet::PimDm::unroutableMulticastPacketArrived().
str()
std::string inet::Ipv4MulticastRoute::str () const override virtual
 {
     std::stringstream out;
     out << "origin:";
     if (origin.isUnspecified())
         out << "*  ";
     else
         out << origin << "  ";
     out << "mask:";
     if (originNetmask.isUnspecified())
         out << "*  ";
     else
         out << originNetmask << "  ";
     out << "group:";
     if (group.isUnspecified())
         out << "*  ";
     else
         out << group << "  ";
     out << "metric:" << metric << " ";
     out << "in:";
     if (!inInterface)
         out << "*  ";
     else
         out << inInterface->getInterface()->getInterfaceName() << "  ";
     out << "out:";
     bool first = true;
     for (auto& elem : outInterfaces) {
         if (!first)
             out << ",";
         if (elem->isEnabled()) {
             out << elem->getInterface()->getInterfaceName();
             first = false;
         }
     }
     out << " " << IMulticastRoute::sourceTypeName(sourceType);
     return out.str();
 }
Referenced by detailedInfo().
Member Data Documentation
group
Ipv4Address inet::Ipv4MulticastRoute::group private
Multicast group, if unspecified then matches any.
Referenced by str().
inInterface
InInterface* inet::Ipv4MulticastRoute::inInterface private
In interface (upstream)
Referenced by setInInterface(), str(), and ~Ipv4MulticastRoute().
metric
int inet::Ipv4MulticastRoute::metric private
Metric ("cost" to reach the source)
Referenced by str().
origin
Ipv4Address inet::Ipv4MulticastRoute::origin private
Source network.
Referenced by str().
originNetmask
Ipv4Address inet::Ipv4MulticastRoute::originNetmask private
Source network mask.
Referenced by str().
outInterfaces
OutInterfaceVector inet::Ipv4MulticastRoute::outInterfaces private
Out interfaces (downstream)
Referenced by addOutInterface(), clearOutInterfaces(), removeOutInterface(), str(), and ~Ipv4MulticastRoute().
rt
IIpv4RoutingTable* inet::Ipv4MulticastRoute::rt private
the routing table in which this route is inserted, or nullptr
Referenced by changed().
source
cObject* inet::Ipv4MulticastRoute::source private
Object identifying the source.
sourceType
SourceType inet::Ipv4MulticastRoute::sourceType private
manual, routing prot, etc.
Referenced by str().
The documentation for this class was generated from the following files:
Ipv4Route.h
Ipv4Route.cc