INET Framework for OMNeT++/OMNEST: inet::physicallayer::IIeee80211Mode Class Reference
inet::physicallayer::IIeee80211Mode Class Reference abstract
#include <IIeee80211Mode.h>
Public Member Functions
virtual int getLegacyCwMin () const =0
virtual int getLegacyCwMax () const =0
virtual const char * getName () const =0
virtual const IIeee80211PreambleMode * getPreambleMode () const =0
virtual const IIeee80211HeaderMode * getHeaderMode () const =0
virtual const IIeee80211DataMode * getDataMode () const =0
IIeee80211PreambleMode * _getPreambleMode () const
IIeee80211HeaderMode * _getHeaderMode () const
IIeee80211DataMode * _getDataMode () const
virtual const simtime_t getDuration (b dataLength) const =0
virtual const simtime_t getSlotTime () const =0
virtual const simtime_t getSifsTime () const =0
virtual const simtime_t getRifsTime () const =0
virtual const simtime_t getCcaTime () const =0
virtual const simtime_t getPhyRxStartDelay () const =0
virtual const simtime_t getRxTxTurnaroundTime () const =0
virtual const simtime_t getPreambleLength () const =0
virtual const simtime_t getPlcpHeaderLength () const =0
virtual int getMpduMaxLength () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
_getDataMode()
IIeee80211DataMode* inet::physicallayer::IIeee80211Mode::_getDataMode () const inline
 { return const_cast<IIeee80211DataMode *>(getDataMode()); }
_getHeaderMode()
IIeee80211HeaderMode* inet::physicallayer::IIeee80211Mode::_getHeaderMode () const inline
 { return const_cast<IIeee80211HeaderMode *>(getHeaderMode()); }
_getPreambleMode()
IIeee80211PreambleMode* inet::physicallayer::IIeee80211Mode::_getPreambleMode () const inline
 { return const_cast<IIeee80211PreambleMode *>(getPreambleMode()); }
getCcaTime()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getCcaTime () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getDataMode()
virtual const IIeee80211DataMode* inet::physicallayer::IIeee80211Mode::getDataMode () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission(), inet::physicallayer::Ieee80211ModeSet::EntryNetBitrateComparator::operator()(), inet::physicallayer::Ieee80211TransmitterBase::setMode(), inet::physicallayer::Ieee80211TransmitterBase::setModeSet(), inet::ieee80211::Dcf::transmitControlResponseFrame(), and inet::ieee80211::Hcf::transmitControlResponseFrame().
getDuration()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getDuration (b dataLength) const pure virtual
Implemented in inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, inet::physicallayer::Ieee80211DsssOfdmMode, inet::physicallayer::Ieee80211ErpOfdmMode, and inet::physicallayer::Ieee80211VhtMode.
Referenced by inet::ieee80211::RecipientAckPolicy::computeAckDuration(), inet::ieee80211::RecipientQosAckPolicy::computeAckDuration(), inet::ieee80211::RecipientQosAckPolicy::computeBasicBlockAckDuration(), inet::ieee80211::SingleProtectionMechanism::computeBlockAckReqDurationField(), inet::ieee80211::QosCtsPolicy::computeCtsDuration(), inet::ieee80211::CtsPolicy::computeCtsDuration(), inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField(), inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
getHeaderMode()
virtual const IIeee80211HeaderMode* inet::physicallayer::IIeee80211Mode::getHeaderMode () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
getLegacyCwMax()
virtual int inet::physicallayer::IIeee80211Mode::getLegacyCwMax () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getLegacyCwMin()
virtual int inet::physicallayer::IIeee80211Mode::getLegacyCwMin () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getMpduMaxLength()
virtual int inet::physicallayer::IIeee80211Mode::getMpduMaxLength () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getName()
virtual const char* inet::physicallayer::IIeee80211Mode::getName () const pure virtual
Implemented in inet::physicallayer::Ieee80211ModeBase.
getPhyRxStartDelay()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getPhyRxStartDelay () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
Referenced by inet::ieee80211::OriginatorAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getBlockAckTimeout(), inet::ieee80211::QosRtsPolicy::getCtsTimeout(), and inet::ieee80211::RtsPolicy::getCtsTimeout().
getPlcpHeaderLength()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getPlcpHeaderLength () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getPreambleLength()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getPreambleLength () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getPreambleMode()
virtual const IIeee80211PreambleMode* inet::physicallayer::IIeee80211Mode::getPreambleMode () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
getRifsTime()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getRifsTime () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, inet::physicallayer::Ieee80211DsssOfdmMode, and inet::physicallayer::Ieee80211ErpOfdmMode.
getRxTxTurnaroundTime()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getRxTxTurnaroundTime () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, and inet::physicallayer::Ieee80211DsssOfdmMode.
getSifsTime()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getSifsTime () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, inet::physicallayer::Ieee80211DsssOfdmMode, and inet::physicallayer::Ieee80211ErpOfdmMode.
getSlotTime()
virtual const simtime_t inet::physicallayer::IIeee80211Mode::getSlotTime () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtMode, inet::physicallayer::Ieee80211HtMode, inet::physicallayer::Ieee80211OfdmMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211FhssMode, inet::physicallayer::Ieee80211DsssOfdmMode, and inet::physicallayer::Ieee80211ErpOfdmMode.
The documentation for this class was generated from the following file:
IIeee80211Mode.h