INET Framework for OMNeT++/OMNEST: inet::TcpSetTimeToLiveCommand Class Reference
inet::TcpSetTimeToLiveCommand Class Reference
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:140 by opp_msgtool.
#include <TcpCommand_m.h>
Public Member Functions
TcpSetTimeToLiveCommand ()
TcpSetTimeToLiveCommand (const TcpSetTimeToLiveCommand &other)
virtual ~TcpSetTimeToLiveCommand ()
TcpSetTimeToLiveCommand & operator= (const TcpSetTimeToLiveCommand &other)
virtual TcpSetTimeToLiveCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getTtl () const
virtual void setTtl (int ttl)
Public Member Functions inherited from inet::TcpSetOptionCommand
TcpSetOptionCommand ()
TcpSetOptionCommand (const TcpSetOptionCommand &other)
virtual ~TcpSetOptionCommand ()
TcpSetOptionCommand & operator= (const TcpSetOptionCommand &other)
Public Member Functions inherited from inet::TcpCommand
TcpCommand ()
TcpCommand (const TcpCommand &other)
virtual ~TcpCommand ()
TcpCommand & operator= (const TcpCommand &other)
virtual int getUserId () const
virtual void setUserId (int userId)
Protected Member Functions
bool operator== (const TcpSetTimeToLiveCommand &)=delete
Protected Member Functions inherited from inet::TcpSetOptionCommand
bool operator== (const TcpSetOptionCommand &)=delete
Protected Member Functions inherited from inet::TcpCommand
bool operator== (const TcpCommand &)=delete
Protected Attributes
int ttl = 0
Protected Attributes inherited from inet::TcpCommand
int userId = -1
Private Member Functions
void copy (const TcpSetTimeToLiveCommand &other)
Detailed Description
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:140 by opp_msgtool.
class TcpSetTimeToLiveCommand extends TcpSetOptionCommand
{
    int ttl;
}
Constructor & Destructor Documentation
TcpSetTimeToLiveCommand() [1/2]
inet::TcpSetTimeToLiveCommand::TcpSetTimeToLiveCommand ()
TcpSetTimeToLiveCommand() [2/2]
inet::TcpSetTimeToLiveCommand::TcpSetTimeToLiveCommand (const TcpSetTimeToLiveCommand & other)
~TcpSetTimeToLiveCommand()
virtual inet::TcpSetTimeToLiveCommand::~TcpSetTimeToLiveCommand () virtual
Member Function Documentation
copy()
void inet::TcpSetTimeToLiveCommand::copy (const TcpSetTimeToLiveCommand & other) private
dup()
virtual TcpSetTimeToLiveCommand* inet::TcpSetTimeToLiveCommand::dup () const inline override virtual
Reimplemented from inet::TcpSetOptionCommand.
 {return new TcpSetTimeToLiveCommand(*this);}
getTtl()
virtual int inet::TcpSetTimeToLiveCommand::getTtl () const virtual
operator=()
TcpSetTimeToLiveCommand& inet::TcpSetTimeToLiveCommand::operator= (const TcpSetTimeToLiveCommand & other)
operator==()
bool inet::TcpSetTimeToLiveCommand::operator== (const TcpSetTimeToLiveCommand &) protected delete
parsimPack()
virtual void inet::TcpSetTimeToLiveCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::TcpSetOptionCommand.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TcpSetTimeToLiveCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::TcpSetOptionCommand.
Referenced by inet::doParsimUnpacking().
setTtl()
virtual void inet::TcpSetTimeToLiveCommand::setTtl (int ttl) virtual
Referenced by inet::TcpSocket::setTimeToLive().
Member Data Documentation
ttl
int inet::TcpSetTimeToLiveCommand::ttl = 0 protected
The documentation for this class was generated from the following file:
TcpCommand_m.h