INET Framework for OMNeT++/OMNEST: inet::tcp::TcpAlgorithm Class Reference
inet::tcp::TcpAlgorithm Class Reference abstract
Abstract base class for TCP algorithms which encapsulate all behaviour during data transfer state: flavour of congestion control, fast retransmit/recovery, selective acknowledgement etc.
#include <TcpAlgorithm.h>
Public Member Functions
TcpAlgorithm ()
Ctor.
virtual ~TcpAlgorithm ()
Virtual dtor.
void setConnection (TcpConnection *_conn)
Assign this object to a TcpConnection.
TcpStateVariables * getStateVariables ()
Creates and returns the TCP state variables.
virtual void initialize ()
Should be redefined to initialize the object: create timers, etc.
virtual void established (bool active)=0
Called when the connection is going to ESTABLISHED from SYN_SENT or SYN_RCVD.
virtual void connectionClosed ()=0
Called when the connection closes, it should cancel all running timers.
virtual void processTimer (cMessage *timer, TcpEventCode &event)=0
Place to process timers specific to this TcpAlgorithm class.
virtual void sendCommandInvoked ()=0
Called after user sent TCP_C_SEND command to us.
virtual void receivedOutOfOrderSegment ()=0
Called after receiving data which are in the window, but not at its left edge (seq != rcv_nxt).
virtual void receiveSeqChanged ()=0
Called after rcv_nxt got advanced, either because we received in-sequence data ("text" in RFC 793 lingo) or a FIN.
virtual void receivedDataAck (uint32_t firstSeqAcked)=0
Called after we received an ACK which acked some data (that is, we could advance snd_una).
virtual void receivedDuplicateAck ()=0
Called after we received a duplicate ACK (that is: ackNo == snd_una, no data in segment, segment doesn't carry window update, and also, we have unacked data).
virtual void receivedAckForDataNotYetSent (uint32_t seq)=0
Called after we received an ACK for data not yet sent.
virtual void ackSent ()=0
Called after we sent an ACK.
virtual void dataSent (uint32_t fromseq)=0
Called after we sent data.
virtual void segmentRetransmitted (uint32_t fromseq, uint32_t toseq)=0
Called after we retransmitted segment.
virtual void restartRexmitTimer ()=0
Restart REXMIT timer.
virtual void rttMeasurementCompleteUsingTS (uint32_t echoedTS)=0
Converting uint32_t echoedTS to simtime_t and calling rttMeasurementComplete() to update state vars with new measured RTT value.
virtual bool shouldMarkAck ()=0
Called before sending ACK.
virtual void processEcnInEstablished ()=0
Called before processing segment in established state.
Protected Member Functions
virtual TcpStateVariables * createStateVariables ()=0
Create state block (TCB) used by this TCP variant.
Protected Attributes
TcpConnection * conn
TcpStateVariables * state
Detailed Description
Abstract base class for TCP algorithms which encapsulate all behaviour during data transfer state: flavour of congestion control, fast retransmit/recovery, selective acknowledgement etc.
Subclasses may implement various sets and flavours of the above algorithms.
Constructor & Destructor Documentation
TcpAlgorithm()
inet::tcp::TcpAlgorithm::TcpAlgorithm () inline
Ctor.
 { state = nullptr; conn = nullptr; }
~TcpAlgorithm()
virtual inet::tcp::TcpAlgorithm::~TcpAlgorithm () inline virtual
Virtual dtor.
 {}
Member Function Documentation
ackSent()
virtual void inet::tcp::TcpAlgorithm::ackSent () pure virtual
Called after we sent an ACK.
This hook can be used to cancel the delayed-ACK timer.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::retransmitOneSegment(), inet::tcp::TcpConnection::sendAck(), inet::tcp::TcpConnection::sendData(), inet::tcp::TcpConnection::sendFin(), inet::tcp::TcpConnection::sendOneNewSegment(), inet::tcp::TcpConnection::sendProbe(), inet::tcp::TcpConnection::sendRstAck(), inet::tcp::TcpConnection::sendSegmentDuringLossRecoveryPhase(), and inet::tcp::TcpConnection::sendSynAck().
connectionClosed()
virtual void inet::tcp::TcpAlgorithm::connectionClosed () pure virtual
Called when the connection closes, it should cancel all running timers.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::stateEntered().
createStateVariables()
virtual TcpStateVariables* inet::tcp::TcpAlgorithm::createStateVariables () protected pure virtual
Create state block (TCB) used by this TCP variant.
It is expected that every TcpAlgorithm subclass will have its own state block, subclassed from TcpStateVariables. This factory method should create and return a "blank" state block of the appropriate type.
Implemented in inet::tcp::TcpVegas, inet::tcp::TcpWestwood, inet::tcp::DumbTcp, inet::tcp::DcTcp, inet::tcp::TcpNoCongestionControl, inet::tcp::TcpTahoe, inet::tcp::TcpReno, and inet::tcp::TcpNewReno.
dataSent()
virtual void inet::tcp::TcpAlgorithm::dataSent (uint32_t fromseq) pure virtual
Called after we sent data.
This hook can be used to schedule the retransmission timer, to start round-trip time measurement, etc. The argument is the seqno of the first byte sent.
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::TcpVegas, inet::tcp::DumbTcp, and inet::tcp::TcpWestwood.
Referenced by inet::tcp::TcpConnection::sendData(), inet::tcp::TcpConnection::sendOneNewSegment(), inet::tcp::TcpConnection::sendProbe(), and inet::tcp::TcpConnection::sendSegmentDuringLossRecoveryPhase().
established()
virtual void inet::tcp::TcpAlgorithm::established (bool active) pure virtual
Called when the connection is going to ESTABLISHED from SYN_SENT or SYN_RCVD.
This is a place to initialize some variables (e.g. set cwnd to the MSS learned during connection setup). If we are on the active side, here we also have to finish the 3-way connection setup procedure by sending an ACK, possibly piggybacked on data.
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::DumbTcp, and inet::tcp::TcpNoCongestionControl.
Referenced by inet::tcp::TcpConnection::processSegment1stThru8th(), and inet::tcp::TcpConnection::processSegmentInSynSent().
getStateVariables()
TcpStateVariables* inet::tcp::TcpAlgorithm::getStateVariables () inline
Creates and returns the TCP state variables.
     {
         if (!state)
             state = createStateVariables();
         return state;
     }
Referenced by inet::tcp::TcpConnection::initClonedConnection(), and inet::tcp::TcpConnection::initConnection().
initialize()
virtual void inet::tcp::TcpAlgorithm::initialize () inline virtual
Should be redefined to initialize the object: create timers, etc.
This method is necessary because the TcpConnection ptr is not available in the constructor yet.
Reimplemented in inet::tcp::TcpBaseAlg, inet::tcp::DumbTcp, inet::tcp::TcpNoCongestionControl, inet::tcp::TcpTahoeRenoFamily, and inet::tcp::DcTcp.
 {}
Referenced by inet::tcp::TcpConnection::initClonedConnection(), inet::tcp::TcpConnection::initConnection(), inet::tcp::DumbTcp::initialize(), and inet::tcp::TcpBaseAlg::initialize().
processEcnInEstablished()
virtual void inet::tcp::TcpAlgorithm::processEcnInEstablished () pure virtual
Called before processing segment in established state.
This function process ECN marks.
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::DumbTcp, and inet::tcp::DcTcp.
Referenced by inet::tcp::TcpConnection::processSegment1stThru8th().
processTimer()
virtual void inet::tcp::TcpAlgorithm::processTimer (cMessage * timer, TcpEventCode & event) pure virtual
Place to process timers specific to this TcpAlgorithm class.
TcpConnection will invoke this method on any timer (self-message) it doesn't recognize (that is, any timer other than the 2MSL, CONN-ESTAB and FIN-WAIT-2 timers).
Method may also change the event code (by default set to TCP_E_IGNORE) to cause the state transition of TCP FSM.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::processTimer().
receivedAckForDataNotYetSent()
virtual void inet::tcp::TcpAlgorithm::receivedAckForDataNotYetSent (uint32_t seq) pure virtual
Called after we received an ACK for data not yet sent.
According to RFC 793 this function should send an ACK.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::processAckInEstabEtc().
receivedDataAck()
virtual void inet::tcp::TcpAlgorithm::receivedDataAck (uint32_t firstSeqAcked) pure virtual
Called after we received an ACK which acked some data (that is, we could advance snd_una).
At this point the state variables (snd_una, snd_wnd) have already been updated. The argument firstSeqAcked is the previous snd_una value, that is, the number of bytes acked is (snd_una - firstSeqAcked). The dupack counter still reflects the old value (needed for Reno and NewReno); it'll be reset to 0 after this call returns.
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::TcpVegas, inet::tcp::DumbTcp, inet::tcp::TcpWestwood, inet::tcp::TcpNoCongestionControl, inet::tcp::TcpTahoe, inet::tcp::DcTcp, inet::tcp::TcpReno, and inet::tcp::TcpNewReno.
Referenced by inet::tcp::TcpConnection::processAckInEstabEtc(), and inet::tcp::TcpConnection::processSegment1stThru8th().
receivedDuplicateAck()
virtual void inet::tcp::TcpAlgorithm::receivedDuplicateAck () pure virtual
Called after we received a duplicate ACK (that is: ackNo == snd_una, no data in segment, segment doesn't carry window update, and also, we have unacked data).
The dupack counter got already updated when calling this method (i.e. dupacks == 1 on first duplicate ACK.)
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::TcpVegas, inet::tcp::TcpWestwood, inet::tcp::DumbTcp, inet::tcp::TcpTahoe, inet::tcp::TcpReno, and inet::tcp::TcpNewReno.
Referenced by inet::tcp::TcpConnection::processAckInEstabEtc().
receivedOutOfOrderSegment()
virtual void inet::tcp::TcpAlgorithm::receivedOutOfOrderSegment () pure virtual
Called after receiving data which are in the window, but not at its left edge (seq != rcv_nxt).
This indicates that either segments got re-ordered in the way, or one segment was lost. RFC 1122 and RFC 2001 recommend sending an immediate ACK here (Fast Retransmit relies on that).
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::processSegment1stThru8th().
receiveSeqChanged()
virtual void inet::tcp::TcpAlgorithm::receiveSeqChanged () pure virtual
Called after rcv_nxt got advanced, either because we received in-sequence data ("text" in RFC 793 lingo) or a FIN.
At this point, rcv_nxt has already been updated. This method should take care to send or schedule an ACK some time.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::processSegment1stThru8th().
restartRexmitTimer()
virtual void inet::tcp::TcpAlgorithm::restartRexmitTimer () pure virtual
Restart REXMIT timer.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::process_CLOSE(), inet::tcp::TcpConnection::sendData(), and inet::tcp::TcpConnection::sendSegmentDuringLossRecoveryPhase().
rttMeasurementCompleteUsingTS()
virtual void inet::tcp::TcpAlgorithm::rttMeasurementCompleteUsingTS (uint32_t echoedTS) pure virtual
Converting uint32_t echoedTS to simtime_t and calling rttMeasurementComplete() to update state vars with new measured RTT value.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::processAckInEstabEtc().
segmentRetransmitted()
virtual void inet::tcp::TcpAlgorithm::segmentRetransmitted (uint32_t fromseq, uint32_t toseq) pure virtual
Called after we retransmitted segment.
The argument fromseq is the seqno of the first byte sent. The argument toseq is the seqno of the last byte sent+1.
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::TcpVegas, inet::tcp::DumbTcp, and inet::tcp::TcpWestwood.
Referenced by inet::tcp::TcpConnection::retransmitData(), and inet::tcp::TcpConnection::retransmitOneSegment().
sendCommandInvoked()
virtual void inet::tcp::TcpAlgorithm::sendCommandInvoked () pure virtual
Called after user sent TCP_C_SEND command to us.
Implemented in inet::tcp::TcpBaseAlg, and inet::tcp::DumbTcp.
Referenced by inet::tcp::TcpConnection::process_SEND().
setConnection()
void inet::tcp::TcpAlgorithm::setConnection (TcpConnection * _conn) inline
Assign this object to a TcpConnection.
Its sendQueue and receiveQueue must be set already at this time, because we cache their pointers here.
 { conn = _conn; }
Referenced by inet::tcp::TcpConnection::initClonedConnection(), and inet::tcp::TcpConnection::initConnection().
shouldMarkAck()
virtual bool inet::tcp::TcpAlgorithm::shouldMarkAck () pure virtual
Called before sending ACK.
Determines whether to set ECE bit.
Implemented in inet::tcp::TcpBaseAlg, inet::tcp::DumbTcp, and inet::tcp::DcTcp.
Referenced by inet::tcp::TcpConnection::sendAck().
Member Data Documentation
conn
TcpConnection* inet::tcp::TcpAlgorithm::conn protected
Referenced by inet::tcp::DumbTcp::connectionClosed(), inet::tcp::DumbTcp::dataSent(), inet::tcp::TcpNoCongestionControl::established(), inet::tcp::DumbTcp::established(), inet::tcp::TcpBaseAlg::established(), inet::tcp::DcTcp::initialize(), inet::tcp::TcpTahoeRenoFamily::initialize(), inet::tcp::DumbTcp::initialize(), inet::tcp::TcpBaseAlg::initialize(), inet::tcp::TcpBaseAlg::processDelayedAckTimer(), inet::tcp::TcpBaseAlg::processPersistTimer(), inet::tcp::TcpNoCongestionControl::processRexmitTimer(), inet::tcp::TcpNewReno::processRexmitTimer(), inet::tcp::TcpReno::processRexmitTimer(), inet::tcp::TcpTahoe::processRexmitTimer(), inet::tcp::TcpWestwood::processRexmitTimer(), inet::tcp::TcpVegas::processRexmitTimer(), inet::tcp::TcpBaseAlg::processRexmitTimer(), inet::tcp::DumbTcp::processTimer(), inet::tcp::TcpNewReno::recalculateSlowStartThreshold(), inet::tcp::TcpReno::recalculateSlowStartThreshold(), inet::tcp::TcpTahoe::recalculateSlowStartThreshold(), inet::tcp::TcpWestwood::recalculateSlowStartThreshold(), inet::tcp::TcpVegas::recalculateSlowStartThreshold(), inet::tcp::DumbTcp::receivedAckForDataNotYetSent(), inet::tcp::TcpBaseAlg::receivedAckForDataNotYetSent(), inet::tcp::TcpNewReno::receivedDataAck(), inet::tcp::DcTcp::receivedDataAck(), inet::tcp::TcpReno::receivedDataAck(), inet::tcp::TcpTahoe::receivedDataAck(), inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::DumbTcp::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), inet::tcp::TcpBaseAlg::receivedDataAck(), inet::tcp::TcpNewReno::receivedDuplicateAck(), inet::tcp::TcpReno::receivedDuplicateAck(), inet::tcp::TcpTahoe::receivedDuplicateAck(), inet::tcp::TcpWestwood::receivedDuplicateAck(), inet::tcp::TcpVegas::receivedDuplicateAck(), inet::tcp::TcpBaseAlg::receivedDuplicateAck(), inet::tcp::DumbTcp::receivedOutOfOrderSegment(), inet::tcp::TcpBaseAlg::receivedOutOfOrderSegment(), inet::tcp::DumbTcp::receiveSeqChanged(), inet::tcp::TcpBaseAlg::receiveSeqChanged(), inet::tcp::TcpBaseAlg::rttMeasurementComplete(), inet::tcp::TcpBaseAlg::rttMeasurementCompleteUsingTS(), inet::tcp::DumbTcp::sendCommandInvoked(), inet::tcp::TcpNoCongestionControl::sendData(), inet::tcp::TcpBaseAlg::sendData(), inet::tcp::TcpBaseAlg::startRexmitTimer(), and inet::tcp::DumbTcp::~DumbTcp().
state
TcpStateVariables* inet::tcp::TcpAlgorithm::state protected
The documentation for this class was generated from the following file:
TcpAlgorithm.h