INET Framework for OMNeT++/OMNEST: inet::physicallayer::IsotropicScalarBackgroundNoise Class Reference
inet::physicallayer::IsotropicScalarBackgroundNoise Class Reference
#include <IsotropicScalarBackgroundNoise.h>
Public Member Functions
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual W getPower () const
virtual const INoise * computeNoise (const IListening *listening) const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
Protected Attributes
W power = W(NaN)
Hz bandwidth = Hz(NaN)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
computeNoise()
const INoise * inet::physicallayer::IsotropicScalarBackgroundNoise::computeNoise (const IListening * listening) const override virtual
Implements inet::physicallayer::IBackgroundNoise.
 {
     const BandListening *bandListening = check_and_cast<const BandListening *>(listening);
     simtime_t startTime = listening->getStartTime();
     simtime_t endTime = listening->getEndTime();
     Hz centerFrequency = bandListening->getCenterFrequency();
     Hz listeningBandwidth = bandListening->getBandwidth();
     if (std::isnan(bandwidth.get()))
         bandwidth = listeningBandwidth;
     else if (bandwidth != listeningBandwidth)
         throw cRuntimeError("Background noise bandwidth doesn't match listening bandwidth");
     std::map<simtime_t, W> *powerChanges = new std::map<simtime_t, W>();
     powerChanges->insert(std::pair<simtime_t, W>(startTime, power));
     powerChanges->insert(std::pair<simtime_t, W>(endTime, -power));
     return new ScalarNoise(startTime, endTime, centerFrequency, bandwidth, powerChanges);
 }
getPower()
virtual W inet::physicallayer::IsotropicScalarBackgroundNoise::getPower () const inline virtual
 { return power; }
initialize()
void inet::physicallayer::IsotropicScalarBackgroundNoise::initialize (int stage) override protected virtual
 {
     cModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         power = mW(math::dBmW2mW(par("power")));
         bandwidth = Hz(par("bandwidth"));
     }
 }
printToStream()
std::ostream & inet::physicallayer::IsotropicScalarBackgroundNoise::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "IsotropicScalarBackgroundNoise";
     if (level <= PRINT_LEVEL_DETAIL) {
         stream << EV_FIELD(power);
         stream << EV_FIELD(bandwidth);
     }
     return stream;
 }
Member Data Documentation
bandwidth
Hz inet::physicallayer::IsotropicScalarBackgroundNoise::bandwidth = Hz(NaN) mutable protected
Referenced by computeNoise(), initialize(), and printToStream().
power
W inet::physicallayer::IsotropicScalarBackgroundNoise::power = W(NaN) protected
Referenced by computeNoise(), initialize(), and printToStream().
The documentation for this class was generated from the following files:
IsotropicScalarBackgroundNoise.h
IsotropicScalarBackgroundNoise.cc