INET Framework for OMNeT++/OMNEST: inet::IRoute Class Reference
inet::IRoute Class Reference abstract
C++ interface for accessing unicast routing table entries of various protocols (IPv4, IPv6, etc) in a uniform way.
#include <IRoute.h>
Public Types
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Public Member Functions
virtual ~IRoute ()
virtual IRoutingTable * getRoutingTableAsGeneric () const =0
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest)=0
virtual void setPrefixLength (int l)=0
virtual void setNextHop (const L3Address &nextHop)=0
virtual void setInterface (NetworkInterface *ie)=0
virtual void setSource (cObject *source)=0
virtual void setSourceType (SourceType type)=0
virtual void setMetric (int metric)=0
virtual void setAdminDist (unsigned int adminDist)=0
virtual L3Address getDestinationAsGeneric () const =0
Destination address prefix to match.
virtual int getPrefixLength () const =0
Represents length of prefix to match.
virtual L3Address getNextHopAsGeneric () const =0
Next hop address.
virtual NetworkInterface * getInterface () const =0
Next hop interface.
virtual cObject * getSource () const =0
Source of route.
virtual SourceType getSourceType () const =0
Source type of the route.
virtual int getMetric () const =0
Cost to reach the destination.
virtual cObject * getProtocolData () const =0
virtual void setProtocolData (cObject *protocolData)=0
Static Public Member Functions
static const char * sourceTypeName (SourceType sourceType)
Detailed Description
C++ interface for accessing unicast routing table entries of various protocols (IPv4, IPv6, etc) in a uniform way.
See also
IRoutingTable, Ipv4Route, Ipv6Route
Member Enumeration Documentation
ChangeCodes
enum inet::IRoute::ChangeCodes
Field codes for NB_ROUTE_CHANGED notifications.
Enumerator
F_DESTINATION
F_PREFIX_LENGTH
F_NEXTHOP
F_IFACE
F_SOURCE
F_TYPE
F_ADMINDIST
F_METRIC
F_EXPIRYTIME
F_LAST
                      {
         F_DESTINATION,
         F_PREFIX_LENGTH,
         F_NEXTHOP,
         F_IFACE,
         F_SOURCE,
         F_TYPE,
         F_ADMINDIST,
         F_METRIC,
         F_EXPIRYTIME,
         F_LAST
     };
RouteAdminDist
enum inet::IRoute::RouteAdminDist
Cisco like administrative distances.
Enumerator
dDirectlyConnected
dStatic
dEIGRPSummary
dBGPExternal
dEIGRPInternal
dIGRP
dOSPF
dISIS
dRIP
dEGP
dODR
dEIGRPExternal
dBGPInternal
dDHCPlearned
dBABEL
dLISP
dUnknown
{
         dDirectlyConnected = 0,
         dStatic            = 1,
         dEIGRPSummary      = 5,
         dBGPExternal       = 20,
         dEIGRPInternal     = 90,
         dIGRP              = 100,
         dOSPF              = 110,
         dISIS              = 115,
         dRIP               = 120,
         dEGP               = 140,
         dODR               = 160,
         dEIGRPExternal     = 170,
         dBGPInternal       = 200,
         dDHCPlearned       = 254,
         dBABEL             = 125,
         dLISP              = 210,
         dUnknown           = 255
     };
SourceType
enum inet::IRoute::SourceType
Specifies where the route comes from.
Enumerator
MANUAL
manually added static route
IFACENETMASK
comes from an interface's netmask
ROUTER_ADVERTISEMENT
on-link prefix, from Router Advertisement
OWN_ADV_PREFIX
on routers: on-link prefix that the router itself advertises on the link
ICMP_REDIRECT
ICMP redirect message.
RIP
managed by the given routing protocol
OSPF
managed by the given routing protocol
BGP
managed by the given routing protocol
ZEBRA
managed by the Quagga/Zebra based model
MANET
managed by manet, search exact address
MANET2
managed by manet, search approximate address
DYMO
managed by DYMO routing
AODV
managed by AODV routing
EIGRP
LISP
BABEL
ODR
UNKNOWN
ISIS
                     {
         MANUAL,
         IFACENETMASK,
         ROUTER_ADVERTISEMENT,
         OWN_ADV_PREFIX,
         ICMP_REDIRECT,
         RIP,
         OSPF,
         BGP,
         ZEBRA,
         MANET,
         MANET2,
         DYMO,
         AODV,
         EIGRP, LISP, BABEL, ODR, UNKNOWN, ISIS
     };
Constructor & Destructor Documentation
~IRoute()
virtual inet::IRoute::~IRoute () inline virtual
 {}
Member Function Documentation
getDestinationAsGeneric()
virtual L3Address inet::IRoute::getDestinationAsGeneric () const pure virtual
Destination address prefix to match.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::expungeRoutes(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::operator<<(), inet::dymo::Dymo::processRerr(), inet::Rip::receiveSignal(), inet::RoutingTableRecorder::recordRouteChange(), inet::RipRoute::RipRoute(), inet::dymo::Dymo::sendRerrForBrokenLink(), inet::Rip::startRIPRouting(), and inet::dymo::Dymo::updateRoutes().
getInterface()
virtual NetworkInterface* inet::IRoute::getInterface () const pure virtual
Next hop interface.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::operator<<(), inet::dymo::Dymo::processRerr(), inet::Rip::receiveSignal(), inet::dymo::Dymo::receiveSignal(), inet::RoutingTableRecorder::recordRouteChange(), inet::RipRoute::RipRoute(), inet::dymo::Dymo::sendRerrForBrokenLink(), and inet::dymo::Dymo::sendRrep().
getMetric()
virtual int inet::IRoute::getMetric () const pure virtual
Cost to reach the destination.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createGratuitousRREP(), inet::aodv::Aodv::createRREP(), inet::dymo::Dymo::createRrep(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREQ(), inet::operator<<(), inet::Rip::processResponse(), inet::aodv::Aodv::sendRREP(), and inet::dymo::Dymo::updateRoutes().
getNextHopAsGeneric()
virtual L3Address inet::IRoute::getNextHopAsGeneric () const pure virtual
Next hop address.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRREP(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::dymo::Dymo::ensureRouteForDatagram(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREQ(), inet::operator<<(), inet::dymo::Dymo::processRerr(), inet::Rip::receiveSignal(), inet::aodv::Aodv::receiveSignal(), inet::dymo::Dymo::receiveSignal(), inet::RoutingTableRecorder::recordRouteChange(), inet::RipRoute::RipRoute(), inet::aodv::Aodv::sendGRREP(), inet::dymo::Dymo::sendRerrForBrokenLink(), inet::dymo::Dymo::sendRrep(), and inet::aodv::Aodv::sendRREP().
getPrefixLength()
virtual int inet::IRoute::getPrefixLength () const pure virtual
Represents length of prefix to match.
Implemented in inet::Ipv4Route, inet::Ipv6Route, and inet::NextHopRoute.
Referenced by inet::Rip::isDefaultRoute(), inet::operator<<(), inet::Rip::receiveSignal(), inet::RoutingTableRecorder::recordRouteChange(), and inet::RipRoute::RipRoute().
getProtocolData()
virtual cObject* inet::IRoute::getProtocolData () const pure virtual
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createGratuitousRREP(), inet::aodv::Aodv::createRREP(), inet::dymo::Dymo::createRrep(), inet::aodv::Aodv::createRREQ(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::dymo::Dymo::ensureRouteForDatagram(), inet::aodv::Aodv::expungeRoutes(), inet::dymo::Dymo::expungeRoutes(), inet::dymo::Dymo::getNextExpungeTime(), inet::aodv::Aodv::handleHelloMessage(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREPACK(), inet::aodv::Aodv::handleRREQ(), inet::dymo::Dymo::processRerr(), inet::aodv::Aodv::scheduleExpungeRoutes(), inet::aodv::Aodv::sendHelloMessagesIfNeeded(), inet::dymo::Dymo::sendRerrForBrokenLink(), inet::aodv::Aodv::sendRERRWhenNoRouteToForward(), inet::aodv::Aodv::sendRREP(), inet::dymo::Dymo::updateRoute(), inet::dymo::Dymo::updateRoutes(), inet::aodv::Aodv::updateRoutingTable(), and inet::aodv::Aodv::updateValidRouteLifeTime().
getRoutingTableAsGeneric()
virtual IRoutingTable* inet::IRoute::getRoutingTableAsGeneric () const pure virtual
The routing table in which this route is inserted, or nullptr.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::RoutingTableRecorder::recordRouteChange().
getSource()
virtual cObject* inet::IRoute::getSource () const pure virtual
Source of route.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRREQ(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::expungeRoutes(), inet::dymo::Dymo::expungeRoutes(), inet::dymo::Dymo::getNextExpungeTime(), inet::aodv::Aodv::handleHelloMessage(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREPACK(), inet::aodv::Aodv::handleRREQ(), inet::Rip::importRoute(), inet::Rip::isLocalInterfaceRoute(), inet::Rip::isLoopbackInterfaceRoute(), inet::dymo::Dymo::processRerr(), inet::Rip::receiveSignal(), inet::aodv::Aodv::receiveSignal(), inet::aodv::Aodv::scheduleExpungeRoutes(), inet::aodv::Aodv::sendHelloMessagesIfNeeded(), inet::dymo::Dymo::sendRerrForBrokenLink(), inet::Rip::startRIPRouting(), inet::dymo::Dymo::updateRoutes(), and inet::aodv::Aodv::updateValidRouteLifeTime().
getSourceType()
virtual SourceType inet::IRoute::getSourceType () const pure virtual
Source type of the route.
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
setAdminDist()
virtual void inet::IRoute::setAdminDist (unsigned int adminDist) pure virtual
Implemented in inet::Ipv6Route, inet::NextHopRoute, and inet::Ipv4Route.
Referenced by inet::Rip::createRoute().
setDestination()
virtual void inet::IRoute::setDestination (const L3Address & dest) pure virtual
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), and inet::dymo::Dymo::updateRoute().
setInterface()
virtual void inet::IRoute::setInterface (NetworkInterface * ie) pure virtual
Implemented in inet::Ipv6Route, inet::NextHopRoute, and inet::Ipv4Route.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), inet::RipRoute::setInterface(), and inet::dymo::Dymo::updateRoute().
setMetric()
virtual void inet::IRoute::setMetric (int metric) pure virtual
Implemented in inet::Ipv6Route, inet::NextHopRoute, and inet::Ipv4Route.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), inet::RipRoute::setMetric(), inet::dymo::Dymo::updateRoute(), and inet::aodv::Aodv::updateRoutingTable().
setNextHop()
virtual void inet::IRoute::setNextHop (const L3Address & nextHop) pure virtual
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), inet::RipRoute::setNextHop(), inet::dymo::Dymo::updateRoute(), and inet::aodv::Aodv::updateRoutingTable().
setPrefixLength()
virtual void inet::IRoute::setPrefixLength (int l) pure virtual
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), and inet::dymo::Dymo::updateRoute().
setProtocolData()
virtual void inet::IRoute::setProtocolData (cObject * protocolData) pure virtual
Implemented in inet::Ipv6Route, inet::Ipv4Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRoute(), and inet::dymo::Dymo::createRoute().
setSource()
virtual void inet::IRoute::setSource (cObject * source) pure virtual
Implemented in inet::Ipv6Route, inet::NextHopRoute, and inet::Ipv4Route.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), and inet::dymo::Dymo::createRoute().
setSourceType()
virtual void inet::IRoute::setSourceType (SourceType type) pure virtual
Implemented in inet::Ipv6Route, and inet::NextHopRoute.
Referenced by inet::aodv::Aodv::createRoute(), inet::Rip::createRoute(), and inet::dymo::Dymo::createRoute().
sourceTypeName()
const char * inet::IRoute::sourceTypeName (SourceType sourceType) static
 {
     switch (sourceType) {
         case MANUAL:
             return "MANUAL";
         case IFACENETMASK:
             return "IFACENETMASK";
         case ROUTER_ADVERTISEMENT:
             return "FROM_RA";
         case OWN_ADV_PREFIX:
             return "OWN_ADV_PREFIX";
         case ICMP_REDIRECT:
             return "REDIRECT";
         case RIP:
             return "RIP";
         case OSPF:
             return "OSPF";
         case BGP:
             return "BGP";
         case ZEBRA:
             return "ZEBRA";
         case MANET:
             return "MANET";
         case MANET2:
             return "MANET2";
         case DYMO:
             return "DYMO";
         case AODV:
             return "AODV";
         case EIGRP:
             return "EIGRP";
         case LISP:
             return "LISP";
         case BABEL:
             return "BABEL";
         default:
             return "???";
     }
 }
Referenced by inet::NextHopRoute::str().
The documentation for this class was generated from the following files:
IRoute.h
IRoute.cc