INET Framework for OMNeT++/OMNEST: inet::ieee80211::HcfFs Class Reference
inet::ieee80211::HcfFs Class Reference
#include <HcfFs.h>
Public Member Functions
HcfFs ()
virtual ~HcfFs ()
virtual int selectHcfSequence (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual int selectDataOrManagementSequence (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual bool isSelfCtsNeeded (OptionalFs *frameSequence, FrameSequenceContext *context)
virtual bool hasMoreTxOps (RepeatingFs *frameSequence, FrameSequenceContext *context)
virtual bool hasMoreTxOpsAndMulticast (RepeatingFs *frameSequence, FrameSequenceContext *context)
Public Member Functions inherited from inet::ieee80211::AlternativesFs
virtual ~AlternativesFs ()
AlternativesFs (std::vector< IFrameSequence * > elements, std::function< int(AlternativesFs *, FrameSequenceContext *)> selector)
virtual int getStep ()
virtual int selectSequence (FrameSequenceContext *context)
virtual void startSequence (FrameSequenceContext *context, int firstStep) override
virtual IFrameSequenceStep * prepareStep (FrameSequenceContext *context) override
virtual bool completeStep (FrameSequenceContext *context) override
virtual std::string getHistory () const override
Public Member Functions inherited from inet::ieee80211::IFrameSequence
virtual ~IFrameSequence ()
Additional Inherited Members
Protected Attributes inherited from inet::ieee80211::AlternativesFs
int firstStep = -1
int step = -1
int elementIndex = -1
std::vector< IFrameSequence * > elements
std::function< int(AlternativesFs *, FrameSequenceContext *)> selector
Constructor & Destructor Documentation
HcfFs()
inet::ieee80211::HcfFs::HcfFs ()
              :
     // G.3 EDCA and HCCA sequences
     // hcf-sequence =
     //   ( [ CTS ] 1{( Data + group [+ QoS ] ) | Management + broadcast ) +pifs} |
     //   ( [ CTS ] 1{txop-sequence} ) |
     //   (* HC only, polled TXOP delivery *)
     //   ( [ RTS CTS ] non-cf-ack-piggybacked-qos-poll-sequence )
     //   (* HC only, polled TXOP delivery *)
     //   cf-ack-piggybacked-qos-poll-sequence |
     //   (* HC only, self TXOP delivery or termination *)
     //   Data + self + null + CF-Poll + QoS;
     AlternativesFs({new SequentialFs({new OptionalFs(new SelfCtsFs(), OPTIONALFS_PREDICATE(isSelfCtsNeeded)),
                                       new RepeatingFs(new AlternativesFs({new DataFs(), new ManagementFs()}, ALTERNATIVESFS_SELECTOR(selectDataOrManagementSequence)),
                                                       REPEATINGFS_PREDICATE(hasMoreTxOpsAndMulticast))}),
                     new SequentialFs({new OptionalFs(new SelfCtsFs(), OPTIONALFS_PREDICATE(isSelfCtsNeeded)),
                                       new RepeatingFs(new TxOpFs(), REPEATINGFS_PREDICATE(hasMoreTxOps))})},
                    ALTERNATIVESFS_SELECTOR(selectHcfSequence))
 {
 }
~HcfFs()
virtual inet::ieee80211::HcfFs::~HcfFs () inline virtual
 {}
Member Function Documentation
hasMoreTxOps()
bool inet::ieee80211::HcfFs::hasMoreTxOps (RepeatingFs * frameSequence, FrameSequenceContext * context) virtual
 {
     bool hasFrameToTransmit = context->getInProgressFrames()->hasInProgressFrames();
     if (hasFrameToTransmit) {
         auto nextFrameToTransmit = context->getInProgressFrames()->getFrameToTransmit();
         const auto& nextHeader = nextFrameToTransmit->peekAtFront<Ieee80211MacHeader>();
         return frameSequence->getCount() == 0 || (!nextHeader->getReceiverAddress().isMulticast() && context->getQoSContext()->txopProcedure->getRemaining() > 0);
     }
     return false;
 }
Referenced by hasMoreTxOpsAndMulticast(), and HcfFs().
hasMoreTxOpsAndMulticast()
bool inet::ieee80211::HcfFs::hasMoreTxOpsAndMulticast (RepeatingFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return hasMoreTxOps(frameSequence, context) && context->getInProgressFrames()->getFrameToTransmit()->peekAtFront<Ieee80211MacHeader>()->getReceiverAddress().isMulticast();
 }
Referenced by HcfFs().
isSelfCtsNeeded()
bool inet::ieee80211::HcfFs::isSelfCtsNeeded (OptionalFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return false;
 }
Referenced by HcfFs().
selectDataOrManagementSequence()
int inet::ieee80211::HcfFs::selectDataOrManagementSequence (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     auto frameToTransmit = context->getInProgressFrames()->getFrameToTransmit();
     const auto& header = frameToTransmit->peekAtFront<Ieee80211MacHeader>();
     if (dynamicPtrCast<const Ieee80211DataHeader>(header))
         return 0;
     else if (dynamicPtrCast<const Ieee80211MgmtHeader>(header))
         return 1;
     else
         throw cRuntimeError("frameToTransmit must be either a Data or a Management frame");
 }
Referenced by HcfFs().
selectHcfSequence()
int inet::ieee80211::HcfFs::selectHcfSequence (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     auto frameToTransmit = context->getInProgressFrames()->getFrameToTransmit();
     return frameToTransmit->peekAtFront<Ieee80211MacHeader>()->getReceiverAddress().isMulticast() ? 0 : 1;
 }
The documentation for this class was generated from the following files:
HcfFs.h
HcfFs.cc