INET Framework for OMNeT++/OMNEST: inet::DrPriorityOption Class Reference
inet::DrPriorityOption Class Reference
Class generated from inet/routing/pim/PimPacket.msg:98 by opp_msgtool.
#include <PimPacket_m.h>
Public Member Functions
DrPriorityOption ()
DrPriorityOption (const DrPriorityOption &other)
virtual ~DrPriorityOption ()
DrPriorityOption & operator= (const DrPriorityOption &other)
virtual DrPriorityOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getPriority () const
virtual void setPriority (uint32_t priority)
Public Member Functions inherited from inet::HelloOption
HelloOption ()
HelloOption (const HelloOption &other)
virtual ~HelloOption ()
HelloOption & operator= (const HelloOption &other)
virtual PimHelloOptionType getType () const
virtual void setType (PimHelloOptionType type)
Protected Member Functions
bool operator== (const DrPriorityOption &)=delete
Protected Member Functions inherited from inet::HelloOption
bool operator== (const HelloOption &)=delete
Protected Attributes
uint32_t priority = 0
Protected Attributes inherited from inet::HelloOption
PimHelloOptionType type = static_cast<inet::PimHelloOptionType>(-1)
Private Member Functions
void copy (const DrPriorityOption &other)
Detailed Description
Class generated from inet/routing/pim/PimPacket.msg:98 by opp_msgtool.
class DrPriorityOption extends HelloOption
{
    type = DRPriority;
    uint32_t priority;
}
Constructor & Destructor Documentation
DrPriorityOption() [1/2]
inet::DrPriorityOption::DrPriorityOption ()
DrPriorityOption() [2/2]
inet::DrPriorityOption::DrPriorityOption (const DrPriorityOption & other)
~DrPriorityOption()
virtual inet::DrPriorityOption::~DrPriorityOption () virtual
Member Function Documentation
copy()
void inet::DrPriorityOption::copy (const DrPriorityOption & other) private
dup()
virtual DrPriorityOption* inet::DrPriorityOption::dup () const inline override virtual
Reimplemented from inet::HelloOption.
 {return new DrPriorityOption(*this);}
getPriority()
virtual uint32_t inet::DrPriorityOption::getPriority () const virtual
Referenced by inet::PimPacketSerializer::serialize().
operator=()
DrPriorityOption& inet::DrPriorityOption::operator= (const DrPriorityOption & other)
operator==()
bool inet::DrPriorityOption::operator== (const DrPriorityOption &) protected delete
parsimPack()
virtual void inet::DrPriorityOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::DrPriorityOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimUnpacking().
setPriority()
virtual void inet::DrPriorityOption::setPriority (uint32_t priority) virtual
Referenced by inet::PimPacketSerializer::deserialize(), and inet::PimBase::sendHelloPacket().
Member Data Documentation
priority
uint32_t inet::DrPriorityOption::priority = 0 protected
The documentation for this class was generated from the following file:
PimPacket_m.h