INET Framework for OMNeT++/OMNEST: inet::L2NetworkConfigurator::Matcher Class Reference
inet::L2NetworkConfigurator::Matcher Class Reference
#include <L2NetworkConfigurator.h>
Public Member Functions
Matcher (const char *pattern)
~Matcher ()
bool matches (const char *s)
bool matchesAny ()
Protected Attributes
bool matchesany
std::vector< inet::PatternMatcher * > matchers
Constructor & Destructor Documentation
Matcher()
inet::L2NetworkConfigurator::Matcher::Matcher (const char * pattern)
 {
     matchesany = opp_isempty(pattern);
     if (matchesany)
         return;
     cStringTokenizer tokenizer(pattern);
     while (tokenizer.hasMoreTokens())
         matchers.push_back(new inet::PatternMatcher(tokenizer.nextToken(), true, true, true));
 }
~Matcher()
inet::L2NetworkConfigurator::Matcher::~Matcher ()
 {
     for (auto& elem : matchers)
         delete elem;
 }
Member Function Documentation
matches()
bool inet::L2NetworkConfigurator::Matcher::matches (const char * s)
 {
     if (matchesany)
         return true;
     for (auto& elem : matchers)
         if (elem->matches(s))
             return true;
     return false;
 }
Referenced by inet::L2NetworkConfigurator::linkContainsMatchingHostExcept(), and inet::L2NetworkConfigurator::readInterfaceConfiguration().
matchesAny()
bool inet::L2NetworkConfigurator::Matcher::matchesAny () inline
 { return matchesany; }
Referenced by inet::L2NetworkConfigurator::readInterfaceConfiguration().
Member Data Documentation
matchers
std::vector<inet::PatternMatcher *> inet::L2NetworkConfigurator::Matcher::matchers protected
matchesany
bool inet::L2NetworkConfigurator::Matcher::matchesany protected
The documentation for this class was generated from the following files:
L2NetworkConfigurator.h
L2NetworkConfigurator.cc