INET Framework for OMNeT++/OMNEST: inet::PcapReader Class Reference
inet::PcapReader Class Reference
#include <PcapReader.h>
Public Member Functions
virtual void openPcap (const char *filename, const char *packetNameFormat)
virtual void closePcap ()
virtual bool isOpen ()
virtual std::pair< simtime_t, Packet * > readPacket ()
Protected Attributes
bool swapByteOrder = false
struct pcap_hdr fileHeader
const char * packetNameFormat = nullptr
FILE * file = nullptr
PacketPrinter packetPrinter
Member Function Documentation
closePcap()
void inet::PcapReader::closePcap () virtual
 {
     if (file != nullptr) {
         fclose(file);
         file = nullptr;
     }
 }
Referenced by inet::queueing::PcapFilePacketProducer::finish().
isOpen()
virtual bool inet::PcapReader::isOpen () inline virtual
 { return file != nullptr; }
Referenced by inet::queueing::PcapFilePacketProducer::finish().
openPcap()
void inet::PcapReader::openPcap (const char * filename, const char * packetNameFormat) virtual
 {
     if (opp_isempty(filename))
         throw cRuntimeError("Cannot open pcap file: file name is empty");
     this->packetNameFormat = packetNameFormat;
     inet::utils::makePathForFile(filename);
     file = fopen(filename, "rb");
     if (file == nullptr)
         throw cRuntimeError("Cannot open pcap file [%s] for reading: %s", filename, strerror(errno));
     struct pcap_hdr fh;
     auto err = fread(&fh, sizeof(fh), 1, file);
     if (err != 1)
         throw cRuntimeError("Cannot read fileheader from file '%s', errno is %ld.", filename, err);
     if (fh.magic == 0xa1b2c3d4)
         swapByteOrder = false;
     else if (fh.magic == 0xd4c3b2a1)
         swapByteOrder = true;
     else
         throw cRuntimeError("Unknown fileheader read from file '%s'", filename);
     if (swapByteOrder) {
         fh.version_major = swapByteOrder16(fh.version_major);
         fh.version_minor = swapByteOrder16(fh.version_minor);
         fh.thiszone = swapByteOrder32(fh.thiszone);
         fh.sigfigs = swapByteOrder32(fh.sigfigs);
         fh.snaplen = swapByteOrder32(fh.snaplen);
         fh.network = swapByteOrder32(fh.network);
     }
 }
Referenced by inet::queueing::PcapFilePacketProducer::initialize().
readPacket()
std::pair< simtime_t, Packet * > inet::PcapReader::readPacket () virtual
 {
     if (file == nullptr)
         throw cRuntimeError("Cannot read packet: pcap input file is not open");
     if (feof(file))
         return { -1, nullptr };
     struct pcaprec_hdr packetHeader;
     auto err = fread(&packetHeader, sizeof(packetHeader), 1, file);
     if (err != 1)
         throw cRuntimeError("Cannot read packetheader, errno is %ld.", err);
     uint8_t buffer[1 << 16];
     memset(buffer, 0, sizeof(buffer));
     err = fread(buffer, packetHeader.incl_len, 1, file);
     if (err != 1)
         throw cRuntimeError("Cannot read packet, errno is %ld.", err);
     if (swapByteOrder) {
         packetHeader.ts_sec = swapByteOrder32(packetHeader.ts_sec);
         packetHeader.ts_usec = swapByteOrder32(packetHeader.ts_usec);
         packetHeader.orig_len = swapByteOrder32(packetHeader.orig_len);
         packetHeader.incl_len = swapByteOrder32(packetHeader.incl_len);
     }
     simtime_t time = SimTime(packetHeader.ts_sec, SIMTIME_S) + SimTime(packetHeader.ts_usec, SIMTIME_US);
     std::vector<uint8_t> bytes;
     const Protocol *protocol = nullptr;
     int offset = 0;
     switch (fileHeader.network) {
         case 0: {
             offset = 4;
             auto type = *((uint32_t *)buffer);
             switch (type) {
                 case 2: protocol = &Protocol::ipv4; break;
                 case 24: case 28: case 30: protocol = &Protocol::ipv6; break;
             }
             break;
         }
         case 1: protocol = &Protocol::ethernetMac; break;
         case 105: protocol = &Protocol::ieee80211Mac; break;
         case 204: protocol = &Protocol::ppp; break;
     }
     bytes.resize(packetHeader.orig_len - offset);
     for (size_t i = 0; i < bytes.size(); i++)
         bytes[i] = buffer[i + offset];
     const auto& data = makeShared<BytesChunk>(bytes);
     if (packetHeader.orig_len > packetHeader.incl_len)
         data->markIncomplete();
     auto packet = new Packet(nullptr, data);
     if (protocol != nullptr)
         packet->addTag<PacketProtocolTag>()->setProtocol(protocol);
     packet->setName(packetPrinter.printPacketToString(packet, packetNameFormat).c_str());
     return { time, packet };
 }
Referenced by inet::queueing::PcapFilePacketProducer::schedulePacket().
Member Data Documentation
file
FILE* inet::PcapReader::file = nullptr protected
Referenced by closePcap(), openPcap(), and readPacket().
fileHeader
struct pcap_hdr inet::PcapReader::fileHeader protected
packetNameFormat
const char* inet::PcapReader::packetNameFormat = nullptr protected
Referenced by openPcap().
packetPrinter
PacketPrinter inet::PcapReader::packetPrinter protected
swapByteOrder
bool inet::PcapReader::swapByteOrder = false protected
Referenced by openPcap(), and readPacket().
The documentation for this class was generated from the following files:
PcapReader.h
PcapReader.cc