INET Framework for OMNeT++/OMNEST: inet::dymo::RreqTimer Class Reference
inet::dymo::RreqTimer Class Reference
Class generated from inet/routing/dymo/Dymo.msg:57 by opp_msgtool.
#include <Dymo_m.h>
Public Member Functions
RreqTimer (const char *name=nullptr, short kind=0)
RreqTimer (const RreqTimer &other)
virtual ~RreqTimer ()
RreqTimer & operator= (const RreqTimer &other)
virtual RreqTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::L3Address & getTarget () const
virtual ::inet::L3Address & getTargetForUpdate ()
virtual void setTarget (const ::inet::L3Address &target)
Protected Member Functions
bool operator== (const RreqTimer &)=delete
Protected Attributes
::inet::L3Address target
Private Member Functions
void copy (const RreqTimer &other)
Detailed Description
Class generated from inet/routing/dymo/Dymo.msg:57 by opp_msgtool.
message RreqTimer
{
    L3Address target;
}
Constructor & Destructor Documentation
RreqTimer() [1/2]
inet::dymo::RreqTimer::RreqTimer (const char * name = nullptr, short kind = 0)
RreqTimer() [2/2]
inet::dymo::RreqTimer::RreqTimer (const RreqTimer & other)
~RreqTimer()
virtual inet::dymo::RreqTimer::~RreqTimer () virtual
Member Function Documentation
copy()
void inet::dymo::RreqTimer::copy (const RreqTimer & other) private
dup()
virtual RreqTimer* inet::dymo::RreqTimer::dup () const inline override virtual
Reimplemented in inet::dymo::RreqHolddownTimer, inet::dymo::RreqBackoffTimer, and inet::dymo::RreqWaitRrepTimer.
 {return new RreqTimer(*this);}
getTarget()
virtual const ::inet::L3Address& inet::dymo::RreqTimer::getTarget () const virtual
Referenced by inet::dymo::Dymo::processRreqBackoffTimer(), inet::dymo::Dymo::processRreqHolddownTimer(), inet::dymo::Dymo::processRreqWaitRrepTimer(), inet::dymo::Dymo::scheduleRreqBackoffTimer(), inet::dymo::Dymo::scheduleRreqHolddownTimer(), and inet::dymo::Dymo::scheduleRreqWaitRrepTimer().
getTargetForUpdate()
virtual ::inet::L3Address& inet::dymo::RreqTimer::getTargetForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<RreqTimer*>(this)->getTarget());}
operator=()
RreqTimer& inet::dymo::RreqTimer::operator= (const RreqTimer & other)
operator==()
bool inet::dymo::RreqTimer::operator== (const RreqTimer &) protected delete
parsimPack()
virtual void inet::dymo::RreqTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::dymo::RreqHolddownTimer, inet::dymo::RreqBackoffTimer, and inet::dymo::RreqWaitRrepTimer.
Referenced by inet::dymo::doParsimPacking().
parsimUnpack()
virtual void inet::dymo::RreqTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::dymo::RreqHolddownTimer, inet::dymo::RreqBackoffTimer, and inet::dymo::RreqWaitRrepTimer.
Referenced by inet::dymo::doParsimUnpacking().
setTarget()
virtual void inet::dymo::RreqTimer::setTarget (const ::inet::L3Address & target) virtual
Referenced by inet::dymo::Dymo::createRreqBackoffTimer(), inet::dymo::Dymo::createRreqHolddownTimer(), and inet::dymo::Dymo::createRreqWaitRrepTimer().
Member Data Documentation
target
::inet::L3Address inet::dymo::RreqTimer::target protected
The documentation for this class was generated from the following file:
Dymo_m.h