INET Framework for OMNeT++/OMNEST: inet::ISocket Class Reference
inet::ISocket Class Reference abstract
This class provides an interface that should be implemented by all sockets.
#include <ISocket.h>
Public Member Functions
virtual ~ISocket ()
virtual int getSocketId () const =0
Returns the socket Id which is unique within the network node.
virtual bool belongsToSocket (cMessage *msg) const =0
Returns true if the message belongs to this socket.
virtual void processMessage (cMessage *msg)=0
Examines the message, takes ownership, and updates socket state.
virtual void send (Packet *packet)=0
virtual void close ()=0
Close the socket.
virtual void destroy ()=0
Notify the protocol that the owner of ISocket has destroyed the socket.
virtual bool isOpen () const =0
Detailed Description
This class provides an interface that should be implemented by all sockets.
Constructor & Destructor Documentation
~ISocket()
virtual inet::ISocket::~ISocket () inline virtual
 {}
Member Function Documentation
belongsToSocket()
virtual bool inet::ISocket::belongsToSocket (cMessage * msg) const pure virtual
Returns true if the message belongs to this socket.
Implemented in inet::TcpSocket, inet::SctpSocket, inet::UdpSocket, inet::TunSocket, inet::SocketBase, inet::L3Socket, inet::Ipv4Socket, and inet::Ipv6Socket.
Referenced by inet::VirtualTunnel::handleMessage().
close()
virtual void inet::ISocket::close () pure virtual
Close the socket.
Implemented in inet::INetworkSocket, inet::TcpSocket, inet::SctpSocket, inet::UdpSocket, inet::TunSocket, inet::L3Socket, inet::Ipv4Socket, inet::Ipv6Socket, and inet::SocketBase.
destroy()
virtual void inet::ISocket::destroy () pure virtual
Notify the protocol that the owner of ISocket has destroyed the socket.
Typically used when the owner of ISocket has crashed.
Implemented in inet::SctpSocket, inet::TcpSocket, inet::UdpSocket, inet::TunSocket, inet::L3Socket, inet::Ipv4Socket, inet::Ipv6Socket, and inet::SocketBase.
Referenced by inet::PingApp::handleCrashOperation().
getSocketId()
virtual int inet::ISocket::getSocketId () const pure virtual
Returns the socket Id which is unique within the network node.
Implemented in inet::TcpSocket, inet::SctpSocket, inet::UdpSocket, inet::TunSocket, inet::L3Socket, inet::Ipv4Socket, inet::Ipv6Socket, and inet::SocketBase.
Referenced by inet::SocketMap::addSocket(), and inet::SocketMap::removeSocket().
isOpen()
virtual bool inet::ISocket::isOpen () const pure virtual
Implemented in inet::TcpSocket, inet::SctpSocket, inet::UdpSocket, inet::TunSocket, inet::L3Socket, inet::Ipv4Socket, inet::Ipv6Socket, and inet::SocketBase.
processMessage()
virtual void inet::ISocket::processMessage (cMessage * msg) pure virtual
Examines the message, takes ownership, and updates socket state.
Implemented in inet::TcpSocket, inet::SctpSocket, inet::UdpSocket, inet::Ieee8021qSocket, inet::TunSocket, inet::EthernetSocket, inet::Ieee8022LlcSocket, inet::L3Socket, inet::Ipv4Socket, and inet::Ipv6Socket.
Referenced by inet::VirtualTunnel::handleMessage(), and inet::Ldp::handleMessageWhenUp().
send()
virtual void inet::ISocket::send (Packet * packet) pure virtual
Implemented in inet::SctpSocket, inet::TunSocket, inet::L3Socket, inet::Ipv4Socket, inet::Ipv6Socket, inet::SocketBase, inet::TcpSocket, and inet::UdpSocket.
Referenced by inet::VirtualTunnel::handleMessage(), and inet::PingApp::sendPingRequest().
The documentation for this class was generated from the following file:
ISocket.h