INET Framework for OMNeT++/OMNEST: inet::InterfaceToken Class Reference
inet::InterfaceToken Class Reference
An "interface token" as defined in RFC 1971 (Ipv6 Stateless Autoconfiguration).
#include <InterfaceToken.h>
Public Member Functions
InterfaceToken ()
InterfaceToken (uint32_t low, uint32_t normal, int len)
InterfaceToken (const InterfaceToken &t)
InterfaceToken & operator= (const InterfaceToken &t)
int length () const
uint32_t low () const
uint32_t normal () const
Private Member Functions
void copy (const InterfaceToken &t)
Private Attributes
uint32_t _normal
uint32_t _low
short _len
Detailed Description
An "interface token" as defined in RFC 1971 (Ipv6 Stateless Autoconfiguration).
This class supports tokens of length 1..64-bits. An interface token needs to be provided by L2 modules in order to be able to form Ipv6 link local addresses.
Constructor & Destructor Documentation
InterfaceToken() [1/3]
inet::InterfaceToken::InterfaceToken () inline
 { _normal = _low = _len = 0; }
InterfaceToken() [2/3]
inet::InterfaceToken::InterfaceToken (uint32_t low, uint32_t normal, int len) inline
 { _normal = normal; _low = low; _len = len; }
InterfaceToken() [3/3]
inet::InterfaceToken::InterfaceToken (const InterfaceToken & t) inline
 { copy(t); }
Member Function Documentation
copy()
void inet::InterfaceToken::copy (const InterfaceToken & t) inline private
 { _normal = t._normal; _low = t._low; _len = t._len; }
length()
int inet::InterfaceToken::length () const inline
 { return _len; }
Referenced by inet::Ipv6Address::formLinkLocalAddress().
low()
uint32_t inet::InterfaceToken::low () const inline
 { return _low; }
Referenced by inet::Ipv6Address::formLinkLocalAddress().
normal()
uint32_t inet::InterfaceToken::normal () const inline
 { return _normal; }
Referenced by inet::Ipv6Address::formLinkLocalAddress().
operator=()
InterfaceToken& inet::InterfaceToken::operator= (const InterfaceToken & t) inline
 { copy(t); return *this; }
Member Data Documentation
_len
short inet::InterfaceToken::_len private
Referenced by copy().
_low
uint32_t inet::InterfaceToken::_low private
Referenced by copy().
_normal
uint32_t inet::InterfaceToken::_normal private
Referenced by copy().
The documentation for this class was generated from the following file:
InterfaceToken.h