INET Framework for OMNeT++/OMNEST: inet::sctp::SctpErrorCauseParameter Class Reference
inet::sctp::SctpErrorCauseParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:341 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpErrorCauseParameter (const char *name=nullptr)
SctpErrorCauseParameter (const SctpErrorCauseParameter &other)
virtual ~SctpErrorCauseParameter ()
SctpErrorCauseParameter & operator= (const SctpErrorCauseParameter &other)
virtual SctpErrorCauseParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getResponseCorrelationId () const
virtual void setResponseCorrelationId (uint32_t responseCorrelationId)
virtual uint32_t getErrorCauseType () const
virtual void setErrorCauseType (uint32_t errorCauseType)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpErrorCauseParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t responseCorrelationId = 0
uint32_t errorCauseType = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpErrorCauseParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:341 by opp_msgtool.
class SctpErrorCauseParameter extends SctpParameter
{
    uint32_t responseCorrelationId;
    uint32_t errorCauseType;
}
Constructor & Destructor Documentation
SctpErrorCauseParameter() [1/2]
inet::sctp::SctpErrorCauseParameter::SctpErrorCauseParameter (const char * name = nullptr)
SctpErrorCauseParameter() [2/2]
inet::sctp::SctpErrorCauseParameter::SctpErrorCauseParameter (const SctpErrorCauseParameter & other)
~SctpErrorCauseParameter()
virtual inet::sctp::SctpErrorCauseParameter::~SctpErrorCauseParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpErrorCauseParameter::copy (const SctpErrorCauseParameter & other) private
dup()
virtual SctpErrorCauseParameter* inet::sctp::SctpErrorCauseParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpErrorCauseParameter(*this);}
getErrorCauseType()
virtual uint32_t inet::sctp::SctpErrorCauseParameter::getErrorCauseType () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getResponseCorrelationId()
virtual uint32_t inet::sctp::SctpErrorCauseParameter::getResponseCorrelationId () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpErrorCauseParameter& inet::sctp::SctpErrorCauseParameter::operator= (const SctpErrorCauseParameter & other)
operator==()
bool inet::sctp::SctpErrorCauseParameter::operator== (const SctpErrorCauseParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpErrorCauseParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpErrorCauseParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setErrorCauseType()
virtual void inet::sctp::SctpErrorCauseParameter::setErrorCauseType (uint32_t errorCauseType) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::processAsconfArrived().
setResponseCorrelationId()
virtual void inet::sctp::SctpErrorCauseParameter::setResponseCorrelationId (uint32_t responseCorrelationId) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::processAsconfArrived().
Member Data Documentation
errorCauseType
uint32_t inet::sctp::SctpErrorCauseParameter::errorCauseType = 0 protected
responseCorrelationId
uint32_t inet::sctp::SctpErrorCauseParameter::responseCorrelationId = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h