INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAddIPParameter Class Reference
inet::sctp::SctpAddIPParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:318 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpAddIPParameter (const char *name=nullptr)
SctpAddIPParameter (const SctpAddIPParameter &other)
virtual ~SctpAddIPParameter ()
SctpAddIPParameter & operator= (const SctpAddIPParameter &other)
virtual SctpAddIPParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getRequestCorrelationId () const
virtual void setRequestCorrelationId (uint32_t requestCorrelationId)
virtual const ::inet::L3Address & getAddressParam () const
virtual ::inet::L3Address & getAddressParamForUpdate ()
virtual void setAddressParam (const ::inet::L3Address &addressParam)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpAddIPParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t requestCorrelationId = 0
::inet::L3Address addressParam
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpAddIPParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:318 by opp_msgtool.
class SctpAddIPParameter extends SctpParameter
{
    uint32_t requestCorrelationId; //assigned by the sender to identify each request parameter
    L3Address addressParam;
}
Constructor & Destructor Documentation
SctpAddIPParameter() [1/2]
inet::sctp::SctpAddIPParameter::SctpAddIPParameter (const char * name = nullptr)
SctpAddIPParameter() [2/2]
inet::sctp::SctpAddIPParameter::SctpAddIPParameter (const SctpAddIPParameter & other)
~SctpAddIPParameter()
virtual inet::sctp::SctpAddIPParameter::~SctpAddIPParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpAddIPParameter::copy (const SctpAddIPParameter & other) private
dup()
virtual SctpAddIPParameter* inet::sctp::SctpAddIPParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpAddIPParameter(*this);}
getAddressParam()
virtual const ::inet::L3Address& inet::sctp::SctpAddIPParameter::getAddressParam () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::sendAsconf(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressParamForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpAddIPParameter::getAddressParamForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpAddIPParameter*>(this)->getAddressParam());}
getRequestCorrelationId()
virtual uint32_t inet::sctp::SctpAddIPParameter::getRequestCorrelationId () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpAddIPParameter& inet::sctp::SctpAddIPParameter::operator= (const SctpAddIPParameter & other)
operator==()
bool inet::sctp::SctpAddIPParameter::operator== (const SctpAddIPParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpAddIPParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpAddIPParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setAddressParam()
virtual void inet::sctp::SctpAddIPParameter::setAddressParam (const ::inet::L3Address & addressParam) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendAsconf().
setRequestCorrelationId()
virtual void inet::sctp::SctpAddIPParameter::setRequestCorrelationId (uint32_t requestCorrelationId) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendAsconf().
Member Data Documentation
addressParam
::inet::L3Address inet::sctp::SctpAddIPParameter::addressParam protected
requestCorrelationId
uint32_t inet::sctp::SctpAddIPParameter::requestCorrelationId = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h