INET Framework for OMNeT++/OMNEST: inet::physicallayer::IAnalogModel Class Reference
inet::physicallayer::IAnalogModel Class Reference abstract
This interface models how a radio signal attenuates during propagation.
#include <IAnalogModel.h>
Public Member Functions
virtual const IReception * computeReception (const IRadio *receiver, const ITransmission *transmission, const IArrival *arrival) const =0
Returns the reception for the provided transmission at the receiver.
virtual const INoise * computeNoise (const IListening *listening, const IInterference *interference) const =0
Returns the total noise summing up all the interfering receptions and noises.
virtual const INoise * computeNoise (const IReception *reception, const INoise *noise) const =0
Returns the total noise summing up all the reception and the noise.
virtual const ISnir * computeSNIR (const IReception *reception, const INoise *noise) const =0
Returns the signal to noise and interference ratio.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface models how a radio signal attenuates during propagation.
It includes various effects such as free-space path loss, shadowing, refraction, reflection, absorption, diffraction and others.
Member Function Documentation
computeNoise() [1/2]
virtual const INoise* inet::physicallayer::IAnalogModel::computeNoise (const IListening * listening, const IInterference * interference) const pure virtual
Returns the total noise summing up all the interfering receptions and noises.
This function never returns nullptr.
Implemented in inet::physicallayer::ScalarAnalogModelBase, inet::physicallayer::DimensionalAnalogModelBase, and inet::physicallayer::UnitDiskAnalogModel.
Referenced by inet::physicallayer::FlatReceiverBase::computeListeningDecision(), inet::physicallayer::ApskLayeredReceiver::computeListeningDecision(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeListeningDecision(), and inet::physicallayer::RadioMedium::getNoise().
computeNoise() [2/2]
virtual const INoise* inet::physicallayer::IAnalogModel::computeNoise (const IReception * reception, const INoise * noise) const pure virtual
Returns the total noise summing up all the reception and the noise.
This function never returns nullptr.
Implemented in inet::physicallayer::ScalarAnalogModelBase, inet::physicallayer::DimensionalAnalogModelBase, and inet::physicallayer::UnitDiskAnalogModel.
computeReception()
virtual const IReception* inet::physicallayer::IAnalogModel::computeReception (const IRadio * receiver, const ITransmission * transmission, const IArrival * arrival) const pure virtual
Returns the reception for the provided transmission at the receiver.
The result incorporates all modeled attenuation. This function never returns nullptr.
Implemented in inet::physicallayer::LayeredDimensionalAnalogModel, inet::physicallayer::LayeredScalarAnalogModel, inet::physicallayer::UnitDiskAnalogModel, inet::physicallayer::DimensionalAnalogModel, and inet::physicallayer::ScalarAnalogModel.
Referenced by inet::physicallayer::RadioMedium::computeReception(), and inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight().
computeSNIR()
virtual const ISnir* inet::physicallayer::IAnalogModel::computeSNIR (const IReception * reception, const INoise * noise) const pure virtual
Returns the signal to noise and interference ratio.
This function never returns nullptr.
Implemented in inet::physicallayer::ScalarAnalogModelBase, inet::physicallayer::DimensionalAnalogModelBase, and inet::physicallayer::UnitDiskAnalogModel.
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), and inet::physicallayer::RadioMedium::getSNIR().
The documentation for this class was generated from the following file:
IAnalogModel.h