INET Framework for OMNeT++/OMNEST: inet::ieee80211::DcfFs Class Reference
inet::ieee80211::DcfFs Class Reference
#include <DcfFs.h>
Public Member Functions
DcfFs ()
virtual int selectDcfSequence (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual int selectSelfCtsOrRtsCts (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual int selectMulticastDataOrMgmt (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual bool hasMoreFragments (RepeatingFs *frameSequence, FrameSequenceContext *context)
virtual bool isSelfCtsNeeded (OptionalFs *frameSequence, FrameSequenceContext *context)
virtual bool isRtsCtsNeeded (OptionalFs *frameSequence, FrameSequenceContext *context)
virtual bool isCtsOrRtsCtsNeeded (OptionalFs *frameSequence, FrameSequenceContext *context)
virtual bool isBroadcastManagementOrGroupDataSequenceNeeded (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual bool isFragFrameSequenceNeeded (AlternativesFs *frameSequence, FrameSequenceContext *context)
Public Member Functions inherited from inet::ieee80211::AlternativesFs
virtual ~AlternativesFs ()
AlternativesFs (std::vector< IFrameSequence * > elements, std::function< int(AlternativesFs *, FrameSequenceContext *)> selector)
virtual int getStep ()
virtual int selectSequence (FrameSequenceContext *context)
virtual void startSequence (FrameSequenceContext *context, int firstStep) override
virtual IFrameSequenceStep * prepareStep (FrameSequenceContext *context) override
virtual bool completeStep (FrameSequenceContext *context) override
virtual std::string getHistory () const override
Public Member Functions inherited from inet::ieee80211::IFrameSequence
virtual ~IFrameSequence ()
Additional Inherited Members
Protected Attributes inherited from inet::ieee80211::AlternativesFs
int firstStep = -1
int step = -1
int elementIndex = -1
std::vector< IFrameSequence * > elements
std::function< int(AlternativesFs *, FrameSequenceContext *)> selector
Constructor & Destructor Documentation
DcfFs()
inet::ieee80211::DcfFs::DcfFs ()
              :
     // Excerpt from G.2 Basic sequences (p. 2309)
     // frame-sequence =
     //   ( [ CTS ] ( Management + broadcast | Data + group ) ) |
     //   ( [ CTS | RTS CTS] {frag-frame ACK } last-frame ACK )
     //
     // frag-frame = ( Data | Management ) + individual + frag;
     // last-frame = ( Data | Management ) + individual + last;
     //
     AlternativesFs({new SequentialFs({new OptionalFs(new SelfCtsFs(), OPTIONALFS_PREDICATE(isSelfCtsNeeded)),
                                       new AlternativesFs({new ManagementFs(), new DataFs()}, ALTERNATIVESFS_SELECTOR(selectMulticastDataOrMgmt))}),
                     new SequentialFs({new OptionalFs(new AlternativesFs({new SelfCtsFs(), new SequentialFs({new RtsFs(), new CtsFs()})},
                                                                         ALTERNATIVESFS_SELECTOR(selectSelfCtsOrRtsCts)),
                                                      OPTIONALFS_PREDICATE(isCtsOrRtsCtsNeeded)),
                                       new RepeatingFs(new FragFrameAckFs(), REPEATINGFS_PREDICATE(hasMoreFragments)),
                                       new LastFrameAckFs()})},
                    ALTERNATIVESFS_SELECTOR(selectDcfSequence))
 {
 }
Member Function Documentation
hasMoreFragments()
bool inet::ieee80211::DcfFs::hasMoreFragments (RepeatingFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return context->getInProgressFrames()->hasInProgressFrames() && context->getInProgressFrames()->getFrameToTransmit()->peekAtFront<Ieee80211MacHeader>()->getMoreFragments();
 }
Referenced by DcfFs().
isBroadcastManagementOrGroupDataSequenceNeeded()
bool inet::ieee80211::DcfFs::isBroadcastManagementOrGroupDataSequenceNeeded (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     if (context->getInProgressFrames()->hasInProgressFrames()) {
         auto frameToTransmit = context->getInProgressFrames()->getFrameToTransmit();
         return frameToTransmit->peekAtFront<Ieee80211MacHeader>()->getReceiverAddress().isMulticast();
     }
     else
         return false;
 }
Referenced by selectDcfSequence().
isCtsOrRtsCtsNeeded()
bool inet::ieee80211::DcfFs::isCtsOrRtsCtsNeeded (OptionalFs * frameSequence, FrameSequenceContext * context) virtual
 {
     bool selfCts = isSelfCtsNeeded(frameSequence, context);
     bool rtsCts = isRtsCtsNeeded(frameSequence, context);
     return selfCts || rtsCts;
 }
Referenced by DcfFs().
isFragFrameSequenceNeeded()
bool inet::ieee80211::DcfFs::isFragFrameSequenceNeeded (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return context->getInProgressFrames()->hasInProgressFrames() && dynamicPtrCast<const Ieee80211DataOrMgmtHeader>(context->getInProgressFrames()->getFrameToTransmit()->peekAtFront<Ieee80211MacHeader>());
 }
Referenced by selectDcfSequence().
isRtsCtsNeeded()
bool inet::ieee80211::DcfFs::isRtsCtsNeeded (OptionalFs * frameSequence, FrameSequenceContext * context) virtual
 {
     auto protectedFrame = context->getInProgressFrames()->getFrameToTransmit();
     return context->getRtsPolicy()->isRtsNeeded(protectedFrame, protectedFrame->peekAtFront<Ieee80211MacHeader>());
 }
Referenced by isCtsOrRtsCtsNeeded(), and selectSelfCtsOrRtsCts().
isSelfCtsNeeded()
bool inet::ieee80211::DcfFs::isSelfCtsNeeded (OptionalFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return false; // TODO Implement
 }
Referenced by DcfFs(), isCtsOrRtsCtsNeeded(), and selectSelfCtsOrRtsCts().
selectDcfSequence()
int inet::ieee80211::DcfFs::selectDcfSequence (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     bool multicastMgmtOrDataSequence = isBroadcastManagementOrGroupDataSequenceNeeded(frameSequence, context);
     bool fragFrameSequence = isFragFrameSequenceNeeded(frameSequence, context);
     if (multicastMgmtOrDataSequence) return 0;
     else if (fragFrameSequence) return 1;
     else throw cRuntimeError("One alternative must be chosen");
 }
selectMulticastDataOrMgmt()
int inet::ieee80211::DcfFs::selectMulticastDataOrMgmt (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     auto frameToTransmit = context->getInProgressFrames()->getFrameToTransmit();
     return dynamicPtrCast<const Ieee80211MgmtHeader>(frameToTransmit->peekAtFront<Ieee80211MacHeader>()) ? 0 : 1;
 }
Referenced by DcfFs().
selectSelfCtsOrRtsCts()
int inet::ieee80211::DcfFs::selectSelfCtsOrRtsCts (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     bool selfCts = isSelfCtsNeeded(nullptr, context); // TODO
     bool rtsCts = isRtsCtsNeeded(nullptr, context); // TODO
     if (selfCts) return 0;
     else if (rtsCts) return 1;
     else throw cRuntimeError("One alternative must be chosen");
 }
Referenced by DcfFs().
The documentation for this class was generated from the following files:
DcfFs.h
DcfFs.cc