INET Framework for OMNeT++/OMNEST: inet::L3SocketBindCommand Class Reference
inet::L3SocketBindCommand Class Reference
Class generated from inet/networklayer/contract/L3SocketCommand.msg:31 by opp_msgtool.
#include <L3SocketCommand_m.h>
Public Member Functions
L3SocketBindCommand ()
L3SocketBindCommand (const L3SocketBindCommand &other)
virtual ~L3SocketBindCommand ()
L3SocketBindCommand & operator= (const L3SocketBindCommand &other)
virtual L3SocketBindCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Protocol * getProtocol () const
virtual void setProtocol (const Protocol *protocol)
virtual const L3Address & getLocalAddress () const
virtual L3Address & getLocalAddressForUpdate ()
virtual void setLocalAddress (const L3Address &localAddress)
Public Member Functions inherited from inet::L3SocketCommandBase
L3SocketCommandBase ()
L3SocketCommandBase (const L3SocketCommandBase &other)
virtual ~L3SocketCommandBase ()
L3SocketCommandBase & operator= (const L3SocketCommandBase &other)
Protected Member Functions
bool operator== (const L3SocketBindCommand &)=delete
Protected Member Functions inherited from inet::L3SocketCommandBase
bool operator== (const L3SocketCommandBase &)=delete
Protected Attributes
const Protocol * protocol = nullptr
L3Address localAddress
Private Member Functions
void copy (const L3SocketBindCommand &other)
Detailed Description
Class generated from inet/networklayer/contract/L3SocketCommand.msg:31 by opp_msgtool.
class L3SocketBindCommand extends L3SocketCommandBase
{
    const Protocol *protocol;
    L3Address localAddress;
}
Constructor & Destructor Documentation
L3SocketBindCommand() [1/2]
inet::L3SocketBindCommand::L3SocketBindCommand ()
L3SocketBindCommand() [2/2]
inet::L3SocketBindCommand::L3SocketBindCommand (const L3SocketBindCommand & other)
~L3SocketBindCommand()
virtual inet::L3SocketBindCommand::~L3SocketBindCommand () virtual
Member Function Documentation
copy()
void inet::L3SocketBindCommand::copy (const L3SocketBindCommand & other) private
dup()
virtual L3SocketBindCommand* inet::L3SocketBindCommand::dup () const inline override virtual
Reimplemented from inet::L3SocketCommandBase.
 {return new L3SocketBindCommand(*this);}
getLocalAddress()
virtual const L3Address& inet::L3SocketBindCommand::getLocalAddress () const virtual
getLocalAddressForUpdate()
virtual L3Address& inet::L3SocketBindCommand::getLocalAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<L3SocketBindCommand*>(this)->getLocalAddress());}
getProtocol()
virtual const Protocol* inet::L3SocketBindCommand::getProtocol () const virtual
operator=()
L3SocketBindCommand& inet::L3SocketBindCommand::operator= (const L3SocketBindCommand & other)
operator==()
bool inet::L3SocketBindCommand::operator== (const L3SocketBindCommand &) protected delete
parsimPack()
virtual void inet::L3SocketBindCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::L3SocketCommandBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::L3SocketBindCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::L3SocketCommandBase.
Referenced by inet::doParsimUnpacking().
setLocalAddress()
virtual void inet::L3SocketBindCommand::setLocalAddress (const L3Address & localAddress) virtual
setProtocol()
virtual void inet::L3SocketBindCommand::setProtocol (const Protocol * protocol) virtual
Referenced by inet::L3Socket::bind().
Member Data Documentation
localAddress
L3Address inet::L3SocketBindCommand::localAddress protected
protocol
const Protocol* inet::L3SocketBindCommand::protocol = nullptr protected
The documentation for this class was generated from the following file:
L3SocketCommand_m.h