INET Framework for OMNeT++/OMNEST: inet::TunSocket Class Reference
inet::TunSocket Class Reference
#include <TunSocket.h>
Classes
class ICallback
Public Member Functions
TunSocket ()
~TunSocket ()
void setOutputGate (cGate *outputGate)
Sets the gate on which to send raw packets.
void setCallback (ICallback *cb)
Sets a callback object, to be used with processMessage().
void * getUserData () const
void setUserData (void *userData)
virtual int getSocketId () const override
Returns the internal socket Id.
void open (int interfaceId)
virtual void send (Packet *packet) override
virtual void close () override
Close the socket.
virtual void destroy () override
Notify the protocol that the owner of ISocket has destroyed the socket.
virtual bool isOpen () const override
virtual bool belongsToSocket (cMessage *msg) const override
Returns true if the message belongs to this socket.
virtual void processMessage (cMessage *msg) override
Examines the message, takes ownership, and updates socket state.
Public Member Functions inherited from inet::ISocket
virtual ~ISocket ()
Protected Member Functions
void sendToTun (cMessage *msg)
Protected Attributes
int socketId = -1
int interfaceId = -1
ICallback * callback = nullptr
void * userData = nullptr
cGate * outputGate = nullptr
bool isOpen_ = false
Constructor & Destructor Documentation
TunSocket()
inet::TunSocket::TunSocket ()
 {
     socketId = getEnvir()->getUniqueNumber();
 }
~TunSocket()
inet::TunSocket::~TunSocket () inline
 {}
Member Function Documentation
belongsToSocket()
bool inet::TunSocket::belongsToSocket (cMessage * msg) const override virtual
Returns true if the message belongs to this socket.
Implements inet::ISocket.
 {
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     int msgSocketId = tags.getTag<SocketInd>()->getSocketId();
     return socketId == msgSocketId;
 }
Referenced by processMessage().
close()
void inet::TunSocket::close () override virtual
Close the socket.
Implements inet::ISocket.
 {
     auto request = new Request("CLOSE", TUN_C_CLOSE);
     TunCloseCommand *command = new TunCloseCommand();
     request->setControlInfo(command);
     sendToTun(request);
     this->interfaceId = -1;
 }
destroy()
void inet::TunSocket::destroy () override virtual
Notify the protocol that the owner of ISocket has destroyed the socket.
Typically used when the owner of ISocket has crashed.
Implements inet::ISocket.
 {
     auto request = new Request("DESTROY", TUN_C_DESTROY);
     auto command = new TunDestroyCommand();
     request->setControlInfo(command);
     sendToTun(request);
     this->interfaceId = -1;
 }
getSocketId()
virtual int inet::TunSocket::getSocketId () const inline override virtual
Returns the internal socket Id.
Implements inet::ISocket.
 { return socketId; }
Referenced by belongsToSocket().
getUserData()
void* inet::TunSocket::getUserData () const inline
 { return userData; }
isOpen()
virtual bool inet::TunSocket::isOpen () const inline override virtual
Implements inet::ISocket.
 { return isOpen_; }
open()
void inet::TunSocket::open (int interfaceId)
 {
     isOpen_ = true;
     this->interfaceId = interfaceId;
     auto request = new Request("OPEN", TUN_C_OPEN);
     TunOpenCommand *command = new TunOpenCommand();
     request->setControlInfo(command);
     sendToTun(request);
 }
Referenced by inet::TunLoopbackApp::initialize(), and inet::TunnelApp::initialize().
processMessage()
void inet::TunSocket::processMessage (cMessage * msg) override virtual
Examines the message, takes ownership, and updates socket state.
Implements inet::ISocket.
 {
     ASSERT(belongsToSocket(msg));
     switch (msg->getKind()) {
         case TUN_I_DATA:
             if (callback)
                 callback->socketDataArrived(this, check_and_cast<Packet *>(msg));
             else
                 delete msg;
             break;
         case TUN_I_CLOSED:
             isOpen_ = false;
             if (callback)
                 callback->socketClosed(this);
             delete msg;
             break;
         default:
             throw cRuntimeError("TunSocket: invalid msg kind %d, one of the TUN_I_xxx constants expected", msg->getKind());
     }
 }
send()
void inet::TunSocket::send (Packet * packet) override virtual
Implements inet::ISocket.
 {
     if (interfaceId == -1)
         throw cRuntimeError("Socket is closed");
 //    TunSendCommand *command = new TunSendCommand();
 //    packet->setControlInfo(command);
     packet->setKind(TUN_C_DATA);
     sendToTun(packet);
 }
Referenced by inet::TunLoopbackApp::handleMessage(), and inet::TunnelApp::socketDataArrived().
sendToTun()
void inet::TunSocket::sendToTun (cMessage * msg) protected
 {
     if (!outputGate)
         throw cRuntimeError("TunSocket: setOutputGate() must be invoked before socket can be used");
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     tags.addTagIfAbsent<SocketReq>()->setSocketId(socketId);
     tags.addTagIfAbsent<InterfaceReq>()->setInterfaceId(interfaceId);
     check_and_cast<cSimpleModule *>(outputGate->getOwnerModule())->send(msg, outputGate);
 }
Referenced by close(), destroy(), open(), and send().
setCallback()
void inet::TunSocket::setCallback (ICallback * cb)
Sets a callback object, to be used with processMessage().
This callback object may be your simple module itself (if it multiply inherits from ICallback too, that is you declared it as
class MyAppModule : public cSimpleModule, public TunSocket::ICallback
and redefined the necessary virtual functions; or you may use dedicated class (and objects) for this purpose.
TunSocket doesn't delete the callback object in the destructor or on any other occasion.
 {
     this->callback = callback;
 }
Referenced by inet::TunnelApp::initialize().
setOutputGate()
void inet::TunSocket::setOutputGate (cGate * outputGate) inline
Sets the gate on which to send raw packets.
Must be invoked before socket can be used. Example: socket.setOutputGate(gate("ipOut"));
 { this->outputGate = outputGate; }
Referenced by inet::TunLoopbackApp::initialize(), and inet::TunnelApp::initialize().
setUserData()
void inet::TunSocket::setUserData (void * userData) inline
 { this->userData = userData; }
Member Data Documentation
callback
ICallback* inet::TunSocket::callback = nullptr protected
Referenced by processMessage(), and setCallback().
interfaceId
int inet::TunSocket::interfaceId = -1 protected
Referenced by close(), destroy(), open(), send(), and sendToTun().
isOpen_
bool inet::TunSocket::isOpen_ = false protected
Referenced by open(), and processMessage().
outputGate
cGate* inet::TunSocket::outputGate = nullptr protected
Referenced by sendToTun().
socketId
int inet::TunSocket::socketId = -1 protected
Referenced by belongsToSocket(), sendToTun(), and TunSocket().
userData
void* inet::TunSocket::userData = nullptr protected
The documentation for this class was generated from the following files:
TunSocket.h
TunSocket.cc