INET Framework for OMNeT++/OMNEST: inet::SharingRegionTagSet::RegionTag< T > Class Template Reference
inet::SharingRegionTagSet::RegionTag< T > Class Template Reference
Region tags keep a tag for a specific range identified by offset and length.
#include <SharingRegionTagSet.h>
Public Member Functions
RegionTag (b offset, b length, const Ptr< const T > &tag)
RegionTag (const RegionTag< T > &other)
RegionTag (RegionTag &&other)
RegionTag & operator= (const RegionTag &other)
RegionTag & operator= (RegionTag &&other)
bool operator< (const SharingRegionTagSet::RegionTag< T > &other) const
b getOffset () const
void setOffset (b offset)
b getLength () const
void setLength (b length)
b getStartOffset () const
b getEndOffset () const
const Ptr< const T > & getTag () const
void setTag (const Ptr< const T > &tag)
virtual std::string str () const override
Protected Member Functions
const T * _getTag () const
Protected Attributes
b offset
b length
Ptr< const T > tag
Friends
class SharingRegionTagSet__TagBaseRegionTagDescriptor
Detailed Description
template<typename T>
class inet::SharingRegionTagSet::RegionTag< T >
Region tags keep a tag for a specific range identified by offset and length.
Constructor & Destructor Documentation
RegionTag() [1/3]
template<typename T > inet::SharingRegionTagSet::RegionTag< T >::RegionTag (b offset, b length, const Ptr< const T > & tag) inline
                                                                : offset(offset), length(length), tag(tag) {
             ASSERT(offset >= b(0));
             ASSERT(length >= b(0));
         }
RegionTag() [2/3]
template<typename T > inet::SharingRegionTagSet::RegionTag< T >::RegionTag (const RegionTag< T > & other) inline
 : offset(other.offset), length(other.length), tag(other.tag) {}
RegionTag() [3/3]
template<typename T > inet::SharingRegionTagSet::RegionTag< T >::RegionTag (RegionTag< T > && other) inline
 : offset(other.offset), length(other.length), tag(other.tag) { other.tag = nullptr; }
Member Function Documentation
_getTag()
template<typename T > const T* inet::SharingRegionTagSet::RegionTag< T >::_getTag () const inline protected
 { return tag.get(); }
getEndOffset()
template<typename T > b inet::SharingRegionTagSet::RegionTag< T >::getEndOffset () const inline
 { return offset + length; }
Referenced by inet::SharingRegionTagSet::mapAllTagsForUpdate().
getLength()
template<typename T > b inet::SharingRegionTagSet::RegionTag< T >::getLength () const inline
 { return length; }
Referenced by inet::SharingRegionTagSet::mapAllTagsForUpdate().
getOffset()
template<typename T > b inet::SharingRegionTagSet::RegionTag< T >::getOffset () const inline
 { return offset; }
Referenced by inet::SharingRegionTagSet::mapAllTagsForUpdate().
getStartOffset()
template<typename T > b inet::SharingRegionTagSet::RegionTag< T >::getStartOffset () const inline
 { return offset; }
Referenced by inet::SharingRegionTagSet::mapAllTagsForUpdate().
getTag()
template<typename T > const Ptr<const T>& inet::SharingRegionTagSet::RegionTag< T >::getTag () const inline
 { return tag; }
operator<()
template<typename T > bool inet::SharingRegionTagSet::RegionTag< T >::operator< (const SharingRegionTagSet::RegionTag< T > & other) const inline
 { return offset < other.offset; }
operator=() [1/2]
template<typename T > RegionTag& inet::SharingRegionTagSet::RegionTag< T >::operator= (const RegionTag< T > & other) inline
{
             if (this != &other) {
                 offset = other.offset;
                 length = other.length;
                 tag = other.tag;
             }
             return *this;
         }
operator=() [2/2]
template<typename T > RegionTag& inet::SharingRegionTagSet::RegionTag< T >::operator= (RegionTag< T > && other) inline
{
             if (this != &other) {
                 offset = other.offset;
                 length = other.length;
                 tag = other.tag;
                 other.tag = nullptr;
             }
             return *this;
         }
setLength()
template<typename T > void inet::SharingRegionTagSet::RegionTag< T >::setLength (b length) inline
{
             ASSERT(length >= b(0));
             if (this->length != length) {
                 tag = tag->changeRegion(b(0), length - this->length);
                 this->length = length;
             }
         }
Referenced by inet::SharingRegionTagSet::clearTags(), and inet::SharingRegionTagSet::splitTags().
setOffset()
template<typename T > void inet::SharingRegionTagSet::RegionTag< T >::setOffset (b offset) inline
{
             ASSERT(offset >= b(0));
             if (this->offset != offset) {
                 tag = tag->changeRegion(offset - this->offset, b(0));
                 this->offset = offset;
             }
         }
Referenced by inet::SharingRegionTagSet::clearTags(), and inet::SharingRegionTagSet::splitTags().
setTag()
template<typename T > void inet::SharingRegionTagSet::RegionTag< T >::setTag (const Ptr< const T > & tag) inline
 { this->tag = tag; }
str()
template<typename T > virtual std::string inet::SharingRegionTagSet::RegionTag< T >::str () const inline override virtual
{
             using std::operator<<; // KLUDGE but whyyyyyyyy?
             std::stringstream stream;
             stream << "(" << getStartOffset() << ", " << getEndOffset() << ") " << (tag != nullptr ? tag->str() : "<nullptr>");
             return stream.str();
         }
Friends And Related Function Documentation
SharingRegionTagSet__TagBaseRegionTagDescriptor
template<typename T > friend class SharingRegionTagSet__TagBaseRegionTagDescriptor friend
Member Data Documentation
length
template<typename T > b inet::SharingRegionTagSet::RegionTag< T >::length protected
Referenced by inet::SharingRegionTagSet::RegionTag< T >::operator=().
offset
template<typename T > b inet::SharingRegionTagSet::RegionTag< T >::offset protected
Referenced by inet::SharingRegionTagSet::RegionTag< T >::operator<(), and inet::SharingRegionTagSet::RegionTag< T >::operator=().
tag
template<typename T > Ptr<const T> inet::SharingRegionTagSet::RegionTag< T >::tag protected
Referenced by inet::SharingRegionTagSet::RegionTag< T >::operator=().
The documentation for this class was generated from the following file:
SharingRegionTagSet.h