INET Framework for OMNeT++/OMNEST: inet::ieee80211::IProcedureCallback Class Reference
inet::ieee80211::IProcedureCallback Class Reference abstract
#include <IProcedureCallback.h>
Public Member Functions
virtual ~IProcedureCallback ()
virtual void transmitControlResponseFrame (Packet *responsePacket, const Ptr< const Ieee80211MacHeader > &responseHeader, Packet *receivedPacket, const Ptr< const Ieee80211MacHeader > &receivedHeader)=0
virtual void processMgmtFrame (Packet *mgmtPacket, const Ptr< const Ieee80211MgmtHeader > &mgmtHeader)=0
Constructor & Destructor Documentation
~IProcedureCallback()
virtual inet::ieee80211::IProcedureCallback::~IProcedureCallback () inline virtual
 {}
Member Function Documentation
processMgmtFrame()
virtual void inet::ieee80211::IProcedureCallback::processMgmtFrame (Packet * mgmtPacket, const Ptr< const Ieee80211MgmtHeader > & mgmtHeader) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::blockAckAgreementExpired(), inet::ieee80211::RecipientBlockAckAgreementHandler::blockAckAgreementExpired(), inet::ieee80211::RecipientBlockAckAgreementHandler::processReceivedAddbaRequest(), and inet::ieee80211::OriginatorBlockAckAgreementHandler::processTransmittedDataFrame().
transmitControlResponseFrame()
virtual void inet::ieee80211::IProcedureCallback::transmitControlResponseFrame (Packet * responsePacket, const Ptr< const Ieee80211MacHeader > & responseHeader, Packet * receivedPacket, const Ptr< const Ieee80211MacHeader > & receivedHeader) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::RecipientBlockAckProcedure::processReceivedBlockAckReq(), inet::ieee80211::RecipientAckProcedure::processReceivedFrame(), and inet::ieee80211::CtsProcedure::processReceivedRts().
The documentation for this class was generated from the following file:
IProcedureCallback.h