INET Framework for OMNeT++/OMNEST: inet::PcpTagBase Class Reference
inet::PcpTagBase Class Reference
Class generated from inet/linklayer/common/PcpTag.msg:16 by opp_msgtool.
#include <PcpTag_m.h>
Public Member Functions
PcpTagBase ()
PcpTagBase (const PcpTagBase &other)
virtual ~PcpTagBase ()
PcpTagBase & operator= (const PcpTagBase &other)
virtual PcpTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getPcp () const
virtual void setPcp (int pcp)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const PcpTagBase &)=delete
Protected Attributes
int pcp = -1
Private Member Functions
void copy (const PcpTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/common/PcpTag.msg:16 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class PcpTagBase extends TagBase
{
    int pcp = -1;
}
Constructor & Destructor Documentation
PcpTagBase() [1/2]
inet::PcpTagBase::PcpTagBase ()
PcpTagBase() [2/2]
inet::PcpTagBase::PcpTagBase (const PcpTagBase & other)
~PcpTagBase()
virtual inet::PcpTagBase::~PcpTagBase () virtual
Member Function Documentation
copy()
void inet::PcpTagBase::copy (const PcpTagBase & other) private
dup()
virtual PcpTagBase* inet::PcpTagBase::dup () const inline override virtual
Reimplemented in inet::PcpInd, and inet::PcpReq.
 {return new PcpTagBase(*this);}
getPcp()
virtual int inet::PcpTagBase::getPcp () const virtual
Referenced by inet::PcpClassifier::classifyPacket(), inet::PcpTrafficClassClassifier::classifyPacket(), inet::Ieee8021qTagEpdHeaderInserter::processPacket(), and inet::Ieee8021qTagTpidHeaderInserter::processPacket().
operator=()
PcpTagBase& inet::PcpTagBase::operator= (const PcpTagBase & other)
operator==()
bool inet::PcpTagBase::operator== (const PcpTagBase &) protected delete
parsimPack()
virtual void inet::PcpTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::PcpInd, and inet::PcpReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::PcpTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::PcpInd, and inet::PcpReq.
Referenced by inet::doParsimUnpacking().
setPcp()
virtual void inet::PcpTagBase::setPcp (int pcp) virtual
Member Data Documentation
pcp
int inet::PcpTagBase::pcp = -1 protected
The documentation for this class was generated from the following file:
PcpTag_m.h