INET Framework for OMNeT++/OMNEST: inet::DestreamingReceiver Class Reference
inet::DestreamingReceiver Class Reference
#include <DestreamingReceiver.h>
Public Member Functions
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
Public Member Functions inherited from inet::StreamingReceiverBase
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::PacketReceiverBase
virtual ~PacketReceiverBase ()
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessageWhenUp (cMessage *message) override
virtual void sendToUpperLayer (Packet *packet)
virtual void receivePacketStart (cPacket *packet, cGate *gate, bps datarate)
virtual void receivePacketEnd (cPacket *packet, cGate *gate, bps datarate)
virtual void receivePacketProgress (cPacket *packet, cGate *gate, bps datarate, b position, simtime_t timePosition, b extraProcessableLength, simtime_t extraProcessableDuration)
Protected Member Functions inherited from inet::PacketReceiverBase
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleMessageWhenDown (cMessage *message) override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual Packet * decodePacket (Signal *signal) const
Protected Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< PacketProcessorBase >
enum State
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Protected Attributes inherited from inet::StreamingReceiverBase
cChannel * transmissionChannel = nullptr
Protected Attributes inherited from inet::PacketReceiverBase
const NetworkInterface * networkInterface = nullptr
bps rxDatarate = bps(NaN)
cGate * inputGate = nullptr
cGate * outputGate = nullptr
IPassivePacketSink * consumer = nullptr
Signal * rxSignal = nullptr
Protected Attributes inherited from inet::OperationalMixin< PacketProcessorBase >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Member Function Documentation
handleMessageWhenUp()
void inet::DestreamingReceiver::handleMessageWhenUp (cMessage * message) override protected virtual
Reimplemented from inet::PacketReceiverBase.
 {
     if (message->getArrivalGate() == inputGate) {
         auto signal = check_and_cast<Signal *>(message);
         if (!signal->isUpdate())
             receivePacketStart(signal, inputGate, rxDatarate);
         else if (signal->getRemainingDuration() == 0)
             receivePacketEnd(signal, inputGate, rxDatarate);
         else {
             auto packet = check_and_cast<Packet *>(signal->getEncapsulatedPacket());
             simtime_t timePosition = signal->getDuration() - signal->getRemainingDuration();
             b position(std::floor(packet->getTotalLength().get() * timePosition.dbl() / signal->getDuration().dbl()));
             receivePacketProgress(signal, inputGate, rxDatarate, position, timePosition, b(0), 0);
         }
     }
     else
         StreamingReceiverBase::handleMessage(message);
     updateDisplayString();
 }
initialize()
void inet::DestreamingReceiver::initialize (int stage) override protected virtual
Reimplemented from inet::StreamingReceiverBase.
 {
     StreamingReceiverBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         setTxUpdateSupport(true);
         inputGate->setDeliverImmediately(true);
     }
 }
receivePacketEnd()
void inet::DestreamingReceiver::receivePacketEnd (cPacket * packet, cGate * gate, bps datarate) protected virtual
 {
     take(cpacket);
     auto signal = check_and_cast<Signal *>(cpacket);
     EV_INFO << "Receiving signal end from channel" << EV_FIELD(signal) << EV_ENDL;
     delete rxSignal;
     rxSignal = signal;
     emit(receptionEndedSignal, rxSignal);
     auto packet = decodePacket(rxSignal);
     handlePacketProcessed(packet);
     sendToUpperLayer(packet);
     delete rxSignal;
     rxSignal = nullptr;
 }
Referenced by handleMessageWhenUp().
receivePacketProgress()
void inet::DestreamingReceiver::receivePacketProgress (cPacket * packet, cGate * gate, bps datarate, b position, simtime_t timePosition, b extraProcessableLength, simtime_t extraProcessableDuration) protected virtual
 {
     take(cpacket);
     auto signal = check_and_cast<Signal *>(cpacket);
     EV_INFO << "Receiving signal progress from channel" << EV_FIELD(signal) << EV_ENDL;
     delete rxSignal;
     rxSignal = signal;
 }
Referenced by handleMessageWhenUp().
receivePacketStart()
void inet::DestreamingReceiver::receivePacketStart (cPacket * packet, cGate * gate, bps datarate) protected virtual
 {
     ASSERT(rxSignal == nullptr);
     take(cpacket);
     auto signal = check_and_cast<Signal *>(cpacket);
     EV_INFO << "Receiving signal start from channel" << EV_FIELD(signal) << EV_ENDL;
     rxSignal = signal;
     emit(receptionStartedSignal, rxSignal);
 }
Referenced by handleMessageWhenUp().
sendToUpperLayer()
void inet::DestreamingReceiver::sendToUpperLayer (Packet * packet) protected virtual
 {
     pushOrSendPacket(packet, outputGate, consumer);
 }
Referenced by receivePacketEnd().
supportsPacketStreaming()
virtual bool inet::DestreamingReceiver::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return gate == inputGate; }
The documentation for this class was generated from the following files:
DestreamingReceiver.h
DestreamingReceiver.cc