INET Framework for OMNeT++/OMNEST: inet::visualizer::QueueVisualizerBase Class Reference
inet::visualizer::QueueVisualizerBase Class Reference abstract
#include <QueueVisualizerBase.h>
Classes
class QueueVisitor
class QueueVisualization
Parameters
bool displayQueues = false
QueueFilter queueFilter
cFigure::Color color
double width
double height
double spacing
Placement placementHint
double placementPriority
std::vector< const QueueVisualization * > queueVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void refreshDisplay () const override
virtual void preDelete (cComponent *root) override
virtual QueueVisualization * createQueueVisualization (queueing::IPacketQueue *queue) const =0
virtual void addQueueVisualization (const QueueVisualization *queueVisualization)
virtual void addQueueVisualizations ()
virtual void removeQueueVisualization (const QueueVisualization *queueVisualization)
virtual void refreshQueueVisualization (const QueueVisualization *queueVisualization) const =0
virtual void removeAllQueueVisualizations ()
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addQueueVisualization()
void inet::visualizer::QueueVisualizerBase::addQueueVisualization (const QueueVisualization * queueVisualization) protected virtual
Reimplemented in inet::visualizer::QueueCanvasVisualizer.
 {
     queueVisualizations.push_back(queueVisualization);
 }
Referenced by inet::visualizer::QueueCanvasVisualizer::addQueueVisualization(), and addQueueVisualizations().
addQueueVisualizations()
void inet::visualizer::QueueVisualizerBase::addQueueVisualizations () protected virtual
 {
     QueueVisitor queueVisitor;
     visualizationSubjectModule->forEachChild(&queueVisitor);
     for (auto queue : queueVisitor.queues) {
         if (queueFilter.matches(queue))
             addQueueVisualization(createQueueVisualization(queue));
     }
 }
Referenced by handleParameterChange(), and initialize().
createQueueVisualization()
virtual QueueVisualization* inet::visualizer::QueueVisualizerBase::createQueueVisualization (queueing::IPacketQueue * queue) const protected pure virtual
Implemented in inet::visualizer::QueueCanvasVisualizer, and inet::visualizer::QueueOsgVisualizer.
Referenced by addQueueVisualizations().
handleParameterChange()
void inet::visualizer::QueueVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         removeAllQueueVisualizations();
         addQueueVisualizations();
     }
 }
initialize()
void inet::visualizer::QueueVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::QueueCanvasVisualizer, and inet::visualizer::QueueOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayQueues = par("displayQueues");
         queueFilter.setPattern(par("queueFilter"));
         color = cFigure::parseColor(par("color"));
         width = par("width");
         height = par("height");
         spacing = par("spacing");
         placementHint = parsePlacement(par("placementHint"));
         placementPriority = par("placementPriority");
     }
     else if (stage == INITSTAGE_LAST) {
         if (displayQueues)
             addQueueVisualizations();
     }
 }
Referenced by inet::visualizer::QueueOsgVisualizer::initialize(), and inet::visualizer::QueueCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::QueueVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayQueues)
         removeAllQueueVisualizations();
 }
refreshDisplay()
void inet::visualizer::QueueVisualizerBase::refreshDisplay () const override protected virtual
 {
     for (auto queueVisualization : queueVisualizations)
         refreshQueueVisualization(queueVisualization);
 }
refreshQueueVisualization()
virtual void inet::visualizer::QueueVisualizerBase::refreshQueueVisualization (const QueueVisualization * queueVisualization) const protected pure virtual
Implemented in inet::visualizer::QueueCanvasVisualizer, and inet::visualizer::QueueOsgVisualizer.
Referenced by refreshDisplay().
removeAllQueueVisualizations()
void inet::visualizer::QueueVisualizerBase::removeAllQueueVisualizations () protected virtual
 {
     for (auto queueVisualization : std::vector<const QueueVisualization *>(queueVisualizations)) {
         removeQueueVisualization(queueVisualization);
         delete queueVisualization;
     }
 }
Referenced by handleParameterChange(), and preDelete().
removeQueueVisualization()
void inet::visualizer::QueueVisualizerBase::removeQueueVisualization (const QueueVisualization * queueVisualization) protected virtual
Reimplemented in inet::visualizer::QueueCanvasVisualizer.
 {
     queueVisualizations.erase(std::remove(queueVisualizations.begin(), queueVisualizations.end(), queueVisualization), queueVisualizations.end());
 }
Referenced by removeAllQueueVisualizations(), and inet::visualizer::QueueCanvasVisualizer::removeQueueVisualization().
Member Data Documentation
color
cFigure::Color inet::visualizer::QueueVisualizerBase::color protected
Referenced by inet::visualizer::QueueCanvasVisualizer::createQueueVisualization(), and initialize().
displayQueues
bool inet::visualizer::QueueVisualizerBase::displayQueues = false protected
Referenced by initialize(), and preDelete().
height
double inet::visualizer::QueueVisualizerBase::height protected
Referenced by inet::visualizer::QueueCanvasVisualizer::createQueueVisualization(), and initialize().
placementHint
Placement inet::visualizer::QueueVisualizerBase::placementHint protected
Referenced by inet::visualizer::QueueCanvasVisualizer::addQueueVisualization(), and initialize().
placementPriority
double inet::visualizer::QueueVisualizerBase::placementPriority protected
Referenced by inet::visualizer::QueueCanvasVisualizer::addQueueVisualization(), and initialize().
queueFilter
QueueFilter inet::visualizer::QueueVisualizerBase::queueFilter protected
Referenced by addQueueVisualizations(), and initialize().
queueVisualizations
std::vector<const QueueVisualization *> inet::visualizer::QueueVisualizerBase::queueVisualizations protected
Referenced by addQueueVisualization(), inet::visualizer::QueueOsgVisualizer::initialize(), refreshDisplay(), removeAllQueueVisualizations(), and removeQueueVisualization().
spacing
double inet::visualizer::QueueVisualizerBase::spacing protected
Referenced by inet::visualizer::QueueCanvasVisualizer::createQueueVisualization(), and initialize().
width
double inet::visualizer::QueueVisualizerBase::width protected
Referenced by inet::visualizer::QueueCanvasVisualizer::createQueueVisualization(), and initialize().
The documentation for this class was generated from the following files:
QueueVisualizerBase.h
QueueVisualizerBase.cc