INET Framework for OMNeT++/OMNEST: inet::ModulePathAddress Class Reference
inet::ModulePathAddress Class Reference
This class provides network addresses using the module path to interface modules.
#include <ModulePathAddress.h>
Public Member Functions
ModulePathAddress ()
ModulePathAddress (int id)
int getId () const
bool tryParse (const char *addr)
bool isUnspecified () const
bool isUnicast () const
bool isMulticast () const
bool isBroadcast () const
bool operator== (const ModulePathAddress &addr1) const
Returns equals(addr).
bool operator!= (const ModulePathAddress &addr1) const
Returns !equals(addr).
bool operator< (const ModulePathAddress &addr1) const
Compares two addresses.
bool operator<= (const ModulePathAddress &addr1) const
bool operator> (const ModulePathAddress &addr1) const
bool operator>= (const ModulePathAddress &addr1) const
std::string str () const
Static Public Member Functions
static bool maskedAddrAreEqual (const ModulePathAddress &addr1, const ModulePathAddress &addr2, int prefixLength)
Private Attributes
int id
Detailed Description
This class provides network addresses using the module path to interface modules.
The module path address supports unspecified, broadcast and multicast addresses too. TODO add support for partial module paths addresses to allow prefix routing
Constructor & Destructor Documentation
ModulePathAddress() [1/2]
inet::ModulePathAddress::ModulePathAddress () inline
 : id(0) {}
ModulePathAddress() [2/2]
inet::ModulePathAddress::ModulePathAddress (int id) inline
 : id(id) {}
Member Function Documentation
getId()
int inet::ModulePathAddress::getId () const inline
 { return id; }
Referenced by inet::L3Address::mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), and inet::L3Address::set().
isBroadcast()
bool inet::ModulePathAddress::isBroadcast () const inline
 { return id == -1; }
Referenced by inet::L3Address::isBroadcast().
isMulticast()
bool inet::ModulePathAddress::isMulticast () const inline
 { return id < -1; }
Referenced by inet::L3Address::isMulticast().
isUnicast()
bool inet::ModulePathAddress::isUnicast () const inline
 { return id > 0; }
Referenced by inet::L3Address::isUnicast().
isUnspecified()
bool inet::ModulePathAddress::isUnspecified () const inline
 { return id == 0; }
Referenced by inet::L3Address::isUnspecified().
maskedAddrAreEqual()
static bool inet::ModulePathAddress::maskedAddrAreEqual (const ModulePathAddress & addr1, const ModulePathAddress & addr2, int prefixLength) inline static
 { return addr1.id == addr2.id; }
Referenced by inet::L3Address::matches().
operator!=()
bool inet::ModulePathAddress::operator!= (const ModulePathAddress & addr1) const inline
Returns !equals(addr).
 { return id != addr1.id; }
operator<()
bool inet::ModulePathAddress::operator< (const ModulePathAddress & addr1) const inline
Compares two addresses.
 { return id < addr1.id; }
operator<=()
bool inet::ModulePathAddress::operator<= (const ModulePathAddress & addr1) const inline
 { return id <= addr1.id; }
operator==()
bool inet::ModulePathAddress::operator== (const ModulePathAddress & addr1) const inline
Returns equals(addr).
 { return id == addr1.id; }
operator>()
bool inet::ModulePathAddress::operator> (const ModulePathAddress & addr1) const inline
 { return id > addr1.id; }
operator>=()
bool inet::ModulePathAddress::operator>= (const ModulePathAddress & addr1) const inline
 { return id >= addr1.id; }
str()
std::string inet::ModulePathAddress::str () const
 {
     if (id == 0) {
         return "<unspec>";
     }
     else if (id == -1) {
         return "<BROADCAST>";
     }
     else if (id < -1) {
         std::ostringstream s;
         s << "<MULTICAST ID=" << -id << ">";
         return s.str();
     }
     else /* if (id > 0) */ {
         cModule *module = getSimulation()->getModule(id);
         if (module) {
             std::string fullPath = module->getFullPath();
             return strchr(fullPath.c_str(), '.') + 1;
         }
         std::ostringstream s;
         s << "<module ID=" << id << ">";
         return s.str();
     }
 }
Referenced by inet::L3Address::str().
tryParse()
bool inet::ModulePathAddress::tryParse (const char * addr)
 {
     cModule *module = getModuleByRelativePath(getSimulation()->getSystemModule(), addr);
     if (module) {
         // accepts network interface modules only:
         if (isNetworkNode(module))
             return false;
         IInterfaceTable *ift = L3AddressResolver().findInterfaceTableOf(findContainingNode(module));
         if (ift == nullptr)
             return false;
         if (ift->findInterfaceByInterfaceModule(module) == nullptr)
             return false;
         id = module->getId();
         return true;
     }
     return false;
 }
Referenced by inet::L3Address::tryParse(), and inet::L3AddressResolver::tryParse().
Member Data Documentation
id
int inet::ModulePathAddress::id private
Referenced by maskedAddrAreEqual(), operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
ModulePathAddress.h
ModulePathAddress.cc