INET Framework for OMNeT++/OMNEST: inet::sctp::SctpQueue Class Reference
inet::sctp::SctpQueue Class Reference
Abstract base class for SCTP receive queues.
#include <SctpQueue.h>
Public Types
typedef std::map< uint32_t, SctpDataVariables * > PayloadQueue
Public Member Functions
SctpQueue ()
Constructor.
SctpQueue (SctpAssociation *assoc)
~SctpQueue ()
Virtual destructor.
bool checkAndInsertChunk (const uint32_t key, SctpDataVariables *chunk)
SctpDataVariables * getAndExtractChunk (const uint32_t tsn)
SctpDataVariables * extractMessage ()
void printQueue () const
uint32_t getQueueSize () const
SctpDataVariables * getFirstChunk () const
cMessage * getMsg (const uint32_t key) const
SctpDataVariables * getChunk (const uint32_t key) const
SctpDataVariables * getChunkFast (const uint32_t tsn, bool &firstTime)
void removeMsg (const uint32_t key)
bool deleteMsg (const uint32_t tsn)
int32_t getNumBytes () const
SctpDataVariables * dequeueChunkBySSN (const uint16_t ssn)
uint32_t getSizeOfFirstChunk (const L3Address &remoteAddress)
uint16_t getFirstSsnInQueue (const uint16_t sid)
void findEarliestOutstandingTsnsForPath (const L3Address &remoteAddress, uint32_t &earliestOutstandingTsn, uint32_t &rtxEarliestOutstandingTsn) const
Public Attributes
PayloadQueue payloadQueue
Protected Attributes
SctpAssociation * assoc
Private Attributes
PayloadQueue::iterator GetChunkFastIterator
Detailed Description
Abstract base class for SCTP receive queues.
This class represents data received by SCTP but not yet passed up to the application. The class also accomodates for selective retransmission, i.e. also acts as a segment buffer.
This class goes hand-in-hand with SctpSendQueue.
This class is polymorphic because depending on where and how you use the SCTP model you might have different ideas about "sending data" on a simulated connection: you might want to transmit real bytes, "dummy" (byte count only), cMessage objects, etc; see discussion at SctpSendQueue. Different subclasses can be written to accomodate different needs.
See also
SctpSendQueue
Member Typedef Documentation
PayloadQueue
typedef std::map<uint32_t, SctpDataVariables *> inet::sctp::SctpQueue::PayloadQueue
Constructor & Destructor Documentation
SctpQueue() [1/2]
inet::sctp::SctpQueue::SctpQueue ()
Constructor.
 {
     assoc = nullptr;
 }
SctpQueue() [2/2]
inet::sctp::SctpQueue::SctpQueue (SctpAssociation * assoc)
 {
     assoc = assoc_;
 }
~SctpQueue()
inet::sctp::SctpQueue::~SctpQueue ()
Virtual destructor.
 {
     for (auto& elem : payloadQueue) {
         SctpDataVariables *chunk = elem.second;
         delete chunk->userData;
     }
     if (!payloadQueue.empty()) {
         payloadQueue.clear();
     }
 }
Member Function Documentation
checkAndInsertChunk()
bool inet::sctp::SctpQueue::checkAndInsertChunk (const uint32_t key, SctpDataVariables * chunk)
 {
     auto found = payloadQueue.find(key);
     if (found != payloadQueue.end()) {
         return false;
     }
     payloadQueue[key] = chunk;
     return true;
 }
Referenced by inet::sctp::SctpReceiveStream::enqueueNewDataChunk(), inet::sctp::SctpAssociation::handleChunkReportedAsMissing(), inet::sctp::SctpAssociation::moveChunkToOtherPath(), inet::sctp::SctpAssociation::putInDeliveryQ(), inet::sctp::SctpAssociation::putInTransmissionQ(), and inet::sctp::SctpAssociation::sendOnPath().
deleteMsg()
bool inet::sctp::SctpQueue::deleteMsg (const uint32_t tsn)
 {
     auto iterator = payloadQueue.find(tsn);
     if (iterator != payloadQueue.end()) {
         SctpDataVariables *chunk = iterator->second;
         cMessage *msg = check_and_cast<cMessage *>(chunk->userData);
         delete msg;
         payloadQueue.erase(iterator);
         return true;
     }
     return false;
 }
Referenced by inet::sctp::SctpAssociation::makeRoomForTsn().
dequeueChunkBySSN()
SctpDataVariables * inet::sctp::SctpQueue::dequeueChunkBySSN (const uint16_t ssn)
 {
     for (auto iterator = payloadQueue.begin();
          iterator != payloadQueue.end(); iterator++)
     {
         SctpDataVariables *chunk = iterator->second;
         if ((iterator->second->ssn == ssn) &&
             (iterator->second->bbit) &&
             (iterator->second->ebit))
         {
             payloadQueue.erase(iterator);
             return chunk;
         }
     }
     return nullptr;
 }
Referenced by inet::sctp::SctpReceiveStream::enqueueNewDataChunk(), and inet::sctp::SctpAssociation::putInDeliveryQ().
extractMessage()
SctpDataVariables * inet::sctp::SctpQueue::extractMessage ()
 {
     if (!payloadQueue.empty()) {
         auto iterator = payloadQueue.begin();
         SctpDataVariables *chunk = iterator->second;
         payloadQueue.erase(iterator);
         return chunk;
     }
     return nullptr;
 }
Referenced by inet::sctp::SctpAssociation::pushUlp().
findEarliestOutstandingTsnsForPath()
void inet::sctp::SctpQueue::findEarliestOutstandingTsnsForPath (const L3Address & remoteAddress, uint32_t & earliestOutstandingTsn, uint32_t & rtxEarliestOutstandingTsn) const
 {
     bool findEarliestOutstandingTsn = true;
     bool findRTXEarliestOutstandingTsn = true;
     for (const auto& elem : payloadQueue) {
         const SctpDataVariables *chunk = elem.second;
         if (chunk->getLastDestination() == remoteAddress) {
             // ====== Find earliest outstanding TSNs ===========================
             if (chunk->hasBeenAcked == false) {
                 if ((findEarliestOutstandingTsn) &&
                     (chunk->numberOfRetransmissions == 0))
                 {
                     earliestOutstandingTsn = chunk->tsn;
                 }
                 findEarliestOutstandingTsn = false;
                 if ((findRTXEarliestOutstandingTsn) &&
                     (chunk->numberOfRetransmissions > 0))
                 {
                     rtxEarliestOutstandingTsn = chunk->tsn;
                 }
                 findRTXEarliestOutstandingTsn = false;
             }
         }
     }
 }
Referenced by inet::sctp::SctpAssociation::checkPseudoCumAck().
getAndExtractChunk()
SctpDataVariables * inet::sctp::SctpQueue::getAndExtractChunk (const uint32_t tsn)
 {
     if (!payloadQueue.empty()) {
         auto iterator = payloadQueue.find(tsn);
         SctpDataVariables *chunk = iterator->second;
         payloadQueue.erase(iterator);
         return chunk;
     }
     return nullptr;
 }
Referenced by inet::sctp::SctpReceiveStream::enqueueNewDataChunk(), inet::sctp::SctpAssociation::nonRenegablyAckChunk(), and inet::sctp::SctpReceiveStream::reassemble().
getChunk()
SctpDataVariables * inet::sctp::SctpQueue::getChunk (const uint32_t key) const
 {
     PayloadQueue::const_iterator iterator = payloadQueue.find(tsn);
     if (iterator != payloadQueue.end()) {
         SctpDataVariables *chunk = iterator->second;
         return chunk;
     }
     return nullptr;
 }
Referenced by inet::sctp::SctpAssociation::chunkHasBeenAcked(), inet::sctp::SctpReceiveStream::enqueueNewDataChunk(), inet::sctp::SctpAssociation::handleChunkReportedAsMissing(), inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::nonRenegablyAckChunk(), inet::sctp::SctpAssociation::processSackArrived(), inet::sctp::SctpReceiveStream::reassemble(), and inet::sctp::SctpAssociation::renegablyAckChunk().
getChunkFast()
SctpDataVariables * inet::sctp::SctpQueue::getChunkFast (const uint32_t tsn, bool & firstTime)
 {
     if (!firstTime) {
         if (GetChunkFastIterator != payloadQueue.end()) {
             SctpDataVariables *chunk = GetChunkFastIterator->second;
             if (chunk->tsn == tsn) {
                 GetChunkFastIterator++;
                 return chunk; // Found the right TSN!
             }
         }
         // TSN not found -> needs regular TSN lookup.
     }
     GetChunkFastIterator = payloadQueue.find(tsn);
     if (GetChunkFastIterator != payloadQueue.end()) {
         SctpDataVariables *chunk = GetChunkFastIterator->second;
         GetChunkFastIterator++;
         firstTime = false;
         return chunk;
     }
     return nullptr;
 }
Referenced by inet::sctp::SctpAssociation::processSackArrived().
getFirstChunk()
SctpDataVariables * inet::sctp::SctpQueue::getFirstChunk () const
 {
     PayloadQueue::const_iterator iterator = payloadQueue.begin();
     SctpDataVariables *chunk = iterator->second;
     return chunk;
 }
getFirstSsnInQueue()
uint16_t inet::sctp::SctpQueue::getFirstSsnInQueue (const uint16_t sid)
 {
     return payloadQueue.begin()->second->ssn;
 }
Referenced by inet::sctp::SctpAssociation::processForwardTsnArrived().
getMsg()
cMessage * inet::sctp::SctpQueue::getMsg (const uint32_t key) const
 {
     PayloadQueue::const_iterator iterator = payloadQueue.find(tsn);
     if (iterator != payloadQueue.end()) {
         SctpDataVariables *chunk = iterator->second;
         cMessage *msg = check_and_cast<cMessage *>(chunk->userData);
         return msg;
     }
     return nullptr;
 }
getNumBytes()
int32_t inet::sctp::SctpQueue::getNumBytes () const
 {
     int32_t qb = 0;
     for (const auto& elem : payloadQueue) {
         qb += (elem.second->len / 8);
     }
     return qb;
 }
getQueueSize()
uint32_t inet::sctp::SctpQueue::getQueueSize () const
 {
     return payloadQueue.size();
 }
Referenced by inet::sctp::SctpAssociation::calculateRcvBuffer(), inet::sctp::SctpReceiveStream::enqueueNewDataChunk(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::processForwardTsnArrived(), inet::sctp::SctpAssociation::pushUlp(), inet::sctp::SctpAssociation::putInDeliveryQ(), inet::sctp::SctpAssociation::putInTransmissionQ(), inet::sctp::SctpAssociation::sendOnPath(), and inet::sctp::SctpAssociation::stateEntered().
getSizeOfFirstChunk()
uint32_t inet::sctp::SctpQueue::getSizeOfFirstChunk (const L3Address & remoteAddress)
 {
     for (PayloadQueue::const_iterator iterator = payloadQueue.begin();
          iterator != payloadQueue.end(); ++iterator)
     {
         const SctpDataVariables *chunk = iterator->second;
         if (chunk->getNextDestination() == remoteAddress) {
             return chunk->booksize;
         }
     }
     return 0;
 }
Referenced by inet::sctp::SctpAssociation::sendOnPath().
printQueue()
void inet::sctp::SctpQueue::printQueue () const
 {
     EV_DEBUG << "Queue contents:\n";
     for (const auto& elem : payloadQueue) {
         const uint32_t key = elem.first;
         const SctpDataVariables *chunk = elem.second;
         EV_DEBUG << key << ":\t"
                  << "lastDestination=" << chunk->getLastDestination()
                  << " nextDestination=" << chunk->getNextDestination()
                  << " hasBeenAcked=" << chunk->hasBeenAcked
                  << " countsAsOutstanding=" << chunk->countsAsOutstanding
                  << " numberOfRetransmissions=" << chunk->numberOfRetransmissions
                  << endl;
     }
     EV_DEBUG << endl;
 }
removeMsg()
void inet::sctp::SctpQueue::removeMsg (const uint32_t key)
 {
     auto iterator = payloadQueue.find(tsn);
     payloadQueue.erase(iterator);
 }
Referenced by inet::sctp::SctpAssociation::nonRenegablyAckChunk(), and inet::sctp::SctpAssociation::renegablyAckChunk().
Member Data Documentation
assoc
SctpAssociation* inet::sctp::SctpQueue::assoc protected
Referenced by SctpQueue().
GetChunkFastIterator
PayloadQueue::iterator inet::sctp::SctpQueue::GetChunkFastIterator private
Referenced by getChunkFast().
payloadQueue
PayloadQueue inet::sctp::SctpQueue::payloadQueue
Referenced by inet::sctp::SctpAssociation::advancePeerTsn(), checkAndInsertChunk(), inet::sctp::SctpAssociation::chunkReschedulingControl(), inet::sctp::SctpAssociation::createForwardTsnChunk(), inet::sctp::SctpAssociation::cwndUpdateAfterSack(), deleteMsg(), inet::sctp::SctpAssociation::dequeueAckedChunks(), dequeueChunkBySSN(), extractMessage(), findEarliestOutstandingTsnsForPath(), getAndExtractChunk(), getChunk(), getChunkFast(), getFirstChunk(), getFirstSsnInQueue(), getMsg(), getNumBytes(), inet::sctp::SctpAssociation::getOutboundDataChunk(), getQueueSize(), getSizeOfFirstChunk(), inet::sctp::SctpAssociation::loadPacket(), inet::sctp::SctpAssociation::peekAbandonedChunk(), printQueue(), inet::sctp::SctpAssociation::process_TIMEOUT_RTX(), inet::sctp::SctpAssociation::processPacketDropArrived(), inet::sctp::SctpAssociation::processSackArrived(), inet::sctp::SctpAssociation::pushUlp(), inet::sctp::SctpAssociation::putInTransmissionQ(), inet::sctp::Sctp::removeAssociation(), removeMsg(), inet::sctp::SctpAssociation::storePacket(), and ~SctpQueue().
The documentation for this class was generated from the following files:
SctpQueue.h
SctpQueue.cc