INET Framework for OMNeT++/OMNEST: inet::Ipv6NdOptions Class Reference
inet::Ipv6NdOptions Class Reference
Class generated from inet/networklayer/icmpv6/Ipv6NdMessage.msg:111 by opp_msgtool.
#include <Ipv6NdMessage_m.h>
Public Member Functions
Ipv6NdOptions ()
Ipv6NdOptions (const Ipv6NdOptions &other)
virtual ~Ipv6NdOptions ()
Ipv6NdOptions & operator= (const Ipv6NdOptions &other)
virtual Ipv6NdOptions * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setOptionArraySize (size_t size)
virtual size_t getOptionArraySize () const
virtual const Ipv6NdOption * getOption (size_t k) const
virtual Ipv6NdOption * getOptionForUpdate (size_t k)
virtual void setOption (size_t k, Ipv6NdOption *option)
virtual Ipv6NdOption * removeOption (size_t k)
Ipv6NdOption * dropOption (size_t k)
virtual void insertOption (size_t k, Ipv6NdOption *option)
void insertOption (Ipv6NdOption *option)
virtual void appendOption (Ipv6NdOption *option)
virtual void eraseOption (size_t k)
virtual const Ipv6NdOption * findOption (Ipv6NdOptionTypes t) const
virtual Ipv6NdOption * findOptionForUpdate (Ipv6NdOptionTypes t)
virtual void insertUniqueOption (size_t k, Ipv6NdOption *option)
virtual void insertUniqueOption (Ipv6NdOption *option)
Protected Member Functions
bool operator== (const Ipv6NdOptions &)=delete
Protected Attributes
Ipv6NdOption ** option = nullptr
size_t option_arraysize = 0
Private Member Functions
void copy (const Ipv6NdOptions &other)
Detailed Description
Class generated from inet/networklayer/icmpv6/Ipv6NdMessage.msg:111 by opp_msgtool.
class Ipv6NdOptions extends cObject
{
    @packetData;
    // TLV Options:
    Ipv6NdOption *option[] @owned;  // on end of message
}
Constructor & Destructor Documentation
Ipv6NdOptions() [1/2]
inet::Ipv6NdOptions::Ipv6NdOptions ()
Ipv6NdOptions() [2/2]
inet::Ipv6NdOptions::Ipv6NdOptions (const Ipv6NdOptions & other)
~Ipv6NdOptions()
virtual inet::Ipv6NdOptions::~Ipv6NdOptions () virtual
Member Function Documentation
appendOption()
virtual void inet::Ipv6NdOptions::appendOption (Ipv6NdOption * option) virtual
Referenced by inet::deserializeIpv6NdOptions(), and insertUniqueOption().
copy()
void inet::Ipv6NdOptions::copy (const Ipv6NdOptions & other) private
dropOption()
Ipv6NdOption* inet::Ipv6NdOptions::dropOption (size_t k) inline
 {return removeOption(k);}
dup()
virtual Ipv6NdOptions* inet::Ipv6NdOptions::dup () const inline override virtual
 {return new Ipv6NdOptions(*this);}
eraseOption()
virtual void inet::Ipv6NdOptions::eraseOption (size_t k) virtual
findOption()
const Ipv6NdOption * inet::Ipv6NdOptions::findOption (Ipv6NdOptionTypes t) const virtual
 {
     for (size_t i = 0; i < option_arraysize; i++) {
         if (option[i]->getType() == t)
             return option[i];
     }
     return nullptr;
 }
Referenced by insertUniqueOption(), inet::Ipv6NeighbourDiscovery::processNaForIncompleteNceState(), inet::Ipv6NeighbourDiscovery::processNaForOtherNceStates(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6NeighbourDiscovery::processRsPacket(), and inet::Ipv6NeighbourDiscovery::validateRsPacket().
findOptionForUpdate()
Ipv6NdOption * inet::Ipv6NdOptions::findOptionForUpdate (Ipv6NdOptionTypes t) virtual
 {
     for (size_t i = 0; i < option_arraysize; i++) {
         if (option[i]->getType() == t)
             return getOptionForUpdate(i);
     }
     return nullptr;
 }
getOption()
virtual const Ipv6NdOption* inet::Ipv6NdOptions::getOption (size_t k) const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfo(), inet::serializeIpv6NdOptions(), and inet::Ipv6NeighbourDiscovery::validateRaPacket().
getOptionArraySize()
virtual size_t inet::Ipv6NdOptions::getOptionArraySize () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfo(), inet::serializeIpv6NdOptions(), and inet::Ipv6NeighbourDiscovery::validateRaPacket().
getOptionForUpdate()
virtual Ipv6NdOption* inet::Ipv6NdOptions::getOptionForUpdate (size_t k) inline virtual
 { return const_cast<Ipv6NdOption *>(const_cast<Ipv6NdOptions*>(this)->getOption(k));}
Referenced by findOptionForUpdate().
insertOption() [1/2]
void inet::Ipv6NdOptions::insertOption (Ipv6NdOption * option) inline
 {appendOption(option);}
insertOption() [2/2]
virtual void inet::Ipv6NdOptions::insertOption (size_t k, Ipv6NdOption * option) virtual
insertUniqueOption() [1/2]
virtual void inet::Ipv6NdOptions::insertUniqueOption (Ipv6NdOption * option) inline virtual
 { insertUniqueOption(option_arraysize, option); }
Referenced by insertUniqueOption().
insertUniqueOption() [2/2]
void inet::Ipv6NdOptions::insertUniqueOption (size_t k, Ipv6NdOption * option) virtual
 {
     if (findOption(option->getType()))
         throw cRuntimeError("Option %i already exists", (int)option->getType());
     appendOption(option);
 }
operator=()
Ipv6NdOptions& inet::Ipv6NdOptions::operator= (const Ipv6NdOptions & other)
operator==()
bool inet::Ipv6NdOptions::operator== (const Ipv6NdOptions &) protected delete
parsimPack()
virtual void inet::Ipv6NdOptions::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6NdOptions::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
removeOption()
virtual Ipv6NdOption* inet::Ipv6NdOptions::removeOption (size_t k) virtual
setOption()
virtual void inet::Ipv6NdOptions::setOption (size_t k, Ipv6NdOption * option) virtual
setOptionArraySize()
virtual void inet::Ipv6NdOptions::setOptionArraySize (size_t size) virtual
Member Data Documentation
option
Ipv6NdOption* * inet::Ipv6NdOptions::option = nullptr protected
Referenced by findOption(), findOptionForUpdate(), and insertUniqueOption().
option_arraysize
size_t inet::Ipv6NdOptions::option_arraysize = 0 protected
Referenced by findOption(), and findOptionForUpdate().
The documentation for this class was generated from the following files:
Ipv6NdMessage_m.h
Ipv6NdMessage.cc