INET Framework for OMNeT++/OMNEST: inet::ieee80211::IAckHandler Class Reference
inet::ieee80211::IAckHandler Class Reference abstract
#include <IAckHandler.h>
Public Member Functions
virtual ~IAckHandler ()
virtual bool isEligibleToTransmit (const Ptr< const Ieee80211DataOrMgmtHeader > &header)=0
virtual bool isOutstandingFrame (const Ptr< const Ieee80211DataOrMgmtHeader > &header)=0
virtual void frameGotInProgress (const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader)=0
Constructor & Destructor Documentation
~IAckHandler()
virtual inet::ieee80211::IAckHandler::~IAckHandler () inline virtual
 {}
Member Function Documentation
frameGotInProgress()
virtual void inet::ieee80211::IAckHandler::frameGotInProgress (const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) pure virtual
Implemented in inet::ieee80211::QosAckHandler, and inet::ieee80211::AckHandler.
Referenced by inet::ieee80211::InProgressFrames::ensureHasFrameToTransmit(), and inet::ieee80211::InProgressFrames::getPendingFrameFor().
isEligibleToTransmit()
virtual bool inet::ieee80211::IAckHandler::isEligibleToTransmit (const Ptr< const Ieee80211DataOrMgmtHeader > & header) pure virtual
Implemented in inet::ieee80211::QosAckHandler, and inet::ieee80211::AckHandler.
Referenced by inet::ieee80211::InProgressFrames::getFrameToTransmit(), inet::ieee80211::InProgressFrames::getPendingFrameFor(), and inet::ieee80211::InProgressFrames::hasEligibleFrameToTransmit().
isOutstandingFrame()
virtual bool inet::ieee80211::IAckHandler::isOutstandingFrame (const Ptr< const Ieee80211DataOrMgmtHeader > & header) pure virtual
Implemented in inet::ieee80211::QosAckHandler, and inet::ieee80211::AckHandler.
Referenced by inet::ieee80211::InProgressFrames::getOutstandingFrames().
The documentation for this class was generated from the following file:
IAckHandler.h