INET Framework for OMNeT++/OMNEST: inet::Ipv6Header Class Reference
inet::Ipv6Header Class Reference
Class generated from inet/networklayer/ipv6/Ipv6Header.msg:50 by opp_msgtool.
#include <Ipv6Header_m.h>
Public Member Functions
Ipv6Header ()
Ipv6Header (const Ipv6Header &other)
virtual ~Ipv6Header ()
Ipv6Header & operator= (const Ipv6Header &other)
virtual Ipv6Header * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getVersion () const
virtual void setVersion (uint8_t version)
virtual const Ipv6Address & getSrcAddress () const
virtual Ipv6Address & getSrcAddressForUpdate ()
virtual void setSrcAddress (const Ipv6Address &srcAddress)
virtual const Ipv6Address & getDestAddress () const
virtual Ipv6Address & getDestAddressForUpdate ()
virtual void setDestAddress (const Ipv6Address &destAddress)
virtual B getPayloadLength () const
virtual void setPayloadLength (B payloadLength)
virtual short getTrafficClass () const
virtual void setTrafficClass (short trafficClass)
virtual unsigned int getFlowLabel () const
virtual void setFlowLabel (unsigned int flowLabel)
virtual short getHopLimit () const
virtual void setHopLimit (short hopLimit)
virtual IpProtocolId getProtocolId () const
virtual void setProtocolId (IpProtocolId protocolId)
virtual void setExtensionHeaderArraySize (size_t size)
virtual size_t getExtensionHeaderArraySize () const
virtual const Ipv6ExtensionHeader * getExtensionHeader (size_t k) const
virtual Ipv6ExtensionHeader * getExtensionHeaderForUpdate (size_t k)
virtual void setExtensionHeader (size_t k, Ipv6ExtensionHeader *extensionHeader)
virtual Ipv6ExtensionHeader * removeExtensionHeader (size_t k)
Ipv6ExtensionHeader * dropExtensionHeader (size_t k)
virtual void insertExtensionHeader (size_t k, Ipv6ExtensionHeader *extensionHeader)
void insertExtensionHeader (Ipv6ExtensionHeader *extensionHeader)
virtual void appendExtensionHeader (Ipv6ExtensionHeader *extensionHeader)
virtual void eraseExtensionHeader (size_t k)
virtual short getDscp () const
virtual void setDscp (short dscp)
virtual short getEcn () const
virtual void setEcn (short ecn)
virtual Ipv6ExtensionHeader * findExtensionHeaderByTypeForUpdate (IpProtocolId extensionType, int index=0)
Returns the extension header of the specified type, or nullptr.
virtual const Ipv6ExtensionHeader * findExtensionHeaderByType (IpProtocolId extensionType, int index=0) const
virtual void addExtensionHeader (Ipv6ExtensionHeader *eh)
Adds an extension header to the datagram.
virtual B calculateHeaderByteLength () const
Calculates the length of the Ipv6 header plus the extension headers.
virtual B calculateUnfragmentableHeaderByteLength () const
Calculates the length of the unfragmentable part of Ipv6 header plus the extension headers.
virtual B calculateFragmentLength () const
Calculates the length of the payload and extension headers after the Fragment Header.
virtual Ipv6ExtensionHeader * removeFirstExtensionHeader ()
Removes and returns the first extension header of this datagram.
virtual Ipv6ExtensionHeader * removeExtensionHeader (IpProtocolId extensionType)
Removes and returns the first extension header with the given type.
virtual L3Address getSourceAddress () const override
virtual void setSourceAddress (const L3Address &address) override
virtual L3Address getDestinationAddress () const override
virtual void setDestinationAddress (const L3Address &address) override
virtual const Protocol * getProtocol () const override
virtual void setProtocol (const Protocol *protocol) override
virtual bool isFragment () const override
Public Member Functions inherited from inet::NetworkHeaderBase
NetworkHeaderBase ()
NetworkHeaderBase (const NetworkHeaderBase &other)
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ipv6Header &)=delete
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Protected Attributes
uint8_t version = 6
Ipv6Address srcAddress
Ipv6Address destAddress
B payloadLength = B(-1)
short trafficClass = 0
unsigned int flowLabel = 0
short hopLimit = 0
IpProtocolId protocolId = IP_PROT_NONE
Ipv6ExtensionHeader ** extensionHeader = nullptr
size_t extensionHeader_arraysize = 0
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const Ipv6Header &other)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Class generated from inet/networklayer/ipv6/Ipv6Header.msg:50 by opp_msgtool.
//
// Ipv6 datagram. RFC 2460 Section 3.
//
// Header fields not explicitly modelled:
//    - payload length: will be calculated from encapsulated message length
//      and extension headers' length
//
class Ipv6Header extends NetworkHeaderBase
{
    chunkLength = IPv6_HEADER_BYTES;
    uint8_t version = 6;
    Ipv6Address srcAddress;
    Ipv6Address destAddress;
    B payloadLength = B(-1);    // The size of the payload in octets, including any extension headers. The length is set to zero when a Hop-by-Hop extension header carries a Jumbo Payload option.
    short trafficClass;    // @bits(8) Traffic Class
    // OMNeT++ 6.0:
    // short __dscp @custom @getter(getDscp) @setter(setDscp);  // @bit(6), maps to bits 0-5 of trafficClass
    // short __ecn @custom @getter(getEcn) @setter(setEcn);  // @bit(2),  maps to bits 6-7 of trafficClass
    unsigned int flowLabel;
    short hopLimit = 0;
    IpProtocolId protocolId = IP_PROT_NONE;
    Ipv6ExtensionHeader *extensionHeader[] @owned; // array of extension headers, subclassed from ~Ipv6ExtensionHeader
}
Constructor & Destructor Documentation
Ipv6Header() [1/2]
inet::Ipv6Header::Ipv6Header ()
Ipv6Header() [2/2]
inet::Ipv6Header::Ipv6Header (const Ipv6Header & other)
~Ipv6Header()
virtual inet::Ipv6Header::~Ipv6Header () virtual
Member Function Documentation
addExtensionHeader()
void inet::Ipv6Header::addExtensionHeader (Ipv6ExtensionHeader * eh) virtual
Adds an extension header to the datagram.
The extension headers are stored in the order specified in RFC 2460 4.1.
 {
     ASSERT((eh->getByteLength() >= B(1)) && (eh->getByteLength().get() % 8 == 0));
     int thisOrder = eh->getOrder();
     size_t i;
     for (i = 0; i < extensionHeader_arraysize; i++) {
         int thatOrder = extensionHeader[i]->getOrder();
         if (thisOrder != -1 && thatOrder > thisOrder)
             break;
         else if (thisOrder == thatOrder) {
             if (thisOrder == 1) // first IP_PROT_IPv6EXT_DEST has order 1, second IP_PROT_IPv6EXT_DEST has order 6
                 thisOrder = 6;
             else if (thisOrder != -1)
                 throw cRuntimeError(this, "addExtensionHeader() duplicate extension header: %d",
                         eh->getExtensionType());
         }
     }
     // insert at position atPos, shift up the rest of the array
     insertExtensionHeader(i, eh);
 }
appendExtensionHeader()
virtual void inet::Ipv6Header::appendExtensionHeader (Ipv6ExtensionHeader * extensionHeader) virtual
calculateFragmentLength()
B inet::Ipv6Header::calculateFragmentLength () const virtual
Calculates the length of the payload and extension headers after the Fragment Header.
Note: it is assumed that headers are ordered as described in RFC 2460 4.1.
 {
     B len = getChunkLength() - IPv6_HEADER_BYTES;
     size_t i;
     for (i = 0; i < extensionHeader_arraysize; i++) {
         len -= extensionHeader[i]->getByteLength();
         if (extensionHeader[i]->getExtensionType() == IP_PROT_IPv6EXT_FRAGMENT)
             break;
     }
     ASSERT2(i < extensionHeader_arraysize, "IPv6Datagram::calculateFragmentLength() called on non-fragment datagram");
     return len;
 }
calculateHeaderByteLength()
B inet::Ipv6Header::calculateHeaderByteLength () const virtual
Calculates the length of the Ipv6 header plus the extension headers.
 {
     B len = B(40);
     for (size_t i = 0; i < extensionHeader_arraysize; i++)
         len += extensionHeader[i]->getByteLength();
     return len;
 }
calculateUnfragmentableHeaderByteLength()
B inet::Ipv6Header::calculateUnfragmentableHeaderByteLength () const virtual
Calculates the length of the unfragmentable part of Ipv6 header plus the extension headers.
Note: it is assumed that headers are ordered as described in RFC 2460 4.1.
 {
     size_t firstFragmentableExtensionIndex = 0;
     for (size_t i = extensionHeader_arraysize; i > 0; i--) {
         int type = extensionHeader[i - 1]->getExtensionType();
         if (type == IP_PROT_IPv6EXT_ROUTING || type == IP_PROT_IPv6EXT_HOP) {
             firstFragmentableExtensionIndex = i;
             break;
         }
     }
     B len = B(40);
     for (size_t i = 0; i < firstFragmentableExtensionIndex; i++)
         len += extensionHeader[i]->getByteLength();
     return len;
 }
copy()
void inet::Ipv6Header::copy (const Ipv6Header & other) private
dropExtensionHeader()
Ipv6ExtensionHeader* inet::Ipv6Header::dropExtensionHeader (size_t k) inline
 {return removeExtensionHeader(k);}
dup()
virtual Ipv6Header* inet::Ipv6Header::dup () const inline override virtual
Reimplemented from inet::NetworkHeaderBase.
 {return new Ipv6Header(*this);}
Referenced by inet::Ipv6FragBuf::addFragment().
eraseExtensionHeader()
virtual void inet::Ipv6Header::eraseExtensionHeader (size_t k) virtual
Referenced by removeExtensionHeader(), and removeFirstExtensionHeader().
findExtensionHeaderByType()
const Ipv6ExtensionHeader * inet::Ipv6Header::findExtensionHeaderByType (IpProtocolId extensionType, int index = 0) const virtual
 {
     for (size_t i = 0; i < extensionHeader_arraysize; i++)
         if (extensionHeader[i]->getExtensionType() == extensionType) {
             if (index == 0)
                 return extensionHeader[i];
             else
                 index--;
         }
     return nullptr;
 }
Referenced by findExtensionHeaderByTypeForUpdate().
findExtensionHeaderByTypeForUpdate()
Ipv6ExtensionHeader * inet::Ipv6Header::findExtensionHeaderByTypeForUpdate (IpProtocolId extensionType, int index = 0) virtual
Returns the extension header of the specified type, or nullptr.
If index is 0, then the first, if 1 then the second extension is returned. (The datagram might contain two Destination Options extension.)
 {
     handleChange();
     return const_cast<Ipv6ExtensionHeader *>(const_cast<Ipv6Header *>(this)->findExtensionHeaderByType(extensionType, index));
 }
getDestAddress()
virtual const Ipv6Address& inet::Ipv6Header::getDestAddress () const virtual
Referenced by inet::Ipv6FragBuf::addFragment().
getDestAddressForUpdate()
virtual Ipv6Address& inet::Ipv6Header::getDestAddressForUpdate () inline virtual
 { handleChange();return const_cast<Ipv6Address&>(const_cast<Ipv6Header*>(this)->getDestAddress());}
getDestinationAddress()
virtual L3Address inet::Ipv6Header::getDestinationAddress () const inline override virtual
Implements inet::NetworkHeaderBase.
 { return L3Address(getDestAddress()); }
getDscp()
short inet::Ipv6Header::getDscp () const virtual
 {
     return (trafficClass & 0xfc) >> 2;
 }
getEcn()
short inet::Ipv6Header::getEcn () const virtual
 {
     return trafficClass & 0x03;
 }
getExtensionHeader()
virtual const Ipv6ExtensionHeader* inet::Ipv6Header::getExtensionHeader (size_t k) const virtual
getExtensionHeaderArraySize()
virtual size_t inet::Ipv6Header::getExtensionHeaderArraySize () const virtual
getExtensionHeaderForUpdate()
virtual Ipv6ExtensionHeader* inet::Ipv6Header::getExtensionHeaderForUpdate (size_t k) inline virtual
 { handleChange();return const_cast<Ipv6ExtensionHeader *>(const_cast<Ipv6Header*>(this)->getExtensionHeader(k));}
getFlowLabel()
virtual unsigned int inet::Ipv6Header::getFlowLabel () const virtual
getHopLimit()
virtual short inet::Ipv6Header::getHopLimit () const virtual
getPayloadLength()
virtual B inet::Ipv6Header::getPayloadLength () const virtual
getProtocol()
virtual const Protocol* inet::Ipv6Header::getProtocol () const inline override virtual
Implements inet::NetworkHeaderBase.
 { return ProtocolGroup::ipprotocol.findProtocol(getProtocolId()); }
getProtocolId()
virtual IpProtocolId inet::Ipv6Header::getProtocolId () const virtual
Referenced by inet::QosClassifier::getUserPriority(), and inet::Icmpv6::processICMPv6Message().
getSourceAddress()
virtual L3Address inet::Ipv6Header::getSourceAddress () const inline override virtual
Implements inet::NetworkHeaderBase.
 { return L3Address(getSrcAddress()); }
getSrcAddress()
virtual const Ipv6Address& inet::Ipv6Header::getSrcAddress () const virtual
Referenced by inet::Ipv6FragBuf::addFragment(), and inet::xMIPv6::validateType2RH().
getSrcAddressForUpdate()
virtual Ipv6Address& inet::Ipv6Header::getSrcAddressForUpdate () inline virtual
 { handleChange();return const_cast<Ipv6Address&>(const_cast<Ipv6Header*>(this)->getSrcAddress());}
getTrafficClass()
virtual short inet::Ipv6Header::getTrafficClass () const virtual
getVersion()
virtual uint8_t inet::Ipv6Header::getVersion () const virtual
insertExtensionHeader() [1/2]
void inet::Ipv6Header::insertExtensionHeader (Ipv6ExtensionHeader * extensionHeader) inline
 {appendExtensionHeader(extensionHeader);}
insertExtensionHeader() [2/2]
virtual void inet::Ipv6Header::insertExtensionHeader (size_t k, Ipv6ExtensionHeader * extensionHeader) virtual
Referenced by addExtensionHeader().
isFragment()
virtual bool inet::Ipv6Header::isFragment () const inline override virtual
Implements inet::NetworkHeaderBase.
 { return findExtensionHeaderByType(IP_PROT_IPv6EXT_FRAGMENT) != nullptr; }
operator=()
Ipv6Header& inet::Ipv6Header::operator= (const Ipv6Header & other)
operator==()
bool inet::Ipv6Header::operator== (const Ipv6Header &) protected delete
parsimPack()
virtual void inet::Ipv6Header::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6Header::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
removeExtensionHeader() [1/2]
Ipv6ExtensionHeader * inet::Ipv6Header::removeExtensionHeader (IpProtocolId extensionType) virtual
Removes and returns the first extension header with the given type.
 {
     handleChange();
     if (extensionHeader_arraysize == 0)
         return nullptr;
     for (size_t i = 0; i < extensionHeader_arraysize; i++) {
         if (extensionHeader[i]->getExtensionType() == extensionType) {
             Ipv6ExtensionHeader *eh = removeExtensionHeader(i);
             eraseExtensionHeader(i);
             return eh;
         }
     }
     return nullptr;
 }
removeExtensionHeader() [2/2]
virtual Ipv6ExtensionHeader* inet::Ipv6Header::removeExtensionHeader (size_t k) virtual
Referenced by removeExtensionHeader(), and removeFirstExtensionHeader().
removeFirstExtensionHeader()
Ipv6ExtensionHeader * inet::Ipv6Header::removeFirstExtensionHeader () virtual
Removes and returns the first extension header of this datagram.
 {
     handleChange();
     if (extensionHeader_arraysize == 0)
         return nullptr;
     Ipv6ExtensionHeader *eh = removeExtensionHeader(0);
     eraseExtensionHeader(0);
     return eh;
 }
setDestAddress()
virtual void inet::Ipv6Header::setDestAddress (const Ipv6Address & destAddress) virtual
Referenced by inet::xMIPv6::processType2RH().
setDestinationAddress()
virtual void inet::Ipv6Header::setDestinationAddress (const L3Address & address) inline override virtual
Implements inet::NetworkHeaderBase.
 { setDestAddress(address.toIpv6()); }
setDscp()
void inet::Ipv6Header::setDscp (short dscp) virtual
 {
     setTrafficClass(((dscp & 0x3f) << 2) | (trafficClass & 0x03));
 }
setEcn()
void inet::Ipv6Header::setEcn (short ecn) virtual
 {
     setTrafficClass((trafficClass & 0xfc) | (ecn & 0x03));
 }
setExtensionHeader()
virtual void inet::Ipv6Header::setExtensionHeader (size_t k, Ipv6ExtensionHeader * extensionHeader) virtual
setExtensionHeaderArraySize()
virtual void inet::Ipv6Header::setExtensionHeaderArraySize (size_t size) virtual
setFlowLabel()
virtual void inet::Ipv6Header::setFlowLabel (unsigned int flowLabel) virtual
setHopLimit()
virtual void inet::Ipv6Header::setHopLimit (short hopLimit) virtual
setPayloadLength()
virtual void inet::Ipv6Header::setPayloadLength (B payloadLength) virtual
setProtocol()
virtual void inet::Ipv6Header::setProtocol (const Protocol * protocol) inline override virtual
Implements inet::NetworkHeaderBase.
 { setProtocolId(static_cast<IpProtocolId>(ProtocolGroup::ipprotocol.getProtocolNumber(protocol))); }
setProtocolId()
virtual void inet::Ipv6Header::setProtocolId (IpProtocolId protocolId) virtual
setSourceAddress()
virtual void inet::Ipv6Header::setSourceAddress (const L3Address & address) inline override virtual
Implements inet::NetworkHeaderBase.
 { setSrcAddress(address.toIpv6()); }
setSrcAddress()
virtual void inet::Ipv6Header::setSrcAddress (const Ipv6Address & srcAddress) virtual
Referenced by inet::xMIPv6::processHoAOpt().
setTrafficClass()
virtual void inet::Ipv6Header::setTrafficClass (short trafficClass) virtual
Referenced by setDscp(), and setEcn().
setVersion()
virtual void inet::Ipv6Header::setVersion (uint8_t version) virtual
Member Data Documentation
destAddress
Ipv6Address inet::Ipv6Header::destAddress protected
extensionHeader
Ipv6ExtensionHeader* * inet::Ipv6Header::extensionHeader = nullptr protected
Referenced by addExtensionHeader(), calculateFragmentLength(), calculateHeaderByteLength(), calculateUnfragmentableHeaderByteLength(), findExtensionHeaderByType(), and removeExtensionHeader().
extensionHeader_arraysize
size_t inet::Ipv6Header::extensionHeader_arraysize = 0 protected
Referenced by addExtensionHeader(), calculateFragmentLength(), calculateHeaderByteLength(), calculateUnfragmentableHeaderByteLength(), findExtensionHeaderByType(), removeExtensionHeader(), and removeFirstExtensionHeader().
flowLabel
unsigned int inet::Ipv6Header::flowLabel = 0 protected
hopLimit
short inet::Ipv6Header::hopLimit = 0 protected
payloadLength
B inet::Ipv6Header::payloadLength = B(-1) protected
protocolId
IpProtocolId inet::Ipv6Header::protocolId = IP_PROT_NONE protected
srcAddress
Ipv6Address inet::Ipv6Header::srcAddress protected
trafficClass
short inet::Ipv6Header::trafficClass = 0 protected
Referenced by getDscp(), getEcn(), setDscp(), and setEcn().
version
uint8_t inet::Ipv6Header::version = 6 protected
The documentation for this class was generated from the following files:
Ipv6Header_m.h
Ipv6Header.cc