INET Framework for OMNeT++/OMNEST: inet::EigrpMsgReq Class Reference
inet::EigrpMsgReq Class Reference
#include <EigrpMsgReq.h>
Public Member Functions
EigrpMsgReq (const char *name=nullptr)
EigrpMsgReq (const EigrpMsgReq &other)
EigrpMsgReq & operator= (const EigrpMsgReq &other)
virtual EigrpMsgReq * dup () const
bool isMsgReliable ()
int findMsgRoute (int routeId) const
Public Member Functions inherited from inet::EigrpMsgReq_Base
virtual ~EigrpMsgReq_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int8_t getOpcode () const
virtual void setOpcode (int8_t opcode)
virtual bool getGoodbyeMsg () const
virtual void setGoodbyeMsg (bool goodbyeMsg)
virtual bool getInit () const
virtual void setInit (bool init)
virtual bool getCr () const
virtual void setCr (bool cr)
virtual bool getRs () const
virtual void setRs (bool rs)
virtual bool getEot () const
virtual void setEot (bool eot)
virtual int getDestNeighbor () const
virtual void setDestNeighbor (int destNeighbor)
virtual int getDestInterface () const
virtual void setDestInterface (int destInterface)
virtual uint32_t getSeqNumber () const
virtual void setSeqNumber (uint32_t seqNumber)
virtual uint32_t getAckNumber () const
virtual void setAckNumber (uint32_t ackNumber)
virtual int getNumOfAck () const
virtual void setNumOfAck (int numOfAck)
virtual void setRoutesArraySize (size_t size)
virtual size_t getRoutesArraySize () const
virtual const EigrpMsgRoute & getRoutes (size_t k) const
virtual EigrpMsgRoute & getRoutesForUpdate (size_t k)
virtual void setRoutes (size_t k, const EigrpMsgRoute &routes)
virtual void insertRoutes (size_t k, const EigrpMsgRoute &routes)
void insertRoutes (const EigrpMsgRoute &routes)
virtual void appendRoutes (const EigrpMsgRoute &routes)
virtual void eraseRoutes (size_t k)
Additional Inherited Members
Protected Member Functions inherited from inet::EigrpMsgReq_Base
bool operator== (const EigrpMsgReq_Base &)=delete
EigrpMsgReq_Base (const char *name=nullptr, short kind=0)
EigrpMsgReq_Base (const EigrpMsgReq_Base &other)
EigrpMsgReq_Base & operator= (const EigrpMsgReq_Base &other)
Protected Attributes inherited from inet::EigrpMsgReq_Base
int8_t opcode = 0
bool goodbyeMsg = false
bool init = false
bool cr = false
bool rs = false
bool eot = false
int destNeighbor = 0
int destInterface = 0
uint32_t seqNumber = 0
uint32_t ackNumber = 0
int numOfAck = 0
EigrpMsgRoute * routes = nullptr
size_t routes_arraysize = 0
Constructor & Destructor Documentation
EigrpMsgReq() [1/2]
inet::EigrpMsgReq::EigrpMsgReq (const char * name = nullptr) inline
 : EigrpMsgReq_Base(name) {}
Referenced by dup().
EigrpMsgReq() [2/2]
inet::EigrpMsgReq::EigrpMsgReq (const EigrpMsgReq & other) inline
 : EigrpMsgReq_Base(other) {}
Member Function Documentation
dup()
virtual EigrpMsgReq* inet::EigrpMsgReq::dup () const inline virtual
Reimplemented from inet::EigrpMsgReq_Base.
 { return new EigrpMsgReq(*this); }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
findMsgRoute()
int inet::EigrpMsgReq::findMsgRoute (int routeId) const
 {
     EigrpMsgRoute rt;
     for (unsigned i = 0; i < getRoutesArraySize(); i++) {
         rt = getRoutes(i);
         if (rt.routeId == routeId) {
             return i;
         }
     }
     return -1;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::pushMsgRouteToQueue(), and inet::eigrp::EigrpIpv6Pdm::pushMsgRouteToQueue().
isMsgReliable()
bool inet::EigrpMsgReq::isMsgReliable () inline
 { return getOpcode() != EIGRP_HELLO_MSG; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::sendMsg().
operator=()
EigrpMsgReq& inet::EigrpMsgReq::operator= (const EigrpMsgReq & other) inline
     { EigrpMsgReq_Base::operator=(other); return *this; }
The documentation for this class was generated from the following files:
EigrpMsgReq.h
EigrpMsgReq.cc