INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_ScanConfirm Class Reference
inet::ieee80211::Ieee80211Prim_ScanConfirm Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:121 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_ScanConfirm ()
Ieee80211Prim_ScanConfirm (const Ieee80211Prim_ScanConfirm &other)
virtual ~Ieee80211Prim_ScanConfirm ()
Ieee80211Prim_ScanConfirm & operator= (const Ieee80211Prim_ScanConfirm &other)
virtual Ieee80211Prim_ScanConfirm * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setBssListArraySize (size_t size)
virtual size_t getBssListArraySize () const
virtual const Ieee80211Prim_BssDescription & getBssList (size_t k) const
virtual Ieee80211Prim_BssDescription & getBssListForUpdate (size_t k)
virtual void setBssList (size_t k, const Ieee80211Prim_BssDescription &bssList)
virtual void insertBssList (size_t k, const Ieee80211Prim_BssDescription &bssList)
void insertBssList (const Ieee80211Prim_BssDescription &bssList)
virtual void appendBssList (const Ieee80211Prim_BssDescription &bssList)
virtual void eraseBssList (size_t k)
Public Member Functions inherited from inet::ieee80211::Ieee80211PrimConfirm
Ieee80211PrimConfirm ()
Ieee80211PrimConfirm (const Ieee80211PrimConfirm &other)
virtual ~Ieee80211PrimConfirm ()
Ieee80211PrimConfirm & operator= (const Ieee80211PrimConfirm &other)
virtual Ieee80211PrimResultCode getResultCode () const
virtual void setResultCode (Ieee80211PrimResultCode resultCode)
Protected Member Functions
bool operator== (const Ieee80211Prim_ScanConfirm &)=delete
Protected Member Functions inherited from inet::ieee80211::Ieee80211PrimConfirm
bool operator== (const Ieee80211PrimConfirm &)=delete
Protected Attributes
Ieee80211Prim_BssDescription * bssList = nullptr
size_t bssList_arraysize = 0
Protected Attributes inherited from inet::ieee80211::Ieee80211PrimConfirm
Ieee80211PrimResultCode resultCode = static_cast<inet::ieee80211::Ieee80211PrimResultCode>(-1)
Private Member Functions
void copy (const Ieee80211Prim_ScanConfirm &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:121 by opp_msgtool.
//
// Losely based on MLME-SCAN.confirm
// Possible result codes: SUCCESS, INVALID_PARAMETERS
//
class Ieee80211Prim_ScanConfirm extends Ieee80211PrimConfirm
{
    Ieee80211Prim_BssDescription bssList[];
}
Constructor & Destructor Documentation
Ieee80211Prim_ScanConfirm() [1/2]
inet::ieee80211::Ieee80211Prim_ScanConfirm::Ieee80211Prim_ScanConfirm ()
Ieee80211Prim_ScanConfirm() [2/2]
inet::ieee80211::Ieee80211Prim_ScanConfirm::Ieee80211Prim_ScanConfirm (const Ieee80211Prim_ScanConfirm & other)
~Ieee80211Prim_ScanConfirm()
virtual inet::ieee80211::Ieee80211Prim_ScanConfirm::~Ieee80211Prim_ScanConfirm () virtual
Member Function Documentation
appendBssList()
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::appendBssList (const Ieee80211Prim_BssDescription & bssList) virtual
copy()
void inet::ieee80211::Ieee80211Prim_ScanConfirm::copy (const Ieee80211Prim_ScanConfirm & other) private
dup()
virtual Ieee80211Prim_ScanConfirm* inet::ieee80211::Ieee80211Prim_ScanConfirm::dup () const inline override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimConfirm.
 {return new Ieee80211Prim_ScanConfirm(*this);}
eraseBssList()
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::eraseBssList (size_t k) virtual
getBssList()
virtual const Ieee80211Prim_BssDescription& inet::ieee80211::Ieee80211Prim_ScanConfirm::getBssList (size_t k) const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::chooseBSS(), inet::ieee80211::Ieee80211AgentSta::dumpAPList(), and inet::ieee80211::Ieee80211AgentSta::processScanConfirm().
getBssListArraySize()
virtual size_t inet::ieee80211::Ieee80211Prim_ScanConfirm::getBssListArraySize () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::chooseBSS(), inet::ieee80211::Ieee80211AgentSta::dumpAPList(), and inet::ieee80211::Ieee80211AgentSta::processScanConfirm().
getBssListForUpdate()
virtual Ieee80211Prim_BssDescription& inet::ieee80211::Ieee80211Prim_ScanConfirm::getBssListForUpdate (size_t k) inline virtual
 { return const_cast<Ieee80211Prim_BssDescription&>(const_cast<Ieee80211Prim_ScanConfirm*>(this)->getBssList(k));}
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
insertBssList() [1/2]
void inet::ieee80211::Ieee80211Prim_ScanConfirm::insertBssList (const Ieee80211Prim_BssDescription & bssList) inline
 {appendBssList(bssList);}
insertBssList() [2/2]
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::insertBssList (size_t k, const Ieee80211Prim_BssDescription & bssList) virtual
operator=()
Ieee80211Prim_ScanConfirm& inet::ieee80211::Ieee80211Prim_ScanConfirm::operator= (const Ieee80211Prim_ScanConfirm & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_ScanConfirm::operator== (const Ieee80211Prim_ScanConfirm &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimConfirm.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimConfirm.
Referenced by inet::ieee80211::doParsimUnpacking().
setBssList()
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::setBssList (size_t k, const Ieee80211Prim_BssDescription & bssList) virtual
setBssListArraySize()
virtual void inet::ieee80211::Ieee80211Prim_ScanConfirm::setBssListArraySize (size_t size) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
Member Data Documentation
bssList
Ieee80211Prim_BssDescription* inet::ieee80211::Ieee80211Prim_ScanConfirm::bssList = nullptr protected
bssList_arraysize
size_t inet::ieee80211::Ieee80211Prim_ScanConfirm::bssList_arraysize = 0 protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h