INET Framework for OMNeT++/OMNEST: inet::RsvpPathMsg Class Reference
inet::RsvpPathMsg Class Reference
Class generated from inet/networklayer/rsvpte/RsvpPathMsg.msg:19 by opp_msgtool.
#include <RsvpPathMsg_m.h>
Public Member Functions
RsvpPathMsg ()
RsvpPathMsg (const RsvpPathMsg &other)
virtual ~RsvpPathMsg ()
RsvpPathMsg & operator= (const RsvpPathMsg &other)
virtual RsvpPathMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const RsvpHopObj & getHop () const
virtual RsvpHopObj & getHopForUpdate ()
virtual void setHop (const RsvpHopObj &hop)
virtual const LabelRequestObj & getLabel_request () const
virtual LabelRequestObj & getLabel_requestForUpdate ()
virtual void setLabel_request (const LabelRequestObj &label_request)
virtual const SenderDescriptor_t & getSender_descriptor () const
virtual SenderDescriptor_t & getSender_descriptorForUpdate ()
virtual void setSender_descriptor (const SenderDescriptor_t &sender_descriptor)
virtual const EroVector & getERO () const
virtual EroVector & getEROForUpdate ()
virtual void setERO (const EroVector &ERO)
virtual int getColor () const
virtual void setColor (int color)
Ipv4Address getSrcAddress ()
int getLspId () const
Ipv4Address getNHOP ()
Ipv4Address getLIH ()
double getBW ()
SenderTemplateObj & getSenderTemplateForUpdate ()
const SenderTemplateObj & getSenderTemplate () const
void setSenderTemplate (const SenderTemplateObj &s)
SenderTspecObj & getSenderTspecForUpdate ()
const SenderTspecObj & getSenderTspec ()
void setSenderTspec (const SenderTspecObj &s)
Public Member Functions inherited from inet::RsvpPacket
RsvpPacket ()
RsvpPacket (const RsvpPacket &other)
virtual ~RsvpPacket ()
RsvpPacket & operator= (const RsvpPacket &other)
virtual const SessionObj & getSession () const
virtual SessionObj & getSessionForUpdate ()
virtual void setSession (const SessionObj &session)
virtual bool getChecksumValid () const
virtual void setChecksumValid (bool checksumValid)
Ipv4Address getDestAddress ()
RsvpPacket common part.
int getTunnelId ()
int getExTunnelId ()
int getSetupPri ()
int getHoldingPri ()
bool isInSession (SessionObj *s) const
Public Member Functions inherited from inet::RsvpMessage
RsvpMessage ()
RsvpMessage (const RsvpMessage &other)
virtual ~RsvpMessage ()
RsvpMessage & operator= (const RsvpMessage &other)
virtual int getRsvpKind () const
virtual void setRsvpKind (int rsvpKind)
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const RsvpPathMsg &)=delete
Protected Member Functions inherited from inet::RsvpPacket
bool operator== (const RsvpPacket &)=delete
Protected Member Functions inherited from inet::RsvpMessage
bool operator== (const RsvpMessage &)=delete
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Protected Attributes
RsvpHopObj hop
LabelRequestObj label_request
SenderDescriptor_t sender_descriptor
EroVector ERO
int color = 0
Protected Attributes inherited from inet::RsvpPacket
SessionObj session
bool checksumValid = true
Protected Attributes inherited from inet::RsvpMessage
int rsvpKind = 0
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const RsvpPathMsg &other)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Class generated from inet/networklayer/rsvpte/RsvpPathMsg.msg:19 by opp_msgtool.
//
// FIXME missing documentation
//
class RsvpPathMsg extends RsvpPacket
{
    RsvpHopObj hop;
    LabelRequestObj label_request;
    SenderDescriptor_t sender_descriptor;
    EroVector ERO;
    int color;
    rsvpKind = PATH_MESSAGE;
}
Constructor & Destructor Documentation
RsvpPathMsg() [1/2]
inet::RsvpPathMsg::RsvpPathMsg ()
RsvpPathMsg() [2/2]
inet::RsvpPathMsg::RsvpPathMsg (const RsvpPathMsg & other)
~RsvpPathMsg()
virtual inet::RsvpPathMsg::~RsvpPathMsg () virtual
Member Function Documentation
copy()
void inet::RsvpPathMsg::copy (const RsvpPathMsg & other) private
dup()
virtual RsvpPathMsg* inet::RsvpPathMsg::dup () const inline override virtual
Reimplemented from inet::RsvpPacket.
 {return new RsvpPathMsg(*this);}
getBW()
double inet::RsvpPathMsg::getBW () inline
 { return getSender_descriptor().Sender_Tspec_Object.req_bandwidth; }
getColor()
virtual int inet::RsvpPathMsg::getColor () const virtual
getERO()
virtual const EroVector& inet::RsvpPathMsg::getERO () const virtual
Referenced by inet::RsvpTe::print().
getEROForUpdate()
virtual EroVector& inet::RsvpPathMsg::getEROForUpdate () inline virtual
 { handleChange();return const_cast<EroVector&>(const_cast<RsvpPathMsg*>(this)->getERO());}
getHop()
virtual const RsvpHopObj& inet::RsvpPathMsg::getHop () const virtual
getHopForUpdate()
virtual RsvpHopObj& inet::RsvpPathMsg::getHopForUpdate () inline virtual
 { handleChange();return const_cast<RsvpHopObj&>(const_cast<RsvpPathMsg*>(this)->getHop());}
getLabel_request()
virtual const LabelRequestObj& inet::RsvpPathMsg::getLabel_request () const virtual
getLabel_requestForUpdate()
virtual LabelRequestObj& inet::RsvpPathMsg::getLabel_requestForUpdate () inline virtual
 { handleChange();return const_cast<LabelRequestObj&>(const_cast<RsvpPathMsg*>(this)->getLabel_request());}
getLIH()
Ipv4Address inet::RsvpPathMsg::getLIH () inline
 { return getHop().Logical_Interface_Handle; }
getLspId()
int inet::RsvpPathMsg::getLspId () const inline
 { return getSender_descriptor().Sender_Template_Object.Lsp_Id; }
Referenced by inet::RsvpTe::print().
getNHOP()
Ipv4Address inet::RsvpPathMsg::getNHOP () inline
 { return getHop().Next_Hop_Address; }
getSender_descriptor()
virtual const SenderDescriptor_t& inet::RsvpPathMsg::getSender_descriptor () const virtual
getSender_descriptorForUpdate()
virtual SenderDescriptor_t& inet::RsvpPathMsg::getSender_descriptorForUpdate () inline virtual
 { handleChange();return const_cast<SenderDescriptor_t&>(const_cast<RsvpPathMsg*>(this)->getSender_descriptor());}
getSenderTemplate()
const SenderTemplateObj& inet::RsvpPathMsg::getSenderTemplate () const inline
 { return getSender_descriptor().Sender_Template_Object; }
getSenderTemplateForUpdate()
SenderTemplateObj& inet::RsvpPathMsg::getSenderTemplateForUpdate () inline
 { return getSender_descriptorForUpdate().Sender_Template_Object; }
getSenderTspec()
const SenderTspecObj& inet::RsvpPathMsg::getSenderTspec () inline
 { return getSender_descriptor().Sender_Tspec_Object; }
getSenderTspecForUpdate()
SenderTspecObj& inet::RsvpPathMsg::getSenderTspecForUpdate () inline
 { return getSender_descriptorForUpdate().Sender_Tspec_Object; }
getSrcAddress()
Ipv4Address inet::RsvpPathMsg::getSrcAddress () inline
 { return getSender_descriptor().Sender_Template_Object.SrcAddress; }
operator=()
RsvpPathMsg& inet::RsvpPathMsg::operator= (const RsvpPathMsg & other)
operator==()
bool inet::RsvpPathMsg::operator== (const RsvpPathMsg &) protected delete
parsimPack()
virtual void inet::RsvpPathMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::RsvpPacket.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::RsvpPathMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::RsvpPacket.
Referenced by inet::doParsimUnpacking().
setColor()
virtual void inet::RsvpPathMsg::setColor (int color) virtual
setERO()
virtual void inet::RsvpPathMsg::setERO (const EroVector & ERO) virtual
setHop()
virtual void inet::RsvpPathMsg::setHop (const RsvpHopObj & hop) virtual
setLabel_request()
virtual void inet::RsvpPathMsg::setLabel_request (const LabelRequestObj & label_request) virtual
setSender_descriptor()
virtual void inet::RsvpPathMsg::setSender_descriptor (const SenderDescriptor_t & sender_descriptor) virtual
setSenderTemplate()
void inet::RsvpPathMsg::setSenderTemplate (const SenderTemplateObj & s) inline
 { getSender_descriptorForUpdate().Sender_Template_Object = s; }
setSenderTspec()
void inet::RsvpPathMsg::setSenderTspec (const SenderTspecObj & s) inline
 { getSender_descriptorForUpdate().Sender_Tspec_Object = s; }
Member Data Documentation
color
int inet::RsvpPathMsg::color = 0 protected
ERO
EroVector inet::RsvpPathMsg::ERO protected
hop
RsvpHopObj inet::RsvpPathMsg::hop protected
label_request
LabelRequestObj inet::RsvpPathMsg::label_request protected
sender_descriptor
SenderDescriptor_t inet::RsvpPathMsg::sender_descriptor protected
The documentation for this class was generated from the following file:
RsvpPathMsg_m.h