INET Framework for OMNeT++/OMNEST: inet::physicallayer::PropagationBase Class Reference
inet::physicallayer::PropagationBase Class Reference
#include <PropagationBase.h>
Public Member Functions
PropagationBase ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual mps getPropagationSpeed () const override
Returns the theoretical propagation speed of radio signals in the range (0, +infinity).
Public Member Functions inherited from inet::physicallayer::IPropagation
virtual const IArrival * computeArrival (const ITransmission *transmission, IMobility *mobility) const =0
Returns the time and space coordinates when the transmission arrives at the object that moves with the provided mobility.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
virtual void finish () override
Protected Attributes
mps propagationSpeed
long arrivalComputationCount
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
PropagationBase()
inet::physicallayer::PropagationBase::PropagationBase ()
                                  :
     propagationSpeed(mps(NaN)),
     arrivalComputationCount(0)
 {
 }
Member Function Documentation
finish()
void inet::physicallayer::PropagationBase::finish () override protected virtual
 {
     EV_INFO << "Radio signal arrival computation count = " << arrivalComputationCount << endl;
     recordScalar("Arrival computation count", arrivalComputationCount);
 }
getPropagationSpeed()
virtual mps inet::physicallayer::PropagationBase::getPropagationSpeed () const inline override virtual
Returns the theoretical propagation speed of radio signals in the range (0, +infinity).
The value might be different from the approximation provided by the actual computation of arrival times.
Implements inet::physicallayer::IPropagation.
 { return propagationSpeed; }
initialize()
void inet::physicallayer::PropagationBase::initialize (int stage) override protected virtual
Reimplemented in inet::physicallayer::ConstantSpeedPropagation, and inet::physicallayer::ConstantTimePropagation.
 {
     if (stage == INITSTAGE_LOCAL)
         propagationSpeed = mps(par("propagationSpeed"));
 }
Referenced by inet::physicallayer::ConstantTimePropagation::initialize(), and inet::physicallayer::ConstantSpeedPropagation::initialize().
printToStream()
std::ostream & inet::physicallayer::PropagationBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::ConstantSpeedPropagation, and inet::physicallayer::ConstantTimePropagation.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(propagationSpeed);
     return stream;
 }
Referenced by inet::physicallayer::ConstantTimePropagation::printToStream(), and inet::physicallayer::ConstantSpeedPropagation::printToStream().
Member Data Documentation
arrivalComputationCount
long inet::physicallayer::PropagationBase::arrivalComputationCount mutable protected
Referenced by inet::physicallayer::ConstantTimePropagation::computeArrival(), inet::physicallayer::ConstantSpeedPropagation::computeArrival(), and finish().
propagationSpeed
mps inet::physicallayer::PropagationBase::propagationSpeed protected
Referenced by inet::physicallayer::ConstantSpeedPropagation::computeArrival(), initialize(), and printToStream().
The documentation for this class was generated from the following files:
PropagationBase.h
PropagationBase.cc