INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211NistErrorModel Class Reference
inet::physicallayer::Ieee80211NistErrorModel Class Reference
A model for the error rate for different modulations.
#include <Ieee80211NistErrorModel.h>
Public Member Functions
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::physicallayer::Ieee80211ErrorModelBase
Ieee80211ErrorModelBase ()
virtual double computePacketErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the packet error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeBitErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the bit error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeSymbolErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the symbol error rate based on SNIR, modulation, and any other physical layer characteristics.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
double calculatePe (double p, uint32_t bValue) const
double getBpskBer (double snr) const
double getQpskBer (double snr) const
double get16QamBer (double snr) const
double get64QamBer (double snr) const
double get256QamBer (double snr) const
double get1024QamBer (double snr) const
double getFecBpskBer (double snr, double nbits, uint32_t bValue) const
double getFecQpskBer (double snr, double nbits, uint32_t bValue) const
double getFec16QamBer (double snr, uint32_t nbits, uint32_t bValue) const
double getFec64QamBer (double snr, uint32_t nbits, uint32_t bValue) const
double getFec256QamBer (double snr, uint64_t nbits, uint32_t bValue) const
double getFec1024QamBer (double snr, uint64_t nbits, uint32_t bValue) const
virtual double getOFDMAndERPOFDMChunkSuccessRate (const ApskModulationBase *subcarrierModulation, const ConvolutionalCode *convolutionalCode, unsigned int bitLength, double snr) const
virtual double getDSSSAndHrDSSSChunkSuccessRate (bps bitrate, unsigned int bitLength, double snr) const
virtual double getHeaderSuccessRate (const IIeee80211Mode *mode, unsigned int headerBitLength, double snr) const override
virtual double getDataSuccessRate (const IIeee80211Mode *mode, unsigned int bitLength, double snr) const override
Protected Member Functions inherited from inet::physicallayer::Ieee80211ErrorModelBase
virtual Packet * computeCorruptedPacket (const Packet *packet, double ber) const override
virtual double getDsssDbpskSuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskSuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskCck5_5SuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskCck11SuccessRate (unsigned int bitLength, double snir) const
Protected Member Functions inherited from inet::physicallayer::ErrorModelBase
virtual void initialize (int stage) override
virtual double getScalarSnir (const ISnir *snir) const
virtual bool hasProbabilisticError (b length, double ber) const
virtual Packet * corruptBits (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptBytes (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptChunks (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptPacket (const Packet *packet, bool &isCorrupted) const
virtual Packet * computeCorruptedPacket (const ISnir *snir) const override
Additional Inherited Members
Public Types inherited from inet::physicallayer::ErrorModelBase
enum CorruptionMode {
CorruptionMode::CM_UNDEFINED = -1, CorruptionMode::CM_PACKET, CorruptionMode::CM_CHUNK, CorruptionMode::CM_BYTE,
CorruptionMode::CM_BIT
}
enum SnirMode { SnirMode::SM_UNDEFINED = -1, SnirMode::SM_MIN, SnirMode::SM_MEAN }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Attributes inherited from inet::physicallayer::Ieee80211ErrorModelBase
double spectralEfficiency1bit = 2000000.0 / 1000000.0
double spectralEfficiency2bit = 2000000.0 / 1000000.0 / 2.0
double sirPerfect = 10.0
double sirImpossible = 0.1
Protected Attributes inherited from inet::physicallayer::ErrorModelBase
CorruptionMode corruptionMode = CorruptionMode::CM_UNDEFINED
SnirMode snirMode = SnirMode::SM_UNDEFINED
double snirOffset = NaN
Detailed Description
A model for the error rate for different modulations.
For OFDM modulation, the model description and validation can be found in http://www.nsnam.org/~pei/80211ofdm.pdf. For DSSS modulations (802.11b), the model uses a separate error model.
Member Function Documentation
calculatePe()
double inet::physicallayer::Ieee80211NistErrorModel::calculatePe (double p, uint32_t bValue) const protected
 {
     double D = sqrt(4.0 * p * (1.0 - p));
     double pe = 1.0;
     if (bValue == 1) {
         // code rate 1/2, use table 3.1.1
         pe = 0.5
             * (36.0 * pow(D, 10.0) + 211.0 * pow(D, 12.0) + 1404.0 * pow(D, 14.0) + 11633.0 * pow(D, 16.0)
                + 77433.0 * pow(D, 18.0) + 502690.0 * pow(D, 20.0) + 3322763.0 * pow(D, 22.0)
                + 21292910.0 * pow(D, 24.0) + 134365911.0 * pow(D, 26.0));
     }
     else if (bValue == 2) {
         // code rate 2/3, use table 3.1.2
         pe = 1.0 / (2.0 * bValue)
             * (3.0 * pow(D, 6.0) + 70.0 * pow(D, 7.0) + 285.0 * pow(D, 8.0) + 1276.0 * pow(D, 9.0)
                + 6160.0 * pow(D, 10.0) + 27128.0 * pow(D, 11.0) + 117019.0 * pow(D, 12.0)
                + 498860.0 * pow(D, 13.0) + 2103891.0 * pow(D, 14.0) + 8784123.0 * pow(D, 15.0));
     }
     else if (bValue == 3) {
         // code rate 3/4, use table 3.1.2
         pe = 1.0 / (2.0 * bValue)
             * (42.0 * pow(D, 5.0) + 201.0 * pow(D, 6.0) + 1492.0 * pow(D, 7.0) + 10469.0 * pow(D, 8.0)
                + 62935.0 * pow(D, 9.0) + 379644.0 * pow(D, 10.0) + 2253373.0 * pow(D, 11.0)
                + 13073811.0 * pow(D, 12.0) + 75152755.0 * pow(D, 13.0) + 428005675.0 * pow(D, 14.0));
     }
     else if (bValue == 5) {
         // code rate 5/6, use table V from D. Haccoun and G. Begin, "High-Rate Punctured Convolutional Codes
         // for Viterbi Sequential Decoding", IEEE Transactions on Communications, Vol. 32, Issue 3, pp.315-319.
         pe = 1.0 / (2.0 * bValue)
             * (92.0 * pow(D, 4.0) + 528.0 * pow(D, 5.0) + 8694.0 * pow(D, 6.0) + 79453.0 * pow(D, 7.0)
                + 792114.0 * pow(D, 8.0) + 7375573.0 * pow(D, 9.0) + 67884974.0 * pow(D, 10.0)
                + 610875423.0 * pow(D, 11.0) + 5427275376.0 * pow(D, 12.0) + 47664215639.0 * pow(D, 13.0));
     }
     else {
         ASSERT(false);
     }
     return pe;
 }
Referenced by getFec1024QamBer(), getFec16QamBer(), getFec256QamBer(), getFec64QamBer(), getFecBpskBer(), and getFecQpskBer().
get1024QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::get1024QamBer (double snr) const protected
 {
     double z = std::sqrt(snr / (341.0 * 2.0));
     double ber = 31.0 / 160.0 * 0.5 * erfc(z);
     EV << "1024-Qam" << " snr=" << snr << " ber=" << ber;
     return ber;
 }
Referenced by getFec1024QamBer().
get16QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::get16QamBer (double snr) const protected
 {
     double z = sqrt(snr / (5.0 * 2.0));
     double ber = 0.75 * 0.5 * erfc(z);
     EV << "16-Qam" << " snr=" << snr << " ber=" << ber << "\n";
     return ber;
 }
Referenced by getFec16QamBer().
get256QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::get256QamBer (double snr) const protected
 {
     double z = std::sqrt(snr / (85.0 * 2.0));
     double ber = 15.0 / 32.0 * 0.5 * erfc(z);
     EV << "256-Qam" << " snr=" << snr << " ber=" << ber;
     return ber;
 }
Referenced by getFec256QamBer().
get64QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::get64QamBer (double snr) const protected
 {
     double z = sqrt(snr / (21.0 * 2.0));
     double ber = 7.0 / 12.0 * 0.5 * erfc(z);
     EV << "64-Qam" << " snr=" << snr << " ber=" << ber << "\n";
     return ber;
 }
Referenced by getFec64QamBer().
getBpskBer()
double inet::physicallayer::Ieee80211NistErrorModel::getBpskBer (double snr) const protected
 {
     double z = sqrt(snr);
     double ber = 0.5 * erfc(z);
     EV << "bpsk snr=" << snr << " ber=" << ber << "\n";
     return ber;
 }
Referenced by getFecBpskBer().
getDataSuccessRate()
double inet::physicallayer::Ieee80211NistErrorModel::getDataSuccessRate (const IIeee80211Mode * mode, unsigned int bitLength, double snr) const override protected virtual
Implements inet::physicallayer::Ieee80211ErrorModelBase.
 {
     double successRate = 0;
     if (auto ofdmMode = dynamic_cast<const Ieee80211OfdmMode *>(mode))
         successRate = getOFDMAndERPOFDMChunkSuccessRate(ofdmMode->getDataMode()->getModulation()->getSubcarrierModulation(),
                                                         ofdmMode->getDataMode()->getCode()->getConvolutionalCode(),
                                                         bitLength + b(ofdmMode->getHeaderMode()->getServiceFieldLength()).get(),
                                                         snr);
     else if (auto htMode = dynamic_cast<const Ieee80211HtMode *>(mode))
         successRate = getOFDMAndERPOFDMChunkSuccessRate(htMode->getDataMode()->getModulation()->getSubcarrierModulation(),
                                                         htMode->getDataMode()->getCode()->getForwardErrorCorrection(),
                                                         //bitLength + b(htMode->getHeaderMode()->getHTLengthLength()).get(),
                                                         bitLength,
                                                         snr);
     else if (auto vhtMode = dynamic_cast<const Ieee80211VhtMode *>(mode))
         successRate = getOFDMAndERPOFDMChunkSuccessRate(vhtMode->getDataMode()->getModulation()->getSubcarrierModulation(),
                                                         vhtMode->getDataMode()->getCode()->getForwardErrorCorrection(),
                                                         //bitLength + b(vhtMode->getHeaderMode()->getHTLengthLength()).get(),
                                                         bitLength,
                                                         snr);
     else if (auto dsssMode = dynamic_cast<const Ieee80211DsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(dsssMode->getDataMode()->getNetBitrate(), bitLength, snr);
     else if (auto hrDsssMode = dynamic_cast<const Ieee80211HrDsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(hrDsssMode->getDataMode()->getNetBitrate(), bitLength, snr);
     else
         throw cRuntimeError("Unsupported 802.11 mode");
     EV_DEBUG << "SNIR = " << snr << ", bit length = " << bitLength << ", data error rate = " << 1 - successRate << endl;
     if (successRate >= 1)
         successRate = 1;
     return successRate;
 }
getDSSSAndHrDSSSChunkSuccessRate()
double inet::physicallayer::Ieee80211NistErrorModel::getDSSSAndHrDSSSChunkSuccessRate (bps bitrate, unsigned int bitLength, double snr) const protected virtual
 {
     switch ((int)bitrate.get()) {
         case 1000000:
             return getDsssDbpskSuccessRate(bitLength, snr);
         case 2000000:
             return getDsssDqpskSuccessRate(bitLength, snr);
         case 5500000:
             return getDsssDqpskCck5_5SuccessRate(bitLength, snr);
         case 11000000:
             return getDsssDqpskCck11SuccessRate(bitLength, snr);
     }
     throw cRuntimeError("Unsupported bitrate");
 }
Referenced by getDataSuccessRate(), and getHeaderSuccessRate().
getFec1024QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::getFec1024QamBer (double snr, uint64_t nbits, uint32_t bValue) const protected
 {
     double ber = get1024QamBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = math::minnan(pe, 1.0);
     double pms = std::pow(1 - pe, nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getFec16QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::getFec16QamBer (double snr, uint32_t nbits, uint32_t bValue) const protected
 {
     double ber = get16QamBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = math::minnan(pe, 1.0);
     double pms = pow(1 - pe, (double)nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getFec256QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::getFec256QamBer (double snr, uint64_t nbits, uint32_t bValue) const protected
 {
     double ber = get256QamBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = math::minnan(pe, 1.0);
     double pms = std::pow(1 - pe, nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getFec64QamBer()
double inet::physicallayer::Ieee80211NistErrorModel::getFec64QamBer (double snr, uint32_t nbits, uint32_t bValue) const protected
 {
     double ber = get64QamBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = math::minnan(pe, 1.0);
     double pms = pow(1 - pe, (double)nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getFecBpskBer()
double inet::physicallayer::Ieee80211NistErrorModel::getFecBpskBer (double snr, double nbits, uint32_t bValue) const protected
 {
     double ber = getBpskBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = math::minnan(pe, 1.0);
     double pms = pow(1 - pe, nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getFecQpskBer()
double inet::physicallayer::Ieee80211NistErrorModel::getFecQpskBer (double snr, double nbits, uint32_t bValue) const protected
 {
     double ber = getQpskBer(snr);
     if (ber == 0.0) {
         return 1.0;
     }
     double pe = calculatePe(ber, bValue);
     pe = math::minnan(pe, 1.0);
     double pms = pow(1 - pe, nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getHeaderSuccessRate()
double inet::physicallayer::Ieee80211NistErrorModel::getHeaderSuccessRate (const IIeee80211Mode * mode, unsigned int headerBitLength, double snr) const override protected virtual
Implements inet::physicallayer::Ieee80211ErrorModelBase.
 {
     double successRate = 0;
     if (auto ofdmMode = dynamic_cast<const Ieee80211OfdmMode *>(mode)) {
         int chunkLength = bitLength - b(ofdmMode->getHeaderMode()->getServiceFieldLength()).get();
         ASSERT(chunkLength == 24);
         successRate = getOFDMAndERPOFDMChunkSuccessRate(ofdmMode->getHeaderMode()->getModulation()->getSubcarrierModulation(),
                                                         ofdmMode->getHeaderMode()->getCode()->getConvolutionalCode(),
                                                         chunkLength,
                                                         snr);
     }
     else if (auto htMode = dynamic_cast<const Ieee80211HtMode *>(mode)) {
 //        int chunkLength = bitLength - b(htMode->getHeaderMode()->getHTLengthLength()).get();
 //        ASSERT(chunkLength == 24);
         int chunkLength = bitLength;
         successRate = getOFDMAndERPOFDMChunkSuccessRate(htMode->getHeaderMode()->getModulation()->getSubcarrierModulation(),
                                                         htMode->getHeaderMode()->getCode()->getForwardErrorCorrection(),
                                                         chunkLength,
                                                         snr);
     }
     else if (auto vhtMode = dynamic_cast<const Ieee80211VhtMode *>(mode)) {
 //        int chunkLength = bitLength - b(vhtMode->getHeaderMode()->getHTLengthLength()).get();
 //        ASSERT(chunkLength == 24);
         int chunkLength = bitLength;
         successRate = getOFDMAndERPOFDMChunkSuccessRate(vhtMode->getHeaderMode()->getModulation()->getSubcarrierModulation(),
                                                         vhtMode->getHeaderMode()->getCode()->getForwardErrorCorrection(),
                                                         chunkLength,
                                                         snr);
     }
     else if (auto dsssMode = dynamic_cast<const Ieee80211DsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(dsssMode->getHeaderMode()->getNetBitrate(), bitLength, snr);
     else if (auto hrDsssMode = dynamic_cast<const Ieee80211HrDsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(hrDsssMode->getHeaderMode()->getNetBitrate(), bitLength, snr);
     else
         throw cRuntimeError("Unsupported 802.11 mode");
     EV_DEBUG << "SNIR = " << snr << ", bit length = " << bitLength << ", header error rate = " << 1 - successRate << endl;
     if (successRate >= 1)
         successRate = 1;
     return successRate;
 }
getOFDMAndERPOFDMChunkSuccessRate()
double inet::physicallayer::Ieee80211NistErrorModel::getOFDMAndERPOFDMChunkSuccessRate (const ApskModulationBase * subcarrierModulation, const ConvolutionalCode * convolutionalCode, unsigned int bitLength, double snr) const protected virtual
 {
     if (subcarrierModulation == &BpskModulation::singleton || subcarrierModulation == &QbpskModulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 1 && convolutionalCode->getCodeRatePuncturingN() == 2)
             return getFecBpskBer(snr, bitLength, 1);
         return getFecBpskBer(snr, bitLength, 3);
     }
     else if (subcarrierModulation == &QpskModulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 1 && convolutionalCode->getCodeRatePuncturingN() == 2)
             return getFecQpskBer(snr, bitLength, 1);
         return getFecQpskBer(snr, bitLength, 3);
     }
     else if (subcarrierModulation == &Qam16Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 1 && convolutionalCode->getCodeRatePuncturingN() == 2)
             return getFec16QamBer(snr, bitLength, 1);
         return getFec16QamBer(snr, bitLength, 3);
     }
     else if (subcarrierModulation == &Qam64Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 2 && convolutionalCode->getCodeRatePuncturingN() == 3)
             return getFec64QamBer(snr, bitLength, 2);
         else if (convolutionalCode->getCodeRatePuncturingK() == 5 && convolutionalCode->getCodeRatePuncturingN() == 6)
             return getFec64QamBer(snr, bitLength, 2);
         return getFec64QamBer(snr, bitLength, 3);
     }
     else if (subcarrierModulation == &Qam256Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 5 && convolutionalCode->getCodeRatePuncturingN() == 6)
             return getFec256QamBer(snr, bitLength, 5);
         return getFec256QamBer(snr, bitLength, 3);
     }
     else if (subcarrierModulation == &Qam1024Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 5 && convolutionalCode->getCodeRatePuncturingN() == 6)
             return getFec1024QamBer(snr, bitLength, 5);
         return getFec1024QamBer(snr, bitLength, 3);
     }
     else
         throw cRuntimeError("Unknown modulation");
 }
Referenced by getDataSuccessRate(), and getHeaderSuccessRate().
getQpskBer()
double inet::physicallayer::Ieee80211NistErrorModel::getQpskBer (double snr) const protected
 {
     double z = sqrt(snr / 2.0);
     double ber = 0.5 * erfc(z);
     EV << "qpsk snr=" << snr << " ber=" << ber << "\n";
     return ber;
 }
Referenced by getFecQpskBer().
printToStream()
virtual std::ostream& inet::physicallayer::Ieee80211NistErrorModel::printToStream (std::ostream & stream, int level, int evFlags = 0) const inline override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::Ieee80211OfdmErrorModel.
 { return stream << "Ieee80211NistErrorModel"; }
The documentation for this class was generated from the following files:
Ieee80211NistErrorModel.h
Ieee80211NistErrorModel.cc