INET Framework for OMNeT++/OMNEST: inet::GenerationIdOption Class Reference
inet::GenerationIdOption Class Reference
Class generated from inet/routing/pim/PimPacket.msg:104 by opp_msgtool.
#include <PimPacket_m.h>
Public Member Functions
GenerationIdOption ()
GenerationIdOption (const GenerationIdOption &other)
virtual ~GenerationIdOption ()
GenerationIdOption & operator= (const GenerationIdOption &other)
virtual GenerationIdOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getGenerationID () const
virtual void setGenerationID (uint32_t generationID)
Public Member Functions inherited from inet::HelloOption
HelloOption ()
HelloOption (const HelloOption &other)
virtual ~HelloOption ()
HelloOption & operator= (const HelloOption &other)
virtual PimHelloOptionType getType () const
virtual void setType (PimHelloOptionType type)
Protected Member Functions
bool operator== (const GenerationIdOption &)=delete
Protected Member Functions inherited from inet::HelloOption
bool operator== (const HelloOption &)=delete
Protected Attributes
uint32_t generationID = 0
Protected Attributes inherited from inet::HelloOption
PimHelloOptionType type = static_cast<inet::PimHelloOptionType>(-1)
Private Member Functions
void copy (const GenerationIdOption &other)
Detailed Description
Class generated from inet/routing/pim/PimPacket.msg:104 by opp_msgtool.
class GenerationIdOption extends HelloOption
{
    type = GenerationID;
    uint32_t generationID;
}
Constructor & Destructor Documentation
GenerationIdOption() [1/2]
inet::GenerationIdOption::GenerationIdOption ()
GenerationIdOption() [2/2]
inet::GenerationIdOption::GenerationIdOption (const GenerationIdOption & other)
~GenerationIdOption()
virtual inet::GenerationIdOption::~GenerationIdOption () virtual
Member Function Documentation
copy()
void inet::GenerationIdOption::copy (const GenerationIdOption & other) private
dup()
virtual GenerationIdOption* inet::GenerationIdOption::dup () const inline override virtual
Reimplemented from inet::HelloOption.
 {return new GenerationIdOption(*this);}
getGenerationID()
virtual uint32_t inet::GenerationIdOption::getGenerationID () const virtual
Referenced by inet::PimPacketSerializer::serialize().
operator=()
GenerationIdOption& inet::GenerationIdOption::operator= (const GenerationIdOption & other)
operator==()
bool inet::GenerationIdOption::operator== (const GenerationIdOption &) protected delete
parsimPack()
virtual void inet::GenerationIdOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::GenerationIdOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimUnpacking().
setGenerationID()
virtual void inet::GenerationIdOption::setGenerationID (uint32_t generationID) virtual
Referenced by inet::PimPacketSerializer::deserialize(), and inet::PimBase::sendHelloPacket().
Member Data Documentation
generationID
uint32_t inet::GenerationIdOption::generationID = 0 protected
The documentation for this class was generated from the following file:
PimPacket_m.h