INET Framework for OMNeT++/OMNEST: inet::ieee80211::TxOpFs Class Reference
inet::ieee80211::TxOpFs Class Reference
#include <TxOpFs.h>
Public Member Functions
TxOpFs ()
virtual ~TxOpFs ()
virtual int selectTxOpSequence (AlternativesFs *frameSequence, FrameSequenceContext *context)
virtual bool isRtsCtsNeeded (OptionalFs *frameSequence, FrameSequenceContext *context)
virtual bool isBlockAckReqRtsCtsNeeded (OptionalFs *frameSequence, FrameSequenceContext *context)
virtual int selectMgmtOrDataQap (AlternativesFs *frameSequence, FrameSequenceContext *context)
Public Member Functions inherited from inet::ieee80211::AlternativesFs
virtual ~AlternativesFs ()
AlternativesFs (std::vector< IFrameSequence * > elements, std::function< int(AlternativesFs *, FrameSequenceContext *)> selector)
virtual int getStep ()
virtual int selectSequence (FrameSequenceContext *context)
virtual void startSequence (FrameSequenceContext *context, int firstStep) override
virtual IFrameSequenceStep * prepareStep (FrameSequenceContext *context) override
virtual bool completeStep (FrameSequenceContext *context) override
virtual std::string getHistory () const override
Public Member Functions inherited from inet::ieee80211::IFrameSequence
virtual ~IFrameSequence ()
Additional Inherited Members
Protected Attributes inherited from inet::ieee80211::AlternativesFs
int firstStep = -1
int step = -1
int elementIndex = -1
std::vector< IFrameSequence * > elements
std::function< int(AlternativesFs *, FrameSequenceContext *)> selector
Constructor & Destructor Documentation
TxOpFs()
inet::ieee80211::TxOpFs::TxOpFs ()
                :
     // Excerpt from G.3 EDCA and HCCA sequences
     // txop-sequence =
     //   ( ( ( RTS CTS ) | CTS + self ) Data + individual + QoS +( block-ack | no-ack ) ) |
     //   [ RTS CTS ] (txop-part-requiring-ack txop-part-providing-ack )|
     //   [ RTS CTS ] (Management | ( Data + QAP )) + individual ACK |
     //   [ RTS CTS ] (BlockAckReq BlockAck ) |
     //   ht-txop-sequence;
     AlternativesFs({new SequentialFs({new OptionalFs(new RtsCtsFs(), OPTIONALFS_PREDICATE(isRtsCtsNeeded)),
                                       new DataFs()}),
                     new SequentialFs({new OptionalFs(new RtsCtsFs(), OPTIONALFS_PREDICATE(isRtsCtsNeeded)),
                                       new DataFs(),
                                       new AckFs()}), // TODO should be in txop-part-requiring-ack
                     new SequentialFs({new OptionalFs(new RtsCtsFs(), OPTIONALFS_PREDICATE(isBlockAckReqRtsCtsNeeded)),
                                       new BlockAckReqBlockAckFs()}),
                     new SequentialFs({new OptionalFs(new RtsCtsFs(), OPTIONALFS_PREDICATE(isRtsCtsNeeded)),
                                       new AlternativesFs({new ManagementAckFs(),
                                                           /* TODO DATA + QAP*/},
                                                          ALTERNATIVESFS_SELECTOR(selectMgmtOrDataQap))})},
                    ALTERNATIVESFS_SELECTOR(selectTxOpSequence))
 {
 }
~TxOpFs()
virtual inet::ieee80211::TxOpFs::~TxOpFs () inline virtual
 {}
Member Function Documentation
isBlockAckReqRtsCtsNeeded()
bool inet::ieee80211::TxOpFs::isBlockAckReqRtsCtsNeeded (OptionalFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return false; // FIXME QosRtsPolicy should handle this case
 }
Referenced by TxOpFs().
isRtsCtsNeeded()
bool inet::ieee80211::TxOpFs::isRtsCtsNeeded (OptionalFs * frameSequence, FrameSequenceContext * context) virtual
 {
     auto protectedFrame = context->getInProgressFrames()->getFrameToTransmit();
     return context->getRtsPolicy()->isRtsNeeded(protectedFrame, protectedFrame->peekAtFront<Ieee80211MacHeader>());
 }
Referenced by TxOpFs().
selectMgmtOrDataQap()
int inet::ieee80211::TxOpFs::selectMgmtOrDataQap (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     return 0;
 }
Referenced by TxOpFs().
selectTxOpSequence()
int inet::ieee80211::TxOpFs::selectTxOpSequence (AlternativesFs * frameSequence, FrameSequenceContext * context) virtual
 {
     auto frameToTransmit = context->getInProgressFrames()->getFrameToTransmit();
     const auto& macHeader = frameToTransmit->peekAtFront<Ieee80211MacHeader>();
     if (context->getQoSContext()->ackPolicy->isBlockAckReqNeeded(context->getInProgressFrames(), context->getQoSContext()->txopProcedure))
         return 2;
     if (dynamicPtrCast<const Ieee80211MgmtHeader>(macHeader))
         return 3;
     else {
         auto dataHeaderToTransmit = dynamicPtrCast<const Ieee80211DataHeader>(macHeader);
         OriginatorBlockAckAgreement *agreement = nullptr;
         if (context->getQoSContext()->blockAckAgreementHandler)
             agreement = context->getQoSContext()->blockAckAgreementHandler->getAgreement(dataHeaderToTransmit->getReceiverAddress(), dataHeaderToTransmit->getTid());
         auto ackPolicy = context->getQoSContext()->ackPolicy->computeAckPolicy(frameToTransmit, dataHeaderToTransmit, agreement);
         if (ackPolicy == AckPolicy::BLOCK_ACK)
             return 0;
         else if (ackPolicy == AckPolicy::NORMAL_ACK)
             return 1;
         else
             throw cRuntimeError("Unknown AckPolicy");
     }
 }
The documentation for this class was generated from the following files:
TxOpFs.h
TxOpFs.cc