INET Framework for OMNeT++/OMNEST: inet::Ipv6NeighbourCache Class Reference
inet::Ipv6NeighbourCache Class Reference
Ipv6 Neighbour Cache (RFC 2461 Neighbor Discovery for Ipv6).
#include <Ipv6NeighbourCache.h>
Classes
class DefaultRouterList
struct Key
Key into neighbour cache.
struct Neighbour
Stores a neighbour (or router) entry.
Public Types
enum ReachabilityState {
INCOMPLETE, REACHABLE, STALE, DELAY,
PROBE
}
Neighbour's reachability state.
typedef std::vector< Packet * > MsgPtrVector
typedef std::map< Key, Neighbour > NeighbourMap
The std::map underlying the Neighbour Cache data structure.
Public Member Functions
Ipv6NeighbourCache (cSimpleModule &neighbourDiscovery)
virtual ~Ipv6NeighbourCache ()
virtual Neighbour * lookup (const Ipv6Address &addr, int interfaceID)
Returns a neighbour entry, or nullptr.
virtual const Key * lookupKeyAddr (Key &key)
Experimental code.
DefaultRouterList & getDefaultRouterList ()
NeighbourMap::iterator begin ()
For iteration on the internal std::map.
NeighbourMap::iterator end ()
For iteration on the internal std::map.
virtual Neighbour * addNeighbour (const Ipv6Address &addr, int interfaceID)
Creates and initializes a neighbour entry with isRouter=false, state=INCOMPLETE.
virtual Neighbour * addNeighbour (const Ipv6Address &addr, int interfaceID, MacAddress macAddress)
Creates and initializes a neighbour entry with isRouter=false, MAC address and state=STALE.
virtual Neighbour * addRouter (const Ipv6Address &addr, int interfaceID, MacAddress macAddress, simtime_t expiryTime, bool isHomeAgent=false)
Creates and initializes a router entry (isRouter=isDefaultRouter=true), MAC address and state=STALE.
virtual void remove (const Ipv6Address &addr, int interfaceID)
Deletes the given neighbour from the cache.
virtual void invalidateEntriesForInterfaceID (int interfaceID)
Set status of all neighbours on given interface to state PROBE.
virtual void invalidateAllEntries ()
Set status of all neighbours to state PROBE.
virtual void remove (NeighbourMap::iterator it)
Deletes the given neighbour from the cache.
Static Public Member Functions
static const char * stateName (ReachabilityState state)
Returns the name of the given state as string.
Protected Attributes
cSimpleModule & neighbourDiscovery
NeighbourMap neighbourMap
DefaultRouterList defaultRouterList
Detailed Description
Ipv6 Neighbour Cache (RFC 2461 Neighbor Discovery for Ipv6).
Used internally by the Ipv6NeighbourDiscovery simple module.
This is just a plain container class – the Ipv6NeighbourDiscovery module is free to manipulate the contents of the Neighbour entries as it pleases.
NOTE: Ipv6NeighbourCache also stores the Default Router List. A router becomes a default router by calling getDefaultRouterList().add(router) and stops to be a default router after getDefaultRouterList().remove(router) has been called. References to default routers are stored in a circular list to ease round-robin selection.
Member Typedef Documentation
MsgPtrVector
typedef std::vector<Packet *> inet::Ipv6NeighbourCache::MsgPtrVector
NeighbourMap
typedef std::map<Key, Neighbour> inet::Ipv6NeighbourCache::NeighbourMap
The std::map underlying the Neighbour Cache data structure.
Member Enumeration Documentation
ReachabilityState
enum inet::Ipv6NeighbourCache::ReachabilityState
Neighbour's reachability state.
Enumerator
INCOMPLETE
REACHABLE
STALE
DELAY
PROBE
 { INCOMPLETE, REACHABLE, STALE, DELAY, PROBE };
Constructor & Destructor Documentation
Ipv6NeighbourCache()
inet::Ipv6NeighbourCache::Ipv6NeighbourCache (cSimpleModule & neighbourDiscovery)
     : neighbourDiscovery(neighbourDiscovery)
 {
     WATCH_MAP(neighbourMap);
 }
~Ipv6NeighbourCache()
virtual inet::Ipv6NeighbourCache::~Ipv6NeighbourCache () inline virtual
 {}
Member Function Documentation
addNeighbour() [1/2]
Ipv6NeighbourCache::Neighbour * inet::Ipv6NeighbourCache::addNeighbour (const Ipv6Address & addr, int interfaceID) virtual
Creates and initializes a neighbour entry with isRouter=false, state=INCOMPLETE.
 {
     Key key(addr, interfaceID);
     ASSERT(!containsKey(neighbourMap, key)); // entry must not exist yet
     Neighbour& nbor = neighbourMap[key];
     nbor.nceKey = lookupKeyAddr(key);
     nbor.isRouter = false;
     nbor.isHomeAgent = false;
     nbor.reachabilityState = INCOMPLETE;
     return &nbor;
 }
Referenced by inet::Ipv6NeighbourDiscovery::processIpv6Datagram(), inet::Ipv6NeighbourDiscovery::processNsWithSpecifiedSrcAddr(), and inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates().
addNeighbour() [2/2]
Ipv6NeighbourCache::Neighbour * inet::Ipv6NeighbourCache::addNeighbour (const Ipv6Address & addr, int interfaceID, MacAddress macAddress) virtual
Creates and initializes a neighbour entry with isRouter=false, MAC address and state=STALE.
 {
     Key key(addr, interfaceID);
     ASSERT(!containsKey(neighbourMap, key)); // entry must not exist yet
     Neighbour& nbor = neighbourMap[key];
     nbor.nceKey = lookupKeyAddr(key);
     nbor.macAddress = macAddress;
     nbor.isRouter = false;
     nbor.isHomeAgent = false;
     nbor.reachabilityState = STALE;
     return &nbor;
 }
addRouter()
Ipv6NeighbourCache::Neighbour * inet::Ipv6NeighbourCache::addRouter (const Ipv6Address & addr, int interfaceID, MacAddress macAddress, simtime_t expiryTime, bool isHomeAgent = false) virtual
Creates and initializes a router entry (isRouter=isDefaultRouter=true), MAC address and state=STALE.
Update by CB: Added an optional parameter which is false by default. Specifies whether a router is also a home agent.
 {
     Key key(addr, interfaceID);
     ASSERT(!containsKey(neighbourMap, key)); // entry must not exist yet
     Neighbour& nbor = neighbourMap[key];
     nbor.nceKey = lookupKeyAddr(key);
     nbor.macAddress = macAddress;
     nbor.isRouter = true;
     nbor.isHomeAgent = isHomeAgent;
     nbor.reachabilityState = STALE;
     nbor.routerExpiryTime = expiryTime;
     defaultRouterList.add(nbor);
     return &nbor;
 }
Referenced by inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates().
begin()
NeighbourMap::iterator inet::Ipv6NeighbourCache::begin () inline
For iteration on the internal std::map.
 { return neighbourMap.begin(); }
end()
NeighbourMap::iterator inet::Ipv6NeighbourCache::end () inline
For iteration on the internal std::map.
 { return neighbourMap.end(); }
getDefaultRouterList()
DefaultRouterList& inet::Ipv6NeighbourCache::getDefaultRouterList () inline
 { return defaultRouterList; }
Referenced by inet::Ipv6NeighbourDiscovery::processNaForIncompleteNceState(), inet::Ipv6NeighbourDiscovery::processNaForOtherNceStates(), and inet::Ipv6NeighbourDiscovery::selectDefaultRouter().
invalidateAllEntries()
void inet::Ipv6NeighbourCache::invalidateAllEntries () virtual
Set status of all neighbours to state PROBE.
 {
     while (!neighbourMap.empty()) {
         auto it = neighbourMap.begin();
         remove(it);
     }
     defaultRouterList.clear();
     /*
        int size = neighbourMap.size();
        EV << "size: " << size << endl;
        for (auto it = neighbourMap.begin(); it != neighbourMap.end(); it++)
        {
         it->second.reachabilityState = PROBE; // we make sure this neighbour is not used anymore in the future, unless reachability can be confirmed
        }
      */
 }
invalidateEntriesForInterfaceID()
void inet::Ipv6NeighbourCache::invalidateEntriesForInterfaceID (int interfaceID) virtual
Set status of all neighbours on given interface to state PROBE.
 {
     for (auto& elem : neighbourMap) {
         if (elem.first.interfaceID == interfaceID) {
             elem.second.reachabilityState = PROBE; // we make sure this neighbour is not used anymore in the future, unless reachability can be confirmed
             neighbourDiscovery.cancelAndDelete(elem.second.nudTimeoutEvent); // 20.9.07 - CB
             elem.second.nudTimeoutEvent = nullptr;
         }
     }
 }
lookup()
Ipv6NeighbourCache::Neighbour * inet::Ipv6NeighbourCache::lookup (const Ipv6Address & addr, int interfaceID) virtual
Returns a neighbour entry, or nullptr.
 {
     Key key(addr, interfaceID);
     auto i = neighbourMap.find(key);
     return i == neighbourMap.end() ? nullptr : &(i->second);
 }
Referenced by inet::Ipv6NeighbourDiscovery::processIpv6Datagram(), inet::Ipv6NeighbourDiscovery::processNaPacket(), inet::Ipv6NeighbourDiscovery::processNsWithSpecifiedSrcAddr(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6NeighbourDiscovery::reachabilityConfirmed(), and inet::Ipv6NeighbourDiscovery::resolveNeighbour().
lookupKeyAddr()
const Ipv6NeighbourCache::Key * inet::Ipv6NeighbourCache::lookupKeyAddr (Key & key) virtual
Experimental code.
 {
     auto i = neighbourMap.find(key);
     return &(i->first);
 }
Referenced by addNeighbour(), and addRouter().
remove() [1/2]
void inet::Ipv6NeighbourCache::remove (const Ipv6Address & addr, int interfaceID) virtual
Deletes the given neighbour from the cache.
 {
     Key key(addr, interfaceID);
     auto it = neighbourMap.find(key);
     ASSERT(it != neighbourMap.end()); // entry must exist
     remove(it);
 }
Referenced by inet::Ipv6NeighbourDiscovery::dropQueuedPacketsAwaitingAr(), invalidateAllEntries(), inet::Ipv6NeighbourDiscovery::processNudTimeout(), inet::Ipv6NeighbourDiscovery::selectDefaultRouter(), and inet::Ipv6NeighbourDiscovery::timeoutDefaultRouter().
remove() [2/2]
void inet::Ipv6NeighbourCache::remove (NeighbourMap::iterator it) virtual
Deletes the given neighbour from the cache.
 {
     neighbourDiscovery.cancelAndDelete(it->second.nudTimeoutEvent); // 20.9.07 - CB
     it->second.nudTimeoutEvent = nullptr;
     if (it->second.isDefaultRouter())
         defaultRouterList.remove(it->second);
     neighbourMap.erase(it);
 }
stateName()
const char * inet::Ipv6NeighbourCache::stateName (ReachabilityState state) static
Returns the name of the given state as string.
 {
     switch (state) {
         case INCOMPLETE:
             return "INCOMPLETE";
         case REACHABLE:
             return "REACHABLE";
         case STALE:
             return "STALE";
         case DELAY:
             return "DELAY";
         case PROBE:
             return "PROBE";
         default:
             return "???";
     }
 }
Referenced by inet::operator<<().
Member Data Documentation
defaultRouterList
DefaultRouterList inet::Ipv6NeighbourCache::defaultRouterList protected
Referenced by addRouter(), invalidateAllEntries(), and remove().
neighbourDiscovery
cSimpleModule& inet::Ipv6NeighbourCache::neighbourDiscovery protected
Referenced by invalidateEntriesForInterfaceID(), and remove().
neighbourMap
NeighbourMap inet::Ipv6NeighbourCache::neighbourMap protected
Referenced by addNeighbour(), addRouter(), invalidateAllEntries(), invalidateEntriesForInterfaceID(), Ipv6NeighbourCache(), lookup(), lookupKeyAddr(), and remove().
The documentation for this class was generated from the following files:
Ipv6NeighbourCache.h
Ipv6NeighbourCache.cc