INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmInterleaver Class Reference
inet::physicallayer::Ieee80211OfdmInterleaver Class Reference
#include <Ieee80211OfdmInterleaver.h>
Public Member Functions
Ieee80211OfdmInterleaver (const Ieee80211OfdmInterleaving *interleaving)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
BitVector interleave (const BitVector &bits) const override
BitVector deinterleave (const BitVector &bits) const override
int getNumberOfCodedBitsPerSymbol () const
int getNumberOfCodedBitsPerSubcarrier () const
const Ieee80211OfdmInterleaving * getInterleaving () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
int numberOfCodedBitsPerSymbol
int numberOfCodedBitsPerSubcarrier
int s
const Ieee80211OfdmInterleaving * interleaving = nullptr
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211OfdmInterleaver()
inet::physicallayer::Ieee80211OfdmInterleaver::Ieee80211OfdmInterleaver (const Ieee80211OfdmInterleaving * interleaving)
                                                                                                 : interleaving(interleaving)
 {
     numberOfCodedBitsPerSubcarrier = interleaving->getNumberOfCodedBitsPerSubcarrier();
     numberOfCodedBitsPerSymbol = interleaving->getNumberOfCodedBitsPerSymbol();
     s = std::max(numberOfCodedBitsPerSubcarrier / 2, 1);
 }
Member Function Documentation
deinterleave()
BitVector inet::physicallayer::Ieee80211OfdmInterleaver::deinterleave (const BitVector & bits) const override virtual
Implements inet::physicallayer::IInterleaver.
 {
     if (interleavedBits.getSize() % numberOfCodedBitsPerSymbol)
         throw cRuntimeError("interleavedBits length must be a multiple of numberOfCodedBitsPerSymbol = %d", numberOfCodedBitsPerSymbol);
     EV_DEBUG << "Deinterleaving the following bits: " << interleavedBits << endl;
     int numberOfSymbols = interleavedBits.getSize() / numberOfCodedBitsPerSymbol;
     BitVector deinterleavedBits;
     for (int i = 0; i < numberOfSymbols; i++) {
         for (int j = 0; j < numberOfCodedBitsPerSymbol; j++) {
             // i = s × Floor(j/s) + (j + Floor(16 × j/N_CBPS )) mod s, j = 0,1,... N CBPS - 1,
             // where s = max(N_BPSC / 2, 1).
             int firstPerm = s * floor(j / s) + (j + (int)floor(16 * j / numberOfCodedBitsPerSymbol)) % s;
             // k = 16 × i - (N_CBPS - 1)Floor(16 × i/N_CBPS ), i = 0,1,... N_CBPS - 1
             int secondPerm = 16 * firstPerm - (numberOfCodedBitsPerSymbol - 1) * floor(16 * firstPerm / numberOfCodedBitsPerSymbol);
             int shiftedSecondPerm = secondPerm + i * numberOfCodedBitsPerSymbol;
             deinterleavedBits.setBit(shiftedSecondPerm, interleavedBits.getBit(i * numberOfCodedBitsPerSymbol + j));
         }
     }
     EV_DEBUG << "The deinterleaved bits are: " << deinterleavedBits << endl;
     return deinterleavedBits;
 }
Referenced by inet::physicallayer::Ieee80211OfdmInterleaverModule::deinterleave().
getInterleaving()
const Ieee80211OfdmInterleaving* inet::physicallayer::Ieee80211OfdmInterleaver::getInterleaving () const inline override virtual
Implements inet::physicallayer::IInterleaver.
 { return interleaving; }
Referenced by inet::physicallayer::Ieee80211OfdmInterleaverModule::getInterleaving(), and inet::physicallayer::Ieee80211OfdmInterleaverModule::~Ieee80211OfdmInterleaverModule().
getNumberOfCodedBitsPerSubcarrier()
int inet::physicallayer::Ieee80211OfdmInterleaver::getNumberOfCodedBitsPerSubcarrier () const inline
 { return numberOfCodedBitsPerSubcarrier; }
getNumberOfCodedBitsPerSymbol()
int inet::physicallayer::Ieee80211OfdmInterleaver::getNumberOfCodedBitsPerSymbol () const inline
 { return numberOfCodedBitsPerSymbol; }
interleave()
BitVector inet::physicallayer::Ieee80211OfdmInterleaver::interleave (const BitVector & bits) const override virtual
Implements inet::physicallayer::IInterleaver.
 {
     if (deinterleavedBits.getSize() % numberOfCodedBitsPerSymbol)
         throw cRuntimeError("deinterleavedBits length = %d must be a multiple of numberOfCodedBitsPerSymbol = %d", deinterleavedBits.getSize(), numberOfCodedBitsPerSymbol);
     int numberOfSymbols = deinterleavedBits.getSize() / numberOfCodedBitsPerSymbol;
     EV_DEBUG << "Interleaving the following bits: " << deinterleavedBits << endl;
     BitVector interleavedBits;
     for (int i = 0; i < numberOfSymbols; i++) {
         for (int j = 0; j < numberOfCodedBitsPerSymbol; j++) {
             // First permutation: (N_CBPS /16) (k mod 16) + Floor(k/16), k = 0,1,...,N_CBPS - 1.
             int firstPerm = (numberOfCodedBitsPerSymbol / 16) * (j % 16) + floor(j / 16);
             // Second permutation: j = s × Floor(i/s) + (i + N_CBPS - Floor(16 × i/N_CBPS )) mod s, i = 0,1,... N_CBPS – 1,
             // where s = max(N_BPSC / 2, 1).
             int secondPerm = s * floor(firstPerm / s)
                 + (firstPerm + numberOfCodedBitsPerSymbol - (int)floor(16 * firstPerm / numberOfCodedBitsPerSymbol)) % s;
             int shiftedSecondPerm = secondPerm + i * numberOfCodedBitsPerSymbol;
             interleavedBits.setBit(shiftedSecondPerm, deinterleavedBits.getBit(i * numberOfCodedBitsPerSymbol + j));
         }
     }
     EV_DEBUG << "The interleaved bits are: " << interleavedBits << endl;
     return interleavedBits;
 }
Referenced by inet::physicallayer::Ieee80211OfdmInterleaverModule::interleave().
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmInterleaver::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Ieee80211Interleaver";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(interleaving, printFieldToString(interleaving, level + 1, evFlags));
     return stream;
 }
Referenced by inet::physicallayer::Ieee80211OfdmInterleaverModule::printToStream().
Member Data Documentation
interleaving
const Ieee80211OfdmInterleaving* inet::physicallayer::Ieee80211OfdmInterleaver::interleaving = nullptr protected
Referenced by Ieee80211OfdmInterleaver(), and printToStream().
numberOfCodedBitsPerSubcarrier
int inet::physicallayer::Ieee80211OfdmInterleaver::numberOfCodedBitsPerSubcarrier protected
Referenced by Ieee80211OfdmInterleaver().
numberOfCodedBitsPerSymbol
int inet::physicallayer::Ieee80211OfdmInterleaver::numberOfCodedBitsPerSymbol protected
Referenced by deinterleave(), Ieee80211OfdmInterleaver(), and interleave().
s
int inet::physicallayer::Ieee80211OfdmInterleaver::s protected
The documentation for this class was generated from the following files:
Ieee80211OfdmInterleaver.h
Ieee80211OfdmInterleaver.cc