INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAddStreamsRequestParameter Class Reference
inet::sctp::SctpAddStreamsRequestParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:279 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpAddStreamsRequestParameter (const char *name=nullptr)
SctpAddStreamsRequestParameter (const SctpAddStreamsRequestParameter &other)
virtual ~SctpAddStreamsRequestParameter ()
SctpAddStreamsRequestParameter & operator= (const SctpAddStreamsRequestParameter &other)
virtual SctpAddStreamsRequestParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSrReqSn () const
virtual void setSrReqSn (uint32_t srReqSn)
virtual uint16_t getNumberOfStreams () const
virtual void setNumberOfStreams (uint16_t numberOfStreams)
virtual uint16_t getReserved () const
virtual void setReserved (uint16_t reserved)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpAddStreamsRequestParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t srReqSn = 0
uint16_t numberOfStreams = 0
uint16_t reserved = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpAddStreamsRequestParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:279 by opp_msgtool.
class SctpAddStreamsRequestParameter extends SctpParameter
{
    uint32_t srReqSn; //Stream Reset Request Sequence Number
    uint16_t numberOfStreams;
    uint16_t reserved = 0;
}
Constructor & Destructor Documentation
SctpAddStreamsRequestParameter() [1/2]
inet::sctp::SctpAddStreamsRequestParameter::SctpAddStreamsRequestParameter (const char * name = nullptr)
SctpAddStreamsRequestParameter() [2/2]
inet::sctp::SctpAddStreamsRequestParameter::SctpAddStreamsRequestParameter (const SctpAddStreamsRequestParameter & other)
~SctpAddStreamsRequestParameter()
virtual inet::sctp::SctpAddStreamsRequestParameter::~SctpAddStreamsRequestParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpAddStreamsRequestParameter::copy (const SctpAddStreamsRequestParameter & other) private
dup()
virtual SctpAddStreamsRequestParameter* inet::sctp::SctpAddStreamsRequestParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpAddStreamsRequestParameter(*this);}
getNumberOfStreams()
virtual uint16_t inet::sctp::SctpAddStreamsRequestParameter::getNumberOfStreams () const virtual
Referenced by inet::sctp::SctpAssociation::makeAddStreamsRequestParameter(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest(), and inet::sctp::SctpHeaderSerializer::serialize().
getReserved()
virtual uint16_t inet::sctp::SctpAddStreamsRequestParameter::getReserved () const virtual
getSrReqSn()
virtual uint32_t inet::sctp::SctpAddStreamsRequestParameter::getSrReqSn () const virtual
Referenced by inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpAddStreamsRequestParameter& inet::sctp::SctpAddStreamsRequestParameter::operator= (const SctpAddStreamsRequestParameter & other)
operator==()
bool inet::sctp::SctpAddStreamsRequestParameter::operator== (const SctpAddStreamsRequestParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpAddStreamsRequestParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpAddStreamsRequestParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setNumberOfStreams()
virtual void inet::sctp::SctpAddStreamsRequestParameter::setNumberOfStreams (uint16_t numberOfStreams) virtual
Referenced by inet::sctp::SctpAssociation::makeAddStreamsRequestParameter(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), and inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest().
setReserved()
virtual void inet::sctp::SctpAddStreamsRequestParameter::setReserved (uint16_t reserved) virtual
setSrReqSn()
virtual void inet::sctp::SctpAddStreamsRequestParameter::setSrReqSn (uint32_t srReqSn) virtual
Referenced by inet::sctp::SctpAssociation::makeAddStreamsRequestParameter(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), and inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest().
Member Data Documentation
numberOfStreams
uint16_t inet::sctp::SctpAddStreamsRequestParameter::numberOfStreams = 0 protected
reserved
uint16_t inet::sctp::SctpAddStreamsRequestParameter::reserved = 0 protected
srReqSn
uint32_t inet::sctp::SctpAddStreamsRequestParameter::srReqSn = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h