INET Framework for OMNeT++/OMNEST: inet::Ieee8021qTagTpidHeader Class Reference
inet::Ieee8021qTagTpidHeader Class Reference
Class generated from inet/linklayer/ieee8021q/Ieee8021qTagHeader.msg:24 by opp_msgtool.
#include <Ieee8021qTagHeader_m.h>
Public Member Functions
Ieee8021qTagTpidHeader ()
Ieee8021qTagTpidHeader (const Ieee8021qTagTpidHeader &other)
virtual ~Ieee8021qTagTpidHeader ()
Ieee8021qTagTpidHeader & operator= (const Ieee8021qTagTpidHeader &other)
virtual Ieee8021qTagTpidHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getTpid () const
virtual void setTpid (uint16_t tpid)
virtual uint8_t getPcp () const
virtual void setPcp (uint8_t pcp)
virtual bool getDei () const
virtual void setDei (bool dei)
virtual uint16_t getVid () const
virtual void setVid (uint16_t vid)
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ieee8021qTagTpidHeader &)=delete
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Protected Attributes
uint16_t tpid = 0
uint8_t pcp = 0
bool dei = false
uint16_t vid = 0
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const Ieee8021qTagTpidHeader &other)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Class generated from inet/linklayer/ieee8021q/Ieee8021qTagHeader.msg:24 by opp_msgtool.
//
// This chunk represents an IEEE 802.1Q tag header as defined by the section
// 9.3 Tag format of the IEEE Std 802.1Q-2018, IEEE Standard for Local and
// Metropolitan Area Networks, Bridges and Bridged Networks.
//
//  0                   1                   2                   3
//  0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
// +-------------------------------+-----+-+-----------------------+
// |       TPID (e.g. 0x8100)      | PCP |D|        VLAN ID        |
// +-------------------------------+-----+-+-----------------------+
//
class Ieee8021qTagTpidHeader extends FieldsChunk
{
    chunkLength = B(4);
    uint16_t tpid; // Tag Protocol Identifier (TPID): 16-bit field specifying an EtherType value that is used to identify the frame as a tagged frame and to select the correct tag decoding functions.
    uint8_t pcp;   // Priority Code Point (PCP): a 3-bit field which refers to the IEEE 802.1p priority. It indicates the frame priority level.
                   // Values are from 0 (best effort) to 7 (highest); 1 represents the lowest priority.
                   // Priority order lowest to highest: 1 0 2 3 4 5 6 7
    bool dei;      // Drop Eligible Indicator (DEI): a 1-bit field. May be used separately or in conjunction with PCP to indicate frames eligible to be dropped in the presence of congestion.
    uint16_t vid;  // VLAN Identifier (VID): a 12-bit field specifying the VLAN to which the frame belongs.
                   // The hexadecimal values of 0x000 and 0xFFF are reserved. All other values may be used as VLAN identifiers, allowing up to 4,094 VLANs.
                   // The reserved value 0x000 indicates that the frame does not belong to any VLAN; in this case,
                   // the 802.1Q tag specifies only a priority and is referred to as a priority tag. On bridges,
                   // VLAN 1 (the default VLAN ID) is often reserved for a management VLAN; this is vendor-specific.
}
Constructor & Destructor Documentation
Ieee8021qTagTpidHeader() [1/2]
inet::Ieee8021qTagTpidHeader::Ieee8021qTagTpidHeader ()
Ieee8021qTagTpidHeader() [2/2]
inet::Ieee8021qTagTpidHeader::Ieee8021qTagTpidHeader (const Ieee8021qTagTpidHeader & other)
~Ieee8021qTagTpidHeader()
virtual inet::Ieee8021qTagTpidHeader::~Ieee8021qTagTpidHeader () virtual
Member Function Documentation
copy()
void inet::Ieee8021qTagTpidHeader::copy (const Ieee8021qTagTpidHeader & other) private
dup()
virtual Ieee8021qTagTpidHeader* inet::Ieee8021qTagTpidHeader::dup () const inline override virtual
 {return new Ieee8021qTagTpidHeader(*this);}
getDei()
virtual bool inet::Ieee8021qTagTpidHeader::getDei () const virtual
getPcp()
virtual uint8_t inet::Ieee8021qTagTpidHeader::getPcp () const virtual
getTpid()
virtual uint16_t inet::Ieee8021qTagTpidHeader::getTpid () const virtual
getVid()
virtual uint16_t inet::Ieee8021qTagTpidHeader::getVid () const virtual
Referenced by inet::Ieee8021qTagTpidHeaderChecker::matchesPacket().
operator=()
Ieee8021qTagTpidHeader& inet::Ieee8021qTagTpidHeader::operator= (const Ieee8021qTagTpidHeader & other)
operator==()
bool inet::Ieee8021qTagTpidHeader::operator== (const Ieee8021qTagTpidHeader &) protected delete
parsimPack()
virtual void inet::Ieee8021qTagTpidHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ieee8021qTagTpidHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setDei()
virtual void inet::Ieee8021qTagTpidHeader::setDei (bool dei) virtual
setPcp()
virtual void inet::Ieee8021qTagTpidHeader::setPcp (uint8_t pcp) virtual
setTpid()
virtual void inet::Ieee8021qTagTpidHeader::setTpid (uint16_t tpid) virtual
setVid()
virtual void inet::Ieee8021qTagTpidHeader::setVid (uint16_t vid) virtual
Member Data Documentation
dei
bool inet::Ieee8021qTagTpidHeader::dei = false protected
pcp
uint8_t inet::Ieee8021qTagTpidHeader::pcp = 0 protected
tpid
uint16_t inet::Ieee8021qTagTpidHeader::tpid = 0 protected
vid
uint16_t inet::Ieee8021qTagTpidHeader::vid = 0 protected
The documentation for this class was generated from the following file:
Ieee8021qTagHeader_m.h