INET Framework for OMNeT++/OMNEST: inet::ieee80211::RecipientBlockAckAgreementHandler Class Reference
inet::ieee80211::RecipientBlockAckAgreementHandler Class Reference
#include <RecipientBlockAckAgreementHandler.h>
Public Member Functions
virtual ~RecipientBlockAckAgreementHandler ()
virtual void processTransmittedAddbaResp (const Ptr< const Ieee80211AddbaResponse > &addbaResp, IBlockAckAgreementHandlerCallback *callback) override
virtual void processReceivedAddbaRequest (const Ptr< const Ieee80211AddbaRequest > &addbaRequest, IRecipientBlockAckAgreementPolicy *blockAckAgreementPolicy, IProcedureCallback *callback) override
virtual void processReceivedDelba (const Ptr< const Ieee80211Delba > &delba, IRecipientBlockAckAgreementPolicy *blockAckAgreementPolicy) override
virtual void qosFrameReceived (const Ptr< const Ieee80211DataHeader > &qosHeader, IBlockAckAgreementHandlerCallback *callback) override
virtual void processTransmittedDelba (const Ptr< const Ieee80211Delba > &delba) override
virtual void blockAckAgreementExpired (IProcedureCallback *procedureCallback, IBlockAckAgreementHandlerCallback *agreementHandlerCallback) override
virtual RecipientBlockAckAgreement * getAgreement (Tid tid, MacAddress originatorAddr) override
Public Member Functions inherited from inet::ieee80211::IRecipientBlockAckAgreementHandler
virtual ~IRecipientBlockAckAgreementHandler ()
Protected Member Functions
virtual void terminateAgreement (MacAddress originatorAddr, Tid tid)
virtual RecipientBlockAckAgreement * addAgreement (const Ptr< const Ieee80211AddbaRequest > &addbaReq)
virtual void updateAgreement (const Ptr< const Ieee80211AddbaResponse > &addbaResponse)
virtual const Ptr< Ieee80211AddbaResponse > buildAddbaResponse (const Ptr< const Ieee80211AddbaRequest > &addbaRequest, IRecipientBlockAckAgreementPolicy *blockAckAgreementPolicy)
virtual const Ptr< Ieee80211Delba > buildDelba (MacAddress receiverAddr, Tid tid, int reasonCode)
virtual simtime_t computeEarliestExpirationTime ()
virtual void scheduleInactivityTimer (IBlockAckAgreementHandlerCallback *callback)
Protected Attributes
std::map< std::pair< MacAddress, Tid >, RecipientBlockAckAgreement * > blockAckAgreements
Constructor & Destructor Documentation
~RecipientBlockAckAgreementHandler()
inet::ieee80211::RecipientBlockAckAgreementHandler::~RecipientBlockAckAgreementHandler () virtual
 {
     for (auto it : blockAckAgreements)
         delete it.second;
 }
Member Function Documentation
addAgreement()
RecipientBlockAckAgreement * inet::ieee80211::RecipientBlockAckAgreementHandler::addAgreement (const Ptr< const Ieee80211AddbaRequest > & addbaReq) protected virtual
 {
     MacAddress originatorAddr = addbaReq->getTransmitterAddress();
     auto id = std::make_pair(originatorAddr, addbaReq->getTid());
     auto it = blockAckAgreements.find(id);
     if (it == blockAckAgreements.end()) {
         RecipientBlockAckAgreement *agreement = new RecipientBlockAckAgreement(originatorAddr, addbaReq->getTid(), addbaReq->getStartingSequenceNumber(), addbaReq->getBufferSize(), addbaReq->getBlockAckTimeoutValue());
         blockAckAgreements[id] = agreement;
         EV_DETAIL << "Block Ack Agreement is added with the following parameters: " << *agreement << endl;
         return agreement;
     }
     else
         // TODO update?
         return it->second;
 }
Referenced by processReceivedAddbaRequest().
blockAckAgreementExpired()
void inet::ieee80211::RecipientBlockAckAgreementHandler::blockAckAgreementExpired (IProcedureCallback * procedureCallback, IBlockAckAgreementHandlerCallback * agreementHandlerCallback) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     // When a timeout of BlockAckTimeout is detected, the STA shall send a DELBA frame to the
     // peer STA with the Reason Code field set to TIMEOUT and shall issue a MLME-DELBA.indication
     // primitive with the ReasonCode parameter having a value of TIMEOUT.
     // The procedure is illustrated in Figure 10-14.
     simtime_t now = simTime();
     for (auto id : blockAckAgreements) {
         auto agreement = id.second;
         if (agreement->getExpirationTime() == now) {
             MacAddress receiverAddr = id.first.first;
             Tid tid = id.first.second;
             const auto& delba = buildDelba(receiverAddr, tid, 39);
             auto delbaPacket = new Packet("Delba", delba);
             procedureCallback->processMgmtFrame(delbaPacket, delba); // 39 - TIMEOUT see: Table 8-36—Reason codes
         }
     }
     scheduleInactivityTimer(agreementHandlerCallback);
 }
buildAddbaResponse()
const Ptr< Ieee80211AddbaResponse > inet::ieee80211::RecipientBlockAckAgreementHandler::buildAddbaResponse (const Ptr< const Ieee80211AddbaRequest > & addbaRequest, IRecipientBlockAckAgreementPolicy * blockAckAgreementPolicy) protected virtual
 {
     auto addbaResponse = makeShared<Ieee80211AddbaResponse>();
     addbaResponse->setReceiverAddress(addbaRequest->getTransmitterAddress());
     // The Block Ack Policy subfield is set to 1 for immediate Block Ack and 0 for delayed Block Ack.
     Tid tid = addbaRequest->getTid();
     addbaResponse->setTid(tid);
     addbaResponse->setBlockAckPolicy(!addbaRequest->getBlockAckPolicy() && blockAckAgreementPolicy->delayedBlockAckPolicySupported() ? false : true);
     addbaResponse->setBufferSize(addbaRequest->getBufferSize() <= blockAckAgreementPolicy->getMaximumAllowedBufferSize() ? addbaRequest->getBufferSize() : blockAckAgreementPolicy->getMaximumAllowedBufferSize());
     addbaResponse->setBlockAckTimeoutValue(blockAckAgreementPolicy->getBlockAckTimeoutValue() == 0 ? blockAckAgreementPolicy->getBlockAckTimeoutValue() : addbaRequest->getBlockAckTimeoutValue());
     addbaResponse->setAMsduSupported(blockAckAgreementPolicy->aMsduSupported());
     return addbaResponse;
 }
Referenced by processReceivedAddbaRequest().
buildDelba()
const Ptr< Ieee80211Delba > inet::ieee80211::RecipientBlockAckAgreementHandler::buildDelba (MacAddress receiverAddr, Tid tid, int reasonCode) protected virtual
 {
     auto delba = makeShared<Ieee80211Delba>();
     delba->setReceiverAddress(receiverAddr);
     delba->setInitiator(false);
     delba->setTid(tid);
     delba->setReasonCode(reasonCode);
     return delba;
 }
Referenced by blockAckAgreementExpired().
computeEarliestExpirationTime()
simtime_t inet::ieee80211::RecipientBlockAckAgreementHandler::computeEarliestExpirationTime () protected virtual
 {
     simtime_t earliestTime = SIMTIME_MAX;
     for (auto id : blockAckAgreements) {
         auto agreement = id.second;
         earliestTime = std::min(earliestTime, agreement->getExpirationTime());
     }
     return earliestTime;
 }
Referenced by scheduleInactivityTimer().
getAgreement()
RecipientBlockAckAgreement * inet::ieee80211::RecipientBlockAckAgreementHandler::getAgreement (Tid tid, MacAddress originatorAddr) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     auto agreementId = std::make_pair(originatorAddr, tid);
     auto it = blockAckAgreements.find(agreementId);
     return it != blockAckAgreements.end() ? it->second : nullptr;
 }
Referenced by qosFrameReceived().
processReceivedAddbaRequest()
void inet::ieee80211::RecipientBlockAckAgreementHandler::processReceivedAddbaRequest (const Ptr< const Ieee80211AddbaRequest > & addbaRequest, IRecipientBlockAckAgreementPolicy * blockAckAgreementPolicy, IProcedureCallback * callback) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     EV_INFO << "Processing Addba Request from " << addbaRequest->getTransmitterAddress() << endl;
     if (blockAckAgreementPolicy->isAddbaReqAccepted(addbaRequest)) {
         EV_DETAIL << "Addba Request has been accepted. Creating a new Block Ack Agreement." << endl;
         auto agreement = addAgreement(addbaRequest);
         EV_DETAIL << "Agreement is added with the following parameters: " << *agreement << endl;
         EV_DETAIL << "Building Addba Response" << endl;
         auto addbaResponse = buildAddbaResponse(addbaRequest, blockAckAgreementPolicy);
         auto addbaResponsePacket = new Packet("AddbaResponse", addbaResponse);
         callback->processMgmtFrame(addbaResponsePacket, addbaResponse);
     }
 }
processReceivedDelba()
void inet::ieee80211::RecipientBlockAckAgreementHandler::processReceivedDelba (const Ptr< const Ieee80211Delba > & delba, IRecipientBlockAckAgreementPolicy * blockAckAgreementPolicy) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     if (blockAckAgreementPolicy->isDelbaAccepted(delba))
         terminateAgreement(delba->getReceiverAddress(), delba->getTid());
 }
processTransmittedAddbaResp()
void inet::ieee80211::RecipientBlockAckAgreementHandler::processTransmittedAddbaResp (const Ptr< const Ieee80211AddbaResponse > & addbaResp, IBlockAckAgreementHandlerCallback * callback) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     updateAgreement(addbaResp);
     scheduleInactivityTimer(callback);
 }
processTransmittedDelba()
void inet::ieee80211::RecipientBlockAckAgreementHandler::processTransmittedDelba (const Ptr< const Ieee80211Delba > & delba) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     terminateAgreement(delba->getReceiverAddress(), delba->getTid());
 }
qosFrameReceived()
void inet::ieee80211::RecipientBlockAckAgreementHandler::qosFrameReceived (const Ptr< const Ieee80211DataHeader > & qosHeader, IBlockAckAgreementHandlerCallback * callback) override virtual
Implements inet::ieee80211::IRecipientBlockAckAgreementHandler.
 {
     if (qosHeader->getAckPolicy() == AckPolicy::BLOCK_ACK) { // TODO + Implicit Block Ack
         Tid tid = qosHeader->getTid();
         MacAddress originatorAddr = qosHeader->getTransmitterAddress();
         auto agreement = getAgreement(tid, originatorAddr);
         if (agreement)
             scheduleInactivityTimer(callback);
     }
 }
scheduleInactivityTimer()
void inet::ieee80211::RecipientBlockAckAgreementHandler::scheduleInactivityTimer (IBlockAckAgreementHandlerCallback * callback) protected virtual
 {
     simtime_t earliestExpirationTime = computeEarliestExpirationTime();
     if (earliestExpirationTime != SIMTIME_MAX)
         callback->scheduleInactivityTimer(earliestExpirationTime);
 }
Referenced by blockAckAgreementExpired(), processTransmittedAddbaResp(), and qosFrameReceived().
terminateAgreement()
void inet::ieee80211::RecipientBlockAckAgreementHandler::terminateAgreement (MacAddress originatorAddr, Tid tid) protected virtual
 {
     auto agreementId = std::make_pair(originatorAddr, tid);
     auto it = blockAckAgreements.find(agreementId);
     if (it != blockAckAgreements.end()) {
         RecipientBlockAckAgreement *agreement = it->second;
         blockAckAgreements.erase(it);
         delete agreement;
     }
 }
Referenced by processReceivedDelba(), and processTransmittedDelba().
updateAgreement()
void inet::ieee80211::RecipientBlockAckAgreementHandler::updateAgreement (const Ptr< const Ieee80211AddbaResponse > & addbaResponse) protected virtual
 {
     auto id = std::make_pair(addbaResponse->getReceiverAddress(), addbaResponse->getTid());
     auto it = blockAckAgreements.find(id);
     if (it != blockAckAgreements.end()) {
         RecipientBlockAckAgreement *agreement = it->second;
         agreement->addbaResposneSent();
     }
     else
         throw cRuntimeError("Agreement is not found");
 }
Referenced by processTransmittedAddbaResp().
Member Data Documentation
blockAckAgreements
std::map<std::pair<MacAddress, Tid>, RecipientBlockAckAgreement *> inet::ieee80211::RecipientBlockAckAgreementHandler::blockAckAgreements protected
Referenced by addAgreement(), blockAckAgreementExpired(), computeEarliestExpirationTime(), getAgreement(), terminateAgreement(), updateAgreement(), and ~RecipientBlockAckAgreementHandler().
The documentation for this class was generated from the following files:
RecipientBlockAckAgreementHandler.h
RecipientBlockAckAgreementHandler.cc