INET Framework for OMNeT++/OMNEST: inet::ospfv2::AsExternalLsa Class Reference
inet::ospfv2::AsExternalLsa Class Reference
#include <Lsa.h>
Public Member Functions
AsExternalLsa ()
AsExternalLsa (const Ospfv2AsExternalLsa &lsa)
AsExternalLsa (const AsExternalLsa &lsa)
virtual ~AsExternalLsa ()
bool getPurgeable () const
void setPurgeable (bool purge=true)
bool validateLSChecksum () const
bool update (const Ospfv2AsExternalLsa *lsa)
bool differsFrom (const Ospfv2AsExternalLsa *asExternalLSA) const
Public Member Functions inherited from inet::ospfv2::Ospfv2AsExternalLsa
Ospfv2AsExternalLsa ()
Ospfv2AsExternalLsa (const Ospfv2AsExternalLsa &other)
virtual ~Ospfv2AsExternalLsa ()
Ospfv2AsExternalLsa & operator= (const Ospfv2AsExternalLsa &other)
virtual Ospfv2AsExternalLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ospfv2AsExternalLsaContents & getContents () const
virtual Ospfv2AsExternalLsaContents & getContentsForUpdate ()
virtual void setContents (const Ospfv2AsExternalLsaContents &contents)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Public Member Functions inherited from inet::ospfv2::RoutingInfo
RoutingInfo ()
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo ()
void addNextHop (NextHop nextHop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
void setDistance (unsigned long d)
unsigned long getDistance () const
void setParent (Ospfv2Lsa *p)
Ospfv2Lsa * getParent () const
Public Member Functions inherited from inet::ospfv2::LsaTrackingInfo
LsaTrackingInfo ()
LsaTrackingInfo (const LsaTrackingInfo &info)
void setSource (InstallSource installSource)
InstallSource getSource () const
void incrementInstallTime ()
void resetInstallTime ()
unsigned long getInstallTime () const
Protected Attributes
bool purgeable
Protected Attributes inherited from inet::ospfv2::Ospfv2AsExternalLsa
Ospfv2AsExternalLsaContents contents
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Additional Inherited Members
Public Types inherited from inet::ospfv2::LsaTrackingInfo
enum InstallSource { ORIGINATED = 0, FLOODED = 1 }
Protected Member Functions inherited from inet::ospfv2::Ospfv2AsExternalLsa
bool operator== (const Ospfv2AsExternalLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Constructor & Destructor Documentation
AsExternalLsa() [1/3]
inet::ospfv2::AsExternalLsa::AsExternalLsa () inline
 : Ospfv2AsExternalLsa(), RoutingInfo(), LsaTrackingInfo(), purgeable(false) {}
AsExternalLsa() [2/3]
inet::ospfv2::AsExternalLsa::AsExternalLsa (const Ospfv2AsExternalLsa & lsa) inline
 : Ospfv2AsExternalLsa(lsa), RoutingInfo(), LsaTrackingInfo(), purgeable(false) {}
AsExternalLsa() [3/3]
inet::ospfv2::AsExternalLsa::AsExternalLsa (const AsExternalLsa & lsa) inline
 : Ospfv2AsExternalLsa(lsa), RoutingInfo(lsa), LsaTrackingInfo(lsa), purgeable(lsa.purgeable) {}
~AsExternalLsa()
virtual inet::ospfv2::AsExternalLsa::~AsExternalLsa () inline virtual
 {}
Member Function Documentation
differsFrom()
bool inet::ospfv2::AsExternalLsa::differsFrom (const Ospfv2AsExternalLsa * asExternalLSA) const
 {
     const Ospfv2LsaHeader& thisHeader = getHeader();
     const Ospfv2LsaHeader& lsaHeader = asExternalLSA->getHeader();
     bool differentHeader = ((thisHeader.getLsOptions() != lsaHeader.getLsOptions()) ||
                             ((thisHeader.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                             ((thisHeader.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                             (thisHeader.getLsaLength() != lsaHeader.getLsaLength()));
     bool differentBody = false;
     if (!differentHeader) {
         const Ospfv2AsExternalLsaContents& thisContents = getContents();
         const Ospfv2AsExternalLsaContents& lsaContents = asExternalLSA->getContents();
         unsigned int thisTosInfoCount = thisContents.getExternalTOSInfoArraySize();
         differentBody = ((thisContents.getNetworkMask() != lsaContents.getNetworkMask()) ||
                          (thisTosInfoCount != lsaContents.getExternalTOSInfoArraySize()));
         if (!differentBody) {
             for (unsigned int i = 0; i < thisTosInfoCount; i++) {
                 const auto& thisTOSInfo = thisContents.getExternalTOSInfo(i);
                 const auto& lsaTOSInfo = lsaContents.getExternalTOSInfo(i);
                 if ((thisTOSInfo.E_ExternalMetricType != lsaTOSInfo.E_ExternalMetricType) ||
                     (thisTOSInfo.routeCost != lsaTOSInfo.routeCost) ||
                     (thisTOSInfo.forwardingAddress != lsaTOSInfo.forwardingAddress) ||
                     (thisTOSInfo.externalRouteTag != lsaTOSInfo.externalRouteTag) ||
                     (thisTOSInfo.tos != lsaTOSInfo.tos))
                 {
                     differentBody = true;
                     break;
                 }
             }
         }
     }
     return differentHeader || differentBody;
 }
Referenced by update().
getPurgeable()
bool inet::ospfv2::AsExternalLsa::getPurgeable () const inline
 { return purgeable; }
Referenced by inet::ospfv2::Router::ageDatabase().
setPurgeable()
void inet::ospfv2::AsExternalLsa::setPurgeable (bool purge = true) inline
 { purgeable = purge; }
update()
bool inet::ospfv2::AsExternalLsa::update (const Ospfv2AsExternalLsa * lsa)
 {
     bool different = differsFrom(lsa);
     (*this) = (*lsa);
     resetInstallTime();
     if (different) {
         clearNextHops();
     }
     return different;
 }
Referenced by inet::ospfv2::Router::ageDatabase().
validateLSChecksum()
bool inet::ospfv2::AsExternalLsa::validateLSChecksum () const inline
 { return true; } // not implemented
Referenced by inet::ospfv2::Router::ageDatabase().
Member Data Documentation
purgeable
bool inet::ospfv2::AsExternalLsa::purgeable protected
The documentation for this class was generated from the following files:
Lsa.h
AsExternalLsa.cc