INET Framework for OMNeT++/OMNEST: inet::physicallayer::WireJunction Class Reference
inet::physicallayer::WireJunction Class Reference
Models a wiring hub.
#include <WireJunction.h>
Classes
struct TxInfo
Protected Member Functions
virtual void initialize () override
virtual void handleMessage (cMessage *msg) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void setChannelModes ()
virtual void setGateModes ()
virtual void addTxInfo (long incomingTxId, int port, long outgoingTxId, simtime_t finishTime)
virtual void updateTxInfo (TxInfo *txInfo, simtime_t finishTime)
virtual TxInfo * findTxInfo (long incomingTxId, int port)
Protected Attributes
std::vector< TxInfo > txList
int numPorts
int inputGateBaseId
int outputGateBaseId
long numMessages
Detailed Description
Models a wiring hub.
It simply broadcasts the received message (which can be a transmission update, requiring special attention) on all other ports.
Note that no special attention is made to appropriately model frame truncations that occur when the link breaks, or comes back up while a transmission is underway. This is mainly so because being a generic model, WireJunction doesn't know how to produce sliced (truncated) versions of frames. If you need to precisely model what happens when the link state changes, you cannot use this class.
Member Function Documentation
addTxInfo()
void inet::physicallayer::WireJunction::addTxInfo (long incomingTxId, int port, long outgoingTxId, simtime_t finishTime) protected virtual
 {
     txList.push_back(TxInfo());
     TxInfo *tx = &txList.back();
     tx->incomingTxId = incomingTxId;
     tx->outgoingPort = port;
     tx->outgoingTxId = outgoingTxId;
     tx->finishTime = finishTime;
 }
Referenced by handleMessage().
findTxInfo()
WireJunction::TxInfo * inet::physicallayer::WireJunction::findTxInfo (long incomingTxId, int port) protected virtual
 {
     // find transmission, purge expired ones
     int txIndex = -1;
     simtime_t now = getSimulation()->getSimTime();
     for (int i = 0; i < (int)txList.size(); i++) {
         if (txList[i].finishTime < now) {
             txList[i] = txList.back(); // no-op if txList[i] is the last item (i.e. txList.back())
             txList.pop_back();
             i--;
         }
         else if (incomingTxId == txList[i].incomingTxId && port == txList[i].outgoingPort)
             txIndex = i;
     }
     return (txIndex == -1) ? nullptr : &txList[txIndex];
 }
Referenced by handleMessage().
handleMessage()
void inet::physicallayer::WireJunction::handleMessage (cMessage * msg) override protected virtual
 {
     cPacket *signal = check_and_cast<cPacket *>(msg);
     // Handle frame sent down from the network entity: send out on every other port
     int arrivalPort = signal->getArrivalGate()->getIndex();
     EV << "Frame " << signal << " arrived on port " << arrivalPort << ", broadcasting on all other ports\n";
     numMessages++;
     emit(packetReceivedSignal, signal);
     if (numPorts <= 1) {
         delete signal;
         return;
     }
     long incomingTxId = signal->getTransmissionId();
     for (int i = 0; i < numPorts; i++) {
         if (i != arrivalPort) {
             cGate *ogate = gate(outputGateBaseId + i);
             if (!ogate->isConnected())
                 continue;
             cPacket *outSignal = signal->dup();
             SendOptions sendOptions;
             sendOptions.duration(signal->getDuration());
             if (!signal->isUpdate()) {
                 sendOptions.transmissionId(outSignal->getId());
                 addTxInfo(signal->getTransmissionId(), i, outSignal->getId(), simTime() + signal->getDuration());
             }
             else {
                 TxInfo *tx = findTxInfo(incomingTxId, i);
                 if (!tx) { // we missed the original signal, ignore the update
                     delete outSignal;
                     continue;
                 }
                 updateTxInfo(tx, simTime() + signal->getRemainingDuration());
                 sendOptions.updateTx(tx->outgoingTxId, signal->getRemainingDuration());
             }
             // send
             send(outSignal, sendOptions, ogate);
         }
     }
     delete signal;
 }
initialize()
void inet::physicallayer::WireJunction::initialize () override protected virtual
 {
     auto gateNames = getGateNames();
     if (gateNames.size() != 1)
         throw cRuntimeError("Cannot find the gate vector");
     std::string gateName = gateNames[0];
     numPorts = gateSize(gateName.c_str());
     inputGateBaseId = gateBaseId((gateName + "$i").c_str());
     outputGateBaseId = gateBaseId((gateName + "$o").c_str());
     numMessages = 0;
     WATCH(numMessages);
     subscribe(POST_MODEL_CHANGE, this);
     setTxUpdateSupport(true);
     setGateModes();
     setChannelModes();
 }
receiveSignal()
void inet::physicallayer::WireJunction::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     ASSERT(signalID == POST_MODEL_CHANGE);
     if (auto notif = dynamic_cast<cPostGateVectorResizeNotification *>(obj)) {
         if (notif->module == this)
             setGateModes();
         return;
     }
     if (auto notif = dynamic_cast<cPostPathCreateNotification *>(obj)) {
         if ((this == notif->pathStartGate->getOwnerModule()) || (this == notif->pathEndGate->getOwnerModule()))
             setChannelModes();
         return;
     }
 }
setChannelModes()
void inet::physicallayer::WireJunction::setChannelModes () protected virtual
 {
     for (int i = 0; i < numPorts; i++) {
         cGate *outGate = gate(outputGateBaseId + i);
         if (outGate->isConnected()) {
             cDatarateChannel *outTxChannel = check_and_cast<cDatarateChannel *>(outGate->getTransmissionChannel());
             outTxChannel->setMode(cDatarateChannel::MULTI);
         }
     }
 }
Referenced by initialize(), and receiveSignal().
setGateModes()
void inet::physicallayer::WireJunction::setGateModes () protected virtual
 {
     for (int i = 0; i < numPorts; i++)
         gate(inputGateBaseId + i)->setDeliverImmediately(true);
 }
Referenced by initialize(), and receiveSignal().
updateTxInfo()
virtual void inet::physicallayer::WireJunction::updateTxInfo (TxInfo * txInfo, simtime_t finishTime) inline protected virtual
 { txInfo->finishTime = finishTime; }
Referenced by handleMessage().
Member Data Documentation
inputGateBaseId
int inet::physicallayer::WireJunction::inputGateBaseId protected
Referenced by initialize(), and setGateModes().
numMessages
long inet::physicallayer::WireJunction::numMessages protected
Referenced by handleMessage(), and initialize().
numPorts
int inet::physicallayer::WireJunction::numPorts protected
Referenced by handleMessage(), initialize(), setChannelModes(), and setGateModes().
outputGateBaseId
int inet::physicallayer::WireJunction::outputGateBaseId protected
Referenced by handleMessage(), initialize(), and setChannelModes().
txList
std::vector<TxInfo> inet::physicallayer::WireJunction::txList protected
Referenced by addTxInfo(), and findTxInfo().
The documentation for this class was generated from the following files:
WireJunction.h
WireJunction.cc