INET Framework for OMNeT++/OMNEST: inet::tcp::TcpSpoof Class Reference
inet::tcp::TcpSpoof Class Reference
Sends fabricated TCP packets.
#include <TcpSpoof.h>
Protected Member Functions
virtual void sendToIP (Packet *pk, L3Address src, L3Address dest)
virtual unsigned long chooseInitialSeqNum ()
virtual void sendSpoofPacket ()
virtual void initialize () override
virtual void handleMessage (cMessage *msg) override
Detailed Description
Sends fabricated TCP packets.
Member Function Documentation
chooseInitialSeqNum()
unsigned long inet::tcp::TcpSpoof::chooseInitialSeqNum () protected virtual
 {
     // choose an initial send sequence number in the same way as TCP does
     return (unsigned long)SIMTIME_DBL(fmod(simTime() * 250000.0, 1.0 + (double)(unsigned)0xffffffffUL)) & 0xffffffffUL;
 }
Referenced by sendSpoofPacket().
handleMessage()
void inet::tcp::TcpSpoof::handleMessage (cMessage * msg) override protected virtual
 {
     if (!msg->isSelfMessage())
         throw cRuntimeError("Does not process incoming messages");
     sendSpoofPacket();
     delete msg;
 }
initialize()
void inet::tcp::TcpSpoof::initialize () override protected virtual
 {
     simtime_t t = par("t");
     scheduleAt(t, new cMessage("timer"));
 }
sendSpoofPacket()
void inet::tcp::TcpSpoof::sendSpoofPacket () protected virtual
 {
     Packet *packet = new Packet("spoof");
     const auto& tcpseg = makeShared<TcpHeader>();
     L3Address srcAddr = L3AddressResolver().resolve(par("srcAddress"));
     L3Address destAddr = L3AddressResolver().resolve(par("destAddress"));
     int srcPort = par("srcPort");
     int destPort = par("destPort");
     bool isSYN = par("isSYN");
     unsigned long seq = par("seqNo").intValue() == -1 ? chooseInitialSeqNum() : par("seqNo");
     // one can customize the following according to concrete needs
     tcpseg->setSrcPort(srcPort);
     tcpseg->setDestPort(destPort);
     tcpseg->setChunkLength(TCP_MIN_HEADER_LENGTH);
     tcpseg->setSequenceNo(seq);
 //    tcpseg->setAckNo(...);
     tcpseg->setSynBit(isSYN);
     tcpseg->setWindow(16384);
     insertTransportProtocolHeader(packet, Protocol::tcp, tcpseg);
     sendToIP(packet, srcAddr, destAddr);
 }
Referenced by handleMessage().
sendToIP()
void inet::tcp::TcpSpoof::sendToIP (Packet * pk, L3Address src, L3Address dest) protected virtual
 {
     EV_INFO << "Sending: ";
 //    printSegmentBrief(tcpseg);
     ASSERT(pk != nullptr);
     IL3AddressType *addressType = dest.getAddressType();
     pk->addTagIfAbsent<TransportProtocolInd>()->setProtocol(&Protocol::tcp);
     pk->addTagIfAbsent<DispatchProtocolReq>()->setProtocol(addressType->getNetworkProtocol());
     auto addresses = pk->addTagIfAbsent<L3AddressReq>();
     addresses->setSrcAddress(src);
     addresses->setDestAddress(dest);
     emit(packetSentSignal, pk);
     send(pk, "ipOut");
 }
Referenced by sendSpoofPacket().
The documentation for this class was generated from the following files:
TcpSpoof.h
TcpSpoof.cc