INET Framework for OMNeT++/OMNEST: inet::rtp::SenderReport Class Reference
inet::rtp::SenderReport Class Reference
Class generated from inet/transportlayer/rtp/Reports.msg:16 by opp_msgtool.
#include <Reports_m.h>
Public Member Functions
SenderReport ()
SenderReport (const SenderReport &other)
virtual ~SenderReport ()
SenderReport & operator= (const SenderReport &other)
virtual SenderReport * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint64_t getNTPTimeStamp () const
virtual void setNTPTimeStamp (uint64_t NTPTimeStamp)
virtual uint32_t getRTPTimeStamp () const
virtual void setRTPTimeStamp (uint32_t RTPTimeStamp)
virtual uint32_t getPacketCount () const
virtual void setPacketCount (uint32_t packetCount)
virtual uint32_t getByteCount () const
virtual void setByteCount (uint32_t byteCount)
virtual std::string str () const override
Writes a short info about this SenderReport into the given string.
virtual void dump (std::ostream &os) const
Writes a longer info about this SenderReport into the given stream.
Protected Member Functions
bool operator== (const SenderReport &)=delete
Protected Attributes
uint64_t NTPTimeStamp = 0
uint32_t RTPTimeStamp = 0
uint32_t packetCount = 0
uint32_t byteCount = 0
Private Member Functions
void copy (const SenderReport &other)
Detailed Description
Class generated from inet/transportlayer/rtp/Reports.msg:16 by opp_msgtool.
//
// Represents an RTP sender report as contained
// in an ~RtcpSenderReportPacket.
//
class SenderReport extends cObject
{
    // The ntp time stamp.
    uint64_t NTPTimeStamp;
    // The rtp time stamp.
    uint32_t RTPTimeStamp;
    // The number of packets sent.
    uint32_t packetCount;
    // The number of (payload) bytes sent.
    uint32_t byteCount;
}
Constructor & Destructor Documentation
SenderReport() [1/2]
inet::rtp::SenderReport::SenderReport ()
SenderReport() [2/2]
inet::rtp::SenderReport::SenderReport (const SenderReport & other)
~SenderReport()
virtual inet::rtp::SenderReport::~SenderReport () virtual
Member Function Documentation
copy()
void inet::rtp::SenderReport::copy (const SenderReport & other) private
dump()
void inet::rtp::SenderReport::dump (std::ostream & os) const virtual
Writes a longer info about this SenderReport into the given stream.
 {
     os << "SenderReport:" << endl;
     os << "  ntpTimeStamp = " << getNTPTimeStamp() << endl;
     os << "  rtpTimeStamp = " << getRTPTimeStamp() << endl;
     os << "  packetCount = " << getPacketCount() << endl;
     os << "  byteCount = " << getByteCount() << endl;
 }
dup()
virtual SenderReport* inet::rtp::SenderReport::dup () const inline override virtual
 {return new SenderReport(*this);}
getByteCount()
virtual uint32_t inet::rtp::SenderReport::getByteCount () const virtual
Referenced by dump().
getNTPTimeStamp()
virtual uint64_t inet::rtp::SenderReport::getNTPTimeStamp () const virtual
Referenced by dump(), and inet::rtp::RtpReceiverInfo::processSenderReport().
getPacketCount()
virtual uint32_t inet::rtp::SenderReport::getPacketCount () const virtual
Referenced by dump().
getRTPTimeStamp()
virtual uint32_t inet::rtp::SenderReport::getRTPTimeStamp () const virtual
Referenced by dump(), inet::rtp::RtpReceiverInfo::processSenderReport(), and str().
operator=()
SenderReport& inet::rtp::SenderReport::operator= (const SenderReport & other)
operator==()
bool inet::rtp::SenderReport::operator== (const SenderReport &) protected delete
parsimPack()
virtual void inet::rtp::SenderReport::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::SenderReport::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::rtp::doParsimUnpacking().
setByteCount()
virtual void inet::rtp::SenderReport::setByteCount (uint32_t byteCount) virtual
Referenced by inet::rtp::RtpSenderInfo::senderReport().
setNTPTimeStamp()
virtual void inet::rtp::SenderReport::setNTPTimeStamp (uint64_t NTPTimeStamp) virtual
Referenced by inet::rtp::RtpSenderInfo::senderReport().
setPacketCount()
virtual void inet::rtp::SenderReport::setPacketCount (uint32_t packetCount) virtual
Referenced by inet::rtp::RtpSenderInfo::senderReport().
setRTPTimeStamp()
virtual void inet::rtp::SenderReport::setRTPTimeStamp (uint32_t RTPTimeStamp) virtual
Referenced by inet::rtp::RtpSenderInfo::senderReport().
str()
std::string inet::rtp::SenderReport::str () const override virtual
Writes a short info about this SenderReport into the given string.
 {
     std::stringstream out;
     out << "SenderReport.timeStamp=" << getRTPTimeStamp();
     return out.str();
 }
Member Data Documentation
byteCount
uint32_t inet::rtp::SenderReport::byteCount = 0 protected
NTPTimeStamp
uint64_t inet::rtp::SenderReport::NTPTimeStamp = 0 protected
packetCount
uint32_t inet::rtp::SenderReport::packetCount = 0 protected
RTPTimeStamp
uint32_t inet::rtp::SenderReport::RTPTimeStamp = 0 protected
The documentation for this class was generated from the following files:
Reports_m.h
Reports.cc