INET Framework for OMNeT++/OMNEST: inet::queueing::CreditBasedGate Class Reference
inet::queueing::CreditBasedGate Class Reference
#include <CreditBasedGate.h>
Public Member Functions
virtual ~CreditBasedGate ()
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
virtual const char * resolveDirective (char directive) const override
virtual void receiveSignal (cComponent *source, simsignal_t signal, double value, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::queueing::PacketGateBase
virtual bool isOpen () const override
Returns true if the gate is open.
virtual bool isClosed () const
virtual void open () override
Opens the gate and starts traffic go through.
virtual void close () override
Closes the gate and stops traffic.
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual bool canPullSomePacket (cGate *gate) const override
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const override
Returns the packet that can be pulled at the given gate.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
Public Member Functions inherited from inet::queueing::PacketFlowBase
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
virtual Packet * pullPacket (cGate *gate) override
Pulls the packet from the packet source at the given gate.
virtual Packet * pullPacketStart (cGate *gate, bps datarate) override
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate) override
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength) override
Progresses pulling the packet from the packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
virtual int getMaxNumPackets () const override
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const override
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const override
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const override
Returns the total length of all packets in the collection in the range [0, inf).
virtual Packet * getPacket (int index) const override
Returns the packet at the given index.
virtual bool isEmpty () const override
Returns true if there are no packets available in the collection.
virtual void removePacket (Packet *packet) override
Removes a packet from the collection.
virtual void removeAllPackets () override
Removes all packets from the collection.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Public Member Functions inherited from inet::TransparentProtocolRegistrationListener
virtual void mapRegistrationForwardingGates (cGate *gate, std::function< void(cGate *)> f)
virtual bool isForwardingProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingProtocol (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingAnyService (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingService (cGate *gate, ServicePrimitive servicePrimitive) const
virtual void handleRegisterService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyService (cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) override
Static Public Attributes
static simsignal_t creditsChangedSignal = cComponent::registerSignal("creditsChanged")
Static Public Attributes inherited from inet::queueing::PacketGateBase
static simsignal_t gateStateChangedSignal = registerSignal("gateStateChanged")
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void finish () override
virtual void refreshDisplay () const override
virtual void processPacket (Packet *packet) override
virtual bool hasAvailablePacket () const
virtual void updateCurrentCredit ()
virtual void updateCurrentCreditGainRate ()
virtual void emitCurrentCredit ()
virtual void scheduleChangeTimer ()
virtual void processChangeTimer ()
Protected Member Functions inherited from inet::queueing::PacketGateBase
virtual cGate * getRegistrationForwardingGate (cGate *gate) override
virtual bool canPacketFlowThrough (Packet *packet) const
virtual void updateDisplayString () const override
Protected Member Functions inherited from inet::queueing::PacketFlowBase
virtual bool isStreamingPacket () const
virtual void startPacketStreaming (Packet *packet)
virtual void endPacketStreaming (Packet *packet)
virtual void checkPacketStreaming (Packet *packet)
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
Protected Attributes
double idleCreditGainRate = NaN
double transmitCreditSpendRate = NaN
double transmitCreditLimit = NaN
double minCredit = NaN
double maxCredit = NaN
bool isTransmitting = false
bool isInterpacketGap = false
double currentCredit = NaN
double currentCreditGainRate = NaN
double lastCurrentCreditEmitted = NaN
simtime_t lastCurrentCreditEmittedTime = -1
cMessage * changeTimer = nullptr
Protected Attributes inherited from inet::queueing::PacketGateBase
bps bitrate = bps(NaN)
b extraLength = b(-1)
simtime_t extraDuration
bool isOpen_ = false
Protected Attributes inherited from inet::queueing::PacketFlowBase
cGate * inputGate = nullptr
ModuleRef< IActivePacketSource > producer
ModuleRef< IPassivePacketSource > provider
ModuleRef< IPacketCollection > collection
cGate * outputGate = nullptr
ModuleRef< IPassivePacketSink > consumer
ModuleRef< IActivePacketSink > collector
int inProgressStreamId = -1
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Constructor & Destructor Documentation
~CreditBasedGate()
virtual inet::queueing::CreditBasedGate::~CreditBasedGate () inline virtual
 { cancelAndDelete(changeTimer); }
Member Function Documentation
emitCurrentCredit()
void inet::queueing::CreditBasedGate::emitCurrentCredit () protected virtual
 {
     simtime_t now = simTime();
     if (!initialized() || lastCurrentCreditEmitted != currentCredit || lastCurrentCreditEmittedTime != now) {
         emit(creditsChangedSignal, currentCredit);
         lastCurrentCreditEmitted = currentCredit;
         lastCurrentCreditEmittedTime = now;
     }
 }
Referenced by finish(), handleCanPullPacketChanged(), handleMessage(), initialize(), and receiveSignal().
finish()
void inet::queueing::CreditBasedGate::finish () override protected virtual
 {
     updateCurrentCredit();
     updateCurrentCreditGainRate();
     emitCurrentCredit();
 }
handleCanPullPacketChanged()
void inet::queueing::CreditBasedGate::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Reimplemented from inet::queueing::PacketGateBase.
 {
     Enter_Method("handleCanPullPacketChanged");
     // 1. update currentCredit and currentCreditGainRate
     updateCurrentCredit();
     updateCurrentCreditGainRate();
     // 2. notify listeners about currentCredit change
     emitCurrentCredit();
     // 3. reschedule change timer when currentCredit reaches transmitCreditLimit
     scheduleChangeTimer();
     PacketGateBase::handleCanPullPacketChanged(gate);
 }
handleMessage()
void inet::queueing::CreditBasedGate::handleMessage (cMessage * message) override protected virtual
Reimplemented from inet::queueing::PacketFlowBase.
 {
     if (message == changeTimer) {
         // 1. timer is executed when currentCredit reaches transmitCreditLimit with currentCreditGainRate
         currentCredit = transmitCreditLimit;
         // 2. notify listeners and update lastCurrentCreditEmitted
         emitCurrentCredit();
         // 3. open/close gate and allow consumer to pull packet if necessary
         processChangeTimer();
         // 4. update currentCreditGainRate to know the slope when the timer is rescheduled
         updateCurrentCreditGainRate();
         // 5. reschedule change timer based on currentCredit and currentCreditGainRate
         scheduleChangeTimer();
     }
     else
         throw cRuntimeError("Unknown message");
 }
hasAvailablePacket()
virtual bool inet::queueing::CreditBasedGate::hasAvailablePacket () const inline protected virtual
 { return provider->canPullSomePacket(inputGate->getPathStartGate()); }
Referenced by receiveSignal(), and updateCurrentCreditGainRate().
initialize()
void inet::queueing::CreditBasedGate::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketGateBase.
 {
     PacketGateBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         idleCreditGainRate = par("idleCreditGainRate");
         transmitCreditSpendRate = par("transmitCreditSpendRate");
         transmitCreditLimit = par("transmitCreditLimit");
         minCredit = par("minCredit");
         maxCredit = par("maxCredit");
         displayStringTextFormat = par("displayStringTextFormat");
         currentCredit = par("initialCredit");
         currentCreditGainRate = idleCreditGainRate;
         lastCurrentCreditEmitted = currentCredit;
         lastCurrentCreditEmittedTime = simTime();
         isOpen_ = currentCredit >= transmitCreditLimit;
         cModule *module = getContainingNicModule(this);
         module->subscribe(transmissionStartedSignal, this);
         module->subscribe(transmissionEndedSignal, this);
         module->subscribe(interpacketGapEndedSignal, this);
         changeTimer = new cMessage("ChangeTimer");
         WATCH(currentCredit);
         WATCH(currentCreditGainRate);
     }
     else if (stage == INITSTAGE_QUEUEING) {
         updateCurrentCredit();
         updateCurrentCreditGainRate();
         emitCurrentCredit();
         scheduleChangeTimer();
     }
     else if (stage == INITSTAGE_LAST)
         updateDisplayString();
 }
processChangeTimer()
void inet::queueing::CreditBasedGate::processChangeTimer () protected virtual
 {
     if (isOpen_)
         close();
     else
         open();
 }
Referenced by handleMessage().
processPacket()
void inet::queueing::CreditBasedGate::processPacket (Packet * packet) override protected virtual
Reimplemented from inet::queueing::PacketGateBase.
 {
     PacketGateBase::processPacket(packet);
     packet->addTag<CreditGateTag>()->setId(getId());
 }
receiveSignal() [1/2]
void inet::queueing::CreditBasedGate::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(simsignal));
     if (simsignal == transmissionStartedSignal || simsignal == transmissionEndedSignal) {
 #ifdef INET_WITH_PHYSICALLAYERWIRELESSCOMMON
         auto signal = check_and_cast<physicallayer::Signal *>(object);
         auto packet = check_and_cast<Packet *>(signal->getEncapsulatedPacket());
         auto creditGateTag = packet->findTag<CreditGateTag>();
         if (creditGateTag != nullptr && creditGateTag->getId() == getId()) {
             // 1. update currentCredit and currentCreditGainRate because some time may have elapsed
             updateCurrentCredit();
             updateCurrentCreditGainRate();
             emitCurrentCredit();
             // 2. update transmitting state
             if (simsignal == transmissionStartedSignal)
                 isTransmitting = true;
             else if (simsignal == transmissionEndedSignal) {
                 isTransmitting = false;
                 isInterpacketGap = true;
             }
             else
                 throw cRuntimeError("Unknown signal");
             // 3. update currentCreditGainRate and notify listeners about currentCredit change
             updateCurrentCredit();
             updateCurrentCreditGainRate();
             emitCurrentCredit();
             // 4. reschedule change timer when currentCredit reaches transmitCreditLimit
             scheduleChangeTimer();
         }
 #endif
     }
     else
         throw cRuntimeError("Unknown signal");
 }
receiveSignal() [2/2]
void inet::queueing::CreditBasedGate::receiveSignal (cComponent * source, simsignal_t signal, double value, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(simsignal));
     if (simsignal == interpacketGapEndedSignal) {
         if (isInterpacketGap) {
             isInterpacketGap = false;
             // 1. immediately set currentCredit to 0 if there are no packets to transmit
             if (!hasAvailablePacket())
                 currentCredit = std::min(transmitCreditLimit, currentCredit);
             // 2. update currentCreditGainRate and notify listeners about currentCredit change
             updateCurrentCredit();
             updateCurrentCreditGainRate();
             emitCurrentCredit();
             // 3. reschedule change timer when currentCredit reaches transmitCreditLimit
             scheduleChangeTimer();
         }
     }
     else
         throw cRuntimeError("Unknown signal");
 }
refreshDisplay()
void inet::queueing::CreditBasedGate::refreshDisplay () const override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     // NOTE: don't emit current credit and no need to call updateCurrentCreditGainRate
     const_cast<CreditBasedGate *>(this)->updateCurrentCredit();
     updateDisplayString();
 }
resolveDirective()
const char * inet::queueing::CreditBasedGate::resolveDirective (char directive) const override virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     static std::string result;
     switch (directive) {
         case 'n': {
             std::stringstream stream;
             stream << currentCredit;
             result = stream.str();
             break;
         }
         default:
             return PacketGateBase::resolveDirective(directive);
     }
     return result.c_str();
 }
scheduleChangeTimer()
void inet::queueing::CreditBasedGate::scheduleChangeTimer () protected virtual
 {
     ASSERT(lastCurrentCreditEmitted == currentCredit);
     ASSERT(lastCurrentCreditEmittedTime == simTime());
     if (currentCreditGainRate == 0)
         cancelEvent(changeTimer);
     else {
         double changeTime = (transmitCreditLimit - currentCredit) / currentCreditGainRate;
         if (changeTime < 0)
             cancelEvent(changeTimer);
         else if (changeTime > 0 || (isOpen_ ? currentCreditGainRate < 0 : currentCreditGainRate > 0))
             // NOTE: schedule for future or for now if credit change direction and gate state requires
             rescheduleAfter(changeTime, changeTimer);
     }
 }
Referenced by handleCanPullPacketChanged(), handleMessage(), initialize(), and receiveSignal().
updateCurrentCredit()
void inet::queueing::CreditBasedGate::updateCurrentCredit () protected virtual
 {
     currentCredit = lastCurrentCreditEmitted + currentCreditGainRate * (simTime() - lastCurrentCreditEmittedTime).dbl();
     currentCredit = std::max(minCredit, std::min(maxCredit, currentCredit));
 }
Referenced by finish(), handleCanPullPacketChanged(), initialize(), receiveSignal(), and refreshDisplay().
updateCurrentCreditGainRate()
void inet::queueing::CreditBasedGate::updateCurrentCreditGainRate () protected virtual
 {
     if (isTransmitting || isInterpacketGap)
         currentCreditGainRate = -transmitCreditSpendRate;
     else if (currentCredit < 0 || hasAvailablePacket())
         currentCreditGainRate = idleCreditGainRate;
     else
         currentCreditGainRate = 0;
 }
Referenced by finish(), handleCanPullPacketChanged(), handleMessage(), initialize(), and receiveSignal().
Member Data Documentation
changeTimer
cMessage* inet::queueing::CreditBasedGate::changeTimer = nullptr protected
Referenced by handleMessage(), initialize(), and scheduleChangeTimer().
creditsChangedSignal
simsignal_t inet::queueing::CreditBasedGate::creditsChangedSignal = cComponent::registerSignal("creditsChanged") static
Referenced by emitCurrentCredit().
currentCredit
double inet::queueing::CreditBasedGate::currentCredit = NaN protected
Referenced by emitCurrentCredit(), handleMessage(), initialize(), receiveSignal(), resolveDirective(), scheduleChangeTimer(), updateCurrentCredit(), and updateCurrentCreditGainRate().
currentCreditGainRate
double inet::queueing::CreditBasedGate::currentCreditGainRate = NaN protected
Referenced by initialize(), scheduleChangeTimer(), updateCurrentCredit(), and updateCurrentCreditGainRate().
idleCreditGainRate
double inet::queueing::CreditBasedGate::idleCreditGainRate = NaN protected
Referenced by initialize(), and updateCurrentCreditGainRate().
isInterpacketGap
bool inet::queueing::CreditBasedGate::isInterpacketGap = false protected
Referenced by receiveSignal(), and updateCurrentCreditGainRate().
isTransmitting
bool inet::queueing::CreditBasedGate::isTransmitting = false protected
Referenced by receiveSignal(), and updateCurrentCreditGainRate().
lastCurrentCreditEmitted
double inet::queueing::CreditBasedGate::lastCurrentCreditEmitted = NaN protected
Referenced by emitCurrentCredit(), initialize(), scheduleChangeTimer(), and updateCurrentCredit().
lastCurrentCreditEmittedTime
simtime_t inet::queueing::CreditBasedGate::lastCurrentCreditEmittedTime = -1 protected
Referenced by emitCurrentCredit(), initialize(), scheduleChangeTimer(), and updateCurrentCredit().
maxCredit
double inet::queueing::CreditBasedGate::maxCredit = NaN protected
Referenced by initialize(), and updateCurrentCredit().
minCredit
double inet::queueing::CreditBasedGate::minCredit = NaN protected
Referenced by initialize(), and updateCurrentCredit().
transmitCreditLimit
double inet::queueing::CreditBasedGate::transmitCreditLimit = NaN protected
Referenced by handleMessage(), initialize(), receiveSignal(), and scheduleChangeTimer().
transmitCreditSpendRate
double inet::queueing::CreditBasedGate::transmitCreditSpendRate = NaN protected
Referenced by initialize(), and updateCurrentCreditGainRate().
The documentation for this class was generated from the following files:
CreditBasedGate.h
CreditBasedGate.cc