INET Framework for OMNeT++/OMNEST: inet::ospfv2::NeighborState Class Reference
inet::ospfv2::NeighborState Class Reference abstract
#include <Ospfv2NeighborState.h>
Public Member Functions
virtual ~NeighborState ()
virtual void processEvent (Neighbor *neighbor, Neighbor::NeighborEventType event)=0
virtual Neighbor::NeighborStateType getState () const =0
Protected Member Functions
void changeState (Neighbor *neighbor, NeighborState *newState, NeighborState *currentState)
bool updateLsa (Neighbor *neighbor)
Constructor & Destructor Documentation
~NeighborState()
virtual inet::ospfv2::NeighborState::~NeighborState () inline virtual
 {}
Member Function Documentation
changeState()
void inet::ospfv2::NeighborState::changeState (Neighbor * neighbor, NeighborState * newState, NeighborState * currentState) protected
 {
     neighbor->changeState(newState, currentState);
     if ((currentState->getState() == Neighbor::FULL_STATE) || (newState->getState() == Neighbor::FULL_STATE))
         if (updateLsa(neighbor))
             neighbor->getInterface()->getArea()->getRouter()->rebuildRoutingTable();
 }
Referenced by inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateDown::processEvent().
getState()
virtual Neighbor::NeighborStateType inet::ospfv2::NeighborState::getState () const pure virtual
Implemented in inet::ospfv2::NeighborStateAttempt, inet::ospfv2::NeighborStateDown, inet::ospfv2::NeighborStateExchange, inet::ospfv2::NeighborStateExchangeStart, inet::ospfv2::NeighborStateFull, inet::ospfv2::NeighborStateInit, inet::ospfv2::NeighborStateLoading, and inet::ospfv2::NeighborStateTwoWay.
Referenced by changeState(), inet::ospfv2::Neighbor::changeState(), and inet::ospfv2::Neighbor::getState().
processEvent()
virtual void inet::ospfv2::NeighborState::processEvent (Neighbor * neighbor, Neighbor::NeighborEventType event) pure virtual
Implemented in inet::ospfv2::NeighborStateAttempt, inet::ospfv2::NeighborStateDown, inet::ospfv2::NeighborStateExchange, inet::ospfv2::NeighborStateExchangeStart, inet::ospfv2::NeighborStateFull, inet::ospfv2::NeighborStateInit, inet::ospfv2::NeighborStateLoading, and inet::ospfv2::NeighborStateTwoWay.
Referenced by inet::ospfv2::Neighbor::processEvent().
updateLsa()
bool inet::ospfv2::NeighborState::updateLsa (Neighbor * neighbor) protected
 {
     bool shouldRebuildRoutingTable = false;
     RouterId routerID = neighbor->getInterface()->getArea()->getRouter()->getRouterID();
     RouterLsa *routerLSA = neighbor->getInterface()->getArea()->findRouterLSA(routerID);
     if (routerLSA != nullptr) {
         long sequenceNumber = routerLSA->getHeader().getLsSequenceNumber();
         if (sequenceNumber == MAX_SEQUENCE_NUMBER) {
             routerLSA->getHeaderForUpdate().setLsAge(MAX_AGE);
             neighbor->getInterface()->getArea()->floodLSA(routerLSA);
             routerLSA->incrementInstallTime();
         }
         else {
             RouterLsa *newLSA = neighbor->getInterface()->getArea()->originateRouterLSA();
             newLSA->getHeaderForUpdate().setLsSequenceNumber(sequenceNumber + 1);
             shouldRebuildRoutingTable |= routerLSA->update(newLSA);
             delete newLSA;
             neighbor->getInterface()->getArea()->floodLSA(routerLSA);
         }
     }
     if (neighbor->getInterface()->getState() == Ospfv2Interface::DESIGNATED_ROUTER_STATE) {
         NetworkLsa *networkLSA = neighbor->getInterface()->getArea()->findNetworkLSA(neighbor->getInterface()->getAddressRange().address);
         if (networkLSA != nullptr) {
             long sequenceNumber = networkLSA->getHeader().getLsSequenceNumber();
             if (sequenceNumber == MAX_SEQUENCE_NUMBER) {
                 networkLSA->getHeaderForUpdate().setLsAge(MAX_AGE);
                 neighbor->getInterface()->getArea()->floodLSA(networkLSA);
                 networkLSA->incrementInstallTime();
             }
             else {
                 NetworkLsa *newLSA = neighbor->getInterface()->getArea()->originateNetworkLSA(neighbor->getInterface());
                 if (newLSA != nullptr) {
                     newLSA->getHeaderForUpdate().setLsSequenceNumber(sequenceNumber + 1);
                     shouldRebuildRoutingTable |= networkLSA->update(newLSA);
                     delete newLSA;
                 }
                 else { // no neighbors on the network -> old NetworkLsa must be flushed
                     networkLSA->getHeaderForUpdate().setLsAge(MAX_AGE);
                     networkLSA->incrementInstallTime();
                 }
                 neighbor->getInterface()->getArea()->floodLSA(networkLSA);
             }
         }
     }
     return shouldRebuildRoutingTable;
 }
Referenced by changeState().
The documentation for this class was generated from the following files:
Ospfv2NeighborState.h
Ospfv2NeighborState.cc