INET Framework for OMNeT++/OMNEST: inet::sctp::SctpCookieEchoChunk Class Reference
inet::sctp::SctpCookieEchoChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:93 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpCookieEchoChunk (const char *name=nullptr)
SctpCookieEchoChunk (const SctpCookieEchoChunk &other)
virtual ~SctpCookieEchoChunk ()
SctpCookieEchoChunk & operator= (const SctpCookieEchoChunk &other)
virtual SctpCookieEchoChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setCookieArraySize (size_t size)
virtual size_t getCookieArraySize () const
virtual char getCookie (size_t k) const
virtual void setCookie (size_t k, char cookie)
virtual void insertCookie (size_t k, char cookie)
void insertCookie (char cookie)
virtual void appendCookie (char cookie)
virtual void eraseCookie (size_t k)
virtual const SctpCookie * getStateCookie () const
virtual SctpCookie * getStateCookieForUpdate ()
virtual void setStateCookie (SctpCookie *stateCookie)
virtual void setUnrecognizedParametersArraySize (size_t size)
virtual size_t getUnrecognizedParametersArraySize () const
virtual uint8_t getUnrecognizedParameters (size_t k) const
virtual void setUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters)
virtual void insertUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters)
void insertUnrecognizedParameters (uint8_t unrecognizedParameters)
virtual void appendUnrecognizedParameters (uint8_t unrecognizedParameters)
virtual void eraseUnrecognizedParameters (size_t k)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpCookieEchoChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
char * cookie = nullptr
size_t cookie_arraysize = 0
SctpCookie * stateCookie = nullptr
uint8_t * unrecognizedParameters = nullptr
size_t unrecognizedParameters_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpCookieEchoChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:93 by opp_msgtool.
class SctpCookieEchoChunk extends SctpChunk
{
    char cookie[];
    SctpCookie *stateCookie;
    uint8_t unrecognizedParameters[]; //for the serializer to send an Error chunk bundled with a Cookie-Echo
}
Constructor & Destructor Documentation
SctpCookieEchoChunk() [1/2]
inet::sctp::SctpCookieEchoChunk::SctpCookieEchoChunk (const char * name = nullptr)
SctpCookieEchoChunk() [2/2]
inet::sctp::SctpCookieEchoChunk::SctpCookieEchoChunk (const SctpCookieEchoChunk & other)
~SctpCookieEchoChunk()
virtual inet::sctp::SctpCookieEchoChunk::~SctpCookieEchoChunk () virtual
Member Function Documentation
appendCookie()
virtual void inet::sctp::SctpCookieEchoChunk::appendCookie (char cookie) virtual
appendUnrecognizedParameters()
virtual void inet::sctp::SctpCookieEchoChunk::appendUnrecognizedParameters (uint8_t unrecognizedParameters) virtual
copy()
void inet::sctp::SctpCookieEchoChunk::copy (const SctpCookieEchoChunk & other) private
dup()
virtual SctpCookieEchoChunk* inet::sctp::SctpCookieEchoChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpCookieEchoChunk(*this);}
Referenced by inet::sctp::SctpAssociation::retransmitCookieEcho(), and inet::sctp::SctpAssociation::sendCookieEcho().
eraseCookie()
virtual void inet::sctp::SctpCookieEchoChunk::eraseCookie (size_t k) virtual
eraseUnrecognizedParameters()
virtual void inet::sctp::SctpCookieEchoChunk::eraseUnrecognizedParameters (size_t k) virtual
getCookie()
virtual char inet::sctp::SctpCookieEchoChunk::getCookie (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getCookieArraySize()
virtual size_t inet::sctp::SctpCookieEchoChunk::getCookieArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processCookieAckArrived(), inet::sctp::SctpAssociation::retransmitCookieEcho(), and inet::sctp::SctpHeaderSerializer::serialize().
getStateCookie()
virtual const SctpCookie* inet::sctp::SctpCookieEchoChunk::getStateCookie () const virtual
Referenced by inet::sctp::SctpAssociation::processCookieAckArrived(), inet::sctp::SctpAssociation::processCookieEchoArrived(), inet::sctp::SctpAssociation::retransmitCookieEcho(), and inet::sctp::SctpHeaderSerializer::serialize().
getStateCookieForUpdate()
virtual SctpCookie* inet::sctp::SctpCookieEchoChunk::getStateCookieForUpdate () inline virtual
 { return const_cast<SctpCookie *>(const_cast<SctpCookieEchoChunk*>(this)->getStateCookie());}
getUnrecognizedParameters()
virtual uint8_t inet::sctp::SctpCookieEchoChunk::getUnrecognizedParameters (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getUnrecognizedParametersArraySize()
virtual size_t inet::sctp::SctpCookieEchoChunk::getUnrecognizedParametersArraySize () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
insertCookie() [1/2]
void inet::sctp::SctpCookieEchoChunk::insertCookie (char cookie) inline
 {appendCookie(cookie);}
insertCookie() [2/2]
virtual void inet::sctp::SctpCookieEchoChunk::insertCookie (size_t k, char cookie) virtual
insertUnrecognizedParameters() [1/2]
virtual void inet::sctp::SctpCookieEchoChunk::insertUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters) virtual
insertUnrecognizedParameters() [2/2]
void inet::sctp::SctpCookieEchoChunk::insertUnrecognizedParameters (uint8_t unrecognizedParameters) inline
 {appendUnrecognizedParameters(unrecognizedParameters);}
operator=()
SctpCookieEchoChunk& inet::sctp::SctpCookieEchoChunk::operator= (const SctpCookieEchoChunk & other)
operator==()
bool inet::sctp::SctpCookieEchoChunk::operator== (const SctpCookieEchoChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpCookieEchoChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpCookieEchoChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setCookie()
virtual void inet::sctp::SctpCookieEchoChunk::setCookie (size_t k, char cookie) virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho().
setCookieArraySize()
virtual void inet::sctp::SctpCookieEchoChunk::setCookieArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho().
setStateCookie()
virtual void inet::sctp::SctpCookieEchoChunk::setStateCookie (SctpCookie * stateCookie) virtual
Referenced by inet::sctp::SctpAssociation::retransmitCookieEcho(), and inet::sctp::SctpAssociation::sendCookieEcho().
setUnrecognizedParameters()
virtual void inet::sctp::SctpCookieEchoChunk::setUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters) virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho().
setUnrecognizedParametersArraySize()
virtual void inet::sctp::SctpCookieEchoChunk::setUnrecognizedParametersArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho().
Member Data Documentation
cookie
char* inet::sctp::SctpCookieEchoChunk::cookie = nullptr protected
cookie_arraysize
size_t inet::sctp::SctpCookieEchoChunk::cookie_arraysize = 0 protected
stateCookie
SctpCookie* inet::sctp::SctpCookieEchoChunk::stateCookie = nullptr protected
unrecognizedParameters
uint8_t* inet::sctp::SctpCookieEchoChunk::unrecognizedParameters = nullptr protected
unrecognizedParameters_arraysize
size_t inet::sctp::SctpCookieEchoChunk::unrecognizedParameters_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h