INET Framework for OMNeT++/OMNEST: inet::SctpInfoReq Class Reference
inet::SctpInfoReq Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:191 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpInfoReq ()
SctpInfoReq (const SctpInfoReq &other)
virtual ~SctpInfoReq ()
SctpInfoReq & operator= (const SctpInfoReq &other)
virtual SctpInfoReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getText () const
virtual void setText (int text)
Public Member Functions inherited from inet::SctpCommandReq
SctpCommandReq ()
SctpCommandReq (const SctpCommandReq &other)
virtual ~SctpCommandReq ()
SctpCommandReq & operator= (const SctpCommandReq &other)
virtual int getSocketId () const
virtual void setSocketId (int socketId)
virtual int getSid () const
virtual void setSid (int sid)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs)
virtual int getSsn () const
virtual void setSsn (int ssn)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered)
virtual double getPrValue () const
virtual void setPrValue (double prValue)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getGate () const
virtual void setGate (int gate)
virtual int getFd () const
virtual void setFd (int fd)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SctpInfoReq &)=delete
Protected Member Functions inherited from inet::SctpCommandReq
bool operator== (const SctpCommandReq &)=delete
Protected Attributes
int text = 0
Protected Attributes inherited from inet::SctpCommandReq
int socketId = -1
int sid = -1
int numMsgs = 1
int ssn = -1
unsigned short sendUnordered = false
double prValue = 0
L3Address localAddr
L3Address remoteAddr
int localPort = -1
int remotePort = -1
int gate = -1
int fd = -1
Private Member Functions
void copy (const SctpInfoReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:191 by opp_msgtool.
class SctpInfoReq extends SctpCommandReq
{
    int text = 0;
}
Constructor & Destructor Documentation
SctpInfoReq() [1/2]
inet::SctpInfoReq::SctpInfoReq ()
SctpInfoReq() [2/2]
inet::SctpInfoReq::SctpInfoReq (const SctpInfoReq & other)
~SctpInfoReq()
virtual inet::SctpInfoReq::~SctpInfoReq () virtual
Member Function Documentation
copy()
void inet::SctpInfoReq::copy (const SctpInfoReq & other) private
dup()
virtual SctpInfoReq* inet::SctpInfoReq::dup () const inline override virtual
Reimplemented from inet::SctpCommandReq.
 {return new SctpInfoReq(*this);}
getText()
virtual int inet::SctpInfoReq::getText () const virtual
Referenced by inet::sctp::SctpAssociation::process_QUEUE_BYTES_LIMIT(), and inet::sctp::SctpAssociation::process_QUEUE_MSGS_LIMIT().
operator=()
SctpInfoReq& inet::SctpInfoReq::operator= (const SctpInfoReq & other)
operator==()
bool inet::SctpInfoReq::operator== (const SctpInfoReq &) protected delete
parsimPack()
virtual void inet::SctpInfoReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpInfoReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimUnpacking().
setText()
virtual void inet::SctpInfoReq::setText (int text) virtual
Referenced by inet::SctpServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::SctpClient::sendQueueRequest(), inet::SctpPeer::sendQueueRequest(), inet::SctpNatPeer::sendQueueRequest(), and inet::NetPerfMeter::sendSCTPQueueRequest().
Member Data Documentation
text
int inet::SctpInfoReq::text = 0 protected
The documentation for this class was generated from the following file:
SctpCommand_m.h