INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211HrDsssPreambleMode Class Reference
inet::physicallayer::Ieee80211HrDsssPreambleMode Class Reference
#include <Ieee80211HrDsssMode.h>
Public Member Functions
Ieee80211HrDsssPreambleMode (const Ieee80211HrDsssPreambleType preambleType)
Ieee80211HrDsssPreambleType getPreambleType () const
b getSyncFieldLength () const
b getSfdFieldLength () const
b getBitLength () const
virtual bps getNetBitrate () const
virtual bps getGrossBitrate () const
virtual const simtime_t getDuration () const override
virtual const DbpskModulation * getModulation () const
virtual Ptr< Ieee80211PhyPreamble > createPreamble () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const Ieee80211HrDsssPreambleType preambleType
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211HrDsssPreambleMode()
inet::physicallayer::Ieee80211HrDsssPreambleMode::Ieee80211HrDsssPreambleMode (const Ieee80211HrDsssPreambleType preambleType)
                                                                                                        :
     preambleType(preambleType)
 {
 }
Member Function Documentation
createPreamble()
virtual Ptr<Ieee80211PhyPreamble> inet::physicallayer::Ieee80211HrDsssPreambleMode::createPreamble () const inline override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 { return makeShared<Ieee80211HrDsssPhyPreamble>(); }
getBitLength()
b inet::physicallayer::Ieee80211HrDsssPreambleMode::getBitLength () const inline
 { return getSyncFieldLength() + getSfdFieldLength(); }
getDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HrDsssPreambleMode::getDuration () const inline override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 { return (double)getBitLength().get() / getNetBitrate().get(); }
Referenced by inet::physicallayer::Ieee80211HrDsssMode::getDuration(), and inet::physicallayer::Ieee80211HrDsssMode::getPreambleLength().
getGrossBitrate()
virtual bps inet::physicallayer::Ieee80211HrDsssPreambleMode::getGrossBitrate () const inline virtual
 { return getNetBitrate(); }
getModulation()
virtual const DbpskModulation* inet::physicallayer::Ieee80211HrDsssPreambleMode::getModulation () const inline virtual
 { return &DbpskModulation::singleton; }
getNetBitrate()
virtual bps inet::physicallayer::Ieee80211HrDsssPreambleMode::getNetBitrate () const inline virtual
 { return Mbps(1); }
getPreambleType()
Ieee80211HrDsssPreambleType inet::physicallayer::Ieee80211HrDsssPreambleMode::getPreambleType () const inline
 { return preambleType; }
Referenced by inet::physicallayer::Ieee80211HrDsssMode::getPhyRxStartDelay().
getSfdFieldLength()
b inet::physicallayer::Ieee80211HrDsssPreambleMode::getSfdFieldLength () const inline
 { return b(16); }
getSyncFieldLength()
b inet::physicallayer::Ieee80211HrDsssPreambleMode::getSyncFieldLength () const inline
 { return preambleType == IEEE80211_HRDSSS_PREAMBLE_TYPE_SHORT ? b(72) : b(128); }
Member Data Documentation
preambleType
const Ieee80211HrDsssPreambleType inet::physicallayer::Ieee80211HrDsssPreambleMode::preambleType protected
The documentation for this class was generated from the following files:
Ieee80211HrDsssMode.h
Ieee80211HrDsssMode.cc