INET Framework for OMNeT++/OMNEST: inet::rtp::RtpSenderStatusMessage Class Reference
inet::rtp::RtpSenderStatusMessage Class Reference
Class generated from inet/transportlayer/rtp/RtpSenderStatusMessage.msg:30 by opp_msgtool.
#include <RtpSenderStatusMessage_m.h>
Public Member Functions
RtpSenderStatusMessage (const char *name=nullptr, short kind=0)
RtpSenderStatusMessage (const RtpSenderStatusMessage &other)
virtual ~RtpSenderStatusMessage ()
RtpSenderStatusMessage & operator= (const RtpSenderStatusMessage &other)
virtual RtpSenderStatusMessage * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual RtpSenderStatus getStatus () const
virtual void setStatus (RtpSenderStatus status)
virtual uint32_t getTimeStamp () const
virtual void setTimeStamp (uint32_t timeStamp)
Protected Member Functions
bool operator== (const RtpSenderStatusMessage &)=delete
Protected Attributes
RtpSenderStatus status = static_cast<inet::rtp::RtpSenderStatus>(-1)
uint32_t timeStamp = 0
Private Member Functions
void copy (const RtpSenderStatusMessage &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpSenderStatusMessage.msg:30 by opp_msgtool.
packet RtpSenderStatusMessage
{
    RtpSenderStatus status;
    uint32_t timeStamp;
}
Constructor & Destructor Documentation
RtpSenderStatusMessage() [1/2]
inet::rtp::RtpSenderStatusMessage::RtpSenderStatusMessage (const char * name = nullptr, short kind = 0)
RtpSenderStatusMessage() [2/2]
inet::rtp::RtpSenderStatusMessage::RtpSenderStatusMessage (const RtpSenderStatusMessage & other)
~RtpSenderStatusMessage()
virtual inet::rtp::RtpSenderStatusMessage::~RtpSenderStatusMessage () virtual
Member Function Documentation
copy()
void inet::rtp::RtpSenderStatusMessage::copy (const RtpSenderStatusMessage & other) private
dup()
virtual RtpSenderStatusMessage* inet::rtp::RtpSenderStatusMessage::dup () const inline override virtual
 {return new RtpSenderStatusMessage(*this);}
getStatus()
virtual RtpSenderStatus inet::rtp::RtpSenderStatusMessage::getStatus () const virtual
Referenced by inet::rtp::Rtp::senderModuleStatus().
getTimeStamp()
virtual uint32_t inet::rtp::RtpSenderStatusMessage::getTimeStamp () const virtual
Referenced by inet::rtp::Rtp::senderModuleStatus().
operator=()
RtpSenderStatusMessage& inet::rtp::RtpSenderStatusMessage::operator= (const RtpSenderStatusMessage & other)
operator==()
bool inet::rtp::RtpSenderStatusMessage::operator== (const RtpSenderStatusMessage &) protected delete
parsimPack()
virtual void inet::rtp::RtpSenderStatusMessage::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpSenderStatusMessage::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::rtp::doParsimUnpacking().
setStatus()
virtual void inet::rtp::RtpSenderStatusMessage::setStatus (RtpSenderStatus status) virtual
Referenced by inet::rtp::RtpPayloadSender::endOfFile(), inet::rtp::RtpPayloadSender::pause(), inet::rtp::RtpPayloadSender::play(), and inet::rtp::RtpPayloadSender::stop().
setTimeStamp()
virtual void inet::rtp::RtpSenderStatusMessage::setTimeStamp (uint32_t timeStamp) virtual
Referenced by inet::rtp::RtpPayloadSender::play().
Member Data Documentation
status
RtpSenderStatus inet::rtp::RtpSenderStatusMessage::status = static_cast<inet::rtp::RtpSenderStatus>(-1) protected
timeStamp
uint32_t inet::rtp::RtpSenderStatusMessage::timeStamp = 0 protected
The documentation for this class was generated from the following file:
RtpSenderStatusMessage_m.h