INET Framework for OMNeT++/OMNEST: inet::sctp::SctpChecksum Class Reference
inet::sctp::SctpChecksum Class Reference
Calculates checksum.
#include <SctpChecksum.h>
Public Member Functions
SctpChecksum ()
Static Public Member Functions
static uint32_t checksum (const void *addr, unsigned int count)
Detailed Description
Calculates checksum.
Constructor & Destructor Documentation
SctpChecksum()
inet::sctp::SctpChecksum::SctpChecksum () inline
 {}
Member Function Documentation
checksum()
uint32_t inet::sctp::SctpChecksum::checksum (const void * addr, unsigned int count) static
 {
     uint32_t h;
     const uint8_t *buf = static_cast<const uint8_t *>(addr);
     unsigned char byte0, byte1, byte2, byte3;
     uint32_t crc32c;
     uint32_t i;
     uint32_t res = (~0L);
     for (i = 0; i < len; i++) {
         CRC32C(res, buf[i]);
     }
     h = ~res;
     byte0 = h & 0xff;
     byte1 = (h >> 8) & 0xff;
     byte2 = (h >> 16) & 0xff;
     byte3 = (h >> 24) & 0xff;
     crc32c = ((byte0 << 24) | (byte1 << 16) | (byte2 << 8) | byte3);
     return htonl(crc32c);
 }
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpCrcInsertion::insertCrc(), and inet::sctp::SctpHeaderSerializer::serialize().
The documentation for this class was generated from the following files:
SctpChecksum.h
SctpChecksum.cc