INET Framework for OMNeT++/OMNEST: inet::HeatMapFigure Class Reference
inet::HeatMapFigure Class Reference
#include <HeatMapFigure.h>
Public Member Functions
HeatMapFigure (int size, const char *name)
virtual const char * getClassNameForRenderer () const
virtual void heatPoint (int x, int y)
virtual void heatLine (int x1, int y1, int x2, int y2)
virtual void coolDown ()
Protected Member Functions
double getHeat (int x, int y)
void setHeat (int x, int y, double value)
Protected Attributes
double alpha = 0.5
double coolingSpeed = 0.01
cFigure::Color fromColor = cFigure::BLACK
cFigure::Color toColor = cFigure::RED
simtime_t lastCoolDown
Constructor & Destructor Documentation
HeatMapFigure()
inet::HeatMapFigure::HeatMapFigure (int size, const char * name)
                                                        :
     cPixmapFigure(name)
 {
     setPixmap(cFigure::Pixmap(size, size));
     fillPixmap(fromColor, 0);
 }
Member Function Documentation
coolDown()
void inet::HeatMapFigure::coolDown () virtual
 {
     double factor = exp(coolingSpeed * (lastCoolDown - simTime()).dbl());
     if (factor < 0.9) {
         lastCoolDown = simTime();
         for (int x = 0; x < getPixmapWidth(); x++)
             for (int y = 0; y < getPixmapHeight(); y++)
                 setHeat(x, y, getHeat(x, y) * factor);
     }
 }
getClassNameForRenderer()
virtual const char* inet::HeatMapFigure::getClassNameForRenderer () const inline virtual
 { return "cPixmapFigure"; }
getHeat()
double inet::HeatMapFigure::getHeat (int x, int y) protected
 {
     return getPixelOpacity(x, y);
 }
Referenced by coolDown(), and heatPoint().
heatLine()
void inet::HeatMapFigure::heatLine (int x1, int y1, int x2, int y2) virtual
 {
     // NOTE: http://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm
     bool steep = (std::abs(y2 - y1) > std::abs(x2 - x1));
     if (steep) {
         std::swap(x1, y1);
         std::swap(x2, y2);
     }
     if (x1 > x2) {
         std::swap(x1, x2);
         std::swap(y1, y2);
     }
     double dx = x2 - x1;
     double dy = std::abs(y2 - y1);
     double error = dx / 2.0f;
     int yStep = (y1 < y2) ? 1 : -1;
     int y = y1;
     for (int x = x1; x <= x2; x++) {
         if (steep)
             heatPoint(y, x);
         else
             heatPoint(x, y);
         error -= dy;
         if (error < 0) {
             y += yStep;
             error += dx;
         }
     }
 }
heatPoint()
void inet::HeatMapFigure::heatPoint (int x, int y) virtual
 {
     double value = alpha + (1 - alpha) * getHeat(x, y);
     setHeat(x, y, value);
 }
Referenced by heatLine().
setHeat()
void inet::HeatMapFigure::setHeat (int x, int y, double value) protected
 {
     cFigure::Color color(
             (1 - value) * fromColor.red + value * toColor.red,
             (1 - value) * fromColor.green + value * toColor.green,
             (1 - value) * fromColor.blue + value * toColor.blue);
     setPixel(x, y, color, value);
 }
Referenced by coolDown(), and heatPoint().
Member Data Documentation
alpha
double inet::HeatMapFigure::alpha = 0.5 protected
Referenced by heatPoint().
coolingSpeed
double inet::HeatMapFigure::coolingSpeed = 0.01 protected
Referenced by coolDown().
fromColor
cFigure::Color inet::HeatMapFigure::fromColor = cFigure::BLACK protected
Referenced by HeatMapFigure(), and setHeat().
lastCoolDown
simtime_t inet::HeatMapFigure::lastCoolDown protected
Referenced by coolDown().
toColor
cFigure::Color inet::HeatMapFigure::toColor = cFigure::RED protected
Referenced by setHeat().
The documentation for this class was generated from the following files:
HeatMapFigure.h
HeatMapFigure.cc