INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRateSelection Class Reference
inet::ieee80211::IRateSelection Class Reference abstract
Abstract interface for rate selection.
#include <IRateSelection.h>
Public Member Functions
virtual ~IRateSelection ()
virtual const physicallayer::IIeee80211Mode * computeResponseCtsFrameMode (Packet *packet, const Ptr< const Ieee80211RtsFrame > &rtsFrame)=0
virtual const physicallayer::IIeee80211Mode * computeResponseAckFrameMode (Packet *packet, const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader)=0
virtual const physicallayer::IIeee80211Mode * computeMode (Packet *packet, const Ptr< const Ieee80211MacHeader > &header)=0
Static Public Attributes
static simsignal_t datarateSelectedSignal = cComponent::registerSignal("datarateSelected")
Detailed Description
Abstract interface for rate selection.
Rate selection decides what bit rate (or MCS) should be used for any particular frame. The rules of rate selection is described in the 802.11 specification in the section titled "Multirate Support".
Constructor & Destructor Documentation
~IRateSelection()
virtual inet::ieee80211::IRateSelection::~IRateSelection () inline virtual
 {}
Member Function Documentation
computeMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IRateSelection::computeMode (Packet * packet, const Ptr< const Ieee80211MacHeader > & header) pure virtual
Implemented in inet::ieee80211::RateSelection.
Referenced by inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField(), and inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField().
computeResponseAckFrameMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IRateSelection::computeResponseAckFrameMode (Packet * packet, const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) pure virtual
Implemented in inet::ieee80211::RateSelection.
Referenced by inet::ieee80211::RecipientAckPolicy::computeAckDuration(), inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), and inet::ieee80211::OriginatorAckPolicy::getAckTimeout().
computeResponseCtsFrameMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IRateSelection::computeResponseCtsFrameMode (Packet * packet, const Ptr< const Ieee80211RtsFrame > & rtsFrame) pure virtual
Implemented in inet::ieee80211::RateSelection.
Referenced by inet::ieee80211::CtsPolicy::computeCtsDuration(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), and inet::ieee80211::RtsPolicy::getCtsTimeout().
Member Data Documentation
datarateSelectedSignal
simsignal_t inet::ieee80211::IRateSelection::datarateSelectedSignal = cComponent::registerSignal("datarateSelected") static
Referenced by inet::ieee80211::Dcf::transmitControlResponseFrame(), inet::ieee80211::Hcf::transmitControlResponseFrame(), inet::ieee80211::Dcf::transmitFrame(), and inet::ieee80211::Hcf::transmitFrame().
The documentation for this class was generated from the following files:
IRateSelection.h
IRateSelection.cc