INET Framework for OMNeT++/OMNEST: inet::tcp::TcpSegmentTransmitInfoList Class Reference
inet::tcp::TcpSegmentTransmitInfoList Class Reference
#include <TcpSegmentTransmitInfoList.h>
Classes
class Item
Public Types
typedef std::list< Item > TcpSegmentTransmitInfoItems
Public Member Functions
void set (uint32_t beg, uint32_t end, simtime_t sentTime)
const Item * get (uint32_t seq) const
returns pointer to Item, or nullptr if not found
void clearTo (uint32_t endseg)
Public Attributes
TcpSegmentTransmitInfoItems regions
Member Typedef Documentation
TcpSegmentTransmitInfoItems
typedef std::list<Item> inet::tcp::TcpSegmentTransmitInfoList::TcpSegmentTransmitInfoItems
Member Function Documentation
clearTo()
void inet::tcp::TcpSegmentTransmitInfoList::clearTo (uint32_t endseg)
 {
     while (!regions.empty() && seqLE(regions.front().end, endseq))
         regions.pop_front();
     if (!regions.empty() && seqLess(regions.front().beg, endseq))
         regions.front().beg = endseq;
 }
Referenced by inet::tcp::TcpWestwood::dataSent(), inet::tcp::TcpVegas::dataSent(), inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
get()
const TcpSegmentTransmitInfoList::Item * inet::tcp::TcpSegmentTransmitInfoList::get (uint32_t seq) const
returns pointer to Item, or nullptr if not found
 {
     for (const auto& elem : regions) {
         if (seqLess(seq, elem.beg))
             break;
         if (seqLE(elem.beg, seq) && seqLess(seq, elem.end))
             return &(elem);
     }
     return nullptr;
 }
Referenced by inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
set()
void inet::tcp::TcpSegmentTransmitInfoList::set (uint32_t beg, uint32_t end, simtime_t sentTime)
 {
     ASSERT(seqLess(beg, end));
     ASSERT(regions.empty() || (seqLE(regions.front().beg, beg) && seqLE(beg, regions.back().end)));
     if (regions.empty() || (regions.back().end == beg))
         regions.push_back(Item(beg, end, sentTime, sentTime, 1));
     else if (end == regions.front().beg)
         regions.push_front(Item(beg, end, sentTime, sentTime, 1));
     else {
         auto i = regions.begin();
         while (seqLE(i->end, beg))
             ++i;
         ASSERT(seqLE(i->beg, beg));
         if (beg != i->beg) {
             regions.insert(i, Item(i->beg, beg, i->firstSentTime, i->lastSentTime, i->transmitCount));
             i->beg = beg;
         }
         while (i != regions.end() && seqLE(i->end, end)) {
             ASSERT(beg == i->beg);
             if (i->firstSentTime > sentTime)
                 i->firstSentTime = sentTime;
             if (i->lastSentTime < sentTime)
                 i->lastSentTime = sentTime;
             i->transmitCount++;
             beg = i->end;
             ++i;
         }
         if (beg != end) {
             if (i != regions.end()) {
                 ASSERT(beg == i->beg);
                 simtime_t firstSent = std::min(i->firstSentTime, sentTime);
                 simtime_t lastSent = std::max(i->lastSentTime, sentTime);
 //                if (firstSent > sentTime)
 //                    firstSent = sentTime;
 //                if (lastSent < sentTime)
 //                    lastSent = sentTime;
                 regions.insert(i, Item(beg, end, firstSent, lastSent, i->transmitCount + 1));
                 i->beg = end;
             }
             else
                 regions.push_back(Item(beg, end, sentTime, sentTime, 1));
         }
     }
 }
Referenced by inet::tcp::TcpWestwood::dataSent(), inet::tcp::TcpVegas::dataSent(), inet::tcp::TcpWestwood::segmentRetransmitted(), and inet::tcp::TcpVegas::segmentRetransmitted().
Member Data Documentation
regions
TcpSegmentTransmitInfoItems inet::tcp::TcpSegmentTransmitInfoList::regions
Referenced by clearTo(), get(), and set().
The documentation for this class was generated from the following files:
TcpSegmentTransmitInfoList.h
TcpSegmentTransmitInfoList.cc