INET Framework for OMNeT++/OMNEST: inet::physicallayer::ScalarSnir Class Reference
inet::physicallayer::ScalarSnir Class Reference
#include <ScalarSnir.h>
Public Member Functions
ScalarSnir (const IReception *reception, const INoise *noise)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual double getMin () const override
virtual double getMax () const override
virtual double getMean () const override
Public Member Functions inherited from inet::physicallayer::SnirBase
SnirBase (const IReception *reception, const INoise *noise)
virtual const IReception * getReception () const override
virtual const INoise * getNoise () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual double computeMin () const
virtual double computeMax () const
virtual double computeMean () const
Protected Attributes
double minSNIR
double maxSNIR
double meanSNIR
Protected Attributes inherited from inet::physicallayer::SnirBase
const IReception * reception
const INoise * noise
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
ScalarSnir()
inet::physicallayer::ScalarSnir::ScalarSnir (const IReception * reception, const INoise * noise)
                                                                        :
     SnirBase(reception, noise),
     minSNIR(NaN),
     maxSNIR(NaN),
     meanSNIR(NaN)
 {
 }
Member Function Documentation
computeMax()
double inet::physicallayer::ScalarSnir::computeMax () const protected virtual
 {
     const IScalarSignal *scalarSignalAnalogModel = check_and_cast<const IScalarSignal *>(reception->getAnalogModel());
     const ScalarNoise *scalarNoise = check_and_cast<const ScalarNoise *>(noise);
     return unit(scalarSignalAnalogModel->getPower() / scalarNoise->computeMinPower(reception->getStartTime(), reception->getEndTime())).get();
 }
Referenced by getMax().
computeMean()
double inet::physicallayer::ScalarSnir::computeMean () const protected virtual
 {
     // TODO
     return NaN;
 }
Referenced by getMean().
computeMin()
double inet::physicallayer::ScalarSnir::computeMin () const protected virtual
 {
     const IScalarSignal *scalarSignalAnalogModel = check_and_cast<const IScalarSignal *>(reception->getAnalogModel());
     const ScalarNoise *scalarNoise = check_and_cast<const ScalarNoise *>(noise);
     return unit(scalarSignalAnalogModel->getPower() / scalarNoise->computeMaxPower(reception->getStartTime(), reception->getEndTime())).get();
 }
Referenced by getMin().
getMax()
double inet::physicallayer::ScalarSnir::getMax () const override virtual
Implements inet::physicallayer::ISnir.
 {
     if (std::isnan(maxSNIR))
         maxSNIR = computeMax();
     return maxSNIR;
 }
getMean()
double inet::physicallayer::ScalarSnir::getMean () const override virtual
Implements inet::physicallayer::ISnir.
 {
     if (std::isnan(meanSNIR))
         meanSNIR = computeMean();
     return meanSNIR;
 }
getMin()
double inet::physicallayer::ScalarSnir::getMin () const override virtual
Implements inet::physicallayer::ISnir.
 {
     if (std::isnan(minSNIR))
         minSNIR = computeMin();
     return minSNIR;
 }
printToStream()
std::ostream & inet::physicallayer::ScalarSnir::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::SnirBase.
 {
     stream << "ScalarSnir";
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(minSNIR);
     return stream;
 }
Member Data Documentation
maxSNIR
double inet::physicallayer::ScalarSnir::maxSNIR mutable protected
Referenced by getMax().
meanSNIR
double inet::physicallayer::ScalarSnir::meanSNIR mutable protected
Referenced by getMean().
minSNIR
double inet::physicallayer::ScalarSnir::minSNIR mutable protected
Referenced by getMin(), and printToStream().
The documentation for this class was generated from the following files:
ScalarSnir.h
ScalarSnir.cc