INET Framework for OMNeT++/OMNEST: inet::bgp::BgpUpdatePathAttributesNextHop Class Reference
inet::bgp::BgpUpdatePathAttributesNextHop Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:147 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpUpdatePathAttributesNextHop ()
BgpUpdatePathAttributesNextHop (const BgpUpdatePathAttributesNextHop &other)
virtual ~BgpUpdatePathAttributesNextHop ()
BgpUpdatePathAttributesNextHop & operator= (const BgpUpdatePathAttributesNextHop &other)
virtual BgpUpdatePathAttributesNextHop * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getValue () const
virtual ::inet::Ipv4Address & getValueForUpdate ()
virtual void setValue (const ::inet::Ipv4Address &value)
Public Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
BgpUpdatePathAttributes ()
BgpUpdatePathAttributes (const BgpUpdatePathAttributes &other)
virtual ~BgpUpdatePathAttributes ()
BgpUpdatePathAttributes & operator= (const BgpUpdatePathAttributes &other)
virtual bool getOptionalBit () const
virtual void setOptionalBit (bool optionalBit)
virtual bool getTransitiveBit () const
virtual void setTransitiveBit (bool transitiveBit)
virtual bool getPartialBit () const
virtual void setPartialBit (bool partialBit)
virtual bool getExtendedLengthBit () const
virtual void setExtendedLengthBit (bool extendedLengthBit)
virtual unsigned short getReserved () const
virtual void setReserved (unsigned short reserved)
virtual BgpUpdateAttributeTypeCode getTypeCode () const
virtual void setTypeCode (BgpUpdateAttributeTypeCode typeCode)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const BgpUpdatePathAttributesNextHop &)=delete
Protected Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
bool operator== (const BgpUpdatePathAttributes &)=delete
Protected Attributes
::inet::Ipv4Address value
Protected Attributes inherited from inet::bgp::BgpUpdatePathAttributes
bool optionalBit = false
bool transitiveBit = false
bool partialBit = false
bool extendedLengthBit = false
unsigned short reserved = 0
BgpUpdateAttributeTypeCode typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1)
unsigned short length = 0
Private Member Functions
void copy (const BgpUpdatePathAttributesNextHop &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:147 by opp_msgtool.
//NEXT_HOP (RFC4271 Section 4.3, Type code 3):
class BgpUpdatePathAttributesNextHop extends BgpUpdatePathAttributes
{
    typeCode = NEXT_HOP;
    optionalBit = false;
    transitiveBit = true;
    length = 4;
    Ipv4Address value;
}
Constructor & Destructor Documentation
BgpUpdatePathAttributesNextHop() [1/2]
inet::bgp::BgpUpdatePathAttributesNextHop::BgpUpdatePathAttributesNextHop ()
BgpUpdatePathAttributesNextHop() [2/2]
inet::bgp::BgpUpdatePathAttributesNextHop::BgpUpdatePathAttributesNextHop (const BgpUpdatePathAttributesNextHop & other)
~BgpUpdatePathAttributesNextHop()
virtual inet::bgp::BgpUpdatePathAttributesNextHop::~BgpUpdatePathAttributesNextHop () virtual
Member Function Documentation
copy()
void inet::bgp::BgpUpdatePathAttributesNextHop::copy (const BgpUpdatePathAttributesNextHop & other) private
dup()
virtual BgpUpdatePathAttributesNextHop* inet::bgp::BgpUpdatePathAttributesNextHop::dup () const inline override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
 {return new BgpUpdatePathAttributesNextHop(*this);}
getValue()
virtual const ::inet::Ipv4Address& inet::bgp::BgpUpdatePathAttributesNextHop::getValue () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getValueForUpdate()
virtual ::inet::Ipv4Address& inet::bgp::BgpUpdatePathAttributesNextHop::getValueForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<BgpUpdatePathAttributesNextHop*>(this)->getValue());}
operator=()
BgpUpdatePathAttributesNextHop& inet::bgp::BgpUpdatePathAttributesNextHop::operator= (const BgpUpdatePathAttributesNextHop & other)
operator==()
bool inet::bgp::BgpUpdatePathAttributesNextHop::operator== (const BgpUpdatePathAttributesNextHop &) protected delete
parsimPack()
virtual void inet::bgp::BgpUpdatePathAttributesNextHop::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpUpdatePathAttributesNextHop::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimUnpacking().
setValue()
virtual void inet::bgp::BgpUpdatePathAttributesNextHop::setValue (const ::inet::Ipv4Address & value) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
value
::inet::Ipv4Address inet::bgp::BgpUpdatePathAttributesNextHop::value protected
The documentation for this class was generated from the following file:
BgpHeader_m.h