INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmMode Class Reference
inet::physicallayer::Ieee80211OfdmMode Class Reference
#include <Ieee80211OfdmMode.h>
Public Member Functions
Ieee80211OfdmMode (const char *name, const Ieee80211OfdmPreambleMode *preambleMode, const Ieee80211OfdmSignalMode *signalMode, const Ieee80211OfdmDataMode *dataMode, Hz channelSpacing, Hz bandwidth)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const Ieee80211OfdmPreambleMode * getPreambleMode () const override
virtual const Ieee80211OfdmSignalMode * getHeaderMode () const override
virtual const Ieee80211OfdmDataMode * getDataMode () const override
virtual const Ieee80211OfdmSignalMode * getSignalMode () const
virtual const simtime_t getDuration (b dataLength) const override
virtual const simtime_t getSlotTime () const override
virtual const simtime_t getSifsTime () const override
virtual const simtime_t getRifsTime () const override
virtual const simtime_t getCcaTime () const override
virtual const simtime_t getPhyRxStartDelay () const override
virtual const simtime_t getRxTxTurnaroundTime () const override
virtual const simtime_t getPreambleLength () const override
virtual const simtime_t getPlcpHeaderLength () const override
virtual int getMpduMaxLength () const override
Public Member Functions inherited from inet::physicallayer::Ieee80211ModeBase
Ieee80211ModeBase (const char *name)
virtual const char * getName () const override
Public Member Functions inherited from inet::physicallayer::IIeee80211Mode
IIeee80211PreambleMode * _getPreambleMode () const
IIeee80211HeaderMode * _getHeaderMode () const
IIeee80211DataMode * _getDataMode () const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing)
Hz getSubcarrierFrequencySpacing () const
const simtime_t getFFTTransformPeriod () const
const simtime_t getGIDuration () const
const simtime_t getSymbolInterval () const
const Hz getChannelSpacing () const
Protected Member Functions
virtual int getLegacyCwMin () const override
virtual int getLegacyCwMax () const override
Protected Attributes
const Ieee80211OfdmPreambleMode * preambleMode
const Ieee80211OfdmSignalMode * signalMode
const Ieee80211OfdmDataMode * dataMode
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Hz channelSpacing
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211OfdmMode()
inet::physicallayer::Ieee80211OfdmMode::Ieee80211OfdmMode (const char * name, const Ieee80211OfdmPreambleMode * preambleMode, const Ieee80211OfdmSignalMode * signalMode, const Ieee80211OfdmDataMode * dataMode, Hz channelSpacing, Hz bandwidth)
                                                                                                                                                                                                                        :
     Ieee80211ModeBase(name),
     Ieee80211OfdmTimingRelatedParametersBase(channelSpacing),
     preambleMode(preambleMode),
     signalMode(signalMode),
     dataMode(dataMode)
 {
 }
Member Function Documentation
getCcaTime()
const simtime_t inet::physicallayer::Ieee80211OfdmMode::getCcaTime () const override virtual
Implements inet::physicallayer::IIeee80211Mode.
 {
     // < 4, < 8, < 16
     if (channelSpacing == MHz(20))
         return 4E-6;
     else if (channelSpacing == MHz(10))
         return 8E-6;
     else if (channelSpacing == MHz(5))
         return 16E-6;
     else
         throw cRuntimeError("Unknown channel spacing = %f", channelSpacing.get());
 }
getDataMode()
virtual const Ieee80211OfdmDataMode* inet::physicallayer::Ieee80211OfdmMode::getDataMode () const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return dataMode; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldPacketModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createPacketModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::getBandwidth(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::~Ieee80211LayeredOfdmReceiver(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::~Ieee80211LayeredOfdmTransmitter().
getDuration()
virtual const simtime_t inet::physicallayer::Ieee80211OfdmMode::getDuration (b dataLength) const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
Reimplemented in inet::physicallayer::Ieee80211ErpOfdmMode.
 { return preambleMode->getDuration() + signalMode->getDuration() + dataMode->getDuration(dataLength); }
getHeaderMode()
virtual const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211OfdmMode::getHeaderMode () const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return signalMode; }
getLegacyCwMax()
virtual int inet::physicallayer::Ieee80211OfdmMode::getLegacyCwMax () const inline override protected virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return 1023; }
getLegacyCwMin()
virtual int inet::physicallayer::Ieee80211OfdmMode::getLegacyCwMin () const inline override protected virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return 15; }
getMpduMaxLength()
virtual int inet::physicallayer::Ieee80211OfdmMode::getMpduMaxLength () const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return 4095; }
getPhyRxStartDelay()
const simtime_t inet::physicallayer::Ieee80211OfdmMode::getPhyRxStartDelay () const override virtual
Implements inet::physicallayer::IIeee80211Mode.
 {
     if (channelSpacing == MHz(20))
         return 25E-6;
     else if (channelSpacing == MHz(10))
         return 49E-6;
     else if (channelSpacing == MHz(5))
         return 97E-6;
     else
         throw cRuntimeError("Unknown channel spacing = %f", channelSpacing.get());
 }
getPlcpHeaderLength()
virtual const simtime_t inet::physicallayer::Ieee80211OfdmMode::getPlcpHeaderLength () const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return signalMode->getDuration(); }
getPreambleLength()
virtual const simtime_t inet::physicallayer::Ieee80211OfdmMode::getPreambleLength () const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return preambleMode->getDuration(); }
getPreambleMode()
virtual const Ieee80211OfdmPreambleMode* inet::physicallayer::Ieee80211OfdmMode::getPreambleMode () const inline override virtual
Implements inet::physicallayer::IIeee80211Mode.
 { return preambleMode; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::~Ieee80211LayeredOfdmReceiver(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::~Ieee80211LayeredOfdmTransmitter().
getRifsTime()
const simtime_t inet::physicallayer::Ieee80211OfdmMode::getRifsTime () const override virtual
Implements inet::physicallayer::IIeee80211Mode.
Reimplemented in inet::physicallayer::Ieee80211ErpOfdmMode.
 {
     return -1;
 }
getRxTxTurnaroundTime()
const simtime_t inet::physicallayer::Ieee80211OfdmMode::getRxTxTurnaroundTime () const override virtual
Implements inet::physicallayer::IIeee80211Mode.
 {
     // TODO < 2;
     return -1;
 }
getSifsTime()
const simtime_t inet::physicallayer::Ieee80211OfdmMode::getSifsTime () const override virtual
Implements inet::physicallayer::IIeee80211Mode.
Reimplemented in inet::physicallayer::Ieee80211ErpOfdmMode.
 {
     if (channelSpacing == MHz(20))
         return 16E-6;
     else if (channelSpacing == MHz(10))
         return 32E-6;
     else if (channelSpacing == MHz(5))
         return 64E-6;
     else
         throw cRuntimeError("Unknown channel spacing = %f", channelSpacing.get());
 }
getSignalMode()
virtual const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211OfdmMode::getSignalMode () const inline virtual
 { return signalMode; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::~Ieee80211LayeredOfdmReceiver(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::~Ieee80211LayeredOfdmTransmitter().
getSlotTime()
const simtime_t inet::physicallayer::Ieee80211OfdmMode::getSlotTime () const override virtual
Implements inet::physicallayer::IIeee80211Mode.
Reimplemented in inet::physicallayer::Ieee80211ErpOfdmMode.
 {
     if (channelSpacing == MHz(20))
         return 9E-6;
     else if (channelSpacing == MHz(10))
         return 13E-6;
     else if (channelSpacing == MHz(5))
         return 21E-6;
     else
         throw cRuntimeError("Unknown channel spacing = %f", channelSpacing.get());
 }
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmMode::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::Ieee80211ErpOfdmMode.
 {
     stream << "Ieee80211OfdmMode";
     if (level <= PRINT_LEVEL_DEBUG)
         stream << EV_FIELD(preambleMode, printFieldToString(preambleMode, level + 1, evFlags))
                << EV_FIELD(signalMode, printFieldToString(signalMode, level + 1, evFlags));
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(dataMode, printFieldToString(dataMode, level + 1, evFlags));
     return stream;
 }
Member Data Documentation
dataMode
const Ieee80211OfdmDataMode* inet::physicallayer::Ieee80211OfdmMode::dataMode protected
Referenced by printToStream().
preambleMode
const Ieee80211OfdmPreambleMode* inet::physicallayer::Ieee80211OfdmMode::preambleMode protected
Referenced by printToStream().
signalMode
const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211OfdmMode::signalMode protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
Ieee80211OfdmMode.h
Ieee80211OfdmMode.cc