INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211CompliantBands Class Reference
inet::physicallayer::Ieee80211CompliantBands Class Reference
#include <Ieee80211Band.h>
Static Public Member Functions
static const IIeee80211Band * findBand (const char *name)
static const IIeee80211Band * getBand (const char *name)
Static Public Attributes
static const Ieee80211EnumeratedBand band2_4GHz
static const Ieee80211ArithmeticalBand band5GHz
static const Ieee80211ArithmeticalBand band5GHz20MHz
static const Ieee80211ArithmeticalBand band5GHz40MHz
static const Ieee80211ArithmeticalBand band5GHz80MHz
static const Ieee80211ArithmeticalBand band5GHz160MHz
static const Ieee80211ArithmeticalBand band5_9GHz
Static Protected Attributes
static const std::vector< const IIeee80211Band * > bands = { &band2_4GHz, &band5GHz, &band5GHz20MHz, &band5GHz40MHz, &band5GHz80MHz, &band5GHz160MHz, &band5_9GHz }
Member Function Documentation
findBand()
const IIeee80211Band * inet::physicallayer::Ieee80211CompliantBands::findBand (const char * name) static
 {
     for (auto& band : bands)
         if (!strcmp(band->getName(), name))
             return band;
     return nullptr;
 }
Referenced by getBand().
getBand()
const IIeee80211Band * inet::physicallayer::Ieee80211CompliantBands::getBand (const char * name) static
 {
     const IIeee80211Band *band = findBand(name);
     if (band == nullptr)
         throw cRuntimeError("Unknown 802.11 band: '%s'", name);
     else
         return band;
 }
Referenced by inet::physicallayer::Ieee80211ReceiverBase::initialize(), and inet::physicallayer::Ieee80211TransmitterBase::initialize().
Member Data Documentation
band2_4GHz
const Ieee80211EnumeratedBand inet::physicallayer::Ieee80211CompliantBands::band2_4GHz static
band5_9GHz
const Ieee80211ArithmeticalBand inet::physicallayer::Ieee80211CompliantBands::band5_9GHz static
Referenced by inet::Ieee80211MacProtocolDissector::computeLlcProtocol().
band5GHz
const Ieee80211ArithmeticalBand inet::physicallayer::Ieee80211CompliantBands::band5GHz static
band5GHz160MHz
const Ieee80211ArithmeticalBand inet::physicallayer::Ieee80211CompliantBands::band5GHz160MHz static
band5GHz20MHz
const Ieee80211ArithmeticalBand inet::physicallayer::Ieee80211CompliantBands::band5GHz20MHz static
band5GHz40MHz
const Ieee80211ArithmeticalBand inet::physicallayer::Ieee80211CompliantBands::band5GHz40MHz static
band5GHz80MHz
const Ieee80211ArithmeticalBand inet::physicallayer::Ieee80211CompliantBands::band5GHz80MHz static
bands
const std::vector< const IIeee80211Band * > inet::physicallayer::Ieee80211CompliantBands::bands = { &band2_4GHz, &band5GHz, &band5GHz20MHz, &band5GHz40MHz, &band5GHz80MHz, &band5GHz160MHz, &band5_9GHz } static protected
Referenced by findBand().
The documentation for this class was generated from the following files:
Ieee80211Band.h
Ieee80211Band.cc