INET Framework for OMNeT++/OMNEST: inet::HelloOption Class Reference
inet::HelloOption Class Reference
Class generated from inet/routing/pim/PimPacket.msg:78 by opp_msgtool.
#include <PimPacket_m.h>
Public Member Functions
HelloOption ()
HelloOption (const HelloOption &other)
virtual ~HelloOption ()
HelloOption & operator= (const HelloOption &other)
virtual HelloOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual PimHelloOptionType getType () const
virtual void setType (PimHelloOptionType type)
Protected Member Functions
bool operator== (const HelloOption &)=delete
Protected Attributes
PimHelloOptionType type = static_cast<inet::PimHelloOptionType>(-1)
Private Member Functions
void copy (const HelloOption &other)
Detailed Description
Class generated from inet/routing/pim/PimPacket.msg:78 by opp_msgtool.
class HelloOption extends cObject
{
    @packetData;
    PimHelloOptionType type;
}
Constructor & Destructor Documentation
HelloOption() [1/2]
inet::HelloOption::HelloOption ()
HelloOption() [2/2]
inet::HelloOption::HelloOption (const HelloOption & other)
~HelloOption()
virtual inet::HelloOption::~HelloOption () virtual
Member Function Documentation
copy()
void inet::HelloOption::copy (const HelloOption & other) private
dup()
virtual HelloOption* inet::HelloOption::dup () const inline override virtual
Reimplemented in inet::AddressListOption, inet::GenerationIdOption, inet::DrPriorityOption, inet::LanPruneDelayOption, and inet::HoldtimeOption.
 {return new HelloOption(*this);}
getType()
virtual PimHelloOptionType inet::HelloOption::getType () const virtual
Referenced by inet::PimBase::processHelloPacket().
operator=()
HelloOption& inet::HelloOption::operator= (const HelloOption & other)
operator==()
bool inet::HelloOption::operator== (const HelloOption &) protected delete
parsimPack()
virtual void inet::HelloOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::AddressListOption, inet::GenerationIdOption, inet::DrPriorityOption, inet::LanPruneDelayOption, and inet::HoldtimeOption.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::HelloOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::AddressListOption, inet::GenerationIdOption, inet::DrPriorityOption, inet::LanPruneDelayOption, and inet::HoldtimeOption.
Referenced by inet::doParsimUnpacking().
setType()
virtual void inet::HelloOption::setType (PimHelloOptionType type) virtual
Member Data Documentation
type
PimHelloOptionType inet::HelloOption::type = static_cast<inet::PimHelloOptionType>(-1) protected
The documentation for this class was generated from the following file:
PimPacket_m.h