INET Framework for OMNeT++/OMNEST: inet::physicallayer::DimensionalNoise Class Reference
inet::physicallayer::DimensionalNoise Class Reference
#include <DimensionalNoise.h>
Public Member Functions
DimensionalNoise (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth, const Ptr< const IFunction< WpHz, Domain< simsec, Hz >>> &power)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const Ptr< const IFunction< WpHz, Domain< simsec, Hz > > > & getPower () const
virtual W computeMinPower (simtime_t startTime, simtime_t endTime) const override
virtual W computeMaxPower (simtime_t startTime, simtime_t endTime) const override
Public Member Functions inherited from inet::physicallayer::NarrowbandNoiseBase
NarrowbandNoiseBase (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth)
virtual Hz getCenterFrequency () const
virtual Hz getBandwidth () const
Public Member Functions inherited from inet::physicallayer::NoiseBase
NoiseBase (simtime_t startTime, simtime_t endTime)
virtual const simtime_t getStartTime () const override
virtual const simtime_t getEndTime () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const Ptr< const IFunction< WpHz, Domain< simsec, Hz > > > power
Protected Attributes inherited from inet::physicallayer::NarrowbandNoiseBase
const Hz centerFrequency
const Hz bandwidth
Protected Attributes inherited from inet::physicallayer::NoiseBase
const simtime_t startTime
const simtime_t endTime
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
DimensionalNoise()
inet::physicallayer::DimensionalNoise::DimensionalNoise (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth, const Ptr< const IFunction< WpHz, Domain< simsec, Hz >>> & power)
                                                                                                                                                                         :
     NarrowbandNoiseBase(startTime, endTime, centerFrequency, bandwidth),
     power(power)
 {
 }
Member Function Documentation
computeMaxPower()
W inet::physicallayer::DimensionalNoise::computeMaxPower (simtime_t startTime, simtime_t endTime) const override virtual
Implements inet::physicallayer::NarrowbandNoiseBase.
 {
     Point<simsec> startPoint{ simsec(startTime) };
     Point<simsec> endPoint{ simsec(endTime) };
     W maxPower = integrate<WpHz, Domain<simsec, Hz>, 0b10, W, Domain<simsec>>(power)->getMax(Interval<simsec>(startPoint, endPoint, 0b1, 0b1, 0b0));
     EV_DEBUG << "Computing maximum noise power" << EV_FIELD(startPoint) << EV_FIELD(endPoint) << EV_FIELD(maxPower) << endl;
     return maxPower;
 }
computeMinPower()
W inet::physicallayer::DimensionalNoise::computeMinPower (simtime_t startTime, simtime_t endTime) const override virtual
Implements inet::physicallayer::NarrowbandNoiseBase.
 {
     Point<simsec> startPoint{ simsec(startTime) };
     Point<simsec> endPoint{ simsec(endTime) };
     W minPower = integrate<WpHz, Domain<simsec, Hz>, 0b10, W, Domain<simsec>>(power)->getMin(Interval<simsec>(startPoint, endPoint, 0b1, 0b1, 0b0));
     EV_DEBUG << "Computing minimum noise power" << EV_FIELD(startPoint) << EV_FIELD(endPoint) << EV_FIELD(minPower) << endl;
     return minPower;
 }
getPower()
virtual const Ptr<const IFunction<WpHz, Domain<simsec, Hz> > >& inet::physicallayer::DimensionalNoise::getPower () const inline virtual
 { return power; }
Referenced by inet::physicallayer::DimensionalSnir::computeMax(), inet::physicallayer::DimensionalSnir::computeMean(), inet::physicallayer::DimensionalSnir::computeMin(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), and inet::physicallayer::Ieee802154UwbIrReceiver::integrateWindow().
printToStream()
std::ostream & inet::physicallayer::DimensionalNoise::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::NarrowbandNoiseBase.
 {
     stream << "DimensionalNoise";
     if (level <= PRINT_LEVEL_DEBUG)
         stream << EV_FIELD(powerMax, power->getMax())
                << EV_FIELD(powerMin, power->getMin());
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(power);
     return NarrowbandNoiseBase::printToStream(stream, level);
 }
Member Data Documentation
power
const Ptr<const IFunction<WpHz, Domain<simsec, Hz> > > inet::physicallayer::DimensionalNoise::power protected
Referenced by computeMaxPower(), computeMinPower(), and printToStream().
The documentation for this class was generated from the following files:
DimensionalNoise.h
DimensionalNoise.cc