INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211VhtSignalMode Class Reference
inet::physicallayer::Ieee80211VhtSignalMode Class Reference
#include <Ieee80211VhtMode.h>
Public Member Functions
Ieee80211VhtSignalMode (unsigned int modulationAndCodingScheme, const Ieee80211OfdmModulation *modulation, const Ieee80211VhtCode *code, const Hz bandwidth, GuardIntervalType guardIntervalType)
Ieee80211VhtSignalMode (unsigned int modulationAndCodingScheme, const Ieee80211OfdmModulation *modulation, const Ieee80211ConvolutionalCode *convolutionalCode, const Hz bandwidth, GuardIntervalType guardIntervalType)
virtual ~Ieee80211VhtSignalMode ()
virtual b getMCSLength () const
virtual b getCBWLength () const
virtual b getHTLengthLength () const
virtual b getSmoothingLength () const
virtual b getNotSoundingLength () const
virtual b getReservedLength () const
virtual b getAggregationLength () const
virtual b getSTBCLength () const
virtual b getFECCodingLength () const
virtual b getShortGILength () const
virtual b getNumOfExtensionSpatialStreamsLength () const
virtual b getCRCLength () const
virtual b getTailBitsLength () const
virtual unsigned int getSTBC () const
virtual const simtime_t getHTSIGDuration () const
virtual unsigned int getModulationAndCodingScheme () const
virtual const simtime_t getDuration () const override
virtual b getLength () const override
virtual bps getNetBitrate () const override
virtual bps getGrossBitrate () const override
virtual const Ieee80211OfdmModulation * getModulation () const override
virtual const Ieee80211VhtCode * getCode () const
virtual Ptr< Ieee80211PhyHeader > createHeader () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211VhtModeBase
Ieee80211VhtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
virtual int getNumberOfDataSubcarriers () const
virtual int getNumberOfPilotSubcarriers () const
virtual int getNumberOfTotalSubcarriers () const
virtual GuardIntervalType getGuardIntervalType () const
virtual int getNumberOfSpatialStreams () const
virtual unsigned int getMcsIndex () const
virtual Hz getBandwidth () const
Public Member Functions inherited from inet::physicallayer::Ieee80211HtTimingRelatedParametersBase
const simtime_t getDFTPeriod () const
const simtime_t getGIDuration () const
const simtime_t getShortGIDuration () const
const simtime_t getSymbolInterval () const
const simtime_t getShortGISymbolInterval () const
Protected Member Functions
virtual bps computeGrossBitrate () const override
virtual bps computeNetBitrate () const override
Protected Attributes
const Ieee80211OfdmModulation * modulation
const Ieee80211VhtCode * code
Protected Attributes inherited from inet::physicallayer::Ieee80211VhtModeBase
const Hz bandwidth
const GuardIntervalType guardIntervalType
const unsigned int mcsIndex
const unsigned int numberOfSpatialStreams
bps netBitrate
bps grossBitrate
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Types inherited from inet::physicallayer::Ieee80211VhtModeBase
enum GuardIntervalType { HT_GUARD_INTERVAL_SHORT, HT_GUARD_INTERVAL_LONG }
Constructor & Destructor Documentation
Ieee80211VhtSignalMode() [1/2]
inet::physicallayer::Ieee80211VhtSignalMode::Ieee80211VhtSignalMode (unsigned int modulationAndCodingScheme, const Ieee80211OfdmModulation * modulation, const Ieee80211VhtCode * code, const Hz bandwidth, GuardIntervalType guardIntervalType)
                                                                                                                                                                                                                        :
     Ieee80211VhtModeBase(modulationAndCodingScheme, 1, bandwidth, guardIntervalType),
     modulation(modulation),
     code(code)
 {
 }
Ieee80211VhtSignalMode() [2/2]
inet::physicallayer::Ieee80211VhtSignalMode::Ieee80211VhtSignalMode (unsigned int modulationAndCodingScheme, const Ieee80211OfdmModulation * modulation, const Ieee80211ConvolutionalCode * convolutionalCode, const Hz bandwidth, GuardIntervalType guardIntervalType)
                                                                                                                                                                                                                                               :
     Ieee80211VhtModeBase(modulationAndCodingScheme, 1, bandwidth, guardIntervalType),
     modulation(modulation),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, modulation, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, bandwidth, false))
 {
 }
~Ieee80211VhtSignalMode()
inet::physicallayer::Ieee80211VhtSignalMode::~Ieee80211VhtSignalMode () virtual
 {
     delete code;
 }
Member Function Documentation
computeGrossBitrate()
bps inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate () const override protected virtual
Implements inet::physicallayer::Ieee80211VhtModeBase.
 {
     unsigned int numberOfCodedBitsPerSymbol = modulation->getSubcarrierModulation()->getCodeWordSize() * getNumberOfDataSubcarriers();
     if (guardIntervalType == HT_GUARD_INTERVAL_LONG)
         return bps(numberOfCodedBitsPerSymbol / getSymbolInterval());
     else if (guardIntervalType == HT_GUARD_INTERVAL_SHORT)
         return bps(numberOfCodedBitsPerSymbol / getShortGISymbolInterval());
     else
         throw cRuntimeError("Unknown guard interval type");
 }
Referenced by computeNetBitrate().
computeNetBitrate()
bps inet::physicallayer::Ieee80211VhtSignalMode::computeNetBitrate () const override protected virtual
Implements inet::physicallayer::Ieee80211VhtModeBase.
 {
     return computeGrossBitrate() * code->getForwardErrorCorrection()->getCodeRate();
 }
createHeader()
virtual Ptr<Ieee80211PhyHeader> inet::physicallayer::Ieee80211VhtSignalMode::createHeader () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return makeShared<Ieee80211HtPhyHeader>(); }
getAggregationLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getAggregationLength () const inline virtual
 { return b(1); }
Referenced by getLength().
getCBWLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getCBWLength () const inline virtual
 { return b(1); }
Referenced by getLength().
getCode()
virtual const Ieee80211VhtCode* inet::physicallayer::Ieee80211VhtSignalMode::getCode () const inline virtual
 { return code; }
getCRCLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getCRCLength () const inline virtual
 { return b(8); }
Referenced by getLength().
getDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtSignalMode::getDuration () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return getHTSIGDuration(); }
getFECCodingLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getFECCodingLength () const inline virtual
 { return b(1); }
Referenced by getLength().
getGrossBitrate()
virtual bps inet::physicallayer::Ieee80211VhtSignalMode::getGrossBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211VhtModeBase.
 { return Ieee80211VhtModeBase::getGrossBitrate(); }
getHTLengthLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getHTLengthLength () const inline virtual
 { return b(16); }
Referenced by getLength().
getHTSIGDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtSignalMode::getHTSIGDuration () const inline virtual
 { return 2 * getSymbolInterval(); } // HT-SIG
getLength()
b inet::physicallayer::Ieee80211VhtSignalMode::getLength () const override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 {
     return getMCSLength() +
            getCBWLength() +
            getHTLengthLength() +
            getSmoothingLength() +
            getNotSoundingLength() +
            getReservedLength() +
            getAggregationLength() +
            getSTBCLength() +
            getFECCodingLength() +
            getShortGILength() +
            getNumOfExtensionSpatialStreamsLength() +
            getCRCLength() +
            getTailBitsLength();
 }
getMCSLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getMCSLength () const inline virtual
 { return b(9); }
Referenced by getLength().
getModulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211VhtSignalMode::getModulation () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return modulation; }
getModulationAndCodingScheme()
virtual unsigned int inet::physicallayer::Ieee80211VhtSignalMode::getModulationAndCodingScheme () const inline virtual
 { return mcsIndex; }
getNetBitrate()
virtual bps inet::physicallayer::Ieee80211VhtSignalMode::getNetBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211VhtModeBase.
 { return Ieee80211VhtModeBase::getNetBitrate(); }
getNotSoundingLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getNotSoundingLength () const inline virtual
 { return b(1); }
Referenced by getLength().
getNumOfExtensionSpatialStreamsLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getNumOfExtensionSpatialStreamsLength () const inline virtual
 { return b(2); }
Referenced by getLength().
getReservedLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getReservedLength () const inline virtual
 { return b(1); }
Referenced by getLength().
getShortGILength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getShortGILength () const inline virtual
 { return b(1); }
Referenced by getLength().
getSmoothingLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getSmoothingLength () const inline virtual
 { return b(1); }
Referenced by getLength().
getSTBC()
virtual unsigned int inet::physicallayer::Ieee80211VhtSignalMode::getSTBC () const inline virtual
 { return 0; } // Limitation: We assume that STBC is not used
Referenced by inet::physicallayer::Ieee80211VhtPreambleMode::computeNumberOfSpaceTimeStreams().
getSTBCLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getSTBCLength () const inline virtual
 { return b(2); }
Referenced by getLength().
getTailBitsLength()
virtual b inet::physicallayer::Ieee80211VhtSignalMode::getTailBitsLength () const inline virtual
 { return b(6); }
Referenced by getLength().
Member Data Documentation
code
const Ieee80211VhtCode* inet::physicallayer::Ieee80211VhtSignalMode::code protected
Referenced by computeNetBitrate(), and ~Ieee80211VhtSignalMode().
modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211VhtSignalMode::modulation protected
Referenced by computeGrossBitrate().
The documentation for this class was generated from the following files:
Ieee80211VhtMode.h
Ieee80211VhtMode.cc