INET Framework for OMNeT++/OMNEST: inet::visualizer::LinkBreakVisualizerBase Class Reference
inet::visualizer::LinkBreakVisualizerBase Class Reference abstract
#include <LinkBreakVisualizerBase.h>
Classes
class LinkBreakVisualization
Parameters
bool displayLinkBreaks = false
NetworkNodeFilter nodeFilter
InterfaceFilter interfaceFilter
PacketFilter packetFilter
const char * icon = nullptr
double iconTintAmount = NaN
cFigure::Color iconTintColor
const char * fadeOutMode = nullptr
double fadeOutTime = NaN
double fadeOutAnimationSpeed = NaN
std::map< std::pair< int, int >, const LinkBreakVisualization * > linkBreakVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void refreshDisplay () const override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual const LinkBreakVisualization * createLinkBreakVisualization (cModule *transmitter, cModule *receiver) const =0
virtual void addLinkBreakVisualization (const LinkBreakVisualization *linkBreakVisualization)
virtual void removeLinkBreakVisualization (const LinkBreakVisualization *linkBreakVisualization)
virtual void removeAllLinkBreakVisualizations ()
virtual void setAlpha (const LinkBreakVisualization *linkBreakVisualization, double alpha) const =0
virtual cModule * findNode (MacAddress address)
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addLinkBreakVisualization()
void inet::visualizer::LinkBreakVisualizerBase::addLinkBreakVisualization (const LinkBreakVisualization * linkBreakVisualization) protected virtual
Reimplemented in inet::visualizer::LinkBreakCanvasVisualizer, and inet::visualizer::LinkBreakOsgVisualizer.
 {
     auto key = std::pair<int, int>(linkBreakVisualization->transmitterModuleId, linkBreakVisualization->receiverModuleId);
     linkBreakVisualizations[key] = linkBreakVisualization;
 }
Referenced by inet::visualizer::LinkBreakOsgVisualizer::addLinkBreakVisualization(), inet::visualizer::LinkBreakCanvasVisualizer::addLinkBreakVisualization(), and receiveSignal().
createLinkBreakVisualization()
virtual const LinkBreakVisualization* inet::visualizer::LinkBreakVisualizerBase::createLinkBreakVisualization (cModule * transmitter, cModule * receiver) const protected pure virtual
Implemented in inet::visualizer::LinkBreakCanvasVisualizer, and inet::visualizer::LinkBreakOsgVisualizer.
Referenced by receiveSignal().
findNode()
cModule * inet::visualizer::LinkBreakVisualizerBase::findNode (MacAddress address) protected virtual
 {
     L3AddressResolver addressResolver;
     for (cModule::SubmoduleIterator it(visualizationSubjectModule); !it.end(); it++) {
         auto networkNode = *it;
         if (isNetworkNode(networkNode)) {
             auto interfaceTable = addressResolver.findInterfaceTableOf(networkNode);
             for (int i = 0; i < interfaceTable->getNumInterfaces(); i++)
                 if (interfaceTable->getInterface(i)->getMacAddress() == address)
                     return networkNode;
         }
     }
     return nullptr;
 }
Referenced by receiveSignal().
handleParameterChange()
void inet::visualizer::LinkBreakVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "nodeFilter"))
             nodeFilter.setPattern(par("nodeFilter"));
         else if (!strcmp(name, "interfaceFilter"))
             interfaceFilter.setPattern(par("interfaceFilter"));
         else if (!strcmp(name, "packetFilter"))
             packetFilter.setExpression(par("packetFilter").objectValue());
         removeAllLinkBreakVisualizations();
     }
 }
initialize()
void inet::visualizer::LinkBreakVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::LinkBreakCanvasVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayLinkBreaks = par("displayLinkBreaks");
         nodeFilter.setPattern(par("nodeFilter"));
         interfaceFilter.setPattern(par("interfaceFilter"));
         packetFilter.setExpression(par("packetFilter").objectValue());
         icon = par("icon");
         iconTintAmount = par("iconTintAmount");
         if (iconTintAmount != 0)
             iconTintColor = cFigure::Color(par("iconTintColor"));
         fadeOutMode = par("fadeOutMode");
         fadeOutTime = par("fadeOutTime");
         fadeOutAnimationSpeed = par("fadeOutAnimationSpeed");
         if (displayLinkBreaks)
             subscribe();
     }
 }
Referenced by inet::visualizer::LinkBreakCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::LinkBreakVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayLinkBreaks) {
         unsubscribe();
         removeAllLinkBreakVisualizations();
     }
 }
receiveSignal()
void inet::visualizer::LinkBreakVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == linkBrokenSignal) {
         MacAddress transmitterAddress;
         MacAddress receiverAddress;
         // TODO revive
 //        if (auto frame = dynamic_cast<IMACFrame *>(object)) {
 //            transmitterAddress = frame->getTransmitterAddress();
 //            receiverAddress = frame->getReceiverAddress();
 //        }
 #ifdef INET_WITH_IEEE80211
         if (auto frame = dynamic_cast<ieee80211::Ieee80211TwoAddressHeader *>(object)) {
             transmitterAddress = frame->getTransmitterAddress();
             receiverAddress = frame->getReceiverAddress();
         }
 #endif // INET_WITH_IEEE80211
         auto transmitter = findNode(transmitterAddress);
         auto receiver = findNode(receiverAddress);
         if (nodeFilter.matches(transmitter) && nodeFilter.matches(receiver)) {
             auto key = std::pair<int, int>(transmitter->getId(), receiver->getId());
             auto it = linkBreakVisualizations.find(key);
             if (it == linkBreakVisualizations.end())
                 addLinkBreakVisualization(createLinkBreakVisualization(transmitter, receiver));
             else {
                 auto linkBreakVisualization = it->second;
                 linkBreakVisualization->linkBreakAnimationPosition = AnimationPosition();
             }
         }
     }
     else
         throw cRuntimeError("Unknown signal");
 }
refreshDisplay()
void inet::visualizer::LinkBreakVisualizerBase::refreshDisplay () const override protected virtual
Reimplemented in inet::visualizer::LinkBreakCanvasVisualizer, and inet::visualizer::LinkBreakOsgVisualizer.
 {
     AnimationPosition currentAnimationPosition;
     std::vector<const LinkBreakVisualization *> removedLinkBreakVisualizations;
     for (auto it : linkBreakVisualizations) {
         auto linkBreakVisualization = it.second;
         double delta;
         if (!strcmp(fadeOutMode, "simulationTime"))
             delta = (currentAnimationPosition.getSimulationTime() - linkBreakVisualization->linkBreakAnimationPosition.getSimulationTime()).dbl();
         else if (!strcmp(fadeOutMode, "animationTime"))
             delta = currentAnimationPosition.getAnimationTime() - linkBreakVisualization->linkBreakAnimationPosition.getAnimationTime();
         else if (!strcmp(fadeOutMode, "realTime"))
             delta = currentAnimationPosition.getRealTime() - linkBreakVisualization->linkBreakAnimationPosition.getRealTime();
         else
             throw cRuntimeError("Unknown fadeOutMode: %s", fadeOutMode);
         if (delta > fadeOutTime)
             removedLinkBreakVisualizations.push_back(linkBreakVisualization);
         else
             setAlpha(linkBreakVisualization, 1 - delta / fadeOutTime);
     }
     for (auto linkBreakVisualization : removedLinkBreakVisualizations) {
         const_cast<LinkBreakVisualizerBase *>(this)->removeLinkBreakVisualization(linkBreakVisualization);
         delete linkBreakVisualization;
     }
 }
Referenced by inet::visualizer::LinkBreakOsgVisualizer::refreshDisplay(), and inet::visualizer::LinkBreakCanvasVisualizer::refreshDisplay().
removeAllLinkBreakVisualizations()
void inet::visualizer::LinkBreakVisualizerBase::removeAllLinkBreakVisualizations () protected virtual
 {
     std::vector<const LinkBreakVisualization *> removedLinkBreakVisualizations;
     for (auto it : linkBreakVisualizations)
         removedLinkBreakVisualizations.push_back(it.second);
     for (auto it : removedLinkBreakVisualizations) {
         removeLinkBreakVisualization(it);
         delete it;
     }
 }
Referenced by handleParameterChange(), and preDelete().
removeLinkBreakVisualization()
void inet::visualizer::LinkBreakVisualizerBase::removeLinkBreakVisualization (const LinkBreakVisualization * linkBreakVisualization) protected virtual
Reimplemented in inet::visualizer::LinkBreakCanvasVisualizer, and inet::visualizer::LinkBreakOsgVisualizer.
 {
     auto key = std::pair<int, int>(linkBreakVisualization->transmitterModuleId, linkBreakVisualization->receiverModuleId);
     auto it = linkBreakVisualizations.find(key);
     linkBreakVisualizations.erase(it);
 }
Referenced by refreshDisplay(), removeAllLinkBreakVisualizations(), inet::visualizer::LinkBreakOsgVisualizer::removeLinkBreakVisualization(), and inet::visualizer::LinkBreakCanvasVisualizer::removeLinkBreakVisualization().
setAlpha()
virtual void inet::visualizer::LinkBreakVisualizerBase::setAlpha (const LinkBreakVisualization * linkBreakVisualization, double alpha) const protected pure virtual
Implemented in inet::visualizer::LinkBreakCanvasVisualizer, and inet::visualizer::LinkBreakOsgVisualizer.
Referenced by refreshDisplay().
subscribe()
void inet::visualizer::LinkBreakVisualizerBase::subscribe () protected virtual
 {
     visualizationSubjectModule->subscribe(linkBrokenSignal, this);
 }
Referenced by initialize().
unsubscribe()
void inet::visualizer::LinkBreakVisualizerBase::unsubscribe () protected virtual
 {
     // NOTE: lookup the module again because it may have been deleted first
     auto visualizationSubjectModule = findModuleFromPar<cModule>(par("visualizationSubjectModule"), this);
     if (visualizationSubjectModule != nullptr)
         visualizationSubjectModule->unsubscribe(linkBrokenSignal, this);
 }
Referenced by preDelete().
Member Data Documentation
displayLinkBreaks
bool inet::visualizer::LinkBreakVisualizerBase::displayLinkBreaks = false protected
Referenced by initialize(), and preDelete().
fadeOutAnimationSpeed
double inet::visualizer::LinkBreakVisualizerBase::fadeOutAnimationSpeed = NaN protected
Referenced by initialize(), inet::visualizer::LinkBreakOsgVisualizer::refreshDisplay(), and inet::visualizer::LinkBreakCanvasVisualizer::refreshDisplay().
fadeOutMode
const char* inet::visualizer::LinkBreakVisualizerBase::fadeOutMode = nullptr protected
Referenced by initialize(), and refreshDisplay().
fadeOutTime
double inet::visualizer::LinkBreakVisualizerBase::fadeOutTime = NaN protected
Referenced by initialize(), and refreshDisplay().
icon
const char* inet::visualizer::LinkBreakVisualizerBase::icon = nullptr protected
Referenced by inet::visualizer::LinkBreakOsgVisualizer::createLinkBreakVisualization(), inet::visualizer::LinkBreakCanvasVisualizer::createLinkBreakVisualization(), and initialize().
iconTintAmount
double inet::visualizer::LinkBreakVisualizerBase::iconTintAmount = NaN protected
Referenced by inet::visualizer::LinkBreakCanvasVisualizer::createLinkBreakVisualization(), and initialize().
iconTintColor
cFigure::Color inet::visualizer::LinkBreakVisualizerBase::iconTintColor protected
Referenced by inet::visualizer::LinkBreakOsgVisualizer::createLinkBreakVisualization(), inet::visualizer::LinkBreakCanvasVisualizer::createLinkBreakVisualization(), and initialize().
interfaceFilter
InterfaceFilter inet::visualizer::LinkBreakVisualizerBase::interfaceFilter protected
Referenced by handleParameterChange(), and initialize().
linkBreakVisualizations
std::map<std::pair<int, int>, const LinkBreakVisualization *> inet::visualizer::LinkBreakVisualizerBase::linkBreakVisualizations protected
Referenced by addLinkBreakVisualization(), receiveSignal(), inet::visualizer::LinkBreakOsgVisualizer::refreshDisplay(), inet::visualizer::LinkBreakCanvasVisualizer::refreshDisplay(), refreshDisplay(), removeAllLinkBreakVisualizations(), and removeLinkBreakVisualization().
nodeFilter
NetworkNodeFilter inet::visualizer::LinkBreakVisualizerBase::nodeFilter protected
Referenced by handleParameterChange(), initialize(), and receiveSignal().
packetFilter
PacketFilter inet::visualizer::LinkBreakVisualizerBase::packetFilter protected
Referenced by handleParameterChange(), and initialize().
The documentation for this class was generated from the following files:
LinkBreakVisualizerBase.h
LinkBreakVisualizerBase.cc