INET Framework for OMNeT++/OMNEST: inet::tcp::Sack Class Reference
inet::tcp::Sack Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:87 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
Sack ()
Sack (const Sack &other)
virtual ~Sack ()
Sack & operator= (const Sack &other)
virtual Sack * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
Sack (unsigned int start_par, unsigned int end_par)
virtual bool empty () const
virtual bool contains (const Sack &other) const
virtual void clear ()
virtual void setSegment (unsigned int start_par, unsigned int end_par)
virtual std::string str () const override
Public Member Functions inherited from inet::tcp::SackItem
SackItem ()
SackItem (const SackItem &other)
virtual ~SackItem ()
SackItem & operator= (const SackItem &other)
virtual unsigned int getStart () const
virtual void setStart (unsigned int start)
virtual unsigned int getEnd () const
virtual void setEnd (unsigned int end)
Protected Member Functions
bool operator== (const Sack &)=delete
Protected Member Functions inherited from inet::tcp::SackItem
bool operator== (const SackItem &)=delete
Private Member Functions
void copy (const Sack &other)
Additional Inherited Members
Protected Attributes inherited from inet::tcp::SackItem
unsigned int start = 0
unsigned int end = 0
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:87 by opp_msgtool.
class Sack extends SackItem
{
}
Constructor & Destructor Documentation
Sack() [1/3]
inet::tcp::Sack::Sack ()
Sack() [2/3]
inet::tcp::Sack::Sack (const Sack & other)
~Sack()
virtual inet::tcp::Sack::~Sack () virtual
Sack() [3/3]
inet::tcp::Sack::Sack (unsigned int start_par, unsigned int end_par) inline
 { setSegment(start_par, end_par); }
Member Function Documentation
clear()
void inet::tcp::Sack::clear () virtual
 {
     start = end = 0;
 }
contains()
bool inet::tcp::Sack::contains (const Sack & other) const virtual
 {
     return seqLE(start, other.start) && seqLE(other.end, end);
 }
Referenced by inet::tcp::TcpConnection::processSACKOption().
copy()
void inet::tcp::Sack::copy (const Sack & other) private
dup()
virtual Sack* inet::tcp::Sack::dup () const inline override virtual
Reimplemented from inet::tcp::SackItem.
 {return new Sack(*this);}
empty()
bool inet::tcp::Sack::empty () const virtual
 {
     return start == 0 && end == 0;
 }
operator=()
Sack& inet::tcp::Sack::operator= (const Sack & other)
operator==()
bool inet::tcp::Sack::operator== (const Sack &) protected delete
parsimPack()
virtual void inet::tcp::Sack::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::tcp::SackItem.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::Sack::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::tcp::SackItem.
Referenced by inet::tcp::doParsimUnpacking().
setSegment()
void inet::tcp::Sack::setSegment (unsigned int start_par, unsigned int end_par) virtual
 {
     setStart(start_par);
     setEnd(end_par);
 }
str()
std::string inet::tcp::Sack::str () const override virtual
 {
     std::stringstream out;
     out << "[" << start << ".." << end << ")";
     return out.str();
 }
Referenced by inet::tcp::TcpConnection::addSacks(), and inet::tcp::TcpConnection::processSACKOption().
The documentation for this class was generated from the following files:
TcpHeader_m.h
TcpHeader.cc