INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2SummaryLsa Class Reference
inet::ospfv2::Ospfv2SummaryLsa Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:169 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2SummaryLsa ()
Ospfv2SummaryLsa (const Ospfv2SummaryLsa &other)
virtual ~Ospfv2SummaryLsa ()
Ospfv2SummaryLsa & operator= (const Ospfv2SummaryLsa &other)
virtual Ospfv2SummaryLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getNetworkMask () const
virtual ::inet::Ipv4Address & getNetworkMaskForUpdate ()
virtual void setNetworkMask (const ::inet::Ipv4Address &networkMask)
virtual unsigned long getRouteCost () const
virtual void setRouteCost (unsigned long routeCost)
virtual void setTosDataArraySize (size_t size)
virtual size_t getTosDataArraySize () const
virtual const Ospfv2TosData & getTosData (size_t k) const
virtual Ospfv2TosData & getTosDataForUpdate (size_t k)
virtual void setTosData (size_t k, const Ospfv2TosData &tosData)
virtual void insertTosData (size_t k, const Ospfv2TosData &tosData)
void insertTosData (const Ospfv2TosData &tosData)
virtual void appendTosData (const Ospfv2TosData &tosData)
virtual void eraseTosData (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv2SummaryLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes
::inet::Ipv4Address networkMask
unsigned long routeCost = 1
Ospfv2TosData * tosData = nullptr
size_t tosData_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Private Member Functions
void copy (const Ospfv2SummaryLsa &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:169 by opp_msgtool.
//
// Represents an OSPF Summary LSA
//
class Ospfv2SummaryLsa extends Ospfv2Lsa
{
    // header.lsType = SUMMARYLSA_NETWORKS_TYPE;
    Ipv4Address networkMask;
    unsigned long routeCost = 1;
    Ospfv2TosData tosData[];  // 1 element required, count of tosData not stored, calculate it from length of LSA
}
Constructor & Destructor Documentation
Ospfv2SummaryLsa() [1/2]
inet::ospfv2::Ospfv2SummaryLsa::Ospfv2SummaryLsa ()
Ospfv2SummaryLsa() [2/2]
inet::ospfv2::Ospfv2SummaryLsa::Ospfv2SummaryLsa (const Ospfv2SummaryLsa & other)
~Ospfv2SummaryLsa()
virtual inet::ospfv2::Ospfv2SummaryLsa::~Ospfv2SummaryLsa () virtual
Member Function Documentation
appendTosData()
virtual void inet::ospfv2::Ospfv2SummaryLsa::appendTosData (const Ospfv2TosData & tosData) virtual
copy()
void inet::ospfv2::Ospfv2SummaryLsa::copy (const Ospfv2SummaryLsa & other) private
dup()
virtual Ospfv2SummaryLsa* inet::ospfv2::Ospfv2SummaryLsa::dup () const inline override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
 {return new Ospfv2SummaryLsa(*this);}
eraseTosData()
virtual void inet::ospfv2::Ospfv2SummaryLsa::eraseTosData (size_t k) virtual
getNetworkMask()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2SummaryLsa::getNetworkMask () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::Ospfv2Area::printSummaryLsa(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), and inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa().
getNetworkMaskForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2SummaryLsa::getNetworkMaskForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2SummaryLsa*>(this)->getNetworkMask());}
getRouteCost()
virtual unsigned long inet::ospfv2::Ospfv2SummaryLsa::getRouteCost () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::Ospfv2Area::printSummaryLsa(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), and inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa().
getTosData()
virtual const Ospfv2TosData& inet::ospfv2::Ospfv2SummaryLsa::getTosData (size_t k) const virtual
Referenced by inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::operator<<(), and inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa().
getTosDataArraySize()
virtual size_t inet::ospfv2::Ospfv2SummaryLsa::getTosDataArraySize () const virtual
Referenced by inet::ospfv2::calculateLsaSize(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::operator<<(), and inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa().
getTosDataForUpdate()
virtual Ospfv2TosData& inet::ospfv2::Ospfv2SummaryLsa::getTosDataForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv2TosData&>(const_cast<Ospfv2SummaryLsa*>(this)->getTosData(k));}
insertTosData() [1/2]
void inet::ospfv2::Ospfv2SummaryLsa::insertTosData (const Ospfv2TosData & tosData) inline
 {appendTosData(tosData);}
insertTosData() [2/2]
virtual void inet::ospfv2::Ospfv2SummaryLsa::insertTosData (size_t k, const Ospfv2TosData & tosData) virtual
operator=()
Ospfv2SummaryLsa& inet::ospfv2::Ospfv2SummaryLsa::operator= (const Ospfv2SummaryLsa & other)
operator==()
bool inet::ospfv2::Ospfv2SummaryLsa::operator== (const Ospfv2SummaryLsa &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2SummaryLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2SummaryLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimUnpacking().
setNetworkMask()
virtual void inet::ospfv2::Ospfv2SummaryLsa::setNetworkMask (const ::inet::Ipv4Address & networkMask) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub().
setRouteCost()
virtual void inet::ospfv2::Ospfv2SummaryLsa::setRouteCost (unsigned long routeCost) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub().
setTosData()
virtual void inet::ospfv2::Ospfv2SummaryLsa::setTosData (size_t k, const Ospfv2TosData & tosData) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa().
setTosDataArraySize()
virtual void inet::ospfv2::Ospfv2SummaryLsa::setTosDataArraySize (size_t size) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub().
Member Data Documentation
networkMask
::inet::Ipv4Address inet::ospfv2::Ospfv2SummaryLsa::networkMask protected
routeCost
unsigned long inet::ospfv2::Ospfv2SummaryLsa::routeCost = 1 protected
tosData
Ospfv2TosData* inet::ospfv2::Ospfv2SummaryLsa::tosData = nullptr protected
tosData_arraysize
size_t inet::ospfv2::Ospfv2SummaryLsa::tosData_arraysize = 0 protected
Referenced by inet::ospfv2::SummaryLsa::differsFrom().
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h