INET Framework for OMNeT++/OMNEST: inet::PimNeighbor Class Reference
inet::PimNeighbor Class Reference
Class holding information about a neighboring PIM router.
#include <PimNeighborTable.h>
Public Member Functions
PimNeighbor (NetworkInterface *ie, Ipv4Address address, int version)
virtual ~PimNeighbor ()
virtual std::string str () const override
int getInterfaceId () const
NetworkInterface * getInterfacePtr () const
Ipv4Address getAddress () const
int getVersion () const
unsigned int getGenerationId () const
long getDRPriority () const
cMessage * getLivenessTimer () const
void setGenerationId (unsigned int genId)
void setDRPriority (long priority)
Protected Member Functions
void changed ()
Protected Attributes
PimNeighborTable * nt
NetworkInterface * ie
Ipv4Address address
int version
unsigned int generationId
long drPriority
cMessage * livenessTimer
Friends
class PimNeighborTable
Detailed Description
Class holding information about a neighboring PIM router.
Routers are identified by the link to which they are connected and their address.
Currently only the version of the routers are stored. TODO add fields for options received in Hello Messages (RFC 3973 4.7.5, RFC 4601 4.9.2).
Constructor & Destructor Documentation
PimNeighbor()
inet::PimNeighbor::PimNeighbor (NetworkInterface * ie, Ipv4Address address, int version)
     : nt(nullptr), ie(ie), address(address), version(version), generationId(0), drPriority(-1L)
 {
     ASSERT(ie);
     livenessTimer = new cMessage("NeighborLivenessTimer", PimNeighborTable::NeighborLivenessTimer);
     livenessTimer->setContextPointer(this);
 }
~PimNeighbor()
inet::PimNeighbor::~PimNeighbor () virtual
 {
     delete livenessTimer;
 }
Member Function Documentation
changed()
void inet::PimNeighbor::changed () protected
 {
     if (nt)
         nt->emit(pimNeighborChangedSignal, this);
 }
getAddress()
Ipv4Address inet::PimNeighbor::getAddress () const inline
 { return address; }
Referenced by inet::PimNeighborTable::addNeighbor(), inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::PimNeighborTable::processLivenessTimer(), and inet::PimSm::updateDesignatedRouterAddress().
getDRPriority()
long inet::PimNeighbor::getDRPriority () const inline
 { return drPriority; }
Referenced by inet::PimSm::updateDesignatedRouterAddress().
getGenerationId()
unsigned int inet::PimNeighbor::getGenerationId () const inline
 { return generationId; }
getInterfaceId()
int inet::PimNeighbor::getInterfaceId () const inline
 { return ie->getInterfaceId(); }
Referenced by inet::PimNeighborTable::addNeighbor(), and inet::PimNeighborTable::deleteNeighbor().
getInterfacePtr()
NetworkInterface* inet::PimNeighbor::getInterfacePtr () const inline
 { return ie; }
Referenced by inet::PimSm::receiveSignal().
getLivenessTimer()
cMessage* inet::PimNeighbor::getLivenessTimer () const inline
 { return livenessTimer; }
Referenced by inet::PimNeighborTable::addNeighbor(), inet::PimNeighborTable::deleteNeighbor(), and inet::PimNeighborTable::restartLivenessTimer().
getVersion()
int inet::PimNeighbor::getVersion () const inline
 { return version; }
setDRPriority()
void inet::PimNeighbor::setDRPriority (long priority) inline
 { if (drPriority != priority) { drPriority = priority; changed(); } }
Referenced by inet::PimBase::processHelloPacket().
setGenerationId()
void inet::PimNeighbor::setGenerationId (unsigned int genId) inline
 { if (generationId != genId) { generationId = genId; changed(); } }
Referenced by inet::PimBase::processHelloPacket().
str()
std::string inet::PimNeighbor::str () const override virtual
 {
     std::stringstream out;
     out << "PimNeighbor addr=" << address << ", iface=" << ie->getInterfaceName() << ", v=" << version << ", priority=" << this->drPriority << "}";
     return out.str();
 }
Referenced by inet::PimNeighborTable::addNeighbor().
Friends And Related Function Documentation
PimNeighborTable
friend class PimNeighborTable friend
Member Data Documentation
address
Ipv4Address inet::PimNeighbor::address protected
Referenced by str().
drPriority
long inet::PimNeighbor::drPriority protected
Referenced by str().
generationId
unsigned int inet::PimNeighbor::generationId protected
ie
NetworkInterface* inet::PimNeighbor::ie protected
Referenced by PimNeighbor(), and str().
livenessTimer
cMessage* inet::PimNeighbor::livenessTimer protected
Referenced by PimNeighbor(), and ~PimNeighbor().
nt
PimNeighborTable* inet::PimNeighbor::nt protected
Referenced by inet::PimNeighborTable::addNeighbor(), changed(), and inet::PimNeighborTable::deleteNeighbor().
version
int inet::PimNeighbor::version protected
Referenced by str().
The documentation for this class was generated from the following files:
PimNeighborTable.h
PimNeighborTable.cc