INET Framework for OMNeT++/OMNEST: inet::Ipv4SocketBindCommand Class Reference
inet::Ipv4SocketBindCommand Class Reference
Class generated from inet/networklayer/contract/ipv4/Ipv4SocketCommand.msg:31 by opp_msgtool.
#include <Ipv4SocketCommand_m.h>
Public Member Functions
Ipv4SocketBindCommand ()
Ipv4SocketBindCommand (const Ipv4SocketBindCommand &other)
virtual ~Ipv4SocketBindCommand ()
Ipv4SocketBindCommand & operator= (const Ipv4SocketBindCommand &other)
virtual Ipv4SocketBindCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Protocol * getProtocol () const
virtual void setProtocol (const Protocol *protocol)
virtual const Ipv4Address & getLocalAddress () const
virtual Ipv4Address & getLocalAddressForUpdate ()
virtual void setLocalAddress (const Ipv4Address &localAddress)
Public Member Functions inherited from inet::Ipv4SocketCommandBase
Ipv4SocketCommandBase ()
Ipv4SocketCommandBase (const Ipv4SocketCommandBase &other)
virtual ~Ipv4SocketCommandBase ()
Ipv4SocketCommandBase & operator= (const Ipv4SocketCommandBase &other)
Protected Member Functions
bool operator== (const Ipv4SocketBindCommand &)=delete
Protected Member Functions inherited from inet::Ipv4SocketCommandBase
bool operator== (const Ipv4SocketCommandBase &)=delete
Protected Attributes
const Protocol * protocol = nullptr
Ipv4Address localAddress
Private Member Functions
void copy (const Ipv4SocketBindCommand &other)
Detailed Description
Class generated from inet/networklayer/contract/ipv4/Ipv4SocketCommand.msg:31 by opp_msgtool.
class Ipv4SocketBindCommand extends Ipv4SocketCommandBase
{
    const Protocol *protocol;
    Ipv4Address localAddress;
}
Constructor & Destructor Documentation
Ipv4SocketBindCommand() [1/2]
inet::Ipv4SocketBindCommand::Ipv4SocketBindCommand ()
Ipv4SocketBindCommand() [2/2]
inet::Ipv4SocketBindCommand::Ipv4SocketBindCommand (const Ipv4SocketBindCommand & other)
~Ipv4SocketBindCommand()
virtual inet::Ipv4SocketBindCommand::~Ipv4SocketBindCommand () virtual
Member Function Documentation
copy()
void inet::Ipv4SocketBindCommand::copy (const Ipv4SocketBindCommand & other) private
dup()
virtual Ipv4SocketBindCommand* inet::Ipv4SocketBindCommand::dup () const inline override virtual
Reimplemented from inet::Ipv4SocketCommandBase.
 {return new Ipv4SocketBindCommand(*this);}
getLocalAddress()
virtual const Ipv4Address& inet::Ipv4SocketBindCommand::getLocalAddress () const virtual
getLocalAddressForUpdate()
virtual Ipv4Address& inet::Ipv4SocketBindCommand::getLocalAddressForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<Ipv4SocketBindCommand*>(this)->getLocalAddress());}
getProtocol()
virtual const Protocol* inet::Ipv4SocketBindCommand::getProtocol () const virtual
operator=()
Ipv4SocketBindCommand& inet::Ipv4SocketBindCommand::operator= (const Ipv4SocketBindCommand & other)
operator==()
bool inet::Ipv4SocketBindCommand::operator== (const Ipv4SocketBindCommand &) protected delete
parsimPack()
virtual void inet::Ipv4SocketBindCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::Ipv4SocketCommandBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv4SocketBindCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::Ipv4SocketCommandBase.
Referenced by inet::doParsimUnpacking().
setLocalAddress()
virtual void inet::Ipv4SocketBindCommand::setLocalAddress (const Ipv4Address & localAddress) virtual
Referenced by inet::Ipv4Socket::bind().
setProtocol()
virtual void inet::Ipv4SocketBindCommand::setProtocol (const Protocol * protocol) virtual
Referenced by inet::Ipv4Socket::bind().
Member Data Documentation
localAddress
Ipv4Address inet::Ipv4SocketBindCommand::localAddress protected
protocol
const Protocol* inet::Ipv4SocketBindCommand::protocol = nullptr protected
The documentation for this class was generated from the following file:
Ipv4SocketCommand_m.h