INET Framework for OMNeT++/OMNEST: inet::SimpleVoipReceiver::TalkspurtInfo Class Reference
inet::SimpleVoipReceiver::TalkspurtInfo Class Reference
Public Types
enum Status { EMPTY, ACTIVE, FINISHED }
Public Member Functions
TalkspurtInfo ()
void startTalkspurt (const SimpleVoipPacket *pk)
void finishTalkspurt ()
bool checkPacket (const SimpleVoipPacket *pk)
void addPacket (const SimpleVoipPacket *pk)
bool isActive ()
Public Attributes
Status status = EMPTY
unsigned int talkspurtID = -1
unsigned int talkspurtNumPackets = 0
simtime_t voiceDuration
PacketsVector packets
Member Enumeration Documentation
Status
enum inet::SimpleVoipReceiver::TalkspurtInfo::Status
Enumerator
EMPTY
ACTIVE
FINISHED
                     {
             EMPTY,
             ACTIVE,
             FINISHED
         };
Constructor & Destructor Documentation
TalkspurtInfo()
inet::SimpleVoipReceiver::TalkspurtInfo::TalkspurtInfo () inline
 {}
Member Function Documentation
addPacket()
void inet::SimpleVoipReceiver::TalkspurtInfo::addPacket (const SimpleVoipPacket * pk)
 {
     VoipPacketInfo packet;
     packet.packetID = pk->getPacketID();
     packet.creationTime = pk->getVoipTimestamp();
     packet.arrivalTime = simTime();
     packets.push_back(packet);
 }
Referenced by inet::SimpleVoipReceiver::socketDataArrived(), and startTalkspurt().
checkPacket()
bool inet::SimpleVoipReceiver::TalkspurtInfo::checkPacket (const SimpleVoipPacket * pk)
 {
     return talkspurtID == pk->getTalkspurtID()
            && talkspurtNumPackets == pk->getTalkspurtNumPackets()
            && voiceDuration == pk->getVoiceDuration();
 }
Referenced by inet::SimpleVoipReceiver::socketDataArrived().
finishTalkspurt()
void inet::SimpleVoipReceiver::TalkspurtInfo::finishTalkspurt () inline
 { status = FINISHED; packets.clear(); }
Referenced by inet::SimpleVoipReceiver::evaluateTalkspurt().
isActive()
bool inet::SimpleVoipReceiver::TalkspurtInfo::isActive () inline
 { return status == ACTIVE; }
Referenced by inet::SimpleVoipReceiver::evaluateTalkspurt(), inet::SimpleVoipReceiver::finish(), and inet::SimpleVoipReceiver::socketDataArrived().
startTalkspurt()
void inet::SimpleVoipReceiver::TalkspurtInfo::startTalkspurt (const SimpleVoipPacket * pk)
 {
     status = ACTIVE;
     talkspurtID = pk->getTalkspurtID();
     talkspurtNumPackets = pk->getTalkspurtNumPackets();
     voiceDuration = pk->getVoiceDuration();
     packets.clear();
     packets.reserve(talkspurtNumPackets * 1.1);
     addPacket(pk);
 }
Referenced by inet::SimpleVoipReceiver::startTalkspurt().
Member Data Documentation
packets
PacketsVector inet::SimpleVoipReceiver::TalkspurtInfo::packets
Referenced by inet::SimpleVoipReceiver::evaluateTalkspurt(), and startTalkspurt().
status
Status inet::SimpleVoipReceiver::TalkspurtInfo::status = EMPTY
Referenced by inet::SimpleVoipReceiver::socketDataArrived(), and startTalkspurt().
talkspurtID
unsigned int inet::SimpleVoipReceiver::TalkspurtInfo::talkspurtID = -1
Referenced by inet::SimpleVoipReceiver::evaluateTalkspurt(), inet::SimpleVoipReceiver::initialize(), inet::SimpleVoipReceiver::socketDataArrived(), and startTalkspurt().
talkspurtNumPackets
unsigned int inet::SimpleVoipReceiver::TalkspurtInfo::talkspurtNumPackets = 0
Referenced by inet::SimpleVoipReceiver::evaluateTalkspurt(), startTalkspurt(), and inet::SimpleVoipReceiver::startTalkspurt().
voiceDuration
simtime_t inet::SimpleVoipReceiver::TalkspurtInfo::voiceDuration
Referenced by inet::SimpleVoipReceiver::evaluateTalkspurt(), startTalkspurt(), and inet::SimpleVoipReceiver::startTalkspurt().
The documentation for this class was generated from the following files:
SimpleVoipReceiver.h
SimpleVoipReceiver.cc