INET Framework for OMNeT++/OMNEST: inet::EigrpMsgReq_Base Class Reference
inet::EigrpMsgReq_Base Class Reference
Class generated from inet/routing/eigrp/messages/EigrpMessage.msg:262 by opp_msgtool.
#include <EigrpMessage_m.h>
Public Member Functions
virtual ~EigrpMsgReq_Base ()
virtual EigrpMsgReq_Base * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int8_t getOpcode () const
virtual void setOpcode (int8_t opcode)
virtual bool getGoodbyeMsg () const
virtual void setGoodbyeMsg (bool goodbyeMsg)
virtual bool getInit () const
virtual void setInit (bool init)
virtual bool getCr () const
virtual void setCr (bool cr)
virtual bool getRs () const
virtual void setRs (bool rs)
virtual bool getEot () const
virtual void setEot (bool eot)
virtual int getDestNeighbor () const
virtual void setDestNeighbor (int destNeighbor)
virtual int getDestInterface () const
virtual void setDestInterface (int destInterface)
virtual uint32_t getSeqNumber () const
virtual void setSeqNumber (uint32_t seqNumber)
virtual uint32_t getAckNumber () const
virtual void setAckNumber (uint32_t ackNumber)
virtual int getNumOfAck () const
virtual void setNumOfAck (int numOfAck)
virtual void setRoutesArraySize (size_t size)
virtual size_t getRoutesArraySize () const
virtual const EigrpMsgRoute & getRoutes (size_t k) const
virtual EigrpMsgRoute & getRoutesForUpdate (size_t k)
virtual void setRoutes (size_t k, const EigrpMsgRoute &routes)
virtual void insertRoutes (size_t k, const EigrpMsgRoute &routes)
void insertRoutes (const EigrpMsgRoute &routes)
virtual void appendRoutes (const EigrpMsgRoute &routes)
virtual void eraseRoutes (size_t k)
Protected Member Functions
bool operator== (const EigrpMsgReq_Base &)=delete
EigrpMsgReq_Base (const char *name=nullptr, short kind=0)
EigrpMsgReq_Base (const EigrpMsgReq_Base &other)
EigrpMsgReq_Base & operator= (const EigrpMsgReq_Base &other)
Protected Attributes
int8_t opcode = 0
bool goodbyeMsg = false
bool init = false
bool cr = false
bool rs = false
bool eot = false
int destNeighbor = 0
int destInterface = 0
uint32_t seqNumber = 0
uint32_t ackNumber = 0
int numOfAck = 0
EigrpMsgRoute * routes = nullptr
size_t routes_arraysize = 0
Private Member Functions
void copy (const EigrpMsgReq_Base &other)
Detailed Description
Class generated from inet/routing/eigrp/messages/EigrpMessage.msg:262 by opp_msgtool.
// Message request
message EigrpMsgReq
{
    @customize(true);
    int8_t opcode;              // Type of message
    bool goodbyeMsg = false;    // Message is Hello goodbye
    // flags
    bool init;                  // Initialization - establishment of neighborship
    bool cr;                    // Conditionally Received
    bool rs;                    // Reset
    bool eot;                   // End of table
    int destNeighbor;           // ID of neighbor that is destination of message
    int destInterface;          // ID of destination interface
    uint32_t seqNumber;         // Sequence number for reliable transmission
    uint32_t ackNumber;         // Ack number for reliable transmission
    int numOfAck;               // Number of acknowledges
    EigrpMsgRoute routes[];
}
EigrpMsgReq_Base is only useful if it gets subclassed, and EigrpMsgReq is derived from it. The minimum code to be written for EigrpMsgReq is the following:
class INET_API EigrpMsgReq : public EigrpMsgReq_Base
{
  private:
    void copy(const EigrpMsgReq& other) { ... }
  public:
    EigrpMsgReq(const char *name=nullptr, short kind=0) : EigrpMsgReq_Base(name,kind) {}
    EigrpMsgReq(const EigrpMsgReq& other) : EigrpMsgReq_Base(other) {copy(other);}
    EigrpMsgReq& operator=(const EigrpMsgReq& other) {if (this==&other) return *this; EigrpMsgReq_Base::operator=(other); copy(other); return *this;}
    virtual EigrpMsgReq *dup() const override {return new EigrpMsgReq(*this);}
    // ADD CODE HERE to redefine and implement pure virtual functions from EigrpMsgReq_Base
};
The following should go into a .cc (.cpp) file:
Register_Class(EigrpMsgReq)
Constructor & Destructor Documentation
EigrpMsgReq_Base() [1/2]
inet::EigrpMsgReq_Base::EigrpMsgReq_Base (const char * name = nullptr, short kind = 0) protected
EigrpMsgReq_Base() [2/2]
inet::EigrpMsgReq_Base::EigrpMsgReq_Base (const EigrpMsgReq_Base & other) protected
~EigrpMsgReq_Base()
virtual inet::EigrpMsgReq_Base::~EigrpMsgReq_Base () virtual
Member Function Documentation
appendRoutes()
virtual void inet::EigrpMsgReq_Base::appendRoutes (const EigrpMsgRoute & routes) virtual
copy()
void inet::EigrpMsgReq_Base::copy (const EigrpMsgReq_Base & other) private
dup()
virtual EigrpMsgReq_Base* inet::EigrpMsgReq_Base::dup () const inline override virtual
Reimplemented in inet::EigrpMsgReq.
 {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class EigrpMsgReq");}
eraseRoutes()
virtual void inet::EigrpMsgReq_Base::eraseRoutes (size_t k) virtual
getAckNumber()
virtual uint32_t inet::EigrpMsgReq_Base::getAckNumber () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::createAckPacket(), inet::eigrp::EigrpIpv6Pdm::createAckPacket(), inet::eigrp::EigrpIpv4Pdm::createQueryPacket(), inet::eigrp::EigrpIpv6Pdm::createQueryPacket(), inet::eigrp::EigrpIpv4Pdm::createReplyPacket(), inet::eigrp::EigrpIpv6Pdm::createReplyPacket(), inet::eigrp::EigrpIpv4Pdm::createUpdatePacket(), inet::eigrp::EigrpIpv6Pdm::createUpdatePacket(), inet::eigrp::EigrpRequestQueue::printInfo(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), inet::eigrp::EigrpIpv6Pdm::printSentMsg(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), and inet::eigrp::EigrpRtpT< Ipv4Address >::scheduleNewMsg().
getCr()
virtual bool inet::EigrpMsgReq_Base::getCr () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::addMessageHeader(), inet::eigrp::EigrpIpv6Pdm::addMessageHeader(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), and inet::eigrp::EigrpIpv6Pdm::printSentMsg().
getDestInterface()
virtual int inet::EigrpMsgReq_Base::getDestInterface () const virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::discardMsg(), inet::eigrp::operator<<(), inet::eigrp::EigrpRequestQueue::printInfo(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), inet::eigrp::EigrpIpv6Pdm::printSentMsg(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), inet::eigrp::EigrpRtpT< Ipv4Address >::scheduleNewMsg(), inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendUnrelMsg().
getDestNeighbor()
virtual int inet::EigrpMsgReq_Base::getDestNeighbor () const virtual
Referenced by inet::eigrp::operator<<(), inet::eigrp::EigrpRequestQueue::printInfo(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
getEot()
virtual bool inet::EigrpMsgReq_Base::getEot () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::addMessageHeader(), inet::eigrp::EigrpIpv6Pdm::addMessageHeader(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), and inet::eigrp::EigrpIpv6Pdm::printSentMsg().
getGoodbyeMsg()
virtual bool inet::EigrpMsgReq_Base::getGoodbyeMsg () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::printSentMsg(), inet::eigrp::EigrpIpv6Pdm::printSentMsg(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), and inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp().
getInit()
virtual bool inet::EigrpMsgReq_Base::getInit () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::addMessageHeader(), inet::eigrp::EigrpIpv6Pdm::addMessageHeader(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), and inet::eigrp::EigrpIpv6Pdm::printSentMsg().
getNumOfAck()
virtual int inet::EigrpMsgReq_Base::getNumOfAck () const virtual
Referenced by inet::eigrp::operator<<(), inet::eigrp::EigrpRequestQueue::printInfo(), inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader(), and inet::eigrp::EigrpRtpT< Ipv4Address >::scheduleNextMsg().
getOpcode()
virtual int8_t inet::EigrpMsgReq_Base::getOpcode () const virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::discardMsg(), inet::EigrpMsgReq::isMsgReliable(), inet::eigrp::operator<<(), inet::eigrp::EigrpRequestQueue::printInfo(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), inet::eigrp::EigrpIpv6Pdm::printSentMsg(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), and inet::eigrp::EigrpRtpT< Ipv4Address >::scheduleNewMsg().
getRoutes()
virtual const EigrpMsgRoute& inet::EigrpMsgReq_Base::getRoutes (size_t k) const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv6Pdm::addRoutesToMsg(), inet::EigrpMsgReq::findMsgRoute(), inet::eigrp::EigrpIpv4Pdm::unlockRoutes(), and inet::eigrp::EigrpIpv6Pdm::unlockRoutes().
getRoutesArraySize()
virtual size_t inet::EigrpMsgReq_Base::getRoutesArraySize () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv6Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv4Pdm::createQueryPacket(), inet::eigrp::EigrpIpv6Pdm::createQueryPacket(), inet::eigrp::EigrpIpv4Pdm::createReplyPacket(), inet::eigrp::EigrpIpv6Pdm::createReplyPacket(), inet::eigrp::EigrpIpv4Pdm::createUpdatePacket(), inet::eigrp::EigrpIpv6Pdm::createUpdatePacket(), inet::EigrpMsgReq::findMsgRoute(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv4Pdm::pushMsgRouteToQueue(), inet::eigrp::EigrpIpv6Pdm::pushMsgRouteToQueue(), inet::eigrp::EigrpIpv4Pdm::unlockRoutes(), and inet::eigrp::EigrpIpv6Pdm::unlockRoutes().
getRoutesForUpdate()
virtual EigrpMsgRoute& inet::EigrpMsgReq_Base::getRoutesForUpdate (size_t k) inline virtual
 { return const_cast<EigrpMsgRoute&>(const_cast<EigrpMsgReq_Base*>(this)->getRoutes(k));}
Referenced by inet::eigrp::EigrpIpv4Pdm::pushMsgRouteToQueue(), and inet::eigrp::EigrpIpv6Pdm::pushMsgRouteToQueue().
getRs()
virtual bool inet::EigrpMsgReq_Base::getRs () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::addMessageHeader(), inet::eigrp::EigrpIpv6Pdm::addMessageHeader(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), and inet::eigrp::EigrpIpv6Pdm::printSentMsg().
getSeqNumber()
virtual uint32_t inet::EigrpMsgReq_Base::getSeqNumber () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::createQueryPacket(), inet::eigrp::EigrpIpv6Pdm::createQueryPacket(), inet::eigrp::EigrpIpv4Pdm::createReplyPacket(), inet::eigrp::EigrpIpv6Pdm::createReplyPacket(), inet::eigrp::EigrpIpv4Pdm::createUpdatePacket(), inet::eigrp::EigrpIpv6Pdm::createUpdatePacket(), inet::eigrp::operator<<(), inet::eigrp::EigrpRequestQueue::printInfo(), inet::eigrp::EigrpIpv4Pdm::printSentMsg(), inet::eigrp::EigrpIpv6Pdm::printSentMsg(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
insertRoutes() [1/2]
void inet::EigrpMsgReq_Base::insertRoutes (const EigrpMsgRoute & routes) inline
 {appendRoutes(routes);}
insertRoutes() [2/2]
virtual void inet::EigrpMsgReq_Base::insertRoutes (size_t k, const EigrpMsgRoute & routes) virtual
operator=()
EigrpMsgReq_Base& inet::EigrpMsgReq_Base::operator= (const EigrpMsgReq_Base & other) protected
Referenced by inet::EigrpMsgReq::operator=().
operator==()
bool inet::EigrpMsgReq_Base::operator== (const EigrpMsgReq_Base &) protected delete
parsimPack()
virtual void inet::EigrpMsgReq_Base::parsimPack (omnetpp::cCommBuffer * b) const override virtual
parsimUnpack()
virtual void inet::EigrpMsgReq_Base::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
setAckNumber()
virtual void inet::EigrpMsgReq_Base::setAckNumber (uint32_t ackNumber) virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::acknowledgeMsg(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
setCr()
virtual void inet::EigrpMsgReq_Base::setCr (bool cr) virtual
setDestInterface()
virtual void inet::EigrpMsgReq_Base::setDestInterface (int destInterface) virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::acknowledgeMsg(), inet::eigrp::EigrpIpv4Pdm::createMsgReq(), and inet::eigrp::EigrpIpv6Pdm::createMsgReq().
setDestNeighbor()
virtual void inet::EigrpMsgReq_Base::setDestNeighbor (int destNeighbor) virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::acknowledgeMsg(), inet::eigrp::EigrpIpv4Pdm::createMsgReq(), and inet::eigrp::EigrpIpv6Pdm::createMsgReq().
setEot()
virtual void inet::EigrpMsgReq_Base::setEot (bool eot) virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), and inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths().
setGoodbyeMsg()
virtual void inet::EigrpMsgReq_Base::setGoodbyeMsg (bool goodbyeMsg) virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), inet::eigrp::EigrpIpv6Pdm::processHelloPacket(), inet::eigrp::EigrpIpv4Pdm::processTimer(), and inet::eigrp::EigrpIpv6Pdm::processTimer().
setInit()
virtual void inet::EigrpMsgReq_Base::setInit (bool init) virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), and inet::eigrp::EigrpIpv6Pdm::processNewNeighbor().
setNumOfAck()
virtual void inet::EigrpMsgReq_Base::setNumOfAck (int numOfAck) virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
setOpcode()
virtual void inet::EigrpMsgReq_Base::setOpcode (int8_t opcode) virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::acknowledgeMsg(), inet::eigrp::EigrpIpv4Pdm::createMsgReq(), and inet::eigrp::EigrpIpv6Pdm::createMsgReq().
setRoutes()
virtual void inet::EigrpMsgReq_Base::setRoutes (size_t k, const EigrpMsgRoute & routes) virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::pushMsgRouteToQueue(), inet::eigrp::EigrpIpv6Pdm::pushMsgRouteToQueue(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), and inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths().
setRoutesArraySize()
virtual void inet::EigrpMsgReq_Base::setRoutesArraySize (size_t size) virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::pushMsgRouteToQueue(), inet::eigrp::EigrpIpv6Pdm::pushMsgRouteToQueue(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), and inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths().
setRs()
virtual void inet::EigrpMsgReq_Base::setRs (bool rs) virtual
setSeqNumber()
virtual void inet::EigrpMsgReq_Base::setSeqNumber (uint32_t seqNumber) virtual
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
Member Data Documentation
ackNumber
uint32_t inet::EigrpMsgReq_Base::ackNumber = 0 protected
cr
bool inet::EigrpMsgReq_Base::cr = false protected
destInterface
int inet::EigrpMsgReq_Base::destInterface = 0 protected
destNeighbor
int inet::EigrpMsgReq_Base::destNeighbor = 0 protected
eot
bool inet::EigrpMsgReq_Base::eot = false protected
goodbyeMsg
bool inet::EigrpMsgReq_Base::goodbyeMsg = false protected
init
bool inet::EigrpMsgReq_Base::init = false protected
numOfAck
int inet::EigrpMsgReq_Base::numOfAck = 0 protected
opcode
int8_t inet::EigrpMsgReq_Base::opcode = 0 protected
routes
EigrpMsgRoute* inet::EigrpMsgReq_Base::routes = nullptr protected
routes_arraysize
size_t inet::EigrpMsgReq_Base::routes_arraysize = 0 protected
rs
bool inet::EigrpMsgReq_Base::rs = false protected
seqNumber
uint32_t inet::EigrpMsgReq_Base::seqNumber = 0 protected
The documentation for this class was generated from the following file:
EigrpMessage_m.h