INET Framework for OMNeT++/OMNEST: inet::sctp::SctpIncomingSsnResetRequestParameter_Base Class Reference
inet::sctp::SctpIncomingSsnResetRequestParameter_Base Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:259 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
virtual ~SctpIncomingSsnResetRequestParameter_Base ()
virtual SctpIncomingSsnResetRequestParameter_Base * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSrReqSn () const
virtual void setSrReqSn (uint32_t srReqSn)
virtual void setStreamNumbersArraySize (size_t size)
virtual size_t getStreamNumbersArraySize () const
virtual uint16_t getStreamNumbers (size_t k) const
virtual void setStreamNumbers (size_t k, uint16_t streamNumbers)
virtual void insertStreamNumbers (size_t k, uint16_t streamNumbers)
void insertStreamNumbers (uint16_t streamNumbers)
virtual void appendStreamNumbers (uint16_t streamNumbers)
virtual void eraseStreamNumbers (size_t k)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpIncomingSsnResetRequestParameter_Base &)=delete
SctpIncomingSsnResetRequestParameter_Base (const char *name=nullptr)
SctpIncomingSsnResetRequestParameter_Base (const SctpIncomingSsnResetRequestParameter_Base &other)
SctpIncomingSsnResetRequestParameter_Base & operator= (const SctpIncomingSsnResetRequestParameter_Base &other)
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t srReqSn = 0
uint16_t * streamNumbers = nullptr
size_t streamNumbers_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpIncomingSsnResetRequestParameter_Base &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:259 by opp_msgtool.
class SctpIncomingSsnResetRequestParameter extends SctpParameter
{
    @customize;
    uint32_t srReqSn; //Stream Reset Request Sequence Number
    uint16_t streamNumbers[];
}
SctpIncomingSsnResetRequestParameter_Base is only useful if it gets subclassed, and SctpIncomingSsnResetRequestParameter is derived from it. The minimum code to be written for SctpIncomingSsnResetRequestParameter is the following:
class INET_API SctpIncomingSsnResetRequestParameter : public SctpIncomingSsnResetRequestParameter_Base
{
  private:
    void copy(const SctpIncomingSsnResetRequestParameter& other) { ... }
  public:
    SctpIncomingSsnResetRequestParameter(const char *name=nullptr) : SctpIncomingSsnResetRequestParameter_Base(name) {}
    SctpIncomingSsnResetRequestParameter(const SctpIncomingSsnResetRequestParameter& other) : SctpIncomingSsnResetRequestParameter_Base(other) {copy(other);}
    SctpIncomingSsnResetRequestParameter& operator=(const SctpIncomingSsnResetRequestParameter& other) {if (this==&other) return *this; SctpIncomingSsnResetRequestParameter_Base::operator=(other); copy(other); return *this;}
    virtual SctpIncomingSsnResetRequestParameter *dup() const override {return new SctpIncomingSsnResetRequestParameter(*this);}
    // ADD CODE HERE to redefine and implement pure virtual functions from SctpIncomingSsnResetRequestParameter_Base
};
The following should go into a .cc (.cpp) file:
Register_Class(SctpIncomingSsnResetRequestParameter)
Constructor & Destructor Documentation
SctpIncomingSsnResetRequestParameter_Base() [1/2]
inet::sctp::SctpIncomingSsnResetRequestParameter_Base::SctpIncomingSsnResetRequestParameter_Base (const char * name = nullptr) protected
SctpIncomingSsnResetRequestParameter_Base() [2/2]
inet::sctp::SctpIncomingSsnResetRequestParameter_Base::SctpIncomingSsnResetRequestParameter_Base (const SctpIncomingSsnResetRequestParameter_Base & other) protected
~SctpIncomingSsnResetRequestParameter_Base()
virtual inet::sctp::SctpIncomingSsnResetRequestParameter_Base::~SctpIncomingSsnResetRequestParameter_Base () virtual
Member Function Documentation
appendStreamNumbers()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::appendStreamNumbers (uint16_t streamNumbers) virtual
copy()
void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::copy (const SctpIncomingSsnResetRequestParameter_Base & other) private
dup()
virtual SctpIncomingSsnResetRequestParameter_Base* inet::sctp::SctpIncomingSsnResetRequestParameter_Base::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
Reimplemented in inet::sctp::SctpIncomingSsnResetRequestParameter.
 {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class SctpIncomingSsnResetRequestParameter");}
eraseStreamNumbers()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::eraseStreamNumbers (size_t k) virtual
getSrReqSn()
virtual uint32_t inet::sctp::SctpIncomingSsnResetRequestParameter_Base::getSrReqSn () const virtual
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::copy(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processIncomingResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), and inet::sctp::SctpHeaderSerializer::serialize().
getStreamNumbers()
virtual uint16_t inet::sctp::SctpIncomingSsnResetRequestParameter_Base::getStreamNumbers (size_t k) const virtual
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::copy(), inet::sctp::SctpAssociation::makeIncomingStreamResetParameter(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processIncomingResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), and inet::sctp::SctpHeaderSerializer::serialize().
getStreamNumbersArraySize()
virtual size_t inet::sctp::SctpIncomingSsnResetRequestParameter_Base::getStreamNumbersArraySize () const virtual
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::copy(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processIncomingResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), and inet::sctp::SctpHeaderSerializer::serialize().
insertStreamNumbers() [1/2]
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::insertStreamNumbers (size_t k, uint16_t streamNumbers) virtual
insertStreamNumbers() [2/2]
void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::insertStreamNumbers (uint16_t streamNumbers) inline
 {appendStreamNumbers(streamNumbers);}
operator=()
SctpIncomingSsnResetRequestParameter_Base& inet::sctp::SctpIncomingSsnResetRequestParameter_Base::operator= (const SctpIncomingSsnResetRequestParameter_Base & other) protected
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::operator=().
operator==()
bool inet::sctp::SctpIncomingSsnResetRequestParameter_Base::operator== (const SctpIncomingSsnResetRequestParameter_Base &) protected delete
parsimPack()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
parsimUnpack()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
setSrReqSn()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::setSrReqSn (uint32_t srReqSn) virtual
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::copy(), inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::makeIncomingStreamResetParameter().
setStreamNumbers()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::setStreamNumbers (size_t k, uint16_t streamNumbers) virtual
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::copy(), inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::makeIncomingStreamResetParameter().
setStreamNumbersArraySize()
virtual void inet::sctp::SctpIncomingSsnResetRequestParameter_Base::setStreamNumbersArraySize (size_t size) virtual
Referenced by inet::sctp::SctpIncomingSsnResetRequestParameter::copy(), inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::makeIncomingStreamResetParameter().
Member Data Documentation
srReqSn
uint32_t inet::sctp::SctpIncomingSsnResetRequestParameter_Base::srReqSn = 0 protected
streamNumbers
uint16_t* inet::sctp::SctpIncomingSsnResetRequestParameter_Base::streamNumbers = nullptr protected
streamNumbers_arraysize
size_t inet::sctp::SctpIncomingSsnResetRequestParameter_Base::streamNumbers_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h