INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_DeauthenticateRequest Class Reference
inet::ieee80211::Ieee80211Prim_DeauthenticateRequest Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:156 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_DeauthenticateRequest ()
Ieee80211Prim_DeauthenticateRequest (const Ieee80211Prim_DeauthenticateRequest &other)
virtual ~Ieee80211Prim_DeauthenticateRequest ()
Ieee80211Prim_DeauthenticateRequest & operator= (const Ieee80211Prim_DeauthenticateRequest &other)
virtual Ieee80211Prim_DeauthenticateRequest * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::MacAddress & getAddress () const
virtual ::inet::MacAddress & getAddressForUpdate ()
virtual void setAddress (const ::inet::MacAddress &address)
virtual Ieee80211ReasonCode getReasonCode () const
virtual void setReasonCode (Ieee80211ReasonCode reasonCode)
Public Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
Ieee80211PrimRequest ()
Ieee80211PrimRequest (const Ieee80211PrimRequest &other)
virtual ~Ieee80211PrimRequest ()
Ieee80211PrimRequest & operator= (const Ieee80211PrimRequest &other)
Protected Member Functions
bool operator== (const Ieee80211Prim_DeauthenticateRequest &)=delete
Protected Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
bool operator== (const Ieee80211PrimRequest &)=delete
Protected Attributes
::inet::MacAddress address
Ieee80211ReasonCode reasonCode = static_cast<inet::ieee80211::Ieee80211ReasonCode>(-1)
Private Member Functions
void copy (const Ieee80211Prim_DeauthenticateRequest &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:156 by opp_msgtool.
//
// Losely based on MLME-DEAUTHENTICATE.request
//
// NOTE: there is no Deauthenticate Confirm, because Deauthenticate Request
// takes place immediately, and nothing can go wrong (there is no reply
// from the AP to wait for)
//
class Ieee80211Prim_DeauthenticateRequest extends Ieee80211PrimRequest
{
    MacAddress address;
    Ieee80211ReasonCode reasonCode;
}
Constructor & Destructor Documentation
Ieee80211Prim_DeauthenticateRequest() [1/2]
inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::Ieee80211Prim_DeauthenticateRequest ()
Ieee80211Prim_DeauthenticateRequest() [2/2]
inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::Ieee80211Prim_DeauthenticateRequest (const Ieee80211Prim_DeauthenticateRequest & other)
~Ieee80211Prim_DeauthenticateRequest()
virtual inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::~Ieee80211Prim_DeauthenticateRequest () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::copy (const Ieee80211Prim_DeauthenticateRequest & other) private
dup()
virtual Ieee80211Prim_DeauthenticateRequest* inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::dup () const inline override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
 {return new Ieee80211Prim_DeauthenticateRequest(*this);}
getAddress()
virtual const ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::getAddress () const virtual
getAddressForUpdate()
virtual ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::getAddressForUpdate () inline
 { return const_cast<::inet::MacAddress&>(const_cast<Ieee80211Prim_DeauthenticateRequest*>(this)->getAddress());}
getReasonCode()
virtual Ieee80211ReasonCode inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::getReasonCode () const virtual
operator=()
Ieee80211Prim_DeauthenticateRequest& inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::operator= (const Ieee80211Prim_DeauthenticateRequest & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::operator== (const Ieee80211Prim_DeauthenticateRequest &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Referenced by inet::ieee80211::doParsimUnpacking().
setAddress()
virtual void inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::setAddress (const ::inet::MacAddress & address) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendDeauthenticateRequest().
setReasonCode()
virtual void inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::setReasonCode (Ieee80211ReasonCode reasonCode) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendDeauthenticateRequest().
Member Data Documentation
address
::inet::MacAddress inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::address protected
reasonCode
Ieee80211ReasonCode inet::ieee80211::Ieee80211Prim_DeauthenticateRequest::reasonCode = static_cast<inet::ieee80211::Ieee80211ReasonCode>(-1) protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h