INET Framework for OMNeT++/OMNEST: inet::sctp::SctpInitAckChunk Class Reference
inet::sctp::SctpInitAckChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:67 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpInitAckChunk (const char *name=nullptr)
SctpInitAckChunk (const SctpInitAckChunk &other)
virtual ~SctpInitAckChunk ()
SctpInitAckChunk & operator= (const SctpInitAckChunk &other)
virtual SctpInitAckChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getInitTag () const
virtual void setInitTag (uint32_t initTag)
virtual uint32_t getA_rwnd () const
virtual void setA_rwnd (uint32_t a_rwnd)
virtual uint16_t getNoOutStreams () const
virtual void setNoOutStreams (uint16_t noOutStreams)
virtual uint16_t getNoInStreams () const
virtual void setNoInStreams (uint16_t noInStreams)
virtual uint32_t getInitTsn () const
virtual void setInitTsn (uint32_t initTsn)
virtual bool getForwardTsn () const
virtual void setForwardTsn (bool forwardTsn)
virtual bool getIpv4Supported () const
virtual void setIpv4Supported (bool ipv4Supported)
virtual bool getIpv6Supported () const
virtual void setIpv6Supported (bool ipv6Supported)
virtual void setAddressesArraySize (size_t size)
virtual size_t getAddressesArraySize () const
virtual const ::inet::L3Address & getAddresses (size_t k) const
virtual ::inet::L3Address & getAddressesForUpdate (size_t k)
virtual void setAddresses (size_t k, const ::inet::L3Address &addresses)
virtual void insertAddresses (size_t k, const ::inet::L3Address &addresses)
void insertAddresses (const ::inet::L3Address &addresses)
virtual void appendAddresses (const ::inet::L3Address &addresses)
virtual void eraseAddresses (size_t k)
virtual void setCookieArraySize (size_t size)
virtual size_t getCookieArraySize () const
virtual char getCookie (size_t k) const
virtual void setCookie (size_t k, char cookie)
virtual void insertCookie (size_t k, char cookie)
void insertCookie (char cookie)
virtual void appendCookie (char cookie)
virtual void eraseCookie (size_t k)
virtual void setUnrecognizedParametersArraySize (size_t size)
virtual size_t getUnrecognizedParametersArraySize () const
virtual uint8_t getUnrecognizedParameters (size_t k) const
virtual void setUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters)
virtual void insertUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters)
void insertUnrecognizedParameters (uint8_t unrecognizedParameters)
virtual void appendUnrecognizedParameters (uint8_t unrecognizedParameters)
virtual void eraseUnrecognizedParameters (size_t k)
virtual const SctpCookie * getStateCookie () const
virtual SctpCookie * getStateCookieForUpdate ()
virtual void setStateCookie (SctpCookie *stateCookie)
virtual uint32_t getMsg_rwnd () const
virtual void setMsg_rwnd (uint32_t msg_rwnd)
virtual void setRandomArraySize (size_t size)
virtual size_t getRandomArraySize () const
virtual uint8_t getRandom (size_t k) const
virtual void setRandom (size_t k, uint8_t random)
virtual void insertRandom (size_t k, uint8_t random)
void insertRandom (uint8_t random)
virtual void appendRandom (uint8_t random)
virtual void eraseRandom (size_t k)
virtual void setSctpChunkTypesArraySize (size_t size)
virtual size_t getSctpChunkTypesArraySize () const
virtual uint16_t getSctpChunkTypes (size_t k) const
virtual void setSctpChunkTypes (size_t k, uint16_t sctpChunkTypes)
virtual void insertSctpChunkTypes (size_t k, uint16_t sctpChunkTypes)
void insertSctpChunkTypes (uint16_t sctpChunkTypes)
virtual void appendSctpChunkTypes (uint16_t sctpChunkTypes)
virtual void eraseSctpChunkTypes (size_t k)
virtual void setSepChunksArraySize (size_t size)
virtual size_t getSepChunksArraySize () const
virtual uint16_t getSepChunks (size_t k) const
virtual void setSepChunks (size_t k, uint16_t sepChunks)
virtual void insertSepChunks (size_t k, uint16_t sepChunks)
void insertSepChunks (uint16_t sepChunks)
virtual void appendSepChunks (uint16_t sepChunks)
virtual void eraseSepChunks (size_t k)
virtual void setHmacTypesArraySize (size_t size)
virtual size_t getHmacTypesArraySize () const
virtual uint16_t getHmacTypes (size_t k) const
virtual void setHmacTypes (size_t k, uint16_t hmacTypes)
virtual void insertHmacTypes (size_t k, uint16_t hmacTypes)
void insertHmacTypes (uint16_t hmacTypes)
virtual void appendHmacTypes (uint16_t hmacTypes)
virtual void eraseHmacTypes (size_t k)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpInitAckChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint32_t initTag = 0
uint32_t a_rwnd = 0
uint16_t noOutStreams = 0
uint16_t noInStreams = 0
uint32_t initTsn = 0
bool forwardTsn = false
bool ipv4Supported = false
bool ipv6Supported = false
::inet::L3Address * addresses = nullptr
size_t addresses_arraysize = 0
char * cookie = nullptr
size_t cookie_arraysize = 0
uint8_t * unrecognizedParameters = nullptr
size_t unrecognizedParameters_arraysize = 0
SctpCookie * stateCookie = nullptr
uint32_t msg_rwnd = 0
uint8_t * random = nullptr
size_t random_arraysize = 0
uint16_t * sctpChunkTypes = nullptr
size_t sctpChunkTypes_arraysize = 0
uint16_t * sepChunks = nullptr
size_t sepChunks_arraysize = 0
uint16_t * hmacTypes = nullptr
size_t hmacTypes_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpInitAckChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:67 by opp_msgtool.
class SctpInitAckChunk extends SctpChunk
{
    // Initiate Tag
    uint32_t initTag;
    // Advertised Receiver Window
    uint32_t a_rwnd;
    // Number of Outbound Streams
    uint16_t noOutStreams;
    // Number of Inbound Streams
    uint16_t noInStreams;
    // Initial TSN
    uint32_t initTsn;
    bool forwardTsn;
    bool ipv4Supported;
    bool ipv6Supported;
    L3Address addresses[];
    char cookie[];
    uint8_t unrecognizedParameters[];
    SctpCookie *stateCookie;
    uint32_t msg_rwnd;
    uint8_t random[]; //Random Number
    uint16_t sctpChunkTypes[];
    uint16_t sepChunks[]; //Supported extensions parameter, i.e. for StreamReset
    uint16_t hmacTypes[];
}
Constructor & Destructor Documentation
SctpInitAckChunk() [1/2]
inet::sctp::SctpInitAckChunk::SctpInitAckChunk (const char * name = nullptr)
SctpInitAckChunk() [2/2]
inet::sctp::SctpInitAckChunk::SctpInitAckChunk (const SctpInitAckChunk & other)
~SctpInitAckChunk()
virtual inet::sctp::SctpInitAckChunk::~SctpInitAckChunk () virtual
Member Function Documentation
appendAddresses()
virtual void inet::sctp::SctpInitAckChunk::appendAddresses (const ::inet::L3Address & addresses) virtual
appendCookie()
virtual void inet::sctp::SctpInitAckChunk::appendCookie (char cookie) virtual
appendHmacTypes()
virtual void inet::sctp::SctpInitAckChunk::appendHmacTypes (uint16_t hmacTypes) virtual
appendRandom()
virtual void inet::sctp::SctpInitAckChunk::appendRandom (uint8_t random) virtual
appendSctpChunkTypes()
virtual void inet::sctp::SctpInitAckChunk::appendSctpChunkTypes (uint16_t sctpChunkTypes) virtual
appendSepChunks()
virtual void inet::sctp::SctpInitAckChunk::appendSepChunks (uint16_t sepChunks) virtual
appendUnrecognizedParameters()
virtual void inet::sctp::SctpInitAckChunk::appendUnrecognizedParameters (uint8_t unrecognizedParameters) virtual
copy()
void inet::sctp::SctpInitAckChunk::copy (const SctpInitAckChunk & other) private
dup()
virtual SctpInitAckChunk* inet::sctp::SctpInitAckChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpInitAckChunk(*this);}
eraseAddresses()
virtual void inet::sctp::SctpInitAckChunk::eraseAddresses (size_t k) virtual
eraseCookie()
virtual void inet::sctp::SctpInitAckChunk::eraseCookie (size_t k) virtual
eraseHmacTypes()
virtual void inet::sctp::SctpInitAckChunk::eraseHmacTypes (size_t k) virtual
eraseRandom()
virtual void inet::sctp::SctpInitAckChunk::eraseRandom (size_t k) virtual
eraseSctpChunkTypes()
virtual void inet::sctp::SctpInitAckChunk::eraseSctpChunkTypes (size_t k) virtual
eraseSepChunks()
virtual void inet::sctp::SctpInitAckChunk::eraseSepChunks (size_t k) virtual
eraseUnrecognizedParameters()
virtual void inet::sctp::SctpInitAckChunk::eraseUnrecognizedParameters (size_t k) virtual
getA_rwnd()
virtual uint32_t inet::sctp::SctpInitAckChunk::getA_rwnd () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddresses()
virtual const ::inet::L3Address& inet::sctp::SctpInitAckChunk::getAddresses (size_t k) const virtual
Referenced by inet::sctp::Sctp::findAssocForInitAck(), inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressesArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getAddressesArraySize () const virtual
Referenced by inet::sctp::Sctp::findAssocForInitAck(), inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressesForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpInitAckChunk::getAddressesForUpdate (size_t k) inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpInitAckChunk*>(this)->getAddresses(k));}
getCookie()
virtual char inet::sctp::SctpInitAckChunk::getCookie (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho(), and inet::sctp::SctpHeaderSerializer::serialize().
getCookieArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getCookieArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getForwardTsn()
virtual bool inet::sctp::SctpInitAckChunk::getForwardTsn () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getHmacTypes()
virtual uint16_t inet::sctp::SctpInitAckChunk::getHmacTypes (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getHmacTypesArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getHmacTypesArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getInitTag()
virtual uint32_t inet::sctp::SctpInitAckChunk::getInitTag () const virtual
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), inet::sctp::SctpNatHook::datagramPreRoutingHook(), inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getInitTsn()
virtual uint32_t inet::sctp::SctpInitAckChunk::getInitTsn () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getIpv4Supported()
virtual bool inet::sctp::SctpInitAckChunk::getIpv4Supported () const virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getIpv6Supported()
virtual bool inet::sctp::SctpInitAckChunk::getIpv6Supported () const virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getMsg_rwnd()
virtual uint32_t inet::sctp::SctpInitAckChunk::getMsg_rwnd () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived().
getNoInStreams()
virtual uint16_t inet::sctp::SctpInitAckChunk::getNoInStreams () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getNoOutStreams()
virtual uint16_t inet::sctp::SctpInitAckChunk::getNoOutStreams () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getRandom()
virtual uint8_t inet::sctp::SctpInitAckChunk::getRandom (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getRandomArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getRandomArraySize () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getSctpChunkTypes()
virtual uint16_t inet::sctp::SctpInitAckChunk::getSctpChunkTypes (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSctpChunkTypesArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getSctpChunkTypesArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getSepChunks()
virtual uint16_t inet::sctp::SctpInitAckChunk::getSepChunks (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSepChunksArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getSepChunksArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getStateCookie()
virtual const SctpCookie* inet::sctp::SctpInitAckChunk::getStateCookie () const virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho(), and inet::sctp::SctpHeaderSerializer::serialize().
getStateCookieForUpdate()
virtual SctpCookie* inet::sctp::SctpInitAckChunk::getStateCookieForUpdate () inline virtual
 { return const_cast<SctpCookie *>(const_cast<SctpInitAckChunk*>(this)->getStateCookie());}
getUnrecognizedParameters()
virtual uint8_t inet::sctp::SctpInitAckChunk::getUnrecognizedParameters (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho(), and inet::sctp::SctpHeaderSerializer::serialize().
getUnrecognizedParametersArraySize()
virtual size_t inet::sctp::SctpInitAckChunk::getUnrecognizedParametersArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho(), and inet::sctp::SctpHeaderSerializer::serialize().
insertAddresses() [1/2]
void inet::sctp::SctpInitAckChunk::insertAddresses (const ::inet::L3Address & addresses) inline
 {appendAddresses(addresses);}
insertAddresses() [2/2]
virtual void inet::sctp::SctpInitAckChunk::insertAddresses (size_t k, const ::inet::L3Address & addresses) virtual
insertCookie() [1/2]
void inet::sctp::SctpInitAckChunk::insertCookie (char cookie) inline
 {appendCookie(cookie);}
insertCookie() [2/2]
virtual void inet::sctp::SctpInitAckChunk::insertCookie (size_t k, char cookie) virtual
insertHmacTypes() [1/2]
virtual void inet::sctp::SctpInitAckChunk::insertHmacTypes (size_t k, uint16_t hmacTypes) virtual
insertHmacTypes() [2/2]
void inet::sctp::SctpInitAckChunk::insertHmacTypes (uint16_t hmacTypes) inline
 {appendHmacTypes(hmacTypes);}
insertRandom() [1/2]
virtual void inet::sctp::SctpInitAckChunk::insertRandom (size_t k, uint8_t random) virtual
insertRandom() [2/2]
void inet::sctp::SctpInitAckChunk::insertRandom (uint8_t random) inline
 {appendRandom(random);}
insertSctpChunkTypes() [1/2]
virtual void inet::sctp::SctpInitAckChunk::insertSctpChunkTypes (size_t k, uint16_t sctpChunkTypes) virtual
insertSctpChunkTypes() [2/2]
void inet::sctp::SctpInitAckChunk::insertSctpChunkTypes (uint16_t sctpChunkTypes) inline
 {appendSctpChunkTypes(sctpChunkTypes);}
insertSepChunks() [1/2]
virtual void inet::sctp::SctpInitAckChunk::insertSepChunks (size_t k, uint16_t sepChunks) virtual
insertSepChunks() [2/2]
void inet::sctp::SctpInitAckChunk::insertSepChunks (uint16_t sepChunks) inline
 {appendSepChunks(sepChunks);}
insertUnrecognizedParameters() [1/2]
virtual void inet::sctp::SctpInitAckChunk::insertUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters) virtual
insertUnrecognizedParameters() [2/2]
void inet::sctp::SctpInitAckChunk::insertUnrecognizedParameters (uint8_t unrecognizedParameters) inline
 {appendUnrecognizedParameters(unrecognizedParameters);}
operator=()
SctpInitAckChunk& inet::sctp::SctpInitAckChunk::operator= (const SctpInitAckChunk & other)
operator==()
bool inet::sctp::SctpInitAckChunk::operator== (const SctpInitAckChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpInitAckChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpInitAckChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setA_rwnd()
virtual void inet::sctp::SctpInitAckChunk::setA_rwnd (uint32_t a_rwnd) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setAddresses()
virtual void inet::sctp::SctpInitAckChunk::setAddresses (size_t k, const ::inet::L3Address & addresses) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setAddressesArraySize()
virtual void inet::sctp::SctpInitAckChunk::setAddressesArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setCookie()
virtual void inet::sctp::SctpInitAckChunk::setCookie (size_t k, char cookie) virtual
setCookieArraySize()
virtual void inet::sctp::SctpInitAckChunk::setCookieArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setForwardTsn()
virtual void inet::sctp::SctpInitAckChunk::setForwardTsn (bool forwardTsn) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setHmacTypes()
virtual void inet::sctp::SctpInitAckChunk::setHmacTypes (size_t k, uint16_t hmacTypes) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setHmacTypesArraySize()
virtual void inet::sctp::SctpInitAckChunk::setHmacTypesArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setInitTag()
virtual void inet::sctp::SctpInitAckChunk::setInitTag (uint32_t initTag) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setInitTsn()
virtual void inet::sctp::SctpInitAckChunk::setInitTsn (uint32_t initTsn) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setIpv4Supported()
virtual void inet::sctp::SctpInitAckChunk::setIpv4Supported (bool ipv4Supported) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setIpv6Supported()
virtual void inet::sctp::SctpInitAckChunk::setIpv6Supported (bool ipv6Supported) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setMsg_rwnd()
virtual void inet::sctp::SctpInitAckChunk::setMsg_rwnd (uint32_t msg_rwnd) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setNoInStreams()
virtual void inet::sctp::SctpInitAckChunk::setNoInStreams (uint16_t noInStreams) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setNoOutStreams()
virtual void inet::sctp::SctpInitAckChunk::setNoOutStreams (uint16_t noOutStreams) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setRandom()
virtual void inet::sctp::SctpInitAckChunk::setRandom (size_t k, uint8_t random) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setRandomArraySize()
virtual void inet::sctp::SctpInitAckChunk::setRandomArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setSctpChunkTypes()
virtual void inet::sctp::SctpInitAckChunk::setSctpChunkTypes (size_t k, uint16_t sctpChunkTypes) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setSctpChunkTypesArraySize()
virtual void inet::sctp::SctpInitAckChunk::setSctpChunkTypesArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setSepChunks()
virtual void inet::sctp::SctpInitAckChunk::setSepChunks (size_t k, uint16_t sepChunks) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setSepChunksArraySize()
virtual void inet::sctp::SctpInitAckChunk::setSepChunksArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setStateCookie()
virtual void inet::sctp::SctpInitAckChunk::setStateCookie (SctpCookie * stateCookie) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setUnrecognizedParameters()
virtual void inet::sctp::SctpInitAckChunk::setUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
setUnrecognizedParametersArraySize()
virtual void inet::sctp::SctpInitAckChunk::setUnrecognizedParametersArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
Member Data Documentation
a_rwnd
uint32_t inet::sctp::SctpInitAckChunk::a_rwnd = 0 protected
addresses
::inet::L3Address* inet::sctp::SctpInitAckChunk::addresses = nullptr protected
addresses_arraysize
size_t inet::sctp::SctpInitAckChunk::addresses_arraysize = 0 protected
cookie
char* inet::sctp::SctpInitAckChunk::cookie = nullptr protected
cookie_arraysize
size_t inet::sctp::SctpInitAckChunk::cookie_arraysize = 0 protected
forwardTsn
bool inet::sctp::SctpInitAckChunk::forwardTsn = false protected
hmacTypes
uint16_t* inet::sctp::SctpInitAckChunk::hmacTypes = nullptr protected
hmacTypes_arraysize
size_t inet::sctp::SctpInitAckChunk::hmacTypes_arraysize = 0 protected
initTag
uint32_t inet::sctp::SctpInitAckChunk::initTag = 0 protected
initTsn
uint32_t inet::sctp::SctpInitAckChunk::initTsn = 0 protected
ipv4Supported
bool inet::sctp::SctpInitAckChunk::ipv4Supported = false protected
ipv6Supported
bool inet::sctp::SctpInitAckChunk::ipv6Supported = false protected
msg_rwnd
uint32_t inet::sctp::SctpInitAckChunk::msg_rwnd = 0 protected
noInStreams
uint16_t inet::sctp::SctpInitAckChunk::noInStreams = 0 protected
noOutStreams
uint16_t inet::sctp::SctpInitAckChunk::noOutStreams = 0 protected
random
uint8_t* inet::sctp::SctpInitAckChunk::random = nullptr protected
random_arraysize
size_t inet::sctp::SctpInitAckChunk::random_arraysize = 0 protected
sctpChunkTypes
uint16_t* inet::sctp::SctpInitAckChunk::sctpChunkTypes = nullptr protected
sctpChunkTypes_arraysize
size_t inet::sctp::SctpInitAckChunk::sctpChunkTypes_arraysize = 0 protected
sepChunks
uint16_t* inet::sctp::SctpInitAckChunk::sepChunks = nullptr protected
sepChunks_arraysize
size_t inet::sctp::SctpInitAckChunk::sepChunks_arraysize = 0 protected
stateCookie
SctpCookie* inet::sctp::SctpInitAckChunk::stateCookie = nullptr protected
unrecognizedParameters
uint8_t* inet::sctp::SctpInitAckChunk::unrecognizedParameters = nullptr protected
unrecognizedParameters_arraysize
size_t inet::sctp::SctpInitAckChunk::unrecognizedParameters_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h