INET Framework for OMNeT++/OMNEST: inet::ieee80211::SequenceControlField Class Reference
inet::ieee80211::SequenceControlField Class Reference
8.2.4.4.1 Sequence Control field structure The Sequence Control field is 16 bits in length and consists of two subfields, the Sequence Number and the Fragment Number.
#include <SequenceControlField.h>
Public Member Functions
SequenceControlField (SequenceNumber sequenceNumber, FragmentNumber fragmentNumber)
SequenceNumber getSequenceNumber () const
FragmentNumber getFragmentNumber () const
bool operator< (const SequenceControlField &other) const
Private Attributes
SequenceNumber sequenceNumber
FragmentNumber fragmentNumber
Detailed Description
8.2.4.4.1 Sequence Control field structure The Sequence Control field is 16 bits in length and consists of two subfields, the Sequence Number and the Fragment Number.
Constructor & Destructor Documentation
SequenceControlField()
inet::ieee80211::SequenceControlField::SequenceControlField (SequenceNumber sequenceNumber, FragmentNumber fragmentNumber) inline
                                                                                        :
         sequenceNumber(sequenceNumber),
         fragmentNumber(fragmentNumber)
     {
         ASSERT(fragmentNumber < 16);
     }
Member Function Documentation
getFragmentNumber()
FragmentNumber inet::ieee80211::SequenceControlField::getFragmentNumber () const inline
 { return fragmentNumber; }
Referenced by inet::ieee80211::LegacyDuplicateRemoval::isDuplicate(), inet::ieee80211::QoSDuplicateRemoval::isDuplicate(), and inet::ieee80211::operator<<().
getSequenceNumber()
SequenceNumber inet::ieee80211::SequenceControlField::getSequenceNumber () const inline
 { return sequenceNumber; }
Referenced by inet::ieee80211::LegacyDuplicateRemoval::isDuplicate(), inet::ieee80211::QoSDuplicateRemoval::isDuplicate(), and inet::ieee80211::operator<<().
operator<()
bool inet::ieee80211::SequenceControlField::operator< (const SequenceControlField & other) const inline
{
         return sequenceNumber < other.sequenceNumber ||
                (sequenceNumber == other.sequenceNumber && fragmentNumber < other.fragmentNumber);
     }
Member Data Documentation
fragmentNumber
FragmentNumber inet::ieee80211::SequenceControlField::fragmentNumber private
Referenced by operator<().
sequenceNumber
SequenceNumber inet::ieee80211::SequenceControlField::sequenceNumber private
Referenced by operator<().
The documentation for this class was generated from the following file:
SequenceControlField.h