INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpDisabledInterfaces Class Reference
inet::eigrp::EigrpDisabledInterfaces Class Reference
Table with disabled EIGRP interfaces.
#include <EigrpDisabledInterfaces.h>
Public Member Functions
EigrpDisabledInterfaces ()
virtual ~EigrpDisabledInterfaces ()
int getNumInterfaces () const
Returns number of interfaces in the table.
EigrpInterface * removeInterface (EigrpInterface *iface)
Removes specified interface from table and returns it.
void addInterface (EigrpInterface *interface)
Adds interface to the table.
EigrpInterface * findInterface (int ifaceId)
Finds interface by ID in table and returns it.
EigrpInterface * getInterface (int k) const
Returns interface by its position in the table.
Protected Attributes
std::vector< EigrpInterface * > ifVector
Detailed Description
Table with disabled EIGRP interfaces.
Used to store the settings of interfaces.
Constructor & Destructor Documentation
EigrpDisabledInterfaces()
inet::eigrp::EigrpDisabledInterfaces::EigrpDisabledInterfaces ()
 {
 }
~EigrpDisabledInterfaces()
inet::eigrp::EigrpDisabledInterfaces::~EigrpDisabledInterfaces () virtual
 {
     int cnt = ifVector.size();
     EigrpInterface *iface;
     for (int i = 0; i < cnt; i++) {
         iface = ifVector[i];
         ifVector[i] = nullptr;
         delete iface;
     }
     ifVector.clear();
 }
Member Function Documentation
addInterface()
void inet::eigrp::EigrpDisabledInterfaces::addInterface (EigrpInterface * interface)
Adds interface to the table.
 {
     // TODO check duplicity
     this->ifVector.push_back(interface);
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::addInterfaceToEigrp(), inet::eigrp::EigrpIpv6Pdm::addInterfaceToEigrp(), inet::eigrp::EigrpIpv4Pdm::disableInterface(), and inet::eigrp::EigrpIpv6Pdm::disableInterface().
findInterface()
EigrpInterface * inet::eigrp::EigrpDisabledInterfaces::findInterface (int ifaceId)
Finds interface by ID in table and returns it.
If interface with specified ID does not exist in the table, returns null.
 {
     EigrpInterface *iface;
     for (auto it = ifVector.begin(); it != ifVector.end(); it++) {
         iface = *it;
         if (iface->getInterfaceId() == ifaceId) {
             return iface;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::getInterfaceById(), and inet::eigrp::EigrpIpv6Pdm::getInterfaceById().
getInterface()
EigrpInterface* inet::eigrp::EigrpDisabledInterfaces::getInterface (int k) const inline
Returns interface by its position in the table.
 { return ifVector[k]; }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHelloTimers(), and inet::eigrp::EigrpIpv6Pdm::cancelHelloTimers().
getNumInterfaces()
int inet::eigrp::EigrpDisabledInterfaces::getNumInterfaces () const inline
Returns number of interfaces in the table.
 { return ifVector.size(); }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHelloTimers(), and inet::eigrp::EigrpIpv6Pdm::cancelHelloTimers().
removeInterface()
EigrpInterface * inet::eigrp::EigrpDisabledInterfaces::removeInterface (EigrpInterface * iface)
Removes specified interface from table and returns it.
If interface does not exist in the table, returns null.
 {
     auto it = find(ifVector, iface);
     if (it != ifVector.end()) {
         ifVector.erase(it);
         return iface;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), and inet::eigrp::EigrpIpv6Pdm::enableInterface().
Member Data Documentation
ifVector
std::vector<EigrpInterface *> inet::eigrp::EigrpDisabledInterfaces::ifVector protected
Referenced by addInterface(), findInterface(), getInterface(), getNumInterfaces(), removeInterface(), and ~EigrpDisabledInterfaces().
The documentation for this class was generated from the following files:
EigrpDisabledInterfaces.h
EigrpDisabledInterfaces.cc