INET Framework for OMNeT++/OMNEST: inet::EligibilityTimeMeter Class Reference
inet::EligibilityTimeMeter Class Reference
#include <EligibilityTimeMeter.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual void meterPacket (Packet *packet) override
virtual void emitNumTokenChangedSignal ()
Protected Member Functions inherited from inet::PacketMeterBase
virtual int numInitStages () const override
virtual void handleMessage (cMessage *message) override
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
b packetOverheadLength = b(-1)
bps committedInformationRate = bps(NaN)
b committedBurstSize = b(-1)
clocktime_t maxResidenceTime
clocktime_t groupEligibilityTime
clocktime_t bucketEmptyTime
double numTokens = 0
Protected Attributes inherited from inet::PacketMeterBase
cGate * inputGate = nullptr
IActivePacketSource * producer = nullptr
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Public Member Functions inherited from inet::ClockUserModuleMixin< PacketMeterBase >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::PacketMeterBase
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
virtual void pushPacket (Packet *packet, cGate *gate)=0
Pushes the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
emitNumTokenChangedSignal()
void inet::EligibilityTimeMeter::emitNumTokenChangedSignal () protected virtual
 {
     clocktime_t emptyToFullDuration = s(committedBurstSize / committedInformationRate).get();
     double alpha = (getClockTime() - bucketEmptyTime).dbl() / emptyToFullDuration.dbl();
     if (alpha > 1.0) {
         numTokens = b(committedBurstSize).get();
         cTimestampedValue value(CLOCKTIME_AS_SIMTIME(bucketEmptyTime + emptyToFullDuration), numTokens);
         emit(tokensChangedSignal, &value);
         emit(tokensChangedSignal, numTokens);
     }
     else {
         numTokens = b(committedBurstSize).get() * alpha;
         emit(tokensChangedSignal, numTokens);
     }
 }
Referenced by initialize(), and meterPacket().
initialize()
void inet::EligibilityTimeMeter::initialize (int stage) override protected virtual
Reimplemented from inet::PacketMeterBase.
 {
     ClockUserModuleMixin::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         packetOverheadLength = b(par("packetOverheadLength"));
         committedInformationRate = bps(par("committedInformationRate"));
         committedBurstSize = b(par("committedBurstSize"));
         maxResidenceTime = par("maxResidenceTime");
         groupEligibilityTime = 0;
         bucketEmptyTime = s(-committedBurstSize / committedInformationRate).get();
         WATCH(groupEligibilityTime);
         WATCH(bucketEmptyTime);
         WATCH(maxResidenceTime);
         WATCH(numTokens);
     }
     else if (stage == INITSTAGE_QUEUEING)
         emitNumTokenChangedSignal();
 }
meterPacket()
void inet::EligibilityTimeMeter::meterPacket (Packet * packet) override protected virtual
Implements inet::PacketMeterBase.
 {
     emitNumTokenChangedSignal();
     clocktime_t arrivalTime = getClockTime();
     clocktime_t lengthRecoveryDuration = s((packet->getDataLength() + packetOverheadLength) / committedInformationRate).get();
     clocktime_t emptyToFullDuration = s(committedBurstSize / committedInformationRate).get();
     clocktime_t schedulerEligibilityTime = bucketEmptyTime + lengthRecoveryDuration;
     clocktime_t bucketFullTime = bucketEmptyTime + emptyToFullDuration;
     clocktime_t eligibilityTime;
     eligibilityTime.setRaw(std::max(std::max(arrivalTime.raw(), groupEligibilityTime.raw()), schedulerEligibilityTime.raw()));
     if (maxResidenceTime == -1 || eligibilityTime <= arrivalTime + maxResidenceTime) {
         groupEligibilityTime = eligibilityTime;
         bucketEmptyTime = eligibilityTime < bucketFullTime ? schedulerEligibilityTime : schedulerEligibilityTime + eligibilityTime - bucketFullTime;
         packet->addTagIfAbsent<EligibilityTimeTag>()->setEligibilityTime(eligibilityTime);
         emitNumTokenChangedSignal();
     }
 }
Member Data Documentation
bucketEmptyTime
clocktime_t inet::EligibilityTimeMeter::bucketEmptyTime protected
Referenced by emitNumTokenChangedSignal(), initialize(), and meterPacket().
committedBurstSize
b inet::EligibilityTimeMeter::committedBurstSize = b(-1) protected
Referenced by emitNumTokenChangedSignal(), initialize(), and meterPacket().
committedInformationRate
bps inet::EligibilityTimeMeter::committedInformationRate = bps(NaN) protected
Referenced by emitNumTokenChangedSignal(), initialize(), and meterPacket().
groupEligibilityTime
clocktime_t inet::EligibilityTimeMeter::groupEligibilityTime protected
Referenced by initialize(), and meterPacket().
maxResidenceTime
clocktime_t inet::EligibilityTimeMeter::maxResidenceTime protected
Referenced by initialize(), and meterPacket().
numTokens
double inet::EligibilityTimeMeter::numTokens = 0 protected
Referenced by emitNumTokenChangedSignal(), and initialize().
packetOverheadLength
b inet::EligibilityTimeMeter::packetOverheadLength = b(-1) protected
Referenced by initialize(), and meterPacket().
The documentation for this class was generated from the following files:
EligibilityTimeMeter.h
EligibilityTimeMeter.cc