INET Framework for OMNeT++/OMNEST: inet::physicallayer::ScalarAnalogModelBase Class Reference
inet::physicallayer::ScalarAnalogModelBase Class Reference
#include <ScalarAnalogModelBase.h>
Public Member Functions
virtual W computeReceptionPower (const IRadio *radio, const ITransmission *transmission, const IArrival *arrival) const
virtual const INoise * computeNoise (const IListening *listening, const IInterference *interference) const override
Returns the total noise summing up all the interfering receptions and noises.
virtual const INoise * computeNoise (const IReception *reception, const INoise *noise) const override
Returns the total noise summing up all the reception and the noise.
virtual const ISnir * computeSNIR (const IReception *reception, const INoise *noise) const override
Returns the signal to noise and interference ratio.
Public Member Functions inherited from inet::physicallayer::IAnalogModel
virtual const IReception * computeReception (const IRadio *receiver, const ITransmission *transmission, const IArrival *arrival) const =0
Returns the reception for the provided transmission at the receiver.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual bool areOverlappingBands (Hz centerFrequency1, Hz bandwidth1, Hz centerFrequency2, Hz bandwidth2) const
virtual void addReception (const IReception *reception, simtime_t &noiseStartTime, simtime_t &noiseEndTime, std::map< simtime_t, W > *powerChanges) const
virtual void addNoise (const ScalarNoise *noise, simtime_t &noiseStartTime, simtime_t &noiseEndTime, std::map< simtime_t, W > *powerChanges) const
Protected Member Functions inherited from inet::physicallayer::AnalogModelBase
virtual double computeAntennaGain (const IAntennaGain *antenna, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation) const
Protected Attributes
bool ignorePartialInterference
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
addNoise()
void inet::physicallayer::ScalarAnalogModelBase::addNoise (const ScalarNoise * noise, simtime_t & noiseStartTime, simtime_t & noiseEndTime, std::map< simtime_t, W > * powerChanges) const protected virtual
 {
     const std::map<simtime_t, W> *noisePowerChanges = noise->getPowerChanges();
     for (const auto& noisePowerChange : *noisePowerChanges) {
         auto jt = powerChanges->find(noisePowerChange.first);
         if (jt != powerChanges->end())
             jt->second += noisePowerChange.second;
         else
             powerChanges->insert(std::pair<simtime_t, W>(noisePowerChange.first, noisePowerChange.second));
     }
     if (noise->getStartTime() < noiseStartTime)
         noiseStartTime = noise->getStartTime();
     if (noise->getEndTime() > noiseEndTime)
         noiseEndTime = noise->getEndTime();
 }
Referenced by computeNoise().
addReception()
void inet::physicallayer::ScalarAnalogModelBase::addReception (const IReception * reception, simtime_t & noiseStartTime, simtime_t & noiseEndTime, std::map< simtime_t, W > * powerChanges) const protected virtual
 {
     W power = check_and_cast<const IScalarSignal *>(reception->getAnalogModel())->getPower();
     simtime_t startTime = reception->getStartTime();
     simtime_t endTime = reception->getEndTime();
     auto itStartTime = powerChanges->find(startTime);
     if (itStartTime != powerChanges->end())
         itStartTime->second += power;
     else
         powerChanges->insert(std::pair<simtime_t, W>(startTime, power));
     auto itEndTime = powerChanges->find(endTime);
     if (itEndTime != powerChanges->end())
         itEndTime->second -= power;
     else
         powerChanges->insert(std::pair<simtime_t, W>(endTime, -power));
     if (reception->getStartTime() < noiseStartTime)
         noiseStartTime = reception->getStartTime();
     if (reception->getEndTime() > noiseEndTime)
         noiseEndTime = reception->getEndTime();
 }
Referenced by computeNoise().
areOverlappingBands()
bool inet::physicallayer::ScalarAnalogModelBase::areOverlappingBands (Hz centerFrequency1, Hz bandwidth1, Hz centerFrequency2, Hz bandwidth2) const protected virtual
 {
     return centerFrequency1 + bandwidth1 / 2 >= centerFrequency2 - bandwidth2 / 2 &&
            centerFrequency1 - bandwidth1 / 2 <= centerFrequency2 + bandwidth2 / 2;
 }
Referenced by computeNoise().
computeNoise() [1/2]
const INoise * inet::physicallayer::ScalarAnalogModelBase::computeNoise (const IListening * listening, const IInterference * interference) const override virtual
Returns the total noise summing up all the interfering receptions and noises.
This function never returns nullptr.
Implements inet::physicallayer::IAnalogModel.
 {
     const BandListening *bandListening = check_and_cast<const BandListening *>(listening);
     Hz commonCenterFrequency = bandListening->getCenterFrequency();
     Hz commonBandwidth = bandListening->getBandwidth();
     simtime_t noiseStartTime = SimTime::getMaxTime();
     simtime_t noiseEndTime = 0;
     std::map<simtime_t, W> *powerChanges = new std::map<simtime_t, W>();
     const std::vector<const IReception *> *interferingReceptions = interference->getInterferingReceptions();
     for (auto reception : *interferingReceptions) {
         const ISignalAnalogModel *signalAnalogModel = reception->getAnalogModel();
         const INarrowbandSignal *narrowbandSignalAnalogModel = check_and_cast<const INarrowbandSignal *>(signalAnalogModel);
         Hz signalCenterFrequency = narrowbandSignalAnalogModel->getCenterFrequency();
         Hz signalBandwidth = narrowbandSignalAnalogModel->getBandwidth();
         if (commonCenterFrequency == signalCenterFrequency && commonBandwidth >= signalBandwidth)
             addReception(reception, noiseStartTime, noiseEndTime, powerChanges);
         else if (!ignorePartialInterference && areOverlappingBands(commonCenterFrequency, commonBandwidth, narrowbandSignalAnalogModel->getCenterFrequency(), narrowbandSignalAnalogModel->getBandwidth()))
             throw cRuntimeError("Partially interfering signals are not supported by ScalarAnalogModel, enable ignorePartialInterference to avoid this error!");
     }
     const ScalarNoise *scalarBackgroundNoise = dynamic_cast<const ScalarNoise *>(interference->getBackgroundNoise());
     if (scalarBackgroundNoise) {
         if (commonCenterFrequency == scalarBackgroundNoise->getCenterFrequency() && commonBandwidth >= scalarBackgroundNoise->getBandwidth())
             addNoise(scalarBackgroundNoise, noiseStartTime, noiseEndTime, powerChanges);
         else if (!ignorePartialInterference && areOverlappingBands(commonCenterFrequency, commonBandwidth, scalarBackgroundNoise->getCenterFrequency(), scalarBackgroundNoise->getBandwidth()))
             throw cRuntimeError("Partially interfering background noise is not supported by ScalarAnalogModel, enable ignorePartialInterference to avoid this error!");
     }
     EV_TRACE << "Noise power begin " << endl;
     W noise = W(0);
     for (std::map<simtime_t, W>::const_iterator it = powerChanges->begin(); it != powerChanges->end(); it++) {
         noise += it->second;
         EV_TRACE << "Noise at " << it->first << " = " << noise << endl;
     }
     EV_TRACE << "Noise power end" << endl;
     return new ScalarNoise(noiseStartTime, noiseEndTime, commonCenterFrequency, commonBandwidth, powerChanges);
 }
computeNoise() [2/2]
const INoise * inet::physicallayer::ScalarAnalogModelBase::computeNoise (const IReception * reception, const INoise * noise) const override virtual
Returns the total noise summing up all the reception and the noise.
This function never returns nullptr.
Implements inet::physicallayer::IAnalogModel.
 {
     auto scalarNoise = check_and_cast<const ScalarNoise *>(noise);
     simtime_t noiseStartTime = SimTime::getMaxTime();
     simtime_t noiseEndTime = 0;
     std::map<simtime_t, W> *powerChanges = new std::map<simtime_t, W>();
     addReception(reception, noiseStartTime, noiseEndTime, powerChanges);
     addNoise(scalarNoise, noiseStartTime, noiseEndTime, powerChanges);
     return new ScalarNoise(noiseStartTime, noiseEndTime, scalarNoise->getCenterFrequency(), scalarNoise->getBandwidth(), powerChanges);
 }
computeReceptionPower()
W inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower (const IRadio * radio, const ITransmission * transmission, const IArrival * arrival) const virtual
 {
     const IRadioMedium *radioMedium = receiverRadio->getMedium();
     const INarrowbandSignal *narrowbandSignalAnalogModel = check_and_cast<const INarrowbandSignal *>(transmission->getAnalogModel());
     const IScalarSignal *scalarSignalAnalogModel = check_and_cast<const IScalarSignal *>(transmission->getAnalogModel());
     const Coord& receptionStartPosition = arrival->getStartPosition();
     // TODO could be used for doppler shift? const Coord& receptionEndPosition = arrival->getEndPosition();
     double transmitterAntennaGain = computeAntennaGain(transmission->getTransmitterAntennaGain(), transmission->getStartPosition(), arrival->getStartPosition(), transmission->getStartOrientation());
     double receiverAntennaGain = computeAntennaGain(receiverRadio->getAntenna()->getGain().get(), arrival->getStartPosition(), transmission->getStartPosition(), arrival->getStartOrientation());
     double pathLoss = radioMedium->getPathLoss()->computePathLoss(transmission, arrival);
     double obstacleLoss = radioMedium->getObstacleLoss() ? radioMedium->getObstacleLoss()->computeObstacleLoss(narrowbandSignalAnalogModel->getCenterFrequency(), transmission->getStartPosition(), receptionStartPosition) : 1;
     W transmissionPower = scalarSignalAnalogModel->getPower();
     ASSERT(!std::isnan(transmissionPower.get()));
     double gain = transmitterAntennaGain * receiverAntennaGain * pathLoss * obstacleLoss;
     ASSERT(!std::isnan(gain));
     if (gain > 1.0) {
         EV_WARN << "Signal power attenuation is zero.\n";
         gain = 1.0;
     }
     return transmissionPower * gain;
 }
Referenced by inet::physicallayer::ScalarAnalogModel::computeReception(), and inet::physicallayer::LayeredScalarAnalogModel::computeReception().
computeSNIR()
const ISnir * inet::physicallayer::ScalarAnalogModelBase::computeSNIR (const IReception * reception, const INoise * noise) const override virtual
Returns the signal to noise and interference ratio.
This function never returns nullptr.
Implements inet::physicallayer::IAnalogModel.
 {
     return new ScalarSnir(reception, noise);
 }
initialize()
void inet::physicallayer::ScalarAnalogModelBase::initialize (int stage) override protected virtual
 {
     AnalogModelBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         ignorePartialInterference = par("ignorePartialInterference");
     }
 }
numInitStages()
virtual int inet::physicallayer::ScalarAnalogModelBase::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
Member Data Documentation
ignorePartialInterference
bool inet::physicallayer::ScalarAnalogModelBase::ignorePartialInterference protected
Referenced by computeNoise(), and initialize().
The documentation for this class was generated from the following files:
ScalarAnalogModelBase.h
ScalarAnalogModelBase.cc