INET Framework for OMNeT++/OMNEST: inet::Ipv6FragmentHeader Class Reference
inet::Ipv6FragmentHeader Class Reference
Class generated from inet/networklayer/ipv6/Ipv6ExtensionHeaders.msg:69 by opp_msgtool.
#include <Ipv6ExtensionHeaders_m.h>
Public Member Functions
Ipv6FragmentHeader ()
Ipv6FragmentHeader (const Ipv6FragmentHeader &other)
virtual ~Ipv6FragmentHeader ()
Ipv6FragmentHeader & operator= (const Ipv6FragmentHeader &other)
virtual Ipv6FragmentHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getFragmentOffset () const
virtual void setFragmentOffset (uint16_t fragmentOffset)
virtual uint8_t getReserved () const
virtual void setReserved (uint8_t reserved)
virtual bool getMoreFragments () const
virtual void setMoreFragments (bool moreFragments)
virtual uint32_t getIdentification () const
virtual void setIdentification (uint32_t identification)
Public Member Functions inherited from inet::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Ipv6ExtensionHeader (const Ipv6ExtensionHeader &other)
virtual ~Ipv6ExtensionHeader ()
Ipv6ExtensionHeader & operator= (const Ipv6ExtensionHeader &other)
virtual uint8_t getExtensionType () const
virtual void setExtensionType (uint8_t extensionType)
virtual B getByteLength () const
virtual void setByteLength (B byteLength)
int getOrder () const
Protected Member Functions
bool operator== (const Ipv6FragmentHeader &)=delete
Protected Member Functions inherited from inet::Ipv6ExtensionHeader
bool operator== (const Ipv6ExtensionHeader &)=delete
Protected Attributes
uint16_t fragmentOffset = 0
uint8_t reserved = 0
bool moreFragments = false
uint32_t identification = 0
Protected Attributes inherited from inet::Ipv6ExtensionHeader
uint8_t extensionType = 0
B byteLength = B(0)
Private Member Functions
void copy (const Ipv6FragmentHeader &other)
Detailed Description
Class generated from inet/networklayer/ipv6/Ipv6ExtensionHeaders.msg:69 by opp_msgtool.
//
// Fragment Header
// RFC 2460 Section 4.5
// Next Header Value: 44
//
class Ipv6FragmentHeader extends Ipv6ExtensionHeader
{
    extensionType = IP_PROT_IPv6EXT_FRAGMENT;
    byteLength = IPv6_FRAGMENT_HEADER_LENGTH;
    uint16_t fragmentOffset;    // @bit(13), divided by 8
    uint8_t reserved = 0;    // @bit(2)
    bool moreFragments; //Is this the last fragment?
    uint32_t identification;  // datagram ID: identifies which datagram this fragment belongs to.
}
Constructor & Destructor Documentation
Ipv6FragmentHeader() [1/2]
inet::Ipv6FragmentHeader::Ipv6FragmentHeader ()
Ipv6FragmentHeader() [2/2]
inet::Ipv6FragmentHeader::Ipv6FragmentHeader (const Ipv6FragmentHeader & other)
~Ipv6FragmentHeader()
virtual inet::Ipv6FragmentHeader::~Ipv6FragmentHeader () virtual
Member Function Documentation
copy()
void inet::Ipv6FragmentHeader::copy (const Ipv6FragmentHeader & other) private
dup()
virtual Ipv6FragmentHeader* inet::Ipv6FragmentHeader::dup () const inline override virtual
Reimplemented from inet::Ipv6ExtensionHeader.
 {return new Ipv6FragmentHeader(*this);}
getFragmentOffset()
virtual uint16_t inet::Ipv6FragmentHeader::getFragmentOffset () const virtual
Referenced by inet::Ipv6FragBuf::addFragment(), inet::Ipv6::localDeliver(), inet::Ipv6ProtocolPrinter::print(), and inet::Ipv6HeaderSerializer::serialize().
getIdentification()
virtual uint32_t inet::Ipv6FragmentHeader::getIdentification () const virtual
Referenced by inet::Ipv6FragBuf::addFragment(), inet::Ipv6ProtocolPrinter::print(), and inet::Ipv6HeaderSerializer::serialize().
getMoreFragments()
virtual bool inet::Ipv6FragmentHeader::getMoreFragments () const virtual
Referenced by inet::Ipv6FragBuf::addFragment(), inet::Ipv6ProtocolPrinter::print(), and inet::Ipv6HeaderSerializer::serialize().
getReserved()
virtual uint8_t inet::Ipv6FragmentHeader::getReserved () const virtual
Referenced by inet::Ipv6HeaderSerializer::serialize().
operator=()
Ipv6FragmentHeader& inet::Ipv6FragmentHeader::operator= (const Ipv6FragmentHeader & other)
operator==()
bool inet::Ipv6FragmentHeader::operator== (const Ipv6FragmentHeader &) protected delete
parsimPack()
virtual void inet::Ipv6FragmentHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::Ipv6ExtensionHeader.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6FragmentHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::Ipv6ExtensionHeader.
Referenced by inet::doParsimUnpacking().
setFragmentOffset()
virtual void inet::Ipv6FragmentHeader::setFragmentOffset (uint16_t fragmentOffset) virtual
Referenced by inet::Ipv6HeaderSerializer::deserialize().
setIdentification()
virtual void inet::Ipv6FragmentHeader::setIdentification (uint32_t identification) virtual
Referenced by inet::Ipv6HeaderSerializer::deserialize().
setMoreFragments()
virtual void inet::Ipv6FragmentHeader::setMoreFragments (bool moreFragments) virtual
Referenced by inet::Ipv6HeaderSerializer::deserialize().
setReserved()
virtual void inet::Ipv6FragmentHeader::setReserved (uint8_t reserved) virtual
Referenced by inet::Ipv6HeaderSerializer::deserialize().
Member Data Documentation
fragmentOffset
uint16_t inet::Ipv6FragmentHeader::fragmentOffset = 0 protected
identification
uint32_t inet::Ipv6FragmentHeader::identification = 0 protected
moreFragments
bool inet::Ipv6FragmentHeader::moreFragments = false protected
reserved
uint8_t inet::Ipv6FragmentHeader::reserved = 0 protected
The documentation for this class was generated from the following file:
Ipv6ExtensionHeaders_m.h