INET Framework for OMNeT++/OMNEST: inet::bgp::BgpUpdatePathAttributes Class Reference
inet::bgp::BgpUpdatePathAttributes Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:114 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpUpdatePathAttributes ()
BgpUpdatePathAttributes (const BgpUpdatePathAttributes &other)
virtual ~BgpUpdatePathAttributes ()
BgpUpdatePathAttributes & operator= (const BgpUpdatePathAttributes &other)
virtual BgpUpdatePathAttributes * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getOptionalBit () const
virtual void setOptionalBit (bool optionalBit)
virtual bool getTransitiveBit () const
virtual void setTransitiveBit (bool transitiveBit)
virtual bool getPartialBit () const
virtual void setPartialBit (bool partialBit)
virtual bool getExtendedLengthBit () const
virtual void setExtendedLengthBit (bool extendedLengthBit)
virtual unsigned short getReserved () const
virtual void setReserved (unsigned short reserved)
virtual BgpUpdateAttributeTypeCode getTypeCode () const
virtual void setTypeCode (BgpUpdateAttributeTypeCode typeCode)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const BgpUpdatePathAttributes &)=delete
Protected Attributes
bool optionalBit = false
bool transitiveBit = false
bool partialBit = false
bool extendedLengthBit = false
unsigned short reserved = 0
BgpUpdateAttributeTypeCode typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1)
unsigned short length = 0
Private Member Functions
void copy (const BgpUpdatePathAttributes &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:114 by opp_msgtool.
class BgpUpdatePathAttributes extends cObject
{
    @packetData;
    bool optionalBit = false;    // 1 bit, Optional bit. It defines whether the attribute is optional (if set to 1) or well-known (if set to 0).
    bool transitiveBit = false;    // 1 bit, Transitive bit. It defines whether an optional attribute is transitive (if set to 1) or non-transitive (if set to 0). Transitive bit MUST be set to 1 for well-known attributes
    bool partialBit = false;    // 1 bit, Partial bit. It defines whether the information contained in the optional transitive attribute is partial (if set to 1) or complete (if set to 0).  For well-known attributes and for optional non-transitive attributes, the Partial bit MUST be set to 0.
    bool extendedLengthBit = false;    // 1 bit, Extended Length bit. It defines whether the Attribute Length is one octet (if set to 0) or two octets (if set to 1).
    unsigned short reserved = 0;    // 4 bit
    BgpUpdateAttributeTypeCode typeCode;    // 1 octet
    unsigned short length; // 2 octets or just 1 depending on the value of flags.extendedLengthBit
}
Constructor & Destructor Documentation
BgpUpdatePathAttributes() [1/2]
inet::bgp::BgpUpdatePathAttributes::BgpUpdatePathAttributes ()
BgpUpdatePathAttributes() [2/2]
inet::bgp::BgpUpdatePathAttributes::BgpUpdatePathAttributes (const BgpUpdatePathAttributes & other)
~BgpUpdatePathAttributes()
virtual inet::bgp::BgpUpdatePathAttributes::~BgpUpdatePathAttributes () virtual
Member Function Documentation
copy()
void inet::bgp::BgpUpdatePathAttributes::copy (const BgpUpdatePathAttributes & other) private
dup()
virtual BgpUpdatePathAttributes* inet::bgp::BgpUpdatePathAttributes::dup () const inline override virtual
Reimplemented in inet::bgp::BgpUpdatePathAttributesAggregator, inet::bgp::BgpUpdatePathAttributesAtomicAggregate, inet::bgp::BgpUpdatePathAttributesLocalPref, inet::bgp::BgpUpdatePathAttributesMultiExitDisc, inet::bgp::BgpUpdatePathAttributesNextHop, inet::bgp::BgpUpdatePathAttributesAsPath, and inet::bgp::BgpUpdatePathAttributesOrigin.
 {return new BgpUpdatePathAttributes(*this);}
getExtendedLengthBit()
virtual bool inet::bgp::BgpUpdatePathAttributes::getExtendedLengthBit () const virtual
Referenced by inet::bgp::computePathAttributeBytes().
getLength()
virtual unsigned short inet::bgp::BgpUpdatePathAttributes::getLength () const virtual
Referenced by inet::bgp::BgpRouter::printUpdateMessage().
getOptionalBit()
virtual bool inet::bgp::BgpUpdatePathAttributes::getOptionalBit () const virtual
getPartialBit()
virtual bool inet::bgp::BgpUpdatePathAttributes::getPartialBit () const virtual
getReserved()
virtual unsigned short inet::bgp::BgpUpdatePathAttributes::getReserved () const virtual
getTransitiveBit()
virtual bool inet::bgp::BgpUpdatePathAttributes::getTransitiveBit () const virtual
getTypeCode()
virtual BgpUpdateAttributeTypeCode inet::bgp::BgpUpdatePathAttributes::getTypeCode () const virtual
Referenced by inet::bgp::computePathAttributeBytes(), inet::bgp::BgpRouter::decisionProcess(), inet::bgp::BgpRouter::printUpdateMessage(), and inet::bgp::BgpRouter::processMessage().
operator=()
BgpUpdatePathAttributes& inet::bgp::BgpUpdatePathAttributes::operator= (const BgpUpdatePathAttributes & other)
operator==()
bool inet::bgp::BgpUpdatePathAttributes::operator== (const BgpUpdatePathAttributes &) protected delete
parsimPack()
virtual void inet::bgp::BgpUpdatePathAttributes::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::bgp::BgpUpdatePathAttributesAggregator, inet::bgp::BgpUpdatePathAttributesAtomicAggregate, inet::bgp::BgpUpdatePathAttributesLocalPref, inet::bgp::BgpUpdatePathAttributesMultiExitDisc, inet::bgp::BgpUpdatePathAttributesNextHop, inet::bgp::BgpUpdatePathAttributesAsPath, and inet::bgp::BgpUpdatePathAttributesOrigin.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpUpdatePathAttributes::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::bgp::BgpUpdatePathAttributesAggregator, inet::bgp::BgpUpdatePathAttributesAtomicAggregate, inet::bgp::BgpUpdatePathAttributesLocalPref, inet::bgp::BgpUpdatePathAttributesMultiExitDisc, inet::bgp::BgpUpdatePathAttributesNextHop, inet::bgp::BgpUpdatePathAttributesAsPath, and inet::bgp::BgpUpdatePathAttributesOrigin.
Referenced by inet::bgp::doParsimUnpacking().
setExtendedLengthBit()
virtual void inet::bgp::BgpUpdatePathAttributes::setExtendedLengthBit (bool extendedLengthBit) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setLength()
virtual void inet::bgp::BgpUpdatePathAttributes::setLength (unsigned short length) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setOptionalBit()
virtual void inet::bgp::BgpUpdatePathAttributes::setOptionalBit (bool optionalBit) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setPartialBit()
virtual void inet::bgp::BgpUpdatePathAttributes::setPartialBit (bool partialBit) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setReserved()
virtual void inet::bgp::BgpUpdatePathAttributes::setReserved (unsigned short reserved) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setTransitiveBit()
virtual void inet::bgp::BgpUpdatePathAttributes::setTransitiveBit (bool transitiveBit) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setTypeCode()
virtual void inet::bgp::BgpUpdatePathAttributes::setTypeCode (BgpUpdateAttributeTypeCode typeCode) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
extendedLengthBit
bool inet::bgp::BgpUpdatePathAttributes::extendedLengthBit = false protected
length
unsigned short inet::bgp::BgpUpdatePathAttributes::length = 0 protected
optionalBit
bool inet::bgp::BgpUpdatePathAttributes::optionalBit = false protected
partialBit
bool inet::bgp::BgpUpdatePathAttributes::partialBit = false protected
reserved
unsigned short inet::bgp::BgpUpdatePathAttributes::reserved = 0 protected
transitiveBit
bool inet::bgp::BgpUpdatePathAttributes::transitiveBit = false protected
typeCode
BgpUpdateAttributeTypeCode inet::bgp::BgpUpdatePathAttributes::typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1) protected
The documentation for this class was generated from the following file:
BgpHeader_m.h