INET Framework for OMNeT++/OMNEST: inet::visualizer::SceneVisualizerBase Class Reference
inet::visualizer::SceneVisualizerBase Class Reference
#include <SceneVisualizerBase.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual Box getSceneBounds ()
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes
Coord sceneMin
Coord sceneMax
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
getSceneBounds()
Box inet::visualizer::SceneVisualizerBase::getSceneBounds () protected virtual
 {
     Coord min;
     Coord max;
     auto physicalEnvironment = findModuleFromPar<IPhysicalEnvironment>(par("physicalEnvironmentModule"), this);
     if (physicalEnvironment == nullptr) {
         auto displayString = visualizationTargetModule->getDisplayString();
         auto width = atof(displayString.getTagArg("bgb", 0));
         auto height = atof(displayString.getTagArg("bgb", 1));
         min = Coord(0.0, 0.0, 0.0);
         max = Coord(width, height, 0.0);
     }
     else {
         min = physicalEnvironment->getSpaceMin();
         max = physicalEnvironment->getSpaceMax();
     }
     for (int id = 0; id <= getSimulation()->getLastComponentId(); id++) {
         auto mobility = dynamic_cast<IMobility *>(getSimulation()->getModule(id));
         if (mobility != nullptr) {
             min = mobility->getConstraintAreaMin().min(min);
             max = mobility->getConstraintAreaMax().max(max);
         }
     }
     min = sceneMin.min(min);
     max = sceneMax.max(max);
     return Box(min, max);
 }
Referenced by inet::visualizer::SceneOsgVisualizerBase::initializeSceneFloor().
initialize()
void inet::visualizer::SceneVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::OpenStreetMapSceneCanvasVisualizer, inet::visualizer::SceneCanvasVisualizer, and inet::visualizer::SceneOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         visualizationTargetModule->getCanvas()->setAnimationSpeed(par("animationSpeed"), this);
         sceneMin.x = par("sceneMinX");
         sceneMin.y = par("sceneMinY");
         sceneMin.z = par("sceneMinZ");
         sceneMax.x = par("sceneMaxX");
         sceneMax.y = par("sceneMaxY");
         sceneMax.z = par("sceneMaxZ");
     }
 }
Referenced by inet::visualizer::SceneOsgVisualizer::initialize(), and inet::visualizer::SceneCanvasVisualizer::initialize().
Member Data Documentation
sceneMax
Coord inet::visualizer::SceneVisualizerBase::sceneMax protected
sceneMin
Coord inet::visualizer::SceneVisualizerBase::sceneMin protected
The documentation for this class was generated from the following files:
SceneVisualizerBase.h
SceneVisualizerBase.cc