INET Framework for OMNeT++/OMNEST: inet::sctp::SctpOutgoingSsnResetRequestParameter Class Reference
inet::sctp::SctpOutgoingSsnResetRequestParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:251 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpOutgoingSsnResetRequestParameter (const char *name=nullptr)
SctpOutgoingSsnResetRequestParameter (const SctpOutgoingSsnResetRequestParameter &other)
virtual ~SctpOutgoingSsnResetRequestParameter ()
SctpOutgoingSsnResetRequestParameter & operator= (const SctpOutgoingSsnResetRequestParameter &other)
virtual SctpOutgoingSsnResetRequestParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSrReqSn () const
virtual void setSrReqSn (uint32_t srReqSn)
virtual uint32_t getSrResSn () const
virtual void setSrResSn (uint32_t srResSn)
virtual uint32_t getLastTsn () const
virtual void setLastTsn (uint32_t lastTsn)
virtual void setStreamNumbersArraySize (size_t size)
virtual size_t getStreamNumbersArraySize () const
virtual uint16_t getStreamNumbers (size_t k) const
virtual void setStreamNumbers (size_t k, uint16_t streamNumbers)
virtual void insertStreamNumbers (size_t k, uint16_t streamNumbers)
void insertStreamNumbers (uint16_t streamNumbers)
virtual void appendStreamNumbers (uint16_t streamNumbers)
virtual void eraseStreamNumbers (size_t k)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpOutgoingSsnResetRequestParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t srReqSn = 0
uint32_t srResSn = 0
uint32_t lastTsn = 0
uint16_t * streamNumbers = nullptr
size_t streamNumbers_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpOutgoingSsnResetRequestParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:251 by opp_msgtool.
class SctpOutgoingSsnResetRequestParameter extends SctpParameter
{
    uint32_t srReqSn; //Stream Reset Request Sequence Number: initialized with the initial TSN, then incremented
    uint32_t srResSn; //Stream Reset Response Sequence Number
    uint32_t lastTsn; //Senders last assigned TSN
    uint16_t streamNumbers[];
}
Constructor & Destructor Documentation
SctpOutgoingSsnResetRequestParameter() [1/2]
inet::sctp::SctpOutgoingSsnResetRequestParameter::SctpOutgoingSsnResetRequestParameter (const char * name = nullptr)
SctpOutgoingSsnResetRequestParameter() [2/2]
inet::sctp::SctpOutgoingSsnResetRequestParameter::SctpOutgoingSsnResetRequestParameter (const SctpOutgoingSsnResetRequestParameter & other)
~SctpOutgoingSsnResetRequestParameter()
virtual inet::sctp::SctpOutgoingSsnResetRequestParameter::~SctpOutgoingSsnResetRequestParameter () virtual
Member Function Documentation
appendStreamNumbers()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::appendStreamNumbers (uint16_t streamNumbers) virtual
copy()
void inet::sctp::SctpOutgoingSsnResetRequestParameter::copy (const SctpOutgoingSsnResetRequestParameter & other) private
dup()
virtual SctpOutgoingSsnResetRequestParameter* inet::sctp::SctpOutgoingSsnResetRequestParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpOutgoingSsnResetRequestParameter(*this);}
Referenced by inet::sctp::SctpAssociation::processOutgoingResetRequestArrived().
eraseStreamNumbers()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::eraseStreamNumbers (size_t k) virtual
getLastTsn()
virtual uint32_t inet::sctp::SctpOutgoingSsnResetRequestParameter::getLastTsn () const virtual
Referenced by inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSrReqSn()
virtual uint32_t inet::sctp::SctpOutgoingSsnResetRequestParameter::getSrReqSn () const virtual
Referenced by inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpHeaderSerializer::serialize().
getSrResSn()
virtual uint32_t inet::sctp::SctpOutgoingSsnResetRequestParameter::getSrResSn () const virtual
Referenced by inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getStreamNumbers()
virtual uint16_t inet::sctp::SctpOutgoingSsnResetRequestParameter::getStreamNumbers (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), and inet::sctp::SctpHeaderSerializer::serialize().
getStreamNumbersArraySize()
virtual size_t inet::sctp::SctpOutgoingSsnResetRequestParameter::getStreamNumbersArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
insertStreamNumbers() [1/2]
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::insertStreamNumbers (size_t k, uint16_t streamNumbers) virtual
insertStreamNumbers() [2/2]
void inet::sctp::SctpOutgoingSsnResetRequestParameter::insertStreamNumbers (uint16_t streamNumbers) inline
 {appendStreamNumbers(streamNumbers);}
operator=()
SctpOutgoingSsnResetRequestParameter& inet::sctp::SctpOutgoingSsnResetRequestParameter::operator= (const SctpOutgoingSsnResetRequestParameter & other)
operator==()
bool inet::sctp::SctpOutgoingSsnResetRequestParameter::operator== (const SctpOutgoingSsnResetRequestParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setLastTsn()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::setLastTsn (uint32_t lastTsn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendOutgoingResetRequest().
setSrReqSn()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::setSrReqSn (uint32_t srReqSn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendOutgoingResetRequest().
setSrResSn()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::setSrResSn (uint32_t srResSn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendOutgoingResetRequest().
setStreamNumbers()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::setStreamNumbers (size_t k, uint16_t streamNumbers) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendOutgoingResetRequest().
setStreamNumbersArraySize()
virtual void inet::sctp::SctpOutgoingSsnResetRequestParameter::setStreamNumbersArraySize (size_t size) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendOutgoingResetRequest().
Member Data Documentation
lastTsn
uint32_t inet::sctp::SctpOutgoingSsnResetRequestParameter::lastTsn = 0 protected
srReqSn
uint32_t inet::sctp::SctpOutgoingSsnResetRequestParameter::srReqSn = 0 protected
srResSn
uint32_t inet::sctp::SctpOutgoingSsnResetRequestParameter::srResSn = 0 protected
streamNumbers
uint16_t* inet::sctp::SctpOutgoingSsnResetRequestParameter::streamNumbers = nullptr protected
streamNumbers_arraysize
size_t inet::sctp::SctpOutgoingSsnResetRequestParameter::streamNumbers_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h