INET Framework for OMNeT++/OMNEST: inet::queueing::TokenBucket Class Reference
inet::queueing::TokenBucket Class Reference
#include <TokenBucket.h>
Public Member Functions
TokenBucket ()
TokenBucket (double numTokens, double maxNumTokens, double tokenProductionRate, ITokenStorage *excessTokenStorage)
virtual ITokenStorage * getExcessTokenStorage () const
virtual double getNumTokens () const override
virtual void addTokens (double numTokens) override
virtual void removeTokens (double numTokens) override
virtual void addTokenProductionRate (double tokenRate) override
virtual void removeTokenProductionRate (double tokenRate) override
virtual simtime_t getOverflowTime ()
Returns the simulation time when the token bucket becomes full with the current rate of token production.
Public Member Functions inherited from inet::queueing::ITokenStorage
virtual ~ITokenStorage ()
Protected Member Functions
void updateNumTokens ()
Protected Attributes
double numTokens = 0
double maxNumTokens = -1
double tokenProductionRate = 0
double excessTokenProductionRate = 0
ITokenStorage * excessTokenStorage = nullptr
simtime_t lastUpdate
Constructor & Destructor Documentation
TokenBucket() [1/2]
inet::queueing::TokenBucket::TokenBucket () inline
 {}
TokenBucket() [2/2]
inet::queueing::TokenBucket::TokenBucket (double numTokens, double maxNumTokens, double tokenProductionRate, ITokenStorage * excessTokenStorage)
                                                                                                                              :
     maxNumTokens(maxNumTokens),
     tokenProductionRate(tokenProductionRate),
     excessTokenStorage(excessTokenStorage)
 {
     addTokens(numTokens);
 }
Member Function Documentation
addTokenProductionRate()
void inet::queueing::TokenBucket::addTokenProductionRate (double tokenRate) override virtual
Implements inet::queueing::ITokenStorage.
 {
     ASSERT(tokenRate >= 0);
     if (tokenRate > 0) {
         EV_TRACE << " Adding rate: tokenProductionRate = " << tokenProductionRate << ", excessTokenProductionRate = " << excessTokenProductionRate << ", tokenRate = " << tokenRate << std::endl;
         if (numTokens == maxNumTokens) {
             if (excessTokenStorage != nullptr) {
                 ASSERT(tokenProductionRate == excessTokenProductionRate);
                 excessTokenStorage->addTokenProductionRate(tokenRate);
                 excessTokenProductionRate += tokenRate;
             }
         }
         tokenProductionRate += tokenRate;
         ASSERT(tokenProductionRate >= 0);
         EV_TRACE << " Added rate: tokenProductionRate = " << tokenProductionRate << ", excessTokenProductionRate = " << excessTokenProductionRate << ", tokenRate = " << tokenRate << std::endl;
     }
 }
Referenced by inet::queueing::TokenBucketMixin< PacketClassifierBase >::addTokenProductionRate().
addTokens()
void inet::queueing::TokenBucket::addTokens (double numTokens) override virtual
Implements inet::queueing::ITokenStorage.
 {
     ASSERT(addedNumTokens >= 0);
     if (addedNumTokens > 0) {
         EV_TRACE << " Adding tokens: numTokens = " << numTokens << ", addedNumTokens = " << addedNumTokens << std::endl;
         numTokens += addedNumTokens;
         if (maxNumTokens > 0 && numTokens >= maxNumTokens) {
             if (excessTokenStorage != nullptr) {
                 excessTokenStorage->addTokens(numTokens - maxNumTokens);
                 excessTokenStorage->addTokenProductionRate(tokenProductionRate - excessTokenProductionRate);
                 excessTokenProductionRate = tokenProductionRate;
             }
             numTokens = maxNumTokens;
         }
         EV_TRACE << " Added tokens: numTokens = " << numTokens << ", addedNumTokens = " << addedNumTokens << std::endl;
     }
 }
Referenced by inet::queueing::TokenBucketMixin< PacketClassifierBase >::addTokens(), TokenBucket(), and updateNumTokens().
getExcessTokenStorage()
virtual ITokenStorage* inet::queueing::TokenBucket::getExcessTokenStorage () const inline virtual
 { return excessTokenStorage; }
Referenced by inet::queueing::TokenBucketMixin< PacketClassifierBase >::rescheduleOverflowTimer().
getNumTokens()
double inet::queueing::TokenBucket::getNumTokens () const override virtual
Implements inet::queueing::ITokenStorage.
 {
     const_cast<TokenBucket*>(this)->updateNumTokens();
     return numTokens;
 }
Referenced by inet::queueing::TokenBucketMixin< PacketClassifierBase >::addTokens(), inet::queueing::TokenBucketClassifier::classifyPacket(), inet::queueing::TokenBucketMixin< PacketClassifierBase >::getNumTokens(), getOverflowTime(), inet::queueing::TokenBucketMixin< PacketClassifierBase >::handleMessage(), inet::queueing::TokenBucketMeter::meterPacket(), inet::queueing::operator<<(), inet::queueing::TokenBucketMixin< PacketClassifierBase >::removeTokens(), and inet::queueing::TokenBucketMixin< PacketClassifierBase >::resolveDirective().
getOverflowTime()
simtime_t inet::queueing::TokenBucket::getOverflowTime () virtual
Returns the simulation time when the token bucket becomes full with the current rate of token production.
 {
     double numTokens = getNumTokens();
     if (maxNumTokens > 0 && maxNumTokens != numTokens) {
         simtime_t overflowTime = simTime() + (maxNumTokens - numTokens) / tokenProductionRate;
         return SimTime::fromRaw(overflowTime.raw() + 1);
     }
     else
         return -1;
 }
Referenced by inet::queueing::TokenBucketMixin< PacketClassifierBase >::rescheduleOverflowTimer().
removeTokenProductionRate()
void inet::queueing::TokenBucket::removeTokenProductionRate (double tokenRate) override virtual
Implements inet::queueing::ITokenStorage.
 {
     ASSERT(tokenRate >= 0);
     if (tokenRate > 0) {
         EV_TRACE << " Removing rate: tokenProductionRate = " << tokenProductionRate << ", excessTokenProductionRate = " << excessTokenProductionRate << ", tokenRate = " << tokenRate << std::endl;
         if (numTokens == maxNumTokens) {
             if (excessTokenStorage != nullptr) {
                 ASSERT(tokenProductionRate == excessTokenProductionRate);
                 excessTokenStorage->removeTokenProductionRate(tokenRate);
                 excessTokenProductionRate -= tokenRate;
             }
         }
         tokenProductionRate -= tokenRate;
         ASSERT(tokenProductionRate >= 0);
         EV_TRACE << " Removed rate: tokenProductionRate = " << tokenProductionRate << ", excessTokenProductionRate = " << excessTokenProductionRate << ", tokenRate = " << tokenRate << std::endl;
     }
 }
Referenced by inet::queueing::TokenBucketMixin< PacketClassifierBase >::removeTokenProductionRate().
removeTokens()
void inet::queueing::TokenBucket::removeTokens (double numTokens) override virtual
Implements inet::queueing::ITokenStorage.
 {
     ASSERT(removedNumTokens >= 0);
     if (removedNumTokens > 0) {
         EV_TRACE << " Removing tokens: numTokens = " << numTokens << ", removedNumTokens = " << removedNumTokens << std::endl;
         if (numTokens == maxNumTokens && excessTokenStorage != nullptr) {
             ASSERT(tokenProductionRate == excessTokenProductionRate);
             excessTokenStorage->removeTokenProductionRate(excessTokenProductionRate);
             excessTokenProductionRate = 0;
         }
         if (numTokens < removedNumTokens)
             throw cRuntimeError("Insufficient number of tokens");
         numTokens -= removedNumTokens;
         EV_TRACE << " Removed tokens: numTokens = " << numTokens << ", removedNumTokens = " << removedNumTokens << std::endl;
     }
 }
Referenced by inet::queueing::TokenBucketClassifier::classifyPacket(), inet::queueing::TokenBucketMeter::meterPacket(), and inet::queueing::TokenBucketMixin< PacketClassifierBase >::removeTokens().
updateNumTokens()
void inet::queueing::TokenBucket::updateNumTokens () protected
 {
     simtime_t now = simTime();
     simtime_t elapsedTime = now - lastUpdate;
     addTokens(tokenProductionRate * elapsedTime.dbl());
     lastUpdate = now;
 }
Referenced by getNumTokens().
Member Data Documentation
excessTokenProductionRate
double inet::queueing::TokenBucket::excessTokenProductionRate = 0 protected
Referenced by addTokenProductionRate(), addTokens(), removeTokenProductionRate(), and removeTokens().
excessTokenStorage
ITokenStorage* inet::queueing::TokenBucket::excessTokenStorage = nullptr protected
Referenced by addTokenProductionRate(), addTokens(), removeTokenProductionRate(), and removeTokens().
lastUpdate
simtime_t inet::queueing::TokenBucket::lastUpdate protected
Referenced by updateNumTokens().
maxNumTokens
double inet::queueing::TokenBucket::maxNumTokens = -1 protected
Referenced by addTokenProductionRate(), addTokens(), getOverflowTime(), removeTokenProductionRate(), and removeTokens().
numTokens
double inet::queueing::TokenBucket::numTokens = 0 protected
Referenced by addTokenProductionRate(), addTokens(), getNumTokens(), getOverflowTime(), removeTokenProductionRate(), removeTokens(), and TokenBucket().
tokenProductionRate
double inet::queueing::TokenBucket::tokenProductionRate = 0 protected
Referenced by addTokenProductionRate(), addTokens(), getOverflowTime(), removeTokenProductionRate(), removeTokens(), and updateNumTokens().
The documentation for this class was generated from the following files:
TokenBucket.h
TokenBucket.cc