INET Framework for OMNeT++/OMNEST: inet::visualizer::InterfaceFilter Class Reference
inet::visualizer::InterfaceFilter Class Reference
This class provides a generic filter for interfaces.
#include <InterfaceFilter.h>
Public Member Functions
void setPattern (const char *pattern)
bool matches (const NetworkInterface *networkInterface) const
Protected Attributes
cMatchExpression matchExpression
Detailed Description
This class provides a generic filter for interfaces.
The filter is expressed as a pattern using the cMatchExpression format.
Member Function Documentation
matches()
bool inet::visualizer::InterfaceFilter::matches (const NetworkInterface * networkInterface) const
 {
     MatchableObject matchableObject(MatchableObject::ATTRIBUTE_FULLNAME, networkInterface);
     return matchExpression.matches(&matchableObject);
 }
Referenced by inet::visualizer::InterfaceTableVisualizerBase::addAllInterfaceVisualizations(), inet::visualizer::InterfaceTableVisualizerBase::receiveSignal(), inet::visualizer::LinkVisualizerBase::receiveSignal(), and inet::visualizer::PacketDropVisualizerBase::receiveSignal().
setPattern()
void inet::visualizer::InterfaceFilter::setPattern (const char * pattern)
 {
     matchExpression.setPattern(pattern, false, true, true);
 }
Referenced by inet::visualizer::Ieee80211VisualizerBase::handleParameterChange(), inet::visualizer::LinkBreakVisualizerBase::handleParameterChange(), inet::visualizer::InterfaceTableVisualizerBase::handleParameterChange(), inet::visualizer::LinkVisualizerBase::handleParameterChange(), inet::visualizer::PacketDropVisualizerBase::handleParameterChange(), inet::visualizer::Ieee80211VisualizerBase::initialize(), inet::visualizer::LinkBreakVisualizerBase::initialize(), inet::visualizer::InterfaceTableVisualizerBase::initialize(), inet::visualizer::LinkVisualizerBase::initialize(), and inet::visualizer::PacketDropVisualizerBase::initialize().
Member Data Documentation
matchExpression
cMatchExpression inet::visualizer::InterfaceFilter::matchExpression protected
Referenced by matches(), and setPattern().
The documentation for this class was generated from the following files:
InterfaceFilter.h
InterfaceFilter.cc