INET Framework for OMNeT++/OMNEST: inet::TcpAppBase Class Reference
inet::TcpAppBase Class Reference abstract
Base class for clients app for TCP-based request-reply protocols or apps.
#include <TcpAppBase.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual int numInitStages () const override
virtual void handleMessageWhenUp (cMessage *msg) override
virtual void finish () override
virtual void refreshDisplay () const override
virtual void connect ()
virtual void close ()
virtual void sendPacket (Packet *pkt)
virtual void handleTimer (cMessage *msg)=0
virtual void socketDataArrived (TcpSocket *socket, Packet *msg, bool urgent) override
Notifies about data arrival, packet ownership is transferred to the callee.
virtual void socketAvailable (TcpSocket *socket, TcpAvailableInfo *availableInfo) override
virtual void socketEstablished (TcpSocket *socket) override
virtual void socketPeerClosed (TcpSocket *socket) override
virtual void socketClosed (TcpSocket *socket) override
virtual void socketFailure (TcpSocket *socket, int code) override
virtual void socketStatusArrived (TcpSocket *socket, TcpStatusInfo *status) override
virtual void socketDeleted (TcpSocket *socket) override
Protected Member Functions inherited from inet::ApplicationBase
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void handleStartOperation (LifecycleOperation *operation)=0
virtual void handleStopOperation (LifecycleOperation *operation)=0
virtual void handleCrashOperation (LifecycleOperation *operation)=0
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
TcpSocket socket
int numSessions
int numBroken
int packetsSent
int packetsRcvd
int bytesSent
int bytesRcvd
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Static Protected Attributes
static simsignal_t connectSignal = registerSignal("connect")
Additional Inherited Members
Public Member Functions inherited from inet::ApplicationBase
ApplicationBase ()
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::TcpSocket::ICallback
virtual ~ICallback ()
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Detailed Description
Base class for clients app for TCP-based request-reply protocols or apps.
Handles a single session (and TCP connection) at a time.
It needs the following NED parameters: localAddress, localPort, connectAddress, connectPort.
Member Function Documentation
close()
void inet::TcpAppBase::close () protected virtual
Reimplemented in inet::TcpBasicClientApp.
 {
     EV_INFO << "issuing CLOSE command\n";
     socket.close();
     emit(connectSignal, -1L);
 }
Referenced by inet::TcpBasicClientApp::close(), inet::TelnetApp::handleStopOperation(), inet::TcpSessionApp::handleStopOperation(), inet::TelnetApp::handleTimer(), inet::TcpSessionApp::handleTimer(), and socketPeerClosed().
connect()
void inet::TcpAppBase::connect () protected virtual
 {
     // we need a new connId if this is not the first connection
     socket.renewSocket();
     const char *localAddress = par("localAddress");
     int localPort = par("localPort");
     socket.bind(*localAddress ? L3AddressResolver().resolve(localAddress) : L3Address(), localPort);
     int timeToLive = par("timeToLive");
     if (timeToLive != -1)
         socket.setTimeToLive(timeToLive);
     int dscp = par("dscp");
     if (dscp != -1)
         socket.setDscp(dscp);
     int tos = par("tos");
     if (tos != -1)
         socket.setTos(tos);
     // connect
     const char *connectAddress = par("connectAddress");
     int connectPort = par("connectPort");
     L3Address destination;
     L3AddressResolver().tryResolve(connectAddress, destination);
     if (destination.isUnspecified()) {
         EV_ERROR << "Connecting to " << connectAddress << " port=" << connectPort << ": cannot resolve destination address\n";
     }
     else {
         EV_INFO << "Connecting to " << connectAddress << "(" << destination << ") port=" << connectPort << endl;
         socket.connect(destination, connectPort);
         numSessions++;
         emit(connectSignal, 1L);
     }
 }
Referenced by inet::TelnetApp::handleTimer(), inet::TcpBasicClientApp::handleTimer(), and inet::TcpSessionApp::handleTimer().
finish()
void inet::TcpAppBase::finish () override protected virtual
Reimplemented in inet::TcpSessionApp.
 {
     std::string modulePath = getFullPath();
     EV_INFO << modulePath << ": opened " << numSessions << " sessions\n";
     EV_INFO << modulePath << ": sent " << bytesSent << " bytes in " << packetsSent << " packets\n";
     EV_INFO << modulePath << ": received " << bytesRcvd << " bytes in " << packetsRcvd << " packets\n";
 }
handleMessageWhenUp()
void inet::TcpAppBase::handleMessageWhenUp (cMessage * msg) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
     if (msg->isSelfMessage())
         handleTimer(msg);
     else
         socket.processMessage(msg);
 }
handleTimer()
virtual void inet::TcpAppBase::handleTimer (cMessage * msg) protected pure virtual
Implemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
Referenced by handleMessageWhenUp().
initialize()
void inet::TcpAppBase::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
 {
     ApplicationBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         numSessions = numBroken = packetsSent = packetsRcvd = bytesSent = bytesRcvd = 0;
         WATCH(numSessions);
         WATCH(numBroken);
         WATCH(packetsSent);
         WATCH(packetsRcvd);
         WATCH(bytesSent);
         WATCH(bytesRcvd);
     }
     else if (stage == INITSTAGE_APPLICATION_LAYER) {
         // parameters
         const char *localAddress = par("localAddress");
         int localPort = par("localPort");
         socket.bind(*localAddress ? L3AddressResolver().resolve(localAddress) : L3Address(), localPort);
         socket.setCallback(this);
         socket.setOutputGate(gate("socketOut"));
     }
 }
Referenced by inet::TelnetApp::initialize(), inet::TcpBasicClientApp::initialize(), and inet::TcpSessionApp::initialize().
numInitStages()
virtual int inet::TcpAppBase::numInitStages () const inline override protected virtual
Reimplemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
 { return NUM_INIT_STAGES; }
refreshDisplay()
void inet::TcpAppBase::refreshDisplay () const override protected virtual
Reimplemented in inet::TcpSessionApp.
 {
     ApplicationBase::refreshDisplay();
     getDisplayString().setTagArg("t", 0, TcpSocket::stateName(socket.getState()));
 }
Referenced by inet::TcpSessionApp::refreshDisplay().
sendPacket()
void inet::TcpAppBase::sendPacket (Packet * pkt) protected virtual
 {
     int numBytes = msg->getByteLength();
     emit(packetSentSignal, msg);
     socket.send(msg);
     packetsSent++;
     bytesSent += numBytes;
 }
Referenced by inet::TcpSessionApp::sendData(), inet::TelnetApp::sendGenericAppMsg(), and inet::TcpBasicClientApp::sendRequest().
socketAvailable()
virtual void inet::TcpAppBase::socketAvailable (TcpSocket * socket, TcpAvailableInfo * availableInfo) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { socket->accept(availableInfo->getNewSocketId()); }
socketClosed()
void inet::TcpAppBase::socketClosed (TcpSocket * socket) override protected virtual
Implements inet::TcpSocket::ICallback.
Reimplemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
 {
     // *redefine* to start another session etc.
     EV_INFO << "connection closed\n";
 }
Referenced by inet::TelnetApp::socketClosed(), inet::TcpBasicClientApp::socketClosed(), and inet::TcpSessionApp::socketClosed().
socketDataArrived()
void inet::TcpAppBase::socketDataArrived (TcpSocket * socket, Packet * packet, bool urgent) override protected virtual
Notifies about data arrival, packet ownership is transferred to the callee.
Implements inet::TcpSocket::ICallback.
Reimplemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
 {
     // *redefine* to perform or schedule next sending
     packetsRcvd++;
     bytesRcvd += msg->getByteLength();
     emit(packetReceivedSignal, msg);
     delete msg;
 }
Referenced by inet::TelnetApp::socketDataArrived(), inet::TcpBasicClientApp::socketDataArrived(), and inet::TcpSessionApp::socketDataArrived().
socketDeleted()
virtual void inet::TcpAppBase::socketDeleted (TcpSocket * socket) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 {}
socketEstablished()
void inet::TcpAppBase::socketEstablished (TcpSocket * socket) override protected virtual
Implements inet::TcpSocket::ICallback.
Reimplemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
 {
     // *redefine* to perform or schedule first sending
     EV_INFO << "connected\n";
 }
Referenced by inet::TelnetApp::socketEstablished(), inet::TcpBasicClientApp::socketEstablished(), and inet::TcpSessionApp::socketEstablished().
socketFailure()
void inet::TcpAppBase::socketFailure (TcpSocket * socket, int code) override protected virtual
Implements inet::TcpSocket::ICallback.
Reimplemented in inet::TcpSessionApp, inet::TcpBasicClientApp, and inet::TelnetApp.
 {
     // subclasses may override this function, and add code try to reconnect after a delay.
     EV_WARN << "connection broken\n";
     numBroken++;
 }
Referenced by inet::TelnetApp::socketFailure(), inet::TcpBasicClientApp::socketFailure(), and inet::TcpSessionApp::socketFailure().
socketPeerClosed()
void inet::TcpAppBase::socketPeerClosed (TcpSocket * socket) override protected virtual
Implements inet::TcpSocket::ICallback.
 {
     ASSERT(socket_ == &socket);
     // close the connection (if not already closed)
     if (socket.getState() == TcpSocket::PEER_CLOSED) {
         EV_INFO << "remote TCP closed, closing here as well\n";
         close();
     }
 }
socketStatusArrived()
virtual void inet::TcpAppBase::socketStatusArrived (TcpSocket * socket, TcpStatusInfo * status) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 {}
Member Data Documentation
bytesRcvd
int inet::TcpAppBase::bytesRcvd protected
Referenced by finish(), inet::TcpSessionApp::finish(), initialize(), inet::TcpSessionApp::refreshDisplay(), and socketDataArrived().
bytesSent
int inet::TcpAppBase::bytesSent protected
Referenced by inet::TcpSessionApp::createDataPacket(), finish(), inet::TcpSessionApp::finish(), initialize(), inet::TcpSessionApp::refreshDisplay(), and sendPacket().
connectSignal
simsignal_t inet::TcpAppBase::connectSignal = registerSignal("connect") static protected
Referenced by close(), and connect().
numBroken
int inet::TcpAppBase::numBroken protected
Referenced by initialize(), and socketFailure().
numSessions
int inet::TcpAppBase::numSessions protected
Referenced by connect(), finish(), and initialize().
packetsRcvd
int inet::TcpAppBase::packetsRcvd protected
Referenced by finish(), inet::TcpSessionApp::finish(), initialize(), and socketDataArrived().
packetsSent
int inet::TcpAppBase::packetsSent protected
Referenced by finish(), initialize(), and sendPacket().
socket
TcpSocket inet::TcpAppBase::socket protected
Referenced by close(), connect(), inet::TelnetApp::handleCrashOperation(), inet::TcpBasicClientApp::handleCrashOperation(), inet::TcpSessionApp::handleCrashOperation(), handleMessageWhenUp(), inet::TelnetApp::handleStopOperation(), inet::TcpBasicClientApp::handleStopOperation(), inet::TcpSessionApp::handleStopOperation(), initialize(), refreshDisplay(), inet::TcpSessionApp::refreshDisplay(), sendPacket(), inet::TelnetApp::socketClosed(), inet::TcpBasicClientApp::socketClosed(), inet::TcpSessionApp::socketClosed(), inet::TelnetApp::socketDataArrived(), inet::TcpBasicClientApp::socketDataArrived(), inet::TcpSessionApp::socketDataArrived(), inet::TelnetApp::socketEstablished(), inet::TcpBasicClientApp::socketEstablished(), inet::TcpSessionApp::socketEstablished(), inet::TelnetApp::socketFailure(), inet::TcpBasicClientApp::socketFailure(), inet::TcpSessionApp::socketFailure(), and socketPeerClosed().
The documentation for this class was generated from the following files:
TcpAppBase.h
TcpAppBase.cc