INET Framework for OMNeT++/OMNEST: inet::LabeledLineFigure Class Reference
inet::LabeledLineFigure Class Reference
#include <LabeledLineFigure.h>
Public Member Functions
LabeledLineFigure (const char *name=nullptr)
cLineFigure * getLineFigure () const
cTextFigure * getLabelFigure () const
void setStart (cFigure::Point point)
void setEnd (cFigure::Point point)
Protected Member Functions
void updateLabelPosition ()
Protected Attributes
cLineFigure * lineFigure
cPanelFigure * panelFigure
cTextFigure * labelFigure
Constructor & Destructor Documentation
LabeledLineFigure()
inet::LabeledLineFigure::LabeledLineFigure (const char * name = nullptr)
                                                      :
     cGroupFigure(name)
 {
     lineFigure = new cLineFigure("line");
     panelFigure = new cPanelFigure("panel");
     addFigure(lineFigure);
     addFigure(panelFigure);
     labelFigure = new cTextFigure("label");
     labelFigure->setAnchor(cFigure::ANCHOR_S);
     labelFigure->setTags("label");
     labelFigure->setHalo(true);
     panelFigure->addFigure(labelFigure);
 }
Member Function Documentation
getLabelFigure()
cTextFigure* inet::LabeledLineFigure::getLabelFigure () const inline
 { return labelFigure; }
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization(), and inet::visualizer::RoutingTableCanvasVisualizer::refreshRouteVisualization().
getLineFigure()
cLineFigure* inet::LabeledLineFigure::getLineFigure () const inline
 { return lineFigure; }
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization(), inet::visualizer::LinkCanvasVisualizerBase::setAlpha(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::setAlpha().
setEnd()
void inet::LabeledLineFigure::setEnd (cFigure::Point point)
 {
     lineFigure->setEnd(point);
     updateLabelPosition();
 }
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
setStart()
void inet::LabeledLineFigure::setStart (cFigure::Point point)
 {
     lineFigure->setStart(point);
     updateLabelPosition();
 }
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
updateLabelPosition()
void inet::LabeledLineFigure::updateLabelPosition () protected
 {
     auto position = (lineFigure->getStart() + lineFigure->getEnd()) / 2;
     auto direction = lineFigure->getEnd() - lineFigure->getStart();
     double alpha = atan2(-direction.y, direction.x);
     if (alpha > M_PI / 2 || alpha < -M_PI / 2)
         alpha += M_PI;
     panelFigure->setTransform(cFigure::Transform().rotate(-alpha));
     panelFigure->setPosition(position);
     labelFigure->setPosition(cFigure::Point(0, -lineFigure->getLineWidth() / 2));
 }
Referenced by setEnd(), and setStart().
Member Data Documentation
labelFigure
cTextFigure* inet::LabeledLineFigure::labelFigure protected
Referenced by LabeledLineFigure(), and updateLabelPosition().
lineFigure
cLineFigure* inet::LabeledLineFigure::lineFigure protected
Referenced by LabeledLineFigure(), setEnd(), setStart(), and updateLabelPosition().
panelFigure
cPanelFigure* inet::LabeledLineFigure::panelFigure protected
Referenced by LabeledLineFigure(), and updateLabelPosition().
The documentation for this class was generated from the following files:
LabeledLineFigure.h
LabeledLineFigure.cc