INET Framework for OMNeT++/OMNEST: inet::SctpSimpleMessage Class Reference
inet::SctpSimpleMessage Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:106 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpSimpleMessage (const char *name=nullptr)
SctpSimpleMessage (const SctpSimpleMessage &other)
virtual ~SctpSimpleMessage ()
SctpSimpleMessage & operator= (const SctpSimpleMessage &other)
virtual SctpSimpleMessage * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getDataLen () const
virtual void setDataLen (uint32_t dataLen)
virtual void setDataArraySize (size_t size)
virtual size_t getDataArraySize () const
virtual uint8_t getData (size_t k) const
virtual void setData (size_t k, uint8_t data)
virtual void insertData (size_t k, uint8_t data)
void insertData (uint8_t data)
virtual void appendData (uint8_t data)
virtual void eraseData (size_t k)
virtual ::omnetpp::simtime_t getCreationTime () const
virtual void setCreationTime (::omnetpp::simtime_t creationTime)
virtual bool getEncaps () const
virtual void setEncaps (bool encaps)
Protected Member Functions
bool operator== (const SctpSimpleMessage &)=delete
Protected Attributes
uint32_t dataLen = 0
uint8_t * data = nullptr
size_t data_arraysize = 0
::omnetpp::simtime_t creationTime = 0
bool encaps = false
Private Member Functions
void copy (const SctpSimpleMessage &other)
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:106 by opp_msgtool.
class SctpSimpleMessage extends cPacket
{
    uint32_t dataLen;     //TODO remove it, use set/getDataArraySize() functions only
    uint8_t data[];
    simtime_t creationTime = 0;
    bool encaps = false;
}
Constructor & Destructor Documentation
SctpSimpleMessage() [1/2]
inet::SctpSimpleMessage::SctpSimpleMessage (const char * name = nullptr)
SctpSimpleMessage() [2/2]
inet::SctpSimpleMessage::SctpSimpleMessage (const SctpSimpleMessage & other)
~SctpSimpleMessage()
virtual inet::SctpSimpleMessage::~SctpSimpleMessage () virtual
Member Function Documentation
appendData()
virtual void inet::SctpSimpleMessage::appendData (uint8_t data) virtual
copy()
void inet::SctpSimpleMessage::copy (const SctpSimpleMessage & other) private
dup()
virtual SctpSimpleMessage* inet::SctpSimpleMessage::dup () const inline override virtual
Reimplemented in inet::NetPerfMeterDataMessage.
 {return new SctpSimpleMessage(*this);}
eraseData()
virtual void inet::SctpSimpleMessage::eraseData (size_t k) virtual
getCreationTime()
virtual ::omnetpp::simtime_t inet::SctpSimpleMessage::getCreationTime () const
Referenced by inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), and inet::sctp::SctpAssociation::pushUlp().
getData()
virtual uint8_t inet::SctpSimpleMessage::getData (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::pushUlp(), inet::sctp::SctpReceiveStream::reassemble(), and inet::sctp::SctpHeaderSerializer::serialize().
getDataArraySize()
virtual size_t inet::SctpSimpleMessage::getDataArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpReceiveStream::reassemble(), and inet::sctp::SctpHeaderSerializer::serialize().
getDataLen()
virtual uint32_t inet::SctpSimpleMessage::getDataLen () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), inet::sctp::SctpAssociation::pushUlp(), inet::sctp::SctpReceiveStream::reassemble(), inet::sctp::SctpAssociation::sendPacketDrop(), and inet::sctp::SctpHeaderSerializer::serialize().
getEncaps()
virtual bool inet::SctpSimpleMessage::getEncaps () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg().
insertData() [1/2]
virtual void inet::SctpSimpleMessage::insertData (size_t k, uint8_t data) virtual
insertData() [2/2]
void inet::SctpSimpleMessage::insertData (uint8_t data) inline
 {appendData(data);}
operator=()
SctpSimpleMessage& inet::SctpSimpleMessage::operator= (const SctpSimpleMessage & other)
operator==()
bool inet::SctpSimpleMessage::operator== (const SctpSimpleMessage &) protected delete
parsimPack()
virtual void inet::SctpSimpleMessage::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::NetPerfMeterDataMessage.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpSimpleMessage::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::NetPerfMeterDataMessage.
Referenced by inet::doParsimUnpacking().
setCreationTime()
virtual void inet::SctpSimpleMessage::setCreationTime (::omnetpp::simtime_t creationTime) virtual
setData()
virtual void inet::SctpSimpleMessage::setData (size_t k, uint8_t data) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::process_SEND(), inet::sctp::SctpReceiveStream::reassemble(), and inet::sctp::SctpAssociation::sendPacketDrop().
setDataArraySize()
virtual void inet::SctpSimpleMessage::setDataArraySize (size_t size) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::process_SEND(), inet::sctp::SctpReceiveStream::reassemble(), and inet::sctp::SctpAssociation::sendPacketDrop().
setDataLen()
virtual void inet::SctpSimpleMessage::setDataLen (uint32_t dataLen) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::process_SEND(), inet::sctp::SctpReceiveStream::reassemble(), and inet::sctp::SctpAssociation::sendPacketDrop().
setEncaps()
virtual void inet::SctpSimpleMessage::setEncaps (bool encaps) virtual
Referenced by inet::sctp::SctpAssociation::process_SEND(), and inet::sctp::SctpAssociation::sendPacketDrop().
Member Data Documentation
creationTime
::omnetpp::simtime_t inet::SctpSimpleMessage::creationTime = 0 protected
data
uint8_t* inet::SctpSimpleMessage::data = nullptr protected
data_arraysize
size_t inet::SctpSimpleMessage::data_arraysize = 0 protected
dataLen
uint32_t inet::SctpSimpleMessage::dataLen = 0 protected
encaps
bool inet::SctpSimpleMessage::encaps = false protected
The documentation for this class was generated from the following file:
SctpCommand_m.h