INET Framework for OMNeT++/OMNEST: inet::GroupRecord Class Reference
inet::GroupRecord Class Reference
Class generated from inet/networklayer/ipv4/IgmpMessage.msg:104 by opp_msgtool.
#include <IgmpMessage_m.h>
Public Member Functions
GroupRecord ()
GroupRecord (const GroupRecord &other)
virtual ~GroupRecord ()
GroupRecord & operator= (const GroupRecord &other)
virtual void parsimPack (omnetpp::cCommBuffer *b) const
virtual void parsimUnpack (omnetpp::cCommBuffer *b)
virtual int getRecordType () const
virtual void setRecordType (int recordType)
virtual const Ipv4Address & getGroupAddress () const
virtual Ipv4Address & getGroupAddressForUpdate ()
virtual void setGroupAddress (const Ipv4Address &groupAddress)
virtual const Ipv4AddressVector & getSourceList () const
virtual Ipv4AddressVector & getSourceListForUpdate ()
virtual void setSourceList (const Ipv4AddressVector &sourceList)
virtual void setAuxDataArraySize (size_t size)
virtual size_t getAuxDataArraySize () const
virtual uint32_t getAuxData (size_t k) const
virtual void setAuxData (size_t k, uint32_t auxData)
virtual void insertAuxData (size_t k, uint32_t auxData)
void insertAuxData (uint32_t auxData)
virtual void appendAuxData (uint32_t auxData)
virtual void eraseAuxData (size_t k)
Protected Member Functions
bool operator== (const GroupRecord &)=delete
Protected Attributes
int recordType = 0
Ipv4Address groupAddress
Ipv4AddressVector sourceList
uint32_t * auxData = nullptr
size_t auxData_arraysize = 0
Private Member Functions
void copy (const GroupRecord &other)
Detailed Description
Class generated from inet/networklayer/ipv4/IgmpMessage.msg:104 by opp_msgtool.
class GroupRecord
{
    @packetData;
    int recordType @enum(GroupRecordType);
    Ipv4Address groupAddress;
    Ipv4AddressVector sourceList;
    uint32_t auxData[];
}
Constructor & Destructor Documentation
GroupRecord() [1/2]
inet::GroupRecord::GroupRecord ()
GroupRecord() [2/2]
inet::GroupRecord::GroupRecord (const GroupRecord & other)
~GroupRecord()
virtual inet::GroupRecord::~GroupRecord () virtual
Member Function Documentation
appendAuxData()
virtual void inet::GroupRecord::appendAuxData (uint32_t auxData) virtual
copy()
void inet::GroupRecord::copy (const GroupRecord & other) private
eraseAuxData()
virtual void inet::GroupRecord::eraseAuxData (size_t k) virtual
getAuxData()
virtual uint32_t inet::GroupRecord::getAuxData (size_t k) const virtual
Referenced by inet::IgmpHeaderSerializer::serialize().
getAuxDataArraySize()
virtual size_t inet::GroupRecord::getAuxDataArraySize () const virtual
Referenced by inet::IgmpHeaderSerializer::serialize().
getGroupAddress()
virtual const Ipv4Address& inet::GroupRecord::getGroupAddress () const virtual
Referenced by inet::Igmpv3::processReport(), and inet::IgmpHeaderSerializer::serialize().
getGroupAddressForUpdate()
virtual Ipv4Address& inet::GroupRecord::getGroupAddressForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<GroupRecord*>(this)->getGroupAddress());}
getRecordType()
virtual int inet::GroupRecord::getRecordType () const virtual
Referenced by inet::Igmpv3::processReport(), and inet::IgmpHeaderSerializer::serialize().
getSourceList()
virtual const Ipv4AddressVector& inet::GroupRecord::getSourceList () const virtual
Referenced by inet::Igmpv3::processHostGeneralQueryTimer(), and inet::IgmpHeaderSerializer::serialize().
getSourceListForUpdate()
virtual Ipv4AddressVector& inet::GroupRecord::getSourceListForUpdate () inline virtual
 { return const_cast<Ipv4AddressVector&>(const_cast<GroupRecord*>(this)->getSourceList());}
Referenced by inet::IgmpHeaderSerializer::deserialize(), and inet::Igmpv3::processReport().
insertAuxData() [1/2]
virtual void inet::GroupRecord::insertAuxData (size_t k, uint32_t auxData) virtual
insertAuxData() [2/2]
void inet::GroupRecord::insertAuxData (uint32_t auxData) inline
 {appendAuxData(auxData);}
operator=()
GroupRecord& inet::GroupRecord::operator= (const GroupRecord & other)
operator==()
bool inet::GroupRecord::operator== (const GroupRecord &) protected delete
parsimPack()
virtual void inet::GroupRecord::parsimPack (omnetpp::cCommBuffer * b) const virtual
parsimUnpack()
virtual void inet::GroupRecord::parsimUnpack (omnetpp::cCommBuffer * b) virtual
setAuxData()
virtual void inet::GroupRecord::setAuxData (size_t k, uint32_t auxData) virtual
Referenced by inet::IgmpHeaderSerializer::deserialize().
setAuxDataArraySize()
virtual void inet::GroupRecord::setAuxDataArraySize (size_t size) virtual
Referenced by inet::IgmpHeaderSerializer::deserialize().
setGroupAddress()
virtual void inet::GroupRecord::setGroupAddress (const Ipv4Address & groupAddress) virtual
Referenced by inet::IgmpHeaderSerializer::deserialize(), and inet::Igmpv3::processHostGeneralQueryTimer().
setRecordType()
virtual void inet::GroupRecord::setRecordType (int recordType) virtual
Referenced by inet::IgmpHeaderSerializer::deserialize(), and inet::Igmpv3::processHostGeneralQueryTimer().
setSourceList()
virtual void inet::GroupRecord::setSourceList (const Ipv4AddressVector & sourceList) virtual
Referenced by inet::Igmpv3::processHostGeneralQueryTimer().
Member Data Documentation
auxData
uint32_t* inet::GroupRecord::auxData = nullptr protected
auxData_arraysize
size_t inet::GroupRecord::auxData_arraysize = 0 protected
groupAddress
Ipv4Address inet::GroupRecord::groupAddress protected
recordType
int inet::GroupRecord::recordType = 0 protected
sourceList
Ipv4AddressVector inet::GroupRecord::sourceList protected
The documentation for this class was generated from the following file:
IgmpMessage_m.h