INET Framework for OMNeT++/OMNEST: inet::Ieee8022Llc Class Reference
inet::Ieee8022Llc Class Reference
#include <Ieee8022Llc.h>
Classes
struct SocketDescriptor
Public Member Functions
virtual ~Ieee8022Llc ()
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::DefaultProtocolRegistrationListener
virtual void handleRegisterServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyService (cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) override
Static Public Member Functions
static const Protocol * getProtocol (const Ptr< const Ieee8022LlcHeader > &header)
Protected Member Functions
void clearSockets ()
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessageWhenUp (cMessage *message) override
virtual void encapsulate (Packet *frame)
virtual void decapsulate (Packet *frame)
virtual void processPacketFromHigherLayer (Packet *msg)
virtual bool deliverCopyToSockets (Packet *packet)
virtual bool isDeliverableToUpperLayer (Packet *packet)
virtual void processPacketFromMac (Packet *packet)
virtual void processCommandFromHigherLayer (Request *request)
virtual void registerMyProtocol ()
virtual void handleRegisterService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
std::set< const Protocol * > upperProtocols
std::map< int, SocketDescriptor * > socketIdToSocketDescriptor
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Friends
std::ostream & operator<< (std::ostream &o, const SocketDescriptor &t)
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Constructor & Destructor Documentation
~Ieee8022Llc()
inet::Ieee8022Llc::~Ieee8022Llc () virtual
 {
     clearSockets();
 }
Member Function Documentation
clearSockets()
void inet::Ieee8022Llc::clearSockets () protected
 {
     for (auto& elem : socketIdToSocketDescriptor) {
         delete elem.second;
         elem.second = nullptr;
     }
     socketIdToSocketDescriptor.clear();
 }
Referenced by handleCrashOperation(), handleStartOperation(), handleStopOperation(), and ~Ieee8022Llc().
decapsulate()
void inet::Ieee8022Llc::decapsulate (Packet * frame) protected virtual
 {
     const auto& llcHeader = frame->popAtFront<Ieee8022LlcHeader>();
     auto sapInd = frame->addTagIfAbsent<Ieee802SapInd>();
     sapInd->setSsap(llcHeader->getSsap());
     sapInd->setDsap(llcHeader->getDsap());
     // TODO control?
     if (llcHeader->getSsap() == 0xAA && llcHeader->getDsap() == 0xAA && llcHeader->getControl() == 0x03) {
         const auto& snapHeader = dynamicPtrCast<const Ieee8022LlcSnapHeader>(llcHeader);
         if (snapHeader == nullptr)
             throw cRuntimeError("LLC header indicates SNAP header, but SNAP header is missing");
     }
     auto payloadProtocol = getProtocol(llcHeader);
     if (payloadProtocol) {
         frame->addTagIfAbsent<DispatchProtocolReq>()->setProtocol(payloadProtocol);
         frame->addTagIfAbsent<PacketProtocolTag>()->setProtocol(payloadProtocol);
     }
     else {
         frame->removeTagIfPresent<DispatchProtocolReq>();
         frame->removeTagIfPresent<PacketProtocolTag>();
     }
 }
Referenced by processPacketFromMac().
deliverCopyToSockets()
bool inet::Ieee8022Llc::deliverCopyToSockets (Packet * packet) protected virtual
 {
     bool isSent = false;
     if (auto sap = packet->findTag<Ieee802SapInd>()) {
         int localSap = sap->getDsap();
         int remoteSap = sap->getSsap();
         for (const auto& elem : socketIdToSocketDescriptor) {
             if ((elem.second->localSap == localSap || elem.second->localSap == -1)
                 && (elem.second->remoteSap == remoteSap || elem.second->remoteSap == -1))
             {
                 auto *packetCopy = packet->dup();
                 packetCopy->addTagIfAbsent<SocketInd>()->setSocketId(elem.second->socketId);
                 EV_INFO << "Passing up to socket " << elem.second->socketId << "\n";
                 packetCopy->setKind(SOCKET_I_DATA);
                 send(packetCopy, "upperLayerOut");
                 isSent = true;
             }
         }
     }
     return isSent;
 }
Referenced by processPacketFromMac().
encapsulate()
void inet::Ieee8022Llc::encapsulate (Packet * frame) protected virtual
Reimplemented in inet::ieee80211::Ieee80211LlcLpd.
 {
     const auto& sapReq = frame->findTag<Ieee802SapReq>();
     const auto& protocolTag = frame->findTag<PacketProtocolTag>();
     const Protocol *protocol = protocolTag ? protocolTag->getProtocol() : nullptr;
     int ethType = -1;
     int snapOui = -1;
     if (sapReq == nullptr && protocol != nullptr) {
         ethType = ProtocolGroup::ethertype.findProtocolNumber(protocol);
         if (ethType == -1)
             snapOui = ProtocolGroup::snapOui.findProtocolNumber(protocol);
     }
     if (ethType != -1 || snapOui != -1) {
         const auto& snapHeader = makeShared<Ieee8022LlcSnapHeader>();
         if (ethType != -1) {
             snapHeader->setOui(0);
             snapHeader->setProtocolId(ethType);
         }
         else {
             snapHeader->setOui(snapOui);
             snapHeader->setProtocolId(-1); // FIXME get value from a tag (e.g. protocolTag->getSubId() ???)
         }
         frame->insertAtFront(snapHeader);
     }
     else {
         const auto& llcHeader = makeShared<Ieee8022LlcHeader>();
         int sapData = ProtocolGroup::ieee8022protocol.findProtocolNumber(protocol);
         if (sapReq == nullptr && sapData != -1) {
             llcHeader->setSsap((sapData >> 8) & 0xFF);
             llcHeader->setDsap(sapData & 0xFF);
             llcHeader->setControl(3);
         }
         else if (sapReq != nullptr) {
             llcHeader->setSsap(sapReq->getSsap());
             llcHeader->setDsap(sapReq->getDsap());
             llcHeader->setControl(3); // TODO get from sapTag
         }
         else
             throw cRuntimeError("Missing the required Ieee802SapReq for LLC header, or protocol number for SNAP header.");
         frame->insertAtFront(llcHeader);
     }
     frame->addTagIfAbsent<PacketProtocolTag>()->setProtocol(&Protocol::ieee8022llc);
     frame->addTagIfAbsent<DispatchProtocolReq>()->setProtocol(&Protocol::ethernetMac);
 }
Referenced by inet::ieee80211::Ieee80211LlcLpd::encapsulate(), and processPacketFromHigherLayer().
getProtocol()
const Protocol * inet::Ieee8022Llc::getProtocol (const Ptr< const Ieee8022LlcHeader > & header) static
 {
     const Protocol *payloadProtocol = nullptr;
     if (llcHeader->getSsap() == 0xAA && llcHeader->getDsap() == 0xAA && llcHeader->getControl() == 0x03) {
         const auto& snapHeader = dynamicPtrCast<const Ieee8022LlcSnapHeader>(llcHeader);
         if (snapHeader == nullptr)
             throw cRuntimeError("LLC header indicates SNAP header, but SNAP header is missing");
         if (snapHeader->getOui() == 0)
             payloadProtocol = ProtocolGroup::ethertype.findProtocol(snapHeader->getProtocolId());
         else
             payloadProtocol = ProtocolGroup::snapOui.findProtocol(snapHeader->getOui());
     }
     else {
         int32_t sapData = ((llcHeader->getSsap() & 0xFF) << 8) | (llcHeader->getDsap() & 0xFF);
         payloadProtocol = ProtocolGroup::ieee8022protocol.findProtocol(sapData); // do not use getProtocol
     }
     return payloadProtocol;
 }
Referenced by decapsulate(), and inet::Ieee802LlcDissector::dissect().
handleCrashOperation()
void inet::Ieee8022Llc::handleCrashOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
     clearSockets();
 }
handleMessageWhenUp()
void inet::Ieee8022Llc::handleMessageWhenUp (cMessage * message) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
     if (msg->arrivedOn("upperLayerIn")) {
         // from upper layer
         EV_INFO << "Received " << msg << " from upper layer." << endl;
         if (msg->isPacket())
             processPacketFromHigherLayer(check_and_cast<Packet *>(msg));
         else
             processCommandFromHigherLayer(check_and_cast<Request *>(msg));
     }
     else if (msg->arrivedOn("lowerLayerIn")) {
         EV_INFO << "Received " << msg << " from lower layer." << endl;
         processPacketFromMac(check_and_cast<Packet *>(msg));
     }
     else
         throw cRuntimeError("Unknown gate");
 }
handleRegisterProtocol()
void inet::Ieee8022Llc::handleRegisterProtocol (const Protocol & protocol, cGate * gate, ServicePrimitive servicePrimitive) override protected virtual
Reimplemented from inet::DefaultProtocolRegistrationListener.
 {
     Enter_Method("handleRegisterProtocol");
     // KLUDGE this should be here: if (!strcmp("upperLayerOut", gate->getBaseName()))
     // but then the register protocol calls are lost, because they can't go through the traffic conditioner
     upperProtocols.insert(&protocol);
 }
handleRegisterService()
void inet::Ieee8022Llc::handleRegisterService (const Protocol & protocol, cGate * gate, ServicePrimitive servicePrimitive) override protected virtual
Reimplemented from inet::DefaultProtocolRegistrationListener.
 {
     Enter_Method("handleRegisterService");
 }
handleStartOperation()
void inet::Ieee8022Llc::handleStartOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
     clearSockets();
 }
handleStopOperation()
void inet::Ieee8022Llc::handleStopOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
     clearSockets();
 }
initialize()
void inet::Ieee8022Llc::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
 {
     OperationalBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         // TODO parameterization for llc or snap?
     }
     else if (stage == INITSTAGE_LINK_LAYER) {
         if (par("registerProtocol").boolValue()) { // FIXME //KUDGE should redesign place of EthernetEncapsulation and LLC modules
             // register service and protocol
             registerService(Protocol::ieee8022llc, gate("upperLayerIn"), gate("upperLayerOut"));
             registerMyProtocol();
         }
         WATCH_PTRMAP(socketIdToSocketDescriptor);
         WATCH_PTRSET(upperProtocols);
     }
 }
isDeliverableToUpperLayer()
bool inet::Ieee8022Llc::isDeliverableToUpperLayer (Packet * packet) protected virtual
 {
     const auto& protocolTag = packet->findTag<PacketProtocolTag>();
     return (protocolTag != nullptr && contains(upperProtocols, protocolTag->getProtocol()));
 }
Referenced by processPacketFromMac().
isInitializeStage()
virtual bool inet::Ieee8022Llc::isInitializeStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == INITSTAGE_LINK_LAYER; }
isModuleStartStage()
virtual bool inet::Ieee8022Llc::isModuleStartStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStartOperation::STAGE_LINK_LAYER; }
isModuleStopStage()
virtual bool inet::Ieee8022Llc::isModuleStopStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStopOperation::STAGE_LINK_LAYER; }
numInitStages()
virtual int inet::Ieee8022Llc::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
processCommandFromHigherLayer()
void inet::Ieee8022Llc::processCommandFromHigherLayer (Request * request) protected virtual
 {
     auto ctrl = request->getControlInfo();
     if (ctrl == nullptr)
         throw cRuntimeError("Request '%s' arrived without controlinfo", request->getName());
     else if (auto command = dynamic_cast<Ieee8022LlcSocketOpenCommand *>(ctrl)) {
         int socketId = request->getTag<SocketReq>()->getSocketId();
         SocketDescriptor *descriptor = new SocketDescriptor(socketId, command->getLocalSap());
         socketIdToSocketDescriptor[socketId] = descriptor;
         delete request;
     }
     else if (dynamic_cast<SocketCloseCommand *>(ctrl) != nullptr) {
         int socketId = request->getTag<SocketReq>()->getSocketId();
         auto it = socketIdToSocketDescriptor.find(socketId);
         if (it != socketIdToSocketDescriptor.end()) {
             delete it->second;
             socketIdToSocketDescriptor.erase(it);
         }
         delete request;
         auto indication = new Indication("closed", SOCKET_I_CLOSED);
         auto ctrl = new SocketClosedIndication();
         indication->setControlInfo(ctrl);
         indication->addTag<SocketInd>()->setSocketId(socketId);
         send(indication, "upperLayerOut");
     }
     else if (dynamic_cast<SocketDestroyCommand *>(ctrl) != nullptr) {
         int socketId = request->getTag<SocketReq>()->getSocketId();
         auto it = socketIdToSocketDescriptor.find(socketId);
         if (it != socketIdToSocketDescriptor.end()) {
             delete it->second;
             socketIdToSocketDescriptor.erase(it);
         }
         delete request;
     }
     else
         throw cRuntimeError("Unknown command: '%s' with %s", request->getName(), ctrl->getClassName());
 }
Referenced by handleMessageWhenUp().
processPacketFromHigherLayer()
void inet::Ieee8022Llc::processPacketFromHigherLayer (Packet * msg) protected virtual
 {
     encapsulate(packet);
     send(packet, "lowerLayerOut");
 }
Referenced by handleMessageWhenUp().
processPacketFromMac()
void inet::Ieee8022Llc::processPacketFromMac (Packet * packet) protected virtual
 {
     decapsulate(packet);
     bool isSent = deliverCopyToSockets(packet);
     if (isDeliverableToUpperLayer(packet)) {
         send(packet, "upperLayerOut");
     }
     else {
         if (!isSent) {
             EV_WARN << "Unknown protocol, dropping packet\n";
             PacketDropDetails details;
             details.setReason(NO_PROTOCOL_FOUND);
             emit(packetDroppedSignal, packet, &details);
         }
         delete packet;
     }
 }
Referenced by handleMessageWhenUp().
registerMyProtocol()
void inet::Ieee8022Llc::registerMyProtocol () protected virtual
 {
     registerProtocol(Protocol::ieee8022llc, gate("lowerLayerOut"), gate("lowerLayerIn"));
 }
Referenced by initialize().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & o, const SocketDescriptor & t) friend
 {
     o << "(id:" << t.socketId << ",lsap:" << t.localSap << ",rsap" << t.remoteSap << ")";
     return o;
 }
Member Data Documentation
socketIdToSocketDescriptor
std::map<int, SocketDescriptor *> inet::Ieee8022Llc::socketIdToSocketDescriptor protected
Referenced by clearSockets(), deliverCopyToSockets(), initialize(), and processCommandFromHigherLayer().
upperProtocols
std::set<const Protocol *> inet::Ieee8022Llc::upperProtocols protected
Referenced by handleRegisterProtocol(), initialize(), and isDeliverableToUpperLayer().
The documentation for this class was generated from the following files:
Ieee8022Llc.h
Ieee8022Llc.cc