INET Framework for OMNeT++/OMNEST: inet::SocketTagBase Class Reference
inet::SocketTagBase Class Reference
Class generated from inet/common/socket/SocketTag.msg:13 by opp_msgtool.
#include <SocketTag_m.h>
Public Member Functions
SocketTagBase ()
SocketTagBase (const SocketTagBase &other)
virtual ~SocketTagBase ()
SocketTagBase & operator= (const SocketTagBase &other)
virtual SocketTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getSocketId () const
virtual void setSocketId (int socketId)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SocketTagBase &)=delete
Protected Attributes
int socketId = -1
Private Member Functions
void copy (const SocketTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/common/socket/SocketTag.msg:13 by opp_msgtool.
class SocketTagBase extends TagBase
{
    int socketId = -1; // a locally unique (network node) identifier that determines the application socket
}
Constructor & Destructor Documentation
SocketTagBase() [1/2]
inet::SocketTagBase::SocketTagBase ()
SocketTagBase() [2/2]
inet::SocketTagBase::SocketTagBase (const SocketTagBase & other)
~SocketTagBase()
virtual inet::SocketTagBase::~SocketTagBase () virtual
Member Function Documentation
copy()
void inet::SocketTagBase::copy (const SocketTagBase & other) private
dup()
virtual SocketTagBase* inet::SocketTagBase::dup () const inline override virtual
Reimplemented in inet::SocketInd, and inet::SocketReq.
 {return new SocketTagBase(*this);}
getSocketId()
virtual int inet::SocketTagBase::getSocketId () const virtual
Referenced by inet::SocketBase::belongsToSocket(), inet::UdpSocket::belongsToSocket(), inet::TcpSocket::belongsToSocket(), inet::MessageDispatcher::handleMessage(), inet::MessageDispatcher::handlePacket(), inet::Tun::handleUpperPacket(), and inet::Udp::handleUpperPacket().
operator=()
SocketTagBase& inet::SocketTagBase::operator= (const SocketTagBase & other)
operator==()
bool inet::SocketTagBase::operator== (const SocketTagBase &) protected delete
parsimPack()
virtual void inet::SocketTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::SocketInd, and inet::SocketReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SocketTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::SocketInd, and inet::SocketReq.
Referenced by inet::doParsimUnpacking().
setSocketId()
virtual void inet::SocketTagBase::setSocketId (int socketId) virtual
Member Data Documentation
socketId
int inet::SocketTagBase::socketId = -1 protected
The documentation for this class was generated from the following file:
SocketTag_m.h