INET Framework for OMNeT++/OMNEST: inet::NetPerfMeterTransmitTimer Class Reference
inet::NetPerfMeterTransmitTimer Class Reference
Class generated from inet/applications/netperfmeter/NetPerfMeter.msg:23 by opp_msgtool.
#include <NetPerfMeter_m.h>
Public Member Functions
NetPerfMeterTransmitTimer (const char *name=nullptr, short kind=0)
NetPerfMeterTransmitTimer (const NetPerfMeterTransmitTimer &other)
virtual ~NetPerfMeterTransmitTimer ()
NetPerfMeterTransmitTimer & operator= (const NetPerfMeterTransmitTimer &other)
virtual NetPerfMeterTransmitTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned int getStreamID () const
virtual void setStreamID (unsigned int streamID)
Protected Member Functions
bool operator== (const NetPerfMeterTransmitTimer &)=delete
Protected Attributes
unsigned int streamID = 0
Private Member Functions
void copy (const NetPerfMeterTransmitTimer &other)
Detailed Description
Class generated from inet/applications/netperfmeter/NetPerfMeter.msg:23 by opp_msgtool.
message NetPerfMeterTransmitTimer
{
    unsigned int streamID;
}
Constructor & Destructor Documentation
NetPerfMeterTransmitTimer() [1/2]
inet::NetPerfMeterTransmitTimer::NetPerfMeterTransmitTimer (const char * name = nullptr, short kind = 0)
NetPerfMeterTransmitTimer() [2/2]
inet::NetPerfMeterTransmitTimer::NetPerfMeterTransmitTimer (const NetPerfMeterTransmitTimer & other)
~NetPerfMeterTransmitTimer()
virtual inet::NetPerfMeterTransmitTimer::~NetPerfMeterTransmitTimer () virtual
Member Function Documentation
copy()
void inet::NetPerfMeterTransmitTimer::copy (const NetPerfMeterTransmitTimer & other) private
dup()
virtual NetPerfMeterTransmitTimer* inet::NetPerfMeterTransmitTimer::dup () const inline override virtual
 {return new NetPerfMeterTransmitTimer(*this);}
getStreamID()
virtual unsigned int inet::NetPerfMeterTransmitTimer::getStreamID () const virtual
Referenced by inet::NetPerfMeter::handleTimer().
operator=()
NetPerfMeterTransmitTimer& inet::NetPerfMeterTransmitTimer::operator= (const NetPerfMeterTransmitTimer & other)
operator==()
bool inet::NetPerfMeterTransmitTimer::operator== (const NetPerfMeterTransmitTimer &) protected delete
parsimPack()
virtual void inet::NetPerfMeterTransmitTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::NetPerfMeterTransmitTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setStreamID()
virtual void inet::NetPerfMeterTransmitTimer::setStreamID (unsigned int streamID) virtual
Member Data Documentation
streamID
unsigned int inet::NetPerfMeterTransmitTimer::streamID = 0 protected
The documentation for this class was generated from the following file:
NetPerfMeter_m.h