INET Framework for OMNeT++/OMNEST: inet::Ieee802PauseCommand Class Reference
inet::Ieee802PauseCommand Class Reference
Class generated from inet/linklayer/common/Ieee802Ctrl.msg:23 by opp_msgtool.
#include <Ieee802Ctrl_m.h>
Public Member Functions
Ieee802PauseCommand ()
Ieee802PauseCommand (const Ieee802PauseCommand &other)
virtual ~Ieee802PauseCommand ()
Ieee802PauseCommand & operator= (const Ieee802PauseCommand &other)
virtual Ieee802PauseCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const MacAddress & getDestinationAddress () const
virtual MacAddress & getDestinationAddressForUpdate ()
virtual void setDestinationAddress (const MacAddress &destinationAddress)
virtual int getPauseUnits () const
virtual void setPauseUnits (int pauseUnits)
Protected Member Functions
bool operator== (const Ieee802PauseCommand &)=delete
Protected Attributes
MacAddress destinationAddress
int pauseUnits = 0
Private Member Functions
void copy (const Ieee802PauseCommand &other)
Detailed Description
Class generated from inet/linklayer/common/Ieee802Ctrl.msg:23 by opp_msgtool.
// used with IEEE802CTRL_SENDPAUSE
class Ieee802PauseCommand extends cObject
{
    MacAddress destinationAddress;
    int pauseUnits;
}
Constructor & Destructor Documentation
Ieee802PauseCommand() [1/2]
inet::Ieee802PauseCommand::Ieee802PauseCommand ()
Ieee802PauseCommand() [2/2]
inet::Ieee802PauseCommand::Ieee802PauseCommand (const Ieee802PauseCommand & other)
~Ieee802PauseCommand()
virtual inet::Ieee802PauseCommand::~Ieee802PauseCommand () virtual
Member Function Documentation
copy()
void inet::Ieee802PauseCommand::copy (const Ieee802PauseCommand & other) private
dup()
virtual Ieee802PauseCommand* inet::Ieee802PauseCommand::dup () const inline override virtual
 {return new Ieee802PauseCommand(*this);}
getDestinationAddress()
virtual const MacAddress& inet::Ieee802PauseCommand::getDestinationAddress () const virtual
Referenced by inet::EthernetPauseCommandProcessor::handleSendPause(), and inet::EthernetEncapsulation::handleSendPause().
getDestinationAddressForUpdate()
virtual MacAddress& inet::Ieee802PauseCommand::getDestinationAddressForUpdate () inline virtual
 { return const_cast<MacAddress&>(const_cast<Ieee802PauseCommand*>(this)->getDestinationAddress());}
getPauseUnits()
virtual int inet::Ieee802PauseCommand::getPauseUnits () const virtual
Referenced by inet::EthernetPauseCommandProcessor::handleSendPause(), and inet::EthernetEncapsulation::handleSendPause().
operator=()
Ieee802PauseCommand& inet::Ieee802PauseCommand::operator= (const Ieee802PauseCommand & other)
operator==()
bool inet::Ieee802PauseCommand::operator== (const Ieee802PauseCommand &) protected delete
parsimPack()
virtual void inet::Ieee802PauseCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ieee802PauseCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setDestinationAddress()
virtual void inet::Ieee802PauseCommand::setDestinationAddress (const MacAddress & destinationAddress) virtual
setPauseUnits()
virtual void inet::Ieee802PauseCommand::setPauseUnits (int pauseUnits) virtual
Member Data Documentation
destinationAddress
MacAddress inet::Ieee802PauseCommand::destinationAddress protected
pauseUnits
int inet::Ieee802PauseCommand::pauseUnits = 0 protected
The documentation for this class was generated from the following file:
Ieee802Ctrl_m.h