INET Framework for OMNeT++/OMNEST: inet::power::EnergySinkBase Class Reference
inet::power::EnergySinkBase Class Reference
#include <EnergySinkBase.h>
Public Member Functions
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Protected Attributes
std::vector< const IEnergyGenerator * > energyGenerators
Member Function Documentation
addEnergyGenerator()
void inet::power::EnergySinkBase::addEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Adds a new energy generator to the energy sink.
The energyGenerator parameter must not be nullptr.
Implements inet::power::IEnergySink.
Reimplemented in inet::power::CcEnergySinkBase, inet::power::CcEnergyStorageBase, inet::power::EpEnergySinkBase, and inet::power::EpEnergyStorageBase.
 {
     energyGenerators.push_back(energyGenerator);
 }
Referenced by inet::power::CcEnergySinkBase::addEnergyGenerator(), and inet::power::EpEnergySinkBase::addEnergyGenerator().
getEnergyGenerator()
const IEnergyGenerator * inet::power::EnergySinkBase::getEnergyGenerator (int index) const override virtual
Returns the energy generator for the provided index.
This functions throws an exception if the index is out of range, and it never returns nullptr.
Implements inet::power::IEnergySink.
 {
     return energyGenerators[index];
 }
getNumEnergyGenerators()
virtual int inet::power::EnergySinkBase::getNumEnergyGenerators () const inline override virtual
Returns the number of energy generators in the range [0, +infinity).
Implements inet::power::IEnergySink.
 { return energyGenerators.size(); }
removeEnergyGenerator()
void inet::power::EnergySinkBase::removeEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Removes a previously added energy generator from this energy sink.
This functions throws an exception if the generator is not found.
Implements inet::power::IEnergySink.
Reimplemented in inet::power::CcEnergySinkBase, inet::power::CcEnergyStorageBase, inet::power::EpEnergySinkBase, and inet::power::EpEnergyStorageBase.
 {
     auto it = find(energyGenerators, energyGenerator);
     if (it == energyGenerators.end())
         throw cRuntimeError("Energy generator not found");
     else
         energyGenerators.erase(it);
 }
Referenced by inet::power::CcEnergySinkBase::removeEnergyGenerator(), and inet::power::EpEnergySinkBase::removeEnergyGenerator().
Member Data Documentation
energyGenerators
std::vector<const IEnergyGenerator *> inet::power::EnergySinkBase::energyGenerators protected
Referenced by addEnergyGenerator(), inet::power::CcEnergySinkBase::computeTotalCurrentGeneration(), inet::power::EpEnergySinkBase::computeTotalPowerGeneration(), getEnergyGenerator(), and removeEnergyGenerator().
The documentation for this class was generated from the following files:
EnergySinkBase.h
EnergySinkBase.cc