INET Framework for OMNeT++/OMNEST: inet::dymo::AddressBlock Class Reference
inet::dymo::AddressBlock Class Reference
Class generated from inet/routing/dymo/Dymo.msg:39 by opp_msgtool.
#include <Dymo_m.h>
Public Member Functions
AddressBlock ()
AddressBlock (const AddressBlock &other)
virtual ~AddressBlock ()
AddressBlock & operator= (const AddressBlock &other)
virtual AddressBlock * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::L3Address & getAddress () const
virtual ::inet::L3Address & getAddressForUpdate ()
virtual void setAddress (const ::inet::L3Address &address)
virtual int getPrefixLength () const
virtual void setPrefixLength (int prefixLength)
virtual bool getHasValidityTime () const
virtual void setHasValidityTime (bool hasValidityTime)
virtual ::omnetpp::simtime_t getValidityTime () const
virtual void setValidityTime (::omnetpp::simtime_t validityTime)
virtual bool getHasMetric () const
virtual void setHasMetric (bool hasMetric)
virtual double getMetric () const
virtual void setMetric (double metric)
virtual bool getHasMetricType () const
virtual void setHasMetricType (bool hasMetricType)
virtual DymoMetricType getMetricType () const
virtual void setMetricType (DymoMetricType metricType)
virtual bool getHasSequenceNumber () const
virtual void setHasSequenceNumber (bool hasSequenceNumber)
virtual DymoSequenceNumber getSequenceNumber () const
virtual void setSequenceNumber (DymoSequenceNumber sequenceNumber)
Protected Member Functions
bool operator== (const AddressBlock &)=delete
Protected Attributes
::inet::L3Address address
int prefixLength = 0
bool hasValidityTime = false
::omnetpp::simtime_t validityTime = SIMTIME_ZERO
bool hasMetric = false
double metric = 0
bool hasMetricType = false
DymoMetricType metricType = static_cast<inet::dymo::DymoMetricType>(-1)
bool hasSequenceNumber = false
DymoSequenceNumber sequenceNumber = 0
Private Member Functions
void copy (const AddressBlock &other)
Detailed Description
Class generated from inet/routing/dymo/Dymo.msg:39 by opp_msgtool.
class AddressBlock extends cObject
{
    @packetData;
    L3Address address;
    int prefixLength;
    bool hasValidityTime;
    simtime_t validityTime;
    bool hasMetric;
    double metric;
    bool hasMetricType;
    DymoMetricType metricType;
    bool hasSequenceNumber;
    DymoSequenceNumber sequenceNumber = 0;
}
//
// Dymo timer messages
//
Constructor & Destructor Documentation
AddressBlock() [1/2]
inet::dymo::AddressBlock::AddressBlock ()
AddressBlock() [2/2]
inet::dymo::AddressBlock::AddressBlock (const AddressBlock & other)
~AddressBlock()
virtual inet::dymo::AddressBlock::~AddressBlock () virtual
Member Function Documentation
copy()
void inet::dymo::AddressBlock::copy (const AddressBlock & other) private
dup()
virtual AddressBlock* inet::dymo::AddressBlock::dup () const inline override virtual
 {return new AddressBlock(*this);}
getAddress()
virtual const ::inet::L3Address& inet::dymo::AddressBlock::getAddress () const virtual
Referenced by inet::dymo::Dymo::permissibleRteMsg(), inet::dymo::Dymo::processRerr(), inet::dymo::Dymo::updateRoute(), and inet::dymo::Dymo::updateRoutes().
getAddressForUpdate()
virtual ::inet::L3Address& inet::dymo::AddressBlock::getAddressForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<AddressBlock*>(this)->getAddress());}
getHasMetric()
virtual bool inet::dymo::AddressBlock::getHasMetric () const virtual
Referenced by inet::dymo::Dymo::permissibleRteMsg().
getHasMetricType()
virtual bool inet::dymo::AddressBlock::getHasMetricType () const virtual
Referenced by inet::dymo::Dymo::updateRoute().
getHasSequenceNumber()
virtual bool inet::dymo::AddressBlock::getHasSequenceNumber () const virtual
Referenced by inet::dymo::Dymo::permissibleRteMsg(), and inet::dymo::Dymo::processRerr().
getHasValidityTime()
virtual bool inet::dymo::AddressBlock::getHasValidityTime () const virtual
Referenced by inet::dymo::Dymo::updateRoute().
getMetric()
virtual double inet::dymo::AddressBlock::getMetric () const virtual
Referenced by inet::dymo::Dymo::updateRoute(), and inet::dymo::Dymo::updateRoutes().
getMetricType()
virtual DymoMetricType inet::dymo::AddressBlock::getMetricType () const virtual
Referenced by inet::dymo::Dymo::permissibleRteMsg(), inet::dymo::Dymo::updateRoute(), and inet::dymo::Dymo::updateRoutes().
getPrefixLength()
virtual int inet::dymo::AddressBlock::getPrefixLength () const virtual
Referenced by inet::dymo::Dymo::updateRoute().
getSequenceNumber()
virtual DymoSequenceNumber inet::dymo::AddressBlock::getSequenceNumber () const virtual
Referenced by inet::dymo::Dymo::processRerr(), inet::dymo::Dymo::updateRoute(), and inet::dymo::Dymo::updateRoutes().
getValidityTime()
virtual ::omnetpp::simtime_t inet::dymo::AddressBlock::getValidityTime () const
Referenced by inet::dymo::Dymo::updateRoute().
operator=()
AddressBlock& inet::dymo::AddressBlock::operator= (const AddressBlock & other)
operator==()
bool inet::dymo::AddressBlock::operator== (const AddressBlock &) protected delete
parsimPack()
virtual void inet::dymo::AddressBlock::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::dymo::doParsimPacking().
parsimUnpack()
virtual void inet::dymo::AddressBlock::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::dymo::doParsimUnpacking().
setAddress()
virtual void inet::dymo::AddressBlock::setAddress (const ::inet::L3Address & address) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), and inet::dymo::Dymo::createRreq().
setHasMetric()
virtual void inet::dymo::AddressBlock::setHasMetric (bool hasMetric) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), inet::dymo::Dymo::createRrep(), and inet::dymo::Dymo::createRreq().
setHasMetricType()
virtual void inet::dymo::AddressBlock::setHasMetricType (bool hasMetricType) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), inet::dymo::Dymo::createRrep(), and inet::dymo::Dymo::createRreq().
setHasSequenceNumber()
virtual void inet::dymo::AddressBlock::setHasSequenceNumber (bool hasSequenceNumber) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), inet::dymo::Dymo::createRrep(), and inet::dymo::Dymo::createRreq().
setHasValidityTime()
virtual void inet::dymo::AddressBlock::setHasValidityTime (bool hasValidityTime) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), and inet::dymo::Dymo::createRerr().
setMetric()
virtual void inet::dymo::AddressBlock::setMetric (double metric) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRrep(), and inet::dymo::Dymo::createRreq().
setMetricType()
virtual void inet::dymo::AddressBlock::setMetricType (DymoMetricType metricType) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRrep(), and inet::dymo::Dymo::createRreq().
setPrefixLength()
virtual void inet::dymo::AddressBlock::setPrefixLength (int prefixLength) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), and inet::dymo::Dymo::createRreq().
setSequenceNumber()
virtual void inet::dymo::AddressBlock::setSequenceNumber (DymoSequenceNumber sequenceNumber) virtual
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), inet::dymo::Dymo::createRrep(), and inet::dymo::Dymo::createRreq().
setValidityTime()
virtual void inet::dymo::AddressBlock::setValidityTime (::omnetpp::simtime_t validityTime) virtual
Referenced by inet::dymo::Dymo::addSelfNode().
Member Data Documentation
address
::inet::L3Address inet::dymo::AddressBlock::address protected
hasMetric
bool inet::dymo::AddressBlock::hasMetric = false protected
hasMetricType
bool inet::dymo::AddressBlock::hasMetricType = false protected
hasSequenceNumber
bool inet::dymo::AddressBlock::hasSequenceNumber = false protected
hasValidityTime
bool inet::dymo::AddressBlock::hasValidityTime = false protected
metric
double inet::dymo::AddressBlock::metric = 0 protected
metricType
DymoMetricType inet::dymo::AddressBlock::metricType = static_cast<inet::dymo::DymoMetricType>(-1) protected
prefixLength
int inet::dymo::AddressBlock::prefixLength = 0 protected
sequenceNumber
DymoSequenceNumber inet::dymo::AddressBlock::sequenceNumber = 0 protected
validityTime
::omnetpp::simtime_t inet::dymo::AddressBlock::validityTime = SIMTIME_ZERO protected
The documentation for this class was generated from the following file:
Dymo_m.h