INET Framework for OMNeT++/OMNEST: inet::SimpleGeographicCoordinateSystem Class Reference
inet::SimpleGeographicCoordinateSystem Class Reference
#include <GeographicCoordinateSystem.h>
Public Member Functions
virtual GeoCoord getScenePosition () const override
virtual Quaternion getSceneOrientation () const override
virtual Coord computeSceneCoordinate (const GeoCoord &geographicCoordinate) const override
virtual GeoCoord computeGeographicCoordinate (const Coord &sceneCoordinate) const override
Protected Member Functions
virtual void initialize (int stage) override
Protected Attributes
double metersPerDegree = 111320
deg sceneLatitude = deg(NaN)
deg sceneLongitude = deg(NaN)
m sceneAltitude = m(NaN)
Member Function Documentation
computeGeographicCoordinate()
GeoCoord inet::SimpleGeographicCoordinateSystem::computeGeographicCoordinate (const Coord & sceneCoordinate) const override virtual
Implements inet::IGeographicCoordinateSystem.
 {
     auto geograpicLatitude = sceneLatitude - deg(sceneCoordinate.y / metersPerDegree);
     auto geograpicLongitude = sceneLongitude + deg(sceneCoordinate.x / metersPerDegree / cos(fabs(rad(sceneLatitude).get())));
     return GeoCoord(geograpicLatitude, geograpicLongitude, m(sceneCoordinate.z) - sceneAltitude);
 }
computeSceneCoordinate()
Coord inet::SimpleGeographicCoordinateSystem::computeSceneCoordinate (const GeoCoord & geographicCoordinate) const override virtual
Implements inet::IGeographicCoordinateSystem.
 {
     double sceneX = deg(geographicCoordinate.longitude - sceneLongitude).get() * cos(fabs(rad(sceneLatitude).get())) * metersPerDegree;
     double sceneY = deg(sceneLatitude - geographicCoordinate.latitude).get() * metersPerDegree;
     return Coord(sceneX, sceneY, m(geographicCoordinate.altitude + sceneAltitude).get());
 }
getSceneOrientation()
virtual Quaternion inet::SimpleGeographicCoordinateSystem::getSceneOrientation () const inline override virtual
Implements inet::IGeographicCoordinateSystem.
 { return Quaternion::IDENTITY; }
getScenePosition()
virtual GeoCoord inet::SimpleGeographicCoordinateSystem::getScenePosition () const inline override virtual
Implements inet::IGeographicCoordinateSystem.
 { return GeoCoord(sceneLatitude, sceneLongitude, sceneAltitude); }
initialize()
void inet::SimpleGeographicCoordinateSystem::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         sceneLatitude = deg(par("sceneLatitude"));
         sceneLongitude = deg(par("sceneLongitude"));
         sceneAltitude = m(par("sceneAltitude"));
     }
 }
Member Data Documentation
metersPerDegree
double inet::SimpleGeographicCoordinateSystem::metersPerDegree = 111320 protected
Referenced by computeGeographicCoordinate(), and computeSceneCoordinate().
sceneAltitude
m inet::SimpleGeographicCoordinateSystem::sceneAltitude = m(NaN) protected
Referenced by computeGeographicCoordinate(), computeSceneCoordinate(), and initialize().
sceneLatitude
deg inet::SimpleGeographicCoordinateSystem::sceneLatitude = deg(NaN) protected
Referenced by computeGeographicCoordinate(), computeSceneCoordinate(), and initialize().
sceneLongitude
deg inet::SimpleGeographicCoordinateSystem::sceneLongitude = deg(NaN) protected
Referenced by computeGeographicCoordinate(), computeSceneCoordinate(), and initialize().
The documentation for this class was generated from the following files:
GeographicCoordinateSystem.h
GeographicCoordinateSystem.cc