INET Framework for OMNeT++/OMNEST: inet::bgp::BgpOptionalParameterRaw Class Reference
inet::bgp::BgpOptionalParameterRaw Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:81 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpOptionalParameterRaw ()
BgpOptionalParameterRaw (const BgpOptionalParameterRaw &other)
virtual ~BgpOptionalParameterRaw ()
BgpOptionalParameterRaw & operator= (const BgpOptionalParameterRaw &other)
virtual void parsimPack (omnetpp::cCommBuffer *b) const
virtual void parsimUnpack (omnetpp::cCommBuffer *b)
virtual void setValueArraySize (size_t size)
virtual size_t getValueArraySize () const
virtual char getValue (size_t k) const
virtual void setValue (size_t k, char value)
virtual void insertValue (size_t k, char value)
void insertValue (char value)
virtual void appendValue (char value)
virtual void eraseValue (size_t k)
Public Member Functions inherited from inet::bgp::BgpOptionalParameterBase
BgpOptionalParameterBase ()
BgpOptionalParameterBase (const BgpOptionalParameterBase &other)
virtual ~BgpOptionalParameterBase ()
BgpOptionalParameterBase & operator= (const BgpOptionalParameterBase &other)
virtual short getParameterType () const
virtual void setParameterType (short parameterType)
virtual unsigned short getParameterValueLength () const
virtual void setParameterValueLength (unsigned short parameterValueLength)
Protected Member Functions
bool operator== (const BgpOptionalParameterRaw &)=delete
Protected Member Functions inherited from inet::bgp::BgpOptionalParameterBase
bool operator== (const BgpOptionalParameterBase &)=delete
Protected Attributes
char * value = nullptr
size_t value_arraysize = 0
Protected Attributes inherited from inet::bgp::BgpOptionalParameterBase
short parameterType = 0
unsigned short parameterValueLength = 0
Private Member Functions
void copy (const BgpOptionalParameterRaw &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:81 by opp_msgtool.
class BgpOptionalParameterRaw extends BgpOptionalParameterBase
{
    char value[];
}
Constructor & Destructor Documentation
BgpOptionalParameterRaw() [1/2]
inet::bgp::BgpOptionalParameterRaw::BgpOptionalParameterRaw ()
BgpOptionalParameterRaw() [2/2]
inet::bgp::BgpOptionalParameterRaw::BgpOptionalParameterRaw (const BgpOptionalParameterRaw & other)
~BgpOptionalParameterRaw()
virtual inet::bgp::BgpOptionalParameterRaw::~BgpOptionalParameterRaw () virtual
Member Function Documentation
appendValue()
virtual void inet::bgp::BgpOptionalParameterRaw::appendValue (char value) virtual
copy()
void inet::bgp::BgpOptionalParameterRaw::copy (const BgpOptionalParameterRaw & other) private
eraseValue()
virtual void inet::bgp::BgpOptionalParameterRaw::eraseValue (size_t k) virtual
getValue()
virtual char inet::bgp::BgpOptionalParameterRaw::getValue (size_t k) const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getValueArraySize()
virtual size_t inet::bgp::BgpOptionalParameterRaw::getValueArraySize () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
insertValue() [1/2]
void inet::bgp::BgpOptionalParameterRaw::insertValue (char value) inline
 {appendValue(value);}
insertValue() [2/2]
virtual void inet::bgp::BgpOptionalParameterRaw::insertValue (size_t k, char value) virtual
operator=()
BgpOptionalParameterRaw& inet::bgp::BgpOptionalParameterRaw::operator= (const BgpOptionalParameterRaw & other)
operator==()
bool inet::bgp::BgpOptionalParameterRaw::operator== (const BgpOptionalParameterRaw &) protected delete
parsimPack()
virtual void inet::bgp::BgpOptionalParameterRaw::parsimPack (omnetpp::cCommBuffer * b) const virtual
Reimplemented from inet::bgp::BgpOptionalParameterBase.
parsimUnpack()
virtual void inet::bgp::BgpOptionalParameterRaw::parsimUnpack (omnetpp::cCommBuffer * b) virtual
Reimplemented from inet::bgp::BgpOptionalParameterBase.
setValue()
virtual void inet::bgp::BgpOptionalParameterRaw::setValue (size_t k, char value) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setValueArraySize()
virtual void inet::bgp::BgpOptionalParameterRaw::setValueArraySize (size_t size) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
value
char* inet::bgp::BgpOptionalParameterRaw::value = nullptr protected
value_arraysize
size_t inet::bgp::BgpOptionalParameterRaw::value_arraysize = 0 protected
The documentation for this class was generated from the following file:
BgpHeader_m.h