INET Framework for OMNeT++/OMNEST: inet::Ieee8022LlcSocketOpenCommand Class Reference
inet::Ieee8022LlcSocketOpenCommand Class Reference
Class generated from inet/linklayer/ieee8022/Ieee8022LlcSocketCommand.msg:13 by opp_msgtool.
#include <Ieee8022LlcSocketCommand_m.h>
Public Member Functions
Ieee8022LlcSocketOpenCommand ()
Ieee8022LlcSocketOpenCommand (const Ieee8022LlcSocketOpenCommand &other)
virtual ~Ieee8022LlcSocketOpenCommand ()
Ieee8022LlcSocketOpenCommand & operator= (const Ieee8022LlcSocketOpenCommand &other)
virtual Ieee8022LlcSocketOpenCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getLocalSap () const
virtual void setLocalSap (int localSap)
Public Member Functions inherited from inet::SocketCommandBase
SocketCommandBase ()
SocketCommandBase (const SocketCommandBase &other)
virtual ~SocketCommandBase ()
SocketCommandBase & operator= (const SocketCommandBase &other)
Protected Member Functions
bool operator== (const Ieee8022LlcSocketOpenCommand &)=delete
Protected Member Functions inherited from inet::SocketCommandBase
bool operator== (const SocketCommandBase &)=delete
Protected Attributes
int localSap = 0
Private Member Functions
void copy (const Ieee8022LlcSocketOpenCommand &other)
Detailed Description
Class generated from inet/linklayer/ieee8022/Ieee8022LlcSocketCommand.msg:13 by opp_msgtool.
class Ieee8022LlcSocketOpenCommand extends SocketCommandBase
{
    int localSap;
}
Constructor & Destructor Documentation
Ieee8022LlcSocketOpenCommand() [1/2]
inet::Ieee8022LlcSocketOpenCommand::Ieee8022LlcSocketOpenCommand ()
Ieee8022LlcSocketOpenCommand() [2/2]
inet::Ieee8022LlcSocketOpenCommand::Ieee8022LlcSocketOpenCommand (const Ieee8022LlcSocketOpenCommand & other)
~Ieee8022LlcSocketOpenCommand()
virtual inet::Ieee8022LlcSocketOpenCommand::~Ieee8022LlcSocketOpenCommand () virtual
Member Function Documentation
copy()
void inet::Ieee8022LlcSocketOpenCommand::copy (const Ieee8022LlcSocketOpenCommand & other) private
dup()
virtual Ieee8022LlcSocketOpenCommand* inet::Ieee8022LlcSocketOpenCommand::dup () const inline override virtual
Reimplemented from inet::SocketCommandBase.
 {return new Ieee8022LlcSocketOpenCommand(*this);}
getLocalSap()
virtual int inet::Ieee8022LlcSocketOpenCommand::getLocalSap () const virtual
operator=()
Ieee8022LlcSocketOpenCommand& inet::Ieee8022LlcSocketOpenCommand::operator= (const Ieee8022LlcSocketOpenCommand & other)
operator==()
bool inet::Ieee8022LlcSocketOpenCommand::operator== (const Ieee8022LlcSocketOpenCommand &) protected delete
parsimPack()
virtual void inet::Ieee8022LlcSocketOpenCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SocketCommandBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ieee8022LlcSocketOpenCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SocketCommandBase.
Referenced by inet::doParsimUnpacking().
setLocalSap()
virtual void inet::Ieee8022LlcSocketOpenCommand::setLocalSap (int localSap) virtual
Referenced by inet::Ieee8022LlcSocket::open().
Member Data Documentation
localSap
int inet::Ieee8022LlcSocketOpenCommand::localSap = 0 protected
The documentation for this class was generated from the following file:
Ieee8022LlcSocketCommand_m.h