INET Framework for OMNeT++/OMNEST: inet::visualizer::AnimationPosition Class Reference
inet::visualizer::AnimationPosition Class Reference
#include <AnimationPosition.h>
Public Types
enum TimeType { SIMULATION_TIME, ANIMATION_TIME, REAL_TIME }
Public Member Functions
AnimationPosition ()
AnimationPosition (simtime_t simulationTime, double animationTime, double realTime)
simtime_t getSimulationTime () const
double getAnimationTime () const
double getRealTime () const
double getTime (TimeType type) const
AnimationPosition & operator= (const AnimationPosition &other)
Protected Member Functions
double computeRealTime () const
Protected Attributes
simtime_t simulationTime
double animationTime
double realTime
Member Enumeration Documentation
TimeType
enum inet::visualizer::AnimationPosition::TimeType
Enumerator
SIMULATION_TIME
ANIMATION_TIME
REAL_TIME
                   {
         SIMULATION_TIME,
         ANIMATION_TIME,
         REAL_TIME
     };
Constructor & Destructor Documentation
AnimationPosition() [1/2]
inet::visualizer::AnimationPosition::AnimationPosition ()
                                      :
     simulationTime(getSimulation()->getSimTime()),
     animationTime(getSimulation()->getEnvir()->getAnimationTime()),
     realTime(computeRealTime())
 {
 }
AnimationPosition() [2/2]
inet::visualizer::AnimationPosition::AnimationPosition (simtime_t simulationTime, double animationTime, double realTime)
                                                                                                     :
     simulationTime(simulationTime),
     animationTime(animationTime),
     realTime(realTime)
 {
 }
Member Function Documentation
computeRealTime()
double inet::visualizer::AnimationPosition::computeRealTime () const protected
 {
     return opp_get_monotonic_clock_usecs() / 1.0E+6;
 }
getAnimationTime()
double inet::visualizer::AnimationPosition::getAnimationTime () const inline
 { return animationTime; }
Referenced by inet::visualizer::TracingObstacleLossVisualizerBase::refreshDisplay(), inet::visualizer::LinkBreakVisualizerBase::refreshDisplay(), inet::visualizer::LinkVisualizerBase::refreshDisplay(), inet::visualizer::PathVisualizerBase::refreshDisplay(), and inet::visualizer::PacketDropVisualizerBase::refreshDisplay().
getRealTime()
double inet::visualizer::AnimationPosition::getRealTime () const inline
 { return realTime; }
Referenced by inet::visualizer::TracingObstacleLossVisualizerBase::refreshDisplay(), inet::visualizer::LinkBreakVisualizerBase::refreshDisplay(), inet::visualizer::LinkVisualizerBase::refreshDisplay(), inet::visualizer::PathVisualizerBase::refreshDisplay(), and inet::visualizer::PacketDropVisualizerBase::refreshDisplay().
getSimulationTime()
simtime_t inet::visualizer::AnimationPosition::getSimulationTime () const inline
 { return simulationTime; }
Referenced by inet::visualizer::TracingObstacleLossVisualizerBase::refreshDisplay(), inet::visualizer::LinkBreakVisualizerBase::refreshDisplay(), inet::visualizer::LinkVisualizerBase::refreshDisplay(), inet::visualizer::PathVisualizerBase::refreshDisplay(), and inet::visualizer::PacketDropVisualizerBase::refreshDisplay().
getTime()
double inet::visualizer::AnimationPosition::getTime (TimeType type) const
 {
     switch (type) {
         case SIMULATION_TIME:
             return simulationTime.dbl();
         case ANIMATION_TIME:
             return animationTime;
         case REAL_TIME:
             return realTime;
         default:
             throw cRuntimeError("Unknown time type");
     }
 }
Referenced by inet::visualizer::AnimationSpeedInterpolator::getCurrentAnimationSpeed().
operator=()
AnimationPosition & inet::visualizer::AnimationPosition::operator= (const AnimationPosition & other)
 {
     simulationTime = other.simulationTime;
     animationTime = other.animationTime;
     realTime = other.realTime;
     return *this;
 }
Member Data Documentation
animationTime
double inet::visualizer::AnimationPosition::animationTime protected
Referenced by getTime(), and operator=().
realTime
double inet::visualizer::AnimationPosition::realTime protected
Referenced by getTime(), and operator=().
simulationTime
simtime_t inet::visualizer::AnimationPosition::simulationTime protected
Referenced by getTime(), and operator=().
The documentation for this class was generated from the following files:
AnimationPosition.h
AnimationPosition.cc