INET Framework for OMNeT++/OMNEST: inet::ieee80211::OriginatorBlockAckAgreementHandler Class Reference
inet::ieee80211::OriginatorBlockAckAgreementHandler Class Reference
#include <OriginatorBlockAckAgreementHandler.h>
Public Member Functions
virtual ~OriginatorBlockAckAgreementHandler ()
virtual void processTransmittedAddbaReq (const Ptr< const Ieee80211AddbaRequest > &addbaReq) override
virtual void processTransmittedDataFrame (Packet *packet, const Ptr< const Ieee80211DataHeader > &dataHeader, IOriginatorBlockAckAgreementPolicy *blockAckAgreementPolicy, IProcedureCallback *callback) override
virtual void processReceivedBlockAck (const Ptr< const Ieee80211BlockAck > &blockAck, IBlockAckAgreementHandlerCallback *callback) override
virtual void processReceivedAddbaResp (const Ptr< const Ieee80211AddbaResponse > &addbaResp, IOriginatorBlockAckAgreementPolicy *blockAckAgreementPolicy, IBlockAckAgreementHandlerCallback *callback) override
virtual void processReceivedDelba (const Ptr< const Ieee80211Delba > &delba, IOriginatorBlockAckAgreementPolicy *blockAckAgreementPolicy) override
virtual void processTransmittedDelba (const Ptr< const Ieee80211Delba > &delba) override
virtual void blockAckAgreementExpired (IProcedureCallback *procedureCallback, IBlockAckAgreementHandlerCallback *agreementHandlerCallback) override
virtual OriginatorBlockAckAgreement * getAgreement (MacAddress receiverAddr, Tid tid) override
Public Member Functions inherited from inet::ieee80211::IOriginatorBlockAckAgreementHandler
virtual ~IOriginatorBlockAckAgreementHandler ()
Protected Member Functions
virtual const Ptr< Ieee80211AddbaRequest > buildAddbaRequest (MacAddress receiverAddr, Tid tid, SequenceNumberCyclic startingSequenceNumber, IOriginatorBlockAckAgreementPolicy *blockAckAgreementPolicy)
virtual void createAgreement (const Ptr< const Ieee80211AddbaRequest > &addbaRequest)
virtual void updateAgreement (OriginatorBlockAckAgreement *agreement, const Ptr< const Ieee80211AddbaResponse > &addbaResp)
virtual void terminateAgreement (MacAddress originatorAddr, Tid tid)
virtual const Ptr< Ieee80211Delba > buildDelba (MacAddress receiverAddr, Tid tid, int reasonCode)
virtual simtime_t computeEarliestExpirationTime ()
virtual void scheduleInactivityTimer (IBlockAckAgreementHandlerCallback *callback)
Protected Attributes
std::map< std::pair< MacAddress, Tid >, OriginatorBlockAckAgreement * > blockAckAgreements
Constructor & Destructor Documentation
~OriginatorBlockAckAgreementHandler()
inet::ieee80211::OriginatorBlockAckAgreementHandler::~OriginatorBlockAckAgreementHandler () virtual
 {
     for (auto it : blockAckAgreements)
         delete it.second;
 }
Member Function Documentation
blockAckAgreementExpired()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::blockAckAgreementExpired (IProcedureCallback * procedureCallback, IBlockAckAgreementHandlerCallback * agreementHandlerCallback) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     // When a timeout of BlockAckTimeout is detected, the STA shall send a DELBA frame to the
     // peer STA with the Reason Code field set to TIMEOUT and shall issue a MLME-DELBA.indication
     // primitive with the ReasonCode parameter having a value of TIMEOUT.
     // The procedure is illustrated in Figure 10-14.
     simtime_t now = simTime();
     for (auto id : blockAckAgreements) {
         auto agreement = id.second;
         if (agreement->getExpirationTime() == now) {
             MacAddress receiverAddr = id.first.first;
             Tid tid = id.first.second;
             const auto& delba = buildDelba(receiverAddr, tid, 39);
             auto delbaPacket = new Packet("Delba", delba);
             procedureCallback->processMgmtFrame(delbaPacket, delba); // 39 - TIMEOUT see: Table 8-36—Reason codes
         }
     }
     scheduleInactivityTimer(agreementHandlerCallback);
 }
buildAddbaRequest()
const Ptr< Ieee80211AddbaRequest > inet::ieee80211::OriginatorBlockAckAgreementHandler::buildAddbaRequest (MacAddress receiverAddr, Tid tid, SequenceNumberCyclic startingSequenceNumber, IOriginatorBlockAckAgreementPolicy * blockAckAgreementPolicy) protected virtual
 {
     auto addbaRequest = makeShared<Ieee80211AddbaRequest>();
     addbaRequest->setReceiverAddress(receiverAddr);
     addbaRequest->setTid(tid);
     addbaRequest->setAMsduSupported(blockAckAgreementPolicy->isMsduSupported());
     addbaRequest->setBlockAckTimeoutValue(blockAckAgreementPolicy->getBlockAckTimeoutValue());
     addbaRequest->setBufferSize(blockAckAgreementPolicy->getMaximumAllowedBufferSize());
     // The Block Ack Policy subfield is set to 1 for immediate Block Ack and 0 for delayed Block Ack.
     addbaRequest->setBlockAckPolicy(blockAckAgreementPolicy->isDelayedAckPolicySupported() ? 0 : 1);
     addbaRequest->setStartingSequenceNumber(startingSequenceNumber);
     return addbaRequest;
 }
Referenced by processTransmittedDataFrame().
buildDelba()
const Ptr< Ieee80211Delba > inet::ieee80211::OriginatorBlockAckAgreementHandler::buildDelba (MacAddress receiverAddr, Tid tid, int reasonCode) protected virtual
 {
     auto delba = makeShared<Ieee80211Delba>();
     delba->setReceiverAddress(receiverAddr);
     delba->setTid(tid);
     delba->setReasonCode(reasonCode);
     // The Initiator subfield indicates if the originator or the recipient of the data is sending this frame.
     delba->setInitiator(true);
     return delba;
 }
Referenced by blockAckAgreementExpired().
computeEarliestExpirationTime()
simtime_t inet::ieee80211::OriginatorBlockAckAgreementHandler::computeEarliestExpirationTime () protected virtual
 {
     simtime_t earliestTime = SIMTIME_MAX;
     for (auto id : blockAckAgreements) {
         auto agreement = id.second;
         if (agreement->getIsAddbaResponseReceived()) {
             ASSERT(earliestTime >= 0);
             ASSERT(agreement->getExpirationTime() >= 0);
             earliestTime = std::min(earliestTime, agreement->getExpirationTime());
         }
     }
     return earliestTime;
 }
Referenced by scheduleInactivityTimer().
createAgreement()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::createAgreement (const Ptr< const Ieee80211AddbaRequest > & addbaRequest) protected virtual
 {
     OriginatorBlockAckAgreement *blockAckAgreement = new OriginatorBlockAckAgreement(addbaRequest->getReceiverAddress(), addbaRequest->getTid(), addbaRequest->getStartingSequenceNumber(), addbaRequest->getBufferSize(), addbaRequest->getAMsduSupported(), addbaRequest->getBlockAckPolicy() == 0);
     auto agreementId = std::make_pair(addbaRequest->getReceiverAddress(), addbaRequest->getTid());
     blockAckAgreements[agreementId] = blockAckAgreement;
 }
Referenced by processTransmittedDataFrame().
getAgreement()
OriginatorBlockAckAgreement * inet::ieee80211::OriginatorBlockAckAgreementHandler::getAgreement (MacAddress receiverAddr, Tid tid) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     auto agreementId = std::make_pair(receiverAddr, tid);
     auto it = blockAckAgreements.find(agreementId);
     return it != blockAckAgreements.end() ? it->second : nullptr;
 }
Referenced by processReceivedAddbaResp(), processReceivedBlockAck(), processTransmittedAddbaReq(), and processTransmittedDataFrame().
processReceivedAddbaResp()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::processReceivedAddbaResp (const Ptr< const Ieee80211AddbaResponse > & addbaResp, IOriginatorBlockAckAgreementPolicy * blockAckAgreementPolicy, IBlockAckAgreementHandlerCallback * callback) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     auto agreement = getAgreement(addbaResp->getTransmitterAddress(), addbaResp->getTid());
     if (blockAckAgreementPolicy->isAddbaReqAccepted(addbaResp, agreement)) {
         updateAgreement(agreement, addbaResp);
         scheduleInactivityTimer(callback);
     }
     else {
         // TODO send a new one?
     }
 }
processReceivedBlockAck()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::processReceivedBlockAck (const Ptr< const Ieee80211BlockAck > & blockAck, IBlockAckAgreementHandlerCallback * callback) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     if (auto basicBlockAck = dynamicPtrCast<const Ieee80211BasicBlockAck>(blockAck)) {
         auto agreement = getAgreement(basicBlockAck->getTransmitterAddress(), basicBlockAck->getTidInfo());
         if (agreement) {
             agreement->setStartingSequenceNumber(basicBlockAck->getStartingSequenceNumber());
             agreement->calculateExpirationTime();
             scheduleInactivityTimer(callback);
         }
     }
     else
         throw cRuntimeError("Unsupported BlockAck");
 }
processReceivedDelba()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::processReceivedDelba (const Ptr< const Ieee80211Delba > & delba, IOriginatorBlockAckAgreementPolicy * blockAckAgreementPolicy) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     if (blockAckAgreementPolicy->isDelbaAccepted(delba))
         terminateAgreement(delba->getTransmitterAddress(), delba->getTid());
 }
processTransmittedAddbaReq()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::processTransmittedAddbaReq (const Ptr< const Ieee80211AddbaRequest > & addbaReq) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     auto agreement = getAgreement(addbaReq->getReceiverAddress(), addbaReq->getTid());
     if (agreement)
         agreement->setIsAddbaRequestSent(true);
     else
         throw cRuntimeError("Block Ack Agreement should have already been added");
 }
processTransmittedDataFrame()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::processTransmittedDataFrame (Packet * packet, const Ptr< const Ieee80211DataHeader > & dataHeader, IOriginatorBlockAckAgreementPolicy * blockAckAgreementPolicy, IProcedureCallback * callback) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     auto agreement = getAgreement(dataHeader->getReceiverAddress(), dataHeader->getTid());
     if (blockAckAgreementPolicy->isAddbaReqNeeded(packet, dataHeader) && agreement == nullptr) {
         auto addbaReq = buildAddbaRequest(dataHeader->getReceiverAddress(), dataHeader->getTid(), dataHeader->getSequenceNumber() + 1, blockAckAgreementPolicy);
         createAgreement(addbaReq);
         auto addbaPacket = new Packet("AddbaReq", addbaReq);
         callback->processMgmtFrame(addbaPacket, addbaReq);
     }
 }
processTransmittedDelba()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::processTransmittedDelba (const Ptr< const Ieee80211Delba > & delba) override virtual
Implements inet::ieee80211::IOriginatorBlockAckAgreementHandler.
 {
     terminateAgreement(delba->getReceiverAddress(), delba->getTid());
 }
scheduleInactivityTimer()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::scheduleInactivityTimer (IBlockAckAgreementHandlerCallback * callback) protected virtual
 {
     simtime_t earliestExpirationTime = computeEarliestExpirationTime();
     if (earliestExpirationTime != SIMTIME_MAX)
         callback->scheduleInactivityTimer(earliestExpirationTime);
 }
Referenced by blockAckAgreementExpired(), processReceivedAddbaResp(), and processReceivedBlockAck().
terminateAgreement()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::terminateAgreement (MacAddress originatorAddr, Tid tid) protected virtual
 {
     auto agreementId = std::make_pair(originatorAddr, tid);
     auto it = blockAckAgreements.find(agreementId);
     if (it != blockAckAgreements.end()) {
         OriginatorBlockAckAgreement *agreement = it->second;
         blockAckAgreements.erase(it);
         delete agreement;
     }
 }
Referenced by processReceivedDelba(), and processTransmittedDelba().
updateAgreement()
void inet::ieee80211::OriginatorBlockAckAgreementHandler::updateAgreement (OriginatorBlockAckAgreement * agreement, const Ptr< const Ieee80211AddbaResponse > & addbaResp) protected virtual
 {
     agreement->setIsAddbaResponseReceived(true);
     agreement->setBufferSize(addbaResp->getBufferSize());
     agreement->setBlockAckTimeoutValue(addbaResp->getBlockAckTimeoutValue());
     agreement->calculateExpirationTime();
 }
Referenced by processReceivedAddbaResp().
Member Data Documentation
blockAckAgreements
std::map<std::pair<MacAddress, Tid>, OriginatorBlockAckAgreement *> inet::ieee80211::OriginatorBlockAckAgreementHandler::blockAckAgreements protected
Referenced by blockAckAgreementExpired(), computeEarliestExpirationTime(), createAgreement(), getAgreement(), terminateAgreement(), and ~OriginatorBlockAckAgreementHandler().
The documentation for this class was generated from the following files:
OriginatorBlockAckAgreementHandler.h
OriginatorBlockAckAgreementHandler.cc