INET Framework for OMNeT++/OMNEST: inet::physicallayer::IErrorModel Class Reference
inet::physicallayer::IErrorModel Class Reference abstract
The error model describes how the signal to noise ratio affects the amount of errors at the receiver.
#include <IErrorModel.h>
Public Member Functions
virtual Packet * computeCorruptedPacket (const ISnir *snir) const =0
virtual double computePacketErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const =0
Returns the packet error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeBitErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const =0
Returns the bit error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeSymbolErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const =0
Returns the symbol error rate based on SNIR, modulation, and any other physical layer characteristics.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
The error model describes how the signal to noise ratio affects the amount of errors at the receiver.
The main purpose of this model is to determine whether if the received packet has errors or not. It also computes various physical layer indications for higher layers such as packet error rate, bit error rate, and symbol error rate.
Member Function Documentation
computeBitErrorRate()
virtual double inet::physicallayer::IErrorModel::computeBitErrorRate (const ISnir * snir, IRadioSignal::SignalPart part) const pure virtual
Returns the bit error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
Implemented in inet::physicallayer::Ieee80211ErrorModelBase, inet::physicallayer::StochasticErrorModel, inet::physicallayer::Ieee80211BerTableErrorModel, and inet::physicallayer::ApskErrorModel.
Referenced by inet::physicallayer::ErrorModelBase::computeCorruptedPacket(), and inet::physicallayer::FlatReceiverBase::computeReceptionResult().
computeCorruptedPacket()
virtual Packet* inet::physicallayer::IErrorModel::computeCorruptedPacket (const ISnir * snir) const pure virtual
Implemented in inet::physicallayer::ErrorModelBase.
Referenced by inet::physicallayer::FlatReceiverBase::computeReceivedPacket().
computePacketErrorRate()
virtual double inet::physicallayer::IErrorModel::computePacketErrorRate (const ISnir * snir, IRadioSignal::SignalPart part) const pure virtual
Returns the packet error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
Implemented in inet::physicallayer::Ieee80211ErrorModelBase, inet::physicallayer::StochasticErrorModel, inet::physicallayer::Ieee80211BerTableErrorModel, and inet::physicallayer::ApskErrorModel.
Referenced by inet::physicallayer::FlatReceiverBase::computeIsReceptionSuccessful(), and inet::physicallayer::FlatReceiverBase::computeReceptionResult().
computeSymbolErrorRate()
virtual double inet::physicallayer::IErrorModel::computeSymbolErrorRate (const ISnir * snir, IRadioSignal::SignalPart part) const pure virtual
Returns the symbol error rate based on SNIR, modulation, and any other physical layer characteristics.
Implemented in inet::physicallayer::Ieee80211ErrorModelBase, inet::physicallayer::StochasticErrorModel, inet::physicallayer::Ieee80211BerTableErrorModel, and inet::physicallayer::ApskErrorModel.
Referenced by inet::physicallayer::FlatReceiverBase::computeReceptionResult().
The documentation for this class was generated from the following file:
IErrorModel.h