INET Framework for OMNeT++/OMNEST: inet::queueing::PacketFilterBase Class Reference
inet::queueing::PacketFilterBase Class Reference
#include <PacketFilterBase.h>
Public Member Functions
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
virtual bool canPullSomePacket (cGate *gate) const override
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const override
Returns the packet that can be pulled at the given gate.
virtual Packet * pullPacket (cGate *gate) override
Pulls the packet from the packet source at the given gate.
virtual Packet * pullPacketStart (cGate *gate, bps datarate) override
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate) override
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength) override
Progresses pulling the packet from the packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPacketFilter
virtual bool matchesPacket (const Packet *packet) const =0
Returns true if the filter matches the given packet.
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void processPacket (Packet *packet)
virtual bool isStreamingPacket () const
virtual void startPacketStreaming (Packet *packet)
virtual void endPacketStreaming (Packet *packet)
virtual void checkPacketStreaming (Packet *packet)
virtual void dropPacket (Packet *packet)
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1) override
virtual const char * resolveDirective (char directive) const override
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void updateDisplayString () const
Protected Attributes
bool backpressure = false
cGate * inputGate = nullptr
ModuleRef< IActivePacketSource > producer
ModuleRef< IPassivePacketSource > provider
cGate * outputGate = nullptr
ModuleRef< IPassivePacketSink > consumer
ModuleRef< IActivePacketSink > collector
int inProgressStreamId = -1
int numDroppedPackets = 0
b droppedTotalLength = b(-1)
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
canPullPacket()
Packet * inet::queueing::PacketFilterBase::canPullPacket (cGate * gate) const override virtual
Returns the packet that can be pulled at the given gate.
The returned value is nullptr if there is no such packet.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("canPullPacket");
     auto providerGate = inputGate->getPathStartGate();
     while (true) {
         auto packet = provider->canPullPacket(providerGate);
         if (packet == nullptr)
             return nullptr;
         else if (matchesPacket(packet))
             return packet;
         else if (backpressure)
             return nullptr;
         else {
             auto nonConstThisPtr = const_cast<PacketFilterBase *>(this);
             packet = provider->pullPacket(providerGate);
             nonConstThisPtr->take(packet);
             nonConstThisPtr->emit(packetPulledInSignal, packet);
             EV_INFO << "Filtering out packet" << EV_FIELD(packet) << EV_ENDL;
             // KLUDGE
             nonConstThisPtr->handlePacketProcessed(packet);
             nonConstThisPtr->dropPacket(packet);
             updateDisplayString();
         }
     }
 }
Referenced by canPullSomePacket().
canPullSomePacket()
bool inet::queueing::PacketFilterBase::canPullSomePacket (cGate * gate) const override virtual
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
The gate must be a valid gate of this module and it must support pulling packets.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("canPullSomePacket");
     return canPullPacket(gate) != nullptr;
 }
canPushPacket()
bool inet::queueing::PacketFilterBase::canPushPacket (Packet * packet, cGate * gate) const override virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     if (backpressure)
         return matchesPacket(packet) && consumer != nullptr && consumer->canPushPacket(packet, outputGate->getPathEndGate());
     else
         return !matchesPacket(packet) || consumer == nullptr || consumer->canPushPacket(packet, outputGate->getPathEndGate());
 }
canPushSomePacket()
bool inet::queueing::PacketFilterBase::canPushSomePacket (cGate * gate) const override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     return consumer == nullptr || consumer->canPushSomePacket(outputGate->getPathEndGate());
 }
checkPacketStreaming()
void inet::queueing::PacketFilterBase::checkPacketStreaming (Packet * packet) protected virtual
 {
     if (inProgressStreamId != -1 && (packet == nullptr || packet->getTreeId() != inProgressStreamId))
         throw cRuntimeError("Another packet streaming operation is already in progress");
 }
Referenced by pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
dropPacket() [1/2]
void inet::queueing::PacketFilterBase::dropPacket (Packet * packet) protected virtual
Reimplemented in inet::queueing::OrdinalBasedDropper, inet::Ieee8021qTagEpdHeaderChecker, inet::VlanIndFilter, inet::VlanReqFilter, inet::EthernetAddressChecker, inet::EthernetMacHeaderChecker, inet::physicallayer::EthernetFragmentPhyHeaderChecker, inet::EthernetFragmentFcsChecker, inet::Ieee8021qTagTpidHeaderChecker, inet::Ieee8021rTagEpdHeaderChecker, inet::Ieee8022SnapChecker, inet::ProtocolChecker, inet::Ieee8022LlcChecker, inet::physicallayer::EthernetPhyHeaderChecker, inet::EthernetFcsChecker, inet::EthernetTypeOrLengthChecker, and inet::Ieee8021aeTagEpdHeaderChecker.
 {
     dropPacket(packet, OTHER_PACKET_DROP);
 }
Referenced by inet::EthernetTypeOrLengthChecker::dropPacket(), inet::Ieee8021aeTagEpdHeaderChecker::dropPacket(), inet::EthernetFcsChecker::dropPacket(), inet::physicallayer::EthernetPhyHeaderChecker::dropPacket(), inet::Ieee8022LlcChecker::dropPacket(), inet::ProtocolChecker::dropPacket(), inet::Ieee8022SnapChecker::dropPacket(), inet::Ieee8021qTagTpidHeaderChecker::dropPacket(), inet::Ieee8021rTagEpdHeaderChecker::dropPacket(), inet::EthernetFragmentFcsChecker::dropPacket(), inet::physicallayer::EthernetFragmentPhyHeaderChecker::dropPacket(), inet::EthernetAddressChecker::dropPacket(), inet::EthernetMacHeaderChecker::dropPacket(), inet::VlanReqFilter::dropPacket(), inet::Ieee8021qTagEpdHeaderChecker::dropPacket(), inet::VlanIndFilter::dropPacket(), pullPacket(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
dropPacket() [2/2]
void inet::queueing::PacketFilterBase::dropPacket (Packet * packet, PacketDropReason reason, int limit = -1) override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     numDroppedPackets++;
     droppedTotalLength += packet->getTotalLength();
     PacketProcessorBase::dropPacket(packet, reason, limit);
 }
endPacketStreaming()
void inet::queueing::PacketFilterBase::endPacketStreaming (Packet * packet) protected virtual
 {
     emit(packetPushedInSignal, packet);
     handlePacketProcessed(packet);
     inProgressStreamId = -1;
 }
Referenced by pushPacketEnd(), and pushPacketProgress().
getConsumer()
virtual IPassivePacketSink* inet::queueing::PacketFilterBase::getConsumer (cGate * gate) inline override virtual
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
 { return this; }
getProvider()
virtual IPassivePacketSource* inet::queueing::PacketFilterBase::getProvider (cGate * gate) inline override virtual
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
 { return this; }
handleCanPullPacketChanged()
void inet::queueing::PacketFilterBase::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handleCanPullPacketChanged");
     if (collector != nullptr)
         collector->handleCanPullPacketChanged(outputGate->getPathEndGate());
 }
handleCanPushPacketChanged()
void inet::queueing::PacketFilterBase::handleCanPushPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
This method is called, for example, when a new packet can be inserted into a queue. It allows the source to push a new packet into the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
 {
     Enter_Method("handleCanPushPacketChanged");
     if (producer != nullptr)
         producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
 }
handleMessage()
void inet::queueing::PacketFilterBase::handleMessage (cMessage * message) override protected virtual
 {
     auto packet = check_and_cast<Packet *>(message);
     pushPacket(packet, packet->getArrivalGate());
 }
handlePullPacketProcessed()
void inet::queueing::PacketFilterBase::handlePullPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pulled packet is failed to be processed successfully. It allows the sink to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handlePullPacketProcessed");
     if (collector != nullptr)
         collector->handlePullPacketProcessed(packet, outputGate->getPathEndGate(), successful);
 }
handlePushPacketProcessed()
void inet::queueing::PacketFilterBase::handlePushPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pushed packet is failed to be processed successfully. It allows the source to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSource.
 {
     producer->handlePushPacketProcessed(packet, inputGate->getPathStartGate(), successful);
 }
initialize()
void inet::queueing::PacketFilterBase::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
Reimplemented in inet::queueing::RedDropper, inet::queueing::OrdinalBasedDropper, inet::VlanIndFilter, inet::VlanReqFilter, inet::StreamMerger, inet::EthernetAddressChecker, inet::EthernetMacHeaderChecker, inet::Ieee8021qTagEpdHeaderChecker, inet::EligibilityTimeFilter, inet::Ieee8021qTagTpidHeaderChecker, inet::Ieee8021rTagEpdHeaderChecker, inet::CrcHeaderChecker, inet::FcsHeaderChecker, inet::ProtocolChecker, inet::StreamFilter, inet::ReceiveAtL3Address, inet::queueing::LabelFilter, inet::queueing::StatisticalRateLimiter, inet::Ieee8022SnapChecker, inet::ReceiveAtMacAddress, inet::ReceiveAtPort, inet::queueing::ContentBasedFilter, inet::queueing::PacketFilter, inet::Ieee8022LlcChecker, and inet::ReceiveWithHopLimit.
 {
     PacketProcessorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         backpressure = par("backpressure");
         inputGate = gate("in");
         outputGate = gate("out");
         producer.reference(inputGate, false);
         collector.reference(outputGate, false);
         provider.reference(inputGate, false);
         consumer.reference(outputGate, false);
         numDroppedPackets = 0;
         droppedTotalLength = b(0);
     }
     else if (stage == INITSTAGE_QUEUEING) {
         checkPacketOperationSupport(inputGate);
         checkPacketOperationSupport(outputGate);
     }
 }
Referenced by inet::ReceiveWithHopLimit::initialize(), inet::Ieee8022LlcChecker::initialize(), inet::queueing::ContentBasedFilter::initialize(), inet::ReceiveAtPort::initialize(), inet::ReceiveAtMacAddress::initialize(), inet::Ieee8022SnapChecker::initialize(), inet::queueing::PacketFilter::initialize(), inet::queueing::StatisticalRateLimiter::initialize(), inet::CrcHeaderChecker::initialize(), inet::Ieee8021rTagEpdHeaderChecker::initialize(), inet::ReceiveAtL3Address::initialize(), inet::StreamFilter::initialize(), inet::FcsHeaderChecker::initialize(), inet::queueing::LabelFilter::initialize(), inet::Ieee8021qTagTpidHeaderChecker::initialize(), inet::ProtocolChecker::initialize(), inet::EthernetMacHeaderChecker::initialize(), inet::EthernetAddressChecker::initialize(), inet::Ieee8021qTagEpdHeaderChecker::initialize(), inet::StreamMerger::initialize(), inet::VlanIndFilter::initialize(), inet::VlanReqFilter::initialize(), inet::queueing::OrdinalBasedDropper::initialize(), and inet::queueing::RedDropper::initialize().
isStreamingPacket()
virtual bool inet::queueing::PacketFilterBase::isStreamingPacket () const inline protected virtual
 { return inProgressStreamId != -1; }
Referenced by pushPacketEnd(), and pushPacketProgress().
processPacket()
virtual void inet::queueing::PacketFilterBase::processPacket (Packet * packet) inline protected virtual
Reimplemented in inet::queueing::RedDropper, inet::queueing::OrdinalBasedDropper, inet::StreamMerger, inet::Ieee8021qTagEpdHeaderChecker, inet::VlanIndFilter, inet::VlanReqFilter, inet::EthernetAddressChecker, inet::EthernetMacHeaderChecker, inet::physicallayer::EthernetFragmentPhyHeaderChecker, inet::EthernetFragmentFcsChecker, inet::Ieee8021qTagTpidHeaderChecker, inet::Ieee8021rTagEpdHeaderChecker, inet::CrcHeaderChecker, inet::FcsHeaderChecker, inet::ReceiveAtL3Address, inet::Ieee8022SnapChecker, inet::ReceiveAtMacAddress, inet::ReceiveAtPort, inet::Ieee8022LlcChecker, inet::physicallayer::EthernetPhyHeaderChecker, inet::EthernetFcsChecker, inet::ReceiveWithHopLimit, inet::EthernetTypeOrLengthChecker, and inet::Ieee8021aeTagEpdHeaderChecker.
 {}
Referenced by pullPacket(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
pullPacket()
Packet * inet::queueing::PacketFilterBase::pullPacket (cGate * gate) override virtual
Pulls the packet from the packet source at the given gate.
This operation pulls the packet as a whole. The onwership of the packet is transferred to the sink.
The source must not be empty at the given gate. The returned packet must not be nullptr. The gate must be a valid gate of this module and it must support pulling and passing packets.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacket");
     auto providerGate = inputGate->getPathStartGate();
     while (true) {
         auto packet = provider->pullPacket(providerGate);
         take(packet);
         emit(packetPulledInSignal, packet);
         if (matchesPacket(packet)) {
             processPacket(packet);
             handlePacketProcessed(packet);
             EV_INFO << "Passing through packet" << EV_FIELD(packet) << EV_ENDL;
             animatePullPacket(packet, outputGate);
             updateDisplayString();
             emit(packetPulledOutSignal, packet);
             return packet;
         }
         else {
             EV_INFO << "Filtering out packet" << EV_FIELD(packet) << EV_ENDL;
             handlePacketProcessed(packet);
             dropPacket(packet);
         }
     }
 }
pullPacketEnd()
Packet * inet::queueing::PacketFilterBase::pullPacketEnd (cGate * gate) override virtual
Ends pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet from the the source.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacketEnd");
     throw cRuntimeError("Invalid operation");
 }
pullPacketProgress()
Packet * inet::queueing::PacketFilterBase::pullPacketProgress (cGate * gate, bps datarate, b position, b extraProcessableLength) override virtual
Progresses pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the source about a change in the packet data when a preemption occurs.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacketProgress");
     throw cRuntimeError("Invalid operation");
 }
pullPacketStart()
Packet * inet::queueing::PacketFilterBase::pullPacketStart (cGate * gate, bps datarate) override virtual
Starts pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet from the source.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacketStart");
     throw cRuntimeError("Invalid operation");
 }
pushPacket()
void inet::queueing::PacketFilterBase::pushPacket (Packet * packet, cGate * gate) override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacket");
     take(packet);
     checkPacketStreaming(nullptr);
     emit(packetPushedInSignal, packet);
     if (matchesPacket(packet)) {
         processPacket(packet);
         handlePacketProcessed(packet);
         EV_INFO << "Passing through packet" << EV_FIELD(packet) << EV_ENDL;
         emit(packetPushedOutSignal, packet);
         pushOrSendPacket(packet, outputGate, consumer);
     }
     else {
         EV_INFO << "Filtering out packet" << EV_FIELD(packet) << EV_ENDL;
         handlePacketProcessed(packet);
         dropPacket(packet);
     }
     updateDisplayString();
 }
Referenced by handleMessage().
pushPacketEnd()
void inet::queueing::PacketFilterBase::pushPacketEnd (Packet * packet, cGate * gate) override virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketEnd");
     take(packet);
     if (!isStreamingPacket())
         startPacketStreaming(packet);
     else
         checkPacketStreaming(packet);
     if (matchesPacket(packet)) {
         processPacket(packet);
         EV_INFO << "Passing through packet" << EV_FIELD(packet) << EV_ENDL;
         endPacketStreaming(packet);
         emit(packetPushedOutSignal, packet);
         pushOrSendPacketEnd(packet, outputGate, consumer, packet->getTransmissionId());
     }
     else {
         EV_INFO << "Filtering out packet" << EV_FIELD(packet) << EV_ENDL;
         endPacketStreaming(packet);
         dropPacket(packet);
     }
     updateDisplayString();
 }
pushPacketProgress()
void inet::queueing::PacketFilterBase::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) override virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketProgress");
     take(packet);
     if (!isStreamingPacket())
         startPacketStreaming(packet);
     else
         checkPacketStreaming(packet);
     if (matchesPacket(packet)) {
         processPacket(packet);
         EV_INFO << "Passing through packet" << EV_FIELD(packet) << EV_ENDL;
         if (packet->getTotalLength() == position + extraProcessableLength)
             endPacketStreaming(packet);
         pushOrSendPacketProgress(packet, outputGate, consumer, datarate, position, extraProcessableLength, packet->getTransmissionId());
     }
     else {
         EV_INFO << "Filtering out packet" << EV_FIELD(packet) << EV_ENDL;
         endPacketStreaming(packet);
         dropPacket(packet);
     }
     updateDisplayString();
 }
pushPacketStart()
void inet::queueing::PacketFilterBase::pushPacketStart (Packet * packet, cGate * gate, bps datarate) override virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketStart");
     take(packet);
     checkPacketStreaming(packet);
     startPacketStreaming(packet);
     if (matchesPacket(packet)) {
         processPacket(packet);
         EV_INFO << "Passing through packet" << EV_FIELD(packet) << EV_ENDL;
         pushOrSendPacketStart(packet, outputGate, consumer, datarate, packet->getTransmissionId());
     }
     else {
         EV_INFO << "Filtering out packet" << EV_FIELD(packet) << EV_ENDL;
         dropPacket(packet);
     }
     updateDisplayString();
 }
resolveDirective()
const char * inet::queueing::PacketFilterBase::resolveDirective (char directive) const override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     static std::string result;
     switch (directive) {
         case 'd':
             result = std::to_string(numDroppedPackets);
             break;
         case 'k':
             result = droppedTotalLength.str();
             break;
         default:
             return PacketProcessorBase::resolveDirective(directive);
     }
     return result.c_str();
 }
startPacketStreaming()
void inet::queueing::PacketFilterBase::startPacketStreaming (Packet * packet) protected virtual
 {
     inProgressStreamId = packet->getTreeId();
 }
Referenced by pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
supportsPacketPulling()
virtual bool inet::queueing::PacketFilterBase::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return true; }
supportsPacketPushing()
virtual bool inet::queueing::PacketFilterBase::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return true; }
supportsPacketStreaming()
virtual bool inet::queueing::PacketFilterBase::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return true; }
Member Data Documentation
backpressure
bool inet::queueing::PacketFilterBase::backpressure = false protected
Referenced by canPullPacket(), canPushPacket(), and initialize().
collector
ModuleRef<IActivePacketSink> inet::queueing::PacketFilterBase::collector protected
Referenced by handleCanPullPacketChanged(), handlePullPacketProcessed(), and initialize().
consumer
ModuleRef<IPassivePacketSink> inet::queueing::PacketFilterBase::consumer protected
Referenced by canPushPacket(), canPushSomePacket(), initialize(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
droppedTotalLength
b inet::queueing::PacketFilterBase::droppedTotalLength = b(-1) protected
Referenced by dropPacket(), initialize(), and resolveDirective().
inProgressStreamId
int inet::queueing::PacketFilterBase::inProgressStreamId = -1 protected
Referenced by checkPacketStreaming(), endPacketStreaming(), and startPacketStreaming().
inputGate
cGate* inet::queueing::PacketFilterBase::inputGate = nullptr protected
Referenced by canPullPacket(), inet::queueing::StatisticalRateLimiter::getRegistrationForwardingGate(), inet::queueing::LabelFilter::getRegistrationForwardingGate(), inet::EligibilityTimeFilter::getRegistrationForwardingGate(), inet::VlanReqFilter::getRegistrationForwardingGate(), inet::VlanIndFilter::getRegistrationForwardingGate(), inet::StreamMerger::getRegistrationForwardingGate(), handleCanPushPacketChanged(), handlePushPacketProcessed(), inet::ReceiveWithHopLimit::initialize(), inet::Ieee8022LlcChecker::initialize(), inet::ReceiveAtMacAddress::initialize(), inet::Ieee8022SnapChecker::initialize(), inet::ReceiveAtPort::initialize(), inet::CrcHeaderChecker::initialize(), inet::FcsHeaderChecker::initialize(), inet::ReceiveAtL3Address::initialize(), inet::Ieee8021rTagEpdHeaderChecker::initialize(), inet::EthernetMacHeaderChecker::initialize(), inet::Ieee8021qTagEpdHeaderChecker::initialize(), inet::EthernetAddressChecker::initialize(), initialize(), and pullPacket().
numDroppedPackets
int inet::queueing::PacketFilterBase::numDroppedPackets = 0 protected
Referenced by dropPacket(), initialize(), and resolveDirective().
outputGate
cGate* inet::queueing::PacketFilterBase::outputGate = nullptr protected
Referenced by canPushPacket(), canPushSomePacket(), inet::queueing::LabelFilter::getRegistrationForwardingGate(), inet::queueing::StatisticalRateLimiter::getRegistrationForwardingGate(), inet::EligibilityTimeFilter::getRegistrationForwardingGate(), inet::VlanIndFilter::getRegistrationForwardingGate(), inet::VlanReqFilter::getRegistrationForwardingGate(), inet::StreamMerger::getRegistrationForwardingGate(), handleCanPullPacketChanged(), handlePullPacketProcessed(), inet::ProtocolChecker::handleRegisterProtocol(), inet::ReceiveWithHopLimit::initialize(), inet::Ieee8022LlcChecker::initialize(), inet::ReceiveAtMacAddress::initialize(), inet::Ieee8022SnapChecker::initialize(), inet::ReceiveAtPort::initialize(), inet::CrcHeaderChecker::initialize(), inet::FcsHeaderChecker::initialize(), inet::ReceiveAtL3Address::initialize(), initialize(), inet::queueing::RedDropper::initialize(), pullPacket(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
producer
ModuleRef<IActivePacketSource> inet::queueing::PacketFilterBase::producer protected
Referenced by handleCanPushPacketChanged(), handlePushPacketProcessed(), and initialize().
provider
ModuleRef<IPassivePacketSource> inet::queueing::PacketFilterBase::provider protected
Referenced by canPullPacket(), initialize(), and pullPacket().
The documentation for this class was generated from the following files:
PacketFilterBase.h
PacketFilterBase.cc