INET Framework for OMNeT++/OMNEST: inet::visualizer::PacketDropVisualizerBase::DetailsFilter Class Reference
inet::visualizer::PacketDropVisualizerBase::DetailsFilter Class Reference
#include <PacketDropVisualizerBase.h>
Public Member Functions
void setPattern (const char *pattern)
bool matches (const PacketDropDetails *details) const
Protected Attributes
cMatchExpression matchExpression
Member Function Documentation
matches()
bool inet::visualizer::PacketDropVisualizerBase::DetailsFilter::matches (const PacketDropDetails * details) const
 {
     MatchableObject matchableObject(MatchableObject::ATTRIBUTE_FULLNAME, details);
     return matchExpression.matches(&matchableObject);
 }
Referenced by inet::visualizer::PacketDropVisualizerBase::receiveSignal().
setPattern()
void inet::visualizer::PacketDropVisualizerBase::DetailsFilter::setPattern (const char * pattern)
 {
     matchExpression.setPattern(pattern, true, true, true);
 }
Referenced by inet::visualizer::PacketDropVisualizerBase::handleParameterChange(), and inet::visualizer::PacketDropVisualizerBase::initialize().
Member Data Documentation
matchExpression
cMatchExpression inet::visualizer::PacketDropVisualizerBase::DetailsFilter::matchExpression protected
The documentation for this class was generated from the following files:
PacketDropVisualizerBase.h
PacketDropVisualizerBase.cc