INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211ModeSet Class Reference
inet::physicallayer::Ieee80211ModeSet Class Reference
#include <Ieee80211ModeSet.h>
Classes
class Entry
struct EntryNetBitrateComparator
Public Member Functions
Ieee80211ModeSet (const char *name, const std::vector< Entry > entries)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
const char * getName () const override
bool containsMode (const IIeee80211Mode *mode) const
bool getIsMandatory (const IIeee80211Mode *mode) const
const IIeee80211Mode * findMode (bps bitrate, Hz bandwidth=Hz(NaN), int numSpatialStreams=-1) const
const IIeee80211Mode * findMode (bps minBitrate, bps maxBitrate, Hz bandwidth=Hz(NaN), int numSpatialStreams=-1) const
const IIeee80211Mode * getMode (bps bitrate, Hz bandwidth=Hz(NaN), int numSpatialStreams=-1) const
const IIeee80211Mode * getMode (bps minBitrate, bps maxBitrate, Hz bandwidth=Hz(NaN), int numSpatialStreams=-1) const
const IIeee80211Mode * getSlowestMode () const
const IIeee80211Mode * getFastestMode () const
const IIeee80211Mode * getSlowerMode (const IIeee80211Mode *mode) const
const IIeee80211Mode * getFasterMode (const IIeee80211Mode *mode) const
const IIeee80211Mode * getSlowestMandatoryMode () const
const IIeee80211Mode * getFastestMandatoryMode () const
const IIeee80211Mode * getSlowerMandatoryMode (const IIeee80211Mode *mode) const
const IIeee80211Mode * getFasterMandatoryMode (const IIeee80211Mode *mode) const
simtime_t getSifsTime () const
simtime_t getSlotTime () const
simtime_t getPhyRxStartDelay () const
int getCwMin () const
int getCwMax () const
IIeee80211Mode * _getSlowestMode () const
IIeee80211Mode * _getFastestMode () const
IIeee80211Mode * _getSlowestMandatoryMode () const
IIeee80211Mode * _getFastestMandatoryMode () const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Member Functions
static const Ieee80211ModeSet * findModeSet (const char *mode)
static const Ieee80211ModeSet * getModeSet (const char *mode)
Static Public Attributes
static const DelayedInitializer< std::vector< Ieee80211ModeSet > > modeSets
Protected Member Functions
int findModeIndex (const IIeee80211Mode *mode) const
int getModeIndex (const IIeee80211Mode *mode) const
Protected Attributes
std::string name
const std::vector< Entry > entries
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211ModeSet()
inet::physicallayer::Ieee80211ModeSet::Ieee80211ModeSet (const char * name, const std::vector< Entry > entries)
                                                                                    :
     name(name),
     entries(entries)
 {
     std::vector<Entry> *nonConstEntries = const_cast<std::vector<Entry> *>(&this->entries);
     std::stable_sort(nonConstEntries->begin(), nonConstEntries->end(), EntryNetBitrateComparator());
     auto referenceMode = entries[0].mode;
     for (auto entry : entries) {
         auto mode = entry.mode;
         if (mode->getSifsTime() != referenceMode->getSifsTime() ||
             mode->getSlotTime() != referenceMode->getSlotTime() ||
             mode->getPhyRxStartDelay() != referenceMode->getPhyRxStartDelay())
         {
             // FIXME throw cRuntimeError("Sifs, slot and phyRxStartDelay time must be identical within a ModeSet");
         }
     }
 }
Member Function Documentation
_getFastestMandatoryMode()
IIeee80211Mode* inet::physicallayer::Ieee80211ModeSet::_getFastestMandatoryMode () const inline
 { return const_cast<IIeee80211Mode *>(getFastestMandatoryMode()); }
_getFastestMode()
IIeee80211Mode* inet::physicallayer::Ieee80211ModeSet::_getFastestMode () const inline
 { return const_cast<IIeee80211Mode *>(getFastestMode()); }
_getSlowestMandatoryMode()
IIeee80211Mode* inet::physicallayer::Ieee80211ModeSet::_getSlowestMandatoryMode () const inline
 { return const_cast<IIeee80211Mode *>(getSlowestMandatoryMode()); }
_getSlowestMode()
IIeee80211Mode* inet::physicallayer::Ieee80211ModeSet::_getSlowestMode () const inline
 { return const_cast<IIeee80211Mode *>(getSlowestMode()); }
containsMode()
bool inet::physicallayer::Ieee80211ModeSet::containsMode (const IIeee80211Mode * mode) const inline
 { return findModeIndex(mode) != -1; }
Referenced by inet::physicallayer::Ieee80211DimensionalReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211ScalarReceiver::computeIsReceptionPossible(), and inet::physicallayer::Ieee80211TransmitterBase::computeTransmissionMode().
findMode() [1/2]
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::findMode (bps bitrate, Hz bandwidth = Hz(NaN), int numSpatialStreams = -1) const
 {
     return findMode(bitrate - Mbps(0.05), bitrate + Mbps(0.05), bandwidth, numSpatialStreams);
 }
Referenced by getMode(), and inet::physicallayer::Ieee80211TransmitterBase::setMode().
findMode() [2/2]
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::findMode (bps minBitrate, bps maxBitrate, Hz bandwidth = Hz(NaN), int numSpatialStreams = -1) const
 {
     for (size_t index = 0; index < entries.size(); index++) {
         auto mode = entries[index].mode;
         auto dataMode = mode->getDataMode();
         auto bitrate = dataMode->getNetBitrate();
         if (minBitrate <= bitrate && bitrate <= maxBitrate &&
             (std::isnan(bandwidth.get()) || dataMode->getBandwidth() == bandwidth) &&
             (numSpatialStreams == -1 || dataMode->getNumberOfSpatialStreams() == numSpatialStreams))
         {
             return entries[index].mode;
         }
     }
     return nullptr;
 }
findModeIndex()
int inet::physicallayer::Ieee80211ModeSet::findModeIndex (const IIeee80211Mode * mode) const protected
 {
     for (int index = 0; index < (int)entries.size(); index++)
         if (entries[index].mode == mode)
             return index;
     return -1;
 }
Referenced by getFasterMandatoryMode(), getFasterMode(), getModeIndex(), getSlowerMandatoryMode(), and getSlowerMode().
findModeSet()
const Ieee80211ModeSet * inet::physicallayer::Ieee80211ModeSet::findModeSet (const char * mode) static
 {
     for (int index = 0; index < (int)(&modeSets)->size(); index++) {
         const Ieee80211ModeSet *modeSet = &(&modeSets)->at(index);
         if (strcmp(modeSet->getName(), mode) == 0)
             return modeSet;
     }
     return nullptr;
 }
Referenced by getModeSet().
getCwMax()
int inet::physicallayer::Ieee80211ModeSet::getCwMax () const inline
 { return entries[0].mode->getLegacyCwMax(); }
getCwMin()
int inet::physicallayer::Ieee80211ModeSet::getCwMin () const inline
 { return entries[0].mode->getLegacyCwMin(); }
getFasterMandatoryMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getFasterMandatoryMode (const IIeee80211Mode * mode) const
 {
     int index = findModeIndex(mode);
     if (index >= 0)
         for (int i = index + 1; i < (int)entries.size(); i++)
             if (entries[i].isMandatory)
                 return entries[i].mode;
     return nullptr;
 }
getFasterMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getFasterMode (const IIeee80211Mode * mode) const
 {
     int index = findModeIndex(mode);
     if (index >= 0 && index < (int)entries.size() - 1)
         return entries[index + 1].mode;
     else
         return nullptr;
 }
getFastestMandatoryMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getFastestMandatoryMode () const
 {
     for (int i = (int)entries.size() - 1; i >= 0; i--)
         if (entries[i].isMandatory)
             return entries[i].mode;
     return nullptr;
 }
getFastestMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getFastestMode () const
 {
     return entries.back().mode;
 }
Referenced by inet::physicallayer::Ieee80211TransmitterBase::initialize().
getIsMandatory()
bool inet::physicallayer::Ieee80211ModeSet::getIsMandatory (const IIeee80211Mode * mode) const
 {
     return entries[getModeIndex(mode)].isMandatory;
 }
getMode() [1/2]
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getMode (bps bitrate, Hz bandwidth = Hz(NaN), int numSpatialStreams = -1) const
 {
     const IIeee80211Mode *mode = getMode(bitrate - Mbps(0.05), bitrate + Mbps(0.05), bandwidth, numSpatialStreams);
     if (mode == nullptr)
         throw cRuntimeError("Unknown bitrate: %g in operation mode: '%s'", bitrate.get(), getName());
     else
         return mode;
 }
Referenced by inet::physicallayer::Ieee80211TransmitterBase::computeTransmissionMode(), inet::physicallayer::Ieee80211TransmitterBase::initialize(), and inet::physicallayer::Ieee80211TransmitterBase::setModeSet().
getMode() [2/2]
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getMode (bps minBitrate, bps maxBitrate, Hz bandwidth = Hz(NaN), int numSpatialStreams = -1) const
 {
     const IIeee80211Mode *mode = findMode(minBitrate, maxBitrate, bandwidth, numSpatialStreams);
     if (mode == nullptr)
         throw cRuntimeError("Unknown bitrate: (%g - %g) in operation mode: '%s'", minBitrate.get(), maxBitrate.get(), getName());
     else
         return mode;
 }
getModeIndex()
int inet::physicallayer::Ieee80211ModeSet::getModeIndex (const IIeee80211Mode * mode) const protected
 {
     int index = findModeIndex(mode);
     if (index < 0)
         throw cRuntimeError("Unknown mode");
     else
         return index;
 }
Referenced by getIsMandatory().
getModeSet()
const Ieee80211ModeSet * inet::physicallayer::Ieee80211ModeSet::getModeSet (const char * mode) static
 {
     const Ieee80211ModeSet *modeSet = findModeSet(mode);
     if (modeSet == nullptr) {
         std::string validModeSets;
         for (size_t index = 0; index < (&modeSets)->size(); index++) {
             const Ieee80211ModeSet *modeSet = &(&modeSets)->at(index);
             validModeSets += std::string("'") + modeSet->getName() + "' ";
         }
         throw cRuntimeError("Unknown 802.11 operational mode: '%s', valid modes are: %s", mode, validModeSets.c_str());
     }
     else
         return modeSet;
 }
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand(), inet::physicallayer::Ieee80211ReceiverBase::initialize(), inet::physicallayer::Ieee80211TransmitterBase::initialize(), and inet::ieee80211::Ieee80211Mac::initialize().
getName()
const char* inet::physicallayer::Ieee80211ModeSet::getName () const inline override
 { return name.c_str(); }
Referenced by findModeSet(), getMode(), and getModeSet().
getPhyRxStartDelay()
simtime_t inet::physicallayer::Ieee80211ModeSet::getPhyRxStartDelay () const inline
 { return entries[0].mode->getPhyRxStartDelay(); }
getSifsTime()
simtime_t inet::physicallayer::Ieee80211ModeSet::getSifsTime () const inline
 { return entries[0].mode->getSifsTime(); }
Referenced by inet::ieee80211::RecipientAckPolicy::computeAckDurationField(), inet::ieee80211::RecipientQosAckPolicy::computeAckDurationField(), inet::ieee80211::RecipientQosAckPolicy::computeBasicBlockAckDurationField(), inet::ieee80211::SingleProtectionMechanism::computeBlockAckReqDurationField(), inet::ieee80211::QosCtsPolicy::computeCtsDurationField(), inet::ieee80211::CtsPolicy::computeCtsDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField(), inet::ieee80211::OriginatorAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getBlockAckTimeout(), inet::ieee80211::QosRtsPolicy::getCtsTimeout(), inet::ieee80211::RtsPolicy::getCtsTimeout(), and inet::ieee80211::FrameSequenceContext::getIfs().
getSlotTime()
simtime_t inet::physicallayer::Ieee80211ModeSet::getSlotTime () const inline
 { return entries[0].mode->getSlotTime(); }
Referenced by inet::ieee80211::OriginatorAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getBlockAckTimeout(), inet::ieee80211::QosRtsPolicy::getCtsTimeout(), and inet::ieee80211::RtsPolicy::getCtsTimeout().
getSlowerMandatoryMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getSlowerMandatoryMode (const IIeee80211Mode * mode) const
 {
     int index = findModeIndex(mode);
     if (index > 0)
         for (int i = index - 1; i >= 0; i--)
             if (entries[i].isMandatory)
                 return entries[i].mode;
     return nullptr;
 }
getSlowerMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getSlowerMode (const IIeee80211Mode * mode) const
 {
     int index = findModeIndex(mode);
     if (index > 0)
         return entries[index - 1].mode;
     else
         return nullptr;
 }
getSlowestMandatoryMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getSlowestMandatoryMode () const
 {
     for (size_t i = 0; i < entries.size(); i++)
         if (entries[i].isMandatory)
             return entries[i].mode;
     return nullptr;
 }
getSlowestMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211ModeSet::getSlowestMode () const
 {
     return entries.front().mode;
 }
printToStream()
virtual std::ostream& inet::physicallayer::Ieee80211ModeSet::printToStream (std::ostream & stream, int level, int evFlags = 0) const inline override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 { return stream << "Ieee80211ModeSet, name = " << name; }
Member Data Documentation
entries
const std::vector<Entry> inet::physicallayer::Ieee80211ModeSet::entries protected
Referenced by findMode(), findModeIndex(), getFasterMandatoryMode(), getFasterMode(), getFastestMandatoryMode(), getFastestMode(), getIsMandatory(), getSlowerMandatoryMode(), getSlowerMode(), getSlowestMandatoryMode(), getSlowestMode(), and Ieee80211ModeSet().
modeSets
const DelayedInitializer< std::vector< Ieee80211ModeSet > > inet::physicallayer::Ieee80211ModeSet::modeSets static
Referenced by findModeSet(), and getModeSet().
name
std::string inet::physicallayer::Ieee80211ModeSet::name protected
The documentation for this class was generated from the following files:
Ieee80211ModeSet.h
Ieee80211ModeSet.cc