INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211YansErrorModel Class Reference
inet::physicallayer::Ieee80211YansErrorModel Class Reference
Model the error rate for different modulations.
#include <Ieee80211YansErrorModel.h>
Public Member Functions
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::physicallayer::Ieee80211ErrorModelBase
Ieee80211ErrorModelBase ()
virtual double computePacketErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the packet error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeBitErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the bit error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeSymbolErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the symbol error rate based on SNIR, modulation, and any other physical layer characteristics.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
double getBpskBer (double snr, Hz signalSpread, bps phyRate) const
double getQamBer (double snr, unsigned int m, Hz signalSpread, bps phyRate) const
uint32_t factorial (uint32_t k) const
double binomialCoefficient (uint32_t k, double p, uint32_t n) const
double calculatePdOdd (double ber, unsigned int d) const
double calculatePdEven (double ber, unsigned int d) const
double calculatePd (double ber, unsigned int d) const
double getFecBpskBer (double snr, double nbits, Hz signalSpread, bps phyRate, uint32_t dFree, uint32_t adFree) const
double getFecQamBer (double snr, uint32_t nbits, Hz signalSpread, bps phyRate, uint32_t m, uint32_t dfree, uint32_t adFree, uint32_t adFreePlusOne) const
virtual double getOFDMAndERPOFDMChunkSuccessRate (const ApskModulationBase *subcarrierModulation, const ConvolutionalCode *convolutionalCode, unsigned int bitLength, bps gorssBitrate, Hz bandwidth, double snr) const
virtual double getDSSSAndHrDSSSChunkSuccessRate (bps bitrate, unsigned int bitLength, double snr) const
virtual double getHeaderSuccessRate (const IIeee80211Mode *mode, unsigned int bitLength, double snr) const override
virtual double getDataSuccessRate (const IIeee80211Mode *mode, unsigned int bitLength, double snr) const override
Protected Member Functions inherited from inet::physicallayer::Ieee80211ErrorModelBase
virtual Packet * computeCorruptedPacket (const Packet *packet, double ber) const override
virtual double getDsssDbpskSuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskSuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskCck5_5SuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskCck11SuccessRate (unsigned int bitLength, double snir) const
Protected Member Functions inherited from inet::physicallayer::ErrorModelBase
virtual void initialize (int stage) override
virtual double getScalarSnir (const ISnir *snir) const
virtual bool hasProbabilisticError (b length, double ber) const
virtual Packet * corruptBits (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptBytes (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptChunks (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptPacket (const Packet *packet, bool &isCorrupted) const
virtual Packet * computeCorruptedPacket (const ISnir *snir) const override
Additional Inherited Members
Public Types inherited from inet::physicallayer::ErrorModelBase
enum CorruptionMode {
CorruptionMode::CM_UNDEFINED = -1, CorruptionMode::CM_PACKET, CorruptionMode::CM_CHUNK, CorruptionMode::CM_BYTE,
CorruptionMode::CM_BIT
}
enum SnirMode { SnirMode::SM_UNDEFINED = -1, SnirMode::SM_MIN, SnirMode::SM_MEAN }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Attributes inherited from inet::physicallayer::Ieee80211ErrorModelBase
double spectralEfficiency1bit = 2000000.0 / 1000000.0
double spectralEfficiency2bit = 2000000.0 / 1000000.0 / 2.0
double sirPerfect = 10.0
double sirImpossible = 0.1
Protected Attributes inherited from inet::physicallayer::ErrorModelBase
CorruptionMode corruptionMode = CorruptionMode::CM_UNDEFINED
SnirMode snirMode = SnirMode::SM_UNDEFINED
double snirOffset = NaN
Detailed Description
Model the error rate for different modulations.
A packet of interest (e.g., a packet can potentially be received by the MAC) is divided into chunks. Each chunk is related to an start/end receiving event. For each chunk, it calculates the ratio (SINR) between received power of packet of interest and summation of noise and interfering power of all the other incoming packets. Then, it will calculate the success rate of the chunk based on BER of the modulation. The success reception rate of the packet is derived from the success rate of all chunks.
The 802.11b modulations:
1 Mbps mode is based on DBPSK. BER is from equation 5.2-69 from John G. Proakis Digitial Communications, 2001 edition
2 Mbps model is based on DQPSK. Equation 8 from "Tight bounds and accurate approximations for dqpsk transmission bit error rate", G. Ferrari and G.E. Corazza ELECTRONICS LETTERS, 40(20):1284-1285, September 2004
5.5 Mbps and 11 Mbps are based on equations (18) and (17) from "Properties and performance of the ieee 802.11b complementarycode-key signal sets", Michael B. Pursley and Thomas C. Royster. IEEE TRANSACTIONS ON COMMUNICATIONS, 57(2):440-449, February 2009.
More detailed description and validation can be found in http://www.nsnam.org/~pei/80211b.pdf
Member Function Documentation
binomialCoefficient()
double inet::physicallayer::Ieee80211YansErrorModel::binomialCoefficient (uint32_t k, double p, uint32_t n) const protected
 {
     double retval = factorial(n) / (factorial(k) * factorial(n - k)) * pow(p, (int)k) * pow(1 - p, (int)(n - k));
     return retval;
 }
Referenced by calculatePdEven(), and calculatePdOdd().
calculatePd()
double inet::physicallayer::Ieee80211YansErrorModel::calculatePd (double ber, unsigned int d) const protected
 {
     double pd;
     if ((d % 2) == 0) {
         pd = calculatePdEven(ber, d);
     }
     else {
         pd = calculatePdOdd(ber, d);
     }
     return pd;
 }
Referenced by getFecBpskBer(), and getFecQamBer().
calculatePdEven()
double inet::physicallayer::Ieee80211YansErrorModel::calculatePdEven (double ber, unsigned int d) const protected
 {
     ASSERT((d % 2) == 0);
     unsigned int dstart = d / 2 + 1;
     unsigned int dend = d;
     double pd = 0;
     for (unsigned int i = dstart; i < dend; i++) {
         pd += binomialCoefficient(i, ber, d);
     }
     pd += 0.5 * binomialCoefficient(d / 2, ber, d);
     return pd;
 }
Referenced by calculatePd().
calculatePdOdd()
double inet::physicallayer::Ieee80211YansErrorModel::calculatePdOdd (double ber, unsigned int d) const protected
 {
     ASSERT((d % 2) == 1);
     unsigned int dstart = (d + 1) / 2;
     unsigned int dend = d;
     double pd = 0;
     for (unsigned int i = dstart; i < dend; i++) {
         pd += binomialCoefficient(i, ber, d);
     }
     return pd;
 }
Referenced by calculatePd().
factorial()
uint32_t inet::physicallayer::Ieee80211YansErrorModel::factorial (uint32_t k) const protected
 {
     uint32_t fact = 1;
     while (k > 0) {
         fact *= k;
         k--;
     }
     return fact;
 }
Referenced by binomialCoefficient().
getBpskBer()
double inet::physicallayer::Ieee80211YansErrorModel::getBpskBer (double snr, Hz signalSpread, bps phyRate) const protected
 {
     double EbNo = snr * signalSpread.get() / phyRate.get();
     double z = sqrt(EbNo);
     double ber = 0.5 * erfc(z);
     EV << "bpsk snr=" << snr << " ber=" << ber << endl;
     return ber;
 }
Referenced by getFecBpskBer().
getDataSuccessRate()
double inet::physicallayer::Ieee80211YansErrorModel::getDataSuccessRate (const IIeee80211Mode * mode, unsigned int bitLength, double snr) const override protected virtual
Implements inet::physicallayer::Ieee80211ErrorModelBase.
 {
     double successRate = 0;
     if (auto ofdmMode = dynamic_cast<const Ieee80211OfdmMode *>(mode))
         successRate = getOFDMAndERPOFDMChunkSuccessRate(ofdmMode->getDataMode()->getModulation()->getSubcarrierModulation(),
                                                         ofdmMode->getDataMode()->getCode()->getConvolutionalCode(),
                                                         bitLength + b(ofdmMode->getHeaderMode()->getServiceFieldLength()).get(),
                                                         ofdmMode->getDataMode()->getGrossBitrate(),
                                                         ofdmMode->getHeaderMode()->getBandwidth(),
                                                         snr);
     else if (auto htMode = dynamic_cast<const Ieee80211HtMode *>(mode))
         successRate = getOFDMAndERPOFDMChunkSuccessRate(htMode->getDataMode()->getModulation()->getSubcarrierModulation(),
                                                         htMode->getDataMode()->getCode()->getForwardErrorCorrection(),
                                                         //bitLength + b(htMode->getHeaderMode()->getHTLengthLength()).get(),
                                                         bitLength,
                                                         htMode->getDataMode()->getGrossBitrate(),
                                                         htMode->getDataMode()->getBandwidth(),
                                                         snr);
     else if (auto vhtMode = dynamic_cast<const Ieee80211VhtMode *>(mode))
         successRate = getOFDMAndERPOFDMChunkSuccessRate(vhtMode->getDataMode()->getModulation()->getSubcarrierModulation(),
                                                         vhtMode->getDataMode()->getCode()->getForwardErrorCorrection(),
                                                         //bitLength + b(vhtMode->getHeaderMode()->getHTLengthLength()).get(),
                                                         bitLength,
                                                         vhtMode->getDataMode()->getGrossBitrate(),
                                                         vhtMode->getDataMode()->getBandwidth(),
                                                         snr);
     else if (auto dsssMode = dynamic_cast<const Ieee80211DsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(dsssMode->getDataMode()->getNetBitrate(), bitLength, snr);
     else if (auto hrDsssMode = dynamic_cast<const Ieee80211HrDsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(hrDsssMode->getDataMode()->getNetBitrate(), bitLength, snr);
     else
         throw cRuntimeError("Unsupported 802.11 mode");
     EV_DEBUG << "SNIR = " << snr << ", data bit length = " << bitLength << ", data error rate = " << 1 - successRate << endl;
     if (successRate >= 1)
         successRate = 1;
     return successRate;
 }
getDSSSAndHrDSSSChunkSuccessRate()
double inet::physicallayer::Ieee80211YansErrorModel::getDSSSAndHrDSSSChunkSuccessRate (bps bitrate, unsigned int bitLength, double snr) const protected virtual
 {
     switch ((int)bitrate.get()) {
         case 1000000:
             return getDsssDbpskSuccessRate(bitLength, snr);
         case 2000000:
             return getDsssDqpskSuccessRate(bitLength, snr);
         case 5500000:
             return getDsssDqpskCck5_5SuccessRate(bitLength, snr);
         case 11000000:
             return getDsssDqpskCck11SuccessRate(bitLength, snr);
     }
     throw cRuntimeError("Unsupported bitrate");
 }
Referenced by getDataSuccessRate(), and getHeaderSuccessRate().
getFecBpskBer()
double inet::physicallayer::Ieee80211YansErrorModel::getFecBpskBer (double snr, double nbits, Hz signalSpread, bps phyRate, uint32_t dFree, uint32_t adFree) const protected
 {
     double ber = getBpskBer(snr, signalSpread, phyRate);
     if (ber == 0.0) {
         return 1.0;
     }
     double pd = calculatePd(ber, dFree);
     double pmu = adFree * pd;
     pmu = math::minnan(pmu, 1.0);
     double pms = pow(1 - pmu, nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getFecQamBer()
double inet::physicallayer::Ieee80211YansErrorModel::getFecQamBer (double snr, uint32_t nbits, Hz signalSpread, bps phyRate, uint32_t m, uint32_t dfree, uint32_t adFree, uint32_t adFreePlusOne) const protected
 {
     double ber = getQamBer(snr, m, signalSpread, phyRate);
     if (ber == 0.0) {
         return 1.0;
     }
     /* first term */
     double pd = calculatePd(ber, dFree);
     double pmu = adFree * pd;
     /* second term */
     pd = calculatePd(ber, dFree + 1);
     pmu += adFreePlusOne * pd;
     pmu = math::minnan(pmu, 1.0);
     double pms = pow(1 - pmu, (int)nbits);
     return pms;
 }
Referenced by getOFDMAndERPOFDMChunkSuccessRate().
getHeaderSuccessRate()
double inet::physicallayer::Ieee80211YansErrorModel::getHeaderSuccessRate (const IIeee80211Mode * mode, unsigned int bitLength, double snr) const override protected virtual
Implements inet::physicallayer::Ieee80211ErrorModelBase.
 {
     double successRate = 0;
     if (auto ofdmMode = dynamic_cast<const Ieee80211OfdmMode *>(mode)) {
         int chunkLength = bitLength - b(ofdmMode->getHeaderMode()->getServiceFieldLength()).get();
         ASSERT(chunkLength == 24);
         successRate = getOFDMAndERPOFDMChunkSuccessRate(ofdmMode->getHeaderMode()->getModulation()->getSubcarrierModulation(),
                                                         ofdmMode->getHeaderMode()->getCode()->getConvolutionalCode(),
                                                         chunkLength,
                                                         ofdmMode->getHeaderMode()->getGrossBitrate(),
                                                         ofdmMode->getHeaderMode()->getBandwidth(),
                                                         snr);
     }
     else if (auto htMode = dynamic_cast<const Ieee80211HtMode *>(mode)) {
 //        int chunkLength = bitLength - b(htMode->getHeaderMode()->getHTLengthLength()).get();
 //        ASSERT(chunkLength == 24);
         int chunkLength = bitLength;
         successRate = getOFDMAndERPOFDMChunkSuccessRate(htMode->getHeaderMode()->getModulation()->getSubcarrierModulation(),
                                                         htMode->getHeaderMode()->getCode()->getForwardErrorCorrection(),
                                                         chunkLength,
                                                         htMode->getHeaderMode()->getGrossBitrate(),
                                                         htMode->getHeaderMode()->getBandwidth(),
                                                         snr);
     }
     else if (auto vhtMode = dynamic_cast<const Ieee80211VhtMode *>(mode)) {
 //        int chunkLength = bitLength - b(vhtMode->getHeaderMode()->getHTLengthLength()).get();
 //        ASSERT(chunkLength == 24);
         int chunkLength = bitLength;
         successRate = getOFDMAndERPOFDMChunkSuccessRate(vhtMode->getHeaderMode()->getModulation()->getSubcarrierModulation(),
                                                         vhtMode->getHeaderMode()->getCode()->getForwardErrorCorrection(),
                                                         chunkLength,
                                                         vhtMode->getHeaderMode()->getGrossBitrate(),
                                                         vhtMode->getHeaderMode()->getBandwidth(),
                                                         snr);
     }
     else if (auto dsssMode = dynamic_cast<const Ieee80211DsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(dsssMode->getHeaderMode()->getNetBitrate(), bitLength, snr);
     else if (auto hrDsssMode = dynamic_cast<const Ieee80211HrDsssMode *>(mode))
         successRate = getDSSSAndHrDSSSChunkSuccessRate(hrDsssMode->getHeaderMode()->getNetBitrate(), bitLength, snr);
     else
         throw cRuntimeError("Unsupported 802.11 mode");
     EV_DEBUG << "SNIR = " << snr << ", header bit length = " << bitLength << ", header error rate = " << 1 - successRate << endl;
     if (successRate >= 1)
         successRate = 1;
     return successRate;
 }
getOFDMAndERPOFDMChunkSuccessRate()
double inet::physicallayer::Ieee80211YansErrorModel::getOFDMAndERPOFDMChunkSuccessRate (const ApskModulationBase * subcarrierModulation, const ConvolutionalCode * convolutionalCode, unsigned int bitLength, bps gorssBitrate, Hz bandwidth, double snr) const protected virtual
 {
     if (subcarrierModulation == &BpskModulation::singleton || subcarrierModulation == &QbpskModulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 1 && convolutionalCode->getCodeRatePuncturingN() == 2)
             return getFecBpskBer(snr, bitLength, bandwidth, grossBitrate, 10, 11);
         else
             return getFecBpskBer(snr, bitLength, bandwidth, grossBitrate, 5, 8);
     }
     else if (subcarrierModulation == &QpskModulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 1 && convolutionalCode->getCodeRatePuncturingN() == 2)
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 4, 10, 11, 0);
         else
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 4, 5, 8, 31);
     }
     else if (subcarrierModulation == &Qam16Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 1 && convolutionalCode->getCodeRatePuncturingN() == 2)
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 16, 10, 11, 0);
         else
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 16, 5, 8, 31);
     }
     else if (subcarrierModulation == &Qam64Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 2 && convolutionalCode->getCodeRatePuncturingN() == 3)
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 64, 6, 1, 16);
         else if (convolutionalCode->getCodeRatePuncturingK() == 5 && convolutionalCode->getCodeRatePuncturingN() == 6)
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 64, 4, 14, 69);
         else
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 64, 5, 8, 31);
     }
     else if (subcarrierModulation == &Qam256Modulation::singleton) {
         if (convolutionalCode->getCodeRatePuncturingK() == 5 && convolutionalCode->getCodeRatePuncturingN() == 6)
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 256, 4, 14, 69);
         else
             return getFecQamBer(snr, bitLength, bandwidth, grossBitrate, 256, 5, 8, 31);
     }
     else
         throw cRuntimeError("Unknown modulation");
 }
Referenced by getDataSuccessRate(), and getHeaderSuccessRate().
getQamBer()
double inet::physicallayer::Ieee80211YansErrorModel::getQamBer (double snr, unsigned int m, Hz signalSpread, bps phyRate) const protected
 {
     double EbNo = snr * signalSpread.get() / phyRate.get();
     double z = sqrt((1.5 * log2(m) * EbNo) / (m - 1.0));
     double z1 = ((1.0 - 1.0 / sqrt((double)m)) * erfc(z));
     double z2 = 1 - pow((1 - z1), 2.0);
     double ber = z2 / log2(m);
     EV << "Qam m=" << m << " rate=" << phyRate << " snr=" << snr << " ber=" << ber << endl;
     return ber;
 }
Referenced by getFecQamBer().
printToStream()
virtual std::ostream& inet::physicallayer::Ieee80211YansErrorModel::printToStream (std::ostream & stream, int level, int evFlags = 0) const inline override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 { return stream << "Ieee80211YansErrorModel"; }
The documentation for this class was generated from the following files:
Ieee80211YansErrorModel.h
Ieee80211YansErrorModel.cc