INET Framework for OMNeT++/OMNEST: inet::queueing::CompoundPacketQueueBase Class Reference
inet::queueing::CompoundPacketQueueBase Class Reference
#include <CompoundPacketQueueBase.h>
Public Member Functions
virtual int getMaxNumPackets () const override
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const override
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const override
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const override
Returns the total length of all packets in the collection in the range [0, inf).
virtual bool isEmpty () const override
Returns true if there are no packets available in the collection.
virtual Packet * getPacket (int index) const override
Returns the packet at the given index.
virtual void removePacket (Packet *packet) override
Removes a packet from the collection.
virtual void removeAllPackets () override
Removes all packets from the collection.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPullSomePacket (cGate *gate) const override
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const override
Returns the packet that can be pulled at the given gate.
virtual Packet * pullPacket (cGate *gate) override
Pulls the packet from the packet source at the given gate.
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::queueing::PacketQueueBase
virtual void enqueuePacket (Packet *packet) override
Enqueues the packet into the packet queue.
virtual Packet * dequeuePacket () override
Dequeues the packet from the packet queue.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
virtual Packet * pullPacketStart (cGate *gate, bps datarate) override
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate) override
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength) override
Progresses pulling the packet from the packet source at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual IPacketDropperFunction * createDropperFunction (const char *dropperClass) const
virtual bool isOverloaded () const
Protected Member Functions inherited from inet::queueing::PacketQueueBase
virtual void handleMessage (cMessage *message) override
virtual void emit (simsignal_t signal, cObject *object, cObject *details=nullptr) override
virtual const char * resolveDirective (char directive) const override
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
int packetCapacity = -1
b dataCapacity = b(-1)
IPassivePacketSink * consumer = nullptr
IPassivePacketSource * provider = nullptr
IPacketCollection * collection = nullptr
IPacketDropperFunction * packetDropperFunction = nullptr
Protected Attributes inherited from inet::queueing::PacketQueueBase
int numPushedPackets = -1
int numPulledPackets = -1
int numRemovedPackets = -1
int numDroppedPackets = -1
int numCreatedPackets = -1
cGate * inputGate = nullptr
cGate * outputGate = nullptr
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
canPullPacket()
virtual Packet* inet::queueing::CompoundPacketQueueBase::canPullPacket (cGate * gate) const inline override virtual
Returns the packet that can be pulled at the given gate.
The returned value is nullptr if there is no such packet.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSource.
 { return provider->canPullPacket(gate); }
canPullSomePacket()
virtual bool inet::queueing::CompoundPacketQueueBase::canPullSomePacket (cGate * gate) const inline override virtual
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
The gate must be a valid gate of this module and it must support pulling packets.
Reimplemented from inet::queueing::PacketQueueBase.
 { return provider->canPullSomePacket(gate); }
canPushPacket()
bool inet::queueing::CompoundPacketQueueBase::canPushPacket (Packet * packet, cGate * gate) const override virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     if (packetDropperFunction)
         return true;
     if (getMaxNumPackets() != -1 && getNumPackets() >= getMaxNumPackets())
         return false;
     if (getMaxTotalLength() != b(-1) && getMaxTotalLength() - getTotalLength() < packet->getDataLength())
         return false;
     return true;
 }
canPushSomePacket()
bool inet::queueing::CompoundPacketQueueBase::canPushSomePacket (cGate * gate) const override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Reimplemented from inet::queueing::PacketQueueBase.
 {
     if (packetDropperFunction)
         return true;
     if (getMaxNumPackets() != -1 && getNumPackets() >= getMaxNumPackets())
         return false;
     if (getMaxTotalLength() != b(-1) && getTotalLength() >= getMaxTotalLength())
         return false;
     return true;
 }
createDropperFunction()
IPacketDropperFunction * inet::queueing::CompoundPacketQueueBase::createDropperFunction (const char * dropperClass) const protected virtual
 {
     if (strlen(dropperClass) == 0)
         return nullptr;
     else
         return check_and_cast<IPacketDropperFunction *>(createOne(dropperClass));
 }
Referenced by initialize().
getMaxNumPackets()
virtual int inet::queueing::CompoundPacketQueueBase::getMaxNumPackets () const inline override virtual
Returns maximum allowed number of packets in the collection.
The value -1 means no such limit.
Implements inet::queueing::IPacketCollection.
 { return packetCapacity; }
Referenced by canPushPacket(), and canPushSomePacket().
getMaxTotalLength()
virtual b inet::queueing::CompoundPacketQueueBase::getMaxTotalLength () const inline override virtual
Returns maximum allowed total length of all packets in the collection.
The value -1 means no such limit.
Implements inet::queueing::IPacketCollection.
 { return dataCapacity; }
Referenced by canPushPacket(), and canPushSomePacket().
getNumPackets()
virtual int inet::queueing::CompoundPacketQueueBase::getNumPackets () const inline override virtual
Returns the number of available packets in the collection in the range [0, inf).
Implements inet::queueing::IPacketCollection.
 { return collection->getNumPackets(); }
Referenced by canPushPacket(), canPushSomePacket(), and isOverloaded().
getPacket()
virtual Packet* inet::queueing::CompoundPacketQueueBase::getPacket (int index) const inline override virtual
Returns the packet at the given index.
Throws error when the index is out of range.
Implements inet::queueing::IPacketCollection.
 { return collection->getPacket(index); }
getTotalLength()
virtual b inet::queueing::CompoundPacketQueueBase::getTotalLength () const inline override virtual
Returns the total length of all packets in the collection in the range [0, inf).
Implements inet::queueing::IPacketCollection.
 { return collection->getTotalLength(); }
Referenced by canPushPacket(), canPushSomePacket(), and isOverloaded().
initialize()
void inet::queueing::CompoundPacketQueueBase::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketQueueBase.
 {
     PacketQueueBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         packetCapacity = par("packetCapacity");
         dataCapacity = b(par("dataCapacity"));
         consumer = check_and_cast<IPassivePacketSink *>(inputGate->getPathEndGate()->getOwnerModule());
         provider = check_and_cast<IPassivePacketSource *>(outputGate->getPathStartGate()->getOwnerModule());
         collection = check_and_cast<IPacketCollection *>(provider);
         packetDropperFunction = createDropperFunction(par("dropperClass"));
         subscribe(packetDroppedSignal, this);
         subscribe(packetCreatedSignal, this);
         WATCH(numCreatedPackets);
     }
     else if (stage == INITSTAGE_QUEUEING) {
         checkPacketOperationSupport(inputGate);
         checkPacketOperationSupport(outputGate);
     }
     else if (stage == INITSTAGE_LAST)
         updateDisplayString();
 }
isEmpty()
virtual bool inet::queueing::CompoundPacketQueueBase::isEmpty () const inline override virtual
Returns true if there are no packets available in the collection.
Implements inet::queueing::IPacketCollection.
 { return collection->isEmpty(); }
isOverloaded()
bool inet::queueing::CompoundPacketQueueBase::isOverloaded () const protected virtual
 {
     return (packetCapacity != -1 && getNumPackets() > packetCapacity) ||
            (dataCapacity != b(-1) && getTotalLength() > dataCapacity);
 }
Referenced by pushPacket().
pullPacket()
Packet * inet::queueing::CompoundPacketQueueBase::pullPacket (cGate * gate) override virtual
Pulls the packet from the packet source at the given gate.
This operation pulls the packet as a whole. The onwership of the packet is transferred to the sink.
The source must not be empty at the given gate. The returned packet must not be nullptr. The gate must be a valid gate of this module and it must support pulling and passing packets.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacket");
     auto packet = provider->pullPacket(outputGate->getPathStartGate());
     take(packet);
     emit(packetPulledSignal, packet);
     updateDisplayString();
     return packet;
 }
pushPacket()
void inet::queueing::CompoundPacketQueueBase::pushPacket (Packet * packet, cGate * gate) override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacket");
     take(packet);
     cNamedObject packetPushStartedDetails("atomicOperationStarted");
     emit(packetPushStartedSignal, packet, &packetPushStartedDetails);
     EV_INFO << "Pushing packet" << EV_FIELD(packet) << EV_ENDL;
     consumer->pushPacket(packet, inputGate->getPathEndGate());
     if (packetDropperFunction != nullptr) {
         while (isOverloaded()) {
             auto packet = packetDropperFunction->selectPacket(this);
             EV_INFO << "Dropping packet" << EV_FIELD(packet) << EV_ENDL;
             removePacket(packet);
             dropPacket(packet, QUEUE_OVERFLOW);
         }
     }
     ASSERT(!isOverloaded());
     cNamedObject packetPushEndedDetails("atomicOperationEnded");
     emit(packetPushEndedSignal, nullptr, &packetPushEndedDetails);
     updateDisplayString();
 }
receiveSignal()
void inet::queueing::CompoundPacketQueueBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == packetDroppedSignal)
         numDroppedPackets++;
     else if (signal == packetCreatedSignal)
         numCreatedPackets++;
     else
         throw cRuntimeError("Unknown signal");
     updateDisplayString();
 }
removeAllPackets()
void inet::queueing::CompoundPacketQueueBase::removeAllPackets () override virtual
Removes all packets from the collection.
Implements inet::queueing::IPacketCollection.
 {
     Enter_Method("removeAllPacket");
     collection->removeAllPackets();
     updateDisplayString();
 }
removePacket()
void inet::queueing::CompoundPacketQueueBase::removePacket (Packet * packet) override virtual
Removes a packet from the collection.
The collection must contain the packet.
Implements inet::queueing::IPacketCollection.
 {
     Enter_Method("removePacket");
     collection->removePacket(packet);
     emit(packetRemovedSignal, packet);
     updateDisplayString();
 }
Referenced by pushPacket().
supportsPacketPulling()
virtual bool inet::queueing::CompoundPacketQueueBase::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return outputGate == gate; }
supportsPacketPushing()
virtual bool inet::queueing::CompoundPacketQueueBase::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return inputGate == gate; }
Member Data Documentation
collection
IPacketCollection* inet::queueing::CompoundPacketQueueBase::collection = nullptr protected
Referenced by initialize(), removeAllPackets(), and removePacket().
consumer
IPassivePacketSink* inet::queueing::CompoundPacketQueueBase::consumer = nullptr protected
Referenced by initialize(), and pushPacket().
dataCapacity
b inet::queueing::CompoundPacketQueueBase::dataCapacity = b(-1) protected
Referenced by initialize(), and isOverloaded().
packetCapacity
int inet::queueing::CompoundPacketQueueBase::packetCapacity = -1 protected
Referenced by initialize(), and isOverloaded().
packetDropperFunction
IPacketDropperFunction* inet::queueing::CompoundPacketQueueBase::packetDropperFunction = nullptr protected
Referenced by canPushPacket(), canPushSomePacket(), initialize(), and pushPacket().
provider
IPassivePacketSource* inet::queueing::CompoundPacketQueueBase::provider = nullptr protected
Referenced by initialize(), and pullPacket().
The documentation for this class was generated from the following files:
CompoundPacketQueueBase.h
CompoundPacketQueueBase.cc