INET Framework for OMNeT++/OMNEST: inet::physicallayer::IReceptionResult Class Reference
inet::physicallayer::IReceptionResult Class Reference abstract
This interface represents the result of a receiver's reception process.
#include <IReceptionResult.h>
Public Member Functions
virtual const IReception * getReception () const =0
Returns the corresponding reception that also specifies the receiver and the received transmission.
virtual const std::vector< const IReceptionDecision * > * getDecisions () const =0
Returns the reception decisions made by the receiver in the order of received signal parts.
virtual const Packet * getPacket () const =0
Returns the packet corresponding to this reception.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents the result of a receiver's reception process.
This interface is strictly immutable to safely support parallel computation.
Member Function Documentation
getDecisions()
virtual const std::vector<const IReceptionDecision *>* inet::physicallayer::IReceptionResult::getDecisions () const pure virtual
Returns the reception decisions made by the receiver in the order of received signal parts.
This function never returns an empty vector.
Implemented in inet::physicallayer::ReceptionResult.
getPacket()
virtual const Packet* inet::physicallayer::IReceptionResult::getPacket () const pure virtual
Returns the packet corresponding to this reception.
This function never returns nullptr.
Implemented in inet::physicallayer::LayeredReceptionResult, and inet::physicallayer::ReceptionResult.
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), and inet::physicallayer::RadioMedium::receivePacket().
getReception()
virtual const IReception* inet::physicallayer::IReceptionResult::getReception () const pure virtual
Returns the corresponding reception that also specifies the receiver and the received transmission.
This function never returns nullptr.
Implemented in inet::physicallayer::ReceptionResult.
Referenced by inet::physicallayer::RadioMedium::getReceptionResult().
The documentation for this class was generated from the following file:
IReceptionResult.h