INET Framework for OMNeT++/OMNEST: inet::L3AddressResolver Class Reference
inet::L3AddressResolver Class Reference
Utility class for finding Ipv4 or Ipv6 address of a host or router.
#include <L3AddressResolver.h>
Public Types
enum {
ADDR_IPv4 = 1, ADDR_IPv6 = 2, ADDR_MAC = 4, ADDR_MODULEPATH = 8,
ADDR_MODULEID = 16, ADDR_MASK = 32
}
Public Member Functions
L3AddressResolver ()
virtual ~L3AddressResolver ()
virtual L3Address resolve (const char *str, int addrType=DEFAULT_ADDR_TYPE)
Accepts dotted decimal notation ("127.0.0.1"), module name of the host or router ("host[2]"), and empty string ("").
virtual std::vector< L3Address > resolve (std::vector< std::string > strs, int addrType=DEFAULT_ADDR_TYPE)
Utility function: Calls resolve() for each item in the string vector, and returns the result in an address vector.
virtual bool tryResolve (const char *str, L3Address &result, int addrType=DEFAULT_ADDR_TYPE)
Similar to resolve(), but returns false (instead of throwing an error) if the address cannot be resolved because the given host (or interface) doesn't have an address assigned yet.
Utility functions supporting resolve()
bool tryParse (L3Address &result, const char *addr, int addrType=DEFAULT_ADDR_TYPE)
virtual L3Address addressOf (cModule *host, int addrType=DEFAULT_ADDR_TYPE)
Returns Ipv4 or Ipv6 address of the given host or router.
virtual L3Address addressOf (cModule *host, const char *ifname, int addrType=DEFAULT_ADDR_TYPE)
Similar to addressOf(), but only looks at the given interface.
virtual L3Address addressOf (cModule *host, cModule *destmod, int addrType=DEFAULT_ADDR_TYPE)
Returns Ipv4 or Ipv6 address of the given host or router.
virtual L3Address routerIdOf (cModule *host)
Returns the router Id of the given router.
virtual L3Address getAddressFrom (IInterfaceTable *ift, int addrType=DEFAULT_ADDR_TYPE)
Returns the Ipv4 or Ipv6 address of the given host or router, given its IInterfaceTable module.
virtual L3Address getAddressFrom (NetworkInterface *ie, int addrType=DEFAULT_ADDR_TYPE)
Returns the Ipv4 or Ipv6 address of the given interface (of a host or router).
virtual IInterfaceTable * interfaceTableOf (cModule *host)
The function tries to look up the IInterfaceTable module as submodule "interfaceTable" or "networkLayer.interfaceTable" within the host/router module.
virtual IIpv4RoutingTable * getIpv4RoutingTableOf (cModule *host)
The function tries to look up the IIpv4RoutingTable module as submodule "routingTable" or "networkLayer.routingTable" within the host/router module.
virtual Ipv6RoutingTable * getIpv6RoutingTableOf (cModule *host)
The function tries to look up the Ipv6RoutingTable module as submodule "routingTable6" or "networkLayer.routingTable6" within the host/router module.
virtual IInterfaceTable * findInterfaceTableOf (cModule *host)
Like interfaceTableOf(), but doesn't throw error if not found.
virtual IIpv4RoutingTable * findIpv4RoutingTableOf (cModule *host)
Like routingTableOf(), but doesn't throw error if not found.
virtual Ipv6RoutingTable * findIpv6RoutingTableOf (cModule *host)
Like interfaceTableOf(), but doesn't throw error if not found.
virtual NextHopRoutingTable * findNextHopRoutingTableOf (cModule *host)
Like interfaceTableOf(), but doesn't throw error if not found.
virtual std::vector< cModule * > collectNetworkNodes ()
Collect modules that represent network nodes, as denoted by the @networkNode(true) annotation.
virtual cModule * findHostWithAddress (const L3Address &addr)
Find the Host with the specified address.
virtual NetworkInterface * findInterfaceWithMacAddress (const MacAddress &addr)
Find the interface with the specified MAC address.
virtual cModule * findHostWithMacAddress (const MacAddress &addr)
Find the host with the specified MAC address.
Protected Member Functions
virtual bool getIpv4AddressFrom (L3Address &retAddr, IInterfaceTable *ift, bool netmask)
virtual bool getIpv6AddressFrom (L3Address &retAddr, IInterfaceTable *ift, bool netmask)
virtual bool getMacAddressFrom (L3Address &retAddr, IInterfaceTable *ift, bool netmask)
virtual bool getModulePathAddressFrom (L3Address &retAddr, IInterfaceTable *ift, bool netmask)
virtual bool getModuleIdAddressFrom (L3Address &retAddr, IInterfaceTable *ift, bool netmask)
virtual bool getInterfaceIpv4Address (L3Address &ret, NetworkInterface *ie, bool mask)
virtual bool getInterfaceIpv6Address (L3Address &ret, NetworkInterface *ie, bool mask)
virtual bool getInterfaceMacAddress (L3Address &ret, NetworkInterface *ie, bool mask)
virtual bool getInterfaceModulePathAddress (L3Address &ret, NetworkInterface *ie, bool mask)
virtual bool getInterfaceModuleIdAddress (L3Address &ret, NetworkInterface *ie, bool mask)
virtual void doCollectNetworkNodes (cModule *parent, std::vector< cModule * > &result)
Detailed Description
Utility class for finding Ipv4 or Ipv6 address of a host or router.
Syntax variations understood:
literal Ipv4 address: "186.54.66.2"
literal Ipv6 address: "3011:7cd6:750b:5fd6:aba3:c231:e9f9:6a43"
module name: "server", "subnet.server[3]"
interface of a host or router: "server%eth0", "subnet.server[3]%eth0"
Ipv4 or Ipv6 address of a host or router: "server(ipv4)", "subnet.server[3](ipv6)"
Ipv4 or Ipv6 address of an interface of a host or router: "server%eth0(ipv4)", "subnet.server[3]%eth0(ipv6)"
routerId: "router1%routerId", "R1%routerId"
interface of a host or router toward defined another node: "client1>router"
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
ADDR_IPv4
ADDR_IPv6
ADDR_MAC
ADDR_MODULEPATH
ADDR_MODULEID
ADDR_MASK
          {
         ADDR_IPv4       = 1,
         ADDR_IPv6       = 2,
         ADDR_MAC        = 4,
         ADDR_MODULEPATH = 8,
         ADDR_MODULEID   = 16,
         ADDR_MASK       = 32
     };
Constructor & Destructor Documentation
L3AddressResolver()
inet::L3AddressResolver::L3AddressResolver () inline
 {}
Referenced by findHostWithAddress(), findInterfaceWithMacAddress(), inet::NextHopNetworkConfigurator::findRoutingTable(), and inet::Ipv4NetworkConfigurator::findRoutingTable().
~L3AddressResolver()
virtual inet::L3AddressResolver::~L3AddressResolver () inline virtual
 {}
Member Function Documentation
addressOf() [1/3]
L3Address inet::L3AddressResolver::addressOf (cModule * host, cModule * destmod, int addrType = DEFAULT_ADDR_TYPE) virtual
Returns Ipv4 or Ipv6 address of the given host or router.
This function find an interface of host connected to destmod then invokes getAddressFrom() to extract the IP address.
 {
     IInterfaceTable *ift = interfaceTableOf(host);
     for (int i = 0; i < ift->getNumInterfaces(); i++) {
         NetworkInterface *ie = ift->getInterface(i);
         if (ie) {
             int gateId = ie->getNodeOutputGateId();
             if (gateId != -1)
                 if (host->gate(gateId)->pathContains(destmod))
                     return getAddressFrom(ie, addrType);
         }
     }
     throw cRuntimeError("L3AddressResolver: no interface connected to `%s' module in interface table of `%s'", destmod->getFullPath().c_str(), host->getFullPath().c_str());
 }
addressOf() [2/3]
L3Address inet::L3AddressResolver::addressOf (cModule * host, const char * ifname, int addrType = DEFAULT_ADDR_TYPE) virtual
Similar to addressOf(), but only looks at the given interface.
 {
     IInterfaceTable *ift = interfaceTableOf(host);
     NetworkInterface *ie = ift->findInterfaceByName(ifname);
     if (ie)
         return getAddressFrom(ie, addrType);
     throw cRuntimeError("L3AddressResolver: no interface called `%s' in interface table of `%s'", ifname, host->getFullPath().c_str());
 }
addressOf() [3/3]
L3Address inet::L3AddressResolver::addressOf (cModule * host, int addrType = DEFAULT_ADDR_TYPE) virtual
Returns Ipv4 or Ipv6 address of the given host or router.
This function uses routingTableOf() to find the IIpv4RoutingTable module, then invokes getAddressFrom() to extract the IP address.
 {
     IInterfaceTable *ift = interfaceTableOf(host);
     return getAddressFrom(ift, addrType);
 }
Referenced by tryResolve().
collectNetworkNodes()
std::vector< cModule * > inet::L3AddressResolver::collectNetworkNodes () virtual
Collect modules that represent network nodes, as denoted by the @networkNode(true) annotation.
 {
     std::vector<cModule *> result;
     doCollectNetworkNodes(getSimulation()->getSystemModule(), result);
     return result;
 }
Referenced by findHostWithAddress(), and findInterfaceWithMacAddress().
doCollectNetworkNodes()
void inet::L3AddressResolver::doCollectNetworkNodes (cModule * parent, std::vector< cModule * > & result) protected virtual
 {
     for (cModule::SubmoduleIterator it(parent); !it.end(); ++it) {
         cModule *submodule = *it;
         if (submodule->getProperties()->getAsBool("networkNode"))
             result.push_back(submodule);
         else
             doCollectNetworkNodes(submodule, result);
     }
 }
Referenced by collectNetworkNodes().
findHostWithAddress()
cModule * inet::L3AddressResolver::findHostWithAddress (const L3Address & addr) virtual
Find the Host with the specified address.
 {
     if (add.isUnspecified() || add.isMulticast())
         return nullptr;
     auto networkNodes = collectNetworkNodes();
     for (cModule *mod : networkNodes) {
         IInterfaceTable *itable = L3AddressResolver().findInterfaceTableOf(mod);
         if (itable != nullptr) {
             if(itable->isLocalAddress(add))
                 return mod;
         }
     }
     return nullptr;
 }
Referenced by inet::visualizer::RoutingTableVisualizerBase::addRouteVisualizations(), inet::ieee80211::Ieee80211MgmtStaSimplified::initialize(), and inet::visualizer::TransportConnectionVisualizerBase::receiveSignal().
findHostWithMacAddress()
cModule * inet::L3AddressResolver::findHostWithMacAddress (const MacAddress & addr) virtual
Find the host with the specified MAC address.
Returns nullptr if not found.
 {
     NetworkInterface *entry = findInterfaceWithMacAddress(addr);
     return entry ? entry->getInterfaceTable()->getHostModule() : nullptr;
 }
findInterfaceTableOf()
IInterfaceTable * inet::L3AddressResolver::findInterfaceTableOf (cModule * host) virtual
Like interfaceTableOf(), but doesn't throw error if not found.
 {
     return dynamic_cast<IInterfaceTable *>(host->getSubmodule("interfaceTable"));
 }
Referenced by inet::visualizer::InterfaceTableVisualizerBase::addAllInterfaceVisualizations(), inet::Ipv4FlatNetworkConfigurator::extractTopology(), inet::NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::findInterfaceTable(), inet::visualizer::LinkBreakVisualizerBase::findNode(), inet::visualizer::RoutingTableVisualizerBase::getDestinations(), inet::visualizer::InterfaceTableCanvasVisualizer::getNetworkInterface(), inet::ieee80211::Ieee80211MgmtStaSimplified::initialize(), inet::InterfaceOperationBase::initialize(), inet::Ipv6FlatNetworkConfigurator::isIPNode(), inet::visualizer::Ieee80211CanvasVisualizer::refreshDisplay(), and inet::ModulePathAddress::tryParse().
findInterfaceWithMacAddress()
NetworkInterface * inet::L3AddressResolver::findInterfaceWithMacAddress (const MacAddress & addr) virtual
Find the interface with the specified MAC address.
Returns nullptr if not found.
 {
     if (addr.isUnspecified() || addr.isBroadcast() || addr.isMulticast())
         return nullptr;
     auto networkNodes = collectNetworkNodes();
     for (cModule *mod : networkNodes) {
         IInterfaceTable *itable = L3AddressResolver().findInterfaceTableOf(mod);
         if (itable != nullptr) {
             for (int i = 0; i < itable->getNumInterfaces(); i++) {
                 NetworkInterface *entry = itable->getInterface(i);
                 if (entry->getMacAddress() == addr)
                     return entry;
             }
         }
     }
     return nullptr;
 }
Referenced by findHostWithMacAddress().
findIpv4RoutingTableOf()
IIpv4RoutingTable * inet::L3AddressResolver::findIpv4RoutingTableOf (cModule * host) virtual
Like routingTableOf(), but doesn't throw error if not found.
 {
 #ifdef INET_WITH_IPv4
     return dynamic_cast<IIpv4RoutingTable *>(host->findModuleByPath(".ipv4.routingTable"));
 #else // ifdef INET_WITH_IPv4
     return nullptr;
 #endif // ifdef INET_WITH_IPv4
 }
Referenced by inet::Ipv4FlatNetworkConfigurator::extractTopology(), inet::NetworkConfiguratorBase::extractTopology(), getIpv4RoutingTableOf(), inet::Ted::initializeTED(), and inet::visualizer::RoutingTableVisualizerBase::updateAllRouteVisualizations().
findIpv6RoutingTableOf()
Ipv6RoutingTable * inet::L3AddressResolver::findIpv6RoutingTableOf (cModule * host) virtual
Like interfaceTableOf(), but doesn't throw error if not found.
 {
 #ifdef INET_WITH_IPv6
     return dynamic_cast<Ipv6RoutingTable *>(host->findModuleByPath(".ipv6.routingTable"));
 #else // ifdef INET_WITH_IPv6
     return nullptr;
 #endif // ifdef INET_WITH_IPv6
 }
Referenced by inet::Ipv6FlatNetworkConfigurator::addOwnAdvPrefixRoutes(), inet::Ipv6FlatNetworkConfigurator::addStaticRoutes(), inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes(), getIpv6RoutingTableOf(), and inet::Ipv6FlatNetworkConfigurator::isIPNode().
findNextHopRoutingTableOf()
NextHopRoutingTable * inet::L3AddressResolver::findNextHopRoutingTableOf (cModule * host) virtual
Like interfaceTableOf(), but doesn't throw error if not found.
 {
 #ifdef INET_WITH_NEXTHOP
     return dynamic_cast<NextHopRoutingTable *>(host->findModuleByPath(".generic.routingTable"));
 #else // ifdef INET_WITH_NEXTHOP
     return nullptr;
 #endif // ifdef INET_WITH_NEXTHOP
 }
getAddressFrom() [1/2]
L3Address inet::L3AddressResolver::getAddressFrom (IInterfaceTable * ift, int addrType = DEFAULT_ADDR_TYPE) virtual
Returns the Ipv4 or Ipv6 address of the given host or router, given its IInterfaceTable module.
For Ipv4, the first usable interface address is chosen.
 {
     L3Address ret;
     bool netmask = addrType & ADDR_MASK;
     if ((addrType & ADDR_IPv4) && getIpv4AddressFrom(ret, ift, netmask))
         return ret;
     else if ((addrType & ADDR_IPv6) && getIpv6AddressFrom(ret, ift, netmask))
         return ret;
     else if ((addrType & ADDR_MAC) && getMacAddressFrom(ret, ift, netmask))
         return ret;
     else if ((addrType & ADDR_MODULEPATH) && getModulePathAddressFrom(ret, ift, netmask))
         return ret;
     else if ((addrType & ADDR_MODULEID) && getModuleIdAddressFrom(ret, ift, netmask))
         return ret;
     return ret;
 }
Referenced by addressOf().
getAddressFrom() [2/2]
L3Address inet::L3AddressResolver::getAddressFrom (NetworkInterface * ie, int addrType = DEFAULT_ADDR_TYPE) virtual
Returns the Ipv4 or Ipv6 address of the given interface (of a host or router).
 {
     L3Address ret;
     bool mask = addrType & ADDR_MASK;
     if ((addrType & ADDR_IPv4) && getInterfaceIpv4Address(ret, ie, mask))
         return ret;
     else if ((addrType & ADDR_IPv6) && getInterfaceIpv6Address(ret, ie, mask))
         return ret;
     else if ((addrType & ADDR_MAC) && getInterfaceMacAddress(ret, ie, mask))
         return ret;
     else if ((addrType & ADDR_MODULEPATH) && getInterfaceModulePathAddress(ret, ie, mask))
         return ret;
     else if ((addrType & ADDR_MODULEID) && getInterfaceModuleIdAddress(ret, ie, mask))
         return ret;
     return ret;
 }
getInterfaceIpv4Address()
bool inet::L3AddressResolver::getInterfaceIpv4Address (L3Address & ret, NetworkInterface * ie, bool mask) protected virtual
Reimplemented in inet::Ipv4NetworkConfigurator.
 {
 #ifdef INET_WITH_IPv4
     Ipv4Address addr = ie->getIpv4Address();
     if (!addr.isUnspecified()) {
         ret.set(netmask ? ie->getIpv4Netmask() : addr);
         return true;
     }
     else {
         // find address in the configurator's notebook
         // TODO how do we know where is the configurator? get the path from a NED parameter?
         Ipv4NetworkConfigurator *configurator = dynamic_cast<Ipv4NetworkConfigurator *>(getSimulation()->findModuleByPath("configurator"));
         if (configurator)
             return static_cast<L3AddressResolver *>(configurator)->getInterfaceIpv4Address(ret, ie, netmask);
     }
 #endif // ifdef INET_WITH_IPv4
     return false;
 }
Referenced by getAddressFrom(), getInterfaceModuleIdAddress(), getInterfaceModulePathAddress(), and getIpv4AddressFrom().
getInterfaceIpv6Address()
bool inet::L3AddressResolver::getInterfaceIpv6Address (L3Address & ret, NetworkInterface * ie, bool mask) protected virtual
 {
 #ifdef INET_WITH_IPv6
     if (netmask)
         return false; // Ipv6 netmask not supported yet
     if (auto ipv6Data = ie->findProtocolData<Ipv6InterfaceData>()) {
         Ipv6Address addr = ipv6Data->getPreferredAddress();
         if (!addr.isUnspecified()) {
             ret.set(addr);
             return true;
         }
     }
 #endif // ifdef INET_WITH_IPv6
     return false;
 }
Referenced by getAddressFrom(), and getIpv6AddressFrom().
getInterfaceMacAddress()
bool inet::L3AddressResolver::getInterfaceMacAddress (L3Address & ret, NetworkInterface * ie, bool mask) protected virtual
 {
     if (!ie->getMacAddress().isUnspecified()) {
         ret = ie->getMacAddress();
         return true;
     }
     return false;
 }
Referenced by getAddressFrom(), and getMacAddressFrom().
getInterfaceModuleIdAddress()
bool inet::L3AddressResolver::getInterfaceModuleIdAddress (L3Address & ret, NetworkInterface * ie, bool mask) protected virtual
 {
 #ifdef INET_WITH_NEXTHOP
     if (auto nextHopData = ie->findProtocolData<NextHopInterfaceData>()) {
         L3Address addr = nextHopData->getAddress();
         if (!addr.isUnspecified() && addr.getType() == L3Address::MODULEID) {
             ret = addr;
             return true;
         }
     }
     else {
         // find address in the configurator's notebook
         // TODO how do we know where is the configurator? getNextHopNetworkConfigurator the path from a NED parameter?
         NextHopNetworkConfigurator *configurator = dynamic_cast<NextHopNetworkConfigurator *>(getSimulation()->findModuleByPath("configurator"));
         if (configurator)
             return static_cast<L3AddressResolver *>(configurator)->getInterfaceIpv4Address(ret, ie, netmask);
     }
 #endif // ifdef INET_WITH_NEXTHOP
     ret = ie->getModuleIdAddress();
     return true;
 }
Referenced by getAddressFrom(), and getModuleIdAddressFrom().
getInterfaceModulePathAddress()
bool inet::L3AddressResolver::getInterfaceModulePathAddress (L3Address & ret, NetworkInterface * ie, bool mask) protected virtual
 {
 #ifdef INET_WITH_NEXTHOP
     if (auto nextHopData = ie->findProtocolData<NextHopInterfaceData>()) {
         L3Address addr = nextHopData->getAddress();
         if (!addr.isUnspecified() && addr.getType() == L3Address::MODULEPATH) {
             ret = addr;
             return true;
         }
     }
     else {
         // find address in the configurator's notebook
         // TODO how do we know where is the configurator? getNextHopNetworkConfigurator the path from a NED parameter?
         NextHopNetworkConfigurator *configurator = dynamic_cast<NextHopNetworkConfigurator *>(getSimulation()->findModuleByPath("configurator"));
         if (configurator)
             return static_cast<L3AddressResolver *>(configurator)->getInterfaceIpv4Address(ret, ie, netmask);
     }
 #endif // ifdef INET_WITH_NEXTHOP
     ret = ie->getModulePathAddress();
     return true;
 }
Referenced by getAddressFrom(), and getModulePathAddressFrom().
getIpv4AddressFrom()
bool inet::L3AddressResolver::getIpv4AddressFrom (L3Address & retAddr, IInterfaceTable * ift, bool netmask) protected virtual
 {
     if (ift->getNumInterfaces() == 0)
         throw cRuntimeError("L3AddressResolver: interface table `%s' has no interface registered "
                             "(yet? try in a later init stage!)", ift->getFullPath().c_str());
 #ifdef INET_WITH_IPv4
     // choose first usable interface address (configured for Ipv4, non-loopback if, addr non-null)
     for (int i = 0; i < ift->getNumInterfaces(); i++) {
         NetworkInterface *ie = ift->getInterface(i);
         if (ie->isLoopback())
             continue;
         if (getInterfaceIpv4Address(retAddr, ie, netmask))
             return true;
     }
 #endif // ifdef INET_WITH_IPv4
     return false;
 }
Referenced by getAddressFrom().
getIpv4RoutingTableOf()
IIpv4RoutingTable * inet::L3AddressResolver::getIpv4RoutingTableOf (cModule * host) virtual
The function tries to look up the IIpv4RoutingTable module as submodule "routingTable" or "networkLayer.routingTable" within the host/router module.
Throws an error if not found.
 {
     IIpv4RoutingTable *mod = findIpv4RoutingTableOf(host);
     if (!mod)
         throw cRuntimeError("L3AddressResolver: IIpv4RoutingTable not found as submodule "
                             " `routingTable' in host/router `%s'", host->getFullPath().c_str());
     return mod;
 }
Referenced by inet::Ipv4FlatNetworkConfigurator::extractTopology(), routerIdOf(), and inet::HostAutoConfigurator::setupNetworkLayer().
getIpv6AddressFrom()
bool inet::L3AddressResolver::getIpv6AddressFrom (L3Address & retAddr, IInterfaceTable * ift, bool netmask) protected virtual
 {
     // browse interfaces and pick a globally routable address
     if (ift->getNumInterfaces() == 0)
         throw cRuntimeError("L3AddressResolver: interface table `%s' has no interface registered "
                             "(yet? try in a later init stage!)", ift->getFullPath().c_str());
 #ifndef INET_WITH_IPv6
     return false;
 #else // ifndef INET_WITH_IPv6
     if (netmask)
         return false; // Ipv6 netmask not supported yet
     bool ret = false;
     Ipv6Address::Scope retScope = Ipv6Address::UNSPECIFIED;
     for (int i = 0; i < ift->getNumInterfaces() && retScope != Ipv6Address::GLOBAL; i++) {
         NetworkInterface *ie = ift->getInterface(i);
         L3Address curAddr;
         bool ieHasIpv6Addr = getInterfaceIpv6Address(curAddr, ie, false);
         if (!ieHasIpv6Addr || ie->isLoopback())
             continue;
         Ipv6Address::Scope curScope = curAddr.toIpv6().getScope();
         if (curScope > retScope) {
             retAddr = curAddr;
             retScope = curScope;
             ret = true;
         }
     }
     return ret;
 #endif // ifndef INET_WITH_IPv6
 }
Referenced by getAddressFrom().
getIpv6RoutingTableOf()
Ipv6RoutingTable * inet::L3AddressResolver::getIpv6RoutingTableOf (cModule * host) virtual
The function tries to look up the Ipv6RoutingTable module as submodule "routingTable6" or "networkLayer.routingTable6" within the host/router module.
Throws an error if not found.
 {
     // find Ipv6RoutingTable
     Ipv6RoutingTable *mod = findIpv6RoutingTableOf(host);
     if (!mod)
         throw cRuntimeError("L3AddressResolver: Ipv6RoutingTable not found as submodule "
                             " `routingTable' in host/router `%s'", host->getFullPath().c_str());
     return mod;
 }
Referenced by inet::xMIPv6::initialize().
getMacAddressFrom()
bool inet::L3AddressResolver::getMacAddressFrom (L3Address & retAddr, IInterfaceTable * ift, bool netmask) protected virtual
 {
     if (ift->getNumInterfaces() == 0)
         throw cRuntimeError("L3AddressResolver: interface table `%s' has no interface registered "
                             "(yet? try in a later init stage!)", ift->getFullPath().c_str());
     // choose first usable interface address (configured for generic, non-loopback if, addr non-null)
     for (int i = 0; i < ift->getNumInterfaces(); i++) {
         NetworkInterface *ie = ift->getInterface(i);
         if (ie->isLoopback())
             continue;
         if (getInterfaceMacAddress(retAddr, ie, netmask))
             return true;
     }
     return false;
 }
Referenced by getAddressFrom().
getModuleIdAddressFrom()
bool inet::L3AddressResolver::getModuleIdAddressFrom (L3Address & retAddr, IInterfaceTable * ift, bool netmask) protected virtual
 {
     if (ift->getNumInterfaces() == 0)
         throw cRuntimeError("L3AddressResolver: interface table `%s' has no interface registered "
                             "(yet? try in a later init stage!)", ift->getFullPath().c_str());
     // choose first usable interface address (configured for generic, non-loopback if, addr non-null)
     for (int i = 0; i < ift->getNumInterfaces(); i++) {
         NetworkInterface *ie = ift->getInterface(i);
         if (ie->isLoopback())
             continue;
         if (getInterfaceModuleIdAddress(retAddr, ie, netmask))
             return true;
     }
     return false;
 }
Referenced by getAddressFrom().
getModulePathAddressFrom()
bool inet::L3AddressResolver::getModulePathAddressFrom (L3Address & retAddr, IInterfaceTable * ift, bool netmask) protected virtual
 {
     if (ift->getNumInterfaces() == 0)
         throw cRuntimeError("L3AddressResolver: interface table `%s' has no interface registered "
                             "(yet? try in a later init stage!)", ift->getFullPath().c_str());
     // choose first usable interface address (configured for generic, non-loopback if, addr non-null)
     for (int i = 0; i < ift->getNumInterfaces(); i++) {
         NetworkInterface *ie = ift->getInterface(i);
         if (ie->isLoopback())
             continue;
         if (getInterfaceModulePathAddress(retAddr, ie, netmask))
             return true;
     }
     return false;
 }
Referenced by getAddressFrom().
interfaceTableOf()
IInterfaceTable * inet::L3AddressResolver::interfaceTableOf (cModule * host) virtual
The function tries to look up the IInterfaceTable module as submodule "interfaceTable" or "networkLayer.interfaceTable" within the host/router module.
Throws an error if not found.
 {
     // find IInterfaceTable
     cModule *mod = host->getSubmodule("interfaceTable");
     if (!mod)
         throw cRuntimeError("L3AddressResolver: IInterfaceTable not found as submodule "
                             " `interfaceTable' in host/router `%s'", host->getFullPath().c_str());
     return check_and_cast<IInterfaceTable *>(mod);
 }
Referenced by inet::Ipv6FlatNetworkConfigurator::addOwnAdvPrefixRoutes(), addressOf(), inet::Ipv6FlatNetworkConfigurator::addStaticRoutes(), inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes(), inet::Ipv4FlatNetworkConfigurator::extractTopology(), and inet::Ted::initializeTED().
resolve() [1/2]
L3Address inet::L3AddressResolver::resolve (const char * str, int addrType = DEFAULT_ADDR_TYPE) virtual
Accepts dotted decimal notation ("127.0.0.1"), module name of the host or router ("host[2]"), and empty string ("").
For the latter, it returns the null address. If module name is specified, the module will be looked up using getModuleByPath(), and then addressOf() will be called to determine its IP address.
 {
     L3Address addr;
     if (!tryResolve(s, addr, addrType))
         throw cRuntimeError("L3AddressResolver: Cannot resolve address `%s'", s);
     return addr;
 }
Referenced by inet::MultiFieldClassifier::configureFilters(), inet::NetPerfMeter::createAndBindSocket(), inet::Define_Module(), inet::NetPerfMeter::establishConnection(), inet::xmlutils::getParameterIPAddressValue(), inet::PingApp::handleSelfMessage(), inet::DhcpServer::handleStartOperation(), inet::Forwarding::initialize(), inet::ieee80211::Ieee80211MgmtStaSimplified::initialize(), inet::VoipStreamSender::initialize(), inet::SctpNatServer::initialize(), inet::SctpClient::initialize(), inet::SctpServer::initialize(), inet::SctpPeer::initialize(), inet::dymo::Dymo::initialize(), inet::SctpNatPeer::initialize(), inet::ospfv2::ipv4AddressFromAddressString(), inet::ospfv2::ipv4NetmaskFromAddressString(), inet::PingApp::parseDestAddressesPar(), inet::UdpBasicBurst::processStart(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::RsvpTe::readTrafficRouteFromXML(), inet::UdpVideoStreamClient::requestStream(), resolve(), inet::EtherAppClient::resolveDestMacAddress(), inet::EtherTrafGen::resolveDestMacAddress(), inet::Ipv4NetworkConfigurator::resolveInterfaceAndGateway(), inet::tcp::TcpSpoof::sendSpoofPacket(), inet::SimpleVoipSender::sendVoIPPacket(), inet::UdpSink::setSocketOptions(), inet::SctpNatPeer::socketClosed(), inet::TunnelApp::socketDataArrived(), and inet::SctpNatPeer::socketPeerClosed().
resolve() [2/2]
std::vector< L3Address > inet::L3AddressResolver::resolve (std::vector< std::string > strs, int addrType = DEFAULT_ADDR_TYPE) virtual
Utility function: Calls resolve() for each item in the string vector, and returns the result in an address vector.
The string vector may come e.g. from cStringTokenizer::asVector().
 {
     std::vector<L3Address> result;
     int n = strs.size();
     result.reserve(n);
     for (int i = 0; i < n; i++)
         result.push_back(resolve(strs[i].c_str(), addrType));
     return result;
 }
routerIdOf()
L3Address inet::L3AddressResolver::routerIdOf (cModule * host) virtual
Returns the router Id of the given router.
Router Id is obtained from the getRouterId() method of the IIpv4RoutingTable submodule.
 {
 #ifdef INET_WITH_IPv4
     IIpv4RoutingTable *rt = getIpv4RoutingTableOf(host);
     return L3Address(rt->getRouterId());
 #else // ifdef INET_WITH_IPv4
     throw cRuntimeError("INET was compiled without Ipv4 support");
 #endif // ifdef INET_WITH_IPv4
 }
Referenced by tryResolve().
tryParse()
bool inet::L3AddressResolver::tryParse (L3Address & result, const char * addr, int addrType = DEFAULT_ADDR_TYPE)
 {
     Ipv6Address ipv6;
     MacAddress mac;
     ModuleIdAddress moduleId;
     ModulePathAddress modulePath;
     if (((addrType & ADDR_IPv4) != 0) && Ipv4Address::isWellFormed(addr))
         result.set(Ipv4Address(addr));
     else if (((addrType & ADDR_IPv6) != 0) && ipv6.tryParse(addr))
         result.set(ipv6);
     else if (((addrType & ADDR_MAC) != 0) && mac.tryParse(addr))
         result.set(mac);
     else if (((addrType & ADDR_MODULEID) != 0) && moduleId.tryParse(addr))
         result.set(moduleId);
     else if (((addrType & ADDR_MODULEPATH) != 0) && modulePath.tryParse(addr))
         result.set(modulePath);
     else
         return false;
     return true;
 }
Referenced by tryResolve().
tryResolve()
bool inet::L3AddressResolver::tryResolve (const char * str, L3Address & result, int addrType = DEFAULT_ADDR_TYPE) virtual
Similar to resolve(), but returns false (instead of throwing an error) if the address cannot be resolved because the given host (or interface) doesn't have an address assigned yet.
(It still throws an error on any other error condition).
 {
     // empty address
     result = L3Address();
     if (!s || !*s)
         return true;
     // handle address literal
     if (tryParse(result, s, addrType))
         return true;
     // must be " modulename [ { '%' interfacename | '>' destnode } ] [ '(' protocol ')' ] [ '/' ] " syntax
     // interfacename: existing_interface_of_module | 'routerId'
     // protocol: 'ipv4' | 'ipv6' | 'mac' | 'modulepath' | 'moduleid'
     // '/': returns mask instead address
     std::string modname, ifname, protocol, destnodename;
     bool netmask = addrType & ADDR_MASK;
     const char *p = s;
     const char *endp = strchr(p, '\0');
     const char *nextsep = strpbrk(p, "%>(/");
     if (!nextsep)
         nextsep = endp;
     modname.assign(p, nextsep - p);
     char c = *nextsep;
     if (c == '%') {
         {
             p = nextsep + 1;
             nextsep = strpbrk(p, "(/");
             if (!nextsep)
                 nextsep = endp;
         }
         ifname.assign(p, nextsep - p);
         c = *nextsep;
     }
     else if (c == '>') {
         {
             p = nextsep + 1;
             nextsep = strpbrk(p, "(/");
             if (!nextsep)
                 nextsep = endp;
         }
         destnodename.assign(p, nextsep - p);
         c = *nextsep;
     }
     if (c == '(') {
         {
             p = nextsep + 1;
             nextsep = strpbrk(p, ")");
             if (!nextsep)
                 nextsep = endp;
         }
         protocol.assign(p, nextsep - p);
         c = *nextsep;
         if (c == ')') {
             {
                 p = nextsep + 1;
                 nextsep = p;
             }
             c = *nextsep;
         }
     }
     if (c == '/') {
         netmask = true;
         {
             p = nextsep + 1;
             nextsep = p;
         }
         c = *nextsep;
     }
     if (c)
         throw cRuntimeError("L3AddressResolver: syntax error parsing address spec `%s'", s);
     // find module
     cModule *mod = getSimulation()->findModuleByPath(modname.c_str());
     if (!mod)
         throw cRuntimeError("L3AddressResolver: module `%s' not found", modname.c_str());
     // check protocol
     if (!protocol.empty()) {
         if (protocol == "ipv4")
             addrType = ADDR_IPv4;
         else if (protocol == "ipv6")
             addrType = ADDR_IPv6;
         else if (protocol == "mac")
             addrType = ADDR_MAC;
         else if (protocol == "modulepath")
             addrType = ADDR_MODULEPATH;
         else if (protocol == "moduleid")
             addrType = ADDR_MODULEID;
         else
             throw cRuntimeError("L3AddressResolver: error parsing address spec `%s': address type must be `(ipv4)' or `(ipv6)'", s);
     }
     if (netmask)
         addrType |= ADDR_MASK;
     // find interface for dest node
     // get address from the given module/interface
     if (!destnodename.empty()) {
         cModule *destnode = getSimulation()->findModuleByPath(destnodename.c_str());
         if (!destnode)
             throw cRuntimeError("L3AddressResolver: destination module `%s' not found", destnodename.c_str());
         result = addressOf(mod, destnode, addrType);
     }
     else if (ifname.empty())
         result = addressOf(mod, addrType);
     else if (ifname == "routerId")
         result = routerIdOf(mod); // addrType is meaningless here, routerId is protocol independent
     else
         result = addressOf(mod, ifname.c_str(), addrType);
     return !result.isUnspecified();
 }
Referenced by inet::UdpBasicApp::chooseDestAddr(), inet::StreamDecoder::configureMappings(), inet::TcpAppBase::connect(), inet::SctpClient::connect(), inet::SctpPeer::connect(), inet::IpvxTrafGen::handleMessageWhenUp(), inet::EthernetSocketIo::initialize(), inet::Ieee8022LlcSocketIo::initialize(), inet::TcpClientSocketIo::open(), inet::UdpBasicApp::processStart(), and resolve().
The documentation for this class was generated from the following files:
L3AddressResolver.h
L3AddressResolver.cc