INET Framework for OMNeT++/OMNEST: inet::physicallayer::ISnir Class Reference
inet::physicallayer::ISnir Class Reference abstract
#include <ISnir.h>
Public Member Functions
virtual const IReception * getReception () const =0
virtual const INoise * getNoise () const =0
virtual double getMin () const =0
virtual double getMax () const =0
virtual double getMean () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
getMax()
virtual double inet::physicallayer::ISnir::getMax () const pure virtual
Implemented in inet::physicallayer::DimensionalSnir, inet::physicallayer::ScalarSnir, and inet::physicallayer::UnitDiskSnir.
Referenced by inet::physicallayer::ReceiverBase::computeReceptionResult(), inet::physicallayer::ApskLayeredReceiver::computeReceptionResult(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
getMean()
virtual double inet::physicallayer::ISnir::getMean () const pure virtual
Implemented in inet::physicallayer::DimensionalSnir, inet::physicallayer::ScalarSnir, and inet::physicallayer::UnitDiskSnir.
Referenced by inet::physicallayer::SnirReceiverBase::computeIsReceptionSuccessful(), inet::physicallayer::ReceiverBase::computeReceptionResult(), inet::physicallayer::ApskLayeredReceiver::computeReceptionResult(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult(), and inet::physicallayer::ErrorModelBase::getScalarSnir().
getMin()
virtual double inet::physicallayer::ISnir::getMin () const pure virtual
Implemented in inet::physicallayer::DimensionalSnir, inet::physicallayer::ScalarSnir, and inet::physicallayer::UnitDiskSnir.
Referenced by inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), inet::physicallayer::SnirReceiverBase::computeIsReceptionSuccessful(), inet::physicallayer::ApskLayeredErrorModel::computePacketModel(), inet::physicallayer::ReceiverBase::computeReceptionResult(), inet::physicallayer::ApskLayeredReceiver::computeReceptionResult(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult(), inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel(), and inet::physicallayer::ErrorModelBase::getScalarSnir().
getNoise()
virtual const INoise* inet::physicallayer::ISnir::getNoise () const pure virtual
Implemented in inet::physicallayer::SnirBase.
Referenced by inet::physicallayer::UnitDiskReceiver::computeReceptionResult(), and inet::physicallayer::ReceiverBase::computeSignalPower().
getReception()
virtual const IReception* inet::physicallayer::ISnir::getReception () const pure virtual
Implemented in inet::physicallayer::SnirBase.
Referenced by inet::physicallayer::ApskErrorModel::computeBitErrorRate(), inet::physicallayer::ErrorModelBase::computeCorruptedPacket(), inet::physicallayer::ApskErrorModel::computePacketErrorRate(), inet::physicallayer::Ieee80211BerTableErrorModel::computePacketErrorRate(), inet::physicallayer::StochasticErrorModel::computePacketErrorRate(), inet::physicallayer::Ieee80211ErrorModelBase::computePacketErrorRate(), inet::physicallayer::ReceiverBase::computeReceivedPacket(), inet::physicallayer::ReceiverBase::computeSignalPower(), and inet::physicallayer::ApskErrorModel::computeSymbolErrorRate().
The documentation for this class was generated from the following file:
ISnir.h