INET Framework for OMNeT++/OMNEST: inet::StreamingTransmitterBase Class Reference
inet::StreamingTransmitterBase Class Reference abstract
#include <StreamingTransmitterBase.h>
Public Member Functions
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::PacketTransmitterBase
virtual ~PacketTransmitterBase ()
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::ClockUserModuleMixin< OperationalMixin< PacketProcessorBase > >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
virtual void pushPacket (Packet *packet, cGate *gate)=0
Pushes the packet into the packet sink at the given gate.
Protected Member Functions
virtual void initialize (int stage) override
virtual void scheduleAt (simtime_t t, cMessage *message) override
virtual void abortTx ()=0
virtual void scheduleTxEndTimer (Signal *signal)
Protected Member Functions inherited from inet::PacketTransmitterBase
virtual void finish () override
virtual void handleMessageWhenUp (cMessage *message) override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual Signal * encodePacket (Packet *packet)
virtual void prepareSignal (Signal *signal)
virtual void sendSignalStart (Signal *signal, int transmissionId)
virtual void sendSignalProgress (Signal *signal, int transmissionId, b bitPosition, clocktime_t timePosition)
virtual void sendSignalEnd (Signal *signal, int transmissionId)
virtual clocktime_t calculateClockTimeDuration (const Packet *packet) const
virtual simtime_t calculateDuration (clocktime_t clockTimeDuration) const
virtual bool isTransmitting () const
Protected Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void handleStopOperation (LifecycleOperation *operation)=0
virtual void handleCrashOperation (LifecycleOperation *operation)=0
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
cChannel * transmissionChannel = nullptr
Protected Attributes inherited from inet::PacketTransmitterBase
cPar * dataratePar = nullptr
cGate * inputGate = nullptr
cGate * outputGate = nullptr
ModuleRef< IActivePacketSource > producer
bps txDatarate = bps(NaN)
Signal * txSignal = nullptr
ClockEvent * txEndTimer = nullptr
simtime_t txStartTime = -1
clocktime_t txStartClockTime = -1
clocktime_t txDurationClockTime = -1
Protected Attributes inherited from inet::OperationalMixin< PacketProcessorBase >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< PacketProcessorBase >
enum State
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
abortTx()
virtual void inet::StreamingTransmitterBase::abortTx () protected pure virtual
Implemented in inet::StreamThroughTransmitter, and inet::StreamingTransmitter.
Referenced by receiveSignal().
canPushSomePacket()
bool inet::StreamingTransmitterBase::canPushSomePacket (cGate * gate) const override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Reimplemented from inet::PacketTransmitterBase.
 {
     return transmissionChannel != nullptr && !transmissionChannel->isDisabled() && PacketTransmitterBase::canPushSomePacket(gate);
 }
initialize()
void inet::StreamingTransmitterBase::initialize (int stage) override protected virtual
Reimplemented from inet::PacketTransmitterBase.
Reimplemented in inet::StreamThroughTransmitter.
 {
     PacketTransmitterBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         transmissionChannel = outputGate->findTransmissionChannel();
         if (transmissionChannel != nullptr) {
             transmissionChannel->subscribe(PRE_MODEL_CHANGE, this);
             transmissionChannel->subscribe(POST_MODEL_CHANGE, this);
         }
         subscribe(PRE_MODEL_CHANGE, this);
         subscribe(POST_MODEL_CHANGE, this);
     }
 }
Referenced by inet::StreamThroughTransmitter::initialize().
receiveSignal()
void inet::StreamingTransmitterBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == PRE_MODEL_CHANGE) {
         if (auto notification = dynamic_cast<cPrePathCutNotification *>(object)) {
             if (outputGate == notification->pathStartGate && isTransmitting())
                 abortTx();
         }
         else if (auto notification = dynamic_cast<cPreParameterChangeNotification *>(object)) {
             if (notification->par->getOwner() == transmissionChannel &&
                 notification->par->getType() == cPar::BOOL && strcmp(notification->par->getName(), "disabled") == 0 &&
                 !transmissionChannel->isDisabled() &&
                 isTransmitting()) // TODO the new value of parameter currently unavailable: notification->newValue == true
             {
                 abortTx();
             }
         }
     }
     else if (signal == POST_MODEL_CHANGE) {
         if (auto notification = dynamic_cast<cPostPathCreateNotification *>(object)) {
             if (outputGate == notification->pathStartGate) {
                 transmissionChannel = outputGate->findTransmissionChannel();
                 if (transmissionChannel != nullptr && !transmissionChannel->isSubscribed(POST_MODEL_CHANGE, this))
                     transmissionChannel->subscribe(POST_MODEL_CHANGE, this);
                 if (producer != nullptr)
                     producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
             }
         }
         else if (auto notification = dynamic_cast<cPostPathCutNotification *>(object)) {
             if (outputGate == notification->pathStartGate) {
                 transmissionChannel = nullptr;
                 if (producer != nullptr)
                     producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
             }
         }
         else if (auto notification = dynamic_cast<cPostParameterChangeNotification *>(object)) {
             if (producer != nullptr && notification->par->getOwner() == transmissionChannel && notification->par->getType() == cPar::BOOL && strcmp(notification->par->getName(), "disabled") == 0)
                 producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
         }
     }
 }
scheduleAt()
void inet::StreamingTransmitterBase::scheduleAt (simtime_t t, cMessage * message) override protected virtual
 {
     if (message == txEndTimer) {
         if (txStartTime + txSignal->getDuration() != t) {
             clocktime_t timePosition = getClockTime() - txStartClockTime;
             b bitPosition = b(std::floor(txDatarate.get() * timePosition.dbl()));
             txSignal->setDuration(t - txStartTime);
             sendSignalProgress(txSignal->dup(), txSignal->getId(), bitPosition, timePosition);
         }
     }
     ClockUserModuleMixin::scheduleAt(t, message);
 }
Referenced by inet::StreamThroughTransmitter::scheduleBufferUnderrunTimer().
scheduleTxEndTimer()
void inet::StreamingTransmitterBase::scheduleTxEndTimer (Signal * signal) protected virtual
 {
     ASSERT(txStartClockTime != -1);
     clocktime_t txEndClockTime = txStartClockTime + txDurationClockTime;
     EV_INFO << "Scheduling transmission end timer" << EV_FIELD(at, txEndClockTime.ustr()) << EV_ENDL;
     rescheduleClockEventAt(txEndClockTime, txEndTimer);
 }
Referenced by inet::StreamThroughTransmitter::progressTx(), inet::StreamingTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
Member Data Documentation
transmissionChannel
cChannel* inet::StreamingTransmitterBase::transmissionChannel = nullptr protected
Referenced by canPushSomePacket(), initialize(), and receiveSignal().
The documentation for this class was generated from the following files:
StreamingTransmitterBase.h
StreamingTransmitterBase.cc