INET Framework for OMNeT++/OMNEST: inet::LabelsTag Class Reference
inet::LabelsTag Class Reference
Class generated from inet/queueing/common/LabelsTag.msg:13 by opp_msgtool.
#include <LabelsTag_m.h>
Public Member Functions
LabelsTag ()
LabelsTag (const LabelsTag &other)
virtual ~LabelsTag ()
LabelsTag & operator= (const LabelsTag &other)
virtual LabelsTag * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setLabelsArraySize (size_t size)
virtual size_t getLabelsArraySize () const
virtual const char * getLabels (size_t k) const
virtual void setLabels (size_t k, const char *labels)
virtual void insertLabels (size_t k, const char *labels)
void insertLabels (const char *labels)
virtual void appendLabels (const char *labels)
virtual void eraseLabels (size_t k)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const LabelsTag &)=delete
Protected Attributes
::omnetpp::opp_string * labels = nullptr
size_t labels_arraysize = 0
Private Member Functions
void copy (const LabelsTag &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/queueing/common/LabelsTag.msg:13 by opp_msgtool.
class LabelsTag extends TagBase
{
    string labels[];
}
Constructor & Destructor Documentation
LabelsTag() [1/2]
inet::LabelsTag::LabelsTag ()
LabelsTag() [2/2]
inet::LabelsTag::LabelsTag (const LabelsTag & other)
~LabelsTag()
virtual inet::LabelsTag::~LabelsTag () virtual
Member Function Documentation
appendLabels()
virtual void inet::LabelsTag::appendLabels (const char * labels) virtual
Referenced by inet::queueing::TokenBucketMeterMixin< TokenBucketMixin< PacketMeterBase > >::labelPacket().
copy()
void inet::LabelsTag::copy (const LabelsTag & other) private
dup()
virtual LabelsTag* inet::LabelsTag::dup () const inline override virtual
 {return new LabelsTag(*this);}
eraseLabels()
virtual void inet::LabelsTag::eraseLabels (size_t k) virtual
getLabels()
virtual const char* inet::LabelsTag::getLabels (size_t k) const virtual
Referenced by inet::queueing::LabelClassifier::classifyPacket(), and inet::queueing::LabelFilter::matchesPacket().
getLabelsArraySize()
virtual size_t inet::LabelsTag::getLabelsArraySize () const virtual
insertLabels() [1/2]
void inet::LabelsTag::insertLabels (const char * labels) inline
 {appendLabels(labels);}
insertLabels() [2/2]
virtual void inet::LabelsTag::insertLabels (size_t k, const char * labels) virtual
operator=()
LabelsTag& inet::LabelsTag::operator= (const LabelsTag & other)
operator==()
bool inet::LabelsTag::operator== (const LabelsTag &) protected delete
parsimPack()
virtual void inet::LabelsTag::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::LabelsTag::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setLabels()
virtual void inet::LabelsTag::setLabels (size_t k, const char * labels) virtual
setLabelsArraySize()
virtual void inet::LabelsTag::setLabelsArraySize (size_t size) virtual
Member Data Documentation
labels
::omnetpp::opp_string* inet::LabelsTag::labels = nullptr protected
labels_arraysize
size_t inet::LabelsTag::labels_arraysize = 0 protected
The documentation for this class was generated from the following file:
LabelsTag_m.h