INET Framework for OMNeT++/OMNEST: inet::rtp::SdesChunk Class Reference
inet::rtp::SdesChunk Class Reference
The class SdesChunk is used for storing SdesItem objects for one rtp end system.
#include <Sdes.h>
Public Member Functions
SdesChunk (const char *name=nullptr, uint32_t ssrc=0)
Default constructor.
SdesChunk (const SdesChunk &sdesChunk)
Copy constructor.
virtual ~SdesChunk ()
Destructor.
SdesChunk & operator= (const SdesChunk &sdesChunk)
Operator equal.
virtual SdesChunk * dup () const override
Duplicates this SdesChunk by calling the copy constructor.
virtual std::string str () const override
Writes a short info about this SdesChunk into the given string.
virtual void dump (std::ostream &os) const
Writes a longer info about this SdesChunk into the given stream.
virtual void addSDESItem (SdesItem *item)
Adds an SdesItem to this SdesChunk.
virtual uint32_t getSsrc () const
Returns the ssrc identifier this SdesChunk is for.
virtual void setSsrc (uint32_t ssrc)
Sets the ssrc identifier this SdesChunk is for.
virtual int getLength () const
Returns the length in bytes of this SdesChunk.
Protected Attributes
uint32_t _ssrc
The ssrc identifier this SdesChunk is for.
int _length
The length in bytes of this SdesChunk.
Private Member Functions
void copy (const SdesChunk &other)
Detailed Description
The class SdesChunk is used for storing SdesItem objects for one rtp end system.
Constructor & Destructor Documentation
SdesChunk() [1/2]
inet::rtp::SdesChunk::SdesChunk (const char * name = nullptr, uint32_t ssrc = 0)
Default constructor.
                                                     : cArray(name)
 {
     _ssrc = ssrc;
     _length = 4;
 }
Referenced by dup().
SdesChunk() [2/2]
inet::rtp::SdesChunk::SdesChunk (const SdesChunk & sdesChunk)
Copy constructor.
                                                : cArray(sdesChunk)
 {
     copy(sdesChunk);
 }
~SdesChunk()
inet::rtp::SdesChunk::~SdesChunk () virtual
Destructor.
 {
 }
Member Function Documentation
addSDESItem()
void inet::rtp::SdesChunk::addSDESItem (SdesItem * item) virtual
Adds an SdesItem to this SdesChunk.
If there is already an SdesItem of the same type in this SdesChunk it is replaced by the new one.
 {
     for (int i = 0; i < size(); i++) {
         if (exist(i)) {
             SdesItem *compareItem = check_and_cast<SdesItem *>(get(i));
             if (compareItem->getType() == sdesItem->getType()) {
                 remove(compareItem);
                 _length = _length - compareItem->getSdesTotalLength();
                 delete compareItem;
             }
         }
     }
 //    sdesItem->setOwner(this);
     add(sdesItem);
     _length += sdesItem->getSdesTotalLength();
 }
Referenced by inet::rtp::RtpParticipantInfo::addSDESItem().
copy()
void inet::rtp::SdesChunk::copy (const SdesChunk & other) inline private
 {
     _ssrc = sdesChunk._ssrc;
     _length = sdesChunk._length;
 }
Referenced by operator=(), and SdesChunk().
dump()
void inet::rtp::SdesChunk::dump (std::ostream & os) const virtual
Writes a longer info about this SdesChunk into the given stream.
 {
     os << "SdesChunk:" << endl;
     os << "  ssrc = " << _ssrc << endl;
     for (int i = 0; i < size(); i++) {
         if (exist(i)) {
             ((const SdesItem *)(get(i)))->dump(os);
         }
     }
 }
dup()
SdesChunk * inet::rtp::SdesChunk::dup () const override virtual
Duplicates this SdesChunk by calling the copy constructor.
 {
     return new SdesChunk(*this);
 }
getLength()
int inet::rtp::SdesChunk::getLength () const virtual
Returns the length in bytes of this SdesChunk.
 {
     return _length;
 }
Referenced by inet::rtp::RtcpSdesPacket::addSDESChunk().
getSsrc()
uint32_t inet::rtp::SdesChunk::getSsrc () const virtual
Returns the ssrc identifier this SdesChunk is for.
 {
     return _ssrc;
 }
Referenced by inet::rtp::RtpParticipantInfo::getSsrc(), and inet::rtp::Rtcp::processIncomingRTCPSDESPacket().
operator=()
SdesChunk & inet::rtp::SdesChunk::operator= (const SdesChunk & sdesChunk)
Operator equal.
 {
     if (this == &sdesChunk)
         return *this;
     cArray::operator=(sdesChunk);
     copy(sdesChunk);
     return *this;
 }
setSsrc()
void inet::rtp::SdesChunk::setSsrc (uint32_t ssrc) virtual
Sets the ssrc identifier this SdesChunk is for.
 {
     _ssrc = ssrc;
 }
Referenced by inet::rtp::RtpParticipantInfo::setSsrc().
str()
std::string inet::rtp::SdesChunk::str () const override virtual
Writes a short info about this SdesChunk into the given string.
 {
     std::stringstream out;
     out << "SdesChunk.ssrc=" << _ssrc << " items=" << size();
     return out.str();
 }
Member Data Documentation
_length
int inet::rtp::SdesChunk::_length protected
The length in bytes of this SdesChunk.
Referenced by addSDESItem(), copy(), getLength(), and SdesChunk().
_ssrc
uint32_t inet::rtp::SdesChunk::_ssrc protected
The ssrc identifier this SdesChunk is for.
Referenced by copy(), dump(), getSsrc(), SdesChunk(), setSsrc(), and str().
The documentation for this class was generated from the following files:
Sdes.h
Sdes.cc