INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3InterAreaPrefixLsa Class Reference
inet::ospfv3::Ospfv3InterAreaPrefixLsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:228 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3InterAreaPrefixLsa ()
Ospfv3InterAreaPrefixLsa (const Ospfv3InterAreaPrefixLsa &other)
virtual ~Ospfv3InterAreaPrefixLsa ()
Ospfv3InterAreaPrefixLsa & operator= (const Ospfv3InterAreaPrefixLsa &other)
virtual Ospfv3InterAreaPrefixLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getReserved1 () const
virtual void setReserved1 (uint8_t reserved1)
virtual uint32_t getMetric () const
virtual void setMetric (uint32_t metric)
virtual const Ospfv3LsaPrefix0 & getPrefix () const
virtual Ospfv3LsaPrefix0 & getPrefixForUpdate ()
virtual void setPrefix (const Ospfv3LsaPrefix0 &prefix)
Public Member Functions inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3InterAreaPrefixLsa &)=delete
Protected Member Functions inherited from inet::ospfv3::Ospfv3Lsa
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
uint8_t reserved1 = 0
uint32_t metric = 0
Ospfv3LsaPrefix0 prefix
Protected Attributes inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3InterAreaPrefixLsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:228 by opp_msgtool.
// Inter-Area-Prefix-LSAs
class Ospfv3InterAreaPrefixLsa extends Ospfv3Lsa
{
    uint8_t reserved1 = 0;      // 8 bits
    uint32_t metric;            // 24 bits
    Ospfv3LsaPrefix0 prefix;
}
Constructor & Destructor Documentation
Ospfv3InterAreaPrefixLsa() [1/2]
inet::ospfv3::Ospfv3InterAreaPrefixLsa::Ospfv3InterAreaPrefixLsa ()
Ospfv3InterAreaPrefixLsa() [2/2]
inet::ospfv3::Ospfv3InterAreaPrefixLsa::Ospfv3InterAreaPrefixLsa (const Ospfv3InterAreaPrefixLsa & other)
~Ospfv3InterAreaPrefixLsa()
virtual inet::ospfv3::Ospfv3InterAreaPrefixLsa::~Ospfv3InterAreaPrefixLsa () virtual
Member Function Documentation
copy()
void inet::ospfv3::Ospfv3InterAreaPrefixLsa::copy (const Ospfv3InterAreaPrefixLsa & other) private
dup()
virtual Ospfv3InterAreaPrefixLsa* inet::ospfv3::Ospfv3InterAreaPrefixLsa::dup () const inline override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
 {return new Ospfv3InterAreaPrefixLsa(*this);}
getMetric()
virtual uint32_t inet::ospfv3::Ospfv3InterAreaPrefixLsa::getMetric () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::interAreaPrefixLSADiffersFrom(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getPrefix()
virtual const Ospfv3LsaPrefix0& inet::ospfv3::Ospfv3InterAreaPrefixLsa::getPrefix () const virtual
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::calculateLSASize(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::InterAreaPrefixLSAAlreadyExists(), inet::ospfv3::Ospfv3Area::interAreaPrefixLSADiffersFrom(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getPrefixForUpdate()
virtual Ospfv3LsaPrefix0& inet::ospfv3::Ospfv3InterAreaPrefixLsa::getPrefixForUpdate () inline virtual
 { return const_cast<Ospfv3LsaPrefix0&>(const_cast<Ospfv3InterAreaPrefixLsa*>(this)->getPrefix());}
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA().
getReserved1()
virtual uint8_t inet::ospfv3::Ospfv3InterAreaPrefixLsa::getReserved1 () const virtual
operator=()
Ospfv3InterAreaPrefixLsa& inet::ospfv3::Ospfv3InterAreaPrefixLsa::operator= (const Ospfv3InterAreaPrefixLsa & other)
operator==()
bool inet::ospfv3::Ospfv3InterAreaPrefixLsa::operator== (const Ospfv3InterAreaPrefixLsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3InterAreaPrefixLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3InterAreaPrefixLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setMetric()
virtual void inet::ospfv3::Ospfv3InterAreaPrefixLsa::setMetric (uint32_t metric) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA().
setPrefix()
virtual void inet::ospfv3::Ospfv3InterAreaPrefixLsa::setPrefix (const Ospfv3LsaPrefix0 & prefix) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA().
setReserved1()
virtual void inet::ospfv3::Ospfv3InterAreaPrefixLsa::setReserved1 (uint8_t reserved1) virtual
Member Data Documentation
metric
uint32_t inet::ospfv3::Ospfv3InterAreaPrefixLsa::metric = 0 protected
prefix
Ospfv3LsaPrefix0 inet::ospfv3::Ospfv3InterAreaPrefixLsa::prefix protected
reserved1
uint8_t inet::ospfv3::Ospfv3InterAreaPrefixLsa::reserved1 = 0 protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h