INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Mib::BssStationData Class Reference
inet::ieee80211::Ieee80211Mib::BssStationData Class Reference
#include <Ieee80211Mib.h>
Public Attributes
BssStationType stationType = static_cast<BssStationType>(-1)
bool isAssociated = false
Member Data Documentation
isAssociated
bool inet::ieee80211::Ieee80211Mib::BssStationData::isAssociated = false
Referenced by inet::ieee80211::Ieee80211Mib::initialize(), inet::ieee80211::Ds::processDataFrame(), and inet::ieee80211::Ieee80211Mib::refreshDisplay().
stationType
BssStationType inet::ieee80211::Ieee80211Mib::BssStationData::stationType = static_cast<BssStationType>(-1)
Referenced by inet::ieee80211::Ieee80211Mib::initialize(), inet::ieee80211::Ds::processDataFrame(), and inet::ieee80211::Ieee80211Mib::refreshDisplay().
The documentation for this class was generated from the following file:
Ieee80211Mib.h