INET Framework for OMNeT++/OMNEST: inet::physicallayer::ILayeredErrorModel Class Reference
inet::physicallayer::ILayeredErrorModel Class Reference abstract
The layered error model computes the erroneous bits, symbols, or samples based on the SNIR and a simplified model of the signal processing.
#include <ILayeredErrorModel.h>
Public Member Functions
virtual const IReceptionPacketModel * computePacketModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the packet domain representation at the receiver using a simplified model for the underlying domains.
virtual const IReceptionBitModel * computeBitModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the bit domain representation at the receiver using a simplified model for the underlying domains.
virtual const IReceptionSymbolModel * computeSymbolModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the symbol domain representation at the receiver using a simplified model for the underlying domains.
virtual const IReceptionSampleModel * computeSampleModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the sample domain representation at the receiver using a simplified model for the underlying domains.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
The layered error model computes the erroneous bits, symbols, or samples based on the SNIR and a simplified model of the signal processing.
Member Function Documentation
computeBitModel()
virtual const IReceptionBitModel* inet::physicallayer::ILayeredErrorModel::computeBitModel (const LayeredTransmission * transmission, const ISnir * snir) const pure virtual
Computes the bit domain representation at the receiver using a simplified model for the underlying domains.
This result includes all potential errors that were not corrected by the underlying domains.
Implemented in inet::physicallayer::Ieee80211OfdmErrorModel, inet::physicallayer::StochasticLayeredErrorModel, and inet::physicallayer::ApskLayeredErrorModel.
Referenced by inet::physicallayer::ApskLayeredReceiver::createBitModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createBitModel().
computePacketModel()
virtual const IReceptionPacketModel* inet::physicallayer::ILayeredErrorModel::computePacketModel (const LayeredTransmission * transmission, const ISnir * snir) const pure virtual
Computes the packet domain representation at the receiver using a simplified model for the underlying domains.
This result includes all potential errors that were not corrected by the underlying domains.
Implemented in inet::physicallayer::Ieee80211OfdmErrorModel, inet::physicallayer::StochasticLayeredErrorModel, and inet::physicallayer::ApskLayeredErrorModel.
Referenced by inet::physicallayer::ApskLayeredReceiver::createPacketModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createPacketModel().
computeSampleModel()
virtual const IReceptionSampleModel* inet::physicallayer::ILayeredErrorModel::computeSampleModel (const LayeredTransmission * transmission, const ISnir * snir) const pure virtual
Computes the sample domain representation at the receiver using a simplified model for the underlying domains.
This result includes all potential errors that were not corrected by the underlying domains.
Implemented in inet::physicallayer::Ieee80211OfdmErrorModel, inet::physicallayer::StochasticLayeredErrorModel, and inet::physicallayer::ApskLayeredErrorModel.
Referenced by inet::physicallayer::ApskLayeredReceiver::createSampleModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSampleModel().
computeSymbolModel()
virtual const IReceptionSymbolModel* inet::physicallayer::ILayeredErrorModel::computeSymbolModel (const LayeredTransmission * transmission, const ISnir * snir) const pure virtual
Computes the symbol domain representation at the receiver using a simplified model for the underlying domains.
This result includes all potential errors that were not corrected by the underlying domains.
Implemented in inet::physicallayer::Ieee80211OfdmErrorModel, inet::physicallayer::StochasticLayeredErrorModel, and inet::physicallayer::ApskLayeredErrorModel.
Referenced by inet::physicallayer::ApskLayeredReceiver::createSymbolModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSymbolModel().
The documentation for this class was generated from the following file:
ILayeredErrorModel.h