INET Framework for OMNeT++/OMNEST: inet::ospfv2::Neighbor Class Reference
inet::ospfv2::Neighbor Class Reference
#include <Ospfv2Neighbor.h>
Classes
struct DdPacketId
struct TransmittedLsa
Public Types
enum NeighborEventType {
HELLO_RECEIVED = 0, START = 1, TWOWAY_RECEIVED = 2, NEGOTIATION_DONE = 3,
EXCHANGE_DONE = 4, BAD_LINK_STATE_REQUEST = 5, LOADING_DONE = 6, IS_ADJACENCY_OK = 7,
SEQUENCE_NUMBER_MISMATCH = 8, ONEWAY_RECEIVED = 9, KILL_NEIGHBOR = 10, INACTIVITY_TIMER = 11,
POLL_TIMER = 12, LINK_DOWN = 13, DD_RETRANSMISSION_TIMER = 14, UPDATE_RETRANSMISSION_TIMER = 15,
REQUEST_RETRANSMISSION_TIMER = 16
}
enum NeighborStateType {
DOWN_STATE = 0, ATTEMPT_STATE = 1, INIT_STATE = 2, TWOWAY_STATE = 4,
EXCHANGE_START_STATE = 8, EXCHANGE_STATE = 16, LOADING_STATE = 32, FULL_STATE = 64
}
enum DatabaseExchangeRelationshipType { MASTER = 0, SLAVE = 1 }
Public Member Functions
Neighbor (RouterId neighbor=NULL_ROUTERID)
virtual ~Neighbor ()
void processEvent (NeighborEventType event)
void reset ()
void initFirstAdjacency ()
NeighborStateType getState () const
void sendDatabaseDescriptionPacket (bool init=false)
bool retransmitDatabaseDescriptionPacket ()
void createDatabaseSummary ()
void sendLinkStateRequestPacket ()
void retransmitUpdatePacket ()
bool needAdjacency ()
void addToRetransmissionList (const Ospfv2Lsa *lsa)
If the LSA is already on the retransmission list then it is replaced, else a copy of the LSA is added to the end of the retransmission list.
void removeFromRetransmissionList (LsaKeyType lsaKey)
bool isLinkStateRequestListEmpty (LsaKeyType lsaKey) const
Ospfv2Lsa * findOnRetransmissionList (LsaKeyType lsaKey)
void startUpdateRetransmissionTimer ()
void clearUpdateRetransmissionTimer ()
void addToRequestList (const Ospfv2LsaHeader *lsaHeader)
void removeFromRequestList (LsaKeyType lsaKey)
bool isLSAOnRequestList (LsaKeyType lsaKey) const
Ospfv2LsaHeader * findOnRequestList (LsaKeyType lsaKey)
void startRequestRetransmissionTimer ()
void clearRequestRetransmissionTimer ()
void addToTransmittedLSAList (LsaKeyType lsaKey)
bool isOnTransmittedLSAList (LsaKeyType lsaKey) const
void ageTransmittedLSAList ()
unsigned long getUniqueULong ()
void deleteLastSentDDPacket ()
void setNeighborID (RouterId id)
RouterId getNeighborID () const
void setPriority (unsigned char priority)
unsigned char getPriority () const
void setAddress (Ipv4Address address)
Ipv4Address getAddress () const
void setDesignatedRouter (DesignatedRouterId routerID)
DesignatedRouterId getDesignatedRouter () const
void setBackupDesignatedRouter (DesignatedRouterId routerID)
DesignatedRouterId getBackupDesignatedRouter () const
void setRouterDeadInterval (short interval)
short getRouterDeadInterval () const
void setDDSequenceNumber (unsigned long sequenceNumber)
unsigned long getDDSequenceNumber () const
void setOptions (Ospfv2Options options)
Ospfv2Options getOptions () const
void setLastReceivedDDPacket (DdPacketId packetID)
DdPacketId getLastReceivedDDPacket () const
void setDatabaseExchangeRelationship (DatabaseExchangeRelationshipType relation)
DatabaseExchangeRelationshipType getDatabaseExchangeRelationship () const
void setInterface (Ospfv2Interface *intf)
Ospfv2Interface * getInterface ()
const Ospfv2Interface * getInterface () const
cMessage * getInactivityTimer ()
cMessage * getPollTimer ()
cMessage * getDDRetransmissionTimer ()
cMessage * getUpdateRetransmissionTimer ()
bool isUpdateRetransmissionTimerActive () const
bool isRequestRetransmissionTimerActive () const
bool isFirstAdjacencyInited () const
bool designatedRoutersAreSetUp () const
void setupDesignatedRouters (bool setUp)
unsigned long getDatabaseSummaryListCount () const
void incrementDDSequenceNumber ()
bool isLinkStateRequestListEmpty () const
bool isLinkStateRetransmissionListEmpty () const
void popFirstLinkStateRequest ()
Static Public Member Functions
static const char * getStateString (NeighborStateType stateType)
Private Member Functions
void changeState (NeighborState *newState, NeighborState *currentState)
Private Attributes
NeighborState * state = nullptr
NeighborState * previousState = nullptr
cMessage * inactivityTimer = nullptr
cMessage * pollTimer = nullptr
cMessage * ddRetransmissionTimer = nullptr
cMessage * updateRetransmissionTimer = nullptr
bool updateRetransmissionTimerActive = false
cMessage * requestRetransmissionTimer = nullptr
bool requestRetransmissionTimerActive = false
DatabaseExchangeRelationshipType databaseExchangeRelationship = static_cast<DatabaseExchangeRelationshipType>(-1)
bool firstAdjacencyInited = false
unsigned long ddSequenceNumber = 0
DdPacketId lastReceivedDDPacket
RouterId neighborID
unsigned char neighborPriority = 0
Ipv4Address neighborIPAddress
Ospfv2Options neighborOptions
DesignatedRouterId neighborsDesignatedRouter
DesignatedRouterId neighborsBackupDesignatedRouter
bool designatedRoutersSetUp = false
short neighborsRouterDeadInterval = 0
std::list< Ospfv2Lsa * > linkStateRetransmissionList
std::list< Ospfv2LsaHeader * > databaseSummaryList
std::list< Ospfv2LsaHeader * > linkStateRequestList
std::list< TransmittedLsa > transmittedLSAs
Packet * lastTransmittedDDPacket = nullptr
Ospfv2Interface * parentInterface = nullptr
Static Private Attributes
static unsigned long ddSequenceNumberInitSeed = 0
Friends
class NeighborState
Member Enumeration Documentation
DatabaseExchangeRelationshipType
enum inet::ospfv2::Neighbor::DatabaseExchangeRelationshipType
Enumerator
MASTER
SLAVE
{
         MASTER = 0,
         SLAVE  = 1
     };
NeighborEventType
enum inet::ospfv2::Neighbor::NeighborEventType
Enumerator
HELLO_RECEIVED
START
TWOWAY_RECEIVED
NEGOTIATION_DONE
EXCHANGE_DONE
BAD_LINK_STATE_REQUEST
LOADING_DONE
IS_ADJACENCY_OK
SEQUENCE_NUMBER_MISMATCH
ONEWAY_RECEIVED
KILL_NEIGHBOR
INACTIVITY_TIMER
POLL_TIMER
LINK_DOWN
DD_RETRANSMISSION_TIMER
UPDATE_RETRANSMISSION_TIMER
REQUEST_RETRANSMISSION_TIMER
{
         HELLO_RECEIVED               = 0,
         START                        = 1,
         TWOWAY_RECEIVED              = 2,
         NEGOTIATION_DONE             = 3,
         EXCHANGE_DONE                = 4,
         BAD_LINK_STATE_REQUEST       = 5,
         LOADING_DONE                 = 6,
         IS_ADJACENCY_OK              = 7,
         SEQUENCE_NUMBER_MISMATCH     = 8,
         ONEWAY_RECEIVED              = 9,
         KILL_NEIGHBOR                = 10,
         INACTIVITY_TIMER             = 11,
         POLL_TIMER                   = 12,
         LINK_DOWN                    = 13,
         DD_RETRANSMISSION_TIMER      = 14,
         UPDATE_RETRANSMISSION_TIMER  = 15,
         REQUEST_RETRANSMISSION_TIMER = 16
     };
NeighborStateType
enum inet::ospfv2::Neighbor::NeighborStateType
Enumerator
DOWN_STATE
ATTEMPT_STATE
INIT_STATE
TWOWAY_STATE
EXCHANGE_START_STATE
EXCHANGE_STATE
LOADING_STATE
FULL_STATE
{
         DOWN_STATE           = 0,
         ATTEMPT_STATE        = 1,
         INIT_STATE           = 2,
         TWOWAY_STATE         = 4,
         EXCHANGE_START_STATE = 8,
         EXCHANGE_STATE       = 16,
         LOADING_STATE        = 32,
         FULL_STATE           = 64
     };
Constructor & Destructor Documentation
Neighbor()
inet::ospfv2::Neighbor::Neighbor (RouterId neighbor = NULL_ROUTERID)
                                     :
     neighborID(neighbor),
     neighborIPAddress(NULL_IPV4ADDRESS),
     neighborsDesignatedRouter(NULL_DESIGNATEDROUTERID),
     neighborsBackupDesignatedRouter(NULL_DESIGNATEDROUTERID),
     neighborsRouterDeadInterval(40)
 {
     Neighbor::DdPacketId emptyDD;
     lastReceivedDDPacket = emptyDD;
     // setting only I and M bits is invalid -> good initializer
     lastReceivedDDPacket.ddOptions.I_Init = true;
     lastReceivedDDPacket.ddOptions.M_More = true;
     inactivityTimer = new cMessage("Neighbor::NeighborInactivityTimer", NEIGHBOR_INACTIVITY_TIMER);
     inactivityTimer->setContextPointer(this);
     pollTimer = new cMessage("Neighbor::NeighborPollTimer", NEIGHBOR_POLL_TIMER);
     pollTimer->setContextPointer(this);
     ddRetransmissionTimer = new cMessage("Neighbor::NeighborDDRetransmissionTimer", NEIGHBOR_DD_RETRANSMISSION_TIMER);
     ddRetransmissionTimer->setContextPointer(this);
     updateRetransmissionTimer = new cMessage("Neighbor::Neighbor::NeighborUpdateRetransmissionTimer", NEIGHBOR_UPDATE_RETRANSMISSION_TIMER);
     updateRetransmissionTimer->setContextPointer(this);
     requestRetransmissionTimer = new cMessage("Neighbor::NeighborRequestRetransmissionTimer", NEIGHBOR_REQUEST_RETRANSMISSION_TIMER);
     requestRetransmissionTimer->setContextPointer(this);
     state = new NeighborStateDown;
     previousState = nullptr;
 }
~Neighbor()
inet::ospfv2::Neighbor::~Neighbor () virtual
 {
     reset();
     if (parentInterface && parentInterface->getArea()) {
         MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
         messageHandler->clearTimer(inactivityTimer);
         messageHandler->clearTimer(pollTimer);
     }
     delete inactivityTimer;
     delete pollTimer;
     delete ddRetransmissionTimer;
     delete updateRetransmissionTimer;
     delete requestRetransmissionTimer;
     if (previousState)
         delete previousState;
     delete state;
 }
Member Function Documentation
addToRequestList()
void inet::ospfv2::Neighbor::addToRequestList (const Ospfv2LsaHeader * lsaHeader)
 {
     linkStateRequestList.push_back(new Ospfv2LsaHeader(*lsaHeader));
 }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processDDPacket().
addToRetransmissionList()
void inet::ospfv2::Neighbor::addToRetransmissionList (const Ospfv2Lsa * lsa)
If the LSA is already on the retransmission list then it is replaced, else a copy of the LSA is added to the end of the retransmission list.
Parameters
lsa [in] The LSA to be added.
 {
     auto it = linkStateRetransmissionList.begin();
     for (; it != linkStateRetransmissionList.end(); it++) {
         if (((*it)->getHeader().getLinkStateID() == lsa->getHeader().getLinkStateID()) &&
             ((*it)->getHeader().getAdvertisingRouter().getInt() == lsa->getHeader().getAdvertisingRouter().getInt()))
         {
             break;
         }
     }
     Ospfv2Lsa *lsaCopy = nullptr;
     switch (lsa->getHeader().getLsType()) {
         case ROUTERLSA_TYPE:
             lsaCopy = new Ospfv2RouterLsa(*(check_and_cast<const Ospfv2RouterLsa *>(lsa)));
             break;
         case NETWORKLSA_TYPE:
             lsaCopy = new Ospfv2NetworkLsa(*(check_and_cast<const Ospfv2NetworkLsa *>(lsa)));
             break;
         case SUMMARYLSA_NETWORKS_TYPE:
         case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
             lsaCopy = new Ospfv2SummaryLsa(*(check_and_cast<const Ospfv2SummaryLsa *>(lsa)));
             break;
         case AS_EXTERNAL_LSA_TYPE:
             lsaCopy = new Ospfv2AsExternalLsa(*(check_and_cast<const Ospfv2AsExternalLsa *>(lsa)));
             break;
         default:
             ASSERT(false); // error
             break;
     }
     if (it != linkStateRetransmissionList.end()) {
         delete *it;
         *it = static_cast<Ospfv2Lsa *>(lsaCopy);
     }
     else {
         linkStateRetransmissionList.push_back(static_cast<Ospfv2Lsa *>(lsaCopy));
     }
 }
addToTransmittedLSAList()
void inet::ospfv2::Neighbor::addToTransmittedLSAList (LsaKeyType lsaKey)
 {
     TransmittedLsa transmit;
     transmit.lsaKey = lsaKey;
     transmit.age = 0;
     transmittedLSAs.push_back(transmit);
 }
Referenced by inet::ospfv2::Ospfv2Interface::floodLsa().
ageTransmittedLSAList()
void inet::ospfv2::Neighbor::ageTransmittedLSAList ()
 {
     auto it = transmittedLSAs.begin();
     while ((it != transmittedLSAs.end()) && (it->age == MIN_LS_ARRIVAL)) {
         transmittedLSAs.pop_front();
         it = transmittedLSAs.begin();
     }
     for (it = transmittedLSAs.begin(); it != transmittedLSAs.end(); it++) {
         it->age++;
     }
 }
changeState()
void inet::ospfv2::Neighbor::changeState (NeighborState * newState, NeighborState * currentState) private
 {
     EV_INFO << "Changing neighborhood state of " << this->getNeighborID().str(false)
             << " from '" << getStateString(currentState->getState())
             << "' to '" << getStateString(newState->getState()) << "'" << std::endl;
     if (previousState != nullptr) {
         delete previousState;
     }
     state = newState;
     previousState = currentState;
 }
Referenced by inet::ospfv2::NeighborState::changeState().
clearRequestRetransmissionTimer()
void inet::ospfv2::Neighbor::clearRequestRetransmissionTimer ()
 {
     if (parentInterface && parentInterface->getArea()) {
         MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
         messageHandler->clearTimer(requestRetransmissionTimer);
     }
     requestRetransmissionTimerActive = false;
 }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), removeFromRequestList(), and reset().
clearUpdateRetransmissionTimer()
void inet::ospfv2::Neighbor::clearUpdateRetransmissionTimer ()
 {
     if (parentInterface && parentInterface->getArea()) {
         MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
         messageHandler->clearTimer(updateRetransmissionTimer);
     }
     updateRetransmissionTimerActive = false;
 }
Referenced by inet::ospfv2::LinkStateAcknowledgementHandler::processPacket(), and reset().
createDatabaseSummary()
void inet::ospfv2::Neighbor::createDatabaseSummary ()
 {
     Ospfv2Area *area = parentInterface->getArea();
     unsigned long routerLSACount = area->getRouterLSACount();
     /* Note: OSPF specification says:
      * "LSAs whose age is equal to MaxAge are instead added to the neighbor's
      *  Link state retransmission list."
      * But this task has been already done during the aging of the database. (???)
      * So we'll skip this.
      */
     for (unsigned long i = 0; i < routerLSACount; i++) {
         if (area->getRouterLSA(i)->getHeader().getLsAge() < MAX_AGE) {
             Ospfv2LsaHeader *routerLSA = new Ospfv2LsaHeader(area->getRouterLSA(i)->getHeader());
             databaseSummaryList.push_back(routerLSA);
         }
     }
     unsigned long networkLSACount = area->getNetworkLSACount();
     for (unsigned long j = 0; j < networkLSACount; j++) {
         if (area->getNetworkLSA(j)->getHeader().getLsAge() < MAX_AGE) {
             Ospfv2LsaHeader *networkLSA = new Ospfv2LsaHeader(area->getNetworkLSA(j)->getHeader());
             databaseSummaryList.push_back(networkLSA);
         }
     }
     unsigned long summaryLSACount = area->getSummaryLSACount();
     for (unsigned long k = 0; k < summaryLSACount; k++) {
         if (area->getSummaryLSA(k)->getHeader().getLsAge() < MAX_AGE) {
             Ospfv2LsaHeader *summaryLSA = new Ospfv2LsaHeader(area->getSummaryLSA(k)->getHeader());
             databaseSummaryList.push_back(summaryLSA);
         }
     }
     if ((parentInterface->getType() != Ospfv2Interface::VIRTUAL) &&
         (area->getExternalRoutingCapability()))
     {
         Router *router = area->getRouter();
         unsigned long asExternalLSACount = router->getASExternalLSACount();
         for (unsigned long m = 0; m < asExternalLSACount; m++) {
             if (router->getASExternalLSA(m)->getHeader().getLsAge() < MAX_AGE) {
                 Ospfv2LsaHeader *asExternalLSA = new Ospfv2LsaHeader(router->getASExternalLSA(m)->getHeader());
                 databaseSummaryList.push_back(asExternalLSA);
             }
         }
     }
 }
Referenced by inet::ospfv2::NeighborStateExchangeStart::processEvent().
deleteLastSentDDPacket()
void inet::ospfv2::Neighbor::deleteLastSentDDPacket ()
 {
     if (lastTransmittedDDPacket != nullptr) {
         delete lastTransmittedDDPacket;
         lastTransmittedDDPacket = nullptr;
     }
 }
Referenced by inet::ospfv2::NeighborStateFull::processEvent(), and inet::ospfv2::NeighborStateLoading::processEvent().
designatedRoutersAreSetUp()
bool inet::ospfv2::Neighbor::designatedRoutersAreSetUp () const inline
 { return designatedRoutersSetUp; }
Referenced by inet::ospfv2::HelloHandler::processPacket().
findOnRequestList()
Ospfv2LsaHeader * inet::ospfv2::Neighbor::findOnRequestList (LsaKeyType lsaKey)
 {
     for (auto& elem : linkStateRequestList) {
         if (((elem)->getLinkStateID() == lsaKey.linkStateID) &&
             ((elem)->getAdvertisingRouter() == lsaKey.advertisingRouter))
         {
             return elem;
         }
     }
     return nullptr;
 }
findOnRetransmissionList()
Ospfv2Lsa * inet::ospfv2::Neighbor::findOnRetransmissionList (LsaKeyType lsaKey)
 {
     for (auto& elem : linkStateRetransmissionList) {
         if (((elem)->getHeader().getLinkStateID() == lsaKey.linkStateID) &&
             ((elem)->getHeader().getAdvertisingRouter() == lsaKey.advertisingRouter))
         {
             return elem;
         }
     }
     return nullptr;
 }
Referenced by inet::ospfv2::LinkStateAcknowledgementHandler::processPacket().
getAddress()
Ipv4Address inet::ospfv2::Neighbor::getAddress () const inline
 { return neighborIPAddress; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2Interface::addNeighbor(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::NeighborStateDown::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateRequestHandler::processPacket(), and inet::ospfv2::LinkStateUpdateHandler::processPacket().
getBackupDesignatedRouter()
DesignatedRouterId inet::ospfv2::Neighbor::getBackupDesignatedRouter () const inline
 { return neighborsBackupDesignatedRouter; }
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), and inet::ospfv2::HelloHandler::processPacket().
getDatabaseExchangeRelationship()
DatabaseExchangeRelationshipType inet::ospfv2::Neighbor::getDatabaseExchangeRelationship () const inline
 { return databaseExchangeRelationship; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processPacket().
getDatabaseSummaryListCount()
unsigned long inet::ospfv2::Neighbor::getDatabaseSummaryListCount () const inline
 { return databaseSummaryList.size(); }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processDDPacket().
getDDRetransmissionTimer()
cMessage* inet::ospfv2::Neighbor::getDDRetransmissionTimer () inline
 { return ddRetransmissionTimer; }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), and inet::ospfv2::NeighborStateExchangeStart::processEvent().
getDDSequenceNumber()
unsigned long inet::ospfv2::Neighbor::getDDSequenceNumber () const inline
 { return ddSequenceNumber; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processPacket().
getDesignatedRouter()
DesignatedRouterId inet::ospfv2::Neighbor::getDesignatedRouter () const inline
 { return neighborsDesignatedRouter; }
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), and inet::ospfv2::HelloHandler::processPacket().
getInactivityTimer()
cMessage* inet::ospfv2::Neighbor::getInactivityTimer () inline
 { return inactivityTimer; }
Referenced by inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateDown::processEvent().
getInterface() [1/2]
Ospfv2Interface* inet::ospfv2::Neighbor::getInterface () inline
 { return parentInterface; }
Referenced by inet::ospfv2::NeighborState::changeState(), inet::ospfv2::MessageHandler::handleTimer(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateDown::processEvent(), inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborState::updateLsa().
getInterface() [2/2]
const Ospfv2Interface* inet::ospfv2::Neighbor::getInterface () const inline
 { return parentInterface; }
getLastReceivedDDPacket()
DdPacketId inet::ospfv2::Neighbor::getLastReceivedDDPacket () const inline
 { return lastReceivedDDPacket; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processPacket().
getNeighborID()
RouterId inet::ospfv2::Neighbor::getNeighborID () const inline
 { return neighborID; }
Referenced by inet::ospfv2::Ospfv2Interface::addNeighbor(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::Ospfv2Area::calculateNextHops(), changeState(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::MessageHandler::printEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::HelloHandler::processPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processPacket().
getOptions()
Ospfv2Options inet::ospfv2::Neighbor::getOptions () const inline
 { return neighborOptions; }
getPollTimer()
cMessage* inet::ospfv2::Neighbor::getPollTimer () inline
 { return pollTimer; }
Referenced by inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateDown::processEvent().
getPriority()
unsigned char inet::ospfv2::Neighbor::getPriority () const inline
 { return neighborPriority; }
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
getRouterDeadInterval()
short inet::ospfv2::Neighbor::getRouterDeadInterval () const inline
 { return neighborsRouterDeadInterval; }
Referenced by inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateDown::processEvent().
getState()
Neighbor::NeighborStateType inet::ospfv2::Neighbor::getState () const
 {
     return state->getState();
 }
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::MessageHandler::printEvent(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::LinkStateAcknowledgementHandler::processPacket(), inet::ospfv2::DatabaseDescriptionHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), and removeFromRequestList().
getStateString()
const char * inet::ospfv2::Neighbor::getStateString (Neighbor::NeighborStateType stateType) static
 {
     switch (stateType) {
         case DOWN_STATE:
             return "Down";
         case ATTEMPT_STATE:
             return "Attempt";
         case INIT_STATE:
             return "Init";
         case TWOWAY_STATE:
             return "TwoWay";
         case EXCHANGE_START_STATE:
             return "ExchangeStart";
         case EXCHANGE_STATE:
             return "Exchange";
         case LOADING_STATE:
             return "Loading";
         case FULL_STATE:
             return "Full";
         default:
             ASSERT(false);
             break;
     }
     return "";
 }
Referenced by changeState(), inet::ospfv2::operator<<(), and inet::ospfv2::MessageHandler::printEvent().
getUniqueULong()
unsigned long inet::ospfv2::Neighbor::getUniqueULong ()
 {
     // FIXME!!! Should come from a global unique number generator module.
     return ddSequenceNumberInitSeed++;
 }
Referenced by initFirstAdjacency().
getUpdateRetransmissionTimer()
cMessage* inet::ospfv2::Neighbor::getUpdateRetransmissionTimer () inline
 { return updateRetransmissionTimer; }
incrementDDSequenceNumber()
void inet::ospfv2::Neighbor::incrementDDSequenceNumber () inline
 { ddSequenceNumber++; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), and inet::ospfv2::NeighborStateExchange::processEvent().
initFirstAdjacency()
void inet::ospfv2::Neighbor::initFirstAdjacency ()
 {
     ddSequenceNumber = getUniqueULong();
     firstAdjacencyInited = true;
 }
Referenced by inet::ospfv2::NeighborStateInit::processEvent(), and inet::ospfv2::NeighborStateTwoWay::processEvent().
isFirstAdjacencyInited()
bool inet::ospfv2::Neighbor::isFirstAdjacencyInited () const inline
 { return firstAdjacencyInited; }
Referenced by inet::ospfv2::NeighborStateInit::processEvent(), and inet::ospfv2::NeighborStateTwoWay::processEvent().
isLinkStateRequestListEmpty() [1/2]
bool inet::ospfv2::Neighbor::isLinkStateRequestListEmpty () const inline
 { return linkStateRequestList.empty(); }
isLinkStateRequestListEmpty() [2/2]
bool inet::ospfv2::Neighbor::isLinkStateRequestListEmpty (LsaKeyType lsaKey) const
 {
     for (auto lsa : linkStateRetransmissionList) {
         if ((lsa->getHeader().getLinkStateID() == lsaKey.linkStateID) &&
             (lsa->getHeader().getAdvertisingRouter() == lsaKey.advertisingRouter))
         {
             return true;
         }
     }
     return false;
 }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::LinkStateUpdateHandler::processPacket().
isLinkStateRetransmissionListEmpty()
bool inet::ospfv2::Neighbor::isLinkStateRetransmissionListEmpty () const inline
 { return linkStateRetransmissionList.empty(); }
Referenced by inet::ospfv2::LinkStateAcknowledgementHandler::processPacket().
isLSAOnRequestList()
bool inet::ospfv2::Neighbor::isLSAOnRequestList (LsaKeyType lsaKey) const
 {
     for (auto lsaHeader : linkStateRequestList) {
         if ((lsaHeader->getLinkStateID() == lsaKey.linkStateID) &&
             (lsaHeader->getAdvertisingRouter() == lsaKey.advertisingRouter))
         {
             return true;
         }
     }
     return false;
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::processPacket().
isOnTransmittedLSAList()
bool inet::ospfv2::Neighbor::isOnTransmittedLSAList (LsaKeyType lsaKey) const
 {
     for (const auto& elem : transmittedLSAs) {
         if ((elem.lsaKey.linkStateID == lsaKey.linkStateID) &&
             (elem.lsaKey.advertisingRouter == lsaKey.advertisingRouter))
         {
             return true;
         }
     }
     return false;
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::processPacket().
isRequestRetransmissionTimerActive()
bool inet::ospfv2::Neighbor::isRequestRetransmissionTimerActive () const inline
 { return requestRetransmissionTimerActive; }
isUpdateRetransmissionTimerActive()
bool inet::ospfv2::Neighbor::isUpdateRetransmissionTimerActive () const inline
 { return updateRetransmissionTimerActive; }
Referenced by inet::ospfv2::Ospfv2Interface::floodLsa().
needAdjacency()
bool inet::ospfv2::Neighbor::needAdjacency ()
 {
     Ospfv2Interface::Ospfv2InterfaceType interfaceType = parentInterface->getType();
     RouterId routerID = parentInterface->getArea()->getRouter()->getRouterID();
     DesignatedRouterId dRouter = parentInterface->getDesignatedRouter();
     DesignatedRouterId backupDRouter = parentInterface->getBackupDesignatedRouter();
     if ((interfaceType == Ospfv2Interface::POINTTOPOINT) ||
         (interfaceType == Ospfv2Interface::POINTTOMULTIPOINT) ||
         (interfaceType == Ospfv2Interface::VIRTUAL) ||
         (dRouter.routerID == routerID) ||
         (backupDRouter.routerID == routerID) ||
         ((neighborsDesignatedRouter.routerID == dRouter.routerID) ||
          (!designatedRoutersSetUp &&
           (neighborsDesignatedRouter.ipInterfaceAddress == dRouter.ipInterfaceAddress))) ||
         ((neighborsBackupDesignatedRouter.routerID == backupDRouter.routerID) ||
          (!designatedRoutersSetUp &&
           (neighborsBackupDesignatedRouter.ipInterfaceAddress == backupDRouter.ipInterfaceAddress))))
     {
         return true;
     }
     else {
         return false;
     }
 }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), and inet::ospfv2::NeighborStateExchangeStart::processEvent().
popFirstLinkStateRequest()
void inet::ospfv2::Neighbor::popFirstLinkStateRequest () inline
 { linkStateRequestList.pop_front(); }
processEvent()
void inet::ospfv2::Neighbor::processEvent (Neighbor::NeighborEventType event)
 {
     state->processEvent(this, event);
 }
Referenced by inet::ospfv2::MessageHandler::handleTimer(), inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), inet::ospfv2::InterfaceStateDown::processEvent(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::DatabaseDescriptionHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), and removeFromRequestList().
removeFromRequestList()
void inet::ospfv2::Neighbor::removeFromRequestList (LsaKeyType lsaKey)
 {
     auto it = linkStateRequestList.begin();
     while (it != linkStateRequestList.end()) {
         if (((*it)->getLinkStateID() == lsaKey.linkStateID) &&
             ((*it)->getAdvertisingRouter() == lsaKey.advertisingRouter))
         {
             delete *it;
             it = linkStateRequestList.erase(it);
         }
         else {
             it++;
         }
     }
     if ((getState() == Neighbor::LOADING_STATE) && (linkStateRequestList.empty())) {
         clearRequestRetransmissionTimer();
         processEvent(Neighbor::LOADING_DONE);
     }
 }
removeFromRetransmissionList()
void inet::ospfv2::Neighbor::removeFromRetransmissionList (LsaKeyType lsaKey)
 {
     auto it = linkStateRetransmissionList.begin();
     while (it != linkStateRetransmissionList.end()) {
         if (((*it)->getHeader().getLinkStateID() == lsaKey.linkStateID) &&
             ((*it)->getHeader().getAdvertisingRouter() == lsaKey.advertisingRouter))
         {
             delete *it;
             it = linkStateRetransmissionList.erase(it);
         }
         else {
             it++;
         }
     }
 }
Referenced by inet::ospfv2::LinkStateAcknowledgementHandler::processPacket(), and inet::ospfv2::LinkStateUpdateHandler::processPacket().
reset()
void inet::ospfv2::Neighbor::reset ()
 {
     for (auto& elem : linkStateRetransmissionList)
         delete elem;
     linkStateRetransmissionList.clear();
     for (auto& elem : databaseSummaryList)
         delete elem;
     databaseSummaryList.clear();
     for (auto& elem : linkStateRequestList)
         delete elem;
     linkStateRequestList.clear();
     if (parentInterface && parentInterface->getArea())
         parentInterface->getArea()->getRouter()->getMessageHandler()->clearTimer(ddRetransmissionTimer);
     clearUpdateRetransmissionTimer();
     clearRequestRetransmissionTimer();
     if (lastTransmittedDDPacket != nullptr) {
         delete lastTransmittedDDPacket;
         lastTransmittedDDPacket = nullptr;
     }
 }
Referenced by inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and ~Neighbor().
retransmitDatabaseDescriptionPacket()
bool inet::ospfv2::Neighbor::retransmitDatabaseDescriptionPacket ()
 {
     if (lastTransmittedDDPacket != nullptr) {
         Packet *ddPacket = new Packet(*lastTransmittedDDPacket);
         MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
         int ttl = (parentInterface->getType() == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
         if (parentInterface->getType() == Ospfv2Interface::POINTTOPOINT) {
             messageHandler->sendPacket(ddPacket, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, parentInterface, ttl);
         }
         else {
             messageHandler->sendPacket(ddPacket, neighborIPAddress, parentInterface, ttl);
         }
         return true;
     }
     else {
         return false;
     }
 }
Referenced by inet::ospfv2::NeighborStateExchangeStart::processEvent(), and inet::ospfv2::DatabaseDescriptionHandler::processPacket().
retransmitUpdatePacket()
void inet::ospfv2::Neighbor::retransmitUpdatePacket ()
 {
     const auto& updatePacket = makeShared<Ospfv2LinkStateUpdatePacket>();
     updatePacket->setType(LINKSTATE_UPDATE_PACKET);
     updatePacket->setRouterID(Ipv4Address(parentInterface->getArea()->getRouter()->getRouterID()));
     updatePacket->setAreaID(Ipv4Address(parentInterface->getArea()->getAreaID()));
     updatePacket->setAuthenticationType(parentInterface->getAuthenticationType());
     bool packetFull = false;
     unsigned short lsaCount = 0;
     B packetLength = IPv4_MAX_HEADER_LENGTH + OSPFv2_HEADER_LENGTH + B(4);
     auto it = linkStateRetransmissionList.begin();
     while (!packetFull && (it != linkStateRetransmissionList.end())) {
         Ospfv2Lsa *ospfLsa = *it;
         B lsaSize = B(0);
         bool includeLSA = false;
         if (ospfLsa != nullptr) {
             lsaSize = calculateLSASize(ospfLsa);
         }
         if (packetLength + lsaSize < B(parentInterface->getMtu())) {
             includeLSA = true;
             lsaCount++;
         }
         else {
             if ((lsaCount == 0) && (packetLength + lsaSize < IPV4_DATAGRAM_LENGTH)) {
                 includeLSA = true;
                 lsaCount++;
                 packetFull = true;
             }
         }
         if (includeLSA) {
             packetLength += lsaSize;
             unsigned int ospfLSACount = updatePacket->getOspfLSAsArraySize();
             setLsaCrc(*ospfLsa, parentInterface->getCrcMode());
             updatePacket->setOspfLSAsArraySize(ospfLSACount + 1);
             updatePacket->setOspfLSAs(ospfLSACount, ospfLsa->dup());
             unsigned short lsAge = updatePacket->getOspfLSAs(ospfLSACount)->getHeader().getLsAge();
             if (lsAge < MAX_AGE - parentInterface->getTransmissionDelay()) {
                 lsAge += parentInterface->getTransmissionDelay();
             }
             else {
                 lsAge = MAX_AGE;
             }
             updatePacket->getOspfLSAsForUpdate(ospfLSACount)->getHeaderForUpdate().setLsAge(lsAge);
         }
         it++;
     }
     updatePacket->setPacketLengthField(B(packetLength - IPv4_MAX_HEADER_LENGTH).get());
     updatePacket->setChunkLength(B(updatePacket->getPacketLengthField()));
     AuthenticationKeyType authKey = parentInterface->getAuthenticationKey();
     for (int i = 0; i < 8; i++) {
         updatePacket->setAuthentication(i, authKey.bytes[i]);
     }
     setOspfCrc(updatePacket, parentInterface->getCrcMode());
     Packet *pk = new Packet();
     pk->insertAtBack(updatePacket);
     MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
     int ttl = (parentInterface->getType() == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
     messageHandler->sendPacket(pk, neighborIPAddress, parentInterface, ttl);
 }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), and inet::ospfv2::NeighborStateFull::processEvent().
sendDatabaseDescriptionPacket()
void inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket (bool init = false)
 {
     const auto& ddPacket = makeShared<Ospfv2DatabaseDescriptionPacket>();
     auto crcMode = parentInterface->getCrcMode();
     ddPacket->setType(DATABASE_DESCRIPTION_PACKET);
     ddPacket->setRouterID(Ipv4Address(parentInterface->getArea()->getRouter()->getRouterID()));
     ddPacket->setAreaID(Ipv4Address(parentInterface->getArea()->getAreaID()));
     ddPacket->setAuthenticationType(parentInterface->getAuthenticationType());
     if (parentInterface->getType() != Ospfv2Interface::VIRTUAL) {
         ddPacket->setInterfaceMTU(parentInterface->getMtu());
     }
     else {
         ddPacket->setInterfaceMTU(0);
     }
     Ospfv2Options options;
     options.E_ExternalRoutingCapability = parentInterface->getArea()->getExternalRoutingCapability();
     ddPacket->setOptions(options);
     ddPacket->setDdSequenceNumber(ddSequenceNumber);
     B maxPacketSize = (((IPv4_MAX_HEADER_LENGTH + OSPFv2_HEADER_LENGTH + OSPFv2_DD_HEADER_LENGTH + OSPFv2_LSA_HEADER_LENGTH) > B(parentInterface->getMtu())) ?
                        IPV4_DATAGRAM_LENGTH :
                        B(parentInterface->getMtu())) - IPv4_MAX_HEADER_LENGTH;
     B packetSize = OSPFv2_HEADER_LENGTH + OSPFv2_DD_HEADER_LENGTH;
     if (init || databaseSummaryList.empty()) {
         ddPacket->setLsaHeadersArraySize(0);
     }
     else {
         // delete included LSAs from summary list
         // (they are still in lastTransmittedDDPacket)
         while ((!databaseSummaryList.empty()) && (packetSize <= (maxPacketSize - OSPFv2_LSA_HEADER_LENGTH))) {
             Ospfv2LsaHeader *lsaHeader = *(databaseSummaryList.begin());
             setLsaHeaderCrc(*lsaHeader, crcMode);
             ddPacket->appendLsaHeaders(*lsaHeader);
             delete lsaHeader;
             databaseSummaryList.pop_front();
             packetSize += OSPFv2_LSA_HEADER_LENGTH;
         }
     }
     Ospfv2DdOptions ddOptions;
     if (init) {
         ddOptions.I_Init = true;
         ddOptions.M_More = true;
         ddOptions.MS_MasterSlave = true;
     }
     else {
         ddOptions.I_Init = false;
         ddOptions.M_More = (databaseSummaryList.empty()) ? false : true;
         ddOptions.MS_MasterSlave = (databaseExchangeRelationship == Neighbor::MASTER) ? true : false;
     }
     ddPacket->setDdOptions(ddOptions);
     ddPacket->setPacketLengthField(B(packetSize).get());
     ddPacket->setChunkLength(packetSize);
     AuthenticationKeyType authKey = parentInterface->getAuthenticationKey();
     for (int i = 0; i < 8; i++) {
         ddPacket->setAuthentication(i, authKey.bytes[i]);
     }
     setOspfCrc(ddPacket, crcMode);
     Packet *pk = new Packet();
     pk->insertAtBack(ddPacket);
     MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
     int ttl = (parentInterface->getType() == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
     if (lastTransmittedDDPacket != nullptr)
         delete lastTransmittedDDPacket;
     lastTransmittedDDPacket = pk->dup();
     if (parentInterface->getType() == Ospfv2Interface::POINTTOPOINT) {
         messageHandler->sendPacket(pk, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, parentInterface, ttl);
     }
     else {
         messageHandler->sendPacket(pk, neighborIPAddress, parentInterface, ttl);
     }
 }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::DatabaseDescriptionHandler::processPacket().
sendLinkStateRequestPacket()
void inet::ospfv2::Neighbor::sendLinkStateRequestPacket ()
 {
     const auto& requestPacket = makeShared<Ospfv2LinkStateRequestPacket>();
     requestPacket->setType(LINKSTATE_REQUEST_PACKET);
     requestPacket->setRouterID(Ipv4Address(parentInterface->getArea()->getRouter()->getRouterID()));
     requestPacket->setAreaID(Ipv4Address(parentInterface->getArea()->getAreaID()));
     requestPacket->setAuthenticationType(parentInterface->getAuthenticationType());
     B maxPacketSize = ((IPv4_MAX_HEADER_LENGTH + OSPFv2_HEADER_LENGTH + OSPFv2_REQUEST_LENGTH) > B(parentInterface->getMtu())) ?
                           IPV4_DATAGRAM_LENGTH :
                           B(parentInterface->getMtu()) - IPv4_MAX_HEADER_LENGTH;
     B packetSize = OSPFv2_HEADER_LENGTH;
     if (linkStateRequestList.empty()) {
         requestPacket->setRequestsArraySize(0);
     }
     else {
         auto it = linkStateRequestList.begin();
         while ((it != linkStateRequestList.end()) && (packetSize <= (maxPacketSize - OSPFv2_REQUEST_LENGTH))) {
             unsigned long requestCount = requestPacket->getRequestsArraySize();
             Ospfv2LsaHeader *requestHeader = (*it);
             Ospfv2LsaRequest request;
             request.lsType = requestHeader->getLsType();
             request.linkStateID = requestHeader->getLinkStateID();
             request.advertisingRouter = requestHeader->getAdvertisingRouter();
             requestPacket->setRequestsArraySize(requestCount + 1);
             requestPacket->setRequests(requestCount, request);
             packetSize += OSPFv2_REQUEST_LENGTH;
             it++;
         }
     }
     requestPacket->setPacketLengthField(B(packetSize).get());
     requestPacket->setChunkLength(packetSize);
     AuthenticationKeyType authKey = parentInterface->getAuthenticationKey();
     for (int i = 0; i < 8; i++) {
         requestPacket->setAuthentication(i, authKey.bytes[i]);
     }
     setOspfCrc(requestPacket, parentInterface->getCrcMode());
     Packet *pk = new Packet();
     pk->insertAtBack(requestPacket);
     MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
     int ttl = (parentInterface->getType() == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
     if (parentInterface->getType() == Ospfv2Interface::POINTTOPOINT) {
         messageHandler->sendPacket(pk, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, parentInterface, ttl);
     }
     else {
         messageHandler->sendPacket(pk, neighborIPAddress, parentInterface, ttl);
     }
 }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateLoading::processEvent().
setAddress()
void inet::ospfv2::Neighbor::setAddress (Ipv4Address address) inline
 { neighborIPAddress = address; }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::HelloHandler::processPacket().
setBackupDesignatedRouter()
void inet::ospfv2::Neighbor::setBackupDesignatedRouter (DesignatedRouterId routerID) inline
 { neighborsBackupDesignatedRouter = routerID; }
Referenced by inet::ospfv2::HelloHandler::processPacket().
setDatabaseExchangeRelationship()
void inet::ospfv2::Neighbor::setDatabaseExchangeRelationship (DatabaseExchangeRelationshipType relation) inline
 { databaseExchangeRelationship = relation; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processPacket().
setDDSequenceNumber()
void inet::ospfv2::Neighbor::setDDSequenceNumber (unsigned long sequenceNumber) inline
 { ddSequenceNumber = sequenceNumber; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processPacket().
setDesignatedRouter()
void inet::ospfv2::Neighbor::setDesignatedRouter (DesignatedRouterId routerID) inline
 { neighborsDesignatedRouter = routerID; }
Referenced by inet::ospfv2::HelloHandler::processPacket().
setInterface()
void inet::ospfv2::Neighbor::setInterface (Ospfv2Interface * intf) inline
 { parentInterface = intf; }
Referenced by inet::ospfv2::Ospfv2Interface::addNeighbor().
setLastReceivedDDPacket()
void inet::ospfv2::Neighbor::setLastReceivedDDPacket (DdPacketId packetID) inline
 { lastReceivedDDPacket = packetID; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processPacket().
setNeighborID()
void inet::ospfv2::Neighbor::setNeighborID (RouterId id) inline
 { neighborID = id; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink(), and inet::ospfv2::HelloHandler::processPacket().
setOptions()
void inet::ospfv2::Neighbor::setOptions (Ospfv2Options options) inline
 { neighborOptions = options; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processPacket().
setPriority()
void inet::ospfv2::Neighbor::setPriority (unsigned char priority) inline
 { neighborPriority = priority; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::HelloHandler::processPacket().
setRouterDeadInterval()
void inet::ospfv2::Neighbor::setRouterDeadInterval (short interval) inline
 { neighborsRouterDeadInterval = interval; }
Referenced by inet::ospfv2::HelloHandler::processPacket().
setupDesignatedRouters()
void inet::ospfv2::Neighbor::setupDesignatedRouters (bool setUp) inline
 { designatedRoutersSetUp = setUp; }
Referenced by inet::ospfv2::HelloHandler::processPacket().
startRequestRetransmissionTimer()
void inet::ospfv2::Neighbor::startRequestRetransmissionTimer ()
 {
     MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
     messageHandler->startTimer(requestRetransmissionTimer, parentInterface->getRetransmissionInterval());
     requestRetransmissionTimerActive = true;
 }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateLoading::processEvent().
startUpdateRetransmissionTimer()
void inet::ospfv2::Neighbor::startUpdateRetransmissionTimer ()
 {
     MessageHandler *messageHandler = parentInterface->getArea()->getRouter()->getMessageHandler();
     messageHandler->startTimer(updateRetransmissionTimer, parentInterface->getRetransmissionInterval());
     updateRetransmissionTimerActive = true;
 }
Referenced by inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), and inet::ospfv2::NeighborStateExchange::processEvent().
Friends And Related Function Documentation
NeighborState
friend class NeighborState friend
Member Data Documentation
databaseExchangeRelationship
DatabaseExchangeRelationshipType inet::ospfv2::Neighbor::databaseExchangeRelationship = static_cast<DatabaseExchangeRelationshipType>(-1) private
Referenced by sendDatabaseDescriptionPacket().
databaseSummaryList
std::list<Ospfv2LsaHeader *> inet::ospfv2::Neighbor::databaseSummaryList private
Referenced by createDatabaseSummary(), reset(), and sendDatabaseDescriptionPacket().
ddRetransmissionTimer
cMessage* inet::ospfv2::Neighbor::ddRetransmissionTimer = nullptr private
Referenced by Neighbor(), reset(), and ~Neighbor().
ddSequenceNumber
unsigned long inet::ospfv2::Neighbor::ddSequenceNumber = 0 private
Referenced by initFirstAdjacency(), and sendDatabaseDescriptionPacket().
ddSequenceNumberInitSeed
unsigned long inet::ospfv2::Neighbor::ddSequenceNumberInitSeed = 0 static private
Referenced by getUniqueULong().
designatedRoutersSetUp
bool inet::ospfv2::Neighbor::designatedRoutersSetUp = false private
Referenced by needAdjacency().
firstAdjacencyInited
bool inet::ospfv2::Neighbor::firstAdjacencyInited = false private
Referenced by initFirstAdjacency().
inactivityTimer
cMessage* inet::ospfv2::Neighbor::inactivityTimer = nullptr private
Referenced by Neighbor(), and ~Neighbor().
lastReceivedDDPacket
DdPacketId inet::ospfv2::Neighbor::lastReceivedDDPacket private
Referenced by Neighbor().
lastTransmittedDDPacket
Packet* inet::ospfv2::Neighbor::lastTransmittedDDPacket = nullptr private
Referenced by deleteLastSentDDPacket(), reset(), retransmitDatabaseDescriptionPacket(), and sendDatabaseDescriptionPacket().
linkStateRequestList
std::list<Ospfv2LsaHeader *> inet::ospfv2::Neighbor::linkStateRequestList private
Referenced by addToRequestList(), findOnRequestList(), isLSAOnRequestList(), removeFromRequestList(), reset(), and sendLinkStateRequestPacket().
linkStateRetransmissionList
std::list<Ospfv2Lsa *> inet::ospfv2::Neighbor::linkStateRetransmissionList private
Referenced by addToRetransmissionList(), findOnRetransmissionList(), isLinkStateRequestListEmpty(), removeFromRetransmissionList(), reset(), and retransmitUpdatePacket().
neighborID
RouterId inet::ospfv2::Neighbor::neighborID private
neighborIPAddress
Ipv4Address inet::ospfv2::Neighbor::neighborIPAddress private
Referenced by retransmitDatabaseDescriptionPacket(), retransmitUpdatePacket(), sendDatabaseDescriptionPacket(), and sendLinkStateRequestPacket().
neighborOptions
Ospfv2Options inet::ospfv2::Neighbor::neighborOptions private
neighborPriority
unsigned char inet::ospfv2::Neighbor::neighborPriority = 0 private
neighborsBackupDesignatedRouter
DesignatedRouterId inet::ospfv2::Neighbor::neighborsBackupDesignatedRouter private
Referenced by needAdjacency().
neighborsDesignatedRouter
DesignatedRouterId inet::ospfv2::Neighbor::neighborsDesignatedRouter private
Referenced by needAdjacency().
neighborsRouterDeadInterval
short inet::ospfv2::Neighbor::neighborsRouterDeadInterval = 0 private
parentInterface
Ospfv2Interface* inet::ospfv2::Neighbor::parentInterface = nullptr private
Referenced by clearRequestRetransmissionTimer(), clearUpdateRetransmissionTimer(), createDatabaseSummary(), needAdjacency(), reset(), retransmitDatabaseDescriptionPacket(), retransmitUpdatePacket(), sendDatabaseDescriptionPacket(), sendLinkStateRequestPacket(), startRequestRetransmissionTimer(), startUpdateRetransmissionTimer(), and ~Neighbor().
pollTimer
cMessage* inet::ospfv2::Neighbor::pollTimer = nullptr private
Referenced by Neighbor(), and ~Neighbor().
previousState
NeighborState* inet::ospfv2::Neighbor::previousState = nullptr private
Referenced by changeState(), Neighbor(), and ~Neighbor().
requestRetransmissionTimer
cMessage* inet::ospfv2::Neighbor::requestRetransmissionTimer = nullptr private
Referenced by clearRequestRetransmissionTimer(), Neighbor(), startRequestRetransmissionTimer(), and ~Neighbor().
requestRetransmissionTimerActive
bool inet::ospfv2::Neighbor::requestRetransmissionTimerActive = false private
Referenced by clearRequestRetransmissionTimer(), and startRequestRetransmissionTimer().
state
NeighborState* inet::ospfv2::Neighbor::state = nullptr private
Referenced by changeState(), getState(), Neighbor(), processEvent(), and ~Neighbor().
transmittedLSAs
std::list<TransmittedLsa> inet::ospfv2::Neighbor::transmittedLSAs private
Referenced by addToTransmittedLSAList(), ageTransmittedLSAList(), and isOnTransmittedLSAList().
updateRetransmissionTimer
cMessage* inet::ospfv2::Neighbor::updateRetransmissionTimer = nullptr private
Referenced by clearUpdateRetransmissionTimer(), Neighbor(), startUpdateRetransmissionTimer(), and ~Neighbor().
updateRetransmissionTimerActive
bool inet::ospfv2::Neighbor::updateRetransmissionTimerActive = false private
Referenced by clearUpdateRetransmissionTimer(), and startUpdateRetransmissionTimer().
The documentation for this class was generated from the following files:
Ospfv2Neighbor.h
Ospfv2Neighbor.cc