INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmModulator Class Reference
inet::physicallayer::Ieee80211OfdmModulator Class Reference
#include <Ieee80211OfdmModulator.h>
Public Member Functions
Ieee80211OfdmModulator (const Ieee80211OfdmModulation *subcarrierModulation, unsigned int polarityVectorOffset)
virtual const ITransmissionSymbolModel * modulate (const ITransmissionBitModel *bitModel) const override
const Ieee80211OfdmModulation * getModulation () const override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Attributes
static const ApskSymbol negativePilotSubcarrier
static const ApskSymbol positivePilotSubcarrier
Protected Member Functions
int getSubcarrierIndex (int ofdmSymbolIndex) const
void insertPilotSubcarriers (Ieee80211OfdmSymbol *ofdmSymbol, int symbolID) const
Protected Attributes
const Ieee80211OfdmModulation * subcarrierModulation
unsigned int pilotSubcarrierPolarityVectorOffset
Static Protected Attributes
static const double pilotSubcarrierPolarityVector [127]
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211OfdmModulator()
inet::physicallayer::Ieee80211OfdmModulator::Ieee80211OfdmModulator (const Ieee80211OfdmModulation * subcarrierModulation, unsigned int polarityVectorOffset)
                                                                                                                                      :
     subcarrierModulation(subcarrierModulation),
     pilotSubcarrierPolarityVectorOffset(polarityVectorOffset)
 {
 }
Member Function Documentation
getModulation()
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmModulator::getModulation () const inline override virtual
Implements inet::physicallayer::IModulator.
 { return subcarrierModulation; }
Referenced by inet::physicallayer::Ieee80211OfdmModulatorModule::getModulation().
getSubcarrierIndex()
int inet::physicallayer::Ieee80211OfdmModulator::getSubcarrierIndex (int ofdmSymbolIndex) const protected
 {
     // This is the translated version of the M(k) function defined in 18.3.5.10 OFDM modulation: (18-23) equation.
     // We translate it by 26 since its range is [-26,26] and we use subcarrier indices as array indices.
     if (ofdmSymbolIndex >= 0 && ofdmSymbolIndex <= 4)
         return ofdmSymbolIndex;
     else if (ofdmSymbolIndex >= 5 && ofdmSymbolIndex <= 17)
         return ofdmSymbolIndex + 1;
     else if (ofdmSymbolIndex >= 18 && ofdmSymbolIndex <= 23)
         return ofdmSymbolIndex + 2;
     else if (ofdmSymbolIndex >= 24 && ofdmSymbolIndex <= 29)
         return ofdmSymbolIndex + 3;
     else if (ofdmSymbolIndex >= 30 && ofdmSymbolIndex <= 42)
         return ofdmSymbolIndex + 4;
     else if (ofdmSymbolIndex >= 43 && ofdmSymbolIndex <= 47)
         return ofdmSymbolIndex + 5;
     else
         throw cRuntimeError("The domain of the M(k) (k = %d) function is [0,47]", ofdmSymbolIndex);
 }
Referenced by modulate().
insertPilotSubcarriers()
void inet::physicallayer::Ieee80211OfdmModulator::insertPilotSubcarriers (Ieee80211OfdmSymbol * ofdmSymbol, int symbolID) const protected
 {
     ofdmSymbol->pushApskSymbol(pilotSubcarrierPolarityVector[symbolID % 127] == 1 ? &positivePilotSubcarrier : &negativePilotSubcarrier, 5);
     ofdmSymbol->pushApskSymbol(pilotSubcarrierPolarityVector[symbolID % 127] == 1 ? &positivePilotSubcarrier : &negativePilotSubcarrier, 19);
     ofdmSymbol->pushApskSymbol(pilotSubcarrierPolarityVector[symbolID % 127] == 1 ? &positivePilotSubcarrier : &negativePilotSubcarrier, 33);
     ofdmSymbol->pushApskSymbol(pilotSubcarrierPolarityVector[symbolID % 127] == 1 ? &negativePilotSubcarrier : &positivePilotSubcarrier, 47);
 }
Referenced by modulate().
modulate()
const ITransmissionSymbolModel * inet::physicallayer::Ieee80211OfdmModulator::modulate (const ITransmissionBitModel * bitModel) const override virtual
Implements inet::physicallayer::IModulator.
 {
     std::vector<const ISymbol *> *ofdmSymbols = new std::vector<const ISymbol *>();
     const ApskModulationBase *modulationScheme = subcarrierModulation->getSubcarrierModulation();
     const BitVector *bits = bitModel->getBits();
     // Divide the resulting coded and interleaved data string into groups of N_BPSC bits.
     unsigned int nBPSC = modulationScheme->getCodeWordSize();
     ShortBitVector bitGroup;
     std::vector<const ApskSymbol *> apskSymbols;
     for (unsigned int i = 0; i < bits->getSize(); i++) {
         // For each of the bit groups, convert the bit group into a complex number according
         // to the modulation encoding tables
         bitGroup.setBit(i % nBPSC, bits->getBit(i));
         if (i % nBPSC == nBPSC - 1) {
             const ApskSymbol *apskSymbol = modulationScheme->mapToConstellationDiagram(bitGroup);
             apskSymbols.push_back(apskSymbol);
         }
     }
     // Divide the complex number string into groups of 48 complex numbers.
     // Each such group is associated with one OFDM symbol.
     for (unsigned int i = 0; i < apskSymbols.size(); i += NUMBER_OF_OFDM_DATA_SUBCARRIERS) {
         Ieee80211OfdmSymbol *ofdmSymbol = new Ieee80211OfdmSymbol();
         // In each group, the complex numbers are numbered 0 to 47 and mapped hereafter into OFDM
         // subcarriers numbered -26 to -22, -20 to -8, -6 to -1, 1 to 6, 8 to 20, and 22 to 26.
         // The 0 subcarrier, associated with center frequency, is omitted and filled with the value 0.
         for (unsigned int j = 0; j < NUMBER_OF_OFDM_DATA_SUBCARRIERS; j++) {
             int subcarrierIndex = getSubcarrierIndex(j);
             ofdmSymbol->pushApskSymbol(apskSymbols.at(j + i), subcarrierIndex);
         }
         insertPilotSubcarriers(ofdmSymbol, i / NUMBER_OF_OFDM_DATA_SUBCARRIERS + pilotSubcarrierPolarityVectorOffset);
         EV_DEBUG << "Modulated OFDM symbol: " << *ofdmSymbol << endl;
         ofdmSymbols->push_back(ofdmSymbol);
     }
     return new Ieee80211OfdmTransmissionSymbolModel(1, NaN, ofdmSymbols->size() - 1, NaN, ofdmSymbols, modulationScheme, modulationScheme);
 }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate(), and inet::physicallayer::Ieee80211OfdmModulatorModule::modulate().
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmModulator::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Ieee80211OfdmModulator";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(subcarrierModulation, printFieldToString(subcarrierModulation, level + 1, evFlags));
     return stream;
 }
Referenced by inet::physicallayer::Ieee80211OfdmModulatorModule::printToStream().
Member Data Documentation
negativePilotSubcarrier
const ApskSymbol inet::physicallayer::Ieee80211OfdmModulator::negativePilotSubcarrier static
Referenced by insertPilotSubcarriers().
pilotSubcarrierPolarityVector
const double inet::physicallayer::Ieee80211OfdmModulator::pilotSubcarrierPolarityVector static protected
Initial value:
= {
    1, 1, 1, 1, -1, -1, -1, 1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1,
    1, 1, -1, 1, 1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, 1, -1, 1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, -1, -1, 1, 1,
    -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, -1, 1, 1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, 1, 1, 1, -1, 1, -1, 1, -1, 1,
    -1, -1, -1, -1, -1, 1, -1, 1, 1, -1, 1, -1, 1, 1, 1, -1, -1, 1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1
}
Referenced by insertPilotSubcarriers().
pilotSubcarrierPolarityVectorOffset
unsigned int inet::physicallayer::Ieee80211OfdmModulator::pilotSubcarrierPolarityVectorOffset protected
Referenced by modulate().
positivePilotSubcarrier
const ApskSymbol inet::physicallayer::Ieee80211OfdmModulator::positivePilotSubcarrier static
Referenced by insertPilotSubcarriers().
subcarrierModulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmModulator::subcarrierModulation protected
Referenced by modulate(), and printToStream().
The documentation for this class was generated from the following files:
Ieee80211OfdmModulator.h
Ieee80211OfdmModulator.cc