INET Framework for OMNeT++/OMNEST: inet::tcp::DcTcp Class Reference
inet::tcp::DcTcp Class Reference
Implements DCTCP.
#include <DcTcp.h>
Public Member Functions
DcTcp ()
Constructor.
virtual void receivedDataAck (uint32_t firstSeqAcked) override
Redefine what should happen when data got acked, to add congestion window management.
virtual bool shouldMarkAck () override
Called before sending ACK.
virtual void processEcnInEstablished () override
Called before processing segment in established state.
Public Member Functions inherited from inet::tcp::TcpReno
TcpReno ()
Ctor.
virtual void receivedDuplicateAck () override
Redefine what should happen when dupAck was received, to add congestion window management.
Public Member Functions inherited from inet::tcp::TcpTahoeRenoFamily
TcpTahoeRenoFamily ()
Ctor.
void initialize () override
Create timers, etc.
Public Member Functions inherited from inet::tcp::TcpBaseAlg
TcpBaseAlg ()
Ctor.
virtual ~TcpBaseAlg ()
Virtual dtor.
virtual void established (bool active) override
Called when the connection is going to ESTABLISHED from SYN_SENT or SYN_RCVD.
virtual void connectionClosed () override
Called when the connection closes, it should cancel all running timers.
virtual void processTimer (cMessage *timer, TcpEventCode &event) override
Process REXMIT, PERSIST, DELAYED-ACK and KEEP-ALIVE timers.
virtual void sendCommandInvoked () override
Called after user sent TCP_C_SEND command to us.
virtual void receivedOutOfOrderSegment () override
Called after receiving data which are in the window, but not at its left edge (seq != rcv_nxt).
virtual void receiveSeqChanged () override
Called after rcv_nxt got advanced, either because we received in-sequence data ("text" in RFC 793 lingo) or a FIN.
virtual void receivedAckForDataNotYetSent (uint32_t seq) override
Called after we received an ACK for data not yet sent.
virtual void ackSent () override
Called after we sent an ACK.
virtual void dataSent (uint32_t fromseq) override
Called after we sent data.
virtual void segmentRetransmitted (uint32_t fromseq, uint32_t toseq) override
Called after we retransmitted segment.
virtual void restartRexmitTimer () override
Restart REXMIT timer.
Public Member Functions inherited from inet::tcp::TcpAlgorithm
TcpAlgorithm ()
Ctor.
virtual ~TcpAlgorithm ()
Virtual dtor.
void setConnection (TcpConnection *_conn)
Assign this object to a TcpConnection.
TcpStateVariables * getStateVariables ()
Creates and returns the TCP state variables.
Protected Member Functions
virtual TcpStateVariables * createStateVariables () override
Create and return a DcTcpStateVariables object.
virtual void initialize () override
Create timers, etc.
Protected Member Functions inherited from inet::tcp::TcpReno
virtual void recalculateSlowStartThreshold ()
Utility function to recalculate ssthresh.
virtual void processRexmitTimer (TcpEventCode &event) override
Redefine what should happen on retransmission.
Protected Member Functions inherited from inet::tcp::TcpBaseAlg
virtual void processPersistTimer (TcpEventCode &event)
virtual void processDelayedAckTimer (TcpEventCode &event)
virtual void processKeepAliveTimer (TcpEventCode &event)
virtual void startRexmitTimer ()
Start REXMIT timer and initialize retransmission variables.
virtual void rttMeasurementComplete (simtime_t tSent, simtime_t tAcked)
Update state vars with new measured RTT value.
virtual void rttMeasurementCompleteUsingTS (uint32_t echoedTS) override
Converting uint32_t echoedTS to simtime_t and calling rttMeasurementComplete() to update state vars with new measured RTT value.
virtual bool sendData (bool sendCommandInvoked)
Send data, observing Nagle's algorithm and congestion window.
cMessage * cancelEvent (cMessage *msg)
Utility function.
Protected Attributes
DcTcpStateVariables *& state
Protected Attributes inherited from inet::tcp::TcpReno
TcpRenoStateVariables *& state
Protected Attributes inherited from inet::tcp::TcpTahoeRenoFamily
TcpTahoeRenoFamilyStateVariables *& state
Protected Attributes inherited from inet::tcp::TcpBaseAlg
TcpBaseAlgStateVariables *& state
cMessage * rexmitTimer
cMessage * persistTimer
cMessage * delayedAckTimer
cMessage * keepAliveTimer
Protected Attributes inherited from inet::tcp::TcpAlgorithm
TcpConnection * conn
TcpStateVariables * state
Static Protected Attributes
static simsignal_t loadSignal = cComponent::registerSignal("load")
static simsignal_t calcLoadSignal = cComponent::registerSignal("calcLoad")
static simsignal_t markingProbSignal = cComponent::registerSignal("markingProb")
Static Protected Attributes inherited from inet::tcp::TcpBaseAlg
static simsignal_t cwndSignal = cComponent::registerSignal("cwnd")
static simsignal_t ssthreshSignal = cComponent::registerSignal("ssthresh")
static simsignal_t rttSignal = cComponent::registerSignal("rtt")
static simsignal_t srttSignal = cComponent::registerSignal("srtt")
static simsignal_t rttvarSignal = cComponent::registerSignal("rttvar")
static simsignal_t rtoSignal = cComponent::registerSignal("rto")
static simsignal_t numRtosSignal = cComponent::registerSignal("numRtos")
Detailed Description
Implements DCTCP.
Constructor & Destructor Documentation
DcTcp()
inet::tcp::DcTcp::DcTcp ()
Constructor.
              : TcpReno(),
     state((DcTcpStateVariables *&)TcpAlgorithm::state)
 {
 }
Member Function Documentation
createStateVariables()
virtual TcpStateVariables* inet::tcp::DcTcp::createStateVariables () inline override protected virtual
Create and return a DcTcpStateVariables object.
Reimplemented from inet::tcp::TcpReno.
     {
         return new DcTcpStateVariables();
     }
initialize()
void inet::tcp::DcTcp::initialize () override protected virtual
Create timers, etc.
Reimplemented from inet::tcp::TcpBaseAlg.
 {
     TcpReno::initialize();
     state->dctcp_gamma = conn->getTcpMain()->par("dctcpGamma");
 }
processEcnInEstablished()
void inet::tcp::DcTcp::processEcnInEstablished () override virtual
Called before processing segment in established state.
This function process ECN marks.
Reimplemented from inet::tcp::TcpBaseAlg.
 {
     if (state && state->ect) {
         // RFC 8257 3.2.1
         if (state->gotCeIndication && !state->dctcp_ce) {
             state->dctcp_ce = true;
             state->ack_now = true;
         }
         // RFC 8257 3.2.2
         if (!state->gotCeIndication && state->dctcp_ce) {
             state->dctcp_ce = false;
             state->ack_now = true;
         }
     }
 }
receivedDataAck()
void inet::tcp::DcTcp::receivedDataAck (uint32_t firstSeqAcked) override virtual
Redefine what should happen when data got acked, to add congestion window management.
Reimplemented from inet::tcp::TcpReno.
 {
     TcpTahoeRenoFamily::receivedDataAck(firstSeqAcked);
     if (state->dupacks >= state->dupthresh) {
         //
         // Perform Fast Recovery: set cwnd to ssthresh (deflating the window).
         //
         EV_INFO << "Fast Recovery: setting cwnd to ssthresh=" << state->ssthresh << "\n";
         state->snd_cwnd = state->ssthresh;
         conn->emit(cwndSignal, state->snd_cwnd);
     }
     else {
         bool performSsCa = true; // Stands for: "perform slow start and congestion avoidance"
         if (state && state->ect) {
             // RFC 8257 3.3.1
             uint32_t bytes_acked = state->snd_una - firstSeqAcked;
             // bool cut = false; TODO unused?
             // RFC 8257 3.3.2
             state->dctcp_bytesAcked += bytes_acked;
             // RFC 8257 3.3.3
             if (state->gotEce) {
                 state->dctcp_bytesMarked += bytes_acked;
                 conn->emit(markingProbSignal, 1);
             }
             else {
                 conn->emit(markingProbSignal, 0);
             }
             // RFC 8257 3.3.4
             if (state->snd_una > state->dctcp_windEnd) {
                 if (state->dctcp_bytesMarked) {
                     // cut = true;  TODO unused?
                 }
                 // RFC 8257 3.3.5
                 double ratio;
                 ratio = ((double)state->dctcp_bytesMarked / state->dctcp_bytesAcked);
                 conn->emit(loadSignal, ratio);
                 // RFC 8257 3.3.6
                 // DCTCP.Alpha = DCTCP.Alpha * (1 - g) + g * M
                 state->dctcp_alpha = state->dctcp_alpha * (1 - state->dctcp_gamma) + state->dctcp_gamma * ratio;
                 conn->emit(calcLoadSignal, state->dctcp_alpha);
                 // RFC 8257 3.3.7
                 state->dctcp_windEnd = state->snd_nxt;
                 // RFC 8257 3.3.8
                 state->dctcp_bytesAcked = state->dctcp_bytesMarked = 0;
                 state->sndCwr = false;
             }
             // Applying DcTcp style cwnd update only if there was congestion and the window has not yet been reduced during current interval
             if ((state->dctcp_bytesMarked && !state->sndCwr)) {
                 performSsCa = false;
                 state->sndCwr = true;
                 // RFC 8257 3.3.9
                 state->snd_cwnd = state->snd_cwnd * (1 - state->dctcp_alpha / 2);
                 conn->emit(cwndSignal, state->snd_cwnd);
                 uint32_t flight_size = std::min(state->snd_cwnd, state->snd_wnd); // FIXME - Does this formula computes the amount of outstanding data?
                 state->ssthresh = std::max(3 * flight_size / 4, 2 * state->snd_mss);
                 conn->emit(ssthreshSignal, state->ssthresh);
             }
         }
         if (performSsCa) {
             // If ECN is not enabled or if ECN is enabled and received multiple ECE-Acks in
             // less than RTT, then perform slow start and congestion avoidance.
             if (state->snd_cwnd < state->ssthresh) {
                 EV_INFO << "cwnd <= ssthresh: Slow Start: increasing cwnd by one SMSS bytes to ";
                 // perform Slow Start. RFC 2581: "During slow start, a TCP increments cwnd
                 // by at most SMSS bytes for each ACK received that acknowledges new data."
                 state->snd_cwnd += state->snd_mss;
                 conn->emit(cwndSignal, state->snd_cwnd);
                 conn->emit(ssthreshSignal, state->ssthresh);
                 EV_INFO << "cwnd=" << state->snd_cwnd << "\n";
             }
             else {
                 // perform Congestion Avoidance (RFC 2581)
                 uint32_t incr = state->snd_mss * state->snd_mss / state->snd_cwnd;
                 if (incr == 0)
                     incr = 1;
                 state->snd_cwnd += incr;
                 conn->emit(cwndSignal, state->snd_cwnd);
                 conn->emit(ssthreshSignal, state->ssthresh);
                 //
                 // Note: some implementations use extra additive constant mss / 8 here
                 // which is known to be incorrect (RFC 2581 p5)
                 //
                 // Note 2: RFC 3465 (experimental) "Appropriate Byte Counting" (ABC)
                 // would require maintaining a bytes_acked variable here which we don't do
                 //
                 EV_INFO << "cwnd > ssthresh: Congestion Avoidance: increasing cwnd linearly, to " << state->snd_cwnd << "\n";
             }
         }
     }
     if (state->sack_enabled && state->lossRecovery) {
         // RFC 3517, page 7: "Once a TCP is in the loss recovery phase the following procedure MUST
         // be used for each arriving ACK:
         //
         // (A) An incoming cumulative ACK for a sequence number greater than
         // RecoveryPoint signals the end of loss recovery and the loss
         // recovery phase MUST be terminated.  Any information contained in
         // the scoreboard for sequence numbers greater than the new value of
         // HighACK SHOULD NOT be cleared when leaving the loss recovery
         // phase."
         if (seqGE(state->snd_una, state->recoveryPoint)) {
             EV_INFO << "Loss Recovery terminated.\n";
             state->lossRecovery = false;
         }
         // RFC 3517, page 7: "(B) Upon receipt of an ACK that does not cover RecoveryPoint the
         // following actions MUST be taken:
         //
         // (B.1) Use Update () to record the new SACK information conveyed
         // by the incoming ACK.
         //
         // (B.2) Use SetPipe () to re-calculate the number of octets still
         // in the network."
         else {
             // update of scoreboard (B.1) has already be done in readHeaderOptions()
             conn->setPipe();
             // RFC 3517, page 7: "(C) If cwnd - pipe >= 1 SMSS the sender SHOULD transmit one or more
             // segments as follows:"
             if (((int)state->snd_cwnd - (int)state->pipe) >= (int)state->snd_mss) // Note: Typecast needed to avoid prohibited transmissions
                 conn->sendDataDuringLossRecoveryPhase(state->snd_cwnd);
         }
     }
     // RFC 3517, pages 7 and 8: "5.1 Retransmission Timeouts
     // (...)
     // If there are segments missing from the receiver's buffer following
     // processing of the retransmitted segment, the corresponding ACK will
     // contain SACK information.  In this case, a TCP sender SHOULD use this
     // SACK information when determining what data should be sent in each
     // segment of the slow start.  The exact algorithm for this selection is
     // not specified in this document (specifically NextSeg () is
     // inappropriate during slow start after an RTO).  A relatively
     // straightforward approach to "filling in" the sequence space reported
     // as missing should be a reasonable approach."
     sendData(false);
 }
shouldMarkAck()
bool inet::tcp::DcTcp::shouldMarkAck () override virtual
Called before sending ACK.
Determines whether to set ECE bit.
Reimplemented from inet::tcp::TcpBaseAlg.
 {
     // RFC 8257 3.2 page 6
     // When sending an ACK, the ECE flag MUST be set if and only if DCTCP.CE is true.
     return state->dctcp_ce;
 }
Member Data Documentation
calcLoadSignal
simsignal_t inet::tcp::DcTcp::calcLoadSignal = cComponent::registerSignal("calcLoad") static protected
Referenced by receivedDataAck().
loadSignal
simsignal_t inet::tcp::DcTcp::loadSignal = cComponent::registerSignal("load") static protected
Referenced by receivedDataAck().
markingProbSignal
simsignal_t inet::tcp::DcTcp::markingProbSignal = cComponent::registerSignal("markingProb") static protected
Referenced by receivedDataAck().
state
DcTcpStateVariables*& inet::tcp::DcTcp::state protected
Referenced by initialize(), processEcnInEstablished(), receivedDataAck(), and shouldMarkAck().
The documentation for this class was generated from the following files:
DcTcp.h
DcTcp.cc