INET Framework for OMNeT++/OMNEST: inet::LanPruneDelayOption Class Reference
inet::LanPruneDelayOption Class Reference
Class generated from inet/routing/pim/PimPacket.msg:90 by opp_msgtool.
#include <PimPacket_m.h>
Public Member Functions
LanPruneDelayOption ()
LanPruneDelayOption (const LanPruneDelayOption &other)
virtual ~LanPruneDelayOption ()
LanPruneDelayOption & operator= (const LanPruneDelayOption &other)
virtual LanPruneDelayOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getT () const
virtual void setT (bool T)
virtual uint16_t getPropagationDelay () const
virtual void setPropagationDelay (uint16_t propagationDelay)
virtual uint16_t getOverrideInterval () const
virtual void setOverrideInterval (uint16_t overrideInterval)
Public Member Functions inherited from inet::HelloOption
HelloOption ()
HelloOption (const HelloOption &other)
virtual ~HelloOption ()
HelloOption & operator= (const HelloOption &other)
virtual PimHelloOptionType getType () const
virtual void setType (PimHelloOptionType type)
Protected Member Functions
bool operator== (const LanPruneDelayOption &)=delete
Protected Member Functions inherited from inet::HelloOption
bool operator== (const HelloOption &)=delete
Protected Attributes
bool T = false
uint16_t propagationDelay = 0
uint16_t overrideInterval = 0
Protected Attributes inherited from inet::HelloOption
PimHelloOptionType type = static_cast<inet::PimHelloOptionType>(-1)
Private Member Functions
void copy (const LanPruneDelayOption &other)
Detailed Description
Class generated from inet/routing/pim/PimPacket.msg:90 by opp_msgtool.
class LanPruneDelayOption extends HelloOption
{
    type = LANPruneDelay;
    bool T = false;
    uint16_t propagationDelay;
    uint16_t overrideInterval;
}
Constructor & Destructor Documentation
LanPruneDelayOption() [1/2]
inet::LanPruneDelayOption::LanPruneDelayOption ()
LanPruneDelayOption() [2/2]
inet::LanPruneDelayOption::LanPruneDelayOption (const LanPruneDelayOption & other)
~LanPruneDelayOption()
virtual inet::LanPruneDelayOption::~LanPruneDelayOption () virtual
Member Function Documentation
copy()
void inet::LanPruneDelayOption::copy (const LanPruneDelayOption & other) private
dup()
virtual LanPruneDelayOption* inet::LanPruneDelayOption::dup () const inline override virtual
Reimplemented from inet::HelloOption.
 {return new LanPruneDelayOption(*this);}
getOverrideInterval()
virtual uint16_t inet::LanPruneDelayOption::getOverrideInterval () const virtual
Referenced by inet::PimPacketSerializer::serialize().
getPropagationDelay()
virtual uint16_t inet::LanPruneDelayOption::getPropagationDelay () const virtual
Referenced by inet::PimPacketSerializer::serialize().
getT()
virtual bool inet::LanPruneDelayOption::getT () const virtual
operator=()
LanPruneDelayOption& inet::LanPruneDelayOption::operator= (const LanPruneDelayOption & other)
operator==()
bool inet::LanPruneDelayOption::operator== (const LanPruneDelayOption &) protected delete
parsimPack()
virtual void inet::LanPruneDelayOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::LanPruneDelayOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimUnpacking().
setOverrideInterval()
virtual void inet::LanPruneDelayOption::setOverrideInterval (uint16_t overrideInterval) virtual
Referenced by inet::PimPacketSerializer::deserialize().
setPropagationDelay()
virtual void inet::LanPruneDelayOption::setPropagationDelay (uint16_t propagationDelay) virtual
Referenced by inet::PimPacketSerializer::deserialize().
setT()
virtual void inet::LanPruneDelayOption::setT (bool T) virtual
Member Data Documentation
overrideInterval
uint16_t inet::LanPruneDelayOption::overrideInterval = 0 protected
propagationDelay
uint16_t inet::LanPruneDelayOption::propagationDelay = 0 protected
T
bool inet::LanPruneDelayOption::T = false protected
The documentation for this class was generated from the following file:
PimPacket_m.h