INET Framework for OMNeT++/OMNEST: inet::queueing::IPassivePacketSink Class Reference
inet::queueing::IPassivePacketSink Class Reference abstract
This class defines the interface for passive packet sinks.
#include <IPassivePacketSink.h>
Public Member Functions
virtual ~IPassivePacketSink ()
virtual bool canPushSomePacket (cGate *gate) const =0
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const =0
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate)=0
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate)=0
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate)=0
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0))=0
Progresses pushing the packet into the packet sink at the given gate.
Detailed Description
This class defines the interface for passive packet sinks.
See the corresponding NED file for more details.
Constructor & Destructor Documentation
~IPassivePacketSink()
virtual inet::queueing::IPassivePacketSink::~IPassivePacketSink () inline virtual
 {}
Member Function Documentation
canPushPacket()
virtual bool inet::queueing::IPassivePacketSink::canPushPacket (Packet * packet, cGate * gate) const pure virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implemented in inet::NetworkInterface, inet::PacketTransmitterBase, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketQueue, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::queueing::PacketGateBase, inet::PacketStreamer, inet::queueing::PacketFlowBase, inet::queueing::CompoundPacketQueueBase, inet::InterpacketGapInserter, inet::PacketDestreamer, inet::queueing::PacketMultiplexer, inet::queueing::MarkovScheduler, inet::DscpMarker, inet::queueing::PacketPusherBase, inet::queueing::PassivePacketSink, inet::PacketMeterBase, inet::queueing::PacketCloner, inet::queueing::PacketBasedTokenGenerator, inet::queueing::PacketDuplicatorBase, inet::Resending, inet::queueing::PassivePacketSinkBase, inet::EthernetCutthroughSink, inet::SendToMacAddress, inet::queueing::PriorityClassifier, and inet::queueing::InProgressQueue.
Referenced by inet::queueing::InstantServer::canProcessPacket(), inet::EthernetCutthroughSink::canPushPacket(), inet::queueing::PacketPusherBase::canPushPacket(), inet::PacketDestreamer::canPushPacket(), inet::queueing::PacketMultiplexer::canPushPacket(), inet::InterpacketGapInserter::canPushPacket(), inet::PacketStreamer::canPushPacket(), inet::PreemptableStreamer::canPushPacket(), and inet::queueing::PcapFilePacketProducer::handleMessage().
canPushSomePacket()
virtual bool inet::queueing::IPassivePacketSink::canPushSomePacket (cGate * gate) const pure virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Implemented in inet::NetworkInterface, inet::PacketTransmitterBase, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketQueue, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::queueing::PacketGateBase, inet::PacketStreamer, inet::queueing::PacketFlowBase, inet::queueing::CompoundPacketQueueBase, inet::InterpacketGapInserter, inet::PacketDestreamer, inet::queueing::PacketMultiplexer, inet::queueing::MarkovScheduler, inet::DscpMarker, inet::queueing::PacketQueueBase, inet::queueing::PacketPusherBase, inet::queueing::PassivePacketSink, inet::PacketMeterBase, inet::queueing::PacketCloner, inet::queueing::PacketBasedTokenGenerator, inet::queueing::PacketDuplicatorBase, inet::Resending, inet::queueing::PassivePacketSinkBase, inet::StreamingTransmitterBase, inet::SendToMacAddress, inet::queueing::PriorityClassifier, and inet::queueing::InProgressQueue.
Referenced by inet::queueing::InstantServer::canProcessPacket(), inet::queueing::PacketPusherBase::canPushSomePacket(), inet::InterpacketGapInserter::canPushSomePacket(), inet::queueing::PacketMultiplexer::canPushSomePacket(), inet::PacketDestreamer::canPushSomePacket(), inet::PacketStreamer::canPushSomePacket(), inet::PreemptableStreamer::canPushSomePacket(), inet::queueing::PacketServer::canStartProcessingPacket(), inet::queueing::PreemptingServer::canStartStreaming(), inet::queueing::ActivePacketSource::handleCanPushPacketChanged(), inet::queueing::PacketMultiplexer::handleCanPushPacketChanged(), inet::queueing::ActivePacketSource::handleMessage(), and inet::queueing::ActivePacketSource::initialize().
pushPacket()
virtual void inet::queueing::IPassivePacketSink::pushPacket (Packet * packet, cGate * gate) pure virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implemented in inet::NetworkInterface, inet::MultiFieldClassifier, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketClassifierBase, inet::queueing::PacketQueue, inet::DscpMarker, inet::queueing::PacketSchedulerBase, inet::BehaviorAggregateClassifier, inet::PacketStreamer, inet::queueing::PacketFlowBase, inet::InterpacketGapInserter, inet::queueing::PacketMultiplexer, inet::queueing::CompoundPacketQueueBase, inet::PacketDestreamer, inet::queueing::MarkovScheduler, inet::VirtualTunnel, inet::SingleRateThreeColorMeter, inet::TwoRateThreeColorMeter, inet::StreamThroughTransmitter, inet::queueing::PacketPusherBase, inet::queueing::PacketCloner, inet::queueing::PassivePacketSink, inet::AggregatorBase, inet::queueing::PacketBasedTokenGenerator, inet::TokenBucketMeter, inet::PacketEmitter, inet::queueing::PacketDuplicatorBase, inet::Resending, inet::RelayInterfaceSelector, inet::queueing::PcapFilePacketConsumer, inet::FragmenterBase, inet::SendToMacAddress, inet::Ieee8021qSocketPacketProcessor, inet::Ieee8022LlcSocketPacketProcessor, inet::Forwarding, inet::StreamingTransmitter, inet::PacketTransmitter, inet::EthernetSocketPacketProcessor, inet::Reordering, inet::DuplicateRemoval, inet::StreamSplitter, inet::queueing::PacketDelayer, inet::ReceiveWithAcknowledge, inet::ReceiveWithProtocol, inet::queueing::PacketDuplicator, inet::queueing::PacketPushToSend, inet::FragmentNumberHeaderBasedDefragmenter, inet::FragmentTagBasedDefragmenter, and inet::DeaggregatorBase.
Referenced by inet::queueing::PacketQueueBase::enqueuePacket(), inet::queueing::PassivePacketSinkBase::handleMessage(), inet::PacketMeterBase::handleMessage(), inet::queueing::PacketQueueBase::handleMessage(), inet::PacketTransmitterBase::handleMessageWhenUp(), inet::queueing::PacketProcessorBase::pushOrSendPacket(), inet::queueing::CompoundPacketQueueBase::pushPacket(), and inet::queueing::PacketSchedulerBase::pushPacket().
pushPacketEnd()
virtual void inet::queueing::IPassivePacketSink::pushPacketEnd (Packet * packet, cGate * gate) pure virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implemented in inet::NetworkInterface, inet::PacketTransmitterBase, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::PacketStreamer, inet::queueing::PacketMultiplexer, inet::InterpacketGapInserter, inet::queueing::PacketFlowBase, inet::PacketDestreamer, inet::queueing::MarkovScheduler, inet::StreamThroughTransmitter, inet::DscpMarker, inet::queueing::PacketQueueBase, inet::PacketMeterBase, inet::queueing::PacketPusherBase, inet::queueing::PacketCloner, inet::EthernetCutthroughSource, inet::queueing::PacketDuplicatorBase, inet::PacketEmitter, inet::queueing::PassivePacketSinkBase, inet::EthernetCutthroughSink, and inet::EthernetCutthroughInterface.
Referenced by inet::queueing::PacketProcessorBase::pushOrSendPacketEnd(), inet::queueing::PacketProcessorBase::pushOrSendPacketProgress(), and inet::EthernetCutthroughInterface::pushPacketEnd().
pushPacketProgress()
virtual void inet::queueing::IPassivePacketSink::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) pure virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implemented in inet::NetworkInterface, inet::PacketTransmitterBase, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::PacketStreamer, inet::InterpacketGapInserter, inet::queueing::PacketFlowBase, inet::PacketDestreamer, inet::queueing::PacketMultiplexer, inet::queueing::MarkovScheduler, inet::StreamThroughTransmitter, inet::DscpMarker, inet::queueing::PacketQueueBase, inet::PacketMeterBase, inet::queueing::PacketPusherBase, inet::queueing::PacketCloner, inet::queueing::PacketDuplicatorBase, inet::queueing::PassivePacketSinkBase, and inet::PacketTransmitter.
Referenced by inet::queueing::PacketProcessorBase::pushOrSendPacketProgress().
pushPacketStart()
virtual void inet::queueing::IPassivePacketSink::pushPacketStart (Packet * packet, cGate * gate, bps datarate) pure virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implemented in inet::NetworkInterface, inet::PacketTransmitterBase, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::PacketStreamer, inet::InterpacketGapInserter, inet::queueing::PacketFlowBase, inet::queueing::PacketMultiplexer, inet::PacketDestreamer, inet::queueing::MarkovScheduler, inet::StreamThroughTransmitter, inet::DscpMarker, inet::queueing::PacketQueueBase, inet::PacketMeterBase, inet::queueing::PacketPusherBase, inet::queueing::PacketCloner, inet::EthernetCutthroughSource, inet::queueing::PacketDuplicatorBase, inet::queueing::PassivePacketSinkBase, inet::EthernetCutthroughSink, inet::physicallayer::EthernetFragmentPhyHeaderInserter, inet::EthernetCutthroughInterface, and inet::physicallayer::EthernetPhyHeaderInserter.
Referenced by inet::queueing::PacketProcessorBase::pushOrSendPacketProgress(), inet::queueing::PacketProcessorBase::pushOrSendPacketStart(), and inet::EthernetCutthroughInterface::pushPacketStart().
The documentation for this class was generated from the following file:
IPassivePacketSink.h