INET Framework for OMNeT++/OMNEST: inet::queueing::IPacketBuffer Class Reference
inet::queueing::IPacketBuffer Class Reference abstract
This class defines the interface for packet buffers.
#include <IPacketBuffer.h>
Classes
class ICallback
Public Member Functions
virtual ~IPacketBuffer ()
virtual void addPacket (Packet *packet)=0
Adds the packet to the buffer.
virtual void removePacket (Packet *packet)=0
Removes the packet from the buffer.
Public Member Functions inherited from inet::queueing::IPacketCollection
virtual int getMaxNumPackets () const =0
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const =0
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const =0
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const =0
Returns the total length of all packets in the collection in the range [0, inf).
virtual Packet * getPacket (int index) const =0
Returns the packet at the given index.
virtual bool isEmpty () const =0
Returns true if there are no packets available in the collection.
virtual void removeAllPackets ()=0
Removes all packets from the collection.
Detailed Description
This class defines the interface for packet buffers.
Constructor & Destructor Documentation
~IPacketBuffer()
virtual inet::queueing::IPacketBuffer::~IPacketBuffer () inline virtual
 {}
Member Function Documentation
addPacket()
virtual void inet::queueing::IPacketBuffer::addPacket (Packet * packet) pure virtual
Adds the packet to the buffer.
Implemented in inet::queueing::PacketBuffer.
Referenced by inet::queueing::PacketQueue::pushPacket().
removePacket()
virtual void inet::queueing::IPacketBuffer::removePacket (Packet * packet) pure virtual
Removes the packet from the buffer.
Implements inet::queueing::IPacketCollection.
Implemented in inet::queueing::PacketBuffer.
Referenced by inet::queueing::PacketQueue::pullPacket(), and inet::queueing::PacketQueue::removePacket().
The documentation for this class was generated from the following file:
IPacketBuffer.h