INET Framework for OMNeT++/OMNEST: inet::aodv::AodvRouteData Class Reference
inet::aodv::AodvRouteData Class Reference
#include <AodvRouteData.h>
Public Member Functions
AodvRouteData ()
virtual ~AodvRouteData ()
unsigned int getDestSeqNum () const
void setDestSeqNum (unsigned int destSeqNum)
bool hasValidDestNum () const
void setHasValidDestNum (bool hasValidDestNum)
bool isBeingRepaired () const
void setIsBeingRepaired (bool isBeingRepaired)
bool isRepariable () const
void setIsRepariable (bool isRepariable)
const simtime_t & getLifeTime () const
void setLifeTime (const simtime_t &lifeTime)
bool isActive () const
void setIsActive (bool active)
void addPrecursor (const L3Address &precursorAddr)
const std::set< L3Address > & getPrecursorList () const
virtual std::string str () const
Protected Attributes
std::set< L3Address > precursorList
bool active
bool repariable
bool beingRepaired
bool validDestNum
unsigned int destSeqNum
simtime_t lifeTime
Constructor & Destructor Documentation
AodvRouteData()
inet::aodv::AodvRouteData::AodvRouteData () inline
     {
         active = true;
         repariable = false;
         beingRepaired = false;
         validDestNum = true;
         lifeTime = SIMTIME_ZERO;
         destSeqNum = 0;
     }
~AodvRouteData()
virtual inet::aodv::AodvRouteData::~AodvRouteData () inline virtual
 {}
Member Function Documentation
addPrecursor()
void inet::aodv::AodvRouteData::addPrecursor (const L3Address & precursorAddr) inline
 { precursorList.insert(precursorAddr); }
Referenced by inet::aodv::Aodv::createRREP(), inet::aodv::Aodv::handleRREP(), and inet::aodv::Aodv::sendRREP().
getDestSeqNum()
unsigned int inet::aodv::AodvRouteData::getDestSeqNum () const inline
 { return destSeqNum; }
Referenced by inet::aodv::Aodv::createRREP(), inet::aodv::Aodv::createRREQ(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREQ(), inet::aodv::Aodv::sendRERRWhenNoRouteToForward(), and str().
getLifeTime()
const simtime_t& inet::aodv::AodvRouteData::getLifeTime () const inline
 { return lifeTime; }
Referenced by inet::aodv::Aodv::createGratuitousRREP(), inet::aodv::Aodv::createRREP(), inet::aodv::Aodv::expungeRoutes(), inet::aodv::Aodv::handleHelloMessage(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::scheduleExpungeRoutes(), str(), and inet::aodv::Aodv::updateValidRouteLifeTime().
getPrecursorList()
const std::set<L3Address>& inet::aodv::AodvRouteData::getPrecursorList () const inline
 { return precursorList; }
Referenced by inet::aodv::Aodv::handleRERR(), and str().
hasValidDestNum()
bool inet::aodv::AodvRouteData::hasValidDestNum () const inline
 { return validDestNum; }
Referenced by inet::aodv::Aodv::createRREQ(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREQ(), inet::aodv::Aodv::sendRERRWhenNoRouteToForward(), and str().
isActive()
bool inet::aodv::AodvRouteData::isActive () const inline
 { return active; }
Referenced by inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::aodv::Aodv::expungeRoutes(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREQ(), inet::aodv::Aodv::sendHelloMessagesIfNeeded(), str(), and inet::aodv::Aodv::updateValidRouteLifeTime().
isBeingRepaired()
bool inet::aodv::AodvRouteData::isBeingRepaired () const inline
 { return beingRepaired; }
isRepariable()
bool inet::aodv::AodvRouteData::isRepariable () const inline
 { return repariable; }
setDestSeqNum()
void inet::aodv::AodvRouteData::setDestSeqNum (unsigned int destSeqNum) inline
 { this->destSeqNum = destSeqNum; }
Referenced by inet::aodv::Aodv::createRoute(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), and inet::aodv::Aodv::updateRoutingTable().
setHasValidDestNum()
void inet::aodv::AodvRouteData::setHasValidDestNum (bool hasValidDestNum) inline
 { this->validDestNum = hasValidDestNum; }
Referenced by inet::aodv::Aodv::createRoute(), and inet::aodv::Aodv::updateRoutingTable().
setIsActive()
void inet::aodv::AodvRouteData::setIsActive (bool active) inline
 { this->active = active; }
Referenced by inet::aodv::Aodv::createRoute(), inet::aodv::Aodv::expungeRoutes(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleRREPACK(), and inet::aodv::Aodv::updateRoutingTable().
setIsBeingRepaired()
void inet::aodv::AodvRouteData::setIsBeingRepaired (bool isBeingRepaired) inline
 { this->beingRepaired = isBeingRepaired; }
setIsRepariable()
void inet::aodv::AodvRouteData::setIsRepariable (bool isRepariable) inline
 { this->repariable = isRepariable; }
setLifeTime()
void inet::aodv::AodvRouteData::setLifeTime (const simtime_t & lifeTime) inline
 { this->lifeTime = lifeTime; }
Referenced by inet::aodv::Aodv::createRoute(), inet::aodv::Aodv::datagramForwardHook(), inet::aodv::Aodv::expungeRoutes(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::updateRoutingTable(), and inet::aodv::Aodv::updateValidRouteLifeTime().
str()
std::string inet::aodv::AodvRouteData::str () const virtual
 {
     std::ostringstream out;
     out << "isActive = " << isActive()
         << ", hasValidDestNum = " << hasValidDestNum()
         << ", destNum = " << getDestSeqNum()
         << ", lifetime = " << getLifeTime();
     const std::set<L3Address>& preList = getPrecursorList();
     if (!preList.empty()) {
         out << ", precursor list: ";
         std::set<L3Address>::const_iterator iter = preList.begin();
         out << *iter;
         for (++iter; iter != preList.end(); ++iter)
             out << "; " << *iter;
     }
     return out.str();
 };
Member Data Documentation
active
bool inet::aodv::AodvRouteData::active protected
beingRepaired
bool inet::aodv::AodvRouteData::beingRepaired protected
destSeqNum
unsigned int inet::aodv::AodvRouteData::destSeqNum protected
lifeTime
simtime_t inet::aodv::AodvRouteData::lifeTime protected
precursorList
std::set<L3Address> inet::aodv::AodvRouteData::precursorList protected
repariable
bool inet::aodv::AodvRouteData::repariable protected
validDestNum
bool inet::aodv::AodvRouteData::validDestNum protected
The documentation for this class was generated from the following files:
AodvRouteData.h
AodvRouteData.cc