INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_BssDescription Class Reference
inet::ieee80211::Ieee80211Prim_BssDescription Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:106 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_BssDescription ()
Ieee80211Prim_BssDescription (const Ieee80211Prim_BssDescription &other)
virtual ~Ieee80211Prim_BssDescription ()
Ieee80211Prim_BssDescription & operator= (const Ieee80211Prim_BssDescription &other)
virtual Ieee80211Prim_BssDescription * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
virtual const ::inet::MacAddress & getBSSID () const
virtual ::inet::MacAddress & getBSSIDForUpdate ()
virtual void setBSSID (const ::inet::MacAddress &BSSID)
virtual const char * getSSID () const
virtual void setSSID (const char *SSID)
virtual const Ieee80211SupportedRatesElement & getSupportedRates () const
virtual Ieee80211SupportedRatesElement & getSupportedRatesForUpdate ()
virtual void setSupportedRates (const Ieee80211SupportedRatesElement &supportedRates)
virtual ::omnetpp::simtime_t getBeaconInterval () const
virtual void setBeaconInterval (::omnetpp::simtime_t beaconInterval)
virtual double getRxPower () const
virtual void setRxPower (double rxPower)
Protected Member Functions
bool operator== (const Ieee80211Prim_BssDescription &)=delete
Protected Attributes
int channelNumber = 0
::inet::MacAddress BSSID
::omnetpp::opp_string SSID
Ieee80211SupportedRatesElement supportedRates
::omnetpp::simtime_t beaconInterval = SIMTIME_ZERO
double rxPower = 0
Private Member Functions
void copy (const Ieee80211Prim_BssDescription &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:106 by opp_msgtool.
class Ieee80211Prim_BssDescription extends cObject
{
    int channelNumber;
    MacAddress BSSID;
    string SSID;
    Ieee80211SupportedRatesElement supportedRates;
    simtime_t beaconInterval;
    double rxPower; // received power from AP; not part of the standard
}
Constructor & Destructor Documentation
Ieee80211Prim_BssDescription() [1/2]
inet::ieee80211::Ieee80211Prim_BssDescription::Ieee80211Prim_BssDescription ()
Ieee80211Prim_BssDescription() [2/2]
inet::ieee80211::Ieee80211Prim_BssDescription::Ieee80211Prim_BssDescription (const Ieee80211Prim_BssDescription & other)
~Ieee80211Prim_BssDescription()
virtual inet::ieee80211::Ieee80211Prim_BssDescription::~Ieee80211Prim_BssDescription () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211Prim_BssDescription::copy (const Ieee80211Prim_BssDescription & other) private
dup()
virtual Ieee80211Prim_BssDescription* inet::ieee80211::Ieee80211Prim_BssDescription::dup () const inline override virtual
 {return new Ieee80211Prim_BssDescription(*this);}
getBeaconInterval()
virtual ::omnetpp::simtime_t inet::ieee80211::Ieee80211Prim_BssDescription::getBeaconInterval () const
Referenced by inet::ieee80211::Ieee80211AgentSta::dumpAPList().
getBSSID()
virtual const ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_BssDescription::getBSSID () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::dumpAPList(), and inet::ieee80211::Ieee80211AgentSta::processScanConfirm().
getBSSIDForUpdate()
virtual ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_BssDescription::getBSSIDForUpdate () inline
 { return const_cast<::inet::MacAddress&>(const_cast<Ieee80211Prim_BssDescription*>(this)->getBSSID());}
getChannelNumber()
virtual int inet::ieee80211::Ieee80211Prim_BssDescription::getChannelNumber () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::dumpAPList().
getRxPower()
virtual double inet::ieee80211::Ieee80211Prim_BssDescription::getRxPower () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::chooseBSS(), and inet::ieee80211::Ieee80211AgentSta::dumpAPList().
getSSID()
virtual const char* inet::ieee80211::Ieee80211Prim_BssDescription::getSSID () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::dumpAPList(), and inet::ieee80211::Ieee80211AgentSta::processScanConfirm().
getSupportedRates()
virtual const Ieee80211SupportedRatesElement& inet::ieee80211::Ieee80211Prim_BssDescription::getSupportedRates () const virtual
getSupportedRatesForUpdate()
virtual Ieee80211SupportedRatesElement& inet::ieee80211::Ieee80211Prim_BssDescription::getSupportedRatesForUpdate () inline virtual
 { return const_cast<Ieee80211SupportedRatesElement&>(const_cast<Ieee80211Prim_BssDescription*>(this)->getSupportedRates());}
operator=()
Ieee80211Prim_BssDescription& inet::ieee80211::Ieee80211Prim_BssDescription::operator= (const Ieee80211Prim_BssDescription & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_BssDescription::operator== (const Ieee80211Prim_BssDescription &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::ieee80211::doParsimUnpacking().
setBeaconInterval()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::setBeaconInterval (::omnetpp::simtime_t beaconInterval) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
setBSSID()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::setBSSID (const ::inet::MacAddress & BSSID) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
setChannelNumber()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::setChannelNumber (int channelNumber) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
setRxPower()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::setRxPower (double rxPower) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
setSSID()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::setSSID (const char * SSID) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
setSupportedRates()
virtual void inet::ieee80211::Ieee80211Prim_BssDescription::setSupportedRates (const Ieee80211SupportedRatesElement & supportedRates) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendScanConfirm().
Member Data Documentation
beaconInterval
::omnetpp::simtime_t inet::ieee80211::Ieee80211Prim_BssDescription::beaconInterval = SIMTIME_ZERO protected
BSSID
::inet::MacAddress inet::ieee80211::Ieee80211Prim_BssDescription::BSSID protected
channelNumber
int inet::ieee80211::Ieee80211Prim_BssDescription::channelNumber = 0 protected
rxPower
double inet::ieee80211::Ieee80211Prim_BssDescription::rxPower = 0 protected
SSID
::omnetpp::opp_string inet::ieee80211::Ieee80211Prim_BssDescription::SSID protected
supportedRates
Ieee80211SupportedRatesElement inet::ieee80211::Ieee80211Prim_BssDescription::supportedRates protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h