INET Framework for OMNeT++/OMNEST: inet::power::IEpEnergySink Class Reference
inet::power::IEpEnergySink Class Reference abstract
TODO.
#include <IEpEnergySink.h>
Public Member Functions
virtual W getTotalPowerGeneration () const =0
Returns the total power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
virtual int getNumEnergyGenerators () const =0
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const =0
Returns the energy generator for the provided index.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator)=0
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator)=0
Removes a previously added energy generator from this energy sink.
Static Public Attributes
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Detailed Description
TODO.
See the corresponding NED file for more details.
Member Function Documentation
getTotalPowerGeneration()
virtual W inet::power::IEpEnergySink::getTotalPowerGeneration () const pure virtual
Returns the total power generation in the range [0, +infinity).
Implemented in inet::power::EpEnergySinkBase.
Referenced by inet::power::SimpleEpEnergyManagement::scheduleLifecycleOperationTimer().
Member Data Documentation
powerGenerationChangedSignal
simsignal_t inet::power::IEpEnergySink::powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged") static
The signal that is used to publish power generation changes.
Referenced by inet::power::SimpleEpEnergyManagement::initialize(), inet::power::SimpleEpEnergyManagement::receiveSignal(), inet::power::AlternatingEpEnergyGenerator::updatePowerGeneration(), and inet::power::EpEnergyStorageBase::updateTotalPowerGeneration().
The documentation for this class was generated from the following files:
IEpEnergySink.h
IEpEnergySink.cc