INET Framework for OMNeT++/OMNEST: inet::ProtocolGroup Class Reference
inet::ProtocolGroup Class Reference
#include <ProtocolGroup.h>
Public Member Functions
ProtocolGroup (const char *name, std::map< int, const Protocol * > protocolNumberToProtocol)
const char * getName () const
int getNumElements () const
const Protocol * getElement (int index) const
const Protocol * findProtocol (int protocolNumber) const
const Protocol * getProtocol (int protocolNumber) const
int findProtocolNumber (const Protocol *protocol) const
int getProtocolNumber (const Protocol *protocol) const
void addProtocol (int protocolId, const Protocol *protocol)
std::string str () const
Static Public Attributes
static ProtocolGroup ethertype
static ProtocolGroup ieee8022protocol
static ProtocolGroup ipprotocol
static ProtocolGroup pppprotocol
static ProtocolGroup snapOui
static ProtocolGroup tcpprotocol
static ProtocolGroup udpprotocol
Protected Attributes
const char * name
std::vector< const Protocol * > protocols
std::map< int, const Protocol * > protocolNumberToProtocol
std::map< const Protocol *, int > protocolToProtocolNumber
Constructor & Destructor Documentation
ProtocolGroup()
inet::ProtocolGroup::ProtocolGroup (const char * name, std::map< int, const Protocol * > protocolNumberToProtocol)
                                                                                                      :
     name(name),
     protocolNumberToProtocol(protocolNumberToProtocol)
 {
     for (auto it : protocolNumberToProtocol) {
         protocols.push_back(it.second);
         protocolToProtocolNumber[it.second] = it.first;
     }
 }
Member Function Documentation
addProtocol()
void inet::ProtocolGroup::addProtocol (int protocolId, const Protocol * protocol)
 {
     protocols.push_back(protocol);
     protocolNumberToProtocol[protocolId] = protocol;
     protocolToProtocolNumber[protocol] = protocolId;
 }
Referenced by inet::IpvxTrafSink::initialize(), and inet::IpvxTrafGen::initialize().
findProtocol()
const Protocol * inet::ProtocolGroup::findProtocol (int protocolNumber) const
 {
     auto it = protocolNumberToProtocol.find(protocolNumber);
     return it != protocolNumberToProtocol.end() ? it->second : nullptr;
 }
Referenced by inet::ieee80211::Ieee80211LlcEpd::decapsulate(), inet::Ieee802EpdProtocolDissector::dissect(), inet::BMacProtocolDissector::dissect(), inet::TcpProtocolDissector::dissect(), inet::UdpProtocolDissector::dissect(), inet::XMacProtocolDissector::dissect(), inet::AckingMacProtocolDissector::dissect(), inet::Ieee802154ProtocolDissector::dissect(), inet::CsmaCaMacProtocolDissector::dissect(), inet::EthernetMacProtocolDissector::dissect(), inet::LMacProtocolDissector::dissect(), inet::PppProtocolDissector::dissect(), inet::physicallayer::Ieee8021qTagEpdProtocolDissector::dissect(), inet::physicallayer::Ieee8021rTagEpdProtocolDissector::dissect(), inet::Ieee8022LlcInserter::getProtocol(), inet::Ieee8022SnapInserter::getProtocol(), inet::Ieee8022LlcChecker::getProtocol(), inet::Ieee8022SnapChecker::getProtocol(), getProtocol(), inet::Ieee8022Llc::getProtocol(), inet::ieee80211::LlcProtocolTag::getProtocol(), inet::FloodingHeader::getProtocol(), inet::ProbabilisticBroadcastHeader::getProtocol(), inet::NextHopForwardingHeader::getProtocol(), inet::WiseRouteHeader::getProtocol(), inet::Ipv6Header::getProtocol(), inet::Ipv4Header::getProtocol(), inet::IpvxTrafSink::initialize(), inet::IpvxTrafGen::initialize(), inet::EthernetTypeOrLengthChecker::matchesPacket(), inet::Ieee8021aeTagEpdHeaderChecker::matchesPacket(), inet::Ieee8021rTagEpdHeaderChecker::matchesPacket(), inet::EthernetMacHeaderChecker::matchesPacket(), inet::Ieee8021qTagEpdHeaderChecker::matchesPacket(), and inet::EthernetEncapsulation::processPacketFromMac().
findProtocolNumber()
int inet::ProtocolGroup::findProtocolNumber (const Protocol * protocol) const
 {
     auto it = protocolToProtocolNumber.find(protocol);
     return it != protocolToProtocolNumber.end() ? it->second : -1;
 }
Referenced by inet::ieee80211::Ieee80211LlcEpd::encapsulate(), inet::Ieee8022Llc::encapsulate(), getProtocolNumber(), inet::Icmp::handleRegisterProtocol(), inet::Icmpv6::handleRegisterProtocol(), inet::Ieee8022LlcInserter::processPacket(), and inet::Ieee8022SnapInserter::processPacket().
getElement()
const Protocol* inet::ProtocolGroup::getElement (int index) const inline
 { return protocols.at(index); }
getName()
const char* inet::ProtocolGroup::getName () const inline
 { return name; }
getNumElements()
int inet::ProtocolGroup::getNumElements () const inline
 { return protocols.size(); }
getProtocol()
const Protocol * inet::ProtocolGroup::getProtocol (int protocolNumber) const
 {
     auto protocol = findProtocol(protocolNumber);
     if (protocol != nullptr)
         return protocol;
     else
         throw cRuntimeError("Unknown protocol: number = %d", protocolNumber);
 }
Referenced by inet::Ipv4Encap::decapsulate(), inet::AckingMac::decapsulate(), inet::Ppp::decapsulate(), inet::LMac::decapsulate(), inet::CsmaCaMac::decapsulate(), inet::Ipv4::decapsulate(), inet::BMac::decapsulate(), inet::XMac::decapsulate(), inet::Ieee802154Mac::decapsulate(), inet::queueing::EcnMarker::getEcn(), inet::DscpMarker::markPacket(), inet::EthernetTypeOrLengthChecker::processPacket(), inet::Ieee8021aeTagEpdHeaderChecker::processPacket(), inet::Ieee8021rTagEpdHeaderChecker::processPacket(), inet::EthernetMacHeaderChecker::processPacket(), inet::Ieee8021qTagEpdHeaderChecker::processPacket(), and inet::queueing::EcnMarker::setEcn().
getProtocolNumber()
int inet::ProtocolGroup::getProtocolNumber (const Protocol * protocol) const
 {
     auto protocolNumber = findProtocolNumber(protocol);
     if (protocolNumber != -1)
         return protocolNumber;
     else
         throw cRuntimeError("Unknown protocol: id = %d, name = %s", protocol->getId(), protocol->getName());
 }
Referenced by inet::Ipv4Encap::encapsulate(), inet::Ipv4::encapsulate(), inet::CsmaCaMac::encapsulate(), inet::IpvxTrafSink::printPacket(), inet::IpvxTrafGen::printPacket(), and inet::EthernetEncapsulation::processPacketFromHigherLayer().
str()
std::string inet::ProtocolGroup::str () const inline
 { return name; }
Referenced by inet::operator<<().
Member Data Documentation
ethertype
ProtocolGroup inet::ProtocolGroup::ethertype static
Referenced by inet::ieee80211::Ieee80211LlcEpd::decapsulate(), inet::AckingMac::decapsulate(), inet::LMac::decapsulate(), inet::CsmaCaMac::decapsulate(), inet::BMac::decapsulate(), inet::XMac::decapsulate(), inet::Ieee802154Mac::decapsulate(), inet::Ieee802EpdProtocolDissector::dissect(), inet::CsmaCaMacProtocolDissector::dissect(), inet::EthernetMacProtocolDissector::dissect(), inet::LMacProtocolDissector::dissect(), inet::AckingMacProtocolDissector::dissect(), inet::BMacProtocolDissector::dissect(), inet::XMacProtocolDissector::dissect(), inet::Ieee802154ProtocolDissector::dissect(), inet::physicallayer::Ieee8021qTagEpdProtocolDissector::dissect(), inet::physicallayer::Ieee8021rTagEpdProtocolDissector::dissect(), inet::ieee80211::Ieee80211LlcEpd::encapsulate(), inet::Ieee8022Llc::encapsulate(), inet::AckingMac::encapsulate(), inet::LMac::encapsulate(), inet::CsmaCaMac::encapsulate(), inet::BMac::encapsulate(), inet::XMac::encapsulate(), inet::Ieee802154Mac::encapsulate(), inet::queueing::EcnMarker::getEcn(), inet::Ieee8022SnapInserter::getProtocol(), inet::Ieee8022SnapChecker::getProtocol(), inet::Ieee8022Llc::getProtocol(), inet::DscpMarker::markPacket(), inet::EthernetTypeOrLengthChecker::matchesPacket(), inet::Ieee8021aeTagEpdHeaderChecker::matchesPacket(), inet::Ieee8021rTagEpdHeaderChecker::matchesPacket(), inet::EthernetMacHeaderChecker::matchesPacket(), inet::Ieee8021qTagEpdHeaderChecker::matchesPacket(), inet::Ieee8021aeTagEpdHeaderChecker::processPacket(), inet::EthernetTypeOrLengthChecker::processPacket(), inet::EthernetTypeOrLengthInserter::processPacket(), inet::Ieee8021aeTagEpdHeaderInserter::processPacket(), inet::Ieee8022SnapInserter::processPacket(), inet::Ieee8021rTagEpdHeaderChecker::processPacket(), inet::Ieee8021rTagEpdHeaderInserter::processPacket(), inet::EthernetMacHeaderInserter::processPacket(), inet::EthernetMacHeaderChecker::processPacket(), inet::Ieee8021qTagEpdHeaderChecker::processPacket(), inet::Ieee8021qTagEpdHeaderInserter::processPacket(), inet::EthernetEncapsulation::processPacketFromHigherLayer(), inet::EthernetEncapsulation::processPacketFromMac(), and inet::queueing::EcnMarker::setEcn().
ieee8022protocol
ProtocolGroup inet::ProtocolGroup::ieee8022protocol static
Referenced by inet::Ieee8022Llc::encapsulate(), inet::Ieee8022LlcInserter::getProtocol(), inet::Ieee8022LlcChecker::getProtocol(), inet::Ieee8022Llc::getProtocol(), and inet::Ieee8022LlcInserter::processPacket().
ipprotocol
ProtocolGroup inet::ProtocolGroup::ipprotocol static
Referenced by inet::Ipv4Encap::decapsulate(), inet::Ipv4::decapsulate(), inet::Ipv4Encap::encapsulate(), inet::Ipv6::encapsulate(), inet::Ipv4::encapsulate(), inet::FloodingHeader::getProtocol(), inet::ProbabilisticBroadcastHeader::getProtocol(), inet::NextHopForwardingHeader::getProtocol(), inet::WiseRouteHeader::getProtocol(), inet::Ipv6Header::getProtocol(), inet::Ipv4Header::getProtocol(), inet::Icmp::handleRegisterProtocol(), inet::Icmpv6::handleRegisterProtocol(), inet::IpvxTrafSink::initialize(), inet::IpvxTrafGen::initialize(), inet::IpvxTrafSink::printPacket(), inet::IpvxTrafGen::printPacket(), inet::Icmp::processIcmpMessage(), inet::Icmpv6::processICMPv6Message(), inet::FloodingHeader::setProtocol(), inet::ProbabilisticBroadcastHeader::setProtocol(), inet::NextHopForwardingHeader::setProtocol(), inet::WiseRouteHeader::setProtocol(), inet::Ipv6Header::setProtocol(), and inet::Ipv4Header::setProtocol().
name
const char* inet::ProtocolGroup::name protected
pppprotocol
ProtocolGroup inet::ProtocolGroup::pppprotocol static
Referenced by inet::Ppp::decapsulate(), inet::PppProtocolDissector::dissect(), and inet::Ppp::encapsulate().
protocolNumberToProtocol
std::map<int, const Protocol *> inet::ProtocolGroup::protocolNumberToProtocol protected
Referenced by addProtocol(), findProtocol(), and ProtocolGroup().
protocols
std::vector<const Protocol *> inet::ProtocolGroup::protocols protected
Referenced by addProtocol(), and ProtocolGroup().
protocolToProtocolNumber
std::map<const Protocol *, int> inet::ProtocolGroup::protocolToProtocolNumber protected
Referenced by addProtocol(), findProtocolNumber(), and ProtocolGroup().
snapOui
ProtocolGroup inet::ProtocolGroup::snapOui static
Referenced by inet::Ieee8022Llc::encapsulate(), inet::Ieee8022SnapInserter::getProtocol(), inet::Ieee8022SnapChecker::getProtocol(), inet::Ieee8022Llc::getProtocol(), and inet::Ieee8022SnapInserter::processPacket().
tcpprotocol
ProtocolGroup inet::ProtocolGroup::tcpprotocol static
Referenced by inet::TcpProtocolDissector::dissect().
udpprotocol
ProtocolGroup inet::ProtocolGroup::udpprotocol static
Referenced by inet::UdpProtocolDissector::dissect().
The documentation for this class was generated from the following files:
ProtocolGroup.h
ProtocolGroup.cc