INET Framework for OMNeT++/OMNEST: inet::IArp Class Reference
inet::IArp Class Reference abstract
Represents an Ipv4 ARP module.
#include <IArp.h>
Classes
class Notification
Sent in ARP cache change notification signals.
Public Member Functions
virtual ~IArp ()
virtual L3Address getL3AddressFor (const MacAddress &) const =0
Returns the Layer 3 address for the given MAC address.
virtual MacAddress resolveL3Address (const L3Address &address, const NetworkInterface *ie)=0
Tries to resolve the given network address to a MAC address.
Static Public Attributes
static const simsignal_t arpResolutionInitiatedSignal = cComponent::registerSignal("arpResolutionInitiated")
Signals used to publish ARP state changes.
static const simsignal_t arpResolutionCompletedSignal = cComponent::registerSignal("arpResolutionCompleted")
static const simsignal_t arpResolutionFailedSignal = cComponent::registerSignal("arpResolutionFailed")
Detailed Description
Represents an Ipv4 ARP module.
Constructor & Destructor Documentation
~IArp()
virtual inet::IArp::~IArp () inline virtual
 {}
Member Function Documentation
getL3AddressFor()
virtual L3Address inet::IArp::getL3AddressFor (const MacAddress &) const pure virtual
Returns the Layer 3 address for the given MAC address.
If it is not available (not in the cache, pending resolution, or already expired), UNSPECIFIED_ADDRESS is returned.
Implemented in inet::Arp, and inet::GlobalArp.
resolveL3Address()
virtual MacAddress inet::IArp::resolveL3Address (const L3Address & address, const NetworkInterface * ie) pure virtual
Tries to resolve the given network address to a MAC address.
If the MAC address is not yet resolved it returns an unspecified address and starts an address resolution procedure. A signal is emitted when the address resolution procedure terminates.
Implemented in inet::GlobalArp, and inet::Arp.
Member Data Documentation
arpResolutionCompletedSignal
const simsignal_t inet::IArp::arpResolutionCompletedSignal = cComponent::registerSignal("arpResolutionCompleted") static
Referenced by inet::Ipv4::initialize(), inet::Ipv4::receiveSignal(), and inet::Arp::updateArpCache().
arpResolutionFailedSignal
const simsignal_t inet::IArp::arpResolutionFailedSignal = cComponent::registerSignal("arpResolutionFailed") static
Referenced by inet::Ipv4::initialize(), inet::Ipv4::receiveSignal(), and inet::Arp::requestTimedOut().
arpResolutionInitiatedSignal
const simsignal_t inet::IArp::arpResolutionInitiatedSignal = cComponent::registerSignal("arpResolutionInitiated") static
Signals used to publish ARP state changes.
Referenced by inet::Arp::initiateArpResolution().
The documentation for this class was generated from the following files:
IArp.h
IArp.cc