INET Framework for OMNeT++/OMNEST: inet::SignalTimeInd Class Reference
inet::SignalTimeInd Class Reference
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/SignalTag.msg:126 by opp_msgtool.
#include <SignalTag_m.h>
Public Member Functions
SignalTimeInd ()
SignalTimeInd (const SignalTimeInd &other)
virtual ~SignalTimeInd ()
SignalTimeInd & operator= (const SignalTimeInd &other)
virtual SignalTimeInd * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual ::omnetpp::simtime_t getStartTime () const
virtual void setStartTime (::omnetpp::simtime_t startTime)
virtual ::omnetpp::simtime_t getEndTime () const
virtual void setEndTime (::omnetpp::simtime_t endTime)
Public Member Functions inherited from inet::SignalTagBase
SignalTagBase ()
SignalTagBase (const SignalTagBase &other)
virtual ~SignalTagBase ()
SignalTagBase & operator= (const SignalTagBase &other)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SignalTimeInd &)=delete
Protected Member Functions inherited from inet::SignalTagBase
bool operator== (const SignalTagBase &)=delete
Protected Attributes
::omnetpp::simtime_t startTime = SIMTIME_ZERO
::omnetpp::simtime_t endTime = SIMTIME_ZERO
Private Member Functions
void copy (const SignalTimeInd &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/SignalTag.msg:126 by opp_msgtool.
//
// This indication specifies the timing of the received signal.
// It may be present on a packet from the phyiscal layer to the application.
//
class SignalTimeInd extends SignalTagBase
{
    simtime_t startTime;
    simtime_t endTime;
}
Constructor & Destructor Documentation
SignalTimeInd() [1/2]
inet::SignalTimeInd::SignalTimeInd ()
SignalTimeInd() [2/2]
inet::SignalTimeInd::SignalTimeInd (const SignalTimeInd & other)
~SignalTimeInd()
virtual inet::SignalTimeInd::~SignalTimeInd () virtual
Member Function Documentation
copy()
void inet::SignalTimeInd::copy (const SignalTimeInd & other) private
dup()
virtual SignalTimeInd* inet::SignalTimeInd::dup () const inline override virtual
Reimplemented from inet::SignalTagBase.
 {return new SignalTimeInd(*this);}
getEndTime()
virtual ::omnetpp::simtime_t inet::SignalTimeInd::getEndTime () const
getStartTime()
virtual ::omnetpp::simtime_t inet::SignalTimeInd::getStartTime () const
operator=()
SignalTimeInd& inet::SignalTimeInd::operator= (const SignalTimeInd & other)
operator==()
bool inet::SignalTimeInd::operator== (const SignalTimeInd &) protected delete
parsimPack()
virtual void inet::SignalTimeInd::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignalTagBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SignalTimeInd::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignalTagBase.
Referenced by inet::doParsimUnpacking().
setEndTime()
virtual void inet::SignalTimeInd::setEndTime (::omnetpp::simtime_t endTime) virtual
setStartTime()
virtual void inet::SignalTimeInd::setStartTime (::omnetpp::simtime_t startTime) virtual
Referenced by inet::physicallayer::ReceiverBase::computeReceptionResult().
Member Data Documentation
endTime
::omnetpp::simtime_t inet::SignalTimeInd::endTime = SIMTIME_ZERO protected
startTime
::omnetpp::simtime_t inet::SignalTimeInd::startTime = SIMTIME_ZERO protected
The documentation for this class was generated from the following file:
SignalTag_m.h