INET Framework for OMNeT++/OMNEST: inet::GptpIngressTimeInd Class Reference
inet::GptpIngressTimeInd Class Reference
Class generated from inet/linklayer/ieee8021as/GptpPacket.msg:248 by opp_msgtool.
#include <GptpPacket_m.h>
Public Member Functions
GptpIngressTimeInd ()
GptpIngressTimeInd (const GptpIngressTimeInd &other)
virtual ~GptpIngressTimeInd ()
GptpIngressTimeInd & operator= (const GptpIngressTimeInd &other)
virtual GptpIngressTimeInd * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual clocktime_t getArrivalClockTime () const
virtual void setArrivalClockTime (clocktime_t arrivalClockTime)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const GptpIngressTimeInd &)=delete
Protected Attributes
clocktime_t arrivalClockTime = CLOCKTIME_ZERO
Private Member Functions
void copy (const GptpIngressTimeInd &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/ieee8021as/GptpPacket.msg:248 by opp_msgtool.
class GptpIngressTimeInd extends TagBase
{
    clocktime_t arrivalClockTime;
}
Constructor & Destructor Documentation
GptpIngressTimeInd() [1/2]
inet::GptpIngressTimeInd::GptpIngressTimeInd ()
GptpIngressTimeInd() [2/2]
inet::GptpIngressTimeInd::GptpIngressTimeInd (const GptpIngressTimeInd & other)
~GptpIngressTimeInd()
virtual inet::GptpIngressTimeInd::~GptpIngressTimeInd () virtual
Member Function Documentation
copy()
void inet::GptpIngressTimeInd::copy (const GptpIngressTimeInd & other) private
dup()
virtual GptpIngressTimeInd* inet::GptpIngressTimeInd::dup () const inline override virtual
 {return new GptpIngressTimeInd(*this);}
getArrivalClockTime()
virtual clocktime_t inet::GptpIngressTimeInd::getArrivalClockTime () const virtual
Referenced by inet::Gptp::processPdelayReq().
operator=()
GptpIngressTimeInd& inet::GptpIngressTimeInd::operator= (const GptpIngressTimeInd & other)
operator==()
bool inet::GptpIngressTimeInd::operator== (const GptpIngressTimeInd &) protected delete
parsimPack()
virtual void inet::GptpIngressTimeInd::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::GptpIngressTimeInd::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setArrivalClockTime()
virtual void inet::GptpIngressTimeInd::setArrivalClockTime (clocktime_t arrivalClockTime) virtual
Referenced by inet::Gptp::receiveSignal().
Member Data Documentation
arrivalClockTime
clocktime_t inet::GptpIngressTimeInd::arrivalClockTime = CLOCKTIME_ZERO protected
The documentation for this class was generated from the following file:
GptpPacket_m.h