INET Framework for OMNeT++/OMNEST: inet::tcp::SackItem Class Reference
inet::tcp::SackItem Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:80 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
SackItem ()
SackItem (const SackItem &other)
virtual ~SackItem ()
SackItem & operator= (const SackItem &other)
virtual SackItem * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned int getStart () const
virtual void setStart (unsigned int start)
virtual unsigned int getEnd () const
virtual void setEnd (unsigned int end)
Protected Member Functions
bool operator== (const SackItem &)=delete
Protected Attributes
unsigned int start = 0
unsigned int end = 0
Private Member Functions
void copy (const SackItem &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:80 by opp_msgtool.
//
// This structure represents a single SACK (selective acknowledgment):
//
class SackItem extends cObject
{
    @packetData;
    unsigned int start;     // start seq no. of sack block
    unsigned int end;       // end seq no. of sack block
}
Constructor & Destructor Documentation
SackItem() [1/2]
inet::tcp::SackItem::SackItem ()
SackItem() [2/2]
inet::tcp::SackItem::SackItem (const SackItem & other)
~SackItem()
virtual inet::tcp::SackItem::~SackItem () virtual
Member Function Documentation
copy()
void inet::tcp::SackItem::copy (const SackItem & other) private
dup()
virtual SackItem* inet::tcp::SackItem::dup () const inline override virtual
Reimplemented in inet::tcp::Sack.
 {return new SackItem(*this);}
getEnd()
virtual unsigned int inet::tcp::SackItem::getEnd () const virtual
Referenced by inet::tcp::TcpConnection::addSacks(), inet::tcp::TcpConnection::processSACKOption(), and inet::tcp::TcpHeaderSerializer::serializeOption().
getStart()
virtual unsigned int inet::tcp::SackItem::getStart () const virtual
Referenced by inet::tcp::TcpConnection::addSacks(), inet::tcp::TcpConnection::processSACKOption(), and inet::tcp::TcpHeaderSerializer::serializeOption().
operator=()
SackItem& inet::tcp::SackItem::operator= (const SackItem & other)
operator==()
bool inet::tcp::SackItem::operator== (const SackItem &) protected delete
parsimPack()
virtual void inet::tcp::SackItem::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::tcp::Sack.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::SackItem::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::tcp::Sack.
Referenced by inet::tcp::doParsimUnpacking().
setEnd()
virtual void inet::tcp::SackItem::setEnd (unsigned int end) virtual
Referenced by inet::tcp::TcpHeaderSerializer::deserializeOption(), inet::tcp::TcpConnection::processSACKOption(), and inet::tcp::Sack::setSegment().
setStart()
virtual void inet::tcp::SackItem::setStart (unsigned int start) virtual
Referenced by inet::tcp::TcpHeaderSerializer::deserializeOption(), inet::tcp::TcpConnection::processSACKOption(), and inet::tcp::Sack::setSegment().
Member Data Documentation
end
unsigned int inet::tcp::SackItem::end = 0 protected
Referenced by inet::tcp::Sack::clear(), inet::tcp::Sack::contains(), inet::tcp::Sack::empty(), and inet::tcp::Sack::str().
start
unsigned int inet::tcp::SackItem::start = 0 protected
Referenced by inet::tcp::Sack::clear(), inet::tcp::Sack::contains(), inet::tcp::Sack::empty(), and inet::tcp::Sack::str().
The documentation for this class was generated from the following file:
TcpHeader_m.h