INET Framework for OMNeT++/OMNEST: inet::TlvOptionRaw Class Reference
inet::TlvOptionRaw Class Reference
Class generated from inet/common/TlvOptions.msg:19 by opp_msgtool.
#include <TlvOptions_m.h>
Public Member Functions
TlvOptionRaw ()
TlvOptionRaw (const TlvOptionRaw &other)
virtual ~TlvOptionRaw ()
TlvOptionRaw & operator= (const TlvOptionRaw &other)
virtual TlvOptionRaw * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setBytesArraySize (size_t size)
virtual size_t getBytesArraySize () const
virtual char getBytes (size_t k) const
virtual void setBytes (size_t k, char bytes)
virtual void insertBytes (size_t k, char bytes)
void insertBytes (char bytes)
virtual void appendBytes (char bytes)
virtual void eraseBytes (size_t k)
Public Member Functions inherited from inet::TlvOptionBase
TlvOptionBase ()
TlvOptionBase (const TlvOptionBase &other)
virtual ~TlvOptionBase ()
TlvOptionBase & operator= (const TlvOptionBase &other)
virtual short getType () const
virtual void setType (short type)
virtual short getLength () const
virtual void setLength (short length)
Protected Member Functions
bool operator== (const TlvOptionRaw &)=delete
Protected Member Functions inherited from inet::TlvOptionBase
bool operator== (const TlvOptionBase &)=delete
Protected Attributes
char * bytes = nullptr
size_t bytes_arraysize = 0
Protected Attributes inherited from inet::TlvOptionBase
short type = -1
short length = 0
Private Member Functions
void copy (const TlvOptionRaw &other)
Detailed Description
Class generated from inet/common/TlvOptions.msg:19 by opp_msgtool.
class TlvOptionRaw extends TlvOptionBase
{
    char bytes[];
}
Constructor & Destructor Documentation
TlvOptionRaw() [1/2]
inet::TlvOptionRaw::TlvOptionRaw ()
TlvOptionRaw() [2/2]
inet::TlvOptionRaw::TlvOptionRaw (const TlvOptionRaw & other)
~TlvOptionRaw()
virtual inet::TlvOptionRaw::~TlvOptionRaw () virtual
Member Function Documentation
appendBytes()
virtual void inet::TlvOptionRaw::appendBytes (char bytes) virtual
copy()
void inet::TlvOptionRaw::copy (const TlvOptionRaw & other) private
dup()
virtual TlvOptionRaw* inet::TlvOptionRaw::dup () const inline override virtual
Reimplemented from inet::TlvOptionBase.
 {return new TlvOptionRaw(*this);}
eraseBytes()
virtual void inet::TlvOptionRaw::eraseBytes (size_t k) virtual
getBytes()
virtual char inet::TlvOptionRaw::getBytes (size_t k) const virtual
getBytesArraySize()
virtual size_t inet::TlvOptionRaw::getBytesArraySize () const virtual
Referenced by inet::Ipv4HeaderSerializer::serializeOption().
insertBytes() [1/2]
void inet::TlvOptionRaw::insertBytes (char bytes) inline
 {appendBytes(bytes);}
insertBytes() [2/2]
virtual void inet::TlvOptionRaw::insertBytes (size_t k, char bytes) virtual
operator=()
TlvOptionRaw& inet::TlvOptionRaw::operator= (const TlvOptionRaw & other)
operator==()
bool inet::TlvOptionRaw::operator== (const TlvOptionRaw &) protected delete
parsimPack()
virtual void inet::TlvOptionRaw::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::TlvOptionBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TlvOptionRaw::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::TlvOptionBase.
Referenced by inet::doParsimUnpacking().
setBytes()
virtual void inet::TlvOptionRaw::setBytes (size_t k, char bytes) virtual
setBytesArraySize()
virtual void inet::TlvOptionRaw::setBytesArraySize (size_t size) virtual
Member Data Documentation
bytes
char* inet::TlvOptionRaw::bytes = nullptr protected
bytes_arraysize
size_t inet::TlvOptionRaw::bytes_arraysize = 0 protected
The documentation for this class was generated from the following file:
TlvOptions_m.h