INET Framework for OMNeT++/OMNEST: inet::physicallayer::BandListening Class Reference
inet::physicallayer::BandListening Class Reference
#include <BandListening.h>
Public Member Functions
BandListening (const IRadio *radio, simtime_t startTime, simtime_t endTime, Coord startPosition, Coord endPosition, Hz centerFrequency, Hz bandwidth)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual Hz getCenterFrequency () const
virtual Hz getBandwidth () const
Public Member Functions inherited from inet::physicallayer::ListeningBase
ListeningBase (const IRadio *receiver, simtime_t startTime, simtime_t endTime, Coord startPosition, Coord endPosition)
virtual const IRadio * getReceiver () const override
virtual const simtime_t getStartTime () const override
virtual const simtime_t getEndTime () const override
virtual const Coord & getStartPosition () const override
virtual const Coord & getEndPosition () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const Hz centerFrequency
const Hz bandwidth
Protected Attributes inherited from inet::physicallayer::ListeningBase
const IRadio * receiver
const simtime_t startTime
const simtime_t endTime
const Coord startPosition
const Coord endPosition
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
BandListening()
inet::physicallayer::BandListening::BandListening (const IRadio * radio, simtime_t startTime, simtime_t endTime, Coord startPosition, Coord endPosition, Hz centerFrequency, Hz bandwidth)
                                                                                                                                                                   :
     ListeningBase(radio, startTime, endTime, startPosition, endPosition),
     centerFrequency(centerFrequency),
     bandwidth(bandwidth)
 {
 }
Member Function Documentation
getBandwidth()
virtual Hz inet::physicallayer::BandListening::getBandwidth () const inline virtual
 { return bandwidth; }
Referenced by inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible(), inet::physicallayer::ApskLayeredReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeIsReceptionPossible(), inet::physicallayer::IsotropicDimensionalBackgroundNoise::computeNoise(), inet::physicallayer::IsotropicScalarBackgroundNoise::computeNoise(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), inet::physicallayer::DimensionalBackgroundNoise::computeNoise(), inet::physicallayer::ScalarAnalogModelBase::computeNoise(), and inet::physicallayer::NarrowbandReceiverBase::computeReceptionDecision().
getCenterFrequency()
virtual Hz inet::physicallayer::BandListening::getCenterFrequency () const inline virtual
 { return centerFrequency; }
Referenced by inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible(), inet::physicallayer::ApskLayeredReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeIsReceptionPossible(), inet::physicallayer::IsotropicDimensionalBackgroundNoise::computeNoise(), inet::physicallayer::IsotropicScalarBackgroundNoise::computeNoise(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), inet::physicallayer::DimensionalBackgroundNoise::computeNoise(), inet::physicallayer::ScalarAnalogModelBase::computeNoise(), and inet::physicallayer::NarrowbandReceiverBase::computeReceptionDecision().
printToStream()
std::ostream & inet::physicallayer::BandListening::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::ListeningBase.
 {
     stream << "BandListening";
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(centerFrequency)
                << EV_FIELD(bandwidth);
     return ListeningBase::printToStream(stream, level);
 }
Member Data Documentation
bandwidth
const Hz inet::physicallayer::BandListening::bandwidth protected
Referenced by printToStream().
centerFrequency
const Hz inet::physicallayer::BandListening::centerFrequency protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
BandListening.h
BandListening.cc