INET Framework for OMNeT++/OMNEST: inet::tcp::TcpOptionTimestamp Class Reference
inet::tcp::TcpOptionTimestamp Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:148 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
TcpOptionTimestamp ()
TcpOptionTimestamp (const TcpOptionTimestamp &other)
virtual ~TcpOptionTimestamp ()
TcpOptionTimestamp & operator= (const TcpOptionTimestamp &other)
virtual TcpOptionTimestamp * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSenderTimestamp () const
virtual void setSenderTimestamp (uint32_t senderTimestamp)
virtual uint32_t getEchoedTimestamp () const
virtual void setEchoedTimestamp (uint32_t echoedTimestamp)
Public Member Functions inherited from inet::tcp::TcpOption
TcpOption ()
TcpOption (const TcpOption &other)
virtual ~TcpOption ()
TcpOption & operator= (const TcpOption &other)
virtual TcpOptionNumbers getKind () const
virtual void setKind (TcpOptionNumbers kind)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const TcpOptionTimestamp &)=delete
Protected Member Functions inherited from inet::tcp::TcpOption
bool operator== (const TcpOption &)=delete
Protected Attributes
uint32_t senderTimestamp = 0
uint32_t echoedTimestamp = 0
Protected Attributes inherited from inet::tcp::TcpOption
TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1)
unsigned short length = 1
Private Member Functions
void copy (const TcpOptionTimestamp &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:148 by opp_msgtool.
class TcpOptionTimestamp extends TcpOption
{
    kind = TCPOPTION_TIMESTAMP;
    length = 10;
    uint32_t senderTimestamp;
    uint32_t echoedTimestamp;
}
Constructor & Destructor Documentation
TcpOptionTimestamp() [1/2]
inet::tcp::TcpOptionTimestamp::TcpOptionTimestamp ()
TcpOptionTimestamp() [2/2]
inet::tcp::TcpOptionTimestamp::TcpOptionTimestamp (const TcpOptionTimestamp & other)
~TcpOptionTimestamp()
virtual inet::tcp::TcpOptionTimestamp::~TcpOptionTimestamp () virtual
Member Function Documentation
copy()
void inet::tcp::TcpOptionTimestamp::copy (const TcpOptionTimestamp & other) private
dup()
virtual TcpOptionTimestamp* inet::tcp::TcpOptionTimestamp::dup () const inline override virtual
Reimplemented from inet::tcp::TcpOption.
 {return new TcpOptionTimestamp(*this);}
getEchoedTimestamp()
virtual uint32_t inet::tcp::TcpOptionTimestamp::getEchoedTimestamp () const virtual
Referenced by inet::tcp::TcpConnection::processTSOption(), and inet::tcp::TcpConnection::writeHeaderOptions().
getSenderTimestamp()
virtual uint32_t inet::tcp::TcpOptionTimestamp::getSenderTimestamp () const virtual
Referenced by inet::tcp::TcpConnection::processTSOption(), and inet::tcp::TcpConnection::writeHeaderOptions().
operator=()
TcpOptionTimestamp& inet::tcp::TcpOptionTimestamp::operator= (const TcpOptionTimestamp & other)
operator==()
bool inet::tcp::TcpOptionTimestamp::operator== (const TcpOptionTimestamp &) protected delete
parsimPack()
virtual void inet::tcp::TcpOptionTimestamp::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::TcpOptionTimestamp::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimUnpacking().
setEchoedTimestamp()
virtual void inet::tcp::TcpOptionTimestamp::setEchoedTimestamp (uint32_t echoedTimestamp) virtual
Referenced by inet::tcp::TcpConnection::writeHeaderOptions().
setSenderTimestamp()
virtual void inet::tcp::TcpOptionTimestamp::setSenderTimestamp (uint32_t senderTimestamp) virtual
Referenced by inet::tcp::TcpConnection::writeHeaderOptions().
Member Data Documentation
echoedTimestamp
uint32_t inet::tcp::TcpOptionTimestamp::echoedTimestamp = 0 protected
senderTimestamp
uint32_t inet::tcp::TcpOptionTimestamp::senderTimestamp = 0 protected
The documentation for this class was generated from the following file:
TcpHeader_m.h