INET Framework for OMNeT++/OMNEST: inet::tcp::TcpBaseAlg Class Reference
inet::tcp::TcpBaseAlg Class Reference
Includes basic TCP algorithms: adaptive retransmission, PERSIST timer, keep-alive, delayed acks – EXCLUDING congestion control.
#include <TcpBaseAlg.h>
Protected Attributes
TcpBaseAlgStateVariables *& state
cMessage * rexmitTimer
cMessage * persistTimer
cMessage * delayedAckTimer
cMessage * keepAliveTimer
Protected Attributes inherited from inet::tcp::TcpAlgorithm
TcpConnection * conn
TcpStateVariables * state
Static Protected Attributes
static simsignal_t cwndSignal = cComponent::registerSignal("cwnd")
static simsignal_t ssthreshSignal = cComponent::registerSignal("ssthresh")
static simsignal_t rttSignal = cComponent::registerSignal("rtt")
static simsignal_t srttSignal = cComponent::registerSignal("srtt")
static simsignal_t rttvarSignal = cComponent::registerSignal("rttvar")
static simsignal_t rtoSignal = cComponent::registerSignal("rto")
static simsignal_t numRtosSignal = cComponent::registerSignal("numRtos")
Process REXMIT, PERSIST, DELAYED-ACK and KEEP-ALIVE timers
virtual void processRexmitTimer (TcpEventCode &event)
virtual void processPersistTimer (TcpEventCode &event)
virtual void processDelayedAckTimer (TcpEventCode &event)
virtual void processKeepAliveTimer (TcpEventCode &event)
virtual void startRexmitTimer ()
Start REXMIT timer and initialize retransmission variables.
virtual void rttMeasurementComplete (simtime_t tSent, simtime_t tAcked)
Update state vars with new measured RTT value.
virtual void rttMeasurementCompleteUsingTS (uint32_t echoedTS) override
Converting uint32_t echoedTS to simtime_t and calling rttMeasurementComplete() to update state vars with new measured RTT value.
virtual bool sendData (bool sendCommandInvoked)
Send data, observing Nagle's algorithm and congestion window.
cMessage * cancelEvent (cMessage *msg)
Utility function.
TcpBaseAlg ()
Ctor.
virtual ~TcpBaseAlg ()
Virtual dtor.
virtual void initialize () override
Create timers, etc.
virtual void established (bool active) override
Called when the connection is going to ESTABLISHED from SYN_SENT or SYN_RCVD.
virtual void connectionClosed () override
Called when the connection closes, it should cancel all running timers.
virtual void processTimer (cMessage *timer, TcpEventCode &event) override
Process REXMIT, PERSIST, DELAYED-ACK and KEEP-ALIVE timers.
virtual void sendCommandInvoked () override
Called after user sent TCP_C_SEND command to us.
virtual void receivedOutOfOrderSegment () override
Called after receiving data which are in the window, but not at its left edge (seq != rcv_nxt).
virtual void receiveSeqChanged () override
Called after rcv_nxt got advanced, either because we received in-sequence data ("text" in RFC 793 lingo) or a FIN.
virtual void receivedDataAck (uint32_t firstSeqAcked) override
Called after we received an ACK which acked some data (that is, we could advance snd_una).
virtual void receivedDuplicateAck () override
Called after we received a duplicate ACK (that is: ackNo == snd_una, no data in segment, segment doesn't carry window update, and also, we have unacked data).
virtual void receivedAckForDataNotYetSent (uint32_t seq) override
Called after we received an ACK for data not yet sent.
virtual void ackSent () override
Called after we sent an ACK.
virtual void dataSent (uint32_t fromseq) override
Called after we sent data.
virtual void segmentRetransmitted (uint32_t fromseq, uint32_t toseq) override
Called after we retransmitted segment.
virtual void restartRexmitTimer () override
Restart REXMIT timer.
virtual bool shouldMarkAck () override
Called before sending ACK.
virtual void processEcnInEstablished () override
Called before processing segment in established state.
Additional Inherited Members
Public Member Functions inherited from inet::tcp::TcpAlgorithm
TcpAlgorithm ()
Ctor.
virtual ~TcpAlgorithm ()
Virtual dtor.
void setConnection (TcpConnection *_conn)
Assign this object to a TcpConnection.
TcpStateVariables * getStateVariables ()
Creates and returns the TCP state variables.
Protected Member Functions inherited from inet::tcp::TcpAlgorithm
virtual TcpStateVariables * createStateVariables ()=0
Create state block (TCB) used by this TCP variant.
Detailed Description
Includes basic TCP algorithms: adaptive retransmission, PERSIST timer, keep-alive, delayed acks – EXCLUDING congestion control.
Congestion control is implemented in subclasses such as TCPTahoeAlg or TCPRenoAlg.
Implements:
delayed ACK algorithm (RFC 1122)
Jacobson's and Karn's algorithms for adaptive retransmission
Nagle's algorithm (RFC 896) to prevent silly window syndrome
Increased Initial Window (RFC 3390)
PERSIST timer
To be done:
KEEP-ALIVE timer
Note: currently the timers and time calculations are done in double and NOT in Unix (200ms or 500ms) ticks. It's possible to write another TcpAlgorithm which uses ticks (or rather, factor out timer handling to separate methods, and redefine only those).
Congestion window is set to SMSS when the connection is established, and not touched after that. Subclasses may redefine any of the virtual functions here to add their congestion control code.
Constructor & Destructor Documentation
TcpBaseAlg()
inet::tcp::TcpBaseAlg::TcpBaseAlg ()
Ctor.
                        : TcpAlgorithm(),
     state((TcpBaseAlgStateVariables *&)TcpAlgorithm::state)
 {
     rexmitTimer = persistTimer = delayedAckTimer = keepAliveTimer = nullptr;
 }
~TcpBaseAlg()
inet::tcp::TcpBaseAlg::~TcpBaseAlg () virtual
Virtual dtor.
 {
     // Note: don't delete "state" here, it'll be deleted from TcpConnection
     // cancel and delete timers
     if (rexmitTimer)
         delete cancelEvent(rexmitTimer);
     if (persistTimer)
         delete cancelEvent(persistTimer);
     if (delayedAckTimer)
         delete cancelEvent(delayedAckTimer);
     if (keepAliveTimer)
         delete cancelEvent(keepAliveTimer);
 }
Member Function Documentation
ackSent()
void inet::tcp::TcpBaseAlg::ackSent () override virtual
Called after we sent an ACK.
This hook can be used to cancel the delayed-ACK timer.
Implements inet::tcp::TcpAlgorithm.
 {
     state->full_sized_segment_counter = 0; // reset counter
     state->ack_now = false; // reset flag
     state->last_ack_sent = state->rcv_nxt; // update last_ack_sent, needed for TS option
     // if delayed ACK timer is running, cancel it
     if (delayedAckTimer->isScheduled())
         cancelEvent(delayedAckTimer);
 }
cancelEvent()
cMessage* inet::tcp::TcpBaseAlg::cancelEvent (cMessage * msg) inline protected
Utility function.
 { return conn->cancelEvent(msg); }
Referenced by ackSent(), connectionClosed(), receivedDataAck(), restartRexmitTimer(), and ~TcpBaseAlg().
connectionClosed()
void inet::tcp::TcpBaseAlg::connectionClosed () override virtual
Called when the connection closes, it should cancel all running timers.
Implements inet::tcp::TcpAlgorithm.
 {
     cancelEvent(rexmitTimer);
     cancelEvent(persistTimer);
     cancelEvent(delayedAckTimer);
     cancelEvent(keepAliveTimer);
 }
dataSent()
void inet::tcp::TcpBaseAlg::dataSent (uint32_t fromseq) override virtual
Called after we sent data.
This hook can be used to schedule the retransmission timer, to start round-trip time measurement, etc. The argument is the seqno of the first byte sent.
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::TcpVegas, and inet::tcp::TcpWestwood.
 {
     // if retransmission timer not running, schedule it
     if (!rexmitTimer->isScheduled()) {
         EV_INFO << "Starting REXMIT timer\n";
         startRexmitTimer();
     }
     if (!state->ts_enabled) {
         // start round-trip time measurement (if not already running)
         if (state->rtseq_sendtime == 0) {
             // remember this sequence number and when it was sent
             state->rtseq = fromseq;
             state->rtseq_sendtime = simTime();
             EV_DETAIL << "Starting rtt measurement on seq=" << state->rtseq << "\n";
         }
     }
     state->time_last_data_sent = simTime();
 }
Referenced by inet::tcp::TcpWestwood::dataSent(), and inet::tcp::TcpVegas::dataSent().
established()
void inet::tcp::TcpBaseAlg::established (bool active) override virtual
Called when the connection is going to ESTABLISHED from SYN_SENT or SYN_RCVD.
This is a place to initialize some variables (e.g. set cwnd to the MSS learned during connection setup). If we are on the active side, here we also have to finish the 3-way connection setup procedure by sending an ACK, possibly piggybacked on data.
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::TcpNoCongestionControl.
 {
     // initialize cwnd (we may learn SMSS during connection setup)
     // RFC 3390, page 2: "The upper bound for the initial window is given more precisely in
     // (1):
     //
     //   min (4*MSS, max (2*MSS, 4380 bytes))                        (1)
     //
     // Note: Sending a 1500 byte packet indicates a maximum segment size
     // (MSS) of 1460 bytes (assuming no IP or TCP options).  Therefore,
     // limiting the initial window's MSS to 4380 bytes allows the sender to
     // transmit three segments initially in the common case when using 1500
     // byte packets.
     //
     // Equivalently, the upper bound for the initial window size is based on
     // the MSS, as follows:
     //
     //   If (MSS <= 1095 bytes)
     //     then win <= 4 * MSS;
     //   If (1095 bytes < MSS < 2190 bytes)
     //     then win <= 4380;
     //   If (2190 bytes <= MSS)
     //     then win <= 2 * MSS;
     //
     // This increased initial window is optional: a TCP MAY start with a
     // larger initial window.  However, we expect that most general-purpose
     // TCP implementations would choose to use the larger initial congestion
     // window given in equation (1) above.
     //
     // This upper bound for the initial window size represents a change from
     // RFC 2581 [RFC2581], which specified that the congestion window be
     // initialized to one or two segments.
     // (...)
     // If the SYN or SYN/ACK is
     // lost, the initial window used by a sender after a correctly
     // transmitted SYN MUST be one segment consisting of MSS bytes."
     if (state->increased_IW_enabled && state->syn_rexmit_count == 0) {
         state->snd_cwnd = std::min(4 * state->snd_mss, std::max(2 * state->snd_mss, (uint32_t)4380));
         EV_DETAIL << "Enabled Increased Initial Window, CWND is set to " << state->snd_cwnd << "\n";
     }
     // RFC 2001, page 3:
     // " 1.  Initialization for a given connection sets cwnd to one segment
     // and ssthresh to 65535 bytes."
     else
         state->snd_cwnd = state->snd_mss; // RFC 2001
     if (active) {
         // finish connection setup with ACK (possibly piggybacked on data)
         EV_INFO << "Completing connection setup by sending ACK (possibly piggybacked on data)\n";
         if (!sendData(false)) // FIXME - This condition is never true because the buffer is empty (at this time) therefore the first ACK is never piggyback on data
             conn->sendAck();
     }
 }
initialize()
void inet::tcp::TcpBaseAlg::initialize () override virtual
Create timers, etc.
Reimplemented from inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::TcpNoCongestionControl, inet::tcp::TcpTahoeRenoFamily, and inet::tcp::DcTcp.
 {
     TcpAlgorithm::initialize();
     rexmitTimer = new cMessage("REXMIT");
     persistTimer = new cMessage("PERSIST");
     delayedAckTimer = new cMessage("DELAYEDACK");
     keepAliveTimer = new cMessage("KEEPALIVE");
     rexmitTimer->setContextPointer(conn);
     persistTimer->setContextPointer(conn);
     delayedAckTimer->setContextPointer(conn);
     keepAliveTimer->setContextPointer(conn);
 }
Referenced by inet::tcp::TcpTahoeRenoFamily::initialize(), and inet::tcp::TcpNoCongestionControl::initialize().
processDelayedAckTimer()
void inet::tcp::TcpBaseAlg::processDelayedAckTimer (TcpEventCode & event) protected virtual
 {
     state->ack_now = true;
     conn->sendAck();
 }
Referenced by processTimer().
processEcnInEstablished()
void inet::tcp::TcpBaseAlg::processEcnInEstablished () override virtual
Called before processing segment in established state.
This function process ECN marks.
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::DcTcp.
 {
 }
processKeepAliveTimer()
void inet::tcp::TcpBaseAlg::processKeepAliveTimer (TcpEventCode & event) protected virtual
 {
     // TODO
     // RFC 1122, page 102:
     // "A "keep-alive" mechanism periodically probes the other
     // end of a connection when the connection is otherwise
     // idle, even when there is no data to be sent.  The TCP
     // specification does not include a keep-alive mechanism
     // because it could:  (1) cause perfectly good connections
     // to break during transient Internet failures; (2)
     // consume unnecessary bandwidth ("if no one is using the
     // connection, who cares if it is still good?"); and (3)
     // cost money for an Internet path that charges for
     // packets."
 }
Referenced by processTimer().
processPersistTimer()
void inet::tcp::TcpBaseAlg::processPersistTimer (TcpEventCode & event) protected virtual
 {
     // setup and restart the PERSIST timer
     // FIXME Calculation of PERSIST timer is not as simple as done here!
     // It depends on RTT calculations and is bounded to 5-60 seconds.
     // This simplified PERSIST timer calculation generates values
     // as presented in [Stevens, W.R.: TCP/IP Illustrated, Volume 1, chapter 22.2]
     // (5, 5, 6, 12, 24, 48, 60, 60, 60...)
     if (state->persist_factor == 0)
         state->persist_factor++;
     else if (state->persist_factor < 64)
         state->persist_factor = state->persist_factor * 2;
     state->persist_timeout = state->persist_factor * 1.5; // 1.5 is a factor for typical LAN connection [Stevens, W.R.: TCP/IP Ill. Vol. 1, chapter 22.2]
     // PERSIST timer is bounded to 5-60 seconds
     if (state->persist_timeout < MIN_PERSIST_TIMEOUT)
         state->rexmit_timeout = MIN_PERSIST_TIMEOUT;
     if (state->persist_timeout > MAX_PERSIST_TIMEOUT)
         state->rexmit_timeout = MAX_PERSIST_TIMEOUT;
     conn->scheduleAfter(state->persist_timeout, persistTimer);
     // sending persist probe
     conn->sendProbe();
 }
Referenced by processTimer().
processRexmitTimer()
void inet::tcp::TcpBaseAlg::processRexmitTimer (TcpEventCode & event) protected virtual
Reimplemented in inet::tcp::TcpVegas, inet::tcp::TcpWestwood, inet::tcp::TcpTahoe, inet::tcp::TcpReno, inet::tcp::TcpNewReno, and inet::tcp::TcpNoCongestionControl.
 {
     EV_DETAIL << "TCB: " << state->str() << "\n";
     //"
     // For any state if the retransmission timeout expires on a segment in
     // the retransmission queue, send the segment at the front of the
     // retransmission queue again, reinitialize the retransmission timer,
     // and return.
     //"
     // Also: abort connection after max 12 retries.
     //
     // However, retransmission is actually more complicated than that
     // in RFC 793 above, we'll leave it to subclasses (e.g. TcpTahoe, TcpReno).
     //
     if (++state->rexmit_count > MAX_REXMIT_COUNT) {
         EV_DETAIL << "Retransmission count exceeds " << MAX_REXMIT_COUNT << ", aborting connection\n";
         conn->signalConnectionTimeout();
         event = TCP_E_ABORT; // TODO maybe rather introduce a TCP_E_TIMEDOUT event
         return;
     }
     EV_INFO << "Performing retransmission #" << state->rexmit_count
             << "; increasing RTO from " << state->rexmit_timeout << "s ";
     //
     // Karn's algorithm is implemented below:
     //  (1) don't measure RTT for retransmitted packets.
     //  (2) RTO should be doubled after retransmission ("exponential back-off")
     //
     // restart the retransmission timer with twice the latest RTO value, or with the max, whichever is smaller
     state->rexmit_timeout += state->rexmit_timeout;
     if (state->rexmit_timeout > MAX_REXMIT_TIMEOUT)
         state->rexmit_timeout = MAX_REXMIT_TIMEOUT;
     conn->scheduleAfter(state->rexmit_timeout, rexmitTimer);
     EV_INFO << " to " << state->rexmit_timeout << "s, and cancelling RTT measurement\n";
     // cancel round-trip time measurement
     state->rtseq_sendtime = 0;
     state->numRtos++;
     conn->emit(numRtosSignal, state->numRtos);
     // if sacked_enabled reset sack related flags
     if (state->sack_enabled) {
         conn->rexmitQueue->resetSackedBit();
         conn->rexmitQueue->resetRexmittedBit();
         // RFC 3517, page 8: "If an RTO occurs during loss recovery as specified in this document,
         // RecoveryPoint MUST be set to HighData.  Further, the new value of
         // RecoveryPoint MUST be preserved and the loss recovery algorithm
         // outlined in this document MUST be terminated.  In addition, a new
         // recovery phase (as described in section 5) MUST NOT be initiated
         // until HighACK is greater than or equal to the new value of
         // RecoveryPoint."
         if (state->lossRecovery) {
             state->recoveryPoint = state->snd_max; // HighData = snd_max
             EV_DETAIL << "Loss Recovery terminated.\n";
             state->lossRecovery = false;
         }
     }
     state->time_last_data_sent = simTime();
     //
     // Leave congestion window management and actual retransmission to
     // subclasses (e.g. TcpTahoe, TcpReno).
     //
     // That is, subclasses will redefine this method, call us, then perform
     // window adjustments and do the retransmission as they like.
     //
 }
Referenced by inet::tcp::TcpNoCongestionControl::processRexmitTimer(), inet::tcp::TcpNewReno::processRexmitTimer(), inet::tcp::TcpReno::processRexmitTimer(), inet::tcp::TcpTahoe::processRexmitTimer(), inet::tcp::TcpWestwood::processRexmitTimer(), inet::tcp::TcpVegas::processRexmitTimer(), and processTimer().
processTimer()
void inet::tcp::TcpBaseAlg::processTimer (cMessage * timer, TcpEventCode & event) override virtual
Process REXMIT, PERSIST, DELAYED-ACK and KEEP-ALIVE timers.
Implements inet::tcp::TcpAlgorithm.
 {
     if (timer == rexmitTimer)
         processRexmitTimer(event);
     else if (timer == persistTimer)
         processPersistTimer(event);
     else if (timer == delayedAckTimer)
         processDelayedAckTimer(event);
     else if (timer == keepAliveTimer)
         processKeepAliveTimer(event);
     else
         throw cRuntimeError(timer, "unrecognized timer");
 }
receivedAckForDataNotYetSent()
void inet::tcp::TcpBaseAlg::receivedAckForDataNotYetSent (uint32_t seq) override virtual
Called after we received an ACK for data not yet sent.
According to RFC 793 this function should send an ACK.
Implements inet::tcp::TcpAlgorithm.
 {
     // Note: In this case no immediate ACK will be send because not mentioned
     // in [Stevens, W.R.: TCP/IP Illustrated, Volume 2, page 861].
     // To force immediate ACK use:
 //    state->ack_now = true;
 //    tcpEV << "ACK acks something not yet sent, sending immediate ACK\n";
     EV_INFO << "ACK acks something not yet sent, sending ACK\n";
     conn->sendAck();
 }
receivedDataAck()
void inet::tcp::TcpBaseAlg::receivedDataAck (uint32_t firstSeqAcked) override virtual
Called after we received an ACK which acked some data (that is, we could advance snd_una).
At this point the state variables (snd_una, snd_wnd) have already been updated. The argument firstSeqAcked is the previous snd_una value, that is, the number of bytes acked is (snd_una - firstSeqAcked). The dupack counter still reflects the old value (needed for Reno and NewReno); it'll be reset to 0 after this call returns.
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::TcpVegas, inet::tcp::TcpWestwood, inet::tcp::TcpNoCongestionControl, inet::tcp::TcpTahoe, inet::tcp::DcTcp, inet::tcp::TcpReno, and inet::tcp::TcpNewReno.
 {
     if (!state->ts_enabled) {
         // if round-trip time measurement is running, check if rtseq has been acked
         if (state->rtseq_sendtime != 0 && seqLess(state->rtseq, state->snd_una)) {
             // print value
             EV_DETAIL << "Round-trip time measured on rtseq=" << state->rtseq << ": "
                       << floor((simTime() - state->rtseq_sendtime) * 1000 + 0.5) << "ms\n";
             rttMeasurementComplete(state->rtseq_sendtime, simTime()); // update RTT variables with new value
             // measurement finished
             state->rtseq_sendtime = 0;
         }
     }
     //
     // handling of retransmission timer: if the ACK is for the last segment sent
     // (no data in flight), cancel the timer, otherwise restart the timer
     // with the current RTO value.
     //
     if (state->snd_una == state->snd_max) {
         if (rexmitTimer->isScheduled()) {
             EV_INFO << "ACK acks all outstanding segments, cancel REXMIT timer\n";
             cancelEvent(rexmitTimer);
         }
         else
             EV_INFO << "There were no outstanding segments, nothing new in this ACK.\n";
     }
     else {
         EV_INFO << "ACK acks some but not all outstanding segments ("
                 << (state->snd_max - state->snd_una) << " bytes outstanding), "
                 << "restarting REXMIT timer\n";
         cancelEvent(rexmitTimer);
         startRexmitTimer();
     }
     //
     // handling of PERSIST timer:
     // If data sender received a zero-sized window, check retransmission timer.
     //  If retransmission timer is not scheduled, start PERSIST timer if not already
     //  running.
     //
     // If data sender received a non zero-sized window, check PERSIST timer.
     //  If PERSIST timer is scheduled, cancel PERSIST timer.
     //
     if (state->snd_wnd == 0) { // received zero-sized window?
         if (rexmitTimer->isScheduled()) {
             if (persistTimer->isScheduled()) {
                 EV_INFO << "Received zero-sized window and REXMIT timer is running therefore PERSIST timer is canceled.\n";
                 cancelEvent(persistTimer);
                 state->persist_factor = 0;
             }
             else
                 EV_INFO << "Received zero-sized window and REXMIT timer is running therefore PERSIST timer is not started.\n";
         }
         else {
             if (!persistTimer->isScheduled()) {
                 EV_INFO << "Received zero-sized window therefore PERSIST timer is started.\n";
                 conn->scheduleAfter(state->persist_timeout, persistTimer);
             }
             else
                 EV_INFO << "Received zero-sized window and PERSIST timer is already running.\n";
         }
     }
     else { // received non zero-sized window?
         if (persistTimer->isScheduled()) {
             EV_INFO << "Received non zero-sized window therefore PERSIST timer is canceled.\n";
             cancelEvent(persistTimer);
             state->persist_factor = 0;
         }
     }
     //
     // Leave congestion window management and possible sending data to
     // subclasses (e.g. TcpTahoe, TcpReno).
     //
     // That is, subclasses will redefine this method, call us, then perform
     // window adjustments and send data (if there's room in the window).
     //
 }
Referenced by inet::tcp::TcpNewReno::receivedDataAck(), inet::tcp::DcTcp::receivedDataAck(), inet::tcp::TcpReno::receivedDataAck(), inet::tcp::TcpTahoe::receivedDataAck(), inet::tcp::TcpNoCongestionControl::receivedDataAck(), inet::tcp::TcpWestwood::receivedDataAck(), and inet::tcp::TcpVegas::receivedDataAck().
receivedDuplicateAck()
void inet::tcp::TcpBaseAlg::receivedDuplicateAck () override virtual
Called after we received a duplicate ACK (that is: ackNo == snd_una, no data in segment, segment doesn't carry window update, and also, we have unacked data).
The dupack counter got already updated when calling this method (i.e. dupacks == 1 on first duplicate ACK.)
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::TcpVegas, inet::tcp::TcpWestwood, inet::tcp::TcpTahoe, inet::tcp::TcpReno, and inet::tcp::TcpNewReno.
 {
     EV_INFO << "Duplicate ACK #" << state->dupacks << "\n";
     bool fullSegmentsOnly = state->nagle_enabled && state->snd_una != state->snd_max;
     if (state->dupacks < state->dupthresh && state->limited_transmit_enabled) // DUPTRESH = 3
         conn->sendOneNewSegment(fullSegmentsOnly, state->snd_cwnd); // RFC 3042
     //
     // Leave to subclasses (e.g. TcpTahoe, TcpReno) whatever they want to do
     // on duplicate Acks.
     //
     // That is, subclasses will redefine this method, call us, then perform
     // whatever action they want to do on dupAcks (e.g. retransmitting one segment).
     //
 }
Referenced by inet::tcp::TcpNewReno::receivedDuplicateAck(), inet::tcp::TcpReno::receivedDuplicateAck(), inet::tcp::TcpTahoe::receivedDuplicateAck(), inet::tcp::TcpWestwood::receivedDuplicateAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
receivedOutOfOrderSegment()
void inet::tcp::TcpBaseAlg::receivedOutOfOrderSegment () override virtual
Called after receiving data which are in the window, but not at its left edge (seq != rcv_nxt).
This indicates that either segments got re-ordered in the way, or one segment was lost. RFC 1122 and RFC 2001 recommend sending an immediate ACK here (Fast Retransmit relies on that).
Implements inet::tcp::TcpAlgorithm.
 {
     state->ack_now = true;
     EV_INFO << "Out-of-order segment, sending immediate ACK\n";
     conn->sendAck();
 }
receiveSeqChanged()
void inet::tcp::TcpBaseAlg::receiveSeqChanged () override virtual
Called after rcv_nxt got advanced, either because we received in-sequence data ("text" in RFC 793 lingo) or a FIN.
At this point, rcv_nxt has already been updated. This method should take care to send or schedule an ACK some time.
Implements inet::tcp::TcpAlgorithm.
 {
     // If we send a data segment already (with the updated seqNo) there is no need to send an additional ACK
     if (state->full_sized_segment_counter == 0 && !state->ack_now && state->last_ack_sent == state->rcv_nxt && !delayedAckTimer->isScheduled()) { // ackSent?
 //        tcpEV << "ACK has already been sent (possibly piggybacked on data)\n";
     }
     else {
         // RFC 2581, page 6:
         // "3.2 Fast Retransmit/Fast Recovery
         // (...)
         // In addition, a TCP receiver SHOULD send an immediate ACK
         // when the incoming segment fills in all or part of a gap in the
         // sequence space."
         if (state->lossRecovery)
             state->ack_now = true; // although not mentioned in [Stevens, W.R.: TCP/IP Illustrated, Volume 2, page 861] seems like we have to set ack_now
         if (!state->delayed_acks_enabled) { // delayed ACK disabled
             EV_INFO << "rcv_nxt changed to " << state->rcv_nxt << ", (delayed ACK disabled) sending ACK now\n";
             conn->sendAck();
         }
         else { // delayed ACK enabled
             if (state->ack_now) {
                 EV_INFO << "rcv_nxt changed to " << state->rcv_nxt << ", (delayed ACK enabled, but ack_now is set) sending ACK now\n";
                 conn->sendAck();
             }
             // RFC 1122, page 96: "in a stream of full-sized segments there SHOULD be an ACK for at least every second segment."
             else if (state->full_sized_segment_counter >= 2) {
                 EV_INFO << "rcv_nxt changed to " << state->rcv_nxt << ", (delayed ACK enabled, but full_sized_segment_counter=" << state->full_sized_segment_counter << ") sending ACK now\n";
                 conn->sendAck();
             }
             else {
                 EV_INFO << "rcv_nxt changed to " << state->rcv_nxt << ", (delayed ACK enabled and full_sized_segment_counter=" << state->full_sized_segment_counter << ") scheduling ACK\n";
                 if (!delayedAckTimer->isScheduled()) // schedule delayed ACK timer if not already running
                     conn->scheduleAfter(DELAYED_ACK_TIMEOUT, delayedAckTimer);
             }
         }
     }
 }
restartRexmitTimer()
void inet::tcp::TcpBaseAlg::restartRexmitTimer () override virtual
Restart REXMIT timer.
Implements inet::tcp::TcpAlgorithm.
 {
     if (rexmitTimer->isScheduled())
         cancelEvent(rexmitTimer);
     startRexmitTimer();
 }
Referenced by inet::tcp::TcpNewReno::receivedDataAck(), inet::tcp::TcpReno::receivedDataAck(), inet::tcp::TcpReno::receivedDuplicateAck(), inet::tcp::TcpWestwood::receivedDuplicateAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
rttMeasurementComplete()
void inet::tcp::TcpBaseAlg::rttMeasurementComplete (simtime_t tSent, simtime_t tAcked) protected virtual
Update state vars with new measured RTT value.
Passing two simtime_t's will allow rttMeasurementComplete() to do calculations in double or in 200ms/500ms ticks, as needed)
 {
     //
     // Jacobson's algorithm for estimating RTT and adaptively setting RTO.
     //
     // Note: this implementation calculates in doubles. An impl. which uses
     // 500ms ticks is available from old tcpmodule.cc:calcRetransTimer().
     //
     // update smoothed RTT estimate (srtt) and variance (rttvar)
     const double g = 0.125; // 1 / 8; (1 - alpha) where alpha == 7 / 8;
     simtime_t newRTT = tAcked - tSent;
     simtime_t& srtt = state->srtt;
     simtime_t& rttvar = state->rttvar;
     simtime_t err = newRTT - srtt;
     srtt += g * err;
     rttvar += g * (fabs(err) - rttvar);
     // assign RTO (here: rexmit_timeout) a new value
     simtime_t rto = srtt + 4 * rttvar;
     if (rto > MAX_REXMIT_TIMEOUT)
         rto = MAX_REXMIT_TIMEOUT;
     else if (rto < MIN_REXMIT_TIMEOUT)
         rto = MIN_REXMIT_TIMEOUT;
     state->rexmit_timeout = rto;
     // record statistics
     EV_DETAIL << "Measured RTT=" << (newRTT * 1000) << "ms, updated SRTT=" << (srtt * 1000)
               << "ms, new RTO=" << (rto * 1000) << "ms\n";
     conn->emit(rttSignal, newRTT);
     conn->emit(srttSignal, srtt);
     conn->emit(rttvarSignal, rttvar);
     conn->emit(rtoSignal, rto);
 }
Referenced by receivedDataAck(), and rttMeasurementCompleteUsingTS().
rttMeasurementCompleteUsingTS()
void inet::tcp::TcpBaseAlg::rttMeasurementCompleteUsingTS (uint32_t echoedTS) override protected virtual
Converting uint32_t echoedTS to simtime_t and calling rttMeasurementComplete() to update state vars with new measured RTT value.
Implements inet::tcp::TcpAlgorithm.
 {
     ASSERT(state->ts_enabled);
     // Note: The TS option is using uint32_t values (ms precision) therefore we convert the current simTime also to a uint32_t value (ms precision)
     // and then convert back to simtime_t to use rttMeasurementComplete() to update srtt and rttvar
     uint32_t now = conn->convertSimtimeToTS(simTime());
     simtime_t tSent = conn->convertTSToSimtime(echoedTS);
     simtime_t tAcked = conn->convertTSToSimtime(now);
     rttMeasurementComplete(tSent, tAcked);
 }
segmentRetransmitted()
void inet::tcp::TcpBaseAlg::segmentRetransmitted (uint32_t fromseq, uint32_t toseq) override virtual
Called after we retransmitted segment.
The argument fromseq is the seqno of the first byte sent. The argument toseq is the seqno of the last byte sent+1.
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::TcpVegas, and inet::tcp::TcpWestwood.
 {
 }
Referenced by inet::tcp::TcpWestwood::segmentRetransmitted(), and inet::tcp::TcpVegas::segmentRetransmitted().
sendCommandInvoked()
void inet::tcp::TcpBaseAlg::sendCommandInvoked () override virtual
Called after user sent TCP_C_SEND command to us.
Implements inet::tcp::TcpAlgorithm.
 {
     // try sending
     sendData(true);
 }
Referenced by inet::tcp::TcpNoCongestionControl::sendData().
sendData()
bool inet::tcp::TcpBaseAlg::sendData (bool sendCommandInvoked) protected virtual
Send data, observing Nagle's algorithm and congestion window.
Reimplemented in inet::tcp::TcpNoCongestionControl.
 {
     // RFC 2581, pages 7 and 8: "When TCP has not received a segment for
     // more than one retransmission timeout, cwnd is reduced to the value
     // of the restart window (RW) before transmission begins.
     // For the purposes of this standard, we define RW = IW.
     // (...)
     // Using the last time a segment was received to determine whether or
     // not to decrease cwnd fails to deflate cwnd in the common case of
     // persistent HTTP connections [HTH98].
     // (...)
     // Therefore, a TCP SHOULD set cwnd to no more than RW before beginning
     // transmission if the TCP has not sent data in an interval exceeding
     // the retransmission timeout."
     if (!conn->isSendQueueEmpty()) { // do we have any data to send?
         if ((simTime() - state->time_last_data_sent) > state->rexmit_timeout) {
             // RFC 5681, page 11: "For the purposes of this standard, we define RW = min(IW,cwnd)."
             if (state->increased_IW_enabled)
                 state->snd_cwnd = std::min(std::min(4 * state->snd_mss, std::max(2 * state->snd_mss, (uint32_t)4380)), state->snd_cwnd);
             else
                 state->snd_cwnd = state->snd_mss;
             EV_INFO << "Restarting idle connection, CWND is set to " << state->snd_cwnd << "\n";
         }
     }
     //
     // Send window is effectively the minimum of the congestion window (cwnd)
     // and the advertised window (snd_wnd).
     //
     return conn->sendData(state->snd_cwnd);
 }
Referenced by established(), inet::tcp::TcpNewReno::receivedDataAck(), inet::tcp::DcTcp::receivedDataAck(), inet::tcp::TcpReno::receivedDataAck(), inet::tcp::TcpTahoe::receivedDataAck(), inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), inet::tcp::TcpNewReno::receivedDuplicateAck(), inet::tcp::TcpReno::receivedDuplicateAck(), inet::tcp::TcpWestwood::receivedDuplicateAck(), inet::tcp::TcpVegas::receivedDuplicateAck(), and sendCommandInvoked().
shouldMarkAck()
bool inet::tcp::TcpBaseAlg::shouldMarkAck () override virtual
Called before sending ACK.
Determines whether to set ECE bit.
Implements inet::tcp::TcpAlgorithm.
Reimplemented in inet::tcp::DcTcp.
 {
     // rfc-3168, pages 19-20:
     // When TCP receives a CE data packet at the destination end-system, the
     // TCP data receiver sets the ECN-Echo flag in the TCP header of the
     // subsequent ACK packet.
     // ...
     // After a TCP receiver sends an ACK packet with the ECN-Echo bit set,
     // that TCP receiver continues to set the ECN-Echo flag in all the ACK
     // packets it sends (whether they acknowledge CE data packets or non-CE
     // data packets) until it receives a CWR packet (a packet with the CWR
     // flag set).  After the receipt of the CWR packet, acknowledgments for
     // subsequent non-CE data packets do not have the ECN-Echo flag set.
     if (state && state->ect) {
         if (state->gotCeIndication) {
             EV_INFO << "Received CE... ";
             if (state->ecnEchoState)
                 EV_INFO << "Already in ecnEcho state\n";
             else {
                 state->ecnEchoState = true;
                 EV << "Entering ecnEcho state\n";
             }
             state->gotCeIndication = false;
         }
         return state->ecnEchoState;
     }
     return false;
 }
startRexmitTimer()
void inet::tcp::TcpBaseAlg::startRexmitTimer () protected virtual
Start REXMIT timer and initialize retransmission variables.
 {
     // start counting retransmissions for this seq number.
     // Note: state->rexmit_timeout is set from rttMeasurementComplete().
     state->rexmit_count = 0;
     // schedule timer
     conn->scheduleAfter(state->rexmit_timeout, rexmitTimer);
 }
Referenced by dataSent(), receivedDataAck(), and restartRexmitTimer().
Member Data Documentation
cwndSignal
simsignal_t inet::tcp::TcpBaseAlg::cwndSignal = cComponent::registerSignal("cwnd") static protected
Referenced by inet::tcp::TcpNewReno::processRexmitTimer(), inet::tcp::TcpReno::processRexmitTimer(), inet::tcp::TcpTahoe::processRexmitTimer(), inet::tcp::TcpWestwood::processRexmitTimer(), inet::tcp::TcpVegas::processRexmitTimer(), inet::tcp::TcpNewReno::receivedDataAck(), inet::tcp::DcTcp::receivedDataAck(), inet::tcp::TcpReno::receivedDataAck(), inet::tcp::TcpTahoe::receivedDataAck(), inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), inet::tcp::TcpNewReno::receivedDuplicateAck(), inet::tcp::TcpReno::receivedDuplicateAck(), inet::tcp::TcpTahoe::receivedDuplicateAck(), inet::tcp::TcpWestwood::receivedDuplicateAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
delayedAckTimer
cMessage* inet::tcp::TcpBaseAlg::delayedAckTimer protected
Referenced by ackSent(), connectionClosed(), initialize(), processTimer(), receiveSeqChanged(), TcpBaseAlg(), and ~TcpBaseAlg().
keepAliveTimer
cMessage* inet::tcp::TcpBaseAlg::keepAliveTimer protected
Referenced by connectionClosed(), initialize(), processTimer(), TcpBaseAlg(), and ~TcpBaseAlg().
numRtosSignal
simsignal_t inet::tcp::TcpBaseAlg::numRtosSignal = cComponent::registerSignal("numRtos") static protected
Referenced by processRexmitTimer().
persistTimer
cMessage* inet::tcp::TcpBaseAlg::persistTimer protected
Referenced by connectionClosed(), initialize(), processPersistTimer(), processTimer(), receivedDataAck(), TcpBaseAlg(), and ~TcpBaseAlg().
rexmitTimer
cMessage* inet::tcp::TcpBaseAlg::rexmitTimer protected
Referenced by connectionClosed(), dataSent(), initialize(), processRexmitTimer(), processTimer(), receivedDataAck(), restartRexmitTimer(), startRexmitTimer(), TcpBaseAlg(), and ~TcpBaseAlg().
rtoSignal
simsignal_t inet::tcp::TcpBaseAlg::rtoSignal = cComponent::registerSignal("rto") static protected
Referenced by rttMeasurementComplete().
rttSignal
simsignal_t inet::tcp::TcpBaseAlg::rttSignal = cComponent::registerSignal("rtt") static protected
Referenced by rttMeasurementComplete().
rttvarSignal
simsignal_t inet::tcp::TcpBaseAlg::rttvarSignal = cComponent::registerSignal("rttvar") static protected
Referenced by rttMeasurementComplete().
srttSignal
simsignal_t inet::tcp::TcpBaseAlg::srttSignal = cComponent::registerSignal("srtt") static protected
Referenced by rttMeasurementComplete().
ssthreshSignal
simsignal_t inet::tcp::TcpBaseAlg::ssthreshSignal = cComponent::registerSignal("ssthresh") static protected
Referenced by inet::tcp::TcpNewReno::recalculateSlowStartThreshold(), inet::tcp::TcpReno::recalculateSlowStartThreshold(), inet::tcp::TcpTahoe::recalculateSlowStartThreshold(), inet::tcp::TcpWestwood::recalculateSlowStartThreshold(), inet::tcp::TcpVegas::recalculateSlowStartThreshold(), inet::tcp::DcTcp::receivedDataAck(), and inet::tcp::TcpReno::receivedDataAck().
state
TcpBaseAlgStateVariables*& inet::tcp::TcpBaseAlg::state protected
Referenced by ackSent(), dataSent(), established(), processDelayedAckTimer(), processPersistTimer(), processRexmitTimer(), receivedDataAck(), receivedDuplicateAck(), receivedOutOfOrderSegment(), receiveSeqChanged(), rttMeasurementComplete(), rttMeasurementCompleteUsingTS(), sendData(), shouldMarkAck(), and startRexmitTimer().
The documentation for this class was generated from the following files:
TcpBaseAlg.h
TcpBaseAlg.cc