INET Framework for OMNeT++/OMNEST: inet::Message Class Reference
inet::Message Class Reference
#include <Message.h>
Public Member Functions
Tag related functions
virtual SharingTagSet & getTags () override
Returns all tags.
int getNumTags () const
Returns the number of message tags.
const Ptr< const TagBase > getTag (int index) const
Returns the message tag at the given index.
void clearTags ()
Clears the set of message tags.
void copyTags (const Message &source)
Copies the set of message tags from the other message.
template<typename T >
const Ptr< const T > findTag () const
Returns the message tag for the provided type or returns nullptr if no such message tag is found.
template<typename T >
const Ptr< T > findTagForUpdate ()
Returns the message tag for the provided type or returns nullptr if no such message tag is found.
template<typename T >
const Ptr< const T > getTag () const
Returns the message tag for the provided type or throws an exception if no such message tag is found.
template<typename T >
const Ptr< T > getTagForUpdate ()
Returns the message tag for the provided type or throws an exception if no such message tag is found.
template<typename T >
const Ptr< T > addTag ()
Returns a newly added message tag for the provided type, or throws an exception if such a message tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent ()
Returns a newly added message tag for the provided type if absent, or returns the message tag that is already present.
template<typename T >
const Ptr< T > removeTag ()
Removes the message tag for the provided type, or throws an exception if no such message tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent ()
Removes the message tag for the provided type if present, or returns nullptr if no such message tag is found.
Utility functions
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
SharingTagSet tags
Friends
class MessageDescriptor
Class descriptor functions
const TagBase * _getTag (int index)
Message (const char *name=nullptr, short kind=0)
Message (const Message &other)
virtual Message * dup () const override
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Message() [1/2]
inet::Message::Message (const char * name = nullptr, short kind = 0) explicit
                                              :
     cMessage(name, kind)
 {
 }
Message() [2/2]
inet::Message::Message (const Message & other)
                                      :
     cMessage(other),
     tags(other.tags)
 {
 }
Member Function Documentation
_getTag()
const TagBase* inet::Message::_getTag (int index) inline protected
 { return tags.getTag(index).get(); }
addTag()
template<typename T > const Ptr<T> inet::Message::addTag () inline
Returns a newly added message tag for the provided type, or throws an exception if such a message tag is already present.
{
         return tags.addTag<T>();
     }
Referenced by inet::SctpSocket::abort(), inet::SctpSocket::accept(), inet::SctpSocket::acceptSocket(), inet::SctpSocket::close(), inet::SctpSocket::connect(), inet::SctpSocket::destroy(), inet::sctp::SctpAssociation::generateSendQueueAbatedIndication(), inet::SctpSocket::getSocketOptions(), inet::NetPerfMeter::handleMessage(), inet::SctpNatServer::handleMessage(), inet::SctpServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::SctpNatServer::handleTimer(), inet::SctpServer::handleTimer(), inet::SctpPeer::handleTimer(), inet::SctpNatPeer::handleTimer(), inet::SctpSocket::listen(), inet::SctpServer::makeAbortNotification(), inet::SctpServer::makeDefaultReceive(), inet::sctp::SctpAssociation::pathStatusIndication(), inet::SctpSocket::requestStatus(), inet::sctp::SctpAssociation::sendAvailableIndicationToApp(), inet::sctp::SctpAssociation::sendDataArrivedNotification(), inet::sctp::SctpAssociation::sendEstabIndicationToApp(), inet::sctp::SctpAssociation::sendIndicationToApp(), inet::SctpNatServer::sendInfo(), inet::SctpClient::sendQueueRequest(), inet::SctpPeer::sendQueueRequest(), inet::SctpNatPeer::sendQueueRequest(), inet::NetPerfMeter::sendSCTPQueueRequest(), inet::SctpClient::sendStreamResetNotification(), inet::SctpClient::setPrimaryPath(), inet::SctpSocket::setRtoInfo(), inet::SctpSocket::setStreamPriority(), inet::SctpSocket::shutdown(), inet::SctpClient::shutdownReceivedArrived(), inet::SctpPeer::shutdownReceivedArrived(), inet::SctpNatPeer::shutdownReceivedArrived(), and inet::SctpNatPeer::socketEstablished().
addTagIfAbsent()
template<typename T > const Ptr<T> inet::Message::addTagIfAbsent () inline
Returns a newly added message tag for the provided type if absent, or returns the message tag that is already present.
{
         return tags.addTagIfAbsent<T>();
     }
Referenced by inet::SctpServer::sendOrSchedule().
clearTags()
void inet::Message::clearTags () inline
Clears the set of message tags.
                      {
         tags.clearTags();
     }
copyTags()
void inet::Message::copyTags (const Message & source) inline
Copies the set of message tags from the other message.
{
         tags.copyTags(source.tags);
     }
dup()
virtual Message* inet::Message::dup () const inline override virtual
Reimplemented in inet::Indication, and inet::Request.
 { return new Message(*this); }
findTag()
template<typename T > const Ptr<const T> inet::Message::findTag () const inline
Returns the message tag for the provided type or returns nullptr if no such message tag is found.
{
         return tags.findTag<T>();
     }
Referenced by inet::MessageDispatcher::handleMessage(), inet::SctpServer::handleMessage(), and inet::SctpClient::socketDataNotificationArrived().
findTagForUpdate()
template<typename T > const Ptr<T> inet::Message::findTagForUpdate () inline
Returns the message tag for the provided type or returns nullptr if no such message tag is found.
{
         return tags.findTagForUpdate<T>();
     }
getNumTags()
int inet::Message::getNumTags () const inline
Returns the number of message tags.
{
         return tags.getNumTags();
     }
getTag() [1/2]
template<typename T > const Ptr<const T> inet::Message::getTag () const inline
Returns the message tag for the provided type or throws an exception if no such message tag is found.
{
         return tags.getTag<T>();
     }
getTag() [2/2]
const Ptr<const TagBase> inet::Message::getTag (int index) const inline
Returns the message tag at the given index.
{
         return tags.getTag(index);
     }
Referenced by inet::EthernetSocketCommandProcessor::handleCommand(), inet::Ieee8022LlcSocketCommandProcessor::handleCommand(), inet::Ieee8021qSocketCommandProcessor::handleCommand(), inet::NextHopForwarding::handleCommand(), inet::NetPerfMeter::handleMessage(), inet::SctpNatServer::handleMessage(), inet::SctpServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::Ipv4Encap::handleRequest(), inet::Ipv6::handleRequest(), inet::Ipv4::handleRequest(), inet::NetworkProtocolBase::handleUpperCommand(), inet::Ieee8022Llc::processCommandFromHigherLayer(), and inet::EthernetEncapsulation::processCommandFromHigherLayer().
getTagForUpdate()
template<typename T > const Ptr<T> inet::Message::getTagForUpdate () inline
Returns the message tag for the provided type or throws an exception if no such message tag is found.
{
         return tags.getTagForUpdate<T>();
     }
getTags()
virtual SharingTagSet& inet::Message::getTags () inline override virtual
Returns all tags.
Implements inet::ITaggedObject.
 { return tags; }
Referenced by inet::NetPerfMeter::handleMessage(), inet::SctpNatServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::SctpServer::makeReceiveRequest(), inet::SctpPeer::socketDataNotificationArrived(), and inet::SctpNatPeer::socketDataNotificationArrived().
printToStream()
std::ostream & inet::Message::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     std::string className = getClassName();
     auto index = className.rfind("::");
     if (index != std::string::npos)
         className = className.substr(index + 2);
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FAINT << "(" << className << ")" << EV_NORMAL;
     stream << EV_ITALIC << getName() << EV_NORMAL;
     return stream;
 }
removeTag()
template<typename T > const Ptr<T> inet::Message::removeTag () inline
Removes the message tag for the provided type, or throws an exception if no such message tag is found.
{
         return tags.removeTag<T>();
     }
removeTagIfPresent()
template<typename T > const Ptr<T> inet::Message::removeTagIfPresent () inline
Removes the message tag for the provided type if present, or returns nullptr if no such message tag is found.
{
         return tags.removeTagIfPresent<T>();
     }
Referenced by inet::EthernetEncapsulation::processCommandFromHigherLayer().
Friends And Related Function Documentation
MessageDescriptor
friend class MessageDescriptor friend
Member Data Documentation
tags
SharingTagSet inet::Message::tags protected
Referenced by copyTags().
The documentation for this class was generated from the following files:
Message.h
Message.cc