INET Framework for OMNeT++/OMNEST: inet::bgp::BgpUpdatePathAttributesAsPath Class Reference
inet::bgp::BgpUpdatePathAttributesAsPath Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:137 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpUpdatePathAttributesAsPath ()
BgpUpdatePathAttributesAsPath (const BgpUpdatePathAttributesAsPath &other)
virtual ~BgpUpdatePathAttributesAsPath ()
BgpUpdatePathAttributesAsPath & operator= (const BgpUpdatePathAttributesAsPath &other)
virtual BgpUpdatePathAttributesAsPath * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setValueArraySize (size_t size)
virtual size_t getValueArraySize () const
virtual const BgpAsPathSegment & getValue (size_t k) const
virtual BgpAsPathSegment & getValueForUpdate (size_t k)
virtual void setValue (size_t k, const BgpAsPathSegment &value)
virtual void insertValue (size_t k, const BgpAsPathSegment &value)
void insertValue (const BgpAsPathSegment &value)
virtual void appendValue (const BgpAsPathSegment &value)
virtual void eraseValue (size_t k)
Public Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
BgpUpdatePathAttributes ()
BgpUpdatePathAttributes (const BgpUpdatePathAttributes &other)
virtual ~BgpUpdatePathAttributes ()
BgpUpdatePathAttributes & operator= (const BgpUpdatePathAttributes &other)
virtual bool getOptionalBit () const
virtual void setOptionalBit (bool optionalBit)
virtual bool getTransitiveBit () const
virtual void setTransitiveBit (bool transitiveBit)
virtual bool getPartialBit () const
virtual void setPartialBit (bool partialBit)
virtual bool getExtendedLengthBit () const
virtual void setExtendedLengthBit (bool extendedLengthBit)
virtual unsigned short getReserved () const
virtual void setReserved (unsigned short reserved)
virtual BgpUpdateAttributeTypeCode getTypeCode () const
virtual void setTypeCode (BgpUpdateAttributeTypeCode typeCode)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const BgpUpdatePathAttributesAsPath &)=delete
Protected Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
bool operator== (const BgpUpdatePathAttributes &)=delete
Protected Attributes
BgpAsPathSegment * value = nullptr
size_t value_arraysize = 0
Protected Attributes inherited from inet::bgp::BgpUpdatePathAttributes
bool optionalBit = false
bool transitiveBit = false
bool partialBit = false
bool extendedLengthBit = false
unsigned short reserved = 0
BgpUpdateAttributeTypeCode typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1)
unsigned short length = 0
Private Member Functions
void copy (const BgpUpdatePathAttributesAsPath &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:137 by opp_msgtool.
// AS_PATH (RFC4271 Section 4.3, Type code 2):
class BgpUpdatePathAttributesAsPath extends BgpUpdatePathAttributes
{
    typeCode = AS_PATH;
    optionalBit = false;
    transitiveBit = true;
    length = 0;
    BgpAsPathSegment value[];
}
Constructor & Destructor Documentation
BgpUpdatePathAttributesAsPath() [1/2]
inet::bgp::BgpUpdatePathAttributesAsPath::BgpUpdatePathAttributesAsPath ()
BgpUpdatePathAttributesAsPath() [2/2]
inet::bgp::BgpUpdatePathAttributesAsPath::BgpUpdatePathAttributesAsPath (const BgpUpdatePathAttributesAsPath & other)
~BgpUpdatePathAttributesAsPath()
virtual inet::bgp::BgpUpdatePathAttributesAsPath::~BgpUpdatePathAttributesAsPath () virtual
Member Function Documentation
appendValue()
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::appendValue (const BgpAsPathSegment & value) virtual
copy()
void inet::bgp::BgpUpdatePathAttributesAsPath::copy (const BgpUpdatePathAttributesAsPath & other) private
dup()
virtual BgpUpdatePathAttributesAsPath* inet::bgp::BgpUpdatePathAttributesAsPath::dup () const inline override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
 {return new BgpUpdatePathAttributesAsPath(*this);}
eraseValue()
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::eraseValue (size_t k) virtual
getValue()
virtual const BgpAsPathSegment& inet::bgp::BgpUpdatePathAttributesAsPath::getValue (size_t k) const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getValueArraySize()
virtual size_t inet::bgp::BgpUpdatePathAttributesAsPath::getValueArraySize () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getValueForUpdate()
virtual BgpAsPathSegment& inet::bgp::BgpUpdatePathAttributesAsPath::getValueForUpdate (size_t k) inline virtual
 { return const_cast<BgpAsPathSegment&>(const_cast<BgpUpdatePathAttributesAsPath*>(this)->getValue(k));}
insertValue() [1/2]
void inet::bgp::BgpUpdatePathAttributesAsPath::insertValue (const BgpAsPathSegment & value) inline
 {appendValue(value);}
insertValue() [2/2]
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::insertValue (size_t k, const BgpAsPathSegment & value) virtual
operator=()
BgpUpdatePathAttributesAsPath& inet::bgp::BgpUpdatePathAttributesAsPath::operator= (const BgpUpdatePathAttributesAsPath & other)
operator==()
bool inet::bgp::BgpUpdatePathAttributesAsPath::operator== (const BgpUpdatePathAttributesAsPath &) protected delete
parsimPack()
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimUnpacking().
setValue()
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::setValue (size_t k, const BgpAsPathSegment & value) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setValueArraySize()
virtual void inet::bgp::BgpUpdatePathAttributesAsPath::setValueArraySize (size_t size) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
value
BgpAsPathSegment* inet::bgp::BgpUpdatePathAttributesAsPath::value = nullptr protected
value_arraysize
size_t inet::bgp::BgpUpdatePathAttributesAsPath::value_arraysize = 0 protected
The documentation for this class was generated from the following file:
BgpHeader_m.h