INET Framework for OMNeT++/OMNEST: inet::physicallayer::IArrival Class Reference
inet::physicallayer::IArrival Class Reference abstract
This interface represents the space and time coordinates of a transmission arriving at a receiver.
#include <IArrival.h>
Public Member Functions
virtual const simtime_t getStartPropagationTime () const =0
virtual const simtime_t getEndPropagationTime () const =0
virtual const simtime_t getStartTime () const =0
virtual const simtime_t getEndTime () const =0
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const =0
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const =0
virtual const simtime_t getPreambleStartTime () const =0
virtual const simtime_t getPreambleEndTime () const =0
virtual const simtime_t getHeaderStartTime () const =0
virtual const simtime_t getHeaderEndTime () const =0
virtual const simtime_t getDataStartTime () const =0
virtual const simtime_t getDataEndTime () const =0
virtual const Coord & getStartPosition () const =0
virtual const Coord & getEndPosition () const =0
virtual const Quaternion & getStartOrientation () const =0
virtual const Quaternion & getEndOrientation () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents the space and time coordinates of a transmission arriving at a receiver.
This interface is strictly immutable to safely support parallel computation.
Member Function Documentation
getDataEndTime()
virtual const simtime_t inet::physicallayer::IArrival::getDataEndTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getDataStartTime()
virtual const simtime_t inet::physicallayer::IArrival::getDataStartTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getEndOrientation()
virtual const Quaternion& inet::physicallayer::IArrival::getEndOrientation () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::ScalarAnalogModel::computeReception(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), and inet::physicallayer::UnitDiskAnalogModel::computeReception().
getEndPosition()
virtual const Coord& inet::physicallayer::IArrival::getEndPosition () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::ScalarAnalogModel::computeReception(), inet::physicallayer::UnitDiskAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::RadioMedium::isPotentialReceiver(), and inet::physicallayer::RadioMedium::receiveSignal().
getEndPropagationTime()
virtual const simtime_t inet::physicallayer::IArrival::getEndPropagationTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getEndTime() [1/2]
virtual const simtime_t inet::physicallayer::IArrival::getEndTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::ReferenceCommunicationCache::computeInterferingTransmissions(), inet::physicallayer::ScalarAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), inet::physicallayer::UnitDiskAnalogModel::computeReception(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::RadioMedium::isInterferingTransmission(), inet::physicallayer::RadioMedium::pickUpSignals(), and inet::physicallayer::RadioMedium::receiveSignal().
getEndTime() [2/2]
virtual const simtime_t inet::physicallayer::IArrival::getEndTime (IRadioSignal::SignalPart part) const pure virtual
Implemented in inet::physicallayer::Arrival.
getHeaderEndTime()
virtual const simtime_t inet::physicallayer::IArrival::getHeaderEndTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getHeaderStartTime()
virtual const simtime_t inet::physicallayer::IArrival::getHeaderStartTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getPreambleEndTime()
virtual const simtime_t inet::physicallayer::IArrival::getPreambleEndTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getPreambleStartTime()
virtual const simtime_t inet::physicallayer::IArrival::getPreambleStartTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
getStartOrientation()
virtual const Quaternion& inet::physicallayer::IArrival::getStartOrientation () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::ScalarAnalogModel::computeReception(), inet::physicallayer::UnitDiskAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), and inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower().
getStartPosition()
virtual const Coord& inet::physicallayer::IArrival::getStartPosition () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::PathLossBase::computePathLoss(), inet::physicallayer::TwoRayInterference::computePathLoss(), inet::physicallayer::ScalarAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::physicallayer::UnitDiskAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::TwoRayGroundReflection::initialize(), inet::physicallayer::RadioMedium::isPotentialReceiver(), inet::physicallayer::RadioMedium::pickUpSignals(), inet::physicallayer::RadioMedium::receiveSignal(), and inet::physicallayer::RadioMedium::sendToRadio().
getStartPropagationTime()
virtual const simtime_t inet::physicallayer::IArrival::getStartPropagationTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::RadioMedium::pickUpSignals(), and inet::physicallayer::RadioMedium::sendToRadio().
getStartTime() [1/2]
virtual const simtime_t inet::physicallayer::IArrival::getStartTime () const pure virtual
Implemented in inet::physicallayer::Arrival.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::ScalarAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::UnitDiskAnalogModel::computeReception(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::RadioMedium::isInterferingTransmission(), inet::physicallayer::RadioMedium::pickUpSignals(), and inet::physicallayer::RadioMedium::receiveSignal().
getStartTime() [2/2]
virtual const simtime_t inet::physicallayer::IArrival::getStartTime (IRadioSignal::SignalPart part) const pure virtual
Implemented in inet::physicallayer::Arrival.
The documentation for this class was generated from the following file:
IArrival.h