INET Framework for OMNeT++/OMNEST: inet::sctp::SctpResetTimer Class Reference
inet::sctp::SctpResetTimer Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:286 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpResetTimer (const char *name=nullptr)
SctpResetTimer (const SctpResetTimer &other)
virtual ~SctpResetTimer ()
SctpResetTimer & operator= (const SctpResetTimer &other)
virtual SctpResetTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getInSN () const
virtual void setInSN (uint32_t inSN)
virtual bool getInAcked () const
virtual void setInAcked (bool inAcked)
virtual uint32_t getOutSN () const
virtual void setOutSN (uint32_t outSN)
virtual bool getOutAcked () const
virtual void setOutAcked (bool outAcked)
Protected Member Functions
bool operator== (const SctpResetTimer &)=delete
Protected Attributes
uint32_t inSN = 0
bool inAcked = false
uint32_t outSN = 0
bool outAcked = false
Private Member Functions
void copy (const SctpResetTimer &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:286 by opp_msgtool.
class SctpResetTimer extends cPacket
{
    uint32_t inSN; //Stream Reset Response Sequence Number for Incoming Reset Request
    bool inAcked;   // false, when timer is running for the Reset Response Sequence Number, true otherwise
    uint32_t outSN; //Stream Reset Response Sequence Number for Outgoing Reset Request
    bool outAcked;
}
Constructor & Destructor Documentation
SctpResetTimer() [1/2]
inet::sctp::SctpResetTimer::SctpResetTimer (const char * name = nullptr)
SctpResetTimer() [2/2]
inet::sctp::SctpResetTimer::SctpResetTimer (const SctpResetTimer & other)
~SctpResetTimer()
virtual inet::sctp::SctpResetTimer::~SctpResetTimer () virtual
Member Function Documentation
copy()
void inet::sctp::SctpResetTimer::copy (const SctpResetTimer & other) private
dup()
virtual SctpResetTimer* inet::sctp::SctpResetTimer::dup () const inline override virtual
 {return new SctpResetTimer(*this);}
getInAcked()
virtual bool inet::sctp::SctpResetTimer::getInAcked () const virtual
Referenced by inet::sctp::SctpAssociation::processOutgoingResetRequestArrived().
getInSN()
virtual uint32_t inet::sctp::SctpResetTimer::getInSN () const virtual
Referenced by inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), and inet::sctp::SctpAssociation::processResetResponseArrived().
getOutAcked()
virtual bool inet::sctp::SctpResetTimer::getOutAcked () const virtual
Referenced by inet::sctp::SctpAssociation::processOutgoingResetRequestArrived().
getOutSN()
virtual uint32_t inet::sctp::SctpResetTimer::getOutSN () const virtual
Referenced by inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), and inet::sctp::SctpAssociation::processResetResponseArrived().
operator=()
SctpResetTimer& inet::sctp::SctpResetTimer::operator= (const SctpResetTimer & other)
operator==()
bool inet::sctp::SctpResetTimer::operator== (const SctpResetTimer &) protected delete
parsimPack()
virtual void inet::sctp::SctpResetTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpResetTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::sctp::doParsimUnpacking().
setInAcked()
virtual void inet::sctp::SctpResetTimer::setInAcked (bool inAcked) virtual
setInSN()
virtual void inet::sctp::SctpResetTimer::setInSN (uint32_t inSN) virtual
setOutAcked()
virtual void inet::sctp::SctpResetTimer::setOutAcked (bool outAcked) virtual
setOutSN()
virtual void inet::sctp::SctpResetTimer::setOutSN (uint32_t outSN) virtual
Member Data Documentation
inAcked
bool inet::sctp::SctpResetTimer::inAcked = false protected
inSN
uint32_t inet::sctp::SctpResetTimer::inSN = 0 protected
outAcked
bool inet::sctp::SctpResetTimer::outAcked = false protected
outSN
uint32_t inet::sctp::SctpResetTimer::outSN = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h