INET Framework for OMNeT++/OMNEST: inet::physicallayer::ISignalBitModel Class Reference
inet::physicallayer::ISignalBitModel Class Reference abstract
This purely virtual interface provides an abstraction for different radio signal models in the bit domain.
#include <ISignalBitModel.h>
Public Member Functions
virtual b getHeaderLength () const =0
virtual bps getHeaderBitRate () const =0
Returns the gross (physical) bitrate of the PHY frame header.
virtual b getDataLength () const =0
virtual bps getDataBitRate () const =0
Returns the gross (physical) bitrate of the PHY frame data.
virtual const BitVector * getBits () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This purely virtual interface provides an abstraction for different radio signal models in the bit domain.
Member Function Documentation
getBits()
virtual const BitVector* inet::physicallayer::ISignalBitModel::getBits () const pure virtual
Implemented in inet::physicallayer::SignalBitModel.
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldBitModel(), inet::physicallayer::ApskDecoder::decode(), inet::physicallayer::Ieee80211OfdmDecoder::decode(), inet::physicallayer::ApskModulator::modulate(), and inet::physicallayer::Ieee80211OfdmModulator::modulate().
getDataBitRate()
virtual bps inet::physicallayer::ISignalBitModel::getDataBitRate () const pure virtual
Returns the gross (physical) bitrate of the PHY frame data.
Implemented in inet::physicallayer::SignalBitModel.
Referenced by inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::ApskLayeredErrorModel::computePacketModel(), inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel().
getDataLength()
virtual b inet::physicallayer::ISignalBitModel::getDataLength () const pure virtual
Implemented in inet::physicallayer::SignalBitModel.
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel().
getHeaderBitRate()
virtual bps inet::physicallayer::ISignalBitModel::getHeaderBitRate () const pure virtual
Returns the gross (physical) bitrate of the PHY frame header.
Implemented in inet::physicallayer::SignalBitModel.
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldBitModel().
getHeaderLength()
virtual b inet::physicallayer::ISignalBitModel::getHeaderLength () const pure virtual
Implemented in inet::physicallayer::SignalBitModel.
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel().
The documentation for this class was generated from the following file:
ISignalBitModel.h