INET Framework for OMNeT++/OMNEST: inet::ieee80211::ReceiveBuffer Class Reference
inet::ieee80211::ReceiveBuffer Class Reference
#include <ReceiveBuffer.h>
Public Types
typedef std::vector< Packet * > Fragments
typedef std::map< SequenceNumber, Fragments > ReorderBuffer
Public Member Functions
ReceiveBuffer (int bufferSize, SequenceNumberCyclic nextExpectedSequenceNumber)
virtual ~ReceiveBuffer ()
bool insertFrame (Packet *dataPacket, const Ptr< const Ieee80211DataHeader > &dataHeader)
void dropFramesUntil (SequenceNumberCyclic sequenceNumber)
void removeFrame (SequenceNumberCyclic sequenceNumber)
const ReorderBuffer & getBuffer ()
int getLength ()
int getBufferSize ()
SequenceNumberCyclic getNextExpectedSequenceNumber ()
void setNextExpectedSequenceNumber (SequenceNumberCyclic nextExpectedSequenceNumber)
bool isFull ()
Protected Attributes
ReorderBuffer buffer
int bufferSize = -1
int length = 0
SequenceNumberCyclic nextExpectedSequenceNumber
Member Typedef Documentation
Fragments
typedef std::vector<Packet *> inet::ieee80211::ReceiveBuffer::Fragments
ReorderBuffer
typedef std::map<SequenceNumber, Fragments> inet::ieee80211::ReceiveBuffer::ReorderBuffer
Constructor & Destructor Documentation
ReceiveBuffer()
inet::ieee80211::ReceiveBuffer::ReceiveBuffer (int bufferSize, SequenceNumberCyclic nextExpectedSequenceNumber)
                                                                                             :
     bufferSize(bufferSize),
     nextExpectedSequenceNumber(nextExpectedSequenceNumber)
 {
 }
~ReceiveBuffer()
inet::ieee80211::ReceiveBuffer::~ReceiveBuffer () virtual
 {
     for (auto fragments : buffer) {
         for (auto fragment : fragments.second)
             delete fragment;
     }
 }
Member Function Documentation
dropFramesUntil()
void inet::ieee80211::ReceiveBuffer::dropFramesUntil (SequenceNumberCyclic sequenceNumber)
 {
     auto it = buffer.begin();
     while (it != buffer.end()) {
         if (SequenceNumberCyclic(it->first) < sequenceNumber) {
             length -= it->second.size();
             for (auto fragment : it->second)
                 delete fragment;
             it = buffer.erase(it);
         }
         else
             it++;
     }
 }
Referenced by inet::ieee80211::BlockAckReordering::passedUp().
getBuffer()
const ReorderBuffer& inet::ieee80211::ReceiveBuffer::getBuffer () inline
 { return buffer; }
Referenced by inet::ieee80211::BlockAckReordering::addMsduIfComplete(), inet::ieee80211::BlockAckReordering::collectCompletePrecedingMpdus(), and inet::ieee80211::BlockAckReordering::getEarliestCompleteMsduOrAMsduIfExists().
getBufferSize()
int inet::ieee80211::ReceiveBuffer::getBufferSize () inline
 { return bufferSize; }
Referenced by inet::ieee80211::BlockAckReordering::collectConsecutiveCompleteFollowingMpdus().
getLength()
int inet::ieee80211::ReceiveBuffer::getLength () inline
 { return length; }
getNextExpectedSequenceNumber()
SequenceNumberCyclic inet::ieee80211::ReceiveBuffer::getNextExpectedSequenceNumber () inline
 { return nextExpectedSequenceNumber; }
Referenced by inet::ieee80211::BlockAckReordering::processReceivedBlockAckReq(), and inet::ieee80211::BlockAckReordering::processReceivedQoSFrame().
insertFrame()
bool inet::ieee80211::ReceiveBuffer::insertFrame (Packet * dataPacket, const Ptr< const Ieee80211DataHeader > & dataHeader)
 {
     auto sequenceNumber = dataHeader->getSequenceNumber();
     auto fragmentNumber = dataHeader->getFragmentNumber();
     // The total number of MPDUs in these MSDUs may not
     // exceed the reorder buffer size in the receiver.
     if (length < bufferSize && nextExpectedSequenceNumber <= sequenceNumber && sequenceNumber < nextExpectedSequenceNumber + bufferSize) {
         auto it = buffer.find(sequenceNumber.get());
         if (it != buffer.end()) {
             auto& fragments = it->second;
             // TODO efficiency
             for (auto fragment : fragments) {
                 const auto& fragmentHeader = fragment->peekAtFront<Ieee80211DataHeader>();
                 if (fragmentHeader->getSequenceNumber() == sequenceNumber && fragmentHeader->getFragmentNumber() == fragmentNumber)
                     return false;
             }
             fragments.push_back(dataPacket);
         }
         else {
             buffer[sequenceNumber.get()].push_back(dataPacket);
         }
         // The total number of frames that can be sent depends on the total
         // number of MPDUs in all the outstanding MSDUs.
         length++;
         return true;
     }
     return false;
 }
Referenced by inet::ieee80211::BlockAckReordering::processReceivedQoSFrame().
isFull()
bool inet::ieee80211::ReceiveBuffer::isFull () inline
 { ASSERT(length <= bufferSize); return length == bufferSize; }
Referenced by inet::ieee80211::BlockAckReordering::processReceivedQoSFrame().
removeFrame()
void inet::ieee80211::ReceiveBuffer::removeFrame (SequenceNumberCyclic sequenceNumber)
 {
     auto it = buffer.find(sequenceNumber.get());
     if (it != buffer.end()) {
         length -= it->second.size();
         buffer.erase(sequenceNumber.get());
     }
     else
         throw cRuntimeError("Unknown sequence number: %d", sequenceNumber.get());
 }
Referenced by inet::ieee80211::BlockAckReordering::passedUp().
setNextExpectedSequenceNumber()
void inet::ieee80211::ReceiveBuffer::setNextExpectedSequenceNumber (SequenceNumberCyclic nextExpectedSequenceNumber) inline
 { this->nextExpectedSequenceNumber = nextExpectedSequenceNumber; }
Referenced by inet::ieee80211::BlockAckReordering::passedUp(), and inet::ieee80211::BlockAckReordering::processReceivedBlockAckReq().
Member Data Documentation
buffer
ReorderBuffer inet::ieee80211::ReceiveBuffer::buffer protected
Referenced by dropFramesUntil(), insertFrame(), removeFrame(), and ~ReceiveBuffer().
bufferSize
int inet::ieee80211::ReceiveBuffer::bufferSize = -1 protected
Referenced by insertFrame().
length
int inet::ieee80211::ReceiveBuffer::length = 0 protected
Referenced by dropFramesUntil(), insertFrame(), and removeFrame().
nextExpectedSequenceNumber
SequenceNumberCyclic inet::ieee80211::ReceiveBuffer::nextExpectedSequenceNumber protected
Referenced by insertFrame().
The documentation for this class was generated from the following files:
ReceiveBuffer.h
ReceiveBuffer.cc