INET Framework for OMNeT++/OMNEST: inet::rtp::RtpSenderInfo Class Reference
inet::rtp::RtpSenderInfo Class Reference
The class RtpSenderInfo is used by an Rtp end system for storing information about itself.
#include <RtpSenderInfo.h>
Public Member Functions
RtpSenderInfo (uint32_t ssrc=0)
Default constructor.
RtpSenderInfo (const RtpSenderInfo &senderInfo)
Copy constructor.
virtual ~RtpSenderInfo ()
Destructor.
RtpSenderInfo & operator= (const RtpSenderInfo &senderInfo)
Assignment operator.
virtual RtpSenderInfo * dup () const override
Duplicates this RtpSenderInfo by calling the copy constructor.
virtual void processRTPPacket (Packet *packet, int id, simtime_t arrivalTime) override
Stores information about this outgoing RtpPacket.
virtual void processReceptionReport (const ReceptionReport *report, simtime_t arrivalTime)
Processes an incoming ReceptionReport for this sender.
virtual SenderReport * senderReport (simtime_t now) override
Returns a SenderReport for this rtp endsystem.
virtual void setStartTime (simtime_t startTime)
Sets the time (simTime) when this endsystem has started sending rtp packets.
virtual void setClockRate (int clockRate)
Sets the clock rate (in ticks per second) this sender increases the rtp time stamp.
virtual void setTimeStampBase (uint32_t timeStampBase)
Sets the initial rtp time stamp.
virtual void setSequenceNumberBase (uint16_t sequenceNumberBase)
Sets the initial sequence number.
Public Member Functions inherited from inet::rtp::RtpParticipantInfo
RtpParticipantInfo (uint32_t ssrc=0)
Default constructor.
RtpParticipantInfo (const RtpParticipantInfo &participantInfo)
Copy constructor.
virtual ~RtpParticipantInfo ()
Destructor.
RtpParticipantInfo & operator= (const RtpParticipantInfo &participantInfo)
Assignment operator.
virtual void processSenderReport (const SenderReport &report, simtime_t arrivalTime)
This method extracts information about an RTP endsystem as provided by the given SenderReport.
virtual void processReceptionReport (const ReceptionReport &report, simtime_t arrivalTime)
This method extracts information of the given ReceptionReport.
virtual void processSDESChunk (const SdesChunk *sdesChunk, simtime_t arrivalTime)
This method extracts sdes information of the given sdes chunk.and stores it.
virtual SdesChunk * getSDESChunk () const
Returns a copy of the sdes chunk used for storing source description items about this system.
virtual void addSDESItem (SdesItem *sdesItem)
Adds this sdes item to the sdes chunk of this participant.
virtual ReceptionReport * receptionReport (simtime_t now)
This method is intended to be overwritten by subclasses.
virtual void nextInterval (simtime_t now)
This method should be called by the rtcp module which uses this class for storing information every time an rtcp packet is sent.
virtual bool toBeDeleted (simtime_t now)
Returns true if the end system does no longer participate in the RTP session.
virtual bool isSender () const
Returns true if this endsystem has sent at least one RTP data packet during the last two rtcp intervals (including the current one).
virtual uint32_t getSsrc () const override
Returns the ssrc identifier of the RTP endsystem.
virtual void setSsrc (uint32_t ssrc) override
Sets the ssrc identifier.
virtual void addSDESItem (SdesItem::SdesItemType type, const char *content)
Creates a new SdesItem and adds it to the SdesChunk stored in this RtpParticipantInfo.
virtual void parsimPack (cCommBuffer *b) const override
virtual void parsimUnpack (cCommBuffer *b) override
Public Member Functions inherited from inet::rtp::RtpParticipantInfo_Base
virtual ~RtpParticipantInfo_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getAddress () const
virtual ::inet::Ipv4Address & getAddressForUpdate ()
virtual void setAddress (const ::inet::Ipv4Address &address)
virtual int getRTPPort () const
virtual void setRTPPort (int RTPPort)
virtual int getRTCPPort () const
virtual void setRTCPPort (int RTCPPort)
Protected Attributes
simtime_t _startTime
The time when the transmission was started.
int _clockRate
The clock rate this sender increases the rtp time stamp.
uint32_t _timeStampBase
The initial rtp time stamp.
uint16_t _sequenceNumberBase
The initial sequence number.
uint32_t _packetsSent
The number of rtp data packets this sender has sent.
uint32_t _bytesSent
The number of data bytes this sender has sent.
Protected Attributes inherited from inet::rtp::RtpParticipantInfo
SdesChunk _sdesChunk
Used for storing sdes information about this RTP endsystem.
int _silentIntervals
Stores the number of rtcp intervals (including the current one) during which this RTP endsystem hasn't sent any RTP data packets.
Protected Attributes inherited from inet::rtp::RtpParticipantInfo_Base
::inet::Ipv4Address address = Ipv4Address::UNSPECIFIED_ADDRESS
int RTPPort = PORT_UNDEF
int RTCPPort = PORT_UNDEF
Private Member Functions
void copy (const RtpSenderInfo &other)
Additional Inherited Members
Static Public Member Functions inherited from inet::rtp::RtpParticipantInfo
static std::string ssrcToName (uint32_t ssrc)
This method returns the given 32 bit ssrc identifier as an 8 character hexadecimal number which is used as name of an RtpParticipantInfo object.
Protected Member Functions inherited from inet::rtp::RtpParticipantInfo_Base
bool operator== (const RtpParticipantInfo_Base &)=delete
RtpParticipantInfo_Base (const char *name=nullptr)
RtpParticipantInfo_Base (const RtpParticipantInfo_Base &other)
RtpParticipantInfo_Base & operator= (const RtpParticipantInfo_Base &other)
Detailed Description
The class RtpSenderInfo is used by an Rtp end system for storing information about itself.
With the stored information it can create a SenderReport.
Constructor & Destructor Documentation
RtpSenderInfo() [1/2]
inet::rtp::RtpSenderInfo::RtpSenderInfo (uint32_t ssrc = 0)
Default constructor.
                                           : RtpParticipantInfo(ssrc)
 {
     _startTime = 0.0;
     _clockRate = 0;
     _timeStampBase = 0;
     _sequenceNumberBase = 0;
     _packetsSent = 0;
     _bytesSent = 0;
 }
Referenced by dup().
RtpSenderInfo() [2/2]
inet::rtp::RtpSenderInfo::RtpSenderInfo (const RtpSenderInfo & senderInfo)
Copy constructor.
                                                             : RtpParticipantInfo(senderInfo)
 {
     copy(senderInfo);
 }
~RtpSenderInfo()
inet::rtp::RtpSenderInfo::~RtpSenderInfo () virtual
Destructor.
 {
 }
Member Function Documentation
copy()
void inet::rtp::RtpSenderInfo::copy (const RtpSenderInfo & other) private
 {
     RtpParticipantInfo::operator=(senderInfo);
     _startTime = senderInfo._startTime;
     _clockRate = senderInfo._clockRate;
     _timeStampBase = senderInfo._timeStampBase;
     _sequenceNumberBase = senderInfo._sequenceNumberBase;
     _packetsSent = senderInfo._packetsSent;
     _bytesSent = senderInfo._bytesSent;
 }
Referenced by operator=(), and RtpSenderInfo().
dup()
RtpSenderInfo * inet::rtp::RtpSenderInfo::dup () const override virtual
Duplicates this RtpSenderInfo by calling the copy constructor.
Reimplemented from inet::rtp::RtpParticipantInfo.
 {
     return new RtpSenderInfo(*this);
 }
operator=()
RtpSenderInfo & inet::rtp::RtpSenderInfo::operator= (const RtpSenderInfo & senderInfo)
Assignment operator.
 {
     if (this == &senderInfo)
         return *this;
     RtpParticipantInfo::operator=(senderInfo);
     copy(senderInfo);
     return *this;
 }
processReceptionReport()
void inet::rtp::RtpSenderInfo::processReceptionReport (const ReceptionReport * report, simtime_t arrivalTime) virtual
Processes an incoming ReceptionReport for this sender.
 {
 }
Referenced by inet::rtp::Rtcp::processIncomingRTCPReceiverReportPacket(), and inet::rtp::Rtcp::processIncomingRTCPSenderReportPacket().
processRTPPacket()
void inet::rtp::RtpSenderInfo::processRTPPacket (Packet * packet, int id, simtime_t arrivalTime) override virtual
Stores information about this outgoing RtpPacket.
Reimplemented from inet::rtp::RtpParticipantInfo.
 {
     const auto& rtpHeader = packet->peekAtFront<RtpHeader>();
     _packetsSent++;
     _bytesSent = _bytesSent + packet->getByteLength() - B(rtpHeader->getChunkLength()).get();
     // call corresponding method of superclass
     // for setting _silentIntervals
     // it deletes the packet !!!
     RtpParticipantInfo::processRTPPacket(packet, id, arrivalTime);
 }
Referenced by inet::rtp::Rtcp::processOutgoingRTPPacket().
senderReport()
SenderReport * inet::rtp::RtpSenderInfo::senderReport (simtime_t now) override virtual
Returns a SenderReport for this rtp endsystem.
If it hasn't sent rtp data packets during the last 2 rtcp intervals, it returns nullptr.
Reimplemented from inet::rtp::RtpParticipantInfo.
 {
     if (isSender()) {
         SenderReport *senderReport = new SenderReport();
         // ntp time stamp is 64 bit integer
         uint64_t ntpSeconds = (uint64_t)SIMTIME_DBL(now);
         uint64_t ntpFraction = (uint64_t)((SIMTIME_DBL(now) - ntpSeconds * 65536.0) * 65536.0);
         senderReport->setNTPTimeStamp((uint64_t)(ntpSeconds << 32) + ntpFraction);
         senderReport->setRTPTimeStamp(SIMTIME_DBL(now - _startTime) * _clockRate);
         senderReport->setPacketCount(_packetsSent);
         senderReport->setByteCount(_bytesSent);
         return senderReport;
     }
     else {
         return nullptr;
     }
 }
Referenced by inet::rtp::Rtcp::createPacket().
setClockRate()
void inet::rtp::RtpSenderInfo::setClockRate (int clockRate) virtual
Sets the clock rate (in ticks per second) this sender increases the rtp time stamp.
 {
     _clockRate = clockRate;
 }
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
setSequenceNumberBase()
void inet::rtp::RtpSenderInfo::setSequenceNumberBase (uint16_t sequenceNumberBase) virtual
Sets the initial sequence number.
 {
     _sequenceNumberBase = sequenceNumberBase;
 }
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
setStartTime()
void inet::rtp::RtpSenderInfo::setStartTime (simtime_t startTime) virtual
Sets the time (simTime) when this endsystem has started sending rtp packets.
 {
     _startTime = startTime;
 }
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
setTimeStampBase()
void inet::rtp::RtpSenderInfo::setTimeStampBase (uint32_t timeStampBase) virtual
Sets the initial rtp time stamp.
 {
     _timeStampBase = timeStampBase;
 }
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
Member Data Documentation
_bytesSent
uint32_t inet::rtp::RtpSenderInfo::_bytesSent protected
The number of data bytes this sender has sent.
Referenced by copy(), processRTPPacket(), RtpSenderInfo(), and senderReport().
_clockRate
int inet::rtp::RtpSenderInfo::_clockRate protected
The clock rate this sender increases the rtp time stamp.
Referenced by copy(), RtpSenderInfo(), senderReport(), and setClockRate().
_packetsSent
uint32_t inet::rtp::RtpSenderInfo::_packetsSent protected
The number of rtp data packets this sender has sent.
Referenced by copy(), processRTPPacket(), RtpSenderInfo(), and senderReport().
_sequenceNumberBase
uint16_t inet::rtp::RtpSenderInfo::_sequenceNumberBase protected
The initial sequence number.
Referenced by copy(), RtpSenderInfo(), and setSequenceNumberBase().
_startTime
simtime_t inet::rtp::RtpSenderInfo::_startTime protected
The time when the transmission was started.
Referenced by copy(), RtpSenderInfo(), senderReport(), and setStartTime().
_timeStampBase
uint32_t inet::rtp::RtpSenderInfo::_timeStampBase protected
The initial rtp time stamp.
Referenced by copy(), RtpSenderInfo(), and setTimeStampBase().
The documentation for this class was generated from the following files:
RtpSenderInfo.h
RtpSenderInfo.cc