INET Framework for OMNeT++/OMNEST: inet::PacketDropDetails Class Reference
inet::PacketDropDetails Class Reference
Class generated from inet/common/Simsignals.msg:33 by opp_msgtool.
#include <Simsignals_m.h>
Public Member Functions
PacketDropDetails ()
PacketDropDetails (const PacketDropDetails &other)
virtual ~PacketDropDetails ()
PacketDropDetails & operator= (const PacketDropDetails &other)
virtual PacketDropDetails * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual PacketDropReason getReason () const
virtual void setReason (PacketDropReason reason)
virtual int getLimit () const
virtual void setLimit (int limit)
Protected Member Functions
bool operator== (const PacketDropDetails &)=delete
Protected Attributes
PacketDropReason reason = static_cast<inet::PacketDropReason>(-1)
int limit = -1
Private Member Functions
void copy (const PacketDropDetails &other)
Detailed Description
Class generated from inet/common/Simsignals.msg:33 by opp_msgtool.
class PacketDropDetails extends cObject
{
    PacketDropReason reason;
    int limit = -1;
}
Constructor & Destructor Documentation
PacketDropDetails() [1/2]
inet::PacketDropDetails::PacketDropDetails ()
PacketDropDetails() [2/2]
inet::PacketDropDetails::PacketDropDetails (const PacketDropDetails & other)
~PacketDropDetails()
virtual inet::PacketDropDetails::~PacketDropDetails () virtual
Member Function Documentation
copy()
void inet::PacketDropDetails::copy (const PacketDropDetails & other) private
dup()
virtual PacketDropDetails* inet::PacketDropDetails::dup () const inline override virtual
 {return new PacketDropDetails(*this);}
getLimit()
virtual int inet::PacketDropDetails::getLimit () const virtual
getReason()
virtual PacketDropReason inet::PacketDropDetails::getReason () const virtual
Referenced by inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), and inet::visualizer::PacketDropCanvasVisualizer::createPacketDropVisualization().
operator=()
PacketDropDetails& inet::PacketDropDetails::operator= (const PacketDropDetails & other)
operator==()
bool inet::PacketDropDetails::operator== (const PacketDropDetails &) protected delete
parsimPack()
virtual void inet::PacketDropDetails::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::PacketDropDetails::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setLimit()
virtual void inet::PacketDropDetails::setLimit (int limit) virtual
Referenced by inet::queueing::PacketProcessorBase::dropPacket(), inet::CsmaCaMac::emitPacketDropSignal(), inet::ieee80211::Hcf::handleInternalCollision(), inet::EthernetCsmaMac::handleRetransmission(), inet::Ieee802154Mac::manageMissingAck(), inet::ieee80211::Dcf::originatorProcessFailedFrame(), inet::ieee80211::Hcf::originatorProcessFailedFrame(), inet::ieee80211::Dcf::originatorProcessRtsProtectionFailed(), inet::ieee80211::Hcf::originatorProcessRtsProtectionFailed(), and inet::Ieee802154Mac::updateStatusCCA().
setReason()
virtual void inet::PacketDropDetails::setReason (PacketDropReason reason) virtual
Referenced by inet::Ipv4::arpResolutionTimedOut(), inet::CarrierBasedLifeTimer::clearCollection(), inet::ieee80211::RecipientQosMacDataService::dataFrameReceived(), inet::Ipv4::datagramLocalOut(), inet::ieee80211::RecipientMacDataService::dataOrMgmtFrameReceived(), inet::NetworkInterface::LocalGate::deliver(), inet::AckingMac::dropFrameNotForUs(), inet::EthernetMacBase::dropFrameNotForUs(), inet::queueing::PacketProcessorBase::dropPacket(), inet::CsmaCaMac::emitPacketDropSignal(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv4::fragmentAndSend(), inet::EthernetCsmaMac::frameReceptionComplete(), inet::Ipv4::handleIncomingDatagram(), inet::ieee80211::Hcf::handleInternalCollision(), inet::MacRelayUnit::handleLowerPacket(), inet::Ieee8021dRelay::handleLowerPacket(), inet::AckingMac::handleLowerPacket(), inet::Ppp::handleLowerPacket(), inet::BMac::handleLowerPacket(), inet::Ieee802154Mac::handleLowerPacket(), inet::LMac::handleLowerPacket(), inet::tcp::Tcp::handleLowerPacket(), inet::ieee80211::Ieee80211LlcEpd::handleMessage(), inet::Ipv6::handleMessageFromHL(), inet::NextHopForwarding::handlePacketFromHL(), inet::Ipv4::handlePacketFromHL(), inet::NextHopForwarding::handlePacketFromNetwork(), inet::EthernetCsmaMac::handleRetransmission(), inet::AckingMac::handleSelfMessage(), inet::BMac::handleSelfMessage(), inet::LMac::handleSelfMessage(), inet::EthernetCsmaMac::handleSignalFromNetwork(), inet::MacProtocolBase::handleStopOperation(), inet::EthernetMac::handleUpperPacket(), inet::Ppp::handleUpperPacket(), inet::ieee80211::Ieee80211Mac::handleUpperPacket(), inet::EthernetCsmaMac::handleUpperPacket(), inet::ieee80211::Rx::lowerFrameReceived(), inet::Ieee802154Mac::manageMissingAck(), inet::ieee80211::Dcf::originatorProcessFailedFrame(), inet::ieee80211::Hcf::originatorProcessFailedFrame(), inet::ieee80211::Dcf::originatorProcessRtsProtectionFailed(), inet::ieee80211::Hcf::originatorProcessRtsProtectionFailed(), inet::Ipv4::preroutingFinish(), inet::xMIPv6::processBRRMessage(), inet::EthernetMacBase::processConnectDisconnect(), inet::xMIPv6::processCoTMessage(), inet::ieee80211::Ds::processDataFrame(), inet::xMIPv6::processHoAOpt(), inet::xMIPv6::processHoTMessage(), inet::Icmp::processIcmpMessage(), inet::Udp::processICMPv4Error(), inet::Udp::processICMPv6Error(), inet::Icmpv6::processICMPv6Message(), inet::Igmpv2::processIgmpMessage(), inet::Igmpv3::processIgmpMessage(), inet::ieee80211::Dcf::processLowerFrame(), inet::ieee80211::Hcf::processLowerFrame(), inet::xMIPv6::processMobilityMessage(), inet::EthernetMac::processMsgFromNetwork(), inet::UdpBasicBurst::processPacket(), inet::Ieee8022Llc::processPacketFromMac(), inet::EthernetEncapsulation::processPacketFromMac(), inet::xMIPv6::processType2RH(), inet::Udp::processUDPPacket(), inet::Udp::processUndeliverablePacket(), inet::RelayInterfaceSelector::pushPacket(), inet::Ppp::refreshOutGateConnection(), inet::Ipv4::routeLocalBroadcastPacket(), inet::NextHopForwarding::routePacket(), inet::Ipv4::routeUnicastPacket(), inet::physicallayer::ApskRadio::sendUp(), inet::VoipStreamReceiver::socketDataArrived(), and inet::Ieee802154Mac::updateStatusCCA().
Member Data Documentation
limit
int inet::PacketDropDetails::limit = -1 protected
reason
PacketDropReason inet::PacketDropDetails::reason = static_cast<inet::PacketDropReason>(-1) protected
Referenced by inet::visualizer::PacketDrop::PacketDrop().
The documentation for this class was generated from the following file:
Simsignals_m.h