INET Framework for OMNeT++/OMNEST: inet::physicallayer::IPropagation Class Reference
inet::physicallayer::IPropagation Class Reference abstract
This interface models how a radio signal propagates through space over time.
#include <IPropagation.h>
Public Member Functions
virtual mps getPropagationSpeed () const =0
Returns the theoretical propagation speed of radio signals in the range (0, +infinity).
virtual const IArrival * computeArrival (const ITransmission *transmission, IMobility *mobility) const =0
Returns the time and space coordinates when the transmission arrives at the object that moves with the provided mobility.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface models how a radio signal propagates through space over time.
Member Function Documentation
computeArrival()
virtual const IArrival* inet::physicallayer::IPropagation::computeArrival (const ITransmission * transmission, IMobility * mobility) const pure virtual
Returns the time and space coordinates when the transmission arrives at the object that moves with the provided mobility.
The result might be an approximation only, because there's a tradeoff between precision and performance. This function never returns nullptr.
Implemented in inet::physicallayer::ConstantSpeedPropagation, and inet::physicallayer::ConstantTimePropagation.
Referenced by inet::physicallayer::RadioMedium::addRadio(), and inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight().
getPropagationSpeed()
virtual mps inet::physicallayer::IPropagation::getPropagationSpeed () const pure virtual
Returns the theoretical propagation speed of radio signals in the range (0, +infinity).
The value might be different from the approximation provided by the actual computation of arrival times.
Implemented in inet::physicallayer::PropagationBase.
Referenced by inet::physicallayer::MediumLimitCache::computeMaxRange(), and inet::physicallayer::FrequencyDependentAttenuationFunction::getValue().
The documentation for this class was generated from the following file:
IPropagation.h