INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211Channel Class Reference
inet::physicallayer::Ieee80211Channel Class Reference
#include <Ieee80211Channel.h>
Public Member Functions
Ieee80211Channel (const IIeee80211Band *band, int channelNumber)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IIeee80211Band * getBand () const
virtual int getChannelNumber () const
virtual Hz getCenterFrequency () const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const IIeee80211Band * band
int channelNumber
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211Channel()
inet::physicallayer::Ieee80211Channel::Ieee80211Channel (const IIeee80211Band * band, int channelNumber)
                                                                                 :
     band(band),
     channelNumber(channelNumber)
 {
 }
Member Function Documentation
getBand()
virtual const IIeee80211Band* inet::physicallayer::Ieee80211Channel::getBand () const inline virtual
 { return band; }
getCenterFrequency()
virtual Hz inet::physicallayer::Ieee80211Channel::getCenterFrequency () const inline virtual
 { return band->getCenterFrequency(channelNumber); }
Referenced by inet::physicallayer::Ieee80211ReceiverBase::setChannel(), and inet::physicallayer::Ieee80211TransmitterBase::setChannel().
getChannelNumber()
virtual int inet::physicallayer::Ieee80211Channel::getChannelNumber () const inline virtual
 { return channelNumber; }
Referenced by inet::physicallayer::Ieee80211ReceiverBase::setBand(), inet::physicallayer::Ieee80211TransmitterBase::setBand(), inet::physicallayer::Ieee80211Radio::setChannel(), inet::physicallayer::Ieee80211ReceiverBase::setChannelNumber(), and inet::physicallayer::Ieee80211TransmitterBase::setChannelNumber().
printToStream()
std::ostream & inet::physicallayer::Ieee80211Channel::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Ieee80211Channel";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(band, printFieldToString(band, level + 1, evFlags));
     if (level <= PRINT_LEVEL_INFO)
         stream << EV_FIELD(channelNumber);
     return stream;
 }
Member Data Documentation
band
const IIeee80211Band* inet::physicallayer::Ieee80211Channel::band protected
Referenced by printToStream().
channelNumber
int inet::physicallayer::Ieee80211Channel::channelNumber protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
Ieee80211Channel.h
Ieee80211Channel.cc