INET Framework for OMNeT++/OMNEST: inet::Ipv6NdPrefixInformation Class Reference
inet::Ipv6NdPrefixInformation Class Reference
Class generated from inet/networklayer/icmpv6/Ipv6NdMessage.msg:67 by opp_msgtool.
#include <Ipv6NdMessage_m.h>
Public Member Functions
Ipv6NdPrefixInformation ()
Ipv6NdPrefixInformation (const Ipv6NdPrefixInformation &other)
virtual ~Ipv6NdPrefixInformation ()
Ipv6NdPrefixInformation & operator= (const Ipv6NdPrefixInformation &other)
virtual Ipv6NdPrefixInformation * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getPrefixLength () const
virtual void setPrefixLength (unsigned short prefixLength)
virtual bool getOnlinkFlag () const
virtual void setOnlinkFlag (bool onlinkFlag)
virtual bool getAutoAddressConfFlag () const
virtual void setAutoAddressConfFlag (bool autoAddressConfFlag)
virtual bool getRouterAddressFlag () const
virtual void setRouterAddressFlag (bool routerAddressFlag)
virtual unsigned int getReserved1 () const
virtual void setReserved1 (unsigned int reserved1)
virtual uint32_t getValidLifetime () const
virtual void setValidLifetime (uint32_t validLifetime)
virtual uint32_t getPreferredLifetime () const
virtual void setPreferredLifetime (uint32_t preferredLifetime)
virtual uint32_t getReserved2 () const
virtual void setReserved2 (uint32_t reserved2)
virtual const Ipv6Address & getPrefix () const
virtual Ipv6Address & getPrefixForUpdate ()
virtual void setPrefix (const Ipv6Address &prefix)
Public Member Functions inherited from inet::Ipv6NdOption
Ipv6NdOption ()
Ipv6NdOption (const Ipv6NdOption &other)
virtual ~Ipv6NdOption ()
Ipv6NdOption & operator= (const Ipv6NdOption &other)
virtual Ipv6NdOptionTypes getType () const
virtual void setType (Ipv6NdOptionTypes type)
virtual short getOptionLength () const
virtual void setOptionLength (short optionLength)
virtual void setPaddingBytesArraySize (size_t size)
virtual size_t getPaddingBytesArraySize () const
virtual char getPaddingBytes (size_t k) const
virtual void setPaddingBytes (size_t k, char paddingBytes)
virtual void insertPaddingBytes (size_t k, char paddingBytes)
void insertPaddingBytes (char paddingBytes)
virtual void appendPaddingBytes (char paddingBytes)
virtual void erasePaddingBytes (size_t k)
Protected Member Functions
bool operator== (const Ipv6NdPrefixInformation &)=delete
Protected Member Functions inherited from inet::Ipv6NdOption
bool operator== (const Ipv6NdOption &)=delete
Protected Attributes
unsigned short prefixLength = 0
bool onlinkFlag = false
bool autoAddressConfFlag = false
bool routerAddressFlag = false
unsigned int reserved1 = 0
uint32_t validLifetime = 0
uint32_t preferredLifetime = 0
uint32_t reserved2 = 0
Ipv6Address prefix
Protected Attributes inherited from inet::Ipv6NdOption
Ipv6NdOptionTypes type = static_cast<Ipv6NdOptionTypes>(0)
short optionLength = 0
char * paddingBytes = nullptr
size_t paddingBytes_arraysize = 0
Private Member Functions
void copy (const Ipv6NdPrefixInformation &other)
Detailed Description
Class generated from inet/networklayer/icmpv6/Ipv6NdMessage.msg:67 by opp_msgtool.
//
// IPv6ND Prefix Information
// RFC 2461 / RFC 4861 Section 4.6.2
// RFC 3775 Section 7.2 (routerAddressFlag)
//
class Ipv6NdPrefixInformation extends Ipv6NdOption
{
    type = IPv6ND_PREFIX_INFORMATION;
    optionLength = 4;
    unsigned short prefixLength;    // 0..128
    bool onlinkFlag;        //L-bit
    bool autoAddressConfFlag;    //A-bit
    bool routerAddressFlag;        //R-bit: used in case of MIPv6 when the H-bit is set
    unsigned int reserved1 = 0;
    uint32_t validLifetime;    // seconds
    uint32_t preferredLifetime;    // seconds
    uint32_t reserved2 = 0;
    Ipv6Address prefix;
}
Constructor & Destructor Documentation
Ipv6NdPrefixInformation() [1/2]
inet::Ipv6NdPrefixInformation::Ipv6NdPrefixInformation ()
Ipv6NdPrefixInformation() [2/2]
inet::Ipv6NdPrefixInformation::Ipv6NdPrefixInformation (const Ipv6NdPrefixInformation & other)
~Ipv6NdPrefixInformation()
virtual inet::Ipv6NdPrefixInformation::~Ipv6NdPrefixInformation () virtual
Member Function Documentation
copy()
void inet::Ipv6NdPrefixInformation::copy (const Ipv6NdPrefixInformation & other) private
dup()
virtual Ipv6NdPrefixInformation* inet::Ipv6NdPrefixInformation::dup () const inline override virtual
Reimplemented from inet::Ipv6NdOption.
 {return new Ipv6NdPrefixInformation(*this);}
getAutoAddressConfFlag()
virtual bool inet::Ipv6NdPrefixInformation::getAutoAddressConfFlag () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPacket().
getOnlinkFlag()
virtual bool inet::Ipv6NdPrefixInformation::getOnlinkFlag () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPrefixInfo().
getPreferredLifetime()
virtual uint32_t inet::Ipv6NdPrefixInformation::getPreferredLifetime () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf().
getPrefix()
virtual const Ipv6Address& inet::Ipv6NdPrefixInformation::getPrefix () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfo(), and inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf().
getPrefixForUpdate()
virtual Ipv6Address& inet::Ipv6NdPrefixInformation::getPrefixForUpdate () inline virtual
 { return const_cast<Ipv6Address&>(const_cast<Ipv6NdPrefixInformation*>(this)->getPrefix());}
getPrefixLength()
virtual unsigned short inet::Ipv6NdPrefixInformation::getPrefixLength () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfo(), and inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf().
getReserved1()
virtual unsigned int inet::Ipv6NdPrefixInformation::getReserved1 () const virtual
getReserved2()
virtual uint32_t inet::Ipv6NdPrefixInformation::getReserved2 () const virtual
getRouterAddressFlag()
virtual bool inet::Ipv6NdPrefixInformation::getRouterAddressFlag () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPacket().
getValidLifetime()
virtual uint32_t inet::Ipv6NdPrefixInformation::getValidLifetime () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::processRaPrefixInfo(), and inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf().
operator=()
Ipv6NdPrefixInformation& inet::Ipv6NdPrefixInformation::operator= (const Ipv6NdPrefixInformation & other)
operator==()
bool inet::Ipv6NdPrefixInformation::operator== (const Ipv6NdPrefixInformation &) protected delete
parsimPack()
virtual void inet::Ipv6NdPrefixInformation::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::Ipv6NdOption.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6NdPrefixInformation::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::Ipv6NdOption.
Referenced by inet::doParsimUnpacking().
setAutoAddressConfFlag()
virtual void inet::Ipv6NdPrefixInformation::setAutoAddressConfFlag (bool autoAddressConfFlag) virtual
setOnlinkFlag()
virtual void inet::Ipv6NdPrefixInformation::setOnlinkFlag (bool onlinkFlag) virtual
setPreferredLifetime()
virtual void inet::Ipv6NdPrefixInformation::setPreferredLifetime (uint32_t preferredLifetime) virtual
setPrefix()
virtual void inet::Ipv6NdPrefixInformation::setPrefix (const Ipv6Address & prefix) virtual
setPrefixLength()
virtual void inet::Ipv6NdPrefixInformation::setPrefixLength (unsigned short prefixLength) virtual
setReserved1()
virtual void inet::Ipv6NdPrefixInformation::setReserved1 (unsigned int reserved1) virtual
setReserved2()
virtual void inet::Ipv6NdPrefixInformation::setReserved2 (uint32_t reserved2) virtual
setRouterAddressFlag()
virtual void inet::Ipv6NdPrefixInformation::setRouterAddressFlag (bool routerAddressFlag) virtual
setValidLifetime()
virtual void inet::Ipv6NdPrefixInformation::setValidLifetime (uint32_t validLifetime) virtual
Member Data Documentation
autoAddressConfFlag
bool inet::Ipv6NdPrefixInformation::autoAddressConfFlag = false protected
onlinkFlag
bool inet::Ipv6NdPrefixInformation::onlinkFlag = false protected
preferredLifetime
uint32_t inet::Ipv6NdPrefixInformation::preferredLifetime = 0 protected
prefix
Ipv6Address inet::Ipv6NdPrefixInformation::prefix protected
prefixLength
unsigned short inet::Ipv6NdPrefixInformation::prefixLength = 0 protected
reserved1
unsigned int inet::Ipv6NdPrefixInformation::reserved1 = 0 protected
reserved2
uint32_t inet::Ipv6NdPrefixInformation::reserved2 = 0 protected
routerAddressFlag
bool inet::Ipv6NdPrefixInformation::routerAddressFlag = false protected
validLifetime
uint32_t inet::Ipv6NdPrefixInformation::validLifetime = 0 protected
The documentation for this class was generated from the following file:
Ipv6NdMessage_m.h