INET Framework for OMNeT++/OMNEST: inet::sctp::SctpNatEntry Class Reference
inet::sctp::SctpNatEntry Class Reference
#include <SctpNatTable.h>
Public Member Functions
SctpNatEntry ()
~SctpNatEntry ()
void setLocalAddress (L3Address addr)
void setGlobalAddress (L3Address addr)
void setNattedAddress (L3Address addr)
void setLocalPort (uint16_t port)
void setGlobalPort (uint16_t port)
void setNattedPort (uint16_t port)
void setGlobalVTag (uint32_t tag)
void setLocalVTag (uint32_t tag)
void setEntryNumber (uint32_t number)
L3Address getLocalAddress ()
L3Address getGlobalAddress ()
L3Address getNattedAddress ()
uint16_t getLocalPort ()
uint16_t getGlobalPort ()
uint16_t getNattedPort ()
uint32_t getGlobalVTag ()
uint32_t getLocalVTag ()
Protected Attributes
uint32_t entryNumber
L3Address localAddress
L3Address globalAddress
L3Address nattedAddress
uint16_t localPort
uint16_t globalPort
uint16_t nattedPort
uint32_t globalVtag
uint32_t localVtag
Constructor & Destructor Documentation
SctpNatEntry()
inet::sctp::SctpNatEntry::SctpNatEntry ()
 {
     localAddress = L3Address();
     globalAddress = L3Address();
     nattedAddress = L3Address();
     localPort = 0;
     globalPort = 0;
     nattedPort = 0;
     globalVtag = 0;
     localVtag = 0;
     entryNumber = 0;
 }
~SctpNatEntry()
inet::sctp::SctpNatEntry::~SctpNatEntry ()
 {
 }
Member Function Documentation
getGlobalAddress()
L3Address inet::sctp::SctpNatEntry::getGlobalAddress () inline
 { return globalAddress; };
Referenced by inet::sctp::SctpNatHook::datagramPreRoutingHook(), and inet::sctp::SctpNatTable::removeEntry().
getGlobalPort()
uint16_t inet::sctp::SctpNatEntry::getGlobalPort () inline
 { return globalPort; };
Referenced by inet::sctp::SctpNatHook::datagramPreRoutingHook(), and inet::sctp::SctpNatTable::removeEntry().
getGlobalVTag()
uint32_t inet::sctp::SctpNatEntry::getGlobalVTag () inline
 { return globalVtag; };
Referenced by inet::sctp::SctpNatHook::datagramPreRoutingHook().
getLocalAddress()
L3Address inet::sctp::SctpNatEntry::getLocalAddress () inline
 { return localAddress; };
Referenced by inet::sctp::SctpNatHook::datagramPreRoutingHook().
getLocalPort()
uint16_t inet::sctp::SctpNatEntry::getLocalPort () inline
 { return localPort; };
Referenced by inet::sctp::SctpNatHook::datagramPreRoutingHook(), and inet::sctp::SctpNatTable::removeEntry().
getLocalVTag()
uint32_t inet::sctp::SctpNatEntry::getLocalVTag () inline
 { return localVtag; };
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatTable::removeEntry().
getNattedAddress()
L3Address inet::sctp::SctpNatEntry::getNattedAddress () inline
 { return nattedAddress; };
getNattedPort()
uint16_t inet::sctp::SctpNatEntry::getNattedPort () inline
 { return nattedPort; };
Referenced by inet::sctp::SctpNatHook::datagramForwardHook().
setEntryNumber()
void inet::sctp::SctpNatEntry::setEntryNumber (uint32_t number) inline
 { entryNumber = number; }
setGlobalAddress()
void inet::sctp::SctpNatEntry::setGlobalAddress (L3Address addr) inline
 { globalAddress = addr; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setGlobalPort()
void inet::sctp::SctpNatEntry::setGlobalPort (uint16_t port) inline
 { globalPort = port; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setGlobalVTag()
void inet::sctp::SctpNatEntry::setGlobalVTag (uint32_t tag) inline
 { globalVtag = tag; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setLocalAddress()
void inet::sctp::SctpNatEntry::setLocalAddress (L3Address addr) inline
 { localAddress = addr; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setLocalPort()
void inet::sctp::SctpNatEntry::setLocalPort (uint16_t port) inline
 { localPort = port; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setLocalVTag()
void inet::sctp::SctpNatEntry::setLocalVTag (uint32_t tag) inline
 { localVtag = tag; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setNattedAddress()
void inet::sctp::SctpNatEntry::setNattedAddress (L3Address addr) inline
 { nattedAddress = addr; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
setNattedPort()
void inet::sctp::SctpNatEntry::setNattedPort (uint16_t port) inline
 { nattedPort = port; }
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), and inet::sctp::SctpNatHook::datagramPreRoutingHook().
Member Data Documentation
entryNumber
uint32_t inet::sctp::SctpNatEntry::entryNumber protected
Referenced by SctpNatEntry().
globalAddress
L3Address inet::sctp::SctpNatEntry::globalAddress protected
Referenced by SctpNatEntry().
globalPort
uint16_t inet::sctp::SctpNatEntry::globalPort protected
Referenced by SctpNatEntry().
globalVtag
uint32_t inet::sctp::SctpNatEntry::globalVtag protected
Referenced by SctpNatEntry().
localAddress
L3Address inet::sctp::SctpNatEntry::localAddress protected
Referenced by SctpNatEntry().
localPort
uint16_t inet::sctp::SctpNatEntry::localPort protected
Referenced by SctpNatEntry().
localVtag
uint32_t inet::sctp::SctpNatEntry::localVtag protected
Referenced by SctpNatEntry().
nattedAddress
L3Address inet::sctp::SctpNatEntry::nattedAddress protected
Referenced by SctpNatEntry().
nattedPort
uint16_t inet::sctp::SctpNatEntry::nattedPort protected
Referenced by SctpNatEntry().
The documentation for this class was generated from the following files:
SctpNatTable.h
SctpNatTable.cc