INET Framework for OMNeT++/OMNEST: inet::tcp::TcpCrcInsertionHook Class Reference
inet::tcp::TcpCrcInsertionHook Class Reference
#include <TcpCrcInsertionHook.h>
Public Member Functions
virtual Result datagramPreRoutingHook (Packet *packet) override
This is the first hook called by the network protocol before it routes a datagram that was received from the lower layer.
virtual Result datagramForwardHook (Packet *packet) override
This is the second hook called by the network protocol before it sends a datagram to the lower layer.
virtual Result datagramPostRoutingHook (Packet *packet) override
This is the last hook called by the network protocol before it sends a datagram to the lower layer.
virtual Result datagramLocalInHook (Packet *packet) override
This is the last hook called by the network protocol before it sends a datagram to the upper layer.
virtual Result datagramLocalOutHook (Packet *packet) override
This is the first hook called by the network protocol before it routes a datagram that was received from the upper layer.
Public Member Functions inherited from inet::NetfilterBase::HookBase
virtual ~HookBase ()
void registeredTo (INetfilter *nf)
void unregisteredFrom (INetfilter *nf)
bool isRegisteredHook (INetfilter *nf)
Public Member Functions inherited from inet::INetfilter::IHook
virtual ~IHook ()
Static Public Member Functions
static void insertCrc (const Protocol *networkProtocol, const L3Address &srcAddress, const L3Address &destAddress, const Ptr< TcpHeader > &tcpHeader, Packet *tcpPayload)
static uint16_t computeCrc (const Protocol *networkProtocol, const L3Address &srcAddress, const L3Address &destAddress, const Ptr< const TcpHeader > &tcpHeader, const Ptr< const Chunk > &tcpData)
Additional Inherited Members
Public Types inherited from inet::INetfilter::IHook
enum Type {
PREROUTING, LOCALIN, FORWARD, POSTROUTING,
LOCALOUT
}
enum Result { ACCEPT, DROP, QUEUE, STOLEN }
Protected Attributes inherited from inet::NetfilterBase::HookBase
std::vector< INetfilter * > netfilters
Member Function Documentation
computeCrc()
uint16_t inet::tcp::TcpCrcInsertionHook::computeCrc (const Protocol * networkProtocol, const L3Address & srcAddress, const L3Address & destAddress, const Ptr< const TcpHeader > & tcpHeader, const Ptr< const Chunk > & tcpData) static
 {
     auto pseudoHeader = makeShared<TransportPseudoHeader>();
     pseudoHeader->setSrcAddress(srcAddress);
     pseudoHeader->setDestAddress(destAddress);
     pseudoHeader->setNetworkProtocolId(networkProtocol->getId());
     pseudoHeader->setProtocolId(IP_PROT_TCP);
     pseudoHeader->setPacketLength(tcpHeader->getChunkLength() + tcpData->getChunkLength());
     // pseudoHeader length: ipv4: 12 bytes, ipv6: 40 bytes, generic: ???
     if (networkProtocol == &Protocol::ipv4)
         pseudoHeader->setChunkLength(B(12));
     else if (networkProtocol == &Protocol::ipv6)
         pseudoHeader->setChunkLength(B(40));
     else
         throw cRuntimeError("Unknown network protocol: %s", networkProtocol->getName());
     MemoryOutputStream stream;
     Chunk::serialize(stream, pseudoHeader);
     Chunk::serialize(stream, tcpHeader);
     Chunk::serialize(stream, tcpData);
     uint16_t crc = TcpIpChecksum::checksum(stream.getData());
     return crc;
 }
Referenced by insertCrc().
datagramForwardHook()
virtual Result inet::tcp::TcpCrcInsertionHook::datagramForwardHook (Packet * datagram) inline override virtual
This is the second hook called by the network protocol before it sends a datagram to the lower layer.
This is done after the datagramPreRoutingHook or the datagramLocalInHook is called and the datagram is routed.
Implements inet::INetfilter::IHook.
 { return ACCEPT; }
datagramLocalInHook()
virtual Result inet::tcp::TcpCrcInsertionHook::datagramLocalInHook (Packet * datagram) inline override virtual
This is the last hook called by the network protocol before it sends a datagram to the upper layer.
This is done after the datagramPreRoutingHook is called and the datagram is routed.
Implements inet::INetfilter::IHook.
 { return ACCEPT; }
datagramLocalOutHook()
virtual Result inet::tcp::TcpCrcInsertionHook::datagramLocalOutHook (Packet * datagram) inline override virtual
This is the first hook called by the network protocol before it routes a datagram that was received from the upper layer.
The nextHopAddress is ignored when the outputNetworkInterface is a nullptr. After this is done
Implements inet::INetfilter::IHook.
 { return ACCEPT; }
datagramPostRoutingHook()
INetfilter::IHook::Result inet::tcp::TcpCrcInsertionHook::datagramPostRoutingHook (Packet * datagram) override virtual
This is the last hook called by the network protocol before it sends a datagram to the lower layer.
Implements inet::INetfilter::IHook.
 {
     Enter_Method("datagramPostRoutingHook");
     if (packet->findTag<InterfaceInd>())
         return ACCEPT; // FORWARD
     auto networkProtocol = packet->getTag<PacketProtocolTag>()->getProtocol();
     const auto& networkHeader = getNetworkProtocolHeader(packet);
     if (networkHeader->getProtocol() == &Protocol::tcp) {
         ASSERT(!networkHeader->isFragment());
         packet->eraseAtFront(networkHeader->getChunkLength());
         auto tcpHeader = packet->removeAtFront<TcpHeader>();
         ASSERT(tcpHeader->getCrcMode() == CRC_COMPUTED);
         const L3Address& srcAddress = networkHeader->getSourceAddress();
         const L3Address& destAddress = networkHeader->getDestinationAddress();
         insertCrc(networkProtocol, srcAddress, destAddress, tcpHeader, packet);
         packet->insertAtFront(tcpHeader);
         packet->insertAtFront(networkHeader);
     }
     return ACCEPT;
 }
datagramPreRoutingHook()
virtual Result inet::tcp::TcpCrcInsertionHook::datagramPreRoutingHook (Packet * datagram) inline override virtual
This is the first hook called by the network protocol before it routes a datagram that was received from the lower layer.
The nextHopAddress is ignored when the outputNetworkInterface is nullptr.
Implements inet::INetfilter::IHook.
 { return ACCEPT; }
insertCrc()
void inet::tcp::TcpCrcInsertionHook::insertCrc (const Protocol * networkProtocol, const L3Address & srcAddress, const L3Address & destAddress, const Ptr< TcpHeader > & tcpHeader, Packet * tcpPayload) static
 {
     auto crcMode = tcpHeader->getCrcMode();
     switch (crcMode) {
         case CRC_DECLARED_CORRECT:
             // if the CRC mode is declared to be correct, then set the CRC to an easily recognizable value
             tcpHeader->setCrc(0xC00D);
             break;
         case CRC_DECLARED_INCORRECT:
             // if the CRC mode is declared to be incorrect, then set the CRC to an easily recognizable value
             tcpHeader->setCrc(0xBAAD);
             break;
         case CRC_COMPUTED: {
             // if the CRC mode is computed, then compute the CRC and set it
             // this computation is delayed after the routing decision, see INetfilter hook
             tcpHeader->setCrc(0x0000); // make sure that the CRC is 0 in the TCP header before computing the CRC
             auto tcpData = packet->peekData(Chunk::PF_ALLOW_EMPTY);
             auto crc = computeCrc(networkProtocol, srcAddress, destAddress, tcpHeader, tcpData);
             tcpHeader->setCrc(crc);
             break;
         }
         default:
             throw cRuntimeError("Unknown CRC mode");
     }
 }
Referenced by datagramPostRoutingHook(), and inet::Ipv4NatTable::processPacket().
The documentation for this class was generated from the following files:
TcpCrcInsertionHook.h
TcpCrcInsertionHook.cc