INET Framework for OMNeT++/OMNEST: inet::rtp::RtpControlInfo Class Reference
inet::rtp::RtpControlInfo Class Reference
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:45 by opp_msgtool.
#include <RtpInterfacePacket_m.h>
Public Member Functions
RtpControlInfo ()
RtpControlInfo (const RtpControlInfo &other)
virtual ~RtpControlInfo ()
RtpControlInfo & operator= (const RtpControlInfo &other)
virtual RtpControlInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual RtpIfpType getType () const
virtual void setType (RtpIfpType type)
Protected Member Functions
bool operator== (const RtpControlInfo &)=delete
Protected Attributes
RtpIfpType type = static_cast<inet::rtp::RtpIfpType>(-1)
Private Member Functions
void copy (const RtpControlInfo &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:45 by opp_msgtool.
// base class
class RtpControlInfo extends cObject
{
    RtpIfpType type;
}
Constructor & Destructor Documentation
RtpControlInfo() [1/2]
inet::rtp::RtpControlInfo::RtpControlInfo ()
RtpControlInfo() [2/2]
inet::rtp::RtpControlInfo::RtpControlInfo (const RtpControlInfo & other)
~RtpControlInfo()
virtual inet::rtp::RtpControlInfo::~RtpControlInfo () virtual
Member Function Documentation
copy()
void inet::rtp::RtpControlInfo::copy (const RtpControlInfo & other) private
dup()
virtual RtpControlInfo* inet::rtp::RtpControlInfo::dup () const inline override virtual
Reimplemented in inet::rtp::RtpCiSenderModuleDeleted, inet::rtp::RtpCiDeleteSenderModule, inet::rtp::RtpCiSenderModuleCreated, inet::rtp::RtpCiCreateSenderModule, inet::rtp::RtpCiSessionLeft, inet::rtp::RtpCiLeaveSession, inet::rtp::RtpCiSenderStatus, inet::rtp::RtpCiSenderControl, inet::rtp::RtpCiSessionEntered, inet::rtp::RtpCiEnterSession, and inet::rtp::RtpSessionControlInfo.
 {return new RtpControlInfo(*this);}
getType()
virtual RtpIfpType inet::rtp::RtpControlInfo::getType () const virtual
Referenced by inet::rtp::Rtp::handleMessageFromApp().
operator=()
RtpControlInfo& inet::rtp::RtpControlInfo::operator= (const RtpControlInfo & other)
operator==()
bool inet::rtp::RtpControlInfo::operator== (const RtpControlInfo &) protected delete
parsimPack()
virtual void inet::rtp::RtpControlInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::rtp::RtpCiSenderModuleDeleted, inet::rtp::RtpCiDeleteSenderModule, inet::rtp::RtpCiSenderModuleCreated, inet::rtp::RtpCiCreateSenderModule, inet::rtp::RtpCiSessionLeft, inet::rtp::RtpCiLeaveSession, inet::rtp::RtpCiSenderStatus, inet::rtp::RtpCiSenderControl, inet::rtp::RtpCiSessionEntered, inet::rtp::RtpCiEnterSession, and inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpControlInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::rtp::RtpCiSenderModuleDeleted, inet::rtp::RtpCiDeleteSenderModule, inet::rtp::RtpCiSenderModuleCreated, inet::rtp::RtpCiCreateSenderModule, inet::rtp::RtpCiSessionLeft, inet::rtp::RtpCiLeaveSession, inet::rtp::RtpCiSenderStatus, inet::rtp::RtpCiSenderControl, inet::rtp::RtpCiSessionEntered, inet::rtp::RtpCiEnterSession, and inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimUnpacking().
setType()
virtual void inet::rtp::RtpControlInfo::setType (RtpIfpType type) virtual
Member Data Documentation
type
RtpIfpType inet::rtp::RtpControlInfo::type = static_cast<inet::rtp::RtpIfpType>(-1) protected
The documentation for this class was generated from the following file:
RtpInterfacePacket_m.h