INET Framework for OMNeT++/OMNEST: inet::TcpIpChecksum Class Reference
inet::TcpIpChecksum Class Reference
Calculates checksum.
#include <TcpIpChecksum.h>
Public Member Functions
TcpIpChecksum ()
Static Public Member Functions
static uint16_t checksum (const void *addr, unsigned int count)
static uint16_t _checksum (const void *addr, unsigned int count)
static uint16_t _checksum (const std::vector< uint8_t > &vec)
static uint16_t checksum (const std::vector< uint8_t > &vec)
Detailed Description
Calculates checksum.
Constructor & Destructor Documentation
TcpIpChecksum()
inet::TcpIpChecksum::TcpIpChecksum () inline
 {}
Member Function Documentation
_checksum() [1/2]
uint16_t inet::TcpIpChecksum::_checksum (const std::vector< uint8_t > & vec) static
 {
     uint32_t sum = 0;
     for (size_t i = 0; i < vec.size(); i++) {
         sum += (i & 1) ? vec[i] : (vec[i] << 8);
         if (sum & 0x80000000)
             sum = (sum & 0xFFFF) + (sum >> 16);
     }
     while (sum >> 16)
         sum = (sum & 0xFFFF) + (sum >> 16);
     return (uint16_t)sum;
 }
_checksum() [2/2]
uint16_t inet::TcpIpChecksum::_checksum (const void * addr, unsigned int count) static
 {
     const uint8_t *addr = static_cast<const uint8_t *>(_addr);
     uint32_t sum = 0;
     while (count > 1) {
         sum += (addr[0] << 8) | addr[1];
         addr += 2;
         if (sum & 0x80000000)
             sum = (sum & 0xFFFF) + (sum >> 16);
         count -= 2;
     }
     if (count)
         sum += addr[0] << 8;
     while (sum >> 16)
         sum = (sum & 0xFFFF) + (sum >> 16);
     return (uint16_t)sum;
 }
checksum() [1/2]
static uint16_t inet::TcpIpChecksum::checksum (const std::vector< uint8_t > & vec) inline static
 { return ~_checksum(vec); }
checksum() [2/2]
static uint16_t inet::TcpIpChecksum::checksum (const void * addr, unsigned int count) inline static
     {
         return ~_checksum(addr, count);
     }
Referenced by inet::CrcCheckerBase::checkComputedCrc(), inet::tcp::Tcp::checkCrc(), inet::CrcInserterBase::computeComputedCrc(), inet::tcp::TcpCrcInsertionHook::computeCrc(), inet::Pim::computeCrc(), inet::Udp::computeCrc(), inet::Ipv4Encap::encapsulate(), inet::Icmp::insertCrc(), inet::Icmpv6::insertCrc(), inet::Ipv4::insertCrc(), inet::Igmpv2::insertCrc(), inet::Igmpv3::insertCrc(), inet::Ipv4::setComputedCrc(), inet::ospfv2::setLsaCrc(), inet::ospfv2::setLsaHeaderCrc(), inet::ospfv2::setOspfCrc(), inet::Icmpv6::verifyCrc(), inet::Icmp::verifyCrc(), inet::Ipv4::verifyCrc(), inet::Igmpv2::verifyCrc(), and inet::Igmpv3::verifyCrc().
The documentation for this class was generated from the following files:
TcpIpChecksum.h
TcpIpChecksum.cc