INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3LsaHeader Class Reference
inet::ospfv3::Ospfv3LsaHeader Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:82 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3LsaHeader ()
Ospfv3LsaHeader (const Ospfv3LsaHeader &other)
virtual ~Ospfv3LsaHeader ()
Ospfv3LsaHeader & operator= (const Ospfv3LsaHeader &other)
virtual Ospfv3LsaHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getLsaAge () const
virtual void setLsaAge (unsigned short lsaAge)
virtual unsigned short getOptions () const
virtual void setOptions (unsigned short options)
virtual unsigned short getLsaType () const
virtual void setLsaType (unsigned short lsaType)
virtual const ::inet::Ipv4Address & getLinkStateID () const
virtual ::inet::Ipv4Address & getLinkStateIDForUpdate ()
virtual void setLinkStateID (const ::inet::Ipv4Address &linkStateID)
virtual const ::inet::Ipv4Address & getAdvertisingRouter () const
virtual ::inet::Ipv4Address & getAdvertisingRouterForUpdate ()
virtual void setAdvertisingRouter (const ::inet::Ipv4Address &advertisingRouter)
virtual uint32_t getLsaSequenceNumber () const
virtual void setLsaSequenceNumber (uint32_t lsaSequenceNumber)
virtual uint16_t getLsaChecksum () const
virtual void setLsaChecksum (uint16_t lsaChecksum)
virtual ::inet::CrcMode getLsCrcMode () const
virtual void setLsCrcMode (::inet::CrcMode lsCrcMode)
virtual uint16_t getLsaLength () const
virtual void setLsaLength (uint16_t lsaLength)
Protected Member Functions
bool operator== (const Ospfv3LsaHeader &)=delete
Protected Attributes
unsigned short lsaAge = 0
unsigned short options = 0
unsigned short lsaType = 0
::inet::Ipv4Address linkStateID
::inet::Ipv4Address advertisingRouter
uint32_t lsaSequenceNumber = 0
uint16_t lsaChecksum = 0
::inet::CrcMode lsCrcMode = CRC_MODE_UNDEFINED
uint16_t lsaLength = 0
Private Member Functions
void copy (const Ospfv3LsaHeader &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:82 by opp_msgtool.
//Common LSA Header - this header is present in every LSA
//triplet {lsType, linkStateID, advertisingRouter} uniquely identify the LSA
class Ospfv3LsaHeader extends cObject
{
    @packetData;
    unsigned short lsaAge;          // [sec] 16 bits
    unsigned short options;         // 8 bits
    unsigned short lsaType;         // 8 bits
    Ipv4Address linkStateID;        // 32 bits
    Ipv4Address advertisingRouter;  // 32 bits
    uint32_t lsaSequenceNumber;     // 32 bits
    uint16_t lsaChecksum;     // 16 bits
    CrcMode lsCrcMode = CRC_MODE_UNDEFINED;
    uint16_t lsaLength;
}
Constructor & Destructor Documentation
Ospfv3LsaHeader() [1/2]
inet::ospfv3::Ospfv3LsaHeader::Ospfv3LsaHeader ()
Ospfv3LsaHeader() [2/2]
inet::ospfv3::Ospfv3LsaHeader::Ospfv3LsaHeader (const Ospfv3LsaHeader & other)
~Ospfv3LsaHeader()
virtual inet::ospfv3::Ospfv3LsaHeader::~Ospfv3LsaHeader () virtual
Member Function Documentation
copy()
void inet::ospfv3::Ospfv3LsaHeader::copy (const Ospfv3LsaHeader & other) private
dup()
virtual Ospfv3LsaHeader* inet::ospfv3::Ospfv3LsaHeader::dup () const inline override virtual
 {return new Ospfv3LsaHeader(*this);}
getAdvertisingRouter()
virtual const ::inet::Ipv4Address& inet::ospfv3::Ospfv3LsaHeader::getAdvertisingRouter () const virtual
Referenced by inet::ospfv3::Ospfv3Neighbor::addToRetransmissionList(), inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateNextHops(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Area::deleteRouterLSA(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv3::Ospfv3Process::floodLSA(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::ospfv3::Ospfv3Area::hasLink(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::installLinkLSA(), inet::ospfv3::Ospfv3Area::installNetworkLSA(), inet::ospfv3::Ospfv3Area::installRouterLSA(), inet::ospfv3::Ospfv3Area::InterAreaPrefixLSAAlreadyExists(), inet::ospfv3::Ospfv3Area::IntraAreaPrefixLSAAlreadyExists(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::preProcessDDPacket(), inet::ospfv3::Ospfv3Interface::processLSAck(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::ospfv3::Ospfv3Area::routerLSAAlreadyExists(), and inet::ospfv3::Ospfv3Neighbor::sendLinkStateRequestPacket().
getAdvertisingRouterForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv3::Ospfv3LsaHeader::getAdvertisingRouterForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv3LsaHeader*>(this)->getAdvertisingRouter());}
getLinkStateID()
virtual const ::inet::Ipv4Address& inet::ospfv3::Ospfv3LsaHeader::getLinkStateID () const virtual
Referenced by inet::ospfv3::Ospfv3Neighbor::addToRetransmissionList(), inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateNextHops(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::deleteRouterLSA(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv3::Ospfv3Process::floodLSA(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::installLinkLSA(), inet::ospfv3::Ospfv3Area::installNetworkLSA(), inet::ospfv3::Ospfv3Area::installRouterLSA(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3SpfVertex::Ospfv3SpfVertex(), inet::ospfv3::Ospfv3Interface::preProcessDDPacket(), inet::ospfv3::Ospfv3Interface::processLSAck(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Area::routerLSAAlreadyExists(), and inet::ospfv3::Ospfv3Neighbor::sendLinkStateRequestPacket().
getLinkStateIDForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv3::Ospfv3LsaHeader::getLinkStateIDForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv3LsaHeader*>(this)->getLinkStateID());}
getLsaAge()
virtual unsigned short inet::ospfv3::Ospfv3LsaHeader::getLsaAge () const virtual
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv3::Ospfv3Area::interAreaPrefixLSADiffersFrom(), inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom(), inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom(), inet::ospfv3::Ospfv3Area::networkLSADiffersFrom(), inet::ospfv3::operator<(), inet::ospfv3::operator<<(), inet::ospfv3::operator==(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getLsaChecksum()
virtual uint16_t inet::ospfv3::Ospfv3LsaHeader::getLsaChecksum () const virtual
getLsaLength()
virtual uint16_t inet::ospfv3::Ospfv3LsaHeader::getLsaLength () const virtual
Referenced by inet::ospfv3::Ospfv3Area::interAreaPrefixLSADiffersFrom(), inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom(), inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom(), inet::ospfv3::Ospfv3Area::networkLSADiffersFrom(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getLsaSequenceNumber()
virtual uint32_t inet::ospfv3::Ospfv3LsaHeader::getLsaSequenceNumber () const virtual
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::operator<(), inet::ospfv3::operator<<(), inet::ospfv3::operator==(), and inet::ospfv3::Ospfv3Interface::processLSU().
getLsaType()
virtual unsigned short inet::ospfv3::Ospfv3LsaHeader::getLsaType () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::Ospfv3Process::floodLSA(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::installLinkLSA(), inet::ospfv3::Ospfv3Process::installLSA(), inet::ospfv3::Ospfv3Area::installNetworkLSA(), inet::ospfv3::Ospfv3Area::installRouterLSA(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3SpfVertex::Ospfv3SpfVertex(), inet::ospfv3::Ospfv3Interface::prepareUpdatePacket(), inet::ospfv3::Ospfv3Interface::preProcessDDPacket(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), and inet::ospfv3::Ospfv3Neighbor::sendLinkStateRequestPacket().
getLsCrcMode()
virtual ::inet::CrcMode inet::ospfv3::Ospfv3LsaHeader::getLsCrcMode () const
getOptions()
virtual unsigned short inet::ospfv3::Ospfv3LsaHeader::getOptions () const virtual
operator=()
Ospfv3LsaHeader& inet::ospfv3::Ospfv3LsaHeader::operator= (const Ospfv3LsaHeader & other)
operator==()
bool inet::ospfv3::Ospfv3LsaHeader::operator== (const Ospfv3LsaHeader &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3LsaHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3LsaHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::ospfv3::doParsimUnpacking().
setAdvertisingRouter()
virtual void inet::ospfv3::Ospfv3LsaHeader::setAdvertisingRouter (const ::inet::Ipv4Address & advertisingRouter) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), and inet::ospfv3::Ospfv3Area::originateRouterLSA().
setLinkStateID()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLinkStateID (const ::inet::Ipv4Address & linkStateID) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), and inet::ospfv3::Ospfv3Area::originateRouterLSA().
setLsaAge()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLsaAge (unsigned short lsaAge) virtual
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Area::deleteRouterLSA(), inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), inet::ospfv3::Ospfv3Area::originateRouterLSA(), and inet::ospfv3::Ospfv3Interface::processLSU().
setLsaChecksum()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLsaChecksum (uint16_t lsaChecksum) virtual
setLsaLength()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLsaLength (uint16_t lsaLength) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetworkLSA().
setLsaSequenceNumber()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLsaSequenceNumber (uint32_t lsaSequenceNumber) virtual
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), inet::ospfv3::Ospfv3Area::originateRouterLSA(), and inet::ospfv3::Ospfv3Interface::processLSU().
setLsaType()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLsaType (unsigned short lsaType) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), and inet::ospfv3::Ospfv3Area::originateRouterLSA().
setLsCrcMode()
virtual void inet::ospfv3::Ospfv3LsaHeader::setLsCrcMode (::inet::CrcMode lsCrcMode) virtual
setOptions()
virtual void inet::ospfv3::Ospfv3LsaHeader::setOptions (unsigned short options) virtual
Member Data Documentation
advertisingRouter
::inet::Ipv4Address inet::ospfv3::Ospfv3LsaHeader::advertisingRouter protected
linkStateID
::inet::Ipv4Address inet::ospfv3::Ospfv3LsaHeader::linkStateID protected
lsaAge
unsigned short inet::ospfv3::Ospfv3LsaHeader::lsaAge = 0 protected
lsaChecksum
uint16_t inet::ospfv3::Ospfv3LsaHeader::lsaChecksum = 0 protected
lsaLength
uint16_t inet::ospfv3::Ospfv3LsaHeader::lsaLength = 0 protected
lsaSequenceNumber
uint32_t inet::ospfv3::Ospfv3LsaHeader::lsaSequenceNumber = 0 protected
lsaType
unsigned short inet::ospfv3::Ospfv3LsaHeader::lsaType = 0 protected
lsCrcMode
::inet::CrcMode inet::ospfv3::Ospfv3LsaHeader::lsCrcMode = CRC_MODE_UNDEFINED protected
options
unsigned short inet::ospfv3::Ospfv3LsaHeader::options = 0 protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h