INET Framework for OMNeT++/OMNEST: inet::rtp::RtpInnerPacket Class Reference
inet::rtp::RtpInnerPacket Class Reference
Class generated from inet/transportlayer/rtp/RtpInnerPacket.msg:49 by opp_msgtool.
#include <RtpInnerPacket_m.h>
Public Member Functions
RtpInnerPacket (const char *name=nullptr, short kind=0)
RtpInnerPacket (const RtpInnerPacket &other)
virtual ~RtpInnerPacket ()
RtpInnerPacket & operator= (const RtpInnerPacket &other)
virtual RtpInnerPacket * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual RtpInpType getType () const
virtual void setType (RtpInpType type)
virtual const char * getCommonName () const
virtual void setCommonName (const char *commonName)
virtual int getMtu () const
virtual void setMtu (int mtu)
virtual int getBandwidth () const
virtual void setBandwidth (int bandwidth)
virtual int getRtcpPercentage () const
virtual void setRtcpPercentage (int rtcpPercentage)
virtual const ::inet::Ipv4Address & getAddress () const
virtual ::inet::Ipv4Address & getAddressForUpdate ()
virtual void setAddress (const ::inet::Ipv4Address &address)
virtual int getPort () const
virtual void setPort (int port)
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
virtual int getPayloadType () const
virtual void setPayloadType (int payloadType)
virtual const char * getFileName () const
virtual void setFileName (const char *fileName)
virtual int getClockRate () const
virtual void setClockRate (int clockRate)
virtual int getTimeStampBase () const
virtual void setTimeStampBase (int timeStampBase)
virtual int getSequenceNumberBase () const
virtual void setSequenceNumberBase (int sequenceNumberBase)
virtual std::string str () const override
Writes a short info about this RtpInnerPacket into the given string.
virtual void dump (std::ostream &os) const
Writes a longer info about this RtpInnerPacket into the given output stream.
virtual void setInitializeProfilePkt (int mtu)
Called by the rtp module after creating the profile module.
virtual void setProfileInitializedPkt (int rtcpPercentage, int port)
Called by the profile module after it has received the initializeProfile() message.
virtual void setInitializeRTCPPkt (const char *commonName, int mtu, int bandwidth, int rtcpPercentage, Ipv4Address address, int port)
Called by the rtp module to inform the rtcp module about mandatory information for starting the rtp session.
virtual void setRtcpInitializedPkt (uint32_t ssrc)
Called by the rtcp module after it has waited for half an rtcp interval for incoming messages from other session participants.
virtual void setCreateSenderModulePkt (uint32_t ssrc, int payloadType, const char *fileName)
virtual void setSenderModuleCreatedPkt (uint32_t ssrc)
virtual void setDeleteSenderModulePkt (uint32_t ssrc)
virtual void setSenderModuleDeletedPkt (uint32_t ssrc)
virtual void setInitializeSenderModulePkt (uint32_t ssrc, const char *fileName, int mtu)
virtual void setSenderModuleInitializedPkt (uint32_t ssrc, int payloadType, int clockRate, int timeStampBase, int sequenceNumberBase)
virtual void setSenderModuleControlPkt (uint32_t ssrc, RtpSenderControlMessage *msg)
virtual void setSenderModuleStatusPkt (uint32_t ssrc, RtpSenderStatusMessage *msg)
virtual void setLeaveSessionPkt ()
Called by the rtp module to inform the rtcp module that the session should be left.
virtual void setSessionLeftPkt ()
Called by the rtcp module when the rtcp bye packet has been sent to the network.
virtual void setDataOutPkt (Packet *packet)
Capsulates the outgoing RtpPacket into this RtpInnerPacket to transport it within the rtp layer.
virtual void setDataInPkt (Packet *packet, Ipv4Address address, int port)
Capsulates the incoming RtpPacket into this RtpInnerPacket to transport it within the rtp layer.
Protected Member Functions
bool operator== (const RtpInnerPacket &)=delete
Protected Attributes
RtpInpType type = RTP_INP_UNDEF
::omnetpp::opp_string commonName
int mtu = 0
int bandwidth = 0
int rtcpPercentage = 0
::inet::Ipv4Address address = Ipv4Address::UNSPECIFIED_ADDRESS
int port = PORT_UNDEF
uint32_t ssrc = 0
int payloadType = 0
::omnetpp::opp_string fileName
int clockRate = 0
int timeStampBase = 0
int sequenceNumberBase = 0
Private Member Functions
void copy (const RtpInnerPacket &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInnerPacket.msg:49 by opp_msgtool.
//
// This class is used for communication between submodules of the RTP layer module.
//
packet RtpInnerPacket
{
    // The type of this ~RtpInnerPacket.
    RtpInpType type = RTP_INP_UNDEF;
    // The CNAME
    string commonName;
    // The MTU
    int mtu;
    // The Bandwidth
    int bandwidth;
    // The RTCP percentage
    int rtcpPercentage;
    // The Ipv4 address
    Ipv4Address address = Ipv4Address::UNSPECIFIED_ADDRESS;
    // The port number
    int port = PORT_UNDEF;
    // The SSRC identifier
    uint32_t ssrc;
    // The payload type
    int payloadType;
    // The file name
    string fileName;
    // The clock rate
    int clockRate;
    // The RTP time stamp base
    int timeStampBase;
    // The RTP sequence number base
    int sequenceNumberBase;
}
Constructor & Destructor Documentation
RtpInnerPacket() [1/2]
inet::rtp::RtpInnerPacket::RtpInnerPacket (const char * name = nullptr, short kind = 0)
RtpInnerPacket() [2/2]
inet::rtp::RtpInnerPacket::RtpInnerPacket (const RtpInnerPacket & other)
~RtpInnerPacket()
virtual inet::rtp::RtpInnerPacket::~RtpInnerPacket () virtual
Member Function Documentation
copy()
void inet::rtp::RtpInnerPacket::copy (const RtpInnerPacket & other) private
dump()
void inet::rtp::RtpInnerPacket::dump (std::ostream & os) const virtual
Writes a longer info about this RtpInnerPacket into the given output stream.
 {
     os << "RtpInnerPacket:" << endl;
     os << "  type = " << type << endl;
     os << "  commonName = " << commonName << endl;
     os << "  mtu = " << mtu << endl;
     os << "  bandwidth = " << bandwidth << endl;
     os << "  rtcpPercentage = " << rtcpPercentage << endl;
     os << "  address = " << address << endl;
     os << "  port = " << port << endl;
     os << "  ssrc = " << ssrc << endl;
     os << "  payloadType = " << payloadType << endl;
     os << "  fileName = " << fileName << endl;
     os << "  clockRate = " << clockRate << endl;
     os << "  timeStampBase = " << timeStampBase << endl;
     os << "  sequenceNumberBase = " << sequenceNumberBase << endl;
 }
dup()
virtual RtpInnerPacket* inet::rtp::RtpInnerPacket::dup () const inline override virtual
 {return new RtpInnerPacket(*this);}
Referenced by inet::rtp::Rtp::dataOut().
getAddress()
virtual const ::inet::Ipv4Address& inet::rtp::RtpInnerPacket::getAddress () const virtual
Referenced by inet::rtp::Rtcp::handleDataIn(), and inet::rtp::Rtcp::handleInitializeRTCP().
getAddressForUpdate()
virtual ::inet::Ipv4Address& inet::rtp::RtpInnerPacket::getAddressForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<RtpInnerPacket*>(this)->getAddress());}
getBandwidth()
virtual int inet::rtp::RtpInnerPacket::getBandwidth () const virtual
Referenced by inet::rtp::Rtcp::handleInitializeRTCP().
getClockRate()
virtual int inet::rtp::RtpInnerPacket::getClockRate () const virtual
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
getCommonName()
virtual const char* inet::rtp::RtpInnerPacket::getCommonName () const virtual
Referenced by inet::rtp::Rtcp::handleInitializeRTCP().
getFileName()
virtual const char* inet::rtp::RtpInnerPacket::getFileName () const virtual
Referenced by inet::rtp::RtpProfile::createSenderModule(), and inet::rtp::RtpPayloadSender::initializeSenderModule().
getMtu()
virtual int inet::rtp::RtpInnerPacket::getMtu () const virtual
Referenced by inet::rtp::Rtcp::handleInitializeRTCP(), inet::rtp::RtpProfile::initializeProfile(), and inet::rtp::RtpPayloadSender::initializeSenderModule().
getPayloadType()
virtual int inet::rtp::RtpInnerPacket::getPayloadType () const virtual
Referenced by inet::rtp::RtpProfile::createSenderModule().
getPort()
virtual int inet::rtp::RtpInnerPacket::getPort () const virtual
Referenced by inet::rtp::Rtcp::handleDataIn(), inet::rtp::Rtcp::handleInitializeRTCP(), and inet::rtp::Rtp::profileInitialized().
getRtcpPercentage()
virtual int inet::rtp::RtpInnerPacket::getRtcpPercentage () const virtual
Referenced by inet::rtp::Rtcp::handleInitializeRTCP(), and inet::rtp::Rtp::profileInitialized().
getSequenceNumberBase()
virtual int inet::rtp::RtpInnerPacket::getSequenceNumberBase () const virtual
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
getSsrc()
virtual uint32_t inet::rtp::RtpInnerPacket::getSsrc () const virtual
Referenced by inet::rtp::RtpProfile::createSenderModule(), inet::rtp::RtpProfile::deleteSenderModule(), inet::rtp::RtpPayloadSender::initializeSenderModule(), inet::rtp::Rtp::rtcpInitialized(), inet::rtp::Rtp::senderModuleControl(), inet::rtp::Rtp::senderModuleCreated(), inet::rtp::Rtp::senderModuleDeleted(), and inet::rtp::Rtp::senderModuleStatus().
getTimeStampBase()
virtual int inet::rtp::RtpInnerPacket::getTimeStampBase () const virtual
Referenced by inet::rtp::Rtcp::handleSenderModuleInitialized().
getType()
virtual RtpInpType inet::rtp::RtpInnerPacket::getType () const virtual
Referenced by inet::rtp::RtpPayloadReceiver::handleMessage(), inet::rtp::RtpPayloadSender::handleMessage(), inet::rtp::RtpProfile::handleMessageFromPayloadSender(), inet::rtp::Rtp::handleMessageFromProfile(), inet::rtp::Rtp::handleMessageFromRTCP(), inet::rtp::Rtcp::handleMessageFromRTP(), and inet::rtp::RtpProfile::handleMessageFromRTP().
operator=()
RtpInnerPacket& inet::rtp::RtpInnerPacket::operator= (const RtpInnerPacket & other)
operator==()
bool inet::rtp::RtpInnerPacket::operator== (const RtpInnerPacket &) protected delete
parsimPack()
virtual void inet::rtp::RtpInnerPacket::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpInnerPacket::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::rtp::doParsimUnpacking().
setAddress()
virtual void inet::rtp::RtpInnerPacket::setAddress (const ::inet::Ipv4Address & address) virtual
setBandwidth()
virtual void inet::rtp::RtpInnerPacket::setBandwidth (int bandwidth) virtual
setClockRate()
virtual void inet::rtp::RtpInnerPacket::setClockRate (int clockRate) virtual
setCommonName()
virtual void inet::rtp::RtpInnerPacket::setCommonName (const char * commonName) virtual
setCreateSenderModulePkt()
void inet::rtp::RtpInnerPacket::setCreateSenderModulePkt (uint32_t ssrc, int payloadType, const char * fileName) virtual
 {
     type = RTP_INP_CREATE_SENDER_MODULE;
     ssrc = ssrc_par;
     payloadType = payloadType_par;
     fileName = fileName_par;
 }
Referenced by inet::rtp::Rtp::createSenderModule().
setDataInPkt()
void inet::rtp::RtpInnerPacket::setDataInPkt (Packet * packet, Ipv4Address address, int port) virtual
Capsulates the incoming RtpPacket into this RtpInnerPacket to transport it within the rtp layer.
 {
     type = RTP_INP_DATA_IN;
     address = address_par;
     port = port_par;
     encapsulate(packet);
 }
Referenced by inet::rtp::Rtp::readRet().
setDataOutPkt()
void inet::rtp::RtpInnerPacket::setDataOutPkt (Packet * packet) virtual
Capsulates the outgoing RtpPacket into this RtpInnerPacket to transport it within the rtp layer.
 {
     type = RTP_INP_DATA_OUT;
     encapsulate(packet);
 }
setDeleteSenderModulePkt()
void inet::rtp::RtpInnerPacket::setDeleteSenderModulePkt (uint32_t ssrc) virtual
 {
     type = RTP_INP_DELETE_SENDER_MODULE;
     ssrc = ssrc_par;
 }
Referenced by inet::rtp::Rtp::deleteSenderModule().
setFileName()
virtual void inet::rtp::RtpInnerPacket::setFileName (const char * fileName) virtual
setInitializeProfilePkt()
void inet::rtp::RtpInnerPacket::setInitializeProfilePkt (int mtu) virtual
Called by the rtp module after creating the profile module.
It informes the profile about the maximum size an rtp packet can have.
 {
     type = RTP_INP_INITIALIZE_PROFILE;
     mtu = mtu_par;
 }
Referenced by inet::rtp::Rtp::initializeProfile().
setInitializeRTCPPkt()
void inet::rtp::RtpInnerPacket::setInitializeRTCPPkt (const char * commonName, int mtu, int bandwidth, int rtcpPercentage, Ipv4Address address, int port) virtual
Called by the rtp module to inform the rtcp module about mandatory information for starting the rtp session.
 {
     type = RTP_INP_INITIALIZE_RTCP;
     commonName = commonName_par;
     mtu = mtu_par;
     bandwidth = bandwidth_par;
     rtcpPercentage = rtcpPercentage_par;
     address = address_par;
     port = port_par;
 }
Referenced by inet::rtp::Rtp::initializeRTCP().
setInitializeSenderModulePkt()
void inet::rtp::RtpInnerPacket::setInitializeSenderModulePkt (uint32_t ssrc, const char * fileName, int mtu) virtual
 {
     type = RTP_INP_INITIALIZE_SENDER_MODULE;
     ssrc = ssrc_par;
     fileName = fileName_par;
     mtu = mtu_par;
 }
Referenced by inet::rtp::RtpProfile::createSenderModule().
setLeaveSessionPkt()
void inet::rtp::RtpInnerPacket::setLeaveSessionPkt () virtual
Called by the rtp module to inform the rtcp module that the session should be left.
 {
     type = RTP_INP_LEAVE_SESSION;
 }
Referenced by inet::rtp::Rtp::leaveSession().
setMtu()
virtual void inet::rtp::RtpInnerPacket::setMtu (int mtu) virtual
setPayloadType()
virtual void inet::rtp::RtpInnerPacket::setPayloadType (int payloadType) virtual
setPort()
virtual void inet::rtp::RtpInnerPacket::setPort (int port) virtual
setProfileInitializedPkt()
void inet::rtp::RtpInnerPacket::setProfileInitializedPkt (int rtcpPercentage, int port) virtual
Called by the profile module after it has received the initializeProfile() message.
It informs the rtp module about the percentage of the available bandwidth to be used by rtcp and the preferred port for this profile.
 {
     type = RTP_INP_PROFILE_INITIALIZED;
     rtcpPercentage = rtcpPercentage_par;
     port = port_par;
 }
Referenced by inet::rtp::RtpProfile::initializeProfile().
setRtcpInitializedPkt()
void inet::rtp::RtpInnerPacket::setRtcpInitializedPkt (uint32_t ssrc) virtual
Called by the rtcp module after it has waited for half an rtcp interval for incoming messages from other session participants.
It informs the rtp module which later informs the rtp application about the ssrc identifier
 {
     type = RTP_INP_RTCP_INITIALIZED;
     ssrc = ssrc_par;
 }
Referenced by inet::rtp::Rtcp::handleSelfMessage().
setRtcpPercentage()
virtual void inet::rtp::RtpInnerPacket::setRtcpPercentage (int rtcpPercentage) virtual
setSenderModuleControlPkt()
void inet::rtp::RtpInnerPacket::setSenderModuleControlPkt (uint32_t ssrc, RtpSenderControlMessage * msg) virtual
 {
     type = RTP_INP_SENDER_MODULE_CONTROL;
     ssrc = ssrc_par;
     encapsulate(msg);
 }
Referenced by inet::rtp::Rtp::senderModuleControl().
setSenderModuleCreatedPkt()
void inet::rtp::RtpInnerPacket::setSenderModuleCreatedPkt (uint32_t ssrc) virtual
 {
     type = RTP_INP_SENDER_MODULE_CREATED;
     ssrc = ssrc_par;
 }
Referenced by inet::rtp::RtpProfile::createSenderModule().
setSenderModuleDeletedPkt()
void inet::rtp::RtpInnerPacket::setSenderModuleDeletedPkt (uint32_t ssrc) virtual
 {
     type = RTP_INP_SENDER_MODULE_DELETED;
     ssrc = ssrc_par;
 }
Referenced by inet::rtp::RtpProfile::deleteSenderModule().
setSenderModuleInitializedPkt()
void inet::rtp::RtpInnerPacket::setSenderModuleInitializedPkt (uint32_t ssrc, int payloadType, int clockRate, int timeStampBase, int sequenceNumberBase) virtual
 {
     type = RTP_INP_SENDER_MODULE_INITIALIZED;
     ssrc = ssrc_par;
     payloadType = payloadType_par;
     clockRate = clockRate_par;
     timeStampBase = timeStampBase_par;
     sequenceNumberBase = sequenceNumberBase_par;
 }
Referenced by inet::rtp::RtpPayloadSender::initializeSenderModule().
setSenderModuleStatusPkt()
void inet::rtp::RtpInnerPacket::setSenderModuleStatusPkt (uint32_t ssrc, RtpSenderStatusMessage * msg) virtual
 {
     type = RTP_INP_SENDER_MODULE_STATUS;
     ssrc = ssrc_par;
     encapsulate(msg);
 }
Referenced by inet::rtp::RtpPayloadSender::endOfFile(), inet::rtp::RtpPayloadSender::pause(), inet::rtp::RtpPayloadSender::play(), and inet::rtp::RtpPayloadSender::stop().
setSequenceNumberBase()
virtual void inet::rtp::RtpInnerPacket::setSequenceNumberBase (int sequenceNumberBase) virtual
setSessionLeftPkt()
void inet::rtp::RtpInnerPacket::setSessionLeftPkt () virtual
Called by the rtcp module when the rtcp bye packet has been sent to the network.
 {
     type = RTP_INP_SESSION_LEFT;
 }
Referenced by inet::rtp::Rtcp::createPacket().
setSsrc()
virtual void inet::rtp::RtpInnerPacket::setSsrc (uint32_t ssrc) virtual
setTimeStampBase()
virtual void inet::rtp::RtpInnerPacket::setTimeStampBase (int timeStampBase) virtual
setType()
virtual void inet::rtp::RtpInnerPacket::setType (RtpInpType type) virtual
str()
std::string inet::rtp::RtpInnerPacket::str () const override virtual
Writes a short info about this RtpInnerPacket into the given string.
 {
     std::stringstream out;
     out << "RtpInnerPacket: type=" << type;
     return out.str();
 }
Member Data Documentation
address
::inet::Ipv4Address inet::rtp::RtpInnerPacket::address = Ipv4Address::UNSPECIFIED_ADDRESS protected
Referenced by dump(), setDataInPkt(), and setInitializeRTCPPkt().
bandwidth
int inet::rtp::RtpInnerPacket::bandwidth = 0 protected
Referenced by dump(), and setInitializeRTCPPkt().
clockRate
int inet::rtp::RtpInnerPacket::clockRate = 0 protected
Referenced by dump(), and setSenderModuleInitializedPkt().
commonName
::omnetpp::opp_string inet::rtp::RtpInnerPacket::commonName protected
Referenced by dump(), and setInitializeRTCPPkt().
fileName
::omnetpp::opp_string inet::rtp::RtpInnerPacket::fileName protected
Referenced by dump(), setCreateSenderModulePkt(), and setInitializeSenderModulePkt().
mtu
int inet::rtp::RtpInnerPacket::mtu = 0 protected
Referenced by dump(), setInitializeProfilePkt(), setInitializeRTCPPkt(), and setInitializeSenderModulePkt().
payloadType
int inet::rtp::RtpInnerPacket::payloadType = 0 protected
Referenced by dump(), setCreateSenderModulePkt(), and setSenderModuleInitializedPkt().
port
int inet::rtp::RtpInnerPacket::port = PORT_UNDEF protected
Referenced by dump(), setDataInPkt(), setInitializeRTCPPkt(), and setProfileInitializedPkt().
rtcpPercentage
int inet::rtp::RtpInnerPacket::rtcpPercentage = 0 protected
Referenced by dump(), setInitializeRTCPPkt(), and setProfileInitializedPkt().
sequenceNumberBase
int inet::rtp::RtpInnerPacket::sequenceNumberBase = 0 protected
Referenced by dump(), and setSenderModuleInitializedPkt().
ssrc
uint32_t inet::rtp::RtpInnerPacket::ssrc = 0 protected
Referenced by dump(), setCreateSenderModulePkt(), setDeleteSenderModulePkt(), setInitializeSenderModulePkt(), setRtcpInitializedPkt(), setSenderModuleControlPkt(), setSenderModuleCreatedPkt(), setSenderModuleDeletedPkt(), setSenderModuleInitializedPkt(), and setSenderModuleStatusPkt().
timeStampBase
int inet::rtp::RtpInnerPacket::timeStampBase = 0 protected
Referenced by dump(), and setSenderModuleInitializedPkt().
type
RtpInpType inet::rtp::RtpInnerPacket::type = RTP_INP_UNDEF protected
Referenced by dump(), setCreateSenderModulePkt(), setDataInPkt(), setDataOutPkt(), setDeleteSenderModulePkt(), setInitializeProfilePkt(), setInitializeRTCPPkt(), setInitializeSenderModulePkt(), setLeaveSessionPkt(), setProfileInitializedPkt(), setRtcpInitializedPkt(), setSenderModuleControlPkt(), setSenderModuleCreatedPkt(), setSenderModuleDeletedPkt(), setSenderModuleInitializedPkt(), setSenderModuleStatusPkt(), setSessionLeftPkt(), and str().
The documentation for this class was generated from the following files:
RtpInnerPacket_m.h
RtpInnerPacket.cc