INET Framework for OMNeT++/OMNEST: inet::physicallayer::IRadio Class Reference
inet::physicallayer::IRadio Class Reference abstract
This interface represents a physical device that is capable of transmitting and receiving radio signals.
#include <IRadio.h>
Public Types
enum RadioMode {
RADIO_MODE_OFF, RADIO_MODE_SLEEP, RADIO_MODE_RECEIVER, RADIO_MODE_TRANSMITTER,
RADIO_MODE_TRANSCEIVER, RADIO_MODE_SWITCHING
}
This enumeration specifies the requested operational mode of the radio.
enum ReceptionState { RECEPTION_STATE_UNDEFINED, RECEPTION_STATE_IDLE, RECEPTION_STATE_BUSY, RECEPTION_STATE_RECEIVING }
This enumeration specifies the reception state of the radio.
enum TransmissionState { TRANSMISSION_STATE_UNDEFINED, TRANSMISSION_STATE_IDLE, TRANSMISSION_STATE_TRANSMITTING }
This enumeration specifies the transmission state of the radio.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
virtual const cGate * getRadioGate () const =0
Returns the gate of the radio that receives incoming signals.
virtual RadioMode getRadioMode () const =0
Returns the current radio mode, This is the same mode as the one emitted with the last radioModeChangedSignal.
virtual void setRadioMode (RadioMode radioMode)=0
Changes the current radio mode.
virtual ReceptionState getReceptionState () const =0
Returns the current radio reception state.
virtual TransmissionState getTransmissionState () const =0
Returns the current radio transmission state.
virtual int getId () const =0
Returns an identifier for this radio which is globally unique for the whole lifetime of the simulation among all radios.
virtual const IAntenna * getAntenna () const =0
Returns the antenna used by the transceiver of this radio.
virtual const ITransmitter * getTransmitter () const =0
Returns the transmitter part of this radio.
virtual const IReceiver * getReceiver () const =0
Returns the receiver part of this radio.
virtual const IRadioMedium * getMedium () const =0
Returns the radio medium where this radio is transmitting and receiving radio signals.
virtual const ITransmission * getTransmissionInProgress () const =0
Returns the ongoing transmission that the transmitter is currently transmitting or nullptr.
virtual const ITransmission * getReceptionInProgress () const =0
Returns the ongoing reception that the receiver is currently receiving or nullptr.
virtual IRadioSignal::SignalPart getTransmittedSignalPart () const =0
Returns the signal part of the ongoing transmission that the transmitter is currently transmitting or -1 if no transmission is in progress.
virtual IRadioSignal::SignalPart getReceivedSignalPart () const =0
Returns the signal part of the ongoing reception that the receiver is currently receiving or -1 if no reception is in progress.
Public Member Functions inherited from inet::IPhysicalLayer
virtual ~IPhysicalLayer ()
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Member Functions
static const char * getRadioModeName (RadioMode radioMode)
Returns the name of the provided radio mode.
static const char * getRadioReceptionStateName (ReceptionState receptionState)
Returns the name of the provided radio reception state.
static const char * getRadioTransmissionStateName (TransmissionState transmissionState)
Returns the name of the provided radio transmission state.
Static Public Attributes
static simsignal_t radioModeChangedSignal = cComponent::registerSignal("radioModeChanged")
This signal is emitted when the radio mode of the radio is changed.
static simsignal_t listeningChangedSignal = cComponent::registerSignal("listeningChanged")
This signal is emitted when the radio listening of the radio is changed.
static simsignal_t receptionStateChangedSignal = cComponent::registerSignal("receptionStateChanged")
This signal is emitted when the radio reception state of the radio is changed.
static simsignal_t transmissionStateChangedSignal = cComponent::registerSignal("transmissionStateChanged")
This signal is emitted when the radio transmission state of the radio is changed.
static simsignal_t receivedSignalPartChangedSignal = cComponent::registerSignal("receivedSignalPartChanged")
This signal is emitted when the received part is changed by the radio.
static simsignal_t transmittedSignalPartChangedSignal = cComponent::registerSignal("transmittedSignalPartChanged")
This signal is emitted when the transmitted part is changed by the radio.
Static Protected Attributes
static int nextId = 0
static cEnum * radioModeEnum = nullptr
The enumeration registered for radio mode.
static cEnum * receptionStateEnum = nullptr
The enumeration registered for radio reception state.
static cEnum * transmissionStateEnum = nullptr
The enumeration registered for radio transmission state.
Detailed Description
This interface represents a physical device that is capable of transmitting and receiving radio signals.
Simultaneous reception and transmission is also supported. The radio has an operation mode and it provides the state of the radio medium at its position.
Member Enumeration Documentation
RadioMode
enum inet::physicallayer::IRadio::RadioMode
This enumeration specifies the requested operational mode of the radio.
NOTE: Some parts of the code base may be sensitive to the order of the enum items because they may be used as an array index.
Enumerator
RADIO_MODE_OFF
The radio is turned off, frame reception or transmission is not possible, power consumption is zero, radio mode switching is slow.
RADIO_MODE_SLEEP
The radio is sleeping, frame reception or transmission is not possible, power consumption is minimal, radio mode switching is fast.
RADIO_MODE_RECEIVER
The radio is prepared for frame reception, frame transmission is not possible, power consumption is low when receiver is idle and medium when receiving.
RADIO_MODE_TRANSMITTER
The radio is prepared for frame transmission, frame reception is not possible, power consumption is low when transmitter is idle and high when transmitting.
RADIO_MODE_TRANSCEIVER
The radio is prepared for simultaneous frame reception and transmission, power consumption is low when transceiver is idle, medium when receiving and high when transmitting.
RADIO_MODE_SWITCHING
The radio is switching from one mode to another, frame reception or transmission is not possible, power consumption is minimal.
                    {
         RADIO_MODE_OFF,
         RADIO_MODE_SLEEP,
         RADIO_MODE_RECEIVER,
         RADIO_MODE_TRANSMITTER,
         RADIO_MODE_TRANSCEIVER,
         RADIO_MODE_SWITCHING // this radio mode must be the very last
     };
ReceptionState
enum inet::physicallayer::IRadio::ReceptionState
This enumeration specifies the reception state of the radio.
This also determines the state of the radio medium.
Enumerator
RECEPTION_STATE_UNDEFINED
The radio medium state is unknown, reception state is meaningless, signal detection is not possible.
(e.g. the radio mode is off, sleep or transmitter)
RECEPTION_STATE_IDLE
The radio medium is free, no signal is detected.
(e.g. the RSSI is below the energy detection threshold)
RECEPTION_STATE_BUSY
The radio medium is busy, a signal is detected but it is not strong enough to receive.
(e.g. the RSSI is above the energy detection threshold but below the reception threshold)
RECEPTION_STATE_RECEIVING
The radio medium is busy, a signal strong enough to receive is detected.
(e.g. the SNIR was above the reception threshold)
{
         RECEPTION_STATE_UNDEFINED,
         RECEPTION_STATE_IDLE,
         RECEPTION_STATE_BUSY,
         RECEPTION_STATE_RECEIVING
     };
TransmissionState
enum inet::physicallayer::IRadio::TransmissionState
This enumeration specifies the transmission state of the radio.
Enumerator
TRANSMISSION_STATE_UNDEFINED
The transmission state is undefined or meaningless.
(e.g. the radio mode is off, sleep or receiver)
TRANSMISSION_STATE_IDLE
The radio is not transmitting a signal on the radio medium.
(e.g. the last transmission has been completed)
TRANSMISSION_STATE_TRANSMITTING
The radio medium is busy, the radio is currently transmitting a signal.
{
         TRANSMISSION_STATE_UNDEFINED,
         TRANSMISSION_STATE_IDLE,
         TRANSMISSION_STATE_TRANSMITTING
     };
Member Function Documentation
getAntenna()
virtual const IAntenna* inet::physicallayer::IRadio::getAntenna () const pure virtual
Returns the antenna used by the transceiver of this radio.
This function never returns nullptr.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::physicallayer::GridNeighborCache::addRadio(), inet::physicallayer::QuadTreeNeighborCache::addRadio(), inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::visualizer::RadioCanvasVisualizer::createRadioVisualization(), inet::physicallayer::ApskScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::createTransmission(), inet::physicallayer::ApskDimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), inet::physicallayer::NoiseDimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission(), inet::physicallayer::UnitDiskTransmitter::createTransmission(), inet::physicallayer::Ieee802154UwbIrTransmitter::createTransmission(), inet::physicallayer::ApskLayeredTransmitter::createTransmission(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createTransmission(), inet::physicallayer::GridNeighborCache::fillCubeVector(), inet::physicallayer::QuadTreeNeighborCache::sendToNeighbors(), inet::physicallayer::GridNeighborCache::sendToNeighbors(), and inet::physicallayer::NeighborListNeighborCache::updateNeighborList().
getId()
virtual int inet::physicallayer::IRadio::getId () const pure virtual
Returns an identifier for this radio which is globally unique for the whole lifetime of the simulation among all radios.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::physicallayer::ReferenceCommunicationCache::addRadio(), inet::physicallayer::VectorCommunicationCache::addRadio(), inet::physicallayer::ReferenceCommunicationCache::computeInterferingTransmissions(), inet::physicallayer::ReferenceCommunicationCache::getRadioCacheEntry(), inet::physicallayer::MapCommunicationCache::getRadioCacheEntry(), inet::physicallayer::VectorCommunicationCache::getRadioCacheEntry(), inet::physicallayer::ReferenceCommunicationCache::getReceptionCacheEntry(), inet::physicallayer::MapCommunicationCache::getReceptionCacheEntry(), inet::physicallayer::VectorCommunicationCache::getReceptionCacheEntry(), inet::physicallayer::RadioMedium::isInterferingTransmission(), inet::physicallayer::NeighborListNeighborCache::RadioEntry::operator==(), inet::physicallayer::ListeningBase::printToStream(), inet::physicallayer::ReceptionBase::printToStream(), inet::physicallayer::MapCommunicationCache::removeRadio(), inet::physicallayer::GridNeighborCache::removeRadio(), inet::physicallayer::QuadTreeNeighborCache::removeRadio(), inet::physicallayer::RadioMedium::sendToAffectedRadios(), inet::physicallayer::NeighborListNeighborCache::sendToNeighbors(), inet::physicallayer::NeighborListNeighborCache::updateNeighborList(), inet::physicallayer::GridNeighborCache::GridNeighborCacheVisitor::visit(), inet::physicallayer::QuadTreeNeighborCache::QuadTreeNeighborCacheVisitor::visit(), and inet::physicallayer::CommunicationLog::writeReception().
getMedium()
virtual const IRadioMedium* inet::physicallayer::IRadio::getMedium () const pure virtual
Returns the radio medium where this radio is transmitting and receiving radio signals.
This function never returns nullptr.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::physicallayer::ReceiverBase::computeIsReceptionAttempted(), inet::physicallayer::FlatReceiverBase::computeListeningDecision(), inet::physicallayer::ApskLayeredReceiver::computeListeningDecision(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeListeningDecision(), inet::physicallayer::UnitDiskAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), and inet::L3NetworkConfiguratorBase::getWirelessId().
getRadioGate()
virtual const cGate* inet::physicallayer::IRadio::getRadioGate () const pure virtual
Returns the gate of the radio that receives incoming signals.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::physicallayer::RadioMedium::pickUpSignals(), and inet::physicallayer::RadioMedium::sendToRadio().
getRadioMode()
virtual RadioMode inet::physicallayer::IRadio::getRadioMode () const pure virtual
Returns the current radio mode, This is the same mode as the one emitted with the last radioModeChangedSignal.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
getRadioModeName()
const char * inet::physicallayer::IRadio::getRadioModeName (RadioMode radioMode) static
Returns the name of the provided radio mode.
 {
     if (!radioModeEnum)
         radioModeEnum = cEnum::get(opp_typename(typeid(IRadio::RadioMode)));
     return radioModeEnum->getStringFor(radioMode) + 11;
 }
Referenced by inet::physicallayer::Radio::completeRadioModeSwitch(), and inet::physicallayer::Radio::startRadioModeSwitch().
getRadioReceptionStateName()
const char * inet::physicallayer::IRadio::getRadioReceptionStateName (ReceptionState receptionState) static
Returns the name of the provided radio reception state.
 {
     if (!receptionStateEnum)
         receptionStateEnum = cEnum::get(opp_typename(typeid(IRadio::ReceptionState)));
     return receptionStateEnum->getStringFor(receptionState) + 16;
 }
Referenced by inet::physicallayer::Radio::updateTransceiverState().
getRadioTransmissionStateName()
const char * inet::physicallayer::IRadio::getRadioTransmissionStateName (TransmissionState transmissionState) static
Returns the name of the provided radio transmission state.
 {
     if (!transmissionStateEnum)
         transmissionStateEnum = cEnum::get(opp_typename(typeid(IRadio::TransmissionState)));
     return transmissionStateEnum->getStringFor(transmissionState) + 19;
 }
Referenced by inet::physicallayer::Radio::updateTransceiverState().
getReceivedSignalPart()
virtual IRadioSignal::SignalPart inet::physicallayer::IRadio::getReceivedSignalPart () const pure virtual
Returns the signal part of the ongoing reception that the receiver is currently receiving or -1 if no reception is in progress.
This is the same part as the one emitted with the last receivedPartChangedSignal.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
getReceiver()
virtual const IReceiver* inet::physicallayer::IRadio::getReceiver () const pure virtual
Returns the receiver part of this radio.
This function never returns nullptr.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::RadioMedium::addTransmission(), inet::physicallayer::RadioMedium::computeListeningDecision(), inet::physicallayer::RadioMedium::computeReceptionDecision(), inet::physicallayer::RadioMedium::computeReceptionResult(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::RadioMedium::isPotentialReceiver(), inet::physicallayer::RadioMedium::isReceptionAttempted(), inet::physicallayer::RadioMedium::isReceptionPossible(), inet::physicallayer::RadioMedium::isReceptionSuccessful(), and inet::physicallayer::RadioMedium::sendToRadio().
getReceptionInProgress()
virtual const ITransmission* inet::physicallayer::IRadio::getReceptionInProgress () const pure virtual
Returns the ongoing reception that the receiver is currently receiving or nullptr.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::physicallayer::ReceiverBase::computeIsReceptionAttempted().
getReceptionState()
virtual ReceptionState inet::physicallayer::IRadio::getReceptionState () const pure virtual
Returns the current radio reception state.
This is the same state as the one emitted with the last receptionStateChangedSignal.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
getTransmissionInProgress()
virtual const ITransmission* inet::physicallayer::IRadio::getTransmissionInProgress () const pure virtual
Returns the ongoing transmission that the transmitter is currently transmitting or nullptr.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
getTransmissionState()
virtual TransmissionState inet::physicallayer::IRadio::getTransmissionState () const pure virtual
Returns the current radio transmission state.
This is the same state as the one emitted with the last transmissionStateChangedSignal.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
getTransmittedSignalPart()
virtual IRadioSignal::SignalPart inet::physicallayer::IRadio::getTransmittedSignalPart () const pure virtual
Returns the signal part of the ongoing transmission that the transmitter is currently transmitting or -1 if no transmission is in progress.
This is the same part as the one emitted with the last transmittedPartChangedSignal.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
getTransmitter()
virtual const ITransmitter* inet::physicallayer::IRadio::getTransmitter () const pure virtual
Returns the transmitter part of this radio.
This function never returns nullptr.
Implemented in inet::physicallayer::Radio, inet::physicallayer::NoiseSource, and inet::physicallayer::ShortcutRadio.
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::RadioMedium::createTransmitterSignal(), inet::physicallayer::MediumLimitCache::getMaxCommunicationRange(), and inet::physicallayer::MediumLimitCache::getMaxInterferenceRange().
setRadioMode()
virtual void inet::physicallayer::IRadio::setRadioMode (RadioMode radioMode) pure virtual
Changes the current radio mode.
The actual change may take zero or more time. The new radio mode will be emitted with a radioModeChangedSignal.
Implemented in inet::physicallayer::NoiseSource, and inet::physicallayer::Radio.
Member Data Documentation
listeningChangedSignal
simsignal_t inet::physicallayer::IRadio::listeningChangedSignal = cComponent::registerSignal("listeningChanged") static
This signal is emitted when the radio listening of the radio is changed.
The source is the radio and the emitted value is the new listening.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::RadioMedium::receiveSignal(), inet::physicallayer::RadioMedium::removeRadio(), inet::physicallayer::Ieee80211Radio::setBand(), inet::physicallayer::Ieee80211Radio::setChannel(), inet::physicallayer::Ieee80211Radio::setChannelNumber(), inet::physicallayer::Ieee80211Radio::setMode(), and inet::physicallayer::Ieee80211Radio::setModeSet().
nextId
int inet::physicallayer::IRadio::nextId = 0 static protected
radioModeChangedSignal
simsignal_t inet::physicallayer::IRadio::radioModeChangedSignal = cComponent::registerSignal("radioModeChanged") static
This signal is emitted when the radio mode of the radio is changed.
The source is the radio and the emitted value is the new radio mode.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::Radio::completeRadioModeSwitch(), inet::physicallayer::StateBasedEpEnergyConsumer::initialize(), inet::physicallayer::StateBasedCcEnergyConsumer::initialize(), inet::ieee80211::Ieee80211Mac::initialize(), inet::BMac::initialize(), inet::XMac::initialize(), inet::LMac::initialize(), inet::physicallayer::StateBasedEpEnergyConsumer::receiveSignal(), inet::physicallayer::StateBasedCcEnergyConsumer::receiveSignal(), inet::BMac::receiveSignal(), inet::visualizer::RadioVisualizerBase::receiveSignal(), inet::XMac::receiveSignal(), inet::LMac::receiveSignal(), inet::physicallayer::RadioMedium::receiveSignal(), inet::physicallayer::RadioMedium::removeRadio(), inet::physicallayer::Radio::startRadioModeSwitch(), inet::visualizer::RadioVisualizerBase::subscribe(), and inet::visualizer::RadioVisualizerBase::unsubscribe().
radioModeEnum
cEnum * inet::physicallayer::IRadio::radioModeEnum = nullptr static protected
The enumeration registered for radio mode.
Referenced by getRadioModeName().
receivedSignalPartChangedSignal
simsignal_t inet::physicallayer::IRadio::receivedSignalPartChangedSignal = cComponent::registerSignal("receivedSignalPartChanged") static
This signal is emitted when the received part is changed by the radio.
The source is the radio and the emitted value is the new received part.
Referenced by inet::physicallayer::StateBasedEpEnergyConsumer::initialize(), inet::physicallayer::StateBasedCcEnergyConsumer::initialize(), inet::ieee80211::Ieee80211Mac::initialize(), inet::physicallayer::StateBasedEpEnergyConsumer::receiveSignal(), inet::physicallayer::StateBasedCcEnergyConsumer::receiveSignal(), inet::ieee80211::Ieee80211Mac::receiveSignal(), and inet::physicallayer::Radio::updateTransceiverPart().
receptionStateChangedSignal
simsignal_t inet::physicallayer::IRadio::receptionStateChangedSignal = cComponent::registerSignal("receptionStateChanged") static
This signal is emitted when the radio reception state of the radio is changed.
The source is the radio and the emitted value is the new radio reception state.
Referenced by inet::physicallayer::StateBasedEpEnergyConsumer::initialize(), inet::physicallayer::StateBasedCcEnergyConsumer::initialize(), inet::ieee80211::Ieee80211Mac::initialize(), inet::CsmaCaMac::initialize(), inet::ieee80211::Ieee80211MgmtSta::processScanCommand(), inet::physicallayer::StateBasedEpEnergyConsumer::receiveSignal(), inet::physicallayer::StateBasedCcEnergyConsumer::receiveSignal(), inet::ieee80211::Ieee80211Mac::receiveSignal(), inet::visualizer::RadioVisualizerBase::receiveSignal(), inet::CsmaCaMac::receiveSignal(), inet::ieee80211::Ieee80211MgmtSta::receiveSignal(), inet::ieee80211::Ieee80211MgmtSta::scanNextChannel(), inet::visualizer::RadioVisualizerBase::subscribe(), inet::visualizer::RadioVisualizerBase::unsubscribe(), and inet::physicallayer::Radio::updateTransceiverState().
receptionStateEnum
cEnum * inet::physicallayer::IRadio::receptionStateEnum = nullptr static protected
The enumeration registered for radio reception state.
Referenced by getRadioReceptionStateName().
transmissionStateChangedSignal
simsignal_t inet::physicallayer::IRadio::transmissionStateChangedSignal = cComponent::registerSignal("transmissionStateChanged") static
This signal is emitted when the radio transmission state of the radio is changed.
The source is the radio and the emitted value is the new radio transmission state.
Referenced by inet::Ieee802154Mac::handleCrashOperation(), inet::Ieee802154Mac::handleStartOperation(), inet::Ieee802154Mac::handleStopOperation(), inet::physicallayer::ShortcutRadio::handleUpperPacket(), inet::physicallayer::StateBasedEpEnergyConsumer::initialize(), inet::physicallayer::StateBasedCcEnergyConsumer::initialize(), inet::ieee80211::Ieee80211Mac::initialize(), inet::BMac::initialize(), inet::AckingMac::initialize(), inet::XMac::initialize(), inet::LMac::initialize(), inet::CsmaCaMac::initialize(), inet::AckingMac::receiveSignal(), inet::physicallayer::StateBasedEpEnergyConsumer::receiveSignal(), inet::physicallayer::StateBasedCcEnergyConsumer::receiveSignal(), inet::ieee80211::Ieee80211Mac::receiveSignal(), inet::BMac::receiveSignal(), inet::visualizer::RadioVisualizerBase::receiveSignal(), inet::XMac::receiveSignal(), inet::Ieee802154Mac::receiveSignal(), inet::LMac::receiveSignal(), inet::CsmaCaMac::receiveSignal(), inet::visualizer::RadioVisualizerBase::subscribe(), inet::visualizer::RadioVisualizerBase::unsubscribe(), and inet::physicallayer::Radio::updateTransceiverState().
transmissionStateEnum
cEnum * inet::physicallayer::IRadio::transmissionStateEnum = nullptr static protected
The enumeration registered for radio transmission state.
Referenced by getRadioTransmissionStateName().
transmittedSignalPartChangedSignal
simsignal_t inet::physicallayer::IRadio::transmittedSignalPartChangedSignal = cComponent::registerSignal("transmittedSignalPartChanged") static
This signal is emitted when the transmitted part is changed by the radio.
The source is the radio and the emitted value is the new transmitted part.
Referenced by inet::physicallayer::StateBasedEpEnergyConsumer::initialize(), inet::physicallayer::StateBasedCcEnergyConsumer::initialize(), inet::physicallayer::StateBasedEpEnergyConsumer::receiveSignal(), inet::physicallayer::StateBasedCcEnergyConsumer::receiveSignal(), and inet::physicallayer::Radio::updateTransceiverPart().
The documentation for this class was generated from the following files:
IRadio.h
IRadio.cc