INET Framework for OMNeT++/OMNEST: inet::visualizer::InfoVisualizerBase Class Reference
inet::visualizer::InfoVisualizerBase Class Reference abstract
#include <InfoVisualizerBase.h>
Classes
class DirectiveResolver
class InfoVisualization
Parameters
bool displayInfos = false
ModuleFilter modules
StringFormat format
cFigure::Font font
cFigure::Color textColor
cFigure::Color backgroundColor
double opacity = NaN
Placement placementHint
double placementPriority
std::vector< const InfoVisualization * > infoVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void refreshDisplay () const override
virtual InfoVisualization * createInfoVisualization (cModule *module) const =0
virtual void addInfoVisualization (const InfoVisualization *infoVisualization)
virtual void addInfoVisualizations ()
virtual void removeInfoVisualization (const InfoVisualization *infoVisualization)
virtual void refreshInfoVisualization (const InfoVisualization *infoVisualization, const char *info) const =0
virtual void removeAllInfoVisualizations ()
virtual const char * getInfoVisualizationText (cModule *module) const
virtual void preDelete (cComponent *root) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addInfoVisualization()
void inet::visualizer::InfoVisualizerBase::addInfoVisualization (const InfoVisualization * infoVisualization) protected virtual
Reimplemented in inet::visualizer::InfoCanvasVisualizer.
 {
     infoVisualizations.push_back(infoVisualization);
 }
Referenced by inet::visualizer::InfoCanvasVisualizer::addInfoVisualization(), and addInfoVisualizations().
addInfoVisualizations()
void inet::visualizer::InfoVisualizerBase::addInfoVisualizations () protected virtual
 {
     auto simulation = getSimulation();
     for (int id = 0; id < simulation->getLastComponentId(); id++) {
         auto component = simulation->getComponent(id);
         if (component != nullptr && component->isModule() && modules.matches(static_cast<cModule *>(component))) {
             auto infoVisualization = createInfoVisualization(static_cast<cModule *>(component));
             addInfoVisualization(infoVisualization);
         }
     }
 }
Referenced by handleParameterChange(), and initialize().
createInfoVisualization()
virtual InfoVisualization* inet::visualizer::InfoVisualizerBase::createInfoVisualization (cModule * module) const protected pure virtual
Implemented in inet::visualizer::InfoCanvasVisualizer, and inet::visualizer::InfoOsgVisualizer.
Referenced by addInfoVisualizations().
getInfoVisualizationText()
const char * inet::visualizer::InfoVisualizerBase::getInfoVisualizationText (cModule * module) const protected virtual
 {
     DirectiveResolver directiveResolver(module);
     return format.formatString(&directiveResolver);
 }
Referenced by inet::visualizer::InfoCanvasVisualizer::createInfoVisualization(), and refreshDisplay().
handleParameterChange()
void inet::visualizer::InfoVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "modules"))
             modules.setPattern(par("modules"));
         else if (!strcmp(name, "format"))
             format.parseFormat(par("format"));
         removeAllInfoVisualizations();
         addInfoVisualizations();
     }
 }
initialize()
void inet::visualizer::InfoVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::InfoCanvasVisualizer, and inet::visualizer::InfoOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayInfos = par("displayInfos");
         modules.setPattern(par("modules"));
         format.parseFormat(par("format"));
         font = cFigure::parseFont(par("font"));
         textColor = cFigure::Color(par("textColor"));
         backgroundColor = cFigure::Color(par("backgroundColor"));
         opacity = par("opacity");
         placementHint = parsePlacement(par("placementHint"));
         placementPriority = par("placementPriority");
     }
     else if (stage == INITSTAGE_LAST) {
         if (displayInfos)
             addInfoVisualizations();
     }
 }
Referenced by inet::visualizer::InfoOsgVisualizer::initialize(), and inet::visualizer::InfoCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::InfoVisualizerBase::preDelete (cComponent * root) override virtual
 {
     if (displayInfos)
         removeAllInfoVisualizations();
 }
refreshDisplay()
void inet::visualizer::InfoVisualizerBase::refreshDisplay () const override protected virtual
 {
     auto simulation = getSimulation();
     for (auto infoVisualization : infoVisualizations) {
         auto module = simulation->getModule(infoVisualization->moduleId);
         if (module != nullptr)
             refreshInfoVisualization(infoVisualization, getInfoVisualizationText(module));
     }
 }
refreshInfoVisualization()
virtual void inet::visualizer::InfoVisualizerBase::refreshInfoVisualization (const InfoVisualization * infoVisualization, const char * info) const protected pure virtual
Implemented in inet::visualizer::InfoCanvasVisualizer, and inet::visualizer::InfoOsgVisualizer.
Referenced by refreshDisplay().
removeAllInfoVisualizations()
void inet::visualizer::InfoVisualizerBase::removeAllInfoVisualizations () protected virtual
 {
     for (auto infoVisualization : std::vector<const InfoVisualization *>(infoVisualizations)) {
         removeInfoVisualization(infoVisualization);
         delete infoVisualization;
     }
 }
Referenced by handleParameterChange(), and preDelete().
removeInfoVisualization()
void inet::visualizer::InfoVisualizerBase::removeInfoVisualization (const InfoVisualization * infoVisualization) protected virtual
Reimplemented in inet::visualizer::InfoCanvasVisualizer.
 {
     infoVisualizations.erase(std::remove(infoVisualizations.begin(), infoVisualizations.end(), infoVisualization), infoVisualizations.end());
 }
Referenced by removeAllInfoVisualizations(), and inet::visualizer::InfoCanvasVisualizer::removeInfoVisualization().
Member Data Documentation
backgroundColor
cFigure::Color inet::visualizer::InfoVisualizerBase::backgroundColor protected
Referenced by inet::visualizer::InfoOsgVisualizer::createInfoVisualization(), inet::visualizer::InfoCanvasVisualizer::createInfoVisualization(), and initialize().
displayInfos
bool inet::visualizer::InfoVisualizerBase::displayInfos = false protected
Referenced by initialize(), and preDelete().
font
cFigure::Font inet::visualizer::InfoVisualizerBase::font protected
Referenced by inet::visualizer::InfoCanvasVisualizer::createInfoVisualization(), and initialize().
format
StringFormat inet::visualizer::InfoVisualizerBase::format protected
Referenced by getInfoVisualizationText(), handleParameterChange(), and initialize().
infoVisualizations
std::vector<const InfoVisualization *> inet::visualizer::InfoVisualizerBase::infoVisualizations protected
Referenced by addInfoVisualization(), inet::visualizer::InfoOsgVisualizer::initialize(), refreshDisplay(), removeAllInfoVisualizations(), and removeInfoVisualization().
modules
ModuleFilter inet::visualizer::InfoVisualizerBase::modules protected
Referenced by addInfoVisualizations(), handleParameterChange(), and initialize().
opacity
double inet::visualizer::InfoVisualizerBase::opacity = NaN protected
Referenced by inet::visualizer::InfoCanvasVisualizer::createInfoVisualization(), and initialize().
placementHint
Placement inet::visualizer::InfoVisualizerBase::placementHint protected
Referenced by inet::visualizer::InfoCanvasVisualizer::addInfoVisualization(), and initialize().
placementPriority
double inet::visualizer::InfoVisualizerBase::placementPriority protected
Referenced by inet::visualizer::InfoCanvasVisualizer::addInfoVisualization(), and initialize().
textColor
cFigure::Color inet::visualizer::InfoVisualizerBase::textColor protected
Referenced by inet::visualizer::InfoOsgVisualizer::createInfoVisualization(), inet::visualizer::InfoCanvasVisualizer::createInfoVisualization(), and initialize().
The documentation for this class was generated from the following files:
InfoVisualizerBase.h
InfoVisualizerBase.cc