INET Framework for OMNeT++/OMNEST: inet::Ipv4NetworkConfigurator::RoutingTableInfo Class Reference
inet::Ipv4NetworkConfigurator::RoutingTableInfo Class Reference
Simplified routing table representation used by the optimizer.
#include <Ipv4NetworkConfigurator.h>
Public Member Functions
RoutingTableInfo ()
~RoutingTableInfo ()
int addRouteInfo (RouteInfo *routeInfo)
void removeRouteInfo (const RouteInfo *routeInfo)
RouteInfo * findBestMatchingRouteInfo (const uint32_t destination, int begin=0, int end=-1) const
Static Public Member Functions
static RouteInfo * findBestMatchingRouteInfo (const std::vector< RouteInfo * > &routeInfos, const uint32_t destination, int begin, int end)
static bool routeInfoLessThan (const RouteInfo *a, const RouteInfo *b)
Public Attributes
std::vector< RouteInfo * > routeInfos
Detailed Description
Simplified routing table representation used by the optimizer.
Constructor & Destructor Documentation
RoutingTableInfo()
inet::Ipv4NetworkConfigurator::RoutingTableInfo::RoutingTableInfo () inline
 {}
~RoutingTableInfo()
inet::Ipv4NetworkConfigurator::RoutingTableInfo::~RoutingTableInfo () inline
 {}
Member Function Documentation
addRouteInfo()
int inet::Ipv4NetworkConfigurator::RoutingTableInfo::addRouteInfo (RouteInfo * routeInfo)
 {
     auto it = upper_bound(routeInfos.begin(), routeInfos.end(), routeInfo, routeInfoLessThan);
     int index = it - routeInfos.begin();
     routeInfos.insert(it, routeInfo);
     return index;
 }
Referenced by inet::Ipv4NetworkConfigurator::optimizeRoutes(), and inet::Ipv4NetworkConfigurator::tryToMergeTwoRoutes().
findBestMatchingRouteInfo() [1/2]
Ipv4NetworkConfigurator::RouteInfo * inet::Ipv4NetworkConfigurator::RoutingTableInfo::findBestMatchingRouteInfo (const std::vector< RouteInfo * > & routeInfos, const uint32_t destination, int begin, int end) static
 {
     for (int index = begin; index < end; index++) {
         RouteInfo *routeInfo = routeInfos.at(index);
         if (routeInfo->enabled && !((destination ^ routeInfo->destination) & routeInfo->netmask))
             return const_cast<RouteInfo *>(routeInfo);
     }
     return nullptr;
 }
findBestMatchingRouteInfo() [2/2]
RouteInfo* inet::Ipv4NetworkConfigurator::RoutingTableInfo::findBestMatchingRouteInfo (const uint32_t destination, int begin = 0, int end = -1) const inline
 { return findBestMatchingRouteInfo(routeInfos, destination, 0, end == -1 ? routeInfos.size() : end); }
Referenced by inet::Ipv4NetworkConfigurator::addOriginalRouteInfos(), inet::Ipv4NetworkConfigurator::checkOriginalRoutes(), findBestMatchingRouteInfo(), and inet::Ipv4NetworkConfigurator::interruptsOriginalRoute().
removeRouteInfo()
void inet::Ipv4NetworkConfigurator::RoutingTableInfo::removeRouteInfo (const RouteInfo * routeInfo) inline
 { routeInfos.erase(find(routeInfos.begin(), routeInfos.end(), routeInfo)); }
Referenced by inet::Ipv4NetworkConfigurator::tryToMergeTwoRoutes().
routeInfoLessThan()
static bool inet::Ipv4NetworkConfigurator::RoutingTableInfo::routeInfoLessThan (const RouteInfo * a, const RouteInfo * b) inline static
 { return a->netmask != b->netmask ? a->netmask > b->netmask : a->destination < b->destination; }
Member Data Documentation
routeInfos
std::vector<RouteInfo *> inet::Ipv4NetworkConfigurator::RoutingTableInfo::routeInfos
Referenced by inet::Ipv4NetworkConfigurator::checkOriginalRoutes(), inet::Ipv4NetworkConfigurator::interruptsSubsequentOriginalRoutes(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::Ipv4NetworkConfigurator::tryToMergeAnyTwoRoutes(), and inet::Ipv4NetworkConfigurator::tryToMergeTwoRoutes().
The documentation for this class was generated from the following files:
Ipv4NetworkConfigurator.h
Ipv4NetworkConfigurator.cc