INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta Class Reference
inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta Class Reference
#include <Ieee80211MgmtAp.h>
Public Member Functions
void setApAddress (const MacAddress &a)
void setStaAddress (const MacAddress &a)
const MacAddress & getApAddress () const
const MacAddress & getStaAddress () const
Private Attributes
MacAddress apAddress
MacAddress staAddress
Member Function Documentation
getApAddress()
const MacAddress& inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta::getApAddress () const inline
 { return apAddress; }
getStaAddress()
const MacAddress& inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta::getStaAddress () const inline
 { return staAddress; }
setApAddress()
void inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta::setApAddress (const MacAddress & a) inline
 { apAddress = a; }
Referenced by inet::ieee80211::Ieee80211MgmtAp::sendAssocNotification(), and inet::ieee80211::Ieee80211MgmtAp::sendDisAssocNotification().
setStaAddress()
void inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta::setStaAddress (const MacAddress & a) inline
 { staAddress = a; }
Referenced by inet::ieee80211::Ieee80211MgmtAp::sendAssocNotification(), and inet::ieee80211::Ieee80211MgmtAp::sendDisAssocNotification().
Member Data Documentation
apAddress
MacAddress inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta::apAddress private
staAddress
MacAddress inet::ieee80211::Ieee80211MgmtAp::NotificationInfoSta::staAddress private
The documentation for this class was generated from the following file:
Ieee80211MgmtAp.h