INET Framework for OMNeT++/OMNEST: inet::osg::TopLevelScene Class Reference
inet::osg::TopLevelScene Class Reference
This class is used for the topmost node in the OSG node hierarchy.
#include <OsgScene.h>
Public Member Functions
virtual SimulationScene * getSimulationScene ()
Static Public Member Functions
static SimulationScene * getSimulationScene (cModule *module)
Protected Attributes
SimulationScene * simulationScene = nullptr
Detailed Description
This class is used for the topmost node in the OSG node hierarchy.
The scene of the OSG canvas is a TopLevelScene instance.
Member Function Documentation
getSimulationScene() [1/2]
SimulationScene * inet::osg::TopLevelScene::getSimulationScene () virtual
 {
     if (simulationScene == nullptr) {
         FindNodesVisitor<SimulationScene> visitor;
         accept(visitor);
         auto foundNodes = visitor.getFoundNodes();
         ASSERT(foundNodes.size() == 1);
         simulationScene = check_and_cast<SimulationScene *>(foundNodes[0]);
     }
     return simulationScene;
 }
Referenced by inet::visualizer::LinkBreakOsgVisualizer::addLinkBreakVisualization(), inet::visualizer::LinkOsgVisualizerBase::addLinkVisualization(), inet::visualizer::MobilityOsgVisualizer::addMobilityVisualization(), inet::visualizer::NetworkNodeOsgVisualizer::addNetworkNodeVisualization(), inet::visualizer::TracingObstacleLossOsgVisualizer::addObstacleLossVisualization(), inet::visualizer::PacketDropOsgVisualizer::addPacketDropVisualization(), inet::visualizer::PathOsgVisualizerBase::addPathVisualization(), inet::visualizer::RoutingTableOsgVisualizer::addRouteVisualization(), inet::visualizer::NetworkConnectionOsgVisualizer::createNetworkConnectionVisualization(), getSimulationScene(), inet::visualizer::TracingObstacleLossOsgVisualizer::initialize(), inet::visualizer::SceneOsgVisualizerBase::initializeAxis(), inet::visualizer::SceneOsgVisualizerBase::initializeSceneFloor(), inet::visualizer::PhysicalEnvironmentOsgVisualizer::refreshDisplay(), inet::visualizer::MobilityOsgVisualizer::removeMobilityVisualization(), and inet::visualizer::NetworkNodeOsgVisualizer::removeNetworkNodeVisualization().
getSimulationScene() [2/2]
SimulationScene * inet::osg::TopLevelScene::getSimulationScene (cModule * module) static
 {
     auto osgCanvas = module->getOsgCanvas();
     auto topLevelScene = dynamic_cast<TopLevelScene *>(osgCanvas->getScene());
     if (topLevelScene != nullptr)
         return topLevelScene->getSimulationScene();
     else {
         auto simulationScene = new SimulationScene();
         topLevelScene = new TopLevelScene();
         topLevelScene->addChild(simulationScene);
         // NOTE: these are the default values when there's no SceneOsgVisualizer
         osgCanvas->setScene(topLevelScene);
         osgCanvas->setClearColor(cFigure::Color("#FFFFFF"));
         osgCanvas->setZNear(0.1);
         osgCanvas->setZFar(100000);
         osgCanvas->setCameraManipulatorType(cOsgCanvas::CAM_TERRAIN);
         return simulationScene;
     }
 }
Member Data Documentation
simulationScene
SimulationScene* inet::osg::TopLevelScene::simulationScene = nullptr protected
Referenced by getSimulationScene().
The documentation for this class was generated from the following files:
OsgScene.h
OsgScene.cc