INET Framework for OMNeT++/OMNEST: inet::power::CcEnergyStorageBase Class Reference
inet::power::CcEnergyStorageBase Class Reference
#include <CcEnergyStorageBase.h>
Public Member Functions
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
virtual void receiveSignal (cComponent *source, simsignal_t signal, double value, cObject *details) override
Public Member Functions inherited from inet::power::CcEnergySourceBase
virtual A getTotalCurrentConsumption () const override
Returns the total current consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Public Member Functions inherited from inet::power::ICcEnergySource
virtual V getNominalVoltage () const =0
Returns the open circuit voltage in the range [0, +infinity).
virtual V getOutputVoltage () const =0
Returns the output voltage in the ragne [0, +infinity).
Public Member Functions inherited from inet::power::CcEnergySinkBase
virtual A getTotalCurrentGeneration () const override
Returns the total current generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Public Member Functions inherited from inet::power::ICcEnergyStorage
virtual C getNominalChargeCapacity () const =0
Returns the nominal charge capacity in the range [0, +infinity).
virtual C getResidualChargeCapacity () const =0
Returns the residual charge capacity in the range [0, nominalCapacity].
Protected Member Functions
virtual void initialize (int stage) override
virtual void updateTotalCurrentConsumption () override
virtual void updateTotalCurrentGeneration () override
Protected Member Functions inherited from inet::power::CcEnergySourceBase
virtual A computeTotalCurrentConsumption () const
Protected Member Functions inherited from inet::power::CcEnergySinkBase
virtual A computeTotalCurrentGeneration () const
Additional Inherited Members
Static Public Attributes inherited from inet::power::ICcEnergySource
static simsignal_t currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged")
The signal that is used to publish current consumption changes.
Static Public Attributes inherited from inet::power::ICcEnergySink
static simsignal_t currentGenerationChangedSignal = cComponent::registerSignal("currentGenerationChanged")
The signal that is used to publish current generation changes.
Static Public Attributes inherited from inet::power::ICcEnergyStorage
static simsignal_t residualChargeCapacityChangedSignal = cComponent::registerSignal("residualChargeCapacityChanged")
The signal that is used to publish residual charge capacity changes also including when the energy storage becomes completely depleted or charged.
Protected Attributes inherited from inet::power::CcEnergySourceBase
A totalCurrentConsumption = A(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Protected Attributes inherited from inet::power::CcEnergySinkBase
A totalCurrentGeneration = A(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Member Function Documentation
addEnergyConsumer()
void inet::power::CcEnergyStorageBase::addEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Adds a new energy consumer to the energy source.
The energyConsumer parameter must not be nullptr.
Reimplemented from inet::power::CcEnergySourceBase.
 {
     Enter_Method("addEnergyConsumer");
     CcEnergySourceBase::addEnergyConsumer(energyConsumer);
 }
addEnergyGenerator()
void inet::power::CcEnergyStorageBase::addEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Adds a new energy generator to the energy sink.
The energyGenerator parameter must not be nullptr.
Reimplemented from inet::power::CcEnergySinkBase.
 {
     Enter_Method("addEnergyGenerator");
     CcEnergySinkBase::addEnergyGenerator(energyGenerator);
 }
initialize()
void inet::power::CcEnergyStorageBase::initialize (int stage) override protected virtual
Reimplemented in inet::power::SimpleCcBattery.
 {
     if (stage == INITSTAGE_LOCAL) {
         totalCurrentConsumption = computeTotalCurrentConsumption();
         totalCurrentGeneration = computeTotalCurrentGeneration();
         WATCH(totalCurrentConsumption);
         WATCH(totalCurrentGeneration);
     }
 }
Referenced by inet::power::SimpleCcBattery::initialize().
receiveSignal()
void inet::power::CcEnergyStorageBase::receiveSignal (cComponent * source, simsignal_t signal, double value, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == ICcEnergyConsumer::currentConsumptionChangedSignal)
         updateTotalCurrentConsumption();
     else if (signal == ICcEnergyGenerator::currentGenerationChangedSignal)
         updateTotalCurrentGeneration();
 }
removeEnergyConsumer()
void inet::power::CcEnergyStorageBase::removeEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Removes a previously added energy consumer from this energy source.
This functions throws an exception if the consumer is not found.
Reimplemented from inet::power::CcEnergySourceBase.
 {
     Enter_Method("removeEnergyConsumer");
     CcEnergySourceBase::removeEnergyConsumer(energyConsumer);
 }
removeEnergyGenerator()
void inet::power::CcEnergyStorageBase::removeEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Removes a previously added energy generator from this energy sink.
This functions throws an exception if the generator is not found.
Reimplemented from inet::power::CcEnergySinkBase.
 {
     Enter_Method("removeEnergyGenerator");
     CcEnergySinkBase::removeEnergyGenerator(energyGenerator);
 }
updateTotalCurrentConsumption()
void inet::power::CcEnergyStorageBase::updateTotalCurrentConsumption () override protected virtual
Reimplemented from inet::power::CcEnergySourceBase.
Reimplemented in inet::power::SimpleCcBattery.
 {
     CcEnergySourceBase::updateTotalCurrentConsumption();
     emit(currentConsumptionChangedSignal, totalCurrentConsumption.get());
 }
Referenced by receiveSignal(), and inet::power::SimpleCcBattery::updateTotalCurrentConsumption().
updateTotalCurrentGeneration()
void inet::power::CcEnergyStorageBase::updateTotalCurrentGeneration () override protected virtual
Reimplemented from inet::power::CcEnergySinkBase.
Reimplemented in inet::power::SimpleCcBattery.
 {
     CcEnergySinkBase::updateTotalCurrentGeneration();
     emit(currentGenerationChangedSignal, totalCurrentGeneration.get());
 }
Referenced by receiveSignal(), and inet::power::SimpleCcBattery::updateTotalCurrentGeneration().
The documentation for this class was generated from the following files:
CcEnergyStorageBase.h
CcEnergyStorageBase.cc