INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211VhtModeBase Class Reference
inet::physicallayer::Ieee80211VhtModeBase Class Reference abstract
#include <Ieee80211VhtMode.h>
Public Types
enum GuardIntervalType { HT_GUARD_INTERVAL_SHORT, HT_GUARD_INTERVAL_LONG }
Public Member Functions
Ieee80211VhtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
virtual int getNumberOfDataSubcarriers () const
virtual int getNumberOfPilotSubcarriers () const
virtual int getNumberOfTotalSubcarriers () const
virtual GuardIntervalType getGuardIntervalType () const
virtual int getNumberOfSpatialStreams () const
virtual unsigned int getMcsIndex () const
virtual Hz getBandwidth () const
virtual bps getNetBitrate () const
virtual bps getGrossBitrate () const
Protected Member Functions
virtual bps computeGrossBitrate () const =0
virtual bps computeNetBitrate () const =0
Protected Attributes
const Hz bandwidth
const GuardIntervalType guardIntervalType
const unsigned int mcsIndex
const unsigned int numberOfSpatialStreams
bps netBitrate
bps grossBitrate
Member Enumeration Documentation
GuardIntervalType
enum inet::physicallayer::Ieee80211VhtModeBase::GuardIntervalType
Enumerator
HT_GUARD_INTERVAL_SHORT
HT_GUARD_INTERVAL_LONG
{
         HT_GUARD_INTERVAL_SHORT, // 400 ns
         HT_GUARD_INTERVAL_LONG // 800 ns
     };
Constructor & Destructor Documentation
Ieee80211VhtModeBase()
inet::physicallayer::Ieee80211VhtModeBase::Ieee80211VhtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
                                                                                                                                                                                :
     bandwidth(bandwidth),
     guardIntervalType(guardIntervalType),
     mcsIndex(modulationAndCodingScheme),
     numberOfSpatialStreams(numberOfSpatialStreams),
     netBitrate(bps(NaN)),
     grossBitrate(bps(NaN))
 {
 }
Member Function Documentation
computeGrossBitrate()
virtual bps inet::physicallayer::Ieee80211VhtModeBase::computeGrossBitrate () const protected pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, and inet::physicallayer::Ieee80211VhtSignalMode.
Referenced by getGrossBitrate().
computeNetBitrate()
virtual bps inet::physicallayer::Ieee80211VhtModeBase::computeNetBitrate () const protected pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, and inet::physicallayer::Ieee80211VhtSignalMode.
Referenced by getNetBitrate().
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211VhtModeBase::getBandwidth () const inline virtual
Reimplemented in inet::physicallayer::Ieee80211VhtDataMode.
 { return bandwidth; }
getGrossBitrate()
bps inet::physicallayer::Ieee80211VhtModeBase::getGrossBitrate () const virtual
Reimplemented in inet::physicallayer::Ieee80211VhtDataMode, and inet::physicallayer::Ieee80211VhtSignalMode.
 {
     if (std::isnan(grossBitrate.get()))
         grossBitrate = computeGrossBitrate();
     return grossBitrate;
 }
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::getGrossBitrate(), and inet::physicallayer::Ieee80211VhtDataMode::getGrossBitrate().
getGuardIntervalType()
virtual GuardIntervalType inet::physicallayer::Ieee80211VhtModeBase::getGuardIntervalType () const inline virtual
 { return guardIntervalType; }
getMcsIndex()
virtual unsigned int inet::physicallayer::Ieee80211VhtModeBase::getMcsIndex () const inline virtual
 { return mcsIndex; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders160MHz(), inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders20MHz(), inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders40MHz(), and inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders80MHz().
getNetBitrate()
bps inet::physicallayer::Ieee80211VhtModeBase::getNetBitrate () const virtual
Reimplemented in inet::physicallayer::Ieee80211VhtDataMode, and inet::physicallayer::Ieee80211VhtSignalMode.
 {
     if (std::isnan(netBitrate.get()))
         netBitrate = computeNetBitrate();
     return netBitrate;
 }
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::getNetBitrate(), and inet::physicallayer::Ieee80211VhtDataMode::getNetBitrate().
getNumberOfDataSubcarriers()
int inet::physicallayer::Ieee80211VhtModeBase::getNumberOfDataSubcarriers () const virtual
 {
     if (bandwidth == MHz(20))
         return 52;
     else if (bandwidth == MHz(40))
         return 108;
     else if (bandwidth == MHz(80))
         return 234;
     else if (bandwidth == MHz(160))
         return 468;
     else
         throw cRuntimeError("Unsupported bandwidth");
 }
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211VhtDataMode::computeGrossBitrate(), and inet::physicallayer::Ieee80211VhtDataMode::getDuration().
getNumberOfPilotSubcarriers()
int inet::physicallayer::Ieee80211VhtModeBase::getNumberOfPilotSubcarriers () const virtual
 {
     if (bandwidth == MHz(20))
         return 4;
     else if (bandwidth == MHz(40))
         // It is a spacial case, see the comment above.
         return 6;
     else if (bandwidth == MHz(80))
         // It is a spacial case, see the comment above.
         return 8;
     else if (bandwidth == MHz(160))
         // It is a spacial case, see the comment above.
         return 16;
     else
         throw cRuntimeError("Unsupported bandwidth");
 }
getNumberOfSpatialStreams()
virtual int inet::physicallayer::Ieee80211VhtModeBase::getNumberOfSpatialStreams () const inline virtual
Reimplemented in inet::physicallayer::Ieee80211VhtDataMode.
 { return numberOfSpatialStreams; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::getNumberOfSpatialStreams().
getNumberOfTotalSubcarriers()
virtual int inet::physicallayer::Ieee80211VhtModeBase::getNumberOfTotalSubcarriers () const inline virtual
 { return getNumberOfDataSubcarriers() + getNumberOfPilotSubcarriers(); }
Member Data Documentation
bandwidth
const Hz inet::physicallayer::Ieee80211VhtModeBase::bandwidth protected
Referenced by getNumberOfDataSubcarriers(), and getNumberOfPilotSubcarriers().
grossBitrate
bps inet::physicallayer::Ieee80211VhtModeBase::grossBitrate mutable protected
Referenced by getGrossBitrate().
guardIntervalType
const GuardIntervalType inet::physicallayer::Ieee80211VhtModeBase::guardIntervalType protected
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate(), and inet::physicallayer::Ieee80211VhtDataMode::computeGrossBitrate().
mcsIndex
const unsigned int inet::physicallayer::Ieee80211VhtModeBase::mcsIndex protected
netBitrate
bps inet::physicallayer::Ieee80211VhtModeBase::netBitrate mutable protected
Referenced by getNetBitrate().
numberOfSpatialStreams
const unsigned int inet::physicallayer::Ieee80211VhtModeBase::numberOfSpatialStreams protected
The documentation for this class was generated from the following files:
Ieee80211VhtMode.h
Ieee80211VhtMode.cc