INET Framework for OMNeT++/OMNEST: inet::ospfv2::RouterLsa Class Reference
inet::ospfv2::RouterLsa Class Reference
#include <Lsa.h>
Public Member Functions
RouterLsa ()
RouterLsa (const Ospfv2RouterLsa &lsa)
RouterLsa (const RouterLsa &lsa)
virtual ~RouterLsa ()
bool validateLSChecksum () const
bool update (const Ospfv2RouterLsa *lsa)
bool differsFrom (const Ospfv2RouterLsa *routerLSA) const
Public Member Functions inherited from inet::ospfv2::Ospfv2RouterLsa
Ospfv2RouterLsa ()
Ospfv2RouterLsa (const Ospfv2RouterLsa &other)
virtual ~Ospfv2RouterLsa ()
Ospfv2RouterLsa & operator= (const Ospfv2RouterLsa &other)
virtual Ospfv2RouterLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getReserved1 () const
virtual void setReserved1 (unsigned short reserved1)
virtual bool getV_VirtualLinkEndpoint () const
virtual void setV_VirtualLinkEndpoint (bool V_VirtualLinkEndpoint)
virtual bool getE_ASBoundaryRouter () const
virtual void setE_ASBoundaryRouter (bool E_ASBoundaryRouter)
virtual bool getB_AreaBorderRouter () const
virtual void setB_AreaBorderRouter (bool B_AreaBorderRouter)
virtual unsigned short getReserved2 () const
virtual void setReserved2 (unsigned short reserved2)
virtual unsigned short getNumberOfLinks () const
virtual void setNumberOfLinks (unsigned short numberOfLinks)
virtual void setLinksArraySize (size_t size)
virtual size_t getLinksArraySize () const
virtual const Ospfv2Link & getLinks (size_t k) const
virtual Ospfv2Link & getLinksForUpdate (size_t k)
virtual void setLinks (size_t k, const Ospfv2Link &links)
virtual void insertLinks (size_t k, const Ospfv2Link &links)
void insertLinks (const Ospfv2Link &links)
virtual void appendLinks (const Ospfv2Link &links)
virtual void eraseLinks (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Public Member Functions inherited from inet::ospfv2::RoutingInfo
RoutingInfo ()
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo ()
void addNextHop (NextHop nextHop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
void setDistance (unsigned long d)
unsigned long getDistance () const
void setParent (Ospfv2Lsa *p)
Ospfv2Lsa * getParent () const
Public Member Functions inherited from inet::ospfv2::LsaTrackingInfo
LsaTrackingInfo ()
LsaTrackingInfo (const LsaTrackingInfo &info)
void setSource (InstallSource installSource)
InstallSource getSource () const
void incrementInstallTime ()
void resetInstallTime ()
unsigned long getInstallTime () const
Additional Inherited Members
Public Types inherited from inet::ospfv2::LsaTrackingInfo
enum InstallSource { ORIGINATED = 0, FLOODED = 1 }
Protected Member Functions inherited from inet::ospfv2::Ospfv2RouterLsa
bool operator== (const Ospfv2RouterLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes inherited from inet::ospfv2::Ospfv2RouterLsa
unsigned short reserved1 = 0
bool V_VirtualLinkEndpoint = false
bool E_ASBoundaryRouter = false
bool B_AreaBorderRouter = false
unsigned short reserved2 = 0
unsigned short numberOfLinks = 0
Ospfv2Link * links = nullptr
size_t links_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Constructor & Destructor Documentation
RouterLsa() [1/3]
inet::ospfv2::RouterLsa::RouterLsa () inline
 : Ospfv2RouterLsa(), RoutingInfo(), LsaTrackingInfo() {}
RouterLsa() [2/3]
inet::ospfv2::RouterLsa::RouterLsa (const Ospfv2RouterLsa & lsa) inline
 : Ospfv2RouterLsa(lsa), RoutingInfo(), LsaTrackingInfo() {}
RouterLsa() [3/3]
inet::ospfv2::RouterLsa::RouterLsa (const RouterLsa & lsa) inline
 : Ospfv2RouterLsa(lsa), RoutingInfo(lsa), LsaTrackingInfo(lsa) {}
~RouterLsa()
virtual inet::ospfv2::RouterLsa::~RouterLsa () inline virtual
 {}
Member Function Documentation
differsFrom()
bool inet::ospfv2::RouterLsa::differsFrom (const Ospfv2RouterLsa * routerLSA) const
 {
     const Ospfv2LsaHeader& thisHeader = getHeader();
     const Ospfv2LsaHeader& lsaHeader = routerLSA->getHeader();
     bool differentHeader = ((thisHeader.getLsOptions() != lsaHeader.getLsOptions()) ||
                             ((thisHeader.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                             ((thisHeader.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                             (thisHeader.getLsaLength() != lsaHeader.getLsaLength()));
     bool differentBody = false;
     if (!differentHeader) {
         differentBody = ((getV_VirtualLinkEndpoint() != routerLSA->getV_VirtualLinkEndpoint()) ||
                          (getE_ASBoundaryRouter() != routerLSA->getE_ASBoundaryRouter()) ||
                          (getB_AreaBorderRouter() != routerLSA->getB_AreaBorderRouter()) ||
                          (getNumberOfLinks() != routerLSA->getNumberOfLinks()) ||
                          (getLinksArraySize() != routerLSA->getLinksArraySize()));
         if (!differentBody) {
             unsigned int linkCount = links_arraysize;
             for (unsigned int i = 0; i < linkCount; i++) {
                 auto thisLink = getLinks(i);
                 auto lsaLink = routerLSA->getLinks(i);
                 bool differentLink = ((thisLink.getLinkID() != lsaLink.getLinkID()) ||
                                       (thisLink.getLinkData() != lsaLink.getLinkData()) ||
                                       (thisLink.getType() != lsaLink.getType()) ||
                                       (thisLink.getNumberOfTOS() != lsaLink.getNumberOfTOS()) ||
                                       (thisLink.getLinkCost() != lsaLink.getLinkCost()) ||
                                       (thisLink.getTosDataArraySize() != lsaLink.getTosDataArraySize()));
                 if (!differentLink) {
                     unsigned int tosCount = thisLink.getTosDataArraySize();
                     for (unsigned int j = 0; j < tosCount; j++) {
                         bool differentTOS = ((thisLink.getTosData(j).tos != lsaLink.getTosData(j).tos) ||
                                              (thisLink.getTosData(j).tosMetric != lsaLink.getTosData(j).tosMetric));
                         if (differentTOS) {
                             differentLink = true;
                             break;
                         }
                     }
                 }
                 if (differentLink) {
                     differentBody = true;
                     break;
                 }
             }
         }
     }
     return differentHeader || differentBody;
 }
Referenced by update().
update()
bool inet::ospfv2::RouterLsa::update (const Ospfv2RouterLsa * lsa)
 {
     bool different = differsFrom(lsa);
     (*this) = (*lsa);
     resetInstallTime();
     if (different) {
         clearNextHops();
         return true;
     }
     else {
         return false;
     }
 }
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::HelloHandler::processPacket(), and inet::ospfv2::NeighborState::updateLsa().
validateLSChecksum()
bool inet::ospfv2::RouterLsa::validateLSChecksum () const inline
 { return true; } // not implemented
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase().
The documentation for this class was generated from the following files:
Lsa.h
RouterLsa.cc