INET Framework for OMNeT++/OMNEST: inet::ModuleIdAddress Class Reference
inet::ModuleIdAddress Class Reference
This class provides network addresses using the module id of interface modules.
#include <ModuleIdAddress.h>
Public Member Functions
ModuleIdAddress ()
ModuleIdAddress (int id)
int getId () const
bool tryParse (const char *addr)
bool isUnspecified () const
bool isUnicast () const
bool isMulticast () const
bool isBroadcast () const
bool operator== (const ModuleIdAddress &addr1) const
Returns equals(addr).
bool operator!= (const ModuleIdAddress &addr1) const
Returns !equals(addr).
bool operator< (const ModuleIdAddress &addr1) const
Compares two addresses.
bool operator<= (const ModuleIdAddress &addr1) const
bool operator> (const ModuleIdAddress &addr1) const
bool operator>= (const ModuleIdAddress &addr1) const
std::string str () const
Private Attributes
int id
Detailed Description
This class provides network addresses using the module id of interface modules.
The module id address supports unspecified, broadcast and multicast addresses too. This class doesn't support address prefixes.
Constructor & Destructor Documentation
ModuleIdAddress() [1/2]
inet::ModuleIdAddress::ModuleIdAddress () inline
 : id(0) {}
ModuleIdAddress() [2/2]
inet::ModuleIdAddress::ModuleIdAddress (int id) inline
 : id(id) {}
Member Function Documentation
getId()
int inet::ModuleIdAddress::getId () const inline
 { return id; }
Referenced by inet::L3Address::mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), and inet::L3Address::set().
isBroadcast()
bool inet::ModuleIdAddress::isBroadcast () const inline
 { return id == -1; }
Referenced by inet::L3Address::isBroadcast().
isMulticast()
bool inet::ModuleIdAddress::isMulticast () const inline
 { return id < -1; }
Referenced by inet::L3Address::isMulticast().
isUnicast()
bool inet::ModuleIdAddress::isUnicast () const inline
 { return id > 0; }
Referenced by inet::L3Address::isUnicast().
isUnspecified()
bool inet::ModuleIdAddress::isUnspecified () const inline
 { return id == 0; }
Referenced by inet::L3Address::isUnspecified().
operator!=()
bool inet::ModuleIdAddress::operator!= (const ModuleIdAddress & addr1) const inline
Returns !equals(addr).
 { return id != addr1.id; }
operator<()
bool inet::ModuleIdAddress::operator< (const ModuleIdAddress & addr1) const inline
Compares two addresses.
 { return id < addr1.id; }
operator<=()
bool inet::ModuleIdAddress::operator<= (const ModuleIdAddress & addr1) const inline
 { return id <= addr1.id; }
operator==()
bool inet::ModuleIdAddress::operator== (const ModuleIdAddress & addr1) const inline
Returns equals(addr).
 { return id == addr1.id; }
operator>()
bool inet::ModuleIdAddress::operator> (const ModuleIdAddress & addr1) const inline
 { return id > addr1.id; }
operator>=()
bool inet::ModuleIdAddress::operator>= (const ModuleIdAddress & addr1) const inline
 { return id >= addr1.id; }
str()
std::string inet::ModuleIdAddress::str () const inline
 { std::ostringstream s; s << id; return s.str(); }
Referenced by inet::L3Address::str().
tryParse()
bool inet::ModuleIdAddress::tryParse (const char * addr)
 {
     char *endp;
     id = strtol(addr, &endp, 10);
     return *endp == 0;
 }
Referenced by inet::L3Address::tryParse(), and inet::L3AddressResolver::tryParse().
Member Data Documentation
id
int inet::ModuleIdAddress::id private
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
The documentation for this class was generated from the following files:
ModuleIdAddress.h
ModuleIdAddress.cc