INET Framework for OMNeT++/OMNEST: inet::TcpStatusInfo Class Reference
inet::TcpStatusInfo Class Reference
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:191 by opp_msgtool.
#include <TcpCommand_m.h>
Public Member Functions
TcpStatusInfo ()
TcpStatusInfo (const TcpStatusInfo &other)
virtual ~TcpStatusInfo ()
TcpStatusInfo & operator= (const TcpStatusInfo &other)
virtual TcpStatusInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getState () const
virtual void setState (int state)
virtual const char * getStateName () const
virtual void setStateName (const char *stateName)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual unsigned int getSnd_mss () const
virtual void setSnd_mss (unsigned int snd_mss)
virtual unsigned int getSnd_una () const
virtual void setSnd_una (unsigned int snd_una)
virtual unsigned int getSnd_nxt () const
virtual void setSnd_nxt (unsigned int snd_nxt)
virtual unsigned int getSnd_max () const
virtual void setSnd_max (unsigned int snd_max)
virtual unsigned int getSnd_wnd () const
virtual void setSnd_wnd (unsigned int snd_wnd)
virtual unsigned int getSnd_up () const
virtual void setSnd_up (unsigned int snd_up)
virtual unsigned int getSnd_wl1 () const
virtual void setSnd_wl1 (unsigned int snd_wl1)
virtual unsigned int getSnd_wl2 () const
virtual void setSnd_wl2 (unsigned int snd_wl2)
virtual unsigned int getIss () const
virtual void setIss (unsigned int iss)
virtual unsigned int getRcv_nxt () const
virtual void setRcv_nxt (unsigned int rcv_nxt)
virtual unsigned int getRcv_wnd () const
virtual void setRcv_wnd (unsigned int rcv_wnd)
virtual unsigned int getRcv_up () const
virtual void setRcv_up (unsigned int rcv_up)
virtual unsigned int getIrs () const
virtual void setIrs (unsigned int irs)
virtual bool getFin_ack_rcvd () const
virtual void setFin_ack_rcvd (bool fin_ack_rcvd)
Public Member Functions inherited from inet::TcpCommand
TcpCommand ()
TcpCommand (const TcpCommand &other)
virtual ~TcpCommand ()
TcpCommand & operator= (const TcpCommand &other)
virtual int getUserId () const
virtual void setUserId (int userId)
Protected Member Functions
bool operator== (const TcpStatusInfo &)=delete
Protected Member Functions inherited from inet::TcpCommand
bool operator== (const TcpCommand &)=delete
Protected Attributes
int state = 0
::omnetpp::opp_string stateName
L3Address localAddr
L3Address remoteAddr
int localPort = 0
int remotePort = 0
unsigned int snd_mss = 0
unsigned int snd_una = 0
unsigned int snd_nxt = 0
unsigned int snd_max = 0
unsigned int snd_wnd = 0
unsigned int snd_up = 0
unsigned int snd_wl1 = 0
unsigned int snd_wl2 = 0
unsigned int iss = 0
unsigned int rcv_nxt = 0
unsigned int rcv_wnd = 0
unsigned int rcv_up = 0
unsigned int irs = 0
bool fin_ack_rcvd = false
Protected Attributes inherited from inet::TcpCommand
int userId = -1
Private Member Functions
void copy (const TcpStatusInfo &other)
Detailed Description
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:191 by opp_msgtool.
//
// Sent with message kind TCP_I_STATUS, in response to command TCP_C_STATUS.
// For explanation of variables, see RFC 793 or TcpStateVariables in
// TcpConnection.h.
//
// @see ~TcpStatusInd, ~TcpCommandCode, ~ITcp
//
class TcpStatusInfo extends TcpCommand
{
    int state;
    string stateName;
    L3Address localAddr;
    L3Address remoteAddr;
    int localPort;
    int remotePort;
    unsigned int snd_mss;
    unsigned int snd_una;
    unsigned int snd_nxt;
    unsigned int snd_max;
    unsigned int snd_wnd;
    unsigned int snd_up;
    unsigned int snd_wl1;
    unsigned int snd_wl2;
    unsigned int iss;
    unsigned int rcv_nxt;
    unsigned int rcv_wnd;
    unsigned int rcv_up;
    unsigned int irs;
    bool fin_ack_rcvd;
}
Constructor & Destructor Documentation
TcpStatusInfo() [1/2]
inet::TcpStatusInfo::TcpStatusInfo ()
TcpStatusInfo() [2/2]
inet::TcpStatusInfo::TcpStatusInfo (const TcpStatusInfo & other)
~TcpStatusInfo()
virtual inet::TcpStatusInfo::~TcpStatusInfo () virtual
Member Function Documentation
copy()
void inet::TcpStatusInfo::copy (const TcpStatusInfo & other) private
dup()
virtual TcpStatusInfo* inet::TcpStatusInfo::dup () const inline override virtual
Reimplemented from inet::TcpCommand.
 {return new TcpStatusInfo(*this);}
getFin_ack_rcvd()
virtual bool inet::TcpStatusInfo::getFin_ack_rcvd () const virtual
getIrs()
virtual unsigned int inet::TcpStatusInfo::getIrs () const virtual
getIss()
virtual unsigned int inet::TcpStatusInfo::getIss () const virtual
getLocalAddr()
virtual const L3Address& inet::TcpStatusInfo::getLocalAddr () const virtual
getLocalAddrForUpdate()
virtual L3Address& inet::TcpStatusInfo::getLocalAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<TcpStatusInfo*>(this)->getLocalAddr());}
getLocalPort()
virtual int inet::TcpStatusInfo::getLocalPort () const virtual
getRcv_nxt()
virtual unsigned int inet::TcpStatusInfo::getRcv_nxt () const virtual
getRcv_up()
virtual unsigned int inet::TcpStatusInfo::getRcv_up () const virtual
getRcv_wnd()
virtual unsigned int inet::TcpStatusInfo::getRcv_wnd () const virtual
getRemoteAddr()
virtual const L3Address& inet::TcpStatusInfo::getRemoteAddr () const virtual
getRemoteAddrForUpdate()
virtual L3Address& inet::TcpStatusInfo::getRemoteAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<TcpStatusInfo*>(this)->getRemoteAddr());}
getRemotePort()
virtual int inet::TcpStatusInfo::getRemotePort () const virtual
getSnd_max()
virtual unsigned int inet::TcpStatusInfo::getSnd_max () const virtual
getSnd_mss()
virtual unsigned int inet::TcpStatusInfo::getSnd_mss () const virtual
getSnd_nxt()
virtual unsigned int inet::TcpStatusInfo::getSnd_nxt () const virtual
getSnd_una()
virtual unsigned int inet::TcpStatusInfo::getSnd_una () const virtual
getSnd_up()
virtual unsigned int inet::TcpStatusInfo::getSnd_up () const virtual
getSnd_wl1()
virtual unsigned int inet::TcpStatusInfo::getSnd_wl1 () const virtual
getSnd_wl2()
virtual unsigned int inet::TcpStatusInfo::getSnd_wl2 () const virtual
getSnd_wnd()
virtual unsigned int inet::TcpStatusInfo::getSnd_wnd () const virtual
getState()
virtual int inet::TcpStatusInfo::getState () const virtual
getStateName()
virtual const char* inet::TcpStatusInfo::getStateName () const virtual
operator=()
TcpStatusInfo& inet::TcpStatusInfo::operator= (const TcpStatusInfo & other)
operator==()
bool inet::TcpStatusInfo::operator== (const TcpStatusInfo &) protected delete
parsimPack()
virtual void inet::TcpStatusInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::TcpCommand.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TcpStatusInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::TcpCommand.
Referenced by inet::doParsimUnpacking().
setFin_ack_rcvd()
virtual void inet::TcpStatusInfo::setFin_ack_rcvd (bool fin_ack_rcvd) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setIrs()
virtual void inet::TcpStatusInfo::setIrs (unsigned int irs) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setIss()
virtual void inet::TcpStatusInfo::setIss (unsigned int iss) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setLocalAddr()
virtual void inet::TcpStatusInfo::setLocalAddr (const L3Address & localAddr) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setLocalPort()
virtual void inet::TcpStatusInfo::setLocalPort (int localPort) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setRcv_nxt()
virtual void inet::TcpStatusInfo::setRcv_nxt (unsigned int rcv_nxt) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setRcv_up()
virtual void inet::TcpStatusInfo::setRcv_up (unsigned int rcv_up) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setRcv_wnd()
virtual void inet::TcpStatusInfo::setRcv_wnd (unsigned int rcv_wnd) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setRemoteAddr()
virtual void inet::TcpStatusInfo::setRemoteAddr (const L3Address & remoteAddr) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setRemotePort()
virtual void inet::TcpStatusInfo::setRemotePort (int remotePort) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setSnd_max()
virtual void inet::TcpStatusInfo::setSnd_max (unsigned int snd_max) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setSnd_mss()
virtual void inet::TcpStatusInfo::setSnd_mss (unsigned int snd_mss) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setSnd_nxt()
virtual void inet::TcpStatusInfo::setSnd_nxt (unsigned int snd_nxt) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setSnd_una()
virtual void inet::TcpStatusInfo::setSnd_una (unsigned int snd_una) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setSnd_up()
virtual void inet::TcpStatusInfo::setSnd_up (unsigned int snd_up) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setSnd_wl1()
virtual void inet::TcpStatusInfo::setSnd_wl1 (unsigned int snd_wl1) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setSnd_wl2()
virtual void inet::TcpStatusInfo::setSnd_wl2 (unsigned int snd_wl2) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setSnd_wnd()
virtual void inet::TcpStatusInfo::setSnd_wnd (unsigned int snd_wnd) virtual
Referenced by inet::tcp::TcpLwipConnection::fillStatusInfo(), and inet::tcp::TcpConnection::process_STATUS().
setState()
virtual void inet::TcpStatusInfo::setState (int state) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
setStateName()
virtual void inet::TcpStatusInfo::setStateName (const char * stateName) virtual
Referenced by inet::tcp::TcpConnection::process_STATUS().
Member Data Documentation
fin_ack_rcvd
bool inet::TcpStatusInfo::fin_ack_rcvd = false protected
irs
unsigned int inet::TcpStatusInfo::irs = 0 protected
iss
unsigned int inet::TcpStatusInfo::iss = 0 protected
localAddr
L3Address inet::TcpStatusInfo::localAddr protected
localPort
int inet::TcpStatusInfo::localPort = 0 protected
rcv_nxt
unsigned int inet::TcpStatusInfo::rcv_nxt = 0 protected
rcv_up
unsigned int inet::TcpStatusInfo::rcv_up = 0 protected
rcv_wnd
unsigned int inet::TcpStatusInfo::rcv_wnd = 0 protected
remoteAddr
L3Address inet::TcpStatusInfo::remoteAddr protected
remotePort
int inet::TcpStatusInfo::remotePort = 0 protected
snd_max
unsigned int inet::TcpStatusInfo::snd_max = 0 protected
snd_mss
unsigned int inet::TcpStatusInfo::snd_mss = 0 protected
snd_nxt
unsigned int inet::TcpStatusInfo::snd_nxt = 0 protected
snd_una
unsigned int inet::TcpStatusInfo::snd_una = 0 protected
snd_up
unsigned int inet::TcpStatusInfo::snd_up = 0 protected
snd_wl1
unsigned int inet::TcpStatusInfo::snd_wl1 = 0 protected
snd_wl2
unsigned int inet::TcpStatusInfo::snd_wl2 = 0 protected
snd_wnd
unsigned int inet::TcpStatusInfo::snd_wnd = 0 protected
state
int inet::TcpStatusInfo::state = 0 protected
stateName
::omnetpp::opp_string inet::TcpStatusInfo::stateName protected
The documentation for this class was generated from the following file:
TcpCommand_m.h