INET Framework for OMNeT++/OMNEST: inet::sctp::SctpCookie Class Reference
inet::sctp::SctpCookie Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:100 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpCookie (const char *name=nullptr)
SctpCookie (const SctpCookie &other)
virtual ~SctpCookie ()
SctpCookie & operator= (const SctpCookie &other)
virtual SctpCookie * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual ::omnetpp::simtime_t getCreationTime () const
virtual void setCreationTime (::omnetpp::simtime_t creationTime)
virtual uint32_t getLocalTag () const
virtual void setLocalTag (uint32_t localTag)
virtual uint32_t getPeerTag () const
virtual void setPeerTag (uint32_t peerTag)
virtual void setLocalTieTagArraySize (size_t size)
virtual size_t getLocalTieTagArraySize () const
virtual uint8_t getLocalTieTag (size_t k) const
virtual void setLocalTieTag (size_t k, uint8_t localTieTag)
virtual void insertLocalTieTag (size_t k, uint8_t localTieTag)
void insertLocalTieTag (uint8_t localTieTag)
virtual void appendLocalTieTag (uint8_t localTieTag)
virtual void eraseLocalTieTag (size_t k)
virtual void setPeerTieTagArraySize (size_t size)
virtual size_t getPeerTieTagArraySize () const
virtual uint8_t getPeerTieTag (size_t k) const
virtual void setPeerTieTag (size_t k, uint8_t peerTieTag)
virtual void insertPeerTieTag (size_t k, uint8_t peerTieTag)
void insertPeerTieTag (uint8_t peerTieTag)
virtual void appendPeerTieTag (uint8_t peerTieTag)
virtual void erasePeerTieTag (size_t k)
virtual uint32_t getLength () const
virtual void setLength (uint32_t length)
Protected Member Functions
bool operator== (const SctpCookie &)=delete
Protected Attributes
::omnetpp::simtime_t creationTime = SIMTIME_ZERO
uint32_t localTag = 0
uint32_t peerTag = 0
uint8_t * localTieTag = nullptr
size_t localTieTag_arraysize = 0
uint8_t * peerTieTag = nullptr
size_t peerTieTag_arraysize = 0
uint32_t length = 0
Private Member Functions
void copy (const SctpCookie &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:100 by opp_msgtool.
class SctpCookie extends cNamedObject
{
    simtime_t creationTime;
    uint32_t localTag;
    uint32_t peerTag;
    uint8_t localTieTag[];
    uint8_t peerTieTag[];
    uint32_t length;
}
Constructor & Destructor Documentation
SctpCookie() [1/2]
inet::sctp::SctpCookie::SctpCookie (const char * name = nullptr)
SctpCookie() [2/2]
inet::sctp::SctpCookie::SctpCookie (const SctpCookie & other)
~SctpCookie()
virtual inet::sctp::SctpCookie::~SctpCookie () virtual
Member Function Documentation
appendLocalTieTag()
virtual void inet::sctp::SctpCookie::appendLocalTieTag (uint8_t localTieTag) virtual
appendPeerTieTag()
virtual void inet::sctp::SctpCookie::appendPeerTieTag (uint8_t peerTieTag) virtual
copy()
void inet::sctp::SctpCookie::copy (const SctpCookie & other) private
dup()
virtual SctpCookie* inet::sctp::SctpCookie::dup () const inline override virtual
 {return new SctpCookie(*this);}
Referenced by inet::sctp::SctpAssociation::retransmitCookieEcho(), and inet::sctp::SctpAssociation::sendCookieEcho().
eraseLocalTieTag()
virtual void inet::sctp::SctpCookie::eraseLocalTieTag (size_t k) virtual
erasePeerTieTag()
virtual void inet::sctp::SctpCookie::erasePeerTieTag (size_t k) virtual
getCreationTime()
virtual ::omnetpp::simtime_t inet::sctp::SctpCookie::getCreationTime () const
Referenced by inet::sctp::SctpAssociation::processCookieEchoArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getLength()
virtual uint32_t inet::sctp::SctpCookie::getLength () const virtual
Referenced by inet::sctp::SctpAssociation::sendCookieEcho(), and inet::sctp::SctpAssociation::sendInitAck().
getLocalTag()
virtual uint32_t inet::sctp::SctpCookie::getLocalTag () const virtual
Referenced by inet::sctp::SctpAssociation::processCookieEchoArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getLocalTieTag()
virtual uint8_t inet::sctp::SctpCookie::getLocalTieTag (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processCookieEchoArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getLocalTieTagArraySize()
virtual size_t inet::sctp::SctpCookie::getLocalTieTagArraySize () const virtual
getPeerTag()
virtual uint32_t inet::sctp::SctpCookie::getPeerTag () const virtual
Referenced by inet::sctp::SctpAssociation::processCookieEchoArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getPeerTieTag()
virtual uint8_t inet::sctp::SctpCookie::getPeerTieTag (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processCookieEchoArrived(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getPeerTieTagArraySize()
virtual size_t inet::sctp::SctpCookie::getPeerTieTagArraySize () const virtual
insertLocalTieTag() [1/2]
virtual void inet::sctp::SctpCookie::insertLocalTieTag (size_t k, uint8_t localTieTag) virtual
insertLocalTieTag() [2/2]
void inet::sctp::SctpCookie::insertLocalTieTag (uint8_t localTieTag) inline
 {appendLocalTieTag(localTieTag);}
insertPeerTieTag() [1/2]
virtual void inet::sctp::SctpCookie::insertPeerTieTag (size_t k, uint8_t peerTieTag) virtual
insertPeerTieTag() [2/2]
void inet::sctp::SctpCookie::insertPeerTieTag (uint8_t peerTieTag) inline
 {appendPeerTieTag(peerTieTag);}
operator=()
SctpCookie& inet::sctp::SctpCookie::operator= (const SctpCookie & other)
operator==()
bool inet::sctp::SctpCookie::operator== (const SctpCookie &) protected delete
parsimPack()
virtual void inet::sctp::SctpCookie::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpCookie::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::sctp::doParsimUnpacking().
setCreationTime()
virtual void inet::sctp::SctpCookie::setCreationTime (::omnetpp::simtime_t creationTime) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setLength()
virtual void inet::sctp::SctpCookie::setLength (uint32_t length) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setLocalTag()
virtual void inet::sctp::SctpCookie::setLocalTag (uint32_t localTag) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setLocalTieTag()
virtual void inet::sctp::SctpCookie::setLocalTieTag (size_t k, uint8_t localTieTag) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setLocalTieTagArraySize()
virtual void inet::sctp::SctpCookie::setLocalTieTagArraySize (size_t size) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setPeerTag()
virtual void inet::sctp::SctpCookie::setPeerTag (uint32_t peerTag) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setPeerTieTag()
virtual void inet::sctp::SctpCookie::setPeerTieTag (size_t k, uint8_t peerTieTag) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
setPeerTieTagArraySize()
virtual void inet::sctp::SctpCookie::setPeerTieTagArraySize (size_t size) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendInitAck().
Member Data Documentation
creationTime
::omnetpp::simtime_t inet::sctp::SctpCookie::creationTime = SIMTIME_ZERO protected
length
uint32_t inet::sctp::SctpCookie::length = 0 protected
localTag
uint32_t inet::sctp::SctpCookie::localTag = 0 protected
localTieTag
uint8_t* inet::sctp::SctpCookie::localTieTag = nullptr protected
localTieTag_arraysize
size_t inet::sctp::SctpCookie::localTieTag_arraysize = 0 protected
peerTag
uint32_t inet::sctp::SctpCookie::peerTag = 0 protected
peerTieTag
uint8_t* inet::sctp::SctpCookie::peerTieTag = nullptr protected
peerTieTag_arraysize
size_t inet::sctp::SctpCookie::peerTieTag_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h