INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_DisassociateRequest Class Reference
inet::ieee80211::Ieee80211Prim_DisassociateRequest Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:201 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_DisassociateRequest ()
Ieee80211Prim_DisassociateRequest (const Ieee80211Prim_DisassociateRequest &other)
virtual ~Ieee80211Prim_DisassociateRequest ()
Ieee80211Prim_DisassociateRequest & operator= (const Ieee80211Prim_DisassociateRequest &other)
virtual Ieee80211Prim_DisassociateRequest * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::MacAddress & getAddress () const
virtual ::inet::MacAddress & getAddressForUpdate ()
virtual void setAddress (const ::inet::MacAddress &address)
virtual Ieee80211ReasonCode getReasonCode () const
virtual void setReasonCode (Ieee80211ReasonCode reasonCode)
Public Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
Ieee80211PrimRequest ()
Ieee80211PrimRequest (const Ieee80211PrimRequest &other)
virtual ~Ieee80211PrimRequest ()
Ieee80211PrimRequest & operator= (const Ieee80211PrimRequest &other)
Protected Member Functions
bool operator== (const Ieee80211Prim_DisassociateRequest &)=delete
Protected Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
bool operator== (const Ieee80211PrimRequest &)=delete
Protected Attributes
::inet::MacAddress address
Ieee80211ReasonCode reasonCode = static_cast<inet::ieee80211::Ieee80211ReasonCode>(-1)
Private Member Functions
void copy (const Ieee80211Prim_DisassociateRequest &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:201 by opp_msgtool.
//
// Losely based on MLME-DISASSOCIATE.request.
//
// NOTE: there is no Disassociate Confirm, because Disassociate Request
// takes place immediately, and nothing can go wrong (there is no reply
// from the AP to wait for)
//
class Ieee80211Prim_DisassociateRequest extends Ieee80211PrimRequest
{
    MacAddress address;
    Ieee80211ReasonCode reasonCode;
}
Constructor & Destructor Documentation
Ieee80211Prim_DisassociateRequest() [1/2]
inet::ieee80211::Ieee80211Prim_DisassociateRequest::Ieee80211Prim_DisassociateRequest ()
Ieee80211Prim_DisassociateRequest() [2/2]
inet::ieee80211::Ieee80211Prim_DisassociateRequest::Ieee80211Prim_DisassociateRequest (const Ieee80211Prim_DisassociateRequest & other)
~Ieee80211Prim_DisassociateRequest()
virtual inet::ieee80211::Ieee80211Prim_DisassociateRequest::~Ieee80211Prim_DisassociateRequest () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211Prim_DisassociateRequest::copy (const Ieee80211Prim_DisassociateRequest & other) private
dup()
virtual Ieee80211Prim_DisassociateRequest* inet::ieee80211::Ieee80211Prim_DisassociateRequest::dup () const inline override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
 {return new Ieee80211Prim_DisassociateRequest(*this);}
getAddress()
virtual const ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_DisassociateRequest::getAddress () const virtual
getAddressForUpdate()
virtual ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_DisassociateRequest::getAddressForUpdate () inline
 { return const_cast<::inet::MacAddress&>(const_cast<Ieee80211Prim_DisassociateRequest*>(this)->getAddress());}
getReasonCode()
virtual Ieee80211ReasonCode inet::ieee80211::Ieee80211Prim_DisassociateRequest::getReasonCode () const virtual
operator=()
Ieee80211Prim_DisassociateRequest& inet::ieee80211::Ieee80211Prim_DisassociateRequest::operator= (const Ieee80211Prim_DisassociateRequest & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_DisassociateRequest::operator== (const Ieee80211Prim_DisassociateRequest &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_DisassociateRequest::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_DisassociateRequest::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Referenced by inet::ieee80211::doParsimUnpacking().
setAddress()
virtual void inet::ieee80211::Ieee80211Prim_DisassociateRequest::setAddress (const ::inet::MacAddress & address) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendDisassociateRequest().
setReasonCode()
virtual void inet::ieee80211::Ieee80211Prim_DisassociateRequest::setReasonCode (Ieee80211ReasonCode reasonCode) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendDisassociateRequest().
Member Data Documentation
address
::inet::MacAddress inet::ieee80211::Ieee80211Prim_DisassociateRequest::address protected
reasonCode
Ieee80211ReasonCode inet::ieee80211::Ieee80211Prim_DisassociateRequest::reasonCode = static_cast<inet::ieee80211::Ieee80211ReasonCode>(-1) protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h