INET Framework for OMNeT++/OMNEST: inet::tcp::TcpOptionMaxSegmentSize Class Reference
inet::tcp::TcpOptionMaxSegmentSize Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:121 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
TcpOptionMaxSegmentSize ()
TcpOptionMaxSegmentSize (const TcpOptionMaxSegmentSize &other)
virtual ~TcpOptionMaxSegmentSize ()
TcpOptionMaxSegmentSize & operator= (const TcpOptionMaxSegmentSize &other)
virtual TcpOptionMaxSegmentSize * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getMaxSegmentSize () const
virtual void setMaxSegmentSize (uint16_t maxSegmentSize)
Public Member Functions inherited from inet::tcp::TcpOption
TcpOption ()
TcpOption (const TcpOption &other)
virtual ~TcpOption ()
TcpOption & operator= (const TcpOption &other)
virtual TcpOptionNumbers getKind () const
virtual void setKind (TcpOptionNumbers kind)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const TcpOptionMaxSegmentSize &)=delete
Protected Member Functions inherited from inet::tcp::TcpOption
bool operator== (const TcpOption &)=delete
Protected Attributes
uint16_t maxSegmentSize = 0
Protected Attributes inherited from inet::tcp::TcpOption
TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1)
unsigned short length = 1
Private Member Functions
void copy (const TcpOptionMaxSegmentSize &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:121 by opp_msgtool.
class TcpOptionMaxSegmentSize extends TcpOption
{
    kind = TCPOPTION_MAXIMUM_SEGMENT_SIZE;
    length = 4;
    uint16_t maxSegmentSize;   // uint16_t
}
Constructor & Destructor Documentation
TcpOptionMaxSegmentSize() [1/2]
inet::tcp::TcpOptionMaxSegmentSize::TcpOptionMaxSegmentSize ()
TcpOptionMaxSegmentSize() [2/2]
inet::tcp::TcpOptionMaxSegmentSize::TcpOptionMaxSegmentSize (const TcpOptionMaxSegmentSize & other)
~TcpOptionMaxSegmentSize()
virtual inet::tcp::TcpOptionMaxSegmentSize::~TcpOptionMaxSegmentSize () virtual
Member Function Documentation
copy()
void inet::tcp::TcpOptionMaxSegmentSize::copy (const TcpOptionMaxSegmentSize & other) private
dup()
virtual TcpOptionMaxSegmentSize* inet::tcp::TcpOptionMaxSegmentSize::dup () const inline override virtual
Reimplemented from inet::tcp::TcpOption.
 {return new TcpOptionMaxSegmentSize(*this);}
getMaxSegmentSize()
virtual uint16_t inet::tcp::TcpOptionMaxSegmentSize::getMaxSegmentSize () const virtual
Referenced by inet::tcp::TcpConnection::processMSSOption().
operator=()
TcpOptionMaxSegmentSize& inet::tcp::TcpOptionMaxSegmentSize::operator= (const TcpOptionMaxSegmentSize & other)
operator==()
bool inet::tcp::TcpOptionMaxSegmentSize::operator== (const TcpOptionMaxSegmentSize &) protected delete
parsimPack()
virtual void inet::tcp::TcpOptionMaxSegmentSize::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::TcpOptionMaxSegmentSize::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimUnpacking().
setMaxSegmentSize()
virtual void inet::tcp::TcpOptionMaxSegmentSize::setMaxSegmentSize (uint16_t maxSegmentSize) virtual
Referenced by inet::tcp::TcpConnection::writeHeaderOptions().
Member Data Documentation
maxSegmentSize
uint16_t inet::tcp::TcpOptionMaxSegmentSize::maxSegmentSize = 0 protected
The documentation for this class was generated from the following file:
TcpHeader_m.h