INET Framework for OMNeT++/OMNEST: inet::SctpSendReq Class Reference
inet::SctpSendReq Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:130 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpSendReq ()
SctpSendReq (const SctpSendReq &other)
virtual ~SctpSendReq ()
SctpSendReq & operator= (const SctpSendReq &other)
virtual SctpSendReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned int getPrMethod () const
virtual void setPrMethod (unsigned int prMethod)
virtual bool getLast () const
virtual void setLast (bool last)
virtual unsigned int getPpid () const
virtual void setPpid (unsigned int ppid)
virtual bool getPrimary () const
virtual void setPrimary (bool primary)
virtual bool getSackNow () const
virtual void setSackNow (bool sackNow)
Public Member Functions inherited from inet::SctpCommandReq
SctpCommandReq ()
SctpCommandReq (const SctpCommandReq &other)
virtual ~SctpCommandReq ()
SctpCommandReq & operator= (const SctpCommandReq &other)
virtual int getSocketId () const
virtual void setSocketId (int socketId)
virtual int getSid () const
virtual void setSid (int sid)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs)
virtual int getSsn () const
virtual void setSsn (int ssn)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered)
virtual double getPrValue () const
virtual void setPrValue (double prValue)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getGate () const
virtual void setGate (int gate)
virtual int getFd () const
virtual void setFd (int fd)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SctpSendReq &)=delete
Protected Member Functions inherited from inet::SctpCommandReq
bool operator== (const SctpCommandReq &)=delete
Protected Attributes
unsigned int prMethod = 0
bool last = false
unsigned int ppid = 0
bool primary = true
bool sackNow = false
Protected Attributes inherited from inet::SctpCommandReq
int socketId = -1
int sid = -1
int numMsgs = 1
int ssn = -1
unsigned short sendUnordered = false
double prValue = 0
L3Address localAddr
L3Address remoteAddr
int localPort = -1
int remotePort = -1
int gate = -1
int fd = -1
Private Member Functions
void copy (const SctpSendReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:130 by opp_msgtool.
class SctpSendReq extends SctpCommandReq
{
    unsigned int prMethod;
    bool last;
    unsigned int ppid = 0;
    bool primary = true;
    bool sackNow = false;
}
Constructor & Destructor Documentation
SctpSendReq() [1/2]
inet::SctpSendReq::SctpSendReq ()
SctpSendReq() [2/2]
inet::SctpSendReq::SctpSendReq (const SctpSendReq & other)
~SctpSendReq()
virtual inet::SctpSendReq::~SctpSendReq () virtual
Member Function Documentation
copy()
void inet::SctpSendReq::copy (const SctpSendReq & other) private
dup()
virtual SctpSendReq* inet::SctpSendReq::dup () const inline override virtual
Reimplemented from inet::SctpCommandReq.
 {return new SctpSendReq(*this);}
getLast()
virtual bool inet::SctpSendReq::getLast () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
getPpid()
virtual unsigned int inet::SctpSendReq::getPpid () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
getPrimary()
virtual bool inet::SctpSendReq::getPrimary () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
getPrMethod()
virtual unsigned int inet::SctpSendReq::getPrMethod () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
getSackNow()
virtual bool inet::SctpSendReq::getSackNow () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
operator=()
SctpSendReq& inet::SctpSendReq::operator= (const SctpSendReq & other)
operator==()
bool inet::SctpSendReq::operator== (const SctpSendReq &) protected delete
parsimPack()
virtual void inet::SctpSendReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpSendReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimUnpacking().
setLast()
virtual void inet::SctpSendReq::setLast (bool last) virtual
Referenced by inet::SctpNatPeer::addressAddedArrived(), inet::SctpServer::generateAndSend(), inet::SctpPeer::generateAndSend(), inet::SctpNatPeer::generateAndSend(), inet::SctpNatServer::sendInfo(), inet::SctpNatPeer::sendRequest(), inet::SctpClient::sendRequest(), inet::SctpPeer::sendRequest(), inet::SctpClient::socketDataArrived(), inet::SctpPeer::socketDataArrived(), inet::SctpNatPeer::socketDataArrived(), and inet::SctpNatPeer::socketEstablished().
setPpid()
virtual void inet::SctpSendReq::setPpid (unsigned int ppid) virtual
setPrimary()
virtual void inet::SctpSendReq::setPrimary (bool primary) virtual
setPrMethod()
virtual void inet::SctpSendReq::setPrMethod (unsigned int prMethod) virtual
setSackNow()
virtual void inet::SctpSendReq::setSackNow (bool sackNow) virtual
Member Data Documentation
last
bool inet::SctpSendReq::last = false protected
ppid
unsigned int inet::SctpSendReq::ppid = 0 protected
primary
bool inet::SctpSendReq::primary = true protected
prMethod
unsigned int inet::SctpSendReq::prMethod = 0 protected
sackNow
bool inet::SctpSendReq::sackNow = false protected
The documentation for this class was generated from the following file:
SctpCommand_m.h