INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211LlcEpd Class Reference
inet::ieee80211::Ieee80211LlcEpd Class Reference
#include <Ieee80211LlcEpd.h>
Public Member Functions
const Protocol * getProtocol () const override
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void encapsulate (Packet *frame)
virtual void decapsulate (Packet *frame)
Member Function Documentation
decapsulate()
void inet::ieee80211::Ieee80211LlcEpd::decapsulate (Packet * frame) protected virtual
 {
     const auto& epdHeader = frame->popAtFront<Ieee802EpdHeader>();
     auto payloadProtocol = ProtocolGroup::ethertype.findProtocol(epdHeader->getEtherType());
     frame->addTagIfAbsent<DispatchProtocolReq>()->setProtocol(payloadProtocol);
     frame->addTagIfAbsent<PacketProtocolTag>()->setProtocol(payloadProtocol);
 }
Referenced by handleMessage().
encapsulate()
void inet::ieee80211::Ieee80211LlcEpd::encapsulate (Packet * frame) protected virtual
 {
     const Protocol *protocol = frame->getTag<PacketProtocolTag>()->getProtocol();
     int ethType = ProtocolGroup::ethertype.findProtocolNumber(protocol);
     if (ethType == -1)
         throw cRuntimeError("EtherType not found for protocol %s", protocol ? protocol->getName() : "(nullptr)");
     const auto& llcHeader = makeShared<Ieee802EpdHeader>();
     llcHeader->setEtherType(ethType);
     frame->insertAtFront(llcHeader);
     frame->addTagIfAbsent<PacketProtocolTag>()->setProtocol(&Protocol::ieee802epd);
     frame->addTagIfAbsent<LlcProtocolTag>()->setProtocol(&Protocol::ieee802epd);
 }
Referenced by handleMessage().
getProtocol()
const Protocol * inet::ieee80211::Ieee80211LlcEpd::getProtocol () const override virtual
Implements inet::ieee80211::IIeee80211Llc.
 {
     return &Protocol::ieee802epd;
 }
Referenced by encapsulate().
handleMessage()
void inet::ieee80211::Ieee80211LlcEpd::handleMessage (cMessage * message) override protected virtual
 {
     if (message->arrivedOn("upperLayerIn")) {
         auto packet = check_and_cast<Packet *>(message);
         encapsulate(packet);
         send(packet, "lowerLayerOut");
     }
     else if (message->arrivedOn("lowerLayerIn")) {
         auto packet = check_and_cast<Packet *>(message);
         decapsulate(packet);
         if (packet->getTag<PacketProtocolTag>()->getProtocol() != nullptr)
             send(packet, "upperLayerOut");
         else {
             EV_WARN << "Unknown protocol, dropping packet\n";
             PacketDropDetails details;
             details.setReason(NO_PROTOCOL_FOUND);
             emit(packetDroppedSignal, packet, &details);
             delete packet;
         }
     }
     else
         throw cRuntimeError("Unknown message");
 }
initialize()
void inet::ieee80211::Ieee80211LlcEpd::initialize (int stage) override protected virtual
 {
 }
numInitStages()
virtual int inet::ieee80211::Ieee80211LlcEpd::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
The documentation for this class was generated from the following files:
Ieee80211LlcEpd.h
Ieee80211LlcEpd.cc