INET Framework for OMNeT++/OMNEST: inet::Ieee8021dInterfaceData Class Reference
inet::Ieee8021dInterfaceData Class Reference
Per-interface data needed by the STP and RSTP protocols.
#include <Ieee8021dInterfaceData.h>
Classes
class PortInfo
Public Types
enum PortRole {
ALTERNATE, NOTASSIGNED, DISABLED, DESIGNATED,
BACKUP, ROOT
}
enum PortState { DISCARDING, LEARNING, FORWARDING }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
Ieee8021dInterfaceData ()
virtual std::string str () const override
virtual std::string detailedInfo () const
bool isLearning () const
bool isForwarding () const
simtime_t getAge () const
void setAge (simtime_t age)
const MacAddress & getBridgeAddress () const
void setBridgeAddress (const MacAddress &bridgeAddress)
unsigned int getBridgePriority () const
void setBridgePriority (unsigned int bridgePriority)
simtime_t getFdWhile () const
void setFdWhile (simtime_t fdWhile)
simtime_t getFwdDelay () const
void setFwdDelay (simtime_t fwdDelay)
simtime_t getHelloTime () const
void setHelloTime (simtime_t helloTime)
unsigned int getLinkCost () const
void setLinkCost (unsigned int linkCost)
simtime_t getMaxAge () const
void setMaxAge (simtime_t maxAge)
unsigned int getPortNum () const
void setPortNum (unsigned int portNum)
unsigned int getPortPriority () const
void setPortPriority (unsigned int portPriority)
unsigned int getPriority () const
void setPriority (unsigned int priority)
PortRole getRole () const
void setRole (PortRole role)
const MacAddress & getRootAddress () const
void setRootAddress (const MacAddress &rootAddress)
unsigned int getRootPathCost () const
void setRootPathCost (unsigned int rootPathCost)
unsigned int getRootPriority () const
void setRootPriority (unsigned int rootPriority)
PortState getState () const
void setState (PortState state)
bool isEdge () const
void setEdge (bool edge)
simtime_t getTCWhile () const
void setTCWhile (simtime_t TCWhile)
unsigned int getLostBPDU () const
void setLostBPDU (unsigned int lostBPDU)
const char * getRoleName () const
const char * getStateName () const
simtime_t getNextUpgrade () const
void setNextUpgrade (simtime_t nextUpgrade)
Public Member Functions inherited from inet::InterfaceProtocolData
InterfaceProtocolData (int id)
NetworkInterface * getNetworkInterface () const
Returns the NetworkInterface that contains this data object, or nullptr.
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Member Functions
static const char * getRoleName (PortRole role)
static const char * getStateName (PortState state)
Protected Attributes
PortInfo portData
Protected Attributes inherited from inet::InterfaceProtocolData
NetworkInterface * ownerp = nullptr
int id
Additional Inherited Members
Protected Member Functions inherited from inet::InterfaceProtocolData
virtual void changed (simsignal_t signalID, int fieldId)
Detailed Description
Per-interface data needed by the STP and RSTP protocols.
Member Enumeration Documentation
PortRole
enum inet::Ieee8021dInterfaceData::PortRole
Enumerator
ALTERNATE
NOTASSIGNED
DISABLED
DESIGNATED
BACKUP
ROOT
 { ALTERNATE, NOTASSIGNED, DISABLED, DESIGNATED, BACKUP, ROOT };
PortState
enum inet::Ieee8021dInterfaceData::PortState
Enumerator
DISCARDING
LEARNING
FORWARDING
 { DISCARDING, LEARNING, FORWARDING };
Constructor & Destructor Documentation
Ieee8021dInterfaceData()
inet::Ieee8021dInterfaceData::Ieee8021dInterfaceData ()
     : InterfaceProtocolData(NetworkInterface::F_IEEE8021D_DATA)
 {
 }
Member Function Documentation
detailedInfo()
std::string inet::Ieee8021dInterfaceData::detailedInfo () const virtual
 {
     std::stringstream out;
     out << "role:" << getRoleName() << "\tstate:" << getStateName() << "\n";
     out << "priority:" << getPriority() << "\n";
     out << "linkCost:" << getLinkCost() << "\n";
     return out.str();
 }
getAge()
simtime_t inet::Ieee8021dInterfaceData::getAge () const inline
 { return portData.age; }
Referenced by inet::Stp::checkTimers(), inet::Rstp::printState(), inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
getBridgeAddress()
const MacAddress& inet::Ieee8021dInterfaceData::getBridgeAddress () const inline
 { return portData.bridgeAddress; }
Referenced by inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), inet::Rstp::printState(), and inet::Rstp::processBPDU().
getBridgePriority()
unsigned int inet::Ieee8021dInterfaceData::getBridgePriority () const inline
 { return portData.bridgePriority; }
Referenced by inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), and inet::Rstp::printState().
getFdWhile()
simtime_t inet::Ieee8021dInterfaceData::getFdWhile () const inline
 { return portData.fdWhile; }
Referenced by inet::Stp::checkTimers().
getFwdDelay()
simtime_t inet::Ieee8021dInterfaceData::getFwdDelay () const inline
 { return portData.fwdDelay; }
getHelloTime()
simtime_t inet::Ieee8021dInterfaceData::getHelloTime () const inline
 { return portData.helloTime; }
getLinkCost()
unsigned int inet::Ieee8021dInterfaceData::getLinkCost () const inline
 { return portData.linkCost; }
Referenced by inet::Rstp::contestInterfacedata(), detailedInfo(), inet::operator<<(), and inet::Rstp::processBPDU().
getLostBPDU()
unsigned int inet::Ieee8021dInterfaceData::getLostBPDU () const inline
 { return portData.lostBPDU; }
getMaxAge()
simtime_t inet::Ieee8021dInterfaceData::getMaxAge () const inline
 { return portData.maxAge; }
getNextUpgrade()
simtime_t inet::Ieee8021dInterfaceData::getNextUpgrade () const inline
 { return portData.nextUpgrade; }
Referenced by inet::Rstp::scheduleNextUpgrade().
getPortNum()
unsigned int inet::Ieee8021dInterfaceData::getPortNum () const inline
 { return portData.portNum; }
Referenced by inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), and inet::Rstp::printState().
getPortPriority()
unsigned int inet::Ieee8021dInterfaceData::getPortPriority () const inline
 { return portData.portPriority; }
Referenced by inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), and inet::Rstp::printState().
getPriority()
unsigned int inet::Ieee8021dInterfaceData::getPriority () const inline
 { return portData.priority; }
Referenced by detailedInfo(), and inet::operator<<().
getRole()
PortRole inet::Ieee8021dInterfaceData::getRole () const inline
 { return portData.role; }
Referenced by inet::Stp::checkTimers(), inet::Rstp::getBestAlternate(), inet::StpBase::getRootInterfaceId(), inet::Stp::handleBPDU(), inet::operator<<(), inet::Rstp::scheduleNextUpgrade(), inet::Rstp::sendBPDU(), inet::Rstp::sendBPDUs(), and inet::Rstp::sendTCNtoRoot().
getRoleName() [1/2]
const char* inet::Ieee8021dInterfaceData::getRoleName () const inline
 { return getRoleName(getRole()); }
Referenced by detailedInfo(), getRoleName(), inet::Rstp::printState(), inet::StpBase::refreshDisplay(), and str().
getRoleName() [2/2]
const char * inet::Ieee8021dInterfaceData::getRoleName (PortRole role) static
 {
     switch (role) {
         case ALTERNATE:
             return "ALTERNATE";
         case NOTASSIGNED:
             return "NOTASSIGNED";
         case DISABLED:
             return "DISABLED";
         case DESIGNATED:
             return "DESIGNATED";
         case BACKUP:
             return "BACKUP";
         case ROOT:
             return "ROOT";
         default:
             throw cRuntimeError("Unknown port role %d", role);
     }
 }
getRootAddress()
const MacAddress& inet::Ieee8021dInterfaceData::getRootAddress () const inline
 { return portData.rootAddress; }
Referenced by inet::Stp::checkRootEligibility(), inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), inet::Rstp::printState(), inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
getRootPathCost()
unsigned int inet::Ieee8021dInterfaceData::getRootPathCost () const inline
 { return portData.rootPathCost; }
Referenced by inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), inet::Rstp::printState(), inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
getRootPriority()
unsigned int inet::Ieee8021dInterfaceData::getRootPriority () const inline
 { return portData.rootPriority; }
Referenced by inet::Stp::checkRootEligibility(), inet::Rstp::compareInterfacedata(), inet::Stp::comparePorts(), inet::Rstp::contestInterfacedata(), inet::Rstp::getBestAlternate(), inet::Rstp::printState(), inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
getState()
PortState inet::Ieee8021dInterfaceData::getState () const inline
 { return portData.state; }
Referenced by inet::Rstp::checkTC(), inet::Stp::checkTimers(), inet::operator<<(), inet::StpBase::refreshDisplay(), and inet::Rstp::scheduleNextUpgrade().
getStateName() [1/2]
const char* inet::Ieee8021dInterfaceData::getStateName () const inline
 { return getStateName(getState()); }
Referenced by detailedInfo(), getStateName(), inet::Rstp::printState(), inet::StpBase::refreshDisplay(), and str().
getStateName() [2/2]
const char * inet::Ieee8021dInterfaceData::getStateName (PortState state) static
 {
     switch (state) {
         case DISCARDING:
             return "DISCARDING";
         case LEARNING:
             return "LEARNING";
         case FORWARDING:
             return "FORWARDING";
         default:
             throw cRuntimeError("Unknown port state %d", state);
     }
 }
getTCWhile()
simtime_t inet::Ieee8021dInterfaceData::getTCWhile () const inline
 { return portData.TCWhile; }
Referenced by inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
isEdge()
bool inet::Ieee8021dInterfaceData::isEdge () const inline
 { return portData.edge; }
Referenced by inet::Rstp::printState(), and inet::Rstp::sendBPDUs().
isForwarding()
bool inet::Ieee8021dInterfaceData::isForwarding () const inline
 { return portData.state == FORWARDING; }
Referenced by inet::StpTester::isForwarding(), and inet::operator<<().
isLearning()
bool inet::Ieee8021dInterfaceData::isLearning () const inline
 { return portData.state == LEARNING || portData.state == FORWARDING; }
Referenced by inet::operator<<().
setAge()
void inet::Ieee8021dInterfaceData::setAge (simtime_t age) inline
 { portData.age = age; }
setBridgeAddress()
void inet::Ieee8021dInterfaceData::setBridgeAddress (const MacAddress & bridgeAddress) inline
 { portData.bridgeAddress = bridgeAddress; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setBridgePriority()
void inet::Ieee8021dInterfaceData::setBridgePriority (unsigned int bridgePriority) inline
 { portData.bridgePriority = bridgePriority; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setEdge()
void inet::Ieee8021dInterfaceData::setEdge (bool edge) inline
 { portData.edge = edge; }
setFdWhile()
void inet::Ieee8021dInterfaceData::setFdWhile (simtime_t fdWhile) inline
 { portData.fdWhile = fdWhile; }
Referenced by inet::Stp::checkTimers(), and inet::Stp::isSuperiorBPDU().
setFwdDelay()
void inet::Ieee8021dInterfaceData::setFwdDelay (simtime_t fwdDelay) inline
 { portData.fwdDelay = fwdDelay; }
setHelloTime()
void inet::Ieee8021dInterfaceData::setHelloTime (simtime_t helloTime) inline
 { portData.helloTime = helloTime; }
setLinkCost()
void inet::Ieee8021dInterfaceData::setLinkCost (unsigned int linkCost) inline
 { portData.linkCost = linkCost; }
Referenced by inet::L2NetworkConfigurator::configureInterface().
setLostBPDU()
void inet::Ieee8021dInterfaceData::setLostBPDU (unsigned int lostBPDU) inline
 { portData.lostBPDU = lostBPDU; }
setMaxAge()
void inet::Ieee8021dInterfaceData::setMaxAge (simtime_t maxAge) inline
 { portData.maxAge = maxAge; }
setNextUpgrade()
void inet::Ieee8021dInterfaceData::setNextUpgrade (simtime_t nextUpgrade) inline
 { portData.nextUpgrade = nextUpgrade; }
setPortNum()
void inet::Ieee8021dInterfaceData::setPortNum (unsigned int portNum) inline
 { portData.portNum = portNum; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setPortPriority()
void inet::Ieee8021dInterfaceData::setPortPriority (unsigned int portPriority) inline
 { portData.portPriority = portPriority; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setPriority()
void inet::Ieee8021dInterfaceData::setPriority (unsigned int priority) inline
 { portData.priority = priority; }
setRole()
void inet::Ieee8021dInterfaceData::setRole (PortRole role) inline
 { portData.role = role; }
Referenced by inet::Stp::selectRootPort().
setRootAddress()
void inet::Ieee8021dInterfaceData::setRootAddress (const MacAddress & rootAddress) inline
 { portData.rootAddress = rootAddress; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setRootPathCost()
void inet::Ieee8021dInterfaceData::setRootPathCost (unsigned int rootPathCost) inline
 { portData.rootPathCost = rootPathCost; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setRootPriority()
void inet::Ieee8021dInterfaceData::setRootPriority (unsigned int rootPriority) inline
 { portData.rootPriority = rootPriority; }
Referenced by inet::Stp::isSuperiorBPDU(), and inet::Stp::selectDesignatedPorts().
setState()
void inet::Ieee8021dInterfaceData::setState (PortState state) inline
 { portData.state = state; }
Referenced by inet::Stp::checkTimers().
setTCWhile()
void inet::Ieee8021dInterfaceData::setTCWhile (simtime_t TCWhile) inline
 { portData.TCWhile = TCWhile; }
str()
std::string inet::Ieee8021dInterfaceData::str () const override virtual
Reimplemented from inet::TagBase.
 {
     std::stringstream out;
     out << "role:" << getRoleName() << " state:" << getStateName();
     return out.str();
 }
Member Data Documentation
portData
PortInfo inet::Ieee8021dInterfaceData::portData protected
The documentation for this class was generated from the following files:
Ieee8021dInterfaceData.h
Ieee8021dInterfaceData.cc