INET Framework for OMNeT++/OMNEST: inet::physicallayer::SnirReceiverBase Class Reference
inet::physicallayer::SnirReceiverBase Class Reference
#include <SnirReceiverBase.h>
Public Member Functions
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual double getSNIRThreshold () const
virtual bool computeIsReceptionSuccessful (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns whether the reception of the provided part is actually successful or failed by the receiver.
Public Member Functions inherited from inet::physicallayer::ReceiverBase
ReceiverBase ()
virtual W getMinInterferencePower () const override
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
virtual W getMinReceptionPower () const override
Returns the minimum reception power below which successful reception is definitely not possible.
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const override
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const override
Returns whether the reception of the provided part is possible or not.
virtual bool computeIsReceptionAttempted (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference) const override
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
virtual const IReceptionDecision * computeReceptionDecision (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
virtual const IReceptionResult * computeReceptionResult (const IListening *listening, const IReception *reception, const IInterference *interference, const ISnir *snir, const std::vector< const IReceptionDecision * > *decisions) const override
Returns the complete result of the reception process for the provided reception.
Public Member Functions inherited from inet::physicallayer::IReceiver
virtual const IListening * createListening (const IRadio *radio, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition) const =0
Returns a description of how the receiver is listening on the medium.
virtual const IListeningDecision * computeListeningDecision (const IListening *listening, const IInterference *interference) const =0
Returns the result of the listening process specifying the reception state of the receiver.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Types
enum SnirThresholdMode { SnirThresholdMode::STM_UNDEFINED = -1, SnirThresholdMode::STM_MIN, SnirThresholdMode::STM_MEAN }
Protected Member Functions
virtual void initialize (int stage) override
Protected Member Functions inherited from inet::physicallayer::ReceiverBase
virtual int numInitStages () const override
virtual W computeSignalPower (const IListening *listening, const ISnir *snir, const IInterference *interference) const
virtual Packet * computeReceivedPacket (const ISnir *snir, bool isReceptionSuccessful) const
Protected Attributes
double snirThreshold = NaN
SnirThresholdMode snirThresholdMode = SnirThresholdMode::STM_UNDEFINED
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Enumeration Documentation
SnirThresholdMode
enum inet::physicallayer::SnirReceiverBase::SnirThresholdMode strong protected
Enumerator
STM_UNDEFINED
STM_MIN
STM_MEAN
{
         STM_UNDEFINED = -1,
         STM_MIN,
         STM_MEAN
     };
Member Function Documentation
computeIsReceptionSuccessful()
bool inet::physicallayer::SnirReceiverBase::computeIsReceptionSuccessful (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const override virtual
Returns whether the reception of the provided part is actually successful or failed by the receiver.
For example, it might compute the error rate and draw a random number to make the decision.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::FlatReceiverBase.
 {
     if (snirThresholdMode == SnirThresholdMode::STM_MIN) {
         double minSnir = snir->getMin();
         ASSERT(0.0 <= minSnir);
         return minSnir > snirThreshold;
     }
     else if (snirThresholdMode == SnirThresholdMode::STM_MEAN) {
         double meanSnir = snir->getMean();
         ASSERT(0.0 <= meanSnir);
         return meanSnir > snirThreshold;
     }
     else
         throw cRuntimeError("Unknown SNIR threshold mode: '%d'", snirThresholdMode);
 }
Referenced by inet::physicallayer::FlatReceiverBase::computeIsReceptionSuccessful().
getSNIRThreshold()
virtual double inet::physicallayer::SnirReceiverBase::getSNIRThreshold () const inline virtual
 { return snirThreshold; }
initialize()
void inet::physicallayer::SnirReceiverBase::initialize (int stage) override protected virtual
Reimplemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 {
     ReceiverBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         snirThreshold = math::dB2fraction(par("snirThreshold"));
         const char *snirThresholdModeString = par("snirThresholdMode");
         if (!strcmp("min", snirThresholdModeString))
             snirThresholdMode = SnirThresholdMode::STM_MIN;
         else if (!strcmp("mean", snirThresholdModeString))
             snirThresholdMode = SnirThresholdMode::STM_MEAN;
         else
             throw cRuntimeError("Unknown SNIR threshold mode: '%s'", snirThresholdModeString);
     }
 }
Referenced by inet::physicallayer::NarrowbandReceiverBase::initialize(), inet::physicallayer::ApskLayeredReceiver::initialize(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::initialize().
printToStream()
std::ostream & inet::physicallayer::SnirReceiverBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, inet::physicallayer::Ieee80211ScalarReceiver, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(snirThreshold);
     return stream;
 }
Referenced by inet::physicallayer::NarrowbandReceiverBase::printToStream().
Member Data Documentation
snirThreshold
double inet::physicallayer::SnirReceiverBase::snirThreshold = NaN protected
Referenced by computeIsReceptionSuccessful(), initialize(), and printToStream().
snirThresholdMode
SnirThresholdMode inet::physicallayer::SnirReceiverBase::snirThresholdMode = SnirThresholdMode::STM_UNDEFINED protected
Referenced by computeIsReceptionSuccessful(), and initialize().
The documentation for this class was generated from the following files:
SnirReceiverBase.h
SnirReceiverBase.cc