INET Framework for OMNeT++/OMNEST: inet::ieee80211::FrameSequenceContext Class Reference
inet::ieee80211::FrameSequenceContext Class Reference
#include <FrameSequenceContext.h>
Public Member Functions
FrameSequenceContext (MacAddress address, physicallayer::Ieee80211ModeSet *modeSet, InProgressFrames *inProgressFrames, IRtsProcedure *rtsProcedure, IRtsPolicy *rtsPolicy, NonQoSContext *nonQosContext, QoSContext *qosContext)
virtual ~FrameSequenceContext ()
virtual simtime_t getDuration () const
virtual void addStep (IFrameSequenceStep *step)
virtual int getNumSteps () const
virtual IFrameSequenceStep * getStep (int i) const
virtual IFrameSequenceStep * getLastStep () const
virtual IFrameSequenceStep * getStepBeforeLast () const
virtual InProgressFrames * getInProgressFrames () const
virtual IRtsProcedure * getRtsProcedure () const
virtual IRtsPolicy * getRtsPolicy () const
virtual NonQoSContext * getNonQoSContext () const
virtual QoSContext * getQoSContext () const
virtual simtime_t getAckTimeout (Packet *packet, const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtframe) const
virtual simtime_t getCtsTimeout (Packet *packet, const Ptr< const Ieee80211RtsFrame > &rtsFrame) const
virtual simtime_t getIfs () const
virtual bool isForUs (const Ptr< const Ieee80211MacHeader > &header) const
virtual bool isSentByUs (const Ptr< const Ieee80211MacHeader > &header) const
Protected Attributes
simtime_t startTime = simTime()
MacAddress address = MacAddress::UNSPECIFIED_ADDRESS
physicallayer::Ieee80211ModeSet * modeSet = nullptr
InProgressFrames * inProgressFrames = nullptr
std::vector< IFrameSequenceStep * > steps
IRtsProcedure * rtsProcedure = nullptr
IRtsPolicy * rtsPolicy = nullptr
NonQoSContext * nonQoSContext = nullptr
QoSContext * qosContext = nullptr
Constructor & Destructor Documentation
FrameSequenceContext()
inet::ieee80211::FrameSequenceContext::FrameSequenceContext (MacAddress address, physicallayer::Ieee80211ModeSet * modeSet, InProgressFrames * inProgressFrames, IRtsProcedure * rtsProcedure, IRtsPolicy * rtsPolicy, NonQoSContext * nonQosContext, QoSContext * qosContext)
                                                                                                                                                                                                                                       :
     address(address),
     modeSet(modeSet),
     inProgressFrames(inProgressFrames),
     rtsProcedure(rtsProcedure),
     rtsPolicy(rtsPolicy),
     nonQoSContext(nonQoSContext),
     qosContext(qosContext)
 {
 }
~FrameSequenceContext()
inet::ieee80211::FrameSequenceContext::~FrameSequenceContext () virtual
 {
     for (auto step : steps)
         delete step;
     delete nonQoSContext;
     delete qosContext;
 }
Member Function Documentation
addStep()
virtual void inet::ieee80211::FrameSequenceContext::addStep (IFrameSequenceStep * step) inline virtual
 { steps.push_back(step); }
Referenced by inet::ieee80211::FrameSequenceHandler::startFrameSequenceStep().
getAckTimeout()
simtime_t inet::ieee80211::FrameSequenceContext::getAckTimeout (Packet * packet, const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtframe) const virtual
 {
     return qosContext ? qosContext->ackPolicy->getAckTimeout(packet, dataOrMgmtframe) : nonQoSContext->ackPolicy->getAckTimeout(packet, dataOrMgmtframe);
 }
Referenced by inet::ieee80211::ManagementAckFs::prepareStep(), inet::ieee80211::AckFs::prepareStep(), inet::ieee80211::FragFrameAckFs::prepareStep(), and inet::ieee80211::LastFrameAckFs::prepareStep().
getCtsTimeout()
simtime_t inet::ieee80211::FrameSequenceContext::getCtsTimeout (Packet * packet, const Ptr< const Ieee80211RtsFrame > & rtsFrame) const virtual
 {
     return rtsPolicy->getCtsTimeout(packet, rtsFrame);
 }
Referenced by inet::ieee80211::RtsCtsFs::prepareStep(), and inet::ieee80211::CtsFs::prepareStep().
getDuration()
virtual simtime_t inet::ieee80211::FrameSequenceContext::getDuration () const inline virtual
 { return simTime() - startTime; }
getIfs()
simtime_t inet::ieee80211::FrameSequenceContext::getIfs () const virtual
 {
     return getNumSteps() == 0 ? 0 : modeSet->getSifsTime(); // TODO pifs
 }
Referenced by inet::ieee80211::DataFs::prepareStep(), inet::ieee80211::ManagementAckFs::prepareStep(), inet::ieee80211::ManagementFs::prepareStep(), inet::ieee80211::RtsCtsFs::prepareStep(), inet::ieee80211::RtsFs::prepareStep(), inet::ieee80211::FragFrameAckFs::prepareStep(), inet::ieee80211::LastFrameAckFs::prepareStep(), and inet::ieee80211::BlockAckReqBlockAckFs::prepareStep().
getInProgressFrames()
virtual InProgressFrames* inet::ieee80211::FrameSequenceContext::getInProgressFrames () const inline virtual
 { return inProgressFrames; }
Referenced by inet::ieee80211::FrameSequenceHandler::abortFrameSequence(), inet::ieee80211::FrameSequenceHandler::finishFrameSequence(), inet::ieee80211::DcfFs::hasMoreFragments(), inet::ieee80211::HcfFs::hasMoreTxOps(), inet::ieee80211::HcfFs::hasMoreTxOpsAndMulticast(), inet::ieee80211::DcfFs::isBroadcastManagementOrGroupDataSequenceNeeded(), inet::ieee80211::DcfFs::isFragFrameSequenceNeeded(), inet::ieee80211::TxOpFs::isRtsCtsNeeded(), inet::ieee80211::DcfFs::isRtsCtsNeeded(), inet::ieee80211::DataFs::prepareStep(), inet::ieee80211::ManagementAckFs::prepareStep(), inet::ieee80211::ManagementFs::prepareStep(), inet::ieee80211::RtsCtsFs::prepareStep(), inet::ieee80211::RtsFs::prepareStep(), inet::ieee80211::FragFrameAckFs::prepareStep(), inet::ieee80211::LastFrameAckFs::prepareStep(), inet::ieee80211::BlockAckReqBlockAckFs::prepareStep(), inet::ieee80211::HcfFs::selectDataOrManagementSequence(), inet::ieee80211::HcfFs::selectHcfSequence(), inet::ieee80211::DcfFs::selectMulticastDataOrMgmt(), and inet::ieee80211::TxOpFs::selectTxOpSequence().
getLastStep()
virtual IFrameSequenceStep* inet::ieee80211::FrameSequenceContext::getLastStep () const inline virtual
 { return steps.size() > 0 ? steps.back() : nullptr; }
Referenced by inet::ieee80211::FrameSequenceHandler::abortFrameSequence(), inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep(), inet::ieee80211::FrameSequenceHandler::handleStartRxTimeout(), inet::ieee80211::ManagementAckFs::prepareStep(), inet::ieee80211::AckFs::prepareStep(), inet::ieee80211::RtsCtsFs::prepareStep(), inet::ieee80211::CtsFs::prepareStep(), inet::ieee80211::FragFrameAckFs::prepareStep(), inet::ieee80211::LastFrameAckFs::prepareStep(), inet::ieee80211::BlockAckReqBlockAckFs::prepareStep(), and inet::ieee80211::FrameSequenceHandler::processResponse().
getNonQoSContext()
virtual NonQoSContext* inet::ieee80211::FrameSequenceContext::getNonQoSContext () const inline virtual
 { return nonQoSContext; }
getNumSteps()
virtual int inet::ieee80211::FrameSequenceContext::getNumSteps () const inline virtual
 { return steps.size(); }
Referenced by getIfs().
getQoSContext()
virtual QoSContext* inet::ieee80211::FrameSequenceContext::getQoSContext () const inline virtual
 { return qosContext; }
Referenced by inet::ieee80211::HcfFs::hasMoreTxOps(), inet::ieee80211::BlockAckReqBlockAckFs::prepareStep(), and inet::ieee80211::TxOpFs::selectTxOpSequence().
getRtsPolicy()
virtual IRtsPolicy* inet::ieee80211::FrameSequenceContext::getRtsPolicy () const inline virtual
 { return rtsPolicy; }
Referenced by inet::ieee80211::TxOpFs::isRtsCtsNeeded(), and inet::ieee80211::DcfFs::isRtsCtsNeeded().
getRtsProcedure()
virtual IRtsProcedure* inet::ieee80211::FrameSequenceContext::getRtsProcedure () const inline virtual
 { return rtsProcedure; }
Referenced by inet::ieee80211::RtsCtsFs::prepareStep(), and inet::ieee80211::RtsFs::prepareStep().
getStep()
virtual IFrameSequenceStep* inet::ieee80211::FrameSequenceContext::getStep (int i) const inline virtual
 { return steps[i]; }
Referenced by inet::ieee80211::ManagementAckFs::completeStep(), inet::ieee80211::AckFs::completeStep(), inet::ieee80211::RtsCtsFs::completeStep(), inet::ieee80211::CtsFs::completeStep(), inet::ieee80211::FragFrameAckFs::completeStep(), inet::ieee80211::LastFrameAckFs::completeStep(), and inet::ieee80211::BlockAckReqBlockAckFs::completeStep().
getStepBeforeLast()
virtual IFrameSequenceStep* inet::ieee80211::FrameSequenceContext::getStepBeforeLast () const inline virtual
 { return steps.size() > 1 ? steps[steps.size() - 2] : nullptr; }
Referenced by inet::ieee80211::FrameSequenceHandler::abortFrameSequence(), and inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep().
isForUs()
bool inet::ieee80211::FrameSequenceContext::isForUs (const Ptr< const Ieee80211MacHeader > & header) const virtual
 {
     return header->getReceiverAddress() == address || (header->getReceiverAddress().isMulticast() && !isSentByUs(header));
 }
Referenced by inet::ieee80211::ManagementAckFs::completeStep(), inet::ieee80211::AckFs::completeStep(), inet::ieee80211::RtsCtsFs::completeStep(), inet::ieee80211::CtsFs::completeStep(), inet::ieee80211::FragFrameAckFs::completeStep(), inet::ieee80211::LastFrameAckFs::completeStep(), and inet::ieee80211::BlockAckReqBlockAckFs::completeStep().
isSentByUs()
bool inet::ieee80211::FrameSequenceContext::isSentByUs (const Ptr< const Ieee80211MacHeader > & header) const virtual
 {
     // FIXME
     // Check the roles of the Addr3 field when aggregation is applied
     // Table 8-19Address field contents
     if (auto dataOrMgmtHeader = dynamicPtrCast<const Ieee80211DataOrMgmtHeader>(header))
         return dataOrMgmtHeader->getAddress3() == address;
     else
         return false;
 }
Referenced by isForUs().
Member Data Documentation
address
MacAddress inet::ieee80211::FrameSequenceContext::address = MacAddress::UNSPECIFIED_ADDRESS protected
Referenced by isForUs(), and isSentByUs().
inProgressFrames
InProgressFrames* inet::ieee80211::FrameSequenceContext::inProgressFrames = nullptr protected
modeSet
physicallayer::Ieee80211ModeSet* inet::ieee80211::FrameSequenceContext::modeSet = nullptr protected
Referenced by getIfs().
nonQoSContext
NonQoSContext* inet::ieee80211::FrameSequenceContext::nonQoSContext = nullptr protected
Referenced by getAckTimeout(), and ~FrameSequenceContext().
qosContext
QoSContext* inet::ieee80211::FrameSequenceContext::qosContext = nullptr protected
Referenced by getAckTimeout(), and ~FrameSequenceContext().
rtsPolicy
IRtsPolicy* inet::ieee80211::FrameSequenceContext::rtsPolicy = nullptr protected
Referenced by getCtsTimeout().
rtsProcedure
IRtsProcedure* inet::ieee80211::FrameSequenceContext::rtsProcedure = nullptr protected
startTime
simtime_t inet::ieee80211::FrameSequenceContext::startTime = simTime() protected
steps
std::vector<IFrameSequenceStep *> inet::ieee80211::FrameSequenceContext::steps protected
Referenced by ~FrameSequenceContext().
The documentation for this class was generated from the following files:
FrameSequenceContext.h
FrameSequenceContext.cc