INET Framework for OMNeT++/OMNEST: inet::Ipv6HopByHopOptionsHeader Class Reference
inet::Ipv6HopByHopOptionsHeader Class Reference
Class generated from inet/networklayer/ipv6/Ipv6ExtensionHeaders.msg:42 by opp_msgtool.
#include <Ipv6ExtensionHeaders_m.h>
Public Member Functions
Ipv6HopByHopOptionsHeader ()
Ipv6HopByHopOptionsHeader (const Ipv6HopByHopOptionsHeader &other)
virtual ~Ipv6HopByHopOptionsHeader ()
Ipv6HopByHopOptionsHeader & operator= (const Ipv6HopByHopOptionsHeader &other)
virtual Ipv6HopByHopOptionsHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const TlvOptions & getTlvOptions () const
virtual TlvOptions & getTlvOptionsForUpdate ()
virtual void setTlvOptions (const TlvOptions &tlvOptions)
Public Member Functions inherited from inet::Ipv6ExtensionHeader
Ipv6ExtensionHeader ()
Ipv6ExtensionHeader (const Ipv6ExtensionHeader &other)
virtual ~Ipv6ExtensionHeader ()
Ipv6ExtensionHeader & operator= (const Ipv6ExtensionHeader &other)
virtual uint8_t getExtensionType () const
virtual void setExtensionType (uint8_t extensionType)
virtual B getByteLength () const
virtual void setByteLength (B byteLength)
int getOrder () const
Protected Member Functions
bool operator== (const Ipv6HopByHopOptionsHeader &)=delete
Protected Member Functions inherited from inet::Ipv6ExtensionHeader
bool operator== (const Ipv6ExtensionHeader &)=delete
Protected Attributes
TlvOptions tlvOptions
Protected Attributes inherited from inet::Ipv6ExtensionHeader
uint8_t extensionType = 0
B byteLength = B(0)
Private Member Functions
void copy (const Ipv6HopByHopOptionsHeader &other)
Detailed Description
Class generated from inet/networklayer/ipv6/Ipv6ExtensionHeaders.msg:42 by opp_msgtool.
//
// Hop-by-Hop Options Header.
// RFC 2460 Section 4.3
// Next Header Value: 0
//
class Ipv6HopByHopOptionsHeader extends Ipv6ExtensionHeader
{
    extensionType = IP_PROT_IPv6EXT_HOP;
    // byteLength = utils::roundUp(2 + tlvOptions.getLength(), 8);
    TlvOptions tlvOptions;
}
Constructor & Destructor Documentation
Ipv6HopByHopOptionsHeader() [1/2]
inet::Ipv6HopByHopOptionsHeader::Ipv6HopByHopOptionsHeader ()
Ipv6HopByHopOptionsHeader() [2/2]
inet::Ipv6HopByHopOptionsHeader::Ipv6HopByHopOptionsHeader (const Ipv6HopByHopOptionsHeader & other)
~Ipv6HopByHopOptionsHeader()
virtual inet::Ipv6HopByHopOptionsHeader::~Ipv6HopByHopOptionsHeader () virtual
Member Function Documentation
copy()
void inet::Ipv6HopByHopOptionsHeader::copy (const Ipv6HopByHopOptionsHeader & other) private
dup()
virtual Ipv6HopByHopOptionsHeader* inet::Ipv6HopByHopOptionsHeader::dup () const inline override virtual
Reimplemented from inet::Ipv6ExtensionHeader.
 {return new Ipv6HopByHopOptionsHeader(*this);}
getTlvOptions()
virtual const TlvOptions& inet::Ipv6HopByHopOptionsHeader::getTlvOptions () const virtual
Referenced by inet::Gpsr::findGpsrOptionInNetworkDatagram(), inet::Gpsr::findGpsrOptionInNetworkDatagramForUpdate(), and inet::Gpsr::setGpsrOptionOnNetworkDatagram().
getTlvOptionsForUpdate()
virtual TlvOptions& inet::Ipv6HopByHopOptionsHeader::getTlvOptionsForUpdate () inline virtual
 { return const_cast<TlvOptions&>(const_cast<Ipv6HopByHopOptionsHeader*>(this)->getTlvOptions());}
Referenced by inet::Gpsr::findGpsrOptionInNetworkDatagramForUpdate(), and inet::Gpsr::setGpsrOptionOnNetworkDatagram().
operator=()
Ipv6HopByHopOptionsHeader& inet::Ipv6HopByHopOptionsHeader::operator= (const Ipv6HopByHopOptionsHeader & other)
operator==()
bool inet::Ipv6HopByHopOptionsHeader::operator== (const Ipv6HopByHopOptionsHeader &) protected delete
parsimPack()
virtual void inet::Ipv6HopByHopOptionsHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::Ipv6ExtensionHeader.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6HopByHopOptionsHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::Ipv6ExtensionHeader.
Referenced by inet::doParsimUnpacking().
setTlvOptions()
virtual void inet::Ipv6HopByHopOptionsHeader::setTlvOptions (const TlvOptions & tlvOptions) virtual
Member Data Documentation
tlvOptions
TlvOptions inet::Ipv6HopByHopOptionsHeader::tlvOptions protected
The documentation for this class was generated from the following file:
Ipv6ExtensionHeaders_m.h