INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAbortChunk Class Reference
inet::sctp::SctpAbortChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:186 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpAbortChunk (const char *name=nullptr)
SctpAbortChunk (const SctpAbortChunk &other)
virtual ~SctpAbortChunk ()
SctpAbortChunk & operator= (const SctpAbortChunk &other)
virtual SctpAbortChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getT_Bit () const
virtual void setT_Bit (bool T_Bit)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpAbortChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
bool T_Bit = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpAbortChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:186 by opp_msgtool.
class SctpAbortChunk extends SctpChunk
{
    // Chunk Flags
    bool T_Bit = 0;
}
Constructor & Destructor Documentation
SctpAbortChunk() [1/2]
inet::sctp::SctpAbortChunk::SctpAbortChunk (const char * name = nullptr)
SctpAbortChunk() [2/2]
inet::sctp::SctpAbortChunk::SctpAbortChunk (const SctpAbortChunk & other)
~SctpAbortChunk()
virtual inet::sctp::SctpAbortChunk::~SctpAbortChunk () virtual
Member Function Documentation
copy()
void inet::sctp::SctpAbortChunk::copy (const SctpAbortChunk & other) private
dup()
virtual SctpAbortChunk* inet::sctp::SctpAbortChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpAbortChunk(*this);}
getT_Bit()
virtual bool inet::sctp::SctpAbortChunk::getT_Bit () const virtual
Referenced by inet::sctp::SctpAssociation::sendToIP(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpAbortChunk& inet::sctp::SctpAbortChunk::operator= (const SctpAbortChunk & other)
operator==()
bool inet::sctp::SctpAbortChunk::operator== (const SctpAbortChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpAbortChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpAbortChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setT_Bit()
virtual void inet::sctp::SctpAbortChunk::setT_Bit (bool T_Bit) virtual
Referenced by inet::sctp::SctpAssociation::sendAbort(), and inet::sctp::Sctp::sendAbortFromMain().
Member Data Documentation
T_Bit
bool inet::sctp::SctpAbortChunk::T_Bit = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h