INET Framework for OMNeT++/OMNEST: inet::sctp::SctpStreamResetChunk Class Reference
inet::sctp::SctpStreamResetChunk Class Reference
#include <SctpHeader.h>
Public Member Functions
SctpStreamResetChunk (const char *name=nullptr, int32_t kind=0)
SctpStreamResetChunk (const SctpStreamResetChunk &other)
SctpStreamResetChunk & operator= (const SctpStreamResetChunk &other)
~SctpStreamResetChunk ()
virtual SctpStreamResetChunk * dup () const override
virtual void setParametersArraySize (size_t size) override
virtual size_t getParametersArraySize () const override
virtual void setParameters (size_t k, SctpParameter *parameters) override
Generated but unused method, should not be called.
virtual void appendParameters (SctpParameter *parameters) override
virtual void insertParameters (size_t k, SctpParameter *parameters) override
virtual void eraseParameters (size_t k) override
virtual const SctpParameter * getParameters (size_t k) const override
Returns the kth parameter in this SCTP Reset Chunk.
virtual void addParameter (SctpParameter *msg)
Adds a message object to the SCTP packet.
virtual cPacket * removeParameter ()
Removes and returns the first message object in this SCTP packet.
virtual void insertParameters (size_t k, SctpParameter *parameters)=0
void insertParameters (SctpParameter *parameters)
Public Member Functions inherited from inet::sctp::SctpStreamResetChunk_Base
virtual ~SctpStreamResetChunk_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual SctpParameter * getParametersForUpdate (size_t k)
void insertParameters (SctpParameter *parameters)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Attributes
std::vector< SctpParameter * > parameterList
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpStreamResetChunk &other)
void clean ()
Additional Inherited Members
Protected Member Functions inherited from inet::sctp::SctpStreamResetChunk_Base
bool operator== (const SctpStreamResetChunk_Base &)=delete
SctpStreamResetChunk_Base (const char *name=nullptr)
SctpStreamResetChunk_Base (const SctpStreamResetChunk_Base &other)
SctpStreamResetChunk_Base & operator= (const SctpStreamResetChunk_Base &other)
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Constructor & Destructor Documentation
SctpStreamResetChunk() [1/2]
inet::sctp::SctpStreamResetChunk::SctpStreamResetChunk (const char * name = nullptr, int32_t kind = 0) inline
 : SctpStreamResetChunk_Base() {};
SctpStreamResetChunk() [2/2]
inet::sctp::SctpStreamResetChunk::SctpStreamResetChunk (const SctpStreamResetChunk & other) inline
 : SctpStreamResetChunk_Base(other) { operator=(other); };
~SctpStreamResetChunk()
inet::sctp::SctpStreamResetChunk::~SctpStreamResetChunk ()
 {
     clean();
 }
Member Function Documentation
addParameter()
void inet::sctp::SctpStreamResetChunk::addParameter (SctpParameter * msg) virtual
Adds a message object to the SCTP packet.
The packet length will be adjusted
 {
     take(msg);
     if (this->parameterList.size() < 2) {
         this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
         parameterList.push_back(msg);
     }
     else
         throw cRuntimeError("Not more than two parameters allowed!");
 }
Referenced by operator=(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::sendAddInAndOutStreamsRequest(), inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendDoubleStreamResetResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), inet::sctp::SctpAssociation::sendStreamResetRequest(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
appendParameters()
virtual void inet::sctp::SctpStreamResetChunk::appendParameters (SctpParameter * parameters) inline override virtual
Implements inet::sctp::SctpStreamResetChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
clean()
void inet::sctp::SctpStreamResetChunk::clean () private
 {
     while (!parameterList.empty()) {
         cPacket *msg = parameterList.front();
         parameterList.erase(parameterList.begin());
         dropAndDelete(msg);
     }
 }
Referenced by ~SctpStreamResetChunk().
copy()
void inet::sctp::SctpStreamResetChunk::copy (const SctpStreamResetChunk & other) private
 {
     for (const auto& elem : other.parameterList) {
         SctpParameter *param = (elem)->dup();
         take(param);
         parameterList.push_back(param);
     }
 }
dup()
virtual SctpStreamResetChunk* inet::sctp::SctpStreamResetChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpStreamResetChunk_Base.
 { return new SctpStreamResetChunk(*this); }
Referenced by copy(), operator=(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::retransmitReset(), inet::sctp::SctpAssociation::sendAddInAndOutStreamsRequest(), inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), and inet::sctp::SctpAssociation::sendStreamResetRequest().
eraseParameters()
virtual void inet::sctp::SctpStreamResetChunk::eraseParameters (size_t k) inline override virtual
Implements inet::sctp::SctpStreamResetChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
getParameters()
const SctpParameter * inet::sctp::SctpStreamResetChunk::getParameters (size_t k) const override virtual
Returns the kth parameter in this SCTP Reset Chunk.
Implements inet::sctp::SctpStreamResetChunk_Base.
 {
     return parameterList.at(k);
 }
Referenced by inet::sctp::SctpAssociation::processStreamResetArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getParametersArraySize()
size_t inet::sctp::SctpStreamResetChunk::getParametersArraySize () const override virtual
Implements inet::sctp::SctpStreamResetChunk_Base.
 {
     return parameterList.size();
 }
Referenced by inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::retransmitReset(), and inet::sctp::SctpHeaderSerializer::serialize().
insertParameters() [1/3]
void inet::sctp::SctpStreamResetChunk_Base::insertParameters inline
 {appendParameters(parameters);}
insertParameters() [2/3]
virtual void inet::sctp::SctpStreamResetChunk::insertParameters (size_t k, SctpParameter * parameters) inline override virtual
Implements inet::sctp::SctpStreamResetChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
insertParameters() [3/3]
virtual void inet::sctp::SctpStreamResetChunk_Base::insertParameters
operator=()
SctpStreamResetChunk & inet::sctp::SctpStreamResetChunk::operator= (const SctpStreamResetChunk & other)
 {
     SctpStreamResetChunk_Base::operator=(other);
     this->setByteLength(SCTP_STREAM_RESET_CHUNK_LENGTH);
     for (const auto& elem : other.parameterList)
         addParameter((elem)->dup());
     return *this;
 }
removeParameter()
cPacket * inet::sctp::SctpStreamResetChunk::removeParameter () virtual
Removes and returns the first message object in this SCTP packet.
 {
     if (parameterList.empty())
         return nullptr;
     cPacket *msg = parameterList.front();
     parameterList.erase(parameterList.begin());
     drop(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     return msg;
 }
setParameters()
void inet::sctp::SctpStreamResetChunk::setParameters (size_t k, SctpParameter * parameters) override virtual
Generated but unused method, should not be called.
Implements inet::sctp::SctpStreamResetChunk_Base.
 {
     throw cException(this, "setParameters() not supported, use addParameter()");
 }
setParametersArraySize()
void inet::sctp::SctpStreamResetChunk::setParametersArraySize (size_t size) override virtual
Implements inet::sctp::SctpStreamResetChunk_Base.
 {
     throw cException(this, "setParametersArraySize() not supported, use addParameter()");
 }
Member Data Documentation
parameterList
std::vector<SctpParameter *> inet::sctp::SctpStreamResetChunk::parameterList protected
Referenced by addParameter(), clean(), copy(), getParameters(), getParametersArraySize(), operator=(), and removeParameter().
The documentation for this class was generated from the following files:
SctpHeader.h
SctpHeader.cc