INET Framework for OMNeT++/OMNEST: inet::queueing::PcapFilePacketProducer Class Reference
inet::queueing::PcapFilePacketProducer Class Reference
#include <PcapFilePacketProducer.h>
Public Member Functions
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::queueing::ActivePacketSourceBase
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void finish () override
virtual void handleMessage (cMessage *message) override
virtual void schedulePacket ()
Protected Member Functions inherited from inet::queueing::PacketSourceBase
virtual const char * createPacketName (const Ptr< const Chunk > &data) const
virtual Ptr< Chunk > createPacketContent () const
virtual Packet * createPacket ()
virtual const cModule * findContainingApplication () const
virtual const cModule * getContainingApplication () const
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
PcapReader pcapReader
Protected Attributes inherited from inet::queueing::ActivePacketSourceBase
cGate * outputGate = nullptr
IPassivePacketSink * consumer = nullptr
Protected Attributes inherited from inet::queueing::PacketSourceBase
const char * packetNameFormat = nullptr
const char * packetRepresentation = nullptr
cPar * packetLengthParameter = nullptr
cPar * packetDataParameter = nullptr
bool attachCreationTimeTag = false
bool attachIdentityTag = false
bool attachDirectionTag = false
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
finish()
void inet::queueing::PcapFilePacketProducer::finish () override protected virtual
 {
     if (pcapReader.isOpen())
         pcapReader.closePcap();
 }
handleCanPushPacketChanged()
void inet::queueing::PcapFilePacketProducer::handleCanPushPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
This method is called, for example, when a new packet can be inserted into a queue. It allows the source to push a new packet into the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
 {
     Enter_Method("handleCanPushPacketChanged");
     if (gate == outputGate)
         schedulePacket();
 }
handleMessage()
void inet::queueing::PcapFilePacketProducer::handleMessage (cMessage * message) override protected virtual
 {
     if (message->isPacket()) {
         auto packet = check_and_cast<Packet *>(message);
         if (consumer == nullptr || consumer->canPushPacket(packet, outputGate->getPathEndGate())) {
             emit(packetPushedSignal, packet);
             pushOrSendPacket(packet, outputGate, consumer);
             schedulePacket();
         }
     }
     else
         throw cRuntimeError("Unknown message: %s", message->getFullName());
 }
handlePushPacketProcessed()
virtual void inet::queueing::PcapFilePacketProducer::handlePushPacketProcessed (Packet * packet, cGate * gate, bool successful) inline override virtual
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pushed packet is failed to be processed successfully. It allows the source to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSource.
 {}
initialize()
void inet::queueing::PcapFilePacketProducer::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::ActivePacketSourceBase.
 {
     ActivePacketSourceBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL)
         pcapReader.openPcap(par("filename"), par("packetNameFormat"));
     else if (stage == INITSTAGE_QUEUEING)
         schedulePacket();
 }
schedulePacket()
void inet::queueing::PcapFilePacketProducer::schedulePacket () protected virtual
 {
     auto pair = pcapReader.readPacket();
     auto packet = pair.second;
     emit(packetCreatedSignal, packet);
     if (packet != nullptr) {
         EV << "Scheduling packet from PCAP file" << EV_FIELD(packet) << EV_ENDL;
         scheduleAt(pair.first, packet);
     }
     else
         EV << "End of PCAP file reached" << EV_ENDL;
 }
Referenced by handleCanPushPacketChanged(), handleMessage(), and initialize().
Member Data Documentation
pcapReader
PcapReader inet::queueing::PcapFilePacketProducer::pcapReader protected
Referenced by finish(), initialize(), and schedulePacket().
The documentation for this class was generated from the following files:
PcapFilePacketProducer.h
PcapFilePacketProducer.cc