INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAlgorithm Class Reference
inet::sctp::SctpAlgorithm Class Reference abstract
Abstract base class for SCTP algorithms which encapsulate all behaviour during data transfer state: flavour of congestion control, fast retransmit/recovery, selective acknowledgement etc.
#include <SctpAlgorithm.h>
Public Member Functions
SctpAlgorithm ()
Ctor.
virtual ~SctpAlgorithm ()
Virtual dtor.
void setAssociation (SctpAssociation *_assoc)
virtual void initialize ()
virtual SctpStateVariables * createStateVariables ()=0
virtual void established (bool active)=0
virtual void connectionClosed ()=0
virtual void processTimer (cMessage *timer, SctpEventCode &event)=0
virtual void sendCommandInvoked (SctpPathVariables *path)=0
virtual void receivedDataAck (uint32_t firstSeqAcked)=0
virtual void receivedDuplicateAck ()=0
virtual void receivedAckForDataNotYetSent (uint32_t seq)=0
virtual void sackSent ()=0
virtual void dataSent (uint32_t fromseq)=0
Protected Attributes
SctpAssociation * assoc
SctpQueue * transmissionQ
SctpQueue * retransmissionQ
Detailed Description
Abstract base class for SCTP algorithms which encapsulate all behaviour during data transfer state: flavour of congestion control, fast retransmit/recovery, selective acknowledgement etc.
Subclasses may implement various sets and flavours of the above algorithms.
Constructor & Destructor Documentation
SctpAlgorithm()
inet::sctp::SctpAlgorithm::SctpAlgorithm () inline
Ctor.
 { assoc = nullptr; transmissionQ = nullptr; retransmissionQ = nullptr; }
~SctpAlgorithm()
virtual inet::sctp::SctpAlgorithm::~SctpAlgorithm () inline virtual
Virtual dtor.
 {}
Member Function Documentation
connectionClosed()
virtual void inet::sctp::SctpAlgorithm::connectionClosed () pure virtual
Implemented in inet::sctp::SctpAlg.
createStateVariables()
virtual SctpStateVariables* inet::sctp::SctpAlgorithm::createStateVariables () pure virtual
Implemented in inet::sctp::SctpAlg.
Referenced by inet::sctp::SctpAssociation::cloneAssociation(), and inet::sctp::SctpAssociation::initAssociation().
dataSent()
virtual void inet::sctp::SctpAlgorithm::dataSent (uint32_t fromseq) pure virtual
Implemented in inet::sctp::SctpAlg.
established()
virtual void inet::sctp::SctpAlgorithm::established (bool active) pure virtual
Implemented in inet::sctp::SctpAlg.
initialize()
virtual void inet::sctp::SctpAlgorithm::initialize () inline virtual
 {}
Referenced by inet::sctp::SctpAssociation::cloneAssociation(), and inet::sctp::SctpAssociation::initAssociation().
processTimer()
virtual void inet::sctp::SctpAlgorithm::processTimer (cMessage * timer, SctpEventCode & event) pure virtual
Implemented in inet::sctp::SctpAlg.
Referenced by inet::sctp::SctpAssociation::processTimer().
receivedAckForDataNotYetSent()
virtual void inet::sctp::SctpAlgorithm::receivedAckForDataNotYetSent (uint32_t seq) pure virtual
Implemented in inet::sctp::SctpAlg.
receivedDataAck()
virtual void inet::sctp::SctpAlgorithm::receivedDataAck (uint32_t firstSeqAcked) pure virtual
Implemented in inet::sctp::SctpAlg.
receivedDuplicateAck()
virtual void inet::sctp::SctpAlgorithm::receivedDuplicateAck () pure virtual
Implemented in inet::sctp::SctpAlg.
sackSent()
virtual void inet::sctp::SctpAlgorithm::sackSent () pure virtual
Implemented in inet::sctp::SctpAlg.
Referenced by inet::sctp::SctpAssociation::sendOnPath().
sendCommandInvoked()
virtual void inet::sctp::SctpAlgorithm::sendCommandInvoked (SctpPathVariables * path) pure virtual
Implemented in inet::sctp::SctpAlg.
Referenced by inet::sctp::SctpAssociation::process_SEND().
setAssociation()
void inet::sctp::SctpAlgorithm::setAssociation (SctpAssociation * _assoc) inline
     {
         assoc = _assoc;
         transmissionQ = assoc->getTransmissionQueue();
         retransmissionQ = assoc->getRetransmissionQueue();
     }
Referenced by inet::sctp::SctpAssociation::cloneAssociation(), and inet::sctp::SctpAssociation::initAssociation().
Member Data Documentation
assoc
SctpAssociation* inet::sctp::SctpAlgorithm::assoc protected
Referenced by inet::sctp::SctpAlg::sendCommandInvoked().
retransmissionQ
SctpQueue* inet::sctp::SctpAlgorithm::retransmissionQ protected
transmissionQ
SctpQueue* inet::sctp::SctpAlgorithm::transmissionQ protected
The documentation for this class was generated from the following file:
SctpAlgorithm.h