INET Framework for OMNeT++/OMNEST: inet::PacketPrinter Class Reference
inet::PacketPrinter Class Reference
#include <PacketPrinter.h>
Classes
class Context
class DirectiveResolver
Public Member Functions
virtual int getScoreFor (cMessage *msg) const override
virtual std::set< std::string > getSupportedTags () const override
virtual std::set< std::string > getDefaultEnabledTags () const override
virtual std::vector< std::string > getColumnNames (const Options *options) const override
virtual void printMessage (std::ostream &stream, cMessage *message) const
virtual void printMessage (std::ostream &stream, cMessage *message, const Options *options) const override
virtual void printPacket (std::ostream &stream, Packet *packet, const char *format=nullptr) const
virtual void printPacket (std::ostream &stream, Packet *packet, const Options *options, const char *format=nullptr) const
virtual std::string printPacketToString (Packet *packet, const char *format=nullptr) const
virtual std::string printPacketToString (Packet *packet, const Options *options, const char *format=nullptr) const
Protected Member Functions
virtual bool isEnabledOption (const Options *options, const char *name) const
virtual bool isEnabledInfo (const Options *options, const Protocol *protocol) const
virtual const ProtocolPrinter & getProtocolPrinter (const Protocol *protocol) const
virtual void printContext (std::ostream &stream, const Options *options, Context &context) const
virtual void printPacket (Packet *packet, const Options *options, Context &context) const
virtual void printPacketInsideOut (const Ptr< const PacketDissector::ProtocolDataUnit > &protocolDataUnit, const Options *options, Context &context) const
virtual void printPacketLeftToRight (const Ptr< const PacketDissector::ProtocolDataUnit > &protocolDataUnit, const Options *options, Context &context) const
virtual void printSourceColumn (const std::string source, const Protocol *protocol, const Options *options, Context &context) const
virtual void printDestinationColumn (const std::string destination, const Protocol *protocol, const Options *options, Context &context) const
virtual void printProtocolColumn (const Protocol *protocol, const Options *options, Context &context) const
virtual void printLengthColumn (const Ptr< const PacketDissector::ProtocolDataUnit > &protocolDataUnit, const Options *options, Context &context) const
Protected Attributes
int numPacket = 0
Member Function Documentation
getColumnNames()
std::vector< std::string > inet::PacketPrinter::getColumnNames (const Options * options) const override virtual
 {
     std::vector<std::string> columnNames;
     if (isEnabledOption(options, "Show 'Source' column"))
         columnNames.push_back("Source");
     if (isEnabledOption(options, "Show 'Destination' column"))
         columnNames.push_back("Destination");
     if (isEnabledOption(options, "Show 'Protocol' column"))
         columnNames.push_back("Protocol");
     if (isEnabledOption(options, "Show 'Type' column"))
         columnNames.push_back("Type");
     if (isEnabledOption(options, "Show 'Length' column"))
         columnNames.push_back("Length");
     if (isEnabledOption(options, "Show 'Info' column"))
         columnNames.push_back("Info");
     return columnNames;
 }
getDefaultEnabledTags()
std::set< std::string > inet::PacketPrinter::getDefaultEnabledTags () const override virtual
 {
     return { "Print inside out",
              "Show 'Source' column", "Show 'Destination' column", "Show 'Protocol' column", "Show 'Type' column", "Show 'Length' column", "Show 'Info' column",
              "Show auto source fields", "Show auto destination fields", "Show auto info" };
 }
Referenced by printMessage(), and printPacket().
getProtocolPrinter()
const ProtocolPrinter & inet::PacketPrinter::getProtocolPrinter (const Protocol * protocol) const protected virtual
 {
     auto protocolPrinter = ProtocolPrinterRegistry::globalRegistry.findProtocolPrinter(protocol);
     if (protocolPrinter == nullptr)
         protocolPrinter = ProtocolPrinterRegistry::globalRegistry.findProtocolPrinter(nullptr);
     return *protocolPrinter;
 }
Referenced by printPacketInsideOut(), and printPacketLeftToRight().
getScoreFor()
int inet::PacketPrinter::getScoreFor (cMessage * msg) const override virtual
 {
     return msg->isPacket() ? 100 : 0;
 }
getSupportedTags()
std::set< std::string > inet::PacketPrinter::getSupportedTags () const override virtual
 {
     return { "Print inside out", "Print left to right",
              "Show 'Source' column", "Show 'Destination' column", "Show 'Protocol' column", "Show 'Type' column", "Show 'Length' column", "Show 'Info' column",
              "Show all PDU source fields", "Show all PDU destination fields", "Show all PDU protocols", "Show all PDU lengths",
              "Show physical layer info", "Show link layer info", "Show network layer info", "Show transport layer info", "Show all info", "Show innermost info",
              "Show auto source fields", "Show auto destination fields", "Show auto info" };
 }
isEnabledInfo()
bool inet::PacketPrinter::isEnabledInfo (const Options * options, const Protocol * protocol) const protected virtual
 {
     if (isEnabledOption(options, "Show all info"))
         return true;
     if (protocol) {
         switch (protocol->getLayer()) {
             case Protocol::PhysicalLayer: return isEnabledOption(options, "Show physical layer info");
             case Protocol::LinkLayer: return isEnabledOption(options, "Show link layer info");
             case Protocol::NetworkLayer: return isEnabledOption(options, "Show network layer info");
             case Protocol::TransportLayer: return isEnabledOption(options, "Show transport layer info");
             default: break;
         }
     }
     return false;
 }
Referenced by printPacketInsideOut(), and printPacketLeftToRight().
isEnabledOption()
bool inet::PacketPrinter::isEnabledOption (const Options * options, const char * name) const protected virtual
 {
     return contains(options->enabledTags, name);
 }
Referenced by getColumnNames(), isEnabledInfo(), printContext(), printDestinationColumn(), printLengthColumn(), printPacket(), printPacketInsideOut(), printProtocolColumn(), and printSourceColumn().
printContext()
void inet::PacketPrinter::printContext (std::ostream & stream, const Options * options, Context & context) const protected virtual
 {
     if (!context.isCorrect)
         stream << "\x1b[103m";
     stream << "\x1b[30m";
     if (isEnabledOption(options, "Show 'Source' column"))
         stream << context.sourceColumn.str() << "\t";
     if (isEnabledOption(options, "Show 'Destination' column"))
         stream << context.destinationColumn.str() << "\t";
     if (isEnabledOption(options, "Show 'Protocol' column"))
         stream << "\x1b[34m" << context.protocolColumn.str() << "\x1b[30m\t";
     if (isEnabledOption(options, "Show 'Type' column"))
         stream << "\x1b[34m" << context.typeColumn.str() << "\x1b[30m\t";
     if (isEnabledOption(options, "Show 'Length' column"))
         stream << context.lengthColumn.str() << "\t";
     if (isEnabledOption(options, "Show 'Info' column"))
         stream << context.infoColumn.str();
     stream << std::endl;
 }
Referenced by printMessage(), and printPacket().
printDestinationColumn()
void inet::PacketPrinter::printDestinationColumn (const std::string destination, const Protocol * protocol, const Options * options, Context & context) const protected virtual
 {
     if (destination.length() != 0) {
         bool concatenate = isEnabledOption(options, "Show all PDU destination fields") ||
                           (isEnabledOption(options, "Show auto destination fields") && !(protocol && protocol->getLayer() == Protocol::NetworkLayer));
         if (!concatenate)
             context.destinationColumn.str("");
         else if (context.destinationColumn.str().length() != 0)
             context.destinationColumn << ":";
         context.destinationColumn << destination;
     }
 }
Referenced by printPacketInsideOut(), and printPacketLeftToRight().
printLengthColumn()
void inet::PacketPrinter::printLengthColumn (const Ptr< const PacketDissector::ProtocolDataUnit > & protocolDataUnit, const Options * options, Context & context) const protected virtual
 {
     auto lengthColumnLength = context.lengthColumn.str().length();
     if (lengthColumnLength == 0 || isEnabledOption(options, "Show all PDU lengths")) {
         if (lengthColumnLength != 0)
             context.lengthColumn << ", ";
         context.lengthColumn << protocolDataUnit->getChunkLength();
     }
 }
Referenced by printPacketInsideOut(), and printPacketLeftToRight().
printMessage() [1/2]
void inet::PacketPrinter::printMessage (std::ostream & stream, cMessage * message) const virtual
 {
     Options options;
     options.enabledTags = getDefaultEnabledTags();
     printMessage(stream, message, &options);
 }
printMessage() [2/2]
void inet::PacketPrinter::printMessage (std::ostream & stream, cMessage * message, const Options * options) const override virtual
 {
     Context context;
     for (auto cpacket = dynamic_cast<cPacket *>(message); cpacket != nullptr; cpacket = cpacket->getEncapsulatedPacket()) {
         if (false) ;
 #ifdef INET_WITH_PHYSICALLAYERWIRELESSCOMMON
         else if (auto signal = dynamic_cast<physicallayer::Signal *>(cpacket))
             printSignal(signal, options, context);
 #endif // INET_WITH_PHYSICALLAYERWIRELESSCOMMON
         else if (auto packet = dynamic_cast<Packet *>(cpacket))
             printPacket(packet, options, context);
         else
             context.infoColumn << cpacket->str();
     }
     printContext(stream, options, context);
 }
printPacket() [1/3]
void inet::PacketPrinter::printPacket (Packet * packet, const Options * options, Context & context) const protected virtual
 {
     PacketDissector::PduTreeBuilder pduTreeBuilder;
     try {
         PacketDissector packetDissector(ProtocolDissectorRegistry::globalRegistry, pduTreeBuilder);
         packetDissector.dissectPacket(packet);
     }
     catch (cRuntimeError& e) {
         // NOTE: don't propagate errors from printPacket, becaue it can break Qtenv for example
         context.infoColumn << e.what() << ": ";
     }
     const auto& protocolDataUnit = pduTreeBuilder.getTopLevelPdu();
     if (protocolDataUnit != nullptr) {
         if (pduTreeBuilder.isSimplyEncapsulatedPacket() && isEnabledOption(options, "Print inside out"))
             const_cast<PacketPrinter *>(this)->printPacketInsideOut(protocolDataUnit, options, context);
         else
             const_cast<PacketPrinter *>(this)->printPacketLeftToRight(protocolDataUnit, options, context);
     }
 }
Referenced by printMessage(), printPacket(), and printPacketToString().
printPacket() [2/3]
void inet::PacketPrinter::printPacket (std::ostream & stream, Packet * packet, const char * format = nullptr) const virtual
 {
     Options options;
     options.enabledTags = getDefaultEnabledTags();
     printPacket(stream, packet, &options, format);
 }
printPacket() [3/3]
void inet::PacketPrinter::printPacket (std::ostream & stream, Packet * packet, const Options * options, const char * format = nullptr) const virtual
 {
     Context context;
     printPacket(packet, options, context);
     if (format == nullptr)
         printContext(stream, options, context);
     else {
         DirectiveResolver directiveResolver(context, numPacket++);
         StringFormat stringFormat;
         stringFormat.parseFormat(format);
         stream << stringFormat.formatString(&directiveResolver);
     }
 }
printPacketInsideOut()
void inet::PacketPrinter::printPacketInsideOut (const Ptr< const PacketDissector::ProtocolDataUnit > & protocolDataUnit, const Options * options, Context & context) const protected virtual
 {
     auto protocol = protocolDataUnit->getProtocol();
     context.isCorrect &= protocolDataUnit->isCorrect();
     printLengthColumn(protocolDataUnit, options, context);
     for (const auto& chunk : protocolDataUnit->getChunks()) {
         if (auto childLevel = dynamicPtrCast<const PacketDissector::ProtocolDataUnit>(chunk))
             printPacketInsideOut(childLevel, options, context);
         else {
             auto& protocolPrinter = getProtocolPrinter(protocol);
             ProtocolPrinter::Context protocolContext;
             protocolPrinter.print(chunk, protocol, options, protocolContext);
             if (protocolDataUnit->getLevel() > context.infoLevel) {
                 context.infoLevel = protocolDataUnit->getLevel();
                 printSourceColumn(protocolContext.sourceColumn.str(), protocol, options, context);
                 printDestinationColumn(protocolContext.destinationColumn.str(), protocol, options, context);
                 printProtocolColumn(protocol, options, context);
                 // prepend info column
                 bool showAutoInfo = isEnabledOption(options, "Show auto info");
                 bool showInnermostInfo = isEnabledOption(options, "Show innermost info");
                 if (showAutoInfo || showInnermostInfo || isEnabledInfo(options, protocol)) {
                     if (showInnermostInfo && !(showAutoInfo && protocol == nullptr)) {
                         context.typeColumn.str("");
                         context.infoColumn.str("");
                     }
                     if (protocolContext.typeColumn.str().length() != 0) {
                         if (context.typeColumn.str().length() != 0)
                             protocolContext.typeColumn << " | ";
                         context.typeColumn.str(protocolContext.typeColumn.str() + context.typeColumn.str());
                     }
                     if (protocolContext.infoColumn.str().length() != 0) {
                         if (context.infoColumn.str().length() != 0)
                             protocolContext.infoColumn << " | ";
                         context.infoColumn.str(protocolContext.infoColumn.str() + context.infoColumn.str());
                     }
                 }
             }
         }
     }
 }
Referenced by printPacket().
printPacketLeftToRight()
void inet::PacketPrinter::printPacketLeftToRight (const Ptr< const PacketDissector::ProtocolDataUnit > & protocolDataUnit, const Options * options, Context & context) const protected virtual
 {
     auto protocol = protocolDataUnit->getProtocol();
     context.isCorrect &= protocolDataUnit->isCorrect();
     printLengthColumn(protocolDataUnit, options, context);
     for (const auto& chunk : protocolDataUnit->getChunks()) {
         if (auto childLevel = dynamicPtrCast<const PacketDissector::ProtocolDataUnit>(chunk))
             printPacketLeftToRight(childLevel, options, context);
         else {
             auto& protocolPrinter = getProtocolPrinter(protocol);
             ProtocolPrinter::Context protocolContext;
             protocolPrinter.print(chunk, protocol, options, protocolContext);
             if (protocolDataUnit->getLevel() > context.infoLevel) {
                 context.infoLevel = protocolDataUnit->getLevel();
                 printSourceColumn(protocolContext.sourceColumn.str(), protocol, options, context);
                 printDestinationColumn(protocolContext.destinationColumn.str(), protocol, options, context);
                 printProtocolColumn(protocol, options, context);
             }
             // append info column
             if (isEnabledInfo(options, protocol)) {
                 if (context.typeColumn.str().length() != 0)
                     context.typeColumn << " | ";
                 context.typeColumn << protocolContext.typeColumn.str();
                 if (context.infoColumn.str().length() != 0)
                     context.infoColumn << " | ";
                 context.infoColumn << protocolContext.infoColumn.str();
             }
         }
     }
 }
Referenced by printPacket().
printPacketToString() [1/2]
std::string inet::PacketPrinter::printPacketToString (Packet * packet, const char * format = nullptr) const virtual
 {
     std::stringstream stream;
     printPacket(stream, packet, format);
     return stream.str();
 }
Referenced by inet::ExtLowerUdp::processPacketFromLower(), and inet::PcapRecorder::recordPacket().
printPacketToString() [2/2]
std::string inet::PacketPrinter::printPacketToString (Packet * packet, const Options * options, const char * format = nullptr) const virtual
 {
     std::stringstream stream;
     printPacket(stream, packet, options, format);
     return stream.str();
 }
printProtocolColumn()
void inet::PacketPrinter::printProtocolColumn (const Protocol * protocol, const Options * options, Context & context) const protected virtual
 {
     if (protocol != nullptr) {
         if (!isEnabledOption(options, "Show all PDU protocols"))
             context.protocolColumn.str("");
         else if (context.protocolColumn.str().length() != 0)
             context.protocolColumn << ", ";
         context.protocolColumn << protocol->getDescriptiveName();
     }
 }
Referenced by printPacketInsideOut(), and printPacketLeftToRight().
printSourceColumn()
void inet::PacketPrinter::printSourceColumn (const std::string source, const Protocol * protocol, const Options * options, Context & context) const protected virtual
 {
     if (source.length() != 0) {
         bool concatenate = isEnabledOption(options, "Show all PDU source fields") ||
                           (isEnabledOption(options, "Show auto source fields") && !(protocol && protocol->getLayer() == Protocol::NetworkLayer));
         if (!concatenate)
             context.sourceColumn.str("");
         else if (context.sourceColumn.str().length() != 0)
             context.sourceColumn << ":";
         context.sourceColumn << source;
     }
 }
Referenced by printPacketInsideOut(), and printPacketLeftToRight().
Member Data Documentation
numPacket
int inet::PacketPrinter::numPacket = 0 mutable protected
Referenced by printPacket().
The documentation for this class was generated from the following files:
PacketPrinter.h
PacketPrinter.cc