INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3Ipv4RoutingTableEntry Class Reference
inet::ospfv3::Ospfv3Ipv4RoutingTableEntry Class Reference
#include <Ospfv3RoutingTableEntry.h>
Public Types
enum RoutingPathType { INTRAAREA = 0, INTERAREA = 1, TYPE1_EXTERNAL = 2, TYPE2_EXTERNAL = 3 }
typedef unsigned char RoutingDestinationType
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Public Member Functions
Ospfv3Ipv4RoutingTableEntry (const Ospfv3Ipv4RoutingTableEntry &entry, Ipv4Address destPrefix, int prefixLength, SourceType sourceType)
Ospfv3Ipv4RoutingTableEntry (IInterfaceTable *ift, Ipv4Address destPrefix, int prefixLength, SourceType sourceType)
virtual ~Ospfv3Ipv4RoutingTableEntry ()
bool operator== (const Ospfv3Ipv4RoutingTableEntry &entry) const
bool operator!= (const Ospfv3Ipv4RoutingTableEntry &entry) const
void setDestinationType (RoutingDestinationType type)
RoutingDestinationType getDestinationType () const
void setOptionalCapabilities (Ospfv3Options options)
Ospfv3Options getOptionalCapabilities () const
void setArea (AreaID source)
AreaID getArea () const
void setPathType (RoutingPathType type)
RoutingPathType getPathType () const
void setCost (Metric pathCost)
Metric getCost () const
void setType2Cost (Metric pathCost)
Metric getType2Cost () const
void setLinkStateOrigin (const Ospfv3Lsa *lsa)
const Ospfv3Lsa * getLinkStateOrigin () const
void addNextHop (NextHop hop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
Public Member Functions inherited from inet::Ipv4Route
Ipv4Route ()
virtual ~Ipv4Route ()
virtual std::string str () const override
virtual std::string detailedInfo () const
bool operator== (const Ipv4Route &route) const
bool operator!= (const Ipv4Route &route) const
bool equals (const Ipv4Route &route) const
virtual void setRoutingTable (IIpv4RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
IIpv4RoutingTable * getRoutingTable () const
virtual bool isValid () const
test validity of route entry, e.g.
virtual void setDestination (Ipv4Address _dest)
virtual void setNetmask (Ipv4Address _netmask)
virtual void setGateway (Ipv4Address _gateway)
virtual void setInterface (NetworkInterface *_interfacePtr) override
virtual void setSourceType (SourceType _source) override
const char * getSourceTypeAbbreviation () const
virtual void setAdminDist (unsigned int _adminDist) override
virtual void setMetric (int _metric) override
const Ipv4Address & getDestination () const
Destination address prefix to match.
const Ipv4Address & getNetmask () const
Represents length of prefix to match.
const Ipv4Address & getGateway () const
Next hop address.
NetworkInterface * getInterface () const override
Next hop interface.
const char * getInterfaceName () const
Convenience method.
SourceType getSourceType () const override
Source of route.
unsigned int getAdminDist () const
Route source specific preference value.
int getMetric () const override
"Cost" to reach the destination
void setSource (cObject *_source) override
cObject * getSource () const override
Source of route.
cObject * getProtocolData () const override
void setProtocolData (cObject *protocolData) override
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int len) override
virtual void setNextHop (const L3Address &nextHop) override
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
virtual void setSourceType (SourceType type)=0
Static Public Attributes
static const unsigned char NETWORK_DESTINATION = 0
static const unsigned char AREA_BORDER_ROUTER_DESTINATION = 1
static const unsigned char AS_BOUNDARY_ROUTER_DESTINATION = 2
static const unsigned char ROUTER_DESTINATION = 3
Private Attributes
IInterfaceTable * ift = nullptr
RoutingDestinationType destinationType = 0
Ospfv3Options optionalCapabilities
AreaID area
RoutingPathType pathType = (RoutingPathType) - 1
Metric cost = 0
Metric type2Cost = 0
const Ospfv3Lsa * linkStateOrigin = nullptr
std::vector< NextHop > nextHops
Additional Inherited Members
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Protected Member Functions inherited from inet::Ipv4Route
void changed (int fieldCode)
Member Typedef Documentation
RoutingDestinationType
typedef unsigned char inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::RoutingDestinationType
Member Enumeration Documentation
RoutingPathType
enum inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::RoutingPathType
Enumerator
INTRAAREA
INTERAREA
TYPE1_EXTERNAL
TYPE2_EXTERNAL
{
         INTRAAREA      = 0,
         INTERAREA      = 1,
         TYPE1_EXTERNAL = 2,
         TYPE2_EXTERNAL = 3
     };
Constructor & Destructor Documentation
Ospfv3Ipv4RoutingTableEntry() [1/2]
inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry (const Ospfv3Ipv4RoutingTableEntry & entry, Ipv4Address destPrefix, int prefixLength, SourceType sourceType)
                                                                                                                                                                   :
     // Ipv6Route(destPrefix, prefixLength, sourceType),
     destinationType(entry.destinationType),
     optionalCapabilities(entry.optionalCapabilities),
     area(entry.area),
     pathType(entry.pathType),
     cost(entry.cost),
     type2Cost(entry.type2Cost),
     linkStateOrigin(entry.linkStateOrigin),
     nextHops(entry.nextHops)
 {
     this->setDestination(entry.getDestinationAsGeneric());
     this->setPrefixLength(prefixLength);
     this->setInterface(entry.getInterface());
     this->setSourceType(entry.getSourceType());
     this->setMetric(entry.getMetric());
 }
Ospfv3Ipv4RoutingTableEntry() [2/2]
inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry (IInterfaceTable * ift, Ipv4Address destPrefix, int prefixLength, SourceType sourceType)
                                                                                                                                               :
 //     Ipv6Route(destPrefix, prefixLength, sourceType),
     ift(ift),
     area(BACKBONE_AREAID),
     pathType(Ospfv3Ipv4RoutingTableEntry::INTRAAREA)
 {
     this->setDestination(destPrefix);
     this->setPrefixLength(prefixLength);
     this->setSourceType(sourceType);
 }
~Ospfv3Ipv4RoutingTableEntry()
virtual inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::~Ospfv3Ipv4RoutingTableEntry () inline virtual
 {}
Member Function Documentation
addNextHop()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::addNextHop (NextHop hop)
 {
     if (nextHops.size() == 0) {
         NetworkInterface *routingInterface = ift->getInterfaceById(hop.ifIndex);
         setInterface(routingInterface);
         // TODO this used to be commented out, but it seems we need it
         // otherwise gateways will never be filled in and gateway is needed for broadcast networks
 //        setGateway(hop.hopAddress);
     }
     nextHops.push_back(hop);
 }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
clearNextHops()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::clearNextHops () inline
 { nextHops.clear(); }
Referenced by inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getArea()
AreaID inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getArea () const inline
 { return area; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getCost()
Metric inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getCost () const inline
 { return cost; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getDestinationType()
RoutingDestinationType inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getDestinationType () const inline
 { return destinationType; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getLinkStateOrigin()
const Ospfv3Lsa* inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getLinkStateOrigin () const inline
 { return linkStateOrigin; }
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::operator<<().
getNextHop()
NextHop inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getNextHop (unsigned int index) const inline
 { return nextHops[index]; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getNextHopCount()
unsigned int inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getNextHopCount () const inline
 { return nextHops.size(); }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getOptionalCapabilities()
Ospfv3Options inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getOptionalCapabilities () const inline
 { return optionalCapabilities; }
getPathType()
RoutingPathType inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getPathType () const inline
 { return pathType; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getType2Cost()
Metric inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::getType2Cost () const inline
 { return type2Cost; }
Referenced by inet::ospfv3::operator<<().
operator!=()
bool inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::operator!= (const Ospfv3Ipv4RoutingTableEntry & entry) const inline
 { return !((*this) == entry); }
operator==()
bool inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::operator== (const Ospfv3Ipv4RoutingTableEntry & entry) const
 {
     unsigned int hopCount = nextHops.size();
     unsigned int i = 0;
     if (hopCount != entry.nextHops.size()) {
         return false;
     }
     for (i = 0; i < hopCount; i++) {
         if ((nextHops[i] != entry.nextHops[i])) {
             return false;
         }
     }
     return (this->destinationType == entry.destinationType) &&
            (this->getDestinationAsGeneric() == entry.getDestinationAsGeneric()) &&
            (this->getPrefixLength() == entry.getPrefixLength()) &&
            (this->optionalCapabilities == entry.optionalCapabilities) &&
            (this->area == entry.area) &&
            (this->pathType == entry.pathType) &&
            (this->cost == entry.cost) &&
            (this->type2Cost == entry.type2Cost) &&
            (this->linkStateOrigin == entry.linkStateOrigin);
 }
setArea()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setArea (AreaID source) inline
 { area = source; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setCost()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setCost (Metric pathCost)
 {
     cost = pathCost;
     // FIXME this is a hack. But the correct way to do it is to implement a separate IIPv4RoutingTable module for OSPF...
     if (pathType == Ospfv3Ipv4RoutingTableEntry::TYPE2_EXTERNAL) {
         setMetric(cost + type2Cost * 1000);
     }
     else {
         setMetric(cost);
     }
 }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setDestinationType()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setDestinationType (RoutingDestinationType type) inline
 { destinationType = type; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setLinkStateOrigin()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setLinkStateOrigin (const Ospfv3Lsa * lsa) inline
 { linkStateOrigin = lsa; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setOptionalCapabilities()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setOptionalCapabilities (Ospfv3Options options) inline
 { optionalCapabilities = options; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), and inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
setPathType()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setPathType (RoutingPathType type)
 {
     pathType = type;
     // FIXME this is a hack. But the correct way to do it is to implement a separate IIPv4RoutingTable module for OSPF...
     if (pathType == Ospfv3Ipv4RoutingTableEntry::TYPE2_EXTERNAL) {
         setMetric(cost + type2Cost * 1000);
     }
     else {
         setMetric(cost);
     }
 }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setType2Cost()
void inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setType2Cost (Metric pathCost)
 {
     type2Cost = pathCost;
     // FIXME this is a hack. But the correct way to do it is to implement a separate IIPv4RoutingTable module for OSPF...
     if (pathType == Ospfv3Ipv4RoutingTableEntry::TYPE2_EXTERNAL) {
         setMetric(cost + type2Cost * 1000);
     }
     else {
         setMetric(cost);
     }
 }
Member Data Documentation
area
AreaID inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::area private
Referenced by operator==().
AREA_BORDER_ROUTER_DESTINATION
const unsigned char inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION = 1 static
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
AS_BOUNDARY_ROUTER_DESTINATION
const unsigned char inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION = 2 static
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
cost
Metric inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::cost = 0 private
Referenced by operator==(), setCost(), setPathType(), and setType2Cost().
destinationType
RoutingDestinationType inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::destinationType = 0 private
Referenced by operator==().
ift
IInterfaceTable* inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::ift = nullptr private
Referenced by addNextHop().
linkStateOrigin
const Ospfv3Lsa* inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::linkStateOrigin = nullptr private
Referenced by operator==().
NETWORK_DESTINATION
const unsigned char inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::NETWORK_DESTINATION = 0 static
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
nextHops
std::vector<NextHop> inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::nextHops private
Referenced by addNextHop(), and operator==().
optionalCapabilities
Ospfv3Options inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::optionalCapabilities private
Referenced by operator==().
pathType
RoutingPathType inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::pathType = (RoutingPathType) - 1 private
Referenced by operator==(), setCost(), setPathType(), and setType2Cost().
ROUTER_DESTINATION
const unsigned char inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::ROUTER_DESTINATION = 3 static
type2Cost
Metric inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::type2Cost = 0 private
Referenced by operator==(), setCost(), setPathType(), and setType2Cost().
The documentation for this class was generated from the following files:
Ospfv3RoutingTableEntry.h
Ospfv3RoutingTableEntry.cc