INET Framework for OMNeT++/OMNEST: inet::NextHopInterfaceData Class Reference
inet::NextHopInterfaceData Class Reference
Next hop forwarding protocol specific data for an NetworkInterface, stores generic network address.
#include <NextHopInterfaceData.h>
Public Types
enum { F_ADDRESS, F_METRIC }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
NextHopInterfaceData ()
virtual std::string str () const override
virtual std::string detailedInfo () const
Getters
L3Address getAddress () const
int getMetric () const
Setters
virtual void setAddress (L3Address a)
virtual void setMetric (int m)
virtual void joinMulticastGroup (L3Address address)
Public Member Functions inherited from inet::InterfaceProtocolData
InterfaceProtocolData (int id)
NetworkInterface * getNetworkInterface () const
Returns the NetworkInterface that contains this data object, or nullptr.
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
void changed1 (int fieldId)
Protected Member Functions inherited from inet::InterfaceProtocolData
virtual void changed (simsignal_t signalID, int fieldId)
Protected Attributes
L3Address inetAddr
address of interface
int metric
link "cost"; see e.g. MS KB article Q299540 //TODO needed???
Protected Attributes inherited from inet::InterfaceProtocolData
NetworkInterface * ownerp = nullptr
int id
Private Member Functions
NextHopInterfaceData (const NextHopInterfaceData &obj)
NextHopInterfaceData & operator= (const NextHopInterfaceData &obj)
Detailed Description
Next hop forwarding protocol specific data for an NetworkInterface, stores generic network address.
See also
NetworkInterface
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
F_ADDRESS
F_METRIC
 { F_ADDRESS, F_METRIC };
Constructor & Destructor Documentation
NextHopInterfaceData() [1/2]
inet::NextHopInterfaceData::NextHopInterfaceData (const NextHopInterfaceData & obj) private
NextHopInterfaceData() [2/2]
inet::NextHopInterfaceData::NextHopInterfaceData () inline
 : InterfaceProtocolData(NetworkInterface::F_NEXTHOP_DATA) { metric = 0; }
Member Function Documentation
changed1()
void inet::NextHopInterfaceData::changed1 (int fieldId) inline protected
 { changed(interfaceGnpConfigChangedSignal, fieldId); }
detailedInfo()
std::string inet::NextHopInterfaceData::detailedInfo () const virtual
 {
     std::stringstream out;
     out << "generic addr:" << getAddress() << "\n"
         << "Metric: " << getMetric() << "\n";
     return out.str();
 }
getAddress()
L3Address inet::NextHopInterfaceData::getAddress () const inline
 { return inetAddr; }
Referenced by detailedInfo(), inet::NextHopForwarding::routePacket(), and str().
getMetric()
int inet::NextHopInterfaceData::getMetric () const inline
 { return metric; }
Referenced by detailedInfo().
joinMulticastGroup()
virtual void inet::NextHopInterfaceData::joinMulticastGroup (L3Address address) inline virtual
 {}
operator=()
NextHopInterfaceData& inet::NextHopInterfaceData::operator= (const NextHopInterfaceData & obj) private
setAddress()
virtual void inet::NextHopInterfaceData::setAddress (L3Address a) inline virtual
 { inetAddr = a; changed1(F_ADDRESS); }
setMetric()
virtual void inet::NextHopInterfaceData::setMetric (int m) inline virtual
 { metric = m; changed1(F_METRIC); }
Referenced by inet::NextHopRoutingTable::configureInterface().
str()
std::string inet::NextHopInterfaceData::str () const override virtual
Reimplemented from inet::TagBase.
 {
     std::stringstream out;
     out << "generic addr:" << getAddress();
     return out.str();
 }
Member Data Documentation
inetAddr
L3Address inet::NextHopInterfaceData::inetAddr protected
address of interface
metric
int inet::NextHopInterfaceData::metric protected
link "cost"; see e.g. MS KB article Q299540 //TODO needed???
The documentation for this class was generated from the following files:
NextHopInterfaceData.h
NextHopInterfaceData.cc