INET Framework for OMNeT++/OMNEST: inet::BonnMotionFileCache Class Reference
inet::BonnMotionFileCache Class Reference
Singleton object to read and store BonnMotion files.
#include <BonnMotionFileCache.h>
Public Member Functions
virtual const BonnMotionFile * getFile (const char *filename)
Returns the given document.
Static Public Member Functions
static BonnMotionFileCache * getInstance ()
Returns the singleton instance.
static void deleteInstance ()
Deletes the singleton instance.
Protected Types
typedef std::map< std::string, BonnMotionFile > BmFileMap
Protected Member Functions
void parseFile (const char *filename, BonnMotionFile &bmFile)
BonnMotionFileCache ()
virtual ~BonnMotionFileCache ()
Protected Attributes
BmFileMap cache
Static Protected Attributes
static BonnMotionFileCache * inst
Detailed Description
Singleton object to read and store BonnMotion files.
Used within BonnMotionMobility. Needed because otherwise every node would have to open and read the file independently.
Member Typedef Documentation
BmFileMap
typedef std::map<std::string, BonnMotionFile> inet::BonnMotionFileCache::BmFileMap protected
Constructor & Destructor Documentation
BonnMotionFileCache()
inet::BonnMotionFileCache::BonnMotionFileCache () inline protected
 {}
Referenced by getInstance().
~BonnMotionFileCache()
virtual inet::BonnMotionFileCache::~BonnMotionFileCache () inline protected virtual
 {}
Member Function Documentation
deleteInstance()
void inet::BonnMotionFileCache::deleteInstance () static
Deletes the singleton instance.
 {
     if (inst) {
         delete inst;
         inst = nullptr;
     }
 }
Referenced by inet::BonnMotionMobility::~BonnMotionMobility().
getFile()
const BonnMotionFile * inet::BonnMotionFileCache::getFile (const char * filename) virtual
Returns the given document.
 {
     // if found, return it from cache
     auto it = cache.find(std::string(filename));
     if (it != cache.end())
         return &(it->second);
     // load and store in cache
     BonnMotionFile& bmFile = cache[filename];
     parseFile(filename, bmFile);
     return &bmFile;
 }
Referenced by inet::BonnMotionMobility::initialize().
getInstance()
BonnMotionFileCache * inet::BonnMotionFileCache::getInstance () static
Returns the singleton instance.
 {
     if (!inst)
         inst = new BonnMotionFileCache;
     return inst;
 }
Referenced by inet::BonnMotionMobility::initialize().
parseFile()
void inet::BonnMotionFileCache::parseFile (const char * filename, BonnMotionFile & bmFile) protected
 {
     std::ifstream in(filename, std::ios::in);
     if (in.fail())
         throw cRuntimeError("Cannot open file '%s'", filename);
     std::string line;
     while (std::getline(in, line)) {
         bmFile.lines.push_back(BonnMotionFile::Line());
         BonnMotionFile::Line& vec = bmFile.lines.back();
         std::stringstream linestream(line);
         double d;
         while (linestream >> d)
             vec.push_back(d);
     }
     in.close();
 }
Referenced by getFile().
Member Data Documentation
cache
BmFileMap inet::BonnMotionFileCache::cache protected
Referenced by getFile().
inst
BonnMotionFileCache * inet::BonnMotionFileCache::inst static protected
Referenced by deleteInstance(), and getInstance().
The documentation for this class was generated from the following files:
BonnMotionFileCache.h
BonnMotionFileCache.cc