INET Framework for OMNeT++/OMNEST: inet::PimInterfaceTable Class Reference
inet::PimInterfaceTable Class Reference
PimInterfaceTable contains an PimInterface entry for each interface on which PIM is enabled.
#include <PimInterfaceTable.h>
Public Member Functions
virtual ~PimInterfaceTable ()
virtual int getNumInterfaces ()
virtual PimInterface * getInterface (int k)
virtual PimInterface * getInterfaceById (int interfaceId)
Protected Types
typedef std::vector< PimInterface * > PimInterfaceVector
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void configureInterfaces (cXMLElement *config)
virtual PimInterface * createInterface (NetworkInterface *ie, cXMLElement *config)
virtual PimInterfaceVector::iterator findInterface (NetworkInterface *ie)
virtual void addInterface (NetworkInterface *ie)
virtual void removeInterface (NetworkInterface *ie)
Protected Attributes
PimInterfaceVector pimInterfaces
Detailed Description
PimInterfaceTable contains an PimInterface entry for each interface on which PIM is enabled.
When interfaces are added to/deleted from the InterfaceTable, then the corresponding PimInterface entry is added/deleted automatically.
Member Typedef Documentation
PimInterfaceVector
typedef std::vector<PimInterface *> inet::PimInterfaceTable::PimInterfaceVector protected
Constructor & Destructor Documentation
~PimInterfaceTable()
inet::PimInterfaceTable::~PimInterfaceTable () virtual
 {
     for (auto& elem : pimInterfaces)
         delete elem;
 }
Member Function Documentation
addInterface()
void inet::PimInterfaceTable::addInterface (NetworkInterface * ie) protected virtual
 {
     ASSERT(findInterface(ie) == pimInterfaces.end());
     cXMLElement *config = par("pimConfig");
     cXMLElementList interfaceElements = config->getChildrenByTagName("interface");
     InterfaceMatcher matcher(interfaceElements);
     int i = matcher.findMatchingSelector(ie);
     if (i >= 0) {
         PimInterface *pimInterface = createInterface(ie, interfaceElements[i]);
         if (pimInterface)
             pimInterfaces.push_back(pimInterface);
     }
 }
Referenced by receiveSignal().
configureInterfaces()
void inet::PimInterfaceTable::configureInterfaces (cXMLElement * config) protected virtual
 {
     cXMLElementList interfaceElements = config->getChildrenByTagName("interface");
     InterfaceMatcher matcher(interfaceElements);
     IInterfaceTable *ift = getModuleFromPar<IInterfaceTable>(par("interfaceTableModule"), this);
     for (int k = 0; k < ift->getNumInterfaces(); ++k) {
         NetworkInterface *ie = ift->getInterface(k);
         if (ie->isMulticast() && !ie->isLoopback()) {
             int i = matcher.findMatchingSelector(ie);
             if (i >= 0) {
                 PimInterface *pimInterface = createInterface(ie, interfaceElements[i]);
                 if (pimInterface)
                     pimInterfaces.push_back(pimInterface);
             }
         }
     }
 }
Referenced by initialize().
createInterface()
PimInterface * inet::PimInterfaceTable::createInterface (NetworkInterface * ie, cXMLElement * config) protected virtual
 {
     const char *modeAttr = config->getAttribute("mode");
     if (!modeAttr)
         return nullptr;
     PimInterface::PimMode mode;
     if (strcmp(modeAttr, "dense") == 0)
         mode = PimInterface::DenseMode;
     else if (strcmp(modeAttr, "sparse") == 0)
         mode = PimInterface::SparseMode;
     else
         throw cRuntimeError("PimInterfaceTable: invalid 'mode' attribute value in the configuration of interface '%s'", ie->getInterfaceName());
     const char *stateRefreshAttr = config->getAttribute("state-refresh");
     bool stateRefreshFlag = stateRefreshAttr && !strcmp(stateRefreshAttr, "true");
     return new PimInterface(ie, mode, stateRefreshFlag);
 }
Referenced by addInterface(), and configureInterfaces().
findInterface()
PimInterfaceTable::PimInterfaceVector::iterator inet::PimInterfaceTable::findInterface (NetworkInterface * ie) protected virtual
 {
     for (auto it = pimInterfaces.begin(); it != pimInterfaces.end(); ++it)
         if ((*it)->getInterfacePtr() == ie)
             return it;
     return pimInterfaces.end();
 }
Referenced by addInterface(), and removeInterface().
getInterface()
virtual PimInterface* inet::PimInterfaceTable::getInterface (int k) inline virtual
 { return pimInterfaces[k]; }
Referenced by getInterfaceById().
getInterfaceById()
PimInterface * inet::PimInterfaceTable::getInterfaceById (int interfaceId) virtual
 {
     for (int i = 0; i < getNumInterfaces(); i++)
         if (interfaceId == getInterface(i)->getInterfaceId())
             return getInterface(i);
     return nullptr;
 }
getNumInterfaces()
virtual int inet::PimInterfaceTable::getNumInterfaces () inline virtual
 { return pimInterfaces.size(); }
Referenced by getInterfaceById().
handleMessage()
void inet::PimInterfaceTable::handleMessage (cMessage * msg) override protected virtual
 {
     throw cRuntimeError("This module doesn't process messages");
 }
initialize()
void inet::PimInterfaceTable::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         WATCH_VECTOR(pimInterfaces);
     }
     // TODO INITSTAGE
     else if (stage == INITSTAGE_LINK_LAYER) {
         configureInterfaces(par("pimConfig"));
         cModule *host = findContainingNode(this);
         if (!host)
             throw cRuntimeError("PimInterfaceTable: containing node not found.");
         host->subscribe(interfaceCreatedSignal, this);
         host->subscribe(interfaceDeletedSignal, this);
     }
 }
numInitStages()
virtual int inet::PimInterfaceTable::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
receiveSignal()
void inet::PimInterfaceTable::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     printSignalBanner(signalID, obj, details);
     if (signalID == interfaceCreatedSignal) {
         NetworkInterface *ie = check_and_cast<NetworkInterface *>(obj);
         if (ie->isMulticast() && !ie->isLoopback())
             addInterface(ie);
     }
     else if (signalID == interfaceDeletedSignal) {
         NetworkInterface *ie = check_and_cast<NetworkInterface *>(obj);
         if (ie->isMulticast() && !ie->isLoopback())
             removeInterface(ie);
     }
 }
removeInterface()
void inet::PimInterfaceTable::removeInterface (NetworkInterface * ie) protected virtual
 {
     auto it = findInterface(ie);
     if (it != pimInterfaces.end())
         pimInterfaces.erase(it);
 }
Referenced by receiveSignal().
Member Data Documentation
pimInterfaces
PimInterfaceVector inet::PimInterfaceTable::pimInterfaces protected
Referenced by addInterface(), configureInterfaces(), findInterface(), initialize(), removeInterface(), and ~PimInterfaceTable().
The documentation for this class was generated from the following files:
PimInterfaceTable.h
PimInterfaceTable.cc