INET Framework for OMNeT++/OMNEST: inet::math::IFunction< R, D > Class Template Reference
inet::math::IFunction< R, D > Class Template Reference abstract
This interface represents a mathematical function from domain D to range R.
#include <IFunction.h>
Public Member Functions
virtual ~IFunction ()
virtual Interval< R > getRange () const =0
Returns the valid range of the function as an interval.
virtual Interval< R > getRange (const typename D::I &i) const =0
Returns the valid range of the function as an interval for the given domain.
virtual D::I getDomain () const =0
Returns the valid domain of the function as an interval.
virtual R getValue (const typename D::P &p) const =0
Returns the value of the function at the given point.
virtual void partition (const typename D::I &i, const std::function< void(const typename D::I &, const IFunction< R, D > *)> f) const =0
Subdivides the provided domain and calls back f with the subdomains and the corresponding potentially simpler domain limited functions.
virtual bool isFinite () const =0
Returns true if the function value is finite in the whole domain.
virtual bool isFinite (const typename D::I &i) const =0
Returns true if the function value is finite in the given domain.
virtual bool isNonZero () const =0
Returns true if the function value is non-zero in the whole domain.
virtual bool isNonZero (const typename D::I &i) const =0
Returns true if the function value is non-zero in the given domain.
virtual R getMin () const =0
Returns the minimum value for the whole domain.
virtual R getMin (const typename D::I &i) const =0
Returns the minimum value for the given domain.
virtual R getMax () const =0
Returns the maximum value for the whole domain.
virtual R getMax (const typename D::I &i) const =0
Returns the maximum value for the given domain.
virtual R getMean () const =0
Returns the mean value for the whole domain.
virtual R getMean (const typename D::I &i) const =0
Returns the mean value for the given domain.
virtual R getIntegral () const =0
Returns the integral value for the whole domain.
virtual R getIntegral (const typename D::I &i) const =0
Returns the integral value for the given domain.
virtual const Ptr< const IFunction< R, D > > add (const Ptr< const IFunction< R, D >> &o) const =0
Adds the provided function to this function.
virtual const Ptr< const IFunction< R, D > > subtract (const Ptr< const IFunction< R, D >> &o) const =0
Substracts the provided function from this function.
virtual const Ptr< const IFunction< R, D > > multiply (const Ptr< const IFunction< double, D >> &o) const =0
Multiplies the provided function with this function.
virtual const Ptr< const IFunction< double, D > > divide (const Ptr< const IFunction< R, D >> &o) const =0
Divides this function with the provided function.
virtual void print (std::ostream &os, int level=0) const =0
Prints this function in human readable form to the provided stream for the whole domain.
virtual void print (std::ostream &os, const typename D::I &i, int level=0) const =0
Prints this function in a human readable form to the provided stream for the given domain.
virtual void printPartitioning (std::ostream &os, const typename D::I &i, int level=0) const =0
Prints the partitioning of this function in a human readable form to the provided stream for the given domain.
virtual void printPartition (std::ostream &os, const typename D::I &i, int level=0) const =0
Prints a single partition of this function in a human readable form to the provided stream for the given domain.
virtual void printStructure (std::ostream &os, int level=0) const =0
Prints the internal data structure of this function in a human readable form to the provided stream.
Detailed Description
template<typename R, typename D>
class inet::math::IFunction< R, D >
This interface represents a mathematical function from domain D to range R.
R is a scalar type (double, simtime_t, quantity, etc.) D is a Domain<>.
Constructor & Destructor Documentation
~IFunction()
template<typename R , typename D > virtual inet::math::IFunction< R, D >::~IFunction () inline virtual
 {}
Member Function Documentation
add()
template<typename R , typename D > virtual const Ptr<const IFunction<R, D> > inet::math::IFunction< R, D >::add (const Ptr< const IFunction< R, D >> & o) const pure virtual
Adds the provided function to this function.
Implemented in inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, and inet::math::FunctionBase< double, D >.
divide()
template<typename R , typename D > virtual const Ptr<const IFunction<double, D> > inet::math::IFunction< R, D >::divide (const Ptr< const IFunction< R, D >> & o) const pure virtual
Divides this function with the provided function.
Implemented in inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, and inet::math::FunctionBase< double, D >.
getDomain()
template<typename R , typename D > virtual D::I inet::math::IFunction< R, D >::getDomain () const pure virtual
Returns the valid domain of the function as an interval.
Implemented in inet::math::SummedFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, inet::math::FunctionBase< R, Domain< X > >, inet::math::DomainLimitedFunction< R, D >, and inet::math::AddedFunction< R, D >.
getIntegral() [1/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getIntegral () const pure virtual
Returns the integral value for the whole domain.
Implemented in inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
Referenced by inet::math::IntegratedFunction< R, D, DIMS, RI, DI >::getValue().
getIntegral() [2/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getIntegral (const typename D::I & i) const pure virtual
Returns the integral value for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::UnireciprocalFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
getMax() [1/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getMax () const pure virtual
Returns the maximum value for the whole domain.
Implemented in inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
Referenced by inet::math::FunctionBase< R, Domain< X > >::getMax().
getMax() [2/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getMax (const typename D::I & i) const pure virtual
Returns the maximum value for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
getMean() [1/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getMean () const pure virtual
Returns the mean value for the whole domain.
Implemented in inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
Referenced by inet::math::FunctionBase< R, Domain< X > >::getIntegral().
getMean() [2/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getMean (const typename D::I & i) const pure virtual
Returns the mean value for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
getMin() [1/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getMin () const pure virtual
Returns the minimum value for the whole domain.
Implemented in inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
Referenced by inet::math::FunctionBase< R, Domain< X > >::getMin().
getMin() [2/2]
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getMin (const typename D::I & i) const pure virtual
Returns the minimum value for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
getRange() [1/2]
template<typename R , typename D > virtual Interval<R> inet::math::IFunction< R, D >::getRange () const pure virtual
Returns the valid range of the function as an interval.
Implemented in inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, inet::math::FunctionBase< R, Domain< X > >, inet::math::DomainLimitedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
getRange() [2/2]
template<typename R , typename D > virtual Interval<R> inet::math::IFunction< R, D >::getRange (const typename D::I & i) const pure virtual
Returns the valid range of the function as an interval for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, C >.
getValue()
template<typename R , typename D > virtual R inet::math::IFunction< R, D >::getValue (const typename D::P & p) const pure virtual
Returns the value of the function at the given point.
The returned value falls into the range of the function. The provided point must fall into the domain of the function.
Implemented in inet::math::LeftCurryingFunction< R, C, DIMSC, D, DIMSD, E >, inet::math::SummedFunction< R, D >, inet::math::ApproximatedFunction< R, D, DIMENSION, X >, inet::math::DividedFunction< R, D >, inet::math::UnireciprocalFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::MemoizedFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::AddedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
isFinite() [1/2]
template<typename R , typename D > virtual bool inet::math::IFunction< R, D >::isFinite () const pure virtual
Returns true if the function value is finite in the whole domain.
Implemented in inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
Referenced by inet::math::FunctionBase< R, Domain< X > >::isFinite().
isFinite() [2/2]
template<typename R , typename D > virtual bool inet::math::IFunction< R, D >::isFinite (const typename D::I & i) const pure virtual
Returns true if the function value is finite in the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::ApproximatedFunction< R, D, DIMENSION, X >, inet::math::SummedFunction< R, D >, inet::math::DividedFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::AddedFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
isNonZero() [1/2]
template<typename R , typename D > virtual bool inet::math::IFunction< R, D >::isNonZero () const pure virtual
Returns true if the function value is non-zero in the whole domain.
Implemented in inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
Referenced by inet::math::FunctionBase< R, Domain< X > >::isNonZero().
isNonZero() [2/2]
template<typename R , typename D > virtual bool inet::math::IFunction< R, D >::isNonZero (const typename D::I & i) const pure virtual
Returns true if the function value is non-zero in the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
multiply()
template<typename R , typename D > virtual const Ptr<const IFunction<R, D> > inet::math::IFunction< R, D >::multiply (const Ptr< const IFunction< double, D >> & o) const pure virtual
Multiplies the provided function with this function.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, C >.
partition()
template<typename R , typename D > virtual void inet::math::IFunction< R, D >::partition (const typename D::I & i, const std::function< void(const typename D::I &, const IFunction< R, D > *)> f) const pure virtual
Subdivides the provided domain and calls back f with the subdomains and the corresponding potentially simpler domain limited functions.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::LeftCurryingFunction< R, C, DIMSC, D, DIMSD, E >, inet::math::SummedFunction< R, D >, inet::math::UnireciprocalFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::AddedFunction< R, D >, inet::math::ConstantFunction< R, D >, inet::math::DividedFunction< R, D >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, C >.
print() [1/2]
template<typename R , typename D > virtual void inet::math::IFunction< R, D >::print (std::ostream & os, const typename D::I & i, int level = 0) const pure virtual
Prints this function in a human readable form to the provided stream for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, C >.
print() [2/2]
template<typename R , typename D > virtual void inet::math::IFunction< R, D >::print (std::ostream & os, int level = 0) const pure virtual
Prints this function in human readable form to the provided stream for the whole domain.
Implemented in inet::physicallayer::AntennaGainFunction, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, Domain< X > >.
printPartition()
template<typename R , typename D > virtual void inet::math::IFunction< R, D >::printPartition (std::ostream & os, const typename D::I & i, int level = 0) const pure virtual
Prints a single partition of this function in a human readable form to the provided stream for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, inet::math::UnilinearFunction< R, D >, inet::math::ConstantFunction< R, D >, and inet::math::FunctionBase< R, C >.
Referenced by inet::math::FunctionBase< R, Domain< X > >::printPartitioning().
printPartitioning()
template<typename R , typename D > virtual void inet::math::IFunction< R, D >::printPartitioning (std::ostream & os, const typename D::I & i, int level = 0) const pure virtual
Prints the partitioning of this function in a human readable form to the provided stream for the given domain.
Implemented in inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< double, D >, and inet::math::FunctionBase< R, C >.
printStructure()
template<typename R , typename D > virtual void inet::math::IFunction< R, D >::printStructure (std::ostream & os, int level = 0) const pure virtual
Prints the internal data structure of this function in a human readable form to the provided stream.
Implemented in inet::math::IntegratedFunction< R, D, DIMS, RI, DI >, inet::math::Interpolated1DFunction< R, X >, inet::math::Extruded2DFunction< R, X, Y >, inet::math::ApproximatedFunction< R, D, DIMENSION, X >, inet::physicallayer::AntennaGainFunction, inet::math::Boxcar2DFunction< R, X, Y >, inet::math::SummedFunction< R, D >, inet::physicallayer::ObstacleLossFunction, inet::math::Boxcar1DFunction< R, X >, inet::physicallayer::PathLossFunction, inet::physicallayer::PropagatedTransmissionPowerFunction, inet::math::DividedFunction< R, D >, inet::physicallayer::BackgroundNoisePowerFunction, inet::math::Combined2DFunction< R, X, Y >, inet::math::MultipliedFunction< R, D >, inet::physicallayer::SpaceDependentAttenuationFunction, inet::math::SubtractedFunction< R, D >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, D >, inet::math::FunctionBase< R, Domain< X > >, inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction, inet::math::UnilinearFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::AddedFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, inet::physicallayer::FrequencyDependentAttenuationFunction, and inet::math::ConstantFunction< R, D >.
subtract()
template<typename R , typename D > virtual const Ptr<const IFunction<R, D> > inet::math::IFunction< R, D >::subtract (const Ptr< const IFunction< R, D >> & o) const pure virtual
Substracts the provided function from this function.
Implemented in inet::math::FunctionBase< WpHz, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< RI, Domain< X > >, inet::math::FunctionBase< RI, DI >, inet::math::FunctionBase< R, Domain< X, Y > >, inet::math::FunctionBase< R, Domain< X > >, inet::math::FunctionBase< R, D >, inet::math::FunctionBase< R, C >, inet::math::FunctionBase< double, Domain< simsec, Hz > >, inet::math::FunctionBase< double, Domain< mps, m, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, simsec, Hz > >, inet::math::FunctionBase< double, Domain< m, m, m, m, m, m, Hz > >, and inet::math::FunctionBase< double, D >.
The documentation for this class was generated from the following file:
IFunction.h