INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpNeighbor< IPAddress > Class Template Reference
inet::eigrp::EigrpNeighbor< IPAddress > Class Template Reference
Class represents one entry in EIGRP Neighbor Table.
#include <EigrpNeighbor.h>
Public Member Functions
virtual ~EigrpNeighbor ()
EigrpNeighbor (int ifaceId, const char *ifaceNname, IPAddress ipAddress)
void setStateUp (bool stateUp)
void setHoldInt (int holdInt)
void setHoldTimer (EigrpTimer *holdt)
Sets timer for a neighbor.
void setNeighborId (int neighborId)
void setSeqNumber (int seqNumber)
void setAck (uint32_t waitForAck)
void setRoutesForDeletion (bool routesForDeletion)
void setStubConf (const EigrpStub &stubConf)
void setStubEnable (bool stubEnabled)
IPAddress getIPAddress () const
int getIfaceId () const
bool isStateUp () const
int getHoldInt () const
EigrpTimer * getHoldTimer () const
int getNeighborId () const
int getSeqNumber () const
uint32_t getAck () const
bool getRoutesForDeletion () const
EigrpStub getStubConf () const
bool isStubEnabled () const
const char * getIfaceName () const
Static Public Attributes
static const int UNSPEC_ID = 0
Protected Attributes
int ifaceId
ID of interface that is connected to the neighbor.
const char * ifaceName
int neighborId
ID of neighbor.
IPAddress ipAddress
IP address of neighbor.
bool isUp
State of neighbor.
int holdInt
Neighbor's Hold interval used to set Hold timer.
uint32_t seqNumber
Sequence number received from neighbor.
bool routesForDeletion
After receiving Ack from the neighbor will be removed unreachable routes from TT.
uint32_t waitForAck
Waiting for ack number from neighbor (for reliable transport)
EigrpTimer * holdt
Pointer to Hold timer.
bool stubEnabled
Neighbor is a stub.
EigrpStub stubConf
Neighbor's stub configuration.
Detailed Description
template<typename IPAddress>
class inet::eigrp::EigrpNeighbor< IPAddress >
Class represents one entry in EIGRP Neighbor Table.
Constructor & Destructor Documentation
~EigrpNeighbor()
template<typename IPAddress > virtual inet::eigrp::EigrpNeighbor< IPAddress >::~EigrpNeighbor () inline virtual
 { delete holdt; }
EigrpNeighbor()
template<typename IPAddress > inet::eigrp::EigrpNeighbor< IPAddress >::EigrpNeighbor (int ifaceId, const char * ifaceNname, IPAddress ipAddress) inline
                                                                             :
         ifaceId(ifaceId), ifaceName(ifaceNname), neighborId(UNSPEC_ID), ipAddress(ipAddress), isUp(false), holdt(nullptr)
     { seqNumber = 0; holdInt = 0; routesForDeletion = false; waitForAck = 0; stubEnabled = false; }
Member Function Documentation
getAck()
template<typename IPAddress > uint32_t inet::eigrp::EigrpNeighbor< IPAddress >::getAck () const inline
 { return waitForAck; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader().
getHoldInt()
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::getHoldInt () const inline
 { return this->holdInt; }
Referenced by inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), inet::eigrp::EigrpIpv6Pdm::processHelloPacket(), inet::eigrp::EigrpIpv4Pdm::processMsgFromNetwork(), and inet::eigrp::EigrpIpv6Pdm::processMsgFromNetwork().
getHoldTimer()
template<typename IPAddress > EigrpTimer* inet::eigrp::EigrpNeighbor< IPAddress >::getHoldTimer () const inline
 { return this->holdt; }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHoldTimer(), inet::eigrp::EigrpIpv6Pdm::cancelHoldTimer(), inet::eigrp::EigrpIpv4Pdm::processMsgFromNetwork(), and inet::eigrp::EigrpIpv6Pdm::processMsgFromNetwork().
getIfaceId()
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::getIfaceId () const inline
 { return this->ifaceId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::operator<<(), inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader(), inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv6Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv4Pdm::processTimer(), inet::eigrp::EigrpIpv6Pdm::processTimer(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
getIfaceName()
template<typename IPAddress > const char* inet::eigrp::EigrpNeighbor< IPAddress >::getIfaceName () const inline
 { return ifaceName; }
Referenced by inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
getIPAddress()
template<typename IPAddress > IPAddress inet::eigrp::EigrpNeighbor< IPAddress >::getIPAddress () const inline
 { return this->ipAddress; }
Referenced by inet::eigrp::EigrpNeighborTable< Ipv4Address >::findNeighbor(), inet::eigrp::EigrpIpv4Pdm::getDestIpAddress(), inet::eigrp::EigrpIpv6Pdm::getDestIpAddress(), inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::processTimer(), and inet::eigrp::EigrpIpv6Pdm::processTimer().
getNeighborId()
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::getNeighborId () const inline
 { return neighborId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::processAckPacket(), inet::eigrp::EigrpIpv6Pdm::processAckPacket(), inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), inet::eigrp::EigrpIpv6Pdm::processInterRoute(), inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv6Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv4Pdm::processQueryPacket(), inet::eigrp::EigrpIpv6Pdm::processQueryPacket(), inet::eigrp::EigrpIpv4Pdm::processReplyPacket(), inet::eigrp::EigrpIpv6Pdm::processReplyPacket(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), inet::eigrp::EigrpIpv6Pdm::processUpdatePacket(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
getRoutesForDeletion()
template<typename IPAddress > bool inet::eigrp::EigrpNeighbor< IPAddress >::getRoutesForDeletion () const inline
 { return this->routesForDeletion; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processAckPacket(), and inet::eigrp::EigrpIpv6Pdm::processAckPacket().
getSeqNumber()
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::getSeqNumber () const inline
 { return seqNumber; }
Referenced by inet::eigrp::operator<<(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
getStubConf()
template<typename IPAddress > EigrpStub inet::eigrp::EigrpNeighbor< IPAddress >::getStubConf () const inline
 { return this->stubConf; }
isStateUp()
template<typename IPAddress > bool inet::eigrp::EigrpNeighbor< IPAddress >::isStateUp () const inline
 { return this->isUp; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processAckPacket(), inet::eigrp::EigrpIpv6Pdm::processAckPacket(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), and inet::eigrp::EigrpIpv6Pdm::processUpdatePacket().
isStubEnabled()
template<typename IPAddress > bool inet::eigrp::EigrpNeighbor< IPAddress >::isStubEnabled () const inline
 { return this->stubEnabled; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
setAck()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setAck (uint32_t waitForAck) inline
 { this->waitForAck = waitForAck; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader(), and inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
setHoldInt()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setHoldInt (int holdInt) inline
 { this->holdInt = holdInt; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createNeighbor(), inet::eigrp::EigrpIpv6Pdm::createNeighbor(), inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), and inet::eigrp::EigrpIpv6Pdm::processHelloPacket().
setHoldTimer()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setHoldTimer (EigrpTimer * holdt) inline
Sets timer for a neighbor.
 { ASSERT(this->holdt == nullptr); this->holdt = holdt; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createNeighbor(), and inet::eigrp::EigrpIpv6Pdm::createNeighbor().
setNeighborId()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setNeighborId (int neighborId) inline
 { this->neighborId = neighborId; }
Referenced by inet::eigrp::EigrpNeighborTable< Ipv4Address >::addNeighbor().
setRoutesForDeletion()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setRoutesForDeletion (bool routesForDeletion) inline
 { this->routesForDeletion = routesForDeletion; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processAckPacket(), inet::eigrp::EigrpIpv6Pdm::processAckPacket(), inet::eigrp::EigrpIpv4Pdm::setDelayedRemove(), and inet::eigrp::EigrpIpv6Pdm::setDelayedRemove().
setSeqNumber()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setSeqNumber (int seqNumber) inline
 { this->seqNumber = seqNumber; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader().
setStateUp()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setStateUp (bool stateUp) inline
 { this->isUp = stateUp; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processAckPacket(), inet::eigrp::EigrpIpv6Pdm::processAckPacket(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), and inet::eigrp::EigrpIpv6Pdm::processUpdatePacket().
setStubConf()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setStubConf (const EigrpStub & stubConf) inline
 { this->stubConf = stubConf; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), and inet::eigrp::EigrpIpv6Pdm::processNewNeighbor().
setStubEnable()
template<typename IPAddress > void inet::eigrp::EigrpNeighbor< IPAddress >::setStubEnable (bool stubEnabled) inline
 { this->stubEnabled = stubEnabled; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), and inet::eigrp::EigrpIpv6Pdm::processNewNeighbor().
Member Data Documentation
holdInt
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::holdInt protected
Neighbor's Hold interval used to set Hold timer.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::EigrpNeighbor(), inet::eigrp::EigrpNeighbor< IPAddress >::getHoldInt(), and inet::eigrp::EigrpNeighbor< IPAddress >::setHoldInt().
holdt
template<typename IPAddress > EigrpTimer* inet::eigrp::EigrpNeighbor< IPAddress >::holdt protected
Pointer to Hold timer.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::getHoldTimer(), inet::eigrp::EigrpNeighbor< IPAddress >::setHoldTimer(), and inet::eigrp::EigrpNeighbor< IPAddress >::~EigrpNeighbor().
ifaceId
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::ifaceId protected
ID of interface that is connected to the neighbor.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::getIfaceId().
ifaceName
template<typename IPAddress > const char* inet::eigrp::EigrpNeighbor< IPAddress >::ifaceName protected
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::getIfaceName().
ipAddress
template<typename IPAddress > IPAddress inet::eigrp::EigrpNeighbor< IPAddress >::ipAddress protected
IP address of neighbor.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::getIPAddress().
isUp
template<typename IPAddress > bool inet::eigrp::EigrpNeighbor< IPAddress >::isUp protected
State of neighbor.
Possible states are pending or up.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::isStateUp().
neighborId
template<typename IPAddress > int inet::eigrp::EigrpNeighbor< IPAddress >::neighborId protected
ID of neighbor.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::getNeighborId(), and inet::eigrp::EigrpNeighbor< IPAddress >::setNeighborId().
routesForDeletion
template<typename IPAddress > bool inet::eigrp::EigrpNeighbor< IPAddress >::routesForDeletion protected
After receiving Ack from the neighbor will be removed unreachable routes from TT.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::EigrpNeighbor(), inet::eigrp::EigrpNeighbor< IPAddress >::getRoutesForDeletion(), and inet::eigrp::EigrpNeighbor< IPAddress >::setRoutesForDeletion().
seqNumber
template<typename IPAddress > uint32_t inet::eigrp::EigrpNeighbor< IPAddress >::seqNumber protected
Sequence number received from neighbor.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::EigrpNeighbor(), inet::eigrp::EigrpNeighbor< IPAddress >::getSeqNumber(), and inet::eigrp::EigrpNeighbor< IPAddress >::setSeqNumber().
stubConf
template<typename IPAddress > EigrpStub inet::eigrp::EigrpNeighbor< IPAddress >::stubConf protected
Neighbor's stub configuration.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::getStubConf(), and inet::eigrp::EigrpNeighbor< IPAddress >::setStubConf().
stubEnabled
template<typename IPAddress > bool inet::eigrp::EigrpNeighbor< IPAddress >::stubEnabled protected
Neighbor is a stub.
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::EigrpNeighbor(), inet::eigrp::EigrpNeighbor< IPAddress >::isStubEnabled(), and inet::eigrp::EigrpNeighbor< IPAddress >::setStubEnable().
UNSPEC_ID
template<typename IPAddress > const int inet::eigrp::EigrpNeighbor< IPAddress >::UNSPEC_ID = 0 static
waitForAck
template<typename IPAddress > uint32_t inet::eigrp::EigrpNeighbor< IPAddress >::waitForAck protected
Waiting for ack number from neighbor (for reliable transport)
Referenced by inet::eigrp::EigrpNeighbor< IPAddress >::EigrpNeighbor(), inet::eigrp::EigrpNeighbor< IPAddress >::getAck(), and inet::eigrp::EigrpNeighbor< IPAddress >::setAck().
The documentation for this class was generated from the following file:
EigrpNeighbor.h