INET Framework for OMNeT++/OMNEST: inet::Ipv4Address Class Reference
inet::Ipv4Address Class Reference
Ipv4 address.
#include <Ipv4Address.h>
Public Types
enum AddressCategory {
UNSPECIFIED, THIS_NETWORK, LOOPBACK, MULTICAST,
BROADCAST, IETF, TEST_NET, IPv6_TO_IPv4_RELAY,
BENCHMARK, RESERVED, LINKLOCAL, PRIVATE_NETWORK,
GLOBAL
}
Ipv4 address category.
Static Protected Member Functions
static bool parseIPAddress (const char *text, unsigned char tobytes[])
static void _checkNetmaskLength (int length)
static uint32_t _makeNetmask (int length)
Protected Attributes
uint32_t addr
Predefined addresses
static const Ipv4Address UNSPECIFIED_ADDRESS
0.0.0.0
static const Ipv4Address LOOPBACK_ADDRESS
127.0.0.1
static const Ipv4Address LOOPBACK_NETMASK
255.0.0.0
static const Ipv4Address ALLONES_ADDRESS
255.255.255.255
static const Ipv4Address ALL_HOSTS_MCAST
224.0.0.1 All hosts on a subnet
static const Ipv4Address ALL_ROUTERS_MCAST
224.0.0.2 All routers on a subnet
static const Ipv4Address ALL_DVMRP_ROUTERS_MCAST
224.0.0.4 All DVMRP routers
static const Ipv4Address ALL_OSPF_ROUTERS_MCAST
224.0.0.5 All OSPF routers (DR Others)
static const Ipv4Address ALL_OSPF_DESIGNATED_ROUTERS_MCAST
224.0.0.6 All OSPF Designated Routers
static const Ipv4Address ALL_IGMPV3_ROUTERS_MCAST
224.0.0.22 All IGMPv3 routers
static const Ipv4Address LL_MANET_ROUTERS
224.0.0.109 Manet all designated routers
static const Ipv4Address ALL_RIP_ROUTERS_MCAST
Ipv4Address ()
name Constructors, destructor
Ipv4Address (uint32_t ip)
Ipv4 address as int.
Ipv4Address (int i0, int i1, int i2, int i3)
Ipv4 address bytes: "i0.i1.i2.i3" format.
Ipv4Address (const char *text)
Ipv4 address given as text: "192.66.86.1".
Ipv4Address (const Ipv4Address &obj)
Copy constructor.
~Ipv4Address ()
void set (uint32_t ip)
name Setting the address
void set (int i0, int i1, int i2, int i3)
Ipv4 address bytes: "i0.i1.i2.i3" format.
void set (const char *t)
Ipv4 address given as text: "192.66.86.1".
Ipv4Address & operator= (const Ipv4Address &obj)
Assignment.
bool isUnspecified () const
True if all four address bytes are zero.
bool equals (const Ipv4Address &toCmp) const
Returns true if the two addresses are equal.
Ipv4Address doAnd (const Ipv4Address &ip) const
Returns binary AND of the two addresses.
std::string str (bool printUnspec=true) const
Returns the string representation of the address (e.g.
uint32_t getInt () const
Returns the address as an uint32_t in host byte order (e.g.
int getDByte (int i) const
Returns the corresponding part of the address specified by the index ("[0].[1].[2].[3]")
char getIPClass () const
Returns the network class of the address: char 'A', 'B', 'C', 'D', 'E', or '?' (returned when the address begins with at least five 1 bits.)
AddressCategory getAddressCategory () const
Get the Ipv4 address category.
bool isLimitedBroadcastAddress () const
Returns true if this address is the limited broadcast address, i.e.
bool isMulticast () const
Returns true if this address is in the multicast address range, 224.0.0.0 thru 239.255.255.255, that is, it's a class D address.
bool isUnicast () const
Returns true if this address is unicast address.
bool isLinkLocalMulticast () const
Returns true if this address is in the range 224.0.0.0 to 224.0.0.255.
Ipv4Address getNetwork () const
Returns an address with the network part of the address (the bits of the hosts part are to 0).
Ipv4Address getNetworkMask () const
Returns an address with the network mask corresponding to the address class.
bool isNetwork (const Ipv4Address &toCmp) const
Indicates if the address is from the same network.
bool prefixMatches (const Ipv4Address &to_cmp, int numbits) const
Compares the first numbits bits of the two addresses.
int getNumMatchingPrefixBits (const Ipv4Address &to_cmp) const
Indicates how many bits from the to_cmp address, starting counting from the left, matches the address.
int getNetmaskLength () const
Counts 1 bits in a netmask.
Ipv4Address getPrefix (int prefixLength) const
Get the first prefixLength bits of the address, with the rest set to zero.
bool isValidNetmask () const
Returns true if the address is a valid netmask, i.e.
Ipv4Address makeBroadcastAddress (Ipv4Address netmask) const
Returns the broadcast address for the given netmask.
bool operator== (const Ipv4Address &addr1) const
Returns equals(addr).
bool operator!= (const Ipv4Address &addr1) const
Returns !equals(addr).
bool operator< (const Ipv4Address &addr1) const
Compares two Ipv4 addresses.
bool operator<= (const Ipv4Address &addr1) const
bool operator> (const Ipv4Address &addr1) const
bool operator>= (const Ipv4Address &addr1) const
MacAddress mapToMulticastMacAddress () const
Form a MAC address for a multicast IPv4 address, see RFC 1112, section 6.4.
static bool maskedAddrAreEqual (const Ipv4Address &addr1, const Ipv4Address &addr2, const Ipv4Address &netmask)
Test if the masked addresses (ie the mask is applied to addr1 and addr2) are equal.
static bool isWellFormed (const char *text)
Returns true if the format of the string corresponds to an Ipv4 address with the dotted notation ("192.66.86.1"), and false otherwise.
static Ipv4Address makeNetmask (int length)
Creates and returns a netmask with the given length.
Detailed Description
Ipv4 address.
Member Enumeration Documentation
AddressCategory
enum inet::Ipv4Address::AddressCategory
Ipv4 address category.
RFC 5735 Special Use Ipv4 Addresses January 2010
Summary Table
Address Block Present Use Reference
0.0.0.0/8 "This" Network RFC 1122, Section 3.2.1.3 10.0.0.0/8 Private-Use Networks RFC 1918 127.0.0.0/8 Loopback RFC 1122, Section 3.2.1.3 169.254.0.0/16 Link Local RFC 3927 172.16.0.0/12 Private-Use Networks RFC 1918 192.0.0.0/24 IETF Protocol Assignments RFC 5736 192.0.2.0/24 TEST-NET-1 RFC 5737 192.88.99.0/24 6to4 Relay Anycast RFC 3068 192.168.0.0/16 Private-Use Networks RFC 1918 198.18.0.0/15 Network Interconnect Device Benchmark Testing RFC 2544 198.51.100.0/24 TEST-NET-2 RFC 5737 203.0.113.0/24 TEST-NET-3 RFC 5737 224.0.0.0/4 Multicast RFC 3171 240.0.0.0/4 Reserved for Future Use RFC 1112, Section 4 255.255.255.255/32 Limited Broadcast RFC 919, Section 7; RFC 922, Section 7
Enumerator
UNSPECIFIED
THIS_NETWORK
LOOPBACK
MULTICAST
BROADCAST
IETF
TEST_NET
IPv6_TO_IPv4_RELAY
BENCHMARK
RESERVED
LINKLOCAL
PRIVATE_NETWORK
GLOBAL
{
         UNSPECIFIED, // 0.0.0.0
         THIS_NETWORK, // 0.0.0.0/8
         LOOPBACK, // 127.0.0.0/8
         MULTICAST, // 224.0.0.0/4
         BROADCAST, // 255.255.255.255/32
         IETF, // 192.0.0.0/24
         TEST_NET, // 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24
         IPv6_TO_IPv4_RELAY, // 192.88.99.0/24
         BENCHMARK, // 198.18.0.0/15
         RESERVED, // 240.0.0.0/4
         LINKLOCAL, // 169.254.0.0/16
         PRIVATE_NETWORK, // 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
         GLOBAL
     };
Constructor & Destructor Documentation
Ipv4Address() [1/5]
inet::Ipv4Address::Ipv4Address () inline
name Constructors, destructor
Default constructor, initializes to 0.0.0.0.
 { addr = 0; }
Referenced by getNetwork(), and getNetworkMask().
Ipv4Address() [2/5]
inet::Ipv4Address::Ipv4Address (uint32_t ip) inline explicit
Ipv4 address as int.
 { addr = ip; }
Ipv4Address() [3/5]
inet::Ipv4Address::Ipv4Address (int i0, int i1, int i2, int i3) inline
Ipv4 address bytes: "i0.i1.i2.i3" format.
 { set(i0, i1, i2, i3); }
Ipv4Address() [4/5]
inet::Ipv4Address::Ipv4Address (const char * text) inline explicit
Ipv4 address given as text: "192.66.86.1".
 { set(text); }
Ipv4Address() [5/5]
inet::Ipv4Address::Ipv4Address (const Ipv4Address & obj) inline
Copy constructor.
 { addr = obj.addr; }
~Ipv4Address()
inet::Ipv4Address::~Ipv4Address () inline
 {}
Member Function Documentation
_checkNetmaskLength()
void inet::Ipv4Address::_checkNetmaskLength (int length) static protected
 {
     if (length < 0 || length > 32)
         throw cRuntimeError("Ipv4Address: wrong netmask length %d (not in 0..32)", length);
 }
_makeNetmask()
static uint32_t inet::Ipv4Address::_makeNetmask (int length) inline static protected
 { return length >= 32 ? 0xffffffffu : ~(0xffffffffu >> length); }
Referenced by prefixMatches().
doAnd()
Ipv4Address inet::Ipv4Address::doAnd (const Ipv4Address & ip) const inline
Returns binary AND of the two addresses.
 { return Ipv4Address(addr & ip.addr); }
Referenced by inet::eigrp::EigrpIpv4Pdm::addInterfaceToEigrp(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::bgp::BgpRouter::isReachable(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks(), inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), and inet::bgp::BgpRouter::updateSendProcess().
equals()
bool inet::Ipv4Address::equals (const Ipv4Address & toCmp) const inline
Returns true if the two addresses are equal.
 { return addr == toCmp.addr; }
Referenced by inet::bgp::BgpConfigReader::loadEbgpSessionConfig().
getAddressCategory()
Ipv4Address::AddressCategory inet::Ipv4Address::getAddressCategory () const
Get the Ipv4 address category.
 {
     if (isUnspecified())
         return UNSPECIFIED; // 0.0.0.0
     if ((addr & 0xFF000000u) == 0)
         return THIS_NETWORK; // 0.0.0.0/8
     if ((addr & 0xFF000000u) == 0x7F000000u)
         return LOOPBACK; // 127.0.0.0/8
     if (isMulticast())
         return MULTICAST; // 224.0.0.0/4
     if (addr == 0xFFFFFFFFu)
         return BROADCAST; // 255.255.255.255/32
     uint32_t addr24 = addr & 0xFFFFFF00u;
     if (addr24 == 0xC0000000u)
         return IETF; // 192.0.0.0/24
     if ((addr24 == 0xC0000200u) || (addr24 == 0xC6336400u) || (addr24 == 0xCB007100u))
         return TEST_NET; // 192.0.2.0/24, 198.51.100.0/24, 203.0.113.0/24
     if (addr24 == 0xC0586300u)
         return IPv6_TO_IPv4_RELAY; // 192.88.99.0/24
     if ((addr & 0xFFFE0000u) == 0xC6120000u)
         return BENCHMARK; // 198.18.0.0/15
     if ((addr & 0xF0000000u) == 0xF0000000u)
         return RESERVED; // 240.0.0.0/4
     if ((addr & 0xFFFF0000u) == 0xA9FE0000u)
         return LINKLOCAL; // 169.254.0.0/16
     if (((addr & 0xFF000000u) == 0x0A000000u)
         || ((addr & 0xFFF00000u) == 0xAC100000u)
         || ((addr & 0xFFFF0000u) == 0xC0A80000u))
         return PRIVATE_NETWORK; // 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
     return GLOBAL;
 }
Referenced by inet::sctp::SctpAssociation::getAddressLevel().
getDByte()
int inet::Ipv4Address::getDByte (int i) const inline
Returns the corresponding part of the address specified by the index ("[0].[1].[2].[3]")
 { return (addr >> (3 - i) * 8) & 0xFF; }
Referenced by inet::Ipv4RoutingTable::findBestMatchingMulticastRoute(), inet::Ipv4RoutingTable::findBestMatchingRoute(), inet::Ipv4RoutingTable::findInterfaceByLocalBroadcastAddress(), inet::Ipv4RoutingTable::getGatewayForDestAddr(), inet::Ipv4RoutingTable::getInterfaceByAddress(), inet::Ipv4RoutingTable::getInterfaceForDestAddr(), getIPClass(), getNetwork(), inet::Ipv4RoutingTable::isLocalAddress(), inet::Ipv4RoutingTable::isLocalBroadcastAddress(), and inet::Ipv4RoutingTable::isLocalMulticastAddress().
getInt()
uint32_t inet::Ipv4Address::getInt () const inline
Returns the address as an uint32_t in host byte order (e.g.
"10.0.0.1" is 0x0A000001).
 { return addr; }
Referenced by inet::SctpNatPeer::addressAddedArrived(), inet::ospfv3::Ospfv3Neighbor::addToRetransmissionList(), inet::ospfv2::Neighbor::addToRetransmissionList(), inet::Ipv4FlatNetworkConfigurator::assignAddresses(), inet::ExtLowerUdp::bind(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::eigrp::EigrpIpv4Pdm::checkNeighborshipRules(), inet::ExtLowerUdp::connect(), inet::bgp::BgpRouter::createEbgpSession(), inet::bgp::BgpRouter::createIbgpSession(), inet::Ipv4NetworkConfigurator::createInterfaceInfo(), inet::bgp::BgpRouter::deleteBGPRoutingEntry(), inet::RsvpTe::delSession(), inet::ospfv3::Ospfv3Interface::detailedInfo(), inet::doParsimPacking(), inet::Ipv4NetworkConfigurator::findInterfaceOnLinkByNodeAddress(), inet::DhcpServer::getAvailableLease(), inet::eigrp::EigrpIpv4Pdm::getDestIpAddress(), inet::ospfv3::Ospfv3Instance::getNewInterAreaPrefixLinkStateID(), inet::ospfv3::Ospfv3Area::getNewIntraAreaPrefixLinkStateID(), inet::ospfv3::Ospfv3Area::getNewNetworkLinkStateID(), inet::ospfv3::Ospfv3Area::getNewRouterLinkStateID(), getNumMatchingPrefixBits(), inet::DhcpServer::handleStartOperation(), inet::Ted::initializeTED(), inet::ospfv2::Router::installASExternalLSA(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::Ipv4RoutingTable::internalAddRoute(), inet::ospfv2::Ospfv2Area::isAllZero(), inet::ospfv2::Ospfv2Area::isDefaultRoute(), inet::bgp::BgpRouter::isDefaultRoute(), inet::bgp::BgpRouter::isInRoutingTable(), inet::bgp::BgpRouter::isInTable(), inet::ospfv2::Router::lookup(), makeBroadcastAddress(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::operator&(), inet::ospfv3::operator&(), operator<(), operator<=(), operator>(), operator>=(), inet::ospfv2::operator|(), inet::ospfv3::operator|(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::Ipv4NetworkConfigurator::parseAddressAndSpecifiedBits(), inet::Icmp::possiblyLocalBroadcast(), inet::LinkStateRouting::processLINK_STATE_MESSAGE(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), inet::RsvpClassifier::readItemFromXML(), inet::SctpNatServer::sendInfo(), inet::sctp::SctpAssociation::sendInit(), inet::sctp::SctpHeaderSerializer::serialize(), inet::L3Address::set(), inet::HostAutoConfigurator::setupNetworkLayer(), inet::SctpNatPeer::socketEstablished(), inet::ospfv3::Ospfv3Instance::subtractInterAreaPrefixLinkStateID(), inet::ospfv3::Ospfv3Area::subtractIntraAreaPrefixLinkStateID(), inet::eigrp::EigrpDeviceConfigurator::wildcardToMask(), and inet::MemoryOutputStream::writeIpv4Address().
getIPClass()
char inet::Ipv4Address::getIPClass () const
Returns the network class of the address: char 'A', 'B', 'C', 'D', 'E', or '?' (returned when the address begins with at least five 1 bits.)
 {
     unsigned char buf = getDByte(0);
     if ((buf & 0x80) == 0x00) // 0xxxx
         return 'A';
     else if ((buf & 0xC0) == 0x80) // 10xxx
         return 'B';
     else if ((buf & 0xE0) == 0xC0) // 110xx
         return 'C';
     else if ((buf & 0xF0) == 0xE0) // 1110x
         return 'D';
     else if ((buf & 0xF8) == 0xF0) // 11110
         return 'E';
     else
         return '?';
 }
Referenced by getNetwork(), and getNetworkMask().
getNetmaskLength()
int inet::Ipv4Address::getNetmaskLength () const
Counts 1 bits in a netmask.
E.g. for 255.255.254.0, it will return 23.
 {
     for (int i = 0; i < 32; i++)
         if (addr & (1 << i))
             return 32 - i;
     return 0;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::RipPacketSerializer::deserialize(), inet::getNetmaskLength(), inet::eigrp::EigrpDeviceConfigurator::isEigrpInterface(), inet::bgp::operator<<(), inet::ospfv2::operator<<(), inet::Ldp::rebuildFecList(), inet::bgp::BgpRoutingTableEntry::str(), inet::Ipv4Route::str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), inet::Ipv4InterfaceData::str(), and inet::bgp::BgpRouter::updateSendProcess().
getNetwork()
Ipv4Address inet::Ipv4Address::getNetwork () const
Returns an address with the network part of the address (the bits of the hosts part are to 0).
For D and E class addresses, it returns a null address.
 {
     switch (getIPClass()) {
         case 'A':
             // Class A: network = 7 bits
             return Ipv4Address(getDByte(0), 0, 0, 0);
         case 'B':
             // Class B: network = 14 bits
             return Ipv4Address(getDByte(0), getDByte(1), 0, 0);
         case 'C':
             // Class C: network = 21 bits
             return Ipv4Address(getDByte(0), getDByte(1), getDByte(2), 0);
         default:
             // Class D or E
             return Ipv4Address();
     }
 }
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks().
getNetworkMask()
Ipv4Address inet::Ipv4Address::getNetworkMask () const
Returns an address with the network mask corresponding to the address class.
For D and E class addresses, it returns a null address.
 {
     switch (getIPClass()) {
         case 'A':
             // Class A: network = 7 bits
             return Ipv4Address(255, 0, 0, 0);
         case 'B':
             // Class B: network = 14 bits
             return Ipv4Address(255, 255, 0, 0);
         case 'C':
             // Class C: network = 21 bits
             return Ipv4Address(255, 255, 255, 0);
         default:
             // Class D or E: return null address
             return Ipv4Address();
     }
 }
Referenced by inet::eigrp::EigrpDeviceConfigurator::isEigrpInterface(), inet::eigrp::EigrpNetworkTable< inet::Ipv4Address >::isInterfaceIncluded(), isNetwork(), and inet::ospfv2::HelloHandler::processPacket().
getNumMatchingPrefixBits()
int inet::Ipv4Address::getNumMatchingPrefixBits (const Ipv4Address & to_cmp) const
Indicates how many bits from the to_cmp address, starting counting from the left, matches the address.
E.g. if the address is 130.206.72.237, and to_cmp 130.206.72.0, 24 will be returned.
Typical usage for comparing Ipv4 prefixes.
 {
     uint32_t addr2 = to_cmp.getInt();
     uint32_t res = addr ^ addr2;
     // If the bits are equal, there is a 0, so counting
     // the zeros from the left
     for (int i = 31; i >= 0; i--) {
         if (res & (1 << i)) {
             // 1, means not equal, so stop
             return 31 - i;
         }
     }
     return 32;
 }
getPrefix()
Ipv4Address inet::Ipv4Address::getPrefix (int prefixLength) const inline
Get the first prefixLength bits of the address, with the rest set to zero.
 { return doAnd(makeNetmask(prefixLength)); }
Referenced by inet::ospfv3::Ospfv3Area::InterAreaPrefixLSAAlreadyExists().
isLimitedBroadcastAddress()
bool inet::Ipv4Address::isLimitedBroadcastAddress () const inline
Returns true if this address is the limited broadcast address, i.e.
255.255.255.255.
 { return addr == 0xFFFFFFFF; }
Referenced by inet::Ipv4::datagramLocalOut(), inet::L3Address::isBroadcast(), inet::L3Address::isUnicast(), inet::Icmp::maySendErrorMessage(), inet::Ipv4::preroutingFinish(), and inet::Ipv4::resolveNextHopMacAddress().
isLinkLocalMulticast()
bool inet::Ipv4Address::isLinkLocalMulticast () const inline
Returns true if this address is in the range 224.0.0.0 to 224.0.0.255.
These addresses are reserved for local purposes meaning, that routers should not forward these datagrams since the applications that use these addresses do not need the datagrams to go further than one hop.
 { return (addr & 0xFFFFFF00) == 0xE0000000; }
Referenced by inet::PimSm::addNewRouteSG(), inet::Ipv4::forwardMulticastPacket(), inet::Igmpv2::multicastGroupJoined(), inet::Igmpv2::multicastGroupLeft(), inet::Igmpv3::multicastSourceListChanged(), inet::Ipv4::preroutingFinish(), inet::Igmpv3::sendGroupReport(), inet::Igmpv2::sendLeave(), inet::Igmpv2::sendQuery(), and inet::Igmpv2::sendReport().
isMulticast()
bool inet::Ipv4Address::isMulticast () const inline
Returns true if this address is in the multicast address range, 224.0.0.0 thru 239.255.255.255, that is, it's a class D address.
 { return (addr & 0xF0000000) == 0xE0000000; }
Referenced by inet::Ipv4InterfaceData::addMulticastListener(), inet::PimSm::addNewRouteSG(), inet::Ipv4InterfaceData::changeMulticastGroupMembership(), inet::Ipv4InterfaceData::findHostGroupData(), inet::Ipv4InterfaceData::findRouterGroupData(), inet::Ipv4::forwardMulticastPacket(), getAddressCategory(), inet::Igmpv2::HostGroupData::HostGroupData(), inet::Igmpv3::HostGroupData::HostGroupData(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::L3Address::isMulticast(), inet::L3Address::isUnicast(), mapToMulticastMacAddress(), inet::Icmp::maySendErrorMessage(), inet::Igmpv2::multicastGroupJoined(), inet::Igmpv2::multicastGroupLeft(), inet::Ipv4::preroutingFinish(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration(), inet::Ldp::rebuildFecList(), inet::Ted::rebuildRoutingTable(), inet::Ipv4InterfaceData::removeHostGroupData(), inet::Ipv4InterfaceData::removeRouterGroupData(), inet::Ipv4::resolveNextHopMacAddress(), inet::Igmpv2::RouterGroupData::RouterGroupData(), inet::Igmpv3::RouterGroupData::RouterGroupData(), inet::Igmpv3::sendGroupReport(), inet::Ldp::sendHelloTo(), inet::PimDm::sendJoinPacket(), inet::Igmpv2::sendLeave(), inet::PimDm::sendPrunePacket(), inet::Igmpv2::sendQuery(), inet::Igmpv2::sendReport(), inet::Ipv4InterfaceData::setMulticastListeners(), and inet::PimDm::unroutableMulticastPacketArrived().
isNetwork()
bool inet::Ipv4Address::isNetwork (const Ipv4Address & toCmp) const
Indicates if the address is from the same network.
 {
     Ipv4Address netmask = getNetworkMask();
     if (netmask.isUnspecified())
         return false; // Class is D or E
     return maskedAddrAreEqual(*this, toCmp, netmask);
 }
Referenced by inet::eigrp::EigrpDeviceConfigurator::isEigrpInterface(), and inet::eigrp::EigrpNetworkTable< inet::Ipv4Address >::isInterfaceIncluded().
isUnicast()
bool inet::Ipv4Address::isUnicast () const inline
Returns true if this address is unicast address.
 { return !isMulticast() && !isLimitedBroadcastAddress(); }
isUnspecified()
bool inet::Ipv4Address::isUnspecified () const inline
True if all four address bytes are zero.
The null value is customarily used to represent a missing, unspecified or invalid address in the simulation models.
 { return addr == 0; }
Referenced by inet::PimSm::addNewRouteSG(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::RsvpTe::allocateResource(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::DhcpClient::chooseInterface(), inet::Ipv4NetworkConfigurator::createInterfaceInfo(), inet::sctp::SctpNatHook::datagramForwardHook(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::PimSm::findRouteSG(), inet::Ipv4::fragmentAndSend(), inet::Ipv4::fragmentPostRouting(), getAddressCategory(), inet::PingApp::getAllAddresses(), inet::DhcpServer::getAvailableLease(), inet::ospfv2::Router::getDefaultRoute(), inet::L3AddressResolver::getInterfaceIpv4Address(), inet::eigrp::EigrpIpv4Pdm::getNextHopAddr(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), inet::Ipv4Route::getSourceTypeAbbreviation(), inet::PimSm::handleStartOperation(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::PimSm::IamDR(), inet::GlobalArp::initialize(), inet::Ted::initializeTED(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::Ipv4RoutingTable::internalAddRoute(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::Router::isDirectRoute(), inet::eigrp::EigrpDeviceConfigurator::isEigrpInterface(), inet::eigrp::EigrpNetworkTable< inet::Ipv4Address >::isInterfaceIncluded(), inet::Ipv4RoutingTable::isLocalBroadcastAddress(), isNetwork(), inet::bgp::BgpRouter::isReachable(), inet::L3Address::isUnspecified(), inet::bgp::BgpConfigReader::loadEbgpSessionConfig(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks(), inet::Ipv4MulticastRoute::matches(), inet::bgp::operator<<(), inet::ospfv2::operator<<(), inet::operator<<(), inet::RsvpTe::pathProblem(), inet::Icmp::possiblyLocalBroadcast(), inet::Ipv4::preroutingFinish(), inet::Ipv4RoutingTable::printMulticastRoutingTable(), inet::Ipv4RoutingTable::printRoutingTable(), inet::Arp::processArpPacket(), inet::PimSm::processAssertPacket(), inet::RsvpTe::processPathMsg(), inet::Igmpv2::processQuery(), inet::Igmpv3::processQuery(), inet::Ldp::rebuildFecList(), inet::RsvpTe::refreshPath(), inet::Ipv4NetworkConfigurator::resolveInterfaceAndGateway(), inet::Ipv4::routeUnicastPacket(), inet::RsvpTe::scheduleRefreshTimer(), inet::Arp::sendArpGratuitous(), inet::Arp::sendArpProbe(), inet::Arp::sendArpRequest(), inet::PimDm::sendJoinPacket(), inet::Icmp::sendOrProcessIcmpPacket(), inet::PimDm::sendPrunePacket(), inet::Igmpv2::sendQuery(), inet::DhcpMessageSerializer::serialize(), inet::Ipv4Route::str(), inet::Ipv4MulticastRoute::str(), str(), inet::PimDm::unroutableMulticastPacketArrived(), inet::PimSm::unroutableMulticastPacketArrived(), and inet::PimSm::updateDesignatedRouterAddress().
isValidNetmask()
bool inet::Ipv4Address::isValidNetmask () const inline
Returns true if the address is a valid netmask, i.e.
ones are contiguous and shifted fully to the left in the binary representation.
 { return addr == _makeNetmask(getNetmaskLength()); }
Referenced by inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::Ipv4RoutingTable::internalAddRoute(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), and inet::eigrp::EigrpDeviceConfigurator::wildcardToMask().
isWellFormed()
bool inet::Ipv4Address::isWellFormed (const char * text) static
Returns true if the format of the string corresponds to an Ipv4 address with the dotted notation ("192.66.86.1"), and false otherwise.
This function can be used to verify an Ipv4 address string before assigning it to an Ipv4Address object (both its ctor and set() function raises an error if the string has invalid format.)
 {
     unsigned char dummy[4];
     return parseIPAddress(text, dummy);
 }
Referenced by inet::Ipv4NetworkConfigurator::parseAddressAndSpecifiedBits(), inet::RoutingTableParser::parseRouting(), inet::Ipv4NetworkConfigurator::resolveInterfaceAndGateway(), inet::L3Address::tryParse(), and inet::L3AddressResolver::tryParse().
makeBroadcastAddress()
Ipv4Address inet::Ipv4Address::makeBroadcastAddress (Ipv4Address netmask) const
Returns the broadcast address for the given netmask.
 {
     Ipv4Address br(getInt() | ~(netmask.getInt()));
     return br;
 }
Referenced by inet::Ipv4RoutingTable::findInterfaceByLocalBroadcastAddress(), inet::Ipv4InterfaceData::getNetworkBroadcastAddress(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::Ipv4RoutingTable::isLocalBroadcastAddress(), and inet::Ipv4::routeLocalBroadcastPacket().
makeNetmask()
static Ipv4Address inet::Ipv4Address::makeNetmask (int length) inline static
Creates and returns a netmask with the given length.
For example, for length=23 it will return 255.255.254.0.
 { _checkNetmaskLength(length); return Ipv4Address(_makeNetmask(length)); }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::RipPacketSerializer::deserialize(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::L3Address::matches(), inet::bgp::BgpRouter::processMessage(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::RipPacketSerializer::serialize(), inet::Ipv4Route::setPrefixLength(), and inet::Ipv4MulticastRoute::setPrefixLength().
mapToMulticastMacAddress()
MacAddress inet::Ipv4Address::mapToMulticastMacAddress () const
Form a MAC address for a multicast IPv4 address, see RFC 1112, section 6.4.
 {
     ASSERT(isMulticast());
     MacAddress macAddr;
     macAddr.setAddressByte(0, 0x01);
     macAddr.setAddressByte(1, 0x00);
     macAddr.setAddressByte(2, 0x5e);
     macAddr.setAddressByte(3, (addr >> 16) & 0x7F);
     macAddr.setAddressByte(4, (addr >> 8) & 0xFF);
     macAddr.setAddressByte(5, (addr & 0xFF));
     return macAddr;
 }
Referenced by inet::L3Address::mapToMulticastMacAddress(), and inet::Ipv4::resolveNextHopMacAddress().
maskedAddrAreEqual()
bool inet::Ipv4Address::maskedAddrAreEqual (const Ipv4Address & addr1, const Ipv4Address & addr2, const Ipv4Address & netmask) static
Test if the masked addresses (ie the mask is applied to addr1 and addr2) are equal.
 {
 //    return addr1.doAnd(netmask).equals(addr2.doAnd(netmask));
     // Looks weird, but is the same and is faster
     return ((addr1.addr ^ addr2.addr) & netmask.addr) == 0;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::checkNeighborshipRules(), inet::ospfv2::Ipv4AddressRange::containedByRange(), inet::ospfv3::Ipv4AddressRange::containedByRange(), inet::ospfv2::Ipv4AddressRange::contains(), inet::ospfv3::Ipv4AddressRange::contains(), inet::ospfv2::Ipv4AddressRange::containsRange(), inet::ospfv3::Ipv4AddressRange::containsRange(), inet::Ipv4RoutingTable::findBestMatchingRoute(), inet::DhcpServer::handleStartOperation(), inet::eigrp::EigrpDeviceConfigurator::isEigrpInterface(), inet::ospfv3::Ospfv3Process::isInRoutingTable(), inet::bgp::BgpRouter::isInRoutingTable(), inet::InterfaceTable::isNeighborAddress(), isNetwork(), inet::maskedAddrAreEqual(), inet::L3Address::matches(), inet::Ipv4MulticastRoute::matches(), inet::DhcpServer::processDhcpMessage(), inet::PimDm::receiveSignal(), and inet::HostAutoConfigurator::setupNetworkLayer().
operator!=()
bool inet::Ipv4Address::operator!= (const Ipv4Address & addr1) const inline
Returns !equals(addr).
 { return !equals(addr1); }
operator<()
bool inet::Ipv4Address::operator< (const Ipv4Address & addr1) const inline
Compares two Ipv4 addresses.
 { return getInt() < addr1.getInt(); }
operator<=()
bool inet::Ipv4Address::operator<= (const Ipv4Address & addr1) const inline
 { return getInt() <= addr1.getInt(); }
operator=()
Ipv4Address& inet::Ipv4Address::operator= (const Ipv4Address & obj) inline
Assignment.
 { addr = obj.addr; return *this; }
operator==()
bool inet::Ipv4Address::operator== (const Ipv4Address & addr1) const inline
Returns equals(addr).
 { return equals(addr1); }
operator>()
bool inet::Ipv4Address::operator> (const Ipv4Address & addr1) const inline
 { return getInt() > addr1.getInt(); }
operator>=()
bool inet::Ipv4Address::operator>= (const Ipv4Address & addr1) const inline
 { return getInt() >= addr1.getInt(); }
parseIPAddress()
bool inet::Ipv4Address::parseIPAddress (const char * text, unsigned char tobytes[]) static protected
 {
     if (!text)
         return false;
     if (!strcmp(text, "<unspec>")) {
         tobytes[0] = tobytes[1] = tobytes[2] = tobytes[3] = 0;
         return true;
     }
     const char *s = text;
     int i = 0;
     while (true) {
         if (*s < '0' || *s > '9')
             return false; // missing number
         // read and store number
         int num = 0;
         while (*s >= '0' && *s <= '9')
             num = 10 * num + (*s++ - '0');
         if (num > 255)
             return false; // number too big
         tobytes[i++] = (unsigned char)num;
         if (!*s)
             break; // end of string
         if (*s != '.')
             return false; // invalid char after number
         if (i == 4)
             return false; // read 4th number and not yet EOS
         // skip '.'
         s++;
     }
     return i == 4; // must have all 4 numbers
 }
Referenced by isWellFormed(), and set().
prefixMatches()
bool inet::Ipv4Address::prefixMatches (const Ipv4Address & to_cmp, int numbits) const
Compares the first numbits bits of the two addresses.
 {
     if (length < 1)
         return true;
     if (length > 31)
         return addr == other.addr;
     uint32_t mask = _makeNetmask(length);
     return (addr & mask) == (other.addr & mask);
 }
set() [1/3]
void inet::Ipv4Address::set (const char * t)
Ipv4 address given as text: "192.66.86.1".
 {
     unsigned char buf[4];
     if (!text)
         throw cRuntimeError("Ipv4 address string is nullptr");
     bool ok = parseIPAddress(text, buf);
     if (!ok)
         throw cRuntimeError("Invalid Ipv4 address string `%s'", text);
     set(buf[0], buf[1], buf[2], buf[3]);
 }
set() [2/3]
void inet::Ipv4Address::set (int i0, int i1, int i2, int i3)
Ipv4 address bytes: "i0.i1.i2.i3" format.
 {
     addr = (i0 << 24) | (i1 << 16) | (i2 << 8) | i3;
 }
set() [3/3]
void inet::Ipv4Address::set (uint32_t ip) inline
name Setting the address
Ipv4 address as uint32_t in host byte order (e.g. "10.0.0.1" is 0x0A000001)
 { addr = ip; }
Referenced by inet::eigrp::EigrpIpv4Pdm::checkNeighborshipRules(), inet::bgp::BgpRouter::createEbgpSession(), inet::bgp::BgpRouter::createIbgpSession(), inet::doParsimUnpacking(), inet::eigrp::EigrpIpv4Pdm::getDestIpAddress(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks(), inet::ospfv2::operator&(), inet::ospfv3::operator&(), inet::ospfv2::operator|(), inet::ospfv3::operator|(), set(), and inet::eigrp::EigrpDeviceConfigurator::wildcardToMask().
str()
std::string inet::Ipv4Address::str (bool printUnspec = true) const
Returns the string representation of the address (e.g.
"152.66.86.92")
Parameters
printUnspec show 0.0.0.0 as "<unspec>" if true
 {
     if (printUnspec && isUnspecified())
         return std::string("<unspec>");
     char buf[IPADDRESS_STRING_SIZE];
     sprintf(buf, "%u.%u.%u.%u", (addr >> 24) & 255, (addr >> 16) & 255, (addr >> 8) & 255, addr & 255);
     return std::string(buf);
 }
Referenced by inet::ospfv2::Ospfv2Area::addAddressRange(), inet::Ipv4InterfaceData::addMulticastListener(), inet::bgp::BgpRouter::addToAdvertiseList(), inet::DhcpClient::bindLease(), inet::PacketFilter::DynamicExpressionResolver::callMethod(), inet::Ipv4InterfaceData::changeMulticastGroupMembership(), inet::ospfv2::Neighbor::changeState(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv3::Ospfv3Interface::detailedInfo(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::RsvpTe::evalNextHopInterface(), inet::Ldp::findInterfaceFromPeerAddr(), inet::Ted::getInterfaceAddrByPeerAddress(), inet::Ldp::getPeerSocket(), inet::SctpNatServer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::ospfv2::Ospfv2Area::info(), inet::Ted::initializeTED(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::Ipv4RoutingTable::internalAddRoute(), inet::ospfv2::Ospfv2ConfigReader::loadAreaFromXML(), inet::bgp::BgpConfigReader::loadConfigFromXML(), inet::bgp::BgpConfigReader::loadEbgpSessionConfig(), inet::ospfv2::Ospfv2ConfigReader::loadHostRoute(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::Ospfv2ConfigReader::loadLoopbackParameters(), inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink(), inet::ospfv3::operator<<(), inet::bgp::operator<<(), inet::ospfv2::operator<<(), inet::operator<<(), inet::Ted::peerRemoteInterface(), inet::ospfv2::Router::printAsExternalLsa(), inet::ospfv2::Ospfv2InterfaceState::printElectionResult(), inet::ospfv2::Ospfv2Area::printLSDB(), inet::Ipv4RoutingTable::printMulticastRoutingTable(), inet::Ipv4RoutingTable::printRoutingTable(), inet::bgp::BgpRouter::printSessionSummary(), inet::ospfv2::Ospfv2Area::printSummaryLsa(), inet::PimSm::processAssertPacket(), inet::bgp::BgpRouter::processMessage(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration(), inet::rtp::Rtp::resolveMTU(), inet::SctpNatServer::sendInfo(), inet::bgp::BgpSession::sendKeepAliveMessage(), inet::bgp::BgpSession::sendOpenMessage(), inet::PimSm::sendPIMJoin(), inet::PimSm::sendPIMPrune(), inet::bgp::BgpSession::sendUpdateMessage(), inet::bgp::BgpRouter::setLocalPreference(), inet::Ipv4InterfaceData::setMulticastListeners(), inet::bgp::BgpRouter::setNextHopSelf(), inet::HostAutoConfigurator::setupNetworkLayer(), inet::Igmpv2::startHostTimer(), inet::L3Address::str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), inet::ospfv2::Ipv4AddressRange::str(), inet::ospfv2::Ospfv2Area::str(), inet::ospfv3::Ipv4AddressRange::str(), and inet::InterfaceTable::updateLinkDisplayString().
Member Data Documentation
addr
uint32_t inet::Ipv4Address::addr protected
Referenced by equals(), getAddressCategory(), getNetmaskLength(), getNumMatchingPrefixBits(), Ipv4Address(), mapToMulticastMacAddress(), maskedAddrAreEqual(), operator=(), prefixMatches(), set(), and str().
ALL_DVMRP_ROUTERS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_DVMRP_ROUTERS_MCAST static
224.0.0.4 All DVMRP routers
ALL_HOSTS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_HOSTS_MCAST static
224.0.0.1 All hosts on a subnet
Referenced by inet::Ipv4NodeConfigurator::prepareInterface(), inet::Igmpv3::sendGeneralQuery(), inet::Igmpv2::sendQuery(), and inet::HostAutoConfigurator::setupNetworkLayer().
ALL_IGMPV3_ROUTERS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_IGMPV3_ROUTERS_MCAST static
224.0.0.22 All IGMPv3 routers
Referenced by inet::Igmpv3::initialize(), inet::Igmpv3::processHostGeneralQueryTimer(), and inet::Igmpv3::sendGroupReport().
ALL_OSPF_DESIGNATED_ROUTERS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST static
224.0.0.6 All OSPF Designated Routers
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2Interface::addDelayedAcknowledgement(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Ospfv2ConfigReader::joinMulticastGroups(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::MessageHandler::processPacket(), and inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements().
ALL_OSPF_ROUTERS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_OSPF_ROUTERS_MCAST static
224.0.0.5 All OSPF routers (DR Others)
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2Interface::addDelayedAcknowledgement(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Ospfv2ConfigReader::joinMulticastGroups(), inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Neighbor::retransmitDatabaseDescriptionPacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
ALL_RIP_ROUTERS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_RIP_ROUTERS_MCAST static
ALL_ROUTERS_MCAST
const Ipv4Address inet::Ipv4Address::ALL_ROUTERS_MCAST static
224.0.0.2 All routers on a subnet
Referenced by inet::Ldp::handleMessageWhenUp(), inet::Ipv4NodeConfigurator::prepareInterface(), inet::Igmpv2::sendLeave(), and inet::HostAutoConfigurator::setupNetworkLayer().
ALLONES_ADDRESS
const Ipv4Address inet::Ipv4Address::ALLONES_ADDRESS static
255.255.255.255
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Ipv4FlatNetworkConfigurator::assignAddresses(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::Ipv4RoutingTable::configureRouterId(), inet::PimSm::createIpv4Route(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::Ipv4AddressType::getBroadcastAddress(), inet::Dsdv::handleMessageWhenUp(), inet::Ipv4InterfaceData::Ipv4InterfaceData(), inet::bgp::BgpRouter::isRouteExcluded(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::Ipv4::preroutingFinish(), inet::bgp::BgpRouter::processMessage(), inet::UdpBasicBurst::processStart(), inet::Ted::rebuildRoutingTable(), inet::Ipv4::routeLocalBroadcastPacket(), inet::DhcpServer::sendAck(), inet::DhcpClient::sendDecline(), inet::DhcpClient::sendDiscover(), inet::DhcpServer::sendNak(), inet::DhcpServer::sendOffer(), inet::DhcpClient::sendRequest(), inet::DhcpClient::unbindLease(), inet::PimDm::unroutableMulticastPacketArrived(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
LL_MANET_ROUTERS
const Ipv4Address inet::Ipv4Address::LL_MANET_ROUTERS static
224.0.0.109 Manet all designated routers
Referenced by inet::Ipv4AddressType::getLinkLocalManetRoutersMulticastAddress(), and inet::Dsdv::start().
LOOPBACK_ADDRESS
const Ipv4Address inet::Ipv4Address::LOOPBACK_ADDRESS static
127.0.0.1
Referenced by inet::Ipv4NodeConfigurator::prepareInterface(), inet::Icmp::sendOrProcessIcmpPacket(), and inet::HostAutoConfigurator::setupNetworkLayer().
LOOPBACK_NETMASK
const Ipv4Address inet::Ipv4Address::LOOPBACK_NETMASK static
255.0.0.0
Referenced by inet::Ipv4NodeConfigurator::prepareInterface(), and inet::HostAutoConfigurator::setupNetworkLayer().
UNSPECIFIED_ADDRESS
const Ipv4Address inet::Ipv4Address::UNSPECIFIED_ADDRESS static
0.0.0.0
Referenced by inet::ospfv3::Ospfv3Interface::acknowledgeLSA(), inet::ospfv3::Ospfv3Interface::addDelayedAcknowledgement(), inet::PimSm::addNewRouteG(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv3::Ospfv3Area::calculateNextHops(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::PimSm::createIpv4Route(), inet::eigrp::EigrpIpv4Pdm::createRouteTlv(), inet::ospfv3::Ospfv3Instance::detailedInfo(), inet::PimSm::findRouteG(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::NetworkInterface::getIpv4Address(), inet::NetworkInterface::getIpv4Netmask(), inet::GlobalArp::getL3AddressFor(), inet::Arp::getL3AddressFor(), inet::Ipv4AddressType::getLinkLocalAddress(), inet::Ipv4::getNextHop(), inet::Ipv4AddressType::getUnspecifiedAddress(), inet::Ipv4::handlePacketFromHL(), inet::TunnelApp::initialize(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks(), inet::bgp::BgpRouter::openTCPConnectionToPeer(), inet::ospfv3::Ospfv3Neighbor::Ospfv3Neighbor(), inet::RoutingTableParser::parseRouting(), inet::PimSm::processAssertG(), inet::ospfv3::Ospfv3Interface::processLSR(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Instance::processPacket(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Arp::sendArpProbe(), inet::PimDm::sendAssertPacket(), inet::ospfv3::Ospfv3Interface::sendDelayedAcknowledgements(), inet::PimDm::sendGraftPacket(), inet::PimDm::sendJoinPacket(), inet::PimSm::sendPIMAssert(), inet::PimSm::sendPIMJoin(), inet::PimSm::sendPIMPrune(), inet::PimSm::sendPIMRegister(), inet::PimSm::sendPIMRegisterNull(), inet::PimDm::sendPrunePacket(), inet::PimDm::sendStateRefreshPacket(), and inet::PimDm::unroutableMulticastPacketArrived().
The documentation for this class was generated from the following files:
Ipv4Address.h
Ipv4Address.cc