INET Framework for OMNeT++/OMNEST: inet::ieee80211::IDuplicateRemoval Class Reference
inet::ieee80211::IDuplicateRemoval Class Reference abstract
#include <IDuplicateRemoval.h>
Public Member Functions
virtual ~IDuplicateRemoval ()
virtual bool isDuplicate (const Ptr< const Ieee80211DataOrMgmtHeader > &header)=0
Constructor & Destructor Documentation
~IDuplicateRemoval()
virtual inet::ieee80211::IDuplicateRemoval::~IDuplicateRemoval () inline virtual
 {}
Member Function Documentation
isDuplicate()
virtual bool inet::ieee80211::IDuplicateRemoval::isDuplicate (const Ptr< const Ieee80211DataOrMgmtHeader > & header) pure virtual
Implemented in inet::ieee80211::QoSDuplicateRemoval, and inet::ieee80211::LegacyDuplicateRemoval.
Referenced by inet::ieee80211::RecipientQosMacDataService::dataFrameReceived(), inet::ieee80211::RecipientMacDataService::dataOrMgmtFrameReceived(), and inet::ieee80211::RecipientQosMacDataService::managementFrameReceived().
The documentation for this class was generated from the following file:
IDuplicateRemoval.h