INET Framework for OMNeT++/OMNEST: inet::NetfilterBase::HookBase Class Reference
inet::NetfilterBase::HookBase Class Reference
#include <INetfilter.h>
Public Member Functions
virtual ~HookBase ()
void registeredTo (INetfilter *nf)
void unregisteredFrom (INetfilter *nf)
bool isRegisteredHook (INetfilter *nf)
Public Member Functions inherited from inet::INetfilter::IHook
virtual ~IHook ()
virtual Result datagramPreRoutingHook (Packet *datagram)=0
This is the first hook called by the network protocol before it routes a datagram that was received from the lower layer.
virtual Result datagramForwardHook (Packet *datagram)=0
This is the second hook called by the network protocol before it sends a datagram to the lower layer.
virtual Result datagramPostRoutingHook (Packet *datagram)=0
This is the last hook called by the network protocol before it sends a datagram to the lower layer.
virtual Result datagramLocalInHook (Packet *datagram)=0
This is the last hook called by the network protocol before it sends a datagram to the upper layer.
virtual Result datagramLocalOutHook (Packet *datagram)=0
This is the first hook called by the network protocol before it routes a datagram that was received from the upper layer.
Protected Attributes
std::vector< INetfilter * > netfilters
Friends
class NetfilterBase
Additional Inherited Members
Public Types inherited from inet::INetfilter::IHook
enum Type {
PREROUTING, LOCALIN, FORWARD, POSTROUTING,
LOCALOUT
}
enum Result { ACCEPT, DROP, QUEUE, STOLEN }
Constructor & Destructor Documentation
~HookBase()
virtual inet::NetfilterBase::HookBase::~HookBase () inline virtual
 { for (auto netfilter : netfilters) netfilter->unregisterHook(this); }
Member Function Documentation
isRegisteredHook()
bool inet::NetfilterBase::HookBase::isRegisteredHook (INetfilter * nf) inline
 { return contains(netfilters, nf); }
Referenced by inet::sctp::SctpNatHook::finish(), inet::CloudDelayerBase::finish(), and inet::NetfilterInfoHook::finish().
registeredTo()
void inet::NetfilterBase::HookBase::registeredTo (INetfilter * nf) inline
 { ASSERT(!isRegisteredHook(nf)); netfilters.push_back(nf); }
unregisteredFrom()
void inet::NetfilterBase::HookBase::unregisteredFrom (INetfilter * nf) inline
 { ASSERT(isRegisteredHook(nf)); remove(netfilters, nf); }
Friends And Related Function Documentation
NetfilterBase
friend class NetfilterBase friend
Member Data Documentation
netfilters
std::vector<INetfilter *> inet::NetfilterBase::HookBase::netfilters protected
The documentation for this class was generated from the following file:
INetfilter.h