INET Framework for OMNeT++/OMNEST: inet::bgp::BgpOpenMessage Class Reference
inet::bgp::BgpOpenMessage Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:89 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpOpenMessage ()
BgpOpenMessage (const BgpOpenMessage &other)
virtual ~BgpOpenMessage ()
BgpOpenMessage & operator= (const BgpOpenMessage &other)
virtual BgpOpenMessage * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getVersion () const
virtual void setVersion (uint8_t version)
virtual uint16_t getMyAS () const
virtual void setMyAS (uint16_t myAS)
virtual ::omnetpp::simtime_t getHoldTime () const
virtual void setHoldTime (::omnetpp::simtime_t holdTime)
virtual const ::inet::Ipv4Address & getBGPIdentifier () const
virtual ::inet::Ipv4Address & getBGPIdentifierForUpdate ()
virtual void setBGPIdentifier (const ::inet::Ipv4Address &BGPIdentifier)
virtual unsigned short getOptionalParametersLength () const
virtual void setOptionalParametersLength (unsigned short optionalParametersLength)
virtual void setOptionalParameterArraySize (size_t size)
virtual size_t getOptionalParameterArraySize () const
virtual const BgpOptionalParameterBase * getOptionalParameter (size_t k) const
virtual BgpOptionalParameterBase * getOptionalParameterForUpdate (size_t k)
virtual void setOptionalParameter (size_t k, BgpOptionalParameterBase *optionalParameter)
virtual BgpOptionalParameterBase * removeOptionalParameter (size_t k)
BgpOptionalParameterBase * dropOptionalParameter (size_t k)
virtual void insertOptionalParameter (size_t k, BgpOptionalParameterBase *optionalParameter)
void insertOptionalParameter (BgpOptionalParameterBase *optionalParameter)
virtual void appendOptionalParameter (BgpOptionalParameterBase *optionalParameter)
virtual void eraseOptionalParameter (size_t k)
Public Member Functions inherited from inet::bgp::BgpHeader
BgpHeader ()
BgpHeader (const BgpHeader &other)
virtual ~BgpHeader ()
BgpHeader & operator= (const BgpHeader &other)
virtual size_t getMarkerArraySize () const
virtual uint8_t getMarker (size_t k) const
virtual void setMarker (size_t k, uint8_t marker)
virtual uint16_t getTotalLength () const
virtual void setTotalLength (uint16_t totalLength)
virtual BgpType getType () const
virtual void setType (BgpType type)
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const BgpOpenMessage &)=delete
Protected Member Functions inherited from inet::bgp::BgpHeader
bool operator== (const BgpHeader &)=delete
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Protected Attributes
uint8_t version = 4
uint16_t myAS = 0
::omnetpp::simtime_t holdTime = SIMTIME_ZERO
::inet::Ipv4Address BGPIdentifier
unsigned short optionalParametersLength = 0
BgpOptionalParameterBase ** optionalParameter = nullptr
size_t optionalParameter_arraysize = 0
Protected Attributes inherited from inet::bgp::BgpHeader
uint8_t marker [16]
uint16_t totalLength = B(BGP_HEADER_OCTETS).get()
BgpType type = static_cast<BgpType>(-1)
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const BgpOpenMessage &other)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:89 by opp_msgtool.
//
// Represents a BGPv4 OPEN message.
//
class BgpOpenMessage extends BgpHeader
{
    type = BGP_OPEN;
    chunkLength = BGP_HEADER_OCTETS + BGP_OPEN_OCTETS;
    totalLength = B(BGP_HEADER_OCTETS + BGP_OPEN_OCTETS).get();
    uint8_t version = 4;    // BGP Version, 1 octet
    uint16_t myAS;    // My Autonomous system, 2 octets
    simtime_t holdTime;    // Hold Time in seconds, 2 octets
    Ipv4Address BGPIdentifier;    // 4 octets
    unsigned short optionalParametersLength;    // 1 octet, total length (in bytes) of optionalParameters[] (if = 0, no optional parameters)
    BgpOptionalParameterBase *optionalParameter[] @owned;
}
Constructor & Destructor Documentation
BgpOpenMessage() [1/2]
inet::bgp::BgpOpenMessage::BgpOpenMessage ()
BgpOpenMessage() [2/2]
inet::bgp::BgpOpenMessage::BgpOpenMessage (const BgpOpenMessage & other)
~BgpOpenMessage()
virtual inet::bgp::BgpOpenMessage::~BgpOpenMessage () virtual
Member Function Documentation
appendOptionalParameter()
virtual void inet::bgp::BgpOpenMessage::appendOptionalParameter (BgpOptionalParameterBase * optionalParameter) virtual
copy()
void inet::bgp::BgpOpenMessage::copy (const BgpOpenMessage & other) private
dropOptionalParameter()
BgpOptionalParameterBase* inet::bgp::BgpOpenMessage::dropOptionalParameter (size_t k) inline
 {return removeOptionalParameter(k);}
dup()
virtual BgpOpenMessage* inet::bgp::BgpOpenMessage::dup () const inline override virtual
Reimplemented from inet::bgp::BgpHeader.
 {return new BgpOpenMessage(*this);}
eraseOptionalParameter()
virtual void inet::bgp::BgpOpenMessage::eraseOptionalParameter (size_t k) virtual
getBGPIdentifier()
virtual const ::inet::Ipv4Address& inet::bgp::BgpOpenMessage::getBGPIdentifier () const virtual
Referenced by inet::bgp::BgpRouter::printOpenMessage().
getBGPIdentifierForUpdate()
virtual ::inet::Ipv4Address& inet::bgp::BgpOpenMessage::getBGPIdentifierForUpdate () inline
 { handleChange();return const_cast<::inet::Ipv4Address&>(const_cast<BgpOpenMessage*>(this)->getBGPIdentifier());}
getHoldTime()
virtual ::omnetpp::simtime_t inet::bgp::BgpOpenMessage::getHoldTime () const
Referenced by inet::bgp::BgpRouter::printOpenMessage().
getMyAS()
virtual uint16_t inet::bgp::BgpOpenMessage::getMyAS () const virtual
Referenced by inet::bgp::BgpRouter::printOpenMessage().
getOptionalParameter()
virtual const BgpOptionalParameterBase* inet::bgp::BgpOpenMessage::getOptionalParameter (size_t k) const virtual
Referenced by inet::bgp::BgpRouter::printOpenMessage().
getOptionalParameterArraySize()
virtual size_t inet::bgp::BgpOpenMessage::getOptionalParameterArraySize () const virtual
Referenced by inet::bgp::BgpRouter::printOpenMessage().
getOptionalParameterForUpdate()
virtual BgpOptionalParameterBase* inet::bgp::BgpOpenMessage::getOptionalParameterForUpdate (size_t k) inline virtual
 { handleChange();return const_cast<BgpOptionalParameterBase *>(const_cast<BgpOpenMessage*>(this)->getOptionalParameter(k));}
getOptionalParametersLength()
virtual unsigned short inet::bgp::BgpOpenMessage::getOptionalParametersLength () const virtual
getVersion()
virtual uint8_t inet::bgp::BgpOpenMessage::getVersion () const virtual
insertOptionalParameter() [1/2]
void inet::bgp::BgpOpenMessage::insertOptionalParameter (BgpOptionalParameterBase * optionalParameter) inline
 {appendOptionalParameter(optionalParameter);}
insertOptionalParameter() [2/2]
virtual void inet::bgp::BgpOpenMessage::insertOptionalParameter (size_t k, BgpOptionalParameterBase * optionalParameter) virtual
operator=()
BgpOpenMessage& inet::bgp::BgpOpenMessage::operator= (const BgpOpenMessage & other)
operator==()
bool inet::bgp::BgpOpenMessage::operator== (const BgpOpenMessage &) protected delete
parsimPack()
virtual void inet::bgp::BgpOpenMessage::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::bgp::BgpHeader.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpOpenMessage::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::bgp::BgpHeader.
Referenced by inet::bgp::doParsimUnpacking().
removeOptionalParameter()
virtual BgpOptionalParameterBase* inet::bgp::BgpOpenMessage::removeOptionalParameter (size_t k) virtual
setBGPIdentifier()
virtual void inet::bgp::BgpOpenMessage::setBGPIdentifier (const ::inet::Ipv4Address & BGPIdentifier) virtual
setHoldTime()
virtual void inet::bgp::BgpOpenMessage::setHoldTime (::omnetpp::simtime_t holdTime) virtual
setMyAS()
virtual void inet::bgp::BgpOpenMessage::setMyAS (uint16_t myAS) virtual
setOptionalParameter()
virtual void inet::bgp::BgpOpenMessage::setOptionalParameter (size_t k, BgpOptionalParameterBase * optionalParameter) virtual
setOptionalParameterArraySize()
virtual void inet::bgp::BgpOpenMessage::setOptionalParameterArraySize (size_t size) virtual
setOptionalParametersLength()
virtual void inet::bgp::BgpOpenMessage::setOptionalParametersLength (unsigned short optionalParametersLength) virtual
setVersion()
virtual void inet::bgp::BgpOpenMessage::setVersion (uint8_t version) virtual
Member Data Documentation
BGPIdentifier
::inet::Ipv4Address inet::bgp::BgpOpenMessage::BGPIdentifier protected
holdTime
::omnetpp::simtime_t inet::bgp::BgpOpenMessage::holdTime = SIMTIME_ZERO protected
myAS
uint16_t inet::bgp::BgpOpenMessage::myAS = 0 protected
optionalParameter
BgpOptionalParameterBase* * inet::bgp::BgpOpenMessage::optionalParameter = nullptr protected
optionalParameter_arraysize
size_t inet::bgp::BgpOpenMessage::optionalParameter_arraysize = 0 protected
optionalParametersLength
unsigned short inet::bgp::BgpOpenMessage::optionalParametersLength = 0 protected
version
uint8_t inet::bgp::BgpOpenMessage::version = 4 protected
The documentation for this class was generated from the following file:
BgpHeader_m.h