INET Framework for OMNeT++/OMNEST: inet::Ipv4NatEntry Class Reference
inet::Ipv4NatEntry Class Reference
Class generated from inet/networklayer/ipv4/Ipv4NatEntry.msg:13 by opp_msgtool.
#include <Ipv4NatEntry_m.h>
Public Member Functions
Ipv4NatEntry ()
Ipv4NatEntry (const Ipv4NatEntry &other)
virtual ~Ipv4NatEntry ()
Ipv4NatEntry & operator= (const Ipv4NatEntry &other)
virtual Ipv4NatEntry * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ipv4Address & getDestAddress () const
virtual Ipv4Address & getDestAddressForUpdate ()
virtual void setDestAddress (const Ipv4Address &destAddress)
virtual int getDestPort () const
virtual void setDestPort (int destPort)
virtual const Ipv4Address & getSrcAddress () const
virtual Ipv4Address & getSrcAddressForUpdate ()
virtual void setSrcAddress (const Ipv4Address &srcAddress)
virtual int getSrcPort () const
virtual void setSrcPort (int srcPort)
Protected Member Functions
bool operator== (const Ipv4NatEntry &)=delete
Protected Attributes
Ipv4Address destAddress
int destPort = -1
Ipv4Address srcAddress
int srcPort = -1
Private Member Functions
void copy (const Ipv4NatEntry &other)
Detailed Description
Class generated from inet/networklayer/ipv4/Ipv4NatEntry.msg:13 by opp_msgtool.
class Ipv4NatEntry extends cObject
{
    Ipv4Address destAddress;
    int destPort = -1;
    Ipv4Address srcAddress;
    int srcPort = -1;
}
Constructor & Destructor Documentation
Ipv4NatEntry() [1/2]
inet::Ipv4NatEntry::Ipv4NatEntry ()
Ipv4NatEntry() [2/2]
inet::Ipv4NatEntry::Ipv4NatEntry (const Ipv4NatEntry & other)
~Ipv4NatEntry()
virtual inet::Ipv4NatEntry::~Ipv4NatEntry () virtual
Member Function Documentation
copy()
void inet::Ipv4NatEntry::copy (const Ipv4NatEntry & other) private
dup()
virtual Ipv4NatEntry* inet::Ipv4NatEntry::dup () const inline override virtual
 {return new Ipv4NatEntry(*this);}
getDestAddress()
virtual const Ipv4Address& inet::Ipv4NatEntry::getDestAddress () const virtual
getDestAddressForUpdate()
virtual Ipv4Address& inet::Ipv4NatEntry::getDestAddressForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<Ipv4NatEntry*>(this)->getDestAddress());}
getDestPort()
virtual int inet::Ipv4NatEntry::getDestPort () const virtual
getSrcAddress()
virtual const Ipv4Address& inet::Ipv4NatEntry::getSrcAddress () const virtual
getSrcAddressForUpdate()
virtual Ipv4Address& inet::Ipv4NatEntry::getSrcAddressForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<Ipv4NatEntry*>(this)->getSrcAddress());}
getSrcPort()
virtual int inet::Ipv4NatEntry::getSrcPort () const virtual
operator=()
Ipv4NatEntry& inet::Ipv4NatEntry::operator= (const Ipv4NatEntry & other)
operator==()
bool inet::Ipv4NatEntry::operator== (const Ipv4NatEntry &) protected delete
parsimPack()
virtual void inet::Ipv4NatEntry::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv4NatEntry::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setDestAddress()
virtual void inet::Ipv4NatEntry::setDestAddress (const Ipv4Address & destAddress) virtual
Referenced by inet::Ipv4NatTable::parseConfig().
setDestPort()
virtual void inet::Ipv4NatEntry::setDestPort (int destPort) virtual
Referenced by inet::Ipv4NatTable::parseConfig().
setSrcAddress()
virtual void inet::Ipv4NatEntry::setSrcAddress (const Ipv4Address & srcAddress) virtual
Referenced by inet::Ipv4NatTable::parseConfig().
setSrcPort()
virtual void inet::Ipv4NatEntry::setSrcPort (int srcPort) virtual
Referenced by inet::Ipv4NatTable::parseConfig().
Member Data Documentation
destAddress
Ipv4Address inet::Ipv4NatEntry::destAddress protected
destPort
int inet::Ipv4NatEntry::destPort = -1 protected
srcAddress
Ipv4Address inet::Ipv4NatEntry::srcAddress protected
srcPort
int inet::Ipv4NatEntry::srcPort = -1 protected
The documentation for this class was generated from the following file:
Ipv4NatEntry_m.h