INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211Vhtmcs Class Reference
inet::physicallayer::Ieee80211Vhtmcs Class Reference
#include <Ieee80211VhtMode.h>
Public Member Functions
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211VhtCode *code, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211OfdmModulation *stream5Modulation, const Ieee80211OfdmModulation *stream6Modulation, const Ieee80211OfdmModulation *stream7Modulation, const Ieee80211OfdmModulation *stream8Modulation)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211OfdmModulation *stream5Modulation, const Ieee80211OfdmModulation *stream6Modulation, const Ieee80211OfdmModulation *stream7Modulation, const Ieee80211OfdmModulation *stream8Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211OfdmModulation *stream5Modulation, const Ieee80211OfdmModulation *stream6Modulation, const Ieee80211OfdmModulation *stream7Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211OfdmModulation *stream5Modulation, const Ieee80211OfdmModulation *stream6Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211OfdmModulation *stream5Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth)
Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211ConvolutionalCode *convolutionalCode, Hz bandwidth, int nss)
virtual ~Ieee80211Vhtmcs ()
const Ieee80211VhtCode * getCode () const
unsigned int getMcsIndex () const
virtual const Ieee80211OfdmModulation * getModulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension1Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension2Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension3Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension4Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension5Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension6Modulation () const
virtual const Ieee80211OfdmModulation * getStreamExtension7Modulation () const
virtual Hz getBandwidth () const
virtual unsigned int getNumNss () const
Protected Attributes
const unsigned int mcsIndex
const Ieee80211OfdmModulation * stream1Modulation = nullptr
const Ieee80211OfdmModulation * stream2Modulation = nullptr
const Ieee80211OfdmModulation * stream3Modulation = nullptr
const Ieee80211OfdmModulation * stream4Modulation = nullptr
const Ieee80211OfdmModulation * stream5Modulation = nullptr
const Ieee80211OfdmModulation * stream6Modulation = nullptr
const Ieee80211OfdmModulation * stream7Modulation = nullptr
const Ieee80211OfdmModulation * stream8Modulation = nullptr
const Ieee80211VhtCode * code
const Hz bandwidth
Constructor & Destructor Documentation
Ieee80211Vhtmcs() [1/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211VhtCode * code, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211OfdmModulation * stream5Modulation, const Ieee80211OfdmModulation * stream6Modulation, const Ieee80211OfdmModulation * stream7Modulation, const Ieee80211OfdmModulation * stream8Modulation)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     stream5Modulation(stream5Modulation),
     stream6Modulation(stream6Modulation),
     stream7Modulation(stream7Modulation),
     stream8Modulation(stream8Modulation),
     code(code)
 {
 }
Ieee80211Vhtmcs() [2/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211OfdmModulation * stream5Modulation, const Ieee80211OfdmModulation * stream6Modulation, const Ieee80211OfdmModulation * stream7Modulation, const Ieee80211OfdmModulation * stream8Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     stream5Modulation(stream5Modulation),
     stream6Modulation(stream6Modulation),
     stream7Modulation(stream7Modulation),
     stream8Modulation(stream8Modulation),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [3/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211OfdmModulation * stream5Modulation, const Ieee80211OfdmModulation * stream6Modulation, const Ieee80211OfdmModulation * stream7Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     stream5Modulation(stream5Modulation),
     stream6Modulation(stream6Modulation),
     stream7Modulation(stream7Modulation),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [4/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211OfdmModulation * stream5Modulation, const Ieee80211OfdmModulation * stream6Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                                                                                                                      :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     stream5Modulation(stream5Modulation),
     stream6Modulation(stream6Modulation),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [5/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211OfdmModulation * stream5Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                                                                    :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     stream5Modulation(stream5Modulation),
     stream6Modulation(nullptr),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [6/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                  :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(stream4Modulation),
     stream5Modulation(nullptr),
     stream6Modulation(nullptr),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [7/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                                                                                :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(stream3Modulation),
     stream4Modulation(nullptr),
     stream5Modulation(nullptr),
     stream6Modulation(nullptr),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [8/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                                                                              :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(stream2Modulation),
     stream3Modulation(nullptr),
     stream4Modulation(nullptr),
     stream5Modulation(nullptr),
     stream6Modulation(nullptr),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [9/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth)
                                                                                                                                                                            :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(nullptr),
     stream3Modulation(nullptr),
     stream4Modulation(nullptr),
     stream5Modulation(nullptr),
     stream6Modulation(nullptr),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     code(Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth)),
     bandwidth(bandwidth)
 {
 }
Ieee80211Vhtmcs() [10/10]
inet::physicallayer::Ieee80211Vhtmcs::Ieee80211Vhtmcs (unsigned int mcsIndex, const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211ConvolutionalCode * convolutionalCode, Hz bandwidth, int nss)
                                                                                                                                                                                     :
     mcsIndex(mcsIndex),
     stream1Modulation(stream1Modulation),
     stream2Modulation(nullptr),
     stream3Modulation(nullptr),
     stream4Modulation(nullptr),
     stream5Modulation(nullptr),
     stream6Modulation(nullptr),
     stream7Modulation(nullptr),
     stream8Modulation(nullptr),
     bandwidth(bandwidth)
 {
     if (nss > 1)
         stream2Modulation = stream1Modulation;
     if (nss > 2)
         stream3Modulation = stream1Modulation;
     if (nss > 3)
         stream4Modulation = stream1Modulation;
     if (nss > 4)
         stream5Modulation = stream1Modulation;
     if (nss > 5)
         stream6Modulation = stream1Modulation;
     if (nss > 6)
         stream7Modulation = stream1Modulation;
     if (nss > 7)
         stream8Modulation = stream1Modulation;
     code = Ieee80211VhtCompliantCodes::getCompliantCode(convolutionalCode, stream1Modulation, stream2Modulation, stream3Modulation, stream4Modulation, stream5Modulation, stream6Modulation, stream7Modulation, stream8Modulation, bandwidth);
 }
~Ieee80211Vhtmcs()
inet::physicallayer::Ieee80211Vhtmcs::~Ieee80211Vhtmcs () virtual
 {
     delete code;
 }
Member Function Documentation
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211Vhtmcs::getBandwidth () const inline virtual
 { return bandwidth; }
Referenced by inet::physicallayer::Ieee80211VhtCompliantModes::getCompliantMode().
getCode()
const Ieee80211VhtCode* inet::physicallayer::Ieee80211Vhtmcs::getCode () const inline
 { return code; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::getCode().
getMcsIndex()
unsigned int inet::physicallayer::Ieee80211Vhtmcs::getMcsIndex () const inline
 { return mcsIndex; }
Referenced by inet::physicallayer::Ieee80211VhtCompliantModes::getCompliantMode().
getModulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getModulation () const inline virtual
 { return stream1Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum(), and inet::physicallayer::Ieee80211VhtDataMode::getModulation().
getNumNss()
virtual unsigned int inet::physicallayer::Ieee80211Vhtmcs::getNumNss () const inline virtual
{
         return (stream1Modulation ? 1 : 0) + (stream2Modulation ? 1 : 0)
                + (stream3Modulation ? 1 : 0) + (stream4Modulation ? 1 : 0)
                + (stream5Modulation ? 1 : 0) + (stream6Modulation ? 1 : 0)
                + (stream7Modulation ? 1 : 0) + (stream8Modulation ? 1 : 0);
     }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfSpatialStreams(), and inet::physicallayer::Ieee80211VhtCompliantModes::getCompliantMode().
getStreamExtension1Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension1Modulation () const inline virtual
 { return stream2Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension2Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension2Modulation () const inline virtual
 { return stream3Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension3Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension3Modulation () const inline virtual
 { return stream4Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension4Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension4Modulation () const inline virtual
 { return stream5Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension5Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension5Modulation () const inline virtual
 { return stream6Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension6Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension6Modulation () const inline virtual
 { return stream7Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
getStreamExtension7Modulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::getStreamExtension7Modulation () const inline virtual
 { return stream8Modulation; }
Referenced by inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum().
Member Data Documentation
bandwidth
const Hz inet::physicallayer::Ieee80211Vhtmcs::bandwidth protected
Referenced by Ieee80211Vhtmcs().
code
const Ieee80211VhtCode* inet::physicallayer::Ieee80211Vhtmcs::code protected
Referenced by Ieee80211Vhtmcs(), and ~Ieee80211Vhtmcs().
mcsIndex
const unsigned int inet::physicallayer::Ieee80211Vhtmcs::mcsIndex protected
stream1Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream1Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream2Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream2Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream3Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream3Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream4Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream4Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream5Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream5Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream6Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream6Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream7Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream7Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
stream8Modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211Vhtmcs::stream8Modulation = nullptr protected
Referenced by Ieee80211Vhtmcs().
The documentation for this class was generated from the following files:
Ieee80211VhtMode.h
Ieee80211VhtMode.cc