INET Framework for OMNeT++/OMNEST: inet::LineSegment Class Reference
inet::LineSegment Class Reference
This class represents a 3 dimensional line segment between two points.
#include <LineSegment.h>
Public Member Functions
LineSegment ()
LineSegment (const Coord &point1, const Coord &point2)
const Coord & getPoint1 () const
void setPoint1 (const Coord &point1)
const Coord & getPoint2 () const
void setPoint2 (const Coord &point2)
double length () const
virtual bool isNil () const override
Returns true if this geometric object is the same as the unspecified singleton instance of this type.
virtual bool isUnspecified () const override
Returns true if this geometric object is not completely specified.
bool computeIntersection (const LineSegment &lineSegment, Coord &intersection1, Coord &intersection2)
Public Member Functions inherited from inet::GeometricObjectBase
GeometricObjectBase ()
virtual ~GeometricObjectBase ()
Static Public Attributes
static const LineSegment NIL
Protected Attributes
Coord point1
Coord point2
Detailed Description
This class represents a 3 dimensional line segment between two points.
Constructor & Destructor Documentation
LineSegment() [1/2]
inet::LineSegment::LineSegment ()
                          :
     point1(Coord::NIL),
     point2(Coord::NIL)
 {
 }
LineSegment() [2/2]
inet::LineSegment::LineSegment (const Coord & point1, const Coord & point2)
                                                                  :
     point1(point1),
     point2(point2)
 {
 }
Member Function Documentation
computeIntersection()
bool inet::LineSegment::computeIntersection (const LineSegment & lineSegment, Coord & intersection1, Coord & intersection2)
 {
     // TODO
     throw cRuntimeError("Not yet implemented");
 }
getPoint1()
const Coord& inet::LineSegment::getPoint1 () const inline
 { return point1; }
Referenced by inet::Sphere::computeIntersection(), inet::Cuboid::computeIntersection(), inet::Polygon::computeIntersection(), inet::Plane::computeIntersection(), inet::Prism::computeIntersection(), inet::Polyhedron::computeIntersection(), inet::BvhTree::intersectWithLineSegment(), and inet::SpatialGrid::LineSegmentIterator::LineSegmentIterator().
getPoint2()
const Coord& inet::LineSegment::getPoint2 () const inline
 { return point2; }
Referenced by inet::Sphere::computeIntersection(), inet::Cuboid::computeIntersection(), inet::Polygon::computeIntersection(), inet::Plane::computeIntersection(), inet::Prism::computeIntersection(), inet::Polyhedron::computeIntersection(), inet::BvhTree::intersectWithLineSegment(), and inet::SpatialGrid::LineSegmentIterator::LineSegmentIterator().
isNil()
virtual bool inet::LineSegment::isNil () const inline override virtual
Returns true if this geometric object is the same as the unspecified singleton instance of this type.
Implements inet::GeometricObjectBase.
 { return this == &NIL; }
isUnspecified()
virtual bool inet::LineSegment::isUnspecified () const inline override virtual
Returns true if this geometric object is not completely specified.
Implements inet::GeometricObjectBase.
 { return point1.isUnspecified() || point2.isUnspecified(); }
length()
double inet::LineSegment::length () const inline
 { return point2.distance(point1); }
Referenced by inet::Cuboid::computeIntersection().
setPoint1()
void inet::LineSegment::setPoint1 (const Coord & point1) inline
 { this->point1 = point1; }
setPoint2()
void inet::LineSegment::setPoint2 (const Coord & point2) inline
 { this->point2 = point2; }
Member Data Documentation
NIL
const LineSegment inet::LineSegment::NIL static
point1
Coord inet::LineSegment::point1 protected
point2
Coord inet::LineSegment::point2 protected
The documentation for this class was generated from the following files:
LineSegment.h
LineSegment.cc