INET Framework for OMNeT++/OMNEST: inet::L3Address Class Reference
inet::L3Address Class Reference
This class provides the generic interface for network addresses.
#include <L3Address.h>
Public Types
enum AddressType {
NONE, IPv4, IPv6, CLNS,
MAC, MODULEPATH, MODULEID
}
Public Member Functions
L3Address ()
L3Address (const L3Address &other)
L3Address (const char *str)
L3Address (const Ipv4Address &addr)
L3Address (const Ipv6Address &addr)
L3Address (const MacAddress &addr)
L3Address (const ModuleIdAddress &addr)
L3Address (const ModulePathAddress &addr)
L3Address (const ClnsAddress &addr)
void set (const Ipv4Address &addr)
void set (const Ipv6Address &addr)
void set (const MacAddress &addr)
void set (const ModuleIdAddress &addr)
void set (const ModulePathAddress &addr)
void set (const ClnsAddress &addr)
void reset ()
Ipv4Address toIpv4 () const
Ipv6Address toIpv6 () const
MacAddress toMac () const
ModuleIdAddress toModuleId () const
ModulePathAddress toModulePath () const
ClnsAddress toClns () const
std::string str () const
AddressType getType () const
IL3AddressType * getAddressType () const
L3Address getPrefix (int prefixLength) const
Get the first prefixLength bits of the address, with the rest set to zero.
bool tryParse (const char *addr)
bool isUnspecified () const
bool isUnicast () const
bool isMulticast () const
bool isBroadcast () const
bool isLinkLocal () const
L3Address & operator= (const L3Address &other)
bool operator< (const L3Address &other) const
bool operator> (const L3Address &other) const
bool operator== (const L3Address &other) const
bool operator!= (const L3Address &other) const
bool matches (const L3Address &other, int prefixLength) const
MacAddress mapToMulticastMacAddress () const
void doParsimPacking (cCommBuffer *buf) const
void doParsimUnpacking (cCommBuffer *buf)
Static Public Member Functions
static const char * getTypeName (AddressType t)
Private Member Functions
uint64_t get (AddressType type) const
void set (AddressType type, uint64_t lo)
Private Attributes
uint64_t hi
uint64_t lo
Detailed Description
This class provides the generic interface for network addresses.
For efficiency reasons the implementation uses a 128 bits integer to represent all kinds of network addresses. The different address implementations should not subclass this class, they should rather provide conversions to and from this class.
See also
Ipv4Address, Ipv6Address, CLNSAddress, MacAddress, ModulePathAddress, ModuleIdAddress
Member Enumeration Documentation
AddressType
enum inet::L3Address::AddressType
Enumerator
NONE
IPv4
IPv6
CLNS
MAC
MODULEPATH
MODULEID
                      {
         NONE,
         IPv4,
         IPv6,
         CLNS,
         MAC,
         MODULEPATH,
         MODULEID
     };
Constructor & Destructor Documentation
L3Address() [1/9]
inet::L3Address::L3Address () inline
 { set(NONE, 0); }
Referenced by getPrefix().
L3Address() [2/9]
inet::L3Address::L3Address (const L3Address & other) inline
 : hi(other.hi), lo(other.lo) {}
L3Address() [3/9]
inet::L3Address::L3Address (const char * str) inline explicit
 { tryParse(str); }
L3Address() [4/9]
inet::L3Address::L3Address (const Ipv4Address & addr) inline
 { set(addr); }
L3Address() [5/9]
inet::L3Address::L3Address (const Ipv6Address & addr) inline
 { set(addr); }
L3Address() [6/9]
inet::L3Address::L3Address (const MacAddress & addr) inline
 { set(addr); }
L3Address() [7/9]
inet::L3Address::L3Address (const ModuleIdAddress & addr) inline
 { set(addr); }
L3Address() [8/9]
inet::L3Address::L3Address (const ModulePathAddress & addr) inline
 { set(addr); }
L3Address() [9/9]
inet::L3Address::L3Address (const ClnsAddress & addr) inline
 { set(addr); }
Member Function Documentation
doParsimPacking()
void inet::L3Address::doParsimPacking (cCommBuffer * buf) const inline
     {
         buf->pack(hi);
         buf->pack(lo);
     }
Referenced by inet::doParsimPacking().
doParsimUnpacking()
void inet::L3Address::doParsimUnpacking (cCommBuffer * buf) inline
     {
         buf->unpack(hi);
         buf->unpack(lo);
     }
Referenced by inet::doParsimUnpacking().
get()
uint64_t inet::L3Address::get (AddressType type) const private
 {
     if (getType() == type)
         return lo;
     else
         throw cRuntimeError("Address is not of the given type");
 }
Referenced by inet::Ipv4::arpResolutionTimedOut().
getAddressType()
IL3AddressType * inet::L3Address::getAddressType () const
 {
     switch (getType()) {
         case L3Address::NONE:
             throw cRuntimeError("Address contains no value");
         case L3Address::IPv4:
             return &Ipv4AddressType::INSTANCE;
         case L3Address::IPv6:
             return &Ipv6AddressType::INSTANCE;
         case L3Address::MAC:
             return &MacAddressType::INSTANCE;
         case L3Address::MODULEID:
             return &ModuleIdAddressType::INSTANCE;
         case L3Address::MODULEPATH:
             return &ModulePathAddressType::INSTANCE;
         case L3Address::CLNS:
             return &CLNSAddressType::INSTANCE;
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::Gpsr::computeOptionLength(), inet::ProbabilisticBroadcast::encapsulate(), inet::Flooding::encapsulate(), inet::Gpsr::initialize(), inet::dymo::Dymo::initialize(), inet::aodv::Aodv::initialize(), inet::aodv::Aodv::receiveSignal(), inet::dymo::Dymo::receiveSignal(), inet::sctp::Sctp::sendAbortFromMain(), inet::IpvxTrafGen::sendPacket(), inet::sctp::Sctp::sendShutdownCompleteFromMain(), inet::tcp::TcpSpoof::sendToIP(), and inet::tcp::TcpConnection::sendToIP().
getPrefix()
L3Address inet::L3Address::getPrefix (int prefixLength) const
Get the first prefixLength bits of the address, with the rest set to zero.
 {
     switch (getType()) {
         case L3Address::NONE:
             return *this;
         case L3Address::IPv4:
             return L3Address(toIpv4().getPrefix(prefixLength));
         case L3Address::IPv6:
             return L3Address(toIpv6().getPrefix(prefixLength));
         case L3Address::MAC:
             if (prefixLength != 48)
                 throw cRuntimeError("mask not supported for MacAddress");
             return *this;
         case L3Address::MODULEID:
         case L3Address::MODULEPATH:
             return *this;
         default:
             throw cRuntimeError("getPrefix(): Unknown type");
     }
 }
Referenced by inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv3::Ospfv3Area::findInterAreaPrefixLSAbyAddress(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::InterAreaPrefixLSAAlreadyExists().
getType()
L3Address::AddressType inet::L3Address::getType () const
 {
     if (hi >> 48 == RESERVED_IPV6_ADDRESS_RANGE)
         return (AddressType)(hi & 0xFF);
     else
         return L3Address::IPv6;
 }
Referenced by inet::MultiFieldClassifier::addFilter(), inet::Udp::addMulticastAddressToInterface(), inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::Ipv4::arpResolutionCompleted(), inet::Ipv4::arpResolutionTimedOut(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::NetworkInterface::changeMulticastGroupMembership(), inet::MultiFieldClassifier::configureFilters(), inet::sctp::SctpAssociation::createSack(), inet::sctp::Sctp::findAssocForInitAck(), inet::InterfaceTable::findInterfaceByAddress(), get(), inet::sctp::SctpAssociation::getAddressLevel(), getAddressType(), inet::L3AddressResolver::getInterfaceModuleIdAddress(), inet::L3AddressResolver::getInterfaceModulePathAddress(), getPrefix(), inet::Gpsr::getSelfAddress(), inet::PingApp::handleSelfMessage(), inet::Udp::handleUpperPacket(), inet::NetworkInterface::hasNetworkAddress(), inet::EthernetSocketIo::initialize(), inet::Ieee8022LlcSocketIo::initialize(), isBroadcast(), isLinkLocal(), isMulticast(), inet::InterfaceTable::isNeighborAddress(), isUnicast(), isUnspecified(), inet::NetworkInterface::joinMulticastGroup(), mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), matches(), operator<(), operator==(), inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::processInitArrived(), inet::sctp::SctpAssociation::sendAsconf(), inet::sctp::SctpAssociation::sendInit(), inet::PingApp::sendPingRequest(), inet::sctp::SctpHeaderSerializer::serialize(), set(), str(), and toClns().
getTypeName()
const char * inet::L3Address::getTypeName (AddressType t) static
 {
 #define CASE(x)    case x: \
         return #x
     switch (t) {
         CASE(NONE);
         CASE(IPv4);
         CASE(IPv6);
         CASE(MAC);
         CASE(MODULEID);
         CASE(MODULEPATH);
         default:
             return "Unknown type";
     }
 #undef CASE
 }
Referenced by inet::NetworkInterface::changeMulticastGroupMembership(), and inet::PingApp::handleSelfMessage().
isBroadcast()
bool inet::L3Address::isBroadcast () const
 {
     switch (getType()) {
         case L3Address::NONE:
             throw cRuntimeError("Address contains no value");
         case L3Address::IPv4:
             return toIpv4().isLimitedBroadcastAddress();
         case L3Address::IPv6:
             return false;
 //        throw cRuntimeError("Ipv6 isBroadcast() unimplemented");
         case L3Address::MAC:
             return toMac().isBroadcast();
         case L3Address::MODULEID:
             return toModuleId().isBroadcast();
         case L3Address::MODULEPATH:
             return toModulePath().isBroadcast();
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::aodv::Aodv::datagramForwardHook(), inet::Gpsr::datagramLocalOutHook(), inet::Gpsr::datagramPreRoutingHook(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::dymo::Dymo::ensureRouteForDatagram(), inet::dymo::Dymo::permissibleRteMsg(), inet::GlobalArp::resolveL3Address(), and inet::aodv::Aodv::sendAODVPacket().
isLinkLocal()
bool inet::L3Address::isLinkLocal () const
 {
     switch (getType()) {
         case L3Address::NONE:
             throw cRuntimeError("Address contains no value");
         case L3Address::IPv4:
             return false;
         case L3Address::IPv6:
             return toIpv6().isLinkLocal();
         case L3Address::MAC:
             return true;
         case L3Address::MODULEID:
             return false;
         case L3Address::MODULEPATH:
             return false;
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::Rip::isValidResponse(), and inet::Rip::startRIPRouting().
isMulticast()
bool inet::L3Address::isMulticast () const
 {
     switch (getType()) {
         case L3Address::NONE:
             throw cRuntimeError("Address contains no value");
         case L3Address::IPv4:
             return toIpv4().isMulticast();
         case L3Address::IPv6:
             return toIpv6().isMulticast();
         case L3Address::MAC:
             return toMac().isMulticast();
         case L3Address::MODULEID:
             return toModuleId().isMulticast();
         case L3Address::MODULEPATH:
             return toModulePath().isMulticast();
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::Udp::addMulticastAddressToInterface(), inet::Udp::blockMulticastSources(), inet::aodv::Aodv::datagramForwardHook(), inet::Gpsr::datagramLocalOutHook(), inet::Gpsr::datagramPreRoutingHook(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::dymo::Dymo::ensureRouteForDatagram(), inet::L3AddressResolver::findHostWithAddress(), inet::Udp::handleUpperPacket(), inet::NextHopRoutingTable::isLocalMulticastAddress(), inet::Udp::joinMulticastGroups(), inet::Udp::joinMulticastSources(), inet::Udp::leaveMulticastSources(), mapToMulticastMacAddress(), inet::dymo::Dymo::permissibleRteMsg(), inet::GlobalArp::resolveL3Address(), inet::Rip::sendPacket(), inet::Udp::setMulticastSourceFilter(), inet::UdpSink::setSocketOptions(), inet::Rip::startRIPRouting(), and inet::Udp::unblockMulticastSources().
isUnicast()
bool inet::L3Address::isUnicast () const
 {
     switch (getType()) {
         case L3Address::NONE:
             throw cRuntimeError("Address contains no value");
         case L3Address::IPv4:
             return !toIpv4().isMulticast() && !toIpv4().isLimitedBroadcastAddress(); // TODO move to Ipv4Address
         case L3Address::IPv6:
             return toIpv6().isUnicast();
         case L3Address::MAC:
             return !toMac().isBroadcast() && !toMac().isMulticast(); // TODO move to MacAddress
         case L3Address::MODULEID:
             return toModuleId().isUnicast();
         case L3Address::MODULEPATH:
             return toModulePath().isUnicast();
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::Rip::isValidResponse(), inet::dymo::Dymo::processRerr(), and inet::GlobalArp::resolveL3Address().
isUnspecified()
bool inet::L3Address::isUnspecified () const
 {
     switch (getType()) {
         case L3Address::NONE:
             return true;
         case L3Address::IPv4:
             return toIpv4().isUnspecified();
         case L3Address::IPv6:
             return toIpv6().isUnspecified();
         case L3Address::MAC:
             return toMac().isUnspecified();
         case L3Address::MODULEID:
             return toModuleId().isUnspecified();
         case L3Address::MODULEPATH:
             return toModulePath().isUnspecified();
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::MultiFieldClassifier::addFilter(), inet::sctp::Sctp::addLocalAddress(), inet::sctp::Sctp::addLocalAddressToAllRemoteAddresses(), inet::tcp::Tcp::addSockPair(), inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::NextHopRoutingTable::configureRouterId(), inet::TcpAppBase::connect(), inet::SctpClient::connect(), inet::SctpPeer::connect(), inet::UdpSocket::connect(), inet::Udp::connect(), inet::Udp::createSocket(), inet::aodv::Aodv::ensureRouteForDatagram(), inet::dymo::Dymo::ensureRouteForDatagram(), inet::Gpsr::findGreedyRoutingNextHop(), inet::L3AddressResolver::findHostWithAddress(), inet::InterfaceTable::findInterfaceByAddress(), inet::Gpsr::findPerimeterRoutingNextHop(), inet::Udp::findSocketForUnicastPacket(), inet::L3AddressResolver::getInterfaceModuleIdAddress(), inet::L3AddressResolver::getInterfaceModulePathAddress(), inet::UdpSink::handleCrashOperation(), inet::ospfv2::Ospfv2::handleInterfaceDown(), inet::IpvxTrafGen::handleMessageWhenUp(), inet::PingApp::handleSelfMessage(), inet::UdpSink::handleStopOperation(), inet::Udp::handleUpperPacket(), inet::GlobalArp::initialize(), inet::InterfaceTable::isNeighborAddress(), inet::operator<<(), inet::dymo::Dymo::permissibleRteMsg(), inet::RipProtocolPrinter::print(), inet::sctp::SctpAssociation::process_ASSOCIATE(), inet::tcp::TcpLwipConnection::process_OPEN_ACTIVE(), inet::tcp::TcpConnection::process_OPEN_ACTIVE(), inet::sctp::SctpAssociation::process_SEND(), inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::Gpsr::processBeaconTimer(), inet::Rip::processResponse(), inet::UdpBasicApp::processStart(), inet::UdpSink::processStop(), inet::tcp::TcpConnection::processTCPSegment(), inet::sctp::SctpAssociation::processTimer(), inet::UdpVideoStreamClient::requestStream(), inet::NextHopForwarding::routePacket(), inet::NextHopForwarding::sendDatagramToOutput(), inet::sctp::SctpAssociation::sendInit(), inet::tcp::TcpConnection::sendSyn(), inet::SimpleVoipSender::sendVoIPPacket(), inet::PositionTable::setPosition(), inet::UdpSink::setSocketOptions(), inet::NextHopRoute::str(), inet::RipRoute::str(), inet::NetPerfMeter::transmitFrame(), and inet::L3AddressResolver::tryResolve().
mapToMulticastMacAddress()
MacAddress inet::L3Address::mapToMulticastMacAddress () const
 {
     ASSERT(isMulticast());
     int id = 0;
     switch (getType()) {
         case L3Address::IPv4:
             return toIpv4().mapToMulticastMacAddress();
         case L3Address::IPv6:
             return toIpv6().mapToMulticastMacAddress();
         case L3Address::MAC:
             return toMac();
         case L3Address::MODULEID: {
             ModuleIdAddress moduleIdAddress = toModuleId();
             id = moduleIdAddress.getId();
             MacAddress macAddress;
             macAddress.setAddressByte(0, 0x01);
             macAddress.setAddressByte(1, 0x00);
             macAddress.setAddressByte(2, (id >> 24) & 0xFF);
             macAddress.setAddressByte(3, (id >> 16) & 0xFF);
             macAddress.setAddressByte(4, (id >> 8)  & 0xFF);
             macAddress.setAddressByte(5, (id >> 0)  & 0xFF);
             return macAddress;
         }
         case L3Address::MODULEPATH: {
             ModulePathAddress modulePathAddress = toModulePath();
             id = modulePathAddress.getId();
             MacAddress macAddress;
             macAddress.setAddressByte(0, 0x01);
             macAddress.setAddressByte(1, 0x00);
             macAddress.setAddressByte(2, (id >> 24) & 0xFF);
             macAddress.setAddressByte(3, (id >> 16) & 0xFF);
             macAddress.setAddressByte(4, (id >> 8)  & 0xFF);
             macAddress.setAddressByte(5, (id >> 0)  & 0xFF);
             return macAddress;
         }
         default:
             throw cRuntimeError("Unknown address type");
     }
 }
Referenced by inet::GlobalArp::resolveL3Address().
matches()
bool inet::L3Address::matches (const L3Address & other, int prefixLength) const
 {
     switch (getType()) {
         case L3Address::NONE:
             throw cRuntimeError("Address contains no value");
         case L3Address::IPv4:
             return Ipv4Address::maskedAddrAreEqual(toIpv4(), other.toIpv4(), Ipv4Address::makeNetmask(prefixLength)); // FIXME !!!!!
         case L3Address::IPv6:
             return toIpv6().matches(other.toIpv6(), prefixLength);
         case L3Address::MAC:
             return toMac() == other.toMac();
         case L3Address::MODULEID:
             return toModuleId() == other.toModuleId();
         case L3Address::MODULEPATH:
             return ModulePathAddress::maskedAddrAreEqual(toModulePath(), other.toModulePath(), prefixLength);
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::NextHopRoutingTable::findBestMatchingRoute().
operator!=()
bool inet::L3Address::operator!= (const L3Address & other) const
 {
     return !operator==(other);
 }
operator<()
bool inet::L3Address::operator< (const L3Address & other) const
 {
     AddressType type = getType();
     AddressType otherType = other.getType();
     if (type != otherType)
         return type < otherType;
     else {
         switch (type) {
             case L3Address::NONE:
                 throw cRuntimeError("Address contains no value");
             case L3Address::IPv4:
                 return toIpv4() < other.toIpv4();
             case L3Address::IPv6:
                 return toIpv6() < other.toIpv6();
             case L3Address::MAC:
                 return toMac() < other.toMac();
             case L3Address::MODULEID:
                 return toModuleId() < other.toModuleId();
             case L3Address::MODULEPATH:
                 return toModulePath() < other.toModulePath();
             default:
                 throw cRuntimeError("Unknown type");
         }
     }
 }
operator=()
L3Address& inet::L3Address::operator= (const L3Address & other) inline
 { hi = other.hi; lo = other.lo; return *this; }
operator==()
bool inet::L3Address::operator== (const L3Address & other) const
 {
     AddressType type = getType();
     if (type != other.getType())
         return false;
     else {
         switch (type) {
             case L3Address::NONE:
                 return true;
             case L3Address::IPv4:
                 return toIpv4() == other.toIpv4();
             case L3Address::IPv6:
                 return toIpv6() == other.toIpv6();
             case L3Address::MAC:
                 return toMac() == other.toMac();
             case L3Address::MODULEID:
                 return toModuleId() == other.toModuleId();
             case L3Address::MODULEPATH:
                 return toModulePath() == other.toModulePath();
             default:
                 throw cRuntimeError("Unknown type");
         }
     }
 }
Referenced by operator!=().
operator>()
bool inet::L3Address::operator> (const L3Address & other) const inline
 { return other < *this; };
reset()
void inet::L3Address::reset () inline
 { set(NONE, 0); }
set() [1/7]
void inet::L3Address::set (AddressType type, uint64_t lo) private
 {
     this->hi = ((uint64_t)RESERVED_IPV6_ADDRESS_RANGE << 48) + (uint64_t)type;
     this->lo = lo;
 }
Referenced by inet::L3AddressResolver::getInterfaceIpv4Address(), inet::L3AddressResolver::getInterfaceIpv6Address(), tryParse(), and inet::L3AddressResolver::tryParse().
set() [2/7]
void inet::L3Address::set (const ClnsAddress & addr)
 {
     hi = ((uint64_t)RESERVED_IPV6_ADDRESS_RANGE << 48) | ((addr.getAreaId() & 0xFFFFFFFFL) << 16) | (uint64_t)addr.getNsel() << 8 | (uint64_t)L3Address::CLNS;
     lo = addr.getSystemId();
 }
set() [3/7]
void inet::L3Address::set (const Ipv4Address & addr) inline
 { set(IPv4, addr.getInt()); }
Referenced by set().
set() [4/7]
void inet::L3Address::set (const Ipv6Address & addr)
 {
     const uint32_t *words = addr.words();
     hi = ((uint64_t)*(words + 0) << 32) + *(words + 1);
     lo = ((uint64_t)*(words + 2) << 32) + *(words + 3);
     if (getType() != IPv6)
         throw cRuntimeError("Cannot set Ipv6 address");
 }
set() [5/7]
void inet::L3Address::set (const MacAddress & addr) inline
 { set(MAC, addr.getInt()); }
Referenced by set().
set() [6/7]
void inet::L3Address::set (const ModuleIdAddress & addr) inline
 { set(MODULEID, addr.getId()); }
Referenced by set().
set() [7/7]
void inet::L3Address::set (const ModulePathAddress & addr) inline
 { set(MODULEPATH, addr.getId()); }
Referenced by set().
str()
std::string inet::L3Address::str () const
 {
     switch (getType()) {
         case L3Address::NONE:
             return "<none>";
         case L3Address::IPv4:
             return toIpv4().str();
         case L3Address::IPv6:
             return toIpv6().str();
         case L3Address::MAC:
             return toMac().str();
         case L3Address::MODULEID:
             return toModuleId().str();
         case L3Address::MODULEPATH:
             return toModulePath().str();
         case L3Address::CLNS:
             return toClns().str();
         default:
             throw cRuntimeError("Unknown type");
     }
 }
Referenced by inet::tcp::Tcp::addSockPair(), inet::Udp::bind(), inet::Udp::blockMulticastSources(), inet::PacketFilter::DynamicExpressionResolver::callMethod(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::NextHopRoutingTable::findBestMatchingMulticastRoute(), inet::NextHopRoutingTable::findBestMatchingRoute(), inet::NextHopRoutingTable::getInterfaceByAddress(), inet::NextHopRoutingTable::getNextHopForDestination(), inet::NextHopRoutingTable::getOutputInterfaceForDestination(), inet::UdpSocket::getReceivedPacketInfo(), inet::NextHopRoutingTable::isLocalAddress(), inet::NextHopRoutingTable::isLocalMulticastAddress(), inet::Udp::joinMulticastGroups(), inet::Udp::joinMulticastSources(), inet::Udp::leaveMulticastSources(), inet::operator<<(), inet::RoutingTableRecorder::recordRouteChange(), inet::sctp::Sctp::removeAssociation(), inet::NetworkInterface::resolveDirective(), inet::Arp::resolveL3Address(), inet::sctp::SctpPathVariables::SctpPathVariables(), inet::NextHopForwarding::sendDatagramToOutput(), inet::PingApp::sendPingRequest(), and inet::Udp::unblockMulticastSources().
toClns()
ClnsAddress inet::L3Address::toClns () const
 {
     switch (getType()) {
         case L3Address::NONE:
             return ClnsAddress();
         case L3Address::CLNS:
             return ClnsAddress((hi & 0x0000FFFFFFFF0000L) >> 16, lo, (hi & 0xFF00L) >> 8);
         default:
             throw cRuntimeError("Address is not of the given type");
     }
 }
Referenced by str().
toIpv4()
Ipv4Address inet::L3Address::toIpv4 () const inline
 { return getType() == NONE ? Ipv4Address() : Ipv4Address(get(IPv4)); }
Referenced by inet::Udp::addMulticastAddressToInterface(), inet::SctpNatPeer::addressAddedArrived(), inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::Ipv4::arpResolutionCompleted(), inet::Ipv4::arpResolutionTimedOut(), inet::ExtLowerUdp::bind(), inet::Ipv4Socket::bind(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::NetworkInterface::changeMulticastGroupMembership(), inet::ExtLowerUdp::connect(), inet::Ipv4Socket::connect(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::sctp::SctpNatHook::datagramPreRoutingHook(), inet::Define_Module(), inet::Ipv4RoutingTable::findBestMatchingMulticastRoute(), inet::Ipv4RoutingTable::findBestMatchingRoute(), inet::InterfaceTable::findInterfaceByAddress(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::sctp::SctpAssociation::getAddressLevel(), inet::Ipv4RoutingTable::getInterfaceByAddress(), inet::Ipv4::getNextHop(), inet::Ipv4RoutingTable::getNextHopForDestination(), inet::Ipv4RoutingTable::getOutputInterfaceForDestination(), inet::xmlutils::getParameterIPAddressValue(), getPrefix(), inet::DhcpServer::handleStartOperation(), inet::NetworkInterface::hasNetworkAddress(), inet::ospfv2::ipv4AddressFromAddressString(), inet::ospfv2::ipv4NetmaskFromAddressString(), isBroadcast(), inet::Ipv4RoutingTable::isLocalAddress(), inet::Ipv4RoutingTable::isLocalMulticastAddress(), isMulticast(), inet::InterfaceTable::isNeighborAddress(), isUnicast(), isUnspecified(), inet::NetworkInterface::joinMulticastGroup(), mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), matches(), operator<(), operator==(), inet::PimSm::processAssertPacket(), inet::PimDm::processGraftAckPacket(), inet::PimDm::processGraftPacket(), inet::PimDm::processJoinPrunePacket(), inet::PimSm::processJoinPrunePacket(), inet::bgp::BgpRouter::processMessageFromTCP(), inet::Igmpv3::processQuery(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::RsvpTe::readTrafficRouteFromXML(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::Ipv4NetworkConfigurator::resolveInterfaceAndGateway(), inet::Arp::resolveL3Address(), inet::SctpNatServer::sendInfo(), inet::sctp::SctpAssociation::sendInit(), inet::bgp::BgpSession::sendOpenMessage(), inet::Ipv4Socket::sendTo(), inet::RipPacketSerializer::serialize(), inet::sctp::SctpHeaderSerializer::serialize(), inet::Ipv4Route::setDestination(), inet::Ipv4Header::setDestinationAddress(), inet::Ipv4MulticastRoute::setMulticastGroup(), inet::Ipv4Route::setNextHop(), inet::Ipv4MulticastRoute::setOrigin(), inet::Ipv4Header::setSourceAddress(), inet::Ldp::socketAvailable(), inet::SctpNatPeer::socketEstablished(), and str().
toIpv6()
Ipv6Address inet::L3Address::toIpv6 () const inline
 { return getType() == NONE ? Ipv6Address() : Ipv6Address(hi, get(IPv6)); }
Referenced by inet::Udp::addMulticastAddressToInterface(), inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::Ipv6Socket::bind(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::Ipv6Socket::connect(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::detailedInfo(), inet::Ipv6RoutingTable::findBestMatchingRoute(), inet::InterfaceTable::findInterfaceByAddress(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::sctp::SctpAssociation::getAddressLevel(), inet::Ipv6RoutingTable::getInterfaceByAddress(), inet::L3AddressResolver::getIpv6AddressFrom(), inet::Ipv6RoutingTable::getNextHopForDestination(), inet::Ipv6RoutingTable::getOutputInterfaceForDestination(), getPrefix(), inet::Ipv6::handleMessage(), inet::Ipv6::handleMessageFromHL(), inet::NetworkInterface::hasNetworkAddress(), isLinkLocal(), inet::Ipv6RoutingTable::isLocalAddress(), isMulticast(), inet::InterfaceTable::isNeighborAddress(), isUnicast(), isUnspecified(), inet::NetworkInterface::joinMulticastGroup(), mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), matches(), operator<(), operator==(), inet::ospfv3::Ospfv3Interface::processHelloPacket(), inet::Ipv6NeighbourDiscovery::processNsForNonTentativeAddress(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::Ipv6NeighbourDiscovery::sendSolicitedNa(), inet::Ipv6Socket::sendTo(), inet::sctp::SctpHeaderSerializer::serialize(), inet::Ipv6Route::setDestination(), inet::Ipv6Header::setDestinationAddress(), inet::Ipv6Route::setNextHop(), inet::Ipv6Header::setSourceAddress(), str(), inet::Ipv6NeighbourDiscovery::validateNaPacket(), inet::Ipv6NeighbourDiscovery::validateNsPacket(), and inet::Ipv6NeighbourDiscovery::validateRsPacket().
toMac()
MacAddress inet::L3Address::toMac () const inline
 { return getType() == NONE ? MacAddress() : MacAddress(get(MAC)); }
Referenced by inet::StreamDecoder::configureMappings(), inet::InterfaceTable::findInterfaceByAddress(), inet::Ipv6::fragmentPostRouting(), inet::NetworkInterface::hasNetworkAddress(), inet::ieee80211::Ieee80211MgmtStaSimplified::initialize(), inet::EthernetSocketIo::initialize(), inet::Ieee8022LlcSocketIo::initialize(), isBroadcast(), isMulticast(), isUnicast(), isUnspecified(), mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), matches(), operator<(), operator==(), inet::MacForwardingTable::parseForwardingTableParameter(), inet::MacForwardingTable::readForwardingTable(), inet::EtherAppClient::resolveDestMacAddress(), inet::EtherTrafGen::resolveDestMacAddress(), and str().
toModuleId()
ModuleIdAddress inet::L3Address::toModuleId () const inline
 { return getType() == NONE ? ModuleIdAddress() : ModuleIdAddress(get(MODULEID)); }
Referenced by inet::InterfaceTable::findInterfaceByAddress(), inet::NetworkInterface::hasNetworkAddress(), isBroadcast(), isMulticast(), isUnicast(), isUnspecified(), mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), matches(), operator<(), operator==(), and str().
toModulePath()
ModulePathAddress inet::L3Address::toModulePath () const inline
 { return getType() == NONE ? ModulePathAddress() : ModulePathAddress(get(MODULEPATH)); }
Referenced by inet::InterfaceTable::findInterfaceByAddress(), inet::NetworkInterface::hasNetworkAddress(), isBroadcast(), isMulticast(), isUnicast(), isUnspecified(), mapToMulticastMacAddress(), inet::GlobalArp::mapUnicastAddress(), matches(), operator<(), operator==(), and str().
tryParse()
bool inet::L3Address::tryParse (const char * addr)
 {
     Ipv6Address ipv6;
     MacAddress mac;
     ModuleIdAddress moduleId;
     ModulePathAddress modulePath;
     if (Ipv4Address::isWellFormed(addr))
         set(Ipv4Address(addr));
     else if (ipv6.tryParse(addr))
         set(ipv6);
     else if (mac.tryParse(addr))
         set(mac);
     else if (moduleId.tryParse(addr))
         set(moduleId);
     else if (modulePath.tryParse(addr))
         set(modulePath);
     else
         return false;
     return true;
 }
Member Data Documentation
hi
uint64_t inet::L3Address::hi private
Referenced by getType(), operator=(), set(), and toClns().
lo
uint64_t inet::L3Address::lo private
Referenced by get(), operator=(), set(), and toClns().
The documentation for this class was generated from the following files:
L3Address.h
L3Address.cc