INET Framework for OMNeT++/OMNEST: inet::PacketEvent Class Reference
inet::PacketEvent Class Reference
Class generated from inet/common/PacketEventTag.msg:24 by opp_msgtool.
#include <PacketEventTag_m.h>
Public Member Functions
PacketEvent ()
PacketEvent (const PacketEvent &other)
virtual ~PacketEvent ()
PacketEvent & operator= (const PacketEvent &other)
virtual PacketEvent * dup () const override
virtual std::string str () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getKind () const
virtual void setKind (int kind)
virtual const char * getModulePath () const
virtual void setModulePath (const char *modulePath)
virtual int64_t getEventNumber () const
virtual void setEventNumber (int64_t eventNumber)
virtual ::omnetpp::simtime_t getSimulationTime () const
virtual void setSimulationTime (::omnetpp::simtime_t simulationTime)
virtual ::omnetpp::simtime_t getDuration () const
virtual void setDuration (::omnetpp::simtime_t duration)
virtual b getPacketLength () const
virtual void setPacketLength (b packetLength)
Protected Member Functions
bool operator== (const PacketEvent &)=delete
Protected Attributes
int kind = PEK_UNDEFINED
::omnetpp::opp_string modulePath
int64_t eventNumber = -1
::omnetpp::simtime_t simulationTime = -1
::omnetpp::simtime_t duration = -1
b packetLength = b(-1)
Private Member Functions
void copy (const PacketEvent &other)
Detailed Description
Class generated from inet/common/PacketEventTag.msg:24 by opp_msgtool.
class PacketEvent extends cObject
{
    @str(getClassName());
    int kind @enum(PacketEventKind) = PEK_UNDEFINED;
    string modulePath;
    int64_t eventNumber = -1;
    simtime_t simulationTime = -1;
    simtime_t duration = -1;
    b packetLength = b(-1);
}
Constructor & Destructor Documentation
PacketEvent() [1/2]
inet::PacketEvent::PacketEvent ()
PacketEvent() [2/2]
inet::PacketEvent::PacketEvent (const PacketEvent & other)
~PacketEvent()
virtual inet::PacketEvent::~PacketEvent () virtual
Member Function Documentation
copy()
void inet::PacketEvent::copy (const PacketEvent & other) private
dup()
virtual PacketEvent* inet::PacketEvent::dup () const inline override virtual
Reimplemented in inet::PacketTransmittedEvent, and inet::PacketQueuedEvent.
 {return new PacketEvent(*this);}
Referenced by inet::insertPacketEvent().
getDuration()
virtual ::omnetpp::simtime_t inet::PacketEvent::getDuration () const
getEventNumber()
virtual int64_t inet::PacketEvent::getEventNumber () const virtual
getKind()
virtual int inet::PacketEvent::getKind () const virtual
getModulePath()
virtual const char* inet::PacketEvent::getModulePath () const virtual
getPacketLength()
virtual b inet::PacketEvent::getPacketLength () const virtual
getSimulationTime()
virtual ::omnetpp::simtime_t inet::PacketEvent::getSimulationTime () const
operator=()
PacketEvent& inet::PacketEvent::operator= (const PacketEvent & other)
operator==()
bool inet::PacketEvent::operator== (const PacketEvent &) protected delete
parsimPack()
virtual void inet::PacketEvent::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::PacketTransmittedEvent, and inet::PacketQueuedEvent.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::PacketEvent::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::PacketTransmittedEvent, and inet::PacketQueuedEvent.
Referenced by inet::doParsimUnpacking().
setDuration()
virtual void inet::PacketEvent::setDuration (::omnetpp::simtime_t duration) virtual
setEventNumber()
virtual void inet::PacketEvent::setEventNumber (int64_t eventNumber) virtual
setKind()
virtual void inet::PacketEvent::setKind (int kind) virtual
Referenced by inet::insertPacketEvent().
setModulePath()
virtual void inet::PacketEvent::setModulePath (const char * modulePath) virtual
setPacketLength()
virtual void inet::PacketEvent::setPacketLength (b packetLength) virtual
setSimulationTime()
virtual void inet::PacketEvent::setSimulationTime (::omnetpp::simtime_t simulationTime) virtual
str()
virtual std::string inet::PacketEvent::str () const override virtual
Member Data Documentation
duration
::omnetpp::simtime_t inet::PacketEvent::duration = -1 protected
eventNumber
int64_t inet::PacketEvent::eventNumber = -1 protected
kind
int inet::PacketEvent::kind = PEK_UNDEFINED protected
modulePath
::omnetpp::opp_string inet::PacketEvent::modulePath protected
packetLength
b inet::PacketEvent::packetLength = b(-1) protected
simulationTime
::omnetpp::simtime_t inet::PacketEvent::simulationTime = -1 protected
The documentation for this class was generated from the following file:
PacketEventTag_m.h