INET Framework for OMNeT++/OMNEST: inet::physicallayer::ScalarNoise Class Reference
inet::physicallayer::ScalarNoise Class Reference
#include <ScalarNoise.h>
Public Member Functions
ScalarNoise (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth, const std::map< simtime_t, W > *powerChanges)
virtual ~ScalarNoise ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const std::map< simtime_t, W > * getPowerChanges () const
virtual W computeMinPower (simtime_t startTime, simtime_t endTime) const override
virtual W computeMaxPower (simtime_t startTime, simtime_t endTime) const override
Public Member Functions inherited from inet::physicallayer::NarrowbandNoiseBase
NarrowbandNoiseBase (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth)
virtual Hz getCenterFrequency () const
virtual Hz getBandwidth () const
Public Member Functions inherited from inet::physicallayer::NoiseBase
NoiseBase (simtime_t startTime, simtime_t endTime)
virtual const simtime_t getStartTime () const override
virtual const simtime_t getEndTime () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const std::map< simtime_t, W > * powerChanges
Protected Attributes inherited from inet::physicallayer::NarrowbandNoiseBase
const Hz centerFrequency
const Hz bandwidth
Protected Attributes inherited from inet::physicallayer::NoiseBase
const simtime_t startTime
const simtime_t endTime
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
ScalarNoise()
inet::physicallayer::ScalarNoise::ScalarNoise (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth, const std::map< simtime_t, W > * powerChanges)
                                                                                                                                            :
     NarrowbandNoiseBase(startTime, endTime, centerFrequency, bandwidth),
     powerChanges(powerChanges)
 {
 }
~ScalarNoise()
virtual inet::physicallayer::ScalarNoise::~ScalarNoise () inline virtual
 { delete powerChanges; }
Member Function Documentation
computeMaxPower()
W inet::physicallayer::ScalarNoise::computeMaxPower (simtime_t startTime, simtime_t endTime) const override virtual
Implements inet::physicallayer::NarrowbandNoiseBase.
 {
     W noisePower = W(0);
     W maxNoisePower = W(NaN);
     simtime_t previousTime;
     for (const auto& elem : *powerChanges) {
         if ((std::isnan(maxNoisePower.get()) || noisePower > maxNoisePower) && previousTime < startTime && elem.first > endTime)
             maxNoisePower = noisePower;
         noisePower += elem.second;
         if ((std::isnan(maxNoisePower.get()) || noisePower > maxNoisePower) && startTime <= elem.first && elem.first < endTime)
             maxNoisePower = noisePower;
         previousTime = elem.first;
     }
     if (std::isnan(maxNoisePower.get()))
         maxNoisePower = previousTime < startTime ? W(0) : noisePower;
     return maxNoisePower;
 }
Referenced by inet::physicallayer::ScalarSnir::computeMin().
computeMinPower()
W inet::physicallayer::ScalarNoise::computeMinPower (simtime_t startTime, simtime_t endTime) const override virtual
Implements inet::physicallayer::NarrowbandNoiseBase.
 {
     W noisePower = W(0);
     W minNoisePower = W(NaN);
     simtime_t previousTime;
     for (const auto& elem : *powerChanges) {
         if ((std::isnan(minNoisePower.get()) || noisePower < minNoisePower) && previousTime < startTime && elem.first > endTime)
             minNoisePower = noisePower;
         noisePower += elem.second;
         if ((std::isnan(minNoisePower.get()) || noisePower < minNoisePower) && startTime <= elem.first && elem.first < endTime)
             minNoisePower = noisePower;
         previousTime = elem.first;
     }
     if (std::isnan(minNoisePower.get()))
         minNoisePower = previousTime < startTime ? W(0) : noisePower;
     return minNoisePower;
 }
Referenced by inet::physicallayer::ScalarSnir::computeMax().
getPowerChanges()
virtual const std::map<simtime_t, W>* inet::physicallayer::ScalarNoise::getPowerChanges () const inline virtual
 { return powerChanges; }
Referenced by inet::physicallayer::ScalarAnalogModelBase::addNoise().
printToStream()
std::ostream & inet::physicallayer::ScalarNoise::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::NarrowbandNoiseBase.
 {
     stream << "ScalarNoise";
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(powerChanges);
     return NarrowbandNoiseBase::printToStream(stream, level);
 }
Member Data Documentation
powerChanges
const std::map<simtime_t, W>* inet::physicallayer::ScalarNoise::powerChanges protected
Referenced by computeMaxPower(), computeMinPower(), and printToStream().
The documentation for this class was generated from the following files:
ScalarNoise.h
ScalarNoise.cc