INET Framework for OMNeT++/OMNEST: inet::ieee80211::StationRetryCounters Class Reference
inet::ieee80211::StationRetryCounters Class Reference
#include <StationRetryCounters.h>
Public Member Functions
int getStationLongRetryCount () const
int getStationShortRetryCount () const
void resetStationShortRetryCount ()
void resetStationLongRetryCount ()
void incrementStationShortRetryCount ()
void incrementStationLongRetryCount ()
Protected Attributes
int stationShortRetryCount = 0
int stationLongRetryCount = 0
Member Function Documentation
getStationLongRetryCount()
int inet::ieee80211::StationRetryCounters::getStationLongRetryCount () const inline
 { return stationLongRetryCount; }
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementStationLrc().
getStationShortRetryCount()
int inet::ieee80211::StationRetryCounters::getStationShortRetryCount () const inline
 { return stationShortRetryCount; }
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementStationSrc().
incrementStationLongRetryCount()
void inet::ieee80211::StationRetryCounters::incrementStationLongRetryCount () inline
 { stationLongRetryCount++; }
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementStationLrc().
incrementStationShortRetryCount()
void inet::ieee80211::StationRetryCounters::incrementStationShortRetryCount () inline
 { stationShortRetryCount++; }
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementStationSrc().
resetStationLongRetryCount()
void inet::ieee80211::StationRetryCounters::resetStationLongRetryCount () inline
 { stationLongRetryCount = 0; }
Referenced by inet::ieee80211::NonQosRecoveryProcedure::ackFrameReceived(), and inet::ieee80211::NonQosRecoveryProcedure::multicastFrameTransmitted().
resetStationShortRetryCount()
void inet::ieee80211::StationRetryCounters::resetStationShortRetryCount () inline
 { stationShortRetryCount = 0; }
Referenced by inet::ieee80211::NonQosRecoveryProcedure::ackFrameReceived(), inet::ieee80211::NonQosRecoveryProcedure::ctsFrameReceived(), and inet::ieee80211::NonQosRecoveryProcedure::multicastFrameTransmitted().
Member Data Documentation
stationLongRetryCount
int inet::ieee80211::StationRetryCounters::stationLongRetryCount = 0 protected
stationShortRetryCount
int inet::ieee80211::StationRetryCounters::stationShortRetryCount = 0 protected
The documentation for this class was generated from the following file:
StationRetryCounters.h