INET Framework for OMNeT++/OMNEST: inet::physicallayer::LayeredTransmission Class Reference
inet::physicallayer::LayeredTransmission Class Reference
#include <LayeredTransmission.h>
Public Member Functions
LayeredTransmission (const ITransmissionPacketModel *packetModel, const ITransmissionBitModel *bitModel, const ITransmissionSymbolModel *symbolModel, const ITransmissionSampleModel *sampleModel, const ITransmissionAnalogModel *analogModel, const IRadio *transmitter, const Packet *packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation)
virtual ~LayeredTransmission ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const ITransmissionPacketModel * getPacketModel () const
virtual const ITransmissionBitModel * getBitModel () const
virtual const ITransmissionSymbolModel * getSymbolModel () const
virtual const ITransmissionSampleModel * getSampleModel () const
virtual const ITransmissionAnalogModel * getAnalogModel () const override
Returns the analog model of the transmitted signal.
virtual const Packet * getPacket () const override
Returns the packet corresponding to this transmission.
Public Member Functions inherited from inet::physicallayer::TransmissionBase
TransmissionBase (const IRadio *transmitter, const Packet *packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation)
virtual int getId () const override
Returns an identifier for this transmission which is globally unique for the whole lifetime of the simulation among all transmissions.
virtual const IRadio * getTransmitter () const override
Returns the transmitter that transmitted this radio signal on the radio channel.
virtual int getTransmitterId () const override
Returns the transmitter's id that transmitted this radio signal on the radio channel.
virtual const IAntennaGain * getTransmitterAntennaGain () const override
Returns the gain of the transmitting antenna.
virtual const IRadioMedium * getMedium () const override
Returns the radio medium used for this transmission.
virtual const simtime_t getStartTime () const override
Returns the time when the transmitter started this transmission.
virtual const simtime_t getEndTime () const override
Returns the time when the transmitter ended this transmission.
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getPreambleStartTime () const override
virtual const simtime_t getPreambleEndTime () const override
virtual const simtime_t getHeaderStartTime () const override
virtual const simtime_t getHeaderEndTime () const override
virtual const simtime_t getDataStartTime () const override
virtual const simtime_t getDataEndTime () const override
virtual const simtime_t getDuration () const override
Returns the total length of this transmission.
virtual const simtime_t getDuration (IRadioSignal::SignalPart part) const override
Returns the length of the provided part of this transmission.
virtual const simtime_t getPreambleDuration () const override
Returns the length of the preamble part of this transmission.
virtual const simtime_t getHeaderDuration () const override
Returns the length of the header part of this transmission.
virtual const simtime_t getDataDuration () const override
Returns the length of the data part of this transmission.
virtual const Coord & getStartPosition () const override
Returns the antenna's position when the transmitter started this transmission.
virtual const Coord & getEndPosition () const override
Returns the antenna's position when the transmitter ended this transmission.
virtual const Quaternion & getStartOrientation () const override
Returns the antenna's orientation when the transmitter started this transmission.
virtual const Quaternion & getEndOrientation () const override
Returns the antenna's orientation when the transmitter ended this transmission.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const ITransmissionPacketModel * packetModel
const ITransmissionBitModel * bitModel
const ITransmissionSymbolModel * symbolModel
const ITransmissionSampleModel * sampleModel
const ITransmissionAnalogModel * analogModel
Protected Attributes inherited from inet::physicallayer::TransmissionBase
const int id
const IRadioMedium * radioMedium
const int transmitterId
Ptr< const IAntennaGain > transmitterGain
const Packet * packet
const simtime_t startTime
const simtime_t endTime
const simtime_t preambleDuration
const simtime_t headerDuration
const simtime_t dataDuration
const Coord startPosition
const Coord endPosition
const Quaternion startOrientation
const Quaternion endOrientation
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Protected Attributes inherited from inet::physicallayer::ITransmission
static int nextId = 0
Constructor & Destructor Documentation
LayeredTransmission()
inet::physicallayer::LayeredTransmission::LayeredTransmission (const ITransmissionPacketModel * packetModel, const ITransmissionBitModel * bitModel, const ITransmissionSymbolModel * symbolModel, const ITransmissionSampleModel * sampleModel, const ITransmissionAnalogModel * analogModel, const IRadio * transmitter, const Packet * packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord & startPosition, const Coord & endPosition, const Quaternion & startOrientation, const Quaternion & endOrientation)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    :
     TransmissionBase(transmitter, packet, startTime, endTime, preambleDuration, headerDuration, dataDuration, startPosition, endPosition, startOrientation, endOrientation),
     packetModel(packetModel),
     bitModel(bitModel),
     symbolModel(symbolModel),
     sampleModel(sampleModel),
     analogModel(analogModel)
 {
 }
~LayeredTransmission()
inet::physicallayer::LayeredTransmission::~LayeredTransmission () virtual
 {
     delete packetModel;
     delete bitModel;
     delete symbolModel;
     delete sampleModel;
     delete analogModel;
 }
Member Function Documentation
getAnalogModel()
virtual const ITransmissionAnalogModel* inet::physicallayer::LayeredTransmission::getAnalogModel () const inline override virtual
Returns the analog model of the transmitted signal.
Reimplemented from inet::physicallayer::TransmissionBase.
 { return analogModel; }
Referenced by inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::ApskLayeredErrorModel::computePacketModel(), inet::physicallayer::LayeredDimensionalAnalogModel::computeReception(), inet::physicallayer::LayeredScalarAnalogModel::computeReception(), and inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel().
getBitModel()
virtual const ITransmissionBitModel* inet::physicallayer::LayeredTransmission::getBitModel () const inline virtual
 { return bitModel; }
Referenced by inet::physicallayer::LayeredErrorModelBase::computeBitModel(), inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::ApskLayeredErrorModel::computePacketModel(), and inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel().
getPacket()
virtual const Packet* inet::physicallayer::LayeredTransmission::getPacket () const inline override virtual
Returns the packet corresponding to this transmission.
This function never returns nullptr.
Reimplemented from inet::physicallayer::TransmissionBase.
 { return packetModel->getPacket(); }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
getPacketModel()
virtual const ITransmissionPacketModel* inet::physicallayer::LayeredTransmission::getPacketModel () const inline virtual
 { return packetModel; }
Referenced by inet::physicallayer::LayeredErrorModelBase::computePacketModel(), inet::physicallayer::ApskLayeredErrorModel::computePacketModel(), and inet::physicallayer::Ieee80211OfdmErrorModel::computePacketModel().
getSampleModel()
virtual const ITransmissionSampleModel* inet::physicallayer::LayeredTransmission::getSampleModel () const inline virtual
 { return sampleModel; }
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::computeSampleModel().
getSymbolModel()
virtual const ITransmissionSymbolModel* inet::physicallayer::LayeredTransmission::getSymbolModel () const inline virtual
 { return symbolModel; }
Referenced by inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), inet::physicallayer::ApskLayeredErrorModel::computePacketModel(), inet::physicallayer::LayeredErrorModelBase::computeSymbolModel(), inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel(), and inet::physicallayer::Ieee80211OfdmErrorModel::computeSymbolModel().
printToStream()
std::ostream & inet::physicallayer::LayeredTransmission::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::TransmissionBase.
Reimplemented in inet::physicallayer::Ieee80211LayeredTransmission.
 {
     stream << "LayeredTransmission";
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(packetModel, printFieldToString(packetModel, level + 1, evFlags))
                << EV_FIELD(bitModel, printFieldToString(bitModel, level + 1, evFlags))
                << EV_FIELD(symbolModel, printFieldToString(symbolModel, level + 1, evFlags))
                << EV_FIELD(sampleModel, printFieldToString(sampleModel, level + 1, evFlags))
                << EV_FIELD(analogModel, printFieldToString(analogModel, level + 1, evFlags));
     return TransmissionBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::Ieee80211LayeredTransmission::printToStream().
Member Data Documentation
analogModel
const ITransmissionAnalogModel* inet::physicallayer::LayeredTransmission::analogModel protected
Referenced by printToStream(), and ~LayeredTransmission().
bitModel
const ITransmissionBitModel* inet::physicallayer::LayeredTransmission::bitModel protected
Referenced by printToStream(), and ~LayeredTransmission().
packetModel
const ITransmissionPacketModel* inet::physicallayer::LayeredTransmission::packetModel protected
Referenced by printToStream(), and ~LayeredTransmission().
sampleModel
const ITransmissionSampleModel* inet::physicallayer::LayeredTransmission::sampleModel protected
Referenced by printToStream(), and ~LayeredTransmission().
symbolModel
const ITransmissionSymbolModel* inet::physicallayer::LayeredTransmission::symbolModel protected
Referenced by printToStream(), and ~LayeredTransmission().
The documentation for this class was generated from the following files:
LayeredTransmission.h
LayeredTransmission.cc