INET Framework for OMNeT++/OMNEST: inet::sctp::SctpChunk Class Reference
inet::sctp::SctpChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:33 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual SctpChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:33 by opp_msgtool.
class SctpChunk extends cPacket
{
    @packetData;
    // Chunk Type
    uint8_t sctpChunkType;
    uint32_t flags;
    unsigned short length = 0;
    char chunkName[];
}
Constructor & Destructor Documentation
SctpChunk() [1/2]
inet::sctp::SctpChunk::SctpChunk (const char * name = nullptr)
SctpChunk() [2/2]
inet::sctp::SctpChunk::SctpChunk (const SctpChunk & other)
~SctpChunk()
virtual inet::sctp::SctpChunk::~SctpChunk () virtual
Member Function Documentation
appendChunkName()
virtual void inet::sctp::SctpChunk::appendChunkName (char chunkName) virtual
copy()
void inet::sctp::SctpChunk::copy (const SctpChunk & other) private
dup()
virtual SctpChunk* inet::sctp::SctpChunk::dup () const inline override virtual
Reimplemented in inet::sctp::SctpAsconfAckChunk_Base, inet::sctp::SctpAsconfChunk_Base, inet::sctp::SctpAuthenticationChunk, inet::sctp::SctpStreamResetChunk_Base, inet::sctp::SctpPacketDropChunk, inet::sctp::SctpErrorChunk_Base, inet::sctp::SctpShutdownCompleteChunk, inet::sctp::SctpShutdownAckChunk, inet::sctp::SctpShutdownChunk, inet::sctp::SctpHeartbeatAckChunk, inet::sctp::SctpHeartbeatChunk, inet::sctp::SctpAbortChunk, inet::sctp::SctpSackChunk, inet::sctp::SctpForwardTsnChunk, inet::sctp::SctpDataChunk, inet::sctp::SctpCookieAckChunk, inet::sctp::SctpCookieEchoChunk, inet::sctp::SctpInitAckChunk, inet::sctp::SctpInitChunk, inet::sctp::SctpAsconfAckChunk, inet::sctp::SctpAsconfChunk, inet::sctp::SctpStreamResetChunk, and inet::sctp::SctpErrorChunk.
 {return new SctpChunk(*this);}
eraseChunkName()
virtual void inet::sctp::SctpChunk::eraseChunkName (size_t k) virtual
getChunkName()
virtual char inet::sctp::SctpChunk::getChunkName (size_t k) const virtual
getChunkNameArraySize()
virtual size_t inet::sctp::SctpChunk::getChunkNameArraySize () const virtual
getFlags()
virtual uint32_t inet::sctp::SctpChunk::getFlags () const virtual
getLength()
virtual unsigned short inet::sctp::SctpChunk::getLength () const virtual
getSctpChunkType()
virtual uint8_t inet::sctp::SctpChunk::getSctpChunkType () const virtual
Referenced by inet::sctp::SctpAssociation::loadPacket(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::sendPacketDrop(), inet::sctp::SctpHeaderSerializer::serialize(), and inet::sctp::SctpAssociation::storePacket().
insertChunkName() [1/2]
void inet::sctp::SctpChunk::insertChunkName (char chunkName) inline
 {appendChunkName(chunkName);}
insertChunkName() [2/2]
virtual void inet::sctp::SctpChunk::insertChunkName (size_t k, char chunkName) virtual
operator=()
SctpChunk& inet::sctp::SctpChunk::operator= (const SctpChunk & other)
operator==()
bool inet::sctp::SctpChunk::operator== (const SctpChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::sctp::SctpAsconfAckChunk_Base, inet::sctp::SctpAsconfChunk_Base, inet::sctp::SctpAuthenticationChunk, inet::sctp::SctpStreamResetChunk_Base, inet::sctp::SctpPacketDropChunk, inet::sctp::SctpErrorChunk_Base, inet::sctp::SctpShutdownCompleteChunk, inet::sctp::SctpShutdownAckChunk, inet::sctp::SctpShutdownChunk, inet::sctp::SctpHeartbeatAckChunk, inet::sctp::SctpHeartbeatChunk, inet::sctp::SctpAbortChunk, inet::sctp::SctpSackChunk, inet::sctp::SctpForwardTsnChunk, inet::sctp::SctpDataChunk, inet::sctp::SctpCookieAckChunk, inet::sctp::SctpCookieEchoChunk, inet::sctp::SctpInitAckChunk, and inet::sctp::SctpInitChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::sctp::SctpAsconfAckChunk_Base, inet::sctp::SctpAsconfChunk_Base, inet::sctp::SctpAuthenticationChunk, inet::sctp::SctpStreamResetChunk_Base, inet::sctp::SctpPacketDropChunk, inet::sctp::SctpErrorChunk_Base, inet::sctp::SctpShutdownCompleteChunk, inet::sctp::SctpShutdownAckChunk, inet::sctp::SctpShutdownChunk, inet::sctp::SctpHeartbeatAckChunk, inet::sctp::SctpHeartbeatChunk, inet::sctp::SctpAbortChunk, inet::sctp::SctpSackChunk, inet::sctp::SctpForwardTsnChunk, inet::sctp::SctpDataChunk, inet::sctp::SctpCookieAckChunk, inet::sctp::SctpCookieEchoChunk, inet::sctp::SctpInitAckChunk, and inet::sctp::SctpInitChunk.
Referenced by inet::sctp::doParsimUnpacking().
setChunkName()
virtual void inet::sctp::SctpChunk::setChunkName (size_t k, char chunkName) virtual
setChunkNameArraySize()
virtual void inet::sctp::SctpChunk::setChunkNameArraySize (size_t size) virtual
setFlags()
virtual void inet::sctp::SctpChunk::setFlags (uint32_t flags) virtual
setLength()
virtual void inet::sctp::SctpChunk::setLength (unsigned short length) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setSctpChunkType()
virtual void inet::sctp::SctpChunk::setSctpChunkType (uint8_t sctpChunkType) virtual
Referenced by inet::sctp::SctpAssociation::createAsconfAckChunk(), inet::sctp::SctpAssociation::createAuthChunk(), inet::sctp::SctpAssociation::createForwardTsnChunk(), inet::sctp::SctpAssociation::createSack(), inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::retransmitAsconf(), inet::sctp::SctpAssociation::retransmitReset(), inet::sctp::SctpAssociation::sendAbort(), inet::sctp::Sctp::sendAbortFromMain(), inet::sctp::SctpAssociation::sendAddInAndOutStreamsRequest(), inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest(), inet::sctp::SctpAssociation::sendAsconf(), inet::sctp::SctpAssociation::sendAsconfAck(), inet::sctp::SctpNatHook::sendBackError(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendCookieAck(), inet::sctp::SctpAssociation::sendCookieEcho(), inet::sctp::SctpAssociation::sendDoubleStreamResetResponse(), inet::sctp::SctpAssociation::sendHeartbeat(), inet::sctp::SctpAssociation::sendHeartbeatAck(), inet::sctp::SctpAssociation::sendHMacError(), inet::sctp::SctpAssociation::sendInit(), inet::sctp::SctpAssociation::sendInitAck(), inet::sctp::SctpAssociation::sendInvalidStreamError(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), inet::sctp::SctpAssociation::sendPacketDrop(), inet::sctp::SctpAssociation::sendShutdown(), inet::sctp::SctpAssociation::sendShutdownAck(), inet::sctp::SctpAssociation::sendShutdownComplete(), inet::sctp::Sctp::sendShutdownCompleteFromMain(), inet::sctp::SctpAssociation::sendStreamResetRequest(), inet::sctp::SctpAssociation::sendStreamResetResponse(), and inet::sctp::SctpAssociation::transformDataChunk().
Member Data Documentation
chunkName
char* inet::sctp::SctpChunk::chunkName = nullptr protected
chunkName_arraysize
size_t inet::sctp::SctpChunk::chunkName_arraysize = 0 protected
flags
uint32_t inet::sctp::SctpChunk::flags = 0 protected
length
unsigned short inet::sctp::SctpChunk::length = 0 protected
sctpChunkType
uint8_t inet::sctp::SctpChunk::sctpChunkType = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h