INET Framework for OMNeT++/OMNEST: inet::ieee80211::ModeSetListener Class Reference
inet::ieee80211::ModeSetListener Class Reference
#include <ModeSetListener.h>
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Protected Attributes
physicallayer::Ieee80211ModeSet * modeSet = nullptr
Member Function Documentation
initialize()
void inet::ieee80211::ModeSetListener::initialize (int stage) override protected virtual
Reimplemented in inet::ieee80211::Hcf, inet::ieee80211::Dcf, inet::ieee80211::Edcaf, inet::ieee80211::QosRateSelection, inet::ieee80211::Dcaf, inet::ieee80211::TxopProcedure, inet::ieee80211::SingleProtectionMechanism, inet::ieee80211::AarfRateControl, inet::ieee80211::OnoeRateControl, inet::ieee80211::OriginatorBlockAckAgreementPolicy, inet::ieee80211::OriginatorQosAckPolicy, inet::ieee80211::QosRtsPolicy, inet::ieee80211::RtsPolicy, inet::ieee80211::RateControlBase, inet::ieee80211::CtsPolicy, inet::ieee80211::OriginatorAckPolicy, inet::ieee80211::QosCtsPolicy, inet::ieee80211::RecipientQosAckPolicy, inet::ieee80211::OriginatorProtectionMechanism, and inet::ieee80211::RecipientAckPolicy.
 {
     if (stage == INITSTAGE_LOCAL)
         getContainingNicModule(this)->subscribe(modesetChangedSignal, this);
 }
Referenced by inet::ieee80211::OriginatorProtectionMechanism::initialize(), inet::ieee80211::RecipientAckPolicy::initialize(), inet::ieee80211::QosCtsPolicy::initialize(), inet::ieee80211::OriginatorAckPolicy::initialize(), inet::ieee80211::RecipientQosAckPolicy::initialize(), inet::ieee80211::CtsPolicy::initialize(), inet::ieee80211::QosRtsPolicy::initialize(), inet::ieee80211::RateControlBase::initialize(), inet::ieee80211::RtsPolicy::initialize(), inet::ieee80211::OriginatorQosAckPolicy::initialize(), inet::ieee80211::OriginatorBlockAckAgreementPolicy::initialize(), inet::ieee80211::SingleProtectionMechanism::initialize(), inet::ieee80211::TxopProcedure::initialize(), inet::ieee80211::QosRateSelection::initialize(), inet::ieee80211::Dcf::initialize(), and inet::ieee80211::Hcf::initialize().
numInitStages()
virtual int inet::ieee80211::ModeSetListener::numInitStages () const inline override protected virtual
Reimplemented in inet::ieee80211::Hcf, inet::ieee80211::Dcf, inet::ieee80211::Edcaf, inet::ieee80211::QosRateSelection, inet::ieee80211::Dcaf, inet::ieee80211::TxopProcedure, inet::ieee80211::SingleProtectionMechanism, inet::ieee80211::AarfRateControl, inet::ieee80211::OnoeRateControl, inet::ieee80211::OriginatorBlockAckAgreementPolicy, inet::ieee80211::OriginatorQosAckPolicy, inet::ieee80211::QosRtsPolicy, inet::ieee80211::RtsPolicy, inet::ieee80211::RateControlBase, inet::ieee80211::CtsPolicy, inet::ieee80211::OriginatorAckPolicy, inet::ieee80211::QosCtsPolicy, inet::ieee80211::RecipientQosAckPolicy, inet::ieee80211::OriginatorProtectionMechanism, and inet::ieee80211::RecipientAckPolicy.
 { return NUM_INIT_STAGES; }
receiveSignal()
void inet::ieee80211::ModeSetListener::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
Reimplemented in inet::ieee80211::Edcaf, inet::ieee80211::QosRateSelection, inet::ieee80211::Dcaf, and inet::ieee80211::RateControlBase.
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     if (signalID == modesetChangedSignal)
         modeSet = check_and_cast<physicallayer::Ieee80211ModeSet *>(obj);
 }
Member Data Documentation
modeSet
physicallayer::Ieee80211ModeSet* inet::ieee80211::ModeSetListener::modeSet = nullptr protected
Referenced by inet::ieee80211::RecipientAckPolicy::computeAckDurationField(), inet::ieee80211::RecipientQosAckPolicy::computeAckDurationField(), inet::ieee80211::RecipientQosAckPolicy::computeBasicBlockAckDurationField(), inet::ieee80211::SingleProtectionMechanism::computeBlockAckReqDurationField(), inet::ieee80211::QosCtsPolicy::computeCtsDurationField(), inet::ieee80211::CtsPolicy::computeCtsDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField(), inet::ieee80211::OriginatorAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getAckTimeout(), inet::ieee80211::OriginatorQosAckPolicy::getBlockAckTimeout(), inet::ieee80211::QosRtsPolicy::getCtsTimeout(), inet::ieee80211::RtsPolicy::getCtsTimeout(), and receiveSignal().
The documentation for this class was generated from the following files:
ModeSetListener.h
ModeSetListener.cc