INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmDemodulator Class Reference
inet::physicallayer::Ieee80211OfdmDemodulator Class Reference
#include <Ieee80211OfdmDemodulator.h>
Public Member Functions
Ieee80211OfdmDemodulator (const Ieee80211OfdmModulation *subcarrierModulation)
const Ieee80211OfdmModulation * getModulation () const
virtual const IReceptionBitModel * demodulate (const IReceptionSymbolModel *symbolModel) const override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
BitVector demodulateSymbol (const Ieee80211OfdmSymbol *signalSymbol) const
const IReceptionBitModel * createBitModel (const BitVector *bitRepresentation, int signalFieldBitLength, bps signalFieldBitRate, int dataFieldBitLength, bps dataFieldBitRate) const
bool isPilotOrDcSubcarrier (int i) const
Protected Attributes
const Ieee80211OfdmModulation * subcarrierModulation = nullptr
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211OfdmDemodulator()
inet::physicallayer::Ieee80211OfdmDemodulator::Ieee80211OfdmDemodulator (const Ieee80211OfdmModulation * subcarrierModulation)
                                                                                                       :
     subcarrierModulation(subcarrierModulation)
 {
 }
Member Function Documentation
createBitModel()
const IReceptionBitModel * inet::physicallayer::Ieee80211OfdmDemodulator::createBitModel (const BitVector * bitRepresentation, int signalFieldBitLength, bps signalFieldBitRate, int dataFieldBitLength, bps dataFieldBitRate) const protected
 {
     return new ReceptionBitModel(b(signalFieldLength), signalFieldBitRate, b(dataFieldLength), dataFieldBitRate, bitRepresentation, NaN);
 }
Referenced by demodulate().
demodulate()
const IReceptionBitModel * inet::physicallayer::Ieee80211OfdmDemodulator::demodulate (const IReceptionSymbolModel * symbolModel) const override virtual
Implements inet::physicallayer::IDemodulator.
 {
     const std::vector<const ISymbol *> *symbols = symbolModel->getSymbols();
     BitVector *bitRepresentation = new BitVector();
     for (auto& symbols_i : *symbols) {
         const Ieee80211OfdmSymbol *symbol = dynamic_cast<const Ieee80211OfdmSymbol *>(symbols_i);
         BitVector bits = demodulateSymbol(symbol);
         for (unsigned int j = 0; j < bits.getSize(); j++)
             bitRepresentation->appendBit(bits.getBit(j));
     }
     return createBitModel(bitRepresentation, -1, bps(NaN), -1, bps(NaN)); // TODO
 }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldBitModel(), and inet::physicallayer::Ieee80211OfdmDemodulatorModule::demodulate().
demodulateSymbol()
BitVector inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol (const Ieee80211OfdmSymbol * signalSymbol) const protected
 {
     std::vector<const ApskSymbol *> apskSymbols = signalSymbol->getSubCarrierSymbols();
     const ApskModulationBase *demodulationScheme = subcarrierModulation->getSubcarrierModulation();
     BitVector field;
     for (unsigned int i = 0; i < apskSymbols.size(); i++) {
         if (!isPilotOrDcSubcarrier(i)) {
             const ApskSymbol *apskSymbol = apskSymbols.at(i);
             ShortBitVector bits = demodulationScheme->demapToBitRepresentation(apskSymbol);
             for (unsigned int j = 0; j < bits.getSize(); j++)
                 field.appendBit(bits.getBit(j));
         }
     }
     EV_DEBUG << "The field symbols has been demodulated into the following bit stream: " << field << endl;
     return field;
 }
Referenced by demodulate().
getModulation()
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmDemodulator::getModulation () const inline
 { return subcarrierModulation; }
Referenced by inet::physicallayer::Ieee80211OfdmDemodulatorModule::getModulation(), and inet::physicallayer::Ieee80211OfdmDemodulatorModule::~Ieee80211OfdmDemodulatorModule().
isPilotOrDcSubcarrier()
bool inet::physicallayer::Ieee80211OfdmDemodulator::isPilotOrDcSubcarrier (int i) const protected
 {
     return i == 5 || i == 19 || i == 33 || i == 47 || i == 26; // pilots are: 5,19,33,47, 26 (0+26) is a dc subcarrier
 }
Referenced by demodulateSymbol().
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmDemodulator::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Ieee80211OfdmDemodulator";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(subcarrierModulation, printFieldToString(subcarrierModulation, level + 1, evFlags));
     return stream;
 }
Referenced by inet::physicallayer::Ieee80211OfdmDemodulatorModule::printToStream().
Member Data Documentation
subcarrierModulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmDemodulator::subcarrierModulation = nullptr protected
Referenced by demodulateSymbol(), and printToStream().
The documentation for this class was generated from the following files:
Ieee80211OfdmDemodulator.h
Ieee80211OfdmDemodulator.cc