INET Framework for OMNeT++/OMNEST: inet::physicallayer::FlatReceiverBase Class Reference
inet::physicallayer::FlatReceiverBase Class Reference
#include <FlatReceiverBase.h>
Public Member Functions
FlatReceiverBase ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual W getMinReceptionPower () const override
Returns the minimum reception power below which successful reception is definitely not possible.
virtual const IListeningDecision * computeListeningDecision (const IListening *listening, const IInterference *interference) const override
Returns the result of the listening process specifying the reception state of the receiver.
virtual const IReceptionResult * computeReceptionResult (const IListening *listening, const IReception *reception, const IInterference *interference, const ISnir *snir, const std::vector< const IReceptionDecision * > *decisions) const override
Returns the complete result of the reception process for the provided reception.
virtual const IErrorModel * getErrorModel () const
virtual W getEnergyDetection () const
virtual void setEnergyDetection (W energyDetection)
virtual W getSensitivity () const
virtual void setSensitivity (W sensitivity)
Public Member Functions inherited from inet::physicallayer::NarrowbandReceiverBase
NarrowbandReceiverBase ()
virtual const IListening * createListening (const IRadio *radio, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition) const override
Returns a description of how the receiver is listening on the medium.
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const override
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
virtual const IReceptionDecision * computeReceptionDecision (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
virtual const IModulation * getModulation () const
virtual void setModulation (const IModulation *modulation)
virtual Hz getCenterFrequency () const
virtual void setCenterFrequency (Hz centerFrequency)
virtual Hz getBandwidth () const
virtual void setBandwidth (Hz bandwidth)
Public Member Functions inherited from inet::physicallayer::SnirReceiverBase
virtual double getSNIRThreshold () const
Public Member Functions inherited from inet::physicallayer::ReceiverBase
ReceiverBase ()
virtual W getMinInterferencePower () const override
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
virtual bool computeIsReceptionAttempted (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference) const override
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const override
Returns whether the reception of the provided part is possible or not.
virtual bool computeIsReceptionSuccessful (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns whether the reception of the provided part is actually successful or failed by the receiver.
virtual Packet * computeReceivedPacket (const ISnir *snir, bool isReceptionSuccessful) const override
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const override
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const override
Protected Member Functions inherited from inet::physicallayer::ReceiverBase
virtual int numInitStages () const override
virtual W computeSignalPower (const IListening *listening, const ISnir *snir, const IInterference *interference) const
Protected Attributes
const IErrorModel * errorModel
W energyDetection
W sensitivity
Protected Attributes inherited from inet::physicallayer::NarrowbandReceiverBase
const IModulation * modulation
Hz centerFrequency
Hz bandwidth
Protected Attributes inherited from inet::physicallayer::SnirReceiverBase
double snirThreshold = NaN
SnirThresholdMode snirThresholdMode = SnirThresholdMode::STM_UNDEFINED
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Types inherited from inet::physicallayer::SnirReceiverBase
enum SnirThresholdMode { SnirThresholdMode::STM_UNDEFINED = -1, SnirThresholdMode::STM_MIN, SnirThresholdMode::STM_MEAN }
Constructor & Destructor Documentation
FlatReceiverBase()
inet::physicallayer::FlatReceiverBase::FlatReceiverBase ()
                                    :
     NarrowbandReceiverBase(),
     errorModel(nullptr),
     energyDetection(W(NaN)),
     sensitivity(W(NaN))
 {
 }
Member Function Documentation
computeIsReceptionPossible() [1/3]
bool inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible override protected
 {
     const BandListening *bandListening = check_and_cast<const BandListening *>(listening);
     const NarrowbandReceptionBase *narrowbandReception = check_and_cast<const NarrowbandReceptionBase *>(reception);
     if (bandListening->getCenterFrequency() != narrowbandReception->getCenterFrequency() || bandListening->getBandwidth() < narrowbandReception->getBandwidth()) {
         EV_DEBUG << "Computing whether reception is possible: listening and reception bands are different -> reception is impossible" << endl;
         return false;
     }
     else
         return true;
 }
computeIsReceptionPossible() [2/3]
bool inet::physicallayer::FlatReceiverBase::computeIsReceptionPossible (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part) const override protected virtual
Returns whether the reception of the provided part is possible or not.
For example, it might check if the reception power is above sensitivity.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::NarrowbandReceiverBase.
Reimplemented in inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
 {
     if (!NarrowbandReceiverBase::computeIsReceptionPossible(listening, reception, part))
         return false;
     else {
         const FlatReceptionBase *flatReception = check_and_cast<const FlatReceptionBase *>(reception);
         W minReceptionPower = flatReception->computeMinPower(reception->getStartTime(part), reception->getEndTime(part));
         ASSERT(W(0.0) <= minReceptionPower);
         bool isReceptionPossible = minReceptionPower >= sensitivity;
         EV_DEBUG << "Computing whether reception is possible" << EV_FIELD(minReceptionPower) << EV_FIELD(sensitivity) << " -> reception is " << (isReceptionPossible ? "possible" : "impossible") << endl;
         return isReceptionPossible;
     }
 }
Referenced by inet::physicallayer::Ieee80211DimensionalReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211ScalarReceiver::computeIsReceptionPossible(), inet::physicallayer::ApskDimensionalReceiver::computeIsReceptionPossible(), and inet::physicallayer::ApskScalarReceiver::computeIsReceptionPossible().
computeIsReceptionPossible() [3/3]
bool inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible override protected
 {
     // TODO check if modulation matches?
     const NarrowbandTransmissionBase *narrowbandTransmission = check_and_cast<const NarrowbandTransmissionBase *>(transmission);
     return centerFrequency == narrowbandTransmission->getCenterFrequency() && bandwidth >= narrowbandTransmission->getBandwidth();
 }
computeIsReceptionSuccessful()
bool inet::physicallayer::FlatReceiverBase::computeIsReceptionSuccessful (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const override protected virtual
Returns whether the reception of the provided part is actually successful or failed by the receiver.
For example, it might compute the error rate and draw a random number to make the decision.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::SnirReceiverBase.
 {
     if (!SnirReceiverBase::computeIsReceptionSuccessful(listening, reception, part, interference, snir))
         return false;
     else if (!errorModel)
         return true;
     else {
         double packetErrorRate = errorModel->computePacketErrorRate(snir, part);
         if (packetErrorRate == 0.0)
             return true;
         else if (packetErrorRate == 1.0)
             return false;
         else {
             ASSERT(0.0 < packetErrorRate && packetErrorRate <= 1.0);
             return dblrand() > packetErrorRate;
         }
     }
 }
computeListeningDecision()
const IListeningDecision * inet::physicallayer::FlatReceiverBase::computeListeningDecision (const IListening * listening, const IInterference * interference) const override virtual
Returns the result of the listening process specifying the reception state of the receiver.
This function must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
 {
     const IRadio *receiver = listening->getReceiver();
     const IRadioMedium *radioMedium = receiver->getMedium();
     const IAnalogModel *analogModel = radioMedium->getAnalogModel();
     const INoise *noise = analogModel->computeNoise(listening, interference);
     const NarrowbandNoiseBase *narrowbandNoise = check_and_cast<const NarrowbandNoiseBase *>(noise);
     W maxPower = narrowbandNoise->computeMaxPower(listening->getStartTime(), listening->getEndTime());
     bool isListeningPossible = maxPower >= energyDetection;
     delete noise;
     EV_DEBUG << "Computing whether listening is possible: maximum power = " << maxPower << ", energy detection = " << energyDetection << " -> listening is " << (isListeningPossible ? "possible" : "impossible") << endl;
     return new ListeningDecision(listening, isListeningPossible);
 }
computeReceivedPacket()
Packet * inet::physicallayer::FlatReceiverBase::computeReceivedPacket (const ISnir * snir, bool isReceptionSuccessful) const override protected virtual
Reimplemented from inet::physicallayer::ReceiverBase.
 {
     if (errorModel == nullptr || isReceptionSuccessful)
         return ReceiverBase::computeReceivedPacket(snir, isReceptionSuccessful);
     else
         return errorModel->computeCorruptedPacket(snir);
 }
computeReceptionResult()
const IReceptionResult * inet::physicallayer::FlatReceiverBase::computeReceptionResult (const IListening * listening, const IReception * reception, const IInterference * interference, const ISnir * snir, const std::vector< const IReceptionDecision * > * decisions) const override virtual
Returns the complete result of the reception process for the provided reception.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::ReceiverBase.
Reimplemented in inet::physicallayer::Ieee80211ReceiverBase.
 {
     auto receptionResult = NarrowbandReceiverBase::computeReceptionResult(listening, reception, interference, snir, decisions);
     auto errorRateInd = const_cast<Packet *>(receptionResult->getPacket())->addTagIfAbsent<ErrorRateInd>();
     errorRateInd->setPacketErrorRate(errorModel ? errorModel->computePacketErrorRate(snir, IRadioSignal::SIGNAL_PART_WHOLE) : 0.0);
     errorRateInd->setBitErrorRate(errorModel ? errorModel->computeBitErrorRate(snir, IRadioSignal::SIGNAL_PART_WHOLE) : 0.0);
     errorRateInd->setSymbolErrorRate(errorModel ? errorModel->computeSymbolErrorRate(snir, IRadioSignal::SIGNAL_PART_WHOLE) : 0.0);
     return receptionResult;
 }
Referenced by inet::physicallayer::Ieee80211ReceiverBase::computeReceptionResult().
getEnergyDetection()
virtual W inet::physicallayer::FlatReceiverBase::getEnergyDetection () const inline virtual
 { return energyDetection; }
getErrorModel()
virtual const IErrorModel* inet::physicallayer::FlatReceiverBase::getErrorModel () const inline virtual
 { return errorModel; }
getMinReceptionPower()
virtual W inet::physicallayer::FlatReceiverBase::getMinReceptionPower () const inline override virtual
Returns the minimum reception power below which successful reception is definitely not possible.
Returns a value in the range [0, +infinity) or NaN if unspecified.
Reimplemented from inet::physicallayer::ReceiverBase.
 { return sensitivity; }
getSensitivity()
virtual W inet::physicallayer::FlatReceiverBase::getSensitivity () const inline virtual
 { return sensitivity; }
initialize()
void inet::physicallayer::FlatReceiverBase::initialize (int stage) override protected virtual
Reimplemented from inet::physicallayer::NarrowbandReceiverBase.
Reimplemented in inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 {
     NarrowbandReceiverBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         errorModel = dynamic_cast<IErrorModel *>(getSubmodule("errorModel"));
         energyDetection = mW(math::dBmW2mW(par("energyDetection")));
         sensitivity = mW(math::dBmW2mW(par("sensitivity")));
     }
 }
Referenced by inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver::initialize(), inet::physicallayer::Ieee802154NarrowbandScalarReceiver::initialize(), and inet::physicallayer::Ieee80211ReceiverBase::initialize().
printToStream()
std::ostream & inet::physicallayer::FlatReceiverBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::NarrowbandReceiverBase.
Reimplemented in inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, inet::physicallayer::Ieee80211ScalarReceiver, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(errorModel, printFieldToString(errorModel, level + 1, evFlags));
     if (level <= PRINT_LEVEL_INFO)
         stream << EV_FIELD(energyDetection)
                << EV_FIELD(sensitivity);
     return NarrowbandReceiverBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::ApskDimensionalReceiver::printToStream(), inet::physicallayer::Ieee802154NarrowbandScalarReceiver::printToStream(), inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver::printToStream(), inet::physicallayer::ApskScalarReceiver::printToStream(), and inet::physicallayer::Ieee80211ReceiverBase::printToStream().
setEnergyDetection()
virtual void inet::physicallayer::FlatReceiverBase::setEnergyDetection (W energyDetection) inline virtual
 { this->energyDetection = energyDetection; }
setSensitivity()
virtual void inet::physicallayer::FlatReceiverBase::setSensitivity (W sensitivity) inline virtual
 { this->sensitivity = sensitivity; }
Member Data Documentation
energyDetection
W inet::physicallayer::FlatReceiverBase::energyDetection protected
Referenced by computeListeningDecision(), initialize(), and printToStream().
errorModel
const IErrorModel* inet::physicallayer::FlatReceiverBase::errorModel protected
Referenced by computeIsReceptionSuccessful(), computeReceivedPacket(), computeReceptionResult(), initialize(), and printToStream().
sensitivity
W inet::physicallayer::FlatReceiverBase::sensitivity protected
Referenced by computeIsReceptionPossible(), initialize(), and printToStream().
The documentation for this class was generated from the following files:
FlatReceiverBase.h
FlatReceiverBase.cc