INET Framework for OMNeT++/OMNEST: inet::ieee80211::FrameSequenceHandler Class Reference
inet::ieee80211::FrameSequenceHandler Class Reference
#include <FrameSequenceHandler.h>
Public Member Functions
virtual const FrameSequenceContext * getContext () const override
virtual const IFrameSequence * getFrameSequence () const override
virtual void startFrameSequence (IFrameSequence *frameSequence, FrameSequenceContext *context, IFrameSequenceHandler::ICallback *callback) override
virtual void processResponse (Packet *frame) override
virtual void transmissionComplete () override
virtual void handleStartRxTimeout () override
virtual bool isSequenceRunning () override
virtual ~FrameSequenceHandler ()
Public Member Functions inherited from inet::ieee80211::IFrameSequenceHandler
virtual ~IFrameSequenceHandler ()
Protected Member Functions
virtual void startFrameSequenceStep ()
virtual void finishFrameSequenceStep ()
virtual void finishFrameSequence ()
virtual void abortFrameSequence ()
Protected Attributes
IFrameSequenceHandler::ICallback * callback = nullptr
IFrameSequence * frameSequence = nullptr
FrameSequenceContext * context = nullptr
Additional Inherited Members
Static Public Attributes inherited from inet::ieee80211::IFrameSequenceHandler
static simsignal_t frameSequenceStartedSignal = cComponent::registerSignal("frameSequenceStarted")
static simsignal_t frameSequenceFinishedSignal = cComponent::registerSignal("frameSequenceFinished")
Constructor & Destructor Documentation
~FrameSequenceHandler()
inet::ieee80211::FrameSequenceHandler::~FrameSequenceHandler () virtual
 {
     delete frameSequence;
     delete context;
 }
Member Function Documentation
abortFrameSequence()
void inet::ieee80211::FrameSequenceHandler::abortFrameSequence () protected virtual
 {
     EV_INFO << "Frame sequence aborted.\n";
     auto inProgressFrames = context->getInProgressFrames();
     auto step = context->getLastStep();
     auto failedTxStep = check_and_cast<ITransmitStep *>(dynamic_cast<IReceiveStep *>(step) ? context->getStepBeforeLast() : step);
     auto frameToTransmit = failedTxStep->getFrameToTransmit();
     auto header = frameToTransmit->peekAtFront<Ieee80211MacHeader>();
     if (auto dataOrMgmtHeader = dynamicPtrCast<const Ieee80211DataOrMgmtHeader>(header))
         callback->originatorProcessFailedFrame(frameToTransmit);
     else if (auto rtsTxStep = dynamic_cast<RtsTransmitStep *>(failedTxStep))
         callback->originatorProcessRtsProtectionFailed(const_cast<Packet *>(rtsTxStep->getProtectedFrame()));
     else if (auto blockAckReq = dynamicPtrCast<const Ieee80211BlockAckReq>(header))
         callback->originatorProcessFailedFrame(frameToTransmit);
     callback->frameSequenceFinished();
     delete context;
     delete frameSequence;
     context = nullptr;
     frameSequence = nullptr;
     callback = nullptr;
     inProgressFrames->clearDroppedFrames();
 }
Referenced by finishFrameSequenceStep(), and handleStartRxTimeout().
finishFrameSequence()
void inet::ieee80211::FrameSequenceHandler::finishFrameSequence () protected virtual
 {
     EV_INFO << "Frame sequence finished.\n";
     auto inProgressFrames = context->getInProgressFrames();
     callback->frameSequenceFinished();
     delete context;
     delete frameSequence;
     context = nullptr;
     frameSequence = nullptr;
     callback = nullptr;
     inProgressFrames->clearDroppedFrames();
 }
Referenced by startFrameSequenceStep().
finishFrameSequenceStep()
void inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep () protected virtual
 {
     ASSERT(isSequenceRunning());
     auto lastStep = context->getLastStep();
     auto stepResult = frameSequence->completeStep(context);
     EV_INFO << "Finishing last frame sequence step: history = " << frameSequence->getHistory() << "\n";
     if (!stepResult) {
         lastStep->setCompletion(IFrameSequenceStep::Completion::REJECTED);
         abortFrameSequence();
     }
     else {
         lastStep->setCompletion(IFrameSequenceStep::Completion::ACCEPTED);
         switch (lastStep->getType()) {
             case IFrameSequenceStep::Type::TRANSMIT: {
                 auto transmitStep = static_cast<ITransmitStep *>(lastStep);
                 callback->originatorProcessTransmittedFrame(transmitStep->getFrameToTransmit());
                 break;
             }
             case IFrameSequenceStep::Type::RECEIVE: {
                 auto receiveStep = static_cast<IReceiveStep *>(lastStep);
                 auto transmitStep = check_and_cast<ITransmitStep *>(context->getStepBeforeLast());
                 callback->originatorProcessReceivedFrame(receiveStep->getReceivedFrame(), transmitStep->getFrameToTransmit());
                 break;
             }
             default:
                 throw cRuntimeError("Unknown frame sequence step type");
         }
     }
 }
Referenced by processResponse(), and transmissionComplete().
getContext()
virtual const FrameSequenceContext* inet::ieee80211::FrameSequenceHandler::getContext () const inline override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 { return context; }
getFrameSequence()
virtual const IFrameSequence* inet::ieee80211::FrameSequenceHandler::getFrameSequence () const inline override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 { return frameSequence; }
handleStartRxTimeout()
void inet::ieee80211::FrameSequenceHandler::handleStartRxTimeout () override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 {
     auto lastStep = context->getLastStep();
     switch (lastStep->getType()) {
         case IFrameSequenceStep::Type::RECEIVE:
             abortFrameSequence();
             break;
         case IFrameSequenceStep::Type::TRANSMIT:
             throw cRuntimeError("Received timeout while in transmit step");
         default:
             throw cRuntimeError("Unknown step type");
     }
 }
isSequenceRunning()
virtual bool inet::ieee80211::FrameSequenceHandler::isSequenceRunning () inline override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 { return frameSequence != nullptr; }
Referenced by finishFrameSequenceStep(), processResponse(), startFrameSequence(), startFrameSequenceStep(), and transmissionComplete().
processResponse()
void inet::ieee80211::FrameSequenceHandler::processResponse (Packet * frame) override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 {
     ASSERT(callback != nullptr);
     auto lastStep = context->getLastStep();
     switch (lastStep->getType()) {
         case IFrameSequenceStep::Type::RECEIVE: {
             // TODO check if not for us and abort
             auto receiveStep = check_and_cast<IReceiveStep *>(context->getLastStep());
             receiveStep->setFrameToReceive(frame);
             finishFrameSequenceStep();
             if (isSequenceRunning())
                 startFrameSequenceStep();
             break;
         }
         case IFrameSequenceStep::Type::TRANSMIT:
             throw cRuntimeError("Received frame while current step is transmit");
         default:
             throw cRuntimeError("Unknown step type");
     }
 }
startFrameSequence()
void inet::ieee80211::FrameSequenceHandler::startFrameSequence (IFrameSequence * frameSequence, FrameSequenceContext * context, IFrameSequenceHandler::ICallback * callback) override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 {
     EV_INFO << "Starting frame sequence.\n";
     this->callback = callback;
     if (!isSequenceRunning()) {
         this->frameSequence = frameSequence;
         this->context = context;
         frameSequence->startSequence(context, 0);
         startFrameSequenceStep();
     }
     else
         throw cRuntimeError("Channel access granted while a frame sequence is running");
 }
startFrameSequenceStep()
void inet::ieee80211::FrameSequenceHandler::startFrameSequenceStep () protected virtual
 {
     ASSERT(isSequenceRunning());
     auto nextStep = frameSequence->prepareStep(context);
     EV_INFO << "Starting next frame sequence step: history = " << frameSequence->getHistory() << "\n";
     if (nextStep == nullptr)
         finishFrameSequence();
     else {
         context->addStep(nextStep);
         switch (nextStep->getType()) {
             case IFrameSequenceStep::Type::TRANSMIT: {
                 auto transmitStep = static_cast<TransmitStep *>(nextStep);
                 EV_INFO << "Transmitting, frame = " << transmitStep->getFrameToTransmit() << ".\n";
                 callback->transmitFrame(transmitStep->getFrameToTransmit(), transmitStep->getIfs());
                 // TODO lifetime
 //                if (auto dataFrame = dynamic_cast<const Ptr<const Ieee80211DataHeader>& >(transmitStep->getFrameToTransmit()))
 //                    transmitLifetimeHandler->frameTransmitted(dataFrame);
                 break;
             }
             case IFrameSequenceStep::Type::RECEIVE: {
                 // start reception timer, break loop if timer expires before reception is over
                 auto receiveStep = static_cast<IReceiveStep *>(nextStep);
                 callback->scheduleStartRxTimer(receiveStep->getTimeout());
                 break;
             }
             default:
                 throw cRuntimeError("Unknown frame sequence step type");
         }
     }
 }
Referenced by processResponse(), startFrameSequence(), and transmissionComplete().
transmissionComplete()
void inet::ieee80211::FrameSequenceHandler::transmissionComplete () override virtual
Implements inet::ieee80211::IFrameSequenceHandler.
 {
     if (isSequenceRunning()) {
         finishFrameSequenceStep();
         if (isSequenceRunning())
             startFrameSequenceStep();
     }
 }
Member Data Documentation
callback
IFrameSequenceHandler::ICallback* inet::ieee80211::FrameSequenceHandler::callback = nullptr protected
Referenced by abortFrameSequence(), finishFrameSequence(), finishFrameSequenceStep(), processResponse(), startFrameSequence(), and startFrameSequenceStep().
context
FrameSequenceContext* inet::ieee80211::FrameSequenceHandler::context = nullptr protected
Referenced by abortFrameSequence(), finishFrameSequence(), finishFrameSequenceStep(), handleStartRxTimeout(), processResponse(), startFrameSequence(), startFrameSequenceStep(), and ~FrameSequenceHandler().
frameSequence
IFrameSequence* inet::ieee80211::FrameSequenceHandler::frameSequence = nullptr protected
Referenced by abortFrameSequence(), finishFrameSequence(), finishFrameSequenceStep(), startFrameSequence(), startFrameSequenceStep(), and ~FrameSequenceHandler().
The documentation for this class was generated from the following files:
FrameSequenceHandler.h
FrameSequenceHandler.cc