INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2DatabaseDescriptionPacket Class Reference
inet::ospfv2::Ospfv2DatabaseDescriptionPacket Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:220 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2DatabaseDescriptionPacket ()
Ospfv2DatabaseDescriptionPacket (const Ospfv2DatabaseDescriptionPacket &other)
virtual ~Ospfv2DatabaseDescriptionPacket ()
Ospfv2DatabaseDescriptionPacket & operator= (const Ospfv2DatabaseDescriptionPacket &other)
virtual Ospfv2DatabaseDescriptionPacket * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getInterfaceMTU () const
virtual void setInterfaceMTU (unsigned short interfaceMTU)
virtual const Ospfv2Options & getOptions () const
virtual Ospfv2Options & getOptionsForUpdate ()
virtual void setOptions (const Ospfv2Options &options)
virtual const Ospfv2DdOptions & getDdOptions () const
virtual Ospfv2DdOptions & getDdOptionsForUpdate ()
virtual void setDdOptions (const Ospfv2DdOptions &ddOptions)
virtual unsigned long getDdSequenceNumber () const
virtual void setDdSequenceNumber (unsigned long ddSequenceNumber)
virtual void setLsaHeadersArraySize (size_t size)
virtual size_t getLsaHeadersArraySize () const
virtual const Ospfv2LsaHeader & getLsaHeaders (size_t k) const
virtual Ospfv2LsaHeader & getLsaHeadersForUpdate (size_t k)
virtual void setLsaHeaders (size_t k, const Ospfv2LsaHeader &lsaHeaders)
virtual void insertLsaHeaders (size_t k, const Ospfv2LsaHeader &lsaHeaders)
void insertLsaHeaders (const Ospfv2LsaHeader &lsaHeaders)
virtual void appendLsaHeaders (const Ospfv2LsaHeader &lsaHeaders)
virtual void eraseLsaHeaders (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Packet
Ospfv2Packet ()
Ospfv2Packet (const Ospfv2Packet &other)
virtual ~Ospfv2Packet ()
Ospfv2Packet & operator= (const Ospfv2Packet &other)
virtual short getAuthenticationType () const
virtual void setAuthenticationType (short authenticationType)
virtual size_t getAuthenticationArraySize () const
virtual char getAuthentication (size_t k) const
virtual void setAuthentication (size_t k, char authentication)
Public Member Functions inherited from inet::ospf::OspfPacketBase
OspfPacketBase ()
OspfPacketBase (const OspfPacketBase &other)
virtual ~OspfPacketBase ()
OspfPacketBase & operator= (const OspfPacketBase &other)
virtual short getVersion () const
virtual void setVersion (short version)
virtual OspfPacketType getType () const
virtual void setType (OspfPacketType type)
virtual int getPacketLengthField () const
virtual void setPacketLengthField (int packetLengthField)
virtual const ::inet::Ipv4Address & getRouterID () const
virtual ::inet::Ipv4Address & getRouterIDForUpdate ()
virtual void setRouterID (const ::inet::Ipv4Address &routerID)
virtual const ::inet::Ipv4Address & getAreaID () const
virtual ::inet::Ipv4Address & getAreaIDForUpdate ()
virtual void setAreaID (const ::inet::Ipv4Address &areaID)
virtual uint16_t getCrc () const
virtual void setCrc (uint16_t crc)
virtual ::inet::CrcMode getCrcMode () const
virtual void setCrcMode (::inet::CrcMode crcMode)
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ospfv2DatabaseDescriptionPacket &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Packet
bool operator== (const Ospfv2Packet &)=delete
Protected Member Functions inherited from inet::ospf::OspfPacketBase
bool operator== (const OspfPacketBase &)=delete
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Protected Attributes
unsigned short interfaceMTU = 0
Ospfv2Options options
Ospfv2DdOptions ddOptions
unsigned long ddSequenceNumber = 0
Ospfv2LsaHeader * lsaHeaders = nullptr
size_t lsaHeaders_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Packet
short authenticationType = 0
char authentication [8] = {0}
Protected Attributes inherited from inet::ospf::OspfPacketBase
short version = -1
OspfPacketType type = static_cast<OspfPacketType>(-1)
int packetLengthField = 0
::inet::Ipv4Address routerID
::inet::Ipv4Address areaID
uint16_t crc = 0
::inet::CrcMode crcMode = CRC_MODE_UNDEFINED
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const Ospfv2DatabaseDescriptionPacket &other)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:220 by opp_msgtool.
//
// Represents an OSPF Database Description packet
//
class Ospfv2DatabaseDescriptionPacket extends Ospfv2Packet
{
    unsigned short interfaceMTU;
    Ospfv2Options options;
    Ospfv2DdOptions ddOptions;
    unsigned long ddSequenceNumber;
    Ospfv2LsaHeader lsaHeaders[];     //TODO
}
Constructor & Destructor Documentation
Ospfv2DatabaseDescriptionPacket() [1/2]
inet::ospfv2::Ospfv2DatabaseDescriptionPacket::Ospfv2DatabaseDescriptionPacket ()
Ospfv2DatabaseDescriptionPacket() [2/2]
inet::ospfv2::Ospfv2DatabaseDescriptionPacket::Ospfv2DatabaseDescriptionPacket (const Ospfv2DatabaseDescriptionPacket & other)
~Ospfv2DatabaseDescriptionPacket()
virtual inet::ospfv2::Ospfv2DatabaseDescriptionPacket::~Ospfv2DatabaseDescriptionPacket () virtual
Member Function Documentation
appendLsaHeaders()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::appendLsaHeaders (const Ospfv2LsaHeader & lsaHeaders) virtual
copy()
void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::copy (const Ospfv2DatabaseDescriptionPacket & other) private
dup()
virtual Ospfv2DatabaseDescriptionPacket* inet::ospfv2::Ospfv2DatabaseDescriptionPacket::dup () const inline override virtual
Reimplemented from inet::ospfv2::Ospfv2Packet.
 {return new Ospfv2DatabaseDescriptionPacket(*this);}
eraseLsaHeaders()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::eraseLsaHeaders (size_t k) virtual
getDdOptions()
virtual const Ospfv2DdOptions& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getDdOptions () const virtual
Referenced by inet::ospfv2::MessageHandler::printDatabaseDescriptionPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processDDPacket().
getDdOptionsForUpdate()
virtual Ospfv2DdOptions& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getDdOptionsForUpdate () inline virtual
 { handleChange();return const_cast<Ospfv2DdOptions&>(const_cast<Ospfv2DatabaseDescriptionPacket*>(this)->getDdOptions());}
getDdSequenceNumber()
virtual unsigned long inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getDdSequenceNumber () const virtual
Referenced by inet::ospfv2::MessageHandler::printDatabaseDescriptionPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processDDPacket().
getInterfaceMTU()
virtual unsigned short inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getInterfaceMTU () const virtual
getLsaHeaders()
virtual const Ospfv2LsaHeader& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getLsaHeaders (size_t k) const virtual
Referenced by inet::ospfv2::MessageHandler::printDatabaseDescriptionPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processDDPacket().
getLsaHeadersArraySize()
virtual size_t inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getLsaHeadersArraySize () const virtual
Referenced by inet::ospfv2::MessageHandler::printDatabaseDescriptionPacket(), and inet::ospfv2::DatabaseDescriptionHandler::processDDPacket().
getLsaHeadersForUpdate()
virtual Ospfv2LsaHeader& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getLsaHeadersForUpdate (size_t k) inline virtual
 { handleChange();return const_cast<Ospfv2LsaHeader&>(const_cast<Ospfv2DatabaseDescriptionPacket*>(this)->getLsaHeaders(k));}
getOptions()
virtual const Ospfv2Options& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getOptions () const virtual
getOptionsForUpdate()
virtual Ospfv2Options& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getOptionsForUpdate () inline virtual
 { handleChange();return const_cast<Ospfv2Options&>(const_cast<Ospfv2DatabaseDescriptionPacket*>(this)->getOptions());}
insertLsaHeaders() [1/2]
void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::insertLsaHeaders (const Ospfv2LsaHeader & lsaHeaders) inline
 {appendLsaHeaders(lsaHeaders);}
insertLsaHeaders() [2/2]
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::insertLsaHeaders (size_t k, const Ospfv2LsaHeader & lsaHeaders) virtual
operator=()
Ospfv2DatabaseDescriptionPacket& inet::ospfv2::Ospfv2DatabaseDescriptionPacket::operator= (const Ospfv2DatabaseDescriptionPacket & other)
operator==()
bool inet::ospfv2::Ospfv2DatabaseDescriptionPacket::operator== (const Ospfv2DatabaseDescriptionPacket &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv2::Ospfv2Packet.
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv2::Ospfv2Packet.
Referenced by inet::ospfv2::doParsimUnpacking().
setDdOptions()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::setDdOptions (const Ospfv2DdOptions & ddOptions) virtual
setDdSequenceNumber()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::setDdSequenceNumber (unsigned long ddSequenceNumber) virtual
setInterfaceMTU()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::setInterfaceMTU (unsigned short interfaceMTU) virtual
setLsaHeaders()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::setLsaHeaders (size_t k, const Ospfv2LsaHeader & lsaHeaders) virtual
setLsaHeadersArraySize()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::setLsaHeadersArraySize (size_t size) virtual
setOptions()
virtual void inet::ospfv2::Ospfv2DatabaseDescriptionPacket::setOptions (const Ospfv2Options & options) virtual
Member Data Documentation
ddOptions
Ospfv2DdOptions inet::ospfv2::Ospfv2DatabaseDescriptionPacket::ddOptions protected
ddSequenceNumber
unsigned long inet::ospfv2::Ospfv2DatabaseDescriptionPacket::ddSequenceNumber = 0 protected
interfaceMTU
unsigned short inet::ospfv2::Ospfv2DatabaseDescriptionPacket::interfaceMTU = 0 protected
lsaHeaders
Ospfv2LsaHeader* inet::ospfv2::Ospfv2DatabaseDescriptionPacket::lsaHeaders = nullptr protected
lsaHeaders_arraysize
size_t inet::ospfv2::Ospfv2DatabaseDescriptionPacket::lsaHeaders_arraysize = 0 protected
options
Ospfv2Options inet::ospfv2::Ospfv2DatabaseDescriptionPacket::options protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h