INET Framework for OMNeT++/OMNEST: inet::visualizer::TransportConnectionCanvasVisualizer Class Reference
inet::visualizer::TransportConnectionCanvasVisualizer Class Reference
#include <TransportConnectionCanvasVisualizer.h>
Classes
class TransportConnectionCanvasVisualization
Protected Member Functions
virtual void initialize (int stage) override
virtual LabeledIconFigure * createConnectionEndFigure (tcp::TcpConnection *connectionVisualization) const
virtual const TransportConnectionVisualization * createConnectionVisualization (cModule *source, cModule *destination, tcp::TcpConnection *tcpConnection) const override
virtual void addConnectionVisualization (const TransportConnectionVisualization *connectionVisualization) override
virtual void removeConnectionVisualization (const TransportConnectionVisualization *connectionVisualization) override
virtual void setConnectionLabelsVisible (bool visible)
Protected Member Functions inherited from inet::visualizer::TransportConnectionVisualizerBase
virtual void handleParameterChange (const char *name) override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual void removeAllConnectionVisualizations ()
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes
double zIndex = NaN
const CanvasProjection * canvasProjection = nullptr
ModuleRefByPar< NetworkNodeCanvasVisualizer > networkNodeVisualizer
Protected Attributes inherited from inet::visualizer::TransportConnectionVisualizerBase
bool displayTransportConnections = false
NetworkNodeFilter sourceNodeFilter
PortFilter sourcePortFilter
NetworkNodeFilter destinationNodeFilter
PortFilter destinationPortFilter
const char * icon = nullptr
ColorSet iconColorSet
cFigure::Font labelFont
cFigure::Color labelColor
Placement placementHint
double placementPriority
std::vector< const TransportConnectionVisualization * > connectionVisualizations
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Additional Inherited Members
Public Member Functions inherited from inet::visualizer::TransportConnectionVisualizerBase
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Member Function Documentation
addConnectionVisualization()
void inet::visualizer::TransportConnectionCanvasVisualizer::addConnectionVisualization (const TransportConnectionVisualization * connectionVisualization) override protected virtual
Reimplemented from inet::visualizer::TransportConnectionVisualizerBase.
 {
     TransportConnectionVisualizerBase::addConnectionVisualization(connectionVisualization);
     auto connectionCanvasVisualization = static_cast<const TransportConnectionCanvasVisualization *>(connectionVisualization);
     auto sourceModule = getSimulation()->getModule(connectionVisualization->sourceModuleId);
     if (sourceModule != nullptr) {
         auto sourceVisualization = networkNodeVisualizer->getNetworkNodeVisualization(getContainingNode(sourceModule));
         sourceVisualization->addAnnotation(connectionCanvasVisualization->sourceFigure, connectionCanvasVisualization->sourceFigure->getBounds().getSize(), placementHint, placementPriority);
     }
     auto destinationModule = getSimulation()->getModule(connectionVisualization->destinationModuleId);
     if (destinationModule != nullptr) {
         auto destinationVisualization = networkNodeVisualizer->getNetworkNodeVisualization(getContainingNode(destinationModule));
         destinationVisualization->addAnnotation(connectionCanvasVisualization->destinationFigure, connectionCanvasVisualization->destinationFigure->getBounds().getSize(), placementHint, placementPriority);
     }
     setConnectionLabelsVisible(connectionVisualizations.size() > iconColorSet.getSize());
 }
createConnectionEndFigure()
LabeledIconFigure * inet::visualizer::TransportConnectionCanvasVisualizer::createConnectionEndFigure (tcp::TcpConnection * connectionVisualization) const protected virtual
 {
 #ifdef INET_WITH_TCP_INET
     std::string icon(this->icon);
     auto labeledIconFigure = new LabeledIconFigure("transportConnection");
     labeledIconFigure->setTags((std::string("transport_connection ") + tags).c_str());
     labeledIconFigure->setTooltip("This icon represents a transport connection between two network nodes");
     labeledIconFigure->setAssociatedObject(tcpConnection);
     labeledIconFigure->setZIndex(zIndex);
     auto iconFigure = labeledIconFigure->getIconFigure();
     iconFigure->setTooltip("This icon represents a transport connection between two network nodes");
     iconFigure->setImageName(icon.substr(0, icon.find_first_of(".")).c_str());
     iconFigure->setTintColor(iconColorSet.getColor(connectionVisualizations.size()));
     iconFigure->setTintAmount(1);
     auto labelFigure = labeledIconFigure->getLabelFigure();
     labelFigure->setTooltip("This label represents a transport connection between two network nodes");
     labelFigure->setPosition(iconFigure->getBounds().getSize() / 2);
     labelFigure->setFont(labelFont);
     labelFigure->setColor(labelColor);
     char label[2];
     label[0] = 'A' + (char)(connectionVisualizations.size() / iconColorSet.getSize());
     label[1] = '\0';
     labelFigure->setText(label);
     return labeledIconFigure;
 #else
     return nullptr;
 #endif // INET_WITH_TCP_INET
 }
Referenced by createConnectionVisualization().
createConnectionVisualization()
const TransportConnectionVisualizerBase::TransportConnectionVisualization * inet::visualizer::TransportConnectionCanvasVisualizer::createConnectionVisualization (cModule * source, cModule * destination, tcp::TcpConnection * tcpConnection) const override protected virtual
Implements inet::visualizer::TransportConnectionVisualizerBase.
 {
     auto sourceFigure = createConnectionEndFigure(tcpConnection);
     auto destinationFigure = createConnectionEndFigure(tcpConnection);
     return new TransportConnectionCanvasVisualization(sourceFigure, destinationFigure, source->getId(), destination->getId(), 1);
 }
initialize()
void inet::visualizer::TransportConnectionCanvasVisualizer::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::TransportConnectionVisualizerBase.
 {
     TransportConnectionVisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         zIndex = par("zIndex");
         auto canvas = visualizationTargetModule->getCanvas();
         canvasProjection = CanvasProjection::getCanvasProjection(canvas);
         networkNodeVisualizer.reference(this, "networkNodeVisualizerModule", true);
     }
 }
removeConnectionVisualization()
void inet::visualizer::TransportConnectionCanvasVisualizer::removeConnectionVisualization (const TransportConnectionVisualization * connectionVisualization) override protected virtual
Reimplemented from inet::visualizer::TransportConnectionVisualizerBase.
 {
     TransportConnectionVisualizerBase::removeConnectionVisualization(connectionVisualization);
     auto connectionCanvasVisualization = static_cast<const TransportConnectionCanvasVisualization *>(connectionVisualization);
     auto sourceModule = getSimulation()->getModule(connectionVisualization->sourceModuleId);
     if (sourceModule != nullptr) {
         auto sourceVisualization = networkNodeVisualizer->getNetworkNodeVisualization(getContainingNode(sourceModule));
         sourceVisualization->removeAnnotation(connectionCanvasVisualization->sourceFigure);
     }
     auto destinationModule = getSimulation()->getModule(connectionVisualization->destinationModuleId);
     if (destinationModule != nullptr) {
         auto destinationVisualization = networkNodeVisualizer->getNetworkNodeVisualization(getContainingNode(destinationModule));
         destinationVisualization->removeAnnotation(connectionCanvasVisualization->destinationFigure);
     }
     setConnectionLabelsVisible(connectionVisualizations.size() > iconColorSet.getSize());
 }
setConnectionLabelsVisible()
void inet::visualizer::TransportConnectionCanvasVisualizer::setConnectionLabelsVisible (bool visible) protected virtual
 {
     for (auto connectionVisualization : connectionVisualizations) {
         auto connectionCanvasVisualization = static_cast<const TransportConnectionCanvasVisualization *>(connectionVisualization);
         connectionCanvasVisualization->sourceFigure->getLabelFigure()->setVisible(visible);
         connectionCanvasVisualization->destinationFigure->getLabelFigure()->setVisible(visible);
     }
 }
Referenced by addConnectionVisualization(), and removeConnectionVisualization().
Member Data Documentation
canvasProjection
const CanvasProjection* inet::visualizer::TransportConnectionCanvasVisualizer::canvasProjection = nullptr protected
Referenced by initialize().
networkNodeVisualizer
ModuleRefByPar<NetworkNodeCanvasVisualizer> inet::visualizer::TransportConnectionCanvasVisualizer::networkNodeVisualizer protected
Referenced by addConnectionVisualization(), initialize(), and removeConnectionVisualization().
zIndex
double inet::visualizer::TransportConnectionCanvasVisualizer::zIndex = NaN protected
Referenced by createConnectionEndFigure(), and initialize().
The documentation for this class was generated from the following files:
TransportConnectionCanvasVisualizer.h
TransportConnectionCanvasVisualizer.cc