INET Framework for OMNeT++/OMNEST: inet::LinearGaugeFigure Class Reference
inet::LinearGaugeFigure Class Reference
#include <LinearGaugeFigure.h>
Public Member Functions
LinearGaugeFigure (const char *name=nullptr)
virtual ~LinearGaugeFigure ()
virtual const Point getSize () const override
virtual void setValue (int series, simtime_t timestamp, double value) override
const Rectangle & getBounds () const
void setBounds (const Rectangle &rect)
const Color & getBackgroundColor () const
void setBackgroundColor (const Color &color)
const Color & getNeedleColor () const
void setNeedleColor (const Color &color)
const char * getLabel () const
void setLabel (const char *text)
int getLabelOffset () const
void setLabelOffset (int offset)
const Font & getLabelFont () const
void setLabelFont (const Font &font)
const Color & getLabelColor () const
void setLabelColor (const Color &color)
double getMinValue () const
void setMinValue (double value)
double getMaxValue () const
void setMaxValue (double value)
double getTickSize () const
void setTickSize (double value)
double getCornerRadius () const
void setCornerRadius (double radius)
Public Member Functions inherited from inet::IIndicatorFigure
virtual ~IIndicatorFigure ()
virtual int getNumSeries () const
virtual void refreshDisplay ()
Protected Member Functions
virtual void parse (cProperty *property) override
virtual const char ** getAllowedPropertyKeys () const override
void addChildren ()
void setTickGeometry (cLineFigure *tick, int index)
void setNumberGeometry (cTextFigure *number, int index)
void setNeedleGeometry ()
void redrawTicks ()
void layout ()
void refresh ()
Private Attributes
cLineFigure * needle
cTextFigure * labelFigure
cRectangleFigure * backgroundFigure
cLineFigure * axisFigure
std::vector< cLineFigure * > tickFigures
std::vector< cTextFigure * > numberFigures
double min = 0
double max = 100
double tickSize = 10
double value = NaN
int numTicks = 0
double shifting = 0
int labelOffset = 10
Constructor & Destructor Documentation
LinearGaugeFigure()
inet::LinearGaugeFigure::LinearGaugeFigure (const char * name = nullptr)
                                                      : cGroupFigure(name)
 {
     addChildren();
 }
~LinearGaugeFigure()
inet::LinearGaugeFigure::~LinearGaugeFigure () virtual
 {
     // delete figures which is not in canvas
     for (uint32_t i = numTicks; i < tickFigures.size(); ++i) {
         dropAndDelete(tickFigures[i]);
         dropAndDelete(numberFigures[i]);
     }
 }
Member Function Documentation
addChildren()
void inet::LinearGaugeFigure::addChildren () protected
 {
     backgroundFigure = new cRectangleFigure("background");
     needle = new cLineFigure("needle");
     labelFigure = new cTextFigure("label");
     axisFigure = new cLineFigure("axis");
     backgroundFigure->setFilled(true);
     backgroundFigure->setFillColor(Color("#b8afa6"));
     needle->setLineColor("red");
     labelFigure->setAnchor(cFigure::ANCHOR_N);
     addFigure(backgroundFigure);
     addFigure(axisFigure);
     addFigure(needle);
     addFigure(labelFigure);
 }
Referenced by LinearGaugeFigure().
getAllowedPropertyKeys()
const char ** inet::LinearGaugeFigure::getAllowedPropertyKeys () const override protected virtual
 {
     static const char *keys[32];
     if (!keys[0]) {
         const char *localKeys[] = {
             PKEY_BACKGROUND_COLOR, PKEY_NEEDLE_COLOR, PKEY_LABEL, PKEY_LABEL_FONT,
             PKEY_LABEL_COLOR, PKEY_MIN_VALUE, PKEY_MAX_VALUE, PKEY_TICK_SIZE,
             PKEY_CORNER_RADIUS, PKEY_INITIAL_VALUE, PKEY_POS, PKEY_SIZE, PKEY_ANCHOR,
             PKEY_BOUNDS, PKEY_LABEL_OFFSET, nullptr
         };
         concatArrays(keys, cGroupFigure::getAllowedPropertyKeys(), localKeys);
     }
     return keys;
 }
getBackgroundColor()
const cFigure::Color & inet::LinearGaugeFigure::getBackgroundColor () const
 {
     return backgroundFigure->getFillColor();
 }
getBounds()
const cFigure::Rectangle & inet::LinearGaugeFigure::getBounds () const
 {
     return backgroundFigure->getBounds();
 }
Referenced by layout(), parse(), setLabelOffset(), setNeedleGeometry(), setNumberGeometry(), and setTickGeometry().
getCornerRadius()
double inet::LinearGaugeFigure::getCornerRadius () const
 {
     return backgroundFigure->getCornerRx();
 }
getLabel()
const char * inet::LinearGaugeFigure::getLabel () const
 {
     return labelFigure->getText();
 }
getLabelColor()
const cFigure::Color & inet::LinearGaugeFigure::getLabelColor () const
 {
     return labelFigure->getColor();
 }
getLabelFont()
const cFigure::Font & inet::LinearGaugeFigure::getLabelFont () const
 {
     return labelFigure->getFont();
 }
getLabelOffset()
int inet::LinearGaugeFigure::getLabelOffset () const
 {
     return labelOffset;
 }
getMaxValue()
double inet::LinearGaugeFigure::getMaxValue () const
 {
     return max;
 }
getMinValue()
double inet::LinearGaugeFigure::getMinValue () const
 {
     return min;
 }
getNeedleColor()
const cFigure::Color & inet::LinearGaugeFigure::getNeedleColor () const
 {
     return needle->getLineColor();
 }
getSize()
virtual const Point inet::LinearGaugeFigure::getSize () const inline override virtual
Implements inet::IIndicatorFigure.
 { return getBounds().getSize(); }
getTickSize()
double inet::LinearGaugeFigure::getTickSize () const
 {
     return tickSize;
 }
layout()
void inet::LinearGaugeFigure::layout () protected
 {
     backgroundFigure->setLineWidth(getBounds().height * BORDER_WIDTH_PERCENT);
     double y = getBounds().getCenter().y;
     axisFigure->setLineWidth(getBounds().height * AXIS_WIDTH_PERCENT);
     axisFigure->setStart(Point(getBounds().x + getBounds().width * FRAME_PERCENT + axisFigure->getLineWidth() / 2, y));
     axisFigure->setEnd(Point(getBounds().x + getBounds().width * (1 - FRAME_PERCENT) + axisFigure->getLineWidth() / 2, y));
     for (int i = 0; i < numTicks; ++i) {
         setTickGeometry(tickFigures[i], i);
         setNumberGeometry(numberFigures[i], i);
     }
     setNeedleGeometry();
     labelFigure->setPosition(Point(getBounds().getCenter().x, getBounds().y + getBounds().height + labelOffset));
 }
Referenced by setBounds().
parse()
void inet::LinearGaugeFigure::parse (cProperty * property) override protected virtual
 {
     cGroupFigure::parse(property);
     const char *s;
     setBounds(parseBounds(property, getBounds()));
     // Set default
     redrawTicks();
     if ((s = property->getValue(PKEY_BACKGROUND_COLOR)) != nullptr)
         setBackgroundColor(parseColor(s));
     if ((s = property->getValue(PKEY_NEEDLE_COLOR)) != nullptr)
         setNeedleColor(parseColor(s));
     if ((s = property->getValue(PKEY_LABEL)) != nullptr)
         setLabel(s);
     if ((s = property->getValue(PKEY_LABEL_OFFSET)) != nullptr)
         setLabelOffset(atoi(s));
     if ((s = property->getValue(PKEY_LABEL_FONT)) != nullptr)
         setLabelFont(parseFont(s));
     if ((s = property->getValue(PKEY_LABEL_COLOR)) != nullptr)
         setLabelColor(parseColor(s));
     // This must be initialize before min and max because it is possible to be too much unnecessary tick and number
     if ((s = property->getValue(PKEY_TICK_SIZE)) != nullptr)
         setTickSize(utils::atod(s));
     if ((s = property->getValue(PKEY_MIN_VALUE)) != nullptr)
         setMinValue(utils::atod(s));
     if ((s = property->getValue(PKEY_MAX_VALUE)) != nullptr)
         setMaxValue(utils::atod(s));
     if ((s = property->getValue(PKEY_CORNER_RADIUS)) != nullptr)
         setCornerRadius(utils::atod(s));
     if ((s = property->getValue(PKEY_INITIAL_VALUE)) != nullptr)
         setValue(0, simTime(), utils::atod(s));
 }
redrawTicks()
void inet::LinearGaugeFigure::redrawTicks () protected
 {
     ASSERT(tickFigures.size() == numberFigures.size());
     double fraction = std::abs(fmod(min / tickSize, 1));
     shifting = tickSize * (min < 0 ? fraction : 1 - fraction);
     // if fraction == 0 then shifting == tickSize therefore don't have to shift the ticks
     if (shifting == tickSize)
         shifting = 0;
     int prevNumTicks = numTicks;
     numTicks = std::max(0.0, std::abs(max - min - shifting) / tickSize + 1);
     // Allocate ticks and numbers if needed
     if ((size_t)numTicks > tickFigures.size())
         while ((size_t)numTicks > tickFigures.size()) {
             cLineFigure *tick = new cLineFigure();
             cTextFigure *number = new cTextFigure();
             take(tick);
             take(number);
             number->setAnchor(cFigure::ANCHOR_N);
             tickFigures.push_back(tick);
             numberFigures.push_back(number);
         }
     // Add or remove figures from canvas according to previous number of ticks
     for (int i = numTicks; i < prevNumTicks; ++i) {
         removeFigure(tickFigures[i]);
         removeFigure(numberFigures[i]);
         take(tickFigures[i]);
         take(numberFigures[i]);
     }
     for (int i = prevNumTicks; i < numTicks; ++i) {
         drop(tickFigures[i]);
         drop(numberFigures[i]);
         tickFigures[i]->insertBelow(needle);
         numberFigures[i]->insertBelow(needle);
     }
     for (int i = 0; i < numTicks; ++i) {
         setTickGeometry(tickFigures[i], i);
         double number = min + i * tickSize + shifting;
         if (std::abs(number) < tickSize / 2)
             number = 0;
         char buf[32];
         sprintf(buf, "%g", number);
         numberFigures[i]->setText(buf);
         setNumberGeometry(numberFigures[i], i);
     }
 }
Referenced by parse(), setMaxValue(), setMinValue(), and setTickSize().
refresh()
void inet::LinearGaugeFigure::refresh () protected
 {
     setNeedleGeometry();
 }
Referenced by setMaxValue(), setMinValue(), setTickSize(), and setValue().
setBackgroundColor()
void inet::LinearGaugeFigure::setBackgroundColor (const Color & color)
 {
     backgroundFigure->setFillColor(color);
 }
Referenced by parse().
setBounds()
void inet::LinearGaugeFigure::setBounds (const Rectangle & rect)
 {
     backgroundFigure->setBounds(rect);
     layout();
 }
Referenced by parse().
setCornerRadius()
void inet::LinearGaugeFigure::setCornerRadius (double radius)
 {
     backgroundFigure->setCornerRadius(radius);
 }
Referenced by parse().
setLabel()
void inet::LinearGaugeFigure::setLabel (const char * text)
 {
     labelFigure->setText(text);
 }
Referenced by parse().
setLabelColor()
void inet::LinearGaugeFigure::setLabelColor (const Color & color)
 {
     labelFigure->setColor(color);
 }
Referenced by parse().
setLabelFont()
void inet::LinearGaugeFigure::setLabelFont (const Font & font)
 {
     labelFigure->setFont(font);
 }
Referenced by parse().
setLabelOffset()
void inet::LinearGaugeFigure::setLabelOffset (int offset)
 {
     if (labelOffset != offset) {
         labelOffset = offset;
         labelFigure->setPosition(Point(getBounds().getCenter().x, getBounds().y + getBounds().height + labelOffset));
     }
 }
Referenced by parse().
setMaxValue()
void inet::LinearGaugeFigure::setMaxValue (double value)
 {
     if (max != value) {
         max = value;
         redrawTicks();
         refresh();
     }
 }
Referenced by parse().
setMinValue()
void inet::LinearGaugeFigure::setMinValue (double value)
 {
     if (min != value) {
         min = value;
         redrawTicks();
         refresh();
     }
 }
Referenced by parse().
setNeedleColor()
void inet::LinearGaugeFigure::setNeedleColor (const Color & color)
 {
     needle->setLineColor(color);
 }
Referenced by parse().
setNeedleGeometry()
void inet::LinearGaugeFigure::setNeedleGeometry () protected
 {
     needle->setLineWidth(getBounds().height * NEEDLE_WIDTH_PERCENT);
     double x = axisFigure->getStart().x + axisFigure->getLineWidth() / 2;
     double axisWidth = axisFigure->getEnd().x - axisFigure->getStart().x - axisFigure->getLineWidth();
     needle->setVisible(true);
     if (std::isnan(value)) {
         needle->setVisible(false);
         return;
     }
     else if (value < min)
         x -= getBounds().width * NEEDLE_OFFSET_PERCENT;
     else if (value > max)
         x = axisFigure->getEnd().x + getBounds().width * NEEDLE_OFFSET_PERCENT;
     else
         x += (value - min) * axisWidth / (max - min);
     needle->setStart(Point(x, axisFigure->getStart().y - getBounds().height * NEEDLE_HEIGHT_PERCENT / 2));
     needle->setEnd(Point(x, axisFigure->getStart().y + getBounds().height * NEEDLE_HEIGHT_PERCENT / 2));
 }
Referenced by layout(), and refresh().
setNumberGeometry()
void inet::LinearGaugeFigure::setNumberGeometry (cTextFigure * number, int index) protected
 {
     double axisWidth = axisFigure->getEnd().x - axisFigure->getStart().x - axisFigure->getLineWidth() / 2;
     double x = axisFigure->getStart().x + axisFigure->getLineWidth() / 2
         + axisWidth * (index * tickSize + shifting) / (max - min);
     Point textPos = Point(x, axisFigure->getStart().y + getBounds().height * NUMBER_Y_PERCENT);
     number->setPosition(textPos);
     number->setFont(cFigure::Font("", getBounds().height * NUMBER_FONTSIZE_PERCENT, 0));
 }
Referenced by layout(), and redrawTicks().
setTickGeometry()
void inet::LinearGaugeFigure::setTickGeometry (cLineFigure * tick, int index) protected
 {
     double axisWidth = axisFigure->getEnd().x - axisFigure->getStart().x - axisFigure->getLineWidth();
     double x = axisFigure->getStart().x + axisFigure->getLineWidth() / 2
         + axisWidth * (index * tickSize + shifting) / (max - min);
     tick->setStart(Point(x, getBounds().getCenter().y));
     Point endPos = tick->getStart();
     endPos.y -= !(index % 3) ? getBounds().height * TICK_SMALL_LENGTH_PERCENT :
         getBounds().height * TICK_BIG_LENGTH_PERCENT;
     tick->setEnd(endPos);
     tick->setLineWidth(getBounds().height * AXIS_WIDTH_PERCENT);
 }
Referenced by layout(), and redrawTicks().
setTickSize()
void inet::LinearGaugeFigure::setTickSize (double value)
 {
     if (tickSize != value) {
         tickSize = value;
         redrawTicks();
         refresh();
     }
 }
Referenced by parse().
setValue()
void inet::LinearGaugeFigure::setValue (int series, simtime_t timestamp, double value) override virtual
Implements inet::IIndicatorFigure.
 {
     ASSERT(series == 0);
     // Note: we currently ignore timestamp
     if (value != newValue) {
         value = newValue;
         refresh();
     }
 }
Referenced by parse().
Member Data Documentation
axisFigure
cLineFigure* inet::LinearGaugeFigure::axisFigure private
Referenced by addChildren(), layout(), setNeedleGeometry(), setNumberGeometry(), and setTickGeometry().
backgroundFigure
cRectangleFigure* inet::LinearGaugeFigure::backgroundFigure private
Referenced by addChildren(), getBackgroundColor(), getBounds(), getCornerRadius(), layout(), setBackgroundColor(), setBounds(), and setCornerRadius().
labelFigure
cTextFigure* inet::LinearGaugeFigure::labelFigure private
Referenced by addChildren(), getLabel(), getLabelColor(), getLabelFont(), layout(), setLabel(), setLabelColor(), setLabelFont(), and setLabelOffset().
labelOffset
int inet::LinearGaugeFigure::labelOffset = 10 private
Referenced by getLabelOffset(), layout(), and setLabelOffset().
max
double inet::LinearGaugeFigure::max = 100 private
Referenced by getMaxValue(), redrawTicks(), setMaxValue(), setNeedleGeometry(), setNumberGeometry(), and setTickGeometry().
min
double inet::LinearGaugeFigure::min = 0 private
Referenced by getMinValue(), redrawTicks(), setMinValue(), setNeedleGeometry(), setNumberGeometry(), and setTickGeometry().
needle
cLineFigure* inet::LinearGaugeFigure::needle private
Referenced by addChildren(), getNeedleColor(), redrawTicks(), setNeedleColor(), and setNeedleGeometry().
numberFigures
std::vector<cTextFigure *> inet::LinearGaugeFigure::numberFigures private
Referenced by layout(), redrawTicks(), and ~LinearGaugeFigure().
numTicks
int inet::LinearGaugeFigure::numTicks = 0 private
Referenced by layout(), redrawTicks(), and ~LinearGaugeFigure().
shifting
double inet::LinearGaugeFigure::shifting = 0 private
Referenced by redrawTicks(), setNumberGeometry(), and setTickGeometry().
tickFigures
std::vector<cLineFigure *> inet::LinearGaugeFigure::tickFigures private
Referenced by layout(), redrawTicks(), and ~LinearGaugeFigure().
tickSize
double inet::LinearGaugeFigure::tickSize = 10 private
Referenced by getTickSize(), redrawTicks(), setNumberGeometry(), setTickGeometry(), and setTickSize().
value
double inet::LinearGaugeFigure::value = NaN private
Referenced by setMaxValue(), setMinValue(), setNeedleGeometry(), setTickSize(), and setValue().
The documentation for this class was generated from the following files:
LinearGaugeFigure.h
LinearGaugeFigure.cc