INET Framework for OMNeT++/OMNEST: inet::SelfDoc Class Reference
inet::SelfDoc Class Reference
#include <SelfDoc.h>
Public Member Functions
SelfDoc ()
~SelfDoc () noexcept(false)
void insert (const std::string &text)
Static Public Member Functions
static bool notInInitialize ()
static bool notInInitialize (const char *methodFmt,...)
static const char * enterMethodInfo ()
static const char * enterMethodInfo (const char *methodFmt,...)
static std::string kindToStr (int kind, cProperties *properties1, const char *propName1, cProperties *properties2, const char *propName2)
static std::string val (const char *str)
static std::string val (const std::string &str)
static std::string keyVal (const std::string &key, const std::string &value)
static std::string tagsToJson (const char *key, cMessage *msg)
static std::string gateInfo (cGate *gate)
Static Public Attributes
static bool generateSelfdoc = false
Protected Attributes
std::set< std::string > textSet
Constructor & Destructor Documentation
SelfDoc()
inet::SelfDoc::SelfDoc () inline
 {}
~SelfDoc()
inet::SelfDoc::~SelfDoc () noexcept
 {
     if (generateSelfdoc) {
         std::ofstream file;
         file.open("/tmp/SelfDoc.txt", std::ofstream::out | std::ofstream::app);
         if (file.fail())
             throw std::ios_base::failure(std::strerror(errno));
         //make sure write fails with exception if something is wrong
         file.exceptions(file.exceptions() | std::ios::failbit | std::ifstream::badbit);
         for (const auto& elem : textSet)
             file << elem << ',' << std::endl;
         file.close();
     }
 }
Member Function Documentation
enterMethodInfo() [1/2]
static const char* inet::SelfDoc::enterMethodInfo () inline static
 { return ""; }
enterMethodInfo() [2/2]
const char * inet::SelfDoc::enterMethodInfo (const char * methodFmt, ...) static
 {
     if (methodFmt == nullptr)
         return "";
     if (0 == strcmp("%s", methodFmt)) {
         std::va_list args;
         va_start(args, methodFmt);
         const char *str = va_arg(args, const char *);
         va_end(args);
         return str;
     }
     else
         return methodFmt;
 }
gateInfo()
std::string inet::SelfDoc::gateInfo (cGate * gate) static
 {
     if (gate) {
         std::ostringstream os;
         os << gate->getName() << (gate->isVector() ? "[]" : "");
         return os.str();
     }
     else
         return "";
 }
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), and inet::queueing::PacketProcessorBase::animate().
insert()
void inet::SelfDoc::insert (const std::string & text) inline
 { if (generateSelfdoc) textSet.insert(text); }
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), and inet::queueing::PacketProcessorBase::animate().
keyVal()
static std::string inet::SelfDoc::keyVal (const std::string & key, const std::string & value) inline static
 { return val(key) + " : " + val(value); }
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), and inet::queueing::PacketProcessorBase::animate().
kindToStr()
std::string inet::SelfDoc::kindToStr (int kind, cProperties * properties1, const char * propName1, cProperties * properties2, const char * propName2) static
 {
     if (generateSelfdoc) {
         if (properties1) {
             auto prop = properties1->get(propName1);
             if (!prop && properties2)
                 prop = properties2->get(propName2);
             if (prop) {
                 if (auto propValue = prop->getValue()) {
                     if (auto e = omnetpp::cEnum::find(propValue)) {
                         if (auto t = e->getStringFor(kind)) {
                             std::ostringstream os;
                             os << kind << " (" << propValue << "::" << t << ")";
                             return os.str();
                         }
                     }
                 }
             }
         }
         return std::to_string(kind);
     }
     else
         return std::string("");
 }
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), and inet::queueing::PacketProcessorBase::animate().
notInInitialize() [1/2]
static bool inet::SelfDoc::notInInitialize () inline static
 { return true; }
notInInitialize() [2/2]
static bool inet::SelfDoc::notInInitialize (const char * methodFmt, ...) inline static
 { return methodFmt != nullptr && (0 != strcmp(methodFmt, "initialize(%d)")); }
tagsToJson()
std::string inet::SelfDoc::tagsToJson (const char * key, cMessage * msg) static
 {
     std::set<std::string> tagSet;
     std::ostringstream os;
     auto tags = findTags(msg);
     if (tags) {
         auto cnt = tags->getNumTags();
         for (int i=0; i < cnt; i++) {
             auto tag = tags->getTag(i).get();
             if (tag)
                 tagSet.insert(opp_typename(typeid(*tag)));
         }
     }
     os << SelfDoc::val(key) << " : [ ";
     const char *sep = "";
     for (const auto& t : tagSet) {
         os << sep << SelfDoc::val(t);
         sep = ", ";
     }
     os << " ]";
     return os.str();
 }
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), and inet::queueing::PacketProcessorBase::animate().
val() [1/2]
std::string inet::SelfDoc::val (const char * str) static
 {
     std::ostringstream os;
     os << '"';
     char hexbuf[5];
     while (*str) {
         switch (*str) {
             case '\b': os << "\\b"; break;
             case '\f': os << "\\f"; break;
             case '\n': os << "\\n"; break;
             case '\r': os << "\\r"; break;
             case '\t': os << "\\t"; break;
             case '"':  os << "\\\""; break;
             case '\\': os << "\\\\"; break;
             default: if (iscntrl(*str)) { sprintf(hexbuf,"\\x%2.2X",*str); os << hexbuf; } else { os << *str; } break;
         }
         str++;
     }
     os << '"';
     return os.str();
 }
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), inet::queueing::PacketProcessorBase::animate(), and tagsToJson().
val() [2/2]
static std::string inet::SelfDoc::val (const std::string & str) inline static
 { return val(str.c_str()); }
Referenced by val().
Member Data Documentation
generateSelfdoc
bool inet::SelfDoc::generateSelfdoc = false static
Referenced by inet::SelfDocumenterFingerprintCalculator::addEvent(), inet::queueing::PacketProcessorBase::animate(), kindToStr(), inet::SelfDocTempOffClass::SelfDocTempOffClass(), ~SelfDoc(), and inet::SelfDocTempOffClass::~SelfDocTempOffClass().
textSet
std::set<std::string> inet::SelfDoc::textSet protected
Referenced by ~SelfDoc().
The documentation for this class was generated from the following files:
SelfDoc.h
SelfDoc.cc