INET Framework for OMNeT++/OMNEST: inet::visualizer::Ieee80211VisualizerBase Class Reference
inet::visualizer::Ieee80211VisualizerBase Class Reference abstract
#include <Ieee80211VisualizerBase.h>
Classes
class Ieee80211Visualization
Parameters
bool displayAssociations = false
NetworkNodeFilter nodeFilter
InterfaceFilter interfaceFilter
double minPowerDbm = NaN
double maxPowerDbm = NaN
std::vector< std::string > icons
ColorSet iconColorSet
cFigure::Font labelFont
cFigure::Color labelColor
Placement placementHint
double placementPriority
std::map< std::pair< int, int >, const Ieee80211Visualization * > ieee80211Visualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual Ieee80211Visualization * createIeee80211Visualization (cModule *networkNode, NetworkInterface *networkInterface, std::string ssid, W power)=0
virtual const Ieee80211Visualization * getIeee80211Visualization (cModule *networkNode, NetworkInterface *networkInterface)
virtual void addIeee80211Visualization (const Ieee80211Visualization *ieee80211Visualization)
virtual void removeIeee80211Visualization (const Ieee80211Visualization *ieee80211Visualization)
virtual void removeAllIeee80211Visualizations ()
virtual std::string getIcon (W power) const
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addIeee80211Visualization()
void inet::visualizer::Ieee80211VisualizerBase::addIeee80211Visualization (const Ieee80211Visualization * ieee80211Visualization) protected virtual
Reimplemented in inet::visualizer::Ieee80211CanvasVisualizer, and inet::visualizer::Ieee80211OsgVisualizer.
 {
     auto key = std::pair<int, int>(ieee80211Visualization->networkNodeId, ieee80211Visualization->interfaceId);
     ieee80211Visualizations[key] = ieee80211Visualization;
 }
Referenced by inet::visualizer::Ieee80211OsgVisualizer::addIeee80211Visualization(), inet::visualizer::Ieee80211CanvasVisualizer::addIeee80211Visualization(), and receiveSignal().
createIeee80211Visualization()
virtual Ieee80211Visualization* inet::visualizer::Ieee80211VisualizerBase::createIeee80211Visualization (cModule * networkNode, NetworkInterface * networkInterface, std::string ssid, W power) protected pure virtual
Implemented in inet::visualizer::Ieee80211CanvasVisualizer, and inet::visualizer::Ieee80211OsgVisualizer.
Referenced by receiveSignal().
getIcon()
std::string inet::visualizer::Ieee80211VisualizerBase::getIcon (W power) const protected virtual
 {
     int index;
     auto powerDbm = math::mW2dBmW(mW(power).get());
     if (std::isnan(powerDbm))
         index = icons.size() - 1;
     else if (powerDbm < minPowerDbm)
         index = 0;
     else if (powerDbm > maxPowerDbm)
         index = icons.size() - 1;
     else
         index = round((icons.size() - 1) * (powerDbm - minPowerDbm) / (maxPowerDbm - minPowerDbm));
     return icons[index];
 }
Referenced by inet::visualizer::Ieee80211OsgVisualizer::createIeee80211Visualization(), inet::visualizer::Ieee80211CanvasVisualizer::createIeee80211Visualization(), and inet::visualizer::Ieee80211CanvasVisualizer::refreshDisplay().
getIeee80211Visualization()
const Ieee80211VisualizerBase::Ieee80211Visualization * inet::visualizer::Ieee80211VisualizerBase::getIeee80211Visualization (cModule * networkNode, NetworkInterface * networkInterface) protected virtual
 {
     auto key = std::pair<int, int>(networkNode->getId(), networkInterface->getInterfaceId());
     auto it = ieee80211Visualizations.find(key);
     return it == ieee80211Visualizations.end() ? nullptr : it->second;
 }
Referenced by receiveSignal().
handleParameterChange()
void inet::visualizer::Ieee80211VisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "nodeFilter"))
             nodeFilter.setPattern(par("nodeFilter"));
         else if (!strcmp(name, "interfaceFilter"))
             interfaceFilter.setPattern(par("interfaceFilter"));
         removeAllIeee80211Visualizations();
     }
 }
initialize()
void inet::visualizer::Ieee80211VisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::Ieee80211CanvasVisualizer, and inet::visualizer::Ieee80211OsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayAssociations = par("displayAssociations");
         nodeFilter.setPattern(par("nodeFilter"));
         interfaceFilter.setPattern(par("interfaceFilter"));
         minPowerDbm = par("minPower");
         maxPowerDbm = par("maxPower");
         const char *iconsAsString = par("icons");
         cStringTokenizer tokenizer(iconsAsString);
         while (tokenizer.hasMoreTokens())
             icons.push_back(tokenizer.nextToken());
         iconColorSet.parseColors(par("iconColor"));
         labelFont = cFigure::parseFont(par("labelFont"));
         labelColor = cFigure::Color(par("labelColor"));
         placementHint = parsePlacement(par("placementHint"));
         placementPriority = par("placementPriority");
         if (displayAssociations)
             subscribe();
     }
 }
Referenced by inet::visualizer::Ieee80211OsgVisualizer::initialize(), and inet::visualizer::Ieee80211CanvasVisualizer::initialize().
preDelete()
void inet::visualizer::Ieee80211VisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayAssociations) {
         unsubscribe();
         removeAllIeee80211Visualizations();
     }
 }
receiveSignal()
void inet::visualizer::Ieee80211VisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
 #ifdef INET_WITH_IEEE80211
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == l2AssociatedSignal) {
         auto networkNode = getContainingNode(check_and_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode)) {
             auto networkInterface = check_and_cast<NetworkInterface *>(object);
             auto apInfo = check_and_cast<inet::ieee80211::Ieee80211MgmtSta::ApInfo *>(details);
             auto ieee80211Visualization = createIeee80211Visualization(networkNode, networkInterface, apInfo->ssid, W(apInfo->rxPower));
             addIeee80211Visualization(ieee80211Visualization);
         }
     }
     else if (signal == l2DisassociatedSignal) {
         auto networkNode = getContainingNode(check_and_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode)) {
             auto networkInterface = check_and_cast<NetworkInterface *>(object);
             auto ieee80211Visualization = getIeee80211Visualization(networkNode, networkInterface);
             if (ieee80211Visualization != nullptr) {
                 removeIeee80211Visualization(ieee80211Visualization);
                 delete ieee80211Visualization;
             }
         }
     }
     else if (signal == l2ApAssociatedSignal) {
         auto networkNode = getContainingNode(check_and_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode)) {
             // KLUDGE this is the wrong way to lookup the interface and the ssid
             auto mgmt = check_and_cast<inet::ieee80211::Ieee80211MgmtAp *>(source);
             auto networkInterface = getContainingNicModule(mgmt);
             auto ieee80211Visualization = getIeee80211Visualization(networkNode, networkInterface);
             if (ieee80211Visualization == nullptr) {
                 auto ieee80211Visualization = createIeee80211Visualization(networkNode, networkInterface, mgmt->par("ssid"), W(NaN));
                 addIeee80211Visualization(ieee80211Visualization);
             }
         }
     }
     else if (signal == l2ApDisassociatedSignal) {
         auto networkNode = getContainingNode(check_and_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode)) {
             // KLUDGE this is the wrong way to lookup the interface
             auto mgmt = check_and_cast<inet::ieee80211::Ieee80211MgmtAp *>(source);
             auto networkInterface = getContainingNicModule(mgmt);
             auto ieee80211Visualization = getIeee80211Visualization(networkNode, networkInterface);
             if (ieee80211Visualization != nullptr) {
                 removeIeee80211Visualization(ieee80211Visualization);
                 delete ieee80211Visualization;
             }
         }
     }
     else
         throw cRuntimeError("Unknown signal");
 #endif // INET_WITH_IEEE80211
 }
removeAllIeee80211Visualizations()
void inet::visualizer::Ieee80211VisualizerBase::removeAllIeee80211Visualizations () protected virtual
 {
     std::vector<const Ieee80211Visualization *> removedIeee80211Visualizations;
     for (auto it : ieee80211Visualizations)
         removedIeee80211Visualizations.push_back(it.second);
     for (auto visualization : removedIeee80211Visualizations) {
         removeIeee80211Visualization(visualization);
         delete visualization;
     }
 }
Referenced by handleParameterChange(), and preDelete().
removeIeee80211Visualization()
void inet::visualizer::Ieee80211VisualizerBase::removeIeee80211Visualization (const Ieee80211Visualization * ieee80211Visualization) protected virtual
Reimplemented in inet::visualizer::Ieee80211CanvasVisualizer, and inet::visualizer::Ieee80211OsgVisualizer.
 {
     auto key = std::pair<int, int>(ieee80211Visualization->networkNodeId, ieee80211Visualization->interfaceId);
     ieee80211Visualizations.erase(ieee80211Visualizations.find(key));
 }
Referenced by receiveSignal(), removeAllIeee80211Visualizations(), inet::visualizer::Ieee80211OsgVisualizer::removeIeee80211Visualization(), and inet::visualizer::Ieee80211CanvasVisualizer::removeIeee80211Visualization().
subscribe()
void inet::visualizer::Ieee80211VisualizerBase::subscribe () protected virtual
 {
     visualizationSubjectModule->subscribe(l2AssociatedSignal, this);
     visualizationSubjectModule->subscribe(l2DisassociatedSignal, this);
     visualizationSubjectModule->subscribe(l2ApAssociatedSignal, this);
     visualizationSubjectModule->subscribe(l2ApDisassociatedSignal, this);
 }
Referenced by initialize().
unsubscribe()
void inet::visualizer::Ieee80211VisualizerBase::unsubscribe () protected virtual
 {
     // NOTE: lookup the module again because it may have been deleted first
     auto visualizationSubjectModule = findModuleFromPar<cModule>(par("visualizationSubjectModule"), this);
     if (visualizationSubjectModule != nullptr) {
         visualizationSubjectModule->unsubscribe(l2AssociatedSignal, this);
         visualizationSubjectModule->unsubscribe(l2DisassociatedSignal, this);
         visualizationSubjectModule->unsubscribe(l2ApAssociatedSignal, this);
         visualizationSubjectModule->unsubscribe(l2ApDisassociatedSignal, this);
     }
 }
Referenced by preDelete().
Member Data Documentation
displayAssociations
bool inet::visualizer::Ieee80211VisualizerBase::displayAssociations = false protected
Referenced by initialize(), and preDelete().
iconColorSet
ColorSet inet::visualizer::Ieee80211VisualizerBase::iconColorSet protected
Referenced by inet::visualizer::Ieee80211OsgVisualizer::createIeee80211Visualization(), inet::visualizer::Ieee80211CanvasVisualizer::createIeee80211Visualization(), and initialize().
icons
std::vector<std::string> inet::visualizer::Ieee80211VisualizerBase::icons protected
Referenced by getIcon(), and initialize().
ieee80211Visualizations
std::map<std::pair<int, int>, const Ieee80211Visualization *> inet::visualizer::Ieee80211VisualizerBase::ieee80211Visualizations protected
Referenced by addIeee80211Visualization(), getIeee80211Visualization(), inet::visualizer::Ieee80211CanvasVisualizer::refreshDisplay(), removeAllIeee80211Visualizations(), and removeIeee80211Visualization().
interfaceFilter
InterfaceFilter inet::visualizer::Ieee80211VisualizerBase::interfaceFilter protected
Referenced by handleParameterChange(), and initialize().
labelColor
cFigure::Color inet::visualizer::Ieee80211VisualizerBase::labelColor protected
Referenced by inet::visualizer::Ieee80211CanvasVisualizer::createIeee80211Visualization(), and initialize().
labelFont
cFigure::Font inet::visualizer::Ieee80211VisualizerBase::labelFont protected
Referenced by inet::visualizer::Ieee80211CanvasVisualizer::createIeee80211Visualization(), and initialize().
maxPowerDbm
double inet::visualizer::Ieee80211VisualizerBase::maxPowerDbm = NaN protected
Referenced by getIcon(), and initialize().
minPowerDbm
double inet::visualizer::Ieee80211VisualizerBase::minPowerDbm = NaN protected
Referenced by getIcon(), and initialize().
nodeFilter
NetworkNodeFilter inet::visualizer::Ieee80211VisualizerBase::nodeFilter protected
Referenced by handleParameterChange(), initialize(), and receiveSignal().
placementHint
Placement inet::visualizer::Ieee80211VisualizerBase::placementHint protected
Referenced by inet::visualizer::Ieee80211CanvasVisualizer::addIeee80211Visualization(), and initialize().
placementPriority
double inet::visualizer::Ieee80211VisualizerBase::placementPriority protected
Referenced by inet::visualizer::Ieee80211CanvasVisualizer::addIeee80211Visualization(), and initialize().
The documentation for this class was generated from the following files:
Ieee80211VisualizerBase.h
Ieee80211VisualizerBase.cc