INET Framework for OMNeT++/OMNEST: inet::bgp::BgpUpdatePathAttributesMultiExitDisc Class Reference
inet::bgp::BgpUpdatePathAttributesMultiExitDisc Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:157 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpUpdatePathAttributesMultiExitDisc ()
BgpUpdatePathAttributesMultiExitDisc (const BgpUpdatePathAttributesMultiExitDisc &other)
virtual ~BgpUpdatePathAttributesMultiExitDisc ()
BgpUpdatePathAttributesMultiExitDisc & operator= (const BgpUpdatePathAttributesMultiExitDisc &other)
virtual BgpUpdatePathAttributesMultiExitDisc * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getValue () const
virtual void setValue (uint32_t value)
Public Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
BgpUpdatePathAttributes ()
BgpUpdatePathAttributes (const BgpUpdatePathAttributes &other)
virtual ~BgpUpdatePathAttributes ()
BgpUpdatePathAttributes & operator= (const BgpUpdatePathAttributes &other)
virtual bool getOptionalBit () const
virtual void setOptionalBit (bool optionalBit)
virtual bool getTransitiveBit () const
virtual void setTransitiveBit (bool transitiveBit)
virtual bool getPartialBit () const
virtual void setPartialBit (bool partialBit)
virtual bool getExtendedLengthBit () const
virtual void setExtendedLengthBit (bool extendedLengthBit)
virtual unsigned short getReserved () const
virtual void setReserved (unsigned short reserved)
virtual BgpUpdateAttributeTypeCode getTypeCode () const
virtual void setTypeCode (BgpUpdateAttributeTypeCode typeCode)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const BgpUpdatePathAttributesMultiExitDisc &)=delete
Protected Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
bool operator== (const BgpUpdatePathAttributes &)=delete
Protected Attributes
uint32_t value = 0
Protected Attributes inherited from inet::bgp::BgpUpdatePathAttributes
bool optionalBit = false
bool transitiveBit = false
bool partialBit = false
bool extendedLengthBit = false
unsigned short reserved = 0
BgpUpdateAttributeTypeCode typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1)
unsigned short length = 0
Private Member Functions
void copy (const BgpUpdatePathAttributesMultiExitDisc &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:157 by opp_msgtool.
//MULTI_EXIT_DISC (RFC4271 Section 4.3, Type code 4):
class BgpUpdatePathAttributesMultiExitDisc extends BgpUpdatePathAttributes
{
    typeCode = MULTI_EXIT_DISC;
    optionalBit = true;
    transitiveBit = false;
    length = 4;
    uint32_t value;
}
Constructor & Destructor Documentation
BgpUpdatePathAttributesMultiExitDisc() [1/2]
inet::bgp::BgpUpdatePathAttributesMultiExitDisc::BgpUpdatePathAttributesMultiExitDisc ()
BgpUpdatePathAttributesMultiExitDisc() [2/2]
inet::bgp::BgpUpdatePathAttributesMultiExitDisc::BgpUpdatePathAttributesMultiExitDisc (const BgpUpdatePathAttributesMultiExitDisc & other)
~BgpUpdatePathAttributesMultiExitDisc()
virtual inet::bgp::BgpUpdatePathAttributesMultiExitDisc::~BgpUpdatePathAttributesMultiExitDisc () virtual
Member Function Documentation
copy()
void inet::bgp::BgpUpdatePathAttributesMultiExitDisc::copy (const BgpUpdatePathAttributesMultiExitDisc & other) private
dup()
virtual BgpUpdatePathAttributesMultiExitDisc* inet::bgp::BgpUpdatePathAttributesMultiExitDisc::dup () const inline override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
 {return new BgpUpdatePathAttributesMultiExitDisc(*this);}
getValue()
virtual uint32_t inet::bgp::BgpUpdatePathAttributesMultiExitDisc::getValue () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
operator=()
BgpUpdatePathAttributesMultiExitDisc& inet::bgp::BgpUpdatePathAttributesMultiExitDisc::operator= (const BgpUpdatePathAttributesMultiExitDisc & other)
operator==()
bool inet::bgp::BgpUpdatePathAttributesMultiExitDisc::operator== (const BgpUpdatePathAttributesMultiExitDisc &) protected delete
parsimPack()
virtual void inet::bgp::BgpUpdatePathAttributesMultiExitDisc::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpUpdatePathAttributesMultiExitDisc::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimUnpacking().
setValue()
virtual void inet::bgp::BgpUpdatePathAttributesMultiExitDisc::setValue (uint32_t value) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
value
uint32_t inet::bgp::BgpUpdatePathAttributesMultiExitDisc::value = 0 protected
The documentation for this class was generated from the following file:
BgpHeader_m.h