INET Framework for OMNeT++/OMNEST: inet::FindModule< T > Class Template Reference
inet::FindModule< T > Class Template Reference
Provides method templates to find omnet modules.
#include <FindModule.h>
Static Public Member Functions
static T findSubModule (const cModule *const top)
Returns a pointer to a sub module of the passed module with the type of this template.
static T findGlobalModule ()
Returns a pointer to the module with the type of this template.
static cModule * findHost (cModule *m)
Returns a pointer to the host module of the passed module.
static cModule * findNetwork (cModule *m)
static const cModule * findHost (const cModule *const m)
static const cModule * findNetwork (const cModule *const m)
Detailed Description
template<typename T = cModule *const>
class inet::FindModule< T >
Provides method templates to find omnet modules.
Member Function Documentation
findGlobalModule()
template<typename T = cModule *const> static T inet::FindModule< T >::findGlobalModule () inline static
Returns a pointer to the module with the type of this template.
Returns nullptr if no module of this type could be found.
     {
         return findSubModule(getSimulation()->getSystemModule());
     }
findHost() [1/2]
template<typename T = cModule *const> static cModule* inet::FindModule< T >::findHost (cModule * m) inline static
Returns a pointer to the host module of the passed module.
Assumes that every host module is a direct sub module of the simulation.
     {
         return findContainingNode(m);
     }
Referenced by inet::FindModule< T >::findNetwork(), inet::LMac::findNewSlot(), and inet::LMac::handleSelfMessage().
findHost() [2/2]
template<typename T = cModule *const> static const cModule* inet::FindModule< T >::findHost (const cModule *const m) inline static
     {
         return const_cast<cModule *>(findContainingNode(m));
     }
findNetwork() [1/2]
template<typename T = cModule *const> static cModule* inet::FindModule< T >::findNetwork (cModule * m) inline static
     {
         cModule *node = findHost(m);
         return node ? node->getParentModule() : node;
     }
findNetwork() [2/2]
template<typename T = cModule *const> static const cModule* inet::FindModule< T >::findNetwork (const cModule *const m) inline static
     {
         const cModule *node = findHost(m);
         return node ? node->getParentModule() : node;
     }
findSubModule()
template<typename T = cModule *const> static T inet::FindModule< T >::findSubModule (const cModule *const top) inline static
Returns a pointer to a sub module of the passed module with the type of this template.
Returns nullptr if no matching submodule could be found.
     {
         for (cModule::SubmoduleIterator i(top); !i.end(); i++) {
             cModule *const sub = *i;
             // this allows also a return type of read only pointer: const cModule *const
             T dCastRet = dynamic_cast<T>(sub);
             if (dCastRet != nullptr)
                 return dCastRet;
             // this allows also a return type of read only pointer: const cModule *const
             T recFnd = findSubModule(sub);
             if (recFnd != nullptr)
                 return recFnd;
         }
         return nullptr;
     }
Referenced by inet::FindModule< T >::findGlobalModule(), and inet::AccessModuleWrap< T >::get().
The documentation for this class was generated from the following file:
FindModule.h