INET Framework for OMNeT++/OMNEST: inet::ieee80211::IContention::ICallback Class Reference
inet::ieee80211::IContention::ICallback Class Reference abstract
#include <IContention.h>
Public Member Functions
~ICallback ()
virtual void expectedChannelAccess (simtime_t time)=0
virtual void channelAccessGranted ()=0
Constructor & Destructor Documentation
~ICallback()
inet::ieee80211::IContention::ICallback::~ICallback () inline
 {}
Member Function Documentation
channelAccessGranted()
virtual void inet::ieee80211::IContention::ICallback::channelAccessGranted () pure virtual
Implemented in inet::ieee80211::Edcaf, and inet::ieee80211::Dcaf.
Referenced by inet::ieee80211::Contention::handleMessage().
expectedChannelAccess()
virtual void inet::ieee80211::IContention::ICallback::expectedChannelAccess (simtime_t time) pure virtual
Implemented in inet::ieee80211::Edcaf, and inet::ieee80211::Dcaf.
Referenced by inet::ieee80211::Contention::cancelTransmissionRequest(), and inet::ieee80211::Contention::scheduleTransmissionRequestFor().
The documentation for this class was generated from the following file:
IContention.h