INET Framework for OMNeT++/OMNEST: inet::queueing::ActivePacketSource Class Reference
inet::queueing::ActivePacketSource Class Reference
#include <ActivePacketSource.h>
Public Member Functions
virtual ~ActivePacketSource ()
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::ClockUserModuleMixin< ActivePacketSourceBase >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::queueing::ActivePacketSourceBase
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void scheduleProductionTimer (double delay)
virtual void producePacket ()
Protected Member Functions inherited from inet::queueing::PacketSourceBase
virtual const char * createPacketName (const Ptr< const Chunk > &data) const
virtual Ptr< Chunk > createPacketContent () const
virtual Packet * createPacket ()
virtual const cModule * findContainingApplication () const
virtual const cModule * getContainingApplication () const
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
cPar * productionIntervalParameter = nullptr
ClockEvent * productionTimer = nullptr
bool scheduleForAbsoluteTime = false
Protected Attributes inherited from inet::queueing::ActivePacketSourceBase
cGate * outputGate = nullptr
IPassivePacketSink * consumer = nullptr
Protected Attributes inherited from inet::queueing::PacketSourceBase
const char * packetNameFormat = nullptr
const char * packetRepresentation = nullptr
cPar * packetLengthParameter = nullptr
cPar * packetDataParameter = nullptr
bool attachCreationTimeTag = false
bool attachIdentityTag = false
bool attachDirectionTag = false
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Constructor & Destructor Documentation
~ActivePacketSource()
virtual inet::queueing::ActivePacketSource::~ActivePacketSource () inline virtual
 { cancelAndDeleteClockEvent(productionTimer); }
Member Function Documentation
handleCanPushPacketChanged()
void inet::queueing::ActivePacketSource::handleCanPushPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
This method is called, for example, when a new packet can be inserted into a queue. It allows the source to push a new packet into the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
 {
     Enter_Method("handleCanPushPacketChanged");
     if (!productionTimer->isScheduled() && (consumer == nullptr || consumer->canPushSomePacket(outputGate->getPathEndGate()))) {
         double offset = par("initialProductionOffset");
         if (offset != 0)
             scheduleProductionTimer(offset);
         else {
             scheduleProductionTimer(productionIntervalParameter->doubleValue());
             producePacket();
         }
     }
 }
handleMessage()
void inet::queueing::ActivePacketSource::handleMessage (cMessage * message) override protected virtual
 {
     if (message == productionTimer) {
         if (consumer == nullptr || consumer->canPushSomePacket(outputGate->getPathEndGate())) {
             scheduleProductionTimer(productionIntervalParameter->doubleValue());
             producePacket();
         }
     }
     else
         throw cRuntimeError("Unknown message");
 }
handlePushPacketProcessed()
void inet::queueing::ActivePacketSource::handlePushPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pushed packet is failed to be processed successfully. It allows the source to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSource.
 {
     Enter_Method("handlePushPacketProcessed");
 }
initialize()
void inet::queueing::ActivePacketSource::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::ActivePacketSourceBase.
 {
     ClockUserModuleMixin::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         productionIntervalParameter = &par("productionInterval");
         productionTimer = new ClockEvent("ProductionTimer");
         scheduleForAbsoluteTime = par("scheduleForAbsoluteTime");
     }
     else if (stage == INITSTAGE_QUEUEING) {
         if (!productionTimer->isScheduled() && (consumer == nullptr || consumer->canPushSomePacket(outputGate->getPathEndGate()))) {
             double offset = par("initialProductionOffset");
             if (offset != 0)
                 scheduleProductionTimer(offset);
             else {
                 scheduleProductionTimer(productionIntervalParameter->doubleValue());
                 producePacket();
             }
         }
     }
 }
producePacket()
void inet::queueing::ActivePacketSource::producePacket () protected virtual
 {
     auto packet = createPacket();
     EV_INFO << "Producing packet" << EV_FIELD(packet) << EV_ENDL;
     emit(packetPushedSignal, packet);
     pushOrSendPacket(packet, outputGate, consumer);
     updateDisplayString();
 }
Referenced by handleCanPushPacketChanged(), handleMessage(), and initialize().
scheduleProductionTimer()
void inet::queueing::ActivePacketSource::scheduleProductionTimer (double delay) protected virtual
 {
     if (scheduleForAbsoluteTime)
         scheduleClockEventAt(getClockTime() + delay, productionTimer);
     else
         scheduleClockEventAfter(delay, productionTimer);
 }
Referenced by handleCanPushPacketChanged(), handleMessage(), and initialize().
Member Data Documentation
productionIntervalParameter
cPar* inet::queueing::ActivePacketSource::productionIntervalParameter = nullptr protected
Referenced by handleCanPushPacketChanged(), handleMessage(), and initialize().
productionTimer
ClockEvent* inet::queueing::ActivePacketSource::productionTimer = nullptr protected
Referenced by handleCanPushPacketChanged(), handleMessage(), initialize(), and scheduleProductionTimer().
scheduleForAbsoluteTime
bool inet::queueing::ActivePacketSource::scheduleForAbsoluteTime = false protected
Referenced by initialize(), and scheduleProductionTimer().
The documentation for this class was generated from the following files:
ActivePacketSource.h
ActivePacketSource.cc