INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpTopologyTable< IPAddress > Class Template Reference
inet::eigrp::EigrpTopologyTable< IPAddress > Class Template Reference
Class represents EIGRP Topology Table.
#include <EigrpTopologyTable.h>
Public Member Functions
EigrpTopologyTable ()
virtual ~EigrpTopologyTable ()
void addRoute (EigrpRouteSource< IPAddress > *source)
EigrpRouteSource< IPAddress > * findRoute (const IPAddress &routeAddr, const IPAddress &routeMask, const IPAddress &nextHop)
EigrpRouteSource< IPAddress > * findRoute (const IPAddress &routeAddr, const IPAddress &routeMask, int nextHopId)
int getNumRoutes () const
EigrpRouteSource< IPAddress > * getRoute (int k)
EigrpRouteSource< IPAddress > * removeRoute (EigrpRouteSource< IPAddress > *source)
Removes neighbor form the table, but the record still exists.
EigrpRouteSource< IPAddress > * findRouteById (int sourceId)
EigrpRouteSource< IPAddress > * findRouteByNextHop (int routeId, int nextHopId)
EigrpRouteSource< IPAddress > * findOrCreateRoute (const IPAddress &routeAddr, const IPAddress &routeMask, const Ipv4Address &routerId, eigrp::EigrpInterface *eigrpIface, int nextHopId, bool *sourceNew)
Finds and returns source with given address or create one.
void purgeTable ()
Deletes unreachable routes from the topology table.
void delayedRemove (int neighId)
uint64_t findRouteDMin (EigrpRoute< IPAddress > *route)
bool hasFeasibleSuccessor (EigrpRoute< IPAddress > *route, uint64_t &resultDmin)
Finds feasible successor and minimal distance to the destination.
EigrpRouteSource< IPAddress > * getBestSuccessor (EigrpRoute< IPAddress > *route)
Returns best successor to the destination.
EigrpRouteSource< IPAddress > * getBestSuccessorByIf (EigrpRoute< IPAddress > *route, int ifaceId)
Returns first successor on specified interface.
int getNumRouteInfo () const
EigrpRoute< IPAddress > * getRouteInfo (int k)
void addRouteInfo (EigrpRoute< IPAddress > *route)
EigrpRoute< IPAddress > * removeRouteInfo (EigrpRoute< IPAddress > *route)
EigrpRoute< IPAddress > * findRouteInfo (const IPAddress &routeAddr, const IPAddress &routeMask)
EigrpRoute< IPAddress > * findRouteInfoById (int routeId)
Ipv4Address & getRouterId ()
void setRouterId (Ipv4Address &routerID)
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *msg) override
virtual int numInitStages () const override
Private Types
typedef std::vector< EigrpRouteSource< IPAddress > * > RouteVector
typedef std::vector< EigrpRoute< IPAddress > * > RouteInfoVector
Private Member Functions
RouteVector::iterator removeRoute (typename RouteVector::iterator routeIt)
Private Attributes
RouteVector routeVec
Table with routes.
RouteInfoVector routeInfoVec
Table with info about routes.
Ipv4Address routerID
Router ID of this router, number represented as IPv4 address.
int routeIdCounter
Counter for route ID.
int sourceIdCounter
Counter for source ID.
Detailed Description
template<typename IPAddress>
class inet::eigrp::EigrpTopologyTable< IPAddress >
Class represents EIGRP Topology Table.
Member Typedef Documentation
RouteInfoVector
template<typename IPAddress > typedef std::vector<EigrpRoute<IPAddress> *> inet::eigrp::EigrpTopologyTable< IPAddress >::RouteInfoVector private
RouteVector
template<typename IPAddress > typedef std::vector<EigrpRouteSource<IPAddress> *> inet::eigrp::EigrpTopologyTable< IPAddress >::RouteVector private
Constructor & Destructor Documentation
EigrpTopologyTable()
template<typename IPAddress > inet::eigrp::EigrpTopologyTable< IPAddress >::EigrpTopologyTable () inline
 { routeIdCounter = 1; sourceIdCounter = 1; }
~EigrpTopologyTable()
template<typename IPAddress > inet::eigrp::EigrpTopologyTable< IPAddress >::~EigrpTopologyTable virtual
 {
     EigrpRouteSource<IPAddress> *rtSrc;
     EigrpRoute<IPAddress> *rt;
     unsigned i;
     for (i = 0; i < routeVec.size(); i++) {
         rtSrc = routeVec[i];
         routeVec[i] = nullptr;
         delete rtSrc;
     }
     routeVec.clear();
     for (i = 0; i < routeInfoVec.size(); i++) {
         rt = routeInfoVec[i];
         routeInfoVec[i] = nullptr;
         delete rt;
     }
     routeInfoVec.clear();
 }
Member Function Documentation
addRoute()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::addRoute (EigrpRouteSource< IPAddress > * source)
 {
 //    RouteInfoVector::reverse_iterator rit;
     typename RouteVector::iterator it = routeVec.end();
     int routeId = source->getRouteId();
     source->setSourceId(sourceIdCounter);
     sourceIdCounter++;
     // Find last route with routeId
     while (it != routeVec.begin()) {
         --it;
         if ((*it)->getRouteId() == routeId && (*it)->isValid()) {
             break;
         }
     }
     // Insert item after found item
     if (it == routeVec.end())
         routeVec.push_back(source);
     else
         routeVec.insert(it + 1, source);
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
addRouteInfo()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::addRouteInfo (EigrpRoute< IPAddress > * route) inline
 { route->setRouteId(routeIdCounter); routeInfoVec.push_back(route); routeIdCounter++; }
delayedRemove()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::delayedRemove (int neighId)
 {
     typename RouteVector::iterator it;
     for (it = routeVec.begin(); it != routeVec.end();) {
         if ((*it)->getDelayedRemove() == neighId)
             it = removeRoute(it);
         else
             ++it;
     }
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::processAckPacket(), and inet::eigrp::EigrpIpv6Pdm::processAckPacket().
findOrCreateRoute()
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findOrCreateRoute (const IPAddress & routeAddr, const IPAddress & routeMask, const Ipv4Address & routerId, eigrp::EigrpInterface * eigrpIface, int nextHopId, bool * sourceNew)
Finds and returns source with given address or create one.
Parameters
sourceNew return parameter, it is true if source was created. Else false.
 {
     EigrpRoute<IPAddress> *route = nullptr;
     EigrpRouteSource<IPAddress> *source = nullptr;
     (*sourceNew) = false;
     // Find source of route with given next hop ID
     source = findRoute(routeAddr, routeMask, nextHopId);
     if (source == nullptr) {
         if ((route = findRouteInfo(routeAddr, routeMask)) == nullptr) { // Create route
             route = new EigrpRoute<IPAddress>(routeAddr, routeMask);
             addRouteInfo(route);
         }
         // Create source of route
         source = new EigrpRouteSource<IPAddress>(eigrpIface->getInterfaceId(), eigrpIface->getInterfaceName(), nextHopId, route->getRouteId(), route);
         source->setOriginator(routerId);
         (*sourceNew) = true;
         addRoute(source);
     }
     return source;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
findRoute() [1/2]
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findRoute (const IPAddress & routeAddr, const IPAddress & routeMask, const IPAddress & nextHop)
 {
     typename RouteVector::iterator it;
     EigrpRoute<IPAddress> *route;
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         route = (*it)->getRouteInfo();
         if (route->getRouteAddress() == routeAddr && route->getRouteMask() == routeMask &&
             (*it)->getNextHop() == nextHop && (*it)->isValid())
         {
             return *it;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), and inet::eigrp::EigrpIpv6Pdm::processUpdatePacket().
findRoute() [2/2]
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findRoute (const IPAddress & routeAddr, const IPAddress & routeMask, int nextHopId)
 {
     typename RouteVector::iterator it;
     EigrpRoute<IPAddress> *route;
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         route = (*it)->getRouteInfo();
         if (route->getRouteAddress() == routeAddr && route->getRouteMask() == routeMask &&
             (*it)->getNexthopId() == nextHopId && (*it)->isValid())
         {
             return *it;
         }
     }
     return nullptr;
 }
findRouteById()
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findRouteById (int sourceId)
 {
     typename RouteVector::iterator it;
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         if ((*it)->getSourceId() == sourceId && (*it)->isValid())
             return *it;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), and inet::eigrp::EigrpIpv6Pdm::addRoutesToMsg().
findRouteByNextHop()
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findRouteByNextHop (int routeId, int nextHopId)
 {
     typename RouteVector::iterator it;
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         if ((*it)->getRouteId() == routeId && (*it)->getNexthopId() == nextHopId && (*it)->isValid())
             return *it;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
findRouteDMin()
template<typename IPAddress > uint64_t inet::eigrp::EigrpTopologyTable< IPAddress >::findRouteDMin (EigrpRoute< IPAddress > * route)
 {
     uint64_t dmin = eigrp::EigrpMetricHelper::METRIC_INF;
     uint64_t tempD;
     typename RouteVector::iterator it;
     int routeId = route->getRouteId();
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         if ((*it)->getRouteId() == routeId /* do not check FC here */ && (*it)->isValid()) {
             tempD = (*it)->getMetric();
             if (tempD < dmin) {
                 dmin = tempD;
             }
         }
     }
     return dmin;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::findRouteDMin(), and inet::eigrp::EigrpIpv6Pdm::findRouteDMin().
findRouteInfo()
template<typename IPAddress > EigrpRoute< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findRouteInfo (const IPAddress & routeAddr, const IPAddress & routeMask)
 {
     typename RouteInfoVector::iterator it;
     for (it = routeInfoVec.begin(); it != routeInfoVec.end(); it++) {
         if ((*it)->getRouteAddress() == routeAddr && (*it)->getRouteMask() == routeMask)
             return *it;
     }
     return nullptr;
 }
findRouteInfoById()
template<typename IPAddress > EigrpRoute< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::findRouteInfoById (int routeId)
 {
     typename RouteInfoVector::iterator it;
     for (it = routeInfoVec.begin(); it != routeInfoVec.end(); it++) {
         if ((*it)->getRouteId() == routeId)
             return *it;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv6Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv4Pdm::unlockRoutes(), and inet::eigrp::EigrpIpv6Pdm::unlockRoutes().
getBestSuccessor()
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::getBestSuccessor (EigrpRoute< IPAddress > * route)
Returns best successor to the destination.
Finds successor for the route with minimal metric, second key is minimal next hop IP.
 {
     typename RouteVector::iterator it;
     int routeId = route->getRouteId();
     EigrpRouteSource<IPAddress> *tempSrc = nullptr;
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         if ((*it)->getRouteId() == routeId && (*it)->isSuccessor() && (*it)->isValid()) {
             if (tempSrc != nullptr) {
                 if ((*it)->getMetric() < tempSrc->getMetric())
                     tempSrc = *it;
                 else if ((*it)->getMetric() == tempSrc->getMetric() && (*it)->getNextHop() < tempSrc->getNextHop())
                     tempSrc = *it;
             }
             else
                 tempSrc = *it;
         }
     }
     return tempSrc;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::getBestSuccessor(), inet::eigrp::EigrpIpv6Pdm::getBestSuccessor(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getBestSuccessorByIf()
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::getBestSuccessorByIf (EigrpRoute< IPAddress > * route, int ifaceId)
Returns first successor on specified interface.
Finds successor on specified interface with metric equal to Dij (minimal distance)
 {
     typename RouteVector::iterator it;
     int routeId = route->getRouteId();
     uint64_t dij = route->getDij();
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         if ((*it)->getRouteId() == routeId && (*it)->isSuccessor() && (*it)->getMetric() == dij &&
             (*it)->getIfaceId() == ifaceId && (*it)->isValid())
         {
             return *it;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::applySplitHorizon(), and inet::eigrp::EigrpIpv6Pdm::applySplitHorizon().
getNumRouteInfo()
template<typename IPAddress > int inet::eigrp::EigrpTopologyTable< IPAddress >::getNumRouteInfo () const inline
 { return routeInfoVec.size(); }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), and inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths().
getNumRoutes()
template<typename IPAddress > int inet::eigrp::EigrpTopologyTable< IPAddress >::getNumRoutes () const inline
 { return routeVec.size(); }
Referenced by inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getRoute()
template<typename IPAddress > EigrpRouteSource<IPAddress>* inet::eigrp::EigrpTopologyTable< IPAddress >::getRoute (int k) inline
 { return routeVec[k]; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getRouteInfo()
template<typename IPAddress > EigrpRoute<IPAddress>* inet::eigrp::EigrpTopologyTable< IPAddress >::getRouteInfo (int k) inline
 { return routeInfoVec[k]; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), and inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths().
getRouterId()
template<typename IPAddress > Ipv4Address& inet::eigrp::EigrpTopologyTable< IPAddress >::getRouterId () inline
 { return routerID; }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), and inet::eigrp::EigrpIpv6Pdm::processUpdatePacket().
handleMessage()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::handleMessage (cMessage * msg) override protected virtual
 {
     throw cRuntimeError("This module does not process messages");
 }
hasFeasibleSuccessor()
template<typename IPAddress > bool inet::eigrp::EigrpTopologyTable< IPAddress >::hasFeasibleSuccessor (EigrpRoute< IPAddress > * route, uint64_t & resultDmin)
Finds feasible successor and minimal distance to the destination.
@params resultDmin Return value with minimal distance of all FS.
 {
     typename RouteVector::iterator it;
     int routeId = route->getRouteId();
     bool hasFs = false;
     uint64_t tempD;
     resultDmin = eigrp::EigrpMetricHelper::METRIC_INF;
     EV_DEBUG << "EIGRP: Search feasible successor for route " << route->getRouteAddress();
     EV_DEBUG << ", FD is " << route->getFd() << endl;
     for (it = routeVec.begin(); it != routeVec.end(); it++) {
         if ((*it)->getRouteId() == routeId && (*it)->isValid()) {
             EV_DEBUG << "    Next hop " << (*it)->getNextHop();
             EV_DEBUG << " (" << (*it)->getMetric() << "/" << (*it)->getRd() << ") ";
             tempD = (*it)->getMetric();
             if (tempD < resultDmin) {
                 hasFs = false; // FS must have minimal distance
                 resultDmin = tempD;
             }
             if ((*it)->getRd() < route->getFd() && tempD == resultDmin) {
                 EV_DEBUG << "satisfies FC" << endl;
                 hasFs = true;
             }
             else
                 EV_DEBUG << "not satisfies FC" << endl;
         }
     }
     if (hasFs)
         EV_DEBUG << "    FS found, dmin is " << resultDmin << endl;
     else
         EV_DEBUG << "    FS not found, dmin is " << resultDmin << endl;
     return hasFs;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::hasFeasibleSuccessor(), and inet::eigrp::EigrpIpv6Pdm::hasFeasibleSuccessor().
initialize()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_ROUTING_PROTOCOLS) {
         // TODO
         WATCH(routerID);
         WATCH_PTRVECTOR(routeVec);
         #ifdef EIGRP_TT_DEBUG
         WATCH_PTRVECTOR(routeInfoVec);
         #endif
     }
 }
numInitStages()
template<typename IPAddress > virtual int inet::eigrp::EigrpTopologyTable< IPAddress >::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
purgeTable()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::purgeTable
Deletes unreachable routes from the topology table.
Deletes invalid sources.
 {
     typename RouteVector::iterator it;
     for (it = routeVec.begin(); it != routeVec.end();) {
         if (!(*it)->isValid()) { // Remove invalid source from TT
             it = removeRoute(it);
         }
         else
             ++it;
     }
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), inet::eigrp::EigrpIpv6Pdm::processHelloPacket(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processQueryPacket(), inet::eigrp::EigrpIpv6Pdm::processQueryPacket(), inet::eigrp::EigrpIpv4Pdm::processReplyPacket(), inet::eigrp::EigrpIpv6Pdm::processReplyPacket(), inet::eigrp::EigrpIpv4Pdm::processTimer(), inet::eigrp::EigrpIpv6Pdm::processTimer(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), and inet::eigrp::EigrpIpv6Pdm::processUpdatePacket().
removeRoute() [1/2]
template<typename IPAddress > EigrpRouteSource< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::removeRoute (EigrpRouteSource< IPAddress > * source)
Removes neighbor form the table, but the record still exists.
 {
     typename RouteVector::iterator it;
     if ((it = find(routeVec, source)) != routeVec.end()) {
         removeRoute(it);
         return source;
     }
     return nullptr;
 }
removeRoute() [2/2]
template<typename IPAddress > std::vector< EigrpRouteSource< IPAddress > * >::iterator inet::eigrp::EigrpTopologyTable< IPAddress >::removeRoute (typename RouteVector::iterator routeIt) private
 {
     EigrpRoute<IPAddress> *route = nullptr;
     EigrpRouteSource<IPAddress> *source = nullptr;
     source = *routeIt;
     route = source->getRouteInfo();
     EV_DEBUG << "EIGRP: remove route source " << route->getRouteAddress();
     EV_DEBUG << " via " << source->getNextHop() << " from TT" << endl;
     if (route->getRefCnt() == 1 && !route->isActive() && route->getNumSentMsgs() == 0) {
         EV_DEBUG << "EIGRP: remove route info " << route->getRouteAddress() << ", it does not have any source" << endl;
         removeRouteInfo(route);
         delete route;
     }
     else {
         route->decrementRefCnt();
     }
     delete source;
     return routeVec.erase(routeIt);
 }
removeRouteInfo()
template<typename IPAddress > EigrpRoute< IPAddress > * inet::eigrp::EigrpTopologyTable< IPAddress >::removeRouteInfo (EigrpRoute< IPAddress > * route)
 {
     typename RouteInfoVector::iterator it;
     if ((it = find(routeInfoVec, route)) != routeInfoVec.end()) {
         routeInfoVec.erase(it);
         return route;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::unlockRoutes(), and inet::eigrp::EigrpIpv6Pdm::unlockRoutes().
setRouterId()
template<typename IPAddress > void inet::eigrp::EigrpTopologyTable< IPAddress >::setRouterId (Ipv4Address & routerID) inline
 { this->routerID = routerID; }
Referenced by inet::eigrp::EigrpIpv4Pdm::initialize(), inet::eigrp::EigrpIpv4Pdm::setRouterId(), and inet::eigrp::EigrpIpv6Pdm::setRouterId().
Member Data Documentation
routeIdCounter
template<typename IPAddress > int inet::eigrp::EigrpTopologyTable< IPAddress >::routeIdCounter private
Counter for route ID.
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::addRouteInfo(), and inet::eigrp::EigrpTopologyTable< Ipv4Address >::EigrpTopologyTable().
routeInfoVec
template<typename IPAddress > RouteInfoVector inet::eigrp::EigrpTopologyTable< IPAddress >::routeInfoVec private
Table with info about routes.
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::addRouteInfo(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getNumRouteInfo(), and inet::eigrp::EigrpTopologyTable< Ipv4Address >::getRouteInfo().
routerID
template<typename IPAddress > Ipv4Address inet::eigrp::EigrpTopologyTable< IPAddress >::routerID private
Router ID of this router, number represented as IPv4 address.
INDEPENDENT on routed protocol (Ipv4/IPv6)!
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::getRouterId(), and inet::eigrp::EigrpTopologyTable< Ipv4Address >::setRouterId().
routeVec
template<typename IPAddress > RouteVector inet::eigrp::EigrpTopologyTable< IPAddress >::routeVec private
Table with routes.
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::getNumRoutes(), and inet::eigrp::EigrpTopologyTable< Ipv4Address >::getRoute().
sourceIdCounter
template<typename IPAddress > int inet::eigrp::EigrpTopologyTable< IPAddress >::sourceIdCounter private
Counter for source ID.
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::EigrpTopologyTable().
The documentation for this class was generated from the following files:
EigrpTopologyTable.h
EigrpTopologyTable.cc