INET Framework for OMNeT++/OMNEST: inet::SharingRegionTagSet Class Reference
inet::SharingRegionTagSet Class Reference
This class maintains a set of tags each referring to a specific region.
#include <SharingRegionTagSet.h>
Classes
class RegionTag
Region tags keep a tag for a specific range identified by offset and length.
Public Types
typedef RegionTag< TagBase > TagBaseRegionTag
Public Member Functions
Constructors and operators
SharingRegionTagSet ()
SharingRegionTagSet (const SharingRegionTagSet &other)
SharingRegionTagSet (SharingRegionTagSet &&other)
SharingRegionTagSet & operator= (const SharingRegionTagSet &other)
SharingRegionTagSet & operator= (SharingRegionTagSet &&other)
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
Type independent functions
int getNumTags () const
Returns the number of tags.
const Ptr< const TagBase > & getTag (int index) const
Returns the shared tag at the given index.
const Ptr< TagBase > getTagForUpdate (int index)
Returns the exclusively owned tag at the given index for update.
const RegionTag< TagBase > & getRegionTag (int index) const
Returns the shared region tag at the given index.
const RegionTag< TagBase > getRegionTagForUpdate (int index)
Returns the exclusively owned region tag at the given index.
void clearTags (b offset, b length)
Clears the set of tags in the given region.
void moveTags (b shift)
Moves all tags with the provided shift.
void moveTags (b offset, b length, b shift)
Moves the region of tags with the provided shift.
void copyTags (const SharingRegionTagSet &source, b sourceOffset, b offset, b length)
Copies the set of tags from the source region to the provided region.
Type dependent functions
template<typename T >
const Ptr< const T > findTag (b offset, b length) const
Returns the shared tag of the provided type and range, or returns nullptr if no such tag is found.
template<typename T >
const Ptr< T > findTagForUpdate (b offset, b length)
Returns the exclusively owned tag of the provided type and range for update, or returns nullptr if no such tag is found.
template<typename T >
const Ptr< const T > getTag (b offset, b length) const
Returns the shared tag of the provided type and range, or throws an exception if no such tag is found.
template<typename T >
const Ptr< T > getTagForUpdate (b offset, b length)
Returns the exclusively owned tag of the provided type and range for update, or throws an exception if no such tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Calls the given function with all the shared tags of the provided type and range.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Calls the given function with all the exclusively owned tags of the provided type and range for update.
template<typename T >
std::vector< RegionTag< T > > getAllTags (b offset, b length) const
Returns all the shared tags of the provided type and range.
template<typename T >
std::vector< RegionTag< T > > getAllTagsForUpdate (b offset, b length)
Returns all the exclusively owned tags of the provided type and range for update.
template<typename T >
const Ptr< T > addTag (b offset, b length)
Returns a newly added exclusively owned tag of the provided type and range for update, or throws an exception if such a tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset, b length)
Returns a newly added exclusively owned tag of the provided type and range if absent, or returns the tag that is already present for update.
template<typename T >
std::vector< RegionTag< T > > addTagsWhereAbsent (b offset, b length)
Returns the newly added exclusively owned tags of the provided type and range for update where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the tag of the provided type and range and returns it for update, or throws an exception if no such tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the tag of the provided type and range if present and returns it for update, or returns nullptr if no such tag is found.
template<typename T >
std::vector< RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all tags of the provided type and range and returns them for update.
Protected Member Functions
void setTag (int index, const Ptr< const TagBase > &tag)
void addTag (b offset, b length, const Ptr< const TagBase > &tag)
std::vector< SharingRegionTagSet::RegionTag< TagBase > > addTagsWhereAbsent (const std::type_info &typeInfo, b offset, b length, const Ptr< const TagBase > &tag)
const Ptr< TagBase > removeTag (int index)
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const TagBase > &)> f) const
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< TagBase > &)> f)
void splitTags (b offset, std::function< bool(const TagBase *)> f=[](const TagBase *) { return true;})
template<typename T >
void splitTags (b offset)
int getTagIndex (const std::type_info &typeInfo, b offset, b length) const
template<typename T >
int getTagIndex (b offset, b length) const
void ensureTagsVectorAllocated ()
void prepareTagsVectorForUpdate ()
void sortTagsVector ()
Protected Attributes
Ptr< SharedVector< RegionTag< TagBase > > > regionTags
Detailed Description
This class maintains a set of tags each referring to a specific region.
Regions are identified by their offset and length, and they are not allowed to overlap. Tags are usually small data strcutures that hold some relevant information. Tags are identified by their type, which means that this class supports adding the same tag type for a specific region only once. Tags are shared between other instances of this class. Tags can be changed with a copy-on-write mechanism.
Member Typedef Documentation
TagBaseRegionTag
typedef RegionTag<TagBase> inet::SharingRegionTagSet::TagBaseRegionTag
Constructor & Destructor Documentation
SharingRegionTagSet() [1/3]
inet::SharingRegionTagSet::SharingRegionTagSet () inline
 : regionTags(nullptr) {}
SharingRegionTagSet() [2/3]
inet::SharingRegionTagSet::SharingRegionTagSet (const SharingRegionTagSet & other) inline
 : regionTags(other.regionTags) {}
SharingRegionTagSet() [3/3]
inet::SharingRegionTagSet::SharingRegionTagSet (SharingRegionTagSet && other) inline
 : regionTags(other.regionTags) { other.regionTags = nullptr; }
Member Function Documentation
addTag() [1/2]
template<typename T > const Ptr< T > inet::SharingRegionTagSet::addTag (b offset, b length) inline
Returns a newly added exclusively owned tag of the provided type and range for update, or throws an exception if such a tag is already present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     if (index != -1)
         throw cRuntimeError("Tag '%s' is present", opp_typename(typeid(T)));
     Ptr<T> tag = makeShared<T>();
     addTag(offset, length, tag);
     return tag;
 }
addTag() [2/2]
void inet::SharingRegionTagSet::addTag (b offset, b length, const Ptr< const TagBase > & tag) protected
 {
     ensureTagsVectorAllocated();
     prepareTagsVectorForUpdate();
     regionTags->push_back(RegionTag<TagBase>(offset, length, tag));
 }
Referenced by inet::Packet::addRegionTag(), inet::Chunk::addTag(), copyTags(), and parsimUnpack().
addTagIfAbsent()
template<typename T > const Ptr< T > inet::SharingRegionTagSet::addTagIfAbsent (b offset, b length) inline
Returns a newly added exclusively owned tag of the provided type and range if absent, or returns the tag that is already present for update.
 {
     SELFDOC_FUNCTION_T;
     const Ptr<T>& tag = findTagForUpdate<T>(offset, length);
     if (tag != nullptr)
         return tag;
     else {
         const Ptr<T>& tag = makeShared<T>();
         addTag(offset, length, tag);
         return tag;
     }
 }
Referenced by inet::Packet::addRegionTagIfAbsent(), and inet::Chunk::addTagIfAbsent().
addTagsWhereAbsent() [1/2]
template<typename T > std::vector< SharingRegionTagSet::RegionTag< T > > inet::SharingRegionTagSet::addTagsWhereAbsent (b offset, b length) inline
Returns the newly added exclusively owned tags of the provided type and range for update where the tag is absent.
 {
     SELFDOC_FUNCTION_T;
     splitTags<T>(offset);
     splitTags<T>(offset + length);
     std::vector<SharingRegionTagSet::RegionTag<T>> result;
     for (auto& region : addTagsWhereAbsent(typeid(T), offset, length, makeShared<T>()))
         result.push_back(RegionTag<T>(region.getOffset(), region.getLength(), staticPtrCast<const T>(region.getTag())));
     return result;
 }
addTagsWhereAbsent() [2/2]
std::vector< SharingRegionTagSet::RegionTag< TagBase > > inet::SharingRegionTagSet::addTagsWhereAbsent (const std::type_info & typeInfo, b offset, b length, const Ptr< const TagBase > & tag) protected
 {
     std::vector<SharingRegionTagSet::RegionTag<TagBase>> result;
     b endOffset = offset + length;
     b o = offset;
     if (regionTags != nullptr) {
         for (auto& regionTag : *regionTags) {
             auto tag = regionTag.getTag();
             auto tagObject = tag.get();
             if (typeInfo == typeid(*tagObject)) {
                 b l = regionTag.getStartOffset() - o;
                 if (l > b(0)) {
                     if (l > endOffset - o)
                         l = endOffset - o;
                     result.push_back(RegionTag<TagBase>(o, l, tag->dupShared()));
                     o += l;
                 }
                 if (regionTag.getEndOffset() > o)
                     o = regionTag.getEndOffset();
                 if (o >= endOffset)
                     break;
             }
         }
     }
     b l = endOffset - o;
     if (l > b(0))
         result.push_back(RegionTag<TagBase>(o, l, tag->dupShared()));
     if (!result.empty()) {
         ensureTagsVectorAllocated();
         prepareTagsVectorForUpdate();
         for (auto& regionTag : result)
             regionTags->push_back(RegionTag<TagBase>(regionTag.getOffset(), regionTag.getLength(), regionTag.getTag()));
         sortTagsVector();
     }
     return result;
 }
Referenced by inet::Packet::addRegionTagsWhereAbsent(), and inet::Chunk::addTagsWhereAbsent().
clearTags()
void inet::SharingRegionTagSet::clearTags (b offset, b length)
Clears the set of tags in the given region.
 {
     if (regionTags != nullptr) {
         bool changed = false;
         b clearStartOffset = offset;
         b clearEndOffset = offset + length;
         for (int i = 0; i < (int)regionTags->size(); i++) {
             auto& regionTag = (*regionTags)[i];
             if (clearEndOffset <= regionTag.getStartOffset() || regionTag.getEndOffset() <= clearStartOffset)
                 // no intersection
                 continue;
             else if (clearStartOffset <= regionTag.getStartOffset() && regionTag.getEndOffset() <= clearEndOffset) {
                 // clear totally covers region
                 prepareTagsVectorForUpdate();
                 regionTags->erase(regionTags->begin() + i--);
                 changed = true;
             }
             else if (regionTag.getStartOffset() < clearStartOffset && clearEndOffset < regionTag.getEndOffset()) {
                 // clear splits region into two parts
                 prepareTagsVectorForUpdate();
                 auto& regionTag = (*regionTags)[i];
                 auto startOffset = regionTag.getStartOffset();
                 regionTag.setLength(regionTag.getEndOffset() - clearEndOffset);
                 regionTag.setOffset(clearEndOffset);
                 RegionTag<TagBase> previousRegionTag(regionTag);
                 previousRegionTag.setOffset(startOffset);
                 previousRegionTag.setLength(clearStartOffset - startOffset);
                 regionTags->insert(regionTags->begin() + i++, previousRegionTag);
                 changed = true;
             }
             else if (regionTag.getEndOffset() <= clearEndOffset) {
                 // clear cuts end of region
                 prepareTagsVectorForUpdate();
                 auto& regionTag = (*regionTags)[i];
                 regionTag.setLength(clearStartOffset - regionTag.getStartOffset());
                 changed = true;
             }
             else if (clearStartOffset <= regionTag.getStartOffset()) {
                 // clear cuts beginning of region
                 prepareTagsVectorForUpdate();
                 auto& regionTag = (*regionTags)[i];
                 regionTag.setLength(regionTag.getEndOffset() - clearEndOffset);
                 regionTag.setOffset(clearEndOffset);
                 changed = true;
             }
             else
                 ASSERT(false);
         }
         if (changed)
             sortTagsVector();
     }
 }
Referenced by inet::Packet::clearRegionTags(), inet::Chunk::clearTags(), copyTags(), moveTags(), inet::Chunk::removeAtBack(), and inet::Chunk::removeAtFront().
copyTags()
void inet::SharingRegionTagSet::copyTags (const SharingRegionTagSet & source, b sourceOffset, b offset, b length)
Copies the set of tags from the source region to the provided region.
 {
     auto shift = offset - sourceOffset;
     clearTags(offset, length);
     source.mapAllTags(sourceOffset, length, [&] (b o, b l, const Ptr<const TagBase>& tag) {
         b startOffset = o < sourceOffset ? sourceOffset : o;
         b endOffset = o + l > sourceOffset + length ? sourceOffset + length : o + l;
         addTag(startOffset + shift, endOffset - startOffset, tag);
     });
 }
Referenced by inet::Packet::copyRegionTags(), inet::Chunk::copyTags(), inet::Chunk::insertAt(), inet::Chunk::insertAtBack(), inet::Chunk::insertAtFront(), and inet::SliceChunk::SliceChunk().
ensureTagsVectorAllocated()
void inet::SharingRegionTagSet::ensureTagsVectorAllocated () protected
 {
     if (regionTags == nullptr) {
         regionTags = makeShared<SharedVector<RegionTag<TagBase>>>();
         regionTags->reserve(16);
     }
 }
Referenced by addTag(), and addTagsWhereAbsent().
findTag()
template<typename T > const Ptr< const T > inet::SharingRegionTagSet::findTag (b offset, b length) const inline
Returns the shared tag of the provided type and range, or returns nullptr if no such tag is found.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     return index == -1 ? nullptr : staticPtrCast<const T>(getTag(index));
 }
Referenced by inet::Packet::findRegionTag(), and inet::Chunk::findTag().
findTagForUpdate()
template<typename T > const Ptr< T > inet::SharingRegionTagSet::findTagForUpdate (b offset, b length) inline
Returns the exclusively owned tag of the provided type and range for update, or returns nullptr if no such tag is found.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     return index == -1 ? nullptr : staticPtrCast<T>(getTagForUpdate(index));
 }
getAllTags()
template<typename T > std::vector< SharingRegionTagSet::RegionTag< T > > inet::SharingRegionTagSet::getAllTags (b offset, b length) const inline
Returns all the shared tags of the provided type and range.
 {
     SELFDOC_FUNCTION_T;
     std::vector<SharingRegionTagSet::RegionTag<T>> result;
     mapAllTags<T>(offset, length, [&] (b o, b l, const Ptr<const T>& tag) {
         result.push_back(RegionTag<T>(o, l, staticPtrCast<const T>(tag)));
     });
     return result;
 }
Referenced by inet::Packet::getAllRegionTags(), and inet::Chunk::getAllTags().
getAllTagsForUpdate()
template<typename T > std::vector< SharingRegionTagSet::RegionTag< T > > inet::SharingRegionTagSet::getAllTagsForUpdate (b offset, b length) inline
Returns all the exclusively owned tags of the provided type and range for update.
 {
     SELFDOC_FUNCTION_T;
     std::vector<SharingRegionTagSet::RegionTag<T>> result;
     mapAllTagsForUpdate<T>(offset, length, [&] (b o, b l, const Ptr<T>& tag) {
         result.push_back(RegionTag<T>(o, l, staticPtrCast<T>(tag)));
     });
     return result;
 }
Referenced by inet::Packet::getAllRegionTagsForUpdate(), and inet::Chunk::getAllTagsForUpdate().
getNumTags()
int inet::SharingRegionTagSet::getNumTags () const inline
Returns the number of tags.
 {
     return regionTags == nullptr ? 0 : regionTags->size();
 }
Referenced by inet::Packet::forEachChild(), inet::Chunk::forEachChild(), inet::Packet::getNumRegionTags(), inet::Chunk::getNumTags(), and parsimPack().
getRegionTag()
const SharingRegionTagSet::RegionTag< TagBase > & inet::SharingRegionTagSet::getRegionTag (int index) const inline
Returns the shared region tag at the given index.
 {
     return (*regionTags)[index];
 }
Referenced by inet::Packet::_getRegionTag(), and inet::Chunk::_getTag().
getRegionTagForUpdate()
const SharingRegionTagSet::RegionTag< TagBase > inet::SharingRegionTagSet::getRegionTagForUpdate (int index) inline
Returns the exclusively owned region tag at the given index.
 {
     const auto& regionTag = getRegionTag(index);
     prepareTagsVectorForUpdate();
     if (regionTag.getTag().use_count() != 1)
         setTag(index, regionTag.getTag()->dupShared());
     return regionTag;
 }
getTag() [1/2]
template<typename T > const Ptr< const T > inet::SharingRegionTagSet::getTag (b offset, b length) const inline
Returns the shared tag of the provided type and range, or throws an exception if no such tag is found.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return staticPtrCast<const T>(getTag(index));
 }
getTag() [2/2]
const Ptr< const TagBase > & inet::SharingRegionTagSet::getTag (int index) const inline
Returns the shared tag at the given index.
 {
     return getRegionTag(index).getTag();
 }
Referenced by inet::Packet::forEachChild(), inet::Chunk::forEachChild(), inet::Packet::getRegionTag(), and inet::Chunk::getTag().
getTagForUpdate() [1/2]
template<typename T > const Ptr< T > inet::SharingRegionTagSet::getTagForUpdate (b offset, b length) inline
Returns the exclusively owned tag of the provided type and range for update, or throws an exception if no such tag is found.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return staticPtrCast<T>(getTagForUpdate(index));
 }
getTagForUpdate() [2/2]
const Ptr< TagBase > inet::SharingRegionTagSet::getTagForUpdate (int index) inline
Returns the exclusively owned tag at the given index for update.
 {
     return constPtrCast<TagBase>(getRegionTagForUpdate(index).getTag());
 }
Referenced by mapAllTagsForUpdate(), and removeTag().
getTagIndex() [1/2]
template<typename T > int inet::SharingRegionTagSet::getTagIndex (b offset, b length) const inline protected
 {
     SELFDOC_FUNCTION_T;
     return getTagIndex(typeid(T), offset, length);
 }
getTagIndex() [2/2]
int inet::SharingRegionTagSet::getTagIndex (const std::type_info & typeInfo, b offset, b length) const protected
 {
     if (regionTags == nullptr)
         return -1;
     else {
         int numRegionTags = regionTags->size();
         b getStartOffset = offset;
         b getEndOffset = offset + length;
         for (int index = 0; index < numRegionTags; index++) {
             auto& regionTag = (*regionTags)[index];
             const auto& tag = regionTag.getTag();
             auto tagObject = tag.get();
             if (typeInfo != typeid(*tagObject) || getEndOffset <= regionTag.getStartOffset() || regionTag.getEndOffset() <= getStartOffset)
                 continue;
             else if (regionTag.getOffset() == offset && regionTag.getLength() == length)
                 return index;
             else
                 throw cRuntimeError("Overlapping tag is present");
         }
         return -1;
     }
 }
mapAllTags() [1/2]
template<typename T > void inet::SharingRegionTagSet::mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const inline
Calls the given function with all the shared tags of the provided type and range.
 {
     SELFDOC_FUNCTION_T;
     mapAllTags(offset, length, [&] (b o, b l, const Ptr<const TagBase>& tag) {
         auto tagObject = tag.get();
         if (typeid(*tagObject) == typeid(T))
             f(o, l, staticPtrCast<const T>(tag));
     });
 }
mapAllTags() [2/2]
void inet::SharingRegionTagSet::mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const TagBase > &)> f) const protected
 {
     if (regionTags != nullptr) {
         b startOffset = offset;
         b endOffset = offset + length;
         for (auto& regionTag : *regionTags) {
             if (endOffset <= regionTag.getStartOffset() || regionTag.getEndOffset() <= startOffset)
                 // no intersection
                 continue;
             else if (startOffset <= regionTag.getStartOffset() && regionTag.getEndOffset() <= endOffset)
                 // totally covers region
                 f(regionTag.getOffset(), regionTag.getLength(), regionTag.getTag());
             else if (regionTag.getStartOffset() < startOffset && endOffset < regionTag.getEndOffset())
                 // splits region into two parts
                 f(startOffset, endOffset - startOffset, regionTag.getTag());
             else if (regionTag.getEndOffset() <= endOffset)
                 // cuts end of region
                 f(startOffset, regionTag.getEndOffset() - startOffset, regionTag.getTag());
             else if (startOffset <= regionTag.getStartOffset())
                 // cuts beginning of region
                 f(regionTag.getStartOffset(), endOffset - regionTag.getStartOffset(), regionTag.getTag());
             else
                 ASSERT(false);
         }
     }
 }
Referenced by copyTags(), inet::Packet::mapAllRegionTags(), and inet::Chunk::mapAllTags().
mapAllTagsForUpdate() [1/2]
template<typename T > void inet::SharingRegionTagSet::mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f) inline
Calls the given function with all the exclusively owned tags of the provided type and range for update.
 {
     SELFDOC_FUNCTION_T;
     splitTags<T>(offset);
     splitTags<T>(offset + length);
     mapAllTagsForUpdate(offset, length, [&] (b o, b l, const Ptr<TagBase>& tag) {
         auto tagObject = tag.get();
         if (typeid(*tagObject) == typeid(T))
             f(o, l, staticPtrCast<T>(tag));
     });
 }
mapAllTagsForUpdate() [2/2]
void inet::SharingRegionTagSet::mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< TagBase > &)> f) protected
 {
     if (regionTags != nullptr) {
         prepareTagsVectorForUpdate();
         b startOffset = offset;
         b endOffset = offset + length;
         for (int i = 0; i < (int)regionTags->size(); i++) {
             const RegionTag<TagBase>& regionTag = (*regionTags)[i];
             if (endOffset <= regionTag.getStartOffset() || regionTag.getEndOffset() <= startOffset)
                 // no intersection
                 continue;
             else if (startOffset <= regionTag.getStartOffset() && regionTag.getEndOffset() <= endOffset)
                 // totally covers region
                 f(regionTag.getOffset(), regionTag.getLength(), getTagForUpdate(i));
             else if (regionTag.getStartOffset() < startOffset && endOffset < regionTag.getEndOffset())
                 // splits region into two parts
                 f(startOffset, endOffset - startOffset, getTagForUpdate(i));
             else if (regionTag.getEndOffset() <= endOffset)
                 // cuts end of region
                 f(startOffset, regionTag.getEndOffset() - startOffset, getTagForUpdate(i));
             else if (startOffset <= regionTag.getStartOffset())
                 // cuts beginning of region
                 f(regionTag.getStartOffset(), endOffset - regionTag.getStartOffset(), getTagForUpdate(i));
             else
                 ASSERT(false);
         }
     }
 }
Referenced by inet::Packet::mapAllRegionTagsForUpdate(), and inet::Chunk::mapAllTagsForUpdate().
moveTags() [1/2]
void inet::SharingRegionTagSet::moveTags (b offset, b length, b shift)
Moves the region of tags with the provided shift.
 {
     if (regionTags != nullptr) {
         prepareTagsVectorForUpdate();
         if (shift > b(0)) {
             splitTags(offset);
             clearTags(offset + length, offset + length + shift);
         }
         else {
             splitTags(offset + length);
             clearTags(offset - shift, offset);
         }
         for (auto& regionTag : *regionTags)
             if (offset <= regionTag.getStartOffset() && regionTag.getEndOffset() <= offset + length)
                 regionTag.setOffset(regionTag.getOffset() + shift);
     }
 }
moveTags() [2/2]
void inet::SharingRegionTagSet::moveTags (b shift)
Moves all tags with the provided shift.
 {
     if (regionTags != nullptr) {
         prepareTagsVectorForUpdate();
         for (auto& regionTag : *regionTags)
             regionTag.setOffset(regionTag.getOffset() + shift);
     }
 }
Referenced by inet::Chunk::insertAt(), inet::Chunk::insertAtFront(), inet::Chunk::removeAt(), and inet::Chunk::removeAtFront().
operator=() [1/2]
SharingRegionTagSet & inet::SharingRegionTagSet::operator= (const SharingRegionTagSet & other) inline
 {
     if (this != &other)
         regionTags = other.regionTags;
     return *this;
 }
operator=() [2/2]
SharingRegionTagSet & inet::SharingRegionTagSet::operator= (SharingRegionTagSet && other) inline
 {
     if (this != &other) {
         regionTags = other.regionTags;
         other.regionTags = nullptr;
     }
     return *this;
 }
parsimPack()
void inet::SharingRegionTagSet::parsimPack (cCommBuffer * buffer) const override virtual
 {
     buffer->pack(getNumTags());
     if (regionTags != nullptr) {
         for (auto regionTag : *regionTags) {
             buffer->pack(regionTag.getOffset().get());
             buffer->pack(regionTag.getLength().get());
             buffer->packObject(const_cast<TagBase *>(regionTag.getTag().get()));
         }
     }
 }
Referenced by inet::Packet::parsimPack(), and inet::Chunk::parsimPack().
parsimUnpack()
void inet::SharingRegionTagSet::parsimUnpack (cCommBuffer * buffer) override virtual
 {
     if (regionTags != nullptr)
         regionTags->clear();
     int size;
     buffer->unpack(size);
     for (int i = 0; i < size; i++) {
         uint64_t offset;
         buffer->unpack(offset);
         uint64_t length;
         buffer->unpack(length);
         auto tag = check_and_cast<TagBase *>(buffer->unpackObject());
         addTag(b(offset), b(length), tag->shared_from_this());
     }
 }
Referenced by inet::Packet::parsimUnpack(), and inet::Chunk::parsimUnpack().
prepareTagsVectorForUpdate()
void inet::SharingRegionTagSet::prepareTagsVectorForUpdate () protected
 {
     if (regionTags.use_count() != 1) {
         const auto& newRegionTags = makeShared<SharedVector<RegionTag<TagBase>>>();
         newRegionTags->insert(newRegionTags->begin(), regionTags->begin(), regionTags->end());
         regionTags = newRegionTags;
     }
 }
Referenced by addTag(), addTagsWhereAbsent(), clearTags(), mapAllTagsForUpdate(), moveTags(), removeTag(), and splitTags().
removeTag() [1/2]
template<typename T > const Ptr< T > inet::SharingRegionTagSet::removeTag (b offset, b length) inline
Removes the tag of the provided type and range and returns it for update, or throws an exception if no such tag is found.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return staticPtrCast<T>(removeTag(index));
 }
removeTag() [2/2]
const Ptr< TagBase > inet::SharingRegionTagSet::removeTag (int index) protected
 {
     prepareTagsVectorForUpdate();
     const Ptr<TagBase> tag = getTagForUpdate(index);
     regionTags->erase(regionTags->begin() + index);
     if (regionTags->size() == 0)
         regionTags = nullptr;
     return constPtrCast<TagBase>(tag);
 }
Referenced by inet::Packet::removeRegionTag(), and inet::Chunk::removeTag().
removeTagIfPresent()
template<typename T > const Ptr< T > inet::SharingRegionTagSet::removeTagIfPresent (b offset, b length) inline
Removes the tag of the provided type and range if present and returns it for update, or returns nullptr if no such tag is found.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>(offset, length);
     return index == -1 ? nullptr : staticPtrCast<T>(removeTag(index));
 }
Referenced by inet::Packet::removeRegionTagIfPresent(), and inet::Chunk::removeTagIfPresent().
removeTagsWherePresent()
template<typename T > std::vector< SharingRegionTagSet::RegionTag< T > > inet::SharingRegionTagSet::removeTagsWherePresent (b offset, b length) inline
Removes and returns all tags of the provided type and range and returns them for update.
 {
     SELFDOC_FUNCTION_T;
     auto result = getAllTags<T>(offset, length);
     clearTags(offset, length);
     return result;
 }
Referenced by inet::Packet::removeRegionTagsWherePresent(), and inet::Chunk::removeTagsWherePresent().
setTag()
void inet::SharingRegionTagSet::setTag (int index, const Ptr< const TagBase > & tag) inline protected
 {
     (*regionTags)[index].setTag(tag);
 }
sortTagsVector()
void inet::SharingRegionTagSet::sortTagsVector () inline protected
 {
     std::sort(regionTags->begin(), regionTags->end());
 }
Referenced by addTagsWhereAbsent(), clearTags(), and splitTags().
splitTags() [1/2]
template<typename T > void inet::SharingRegionTagSet::splitTags (b offset) inline protected
 {
     SELFDOC_FUNCTION_T;
     splitTags(offset, [&] (const TagBase *tag) { return typeid(T) == typeid(*tag); });
 }
splitTags() [2/2]
void inet::SharingRegionTagSet::splitTags (b offset, std::function< bool(const TagBase *)> f = [] (const TagBase *) { return true; }) protected
 {
     if (regionTags != nullptr) {
         std::vector<RegionTag<TagBase>> insertedRegionTags;
         for (auto& regionTag : *regionTags) {
             auto tag = regionTag.getTag();
             auto tagObject = tag.get();
             if (f(tagObject) && regionTag.getStartOffset() < offset && offset < regionTag.getEndOffset()) {
                 prepareTagsVectorForUpdate();
                 RegionTag<TagBase> otherRegionTag(regionTag);
                 otherRegionTag.setOffset(offset);
                 otherRegionTag.setLength(regionTag.getEndOffset() - offset);
                 insertedRegionTags.push_back(otherRegionTag);
                 regionTag.setLength(offset - regionTag.getStartOffset());
             }
         }
         if (!insertedRegionTags.empty()) {
             for (auto regionTag : insertedRegionTags)
                 regionTags->push_back(regionTag);
             sortTagsVector();
         }
     }
 }
Referenced by moveTags().
Member Data Documentation
regionTags
Ptr<SharedVector<RegionTag<TagBase> > > inet::SharingRegionTagSet::regionTags protected
Referenced by addTag(), addTagsWhereAbsent(), clearTags(), ensureTagsVectorAllocated(), getTagIndex(), mapAllTags(), mapAllTagsForUpdate(), moveTags(), operator=(), parsimPack(), parsimUnpack(), prepareTagsVectorForUpdate(), removeTag(), and splitTags().
The documentation for this class was generated from the following files:
SharingRegionTagSet.h
SharingRegionTagSet.cc