INET Framework for OMNeT++/OMNEST: inet::power::IEpEnergyConsumer Class Reference
inet::power::IEpEnergyConsumer Class Reference abstract
This class is an interface that should be implemented by power based energy consumer models to integrate with other parts of the power based energy model.
#include <IEpEnergyConsumer.h>
Public Member Functions
virtual W getPowerConsumption () const =0
Returns the power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergyConsumer
virtual ~IEnergyConsumer ()
virtual IEnergySource * getEnergySource () const =0
Returns the energy source that provides energy for this energy consumer.
Static Public Attributes
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Detailed Description
This class is an interface that should be implemented by power based energy consumer models to integrate with other parts of the power based energy model.
Such an energy consumer model describes the energy consumption over time by providing a function that computes the power consumption in watts.
See the corresponding NED file for more details.
Member Function Documentation
getPowerConsumption()
virtual W inet::power::IEpEnergyConsumer::getPowerConsumption () const pure virtual
Returns the power consumption in the range [0, +infinity).
Implemented in inet::physicallayer::StateBasedEpEnergyConsumer, and inet::power::AlternatingEpEnergyConsumer.
Member Data Documentation
powerConsumptionChangedSignal
simsignal_t inet::power::IEpEnergyConsumer::powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged") static
The signal that is used to publish power consumption changes.
Referenced by inet::power::EpEnergySourceBase::addEnergyConsumer(), inet::power::EpEnergyStorageBase::receiveSignal(), and inet::power::EpEnergySourceBase::removeEnergyConsumer().
The documentation for this class was generated from the following files:
IEpEnergyConsumer.h
IEpEnergyConsumer.cc