INET Framework for OMNeT++/OMNEST: inet::Macho::_StateInstance Class Reference
inet::Macho::_StateInstance Class Reference abstract
#include <Macho.h>
Public Member Functions
virtual ~_StateInstance ()
void entry (_StateInstance &previous, bool first=true)
void exit (_StateInstance &next)
void init (bool history)
void saveHistory (_StateInstance &shallow, _StateInstance &deep)
void setHistorySuper (_StateInstance &deep)
void shutdown ()
void restore (_StateInstance &instance)
virtual ID id ()=0
virtual Key key ()=0
virtual const char * name ()=0
virtual _StateInstance * create (_MachineBase &machine, _StateInstance *parent)=0
virtual void createBox ()=0
virtual void deleteBox ()=0
void setBox (void *box)
bool isChild (const _StateInstance &instance)
_StateSpecification & specification ()
void * box ()
_MachineBase & machine ()
void setHistory (_StateInstance *history) const
_StateInstance * history () const
Protected Member Functions
_StateInstance (_MachineBase &machine, _StateInstance *parent)
Protected Attributes
_MachineBase & myMachine
_StateSpecification * mySpecification
_StateInstance * myHistory
_StateInstance * myParent
void * myBox
void * myBoxPlace
Constructor & Destructor Documentation
_StateInstance()
inet::_StateInstance::_StateInstance (_MachineBase & machine, _StateInstance * parent) protected
     : myMachine(machine)
     , mySpecification(nullptr)
     , myHistory(nullptr)
     , myParent(parent)
     , myBox(nullptr)
     , myBoxPlace(nullptr)
 {
 }
~_StateInstance()
inet::_StateInstance::~_StateInstance () virtual
 {
     if (myBoxPlace)
         ::operator delete(myBoxPlace);
     delete mySpecification;
 }
Member Function Documentation
box()
void* inet::Macho::_StateInstance::box () inline
     {
         assert(myBox);
         return myBox;
     }
Referenced by setBox().
create()
virtual _StateInstance* inet::Macho::_StateInstance::create (_MachineBase & machine, _StateInstance * parent) pure virtual
Implemented in inet::Macho::_SubstateInstance< S >, and inet::Macho::_RootInstance.
createBox()
virtual void inet::Macho::_StateInstance::createBox () pure virtual
Implemented in inet::Macho::_SubstateInstance< S >, and inet::Macho::_RootInstance.
Referenced by entry().
deleteBox()
virtual void inet::Macho::_StateInstance::deleteBox () pure virtual
Implemented in inet::Macho::_SubstateInstance< S >, and inet::Macho::_RootInstance.
Referenced by inet::Macho::MachoLink< C, P >::_deleteBox().
entry()
void inet::_StateInstance::entry (_StateInstance & previous, bool first = true)
 {
     // Only Root has no parent
     if (!myParent)
         return;
     // first entry or previous state is not substate -> perform entry
     if (first || !previous.isChild(*this)) {
         myParent->entry(previous, false);
         createBox();
         MACHO_TRC2(name(), "Entry");
         mySpecification->entry();
     }
 }
Referenced by entry(), and inet::Macho::_MachineBase::rattleOn().
exit()
void inet::_StateInstance::exit (_StateInstance & next)
 {
     // Only Root has no parent
     if (!myParent)
         return;
     // self transition or next state is not substate -> perform exit
     if (this == &next || !next.isChild(*this)) {
         MACHO_TRC2(name(), "Exit");
         mySpecification->exit();
         // EmptyBox should be most common box, so optimize for this case.
         if (myBox != &_EmptyBox::theEmptyBox)
             mySpecification->_deleteBox(*this);
         myParent->exit(next);
     }
 }
Referenced by exit(), and inet::Macho::_MachineBase::rattleOn().
history()
_StateInstance* inet::Macho::_StateInstance::history () const inline
     {
         return myHistory;
     }
Referenced by inet::Macho::_AdaptingInitializer::adapt(), inet::Macho::MachoLink< C, P >::history(), init(), and setHistory().
id()
virtual ID inet::Macho::_StateInstance::id () pure virtual
Implemented in inet::Macho::_SubstateInstance< S >, and inet::Macho::_RootInstance.
init()
void inet::_StateInstance::init (bool history)
 {
     if (history && myHistory) {
         MACHO_TRC3(name(), "History transition to", myHistory->name());
         myMachine.setPendingState(*myHistory, &_theDefaultInitializer);
     }
     else {
         MACHO_TRC2(name(), "Init");
         mySpecification->init();
     }
     myHistory = nullptr;
 }
Referenced by inet::Macho::_DefaultInitializer::execute(), inet::Macho::_HistoryInitializer::execute(), and inet::Macho::_AdaptingInitializer::execute().
isChild()
bool inet::Macho::_StateInstance::isChild (const _StateInstance & instance) inline
     {
         return this == &instance || (myParent && myParent->isChild(instance));
     }
Referenced by entry(), exit(), isChild(), and inet::Macho::_MachineBase::rattleOn().
key()
virtual Key inet::Macho::_StateInstance::key () pure virtual
Implemented in inet::Macho::_SubstateInstance< S >, and inet::Macho::_RootInstance.
Referenced by inet::Macho::_AdaptingInitializer::adapt(), inet::Macho::_MachineBase::currentState(), and inet::Macho::MachoLink< C, P >::history().
machine()
_MachineBase& inet::Macho::_StateInstance::machine () inline
     {
         return myMachine;
     }
Referenced by inet::Macho::_StateSpecification::_restore(), inet::Macho::_StateSpecification::_shutdown(), inet::Macho::_RootInstance::create(), inet::Macho::_SubstateInstance< S >::create(), inet::Macho::_StateSpecification::setState(), inet::Macho::_StateSpecification::setStateBox(), inet::Macho::_StateSpecification::setStateDirect(), and inet::Macho::_StateSpecification::setStateHistory().
name()
virtual const char* inet::Macho::_StateInstance::name () pure virtual
Implemented in inet::Macho::_SubstateInstance< S >, and inet::Macho::_RootInstance.
Referenced by entry(), exit(), init(), and inet::Macho::_MachineBase::rattleOn().
restore()
void inet::Macho::_StateInstance::restore (_StateInstance & instance) inline
     {
         mySpecification->_restore(instance);
     }
saveHistory()
void inet::Macho::_StateInstance::saveHistory (_StateInstance & shallow, _StateInstance & deep) inline
     {
         // Check state's history strategy.
         mySpecification->_saveHistory(*this, shallow, deep);
     }
Referenced by setHistorySuper().
setBox()
void inet::Macho::_StateInstance::setBox (void * box) inline
     {
         assert(!myBox);
         if (myBoxPlace) {
             // Free cached memory of previously used box.
             ::operator delete(myBoxPlace);
             myBoxPlace = 0;
         }
         myBox = box;
     }
Referenced by inet::Macho::Machine< fsm::TopState >::Machine(), and inet::Macho::_MachineBase::rattleOn().
setHistory()
void inet::Macho::_StateInstance::setHistory (_StateInstance * history) const inline
     {
         myHistory = history;
     }
Referenced by inet::Macho::MachoLink< C, P >::clearHistory().
setHistorySuper()
void inet::Macho::_StateInstance::setHistorySuper (_StateInstance & deep) inline
     {
         if (myParent)
             // Let it choose between deep or shallow history.
             myParent->saveHistory(*this, deep);
     }
Referenced by inet::Macho::_MachineBase::rattleOn().
shutdown()
void inet::Macho::_StateInstance::shutdown () inline
     {
         mySpecification->_shutdown();
     }
specification()
_StateSpecification& inet::Macho::_StateInstance::specification () inline
     {
         assert(mySpecification);
         return *mySpecification;
     }
Referenced by inet::Macho::_Event6< TOP, R, P1, P2, P3, P4, P5, P6 >::dispatch(), inet::Macho::_Event5< TOP, R, P1, P2, P3, P4, P5 >::dispatch(), inet::Macho::_Event4< TOP, R, P1, P2, P3, P4 >::dispatch(), inet::Macho::_Event3< TOP, R, P1, P2, P3 >::dispatch(), inet::Macho::_Event2< TOP, R, P1, P2 >::dispatch(), inet::Macho::_Event1< TOP, R, P1 >::dispatch(), inet::Macho::_Event0< TOP, R >::dispatch(), and inet::_VS8_Bug_101615::execute().
Member Data Documentation
myBox
void* inet::Macho::_StateInstance::myBox protected
Referenced by box(), inet::Macho::_SubstateInstance< S >::createBox(), inet::Macho::_SubstateInstance< S >::deleteBox(), exit(), setBox(), and inet::Macho::_SubstateInstance< S >::~_SubstateInstance().
myBoxPlace
void* inet::Macho::_StateInstance::myBoxPlace protected
Referenced by inet::Macho::_SubstateInstance< S >::createBox(), inet::Macho::_SubstateInstance< S >::deleteBox(), setBox(), ~_StateInstance(), and inet::Macho::_SubstateInstance< S >::~_SubstateInstance().
myHistory
_StateInstance* inet::Macho::_StateInstance::myHistory mutable protected
Referenced by history(), init(), and setHistory().
myMachine
_MachineBase& inet::Macho::_StateInstance::myMachine protected
Referenced by init(), and machine().
myParent
_StateInstance* inet::Macho::_StateInstance::myParent protected
Referenced by entry(), exit(), isChild(), and setHistorySuper().
mySpecification
_StateSpecification* inet::Macho::_StateInstance::mySpecification protected
Referenced by inet::Macho::_RootInstance::_RootInstance(), inet::Macho::_SubstateInstance< S >::_SubstateInstance(), entry(), exit(), init(), restore(), saveHistory(), shutdown(), specification(), and ~_StateInstance().
The documentation for this class was generated from the following files:
Macho.h
Macho.cc