INET Framework for OMNeT++/OMNEST: inet::BindingUpdateList Class Reference
inet::BindingUpdateList Class Reference
#include <BindingUpdateList.h>
Classes
class BindingUpdateListEntry
Public Types
enum MobilityState {
NONE = 0, RR, RR_COMPLETE, REGISTER,
REGISTERED, DEREGISTER
}
typedef std::map< Ipv6Address, BindingUpdateListEntry > BindingUpdateList6
Public Member Functions
BindingUpdateList ()
virtual ~BindingUpdateList ()
virtual void addOrUpdateBUL (const Ipv6Address &dest, const Ipv6Address &hoa, const Ipv6Address &coa, const uint lifetime, const uint seq, const simtime_t buSentTime)
Sets entry in the Binding Update List with provided values.
virtual BindingUpdateList::BindingUpdateListEntry * createBULEntry (const Ipv6Address &dest)
Creates a new entry in the BUL for the provided address.
virtual void initializeBUValues (BindingUpdateListEntry &entry)
Initializes the values of a BUL entry to initial values.
virtual void addOrUpdateBUL (const Ipv6Address &dest, const Ipv6Address &hoa, simtime_t sentTime, int cookie, bool isHoTI)
Sets HoTI and/or CoTI values (transmission time, etc.) for the BUL entry.
virtual BindingUpdateList::BindingUpdateListEntry * lookup (const Ipv6Address &dest)
Returns the BUL entry for a certain destination address.
virtual BindingUpdateList::BindingUpdateListEntry * fetch (const Ipv6Address &dest)
Similiar to lookup(), but with the difference that this method always returns a valid BUL entry.
virtual MobilityState getMobilityState (const Ipv6Address &dest) const
Returns the current mobility state for the CN identified by the provided IP address.
virtual void setMobilityState (const Ipv6Address &dest, BindingUpdateList::MobilityState state)
Sets the mobility state to provided state for the CN identified by the provided IP address.
virtual int generateBAuthData (const Ipv6Address &dest, const Ipv6Address &CoA)
Generates the Binding Authorization Data based on a certain destination address and CoA.
virtual int generateKey (int homeToken, int careOfToken, const Ipv6Address &CoA)
Generates the key Kbm from home and care-of keygen token.
virtual int generateHomeToken (const Ipv6Address &HoA, int nonce)
Generates a home token from the provided parameters.
virtual int generateCareOfToken (const Ipv6Address &CoA, int nonce)
Generates a care-of token from the provided parameters.
virtual void resetHomeToken (const Ipv6Address &dest, const Ipv6Address &hoa)
Resets the token to UNDEFINED.
virtual void resetCareOfToken (const Ipv6Address &dest, const Ipv6Address &hoa)
Resets the token to UNDEFINED.
virtual bool isHomeTokenAvailable (const Ipv6Address &dest, NetworkInterface *ie)
Returns true if a home keygen token is available.
virtual bool isCareOfTokenAvailable (const Ipv6Address &dest, NetworkInterface *ie)
Returns true if a care-of keygen token is available.
virtual bool isInBindingUpdateList (const Ipv6Address &dest) const
Checks whether there exists an entry in the BUL for the given destination address.
virtual uint getSequenceNumber (const Ipv6Address &dest)
Returns the last used sequence number for the given dest.
virtual const Ipv6Address & getCoA (const Ipv6Address &dest)
Returns the CoA that was registered for the provided dest.
virtual bool isInBindingUpdateList (const Ipv6Address &dest, const Ipv6Address &HoA)
Checks whether there exists an entry in the BUL for the given destination address and home address.
virtual bool isValidBinding (const Ipv6Address &dest)
Returns true if a binding has been acknowledged and it's lifetime has not yet expired.
virtual bool isBindingAboutToExpire (const Ipv6Address &dest)
Returns true if a binding is about to expire.
virtual bool sentBindingUpdate (const Ipv6Address &dest)
Returns true if a binding update has been sent to and acknowledged by the provided destination address and the lifetime has not yet expired.
virtual void removeBinding (const Ipv6Address &dest)
Deletes an entry from the binding update list for the provided destination address.
virtual void suspendBinding (const Ipv6Address &dest)
Sets the state of the binding cache entry to "not usable".
virtual bool recentlySentCOTI (const Ipv6Address &dest, NetworkInterface *ie)
These two methods indicate whether a CoTI or HoTI message has been recently sent to the CN identified by parameter dest.
virtual bool recentlySentHOTI (const Ipv6Address &dest, NetworkInterface *ie)
Public Attributes
BindingUpdateList6 bindingUpdateList
Protected Member Functions
virtual void initialize () override
virtual void handleMessage (cMessage *) override
Raises an error.
virtual void resetBindingCacheEntry (BindingUpdateListEntry &entry)
Resets binding lifetime, tokens, etc.
Friends
std::ostream & operator<< (std::ostream &os, const BindingUpdateListEntry &bul)
Member Typedef Documentation
BindingUpdateList6
typedef std::map<Ipv6Address, BindingUpdateListEntry> inet::BindingUpdateList::BindingUpdateList6
Member Enumeration Documentation
MobilityState
enum inet::BindingUpdateList::MobilityState
Enumerator
NONE
RR
RR_COMPLETE
REGISTER
REGISTERED
DEREGISTER
{
         NONE = 0,
         RR,
         RR_COMPLETE,
         REGISTER,
         REGISTERED,
         DEREGISTER
     };
Constructor & Destructor Documentation
BindingUpdateList()
inet::BindingUpdateList::BindingUpdateList ()
 {
 }
~BindingUpdateList()
inet::BindingUpdateList::~BindingUpdateList () virtual
 {
 //    for (unsigned int i = 0; i < bindingUpdateList.size(); i++)
 //        delete bindingUpdateList[i];
 }
Member Function Documentation
addOrUpdateBUL() [1/2]
void inet::BindingUpdateList::addOrUpdateBUL (const Ipv6Address & dest, const Ipv6Address & hoa, const Ipv6Address & coa, const uint lifetime, const uint seq, const simtime_t buSentTime) virtual
Sets entry in the Binding Update List with provided values.
If entry does not yet exist, a new one is created.
 {
     // modified structure - CB
     // search for entry
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     // if it is not yet existing, create it
     if (entry == nullptr) {
         /*bindingUpdateList[dest].destAddress = dest;
            entry = & bindingUpdateList[dest];
            initializeBUValues(*entry);*/
         entry = createBULEntry(dest);
     }
     EV_INFO << "\n++++++++++++++++++++Binding Update List Being Updated in Routing Table6 ++++++++++++++\n";
     entry->homeAddress = hoa;
     entry->careOfAddress = coa;
     // update lifetime 11.06.08 - CB
     entry->bindingLifetime = lifetime; // for the moment a constant but then it is supposed to decrement with time.
     entry->bindingExpiry = simTime() + lifetime; // binding expires at this point in time
     // TODO bindingUpdateList[dest].remainingLifetime = ;
     entry->sentTime = buSentTime; // the time at which the BU, whose ack is awaited is sent
 //    entry->nextBUTx = nextBUSentTime; //the nextScgheduledTime at which the BU will be sent in case of timeout.
     entry->sequenceNumber = seq; // seq number of the last BU sent.
     entry->BAck = false;
 }
addOrUpdateBUL() [2/2]
void inet::BindingUpdateList::addOrUpdateBUL (const Ipv6Address & dest, const Ipv6Address & hoa, simtime_t sentTime, int cookie, bool isHoTI = false) virtual
Sets HoTI and/or CoTI values (transmission time, etc.) for the BUL entry.
 {
     EV_INFO << "\n++++++++++++++++++++Binding Update List for HoTI/CoTI Being Updated in Routing Table6 ++++++++++++++\n";
     // search for entry
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     // if it is not yet existing, create it
     if (entry == nullptr) {
         bindingUpdateList[dest].destAddress = dest;
         entry = &bindingUpdateList[dest];
         initializeBUValues(*entry);
     }
     if (HoTI) { // those values are from the HoTI message
         entry->homeAddress = addr;
         entry->sentHoTI = sentTime;
         entry->cookieHoTI = cookie;
     }
     else { // and those from the CoTI
         entry->careOfAddress = addr;
         entry->sentCoTI = sentTime;
         entry->cookieCoTI = cookie;
     }
 }
createBULEntry()
BindingUpdateList::BindingUpdateListEntry * inet::BindingUpdateList::createBULEntry (const Ipv6Address & dest) virtual
Creates a new entry in the BUL for the provided address.
 {
     bindingUpdateList[dest].destAddress = dest;
     BindingUpdateListEntry& entry = bindingUpdateList[dest];
 //    BindingUpdateList::BindingUpdateListEntry* entry = & bindingUpdateList[dest];
     initializeBUValues(entry);
     return &entry;
 }
Referenced by addOrUpdateBUL(), and fetch().
fetch()
BindingUpdateList::BindingUpdateListEntry * inet::BindingUpdateList::fetch (const Ipv6Address & dest) virtual
Similiar to lookup(), but with the difference that this method always returns a valid BUL entry.
If none existed prior to the call, a new entry is created.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     return (entry == nullptr) ? createBULEntry(dest) : entry;
 }
generateBAuthData()
int inet::BindingUpdateList::generateBAuthData (const Ipv6Address & dest, const Ipv6Address & CoA) virtual
Generates the Binding Authorization Data based on a certain destination address and CoA.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     if (entry == nullptr) {
         EV_WARN << "Impossible to generate Binding Authorization Data as CN is not existing in BUL!\n";
         return 0;
     }
     // generate the key
     return BindingUpdateList::generateKey(entry->tokenH, entry->tokenC, CoA);
 }
generateCareOfToken()
int inet::BindingUpdateList::generateCareOfToken (const Ipv6Address & CoA, int nonce) virtual
Generates a care-of token from the provided parameters.
Returns a static value for now.
 {
     return CO_TOKEN;
 }
generateHomeToken()
int inet::BindingUpdateList::generateHomeToken (const Ipv6Address & HoA, int nonce) virtual
Generates a home token from the provided parameters.
Returns a static value for now.
 {
     return HO_TOKEN;
 }
generateKey()
int inet::BindingUpdateList::generateKey (int homeToken, int careOfToken, const Ipv6Address & CoA) virtual
Generates the key Kbm from home and care-of keygen token.
For now, this return the sum of both tokens.
 {
     // use a dummy value
     return homeToken + careOfToken;
 }
Referenced by generateBAuthData().
getCoA()
const Ipv6Address & inet::BindingUpdateList::getCoA (const Ipv6Address & dest) virtual
Returns the CoA that was registered for the provided dest.
address.
 {
     // search for entry
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     return entry->careOfAddress;
 }
getMobilityState()
BindingUpdateList::MobilityState inet::BindingUpdateList::getMobilityState (const Ipv6Address & dest) const virtual
Returns the current mobility state for the CN identified by the provided IP address.
 {
     BindingUpdateList6::const_iterator i = bindingUpdateList.find(dest);
     return (i == bindingUpdateList.end()) ? NONE : i->second.state;
 }
getSequenceNumber()
uint inet::BindingUpdateList::getSequenceNumber (const Ipv6Address & dest) virtual
Returns the last used sequence number for the given dest.
address.
 {
     // search for entry
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     return (entry != nullptr) ? entry->sequenceNumber : 0;
 }
handleMessage()
void inet::BindingUpdateList::handleMessage (cMessage * msg) override protected virtual
Raises an error.
 {
     throw cRuntimeError("This module doesn't process messages");
 }
initialize()
void inet::BindingUpdateList::initialize () override protected virtual
 {
     WATCH_MAP(bindingUpdateList); // added by Zarrar Yousaf
 }
initializeBUValues()
void inet::BindingUpdateList::initializeBUValues (BindingUpdateListEntry & entry) virtual
Initializes the values of a BUL entry to initial values.
Called by addOrUpdateBUL() if new entry is created.
 {
     // normal BU values
     entry.bindingLifetime = 0;
     entry.bindingExpiry = 0;
     // TODO bindingUpdateList[dest].remainingLifetime = ;
     entry.sentTime = 0;
 //    entry.nextBUTx = 0;
     entry.sequenceNumber = 0;
     entry.BAck = false;
     // RR specific values
     entry.sentHoTI = 0;
     entry.sentCoTI = 0;
     entry.cookieHoTI = UNDEFINED_COOKIE;
     entry.cookieCoTI = UNDEFINED_COOKIE;
 //    entry.sendNext = 0;
     entry.tokenH = UNDEFINED_TOKEN;
     entry.tokenC = UNDEFINED_TOKEN;
     // 21.07.08 - CB
     entry.state = NONE;
 }
Referenced by addOrUpdateBUL(), and createBULEntry().
isBindingAboutToExpire()
bool inet::BindingUpdateList::isBindingAboutToExpire (const Ipv6Address & dest) virtual
Returns true if a binding is about to expire.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     return (entry == nullptr) ? true : entry->bindingLifetime < SIMTIME_DBL(simTime()) - PRE_BINDING_EXPIRY;
 }
isCareOfTokenAvailable()
bool inet::BindingUpdateList::isCareOfTokenAvailable (const Ipv6Address & dest, NetworkInterface * ie) virtual
Returns true if a care-of keygen token is available.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     return entry->tokenC != UNDEFINED_TOKEN &&
            (entry->sentCoTI + ie->getProtocolData<Ipv6InterfaceData>()->_getMaxTokenLifeTime()) > simTime();
 }
isHomeTokenAvailable()
bool inet::BindingUpdateList::isHomeTokenAvailable (const Ipv6Address & dest, NetworkInterface * ie) virtual
Returns true if a home keygen token is available.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     return entry->tokenH != UNDEFINED_TOKEN &&
            (entry->sentHoTI + ie->getProtocolData<Ipv6InterfaceData>()->_getMaxTokenLifeTime()) > simTime();
 }
isInBindingUpdateList() [1/2]
bool inet::BindingUpdateList::isInBindingUpdateList (const Ipv6Address & dest) const virtual
Checks whether there exists an entry in the BUL for the given destination address.
 {
     return containsKey(bindingUpdateList, dest);
 }
isInBindingUpdateList() [2/2]
bool inet::BindingUpdateList::isInBindingUpdateList (const Ipv6Address & dest, const Ipv6Address & HoA) virtual
Checks whether there exists an entry in the BUL for the given destination address and home address.
 {
     auto pos = bindingUpdateList.find(dest);
     return (pos == bindingUpdateList.end()) ? false : pos->second.homeAddress == HoA;
 }
isValidBinding()
bool inet::BindingUpdateList::isValidBinding (const Ipv6Address & dest) virtual
Returns true if a binding has been acknowledged and it's lifetime has not yet expired.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     return (entry == nullptr) ? false : entry->BAck && (entry->bindingLifetime < SIMTIME_DBL(simTime()));
 }
lookup()
BindingUpdateList::BindingUpdateListEntry * inet::BindingUpdateList::lookup (const Ipv6Address & dest) virtual
Returns the BUL entry for a certain destination address.
 {
     auto i = bindingUpdateList.find(dest);
     return (i == bindingUpdateList.end()) ? nullptr : &(i->second);
 }
Referenced by addOrUpdateBUL(), fetch(), generateBAuthData(), getCoA(), getSequenceNumber(), isBindingAboutToExpire(), isCareOfTokenAvailable(), isHomeTokenAvailable(), isValidBinding(), recentlySentCOTI(), recentlySentHOTI(), removeBinding(), resetCareOfToken(), resetHomeToken(), sentBindingUpdate(), and suspendBinding().
recentlySentCOTI()
bool inet::BindingUpdateList::recentlySentCOTI (const Ipv6Address & dest, NetworkInterface * ie) virtual
These two methods indicate whether a CoTI or HoTI message has been recently sent to the CN identified by parameter dest.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     return entry->sentCoTI + ie->getProtocolData<Ipv6InterfaceData>()->_getMaxTokenLifeTime() / 3 > simTime();
 }
recentlySentHOTI()
bool inet::BindingUpdateList::recentlySentHOTI (const Ipv6Address & dest, NetworkInterface * ie) virtual
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     return entry->sentHoTI + ie->getProtocolData<Ipv6InterfaceData>()->_getMaxTokenLifeTime() / 3 > simTime();
 }
removeBinding()
void inet::BindingUpdateList::removeBinding (const Ipv6Address & dest) virtual
Deletes an entry from the binding update list for the provided destination address.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     if ((entry->tokenH != UNDEFINED_TOKEN) || (entry->tokenC != UNDEFINED_TOKEN))
         // for CNs, we just delete all entries
         resetBindingCacheEntry(*entry);
     else
         // the BUL entry to the HA is completely deleted
         bindingUpdateList.erase(dest);
 }
resetBindingCacheEntry()
void inet::BindingUpdateList::resetBindingCacheEntry (BindingUpdateListEntry & entry) protected virtual
Resets binding lifetime, tokens, etc.
of the BUL entry.
 {
     entry.bindingLifetime = 0;
     entry.bindingExpiry = 0;
 //    entry.remainingLifetime = 0;
 //    entry.sequenceNumber = 0;
     entry.sentTime = 0;
 //    entry.nextBUTx = 0;
     entry.BAck = false;
     entry.state = NONE;
     // if tokens should sustain handovers then comment out the following lines of code
     // (this could eventually allow for parallel CN and HA registration)
     /*entry.sentHoTI = 0;
        entry.sentCoTI = 0;
        entry.tokenH = 0;
        entry.tokenC = 0;*/
 }
Referenced by removeBinding().
resetCareOfToken()
void inet::BindingUpdateList::resetCareOfToken (const Ipv6Address & dest, const Ipv6Address & hoa) virtual
Resets the token to UNDEFINED.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     entry->tokenC = UNDEFINED_TOKEN;
 //    entry->sentCoTI = 0;
 }
resetHomeToken()
void inet::BindingUpdateList::resetHomeToken (const Ipv6Address & dest, const Ipv6Address & hoa) virtual
Resets the token to UNDEFINED.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     entry->tokenH = UNDEFINED_TOKEN;
 //    entry->sentHoTI = 0;
 }
sentBindingUpdate()
bool inet::BindingUpdateList::sentBindingUpdate (const Ipv6Address & dest) virtual
Returns true if a binding update has been sent to and acknowledged by the provided destination address and the lifetime has not yet expired.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     if (entry == nullptr)
         return false;
     return (entry->BAck || (entry->tokenH != UNDEFINED_TOKEN && entry->tokenC != UNDEFINED_TOKEN))
            && entry->sentTime != 0;
 }
setMobilityState()
void inet::BindingUpdateList::setMobilityState (const Ipv6Address & dest, BindingUpdateList::MobilityState state) virtual
Sets the mobility state to provided state for the CN identified by the provided IP address.
 {
     auto i = bindingUpdateList.find(dest);
     if (i != bindingUpdateList.end())
         i->second.state = state;
 }
suspendBinding()
void inet::BindingUpdateList::suspendBinding (const Ipv6Address & dest) virtual
Sets the state of the binding cache entry to "not usable".
Resets the BAck flag to false, etc.
 {
     BindingUpdateList::BindingUpdateListEntry *entry = lookup(dest);
     ASSERT(entry != nullptr);
     entry->BAck = false;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const BindingUpdateListEntry & bul) friend
 {
     os << "Destination: " << bul.destAddress << " HoA of MN: " << bul.homeAddress
        << " CoA of MN: " << bul.careOfAddress << "\n"
        << "Binding Lifetime: " << bul.bindingLifetime << " binding expiry: "
        << SIMTIME_STR(bul.bindingExpiry) << " BU Sequence#: " << bul.sequenceNumber
        << " Sent Time: " << SIMTIME_STR(bul.sentTime) /* << " Next_Tx_Time: " << bul.nextBUTx << */
        << " BU_Ack: " << bul.BAck << "\n";
     // this part will only be displayed if the BUL entry is for CN registration
     if (bul.sentHoTI != 0) {
         os << "Sent Time HoTI: " << SIMTIME_STR(bul.sentHoTI) << " HoTI cookie: " << bul.cookieHoTI
            << " home token: " << bul.tokenH << "\n";
     }
     if (bul.sentCoTI != 0) {
         os << " Sent Time CoTI: " << SIMTIME_STR(bul.sentCoTI) << " CoTI cookie: " << bul.cookieCoTI
            << " care-of token: " << bul.tokenC << "\n";
     }
     os << "State: ";
     switch (bul.state) {
         case BindingUpdateList::NONE:
             os << "none";
             break;
         case BindingUpdateList::RR:
             os << "Return Routability";
             break;
         case BindingUpdateList::RR_COMPLETE:
             os << "Return Routability completed";
             break;
         case BindingUpdateList::REGISTER:
             os << "Registering";
             break;
         case BindingUpdateList::REGISTERED:
             os << "Registered";
             break;
         case BindingUpdateList::DEREGISTER:
             os << "Deregistering";
             break;
         default:
             os << "Unknown";
             break;
     }
     os << endl;
     return os;
 }
Member Data Documentation
bindingUpdateList
BindingUpdateList6 inet::BindingUpdateList::bindingUpdateList
Referenced by addOrUpdateBUL(), createBULEntry(), getMobilityState(), initialize(), isInBindingUpdateList(), lookup(), removeBinding(), and setMobilityState().
The documentation for this class was generated from the following files:
BindingUpdateList.h
BindingUpdateList.cc