INET Framework for OMNeT++/OMNEST: inet::Ipv6NdOption Class Reference
inet::Ipv6NdOption Class Reference
Class generated from inet/networklayer/icmpv6/Ipv6NdMessage.msg:38 by opp_msgtool.
#include <Ipv6NdMessage_m.h>
Public Member Functions
Ipv6NdOption ()
Ipv6NdOption (const Ipv6NdOption &other)
virtual ~Ipv6NdOption ()
Ipv6NdOption & operator= (const Ipv6NdOption &other)
virtual Ipv6NdOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual Ipv6NdOptionTypes getType () const
virtual void setType (Ipv6NdOptionTypes type)
virtual short getOptionLength () const
virtual void setOptionLength (short optionLength)
virtual void setPaddingBytesArraySize (size_t size)
virtual size_t getPaddingBytesArraySize () const
virtual char getPaddingBytes (size_t k) const
virtual void setPaddingBytes (size_t k, char paddingBytes)
virtual void insertPaddingBytes (size_t k, char paddingBytes)
void insertPaddingBytes (char paddingBytes)
virtual void appendPaddingBytes (char paddingBytes)
virtual void erasePaddingBytes (size_t k)
Protected Member Functions
bool operator== (const Ipv6NdOption &)=delete
Protected Attributes
Ipv6NdOptionTypes type = static_cast<Ipv6NdOptionTypes>(0)
short optionLength = 0
char * paddingBytes = nullptr
size_t paddingBytes_arraysize = 0
Private Member Functions
void copy (const Ipv6NdOption &other)
Detailed Description
Class generated from inet/networklayer/icmpv6/Ipv6NdMessage.msg:38 by opp_msgtool.
class Ipv6NdOption extends cObject
{
    @packetData;
    Ipv6NdOptionTypes type = static_cast<Ipv6NdOptionTypes>(0);    // 1 byte, 0 is invalid
    short optionLength = 0;    // The length of the option in units of 8 octets, 0 is invalid.    // 1 byte
    char paddingBytes[];    // padding bytes on end of option
}
Constructor & Destructor Documentation
Ipv6NdOption() [1/2]
inet::Ipv6NdOption::Ipv6NdOption ()
Ipv6NdOption() [2/2]
inet::Ipv6NdOption::Ipv6NdOption (const Ipv6NdOption & other)
~Ipv6NdOption()
virtual inet::Ipv6NdOption::~Ipv6NdOption () virtual
Member Function Documentation
appendPaddingBytes()
virtual void inet::Ipv6NdOption::appendPaddingBytes (char paddingBytes) virtual
copy()
void inet::Ipv6NdOption::copy (const Ipv6NdOption & other) private
dup()
virtual Ipv6NdOption* inet::Ipv6NdOption::dup () const inline override virtual
Reimplemented in inet::Mipv6HaInformation, inet::Mipv6NdAdvertisementInterval, inet::Ipv6NdMtu, inet::Ipv6NdPrefixInformation, inet::Ipv6NdTargetLinkLayerAddress, inet::Ipv6NdSourceLinkLayerAddress, and inet::Ipv6NdSourceTargetLinkLayerAddress.
 {return new Ipv6NdOption(*this);}
erasePaddingBytes()
virtual void inet::Ipv6NdOption::erasePaddingBytes (size_t k) virtual
getOptionLength()
virtual short inet::Ipv6NdOption::getOptionLength () const virtual
Referenced by inet::serializeIpv6NdOptions().
getPaddingBytes()
virtual char inet::Ipv6NdOption::getPaddingBytes (size_t k) const virtual
Referenced by inet::serializeIpv6NdOptions().
getPaddingBytesArraySize()
virtual size_t inet::Ipv6NdOption::getPaddingBytesArraySize () const virtual
Referenced by inet::serializeIpv6NdOptions().
getType()
virtual Ipv6NdOptionTypes inet::Ipv6NdOption::getType () const virtual
Referenced by inet::Ipv6NdOptions::insertUniqueOption(), and inet::serializeIpv6NdOptions().
insertPaddingBytes() [1/2]
void inet::Ipv6NdOption::insertPaddingBytes (char paddingBytes) inline
 {appendPaddingBytes(paddingBytes);}
insertPaddingBytes() [2/2]
virtual void inet::Ipv6NdOption::insertPaddingBytes (size_t k, char paddingBytes) virtual
operator=()
Ipv6NdOption& inet::Ipv6NdOption::operator= (const Ipv6NdOption & other)
operator==()
bool inet::Ipv6NdOption::operator== (const Ipv6NdOption &) protected delete
parsimPack()
virtual void inet::Ipv6NdOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::Mipv6HaInformation, inet::Mipv6NdAdvertisementInterval, inet::Ipv6NdMtu, inet::Ipv6NdPrefixInformation, inet::Ipv6NdTargetLinkLayerAddress, inet::Ipv6NdSourceLinkLayerAddress, and inet::Ipv6NdSourceTargetLinkLayerAddress.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6NdOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::Mipv6HaInformation, inet::Mipv6NdAdvertisementInterval, inet::Ipv6NdMtu, inet::Ipv6NdPrefixInformation, inet::Ipv6NdTargetLinkLayerAddress, inet::Ipv6NdSourceLinkLayerAddress, and inet::Ipv6NdSourceTargetLinkLayerAddress.
Referenced by inet::doParsimUnpacking().
setOptionLength()
virtual void inet::Ipv6NdOption::setOptionLength (short optionLength) virtual
setPaddingBytes()
virtual void inet::Ipv6NdOption::setPaddingBytes (size_t k, char paddingBytes) virtual
setPaddingBytesArraySize()
virtual void inet::Ipv6NdOption::setPaddingBytesArraySize (size_t size) virtual
setType()
virtual void inet::Ipv6NdOption::setType (Ipv6NdOptionTypes type) virtual
Member Data Documentation
optionLength
short inet::Ipv6NdOption::optionLength = 0 protected
paddingBytes
char* inet::Ipv6NdOption::paddingBytes = nullptr protected
paddingBytes_arraysize
size_t inet::Ipv6NdOption::paddingBytes_arraysize = 0 protected
type
Ipv6NdOptionTypes inet::Ipv6NdOption::type = static_cast<Ipv6NdOptionTypes>(0) protected
The documentation for this class was generated from the following file:
Ipv6NdMessage_m.h