INET Framework for OMNeT++/OMNEST: inet::MemoryOutputStream Class Reference
inet::MemoryOutputStream Class Reference
This class provides an efficient in memory bit output stream.
#include <MemoryOutputStream.h>
Public Member Functions
MemoryOutputStream (b initialCapacity=B(64))
Stream querying functions
b getLength () const
Returns the length of the bit stream measured in bits.
const std::vector< uint8_t > & getData () const
void copyData (std::vector< bool > &result, b offset=b(0), b length=b(-1)) const
void copyData (std::vector< uint8_t > &result, B offset=B(0), B length=B(-1)) const
Bit streaming functions
void writeBit (bool value)
Writes a bit to the end of the stream.
void writeBitRepeatedly (bool value, size_t count)
Writes the same bit repeatedly to the end of the stream.
void writeBits (const std::vector< bool > &bits, b offset=b(0), b length=b(-1))
Writes a sequence of bits to the end of the stream keeping the original bit order.
Byte streaming functions
void writeByte (uint8_t value)
Writes a byte to the end of the stream in MSB to LSB bit order.
void writeByteRepeatedly (uint8_t value, size_t count)
Writes the same byte repeatedly to the end of the stream in MSB to LSB bit order.
void writeBytes (const std::vector< uint8_t > &bytes, B offset=B(0), B length=B(-1))
Writes a sequence of bytes to the end of the stream keeping the original byte order and in MSB to LSB bit order.
void writeBytes (const uint8_t *buffer, B length)
Writes a sequence of bytes to the end of the stream keeping the original byte order and in MSB to LSB bit order.
Basic type streaming functions
void writeUint2 (uint8_t value)
Writes a 2 bit unsigned integer to the end of the stream in MSB to LSB bit order.
void writeUint4 (uint8_t value)
Writes a 4 bit unsigned integer to the end of the stream in MSB to LSB bit order.
void writeUint8 (uint8_t value)
Writes an 8 bit unsigned integer to the end of the stream in MSB to LSB bit order.
void writeUint16Be (uint16_t value)
Writes a 16 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeUint16Le (uint16_t value)
Writes a 16 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
void writeUint24Be (uint32_t value)
Writes a 24 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeUint24Le (uint32_t value)
Writes a 24 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
void writeUint32Be (uint32_t value)
Writes a 32 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeUint32Le (uint32_t value)
Writes a 32 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
void writeUint48Be (uint64_t value)
Writes a 48 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeUint48Le (uint64_t value)
Writes a 48 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
void writeUint64Be (uint64_t value)
Writes a 64 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeUint64Le (uint64_t value)
Writes a 64 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
INET specific type streaming functions
void writeMacAddress (MacAddress address)
Writes a MAC address to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeIpv4Address (Ipv4Address address)
Writes an Ipv4 address to the end of the stream in big endian byte order and MSB to LSB bit order.
void writeIpv6Address (Ipv6Address address)
Writes an Ipv6 address to the end of the stream in big endian byte order and MSB to LSB bit order.
other useful streaming functions
void writeString (std::string s)
Writes a zero terminated string in the order of the characters.
void writeNBitsOfUint64Be (uint64_t value, uint8_t n)
Writes n bits of a 64 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
Protected Member Functions
bool isByteAligned ()
Protected Attributes
std::vector< uint8_t > data
This vector contains the bits that were written to this stream so far.
b length
The length of the bit stream measured in bits.
Detailed Description
This class provides an efficient in memory bit output stream.
The stream provides a set of write functions that write data to the end of the stream. Most functions are implemented in the header to allow inlining.
Constructor & Destructor Documentation
MemoryOutputStream()
inet::MemoryOutputStream::MemoryOutputStream (b initialCapacity = B(64)) inline
                                                   :
         length(b(0))
     {
         data.reserve((b(initialCapacity).get() + 7) >> 3);
     }
Member Function Documentation
copyData() [1/2]
void inet::MemoryOutputStream::copyData (std::vector< bool > & result, b offset = b(0), b length = b(-1)) const inline
{
         size_t end = b(length == b(-1) ? this->length : offset + length).get();
         for (size_t i = b(offset).get(); i < end; i++) {
             size_t byteIndex = i / 8;
             size_t bitIndex = i % 8;
             uint8_t byte = data.at(byteIndex);
             uint8_t mask = 1 << (7 - bitIndex);
             bool bit = byte & mask;
             result.push_back(bit);
         }
     }
Referenced by inet::BitsChunk::convertChunk(), inet::Chunk::getBinDumpLine(), inet::Chunk::getHexDumpLine(), and inet::FieldsChunkSerializer::serialize().
copyData() [2/2]
void inet::MemoryOutputStream::copyData (std::vector< uint8_t > & result, B offset = B(0), B length = B(-1)) const inline
{
         auto end = length == B(-1) ? B(data.size()) : offset + length;
         assert(b(0) <= offset && offset <= B(data.size()));
         assert(b(0) <= end && end <= B(data.size()));
         assert(offset <= end);
         result.insert(result.begin(), data.begin() + B(offset).get(), data.begin() + B(end).get());
     }
getData()
const std::vector<uint8_t>& inet::MemoryOutputStream::getData () const inline
 { return data; }
Referenced by inet::tcp::Tcp::checkCrc(), inet::tcp::TcpCrcInsertionHook::computeCrc(), inet::Pim::computeCrc(), inet::Udp::computeCrc(), inet::BytesChunk::convertChunk(), inet::Chunk::convertChunk(), inet::Ipv4Encap::encapsulate(), inet::sctp::SctpCrcInsertion::insertCrc(), inet::Icmp::insertCrc(), inet::Icmpv6::insertCrc(), inet::Ipv4::insertCrc(), inet::Igmpv2::insertCrc(), inet::Igmpv3::insertCrc(), inet::FieldsChunkSerializer::serialize(), inet::Ipv4::setComputedCrc(), inet::ospfv2::setLsaCrc(), inet::ospfv2::setLsaHeaderCrc(), inet::ospfv2::setOspfCrc(), and inet::Ipv4::verifyCrc().
getLength()
b inet::MemoryOutputStream::getLength () const inline
Returns the length of the bit stream measured in bits.
 { return length; }
Referenced by inet::Chunk::getHexDumpLine(), inet::Ipv6HeaderSerializer::serialize(), inet::rtp::RtcpPacketSerializer::serialize(), inet::ApplicationPacketSerializer::serialize(), inet::EtherAppReqSerializer::serialize(), inet::UnitDiskPhyHeaderSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::BMacHeaderSerializer::serialize(), inet::GenericAppMsgSerializer::serialize(), inet::VoipStreamPacketSerializer::serialize(), inet::physicallayer::ApskPhyHeaderSerializer::serialize(), inet::CsmaCaMacHeaderSerializer::serialize(), inet::AckingMacHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::Ipv4HeaderSerializer::serialize(), inet::FieldsChunkSerializer::serialize(), inet::EtherAppRespSerializer::serialize(), and inet::Chunk::serialize().
isByteAligned()
bool inet::MemoryOutputStream::isByteAligned () inline protected
{
         return b(length).get() % 8 == 0;
     }
writeBit()
void inet::MemoryOutputStream::writeBit (bool value) inline
Writes a bit to the end of the stream.
{
         size_t i = b(length).get();
         size_t byteIndex = i / 8;
         size_t bitIndex = i % 8;
         if (bitIndex == 0)
             data.push_back(0);
         if (value)
             data[byteIndex] |= 1 << (7 - bitIndex);
         length += b(1);
     }
Referenced by inet::Ipv6HeaderSerializer::serialize(), inet::rtp::RtcpPacketSerializer::serialize(), inet::rtp::RtpPacketSerializer::serialize(), inet::IgmpHeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::MplsPacketSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::PimPacketSerializer::serialize(), inet::aodv::AodvControlPacketsSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::serialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::serializeOspfOptions(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
writeBitRepeatedly()
void inet::MemoryOutputStream::writeBitRepeatedly (bool value, size_t count) inline
Writes the same bit repeatedly to the end of the stream.
{
         for (size_t i = 0; i < count; i++)
             writeBit(value);
     }
Referenced by inet::BitCountChunkSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::UnitDiskPhyHeaderSerializer::serialize(), inet::BMacHeaderSerializer::serialize(), inet::physicallayer::ApskPhyHeaderSerializer::serialize(), and inet::bgp::BgpHeaderSerializer::serialize().
writeBits()
void inet::MemoryOutputStream::writeBits (const std::vector< bool > & bits, b offset = b(0), b length = b(-1)) inline
Writes a sequence of bits to the end of the stream keeping the original bit order.
{
         auto end = length == b(-1) ? bits.size() : b(offset + length).get();
         for (size_t i = b(offset).get(); i < end; i++)
             writeBit(bits.at(i));
     }
Referenced by inet::BitsChunkSerializer::serialize().
writeByte()
void inet::MemoryOutputStream::writeByte (uint8_t value) inline
Writes a byte to the end of the stream in MSB to LSB bit order.
{
         if (isByteAligned())
             data.push_back(value);
         else {
             int l1 = b(length).get() % 8;
             int l2 = 8 - l1;
             data.back() |= (value & (0xFF << l2)) >> l2;
             data.push_back((value & (0xFF >> l1)) << l1);
         }
         length += B(1);
     }
Referenced by inet::Ieee8021aeTagTpidHeaderSerializer::serialize(), inet::Ieee8022LlcHeaderSerializer::serialize(), inet::Ipv6HeaderSerializer::serialize(), inet::rtp::RtcpPacketSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::GenericAppMsgSerializer::serialize(), inet::TransportPseudoHeaderSerializer::serialize(), inet::VoipStreamPacketSerializer::serialize(), inet::BMacHeaderSerializer::serialize(), inet::IcmpHeaderSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::IgmpHeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::Icmpv6HeaderSerializer::serialize(), inet::PimPacketSerializer::serialize(), inet::aodv::AodvControlPacketsSerializer::serialize(), inet::CsmaCaMacHeaderSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::ArpPacketSerializer::serialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::serialize(), inet::Ieee8021aeTagEpdHeaderSerializer::serialize(), inet::physicallayer::EthernetPhyHeaderSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serialize(), inet::physicallayer::Ieee80211DsssPhyHeaderSerializer::serialize(), inet::physicallayer::EthernetFragmentPhyHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MpduSubframeHeaderSerializer::serialize(), inet::physicallayer::Ieee80211HrDsssPhyHeaderSerializer::serialize(), inet::serializeIpv6NdOptions(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader(), inet::Ipv4HeaderSerializer::serializeOption(), inet::tcp::TcpHeaderSerializer::serializeOption(), inet::ospfv2::Ospfv2PacketSerializer::serializeOspfHeader(), inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa(), and inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa().
writeByteRepeatedly()
void inet::MemoryOutputStream::writeByteRepeatedly (uint8_t value, size_t count) inline
Writes the same byte repeatedly to the end of the stream in MSB to LSB bit order.
{
         for (size_t i = 0; i < count; i++)
             writeByte(value);
     }
Referenced by inet::ByteCountChunkSerializer::serialize(), inet::Ipv6HeaderSerializer::serialize(), inet::ApplicationPacketSerializer::serialize(), inet::EtherAppReqSerializer::serialize(), inet::VoipStreamPacketSerializer::serialize(), inet::BMacHeaderSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::physicallayer::ApskPhyHeaderSerializer::serialize(), inet::GenericAppMsgSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::CsmaCaMacHeaderSerializer::serialize(), inet::AckingMacHeaderSerializer::serialize(), inet::Ipv4HeaderSerializer::serialize(), inet::tcp::TcpHeaderSerializer::serialize(), inet::EtherAppRespSerializer::serialize(), inet::physicallayer::EthernetPhyHeaderSerializer::serialize(), inet::physicallayer::EthernetFragmentPhyHeaderSerializer::serialize(), inet::EthernetPaddingSerializer::serialize(), inet::GptpPacketSerializer::writeGptpPdelayReqPart(), and inet::GptpPacketSerializer::writeGptpSyncPart().
writeBytes() [1/2]
void inet::MemoryOutputStream::writeBytes (const std::vector< uint8_t > & bytes, B offset = B(0), B length = B(-1)) inline
Writes a sequence of bytes to the end of the stream keeping the original byte order and in MSB to LSB bit order.
{
         assert(isByteAligned());
         auto end = length == B(-1) ? B(bytes.size()) : offset + length;
         assert(b(0) <= offset && offset <= B(bytes.size()));
         assert(b(0) <= end && end <= B(bytes.size()));
         assert(offset <= end);
         data.insert(data.end(), bytes.begin() + B(offset).get(), bytes.begin() + B(end).get());
         this->length += end - offset;
     }
Referenced by inet::BytesChunkSerializer::serialize(), inet::sctp::SctpHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::serialize(), inet::Ipv4HeaderSerializer::serialize(), inet::tcp::TcpHeaderSerializer::serialize(), and inet::FieldsChunkSerializer::serialize().
writeBytes() [2/2]
void inet::MemoryOutputStream::writeBytes (const uint8_t * buffer, B length) inline
Writes a sequence of bytes to the end of the stream keeping the original byte order and in MSB to LSB bit order.
{
         assert(isByteAligned());
         data.insert(data.end(), buffer, buffer + B(length).get());
         this->length += length;
     }
writeIpv4Address()
void inet::MemoryOutputStream::writeIpv4Address (Ipv4Address address) inline
Writes an Ipv4 address to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         writeUint32Be(address.getInt());
     }
Referenced by inet::DhcpMessageSerializer::serialize(), inet::DsdvHelloSerializer::serialize(), inet::TransportPseudoHeaderSerializer::serialize(), inet::IgmpHeaderSerializer::serialize(), inet::RipPacketSerializer::serialize(), inet::aodv::AodvControlPacketsSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::ArpPacketSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader(), inet::ospfv2::Ospfv2PacketSerializer::serializeNetworkLsa(), inet::Ipv4HeaderSerializer::serializeOption(), inet::ospfv2::Ospfv2PacketSerializer::serializeOspfHeader(), inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa(), and inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa().
writeIpv6Address()
void inet::MemoryOutputStream::writeIpv6Address (Ipv6Address address) inline
Writes an Ipv6 address to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         for (int i = 0; i < 4; i++)
             writeUint32Be(address.words()[i]);
     }
Referenced by inet::Ipv6HeaderSerializer::serialize(), inet::TransportPseudoHeaderSerializer::serialize(), inet::Icmpv6HeaderSerializer::serialize(), inet::aodv::AodvControlPacketsSerializer::serialize(), and inet::serializeIpv6NdOptions().
writeMacAddress()
void inet::MemoryOutputStream::writeMacAddress (MacAddress address) inline
Writes a MAC address to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
             writeByte(address.getAddressByte(i));
     }
Referenced by inet::BMacHeaderSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::EthernetMacAddressFieldsSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::CsmaCaMacHeaderSerializer::serialize(), inet::AckingMacHeaderSerializer::serialize(), inet::ArpPacketSerializer::serialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::EthernetMacHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MsduSubframeHeaderSerializer::serialize(), and inet::serializeIpv6NdOptions().
writeNBitsOfUint64Be()
void inet::MemoryOutputStream::writeNBitsOfUint64Be (uint64_t value, uint8_t n) inline
Writes n bits of a 64 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         if (n == 0 || n > 64)
             throw cRuntimeError("Can not write 0 bit or more than 64 bits.");
         uint64_t mul = 1 << (n - 1);
         for (int i = 0; i < n; ++i) {
             writeBit((value & mul) != 0);
             mul >>= 1;
         }
     }
Referenced by inet::Ipv6HeaderSerializer::serialize(), inet::rtp::RtcpPacketSerializer::serialize(), inet::rtp::RtpPacketSerializer::serialize(), inet::IgmpHeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::MplsPacketSerializer::serialize(), inet::PimPacketSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::aodv::AodvControlPacketsSerializer::serialize(), inet::physicallayer::Ieee80211FhssPhyHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::serialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serializeAsExternalLsa(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
writeString()
void inet::MemoryOutputStream::writeString (std::string s) inline
Writes a zero terminated string in the order of the characters.
{
         writeBytes(std::vector<uint8_t>(s.begin(), s.end()));
         writeByte(0);
     }
writeUint16Be()
void inet::MemoryOutputStream::writeUint16Be (uint16_t value) inline
Writes a 16 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 0));
     }
Referenced by inet::Ieee802EpdHeaderSerializer::serialize(), inet::EthernetControlFrameSerializer::serialize(), inet::Ieee8021rTagTpidHeaderSerializer::serialize(), inet::Ieee8022LlcHeaderSerializer::serialize(), inet::Ieee8021aeTagTpidHeaderSerializer::serialize(), inet::Ieee8021qTagTpidHeaderSerializer::serialize(), inet::Ipv6HeaderSerializer::serialize(), inet::rtp::RtcpPacketSerializer::serialize(), inet::rtp::RtpMpegPacketSerializer::serialize(), inet::rtp::RtpPacketSerializer::serialize(), inet::UnitDiskPhyHeaderSerializer::serialize(), inet::physicallayer::ApskPhyHeaderSerializer::serialize(), inet::IcmpHeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::EchoPacketSerializer::serialize(), inet::Icmpv6HeaderSerializer::serialize(), inet::IgmpHeaderSerializer::serialize(), inet::BMacHeaderSerializer::serialize(), inet::PimPacketSerializer::serialize(), inet::PppHeaderSerializer::serialize(), inet::RipPacketSerializer::serialize(), inet::SequenceNumberHeaderSerializer::serialize(), inet::TransportPseudoHeaderSerializer::serialize(), inet::UdpHeaderSerializer::serialize(), inet::VoipStreamPacketSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::CrcHeaderSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::CsmaCaMacHeaderSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::AckingMacHeaderSerializer::serialize(), inet::physicallayer::Ieee80211FhssPhyHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::serialize(), inet::ArpPacketSerializer::serialize(), inet::Ieee8021qTagEpdHeaderSerializer::serialize(), inet::Ieee8021rTagEpdHeaderSerializer::serialize(), inet::Ieee8021aeTagEpdHeaderSerializer::serialize(), inet::PppTrailerSerializer::serialize(), inet::EthernetTypeOrLengthFieldSerializer::serialize(), inet::physicallayer::Ieee80211IrPhyHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MsduSubframeHeaderSerializer::serialize(), inet::EthernetMacHeaderSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serialize(), inet::physicallayer::Ieee80211DsssPhyHeaderSerializer::serialize(), inet::physicallayer::Ieee80211HrDsssPhyHeaderSerializer::serialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::serialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::serialize(), inet::serializeIpv6NdOptions(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader(), inet::Ipv4HeaderSerializer::serializeOption(), inet::tcp::TcpHeaderSerializer::serializeOption(), inet::ospfv2::Ospfv2PacketSerializer::serializeOspfHeader(), inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa(), inet::GptpPacketSerializer::writeGptpBase(), inet::GptpPacketSerializer::writeGptpFollowUpInformationTlv(), and inet::GptpPacketSerializer::writePortIdentity().
writeUint16Le()
void inet::MemoryOutputStream::writeUint16Le (uint16_t value) inline
Writes a 16 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 0));
         writeByte(static_cast<uint8_t>(value >> 8));
     }
Referenced by inet::ieee80211::Ieee80211MacHeaderSerializer::serialize().
writeUint2()
void inet::MemoryOutputStream::writeUint2 (uint8_t value) inline
Writes a 2 bit unsigned integer to the end of the stream in MSB to LSB bit order.
{
         writeBit(value & 0x2);
         writeBit(value & 0x1);
     }
Referenced by inet::Ipv6HeaderSerializer::serialize().
writeUint24Be()
void inet::MemoryOutputStream::writeUint24Be (uint32_t value) inline
Writes a 24 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 0));
     }
Referenced by inet::ospfv2::Ospfv2PacketSerializer::serializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::serializeSummaryLsa(), and inet::GptpPacketSerializer::writeGptpFollowUpInformationTlv().
writeUint24Le()
void inet::MemoryOutputStream::writeUint24Le (uint32_t value) inline
Writes a 24 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 0));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 16));
     }
writeUint32Be()
void inet::MemoryOutputStream::writeUint32Be (uint32_t value) inline
Writes a 32 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 24));
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 0));
     }
Referenced by inet::Ieee8021aeTagTpidHeaderSerializer::serialize(), inet::rtp::RtcpPacketSerializer::serialize(), inet::rtp::RtpPacketSerializer::serialize(), inet::Ipv6HeaderSerializer::serialize(), inet::VoipStreamPacketSerializer::serialize(), inet::ApplicationPacketSerializer::serialize(), inet::RipPacketSerializer::serialize(), inet::IcmpHeaderSerializer::serialize(), inet::Icmpv6HeaderSerializer::serialize(), inet::TransportPseudoHeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::FcsHeaderSerializer::serialize(), inet::GenericAppMsgSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::DsdvHelloSerializer::serialize(), inet::IgmpHeaderSerializer::serialize(), inet::EtherAppReqSerializer::serialize(), inet::PimPacketSerializer::serialize(), inet::aodv::AodvControlPacketsSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::Ieee8021aeTagEpdHeaderSerializer::serialize(), inet::CsmaCaMacTrailerSerializer::serialize(), inet::EtherAppRespSerializer::serialize(), inet::ieee80211::Ieee80211MacTrailerSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serialize(), inet::EthernetFcsSerializer::serialize(), inet::ospfv2::Ospfv2PacketSerializer::serializeAsExternalLsa(), inet::serializeIpv6NdOptions(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader(), inet::Ipv4HeaderSerializer::serializeOption(), inet::tcp::TcpHeaderSerializer::serializeOption(), inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa(), inet::GptpPacketSerializer::writeGptpBase(), inet::GptpPacketSerializer::writeGptpFollowUpInformationTlv(), inet::GptpPacketSerializer::writeScaledNS(), and inet::GptpPacketSerializer::writeTimestamp().
writeUint32Le()
void inet::MemoryOutputStream::writeUint32Le (uint32_t value) inline
Writes a 32 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 0));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 24));
     }
writeUint4()
void inet::MemoryOutputStream::writeUint4 (uint8_t value) inline
Writes a 4 bit unsigned integer to the end of the stream in MSB to LSB bit order.
{
         writeBit(value & 0x8);
         writeBit(value & 0x4);
         writeBit(value & 0x2);
         writeBit(value & 0x1);
     }
Referenced by inet::Ipv6HeaderSerializer::serialize(), inet::rtp::RtpPacketSerializer::serialize(), inet::physicallayer::Ieee80211FhssPhyHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MpduSubframeHeaderSerializer::serialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::serialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::serialize(), and inet::GptpPacketSerializer::writeGptpBase().
writeUint48Be()
void inet::MemoryOutputStream::writeUint48Be (uint64_t value) inline
Writes a 48 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 40));
         writeByte(static_cast<uint8_t>(value >> 32));
         writeByte(static_cast<uint8_t>(value >> 24));
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 0));
     }
Referenced by inet::GptpPacketSerializer::writeTimestamp().
writeUint48Le()
void inet::MemoryOutputStream::writeUint48Le (uint64_t value) inline
Writes a 48 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 0));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 24));
         writeByte(static_cast<uint8_t>(value >> 32));
         writeByte(static_cast<uint8_t>(value >> 40));
     }
writeUint64Be()
void inet::MemoryOutputStream::writeUint64Be (uint64_t value) inline
Writes a 64 bit unsigned integer to the end of the stream in big endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 56));
         writeByte(static_cast<uint8_t>(value >> 48));
         writeByte(static_cast<uint8_t>(value >> 40));
         writeByte(static_cast<uint8_t>(value >> 32));
         writeByte(static_cast<uint8_t>(value >> 24));
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 0));
     }
Referenced by inet::rtp::RtcpPacketSerializer::serialize(), inet::XMacHeaderSerializer::serialize(), inet::BMacHeaderSerializer::serialize(), inet::GenericAppMsgSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::AckingMacHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::serialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::serialize(), inet::GptpPacketSerializer::writeClock8(), inet::GptpPacketSerializer::writePortIdentity(), and inet::GptpPacketSerializer::writeScaledNS().
writeUint64Le()
void inet::MemoryOutputStream::writeUint64Le (uint64_t value) inline
Writes a 64 bit unsigned integer to the end of the stream in little endian byte order and MSB to LSB bit order.
{
         writeByte(static_cast<uint8_t>(value >> 0));
         writeByte(static_cast<uint8_t>(value >> 8));
         writeByte(static_cast<uint8_t>(value >> 16));
         writeByte(static_cast<uint8_t>(value >> 24));
         writeByte(static_cast<uint8_t>(value >> 32));
         writeByte(static_cast<uint8_t>(value >> 40));
         writeByte(static_cast<uint8_t>(value >> 48));
         writeByte(static_cast<uint8_t>(value >> 56));
     }
writeUint8()
void inet::MemoryOutputStream::writeUint8 (uint8_t value) inline
Writes an 8 bit unsigned integer to the end of the stream in MSB to LSB bit order.
{
         writeByte(value);
     }
Referenced by inet::Ipv6HeaderSerializer::serialize(), inet::DhcpMessageSerializer::serialize(), inet::PppHeaderSerializer::serialize(), inet::FragmentNumberHeaderSerializer::serialize(), inet::Ieee8021dBpduSerializer::serialize(), inet::MplsPacketSerializer::serialize(), inet::Icmpv6HeaderSerializer::serialize(), inet::RipPacketSerializer::serialize(), inet::CsmaCaMacHeaderSerializer::serialize(), inet::AckingMacHeaderSerializer::serialize(), inet::ieee80211::Ieee80211MpduSubframeHeaderSerializer::serialize(), and inet::GptpPacketSerializer::writeGptpBase().
Member Data Documentation
data
std::vector<uint8_t> inet::MemoryOutputStream::data protected
This vector contains the bits that were written to this stream so far.
The first bit of the bit stream is stored in the most significant bit of the first byte. For the longest possible bit stream given the same number of bytes, the last bit of the bit stream is stored in the least significant bit of the last byte. In other cases some of the lower bits of the last byte are not used.
length
b inet::MemoryOutputStream::length protected
The length of the bit stream measured in bits.
The documentation for this class was generated from the following file:
MemoryOutputStream.h