INET Framework for OMNeT++/OMNEST: inet::SctpStatusReq Class Reference
inet::SctpStatusReq Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:175 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpStatusReq ()
SctpStatusReq (const SctpStatusReq &other)
virtual ~SctpStatusReq ()
SctpStatusReq & operator= (const SctpStatusReq &other)
virtual SctpStatusReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getState () const
virtual void setState (int state)
virtual const char * getStateName () const
virtual void setStateName (const char *stateName)
virtual const L3Address & getPathId () const
virtual L3Address & getPathIdForUpdate ()
virtual void setPathId (const L3Address &pathId)
virtual bool getActive () const
virtual void setActive (bool active)
Public Member Functions inherited from inet::SctpCommandReq
SctpCommandReq ()
SctpCommandReq (const SctpCommandReq &other)
virtual ~SctpCommandReq ()
SctpCommandReq & operator= (const SctpCommandReq &other)
virtual int getSocketId () const
virtual void setSocketId (int socketId)
virtual int getSid () const
virtual void setSid (int sid)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs)
virtual int getSsn () const
virtual void setSsn (int ssn)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered)
virtual double getPrValue () const
virtual void setPrValue (double prValue)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getGate () const
virtual void setGate (int gate)
virtual int getFd () const
virtual void setFd (int fd)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SctpStatusReq &)=delete
Protected Member Functions inherited from inet::SctpCommandReq
bool operator== (const SctpCommandReq &)=delete
Protected Attributes
int state = 0
::omnetpp::opp_string stateName
L3Address pathId
bool active = false
Protected Attributes inherited from inet::SctpCommandReq
int socketId = -1
int sid = -1
int numMsgs = 1
int ssn = -1
unsigned short sendUnordered = false
double prValue = 0
L3Address localAddr
L3Address remoteAddr
int localPort = -1
int remotePort = -1
int gate = -1
int fd = -1
Private Member Functions
void copy (const SctpStatusReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:175 by opp_msgtool.
class SctpStatusReq extends SctpCommandReq
{
    int state;
    string stateName;
    L3Address pathId;
    bool active;
}
Constructor & Destructor Documentation
SctpStatusReq() [1/2]
inet::SctpStatusReq::SctpStatusReq ()
SctpStatusReq() [2/2]
inet::SctpStatusReq::SctpStatusReq (const SctpStatusReq & other)
~SctpStatusReq()
virtual inet::SctpStatusReq::~SctpStatusReq () virtual
Member Function Documentation
copy()
void inet::SctpStatusReq::copy (const SctpStatusReq & other) private
dup()
virtual SctpStatusReq* inet::SctpStatusReq::dup () const inline override virtual
Reimplemented from inet::SctpCommandReq.
 {return new SctpStatusReq(*this);}
getActive()
virtual bool inet::SctpStatusReq::getActive () const virtual
Referenced by inet::SctpClient::socketStatusArrived(), inet::SctpPeer::socketStatusArrived(), and inet::SctpNatPeer::socketStatusArrived().
getPathId()
virtual const L3Address& inet::SctpStatusReq::getPathId () const virtual
Referenced by inet::SctpClient::socketStatusArrived(), inet::SctpPeer::socketStatusArrived(), and inet::SctpNatPeer::socketStatusArrived().
getPathIdForUpdate()
virtual L3Address& inet::SctpStatusReq::getPathIdForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<SctpStatusReq*>(this)->getPathId());}
getState()
virtual int inet::SctpStatusReq::getState () const virtual
getStateName()
virtual const char* inet::SctpStatusReq::getStateName () const virtual
operator=()
SctpStatusReq& inet::SctpStatusReq::operator= (const SctpStatusReq & other)
operator==()
bool inet::SctpStatusReq::operator== (const SctpStatusReq &) protected delete
parsimPack()
virtual void inet::SctpStatusReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpStatusReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimUnpacking().
setActive()
virtual void inet::SctpStatusReq::setActive (bool active) virtual
setPathId()
virtual void inet::SctpStatusReq::setPathId (const L3Address & pathId) virtual
Referenced by inet::sctp::SctpAssociation::pathStatusIndication().
setState()
virtual void inet::SctpStatusReq::setState (int state) virtual
Referenced by inet::sctp::SctpAssociation::process_STATUS().
setStateName()
virtual void inet::SctpStatusReq::setStateName (const char * stateName) virtual
Member Data Documentation
active
bool inet::SctpStatusReq::active = false protected
pathId
L3Address inet::SctpStatusReq::pathId protected
state
int inet::SctpStatusReq::state = 0 protected
stateName
::omnetpp::opp_string inet::SctpStatusReq::stateName protected
The documentation for this class was generated from the following file:
SctpCommand_m.h