INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmSymbol Class Reference
inet::physicallayer::Ieee80211OfdmSymbol Class Reference
#include <Ieee80211OfdmSymbol.h>
Public Member Functions
Ieee80211OfdmSymbol (const std::vector< const ApskSymbol * > &subcarrierSymbols)
Ieee80211OfdmSymbol ()
const std::vector< const ApskSymbol * > & getSubCarrierSymbols () const
int symbolSize () const
void pushApskSymbol (const ApskSymbol *apskSymbol, int subcarrierIndex)
void clearSymbols ()
Public Member Functions inherited from inet::physicallayer::ISymbol
virtual ~ISymbol ()
Protected Attributes
std::vector< const ApskSymbol * > subcarrierSymbols
Friends
std::ostream & operator<< (std::ostream &out, const Ieee80211OfdmSymbol &symbol)
Constructor & Destructor Documentation
Ieee80211OfdmSymbol() [1/2]
inet::physicallayer::Ieee80211OfdmSymbol::Ieee80211OfdmSymbol (const std::vector< const ApskSymbol * > & subcarrierSymbols) inline
 : subcarrierSymbols(subcarrierSymbols) {}
Ieee80211OfdmSymbol() [2/2]
inet::physicallayer::Ieee80211OfdmSymbol::Ieee80211OfdmSymbol () inline
 { subcarrierSymbols.resize(53, nullptr); } // (48 + 4 + 1), but one of them is skipped.
Member Function Documentation
clearSymbols()
void inet::physicallayer::Ieee80211OfdmSymbol::clearSymbols () inline
 { subcarrierSymbols.resize(53, nullptr); }
getSubCarrierSymbols()
const std::vector<const ApskSymbol *>& inet::physicallayer::Ieee80211OfdmSymbol::getSubCarrierSymbols () const inline
 { return subcarrierSymbols; }
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::corruptOfdmSymbol(), and inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol().
pushApskSymbol()
void inet::physicallayer::Ieee80211OfdmSymbol::pushApskSymbol (const ApskSymbol * apskSymbol, int subcarrierIndex)
 {
     if (subcarrierIndex >= 53)
         throw cRuntimeError("Out of range with subcarrierIndex = %d", subcarrierIndex);
     subcarrierSymbols[subcarrierIndex] = apskSymbol;
 }
Referenced by inet::physicallayer::Ieee80211OfdmModulator::insertPilotSubcarriers(), and inet::physicallayer::Ieee80211OfdmModulator::modulate().
symbolSize()
int inet::physicallayer::Ieee80211OfdmSymbol::symbolSize () const inline
 { return subcarrierSymbols.size(); }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const Ieee80211OfdmSymbol & symbol) friend
 {
     if (symbol.subcarrierSymbols[0])
         out << *symbol.subcarrierSymbols[0];
     else
         out << "UNDEFINED SYMBOL";
     for (unsigned int i = 1; i < symbol.subcarrierSymbols.size(); i++)
         if (symbol.subcarrierSymbols[i])
             out << " " << *symbol.subcarrierSymbols[i];
         else
             out << " UNDEFINED SYMBOL";
     return out;
 }
Member Data Documentation
subcarrierSymbols
std::vector<const ApskSymbol *> inet::physicallayer::Ieee80211OfdmSymbol::subcarrierSymbols protected
Referenced by inet::physicallayer::operator<<(), and pushApskSymbol().
The documentation for this class was generated from the following files:
Ieee80211OfdmSymbol.h
Ieee80211OfdmSymbol.cc