INET Framework for OMNeT++/OMNEST: inet::SctpPathInfo Class Reference
inet::SctpPathInfo Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:216 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpPathInfo (const char *name=nullptr)
SctpPathInfo (const SctpPathInfo &other)
virtual ~SctpPathInfo ()
SctpPathInfo & operator= (const SctpPathInfo &other)
virtual SctpPathInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const L3Address & getRemoteAddress () const
virtual L3Address & getRemoteAddressForUpdate ()
virtual void setRemoteAddress (const L3Address &remoteAddress)
Protected Member Functions
bool operator== (const SctpPathInfo &)=delete
Protected Attributes
L3Address remoteAddress
Private Member Functions
void copy (const SctpPathInfo &other)
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:216 by opp_msgtool.
class SctpPathInfo extends cNamedObject
{
    L3Address remoteAddress;
}
Constructor & Destructor Documentation
SctpPathInfo() [1/2]
inet::SctpPathInfo::SctpPathInfo (const char * name = nullptr)
SctpPathInfo() [2/2]
inet::SctpPathInfo::SctpPathInfo (const SctpPathInfo & other)
~SctpPathInfo()
virtual inet::SctpPathInfo::~SctpPathInfo () virtual
Member Function Documentation
copy()
void inet::SctpPathInfo::copy (const SctpPathInfo & other) private
dup()
virtual SctpPathInfo* inet::SctpPathInfo::dup () const inline override virtual
 {return new SctpPathInfo(*this);}
Referenced by inet::sctp::SctpAssociation::SctpAssociation(), and inet::sctp::SctpPathVariables::SctpPathVariables().
getRemoteAddress()
virtual const L3Address& inet::SctpPathInfo::getRemoteAddress () const virtual
Referenced by inet::sctp::SctpAssociation::process_PRIMARY(), and inet::sctp::SctpAssociation::processTimer().
getRemoteAddressForUpdate()
virtual L3Address& inet::SctpPathInfo::getRemoteAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<SctpPathInfo*>(this)->getRemoteAddress());}
operator=()
SctpPathInfo& inet::SctpPathInfo::operator= (const SctpPathInfo & other)
operator==()
bool inet::SctpPathInfo::operator== (const SctpPathInfo &) protected delete
parsimPack()
virtual void inet::SctpPathInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpPathInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setRemoteAddress()
virtual void inet::SctpPathInfo::setRemoteAddress (const L3Address & remoteAddress) virtual
Referenced by inet::sctp::SctpAssociation::SctpAssociation(), and inet::sctp::SctpPathVariables::SctpPathVariables().
Member Data Documentation
remoteAddress
L3Address inet::SctpPathInfo::remoteAddress protected
The documentation for this class was generated from the following file:
SctpCommand_m.h