INET Framework for OMNeT++/OMNEST: inet::SharingTagSet Class Reference
inet::SharingTagSet Class Reference
This class maintains a set of tags.
#include <SharingTagSet.h>
Public Member Functions
Constructors and operators
SharingTagSet ()
SharingTagSet (const SharingTagSet &other)
SharingTagSet (SharingTagSet &&other)
SharingTagSet & operator= (const SharingTagSet &other)
SharingTagSet & operator= (SharingTagSet &&other)
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
Type independent functions
int getNumTags () const
Returns the number of tags.
const Ptr< const TagBase > & getTag (int index) const
Returns the shared tag at the given index.
const Ptr< TagBase > getTagForUpdate (int index)
Returns the exclusively owned tag at the given index for update.
void clearTags ()
Clears the set of tags.
void copyTags (const SharingTagSet &other)
Copies the set of tags from the other set.
Type dependent functions
template<typename T >
const Ptr< const T > findTag () const
Returns the shared tag of the provided type, or returns nullptr if no such tag is present.
template<typename T >
const Ptr< T > findTagForUpdate ()
Returns the exclusively owned tag of the provided type for update, or returns nullptr if no such tag is present.
template<typename T >
const Ptr< const T > getTag () const
Returns the shared tag of the provided type, or throws an exception if no such tag is present.
template<typename T >
const Ptr< T > getTagForUpdate ()
Returns the exclusively owned tag of the provided type for update, or throws an exception if no such tag is present.
template<typename T >
const Ptr< T > addTag ()
Returns a newly added exclusively owned tag of the provided type for update, or throws an exception if such a tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent ()
Returns a newly added exclusively owned tag of the provided type if absent, or returns the exclusively owned tag that is already present for update.
template<typename T >
const Ptr< T > removeTag ()
Removes the tag of the provided type and returns it for update, or throws an exception if no such tag is present.
template<typename T >
const Ptr< T > removeTagIfPresent ()
Removes the tag of the provided type if present and returns it for update, or returns nullptr if no such tag is present.
Protected Member Functions
void setTag (int index, const Ptr< const TagBase > &tag)
void addTag (const Ptr< const TagBase > &tag)
const Ptr< TagBase > removeTag (int index)
int getTagIndex (const std::type_info &typeInfo) const
template<typename T >
int getTagIndex () const
void ensureTagsVectorAllocated ()
void prepareTagsVectorForUpdate ()
Protected Attributes
Ptr< SharedVector< Ptr< const TagBase > > > tags
Both the vector and the individual tags can be shared among different instances of this class.
Detailed Description
This class maintains a set of tags.
Tags are usually small data strcutures that hold some relevant information. Tags are identified by their type, which means that this class supports adding the same tag type only once. Tags are shared between other instances of this class. Tags can be changed with a copy-on-write mechanism.
Constructor & Destructor Documentation
SharingTagSet() [1/3]
inet::SharingTagSet::SharingTagSet () inline
 : tags(nullptr) {}
SharingTagSet() [2/3]
inet::SharingTagSet::SharingTagSet (const SharingTagSet & other) inline
 : tags(other.tags) {}
SharingTagSet() [3/3]
inet::SharingTagSet::SharingTagSet (SharingTagSet && other) inline
 : tags(other.tags) { other.tags = nullptr; }
Member Function Documentation
addTag() [1/2]
template<typename T > const Ptr< T > inet::SharingTagSet::addTag inline
Returns a newly added exclusively owned tag of the provided type for update, or throws an exception if such a tag is already present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index != -1)
         throw cRuntimeError("Tag '%s' is present", opp_typename(typeid(T)));
     const Ptr<T>& tag = makeShared<T>();
     addTag(tag);
     return tag;
 }
Referenced by addTagIfAbsent(), and parsimUnpack().
addTag() [2/2]
void inet::SharingTagSet::addTag (const Ptr< const TagBase > & tag) protected
 {
     ensureTagsVectorAllocated();
     prepareTagsVectorForUpdate();
     tags->push_back(tag);
 }
addTagIfAbsent()
template<typename T > const Ptr< T > inet::SharingTagSet::addTagIfAbsent inline
Returns a newly added exclusively owned tag of the provided type if absent, or returns the exclusively owned tag that is already present for update.
 {
     SELFDOC_FUNCTION_T;
     const Ptr<T>& tag = findTagForUpdate<T>();
     if (tag != nullptr)
         return tag;
     else {
         const Ptr<T>& tag = makeShared<T>();
         addTag(tag);
         return tag;
     }
 }
clearTags()
void inet::SharingTagSet::clearTags () inline
Clears the set of tags.
 {
 #ifdef INET_WITH_SELFDOC
     selfDoc(__FUNCTION__, "");
 #endif // INET_WITH_SELFDOC
     tags = nullptr;
 }
Referenced by parsimUnpack().
copyTags()
void inet::SharingTagSet::copyTags (const SharingTagSet & other) inline
Copies the set of tags from the other set.
 {
     operator=(source);
 }
ensureTagsVectorAllocated()
void inet::SharingTagSet::ensureTagsVectorAllocated () protected
 {
     if (tags == nullptr) {
         tags = makeShared<SharedVector<Ptr<const TagBase>>>();
         tags->reserve(16);
     }
 }
Referenced by addTag().
findTag()
template<typename T > const Ptr< const T > inet::SharingTagSet::findTag inline
Returns the shared tag of the provided type, or returns nullptr if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     return index == -1 ? nullptr : staticPtrCast<const T>(getTag(index));
 }
Referenced by inet::SctpNatServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::SctpServer::makeReceiveRequest(), inet::SctpPeer::socketDataNotificationArrived(), and inet::SctpNatPeer::socketDataNotificationArrived().
findTagForUpdate()
template<typename T > const Ptr< T > inet::SharingTagSet::findTagForUpdate inline
Returns the exclusively owned tag of the provided type for update, or returns nullptr if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     return index == -1 ? nullptr : staticPtrCast<T>(getTagForUpdate(index));
 }
getNumTags()
int inet::SharingTagSet::getNumTags () const inline
Returns the number of tags.
 {
     return tags == nullptr ? 0 : tags->size();
 }
Referenced by inet::Packet::forEachChild(), and parsimPack().
getTag() [1/2]
template<typename T > const Ptr< const T > inet::SharingTagSet::getTag inline
Returns the shared tag of the provided type, or throws an exception if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return staticPtrCast<const T>(getTag(index));
 }
Referenced by findTag(), and getTagForUpdate().
getTag() [2/2]
const Ptr< const TagBase > & inet::SharingTagSet::getTag (int index) const inline
Returns the shared tag at the given index.
The index must be in the range [0, getNumTags()).
 {
     return (*tags)[index];
 }
Referenced by inet::Packet::forEachChild().
getTagForUpdate() [1/2]
template<typename T > const Ptr< T > inet::SharingTagSet::getTagForUpdate inline
Returns the exclusively owned tag of the provided type for update, or throws an exception if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return staticPtrCast<T>(getTagForUpdate(index));
 }
Referenced by findTagForUpdate(), and removeTag().
getTagForUpdate() [2/2]
const Ptr< TagBase > inet::SharingTagSet::getTagForUpdate (int index) inline
Returns the exclusively owned tag at the given index for update.
The index must be in the range [0, getNumTags()).
 {
     const Ptr<const TagBase>& tag = getTag(index);
     prepareTagsVectorForUpdate();
     if (tag.use_count() != 1)
         setTag(index, tag->dupShared());
     return constPtrCast<TagBase>(getTag(index));
 }
getTagIndex() [1/2]
template<typename T > int inet::SharingTagSet::getTagIndex inline protected
 {
     return getTagIndex(typeid(T));
 }
getTagIndex() [2/2]
int inet::SharingTagSet::getTagIndex (const std::type_info & typeInfo) const protected
 {
     if (tags == nullptr)
         return -1;
     else {
         int numTags = tags->size();
         for (int index = 0; index < numTags; index++) {
             const Ptr<const TagBase>& tag = (*tags)[index];
             const TagBase *tagObject = tag.get();
             if (typeInfo == typeid(*tagObject))
                 return index;
         }
         return -1;
     }
 }
operator=() [1/2]
SharingTagSet & inet::SharingTagSet::operator= (const SharingTagSet & other) inline
 {
     if (this != &other)
         tags = other.tags;
     return *this;
 }
Referenced by copyTags().
operator=() [2/2]
SharingTagSet & inet::SharingTagSet::operator= (SharingTagSet && other) inline
 {
     if (this != &other) {
         tags = other.tags;
         other.tags = nullptr;
     }
     return *this;
 }
parsimPack()
void inet::SharingTagSet::parsimPack (cCommBuffer * buffer) const override virtual
 {
     buffer->pack(getNumTags());
     if (tags != nullptr)
         for (auto tag : *tags)
             buffer->packObject(const_cast<TagBase *>(tag.get()));
 }
Referenced by inet::Packet::parsimPack().
parsimUnpack()
void inet::SharingTagSet::parsimUnpack (cCommBuffer * buffer) override virtual
 {
     clearTags();
     int size;
     buffer->unpack(size);
     for (int i = 0; i < size; i++) {
         auto tag = check_and_cast<TagBase *>(buffer->unpackObject());
         addTag(tag->shared_from_this());
     }
 }
Referenced by inet::Packet::parsimUnpack().
prepareTagsVectorForUpdate()
void inet::SharingTagSet::prepareTagsVectorForUpdate () protected
 {
     if (tags.use_count() != 1) {
         const auto& newTags = makeShared<SharedVector<Ptr<const TagBase>>>();
         newTags->insert(newTags->begin(), tags->begin(), tags->end());
         tags = newTags;
     }
 }
Referenced by addTag(), getTagForUpdate(), and removeTag().
removeTag() [1/2]
template<typename T > const Ptr< T > inet::SharingTagSet::removeTag inline
Removes the tag of the provided type and returns it for update, or throws an exception if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return staticPtrCast<T>(removeTag(index));
 }
Referenced by removeTagIfPresent().
removeTag() [2/2]
const Ptr< TagBase > inet::SharingTagSet::removeTag (int index) protected
 {
     prepareTagsVectorForUpdate();
     const Ptr<TagBase> tag = getTagForUpdate(index);
     tags->erase(tags->begin() + index);
     if (tags->size() == 0)
         tags = nullptr;
     return constPtrCast<TagBase>(tag);
 }
removeTagIfPresent()
template<typename T > const Ptr< T > inet::SharingTagSet::removeTagIfPresent inline
Removes the tag of the provided type if present and returns it for update, or returns nullptr if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     return index == -1 ? nullptr : staticPtrCast<T>(removeTag(index));
 }
setTag()
void inet::SharingTagSet::setTag (int index, const Ptr< const TagBase > & tag) inline protected
 {
     (*tags)[index] = tag;
 }
Referenced by getTagForUpdate().
Member Data Documentation
tags
Ptr<SharedVector<Ptr<const TagBase> > > inet::SharingTagSet::tags protected
Both the vector and the individual tags can be shared among different instances of this class.
Referenced by addTag(), clearTags(), ensureTagsVectorAllocated(), getNumTags(), getTag(), getTagIndex(), operator=(), parsimPack(), prepareTagsVectorForUpdate(), and removeTag().
The documentation for this class was generated from the following files:
SharingTagSet.h
SharingTagSet.cc