INET Framework for OMNeT++/OMNEST: inet::StreamThroughTransmitter Class Reference
inet::StreamThroughTransmitter Class Reference
#include <StreamThroughTransmitter.h>
Public Member Functions
virtual ~StreamThroughTransmitter ()
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::StreamingTransmitterBase
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::PacketTransmitterBase
virtual ~PacketTransmitterBase ()
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
Public Member Functions inherited from inet::ClockUserModuleMixin< OperationalMixin< PacketProcessorBase > >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual void startTx (Packet *packet, bps datarate, b position)
virtual void progressTx (Packet *packet, bps datarate, b position)
virtual void endTx ()
virtual void abortTx () override
virtual void scheduleBufferUnderrunTimer ()
Protected Member Functions inherited from inet::StreamingTransmitterBase
virtual void scheduleAt (simtime_t t, cMessage *message) override
virtual void scheduleTxEndTimer (Signal *signal)
Protected Member Functions inherited from inet::PacketTransmitterBase
virtual void finish () override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual Signal * encodePacket (Packet *packet)
virtual void prepareSignal (Signal *signal)
virtual void sendSignalStart (Signal *signal, int transmissionId)
virtual void sendSignalProgress (Signal *signal, int transmissionId, b bitPosition, clocktime_t timePosition)
virtual void sendSignalEnd (Signal *signal, int transmissionId)
virtual clocktime_t calculateClockTimeDuration (const Packet *packet) const
virtual simtime_t calculateDuration (clocktime_t clockTimeDuration) const
virtual bool isTransmitting () const
Protected Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
simtime_t lastTxProgressTime = -1
b lastTxProgressPosition = b(-1)
bps lastInputDatarate = bps(NaN)
simtime_t lastInputProgressTime = -1
b lastInputProgressPosition = b(-1)
cMessage * bufferUnderrunTimer = nullptr
Protected Attributes inherited from inet::StreamingTransmitterBase
cChannel * transmissionChannel = nullptr
Protected Attributes inherited from inet::PacketTransmitterBase
cPar * dataratePar = nullptr
cGate * inputGate = nullptr
cGate * outputGate = nullptr
ModuleRef< IActivePacketSource > producer
bps txDatarate = bps(NaN)
Signal * txSignal = nullptr
ClockEvent * txEndTimer = nullptr
simtime_t txStartTime = -1
clocktime_t txStartClockTime = -1
clocktime_t txDurationClockTime = -1
Protected Attributes inherited from inet::OperationalMixin< PacketProcessorBase >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< PacketProcessorBase >
enum State
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Constructor & Destructor Documentation
~StreamThroughTransmitter()
virtual inet::StreamThroughTransmitter::~StreamThroughTransmitter () inline virtual
 { cancelAndDelete(bufferUnderrunTimer); }
Member Function Documentation
abortTx()
void inet::StreamThroughTransmitter::abortTx () override protected virtual
Implements inet::StreamingTransmitterBase.
 {
     // 1. check current state
     ASSERT(isTransmitting());
     // 2. create new truncated signal
     auto packet = check_and_cast<Packet *>(txSignal->decapsulate());
     // TODO we can't just simply cut the packet proportionally with time because it's not always the case (modulation, scrambling, etc.)
     simtime_t timePosition = simTime() - txStartTime;
     b dataPosition = b(std::floor(txDatarate.get() * timePosition.dbl()));
     packet->eraseAtBack(packet->getTotalLength() - dataPosition);
     packet->setBitError(true);
     auto signal = encodePacket(packet);
     signal->setDuration(timePosition);
     // 3. delete old signal
     delete txSignal;
     txSignal = nullptr;
     // 4. send signal end to receiver and notify subscribers
     EV_INFO << "Aborting transmission" << EV_FIELD(packet) << EV_FIELD(datarate, txDatarate) << EV_ENDL;
     handlePacketProcessed(packet);
     emit(transmissionEndedSignal, signal);
     sendSignalEnd(signal, packet->getTransmissionId());
     // 5. clear internal state
     txDatarate = bps(NaN);
     txStartTime = -1;
     txStartClockTime = -1;
     lastTxProgressTime = -1;
     lastTxProgressPosition = b(-1);
     lastInputDatarate = bps(NaN);
     lastInputProgressTime = -1;
     lastInputProgressPosition = b(-1);
     // 6. notify producer
     auto gate = inputGate->getPathStartGate();
     if (producer != nullptr) {
         producer->handlePushPacketProcessed(packet, gate, true);
         producer->handleCanPushPacketChanged(gate);
     }
 }
Referenced by handleCrashOperation(), and handleStopOperation().
endTx()
void inet::StreamThroughTransmitter::endTx () protected virtual
 {
     // 1. check current state
     ASSERT(isTransmitting());
     // 2. send signal end to receiver and notify subscribers
     auto packet = check_and_cast<Packet *>(txSignal->getEncapsulatedPacket());
     EV_INFO << "Ending transmission" << EV_FIELD(packet) << EV_FIELD(datarate, txDatarate) << EV_ENDL;
     handlePacketProcessed(packet);
     emit(transmissionEndedSignal, txSignal);
     sendSignalEnd(txSignal, packet->getTransmissionId());
     // 3. clear internal state
     txSignal = nullptr;
     txDatarate = bps(NaN);
     txStartTime = -1;
     txStartClockTime = -1;
     lastTxProgressTime = -1;
     lastTxProgressPosition = b(-1);
     lastInputDatarate = bps(NaN);
     lastInputProgressTime = -1;
     lastInputProgressPosition = b(-1);
     // 4. notify producer
     auto gate = inputGate->getPathStartGate();
     if (producer != nullptr) {
         producer->handlePushPacketProcessed(packet, gate, true);
         producer->handleCanPushPacketChanged(gate);
     }
 }
Referenced by handleMessageWhenUp().
handleCrashOperation()
void inet::StreamThroughTransmitter::handleCrashOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 {
     if (isTransmitting())
         abortTx();
 }
handleMessageWhenUp()
void inet::StreamThroughTransmitter::handleMessageWhenUp (cMessage * message) override protected virtual
Reimplemented from inet::PacketTransmitterBase.
 {
     if (message == txEndTimer)
         endTx();
     else if (message == bufferUnderrunTimer)
         throw cRuntimeError("Buffer underrun during transmission");
     else
         StreamingTransmitterBase::handleMessageWhenUp(message);
     updateDisplayString();
 }
handleStopOperation()
void inet::StreamThroughTransmitter::handleStopOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 {
     if (isTransmitting())
         abortTx();
 }
initialize()
void inet::StreamThroughTransmitter::initialize (int stage) override protected virtual
Reimplemented from inet::StreamingTransmitterBase.
 {
     StreamingTransmitterBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL)
         bufferUnderrunTimer = new cMessage("BufferUnderrunTimer");
 }
progressTx()
void inet::StreamThroughTransmitter::progressTx (Packet * packet, bps datarate, b position) protected virtual
 {
     // 1. check current state
     ASSERT(isTransmitting());
     // 2. store input progress
     b inputProgressPosition = lastInputProgressPosition + b(std::floor((simTime() - lastInputProgressTime).dbl() * lastInputDatarate.get()));
     auto txPacket = check_and_cast<Packet *>(txSignal->getEncapsulatedPacket());
     bool isInputProgressAtEnd = inputProgressPosition == packet->getTotalLength() && packet->getTotalLength() == txPacket->getTotalLength();
     bool isPacketUnchangedSinceLastProgress = isInputProgressAtEnd || packet->peekAll()->containsSameData(*txPacket->peekAll().get());
     lastInputDatarate = datarate;
     lastInputProgressTime = simTime();
     lastInputProgressPosition = position;
     // 3. store transmission progress
     clocktime_t timePosition = getClockTime() - txStartClockTime;
     lastTxProgressTime = simTime();
     lastTxProgressPosition = b(std::floor(txDatarate.get() * timePosition.dbl()));
     if (isPacketUnchangedSinceLastProgress)
         delete packet;
     else {
         // 4. create progress signal
         auto signal = encodePacket(packet);
         delete txSignal;
         txSignal = signal->dup();
         // 5. send signal progress
         EV_INFO << "Progressing transmission" << EV_FIELD(packet) << EV_FIELD(datarate, txDatarate) << EV_ENDL;
         sendSignalProgress(signal, packet->getTransmissionId(), lastTxProgressPosition, timePosition);
     }
     // 6. reschedule timers
     scheduleTxEndTimer(txSignal);
     scheduleBufferUnderrunTimer();
 }
Referenced by pushPacketEnd(), and pushPacketProgress().
pushPacket()
virtual void inet::StreamThroughTransmitter::pushPacket (Packet * packet, cGate * gate) inline override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
 { throw cRuntimeError("Invalid operation"); }
pushPacketEnd()
void inet::StreamThroughTransmitter::pushPacketEnd (Packet * packet, cGate * gate) override virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Reimplemented from inet::PacketTransmitterBase.
 {
     Enter_Method("pushPacketEnd");
     ASSERT(txSignal != nullptr);
     take(packet);
     progressTx(packet, bps(NaN), packet->getTotalLength());
     updateDisplayString();
 }
pushPacketProgress()
void inet::StreamThroughTransmitter::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) override virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Reimplemented from inet::PacketTransmitterBase.
 {
     Enter_Method("pushPacketProgress");
     take(packet);
     if (isTransmitting())
         progressTx(packet, datarate, position);
     else
         startTx(packet, datarate, position);
     updateDisplayString();
 }
pushPacketStart()
void inet::StreamThroughTransmitter::pushPacketStart (Packet * packet, cGate * gate, bps datarate) override virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Reimplemented from inet::PacketTransmitterBase.
 {
     Enter_Method("pushPacketStart");
     take(packet);
     startTx(packet, datarate, b(0));
     updateDisplayString();
 }
scheduleBufferUnderrunTimer()
void inet::StreamThroughTransmitter::scheduleBufferUnderrunTimer () protected virtual
 {
     cancelEvent(bufferUnderrunTimer);
     if (lastInputDatarate < txDatarate) {
         // Underrun occurs when the following two values become equal:
         // inputProgressPosition = lastInputProgressPosition + inputDatarate * (simTime() - lastInputProgressTime)
         // txProgressPosition = lastTxProgressPosition + txDatarate * (simTime() - lastTxProgressTime)
         simtime_t bufferUnderrunTime = s((-lastInputProgressPosition + lastInputDatarate * s(lastInputProgressTime.dbl()) + lastTxProgressPosition - txDatarate * s(lastTxProgressTime.dbl())) / (lastInputDatarate - txDatarate)).get();
         EV_INFO << "Scheduling buffer underrun timer" << EV_FIELD(at, bufferUnderrunTime.ustr()) << EV_ENDL;
         scheduleAt(bufferUnderrunTime, bufferUnderrunTimer);
     }
 }
Referenced by progressTx(), and startTx().
startTx()
void inet::StreamThroughTransmitter::startTx (Packet * packet, bps datarate, b position) protected virtual
 {
     // 1. check current state
     ASSERT(!isTransmitting());
     // 2. store input progress
     lastInputDatarate = datarate;
     lastInputProgressTime = simTime();
     lastInputProgressPosition = position;
     // 3. store transmission progress
     txDatarate = bps(*dataratePar);
     txStartTime = simTime();
     txStartClockTime = getClockTime();
     lastTxProgressTime = simTime();
     lastTxProgressPosition = b(0);
     // 4. create signal
     auto signal = encodePacket(packet);
     txSignal = signal->dup();
     // 5. send signal start and notify subscribers
     EV_INFO << "Starting transmission" << EV_FIELD(packet) << EV_FIELD(datarate, txDatarate) << EV_ENDL;
     emit(transmissionStartedSignal, signal);
     sendSignalStart(signal, packet->getTransmissionId());
     // 6. schedule transmission end timer and buffer underrun timer
     scheduleTxEndTimer(txSignal);
     scheduleBufferUnderrunTimer();
 }
Referenced by pushPacketProgress(), and pushPacketStart().
supportsPacketStreaming()
virtual bool inet::StreamThroughTransmitter::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return true; }
Member Data Documentation
bufferUnderrunTimer
cMessage* inet::StreamThroughTransmitter::bufferUnderrunTimer = nullptr protected
Referenced by handleMessageWhenUp(), initialize(), and scheduleBufferUnderrunTimer().
lastInputDatarate
bps inet::StreamThroughTransmitter::lastInputDatarate = bps(NaN) protected
Referenced by abortTx(), endTx(), progressTx(), scheduleBufferUnderrunTimer(), and startTx().
lastInputProgressPosition
b inet::StreamThroughTransmitter::lastInputProgressPosition = b(-1) protected
Referenced by abortTx(), endTx(), progressTx(), scheduleBufferUnderrunTimer(), and startTx().
lastInputProgressTime
simtime_t inet::StreamThroughTransmitter::lastInputProgressTime = -1 protected
Referenced by abortTx(), endTx(), progressTx(), scheduleBufferUnderrunTimer(), and startTx().
lastTxProgressPosition
b inet::StreamThroughTransmitter::lastTxProgressPosition = b(-1) protected
Referenced by abortTx(), endTx(), progressTx(), scheduleBufferUnderrunTimer(), and startTx().
lastTxProgressTime
simtime_t inet::StreamThroughTransmitter::lastTxProgressTime = -1 protected
Referenced by abortTx(), endTx(), progressTx(), scheduleBufferUnderrunTimer(), and startTx().
The documentation for this class was generated from the following files:
StreamThroughTransmitter.h
StreamThroughTransmitter.cc