INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmModulation Class Reference
inet::physicallayer::Ieee80211OfdmModulation Class Reference
#include <Ieee80211OfdmModulation.h>
Public Member Functions
Ieee80211OfdmModulation (const ApskModulationBase *subcarrierModulation)
const ApskModulationBase * getSubcarrierModulation () const
virtual double calculateBER (double snir, Hz bandwidth, bps bitrate) const override
Returns the bit error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
virtual double calculateSER (double snir, Hz bandwidth, bps bitrate) const override
Returns the symbol error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const ApskModulationBase * subcarrierModulation
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211OfdmModulation()
inet::physicallayer::Ieee80211OfdmModulation::Ieee80211OfdmModulation (const ApskModulationBase * subcarrierModulation)
                                                                                                :
     subcarrierModulation(subcarrierModulation)
 {
 }
Member Function Documentation
calculateBER()
virtual double inet::physicallayer::Ieee80211OfdmModulation::calculateBER (double snir, Hz bandwidth, bps bitrate) const inline override virtual
Returns the bit error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
Implements inet::physicallayer::IModulation.
 { return subcarrierModulation->calculateBER(snir, bandwidth, bitrate); }
calculateSER()
virtual double inet::physicallayer::Ieee80211OfdmModulation::calculateSER (double snir, Hz bandwidth, bps bitrate) const inline override virtual
Returns the symbol error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
Implements inet::physicallayer::IModulation.
 { return subcarrierModulation->calculateSER(snir, bandwidth, bitrate); }
getSubcarrierModulation()
const ApskModulationBase* inet::physicallayer::Ieee80211OfdmModulation::getSubcarrierModulation () const inline
 { return subcarrierModulation; }
Referenced by inet::physicallayer::Ieee80211OfdmModeBase::computeGrossBitrate(), inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum(), inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol(), inet::physicallayer::Ieee80211VhtCompliantCodes::getCompliantCode(), inet::physicallayer::Ieee80211HtCompliantCodes::getCompliantCode(), inet::physicallayer::Ieee80211OfdmDataMode::getDuration(), inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength(), and inet::physicallayer::Ieee80211OfdmModulator::modulate().
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmModulation::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Ieee80211OfdmModulation";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(subcarrierModulation, printFieldToString(subcarrierModulation, level + 1, evFlags));
     return stream;
 }
Member Data Documentation
subcarrierModulation
const ApskModulationBase* inet::physicallayer::Ieee80211OfdmModulation::subcarrierModulation protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
Ieee80211OfdmModulation.h
Ieee80211OfdmModulation.cc