INET Framework for OMNeT++/OMNEST: inet::utils::filters::PacketRegionValue Class Reference
inet::utils::filters::PacketRegionValue Class Reference
Public Attributes
Packet * packet = nullptr
b offset = b(-1)
b length = b(-1)
cValue value
Member Data Documentation
length
b inet::utils::filters::PacketRegionValue::length = b(-1)
Referenced by inet::utils::filters::ResidenceTimePerRegionFilter::receiveSignal(), inet::utils::filters::LifeTimePerRegionFilter::receiveSignal(), inet::utils::filters::ElapsedTimePerRegionFilter::receiveSignal(), inet::utils::filters::DelayingTimePerRegionFilter::receiveSignal(), inet::utils::filters::ProcessingTimePerRegionFilter::receiveSignal(), inet::utils::filters::QueueingTimePerRegionFilter::receiveSignal(), inet::utils::filters::PropagationTimePerRegionFilter::receiveSignal(), inet::utils::filters::TransmissionTimePerRegionFilter::receiveSignal(), and inet::utils::filters::PacketTransmissionTimePerRegionFilter::receiveSignal().
offset
b inet::utils::filters::PacketRegionValue::offset = b(-1)
Referenced by inet::utils::filters::ResidenceTimePerRegionFilter::receiveSignal(), inet::utils::filters::LifeTimePerRegionFilter::receiveSignal(), inet::utils::filters::ElapsedTimePerRegionFilter::receiveSignal(), inet::utils::filters::DelayingTimePerRegionFilter::receiveSignal(), inet::utils::filters::ProcessingTimePerRegionFilter::receiveSignal(), inet::utils::filters::QueueingTimePerRegionFilter::receiveSignal(), inet::utils::filters::PropagationTimePerRegionFilter::receiveSignal(), inet::utils::filters::TransmissionTimePerRegionFilter::receiveSignal(), and inet::utils::filters::PacketTransmissionTimePerRegionFilter::receiveSignal().
packet
Packet* inet::utils::filters::PacketRegionValue::packet = nullptr
Referenced by inet::utils::filters::ResidenceTimePerRegionFilter::receiveSignal(), inet::utils::filters::LifeTimePerRegionFilter::receiveSignal(), inet::utils::filters::ElapsedTimePerRegionFilter::receiveSignal(), inet::utils::filters::DelayingTimePerRegionFilter::receiveSignal(), inet::utils::filters::ProcessingTimePerRegionFilter::receiveSignal(), inet::utils::filters::QueueingTimePerRegionFilter::receiveSignal(), inet::utils::filters::PropagationTimePerRegionFilter::receiveSignal(), inet::utils::filters::TransmissionTimePerRegionFilter::receiveSignal(), and inet::utils::filters::PacketTransmissionTimePerRegionFilter::receiveSignal().
value
cValue inet::utils::filters::PacketRegionValue::value
Referenced by inet::utils::filters::ResidenceTimePerRegionFilter::receiveSignal(), inet::utils::filters::LifeTimePerRegionFilter::receiveSignal(), inet::utils::filters::ElapsedTimePerRegionFilter::receiveSignal(), inet::utils::filters::DelayingTimePerRegionFilter::receiveSignal(), inet::utils::filters::ProcessingTimePerRegionFilter::receiveSignal(), inet::utils::filters::QueueingTimePerRegionFilter::receiveSignal(), inet::utils::filters::PropagationTimePerRegionFilter::receiveSignal(), inet::utils::filters::TransmissionTimePerRegionFilter::receiveSignal(), and inet::utils::filters::PacketTransmissionTimePerRegionFilter::receiveSignal().
The documentation for this class was generated from the following file:
common/ResultFilters.cc