INET Framework for OMNeT++/OMNEST: inet::visualizer::PacketDrop Class Reference
inet::visualizer::PacketDrop Class Reference
#include <PacketDropVisualizerBase.h>
Public Member Functions
PacketDrop (PacketDropReason reason, const cPacket *packet, const int moduleId, const Coord &position)
virtual ~PacketDrop ()
const cPacket * getPacket_ () const
const cModule * getModule () const
const cModule * getNetworkNode () const
const NetworkInterface * getNetworkInterface () const
const Coord & getPosition () const
Public Member Functions inherited from inet::PacketDropDetails
PacketDropDetails ()
PacketDropDetails (const PacketDropDetails &other)
virtual ~PacketDropDetails ()
PacketDropDetails & operator= (const PacketDropDetails &other)
virtual PacketDropDetails * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual PacketDropReason getReason () const
virtual void setReason (PacketDropReason reason)
virtual int getLimit () const
virtual void setLimit (int limit)
Protected Attributes
const cPacket * packet = nullptr
const int moduleId = -1
const Coord position
Protected Attributes inherited from inet::PacketDropDetails
PacketDropReason reason = static_cast<inet::PacketDropReason>(-1)
int limit = -1
Additional Inherited Members
Protected Member Functions inherited from inet::PacketDropDetails
bool operator== (const PacketDropDetails &)=delete
Constructor & Destructor Documentation
PacketDrop()
inet::visualizer::PacketDrop::PacketDrop (PacketDropReason reason, const cPacket * packet, const int moduleId, const Coord & position)
                                                                                                                 :
     packet(packet),
     moduleId(moduleId),
     position(position)
 {
     this->reason = reason;
 }
~PacketDrop()
inet::visualizer::PacketDrop::~PacketDrop () virtual
 {
     delete packet;
 }
Member Function Documentation
getModule()
const cModule * inet::visualizer::PacketDrop::getModule () const
 {
     return check_and_cast<cModule *>(cSimulation::getActiveSimulation()->getComponent(moduleId));
 }
Referenced by getNetworkInterface(), and getNetworkNode().
getNetworkInterface()
const NetworkInterface * inet::visualizer::PacketDrop::getNetworkInterface () const
 {
     auto module = getModule();
     return module != nullptr ? findContainingNicModule(module) : nullptr;
 }
getNetworkNode()
const cModule * inet::visualizer::PacketDrop::getNetworkNode () const
 {
     auto module = getModule();
     return module != nullptr ? findContainingNode(module) : nullptr;
 }
getPacket_()
const cPacket* inet::visualizer::PacketDrop::getPacket_ () const inline
 { return packet; }
getPosition()
const Coord& inet::visualizer::PacketDrop::getPosition () const inline
 { return position; }
Referenced by inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), inet::visualizer::PacketDropCanvasVisualizer::createPacketDropVisualization(), inet::visualizer::PacketDropOsgVisualizer::setAlpha(), and inet::visualizer::PacketDropCanvasVisualizer::setAlpha().
Member Data Documentation
moduleId
const int inet::visualizer::PacketDrop::moduleId = -1 protected
Referenced by getModule().
packet
const cPacket* inet::visualizer::PacketDrop::packet = nullptr protected
Referenced by ~PacketDrop().
position
const Coord inet::visualizer::PacketDrop::position protected
The documentation for this class was generated from the following files:
PacketDropVisualizerBase.h
PacketDropVisualizerBase.cc