INET Framework for OMNeT++/OMNEST: inet::physicallayer::IRadioSignal Class Reference
inet::physicallayer::IRadioSignal Class Reference abstract
#include <IRadioSignal.h>
Public Types
enum SignalPart {
SIGNAL_PART_NONE = -1, SIGNAL_PART_WHOLE, SIGNAL_PART_PREAMBLE, SIGNAL_PART_HEADER,
SIGNAL_PART_DATA
}
This enumeration specifies a part of a radio signal.
Public Member Functions
virtual const simtime_t getStartTime () const =0
Returns the time when the signal starts at the start position.
virtual const simtime_t getEndTime () const =0
Returns the time when the signal ends at the end position.
virtual const Coord & getStartPosition () const =0
Returns the position where the signal starts at the start time.
virtual const Coord & getEndPosition () const =0
Returns the position where the signal ends at the end time.
Static Public Member Functions
static const char * getSignalPartName (SignalPart signalPart)
Returns the name of the provided signal part.
Static Protected Attributes
static cEnum * signalPartEnum = nullptr
The enumeration registered for signal part.
Member Enumeration Documentation
SignalPart
enum inet::physicallayer::IRadioSignal::SignalPart
This enumeration specifies a part of a radio signal.
Enumerator
SIGNAL_PART_NONE
SIGNAL_PART_WHOLE
SIGNAL_PART_PREAMBLE
SIGNAL_PART_HEADER
SIGNAL_PART_DATA
                     {
         SIGNAL_PART_NONE = -1,
         SIGNAL_PART_WHOLE,
         SIGNAL_PART_PREAMBLE,
         SIGNAL_PART_HEADER,
         SIGNAL_PART_DATA
     };
Member Function Documentation
getEndPosition()
virtual const Coord& inet::physicallayer::IRadioSignal::getEndPosition () const pure virtual
Returns the position where the signal ends at the end time.
getEndTime()
virtual const simtime_t inet::physicallayer::IRadioSignal::getEndTime () const pure virtual
Returns the time when the signal ends at the end position.
getSignalPartName()
const char * inet::physicallayer::IRadioSignal::getSignalPartName (SignalPart signalPart) static
Returns the name of the provided signal part.
 {
     if (signalPartEnum == nullptr)
         signalPartEnum = cEnum::get(opp_typename(typeid(IRadioSignal::SignalPart)));
     return signalPartEnum->getStringFor(signalPart) + 12;
 }
Referenced by inet::physicallayer::Radio::abortReception(), inet::physicallayer::Radio::abortTransmission(), inet::physicallayer::ApskErrorModel::computePacketErrorRate(), inet::physicallayer::StochasticErrorModel::computePacketErrorRate(), inet::physicallayer::Ieee80211ErrorModelBase::computePacketErrorRate(), inet::physicallayer::Radio::continueReception(), inet::physicallayer::Radio::continueTransmission(), inet::physicallayer::Radio::endReception(), inet::physicallayer::Radio::endTransmission(), inet::physicallayer::ReceptionBase::getDuration(), inet::physicallayer::TransmissionBase::getDuration(), inet::physicallayer::Arrival::getEndTime(), inet::physicallayer::ReceptionBase::getEndTime(), inet::physicallayer::TransmissionBase::getEndTime(), inet::physicallayer::Arrival::getStartTime(), inet::physicallayer::ReceptionBase::getStartTime(), inet::physicallayer::TransmissionBase::getStartTime(), inet::physicallayer::Radio::startReception(), inet::physicallayer::Radio::startTransmission(), and inet::physicallayer::Radio::updateTransceiverPart().
getStartPosition()
virtual const Coord& inet::physicallayer::IRadioSignal::getStartPosition () const pure virtual
Returns the position where the signal starts at the start time.
getStartTime()
virtual const simtime_t inet::physicallayer::IRadioSignal::getStartTime () const pure virtual
Returns the time when the signal starts at the start position.
Member Data Documentation
signalPartEnum
cEnum * inet::physicallayer::IRadioSignal::signalPartEnum = nullptr static protected
The enumeration registered for signal part.
Referenced by getSignalPartName().
The documentation for this class was generated from the following files:
IRadioSignal.h
IRadioSignal.cc