INET Framework for OMNeT++/OMNEST: inet::physicallayer::NarrowbandTransmissionBase Class Reference
inet::physicallayer::NarrowbandTransmissionBase Class Reference
#include <NarrowbandTransmissionBase.h>
Public Member Functions
NarrowbandTransmissionBase (const IRadio *transmitter, const Packet *packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation, const IModulation *modulation, Hz centerFrequency, Hz bandwidth)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IModulation * getModulation () const
virtual Hz getCenterFrequency () const override
virtual Hz getBandwidth () const override
Public Member Functions inherited from inet::physicallayer::TransmissionBase
TransmissionBase (const IRadio *transmitter, const Packet *packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation)
virtual int getId () const override
Returns an identifier for this transmission which is globally unique for the whole lifetime of the simulation among all transmissions.
virtual const IRadio * getTransmitter () const override
Returns the transmitter that transmitted this radio signal on the radio channel.
virtual int getTransmitterId () const override
Returns the transmitter's id that transmitted this radio signal on the radio channel.
virtual const IAntennaGain * getTransmitterAntennaGain () const override
Returns the gain of the transmitting antenna.
virtual const IRadioMedium * getMedium () const override
Returns the radio medium used for this transmission.
virtual const Packet * getPacket () const override
Returns the packet corresponding to this transmission.
virtual const simtime_t getStartTime () const override
Returns the time when the transmitter started this transmission.
virtual const simtime_t getEndTime () const override
Returns the time when the transmitter ended this transmission.
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getPreambleStartTime () const override
virtual const simtime_t getPreambleEndTime () const override
virtual const simtime_t getHeaderStartTime () const override
virtual const simtime_t getHeaderEndTime () const override
virtual const simtime_t getDataStartTime () const override
virtual const simtime_t getDataEndTime () const override
virtual const simtime_t getDuration () const override
Returns the total length of this transmission.
virtual const simtime_t getDuration (IRadioSignal::SignalPart part) const override
Returns the length of the provided part of this transmission.
virtual const simtime_t getPreambleDuration () const override
Returns the length of the preamble part of this transmission.
virtual const simtime_t getHeaderDuration () const override
Returns the length of the header part of this transmission.
virtual const simtime_t getDataDuration () const override
Returns the length of the data part of this transmission.
virtual const Coord & getStartPosition () const override
Returns the antenna's position when the transmitter started this transmission.
virtual const Coord & getEndPosition () const override
Returns the antenna's position when the transmitter ended this transmission.
virtual const Quaternion & getStartOrientation () const override
Returns the antenna's orientation when the transmitter started this transmission.
virtual const Quaternion & getEndOrientation () const override
Returns the antenna's orientation when the transmitter ended this transmission.
virtual const ITransmissionAnalogModel * getAnalogModel () const override
Returns the analog model of the transmitted signal.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::INarrowbandSignal
virtual W computeMinPower (simtime_t startTime, simtime_t endTime) const =0
Protected Attributes
const IModulation * modulation
const Hz centerFrequency
const Hz bandwidth
Protected Attributes inherited from inet::physicallayer::TransmissionBase
const int id
const IRadioMedium * radioMedium
const int transmitterId
Ptr< const IAntennaGain > transmitterGain
const Packet * packet
const simtime_t startTime
const simtime_t endTime
const simtime_t preambleDuration
const simtime_t headerDuration
const simtime_t dataDuration
const Coord startPosition
const Coord endPosition
const Quaternion startOrientation
const Quaternion endOrientation
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Protected Attributes inherited from inet::physicallayer::ITransmission
static int nextId = 0
Constructor & Destructor Documentation
NarrowbandTransmissionBase()
inet::physicallayer::NarrowbandTransmissionBase::NarrowbandTransmissionBase (const IRadio * transmitter, const Packet * packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord & startPosition, const Coord & endPosition, const Quaternion & startOrientation, const Quaternion & endOrientation, const IModulation * modulation, Hz centerFrequency, Hz bandwidth)
                                                                                                                                                                                                                                                                                                                                                                                                                                                        :
     TransmissionBase(transmitter, packet, startTime, endTime, preambleDuration, headerDuration, dataDuration, startPosition, endPosition, startOrientation, endOrientation),
     modulation(modulation),
     centerFrequency(centerFrequency),
     bandwidth(bandwidth)
 {
 }
Member Function Documentation
getBandwidth()
virtual Hz inet::physicallayer::NarrowbandTransmissionBase::getBandwidth () const inline override virtual
Implements inet::physicallayer::INarrowbandSignal.
 { return bandwidth; }
Referenced by inet::physicallayer::ApskErrorModel::computeBitErrorRate(), inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible(), inet::physicallayer::DimensionalAnalogModel::computeReception(), inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), and inet::physicallayer::ApskErrorModel::computeSymbolErrorRate().
getCenterFrequency()
virtual Hz inet::physicallayer::NarrowbandTransmissionBase::getCenterFrequency () const inline override virtual
Implements inet::physicallayer::INarrowbandSignal.
 { return centerFrequency; }
Referenced by inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible(), inet::physicallayer::DimensionalAnalogModel::computeReception(), and inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower().
getModulation()
virtual const IModulation* inet::physicallayer::NarrowbandTransmissionBase::getModulation () const inline virtual
 { return modulation; }
Referenced by inet::physicallayer::ApskErrorModel::computeBitErrorRate(), and inet::physicallayer::ApskErrorModel::computeSymbolErrorRate().
printToStream()
std::ostream & inet::physicallayer::NarrowbandTransmissionBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::TransmissionBase.
Reimplemented in inet::physicallayer::DimensionalTransmission, inet::physicallayer::FlatTransmissionBase, inet::physicallayer::ScalarTransmission, inet::physicallayer::Ieee80211DimensionalTransmission, inet::physicallayer::Ieee80211ScalarTransmission, inet::physicallayer::ApskDimensionalTransmission, and inet::physicallayer::ApskScalarTransmission.
 {
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(centerFrequency);
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(bandwidth)
                << EV_FIELD(modulation, printFieldToString(modulation, level + 1, evFlags));
     return TransmissionBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::FlatTransmissionBase::printToStream().
Member Data Documentation
bandwidth
const Hz inet::physicallayer::NarrowbandTransmissionBase::bandwidth protected
Referenced by printToStream().
centerFrequency
const Hz inet::physicallayer::NarrowbandTransmissionBase::centerFrequency protected
Referenced by printToStream().
modulation
const IModulation* inet::physicallayer::NarrowbandTransmissionBase::modulation protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
NarrowbandTransmissionBase.h
NarrowbandTransmissionBase.cc