INET Framework for OMNeT++/OMNEST: inet::queueing::ActivePacketSink Class Reference
inet::queueing::ActivePacketSink Class Reference
#include <ActivePacketSink.h>
Public Member Functions
virtual ~ActivePacketSink ()
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::ClockUserModuleMixin< ActivePacketSinkBase >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::queueing::ActivePacketSinkBase
virtual IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void scheduleCollectionTimer (double delay)
virtual void collectPacket ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
cPar * collectionIntervalParameter = nullptr
ClockEvent * collectionTimer = nullptr
bool scheduleForAbsoluteTime = false
Protected Attributes inherited from inet::queueing::ActivePacketSinkBase
cGate * inputGate = nullptr
IPassivePacketSource * provider = nullptr
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Constructor & Destructor Documentation
~ActivePacketSink()
virtual inet::queueing::ActivePacketSink::~ActivePacketSink () inline virtual
 { cancelAndDeleteClockEvent(collectionTimer); }
Member Function Documentation
collectPacket()
void inet::queueing::ActivePacketSink::collectPacket () protected virtual
 {
     auto packet = provider->pullPacket(inputGate->getPathStartGate());
     take(packet);
     emit(packetPulledSignal, packet);
     EV_INFO << "Collecting packet" << EV_FIELD(packet) << EV_ENDL;
     numProcessedPackets++;
     processedTotalLength += packet->getDataLength();
     updateDisplayString();
     dropPacket(packet, OTHER_PACKET_DROP);
 }
Referenced by handleCanPullPacketChanged(), handleMessage(), and initialize().
handleCanPullPacketChanged()
void inet::queueing::ActivePacketSink::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handleCanPullPacketChanged");
     if (!collectionTimer->isScheduled() && provider->canPullSomePacket(inputGate->getPathStartGate())) {
         double offset = par("initialCollectionOffset");
         if (offset != 0)
             scheduleCollectionTimer(offset);
         else {
             scheduleCollectionTimer(collectionIntervalParameter->doubleValue());
             collectPacket();
         }
     }
 }
handleMessage()
void inet::queueing::ActivePacketSink::handleMessage (cMessage * message) override protected virtual
 {
     if (message == collectionTimer) {
         if (provider->canPullSomePacket(inputGate->getPathStartGate())) {
             scheduleCollectionTimer(collectionIntervalParameter->doubleValue());
             collectPacket();
         }
     }
     else
         throw cRuntimeError("Unknown message");
 }
handlePullPacketProcessed()
void inet::queueing::ActivePacketSink::handlePullPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pulled packet is failed to be processed successfully. It allows the sink to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handlePullPacketProcessed");
 }
initialize()
void inet::queueing::ActivePacketSink::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::ActivePacketSinkBase.
 {
     ClockUserModuleMixin::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         collectionIntervalParameter = &par("collectionInterval");
         collectionTimer = new ClockEvent("CollectionTimer");
         scheduleForAbsoluteTime = par("scheduleForAbsoluteTime");
     }
     else if (stage == INITSTAGE_QUEUEING) {
         if (!collectionTimer->isScheduled() && provider->canPullSomePacket(inputGate->getPathStartGate())) {
             double offset = par("initialCollectionOffset");
             if (offset != 0)
                 scheduleCollectionTimer(offset);
             else {
                 scheduleCollectionTimer(collectionIntervalParameter->doubleValue());
                 collectPacket();
             }
         }
     }
 }
scheduleCollectionTimer()
void inet::queueing::ActivePacketSink::scheduleCollectionTimer (double delay) protected virtual
 {
     if (scheduleForAbsoluteTime)
         scheduleClockEventAt(getClockTime() + delay, collectionTimer);
     else
         scheduleClockEventAfter(delay, collectionTimer);
 }
Referenced by handleCanPullPacketChanged(), handleMessage(), and initialize().
Member Data Documentation
collectionIntervalParameter
cPar* inet::queueing::ActivePacketSink::collectionIntervalParameter = nullptr protected
Referenced by handleCanPullPacketChanged(), handleMessage(), and initialize().
collectionTimer
ClockEvent* inet::queueing::ActivePacketSink::collectionTimer = nullptr protected
Referenced by handleCanPullPacketChanged(), handleMessage(), initialize(), and scheduleCollectionTimer().
scheduleForAbsoluteTime
bool inet::queueing::ActivePacketSink::scheduleForAbsoluteTime = false protected
Referenced by initialize(), and scheduleCollectionTimer().
The documentation for this class was generated from the following files:
ActivePacketSink.h
ActivePacketSink.cc