INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211HtCode Class Reference
inet::physicallayer::Ieee80211HtCode Class Reference
#include <Ieee80211HtCode.h>
Public Member Functions
Ieee80211HtCode (const Ieee80211ConvolutionalCode *forwardErrorCorrection, const Ieee80211HtInterleaving *interleaving, const AdditiveScrambling *scrambling)
const Ieee80211ConvolutionalCode * getForwardErrorCorrection () const
const AdditiveScrambling * getScrambling () const
const Ieee80211HtInterleaving * getInterleaving () const
virtual ~Ieee80211HtCode ()
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const Ieee80211ConvolutionalCode * forwardErrorCorrection
const Ieee80211HtInterleaving * interleaving
const AdditiveScrambling * scrambling
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211HtCode()
inet::physicallayer::Ieee80211HtCode::Ieee80211HtCode (const Ieee80211ConvolutionalCode * forwardErrorCorrection, const Ieee80211HtInterleaving * interleaving, const AdditiveScrambling * scrambling)
                                               :
     forwardErrorCorrection(forwardErrorCorrection),
     interleaving(interleaving),
     scrambling(scrambling)
 {
 }
~Ieee80211HtCode()
inet::physicallayer::Ieee80211HtCode::~Ieee80211HtCode () virtual
 {
     // NOTE: We assume that convolutional code and scrambling are static variables
     delete interleaving;
 }
Member Function Documentation
getForwardErrorCorrection()
const Ieee80211ConvolutionalCode* inet::physicallayer::Ieee80211HtCode::getForwardErrorCorrection () const inline
 { return forwardErrorCorrection; }
Referenced by inet::physicallayer::Ieee80211HtSignalMode::computeNetBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeNetBitrate(), and inet::physicallayer::Ieee80211HtDataMode::getDuration().
getInterleaving()
const Ieee80211HtInterleaving* inet::physicallayer::Ieee80211HtCode::getInterleaving () const inline
 { return interleaving; }
getScrambling()
const AdditiveScrambling* inet::physicallayer::Ieee80211HtCode::getScrambling () const inline
 { return scrambling; }
Member Data Documentation
forwardErrorCorrection
const Ieee80211ConvolutionalCode* inet::physicallayer::Ieee80211HtCode::forwardErrorCorrection protected
interleaving
const Ieee80211HtInterleaving* inet::physicallayer::Ieee80211HtCode::interleaving protected
Referenced by ~Ieee80211HtCode().
scrambling
const AdditiveScrambling* inet::physicallayer::Ieee80211HtCode::scrambling protected
The documentation for this class was generated from the following files:
Ieee80211HtCode.h
Ieee80211HtCode.cc