INET Framework for OMNeT++/OMNEST: inet::RipRoute Class Reference
inet::RipRoute Class Reference
#include <RipRouteData.h>
Public Types
enum RouteType {
RIP_ROUTE_RTE, RIP_ROUTE_STATIC, RIP_ROUTE_DEFAULT, RIP_ROUTE_REDISTRIBUTE,
RIP_ROUTE_INTERFACE
}
Public Member Functions
RipRoute (IRoute *route, RouteType type, int metric, uint16_t routeTag)
virtual std::string str () const override
IRoute * getRoute () const
RouteType getType () const
L3Address getDestination () const
L3Address getNextHop () const
int getPrefixLength () const
int getMetric () const
NetworkInterface * getInterface () const
L3Address getFrom () const
simtime_t getLastUpdateTime () const
bool isChanged () const
uint16_t getRouteTag () const
simtime_t getLastInvalidationTime () const
void setRoute (IRoute *route)
void setType (RouteType type)
void setDestination (const L3Address &dest)
void setNextHop (const L3Address &nextHop)
void setPrefixLength (int prefixLength)
void setMetric (int metric)
void setInterface (NetworkInterface *ie)
void setFrom (const L3Address &from)
void setLastUpdateTime (simtime_t time)
void setChanged (bool changed)
void setRouteTag (uint16_t routeTag)
void setLastInvalidationTime (simtime_t time)
Protected Attributes
IRoute * route = nullptr
RouteType type = static_cast<RouteType>(-1)
L3Address dest
L3Address nextHop
int prefixLength = 0
int metric = 0
NetworkInterface * ie = nullptr
L3Address from
simtime_t lastUpdateTime = 0
bool changed = false
uint16_t tag = 0
simtime_t lastInvalid = 0
Member Enumeration Documentation
RouteType
enum inet::RipRoute::RouteType
Enumerator
RIP_ROUTE_RTE
RIP_ROUTE_STATIC
RIP_ROUTE_DEFAULT
RIP_ROUTE_REDISTRIBUTE
RIP_ROUTE_INTERFACE
                    {
         RIP_ROUTE_RTE,          // route learned from a RipEntry
         RIP_ROUTE_STATIC,       // static route
         RIP_ROUTE_DEFAULT,      // default route
         RIP_ROUTE_REDISTRIBUTE, // route imported from another routing protocol
         RIP_ROUTE_INTERFACE     // route belongs to a local interface
     };
Constructor & Destructor Documentation
RipRoute()
inet::RipRoute::RipRoute (IRoute * route, RouteType type, int metric, uint16_t routeTag) inline
     {
         this->route = route;
         this->type = type;
         dest = route->getDestinationAsGeneric();
         nextHop = route->getNextHopAsGeneric();
         prefixLength = route->getPrefixLength();
         this->metric = metric;
         ie = route->getInterface();
         this->lastUpdateTime = 0;
         this->changed = false;
         this->tag = routeTag;
         this->lastInvalid = 0;
     }
Member Function Documentation
getDestination()
L3Address inet::RipRoute::getDestination () const inline
 { return dest; }
Referenced by inet::Rip::invalidateRoute(), inet::Rip::processResponse(), inet::Rip::purgeRoute(), inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
getFrom()
L3Address inet::RipRoute::getFrom () const inline
 { return from; }
Referenced by inet::Rip::processResponse().
getInterface()
NetworkInterface* inet::RipRoute::getInterface () const inline
 { return ie; }
Referenced by inet::Rip::receiveSignal().
getLastInvalidationTime()
simtime_t inet::RipRoute::getLastInvalidationTime () const inline
 { return lastInvalid; }
Referenced by inet::Rip::processResponse().
getLastUpdateTime()
simtime_t inet::RipRoute::getLastUpdateTime () const inline
 { return lastUpdateTime; }
Referenced by inet::Rip::checkExpiredRoutes().
getMetric()
int inet::RipRoute::getMetric () const inline
 { return metric; }
Referenced by inet::Rip::processRequest(), inet::Rip::processResponse(), and inet::Rip::updateRoute().
getNextHop()
L3Address inet::RipRoute::getNextHop () const inline
 { return nextHop; }
Referenced by inet::Rip::receiveSignal().
getPrefixLength()
int inet::RipRoute::getPrefixLength () const inline
 { return prefixLength; }
Referenced by inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
getRoute()
IRoute* inet::RipRoute::getRoute () const inline
 { return route; }
Referenced by inet::Rip::invalidateRoute(), inet::Rip::processResponse(), inet::Rip::purgeRoute(), and inet::Rip::updateRoute().
getRouteTag()
uint16_t inet::RipRoute::getRouteTag () const inline
 { return tag; }
getType()
RouteType inet::RipRoute::getType () const inline
 { return type; }
Referenced by inet::Rip::checkExpiredRoutes(), inet::Rip::processResponse(), and inet::Rip::purgeRoute().
isChanged()
bool inet::RipRoute::isChanged () const inline
 { return changed; }
setChanged()
void inet::RipRoute::setChanged (bool changed) inline
 { this->changed = changed; }
Referenced by inet::Rip::addRoute(), inet::Rip::invalidateRoute(), inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
setDestination()
void inet::RipRoute::setDestination (const L3Address & dest) inline
 { this->dest = dest; }
Referenced by inet::Rip::receiveSignal().
setFrom()
void inet::RipRoute::setFrom (const L3Address & from) inline
 { this->from = from; }
Referenced by inet::Rip::addRoute(), and inet::Rip::updateRoute().
setInterface()
void inet::RipRoute::setInterface (NetworkInterface * ie) inline
 { this->ie = ie; if (route && type == RIP_ROUTE_RTE) route->setInterface(ie); }
Referenced by inet::Rip::importRoute(), inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
setLastInvalidationTime()
void inet::RipRoute::setLastInvalidationTime (simtime_t time) inline
 { this->lastInvalid = time; }
Referenced by inet::Rip::invalidateRoute().
setLastUpdateTime()
void inet::RipRoute::setLastUpdateTime (simtime_t time) inline
 { lastUpdateTime = time; }
Referenced by inet::Rip::addRoute(), inet::Rip::processResponse(), and inet::Rip::updateRoute().
setMetric()
void inet::RipRoute::setMetric (int metric) inline
 { this->metric = metric; if (route && type == RIP_ROUTE_RTE) route->setMetric(metric); }
Referenced by inet::Rip::invalidateRoute(), inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
setNextHop()
void inet::RipRoute::setNextHop (const L3Address & nextHop) inline
 { this->nextHop = nextHop; if (route && type == RIP_ROUTE_RTE) route->setNextHop(nextHop); }
Referenced by inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
setPrefixLength()
void inet::RipRoute::setPrefixLength (int prefixLength) inline
 { this->prefixLength = prefixLength; }
Referenced by inet::Rip::receiveSignal().
setRoute()
void inet::RipRoute::setRoute (IRoute * route) inline
 { this->route = route; }
Referenced by inet::Rip::invalidateRoute(), inet::Rip::purgeRoute(), inet::Rip::receiveSignal(), and inet::Rip::updateRoute().
setRouteTag()
void inet::RipRoute::setRouteTag (uint16_t routeTag) inline
 { this->tag = routeTag; }
Referenced by inet::Rip::updateRoute().
setType()
void inet::RipRoute::setType (RouteType type) inline
 { this->type = type; }
Referenced by inet::Rip::updateRoute().
str()
std::string inet::RipRoute::str () const override virtual
 {
     std::stringstream out;
     if (dest.isUnspecified())
         out << "0.0.0.0";
     else
         out << dest;
     out << "/" << prefixLength;
     out << " gw: ";
     if (nextHop.isUnspecified())
         out << "*  ";
     else
         out << nextHop << "  ";
     out << "metric:" << metric << " ";
     out << "if:";
     if (!ie)
         out << "*  ";
     else
         out << ie->getInterfaceName() << "  ";
     out << "from:" << from << " ";
     out << "lastUpdate:" << lastUpdateTime << "s  ";
     out << "changed:" << changed << " ";
     out << "tag:" << tag << " ";
     out << "lastInvalid:" << lastInvalid << "s  ";
     switch (type) {
         case RIP_ROUTE_INTERFACE:
             out << "INTERFACE";
             break;
         case RIP_ROUTE_STATIC:
             out << "STATIC";
             break;
         case RIP_ROUTE_DEFAULT:
             out << "DEFAULT";
             break;
         case RIP_ROUTE_RTE:
             out << "RTE";
             break;
         case RIP_ROUTE_REDISTRIBUTE:
             out << "REDISTRIBUTE";
             break;
     }
     return out.str();
 }
Member Data Documentation
changed
bool inet::RipRoute::changed = false protected
Referenced by str().
dest
L3Address inet::RipRoute::dest protected
Referenced by str().
from
L3Address inet::RipRoute::from protected
Referenced by str().
ie
NetworkInterface* inet::RipRoute::ie = nullptr protected
Referenced by str().
lastInvalid
simtime_t inet::RipRoute::lastInvalid = 0 protected
Referenced by str().
lastUpdateTime
simtime_t inet::RipRoute::lastUpdateTime = 0 protected
Referenced by str().
metric
int inet::RipRoute::metric = 0 protected
Referenced by str().
nextHop
L3Address inet::RipRoute::nextHop protected
Referenced by str().
prefixLength
int inet::RipRoute::prefixLength = 0 protected
Referenced by str().
route
IRoute* inet::RipRoute::route = nullptr protected
tag
uint16_t inet::RipRoute::tag = 0 protected
Referenced by str().
type
RouteType inet::RipRoute::type = static_cast<RouteType>(-1) protected
Referenced by str().
The documentation for this class was generated from the following files:
RipRouteData.h
RipRouteData.cc