INET Framework for OMNeT++/OMNEST: inet::HopLimitTagBase Class Reference
inet::HopLimitTagBase Class Reference
Class generated from inet/networklayer/common/HopLimitTag.msg:13 by opp_msgtool.
#include <HopLimitTag_m.h>
Public Member Functions
HopLimitTagBase ()
HopLimitTagBase (const HopLimitTagBase &other)
virtual ~HopLimitTagBase ()
HopLimitTagBase & operator= (const HopLimitTagBase &other)
virtual HopLimitTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getHopLimit () const
virtual void setHopLimit (int hopLimit)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const HopLimitTagBase &)=delete
Protected Attributes
int hopLimit = -1
Private Member Functions
void copy (const HopLimitTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/networklayer/common/HopLimitTag.msg:13 by opp_msgtool.
class HopLimitTagBase extends TagBase
{
    int hopLimit = -1;
}
Constructor & Destructor Documentation
HopLimitTagBase() [1/2]
inet::HopLimitTagBase::HopLimitTagBase ()
HopLimitTagBase() [2/2]
inet::HopLimitTagBase::HopLimitTagBase (const HopLimitTagBase & other)
~HopLimitTagBase()
virtual inet::HopLimitTagBase::~HopLimitTagBase () virtual
Member Function Documentation
copy()
void inet::HopLimitTagBase::copy (const HopLimitTagBase & other) private
dup()
virtual HopLimitTagBase* inet::HopLimitTagBase::dup () const inline override virtual
Reimplemented in inet::HopLimitInd, and inet::HopLimitReq.
 {return new HopLimitTagBase(*this);}
getHopLimit()
virtual int inet::HopLimitTagBase::getHopLimit () const virtual
Referenced by inet::Ipv4Encap::encapsulate(), inet::Ipv6::encapsulate(), inet::NextHopForwarding::encapsulate(), inet::Flooding::encapsulate(), inet::Ipv4::encapsulate(), inet::Rip::isValidResponse(), inet::dymo::Dymo::permissibleRteMsg(), inet::PingApp::processPingResponse(), inet::Ipv6NeighbourDiscovery::validateNaPacket(), inet::Ipv6NeighbourDiscovery::validateNsPacket(), inet::Ipv6NeighbourDiscovery::validateRaPacket(), and inet::Ipv6NeighbourDiscovery::validateRsPacket().
operator=()
HopLimitTagBase& inet::HopLimitTagBase::operator= (const HopLimitTagBase & other)
operator==()
bool inet::HopLimitTagBase::operator== (const HopLimitTagBase &) protected delete
parsimPack()
virtual void inet::HopLimitTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::HopLimitInd, and inet::HopLimitReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::HopLimitTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::HopLimitInd, and inet::HopLimitReq.
Referenced by inet::doParsimUnpacking().
setHopLimit()
virtual void inet::HopLimitTagBase::setHopLimit (int hopLimit) virtual
Referenced by inet::tcp::TcpConnection::sendToIP().
Member Data Documentation
hopLimit
int inet::HopLimitTagBase::hopLimit = -1 protected
The documentation for this class was generated from the following file:
HopLimitTag_m.h