INET Framework for OMNeT++/OMNEST: inet::rtp::RtpCiCreateSenderModule Class Reference
inet::rtp::RtpCiCreateSenderModule Class Reference
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:107 by opp_msgtool.
#include <RtpInterfacePacket_m.h>
Public Member Functions
RtpCiCreateSenderModule ()
RtpCiCreateSenderModule (const RtpCiCreateSenderModule &other)
virtual ~RtpCiCreateSenderModule ()
RtpCiCreateSenderModule & operator= (const RtpCiCreateSenderModule &other)
virtual RtpCiCreateSenderModule * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getPayloadType () const
virtual void setPayloadType (int payloadType)
virtual const char * getFileName () const
virtual void setFileName (const char *fileName)
Public Member Functions inherited from inet::rtp::RtpSessionControlInfo
RtpSessionControlInfo ()
RtpSessionControlInfo (const RtpSessionControlInfo &other)
virtual ~RtpSessionControlInfo ()
RtpSessionControlInfo & operator= (const RtpSessionControlInfo &other)
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
Public Member Functions inherited from inet::rtp::RtpControlInfo
RtpControlInfo ()
RtpControlInfo (const RtpControlInfo &other)
virtual ~RtpControlInfo ()
RtpControlInfo & operator= (const RtpControlInfo &other)
virtual RtpIfpType getType () const
virtual void setType (RtpIfpType type)
Protected Member Functions
bool operator== (const RtpCiCreateSenderModule &)=delete
Protected Member Functions inherited from inet::rtp::RtpSessionControlInfo
bool operator== (const RtpSessionControlInfo &)=delete
Protected Member Functions inherited from inet::rtp::RtpControlInfo
bool operator== (const RtpControlInfo &)=delete
Protected Attributes
int payloadType = 0
::omnetpp::opp_string fileName
Protected Attributes inherited from inet::rtp::RtpSessionControlInfo
uint32_t ssrc = 0
Protected Attributes inherited from inet::rtp::RtpControlInfo
RtpIfpType type = static_cast<inet::rtp::RtpIfpType>(-1)
Private Member Functions
void copy (const RtpCiCreateSenderModule &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:107 by opp_msgtool.
// App to ~Rtp
class RtpCiCreateSenderModule extends RtpSessionControlInfo
{
    type = RTP_IFP_CREATE_SENDER_MODULE;
    int payloadType;
    string fileName;
}
Constructor & Destructor Documentation
RtpCiCreateSenderModule() [1/2]
inet::rtp::RtpCiCreateSenderModule::RtpCiCreateSenderModule ()
RtpCiCreateSenderModule() [2/2]
inet::rtp::RtpCiCreateSenderModule::RtpCiCreateSenderModule (const RtpCiCreateSenderModule & other)
~RtpCiCreateSenderModule()
virtual inet::rtp::RtpCiCreateSenderModule::~RtpCiCreateSenderModule () virtual
Member Function Documentation
copy()
void inet::rtp::RtpCiCreateSenderModule::copy (const RtpCiCreateSenderModule & other) private
dup()
virtual RtpCiCreateSenderModule* inet::rtp::RtpCiCreateSenderModule::dup () const inline override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
 {return new RtpCiCreateSenderModule(*this);}
getFileName()
virtual const char* inet::rtp::RtpCiCreateSenderModule::getFileName () const virtual
Referenced by inet::rtp::Rtp::createSenderModule().
getPayloadType()
virtual int inet::rtp::RtpCiCreateSenderModule::getPayloadType () const virtual
Referenced by inet::rtp::Rtp::createSenderModule().
operator=()
RtpCiCreateSenderModule& inet::rtp::RtpCiCreateSenderModule::operator= (const RtpCiCreateSenderModule & other)
operator==()
bool inet::rtp::RtpCiCreateSenderModule::operator== (const RtpCiCreateSenderModule &) protected delete
parsimPack()
virtual void inet::rtp::RtpCiCreateSenderModule::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpCiCreateSenderModule::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimUnpacking().
setFileName()
virtual void inet::rtp::RtpCiCreateSenderModule::setFileName (const char * fileName) virtual
setPayloadType()
virtual void inet::rtp::RtpCiCreateSenderModule::setPayloadType (int payloadType) virtual
Member Data Documentation
fileName
::omnetpp::opp_string inet::rtp::RtpCiCreateSenderModule::fileName protected
payloadType
int inet::rtp::RtpCiCreateSenderModule::payloadType = 0 protected
The documentation for this class was generated from the following file:
RtpInterfacePacket_m.h