INET Framework for OMNeT++/OMNEST: inet::physicallayer::FlatTransmitterBase Class Reference
inet::physicallayer::FlatTransmitterBase Class Reference
#include <FlatTransmitterBase.h>
Public Member Functions
FlatTransmitterBase ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual b getHeaderLength () const
virtual void setHeaderLength (b headerLength)
virtual bps getBitrate () const
virtual void setBitrate (bps bitrate)
virtual W getMaxPower () const override
Returns the maximum transmission power above which no transmission is ever transmitted.
virtual W getPower () const
virtual void setPower (W power)
Public Member Functions inherited from inet::physicallayer::NarrowbandTransmitterBase
NarrowbandTransmitterBase ()
virtual const IModulation * getModulation () const
virtual void setModulation (const IModulation *modulation)
virtual Hz getCenterFrequency () const
virtual void setCenterFrequency (Hz centerFrequency)
virtual Hz getBandwidth () const
virtual void setBandwidth (Hz bandwidth)
Public Member Functions inherited from inet::physicallayer::TransmitterBase
virtual m getMaxCommunicationRange () const override
Returns the maximum communication range.
virtual m getMaxInterferenceRange () const override
Returns the maximum interference range.
Public Member Functions inherited from inet::physicallayer::ITransmitter
virtual const ITransmission * createTransmission (const IRadio *transmitter, const Packet *packet, const simtime_t startTime) const =0
Returns a transmission which describes the radio signal corresponding to the provided packet.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
virtual bps computeTransmissionPreambleBitrate (const Packet *packet) const
virtual bps computeTransmissionHeaderBitrate (const Packet *packet) const
virtual bps computeTransmissionDataBitrate (const Packet *packet) const
virtual W computeTransmissionPower (const Packet *packet) const
Protected Member Functions inherited from inet::physicallayer::NarrowbandTransmitterBase
virtual Hz computeCenterFrequency (const Packet *packet) const
virtual Hz computeBandwidth (const Packet *packet) const
Protected Member Functions inherited from inet::physicallayer::TransmitterBase
virtual int numInitStages () const override
Protected Attributes
simtime_t preambleDuration
b headerLength
bps bitrate
W power
Protected Attributes inherited from inet::physicallayer::NarrowbandTransmitterBase
const IModulation * modulation
Hz centerFrequency
Hz bandwidth
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
FlatTransmitterBase()
inet::physicallayer::FlatTransmitterBase::FlatTransmitterBase ()
                                          :
     NarrowbandTransmitterBase(),
     preambleDuration(-1),
     headerLength(b(-1)),
     bitrate(bps(NaN)),
     power(W(NaN))
 {
 }
Member Function Documentation
computeTransmissionDataBitrate()
bps inet::physicallayer::FlatTransmitterBase::computeTransmissionDataBitrate (const Packet * packet) const protected virtual
 {
     const auto& signalBitrateReq = const_cast<Packet *>(packet)->findTag<SignalBitrateReq>();
     return signalBitrateReq != nullptr ? signalBitrateReq->getDataBitrate() : bitrate;
 }
Referenced by inet::physicallayer::ApskScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::createTransmission(), and inet::physicallayer::ApskDimensionalTransmitter::createTransmission().
computeTransmissionHeaderBitrate()
bps inet::physicallayer::FlatTransmitterBase::computeTransmissionHeaderBitrate (const Packet * packet) const protected virtual
 {
     const auto& signalBitrateReq = const_cast<Packet *>(packet)->findTag<SignalBitrateReq>();
     return signalBitrateReq != nullptr ? signalBitrateReq->getHeaderBitrate() : bitrate;
 }
computeTransmissionPower()
W inet::physicallayer::FlatTransmitterBase::computeTransmissionPower (const Packet * packet) const protected virtual
 {
     const auto& signalPowerReq = const_cast<Packet *>(packet)->findTag<SignalPowerReq>();
     return signalPowerReq != nullptr ? signalPowerReq->getPower() : power;
 }
Referenced by inet::physicallayer::ApskScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::createTransmission(), inet::physicallayer::ApskDimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission().
computeTransmissionPreambleBitrate()
bps inet::physicallayer::FlatTransmitterBase::computeTransmissionPreambleBitrate (const Packet * packet) const protected virtual
 {
     const auto& signalBitrateReq = const_cast<Packet *>(packet)->findTag<SignalBitrateReq>();
     return signalBitrateReq != nullptr ? signalBitrateReq->getPreambleBitrate() : bitrate;
 }
getBitrate()
virtual bps inet::physicallayer::FlatTransmitterBase::getBitrate () const inline virtual
 { return bitrate; }
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight().
getHeaderLength()
virtual b inet::physicallayer::FlatTransmitterBase::getHeaderLength () const inline virtual
 { return headerLength; }
getMaxPower()
virtual W inet::physicallayer::FlatTransmitterBase::getMaxPower () const inline override virtual
Returns the maximum transmission power above which no transmission is ever transmitted.
Returns a value in the range [0, +infinity] or NaN if unspecified.
Reimplemented from inet::physicallayer::TransmitterBase.
 { return power; }
getPower()
virtual W inet::physicallayer::FlatTransmitterBase::getPower () const inline virtual
 { return power; }
initialize()
void inet::physicallayer::FlatTransmitterBase::initialize (int stage) override protected virtual
Reimplemented from inet::physicallayer::NarrowbandTransmitterBase.
Reimplemented in inet::physicallayer::Ieee80211TransmitterBase, inet::physicallayer::Ieee80211UnitDiskTransmitter, inet::physicallayer::Ieee80211DimensionalTransmitter, inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter, and inet::physicallayer::ApskDimensionalTransmitter.
 {
     NarrowbandTransmitterBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         preambleDuration = par("preambleDuration");
         headerLength = b(par("headerLength"));
         bitrate = bps(par("bitrate"));
         power = W(par("power"));
     }
 }
Referenced by inet::physicallayer::ApskDimensionalTransmitter::initialize(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::initialize(), and inet::physicallayer::Ieee80211TransmitterBase::initialize().
printToStream()
std::ostream & inet::physicallayer::FlatTransmitterBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::NarrowbandTransmitterBase.
Reimplemented in inet::physicallayer::Ieee80211TransmitterBase, inet::physicallayer::Ieee80211UnitDiskTransmitter, inet::physicallayer::Ieee80211DimensionalTransmitter, inet::physicallayer::ApskDimensionalTransmitter, inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter, inet::physicallayer::ApskScalarTransmitter, inet::physicallayer::Ieee80211ScalarTransmitter, and inet::physicallayer::Ieee802154NarrowbandScalarTransmitter.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(preambleDuration)
                << EV_FIELD(headerLength)
                << EV_FIELD(bitrate)
                << EV_FIELD(power);
     return NarrowbandTransmitterBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::ApskScalarTransmitter::printToStream(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::printToStream(), inet::physicallayer::ApskDimensionalTransmitter::printToStream(), and inet::physicallayer::Ieee80211TransmitterBase::printToStream().
setBitrate()
virtual void inet::physicallayer::FlatTransmitterBase::setBitrate (bps bitrate) inline virtual
 { this->bitrate = bitrate; }
Referenced by inet::physicallayer::FlatRadioBase::setBitrate().
setHeaderLength()
virtual void inet::physicallayer::FlatTransmitterBase::setHeaderLength (b headerLength) inline virtual
 { this->headerLength = headerLength; }
setPower()
virtual void inet::physicallayer::FlatTransmitterBase::setPower (W power) inline virtual
 { this->power = power; }
Referenced by inet::physicallayer::FlatRadioBase::setPower().
Member Data Documentation
bitrate
bps inet::physicallayer::FlatTransmitterBase::bitrate protected
Referenced by computeTransmissionDataBitrate(), computeTransmissionHeaderBitrate(), computeTransmissionPreambleBitrate(), initialize(), inet::physicallayer::Ieee80211TransmitterBase::initialize(), and printToStream().
headerLength
b inet::physicallayer::FlatTransmitterBase::headerLength protected
Referenced by inet::physicallayer::ApskScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::createTransmission(), inet::physicallayer::ApskDimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), initialize(), and printToStream().
power
W inet::physicallayer::FlatTransmitterBase::power protected
Referenced by computeTransmissionPower(), initialize(), and printToStream().
preambleDuration
simtime_t inet::physicallayer::FlatTransmitterBase::preambleDuration protected
Referenced by inet::physicallayer::ApskScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::createTransmission(), inet::physicallayer::ApskDimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission(), initialize(), and printToStream().
The documentation for this class was generated from the following files:
FlatTransmitterBase.h
FlatTransmitterBase.cc