INET Framework for OMNeT++/OMNEST: inet::dymo::RreqWaitRrepTimer Class Reference
inet::dymo::RreqWaitRrepTimer Class Reference
Class generated from inet/routing/dymo/Dymo.msg:61 by opp_msgtool.
#include <Dymo_m.h>
Public Member Functions
RreqWaitRrepTimer (const char *name=nullptr, short kind=0)
RreqWaitRrepTimer (const RreqWaitRrepTimer &other)
virtual ~RreqWaitRrepTimer ()
RreqWaitRrepTimer & operator= (const RreqWaitRrepTimer &other)
virtual RreqWaitRrepTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getRetryCount () const
virtual void setRetryCount (int retryCount)
Public Member Functions inherited from inet::dymo::RreqTimer
RreqTimer (const char *name=nullptr, short kind=0)
RreqTimer (const RreqTimer &other)
virtual ~RreqTimer ()
RreqTimer & operator= (const RreqTimer &other)
virtual const ::inet::L3Address & getTarget () const
virtual ::inet::L3Address & getTargetForUpdate ()
virtual void setTarget (const ::inet::L3Address &target)
Protected Member Functions
bool operator== (const RreqWaitRrepTimer &)=delete
Protected Member Functions inherited from inet::dymo::RreqTimer
bool operator== (const RreqTimer &)=delete
Protected Attributes
int retryCount = 0
Protected Attributes inherited from inet::dymo::RreqTimer
::inet::L3Address target
Private Member Functions
void copy (const RreqWaitRrepTimer &other)
Detailed Description
Class generated from inet/routing/dymo/Dymo.msg:61 by opp_msgtool.
message RreqWaitRrepTimer extends RreqTimer
{
    int retryCount;
}
Constructor & Destructor Documentation
RreqWaitRrepTimer() [1/2]
inet::dymo::RreqWaitRrepTimer::RreqWaitRrepTimer (const char * name = nullptr, short kind = 0)
RreqWaitRrepTimer() [2/2]
inet::dymo::RreqWaitRrepTimer::RreqWaitRrepTimer (const RreqWaitRrepTimer & other)
~RreqWaitRrepTimer()
virtual inet::dymo::RreqWaitRrepTimer::~RreqWaitRrepTimer () virtual
Member Function Documentation
copy()
void inet::dymo::RreqWaitRrepTimer::copy (const RreqWaitRrepTimer & other) private
dup()
virtual RreqWaitRrepTimer* inet::dymo::RreqWaitRrepTimer::dup () const inline override virtual
Reimplemented from inet::dymo::RreqTimer.
 {return new RreqWaitRrepTimer(*this);}
getRetryCount()
virtual int inet::dymo::RreqWaitRrepTimer::getRetryCount () const virtual
Referenced by inet::dymo::Dymo::processRreqWaitRrepTimer().
operator=()
RreqWaitRrepTimer& inet::dymo::RreqWaitRrepTimer::operator= (const RreqWaitRrepTimer & other)
operator==()
bool inet::dymo::RreqWaitRrepTimer::operator== (const RreqWaitRrepTimer &) protected delete
parsimPack()
virtual void inet::dymo::RreqWaitRrepTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::dymo::RreqTimer.
Referenced by inet::dymo::doParsimPacking().
parsimUnpack()
virtual void inet::dymo::RreqWaitRrepTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::dymo::RreqTimer.
Referenced by inet::dymo::doParsimUnpacking().
setRetryCount()
virtual void inet::dymo::RreqWaitRrepTimer::setRetryCount (int retryCount) virtual
Referenced by inet::dymo::Dymo::createRreqWaitRrepTimer().
Member Data Documentation
retryCount
int inet::dymo::RreqWaitRrepTimer::retryCount = 0 protected
The documentation for this class was generated from the following file:
Dymo_m.h