INET Framework for OMNeT++/OMNEST: inet::TcpSocket::ICallback Class Reference
inet::TcpSocket::ICallback Class Reference abstract
Callback interface for TCP sockets, see setCallback() and processMessage() for more info.
#include <TcpSocket.h>
Public Member Functions
virtual ~ICallback ()
virtual void socketDataArrived (TcpSocket *socket, Packet *packet, bool urgent)=0
Notifies about data arrival, packet ownership is transferred to the callee.
virtual void socketAvailable (TcpSocket *socket, TcpAvailableInfo *availableInfo)=0
virtual void socketEstablished (TcpSocket *socket)=0
virtual void socketPeerClosed (TcpSocket *socket)=0
virtual void socketClosed (TcpSocket *socket)=0
virtual void socketFailure (TcpSocket *socket, int code)=0
virtual void socketStatusArrived (TcpSocket *socket, TcpStatusInfo *status)=0
virtual void socketDeleted (TcpSocket *socket)=0
Detailed Description
Callback interface for TCP sockets, see setCallback() and processMessage() for more info.
Note: this class is not subclassed from cObject, because classes may have both this class and cSimpleModule as base class, and cSimpleModule is already a cObject.
Constructor & Destructor Documentation
~ICallback()
virtual inet::TcpSocket::ICallback::~ICallback () inline virtual
 {}
Member Function Documentation
socketAvailable()
virtual void inet::TcpSocket::ICallback::socketAvailable (TcpSocket * socket, TcpAvailableInfo * availableInfo) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpServerListener, inet::TcpServerSocketIo, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::processMessage().
socketClosed()
virtual void inet::TcpSocket::ICallback::socketClosed (TcpSocket * socket) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpSessionApp, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpBasicClientApp, inet::TcpServerListener, inet::TcpServerSocketIo, inet::TelnetApp, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::processMessage().
socketDataArrived()
virtual void inet::TcpSocket::ICallback::socketDataArrived (TcpSocket * socket, Packet * packet, bool urgent) pure virtual
Notifies about data arrival, packet ownership is transferred to the callee.
Implemented in inet::TcpSocket::ReceiveQueueBasedCallback, inet::bgp::BgpRouter, inet::TcpServerHostApp, inet::TcpServerListener, inet::TcpServerSocketIo, inet::TcpClientSocketIo, inet::TcpServerThreadBase, inet::TcpSessionApp, inet::TcpAppBase, inet::TcpBasicClientApp, and inet::TelnetApp.
Referenced by inet::TcpSocket::processMessage().
socketDeleted()
virtual void inet::TcpSocket::ICallback::socketDeleted (TcpSocket * socket) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpServerListener, inet::TcpServerSocketIo, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::~TcpSocket().
socketEstablished()
virtual void inet::TcpSocket::ICallback::socketEstablished (TcpSocket * socket) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpSessionApp, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpBasicClientApp, inet::TcpServerListener, inet::TcpServerSocketIo, inet::TelnetApp, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::processMessage().
socketFailure()
virtual void inet::TcpSocket::ICallback::socketFailure (TcpSocket * socket, int code) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpSessionApp, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpBasicClientApp, inet::TcpServerListener, inet::TcpServerSocketIo, inet::TelnetApp, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::processMessage().
socketPeerClosed()
virtual void inet::TcpSocket::ICallback::socketPeerClosed (TcpSocket * socket) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpServerListener, inet::TcpServerSocketIo, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::processMessage().
socketStatusArrived()
virtual void inet::TcpSocket::ICallback::socketStatusArrived (TcpSocket * socket, TcpStatusInfo * status) pure virtual
Implemented in inet::Ldp, inet::bgp::BgpRouter, inet::TcpServerThreadBase, inet::TcpAppBase, inet::TcpServerHostApp, inet::TcpServerListener, inet::TcpServerSocketIo, and inet::TcpClientSocketIo.
Referenced by inet::TcpSocket::processMessage().
The documentation for this class was generated from the following file:
TcpSocket.h