INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3NetworkLsa Class Reference
inet::ospfv3::Ospfv3NetworkLsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:220 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3NetworkLsa ()
Ospfv3NetworkLsa (const Ospfv3NetworkLsa &other)
virtual ~Ospfv3NetworkLsa ()
Ospfv3NetworkLsa & operator= (const Ospfv3NetworkLsa &other)
virtual Ospfv3NetworkLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ospfv3Options & getOspfOptions () const
virtual Ospfv3Options & getOspfOptionsForUpdate ()
virtual void setOspfOptions (const Ospfv3Options &ospfOptions)
virtual void setAttachedRouterArraySize (size_t size)
virtual size_t getAttachedRouterArraySize () const
virtual const ::inet::Ipv4Address & getAttachedRouter (size_t k) const
virtual ::inet::Ipv4Address & getAttachedRouterForUpdate (size_t k)
virtual void setAttachedRouter (size_t k, const ::inet::Ipv4Address &attachedRouter)
virtual void insertAttachedRouter (size_t k, const ::inet::Ipv4Address &attachedRouter)
void insertAttachedRouter (const ::inet::Ipv4Address &attachedRouter)
virtual void appendAttachedRouter (const ::inet::Ipv4Address &attachedRouter)
virtual void eraseAttachedRouter (size_t k)
Public Member Functions inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3NetworkLsa &)=delete
Protected Member Functions inherited from inet::ospfv3::Ospfv3Lsa
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
Ospfv3Options ospfOptions
::inet::Ipv4Address * attachedRouter = nullptr
size_t attachedRouter_arraysize = 0
Protected Attributes inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3NetworkLsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:220 by opp_msgtool.
//Network LSA
class Ospfv3NetworkLsa extends Ospfv3Lsa
{
    Ospfv3Options ospfOptions;
    Ipv4Address attachedRouter[];
}
Constructor & Destructor Documentation
Ospfv3NetworkLsa() [1/2]
inet::ospfv3::Ospfv3NetworkLsa::Ospfv3NetworkLsa ()
Ospfv3NetworkLsa() [2/2]
inet::ospfv3::Ospfv3NetworkLsa::Ospfv3NetworkLsa (const Ospfv3NetworkLsa & other)
~Ospfv3NetworkLsa()
virtual inet::ospfv3::Ospfv3NetworkLsa::~Ospfv3NetworkLsa () virtual
Member Function Documentation
appendAttachedRouter()
virtual void inet::ospfv3::Ospfv3NetworkLsa::appendAttachedRouter (const ::inet::Ipv4Address & attachedRouter) virtual
copy()
void inet::ospfv3::Ospfv3NetworkLsa::copy (const Ospfv3NetworkLsa & other) private
dup()
virtual Ospfv3NetworkLsa* inet::ospfv3::Ospfv3NetworkLsa::dup () const inline override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
 {return new Ospfv3NetworkLsa(*this);}
eraseAttachedRouter()
virtual void inet::ospfv3::Ospfv3NetworkLsa::eraseAttachedRouter (size_t k) virtual
getAttachedRouter()
virtual const ::inet::Ipv4Address& inet::ospfv3::Ospfv3NetworkLsa::getAttachedRouter (size_t k) const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::hasLink(), inet::ospfv3::Ospfv3Area::networkLSADiffersFrom(), and inet::ospfv3::operator<<().
getAttachedRouterArraySize()
virtual size_t inet::ospfv3::Ospfv3NetworkLsa::getAttachedRouterArraySize () const virtual
Referenced by inet::ospfv3::calculateLSASize(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::hasLink(), inet::ospfv3::Ospfv3Area::networkLSADiffersFrom(), and inet::ospfv3::operator<<().
getAttachedRouterForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv3::Ospfv3NetworkLsa::getAttachedRouterForUpdate (size_t k) inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv3NetworkLsa*>(this)->getAttachedRouter(k));}
getOspfOptions()
virtual const Ospfv3Options& inet::ospfv3::Ospfv3NetworkLsa::getOspfOptions () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::networkLSADiffersFrom().
getOspfOptionsForUpdate()
virtual Ospfv3Options& inet::ospfv3::Ospfv3NetworkLsa::getOspfOptionsForUpdate () inline virtual
 { return const_cast<Ospfv3Options&>(const_cast<Ospfv3NetworkLsa*>(this)->getOspfOptions());}
insertAttachedRouter() [1/2]
void inet::ospfv3::Ospfv3NetworkLsa::insertAttachedRouter (const ::inet::Ipv4Address & attachedRouter) inline
 {appendAttachedRouter(attachedRouter);}
insertAttachedRouter() [2/2]
virtual void inet::ospfv3::Ospfv3NetworkLsa::insertAttachedRouter (size_t k, const ::inet::Ipv4Address & attachedRouter) virtual
operator=()
Ospfv3NetworkLsa& inet::ospfv3::Ospfv3NetworkLsa::operator= (const Ospfv3NetworkLsa & other)
operator==()
bool inet::ospfv3::Ospfv3NetworkLsa::operator== (const Ospfv3NetworkLsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3NetworkLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3NetworkLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setAttachedRouter()
virtual void inet::ospfv3::Ospfv3NetworkLsa::setAttachedRouter (size_t k, const ::inet::Ipv4Address & attachedRouter) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateNetworkLSA().
setAttachedRouterArraySize()
virtual void inet::ospfv3::Ospfv3NetworkLsa::setAttachedRouterArraySize (size_t size) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateNetworkLSA().
setOspfOptions()
virtual void inet::ospfv3::Ospfv3NetworkLsa::setOspfOptions (const Ospfv3Options & ospfOptions) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateNetworkLSA().
Member Data Documentation
attachedRouter
::inet::Ipv4Address* inet::ospfv3::Ospfv3NetworkLsa::attachedRouter = nullptr protected
attachedRouter_arraysize
size_t inet::ospfv3::Ospfv3NetworkLsa::attachedRouter_arraysize = 0 protected
ospfOptions
Ospfv3Options inet::ospfv3::Ospfv3NetworkLsa::ospfOptions protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h