INET Framework for OMNeT++/OMNEST: inet::Ipv4Route Class Reference
inet::Ipv4Route Class Reference
Ipv4 unicast route in IIpv4RoutingTable.
#include <Ipv4Route.h>
Public Member Functions
Ipv4Route ()
virtual ~Ipv4Route ()
virtual std::string str () const override
virtual std::string detailedInfo () const
bool operator== (const Ipv4Route &route) const
bool operator!= (const Ipv4Route &route) const
bool equals (const Ipv4Route &route) const
virtual void setRoutingTable (IIpv4RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
IIpv4RoutingTable * getRoutingTable () const
virtual bool isValid () const
test validity of route entry, e.g.
virtual void setDestination (Ipv4Address _dest)
virtual void setNetmask (Ipv4Address _netmask)
virtual void setGateway (Ipv4Address _gateway)
virtual void setInterface (NetworkInterface *_interfacePtr) override
virtual void setSourceType (SourceType _source) override
const char * getSourceTypeAbbreviation () const
virtual void setAdminDist (unsigned int _adminDist) override
virtual void setMetric (int _metric) override
const Ipv4Address & getDestination () const
Destination address prefix to match.
const Ipv4Address & getNetmask () const
Represents length of prefix to match.
const Ipv4Address & getGateway () const
Next hop address.
NetworkInterface * getInterface () const override
Next hop interface.
const char * getInterfaceName () const
Convenience method.
SourceType getSourceType () const override
Source of route.
unsigned int getAdminDist () const
Route source specific preference value.
int getMetric () const override
"Cost" to reach the destination
void setSource (cObject *_source) override
cObject * getSource () const override
Source of route.
cObject * getProtocolData () const override
void setProtocolData (cObject *protocolData) override
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int len) override
virtual void setNextHop (const L3Address &nextHop) override
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
virtual void setSourceType (SourceType type)=0
Protected Member Functions
void changed (int fieldCode)
Private Member Functions
Ipv4Route (const Ipv4Route &obj)
Ipv4Route & operator= (const Ipv4Route &obj)
Private Attributes
IIpv4RoutingTable * rt
the routing table in which this route is inserted, or nullptr
Ipv4Address dest
Destination.
Ipv4Address netmask
Route mask.
Ipv4Address gateway
Next hop.
NetworkInterface * interfacePtr
interface
SourceType sourceType
manual, routing prot, etc.
unsigned int adminDist
Cisco like administrative distance.
int metric
Metric ("cost" to reach the destination)
cObject * source
Object identifying the source.
cObject * protocolData
Routing Protocol specific data.
Additional Inherited Members
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Detailed Description
Ipv4 unicast route in IIpv4RoutingTable.
See also
IIpv4RoutingTable, Ipv4RoutingTable
Constructor & Destructor Documentation
Ipv4Route() [1/2]
inet::Ipv4Route::Ipv4Route (const Ipv4Route & obj) private
Ipv4Route() [2/2]
inet::Ipv4Route::Ipv4Route () inline
                 : rt(nullptr), interfacePtr(nullptr), sourceType(MANUAL), adminDist(dUnknown),
         metric(0), source(nullptr), protocolData(nullptr) {}
~Ipv4Route()
inet::Ipv4Route::~Ipv4Route () virtual
 {
     delete protocolData;
 }
Member Function Documentation
changed()
void inet::Ipv4Route::changed (int fieldCode) protected
 {
     if (rt)
         rt->routeChanged(this, fieldCode);
 }
detailedInfo()
std::string inet::Ipv4Route::detailedInfo () const virtual
 {
     return std::string();
 }
equals()
bool inet::Ipv4Route::equals (const Ipv4Route & route) const
 {
     return rt == route.rt && dest == route.dest && netmask == route.netmask && gateway == route.gateway &&
            interfacePtr == route.interfacePtr && sourceType == route.sourceType && metric == route.metric;
 }
getAdminDist()
unsigned int inet::Ipv4Route::getAdminDist () const inline
Route source specific preference value.
 { return adminDist; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), getSourceTypeAbbreviation(), inet::eigrp::EigrpIpv4Pdm::isRTSafeForAdd(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::Ipv4RoutingTable::routeLessThan(), inet::bgp::BgpRoutingTableEntry::str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), and inet::PimDm::unroutableMulticastPacketArrived().
getDestination()
const Ipv4Address& inet::Ipv4Route::getDestination () const inline
Destination address prefix to match.
 { return dest; }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::bgp::BgpRouter::addToAdvertiseList(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::bgp::BgpRouter::checkExternalRoute(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::bgp::BgpRouter::decisionProcess(), inet::bgp::BgpRouter::deleteBGPRoutingEntry(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ldp::findPeerAddrFromInterface(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv2::Router::getDefaultRoute(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), getSourceTypeAbbreviation(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::Ipv4RoutingTable::internalAddRoute(), inet::ospfv2::Ospfv2Area::isDefaultRoute(), inet::bgp::BgpRouter::isDefaultRoute(), inet::ospfv2::Router::isDirectRoute(), inet::ospfv3::Ospfv3Process::isInRoutingTable(), inet::bgp::BgpRouter::isInRoutingTable(), inet::bgp::BgpRouter::isInTable(), inet::bgp::BgpRouter::isReachable(), inet::ospfv2::Router::lookup(), inet::bgp::operator<<(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2RoutingTableEntry::operator==(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::Ipv4RoutingTable::printRoutingTable(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::Ldp::rebuildFecList(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Ted::rebuildRoutingTable(), inet::PimDm::receiveSignal(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::Ipv4RoutingTable::routeLessThan(), inet::bgp::BgpRoutingTableEntry::str(), str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), inet::ospfv2::Router::updateExternalRoute(), and inet::bgp::BgpRouter::updateSendProcess().
getDestinationAsGeneric()
virtual L3Address inet::Ipv4Route::getDestinationAsGeneric () const inline override virtual
Destination address prefix to match.
Implements inet::IRoute.
 { return getDestination(); }
Referenced by inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::operator==(), and inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry().
getGateway()
const Ipv4Address& inet::Ipv4Route::getGateway () const inline
Next hop address.
 { return gateway; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::visualizer::RoutingTableVisualizerBase::addRouteVisualizations(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::bgp::BgpRouter::decisionProcess(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::ospfv2::Router::isDirectRoute(), inet::bgp::operator<<(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::Ipv4RoutingTable::printRoutingTable(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::Ldp::rebuildFecList(), inet::Ted::rebuildRoutingTable(), inet::Ipv4NetworkConfigurator::routesHaveSameColor(), inet::Ipv4::routeUnicastPacket(), inet::bgp::BgpRoutingTableEntry::str(), str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), inet::PimDm::unroutableMulticastPacketArrived(), inet::PimSm::unroutableMulticastPacketArrived(), and inet::bgp::BgpRouter::updateSendProcess().
getInterface()
NetworkInterface* inet::Ipv4Route::getInterface () const inline override virtual
Next hop interface.
Implements inet::IRoute.
 { return interfacePtr; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::bgp::BgpRouter::decisionProcess(), inet::Ipv4RoutingTable::deleteInterfaceRoutes(), inet::Ipv4::determineOutgoingInterfaceForMulticastDatagram(), inet::Ldp::findPeerAddrFromInterface(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), inet::ospfv2::Ospfv2::handleInterfaceDown(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::Ipv4RoutingTable::internalAddRoute(), inet::bgp::BgpRouter::isExternalAddress(), inet::bgp::BgpRouter::isRouteExcluded(), inet::ospfv3::operator<<(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::Ipv4RoutingTable::printRoutingTable(), inet::PimDm::receiveSignal(), inet::Ipv4NetworkConfigurator::routesHaveSameColor(), inet::Ipv4::routeUnicastPacket(), inet::PimDm::rpfInterfaceHasChanged(), inet::Dsdv::start(), inet::bgp::BgpRoutingTableEntry::str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), inet::PimDm::unroutableMulticastPacketArrived(), and inet::PimSm::unroutableMulticastPacketArrived().
getInterfaceName()
const char * inet::Ipv4Route::getInterfaceName () const
Convenience method.
 {
     return interfacePtr ? interfacePtr->getInterfaceName() : "";
 }
Referenced by inet::Ipv4NetworkConfigurator::dumpConfig(), inet::bgp::operator<<(), inet::ospfv2::operator<<(), inet::Ted::rebuildRoutingTable(), inet::bgp::BgpRoutingTableEntry::str(), str(), and inet::ospfv2::Ospfv2RoutingTableEntry::str().
getMetric()
int inet::Ipv4Route::getMetric () const inline override virtual
"Cost" to reach the destination
Implements inet::IRoute.
 { return metric; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Dsdv::handleMessageWhenUp(), inet::eigrp::EigrpIpv4Pdm::installRouteToRT(), inet::bgp::operator<<(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::Ipv4RoutingTable::printRoutingTable(), inet::Ipv4RoutingTable::routeLessThan(), inet::Ipv4NetworkConfigurator::routesHaveSameColor(), inet::bgp::BgpRoutingTableEntry::str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), and inet::PimDm::unroutableMulticastPacketArrived().
getNetmask()
const Ipv4Address& inet::Ipv4Route::getNetmask () const inline
Represents length of prefix to match.
 { return netmask; }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::bgp::BgpRouter::decisionProcess(), inet::bgp::BgpRouter::deleteBGPRoutingEntry(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv2::Router::getDefaultRoute(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), inet::Dsdv::handleMessageWhenUp(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::Ipv4RoutingTable::internalAddRoute(), inet::ospfv2::Ospfv2Area::isDefaultRoute(), inet::bgp::BgpRouter::isDefaultRoute(), inet::ospfv3::Ospfv3Process::isInRoutingTable(), inet::bgp::BgpRouter::isInRoutingTable(), inet::bgp::BgpRouter::isInTable(), inet::bgp::BgpRouter::isReachable(), inet::bgp::BgpRouter::isRouteExcluded(), inet::bgp::operator<<(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2RoutingTableEntry::operator==(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::Ipv4RoutingTable::printRoutingTable(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::Ldp::rebuildFecList(), inet::PimDm::receiveSignal(), inet::Ipv4RoutingTable::routeLessThan(), inet::bgp::BgpRoutingTableEntry::str(), str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), inet::ospfv2::Router::updateExternalRoute(), and inet::bgp::BgpRouter::updateSendProcess().
getNextHopAsGeneric()
virtual L3Address inet::Ipv4Route::getNextHopAsGeneric () const inline override virtual
Next hop address.
Implements inet::IRoute.
 { return getGateway(); } // TODO rename Ipv4 method
Referenced by inet::ospfv2::Ospfv2::handleInterfaceDown().
getPrefixLength()
virtual int inet::Ipv4Route::getPrefixLength () const inline override virtual
Represents length of prefix to match.
Implements inet::IRoute.
 { return getNetmask().getNetmaskLength(); }
Referenced by inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::operator==(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getProtocolData()
cObject* inet::Ipv4Route::getProtocolData () const inline override virtual
Implements inet::IRoute.
 { return protocolData; }
getRoutingTable()
IIpv4RoutingTable* inet::Ipv4Route::getRoutingTable () const inline
 { return rt; }
Referenced by inet::visualizer::RoutingTableVisualizerBase::addRouteVisualization(), inet::Ipv4RoutingTable::deleteInterfaceRoutes(), inet::Ipv4RoutingTable::deleteRoute(), inet::visualizer::RoutingTableVisualizerBase::getRouteVisualization(), getRoutingTableAsGeneric(), inet::Ipv4RoutingTable::purge(), inet::Ipv4RoutingTable::removeRoute(), inet::visualizer::RoutingTableVisualizerBase::removeRouteVisualization(), inet::bgp::BgpRoutingTableEntry::str(), inet::ospfv2::Ospfv2RoutingTableEntry::str(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
getRoutingTableAsGeneric()
IRoutingTable * inet::Ipv4Route::getRoutingTableAsGeneric () const override virtual
The routing table in which this route is inserted, or nullptr.
Implements inet::IRoute.
 {
     return getRoutingTable();
 }
getSource()
cObject* inet::Ipv4Route::getSource () const inline override virtual
Source of route.
Implements inet::IRoute.
 { return source; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable().
getSourceType()
SourceType inet::Ipv4Route::getSourceType () const inline override virtual
Source of route.
MANUAL (read from file), from routing protocol, etc
Implements inet::IRoute.
 { return sourceType; }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::bgp::BgpRouter::decisionProcess(), inet::eigrp::EigrpIpv4Pdm::installRouteToRT(), inet::bgp::BgpRouter::isReachable(), inet::bgp::BgpRouter::isRouteExcluded(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::bgp::BgpRouter::ospfExist(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::eigrp::EigrpIpv4Pdm::removeRouteFromRT(), inet::Ipv4NetworkConfigurator::routesHaveSameColor(), inet::PimDm::rpfInterfaceHasChanged(), and inet::PimDm::unroutableMulticastPacketArrived().
getSourceTypeAbbreviation()
const char * inet::Ipv4Route::getSourceTypeAbbreviation () const
{
     switch (sourceType) {
         case IFACENETMASK:
             return "C";
         case MANUAL:
             return getDestination().isUnspecified() ? "S*" : "S";
         case ROUTER_ADVERTISEMENT:
             return "ra";
         case RIP:
             return "R";
         case OSPF:
             return "O";
         case BGP:
             return "B";
         case EIGRP:
             return getAdminDist() < Ipv4Route::dEIGRPExternal ? "D" : "D EX";
         case LISP:
             return "l";
         case BABEL:
             return "ba";
         case ODR:
             return "o";
         default:
             return "???";
     }
 }
Referenced by inet::bgp::BgpRoutingTableEntry::str(), str(), and inet::ospfv2::Ospfv2RoutingTableEntry::str().
isValid()
virtual bool inet::Ipv4Route::isValid () const inline virtual
test validity of route entry, e.g.
check expiry
Reimplemented in inet::DsdvIpv4Route.
 { return true; }
Referenced by inet::Ipv4RoutingTable::purge().
operator!=()
bool inet::Ipv4Route::operator!= (const Ipv4Route & route) const inline
 { return !equals(route); }
operator=()
Ipv4Route& inet::Ipv4Route::operator= (const Ipv4Route & obj) private
operator==()
bool inet::Ipv4Route::operator== (const Ipv4Route & route) const inline
 { return equals(route); }
setAdminDist()
virtual void inet::Ipv4Route::setAdminDist (unsigned int _adminDist) inline override virtual
Implements inet::IRoute.
 { if (adminDist != _adminDist) { adminDist = _adminDist; changed(F_ADMINDIST); } }
Referenced by inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::bgp::BgpRouter::decisionProcess(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setDestination() [1/2]
virtual void inet::Ipv4Route::setDestination (const L3Address & dest) inline override virtual
Implements inet::IRoute.
 { setDestination(dest.toIpv4()); }
Referenced by setDestination().
setDestination() [2/2]
virtual void inet::Ipv4Route::setDestination (Ipv4Address _dest) inline virtual
 { if (dest != _dest) { dest = _dest; changed(F_DESTINATION); } }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::DhcpClient::bindLease(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::bgp::BgpConfigReader::loadASConfig(), inet::ospfv2::Router::lookup(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::bgp::BgpRouter::processMessage(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Ted::rebuildRoutingTable(), inet::ospfv2::Router::updateExternalRoute(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setGateway()
virtual void inet::Ipv4Route::setGateway (Ipv4Address _gateway) inline virtual
 { if (gateway != _gateway) { gateway = _gateway; changed(F_NEXTHOP); } }
Referenced by inet::ospfv2::Ospfv2RoutingTableEntry::addNextHop(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::DhcpClient::bindLease(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::bgp::BgpRouter::decisionProcess(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::Ted::rebuildRoutingTable(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setInterface()
virtual void inet::Ipv4Route::setInterface (NetworkInterface * _interfacePtr) inline override virtual
Implements inet::IRoute.
 { if (interfacePtr != _interfacePtr) { interfacePtr = _interfacePtr; changed(F_IFACE); } }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::ospfv2::Ospfv2RoutingTableEntry::addNextHop(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::addNextHop(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::DhcpClient::bindLease(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::bgp::BgpRouter::decisionProcess(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Ted::rebuildRoutingTable(), inet::ospfv2::Router::updateExternalRoute(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setMetric()
virtual void inet::Ipv4Route::setMetric (int _metric) inline override virtual
Implements inet::IRoute.
 { if (metric != _metric) { metric = _metric; changed(F_METRIC); } }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Ted::rebuildRoutingTable(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setCost(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setPathType(), inet::eigrp::EigrpIpv4Pdm::setRTRouteMetric(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::setType2Cost(), inet::ospfv2::Router::updateExternalRoute(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setNetmask()
virtual void inet::Ipv4Route::setNetmask (Ipv4Address _netmask) inline virtual
 { if (netmask != _netmask) { netmask = _netmask; changed(F_PREFIX_LENGTH); } }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::DhcpClient::bindLease(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::bgp::BgpConfigReader::loadASConfig(), inet::ospfv2::Router::lookup(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::bgp::BgpRouter::processMessage(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Ted::rebuildRoutingTable(), inet::ospfv2::Router::updateExternalRoute(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setNextHop()
virtual void inet::Ipv4Route::setNextHop (const L3Address & nextHop) inline override virtual
Implements inet::IRoute.
 { setGateway(nextHop.toIpv4()); } // TODO rename Ipv4 method
Referenced by inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
setPrefixLength()
virtual void inet::Ipv4Route::setPrefixLength (int len) inline override virtual
Implements inet::IRoute.
 { setNetmask(Ipv4Address::makeNetmask(len)); }
Referenced by inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry().
setProtocolData()
void inet::Ipv4Route::setProtocolData (cObject * protocolData) inline override virtual
Implements inet::IRoute.
 { this->protocolData = protocolData; }
setRoutingTable()
virtual void inet::Ipv4Route::setRoutingTable (IIpv4RoutingTable * rt) inline virtual
To be called by the routing table when this route is added or removed from it.
 { this->rt = rt; }
Referenced by inet::Ipv4RoutingTable::internalAddRoute(), inet::Ipv4RoutingTable::removeRoute(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setSource()
void inet::Ipv4Route::setSource (cObject * _source) inline override virtual
Implements inet::IRoute.
 { if (source != _source) { source = _source; changed(F_SOURCE); } }
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
setSourceType()
virtual void inet::Ipv4Route::setSourceType (SourceType _source) inline override virtual
 { if (sourceType != _source) { sourceType = _source; changed(F_SOURCE); } }
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry(), inet::DhcpClient::bindLease(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::Ipv4NetworkConfigurator::optimizeRoutes(), inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry(), inet::ospfv3::Ospfv3Ipv4RoutingTableEntry::Ospfv3Ipv4RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::Ted::rebuildRoutingTable(), inet::ospfv2::Router::updateExternalRoute(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
str()
std::string inet::Ipv4Route::str () const override virtual
Reimplemented in inet::ospfv2::Ospfv2RoutingTableEntry, and inet::bgp::BgpRoutingTableEntry.
 {
     std::stringstream out;
     out << getSourceTypeAbbreviation();
     if (getDestination().isUnspecified())
         out << " 0.0.0.0";
     else
         out << " " << getDestination();
     out << "/";
     if (getNetmask().isUnspecified())
         out << "0";
     else
         out << getNetmask().getNetmaskLength();
     out << " gw:";
     if (gateway.isUnspecified())
         out << "*";
     else
         out << getGateway();
     if (rt && rt->isAdminDistEnabled())
         out << " AD:" << adminDist;
     out << " metric:" << metric;
     out << " if:";
     if (!interfacePtr)
         out << "*";
     else
         out << getInterfaceName();
     if (protocolData)
         out << " " << protocolData->str();
     return out.str();
 }
Referenced by inet::Ipv4RoutingTable::addRoute(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Ipv4RoutingTable::deleteRoute(), and inet::Ipv4RoutingTable::removeRoute().
Member Data Documentation
adminDist
unsigned int inet::Ipv4Route::adminDist private
Cisco like administrative distance.
Referenced by str().
dest
Ipv4Address inet::Ipv4Route::dest private
Destination.
Referenced by equals().
gateway
Ipv4Address inet::Ipv4Route::gateway private
Next hop.
Referenced by equals(), and str().
interfacePtr
NetworkInterface* inet::Ipv4Route::interfacePtr private
interface
Referenced by equals(), getInterfaceName(), and str().
metric
int inet::Ipv4Route::metric private
Metric ("cost" to reach the destination)
Referenced by equals(), and str().
netmask
Ipv4Address inet::Ipv4Route::netmask private
Route mask.
Referenced by equals().
protocolData
cObject* inet::Ipv4Route::protocolData private
Routing Protocol specific data.
Referenced by str(), and ~Ipv4Route().
rt
IIpv4RoutingTable* inet::Ipv4Route::rt private
the routing table in which this route is inserted, or nullptr
Referenced by changed(), equals(), and str().
source
cObject* inet::Ipv4Route::source private
Object identifying the source.
sourceType
SourceType inet::Ipv4Route::sourceType private
manual, routing prot, etc.
Referenced by equals(), and getSourceTypeAbbreviation().
The documentation for this class was generated from the following files:
Ipv4Route.h
Ipv4Route.cc