INET Framework for OMNeT++/OMNEST: inet::rtp::RtpHeader Class Reference
inet::rtp::RtpHeader Class Reference
Class generated from inet/transportlayer/rtp/RtpPacket.msg:25 by opp_msgtool.
#include <RtpPacket_m.h>
Public Member Functions
RtpHeader ()
RtpHeader (const RtpHeader &other)
virtual ~RtpHeader ()
RtpHeader & operator= (const RtpHeader &other)
virtual RtpHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getVersion () const
virtual void setVersion (uint8_t version)
virtual bool getPaddingFlag () const
virtual void setPaddingFlag (bool paddingFlag)
virtual bool getExtensionFlag () const
virtual void setExtensionFlag (bool extensionFlag)
virtual bool getMarker () const
virtual void setMarker (bool marker)
virtual int8_t getPayloadType () const
virtual void setPayloadType (int8_t payloadType)
virtual uint16_t getSequenceNumber () const
virtual void setSequenceNumber (uint16_t sequenceNumber)
virtual uint32_t getTimeStamp () const
virtual void setTimeStamp (uint32_t timeStamp)
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
virtual void setCsrcArraySize (size_t size)
virtual size_t getCsrcArraySize () const
virtual uint32_t getCsrc (size_t k) const
virtual void setCsrc (size_t k, uint32_t csrc)
virtual void insertCsrc (size_t k, uint32_t csrc)
void insertCsrc (uint32_t csrc)
virtual void appendCsrc (uint32_t csrc)
virtual void eraseCsrc (size_t k)
virtual std::string str () const override
Writes a one line info about this RtpHeader into the given string.
virtual void dump () const
Writes a longer description about this RtpHeader into the given stream.
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const RtpHeader &)=delete
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Protected Attributes
uint8_t version = 2
bool paddingFlag = false
bool extensionFlag = false
bool marker = false
int8_t payloadType = 0
uint16_t sequenceNumber = 0
uint32_t timeStamp = 0
uint32_t ssrc = 0
uint32_t * csrc = nullptr
size_t csrc_arraysize = 0
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const RtpHeader &other)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Class generated from inet/transportlayer/rtp/RtpPacket.msg:25 by opp_msgtool.
//
// This class represents an RTP data packet. Real data can either
// be encapsulated, or simulated by adding length.
//
// The following RTP header fields exist but aren't used:
// padding, extension, csrcCount. The csrcList can't be used
// because csrcCount is always 0.
//
class RtpHeader extends FieldsChunk
{
    chunkLength = RTPPACKET_FIX_HEADERLENGTH;  // 12-byte fixed header
    // The rtp version of this ~RtpPacket.
    uint8_t version = 2;      // 2 bits
    // Set to 1 if padding is used in this ~RtpPacket, 0 otherwise.
    // This implementation doesn't use padding bytes, so it is always 0.
    bool paddingFlag = false;      // 1 bit
    // Set to 1, if this ~RtpPacket contains an rtp header extension, 0 otherwise.
    // This implementation doesn't support rtp header extensions, so it is always 0.
    bool extensionFlag = false;      // 1 bit
    // uint8_t cc;      // 4 bits, csrc count
    // The marker.
    bool marker = false;      // 1 bit
    // The type of payload carried in this ~RtpPacket.
    int8_t payloadType;      // 7 bits
    // The sequence number of this ~RtpPacket.
    uint16_t sequenceNumber;      // 16 bits
    // The rtp time stamp of this ~RtpPacket.
    uint32_t timeStamp;      // 32 bits
    // The ssrc identifier of the creator of this ~RtpPacket.
    uint32_t ssrc;      // 32 bits
    // no mixers, no contributing sources
    uint32_t csrc[];      // cc * 32 bits
}
Constructor & Destructor Documentation
RtpHeader() [1/2]
inet::rtp::RtpHeader::RtpHeader ()
RtpHeader() [2/2]
inet::rtp::RtpHeader::RtpHeader (const RtpHeader & other)
~RtpHeader()
virtual inet::rtp::RtpHeader::~RtpHeader () virtual
Member Function Documentation
appendCsrc()
virtual void inet::rtp::RtpHeader::appendCsrc (uint32_t csrc) virtual
copy()
void inet::rtp::RtpHeader::copy (const RtpHeader & other) private
dump()
void inet::rtp::RtpHeader::dump () const virtual
Writes a longer description about this RtpHeader into the given stream.
 {
     EV_INFO << "RtpHeader:" << endl;
     EV_INFO << "  payloadType = " << payloadType << endl;
     EV_INFO << "  sequenceNumber = " << sequenceNumber << endl;
     EV_INFO << "  timeStamp = " << timeStamp << endl;
 }
dup()
virtual RtpHeader* inet::rtp::RtpHeader::dup () const inline override virtual
 {return new RtpHeader(*this);}
eraseCsrc()
virtual void inet::rtp::RtpHeader::eraseCsrc (size_t k) virtual
getCsrc()
virtual uint32_t inet::rtp::RtpHeader::getCsrc (size_t k) const virtual
getCsrcArraySize()
virtual size_t inet::rtp::RtpHeader::getCsrcArraySize () const virtual
getExtensionFlag()
virtual bool inet::rtp::RtpHeader::getExtensionFlag () const virtual
getMarker()
virtual bool inet::rtp::RtpHeader::getMarker () const virtual
getPaddingFlag()
virtual bool inet::rtp::RtpHeader::getPaddingFlag () const virtual
getPayloadType()
virtual int8_t inet::rtp::RtpHeader::getPayloadType () const virtual
getSequenceNumber()
virtual uint16_t inet::rtp::RtpHeader::getSequenceNumber () const virtual
Referenced by inet::rtp::compareRTPPacketsBySequenceNumber().
getSsrc()
virtual uint32_t inet::rtp::RtpHeader::getSsrc () const virtual
Referenced by inet::rtp::RtpProfile::dataIn(), and inet::rtp::Rtcp::processIncomingRTPPacket().
getTimeStamp()
virtual uint32_t inet::rtp::RtpHeader::getTimeStamp () const virtual
getVersion()
virtual uint8_t inet::rtp::RtpHeader::getVersion () const virtual
insertCsrc() [1/2]
virtual void inet::rtp::RtpHeader::insertCsrc (size_t k, uint32_t csrc) virtual
insertCsrc() [2/2]
void inet::rtp::RtpHeader::insertCsrc (uint32_t csrc) inline
 {appendCsrc(csrc);}
operator=()
RtpHeader& inet::rtp::RtpHeader::operator= (const RtpHeader & other)
operator==()
bool inet::rtp::RtpHeader::operator== (const RtpHeader &) protected delete
parsimPack()
virtual void inet::rtp::RtpHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::rtp::doParsimUnpacking().
setCsrc()
virtual void inet::rtp::RtpHeader::setCsrc (size_t k, uint32_t csrc) virtual
setCsrcArraySize()
virtual void inet::rtp::RtpHeader::setCsrcArraySize (size_t size) virtual
setExtensionFlag()
virtual void inet::rtp::RtpHeader::setExtensionFlag (bool extensionFlag) virtual
setMarker()
virtual void inet::rtp::RtpHeader::setMarker (bool marker) virtual
setPaddingFlag()
virtual void inet::rtp::RtpHeader::setPaddingFlag (bool paddingFlag) virtual
setPayloadType()
virtual void inet::rtp::RtpHeader::setPayloadType (int8_t payloadType) virtual
setSequenceNumber()
virtual void inet::rtp::RtpHeader::setSequenceNumber (uint16_t sequenceNumber) virtual
setSsrc()
virtual void inet::rtp::RtpHeader::setSsrc (uint32_t ssrc) virtual
setTimeStamp()
virtual void inet::rtp::RtpHeader::setTimeStamp (uint32_t timeStamp) virtual
setVersion()
virtual void inet::rtp::RtpHeader::setVersion (uint8_t version) virtual
str()
std::string inet::rtp::RtpHeader::str () const override virtual
Writes a one line info about this RtpHeader into the given string.
Reimplemented from inet::Chunk.
 {
     std::stringstream out;
     out << "RtpHeader: payloadType=" << payloadType;
     return out.str();
 }
Member Data Documentation
csrc
uint32_t* inet::rtp::RtpHeader::csrc = nullptr protected
csrc_arraysize
size_t inet::rtp::RtpHeader::csrc_arraysize = 0 protected
extensionFlag
bool inet::rtp::RtpHeader::extensionFlag = false protected
marker
bool inet::rtp::RtpHeader::marker = false protected
paddingFlag
bool inet::rtp::RtpHeader::paddingFlag = false protected
payloadType
int8_t inet::rtp::RtpHeader::payloadType = 0 protected
Referenced by dump(), and str().
sequenceNumber
uint16_t inet::rtp::RtpHeader::sequenceNumber = 0 protected
Referenced by dump().
ssrc
uint32_t inet::rtp::RtpHeader::ssrc = 0 protected
timeStamp
uint32_t inet::rtp::RtpHeader::timeStamp = 0 protected
Referenced by dump().
version
uint8_t inet::rtp::RtpHeader::version = 2 protected
The documentation for this class was generated from the following files:
RtpPacket_m.h
RtpPacket.cc