INET Framework for OMNeT++/OMNEST: inet::physicallayer::INeighborCache Class Reference
inet::physicallayer::INeighborCache Class Reference abstract
This interface keeps track of neighbor relationships between radios.
#include <INeighborCache.h>
Public Member Functions
virtual void addRadio (const IRadio *radio)=0
virtual void removeRadio (const IRadio *radio)=0
virtual void sendToNeighbors (IRadio *transmitter, const IWirelessSignal *signal, double range) const =0
Sends the provided frame (using the radio medium) to all neighbors within the given range.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface keeps track of neighbor relationships between radios.
Member Function Documentation
addRadio()
virtual void inet::physicallayer::INeighborCache::addRadio (const IRadio * radio) pure virtual
Implemented in inet::physicallayer::GridNeighborCache, inet::physicallayer::NeighborListNeighborCache, and inet::physicallayer::QuadTreeNeighborCache.
Referenced by inet::physicallayer::RadioMedium::addRadio().
removeRadio()
virtual void inet::physicallayer::INeighborCache::removeRadio (const IRadio * radio) pure virtual
Implemented in inet::physicallayer::GridNeighborCache, inet::physicallayer::NeighborListNeighborCache, and inet::physicallayer::QuadTreeNeighborCache.
Referenced by inet::physicallayer::RadioMedium::removeRadio().
sendToNeighbors()
virtual void inet::physicallayer::INeighborCache::sendToNeighbors (IRadio * transmitter, const IWirelessSignal * signal, double range) const pure virtual
Sends the provided frame (using the radio medium) to all neighbors within the given range.
Implemented in inet::physicallayer::GridNeighborCache, inet::physicallayer::NeighborListNeighborCache, and inet::physicallayer::QuadTreeNeighborCache.
Referenced by inet::physicallayer::RadioMedium::sendToAffectedRadios().
The documentation for this class was generated from the following file:
INeighborCache.h