INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2AsExternalLsaContents Class Reference
inet::ospfv2::Ospfv2AsExternalLsaContents Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:191 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2AsExternalLsaContents ()
Ospfv2AsExternalLsaContents (const Ospfv2AsExternalLsaContents &other)
virtual ~Ospfv2AsExternalLsaContents ()
Ospfv2AsExternalLsaContents & operator= (const Ospfv2AsExternalLsaContents &other)
virtual Ospfv2AsExternalLsaContents * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getNetworkMask () const
virtual ::inet::Ipv4Address & getNetworkMaskForUpdate ()
virtual void setNetworkMask (const ::inet::Ipv4Address &networkMask)
virtual void setExternalTOSInfoArraySize (size_t size)
virtual size_t getExternalTOSInfoArraySize () const
virtual const Ospfv2ExternalTosInfo & getExternalTOSInfo (size_t k) const
virtual Ospfv2ExternalTosInfo & getExternalTOSInfoForUpdate (size_t k)
virtual void setExternalTOSInfo (size_t k, const Ospfv2ExternalTosInfo &externalTOSInfo)
virtual void insertExternalTOSInfo (size_t k, const Ospfv2ExternalTosInfo &externalTOSInfo)
void insertExternalTOSInfo (const Ospfv2ExternalTosInfo &externalTOSInfo)
virtual void appendExternalTOSInfo (const Ospfv2ExternalTosInfo &externalTOSInfo)
virtual void eraseExternalTOSInfo (size_t k)
Protected Member Functions
bool operator== (const Ospfv2AsExternalLsaContents &)=delete
Protected Attributes
::inet::Ipv4Address networkMask
Ospfv2ExternalTosInfo * externalTOSInfo = nullptr
size_t externalTOSInfo_arraysize = 0
Private Member Functions
void copy (const Ospfv2AsExternalLsaContents &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:191 by opp_msgtool.
//
// Represents the contents of an OSPF AS External LSA
//
class Ospfv2AsExternalLsaContents extends cObject
{
    @packetData;
    Ipv4Address networkMask;
    Ospfv2ExternalTosInfo externalTOSInfo[];
}
Constructor & Destructor Documentation
Ospfv2AsExternalLsaContents() [1/2]
inet::ospfv2::Ospfv2AsExternalLsaContents::Ospfv2AsExternalLsaContents ()
Ospfv2AsExternalLsaContents() [2/2]
inet::ospfv2::Ospfv2AsExternalLsaContents::Ospfv2AsExternalLsaContents (const Ospfv2AsExternalLsaContents & other)
~Ospfv2AsExternalLsaContents()
virtual inet::ospfv2::Ospfv2AsExternalLsaContents::~Ospfv2AsExternalLsaContents () virtual
Member Function Documentation
appendExternalTOSInfo()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::appendExternalTOSInfo (const Ospfv2ExternalTosInfo & externalTOSInfo) virtual
copy()
void inet::ospfv2::Ospfv2AsExternalLsaContents::copy (const Ospfv2AsExternalLsaContents & other) private
dup()
virtual Ospfv2AsExternalLsaContents* inet::ospfv2::Ospfv2AsExternalLsaContents::dup () const inline override virtual
 {return new Ospfv2AsExternalLsaContents(*this);}
eraseExternalTOSInfo()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::eraseExternalTOSInfo (size_t k) virtual
getExternalTOSInfo()
virtual const Ospfv2ExternalTosInfo& inet::ospfv2::Ospfv2AsExternalLsaContents::getExternalTOSInfo (size_t k) const virtual
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2::checkExternalRoute(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::operator<<(), inet::ospfv2::Router::printAsExternalLsa(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Router::updateExternalRoute().
getExternalTOSInfoArraySize()
virtual size_t inet::ospfv2::Ospfv2AsExternalLsaContents::getExternalTOSInfoArraySize () const virtual
Referenced by inet::ospfv2::calculateLsaSize(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::operator<<(), and inet::ospfv2::MessageHandler::printLinkStateUpdatePacket().
getExternalTOSInfoForUpdate()
virtual Ospfv2ExternalTosInfo& inet::ospfv2::Ospfv2AsExternalLsaContents::getExternalTOSInfoForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv2ExternalTosInfo&>(const_cast<Ospfv2AsExternalLsaContents*>(this)->getExternalTOSInfo(k));}
Referenced by inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Ospfv2ConfigReader::initiateDefaultRouteDistribution(), inet::ospfv2::Ospfv2::insertExternalRoute(), and inet::ospfv2::Ospfv2ConfigReader::loadExternalRoute().
getNetworkMask()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2AsExternalLsaContents::getNetworkMask () const virtual
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::Router::printAsExternalLsa(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Router::updateExternalRoute().
getNetworkMaskForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2AsExternalLsaContents::getNetworkMaskForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2AsExternalLsaContents*>(this)->getNetworkMask());}
insertExternalTOSInfo() [1/2]
void inet::ospfv2::Ospfv2AsExternalLsaContents::insertExternalTOSInfo (const Ospfv2ExternalTosInfo & externalTOSInfo) inline
 {appendExternalTOSInfo(externalTOSInfo);}
insertExternalTOSInfo() [2/2]
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::insertExternalTOSInfo (size_t k, const Ospfv2ExternalTosInfo & externalTOSInfo) virtual
operator=()
Ospfv2AsExternalLsaContents& inet::ospfv2::Ospfv2AsExternalLsaContents::operator= (const Ospfv2AsExternalLsaContents & other)
operator==()
bool inet::ospfv2::Ospfv2AsExternalLsaContents::operator== (const Ospfv2AsExternalLsaContents &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::ospfv2::doParsimUnpacking().
setExternalTOSInfo()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::setExternalTOSInfo (size_t k, const Ospfv2ExternalTosInfo & externalTOSInfo) virtual
setExternalTOSInfoArraySize()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::setExternalTOSInfoArraySize (size_t size) virtual
Referenced by inet::ospfv2::Ospfv2ConfigReader::initiateDefaultRouteDistribution(), inet::ospfv2::Ospfv2::insertExternalRoute(), and inet::ospfv2::Ospfv2ConfigReader::loadExternalRoute().
setNetworkMask()
virtual void inet::ospfv2::Ospfv2AsExternalLsaContents::setNetworkMask (const ::inet::Ipv4Address & networkMask) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Ospfv2ConfigReader::initiateDefaultRouteDistribution(), inet::ospfv2::Ospfv2::insertExternalRoute(), and inet::ospfv2::Ospfv2ConfigReader::loadExternalRoute().
Member Data Documentation
externalTOSInfo
Ospfv2ExternalTosInfo* inet::ospfv2::Ospfv2AsExternalLsaContents::externalTOSInfo = nullptr protected
externalTOSInfo_arraysize
size_t inet::ospfv2::Ospfv2AsExternalLsaContents::externalTOSInfo_arraysize = 0 protected
networkMask
::inet::Ipv4Address inet::ospfv2::Ospfv2AsExternalLsaContents::networkMask protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h