INET Framework for OMNeT++/OMNEST: inet::L2NodeConfigurator Class Reference
inet::L2NodeConfigurator Class Reference
Configures L2 data of a node.
#include <L2NodeConfigurator.h>
Public Member Functions
L2NodeConfigurator ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Protected Member Functions
virtual int numInitStages () const override
virtual void handleMessage (cMessage *msg) override
virtual void initialize (int stage) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void prepareNode ()
virtual void prepareInterface (NetworkInterface *networkInterface)
virtual void configureNode ()
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Protected Attributes
opp_component_ptr< NodeStatus > nodeStatus
ModuleRefByPar< IInterfaceTable > interfaceTable
ModuleRefByPar< L2NetworkConfigurator > networkConfigurator
Detailed Description
Configures L2 data of a node.
See the NED definition for details.
Constructor & Destructor Documentation
L2NodeConfigurator()
inet::L2NodeConfigurator::L2NodeConfigurator ()
 {
 }
Member Function Documentation
configureNode()
void inet::L2NodeConfigurator::configureNode () protected virtual
 {
 //    std::cout << "configureNode(): " << interfaceTable->getNumInterfaces() << endl;
     for (int i = 0; i < interfaceTable->getNumInterfaces(); i++)
         networkConfigurator->configureInterface(interfaceTable->getInterface(i));
 }
Referenced by handleOperationStage().
handleMessage()
virtual void inet::L2NodeConfigurator::handleMessage (cMessage * msg) inline override protected virtual
 { throw cRuntimeError("this module doesn't handle messages, it runs only in initialize()"); }
handleOperationStage()
bool inet::L2NodeConfigurator::handleOperationStage (LifecycleOperation * operation, IDoneCallback * doneCallback) override protected virtual
Perform one stage of a lifecycle operation.
Processing may be done entirely within this method, or may be a longer process that involves nonzero simulation time or several events, and is triggered by this method call.
Return value: true = "done"; false = "not yet done, will invoke doneCallback when done"
Implements inet::ILifecycle.
 {
     Enter_Method("handleOperationStage");
     if (dynamic_cast<ModuleStartOperation *>(operation)) {
         if (static_cast<ModuleStartOperation::Stage>(operation->getCurrentStage()) == ModuleStartOperation::STAGE_LINK_LAYER) {
             prepareNode();
             configureNode();
         }
     }
     else if (dynamic_cast<ModuleStopOperation *>(operation))
         /*nothing to do*/;
     else if (dynamic_cast<ModuleCrashOperation *>(operation))
         /*nothing to do*/;
     else
         throw cRuntimeError("Unsupported lifecycle operation '%s'", operation->getClassName());
     return true;
 }
initialize()
void inet::L2NodeConfigurator::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         cModule *host = getContainingNode(this);
         nodeStatus = dynamic_cast<NodeStatus *>(host->getSubmodule("status"));
         interfaceTable.reference(this, "interfaceTableModule", true);
         networkConfigurator.reference(this, "l2ConfiguratorModule", false);
         host->subscribe(interfaceCreatedSignal, this);
     }
 }
numInitStages()
virtual int inet::L2NodeConfigurator::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
prepareInterface()
void inet::L2NodeConfigurator::prepareInterface (NetworkInterface * networkInterface) protected virtual
 {
 //    ASSERT(!networkInterface->getProtocolData<Ieee8021dInterfaceData>());
     networkInterface->addProtocolData<Ieee8021dInterfaceData>();
 }
Referenced by prepareNode(), and receiveSignal().
prepareNode()
void inet::L2NodeConfigurator::prepareNode () protected virtual
 {
     for (int i = 0; i < interfaceTable->getNumInterfaces(); i++)
         prepareInterface(interfaceTable->getInterface(i));
 }
Referenced by handleOperationStage().
receiveSignal()
void inet::L2NodeConfigurator::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     if (nodeStatus && nodeStatus->getState() != NodeStatus::UP)
         return;
     if (signalID == interfaceCreatedSignal) {
         NetworkInterface *ie = check_and_cast<NetworkInterface *>(obj);
         prepareInterface(ie);
         if (networkConfigurator)
             networkConfigurator->configureInterface(ie);
     }
 }
Member Data Documentation
interfaceTable
ModuleRefByPar<IInterfaceTable> inet::L2NodeConfigurator::interfaceTable protected
Referenced by configureNode(), initialize(), and prepareNode().
networkConfigurator
ModuleRefByPar<L2NetworkConfigurator> inet::L2NodeConfigurator::networkConfigurator protected
Referenced by configureNode(), initialize(), and receiveSignal().
nodeStatus
opp_component_ptr<NodeStatus> inet::L2NodeConfigurator::nodeStatus protected
Referenced by initialize(), and receiveSignal().
The documentation for this class was generated from the following files:
L2NodeConfigurator.h
L2NodeConfigurator.cc