INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2AsExternalLsa Class Reference
inet::ospfv2::Ospfv2AsExternalLsa Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:201 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2AsExternalLsa ()
Ospfv2AsExternalLsa (const Ospfv2AsExternalLsa &other)
virtual ~Ospfv2AsExternalLsa ()
Ospfv2AsExternalLsa & operator= (const Ospfv2AsExternalLsa &other)
virtual Ospfv2AsExternalLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ospfv2AsExternalLsaContents & getContents () const
virtual Ospfv2AsExternalLsaContents & getContentsForUpdate ()
virtual void setContents (const Ospfv2AsExternalLsaContents &contents)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv2AsExternalLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes
Ospfv2AsExternalLsaContents contents
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Private Member Functions
void copy (const Ospfv2AsExternalLsa &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:201 by opp_msgtool.
//
// Represents an OSPF AS External LSA
//
class Ospfv2AsExternalLsa extends Ospfv2Lsa
{
    // header.lsType = AS_EXTERNAL_LSA_TYPE;
    Ospfv2AsExternalLsaContents contents;
}
Constructor & Destructor Documentation
Ospfv2AsExternalLsa() [1/2]
inet::ospfv2::Ospfv2AsExternalLsa::Ospfv2AsExternalLsa ()
Ospfv2AsExternalLsa() [2/2]
inet::ospfv2::Ospfv2AsExternalLsa::Ospfv2AsExternalLsa (const Ospfv2AsExternalLsa & other)
~Ospfv2AsExternalLsa()
virtual inet::ospfv2::Ospfv2AsExternalLsa::~Ospfv2AsExternalLsa () virtual
Member Function Documentation
copy()
void inet::ospfv2::Ospfv2AsExternalLsa::copy (const Ospfv2AsExternalLsa & other) private
dup()
virtual Ospfv2AsExternalLsa* inet::ospfv2::Ospfv2AsExternalLsa::dup () const inline override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
 {return new Ospfv2AsExternalLsa(*this);}
getContents()
virtual const Ospfv2AsExternalLsaContents& inet::ospfv2::Ospfv2AsExternalLsa::getContents () const virtual
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::calculateLsaSize(), inet::ospfv2::Ospfv2::checkExternalRoute(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::Router::printAsExternalLsa(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeAsExternalLsa().
getContentsForUpdate()
virtual Ospfv2AsExternalLsaContents& inet::ospfv2::Ospfv2AsExternalLsa::getContentsForUpdate () inline virtual
 { return const_cast<Ospfv2AsExternalLsaContents&>(const_cast<Ospfv2AsExternalLsa*>(this)->getContents());}
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), and inet::ospfv2::Router::getUniqueLinkStateID().
operator=()
Ospfv2AsExternalLsa& inet::ospfv2::Ospfv2AsExternalLsa::operator= (const Ospfv2AsExternalLsa & other)
operator==()
bool inet::ospfv2::Ospfv2AsExternalLsa::operator== (const Ospfv2AsExternalLsa &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2AsExternalLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2AsExternalLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimUnpacking().
setContents()
virtual void inet::ospfv2::Ospfv2AsExternalLsa::setContents (const Ospfv2AsExternalLsaContents & contents) virtual
Referenced by inet::ospfv2::Router::updateExternalRoute().
Member Data Documentation
contents
Ospfv2AsExternalLsaContents inet::ospfv2::Ospfv2AsExternalLsa::contents protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h