INET Framework for OMNeT++/OMNEST: inet::L3NetworkConfiguratorBase::Matcher Class Reference
inet::L3NetworkConfiguratorBase::Matcher Class Reference
#include <L3NetworkConfiguratorBase.h>
Public Member Functions
Matcher (const char *pattern)
~Matcher ()
bool matches (const char *s)
bool matchesAny ()
Protected Attributes
bool matchesany = false
std::vector< inet::PatternMatcher * > matchers
Constructor & Destructor Documentation
Matcher()
inet::L3NetworkConfiguratorBase::Matcher::Matcher (const char * pattern)
 {
     matchesany = opp_isempty(pattern);
     if (matchesany)
         return;
     cStringTokenizer tokenizer(pattern);
     while (tokenizer.hasMoreTokens())
         matchers.push_back(new inet::PatternMatcher(tokenizer.nextToken(), true, true, true));
 }
~Matcher()
inet::L3NetworkConfiguratorBase::Matcher::~Matcher ()
 {
     for (auto& matcher : matchers)
         delete matcher;
 }
Member Function Documentation
matches()
bool inet::L3NetworkConfiguratorBase::Matcher::matches (const char * s)
 {
     if (matchesany)
         return true;
     for (auto& matcher : matchers)
         if (matcher->matches(s))
             return true;
     return false;
 }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::L3NetworkConfiguratorBase::getWirelessId(), inet::Ipv4NetworkConfigurator::linkContainsMatchingHostExcept(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), and inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration().
matchesAny()
bool inet::L3NetworkConfiguratorBase::Matcher::matchesAny () inline
 { return matchesany; }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::L3NetworkConfiguratorBase::getWirelessId(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), and inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration().
Member Data Documentation
matchers
std::vector<inet::PatternMatcher *> inet::L3NetworkConfiguratorBase::Matcher::matchers protected
matchesany
bool inet::L3NetworkConfiguratorBase::Matcher::matchesany = false protected
The documentation for this class was generated from the following files:
L3NetworkConfiguratorBase.h
L3NetworkConfiguratorBase.cc