INET Framework for OMNeT++/OMNEST: inet::EchoProtocol Class Reference
inet::EchoProtocol Class Reference
TODO.
#include <EchoProtocol.h>
Protected Member Functions
virtual void processPacket (Packet *packet)
virtual void processEchoRequest (Packet *packet)
virtual void processEchoReply (Packet *packet)
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *msg) override
Detailed Description
TODO.
Member Function Documentation
handleMessage()
void inet::EchoProtocol::handleMessage (cMessage * msg) override protected virtual
 {
     cGate *arrivalGate = msg->getArrivalGate();
     if (!strcmp(arrivalGate->getName(), "ipIn"))
         processPacket(check_and_cast<Packet *>(msg));
 }
initialize()
void inet::EchoProtocol::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_NETWORK_LAYER) {
         registerProtocol(Protocol::echo, gate("ipOut"), gate("ipIn"));
     }
 }
numInitStages()
virtual int inet::EchoProtocol::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
processEchoReply()
void inet::EchoProtocol::processEchoReply (Packet * packet) protected virtual
 {
     delete reply;
 }
Referenced by processPacket().
processEchoRequest()
void inet::EchoProtocol::processEchoRequest (Packet * packet) protected virtual
 {
     // turn request into a reply
     const auto& echoReq = request->popAtFront<EchoPacket>();
     Packet *reply = new Packet((std::string(request->getName()) + "-reply").c_str());
     const auto& echoReply = makeShared<EchoPacket>();
     echoReply->setChunkLength(echoReq->getChunkLength());
     echoReply->setType(ECHO_PROTOCOL_REPLY);
     echoReply->setIdentifier(echoReq->getIdentifier());
     echoReply->setSeqNumber(echoReq->getSeqNumber());
     reply->insertAtBack(echoReply);
     reply->insertAtBack(request->peekData());
     auto addressInd = request->getTag<L3AddressInd>();
     // swap src and dest
     // TODO check what to do if dest was multicast etc?
     auto addressReq = reply->addTag<L3AddressReq>();
     addressReq->setSrcAddress(addressInd->getDestAddress());
     addressReq->setDestAddress(addressInd->getSrcAddress());
     reply->addTag<DispatchProtocolReq>()->setProtocol(request->getTag<NetworkProtocolInd>()->getProtocol());
     reply->addTag<PacketProtocolTag>()->setProtocol(&Protocol::echo);
     send(reply, "ipOut");
     delete request;
 }
Referenced by processPacket().
processPacket()
void inet::EchoProtocol::processPacket (Packet * packet) protected virtual
 {
     const auto& echoHdr = msg->peekAtFront<EchoPacket>();
     switch (echoHdr->getType()) {
         case ECHO_PROTOCOL_REQUEST:
             processEchoRequest(msg);
             break;
         case ECHO_PROTOCOL_REPLY:
             processEchoReply(msg);
             break;
         default:
             throw cRuntimeError("Unknown type %d", echoHdr->getType());
     }
 }
Referenced by handleMessage().
The documentation for this class was generated from the following files:
EchoProtocol.h
EchoProtocol.cc