INET Framework for OMNeT++/OMNEST: inet::ClnsAddress Class Reference
inet::ClnsAddress Class Reference
#include <ClnsAddress.h>
Public Types
enum AddressCategory { UNSPECIFIED }
Public Member Functions
ClnsAddress ()
ClnsAddress (std::string net)
ClnsAddress (uint64_t areaID, uint64_t systemID, uint8_t nsel=0)
void set (uint64_t areaID, uint64_t systemID, uint8_t nsel=0)
virtual ~ClnsAddress ()
bool isUnspecified () const
std::string str (bool printUnspec=true) const
Returns the string representation of the address (e.g.
bool equals (const ClnsAddress &toCmp) const
Returns true if the two addresses are equal.
uint64_t getAreaId () const
uint64_t getSystemId () const
uint8_t getNsel () const
void setNsel (uint8_t nsel)
bool operator== (const ClnsAddress &addr1) const
Returns equals(addr).
bool operator!= (const ClnsAddress &addr1) const
Returns !equals(addr).
bool operator< (const ClnsAddress &addr1) const
Compares two CLNS addresses.
bool operator<= (const ClnsAddress &addr1) const
bool operator> (const ClnsAddress &addr1) const
bool operator>= (const ClnsAddress &addr1) const
Static Public Attributes
static const ClnsAddress UNSPECIFIED_ADDRESS
Private Attributes
uint64_t systemID
uint64_t areaID
uint8_t nsel
Member Enumeration Documentation
AddressCategory
enum inet::ClnsAddress::AddressCategory
Enumerator
UNSPECIFIED
{
         UNSPECIFIED // 00.0000.0000.0000.0000.00
     };
Constructor & Destructor Documentation
ClnsAddress() [1/3]
inet::ClnsAddress::ClnsAddress ()
 {
     areaID = 0;
     systemID = 0;
     nsel = 0;
 }
ClnsAddress() [2/3]
inet::ClnsAddress::ClnsAddress (std::string net)
 {
     areaID = 0;
     systemID = 0;
     nsel = 0;
     unsigned int dots = 0;
     size_t found;
     // net address (in this module - not according to standard O:-) MUST have the following format:
     // 49.0001.1921.6800.1001.00
     // IDI: 49 (private addressing)
     // AREA: 0001
     // systemID: 1921.6800.1001 from IP 192.168.1.1
     // NSEL: 00
     found = net.find_first_of(".");
     if (found != 2 || net.length() != 25) {
         return;
     }
     while (found != std::string::npos) {
         switch (found) {
             case 2:
                 dots++;
 //                area[0] = (unsigned char) (atoi(net.substr(0, 2).c_str()));
                 areaID += (uint64_t)(strtoul(net.substr(0, 2).c_str(), nullptr, 16)) << 16;
                 break;
             case 7:
                 areaID += (uint64_t)(strtoul(net.substr(3, 4).c_str(), nullptr, 16));
                 dots++;
                 break;
             case 12:
                 dots++;
                 systemID += (uint64_t)(strtoul(net.substr(8, 4).c_str(), nullptr, 16)) << 32;
                 break;
             case 17:
                 dots++;
                 systemID += (uint64_t)(strtoul(net.substr(13, 4).c_str(), nullptr, 16)) << 16;
                 break;
             case 22:
                 dots++;
                 systemID += (uint64_t)(strtoul(net.substr(18, 4).c_str(), nullptr, 16));
                 break;
             default:
                 return;
                 break;
         }
         found = net.find_first_of(".", found + 1);
     }
     if (dots != 5) {
         return;
     }
     nsel = strtoul(net.substr(23, 2).c_str(), nullptr, 16);
     // 49.0001.1921.6801.2003.00
 //    this->nickname = this->sysId[ISIS_SYSTEM_ID - 1] + this->sysId[ISIS_SYSTEM_ID - 2] * 0xFF;
 }
ClnsAddress() [3/3]
inet::ClnsAddress::ClnsAddress (uint64_t areaID, uint64_t systemID, uint8_t nsel = 0)
                                                                          :
     systemID(systemID),
     areaID(areaID),
     nsel(nsel)
 {
 }
~ClnsAddress()
inet::ClnsAddress::~ClnsAddress () virtual
 {
     // TODO Auto-generated destructor stub
 }
Member Function Documentation
equals()
bool inet::ClnsAddress::equals (const ClnsAddress & toCmp) const inline
Returns true if the two addresses are equal.
 { return systemID == toCmp.systemID && areaID == toCmp.areaID; }
Referenced by operator!=(), and operator==().
getAreaId()
uint64_t inet::ClnsAddress::getAreaId () const
 {
     return areaID;
 }
Referenced by operator<(), operator<=(), operator>(), operator>=(), and inet::L3Address::set().
getNsel()
uint8_t inet::ClnsAddress::getNsel () const
 {
     return nsel;
 }
Referenced by inet::L3Address::set().
getSystemId()
uint64_t inet::ClnsAddress::getSystemId () const
 {
     return systemID;
 }
Referenced by operator<(), operator<=(), operator>(), operator>=(), and inet::L3Address::set().
isUnspecified()
bool inet::ClnsAddress::isUnspecified () const
 {
     return systemID == 0 && areaID == 0;
 }
Referenced by str().
operator!=()
bool inet::ClnsAddress::operator!= (const ClnsAddress & addr1) const inline
Returns !equals(addr).
 { return !equals(addr1); }
operator<()
bool inet::ClnsAddress::operator< (const ClnsAddress & addr1) const inline
Compares two CLNS addresses.
 { if (areaID == addr1.getAreaId()) { return systemID < addr1.getSystemId(); } else { return areaID < addr1.getAreaId(); } }
operator<=()
bool inet::ClnsAddress::operator<= (const ClnsAddress & addr1) const inline
 { if (areaID == addr1.getAreaId()) { return systemID <= addr1.getSystemId(); } else { return areaID < addr1.getAreaId(); } }
operator==()
bool inet::ClnsAddress::operator== (const ClnsAddress & addr1) const inline
Returns equals(addr).
 { return equals(addr1); }
operator>()
bool inet::ClnsAddress::operator> (const ClnsAddress & addr1) const inline
 { if (areaID == addr1.getAreaId()) { return systemID > addr1.getSystemId(); } else { return areaID > addr1.getAreaId(); } }
operator>=()
bool inet::ClnsAddress::operator>= (const ClnsAddress & addr1) const inline
 { if (areaID == addr1.getAreaId()) { return systemID >= addr1.getSystemId(); } else { return areaID > addr1.getAreaId(); } }
set()
void inet::ClnsAddress::set (uint64_t areaID, uint64_t systemID, uint8_t nsel = 0)
 {
     this->areaID = areaID;
     this->systemID = systemID;
     this->nsel = nsel;
 }
setNsel()
void inet::ClnsAddress::setNsel (uint8_t nsel)
 {
     this->nsel = nsel;
 }
str()
std::string inet::ClnsAddress::str (bool printUnspec = true) const
Returns the string representation of the address (e.g.
"49.0001.1921.6800.1001.00")
Parameters
printUnspec show 00.0000.0000.0000.0000.00 as "<unspec>" if true
 {
     if (printUnspec && isUnspecified())
         return std::string("<unspec>");
     std::ostringstream buf;
     buf << std::hex << std::setfill('0')
         << std::setw(2) << ((areaID >> 16) & (0xFF)) << "."
         << std::setw(4) << (areaID & 0xFFFF) << "."
         << std::setw(4) << ((systemID >> 32) & 0xFFFF) << "."
         << std::setw(4) << ((systemID >> 16) & 0xFFFF) << "."
         << std::setw(4) << (systemID & 0xFFFF) << "."
         << std::setw(2) << (nsel & 0xFF);
     return buf.str();
 }
Referenced by inet::operator<<(), and inet::L3Address::str().
Member Data Documentation
areaID
uint64_t inet::ClnsAddress::areaID private
Referenced by ClnsAddress(), equals(), getAreaId(), isUnspecified(), operator<(), operator<=(), operator>(), operator>=(), set(), and str().
nsel
uint8_t inet::ClnsAddress::nsel private
Referenced by ClnsAddress(), getNsel(), set(), setNsel(), and str().
systemID
uint64_t inet::ClnsAddress::systemID private
Referenced by ClnsAddress(), equals(), getSystemId(), isUnspecified(), operator<(), operator<=(), operator>(), operator>=(), set(), and str().
UNSPECIFIED_ADDRESS
const ClnsAddress inet::ClnsAddress::UNSPECIFIED_ADDRESS static
Referenced by inet::CLNSAddressType::getBroadcastAddress(), inet::CLNSAddressType::getLinkLocalAddress(), inet::CLNSAddressType::getLinkLocalManetRoutersMulticastAddress(), inet::CLNSAddressType::getLinkLocalRIPRoutersMulticastAddress(), and inet::CLNSAddressType::getUnspecifiedAddress().
The documentation for this class was generated from the following files:
ClnsAddress.h
ClnsAddress.cc