INET Framework for OMNeT++/OMNEST: inet::physicallayer::NarrowbandReceiverBase Class Reference
inet::physicallayer::NarrowbandReceiverBase Class Reference
#include <NarrowbandReceiverBase.h>
Public Member Functions
NarrowbandReceiverBase ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IListening * createListening (const IRadio *radio, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition) const override
Returns a description of how the receiver is listening on the medium.
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const override
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const override
Returns whether the reception of the provided part is possible or not.
virtual const IReceptionDecision * computeReceptionDecision (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
virtual const IModulation * getModulation () const
virtual void setModulation (const IModulation *modulation)
virtual Hz getCenterFrequency () const
virtual void setCenterFrequency (Hz centerFrequency)
virtual Hz getBandwidth () const
virtual void setBandwidth (Hz bandwidth)
Public Member Functions inherited from inet::physicallayer::SnirReceiverBase
virtual double getSNIRThreshold () const
virtual bool computeIsReceptionSuccessful (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns whether the reception of the provided part is actually successful or failed by the receiver.
Public Member Functions inherited from inet::physicallayer::ReceiverBase
ReceiverBase ()
virtual W getMinInterferencePower () const override
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
virtual W getMinReceptionPower () const override
Returns the minimum reception power below which successful reception is definitely not possible.
virtual bool computeIsReceptionAttempted (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference) const override
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
virtual const IReceptionResult * computeReceptionResult (const IListening *listening, const IReception *reception, const IInterference *interference, const ISnir *snir, const std::vector< const IReceptionDecision * > *decisions) const override
Returns the complete result of the reception process for the provided reception.
Public Member Functions inherited from inet::physicallayer::IReceiver
virtual const IListeningDecision * computeListeningDecision (const IListening *listening, const IInterference *interference) const =0
Returns the result of the listening process specifying the reception state of the receiver.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
Protected Member Functions inherited from inet::physicallayer::ReceiverBase
virtual int numInitStages () const override
virtual W computeSignalPower (const IListening *listening, const ISnir *snir, const IInterference *interference) const
virtual Packet * computeReceivedPacket (const ISnir *snir, bool isReceptionSuccessful) const
Protected Attributes
const IModulation * modulation
Hz centerFrequency
Hz bandwidth
Protected Attributes inherited from inet::physicallayer::SnirReceiverBase
double snirThreshold = NaN
SnirThresholdMode snirThresholdMode = SnirThresholdMode::STM_UNDEFINED
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Types inherited from inet::physicallayer::SnirReceiverBase
enum SnirThresholdMode { SnirThresholdMode::STM_UNDEFINED = -1, SnirThresholdMode::STM_MIN, SnirThresholdMode::STM_MEAN }
Constructor & Destructor Documentation
NarrowbandReceiverBase()
inet::physicallayer::NarrowbandReceiverBase::NarrowbandReceiverBase ()
                                                :
     SnirReceiverBase(),
     modulation(nullptr),
     centerFrequency(Hz(NaN)),
     bandwidth(Hz(NaN))
 {
 }
Member Function Documentation
computeIsReceptionPossible() [1/2]
bool inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part) const override virtual
Returns whether the reception of the provided part is possible or not.
For example, it might check if the reception power is above sensitivity.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::ReceiverBase.
Reimplemented in inet::physicallayer::FlatReceiverBase, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
 {
     const BandListening *bandListening = check_and_cast<const BandListening *>(listening);
     const NarrowbandReceptionBase *narrowbandReception = check_and_cast<const NarrowbandReceptionBase *>(reception);
     if (bandListening->getCenterFrequency() != narrowbandReception->getCenterFrequency() || bandListening->getBandwidth() < narrowbandReception->getBandwidth()) {
         EV_DEBUG << "Computing whether reception is possible: listening and reception bands are different -> reception is impossible" << endl;
         return false;
     }
     else
         return true;
 }
computeIsReceptionPossible() [2/2]
bool inet::physicallayer::NarrowbandReceiverBase::computeIsReceptionPossible (const IListening * listening, const ITransmission * transmission) const override virtual
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
For example, it might check if the carrier frequency and the modulation of the transmission matches how the receiver is listening on the medium.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::ReceiverBase.
Reimplemented in inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
 {
     // TODO check if modulation matches?
     const NarrowbandTransmissionBase *narrowbandTransmission = check_and_cast<const NarrowbandTransmissionBase *>(transmission);
     return centerFrequency == narrowbandTransmission->getCenterFrequency() && bandwidth >= narrowbandTransmission->getBandwidth();
 }
Referenced by inet::physicallayer::ApskDimensionalReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211ScalarReceiver::computeIsReceptionPossible(), inet::physicallayer::ApskScalarReceiver::computeIsReceptionPossible(), and inet::physicallayer::FlatReceiverBase::computeIsReceptionPossible().
computeReceptionDecision()
const IReceptionDecision * inet::physicallayer::NarrowbandReceiverBase::computeReceptionDecision (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const override virtual
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::ReceiverBase.
 {
     const BandListening *bandListening = check_and_cast<const BandListening *>(listening);
     const NarrowbandReceptionBase *narrowbandReception = check_and_cast<const NarrowbandReceptionBase *>(reception);
     if (bandListening->getCenterFrequency() == narrowbandReception->getCenterFrequency() && bandListening->getBandwidth() >= narrowbandReception->getBandwidth())
         return SnirReceiverBase::computeReceptionDecision(listening, reception, part, interference, snir);
     else
         return new ReceptionDecision(reception, part, false, false, false);
 }
createListening()
const IListening * inet::physicallayer::NarrowbandReceiverBase::createListening (const IRadio * radio, const simtime_t startTime, const simtime_t endTime, const Coord & startPosition, const Coord & endPosition) const override virtual
Returns a description of how the receiver is listening on the medium.
Implements inet::physicallayer::IReceiver.
 {
     return new BandListening(radio, startTime, endTime, startPosition, endPosition, centerFrequency, bandwidth);
 }
getBandwidth()
virtual Hz inet::physicallayer::NarrowbandReceiverBase::getBandwidth () const inline virtual
 { return bandwidth; }
getCenterFrequency()
virtual Hz inet::physicallayer::NarrowbandReceiverBase::getCenterFrequency () const inline virtual
 { return centerFrequency; }
getModulation()
virtual const IModulation* inet::physicallayer::NarrowbandReceiverBase::getModulation () const inline virtual
 { return modulation; }
initialize()
void inet::physicallayer::NarrowbandReceiverBase::initialize (int stage) override protected virtual
Reimplemented from inet::physicallayer::SnirReceiverBase.
Reimplemented in inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 {
     SnirReceiverBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         modulation = ApskModulationBase::findModulation(par("modulation"));
         centerFrequency = Hz(par("centerFrequency"));
         bandwidth = Hz(par("bandwidth"));
     }
 }
Referenced by inet::physicallayer::FlatReceiverBase::initialize().
printToStream()
std::ostream & inet::physicallayer::NarrowbandReceiverBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::SnirReceiverBase.
Reimplemented in inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, inet::physicallayer::Ieee80211ScalarReceiver, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(modulation, printFieldToString(modulation, level + 1, evFlags))
                << EV_FIELD(centerFrequency)
                << EV_FIELD(bandwidth);
     return SnirReceiverBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::FlatReceiverBase::printToStream().
setBandwidth()
virtual void inet::physicallayer::NarrowbandReceiverBase::setBandwidth (Hz bandwidth) inline virtual
 { this->bandwidth = bandwidth; }
Referenced by inet::physicallayer::NarrowbandRadioBase::setBandwidth().
setCenterFrequency()
virtual void inet::physicallayer::NarrowbandReceiverBase::setCenterFrequency (Hz centerFrequency) inline virtual
 { this->centerFrequency = centerFrequency; }
Referenced by inet::physicallayer::NarrowbandRadioBase::setCenterFrequency(), and inet::physicallayer::Ieee80211ReceiverBase::setChannel().
setModulation()
virtual void inet::physicallayer::NarrowbandReceiverBase::setModulation (const IModulation * modulation) inline virtual
 { this->modulation = modulation; }
Referenced by inet::physicallayer::NarrowbandRadioBase::setModulation().
Member Data Documentation
bandwidth
Hz inet::physicallayer::NarrowbandReceiverBase::bandwidth protected
Referenced by computeIsReceptionPossible(), createListening(), initialize(), and printToStream().
centerFrequency
Hz inet::physicallayer::NarrowbandReceiverBase::centerFrequency protected
Referenced by computeIsReceptionPossible(), createListening(), initialize(), and printToStream().
modulation
const IModulation* inet::physicallayer::NarrowbandReceiverBase::modulation protected
Referenced by initialize(), and printToStream().
The documentation for this class was generated from the following files:
NarrowbandReceiverBase.h
NarrowbandReceiverBase.cc