INET Framework for OMNeT++/OMNEST: inet::queueing::PacketProcessorBase Class Reference
inet::queueing::PacketProcessorBase Class Reference
#include <PacketProcessorBase.h>
Public Member Functions
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
virtual bool supportsPacketPushing (cGate *gate) const =0
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const =0
Returns true if the processor supports pulling packets at the given gate.
Protected Types
enum Action { PUSH, PULL }
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Member Enumeration Documentation
Action
enum inet::queueing::PacketProcessorBase::Action protected
Enumerator
PUSH
PULL
                 {
         PUSH,
         PULL,
     };
Member Function Documentation
animate()
void inet::queueing::PacketProcessorBase::animate (Packet * packet, cGate * gate, const SendOptions & sendOptions, Action action) const protected virtual
 {
     packet->setIsUpdate(sendOptions.isUpdate);
     packet->setTransmissionId(sendOptions.transmissionId_);
     if (sendOptions.isUpdate && sendOptions.transmissionId_ == -1)
         throw cRuntimeError("No transmissionId specified in SendOptions for a transmission update");
     packet->setDuration(SIMTIME_ZERO);
     packet->setRemainingDuration(SIMTIME_ZERO);
     auto endGate = gate->getPathEndGate();
     packet->setArrival(endGate->getOwnerModule()->getId(), endGate->getId(), simTime());
     packet->setSentFrom(gate->getOwnerModule(), gate->getId(), simTime());
 #ifdef INET_WITH_SELFDOC
     if (SelfDoc::generateSelfdoc) {
         auto from = gate->getOwnerModule();
         auto to = endGate->getOwnerModule();
         auto ctrl = packet->getControlInfo();
         {
             std::ostringstream os;
             os << "=SelfDoc={ " << SelfDoc::keyVal("module", from->getComponentType()->getFullName())
                     << ", " << SelfDoc::keyVal("action", action == PUSH ? "PUSH_OUT" : "PULLED_OUT")
                     << ", " << SelfDoc::val("details") << " : {"
                     << SelfDoc::keyVal("gate", SelfDoc::gateInfo(gate))
                     << ", "<< SelfDoc::keyVal("msg", opp_typename(typeid(*packet)))
                     << ", " << SelfDoc::keyVal("kind", SelfDoc::kindToStr(packet->getKind(), gate->getProperties(), "messageKinds", endGate->getProperties(), "messageKinds"))
                     << ", " << SelfDoc::keyVal("ctrl", ctrl ? opp_typename(typeid(*ctrl)) : "")
                     << ", " << SelfDoc::tagsToJson("tags", packet)
                     << " } }"
                     ;
             globalSelfDoc.insert(os.str());
         }
         {
             std::ostringstream os;
             os << "=SelfDoc={ " << SelfDoc::keyVal("module", to->getComponentType()->getFullName())
                     << ", " << SelfDoc::keyVal("action", action == PUSH ? "PUSHED_IN" : "PULL_IN")
                     << ", " << SelfDoc::val("details") << " : {"
                     << SelfDoc::keyVal("gate", SelfDoc::gateInfo(endGate))
                     << ", " << SelfDoc::keyVal("msg", opp_typename(typeid(*packet)))
                     << ", " << SelfDoc::keyVal("kind", SelfDoc::kindToStr(packet->getKind(), endGate->getProperties(), "messageKinds", gate->getProperties(), "messageKinds"))
                     << ", " << SelfDoc::keyVal("ctrl", ctrl ? opp_typename(typeid(*ctrl)) : "")
                     << ", " << SelfDoc::tagsToJson("tags", packet)
                     << " } }"
                     ;
             globalSelfDoc.insert(os.str());
         }
     }
 #endif // INET_WITH_SELFDOC
     auto envir = getEnvir();
     if (gate->getNextGate() != nullptr) {
         envir->beginSend(packet, sendOptions);
         while (gate->getNextGate() != nullptr) {
             ChannelResult result;
             result.duration = sendOptions.duration_;
             result.remainingDuration = sendOptions.remainingDuration;
             envir->messageSendHop(packet, gate, result);
             gate = gate->getNextGate();
         }
         envir->endSend(packet);
     }
     envir->pausePoint();
 }
Referenced by animatePacket(), animatePacketEnd(), animatePacketProgress(), animatePacketStart(), animatePull(), and animatePush().
animatePacket()
void inet::queueing::PacketProcessorBase::animatePacket (Packet * packet, cGate * gate, Action action) const protected virtual
 {
     SendOptions sendOptions;
     sendOptions.duration_ = 0;
     sendOptions.remainingDuration = 0;
     animate(packet, gate, sendOptions, action);
 }
Referenced by animatePullPacket(), and animatePushPacket().
animatePacketEnd() [1/2]
void inet::queueing::PacketProcessorBase::animatePacketEnd (Packet * packet, cGate * gate, const SendOptions & sendOptions, Action action) const protected virtual
 {
     animate(packet, gate, sendOptions, action);
 }
animatePacketEnd() [2/2]
void inet::queueing::PacketProcessorBase::animatePacketEnd (Packet * packet, cGate * gate, long transmissionId, Action action) const protected virtual
 {
     SendOptions sendOptions;
     sendOptions.updateTx(transmissionId, 0);
     animatePacketEnd(packet, gate, sendOptions, action);
 }
Referenced by animatePullPacketEnd(), and animatePushPacketEnd().
animatePacketProgress() [1/2]
void inet::queueing::PacketProcessorBase::animatePacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength, const SendOptions & sendOptions, Action action) const protected virtual
 {
     animate(packet, gate, sendOptions, action);
 }
animatePacketProgress() [2/2]
void inet::queueing::PacketProcessorBase::animatePacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const protected virtual
 {
     SendOptions sendOptions;
     sendOptions.transmissionId(transmissionId);
     animatePacketProgress(packet, gate, datarate, position, extraProcessableLength, sendOptions, action);
 }
Referenced by animatePullPacketProgress(), and animatePushPacketProgress().
animatePacketStart() [1/2]
void inet::queueing::PacketProcessorBase::animatePacketStart (Packet * packet, cGate * gate, bps datarate, const SendOptions & sendOptions, Action action) const protected virtual
 {
     animate(packet, gate, sendOptions, action);
 }
animatePacketStart() [2/2]
void inet::queueing::PacketProcessorBase::animatePacketStart (Packet * packet, cGate * gate, bps datarate, long transmissionId, Action action) const protected virtual
 {
     simtime_t duration = s(packet->getDataLength() / datarate).get();
     SendOptions sendOptions;
     sendOptions.duration_ = duration;
     sendOptions.remainingDuration = duration;
     sendOptions.transmissionId(transmissionId);
     animatePacketStart(packet, gate, datarate, sendOptions, action);
 }
Referenced by animatePullPacketStart(), and animatePushPacketStart().
animatePull()
void inet::queueing::PacketProcessorBase::animatePull (Packet * packet, cGate * gate, const SendOptions & sendOptions) const protected virtual
 {
     animate(packet, gate, sendOptions, PULL);
 }
animatePullPacket()
void inet::queueing::PacketProcessorBase::animatePullPacket (Packet * packet, cGate * gate) const protected virtual
 {
     animatePacket(packet, gate, PULL);
 }
Referenced by inet::queueing::PacketDemultiplexer::pullPacket(), inet::queueing::PassivePacketSource::pullPacket(), inet::queueing::MarkovClassifier::pullPacket(), inet::PacketDestreamer::pullPacket(), inet::queueing::PacketFlowBase::pullPacket(), inet::queueing::PacketQueue::pullPacket(), inet::queueing::PacketSchedulerBase::pullPacket(), and inet::queueing::PacketFilterBase::pullPacket().
animatePullPacketEnd() [1/2]
void inet::queueing::PacketProcessorBase::animatePullPacketEnd (Packet * packet, cGate * gate, const SendOptions & sendOptions) const protected virtual
 {
     animatePacketEnd(packet, gate, sendOptions, PULL);
 }
animatePullPacketEnd() [2/2]
void inet::queueing::PacketProcessorBase::animatePullPacketEnd (Packet * packet, cGate * gate, long transmissionId) const protected virtual
 {
     animatePacketEnd(packet, gate, transmissionId, PULL);
 }
Referenced by inet::queueing::PacketFlowBase::pullPacketEnd(), inet::PacketStreamer::pullPacketEnd(), inet::queueing::PacketSchedulerBase::pullPacketEnd(), and inet::PreemptableStreamer::pullPacketEnd().
animatePullPacketProgress() [1/2]
void inet::queueing::PacketProcessorBase::animatePullPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength, const SendOptions & sendOptions) const protected virtual
 {
     animatePacketProgress(packet, gate, datarate, position, extraProcessableLength, sendOptions, PULL);
 }
animatePullPacketProgress() [2/2]
void inet::queueing::PacketProcessorBase::animatePullPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const protected virtual
 {
     animatePacketProgress(packet, gate, datarate, position, extraProcessableLength, transmissionId, PULL);
 }
Referenced by inet::queueing::PacketFlowBase::pullPacketProgress(), inet::PacketStreamer::pullPacketProgress(), inet::queueing::PacketSchedulerBase::pullPacketProgress(), and inet::PreemptableStreamer::pullPacketProgress().
animatePullPacketStart() [1/2]
void inet::queueing::PacketProcessorBase::animatePullPacketStart (Packet * packet, cGate * gate, bps datarate, const SendOptions & sendOptions) const protected virtual
 {
     animatePacketStart(packet, gate, datarate, sendOptions, PULL);
 }
animatePullPacketStart() [2/2]
void inet::queueing::PacketProcessorBase::animatePullPacketStart (Packet * packet, cGate * gate, bps datarate, long transmissionId) const protected virtual
 {
     animatePacketStart(packet, gate, datarate, transmissionId, PULL);
 }
Referenced by inet::queueing::PacketFlowBase::pullPacketStart(), inet::PacketStreamer::pullPacketStart(), inet::queueing::PacketSchedulerBase::pullPacketStart(), and inet::PreemptableStreamer::pullPacketStart().
animatePush()
void inet::queueing::PacketProcessorBase::animatePush (Packet * packet, cGate * gate, const SendOptions & sendOptions) const protected virtual
 {
     animate(packet, gate, sendOptions, PUSH);
 }
animatePushPacket()
void inet::queueing::PacketProcessorBase::animatePushPacket (Packet * packet, cGate * gate) const protected virtual
 {
     animatePacket(packet, gate, PUSH);
 }
Referenced by pushOrSendPacket().
animatePushPacketEnd() [1/2]
void inet::queueing::PacketProcessorBase::animatePushPacketEnd (Packet * packet, cGate * gate, const SendOptions & sendOptions) const protected virtual
 {
     animatePacketEnd(packet, gate, sendOptions, PUSH);
 }
animatePushPacketEnd() [2/2]
void inet::queueing::PacketProcessorBase::animatePushPacketEnd (Packet * packet, cGate * gate, long transmissionId) const protected virtual
 {
     animatePacketEnd(packet, gate, transmissionId, PUSH);
 }
Referenced by pushOrSendPacketEnd(), and pushOrSendPacketProgress().
animatePushPacketProgress() [1/2]
void inet::queueing::PacketProcessorBase::animatePushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength, const SendOptions & sendOptions) const protected virtual
 {
     animatePacketProgress(packet, gate, datarate, position, extraProcessableLength, sendOptions, PUSH);
 }
animatePushPacketProgress() [2/2]
void inet::queueing::PacketProcessorBase::animatePushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const protected virtual
 {
     animatePacketProgress(packet, gate, datarate, position, extraProcessableLength, transmissionId, PUSH);
 }
Referenced by pushOrSendPacketProgress().
animatePushPacketStart() [1/2]
void inet::queueing::PacketProcessorBase::animatePushPacketStart (Packet * packet, cGate * gate, bps datarate, const SendOptions & sendOptions) const protected virtual
 {
     animatePacketStart(packet, gate, datarate, sendOptions, PUSH);
 }
animatePushPacketStart() [2/2]
void inet::queueing::PacketProcessorBase::animatePushPacketStart (Packet * packet, cGate * gate, bps datarate, long transmissionId) const protected virtual
 {
     animatePacketStart(packet, gate, datarate, transmissionId, PUSH);
 }
Referenced by pushOrSendPacketProgress(), and pushOrSendPacketStart().
checkPacketOperationSupport() [1/2]
void inet::queueing::PacketProcessorBase::checkPacketOperationSupport (cGate * gate) const protected virtual
 {
     auto startGate = findConnectedGate<IPacketProcessor>(gate, -1);
     auto endGate = findConnectedGate<IPacketProcessor>(gate, 1);
     if (gate->getPreviousGate() != nullptr)
         checkPacketOperationSupport(startGate, gate);
     if (gate->getNextGate() != nullptr)
         checkPacketOperationSupport(gate, endGate);
 }
Referenced by inet::queueing::ActivePacketSinkBase::initialize(), inet::queueing::ActivePacketSourceBase::initialize(), inet::queueing::EmptyPacketSource::initialize(), inet::queueing::PacketSendToPush::initialize(), inet::queueing::PassivePacketSinkBase::initialize(), inet::queueing::PassivePacketSourceBase::initialize(), inet::queueing::PcapFilePacketConsumer::initialize(), inet::queueing::PassivePacketSink::initialize(), inet::queueing::PacketDuplicatorBase::initialize(), inet::PacketMeterBase::initialize(), inet::queueing::PacketDemultiplexer::initialize(), inet::queueing::PacketServerBase::initialize(), inet::queueing::PacketPusherBase::initialize(), inet::queueing::PacketPullerBase::initialize(), inet::queueing::MarkovScheduler::initialize(), inet::queueing::CompoundPacketQueueBase::initialize(), inet::queueing::MarkovClassifier::initialize(), inet::queueing::PacketFlowBase::initialize(), inet::queueing::PacketMultiplexer::initialize(), inet::PacketDestreamer::initialize(), inet::queueing::PacketSchedulerBase::initialize(), inet::queueing::PacketClassifierBase::initialize(), inet::PacketReceiverBase::initialize(), inet::queueing::PacketQueue::initialize(), inet::queueing::PacketFilterBase::initialize(), inet::PacketStreamer::initialize(), inet::PreemptableStreamer::initialize(), and inet::PacketTransmitterBase::initialize().
checkPacketOperationSupport() [2/2]
void inet::queueing::PacketProcessorBase::checkPacketOperationSupport (cGate * startGate, cGate * endGate) const protected virtual
 {
     auto startElement = startGate == nullptr ? nullptr : check_and_cast<IPacketProcessor *>(startGate->getOwnerModule());
     auto endElement = endGate == nullptr ? nullptr : check_and_cast<IPacketProcessor *>(endGate->getOwnerModule());
     if (startElement != nullptr && endElement != nullptr) {
         bool startSending = startElement->supportsPacketSending(startGate);
         bool startPushing = startElement->supportsPacketPushing(startGate);
         bool startPulling = startElement->supportsPacketPulling(startGate);
         bool startPassing = startElement->supportsPacketPassing(startGate);
         bool startStreaming = startElement->supportsPacketStreaming(startGate);
         bool startOnlySending = startSending && !startPushing && !startPulling;
         bool endSending = endElement->supportsPacketSending(endGate);
         bool endPushing = endElement->supportsPacketPushing(endGate);
         bool endPulling = endElement->supportsPacketPulling(endGate);
         bool endPassing = endElement->supportsPacketPassing(endGate);
         bool endStreaming = endElement->supportsPacketStreaming(endGate);
         bool endOnlySending = endSending && !endPushing && !endPulling;
         bool bothPushing = startPushing && endPushing;
         bool bothPulling = startPulling && endPulling;
         bool bothPassing = startPassing && endPassing;
         bool bothStreaming = startStreaming && endStreaming;
         bool eitherPushing = startPushing || endPushing;
         bool eitherPulling = startPulling || endPulling;
         bool eitherPassing = startPassing || endPassing;
         bool eitherStreaming = startStreaming || endStreaming;
         if (startOnlySending || endOnlySending) {
             if (!startSending)
                 throw cRuntimeError(startGate->getOwnerModule(), "doesn't support packet sending on gate %s", startGate->getFullPath().c_str());
             if (!endSending)
                 throw cRuntimeError(endGate->getOwnerModule(), "doesn't support packet sending on gate %s", endGate->getFullPath().c_str());
         }
         else if (!bothPushing && !bothPulling) {
             if (eitherPushing) {
                 if (startPushing)
                     throw cRuntimeError(endGate->getOwnerModule(), "doesn't support packet pushing on gate %s", endGate->getFullPath().c_str());
                 if (endPushing)
                     throw cRuntimeError(startGate->getOwnerModule(), "doesn't support packet pushing on gate %s", startGate->getFullPath().c_str());
             }
             else if (eitherPulling) {
                 if (startPulling)
                     throw cRuntimeError(endGate->getOwnerModule(), "doesn't support packet pulling on gate %s", endGate->getFullPath().c_str());
                 if (endPulling)
                     throw cRuntimeError(startGate->getOwnerModule(), "doesn't support packet pulling on gate %s", startGate->getFullPath().c_str());
             }
             else
                 throw cRuntimeError(endGate->getOwnerModule(), "neither supports packet pushing nor packet pulling on gates %s - %s", startGate->getFullPath().c_str(), endGate->getFullPath().c_str());
         }
         if (!bothPassing && !bothStreaming) {
             if (eitherPassing) {
                 if (startPassing)
                     throw cRuntimeError(endGate->getOwnerModule(), "doesn't support packet passing on gate %s", endGate->getFullPath().c_str());
                 if (endPassing)
                     throw cRuntimeError(startGate->getOwnerModule(), "doesn't support packet passing on gate %s", startGate->getFullPath().c_str());
             }
             else if (eitherStreaming) {
                 if (startStreaming)
                     throw cRuntimeError(endGate->getOwnerModule(), "doesn't support packet streaming on gate %s", endGate->getFullPath().c_str());
                 if (endStreaming)
                     throw cRuntimeError(startGate->getOwnerModule(), "doesn't support packet streaming on gate %s", startGate->getFullPath().c_str());
             }
             else
                 throw cRuntimeError(endGate->getOwnerModule(), "neither supports packet passing nor packet streaming on gates %s - %s", startGate->getFullPath().c_str(), endGate->getFullPath().c_str());
         }
     }
     else if (startElement != nullptr && endElement == nullptr) {
         if (!startElement->supportsPacketSending(startGate))
             throw cRuntimeError(startGate->getOwnerModule(), "doesn't support packet sending on gate %s", startGate->getFullPath().c_str());
     }
     else if (startElement == nullptr && endElement != nullptr) {
         if (!endElement->supportsPacketSending(endGate))
             throw cRuntimeError(endGate->getOwnerModule(), "doesn't support packet sending on gate %s", endGate->getFullPath().c_str());
     }
     else
         throw cRuntimeError("Cannot check packet operation support on gates %s - %s", startGate->getFullPath().c_str(), endGate->getFullPath().c_str());
 }
dropPacket()
void inet::queueing::PacketProcessorBase::dropPacket (Packet * packet, PacketDropReason reason, int limit = -1) protected virtual
Reimplemented in inet::queueing::PacketFilterBase.
 {
     PacketDropDetails details;
     details.setReason(reason);
     details.setLimit(limit);
     emit(packetDroppedSignal, packet, &details);
     delete packet;
 }
Referenced by inet::queueing::PacketBuffer::addPacket(), inet::queueing::ActivePacketSink::collectPacket(), inet::queueing::PassivePacketSink::consumePacket(), inet::queueing::PacketFilterBase::dropPacket(), inet::queueing::CompoundPacketQueueBase::pushPacket(), inet::queueing::PacketQueue::pushPacket(), inet::NetworkInterface::pushPacket(), inet::NetworkInterface::pushPacketEnd(), and inet::NetworkInterface::pushPacketStart().
handlePacketProcessed()
void inet::queueing::PacketProcessorBase::handlePacketProcessed (Packet * packet) protected virtual
Reimplemented in inet::EthernetFragmentFcsInserter, and inet::physicallayer::EthernetFragmentPhyHeaderInserter.
 {
     numProcessedPackets++;
     processedTotalLength += packet->getDataLength();
 }
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::queueing::PacketFlowBase::endPacketStreaming(), inet::queueing::PacketMultiplexer::endPacketStreaming(), inet::queueing::PacketFilterBase::endPacketStreaming(), inet::queueing::PacketSchedulerBase::endPacketStreaming(), inet::queueing::PacketClassifierBase::endPacketStreaming(), inet::StreamingTransmitter::endTx(), inet::PacketTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), inet::queueing::PacketSendToPush::handleMessage(), inet::InterpacketGapInserter::handleMessage(), inet::EthernetFragmentFcsInserter::handlePacketProcessed(), inet::StreamIdentifier::processPacket(), inet::StreamDecoder::processPacket(), inet::PacketDestreamer::pullPacket(), inet::queueing::PacketFlowBase::pullPacket(), inet::queueing::PacketSchedulerBase::pullPacket(), inet::queueing::PacketFilterBase::pullPacket(), inet::PacketStreamer::pullPacketEnd(), inet::PreemptableStreamer::pullPacketEnd(), inet::InterpacketGapInserter::pushOrSendOrSchedulePacketProgress(), inet::queueing::PacketPushToSend::pushPacket(), inet::queueing::PacketDuplicator::pushPacket(), inet::StreamSplitter::pushPacket(), inet::queueing::PacketDelayer::pushPacket(), inet::EthernetSocketPacketProcessor::pushPacket(), inet::Ieee8021qSocketPacketProcessor::pushPacket(), inet::queueing::PacketCloner::pushPacket(), inet::InterpacketGapInserter::pushPacket(), inet::queueing::PacketMultiplexer::pushPacket(), inet::queueing::PacketFlowBase::pushPacket(), inet::queueing::PacketClassifierBase::pushPacket(), inet::queueing::PacketFilterBase::pushPacket(), inet::StreamThroughReceiver::receivePacketEnd(), inet::DestreamingReceiver::receivePacketEnd(), inet::PacketReceiver::receiveSignal(), and inet::queueing::PreemptingServer::startStreaming().
initialize()
void inet::queueing::PacketProcessorBase::initialize (int stage) override protected virtual
Reimplemented in inet::NetworkInterface, inet::MultiFieldClassifier, inet::BehaviorAggregateClassifier, inet::DscpMarker, inet::VirtualTunnel, inet::TwoRateThreeColorMeter, inet::queueing::RedDropper, inet::SingleRateThreeColorMeter, inet::PacketTransmitterBase, inet::PreemptableStreamer, inet::OperationalMixin< PacketProcessorBase >, inet::StreamDecoder, inet::queueing::CreditBasedGate, inet::queueing::FlowMeasurementRecorder, inet::PacketStreamer, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::TokenBucketMeter, inet::PacketReceiverBase, inet::queueing::PacketFilterBase, inet::queueing::PacketQueue, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::PacketDestreamer, inet::EthernetCutthroughSource, inet::queueing::PacketFlowBase, inet::queueing::PacketGateBase, inet::queueing::PacketMultiplexer, inet::queueing::FlowMeasurementStarter, inet::queueing::MarkovClassifier, inet::queueing::CompoundPacketQueueBase, inet::RelayInterfaceSelector, inet::InterpacketGapInserter, inet::StreamEncoder, inet::EligibilityTimeMeter, inet::queueing::MarkovScheduler, inet::EligibilityTimeGate, inet::queueing::OrdinalBasedDuplicator, inet::queueing::OrdinalBasedDropper, inet::queueing::PacketBasedTokenGenerator, inet::PacketEmitter, inet::StreamThroughTransmitter, inet::queueing::PacketQueueBase, inet::queueing::PacketTaggerBase, inet::queueing::PacketBuffer, inet::queueing::PacketPullerBase, inet::queueing::PacketPusherBase, inet::queueing::TokenGeneratorBase, inet::queueing::WrrClassifier, inet::queueing::PeriodicGate, inet::queueing::WrrScheduler, inet::queueing::PreemptingServer, inet::RelayInterfaceLearner, inet::Ieee8021qTagEpdHeaderInserter, inet::Ieee8021qTagTpidHeaderInserter, inet::AggregatorBase, inet::queueing::PacketServerBase, inet::queueing::PacketSourceBase, inet::queueing::PacketCloner, inet::queueing::PacketDemultiplexer, inet::queueing::SlidingWindowRateMeter, inet::queueing::TokenBasedServer, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::TokenBucketMixin< PacketClassifierBase >, inet::ExtInterface, inet::VlanIndFilter, inet::VlanReqFilter, inet::VlanReqMapper, inet::PacketMeterBase, inet::Resending, inet::StreamIdentifier, inet::StreamMerger, inet::queueing::PacketDuplicatorBase, inet::queueing::ExponentialRateMeter, inet::queueing::PassivePacketSource, inet::queueing::QueueBasedTokenGenerator, inet::queueing::TokenBucketMeterMixin< MultiTokenBucketMixin< PacketMeterBase > >, inet::queueing::TokenBucketMeterMixin< TokenBucketMixin< PacketMeterBase > >, inet::EthernetAddressChecker, inet::EthernetCutthroughInterface, inet::EthernetCutthroughSink, inet::EthernetMacHeaderChecker, inet::Ieee8021qTagEpdHeaderChecker, inet::SendWithAcknowledge, inet::PaddingInserter, inet::DefragmenterBase, inet::queueing::DynamicClassifier, inet::queueing::PacketGate, inet::queueing::PassivePacketSink, inet::queueing::PcapFilePacketConsumer, inet::queueing::TimeBasedTokenGenerator, inet::EthernetAddressInserter, inet::EthernetMacHeaderInserter, inet::EthernetSocketCommandProcessor, inet::Ieee8021qSocketCommandProcessor, inet::Ieee8022LlcSocketCommandProcessor, inet::FragmenterBase, inet::EligibilityTimeFilter, inet::queueing::PacketBufferBase, inet::queueing::PassivePacketSinkBase, inet::queueing::PassivePacketSourceBase, inet::queueing::LabelScheduler, inet::queueing::ActivePacketSink, inet::queueing::ActivePacketSource, inet::EthernetSocketPacketProcessor, inet::Ieee8021qSocketPacketProcessor, inet::Ieee8021qTagTpidHeaderChecker, inet::Ieee8021rTagEpdHeaderChecker, inet::Ieee8021rTagEpdHeaderInserter, inet::Ieee8022LlcSocketPacketProcessor, inet::CrcInserterBase, inet::FcsInserterBase, inet::CrcHeaderChecker, inet::CrcHeaderInserter, inet::FcsHeaderChecker, inet::FcsHeaderInserter, inet::ProtocolChecker, inet::Forwarding, inet::FragmentNumberHeaderBasedDefragmenter, inet::FragmentNumberHeaderBasedFragmenter, inet::FragmentNumberHeaderChecker, inet::FragmentNumberHeaderInserter, inet::Reordering, inet::StreamClassifier, inet::StreamFilter, inet::StreamSplitter, inet::ReceiveAtL3Address, inet::SendToL3Address, inet::SendToMacAddress, inet::queueing::ActivePacketSinkBase, inet::queueing::ActivePacketSourceBase, inet::queueing::ContentBasedClassifier, inet::queueing::PacketSendToPush, inet::queueing::LabelFilter, inet::queueing::StatisticalRateLimiter, inet::queueing::MultiTokenBucketMeter, inet::queueing::TokenBucketMeter, inet::queueing::ContentBasedScheduler, inet::queueing::PacketServer, inet::queueing::EmptyPacketSource, inet::queueing::TokenBucketClassifierMixin< TokenBucketMixin< PacketClassifierBase > >, inet::queueing::TokenBucketClassifierMixin< MultiTokenBucketMixin< PacketClassifierBase > >, inet::PcpClassifier, inet::PcpTrafficClassClassifier, inet::Ieee8022SnapChecker, inet::Ieee8022SnapInserter, inet::DeaggregatorBase, inet::SendWithHopLimit, inet::DuplicateRemoval, inet::ReceiveAtMacAddress, inet::ReceiveAtPort, inet::SendToPort, inet::queueing::PacketLabelerBase, inet::queueing::LabelClassifier, inet::queueing::PacketClassifier, inet::queueing::ContentBasedFilter, inet::queueing::PacketFilter, inet::queueing::ContentBasedLabeler, inet::queueing::ContentBasedTagger, inet::queueing::PacketLabeler, inet::queueing::PacketTagger, inet::queueing::PacketScheduler, inet::queueing::PriorityScheduler, inet::queueing::PcapFilePacketProducer, inet::Ieee8022LlcChecker, inet::Ieee8022LlcInserter, inet::queueing::SignalBasedTokenGenerator, inet::StreamingReceiverBase, inet::StreamingTransmitterBase, inet::queueing::MultiTokenBucketClassifier, inet::queueing::TokenBucketClassifier, inet::PacketDirectionReverser, inet::EthernetTypeOrLengthInserter, inet::Ieee8021aeTagEpdHeaderInserter, inet::ReceiveWithAcknowledge, inet::SubpacketLengthHeaderBasedDeaggregator, inet::ReceiveWithHopLimit, inet::queueing::InteractiveGate, inet::DestreamingReceiver, and inet::StreamThroughReceiver.
 {
     if (stage == INITSTAGE_LOCAL) {
         displayStringTextFormat = par("displayStringTextFormat");
         numProcessedPackets = 0;
         processedTotalLength = b(0);
         WATCH(numProcessedPackets);
         WATCH(processedTotalLength);
     }
     else if (stage == INITSTAGE_LAST)
         updateDisplayString();
 }
Referenced by inet::queueing::ActivePacketSinkBase::initialize(), inet::queueing::PacketSendToPush::initialize(), inet::queueing::EmptyPacketSource::initialize(), inet::queueing::PacketBufferBase::initialize(), inet::queueing::PassivePacketSinkBase::initialize(), inet::queueing::PacketDuplicatorBase::initialize(), inet::queueing::PacketDemultiplexer::initialize(), inet::queueing::PacketServerBase::initialize(), inet::queueing::PacketSourceBase::initialize(), inet::queueing::PacketCloner::initialize(), inet::queueing::TokenGeneratorBase::initialize(), inet::queueing::PacketPusherBase::initialize(), inet::queueing::PacketPullerBase::initialize(), inet::queueing::PacketQueueBase::initialize(), inet::queueing::PacketFlowBase::initialize(), inet::queueing::PacketMultiplexer::initialize(), inet::PacketDestreamer::initialize(), inet::queueing::PacketSchedulerBase::initialize(), inet::queueing::PacketClassifierBase::initialize(), inet::PacketReceiverBase::initialize(), inet::queueing::PacketFilterBase::initialize(), inet::DscpMarker::initialize(), and inet::MessageDispatcher::initialize().
numInitStages()
virtual int inet::queueing::PacketProcessorBase::numInitStages () const inline override protected virtual
Reimplemented in inet::NetworkInterface, inet::MultiFieldClassifier, inet::VirtualTunnel, inet::TwoRateThreeColorMeter, inet::SingleRateThreeColorMeter, inet::TokenBucketMeter, inet::ExtInterface, and inet::PacketMeterBase.
 { return NUM_INIT_STAGES; }
pushOrSendPacket()
void inet::queueing::PacketProcessorBase::pushOrSendPacket (Packet * packet, cGate * gate, IPassivePacketSink * consumer) protected virtual
 {
     if (consumer != nullptr) {
         animatePushPacket(packet, gate);
         consumer->pushPacket(packet, findConnectedGate<IPacketProcessor>(gate));
     }
     else
         send(packet, gate);
 }
Referenced by inet::DefragmenterBase::defragmentPacket(), inet::queueing::PacketServer::endProcessingPacket(), inet::queueing::PacketDelayer::handleMessage(), inet::queueing::PacketSendToPush::handleMessage(), inet::queueing::PcapFilePacketProducer::handleMessage(), inet::Resending::handleMessage(), inet::InterpacketGapInserter::handleMessage(), inet::Resending::handlePushPacketProcessed(), inet::queueing::InstantServer::processPacket(), inet::SendWithHopLimit::processPacket(), inet::queueing::TokenBasedServer::processPackets(), inet::queueing::ActivePacketSource::producePacket(), inet::queueing::PacketDuplicator::pushPacket(), inet::StreamSplitter::pushPacket(), inet::DuplicateRemoval::pushPacket(), inet::DeaggregatorBase::pushPacket(), inet::EthernetSocketPacketProcessor::pushPacket(), inet::Reordering::pushPacket(), inet::Forwarding::pushPacket(), inet::Ieee8021qSocketPacketProcessor::pushPacket(), inet::FragmenterBase::pushPacket(), inet::queueing::PacketDuplicatorBase::pushPacket(), inet::AggregatorBase::pushPacket(), inet::queueing::PacketCloner::pushPacket(), inet::queueing::MarkovScheduler::pushPacket(), inet::InterpacketGapInserter::pushPacket(), inet::queueing::PacketMultiplexer::pushPacket(), inet::queueing::PacketFlowBase::pushPacket(), inet::queueing::PacketClassifierBase::pushPacket(), inet::queueing::PacketFilterBase::pushPacket(), inet::NetworkInterface::pushPacket(), inet::PacketDestreamer::pushPacketEnd(), inet::PacketReceiver::receiveSignal(), inet::RelayInterfaceSelector::sendPacket(), and inet::DestreamingReceiver::sendToUpperLayer().
pushOrSendPacketEnd()
void inet::queueing::PacketProcessorBase::pushOrSendPacketEnd (Packet * packet, cGate * gate, IPassivePacketSink * consumer, int transmissionId) protected virtual
 {
     // NOTE: duration is unknown due to arbitrarily changing datarate
     SendOptions sendOptions;
     sendOptions.updateTx(transmissionId, 0);
     if (consumer != nullptr) {
         animatePushPacketEnd(packet, gate, sendOptions);
         consumer->pushPacketEnd(packet, findConnectedGate<IPacketProcessor>(gate));
     }
     else {
         auto progressTag = packet->addTagIfAbsent<ProgressTag>();
         progressTag->setDatarate(bps(NaN));
         progressTag->setPosition(packet->getTotalLength());
         send(packet, sendOptions, gate);
     }
 }
Referenced by inet::queueing::PreemptingServer::endStreaming(), inet::PacketStreamer::endStreaming(), inet::PreemptableStreamer::endStreaming(), inet::EthernetCutthroughSink::pushPacketEnd(), inet::EthernetCutthroughSource::pushPacketEnd(), inet::queueing::PacketFlowBase::pushPacketEnd(), inet::queueing::PacketMultiplexer::pushPacketEnd(), inet::queueing::PacketClassifierBase::pushPacketEnd(), inet::queueing::PacketFilterBase::pushPacketEnd(), inet::NetworkInterface::pushPacketEnd(), inet::queueing::PacketFlowBase::pushPacketProgress(), inet::StreamThroughReceiver::receivePacketEnd(), and inet::InterpacketGapInserter::receivePacketEnd().
pushOrSendPacketProgress()
void inet::queueing::PacketProcessorBase::pushOrSendPacketProgress (Packet * packet, cGate * gate, IPassivePacketSink * consumer, bps datarate, b position, b extraProcessableLength, int transmissionId) protected virtual
 {
     // NOTE: duration is unknown due to arbitrarily changing datarate
     simtime_t remainingDuration = s((packet->getTotalLength() - position) / datarate).get();
     SendOptions sendOptions;
     sendOptions.updateTx(transmissionId, remainingDuration);
     if (consumer != nullptr) {
         if (position == b(0)) {
             animatePushPacketStart(packet, gate, datarate, sendOptions);
             consumer->pushPacketStart(packet, gate->getPathEndGate(), datarate);
         }
         else if (position == packet->getTotalLength()) {
             animatePushPacketEnd(packet, gate, sendOptions);
             consumer->pushPacketEnd(packet, gate->getPathEndGate());
         }
         else {
             animatePushPacketProgress(packet, gate, datarate, position, extraProcessableLength, sendOptions);
             consumer->pushPacketProgress(packet, gate->getPathEndGate(), datarate, position, extraProcessableLength);
         }
     }
     else {
         auto progressTag = packet->addTagIfAbsent<ProgressTag>();
         progressTag->setDatarate(datarate);
         progressTag->setPosition(position);
         progressTag->setExtraProcessableLength(extraProcessableLength);
         send(packet, sendOptions, gate);
     }
 }
Referenced by inet::InterpacketGapInserter::handleMessage(), inet::InterpacketGapInserter::pushOrSendOrSchedulePacketProgress(), inet::queueing::PacketMultiplexer::pushPacketProgress(), inet::queueing::PacketFlowBase::pushPacketProgress(), inet::queueing::PacketClassifierBase::pushPacketProgress(), inet::queueing::PacketFilterBase::pushPacketProgress(), inet::physicallayer::EthernetPhyHeaderInserter::pushPacketStart(), inet::physicallayer::EthernetFragmentPhyHeaderInserter::pushPacketStart(), and inet::InterpacketGapInserter::receivePacketProgress().
pushOrSendPacketStart()
void inet::queueing::PacketProcessorBase::pushOrSendPacketStart (Packet * packet, cGate * gate, IPassivePacketSink * consumer, bps datarate, int transmissionId) protected virtual
 {
     simtime_t duration = s(packet->getTotalLength() / datarate).get();
     SendOptions sendOptions;
     sendOptions.duration(duration);
     sendOptions.updateTx(transmissionId, duration);
     if (consumer != nullptr) {
         animatePushPacketStart(packet, gate, datarate, sendOptions);
         consumer->pushPacketStart(packet, findConnectedGate<IPacketProcessor>(gate), datarate);
     }
     else {
         auto progressTag = packet->addTagIfAbsent<ProgressTag>();
         progressTag->setDatarate(datarate);
         progressTag->setPosition(b(0));
         send(packet, sendOptions, gate);
     }
 }
Referenced by inet::EthernetCutthroughSource::handleMessage(), inet::PacketStreamer::pushPacket(), inet::PreemptableStreamer::pushPacket(), inet::EthernetCutthroughSink::pushPacketStart(), inet::queueing::PacketMultiplexer::pushPacketStart(), inet::queueing::PacketFlowBase::pushPacketStart(), inet::queueing::PacketClassifierBase::pushPacketStart(), inet::queueing::PacketFilterBase::pushPacketStart(), inet::NetworkInterface::pushPacketStart(), inet::StreamThroughReceiver::receivePacketStart(), inet::InterpacketGapInserter::receivePacketStart(), and inet::queueing::PreemptingServer::startStreaming().
refreshDisplay()
void inet::queueing::PacketProcessorBase::refreshDisplay () const override protected virtual
Reimplemented in inet::NetworkInterface, inet::MultiFieldClassifier, inet::BehaviorAggregateClassifier, inet::DscpMarker, inet::TwoRateThreeColorMeter, inet::SingleRateThreeColorMeter, inet::queueing::CreditBasedGate, and inet::TokenBucketMeter.
 {
     updateDisplayString();
 }
resolveDirective()
const char * inet::queueing::PacketProcessorBase::resolveDirective (char directive) const override virtual
Implements inet::StringFormat::IDirectiveResolver.
Reimplemented in inet::NetworkInterface, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::TokenBucketMixin< PacketClassifierBase >, inet::queueing::MarkovClassifier, inet::queueing::CreditBasedGate, inet::queueing::MarkovScheduler, inet::queueing::PacketFilterBase, inet::InterpacketGapInserter, inet::queueing::TokenBasedServer, inet::queueing::PacketBasedTokenGenerator, inet::queueing::PacketServer, inet::queueing::PacketQueueBase, inet::queueing::TokenGeneratorBase, and inet::queueing::PacketBufferBase.
 {
     static std::string result;
     switch (directive) {
         case 'p':
             result = std::to_string(numProcessedPackets);
             break;
         case 'l':
             result = processedTotalLength.str();
             break;
         default:
             throw cRuntimeError("Unknown directive: %c", directive);
     }
     return result.c_str();
 }
Referenced by inet::queueing::PacketBufferBase::resolveDirective(), inet::queueing::TokenGeneratorBase::resolveDirective(), inet::queueing::PacketQueueBase::resolveDirective(), inet::queueing::PacketServer::resolveDirective(), inet::queueing::PacketBasedTokenGenerator::resolveDirective(), inet::queueing::TokenBasedServer::resolveDirective(), inet::InterpacketGapInserter::resolveDirective(), inet::queueing::PacketFilterBase::resolveDirective(), inet::queueing::CreditBasedGate::resolveDirective(), inet::queueing::MarkovScheduler::resolveDirective(), and inet::queueing::MarkovClassifier::resolveDirective().
supportsPacketPassing()
virtual bool inet::queueing::PacketProcessorBase::supportsPacketPassing (cGate * gate) const inline override virtual
Returns true if the processor supports passing packets as a whole at the given gate.
A passed packet is handed over from one module to another by either the standard OMNeT++ handleMessage() mechanism, or by directly calling pushPacket() or pullPacket().
For example, packets are passed as a whole to and from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pass) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::NetworkInterface, inet::PreemptableStreamer, inet::PacketStreamer, and inet::PacketDestreamer.
 { return true; }
supportsPacketSending()
virtual bool inet::queueing::PacketProcessorBase::supportsPacketSending (cGate * gate) const inline override virtual
Returns true if the processor supports sending packets at the given gate.
Sending a packet is an asynchronous operation that is initiated by the source module. A sent packet is always passed as a whole using standard handleMessage().
For output gates, true means that this module can send packets into the connected module. For input gates, true means that the connected module can send packets into this module. For example, a standard OMNeT++ module can send packets to an INET packet processor module, or an INET packet processor module can send packets to a standard OMNeT++ module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(send) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::NetworkInterface.
 { return true; }
supportsPacketStreaming()
virtual bool inet::queueing::PacketProcessorBase::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::NetworkInterface, inet::queueing::PacketFilterBase, inet::PreemptableStreamer, inet::queueing::PacketClassifierBase, inet::queueing::PacketSchedulerBase, inet::PacketStreamer, inet::queueing::PacketFlowBase, inet::PacketDestreamer, inet::queueing::PacketMultiplexer, inet::StreamThroughTransmitter, inet::DestreamingReceiver, inet::StreamingTransmitter, and inet::StreamThroughReceiver.
 { return false; }
updateDisplayString()
void inet::queueing::PacketProcessorBase::updateDisplayString () const protected virtual
Reimplemented in inet::NetworkInterface, and inet::queueing::PacketGateBase.
 {
     if (getEnvir()->isGUI() && displayStringTextFormat != nullptr) {
         auto text = StringFormat::formatString(displayStringTextFormat, this);
         getDisplayString().setTagArg("t", 0, text);
     }
 }
Referenced by inet::queueing::PacketBuffer::addPacket(), inet::queueing::TokenBasedServer::addTokens(), inet::queueing::PacketFilterBase::canPullPacket(), inet::queueing::ActivePacketSink::collectPacket(), inet::queueing::PassivePacketSink::consumePacket(), inet::DefragmenterBase::defragmentPacket(), inet::queueing::PreemptingServer::endStreaming(), inet::PacketStreamer::endStreaming(), inet::PreemptableStreamer::endStreaming(), inet::queueing::SignalBasedTokenGenerator::generateTokens(), inet::queueing::QueueBasedTokenGenerator::generateTokens(), inet::queueing::TokenBasedServer::handleCanPullPacketChanged(), inet::queueing::PacketSendToPush::handleMessage(), inet::queueing::PacketServer::handleMessage(), inet::queueing::TimeBasedTokenGenerator::handleMessage(), inet::InterpacketGapInserter::handleMessage(), inet::EthernetCutthroughSource::handleMessage(), inet::PacketReceiver::handleMessageWhenUp(), inet::PacketTransmitter::handleMessageWhenUp(), inet::StreamingTransmitter::handleMessageWhenUp(), inet::StreamThroughReceiver::handleMessageWhenUp(), inet::DestreamingReceiver::handleMessageWhenUp(), inet::StreamThroughTransmitter::handleMessageWhenUp(), inet::queueing::PacketQueue::handlePacketRemoved(), inet::queueing::TokenBasedServer::initialize(), inet::queueing::PacketBuffer::initialize(), inet::queueing::CompoundPacketQueueBase::initialize(), initialize(), inet::queueing::PacketQueue::initialize(), inet::StreamIdentifier::processPacket(), inet::StreamDecoder::processPacket(), inet::queueing::InstantServer::processPackets(), inet::queueing::TokenBasedServer::processPackets(), inet::queueing::ActivePacketSource::producePacket(), inet::queueing::PassivePacketSource::providePacket(), inet::queueing::PacketDemultiplexer::pullPacket(), inet::queueing::PassivePacketSource::pullPacket(), inet::queueing::MarkovClassifier::pullPacket(), inet::queueing::CompoundPacketQueueBase::pullPacket(), inet::PacketDestreamer::pullPacket(), inet::queueing::PacketQueue::pullPacket(), inet::queueing::PacketFlowBase::pullPacket(), inet::queueing::PacketSchedulerBase::pullPacket(), inet::queueing::PacketFilterBase::pullPacket(), inet::queueing::PacketFlowBase::pullPacketEnd(), inet::PacketStreamer::pullPacketEnd(), inet::queueing::PacketSchedulerBase::pullPacketEnd(), inet::PreemptableStreamer::pullPacketEnd(), inet::queueing::PacketFlowBase::pullPacketProgress(), inet::PacketStreamer::pullPacketProgress(), inet::queueing::PacketSchedulerBase::pullPacketProgress(), inet::PreemptableStreamer::pullPacketProgress(), inet::queueing::PacketFlowBase::pullPacketStart(), inet::PacketStreamer::pullPacketStart(), inet::queueing::PacketSchedulerBase::pullPacketStart(), inet::PreemptableStreamer::pullPacketStart(), inet::queueing::PacketPushToSend::pushPacket(), inet::queueing::PacketDuplicator::pushPacket(), inet::queueing::PacketDelayer::pushPacket(), inet::StreamSplitter::pushPacket(), inet::EthernetSocketPacketProcessor::pushPacket(), inet::DeaggregatorBase::pushPacket(), inet::PacketTransmitter::pushPacket(), inet::Ieee8021qSocketPacketProcessor::pushPacket(), inet::StreamingTransmitter::pushPacket(), inet::FragmenterBase::pushPacket(), inet::RelayInterfaceSelector::pushPacket(), inet::AggregatorBase::pushPacket(), inet::queueing::PacketBasedTokenGenerator::pushPacket(), inet::queueing::PacketCloner::pushPacket(), inet::queueing::MarkovScheduler::pushPacket(), inet::queueing::CompoundPacketQueueBase::pushPacket(), inet::InterpacketGapInserter::pushPacket(), inet::queueing::PacketMultiplexer::pushPacket(), inet::queueing::PacketFlowBase::pushPacket(), inet::queueing::PacketQueue::pushPacket(), inet::queueing::PacketClassifierBase::pushPacket(), inet::queueing::PacketFilterBase::pushPacket(), inet::EthernetCutthroughSink::pushPacketEnd(), inet::EthernetCutthroughSource::pushPacketEnd(), inet::StreamThroughTransmitter::pushPacketEnd(), inet::PacketDestreamer::pushPacketEnd(), inet::InterpacketGapInserter::pushPacketEnd(), inet::queueing::PacketFlowBase::pushPacketEnd(), inet::queueing::PacketMultiplexer::pushPacketEnd(), inet::queueing::PacketClassifierBase::pushPacketEnd(), inet::queueing::PacketFilterBase::pushPacketEnd(), inet::StreamThroughTransmitter::pushPacketProgress(), inet::queueing::PacketMultiplexer::pushPacketProgress(), inet::queueing::PacketFlowBase::pushPacketProgress(), inet::InterpacketGapInserter::pushPacketProgress(), inet::queueing::PacketClassifierBase::pushPacketProgress(), inet::queueing::PacketFilterBase::pushPacketProgress(), inet::physicallayer::EthernetPhyHeaderInserter::pushPacketStart(), inet::physicallayer::EthernetFragmentPhyHeaderInserter::pushPacketStart(), inet::EthernetCutthroughSink::pushPacketStart(), inet::EthernetCutthroughSource::pushPacketStart(), inet::StreamThroughTransmitter::pushPacketStart(), inet::queueing::PacketFlowBase::pushPacketStart(), inet::queueing::PacketMultiplexer::pushPacketStart(), inet::InterpacketGapInserter::pushPacketStart(), inet::queueing::PacketClassifierBase::pushPacketStart(), inet::queueing::PacketFilterBase::pushPacketStart(), inet::queueing::CompoundPacketQueueBase::receiveSignal(), refreshDisplay(), inet::queueing::PacketBuffer::removeAllPackets(), inet::queueing::CompoundPacketQueueBase::removeAllPackets(), inet::queueing::PacketQueue::removeAllPackets(), inet::queueing::PacketBuffer::removePacket(), inet::queueing::CompoundPacketQueueBase::removePacket(), inet::queueing::PacketQueue::removePacket(), inet::queueing::PreemptingServer::startStreaming(), and inet::queueing::PacketGateBase::updateDisplayString().
Member Data Documentation
displayStringTextFormat
const char* inet::queueing::PacketProcessorBase::displayStringTextFormat = nullptr protected
Referenced by inet::queueing::PacketBufferBase::initialize(), inet::queueing::TokenBasedServer::initialize(), inet::queueing::TokenGeneratorBase::initialize(), inet::queueing::PacketBuffer::initialize(), inet::queueing::PacketQueueBase::initialize(), initialize(), inet::queueing::CreditBasedGate::initialize(), and updateDisplayString().
numProcessedPackets
int inet::queueing::PacketProcessorBase::numProcessedPackets = -1 protected
Referenced by inet::queueing::ActivePacketSink::collectPacket(), inet::queueing::PassivePacketSink::consumePacket(), inet::AggregatorBase::continueAggregation(), inet::DefragmenterBase::continueDefragmentation(), inet::queueing::PacketSourceBase::createPacket(), inet::queueing::PacketSourceBase::createPacketContent(), inet::queueing::PacketSourceBase::createPacketName(), inet::queueing::PacketServer::endProcessingPacket(), inet::PacketStreamer::endStreaming(), inet::PreemptableStreamer::endStreaming(), handlePacketProcessed(), initialize(), inet::queueing::InstantServer::processPacket(), inet::queueing::TokenBasedServer::processPackets(), inet::queueing::PacketDemultiplexer::pullPacket(), inet::queueing::MarkovClassifier::pullPacket(), inet::DeaggregatorBase::pushPacket(), inet::FragmenterBase::pushPacket(), inet::queueing::PcapFilePacketConsumer::pushPacket(), inet::queueing::PacketBasedTokenGenerator::pushPacket(), inet::queueing::MarkovScheduler::pushPacket(), inet::PacketDestreamer::pushPacketEnd(), and resolveDirective().
processedTotalLength
b inet::queueing::PacketProcessorBase::processedTotalLength = b(-1) protected
Referenced by inet::queueing::ActivePacketSink::collectPacket(), inet::queueing::PassivePacketSink::consumePacket(), inet::AggregatorBase::continueAggregation(), inet::DefragmenterBase::continueDefragmentation(), inet::queueing::PacketSourceBase::createPacket(), inet::queueing::PacketServer::endProcessingPacket(), inet::PacketStreamer::endStreaming(), inet::PreemptableStreamer::endStreaming(), handlePacketProcessed(), initialize(), inet::queueing::InstantServer::processPacket(), inet::queueing::TokenBasedServer::processPackets(), inet::queueing::PacketDemultiplexer::pullPacket(), inet::queueing::MarkovClassifier::pullPacket(), inet::DeaggregatorBase::pushPacket(), inet::FragmenterBase::pushPacket(), inet::queueing::PcapFilePacketConsumer::pushPacket(), inet::queueing::PacketBasedTokenGenerator::pushPacket(), inet::queueing::MarkovScheduler::pushPacket(), inet::PacketDestreamer::pushPacketEnd(), and resolveDirective().
The documentation for this class was generated from the following files:
PacketProcessorBase.h
PacketProcessorBase.cc