INET Framework for OMNeT++/OMNEST: inet::ospfv2::NetworkLsa Class Reference
inet::ospfv2::NetworkLsa Class Reference
#include <Lsa.h>
Public Member Functions
NetworkLsa ()
NetworkLsa (const Ospfv2NetworkLsa &lsa)
NetworkLsa (const NetworkLsa &lsa)
virtual ~NetworkLsa ()
bool validateLSChecksum () const
bool update (const Ospfv2NetworkLsa *lsa)
bool differsFrom (const Ospfv2NetworkLsa *networkLSA) const
Public Member Functions inherited from inet::ospfv2::Ospfv2NetworkLsa
Ospfv2NetworkLsa ()
Ospfv2NetworkLsa (const Ospfv2NetworkLsa &other)
virtual ~Ospfv2NetworkLsa ()
Ospfv2NetworkLsa & operator= (const Ospfv2NetworkLsa &other)
virtual Ospfv2NetworkLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getNetworkMask () const
virtual ::inet::Ipv4Address & getNetworkMaskForUpdate ()
virtual void setNetworkMask (const ::inet::Ipv4Address &networkMask)
virtual void setAttachedRoutersArraySize (size_t size)
virtual size_t getAttachedRoutersArraySize () const
virtual const ::inet::Ipv4Address & getAttachedRouters (size_t k) const
virtual ::inet::Ipv4Address & getAttachedRoutersForUpdate (size_t k)
virtual void setAttachedRouters (size_t k, const ::inet::Ipv4Address &attachedRouters)
virtual void insertAttachedRouters (size_t k, const ::inet::Ipv4Address &attachedRouters)
void insertAttachedRouters (const ::inet::Ipv4Address &attachedRouters)
virtual void appendAttachedRouters (const ::inet::Ipv4Address &attachedRouters)
virtual void eraseAttachedRouters (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Public Member Functions inherited from inet::ospfv2::RoutingInfo
RoutingInfo ()
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo ()
void addNextHop (NextHop nextHop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
void setDistance (unsigned long d)
unsigned long getDistance () const
void setParent (Ospfv2Lsa *p)
Ospfv2Lsa * getParent () const
Public Member Functions inherited from inet::ospfv2::LsaTrackingInfo
LsaTrackingInfo ()
LsaTrackingInfo (const LsaTrackingInfo &info)
void setSource (InstallSource installSource)
InstallSource getSource () const
void incrementInstallTime ()
void resetInstallTime ()
unsigned long getInstallTime () const
Additional Inherited Members
Public Types inherited from inet::ospfv2::LsaTrackingInfo
enum InstallSource { ORIGINATED = 0, FLOODED = 1 }
Protected Member Functions inherited from inet::ospfv2::Ospfv2NetworkLsa
bool operator== (const Ospfv2NetworkLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes inherited from inet::ospfv2::Ospfv2NetworkLsa
::inet::Ipv4Address networkMask
::inet::Ipv4Address * attachedRouters = nullptr
size_t attachedRouters_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Constructor & Destructor Documentation
NetworkLsa() [1/3]
inet::ospfv2::NetworkLsa::NetworkLsa () inline
 : Ospfv2NetworkLsa(), RoutingInfo(), LsaTrackingInfo() {}
NetworkLsa() [2/3]
inet::ospfv2::NetworkLsa::NetworkLsa (const Ospfv2NetworkLsa & lsa) inline
 : Ospfv2NetworkLsa(lsa), RoutingInfo(), LsaTrackingInfo() {}
NetworkLsa() [3/3]
inet::ospfv2::NetworkLsa::NetworkLsa (const NetworkLsa & lsa) inline
 : Ospfv2NetworkLsa(lsa), RoutingInfo(lsa), LsaTrackingInfo(lsa) {}
~NetworkLsa()
virtual inet::ospfv2::NetworkLsa::~NetworkLsa () inline virtual
 {}
Member Function Documentation
differsFrom()
bool inet::ospfv2::NetworkLsa::differsFrom (const Ospfv2NetworkLsa * networkLSA) const
 {
     const Ospfv2LsaHeader& thisHeader = getHeader();
     const Ospfv2LsaHeader& lsaHeader = networkLSA->getHeader();
     bool differentHeader = ((thisHeader.getLsOptions() != lsaHeader.getLsOptions()) ||
                             ((thisHeader.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                             ((thisHeader.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                             (thisHeader.getLsaLength() != lsaHeader.getLsaLength()));
     bool differentBody = false;
     if (!differentHeader) {
         differentBody = ((getNetworkMask() != networkLSA->getNetworkMask()) ||
                          (getAttachedRoutersArraySize() != networkLSA->getAttachedRoutersArraySize()));
         if (!differentBody) {
             unsigned int routerCount = attachedRouters_arraysize;
             for (unsigned int i = 0; i < routerCount; i++) {
                 if (getAttachedRouters(i) != networkLSA->getAttachedRouters(i)) {
                     differentBody = true;
                     break;
                 }
             }
         }
     }
     return differentHeader || differentBody;
 }
Referenced by update().
update()
bool inet::ospfv2::NetworkLsa::update (const Ospfv2NetworkLsa * lsa)
 {
     bool different = differsFrom(lsa);
     (*this) = (*lsa);
     resetInstallTime();
     if (different) {
         clearNextHops();
         return true;
     }
     else {
         return false;
     }
 }
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), and inet::ospfv2::NeighborState::updateLsa().
validateLSChecksum()
bool inet::ospfv2::NetworkLsa::validateLSChecksum () const inline
 { return true; } // not implemented
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase().
The documentation for this class was generated from the following files:
Lsa.h
NetworkLsa.cc