INET Framework for OMNeT++/OMNEST: inet::sctp::SctpPacketDropChunk Class Reference
inet::sctp::SctpPacketDropChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:234 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpPacketDropChunk (const char *name=nullptr)
SctpPacketDropChunk (const SctpPacketDropChunk &other)
virtual ~SctpPacketDropChunk ()
SctpPacketDropChunk & operator= (const SctpPacketDropChunk &other)
virtual SctpPacketDropChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getCFlag () const
virtual void setCFlag (bool cFlag)
virtual bool getTFlag () const
virtual void setTFlag (bool tFlag)
virtual bool getBFlag () const
virtual void setBFlag (bool bFlag)
virtual bool getMFlag () const
virtual void setMFlag (bool mFlag)
virtual uint32_t getMaxRwnd () const
virtual void setMaxRwnd (uint32_t maxRwnd)
virtual uint32_t getQueuedData () const
virtual void setQueuedData (uint32_t queuedData)
virtual uint16_t getTruncLength () const
virtual void setTruncLength (uint16_t truncLength)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpPacketDropChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
bool cFlag = false
bool tFlag = false
bool bFlag = false
bool mFlag = false
uint32_t maxRwnd = 0
uint32_t queuedData = 0
uint16_t truncLength = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpPacketDropChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:234 by opp_msgtool.
class SctpPacketDropChunk extends SctpChunk
{
    bool cFlag;
    bool tFlag;
    bool bFlag;
    bool mFlag;
    uint32_t maxRwnd;
    uint32_t queuedData;
    uint16_t truncLength;
}
Constructor & Destructor Documentation
SctpPacketDropChunk() [1/2]
inet::sctp::SctpPacketDropChunk::SctpPacketDropChunk (const char * name = nullptr)
SctpPacketDropChunk() [2/2]
inet::sctp::SctpPacketDropChunk::SctpPacketDropChunk (const SctpPacketDropChunk & other)
~SctpPacketDropChunk()
virtual inet::sctp::SctpPacketDropChunk::~SctpPacketDropChunk () virtual
Member Function Documentation
copy()
void inet::sctp::SctpPacketDropChunk::copy (const SctpPacketDropChunk & other) private
dup()
virtual SctpPacketDropChunk* inet::sctp::SctpPacketDropChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpPacketDropChunk(*this);}
getBFlag()
virtual bool inet::sctp::SctpPacketDropChunk::getBFlag () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getCFlag()
virtual bool inet::sctp::SctpPacketDropChunk::getCFlag () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getMaxRwnd()
virtual uint32_t inet::sctp::SctpPacketDropChunk::getMaxRwnd () const virtual
Referenced by inet::sctp::SctpAssociation::processPacketDropArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getMFlag()
virtual bool inet::sctp::SctpPacketDropChunk::getMFlag () const virtual
Referenced by inet::sctp::SctpAssociation::processPacketDropArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getQueuedData()
virtual uint32_t inet::sctp::SctpPacketDropChunk::getQueuedData () const virtual
Referenced by inet::sctp::SctpAssociation::processPacketDropArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getTFlag()
virtual bool inet::sctp::SctpPacketDropChunk::getTFlag () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getTruncLength()
virtual uint16_t inet::sctp::SctpPacketDropChunk::getTruncLength () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpPacketDropChunk& inet::sctp::SctpPacketDropChunk::operator= (const SctpPacketDropChunk & other)
operator==()
bool inet::sctp::SctpPacketDropChunk::operator== (const SctpPacketDropChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpPacketDropChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpPacketDropChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setBFlag()
virtual void inet::sctp::SctpPacketDropChunk::setBFlag (bool bFlag) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
setCFlag()
virtual void inet::sctp::SctpPacketDropChunk::setCFlag (bool cFlag) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
setMaxRwnd()
virtual void inet::sctp::SctpPacketDropChunk::setMaxRwnd (uint32_t maxRwnd) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
setMFlag()
virtual void inet::sctp::SctpPacketDropChunk::setMFlag (bool mFlag) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
setQueuedData()
virtual void inet::sctp::SctpPacketDropChunk::setQueuedData (uint32_t queuedData) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
setTFlag()
virtual void inet::sctp::SctpPacketDropChunk::setTFlag (bool tFlag) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
setTruncLength()
virtual void inet::sctp::SctpPacketDropChunk::setTruncLength (uint16_t truncLength) virtual
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
Member Data Documentation
bFlag
bool inet::sctp::SctpPacketDropChunk::bFlag = false protected
cFlag
bool inet::sctp::SctpPacketDropChunk::cFlag = false protected
maxRwnd
uint32_t inet::sctp::SctpPacketDropChunk::maxRwnd = 0 protected
mFlag
bool inet::sctp::SctpPacketDropChunk::mFlag = false protected
queuedData
uint32_t inet::sctp::SctpPacketDropChunk::queuedData = 0 protected
tFlag
bool inet::sctp::SctpPacketDropChunk::tFlag = false protected
truncLength
uint16_t inet::sctp::SctpPacketDropChunk::truncLength = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h