INET Framework for OMNeT++/OMNEST: inet::physicallayer::NarrowbandNoiseBase Class Reference
inet::physicallayer::NarrowbandNoiseBase Class Reference abstract
#include <NarrowbandNoiseBase.h>
Public Member Functions
NarrowbandNoiseBase (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual Hz getCenterFrequency () const
virtual Hz getBandwidth () const
virtual W computeMinPower (simtime_t startTime, simtime_t endTime) const =0
virtual W computeMaxPower (simtime_t startTime, simtime_t endTime) const =0
Public Member Functions inherited from inet::physicallayer::NoiseBase
NoiseBase (simtime_t startTime, simtime_t endTime)
virtual const simtime_t getStartTime () const override
virtual const simtime_t getEndTime () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const Hz centerFrequency
const Hz bandwidth
Protected Attributes inherited from inet::physicallayer::NoiseBase
const simtime_t startTime
const simtime_t endTime
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
NarrowbandNoiseBase()
inet::physicallayer::NarrowbandNoiseBase::NarrowbandNoiseBase (simtime_t startTime, simtime_t endTime, Hz centerFrequency, Hz bandwidth)
                                                                                                                  :
     NoiseBase(startTime, endTime),
     centerFrequency(centerFrequency),
     bandwidth(bandwidth)
 {
 }
Member Function Documentation
computeMaxPower()
virtual W inet::physicallayer::NarrowbandNoiseBase::computeMaxPower (simtime_t startTime, simtime_t endTime) const pure virtual
Implemented in inet::physicallayer::DimensionalNoise, and inet::physicallayer::ScalarNoise.
Referenced by inet::physicallayer::FlatReceiverBase::computeListeningDecision(), inet::physicallayer::ApskLayeredReceiver::computeListeningDecision(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeListeningDecision().
computeMinPower()
virtual W inet::physicallayer::NarrowbandNoiseBase::computeMinPower (simtime_t startTime, simtime_t endTime) const pure virtual
Implemented in inet::physicallayer::DimensionalNoise, and inet::physicallayer::ScalarNoise.
getBandwidth()
virtual Hz inet::physicallayer::NarrowbandNoiseBase::getBandwidth () const inline virtual
 { return bandwidth; }
Referenced by inet::physicallayer::ScalarAnalogModelBase::computeNoise().
getCenterFrequency()
virtual Hz inet::physicallayer::NarrowbandNoiseBase::getCenterFrequency () const inline virtual
 { return centerFrequency; }
Referenced by inet::physicallayer::ScalarAnalogModelBase::computeNoise().
printToStream()
std::ostream & inet::physicallayer::NarrowbandNoiseBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::NoiseBase.
Reimplemented in inet::physicallayer::DimensionalNoise, and inet::physicallayer::ScalarNoise.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(centerFrequency)
                << EV_FIELD(bandwidth);
     return NoiseBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::ScalarNoise::printToStream(), and inet::physicallayer::DimensionalNoise::printToStream().
Member Data Documentation
bandwidth
const Hz inet::physicallayer::NarrowbandNoiseBase::bandwidth protected
Referenced by printToStream().
centerFrequency
const Hz inet::physicallayer::NarrowbandNoiseBase::centerFrequency protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
NarrowbandNoiseBase.h
NarrowbandNoiseBase.cc