INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmDataMode Class Reference
inet::physicallayer::Ieee80211OfdmDataMode Class Reference
#include <Ieee80211OfdmMode.h>
Public Member Functions
Ieee80211OfdmDataMode (const Ieee80211OfdmCode *code, const Ieee80211OfdmModulation *modulation, Hz channelSpacing, Hz bandwidth)
virtual ~Ieee80211OfdmDataMode ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
b getServiceFieldLength () const
b getTailFieldLength () const
virtual Hz getBandwidth () const override
virtual b getPaddingLength (b dataLength) const override
virtual b getCompleteLength (b dataLength) const override
virtual const simtime_t getDuration (b dataLength) const override
const Ieee80211OfdmCode * getCode () const
const Ieee80211OfdmModulation * getModulation () const override
virtual bps getGrossBitrate () const override
virtual bps getNetBitrate () const override
virtual int getNumberOfSpatialStreams () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmModeBase
Ieee80211OfdmModeBase (const Ieee80211OfdmModulation *modulation, const Ieee80211OfdmCode *code, Hz channelSpacing, Hz bandwidth)
virtual ~Ieee80211OfdmModeBase ()
int getNumberOfDataSubcarriers () const
int getNumberOfPilotSubcarriers () const
int getNumberOfTotalSubcarriers () const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing)
Hz getSubcarrierFrequencySpacing () const
const simtime_t getFFTTransformPeriod () const
const simtime_t getGIDuration () const
const simtime_t getSymbolInterval () const
const Hz getChannelSpacing () const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Member Functions inherited from inet::physicallayer::Ieee80211OfdmModeBase
bps computeGrossBitrate (const Ieee80211OfdmModulation *modulation) const
bps computeNetBitrate (bps grossBitrate, const Ieee80211OfdmCode *code) const
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmModeBase
const Ieee80211OfdmModulation * modulation
const Ieee80211OfdmCode * code
const Hz bandwidth
bps netBitrate
bps grossBitrate
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Hz channelSpacing
Constructor & Destructor Documentation
Ieee80211OfdmDataMode()
inet::physicallayer::Ieee80211OfdmDataMode::Ieee80211OfdmDataMode (const Ieee80211OfdmCode * code, const Ieee80211OfdmModulation * modulation, Hz channelSpacing, Hz bandwidth)
                                                                                                                                                       :
     Ieee80211OfdmModeBase(modulation, code, channelSpacing, bandwidth)
 {
 }
~Ieee80211OfdmDataMode()
virtual inet::physicallayer::Ieee80211OfdmDataMode::~Ieee80211OfdmDataMode () inline virtual
 {}
Member Function Documentation
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211OfdmDataMode::getBandwidth () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211OfdmModeBase.
 { return bandwidth; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::getBandwidth().
getCode()
const Ieee80211OfdmCode* inet::physicallayer::Ieee80211OfdmDataMode::getCode () const inline
 { return code; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldPacketModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate().
getCompleteLength()
b inet::physicallayer::Ieee80211OfdmDataMode::getCompleteLength (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     return dataLength + getTailFieldLength() + getPaddingLength(dataLength);
 }
Referenced by getDuration().
getDuration()
const simtime_t inet::physicallayer::Ieee80211OfdmDataMode::getDuration (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     // IEEE Std 802.11-2007, section 17.3.2.2, table 17-3
     // corresponds to N_{DBPS} in the table
     unsigned int codedBitsPerOFDMSymbol = modulation->getSubcarrierModulation()->getCodeWordSize() * getNumberOfDataSubcarriers();
     const ConvolutionalCode *convolutionalCode = code ? code->getConvolutionalCode() : nullptr;
     unsigned int dataBitsPerOFDMSymbol = convolutionalCode ? convolutionalCode->getDecodedLength(codedBitsPerOFDMSymbol) : codedBitsPerOFDMSymbol;
     // IEEE Std 802.11-2007, section 17.3.5.3, equation (17-11)
     unsigned int numberOfSymbols = lrint(ceil((double)(getServiceFieldLength() + getCompleteLength(dataLength)).get() / dataBitsPerOFDMSymbol));
     // Add signal extension for ERP PHY
     return numberOfSymbols * getSymbolInterval();
 }
Referenced by inet::physicallayer::Ieee80211OfdmMode::getDuration().
getGrossBitrate()
virtual bps inet::physicallayer::Ieee80211OfdmDataMode::getGrossBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211OfdmModeBase.
 { return Ieee80211OfdmModeBase::getGrossBitrate(); }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel().
getModulation()
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmDataMode::getModulation () const inline override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 { return modulation; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::~Ieee80211LayeredOfdmTransmitter().
getNetBitrate()
virtual bps inet::physicallayer::Ieee80211OfdmDataMode::getNetBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211OfdmModeBase.
 { return Ieee80211OfdmModeBase::getNetBitrate(); }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createPacketModel().
getNumberOfSpatialStreams()
virtual int inet::physicallayer::Ieee80211OfdmDataMode::getNumberOfSpatialStreams () const inline override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 { return 1; }
getPaddingLength()
b inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     unsigned int codedBitsPerOFDMSymbol = modulation->getSubcarrierModulation()->getCodeWordSize() * NUMBER_OF_OFDM_DATA_SUBCARRIERS;
     unsigned int dataBitsPerOFDMSymbol = codedBitsPerOFDMSymbol; // N_DBPS
     if (code->getConvolutionalCode()) {
         const ConvolutionalCode *convolutionalCode = code->getConvolutionalCode();
         dataBitsPerOFDMSymbol = convolutionalCode->getDecodedLength(codedBitsPerOFDMSymbol);
     }
     unsigned int dataBitsLength = 6 + b(dataLength).get() + 16;
     unsigned int numberOfOFDMSymbols = lrint(ceil(1.0 * dataBitsLength / dataBitsPerOFDMSymbol));
     unsigned int numberOfBitsInTheDataField = dataBitsPerOFDMSymbol * numberOfOFDMSymbols; // N_DATA
     unsigned int numberOfPadBits = numberOfBitsInTheDataField - dataBitsLength; // N_PAD
     return b(numberOfPadBits);
 }
Referenced by getCompleteLength().
getServiceFieldLength()
b inet::physicallayer::Ieee80211OfdmDataMode::getServiceFieldLength () const inline
 { return b(16); }
Referenced by getDuration().
getTailFieldLength()
b inet::physicallayer::Ieee80211OfdmDataMode::getTailFieldLength () const inline
 { return b(6); }
Referenced by getCompleteLength().
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmDataMode::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Ieee80211OfdmDataMode";
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(netBitrate);
     return stream;
 }
The documentation for this class was generated from the following files:
Ieee80211OfdmMode.h
Ieee80211OfdmMode.cc