INET Framework for OMNeT++/OMNEST: inet::IRoutingTable Class Reference
inet::IRoutingTable Class Reference abstract
A C++ interface to abstract the functionality of a routing table, regardless of address type.
#include <IRoutingTable.h>
Public Member Functions
virtual ~IRoutingTable ()
Miscellaneous functions
virtual bool isForwardingEnabled () const =0
Forwarding on/off.
virtual bool isAdminDistEnabled () const =0
Administrative distance on/off.
virtual bool isMulticastForwardingEnabled () const =0
Multicast forwarding on/off.
virtual L3Address getRouterIdAsGeneric () const =0
Returns routerId.
virtual bool isLocalAddress (const L3Address &dest) const =0
Checks if the address is a local one, i.e.
virtual NetworkInterface * getInterfaceByAddress (const L3Address &address) const =0
Returns an interface given by its address.
virtual void printRoutingTable () const =0
Prints the routing table.
Routing functions (query the route table)
virtual IRoute * findBestMatchingRoute (const L3Address &dest) const =0
The routing function.
virtual NetworkInterface * getOutputInterfaceForDestination (const L3Address &dest) const =0
Convenience function based on findBestMatchingRoute().
virtual L3Address getNextHopForDestination (const L3Address &dest) const =0
Convenience function based on findBestMatchingRoute().
Multicast routing functions
virtual bool isLocalMulticastAddress (const L3Address &dest) const =0
Checks if the address is in one of the local multicast group address list.
virtual IMulticastRoute * findBestMatchingMulticastRoute (const L3Address &origin, const L3Address &group) const =0
Returns route for a multicast origin and group.
Route table manipulation
virtual int getNumRoutes () const =0
Returns the total number of unicast routes.
virtual IRoute * getRoute (int k) const =0
Returns the kth route.
virtual IRoute * getDefaultRoute () const =0
Finds and returns the default route, or nullptr if it doesn't exist.
virtual void addRoute (IRoute *entry)=0
Adds a route to the routing table.
virtual IRoute * removeRoute (IRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (IRoute *entry)=0
Deletes the given route from the routing table.
virtual int getNumMulticastRoutes () const =0
Returns the total number of multicast routes.
virtual IMulticastRoute * getMulticastRoute (int k) const =0
Returns the kth multicast route.
virtual void addMulticastRoute (IMulticastRoute *entry)=0
Adds a multicast route to the routing table.
virtual IMulticastRoute * removeMulticastRoute (IMulticastRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (IMulticastRoute *entry)=0
Deletes the given multicast route from the routing table.
virtual IRoute * createRoute ()=0
Detailed Description
A C++ interface to abstract the functionality of a routing table, regardless of address type.
Constructor & Destructor Documentation
~IRoutingTable()
virtual inet::IRoutingTable::~IRoutingTable () inline virtual
 {}
Member Function Documentation
addMulticastRoute()
virtual void inet::IRoutingTable::addMulticastRoute (IMulticastRoute * entry) pure virtual
Adds a multicast route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable().
addRoute()
virtual void inet::IRoutingTable::addRoute (IRoute * entry) pure virtual
Adds a route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::Ipv4NetworkConfigurator::configureRoutingTable().
createRoute()
virtual IRoute* inet::IRoutingTable::createRoute () pure virtual
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
deleteMulticastRoute()
virtual bool inet::IRoutingTable::deleteMulticastRoute (IMulticastRoute * entry) pure virtual
Deletes the given multicast route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
deleteRoute()
virtual bool inet::IRoutingTable::deleteRoute (IRoute * entry) pure virtual
Deletes the given route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
findBestMatchingMulticastRoute()
virtual IMulticastRoute* inet::IRoutingTable::findBestMatchingMulticastRoute (const L3Address & origin, const L3Address & group) const pure virtual
Returns route for a multicast origin and group.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
findBestMatchingRoute()
virtual IRoute* inet::IRoutingTable::findBestMatchingRoute (const L3Address & dest) const pure virtual
The routing function.
Performs longest prefix match for the given destination address, and returns the resulting route. Returns nullptr if there is no matching route.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
getDefaultRoute()
virtual IRoute* inet::IRoutingTable::getDefaultRoute () const pure virtual
Finds and returns the default route, or nullptr if it doesn't exist.
Implemented in inet::IIpv4RoutingTable, inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
getInterfaceByAddress()
virtual NetworkInterface* inet::IRoutingTable::getInterfaceByAddress (const L3Address & address) const pure virtual
Returns an interface given by its address.
Returns nullptr if not found.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
getMulticastRoute()
virtual IMulticastRoute* inet::IRoutingTable::getMulticastRoute (int k) const pure virtual
Returns the kth multicast route.
Implemented in inet::IIpv4RoutingTable, inet::Ipv4RoutingTable, inet::NextHopRoutingTable, and inet::Ipv6RoutingTable.
getNextHopForDestination()
virtual L3Address inet::IRoutingTable::getNextHopForDestination (const L3Address & dest) const pure virtual
Convenience function based on findBestMatchingRoute().
Returns the gateway for the destination address. Returns the unspecified address if the destination is not in routing table or the gateway field is not filled in in the route.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
getNumMulticastRoutes()
virtual int inet::IRoutingTable::getNumMulticastRoutes () const pure virtual
Returns the total number of multicast routes.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::Ipv4NetworkConfigurator::dumpConfig(), inet::NextHopNetworkConfigurator::dumpRoutes(), and inet::Ipv4NetworkConfigurator::dumpRoutes().
getNumRoutes()
virtual int inet::IRoutingTable::getNumRoutes () const pure virtual
Returns the total number of unicast routes.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::bgp::BgpRouter::addToAdvertiseList(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::ospfv2::Router::getDefaultRoute(), inet::ospfv3::Ospfv3Process::isInRoutingTable(), inet::bgp::BgpRouter::isInRoutingTable(), inet::bgp::BgpRouter::isReachable(), inet::bgp::BgpRouter::ospfExist(), inet::ospfv2::Router::rebuildRoutingTable(), and inet::ospfv2::Router::updateExternalRoute().
getOutputInterfaceForDestination()
virtual NetworkInterface* inet::IRoutingTable::getOutputInterfaceForDestination (const L3Address & dest) const pure virtual
Convenience function based on findBestMatchingRoute().
Returns the output interface for the packets with dest as destination address, or nullptr if the destination is not in routing table.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::sctp::SctpAssociation::pmStartPathManagement(), and inet::sctp::SctpPathVariables::SctpPathVariables().
getRoute()
virtual IRoute* inet::IRoutingTable::getRoute (int k) const pure virtual
Returns the kth route.
Implemented in inet::IIpv4RoutingTable, inet::Ipv4RoutingTable, inet::NextHopRoutingTable, and inet::Ipv6RoutingTable.
getRouterIdAsGeneric()
virtual L3Address inet::IRoutingTable::getRouterIdAsGeneric () const pure virtual
Returns routerId.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::RoutingTableRecorder::recordRouteChange().
isAdminDistEnabled()
virtual bool inet::IRoutingTable::isAdminDistEnabled () const pure virtual
Administrative distance on/off.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::Ipv4Route::str().
isForwardingEnabled()
virtual bool inet::IRoutingTable::isForwardingEnabled () const pure virtual
Forwarding on/off.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::L3NetworkConfiguratorBase::computeNodeWeight(), and inet::L3NetworkConfiguratorBase::determineGatewayForLink().
isLocalAddress()
virtual bool inet::IRoutingTable::isLocalAddress (const L3Address & dest) const pure virtual
Checks if the address is a local one, i.e.
one of the host's.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
isLocalMulticastAddress()
virtual bool inet::IRoutingTable::isLocalMulticastAddress (const L3Address & dest) const pure virtual
Checks if the address is in one of the local multicast group address list.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
isMulticastForwardingEnabled()
virtual bool inet::IRoutingTable::isMulticastForwardingEnabled () const pure virtual
Multicast forwarding on/off.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
Referenced by inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration().
printRoutingTable()
virtual void inet::IRoutingTable::printRoutingTable () const pure virtual
Prints the routing table.
Implemented in inet::Ipv6RoutingTable, inet::NextHopRoutingTable, and inet::Ipv4RoutingTable.
Referenced by inet::NextHopNetworkConfigurator::dumpRoutes().
removeMulticastRoute()
virtual IMulticastRoute* inet::IRoutingTable::removeMulticastRoute (IMulticastRoute * entry) pure virtual
Removes the given route from the routing table, and returns it.
nullptr is returned of the route was not in the routing table.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
removeRoute()
virtual IRoute* inet::IRoutingTable::removeRoute (IRoute * entry) pure virtual
Removes the given route from the routing table, and returns it.
nullptr is returned if the route was not in the routing table.
Implemented in inet::Ipv6RoutingTable, inet::Ipv4RoutingTable, and inet::NextHopRoutingTable.
The documentation for this class was generated from the following file:
IRoutingTable.h