INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211ConfigureRadioCommand Class Reference
inet::physicallayer::Ieee80211ConfigureRadioCommand Class Reference
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211ControlInfo.msg:19 by opp_msgtool.
#include <Ieee80211ControlInfo_m.h>
Public Member Functions
Ieee80211ConfigureRadioCommand ()
Ieee80211ConfigureRadioCommand (const Ieee80211ConfigureRadioCommand &other)
virtual ~Ieee80211ConfigureRadioCommand ()
Ieee80211ConfigureRadioCommand & operator= (const Ieee80211ConfigureRadioCommand &other)
virtual Ieee80211ConfigureRadioCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const char * getOpMode () const
virtual void setOpMode (const char *opMode)
virtual const Ieee80211ModeSet * getModeSet () const
virtual void setModeSet (const Ieee80211ModeSet *modeSet)
virtual const IIeee80211Mode * getMode () const
virtual void setMode (const IIeee80211Mode *mode)
virtual const IIeee80211Band * getBand () const
virtual IIeee80211Band * getBandForUpdate ()
virtual void setBand (IIeee80211Band *band)
virtual const Ieee80211Channel * getChannel () const
virtual Ieee80211Channel * getChannelForUpdate ()
virtual void setChannel (Ieee80211Channel *channel)
virtual int getChannelNumber () const
virtual void setChannelNumber (int channelNumber)
Public Member Functions inherited from inet::physicallayer::ConfigureRadioCommand
ConfigureRadioCommand ()
ConfigureRadioCommand (const ConfigureRadioCommand &other)
virtual ~ConfigureRadioCommand ()
ConfigureRadioCommand & operator= (const ConfigureRadioCommand &other)
virtual int getRadioMode () const
virtual void setRadioMode (int radioMode)
virtual ::inet::W getPower () const
virtual void setPower (::inet::W power)
virtual ::inet::bps getBitrate () const
virtual void setBitrate (::inet::bps bitrate)
virtual const IModulation * getModulation () const
virtual IModulation * getModulationForUpdate ()
virtual void setModulation (IModulation *modulation)
virtual ::inet::Hz getCenterFrequency () const
virtual void setCenterFrequency (::inet::Hz centerFrequency)
virtual ::inet::Hz getBandwidth () const
virtual void setBandwidth (::inet::Hz bandwidth)
Protected Member Functions
bool operator== (const Ieee80211ConfigureRadioCommand &)=delete
Protected Member Functions inherited from inet::physicallayer::ConfigureRadioCommand
bool operator== (const ConfigureRadioCommand &)=delete
Protected Attributes
::omnetpp::opp_string opMode
const Ieee80211ModeSet * modeSet = nullptr
const IIeee80211Mode * mode = nullptr
IIeee80211Band * band = nullptr
Ieee80211Channel * channel = nullptr
int channelNumber = -1
Protected Attributes inherited from inet::physicallayer::ConfigureRadioCommand
int radioMode = -1
::inet::W power = W(NaN)
::inet::bps bitrate = bps(NaN)
IModulation * modulation = nullptr
::inet::Hz centerFrequency = Hz(NaN)
::inet::Hz bandwidth = Hz(NaN)
Private Member Functions
void copy (const Ieee80211ConfigureRadioCommand &other)
Detailed Description
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211ControlInfo.msg:19 by opp_msgtool.
//
// Control info attached to a configure command that is sent to the ~Radio.
//
class Ieee80211ConfigureRadioCommand extends ConfigureRadioCommand
{
    string opMode;                         // new default operation mode or "" if not set.
    const Ieee80211ModeSet *modeSet;       // new default mode set or nullptr if not set.
    const IIeee80211Mode *mode;            // new default transmission mode or nullptr if not set.
    IIeee80211Band *band;                  // new default band or nullptr if not set.
    Ieee80211Channel *channel;             // new default band and channel or nullptr if not set.
    int channelNumber = -1;                // new default channel number in the range [0, numChannels] or -1 if not set.
}
Constructor & Destructor Documentation
Ieee80211ConfigureRadioCommand() [1/2]
inet::physicallayer::Ieee80211ConfigureRadioCommand::Ieee80211ConfigureRadioCommand ()
Ieee80211ConfigureRadioCommand() [2/2]
inet::physicallayer::Ieee80211ConfigureRadioCommand::Ieee80211ConfigureRadioCommand (const Ieee80211ConfigureRadioCommand & other)
~Ieee80211ConfigureRadioCommand()
virtual inet::physicallayer::Ieee80211ConfigureRadioCommand::~Ieee80211ConfigureRadioCommand () virtual
Member Function Documentation
copy()
void inet::physicallayer::Ieee80211ConfigureRadioCommand::copy (const Ieee80211ConfigureRadioCommand & other) private
dup()
virtual Ieee80211ConfigureRadioCommand* inet::physicallayer::Ieee80211ConfigureRadioCommand::dup () const inline override virtual
Reimplemented from inet::physicallayer::ConfigureRadioCommand.
 {return new Ieee80211ConfigureRadioCommand(*this);}
getBand()
virtual const IIeee80211Band* inet::physicallayer::Ieee80211ConfigureRadioCommand::getBand () const virtual
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand().
getBandForUpdate()
virtual IIeee80211Band* inet::physicallayer::Ieee80211ConfigureRadioCommand::getBandForUpdate () inline virtual
 { return const_cast<IIeee80211Band *>(const_cast<Ieee80211ConfigureRadioCommand*>(this)->getBand());}
getChannel()
virtual const Ieee80211Channel* inet::physicallayer::Ieee80211ConfigureRadioCommand::getChannel () const virtual
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand().
getChannelForUpdate()
virtual Ieee80211Channel* inet::physicallayer::Ieee80211ConfigureRadioCommand::getChannelForUpdate () inline virtual
 { return const_cast<Ieee80211Channel *>(const_cast<Ieee80211ConfigureRadioCommand*>(this)->getChannel());}
getChannelNumber()
virtual int inet::physicallayer::Ieee80211ConfigureRadioCommand::getChannelNumber () const virtual
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand(), and inet::ieee80211::Ieee80211Mac::handleUpperCommand().
getMode()
virtual const IIeee80211Mode* inet::physicallayer::Ieee80211ConfigureRadioCommand::getMode () const virtual
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand().
getModeSet()
virtual const Ieee80211ModeSet* inet::physicallayer::Ieee80211ConfigureRadioCommand::getModeSet () const virtual
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand().
getOpMode()
virtual const char* inet::physicallayer::Ieee80211ConfigureRadioCommand::getOpMode () const virtual
Referenced by inet::physicallayer::Ieee80211Radio::handleUpperCommand().
operator=()
Ieee80211ConfigureRadioCommand& inet::physicallayer::Ieee80211ConfigureRadioCommand::operator= (const Ieee80211ConfigureRadioCommand & other)
operator==()
bool inet::physicallayer::Ieee80211ConfigureRadioCommand::operator== (const Ieee80211ConfigureRadioCommand &) protected delete
parsimPack()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::physicallayer::ConfigureRadioCommand.
Referenced by inet::physicallayer::doParsimPacking().
parsimUnpack()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::physicallayer::ConfigureRadioCommand.
Referenced by inet::physicallayer::doParsimUnpacking().
setBand()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::setBand (IIeee80211Band * band) virtual
setChannel()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::setChannel (Ieee80211Channel * channel) virtual
setChannelNumber()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::setChannelNumber (int channelNumber) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::changeChannel(), and inet::ieee80211::Ieee80211Mac::handleUpperCommand().
setMode()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::setMode (const IIeee80211Mode * mode) virtual
setModeSet()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::setModeSet (const Ieee80211ModeSet * modeSet) virtual
setOpMode()
virtual void inet::physicallayer::Ieee80211ConfigureRadioCommand::setOpMode (const char * opMode) virtual
Member Data Documentation
band
IIeee80211Band* inet::physicallayer::Ieee80211ConfigureRadioCommand::band = nullptr protected
channel
Ieee80211Channel* inet::physicallayer::Ieee80211ConfigureRadioCommand::channel = nullptr protected
channelNumber
int inet::physicallayer::Ieee80211ConfigureRadioCommand::channelNumber = -1 protected
mode
const IIeee80211Mode* inet::physicallayer::Ieee80211ConfigureRadioCommand::mode = nullptr protected
modeSet
const Ieee80211ModeSet* inet::physicallayer::Ieee80211ConfigureRadioCommand::modeSet = nullptr protected
opMode
::omnetpp::opp_string inet::physicallayer::Ieee80211ConfigureRadioCommand::opMode protected
The documentation for this class was generated from the following file:
Ieee80211ControlInfo_m.h