INET Framework for OMNeT++/OMNEST: inet::IndexedImageFigure Class Reference
inet::IndexedImageFigure Class Reference
#include <IndexedImageFigure.h>
Public Member Functions
IndexedImageFigure (const char *name=nullptr)
virtual ~IndexedImageFigure ()
virtual void setValue (int series, simtime_t timestamp, double value) override
const std::vector< std::string > & getImages () const
void setImages (const std::vector< std::string > &images)
double getTintAmount () const
void setTintAmount (double tintAmount)
const Color & getTintColor () const
void setTintColor (const Color &color)
double getOpacity () const
void setOpacity (double opacity)
Interpolation getInterpolation () const
void setInterpolation (Interpolation interpolation)
const char * getLabel () const
void setLabel (const char *text)
const Font & getLabelFont () const
void setLabelFont (const Font &font)
const Color & getLabelColor () const
void setLabelColor (const Color &color)
const Point getLabelOffset () const
void setLabelOffset (const Point &offset)
virtual const Point getSize () const override
void setSize (const Point &bounds)
const Point & getPos () const
void setPos (const Point &point)
Anchor getAnchor () const
void setAnchor (Anchor anchor)
Public Member Functions inherited from inet::IIndicatorFigure
virtual ~IIndicatorFigure ()
virtual int getNumSeries () const
virtual void refreshDisplay ()
Protected Member Functions
virtual void parse (cProperty *property) override
virtual const char ** getAllowedPropertyKeys () const override
void addChildren ()
void refresh ()
Private Attributes
std::vector< std::string > images
cImageFigure * image
cTextFigure * labelFigure
double value = NaN
Constructor & Destructor Documentation
IndexedImageFigure()
inet::IndexedImageFigure::IndexedImageFigure (const char * name = nullptr)
                                                        : cGroupFigure(name)
 {
     addChildren();
 }
~IndexedImageFigure()
virtual inet::IndexedImageFigure::~IndexedImageFigure () inline virtual
 {}
Member Function Documentation
addChildren()
void inet::IndexedImageFigure::addChildren () protected
 {
     labelFigure = new cTextFigure("label");
     image = new cImageFigure("image");
     labelFigure->setAnchor(ANCHOR_N);
     addFigure(image);
     addFigure(labelFigure);
 }
Referenced by IndexedImageFigure().
getAllowedPropertyKeys()
const char ** inet::IndexedImageFigure::getAllowedPropertyKeys () const override protected virtual
 {
     static const char *keys[32];
     if (!keys[0]) {
         const char *localKeys[] = {
             PKEY_IMAGES, PKEY_TINT_AMOUNT, PKEY_TINT_COLOR, PKEY_OPACITY,
             PKEY_INTERPOLATION, PKEY_LABEL, PKEY_LABEL_FONT, PKEY_LABEL_COLOR,
             PKEY_LABEL_OFFSET, PKEY_INITIAL_VALUE, PKEY_POS, PKEY_SIZE, PKEY_ANCHOR,
             PKEY_BOUNDS, nullptr
         };
         concatArrays(keys, cGroupFigure::getAllowedPropertyKeys(), localKeys);
     }
     return keys;
 }
getAnchor()
cFigure::Anchor inet::IndexedImageFigure::getAnchor () const
 {
     return image->getAnchor();
 }
getImages()
const std::vector< std::string > & inet::IndexedImageFigure::getImages () const
 {
     return images;
 }
Referenced by inet::visualizer::RadioCanvasVisualizer::setImageIndex().
getInterpolation()
cFigure::Interpolation inet::IndexedImageFigure::getInterpolation () const
 {
     return image->getInterpolation();
 }
getLabel()
const char * inet::IndexedImageFigure::getLabel () const
 {
     return labelFigure->getText();
 }
getLabelColor()
const cFigure::Color & inet::IndexedImageFigure::getLabelColor () const
 {
     return labelFigure->getColor();
 }
getLabelFont()
const cFigure::Font & inet::IndexedImageFigure::getLabelFont () const
 {
     return labelFigure->getFont();
 }
getLabelOffset()
const cFigure::Point inet::IndexedImageFigure::getLabelOffset () const
 {
     return labelFigure->getPosition() - image->getPosition();
 }
Referenced by setPos().
getOpacity()
double inet::IndexedImageFigure::getOpacity () const
 {
     return image->getOpacity();
 }
getPos()
const cFigure::Point & inet::IndexedImageFigure::getPos () const
 {
     return image->getPosition();
 }
getSize()
const cFigure::Point inet::IndexedImageFigure::getSize () const override virtual
Implements inet::IIndicatorFigure.
 {
     return Point(image->getWidth(), image->getHeight());
 }
getTintAmount()
double inet::IndexedImageFigure::getTintAmount () const
 {
     return image->getTintAmount();
 }
getTintColor()
const cFigure::Color & inet::IndexedImageFigure::getTintColor () const
 {
     return image->getTintColor();
 }
parse()
void inet::IndexedImageFigure::parse (cProperty * property) override protected virtual
 {
     ASSERT(property->getNumValues(PKEY_IMAGES));
     cGroupFigure::parse(property);
     const char *s;
     std::vector<std::string> names;
     for (int i = 0; i < property->getNumValues(PKEY_IMAGES); ++i)
         names.push_back(property->getValue(PKEY_IMAGES, i));
     setImages(names);
     if (property->containsKey(PKEY_BOUNDS)) {
         if (property->containsKey(PKEY_POS) || property->containsKey(PKEY_SIZE) || property->containsKey(PKEY_ANCHOR))
             throw cRuntimeError("%s, %s and %s are not allowed when %s is present", PKEY_POS, PKEY_SIZE, PKEY_ANCHOR, PKEY_BOUNDS);
         if (property->getNumValues(PKEY_BOUNDS) != 4)
             throw cRuntimeError("%s: x, y, width, height expected", PKEY_BOUNDS);
         Point p = parsePoint(property, PKEY_BOUNDS, 0);
         Point size = parsePoint(property, PKEY_BOUNDS, 2);
         setPos(p);
         setSize(size);
         setAnchor(ANCHOR_NW);
     }
     else {
         setPos(parsePoint(property, PKEY_POS, 0));
         if ((s = property->getValue(PKEY_ANCHOR)) != nullptr)
             setAnchor(parseAnchor(s));
         if ((s = property->getValue(PKEY_SIZE)) != nullptr)
             setSize(parsePoint(property, PKEY_SIZE, 0));
     }
     if ((s = property->getValue(PKEY_TINT_AMOUNT)) != nullptr)
         setTintAmount(utils::atod(s));
     if ((s = property->getValue(PKEY_TINT_COLOR)) != nullptr)
         setTintColor(parseColor(s));
     if ((s = property->getValue(PKEY_OPACITY)) != nullptr)
         setOpacity(atof(s));
     if ((s = property->getValue(PKEY_INTERPOLATION)) != nullptr)
         setInterpolation(parseInterpolation(s));
     if ((s = property->getValue(PKEY_LABEL)) != nullptr)
         setLabel(s);
     if ((s = property->getValue(PKEY_LABEL_FONT)) != nullptr)
         setLabelFont(parseFont(s));
     if ((s = property->getValue(PKEY_LABEL_COLOR)) != nullptr)
         setLabelColor(parseColor(s));
     if (property->containsKey(PKEY_LABEL_OFFSET))
         setLabelOffset(parsePoint(property, PKEY_LABEL_OFFSET, 0));
     if ((s = property->getValue(PKEY_INITIAL_VALUE)) != nullptr)
         setValue(0, simTime(), utils::atod(s));
 }
refresh()
void inet::IndexedImageFigure::refresh () protected
 {
     if (std::isnan(value)) {
         image->setVisible(false);
         return;
     }
     image->setVisible(true);
     int newValue = (int)value % images.size();
     image->setImageName(images[newValue].c_str());
 }
Referenced by setImages(), and setValue().
setAnchor()
void inet::IndexedImageFigure::setAnchor (Anchor anchor)
 {
     image->setAnchor(anchor);
 }
Referenced by parse().
setImages()
void inet::IndexedImageFigure::setImages (const std::vector< std::string > & images)
 {
     ASSERT(images.size());
     this->images = images;
     refresh();
 }
Referenced by inet::visualizer::RadioCanvasVisualizer::createRadioVisualization(), and parse().
setInterpolation()
void inet::IndexedImageFigure::setInterpolation (Interpolation interpolation)
 {
     image->setInterpolation(interpolation);
 }
Referenced by parse().
setLabel()
void inet::IndexedImageFigure::setLabel (const char * text)
 {
     labelFigure->setText(text);
 }
Referenced by parse().
setLabelColor()
void inet::IndexedImageFigure::setLabelColor (const Color & color)
 {
     labelFigure->setColor(color);
 }
Referenced by parse().
setLabelFont()
void inet::IndexedImageFigure::setLabelFont (const Font & font)
 {
     labelFigure->setFont(font);
 }
Referenced by parse().
setLabelOffset()
void inet::IndexedImageFigure::setLabelOffset (const Point & offset)
 {
     labelFigure->setPosition(image->getPosition() + offset);
 }
Referenced by parse(), and setPos().
setOpacity()
void inet::IndexedImageFigure::setOpacity (double opacity)
 {
     image->setOpacity(opacity);
 }
Referenced by parse().
setPos()
void inet::IndexedImageFigure::setPos (const Point & point)
 {
     Point offset = getLabelOffset();
     image->setPosition(pos);
     setLabelOffset(offset);
 }
Referenced by parse().
setSize()
void inet::IndexedImageFigure::setSize (const Point & bounds)
 {
     image->setWidth(bounds.x);
     image->setHeight(bounds.y);
 }
Referenced by inet::visualizer::RadioCanvasVisualizer::createRadioVisualization(), and parse().
setTintAmount()
void inet::IndexedImageFigure::setTintAmount (double tintAmount)
 {
     image->setTintAmount(tintAmount);
 }
Referenced by parse().
setTintColor()
void inet::IndexedImageFigure::setTintColor (const Color & color)
 {
     image->setTintColor(color);
 }
Referenced by parse().
setValue()
void inet::IndexedImageFigure::setValue (int series, simtime_t timestamp, double value) override virtual
Implements inet::IIndicatorFigure.
 {
     ASSERT(series == 0);
     // Note: we currently ignore timestamp
     if (value != newValue) {
         value = newValue;
         refresh();
     }
 }
Referenced by parse(), and inet::visualizer::RadioCanvasVisualizer::setImageIndex().
Member Data Documentation
image
cImageFigure* inet::IndexedImageFigure::image private
Referenced by addChildren(), getAnchor(), getInterpolation(), getLabelOffset(), getOpacity(), getPos(), getSize(), getTintAmount(), getTintColor(), refresh(), setAnchor(), setInterpolation(), setLabelOffset(), setOpacity(), setPos(), setSize(), setTintAmount(), and setTintColor().
images
std::vector<std::string> inet::IndexedImageFigure::images private
Referenced by getImages(), refresh(), and setImages().
labelFigure
cTextFigure* inet::IndexedImageFigure::labelFigure private
Referenced by addChildren(), getLabel(), getLabelColor(), getLabelFont(), getLabelOffset(), setLabel(), setLabelColor(), setLabelFont(), and setLabelOffset().
value
double inet::IndexedImageFigure::value = NaN private
Referenced by refresh(), and setValue().
The documentation for this class was generated from the following files:
IndexedImageFigure.h
IndexedImageFigure.cc