INET Framework for OMNeT++/OMNEST: inet::Macho::Alias Class Reference
inet::Macho::Alias Class Reference
#include <Macho.h>
Public Member Functions
Alias (Key key, bool history=false)
Alias (Key key, _Initializer *init)
Alias (const Alias &other)
Alias & operator= (const Alias &other)
~Alias ()
operator Key () const
bool isChild (Key k) const
bool isParent (Key k) const
const char * name () const
ID id () const
Protected Member Functions
void setState (_MachineBase &machine) const
_KeyData * key () const
Protected Attributes
Key myStateKey
_Initializer * myInitializer
Friends
class _MachineBase
class _StateSpecification
Constructor & Destructor Documentation
Alias() [1/3]
inet::Macho::Alias::Alias (Key key, bool history = false) inline explicit
         : myStateKey(key)
         , myInitializer(history ? static_cast<_Initializer *>(&_theHistoryInitializer) : static_cast<_Initializer *>(&_theDefaultInitializer))
     {
         assert(key);
     }
Alias() [2/3]
inet::Macho::Alias::Alias (Key key, _Initializer * init) inline
         : myStateKey(key)
         , myInitializer(init)
     {
         assert(key);
     }
Alias() [3/3]
inet::Macho::Alias::Alias (const Alias & other) inline
         : myStateKey(other.myStateKey)
         , myInitializer(other.myInitializer->clone())
     {}
~Alias()
inet::Macho::Alias::~Alias () inline
     {
         myInitializer->destroy();
     }
Member Function Documentation
id()
ID inet::Macho::Alias::id () const inline
     {
         return key()->id;
     }
isChild()
bool inet::Macho::Alias::isChild (Key k) const inline
     {
         return key()->childPredicate(k);
     }
Referenced by inet::Macho::MachoLink< C, P >::isCurrent().
isParent()
bool inet::Macho::Alias::isParent (Key k) const inline
     {
         return static_cast<_KeyData *>(k)->childPredicate(key());
     }
key()
_KeyData* inet::Macho::Alias::key () const inline protected
 { return static_cast<_KeyData *>(myInitializer->adapt(myStateKey)); }
Referenced by Alias(), id(), isChild(), isParent(), name(), operator Key(), and setState().
name()
const char* inet::Macho::Alias::name () const inline
     {
         return key()->name();
     }
operator Key()
inet::Macho::Alias::operator Key () const inline
     {
         return key();
     }
operator=()
Alias& inet::Macho::Alias::operator= (const Alias & other) inline
     {
         if (this == &other) return *this;
         myInitializer->destroy();
         myStateKey = other.myStateKey;
         myInitializer = other.myInitializer->clone();
         return *this;
     }
setState()
void inet::Alias::setState (_MachineBase & machine) const protected
 {
     machine.setPendingState(key()->instanceGenerator(machine), myInitializer->clone());
 }
Referenced by inet::Macho::_MachineBase::setState().
Friends And Related Function Documentation
_MachineBase
friend class _MachineBase friend
_StateSpecification
friend class _StateSpecification friend
Member Data Documentation
myInitializer
_Initializer* inet::Macho::Alias::myInitializer protected
Referenced by key(), operator=(), setState(), and ~Alias().
myStateKey
Key inet::Macho::Alias::myStateKey protected
Referenced by key(), and operator=().
The documentation for this class was generated from the following files:
Macho.h
Macho.cc