INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211HtPreambleMode Class Reference
inet::physicallayer::Ieee80211HtPreambleMode Class Reference
#include <Ieee80211HtMode.h>
Public Types
enum HighTroughputPreambleFormat { HT_PREAMBLE_MIXED, HT_PREAMBLE_GREENFIELD }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
Ieee80211HtPreambleMode (const Ieee80211HtSignalMode *highThroughputSignalMode, const Ieee80211OfdmSignalMode *legacySignalMode, HighTroughputPreambleFormat preambleFormat, unsigned int numberOfSpatialStream)
virtual ~Ieee80211HtPreambleMode ()
HighTroughputPreambleFormat getPreambleFormat () const
virtual const Ieee80211HtSignalMode * getSignalMode () const
virtual const Ieee80211OfdmSignalMode * getLegacySignalMode () const
virtual const Ieee80211HtSignalMode * getHighThroughputSignalMode () const
virtual const simtime_t getDoubleGIDuration () const
virtual const simtime_t getLSIGDuration () const
virtual const simtime_t getNonHTShortTrainingSequenceDuration () const
virtual const simtime_t getHTGreenfieldShortTrainingFieldDuration () const
virtual const simtime_t getNonHTLongTrainingFieldDuration () const
virtual const simtime_t getHTShortTrainingFieldDuration () const
virtual const simtime_t getFirstHTLongTrainingFieldDuration () const
virtual const simtime_t getSecondAndSubsequentHTLongTrainingFielDuration () const
virtual unsigned int getNumberOfHtLongTrainings () const
virtual const simtime_t getDuration () const override
virtual Ptr< Ieee80211PhyPreamble > createPreamble () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211HtTimingRelatedParametersBase
const simtime_t getDFTPeriod () const
const simtime_t getGIDuration () const
const simtime_t getShortGIDuration () const
const simtime_t getSymbolInterval () const
const simtime_t getShortGISymbolInterval () const
Protected Member Functions
virtual unsigned int computeNumberOfSpaceTimeStreams (unsigned int numberOfSpatialStreams) const
virtual unsigned int computeNumberOfHTLongTrainings (unsigned int numberOfSpaceTimeStreams) const
Protected Attributes
const Ieee80211HtSignalMode * highThroughputSignalMode
const Ieee80211OfdmSignalMode * legacySignalMode
const HighTroughputPreambleFormat preambleFormat
const unsigned int numberOfHTLongTrainings
Member Enumeration Documentation
HighTroughputPreambleFormat
enum inet::physicallayer::Ieee80211HtPreambleMode::HighTroughputPreambleFormat
Enumerator
HT_PREAMBLE_MIXED
HT_PREAMBLE_GREENFIELD
{
         HT_PREAMBLE_MIXED, // can be received by non-HT STAs compliant with Clause 18 or Clause 19
         HT_PREAMBLE_GREENFIELD // all of the non-HT fields are omitted
     };
Constructor & Destructor Documentation
Ieee80211HtPreambleMode()
inet::physicallayer::Ieee80211HtPreambleMode::Ieee80211HtPreambleMode (const Ieee80211HtSignalMode * highThroughputSignalMode, const Ieee80211OfdmSignalMode * legacySignalMode, HighTroughputPreambleFormat preambleFormat, unsigned int numberOfSpatialStream)
                                                                                                                                                                                                                                        :
     highThroughputSignalMode(highThroughputSignalMode),
     legacySignalMode(legacySignalMode),
     preambleFormat(preambleFormat),
     numberOfHTLongTrainings(computeNumberOfHTLongTrainings(computeNumberOfSpaceTimeStreams(numberOfSpatialStream)))
 {
 }
~Ieee80211HtPreambleMode()
virtual inet::physicallayer::Ieee80211HtPreambleMode::~Ieee80211HtPreambleMode () inline virtual
 { delete highThroughputSignalMode; }
Member Function Documentation
computeNumberOfHTLongTrainings()
unsigned int inet::physicallayer::Ieee80211HtPreambleMode::computeNumberOfHTLongTrainings (unsigned int numberOfSpaceTimeStreams) const protected virtual
 {
     // If the transmitter is providing training for exactly the space-time
     // streams (spatial mapper inputs) used for the transmission of the PSDU,
     // the number of training symbols, N_LTF, is equal to the number of space-time
     // streams, N STS, except that for three space-time streams, four training symbols
     // are required.
     return numberOfSpaceTimeStreams == 3 ? 4 : numberOfSpaceTimeStreams;
 }
computeNumberOfSpaceTimeStreams()
unsigned int inet::physicallayer::Ieee80211HtPreambleMode::computeNumberOfSpaceTimeStreams (unsigned int numberOfSpatialStreams) const protected virtual
 {
     // Table 20-12—Determining the number of space-time streams
     return numberOfSpatialStreams + highThroughputSignalMode->getSTBC();
 }
createPreamble()
virtual Ptr<Ieee80211PhyPreamble> inet::physicallayer::Ieee80211HtPreambleMode::createPreamble () const inline override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 { return makeShared<Ieee80211HtPhyPreamble>(); }
getDoubleGIDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getDoubleGIDuration () const inline virtual
 { return 2 * getGIDuration(); } // GI2
getDuration()
const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getDuration () const override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 {
     // 20.3.7 Mathematical description of signals
     simtime_t sumOfHTLTFs = getFirstHTLongTrainingFieldDuration() + getSecondAndSubsequentHTLongTrainingFielDuration() * (numberOfHTLongTrainings - 1);
     if (preambleFormat == HT_PREAMBLE_MIXED)
         // L-STF -> L-LTF -> L-SIG -> HT-SIG -> HT-STF -> HT-LTF1 -> HT-LTF2 -> ... -> HT_LTFn
         return getNonHTShortTrainingSequenceDuration() + getNonHTLongTrainingFieldDuration() + legacySignalMode->getDuration() + highThroughputSignalMode->getDuration() + getHTShortTrainingFieldDuration() + sumOfHTLTFs;
     else if (preambleFormat == HT_PREAMBLE_GREENFIELD)
         // HT-GF-STF -> HT-LTF1 -> HT-SIG -> HT-LTF2 -> ... -> HT-LTFn
         return getHTGreenfieldShortTrainingFieldDuration() + highThroughputSignalMode->getDuration() + sumOfHTLTFs;
     else
         throw cRuntimeError("Unknown preamble format");
 }
Referenced by inet::physicallayer::Ieee80211HtMode::getDuration().
getFirstHTLongTrainingFieldDuration()
const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getFirstHTLongTrainingFieldDuration () const virtual
 {
     if (preambleFormat == HT_PREAMBLE_MIXED)
         return simtime_t(4E-6);
     else if (preambleFormat == HT_PREAMBLE_GREENFIELD)
         return simtime_t(8E-6);
     else
         throw cRuntimeError("Unknown preamble format");
 }
Referenced by getDuration().
getHighThroughputSignalMode()
virtual const Ieee80211HtSignalMode* inet::physicallayer::Ieee80211HtPreambleMode::getHighThroughputSignalMode () const inline virtual
 { return highThroughputSignalMode; }
getHTGreenfieldShortTrainingFieldDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getHTGreenfieldShortTrainingFieldDuration () const inline virtual
 { return 10 * getDFTPeriod() / 4; } // HT-GF-STF
Referenced by getDuration().
getHTShortTrainingFieldDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getHTShortTrainingFieldDuration () const inline virtual
 { return 4E-6; } // HT-STF
Referenced by getDuration().
getLegacySignalMode()
virtual const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211HtPreambleMode::getLegacySignalMode () const inline virtual
 { return legacySignalMode; }
Referenced by inet::physicallayer::Ieee80211HtMode::getLegacySignalMode().
getLSIGDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getLSIGDuration () const inline virtual
 { return getSymbolInterval(); } // L-SIG
getNonHTLongTrainingFieldDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getNonHTLongTrainingFieldDuration () const inline virtual
 { return 2 * getDFTPeriod() + getDoubleGIDuration(); } // L-LTF
Referenced by getDuration().
getNonHTShortTrainingSequenceDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getNonHTShortTrainingSequenceDuration () const inline virtual
 { return 10 * getDFTPeriod() / 4; } // L-STF
Referenced by getDuration().
getNumberOfHtLongTrainings()
virtual unsigned int inet::physicallayer::Ieee80211HtPreambleMode::getNumberOfHtLongTrainings () const inline virtual
 { return numberOfHTLongTrainings; }
getPreambleFormat()
HighTroughputPreambleFormat inet::physicallayer::Ieee80211HtPreambleMode::getPreambleFormat () const inline
 { return preambleFormat; }
getSecondAndSubsequentHTLongTrainingFielDuration()
virtual const simtime_t inet::physicallayer::Ieee80211HtPreambleMode::getSecondAndSubsequentHTLongTrainingFielDuration () const inline virtual
 { return 4E-6; } // HT-LTFs, s = 2,3,..,n
Referenced by getDuration().
getSignalMode()
virtual const Ieee80211HtSignalMode* inet::physicallayer::Ieee80211HtPreambleMode::getSignalMode () const inline virtual
 { return highThroughputSignalMode; }
Referenced by inet::physicallayer::Ieee80211HtMode::getHeaderMode().
Member Data Documentation
highThroughputSignalMode
const Ieee80211HtSignalMode* inet::physicallayer::Ieee80211HtPreambleMode::highThroughputSignalMode protected
Referenced by computeNumberOfSpaceTimeStreams(), and getDuration().
legacySignalMode
const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211HtPreambleMode::legacySignalMode protected
Referenced by getDuration().
numberOfHTLongTrainings
const unsigned int inet::physicallayer::Ieee80211HtPreambleMode::numberOfHTLongTrainings protected
Referenced by getDuration().
preambleFormat
const HighTroughputPreambleFormat inet::physicallayer::Ieee80211HtPreambleMode::preambleFormat protected
Referenced by getDuration(), and getFirstHTLongTrainingFieldDuration().
The documentation for this class was generated from the following files:
Ieee80211HtMode.h
Ieee80211HtMode.cc