INET Framework for OMNeT++/OMNEST: inet::physicallayer::IPathLoss Class Reference
inet::physicallayer::IPathLoss Class Reference abstract
This interface models path loss (or path attenuation) that is the reduction in power density of a radio signal as it propagates through space.
#include <IPathLoss.h>
Public Member Functions
virtual double computePathLoss (const ITransmission *transmission, const IArrival *arrival) const =0
Returns the loss factor for the provided transmission and arrival.
virtual double computePathLoss (mps propagationSpeed, Hz frequency, m distance) const =0
Returns the loss factor as a function of propagation speed, carrier frequency and distance.
virtual m computeRange (mps propagationSpeed, Hz frequency, double loss) const =0
Returns the range for the given loss factor.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface models path loss (or path attenuation) that is the reduction in power density of a radio signal as it propagates through space.
Member Function Documentation
computePathLoss() [1/2]
virtual double inet::physicallayer::IPathLoss::computePathLoss (const ITransmission * transmission, const IArrival * arrival) const pure virtual
Returns the loss factor for the provided transmission and arrival.
The value is in the range [0, 1] where 1 means no loss at all and 0 means all power is lost.
Implemented in inet::physicallayer::TwoRayGroundReflection, inet::physicallayer::PathLossBase, and inet::physicallayer::TwoRayInterference.
Referenced by inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower(), inet::physicallayer::FrequencyDependentAttenuationFunction::getValue(), and inet::physicallayer::PathLossFunction::getValue().
computePathLoss() [2/2]
virtual double inet::physicallayer::IPathLoss::computePathLoss (mps propagationSpeed, Hz frequency, m distance) const pure virtual
Returns the loss factor as a function of propagation speed, carrier frequency and distance.
The value is in the range [0, 1] where 1 means no loss at all and 0 means all power is lost.
Implemented in inet::physicallayer::PathLossBase, inet::physicallayer::UwbIrStochasticPathLoss, inet::physicallayer::SuiPathLoss, inet::physicallayer::FreeSpacePathLoss, inet::physicallayer::RicianFading, inet::physicallayer::NakagamiFading, inet::physicallayer::RayleighFading, inet::physicallayer::LogNormalShadowing, inet::physicallayer::BreakpointPathLoss, and inet::physicallayer::TwoRayInterference.
computeRange()
virtual m inet::physicallayer::IPathLoss::computeRange (mps propagationSpeed, Hz frequency, double loss) const pure virtual
Returns the range for the given loss factor.
The value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::UwbIrStochasticPathLoss, inet::physicallayer::SuiPathLoss, inet::physicallayer::FreeSpacePathLoss, inet::physicallayer::BreakpointPathLoss, and inet::physicallayer::TwoRayInterference.
Referenced by inet::physicallayer::MediumLimitCache::computeMaxRange().
The documentation for this class was generated from the following file:
IPathLoss.h