INET Framework for OMNeT++/OMNEST: inet::Ipv6InterfaceData Class Reference
inet::Ipv6InterfaceData Class Reference
Ipv6-specific data for NetworkInterface.
#include <Ipv6InterfaceData.h>
Classes
struct AddressData
struct AdvPrefix
For routers: advertised prefix configuration.
struct HostConstants
struct HostMulticastData
struct HostVariables
struct NodeConstants
struct NodeVariables
struct RouterConstants
struct RouterMulticastData
struct RouterVariables
Public Types
enum { F_IP_ADDRESS, F_MULTICAST_ADDRESSES, F_MULTICAST_LISTENERS }
typedef std::vector< Ipv6Address > Ipv6AddressVector
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
Ipv6InterfaceData ()
virtual ~Ipv6InterfaceData ()
std::string str () const override
std::string detailedInfo () const
Addresses
virtual void assignAddress (const Ipv6Address &addr, bool tentative, simtime_t expiryTime, simtime_t prefExpiryTime)
Assigns the given address to the interface.
virtual void updateMatchingAddressExpiryTimes (const Ipv6Address &prefix, int length, simtime_t expiryTime=SIMTIME_ZERO, simtime_t prefExpiryTime=SIMTIME_ZERO)
Update expiry times of addresses.
int getNumAddresses () const
Returns the number of addresses the interface has.
const Ipv6Address & getAddress (int i) const
Returns ith address of the interface.
const Ipv6Address & getGlblAddress () const
bool isTentativeAddress (int i) const
Returns true if the ith address of the interface is tentative.
bool hasAddress (const Ipv6Address &addr) const
Returns true if the given address is one of the addresses assigned, regardless whether it is tentative or not.
bool matchesSolicitedNodeMulticastAddress (const Ipv6Address &solNodeAddr) const
Returns true if the interface has an address matching the given solicited-node multicast addresses.
bool isTentativeAddress (const Ipv6Address &addr) const
Returns true if the interface has the given address and it is tentative.
virtual void permanentlyAssign (const Ipv6Address &addr)
Clears the "tentative" flag of an existing interface address.
const Ipv6AddressVector & getJoinedMulticastGroups () const
const Ipv6AddressVector & getReportedMulticastGroups () const
bool isMemberOfMulticastGroup (const Ipv6Address &multicastAddress) const
virtual void joinMulticastGroup (const Ipv6Address &multicastAddress)
virtual void leaveMulticastGroup (const Ipv6Address &multicastAddress)
bool hasMulticastListener (const Ipv6Address &multicastAddress) const
virtual void addMulticastListener (const Ipv6Address &multicastAddress)
virtual void removeMulticastListener (const Ipv6Address &multicastAddress)
const Ipv6Address & getPreferredAddress () const
Chooses a preferred address for the interface and returns it.
const Ipv6Address & getLinkLocalAddress () const
Returns the first valid link-local address of the interface, or UNSPECIFIED_ADDRESS if there's none.
virtual void removeAddress (const Ipv6Address &address)
Removes the address.
simtime_t _getMaxInitialRtrAdvertInterval () const
Getters/Setters for all variables and constants defined in RFC 2461/2462 can be found here.
uint _getMaxInitialRtrAdvertisements () const
uint _getMaxFinalRtrAdvertisements () const
simtime_t _getMinDelayBetweenRAs () const
simtime_t _getMaxRaDelayTime () const
virtual void _setMaxInitialRtrAdvertInterval (simtime_t d)
virtual void _setMaxInitialRtrAdvertisements (uint d)
virtual void _setMaxFinalRtrAdvertisements (uint d)
virtual void _setMinDelayBetweenRAs (simtime_t d)
virtual void _setMaxRaDelayTime (simtime_t d)
simtime_t _getMaxRtrSolicitationDelay () const
simtime_t _getRtrSolicitationInterval () const
uint _getMaxRtrSolicitations () const
virtual void _setMaxRtrSolicitationDelay (simtime_t d)
virtual void _setRtrSolicitationInterval (simtime_t d)
virtual void _setMaxRtrSolicitations (uint d)
uint _getMaxMulticastSolicit () const
uint _getMaxUnicastSolicit () const
simtime_t _getMaxAnycastDelayTime () const
uint _getMaxNeighbourAdvertisement () const
simtime_t _getReachableTime () const
simtime_t _getRetransTimer () const
simtime_t _getDelayFirstProbeTime () const
double _getMinRandomFactor () const
double _getMaxRandomFactor () const
virtual void _setMaxMulticastSolicit (uint d)
virtual void _setMaxUnicastSolicit (uint d)
virtual void _setMaxAnycastDelayTime (simtime_t d)
virtual void _setMaxNeighbourAdvertisement (uint d)
virtual void _setReachableTime (simtime_t d)
virtual void _setRetransTimer (simtime_t d)
virtual void _setDelayFirstProbeTime (simtime_t d)
virtual void _setMinRandomFactor (double d)
virtual void _setMaxRandomFactor (double d)
int getDupAddrDetectTransmits () const
virtual void setDupAddrDetectTransmits (int d)
uint getLinkMtu () const
short getCurHopLimit () const
uint getBaseReachableTime () const
simtime_t getReachableTime () const
uint getRetransTimer () const
virtual void setLinkMtu (uint d)
virtual void setCurHopLimit (short d)
virtual void setBaseReachableTime (uint d)
virtual void setReachableTime (simtime_t d)
virtual void setRetransTimer (uint d)
bool getAdvSendAdvertisements () const
simtime_t getMaxRtrAdvInterval () const
simtime_t getMinRtrAdvInterval () const
bool getAdvManagedFlag () const
bool getAdvOtherConfigFlag () const
int getAdvLinkMtu () const
int getAdvReachableTime () const
int getAdvRetransTimer () const
short getAdvCurHopLimit () const
simtime_t getAdvDefaultLifetime () const
virtual void setAdvSendAdvertisements (bool d)
virtual void setMaxRtrAdvInterval (simtime_t d)
virtual void setMinRtrAdvInterval (simtime_t d)
virtual void setAdvManagedFlag (bool d)
virtual void setAdvOtherConfigFlag (bool d)
virtual void setAdvLinkMtu (int d)
virtual void setAdvReachableTime (int d)
virtual void setAdvRetransTimer (int d)
virtual void setAdvCurHopLimit (short d)
virtual void setAdvDefaultLifetime (simtime_t d)
Router advertised prefixes
virtual void addAdvPrefix (const AdvPrefix &advPrefix)
Adds the given advertised prefix to the interface.
int getNumAdvPrefixes () const
Returns the number of advertised prefixes on the interface.
const AdvPrefix & getAdvPrefix (int i) const
Returns the ith advertised prefix on the interface.
virtual void setAdvPrefix (int i, const AdvPrefix &advPrefix)
Changes the configuration of the ith advertised prefix on the interface.
virtual void removeAdvPrefix (int i)
Remove the ith advertised prefix on the interface.
virtual simtime_t generateReachableTime (double MIN_RANDOM_FACTOR, double MAX_RANDOM_FACTOR, uint baseReachableTime)
This method randomly generates a reachableTime given the MIN_RANDOM_FACTOR MAX_RANDOM_FACTOR and baseReachableTime.
virtual simtime_t generateReachableTime ()
Arg-less version.
Public Member Functions inherited from inet::InterfaceProtocolData
InterfaceProtocolData (int id)
NetworkInterface * getNetworkInterface () const
Returns the NetworkInterface that contains this data object, or nullptr.
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Attributes
RouterConstants routerConstants
HostConstants hostConstants
NodeConstants nodeConstants
Protected Types
typedef std::vector< AddressData > AddressDataVector
typedef std::vector< AdvPrefix > AdvPrefixList
Protected Member Functions
int findAddress (const Ipv6Address &addr) const
void choosePreferredAddress ()
void changed1 (int fieldId)
HostMulticastData * getHostData ()
const HostMulticastData * getHostData () const
RouterMulticastData * getRouterData ()
const RouterMulticastData * getRouterData () const
Protected Member Functions inherited from inet::InterfaceProtocolData
virtual void changed (simsignal_t signalID, int fieldId)
Static Protected Member Functions
static bool addrLess (const AddressData &a, const AddressData &b)
Protected Attributes
HostMulticastData * hostMcastData = nullptr
RouterMulticastData * routerMcastData = nullptr
AddressDataVector addresses
Ipv6Address preferredAddr
simtime_t preferredAddrExpiryTime
NodeVariables nodeVars
HostVariables hostVars
RouterVariables rtrVars
Protected Attributes inherited from inet::InterfaceProtocolData
NetworkInterface * ownerp = nullptr
int id
Detailed Description
Ipv6-specific data for NetworkInterface.
Most of this comes from section 6.2.1 of RFC 2461 (Ipv6 Neighbor Discovery, Router Configuration Variables).
Member Typedef Documentation
AddressDataVector
typedef std::vector<AddressData> inet::Ipv6InterfaceData::AddressDataVector protected
AdvPrefixList
typedef std::vector<AdvPrefix> inet::Ipv6InterfaceData::AdvPrefixList protected
Ipv6AddressVector
typedef std::vector<Ipv6Address> inet::Ipv6InterfaceData::Ipv6AddressVector
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
F_IP_ADDRESS
F_MULTICAST_ADDRESSES
F_MULTICAST_LISTENERS
 { F_IP_ADDRESS, F_MULTICAST_ADDRESSES, F_MULTICAST_LISTENERS }; // FIXME missed field IDs and missed notifications in setter functions
Constructor & Destructor Documentation
Ipv6InterfaceData()
inet::Ipv6InterfaceData::Ipv6InterfaceData ()
     : InterfaceProtocolData(NetworkInterface::F_IPV6_DATA)
 {
 #ifdef INET_WITH_xMIPv6
 //    rt6 = IPv6RoutingTableAccess().get();
 #endif /* INET_WITH_xMIPv6 */
     /*******************Setting host/node/router Protocol Constants************/
     routerConstants.maxInitialRtrAdvertInterval = IPv6_MAX_INITIAL_RTR_ADVERT_INTERVAL;
     routerConstants.maxInitialRtrAdvertisements = IPv6_MAX_INITIAL_RTR_ADVERTISEMENTS;
     routerConstants.maxFinalRtrAdvertisements = IPv6_MAX_FINAL_RTR_ADVERTISEMENTS;
     routerConstants.minDelayBetweenRAs = IPv6_MIN_DELAY_BETWEEN_RAS;
     routerConstants.maxRADelayTime = IPv6_MAX_RA_DELAY_TIME;
     hostConstants.maxRtrSolicitationDelay = IPv6_MAX_RTR_SOLICITATION_DELAY;
     hostConstants.rtrSolicitationInterval = IPv6_RTR_SOLICITATION_INTERVAL;
     hostConstants.maxRtrSolicitations = IPv6_MAX_RTR_SOLICITATIONS;
 #ifdef INET_WITH_xMIPv6
     hostConstants.initialBindAckTimeout = MIPv6_INITIAL_BINDACK_TIMEOUT; // MIPv6: added by Zarrar Yousaf @ CNI UniDo 17.06.07
     hostConstants.maxBindAckTimeout = MIPv6_MAX_BINDACK_TIMEOUT; // MIPv6: added by Zarrar Yousaf @ CNI UniDo 17.06.07
     hostConstants.initialBindAckTimeoutFirst = MIPv6_INITIAL_BINDACK_TIMEOUT_FIRST; // MIPv6: 12.9.07 - CB
     hostConstants.maxRRBindingLifeTime = MIPv6_MAX_RR_BINDING_LIFETIME; // 14.9.07 - CB
     hostConstants.maxHABindingLifeTime = MIPv6_MAX_HA_BINDING_LIFETIME; // 14.9.07 - CB
     hostConstants.maxTokenLifeTime = MIPv6_MAX_TOKEN_LIFETIME; // 14.9.07 - CB
 #endif /* INET_WITH_xMIPv6 */
     nodeConstants.maxMulticastSolicit = IPv6_MAX_MULTICAST_SOLICIT;
     nodeConstants.maxUnicastSolicit = IPv6_MAX_UNICAST_SOLICIT;
     nodeConstants.maxAnycastDelayTime = IPv6_MAX_ANYCAST_DELAY_TIME;
     nodeConstants.maxNeighbourAdvertisement = IPv6_MAX_NEIGHBOUR_ADVERTISEMENT;
     nodeConstants.reachableTime = IPv6_REACHABLE_TIME;
     nodeConstants.retransTimer = IPv6_RETRANS_TIMER;
     nodeConstants.delayFirstProbeTime = IPv6_DELAY_FIRST_PROBE_TIME;
     nodeConstants.minRandomFactor = IPv6_MIN_RANDOM_FACTOR;
     nodeConstants.maxRandomFactor = IPv6_MAX_RANDOM_FACTOR;
     /*******************Setting host/node/router variables*********************/
     nodeVars.dupAddrDetectTransmits = IPv6_DEFAULT_DUPADDRDETECTTRANSMITS;
     hostVars.linkMTU = IPv6_MIN_MTU;
     hostVars.curHopLimit = IPv6_DEFAULT_ADVCURHOPLIMIT; // value specified in RFC 1700-can't find it
     hostVars.baseReachableTime = IPv6_REACHABLE_TIME;
     hostVars.reachableTime = generateReachableTime(_getMinRandomFactor(),
                 _getMaxRandomFactor(), getBaseReachableTime());
     hostVars.retransTimer = IPv6_RETRANS_TIMER;
     // rtrVars.advSendAdvertisements is set in Ipv6RoutingTable.cc:line 143
     rtrVars.maxRtrAdvInterval = IPv6_DEFAULT_MAX_RTR_ADV_INT;
     rtrVars.minRtrAdvInterval = 0.33 * rtrVars.maxRtrAdvInterval;
     rtrVars.advManagedFlag = false;
     rtrVars.advOtherConfigFlag = false;
 #ifdef INET_WITH_xMIPv6
     rtrVars.advHomeAgentFlag = false; // Zarrar Yousaf Feb-March 2007
 #endif /* INET_WITH_xMIPv6 */
     rtrVars.advLinkMTU = IPv6_MIN_MTU;
     rtrVars.advReachableTime = IPv6_DEFAULT_ADV_REACHABLE_TIME;
     rtrVars.advRetransTimer = IPv6_DEFAULT_ADV_RETRANS_TIMER;
     rtrVars.advCurHopLimit = IPv6_DEFAULT_ADVCURHOPLIMIT;
     rtrVars.advDefaultLifetime = 3 * rtrVars.maxRtrAdvInterval;
 #if USE_MOBILITY
     if (rtrVars.advDefaultLifetime < 1)
         rtrVars.advDefaultLifetime = 1;
 #endif // if USE_MOBILITY
 }
~Ipv6InterfaceData()
inet::Ipv6InterfaceData::~Ipv6InterfaceData () virtual
 {
     delete hostMcastData;
     delete routerMcastData;
 }
Member Function Documentation
_getDelayFirstProbeTime()
simtime_t inet::Ipv6InterfaceData::_getDelayFirstProbeTime () const inline
 { return nodeConstants.delayFirstProbeTime; }
Referenced by inet::Ipv6NeighbourDiscovery::initiateNeighbourUnreachabilityDetection().
_getMaxAnycastDelayTime()
simtime_t inet::Ipv6InterfaceData::_getMaxAnycastDelayTime () const inline
 { return nodeConstants.maxAnycastDelayTime; }
_getMaxFinalRtrAdvertisements()
uint inet::Ipv6InterfaceData::_getMaxFinalRtrAdvertisements () const inline
 { return routerConstants.maxFinalRtrAdvertisements; }
_getMaxInitialRtrAdvertInterval()
simtime_t inet::Ipv6InterfaceData::_getMaxInitialRtrAdvertInterval () const inline
Getters/Setters for all variables and constants defined in RFC 2461/2462 can be found here.
Operations responsible for protocol constants are marked with a "_" prefix. Constants in this class are stored as instance variables. Default values for certain variables are defined at the top of this file, while certain variables have to be generated. Protocol constants are subject to change as specified in RFC2461:section 10 depending on different link layer operation. Getters and setters have been implemented for protocol constants so that a wireless interface may be set to a different set of constant values. (ie. changed by the Ipv4FlatNetworkConfigurator) Such a design allows both wired and wireless networks to co-exist within a simulation run.
 { return routerConstants.maxInitialRtrAdvertInterval; }
Referenced by inet::Ipv6NeighbourDiscovery::sendPeriodicRa().
_getMaxInitialRtrAdvertisements()
uint inet::Ipv6InterfaceData::_getMaxInitialRtrAdvertisements () const inline
 { return routerConstants.maxInitialRtrAdvertisements; }
Referenced by inet::Ipv6NeighbourDiscovery::sendPeriodicRa().
_getMaxMulticastSolicit()
uint inet::Ipv6InterfaceData::_getMaxMulticastSolicit () const inline
 { return nodeConstants.maxMulticastSolicit; }
Referenced by inet::Ipv6NeighbourDiscovery::processArTimeout().
_getMaxNeighbourAdvertisement()
uint inet::Ipv6InterfaceData::_getMaxNeighbourAdvertisement () const inline
 { return nodeConstants.maxNeighbourAdvertisement; }
_getMaxRaDelayTime()
simtime_t inet::Ipv6InterfaceData::_getMaxRaDelayTime () const inline
 { return routerConstants.maxRADelayTime; }
Referenced by inet::Ipv6NeighbourDiscovery::processRsPacket().
_getMaxRandomFactor()
double inet::Ipv6InterfaceData::_getMaxRandomFactor () const inline
 { return nodeConstants.maxRandomFactor; }
Referenced by generateReachableTime(), and Ipv6InterfaceData().
_getMaxRtrSolicitationDelay()
simtime_t inet::Ipv6InterfaceData::_getMaxRtrSolicitationDelay () const inline
 { return hostConstants.maxRtrSolicitationDelay; }
Referenced by inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent(), and inet::Ipv6NeighbourDiscovery::processRdTimeout().
_getMaxRtrSolicitations()
uint inet::Ipv6InterfaceData::_getMaxRtrSolicitations () const inline
 { return hostConstants.maxRtrSolicitations; }
Referenced by inet::Ipv6NeighbourDiscovery::processRdTimeout().
_getMaxUnicastSolicit()
uint inet::Ipv6InterfaceData::_getMaxUnicastSolicit () const inline
 { return nodeConstants.maxUnicastSolicit; }
Referenced by inet::Ipv6NeighbourDiscovery::processNudTimeout().
_getMinDelayBetweenRAs()
simtime_t inet::Ipv6InterfaceData::_getMinDelayBetweenRAs () const inline
 { return routerConstants.minDelayBetweenRAs; }
_getMinRandomFactor()
double inet::Ipv6InterfaceData::_getMinRandomFactor () const inline
 { return nodeConstants.minRandomFactor; }
Referenced by generateReachableTime(), and Ipv6InterfaceData().
_getReachableTime()
simtime_t inet::Ipv6InterfaceData::_getReachableTime () const inline
 { return nodeConstants.reachableTime; }
_getRetransTimer()
simtime_t inet::Ipv6InterfaceData::_getRetransTimer () const inline
 { return nodeConstants.retransTimer; }
Referenced by inet::Ipv6NeighbourDiscovery::initiateAddressResolution(), inet::Ipv6NeighbourDiscovery::processArTimeout(), and inet::Ipv6NeighbourDiscovery::processNudTimeout().
_getRtrSolicitationInterval()
simtime_t inet::Ipv6InterfaceData::_getRtrSolicitationInterval () const inline
 { return hostConstants.rtrSolicitationInterval; }
Referenced by inet::Ipv6NeighbourDiscovery::initiateRouterDiscovery(), and inet::Ipv6NeighbourDiscovery::processRdTimeout().
_setDelayFirstProbeTime()
virtual void inet::Ipv6InterfaceData::_setDelayFirstProbeTime (simtime_t d) inline virtual
 { nodeConstants.delayFirstProbeTime = d; }
_setMaxAnycastDelayTime()
virtual void inet::Ipv6InterfaceData::_setMaxAnycastDelayTime (simtime_t d) inline virtual
 { nodeConstants.maxAnycastDelayTime = d; }
_setMaxFinalRtrAdvertisements()
virtual void inet::Ipv6InterfaceData::_setMaxFinalRtrAdvertisements (uint d) inline virtual
 { routerConstants.maxFinalRtrAdvertisements = d; }
_setMaxInitialRtrAdvertInterval()
virtual void inet::Ipv6InterfaceData::_setMaxInitialRtrAdvertInterval (simtime_t d) inline virtual
 { routerConstants.maxInitialRtrAdvertInterval = d; }
_setMaxInitialRtrAdvertisements()
virtual void inet::Ipv6InterfaceData::_setMaxInitialRtrAdvertisements (uint d) inline virtual
 { routerConstants.maxInitialRtrAdvertisements = d; }
_setMaxMulticastSolicit()
virtual void inet::Ipv6InterfaceData::_setMaxMulticastSolicit (uint d) inline virtual
 { nodeConstants.maxMulticastSolicit = d; }
_setMaxNeighbourAdvertisement()
virtual void inet::Ipv6InterfaceData::_setMaxNeighbourAdvertisement (uint d) inline virtual
 { nodeConstants.maxNeighbourAdvertisement = d; }
_setMaxRaDelayTime()
virtual void inet::Ipv6InterfaceData::_setMaxRaDelayTime (simtime_t d) inline virtual
 { routerConstants.maxRADelayTime = d; }
_setMaxRandomFactor()
virtual void inet::Ipv6InterfaceData::_setMaxRandomFactor (double d) inline virtual
 { nodeConstants.maxRandomFactor = d; }
_setMaxRtrSolicitationDelay()
virtual void inet::Ipv6InterfaceData::_setMaxRtrSolicitationDelay (simtime_t d) inline virtual
 { hostConstants.maxRtrSolicitationDelay = d; }
_setMaxRtrSolicitations()
virtual void inet::Ipv6InterfaceData::_setMaxRtrSolicitations (uint d) inline virtual
 { hostConstants.maxRtrSolicitations = d; }
_setMaxUnicastSolicit()
virtual void inet::Ipv6InterfaceData::_setMaxUnicastSolicit (uint d) inline virtual
 { nodeConstants.maxUnicastSolicit = d; }
_setMinDelayBetweenRAs()
virtual void inet::Ipv6InterfaceData::_setMinDelayBetweenRAs (simtime_t d) inline virtual
 { routerConstants.minDelayBetweenRAs = d; }
_setMinRandomFactor()
virtual void inet::Ipv6InterfaceData::_setMinRandomFactor (double d) inline virtual
 { nodeConstants.minRandomFactor = d; }
_setReachableTime()
virtual void inet::Ipv6InterfaceData::_setReachableTime (simtime_t d) inline virtual
 { nodeConstants.reachableTime = d; }
_setRetransTimer()
virtual void inet::Ipv6InterfaceData::_setRetransTimer (simtime_t d) inline virtual
 { nodeConstants.retransTimer = d; }
_setRtrSolicitationInterval()
virtual void inet::Ipv6InterfaceData::_setRtrSolicitationInterval (simtime_t d) inline virtual
 { hostConstants.rtrSolicitationInterval = d; }
addAdvPrefix()
void inet::Ipv6InterfaceData::addAdvPrefix (const AdvPrefix & advPrefix) virtual
Adds the given advertised prefix to the interface.
 {
     rtrVars.advPrefixList.push_back(advPrefix);
 }
addMulticastListener()
void inet::Ipv6InterfaceData::addMulticastListener (const Ipv6Address & multicastAddress) virtual
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv6InterfaceData::addMulticastListener(): multicast address expected, received %s.", multicastAddress.str().c_str());
     if (!hasMulticastListener(multicastAddress)) {
         getRouterData()->reportedMulticastGroups.push_back(multicastAddress);
         changed1(F_MULTICAST_LISTENERS);
     }
 }
addrLess()
bool inet::Ipv6InterfaceData::addrLess (const AddressData & a, const AddressData & b) static protected
 {
     // This method is used in choosePreferredAddress().
     // sort() produces increasing order, so "better" addresses should
     // compare as "less", to make them appear first in the array
     if (a.tentative != b.tentative)
         return !a.tentative; // tentative=false is better
     if (a.address.getScope() != b.address.getScope())
         return a.address.getScope() > b.address.getScope(); // bigger scope is better
 #ifdef INET_WITH_xMIPv6
     // FIXME  check a.address.isGlobal() != b.address.isGlobal()
     if (a.address.isGlobal() && b.address.isGlobal() && a.addrType != b.addrType)
         return a.addrType == CoA; // HoA is better than CoA, 24.9.07 - CB
 #endif /* INET_WITH_xMIPv6 */
     return (a.expiryTime == SIMTIME_ZERO && b.expiryTime != SIMTIME_ZERO) || a.expiryTime > b.expiryTime; // longer expiry time is better
 }
Referenced by choosePreferredAddress().
assignAddress()
void inet::Ipv6InterfaceData::assignAddress (const Ipv6Address & addr, bool tentative, simtime_t expiryTime, simtime_t prefExpiryTime) virtual
Assigns the given address to the interface.
 {
     addresses.push_back(AddressData());
     AddressData& a = addresses.back();
     a.address = addr;
     a.tentative = tentative;
     a.expiryTime = expiryTime;
     a.prefExpiryTime = prefExpiryTime;
 #ifdef INET_WITH_xMIPv6
     if (addr.isGlobal()) { // only tag a global scope address as HoA or CoA, depending on the status of the H-Flag
         if (hFlag == true)
             a.addrType = HoA; // if H-Flag is set then the auto-conf address is the Home address -.....
         else
             a.addrType = CoA; // else it is a care of address (CoA)
     }
     // FIXME else a.addrType = ???;
 #endif /* INET_WITH_xMIPv6 */
     choosePreferredAddress();
     changed1(F_IP_ADDRESS);
 }
Referenced by inet::eigrp::EigrpIpv6Pdm::enableInterface().
changed1()
void inet::Ipv6InterfaceData::changed1 (int fieldId) inline protected
 { changed(interfaceIpv6ConfigChangedSignal, fieldId); }
Referenced by addMulticastListener(), joinMulticastGroup(), leaveMulticastGroup(), removeAddress(), and removeMulticastListener().
choosePreferredAddress()
void inet::Ipv6InterfaceData::choosePreferredAddress () protected
 {
     // do we have addresses?
     if (addresses.size() == 0) {
         preferredAddr = Ipv6Address();
         return;
     }
     // FIXME shouldn't we stick to the current preferredAddress if its prefLifetime
     // hasn't expired yet?
     // FIXME TODO throw out expired addresses! 0 should be treated as infinity
     // sort addresses by scope and expiry time, then pick the first one
     std::stable_sort(addresses.begin(), addresses.end(), addrLess);
     // choose first unicast address
     for (auto& elem : addresses) {
         if (elem.address.isUnicast()) {
             preferredAddr = elem.address;
             preferredAddrExpiryTime = elem.expiryTime;
             return;
         }
     }
     preferredAddr = Ipv6Address::UNSPECIFIED_ADDRESS;
 }
Referenced by permanentlyAssign(), removeAddress(), and updateMatchingAddressExpiryTimes().
detailedInfo()
std::string inet::Ipv6InterfaceData::detailedInfo () const
 {
     return str(); // TODO this could be improved: multi-line text, etc
 }
findAddress()
int inet::Ipv6InterfaceData::findAddress (const Ipv6Address & addr) const protected
 {
     for (AddressDataVector::const_iterator it = addresses.begin(); it != addresses.end(); it++)
         if (it->address == addr)
             return it - addresses.begin();
     return -1;
 }
Referenced by hasAddress(), isTentativeAddress(), permanentlyAssign(), and removeAddress().
generateReachableTime() [1/2]
simtime_t inet::Ipv6InterfaceData::generateReachableTime () virtual
Arg-less version.
 {
     return RNGCONTEXT uniform(_getMinRandomFactor(), _getMaxRandomFactor()) * getBaseReachableTime();
 }
Referenced by Ipv6InterfaceData().
generateReachableTime() [2/2]
simtime_t inet::Ipv6InterfaceData::generateReachableTime (double MIN_RANDOM_FACTOR, double MAX_RANDOM_FACTOR, uint baseReachableTime) virtual
This method randomly generates a reachableTime given the MIN_RANDOM_FACTOR MAX_RANDOM_FACTOR and baseReachableTime.
Refer to RFC 2461: Section 6.3.2
 {
     return RNGCONTEXT uniform(MIN_RANDOM_FACTOR, MAX_RANDOM_FACTOR) * baseReachableTime;
 }
Referenced by inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates().
getAddress()
const Ipv6Address & inet::Ipv6InterfaceData::getAddress (int i) const
Returns ith address of the interface.
 {
     ASSERT(i >= 0 && i < (int)addresses.size());
     return addresses[i].address;
 }
Referenced by inet::ospfv3::Ospfv3Process::isInInterfaceTable6(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf(), str(), and inet::InterfaceTable::updateLinkDisplayString().
getAdvCurHopLimit()
short inet::Ipv6InterfaceData::getAdvCurHopLimit () const inline
 { return rtrVars.advCurHopLimit; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvDefaultLifetime()
simtime_t inet::Ipv6InterfaceData::getAdvDefaultLifetime () const inline
 { return rtrVars.advDefaultLifetime; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvLinkMtu()
int inet::Ipv6InterfaceData::getAdvLinkMtu () const inline
 { return rtrVars.advLinkMTU; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvManagedFlag()
bool inet::Ipv6InterfaceData::getAdvManagedFlag () const inline
 { return rtrVars.advManagedFlag; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvOtherConfigFlag()
bool inet::Ipv6InterfaceData::getAdvOtherConfigFlag () const inline
 { return rtrVars.advOtherConfigFlag; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvPrefix()
const Ipv6InterfaceData::AdvPrefix & inet::Ipv6InterfaceData::getAdvPrefix (int i) const
Returns the ith advertised prefix on the interface.
 {
     ASSERT(i >= 0 && i < (int)rtrVars.advPrefixList.size());
     return rtrVars.advPrefixList[i];
 }
Referenced by inet::Ipv6RoutingTable::initialize(), and str().
getAdvReachableTime()
int inet::Ipv6InterfaceData::getAdvReachableTime () const inline
 { return rtrVars.advReachableTime; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvRetransTimer()
int inet::Ipv6InterfaceData::getAdvRetransTimer () const inline
 { return rtrVars.advRetransTimer; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket().
getAdvSendAdvertisements()
bool inet::Ipv6InterfaceData::getAdvSendAdvertisements () const inline
 { return rtrVars.advSendAdvertisements; }
Referenced by inet::Ipv6NeighbourDiscovery::createAndSendRaPacket(), inet::Ipv6NeighbourDiscovery::createAndSendRsPacket(), inet::Ipv6NeighbourDiscovery::initialize(), inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent(), inet::Ipv6NeighbourDiscovery::processRaPacket(), and inet::Ipv6NeighbourDiscovery::processRsPacket().
getBaseReachableTime()
uint inet::Ipv6InterfaceData::getBaseReachableTime () const inline
 { return hostVars.baseReachableTime; }
Referenced by generateReachableTime(), and Ipv6InterfaceData().
getCurHopLimit()
short inet::Ipv6InterfaceData::getCurHopLimit () const inline
 { return hostVars.curHopLimit; }
getDupAddrDetectTransmits()
int inet::Ipv6InterfaceData::getDupAddrDetectTransmits () const inline
 { return nodeVars.dupAddrDetectTransmits; }
Referenced by inet::Ipv6NeighbourDiscovery::assignLinkLocalAddress(), and inet::Ipv6NeighbourDiscovery::processDadTimeout().
getGlblAddress()
const Ipv6Address & inet::Ipv6InterfaceData::getGlblAddress () const
 {
     for (const auto& elem : addresses)
         if (elem.address.isGlobal())
             return elem.address;
     return Ipv6Address::UNSPECIFIED_ADDRESS;
 }
getHostData() [1/2]
HostMulticastData* inet::Ipv6InterfaceData::getHostData () inline protected
 { if (!hostMcastData) hostMcastData = new HostMulticastData(); return hostMcastData; }
Referenced by joinMulticastGroup(), and leaveMulticastGroup().
getHostData() [2/2]
const HostMulticastData* inet::Ipv6InterfaceData::getHostData () const inline protected
 { return const_cast<Ipv6InterfaceData *>(this)->getHostData(); }
Referenced by getHostData().
getJoinedMulticastGroups()
const Ipv6AddressVector& inet::Ipv6InterfaceData::getJoinedMulticastGroups () const inline
 { return getHostData()->joinedMulticastGroups; }
Referenced by isMemberOfMulticastGroup().
getLinkLocalAddress()
const Ipv6Address & inet::Ipv6InterfaceData::getLinkLocalAddress () const
Returns the first valid link-local address of the interface, or UNSPECIFIED_ADDRESS if there's none.
 {
     for (const auto& elem : addresses)
         if (elem.address.isLinkLocal()) // FIXME and valid
             return elem.address;
     return Ipv6Address::UNSPECIFIED_ADDRESS;
 }
Referenced by inet::ospfv3::Ospfv3Interface::detailedInfo().
getLinkMtu()
uint inet::Ipv6InterfaceData::getLinkMtu () const inline
 { return hostVars.linkMTU; }
getMaxRtrAdvInterval()
simtime_t inet::Ipv6InterfaceData::getMaxRtrAdvInterval () const inline
 { return rtrVars.maxRtrAdvInterval; }
Referenced by inet::Ipv6NeighbourDiscovery::createRaTimer(), and inet::Ipv6NeighbourDiscovery::sendPeriodicRa().
getMinRtrAdvInterval()
simtime_t inet::Ipv6InterfaceData::getMinRtrAdvInterval () const inline
 { return rtrVars.minRtrAdvInterval; }
Referenced by inet::Ipv6NeighbourDiscovery::createRaTimer(), and inet::Ipv6NeighbourDiscovery::sendPeriodicRa().
getNumAddresses()
int inet::Ipv6InterfaceData::getNumAddresses () const inline
Returns the number of addresses the interface has.
 { return addresses.size(); }
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and str().
getNumAdvPrefixes()
int inet::Ipv6InterfaceData::getNumAdvPrefixes () const inline
Returns the number of advertised prefixes on the interface.
 { return rtrVars.advPrefixList.size(); }
Referenced by str().
getPreferredAddress()
const Ipv6Address& inet::Ipv6InterfaceData::getPreferredAddress () const inline
Chooses a preferred address for the interface and returns it.
This is the address that should be used as source address for outgoing datagrams, if one is not explicitly specified.
Selection is based on scope (globally routable addresses are preferred), then on lifetime (the one that expires last is chosen). See private choosePreferredAddress() function.
FIXME turn into preferredGLOBALAddress()!
 { return preferredAddr; } // FIXME TODO check expiry time!
Referenced by inet::Ipv6NeighbourDiscovery::processNudTimeout().
getReachableTime()
simtime_t inet::Ipv6InterfaceData::getReachableTime () const inline
 { return hostVars.reachableTime; }
Referenced by inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates().
getReportedMulticastGroups()
const Ipv6AddressVector& inet::Ipv6InterfaceData::getReportedMulticastGroups () const inline
 { return getRouterData()->reportedMulticastGroups; }
getRetransTimer()
uint inet::Ipv6InterfaceData::getRetransTimer () const inline
 { return hostVars.retransTimer; }
Referenced by inet::Ipv6NeighbourDiscovery::initiateDad(), and inet::Ipv6NeighbourDiscovery::processDadTimeout().
getRouterData() [1/2]
RouterMulticastData* inet::Ipv6InterfaceData::getRouterData () inline protected
 { if (!routerMcastData) routerMcastData = new RouterMulticastData(); return routerMcastData; }
Referenced by addMulticastListener(), hasMulticastListener(), and removeMulticastListener().
getRouterData() [2/2]
const RouterMulticastData* inet::Ipv6InterfaceData::getRouterData () const inline protected
 { return const_cast<Ipv6InterfaceData *>(this)->getRouterData(); }
Referenced by getRouterData().
hasAddress()
bool inet::Ipv6InterfaceData::hasAddress (const Ipv6Address & addr) const
Returns true if the given address is one of the addresses assigned, regardless whether it is tentative or not.
 {
     return findAddress(addr) != -1;
 }
Referenced by inet::Ipv6NeighbourDiscovery::initiateAddressResolution(), inet::Ipv6NeighbourDiscovery::processNsPacket(), and inet::eigrp::EigrpIpv6Pdm::setPassive().
hasMulticastListener()
bool inet::Ipv6InterfaceData::hasMulticastListener (const Ipv6Address & multicastAddress) const
 {
     const Ipv6AddressVector& multicastGroups = getRouterData()->reportedMulticastGroups;
     return contains(multicastGroups, multicastAddress);
 }
Referenced by addMulticastListener().
isMemberOfMulticastGroup()
bool inet::Ipv6InterfaceData::isMemberOfMulticastGroup (const Ipv6Address & multicastAddress) const
 {
     const Ipv6AddressVector& multicastGroups = getJoinedMulticastGroups();
     return contains(multicastGroups, multicastAddress);
 }
isTentativeAddress() [1/2]
bool inet::Ipv6InterfaceData::isTentativeAddress (const Ipv6Address & addr) const
Returns true if the interface has the given address and it is tentative.
 {
     int k = findAddress(addr);
     return k != -1 && addresses[k].tentative;
 }
isTentativeAddress() [2/2]
bool inet::Ipv6InterfaceData::isTentativeAddress (int i) const
Returns true if the ith address of the interface is tentative.
 {
     ASSERT(i >= 0 && i < (int)addresses.size());
     return addresses[i].tentative;
 }
Referenced by inet::Ipv6NeighbourDiscovery::assignLinkLocalAddress(), inet::Ipv6NeighbourDiscovery::createAndSendRsPacket(), inet::Ipv6::fragmentAndSend(), inet::Ipv6::handleMessage(), inet::Ipv6NeighbourDiscovery::processNaPacket(), inet::Ipv6NeighbourDiscovery::processNsPacket(), and str().
joinMulticastGroup()
void inet::Ipv6InterfaceData::joinMulticastGroup (const Ipv6Address & multicastAddress) virtual
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv6InterfaceData::joinMulticastGroup(): multicast address expected, received %s.", multicastAddress.str().c_str());
     Ipv6AddressVector& multicastGroups = getHostData()->joinedMulticastGroups;
     std::vector<int>& refCounts = getHostData()->refCounts;
     for (int i = 0; i < (int)multicastGroups.size(); ++i) {
         if (multicastGroups[i] == multicastAddress) {
             refCounts[i]++;
             return;
         }
     }
     multicastGroups.push_back(multicastAddress);
     refCounts.push_back(1);
     changed1(F_MULTICAST_ADDRESSES);
     cModule *m = ownerp ? dynamic_cast<cModule *>(ownerp->getInterfaceTable()) : nullptr;
     if (m) {
         Ipv6MulticastGroupInfo info(ownerp, multicastAddress);
         m->emit(ipv6MulticastGroupJoinedSignal, &info);
     }
 }
Referenced by inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), and inet::ospfv3::Ospfv3Splitter::parseConfig().
leaveMulticastGroup()
void inet::Ipv6InterfaceData::leaveMulticastGroup (const Ipv6Address & multicastAddress) virtual
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv6InterfaceData::leaveMulticastGroup(): multicast address expected, received %s.", multicastAddress.str().c_str());
     Ipv6AddressVector& multicastGroups = getHostData()->joinedMulticastGroups;
     std::vector<int>& refCounts = getHostData()->refCounts;
     for (int i = 0; i < (int)multicastGroups.size(); ++i) {
         if (multicastGroups[i] == multicastAddress) {
             if (--refCounts[i] == 0) {
                 multicastGroups.erase(multicastGroups.begin() + i);
                 refCounts.erase(refCounts.begin() + i);
                 changed1(F_MULTICAST_ADDRESSES);
                 cModule *m = ownerp ? dynamic_cast<cModule *>(ownerp->getInterfaceTable()) : nullptr;
                 if (m) {
                     Ipv6MulticastGroupInfo info(ownerp, multicastAddress);
                     m->emit(ipv6MulticastGroupLeftSignal, &info);
                 }
             }
         }
     }
 }
Referenced by inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), and inet::eigrp::EigrpIpv6Pdm::setPassive().
matchesSolicitedNodeMulticastAddress()
bool inet::Ipv6InterfaceData::matchesSolicitedNodeMulticastAddress (const Ipv6Address & solNodeAddr) const
Returns true if the interface has an address matching the given solicited-node multicast addresses.
 {
     for (const auto& elem : addresses)
         if (elem.address.formSolicitedNodeMulticastAddress() == solNodeAddr)
             return true;
     return false;
 }
Referenced by inet::Ipv6RoutingTable::isLocalAddress().
permanentlyAssign()
void inet::Ipv6InterfaceData::permanentlyAssign (const Ipv6Address & addr) virtual
Clears the "tentative" flag of an existing interface address.
 {
     int k = findAddress(addr);
     ASSERT(k != -1);
     addresses[k].tentative = false;
     choosePreferredAddress();
 }
removeAddress()
void inet::Ipv6InterfaceData::removeAddress (const Ipv6Address & address) virtual
Removes the address.
Called when the valid lifetime expires.
 {
     int k = findAddress(address);
     ASSERT(k != -1);
     addresses.erase(addresses.begin() + k);
     choosePreferredAddress();
     changed1(F_IP_ADDRESS);
 }
Referenced by inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent(), and inet::eigrp::EigrpIpv6Pdm::setPassive().
removeAdvPrefix()
void inet::Ipv6InterfaceData::removeAdvPrefix (int i) virtual
Remove the ith advertised prefix on the interface.
Prefixes at larger indices will shift down.
 {
     ASSERT(i >= 0 && i < (int)rtrVars.advPrefixList.size());
     rtrVars.advPrefixList.erase(rtrVars.advPrefixList.begin() + i);
 }
removeMulticastListener()
void inet::Ipv6InterfaceData::removeMulticastListener (const Ipv6Address & multicastAddress) virtual
 {
     Ipv6AddressVector& multicastGroups = getRouterData()->reportedMulticastGroups;
     int n = multicastGroups.size();
     int i;
     for (i = 0; i < n; i++)
         if (multicastGroups[i] == multicastAddress)
             break;
     if (i != n) {
         multicastGroups.erase(multicastGroups.begin() + i);
         changed1(F_MULTICAST_LISTENERS);
     }
 }
setAdvCurHopLimit()
virtual void inet::Ipv6InterfaceData::setAdvCurHopLimit (short d) inline virtual
 { rtrVars.advCurHopLimit = d; }
setAdvDefaultLifetime()
virtual void inet::Ipv6InterfaceData::setAdvDefaultLifetime (simtime_t d) inline virtual
 { rtrVars.advDefaultLifetime = d; }
setAdvLinkMtu()
virtual void inet::Ipv6InterfaceData::setAdvLinkMtu (int d) inline virtual
 { rtrVars.advLinkMTU = d; }
setAdvManagedFlag()
virtual void inet::Ipv6InterfaceData::setAdvManagedFlag (bool d) inline virtual
 { rtrVars.advManagedFlag = d; }
setAdvOtherConfigFlag()
virtual void inet::Ipv6InterfaceData::setAdvOtherConfigFlag (bool d) inline virtual
 { rtrVars.advOtherConfigFlag = d; }
setAdvPrefix()
void inet::Ipv6InterfaceData::setAdvPrefix (int i, const AdvPrefix & advPrefix) virtual
Changes the configuration of the ith advertised prefix on the interface.
The prefix itself should stay the same.
 {
     ASSERT(i >= 0 && i < (int)rtrVars.advPrefixList.size());
     ASSERT(rtrVars.advPrefixList[i].prefix == advPrefix.prefix);
     ASSERT(rtrVars.advPrefixList[i].prefixLength == advPrefix.prefixLength);
     rtrVars.advPrefixList[i] = advPrefix;
 }
setAdvReachableTime()
virtual void inet::Ipv6InterfaceData::setAdvReachableTime (int d) inline virtual
 { rtrVars.advReachableTime = d; }
setAdvRetransTimer()
virtual void inet::Ipv6InterfaceData::setAdvRetransTimer (int d) inline virtual
 { rtrVars.advRetransTimer = d; }
setAdvSendAdvertisements()
virtual void inet::Ipv6InterfaceData::setAdvSendAdvertisements (bool d) inline virtual
 { rtrVars.advSendAdvertisements = d; }
Referenced by inet::Ipv6RoutingTable::configureInterfaceForIpv6(), and inet::Ipv6RoutingTable::configureInterfaceFromXml().
setBaseReachableTime()
virtual void inet::Ipv6InterfaceData::setBaseReachableTime (uint d) inline virtual
 { hostVars.baseReachableTime = d; }
setCurHopLimit()
virtual void inet::Ipv6InterfaceData::setCurHopLimit (short d) inline virtual
 { hostVars.curHopLimit = d; }
setDupAddrDetectTransmits()
virtual void inet::Ipv6InterfaceData::setDupAddrDetectTransmits (int d) inline virtual
 { nodeVars.dupAddrDetectTransmits = d; }
setLinkMtu()
virtual void inet::Ipv6InterfaceData::setLinkMtu (uint d) inline virtual
 { hostVars.linkMTU = d; }
setMaxRtrAdvInterval()
virtual void inet::Ipv6InterfaceData::setMaxRtrAdvInterval (simtime_t d) inline virtual
 { rtrVars.maxRtrAdvInterval = d; }
setMinRtrAdvInterval()
virtual void inet::Ipv6InterfaceData::setMinRtrAdvInterval (simtime_t d) inline virtual
 { rtrVars.minRtrAdvInterval = d; }
setReachableTime()
virtual void inet::Ipv6InterfaceData::setReachableTime (simtime_t d) inline virtual
 { hostVars.reachableTime = d; }
setRetransTimer()
virtual void inet::Ipv6InterfaceData::setRetransTimer (uint d) inline virtual
 { hostVars.retransTimer = d; }
str()
std::string inet::Ipv6InterfaceData::str () const override virtual
Reimplemented from inet::TagBase.
 {
     // FIXME FIXME FIXME FIXME info() should never print a newline
     std::ostringstream os;
     os << "Ipv6:{" << endl;
     for (int i = 0; i < getNumAddresses(); i++) {
         os << (i ? "\t            , " : "\tAddrs:") << getAddress(i)
            << "(" << Ipv6Address::scopeName(getAddress(i).getScope())
            << (isTentativeAddress(i) ? " tent" : "") << ") "
 #ifdef INET_WITH_xMIPv6
 // TODO revise, routing table is not that simple to access
 //           << ((rt6->isMobileNode() && getAddress(i).isGlobal())
 //               ? (addresses[i].addrType==HoA ? "HoA" : "CoA") : "")
 #endif /* INET_WITH_xMIPv6 */
            << " expiryTime: " << (addresses[i].expiryTime == SIMTIME_ZERO ? "inf" : SIMTIME_STR(addresses[i].expiryTime))
            << " prefExpiryTime: " << (addresses[i].prefExpiryTime == SIMTIME_ZERO ? "inf" : SIMTIME_STR(addresses[i].prefExpiryTime))
            << endl;
     }
     if (hostMcastData)
         os << hostMcastData->str();
     for (int i = 0; i < getNumAdvPrefixes(); i++) {
         const AdvPrefix& a = getAdvPrefix(i);
         os << (i ? ", " : "\tAdvPrefixes: ") << a.prefix << "/" << a.prefixLength << "("
            << (a.advOnLinkFlag ? "" : "off-link ")
            << (a.advAutonomousFlag ? "" : "non-auto ");
 #ifdef INET_WITH_xMIPv6
         os << "R-Flag = " << (a.advRtrAddr ? "1 " : "0 ");
 #endif /* INET_WITH_xMIPv6 */
         if (a.advValidLifetime == SIMTIME_ZERO)
             os << "lifetime:inf";
         else if (a.advValidLifetime > SIMTIME_ZERO)
             os << "expires:" << a.advValidLifetime;
         else
             os << "lifetime:+" << (-1 * a.advValidLifetime);
         os << ")" << endl;
     }
     os << " ";
     if (routerMcastData)
         os << routerMcastData->str();
     // uncomment the following as needed!
     os << "\tNode:";
     os << " dupAddrDetectTrans=" << nodeVars.dupAddrDetectTransmits;
 //    os << " curHopLimit=" << hostVars.curHopLimit;
 //    os << " retransTimer=" << hostVars.retransTimer;
 //    os << " baseReachableTime=" << hostVars.baseReachableTime;
     os << " reachableTime=" << hostVars.reachableTime << endl;
 #ifdef INET_WITH_xMIPv6
     // the following is for MIPv6 support
     // 4.9.07 - Zarrar, CB
 // TODO revise, routing table is not that simple to access
 //    if ( rt6->isMobileNode() )
 //        os << "\tHome Network Info: " << " HoA="<< homeInfo.HoA << ", HA=" << homeInfo.homeAgentAddr
 //           << ", home prefix=" << homeInfo.prefix/*.prefix()*/ << "\n";
 #endif /* INET_WITH_xMIPv6 */
     if (rtrVars.advSendAdvertisements) {
         os << "\tRouter:";
         os << " maxRtrAdvInt=" << rtrVars.maxRtrAdvInterval;
         os << " minRtrAdvInt=" << rtrVars.minRtrAdvInterval << endl;
 //        os << " advManagedFlag=" << rtrVars.advManagedFlag;
 //        os << " advOtherFlag=" << rtrVars.advOtherFlag;
 //        os << " advLinkMTU=" << rtrVars.advLinkMTU;
 //        os << " advReachableTime=" << rtrVars.advReachableTime;
 //        os << " advRetransTimer=" << rtrVars.advRetransTimer;
 //        os << " advCurHopLimit=" << rtrVars.advCurHopLimit;
 //        os << " advDefaultLifetime=" << rtrVars.advDefaultLifetime;
     }
     os << "   }" << endl;
     return os.str();
 }
Referenced by detailedInfo().
updateMatchingAddressExpiryTimes()
void inet::Ipv6InterfaceData::updateMatchingAddressExpiryTimes (const Ipv6Address & prefix, int length, simtime_t expiryTime = SIMTIME_ZERO, simtime_t prefExpiryTime = SIMTIME_ZERO) virtual
Update expiry times of addresses.
Expiry times possibly come from prefixes (with on-link flag set to either zero or one) in Router Advertisements. Zero expiry time means infinity.
 {
     for (auto& elem : addresses) {
         if (elem.address.matches(prefix, length)) {
             elem.expiryTime = expiryTime;
             elem.prefExpiryTime = prefExpiryTime;
         }
     }
     choosePreferredAddress();
 }
Member Data Documentation
addresses
AddressDataVector inet::Ipv6InterfaceData::addresses protected
Referenced by choosePreferredAddress(), findAddress(), getAddress(), getGlblAddress(), getLinkLocalAddress(), isTentativeAddress(), matchesSolicitedNodeMulticastAddress(), permanentlyAssign(), removeAddress(), str(), and updateMatchingAddressExpiryTimes().
hostConstants
HostConstants inet::Ipv6InterfaceData::hostConstants
Referenced by Ipv6InterfaceData().
hostMcastData
HostMulticastData* inet::Ipv6InterfaceData::hostMcastData = nullptr protected
Referenced by str(), and ~Ipv6InterfaceData().
hostVars
HostVariables inet::Ipv6InterfaceData::hostVars protected
Referenced by Ipv6InterfaceData(), and str().
nodeConstants
NodeConstants inet::Ipv6InterfaceData::nodeConstants
Referenced by Ipv6InterfaceData().
nodeVars
NodeVariables inet::Ipv6InterfaceData::nodeVars protected
Referenced by Ipv6InterfaceData(), and str().
preferredAddr
Ipv6Address inet::Ipv6InterfaceData::preferredAddr protected
Referenced by choosePreferredAddress().
preferredAddrExpiryTime
simtime_t inet::Ipv6InterfaceData::preferredAddrExpiryTime protected
Referenced by choosePreferredAddress().
routerConstants
RouterConstants inet::Ipv6InterfaceData::routerConstants
Referenced by Ipv6InterfaceData().
routerMcastData
RouterMulticastData* inet::Ipv6InterfaceData::routerMcastData = nullptr protected
Referenced by str(), and ~Ipv6InterfaceData().
rtrVars
RouterVariables inet::Ipv6InterfaceData::rtrVars protected
Referenced by addAdvPrefix(), getAdvPrefix(), Ipv6InterfaceData(), removeAdvPrefix(), setAdvPrefix(), and str().
The documentation for this class was generated from the following files:
Ipv6InterfaceData.h
Ipv6InterfaceData.cc