INET Framework for OMNeT++/OMNEST: inet::MobilityBase Class Reference
inet::MobilityBase Class Reference abstract
Abstract base class for mobility modules.
#include <MobilityBase.h>
Classes
class DirectiveResolver
Public Types
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Selects how a mobility module should behave if it reaches the edge of the constraint area.
Public Member Functions
virtual double getMaxSpeed () const override
Returns the maximum possible speed at any future time.
virtual const Coord & getConstraintAreaMax () const override
Returns the maximum position along each axes for.
virtual const Coord & getConstraintAreaMin () const override
Returns the minimum position along each axes for.
Public Member Functions inherited from inet::IMobility
virtual ~IMobility ()
virtual const Coord & getCurrentPosition ()=0
Returns the position at the current simulation time.
virtual const Coord & getCurrentVelocity ()=0
Returns the velocity at the current simulation time.
virtual const Coord & getCurrentAcceleration ()=0
Returns the acceleration at the current simulation time.
virtual const Quaternion & getCurrentAngularPosition ()=0
Returns the angular position at the current simulation time.
virtual const Quaternion & getCurrentAngularVelocity ()=0
Returns the angular velocity at the current simulation time.
virtual const Quaternion & getCurrentAngularAcceleration ()=0
Returns the angular acceleration at the current simulation time.
Protected Member Functions
MobilityBase ()
virtual int getId () const override
virtual int numInitStages () const override
Returns the required number of initialize stages.
virtual void initialize (int stage) override
Initializes mobility model parameters.
virtual void initializePosition ()
Initializes mobility position.
virtual void setInitialPosition ()
Initializes the position from the display string or from module parameters.
virtual void checkPosition ()
Checks whether the position is valid or not.
virtual void initializeOrientation ()
Initializes the orientation from module parameters.
virtual void refreshDisplay () const override
Moves the visual representation module's icon to the new position on the screen.
virtual void updateDisplayStringFromMobilityState () const
virtual void handleParameterChange (const char *name) override
Allows changing parameters from the GUI.
virtual void handleMessage (cMessage *msg) override
This modules should only receive self-messages.
virtual void handleSelfMessage (cMessage *msg)=0
Called upon arrival of a self messages, subclasses must override.
virtual void emitMobilityStateChangedSignal ()
Emits a signal with the updated mobility state.
virtual Coord getRandomPosition ()
Returns a new random position satisfying the constraint area.
virtual cModule * findSubjectModule ()
Returns the module that represents the object moved by this mobility module.
virtual bool isOutside ()
Returns true if the mobility is outside of the constraint area.
virtual void reflectIfOutside (Coord &targetPosition, Coord &velocity, rad &angle, rad &elevation, Quaternion &quaternion)
Utility function to reflect the node if it goes outside the constraint area.
virtual void wrapIfOutside (Coord &targetPosition)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the constraint area.
virtual void placeRandomlyIfOutside (Coord &targetPosition)
Utility function to place the node randomly if it goes outside the constraint area.
virtual void raiseErrorIfOutside ()
Utility function to raise an error if the node gets outside the constraint area.
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity)
Invokes one of reflectIfOutside(), wrapIfOutside() and placeRandomlyIfOutside(), depending on the given border policy.
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity, rad &heading)
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity, rad &heading, rad &elevation)
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity, rad &heading, rad &elevation, Quaternion &quaternion)
Protected Attributes
cModule * subjectModule
Pointer to visual representation module, to speed up repeated access.
const CanvasProjection * canvasProjection
The 2D projection used on the canvas.
Coord constraintAreaMin
3 dimensional position and size of the constraint area (in meters).
Coord constraintAreaMax
Coord lastPosition
The last position that was reported.
Quaternion lastOrientation
The last orientation that was reported.
StringFormat format
Additional Inherited Members
Static Public Attributes inherited from inet::IMobility
static simsignal_t mobilityStateChangedSignal = cComponent::registerSignal("mobilityStateChanged")
A signal used to publish mobility state changes.
Detailed Description
Abstract base class for mobility modules.
Mobility modules inheriting from this base class may be stationary or may change their mobility state over simulation time. This base class only provides a few utility methods to handle some common tasks among mobility modules.
Subclasses must redefine handleSelfMessage() to update the mobility state and schedule the next update. Subclasses must also redefine initialize() to read their specific parameters and schedule the first update.
This base class also provides random initial placement as a default mechanism. After initialization the module updates the display and emits a signal to subscribers providing the mobility state. Receivers of this signal can query the mobility state through the IMobility interface.
Member Enumeration Documentation
BorderPolicy
enum inet::MobilityBase::BorderPolicy
Selects how a mobility module should behave if it reaches the edge of the constraint area.
See also
handleIfOutside()
Enumerator
REFLECT
reflect off the wall
WRAP
reappear at the opposite edge (torus)
PLACERANDOMLY
placed at a randomly chosen position within the constraint area
RAISEERROR
stop the simulation with error
                       {
         REFLECT,
         WRAP,
         PLACERANDOMLY,
         RAISEERROR
     };
Constructor & Destructor Documentation
MobilityBase()
inet::MobilityBase::MobilityBase () protected
                            :
     subjectModule(nullptr),
     canvasProjection(nullptr),
     constraintAreaMin(Coord::ZERO),
     constraintAreaMax(Coord::ZERO),
     lastPosition(Coord::ZERO)
 {
 }
Member Function Documentation
checkPosition()
void inet::MobilityBase::checkPosition () protected virtual
Checks whether the position is valid or not.
 {
     if (!isFiniteNumber(lastPosition.x) || !isFiniteNumber(lastPosition.y) || !isFiniteNumber(lastPosition.z))
         throw cRuntimeError("Mobility position is not a finite number after initialize (x=%g,y=%g,z=%g)", lastPosition.x, lastPosition.y, lastPosition.z);
     if (isOutside())
         throw cRuntimeError("Mobility position (x=%g,y=%g,z=%g) is outside the constraint area (%g,%g,%g - %g,%g,%g)",
                 lastPosition.x, lastPosition.y, lastPosition.z,
                 constraintAreaMin.x, constraintAreaMin.y, constraintAreaMin.z,
                 constraintAreaMax.x, constraintAreaMax.y, constraintAreaMax.z);
 }
Referenced by initializePosition().
emitMobilityStateChangedSignal()
void inet::MobilityBase::emitMobilityStateChangedSignal () protected virtual
Emits a signal with the updated mobility state.
 {
     emit(mobilityStateChangedSignal, this);
 }
Referenced by inet::FacingMobility::handleParameterChange(), initializePosition(), inet::MovingMobilityBase::moveAndUpdate(), inet::AttachedMobility::receiveSignal(), inet::SuperpositioningMobility::receiveSignal(), and inet::RotatingMobilityBase::rotateAndUpdate().
findSubjectModule()
virtual cModule* inet::MobilityBase::findSubjectModule () inline protected virtual
Returns the module that represents the object moved by this mobility module.
Reimplemented in inet::MoBanCoordinator.
 { return findModuleFromPar<cModule>(par("subjectModule"), this); }
Referenced by initialize().
getConstraintAreaMax()
virtual const Coord& inet::MobilityBase::getConstraintAreaMax () const inline override virtual
Returns the maximum position along each axes for.
Implements inet::IMobility.
Reimplemented in inet::StationaryMobilityBase.
 { return constraintAreaMax; }
getConstraintAreaMin()
virtual const Coord& inet::MobilityBase::getConstraintAreaMin () const inline override virtual
Returns the minimum position along each axes for.
Implements inet::IMobility.
Reimplemented in inet::StationaryMobilityBase.
 { return constraintAreaMin; }
getId()
virtual int inet::MobilityBase::getId () const inline override protected virtual
Implements inet::IMobility.
 { return cSimpleModule::getId(); }
getMaxSpeed()
virtual double inet::MobilityBase::getMaxSpeed () const inline override virtual
Returns the maximum possible speed at any future time.
Implements inet::IMobility.
Reimplemented in inet::MoBanCoordinator, inet::MoBanLocal, inet::Ns2MotionMobility, inet::TurtleMobility, inet::AnsimMobility, inet::MassMobility, inet::BonnMotionMobility, inet::VehicleMobility, inet::CircleMobility, inet::GaussMarkovMobility, inet::RectangleMobility, inet::TractorMobility, inet::ChiangMobility, inet::RandomWaypointMobility, inet::LinearMobility, and inet::StationaryMobilityBase.
 { return NaN; }
getRandomPosition()
Coord inet::MobilityBase::getRandomPosition () protected virtual
Returns a new random position satisfying the constraint area.
 {
     Coord p;
     p.x = uniform(constraintAreaMin.x, constraintAreaMax.x);
     p.y = uniform(constraintAreaMin.y, constraintAreaMax.y);
     p.z = uniform(constraintAreaMin.z, constraintAreaMax.z);
     return p;
 }
Referenced by placeRandomlyIfOutside(), inet::MoBanCoordinator::selectDestination(), setInitialPosition(), and inet::RandomWaypointMobility::setTargetPosition().
handleIfOutside() [1/4]
void inet::MobilityBase::handleIfOutside (BorderPolicy policy, Coord & targetPosition, Coord & velocity) protected virtual
Invokes one of reflectIfOutside(), wrapIfOutside() and placeRandomlyIfOutside(), depending on the given border policy.
 {
     rad a;
     handleIfOutside(policy, targetPosition, velocity, a, a, Quaternion::NIL);
 }
Referenced by handleIfOutside(), inet::LinearMobility::move(), inet::ChiangMobility::move(), inet::GaussMarkovMobility::move(), inet::CircleMobility::move(), inet::MassMobility::move(), and inet::TurtleMobility::move().
handleIfOutside() [2/4]
void inet::MobilityBase::handleIfOutside (BorderPolicy policy, Coord & targetPosition, Coord & velocity, rad & heading) protected virtual
 {
     rad dummy;
     handleIfOutside(policy, targetPosition, velocity, heading, dummy, Quaternion::NIL);
 }
handleIfOutside() [3/4]
void inet::MobilityBase::handleIfOutside (BorderPolicy policy, Coord & targetPosition, Coord & velocity, rad & heading, rad & elevation) protected virtual
 {
     handleIfOutside(policy, targetPosition, velocity, heading, elevation, Quaternion::NIL);
 }
handleIfOutside() [4/4]
void inet::MobilityBase::handleIfOutside (BorderPolicy policy, Coord & targetPosition, Coord & velocity, rad & heading, rad & elevation, Quaternion & quaternion) protected virtual
 {
     switch (policy) {
         case REFLECT:
             reflectIfOutside(targetPosition, velocity, heading, elevation, quaternion);
             break;
         case WRAP:
             wrapIfOutside(targetPosition);
             break;
         case PLACERANDOMLY:
             placeRandomlyIfOutside(targetPosition);
             break;
         case RAISEERROR:
             raiseErrorIfOutside();
             break;
         default:
             throw cRuntimeError("Invalid outside policy=%d in module '%s'", policy, getFullPath().c_str());
     }
 }
handleMessage()
void inet::MobilityBase::handleMessage (cMessage * msg) override protected virtual
This modules should only receive self-messages.
 {
     if (message->isSelfMessage())
         handleSelfMessage(message);
     else
         throw cRuntimeError("Mobility modules can only receive self messages");
 }
handleParameterChange()
void inet::MobilityBase::handleParameterChange (const char * name) override protected virtual
Allows changing parameters from the GUI.
Reimplemented in inet::FacingMobility.
 {
     if (name != nullptr) {
         if (!strcmp(name, "displayStringTextFormat"))
             format.parseFormat(par("displayStringTextFormat"));
     }
 }
handleSelfMessage()
virtual void inet::MobilityBase::handleSelfMessage (cMessage * msg) protected pure virtual
Called upon arrival of a self messages, subclasses must override.
Implemented in inet::SuperpositioningMobility, inet::AttachedMobility, inet::FacingMobility, inet::MovingMobilityBase, inet::RotatingMobilityBase, and inet::StationaryMobilityBase.
Referenced by handleMessage().
initialize()
void inet::MobilityBase::initialize (int stage) override protected virtual
Initializes mobility model parameters.
Reimplemented in inet::MoBanCoordinator, inet::MoBanLocal, inet::TractorMobility, inet::Ns2MotionMobility, inet::MovingMobilityBase, inet::SuperpositioningMobility, inet::RotatingMobilityBase, inet::MassMobility, inet::TurtleMobility, inet::VehicleMobility, inet::CircleMobility, inet::RectangleMobility, inet::GaussMarkovMobility, inet::AnsimMobility, inet::BonnMotionMobility, inet::RandomWaypointMobility, inet::StaticLinearMobility, inet::ChiangMobility, inet::LinearMobility, inet::AttachedMobility, inet::StationaryMobility, and inet::FacingMobility.
 {
     cSimpleModule::initialize(stage);
     EV_TRACE << "initializing MobilityBase stage " << stage << endl;
     if (stage == INITSTAGE_LOCAL) {
         constraintAreaMin.x = par("constraintAreaMinX");
         constraintAreaMin.y = par("constraintAreaMinY");
         constraintAreaMin.z = par("constraintAreaMinZ");
         constraintAreaMax.x = par("constraintAreaMaxX");
         constraintAreaMax.y = par("constraintAreaMaxY");
         constraintAreaMax.z = par("constraintAreaMaxZ");
         format.parseFormat(par("displayStringTextFormat"));
         subjectModule = findSubjectModule();
         if (subjectModule != nullptr) {
             auto visualizationTarget = subjectModule->getParentModule();
             canvasProjection = CanvasProjection::getCanvasProjection(visualizationTarget->getCanvas());
         }
         WATCH(constraintAreaMin);
         WATCH(constraintAreaMax);
         WATCH(lastPosition);
         WATCH(lastOrientation);
     }
     else if (stage == INITSTAGE_SINGLE_MOBILITY) {
         initializeOrientation();
         initializePosition();
     }
 }
Referenced by inet::FacingMobility::initialize(), inet::StationaryMobility::initialize(), inet::AttachedMobility::initialize(), inet::StaticLinearMobility::initialize(), inet::RotatingMobilityBase::initialize(), inet::SuperpositioningMobility::initialize(), and inet::MovingMobilityBase::initialize().
initializeOrientation()
void inet::MobilityBase::initializeOrientation () protected virtual
Initializes the orientation from module parameters.
Reimplemented in inet::RotatingMobilityBase, and inet::LinearRotatingMobilityBase.
 {
     if (hasPar("initialHeading") && hasPar("initialElevation") && hasPar("initialBank")) {
         auto alpha = deg(par("initialHeading"));
         auto initialElevation = deg(par("initialElevation"));
         // NOTE: negation is needed, see IMobility comments on orientation
         auto beta = -initialElevation;
         auto gamma = deg(par("initialBank"));
         lastOrientation = Quaternion(EulerAngles(alpha, beta, gamma));
     }
 }
Referenced by initialize(), inet::LinearRotatingMobilityBase::initializeOrientation(), and inet::RotatingMobilityBase::initializeOrientation().
initializePosition()
void inet::MobilityBase::initializePosition () protected virtual
Initializes mobility position.
Reimplemented in inet::MovingMobilityBase, and inet::LineSegmentsMobilityBase.
 {
     setInitialPosition();
     checkPosition();
     emitMobilityStateChangedSignal();
 }
Referenced by inet::SuperpositioningMobility::initialize(), initialize(), inet::LineSegmentsMobilityBase::initializePosition(), and inet::MovingMobilityBase::initializePosition().
isOutside()
bool inet::MobilityBase::isOutside () protected virtual
Returns true if the mobility is outside of the constraint area.
 {
     return lastPosition.x < constraintAreaMin.x || lastPosition.x > constraintAreaMax.x
            || lastPosition.y < constraintAreaMin.y || lastPosition.y > constraintAreaMax.y
            || lastPosition.z < constraintAreaMin.z || lastPosition.z > constraintAreaMax.z;
 }
Referenced by checkPosition(), placeRandomlyIfOutside(), and raiseErrorIfOutside().
numInitStages()
virtual int inet::MobilityBase::numInitStages () const inline override protected virtual
Returns the required number of initialize stages.
Reimplemented in inet::MoBanCoordinator, inet::MoBanLocal, inet::Ns2MotionMobility, inet::SuperpositioningMobility, inet::MassMobility, inet::TurtleMobility, inet::CircleMobility, inet::GaussMarkovMobility, inet::TractorMobility, inet::AnsimMobility, inet::BonnMotionMobility, inet::RandomWaypointMobility, inet::RectangleMobility, inet::StaticLinearMobility, inet::ChiangMobility, inet::LinearMobility, inet::AttachedMobility, and inet::FacingMobility.
 { return NUM_INIT_STAGES; }
placeRandomlyIfOutside()
void inet::MobilityBase::placeRandomlyIfOutside (Coord & targetPosition) protected virtual
Utility function to place the node randomly if it goes outside the constraint area.
Decision is made on lastPosition, but targetPosition will also be updated. (Pass a dummy you don't have it).
 {
     if (isOutside()) {
         Coord newPosition = getRandomPosition();
         targetPosition += newPosition - lastPosition;
         lastPosition = newPosition;
     }
 }
Referenced by handleIfOutside().
raiseErrorIfOutside()
void inet::MobilityBase::raiseErrorIfOutside () protected virtual
Utility function to raise an error if the node gets outside the constraint area.
 {
     if (isOutside()) {
         throw cRuntimeError("Mobility moved outside the area %g,%g,%g - %g,%g,%g (x=%g,y=%g,z=%g)",
                 constraintAreaMin.x, constraintAreaMin.y, constraintAreaMin.z,
                 constraintAreaMax.x, constraintAreaMax.y, constraintAreaMax.z,
                 lastPosition.x, lastPosition.y, lastPosition.z);
     }
 }
Referenced by handleIfOutside(), inet::RandomWaypointMobility::move(), inet::BonnMotionMobility::move(), inet::AnsimMobility::move(), and inet::Ns2MotionMobility::move().
reflectIfOutside()
void inet::MobilityBase::reflectIfOutside (Coord & targetPosition, Coord & velocity, rad & angle, rad & elevation, Quaternion & quaternion) protected virtual
Utility function to reflect the node if it goes outside the constraint area.
Decision is made on pos, but the variables passed as args will also be updated. (Pass dummies you don't have some of them).
 {
     int sign;
     double dummy = NaN;
     if (lastPosition.x < constraintAreaMin.x || constraintAreaMax.x < lastPosition.x) {
         sign = reflect(constraintAreaMin.x, constraintAreaMax.x, lastPosition.x, velocity.x);
         reflect(constraintAreaMin.x, constraintAreaMax.x, targetPosition.x, dummy);
         heading = deg(90) + (heading - deg(90)) * sign;
         if (sign == -1 && &quaternion != &Quaternion::NIL) {
             std::swap(quaternion.s, quaternion.v.z);
             std::swap(quaternion.v.x, quaternion.v.y);
             quaternion.v.x *= -1;
             quaternion.v.y *= -1;
         }
     }
     if (lastPosition.y < constraintAreaMin.y || constraintAreaMax.y < lastPosition.y) {
         sign = reflect(constraintAreaMin.y, constraintAreaMax.y, lastPosition.y, velocity.y);
         reflect(constraintAreaMin.y, constraintAreaMax.y, targetPosition.y, dummy);
         heading = heading * sign;
         if (sign == -1 && &quaternion != &Quaternion::NIL) {
             quaternion.v.x *= -1;
             quaternion.v.z *= -1;
         }
     }
     if (lastPosition.z < constraintAreaMin.z || constraintAreaMax.z < lastPosition.z) {
         sign = reflect(constraintAreaMin.z, constraintAreaMax.z, lastPosition.z, velocity.z);
         reflect(constraintAreaMin.z, constraintAreaMax.z, targetPosition.z, dummy);
         elevation = elevation * sign;
         if (sign == -1 && &quaternion != &Quaternion::NIL) {
             quaternion.v.x *= -1;
             quaternion.v.y *= -1;
         }
     }
 }
Referenced by handleIfOutside().
refreshDisplay()
void inet::MobilityBase::refreshDisplay () const override protected virtual
Moves the visual representation module's icon to the new position on the screen.
Reimplemented in inet::MoBanCoordinator, inet::MoBanLocal, and inet::StationaryMobility.
 {
     DirectiveResolver directiveResolver(const_cast<MobilityBase *>(this));
     auto text = format.formatString(&directiveResolver);
     getDisplayString().setTagArg("t", 0, text);
     if (par("updateDisplayString"))
         updateDisplayStringFromMobilityState();
 }
Referenced by inet::StationaryMobility::refreshDisplay().
setInitialPosition()
void inet::MobilityBase::setInitialPosition () protected virtual
Initializes the position from the display string or from module parameters.
Reimplemented in inet::MoBanCoordinator, inet::MoBanLocal, inet::Ns2MotionMobility, inet::SuperpositioningMobility, inet::TurtleMobility, inet::CircleMobility, inet::VehicleMobility, inet::RectangleMobility, inet::TractorMobility, inet::AnsimMobility, inet::BonnMotionMobility, inet::StaticLinearMobility, inet::StaticConcentricMobility, and inet::StaticGridMobility.
 {
     // reading the coordinates from omnetpp.ini makes predefined scenarios a lot easier
     auto coordinateSystem = findModuleFromPar<IGeographicCoordinateSystem>(par("coordinateSystemModule"), this);
     if (subjectModule != nullptr && hasPar("initFromDisplayString") && par("initFromDisplayString")) {
         const char *s = subjectModule->getDisplayString().getTagArg("p", 2);
         if (s && *s)
             throw cRuntimeError("The coordinates of '%s' are invalid. Please remove automatic arrangement"
                                 " (3rd argument of 'p' tag) from '@display' attribute.", subjectModule->getFullPath().c_str());
         bool filled = parseIntTo(subjectModule->getDisplayString().getTagArg("p", 0), lastPosition.x) &&
                       parseIntTo(subjectModule->getDisplayString().getTagArg("p", 1), lastPosition.y);
         if (filled) {
             lastPosition.z = hasPar("initialZ") ? par("initialZ") : 0.0;
             lastPosition = canvasProjection->computeCanvasPointInverse(cFigure::Point(lastPosition.x, lastPosition.y), lastPosition.z);
             EV_DEBUG << "position initialized from displayString and initialZ parameter: " << lastPosition << endl;
         }
         else {
             lastPosition = getRandomPosition();
             EV_DEBUG << "position initialized by random values: " << lastPosition << endl;
         }
     }
     // not all mobility models have "initialX", "initialY" and "initialZ" parameters
     else if (coordinateSystem == nullptr && hasPar("initialX") && hasPar("initialY") && hasPar("initialZ")) {
         lastPosition.x = par("initialX");
         lastPosition.y = par("initialY");
         lastPosition.z = par("initialZ");
         EV_DEBUG << "position initialized from initialX/Y/Z parameters: " << lastPosition << endl;
     }
     else if (coordinateSystem != nullptr && hasPar("initialLatitude") && hasPar("initialLongitude") && hasPar("initialAltitude")) {
         auto initialLatitude = deg(par("initialLatitude"));
         auto initialLongitude = deg(par("initialLongitude"));
         auto initialAltitude = m(par("initialAltitude"));
         lastPosition = coordinateSystem->computeSceneCoordinate(GeoCoord(initialLatitude, initialLongitude, initialAltitude));
         EV_DEBUG << "position initialized from initialLatitude/Longitude/Altitude parameters: " << lastPosition << endl;
     }
     else {
         lastPosition = getRandomPosition();
         EV_DEBUG << "position initialized by random values: " << lastPosition << endl;
     }
     if (par("updateDisplayString"))
         updateDisplayStringFromMobilityState();
 }
Referenced by initializePosition(), inet::RectangleMobility::setInitialPosition(), and inet::TurtleMobility::setInitialPosition().
updateDisplayStringFromMobilityState()
void inet::MobilityBase::updateDisplayStringFromMobilityState () const protected virtual
 {
     if (subjectModule != nullptr) {
         // position
         auto position = const_cast<MobilityBase *>(this)->getCurrentPosition();
         EV_TRACE << "current position = " << position << endl;
         auto subjectModulePosition = canvasProjection->computeCanvasPoint(position);
         char buf[32];
         snprintf(buf, sizeof(buf), "%lf", subjectModulePosition.x);
         buf[sizeof(buf) - 1] = 0;
         auto& displayString = subjectModule->getDisplayString();
         displayString.setTagArg("p", 0, buf);
         snprintf(buf, sizeof(buf), "%lf", subjectModulePosition.y);
         buf[sizeof(buf) - 1] = 0;
         displayString.setTagArg("p", 1, buf);
         // angle
         double angle = 0;
         auto angularPosition = const_cast<MobilityBase *>(this)->getCurrentAngularPosition();
         if (angularPosition != Quaternion::IDENTITY) {
             Quaternion swing;
             Quaternion twist;
             Coord vector = canvasProjection->computeCanvasPointInverse(cFigure::Point(0, 0), 1);
             vector.normalize();
             angularPosition.getSwingAndTwist(vector, swing, twist);
             Coord axis;
             twist.getRotationAxisAndAngle(axis, angle);
             angle = math::rad2deg(axis.z >= 0 ? angle : -angle);
         }
         snprintf(buf, sizeof(buf), "%lf", angle);
         displayString.setTagArg("a", 0, buf);
     }
 }
Referenced by refreshDisplay(), and setInitialPosition().
wrapIfOutside()
void inet::MobilityBase::wrapIfOutside (Coord & targetPosition) protected virtual
Utility function to wrap the node to the opposite edge (torus) if it goes outside the constraint area.
Decision is made on pos, but targetPosition will also be updated. (Pass a dummy you don't have it).
 {
     if (lastPosition.x < constraintAreaMin.x || constraintAreaMax.x < lastPosition.x) {
         wrap(constraintAreaMin.x, constraintAreaMax.x, lastPosition.x);
         wrap(constraintAreaMin.x, constraintAreaMax.x, targetPosition.x);
     }
     if (lastPosition.y < constraintAreaMin.y || constraintAreaMax.y < lastPosition.y) {
         wrap(constraintAreaMin.y, constraintAreaMax.y, lastPosition.y);
         wrap(constraintAreaMin.y, constraintAreaMax.y, targetPosition.y);
     }
     if (lastPosition.z < constraintAreaMin.z || constraintAreaMax.z < lastPosition.z) {
         wrap(constraintAreaMin.z, constraintAreaMax.z, lastPosition.z);
         wrap(constraintAreaMin.z, constraintAreaMax.z, targetPosition.z);
     }
 }
Referenced by handleIfOutside().
Member Data Documentation
canvasProjection
const CanvasProjection* inet::MobilityBase::canvasProjection protected
The 2D projection used on the canvas.
Referenced by initialize(), setInitialPosition(), updateDisplayStringFromMobilityState(), and inet::StationaryMobility::updateMobilityStateFromDisplayString().
constraintAreaMax
Coord inet::MobilityBase::constraintAreaMax protected
Referenced by checkPosition(), getRandomPosition(), inet::TurtleMobility::getValue(), inet::RectangleMobility::initialize(), initialize(), isOutside(), inet::RectangleMobility::move(), inet::GaussMarkovMobility::preventBorderHugging(), raiseErrorIfOutside(), reflectIfOutside(), inet::StaticLinearMobility::setInitialPosition(), and wrapIfOutside().
constraintAreaMin
Coord inet::MobilityBase::constraintAreaMin protected
3 dimensional position and size of the constraint area (in meters).
Referenced by checkPosition(), getRandomPosition(), inet::TurtleMobility::getValue(), inet::RectangleMobility::initialize(), initialize(), isOutside(), inet::RectangleMobility::move(), inet::GaussMarkovMobility::preventBorderHugging(), raiseErrorIfOutside(), reflectIfOutside(), inet::StaticGridMobility::setInitialPosition(), inet::StaticConcentricMobility::setInitialPosition(), and wrapIfOutside().
format
StringFormat inet::MobilityBase::format protected
Referenced by inet::FacingMobility::handleParameterChange(), handleParameterChange(), inet::FacingMobility::initialize(), initialize(), inet::StationaryMobility::refreshDisplay(), and refreshDisplay().
lastOrientation
Quaternion inet::MobilityBase::lastOrientation protected
The last orientation that was reported.
Referenced by inet::FacingMobility::getCurrentAngularPosition(), inet::SuperpositioningMobility::getCurrentAngularPosition(), inet::RotatingMobilityBase::getCurrentAngularPosition(), inet::MovingMobilityBase::getCurrentAngularPosition(), initialize(), initializeOrientation(), inet::MassMobility::orient(), inet::MovingMobilityBase::orient(), inet::LinearRotatingMobilityBase::rotate(), and inet::StationaryMobility::updateMobilityStateFromDisplayString().
lastPosition
Coord inet::MobilityBase::lastPosition protected
The last position that was reported.
Referenced by checkPosition(), inet::TurtleMobility::executeStatement(), inet::StaticLinearMobility::finish(), inet::AttachedMobility::getCurrentPosition(), inet::SuperpositioningMobility::getCurrentPosition(), inet::MovingMobilityBase::getCurrentPosition(), initialize(), inet::MoBanCoordinator::initialize(), inet::LineSegmentsMobilityBase::initializePosition(), isOutside(), inet::LineSegmentsMobilityBase::move(), inet::LinearMobility::move(), inet::GaussMarkovMobility::move(), inet::RectangleMobility::move(), inet::CircleMobility::move(), inet::MassMobility::move(), placeRandomlyIfOutside(), inet::GaussMarkovMobility::preventBorderHugging(), raiseErrorIfOutside(), inet::MoBanCoordinator::readConfigurationFile(), reflectIfOutside(), inet::MoBanLocal::refreshDisplay(), inet::TurtleMobility::resumeScript(), inet::MoBanCoordinator::selectDestination(), inet::MoBanCoordinator::selectPosture(), inet::StaticConcentricMobility::setInitialPosition(), inet::StaticGridMobility::setInitialPosition(), inet::BonnMotionMobility::setInitialPosition(), inet::StaticLinearMobility::setInitialPosition(), inet::AnsimMobility::setInitialPosition(), inet::TractorMobility::setInitialPosition(), inet::TurtleMobility::setInitialPosition(), inet::SuperpositioningMobility::setInitialPosition(), inet::Ns2MotionMobility::setInitialPosition(), inet::MoBanLocal::setInitialPosition(), setInitialPosition(), inet::MoBanLocal::setMoBANParameters(), inet::RandomWaypointMobility::setTargetPosition(), inet::ChiangMobility::setTargetPosition(), inet::AnsimMobility::setTargetPosition(), inet::BonnMotionMobility::setTargetPosition(), inet::TractorMobility::setTargetPosition(), inet::GaussMarkovMobility::setTargetPosition(), inet::MassMobility::setTargetPosition(), inet::Ns2MotionMobility::setTargetPosition(), inet::MoBanLocal::setTargetPosition(), inet::MoBanCoordinator::setTargetPosition(), inet::StationaryMobility::updateMobilityStateFromDisplayString(), and wrapIfOutside().
subjectModule
cModule* inet::MobilityBase::subjectModule protected
Pointer to visual representation module, to speed up repeated access.
Referenced by initialize(), inet::MoBanLocal::refreshDisplay(), inet::StaticConcentricMobility::setInitialPosition(), inet::StaticGridMobility::setInitialPosition(), inet::StaticLinearMobility::setInitialPosition(), setInitialPosition(), updateDisplayStringFromMobilityState(), and inet::StationaryMobility::updateMobilityStateFromDisplayString().
The documentation for this class was generated from the following files:
MobilityBase.h
MobilityBase.cc