INET Framework for OMNeT++/OMNEST: inet::Pim Class Reference
inet::Pim Class Reference
Compound module for PIM protocol (RFC 4601).
#include <Pim.h>
Public Member Functions
Pim ()
virtual ~Pim ()
CrcMode getCrcMode ()
Public Member Functions inherited from inet::RoutingProtocolBase
RoutingProtocolBase ()
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Static Public Member Functions
static void insertCrc (const Ptr< PimPacket > &pimPacket)
static void insertCrc (const Protocol *networkProtocol, const L3Address &srcAddress, const L3Address &destAddress, const Ptr< PimPacket > &pimPacket)
static bool verifyCrc (const Protocol *networkProtocol, const Ptr< const PimPacket > &pimPacket, Packet *packet)
static uint16_t computeCrc (const Protocol *networkProtocol, const L3Address &srcAddress, const L3Address &destAddress, const Ptr< const PimPacket > &pimPacket)
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessageWhenUp (cMessage *msg) override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
Protected Member Functions inherited from inet::RoutingProtocolBase
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
CrcMode crcMode = CRC_MODE_UNDEFINED
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Detailed Description
Compound module for PIM protocol (RFC 4601).
Constructor & Destructor Documentation
Pim()
inet::Pim::Pim () inline
 {}
~Pim()
inet::Pim::~Pim () virtual
 {
 }
Member Function Documentation
computeCrc()
uint16_t inet::Pim::computeCrc (const Protocol * networkProtocol, const L3Address & srcAddress, const L3Address & destAddress, const Ptr< const PimPacket > & pimPacket) static
 {
     MemoryOutputStream stream;
     if (networkProtocol == &Protocol::ipv6) {
         auto pseudoHeader = makeShared<TransportPseudoHeader>();
         pseudoHeader->setSrcAddress(srcAddress);
         pseudoHeader->setDestAddress(destAddress);
         pseudoHeader->setNetworkProtocolId(networkProtocol->getId());
         pseudoHeader->setProtocolId(IP_PROT_PIM);
         pseudoHeader->setPacketLength(pimPacket->getChunkLength());
         pseudoHeader->setChunkLength(B(40));
         Chunk::serialize(stream, pseudoHeader);
     }
     Chunk::serialize(stream, pimPacket);
     uint16_t crc = TcpIpChecksum::checksum(stream.getData());
     return crc;
 }
Referenced by insertCrc(), and verifyCrc().
getCrcMode()
CrcMode inet::Pim::getCrcMode () inline
 { return crcMode; }
handleCrashOperation()
void inet::Pim::handleCrashOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
 }
handleMessageWhenUp()
void inet::Pim::handleMessageWhenUp (cMessage * msg) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
     throw cRuntimeError("this module doesn't allow incoming packets");
 }
handleStartOperation()
void inet::Pim::handleStartOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
 }
handleStopOperation()
void inet::Pim::handleStopOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 {
 }
initialize()
void inet::Pim::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
 {
     RoutingProtocolBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         const char *crcModeString = par("crcMode");
         crcMode = parseCrcMode(crcModeString, false);
     }
     else if (stage == INITSTAGE_TRANSPORT_LAYER) {
         if (crcMode == CRC_COMPUTED) {
             cModuleType *moduleType = cModuleType::get("inet.routing.pim.PimCrcInsertionHook");
             auto crcInsertion = check_and_cast<PimCrcInsertionHook *>(moduleType->create("crcInsertion", this));
             crcInsertion->finalizeParameters();
             crcInsertion->callInitialize();
             // For IPv6, the checksum also includes the IPv6 "pseudo-header",
             // as specified in RFC 2460, Section 8.1 [5].  This
             // "pseudo-header" is prepended to the PIM header for the purposes
             // of calculating the checksum.  The "Upper-Layer Packet Length"
             // in the pseudo-header is set to the length of the PIM message,
             // except in Register messages where it is set to the length of
             // the PIM register header (8).  The Next Header value used in the
             // pseudo-header is 103.
 #ifdef INET_WITH_IPv6
             auto ipv6 = dynamic_cast<INetfilter *>(findModuleByPath("^.ipv6.ipv6"));
             if (ipv6 != nullptr)
                 ipv6->registerHook(0, crcInsertion);
 #endif
         }
     }
     else if (stage == INITSTAGE_ROUTING_PROTOCOLS) {
         registerProtocol(Protocol::pim, gate("networkLayerOut"), gate("networkLayerIn"));
     }
 }
insertCrc() [1/2]
void inet::Pim::insertCrc (const Protocol * networkProtocol, const L3Address & srcAddress, const L3Address & destAddress, const Ptr< PimPacket > & pimPacket) static
 {
     CrcMode crcMode = pimPacket->getCrcMode();
     switch (crcMode) {
         case CRC_DISABLED:
             // if the CRC mode is disabled, then the CRC is 0
             pimPacket->setCrc(0x0000);
             break;
         case CRC_DECLARED_CORRECT:
             // if the CRC mode is declared to be correct, then set the CRC to an easily recognizable value
             pimPacket->setCrc(0xC00D);
             break;
         case CRC_DECLARED_INCORRECT:
             // if the CRC mode is declared to be incorrect, then set the CRC to an easily recognizable value
             pimPacket->setCrc(0xBAAD);
             break;
         case CRC_COMPUTED: {
             // if the CRC mode is computed, then compute the CRC and set it
             // this computation is delayed after the routing decision, see INetfilter hook
             pimPacket->setCrc(0x0000); // make sure that the CRC is 0 in the Udp header before computing the CRC
             auto crc = computeCrc(networkProtocol, srcAddress, destAddress, pimPacket);
             pimPacket->setCrc(crc);
             break;
         }
         default:
             throw cRuntimeError("Unknown CRC mode: %d", (int)crcMode);
     }
 }
insertCrc() [2/2]
void inet::Pim::insertCrc (const Ptr< PimPacket > & pimPacket) static
 {
     insertCrc(&Protocol::ipv4, L3Address(), L3Address(), pimPacket);
 }
Referenced by inet::PimCrcInsertionHook::datagramPostRoutingHook(), inet::PimDm::sendAssertPacket(), inet::PimDm::sendGraftAckPacket(), inet::PimDm::sendGraftPacket(), inet::PimBase::sendHelloPacket(), inet::PimDm::sendJoinPacket(), inet::PimSm::sendPIMAssert(), inet::PimSm::sendPIMJoin(), inet::PimSm::sendPIMPrune(), inet::PimSm::sendPIMRegister(), inet::PimSm::sendPIMRegisterNull(), inet::PimSm::sendPIMRegisterStop(), inet::PimDm::sendPrunePacket(), and inet::PimDm::sendStateRefreshPacket().
numInitStages()
virtual int inet::Pim::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
verifyCrc()
bool inet::Pim::verifyCrc (const Protocol * networkProtocol, const Ptr< const PimPacket > & pimPacket, Packet * packet) static
 {
     switch (pimPacket->getCrcMode()) {
         case CRC_DISABLED:
             // if the CRC mode is disabled, then the check passes if the CRC is 0
             return pimPacket->getCrc() == 0x0000;
         case CRC_DECLARED_CORRECT: {
             // if the CRC mode is declared to be correct, then the check passes if and only if the chunks are correct
             auto totalLength = pimPacket->getChunkLength();
             auto udpDataBytes = packet->peekDataAt(B(0), totalLength - pimPacket->getChunkLength(), Chunk::PF_ALLOW_INCORRECT);
             return pimPacket->isCorrect() && udpDataBytes->isCorrect();
         }
         case CRC_DECLARED_INCORRECT:
             // if the CRC mode is declared to be incorrect, then the check fails
             return false;
         case CRC_COMPUTED: {
             auto l3AddressInd = packet->getTag<L3AddressInd>();
             auto srcAddress = l3AddressInd->getSrcAddress();
             auto destAddress = l3AddressInd->getDestAddress();
             auto computedCrc = computeCrc(networkProtocol, srcAddress, destAddress, pimPacket);
             return computedCrc == 0xFFFF;
         }
         default:
             throw cRuntimeError("Unknown CRC mode");
     }
 }
Member Data Documentation
crcMode
CrcMode inet::Pim::crcMode = CRC_MODE_UNDEFINED protected
Referenced by initialize(), and insertCrc().
The documentation for this class was generated from the following files:
Pim.h
Pim.cc