INET Framework for OMNeT++/OMNEST: inet::TcpServerThreadBase Class Reference
inet::TcpServerThreadBase Class Reference abstract
Abstract base class for server processes to be used with TcpServerHostApp.
#include <TcpServerHostApp.h>
Public Member Functions
TcpServerThreadBase ()
virtual ~TcpServerThreadBase ()
virtual void init (TcpServerHostApp *hostmodule, TcpSocket *socket)
virtual TcpSocket * getSocket ()
virtual TcpServerHostApp * getHostModule ()
virtual void established ()=0
Called when connection is established.
virtual void dataArrived (Packet *msg, bool urgent)=0
virtual void timerExpired (cMessage *timer)=0
virtual void peerClosed ()
virtual void failure (int code)
virtual void statusArrived (TcpStatusInfo *status)
Public Member Functions inherited from inet::TcpSocket::ICallback
virtual ~ICallback ()
Protected Member Functions
virtual void socketDataArrived (TcpSocket *socket, Packet *msg, bool urgent) override
Notifies about data arrival, packet ownership is transferred to the callee.
virtual void socketAvailable (TcpSocket *socket, TcpAvailableInfo *availableInfo) override
virtual void socketEstablished (TcpSocket *socket) override
virtual void socketPeerClosed (TcpSocket *socket) override
virtual void socketClosed (TcpSocket *socket) override
virtual void socketFailure (TcpSocket *socket, int code) override
virtual void socketStatusArrived (TcpSocket *socket, TcpStatusInfo *status) override
virtual void socketDeleted (TcpSocket *socket) override
virtual void refreshDisplay () const override
Protected Attributes
TcpServerHostApp * hostmod
TcpSocket * sock
Detailed Description
Abstract base class for server processes to be used with TcpServerHostApp.
Subclasses need to be registered using the Register_Class() macro.
See also
TcpServerHostApp
Constructor & Destructor Documentation
TcpServerThreadBase()
inet::TcpServerThreadBase::TcpServerThreadBase () inline
 { sock = nullptr; hostmod = nullptr; }
~TcpServerThreadBase()
virtual inet::TcpServerThreadBase::~TcpServerThreadBase () inline virtual
 { delete sock; }
Member Function Documentation
dataArrived()
virtual void inet::TcpServerThreadBase::dataArrived (Packet * msg, bool urgent) pure virtual
Implemented in inet::TcpEchoAppThread, inet::TcpSinkAppThread, and inet::TcpGenericServerThread.
established()
virtual void inet::TcpServerThreadBase::established () pure virtual
Called when connection is established.
To be redefined.
Implemented in inet::TcpEchoAppThread, inet::TcpSinkAppThread, and inet::TcpGenericServerThread.
failure()
virtual void inet::TcpServerThreadBase::failure (int code) inline virtual
 { hostmod->removeThread(this); }
getHostModule()
virtual TcpServerHostApp* inet::TcpServerThreadBase::getHostModule () inline virtual
 { return hostmod; }
getSocket()
virtual TcpSocket* inet::TcpServerThreadBase::getSocket () inline virtual
 { return sock; }
Referenced by inet::TcpGenericServerThread::dataArrived(), inet::TcpServerHostApp::removeThread(), and inet::TcpServerHostApp::threadClosed().
init()
virtual void inet::TcpServerThreadBase::init (TcpServerHostApp * hostmodule, TcpSocket * socket) inline virtual
Reimplemented in inet::TcpEchoAppThread, and inet::TcpSinkAppThread.
 { hostmod = hostmodule; sock = socket; }
Referenced by inet::TcpEchoAppThread::init(), inet::TcpSinkAppThread::init(), and inet::TcpServerHostApp::socketAvailable().
peerClosed()
virtual void inet::TcpServerThreadBase::peerClosed () inline virtual
 { getSocket()->close(); }
refreshDisplay()
void inet::TcpServerThreadBase::refreshDisplay () const override protected virtual
Reimplemented in inet::TcpSinkAppThread.
 {
     getDisplayString().setTagArg("t", 0, TcpSocket::stateName(sock->getState()));
 }
socketAvailable()
virtual void inet::TcpServerThreadBase::socketAvailable (TcpSocket * socket, TcpAvailableInfo * availableInfo) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { socket->accept(availableInfo->getNewSocketId()); }
socketClosed()
virtual void inet::TcpServerThreadBase::socketClosed (TcpSocket * socket) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { hostmod->threadClosed(this); }
socketDataArrived()
virtual void inet::TcpServerThreadBase::socketDataArrived (TcpSocket * socket, Packet * packet, bool urgent) inline override protected virtual
Notifies about data arrival, packet ownership is transferred to the callee.
Implements inet::TcpSocket::ICallback.
 { dataArrived(msg, urgent); }
socketDeleted()
void inet::TcpServerThreadBase::socketDeleted (TcpSocket * socket) override protected virtual
Implements inet::TcpSocket::ICallback.
 {
     if (socket == sock) {
         sock = nullptr;
         hostmod->socketDeleted(socket);
     }
 }
socketEstablished()
virtual void inet::TcpServerThreadBase::socketEstablished (TcpSocket * socket) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { established(); }
socketFailure()
virtual void inet::TcpServerThreadBase::socketFailure (TcpSocket * socket, int code) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { failure(code); }
socketPeerClosed()
virtual void inet::TcpServerThreadBase::socketPeerClosed (TcpSocket * socket) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { peerClosed(); }
socketStatusArrived()
virtual void inet::TcpServerThreadBase::socketStatusArrived (TcpSocket * socket, TcpStatusInfo * status) inline override protected virtual
Implements inet::TcpSocket::ICallback.
 { statusArrived(status); }
statusArrived()
virtual void inet::TcpServerThreadBase::statusArrived (TcpStatusInfo * status) inline virtual
 {}
timerExpired()
virtual void inet::TcpServerThreadBase::timerExpired (cMessage * timer) pure virtual
Implemented in inet::TcpEchoAppThread, inet::TcpSinkAppThread, and inet::TcpGenericServerThread.
Referenced by inet::TcpServerHostApp::handleMessageWhenUp().
Member Data Documentation
hostmod
TcpServerHostApp* inet::TcpServerThreadBase::hostmod protected
Referenced by socketDeleted().
sock
TcpSocket* inet::TcpServerThreadBase::sock protected
Referenced by inet::TcpEchoAppThread::dataArrived(), inet::TcpSinkAppThread::refreshDisplay(), refreshDisplay(), and socketDeleted().
The documentation for this class was generated from the following files:
TcpServerHostApp.h
TcpServerHostApp.cc