INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRecipientQosMacDataService Class Reference
inet::ieee80211::IRecipientQosMacDataService Class Reference abstract
#include <IRecipientQosMacDataService.h>
Public Member Functions
virtual ~IRecipientQosMacDataService ()
virtual std::vector< Packet * > dataFrameReceived (Packet *dataPacket, const Ptr< const Ieee80211DataHeader > &dataHeader, IRecipientBlockAckAgreementHandler *blockAckAgreementHandler)=0
virtual std::vector< Packet * > controlFrameReceived (Packet *controlPacket, const Ptr< const Ieee80211MacHeader > &controlHeader, IRecipientBlockAckAgreementHandler *blockAckAgreementHandler)=0
virtual std::vector< Packet * > managementFrameReceived (Packet *mgmtPacket, const Ptr< const Ieee80211MgmtHeader > &mgmtHeader)=0
Static Public Attributes
static simsignal_t packetDefragmentedSignal = cComponent::registerSignal("packetDefragmented")
static simsignal_t packetDeaggregatedSignal = cComponent::registerSignal("packetDeaggregated")
Constructor & Destructor Documentation
~IRecipientQosMacDataService()
virtual inet::ieee80211::IRecipientQosMacDataService::~IRecipientQosMacDataService () inline virtual
 {}
Member Function Documentation
controlFrameReceived()
virtual std::vector<Packet *> inet::ieee80211::IRecipientQosMacDataService::controlFrameReceived (Packet * controlPacket, const Ptr< const Ieee80211MacHeader > & controlHeader, IRecipientBlockAckAgreementHandler * blockAckAgreementHandler) pure virtual
Implemented in inet::ieee80211::RecipientQosMacDataService.
dataFrameReceived()
virtual std::vector<Packet *> inet::ieee80211::IRecipientQosMacDataService::dataFrameReceived (Packet * dataPacket, const Ptr< const Ieee80211DataHeader > & dataHeader, IRecipientBlockAckAgreementHandler * blockAckAgreementHandler) pure virtual
Implemented in inet::ieee80211::RecipientQosMacDataService.
managementFrameReceived()
virtual std::vector<Packet *> inet::ieee80211::IRecipientQosMacDataService::managementFrameReceived (Packet * mgmtPacket, const Ptr< const Ieee80211MgmtHeader > & mgmtHeader) pure virtual
Implemented in inet::ieee80211::RecipientQosMacDataService.
Member Data Documentation
packetDeaggregatedSignal
simsignal_t inet::ieee80211::IRecipientQosMacDataService::packetDeaggregatedSignal = cComponent::registerSignal("packetDeaggregated") static
Referenced by inet::ieee80211::RecipientQosMacDataService::controlFrameReceived(), and inet::ieee80211::RecipientQosMacDataService::dataFrameReceived().
packetDefragmentedSignal
simsignal_t inet::ieee80211::IRecipientQosMacDataService::packetDefragmentedSignal = cComponent::registerSignal("packetDefragmented") static
Referenced by inet::ieee80211::RecipientQosMacDataService::defragment().
The documentation for this class was generated from the following files:
IRecipientQosMacDataService.h
IRecipientQosMacDataService.cc