INET Framework for OMNeT++/OMNEST: inet::IndicatorLabelFigure Class Reference
inet::IndicatorLabelFigure Class Reference
#include <IndicatorLabelFigure.h>
Public Member Functions
IndicatorLabelFigure (const char *name=nullptr)
virtual const Point getSize () const override
virtual void setValue (int series, simtime_t timestamp, double value) override
virtual const char * getTextFormat () const
virtual void setTextFormat (const char *textFormat)
Public Member Functions inherited from inet::IIndicatorFigure
virtual ~IIndicatorFigure ()
virtual int getNumSeries () const
virtual void refreshDisplay ()
Protected Member Functions
virtual const char ** getAllowedPropertyKeys () const override
virtual void parse (cProperty *property) override
virtual void refresh ()
Protected Attributes
std::string textFormat = "%g"
double value = NaN
Constructor & Destructor Documentation
IndicatorLabelFigure()
inet::IndicatorLabelFigure::IndicatorLabelFigure (const char * name = nullptr) inline explicit
 : cLabelFigure(name) {}
Member Function Documentation
getAllowedPropertyKeys()
const char ** inet::IndicatorLabelFigure::getAllowedPropertyKeys () const override protected virtual
 {
     static const char *keys[32];
     if (!keys[0]) {
         const char *localKeys[] = {
             PKEY_TEXT_FORMAT, PKEY_INITIAL_VALUE, nullptr
         };
         concatArrays(keys, cLabelFigure::getAllowedPropertyKeys(), localKeys);
     }
     return keys;
 }
getSize()
virtual const Point inet::IndicatorLabelFigure::getSize () const inline override virtual
Implements inet::IIndicatorFigure.
 { return getBounds().getSize(); }
getTextFormat()
virtual const char* inet::IndicatorLabelFigure::getTextFormat () const inline virtual
 { return textFormat.c_str(); }
parse()
void inet::IndicatorLabelFigure::parse (cProperty * property) override protected virtual
 {
     cLabelFigure::parse(property);
     const char *s;
     if ((s = property->getValue(PKEY_TEXT_FORMAT)) != nullptr)
         setTextFormat(s);
     if ((s = property->getValue(PKEY_INITIAL_VALUE)) != nullptr)
         setValue(0, simTime(), utils::atod(s));
 }
refresh()
void inet::IndicatorLabelFigure::refresh () protected virtual
 {
     if (std::isnan(value)) {
         setText("");
     }
     else {
         char buf[64];
         sprintf(buf, textFormat.c_str(), value);
         setText(buf);
     }
 }
Referenced by setValue().
setTextFormat()
virtual void inet::IndicatorLabelFigure::setTextFormat (const char * textFormat) inline virtual
 { this->textFormat = textFormat; refresh(); }
Referenced by parse().
setValue()
void inet::IndicatorLabelFigure::setValue (int series, simtime_t timestamp, double value) override virtual
Implements inet::IIndicatorFigure.
 {
     // Note: we currently ignore timestamp
     ASSERT(series == 0);
     this->value = value;
     refresh();
 }
Referenced by parse().
Member Data Documentation
textFormat
std::string inet::IndicatorLabelFigure::textFormat = "%g" protected
Referenced by refresh().
value
double inet::IndicatorLabelFigure::value = NaN protected
Referenced by refresh(), and setValue().
The documentation for this class was generated from the following files:
IndicatorLabelFigure.h
IndicatorLabelFigure.cc