INET Framework for OMNeT++/OMNEST: inet::sctp::SctpDataMsg Class Reference
inet::sctp::SctpDataMsg Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:114 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpDataMsg (const char *name=nullptr)
SctpDataMsg (const SctpDataMsg &other)
virtual ~SctpDataMsg ()
SctpDataMsg & operator= (const SctpDataMsg &other)
virtual SctpDataMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getEBit () const
virtual void setEBit (bool eBit)
virtual bool getBBit () const
virtual void setBBit (bool bBit)
virtual ::omnetpp::simtime_t getEnqueuingTime () const
virtual void setEnqueuingTime (::omnetpp::simtime_t enqueuingTime)
virtual ::omnetpp::simtime_t getExpiryTime () const
virtual void setExpiryTime (::omnetpp::simtime_t expiryTime)
virtual uint32_t getPpid () const
virtual void setPpid (uint32_t ppid)
virtual const ::inet::L3Address & getInitialDestination () const
virtual ::inet::L3Address & getInitialDestinationForUpdate ()
virtual void setInitialDestination (const ::inet::L3Address &initialDestination)
virtual uint32_t getMsgNum () const
virtual void setMsgNum (uint32_t msgNum)
virtual uint16_t getSid () const
virtual void setSid (uint16_t sid)
virtual bool getOrdered () const
virtual void setOrdered (bool ordered)
virtual uint32_t getBooksize () const
virtual void setBooksize (uint32_t booksize)
virtual uint32_t getRtx () const
virtual void setRtx (uint32_t rtx)
virtual bool getFragment () const
virtual void setFragment (bool fragment)
virtual uint32_t getPrMethod () const
virtual void setPrMethod (uint32_t prMethod)
virtual uint32_t getPriority () const
virtual void setPriority (uint32_t priority)
virtual bool getStrReset () const
virtual void setStrReset (bool strReset)
virtual bool getSackNow () const
virtual void setSackNow (bool sackNow)
Protected Member Functions
bool operator== (const SctpDataMsg &)=delete
Protected Attributes
bool eBit = 0
bool bBit = 0
::omnetpp::simtime_t enqueuingTime = SIMTIME_ZERO
::omnetpp::simtime_t expiryTime = SIMTIME_ZERO
uint32_t ppid = 0
::inet::L3Address initialDestination
uint32_t msgNum = 0
uint16_t sid = 0
bool ordered = false
uint32_t booksize = 0
uint32_t rtx = 0
bool fragment = false
uint32_t prMethod = 0
uint32_t priority = 0
bool strReset = false
bool sackNow = false
Private Member Functions
void copy (const SctpDataMsg &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:114 by opp_msgtool.
class SctpDataMsg extends cPacket
{
    // Chunk Flags
    bool eBit = 0;
    bool bBit = 0;
    simtime_t enqueuingTime;
    simtime_t expiryTime;
    uint32_t ppid;
    L3Address initialDestination;
    uint32_t msgNum;
    uint16_t sid;
    bool ordered;
    uint32_t booksize;
    uint32_t rtx;
    bool fragment;
    uint32_t prMethod;
    uint32_t priority;
    bool strReset;
    bool sackNow;
}
Constructor & Destructor Documentation
SctpDataMsg() [1/2]
inet::sctp::SctpDataMsg::SctpDataMsg (const char * name = nullptr)
SctpDataMsg() [2/2]
inet::sctp::SctpDataMsg::SctpDataMsg (const SctpDataMsg & other)
~SctpDataMsg()
virtual inet::sctp::SctpDataMsg::~SctpDataMsg () virtual
Member Function Documentation
copy()
void inet::sctp::SctpDataMsg::copy (const SctpDataMsg & other) private
dup()
virtual SctpDataMsg* inet::sctp::SctpDataMsg::dup () const inline override virtual
 {return new SctpDataMsg(*this);}
getBBit()
virtual bool inet::sctp::SctpDataMsg::getBBit () const virtual
Referenced by inet::sctp::SctpAssociation::makeDataVarFromDataMsg(), and inet::sctp::SctpAssociation::sendOnPath().
getBooksize()
virtual uint32_t inet::sctp::SctpDataMsg::getBooksize () const virtual
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::makeDataVarFromDataMsg(), and inet::sctp::SctpAssociation::process_SEND().
getEBit()
virtual bool inet::sctp::SctpDataMsg::getEBit () const virtual
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), inet::sctp::SctpAssociation::makeDataVarFromDataMsg(), and inet::sctp::SctpAssociation::sendOnPath().
getEnqueuingTime()
virtual ::omnetpp::simtime_t inet::sctp::SctpDataMsg::getEnqueuingTime () const
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getExpiryTime()
virtual ::omnetpp::simtime_t inet::sctp::SctpDataMsg::getExpiryTime () const
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getFragment()
virtual bool inet::sctp::SctpDataMsg::getFragment () const virtual
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), and inet::sctp::SctpAssociation::sendOnPath().
getInitialDestination()
virtual const ::inet::L3Address& inet::sctp::SctpDataMsg::getInitialDestination () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
getInitialDestinationForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpDataMsg::getInitialDestinationForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpDataMsg*>(this)->getInitialDestination());}
getMsgNum()
virtual uint32_t inet::sctp::SctpDataMsg::getMsgNum () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs().
getOrdered()
virtual bool inet::sctp::SctpDataMsg::getOrdered () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getPpid()
virtual uint32_t inet::sctp::SctpDataMsg::getPpid () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getPriority()
virtual uint32_t inet::sctp::SctpDataMsg::getPriority () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::makeDataVarFromDataMsg(), and inet::sctp::SctpAssociation::process_SEND().
getPrMethod()
virtual uint32_t inet::sctp::SctpDataMsg::getPrMethod () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getRtx()
virtual uint32_t inet::sctp::SctpDataMsg::getRtx () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getSackNow()
virtual bool inet::sctp::SctpDataMsg::getSackNow () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getSid()
virtual uint16_t inet::sctp::SctpDataMsg::getSid () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::makeDataVarFromDataMsg(), and inet::sctp::SctpAssociation::sendOnPath().
getStrReset()
virtual bool inet::sctp::SctpDataMsg::getStrReset () const virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
operator=()
SctpDataMsg& inet::sctp::SctpDataMsg::operator= (const SctpDataMsg & other)
operator==()
bool inet::sctp::SctpDataMsg::operator== (const SctpDataMsg &) protected delete
parsimPack()
virtual void inet::sctp::SctpDataMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpDataMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::sctp::doParsimUnpacking().
setBBit()
virtual void inet::sctp::SctpDataMsg::setBBit (bool bBit) virtual
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), and inet::sctp::SctpAssociation::fragmentOutboundDataMsgs().
setBooksize()
virtual void inet::sctp::SctpDataMsg::setBooksize (uint32_t booksize) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setEBit()
virtual void inet::sctp::SctpDataMsg::setEBit (bool eBit) virtual
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), and inet::sctp::SctpAssociation::fragmentOutboundDataMsgs().
setEnqueuingTime()
virtual void inet::sctp::SctpDataMsg::setEnqueuingTime (::omnetpp::simtime_t enqueuingTime) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setExpiryTime()
virtual void inet::sctp::SctpDataMsg::setExpiryTime (::omnetpp::simtime_t expiryTime) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setFragment()
virtual void inet::sctp::SctpDataMsg::setFragment (bool fragment) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs().
setInitialDestination()
virtual void inet::sctp::SctpDataMsg::setInitialDestination (const ::inet::L3Address & initialDestination) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::makeDataVarFromDataMsg(), and inet::sctp::SctpAssociation::process_SEND().
setMsgNum()
virtual void inet::sctp::SctpDataMsg::setMsgNum (uint32_t msgNum) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setOrdered()
virtual void inet::sctp::SctpDataMsg::setOrdered (bool ordered) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setPpid()
virtual void inet::sctp::SctpDataMsg::setPpid (uint32_t ppid) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setPriority()
virtual void inet::sctp::SctpDataMsg::setPriority (uint32_t priority) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setPrMethod()
virtual void inet::sctp::SctpDataMsg::setPrMethod (uint32_t prMethod) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setRtx()
virtual void inet::sctp::SctpDataMsg::setRtx (uint32_t rtx) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setSackNow()
virtual void inet::sctp::SctpDataMsg::setSackNow (bool sackNow) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setSid()
virtual void inet::sctp::SctpDataMsg::setSid (uint16_t sid) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), and inet::sctp::SctpAssociation::process_SEND().
setStrReset()
virtual void inet::sctp::SctpDataMsg::setStrReset (bool strReset) virtual
Referenced by inet::sctp::SctpAssociation::fragmentOutboundDataMsgs().
Member Data Documentation
bBit
bool inet::sctp::SctpDataMsg::bBit = 0 protected
booksize
uint32_t inet::sctp::SctpDataMsg::booksize = 0 protected
eBit
bool inet::sctp::SctpDataMsg::eBit = 0 protected
enqueuingTime
::omnetpp::simtime_t inet::sctp::SctpDataMsg::enqueuingTime = SIMTIME_ZERO protected
expiryTime
::omnetpp::simtime_t inet::sctp::SctpDataMsg::expiryTime = SIMTIME_ZERO protected
fragment
bool inet::sctp::SctpDataMsg::fragment = false protected
initialDestination
::inet::L3Address inet::sctp::SctpDataMsg::initialDestination protected
msgNum
uint32_t inet::sctp::SctpDataMsg::msgNum = 0 protected
ordered
bool inet::sctp::SctpDataMsg::ordered = false protected
ppid
uint32_t inet::sctp::SctpDataMsg::ppid = 0 protected
priority
uint32_t inet::sctp::SctpDataMsg::priority = 0 protected
prMethod
uint32_t inet::sctp::SctpDataMsg::prMethod = 0 protected
rtx
uint32_t inet::sctp::SctpDataMsg::rtx = 0 protected
sackNow
bool inet::sctp::SctpDataMsg::sackNow = false protected
sid
uint16_t inet::sctp::SctpDataMsg::sid = 0 protected
strReset
bool inet::sctp::SctpDataMsg::strReset = false protected
The documentation for this class was generated from the following file:
SctpHeader_m.h