INET Framework for OMNeT++/OMNEST: inet::DriftingOscillatorBase Class Reference
inet::DriftingOscillatorBase Class Reference
#include <DriftingOscillatorBase.h>
Public Member Functions
virtual simtime_t getComputationOrigin () const override
Returns the oscillator computation origin from which the ticks are measured.
virtual simtime_t getNominalTickLength () const override
Returns the nominal time interval between subsequent ticks.
virtual simtime_t getCurrentTickLength () const
virtual void setDriftRate (double driftRate)
virtual void setTickOffset (simtime_t tickOffset)
virtual int64_t computeTicksForInterval (simtime_t timeInterval) const override
Returns the number of ticks in the specified time interval measured from the oscillator computation origin.
virtual simtime_t computeIntervalForTicks (int64_t numTicks) const override
Returns the smallest simulation time interval for the specified number of ticks measured from the oscillator computation origin.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::IOscillator
virtual ~IOscillator ()
Public Member Functions inherited from inet::IScriptable
virtual ~IScriptable ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void processCommand (const cXMLElement &node) override
Called by ScenarioManager whenever a script command needs to be carried out by the module.
double invertDriftRate (double driftRate) const
int64_t increaseWithDriftRate (int64_t value) const
int64_t increaseWithDriftRate (int64_t value, double driftRate) const
int64_t decreaseWithDriftRate (int64_t value) const
int64_t decreaseWithDriftRate (int64_t value, double inverseDriftRate) const
Protected Member Functions inherited from inet::OscillatorBase
virtual int numInitStages () const override
virtual void updateDisplayString () const
Protected Attributes
simtime_t nominalTickLength
double driftRate = NaN
double inverseDriftRate = NaN
simtime_t origin
simtime_t nextTickFromOrigin
Protected Attributes inherited from inet::OscillatorBase
const char * displayStringTextFormat = nullptr
Additional Inherited Members
Static Public Attributes inherited from inet::OscillatorBase
static simsignal_t driftRateChangedSignal = cComponent::registerSignal("driftRateChanged")
Static Public Attributes inherited from inet::IOscillator
static simsignal_t preOscillatorStateChangedSignal = cComponent::registerSignal("preOscillatorStateChanged")
static simsignal_t postOscillatorStateChangedSignal = cComponent::registerSignal("postOscillatorStateChanged")
Member Function Documentation
computeIntervalForTicks()
simtime_t inet::DriftingOscillatorBase::computeIntervalForTicks (int64_t numTicks) const override virtual
Returns the smallest simulation time interval for the specified number of ticks measured from the oscillator computation origin.
For example, for 0 ticks returns 0, for 1 tick returns the remaining time till the next tick, and so on.
Implements inet::IOscillator.
 {
     if (numTicks == 0)
         return 0;
     else if (nextTickFromOrigin == 0)
         return SimTime::fromRaw(decreaseWithDriftRate(nominalTickLength.raw() * numTicks));
     else
         return SimTime::fromRaw(decreaseWithDriftRate(nominalTickLength.raw() * (numTicks - 1))) + nextTickFromOrigin;
 }
computeTicksForInterval()
int64_t inet::DriftingOscillatorBase::computeTicksForInterval (simtime_t timeInterval) const override virtual
Returns the number of ticks in the specified time interval measured from the oscillator computation origin.
Note that each tick interval taken into consideration may be different from the nominal tick length. Returns the #ticks in (computation origin, computation origin + time interval].
Implements inet::IOscillator.
 {
     ASSERT(timeInterval >= 0);
     return increaseWithDriftRate(timeInterval.raw() + nextTickFromOrigin.raw()) / nominalTickLength.raw();
 }
decreaseWithDriftRate() [1/2]
int64_t inet::DriftingOscillatorBase::decreaseWithDriftRate (int64_t value) const inline protected
 { return decreaseWithDriftRate(value, inverseDriftRate); }
Referenced by computeIntervalForTicks(), decreaseWithDriftRate(), and setDriftRate().
decreaseWithDriftRate() [2/2]
int64_t inet::DriftingOscillatorBase::decreaseWithDriftRate (int64_t value, double inverseDriftRate) const inline protected
 { return value + (int64_t)(value * inverseDriftRate); }
getComputationOrigin()
virtual simtime_t inet::DriftingOscillatorBase::getComputationOrigin () const inline override virtual
Returns the oscillator computation origin from which the ticks are measured.
There may or may not be an actual tick at the returned simulation time.
Implements inet::IOscillator.
 { return origin; }
getCurrentTickLength()
virtual simtime_t inet::DriftingOscillatorBase::getCurrentTickLength () const inline virtual
 { return SimTime::fromRaw(decreaseWithDriftRate(nominalTickLength.raw())); }
Referenced by initialize(), resolveDirective(), setDriftRate(), and setTickOffset().
getNominalTickLength()
virtual simtime_t inet::DriftingOscillatorBase::getNominalTickLength () const inline override virtual
Returns the nominal time interval between subsequent ticks.
This value is usually different from the actual amount of elapsed time between ticks.
Implements inet::IOscillator.
 { return nominalTickLength; }
increaseWithDriftRate() [1/2]
int64_t inet::DriftingOscillatorBase::increaseWithDriftRate (int64_t value) const inline protected
 { return increaseWithDriftRate(value, driftRate); }
Referenced by computeTicksForInterval(), increaseWithDriftRate(), and setDriftRate().
increaseWithDriftRate() [2/2]
int64_t inet::DriftingOscillatorBase::increaseWithDriftRate (int64_t value, double driftRate) const inline protected
 { return value + (int64_t)(value * driftRate); }
initialize()
void inet::DriftingOscillatorBase::initialize (int stage) override protected virtual
Reimplemented from inet::OscillatorBase.
Reimplemented in inet::RandomDriftOscillator, and inet::ConstantDriftOscillator.
 {
     OscillatorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         nominalTickLength = par("nominalTickLength");
         if (nominalTickLength == 0)
             nominalTickLength.setRaw(1);
         inverseDriftRate = invertDriftRate(driftRate);
         origin = simTime();
         simtime_t currentTickLength = getCurrentTickLength();
         simtime_t tickOffset = par("tickOffset");
         if (tickOffset < 0 || tickOffset >= currentTickLength)
             throw cRuntimeError("First tick offset must be in the range [0, currentTickLength)");
         if (tickOffset == 0)
             nextTickFromOrigin = 0;
         else
             nextTickFromOrigin = currentTickLength - tickOffset;
         WATCH(nominalTickLength);
         WATCH(driftRate);
         WATCH(inverseDriftRate);
         WATCH(nextTickFromOrigin);
     }
 }
Referenced by inet::ConstantDriftOscillator::initialize(), and inet::RandomDriftOscillator::initialize().
invertDriftRate()
double inet::DriftingOscillatorBase::invertDriftRate (double driftRate) const inline protected
 { return 1 / (1 + driftRate) - 1; }
Referenced by initialize(), and setDriftRate().
processCommand()
void inet::DriftingOscillatorBase::processCommand (const cXMLElement & node) override protected virtual
Called by ScenarioManager whenever a script command needs to be carried out by the module.
The command is represented by the XML element or element tree. The command name can be obtained as:
const char *command = node->getTagName()
Parameters are XML attributes, e.g. a "neighbour" parameter can be retrieved as:
const char *attr = node->getAttribute("neighbour")
More complex input can be passed in child elements.
See also
cXMLElement
Implements inet::IScriptable.
 {
     Enter_Method("processCommand");
     if (!strcmp(node.getTagName(), "set-oscillator")) {
         if (const char *driftRateStr = node.getAttribute("drift-rate")) {
             double newDriftRate = strtod(driftRateStr, nullptr) / 1E+6;
             setDriftRate(newDriftRate);
         }
         if (const char *tickOffsetStr = node.getAttribute("tick-offset")) {
             simtime_t newTickOffset = SimTime::parse(tickOffsetStr);
             setTickOffset(newTickOffset);
         }
     }
     else
         throw cRuntimeError("Invalid command: %s", node.getTagName());
 }
resolveDirective()
const char * inet::DriftingOscillatorBase::resolveDirective (char directive) const override virtual
Reimplemented from inet::OscillatorBase.
 {
     static std::string result;
     switch (directive) {
         case 'c':
             result = getCurrentTickLength().str() + " s";
             break;
         case 'd':
             result = std::to_string((int64_t)(driftRate * 1E+6)) + " ppm";
             break;
         default:
             return OscillatorBase::resolveDirective(directive);
     }
     return result.c_str();
 }
setDriftRate()
void inet::DriftingOscillatorBase::setDriftRate (double driftRate) virtual
 {
     Enter_Method("setDriftRate");
     if (newDriftRate != driftRate) {
         emit(preOscillatorStateChangedSignal, this);
         simtime_t currentSimTime = simTime();
         EV_DEBUG << "Setting oscillator drift rate from " << driftRate << " to " << newDriftRate << " at simtime " << currentSimTime << ".\n";
         simtime_t currentTickLength = getCurrentTickLength();
         simtime_t baseTickTime = origin + nextTickFromOrigin - currentTickLength;
         simtime_t elapsedTickTime = fmod(currentSimTime - baseTickTime, currentTickLength);
         double newInverseDriftRate = invertDriftRate(newDriftRate);
         if (elapsedTickTime == SIMTIME_ZERO)
             nextTickFromOrigin = 0;
         else {
             int64_t v = increaseWithDriftRate(currentTickLength.raw() - elapsedTickTime.raw());
             nextTickFromOrigin = SimTime::fromRaw(decreaseWithDriftRate(v, newInverseDriftRate));
         }
         driftRate = newDriftRate;
         inverseDriftRate = newInverseDriftRate;
         origin = currentSimTime;
         emit(driftRateChangedSignal, driftRate);
         emit(postOscillatorStateChangedSignal, this);
         updateDisplayString();
     }
 }
Referenced by inet::RandomDriftOscillator::handleMessage(), and processCommand().
setTickOffset()
void inet::DriftingOscillatorBase::setTickOffset (simtime_t tickOffset) virtual
 {
     Enter_Method("setTickOffset");
     simtime_t currentSimTime = simTime();
     simtime_t currentTickLength = getCurrentTickLength();
     simtime_t baseTickTime = origin + nextTickFromOrigin - currentTickLength;
     simtime_t oldTickOffset = fmod(currentSimTime - baseTickTime, currentTickLength);
     if (newTickOffset != oldTickOffset) {
         emit(preOscillatorStateChangedSignal, this);
         EV_DEBUG << "Setting oscillator tick offset from " << oldTickOffset << " to " << newTickOffset << " at simtime " << currentSimTime << ".\n";
         origin = currentSimTime;
         if (newTickOffset == 0)
             nextTickFromOrigin = 0;
         else
             nextTickFromOrigin = currentTickLength - newTickOffset;
         emit(postOscillatorStateChangedSignal, this);
         updateDisplayString();
     }
 }
Referenced by processCommand().
Member Data Documentation
driftRate
double inet::DriftingOscillatorBase::driftRate = NaN protected
Referenced by inet::RandomDriftOscillator::handleMessage(), inet::ConstantDriftOscillator::initialize(), initialize(), inet::RandomDriftOscillator::initialize(), resolveDirective(), and setDriftRate().
inverseDriftRate
double inet::DriftingOscillatorBase::inverseDriftRate = NaN protected
Referenced by initialize(), and setDriftRate().
nextTickFromOrigin
simtime_t inet::DriftingOscillatorBase::nextTickFromOrigin protected
Referenced by computeIntervalForTicks(), computeTicksForInterval(), initialize(), setDriftRate(), and setTickOffset().
nominalTickLength
simtime_t inet::DriftingOscillatorBase::nominalTickLength protected
Referenced by computeIntervalForTicks(), computeTicksForInterval(), and initialize().
origin
simtime_t inet::DriftingOscillatorBase::origin protected
Referenced by initialize(), setDriftRate(), and setTickOffset().
The documentation for this class was generated from the following files:
DriftingOscillatorBase.h
DriftingOscillatorBase.cc