INET Framework for OMNeT++/OMNEST: inet::physicallayer::AdditiveScrambler Class Reference
inet::physicallayer::AdditiveScrambler Class Reference
#include <AdditiveScrambler.h>
Public Member Functions
AdditiveScrambler (const AdditiveScrambling *scrambling)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
BitVector scramble (const BitVector &bits) const override
BitVector descramble (const BitVector &bits) const override
const AdditiveScrambling * getScrambling () const override
const BitVector & getScramblingSequcene () const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool eXOR (bool alpha, bool beta) const
BitVector generateScramblingSequence (const ShortBitVector &generatorPolynomial, const ShortBitVector &seed) const
Protected Attributes
BitVector scramblingSequence
const AdditiveScrambling * scrambling
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
AdditiveScrambler()
inet::physicallayer::AdditiveScrambler::AdditiveScrambler (const AdditiveScrambling * scrambling)
                                                                          : scrambling(scrambling)
 {
     ShortBitVector generatorPolynomial = scrambling->getGeneratorPolynomial();
     ShortBitVector seed = scrambling->getSeed();
     scramblingSequence = generateScramblingSequence(generatorPolynomial, seed);
 }
Member Function Documentation
descramble()
BitVector inet::physicallayer::AdditiveScrambler::descramble (const BitVector & bits) const inline override virtual
Implements inet::physicallayer::IScrambler.
 { return scramble(bits); }
Referenced by inet::physicallayer::AdditiveScramblerModule::descramble().
eXOR()
bool inet::physicallayer::AdditiveScrambler::eXOR (bool alpha, bool beta) const inline protected
 { return alpha != beta; }
Referenced by generateScramblingSequence(), and scramble().
generateScramblingSequence()
BitVector inet::physicallayer::AdditiveScrambler::generateScramblingSequence (const ShortBitVector & generatorPolynomial, const ShortBitVector & seed) const protected
 {
     BitVector scramblingSequence;
     int sequenceLength = (int)pow(2, seed.getSize()) - 1;
     ShortBitVector shiftRegisters = seed;
     for (int i = 0; i < sequenceLength; i++) {
         bool registerSum = false;
         for (unsigned int j = 0; j < generatorPolynomial.getSize(); j++) {
             if (generatorPolynomial.getBit(j))
                 registerSum = eXOR(shiftRegisters.getBit(j), registerSum);
         }
         shiftRegisters.leftShift(1);
         shiftRegisters.setBit(0, registerSum);
         scramblingSequence.appendBit(registerSum);
     }
     return scramblingSequence;
 }
Referenced by AdditiveScrambler().
getScrambling()
const AdditiveScrambling* inet::physicallayer::AdditiveScrambler::getScrambling () const inline override virtual
Implements inet::physicallayer::IScrambler.
 { return scrambling; }
Referenced by inet::physicallayer::AdditiveScramblerModule::getScrambling(), and inet::physicallayer::AdditiveScramblerModule::~AdditiveScramblerModule().
getScramblingSequcene()
const BitVector& inet::physicallayer::AdditiveScrambler::getScramblingSequcene () const inline
 { return scramblingSequence; }
printToStream()
std::ostream & inet::physicallayer::AdditiveScrambler::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "AdditiveScrambler";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(scrambling, printFieldToString(scrambling, level + 1, evFlags));
     return stream;
 }
Referenced by inet::physicallayer::AdditiveScramblerModule::printToStream().
scramble()
BitVector inet::physicallayer::AdditiveScrambler::scramble (const BitVector & bits) const override virtual
Implements inet::physicallayer::IScrambler.
 {
     EV_DEBUG << "Scrambling the following bits: " << bits << endl;
     BitVector scrambledBits;
     int sequenceLength = scramblingSequence.getSize();
     for (unsigned int i = 0; i < bits.getSize(); i++) {
         int scramblingIndex = i % sequenceLength;
         bool scrambledBit = eXOR(bits.getBit(i), scramblingSequence.getBit(scramblingIndex));
         scrambledBits.appendBit(scrambledBit);
     }
     EV_DEBUG << "The scrambled bits are: " << scrambledBits << endl;
     return scrambledBits;
 }
Referenced by inet::physicallayer::AdditiveScramblerModule::scramble().
Member Data Documentation
scrambling
const AdditiveScrambling* inet::physicallayer::AdditiveScrambler::scrambling protected
Referenced by AdditiveScrambler(), and printToStream().
scramblingSequence
BitVector inet::physicallayer::AdditiveScrambler::scramblingSequence protected
Referenced by AdditiveScrambler(), generateScramblingSequence(), and scramble().
The documentation for this class was generated from the following files:
AdditiveScrambler.h
AdditiveScrambler.cc