INET Framework for OMNeT++/OMNEST: inet::SctpResetReq Class Reference
inet::SctpResetReq Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:183 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpResetReq ()
SctpResetReq (const SctpResetReq &other)
virtual ~SctpResetReq ()
SctpResetReq & operator= (const SctpResetReq &other)
virtual SctpResetReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getRequestType () const
virtual void setRequestType (unsigned short requestType)
virtual uint16_t getInstreams () const
virtual void setInstreams (uint16_t instreams)
virtual uint16_t getOutstreams () const
virtual void setOutstreams (uint16_t outstreams)
virtual void setStreamsArraySize (size_t size)
virtual size_t getStreamsArraySize () const
virtual uint16_t getStreams (size_t k) const
virtual void setStreams (size_t k, uint16_t streams)
virtual void insertStreams (size_t k, uint16_t streams)
void insertStreams (uint16_t streams)
virtual void appendStreams (uint16_t streams)
virtual void eraseStreams (size_t k)
Public Member Functions inherited from inet::SctpCommandReq
SctpCommandReq ()
SctpCommandReq (const SctpCommandReq &other)
virtual ~SctpCommandReq ()
SctpCommandReq & operator= (const SctpCommandReq &other)
virtual int getSocketId () const
virtual void setSocketId (int socketId)
virtual int getSid () const
virtual void setSid (int sid)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs)
virtual int getSsn () const
virtual void setSsn (int ssn)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered)
virtual double getPrValue () const
virtual void setPrValue (double prValue)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getGate () const
virtual void setGate (int gate)
virtual int getFd () const
virtual void setFd (int fd)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SctpResetReq &)=delete
Protected Member Functions inherited from inet::SctpCommandReq
bool operator== (const SctpCommandReq &)=delete
Protected Attributes
unsigned short requestType = 0
uint16_t instreams = 0
uint16_t outstreams = 0
uint16_t * streams = nullptr
size_t streams_arraysize = 0
Protected Attributes inherited from inet::SctpCommandReq
int socketId = -1
int sid = -1
int numMsgs = 1
int ssn = -1
unsigned short sendUnordered = false
double prValue = 0
L3Address localAddr
L3Address remoteAddr
int localPort = -1
int remotePort = -1
int gate = -1
int fd = -1
Private Member Functions
void copy (const SctpResetReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:183 by opp_msgtool.
class SctpResetReq extends SctpCommandReq
{
    unsigned short requestType = 0;
    uint16_t instreams = 0;
    uint16_t outstreams = 0;
    uint16_t streams[];
}
Constructor & Destructor Documentation
SctpResetReq() [1/2]
inet::SctpResetReq::SctpResetReq ()
SctpResetReq() [2/2]
inet::SctpResetReq::SctpResetReq (const SctpResetReq & other)
~SctpResetReq()
virtual inet::SctpResetReq::~SctpResetReq () virtual
Member Function Documentation
appendStreams()
virtual void inet::SctpResetReq::appendStreams (uint16_t streams) virtual
copy()
void inet::SctpResetReq::copy (const SctpResetReq & other) private
dup()
virtual SctpResetReq* inet::SctpResetReq::dup () const inline override virtual
Reimplemented from inet::SctpCommandReq.
 {return new SctpResetReq(*this);}
Referenced by inet::sctp::SctpAssociation::process_STREAM_RESET().
eraseStreams()
virtual void inet::SctpResetReq::eraseStreams (size_t k) virtual
getInstreams()
virtual uint16_t inet::SctpResetReq::getInstreams () const virtual
Referenced by inet::sctp::SctpAssociation::makeAddStreamsRequestParameter(), and inet::sctp::SctpAssociation::sendAddInAndOutStreamsRequest().
getOutstreams()
virtual uint16_t inet::SctpResetReq::getOutstreams () const virtual
Referenced by inet::sctp::SctpAssociation::makeAddStreamsRequestParameter(), and inet::sctp::SctpAssociation::sendAddInAndOutStreamsRequest().
getRequestType()
virtual unsigned short inet::SctpResetReq::getRequestType () const virtual
Referenced by inet::sctp::SctpAssociation::process_STREAM_RESET(), and inet::sctp::SctpAssociation::sendStreamResetRequest().
getStreams()
virtual uint16_t inet::SctpResetReq::getStreams (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::makeIncomingStreamResetParameter(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), and inet::sctp::SctpAssociation::process_STREAM_RESET().
getStreamsArraySize()
virtual size_t inet::SctpResetReq::getStreamsArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::makeIncomingStreamResetParameter(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), and inet::sctp::SctpAssociation::process_STREAM_RESET().
insertStreams() [1/2]
virtual void inet::SctpResetReq::insertStreams (size_t k, uint16_t streams) virtual
insertStreams() [2/2]
void inet::SctpResetReq::insertStreams (uint16_t streams) inline
 {appendStreams(streams);}
operator=()
SctpResetReq& inet::SctpResetReq::operator= (const SctpResetReq & other)
operator==()
bool inet::SctpResetReq::operator== (const SctpResetReq &) protected delete
parsimPack()
virtual void inet::SctpResetReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpResetReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimUnpacking().
setInstreams()
virtual void inet::SctpResetReq::setInstreams (uint16_t instreams) virtual
setOutstreams()
virtual void inet::SctpResetReq::setOutstreams (uint16_t outstreams) virtual
setRequestType()
virtual void inet::SctpResetReq::setRequestType (unsigned short requestType) virtual
setStreams()
virtual void inet::SctpResetReq::setStreams (size_t k, uint16_t streams) virtual
setStreamsArraySize()
virtual void inet::SctpResetReq::setStreamsArraySize (size_t size) virtual
Member Data Documentation
instreams
uint16_t inet::SctpResetReq::instreams = 0 protected
outstreams
uint16_t inet::SctpResetReq::outstreams = 0 protected
requestType
unsigned short inet::SctpResetReq::requestType = 0 protected
streams
uint16_t* inet::SctpResetReq::streams = nullptr protected
streams_arraysize
size_t inet::SctpResetReq::streams_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpCommand_m.h