INET Framework for OMNeT++/OMNEST: inet::NetworkConfiguratorBase Class Reference
inet::NetworkConfiguratorBase Class Reference
#include <NetworkConfiguratorBase.h>
Classes
class Interface
Represents an interface in the network.
class Link
class Node
Represents a node in the network.
class Topology
Protected Member Functions
virtual ~NetworkConfiguratorBase ()
virtual int numInitStages () const override
virtual void handleMessage (cMessage *msg) override
virtual void extractTopology (Topology &topology)
Extracts network topology by walking through the module hierarchy.
virtual std::vector< Node * > computeShortestNodePath (Node *source, Node *destination) const
virtual std::vector< Link * > computeShortestLinkPath (Node *source, Node *destination) const
virtual bool isBridgeNode (Node *node) const
virtual Link * findLinkIn (const Node *node, const char *neighbor) const
virtual Link * findLinkOut (const Node *node, const char *neighbor) const
virtual Link * findLinkOut (const Node *node, const Node *neighbor) const
virtual Link * findLinkOut (const Interface *interface) const
virtual Topology::Link * findLinkOut (const Node *node, int gateId) const
virtual Interface * findInterface (const Node *node, NetworkInterface *networkInterface) const
Protected Attributes
Topology * topology = nullptr
Constructor & Destructor Documentation
~NetworkConfiguratorBase()
virtual inet::NetworkConfiguratorBase::~NetworkConfiguratorBase () inline protected virtual
 { delete topology; }
Member Function Documentation
computeShortestLinkPath()
std::vector< NetworkConfiguratorBase::Link * > inet::NetworkConfiguratorBase::computeShortestLinkPath (Node * source, Node * destination) const protected virtual
 {
     std::vector<Link *> path;
     topology->calculateUnweightedSingleShortestPathsTo(destination);
     auto node = source;
     while (node != destination) {
         auto link = (Link *)node->getPath(0);
         path.push_back(link);
         node = (Node *)node->getPath(0)->getLinkOutRemoteNode();
     }
     return path;
 }
computeShortestNodePath()
std::vector< NetworkConfiguratorBase::Node * > inet::NetworkConfiguratorBase::computeShortestNodePath (Node * source, Node * destination) const protected virtual
 {
     std::vector<Node *> path;
     topology->calculateUnweightedSingleShortestPathsTo(destination);
     auto node = source;
     while (node != destination) {
         path.push_back(node);
         node = (Node *)node->getPath(0)->getLinkOutRemoteNode();
     }
     path.push_back(destination);
     return path;
 }
Referenced by inet::GateScheduleConfiguratorBase::addFlows().
extractTopology()
void inet::NetworkConfiguratorBase::extractTopology (Topology & topology) protected virtual
Extracts network topology by walking through the module hierarchy.
Creates nodes from modules having @networkNode property. Creates links from connections (wired and wireless) between network interfaces.
 {
     topology.extractByProperty("networkNode");
     EV_DEBUG << "Topology found " << topology.getNumNodes() << " nodes\n";
     if (topology.getNumNodes() == 0)
         throw cRuntimeError("Empty network!");
     // extract nodes, fill in interfaceTable and routingTable members in node
     L3AddressResolver addressResolver;
     for (int i = 0; i < topology.getNumNodes(); i++) {
         Node *node = (Node *)topology.getNode(i);
         node->module = node->getModule();
         node->interfaceTable = addressResolver.findInterfaceTableOf(node->module);
         node->routingTable = addressResolver.findIpv4RoutingTableOf(node->module);
     }
     // extract links and interfaces
     std::set<NetworkInterface *> interfacesSeen;
     std::queue<Node *> unvisited; // unvisited nodes in the graph
     auto rootNode = (Node *)topology.getNode(0);
     unvisited.push(rootNode);
     while (!unvisited.empty()) {
         Node *node = unvisited.front();
         unvisited.pop();
         IInterfaceTable *interfaceTable = node->interfaceTable;
         if (interfaceTable) {
             // push neighbors to the queue
             for (int i = 0; i < interfaceTable->getNumInterfaces(); i++) {
                 NetworkInterface *networkInterface = interfaceTable->getInterface(i);
                 if (interfacesSeen.count(networkInterface) == 0) {
                     // visiting this interface
                     interfacesSeen.insert(networkInterface);
                     Topology::Link *linkOut = findLinkOut(node, networkInterface->getNodeOutputGateId());
                     Node *childNode = nullptr;
                     if (linkOut) {
                         childNode = (Node *)linkOut->getLinkOutRemoteNode();
                         unvisited.push(childNode);
                     }
                     Interface *interface = new Interface(node, networkInterface);
                     node->interfaces.push_back(interface);
                 }
             }
         }
     }
     // annotate links with interfaces
     for (int i = 0; i < topology.getNumNodes(); i++) {
         Node *node = (Node *)topology.getNode(i);
         for (int j = 0; j < node->getNumOutLinks(); j++) {
             Topology::Link *linkOut = node->getLinkOut(j);
             Link *link = (Link *)linkOut;
             Node *localNode = (Node *)linkOut->getLinkOutLocalNode();
             if (localNode->interfaceTable)
                 link->sourceInterface = findInterface(localNode, localNode->interfaceTable->findInterfaceByNodeOutputGateId(linkOut->getLinkOutLocalGateId()));
             Node *remoteNode = (Node *)linkOut->getLinkOutRemoteNode();
             if (remoteNode->interfaceTable)
                 link->destinationInterface = findInterface(remoteNode, remoteNode->interfaceTable->findInterfaceByNodeInputGateId(linkOut->getLinkOutRemoteGateId()));
         }
     }
 }
Referenced by inet::MacForwardingTableConfigurator::computeConfiguration(), inet::FailureProtectionConfigurator::computeConfiguration(), inet::StreamRedundancyConfigurator::computeConfiguration(), and inet::GateScheduleConfiguratorBase::computeConfiguration().
findInterface()
NetworkConfiguratorBase::Interface * inet::NetworkConfiguratorBase::findInterface (const Node * node, NetworkInterface * networkInterface) const protected virtual
 {
     if (networkInterface == nullptr)
         return nullptr;
     for (auto& interface : node->interfaces)
         if (interface->networkInterface == networkInterface)
             return interface;
     return nullptr;
 }
Referenced by inet::GateScheduleConfiguratorBase::addPorts(), extractTopology(), and inet::MacForwardingTableConfigurator::receiveSignal().
findLinkIn()
NetworkConfiguratorBase::Link * inet::NetworkConfiguratorBase::findLinkIn (const Node * node, const char * neighbor) const protected virtual
 {
     for (int i = 0; i < node->getNumInLinks(); i++)
         if (!strcmp(node->getLinkIn(i)->getLinkInRemoteNode()->getModule()->getFullName(), neighbor))
             return check_and_cast<Link *>(static_cast<Topology::Link *>(node->getLinkIn(i)));
     return nullptr;
 }
Referenced by inet::StreamRedundancyConfigurator::computeStreamPolicyConfigurations().
findLinkOut() [1/4]
NetworkConfiguratorBase::Link * inet::NetworkConfiguratorBase::findLinkOut (const Interface * interface) const protected virtual
 {
     for (int i = 0; i < interface->node->getNumOutLinks(); i++) {
         auto link = check_and_cast<Link *>(static_cast<Topology::Link *>(interface->node->getLinkOut(i)));
         if (link->sourceInterface == interface)
             return link;
     }
     return nullptr;
 }
findLinkOut() [2/4]
NetworkConfiguratorBase::Link * inet::NetworkConfiguratorBase::findLinkOut (const Node * node, const char * neighbor) const protected virtual
 {
     for (int i = 0; i < node->getNumOutLinks(); i++)
         if (!strcmp(node->getLinkOut(i)->getLinkOutRemoteNode()->getModule()->getFullName(), neighbor))
             return check_and_cast<Link *>(static_cast<Topology::Link *>(node->getLinkOut(i)));
     return nullptr;
 }
Referenced by inet::GateScheduleConfiguratorBase::addPorts(), inet::EagerGateScheduleConfigurator::computeStartOffsetForPathFragments(), inet::StreamRedundancyConfigurator::computeStreamSendersAndReceivers(), and extractTopology().
findLinkOut() [3/4]
NetworkConfiguratorBase::Link * inet::NetworkConfiguratorBase::findLinkOut (const Node * node, const Node * neighbor) const protected virtual
 {
     for (int i = 0; i < node->getNumOutLinks(); i++)
         if (node->getLinkOut(i)->getLinkOutRemoteNode() == neighbor)
             return check_and_cast<Link *>(static_cast<Topology::Link *>(node->getLinkOut(i)));
     return nullptr;
 }
findLinkOut() [4/4]
Topology::Link * inet::NetworkConfiguratorBase::findLinkOut (const Node * node, int gateId) const protected virtual
 {
     for (int i = 0; i < node->getNumOutLinks(); i++)
         if (node->getLinkOut(i)->getLinkOutLocalGateId() == gateId)
             return node->getLinkOut(i);
     return nullptr;
 }
handleMessage()
virtual void inet::NetworkConfiguratorBase::handleMessage (cMessage * msg) inline override protected virtual
Reimplemented in inet::GateScheduleConfiguratorBase.
 { throw cRuntimeError("Invalid operation"); }
isBridgeNode()
bool inet::NetworkConfiguratorBase::isBridgeNode (Node * node) const protected virtual
 {
     return !node->routingTable || !node->interfaceTable;
 }
Referenced by inet::GateScheduleConfiguratorBase::addDevices(), inet::GateScheduleConfiguratorBase::addSwitches(), inet::MacForwardingTableConfigurator::computeMacForwardingTables(), and inet::MacForwardingTableConfigurator::extendConfiguration().
numInitStages()
virtual int inet::NetworkConfiguratorBase::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
Member Data Documentation
topology
Topology* inet::NetworkConfiguratorBase::topology = nullptr protected
Referenced by inet::GateScheduleConfiguratorBase::addDevices(), inet::GateScheduleConfiguratorBase::addFlows(), inet::GateScheduleConfiguratorBase::addPorts(), inet::GateScheduleConfiguratorBase::addSwitches(), inet::StreamRedundancyConfigurator::clearConfiguration(), inet::GateScheduleConfiguratorBase::clearConfiguration(), inet::MacForwardingTableConfigurator::computeConfiguration(), inet::FailureProtectionConfigurator::computeConfiguration(), inet::StreamRedundancyConfigurator::computeConfiguration(), inet::GateScheduleConfiguratorBase::computeConfiguration(), inet::MacForwardingTableConfigurator::computeMacForwardingTables(), computeShortestLinkPath(), computeShortestNodePath(), inet::EagerGateScheduleConfigurator::computeStartOffsetForPathFragments(), inet::FailureProtectionConfigurator::computeStream(), inet::StreamRedundancyConfigurator::computeStreamEncodings(), inet::StreamRedundancyConfigurator::computeStreamPolicyConfigurations(), inet::StreamRedundancyConfigurator::computeStreamSendersAndReceivers(), inet::GateScheduleConfiguratorBase::configureGateScheduling(), inet::StreamRedundancyConfigurator::configureStreams(), inet::MacForwardingTableConfigurator::extendConfiguration(), extractTopology(), inet::StreamRedundancyConfigurator::getPathFragments(), and inet::MacForwardingTableConfigurator::receiveSignal().
The documentation for this class was generated from the following files:
NetworkConfiguratorBase.h
NetworkConfiguratorBase.cc