INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2LsaHeader Class Reference
inet::ospfv2::Ospfv2LsaHeader Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:90 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2LsaHeader ()
Ospfv2LsaHeader (const Ospfv2LsaHeader &other)
virtual ~Ospfv2LsaHeader ()
Ospfv2LsaHeader & operator= (const Ospfv2LsaHeader &other)
virtual Ospfv2LsaHeader * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getLsAge () const
virtual void setLsAge (unsigned short lsAge)
virtual const Ospfv2Options & getLsOptions () const
virtual Ospfv2Options & getLsOptionsForUpdate ()
virtual void setLsOptions (const Ospfv2Options &lsOptions)
virtual Ospfv2LsaType getLsType () const
virtual void setLsType (Ospfv2LsaType lsType)
virtual const ::inet::Ipv4Address & getLinkStateID () const
virtual ::inet::Ipv4Address & getLinkStateIDForUpdate ()
virtual void setLinkStateID (const ::inet::Ipv4Address &linkStateID)
virtual const ::inet::Ipv4Address & getAdvertisingRouter () const
virtual ::inet::Ipv4Address & getAdvertisingRouterForUpdate ()
virtual void setAdvertisingRouter (const ::inet::Ipv4Address &advertisingRouter)
virtual int32_t getLsSequenceNumber () const
virtual void setLsSequenceNumber (int32_t lsSequenceNumber)
virtual uint16_t getLsCrc () const
virtual void setLsCrc (uint16_t lsCrc)
virtual ::inet::CrcMode getLsCrcMode () const
virtual void setLsCrcMode (::inet::CrcMode lsCrcMode)
virtual uint16_t getLsaLength () const
virtual void setLsaLength (uint16_t lsaLength)
Protected Member Functions
bool operator== (const Ospfv2LsaHeader &)=delete
Protected Attributes
unsigned short lsAge = 0
Ospfv2Options lsOptions
Ospfv2LsaType lsType = static_cast<Ospfv2LsaType>(-1)
::inet::Ipv4Address linkStateID
::inet::Ipv4Address advertisingRouter
int32_t lsSequenceNumber = 0
uint16_t lsCrc = 0
::inet::CrcMode lsCrcMode = CRC_MODE_UNDEFINED
uint16_t lsaLength = 0
Private Member Functions
void copy (const Ospfv2LsaHeader &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:90 by opp_msgtool.
//
// Represents an OSPF LSA header
//
class Ospfv2LsaHeader extends cObject
{
    @packetData;
    unsigned short lsAge = 0;
    Ospfv2Options lsOptions;
    Ospfv2LsaType lsType = static_cast<Ospfv2LsaType>(-1);
    Ipv4Address linkStateID;
    Ipv4Address advertisingRouter;
    int32_t lsSequenceNumber = 0;
    uint16_t lsCrc = 0;
    CrcMode lsCrcMode = CRC_MODE_UNDEFINED;
    uint16_t lsaLength = 0;
}
Constructor & Destructor Documentation
Ospfv2LsaHeader() [1/2]
inet::ospfv2::Ospfv2LsaHeader::Ospfv2LsaHeader ()
Ospfv2LsaHeader() [2/2]
inet::ospfv2::Ospfv2LsaHeader::Ospfv2LsaHeader (const Ospfv2LsaHeader & other)
~Ospfv2LsaHeader()
virtual inet::ospfv2::Ospfv2LsaHeader::~Ospfv2LsaHeader () virtual
Member Function Documentation
copy()
void inet::ospfv2::Ospfv2LsaHeader::copy (const Ospfv2LsaHeader & other) private
dup()
virtual Ospfv2LsaHeader* inet::ospfv2::Ospfv2LsaHeader::dup () const inline override virtual
 {return new Ospfv2LsaHeader(*this);}
getAdvertisingRouter()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2LsaHeader::getAdvertisingRouter () const virtual
Referenced by inet::ospfv2::Neighbor::addToRetransmissionList(), inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Ospfv2Area::installNetworkLSA(), inet::ospfv2::Ospfv2Area::installRouterLSA(), inet::ospfv2::Ospfv2Area::installSummaryLSA(), inet::ospfv2::operator<<(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::ospfv2::Neighbor::sendLinkStateRequestPacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
getAdvertisingRouterForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2LsaHeader::getAdvertisingRouterForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2LsaHeader*>(this)->getAdvertisingRouter());}
getLinkStateID()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2LsaHeader::getLinkStateID () const virtual
Referenced by inet::ospfv2::Neighbor::addToRetransmissionList(), inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2::checkExternalRoute(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Ospfv2Area::installNetworkLSA(), inet::ospfv2::Ospfv2Area::installRouterLSA(), inet::ospfv2::Ospfv2Area::installSummaryLSA(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::ospfv2::Neighbor::sendLinkStateRequestPacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
getLinkStateIDForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2LsaHeader::getLinkStateIDForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2LsaHeader*>(this)->getLinkStateID());}
getLsAge()
virtual unsigned short inet::ospfv2::Ospfv2LsaHeader::getLsAge () const virtual
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Neighbor::createDatabaseSummary(), inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::operator<(), inet::ospfv2::operator<<(), inet::ospfv2::operator==(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader(), and inet::ospfv2::setLsaHeaderCrc().
getLsaLength()
virtual uint16_t inet::ospfv2::Ospfv2LsaHeader::getLsaLength () const virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Router::installLSA(), inet::ospfv2::operator<<(), and inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
getLsCrc()
virtual uint16_t inet::ospfv2::Ospfv2LsaHeader::getLsCrc () const virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
getLsCrcMode()
virtual ::inet::CrcMode inet::ospfv2::Ospfv2LsaHeader::getLsCrcMode () const
Referenced by inet::ospfv2::operator<<(), and inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
getLsOptions()
virtual const Ospfv2Options& inet::ospfv2::Ospfv2LsaHeader::getLsOptions () const virtual
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::AsExternalLsa::differsFrom(), and inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
getLsOptionsForUpdate()
virtual Ospfv2Options& inet::ospfv2::Ospfv2LsaHeader::getLsOptionsForUpdate () inline virtual
 { return const_cast<Ospfv2Options&>(const_cast<Ospfv2LsaHeader*>(this)->getLsOptions());}
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader().
getLsSequenceNumber()
virtual int32_t inet::ospfv2::Ospfv2LsaHeader::getLsSequenceNumber () const virtual
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::operator<(), inet::ospfv2::operator<<(), inet::ospfv2::operator==(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader(), and inet::ospfv2::NeighborState::updateLsa().
getLsType()
virtual Ospfv2LsaType inet::ospfv2::Ospfv2LsaHeader::getLsType () const virtual
Referenced by inet::ospfv2::Neighbor::addToRetransmissionList(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::calculateLSASize(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsa(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Router::floodLSA(), inet::ospfv2::Router::installLSA(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::ospfv2::Neighbor::sendLinkStateRequestPacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeLsaHeader().
operator=()
Ospfv2LsaHeader& inet::ospfv2::Ospfv2LsaHeader::operator= (const Ospfv2LsaHeader & other)
operator==()
bool inet::ospfv2::Ospfv2LsaHeader::operator== (const Ospfv2LsaHeader &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2LsaHeader::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2LsaHeader::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::ospfv2::doParsimUnpacking().
setAdvertisingRouter()
virtual void inet::ospfv2::Ospfv2LsaHeader::setAdvertisingRouter (const ::inet::Ipv4Address & advertisingRouter) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Router::updateExternalRoute().
setLinkStateID()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLinkStateID (const ::inet::Ipv4Address & linkStateID) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Router::updateExternalRoute().
setLsAge()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsAge (unsigned short lsAge) virtual
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::Router::originateASExternalLSA(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::setLsaHeaderCrc(), inet::ospfv2::Router::updateExternalRoute(), and inet::ospfv2::NeighborState::updateLsa().
setLsaLength()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsaLength (uint16_t lsaLength) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Router::updateExternalRoute().
setLsCrc()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsCrc (uint16_t lsCrc) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), and inet::ospfv2::setLsaHeaderCrc().
setLsCrcMode()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsCrcMode (::inet::CrcMode lsCrcMode) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::setLsaCrc(), and inet::ospfv2::setLsaHeaderCrc().
setLsOptions()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsOptions (const Ospfv2Options & lsOptions) virtual
Referenced by inet::ospfv2::Router::originateASExternalLSA(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Router::updateExternalRoute().
setLsSequenceNumber()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsSequenceNumber (int32_t lsSequenceNumber) virtual
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::Router::originateASExternalLSA(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Router::updateExternalRoute(), and inet::ospfv2::NeighborState::updateLsa().
setLsType()
virtual void inet::ospfv2::Ospfv2LsaHeader::setLsType (Ospfv2LsaType lsType) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Router::updateExternalRoute().
Member Data Documentation
advertisingRouter
::inet::Ipv4Address inet::ospfv2::Ospfv2LsaHeader::advertisingRouter protected
linkStateID
::inet::Ipv4Address inet::ospfv2::Ospfv2LsaHeader::linkStateID protected
lsAge
unsigned short inet::ospfv2::Ospfv2LsaHeader::lsAge = 0 protected
lsaLength
uint16_t inet::ospfv2::Ospfv2LsaHeader::lsaLength = 0 protected
lsCrc
uint16_t inet::ospfv2::Ospfv2LsaHeader::lsCrc = 0 protected
lsCrcMode
::inet::CrcMode inet::ospfv2::Ospfv2LsaHeader::lsCrcMode = CRC_MODE_UNDEFINED protected
lsOptions
Ospfv2Options inet::ospfv2::Ospfv2LsaHeader::lsOptions protected
lsSequenceNumber
int32_t inet::ospfv2::Ospfv2LsaHeader::lsSequenceNumber = 0 protected
lsType
Ospfv2LsaType inet::ospfv2::Ospfv2LsaHeader::lsType = static_cast<Ospfv2LsaType>(-1) protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h