INET Framework for OMNeT++/OMNEST: inet::power::EpEnergyStorageBase Class Reference
inet::power::EpEnergyStorageBase Class Reference
#include <EpEnergyStorageBase.h>
Public Member Functions
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
virtual void receiveSignal (cComponent *source, simsignal_t signal, double value, cObject *details) override
Public Member Functions inherited from inet::power::EpEnergySourceBase
virtual W getTotalPowerConsumption () const override
Returns the total power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Public Member Functions inherited from inet::power::EpEnergySinkBase
virtual W getTotalPowerGeneration () const override
Returns the total power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Public Member Functions inherited from inet::power::IEpEnergyStorage
virtual J getNominalEnergyCapacity () const =0
Returns the nominal energy capacity in the range [0, +infinity].
virtual J getResidualEnergyCapacity () const =0
Returns the residual energy capacity in the range [0, nominalCapacity].
Protected Member Functions
virtual void initialize (int stage) override
virtual void updateTotalPowerConsumption () override
virtual void updateTotalPowerGeneration () override
Protected Member Functions inherited from inet::power::EpEnergySourceBase
virtual W computeTotalPowerConsumption () const
Protected Member Functions inherited from inet::power::EpEnergySinkBase
virtual W computeTotalPowerGeneration () const
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergySource
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Static Public Attributes inherited from inet::power::IEpEnergySink
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Static Public Attributes inherited from inet::power::IEpEnergyStorage
static simsignal_t residualEnergyCapacityChangedSignal = cComponent::registerSignal("residualEnergyCapacityChanged")
The signal that is used to publish residual energy capacity changes also including when the energy storage becomes completely depleted or charged.
Protected Attributes inherited from inet::power::EpEnergySourceBase
W totalPowerConsumption = W(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Protected Attributes inherited from inet::power::EpEnergySinkBase
W totalPowerGeneration = W(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Member Function Documentation
addEnergyConsumer()
void inet::power::EpEnergyStorageBase::addEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Adds a new energy consumer to the energy source.
The energyConsumer parameter must not be nullptr.
Reimplemented from inet::power::EpEnergySourceBase.
 {
     Enter_Method("addEnergyConsumer");
     EpEnergySourceBase::addEnergyConsumer(energyConsumer);
 }
addEnergyGenerator()
void inet::power::EpEnergyStorageBase::addEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Adds a new energy generator to the energy sink.
The energyGenerator parameter must not be nullptr.
Reimplemented from inet::power::EpEnergySinkBase.
 {
     Enter_Method("addEnergyGenerator");
     EpEnergySinkBase::addEnergyGenerator(energyGenerator);
 }
initialize()
void inet::power::EpEnergyStorageBase::initialize (int stage) override protected virtual
Reimplemented in inet::power::SimpleEpEnergyStorage, and inet::power::IdealEpEnergyStorage.
 {
     if (stage == INITSTAGE_LOCAL) {
         totalPowerConsumption = computeTotalPowerConsumption();
         totalPowerGeneration = computeTotalPowerGeneration();
         WATCH(totalPowerConsumption);
         WATCH(totalPowerGeneration);
     }
 }
Referenced by inet::power::IdealEpEnergyStorage::initialize(), and inet::power::SimpleEpEnergyStorage::initialize().
receiveSignal()
void inet::power::EpEnergyStorageBase::receiveSignal (cComponent * source, simsignal_t signal, double value, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == IEpEnergyConsumer::powerConsumptionChangedSignal)
         updateTotalPowerConsumption();
     else if (signal == IEpEnergyGenerator::powerGenerationChangedSignal)
         updateTotalPowerGeneration();
 }
removeEnergyConsumer()
void inet::power::EpEnergyStorageBase::removeEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Removes a previously added energy consumer from this energy source.
This functions throws an exception if the consumer is not found.
Reimplemented from inet::power::EpEnergySourceBase.
 {
     Enter_Method("removeEnergyConsumer");
     EpEnergySourceBase::removeEnergyConsumer(energyConsumer);
 }
removeEnergyGenerator()
void inet::power::EpEnergyStorageBase::removeEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Removes a previously added energy generator from this energy sink.
This functions throws an exception if the generator is not found.
Reimplemented from inet::power::EpEnergySinkBase.
 {
     Enter_Method("removeEnergyGenerator");
     EpEnergySinkBase::removeEnergyGenerator(energyGenerator);
 }
updateTotalPowerConsumption()
void inet::power::EpEnergyStorageBase::updateTotalPowerConsumption () override protected virtual
Reimplemented from inet::power::EpEnergySourceBase.
Reimplemented in inet::power::SimpleEpEnergyStorage, and inet::power::IdealEpEnergyStorage.
 {
     EpEnergySourceBase::updateTotalPowerConsumption();
     emit(powerConsumptionChangedSignal, totalPowerConsumption.get());
 }
Referenced by receiveSignal(), inet::power::IdealEpEnergyStorage::updateTotalPowerConsumption(), and inet::power::SimpleEpEnergyStorage::updateTotalPowerConsumption().
updateTotalPowerGeneration()
void inet::power::EpEnergyStorageBase::updateTotalPowerGeneration () override protected virtual
Reimplemented from inet::power::EpEnergySinkBase.
Reimplemented in inet::power::SimpleEpEnergyStorage, and inet::power::IdealEpEnergyStorage.
 {
     EpEnergySinkBase::updateTotalPowerGeneration();
     emit(powerGenerationChangedSignal, totalPowerGeneration.get());
 }
Referenced by receiveSignal(), inet::power::IdealEpEnergyStorage::updateTotalPowerGeneration(), and inet::power::SimpleEpEnergyStorage::updateTotalPowerGeneration().
The documentation for this class was generated from the following files:
EpEnergyStorageBase.h
EpEnergyStorageBase.cc