INET Framework for OMNeT++/OMNEST: inet::sctp::SctpShutdownChunk Class Reference
inet::sctp::SctpShutdownChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:206 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpShutdownChunk (const char *name=nullptr)
SctpShutdownChunk (const SctpShutdownChunk &other)
virtual ~SctpShutdownChunk ()
SctpShutdownChunk & operator= (const SctpShutdownChunk &other)
virtual SctpShutdownChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getCumTsnAck () const
virtual void setCumTsnAck (uint32_t cumTsnAck)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpShutdownChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint32_t cumTsnAck = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpShutdownChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:206 by opp_msgtool.
class SctpShutdownChunk extends SctpChunk
{
    uint32_t cumTsnAck;
}
Constructor & Destructor Documentation
SctpShutdownChunk() [1/2]
inet::sctp::SctpShutdownChunk::SctpShutdownChunk (const char * name = nullptr)
SctpShutdownChunk() [2/2]
inet::sctp::SctpShutdownChunk::SctpShutdownChunk (const SctpShutdownChunk & other)
~SctpShutdownChunk()
virtual inet::sctp::SctpShutdownChunk::~SctpShutdownChunk () virtual
Member Function Documentation
copy()
void inet::sctp::SctpShutdownChunk::copy (const SctpShutdownChunk & other) private
dup()
virtual SctpShutdownChunk* inet::sctp::SctpShutdownChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpShutdownChunk(*this);}
Referenced by inet::sctp::SctpAssociation::retransmitShutdown(), and inet::sctp::SctpAssociation::sendShutdown().
getCumTsnAck()
virtual uint32_t inet::sctp::SctpShutdownChunk::getCumTsnAck () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpShutdownChunk& inet::sctp::SctpShutdownChunk::operator= (const SctpShutdownChunk & other)
operator==()
bool inet::sctp::SctpShutdownChunk::operator== (const SctpShutdownChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpShutdownChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpShutdownChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setCumTsnAck()
virtual void inet::sctp::SctpShutdownChunk::setCumTsnAck (uint32_t cumTsnAck) virtual
Referenced by inet::sctp::SctpAssociation::sendShutdown().
Member Data Documentation
cumTsnAck
uint32_t inet::sctp::SctpShutdownChunk::cumTsnAck = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h