INET Framework for OMNeT++/OMNEST: inet::ieee80211::OriginatorProtectionMechanism Class Reference
inet::ieee80211::OriginatorProtectionMechanism Class Reference
#include <OriginatorProtectionMechanism.h>
Public Member Functions
virtual ~OriginatorProtectionMechanism ()
virtual simtime_t computeDurationField (Packet *packet, const Ptr< const Ieee80211MacHeader > &header, Packet *pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > &pendingHeader)
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual simtime_t computeRtsDurationField (Packet *rtsPacket, const Ptr< const Ieee80211RtsFrame > &rtsFrame, Packet *pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > &pendingHeader)
virtual simtime_t computeDataFrameDurationField (Packet *dataPacket, const Ptr< const Ieee80211DataHeader > &dataHeader, Packet *pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > &pendingHeader)
virtual simtime_t computeMgmtFrameDurationField (Packet *mgmtPacket, const Ptr< const Ieee80211MgmtHeader > &mgmtHeader, Packet *pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > &pendingHeader)
Protected Member Functions inherited from inet::ieee80211::ModeSetListener
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Protected Attributes
IRateSelection * rateSelection = nullptr
Protected Attributes inherited from inet::ieee80211::ModeSetListener
physicallayer::Ieee80211ModeSet * modeSet = nullptr
Constructor & Destructor Documentation
~OriginatorProtectionMechanism()
virtual inet::ieee80211::OriginatorProtectionMechanism::~OriginatorProtectionMechanism () inline virtual
 {}
Member Function Documentation
computeDataFrameDurationField()
simtime_t inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField (Packet * dataPacket, const Ptr< const Ieee80211DataHeader > & dataHeader, Packet * pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > & pendingHeader) protected virtual
 {
     simtime_t ackToDataFrameDuration = rateSelection->computeResponseAckFrameMode(dataPacket, dataHeader)->getDuration(LENGTH_ACK);
     if (dataHeader->getReceiverAddress().isMulticast())
         return 0;
     if (!dataHeader->getMoreFragments())
         return ackToDataFrameDuration + modeSet->getSifsTime();
     else {
         simtime_t pendingFrameDuration = rateSelection->computeMode(pendingPacket, pendingHeader)->getDuration(pendingPacket->getDataLength());
         auto pendingFrameMode = rateSelection->computeMode(pendingPacket, pendingHeader);
         RateSelection::setFrameMode(pendingPacket, pendingHeader, pendingFrameMode);
         simtime_t ackToPendingFrame = pendingFrameMode->getDuration(LENGTH_ACK);
         return pendingFrameDuration + ackToDataFrameDuration + ackToPendingFrame + 3 * modeSet->getSifsTime();
     }
 }
Referenced by computeDurationField().
computeDurationField()
simtime_t inet::ieee80211::OriginatorProtectionMechanism::computeDurationField (Packet * packet, const Ptr< const Ieee80211MacHeader > & header, Packet * pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > & pendingHeader) virtual
 {
     if (auto rtsFrame = dynamicPtrCast<const Ieee80211RtsFrame>(header))
         return computeRtsDurationField(packet, rtsFrame, pendingPacket, pendingHeader);
     else if (auto dataHeader = dynamicPtrCast<const Ieee80211DataHeader>(header))
         return computeDataFrameDurationField(packet, dataHeader, pendingPacket, pendingHeader);
     else if (auto mgmtHeader = dynamicPtrCast<const Ieee80211MgmtHeader>(header))
         return computeMgmtFrameDurationField(packet, mgmtHeader, pendingPacket, pendingHeader);
     else
         throw cRuntimeError("Unknown frame");
 }
computeMgmtFrameDurationField()
simtime_t inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField (Packet * mgmtPacket, const Ptr< const Ieee80211MgmtHeader > & mgmtHeader, Packet * pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > & pendingHeader) protected virtual
 {
     simtime_t ackFrameDuration = rateSelection->computeResponseAckFrameMode(mgmtPacket, mgmtHeader)->getDuration(LENGTH_ACK);
     if (mgmtHeader->getReceiverAddress().isMulticast())
         return 0;
     if (!mgmtHeader->getMoreFragments()) {
         return ackFrameDuration + modeSet->getSifsTime();
     }
     else {
         simtime_t pendingFrameDuration = rateSelection->computeMode(pendingPacket, pendingHeader)->getDuration(pendingPacket->getDataLength());
         return pendingFrameDuration + 2 * ackFrameDuration + 3 * modeSet->getSifsTime();
     }
 }
Referenced by computeDurationField().
computeRtsDurationField()
simtime_t inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField (Packet * rtsPacket, const Ptr< const Ieee80211RtsFrame > & rtsFrame, Packet * pendingPacket, const Ptr< const Ieee80211DataOrMgmtHeader > & pendingHeader) protected virtual
 {
     auto pendingFrameMode = rateSelection->computeMode(pendingPacket, pendingHeader);
     RateSelection::setFrameMode(pendingPacket, pendingHeader, pendingFrameMode); // KLUDGE
     simtime_t pendingFrameDuration = pendingFrameMode->getDuration(pendingPacket->getDataLength());
     simtime_t ctsFrameDuration = rateSelection->computeResponseCtsFrameMode(rtsPacket, rtsFrame)->getDuration(LENGTH_CTS);
     simtime_t ackFrameDuration = rateSelection->computeResponseAckFrameMode(pendingPacket, pendingHeader)->getDuration(LENGTH_ACK);
     simtime_t durationId = ctsFrameDuration + pendingFrameDuration + ackFrameDuration;
     return durationId + 3 * modeSet->getSifsTime();
 }
Referenced by computeDurationField().
initialize()
void inet::ieee80211::OriginatorProtectionMechanism::initialize (int stage) override protected virtual
Reimplemented from inet::ieee80211::ModeSetListener.
 {
     ModeSetListener::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         rateSelection = check_and_cast<IRateSelection *>(getModuleByPath(par("rateSelectionModule")));
     }
 }
numInitStages()
virtual int inet::ieee80211::OriginatorProtectionMechanism::numInitStages () const inline override protected virtual
Reimplemented from inet::ieee80211::ModeSetListener.
 { return NUM_INIT_STAGES; }
Member Data Documentation
rateSelection
IRateSelection* inet::ieee80211::OriginatorProtectionMechanism::rateSelection = nullptr protected
Referenced by computeDataFrameDurationField(), computeMgmtFrameDurationField(), computeRtsDurationField(), and initialize().
The documentation for this class was generated from the following files:
OriginatorProtectionMechanism.h
OriginatorProtectionMechanism.cc