INET Framework for OMNeT++/OMNEST: inet::visualizer::PathCanvasVisualizerBase Class Reference
inet::visualizer::PathCanvasVisualizerBase Class Reference
#include <PathCanvasVisualizerBase.h>
Classes
class PathCanvasVisualization
Protected Member Functions
virtual void initialize (int stage) override
virtual void refreshDisplay () const override
virtual const PathVisualization * createPathVisualization (const char *label, const std::vector< int > &path, cPacket *packet) const override
virtual void addPathVisualization (const PathVisualization *pathVisualization) override
virtual void removePathVisualization (const PathVisualization *pathVisualization) override
virtual void setAlpha (const PathVisualization *pathVisualization, double alpha) const override
virtual void refreshPathVisualization (const PathVisualization *pathVisualization, cPacket *packet) override
Protected Member Functions inherited from inet::visualizer::PathVisualizerBase
virtual void handleParameterChange (const char *name) override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual bool isPathStart (cModule *module) const =0
virtual bool isPathEnd (cModule *module) const =0
virtual bool isPathElement (cModule *module) const =0
virtual void processPathStart (cModule *networkNode, const char *label, Packet *packet)
virtual void processPathElement (cModule *networkNode, const char *label, Packet *packet)
virtual void processPathEnd (cModule *networkNode, const char *label, Packet *packet)
virtual const PathVisualization * getPathVisualization (const std::vector< int > &path)
virtual void removeAllPathVisualizations ()
virtual const std::vector< int > * getIncompletePath (const std::string &label, int chunkId)
virtual void addToIncompletePath (const std::string &label, int chunkId, cModule *module)
virtual void removeIncompletePath (const std::string &label, int chunkId)
virtual std::string getPathVisualizationText (const PathVisualization *pathVisualization, cPacket *packet) const
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes
double zIndex = NaN
const CanvasProjection * canvasProjection = nullptr
cGroupFigure * pathGroup = nullptr
Protected Attributes inherited from inet::visualizer::PathVisualizerBase
bool displayRoutes = false
NetworkNodeFilter nodeFilter
PacketFilter packetFilter
ColorSet lineColorSet
cFigure::LineStyle lineStyle
double lineWidth = NaN
bool lineSmooth = false
double lineShift = NaN
const char * lineShiftMode = nullptr
double lineContactSpacing = NaN
const char * lineContactMode = nullptr
StringFormat labelFormat
cFigure::Font labelFont
const char * labelColorAsString = nullptr
cFigure::Color labelColor
const char * fadeOutMode = nullptr
double fadeOutTime = NaN
double fadeOutAnimationSpeed = NaN
simsignal_t startPathSignal = -1
simsignal_t extendPathSignal = -1
simsignal_t endPathSignal = -1
LineManager * lineManager = nullptr
std::map< std::pair< std::string, int >, std::vector< int > > incompletePaths
Maps path label and chunk id to module id vector.
std::map< int, int > numPaths
Maps nodes to the number of paths that go through it.
std::multimap< std::pair< int, int >, const PathVisualization * > pathVisualizations
Maps source/destination modules to multiple paths between them.
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Additional Inherited Members
Public Member Functions inherited from inet::visualizer::PathVisualizerBase
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Member Function Documentation
addPathVisualization()
void inet::visualizer::PathCanvasVisualizerBase::addPathVisualization (const PathVisualization * pathVisualization) override protected virtual
Reimplemented from inet::visualizer::PathVisualizerBase.
 {
     PathVisualizerBase::addPathVisualization(pathVisualization);
     auto pathCanvasVisualization = static_cast<const PathCanvasVisualization *>(pathVisualization);
     lineManager->addModulePath(pathVisualization);
     pathGroup->addFigure(pathCanvasVisualization->figure);
 }
createPathVisualization()
const PathVisualizerBase::PathVisualization * inet::visualizer::PathCanvasVisualizerBase::createPathVisualization (const char * label, const std::vector< int > & path, cPacket * packet) const override protected virtual
Implements inet::visualizer::PathVisualizerBase.
Reimplemented in inet::visualizer::PacketFlowCanvasVisualizer, inet::visualizer::NetworkRouteCanvasVisualizer, and inet::visualizer::TransportRouteCanvasVisualizer.
 {
     auto figure = new LabeledPolylineFigure("path");
     auto polylineFigure = figure->getPolylineFigure();
     polylineFigure->setSmooth(lineSmooth);
     polylineFigure->setLineWidth(lineWidth);
     polylineFigure->setLineStyle(lineStyle);
     polylineFigure->setEndArrowhead(cFigure::ARROW_BARBED);
     auto lineColor = lineColorSet.getColor(pathVisualizations.size());
     polylineFigure->setLineColor(lineColor);
     auto labelFigure = figure->getLabelFigure();
     labelFigure->setFont(labelFont);
     labelFigure->setColor(opp_isempty(labelColorAsString) ? lineColor : labelColor);
     return new PathCanvasVisualization(label, path, figure);
 }
Referenced by inet::visualizer::NetworkRouteCanvasVisualizer::createPathVisualization(), inet::visualizer::TransportRouteCanvasVisualizer::createPathVisualization(), and inet::visualizer::PacketFlowCanvasVisualizer::createPathVisualization().
initialize()
void inet::visualizer::PathCanvasVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::PathVisualizerBase.
 {
     PathVisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         zIndex = par("zIndex");
         auto canvas = visualizationTargetModule->getCanvas();
         lineManager = LineManager::getCanvasLineManager(canvas);
         canvasProjection = CanvasProjection::getCanvasProjection(canvas);
         pathGroup = new cGroupFigure("paths");
         pathGroup->setZIndex(zIndex);
         canvas->addFigure(pathGroup);
     }
 }
refreshDisplay()
void inet::visualizer::PathCanvasVisualizerBase::refreshDisplay () const override protected virtual
Reimplemented from inet::visualizer::PathVisualizerBase.
 {
     PathVisualizerBase::refreshDisplay();
     auto simulation = getSimulation();
     for (auto it : pathVisualizations) {
         auto pathVisualization = it.second;
         auto pathCanvasVisualization = static_cast<const PathCanvasVisualization *>(pathVisualization);
         auto moduleIds = pathCanvasVisualization->moduleIds;
         std::vector<LineSegment> segments;
         for (size_t index = 1; index < moduleIds.size(); index++) {
             auto fromModuleId = moduleIds[index - 1];
             auto toModuleId = moduleIds[index];
             auto fromModule = simulation->getModule(fromModuleId);
             auto toModule = simulation->getModule(toModuleId);
             auto fromPosition = getContactPosition(fromModule, getPosition(toModule), lineContactMode, lineContactSpacing);
             auto toPosition = getContactPosition(toModule, getPosition(fromModule), lineContactMode, lineContactSpacing);
             auto shift = lineManager->getLineShift(fromModuleId, toModuleId, fromPosition, toPosition, lineShiftMode, pathVisualization->shiftOffsets[index - 1]) * lineShift;
             segments.push_back(LineSegment(fromPosition + shift, toPosition + shift));
         }
         std::vector<cFigure::Point> points;
         for (size_t index = 0; index < segments.size(); index++) {
             if (index == 0)
                 points.push_back(canvasProjection->computeCanvasPoint(segments[index].getPoint1()));
             if (index > 0) {
                 auto& segment1 = segments[index - 1];
                 auto& segment2 = segments[index];
                 Coord intersection = intersectLines(segment1, segment2);
                 if (std::isfinite(intersection.x) && std::isfinite(intersection.y)) {
                     if (isPointOnSegment(segment1, intersection) && isPointOnSegment(segment2, intersection))
                         points.push_back(canvasProjection->computeCanvasPoint(intersection));
                     else {
                         double distance = segment1.getPoint2().distance(segment2.getPoint1());
                         double distance1 = intersection.distance(segment1.getPoint2());
                         double distance2 = intersection.distance(segment2.getPoint1());
                         if (distance1 + distance2 < 4 * distance)
                             points.push_back(canvasProjection->computeCanvasPoint(intersection));
                         else {
                             points.push_back(canvasProjection->computeCanvasPoint(segment1.getPoint2()));
                             points.push_back(canvasProjection->computeCanvasPoint(segment2.getPoint1()));
                         }
                     }
                 }
                 else {
                     points.push_back(canvasProjection->computeCanvasPoint(segment1.getPoint2()));
                     points.push_back(canvasProjection->computeCanvasPoint(segment2.getPoint1()));
                 }
             }
             if (index == segments.size() - 1)
                 points.push_back(canvasProjection->computeCanvasPoint(segments[index].getPoint2()));
         }
         pathCanvasVisualization->figure->setPoints(points);
     }
     visualizationTargetModule->getCanvas()->setAnimationSpeed(pathVisualizations.empty() ? 0 : fadeOutAnimationSpeed, this);
 }
refreshPathVisualization()
void inet::visualizer::PathCanvasVisualizerBase::refreshPathVisualization (const PathVisualization * pathVisualization, cPacket * packet) override protected virtual
Reimplemented from inet::visualizer::PathVisualizerBase.
 {
     PathVisualizerBase::refreshPathVisualization(pathVisualization, packet);
     auto pathCanvasVisualization = static_cast<const PathCanvasVisualization *>(pathVisualization);
     auto text = getPathVisualizationText(pathVisualization, packet);
     pathCanvasVisualization->figure->getLabelFigure()->setText(text.c_str());
 }
removePathVisualization()
void inet::visualizer::PathCanvasVisualizerBase::removePathVisualization (const PathVisualization * pathVisualization) override protected virtual
Reimplemented from inet::visualizer::PathVisualizerBase.
 {
     PathVisualizerBase::removePathVisualization(pathVisualization);
     auto pathCanvasVisualization = static_cast<const PathCanvasVisualization *>(pathVisualization);
     lineManager->removeModulePath(pathVisualization);
     pathGroup->removeFigure(pathCanvasVisualization->figure);
 }
setAlpha()
void inet::visualizer::PathCanvasVisualizerBase::setAlpha (const PathVisualization * pathVisualization, double alpha) const override protected virtual
Implements inet::visualizer::PathVisualizerBase.
 {
     auto pathCanvasVisualization = static_cast<const PathCanvasVisualization *>(path);
     pathCanvasVisualization->figure->getPolylineFigure()->setLineOpacity(alpha);
 }
Member Data Documentation
canvasProjection
const CanvasProjection* inet::visualizer::PathCanvasVisualizerBase::canvasProjection = nullptr protected
Referenced by initialize(), and refreshDisplay().
pathGroup
cGroupFigure* inet::visualizer::PathCanvasVisualizerBase::pathGroup = nullptr protected
Referenced by addPathVisualization(), initialize(), and removePathVisualization().
zIndex
double inet::visualizer::PathCanvasVisualizerBase::zIndex = NaN protected
Referenced by initialize().
The documentation for this class was generated from the following files:
PathCanvasVisualizerBase.h
PathCanvasVisualizerBase.cc