INET Framework for OMNeT++/OMNEST: inet::PolyhedronEdge Class Reference
inet::PolyhedronEdge Class Reference
#include <PolyhedronEdge.h>
Public Member Functions
PolyhedronEdge (PolyhedronPoint *point1, PolyhedronPoint *point2, PolyhedronFace *parentFace)
PolyhedronPoint * getP1 ()
PolyhedronPoint * getP2 ()
const PolyhedronPoint * getP1 () const
const PolyhedronPoint * getP2 () const
void setNextEdge (PolyhedronEdge *next)
void setPrevEdge (PolyhedronEdge *prev)
void setJointEdge (PolyhedronEdge *jointEdge)
PolyhedronEdge * getjointEdge ()
PolyhedronEdge * getNextEdge ()
PolyhedronEdge * getPrevEdge ()
PolyhedronFace * getParentFace ()
void setJointFace (PolyhedronFace *jointFace)
PolyhedronFace * getJointFace ()
PolyhedronPoint getEdgeVector () const
bool operator== (const PolyhedronEdge &rhs) const
Protected Attributes
PolyhedronPoint * point1
PolyhedronPoint * point2
PolyhedronFace * parentFace
PolyhedronFace * jointFace
PolyhedronEdge * jointEdge
PolyhedronEdge * next
PolyhedronEdge * prev
Constructor & Destructor Documentation
PolyhedronEdge()
inet::PolyhedronEdge::PolyhedronEdge (PolyhedronPoint * point1, PolyhedronPoint * point2, PolyhedronFace * parentFace) inline
                                                                                                  :
         point1(point1), point2(point2), parentFace(parentFace), jointFace(nullptr),
         jointEdge(nullptr), next(nullptr), prev(nullptr) {};
Member Function Documentation
getEdgeVector()
PolyhedronPoint inet::PolyhedronEdge::getEdgeVector () const
 {
     return *point2 - *point1;
 }
getjointEdge()
PolyhedronEdge* inet::PolyhedronEdge::getjointEdge () inline
 { return jointEdge; }
getJointFace()
PolyhedronFace* inet::PolyhedronEdge::getJointFace () inline
 { return jointFace; }
Referenced by inet::Polyhedron::mergeFaces().
getNextEdge()
PolyhedronEdge* inet::PolyhedronEdge::getNextEdge () inline
 { return next; }
getP1() [1/2]
PolyhedronPoint* inet::PolyhedronEdge::getP1 () inline
 { return point1; }
Referenced by inet::Polyhedron::computeOutwardNormalVector(), inet::PolyhedronFace::isVisibleFrom(), and inet::Polyhedron::mergeFaces().
getP1() [2/2]
const PolyhedronPoint* inet::PolyhedronEdge::getP1 () const inline
 { return point1; }
getP2() [1/2]
PolyhedronPoint* inet::PolyhedronEdge::getP2 () inline
 { return point2; }
Referenced by inet::Polyhedron::mergeFaces().
getP2() [2/2]
const PolyhedronPoint* inet::PolyhedronEdge::getP2 () const inline
 { return point2; }
getParentFace()
PolyhedronFace* inet::PolyhedronEdge::getParentFace () inline
 { return parentFace; }
getPrevEdge()
PolyhedronEdge* inet::PolyhedronEdge::getPrevEdge () inline
 { return prev; }
operator==()
bool inet::PolyhedronEdge::operator== (const PolyhedronEdge & rhs) const
 {
     return (point1 == rhs.point1 && point2 == rhs.point2) ||
            (point1 == rhs.point2 && point2 == rhs.point1);
 }
setJointEdge()
void inet::PolyhedronEdge::setJointEdge (PolyhedronEdge * jointEdge) inline
 { this->jointEdge = jointEdge; }
setJointFace()
void inet::PolyhedronEdge::setJointFace (PolyhedronFace * jointFace) inline
 { this->jointFace = jointFace; }
Referenced by inet::Polyhedron::connectFaces().
setNextEdge()
void inet::PolyhedronEdge::setNextEdge (PolyhedronEdge * next) inline
 { this->next = next; }
Referenced by inet::PolyhedronFace::PolyhedronFace().
setPrevEdge()
void inet::PolyhedronEdge::setPrevEdge (PolyhedronEdge * prev) inline
 { this->prev = prev; }
Referenced by inet::PolyhedronFace::PolyhedronFace().
Member Data Documentation
jointEdge
PolyhedronEdge* inet::PolyhedronEdge::jointEdge protected
jointFace
PolyhedronFace* inet::PolyhedronEdge::jointFace protected
next
PolyhedronEdge* inet::PolyhedronEdge::next protected
parentFace
PolyhedronFace* inet::PolyhedronEdge::parentFace protected
point1
PolyhedronPoint* inet::PolyhedronEdge::point1 protected
Referenced by getEdgeVector(), and operator==().
point2
PolyhedronPoint* inet::PolyhedronEdge::point2 protected
Referenced by getEdgeVector(), and operator==().
prev
PolyhedronEdge* inet::PolyhedronEdge::prev protected
The documentation for this class was generated from the following files:
PolyhedronEdge.h
PolyhedronEdge.cc