INET Framework for OMNeT++/OMNEST: inet::TlvOptions Class Reference
inet::TlvOptions Class Reference
Class generated from inet/common/TlvOptions.msg:24 by opp_msgtool.
#include <TlvOptions_m.h>
Public Member Functions
TlvOptions ()
TlvOptions (const TlvOptions &other)
virtual ~TlvOptions ()
TlvOptions & operator= (const TlvOptions &other)
virtual TlvOptions * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setTlvOptionArraySize (size_t size)
virtual size_t getTlvOptionArraySize () const
virtual const TlvOptionBase * getTlvOption (size_t k) const
virtual TlvOptionBase * getTlvOptionForUpdate (size_t k)
virtual void setTlvOption (size_t k, TlvOptionBase *tlvOption)
virtual TlvOptionBase * removeTlvOption (size_t k)
TlvOptionBase * dropTlvOption (size_t k)
virtual void insertTlvOption (size_t k, TlvOptionBase *tlvOption)
void insertTlvOption (TlvOptionBase *tlvOption)
virtual void appendTlvOption (TlvOptionBase *tlvOption)
virtual void eraseTlvOption (size_t k)
TlvOptionBase * dropTlvOption (TlvOptionBase *option)
void deleteOptionByType (int type, bool firstOnly=true)
virtual int getLength () const
int findByType (short int type, int firstPos=0) const
Protected Member Functions
bool operator== (const TlvOptions &)=delete
Protected Attributes
TlvOptionBase ** tlvOption = nullptr
size_t tlvOption_arraysize = 0
Private Member Functions
void copy (const TlvOptions &other)
Detailed Description
Class generated from inet/common/TlvOptions.msg:24 by opp_msgtool.
class TlvOptions extends cObject
{
    @packetData;
    TlvOptionBase *tlvOption[] @owned;
}
Constructor & Destructor Documentation
TlvOptions() [1/2]
inet::TlvOptions::TlvOptions ()
TlvOptions() [2/2]
inet::TlvOptions::TlvOptions (const TlvOptions & other)
~TlvOptions()
virtual inet::TlvOptions::~TlvOptions () virtual
Member Function Documentation
appendTlvOption()
virtual void inet::TlvOptions::appendTlvOption (TlvOptionBase * tlvOption) virtual
Referenced by inet::Ipv4Header::addOption(), and inet::Gpsr::setGpsrOptionOnNetworkDatagram().
copy()
void inet::TlvOptions::copy (const TlvOptions & other) private
deleteOptionByType()
void inet::TlvOptions::deleteOptionByType (int type, bool firstOnly = true)
 {
     for (size_t i = 0; i < tlvOption_arraysize;) {
         if (tlvOption[i] && tlvOption[i]->getType() == type) {
             removeTlvOption(i);
             eraseTlvOption(i);
             if (firstOnly)
                 break;
         }
         else
             ++i;
     }
 }
dropTlvOption() [1/2]
TlvOptionBase* inet::TlvOptions::dropTlvOption (size_t k) inline
 {return removeTlvOption(k);}
dropTlvOption() [2/2]
TlvOptionBase * inet::TlvOptions::dropTlvOption (TlvOptionBase * option)
 {
     for (size_t i = 0; i < tlvOption_arraysize; i++) {
         if (tlvOption[i] == option) {
             removeTlvOption(i);
             eraseTlvOption(i);
             return option;
         }
     }
     return nullptr;
 }
dup()
virtual TlvOptions* inet::TlvOptions::dup () const inline override virtual
 {return new TlvOptions(*this);}
eraseTlvOption()
virtual void inet::TlvOptions::eraseTlvOption (size_t k) virtual
Referenced by deleteOptionByType(), and dropTlvOption().
findByType()
int inet::TlvOptions::findByType (short int type, int firstPos = 0) const
 {
     for (size_t i = firstPos; i < tlvOption_arraysize; i++)
         if (tlvOption[i] && tlvOption[i]->getType() == type)
             return i;
     return -1;
 }
Referenced by inet::Gpsr::findGpsrOptionInNetworkDatagram(), inet::Gpsr::findGpsrOptionInNetworkDatagramForUpdate(), inet::Ipv4Header::findMutableOptionByType(), and inet::Ipv4Header::findOptionByType().
getLength()
int inet::TlvOptions::getLength () const virtual
 {
     int length = 0;
     for (size_t i = 0; i < tlvOption_arraysize; i++) {
         if (tlvOption[i])
             length += tlvOption[i]->getLength();
     }
     return length;
 }
Referenced by inet::Ipv4Header::calculateHeaderByteLength(), and inet::Gpsr::setGpsrOptionOnNetworkDatagram().
getTlvOption()
virtual const TlvOptionBase* inet::TlvOptions::getTlvOption (size_t k) const virtual
Referenced by inet::Gpsr::findGpsrOptionInNetworkDatagram(), and inet::Ipv4Header::getOption().
getTlvOptionArraySize()
virtual size_t inet::TlvOptions::getTlvOptionArraySize () const virtual
Referenced by inet::Ipv4Header::getOptionArraySize().
getTlvOptionForUpdate()
virtual TlvOptionBase* inet::TlvOptions::getTlvOptionForUpdate (size_t k) inline virtual
 { return const_cast<TlvOptionBase *>(const_cast<TlvOptions*>(this)->getTlvOption(k));}
Referenced by inet::Gpsr::findGpsrOptionInNetworkDatagramForUpdate(), and inet::Ipv4Header::getOptionForUpdate().
insertTlvOption() [1/2]
virtual void inet::TlvOptions::insertTlvOption (size_t k, TlvOptionBase * tlvOption) virtual
Referenced by inet::Ipv4Header::addOption().
insertTlvOption() [2/2]
void inet::TlvOptions::insertTlvOption (TlvOptionBase * tlvOption) inline
 {appendTlvOption(tlvOption);}
operator=()
TlvOptions& inet::TlvOptions::operator= (const TlvOptions & other)
operator==()
bool inet::TlvOptions::operator== (const TlvOptions &) protected delete
parsimPack()
virtual void inet::TlvOptions::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TlvOptions::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
removeTlvOption()
virtual TlvOptionBase* inet::TlvOptions::removeTlvOption (size_t k) virtual
Referenced by deleteOptionByType(), and dropTlvOption().
setTlvOption()
virtual void inet::TlvOptions::setTlvOption (size_t k, TlvOptionBase * tlvOption) virtual
setTlvOptionArraySize()
virtual void inet::TlvOptions::setTlvOptionArraySize (size_t size) virtual
Member Data Documentation
tlvOption
TlvOptionBase* * inet::TlvOptions::tlvOption = nullptr protected
Referenced by deleteOptionByType(), dropTlvOption(), findByType(), and getLength().
tlvOption_arraysize
size_t inet::TlvOptions::tlvOption_arraysize = 0 protected
Referenced by deleteOptionByType(), dropTlvOption(), findByType(), and getLength().
The documentation for this class was generated from the following files:
TlvOptions_m.h
TlvOptions.cc