INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3AsExternalLsa Class Reference
inet::ospfv3::Ospfv3AsExternalLsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:244 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3AsExternalLsa ()
Ospfv3AsExternalLsa (const Ospfv3AsExternalLsa &other)
virtual ~Ospfv3AsExternalLsa ()
Ospfv3AsExternalLsa & operator= (const Ospfv3AsExternalLsa &other)
virtual Ospfv3AsExternalLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getEBit () const
virtual void setEBit (bool eBit)
virtual bool getFBit () const
virtual void setFBit (bool fBit)
virtual bool getTBit () const
virtual void setTBit (bool tBit)
virtual uint32_t getMetric () const
virtual void setMetric (uint32_t metric)
virtual uint16_t getReferencedLSType () const
virtual void setReferencedLSType (uint16_t referencedLSType)
virtual const ::inet::Ipv6Address & getForwardingAddress () const
virtual ::inet::Ipv6Address & getForwardingAddressForUpdate ()
virtual void setForwardingAddress (const ::inet::Ipv6Address &forwardingAddress)
virtual uint32_t getExternalRouteTag () const
virtual void setExternalRouteTag (uint32_t externalRouteTag)
virtual uint32_t getReferencedLSID () const
virtual void setReferencedLSID (uint32_t referencedLSID)
Public Member Functions inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3AsExternalLsa &)=delete
Protected Member Functions inherited from inet::ospfv3::Ospfv3Lsa
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
bool eBit = false
bool fBit = false
bool tBit = false
uint32_t metric = 0
uint16_t referencedLSType = 0
::inet::Ipv6Address forwardingAddress
uint32_t externalRouteTag = 0
uint32_t referencedLSID = 0
Protected Attributes inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3AsExternalLsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:244 by opp_msgtool.
//   AS-External-LSAs
class Ospfv3AsExternalLsa extends Ospfv3Lsa
{
    bool eBit;
    bool fBit;
    bool tBit;
    uint32_t metric;
    uint16_t referencedLSType;
    Ipv6Address forwardingAddress;
    uint32_t externalRouteTag;
    uint32_t referencedLSID;
}
Constructor & Destructor Documentation
Ospfv3AsExternalLsa() [1/2]
inet::ospfv3::Ospfv3AsExternalLsa::Ospfv3AsExternalLsa ()
Ospfv3AsExternalLsa() [2/2]
inet::ospfv3::Ospfv3AsExternalLsa::Ospfv3AsExternalLsa (const Ospfv3AsExternalLsa & other)
~Ospfv3AsExternalLsa()
virtual inet::ospfv3::Ospfv3AsExternalLsa::~Ospfv3AsExternalLsa () virtual
Member Function Documentation
copy()
void inet::ospfv3::Ospfv3AsExternalLsa::copy (const Ospfv3AsExternalLsa & other) private
dup()
virtual Ospfv3AsExternalLsa* inet::ospfv3::Ospfv3AsExternalLsa::dup () const inline override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
 {return new Ospfv3AsExternalLsa(*this);}
getEBit()
virtual bool inet::ospfv3::Ospfv3AsExternalLsa::getEBit () const virtual
Referenced by inet::ospfv3::operator<<().
getExternalRouteTag()
virtual uint32_t inet::ospfv3::Ospfv3AsExternalLsa::getExternalRouteTag () const virtual
Referenced by inet::ospfv3::operator<<().
getFBit()
virtual bool inet::ospfv3::Ospfv3AsExternalLsa::getFBit () const virtual
Referenced by inet::ospfv3::operator<<().
getForwardingAddress()
virtual const ::inet::Ipv6Address& inet::ospfv3::Ospfv3AsExternalLsa::getForwardingAddress () const virtual
Referenced by inet::ospfv3::operator<<().
getForwardingAddressForUpdate()
virtual ::inet::Ipv6Address& inet::ospfv3::Ospfv3AsExternalLsa::getForwardingAddressForUpdate () inline
 { return const_cast<::inet::Ipv6Address&>(const_cast<Ospfv3AsExternalLsa*>(this)->getForwardingAddress());}
getMetric()
virtual uint32_t inet::ospfv3::Ospfv3AsExternalLsa::getMetric () const virtual
Referenced by inet::ospfv3::operator<<().
getReferencedLSID()
virtual uint32_t inet::ospfv3::Ospfv3AsExternalLsa::getReferencedLSID () const virtual
Referenced by inet::ospfv3::operator<<().
getReferencedLSType()
virtual uint16_t inet::ospfv3::Ospfv3AsExternalLsa::getReferencedLSType () const virtual
Referenced by inet::ospfv3::operator<<().
getTBit()
virtual bool inet::ospfv3::Ospfv3AsExternalLsa::getTBit () const virtual
Referenced by inet::ospfv3::operator<<().
operator=()
Ospfv3AsExternalLsa& inet::ospfv3::Ospfv3AsExternalLsa::operator= (const Ospfv3AsExternalLsa & other)
operator==()
bool inet::ospfv3::Ospfv3AsExternalLsa::operator== (const Ospfv3AsExternalLsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setEBit()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setEBit (bool eBit) virtual
setExternalRouteTag()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setExternalRouteTag (uint32_t externalRouteTag) virtual
setFBit()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setFBit (bool fBit) virtual
setForwardingAddress()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setForwardingAddress (const ::inet::Ipv6Address & forwardingAddress) virtual
setMetric()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setMetric (uint32_t metric) virtual
setReferencedLSID()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setReferencedLSID (uint32_t referencedLSID) virtual
setReferencedLSType()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setReferencedLSType (uint16_t referencedLSType) virtual
setTBit()
virtual void inet::ospfv3::Ospfv3AsExternalLsa::setTBit (bool tBit) virtual
Member Data Documentation
eBit
bool inet::ospfv3::Ospfv3AsExternalLsa::eBit = false protected
externalRouteTag
uint32_t inet::ospfv3::Ospfv3AsExternalLsa::externalRouteTag = 0 protected
fBit
bool inet::ospfv3::Ospfv3AsExternalLsa::fBit = false protected
forwardingAddress
::inet::Ipv6Address inet::ospfv3::Ospfv3AsExternalLsa::forwardingAddress protected
metric
uint32_t inet::ospfv3::Ospfv3AsExternalLsa::metric = 0 protected
referencedLSID
uint32_t inet::ospfv3::Ospfv3AsExternalLsa::referencedLSID = 0 protected
referencedLSType
uint16_t inet::ospfv3::Ospfv3AsExternalLsa::referencedLSType = 0 protected
tBit
bool inet::ospfv3::Ospfv3AsExternalLsa::tBit = false protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h