INET Framework for OMNeT++/OMNEST: inet::bgp::BgpUpdatePathAttributesLocalPref Class Reference
inet::bgp::BgpUpdatePathAttributesLocalPref Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:167 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpUpdatePathAttributesLocalPref ()
BgpUpdatePathAttributesLocalPref (const BgpUpdatePathAttributesLocalPref &other)
virtual ~BgpUpdatePathAttributesLocalPref ()
BgpUpdatePathAttributesLocalPref & operator= (const BgpUpdatePathAttributesLocalPref &other)
virtual BgpUpdatePathAttributesLocalPref * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getValue () const
virtual void setValue (uint32_t value)
Public Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
BgpUpdatePathAttributes ()
BgpUpdatePathAttributes (const BgpUpdatePathAttributes &other)
virtual ~BgpUpdatePathAttributes ()
BgpUpdatePathAttributes & operator= (const BgpUpdatePathAttributes &other)
virtual bool getOptionalBit () const
virtual void setOptionalBit (bool optionalBit)
virtual bool getTransitiveBit () const
virtual void setTransitiveBit (bool transitiveBit)
virtual bool getPartialBit () const
virtual void setPartialBit (bool partialBit)
virtual bool getExtendedLengthBit () const
virtual void setExtendedLengthBit (bool extendedLengthBit)
virtual unsigned short getReserved () const
virtual void setReserved (unsigned short reserved)
virtual BgpUpdateAttributeTypeCode getTypeCode () const
virtual void setTypeCode (BgpUpdateAttributeTypeCode typeCode)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const BgpUpdatePathAttributesLocalPref &)=delete
Protected Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
bool operator== (const BgpUpdatePathAttributes &)=delete
Protected Attributes
uint32_t value = 0
Protected Attributes inherited from inet::bgp::BgpUpdatePathAttributes
bool optionalBit = false
bool transitiveBit = false
bool partialBit = false
bool extendedLengthBit = false
unsigned short reserved = 0
BgpUpdateAttributeTypeCode typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1)
unsigned short length = 0
Private Member Functions
void copy (const BgpUpdatePathAttributesLocalPref &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:167 by opp_msgtool.
//LOCAL_PREF (RFC4271 Section 4.3, Type code 5):
class BgpUpdatePathAttributesLocalPref extends BgpUpdatePathAttributes
{
    typeCode = LOCAL_PREF;
    optionalBit = false;
    transitiveBit = true;
    length = 4;
    uint32_t value;
}
Constructor & Destructor Documentation
BgpUpdatePathAttributesLocalPref() [1/2]
inet::bgp::BgpUpdatePathAttributesLocalPref::BgpUpdatePathAttributesLocalPref ()
BgpUpdatePathAttributesLocalPref() [2/2]
inet::bgp::BgpUpdatePathAttributesLocalPref::BgpUpdatePathAttributesLocalPref (const BgpUpdatePathAttributesLocalPref & other)
~BgpUpdatePathAttributesLocalPref()
virtual inet::bgp::BgpUpdatePathAttributesLocalPref::~BgpUpdatePathAttributesLocalPref () virtual
Member Function Documentation
copy()
void inet::bgp::BgpUpdatePathAttributesLocalPref::copy (const BgpUpdatePathAttributesLocalPref & other) private
dup()
virtual BgpUpdatePathAttributesLocalPref* inet::bgp::BgpUpdatePathAttributesLocalPref::dup () const inline override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
 {return new BgpUpdatePathAttributesLocalPref(*this);}
getValue()
virtual uint32_t inet::bgp::BgpUpdatePathAttributesLocalPref::getValue () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
operator=()
BgpUpdatePathAttributesLocalPref& inet::bgp::BgpUpdatePathAttributesLocalPref::operator= (const BgpUpdatePathAttributesLocalPref & other)
operator==()
bool inet::bgp::BgpUpdatePathAttributesLocalPref::operator== (const BgpUpdatePathAttributesLocalPref &) protected delete
parsimPack()
virtual void inet::bgp::BgpUpdatePathAttributesLocalPref::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpUpdatePathAttributesLocalPref::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimUnpacking().
setValue()
virtual void inet::bgp::BgpUpdatePathAttributesLocalPref::setValue (uint32_t value) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
value
uint32_t inet::bgp::BgpUpdatePathAttributesLocalPref::value = 0 protected
The documentation for this class was generated from the following file:
BgpHeader_m.h