INET Framework for OMNeT++/OMNEST: inet::ieee80211::IQosRateSelection Class Reference
inet::ieee80211::IQosRateSelection Class Reference abstract
Abstract interface for rate selection.
#include <IQosRateSelection.h>
Public Member Functions
virtual ~IQosRateSelection ()
virtual const physicallayer::IIeee80211Mode * computeResponseCtsFrameMode (Packet *packet, const Ptr< const Ieee80211RtsFrame > &rtsFrame)=0
virtual const physicallayer::IIeee80211Mode * computeResponseAckFrameMode (Packet *packet, const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader)=0
virtual const physicallayer::IIeee80211Mode * computeResponseBlockAckFrameMode (Packet *packet, const Ptr< const Ieee80211BlockAckReq > &blockAckReq)=0
virtual const physicallayer::IIeee80211Mode * computeMode (Packet *packet, const Ptr< const Ieee80211MacHeader > &header, TxopProcedure *txopProcedure)=0
Detailed Description
Abstract interface for rate selection.
Rate selection decides what bit rate (or MCS) should be used for any particular frame. The rules of rate selection is described in the 802.11 specification in the section titled "Multirate Support".
Constructor & Destructor Documentation
~IQosRateSelection()
virtual inet::ieee80211::IQosRateSelection::~IQosRateSelection () inline virtual
 {}
Member Function Documentation
computeMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IQosRateSelection::computeMode (Packet * packet, const Ptr< const Ieee80211MacHeader > & header, TxopProcedure * txopProcedure) pure virtual
Implemented in inet::ieee80211::QosRateSelection.
Referenced by inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), and inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField().
computeResponseAckFrameMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IQosRateSelection::computeResponseAckFrameMode (Packet * packet, const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) pure virtual
Implemented in inet::ieee80211::QosRateSelection.
Referenced by inet::ieee80211::RecipientQosAckPolicy::computeAckDuration(), inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField(), and inet::ieee80211::OriginatorQosAckPolicy::getAckTimeout().
computeResponseBlockAckFrameMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IQosRateSelection::computeResponseBlockAckFrameMode (Packet * packet, const Ptr< const Ieee80211BlockAckReq > & blockAckReq) pure virtual
Implemented in inet::ieee80211::QosRateSelection.
Referenced by inet::ieee80211::RecipientQosAckPolicy::computeBasicBlockAckDuration(), inet::ieee80211::SingleProtectionMechanism::computeBlockAckReqDurationField(), and inet::ieee80211::OriginatorQosAckPolicy::getBlockAckTimeout().
computeResponseCtsFrameMode()
virtual const physicallayer::IIeee80211Mode* inet::ieee80211::IQosRateSelection::computeResponseCtsFrameMode (Packet * packet, const Ptr< const Ieee80211RtsFrame > & rtsFrame) pure virtual
Implemented in inet::ieee80211::QosRateSelection.
Referenced by inet::ieee80211::QosCtsPolicy::computeCtsDuration(), inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField(), and inet::ieee80211::QosRtsPolicy::getCtsTimeout().
The documentation for this class was generated from the following file:
IQosRateSelection.h