INET Framework for OMNeT++/OMNEST: inet::EthernetSocket Class Reference
inet::EthernetSocket Class Reference
#include <EthernetSocket.h>
Classes
class ICallback
Public Member Functions
Opening and closing connections, sending data
void setCallback (ICallback *callback)
Sets a callback object, to be used with processMessage().
void setNetworkInterface (NetworkInterface *networkInterface)
void bind (const MacAddress &localAddress, const MacAddress &remoteAddress, const Protocol *protocol, bool steal)
Binds the socket to the MAC address.
Handling of messages arriving from Ethernet
virtual void processMessage (cMessage *msg) override
Examines the message, takes ownership, and updates socket state.
Public Member Functions inherited from inet::SocketBase
SocketBase ()
virtual ~SocketBase ()
void setOutputGate (cGate *gate)
Sets the gate on which to send messages.
int getSocketId () const override
Returns the internal socket Id.
virtual void send (Packet *packet) override
Sends a data packet to the address and port specified previously in a connect() call.
virtual bool isOpen () const override
Returns true if the socket is open.
virtual void close () override
Unbinds the socket.
virtual void destroy () override
Notify the protocol that the owner of ISocket has destroyed the socket.
virtual bool belongsToSocket (cMessage *msg) const override
Returns true if the message belongs to this socket instance.
void * getUserData () const
void setUserData (void *userData)
Public Member Functions inherited from inet::ISocket
virtual ~ISocket ()
Protected Member Functions
virtual void sendOut (cMessage *msg) override
Protected Attributes
ICallback * callback = nullptr
NetworkInterface * networkInterface = nullptr
Protected Attributes inherited from inet::SocketBase
cGate * outputGate = nullptr
int socketId = -1
bool isOpen_ = false
void * userData = nullptr
Member Function Documentation
bind()
void inet::EthernetSocket::bind (const MacAddress & localAddress, const MacAddress & remoteAddress, const Protocol * protocol, bool steal)
Binds the socket to the MAC address.
 {
     auto request = new Request("BIND", SOCKET_C_BIND);
     EthernetBindCommand *ctrl = new EthernetBindCommand();
     ctrl->setLocalAddress(localAddress);
     ctrl->setRemoteAddress(remoteAddress);
     ctrl->setProtocol(protocol);
     ctrl->setSteal(steal);
     request->setControlInfo(ctrl);
     isOpen_ = true;
     sendOut(request);
 }
processMessage()
void inet::EthernetSocket::processMessage (cMessage * msg) override virtual
Examines the message, takes ownership, and updates socket state.
Implements inet::ISocket.
 {
     ASSERT(belongsToSocket(msg));
     switch (msg->getKind()) {
         case SOCKET_I_DATA:
             if (callback)
                 callback->socketDataArrived(this, check_and_cast<Packet *>(msg));
             else
                 delete msg;
             break;
         case SOCKET_I_CLOSED:
             isOpen_ = false;
             if (callback)
                 callback->socketClosed(this);
             delete msg;
             break;
         default:
             throw cRuntimeError("EthernetSocket: invalid msg kind %d, one of the ETHERNNET_I_xxx constants expected", msg->getKind());
             break;
     }
 }
Referenced by inet::EthernetSocketIo::handleMessageWhenUp().
sendOut()
void inet::EthernetSocket::sendOut (cMessage * msg) override protected virtual
Reimplemented from inet::SocketBase.
 {
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     if (networkInterface != nullptr)
         tags.addTagIfAbsent<InterfaceReq>()->setInterfaceId(networkInterface->getInterfaceId());
     tags.addTag<DispatchProtocolReq>()->setProtocol(&Protocol::ethernetMac);
     SocketBase::sendOut(msg);
 }
Referenced by bind().
setCallback()
void inet::EthernetSocket::setCallback (ICallback * callback) inline
Sets a callback object, to be used with processMessage().
This callback object may be your simple module itself (if it multiply inherits from ICallback too, that is you declared it as
class MyAppModule : public cSimpleModule, public EthernetSocket::ICallback
and redefined the necessary virtual functions; or you may use dedicated class (and objects) for this purpose.
EthernetSocket doesn't delete the callback object in the destructor or on any other occasion.
 { this->callback = callback; }
Referenced by inet::EthernetSocketIo::setSocketOptions().
setNetworkInterface()
void inet::EthernetSocket::setNetworkInterface (NetworkInterface * networkInterface) inline
 { this->networkInterface = networkInterface; }
Referenced by inet::EthernetSocketIo::setSocketOptions().
Member Data Documentation
callback
ICallback* inet::EthernetSocket::callback = nullptr protected
Referenced by processMessage().
networkInterface
NetworkInterface* inet::EthernetSocket::networkInterface = nullptr protected
Referenced by sendOut().
The documentation for this class was generated from the following files:
EthernetSocket.h
EthernetSocket.cc