INET Framework for OMNeT++/OMNEST: inet::GptpReqAnswerEvent Class Reference
inet::GptpReqAnswerEvent Class Reference
Class generated from inet/linklayer/ieee8021as/GptpPacket.msg:119 by opp_msgtool.
#include <GptpPacket_m.h>
Public Member Functions
GptpReqAnswerEvent (const char *name=nullptr, short kind=0)
GptpReqAnswerEvent (const GptpReqAnswerEvent &other)
virtual ~GptpReqAnswerEvent ()
GptpReqAnswerEvent & operator= (const GptpReqAnswerEvent &other)
virtual GptpReqAnswerEvent * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getPortId () const
virtual void setPortId (int portId)
virtual clocktime_t getIngressTimestamp () const
virtual void setIngressTimestamp (clocktime_t ingressTimestamp)
virtual const PortIdentity & getSourcePortIdentity () const
virtual PortIdentity & getSourcePortIdentityForUpdate ()
virtual void setSourcePortIdentity (const PortIdentity &sourcePortIdentity)
virtual uint16_t getSequenceId () const
virtual void setSequenceId (uint16_t sequenceId)
Public Member Functions inherited from inet::ClockEvent
ClockEvent (const char *name=nullptr, short kind=0)
ClockEvent (const ClockEvent &other)
ClockEvent & operator= (const ClockEvent &other)
Public Member Functions inherited from inet::ClockEvent_Base
virtual ~ClockEvent_Base ()
virtual const IClock * getClock () const
virtual IClock * getClockForUpdate ()
virtual void setClock (IClock *clock)
virtual bool getRelative () const
virtual void setRelative (bool relative)
virtual clocktime_t getArrivalClockTime () const
virtual void setArrivalClockTime (clocktime_t arrivalClockTime)
virtual OverdueClockEventHandlingMode getOverdueClockEventHandlingMode () const
virtual void setOverdueClockEventHandlingMode (OverdueClockEventHandlingMode overdueClockEventHandlingMode)
Protected Member Functions
bool operator== (const GptpReqAnswerEvent &)=delete
Protected Member Functions inherited from inet::ClockEvent
virtual void execute () override
void callBaseExecute ()
Protected Member Functions inherited from inet::ClockEvent_Base
bool operator== (const ClockEvent_Base &)=delete
ClockEvent_Base (const char *name=nullptr, short kind=0)
ClockEvent_Base (const ClockEvent_Base &other)
ClockEvent_Base & operator= (const ClockEvent_Base &other)
Protected Attributes
int portId = 0
clocktime_t ingressTimestamp = CLOCKTIME_ZERO
PortIdentity sourcePortIdentity
uint16_t sequenceId = 0
Protected Attributes inherited from inet::ClockEvent_Base
IClock * clock = nullptr
bool relative = false
clocktime_t arrivalClockTime = -1
OverdueClockEventHandlingMode overdueClockEventHandlingMode = UNSPECIFIED
Private Member Functions
void copy (const GptpReqAnswerEvent &other)
Detailed Description
Class generated from inet/linklayer/ieee8021as/GptpPacket.msg:119 by opp_msgtool.
message GptpReqAnswerEvent extends ClockEvent
{
    int portId;
    clocktime_t ingressTimestamp;
    PortIdentity sourcePortIdentity;
    uint16_t sequenceId;
}
Constructor & Destructor Documentation
GptpReqAnswerEvent() [1/2]
inet::GptpReqAnswerEvent::GptpReqAnswerEvent (const char * name = nullptr, short kind = 0)
GptpReqAnswerEvent() [2/2]
inet::GptpReqAnswerEvent::GptpReqAnswerEvent (const GptpReqAnswerEvent & other)
~GptpReqAnswerEvent()
virtual inet::GptpReqAnswerEvent::~GptpReqAnswerEvent () virtual
Member Function Documentation
copy()
void inet::GptpReqAnswerEvent::copy (const GptpReqAnswerEvent & other) private
dup()
virtual GptpReqAnswerEvent* inet::GptpReqAnswerEvent::dup () const inline override virtual
Reimplemented from inet::ClockEvent.
 {return new GptpReqAnswerEvent(*this);}
getIngressTimestamp()
virtual clocktime_t inet::GptpReqAnswerEvent::getIngressTimestamp () const virtual
Referenced by inet::Gptp::sendPdelayResp().
getPortId()
virtual int inet::GptpReqAnswerEvent::getPortId () const virtual
Referenced by inet::Gptp::sendPdelayResp().
getSequenceId()
virtual uint16_t inet::GptpReqAnswerEvent::getSequenceId () const virtual
Referenced by inet::Gptp::sendPdelayResp().
getSourcePortIdentity()
virtual const PortIdentity& inet::GptpReqAnswerEvent::getSourcePortIdentity () const virtual
Referenced by inet::Gptp::sendPdelayResp().
getSourcePortIdentityForUpdate()
virtual PortIdentity& inet::GptpReqAnswerEvent::getSourcePortIdentityForUpdate () inline virtual
 { return const_cast<PortIdentity&>(const_cast<GptpReqAnswerEvent*>(this)->getSourcePortIdentity());}
operator=()
GptpReqAnswerEvent& inet::GptpReqAnswerEvent::operator= (const GptpReqAnswerEvent & other)
operator==()
bool inet::GptpReqAnswerEvent::operator== (const GptpReqAnswerEvent &) protected delete
parsimPack()
virtual void inet::GptpReqAnswerEvent::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ClockEvent_Base.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::GptpReqAnswerEvent::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ClockEvent_Base.
Referenced by inet::doParsimUnpacking().
setIngressTimestamp()
virtual void inet::GptpReqAnswerEvent::setIngressTimestamp (clocktime_t ingressTimestamp) virtual
setPortId()
virtual void inet::GptpReqAnswerEvent::setPortId (int portId) virtual
setSequenceId()
virtual void inet::GptpReqAnswerEvent::setSequenceId (uint16_t sequenceId) virtual
setSourcePortIdentity()
virtual void inet::GptpReqAnswerEvent::setSourcePortIdentity (const PortIdentity & sourcePortIdentity) virtual
Member Data Documentation
ingressTimestamp
clocktime_t inet::GptpReqAnswerEvent::ingressTimestamp = CLOCKTIME_ZERO protected
portId
int inet::GptpReqAnswerEvent::portId = 0 protected
sequenceId
uint16_t inet::GptpReqAnswerEvent::sequenceId = 0 protected
sourcePortIdentity
PortIdentity inet::GptpReqAnswerEvent::sourcePortIdentity protected
The documentation for this class was generated from the following file:
GptpPacket_m.h