INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3LinkLsa Class Reference
inet::ospfv3::Ospfv3LinkLsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:281 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3LinkLsa ()
Ospfv3LinkLsa (const Ospfv3LinkLsa &other)
virtual ~Ospfv3LinkLsa ()
Ospfv3LinkLsa & operator= (const Ospfv3LinkLsa &other)
virtual Ospfv3LinkLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint8_t getRouterPriority () const
virtual void setRouterPriority (uint8_t routerPriority)
virtual const Ospfv3Options & getOspfOptions () const
virtual Ospfv3Options & getOspfOptionsForUpdate ()
virtual void setOspfOptions (const Ospfv3Options &ospfOptions)
virtual const ::inet::L3Address & getLinkLocalInterfaceAdd () const
virtual ::inet::L3Address & getLinkLocalInterfaceAddForUpdate ()
virtual void setLinkLocalInterfaceAdd (const ::inet::L3Address &linkLocalInterfaceAdd)
virtual uint32_t getNumPrefixes () const
virtual void setNumPrefixes (uint32_t numPrefixes)
virtual void setPrefixesArraySize (size_t size)
virtual size_t getPrefixesArraySize () const
virtual const Ospfv3LsaPrefix0 & getPrefixes (size_t k) const
virtual Ospfv3LsaPrefix0 & getPrefixesForUpdate (size_t k)
virtual void setPrefixes (size_t k, const Ospfv3LsaPrefix0 &prefixes)
virtual void insertPrefixes (size_t k, const Ospfv3LsaPrefix0 &prefixes)
void insertPrefixes (const Ospfv3LsaPrefix0 &prefixes)
virtual void appendPrefixes (const Ospfv3LsaPrefix0 &prefixes)
virtual void erasePrefixes (size_t k)
Public Member Functions inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3LinkLsa &)=delete
Protected Member Functions inherited from inet::ospfv3::Ospfv3Lsa
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
uint8_t routerPriority = 0
Ospfv3Options ospfOptions
::inet::L3Address linkLocalInterfaceAdd
uint32_t numPrefixes = 0
Ospfv3LsaPrefix0 * prefixes = nullptr
size_t prefixes_arraysize = 0
Protected Attributes inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3LinkLsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:281 by opp_msgtool.
// Link-LSAs
// A link-local only LSA for OSPFv3. A Type 8 LSA is used to give
// information about link-local addresses and a list of IPv6 addresses on the link.
class Ospfv3LinkLsa extends Ospfv3Lsa
{
    uint8_t routerPriority;
    Ospfv3Options ospfOptions;
    L3Address linkLocalInterfaceAdd;
    uint32_t numPrefixes;
    Ospfv3LsaPrefix0 prefixes[];
}
Constructor & Destructor Documentation
Ospfv3LinkLsa() [1/2]
inet::ospfv3::Ospfv3LinkLsa::Ospfv3LinkLsa ()
Ospfv3LinkLsa() [2/2]
inet::ospfv3::Ospfv3LinkLsa::Ospfv3LinkLsa (const Ospfv3LinkLsa & other)
~Ospfv3LinkLsa()
virtual inet::ospfv3::Ospfv3LinkLsa::~Ospfv3LinkLsa () virtual
Member Function Documentation
appendPrefixes()
virtual void inet::ospfv3::Ospfv3LinkLsa::appendPrefixes (const Ospfv3LsaPrefix0 & prefixes) virtual
copy()
void inet::ospfv3::Ospfv3LinkLsa::copy (const Ospfv3LinkLsa & other) private
dup()
virtual Ospfv3LinkLsa* inet::ospfv3::Ospfv3LinkLsa::dup () const inline override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
 {return new Ospfv3LinkLsa(*this);}
erasePrefixes()
virtual void inet::ospfv3::Ospfv3LinkLsa::erasePrefixes (size_t k) virtual
getLinkLocalInterfaceAdd()
virtual const ::inet::L3Address& inet::ospfv3::Ospfv3LinkLsa::getLinkLocalInterfaceAdd () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateNextHops(), and inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom().
getLinkLocalInterfaceAddForUpdate()
virtual ::inet::L3Address& inet::ospfv3::Ospfv3LinkLsa::getLinkLocalInterfaceAddForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<Ospfv3LinkLsa*>(this)->getLinkLocalInterfaceAdd());}
getNumPrefixes()
virtual uint32_t inet::ospfv3::Ospfv3LinkLsa::getNumPrefixes () const virtual
Referenced by inet::ospfv3::calculateLSASize(), and inet::ospfv3::Ospfv3Interface::originateLinkLSA().
getOspfOptions()
virtual const Ospfv3Options& inet::ospfv3::Ospfv3LinkLsa::getOspfOptions () const virtual
Referenced by inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom().
getOspfOptionsForUpdate()
virtual Ospfv3Options& inet::ospfv3::Ospfv3LinkLsa::getOspfOptionsForUpdate () inline virtual
 { return const_cast<Ospfv3Options&>(const_cast<Ospfv3LinkLsa*>(this)->getOspfOptions());}
getPrefixes()
virtual const Ospfv3LsaPrefix0& inet::ospfv3::Ospfv3LinkLsa::getPrefixes (size_t k) const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::calculateLSASize(), and inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom().
getPrefixesArraySize()
virtual size_t inet::ospfv3::Ospfv3LinkLsa::getPrefixesArraySize () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom(), and inet::ospfv3::Ospfv3Interface::originateLinkLSA().
getPrefixesForUpdate()
virtual Ospfv3LsaPrefix0& inet::ospfv3::Ospfv3LinkLsa::getPrefixesForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv3LsaPrefix0&>(const_cast<Ospfv3LinkLsa*>(this)->getPrefixes(k));}
getRouterPriority()
virtual uint8_t inet::ospfv3::Ospfv3LinkLsa::getRouterPriority () const virtual
Referenced by inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom().
insertPrefixes() [1/2]
void inet::ospfv3::Ospfv3LinkLsa::insertPrefixes (const Ospfv3LsaPrefix0 & prefixes) inline
 {appendPrefixes(prefixes);}
insertPrefixes() [2/2]
virtual void inet::ospfv3::Ospfv3LinkLsa::insertPrefixes (size_t k, const Ospfv3LsaPrefix0 & prefixes) virtual
operator=()
Ospfv3LinkLsa& inet::ospfv3::Ospfv3LinkLsa::operator= (const Ospfv3LinkLsa & other)
operator==()
bool inet::ospfv3::Ospfv3LinkLsa::operator== (const Ospfv3LinkLsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3LinkLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3LinkLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setLinkLocalInterfaceAdd()
virtual void inet::ospfv3::Ospfv3LinkLsa::setLinkLocalInterfaceAdd (const ::inet::L3Address & linkLocalInterfaceAdd) virtual
Referenced by inet::ospfv3::Ospfv3Interface::originateLinkLSA().
setNumPrefixes()
virtual void inet::ospfv3::Ospfv3LinkLsa::setNumPrefixes (uint32_t numPrefixes) virtual
Referenced by inet::ospfv3::Ospfv3Interface::originateLinkLSA().
setOspfOptions()
virtual void inet::ospfv3::Ospfv3LinkLsa::setOspfOptions (const Ospfv3Options & ospfOptions) virtual
Referenced by inet::ospfv3::Ospfv3Interface::originateLinkLSA().
setPrefixes()
virtual void inet::ospfv3::Ospfv3LinkLsa::setPrefixes (size_t k, const Ospfv3LsaPrefix0 & prefixes) virtual
Referenced by inet::ospfv3::Ospfv3Interface::originateLinkLSA().
setPrefixesArraySize()
virtual void inet::ospfv3::Ospfv3LinkLsa::setPrefixesArraySize (size_t size) virtual
Referenced by inet::ospfv3::Ospfv3Interface::originateLinkLSA().
setRouterPriority()
virtual void inet::ospfv3::Ospfv3LinkLsa::setRouterPriority (uint8_t routerPriority) virtual
Referenced by inet::ospfv3::Ospfv3Interface::originateLinkLSA().
Member Data Documentation
linkLocalInterfaceAdd
::inet::L3Address inet::ospfv3::Ospfv3LinkLsa::linkLocalInterfaceAdd protected
numPrefixes
uint32_t inet::ospfv3::Ospfv3LinkLsa::numPrefixes = 0 protected
ospfOptions
Ospfv3Options inet::ospfv3::Ospfv3LinkLsa::ospfOptions protected
prefixes
Ospfv3LsaPrefix0* inet::ospfv3::Ospfv3LinkLsa::prefixes = nullptr protected
prefixes_arraysize
size_t inet::ospfv3::Ospfv3LinkLsa::prefixes_arraysize = 0 protected
routerPriority
uint8_t inet::ospfv3::Ospfv3LinkLsa::routerPriority = 0 protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h