INET Framework for OMNeT++/OMNEST: inet::PsbTimerMsg Class Reference
inet::PsbTimerMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:46 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
PsbTimerMsg (const char *name=nullptr, short kind=0)
PsbTimerMsg (const PsbTimerMsg &other)
virtual ~PsbTimerMsg ()
PsbTimerMsg & operator= (const PsbTimerMsg &other)
virtual PsbTimerMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getId () const
virtual void setId (int id)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const PsbTimerMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
int id = 0
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const PsbTimerMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:46 by opp_msgtool.
//
// FIXME missing documentation
//
message PsbTimerMsg extends SignallingMsg
{
    int id;
    command = MSG_PSB_TIMER;
}
Constructor & Destructor Documentation
PsbTimerMsg() [1/2]
inet::PsbTimerMsg::PsbTimerMsg (const char * name = nullptr, short kind = 0)
PsbTimerMsg() [2/2]
inet::PsbTimerMsg::PsbTimerMsg (const PsbTimerMsg & other)
~PsbTimerMsg()
virtual inet::PsbTimerMsg::~PsbTimerMsg () virtual
Member Function Documentation
copy()
void inet::PsbTimerMsg::copy (const PsbTimerMsg & other) private
dup()
virtual PsbTimerMsg* inet::PsbTimerMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new PsbTimerMsg(*this);}
getId()
virtual int inet::PsbTimerMsg::getId () const virtual
Referenced by inet::RsvpTe::processPSB_TIMER().
operator=()
PsbTimerMsg& inet::PsbTimerMsg::operator= (const PsbTimerMsg & other)
operator==()
bool inet::PsbTimerMsg::operator== (const PsbTimerMsg &) protected delete
parsimPack()
virtual void inet::PsbTimerMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::PsbTimerMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setId()
virtual void inet::PsbTimerMsg::setId (int id) virtual
Referenced by inet::RsvpTe::createIngressPSB(), and inet::RsvpTe::createPSB().
Member Data Documentation
id
int inet::PsbTimerMsg::id = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h