INET Framework for OMNeT++/OMNEST: inet::NextHopAddressReq Class Reference
inet::NextHopAddressReq Class Reference
Class generated from inet/networklayer/common/NextHopAddressTag.msg:14 by opp_msgtool.
#include <NextHopAddressTag_m.h>
Public Member Functions
NextHopAddressReq ()
NextHopAddressReq (const NextHopAddressReq &other)
virtual ~NextHopAddressReq ()
NextHopAddressReq & operator= (const NextHopAddressReq &other)
virtual NextHopAddressReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const L3Address & getNextHopAddress () const
virtual L3Address & getNextHopAddressForUpdate ()
virtual void setNextHopAddress (const L3Address &nextHopAddress)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const NextHopAddressReq &)=delete
Protected Attributes
L3Address nextHopAddress
Private Member Functions
void copy (const NextHopAddressReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/networklayer/common/NextHopAddressTag.msg:14 by opp_msgtool.
class NextHopAddressReq extends TagBase
{
    L3Address nextHopAddress;      // may be unspecified
}
Constructor & Destructor Documentation
NextHopAddressReq() [1/2]
inet::NextHopAddressReq::NextHopAddressReq ()
NextHopAddressReq() [2/2]
inet::NextHopAddressReq::NextHopAddressReq (const NextHopAddressReq & other)
~NextHopAddressReq()
virtual inet::NextHopAddressReq::~NextHopAddressReq () virtual
Member Function Documentation
copy()
void inet::NextHopAddressReq::copy (const NextHopAddressReq & other) private
dup()
virtual NextHopAddressReq* inet::NextHopAddressReq::dup () const inline override virtual
 {return new NextHopAddressReq(*this);}
getNextHopAddress()
virtual const L3Address& inet::NextHopAddressReq::getNextHopAddress () const virtual
Referenced by inet::NetfilterInfoHook::datagramPostRoutingHook(), and inet::Ipv4::getNextHop().
getNextHopAddressForUpdate()
virtual L3Address& inet::NextHopAddressReq::getNextHopAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<NextHopAddressReq*>(this)->getNextHopAddress());}
operator=()
NextHopAddressReq& inet::NextHopAddressReq::operator= (const NextHopAddressReq & other)
operator==()
bool inet::NextHopAddressReq::operator== (const NextHopAddressReq &) protected delete
parsimPack()
virtual void inet::NextHopAddressReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::NextHopAddressReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setNextHopAddress()
virtual void inet::NextHopAddressReq::setNextHopAddress (const L3Address & nextHopAddress) virtual
Member Data Documentation
nextHopAddress
L3Address inet::NextHopAddressReq::nextHopAddress protected
The documentation for this class was generated from the following file:
NextHopAddressTag_m.h