INET Framework for OMNeT++/OMNEST: inet::EthernetMacBase Class Reference
inet::EthernetMacBase Class Reference
Base class for Ethernet MAC implementations.
#include <EthernetMacBase.h>
Classes
struct EtherDescr
Public Types
enum MacTransmitState {
TX_IDLE_STATE = 1, WAIT_IFG_STATE, SEND_IFG_STATE, TRANSMITTING_STATE,
JAMMING_STATE, BACKOFF_STATE, PAUSE_STATE
}
enum MacReceiveState { RX_IDLE_STATE = 1, RECEIVING_STATE, RX_COLLISION_STATE, RX_RECONNECT_STATE }
Public Member Functions
EthernetMacBase ()
virtual ~EthernetMacBase ()
virtual MacAddress getMacAddress ()
double getTxRate ()
bool isActive ()
MacTransmitState getTransmitState ()
MacReceiveState getReceiveState ()
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual void processAtHandleMessageFinished ()
void addPaddingAndSetFcs (Packet *packet, B requiredMinByteLength=MIN_ETHERNET_FRAME_BYTES) const
Inserts padding in front of FCS and calculate FCS.
virtual queueing::IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
virtual void handleCanPullPacketChanged (cGate *gate)=0
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
Static Public Attributes
static const double SPEED_OF_LIGHT_IN_CABLE = 200000000.0
Protected Types
enum SelfMsgKindValues {
ENDIFG = 100, ENDRECEPTION, ENDBACKOFF, ENDTRANSMISSION,
ENDJAMMING, ENDPAUSE
}
enum { NUM_OF_ETHERDESCRS = 11 }
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Protected Member Functions
virtual void initialize (int stage) override
virtual int numInitStages () const override
virtual void initializeFlags ()
virtual void initializeStatistics ()
virtual void finish () override
virtual bool dropFrameNotForUs (Packet *packet, const Ptr< const EthernetMacHeader > &frame)
Checks destination address and drops the frame when frame is not for us; returns true if frame is dropped.
virtual void readChannelParameters (bool errorWhenAsymmetric)
Calculates datarates, etc.
virtual void printParameters ()
virtual void processConnectDisconnect ()
virtual void encapsulate (Packet *packet)
virtual void decapsulate (Packet *packet)
bool verifyCrcAndLength (Packet *packet)
Verify ethernet packet: check FCS and payload length.
virtual void configureNetworkInterface () override
virtual void refreshDisplay () const override
virtual void receiveSignal (cComponent *src, simsignal_t signalId, cObject *obj, cObject *details) override
virtual void refreshConnection ()
void changeTransmissionState (MacTransmitState newState)
void changeReceptionState (MacReceiveState newState)
virtual void cutEthernetSignalEnd (EthernetSignalBase *signal, simtime_t duration)
virtual void txFinished ()
Protected Member Functions inherited from inet::MacProtocolBase
MacProtocolBase ()
virtual ~MacProtocolBase ()
virtual void registerInterface ()
virtual MacAddress parseMacAddressParameter (const char *addrstr)
virtual void deleteCurrentTxFrame ()
virtual void dropCurrentTxFrame (PacketDropDetails &details)
virtual void handleMessageWhenDown (cMessage *msg) override
virtual void sendUp (cMessage *message)
virtual void sendDown (cMessage *message)
virtual bool isUpperMessage (cMessage *message) const override
virtual bool isLowerMessage (cMessage *message) const override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void flushQueue (PacketDropDetails &details)
should clear queue and emit signal "packetDropped" with entire packets
virtual void clearQueue ()
should clear queue silently
queueing::IPacketQueue * getQueue (cGate *gate) const
virtual bool canDequeuePacket () const
virtual Packet * dequeuePacket ()
Protected Member Functions inherited from inet::LayeredProtocolBase
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleSelfMessage (cMessage *message)
virtual void handleUpperMessage (cMessage *message)
virtual void handleLowerMessage (cMessage *message)
virtual void handleUpperCommand (cMessage *message)
virtual void handleLowerCommand (cMessage *message)
virtual void handleUpperPacket (Packet *packet)
virtual void handleLowerPacket (Packet *packet)
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
const char * displayStringTextFormat = nullptr
bool sendRawBytes = false
FcsMode fcsMode = FCS_MODE_UNDEFINED
const EtherDescr * curEtherDescr = nullptr
bool connected = false
bool promiscuous = false
bool duplexMode = false
bool frameBursting = false
cChannel * transmissionChannel = nullptr
cGate * physInGate = nullptr
cGate * physOutGate = nullptr
bool channelsDiffer = false
MacTransmitState transmitState = static_cast<MacTransmitState>(-1)
MacReceiveState receiveState = static_cast<MacReceiveState>(-1)
simtime_t lastTxFinishTime
int pauseUnitsRequested = 0
cMessage * endTxTimer = nullptr
cMessage * endIfgTimer = nullptr
cMessage * endPauseTimer = nullptr
EthernetSignalBase * curTxSignal = nullptr
unsigned long numFramesSent = 0
unsigned long numFramesReceivedOK = 0
unsigned long numBytesSent = 0
unsigned long numBytesReceivedOK = 0
unsigned long numFramesFromHL = 0
unsigned long numDroppedPkFromHLIfaceDown = 0
unsigned long numDroppedIfaceDown = 0
unsigned long numDroppedBitError = 0
unsigned long numDroppedNotForUs = 0
unsigned long numFramesPassedToHL = 0
unsigned long numPauseFramesRcvd = 0
unsigned long numPauseFramesSent = 0
Protected Attributes inherited from inet::MacProtocolBase
int upperLayerInGateId = -1
Gate ids.
int upperLayerOutGateId = -1
int lowerLayerInGateId = -1
int lowerLayerOutGateId = -1
opp_component_ptr< NetworkInterface > networkInterface
opp_component_ptr< cModule > hostModule
Packet * currentTxFrame = nullptr
Currently transmitted frame if any.
opp_component_ptr< queueing::IPacketQueue > txQueue
Messages received from upper layer and to be transmitted later.
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Static Protected Attributes
static const EtherDescr etherDescrs [NUM_OF_ETHERDESCRS]
static const EtherDescr nullEtherDescr
static simsignal_t rxPkOkSignal = registerSignal("rxPkOk")
static simsignal_t txPausePkUnitsSignal = registerSignal("txPausePkUnits")
static simsignal_t rxPausePkUnitsSignal = registerSignal("rxPausePkUnits")
static simsignal_t transmissionStateChangedSignal = registerSignal("transmissionStateChanged")
static simsignal_t receptionStateChangedSignal = registerSignal("receptionStateChanged")
Detailed Description
Base class for Ethernet MAC implementations.
Member Enumeration Documentation
anonymous enum
anonymous enum protected
Enumerator
NUM_OF_ETHERDESCRS
          {
         NUM_OF_ETHERDESCRS = 11
     };
MacReceiveState
enum inet::EthernetMacBase::MacReceiveState
Enumerator
RX_IDLE_STATE
RECEIVING_STATE
RX_COLLISION_STATE
RX_RECONNECT_STATE
{
         RX_IDLE_STATE = 1,
         RECEIVING_STATE,
         RX_COLLISION_STATE,
         RX_RECONNECT_STATE
         // FIXME add RX_OFF_STATE
     };
MacTransmitState
enum inet::EthernetMacBase::MacTransmitState
Enumerator
TX_IDLE_STATE
WAIT_IFG_STATE
SEND_IFG_STATE
TRANSMITTING_STATE
JAMMING_STATE
BACKOFF_STATE
PAUSE_STATE
{
         TX_IDLE_STATE = 1,
         WAIT_IFG_STATE,
         SEND_IFG_STATE,
         TRANSMITTING_STATE,
         JAMMING_STATE,
         BACKOFF_STATE,
         PAUSE_STATE
         // FIXME add TX_OFF_STATE
     };
SelfMsgKindValues
enum inet::EthernetMacBase::SelfMsgKindValues protected
Enumerator
ENDIFG
ENDRECEPTION
ENDBACKOFF
ENDTRANSMISSION
ENDJAMMING
ENDPAUSE
{
         ENDIFG = 100,
         ENDRECEPTION,
         ENDBACKOFF,
         ENDTRANSMISSION,
         ENDJAMMING,
         ENDPAUSE
     };
Constructor & Destructor Documentation
EthernetMacBase()
inet::EthernetMacBase::EthernetMacBase ()
 {
     lastTxFinishTime = -1.0; // never equals to current simtime
     curEtherDescr = &nullEtherDescr;
 }
~EthernetMacBase()
inet::EthernetMacBase::~EthernetMacBase () virtual
 {
     delete curTxSignal;
     cancelAndDelete(endTxTimer);
     cancelAndDelete(endIfgTimer);
     cancelAndDelete(endPauseTimer);
 }
Member Function Documentation
addPaddingAndSetFcs()
void inet::EthernetMacBase::addPaddingAndSetFcs (Packet * packet, B requiredMinByteLength = MIN_ETHERNET_FRAME_BYTES) const
Inserts padding in front of FCS and calculate FCS.
 {
     auto ethFcs = packet->removeAtBack<EthernetFcs>(ETHER_FCS_BYTES);
     ethFcs->setFcsMode(fcsMode);
     B paddingLength = requiredMinBytes - ETHER_FCS_BYTES - B(packet->getByteLength());
     if (paddingLength > B(0)) {
         const auto& ethPadding = makeShared<EthernetPadding>();
         ethPadding->setChunkLength(paddingLength);
         packet->insertAtBack(ethPadding);
     }
     switch (ethFcs->getFcsMode()) {
         case FCS_DECLARED_CORRECT:
             ethFcs->setFcs(0xC00DC00DL);
             break;
         case FCS_DECLARED_INCORRECT:
             ethFcs->setFcs(0xBAADBAADL);
             break;
         case FCS_COMPUTED: { // calculate FCS
             auto ethBytes = packet->peekDataAsBytes();
             auto bufferLength = B(ethBytes->getChunkLength()).get();
             auto buffer = new uint8_t[bufferLength];
             // 1. fill in the data
             ethBytes->copyToBuffer(buffer, bufferLength);
             // 2. compute the FCS
             auto computedFcs = ethernetCRC(buffer, bufferLength);
             delete[] buffer;
             ethFcs->setFcs(computedFcs);
             break;
         }
         default:
             throw cRuntimeError("Unknown FCS mode: %d", (int)(ethFcs->getFcsMode()));
     }
     packet->insertAtBack(ethFcs);
 }
Referenced by inet::EthernetMac::handleUpperPacket(), and inet::EthernetCsmaMac::handleUpperPacket().
changeReceptionState()
void inet::EthernetMacBase::changeReceptionState (MacReceiveState newState) protected
 {
     receiveState = newState;
     emit(receptionStateChangedSignal, newState);
 }
Referenced by inet::EthernetCsmaMac::handleEndRxPeriod(), inet::EthernetCsmaMac::processConnectDisconnect(), processConnectDisconnect(), inet::EthernetCsmaMac::processDetectedCollision(), and inet::EthernetCsmaMac::processMsgFromNetwork().
changeTransmissionState()
void inet::EthernetMacBase::changeTransmissionState (MacTransmitState newState) protected
 {
     transmitState = newState;
     emit(transmissionStateChangedSignal, newState);
 }
Referenced by inet::EthernetMac::beginSendFrames(), inet::EthernetCsmaMac::beginSendFrames(), inet::EthernetCsmaMac::fillIFGInBurst(), inet::EthernetCsmaMac::handleEndBackoffPeriod(), inet::EthernetMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetMac::handleEndPausePeriod(), inet::EthernetCsmaMac::handleRetransmission(), processConnectDisconnect(), inet::EthernetMac::scheduleEndIFGPeriod(), inet::EthernetCsmaMac::scheduleEndIFGPeriod(), inet::EthernetMac::scheduleEndPausePeriod(), inet::EthernetCsmaMac::scheduleEndPausePeriod(), inet::EthernetCsmaMac::sendJamSignal(), inet::EthernetMac::startFrameTransmission(), and inet::EthernetCsmaMac::startFrameTransmission().
configureNetworkInterface()
void inet::EthernetMacBase::configureNetworkInterface () override protected virtual
Implements inet::MacProtocolBase.
 {
     // MTU: typical values are 576 (Internet de facto), 1500 (Ethernet-friendly),
     // 4000 (on some point-to-point links), 4470 (Cisco routers default, FDDI compatible)
     networkInterface->setMtu(par("mtu"));
     // capabilities
     networkInterface->setMulticast(true);
     networkInterface->setBroadcast(true);
 }
cutEthernetSignalEnd()
void inet::EthernetMacBase::cutEthernetSignalEnd (EthernetSignalBase * signal, simtime_t duration) protected virtual
 {
     ASSERT(duration <= signal->getDuration());
     if (duration == signal->getDuration())
         return;
     int64_t newBitLength = duration.dbl() * signal->getBitrate();
     if (auto packet = check_and_cast_nullable<Packet *>(signal->decapsulate())) {
         // TODO removed length calculation based on the PHY layer (parallel bits, bit order, etc.)
         if (newBitLength < packet->getBitLength()) {
             packet->trimFront();
             packet->setBackOffset(B(newBitLength / 8)); //TODO rounded down to byte align instead of b(newBitLength)
             packet->trimBack();
             packet->setBitError(true);
         }
         signal->encapsulate(packet);
     }
     signal->setBitError(true);
     signal->setBitLength(newBitLength);
     signal->setDuration(duration);
 }
Referenced by inet::EthernetCsmaMac::sendJamSignal().
decapsulate()
void inet::EthernetMacBase::decapsulate (Packet * packet) protected virtual
 {
     auto phyHeader = packet->popAtFront<EthernetPhyHeader>();
     ASSERT(packet->getDataLength() >= MIN_ETHERNET_FRAME_BYTES);
     packet->addTagIfAbsent<PacketProtocolTag>()->setProtocol(&Protocol::ethernetMac);
 }
Referenced by inet::EthernetCsmaMac::frameReceptionComplete(), inet::EthernetCsmaMac::handleSignalFromNetwork(), and inet::EthernetMac::processMsgFromNetwork().
dropFrameNotForUs()
bool inet::EthernetMacBase::dropFrameNotForUs (Packet * packet, const Ptr< const EthernetMacHeader > & frame) protected virtual
Checks destination address and drops the frame when frame is not for us; returns true if frame is dropped.
 {
     // Current ethernet mac implementation does not support the configuration of multicast
     // ethernet address groups. We rather accept all multicast frames (just like they were
     // broadcasts) and pass it up to the higher layer where they will be dropped
     // if not needed.
     //
     // PAUSE frames must be handled a bit differently because they are processed at
     // this level. Multicast PAUSE frames should not be processed unless they have a
     // destination of MULTICAST_PAUSE_ADDRESS. We drop all PAUSE frames that have a
     // different muticast destination. (Note: Would the multicast ethernet addressing
     // implemented, we could also process the PAUSE frames destined to any of our
     // multicast adresses)
     // All NON-PAUSE frames must be passed to the upper layer if the interface is
     // in promiscuous mode.
     if (frame->getDest().equals(getMacAddress()))
         return false;
     if (frame->getDest().isBroadcast())
         return false;
     bool isPause = (frame->getTypeOrLength() == ETHERTYPE_FLOW_CONTROL);
     if (!isPause && (promiscuous || frame->getDest().isMulticast()))
         return false;
     if (isPause && frame->getDest().equals(MacAddress::MULTICAST_PAUSE_ADDRESS))
         return false;
     EV_WARN << "Frame `" << packet->getName() << "' not destined to us, discarding\n";
     numDroppedNotForUs++;
     PacketDropDetails details;
     details.setReason(NOT_ADDRESSED_TO_US);
     emit(packetDroppedSignal, packet, &details);
     delete packet;
     return true;
 }
Referenced by inet::EthernetCsmaMac::frameReceptionComplete(), and inet::EthernetMac::processMsgFromNetwork().
encapsulate()
void inet::EthernetMacBase::encapsulate (Packet * packet) protected virtual
 {
     auto phyHeader = makeShared<EthernetPhyHeader>();
     frame->insertAtFront(phyHeader);
     frame->addTagIfAbsent<PacketProtocolTag>()->setProtocol(&Protocol::ethernetPhy);
 }
Referenced by inet::EthernetMac::startFrameTransmission(), and inet::EthernetCsmaMac::startFrameTransmission().
finish()
void inet::EthernetMacBase::finish () override protected virtual
Reimplemented in inet::EthernetCsmaMac, and inet::EthernetMac.
 {
     {
         simtime_t t = simTime();
         recordScalar("simulated time", t);
         recordScalar("full-duplex", duplexMode);
         if (t > 0) {
             recordScalar("frames/sec sent", numFramesSent / t);
             recordScalar("frames/sec rcvd", numFramesReceivedOK / t);
             recordScalar("bits/sec sent", (8.0 * numBytesSent) / t);
             recordScalar("bits/sec rcvd", (8.0 * numBytesReceivedOK) / t);
         }
     }
 }
Referenced by inet::EthernetCsmaMac::finish(), and inet::EthernetMac::finish().
getMacAddress()
virtual MacAddress inet::EthernetMacBase::getMacAddress () inline virtual
 { return networkInterface ? networkInterface->getMacAddress() : MacAddress::UNSPECIFIED_ADDRESS; }
Referenced by dropFrameNotForUs(), inet::EthernetMac::handleUpperPacket(), inet::EthernetCsmaMac::handleUpperPacket(), and printParameters().
getProvider()
queueing::IPassivePacketSource * inet::EthernetMacBase::getProvider (cGate * gate) override virtual
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
 {
     return (gate->getId() == upperLayerInGateId) ? txQueue.get() : nullptr;
 }
getReceiveState()
MacReceiveState inet::EthernetMacBase::getReceiveState () inline
 { return receiveState; }
getTransmitState()
MacTransmitState inet::EthernetMacBase::getTransmitState () inline
 { return transmitState; }
getTxRate()
double inet::EthernetMacBase::getTxRate () inline
 { return curEtherDescr->txrate; }
handleCrashOperation()
void inet::EthernetMacBase::handleCrashOperation (LifecycleOperation * operation) override virtual
Reimplemented from inet::MacProtocolBase.
 {
 //    clearQueue();
     connected = false;
     networkInterface->setCarrier(false);
     processConnectDisconnect();
     networkInterface->setState(NetworkInterface::State::DOWN);
 }
handlePullPacketProcessed()
void inet::EthernetMacBase::handlePullPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pulled packet is failed to be processed successfully. It allows the sink to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handlePullPacketProcessed");
     throw cRuntimeError("Not supported callback");
 }
handleStartOperation()
void inet::EthernetMacBase::handleStartOperation (LifecycleOperation * operation) override virtual
Reimplemented from inet::MacProtocolBase.
 {
     networkInterface->setState(NetworkInterface::State::UP);
     initializeFlags();
     readChannelParameters(true);
 }
handleStopOperation()
void inet::EthernetMacBase::handleStopOperation (LifecycleOperation * operation) override virtual
Reimplemented from inet::MacProtocolBase.
 {
     if (currentTxFrame != nullptr || !txQueue->isEmpty()) {
         networkInterface->setState(NetworkInterface::State::GOING_DOWN);
         delayActiveOperationFinish(par("stopOperationTimeout"));
     }
     else {
         networkInterface->setCarrier(false);
         networkInterface->setState(NetworkInterface::State::DOWN);
         startActiveOperationExtraTimeOrFinish(par("stopOperationExtraTime"));
     }
 }
initialize()
void inet::EthernetMacBase::initialize (int stage) override protected virtual
Reimplemented from inet::MacProtocolBase.
Reimplemented in inet::EthernetCsmaMac, and inet::EthernetMac.
 {
     MacProtocolBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         fcsMode = parseFcsMode(par("fcsMode"));
         physInGate = gate("phys$i");
         physOutGate = gate("phys$o");
         lowerLayerInGateId = physInGate->getId();
         lowerLayerOutGateId = physOutGate->getId();
         transmissionChannel = nullptr;
         txQueue = getQueue(gate(upperLayerInGateId));
         initializeFlags();
         initializeStatistics();
         lastTxFinishTime = -1.0; // not equals with current simtime.
         // initialize self messages
         endTxTimer = new cMessage("EndTransmission", ENDTRANSMISSION);
         endIfgTimer = new cMessage("EndIFG", ENDIFG);
         endPauseTimer = new cMessage("EndPause", ENDPAUSE);
         // initialize states
         transmitState = TX_IDLE_STATE;
         receiveState = RX_IDLE_STATE;
         // initialize pause
         pauseUnitsRequested = 0;
         subscribe(POST_MODEL_CHANGE, this);
         WATCH(transmitState);
         WATCH(receiveState);
         WATCH(connected);
         WATCH(frameBursting);
         WATCH(promiscuous);
         WATCH(pauseUnitsRequested);
     }
 }
Referenced by inet::EthernetMac::initialize(), and inet::EthernetCsmaMac::initialize().
initializeFlags()
void inet::EthernetMacBase::initializeFlags () protected virtual
Reimplemented in inet::EthernetCsmaMac, and inet::EthernetMac.
 {
     displayStringTextFormat = par("displayStringTextFormat");
     sendRawBytes = par("sendRawBytes");
     duplexMode = true;
     // initialize connected flag
     connected = physOutGate->getPathEndGate()->isConnected() && physInGate->getPathStartGate()->isConnected();
     if (!connected)
         EV_WARN << "MAC not connected to a network.\n";
     // initialize promiscuous flag
     promiscuous = par("promiscuous");
     frameBursting = false;
 }
Referenced by handleStartOperation(), initialize(), inet::EthernetMac::initializeFlags(), and inet::EthernetCsmaMac::initializeFlags().
initializeStatistics()
void inet::EthernetMacBase::initializeStatistics () protected virtual
Reimplemented in inet::EthernetCsmaMac, and inet::EthernetMac.
 {
     numFramesSent = numFramesReceivedOK = numBytesSent = numBytesReceivedOK = 0;
     numFramesPassedToHL = numDroppedBitError = numDroppedNotForUs = 0;
     numFramesFromHL = numDroppedIfaceDown = numDroppedPkFromHLIfaceDown = 0;
     numPauseFramesRcvd = numPauseFramesSent = 0;
     WATCH(numFramesSent);
     WATCH(numFramesReceivedOK);
     WATCH(numBytesSent);
     WATCH(numBytesReceivedOK);
     WATCH(numFramesFromHL);
     WATCH(numDroppedPkFromHLIfaceDown);
     WATCH(numDroppedIfaceDown);
     WATCH(numDroppedBitError);
     WATCH(numDroppedNotForUs);
     WATCH(numFramesPassedToHL);
     WATCH(numPauseFramesRcvd);
     WATCH(numPauseFramesSent);
 }
Referenced by initialize(), inet::EthernetMac::initializeStatistics(), and inet::EthernetCsmaMac::initializeStatistics().
isActive()
bool inet::EthernetMacBase::isActive () inline
 { return connected; }
numInitStages()
virtual int inet::EthernetMacBase::numInitStages () const inline override protected virtual
Reimplemented in inet::EthernetCsmaMac, and inet::EthernetMac.
 { return NUM_INIT_STAGES; }
printParameters()
void inet::EthernetMacBase::printParameters () protected virtual
 {
     // Dump parameters
     EV_DETAIL << "MAC address: " << getMacAddress() << (promiscuous ? ", promiscuous mode" : "") << endl
               << "txrate: " << curEtherDescr->txrate << " bps, "
               << (duplexMode ? "full-duplex" : "half-duplex") << endl
               << "bitTime: " << 1e9 / curEtherDescr->txrate << " ns" << endl
               << "frameBursting: " << (frameBursting ? "on" : "off") << endl
               << "slotTime: " << curEtherDescr->slotTime << endl
               << "interFrameGap: " << INTERFRAME_GAP_BITS / curEtherDescr->txrate << endl
               << endl;
 }
processAtHandleMessageFinished()
void inet::EthernetMacBase::processAtHandleMessageFinished () virtual
 {
     if (operationalState == State::STOPPING_OPERATION) {
         if (currentTxFrame == nullptr && txQueue->isEmpty()) {
             EV << "Ethernet Queue is empty, MAC stopped\n";
             connected = false;
             networkInterface->setCarrier(false);
             processConnectDisconnect();
             networkInterface->setState(NetworkInterface::State::DOWN);
             startActiveOperationExtraTimeOrFinish(par("stopOperationExtraTime"));
         }
     }
 }
Referenced by inet::EthernetMac::handleMessageWhenUp(), and inet::EthernetCsmaMac::handleMessageWhenUp().
processConnectDisconnect()
void inet::EthernetMacBase::processConnectDisconnect () protected virtual
Reimplemented in inet::EthernetCsmaMac.
 {
     if (!connected) {
         cancelEvent(endTxTimer);
         cancelEvent(endIfgTimer);
         cancelEvent(endPauseTimer);
         if (currentTxFrame) {
             EV_DETAIL << "Interface is not connected, dropping packet " << currentTxFrame << endl;
             numDroppedPkFromHLIfaceDown++;
             PacketDropDetails details;
             details.setReason(INTERFACE_DOWN);
             dropCurrentTxFrame(details);
             lastTxFinishTime = -1.0; // so that it never equals to the current simtime, used for Burst mode detection.
         }
         // Clear queue
         while (canDequeuePacket()) {
             Packet *msg = dequeuePacket();
             EV_DETAIL << "Interface is not connected, dropping packet " << msg << endl;
             numDroppedPkFromHLIfaceDown++;
             PacketDropDetails details;
             details.setReason(INTERFACE_DOWN);
             emit(packetDroppedSignal, msg, &details);
             delete msg;
         }
         changeTransmissionState(TX_IDLE_STATE); // FIXME replace status to OFF
         changeReceptionState(RX_IDLE_STATE);
     }
     // FIXME when connect, set statuses to RECONNECT or IDLE
 }
Referenced by handleCrashOperation(), processAtHandleMessageFinished(), inet::EthernetCsmaMac::processConnectDisconnect(), and refreshConnection().
readChannelParameters()
void inet::EthernetMacBase::readChannelParameters (bool errorWhenAsymmetric) protected virtual
Calculates datarates, etc.
Verifies the datarates on the incoming/outgoing channels, and throws error when they differ and the parameter errorWhenAsymmetric is true.
Reimplemented in inet::EthernetCsmaMac.
 {
     // When the connected channels change at runtime, we'll receive
     // two separate notifications (one for the rx channel and one for the tx one),
     // so we cannot immediately raise an error when they differ. Rather, we'll need
     // to verify at the next opportunity (event) that the two channels have eventually
     // been set to the same value.
     cDatarateChannel *outTrChannel = check_and_cast_nullable<cDatarateChannel *>(physOutGate->findTransmissionChannel());
     cDatarateChannel *inTrChannel = check_and_cast_nullable<cDatarateChannel *>(physInGate->findIncomingTransmissionChannel());
     connected = physOutGate->getPathEndGate()->isConnected() && physInGate->getPathStartGate()->isConnected();
     if (connected && ((!outTrChannel) || (!inTrChannel)))
         throw cRuntimeError("Ethernet phys gate must be connected using a transmission channel");
     double txRate = outTrChannel ? outTrChannel->getNominalDatarate() : 0.0;
     double rxRate = inTrChannel ? inTrChannel->getNominalDatarate() : 0.0;
     bool rxDisabled = !inTrChannel || inTrChannel->isDisabled();
     bool txDisabled = !outTrChannel || outTrChannel->isDisabled();
     if (errorWhenAsymmetric && (rxDisabled != txDisabled))
         throw cRuntimeError("The enablements of the input/output channels differ (rx=%s vs tx=%s)", rxDisabled ? "off" : "on", txDisabled ? "off" : "on");
     if (txDisabled)
         connected = false;
     bool dataratesDiffer;
     if (!connected) {
         curEtherDescr = &nullEtherDescr;
         dataratesDiffer = false;
         if (!outTrChannel)
             transmissionChannel = nullptr;
         if (networkInterface) {
             networkInterface->setCarrier(false);
             networkInterface->setDatarate(0);
         }
     }
     else {
         if (outTrChannel && !transmissionChannel)
             outTrChannel->subscribe(POST_MODEL_CHANGE, this);
         transmissionChannel = outTrChannel;
         dataratesDiffer = (txRate != rxRate);
     }
     channelsDiffer = dataratesDiffer || (rxDisabled != txDisabled);
     if (errorWhenAsymmetric && dataratesDiffer)
         throw cRuntimeError("The input/output datarates differ (rx=%g bps vs tx=%g bps)", rxRate, txRate);
     if (connected) {
         // Check valid speeds
         for (auto& etherDescr : etherDescrs) {
             if (txRate == etherDescr.txrate) {
                 curEtherDescr = &(etherDescr);
                 if (networkInterface) {
                     networkInterface->setCarrier(true);
                     networkInterface->setDatarate(txRate);
                 }
                 return;
             }
         }
         throw cRuntimeError("Invalid transmission rate %g bps on channel %s at module %s",
                 txRate, transmissionChannel->getFullPath().c_str(), getFullPath().c_str());
     }
 }
Referenced by inet::EthernetMac::handleMessageWhenUp(), handleStartOperation(), inet::EthernetCsmaMac::readChannelParameters(), and refreshConnection().
receiveSignal()
void inet::EthernetMacBase::receiveSignal (cComponent * src, simsignal_t signalId, cObject * obj, cObject * details) override protected virtual
Reimplemented from inet::MacProtocolBase.
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     MacProtocolBase::receiveSignal(source, signalID, obj, details);
     if (signalID == POST_MODEL_CHANGE) {
         if (auto gcobj = dynamic_cast<cPostPathCreateNotification *>(obj)) {
             if ((physOutGate == gcobj->pathStartGate) || (physInGate == gcobj->pathEndGate))
                 refreshConnection();
         }
         else if (auto gcobj = dynamic_cast<cPostPathCutNotification *>(obj)) {
             if ((physOutGate == gcobj->pathStartGate) || (physInGate == gcobj->pathEndGate))
                 refreshConnection();
         }
         else if (transmissionChannel && dynamic_cast<cPostParameterChangeNotification *>(obj)) { // note: we are subscribed to the channel object too
             cPostParameterChangeNotification *gcobj = static_cast<cPostParameterChangeNotification *>(obj);
             if (transmissionChannel == gcobj->par->getOwner())
                 refreshConnection();
         }
     }
 }
refreshConnection()
void inet::EthernetMacBase::refreshConnection () protected virtual
 {
     Enter_Method("refreshConnection");
     bool oldConn = connected;
     readChannelParameters(false);
     if (oldConn != connected)
         processConnectDisconnect();
 }
Referenced by receiveSignal().
refreshDisplay()
void inet::EthernetMacBase::refreshDisplay () const override protected virtual
 {
     MacProtocolBase::refreshDisplay();
     // icon coloring
     const char *color;
     if (receiveState == RX_COLLISION_STATE)
         color = "red";
     else if (transmitState == TRANSMITTING_STATE)
         color = "yellow";
     else if (transmitState == JAMMING_STATE)
         color = "red";
     else if (receiveState == RECEIVING_STATE)
         color = "#4040ff";
     else if (transmitState == BACKOFF_STATE)
         color = "white";
     else if (transmitState == PAUSE_STATE)
         color = "gray";
     else
         color = "";
     getDisplayString().setTagArg("i", 1, color);
     if (!strcmp(getParentModule()->getNedTypeName(), "inet.linklayer.ethernet.EthernetInterface"))
         getParentModule()->getDisplayString().setTagArg("i", 1, color);
     auto text = StringFormat::formatString(displayStringTextFormat, [&] (char directive) {
         static std::string result;
         switch (directive) {
             case 's':
                 result = std::to_string(numFramesSent);
                 break;
             case 'r':
                 result = std::to_string(numFramesReceivedOK);
                 break;
             case 'd':
                 result = std::to_string(numDroppedPkFromHLIfaceDown + numDroppedIfaceDown + numDroppedBitError + numDroppedNotForUs);
                 break;
             case 'q':
                 result = txQueue != nullptr ? std::to_string(txQueue->getNumPackets()) : "";
                 break;
             case 'b':
                 if (transmissionChannel == nullptr)
                     result = "not connected";
                 else {
                     char datarateText[40];
                     double datarate = transmissionChannel->getNominalDatarate();
                     if (datarate >= 1e9)
                         sprintf(datarateText, "%gGbps", datarate / 1e9);
                     else if (datarate >= 1e6)
                         sprintf(datarateText, "%gMbps", datarate / 1e6);
                     else if (datarate >= 1e3)
                         sprintf(datarateText, "%gkbps", datarate / 1e3);
                     else
                         sprintf(datarateText, "%gbps", datarate);
                     result = datarateText;
                 }
                 break;
             default:
                 throw cRuntimeError("Unknown directive: %c", directive);
         }
         return result.c_str();
     });
     getDisplayString().setTagArg("t", 0, text);
 }
txFinished()
void inet::EthernetMacBase::txFinished () protected virtual
 {
     ASSERT(curTxSignal != nullptr);
     delete curTxSignal;
     curTxSignal = nullptr;
 }
Referenced by inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndJammingPeriod(), inet::EthernetMac::handleEndTxPeriod(), and inet::EthernetCsmaMac::handleEndTxPeriod().
verifyCrcAndLength()
bool inet::EthernetMacBase::verifyCrcAndLength (Packet * packet) protected
Verify ethernet packet: check FCS and payload length.
 {
     EV_STATICCONTEXT;
     auto ethHeader = packet->peekAtFront<EthernetMacHeader>(); // FIXME can I use any flags?
     const auto& ethTrailer = packet->peekAtBack<EthernetFcs>(ETHER_FCS_BYTES); // FIXME can I use any flags?
     switch (ethTrailer->getFcsMode()) {
         case FCS_DECLARED_CORRECT:
             break;
         case FCS_DECLARED_INCORRECT:
             EV_ERROR << "incorrect FCS in ethernet frame\n";
             return false;
         case FCS_COMPUTED: {
             bool isFcsBad = false;
             // check the FCS
             auto ethBytes = packet->peekDataAt<BytesChunk>(B(0), packet->getDataLength() - ethTrailer->getChunkLength());
             auto bufferLength = B(ethBytes->getChunkLength()).get();
             auto buffer = new uint8_t[bufferLength];
             // 1. fill in the data
             ethBytes->copyToBuffer(buffer, bufferLength);
             // 2. compute the FCS
             auto computedFcs = ethernetCRC(buffer, bufferLength);
             delete[] buffer;
             isFcsBad = (computedFcs != ethTrailer->getFcs()); // FIXME how to check fcs?
             if (isFcsBad)
                 return false;
             break;
         }
         default:
             throw cRuntimeError("invalid FCS mode in ethernet frame");
     }
     if (isIeee8023Header(*ethHeader)) {
         b payloadLength = B(ethHeader->getTypeOrLength());
         return payloadLength <= packet->getDataLength() - (ethHeader->getChunkLength() + ethTrailer->getChunkLength());
     }
     return true;
 }
Referenced by inet::EthernetCsmaMac::frameReceptionComplete(), and inet::EthernetMac::processMsgFromNetwork().
Member Data Documentation
channelsDiffer
bool inet::EthernetMacBase::channelsDiffer = false protected
Referenced by inet::EthernetMac::handleMessageWhenUp(), inet::EthernetCsmaMac::handleMessageWhenUp(), and readChannelParameters().
connected
bool inet::EthernetMacBase::connected = false protected
Referenced by handleCrashOperation(), inet::EthernetCsmaMac::handleSignalFromNetwork(), inet::EthernetMac::handleUpperPacket(), inet::EthernetCsmaMac::handleUpperPacket(), initialize(), initializeFlags(), processAtHandleMessageFinished(), inet::EthernetCsmaMac::processConnectDisconnect(), processConnectDisconnect(), inet::EthernetMac::processMsgFromNetwork(), inet::EthernetCsmaMac::readChannelParameters(), readChannelParameters(), and refreshConnection().
curEtherDescr
const EtherDescr* inet::EthernetMacBase::curEtherDescr = nullptr protected
Referenced by inet::EthernetCsmaMac::calculateMinFrameLength(), inet::EthernetCsmaMac::canContinueBurst(), EthernetMacBase(), inet::EthernetCsmaMac::fillIFGInBurst(), inet::EthernetCsmaMac::handleRetransmission(), inet::EthernetCsmaMac::handleSignalFromNetwork(), printParameters(), inet::EthernetCsmaMac::processConnectDisconnect(), inet::EthernetCsmaMac::processMsgFromNetwork(), inet::EthernetCsmaMac::readChannelParameters(), readChannelParameters(), inet::EthernetMac::scheduleEndIFGPeriod(), inet::EthernetCsmaMac::scheduleEndIFGPeriod(), inet::EthernetMac::scheduleEndPausePeriod(), inet::EthernetCsmaMac::scheduleEndPausePeriod(), inet::EthernetCsmaMac::sendJamSignal(), inet::EthernetMac::startFrameTransmission(), and inet::EthernetCsmaMac::startFrameTransmission().
curTxSignal
EthernetSignalBase* inet::EthernetMacBase::curTxSignal = nullptr protected
Referenced by inet::EthernetCsmaMac::dropCurrentTxFrame(), inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndJammingPeriod(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), inet::EthernetCsmaMac::sendJamSignal(), inet::EthernetCsmaMac::sendSignal(), inet::EthernetMac::startFrameTransmission(), txFinished(), and ~EthernetMacBase().
displayStringTextFormat
const char* inet::EthernetMacBase::displayStringTextFormat = nullptr protected
Referenced by initializeFlags(), and refreshDisplay().
duplexMode
bool inet::EthernetMacBase::duplexMode = false protected
Referenced by inet::EthernetCsmaMac::calculateMinFrameLength(), finish(), inet::EthernetCsmaMac::frameReceptionComplete(), inet::EthernetCsmaMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleEndRxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleMessageWhenUp(), inet::EthernetCsmaMac::handleSignalFromNetwork(), inet::EthernetMac::initializeFlags(), inet::EthernetCsmaMac::initializeFlags(), initializeFlags(), printParameters(), inet::EthernetCsmaMac::processConnectDisconnect(), inet::EthernetMac::processMsgFromNetwork(), inet::EthernetCsmaMac::processMsgFromNetwork(), inet::EthernetCsmaMac::readChannelParameters(), inet::EthernetMac::startFrameTransmission(), and inet::EthernetCsmaMac::startFrameTransmission().
endIfgTimer
cMessage* inet::EthernetMacBase::endIfgTimer = nullptr protected
Referenced by inet::EthernetCsmaMac::fillIFGInBurst(), inet::EthernetMac::handleSelfMessage(), initialize(), processConnectDisconnect(), inet::EthernetCsmaMac::processMsgFromNetwork(), inet::EthernetMac::scheduleEndIFGPeriod(), inet::EthernetCsmaMac::scheduleEndIFGPeriod(), and ~EthernetMacBase().
endPauseTimer
cMessage* inet::EthernetMacBase::endPauseTimer = nullptr protected
Referenced by inet::EthernetMac::handleSelfMessage(), initialize(), processConnectDisconnect(), inet::EthernetMac::processPauseCommand(), inet::EthernetCsmaMac::processReceivedControlFrame(), inet::EthernetMac::scheduleEndPausePeriod(), inet::EthernetCsmaMac::scheduleEndPausePeriod(), and ~EthernetMacBase().
endTxTimer
cMessage* inet::EthernetMacBase::endTxTimer = nullptr protected
Referenced by inet::EthernetMac::handleSelfMessage(), initialize(), processConnectDisconnect(), inet::EthernetCsmaMac::processMsgFromNetwork(), inet::EthernetMac::startFrameTransmission(), inet::EthernetCsmaMac::startFrameTransmission(), and ~EthernetMacBase().
etherDescrs
const EthernetMacBase::EtherDescr inet::EthernetMacBase::etherDescrs static protected
Referenced by readChannelParameters().
fcsMode
FcsMode inet::EthernetMacBase::fcsMode = FCS_MODE_UNDEFINED protected
Referenced by addPaddingAndSetFcs(), and initialize().
frameBursting
bool inet::EthernetMacBase::frameBursting = false protected
Referenced by inet::EthernetCsmaMac::calculateMinFrameLength(), inet::EthernetCsmaMac::canContinueBurst(), initialize(), inet::EthernetCsmaMac::initializeFlags(), initializeFlags(), printParameters(), and inet::EthernetCsmaMac::startFrameTransmission().
lastTxFinishTime
simtime_t inet::EthernetMacBase::lastTxFinishTime protected
Referenced by EthernetMacBase(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), initialize(), and processConnectDisconnect().
nullEtherDescr
const EthernetMacBase::EtherDescr inet::EthernetMacBase::nullEtherDescr static protected
Initial value:
= {
    0.0,
    0.0,
    0,
    B(0),
    B(0),
    B(0),
    0.0,
    0.0
}
Referenced by EthernetMacBase(), and readChannelParameters().
numBytesReceivedOK
unsigned long inet::EthernetMacBase::numBytesReceivedOK = 0 protected
Referenced by finish(), initializeStatistics(), inet::EthernetMac::processReceivedDataFrame(), and inet::EthernetCsmaMac::processReceivedDataFrame().
numBytesSent
unsigned long inet::EthernetMacBase::numBytesSent = 0 protected
Referenced by finish(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), and initializeStatistics().
numDroppedBitError
unsigned long inet::EthernetMacBase::numDroppedBitError = 0 protected
Referenced by inet::EthernetCsmaMac::frameReceptionComplete(), initializeStatistics(), inet::EthernetMac::processMsgFromNetwork(), and refreshDisplay().
numDroppedIfaceDown
unsigned long inet::EthernetMacBase::numDroppedIfaceDown = 0 protected
Referenced by inet::EthernetCsmaMac::handleSignalFromNetwork(), initializeStatistics(), inet::EthernetMac::processMsgFromNetwork(), and refreshDisplay().
numDroppedNotForUs
unsigned long inet::EthernetMacBase::numDroppedNotForUs = 0 protected
Referenced by dropFrameNotForUs(), initializeStatistics(), and refreshDisplay().
numDroppedPkFromHLIfaceDown
unsigned long inet::EthernetMacBase::numDroppedPkFromHLIfaceDown = 0 protected
Referenced by inet::EthernetMac::handleUpperPacket(), inet::EthernetCsmaMac::handleUpperPacket(), initializeStatistics(), processConnectDisconnect(), and refreshDisplay().
numFramesFromHL
unsigned long inet::EthernetMacBase::numFramesFromHL = 0 protected
Referenced by inet::EthernetMac::handleUpperPacket(), inet::EthernetCsmaMac::handleUpperPacket(), and initializeStatistics().
numFramesPassedToHL
unsigned long inet::EthernetMacBase::numFramesPassedToHL = 0 protected
Referenced by initializeStatistics(), inet::EthernetMac::processReceivedDataFrame(), and inet::EthernetCsmaMac::processReceivedDataFrame().
numFramesReceivedOK
unsigned long inet::EthernetMacBase::numFramesReceivedOK = 0 protected
Referenced by finish(), initializeStatistics(), inet::EthernetMac::processReceivedDataFrame(), inet::EthernetCsmaMac::processReceivedDataFrame(), and refreshDisplay().
numFramesSent
unsigned long inet::EthernetMacBase::numFramesSent = 0 protected
Referenced by finish(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), initializeStatistics(), and refreshDisplay().
numPauseFramesRcvd
unsigned long inet::EthernetMacBase::numPauseFramesRcvd = 0 protected
Referenced by initializeStatistics(), inet::EthernetMac::processMsgFromNetwork(), and inet::EthernetCsmaMac::processReceivedControlFrame().
numPauseFramesSent
unsigned long inet::EthernetMacBase::numPauseFramesSent = 0 protected
Referenced by inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), and initializeStatistics().
pauseUnitsRequested
int inet::EthernetMacBase::pauseUnitsRequested = 0 protected
Referenced by inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), initialize(), inet::EthernetMac::processPauseCommand(), and inet::EthernetCsmaMac::processReceivedControlFrame().
physInGate
cGate* inet::EthernetMacBase::physInGate = nullptr protected
Referenced by inet::EthernetMac::handleMessageWhenUp(), inet::EthernetCsmaMac::handleMessageWhenUp(), initialize(), inet::EthernetMac::initializeFlags(), inet::EthernetCsmaMac::initializeFlags(), initializeFlags(), readChannelParameters(), and receiveSignal().
physOutGate
cGate* inet::EthernetMacBase::physOutGate = nullptr protected
Referenced by initialize(), initializeFlags(), readChannelParameters(), receiveSignal(), inet::EthernetCsmaMac::sendJamSignal(), inet::EthernetCsmaMac::sendSignal(), and inet::EthernetMac::startFrameTransmission().
promiscuous
bool inet::EthernetMacBase::promiscuous = false protected
Referenced by dropFrameNotForUs(), initialize(), initializeFlags(), and printParameters().
receiveState
MacReceiveState inet::EthernetMacBase::receiveState = static_cast<MacReceiveState>(-1) protected
Referenced by changeReceptionState(), inet::EthernetCsmaMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleEndBackoffPeriod(), inet::EthernetCsmaMac::handleEndRxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleMessageWhenUp(), initialize(), inet::EthernetCsmaMac::printState(), inet::EthernetCsmaMac::processDetectedCollision(), inet::EthernetCsmaMac::processMsgFromNetwork(), refreshDisplay(), and inet::EthernetCsmaMac::startFrameTransmission().
receptionStateChangedSignal
simsignal_t inet::EthernetMacBase::receptionStateChangedSignal = registerSignal("receptionStateChanged") static protected
Referenced by changeReceptionState().
rxPausePkUnitsSignal
simsignal_t inet::EthernetMacBase::rxPausePkUnitsSignal = registerSignal("rxPausePkUnits") static protected
Referenced by inet::EthernetMac::processMsgFromNetwork(), and inet::EthernetCsmaMac::processReceivedControlFrame().
rxPkOkSignal
simsignal_t inet::EthernetMacBase::rxPkOkSignal = registerSignal("rxPkOk") static protected
Referenced by inet::EthernetMac::processReceivedDataFrame(), and inet::EthernetCsmaMac::processReceivedDataFrame().
sendRawBytes
bool inet::EthernetMacBase::sendRawBytes = false protected
Referenced by initializeFlags(), inet::EthernetMac::startFrameTransmission(), and inet::EthernetCsmaMac::startFrameTransmission().
SPEED_OF_LIGHT_IN_CABLE
const double inet::EthernetMacBase::SPEED_OF_LIGHT_IN_CABLE = 200000000.0 static
Referenced by inet::EthernetCsmaMac::handleSignalFromNetwork().
transmissionChannel
cChannel* inet::EthernetMacBase::transmissionChannel = nullptr protected
Referenced by initialize(), readChannelParameters(), receiveSignal(), refreshDisplay(), and inet::EthernetMac::startFrameTransmission().
transmissionStateChangedSignal
simsignal_t inet::EthernetMacBase::transmissionStateChangedSignal = registerSignal("transmissionStateChanged") static protected
Referenced by changeTransmissionState().
transmitState
MacTransmitState inet::EthernetMacBase::transmitState = static_cast<MacTransmitState>(-1) protected
Referenced by changeTransmissionState(), inet::EthernetMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleEndBackoffPeriod(), inet::EthernetMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndJammingPeriod(), inet::EthernetMac::handleEndPausePeriod(), inet::EthernetCsmaMac::handleEndPausePeriod(), inet::EthernetCsmaMac::handleEndRxPeriod(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleMessageWhenUp(), inet::EthernetMac::handleUpperPacket(), initialize(), inet::EthernetCsmaMac::printState(), inet::EthernetCsmaMac::processMsgFromNetwork(), inet::EthernetMac::processPauseCommand(), inet::EthernetCsmaMac::processReceivedControlFrame(), and refreshDisplay().
txPausePkUnitsSignal
simsignal_t inet::EthernetMacBase::txPausePkUnitsSignal = registerSignal("txPausePkUnits") static protected
Referenced by inet::EthernetMac::handleEndTxPeriod(), and inet::EthernetCsmaMac::handleEndTxPeriod().
The documentation for this class was generated from the following files:
EthernetMacBase.h
EthernetMacBase.cc