INET Framework for OMNeT++/OMNEST: inet::LayeredProtocolBase Class Reference
inet::LayeredProtocolBase Class Reference abstract
#include <LayeredProtocolBase.h>
Protected Member Functions
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleSelfMessage (cMessage *message)
virtual void handleUpperMessage (cMessage *message)
virtual void handleLowerMessage (cMessage *message)
virtual void handleUpperCommand (cMessage *message)
virtual void handleLowerCommand (cMessage *message)
virtual void handleUpperPacket (Packet *packet)
virtual void handleLowerPacket (Packet *packet)
virtual bool isUpperMessage (cMessage *message) const =0
virtual bool isLowerMessage (cMessage *message) const =0
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void handleStartOperation (LifecycleOperation *operation)=0
virtual void handleStopOperation (LifecycleOperation *operation)=0
virtual void handleCrashOperation (LifecycleOperation *operation)=0
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual bool isInitializeStage (int stage) const=0
virtual bool isModuleStartStage (int stage) const=0
virtual bool isModuleStopStage (int stage) const=0
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Additional Inherited Members
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Member Function Documentation
handleLowerCommand()
void inet::LayeredProtocolBase::handleLowerCommand (cMessage * message) protected virtual
Reimplemented in inet::physicallayer::Radio.
 {
     throw cRuntimeError("Lower command '%s' is not handled.", message->getName());
 }
Referenced by handleLowerMessage(), and inet::physicallayer::PhysicalLayerBase::handleLowerMessage().
handleLowerMessage()
void inet::LayeredProtocolBase::handleLowerMessage (cMessage * message) protected virtual
Reimplemented in inet::physicallayer::PhysicalLayerBase.
 {
     if (!message->isPacket())
         handleLowerCommand(message);
     else {
         emit(packetReceivedFromLowerSignal, message);
         handleLowerPacket(check_and_cast<Packet *>(message));
     }
 }
Referenced by handleMessageWhenUp().
handleLowerPacket()
void inet::LayeredProtocolBase::handleLowerPacket (Packet * packet) protected virtual
Reimplemented in inet::WiseRoute, inet::tcp::Tcp, inet::CsmaCaMac, inet::Flooding, inet::LMac, inet::Ieee802154Mac, inet::ieee80211::Ieee80211Mac, inet::ProbabilisticBroadcast, inet::BMac, inet::Ppp, inet::AckingMac, inet::Ieee8021dRelay, inet::AdaptiveProbabilisticBroadcast, inet::ShortcutMac, inet::MacRelayUnit, inet::Udp, and inet::XMac.
 {
     throw cRuntimeError("Lower packet '%s' is not handled.", packet->getName());
 }
Referenced by handleLowerMessage().
handleMessageWhenUp()
void inet::LayeredProtocolBase::handleMessageWhenUp (cMessage * message) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::EthernetCsmaMac, inet::EthernetMac, inet::ieee80211::Ieee80211Mac, inet::Ppp, inet::physicallayer::ShortcutRadio, and inet::ShortcutMac.
 {
     if (message->isSelfMessage())
         handleSelfMessage(message);
     else if (isUpperMessage(message))
         handleUpperMessage(message);
     else if (isLowerMessage(message))
         handleLowerMessage(message);
     else
         throw cRuntimeError("Message '%s' received on unexpected gate '%s'", message->getName(), message->getArrivalGate()->getFullName());
 }
Referenced by inet::ShortcutMac::handleMessageWhenUp(), inet::physicallayer::ShortcutRadio::handleMessageWhenUp(), inet::Ppp::handleMessageWhenUp(), and inet::ieee80211::Ieee80211Mac::handleMessageWhenUp().
handleSelfMessage()
void inet::LayeredProtocolBase::handleSelfMessage (cMessage * message) protected virtual
Reimplemented in inet::WiseRoute, inet::CsmaCaMac, inet::ProbabilisticBroadcast, inet::EthernetCsmaMac, inet::ieee80211::Ieee80211Mac, inet::EthernetMac, inet::AdaptiveProbabilisticBroadcast, inet::physicallayer::Radio, inet::tcp::Tcp, inet::Ppp, inet::AckingMac, inet::LMac, inet::Ieee802154Mac, inet::XMac, and inet::BMac.
 {
     throw cRuntimeError("Self message '%s' is not handled.", message->getName());
 }
Referenced by handleMessageWhenUp(), and inet::AckingMac::handleSelfMessage().
handleUpperCommand()
void inet::LayeredProtocolBase::handleUpperCommand (cMessage * message) protected virtual
Reimplemented in inet::Udp, inet::ieee80211::Ieee80211Mac, inet::NetworkProtocolBase, inet::tcp::Tcp, inet::physicallayer::Ieee80211Radio, inet::Tun, inet::physicallayer::NarrowbandRadioBase, inet::physicallayer::FlatRadioBase, and inet::physicallayer::Radio.
 {
     throw cRuntimeError("Upper command '%s' is not handled.", message->getName());
 }
Referenced by inet::NetworkProtocolBase::handleUpperCommand(), and handleUpperMessage().
handleUpperMessage()
void inet::LayeredProtocolBase::handleUpperMessage (cMessage * message) protected virtual
Reimplemented in inet::Tun.
 {
     if (!message->isPacket())
         handleUpperCommand(message);
     else {
         emit(packetReceivedFromUpperSignal, message);
         handleUpperPacket(check_and_cast<Packet *>(message));
     }
 }
Referenced by handleMessageWhenUp().
handleUpperPacket()
void inet::LayeredProtocolBase::handleUpperPacket (Packet * packet) protected virtual
Reimplemented in inet::EthernetMac, inet::WiseRoute, inet::physicallayer::Radio, inet::tcp::Tcp, inet::CsmaCaMac, inet::Flooding, inet::LMac, inet::Ieee802154Mac, inet::ieee80211::Ieee80211Mac, inet::BMac, inet::ProbabilisticBroadcast, inet::Ppp, inet::AckingMac, inet::Ieee8021dRelay, inet::physicallayer::ShortcutRadio, inet::Loopback, inet::ShortcutMac, inet::physicallayer::ApskRadio, inet::Tun, inet::EthernetCsmaMac, inet::Udp, and inet::XMac.
 {
     throw cRuntimeError("Upper packet '%s' is not handled.", packet->getName());
 }
Referenced by handleUpperMessage().
isLowerMessage()
virtual bool inet::LayeredProtocolBase::isLowerMessage (cMessage * message) const protected pure virtual
Implemented in inet::MacProtocolBase, inet::NetworkProtocolBase, inet::MacRelayUnitBase, inet::physicallayer::PhysicalLayerBase, and inet::TransportProtocolBase.
Referenced by handleMessageWhenUp().
isUpperMessage()
virtual bool inet::LayeredProtocolBase::isUpperMessage (cMessage * message) const protected pure virtual
Implemented in inet::MacProtocolBase, inet::NetworkProtocolBase, inet::MacRelayUnitBase, inet::physicallayer::PhysicalLayerBase, and inet::TransportProtocolBase.
Referenced by handleMessageWhenUp().
The documentation for this class was generated from the following files:
LayeredProtocolBase.h
LayeredProtocolBase.cc