INET Framework for OMNeT++/OMNEST: inet::sctp::SctpDeleteIPParameter Class Reference
inet::sctp::SctpDeleteIPParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:324 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpDeleteIPParameter (const char *name=nullptr)
SctpDeleteIPParameter (const SctpDeleteIPParameter &other)
virtual ~SctpDeleteIPParameter ()
SctpDeleteIPParameter & operator= (const SctpDeleteIPParameter &other)
virtual SctpDeleteIPParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getRequestCorrelationId () const
virtual void setRequestCorrelationId (uint32_t requestCorrelationId)
virtual const ::inet::L3Address & getAddressParam () const
virtual ::inet::L3Address & getAddressParamForUpdate ()
virtual void setAddressParam (const ::inet::L3Address &addressParam)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpDeleteIPParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t requestCorrelationId = 0
::inet::L3Address addressParam
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpDeleteIPParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:324 by opp_msgtool.
class SctpDeleteIPParameter extends SctpParameter
{
    uint32_t requestCorrelationId; //assigned by the sender to identify each request parameter
    L3Address addressParam;
}
Constructor & Destructor Documentation
SctpDeleteIPParameter() [1/2]
inet::sctp::SctpDeleteIPParameter::SctpDeleteIPParameter (const char * name = nullptr)
SctpDeleteIPParameter() [2/2]
inet::sctp::SctpDeleteIPParameter::SctpDeleteIPParameter (const SctpDeleteIPParameter & other)
~SctpDeleteIPParameter()
virtual inet::sctp::SctpDeleteIPParameter::~SctpDeleteIPParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpDeleteIPParameter::copy (const SctpDeleteIPParameter & other) private
dup()
virtual SctpDeleteIPParameter* inet::sctp::SctpDeleteIPParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpDeleteIPParameter(*this);}
Referenced by inet::sctp::SctpAssociation::processAsconfArrived().
getAddressParam()
virtual const ::inet::L3Address& inet::sctp::SctpDeleteIPParameter::getAddressParam () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::sendAsconf(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressParamForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpDeleteIPParameter::getAddressParamForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpDeleteIPParameter*>(this)->getAddressParam());}
getRequestCorrelationId()
virtual uint32_t inet::sctp::SctpDeleteIPParameter::getRequestCorrelationId () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpDeleteIPParameter& inet::sctp::SctpDeleteIPParameter::operator= (const SctpDeleteIPParameter & other)
operator==()
bool inet::sctp::SctpDeleteIPParameter::operator== (const SctpDeleteIPParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpDeleteIPParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpDeleteIPParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setAddressParam()
virtual void inet::sctp::SctpDeleteIPParameter::setAddressParam (const ::inet::L3Address & addressParam) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendAsconf().
setRequestCorrelationId()
virtual void inet::sctp::SctpDeleteIPParameter::setRequestCorrelationId (uint32_t requestCorrelationId) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendAsconf().
Member Data Documentation
addressParam
::inet::L3Address inet::sctp::SctpDeleteIPParameter::addressParam protected
requestCorrelationId
uint32_t inet::sctp::SctpDeleteIPParameter::requestCorrelationId = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h