INET Framework for OMNeT++/OMNEST: inet::physicallayer::ReceiverBase Class Reference
inet::physicallayer::ReceiverBase Class Reference
#include <ReceiverBase.h>
Public Member Functions
ReceiverBase ()
virtual W getMinInterferencePower () const override
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
virtual W getMinReceptionPower () const override
Returns the minimum reception power below which successful reception is definitely not possible.
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const override
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const override
Returns whether the reception of the provided part is possible or not.
virtual bool computeIsReceptionAttempted (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference) const override
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
virtual const IReceptionDecision * computeReceptionDecision (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
virtual const IReceptionResult * computeReceptionResult (const IListening *listening, const IReception *reception, const IInterference *interference, const ISnir *snir, const std::vector< const IReceptionDecision * > *decisions) const override
Returns the complete result of the reception process for the provided reception.
Public Member Functions inherited from inet::physicallayer::IReceiver
virtual const IListening * createListening (const IRadio *radio, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition) const =0
Returns a description of how the receiver is listening on the medium.
virtual const IListeningDecision * computeListeningDecision (const IListening *listening, const IInterference *interference) const =0
Returns the result of the listening process specifying the reception state of the receiver.
virtual bool computeIsReceptionSuccessful (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const =0
Returns whether the reception of the provided part is actually successful or failed by the receiver.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual int numInitStages () const override
virtual W computeSignalPower (const IListening *listening, const ISnir *snir, const IInterference *interference) const
virtual Packet * computeReceivedPacket (const ISnir *snir, bool isReceptionSuccessful) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
ReceiverBase()
inet::physicallayer::ReceiverBase::ReceiverBase () inline
 {}
Member Function Documentation
computeIsReceptionAttempted()
bool inet::physicallayer::ReceiverBase::computeIsReceptionAttempted (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference) const override virtual
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
For example, it might check that the radio is not already receiving another signal.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::Ieee802154UwbIrReceiver.
 {
     if (!computeIsReceptionPossible(listening, reception, part))
         return false;
     else if (simTime() == reception->getStartTime(part)) {
         // TODO isn't there a better way for this optimization? see also in RadioMedium::isReceptionAttempted
         auto transmission = reception->getReceiver()->getReceptionInProgress();
         return transmission == nullptr || transmission == reception->getTransmission();
     }
     else {
         // determining whether the reception is attempted or not for the future
         auto radio = reception->getReceiver();
         auto radioMedium = radio->getMedium();
         auto interferingReceptions = interference->getInterferingReceptions();
         for (auto interferingReception : *interferingReceptions) {
             auto isPrecedingReception = interferingReception->getStartTime() < reception->getStartTime() ||
                 (interferingReception->getStartTime() == reception->getStartTime() &&
                  interferingReception->getTransmission()->getId() < reception->getTransmission()->getId());
             if (isPrecedingReception) {
                 auto interferingTransmission = interferingReception->getTransmission();
                 if (interferingReception->getStartTime() <= simTime()) {
                     if (radio->getReceptionInProgress() == interferingTransmission)
                         return false;
                 }
                 else if (radioMedium->isReceptionAttempted(radio, interferingTransmission, part))
                     return false;
             }
         }
         return true;
     }
 }
Referenced by computeReceptionDecision().
computeIsReceptionPossible() [1/2]
bool inet::physicallayer::ReceiverBase::computeIsReceptionPossible (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part) const override virtual
Returns whether the reception of the provided part is possible or not.
For example, it might check if the reception power is above sensitivity.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::UnitDiskReceiver, inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee80211UnitDiskReceiver, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
 {
     return true;
 }
computeIsReceptionPossible() [2/2]
bool inet::physicallayer::ReceiverBase::computeIsReceptionPossible (const IListening * listening, const ITransmission * transmission) const override virtual
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
For example, it might check if the carrier frequency and the modulation of the transmission matches how the receiver is listening on the medium.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::Ieee80211UnitDiskReceiver, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
 {
     return true;
 }
Referenced by computeIsReceptionAttempted(), inet::physicallayer::Ieee80211UnitDiskReceiver::computeIsReceptionPossible(), and computeReceptionDecision().
computeReceivedPacket()
Packet * inet::physicallayer::ReceiverBase::computeReceivedPacket (const ISnir * snir, bool isReceptionSuccessful) const protected virtual
Reimplemented in inet::physicallayer::FlatReceiverBase.
 {
     auto transmittedPacket = snir->getReception()->getTransmission()->getPacket();
     auto receivedPacket = transmittedPacket->dup();
     receivedPacket->clearTags();
     receivedPacket->addTag<PacketProtocolTag>()->setProtocol(transmittedPacket->getTag<PacketProtocolTag>()->getProtocol());
     if (!isReceptionSuccessful)
         receivedPacket->setBitError(true);
     return receivedPacket;
 }
Referenced by inet::physicallayer::FlatReceiverBase::computeReceivedPacket(), and computeReceptionResult().
computeReceptionDecision()
const IReceptionDecision * inet::physicallayer::ReceiverBase::computeReceptionDecision (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const override virtual
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::Ieee802154UwbIrReceiver, and inet::physicallayer::NarrowbandReceiverBase.
 {
     auto isReceptionPossible = computeIsReceptionPossible(listening, reception, part);
     auto isReceptionAttempted = isReceptionPossible && computeIsReceptionAttempted(listening, reception, part, interference);
     auto isReceptionSuccessful = isReceptionAttempted && computeIsReceptionSuccessful(listening, reception, part, interference, snir);
     return new ReceptionDecision(reception, part, isReceptionPossible, isReceptionAttempted, isReceptionSuccessful);
 }
Referenced by inet::physicallayer::NarrowbandReceiverBase::computeReceptionDecision().
computeReceptionResult()
const IReceptionResult * inet::physicallayer::ReceiverBase::computeReceptionResult (const IListening * listening, const IReception * reception, const IInterference * interference, const ISnir * snir, const std::vector< const IReceptionDecision * > * decisions) const override virtual
Returns the complete result of the reception process for the provided reception.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::FlatReceiverBase, inet::physicallayer::UnitDiskReceiver, inet::physicallayer::Ieee80211ReceiverBase, and inet::physicallayer::Ieee80211UnitDiskReceiver.
 {
     bool isReceptionSuccessful = true;
     for (auto decision : *decisions)
         isReceptionSuccessful &= decision->isReceptionSuccessful();
     auto packet = computeReceivedPacket(snir, isReceptionSuccessful);
     auto signalPower = computeSignalPower(listening, snir, interference);
     if (!std::isnan(signalPower.get())) {
         auto signalPowerInd = packet->addTagIfAbsent<SignalPowerInd>();
         signalPowerInd->setPower(signalPower);
     }
     auto snirInd = packet->addTagIfAbsent<SnirInd>();
     snirInd->setMinimumSnir(snir->getMin());
     snirInd->setMaximumSnir(snir->getMax());
     snirInd->setAverageSnir(snir->getMean());
     auto signalTimeInd = packet->addTagIfAbsent<SignalTimeInd>();
     signalTimeInd->setStartTime(reception->getStartTime());
     signalTimeInd->setEndTime(reception->getEndTime());
     return new ReceptionResult(reception, decisions, packet);
 }
Referenced by inet::physicallayer::UnitDiskReceiver::computeReceptionResult(), and inet::physicallayer::FlatReceiverBase::computeReceptionResult().
computeSignalPower()
W inet::physicallayer::ReceiverBase::computeSignalPower (const IListening * listening, const ISnir * snir, const IInterference * interference) const protected virtual
 {
     if (!dynamic_cast<const NarrowbandNoiseBase *>(snir->getNoise()))
         return W(0);
     else {
         auto analogModel = snir->getReception()->getTransmission()->getMedium()->getAnalogModel();
         auto signalPlusNoise = check_and_cast<const NarrowbandNoiseBase *>(analogModel->computeNoise(snir->getReception(), snir->getNoise()));
         auto signalPower = signalPlusNoise == nullptr ? W(NaN) : signalPlusNoise->computeMinPower(listening->getStartTime(), listening->getEndTime());
         delete signalPlusNoise;
         return signalPower;
     }
 }
Referenced by computeReceptionResult().
getMinInterferencePower()
virtual W inet::physicallayer::ReceiverBase::getMinInterferencePower () const inline override virtual
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
Returns a value in the range [0, +infinity) or NaN if unspecified.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
 { return W(NaN); }
getMinReceptionPower()
virtual W inet::physicallayer::ReceiverBase::getMinReceptionPower () const inline override virtual
Returns the minimum reception power below which successful reception is definitely not possible.
Returns a value in the range [0, +infinity) or NaN if unspecified.
Implements inet::physicallayer::IReceiver.
Reimplemented in inet::physicallayer::FlatReceiverBase.
 { return W(NaN); }
numInitStages()
virtual int inet::physicallayer::ReceiverBase::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
The documentation for this class was generated from the following files:
ReceiverBase.h
ReceiverBase.cc