INET Framework for OMNeT++/OMNEST: inet::visualizer::ColorSet Class Reference
inet::visualizer::ColorSet Class Reference
#include <ColorSet.h>
Public Member Functions
void parseColors (const char *colorNames)
size_t getSize () const
cFigure::Color getColor (int index) const
Protected Attributes
std::vector< cFigure::Color > colors
Member Function Documentation
getColor()
cFigure::Color inet::visualizer::ColorSet::getColor (int index) const
 {
     return colors[index % colors.size()];
 }
Referenced by inet::visualizer::TransportConnectionCanvasVisualizer::createConnectionEndFigure(), inet::visualizer::TransportConnectionOsgVisualizer::createConnectionEndNode(), inet::visualizer::Ieee80211OsgVisualizer::createIeee80211Visualization(), inet::visualizer::Ieee80211CanvasVisualizer::createIeee80211Visualization(), inet::visualizer::MobilityOsgVisualizer::createMobilityVisualization(), inet::visualizer::MobilityCanvasVisualizer::createMobilityVisualization(), inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), inet::visualizer::PacketDropCanvasVisualizer::createPacketDropVisualization(), inet::visualizer::PathOsgVisualizerBase::createPathVisualization(), inet::visualizer::PathCanvasVisualizerBase::createPathVisualization(), inet::visualizer::TreeCanvasVisualizerBase::createTreeVisualization(), and inet::visualizer::MobilityCanvasVisualizer::extendMovementTrail().
getSize()
size_t inet::visualizer::ColorSet::getSize () const inline
 { return colors.size(); }
Referenced by inet::visualizer::TransportConnectionCanvasVisualizer::addConnectionVisualization(), inet::visualizer::TransportConnectionCanvasVisualizer::createConnectionEndFigure(), inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), inet::visualizer::PacketDropCanvasVisualizer::createPacketDropVisualization(), and inet::visualizer::TransportConnectionCanvasVisualizer::removeConnectionVisualization().
parseColors()
void inet::visualizer::ColorSet::parseColors (const char * colorNames)
 {
     colors.clear();
     if (!strcmp(colorNames, "dark")) {
         for (auto color : cFigure::GOOD_DARK_COLORS)
             colors.push_back(color);
     }
     else if (!strcmp(colorNames, "light")) {
         for (auto color : cFigure::GOOD_LIGHT_COLORS)
             colors.push_back(color);
     }
     else {
         cStringTokenizer tokenizer(colorNames, " ,");
         while (tokenizer.hasMoreTokens()) {
             colors.push_back(cFigure::parseColor(tokenizer.nextToken()));
         }
     }
 }
Referenced by inet::visualizer::Ieee80211VisualizerBase::initialize(), inet::visualizer::TransportConnectionVisualizerBase::initialize(), inet::visualizer::TreeVisualizerBase::initialize(), inet::visualizer::MobilityVisualizerBase::initialize(), inet::visualizer::PathVisualizerBase::initialize(), and inet::visualizer::PacketDropVisualizerBase::initialize().
Member Data Documentation
colors
std::vector<cFigure::Color> inet::visualizer::ColorSet::colors protected
Referenced by getColor(), and parseColors().
The documentation for this class was generated from the following files:
ColorSet.h
ColorSet.cc