INET Framework for OMNeT++/OMNEST: inet::ospfv3::RoutingInfo Class Reference
inet::ospfv3::RoutingInfo Class Reference
#include <Ospfv3Lsa.h>
Public Member Functions
RoutingInfo ()
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo ()
void addNextHop (NextHop nextHop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
void setDistance (unsigned long d)
unsigned long getDistance () const
void setParent (Ospfv3Lsa *p)
Ospfv3Lsa * getParent () const
Private Attributes
std::vector< NextHop > nextHops
unsigned long distance
Ospfv3Lsa * parent
Constructor & Destructor Documentation
RoutingInfo() [1/2]
inet::ospfv3::RoutingInfo::RoutingInfo () inline
 : distance(0), parent(nullptr) {}
RoutingInfo() [2/2]
inet::ospfv3::RoutingInfo::RoutingInfo (const RoutingInfo & routingInfo) inline
 : nextHops(routingInfo.nextHops), distance(routingInfo.distance), parent(routingInfo.parent) {}
~RoutingInfo()
virtual inet::ospfv3::RoutingInfo::~RoutingInfo () inline virtual
 {}
Member Function Documentation
addNextHop()
void inet::ospfv3::RoutingInfo::addNextHop (NextHop nextHop) inline
 { nextHops.push_back(nextHop); }
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
clearNextHops()
void inet::ospfv3::RoutingInfo::clearNextHops () inline
 { nextHops.clear(); }
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
getDistance()
unsigned long inet::ospfv3::RoutingInfo::getDistance () const inline
 { return distance; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), and inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
getNextHop()
NextHop inet::ospfv3::RoutingInfo::getNextHop (unsigned int index) const inline
 { return nextHops[index]; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateNextHops(), and inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
getNextHopCount()
unsigned int inet::ospfv3::RoutingInfo::getNextHopCount () const inline
 { return nextHops.size(); }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateNextHops(), and inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
getParent()
Ospfv3Lsa* inet::ospfv3::RoutingInfo::getParent () const inline
 { return parent; }
Referenced by inet::ospfv3::Ospfv3Area::calculateNextHops().
setDistance()
void inet::ospfv3::RoutingInfo::setDistance (unsigned long d) inline
 { distance = d; }
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
setParent()
void inet::ospfv3::RoutingInfo::setParent (Ospfv3Lsa * p) inline
 { parent = p; }
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
Member Data Documentation
distance
unsigned long inet::ospfv3::RoutingInfo::distance private
nextHops
std::vector<NextHop> inet::ospfv3::RoutingInfo::nextHops private
parent
Ospfv3Lsa* inet::ospfv3::RoutingInfo::parent private
The documentation for this class was generated from the following file:
Ospfv3Lsa.h