INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211Radio Class Reference
inet::physicallayer::Ieee80211Radio Class Reference
#include <Ieee80211Radio.h>
Public Member Functions
Ieee80211Radio ()
virtual void setModeSet (const Ieee80211ModeSet *modeSet)
virtual void setMode (const IIeee80211Mode *mode)
virtual void setBand (const IIeee80211Band *band)
virtual void setChannel (const Ieee80211Channel *channel)
virtual void setChannelNumber (int newChannelNumber)
Public Member Functions inherited from inet::physicallayer::FlatRadioBase
FlatRadioBase ()
virtual void setPower (W newPower)
virtual void setBitrate (bps newBitrate)
Public Member Functions inherited from inet::physicallayer::NarrowbandRadioBase
NarrowbandRadioBase ()
virtual void setModulation (const IModulation *newModulation)
virtual void setCenterFrequency (Hz newCenterFrequency)
virtual void setBandwidth (Hz newBandwidth)
Public Member Functions inherited from inet::physicallayer::Radio
Radio ()
virtual ~Radio ()
virtual int getId () const override
Returns an identifier for this radio which is globally unique for the whole lifetime of the simulation among all radios.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IAntenna * getAntenna () const override
Returns the antenna used by the transceiver of this radio.
virtual const ITransmitter * getTransmitter () const override
Returns the transmitter part of this radio.
virtual const IReceiver * getReceiver () const override
Returns the receiver part of this radio.
virtual const IRadioMedium * getMedium () const override
Returns the radio medium where this radio is transmitting and receiving radio signals.
virtual const cGate * getRadioGate () const override
Returns the gate of the radio that receives incoming signals.
virtual RadioMode getRadioMode () const override
Returns the current radio mode, This is the same mode as the one emitted with the last radioModeChangedSignal.
virtual void setRadioMode (RadioMode newRadioMode) override
Changes the current radio mode.
virtual ReceptionState getReceptionState () const override
Returns the current radio reception state.
virtual TransmissionState getTransmissionState () const override
Returns the current radio transmission state.
virtual const ITransmission * getTransmissionInProgress () const override
Returns the ongoing transmission that the transmitter is currently transmitting or nullptr.
virtual const ITransmission * getReceptionInProgress () const override
Returns the ongoing reception that the receiver is currently receiving or nullptr.
virtual IRadioSignal::SignalPart getTransmittedSignalPart () const override
Returns the signal part of the ongoing transmission that the transmitter is currently transmitting or -1 if no transmission is in progress.
virtual IRadioSignal::SignalPart getReceivedSignalPart () const override
Returns the signal part of the ongoing reception that the receiver is currently receiving or -1 if no reception is in progress.
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::IPhysicalLayer
virtual ~IPhysicalLayer ()
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Member Functions
static const Ptr< const Ieee80211PhyHeader > popIeee80211PhyHeaderAtFront (Packet *packet, b length=b(-1), int flags=0)
static const Ptr< const Ieee80211PhyHeader > peekIeee80211PhyHeaderAtFront (const Packet *packet, b length=b(-1), int flags=0)
Static Public Member Functions inherited from inet::physicallayer::IRadio
static const char * getRadioModeName (RadioMode radioMode)
Returns the name of the provided radio mode.
static const char * getRadioReceptionStateName (ReceptionState receptionState)
Returns the name of the provided radio reception state.
static const char * getRadioTransmissionStateName (TransmissionState transmissionState)
Returns the name of the provided radio transmission state.
Static Public Attributes
static simsignal_t radioChannelChangedSignal = cComponent::registerSignal("radioChannelChanged")
This signal is emitted every time the radio channel changes.
Static Public Attributes inherited from inet::physicallayer::IRadio
static simsignal_t radioModeChangedSignal = cComponent::registerSignal("radioModeChanged")
This signal is emitted when the radio mode of the radio is changed.
static simsignal_t listeningChangedSignal = cComponent::registerSignal("listeningChanged")
This signal is emitted when the radio listening of the radio is changed.
static simsignal_t receptionStateChangedSignal = cComponent::registerSignal("receptionStateChanged")
This signal is emitted when the radio reception state of the radio is changed.
static simsignal_t transmissionStateChangedSignal = cComponent::registerSignal("transmissionStateChanged")
This signal is emitted when the radio transmission state of the radio is changed.
static simsignal_t receivedSignalPartChangedSignal = cComponent::registerSignal("receivedSignalPartChanged")
This signal is emitted when the received part is changed by the radio.
static simsignal_t transmittedSignalPartChangedSignal = cComponent::registerSignal("transmittedSignalPartChanged")
This signal is emitted when the transmitted part is changed by the radio.
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleUpperCommand (cMessage *message) override
virtual void insertCrc (const Ptr< Ieee80211PhyHeader > &phyHeader) const
virtual bool verifyCrc (const Ptr< const Ieee80211PhyHeader > &phyHeader) const
virtual void encapsulate (Packet *packet) const override
virtual void decapsulate (Packet *packet) const override
Protected Member Functions inherited from inet::physicallayer::Radio
virtual void initializeRadioMode ()
virtual void handleMessageWhenDown (cMessage *message) override
virtual void handleSelfMessage (cMessage *message) override
virtual void handleSwitchTimer (cMessage *message)
virtual void handleTransmissionTimer (cMessage *message)
virtual void handleReceptionTimer (cMessage *message)
virtual void handleLowerCommand (cMessage *command) override
virtual void handleUpperPacket (Packet *packet) override
virtual void handleSignal (WirelessSignal *signal) override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual void startTransmission (Packet *macFrame, IRadioSignal::SignalPart part)
virtual void continueTransmission ()
virtual void endTransmission ()
virtual void abortTransmission ()
virtual WirelessSignal * createSignal (Packet *packet) const
virtual void startReception (cMessage *timer, IRadioSignal::SignalPart part)
virtual void continueReception (cMessage *timer)
virtual void endReception (cMessage *timer)
virtual void abortReception (cMessage *timer)
virtual void captureReception (cMessage *timer)
virtual void sendUp (Packet *macFrame)
virtual cMessage * createReceptionTimer (WirelessSignal *signal) const
virtual bool isReceptionTimer (const cMessage *message) const
virtual bool isReceiverMode (IRadio::RadioMode radioMode) const
virtual bool isTransmitterMode (IRadio::RadioMode radioMode) const
virtual bool isListeningPossible () const
virtual void updateTransceiverState ()
virtual void updateTransceiverPart ()
Protected Member Functions inherited from inet::physicallayer::PhysicalLayerBase
virtual void handleLowerMessage (cMessage *message) override
virtual void sendUp (cMessage *message)
virtual bool isUpperMessage (cMessage *message) const override
virtual bool isLowerMessage (cMessage *message) const override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
Protected Member Functions inherited from inet::LayeredProtocolBase
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleUpperMessage (cMessage *message)
virtual void handleLowerPacket (Packet *packet)
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
CrcMode crcMode = CRC_MODE_UNDEFINED
Protected Attributes inherited from inet::physicallayer::Radio
const int id = nextId++
An identifier which is globally unique for the whole lifetime of the simulation among all radios.
const IAntenna * antenna = nullptr
The radio antenna model is never nullptr.
const ITransmitter * transmitter = nullptr
The transmitter model is never nullptr.
const IReceiver * receiver = nullptr
The receiver model is never nullptr.
ModuleRefByPar< IRadioMedium > medium
The radio medium model is never nullptr.
int mediumModuleId = -1
The module id of the medim model.
simtime_t switchingTimes [RADIO_MODE_SWITCHING][RADIO_MODE_SWITCHING]
Simulation time required to switch from one radio mode to another.
bool sendRawBytes = false
When true packets are serialized into a sequence of bytes before sending out.
bool separateTransmissionParts = false
Determines whether the transmission of the preamble, header and data part are simulated separately or not.
bool separateReceptionParts = false
Determines whether the reception of the preamble, header and data part are simulated separately or not.
cGate * upperLayerOut = nullptr
Gates.
cGate * upperLayerIn = nullptr
cGate * radioIn = nullptr
RadioMode radioMode = RADIO_MODE_OFF
State.
RadioMode nextRadioMode = RADIO_MODE_OFF
The radio is switching to this radio radio mode if a switch is in progress, otherwise this is the same as the current radio mode.
RadioMode previousRadioMode = RADIO_MODE_OFF
The radio is switching from this radio mode to another if a switch is in progress, otherwise this is the same as the current radio mode.
ReceptionState receptionState = RECEPTION_STATE_UNDEFINED
The current reception state.
TransmissionState transmissionState = TRANSMISSION_STATE_UNDEFINED
The current transmission state.
IRadioSignal::SignalPart receivedSignalPart = IRadioSignal::SIGNAL_PART_NONE
The current received signal part.
IRadioSignal::SignalPart transmittedSignalPart = IRadioSignal::SIGNAL_PART_NONE
The current transmitted signal part.
cMessage * transmissionTimer = nullptr
The timer that is scheduled to the end of the current transmission.
cMessage * receptionTimer = nullptr
The timer that is scheduled to the end of the current reception.
cMessage * switchTimer = nullptr
The timer that is scheduled to the end of the radio mode switch.
Protected Attributes inherited from inet::physicallayer::PhysicalLayerBase
int upperLayerInGateId = -1
int upperLayerOutGateId = -1
int radioInGateId = -1
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Additional Inherited Members
Public Types inherited from inet::physicallayer::IRadio
enum RadioMode {
RADIO_MODE_OFF, RADIO_MODE_SLEEP, RADIO_MODE_RECEIVER, RADIO_MODE_TRANSMITTER,
RADIO_MODE_TRANSCEIVER, RADIO_MODE_SWITCHING
}
This enumeration specifies the requested operational mode of the radio.
enum ReceptionState { RECEPTION_STATE_UNDEFINED, RECEPTION_STATE_IDLE, RECEPTION_STATE_BUSY, RECEPTION_STATE_RECEIVING }
This enumeration specifies the reception state of the radio.
enum TransmissionState { TRANSMISSION_STATE_UNDEFINED, TRANSMISSION_STATE_IDLE, TRANSMISSION_STATE_TRANSMITTING }
This enumeration specifies the transmission state of the radio.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Static Protected Attributes inherited from inet::physicallayer::IRadio
static int nextId = 0
static cEnum * radioModeEnum = nullptr
The enumeration registered for radio mode.
static cEnum * receptionStateEnum = nullptr
The enumeration registered for radio reception state.
static cEnum * transmissionStateEnum = nullptr
The enumeration registered for radio transmission state.
Constructor & Destructor Documentation
Ieee80211Radio()
inet::physicallayer::Ieee80211Radio::Ieee80211Radio ()
                                :
     FlatRadioBase()
 {
 }
Member Function Documentation
decapsulate()
void inet::physicallayer::Ieee80211Radio::decapsulate (Packet * packet) const override protected virtual
Reimplemented from inet::physicallayer::Radio.
 {
     auto mode = packet->getTag<Ieee80211ModeInd>()->getMode();
     const auto& phyHeader = popIeee80211PhyHeaderAtFront(packet, b(-1), Chunk::PF_ALLOW_INCORRECT | Chunk::PF_ALLOW_INCOMPLETE | Chunk::PF_ALLOW_IMPROPERLY_REPRESENTED);
     if (phyHeader->isIncorrect() || phyHeader->isIncomplete() || phyHeader->isImproperlyRepresented() || !verifyCrc(phyHeader))
         packet->setBitError(true);
     auto tailLength = dynamic_cast<const Ieee80211OfdmMode *>(mode) ? b(6) : b(0);
     auto paddingLength = mode->getDataMode()->getPaddingLength(B(phyHeader->getLengthField()));
     if (tailLength + paddingLength != b(0))
         packet->popAtBack(tailLength + paddingLength, Chunk::PF_ALLOW_INCORRECT);
     packet->getTagForUpdate<PacketProtocolTag>()->setProtocol(&Protocol::ieee80211Mac);
 }
encapsulate()
void inet::physicallayer::Ieee80211Radio::encapsulate (Packet * packet) const override protected virtual
Reimplemented from inet::physicallayer::Radio.
 {
     auto ieee80211Transmitter = check_and_cast<const Ieee80211TransmitterBase *>(transmitter);
     auto mode = ieee80211Transmitter->computeTransmissionMode(packet);
     auto phyHeader = mode->getHeaderMode()->createHeader();
     phyHeader->setChunkLength(b(mode->getHeaderMode()->getLength()));
     phyHeader->setLengthField(B(packet->getTotalLength()));
     insertCrc(phyHeader);
     packet->insertAtFront(phyHeader);
     auto tailLength = dynamic_cast<const Ieee80211OfdmMode *>(mode) ? b(6) : b(0);
     auto paddingLength = mode->getDataMode()->getPaddingLength(B(phyHeader->getLengthField()));
     if (tailLength + paddingLength != b(0)) {
         const auto& phyTrailer = makeShared<BitCountChunk>(tailLength + paddingLength);
         packet->insertAtBack(phyTrailer);
     }
     const Protocol *protocol = nullptr;
     if (dynamic_cast<Ieee80211FhssPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211FhssPhy;
     else if (dynamic_cast<Ieee80211IrPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211IrPhy;
     else if (dynamic_cast<Ieee80211DsssPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211DsssPhy;
     else if (dynamic_cast<Ieee80211HrDsssPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211HrDsssPhy;
     else if (dynamic_cast<Ieee80211OfdmPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211OfdmPhy;
     else if (dynamic_cast<Ieee80211ErpOfdmPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211ErpOfdmPhy;
     else if (dynamic_cast<Ieee80211HtPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211HtPhy;
     else if (dynamic_cast<Ieee80211VhtPhyHeader *>(phyHeader.get()))
         protocol = &Protocol::ieee80211VhtPhy;
     else
         throw cRuntimeError("Invalid IEEE 802.11 PHY header type.");
     packet->getTagForUpdate<PacketProtocolTag>()->setProtocol(protocol);
 }
handleUpperCommand()
void inet::physicallayer::Ieee80211Radio::handleUpperCommand (cMessage * message) override protected virtual
Reimplemented from inet::physicallayer::FlatRadioBase.
 {
     if (message->getKind() == RADIO_C_CONFIGURE) {
         Ieee80211ConfigureRadioCommand *configureCommand = dynamic_cast<Ieee80211ConfigureRadioCommand *>(message->getControlInfo());
         if (configureCommand != nullptr) {
             const char *opMode = configureCommand->getOpMode();
             if (*opMode)
                 setModeSet(Ieee80211ModeSet::getModeSet(opMode));
             const Ieee80211ModeSet *modeSet = configureCommand->getModeSet();
             if (modeSet != nullptr)
                 setModeSet(modeSet);
             const IIeee80211Mode *mode = configureCommand->getMode();
             if (mode != nullptr)
                 setMode(mode);
             const IIeee80211Band *band = configureCommand->getBand();
             if (band != nullptr)
                 setBand(band);
             const Ieee80211Channel *channel = configureCommand->getChannel();
             if (channel != nullptr)
                 setChannel(channel);
             int newChannelNumber = configureCommand->getChannelNumber();
             if (newChannelNumber != -1)
                 setChannelNumber(newChannelNumber);
         }
     }
     FlatRadioBase::handleUpperCommand(message);
 }
initialize()
void inet::physicallayer::Ieee80211Radio::initialize (int stage) override protected virtual
Reimplemented from inet::physicallayer::Radio.
 {
     FlatRadioBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         const char *crcModeString = par("crcMode");
         crcMode = parseCrcMode(crcModeString, true);
     }
     if (stage == INITSTAGE_PHYSICAL_LAYER) {
         int channelNumber = par("channelNumber");
         if (channelNumber != -1)
             setChannelNumber(channelNumber);
     }
 }
insertCrc()
void inet::physicallayer::Ieee80211Radio::insertCrc (const Ptr< Ieee80211PhyHeader > & phyHeader) const protected virtual
 {
     if (auto header = dynamic_cast<Ieee80211FhssPhyHeader *>(phyHeader.get())) {
         header->setCrcMode(crcMode);
         switch (crcMode) {
             case CRC_COMPUTED:
                 header->setCrc(0); // TODO calculate CRC
                 break;
             case CRC_DECLARED_CORRECT:
                 header->setCrc(0xC00D);
                 break;
             case CRC_DECLARED_INCORRECT:
                 header->setCrc(0xBAAD);
                 break;
             default:
                 throw cRuntimeError("Invalid CRC mode: %i", (int)crcMode);
         }
     }
     else if (auto header = dynamic_cast<Ieee80211IrPhyHeader *>(phyHeader.get())) {
         header->setCrcMode(crcMode);
         switch (crcMode) {
             case CRC_COMPUTED:
                 header->setCrc(0); // TODO calculate CRC
                 break;
             case CRC_DECLARED_CORRECT:
                 header->setCrc(0xC00D);
                 break;
             case CRC_DECLARED_INCORRECT:
                 header->setCrc(0xBAAD);
                 break;
             default:
                 throw cRuntimeError("Invalid CRC mode: %i", (int)crcMode);
         }
     }
     else if (auto header = dynamic_cast<Ieee80211DsssPhyHeader *>(phyHeader.get())) {
         header->setCrcMode(crcMode);
         switch (crcMode) {
             case CRC_COMPUTED:
                 header->setCrc(0); // TODO calculate CRC
                 break;
             case CRC_DECLARED_CORRECT:
                 header->setCrc(0xC00D);
                 break;
             case CRC_DECLARED_INCORRECT:
                 header->setCrc(0xBAAD);
                 break;
             default:
                 throw cRuntimeError("Invalid CRC mode: %i", (int)crcMode);
         }
     }
 }
Referenced by encapsulate().
peekIeee80211PhyHeaderAtFront()
const Ptr< const Ieee80211PhyHeader > inet::physicallayer::Ieee80211Radio::peekIeee80211PhyHeaderAtFront (const Packet * packet, b length = b(-1), int flags = 0) static
 {
     int id = packet->getTag<PacketProtocolTag>()->getProtocol()->getId();
     if (id == Protocol::ieee80211FhssPhy.getId())
         return packet->peekAtFront<Ieee80211FhssPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211IrPhy.getId())
         return packet->peekAtFront<Ieee80211IrPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211DsssPhy.getId())
         return packet->peekAtFront<Ieee80211DsssPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211HrDsssPhy.getId())
         return packet->peekAtFront<Ieee80211HrDsssPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211OfdmPhy.getId())
         return packet->peekAtFront<Ieee80211OfdmPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211ErpOfdmPhy.getId())
         return packet->peekAtFront<Ieee80211ErpOfdmPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211HtPhy.getId())
         return packet->peekAtFront<Ieee80211HtPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211VhtPhy.getId())
         return packet->peekAtFront<Ieee80211VhtPhyHeader>(length, flags);
     else
         throw cRuntimeError("Invalid IEEE 802.11 PHY protocol.");
 }
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), and inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission().
popIeee80211PhyHeaderAtFront()
const Ptr< const Ieee80211PhyHeader > inet::physicallayer::Ieee80211Radio::popIeee80211PhyHeaderAtFront (Packet * packet, b length = b(-1), int flags = 0) static
 {
     int id = packet->getTag<PacketProtocolTag>()->getProtocol()->getId();
     if (id == Protocol::ieee80211FhssPhy.getId())
         return packet->popAtFront<Ieee80211FhssPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211IrPhy.getId())
         return packet->popAtFront<Ieee80211IrPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211DsssPhy.getId())
         return packet->popAtFront<Ieee80211DsssPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211HrDsssPhy.getId())
         return packet->popAtFront<Ieee80211HrDsssPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211OfdmPhy.getId())
         return packet->popAtFront<Ieee80211OfdmPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211ErpOfdmPhy.getId())
         return packet->popAtFront<Ieee80211ErpOfdmPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211HtPhy.getId())
         return packet->popAtFront<Ieee80211HtPhyHeader>(length, flags);
     else if (id == Protocol::ieee80211VhtPhy.getId())
         return packet->popAtFront<Ieee80211VhtPhyHeader>(length, flags);
     else
         throw cRuntimeError("Invalid IEEE 802.11 PHY protocol.");
 }
Referenced by decapsulate(), and inet::Ieee80211PhyProtocolDissector::dissect().
setBand()
void inet::physicallayer::Ieee80211Radio::setBand (const IIeee80211Band * band) virtual
 {
     Ieee80211TransmitterBase *ieee80211Transmitter = const_cast<Ieee80211TransmitterBase *>(check_and_cast<const Ieee80211TransmitterBase *>(transmitter));
     Ieee80211ReceiverBase *ieee80211Receiver = const_cast<Ieee80211ReceiverBase *>(check_and_cast<const Ieee80211ReceiverBase *>(receiver));
     ieee80211Transmitter->setBand(band);
     ieee80211Receiver->setBand(band);
     EV << "Changing radio band to " << band << endl;
     receptionTimer = nullptr;
     emit(listeningChangedSignal, 0);
 }
Referenced by handleUpperCommand().
setChannel()
void inet::physicallayer::Ieee80211Radio::setChannel (const Ieee80211Channel * channel) virtual
 {
     Ieee80211TransmitterBase *ieee80211Transmitter = const_cast<Ieee80211TransmitterBase *>(check_and_cast<const Ieee80211TransmitterBase *>(transmitter));
     Ieee80211ReceiverBase *ieee80211Receiver = const_cast<Ieee80211ReceiverBase *>(check_and_cast<const Ieee80211ReceiverBase *>(receiver));
     ieee80211Transmitter->setChannel(channel);
     ieee80211Receiver->setChannel(channel);
     EV << "Changing radio channel to " << channel->getChannelNumber() << endl;
     receptionTimer = nullptr;
     emit(radioChannelChangedSignal, channel->getChannelNumber());
     emit(listeningChangedSignal, 0);
 }
Referenced by handleUpperCommand().
setChannelNumber()
void inet::physicallayer::Ieee80211Radio::setChannelNumber (int newChannelNumber) virtual
 {
     Ieee80211TransmitterBase *ieee80211Transmitter = const_cast<Ieee80211TransmitterBase *>(check_and_cast<const Ieee80211TransmitterBase *>(transmitter));
     Ieee80211ReceiverBase *ieee80211Receiver = const_cast<Ieee80211ReceiverBase *>(check_and_cast<const Ieee80211ReceiverBase *>(receiver));
     ieee80211Transmitter->setChannelNumber(newChannelNumber);
     ieee80211Receiver->setChannelNumber(newChannelNumber);
     EV << "Changing radio channel to " << newChannelNumber << ".\n";
     receptionTimer = nullptr;
     emit(radioChannelChangedSignal, newChannelNumber);
     emit(listeningChangedSignal, 0);
 }
Referenced by handleUpperCommand(), and initialize().
setMode()
void inet::physicallayer::Ieee80211Radio::setMode (const IIeee80211Mode * mode) virtual
 {
     Ieee80211TransmitterBase *ieee80211Transmitter = const_cast<Ieee80211TransmitterBase *>(check_and_cast<const Ieee80211TransmitterBase *>(transmitter));
     ieee80211Transmitter->setMode(mode);
     EV << "Changing radio mode to " << mode << endl;
     receptionTimer = nullptr;
     emit(listeningChangedSignal, 0);
 }
Referenced by handleUpperCommand().
setModeSet()
void inet::physicallayer::Ieee80211Radio::setModeSet (const Ieee80211ModeSet * modeSet) virtual
 {
     Ieee80211TransmitterBase *ieee80211Transmitter = const_cast<Ieee80211TransmitterBase *>(check_and_cast<const Ieee80211TransmitterBase *>(transmitter));
     Ieee80211ReceiverBase *ieee80211Receiver = const_cast<Ieee80211ReceiverBase *>(check_and_cast<const Ieee80211ReceiverBase *>(receiver));
     ieee80211Transmitter->setModeSet(modeSet);
     ieee80211Receiver->setModeSet(modeSet);
     EV << "Changing radio mode set to " << modeSet << endl;
     receptionTimer = nullptr;
     emit(listeningChangedSignal, 0);
 }
Referenced by handleUpperCommand().
verifyCrc()
bool inet::physicallayer::Ieee80211Radio::verifyCrc (const Ptr< const Ieee80211PhyHeader > & phyHeader) const protected virtual
 {
     if (auto header = dynamicPtrCast<const Ieee80211FhssPhyHeader>(phyHeader)) {
         switch (header->getCrcMode()) {
             case CRC_COMPUTED:
                 return true; // TODO calculate and check CRC
             case CRC_DECLARED_CORRECT:
                 return true;
             case CRC_DECLARED_INCORRECT:
                 return false;
             default:
                 throw cRuntimeError("Invalid CRC mode: %i", (int)crcMode);
         }
     }
     else if (auto header = dynamicPtrCast<const Ieee80211IrPhyHeader>(phyHeader)) {
         switch (header->getCrcMode()) {
             case CRC_COMPUTED:
                 return true; // TODO calculate and check CRC
             case CRC_DECLARED_CORRECT:
                 return true;
             case CRC_DECLARED_INCORRECT:
                 return false;
             default:
                 throw cRuntimeError("Invalid CRC mode: %i", (int)crcMode);
         }
     }
     else if (auto header = dynamicPtrCast<const Ieee80211DsssPhyHeader>(phyHeader)) {
         switch (header->getCrcMode()) {
             case CRC_COMPUTED:
                 return true; // TODO calculate and check CRC
             case CRC_DECLARED_CORRECT:
                 return true;
             case CRC_DECLARED_INCORRECT:
                 return false;
             default:
                 throw cRuntimeError("Invalid CRC mode: %i", (int)crcMode);
         }
     }
     else
         return true;
 }
Referenced by decapsulate().
Member Data Documentation
crcMode
CrcMode inet::physicallayer::Ieee80211Radio::crcMode = CRC_MODE_UNDEFINED protected
Referenced by initialize(), insertCrc(), and verifyCrc().
radioChannelChangedSignal
simsignal_t inet::physicallayer::Ieee80211Radio::radioChannelChangedSignal = cComponent::registerSignal("radioChannelChanged") static
This signal is emitted every time the radio channel changes.
The signal value is the new radio channel.
Referenced by inet::ieee80211::Ieee80211MgmtAp::initialize(), inet::ieee80211::Ieee80211MgmtAp::receiveSignal(), setChannel(), and setChannelNumber().
The documentation for this class was generated from the following files:
Ieee80211Radio.h
Ieee80211Radio.cc