INET Framework for OMNeT++/OMNEST: inet::queueing::PacketBuffer Class Reference
inet::queueing::PacketBuffer Class Reference
#include <PacketBuffer.h>
Public Member Functions
virtual int getMaxNumPackets () const override
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const override
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const override
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const override
Returns the total length of all packets in the collection in the range [0, inf).
virtual Packet * getPacket (int index) const override
Returns the packet at the given index.
virtual bool isEmpty () const override
Returns true if there are no packets available in the collection.
virtual void addPacket (Packet *packet) override
Adds the packet to the buffer.
virtual void removePacket (Packet *packet) override
Removes the packet from the buffer.
virtual void removeAllPackets () override
Removes all packets from the collection.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPacketBuffer
virtual ~IPacketBuffer ()
Protected Member Functions
virtual void initialize (int stage) override
virtual IPacketDropperFunction * createDropperFunction (const char *dropperClass) const
virtual bool isOverloaded () const
Protected Member Functions inherited from inet::queueing::PacketBufferBase
virtual void emit (simsignal_t signal, cObject *object, cObject *details=nullptr) override
virtual const char * resolveDirective (char directive) const override
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
int packetCapacity = -1
b dataCapacity = b(-1)
std::vector< Packet * > packets
IPacketDropperFunction * packetDropperFunction = nullptr
Protected Attributes inherited from inet::queueing::PacketBufferBase
int numAddedPackets = -1
int numRemovedPackets = -1
int numDroppedPackets = -1
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
addPacket()
void inet::queueing::PacketBuffer::addPacket (Packet * packet) override virtual
Adds the packet to the buffer.
Implements inet::queueing::IPacketBuffer.
 {
     Enter_Method("addPacket");
     EV_INFO << "Adding packet" << EV_FIELD(packet) << EV_ENDL;
     emit(packetAddedSignal, packet);
     packets.push_back(packet);
     if (isOverloaded()) {
         if (packetDropperFunction != nullptr) {
             while (!isEmpty() && isOverloaded()) {
                 auto packet = packetDropperFunction->selectPacket(this);
                 EV_INFO << "Dropping packet" << EV_FIELD(packet) << EV_ENDL;
                 packets.erase(find(packets, packet));
                 auto queue = dynamic_cast<cPacketQueue *>(packet->getOwner());
                 if (queue != nullptr) {
                     ICallback *callback = dynamic_cast<ICallback *>(queue->getOwner());
                     if (callback != nullptr)
                         callback->handlePacketRemoved(packet);
                 }
                 // TODO maybe the buffer should take ownership and queues should be aware of it
                 take(packet);
                 dropPacket(packet, QUEUE_OVERFLOW);
             }
         }
         else
             throw cRuntimeError("Buffer is overloaded but packet dropper function is not specified");
     }
     updateDisplayString();
 }
createDropperFunction()
IPacketDropperFunction * inet::queueing::PacketBuffer::createDropperFunction (const char * dropperClass) const protected virtual
 {
     if (strlen(dropperClass) == 0)
         return nullptr;
     else
         return check_and_cast<IPacketDropperFunction *>(createOne(dropperClass));
 }
Referenced by initialize().
getMaxNumPackets()
virtual int inet::queueing::PacketBuffer::getMaxNumPackets () const inline override virtual
Returns maximum allowed number of packets in the collection.
The value -1 means no such limit.
Implements inet::queueing::IPacketCollection.
 { return packetCapacity; }
getMaxTotalLength()
virtual b inet::queueing::PacketBuffer::getMaxTotalLength () const inline override virtual
Returns maximum allowed total length of all packets in the collection.
The value -1 means no such limit.
Implements inet::queueing::IPacketCollection.
 { return dataCapacity; }
getNumPackets()
virtual int inet::queueing::PacketBuffer::getNumPackets () const inline override virtual
Returns the number of available packets in the collection in the range [0, inf).
Implements inet::queueing::IPacketCollection.
 { return packets.size(); }
Referenced by isOverloaded().
getPacket()
Packet * inet::queueing::PacketBuffer::getPacket (int index) const override virtual
Returns the packet at the given index.
Throws error when the index is out of range.
Implements inet::queueing::IPacketCollection.
 {
     if (index < 0 || (size_t)index >= packets.size())
         throw cRuntimeError("index %i out of range", index);
     return packets[index];
 }
Referenced by removeAllPackets().
getTotalLength()
b inet::queueing::PacketBuffer::getTotalLength () const override virtual
Returns the total length of all packets in the collection in the range [0, inf).
Implements inet::queueing::IPacketCollection.
 {
     b totalLength = b(0);
     for (auto packet : packets)
         totalLength += packet->getTotalLength();
     return totalLength;
 }
Referenced by isOverloaded().
initialize()
void inet::queueing::PacketBuffer::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketBufferBase.
 {
     PacketBufferBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         displayStringTextFormat = par("displayStringTextFormat");
         packetCapacity = par("packetCapacity");
         dataCapacity = b(par("dataCapacity"));
         packetDropperFunction = createDropperFunction(par("dropperClass"));
     }
     else if (stage == INITSTAGE_LAST)
         updateDisplayString();
 }
isEmpty()
virtual bool inet::queueing::PacketBuffer::isEmpty () const inline override virtual
Returns true if there are no packets available in the collection.
Implements inet::queueing::IPacketCollection.
 { return packets.size() == 0; }
Referenced by addPacket(), and removeAllPackets().
isOverloaded()
bool inet::queueing::PacketBuffer::isOverloaded () const protected virtual
 {
     return (packetCapacity != -1 && getNumPackets() > packetCapacity) ||
            (dataCapacity != b(-1) && getTotalLength() > dataCapacity);
 }
Referenced by addPacket().
removeAllPackets()
void inet::queueing::PacketBuffer::removeAllPackets () override virtual
Removes all packets from the collection.
Implements inet::queueing::IPacketCollection.
 {
     Enter_Method("removeAllPacket");
     EV_INFO << "Removing all packets" << EV_ENDL;
     while (!isEmpty()) {
         auto packet = getPacket(0);
         emit(packetRemovedSignal, packet);
         packets.erase(packets.begin());
         auto queue = dynamic_cast<cPacketQueue *>(packet->getOwner());
         if (queue != nullptr) {
             ICallback *callback = dynamic_cast<ICallback *>(queue->getOwner());
             if (callback != nullptr)
                 callback->handlePacketRemoved(packet);
         }
     }
     updateDisplayString();
 }
removePacket()
void inet::queueing::PacketBuffer::removePacket (Packet * packet) override virtual
Removes the packet from the buffer.
Implements inet::queueing::IPacketBuffer.
 {
     Enter_Method("removePacket");
     EV_INFO << "Removing packet" << EV_FIELD(packet) << EV_ENDL;
     emit(packetRemovedSignal, packet);
     packets.erase(find(packets, packet));
     updateDisplayString();
     auto queue = dynamic_cast<cPacketQueue *>(packet->getOwner());
     if (queue != nullptr) {
         ICallback *callback = dynamic_cast<ICallback *>(queue->getOwner());
         if (callback != nullptr)
             callback->handlePacketRemoved(packet);
     }
 }
supportsPacketPulling()
virtual bool inet::queueing::PacketBuffer::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return false; }
supportsPacketPushing()
virtual bool inet::queueing::PacketBuffer::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return false; }
Member Data Documentation
dataCapacity
b inet::queueing::PacketBuffer::dataCapacity = b(-1) protected
Referenced by initialize(), and isOverloaded().
packetCapacity
int inet::queueing::PacketBuffer::packetCapacity = -1 protected
Referenced by initialize(), and isOverloaded().
packetDropperFunction
IPacketDropperFunction* inet::queueing::PacketBuffer::packetDropperFunction = nullptr protected
Referenced by addPacket(), and initialize().
packets
std::vector<Packet *> inet::queueing::PacketBuffer::packets protected
Referenced by addPacket(), getPacket(), getTotalLength(), removeAllPackets(), and removePacket().
The documentation for this class was generated from the following files:
PacketBuffer.h
PacketBuffer.cc