INET Framework for OMNeT++/OMNEST: inet::JoinPruneGroup Class Reference
inet::JoinPruneGroup Class Reference
Class generated from inet/routing/pim/PimPacket.msg:151 by opp_msgtool.
#include <PimPacket_m.h>
Public Member Functions
JoinPruneGroup ()
JoinPruneGroup (const JoinPruneGroup &other)
virtual ~JoinPruneGroup ()
JoinPruneGroup & operator= (const JoinPruneGroup &other)
virtual JoinPruneGroup * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const EncodedGroupAddress & getGroupAddress () const
virtual EncodedGroupAddress & getGroupAddressForUpdate ()
virtual void setGroupAddress (const EncodedGroupAddress &groupAddress)
virtual void setJoinedSourceAddressArraySize (size_t size)
virtual size_t getJoinedSourceAddressArraySize () const
virtual const EncodedSourceAddress & getJoinedSourceAddress (size_t k) const
virtual EncodedSourceAddress & getJoinedSourceAddressForUpdate (size_t k)
virtual void setJoinedSourceAddress (size_t k, const EncodedSourceAddress &joinedSourceAddress)
virtual void insertJoinedSourceAddress (size_t k, const EncodedSourceAddress &joinedSourceAddress)
void insertJoinedSourceAddress (const EncodedSourceAddress &joinedSourceAddress)
virtual void appendJoinedSourceAddress (const EncodedSourceAddress &joinedSourceAddress)
virtual void eraseJoinedSourceAddress (size_t k)
virtual void setPrunedSourceAddressArraySize (size_t size)
virtual size_t getPrunedSourceAddressArraySize () const
virtual const EncodedSourceAddress & getPrunedSourceAddress (size_t k) const
virtual EncodedSourceAddress & getPrunedSourceAddressForUpdate (size_t k)
virtual void setPrunedSourceAddress (size_t k, const EncodedSourceAddress &prunedSourceAddress)
virtual void insertPrunedSourceAddress (size_t k, const EncodedSourceAddress &prunedSourceAddress)
void insertPrunedSourceAddress (const EncodedSourceAddress &prunedSourceAddress)
virtual void appendPrunedSourceAddress (const EncodedSourceAddress &prunedSourceAddress)
virtual void erasePrunedSourceAddress (size_t k)
Protected Member Functions
bool operator== (const JoinPruneGroup &)=delete
Protected Attributes
EncodedGroupAddress groupAddress
EncodedSourceAddress * joinedSourceAddress = nullptr
size_t joinedSourceAddress_arraysize = 0
EncodedSourceAddress * prunedSourceAddress = nullptr
size_t prunedSourceAddress_arraysize = 0
Private Member Functions
void copy (const JoinPruneGroup &other)
Detailed Description
Class generated from inet/routing/pim/PimPacket.msg:151 by opp_msgtool.
// Record for Join/Prune message
// in structure it is not possible to use dynamic arrays, it is needed to use class
class JoinPruneGroup extends cObject
{
    @packetData;
    EncodedGroupAddress groupAddress;
    EncodedSourceAddress joinedSourceAddress[];
    EncodedSourceAddress prunedSourceAddress[];
}
Constructor & Destructor Documentation
JoinPruneGroup() [1/2]
inet::JoinPruneGroup::JoinPruneGroup ()
JoinPruneGroup() [2/2]
inet::JoinPruneGroup::JoinPruneGroup (const JoinPruneGroup & other)
~JoinPruneGroup()
virtual inet::JoinPruneGroup::~JoinPruneGroup () virtual
Member Function Documentation
appendJoinedSourceAddress()
virtual void inet::JoinPruneGroup::appendJoinedSourceAddress (const EncodedSourceAddress & joinedSourceAddress) virtual
appendPrunedSourceAddress()
virtual void inet::JoinPruneGroup::appendPrunedSourceAddress (const EncodedSourceAddress & prunedSourceAddress) virtual
copy()
void inet::JoinPruneGroup::copy (const JoinPruneGroup & other) private
dup()
virtual JoinPruneGroup* inet::JoinPruneGroup::dup () const inline override virtual
 {return new JoinPruneGroup(*this);}
eraseJoinedSourceAddress()
virtual void inet::JoinPruneGroup::eraseJoinedSourceAddress (size_t k) virtual
erasePrunedSourceAddress()
virtual void inet::JoinPruneGroup::erasePrunedSourceAddress (size_t k) virtual
getGroupAddress()
virtual const EncodedGroupAddress& inet::JoinPruneGroup::getGroupAddress () const virtual
Referenced by inet::PimDm::processGraftAckPacket(), inet::PimDm::processGraftPacket(), inet::PimDm::processJoinPrunePacket(), and inet::PimSm::processJoinPrunePacket().
getGroupAddressForUpdate()
virtual EncodedGroupAddress& inet::JoinPruneGroup::getGroupAddressForUpdate () inline virtual
 { return const_cast<EncodedGroupAddress&>(const_cast<JoinPruneGroup*>(this)->getGroupAddress());}
Referenced by inet::PimDm::sendGraftPacket(), inet::PimDm::sendJoinPacket(), inet::PimSm::sendPIMJoin(), inet::PimSm::sendPIMPrune(), and inet::PimDm::sendPrunePacket().
getJoinedSourceAddress()
virtual const EncodedSourceAddress& inet::JoinPruneGroup::getJoinedSourceAddress (size_t k) const virtual
Referenced by inet::PimDm::processGraftAckPacket(), inet::PimDm::processGraftPacket(), inet::PimDm::processJoinPrunePacket(), and inet::PimSm::processJoinPrunePacket().
getJoinedSourceAddressArraySize()
virtual size_t inet::JoinPruneGroup::getJoinedSourceAddressArraySize () const virtual
Referenced by inet::PimDm::processGraftAckPacket(), inet::PimDm::processGraftPacket(), inet::PimDm::processJoinPrunePacket(), and inet::PimSm::processJoinPrunePacket().
getJoinedSourceAddressForUpdate()
virtual EncodedSourceAddress& inet::JoinPruneGroup::getJoinedSourceAddressForUpdate (size_t k) inline virtual
 { return const_cast<EncodedSourceAddress&>(const_cast<JoinPruneGroup*>(this)->getJoinedSourceAddress(k));}
Referenced by inet::PimDm::sendGraftPacket(), inet::PimDm::sendJoinPacket(), and inet::PimSm::sendPIMJoin().
getPrunedSourceAddress()
virtual const EncodedSourceAddress& inet::JoinPruneGroup::getPrunedSourceAddress (size_t k) const virtual
Referenced by inet::PimDm::processJoinPrunePacket(), and inet::PimSm::processJoinPrunePacket().
getPrunedSourceAddressArraySize()
virtual size_t inet::JoinPruneGroup::getPrunedSourceAddressArraySize () const virtual
Referenced by inet::PimDm::processJoinPrunePacket(), and inet::PimSm::processJoinPrunePacket().
getPrunedSourceAddressForUpdate()
virtual EncodedSourceAddress& inet::JoinPruneGroup::getPrunedSourceAddressForUpdate (size_t k) inline virtual
 { return const_cast<EncodedSourceAddress&>(const_cast<JoinPruneGroup*>(this)->getPrunedSourceAddress(k));}
Referenced by inet::PimSm::sendPIMPrune(), and inet::PimDm::sendPrunePacket().
insertJoinedSourceAddress() [1/2]
void inet::JoinPruneGroup::insertJoinedSourceAddress (const EncodedSourceAddress & joinedSourceAddress) inline
 {appendJoinedSourceAddress(joinedSourceAddress);}
insertJoinedSourceAddress() [2/2]
virtual void inet::JoinPruneGroup::insertJoinedSourceAddress (size_t k, const EncodedSourceAddress & joinedSourceAddress) virtual
insertPrunedSourceAddress() [1/2]
void inet::JoinPruneGroup::insertPrunedSourceAddress (const EncodedSourceAddress & prunedSourceAddress) inline
 {appendPrunedSourceAddress(prunedSourceAddress);}
insertPrunedSourceAddress() [2/2]
virtual void inet::JoinPruneGroup::insertPrunedSourceAddress (size_t k, const EncodedSourceAddress & prunedSourceAddress) virtual
operator=()
JoinPruneGroup& inet::JoinPruneGroup::operator= (const JoinPruneGroup & other)
operator==()
bool inet::JoinPruneGroup::operator== (const JoinPruneGroup &) protected delete
parsimPack()
virtual void inet::JoinPruneGroup::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::JoinPruneGroup::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setGroupAddress()
virtual void inet::JoinPruneGroup::setGroupAddress (const EncodedGroupAddress & groupAddress) virtual
setJoinedSourceAddress()
virtual void inet::JoinPruneGroup::setJoinedSourceAddress (size_t k, const EncodedSourceAddress & joinedSourceAddress) virtual
setJoinedSourceAddressArraySize()
virtual void inet::JoinPruneGroup::setJoinedSourceAddressArraySize (size_t size) virtual
Referenced by inet::PimDm::sendGraftPacket(), inet::PimDm::sendJoinPacket(), and inet::PimSm::sendPIMJoin().
setPrunedSourceAddress()
virtual void inet::JoinPruneGroup::setPrunedSourceAddress (size_t k, const EncodedSourceAddress & prunedSourceAddress) virtual
setPrunedSourceAddressArraySize()
virtual void inet::JoinPruneGroup::setPrunedSourceAddressArraySize (size_t size) virtual
Referenced by inet::PimSm::sendPIMPrune(), and inet::PimDm::sendPrunePacket().
Member Data Documentation
groupAddress
EncodedGroupAddress inet::JoinPruneGroup::groupAddress protected
joinedSourceAddress
EncodedSourceAddress* inet::JoinPruneGroup::joinedSourceAddress = nullptr protected
joinedSourceAddress_arraysize
size_t inet::JoinPruneGroup::joinedSourceAddress_arraysize = 0 protected
prunedSourceAddress
EncodedSourceAddress* inet::JoinPruneGroup::prunedSourceAddress = nullptr protected
prunedSourceAddress_arraysize
size_t inet::JoinPruneGroup::prunedSourceAddress_arraysize = 0 protected
The documentation for this class was generated from the following file:
PimPacket_m.h