INET Framework for OMNeT++/OMNEST: inet::bgp::BgpAsPathSegment Class Reference
inet::bgp::BgpAsPathSegment Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:26 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpAsPathSegment ()
BgpAsPathSegment (const BgpAsPathSegment &other)
virtual ~BgpAsPathSegment ()
BgpAsPathSegment & operator= (const BgpAsPathSegment &other)
virtual BgpAsPathSegment * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual BgpPathSegmentType getType () const
virtual void setType (BgpPathSegmentType type)
virtual uint8_t getLength () const
virtual void setLength (uint8_t length)
virtual void setAsValueArraySize (size_t size)
virtual size_t getAsValueArraySize () const
virtual uint16_t getAsValue (size_t k) const
virtual void setAsValue (size_t k, uint16_t asValue)
virtual void insertAsValue (size_t k, uint16_t asValue)
void insertAsValue (uint16_t asValue)
virtual void appendAsValue (uint16_t asValue)
virtual void eraseAsValue (size_t k)
Protected Member Functions
bool operator== (const BgpAsPathSegment &)=delete
Protected Attributes
BgpPathSegmentType type = static_cast<inet::bgp::BgpPathSegmentType>(-1)
uint8_t length = 0
uint16_t * asValue = nullptr
size_t asValue_arraysize = 0
Private Member Functions
void copy (const BgpAsPathSegment &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:26 by opp_msgtool.
//
// Represents a BGPv4 AS_PATH path attribute (RFC 4271 Section 4.3)
//
class BgpAsPathSegment extends cObject
{
    @packetData;
    BgpPathSegmentType type;
    uint8_t length;
    uint16_t asValue[];
}
Constructor & Destructor Documentation
BgpAsPathSegment() [1/2]
inet::bgp::BgpAsPathSegment::BgpAsPathSegment ()
BgpAsPathSegment() [2/2]
inet::bgp::BgpAsPathSegment::BgpAsPathSegment (const BgpAsPathSegment & other)
~BgpAsPathSegment()
virtual inet::bgp::BgpAsPathSegment::~BgpAsPathSegment () virtual
Member Function Documentation
appendAsValue()
virtual void inet::bgp::BgpAsPathSegment::appendAsValue (uint16_t asValue) virtual
copy()
void inet::bgp::BgpAsPathSegment::copy (const BgpAsPathSegment & other) private
dup()
virtual BgpAsPathSegment* inet::bgp::BgpAsPathSegment::dup () const inline override virtual
 {return new BgpAsPathSegment(*this);}
eraseAsValue()
virtual void inet::bgp::BgpAsPathSegment::eraseAsValue (size_t k) virtual
getAsValue()
virtual uint16_t inet::bgp::BgpAsPathSegment::getAsValue (size_t k) const virtual
Referenced by inet::bgp::BgpRouter::printUpdateMessage(), and inet::bgp::BgpRouter::processMessage().
getAsValueArraySize()
virtual size_t inet::bgp::BgpAsPathSegment::getAsValueArraySize () const virtual
Referenced by inet::bgp::BgpRouter::printUpdateMessage(), and inet::bgp::BgpRouter::processMessage().
getLength()
virtual uint8_t inet::bgp::BgpAsPathSegment::getLength () const virtual
getType()
virtual BgpPathSegmentType inet::bgp::BgpAsPathSegment::getType () const virtual
insertAsValue() [1/2]
virtual void inet::bgp::BgpAsPathSegment::insertAsValue (size_t k, uint16_t asValue) virtual
insertAsValue() [2/2]
void inet::bgp::BgpAsPathSegment::insertAsValue (uint16_t asValue) inline
 {appendAsValue(asValue);}
operator=()
BgpAsPathSegment& inet::bgp::BgpAsPathSegment::operator= (const BgpAsPathSegment & other)
operator==()
bool inet::bgp::BgpAsPathSegment::operator== (const BgpAsPathSegment &) protected delete
parsimPack()
virtual void inet::bgp::BgpAsPathSegment::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpAsPathSegment::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::bgp::doParsimUnpacking().
setAsValue()
virtual void inet::bgp::BgpAsPathSegment::setAsValue (size_t k, uint16_t asValue) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setAsValueArraySize()
virtual void inet::bgp::BgpAsPathSegment::setAsValueArraySize (size_t size) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setLength()
virtual void inet::bgp::BgpAsPathSegment::setLength (uint8_t length) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setType()
virtual void inet::bgp::BgpAsPathSegment::setType (BgpPathSegmentType type) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
asValue
uint16_t* inet::bgp::BgpAsPathSegment::asValue = nullptr protected
asValue_arraysize
size_t inet::bgp::BgpAsPathSegment::asValue_arraysize = 0 protected
length
uint8_t inet::bgp::BgpAsPathSegment::length = 0 protected
type
BgpPathSegmentType inet::bgp::BgpAsPathSegment::type = static_cast<inet::bgp::BgpPathSegmentType>(-1) protected
The documentation for this class was generated from the following file:
BgpHeader_m.h