INET Framework for OMNeT++/OMNEST: inet::dymo::DymoRouteData Class Reference
inet::dymo::DymoRouteData Class Reference
Dymo-specific extra route data attached to routes in the routing table.
#include <DymoRouteData.h>
Public Member Functions
DymoRouteData ()
virtual ~DymoRouteData ()
bool getBroken () const
void setBroken (bool isBroken)
DymoSequenceNumber getSequenceNumber () const
void setSequenceNumber (DymoSequenceNumber sequenceNumber)
simtime_t getLastUsed () const
void setLastUsed (simtime_t lastUsed)
simtime_t getExpirationTime () const
void setExpirationTime (simtime_t expirationTime)
DymoMetricType getMetricType () const
void setMetricType (DymoMetricType metricType)
virtual std::string str () const
Private Attributes
bool isBroken
DymoSequenceNumber sequenceNumber
simtime_t lastUsed
simtime_t expirationTime
DymoMetricType metricType
Detailed Description
Dymo-specific extra route data attached to routes in the routing table.
Constructor & Destructor Documentation
DymoRouteData()
inet::dymo::DymoRouteData::DymoRouteData ()
 {
     isBroken = false;
     sequenceNumber = 0;
     lastUsed = 0;
     expirationTime = 0;
     metricType = HOP_COUNT;
 }
~DymoRouteData()
virtual inet::dymo::DymoRouteData::~DymoRouteData () inline virtual
 {}
Member Function Documentation
getBroken()
bool inet::dymo::DymoRouteData::getBroken () const inline
 { return isBroken; }
Referenced by inet::dymo::Dymo::ensureRouteForDatagram(), inet::dymo::Dymo::getRouteState(), str(), and inet::dymo::Dymo::updateRoutes().
getExpirationTime()
simtime_t inet::dymo::DymoRouteData::getExpirationTime () const inline
 { return expirationTime; }
Referenced by inet::dymo::Dymo::expungeRoutes(), inet::dymo::Dymo::getNextExpungeTime(), inet::dymo::Dymo::getRouteState(), and str().
getLastUsed()
simtime_t inet::dymo::DymoRouteData::getLastUsed () const inline
 { return lastUsed; }
Referenced by inet::dymo::Dymo::expungeRoutes(), inet::dymo::Dymo::getNextExpungeTime(), inet::dymo::Dymo::getRouteState(), and str().
getMetricType()
DymoMetricType inet::dymo::DymoRouteData::getMetricType () const inline
 { return metricType; }
Referenced by inet::dymo::Dymo::createRrep(), str(), and inet::dymo::Dymo::updateRoutes().
getSequenceNumber()
DymoSequenceNumber inet::dymo::DymoRouteData::getSequenceNumber () const inline
 { return sequenceNumber; }
Referenced by inet::dymo::Dymo::processRerr(), str(), and inet::dymo::Dymo::updateRoutes().
setBroken()
void inet::dymo::DymoRouteData::setBroken (bool isBroken) inline
 { this->isBroken = isBroken; }
Referenced by inet::dymo::Dymo::processRerr(), inet::dymo::Dymo::sendRerrForBrokenLink(), and inet::dymo::Dymo::updateRoute().
setExpirationTime()
void inet::dymo::DymoRouteData::setExpirationTime (simtime_t expirationTime) inline
 { this->expirationTime = expirationTime; }
Referenced by inet::dymo::Dymo::updateRoute().
setLastUsed()
void inet::dymo::DymoRouteData::setLastUsed (simtime_t lastUsed) inline
 { this->lastUsed = lastUsed; }
Referenced by inet::dymo::Dymo::ensureRouteForDatagram(), and inet::dymo::Dymo::updateRoute().
setMetricType()
void inet::dymo::DymoRouteData::setMetricType (DymoMetricType metricType) inline
 { this->metricType = metricType; }
Referenced by inet::dymo::Dymo::updateRoute().
setSequenceNumber()
void inet::dymo::DymoRouteData::setSequenceNumber (DymoSequenceNumber sequenceNumber) inline
 { this->sequenceNumber = sequenceNumber; }
Referenced by inet::dymo::Dymo::updateRoute().
str()
std::string inet::dymo::DymoRouteData::str () const virtual
 {
     std::ostringstream out;
     out << "isBroken = " << getBroken()
         << ", sequenceNumber = " << getSequenceNumber()
         << ", lastUsed = " << getLastUsed()
         << ", expirationTime = " << getExpirationTime()
         << ", metricType = " << getMetricType();
     return out.str();
 };
Member Data Documentation
expirationTime
simtime_t inet::dymo::DymoRouteData::expirationTime private
Referenced by DymoRouteData().
isBroken
bool inet::dymo::DymoRouteData::isBroken private
Referenced by DymoRouteData().
lastUsed
simtime_t inet::dymo::DymoRouteData::lastUsed private
Referenced by DymoRouteData().
metricType
DymoMetricType inet::dymo::DymoRouteData::metricType private
Referenced by DymoRouteData().
sequenceNumber
DymoSequenceNumber inet::dymo::DymoRouteData::sequenceNumber private
Referenced by DymoRouteData().
The documentation for this class was generated from the following files:
DymoRouteData.h
DymoRouteData.cc