INET Framework for OMNeT++/OMNEST: inet::TlvOptionBase Class Reference
inet::TlvOptionBase Class Reference
Class generated from inet/common/TlvOptions.msg:12 by opp_msgtool.
#include <TlvOptions_m.h>
Public Member Functions
TlvOptionBase ()
TlvOptionBase (const TlvOptionBase &other)
virtual ~TlvOptionBase ()
TlvOptionBase & operator= (const TlvOptionBase &other)
virtual TlvOptionBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual short getType () const
virtual void setType (short type)
virtual short getLength () const
virtual void setLength (short length)
Protected Member Functions
bool operator== (const TlvOptionBase &)=delete
Protected Attributes
short type = -1
short length = 0
Private Member Functions
void copy (const TlvOptionBase &other)
Detailed Description
Class generated from inet/common/TlvOptions.msg:12 by opp_msgtool.
class TlvOptionBase extends cObject
{
    @packetData;
    short type = -1;
    short length = 0;   // total length of option
}
Constructor & Destructor Documentation
TlvOptionBase() [1/2]
inet::TlvOptionBase::TlvOptionBase ()
TlvOptionBase() [2/2]
inet::TlvOptionBase::TlvOptionBase (const TlvOptionBase & other)
~TlvOptionBase()
virtual inet::TlvOptionBase::~TlvOptionBase () virtual
Member Function Documentation
copy()
void inet::TlvOptionBase::copy (const TlvOptionBase & other) private
dup()
virtual TlvOptionBase* inet::TlvOptionBase::dup () const inline override virtual
Reimplemented in inet::Ipv4OptionUnknown, inet::Ipv4OptionRouterAlert, inet::Ipv4OptionStreamId, inet::Ipv4OptionTimestamp, inet::Ipv4OptionRecordRoute, inet::Ipv4OptionEnd, inet::Ipv4OptionNop, inet::Ipv4Option, inet::GpsrOption, and inet::TlvOptionRaw.
 {return new TlvOptionBase(*this);}
getLength()
virtual short inet::TlvOptionBase::getLength () const virtual
Referenced by inet::TlvOptions::getLength(), inet::Ipv4HeaderSerializer::serialize(), and inet::Ipv4HeaderSerializer::serializeOption().
getType()
virtual short inet::TlvOptionBase::getType () const virtual
Referenced by inet::Ipv4HeaderSerializer::serializeOption().
operator=()
TlvOptionBase& inet::TlvOptionBase::operator= (const TlvOptionBase & other)
operator==()
bool inet::TlvOptionBase::operator== (const TlvOptionBase &) protected delete
parsimPack()
virtual void inet::TlvOptionBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::Ipv4OptionUnknown, inet::Ipv4OptionRouterAlert, inet::Ipv4OptionStreamId, inet::Ipv4OptionTimestamp, inet::Ipv4OptionRecordRoute, inet::Ipv4OptionEnd, inet::Ipv4OptionNop, inet::Ipv4Option, inet::GpsrOption, and inet::TlvOptionRaw.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TlvOptionBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::Ipv4OptionUnknown, inet::Ipv4OptionRouterAlert, inet::Ipv4OptionStreamId, inet::Ipv4OptionTimestamp, inet::Ipv4OptionRecordRoute, inet::Ipv4OptionEnd, inet::Ipv4OptionNop, inet::Ipv4Option, inet::GpsrOption, and inet::TlvOptionRaw.
Referenced by inet::doParsimUnpacking().
setLength()
virtual void inet::TlvOptionBase::setLength (short length) virtual
Referenced by inet::Gpsr::createGpsrOption().
setType()
virtual void inet::TlvOptionBase::setType (short type) virtual
Referenced by inet::Gpsr::setGpsrOptionOnNetworkDatagram().
Member Data Documentation
length
short inet::TlvOptionBase::length = 0 protected
type
short inet::TlvOptionBase::type = -1 protected
The documentation for this class was generated from the following file:
TlvOptions_m.h