INET Framework for OMNeT++/OMNEST: inet::sctp::SctpShutdownCompleteChunk Class Reference
inet::sctp::SctpShutdownCompleteChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:215 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpShutdownCompleteChunk (const char *name=nullptr)
SctpShutdownCompleteChunk (const SctpShutdownCompleteChunk &other)
virtual ~SctpShutdownCompleteChunk ()
SctpShutdownCompleteChunk & operator= (const SctpShutdownCompleteChunk &other)
virtual SctpShutdownCompleteChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getTBit () const
virtual void setTBit (bool TBit)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpShutdownCompleteChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
bool TBit = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpShutdownCompleteChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:215 by opp_msgtool.
class SctpShutdownCompleteChunk extends SctpChunk
{
    bool TBit = 0;
}
Constructor & Destructor Documentation
SctpShutdownCompleteChunk() [1/2]
inet::sctp::SctpShutdownCompleteChunk::SctpShutdownCompleteChunk (const char * name = nullptr)
SctpShutdownCompleteChunk() [2/2]
inet::sctp::SctpShutdownCompleteChunk::SctpShutdownCompleteChunk (const SctpShutdownCompleteChunk & other)
~SctpShutdownCompleteChunk()
virtual inet::sctp::SctpShutdownCompleteChunk::~SctpShutdownCompleteChunk () virtual
Member Function Documentation
copy()
void inet::sctp::SctpShutdownCompleteChunk::copy (const SctpShutdownCompleteChunk & other) private
dup()
virtual SctpShutdownCompleteChunk* inet::sctp::SctpShutdownCompleteChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpShutdownCompleteChunk(*this);}
getTBit()
virtual bool inet::sctp::SctpShutdownCompleteChunk::getTBit () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpShutdownCompleteChunk& inet::sctp::SctpShutdownCompleteChunk::operator= (const SctpShutdownCompleteChunk & other)
operator==()
bool inet::sctp::SctpShutdownCompleteChunk::operator== (const SctpShutdownCompleteChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpShutdownCompleteChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpShutdownCompleteChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setTBit()
virtual void inet::sctp::SctpShutdownCompleteChunk::setTBit (bool TBit) virtual
Referenced by inet::sctp::SctpAssociation::sendShutdownComplete(), and inet::sctp::Sctp::sendShutdownCompleteFromMain().
Member Data Documentation
TBit
bool inet::sctp::SctpShutdownCompleteChunk::TBit = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h