INET Framework for OMNeT++/OMNEST: inet::sctp::Sctp Class Reference
inet::sctp::Sctp Class Reference
Implements the SCTP protocol.
#include <Sctp.h>
Classes
struct AppAssocKey
struct AssocStat
struct SockPair
struct VTagPair
Public Types
typedef std::map< int32_t, AssocStat > AssocStatMap
typedef std::map< int32_t, VTagPair > SctpVTagMap
typedef std::map< AppAssocKey, SctpAssociation * > SctpAppAssocMap
typedef std::map< SockPair, SctpAssociation * > SctpAssocMap
Public Member Functions
void printInfoAssocMap ()
void printVTagMap ()
void removeAssociation (SctpAssociation *assoc)
virtual ~Sctp ()
virtual void initialize (int stage) override
virtual int numInitStages () const override
virtual void handleMessage (cMessage *msg) override
virtual void finish () override
virtual void send_to_ip (Packet *msg)
AssocStat * getAssocStat (uint32_t assocId)
void updateSockPair (SctpAssociation *assoc, L3Address localAddr, L3Address remoteAddr, int32_t localPort, int32_t remotePort)
To be called from SctpAssociation when socket pair changes.
void addLocalAddress (SctpAssociation *assoc, L3Address address)
void addLocalAddressToAllRemoteAddresses (SctpAssociation *assoc, L3Address address, std::vector< L3Address > remAddresses)
bool addRemoteAddress (SctpAssociation *assoc, L3Address localAddress, L3Address remoteAddress)
void removeLocalAddressFromAllRemoteAddresses (SctpAssociation *assoc, L3Address address, std::vector< L3Address > remAddresses)
void removeRemoteAddressFromAllAssociations (SctpAssociation *assoc, L3Address address, std::vector< L3Address > locAddresses)
void addForkedAssociation (SctpAssociation *assoc, SctpAssociation *newAssoc, L3Address localAddr, L3Address remoteAddr, int32_t localPort, int32_t remotePort)
Update assocs socket pair, and register newAssoc (which'll keep LISTENing).
uint16_t getEphemeralPort ()
To be called from SctpAssociation: reserves an ephemeral port for the connection.
SctpAssociation * getAssoc (int32_t assocId)
SctpAssociation * findAssocWithVTag (uint32_t peerVTag, uint32_t remotePort, uint32_t localPort)
SctpAssociation * findAssocForInitAck (SctpInitAckChunk *initack, L3Address srcAddr, L3Address destAddr, uint32_t srcPort, uint32_t destPort, bool findListen)
SctpVTagMap getVTagMap ()
void bindPortForUDP ()
SocketOptions * collectSocketOptions ()
Getter and Setter for the socket options.
void setSocketOptions (SocketOptions *options)
int getMaxInitRetrans ()
int getMaxInitRetransTimeout ()
double getRtoInitial ()
double getRtoMin ()
double getRtoMax ()
int getSackFrequency ()
double getSackPeriod ()
int getMaxBurst ()
int getFragPoint ()
int getNagle ()
bool getEnableHeartbeats ()
int getPathMaxRetrans ()
int getAssocMaxRtx ()
double getHbInterval ()
void setRtoInitial (double rtoInitial)
void setRtoMin (double rtoMin)
void setRtoMax (double rtoMax)
void setInterfaceId (int id)
int getInterfaceId ()
Public Attributes
AssocStatMap assocStatMap
SctpVTagMap sctpVTagMap
SctpAppAssocMap sctpAppAssocMap
SctpAssocMap sctpAssocMap
std::list< SctpAssociation * > assocList
UdpSocket udpSocket
int udpSockId
SocketOptions * socketOptions
simtime_t testTimeout
uint32_t numGapReports
uint32_t numPacketsReceived
uint32_t numPacketsDropped
bool auth
bool addIP
bool pktdrop
bool sackNow
uint64_t numPktDropReports
int interfaceId = -1
CrcMode crcMode = CRC_MODE_UNDEFINED
Protected Member Functions
SctpAssociation * findAssocForMessage (L3Address srcAddr, L3Address destAddr, uint32_t srcPort, uint32_t destPort, bool findListen)
SctpAssociation * findAssocForApp (int32_t appGateIndex, int32_t assocId)
int32_t findAssocForFd (int32_t fd)
void sendAbortFromMain (Ptr< SctpHeader > &sctpMsg, L3Address fromAddr, L3Address toAddr)
void sendShutdownCompleteFromMain (Ptr< SctpHeader > &sctpMsg, L3Address fromAddr, L3Address toAddr)
virtual void refreshDisplay () const override
Protected Attributes
ModuleRefByPar< IRoutingTable > rt
ModuleRefByPar< IInterfaceTable > ift
int32_t sizeAssocMap
uint16_t nextEphemeralPort
Detailed Description
Implements the SCTP protocol.
This section describes the internal architecture of the SCTP model.
You may want to check the SCTPSocket class which makes it easier to use SCTP from applications.
The SCTP protocol implementation is composed of several classes (discussion follows below):
SCTP: the module class
SctpAssociation: manages an association
SctpSendQueue, SctpReceiveQueue: abstract base classes for various types of send and receive queues
SctpAlgorithm: abstract base class for SCTP algorithms
SCTP subclassed from cSimpleModule. It manages socketpair-to-association mapping, and dispatches segments and user commands to the appropriate SctpAssociation object.
SctpAssociation manages the association, with the help of other objects. SctpAssociation itself implements the basic SCTP "machinery": takes care of the state machine, stores the state variables (TCB), sends/receives etc.
SctpAssociation internally relies on 3 objects. The first two are subclassed from SctpSendQueue and SctpReceiveQueue. They manage the actual data stream, so SctpAssociation itself only works with sequence number variables. This makes it possible to easily accomodate need for various types of simulated data transfer: real byte stream, "virtual" bytes (byte counts only), and sequence of cMessage objects (where every message object is mapped to a SCTP sequence number range).
Currently implemented send queue and receive queue classes are SctpVirtualDataSendQueue and SctpVirtualDataRcvQueue which implement queues with "virtual" bytes (byte counts only).
The third object is subclassed from SctpAlgorithm. Control over retransmissions, congestion control and ACK sending are "outsourced" from SctpAssociation into SctpAlgorithm: delayed acks, slow start, fast rexmit, etc. are all implemented in SctpAlgorithm subclasses.
The concrete SctpAlgorithm class to use can be chosen per association (in OPEN) or in a module parameter.
Member Typedef Documentation
AssocStatMap
typedef std::map<int32_t, AssocStat> inet::sctp::Sctp::AssocStatMap
SctpAppAssocMap
typedef std::map<AppAssocKey, SctpAssociation *> inet::sctp::Sctp::SctpAppAssocMap
SctpAssocMap
typedef std::map<SockPair, SctpAssociation *> inet::sctp::Sctp::SctpAssocMap
SctpVTagMap
typedef std::map<int32_t, VTagPair> inet::sctp::Sctp::SctpVTagMap
Constructor & Destructor Documentation
~Sctp()
inet::sctp::Sctp::~Sctp () virtual
 {
     EV_DEBUG << "delete SctpMain\n";
     if (!(sctpAppAssocMap.empty())) {
         EV_DEBUG << "clear appConnMap ptr=" << &sctpAppAssocMap << "\n";
         sctpAppAssocMap.clear();
     }
     if (!(assocStatMap.empty())) {
         EV_DEBUG << "clear assocStatMap ptr=" << &assocStatMap << "\n";
         assocStatMap.clear();
     }
     if (!(sctpVTagMap.empty())) {
         sctpVTagMap.clear();
     }
     EV_DEBUG << "after clearing maps\n";
 }
Member Function Documentation
addForkedAssociation()
void inet::sctp::Sctp::addForkedAssociation (SctpAssociation * assoc, SctpAssociation * newAssoc, L3Address localAddr, L3Address remoteAddr, int32_t localPort, int32_t remotePort)
Update assocs socket pair, and register newAssoc (which'll keep LISTENing).
Also, assoc will get a new assocId (and newAssoc will live on with its old assocId).
 {
     SockPair keyAssoc;
     bool found = false;
     EV_INFO << "addForkedConnection assocId=" << assoc->assocId << "    newId=" << newAssoc->assocId << "\n";
     for (auto& elem : sctpAssocMap) {
         if (assoc->assocId == elem.second->assocId) {
             keyAssoc = elem.first;
             found = true;
             break;
         }
     }
     ASSERT(found == true);
     // update assoc's socket pair, and register newAssoc (which'll keep LISTENing)
     updateSockPair(assoc, localAddr, remoteAddr, localPort, remotePort);
     updateSockPair(newAssoc, keyAssoc.localAddr, keyAssoc.remoteAddr, keyAssoc.localPort, keyAssoc.remotePort);
     // assoc will get a new assocId...
     AppAssocKey key;
     key.appGateIndex = assoc->appGateIndex;
     key.assocId = assoc->assocId;
     sctpAppAssocMap.erase(key);
     assoc->listeningAssocId = assoc->assocId;
     int id = SctpSocket::getNewAssocId();
     EV_INFO << "id = " << id << endl;
     key.assocId = assoc->assocId = id;
     EV_INFO << "listeningAssocId set to " << assoc->listeningAssocId << " new assocId = " << assoc->assocId << endl;
     sctpAppAssocMap[key] = assoc;
     // ...and newAssoc will live on with the old assocId
     key.appGateIndex = newAssoc->appGateIndex;
     key.assocId = newAssoc->assocId;
     sctpAppAssocMap[key] = newAssoc;
     sizeAssocMap = sctpAssocMap.size();
     printInfoAssocMap();
 }
Referenced by inet::sctp::SctpAssociation::processInitArrived().
addLocalAddress()
void inet::sctp::Sctp::addLocalAddress (SctpAssociation * assoc, L3Address address)
 {
     SockPair key;
     key.localAddr = assoc->localAddr;
     key.remoteAddr = assoc->remoteAddr;
     key.localPort = assoc->localPort;
     key.remotePort = assoc->remotePort;
     auto i = sctpAssocMap.find(key);
     if (i != sctpAssocMap.end()) {
         ASSERT(i->second == assoc);
         if (key.localAddr.isUnspecified()) {
             sctpAssocMap.erase(i);
             sizeAssocMap--;
         }
     }
     else
         EV_INFO << "no actual sockPair found\n";
     key.localAddr = address;
     sctpAssocMap[key] = assoc;
     sizeAssocMap = sctpAssocMap.size();
     EV_INFO << "addLocalAddress " << address << " number of connections now=" << sizeAssocMap << "\n";
     printInfoAssocMap();
 }
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpAssociation::sendInit().
addLocalAddressToAllRemoteAddresses()
void inet::sctp::Sctp::addLocalAddressToAllRemoteAddresses (SctpAssociation * assoc, L3Address address, std::vector< L3Address > remAddresses)
 {
     SockPair key;
     for (auto& remAddresse : remAddresses) {
 //        EV_DEBUG<<"remote address="<<(*i)<<"\n";
         key.localAddr = assoc->localAddr;
         key.remoteAddr = (remAddresse);
         key.localPort = assoc->localPort;
         key.remotePort = assoc->remotePort;
         auto j = sctpAssocMap.find(key);
         if (j != sctpAssocMap.end()) {
             ASSERT(j->second == assoc);
             if (key.localAddr.isUnspecified()) {
                 sctpAssocMap.erase(j);
                 sizeAssocMap--;
             }
         }
         else
             EV_INFO << "no actual sockPair found\n";
         key.localAddr = address;
         sctpAssocMap[key] = assoc;
         sizeAssocMap++;
         EV_DEBUG << "number of connections=" << sctpAssocMap.size() << "\n";
         printInfoAssocMap();
     }
 }
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpAssociation::sendAsconf().
addRemoteAddress()
bool inet::sctp::Sctp::addRemoteAddress (SctpAssociation * assoc, L3Address localAddress, L3Address remoteAddress)
 {
     EV_INFO << "Add remote Address: " << remoteAddress << " to local Address " << localAddress << "\n";
     SockPair key;
     key.localAddr = localAddress;
     key.remoteAddr = remoteAddress;
     key.localPort = assoc->localPort;
     key.remotePort = assoc->remotePort;
     auto i = sctpAssocMap.find(key);
     if (i != sctpAssocMap.end()) {
         ASSERT(i->second == assoc);
         return false;
     }
     else {
         sctpAssocMap[key] = assoc;
         sizeAssocMap++;
     }
     printInfoAssocMap();
     return true;
 }
Referenced by inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::processInitAckArrived(), and inet::sctp::SctpAssociation::processInitArrived().
bindPortForUDP()
void inet::sctp::Sctp::bindPortForUDP ()
 {
     EV_INFO << "Binding to UDP port " << SCTP_UDP_PORT << endl;
     udpSocket.setOutputGate(gate("ipOut"));
     udpSockId = getEnvir()->getUniqueNumber();
     EV_INFO << "UDP socket Id is " << udpSocket.getSocketId() << endl;
 //    udpSocket.bind(SCTP_UDP_PORT);
 }
collectSocketOptions()
SocketOptions * inet::sctp::Sctp::collectSocketOptions ()
Getter and Setter for the socket options.
 {
     SocketOptions *sockOptions = new SocketOptions();
     sockOptions->maxInitRetrans = par("maxInitRetrans");
     sockOptions->maxInitRetransTimeout = SCTP_TIMEOUT_INIT_REXMIT_MAX;
     sockOptions->rtoInitial = par("rtoInitial");
     sockOptions->rtoMin = par("rtoMin");
     sockOptions->rtoMax = par("rtoMax");
     sockOptions->sackFrequency = par("sackFrequency");
     sockOptions->sackPeriod = par("sackPeriod");
     sockOptions->maxBurst = par("maxBurst");
     sockOptions->fragPoint = par("fragPoint");
     sockOptions->nagle = par("nagleEnabled").boolValue() ? 1 : 0;
     sockOptions->enableHeartbeats = par("enableHeartbeats");
     sockOptions->pathMaxRetrans = par("pathMaxRetrans");
     sockOptions->hbInterval = par("hbInterval");
     sockOptions->assocMaxRtx = par("assocMaxRetrans");
     return sockOptions;
 }
Referenced by handleMessage().
findAssocForApp()
SctpAssociation * inet::sctp::Sctp::findAssocForApp (int32_t appGateIndex, int32_t assocId) protected
 {
     AppAssocKey key;
     key.appGateIndex = appGateIndex;
     key.assocId = assocId;
     EV_INFO << "findAssoc for appGateIndex " << appGateIndex << " and assoc " << assocId << "\n";
     auto i = sctpAppAssocMap.find(key);
     return (i == sctpAppAssocMap.end()) ? nullptr : i->second;
 }
Referenced by handleMessage().
findAssocForFd()
int32_t inet::sctp::Sctp::findAssocForFd (int32_t fd) protected
 {
     SctpAssociation *assoc = nullptr;
     for (auto& elem : sctpAppAssocMap) {
         assoc = elem.second;
         if (assoc->fd == fd)
             return assoc->assocId;
     }
     return -1;
 }
Referenced by handleMessage().
findAssocForInitAck()
SctpAssociation * inet::sctp::Sctp::findAssocForInitAck (SctpInitAckChunk * initack, L3Address srcAddr, L3Address destAddr, uint32_t srcPort, uint32_t destPort, bool findListen)
 {
     SctpAssociation *assoc = nullptr;
     int numberAddresses = initAckChunk->getAddressesArraySize();
     for (int32_t j = 0; j < numberAddresses; j++) {
         if (initAckChunk->getAddresses(j).getType() == L3Address::IPv6)
             continue;
         assoc = findAssocForMessage(initAckChunk->getAddresses(j), destAddr, srcPort, destPort, findListen);
         if (assoc) {
             break;
         }
     }
     return assoc;
 }
Referenced by handleMessage().
findAssocForMessage()
SctpAssociation * inet::sctp::Sctp::findAssocForMessage (L3Address srcAddr, L3Address destAddr, uint32_t srcPort, uint32_t destPort, bool findListen) protected
 {
     SockPair key;
     key.localAddr = destAddr;
     key.remoteAddr = srcAddr;
     key.localPort = destPort;
     key.remotePort = srcPort;
     SockPair save = key;
     EV_DEBUG << "findAssocForMessage: srcAddr=" << destAddr << " destAddr=" << srcAddr << " srcPort=" << destPort << "  destPort=" << srcPort << "\n";
     printInfoAssocMap();
     // try with fully qualified SockPair
     auto i = sctpAssocMap.find(key);
     if (i != sctpAssocMap.end())
         return i->second;
     // try with localAddr missing (only localPort specified in passive/active open)
     key.localAddr = L3Address();
     i = sctpAssocMap.find(key);
     if (i != sctpAssocMap.end()) {
         // try with localAddr missing (only localPort specified in passive/active open)
         return i->second;
     }
     if (findListen == true) {
         // try fully qualified local socket + blank remote socket (for incoming SYN)
         key = save;
         key.remoteAddr = L3Address();
         key.remotePort = 0;
         i = sctpAssocMap.find(key);
         if (i != sctpAssocMap.end()) {
             // try fully qualified local socket + blank remote socket
             return i->second;
         }
         // try with blank remote socket, and localAddr missing (for incoming SYN)
         key.localAddr = L3Address();
         i = sctpAssocMap.find(key);
         if (i != sctpAssocMap.end()) {
             // try with blank remote socket, and localAddr missing
             return i->second;
         }
     }
     // given up
     EV_INFO << "giving up on trying to find assoc for localAddr=" << srcAddr << " remoteAddr=" << destAddr << " localPort=" << srcPort << " remotePort=" << destPort << "\n";
     return nullptr;
 }
Referenced by findAssocForInitAck(), and handleMessage().
findAssocWithVTag()
SctpAssociation * inet::sctp::Sctp::findAssocWithVTag (uint32_t peerVTag, uint32_t remotePort, uint32_t localPort)
 {
     printVTagMap();
     EV_DEBUG << "findAssocWithVTag: peerVTag=" << peerVTag << " srcPort=" << remotePort << "    destPort=" << localPort << "\n";
     printInfoAssocMap();
     // try with fully qualified SockPair
     for (auto& elem : sctpVTagMap) {
         if ((elem.second.peerVTag == peerVTag && elem.second.localPort == localPort
              && elem.second.remotePort == remotePort)
             || (elem.second.localVTag == peerVTag && elem.second.localPort == localPort
                 && elem.second.remotePort == remotePort))
             return getAssoc(elem.first);
     }
     return nullptr;
 }
Referenced by handleMessage().
finish()
void inet::sctp::Sctp::finish () override virtual
 {
     auto assocMapIterator = sctpAssocMap.begin();
     while (assocMapIterator != sctpAssocMap.end()) {
         removeAssociation(assocMapIterator->second);
         assocMapIterator = sctpAssocMap.begin();
     }
     EV_INFO << getFullPath() << ": finishing SCTP with "
             << sctpAssocMap.size() << " connections open." << endl;
     for (AssocStatMap::const_iterator iterator = assocStatMap.begin();
          iterator != assocStatMap.end(); iterator++)
     {
         const Sctp::AssocStat& assoc = iterator->second;
         EV_DETAIL << "Association " << assoc.assocId << ": started at " << assoc.start
                   << " and finished at " << assoc.stop << " --> lifetime: " << assoc.lifeTime << endl;
         EV_DETAIL << "Association " << assoc.assocId << ": sent bytes=" << assoc.sentBytes
                   << ", acked bytes=" << assoc.ackedBytes << ", throughput=" << assoc.throughput << " bit/s" << endl;
         EV_DETAIL << "Association " << assoc.assocId << ": transmitted Bytes="
                   << assoc.transmittedBytes << ", retransmitted Bytes=" << assoc.transmittedBytes - assoc.ackedBytes << endl;
         EV_DETAIL << "Association " << assoc.assocId << ": number of Fast RTX="
                   << assoc.numFastRtx << ", number of Timer-Based RTX=" << assoc.numT3Rtx
                   << ", path failures=" << assoc.numPathFailures << ", ForwardTsns=" << assoc.numForwardTsn << endl;
         EV_DETAIL << "AllMessages=" << numPacketsReceived << " BadMessages=" << numPacketsDropped << endl;
         recordScalar("Association Lifetime", assoc.lifeTime);
         recordScalar("Acked Bytes", assoc.ackedBytes);
         recordScalar("Throughput [bit/s]", assoc.throughput);
         recordScalar("Transmitted Bytes", assoc.transmittedBytes);
         recordScalar("Fast RTX", assoc.numFastRtx);
         recordScalar("Timer-Based RTX", assoc.numT3Rtx);
         recordScalar("Duplicate Acks", assoc.numDups);
         recordScalar("Packets Received", numPacketsReceived);
         recordScalar("Packets Dropped", numPacketsDropped);
         recordScalar("Sum of R Gap Ranges", assoc.sumRGapRanges);
         recordScalar("Sum of NR Gap Ranges", assoc.sumNRGapRanges);
         recordScalar("Overfull SACKs", assoc.numOverfullSACKs);
         recordScalar("Drops Because New TSN Greater Than Highest TSN", assoc.numDropsBecauseNewTsnGreaterThanHighestTsn);
         recordScalar("Drops Because No Room In Buffer", assoc.numDropsBecauseNoRoomInBuffer);
         recordScalar("Chunks Reneged", assoc.numChunksReneged);
         recordScalar("sackPeriod", (simtime_t)socketOptions->sackPeriod);
         recordScalar("Number of AUTH chunks sent", assoc.numAuthChunksSent);
         recordScalar("Number of AUTH chunks accepted", assoc.numAuthChunksAccepted);
         recordScalar("Number of AUTH chunks rejected", assoc.numAuthChunksRejected);
         recordScalar("Number of StreamReset requests sent", assoc.numResetRequestsSent);
         recordScalar("Number of StreamReset requests performed", assoc.numResetRequestsPerformed);
         if (par("fairStart").doubleValue() > 0.0) {
             recordScalar("fair acked bytes", assoc.fairAckedBytes);
             recordScalar("fair start time", assoc.fairStart);
             recordScalar("fair stop time", assoc.fairStop);
             recordScalar("fair lifetime", assoc.fairLifeTime);
             recordScalar("fair throughput", assoc.fairThroughput);
         }
         recordScalar("Number of PacketDrop Reports", numPktDropReports);
         if (assoc.numEndToEndMessages > 0 && (assoc.cumEndToEndDelay / assoc.numEndToEndMessages) > 0) {
             uint32_t msgnum = assoc.numEndToEndMessages - assoc.startEndToEndDelay;
             if (assoc.stopEndToEndDelay > 0)
                 msgnum -= (assoc.numEndToEndMessages - assoc.stopEndToEndDelay);
             recordScalar("Average End to End Delay", assoc.cumEndToEndDelay / msgnum);
         }
         recordScalar("RTXMethod", par("RTXMethod").intValue());
     }
 }
getAssoc()
SctpAssociation * inet::sctp::Sctp::getAssoc (int32_t assocId)
 {
     for (auto& elem : sctpAppAssocMap) {
         if (elem.first.assocId == assocId)
             return elem.second;
     }
     return nullptr;
 }
Referenced by findAssocWithVTag().
getAssocMaxRtx()
int inet::sctp::Sctp::getAssocMaxRtx () inline
 { return socketOptions->assocMaxRtx; };
Referenced by inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT(), inet::sctp::SctpAssociation::process_TIMEOUT_RTX(), inet::sctp::SctpAssociation::process_TIMEOUT_SHUTDOWN(), and inet::sctp::SctpAssociation::updateCounters().
getAssocStat()
AssocStat* inet::sctp::Sctp::getAssocStat (uint32_t assocId) inline
     {
         auto found = assocStatMap.find(assocId);
         return (found != assocStatMap.end()) ? &found->second : nullptr;
     }
Referenced by inet::sctp::SctpAssociation::dequeueAckedChunks(), inet::sctp::SctpAssociation::handleChunkReportedAsAcked(), inet::sctp::SctpAssociation::handleChunkReportedAsMissing(), and inet::sctp::SctpAssociation::processSackArrived().
getEnableHeartbeats()
bool inet::sctp::Sctp::getEnableHeartbeats () inline
 { return socketOptions->enableHeartbeats; };
Referenced by inet::sctp::SctpAssociation::pmDataIsSentOn(), inet::sctp::SctpAssociation::pmStartPathManagement(), inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT_INTERVAL(), inet::sctp::SctpAssociation::processAsconfArrived(), and inet::sctp::SctpAssociation::stateEntered().
getEphemeralPort()
uint16_t inet::sctp::Sctp::getEphemeralPort ()
To be called from SctpAssociation: reserves an ephemeral port for the connection.
 {
     if (nextEphemeralPort == 5000)
         throw cRuntimeError("Ephemeral port range 1024..4999 exhausted (email SCTP model "
                             "author that he should implement reuse of ephemeral ports!!!)");
     return nextEphemeralPort++;
 }
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE().
getFragPoint()
int inet::sctp::Sctp::getFragPoint () inline
 { return socketOptions->fragPoint; };
Referenced by inet::sctp::SctpAssociation::stateEntered().
getHbInterval()
double inet::sctp::Sctp::getHbInterval () inline
 { return socketOptions->hbInterval; };
Referenced by inet::sctp::SctpAssociation::pmDataIsSentOn(), inet::sctp::SctpAssociation::pmStartPathManagement(), inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT_INTERVAL(), and inet::sctp::SctpAssociation::processHeartbeatAckArrived().
getInterfaceId()
int inet::sctp::Sctp::getInterfaceId () inline
 { return interfaceId; };
Referenced by inet::sctp::SctpAssociation::sendToIP().
getMaxBurst()
int inet::sctp::Sctp::getMaxBurst () inline
 { return socketOptions->maxBurst; };
Referenced by inet::sctp::SctpAssociation::stateEntered().
getMaxInitRetrans()
int inet::sctp::Sctp::getMaxInitRetrans () inline
 { return socketOptions->maxInitRetrans; };
Referenced by inet::sctp::SctpAssociation::process_TIMEOUT_INIT_REXMIT().
getMaxInitRetransTimeout()
int inet::sctp::Sctp::getMaxInitRetransTimeout () inline
 { return socketOptions->maxInitRetransTimeout; };
Referenced by inet::sctp::SctpAssociation::process_TIMEOUT_INIT_REXMIT().
getNagle()
int inet::sctp::Sctp::getNagle () inline
 { return socketOptions->nagle; };
Referenced by inet::sctp::SctpAssociation::stateEntered().
getPathMaxRetrans()
int inet::sctp::Sctp::getPathMaxRetrans () inline
 { return socketOptions->pathMaxRetrans; };
Referenced by inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT(), inet::sctp::SctpPathVariables::SctpPathVariables(), and inet::sctp::SctpAssociation::updateCounters().
getRtoInitial()
double inet::sctp::Sctp::getRtoInitial () inline
 { return socketOptions->rtoInitial; };
Referenced by inet::sctp::SctpAssociation::pmStartPathManagement(), and inet::sctp::SctpPathVariables::SctpPathVariables().
getRtoMax()
double inet::sctp::Sctp::getRtoMax () inline
 { return socketOptions->rtoMax; };
Referenced by inet::sctp::SctpAssociation::pmRttMeasurement(), inet::sctp::SctpAssociation::process_TIMEOUT_ASCONF(), inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT(), inet::sctp::SctpAssociation::process_TIMEOUT_RESET(), and inet::sctp::SctpAssociation::process_TIMEOUT_RTX().
getRtoMin()
double inet::sctp::Sctp::getRtoMin () inline
 { return socketOptions->rtoMin; };
Referenced by inet::sctp::SctpAssociation::pmRttMeasurement().
getSackFrequency()
int inet::sctp::Sctp::getSackFrequency () inline
 { return socketOptions->sackFrequency; };
Referenced by inet::sctp::SctpAssociation::stateEntered().
getSackPeriod()
double inet::sctp::Sctp::getSackPeriod () inline
 { return socketOptions->sackPeriod; };
Referenced by inet::sctp::SctpAssociation::stateEntered().
getVTagMap()
SctpVTagMap inet::sctp::Sctp::getVTagMap () inline
 { return sctpVTagMap; };
handleMessage()
void inet::sctp::Sctp::handleMessage (cMessage * msg) override virtual
 {
     L3Address destAddr;
     L3Address srcAddr;
     bool findListen = false;
     EV_INFO << "\n\nSctpMain handleMessage at " << getFullPath() << "\n";
     if (msg->isSelfMessage()) {
         EV_DEBUG << "selfMessage\n";
         SctpAssociation *assoc = (SctpAssociation *)msg->getContextPointer();
         if (assoc) {
             bool ret = assoc->processTimer(msg);
             if (!ret)
                 removeAssociation(assoc);
         }
     }
     else if (msg->arrivedOn("ipIn")) {
         EV_INFO << "Message from IP\n";
         printInfoAssocMap();
         Packet *packet = check_and_cast<Packet *>(msg);
         auto protocol = packet->getTag<PacketProtocolTag>()->getProtocol();
         if (protocol == &Protocol::sctp) {
             // must be an SctpHeader
             SctpHeader *sctpmsg = (packet->peekAtFront<SctpHeader>().get()->dup());
             int chunkLength = B(sctpmsg->getChunkLength()).get();
             numPacketsReceived++;
             if (!pktdrop && (packet->hasBitError())) {
                 EV_WARN << "Packet has bit-error. delete it\n";
                 numPacketsDropped++;
                 delete msg;
                 return;
             }
             if (pktdrop && packet->hasBitError()) {
                 EV_WARN << "Packet has bit-error. Call Pktdrop\n";
             }
             srcAddr = packet->getTag<L3AddressInd>()->getSrcAddress();
             destAddr = packet->getTag<L3AddressInd>()->getDestAddress();
             EV_INFO << "srcAddr=" << srcAddr << "   destAddr=" << destAddr << "\n";
             if (chunkLength > SCTP_COMMON_HEADER) {
                 if (((sctpmsg->getSctpChunks(0)))->getSctpChunkType() == INIT || ((sctpmsg->getSctpChunks(0)))->getSctpChunkType() == INIT_ACK)
                     findListen = true;
                 SctpAssociation *assoc = findAssocForMessage(srcAddr, destAddr, sctpmsg->getSrcPort(), sctpmsg->getDestPort(), findListen);
                 if (!assoc && sctpAssocMap.size() > 0 && (((sctpmsg->getSctpChunks(0)))->getSctpChunkType() == INIT_ACK)) {
                     SctpInitAckChunk *initack = check_and_cast<SctpInitAckChunk *>((SctpChunk *)(sctpmsg->getSctpChunks(0)));
                     assoc = findAssocForInitAck(initack, srcAddr, destAddr, sctpmsg->getSrcPort(), sctpmsg->getDestPort(), findListen);
                 }
                 if (!assoc && sctpAssocMap.size() > 0 && (((sctpmsg->getSctpChunks(0)))->getSctpChunkType() == ERRORTYPE
                                                           || (sctpmsg->getSctpChunksArraySize() > 1 &&
                                                               (((sctpmsg->getSctpChunks(1)))->getSctpChunkType() == ASCONF || ((sctpmsg->getSctpChunks(1)))->getSctpChunkType() == ASCONF_ACK))))
                 {
                     assoc = findAssocWithVTag(sctpmsg->getVTag(), sctpmsg->getSrcPort(), sctpmsg->getDestPort());
                 }
                 if (!assoc) {
                     EV_INFO << "no assoc found msg=" << sctpmsg->getName() << "\n";
                     if (!pktdrop && packet->hasBitError()) {
 //                        delete sctpmsg;
                         return;
                     }
                     Ptr<SctpHeader> sctpmsgptr(sctpmsg);
                     if (((sctpmsg->getSctpChunks(0)))->getSctpChunkType() == SHUTDOWN_ACK)
                         sendShutdownCompleteFromMain(sctpmsgptr, destAddr, srcAddr);
                     else if (((sctpmsg->getSctpChunks(0)))->getSctpChunkType() != ABORT &&
                              ((sctpmsg->getSctpChunks(0)))->getSctpChunkType() != SHUTDOWN_COMPLETE)
                     {
                         sendAbortFromMain(sctpmsgptr, destAddr, srcAddr);
                     }
                     delete packet;
                 }
                 else {
                     EV_INFO << "assoc " << assoc->assocId << " found\n";
                     bool ret = assoc->processSctpMessage(sctpmsg, srcAddr, destAddr);
                     if (!ret) {
                         EV_DEBUG << "SctpMain:: removeAssociation \n";
                         removeAssociation(assoc);
                         delete packet;
                     }
                     else {
                         delete packet;
                     }
                 }
             }
         }
         else {
             delete packet;
         }
     }
     else { // must be from app
         EV_DEBUG << "must be from app\n";
         auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
         int32_t assocId = tags.getTag<SocketReq>()->getSocketId();
         EV_INFO << "assocId = " << assocId << endl;
         if (msg->getKind() == SCTP_C_GETSOCKETOPTIONS) {
             auto controlInfo = tags.getTag<SctpSendReq>();
             Indication *cmsg = new Indication("SendSocketOptions", SCTP_I_SENDSOCKETOPTIONS);
             auto indication = cmsg->addTag<SctpCommandReq>();
             indication->setSocketId(controlInfo->getSocketId());
             socketOptions = collectSocketOptions();
             cmsg->setContextPointer((void *)socketOptions);
             cmsg->addTag<SocketInd>()->setSocketId(assocId);
             send(cmsg, "appOut");
             delete msg;
         }
         else {
             int32_t appGateIndex;
             int32_t fd;
             Ptr<const SctpCommandReq> controlInfo = tags.findTag<SctpOpenReq>();
             if (!controlInfo) {
                 controlInfo = tags.findTag<SctpSendReq>();
                 if (!controlInfo) {
                     controlInfo = tags.findTag<SctpCommandReq>();
                     if (!controlInfo) {
                         controlInfo = tags.findTag<SctpAvailableReq>();
                         if (!controlInfo) {
                             controlInfo = tags.findTag<SctpResetReq>();
                             if (!controlInfo) {
                                 controlInfo = tags.findTag<SctpInfoReq>();
                                 if (!controlInfo) {
                                     std::cout << "!!!!!!!!!Unknown Tag!!!!!!!!\n";
                                 }
                             }
                         }
                     }
                 }
             }
             if (controlInfo->getGate() != -1)
                 appGateIndex = controlInfo->getGate();
             else
                 appGateIndex = msg->getArrivalGate()->isVector() ? msg->getArrivalGate()->getIndex() : 0;
             if (controlInfo && assocId == -1) {
                 fd = controlInfo->getFd();
                 assocId = findAssocForFd(fd);
             }
             EV_INFO << "msg arrived from app for assoc " << assocId << "\n";
             SctpAssociation *assoc = findAssocForApp(appGateIndex, assocId);
             if (!assoc) {
                 EV_INFO << "no assoc found. msg=" << msg->getName() << " number of assocs = " << assocList.size() << "\n";
                 if (strcmp(msg->getName(), "PassiveOPEN") == 0 || strcmp(msg->getName(), "Associate") == 0) {
                     if (assocList.size() > 0) {
                         assoc = nullptr;
                         const auto& open = tags.findTag<SctpOpenReq>();
                         EV_INFO << "Looking for assoc with remoteAddr=" << open->getRemoteAddr() << ", remotePort=" << open->getRemotePort() << ", localPort=" << open->getLocalPort() << "\n";
                         for (auto& elem : assocList) {
                             EV_DETAIL << "remoteAddr=" << (elem)->remoteAddr << ", remotePort=" << (elem)->remotePort << ", localPort=" << (elem)->localPort << "\n";
                             if ((elem)->remoteAddr == open->getRemoteAddr() && (elem)->localPort == open->getLocalPort() && (elem)->remotePort == open->getRemotePort()) {
                                 assoc = (elem);
                                 break;
                             }
                         }
                     }
                     if (assocList.size() == 0 || assoc == nullptr) {
                         assoc = new SctpAssociation(this, appGateIndex, assocId, rt, ift);
                         AppAssocKey key;
                         key.appGateIndex = appGateIndex;
                         key.assocId = assocId;
                         sctpAppAssocMap[key] = assoc;
                         EV_INFO << "SCTP association created for appGateIndex " << appGateIndex << " and assoc " << assocId << "\n";
                         bool ret = assoc->processAppCommand(msg, const_cast<SctpCommandReq *>(controlInfo.get()));
                         if (!ret) {
                             removeAssociation(assoc);
                         }
                     }
                 }
             }
             else {
                 EV_INFO << "assoc found\n";
                 bool ret = assoc->processAppCommand(msg, const_cast<SctpCommandReq *>(controlInfo.get()));
                 if (!ret) {
                     removeAssociation(assoc);
                 }
             }
             delete msg;
         }
     }
 }
initialize()
void inet::sctp::Sctp::initialize (int stage) override virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         ift.reference(this, "interfaceTableModule", true);
         rt.reference(this, "routingTableModule", true);
         auth = par("auth");
         pktdrop = par("packetDrop");
         sackNow = par("sackNow");
         numPktDropReports = 0;
         numPacketsReceived = 0;
         numPacketsDropped = 0;
         sizeAssocMap = 0;
         nextEphemeralPort = (uint16_t)(intrand(10000) + 30000);
         cModule *netw = getSimulation()->getSystemModule();
         if (netw->hasPar("testTimeout")) {
             testTimeout = netw->par("testTimeout");
         }
         const char *crcModeString = par("crcMode");
         crcMode = parseCrcMode(crcModeString, false);
     }
     else if (stage == INITSTAGE_TRANSPORT_LAYER) {
         registerService(Protocol::sctp, gate("appIn"), gate("appOut"));
         registerProtocol(Protocol::sctp, gate("ipOut"), gate("ipIn"));
         if (crcMode == CRC_COMPUTED) {
             cModuleType *moduleType = cModuleType::get("inet.transportlayer.sctp.SctpCrcInsertion");
             auto crcInsertion = check_and_cast<SctpCrcInsertion *>(moduleType->create("crcInsertion", this));
             crcInsertion->finalizeParameters();
             crcInsertion->callInitialize();
             crcInsertion->setCrcMode(crcMode);
 #ifdef INET_WITH_IPv4
             auto ipv4 = dynamic_cast<INetfilter *>(findModuleByPath("^.ipv4.ip"));
             if (ipv4 != nullptr) {
                 ipv4->registerHook(0, crcInsertion);
             }
 #endif
 #ifdef INET_WITH_IPv6
             auto ipv6 = dynamic_cast<INetfilter *>(findModuleByPath("^.ipv6.ipv6"));
             if (ipv6 != nullptr)
                 ipv6->registerHook(0, crcInsertion);
 #endif
         }
         if (par("udpEncapsEnabled")) {
             EV_INFO << "udpEncapsEnabled" << endl;
             cModuleType *moduleType = cModuleType::get("inet.transportlayer.sctp.SctpUdpHook");
             auto udpHook = check_and_cast<SctpUdpHook *>(moduleType->create("udpHook", this));
             udpHook->finalizeParameters();
             udpHook->callInitialize();
 #ifdef INET_WITH_IPv4
             auto ipv4 = dynamic_cast<INetfilter *>(findModuleByPath("^.ipv4.ip"));
             if (ipv4 != nullptr)
                 ipv4->registerHook(0, udpHook);
 #endif
 #ifdef INET_WITH_IPv6
             auto ipv6 = dynamic_cast<INetfilter *>(findModuleByPath("^.ipv6.ipv6"));
             if (ipv6 != nullptr)
                 ipv6->registerHook(0, udpHook);
 #endif
         }
     }
 }
numInitStages()
virtual int inet::sctp::Sctp::numInitStages () const inline override virtual
 { return NUM_INIT_STAGES; }
printInfoAssocMap()
void inet::sctp::Sctp::printInfoAssocMap ()
 {
     SctpAssociation *assoc;
     SockPair key;
     EV_DETAIL << "Number of Assocs: " << sizeAssocMap << "\n";
     if (sizeAssocMap > 0) {
         for (auto& elem : sctpAssocMap) {
             assoc = elem.second;
             key = elem.first;
             EV_DETAIL << "assocId: " << assoc->assocId << " src: " << key.localAddr << " dst: " << key.remoteAddr << " lPort: " << key.localPort << " rPort: " << key.remotePort << " fd: " << assoc->fd << "\n";
         }
         EV_DETAIL << "\n";
     }
 }
Referenced by addForkedAssociation(), addLocalAddress(), addLocalAddressToAllRemoteAddresses(), addRemoteAddress(), inet::sctp::SctpAssociation::cloneAssociation(), findAssocForMessage(), findAssocWithVTag(), handleMessage(), removeAssociation(), removeLocalAddressFromAllRemoteAddresses(), removeRemoteAddressFromAllAssociations(), inet::sctp::SctpAssociation::sendInit(), and updateSockPair().
printVTagMap()
void inet::sctp::Sctp::printVTagMap ()
 {
     int32_t assocId;
     VTagPair key;
     EV_DETAIL << "Number of Assocs: " << sctpVTagMap.size() << "\n";
     if (sctpVTagMap.size() > 0) {
         for (auto& elem : sctpVTagMap) {
             assocId = elem.first;
             key = elem.second;
             EV_DETAIL << "assocId: " << assocId << " peerVTag: " << key.peerVTag
                       << " localVTag: " << key.localVTag
                       << " localPort: " << key.localPort << " rPort: " << key.remotePort << "\n";
         }
         EV_DETAIL << "\n";
     }
 }
Referenced by findAssocWithVTag().
refreshDisplay()
void inet::sctp::Sctp::refreshDisplay () const override protected virtual
 {
 #if 0
     if (getEnvir()->disable_tracing) {
         // in express mode, we don't bother to update the display
         // (std::map's iteration is not very fast if map is large)
         getDisplayString().setTagArg("t", 0, "");
         return;
     }
 //    char buf[40];
 //    sprintf(buf,"%d conns", sctpAppConnMap.size());
 //    displayString().setTagArg("t",0,buf);
     int32_t numCLOSED = 0, numLISTEN = 0, numSYN_SENT = 0, numSYN_RCVD = 0,
             numESTABLISHED = 0, numCLOSE_WAIT = 0, numLAST_ACK = 0, numFIN_WAIT_1 = 0,
             numFIN_WAIT_2 = 0, numCLOSING = 0, numTIME_WAIT = 0;
     for (auto i = sctpAppConnMap.begin(); i != sctpAppConnMap.end(); ++i) {
         int32_t state = (*i).second->getFsmState();
         switch (state) {
 //            case SCTP_S_INIT:           numINIT++; break;
             case SCTP_S_CLOSED:
                 numCLOSED++;
                 break;
             case SCTP_S_COOKIE_WAIT:
                 numLISTEN++;
                 break;
             case SCTP_S_COOKIE_ECHOED:
                 numSYN_SENT++;
                 break;
             case SCTP_S_ESTABLISHED:
                 numESTABLISHED++;
                 break;
             case SCTP_S_SHUTDOWN_PENDING:
                 numCLOSE_WAIT++;
                 break;
             case SCTP_S_SHUTDOWN_SENT:
                 numLAST_ACK++;
                 break;
             case SCTP_S_SHUTDOWN_RECEIVED:
                 numFIN_WAIT_1++;
                 break;
             case SCTP_S_SHUTDOWN_ACK_SENT:
                 numFIN_WAIT_2++;
                 break;
         }
     }
     char buf2[300];
     buf2[0] = '\0';
     if (numCLOSED > 0)
         sprintf(buf2 + strlen(buf2), "closed:%d ", numCLOSED);
     if (numLISTEN > 0)
         sprintf(buf2 + strlen(buf2), "listen:%d ", numLISTEN);
     if (numSYN_SENT > 0)
         sprintf(buf2 + strlen(buf2), "syn_sent:%d ", numSYN_SENT);
     if (numSYN_RCVD > 0)
         sprintf(buf2 + strlen(buf2), "syn_rcvd:%d ", numSYN_RCVD);
     if (numESTABLISHED > 0)
         sprintf(buf2 + strlen(buf2), "estab:%d ", numESTABLISHED);
     if (numCLOSE_WAIT > 0)
         sprintf(buf2 + strlen(buf2), "close_wait:%d ", numCLOSE_WAIT);
     if (numLAST_ACK > 0)
         sprintf(buf2 + strlen(buf2), "last_ack:%d ", numLAST_ACK);
     if (numFIN_WAIT_1 > 0)
         sprintf(buf2 + strlen(buf2), "fin_wait_1:%d ", numFIN_WAIT_1);
     if (numFIN_WAIT_2 > 0)
         sprintf(buf2 + strlen(buf2), "fin_wait_2:%d ", numFIN_WAIT_2);
     if (numCLOSING > 0)
         sprintf(buf2 + strlen(buf2), "closing:%d ", numCLOSING);
     if (numTIME_WAIT > 0)
         sprintf(buf2 + strlen(buf2), "time_wait:%d ", numTIME_WAIT);
     getDisplayString().setTagArg("t", 0, buf2);
 #endif // if 0
 }
removeAssociation()
void inet::sctp::Sctp::removeAssociation (SctpAssociation * assoc)
 {
     bool ok = false;
     bool find = false;
     const int32_t id = assoc->assocId;
     EV_INFO << "Deleting SCTP connection " << assoc << " id= " << id << endl;
     printInfoAssocMap();
     if (sizeAssocMap > 0) {
         auto assocStatMapIterator = assocStatMap.find(assoc->assocId);
         if (assocStatMapIterator != assocStatMap.end()) {
             assocStatMapIterator->second.stop = simTime();
             assocStatMapIterator->second.lifeTime = assocStatMapIterator->second.stop - assocStatMapIterator->second.start;
             assocStatMapIterator->second.throughput = assocStatMapIterator->second.ackedBytes * 8 / assocStatMapIterator->second.lifeTime.dbl();
         }
         while (!ok) {
             if (sizeAssocMap == 0) {
                 ok = true;
             }
             else {
                 for (auto sctpAssocMapIterator = sctpAssocMap.begin();
                      sctpAssocMapIterator != sctpAssocMap.end(); sctpAssocMapIterator++)
                 {
                     if (sctpAssocMapIterator->second != nullptr) {
                         SctpAssociation *myAssoc = sctpAssocMapIterator->second;
                         if (myAssoc->assocId == assoc->assocId) {
                             if (myAssoc->T1_InitTimer) {
                                 myAssoc->stopTimer(myAssoc->T1_InitTimer);
                             }
                             if (myAssoc->T2_ShutdownTimer) {
                                 myAssoc->stopTimer(myAssoc->T2_ShutdownTimer);
                             }
                             if (myAssoc->T5_ShutdownGuardTimer) {
                                 myAssoc->stopTimer(myAssoc->T5_ShutdownGuardTimer);
                             }
                             if (myAssoc->SackTimer) {
                                 myAssoc->stopTimer(myAssoc->SackTimer);
                             }
                             if (myAssoc->StartAddIP) {
                                 myAssoc->stopTimer(myAssoc->StartAddIP);
                             }
                             sctpAssocMap.erase(sctpAssocMapIterator);
                             sizeAssocMap--;
                             find = true;
                             break;
                         }
                     }
                 }
             }
             if (!find) {
                 ok = true;
             }
             else {
                 find = false;
             }
         }
     }
     // Write statistics
     char str[128];
     for (auto pathMapIterator = assoc->sctpPathMap.begin();
          pathMapIterator != assoc->sctpPathMap.end(); pathMapIterator++)
     {
         const SctpPathVariables *path = pathMapIterator->second;
         snprintf(str, sizeof(str), "Number of Fast Retransmissions %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfFastRetransmissions);
         snprintf(str, sizeof(str), "Number of Timer-Based Retransmissions %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfTimerBasedRetransmissions);
         snprintf(str, sizeof(str), "Number of Heartbeats Sent %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfHeartbeatsSent);
         snprintf(str, sizeof(str), "Number of Heartbeats Received %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfHeartbeatsRcvd);
         snprintf(str, sizeof(str), "Number of Heartbeat ACKs Sent %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfHeartbeatAcksSent);
         snprintf(str, sizeof(str), "Number of Heartbeat ACKs Received %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfHeartbeatAcksRcvd);
         snprintf(str, sizeof(str), "Number of Duplicates %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfDuplicates);
         snprintf(str, sizeof(str), "Number of Bytes received from %d:%s",
                 assoc->assocId, path->remoteAddress.str().c_str());
         recordScalar(str, path->numberOfBytesReceived);
     }
     for (uint16_t i = 0; i < assoc->inboundStreams; i++) {
         snprintf(str, sizeof(str), "Bytes received on stream %d of assoc %d",
                 i, assoc->assocId);
         recordScalar(str, assoc->getState()->streamThroughput[i]);
     }
     recordScalar("Blocking TSNs Moved", assoc->state->blockingTsnsMoved);
     assoc->removePath();
     assoc->deleteStreams();
     // Chunks may be in the transmission and retransmission queues simultaneously.
     // Remove entry from transmission queue if it is already in the retransmission queue.
     for (auto i = assoc->getRetransmissionQueue()->payloadQueue.begin();
          i != assoc->getRetransmissionQueue()->payloadQueue.end(); i++)
     {
         auto j = assoc->getTransmissionQueue()->payloadQueue.find(i->second->tsn);
         if (j != assoc->getTransmissionQueue()->payloadQueue.end()) {
             assoc->getTransmissionQueue()->payloadQueue.erase(j);
         }
     }
     // Now, both queues can be safely deleted.
     delete assoc->getRetransmissionQueue();
     delete assoc->getTransmissionQueue();
     AppAssocKey key;
     key.appGateIndex = assoc->appGateIndex;
     key.assocId = assoc->assocId;
     sctpAppAssocMap.erase(key);
     assocList.remove(assoc);
     delete assoc;
 }
Referenced by finish(), handleMessage(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT(), inet::sctp::SctpAssociation::process_TIMEOUT_RTX(), inet::sctp::SctpAssociation::process_TIMEOUT_SHUTDOWN(), inet::sctp::SctpAssociation::processTimer(), and inet::sctp::SctpAssociation::updateCounters().
removeLocalAddressFromAllRemoteAddresses()
void inet::sctp::Sctp::removeLocalAddressFromAllRemoteAddresses (SctpAssociation * assoc, L3Address address, std::vector< L3Address > remAddresses)
 {
     SockPair key;
     for (auto& remAddresse : remAddresses) {
         key.localAddr = address;
         key.remoteAddr = (remAddresse);
         key.localPort = assoc->localPort;
         key.remotePort = assoc->remotePort;
         auto j = sctpAssocMap.find(key);
         if (j != sctpAssocMap.end()) {
             ASSERT(j->second == assoc);
             sctpAssocMap.erase(j);
             sizeAssocMap--;
         }
         else
             EV_INFO << "no actual sockPair found\n";
         printInfoAssocMap();
     }
 }
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived().
removeRemoteAddressFromAllAssociations()
void inet::sctp::Sctp::removeRemoteAddressFromAllAssociations (SctpAssociation * assoc, L3Address address, std::vector< L3Address > locAddresses)
 {
     SockPair key;
     for (auto& locAddresse : locAddresses) {
         key.localAddr = (locAddresse);
         key.remoteAddr = address;
         key.localPort = assoc->localPort;
         key.remotePort = assoc->remotePort;
         auto j = sctpAssocMap.find(key);
         if (j != sctpAssocMap.end()) {
             ASSERT(j->second == assoc);
             sctpAssocMap.erase(j);
             sizeAssocMap--;
         }
         else
             EV_INFO << "no actual sockPair found\n";
         printInfoAssocMap();
     }
 }
Referenced by inet::sctp::SctpAssociation::processAsconfArrived().
send_to_ip()
void inet::sctp::Sctp::send_to_ip (Packet * msg) virtual
 {
     EV_INFO << "send packet " << msg << " to IP\n";
     send(msg, "ipOut");
 }
Referenced by sendAbortFromMain(), and sendShutdownCompleteFromMain().
sendAbortFromMain()
void inet::sctp::Sctp::sendAbortFromMain (Ptr< SctpHeader > & sctpMsg, L3Address fromAddr, L3Address toAddr) protected
 {
     const auto& msg = makeShared<SctpHeader>();
     EV_DEBUG << "\n\nSctp::sendAbortFromMain()\n";
     msg->setSrcPort(sctpmsg->getDestPort());
     msg->setDestPort(sctpmsg->getSrcPort());
     msg->setChunkLength(B(SCTP_COMMON_HEADER));
     msg->setCrc(0);
     msg->setCrcMode(crcMode);
     msg->setChecksumOk(true);
     SctpAbortChunk *abortChunk = new SctpAbortChunk();
     abortChunk->setSctpChunkType(ABORT);
     if (sctpmsg->getSctpChunksArraySize() > 0 && ((sctpmsg->getSctpChunks(0)))->getSctpChunkType() == INIT) {
         const SctpInitChunk *initChunk = check_and_cast<const SctpInitChunk *>(sctpmsg->getSctpChunks(0));
         abortChunk->setT_Bit(0);
         msg->setVTag(initChunk->getInitTag());
     }
     else {
         abortChunk->setT_Bit(1);
         msg->setVTag(sctpmsg->getVTag());
     }
     abortChunk->setByteLength(SCTP_ABORT_CHUNK_LENGTH);
     msg->appendSctpChunks(abortChunk);
     Packet *pkt = new Packet("ABORT");
     auto addresses = pkt->addTag<L3AddressReq>();
     addresses->setSrcAddress(fromAddr);
     addresses->setDestAddress(toAddr);
     IL3AddressType *addressType = toAddr.getAddressType();
     pkt->addTag<DispatchProtocolReq>()->setProtocol(addressType->getNetworkProtocol());
     insertTransportProtocolHeader(pkt, Protocol::sctp, msg);
     send_to_ip(pkt);
 }
Referenced by handleMessage().
sendShutdownCompleteFromMain()
void inet::sctp::Sctp::sendShutdownCompleteFromMain (Ptr< SctpHeader > & sctpMsg, L3Address fromAddr, L3Address toAddr) protected
 {
     const auto& msg = makeShared<SctpHeader>();
     EV_DEBUG << "\n\nSCTP:sendShutdownCompleteFromMain \n";
     msg->setSrcPort(sctpmsg->getDestPort());
     msg->setDestPort(sctpmsg->getSrcPort());
     msg->setChunkLength(b(SCTP_COMMON_HEADER));
     msg->setCrc(0);
     msg->setCrcMode(crcMode);
     msg->setChecksumOk(true);
     SctpShutdownCompleteChunk *scChunk = new SctpShutdownCompleteChunk();
     scChunk->setSctpChunkType(SHUTDOWN_COMPLETE);
     scChunk->setTBit(1);
     msg->setVTag(sctpmsg->getVTag());
     scChunk->setByteLength(SCTP_SHUTDOWN_ACK_LENGTH);
     msg->appendSctpChunks(scChunk);
     Packet *pkt = new Packet("SHUTDOWN_COMPLETE");
     auto addresses = pkt->addTag<L3AddressReq>();
     addresses->setSrcAddress(fromAddr);
     addresses->setDestAddress(toAddr);
     IL3AddressType *addressType = toAddr.getAddressType();
     pkt->addTag<DispatchProtocolReq>()->setProtocol(addressType->getNetworkProtocol());
     insertTransportProtocolHeader(pkt, Protocol::sctp, msg);
     send_to_ip(pkt);
 }
Referenced by handleMessage().
setInterfaceId()
void inet::sctp::Sctp::setInterfaceId (int id) inline
 { interfaceId = id; }
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE().
setRtoInitial()
void inet::sctp::Sctp::setRtoInitial (double rtoInitial) inline
 { socketOptions->rtoInitial = rtoInitial; }
Referenced by inet::sctp::SctpAssociation::processAppCommand().
setRtoMax()
void inet::sctp::Sctp::setRtoMax (double rtoMax) inline
 { socketOptions->rtoMax = rtoMax; }
Referenced by inet::sctp::SctpAssociation::processAppCommand().
setRtoMin()
void inet::sctp::Sctp::setRtoMin (double rtoMin) inline
 { socketOptions->rtoMin = rtoMin; }
Referenced by inet::sctp::SctpAssociation::processAppCommand().
setSocketOptions()
void inet::sctp::Sctp::setSocketOptions (SocketOptions * options) inline
 { socketOptions = options; }
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
updateSockPair()
void inet::sctp::Sctp::updateSockPair (SctpAssociation * assoc, L3Address localAddr, L3Address remoteAddr, int32_t localPort, int32_t remotePort)
To be called from SctpAssociation when socket pair changes.
 {
     SockPair key;
     EV_INFO << "updateSockPair:   localAddr: " << localAddr << "   remoteAddr=" << remoteAddr << "    localPort=" << localPort << " remotePort=" << remotePort << "\n";
     key.localAddr = (assoc->localAddr = localAddr);
     key.remoteAddr = (assoc->remoteAddr = remoteAddr);
     key.localPort = assoc->localPort = localPort;
     key.remotePort = assoc->remotePort = remotePort;
     // Do not update a sock pair that is already stored
     for (auto& elem : sctpAssocMap) {
         if (elem.second == assoc &&
             elem.first.localAddr == key.localAddr &&
             elem.first.remoteAddr == key.remoteAddr &&
             elem.first.localPort == key.localPort
             && elem.first.remotePort == key.remotePort)
             return;
     }
     for (auto i = sctpAssocMap.begin(); i != sctpAssocMap.end(); i++) {
         if (i->second == assoc) {
             sctpAssocMap.erase(i);
             break;
         }
     }
     EV_INFO << "updateSockPair assoc=" << assoc->assocId << "    localAddr=" << key.localAddr << "            remoteAddr=" << key.remoteAddr << "     localPort=" << key.localPort << "  remotePort=" << remotePort << "\n";
     sctpAssocMap[key] = assoc;
     sizeAssocMap = sctpAssocMap.size();
     EV_DEBUG << "assoc inserted in sctpAssocMap\n";
     printInfoAssocMap();
 }
Referenced by addForkedAssociation(), inet::sctp::SctpAssociation::process_ASSOCIATE(), inet::sctp::SctpAssociation::process_OPEN_PASSIVE(), and inet::sctp::SctpAssociation::processInitArrived().
Member Data Documentation
addIP
bool inet::sctp::Sctp::addIP
assocList
std::list<SctpAssociation *> inet::sctp::Sctp::assocList
Referenced by handleMessage(), removeAssociation(), inet::sctp::SctpAssociation::sendInit(), and inet::sctp::SctpAssociation::sendInitAck().
assocStatMap
AssocStatMap inet::sctp::Sctp::assocStatMap
Referenced by inet::sctp::SctpAssociation::addAuthChunkIfNecessary(), inet::sctp::SctpAssociation::createForwardTsnChunk(), inet::sctp::SctpAssociation::createSack(), finish(), inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::pathStatusIndication(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::process_SEND(), inet::sctp::SctpAssociation::process_TIMEOUT_RTX(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::processDataArrived(), inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processResetResponseArrived(), inet::sctp::SctpAssociation::processTimer(), inet::sctp::SctpAssociation::pushUlp(), removeAssociation(), inet::sctp::SctpAssociation::retransmitAsconf(), inet::sctp::SctpAssociation::retransmitCookieEcho(), inet::sctp::SctpAssociation::sendAbort(), inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest(), inet::sctp::SctpAssociation::sendAsconf(), inet::sctp::SctpAssociation::sendAsconfAck(), inet::sctp::SctpAssociation::sendCookieAck(), inet::sctp::SctpAssociation::sendCookieEcho(), inet::sctp::SctpAssociation::sendHeartbeat(), inet::sctp::SctpAssociation::sendHeartbeatAck(), inet::sctp::SctpAssociation::sendInvalidStreamError(), inet::sctp::SctpAssociation::sendOnPath(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendSack(), inet::sctp::SctpAssociation::sendShutdown(), inet::sctp::SctpAssociation::sendStreamResetRequest(), inet::sctp::SctpAssociation::stateEntered(), and ~Sctp().
auth
bool inet::sctp::Sctp::auth
Referenced by initialize(), inet::sctp::SctpAssociation::sendInit(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpAssociation::stateEntered().
crcMode
CrcMode inet::sctp::Sctp::crcMode = CRC_MODE_UNDEFINED
Referenced by initialize(), sendAbortFromMain(), sendShutdownCompleteFromMain(), and inet::sctp::SctpAssociation::sendToIP().
ift
ModuleRefByPar<IInterfaceTable> inet::sctp::Sctp::ift protected
Referenced by handleMessage(), and initialize().
interfaceId
int inet::sctp::Sctp::interfaceId = -1
nextEphemeralPort
uint16_t inet::sctp::Sctp::nextEphemeralPort protected
Referenced by getEphemeralPort(), and initialize().
numGapReports
uint32_t inet::sctp::Sctp::numGapReports
numPacketsDropped
uint32_t inet::sctp::Sctp::numPacketsDropped
Referenced by finish(), handleMessage(), and initialize().
numPacketsReceived
uint32_t inet::sctp::Sctp::numPacketsReceived
Referenced by finish(), handleMessage(), and initialize().
numPktDropReports
uint64_t inet::sctp::Sctp::numPktDropReports
Referenced by finish(), initialize(), and inet::sctp::SctpAssociation::sendPacketDrop().
pktdrop
bool inet::sctp::Sctp::pktdrop
Referenced by handleMessage(), initialize(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::processDataArrived(), inet::sctp::SctpAssociation::sendInit(), and inet::sctp::SctpAssociation::sendInitAck().
rt
ModuleRefByPar<IRoutingTable> inet::sctp::Sctp::rt protected
Referenced by handleMessage(), and initialize().
sackNow
bool inet::sctp::Sctp::sackNow
Referenced by inet::sctp::SctpAssociation::chunkReschedulingControl(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), initialize(), and inet::sctp::SctpAssociation::sendOnPath().
sctpAppAssocMap
SctpAppAssocMap inet::sctp::Sctp::sctpAppAssocMap
Referenced by addForkedAssociation(), findAssocForApp(), findAssocForFd(), getAssoc(), handleMessage(), removeAssociation(), and ~Sctp().
sctpAssocMap
SctpAssocMap inet::sctp::Sctp::sctpAssocMap
Referenced by addForkedAssociation(), addLocalAddress(), addLocalAddressToAllRemoteAddresses(), addRemoteAddress(), findAssocForMessage(), finish(), handleMessage(), printInfoAssocMap(), removeAssociation(), removeLocalAddressFromAllRemoteAddresses(), removeRemoteAddressFromAllAssociations(), and updateSockPair().
sctpVTagMap
SctpVTagMap inet::sctp::Sctp::sctpVTagMap
Referenced by findAssocWithVTag(), printVTagMap(), inet::sctp::SctpAssociation::stateEntered(), and ~Sctp().
sizeAssocMap
int32_t inet::sctp::Sctp::sizeAssocMap protected
Referenced by addForkedAssociation(), addLocalAddress(), addLocalAddressToAllRemoteAddresses(), addRemoteAddress(), initialize(), printInfoAssocMap(), removeAssociation(), removeLocalAddressFromAllRemoteAddresses(), removeRemoteAddressFromAllAssociations(), and updateSockPair().
socketOptions
SocketOptions* inet::sctp::Sctp::socketOptions
Referenced by finish(), and handleMessage().
testTimeout
simtime_t inet::sctp::Sctp::testTimeout
Referenced by initialize(), and inet::sctp::SctpAssociation::SctpAssociation().
udpSocket
UdpSocket inet::sctp::Sctp::udpSocket
Referenced by bindPortForUDP().
udpSockId
int inet::sctp::Sctp::udpSockId
Referenced by bindPortForUDP().
The documentation for this class was generated from the following files:
Sctp.h
Sctp.cc