INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRecipientBlockAckAgreementHandler Class Reference
inet::ieee80211::IRecipientBlockAckAgreementHandler Class Reference abstract
#include <IRecipientBlockAckAgreementHandler.h>
Public Member Functions
virtual ~IRecipientBlockAckAgreementHandler ()
virtual void processTransmittedAddbaResp (const Ptr< const Ieee80211AddbaResponse > &addbaResp, IBlockAckAgreementHandlerCallback *callback)=0
virtual void processReceivedAddbaRequest (const Ptr< const Ieee80211AddbaRequest > &addbaRequest, IRecipientBlockAckAgreementPolicy *blockAckAgreementPolicy, IProcedureCallback *callback)=0
virtual void processReceivedDelba (const Ptr< const Ieee80211Delba > &delba, IRecipientBlockAckAgreementPolicy *blockAckAgreementPolicy)=0
virtual void processTransmittedDelba (const Ptr< const Ieee80211Delba > &delba)=0
virtual void qosFrameReceived (const Ptr< const Ieee80211DataHeader > &qosHeader, IBlockAckAgreementHandlerCallback *callback)=0
virtual void blockAckAgreementExpired (IProcedureCallback *procedureCallback, IBlockAckAgreementHandlerCallback *agreementHandlerCallback)=0
virtual RecipientBlockAckAgreement * getAgreement (Tid tid, MacAddress originatorAddr)=0
Constructor & Destructor Documentation
~IRecipientBlockAckAgreementHandler()
virtual inet::ieee80211::IRecipientBlockAckAgreementHandler::~IRecipientBlockAckAgreementHandler () inline virtual
 {}
Member Function Documentation
blockAckAgreementExpired()
virtual void inet::ieee80211::IRecipientBlockAckAgreementHandler::blockAckAgreementExpired (IProcedureCallback * procedureCallback, IBlockAckAgreementHandlerCallback * agreementHandlerCallback) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
getAgreement()
virtual RecipientBlockAckAgreement* inet::ieee80211::IRecipientBlockAckAgreementHandler::getAgreement (Tid tid, MacAddress originatorAddr) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
Referenced by inet::ieee80211::RecipientQosMacDataService::controlFrameReceived(), inet::ieee80211::RecipientQosMacDataService::dataFrameReceived(), and inet::ieee80211::RecipientBlockAckProcedure::processReceivedBlockAckReq().
processReceivedAddbaRequest()
virtual void inet::ieee80211::IRecipientBlockAckAgreementHandler::processReceivedAddbaRequest (const Ptr< const Ieee80211AddbaRequest > & addbaRequest, IRecipientBlockAckAgreementPolicy * blockAckAgreementPolicy, IProcedureCallback * callback) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
processReceivedDelba()
virtual void inet::ieee80211::IRecipientBlockAckAgreementHandler::processReceivedDelba (const Ptr< const Ieee80211Delba > & delba, IRecipientBlockAckAgreementPolicy * blockAckAgreementPolicy) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
processTransmittedAddbaResp()
virtual void inet::ieee80211::IRecipientBlockAckAgreementHandler::processTransmittedAddbaResp (const Ptr< const Ieee80211AddbaResponse > & addbaResp, IBlockAckAgreementHandlerCallback * callback) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
processTransmittedDelba()
virtual void inet::ieee80211::IRecipientBlockAckAgreementHandler::processTransmittedDelba (const Ptr< const Ieee80211Delba > & delba) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
qosFrameReceived()
virtual void inet::ieee80211::IRecipientBlockAckAgreementHandler::qosFrameReceived (const Ptr< const Ieee80211DataHeader > & qosHeader, IBlockAckAgreementHandlerCallback * callback) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementHandler.
The documentation for this class was generated from the following file:
IRecipientBlockAckAgreementHandler.h