INET Framework for OMNeT++/OMNEST: inet::IPrintableObject Class Reference
inet::IPrintableObject Class Reference
This purely virtual interface provides an abstraction for printable objects.
#include <IPrintableObject.h>
Public Types
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Detailed Description
This purely virtual interface provides an abstraction for printable objects.
Member Enumeration Documentation
PrintFlag
enum inet::IPrintableObject::PrintFlag
Enumerator
PRINT_FLAG_FORMATTED
PRINT_FLAG_MULTILINE
                    {
         PRINT_FLAG_FORMATTED = (1 << 0),
         PRINT_FLAG_MULTILINE = (1 << 1),
     };
PrintLevel
enum inet::IPrintableObject::PrintLevel
Enumerator
PRINT_LEVEL_TRACE
PRINT_LEVEL_DEBUG
PRINT_LEVEL_DETAIL
PRINT_LEVEL_INFO
PRINT_LEVEL_COMPLETE
                     {
         PRINT_LEVEL_TRACE,
         PRINT_LEVEL_DEBUG,
         PRINT_LEVEL_DETAIL,
         PRINT_LEVEL_INFO,
         PRINT_LEVEL_COMPLETE = INT_MIN
     };
Constructor & Destructor Documentation
~IPrintableObject()
virtual inet::IPrintableObject::~IPrintableObject () inline virtual
 {}
Member Function Documentation
getCompleteStringRepresentation()
virtual std::string inet::IPrintableObject::getCompleteStringRepresentation (int evFlags = 0) const inline virtual
{
         std::stringstream s;
         printToStream(s, PRINT_LEVEL_COMPLETE, evFlags);
         return s.str();
     }
Referenced by inet::physicallayer::Radio::initialize(), and inet::physicallayer::RadioMedium::initialize().
getDebugStringRepresentation()
virtual std::string inet::IPrintableObject::getDebugStringRepresentation (int evFlags = 0) const inline virtual
{
         std::stringstream s;
         printToStream(s, PRINT_LEVEL_DEBUG, evFlags);
         return s.str();
     }
getDetailStringRepresentation()
virtual std::string inet::IPrintableObject::getDetailStringRepresentation (int evFlags = 0) const inline virtual
{
         std::stringstream s;
         printToStream(s, PRINT_LEVEL_DETAIL, evFlags);
         return s.str();
     }
getInfoStringRepresentation()
virtual std::string inet::IPrintableObject::getInfoStringRepresentation (int evFlags = 0) const inline virtual
{
         std::stringstream s;
         printToStream(s, PRINT_LEVEL_INFO, evFlags);
         return s.str();
     }
getTraceStringRepresentation()
virtual std::string inet::IPrintableObject::getTraceStringRepresentation (int evFlags = 0) const inline virtual
{
         std::stringstream s;
         printToStream(s, PRINT_LEVEL_TRACE, evFlags);
         return s.str();
     }
printToStream()
virtual std::ostream& inet::IPrintableObject::printToStream (std::ostream & stream, int level, int evFlags = 0) const inline virtual
Prints this object to the provided output stream.
Reimplemented in inet::Packet, inet::Chunk, inet::physicallayer::RadioMedium, inet::physicallayer::Radio, inet::physicallayer::ConvolutionalCoder, inet::physicallayer::Ieee80211OfdmMode, inet::Message, inet::SequenceChunk, inet::physicallayer::MediumLimitCache, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssMode, inet::physicallayer::Ieee80211IrMode, inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::Ieee80211DsssMode, inet::physicallayer::Ieee80211LayeredOfdmTransmitter, inet::physicallayer::Ieee80211FhssMode, inet::physicallayer::DielectricObstacleLoss, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::UwbIrStochasticPathLoss, inet::physicallayer::SuiPathLoss, inet::physicallayer::Ieee80211OfdmPreambleMode, inet::physicallayer::Ieee80211YansErrorModel, inet::physicallayer::Ieee802154UwbIrTransmitter, inet::physicallayer::DimensionalTransmitterBase, inet::physicallayer::FreeSpacePathLoss, inet::physicallayer::VectorCommunicationCache, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::RicianFading, inet::physicallayer::NakagamiFading, inet::physicallayer::TwoRayGroundReflection, inet::physicallayer::NeighborListNeighborCache, inet::physicallayer::QuadTreeNeighborCache, inet::physicallayer::IdealObstacleLoss, inet::physicallayer::RayleighFading, inet::physicallayer::ApskLayeredTransmitter, inet::physicallayer::GridNeighborCache, inet::physicallayer::InterpolatingAntenna, inet::physicallayer::MapCommunicationCache, inet::physicallayer::Ieee80211NistErrorModel, inet::physicallayer::ReferenceCommunicationCache, inet::physicallayer::TransmissionBase, inet::physicallayer::Ieee80211OfdmDecoder, inet::physicallayer::Ieee80211ModeSet, inet::physicallayer::AxiallySymmetricAntenna, inet::physicallayer::ParabolicAntenna, inet::physicallayer::Ieee80211OfdmModulator, inet::physicallayer::ApskEncoder, inet::physicallayer::NarrowbandSignalAnalogModel, inet::physicallayer::CosineAntenna, inet::physicallayer::DipoleAntenna, inet::physicallayer::Ieee80211OfdmErrorModel, inet::physicallayer::Ieee80211DsssOfdmMode, inet::physicallayer::ConstantGainAntenna, inet::physicallayer::Ieee80211OfdmDecoderModule, inet::physicallayer::Ieee80211OfdmDemodulator, inet::physicallayer::UnitDiskReception, inet::physicallayer::FlatReceiverBase, inet::physicallayer::ReceptionBase, inet::physicallayer::LogNormalShadowing, inet::physicallayer::AdditiveScrambler, inet::physicallayer::WirelessSignal, inet::physicallayer::FlatTransmitterBase, inet::physicallayer::ConvolutionalCode, inet::physicallayer::Ieee80211OfdmEncoder, inet::physicallayer::Ieee80211TransmitterBase, inet::physicallayer::UnitDiskTransmitter, inet::physicallayer::LayeredReception, inet::physicallayer::LayeredReceptionResult, inet::physicallayer::Ieee80211OfdmInterleaver, inet::physicallayer::Ieee80211ReceiverBase, inet::physicallayer::Ieee802154UwbIrReceiver, inet::physicallayer::ApskDecoder, inet::physicallayer::LayeredTransmission, inet::physicallayer::DimensionalSnir, inet::physicallayer::NarrowbandTransmitterBase, inet::physicallayer::SnirReceiverBase, inet::physicallayer::Qam1024Modulation, inet::physicallayer::Qam16Modulation, inet::physicallayer::Qam256Modulation, inet::physicallayer::Qam64Modulation, inet::physicallayer::Arrival, inet::physicallayer::Ieee80211OfdmEncoderModule, inet::physicallayer::ApskDemodulator, inet::physicallayer::ApskModulator, inet::physicallayer::StochasticErrorModel, inet::physicallayer::BpskModulation, inet::physicallayer::QpskModulation, inet::physicallayer::ScalarSnir, inet::physicallayer::IsotropicAntenna, inet::physicallayer::ApskModulationBase, inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::BreakpointPathLoss, inet::physicallayer::SignalBitModel, inet::physicallayer::ApskCode, inet::physicallayer::ConstantSpeedPropagation, inet::physicallayer::Ieee80211OfdmDemodulatorModule, inet::physicallayer::Ieee80211BerTableErrorModel, inet::physicallayer::Ieee80211UnitDiskTransmitter, inet::physicallayer::NoiseDimensionalTransmitter, inet::physicallayer::UnitDiskReceiver, inet::physicallayer::UnitDiskTransmission, inet::physicallayer::DimensionalBackgroundNoise, inet::physicallayer::PropagationBase, inet::physicallayer::StochasticLayeredErrorModel, inet::physicallayer::MfskModulation, inet::physicallayer::AdditiveScramblerModule, inet::physicallayer::SignalSymbolModel, inet::physicallayer::Ieee80211OfdmInterleaverModule, inet::physicallayer::Ieee80211OfdmModulatorModule, inet::physicallayer::AntennaBase, inet::physicallayer::ListeningBase, inet::physicallayer::NarrowbandNoiseBase, inet::physicallayer::NarrowbandTransmissionBase, inet::physicallayer::MaskModulation, inet::physicallayer::MpskModulation, inet::physicallayer::MqamModulation, inet::physicallayer::ConvolutionalCoderModule, inet::physicallayer::Ieee80211OfdmCode, inet::physicallayer::Ieee80211UnitDiskReceiver, inet::physicallayer::DimensionalSignalAnalogModel, inet::physicallayer::DimensionalNoise, inet::physicallayer::DimensionalTransmission, inet::physicallayer::IsotropicDimensionalBackgroundNoise, inet::physicallayer::SnirBase, inet::physicallayer::ConstantTimePropagation, inet::physicallayer::BandListening, inet::physicallayer::ReceptionDecision, inet::physicallayer::ReceptionResult, inet::physicallayer::Ieee80211OfdmModulation, inet::physicallayer::Ieee80211DimensionalTransmitter, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::IsotropicScalarBackgroundNoise, inet::physicallayer::FlatTransmissionBase, inet::physicallayer::NarrowbandReceptionBase, inet::physicallayer::SignalSampleModel, inet::physicallayer::Ieee80211DimensionalReceiver, inet::physicallayer::Ieee80211ScalarReceiver, inet::physicallayer::Ieee80211TransmissionBase, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, inet::physicallayer::Ieee802154NarrowbandScalarReceiver, inet::physicallayer::Signal, inet::physicallayer::ApskDimensionalTransmitter, inet::physicallayer::SignalAnalogModel, inet::physicallayer::ScalarNoise, inet::physicallayer::ScalarReception, inet::physicallayer::NoiseBase, inet::physicallayer::AdditiveScrambling, inet::physicallayer::Interference, inet::physicallayer::Ieee80211OfdmInterleaving, inet::physicallayer::Ieee80211Channel, inet::physicallayer::ScalarSignalAnalogModel, inet::physicallayer::ScalarTransmission, inet::physicallayer::_16PpmModulation, inet::physicallayer::_2GfskModulation, inet::physicallayer::_4GfskModulation, inet::physicallayer::_4PpmModulation, inet::physicallayer::DbpskModulation, inet::physicallayer::DqpskModulation, inet::physicallayer::SignalPacketModel, inet::physicallayer::ListeningDecision, inet::physicallayer::Ieee80211ErpOfdmMode, inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter, inet::physicallayer::UnitDiskListening, inet::physicallayer::UnitDiskNoise, inet::physicallayer::Ieee80211UnitDiskTransmission, inet::physicallayer::ApskErrorModel, inet::physicallayer::Ieee80211LayeredTransmission, inet::physicallayer::IIeee80211Band, inet::physicallayer::Ieee80211DimensionalTransmission, inet::physicallayer::Ieee80211ScalarTransmission, inet::physicallayer::UnitDiskAnalogModel, inet::physicallayer::ApskLayeredErrorModel, inet::physicallayer::ApskDimensionalTransmission, inet::physicallayer::ApskScalarTransmission, inet::physicallayer::ApskScalarTransmitter, inet::physicallayer::LayeredDimensionalAnalogModel, inet::physicallayer::LayeredScalarAnalogModel, inet::physicallayer::Ieee80211ScalarTransmitter, inet::physicallayer::Ieee802154NarrowbandScalarTransmitter, inet::physicallayer::UnitDiskSnir, inet::physicallayer::DimensionalAnalogModel, inet::physicallayer::ScalarAnalogModel, inet::TagBase, and inet::physicallayer::TwoRayInterference.
{
         return stream << EV_FAINT << "<object@" << static_cast<const void *>(this) << ">" << EV_NORMAL;
     }
Referenced by inet::physicallayer::DimensionalAnalogModel::printToStream(), inet::physicallayer::LayeredDimensionalAnalogModel::printToStream(), and inet::physicallayer::NoiseDimensionalTransmitter::printToStream().
printToString() [1/2]
virtual std::string inet::IPrintableObject::printToString () const inline virtual
{
         return "";
     }
printToString() [2/2]
virtual std::string inet::IPrintableObject::printToString (int level, int evFlags = 0) const inline virtual
{
         std::stringstream s;
         printToStream(s, level, evFlags);
         return s.str();
     }
The documentation for this class was generated from the following file:
IPrintableObject.h