INET Framework for OMNeT++/OMNEST: inet::SettableClock Class Reference
inet::SettableClock Class Reference
#include <SettableClock.h>
Public Member Functions
virtual void setClockTime (clocktime_t time, bool resetOscillator=true)
Public Member Functions inherited from inet::OscillatorBasedClock
virtual ~OscillatorBasedClock ()
virtual clocktime_t computeClockTimeFromSimTime (simtime_t t) const override
Returns the clock time for the specified future simulation time according to the current state of the clock.
virtual simtime_t computeSimTimeFromClockTime (clocktime_t t) const override
Returns the simulation time (first moment) for the specified future clock time according to the current state of the clock.
virtual void scheduleClockEventAt (clocktime_t t, ClockEvent *event) override
Schedules an event to be delivered to the caller module (i.e.
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *event) override
Schedules an event to be delivered to the caller module (i.e.
virtual ClockEvent * cancelClockEvent (ClockEvent *event) override
Cancels a previously scheduled clock event.
virtual void handleClockEvent (ClockEvent *event) override
Called by the clock event to be executed in the context of this clock.
virtual const char * resolveDirective (char directive) const override
virtual void receiveSignal (cComponent *source, int signal, cObject *obj, cObject *details) override
Public Member Functions inherited from inet::ClockBase
virtual clocktime_t getClockTime () const override
Returns the current clock time.
Public Member Functions inherited from inet::IClock
virtual ~IClock ()
Public Member Functions inherited from inet::IScriptable
virtual ~IScriptable ()
Protected Member Functions
virtual void initialize (int stage) override
virtual OverdueClockEventHandlingMode getOverdueClockEventHandlingMode (ClockEvent *event) const
virtual simtime_t handleOverdueClockEvent (ClockEvent *event, simtime_t t)
virtual void processCommand (const cXMLElement &node) override
Called by ScenarioManager whenever a script command needs to be carried out by the module.
Protected Member Functions inherited from inet::ClockBase
virtual int numInitStages () const override
virtual void finish () override
virtual void refreshDisplay () const override
virtual void updateDisplayString () const
cSimpleModule * getTargetModule () const
Protected Attributes
OverdueClockEventHandlingMode defaultOverdueClockEventHandlingMode = UNSPECIFIED
Protected Attributes inherited from inet::OscillatorBasedClock
IOscillator * oscillator = nullptr
int64_t(* roundingFunction)(int64_t, int64_t) = nullptr
int64_t originClockTick = -1
std::vector< ClockEvent * > events
Protected Attributes inherited from inet::ClockBase
clocktime_t clockEventTime = -1
const char * displayStringTextFormat = nullptr
Additional Inherited Members
Static Public Attributes inherited from inet::ClockBase
static simsignal_t timeChangedSignal = cComponent::registerSignal("timeChanged")
Member Function Documentation
getOverdueClockEventHandlingMode()
OverdueClockEventHandlingMode inet::SettableClock::getOverdueClockEventHandlingMode (ClockEvent * event) const protected virtual
 {
     auto mode = event->getOverdueClockEventHandlingMode();
     if (mode == UNSPECIFIED)
         return defaultOverdueClockEventHandlingMode;
     else
         return mode;
 }
Referenced by handleOverdueClockEvent().
handleOverdueClockEvent()
simtime_t inet::SettableClock::handleOverdueClockEvent (ClockEvent * event, simtime_t t) protected virtual
 {
     switch (getOverdueClockEventHandlingMode(event)) {
         case EXECUTE:
             EV_WARN << "Scheduling overdue clock event " << event->getName() << " to current simulation time.\n";
             return t;
         case SKIP:
             EV_WARN << "Skipping overdue clock event " << event->getName() << ".\n";
             cancelClockEvent(event);
             return -1;
         case ERROR:
             throw cRuntimeError("Clock event is overdue");
         default:
             throw cRuntimeError("Unknown overdue clock event handling mode");
     }
 }
Referenced by setClockTime().
initialize()
void inet::SettableClock::initialize (int stage) override protected virtual
Reimplemented from inet::OscillatorBasedClock.
 {
     OscillatorBasedClock::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         const char *text = par("defaultOverdueClockEventHandlingMode");
         if (!strcmp(text, "execute"))
             defaultOverdueClockEventHandlingMode = EXECUTE;
         else if (!strcmp(text, "skip"))
             defaultOverdueClockEventHandlingMode = SKIP;
         else if (!strcmp(text, "error"))
             defaultOverdueClockEventHandlingMode = ERROR;
         else
             throw cRuntimeError("Unknown defaultOverdueClockEventHandlingMode parameter value");
     }
 }
processCommand()
void inet::SettableClock::processCommand (const cXMLElement & node) override protected virtual
Called by ScenarioManager whenever a script command needs to be carried out by the module.
The command is represented by the XML element or element tree. The command name can be obtained as:
const char *command = node->getTagName()
Parameters are XML attributes, e.g. a "neighbour" parameter can be retrieved as:
const char *attr = node->getAttribute("neighbour")
More complex input can be passed in child elements.
See also
cXMLElement
Implements inet::IScriptable.
 {
     Enter_Method("processCommand");
     if (!strcmp(node.getTagName(), "set-clock")) {
         clocktime_t time = ClockTime::parse(xmlutils::getMandatoryFilledAttribute(node, "time"));
         bool resetOscillator = xmlutils::getAttributeBoolValue(&node, "reset-oscillator", true);
         setClockTime(time, resetOscillator);
     }
     else
         throw cRuntimeError("Invalid command: %s", node.getTagName());
 }
setClockTime()
void inet::SettableClock::setClockTime (clocktime_t time, bool resetOscillator = true) virtual
 {
     Enter_Method("setClockTime");
     clocktime_t oldClockTime = getClockTime();
     if (newClockTime != oldClockTime) {
         emit(timeChangedSignal, oldClockTime.asSimTime());
         if (resetOscillator) {
             if (auto constantDriftOscillator = dynamic_cast<ConstantDriftOscillator *>(oscillator))
                 constantDriftOscillator->setTickOffset(0);
         }
         simtime_t currentSimTime = simTime();
         EV_DEBUG << "Setting clock time from " << oldClockTime << " to " << newClockTime << " at simtime " << currentSimTime << ".\n";
         int64_t numTicks = oscillator->computeTicksForInterval(currentSimTime - oscillator->getComputationOrigin());
         originClockTick = newClockTime.raw() / oscillator->getNominalTickLength().raw() - numTicks;
         ASSERT(newClockTime == getClockTime());
         clocktime_t clockDelta = newClockTime - oldClockTime;
         for (auto event : events) {
             if (event->getRelative())
                 // NOTE: the simulation time of event execution is not affected
                 event->setArrivalClockTime(event->getArrivalClockTime() + clockDelta);
             else {
                 clocktime_t arrivalClockTime = event->getArrivalClockTime();
                 bool isOverdue = arrivalClockTime < newClockTime;
                 simtime_t arrivalSimTime = isOverdue ? -1 : computeSimTimeFromClockTime(arrivalClockTime);
                 if (isOverdue || arrivalSimTime < currentSimTime)
                     arrivalSimTime = handleOverdueClockEvent(event, currentSimTime);
                 if (event->isScheduled()) {
                     cSimpleModule *targetModule = check_and_cast<cSimpleModule *>(event->getArrivalModule());
                     cContextSwitcher contextSwitcher(targetModule);
                     targetModule->rescheduleAt(arrivalSimTime, event);
                 }
             }
         }
         emit(timeChangedSignal, newClockTime.asSimTime());
     }
 }
Referenced by processCommand().
Member Data Documentation
defaultOverdueClockEventHandlingMode
OverdueClockEventHandlingMode inet::SettableClock::defaultOverdueClockEventHandlingMode = UNSPECIFIED protected
Referenced by getOverdueClockEventHandlingMode(), and initialize().
The documentation for this class was generated from the following files:
SettableClock.h
SettableClock.cc