INET Framework for OMNeT++/OMNEST: inet::sctp::SctpSackChunk Class Reference
inet::sctp::SctpSackChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:161 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpSackChunk (const char *name=nullptr)
SctpSackChunk (const SctpSackChunk &other)
virtual ~SctpSackChunk ()
SctpSackChunk & operator= (const SctpSackChunk &other)
virtual SctpSackChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getCumTsnAck () const
virtual void setCumTsnAck (uint32_t cumTsnAck)
virtual uint32_t getA_rwnd () const
virtual void setA_rwnd (uint32_t a_rwnd)
virtual uint16_t getNumGaps () const
virtual void setNumGaps (uint16_t numGaps)
virtual uint16_t getNumNrGaps () const
virtual void setNumNrGaps (uint16_t numNrGaps)
virtual uint16_t getNumDupTsns () const
virtual void setNumDupTsns (uint16_t numDupTsns)
virtual bool isNrSack () const
virtual void setIsNrSack (bool isNrSack)
virtual void setGapStartArraySize (size_t size)
virtual size_t getGapStartArraySize () const
virtual uint32_t getGapStart (size_t k) const
virtual void setGapStart (size_t k, uint32_t gapStart)
virtual void insertGapStart (size_t k, uint32_t gapStart)
void insertGapStart (uint32_t gapStart)
virtual void appendGapStart (uint32_t gapStart)
virtual void eraseGapStart (size_t k)
virtual void setGapStopArraySize (size_t size)
virtual size_t getGapStopArraySize () const
virtual uint32_t getGapStop (size_t k) const
virtual void setGapStop (size_t k, uint32_t gapStop)
virtual void insertGapStop (size_t k, uint32_t gapStop)
void insertGapStop (uint32_t gapStop)
virtual void appendGapStop (uint32_t gapStop)
virtual void eraseGapStop (size_t k)
virtual void setDupTsnsArraySize (size_t size)
virtual size_t getDupTsnsArraySize () const
virtual uint32_t getDupTsns (size_t k) const
virtual void setDupTsns (size_t k, uint32_t dupTsns)
virtual void insertDupTsns (size_t k, uint32_t dupTsns)
void insertDupTsns (uint32_t dupTsns)
virtual void appendDupTsns (uint32_t dupTsns)
virtual void eraseDupTsns (size_t k)
virtual uint32_t getSackSeqNum () const
virtual void setSackSeqNum (uint32_t sackSeqNum)
virtual void setNrGapStartArraySize (size_t size)
virtual size_t getNrGapStartArraySize () const
virtual uint32_t getNrGapStart (size_t k) const
virtual void setNrGapStart (size_t k, uint32_t nrGapStart)
virtual void insertNrGapStart (size_t k, uint32_t nrGapStart)
void insertNrGapStart (uint32_t nrGapStart)
virtual void appendNrGapStart (uint32_t nrGapStart)
virtual void eraseNrGapStart (size_t k)
virtual void setNrGapStopArraySize (size_t size)
virtual size_t getNrGapStopArraySize () const
virtual uint32_t getNrGapStop (size_t k) const
virtual void setNrGapStop (size_t k, uint32_t nrGapStop)
virtual void insertNrGapStop (size_t k, uint32_t nrGapStop)
void insertNrGapStop (uint32_t nrGapStop)
virtual void appendNrGapStop (uint32_t nrGapStop)
virtual void eraseNrGapStop (size_t k)
virtual uint32_t getMsg_rwnd () const
virtual void setMsg_rwnd (uint32_t msg_rwnd)
virtual uint8_t getDacPacketsRcvd () const
virtual void setDacPacketsRcvd (uint8_t dacPacketsRcvd)
virtual bool getNrSubtractRGaps () const
virtual void setNrSubtractRGaps (bool nrSubtractRGaps)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpSackChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint32_t cumTsnAck = 0
uint32_t a_rwnd = 0
uint16_t numGaps = 0
uint16_t numNrGaps = 0
uint16_t numDupTsns = 0
bool isNrSack_ = false
uint32_t * gapStart = nullptr
size_t gapStart_arraysize = 0
uint32_t * gapStop = nullptr
size_t gapStop_arraysize = 0
uint32_t * dupTsns = nullptr
size_t dupTsns_arraysize = 0
uint32_t sackSeqNum = 0
uint32_t * nrGapStart = nullptr
size_t nrGapStart_arraysize = 0
uint32_t * nrGapStop = nullptr
size_t nrGapStop_arraysize = 0
uint32_t msg_rwnd = 0
uint8_t dacPacketsRcvd = 0
bool nrSubtractRGaps = false
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpSackChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:161 by opp_msgtool.
class SctpSackChunk extends SctpChunk
{
    // Cumulative TSN Ack
    uint32_t cumTsnAck;
    // Advertised Receiver Window Credit
    uint32_t a_rwnd;
    // Number of Gap Ack Blocks
    uint16_t numGaps;
    // Number of Non-Revokable Gap Ack Blocks
    uint16_t numNrGaps;
    // Number of Duplicate TSNs
    uint16_t numDupTsns;
    // Start and End of Gap Ack Blocks
    bool isNrSack;
    uint32_t gapStart[];
    uint32_t gapStop[];
    uint32_t dupTsns[];
    uint32_t sackSeqNum = 0;
    uint32_t nrGapStart[];
    uint32_t nrGapStop[];
    uint32_t msg_rwnd;
    uint8_t dacPacketsRcvd = 0;
    bool nrSubtractRGaps = false;
}
Constructor & Destructor Documentation
SctpSackChunk() [1/2]
inet::sctp::SctpSackChunk::SctpSackChunk (const char * name = nullptr)
SctpSackChunk() [2/2]
inet::sctp::SctpSackChunk::SctpSackChunk (const SctpSackChunk & other)
~SctpSackChunk()
virtual inet::sctp::SctpSackChunk::~SctpSackChunk () virtual
Member Function Documentation
appendDupTsns()
virtual void inet::sctp::SctpSackChunk::appendDupTsns (uint32_t dupTsns) virtual
appendGapStart()
virtual void inet::sctp::SctpSackChunk::appendGapStart (uint32_t gapStart) virtual
appendGapStop()
virtual void inet::sctp::SctpSackChunk::appendGapStop (uint32_t gapStop) virtual
appendNrGapStart()
virtual void inet::sctp::SctpSackChunk::appendNrGapStart (uint32_t nrGapStart) virtual
appendNrGapStop()
virtual void inet::sctp::SctpSackChunk::appendNrGapStop (uint32_t nrGapStop) virtual
copy()
void inet::sctp::SctpSackChunk::copy (const SctpSackChunk & other) private
dup()
virtual SctpSackChunk* inet::sctp::SctpSackChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpSackChunk(*this);}
eraseDupTsns()
virtual void inet::sctp::SctpSackChunk::eraseDupTsns (size_t k) virtual
eraseGapStart()
virtual void inet::sctp::SctpSackChunk::eraseGapStart (size_t k) virtual
eraseGapStop()
virtual void inet::sctp::SctpSackChunk::eraseGapStop (size_t k) virtual
eraseNrGapStart()
virtual void inet::sctp::SctpSackChunk::eraseNrGapStart (size_t k) virtual
eraseNrGapStop()
virtual void inet::sctp::SctpSackChunk::eraseNrGapStop (size_t k) virtual
getA_rwnd()
virtual uint32_t inet::sctp::SctpSackChunk::getA_rwnd () const virtual
Referenced by inet::sctp::SctpAssociation::createSack(), inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getCumTsnAck()
virtual uint32_t inet::sctp::SctpSackChunk::getCumTsnAck () const virtual
Referenced by inet::sctp::SctpAssociation::createSack(), inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getDacPacketsRcvd()
virtual uint8_t inet::sctp::SctpSackChunk::getDacPacketsRcvd () const virtual
Referenced by inet::sctp::SctpAssociation::handleChunkReportedAsMissing().
getDupTsns()
virtual uint32_t inet::sctp::SctpSackChunk::getDupTsns (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getDupTsnsArraySize()
virtual size_t inet::sctp::SctpSackChunk::getDupTsnsArraySize () const virtual
getGapStart()
virtual uint32_t inet::sctp::SctpSackChunk::getGapStart (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getGapStartArraySize()
virtual size_t inet::sctp::SctpSackChunk::getGapStartArraySize () const virtual
getGapStop()
virtual uint32_t inet::sctp::SctpSackChunk::getGapStop (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getGapStopArraySize()
virtual size_t inet::sctp::SctpSackChunk::getGapStopArraySize () const virtual
getMsg_rwnd()
virtual uint32_t inet::sctp::SctpSackChunk::getMsg_rwnd () const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived().
getNrGapStart()
virtual uint32_t inet::sctp::SctpSackChunk::getNrGapStart (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getNrGapStartArraySize()
virtual size_t inet::sctp::SctpSackChunk::getNrGapStartArraySize () const virtual
getNrGapStop()
virtual uint32_t inet::sctp::SctpSackChunk::getNrGapStop (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getNrGapStopArraySize()
virtual size_t inet::sctp::SctpSackChunk::getNrGapStopArraySize () const virtual
getNrSubtractRGaps()
virtual bool inet::sctp::SctpSackChunk::getNrSubtractRGaps () const virtual
Referenced by inet::sctp::SctpAssociation::createSack(), and inet::sctp::SctpAssociation::processSackArrived().
getNumDupTsns()
virtual uint16_t inet::sctp::SctpSackChunk::getNumDupTsns () const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getNumGaps()
virtual uint16_t inet::sctp::SctpSackChunk::getNumGaps () const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getNumNrGaps()
virtual uint16_t inet::sctp::SctpSackChunk::getNumNrGaps () const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSackSeqNum()
virtual uint32_t inet::sctp::SctpSackChunk::getSackSeqNum () const virtual
Referenced by inet::sctp::SctpAssociation::processSackArrived().
insertDupTsns() [1/2]
virtual void inet::sctp::SctpSackChunk::insertDupTsns (size_t k, uint32_t dupTsns) virtual
insertDupTsns() [2/2]
void inet::sctp::SctpSackChunk::insertDupTsns (uint32_t dupTsns) inline
 {appendDupTsns(dupTsns);}
insertGapStart() [1/2]
virtual void inet::sctp::SctpSackChunk::insertGapStart (size_t k, uint32_t gapStart) virtual
insertGapStart() [2/2]
void inet::sctp::SctpSackChunk::insertGapStart (uint32_t gapStart) inline
 {appendGapStart(gapStart);}
insertGapStop() [1/2]
virtual void inet::sctp::SctpSackChunk::insertGapStop (size_t k, uint32_t gapStop) virtual
insertGapStop() [2/2]
void inet::sctp::SctpSackChunk::insertGapStop (uint32_t gapStop) inline
 {appendGapStop(gapStop);}
insertNrGapStart() [1/2]
virtual void inet::sctp::SctpSackChunk::insertNrGapStart (size_t k, uint32_t nrGapStart) virtual
insertNrGapStart() [2/2]
void inet::sctp::SctpSackChunk::insertNrGapStart (uint32_t nrGapStart) inline
 {appendNrGapStart(nrGapStart);}
insertNrGapStop() [1/2]
virtual void inet::sctp::SctpSackChunk::insertNrGapStop (size_t k, uint32_t nrGapStop) virtual
insertNrGapStop() [2/2]
void inet::sctp::SctpSackChunk::insertNrGapStop (uint32_t nrGapStop) inline
 {appendNrGapStop(nrGapStop);}
isNrSack()
virtual bool inet::sctp::SctpSackChunk::isNrSack () const virtual
operator=()
SctpSackChunk& inet::sctp::SctpSackChunk::operator= (const SctpSackChunk & other)
operator==()
bool inet::sctp::SctpSackChunk::operator== (const SctpSackChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpSackChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpSackChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setA_rwnd()
virtual void inet::sctp::SctpSackChunk::setA_rwnd (uint32_t a_rwnd) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setCumTsnAck()
virtual void inet::sctp::SctpSackChunk::setCumTsnAck (uint32_t cumTsnAck) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setDacPacketsRcvd()
virtual void inet::sctp::SctpSackChunk::setDacPacketsRcvd (uint8_t dacPacketsRcvd) virtual
Referenced by inet::sctp::SctpAssociation::sendOnPath().
setDupTsns()
virtual void inet::sctp::SctpSackChunk::setDupTsns (size_t k, uint32_t dupTsns) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setDupTsnsArraySize()
virtual void inet::sctp::SctpSackChunk::setDupTsnsArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setGapStart()
virtual void inet::sctp::SctpSackChunk::setGapStart (size_t k, uint32_t gapStart) virtual
setGapStartArraySize()
virtual void inet::sctp::SctpSackChunk::setGapStartArraySize (size_t size) virtual
setGapStop()
virtual void inet::sctp::SctpSackChunk::setGapStop (size_t k, uint32_t gapStop) virtual
setGapStopArraySize()
virtual void inet::sctp::SctpSackChunk::setGapStopArraySize (size_t size) virtual
setIsNrSack()
virtual void inet::sctp::SctpSackChunk::setIsNrSack (bool isNrSack) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setMsg_rwnd()
virtual void inet::sctp::SctpSackChunk::setMsg_rwnd (uint32_t msg_rwnd) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setNrGapStart()
virtual void inet::sctp::SctpSackChunk::setNrGapStart (size_t k, uint32_t nrGapStart) virtual
setNrGapStartArraySize()
virtual void inet::sctp::SctpSackChunk::setNrGapStartArraySize (size_t size) virtual
setNrGapStop()
virtual void inet::sctp::SctpSackChunk::setNrGapStop (size_t k, uint32_t nrGapStop) virtual
setNrGapStopArraySize()
virtual void inet::sctp::SctpSackChunk::setNrGapStopArraySize (size_t size) virtual
setNrSubtractRGaps()
virtual void inet::sctp::SctpSackChunk::setNrSubtractRGaps (bool nrSubtractRGaps) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setNumDupTsns()
virtual void inet::sctp::SctpSackChunk::setNumDupTsns (uint16_t numDupTsns) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setNumGaps()
virtual void inet::sctp::SctpSackChunk::setNumGaps (uint16_t numGaps) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setNumNrGaps()
virtual void inet::sctp::SctpSackChunk::setNumNrGaps (uint16_t numNrGaps) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
setSackSeqNum()
virtual void inet::sctp::SctpSackChunk::setSackSeqNum (uint32_t sackSeqNum) virtual
Referenced by inet::sctp::SctpAssociation::createSack().
Member Data Documentation
a_rwnd
uint32_t inet::sctp::SctpSackChunk::a_rwnd = 0 protected
cumTsnAck
uint32_t inet::sctp::SctpSackChunk::cumTsnAck = 0 protected
dacPacketsRcvd
uint8_t inet::sctp::SctpSackChunk::dacPacketsRcvd = 0 protected
dupTsns
uint32_t* inet::sctp::SctpSackChunk::dupTsns = nullptr protected
dupTsns_arraysize
size_t inet::sctp::SctpSackChunk::dupTsns_arraysize = 0 protected
gapStart
uint32_t* inet::sctp::SctpSackChunk::gapStart = nullptr protected
gapStart_arraysize
size_t inet::sctp::SctpSackChunk::gapStart_arraysize = 0 protected
gapStop
uint32_t* inet::sctp::SctpSackChunk::gapStop = nullptr protected
gapStop_arraysize
size_t inet::sctp::SctpSackChunk::gapStop_arraysize = 0 protected
isNrSack_
bool inet::sctp::SctpSackChunk::isNrSack_ = false protected
msg_rwnd
uint32_t inet::sctp::SctpSackChunk::msg_rwnd = 0 protected
nrGapStart
uint32_t* inet::sctp::SctpSackChunk::nrGapStart = nullptr protected
nrGapStart_arraysize
size_t inet::sctp::SctpSackChunk::nrGapStart_arraysize = 0 protected
nrGapStop
uint32_t* inet::sctp::SctpSackChunk::nrGapStop = nullptr protected
nrGapStop_arraysize
size_t inet::sctp::SctpSackChunk::nrGapStop_arraysize = 0 protected
nrSubtractRGaps
bool inet::sctp::SctpSackChunk::nrSubtractRGaps = false protected
numDupTsns
uint16_t inet::sctp::SctpSackChunk::numDupTsns = 0 protected
numGaps
uint16_t inet::sctp::SctpSackChunk::numGaps = 0 protected
numNrGaps
uint16_t inet::sctp::SctpSackChunk::numNrGaps = 0 protected
sackSeqNum
uint32_t inet::sctp::SctpSackChunk::sackSeqNum = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h