INET Framework for OMNeT++/OMNEST: inet::EligibilityTimeGate Class Reference
inet::EligibilityTimeGate Class Reference
#include <EligibilityTimeGate.h>
Public Member Functions
virtual ~EligibilityTimeGate ()
virtual Packet * pullPacket (cGate *gate) override
Pulls the packet from the packet source at the given gate.
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
Public Member Functions inherited from inet::ClockUserModuleMixin< PacketGateBase >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::queueing::PacketGateBase
virtual bool isOpen () const override
Returns true if the gate is open.
virtual bool isClosed () const
virtual void open () override
Opens the gate and starts traffic go through.
virtual void close () override
Closes the gate and stops traffic.
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual bool canPullSomePacket (cGate *gate) const override
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const override
Returns the packet that can be pulled at the given gate.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
Public Member Functions inherited from inet::queueing::PacketFlowBase
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
virtual Packet * pullPacketStart (cGate *gate, bps datarate) override
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate) override
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength) override
Progresses pulling the packet from the packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
virtual int getMaxNumPackets () const override
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const override
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const override
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const override
Returns the total length of all packets in the collection in the range [0, inf).
virtual Packet * getPacket (int index) const override
Returns the packet at the given index.
virtual bool isEmpty () const override
Returns true if there are no packets available in the collection.
virtual void removePacket (Packet *packet) override
Removes a packet from the collection.
virtual void removeAllPackets () override
Removes all packets from the collection.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Public Member Functions inherited from inet::TransparentProtocolRegistrationListener
virtual void mapRegistrationForwardingGates (cGate *gate, std::function< void(cGate *)> f)
virtual bool isForwardingProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingProtocol (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingAnyService (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingService (cGate *gate, ServicePrimitive servicePrimitive) const
virtual void handleRegisterService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyService (cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) override
Static Public Attributes
static simsignal_t remainingEligibilityTimeChangedSignal = cComponent::registerSignal("remainingEligibilityTimeChanged")
Static Public Attributes inherited from inet::queueing::PacketGateBase
static simsignal_t gateStateChangedSignal = registerSignal("gateStateChanged")
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void finish () override
virtual void updateOpen ()
virtual void emitEligibilityTimeChangedSignal ()
Protected Member Functions inherited from inet::queueing::PacketGateBase
virtual cGate * getRegistrationForwardingGate (cGate *gate) override
virtual void processPacket (Packet *packet) override
virtual bool canPacketFlowThrough (Packet *packet) const
virtual void updateDisplayString () const override
Protected Member Functions inherited from inet::queueing::PacketFlowBase
virtual bool isStreamingPacket () const
virtual void startPacketStreaming (Packet *packet)
virtual void endPacketStreaming (Packet *packet)
virtual void checkPacketStreaming (Packet *packet)
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
Protected Attributes
ClockEvent * eligibilityTimer = nullptr
simtime_t lastRemainingEligibilityTimeSignalValue = -1
simtime_t lastRemainingEligibilityTimeSignalTime = -1
Packet * lastRemainingEligibilityTimePacket = nullptr
Protected Attributes inherited from inet::queueing::PacketGateBase
bps bitrate = bps(NaN)
b extraLength = b(-1)
simtime_t extraDuration
bool isOpen_ = false
Protected Attributes inherited from inet::queueing::PacketFlowBase
cGate * inputGate = nullptr
ModuleRef< IActivePacketSource > producer
ModuleRef< IPassivePacketSource > provider
ModuleRef< IPacketCollection > collection
cGate * outputGate = nullptr
ModuleRef< IPassivePacketSink > consumer
ModuleRef< IActivePacketSink > collector
int inProgressStreamId = -1
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Constructor & Destructor Documentation
~EligibilityTimeGate()
virtual inet::EligibilityTimeGate::~EligibilityTimeGate () inline virtual
 { cancelAndDelete(eligibilityTimer); }
Member Function Documentation
emitEligibilityTimeChangedSignal()
void inet::EligibilityTimeGate::emitEligibilityTimeChangedSignal () protected virtual
 {
     simtime_t now = simTime();
     simtime_t signalValue;
     if (lastRemainingEligibilityTimeSignalTime == now) {
         auto packet = provider->canPullPacket(inputGate->getPathStartGate());
         signalValue = packet == nullptr ? 0 : CLOCKTIME_AS_SIMTIME(packet->getTag<EligibilityTimeTag>()->getEligibilityTime() - getClockTime());
         lastRemainingEligibilityTimePacket = packet;
     }
     else
         signalValue = lastRemainingEligibilityTimePacket == nullptr ? 0 : lastRemainingEligibilityTimeSignalValue - (now - lastRemainingEligibilityTimeSignalTime);
     emit(remainingEligibilityTimeChangedSignal, signalValue);
     lastRemainingEligibilityTimeSignalValue = signalValue;
     lastRemainingEligibilityTimeSignalTime = now;
 }
Referenced by finish(), handleCanPullPacketChanged(), initialize(), and pullPacket().
finish()
void inet::EligibilityTimeGate::finish () override protected virtual
 {
     emitEligibilityTimeChangedSignal();
 }
handleCanPullPacketChanged()
void inet::EligibilityTimeGate::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Reimplemented from inet::queueing::PacketGateBase.
 {
     Enter_Method("handleCanPullPacketChanged");
     emitEligibilityTimeChangedSignal();
     updateOpen();
     emitEligibilityTimeChangedSignal();
     PacketGateBase::handleCanPullPacketChanged(gate);
 }
handleMessage()
void inet::EligibilityTimeGate::handleMessage (cMessage * message) override protected virtual
Reimplemented from inet::queueing::PacketFlowBase.
 {
     if (message == eligibilityTimer)
         updateOpen();
     else
         throw cRuntimeError("Unknown message");
 }
initialize()
void inet::EligibilityTimeGate::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketGateBase.
 {
     ClockUserModuleMixin::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         eligibilityTimer = new ClockEvent("EligibilityTimer");
         lastRemainingEligibilityTimeSignalTime = simTime();
     }
     else if (stage == INITSTAGE_QUEUEING) {
         updateOpen();
         emitEligibilityTimeChangedSignal();
     }
 }
pullPacket()
Packet * inet::EligibilityTimeGate::pullPacket (cGate * gate) override virtual
Pulls the packet from the packet source at the given gate.
This operation pulls the packet as a whole. The onwership of the packet is transferred to the sink.
The source must not be empty at the given gate. The returned packet must not be nullptr. The gate must be a valid gate of this module and it must support pulling and passing packets.
Reimplemented from inet::queueing::PacketFlowBase.
 {
     Enter_Method("pullPacket");
     emitEligibilityTimeChangedSignal();
     auto packet = PacketGateBase::pullPacket(gate);
     updateOpen();
     emitEligibilityTimeChangedSignal();
     return packet;
 }
updateOpen()
void inet::EligibilityTimeGate::updateOpen () protected virtual
 {
     auto packet = provider->canPullPacket(inputGate->getPathStartGate());
     if (packet == nullptr || packet->getTag<EligibilityTimeTag>()->getEligibilityTime() <= getClockTime()) {
         if (isClosed())
             open();
     }
     else {
         if (isOpen())
             close();
     }
     packet = provider->canPullPacket(inputGate->getPathStartGate());
     if (packet != nullptr) {
         clocktime_t eligibilityTime = packet->getTag<EligibilityTimeTag>()->getEligibilityTime();
         if (eligibilityTime > getClockTime())
             rescheduleClockEventAt(eligibilityTime, eligibilityTimer);
     }
 }
Referenced by handleCanPullPacketChanged(), handleMessage(), initialize(), and pullPacket().
Member Data Documentation
eligibilityTimer
ClockEvent* inet::EligibilityTimeGate::eligibilityTimer = nullptr protected
Referenced by handleMessage(), initialize(), and updateOpen().
lastRemainingEligibilityTimePacket
Packet* inet::EligibilityTimeGate::lastRemainingEligibilityTimePacket = nullptr protected
Referenced by emitEligibilityTimeChangedSignal().
lastRemainingEligibilityTimeSignalTime
simtime_t inet::EligibilityTimeGate::lastRemainingEligibilityTimeSignalTime = -1 protected
Referenced by emitEligibilityTimeChangedSignal(), and initialize().
lastRemainingEligibilityTimeSignalValue
simtime_t inet::EligibilityTimeGate::lastRemainingEligibilityTimeSignalValue = -1 protected
Referenced by emitEligibilityTimeChangedSignal().
remainingEligibilityTimeChangedSignal
simsignal_t inet::EligibilityTimeGate::remainingEligibilityTimeChangedSignal = cComponent::registerSignal("remainingEligibilityTimeChanged") static
Referenced by emitEligibilityTimeChangedSignal().
The documentation for this class was generated from the following files:
EligibilityTimeGate.h
EligibilityTimeGate.cc