INET Framework for OMNeT++/OMNEST: inet::eigrp::IEigrpModule< IPAddress > Class Template Reference
inet::eigrp::IEigrpModule< IPAddress > Class Template Reference abstract
Interface for EIGRP configuration.
#include <IEigrpModule.h>
Public Member Functions
virtual ~IEigrpModule ()
virtual void addInterface (int interfaceId, int networkId, bool enabled)=0
Adds interface to EIGRP.
virtual void addInterface (int interfaceId, bool enabled)=0
Adds interface to EIGRP for IPv6.
virtual EigrpNetwork< IPAddress > * addNetwork (IPAddress address, IPAddress mask)=0
Adds new network to EigrpNetworkTable for routing.
virtual void setASNum (int asNum)=0
virtual int getASNum ()=0
virtual void setKValues (const EigrpKValues &kValues)=0
virtual void setMaximumPath (int maximumPath)=0
virtual void setVariance (int variance)=0
virtual void setStub (const EigrpStub &stub)=0
virtual void updateInterface (int interfaceId)=0
virtual void setLoad (int load, int interfaceId)=0
virtual void setBandwidth (int bandwith, int interfaceId)=0
virtual void setDelay (int delay, int interfaceId)=0
virtual void setReliability (int reability, int interfaceId)=0
virtual void setHelloInt (int interval, int interfaceId)=0
virtual void setHoldInt (int interval, int interfaceId)=0
virtual void setSplitHorizon (bool shEnabled, int interfaceId)=0
virtual void setPassive (bool passive, int ifaceId)=0
virtual void setRouterId (Ipv4Address routerID)=0
Sets router ID.
virtual bool addNetPrefix (const IPAddress &network, const short int prefixLen, const int ifaceId)=0
Adds information about IPv6 network prefix.
Detailed Description
template<typename IPAddress>
class inet::eigrp::IEigrpModule< IPAddress >
Interface for EIGRP configuration.
Constructor & Destructor Documentation
~IEigrpModule()
template<typename IPAddress > virtual inet::eigrp::IEigrpModule< IPAddress >::~IEigrpModule () inline virtual
 {}
Member Function Documentation
addInterface() [1/2]
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::addInterface (int interfaceId, bool enabled) pure virtual
Adds interface to EIGRP for IPv6.
Parameters
interfaceId ID of interface
enabled state of interface in EIGRP process, enabled or disabled
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
addInterface() [2/2]
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::addInterface (int interfaceId, int networkId, bool enabled) pure virtual
Adds interface to EIGRP.
Parameters
interfaceId ID of interface
networkID ID of network in EigrpNetworkTable
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaces6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks().
addNetPrefix()
template<typename IPAddress > virtual bool inet::eigrp::IEigrpModule< IPAddress >::addNetPrefix (const IPAddress & network, const short int prefixLen, const int ifaceId) pure virtual
Adds information about IPv6 network prefix.
Parameters
network network prefix
prefixLen length of network prefix
ifaceId ID of interface contains network prefix
Returns
True if successfully added, otherwise false (e.g. same IPv6 prefix on different interfaces)
Note
Checks duplicates
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaces6Config().
addNetwork()
template<typename IPAddress > virtual EigrpNetwork<IPAddress>* inet::eigrp::IEigrpModule< IPAddress >::addNetwork (IPAddress address, IPAddress mask) pure virtual
Adds new network to EigrpNetworkTable for routing.
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks().
getASNum()
template<typename IPAddress > virtual int inet::eigrp::IEigrpModule< IPAddress >::getASNum () pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaces6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfacesConfig().
setASNum()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setASNum (int asNum) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig().
setBandwidth()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setBandwidth (int bandwith, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams6().
setDelay()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setDelay (int delay, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams6().
setHelloInt()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setHelloInt (int interval, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterface(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterface6().
setHoldInt()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setHoldInt (int interval, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterface(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterface6().
setKValues()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setKValues (const EigrpKValues & kValues) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig().
setLoad()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setLoad (int load, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams6().
setMaximumPath()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setMaximumPath (int maximumPath) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig().
setPassive()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setPassive (bool passive, int ifaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig().
setReliability()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setReliability (int reability, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaceParams6().
setRouterId()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setRouterId (Ipv4Address routerID) pure virtual
Sets router ID.
Parameters
routerID EIGRP process routerID, represented as IPv4 address
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config().
setSplitHorizon()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setSplitHorizon (bool shEnabled, int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterface(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterface6().
setStub()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setStub (const EigrpStub & stub) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig().
setVariance()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::setVariance (int variance) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig().
updateInterface()
template<typename IPAddress > virtual void inet::eigrp::IEigrpModule< IPAddress >::updateInterface (int interfaceId) pure virtual
Implemented in inet::eigrp::EigrpIpv6Pdm, and inet::eigrp::EigrpIpv4Pdm.
Referenced by inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaces6Config(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfacesConfig().
The documentation for this class was generated from the following file:
IEigrpModule.h