INET Framework for OMNeT++/OMNEST: inet::visualizer::EnergyStorageVisualizerBase Class Reference
inet::visualizer::EnergyStorageVisualizerBase Class Reference abstract
#include <EnergyStorageVisualizerBase.h>
Classes
class EnergyStorageVisualization
Parameters
bool displayEnergyStorages = false
ModuleFilter energyStorageFilter
cFigure::Color color
double width
double height
double spacing
Placement placementHint
double placementPriority
std::vector< const EnergyStorageVisualization * > energyStorageVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void refreshDisplay () const override
virtual void preDelete (cComponent *root) override
virtual double getNominalCapacity (const power::IEnergyStorage *energyStorage) const
virtual double getResidualCapacity (const power::IEnergyStorage *energyStorage) const
virtual EnergyStorageVisualization * createEnergyStorageVisualization (const power::IEnergyStorage *energyStorage) const =0
virtual void addEnergyStorageVisualization (const EnergyStorageVisualization *energyStorageVisualization)
virtual void addEnergyStorageVisualizations ()
virtual void removeEnergyStorageVisualization (const EnergyStorageVisualization *energyStorageVisualization)
virtual void refreshEnergyStorageVisualization (const EnergyStorageVisualization *energyStorageVisualization) const =0
virtual void removeAllEnergyStorageVisualizations ()
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addEnergyStorageVisualization()
void inet::visualizer::EnergyStorageVisualizerBase::addEnergyStorageVisualization (const EnergyStorageVisualization * energyStorageVisualization) protected virtual
Reimplemented in inet::visualizer::EnergyStorageCanvasVisualizer.
 {
     energyStorageVisualizations.push_back(energyStorageVisualization);
 }
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::addEnergyStorageVisualization(), and addEnergyStorageVisualizations().
addEnergyStorageVisualizations()
void inet::visualizer::EnergyStorageVisualizerBase::addEnergyStorageVisualizations () protected virtual
 {
     auto simulation = getSimulation();
     for (int id = 0; id < simulation->getLastComponentId(); id++) {
         auto component = simulation->getComponent(id);
         auto module = dynamic_cast<cModule *>(component);
         auto energyStorage = dynamic_cast<IEnergyStorage *>(module);
         if (energyStorage != nullptr && energyStorageFilter.matches(module))
             addEnergyStorageVisualization(createEnergyStorageVisualization(energyStorage));
     }
 }
Referenced by handleParameterChange(), and initialize().
createEnergyStorageVisualization()
virtual EnergyStorageVisualization* inet::visualizer::EnergyStorageVisualizerBase::createEnergyStorageVisualization (const power::IEnergyStorage * energyStorage) const protected pure virtual
Implemented in inet::visualizer::EnergyStorageCanvasVisualizer, and inet::visualizer::EnergyStorageOsgVisualizer.
Referenced by addEnergyStorageVisualizations().
getNominalCapacity()
double inet::visualizer::EnergyStorageVisualizerBase::getNominalCapacity (const power::IEnergyStorage * energyStorage) const protected virtual
 {
     if (auto epEnergyStorage = dynamic_cast<const IEpEnergyStorage *>(energyStorage))
         return epEnergyStorage->getNominalEnergyCapacity().get();
     else if (auto ccEnergyStorage = dynamic_cast<const ICcEnergyStorage *>(energyStorage))
         return ccEnergyStorage->getNominalChargeCapacity().get();
     else
         throw cRuntimeError("Unknown energy storage");
 }
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::createEnergyStorageVisualization().
getResidualCapacity()
double inet::visualizer::EnergyStorageVisualizerBase::getResidualCapacity (const power::IEnergyStorage * energyStorage) const protected virtual
 {
     if (auto epEnergyStorage = dynamic_cast<const IEpEnergyStorage *>(energyStorage))
         return epEnergyStorage->getResidualEnergyCapacity().get();
     else if (auto ccEnergyStorage = dynamic_cast<const ICcEnergyStorage *>(energyStorage))
         return ccEnergyStorage->getResidualChargeCapacity().get();
     else
         throw cRuntimeError("Unknown energy storage");
 }
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::refreshEnergyStorageVisualization().
handleParameterChange()
void inet::visualizer::EnergyStorageVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         removeAllEnergyStorageVisualizations();
         addEnergyStorageVisualizations();
     }
 }
initialize()
void inet::visualizer::EnergyStorageVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::EnergyStorageCanvasVisualizer, and inet::visualizer::EnergyStorageOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayEnergyStorages = par("displayEnergyStorages");
         energyStorageFilter.setPattern(par("energyStorageFilter"));
         color = cFigure::parseColor(par("color"));
         width = par("width");
         height = par("height");
         spacing = par("spacing");
         placementHint = parsePlacement(par("placementHint"));
         placementPriority = par("placementPriority");
     }
     else if (stage == INITSTAGE_LAST) {
         if (displayEnergyStorages)
             addEnergyStorageVisualizations();
     }
 }
Referenced by inet::visualizer::EnergyStorageOsgVisualizer::initialize(), and inet::visualizer::EnergyStorageCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::EnergyStorageVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayEnergyStorages)
         removeAllEnergyStorageVisualizations();
 }
refreshDisplay()
void inet::visualizer::EnergyStorageVisualizerBase::refreshDisplay () const override protected virtual
 {
     for (auto energyStorageVisualization : energyStorageVisualizations)
         refreshEnergyStorageVisualization(energyStorageVisualization);
 }
refreshEnergyStorageVisualization()
virtual void inet::visualizer::EnergyStorageVisualizerBase::refreshEnergyStorageVisualization (const EnergyStorageVisualization * energyStorageVisualization) const protected pure virtual
Implemented in inet::visualizer::EnergyStorageCanvasVisualizer, and inet::visualizer::EnergyStorageOsgVisualizer.
Referenced by refreshDisplay().
removeAllEnergyStorageVisualizations()
void inet::visualizer::EnergyStorageVisualizerBase::removeAllEnergyStorageVisualizations () protected virtual
 {
     for (auto energyStorageVisualization : std::vector<const EnergyStorageVisualization *>(energyStorageVisualizations)) {
         removeEnergyStorageVisualization(energyStorageVisualization);
         delete energyStorageVisualization;
     }
 }
Referenced by handleParameterChange(), and preDelete().
removeEnergyStorageVisualization()
void inet::visualizer::EnergyStorageVisualizerBase::removeEnergyStorageVisualization (const EnergyStorageVisualization * energyStorageVisualization) protected virtual
Reimplemented in inet::visualizer::EnergyStorageCanvasVisualizer.
 {
     energyStorageVisualizations.erase(std::remove(energyStorageVisualizations.begin(), energyStorageVisualizations.end(), energyStorageVisualization), energyStorageVisualizations.end());
 }
Referenced by removeAllEnergyStorageVisualizations(), and inet::visualizer::EnergyStorageCanvasVisualizer::removeEnergyStorageVisualization().
Member Data Documentation
color
cFigure::Color inet::visualizer::EnergyStorageVisualizerBase::color protected
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::createEnergyStorageVisualization(), and initialize().
displayEnergyStorages
bool inet::visualizer::EnergyStorageVisualizerBase::displayEnergyStorages = false protected
Referenced by initialize(), and preDelete().
energyStorageFilter
ModuleFilter inet::visualizer::EnergyStorageVisualizerBase::energyStorageFilter protected
Referenced by addEnergyStorageVisualizations(), and initialize().
energyStorageVisualizations
std::vector<const EnergyStorageVisualization *> inet::visualizer::EnergyStorageVisualizerBase::energyStorageVisualizations protected
Referenced by addEnergyStorageVisualization(), inet::visualizer::EnergyStorageOsgVisualizer::initialize(), refreshDisplay(), removeAllEnergyStorageVisualizations(), and removeEnergyStorageVisualization().
height
double inet::visualizer::EnergyStorageVisualizerBase::height protected
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::createEnergyStorageVisualization(), and initialize().
placementHint
Placement inet::visualizer::EnergyStorageVisualizerBase::placementHint protected
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::addEnergyStorageVisualization(), and initialize().
placementPriority
double inet::visualizer::EnergyStorageVisualizerBase::placementPriority protected
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::addEnergyStorageVisualization(), and initialize().
spacing
double inet::visualizer::EnergyStorageVisualizerBase::spacing protected
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::createEnergyStorageVisualization(), and initialize().
width
double inet::visualizer::EnergyStorageVisualizerBase::width protected
Referenced by inet::visualizer::EnergyStorageCanvasVisualizer::createEnergyStorageVisualization(), and initialize().
The documentation for this class was generated from the following files:
EnergyStorageVisualizerBase.h
EnergyStorageVisualizerBase.cc