INET Framework for OMNeT++/OMNEST: inet::physicallayer::Signal Class Reference
inet::physicallayer::Signal Class Reference
#include <Signal.h>
Public Member Functions
Signal (const char *name=nullptr, short kind=0, int64_t bitLength=0)
Signal (const Signal &other)
virtual Signal * dup () const override
virtual const char * getFullName () const override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Signal() [1/2]
inet::physicallayer::Signal::Signal (const char * name = nullptr, short kind = 0, int64_t bitLength = 0) explicit
                                                               :
     cPacket(name, kind, bitLength)
 {
 }
Signal() [2/2]
inet::physicallayer::Signal::Signal (const Signal & other)
                                   :
     cPacket(other)
 {
 }
Member Function Documentation
dup()
virtual Signal* inet::physicallayer::Signal::dup () const inline override virtual
Reimplemented in inet::physicallayer::EthernetFilledIfgSignal, inet::physicallayer::EthernetJamSignal, inet::physicallayer::EthernetSignal, inet::physicallayer::EthernetSignalBase, and inet::physicallayer::WirelessSignal.
 { return new Signal(*this); }
Referenced by inet::StreamThroughTransmitter::progressTx(), inet::StreamingTransmitterBase::scheduleAt(), inet::StreamingTransmitter::startTx(), inet::PacketTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
getFullName()
const char * inet::physicallayer::Signal::getFullName () const override virtual
 {
     if (!isUpdate())
         return getName();
     else {
         const char *suffix;
         if (getRemainingDuration().isZero())
             suffix = ":end";
         else if (getRemainingDuration() == getDuration())
             suffix = ":start";
         else
             suffix = ":progress";
         static std::set<std::string> pool;
         std::string fullname = std::string(getName()) + suffix;
         auto it = pool.insert(fullname).first;
         return it->c_str();
     }
 }
printToStream()
std::ostream & inet::physicallayer::Signal::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::WirelessSignal.
 {
     std::string className = getClassName();
     auto index = className.rfind("::");
     if (index != std::string::npos)
         className = className.substr(index + 2);
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FAINT << "(" << className << ")" << EV_NORMAL;
     stream << EV_ITALIC << getName() << EV_NORMAL << " (" << simsec(getDuration()) << " " << b(getBitLength()) << ")";
     auto packet = check_and_cast<Packet *>(getEncapsulatedPacket());
     packet->printToStream(stream, level + 1, evFlags);
     return stream;
 }
str()
std::string inet::physicallayer::Signal::str () const override virtual
 {
     std::stringstream stream;
     stream << "(" << simsec(getDuration()) << " " << b(getBitLength()) << ")";
     if (auto packet = getEncapsulatedPacket())
         stream << " " << packet;
     return stream.str();
 }
The documentation for this class was generated from the following files:
Signal.h
Signal.cc