INET Framework for OMNeT++/OMNEST: inet::power::SimpleCcBattery Class Reference
inet::power::SimpleCcBattery Class Reference
#include <SimpleCcBattery.h>
Public Member Functions
virtual V getNominalVoltage () const override
Returns the open circuit voltage in the range [0, +infinity).
virtual V getOutputVoltage () const override
Returns the output voltage in the ragne [0, +infinity).
virtual A getTotalCurrentConsumption () const override
Returns the total current consumption in the range [0, +infinity).
virtual A getTotalCurrentGeneration () const override
Returns the total current generation in the range [0, +infinity).
virtual C getNominalChargeCapacity () const override
Returns the nominal charge capacity in the range [0, +infinity).
virtual C getResidualChargeCapacity () const override
Returns the residual charge capacity in the range [0, nominalCapacity].
Public Member Functions inherited from inet::power::CcEnergyStorageBase
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
virtual void receiveSignal (cComponent *source, simsignal_t signal, double value, cObject *details) override
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Public Member Functions inherited from inet::LifecycleController
LifecycleController ()
virtual ~LifecycleController ()
virtual bool initiateOperation (LifecycleOperation *operation, IDoneCallback *completionCallback=nullptr)
Initiate an operation.
Protected Member Functions
virtual void initialize (int stage) override
virtual void refreshDisplay () const override
virtual void updateDisplayString () const
virtual const char * resolveDirective (char directive) const override
virtual void updateTotalCurrentConsumption () override
virtual void updateTotalCurrentGeneration () override
virtual void setResidualCapacity (C newResidualCapacity)
virtual void updateResidualCapacity ()
virtual void executeNodeOperation (C newResidualCapacity)
Protected Member Functions inherited from inet::power::CcEnergySourceBase
virtual A computeTotalCurrentConsumption () const
Protected Member Functions inherited from inet::power::CcEnergySinkBase
virtual A computeTotalCurrentGeneration () const
Protected Member Functions inherited from inet::LifecycleController
virtual bool resumeOperation (LifecycleOperation *operation)
virtual void doOneStage (LifecycleOperation *operation, cModule *submodule)
virtual void moduleOperationStageCompleted (Callback *callback)
Protected Attributes
C nominalCapacity = C(NaN)
V nominalVoltage = V(NaN)
Ohm internalResistance = Ohm(NaN)
C residualCapacity = C(NaN)
simtime_t lastResidualCapacityUpdate = -1
cModule * networkNode = nullptr
NodeStatus * nodeStatus = nullptr
Protected Attributes inherited from inet::power::CcEnergySourceBase
A totalCurrentConsumption = A(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Protected Attributes inherited from inet::power::CcEnergySinkBase
A totalCurrentGeneration = A(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Protected Attributes inherited from inet::LifecycleController
Callback * spareCallback = nullptr
Additional Inherited Members
Static Public Attributes inherited from inet::power::ICcEnergySource
static simsignal_t currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged")
The signal that is used to publish current consumption changes.
Static Public Attributes inherited from inet::power::ICcEnergySink
static simsignal_t currentGenerationChangedSignal = cComponent::registerSignal("currentGenerationChanged")
The signal that is used to publish current generation changes.
Static Public Attributes inherited from inet::power::ICcEnergyStorage
static simsignal_t residualChargeCapacityChangedSignal = cComponent::registerSignal("residualChargeCapacityChanged")
The signal that is used to publish residual charge capacity changes also including when the energy storage becomes completely depleted or charged.
Member Function Documentation
executeNodeOperation()
void inet::power::SimpleCcBattery::executeNodeOperation (C newResidualCapacity) protected virtual
 {
     if (nodeStatus->getState() == NodeStatus::UP && newResidualCapacity <= C(0)) {
         EV_WARN << "Battery failed" << endl;
         LifecycleOperation::StringMap params;
         ModuleCrashOperation *operation = new ModuleCrashOperation();
         operation->initialize(networkNode, params);
         initiateOperation(operation);
     }
 }
Referenced by setResidualCapacity().
getNominalChargeCapacity()
virtual C inet::power::SimpleCcBattery::getNominalChargeCapacity () const inline override virtual
Returns the nominal charge capacity in the range [0, +infinity).
It specifies the maximum amount of charge that the energy storage can contain.
Implements inet::power::ICcEnergyStorage.
 { return nominalCapacity; }
Referenced by resolveDirective().
getNominalVoltage()
virtual V inet::power::SimpleCcBattery::getNominalVoltage () const inline override virtual
Returns the open circuit voltage in the range [0, +infinity).
Implements inet::power::ICcEnergySource.
 { return nominalVoltage; }
getOutputVoltage()
virtual V inet::power::SimpleCcBattery::getOutputVoltage () const inline override virtual
Returns the output voltage in the ragne [0, +infinity).
Implements inet::power::ICcEnergySource.
 { return nominalVoltage + (totalCurrentGeneration - totalCurrentConsumption) * internalResistance; }
getResidualChargeCapacity()
virtual C inet::power::SimpleCcBattery::getResidualChargeCapacity () const inline override virtual
Returns the residual charge capacity in the range [0, nominalCapacity].
It specifies the amount of charge that the energy storage contains at the moment.
Implements inet::power::ICcEnergyStorage.
 { return residualCapacity; }
Referenced by resolveDirective().
getTotalCurrentConsumption()
virtual A inet::power::SimpleCcBattery::getTotalCurrentConsumption () const inline override virtual
Returns the total current consumption in the range [0, +infinity).
Reimplemented from inet::power::CcEnergySourceBase.
 { return totalCurrentConsumption; }
getTotalCurrentGeneration()
virtual A inet::power::SimpleCcBattery::getTotalCurrentGeneration () const inline override virtual
Returns the total current generation in the range [0, +infinity).
Reimplemented from inet::power::CcEnergySinkBase.
 { return totalCurrentGeneration; }
initialize()
void inet::power::SimpleCcBattery::initialize (int stage) override protected virtual
Reimplemented from inet::power::CcEnergyStorageBase.
 {
     CcEnergyStorageBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         nominalCapacity = C(par("nominalCapacity"));
         nominalVoltage = V(par("nominalVoltage"));
         internalResistance = Ohm(par("internalResistance"));
         networkNode = findContainingNode(this);
         if (networkNode != nullptr) {
             nodeStatus = dynamic_cast<NodeStatus *>(networkNode->getSubmodule("status"));
             if (!nodeStatus)
                 throw cRuntimeError("Cannot find node status");
         }
         setResidualCapacity(C(par("initialCapacity")));
         WATCH(residualCapacity);
     }
 }
refreshDisplay()
void inet::power::SimpleCcBattery::refreshDisplay () const override protected virtual
 {
     updateDisplayString();
 }
resolveDirective()
const char * inet::power::SimpleCcBattery::resolveDirective (char directive) const override protected virtual
Implements inet::StringFormat::IDirectiveResolver.
 {
     static std::string result;
     switch (directive) {
         case 'c':
             result = getResidualChargeCapacity().str();
             break;
         case 'p':
             result = std::to_string((int)std::round(100 * unit(getResidualChargeCapacity() / getNominalChargeCapacity()).get())) + "%";
             break;
         default:
             throw cRuntimeError("Unknown directive: %c", directive);
     }
     return result.c_str();
 }
setResidualCapacity()
void inet::power::SimpleCcBattery::setResidualCapacity (C newResidualCapacity) protected virtual
 {
     residualCapacity = newResidualCapacity;
     lastResidualCapacityUpdate = simTime();
     if (residualCapacity == C(0))
         EV_WARN << "Battery depleted" << endl;
     else if (residualCapacity == nominalCapacity)
         EV_INFO << "Battery charged" << endl;
     if (networkNode != nullptr)
         executeNodeOperation(newResidualCapacity);
     emit(residualChargeCapacityChangedSignal, residualCapacity.get());
 }
Referenced by initialize(), and updateResidualCapacity().
updateDisplayString()
void inet::power::SimpleCcBattery::updateDisplayString () const protected virtual
 {
     if (getEnvir()->isGUI()) {
         auto text = StringFormat::formatString(par("displayStringTextFormat"), this);
         getDisplayString().setTagArg("t", 0, text);
     }
 }
Referenced by refreshDisplay().
updateResidualCapacity()
void inet::power::SimpleCcBattery::updateResidualCapacity () protected virtual
 {
     simtime_t currentTime = simTime();
     if (currentTime != lastResidualCapacityUpdate) {
         C newResidualCapacity = residualCapacity + s((currentTime - lastResidualCapacityUpdate).dbl()) * (totalCurrentGeneration - totalCurrentConsumption);
         if (newResidualCapacity < C(0))
             newResidualCapacity = C(0);
         else if (newResidualCapacity > nominalCapacity)
             newResidualCapacity = nominalCapacity;
         setResidualCapacity(newResidualCapacity);
     }
 }
Referenced by updateTotalCurrentConsumption(), and updateTotalCurrentGeneration().
updateTotalCurrentConsumption()
void inet::power::SimpleCcBattery::updateTotalCurrentConsumption () override protected virtual
Reimplemented from inet::power::CcEnergyStorageBase.
 {
     updateResidualCapacity();
     CcEnergyStorageBase::updateTotalCurrentConsumption();
 }
updateTotalCurrentGeneration()
void inet::power::SimpleCcBattery::updateTotalCurrentGeneration () override protected virtual
Reimplemented from inet::power::CcEnergyStorageBase.
 {
     updateResidualCapacity();
     CcEnergyStorageBase::updateTotalCurrentGeneration();
 }
Member Data Documentation
internalResistance
Ohm inet::power::SimpleCcBattery::internalResistance = Ohm(NaN) protected
Referenced by initialize().
lastResidualCapacityUpdate
simtime_t inet::power::SimpleCcBattery::lastResidualCapacityUpdate = -1 protected
Referenced by setResidualCapacity(), and updateResidualCapacity().
networkNode
cModule* inet::power::SimpleCcBattery::networkNode = nullptr protected
Referenced by executeNodeOperation(), initialize(), and setResidualCapacity().
nodeStatus
NodeStatus* inet::power::SimpleCcBattery::nodeStatus = nullptr protected
Referenced by executeNodeOperation(), and initialize().
nominalCapacity
C inet::power::SimpleCcBattery::nominalCapacity = C(NaN) protected
Referenced by initialize(), setResidualCapacity(), and updateResidualCapacity().
nominalVoltage
V inet::power::SimpleCcBattery::nominalVoltage = V(NaN) protected
Referenced by initialize().
residualCapacity
C inet::power::SimpleCcBattery::residualCapacity = C(NaN) protected
Referenced by initialize(), setResidualCapacity(), and updateResidualCapacity().
The documentation for this class was generated from the following files:
SimpleCcBattery.h
SimpleCcBattery.cc