INET Framework for OMNeT++/OMNEST: inet::NextHopRoute Class Reference
inet::NextHopRoute Class Reference
A next hop route that uses generic addresses as destination and next hop.
#include <NextHopRoute.h>
Public Member Functions
NextHopRoute ()
virtual ~NextHopRoute ()
virtual std::string str () const override
virtual std::string detailedInfo () const
bool equals (const IRoute &route) const
virtual void setRoutingTable (NextHopRoutingTable *owner)
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int l) override
virtual void setNextHop (const L3Address &nextHop) override
virtual void setInterface (NetworkInterface *ie) override
virtual void setSourceType (SourceType sourceType) override
virtual void setSource (cObject *source) override
virtual void setMetric (int metric) override
virtual void setAdminDist (unsigned int adminDist) override
virtual void setProtocolData (cObject *protocolData) override
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
virtual NetworkInterface * getInterface () const override
Next hop interface.
SourceType getSourceType () const override
Source type of the route.
virtual cObject * getSource () const override
Source of route.
virtual int getMetric () const override
Cost to reach the destination.
virtual cObject * getProtocolData () const override
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
Protected Member Functions
void changed (int fieldCode)
Private Attributes
NextHopRoutingTable * owner
int prefixLength
L3Address destination
L3Address nextHop
NetworkInterface * interface
SourceType sourceType
cObject * source
cObject * protocolData
int metric
Additional Inherited Members
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Detailed Description
A next hop route that uses generic addresses as destination and next hop.
Constructor & Destructor Documentation
NextHopRoute()
inet::NextHopRoute::NextHopRoute () inline
                    : owner(nullptr), prefixLength(0), interface(nullptr), sourceType(IRoute::MANUAL),
         source(nullptr), protocolData(nullptr), metric(0) {}
~NextHopRoute()
virtual inet::NextHopRoute::~NextHopRoute () inline virtual
 { delete protocolData; }
Member Function Documentation
changed()
void inet::NextHopRoute::changed (int fieldCode) protected
 {
     if (owner)
         owner->routeChanged(this, fieldCode);
 }
detailedInfo()
std::string inet::NextHopRoute::detailedInfo () const virtual
 {
     return ""; // TODO
 }
equals()
bool inet::NextHopRoute::equals (const IRoute & route) const
 {
     return false; // TODO
 }
getDestinationAsGeneric()
virtual L3Address inet::NextHopRoute::getDestinationAsGeneric () const inline override virtual
Destination address prefix to match.
Implements inet::IRoute.
 { return destination; }
Referenced by inet::NextHopRoutingTable::routeLessThan().
getInterface()
virtual NetworkInterface* inet::NextHopRoute::getInterface () const inline override virtual
Next hop interface.
Implements inet::IRoute.
 { return interface; }
Referenced by inet::NextHopRoutingTable::addRoute(), and inet::NextHopForwarding::routePacket().
getMetric()
virtual int inet::NextHopRoute::getMetric () const inline override virtual
Cost to reach the destination.
Implements inet::IRoute.
 { return metric; }
Referenced by inet::NextHopRoutingTable::routeLessThan().
getNextHopAsGeneric()
virtual L3Address inet::NextHopRoute::getNextHopAsGeneric () const inline override virtual
Next hop address.
Implements inet::IRoute.
 { return nextHop; }
Referenced by inet::NextHopForwarding::routePacket().
getPrefixLength()
virtual int inet::NextHopRoute::getPrefixLength () const inline override virtual
Represents length of prefix to match.
Implements inet::IRoute.
 { return prefixLength; }
Referenced by inet::NextHopRoutingTable::routeLessThan().
getProtocolData()
virtual cObject* inet::NextHopRoute::getProtocolData () const inline override virtual
Implements inet::IRoute.
 { return protocolData; }
getRoutingTableAsGeneric()
IRoutingTable * inet::NextHopRoute::getRoutingTableAsGeneric () const override virtual
The routing table in which this route is inserted, or nullptr.
Implements inet::IRoute.
 {
     return owner;
 }
Referenced by inet::NextHopRoutingTable::internalAddRoute(), and inet::NextHopRoutingTable::internalRemoveRoute().
getSource()
virtual cObject* inet::NextHopRoute::getSource () const inline override virtual
Source of route.
Implements inet::IRoute.
 { return source; }
getSourceType()
SourceType inet::NextHopRoute::getSourceType () const inline override virtual
Source type of the route.
Implements inet::IRoute.
 { return sourceType; }
setAdminDist()
virtual void inet::NextHopRoute::setAdminDist (unsigned int adminDist) inline override virtual
Implements inet::IRoute.
 {}
setDestination()
virtual void inet::NextHopRoute::setDestination (const L3Address & dest) inline override virtual
Implements inet::IRoute.
 { if (destination != dest) { this->destination = dest; changed(F_DESTINATION); } }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes().
setInterface()
virtual void inet::NextHopRoute::setInterface (NetworkInterface * ie) inline override virtual
Implements inet::IRoute.
 { if (interface != ie) { this->interface = ie; changed(F_IFACE); } }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes().
setMetric()
virtual void inet::NextHopRoute::setMetric (int metric) inline override virtual
Implements inet::IRoute.
 { if (this->metric != metric) { this->metric = metric; changed(F_METRIC); } }
setNextHop()
virtual void inet::NextHopRoute::setNextHop (const L3Address & nextHop) inline override virtual
Implements inet::IRoute.
 { if (this->nextHop != nextHop) { this->nextHop = nextHop; changed(F_NEXTHOP); } }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes().
setPrefixLength()
virtual void inet::NextHopRoute::setPrefixLength (int l) inline override virtual
Implements inet::IRoute.
 { if (prefixLength != l) { this->prefixLength = l; changed(F_PREFIX_LENGTH); } }
setProtocolData()
virtual void inet::NextHopRoute::setProtocolData (cObject * protocolData) inline override virtual
Implements inet::IRoute.
 { this->protocolData = protocolData; }
setRoutingTable()
virtual void inet::NextHopRoute::setRoutingTable (NextHopRoutingTable * owner) inline virtual
 { this->owner = owner; }
Referenced by inet::NextHopRoutingTable::internalAddRoute(), and inet::NextHopRoutingTable::removeRoute().
setSource()
virtual void inet::NextHopRoute::setSource (cObject * source) inline override virtual
Implements inet::IRoute.
 { if (this->source != source) { this->source = source; changed(F_SOURCE); } }
setSourceType()
virtual void inet::NextHopRoute::setSourceType (SourceType sourceType) inline override virtual
Implements inet::IRoute.
 { if (this->sourceType != sourceType) { this->sourceType = sourceType; changed(F_TYPE); } }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes().
str()
std::string inet::NextHopRoute::str () const override virtual
 {
     std::stringstream out;
     out << "dest:";
     if (destination.isUnspecified())
         out << "*  ";
     else
         out << destination << "  ";
     out << "gw:";
     if (nextHop.isUnspecified())
         out << "*  ";
     else
         out << nextHop << "  ";
     out << "metric:" << metric << " ";
     out << "if:";
     if (!interface)
         out << "*";
     else
         out << interface->getInterfaceName();
     if (interface)
         if (auto nextHopData = interface->findProtocolData<NextHopInterfaceData>())
             out << "(" << nextHopData->getAddress() << ")";
     out << "  ";
     out << (nextHop.isUnspecified() ? "DIRECT" : "REMOTE");
     out << " " << IRoute::sourceTypeName(sourceType);
     if (protocolData)
         out << " " << protocolData->str();
     return out.str();
 }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::NextHopRoutingTable::deleteRoute(), and inet::NextHopRoutingTable::removeRoute().
Member Data Documentation
destination
L3Address inet::NextHopRoute::destination private
Referenced by str().
interface
NetworkInterface* inet::NextHopRoute::interface private
Referenced by str().
metric
int inet::NextHopRoute::metric private
Referenced by str().
nextHop
L3Address inet::NextHopRoute::nextHop private
Referenced by str().
owner
NextHopRoutingTable* inet::NextHopRoute::owner private
Referenced by changed(), and getRoutingTableAsGeneric().
prefixLength
int inet::NextHopRoute::prefixLength private
protocolData
cObject* inet::NextHopRoute::protocolData private
Referenced by str().
source
cObject* inet::NextHopRoute::source private
sourceType
SourceType inet::NextHopRoute::sourceType private
Referenced by str().
The documentation for this class was generated from the following files:
NextHopRoute.h
NextHopRoute.cc