INET Framework for OMNeT++/OMNEST: inet::TcpCommand Class Reference
inet::TcpCommand Class Reference
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:78 by opp_msgtool.
#include <TcpCommand_m.h>
Public Member Functions
TcpCommand ()
TcpCommand (const TcpCommand &other)
virtual ~TcpCommand ()
TcpCommand & operator= (const TcpCommand &other)
virtual TcpCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getUserId () const
virtual void setUserId (int userId)
Protected Member Functions
bool operator== (const TcpCommand &)=delete
Protected Attributes
int userId = -1
Private Member Functions
void copy (const TcpCommand &other)
Detailed Description
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:78 by opp_msgtool.
//
// Control info for TCP connections. This class is to be set as control info
// (see cMessage::setControlInfo()) on all messages exchanged between TCP and
// application, in both directions. Some commands and indications
// (TCP_C_OPEN_xxx, TCP_I_STATUS) use subclasses.
//
// connId identifies the connection locally within the application (internally,
// TCP uses the (app gate index, connId) pair to identify the socket).
// connId is to be chosen by the application in the open command.
//
//# TODO explain userId
//
// @see ~TcpCommandCode, ~TcpStatusInd, ~TcpOpenCommand, ~TcpStatusInfo, ~ITcp
//
class TcpCommand extends cObject
{
    int userId = -1;   // id than can be freely used by the app
}
Constructor & Destructor Documentation
TcpCommand() [1/2]
inet::TcpCommand::TcpCommand ()
TcpCommand() [2/2]
inet::TcpCommand::TcpCommand (const TcpCommand & other)
~TcpCommand()
virtual inet::TcpCommand::~TcpCommand () virtual
Member Function Documentation
copy()
void inet::TcpCommand::copy (const TcpCommand & other) private
dup()
virtual TcpCommand* inet::TcpCommand::dup () const inline override virtual
Reimplemented in inet::TcpStatusInfo, inet::TcpConnectInfo, inet::TcpAvailableInfo, inet::TcpSetTosCommand, inet::TcpSetDscpCommand, inet::TcpSetTimeToLiveCommand, inet::TcpSetOptionCommand, inet::TcpAcceptCommand, inet::TcpOpenCommand, and inet::TcpErrorInfo.
 {return new TcpCommand(*this);}
getUserId()
virtual int inet::TcpCommand::getUserId () const virtual
Referenced by inet::NetPerfMeter::handleMessage(), and inet::tcp::TcpConnection::process_QUEUE_BYTES_LIMIT().
operator=()
TcpCommand& inet::TcpCommand::operator= (const TcpCommand & other)
operator==()
bool inet::TcpCommand::operator== (const TcpCommand &) protected delete
parsimPack()
virtual void inet::TcpCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::TcpStatusInfo, inet::TcpConnectInfo, inet::TcpAvailableInfo, inet::TcpSetTosCommand, inet::TcpSetDscpCommand, inet::TcpSetTimeToLiveCommand, inet::TcpSetOptionCommand, inet::TcpAcceptCommand, inet::TcpOpenCommand, and inet::TcpErrorInfo.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TcpCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::TcpStatusInfo, inet::TcpConnectInfo, inet::TcpAvailableInfo, inet::TcpSetTosCommand, inet::TcpSetDscpCommand, inet::TcpSetTimeToLiveCommand, inet::TcpSetOptionCommand, inet::TcpAcceptCommand, inet::TcpOpenCommand, and inet::TcpErrorInfo.
Referenced by inet::doParsimUnpacking().
setUserId()
virtual void inet::TcpCommand::setUserId (int userId) virtual
Referenced by inet::tcp::TcpConnection::sendIndicationToApp(), and inet::NetPerfMeter::sendTCPQueueRequest().
Member Data Documentation
userId
int inet::TcpCommand::userId = -1 protected
The documentation for this class was generated from the following file:
TcpCommand_m.h