INET Framework for OMNeT++/OMNEST: inet::dymo::RreqBackoffTimer Class Reference
inet::dymo::RreqBackoffTimer Class Reference
Class generated from inet/routing/dymo/Dymo.msg:65 by opp_msgtool.
#include <Dymo_m.h>
Public Member Functions
RreqBackoffTimer (const char *name=nullptr, short kind=0)
RreqBackoffTimer (const RreqBackoffTimer &other)
virtual ~RreqBackoffTimer ()
RreqBackoffTimer & operator= (const RreqBackoffTimer &other)
virtual RreqBackoffTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getRetryCount () const
virtual void setRetryCount (int retryCount)
Public Member Functions inherited from inet::dymo::RreqTimer
RreqTimer (const char *name=nullptr, short kind=0)
RreqTimer (const RreqTimer &other)
virtual ~RreqTimer ()
RreqTimer & operator= (const RreqTimer &other)
virtual const ::inet::L3Address & getTarget () const
virtual ::inet::L3Address & getTargetForUpdate ()
virtual void setTarget (const ::inet::L3Address &target)
Protected Member Functions
bool operator== (const RreqBackoffTimer &)=delete
Protected Member Functions inherited from inet::dymo::RreqTimer
bool operator== (const RreqTimer &)=delete
Protected Attributes
int retryCount = 0
Protected Attributes inherited from inet::dymo::RreqTimer
::inet::L3Address target
Private Member Functions
void copy (const RreqBackoffTimer &other)
Detailed Description
Class generated from inet/routing/dymo/Dymo.msg:65 by opp_msgtool.
message RreqBackoffTimer extends RreqTimer
{
    int retryCount;
}
Constructor & Destructor Documentation
RreqBackoffTimer() [1/2]
inet::dymo::RreqBackoffTimer::RreqBackoffTimer (const char * name = nullptr, short kind = 0)
RreqBackoffTimer() [2/2]
inet::dymo::RreqBackoffTimer::RreqBackoffTimer (const RreqBackoffTimer & other)
~RreqBackoffTimer()
virtual inet::dymo::RreqBackoffTimer::~RreqBackoffTimer () virtual
Member Function Documentation
copy()
void inet::dymo::RreqBackoffTimer::copy (const RreqBackoffTimer & other) private
dup()
virtual RreqBackoffTimer* inet::dymo::RreqBackoffTimer::dup () const inline override virtual
Reimplemented from inet::dymo::RreqTimer.
 {return new RreqBackoffTimer(*this);}
getRetryCount()
virtual int inet::dymo::RreqBackoffTimer::getRetryCount () const virtual
Referenced by inet::dymo::Dymo::processRreqBackoffTimer(), and inet::dymo::Dymo::scheduleRreqBackoffTimer().
operator=()
RreqBackoffTimer& inet::dymo::RreqBackoffTimer::operator= (const RreqBackoffTimer & other)
operator==()
bool inet::dymo::RreqBackoffTimer::operator== (const RreqBackoffTimer &) protected delete
parsimPack()
virtual void inet::dymo::RreqBackoffTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::dymo::RreqTimer.
Referenced by inet::dymo::doParsimPacking().
parsimUnpack()
virtual void inet::dymo::RreqBackoffTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::dymo::RreqTimer.
Referenced by inet::dymo::doParsimUnpacking().
setRetryCount()
virtual void inet::dymo::RreqBackoffTimer::setRetryCount (int retryCount) virtual
Referenced by inet::dymo::Dymo::createRreqBackoffTimer().
Member Data Documentation
retryCount
int inet::dymo::RreqBackoffTimer::retryCount = 0 protected
The documentation for this class was generated from the following file:
Dymo_m.h