INET Framework for OMNeT++/OMNEST: inet::physicallayer::TransmissionBase Class Reference
inet::physicallayer::TransmissionBase Class Reference
#include <TransmissionBase.h>
Public Member Functions
TransmissionBase (const IRadio *transmitter, const Packet *packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation)
virtual int getId () const override
Returns an identifier for this transmission which is globally unique for the whole lifetime of the simulation among all transmissions.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IRadio * getTransmitter () const override
Returns the transmitter that transmitted this radio signal on the radio channel.
virtual int getTransmitterId () const override
Returns the transmitter's id that transmitted this radio signal on the radio channel.
virtual const IAntennaGain * getTransmitterAntennaGain () const override
Returns the gain of the transmitting antenna.
virtual const IRadioMedium * getMedium () const override
Returns the radio medium used for this transmission.
virtual const Packet * getPacket () const override
Returns the packet corresponding to this transmission.
virtual const simtime_t getStartTime () const override
Returns the time when the transmitter started this transmission.
virtual const simtime_t getEndTime () const override
Returns the time when the transmitter ended this transmission.
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getPreambleStartTime () const override
virtual const simtime_t getPreambleEndTime () const override
virtual const simtime_t getHeaderStartTime () const override
virtual const simtime_t getHeaderEndTime () const override
virtual const simtime_t getDataStartTime () const override
virtual const simtime_t getDataEndTime () const override
virtual const simtime_t getDuration () const override
Returns the total length of this transmission.
virtual const simtime_t getDuration (IRadioSignal::SignalPart part) const override
Returns the length of the provided part of this transmission.
virtual const simtime_t getPreambleDuration () const override
Returns the length of the preamble part of this transmission.
virtual const simtime_t getHeaderDuration () const override
Returns the length of the header part of this transmission.
virtual const simtime_t getDataDuration () const override
Returns the length of the data part of this transmission.
virtual const Coord & getStartPosition () const override
Returns the antenna's position when the transmitter started this transmission.
virtual const Coord & getEndPosition () const override
Returns the antenna's position when the transmitter ended this transmission.
virtual const Quaternion & getStartOrientation () const override
Returns the antenna's orientation when the transmitter started this transmission.
virtual const Quaternion & getEndOrientation () const override
Returns the antenna's orientation when the transmitter ended this transmission.
virtual const ITransmissionAnalogModel * getAnalogModel () const override
Returns the analog model of the transmitted signal.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const int id
const IRadioMedium * radioMedium
const int transmitterId
Ptr< const IAntennaGain > transmitterGain
const Packet * packet
const simtime_t startTime
const simtime_t endTime
const simtime_t preambleDuration
const simtime_t headerDuration
const simtime_t dataDuration
const Coord startPosition
const Coord endPosition
const Quaternion startOrientation
const Quaternion endOrientation
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Protected Attributes inherited from inet::physicallayer::ITransmission
static int nextId = 0
Constructor & Destructor Documentation
TransmissionBase()
inet::physicallayer::TransmissionBase::TransmissionBase (const IRadio * transmitter, const Packet * packet, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord & startPosition, const Coord & endPosition, const Quaternion & startOrientation, const Quaternion & endOrientation)
                                                                                                                                                                                                                                                                                                                                                                   :
     id(nextId++),
     radioMedium(transmitter->getMedium()),
     transmitterId(transmitter->getId()),
     transmitterGain(transmitter->getAntenna()->getGain()),
     packet(packet),
     startTime(startTime),
     endTime(endTime),
     preambleDuration(preambleDuration),
     headerDuration(headerDuration),
     dataDuration(dataDuration),
     startPosition(startPosition),
     endPosition(endPosition),
     startOrientation(startOrientation),
     endOrientation(endOrientation)
 {
 }
Member Function Documentation
getAnalogModel()
virtual const ITransmissionAnalogModel* inet::physicallayer::TransmissionBase::getAnalogModel () const inline override virtual
Returns the analog model of the transmitted signal.
Implements inet::physicallayer::ITransmission.
Reimplemented in inet::physicallayer::LayeredTransmission.
 { return check_and_cast<const ITransmissionAnalogModel *>(this); }
getDataDuration()
virtual const simtime_t inet::physicallayer::TransmissionBase::getDataDuration () const inline override virtual
Returns the length of the data part of this transmission.
Implements inet::physicallayer::ITransmission.
 { return dataDuration; }
Referenced by getDuration().
getDataEndTime()
virtual const simtime_t inet::physicallayer::TransmissionBase::getDataEndTime () const inline override virtual
Implements inet::physicallayer::ITransmission.
 { return endTime; }
Referenced by getEndTime().
getDataStartTime()
virtual const simtime_t inet::physicallayer::TransmissionBase::getDataStartTime () const inline override virtual
Implements inet::physicallayer::ITransmission.
 { return endTime - dataDuration; }
Referenced by getStartTime().
getDuration() [1/2]
virtual const simtime_t inet::physicallayer::TransmissionBase::getDuration () const inline override virtual
Returns the total length of this transmission.
Implements inet::physicallayer::ITransmission.
 { return endTime - startTime; }
Referenced by getDuration().
getDuration() [2/2]
const simtime_t inet::physicallayer::TransmissionBase::getDuration (IRadioSignal::SignalPart part) const override virtual
Returns the length of the provided part of this transmission.
Implements inet::physicallayer::ITransmission.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getDuration();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleDuration();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderDuration();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataDuration();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getEndOrientation()
virtual const Quaternion& inet::physicallayer::TransmissionBase::getEndOrientation () const inline override virtual
Returns the antenna's orientation when the transmitter ended this transmission.
Implements inet::physicallayer::ITransmission.
 { return endOrientation; }
getEndPosition()
virtual const Coord& inet::physicallayer::TransmissionBase::getEndPosition () const inline override virtual
Returns the antenna's position when the transmitter ended this transmission.
Implements inet::physicallayer::ITransmission.
 { return endPosition; }
getEndTime() [1/2]
virtual const simtime_t inet::physicallayer::TransmissionBase::getEndTime () const inline override virtual
Returns the time when the transmitter ended this transmission.
It is the end of the last bit's transmission.
Implements inet::physicallayer::ITransmission.
 { return endTime; }
Referenced by getEndTime().
getEndTime() [2/2]
const simtime_t inet::physicallayer::TransmissionBase::getEndTime (IRadioSignal::SignalPart part) const override virtual
Implements inet::physicallayer::ITransmission.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getEndTime();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleEndTime();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderEndTime();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataEndTime();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getHeaderDuration()
virtual const simtime_t inet::physicallayer::TransmissionBase::getHeaderDuration () const inline override virtual
Returns the length of the header part of this transmission.
Implements inet::physicallayer::ITransmission.
 { return headerDuration; }
Referenced by getDuration().
getHeaderEndTime()
virtual const simtime_t inet::physicallayer::TransmissionBase::getHeaderEndTime () const inline override virtual
Implements inet::physicallayer::ITransmission.
 { return endTime - dataDuration; }
Referenced by getEndTime().
getHeaderStartTime()
virtual const simtime_t inet::physicallayer::TransmissionBase::getHeaderStartTime () const inline override virtual
Implements inet::physicallayer::ITransmission.
 { return startTime + preambleDuration; }
Referenced by getStartTime().
getId()
virtual int inet::physicallayer::TransmissionBase::getId () const inline override virtual
Returns an identifier for this transmission which is globally unique for the whole lifetime of the simulation among all transmissions.
Implements inet::physicallayer::ITransmission.
 { return id; }
getMedium()
virtual const IRadioMedium* inet::physicallayer::TransmissionBase::getMedium () const inline override virtual
Returns the radio medium used for this transmission.
This function never return nullptr.
Implements inet::physicallayer::ITransmission.
 { return radioMedium; }
getPacket()
virtual const Packet* inet::physicallayer::TransmissionBase::getPacket () const inline override virtual
Returns the packet corresponding to this transmission.
This function never returns nullptr.
Implements inet::physicallayer::ITransmission.
Reimplemented in inet::physicallayer::LayeredTransmission.
 { return packet; }
getPreambleDuration()
virtual const simtime_t inet::physicallayer::TransmissionBase::getPreambleDuration () const inline override virtual
Returns the length of the preamble part of this transmission.
Implements inet::physicallayer::ITransmission.
 { return preambleDuration; }
Referenced by getDuration().
getPreambleEndTime()
virtual const simtime_t inet::physicallayer::TransmissionBase::getPreambleEndTime () const inline override virtual
Implements inet::physicallayer::ITransmission.
 { return startTime + preambleDuration; }
Referenced by getEndTime().
getPreambleStartTime()
virtual const simtime_t inet::physicallayer::TransmissionBase::getPreambleStartTime () const inline override virtual
Implements inet::physicallayer::ITransmission.
 { return startTime; }
Referenced by getStartTime().
getStartOrientation()
virtual const Quaternion& inet::physicallayer::TransmissionBase::getStartOrientation () const inline override virtual
Returns the antenna's orientation when the transmitter started this transmission.
Implements inet::physicallayer::ITransmission.
 { return startOrientation; }
getStartPosition()
virtual const Coord& inet::physicallayer::TransmissionBase::getStartPosition () const inline override virtual
Returns the antenna's position when the transmitter started this transmission.
Implements inet::physicallayer::ITransmission.
 { return startPosition; }
getStartTime() [1/2]
virtual const simtime_t inet::physicallayer::TransmissionBase::getStartTime () const inline override virtual
Returns the time when the transmitter started this transmission.
It is the start of the first bit's transmission.
Implements inet::physicallayer::ITransmission.
 { return startTime; }
Referenced by getStartTime().
getStartTime() [2/2]
const simtime_t inet::physicallayer::TransmissionBase::getStartTime (IRadioSignal::SignalPart part) const override virtual
Implements inet::physicallayer::ITransmission.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getStartTime();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleStartTime();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderStartTime();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataStartTime();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getTransmitter()
const IRadio * inet::physicallayer::TransmissionBase::getTransmitter () const override virtual
Returns the transmitter that transmitted this radio signal on the radio channel.
This function may return nullptr.
Implements inet::physicallayer::ITransmission.
 {
     return radioMedium->getRadio(transmitterId);
 }
getTransmitterAntennaGain()
virtual const IAntennaGain* inet::physicallayer::TransmissionBase::getTransmitterAntennaGain () const inline override virtual
Returns the gain of the transmitting antenna.
Implements inet::physicallayer::ITransmission.
 { return transmitterGain.get(); }
getTransmitterId()
virtual int inet::physicallayer::TransmissionBase::getTransmitterId () const inline override virtual
Returns the transmitter's id that transmitted this radio signal on the radio channel.
Implements inet::physicallayer::ITransmission.
 { return transmitterId; }
printToStream()
std::ostream & inet::physicallayer::TransmissionBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::LayeredTransmission, inet::physicallayer::UnitDiskTransmission, inet::physicallayer::NarrowbandTransmissionBase, inet::physicallayer::DimensionalTransmission, inet::physicallayer::FlatTransmissionBase, inet::physicallayer::ScalarTransmission, inet::physicallayer::Ieee80211UnitDiskTransmission, inet::physicallayer::Ieee80211LayeredTransmission, inet::physicallayer::Ieee80211DimensionalTransmission, inet::physicallayer::Ieee80211ScalarTransmission, inet::physicallayer::ApskDimensionalTransmission, and inet::physicallayer::ApskScalarTransmission.
 {
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(id);
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(transmitterId)
                << EV_FIELD(startTime)
                << EV_FIELD(endTime)
                << EV_FIELD(preambleDuration)
                << EV_FIELD(headerDuration)
                << EV_FIELD(dataDuration)
                << EV_FIELD(startPosition)
                << EV_FIELD(endPosition)
                << EV_FIELD(startOrientation)
                << EV_FIELD(endOrientation);
     return stream;
 }
Referenced by inet::physicallayer::NarrowbandTransmissionBase::printToStream(), inet::physicallayer::UnitDiskTransmission::printToStream(), and inet::physicallayer::LayeredTransmission::printToStream().
Member Data Documentation
dataDuration
const simtime_t inet::physicallayer::TransmissionBase::dataDuration protected
Referenced by printToStream().
endOrientation
const Quaternion inet::physicallayer::TransmissionBase::endOrientation protected
Referenced by printToStream().
endPosition
const Coord inet::physicallayer::TransmissionBase::endPosition protected
Referenced by printToStream().
endTime
const simtime_t inet::physicallayer::TransmissionBase::endTime protected
Referenced by printToStream().
headerDuration
const simtime_t inet::physicallayer::TransmissionBase::headerDuration protected
Referenced by printToStream().
id
const int inet::physicallayer::TransmissionBase::id protected
packet
const Packet* inet::physicallayer::TransmissionBase::packet protected
preambleDuration
const simtime_t inet::physicallayer::TransmissionBase::preambleDuration protected
Referenced by printToStream().
radioMedium
const IRadioMedium* inet::physicallayer::TransmissionBase::radioMedium protected
Referenced by getTransmitter().
startOrientation
const Quaternion inet::physicallayer::TransmissionBase::startOrientation protected
Referenced by printToStream().
startPosition
const Coord inet::physicallayer::TransmissionBase::startPosition protected
Referenced by printToStream().
startTime
const simtime_t inet::physicallayer::TransmissionBase::startTime protected
Referenced by printToStream().
transmitterGain
Ptr<const IAntennaGain> inet::physicallayer::TransmissionBase::transmitterGain protected
transmitterId
const int inet::physicallayer::TransmissionBase::transmitterId protected
Referenced by getTransmitter(), and printToStream().
The documentation for this class was generated from the following files:
TransmissionBase.h
TransmissionBase.cc