INET Framework for OMNeT++/OMNEST: inet::HelloTimerMsg Class Reference
inet::HelloTimerMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:96 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
HelloTimerMsg (const char *name=nullptr, short kind=0)
HelloTimerMsg (const HelloTimerMsg &other)
virtual ~HelloTimerMsg ()
HelloTimerMsg & operator= (const HelloTimerMsg &other)
virtual HelloTimerMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ipv4Address & getPeer () const
virtual Ipv4Address & getPeerForUpdate ()
virtual void setPeer (const Ipv4Address &peer)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const HelloTimerMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
Ipv4Address peer
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const HelloTimerMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:96 by opp_msgtool.
//
// FIXME missing documentation
//
message HelloTimerMsg extends SignallingMsg
{
    Ipv4Address peer;
    command = MSG_HELLO_TIMER;
}
Constructor & Destructor Documentation
HelloTimerMsg() [1/2]
inet::HelloTimerMsg::HelloTimerMsg (const char * name = nullptr, short kind = 0)
HelloTimerMsg() [2/2]
inet::HelloTimerMsg::HelloTimerMsg (const HelloTimerMsg & other)
~HelloTimerMsg()
virtual inet::HelloTimerMsg::~HelloTimerMsg () virtual
Member Function Documentation
copy()
void inet::HelloTimerMsg::copy (const HelloTimerMsg & other) private
dup()
virtual HelloTimerMsg* inet::HelloTimerMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new HelloTimerMsg(*this);}
getPeer()
virtual const Ipv4Address& inet::HelloTimerMsg::getPeer () const virtual
Referenced by inet::RsvpTe::processHELLO_TIMER().
getPeerForUpdate()
virtual Ipv4Address& inet::HelloTimerMsg::getPeerForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<HelloTimerMsg*>(this)->getPeer());}
operator=()
HelloTimerMsg& inet::HelloTimerMsg::operator= (const HelloTimerMsg & other)
operator==()
bool inet::HelloTimerMsg::operator== (const HelloTimerMsg &) protected delete
parsimPack()
virtual void inet::HelloTimerMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::HelloTimerMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setPeer()
virtual void inet::HelloTimerMsg::setPeer (const Ipv4Address & peer) virtual
Member Data Documentation
peer
Ipv4Address inet::HelloTimerMsg::peer protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h