INET Framework for OMNeT++/OMNEST: inet::BitVector Class Reference
inet::BitVector Class Reference
#include <BitVector.h>
Public Member Functions
BitVector ()
BitVector (const char *bits)
BitVector (unsigned int bits)
BitVector (unsigned int bits, unsigned int fixedSize)
BitVector (const BitVector &other)
BitVector (const std::vector< uint8_t > &bytes)
unsigned int toDecimal () const
unsigned int reverseToDecimal () const
void appendBit (bool value)
void appendBit (bool value, int n)
void setBit (int pos, bool value)
void toggleBit (int pos)
bool getBit (int pos) const
void appendByte (uint8_t value)
unsigned int getSize () const
unsigned int getNumberOfBytes () const
const std::vector< uint8_t > & getBytes () const
int computeHammingDistance (const BitVector &u) const
BitVector & operator= (const BitVector &rhs)
bool operator== (const BitVector &rhs) const
bool operator!= (const BitVector &rhs) const
std::string toString () const
Private Member Functions
int containerSize () const
void stringToBitVector (const char *str)
void copy (const BitVector &other)
Private Attributes
std::vector< uint8_t > bytes
int size
Friends
std::ostream & operator<< (std::ostream &out, const BitVector &bitVector)
Constructor & Destructor Documentation
BitVector() [1/6]
inet::BitVector::BitVector ()
 {
     size = 0;
     bytes.push_back(uint8_t(0));
 }
BitVector() [2/6]
inet::BitVector::BitVector (const char * bits)
 {
     size = 0;
     stringToBitVector(bits);
 }
BitVector() [3/6]
inet::BitVector::BitVector (unsigned int bits)
 {
     size = 0;
     if (bits == 0)
         appendBit(false);
     while (bits > 0) {
         appendBit(bits % 2);
         bits /= 2;
     }
 }
BitVector() [4/6]
inet::BitVector::BitVector (unsigned int bits, unsigned int fixedSize)
 {
     this->size = 0;
     if (bits == 0)
         appendBit(false);
     while (bits > 0) {
         appendBit(bits % 2);
         bits /= 2;
     }
     if (getSize() < size)
         appendBit(false, size - getSize());
 }
BitVector() [5/6]
inet::BitVector::BitVector (const BitVector & other) inline
 { copy(other); }
BitVector() [6/6]
inet::BitVector::BitVector (const std::vector< uint8_t > & bytes) inline
 : bytes(bytes), size(bytes.size() * 8) {}
Member Function Documentation
appendBit() [1/2]
void inet::BitVector::appendBit (bool value)
 {
     setBit(size, value);
 }
Referenced by appendBit(), appendByte(), BitVector(), copy(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldBitModel(), inet::physicallayer::ApskDemodulator::demodulate(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulate(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol(), inet::physicallayer::ConvolutionalCoder::depuncturing(), inet::physicallayer::Ieee80211OfdmEncoder::encode(), inet::physicallayer::ApskEncoder::encode(), inet::physicallayer::ConvolutionalCoder::encode(), inet::physicallayer::AdditiveScrambler::generateScramblingSequence(), inet::physicallayer::ConvolutionalCoder::getPuncturedIndices(), inet::physicallayer::ConvolutionalCoder::puncturing(), inet::physicallayer::AdditiveScrambler::scramble(), stringToBitVector(), and inet::physicallayer::ConvolutionalCoder::traversePath().
appendBit() [2/2]
void inet::BitVector::appendBit (bool value, int n)
 {
     while (n--)
         appendBit(value);
 }
appendByte()
void inet::BitVector::appendByte (uint8_t value)
 {
     for (unsigned int i = 0; i < 8; i++)
         appendBit(value & (1 << i));
 }
computeHammingDistance()
int inet::BitVector::computeHammingDistance (const BitVector & u) const
 {
     if (getSize() != u.getSize())
         throw cRuntimeError("You can't compute Hamming distance between two vectors with different sizes");
     int hammingDistance = 0;
     for (unsigned int i = 0; i < getSize(); i++)
         if (u.getBit(i) != getBit(i))
             hammingDistance++;
     return hammingDistance;
 }
containerSize()
int inet::BitVector::containerSize () const inline private
 { return bytes.size() * 8; }
Referenced by setBit().
copy()
void inet::BitVector::copy (const BitVector & other) private
 {
     size = 0;
     bytes.clear();
     for (unsigned int i = 0; i < other.getSize(); i++)
         appendBit(other.getBit(i));
 }
Referenced by operator=().
getBit()
bool inet::BitVector::getBit (int pos) const
 {
     if (pos >= size)
         throw cRuntimeError("Out of range with bit position %d", pos);
     uint8_t field = bytes[pos / UINT8_LENGTH];
     return field & (1 << (pos % UINT8_LENGTH));
 }
Referenced by computeHammingDistance(), copy(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211OfdmDecoder::createPacketModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldBitModel(), inet::physicallayer::ApskDecoder::decode(), inet::physicallayer::Ieee80211OfdmInterleaver::deinterleave(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulate(), inet::physicallayer::ConvolutionalCoder::depuncturing(), inet::physicallayer::ConvolutionalCoder::encode(), inet::physicallayer::Ieee80211OfdmDecoder::getSignalFieldLength(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::getSignalFieldLength(), inet::physicallayer::Ieee80211OfdmDecoder::getSignalFieldRate(), inet::physicallayer::ConvolutionalCoder::giveNextOutputSymbol(), inet::physicallayer::Ieee80211OfdmInterleaver::interleave(), inet::physicallayer::ApskModulator::modulate(), inet::physicallayer::Ieee80211OfdmModulator::modulate(), inet::operator<<(), operator==(), inet::ieee80211::QosAckHandler::processReceivedBlockAck(), inet::physicallayer::ConvolutionalCoder::puncturing(), reverseToDecimal(), inet::physicallayer::AdditiveScrambler::scramble(), toDecimal(), toString(), and inet::physicallayer::ConvolutionalCoder::traversePath().
getBytes()
const std::vector<uint8_t>& inet::BitVector::getBytes () const inline
 { return bytes; }
Referenced by inet::physicallayer::Ieee80211OfdmDecoder::createPacketModel(), inet::physicallayer::ApskDecoder::decode(), and inet::physicallayer::Ieee80211OfdmEncoder::encode().
getNumberOfBytes()
unsigned int inet::BitVector::getNumberOfBytes () const inline
 { return bytes.size(); }
getSize()
unsigned int inet::BitVector::getSize () const inline
 { return size; }
Referenced by BitVector(), inet::physicallayer::LayeredErrorModelBase::computeBitModel(), inet::physicallayer::Ieee80211OfdmErrorModel::computeBitModel(), computeHammingDistance(), copy(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211OfdmDecoder::createPacketModel(), inet::physicallayer::ApskDecoder::decode(), inet::physicallayer::ConvolutionalCoder::decode(), inet::physicallayer::Ieee80211OfdmInterleaver::deinterleave(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulate(), inet::physicallayer::ConvolutionalCoder::depuncturing(), inet::physicallayer::ConvolutionalCoder::encode(), inet::physicallayer::ConvolutionalCoder::giveNextOutputSymbol(), inet::physicallayer::Ieee80211OfdmInterleaver::interleave(), inet::physicallayer::ApskModulator::modulate(), inet::physicallayer::Ieee80211OfdmModulator::modulate(), operator==(), inet::physicallayer::ConvolutionalCoder::puncturing(), reverseToDecimal(), inet::physicallayer::AdditiveScrambler::scramble(), toDecimal(), toString(), and inet::physicallayer::ConvolutionalCoder::traversePath().
operator!=()
bool inet::BitVector::operator!= (const BitVector & rhs) const
 {
     return !(rhs == *this);
 }
operator=()
BitVector & inet::BitVector::operator= (const BitVector & rhs)
 {
     if (this == &rhs)
         return *this;
     copy(rhs);
     return *this;
 }
operator==()
bool inet::BitVector::operator== (const BitVector & rhs) const
 {
     if (rhs.getSize() != getSize())
         return false;
     for (unsigned int i = 0; i < getSize(); i++)
         if (getBit(i) != rhs.getBit(i))
             return false;
     return true;
 }
reverseToDecimal()
unsigned int inet::BitVector::reverseToDecimal () const
 {
     unsigned int dec = 0;
     unsigned int powerOfTwo = 1;
     for (int i = getSize() - 1; i >= 0; i--) {
         if (getBit(i))
             dec += powerOfTwo;
         powerOfTwo *= 2;
     }
     return dec;
 }
setBit()
void inet::BitVector::setBit (int pos, bool value)
 {
     while (containerSize() <= pos)
         bytes.push_back(uint8_t(0));
     if (pos + 1 > size)
         size = pos + 1;
     uint8_t& field = bytes[pos / UINT8_LENGTH];
     if (value)
         field |= 1 << (pos % UINT8_LENGTH);
     else
         field &= ~(1 << (pos % UINT8_LENGTH));
 }
Referenced by appendBit(), inet::ieee80211::RecipientBlockAckProcedure::buildBlockAck(), inet::physicallayer::Ieee80211OfdmInterleaver::deinterleave(), inet::physicallayer::ConvolutionalCoder::getPuncturedIndices(), and inet::physicallayer::Ieee80211OfdmInterleaver::interleave().
stringToBitVector()
void inet::BitVector::stringToBitVector (const char * str) private
 {
     int strSize = strlen(str);
     for (int i = 0; i < strSize; i++) {
         if (str[i] == '1')
             appendBit(true);
         else if (str[i] == '0')
             appendBit(false);
         else
             throw cRuntimeError("str must represent a binary number");
     }
 }
Referenced by BitVector().
toDecimal()
unsigned int inet::BitVector::toDecimal () const
 {
     unsigned int dec = 0;
     unsigned int powerOfTwo = 1;
     for (unsigned int i = 0; i < getSize(); i++) {
         if (getBit(i))
             dec += powerOfTwo;
         powerOfTwo *= 2;
     }
     return dec;
 }
toggleBit()
void inet::BitVector::toggleBit (int pos)
 {
     if (pos >= size)
         throw cRuntimeError("Out of range with bit position %d", pos);
     uint8_t& field = bytes[pos / UINT8_LENGTH];
     field ^= 1 << (pos % UINT8_LENGTH);
 }
Referenced by inet::physicallayer::LayeredErrorModelBase::computeBitModel(), and inet::physicallayer::Ieee80211OfdmErrorModel::corruptBits().
toString()
std::string inet::BitVector::toString () const
 {
     std::string str;
     for (unsigned int i = 0; i < getSize(); i++) {
         if (getBit(i))
             str += "1";
         else
             str += "0";
     }
     return str;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const BitVector & bitVector) friend
 {
     if (bitVector.getBit(0))
         out << "1";
     else
         out << "0";
     for (int i = 1; i < bitVector.size; i++) {
         if (bitVector.getBit(i))
             out << " 1";
         else
             out << " 0";
     }
     return out;
 }
Member Data Documentation
bytes
std::vector<uint8_t> inet::BitVector::bytes private
Referenced by BitVector(), copy(), getBit(), setBit(), and toggleBit().
size
int inet::BitVector::size private
Referenced by appendBit(), BitVector(), copy(), getBit(), inet::operator<<(), setBit(), and toggleBit().
The documentation for this class was generated from the following files:
BitVector.h
BitVector.cc