INET Framework for OMNeT++/OMNEST: inet::RsbRefreshTimerMsg Class Reference
inet::RsbRefreshTimerMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:66 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
RsbRefreshTimerMsg (const char *name=nullptr, short kind=0)
RsbRefreshTimerMsg (const RsbRefreshTimerMsg &other)
virtual ~RsbRefreshTimerMsg ()
RsbRefreshTimerMsg & operator= (const RsbRefreshTimerMsg &other)
virtual RsbRefreshTimerMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getId () const
virtual void setId (int id)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const RsbRefreshTimerMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
int id = 0
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const RsbRefreshTimerMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:66 by opp_msgtool.
//
// FIXME missing documentation
//
message RsbRefreshTimerMsg extends SignallingMsg
{
    int id;
    command = MSG_RSB_REFRESH_TIMER;
}
Constructor & Destructor Documentation
RsbRefreshTimerMsg() [1/2]
inet::RsbRefreshTimerMsg::RsbRefreshTimerMsg (const char * name = nullptr, short kind = 0)
RsbRefreshTimerMsg() [2/2]
inet::RsbRefreshTimerMsg::RsbRefreshTimerMsg (const RsbRefreshTimerMsg & other)
~RsbRefreshTimerMsg()
virtual inet::RsbRefreshTimerMsg::~RsbRefreshTimerMsg () virtual
Member Function Documentation
copy()
void inet::RsbRefreshTimerMsg::copy (const RsbRefreshTimerMsg & other) private
dup()
virtual RsbRefreshTimerMsg* inet::RsbRefreshTimerMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new RsbRefreshTimerMsg(*this);}
getId()
virtual int inet::RsbRefreshTimerMsg::getId () const virtual
Referenced by inet::RsvpTe::processRSB_REFRESH_TIMER().
operator=()
RsbRefreshTimerMsg& inet::RsbRefreshTimerMsg::operator= (const RsbRefreshTimerMsg & other)
operator==()
bool inet::RsbRefreshTimerMsg::operator== (const RsbRefreshTimerMsg &) protected delete
parsimPack()
virtual void inet::RsbRefreshTimerMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::RsbRefreshTimerMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setId()
virtual void inet::RsbRefreshTimerMsg::setId (int id) virtual
Referenced by inet::RsvpTe::createEgressRSB(), and inet::RsvpTe::createRSB().
Member Data Documentation
id
int inet::RsbRefreshTimerMsg::id = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h