INET Framework for OMNeT++/OMNEST: inet::power::IEpEnergySource Class Reference
inet::power::IEpEnergySource Class Reference abstract
This class is an interface that should be implemented by power based energy source models to integrate with other parts of the power based model.
#include <IEpEnergySource.h>
Public Member Functions
virtual W getTotalPowerConsumption () const =0
Returns the total power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
virtual int getNumEnergyConsumers () const =0
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const =0
Returns the energy consumer for the provided index.
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer)=0
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer)=0
Removes a previously added energy consumer from this energy source.
Static Public Attributes
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Detailed Description
This class is an interface that should be implemented by power based energy source models to integrate with other parts of the power based model.
Such an energy source model describes its total energy consumption in terms of power consumption
See the corresponding NED file for more details.
Member Function Documentation
getTotalPowerConsumption()
virtual W inet::power::IEpEnergySource::getTotalPowerConsumption () const pure virtual
Returns the total power consumption in the range [0, +infinity).
Implemented in inet::power::EpEnergySourceBase.
Referenced by inet::power::SimpleEpEnergyManagement::scheduleLifecycleOperationTimer().
Member Data Documentation
powerConsumptionChangedSignal
simsignal_t inet::power::IEpEnergySource::powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged") static
The signal that is used to publish power consumption changes.
Referenced by inet::power::SimpleEpEnergyManagement::initialize(), inet::power::SimpleEpEnergyManagement::receiveSignal(), inet::power::AlternatingEpEnergyConsumer::updatePowerConsumption(), and inet::power::EpEnergyStorageBase::updateTotalPowerConsumption().
The documentation for this class was generated from the following files:
IEpEnergySource.h
IEpEnergySource.cc