INET Framework for OMNeT++/OMNEST: inet::TcpAvailableInfo Class Reference
inet::TcpAvailableInfo Class Reference
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:161 by opp_msgtool.
#include <TcpCommand_m.h>
Public Member Functions
TcpAvailableInfo ()
TcpAvailableInfo (const TcpAvailableInfo &other)
virtual ~TcpAvailableInfo ()
TcpAvailableInfo & operator= (const TcpAvailableInfo &other)
virtual TcpAvailableInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getNewSocketId () const
virtual void setNewSocketId (int newSocketId)
Public Member Functions inherited from inet::TcpCommand
TcpCommand ()
TcpCommand (const TcpCommand &other)
virtual ~TcpCommand ()
TcpCommand & operator= (const TcpCommand &other)
virtual int getUserId () const
virtual void setUserId (int userId)
Protected Member Functions
bool operator== (const TcpAvailableInfo &)=delete
Protected Member Functions inherited from inet::TcpCommand
bool operator== (const TcpCommand &)=delete
Protected Attributes
L3Address localAddr
L3Address remoteAddr
int localPort = 0
int remotePort = 0
int newSocketId = 0
Protected Attributes inherited from inet::TcpCommand
int userId = -1
Private Member Functions
void copy (const TcpAvailableInfo &other)
Detailed Description
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:161 by opp_msgtool.
//
// Sent with message kind TCP_I_AVAILABLE, to let the app know
// about the local and remote IP address and port.
//
// @see ~TcpCommandCode, ~ITcp
//
class TcpAvailableInfo extends TcpCommand
{
    L3Address localAddr;
    L3Address remoteAddr;
    int localPort;
    int remotePort;
    int newSocketId;
}
Constructor & Destructor Documentation
TcpAvailableInfo() [1/2]
inet::TcpAvailableInfo::TcpAvailableInfo ()
TcpAvailableInfo() [2/2]
inet::TcpAvailableInfo::TcpAvailableInfo (const TcpAvailableInfo & other)
~TcpAvailableInfo()
virtual inet::TcpAvailableInfo::~TcpAvailableInfo () virtual
Member Function Documentation
copy()
void inet::TcpAvailableInfo::copy (const TcpAvailableInfo & other) private
dup()
virtual TcpAvailableInfo* inet::TcpAvailableInfo::dup () const inline override virtual
Reimplemented from inet::TcpCommand.
 {return new TcpAvailableInfo(*this);}
getLocalAddr()
virtual const L3Address& inet::TcpAvailableInfo::getLocalAddr () const virtual
Referenced by inet::TcpSocket::TcpSocket().
getLocalAddrForUpdate()
virtual L3Address& inet::TcpAvailableInfo::getLocalAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<TcpAvailableInfo*>(this)->getLocalAddr());}
getLocalPort()
virtual int inet::TcpAvailableInfo::getLocalPort () const virtual
Referenced by inet::TcpSocket::TcpSocket().
getNewSocketId()
virtual int inet::TcpAvailableInfo::getNewSocketId () const virtual
Referenced by inet::TcpServerSocketIo::acceptSocket(), inet::NetPerfMeter::handleMessage(), inet::TcpSocket::processMessage(), inet::TcpServerHostApp::socketAvailable(), inet::TcpAppBase::socketAvailable(), inet::TcpServerThreadBase::socketAvailable(), inet::bgp::BgpRouter::socketAvailable(), inet::Ldp::socketAvailable(), and inet::TcpSocket::TcpSocket().
getRemoteAddr()
virtual const L3Address& inet::TcpAvailableInfo::getRemoteAddr () const virtual
Referenced by inet::TcpSocket::TcpSocket().
getRemoteAddrForUpdate()
virtual L3Address& inet::TcpAvailableInfo::getRemoteAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<TcpAvailableInfo*>(this)->getRemoteAddr());}
getRemotePort()
virtual int inet::TcpAvailableInfo::getRemotePort () const virtual
Referenced by inet::TcpSocket::TcpSocket().
operator=()
TcpAvailableInfo& inet::TcpAvailableInfo::operator= (const TcpAvailableInfo & other)
operator==()
bool inet::TcpAvailableInfo::operator== (const TcpAvailableInfo &) protected delete
parsimPack()
virtual void inet::TcpAvailableInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::TcpCommand.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TcpAvailableInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::TcpCommand.
Referenced by inet::doParsimUnpacking().
setLocalAddr()
virtual void inet::TcpAvailableInfo::setLocalAddr (const L3Address & localAddr) virtual
Referenced by inet::tcp::TcpLwipConnection::sendAvailableIndicationToApp(), and inet::tcp::TcpConnection::sendAvailableIndicationToApp().
setLocalPort()
virtual void inet::TcpAvailableInfo::setLocalPort (int localPort) virtual
Referenced by inet::tcp::TcpLwipConnection::sendAvailableIndicationToApp(), and inet::tcp::TcpConnection::sendAvailableIndicationToApp().
setNewSocketId()
virtual void inet::TcpAvailableInfo::setNewSocketId (int newSocketId) virtual
Referenced by inet::tcp::TcpLwipConnection::sendAvailableIndicationToApp(), and inet::tcp::TcpConnection::sendAvailableIndicationToApp().
setRemoteAddr()
virtual void inet::TcpAvailableInfo::setRemoteAddr (const L3Address & remoteAddr) virtual
Referenced by inet::tcp::TcpLwipConnection::sendAvailableIndicationToApp(), and inet::tcp::TcpConnection::sendAvailableIndicationToApp().
setRemotePort()
virtual void inet::TcpAvailableInfo::setRemotePort (int remotePort) virtual
Referenced by inet::tcp::TcpLwipConnection::sendAvailableIndicationToApp(), and inet::tcp::TcpConnection::sendAvailableIndicationToApp().
Member Data Documentation
localAddr
L3Address inet::TcpAvailableInfo::localAddr protected
localPort
int inet::TcpAvailableInfo::localPort = 0 protected
newSocketId
int inet::TcpAvailableInfo::newSocketId = 0 protected
remoteAddr
L3Address inet::TcpAvailableInfo::remoteAddr protected
remotePort
int inet::TcpAvailableInfo::remotePort = 0 protected
The documentation for this class was generated from the following file:
TcpCommand_m.h