INET Framework for OMNeT++/OMNEST: inet::Quaternion Class Reference
inet::Quaternion Class Reference
#include <Quaternion.h>
Public Member Functions
Quaternion ()
basic ctors
Quaternion (double real, double i, double j, double k)
Quaternion (double real, const Coord &imag)
Quaternion (const Coord &axis, double angle)
constructs a Quaternion from a normalized axis - angle pair rotation
Quaternion (const EulerAngles &angles)
from 3 euler angles
double getS () const
void setS (double s)
const Coord & getV () const
void setV (const Coord &v)
bool operator== (const Quaternion &q)
basic operations
bool operator!= (const Quaternion &q)
Quaternion & operator= (const Quaternion &q)
const Quaternion operator+ (const Quaternion &q) const
const Quaternion operator- (const Quaternion &q) const
const Quaternion operator* (const Quaternion &q) const
const Quaternion operator/ (const Quaternion &q) const
const Quaternion operator* (double scale) const
const Quaternion operator/ (double scale) const
const Quaternion operator- () const
const Quaternion & operator+= (const Quaternion &q)
const Quaternion & operator-= (const Quaternion &q)
const Quaternion & operator*= (const Quaternion &q)
const Quaternion & operator*= (double scale)
const Quaternion & operator/= (double scale)
double length () const
gets the length of this Quaternion
double lengthSquared () const
gets the squared length of this Quaternion
void normalize ()
normalizes this Quaternion
Quaternion normalized () const
returns the normalized version of this Quaternion
void conjugate ()
computes the conjugate of this Quaternion
Quaternion conjugated () const
void invert ()
inverts this Quaternion
Quaternion inverse () const
returns the inverse of this Quaternion
Coord getRotationAxis () const
returns the axis and angle of this unit Quaternion
double getRotationAngle () const
void getRotationAxisAndAngle (Coord &axis, double &angle) const
Coord rotate (const Coord &v) const
rotates v by this quaternion (quaternion must be unit)
EulerAngles toEulerAngles (bool homogenous=false) const
returns the euler angles from a rotation Quaternion
void getSwingAndTwist (const Coord &direction, Quaternion &swing, Quaternion &twist) const
Decompose the rotation on to 2 parts.
std::string str () const
Static Public Member Functions
static double dot (const Quaternion &q1, const Quaternion &q2)
computes the dot product of 2 quaternions
static Quaternion lerp (const Quaternion &q1, const Quaternion &q2, double t)
linear quaternion interpolation
static Quaternion slerp (const Quaternion &q1, const Quaternion &q2, double t)
spherical linear interpolation
static Quaternion rotationFromTo (const Coord &from, const Coord &to)
Public Attributes
double s = 1
the real component
Coord v
the imaginary components
Static Public Attributes
static Quaternion IDENTITY = Quaternion()
static Quaternion NIL = Quaternion(NaN, NaN, NaN, NaN)
Constructor & Destructor Documentation
Quaternion() [1/5]
inet::Quaternion::Quaternion () inline
basic ctors
 {}
Referenced by getSwingAndTwist(), operator*(), and rotationFromTo().
Quaternion() [2/5]
inet::Quaternion::Quaternion (double real, double i, double j, double k) inline
 : s(real), v(i, j, k) {}
Quaternion() [3/5]
inet::Quaternion::Quaternion (double real, const Coord & imag) inline
 : s(real), v(imag) {}
Quaternion() [4/5]
inet::Quaternion::Quaternion (const Coord & axis, double angle)
constructs a Quaternion from a normalized axis - angle pair rotation
                                                       : Quaternion(std::cos(angle / 2), axis * std::sin(angle / 2))
 {
     // nothing
 }
Quaternion() [5/5]
inet::Quaternion::Quaternion (const EulerAngles & angles) explicit
from 3 euler angles
 {
     double cos_z_2 = std::cos(0.5 * rad(angles.alpha).get());
     double cos_y_2 = std::cos(0.5 * rad(angles.beta).get());
     double cos_x_2 = std::cos(0.5 * rad(angles.gamma).get());
     double sin_z_2 = std::sin(0.5 * rad(angles.alpha).get());
     double sin_y_2 = std::sin(0.5 * rad(angles.beta).get());
     double sin_x_2 = std::sin(0.5 * rad(angles.gamma).get());
     // and now compute Quaternion
     s = cos_z_2 * cos_y_2 * cos_x_2 + sin_z_2 * sin_y_2 * sin_x_2;
     v.x = cos_z_2 * cos_y_2 * sin_x_2 - sin_z_2 * sin_y_2 * cos_x_2;
     v.y = cos_z_2 * sin_y_2 * cos_x_2 + sin_z_2 * cos_y_2 * sin_x_2;
     v.z = sin_z_2 * cos_y_2 * cos_x_2 - cos_z_2 * sin_y_2 * sin_x_2;
 }
Member Function Documentation
conjugate()
void inet::Quaternion::conjugate () inline
computes the conjugate of this Quaternion
 { v = -v; }
Referenced by rotate().
conjugated()
Quaternion inet::Quaternion::conjugated () const inline
 { return Quaternion(s, -v.x, -v.y, -v.z); }
Referenced by getSwingAndTwist().
dot()
static double inet::Quaternion::dot (const Quaternion & q1, const Quaternion & q2) inline static
computes the dot product of 2 quaternions
 { return q1.v * q2.v + q1.s * q2.s; }
Referenced by slerp().
getRotationAngle()
double inet::Quaternion::getRotationAngle () const inline
 { return std::acos(s) * 2; }
getRotationAxis()
Coord inet::Quaternion::getRotationAxis () const inline
returns the axis and angle of this unit Quaternion
 { Coord axis; double angle; getRotationAxisAndAngle(axis, angle); return axis; }
getRotationAxisAndAngle()
void inet::Quaternion::getRotationAxisAndAngle (Coord & axis, double & angle) const
 {
     angle = std::acos(s);
     // pre-compute to save time
     double sin_theta_inv = 1.0 / std::sin(angle);
     // now the vector
     axis.x = v.x * sin_theta_inv;
     axis.y = v.y * sin_theta_inv;
     axis.z = v.z * sin_theta_inv;
     angle *= 2;
 }
Referenced by inet::AttachedMobility::getCurrentVelocity(), inet::MobilityBase::updateDisplayStringFromMobilityState(), and inet::StationaryMobility::updateMobilityStateFromDisplayString().
getS()
double inet::Quaternion::getS () const inline
 { return s; }
getSwingAndTwist()
void inet::Quaternion::getSwingAndTwist (const Coord & direction, Quaternion & swing, Quaternion & twist) const
Decompose the rotation on to 2 parts.
Twist - rotation around the "direction" vector
Swing - rotation around axis that is perpendicular to "direction" vector The rotation can be composed back by rotation = swing * twist
has singularity in case of swing_rotation close to 180 degrees rotation. if the input quaternion is of non-unit length, the outputs are non-unit as well otherwise, outputs are both unit
 {
     Coord p = direction * (v * direction); // return projection v1 on to v2  (parallel component)
     twist = Quaternion(s, p);
     twist.normalize();
     swing = *this * twist.conjugated();
 }
Referenced by inet::StationaryMobility::updateMobilityStateFromDisplayString().
getV()
const Coord& inet::Quaternion::getV () const inline
 { return v; }
inverse()
Quaternion inet::Quaternion::inverse () const inline
returns the inverse of this Quaternion
 { Quaternion q(*this); q.invert(); return q; }
Referenced by inet::physicallayer::AnalogModelBase::computeAntennaGain(), inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::getValue(), inet::physicallayer::SpaceDependentAttenuationFunction::getValue(), operator/(), and inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe().
invert()
void inet::Quaternion::invert () inline
inverts this Quaternion
 { conjugate(); *this /= lengthSquared(); }
Referenced by inverse().
length()
double inet::Quaternion::length () const inline
gets the length of this Quaternion
 { return std::sqrt(s * s + v * v); }
lengthSquared()
double inet::Quaternion::lengthSquared () const inline
gets the squared length of this Quaternion
 { return s * s + v * v; }
lerp()
static Quaternion inet::Quaternion::lerp (const Quaternion & q1, const Quaternion & q2, double t) inline static
linear quaternion interpolation
 { return (q1 * (1 - t) + q2 * t).normalized(); }
Referenced by slerp().
normalize()
void inet::Quaternion::normalize () inline
normalizes this Quaternion
 { *this /= length(); }
Referenced by inet::MassMobility::setTargetPosition().
normalized()
Quaternion inet::Quaternion::normalized () const inline
returns the normalized version of this Quaternion
 { return (*this) / length(); }
Referenced by lerp().
operator!=()
bool inet::Quaternion::operator!= (const Quaternion & q) inline
 { return !(*this == q); }
operator*() [1/2]
const Quaternion inet::Quaternion::operator* (const Quaternion & q) const
 {
     return Quaternion(s * q.s - v * q.v,
                       v.y * q.v.z - v.z * q.v.y + s * q.v.x + v.x * q.s,
                       v.z * q.v.x - v.x * q.v.z + s * q.v.y + v.y * q.s,
                       v.x * q.v.y - v.y * q.v.x + s * q.v.z + v.z * q.s);
 }
operator*() [2/2]
const Quaternion inet::Quaternion::operator* (double scale) const inline
 { return Quaternion(s * scale, v * scale); }
operator*=() [1/2]
const Quaternion & inet::Quaternion::operator*= (const Quaternion & q)
 {
     double x = v.x, y = v.y, z = v.z, sn = s * q.s - v * q.v;
     v.x = y * q.v.z - z * q.v.y + s * q.v.x + x * q.s;
     v.y = z * q.v.x - x * q.v.z + s * q.v.y + y * q.s;
     v.z = x * q.v.y - y * q.v.x + s * q.v.z + z * q.s;
     s = sn;
     return *this;
 }
operator*=() [2/2]
const Quaternion& inet::Quaternion::operator*= (double scale) inline
 { s *= scale; v *= scale; return *this; }
operator+()
const Quaternion inet::Quaternion::operator+ (const Quaternion & q) const inline
 { return Quaternion(s + q.s, v + q.v); }
operator+=()
const Quaternion& inet::Quaternion::operator+= (const Quaternion & q) inline
 { v += q.v; s += q.s; return *this; }
operator-() [1/2]
const Quaternion inet::Quaternion::operator- () const inline
 { return Quaternion(-s, -v); }
operator-() [2/2]
const Quaternion inet::Quaternion::operator- (const Quaternion & q) const inline
 { return Quaternion(s - q.s, v - q.v); }
operator-=()
const Quaternion& inet::Quaternion::operator-= (const Quaternion & q) inline
 { v -= q.v; s -= q.s; return *this; }
operator/() [1/2]
const Quaternion inet::Quaternion::operator/ (const Quaternion & q) const inline
 { return (*this) * q.inverse(); }
operator/() [2/2]
const Quaternion inet::Quaternion::operator/ (double scale) const inline
 { return Quaternion(s / scale, v / scale); }
operator/=()
const Quaternion& inet::Quaternion::operator/= (double scale) inline
 { s /= scale; v /= scale; return *this; }
operator=()
Quaternion& inet::Quaternion::operator= (const Quaternion & q) inline
 { s = q.s; v = q.v; return *this; }
operator==()
bool inet::Quaternion::operator== (const Quaternion & q) inline
basic operations
 { return s == q.s && v == q.v; }
rotate()
Coord inet::Quaternion::rotate (const Coord & v) const
rotates v by this quaternion (quaternion must be unit)
 {
     Quaternion V(0, v);
     Quaternion conjugate(*this);
     conjugate.conjugate();
     return (*this * V * conjugate).v;
 }
Referenced by inet::physicallayer::ParabolicAntenna::AntennaGain::computeGain(), inet::physicallayer::CosineAntenna::AntennaGain::computeGain(), inet::physicallayer::AxiallySymmetricAntenna::AntennaGain::computeGain(), inet::physicallayer::DipoleAntenna::AntennaGain::computeGain(), inet::TurtleMobility::executeStatement(), inet::SuperpositioningMobility::getCurrentAngularPosition(), inet::LinearMobility::initialize(), inet::VehicleMobility::orient(), and inet::MassMobility::setTargetPosition().
rotationFromTo()
Quaternion inet::Quaternion::rotationFromTo (const Coord & from, const Coord & to) static
 {
     // Based on Stan Melax's article in Game Programming Gems
     // Copy, since cannot modify local
     Coord v0 = from;
     Coord v1 = to;
     v0.normalize();
     v1.normalize();
     double d = v0 * v1;
     if (d >= 1.0f) { // If dot == 1, vectors are the same
         return Quaternion(1, 0, 0, 0); // identity
     }
     else if (d <= -1.0f) { // exactly opposite
         Coord axis = Coord(1, 0, 0) % v0;
         if (axis.length() == 0)
             axis = Coord(0, 1, 0) % v0;
         // same as fromAxisAngle(axis, PI).normalize();
         return Quaternion(0, axis.x, axis.y, axis.z).normalized();
     }
     double s = std::sqrt((1 + d) * 2);
     Coord c = (v0 % v1) / s;
     return Quaternion(s * 0.5, c.x, c.y, c.z).normalized();
 }
Referenced by inet::physicallayer::AnalogModelBase::computeAntennaGain(), inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::getValue(), inet::physicallayer::SpaceDependentAttenuationFunction::getValue(), inet::VehicleMobility::orient(), and inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe().
setS()
void inet::Quaternion::setS (double s) inline
 { this->s = s; }
setV()
void inet::Quaternion::setV (const Coord & v) inline
 { this->v = v; }
slerp()
Quaternion inet::Quaternion::slerp (const Quaternion & q1, const Quaternion & q2, double t) static
spherical linear interpolation
casting to a 4x4 isomorphic matrix for left multiplication with vector
 {
     Quaternion q3;
     double dot = Quaternion::dot(q1, q2);
     /*  dot = cos(theta)
         if (dot < 0), q1 and q2 are more than 90 degrees apart,
         so we can invert one to reduce spinning */
     if (dot < 0) {
         dot = -dot;
         q3 = -q2;
     }
     else q3 = q2;
     if (dot < 0.95) {
         double angle = std::acos(dot);
         return (q1 * std::sin(angle * (1 - t)) + q3 * std::sin(angle * t)) / std::sin(angle);
     }
     else // if the angle is small, use linear interpolation
         return lerp(q1, q3, t);
 }
Referenced by inet::LinearRotatingMobilityBase::rotate().
str()
std::string inet::Quaternion::str () const inline
 {
     std::stringstream os;
     os << *this;
     return os.str();
 }
Referenced by inet::MobilityBase::DirectiveResolver::resolveDirective().
toEulerAngles()
EulerAngles inet::Quaternion::toEulerAngles (bool homogenous = false) const
returns the euler angles from a rotation Quaternion
 {
     // NOTE: this algorithm is prone to gimbal lock when beta is close to +-90
     double sqw = s * s;
     double sqx = v.x * v.x;
     double sqy = v.y * v.y;
     double sqz = v.z * v.z;
     EulerAngles euler;
     if (homogenous) {
         euler.gamma = rad(std::atan2(2.0 * (v.x * v.y + v.z * s), sqx - sqy - sqz + sqw));
         euler.beta = rad(std::asin(math::minnan(1.0, math::maxnan(-1.0, -2.0 * (v.x * v.z - v.y * s)))));
         euler.alpha = rad(std::atan2(2.0 * (v.y * v.z + v.x * s), -sqx - sqy + sqz + sqw));
     }
     else {
         euler.gamma = rad(std::atan2(2.0 * (v.z * v.y + v.x * s), 1 - 2 * (sqx + sqy)));
         euler.beta = rad(std::asin(math::minnan(1.0, math::maxnan(-1.0, -2.0 * (v.x * v.z - v.y * s)))));
         euler.alpha = rad(std::atan2(2.0 * (v.x * v.y + v.z * s), 1 - 2 * (sqy + sqz)));
     }
     euler.normalize();
     return euler;
 }
Referenced by inet::physicallayer::InterpolatingAntenna::AntennaGain::computeGain(), inet::physicallayer::DielectricObstacleLoss::computeObjectLoss(), inet::physicallayer::IdealObstacleLoss::isObstacle(), inet::visualizer::PhysicalEnvironmentOsgVisualizer::refreshDisplay(), and inet::visualizer::PhysicalEnvironmentCanvasVisualizer::refreshDisplay().
Member Data Documentation
IDENTITY
Quaternion inet::Quaternion::IDENTITY = Quaternion() static
Referenced by inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), inet::StationaryMobilityBase::getCurrentAngularAcceleration(), inet::CircleMobility::getCurrentAngularAcceleration(), inet::SuperpositioningMobility::getCurrentAngularAcceleration(), inet::SuperpositioningMobility::getCurrentAngularPosition(), inet::StationaryMobilityBase::getCurrentAngularVelocity(), inet::SuperpositioningMobility::getCurrentAngularVelocity(), inet::visualizer::VisualizerBase::getOrientation(), inet::SimpleGeographicCoordinateSystem::getSceneOrientation(), and inet::MobilityBase::updateDisplayStringFromMobilityState().
NIL
Quaternion inet::Quaternion::NIL = Quaternion(NaN, NaN, NaN, NaN) static
Referenced by inet::FacingMobility::getCurrentAngularAcceleration(), inet::SuperpositioningMobility::getCurrentAngularAcceleration(), inet::FacingMobility::getCurrentAngularVelocity(), inet::SuperpositioningMobility::getCurrentAngularVelocity(), inet::MobilityBase::handleIfOutside(), and inet::MobilityBase::reflectIfOutside().
s
double inet::Quaternion::s = 1
the real component
Referenced by inet::osg::createPositionAttitudeTransform(), dot(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), inet::operator<<(), operator=(), operator==(), inet::MobilityBase::reflectIfOutside(), inet::RotationMatrix::RotationMatrix(), and toEulerAngles().
v
Coord inet::Quaternion::v
the imaginary components
Referenced by inet::osg::createPositionAttitudeTransform(), dot(), getRotationAxisAndAngle(), getSwingAndTwist(), operator*(), operator*=(), operator+(), operator+=(), operator-(), operator-=(), inet::operator<<(), operator=(), operator==(), Quaternion(), inet::MobilityBase::reflectIfOutside(), rotate(), inet::RotationMatrix::RotationMatrix(), and toEulerAngles().
The documentation for this class was generated from the following files:
Quaternion.h
Quaternion.cc