INET Framework for OMNeT++/OMNEST: inet::OscillatorBase Class Reference
inet::OscillatorBase Class Reference
#include <OscillatorBase.h>
Public Member Functions
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::IOscillator
virtual ~IOscillator ()
virtual simtime_t getNominalTickLength () const =0
Returns the nominal time interval between subsequent ticks.
virtual simtime_t getComputationOrigin () const =0
Returns the oscillator computation origin from which the ticks are measured.
virtual int64_t computeTicksForInterval (simtime_t timeInterval) const =0
Returns the number of ticks in the specified time interval measured from the oscillator computation origin.
virtual simtime_t computeIntervalForTicks (int64_t numTicks) const =0
Returns the smallest simulation time interval for the specified number of ticks measured from the oscillator computation origin.
Static Public Attributes
static simsignal_t driftRateChangedSignal = cComponent::registerSignal("driftRateChanged")
Static Public Attributes inherited from inet::IOscillator
static simsignal_t preOscillatorStateChangedSignal = cComponent::registerSignal("preOscillatorStateChanged")
static simsignal_t postOscillatorStateChangedSignal = cComponent::registerSignal("postOscillatorStateChanged")
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void updateDisplayString () const
Protected Attributes
const char * displayStringTextFormat = nullptr
Member Function Documentation
initialize()
void inet::OscillatorBase::initialize (int stage) override protected virtual
Reimplemented in inet::RandomDriftOscillator, inet::DriftingOscillatorBase, inet::IdealOscillator, and inet::ConstantDriftOscillator.
 {
     if (stage == INITSTAGE_LOCAL)
         displayStringTextFormat = par("displayStringTextFormat");
     else if (stage == INITSTAGE_LAST)
         updateDisplayString();
 }
Referenced by inet::IdealOscillator::initialize(), and inet::DriftingOscillatorBase::initialize().
numInitStages()
virtual int inet::OscillatorBase::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
resolveDirective()
const char * inet::OscillatorBase::resolveDirective (char directive) const override virtual
Implements inet::StringFormat::IDirectiveResolver.
Reimplemented in inet::DriftingOscillatorBase.
 {
     static std::string result;
     switch (directive) {
         case 'n':
             result = getNominalTickLength().str() + " s";
             break;
         case 'o':
             result = getComputationOrigin().str() + " s";
             break;
         default:
             throw cRuntimeError("Unknown directive: %c", directive);
     }
     return result.c_str();
 }
Referenced by inet::DriftingOscillatorBase::resolveDirective().
updateDisplayString()
void inet::OscillatorBase::updateDisplayString () const protected virtual
 {
     if (getEnvir()->isGUI()) {
         auto text = StringFormat::formatString(displayStringTextFormat, this);
         getDisplayString().setTagArg("t", 0, text);
     }
 }
Referenced by initialize(), inet::DriftingOscillatorBase::setDriftRate(), and inet::DriftingOscillatorBase::setTickOffset().
Member Data Documentation
displayStringTextFormat
const char* inet::OscillatorBase::displayStringTextFormat = nullptr protected
Referenced by initialize(), and updateDisplayString().
driftRateChangedSignal
simsignal_t inet::OscillatorBase::driftRateChangedSignal = cComponent::registerSignal("driftRateChanged") static
Referenced by inet::IdealOscillator::finish(), inet::IdealOscillator::initialize(), and inet::DriftingOscillatorBase::setDriftRate().
The documentation for this class was generated from the following files:
OscillatorBase.h
OscillatorBase.cc