INET Framework for OMNeT++/OMNEST: inet::MemoryInputStream Class Reference
inet::MemoryInputStream Class Reference
This class provides an efficient in memory bit input stream.
#include <MemoryInputStream.h>
Public Member Functions
MemoryInputStream (const std::vector< uint8_t > &data, b length=b(-1), b position=b(0))
MemoryInputStream (const uint8_t *buffer, b length, b position=b(0))
Stream querying functions
bool isReadBeyondEnd () const
Returns true if a read operation ever read beyond the end of the stream.
b getLength () const
Returns the total length of the stream measured in bits.
b getRemainingLength () const
Returns the remaining unread length of the stream measured in bits.
b getPosition () const
Returns the current read position of the stream measured in bits.
const std::vector< uint8_t > & getData () const
void copyData (std::vector< bool > &result, b offset=b(0), b length=b(-1)) const
void copyData (std::vector< uint8_t > &result, B offset=B(0), B length=B(-1)) const
Stream updating functions
void seek (b position)
Updates the read position of the stream.
Bit streaming functions
bool readBit ()
Reads a bit at the current position of the stream.
bool readBitRepeatedly (bool value, size_t count)
Reads the same bit repeatedly at the current position of the stream.
b readBits (std::vector< bool > &bits, b length)
Reads a sequence of bits at the current position of the stream keeping the original bit order.
Byte streaming functions
uint8_t readByte ()
Reads a byte at the current position of the stream in MSB to LSB bit order.
bool readByteRepeatedly (uint8_t value, size_t count)
Reads the same byte repeatedly at the current position of the stream in MSB to LSB bit order.
B readBytes (std::vector< uint8_t > &bytes, B length)
Reads a sequence of bytes at the current position of the stream keeping the original byte order in MSB to LSB bit order.
B readBytes (uint8_t *buffer, B length)
Reads a sequence of bytes at the current position of the stream keeping the original byte order in MSB to LSB bit order.
Basic type streaming functions
uint8_t readUint2 ()
Reads a 2 bit unsigned integer at the current position of the stream in MSB to LSB bit order.
uint8_t readUint4 ()
Reads a 4 bit unsigned integer at the current position of the stream in MSB to LSB bit order.
uint8_t readUint8 ()
Reads an 8 bit unsigned integer at the current position of the stream in MSB to LSB bit order.
uint16_t readUint16Be ()
Reads a 16 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
uint16_t readUint16Le ()
Reads a 16 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
uint32_t readUint24Be ()
Reads a 24 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
uint32_t readUint24Le ()
Reads a 24 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
uint32_t readUint32Be ()
Reads a 32 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
uint32_t readUint32Le ()
Reads a 32 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
uint64_t readUint48Be ()
Reads a 48 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
uint64_t readUint48Le ()
Reads a 48 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
uint64_t readUint64Be ()
Reads a 64 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
uint64_t readUint64Le ()
Reads a 64 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
INET specific type streaming functions
MacAddress readMacAddress ()
Reads a MAC address at the current position of the stream in big endian byte order and MSB to LSB bit order.
Ipv4Address readIpv4Address ()
Reads an Ipv4 address at the current position of the stream in big endian byte order and MSB to LSB bit order.
Ipv6Address readIpv6Address ()
Reads an Ipv6 address at the current position of the stream in big endian byte order and MSB to LSB bit order.
other useful streaming functions
std::string readString ()
Reads a string from the current position until a zero.
uint64_t readNBitsToUint64Be (uint8_t n)
Reads n bits of a 64 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
Protected Member Functions
bool isByteAligned ()
Protected Attributes
std::vector< uint8_t > data
This vector contains the bits that are read from this stream.
b length
The length of the bit stream measured in bits.
b position
The position of the next bit that will be read measured in bits.
bool isReadBeyondEnd_ = false
This flag indicates if the stream has been read beyond the end of data.
Detailed Description
This class provides an efficient in memory bit input stream.
The stream provides a set of read functions that read data at the current position of the stream. Most functions are implemented in the header to allow inlining.
Constructor & Destructor Documentation
MemoryInputStream() [1/2]
inet::MemoryInputStream::MemoryInputStream (const std::vector< uint8_t > & data, b length = b(-1), b position = b(0)) inline
                                                                                            :
         data(data),
         length(length == b(-1) ? b(data.size() * 8) : length),
         position(position)
     {
         assert(b(0) <= this->length);
         assert(b(0) <= position && position <= this->length);
     }
MemoryInputStream() [2/2]
inet::MemoryInputStream::MemoryInputStream (const uint8_t * buffer, b length, b position = b(0)) inline
                                                                           :
         data(buffer, buffer + B(length).get()),
         length(length),
         position(position)
     {
         assert(b(0) <= this->length);
         assert(b(0) <= position && position <= this->length);
     }
Member Function Documentation
copyData() [1/2]
void inet::MemoryInputStream::copyData (std::vector< bool > & result, b offset = b(0), b length = b(-1)) const inline
{
         size_t end = b(length == b(-1) ? this->length : offset + length).get();
         for (size_t i = b(offset).get(); i < end; i++) {
             size_t byteIndex = i / 8;
             size_t bitIndex = i % 8;
             uint8_t byte = data.at(byteIndex);
             uint8_t mask = 1 << (7 - bitIndex);
             bool bit = byte & mask;
             result.push_back(bit);
         }
     }
Referenced by inet::FieldsChunkSerializer::deserialize().
copyData() [2/2]
void inet::MemoryInputStream::copyData (std::vector< uint8_t > & result, B offset = B(0), B length = B(-1)) const inline
{
         auto end = length == B(-1) ? B(data.size()) : offset + length;
         assert(b(0) <= offset && offset <= B(data.size()));
         assert(b(0) <= end && end <= B(data.size()));
         assert(offset <= end);
         result.insert(result.begin(), data.begin() + B(offset).get(), data.begin() + B(end).get());
     }
getData()
const std::vector<uint8_t>& inet::MemoryInputStream::getData () const inline
 { return data; }
Referenced by inet::physicallayer::EthernetPhyHeaderBaseSerializer::deserialize().
getLength()
b inet::MemoryInputStream::getLength () const inline
Returns the total length of the stream measured in bits.
 { return length; }
getPosition()
b inet::MemoryInputStream::getPosition () const inline
Returns the current read position of the stream measured in bits.
 { return position; }
Referenced by inet::ApplicationPacketSerializer::deserialize(), inet::EtherAppReqSerializer::deserialize(), inet::UnitDiskPhyHeaderSerializer::deserialize(), inet::VoipStreamPacketSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::physicallayer::ApskPhyHeaderSerializer::deserialize(), inet::BMacHeaderSerializer::deserialize(), inet::GenericAppMsgSerializer::deserialize(), inet::ospf::OspfPacketSerializer::deserialize(), inet::CsmaCaMacHeaderSerializer::deserialize(), inet::AckingMacHeaderSerializer::deserialize(), inet::GptpPacketSerializer::deserialize(), inet::Ipv4HeaderSerializer::deserialize(), inet::tcp::TcpHeaderSerializer::deserialize(), inet::FieldsChunkSerializer::deserialize(), inet::EtherAppRespSerializer::deserialize(), inet::Chunk::deserialize(), inet::Ipv4HeaderSerializer::deserializeOption(), inet::ArpPacketSerializer::readIpv4Address(), and inet::ArpPacketSerializer::readMacAddress().
getRemainingLength()
b inet::MemoryInputStream::getRemainingLength () const inline
Returns the remaining unread length of the stream measured in bits.
 { return length - position; }
Referenced by inet::BitCountChunkSerializer::deserialize(), inet::BitsChunkSerializer::deserialize(), inet::BytesChunkSerializer::deserialize(), inet::ByteCountChunkSerializer::deserialize(), inet::rtp::RtcpPacketSerializer::deserialize(), inet::PimPacketSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::sctp::SctpHeaderSerializer::deserialize(), inet::Ipv4HeaderSerializer::deserialize(), and inet::deserializeIpv6NdOptions().
isByteAligned()
bool inet::MemoryInputStream::isByteAligned () inline protected
{
         return b(position).get() % 8 == 0;
     }
isReadBeyondEnd()
bool inet::MemoryInputStream::isReadBeyondEnd () const inline
Returns true if a read operation ever read beyond the end of the stream.
 { return isReadBeyondEnd_; }
Referenced by inet::Chunk::deserialize().
readBit()
bool inet::MemoryInputStream::readBit () inline
Reads a bit at the current position of the stream.
                    {
         if (position == length) {
             isReadBeyondEnd_ = true;
             return false;
         }
         else {
             size_t i = b(position).get();
             size_t byteIndex = i / 8;
             size_t bitIndex = i % 8;
             position += b(1);
             uint8_t byte = data.at(byteIndex);
             uint8_t mask = 1 << (7 - bitIndex);
             return byte & mask;
         }
     }
Referenced by inet::Ipv6HeaderSerializer::deserialize(), inet::rtp::RtcpPacketSerializer::deserialize(), inet::rtp::RtpPacketSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::MplsPacketSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::PimPacketSerializer::deserialize(), inet::aodv::AodvControlPacketsSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeOspfOptions(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa().
readBitRepeatedly()
bool inet::MemoryInputStream::readBitRepeatedly (bool value, size_t count) inline
Reads the same bit repeatedly at the current position of the stream.
{
         bool success = true;
         for (size_t i = 0; i < count; i++)
             success &= (value == readBit());
         return success;
     }
Referenced by inet::BitCountChunkSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::UnitDiskPhyHeaderSerializer::deserialize(), inet::BMacHeaderSerializer::deserialize(), inet::physicallayer::ApskPhyHeaderSerializer::deserialize(), and inet::bgp::BgpHeaderSerializer::deserialize().
readBits()
b inet::MemoryInputStream::readBits (std::vector< bool > & bits, b length) inline
Reads a sequence of bits at the current position of the stream keeping the original bit order.
{
         b i;
         for (i = b(0); i < length; i++) {
             if (isReadBeyondEnd_)
                 break;
             bits.push_back(readBit());
         }
         return b(i);
     }
Referenced by inet::BitsChunkSerializer::deserialize().
readByte()
uint8_t inet::MemoryInputStream::readByte () inline
Reads a byte at the current position of the stream in MSB to LSB bit order.
{
         if (position + B(1) > length) {
             isReadBeyondEnd_ = true;
             position = length;
             return 0;
         }
         else {
             uint8_t result;
             if (isByteAligned())
                 result = data[B(position).get()];
             else {
                 int l1 = b(position).get() % 8;
                 int l2 = 8 - l1;
                 result = data[B(position - b(l1)).get()] << l1;
                 result |= data[B(position + b(l2)).get()] >> l2;
             }
             position += B(1);
             return result;
         }
     }
Referenced by inet::Ieee8021aeTagTpidHeaderSerializer::deserialize(), inet::Ieee8022LlcHeaderSerializer::deserialize(), inet::Ipv6HeaderSerializer::deserialize(), inet::rtp::RtcpPacketSerializer::deserialize(), inet::GenericAppMsgSerializer::deserialize(), inet::VoipStreamPacketSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::BMacHeaderSerializer::deserialize(), inet::IcmpHeaderSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::Icmpv6HeaderSerializer::deserialize(), inet::PimPacketSerializer::deserialize(), inet::aodv::AodvControlPacketsSerializer::deserialize(), inet::CsmaCaMacHeaderSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::ArpPacketSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::deserialize(), inet::Ieee8021aeTagEpdHeaderSerializer::deserialize(), inet::physicallayer::EthernetPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211DsssPhyHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::physicallayer::EthernetFragmentPhyHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MpduSubframeHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211HrDsssPhyHeaderSerializer::deserialize(), inet::deserializeIpv6NdOptions(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::Ipv4HeaderSerializer::deserializeOption(), inet::tcp::TcpHeaderSerializer::deserializeOption(), inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa().
readByteRepeatedly()
bool inet::MemoryInputStream::readByteRepeatedly (uint8_t value, size_t count) inline
Reads the same byte repeatedly at the current position of the stream in MSB to LSB bit order.
{
         bool success = true;
         for (size_t i = 0; i < count; i++)
             success &= (value == readByte());
         return success;
     }
Referenced by inet::ByteCountChunkSerializer::deserialize(), inet::Ipv6HeaderSerializer::deserialize(), inet::ApplicationPacketSerializer::deserialize(), inet::VoipStreamPacketSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::BMacHeaderSerializer::deserialize(), inet::GenericAppMsgSerializer::deserialize(), inet::physicallayer::ApskPhyHeaderSerializer::deserialize(), inet::EtherAppReqSerializer::deserialize(), inet::ospf::OspfPacketSerializer::deserialize(), inet::CsmaCaMacHeaderSerializer::deserialize(), inet::AckingMacHeaderSerializer::deserialize(), inet::EtherAppRespSerializer::deserialize(), inet::physicallayer::EthernetPhyHeaderSerializer::deserialize(), inet::physicallayer::EthernetFragmentPhyHeaderSerializer::deserialize(), inet::GptpPacketSerializer::readGptpPdelayReqPart(), and inet::GptpPacketSerializer::readGptpSyncPart().
readBytes() [1/2]
B inet::MemoryInputStream::readBytes (std::vector< uint8_t > & bytes, B length) inline
Reads a sequence of bytes at the current position of the stream keeping the original byte order in MSB to LSB bit order.
{
         assert(isByteAligned());
         if (position + length > this->length) {
             length = this->length - position;
             isReadBeyondEnd_ = true;
         }
         auto end = position + length;
         assert(b(0) <= position && position <= B(data.size()));
         assert(b(0) <= end && end <= B(data.size()));
         assert(position <= end);
         bytes.insert(bytes.end(), data.begin() + B(position).get(), data.begin() + B(end).get());
         position += length;
         return length;
     }
Referenced by inet::BytesChunkSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::sctp::SctpHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::deserialize(), inet::Ipv4HeaderSerializer::deserialize(), and inet::tcp::TcpHeaderSerializer::deserialize().
readBytes() [2/2]
B inet::MemoryInputStream::readBytes (uint8_t * buffer, B length) inline
Reads a sequence of bytes at the current position of the stream keeping the original byte order in MSB to LSB bit order.
{
         assert(isByteAligned());
         if (position + length > this->length) {
             length = this->length - position;
             isReadBeyondEnd_ = true;
         }
         std::copy(data.begin() + B(position).get(), data.begin() + B(position + length).get(), buffer);
         position += length;
         return length;
     }
readIpv4Address()
Ipv4Address inet::MemoryInputStream::readIpv4Address () inline
Reads an Ipv4 address at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         return Ipv4Address(readUint32Be());
     }
Referenced by inet::DhcpMessageSerializer::deserialize(), inet::DsdvHelloSerializer::deserialize(), inet::RipPacketSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::ospf::OspfPacketSerializer::deserialize(), inet::aodv::AodvControlPacketsSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), inet::Ipv4HeaderSerializer::deserializeOption(), inet::ospfv2::Ospfv2PacketSerializer::deserializeOspfHeader(), inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), and inet::ArpPacketSerializer::readIpv4Address().
readIpv6Address()
Ipv6Address inet::MemoryInputStream::readIpv6Address () inline
Reads an Ipv6 address at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         uint32_t d[4];
         for (auto& element : d)
             element = readUint32Be();
         return Ipv6Address(d[0], d[1], d[2], d[3]);
     }
Referenced by inet::Ipv6HeaderSerializer::deserialize(), inet::Icmpv6HeaderSerializer::deserialize(), inet::aodv::AodvControlPacketsSerializer::deserialize(), and inet::deserializeIpv6NdOptions().
readMacAddress()
MacAddress inet::MemoryInputStream::readMacAddress () inline
Reads a MAC address at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         MacAddress address;
         for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
             address.setAddressByte(i, readByte());
         return address;
     }
Referenced by inet::BMacHeaderSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::EthernetMacAddressFieldsSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::CsmaCaMacHeaderSerializer::deserialize(), inet::AckingMacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::deserialize(), inet::ieee80211::Ieee80211MsduSubframeHeaderSerializer::deserialize(), inet::EthernetMacHeaderSerializer::deserialize(), inet::deserializeIpv6NdOptions(), and inet::ArpPacketSerializer::readMacAddress().
readNBitsToUint64Be()
uint64_t inet::MemoryInputStream::readNBitsToUint64Be (uint8_t n) inline
Reads n bits of a 64 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         if (n == 0 || n > 64)
             throw cRuntimeError("Can not read 0 bit or more than 64 bits.");
         uint64_t mul = 1 << (n - 1);
         uint64_t num = 0;
         for (int i = 0; i < n; ++i) {
             if (readBit())
                 num |= mul;
             mul >>= 1;
         }
         return num;
     }
Referenced by inet::Ipv6HeaderSerializer::deserialize(), inet::rtp::RtcpPacketSerializer::deserialize(), inet::rtp::RtpPacketSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::MplsPacketSerializer::deserialize(), inet::PimPacketSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::aodv::AodvControlPacketsSerializer::deserialize(), inet::physicallayer::Ieee80211FhssPhyHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa().
readString()
std::string inet::MemoryInputStream::readString () inline
Reads a string from the current position until a zero.
{
         std::vector<uint8_t> data;
         while (uint8_t b = readByte())
             data.push_back(b);
         return std::string(data.begin(), data.end());
     }
readUint16Be()
uint16_t inet::MemoryInputStream::readUint16Be () inline
Reads a 16 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         uint16_t value = 0;
         value |= (static_cast<uint16_t>(readByte()) << 8);
         value |= (static_cast<uint16_t>(readByte()) << 0);
         return value;
     }
Referenced by inet::Ieee802EpdHeaderSerializer::deserialize(), inet::EthernetControlFrameSerializer::deserialize(), inet::Ieee8021rTagTpidHeaderSerializer::deserialize(), inet::Ieee8022LlcHeaderSerializer::deserialize(), inet::Ieee8021aeTagTpidHeaderSerializer::deserialize(), inet::Ieee8021qTagTpidHeaderSerializer::deserialize(), inet::Ipv6HeaderSerializer::deserialize(), inet::rtp::RtcpPacketSerializer::deserialize(), inet::rtp::RtpMpegPacketSerializer::deserialize(), inet::rtp::RtpPacketSerializer::deserialize(), inet::UnitDiskPhyHeaderSerializer::deserialize(), inet::physicallayer::ApskPhyHeaderSerializer::deserialize(), inet::IcmpHeaderSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::EchoPacketSerializer::deserialize(), inet::Icmpv6HeaderSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::BMacHeaderSerializer::deserialize(), inet::PimPacketSerializer::deserialize(), inet::PppHeaderSerializer::deserialize(), inet::RipPacketSerializer::deserialize(), inet::SequenceNumberHeaderSerializer::deserialize(), inet::UdpHeaderSerializer::deserialize(), inet::VoipStreamPacketSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::CrcHeaderSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::CsmaCaMacHeaderSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::ospf::OspfPacketSerializer::deserialize(), inet::AckingMacHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211FhssPhyHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::deserialize(), inet::ArpPacketSerializer::deserialize(), inet::Ieee8021qTagEpdHeaderSerializer::deserialize(), inet::Ieee8021rTagEpdHeaderSerializer::deserialize(), inet::Ieee8021aeTagEpdHeaderSerializer::deserialize(), inet::PppTrailerSerializer::deserialize(), inet::EthernetTypeOrLengthFieldSerializer::deserialize(), inet::physicallayer::Ieee80211IrPhyHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MsduSubframeHeaderSerializer::deserialize(), inet::EthernetMacHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::physicallayer::Ieee80211DsssPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211HrDsssPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::deserialize(), inet::deserializeIpv6NdOptions(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::Ipv4HeaderSerializer::deserializeOption(), inet::tcp::TcpHeaderSerializer::deserializeOption(), inet::ospfv2::Ospfv2PacketSerializer::deserializeOspfHeader(), inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), inet::GptpPacketSerializer::readGptpBase(), inet::GptpPacketSerializer::readGptpFollowUpInformationTlv(), and inet::GptpPacketSerializer::readPortIdentity().
readUint16Le()
uint16_t inet::MemoryInputStream::readUint16Le () inline
Reads a 16 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
{
         uint16_t value = 0;
         value |= (static_cast<uint16_t>(readByte()) << 0);
         value |= (static_cast<uint16_t>(readByte()) << 8);
         return value;
     }
Referenced by inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize().
readUint2()
uint8_t inet::MemoryInputStream::readUint2 () inline
Reads a 2 bit unsigned integer at the current position of the stream in MSB to LSB bit order.
{
         uint8_t value = 0;
         if (readBit()) value |= 0x2;
         if (readBit()) value |= 0x1;
         return value;
     }
Referenced by inet::Ipv6HeaderSerializer::deserialize().
readUint24Be()
uint32_t inet::MemoryInputStream::readUint24Be () inline
Reads a 24 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         uint32_t value = 0;
         value |= (static_cast<uint32_t>(readByte()) << 16);
         value |= (static_cast<uint32_t>(readByte()) << 8);
         value |= (static_cast<uint32_t>(readByte()) << 0);
         return value;
     }
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), and inet::GptpPacketSerializer::readGptpFollowUpInformationTlv().
readUint24Le()
uint32_t inet::MemoryInputStream::readUint24Le () inline
Reads a 24 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
{
         uint32_t value = 0;
         value |= (static_cast<uint32_t>(readByte()) << 0);
         value |= (static_cast<uint32_t>(readByte()) << 8);
         value |= (static_cast<uint32_t>(readByte()) << 16);
         return value;
     }
readUint32Be()
uint32_t inet::MemoryInputStream::readUint32Be () inline
Reads a 32 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         uint32_t value = 0;
         value |= (static_cast<uint32_t>(readByte()) << 24);
         value |= (static_cast<uint32_t>(readByte()) << 16);
         value |= (static_cast<uint32_t>(readByte()) << 8);
         value |= (static_cast<uint32_t>(readByte()) << 0);
         return value;
     }
Referenced by inet::Ieee8021aeTagTpidHeaderSerializer::deserialize(), inet::rtp::RtcpPacketSerializer::deserialize(), inet::rtp::RtpPacketSerializer::deserialize(), inet::Ipv6HeaderSerializer::deserialize(), inet::ApplicationPacketSerializer::deserialize(), inet::RipPacketSerializer::deserialize(), inet::IcmpHeaderSerializer::deserialize(), inet::Icmpv6HeaderSerializer::deserialize(), inet::VoipStreamPacketSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::FcsHeaderSerializer::deserialize(), inet::GenericAppMsgSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::DsdvHelloSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::EtherAppReqSerializer::deserialize(), inet::PimPacketSerializer::deserialize(), inet::aodv::AodvControlPacketsSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::Ieee8021aeTagEpdHeaderSerializer::deserialize(), inet::CsmaCaMacTrailerSerializer::deserialize(), inet::EtherAppRespSerializer::deserialize(), inet::ieee80211::Ieee80211MacTrailerSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::EthernetFcsSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::deserializeIpv6NdOptions(), inet::ospfv2::Ospfv2PacketSerializer::deserializeLsaHeader(), inet::Ipv4HeaderSerializer::deserializeOption(), inet::tcp::TcpHeaderSerializer::deserializeOption(), inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), inet::GptpPacketSerializer::readGptpBase(), inet::GptpPacketSerializer::readGptpFollowUpInformationTlv(), inet::GptpPacketSerializer::readScaledNS(), and inet::GptpPacketSerializer::readTimestamp().
readUint32Le()
uint32_t inet::MemoryInputStream::readUint32Le () inline
Reads a 32 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
{
         uint32_t value = 0;
         value |= (static_cast<uint32_t>(readByte()) << 0);
         value |= (static_cast<uint32_t>(readByte()) << 8);
         value |= (static_cast<uint32_t>(readByte()) << 16);
         value |= (static_cast<uint32_t>(readByte()) << 24);
         return value;
     }
readUint4()
uint8_t inet::MemoryInputStream::readUint4 () inline
Reads a 4 bit unsigned integer at the current position of the stream in MSB to LSB bit order.
{
         uint8_t value = 0;
         if (readBit()) value |= 0x8;
         if (readBit()) value |= 0x4;
         if (readBit()) value |= 0x2;
         if (readBit()) value |= 0x1;
         return value;
     }
Referenced by inet::Ipv6HeaderSerializer::deserialize(), inet::rtp::RtpPacketSerializer::deserialize(), inet::physicallayer::Ieee80211FhssPhyHeaderSerializer::deserialize(), inet::GptpPacketSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MpduSubframeHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211OfdmPhyHeaderSerializer::deserialize(), inet::physicallayer::Ieee80211ErpOfdmPhyHeaderSerializer::deserialize(), and inet::GptpPacketSerializer::readGptpBase().
readUint48Be()
uint64_t inet::MemoryInputStream::readUint48Be () inline
Reads a 48 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         uint64_t value = 0;
         value |= (static_cast<uint64_t>(readByte()) << 40);
         value |= (static_cast<uint64_t>(readByte()) << 32);
         value |= (static_cast<uint64_t>(readByte()) << 24);
         value |= (static_cast<uint64_t>(readByte()) << 16);
         value |= (static_cast<uint64_t>(readByte()) << 8);
         value |= (static_cast<uint64_t>(readByte()) << 0);
         return value;
     }
Referenced by inet::GptpPacketSerializer::readTimestamp().
readUint48Le()
uint64_t inet::MemoryInputStream::readUint48Le () inline
Reads a 48 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
{
         uint64_t value = 0;
         value |= (static_cast<uint64_t>(readByte()) << 0);
         value |= (static_cast<uint64_t>(readByte()) << 8);
         value |= (static_cast<uint64_t>(readByte()) << 16);
         value |= (static_cast<uint64_t>(readByte()) << 24);
         value |= (static_cast<uint64_t>(readByte()) << 32);
         value |= (static_cast<uint64_t>(readByte()) << 40);
         return value;
     }
readUint64Be()
uint64_t inet::MemoryInputStream::readUint64Be () inline
Reads a 64 bit unsigned integer at the current position of the stream in big endian byte order and MSB to LSB bit order.
{
         uint64_t value = 0;
         value |= (static_cast<uint64_t>(readByte()) << 56);
         value |= (static_cast<uint64_t>(readByte()) << 48);
         value |= (static_cast<uint64_t>(readByte()) << 40);
         value |= (static_cast<uint64_t>(readByte()) << 32);
         value |= (static_cast<uint64_t>(readByte()) << 24);
         value |= (static_cast<uint64_t>(readByte()) << 16);
         value |= (static_cast<uint64_t>(readByte()) << 8);
         value |= (static_cast<uint64_t>(readByte()) << 0);
         return value;
     }
Referenced by inet::rtp::RtcpPacketSerializer::deserialize(), inet::XMacHeaderSerializer::deserialize(), inet::BMacHeaderSerializer::deserialize(), inet::GenericAppMsgSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::AckingMacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MgmtFrameSerializer::deserialize(), inet::ieee80211::Ieee80211MacHeaderSerializer::deserialize(), inet::GptpPacketSerializer::readClock8(), inet::GptpPacketSerializer::readPortIdentity(), and inet::GptpPacketSerializer::readScaledNS().
readUint64Le()
uint64_t inet::MemoryInputStream::readUint64Le () inline
Reads a 64 bit unsigned integer at the current position of the stream in little endian byte order and MSB to LSB bit order.
{
         uint64_t value = 0;
         value |= (static_cast<uint64_t>(readByte()) << 0);
         value |= (static_cast<uint64_t>(readByte()) << 8);
         value |= (static_cast<uint64_t>(readByte()) << 16);
         value |= (static_cast<uint64_t>(readByte()) << 24);
         value |= (static_cast<uint64_t>(readByte()) << 32);
         value |= (static_cast<uint64_t>(readByte()) << 40);
         value |= (static_cast<uint64_t>(readByte()) << 48);
         value |= (static_cast<uint64_t>(readByte()) << 56);
         return value;
     }
readUint8()
uint8_t inet::MemoryInputStream::readUint8 () inline
Reads an 8 bit unsigned integer at the current position of the stream in MSB to LSB bit order.
{
         return readByte();
     }
Referenced by inet::Ipv6HeaderSerializer::deserialize(), inet::RipPacketSerializer::deserialize(), inet::DhcpMessageSerializer::deserialize(), inet::FragmentNumberHeaderSerializer::deserialize(), inet::Ieee8021dBpduSerializer::deserialize(), inet::MplsPacketSerializer::deserialize(), inet::Icmpv6HeaderSerializer::deserialize(), inet::PppHeaderSerializer::deserialize(), inet::ospf::OspfPacketSerializer::deserialize(), inet::CsmaCaMacHeaderSerializer::deserialize(), inet::AckingMacHeaderSerializer::deserialize(), inet::ieee80211::Ieee80211MpduSubframeHeaderSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeOspfHeader(), inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), and inet::GptpPacketSerializer::readGptpBase().
seek()
void inet::MemoryInputStream::seek (b position) inline
Updates the read position of the stream.
{
         assert(b(0) <= position && position <= length);
         this->position = position;
     }
Referenced by inet::ospf::OspfPacketSerializer::deserialize(), inet::GptpPacketSerializer::deserialize(), inet::Ipv4HeaderSerializer::deserializeOption(), inet::ArpPacketSerializer::readIpv4Address(), and inet::ArpPacketSerializer::readMacAddress().
Member Data Documentation
data
std::vector<uint8_t> inet::MemoryInputStream::data protected
This vector contains the bits that are read from this stream.
The first bit of the bit stream is stored in the most significant bit of the first byte. For the longest possible bit stream given the same number of bytes, the last bit of the bit stream is stored in the least significant bit of the last byte. In other cases some of the lower bits of the last byte are not used.
isReadBeyondEnd_
bool inet::MemoryInputStream::isReadBeyondEnd_ = false protected
This flag indicates if the stream has been read beyond the end of data.
length
b inet::MemoryInputStream::length protected
The length of the bit stream measured in bits.
position
b inet::MemoryInputStream::position protected
The position of the next bit that will be read measured in bits.
The documentation for this class was generated from the following file:
MemoryInputStream.h