INET Framework for OMNeT++/OMNEST: inet::HelloTimeoutMsg Class Reference
inet::HelloTimeoutMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:106 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
HelloTimeoutMsg (const char *name=nullptr, short kind=0)
HelloTimeoutMsg (const HelloTimeoutMsg &other)
virtual ~HelloTimeoutMsg ()
HelloTimeoutMsg & operator= (const HelloTimeoutMsg &other)
virtual HelloTimeoutMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ipv4Address & getPeer () const
virtual Ipv4Address & getPeerForUpdate ()
virtual void setPeer (const Ipv4Address &peer)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const HelloTimeoutMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
Ipv4Address peer
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const HelloTimeoutMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:106 by opp_msgtool.
//
// FIXME missing documentation
//
message HelloTimeoutMsg extends SignallingMsg
{
    Ipv4Address peer;
    command = MSG_HELLO_TIMEOUT;
}
Constructor & Destructor Documentation
HelloTimeoutMsg() [1/2]
inet::HelloTimeoutMsg::HelloTimeoutMsg (const char * name = nullptr, short kind = 0)
HelloTimeoutMsg() [2/2]
inet::HelloTimeoutMsg::HelloTimeoutMsg (const HelloTimeoutMsg & other)
~HelloTimeoutMsg()
virtual inet::HelloTimeoutMsg::~HelloTimeoutMsg () virtual
Member Function Documentation
copy()
void inet::HelloTimeoutMsg::copy (const HelloTimeoutMsg & other) private
dup()
virtual HelloTimeoutMsg* inet::HelloTimeoutMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new HelloTimeoutMsg(*this);}
getPeer()
virtual const Ipv4Address& inet::HelloTimeoutMsg::getPeer () const virtual
Referenced by inet::RsvpTe::processHELLO_TIMEOUT().
getPeerForUpdate()
virtual Ipv4Address& inet::HelloTimeoutMsg::getPeerForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<HelloTimeoutMsg*>(this)->getPeer());}
operator=()
HelloTimeoutMsg& inet::HelloTimeoutMsg::operator= (const HelloTimeoutMsg & other)
operator==()
bool inet::HelloTimeoutMsg::operator== (const HelloTimeoutMsg &) protected delete
parsimPack()
virtual void inet::HelloTimeoutMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::HelloTimeoutMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setPeer()
virtual void inet::HelloTimeoutMsg::setPeer (const Ipv4Address & peer) virtual
Member Data Documentation
peer
Ipv4Address inet::HelloTimeoutMsg::peer protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h