INET Framework for OMNeT++/OMNEST: inet::SequenceNumberTagBase Class Reference
inet::SequenceNumberTagBase Class Reference
Class generated from inet/common/SequenceNumberTag.msg:16 by opp_msgtool.
#include <SequenceNumberTag_m.h>
Public Member Functions
SequenceNumberTagBase ()
SequenceNumberTagBase (const SequenceNumberTagBase &other)
virtual ~SequenceNumberTagBase ()
SequenceNumberTagBase & operator= (const SequenceNumberTagBase &other)
virtual SequenceNumberTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getSequenceNumber () const
virtual void setSequenceNumber (int sequenceNumber)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SequenceNumberTagBase &)=delete
Protected Attributes
int sequenceNumber = -1
Private Member Functions
void copy (const SequenceNumberTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/common/SequenceNumberTag.msg:16 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class SequenceNumberTagBase extends TagBase
{
    int sequenceNumber = -1;
}
Constructor & Destructor Documentation
SequenceNumberTagBase() [1/2]
inet::SequenceNumberTagBase::SequenceNumberTagBase ()
SequenceNumberTagBase() [2/2]
inet::SequenceNumberTagBase::SequenceNumberTagBase (const SequenceNumberTagBase & other)
~SequenceNumberTagBase()
virtual inet::SequenceNumberTagBase::~SequenceNumberTagBase () virtual
Member Function Documentation
copy()
void inet::SequenceNumberTagBase::copy (const SequenceNumberTagBase & other) private
dup()
virtual SequenceNumberTagBase* inet::SequenceNumberTagBase::dup () const inline override virtual
Reimplemented in inet::SequenceNumberInd, and inet::SequenceNumberReq.
 {return new SequenceNumberTagBase(*this);}
getSequenceNumber()
virtual int inet::SequenceNumberTagBase::getSequenceNumber () const virtual
Referenced by inet::StreamMerger::matchesPacket(), inet::Ieee8021rTagEpdHeaderInserter::processPacket(), and inet::StreamMerger::processPacket().
operator=()
SequenceNumberTagBase& inet::SequenceNumberTagBase::operator= (const SequenceNumberTagBase & other)
operator==()
bool inet::SequenceNumberTagBase::operator== (const SequenceNumberTagBase &) protected delete
parsimPack()
virtual void inet::SequenceNumberTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::SequenceNumberInd, and inet::SequenceNumberReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SequenceNumberTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::SequenceNumberInd, and inet::SequenceNumberReq.
Referenced by inet::doParsimUnpacking().
setSequenceNumber()
virtual void inet::SequenceNumberTagBase::setSequenceNumber (int sequenceNumber) virtual
Member Data Documentation
sequenceNumber
int inet::SequenceNumberTagBase::sequenceNumber = -1 protected
The documentation for this class was generated from the following file:
SequenceNumberTag_m.h