INET Framework for OMNeT++/OMNEST: inet::aodv::WaitForRrep Class Reference
inet::aodv::WaitForRrep Class Reference
Class generated from inet/routing/aodv/AodvControlPackets.msg:109 by opp_msgtool.
#include <AodvControlPackets_m.h>
Public Member Functions
WaitForRrep (const char *name=nullptr, short kind=0)
WaitForRrep (const WaitForRrep &other)
virtual ~WaitForRrep ()
WaitForRrep & operator= (const WaitForRrep &other)
virtual WaitForRrep * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::L3Address & getDestAddr () const
virtual ::inet::L3Address & getDestAddrForUpdate ()
virtual void setDestAddr (const ::inet::L3Address &destAddr)
virtual unsigned int getLastTTL () const
virtual void setLastTTL (unsigned int lastTTL)
virtual bool getFromInvalidEntry () const
virtual void setFromInvalidEntry (bool fromInvalidEntry)
Protected Member Functions
bool operator== (const WaitForRrep &)=delete
Protected Attributes
::inet::L3Address destAddr
unsigned int lastTTL = 0
bool fromInvalidEntry = false
Private Member Functions
void copy (const WaitForRrep &other)
Detailed Description
Class generated from inet/routing/aodv/AodvControlPackets.msg:109 by opp_msgtool.
//
// Represents an internal timer for a Route Reply packet in Aodv module
//
message WaitForRrep
{
    L3Address destAddr;
    unsigned int lastTTL;
    bool fromInvalidEntry;
}
Constructor & Destructor Documentation
WaitForRrep() [1/2]
inet::aodv::WaitForRrep::WaitForRrep (const char * name = nullptr, short kind = 0)
WaitForRrep() [2/2]
inet::aodv::WaitForRrep::WaitForRrep (const WaitForRrep & other)
~WaitForRrep()
virtual inet::aodv::WaitForRrep::~WaitForRrep () virtual
Member Function Documentation
copy()
void inet::aodv::WaitForRrep::copy (const WaitForRrep & other) private
dup()
virtual WaitForRrep* inet::aodv::WaitForRrep::dup () const inline override virtual
 {return new WaitForRrep(*this);}
getDestAddr()
virtual const ::inet::L3Address& inet::aodv::WaitForRrep::getDestAddr () const virtual
Referenced by inet::aodv::Aodv::handleWaitForRREP().
getDestAddrForUpdate()
virtual ::inet::L3Address& inet::aodv::WaitForRrep::getDestAddrForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<WaitForRrep*>(this)->getDestAddr());}
getFromInvalidEntry()
virtual bool inet::aodv::WaitForRrep::getFromInvalidEntry () const virtual
getLastTTL()
virtual unsigned int inet::aodv::WaitForRrep::getLastTTL () const virtual
Referenced by inet::aodv::Aodv::handleWaitForRREP(), and inet::aodv::Aodv::sendRREQ().
operator=()
WaitForRrep& inet::aodv::WaitForRrep::operator= (const WaitForRrep & other)
operator==()
bool inet::aodv::WaitForRrep::operator== (const WaitForRrep &) protected delete
parsimPack()
virtual void inet::aodv::WaitForRrep::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::aodv::doParsimPacking().
parsimUnpack()
virtual void inet::aodv::WaitForRrep::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::aodv::doParsimUnpacking().
setDestAddr()
virtual void inet::aodv::WaitForRrep::setDestAddr (const ::inet::L3Address & destAddr) virtual
Referenced by inet::aodv::Aodv::sendRREQ().
setFromInvalidEntry()
virtual void inet::aodv::WaitForRrep::setFromInvalidEntry (bool fromInvalidEntry) virtual
Referenced by inet::aodv::Aodv::sendRREQ().
setLastTTL()
virtual void inet::aodv::WaitForRrep::setLastTTL (unsigned int lastTTL) virtual
Referenced by inet::aodv::Aodv::sendRREQ().
Member Data Documentation
destAddr
::inet::L3Address inet::aodv::WaitForRrep::destAddr protected
fromInvalidEntry
bool inet::aodv::WaitForRrep::fromInvalidEntry = false protected
lastTTL
unsigned int inet::aodv::WaitForRrep::lastTTL = 0 protected
The documentation for this class was generated from the following file:
AodvControlPackets_m.h