INET Framework for OMNeT++/OMNEST: inet::tcp::TcpSegmentTransmitInfoList::Item Class Reference
inet::tcp::TcpSegmentTransmitInfoList::Item Class Reference
#include <TcpSegmentTransmitInfoList.h>
Public Member Functions
Item (uint32_t beg, uint32_t end, simtime_t firstTime, simtime_t lastTime, int transmits)
uint32_t getBeg () const
uint32_t getEnd () const
simtime_t getFirstSentTime () const
simtime_t getLastSentTime () const
int getTransmitCount () const
Protected Attributes
uint32_t beg
uint32_t end
simtime_t firstSentTime
simtime_t lastSentTime
int transmitCount
Friends
class TcpSegmentTransmitInfoList
Constructor & Destructor Documentation
Item()
inet::tcp::TcpSegmentTransmitInfoList::Item::Item (uint32_t beg, uint32_t end, simtime_t firstTime, simtime_t lastTime, int transmits) inline
 : beg(beg), end(end), firstSentTime(firstTime), lastSentTime(lastTime), transmitCount(transmits) {}
Member Function Documentation
getBeg()
uint32_t inet::tcp::TcpSegmentTransmitInfoList::Item::getBeg () const inline
 { return beg; }
getEnd()
uint32_t inet::tcp::TcpSegmentTransmitInfoList::Item::getEnd () const inline
 { return end; }
getFirstSentTime()
simtime_t inet::tcp::TcpSegmentTransmitInfoList::Item::getFirstSentTime () const inline
 { return firstSentTime; }
Referenced by inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
getLastSentTime()
simtime_t inet::tcp::TcpSegmentTransmitInfoList::Item::getLastSentTime () const inline
 { return lastSentTime; }
getTransmitCount()
int inet::tcp::TcpSegmentTransmitInfoList::Item::getTransmitCount () const inline
 { return transmitCount; }
Referenced by inet::tcp::TcpWestwood::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), and inet::tcp::TcpVegas::receivedDuplicateAck().
Friends And Related Function Documentation
TcpSegmentTransmitInfoList
friend class TcpSegmentTransmitInfoList friend
Member Data Documentation
beg
uint32_t inet::tcp::TcpSegmentTransmitInfoList::Item::beg protected
end
uint32_t inet::tcp::TcpSegmentTransmitInfoList::Item::end protected
firstSentTime
simtime_t inet::tcp::TcpSegmentTransmitInfoList::Item::firstSentTime protected
lastSentTime
simtime_t inet::tcp::TcpSegmentTransmitInfoList::Item::lastSentTime protected
transmitCount
int inet::tcp::TcpSegmentTransmitInfoList::Item::transmitCount protected
The documentation for this class was generated from the following file:
TcpSegmentTransmitInfoList.h