INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpNetwork< IPAddress > Class Template Reference
inet::eigrp::EigrpNetwork< IPAddress > Class Template Reference
Network for EIGRP routing.
#include <EigrpNetworkTable.h>
Public Member Functions
EigrpNetwork (IPAddress &address, IPAddress &mask, int id)
const IPAddress & getAddress () const
void setAddress (const IPAddress &address)
const IPAddress & getMask () const
void setMask (const IPAddress &mask)
int getNetworkId () const
void setNetworkId (int networkId)
Protected Attributes
int networkId
IPAddress address
IPAddress mask
Detailed Description
template<typename IPAddress>
class inet::eigrp::EigrpNetwork< IPAddress >
Network for EIGRP routing.
Constructor & Destructor Documentation
EigrpNetwork()
template<typename IPAddress > inet::eigrp::EigrpNetwork< IPAddress >::EigrpNetwork (IPAddress & address, IPAddress & mask, int id) inline
                                                               :
         networkId(id), address(address), mask(mask) {}
Member Function Documentation
getAddress()
template<typename IPAddress > const IPAddress& inet::eigrp::EigrpNetwork< IPAddress >::getAddress () const inline
{
         return address;
     }
Referenced by inet::eigrp::EigrpIpv6Pdm::disableInterface(), and inet::operator<<().
getMask()
template<typename IPAddress > const IPAddress& inet::eigrp::EigrpNetwork< IPAddress >::getMask () const inline
{
         return mask;
     }
Referenced by inet::eigrp::EigrpIpv6Pdm::disableInterface(), and inet::operator<<().
getNetworkId()
template<typename IPAddress > int inet::eigrp::EigrpNetwork< IPAddress >::getNetworkId () const inline
{
         return networkId;
     }
Referenced by inet::eigrp::EigrpIpv6Pdm::enableInterface(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks().
setAddress()
template<typename IPAddress > void inet::eigrp::EigrpNetwork< IPAddress >::setAddress (const IPAddress & address) inline
{
         this->address = address;
     }
setMask()
template<typename IPAddress > void inet::eigrp::EigrpNetwork< IPAddress >::setMask (const IPAddress & mask) inline
{
         this->mask = mask;
     }
setNetworkId()
template<typename IPAddress > void inet::eigrp::EigrpNetwork< IPAddress >::setNetworkId (int networkId) inline
{
         this->networkId = networkId;
     }
Member Data Documentation
address
template<typename IPAddress > IPAddress inet::eigrp::EigrpNetwork< IPAddress >::address protected
Referenced by inet::eigrp::EigrpNetwork< IPAddress >::getAddress(), and inet::eigrp::EigrpNetwork< IPAddress >::setAddress().
mask
template<typename IPAddress > IPAddress inet::eigrp::EigrpNetwork< IPAddress >::mask protected
Referenced by inet::eigrp::EigrpNetwork< IPAddress >::getMask(), and inet::eigrp::EigrpNetwork< IPAddress >::setMask().
networkId
template<typename IPAddress > int inet::eigrp::EigrpNetwork< IPAddress >::networkId protected
Referenced by inet::eigrp::EigrpNetwork< IPAddress >::getNetworkId(), and inet::eigrp::EigrpNetwork< IPAddress >::setNetworkId().
The documentation for this class was generated from the following file:
EigrpNetworkTable.h