INET Framework for OMNeT++/OMNEST: inet::SctpSocket::ICallback Class Reference
inet::SctpSocket::ICallback Class Reference abstract
Abstract base class for your callback objects.
#include <SctpSocket.h>
Public Member Functions
virtual ~ICallback ()
virtual void socketDataArrived (SctpSocket *socket, Packet *packet, bool urgent)=0
virtual void socketDataNotificationArrived (SctpSocket *socket, Message *msg)=0
virtual void socketAvailable (SctpSocket *socket, Indication *indication)=0
virtual void socketOptionsArrived (SctpSocket *socket, Indication *indication)
virtual void socketEstablished (SctpSocket *socket, unsigned long int buffer)
virtual void socketPeerClosed (SctpSocket *socket)
virtual void socketClosed (SctpSocket *socket)
virtual void socketFailure (SctpSocket *socket, int code)
virtual void socketStatusArrived (SctpSocket *socket, SctpStatusReq *status)
virtual void socketDeleted (SctpSocket *socket)
virtual void sendRequestArrived (SctpSocket *socket)
virtual void msgAbandonedArrived (SctpSocket *socket)
virtual void shutdownReceivedArrived (SctpSocket *socket)
virtual void sendqueueFullArrived (SctpSocket *socket)
virtual void sendqueueAbatedArrived (SctpSocket *socket, unsigned long int buffer)
virtual void addressAddedArrived (SctpSocket *socket, L3Address localAddr, L3Address remoteAddr)
Detailed Description
Abstract base class for your callback objects.
See setCallback() and processMessage() for more info.
Note: this class is not subclassed from cObject, because classes may have both this class and cSimpleModule as base class, and cSimpleModule is already a cObject.
Constructor & Destructor Documentation
~ICallback()
virtual inet::SctpSocket::ICallback::~ICallback () inline virtual
 {}
Member Function Documentation
addressAddedArrived()
virtual void inet::SctpSocket::ICallback::addressAddedArrived (SctpSocket * socket, L3Address localAddr, L3Address remoteAddr) inline virtual
Reimplemented in inet::SctpNatPeer.
 {}
Referenced by inet::SctpSocket::processMessage().
msgAbandonedArrived()
virtual void inet::SctpSocket::ICallback::msgAbandonedArrived (SctpSocket * socket) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
sendqueueAbatedArrived()
virtual void inet::SctpSocket::ICallback::sendqueueAbatedArrived (SctpSocket * socket, unsigned long int buffer) inline virtual
Reimplemented in inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
sendqueueFullArrived()
virtual void inet::SctpSocket::ICallback::sendqueueFullArrived (SctpSocket * socket) inline virtual
Reimplemented in inet::SctpNatPeer, and inet::SctpPeer.
 {}
Referenced by inet::SctpSocket::processMessage().
sendRequestArrived()
virtual void inet::SctpSocket::ICallback::sendRequestArrived (SctpSocket * socket) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
shutdownReceivedArrived()
virtual void inet::SctpSocket::ICallback::shutdownReceivedArrived (SctpSocket * socket) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
socketAvailable()
virtual void inet::SctpSocket::ICallback::socketAvailable (SctpSocket * socket, Indication * indication) pure virtual
Implemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
Referenced by inet::SctpSocket::processMessage().
socketClosed()
virtual void inet::SctpSocket::ICallback::socketClosed (SctpSocket * socket) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
socketDataArrived()
virtual void inet::SctpSocket::ICallback::socketDataArrived (SctpSocket * socket, Packet * packet, bool urgent) pure virtual
Implemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
Referenced by inet::SctpSocket::processMessage().
socketDataNotificationArrived()
virtual void inet::SctpSocket::ICallback::socketDataNotificationArrived (SctpSocket * socket, Message * msg) pure virtual
Implemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
Referenced by inet::SctpSocket::processMessage().
socketDeleted()
virtual void inet::SctpSocket::ICallback::socketDeleted (SctpSocket * socket) inline virtual
 {}
Referenced by inet::SctpSocket::~SctpSocket().
socketEstablished()
virtual void inet::SctpSocket::ICallback::socketEstablished (SctpSocket * socket, unsigned long int buffer) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
socketFailure()
virtual void inet::SctpSocket::ICallback::socketFailure (SctpSocket * socket, int code) inline virtual
Reimplemented in inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
socketOptionsArrived()
virtual void inet::SctpSocket::ICallback::socketOptionsArrived (SctpSocket * socket, Indication * indication) inline virtual
 { delete indication; }
Referenced by inet::SctpSocket::processMessage().
socketPeerClosed()
virtual void inet::SctpSocket::ICallback::socketPeerClosed (SctpSocket * socket) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
socketStatusArrived()
virtual void inet::SctpSocket::ICallback::socketStatusArrived (SctpSocket * socket, SctpStatusReq * status) inline virtual
Reimplemented in inet::SctpNatPeer, inet::SctpPeer, and inet::SctpClient.
 {}
Referenced by inet::SctpSocket::processMessage().
The documentation for this class was generated from the following file:
SctpSocket.h