INET Framework for OMNeT++/OMNEST: inet::IOscillator Class Reference
inet::IOscillator Class Reference abstract
This class defines the interface for oscillators.
#include <IOscillator.h>
Public Member Functions
virtual ~IOscillator ()
virtual simtime_t getNominalTickLength () const =0
Returns the nominal time interval between subsequent ticks.
virtual simtime_t getComputationOrigin () const =0
Returns the oscillator computation origin from which the ticks are measured.
virtual int64_t computeTicksForInterval (simtime_t timeInterval) const =0
Returns the number of ticks in the specified time interval measured from the oscillator computation origin.
virtual simtime_t computeIntervalForTicks (int64_t numTicks) const =0
Returns the smallest simulation time interval for the specified number of ticks measured from the oscillator computation origin.
Static Public Attributes
static simsignal_t preOscillatorStateChangedSignal = cComponent::registerSignal("preOscillatorStateChanged")
static simsignal_t postOscillatorStateChangedSignal = cComponent::registerSignal("postOscillatorStateChanged")
Detailed Description
This class defines the interface for oscillators.
See the corresponding NED file for details.
Constructor & Destructor Documentation
~IOscillator()
virtual inet::IOscillator::~IOscillator () inline virtual
 {}
Member Function Documentation
computeIntervalForTicks()
virtual simtime_t inet::IOscillator::computeIntervalForTicks (int64_t numTicks) const pure virtual
Returns the smallest simulation time interval for the specified number of ticks measured from the oscillator computation origin.
For example, for 0 ticks returns 0, for 1 tick returns the remaining time till the next tick, and so on.
Implemented in inet::DriftingOscillatorBase, and inet::IdealOscillator.
Referenced by inet::OscillatorBasedClock::computeSimTimeFromClockTime().
computeTicksForInterval()
virtual int64_t inet::IOscillator::computeTicksForInterval (simtime_t timeInterval) const pure virtual
Returns the number of ticks in the specified time interval measured from the oscillator computation origin.
Note that each tick interval taken into consideration may be different from the nominal tick length. Returns the #ticks in (computation origin, computation origin + time interval].
Implemented in inet::DriftingOscillatorBase, and inet::IdealOscillator.
Referenced by inet::OscillatorBasedClock::computeClockTimeFromSimTime(), inet::OscillatorBasedClock::receiveSignal(), inet::OscillatorBasedClock::resolveDirective(), and inet::SettableClock::setClockTime().
getComputationOrigin()
virtual simtime_t inet::IOscillator::getComputationOrigin () const pure virtual
Returns the oscillator computation origin from which the ticks are measured.
There may or may not be an actual tick at the returned simulation time.
Implemented in inet::DriftingOscillatorBase, and inet::IdealOscillator.
Referenced by inet::OscillatorBasedClock::computeClockTimeFromSimTime(), inet::OscillatorBasedClock::computeSimTimeFromClockTime(), inet::OscillatorBasedClock::receiveSignal(), inet::OscillatorBase::resolveDirective(), inet::OscillatorBasedClock::resolveDirective(), and inet::SettableClock::setClockTime().
getNominalTickLength()
virtual simtime_t inet::IOscillator::getNominalTickLength () const pure virtual
Returns the nominal time interval between subsequent ticks.
This value is usually different from the actual amount of elapsed time between ticks.
Implemented in inet::DriftingOscillatorBase, and inet::IdealOscillator.
Referenced by inet::OscillatorBasedClock::computeClockTimeFromSimTime(), inet::OscillatorBasedClock::computeSimTimeFromClockTime(), inet::OscillatorBasedClock::initialize(), inet::OscillatorBase::resolveDirective(), inet::OscillatorBasedClock::scheduleClockEventAfter(), inet::OscillatorBasedClock::scheduleClockEventAt(), and inet::SettableClock::setClockTime().
Member Data Documentation
postOscillatorStateChangedSignal
simsignal_t inet::IOscillator::postOscillatorStateChangedSignal = cComponent::registerSignal("postOscillatorStateChanged") static
Referenced by inet::OscillatorBasedClock::initialize(), inet::OscillatorBasedClock::receiveSignal(), inet::DriftingOscillatorBase::setDriftRate(), and inet::DriftingOscillatorBase::setTickOffset().
preOscillatorStateChangedSignal
simsignal_t inet::IOscillator::preOscillatorStateChangedSignal = cComponent::registerSignal("preOscillatorStateChanged") static
Referenced by inet::OscillatorBasedClock::initialize(), inet::OscillatorBasedClock::receiveSignal(), inet::DriftingOscillatorBase::setDriftRate(), and inet::DriftingOscillatorBase::setTickOffset().
The documentation for this class was generated from the following files:
IOscillator.h
IOscillator.cc