INET Framework for OMNeT++/OMNEST: inet::UdpSocket Class Reference
inet::UdpSocket Class Reference
UdpSocket is a convenience class, to make it easier to send and receive UDP packets from your application models.
#include <UdpSocket.h>
Classes
class ICallback
Public Types
enum State { CONNECTED, CLOSED }
Public Member Functions
UdpSocket ()
Constructor.
~UdpSocket ()
Destructor.
void * getUserData () const
void setUserData (void *userData)
State getState () const
int getSocketId () const override
Returns the internal socket Id.
Opening and closing connections, sending data
void setOutputGate (cGate *toUdp)
Sets the gate on which to send to UDP.
void bind (int localPort)
Bind the socket to a local port number.
void bind (L3Address localAddr, int localPort)
Bind the socket to a local port number and IP address (useful with multi-homing or multicast addresses).
void connect (L3Address remoteAddr, int remotePort)
Connects to a remote UDP socket.
void setTimeToLive (int ttl)
Set the TTL (Ipv6: Hop Limit) field on sent packets.
void setDscp (short dscp)
Sets the Ipv4 / Ipv6 dscp fields of packets sent from the UDP socket.
void setTos (short tos)
Sets the Ipv4 Type of Service / Ipv6 Traffic Class fields of packets sent from the UDP socket.
void setBroadcast (bool broadcast)
Set the Broadcast option on the UDP socket.
void setMulticastLoop (bool value)
The boolean value specifies whether sent multicast packets should be looped back to the local sockets (like the Unix IP_MULTICAST_LOOP socket option).
void setMulticastOutputInterface (int interfaceId)
Set the output interface for sending multicast packets (like the Unix IP_MULTICAST_IF socket option).
void setReuseAddress (bool value)
Set the ReuseAddress option on the UDP socket.
void joinMulticastGroup (const L3Address &multicastAddr, int interfaceId=-1)
Adds the socket to the given multicast group, that is, UDP packets arriving to the given multicast address will be passed up to the socket.
void joinLocalMulticastGroups (MulticastGroupList mgl)
Joins the socket to each multicast group that are registered with any of the interfaces.
void leaveMulticastGroup (const L3Address &multicastAddr)
Causes the socket to leave the given multicast group, i.e.
void leaveLocalMulticastGroups (MulticastGroupList mgl)
Causes the socket to leave each multicast groups that are registered with any of the interfaces.
void blockMulticastSources (int interfaceId, const L3Address &multicastAddr, const std::vector< L3Address > &sourceList)
Blocks multicast traffic of the specified group address from specific sources.
void unblockMulticastSources (int interfaceId, const L3Address &multicastAddr, const std::vector< L3Address > &sourceList)
Unblocks the multicast traffic of the specified group address from the specified sources.
void joinMulticastSources (int interfaceId, const L3Address &multicastAddr, const std::vector< L3Address > &sourceList)
Adds the socket to the given multicast group and source addresses, that is, UDP packets arriving from one of the sources and to the given multicast address will be passed up to the socket.
void leaveMulticastSources (int interfaceId, const L3Address &multicastAddr, const std::vector< L3Address > &sourceList)
Causes the socket to leave the given multicast group for the specified sources, i.e.
void setMulticastSourceFilter (int interfaceId, const L3Address &multicastAddr, UdpSourceFilterMode filterMode, const std::vector< L3Address > &sourceList)
Sets the source filter for the given multicast group.
void sendTo (Packet *msg, L3Address destAddr, int destPort)
Sends a data packet to the given address and port.
virtual void send (Packet *msg) override
Sends a data packet to the address and port specified previously in a connect() call.
virtual void close () override
Unbinds the socket.
virtual void destroy () override
Notify the protocol that the owner of ISocket has destroyed the socket.
Public Member Functions inherited from inet::ISocket
virtual ~ISocket ()
Protected Member Functions
void sendToUDP (cMessage *msg)
Protected Attributes
int socketId
ICallback * cb = nullptr
void * userData = nullptr
cGate * gateToUdp = nullptr
State sockState = CLOSED
Handling of messages arriving from UDP
virtual bool belongsToSocket (cMessage *msg) const override
Returns true if the message belongs to this socket instance (message has a UdpControlInfo as getControlInfo(), and the socketId in it matches that of the socket.)
void setCallback (ICallback *cb)
Sets a callback object, to be used with processMessage().
virtual void processMessage (cMessage *msg) override
Examines the message, takes ownership, and updates socket state.
virtual bool isOpen () const override
static std::string getReceivedPacketInfo (Packet *pk)
Utility function: returns a line of information about a packet received via UDP.
Detailed Description
UdpSocket is a convenience class, to make it easier to send and receive UDP packets from your application models.
You'd have one (or more) UdpSocket object(s) in your application simple module class, and call its member functions (bind(), connect(), sendTo(), etc.) to create and configure a socket, and to send datagrams.
UdpSocket chooses and remembers the socketId for you, assembles and sends command packets such as UDP_C_BIND to UDP, and can also help you deal with packets and notification messages arriving from UDP.
Here is a code fragment that creates an UDP socket and sends a 1K packet over it (the code can be placed in your handleMessage() or activity()):
  UdpSocket socket;
  socket.setOutputGate(gate("udpOut"));
  socket.connect(Address("10.0.0.2"), 2000);
  cPacket *pk = new cPacket("dgram");
  pk->setByteLength(1024);
  socket.send(pk);
  socket.close();
Processing messages sent up by the UDP module is relatively straightforward. You only need to distinguish between data packets and error notifications, by checking the message kind (should be either UDP_I_DATA or UDP_I_ERROR), and casting the control info to UDPDataIndication or UdpErrorIndication. USPSocket provides some help for this with the belongsToSocket() and belongsToAnyUDPSocket() methods.
Member Enumeration Documentation
State
enum inet::UdpSocket::State
Enumerator
CONNECTED
CLOSED
 { CONNECTED, CLOSED };
Constructor & Destructor Documentation
UdpSocket()
inet::UdpSocket::UdpSocket ()
Constructor.
The getSocketId() method returns a valid Id right after constructor call.
 {
     // don't allow user-specified socketIds because they may conflict with
     // automatically assigned ones.
     socketId = getEnvir()->getUniqueNumber();
 }
~UdpSocket()
inet::UdpSocket::~UdpSocket () inline
Destructor.
 {}
Member Function Documentation
belongsToSocket()
bool inet::UdpSocket::belongsToSocket (cMessage * msg) const override virtual
Returns true if the message belongs to this socket instance (message has a UdpControlInfo as getControlInfo(), and the socketId in it matches that of the socket.)
Implements inet::ISocket.
 {
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     const auto& socketInd = tags.findTag<SocketInd>();
     return socketInd != nullptr && socketInd->getSocketId() == socketId;
 }
Referenced by inet::UdpSocketIo::handleMessageWhenUp(), inet::Ldp::handleMessageWhenUp(), and processMessage().
bind() [1/2]
void inet::UdpSocket::bind (int localPort)
Bind the socket to a local port number.
Use port=0 for ephemeral port.
 {
     bind(L3Address(), localPort);
 }
Referenced by inet::NetPerfMeter::createAndBindSocket(), inet::rtp::Rtcp::createSocket(), inet::rtp::Rtp::createSocket(), inet::UdpEchoApp::handleStartOperation(), inet::UdpSocketIo::handleStartOperation(), inet::UdpVideoStreamServer::handleStartOperation(), inet::aodv::Aodv::handleStartOperation(), inet::TunnelApp::initialize(), inet::VoipStreamReceiver::initialize(), inet::VoipStreamSender::initialize(), inet::SimpleVoipSender::initialize(), inet::SimpleVoipReceiver::initialize(), inet::Ldp::initialize(), inet::DhcpServer::openSocket(), inet::DhcpClient::openSocket(), inet::UdpSink::processStart(), inet::UdpBasicApp::processStart(), inet::UdpBasicBurst::processStart(), inet::UdpVideoStreamClient::requestStream(), and inet::Rip::startRIPRouting().
bind() [2/2]
void inet::UdpSocket::bind (L3Address localAddr, int localPort)
Bind the socket to a local port number and IP address (useful with multi-homing or multicast addresses).
Use port=0 for an ephemeral port.
 {
     if (localPort < -1 || localPort > 65535) // -1: ephemeral port
         throw cRuntimeError("UdpSocket::bind(): invalid port number %d", localPort);
     UdpBindCommand *ctrl = new UdpBindCommand();
     ctrl->setLocalAddr(localAddr);
     ctrl->setLocalPort(localPort);
     auto request = new Request("bind", UDP_C_BIND);
     request->setControlInfo(ctrl);
     sendToUDP(request);
     sockState = CONNECTED;
 }
blockMulticastSources()
void inet::UdpSocket::blockMulticastSources (int interfaceId, const L3Address & multicastAddr, const std::vector< L3Address > & sourceList)
Blocks multicast traffic of the specified group address from specific sources.
Use this method only if joinMulticastGroup() was previously called for that group.
 {
     auto request = new Request("blockMulticastSources", UDP_C_SETOPTION);
     UdpBlockMulticastSourcesCommand *ctrl = new UdpBlockMulticastSourcesCommand();
     ctrl->setInterfaceId(interfaceId);
     ctrl->setMulticastAddr(multicastAddr);
     ctrl->setSourceListArraySize(sourceList.size());
     for (size_t i = 0; i < sourceList.size(); ++i)
         ctrl->setSourceList(i, sourceList[i]);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
close()
void inet::UdpSocket::close () override virtual
Unbinds the socket.
Once closed, a closed socket may be bound to another (or the same) port, and reused.
Implements inet::ISocket.
 {
     if (sockState == CLOSED)
         return;
     auto request = new Request("close", UDP_C_CLOSE);
     UdpCloseCommand *ctrl = new UdpCloseCommand();
     request->setControlInfo(ctrl);
     sendToUDP(request);
     sockState = CLOSED;
 }
Referenced by inet::UdpEchoApp::handleStopOperation(), inet::UdpSocketIo::handleStopOperation(), inet::UdpVideoStreamClient::handleStopOperation(), inet::UdpSink::handleStopOperation(), inet::TunnelApp::handleStopOperation(), inet::UdpBasicApp::handleStopOperation(), inet::UdpVideoStreamServer::handleStopOperation(), inet::UdpBasicBurst::handleStopOperation(), inet::DhcpServer::handleStopOperation(), inet::DhcpClient::handleStopOperation(), inet::Ldp::handleStopOperation(), inet::aodv::Aodv::handleStopOperation(), inet::UdpSink::processStop(), inet::UdpBasicApp::processStop(), inet::UdpBasicBurst::processStop(), and inet::Rip::stopRIPRouting().
connect()
void inet::UdpSocket::connect (L3Address remoteAddr, int remotePort)
Connects to a remote UDP socket.
This has two effects: (1) this socket will only receive packets from specified address/port, and (2) you can use send() (as opposed to sendTo()) to send packets.
 {
     if (addr.isUnspecified())
         throw cRuntimeError("UdpSocket::connect(): unspecified remote address");
     if (port <= 0 || port > 65535)
         throw cRuntimeError("UdpSocket::connect(): invalid remote port number %d", port);
     UdpConnectCommand *ctrl = new UdpConnectCommand();
     ctrl->setRemoteAddr(addr);
     ctrl->setRemotePort(port);
     auto request = new Request("connect", UDP_C_CONNECT);
     request->setControlInfo(ctrl);
     sendToUDP(request);
     sockState = CONNECTED;
 }
Referenced by inet::NetPerfMeter::establishConnection(), inet::UdpSocketIo::handleStartOperation(), and inet::TunnelApp::initialize().
destroy()
void inet::UdpSocket::destroy () override virtual
Notify the protocol that the owner of ISocket has destroyed the socket.
Typically used when the owner of ISocket has crashed.
Implements inet::ISocket.
 {
     if (this->gateToUdp == nullptr)
         return;
     auto request = new Request("destroy", UDP_C_DESTROY);
     auto ctrl = new UdpDestroyCommand();
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpEchoApp::handleCrashOperation(), inet::UdpSocketIo::handleCrashOperation(), inet::UdpVideoStreamClient::handleCrashOperation(), inet::UdpSink::handleCrashOperation(), inet::TunnelApp::handleCrashOperation(), inet::UdpBasicApp::handleCrashOperation(), inet::UdpVideoStreamServer::handleCrashOperation(), inet::UdpBasicBurst::handleCrashOperation(), inet::DhcpServer::handleCrashOperation(), inet::DhcpClient::handleCrashOperation(), inet::Ldp::handleCrashOperation(), and inet::aodv::Aodv::handleCrashOperation().
getReceivedPacketInfo()
std::string inet::UdpSocket::getReceivedPacketInfo (Packet * pk) static
Utility function: returns a line of information about a packet received via UDP.
 {
     auto l3Addresses = pk->getTag<L3AddressInd>();
     auto ports = pk->getTag<L4PortInd>();
     L3Address srcAddr = l3Addresses->getSrcAddress();
     L3Address destAddr = l3Addresses->getDestAddress();
     int srcPort = ports->getSrcPort();
     int destPort = ports->getDestPort();
     int interfaceID = pk->getTag<InterfaceInd>()->getInterfaceId();
     int ttl = pk->getTag<HopLimitInd>()->getHopLimit();
     std::stringstream os;
     os << pk << " (" << pk->getByteLength() << " bytes) ";
     os << srcAddr << ":" << srcPort << " --> " << destAddr << ":" << destPort;
     os << " TTL=" << ttl;
     if (auto tosTag = pk->findTag<TosInd>())
         os << " TOS=" << tosTag->getTos();
     if (auto dscpTag = pk->findTag<DscpInd>())
         os << " DSCP=" << dscpTag->getDifferentiatedServicesCodePoint();
     os << " on ifID=" << interfaceID;
     return os.str();
 }
Referenced by inet::UdpSink::processPacket(), inet::UdpBasicApp::processPacket(), inet::UdpBasicBurst::processPacket(), inet::UdpVideoStreamClient::receiveStream(), and inet::UdpSocketIo::socketDataArrived().
getSocketId()
int inet::UdpSocket::getSocketId () const inline override virtual
Returns the internal socket Id.
Implements inet::ISocket.
 { return socketId; }
Referenced by inet::sctp::Sctp::bindPortForUDP(), inet::operator<<(), and inet::Ldp::processLDPHello().
getState()
State inet::UdpSocket::getState () const inline
 { return sockState; }
getUserData()
void* inet::UdpSocket::getUserData () const inline
 { return userData; }
isOpen()
virtual bool inet::UdpSocket::isOpen () const inline override virtual
Implements inet::ISocket.
 { return sockState != CLOSED; }
Referenced by inet::TunnelApp::handleMessageWhenUp(), inet::Ldp::handleMessageWhenUp(), inet::DhcpServer::socketClosed(), and inet::DhcpClient::socketClosed().
joinLocalMulticastGroups()
void inet::UdpSocket::joinLocalMulticastGroups (MulticastGroupList mgl)
Joins the socket to each multicast group that are registered with any of the interfaces.
 {
     if (mgl.size() > 0) {
         UdpJoinMulticastGroupsCommand *ctrl = new UdpJoinMulticastGroupsCommand();
         ctrl->setMulticastAddrArraySize(mgl.size());
         ctrl->setInterfaceIdArraySize(mgl.size());
         for (unsigned int j = 0; j < mgl.size(); ++j) {
             ctrl->setMulticastAddr(j, mgl[j].multicastAddr);
             ctrl->setInterfaceId(j, mgl[j].interfaceId);
         }
         auto request = new Request("joinMulticastGroups", UDP_C_SETOPTION);
         request->setControlInfo(ctrl);
         sendToUDP(request);
     }
 }
Referenced by inet::rtp::Rtcp::createSocket(), inet::rtp::Rtp::createSocket(), inet::UdpEchoApp::handleStartOperation(), inet::UdpSocketIo::setSocketOptions(), inet::UdpSink::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
joinMulticastGroup()
void inet::UdpSocket::joinMulticastGroup (const L3Address & multicastAddr, int interfaceId = -1)
Adds the socket to the given multicast group, that is, UDP packets arriving to the given multicast address will be passed up to the socket.
One can also optionally specify the output interface for packets sent to that address.
 {
     auto request = new Request("joinMulticastGroups", UDP_C_SETOPTION);
     UdpJoinMulticastGroupsCommand *ctrl = new UdpJoinMulticastGroupsCommand();
     ctrl->setMulticastAddrArraySize(1);
     ctrl->setMulticastAddr(0, multicastAddr);
     ctrl->setInterfaceIdArraySize(1);
     ctrl->setInterfaceId(0, interfaceId);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpSocketIo::setSocketOptions(), inet::UdpSink::setSocketOptions(), and inet::Rip::startRIPRouting().
joinMulticastSources()
void inet::UdpSocket::joinMulticastSources (int interfaceId, const L3Address & multicastAddr, const std::vector< L3Address > & sourceList)
Adds the socket to the given multicast group and source addresses, that is, UDP packets arriving from one of the sources and to the given multicast address will be passed up to the socket.
 {
     auto request = new Request("joinMulticastSources", UDP_C_SETOPTION);
     UdpJoinMulticastSourcesCommand *ctrl = new UdpJoinMulticastSourcesCommand();
     ctrl->setInterfaceId(interfaceId);
     ctrl->setMulticastAddr(multicastAddr);
     ctrl->setSourceListArraySize(sourceList.size());
     for (size_t i = 0; i < sourceList.size(); ++i)
         ctrl->setSourceList(i, sourceList[i]);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
leaveLocalMulticastGroups()
void inet::UdpSocket::leaveLocalMulticastGroups (MulticastGroupList mgl)
Causes the socket to leave each multicast groups that are registered with any of the interfaces.
 {
     if (mgl.size() > 0) {
         UdpLeaveMulticastGroupsCommand *ctrl = new UdpLeaveMulticastGroupsCommand();
         ctrl->setMulticastAddrArraySize(mgl.size());
         for (unsigned int j = 0; j < mgl.size(); ++j) {
             ctrl->setMulticastAddr(j, mgl[j].multicastAddr);
         }
         auto request = new Request("leaveMulticastGroups", UDP_C_SETOPTION);
         request->setControlInfo(ctrl);
         sendToUDP(request);
     }
 }
leaveMulticastGroup()
void inet::UdpSocket::leaveMulticastGroup (const L3Address & multicastAddr)
Causes the socket to leave the given multicast group, i.e.
UDP packets arriving to the given multicast address will no longer passed up to the socket.
 {
     auto request = new Request("leaveMulticastGroups", UDP_C_SETOPTION);
     UdpLeaveMulticastGroupsCommand *ctrl = new UdpLeaveMulticastGroupsCommand();
     ctrl->setMulticastAddrArraySize(1);
     ctrl->setMulticastAddr(0, multicastAddr);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpSink::handleCrashOperation(), inet::UdpSink::handleStopOperation(), and inet::UdpSink::processStop().
leaveMulticastSources()
void inet::UdpSocket::leaveMulticastSources (int interfaceId, const L3Address & multicastAddr, const std::vector< L3Address > & sourceList)
Causes the socket to leave the given multicast group for the specified sources, i.e.
UDP packets arriving from those sources to the given multicast address will no longer passed up to the socket.
 {
     auto request = new Request("leaveMulticastSources", UDP_C_SETOPTION);
     UdpLeaveMulticastSourcesCommand *ctrl = new UdpLeaveMulticastSourcesCommand();
     ctrl->setInterfaceId(interfaceId);
     ctrl->setMulticastAddr(multicastAddr);
     ctrl->setSourceListArraySize(sourceList.size());
     for (size_t i = 0; i < sourceList.size(); ++i)
         ctrl->setSourceList(i, sourceList[i]);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
processMessage()
void inet::UdpSocket::processMessage (cMessage * msg) override virtual
Examines the message, takes ownership, and updates socket state.
Implements inet::ISocket.
 {
     ASSERT(belongsToSocket(msg));
     switch (msg->getKind()) {
         case UDP_I_DATA:
             if (cb)
                 cb->socketDataArrived(this, check_and_cast<Packet *>(msg));
             else
                 delete msg;
             break;
         case UDP_I_ERROR:
             if (cb)
                 cb->socketErrorArrived(this, check_and_cast<Indication *>(msg));
             else
                 delete msg;
             break;
         case UDP_I_SOCKET_CLOSED:
             check_and_cast<Indication *>(msg);
             sockState = CLOSED;
             if (cb)
                 cb->socketClosed(this);
             delete msg;
             break;
         default:
             throw cRuntimeError("UdpSocket: invalid msg kind %d, one of the UDP_I_xxx constants expected", msg->getKind());
             break;
     }
 }
Referenced by inet::VoipStreamReceiver::handleMessage(), inet::SimpleVoipReceiver::handleMessage(), inet::UdpSocketIo::handleMessageWhenUp(), inet::UdpEchoApp::handleMessageWhenUp(), inet::UdpVideoStreamClient::handleMessageWhenUp(), inet::UdpSink::handleMessageWhenUp(), inet::UdpBasicApp::handleMessageWhenUp(), inet::DhcpServer::handleMessageWhenUp(), inet::UdpVideoStreamServer::handleMessageWhenUp(), inet::DhcpClient::handleMessageWhenUp(), inet::UdpBasicBurst::handleMessageWhenUp(), inet::aodv::Aodv::handleMessageWhenUp(), and inet::Ldp::handleMessageWhenUp().
send()
void inet::UdpSocket::send (Packet * msg) override virtual
Sends a data packet to the address and port specified previously in a connect() call.
Implements inet::ISocket.
 {
     pk->setKind(UDP_C_DATA);
     sendToUDP(pk);
     sockState = CONNECTED;
 }
Referenced by inet::UdpSocketIo::handleMessageWhenUp(), inet::aodv::Aodv::handleMessageWhenUp(), inet::aodv::Aodv::sendAODVPacket(), inet::TunnelApp::socketDataArrived(), and inet::NetPerfMeter::transmitFrame().
sendTo()
void inet::UdpSocket::sendTo (Packet * msg, L3Address destAddr, int destPort)
Sends a data packet to the given address and port.
Additional options can be passed in a SendOptions struct.
 {
     pk->setKind(UDP_C_DATA);
     auto addressReq = pk->addTagIfAbsent<L3AddressReq>();
     addressReq->setDestAddress(destAddr);
     if (destPort != -1)
         pk->addTagIfAbsent<L4PortReq>()->setDestPort(destPort);
     sendToUDP(pk);
     sockState = CONNECTED;
 }
Referenced by inet::rtp::Rtcp::createPacket(), inet::rtp::Rtp::dataOut(), inet::UdpBasicBurst::generateBurst(), inet::VoipStreamSender::handleMessage(), inet::Rip::processRequest(), inet::UdpVideoStreamClient::requestStream(), inet::Ldp::sendHelloTo(), inet::UdpBasicApp::sendPacket(), inet::Rip::sendPacket(), inet::UdpVideoStreamServer::sendStreamData(), inet::DhcpServer::sendToUDP(), inet::DhcpClient::sendToUdp(), inet::SimpleVoipSender::sendVoIPPacket(), and inet::UdpEchoApp::socketDataArrived().
sendToUDP()
void inet::UdpSocket::sendToUDP (cMessage * msg) protected
 {
     if (!gateToUdp)
         throw cRuntimeError("UdpSocket: setOutputGate() must be invoked before socket can be used");
     EV_DEBUG << "Sending to UDP protocol" << EV_FIELD(msg) << EV_ENDL;
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     tags.addTagIfAbsent<DispatchProtocolReq>()->setProtocol(&Protocol::udp);
     tags.addTagIfAbsent<SocketReq>()->setSocketId(socketId);
     check_and_cast<cSimpleModule *>(gateToUdp->getOwnerModule())->send(msg, gateToUdp);
 }
Referenced by bind(), blockMulticastSources(), close(), connect(), destroy(), joinLocalMulticastGroups(), joinMulticastGroup(), joinMulticastSources(), leaveLocalMulticastGroups(), leaveMulticastGroup(), leaveMulticastSources(), send(), sendTo(), setBroadcast(), setDscp(), setMulticastLoop(), setMulticastOutputInterface(), setMulticastSourceFilter(), setReuseAddress(), setTimeToLive(), setTos(), and unblockMulticastSources().
setBroadcast()
void inet::UdpSocket::setBroadcast (bool broadcast)
Set the Broadcast option on the UDP socket.
This will cause the socket to receive broadcast packets as well.
 {
     auto request = new Request("setBroadcast", UDP_C_SETOPTION);
     UdpSetBroadcastCommand *ctrl = new UdpSetBroadcastCommand();
     ctrl->setBroadcast(broadcast);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::aodv::Aodv::handleStartOperation(), inet::DhcpServer::openSocket(), inet::DhcpClient::openSocket(), inet::UdpSocketIo::setSocketOptions(), inet::UdpSink::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
setCallback()
void inet::UdpSocket::setCallback (ICallback * cb)
Sets a callback object, to be used with processMessage().
This callback object may be your simple module itself (if it multiply inherits from ICallback too, that is you declared it as
class MyAppModule : public cSimpleModule, public UdpSocket::ICallback
and redefined the necessary virtual functions; or you may use dedicated class (and objects) for this purpose.
UdpSocket doesn't delete the callback object in the destructor or on any other occasion.
 {
     cb = callback;
 }
Referenced by inet::UdpEchoApp::handleCrashOperation(), inet::UdpVideoStreamServer::handleCrashOperation(), inet::UdpEchoApp::handleStartOperation(), inet::UdpVideoStreamServer::handleStartOperation(), inet::aodv::Aodv::handleStartOperation(), inet::UdpVideoStreamServer::handleStopOperation(), inet::TunnelApp::initialize(), inet::VoipStreamReceiver::initialize(), inet::DhcpServer::initialize(), inet::DhcpClient::initialize(), inet::SimpleVoipReceiver::initialize(), inet::UdpBasicBurst::processStart(), inet::UdpBasicBurst::processStop(), inet::UdpVideoStreamClient::requestStream(), inet::UdpSocketIo::setSocketOptions(), inet::UdpSink::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
setDscp()
void inet::UdpSocket::setDscp (short dscp)
Sets the Ipv4 / Ipv6 dscp fields of packets sent from the UDP socket.
 {
     auto request = new Request("setDscp", UDP_C_SETOPTION);
     auto *ctrl = new UdpSetDscpCommand();
     ctrl->setDscp(dscp);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpVideoStreamServer::handleStartOperation(), inet::VoipStreamSender::initialize(), inet::UdpBasicBurst::processStart(), inet::UdpSocketIo::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
setMulticastLoop()
void inet::UdpSocket::setMulticastLoop (bool value)
The boolean value specifies whether sent multicast packets should be looped back to the local sockets (like the Unix IP_MULTICAST_LOOP socket option).
 {
     auto request = new Request("setMulticastLoop", UDP_C_SETOPTION);
     UdpSetMulticastLoopCommand *ctrl = new UdpSetMulticastLoopCommand();
     ctrl->setLoop(value);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::Rip::startRIPRouting().
setMulticastOutputInterface()
void inet::UdpSocket::setMulticastOutputInterface (int interfaceId)
Set the output interface for sending multicast packets (like the Unix IP_MULTICAST_IF socket option).
The argument is the interface's ID in InterfaceTable.
 {
     auto request = new Request("setMulticastOutputIf", UDP_C_SETOPTION);
     UdpSetMulticastInterfaceCommand *ctrl = new UdpSetMulticastInterfaceCommand();
     ctrl->setInterfaceId(interfaceId);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpSocketIo::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
setMulticastSourceFilter()
void inet::UdpSocket::setMulticastSourceFilter (int interfaceId, const L3Address & multicastAddr, UdpSourceFilterMode filterMode, const std::vector< L3Address > & sourceList)
Sets the source filter for the given multicast group.
If filterMode is INCLUDE, then UDP packets arriving from one of the sources and to to given multicast group will be passed up to the socket. If filterMode is EXCLUDE, then all UDP packets arriving to the given multicast group will be passed up except those that arrive from the specified sources.
 {
     auto request = new Request("setMulticastSourceFilter", UDP_C_SETOPTION);
     UdpSetMulticastSourceFilterCommand *ctrl = new UdpSetMulticastSourceFilterCommand();
     ctrl->setInterfaceId(interfaceId);
     ctrl->setMulticastAddr(multicastAddr);
     ctrl->setFilterMode(filterMode);
     ctrl->setSourceListArraySize(sourceList.size());
     for (size_t i = 0; i < sourceList.size(); ++i)
         ctrl->setSourceList(i, sourceList[i]);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
setOutputGate()
void inet::UdpSocket::setOutputGate (cGate * toUdp) inline
Sets the gate on which to send to UDP.
Must be invoked before socket can be used. Example: socket.setOutputGate(gate("udpOut"));
 { gateToUdp = toUdp; }
Referenced by inet::sctp::Sctp::bindPortForUDP(), inet::NetPerfMeter::createAndBindSocket(), inet::UdpEchoApp::handleStartOperation(), inet::UdpSocketIo::handleStartOperation(), inet::UdpVideoStreamServer::handleStartOperation(), inet::aodv::Aodv::handleStartOperation(), inet::rtp::Rtp::initialize(), inet::TunnelApp::initialize(), inet::VoipStreamReceiver::initialize(), inet::rtp::Rtcp::initialize(), inet::VoipStreamSender::initialize(), inet::SimpleVoipSender::initialize(), inet::DhcpServer::initialize(), inet::DhcpClient::initialize(), inet::SimpleVoipReceiver::initialize(), inet::Rip::initialize(), inet::Ldp::initialize(), inet::UdpSink::processStart(), inet::UdpBasicApp::processStart(), inet::UdpBasicBurst::processStart(), and inet::UdpVideoStreamClient::requestStream().
setReuseAddress()
void inet::UdpSocket::setReuseAddress (bool value)
Set the ReuseAddress option on the UDP socket.
It is possible to use an already bound address/port in the bind() command only if both the original and the new socket set the ReuseAddress flag to true. Note that only one socket will receive the packets arrived at that address/port (the last bound one). This option works like REUSE_ADDR socket option in Linux.
 {
     auto request = new Request("setReuseAddress", UDP_C_SETOPTION);
     UdpSetReuseAddressCommand *ctrl = new UdpSetReuseAddressCommand();
     ctrl->setReuseAddress(value);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
setTimeToLive()
void inet::UdpSocket::setTimeToLive (int ttl)
Set the TTL (Ipv6: Hop Limit) field on sent packets.
 {
     auto request = new Request("setTTL", UDP_C_SETOPTION);
     UdpSetTimeToLiveCommand *ctrl = new UdpSetTimeToLiveCommand();
     ctrl->setTtl(ttl);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpVideoStreamServer::handleStartOperation(), inet::VoipStreamSender::initialize(), inet::UdpBasicBurst::processStart(), inet::Rip::sendPacket(), inet::UdpSocketIo::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
setTos()
void inet::UdpSocket::setTos (short tos)
Sets the Ipv4 Type of Service / Ipv6 Traffic Class fields of packets sent from the UDP socket.
 {
     auto request = new Request("setTos", UDP_C_SETOPTION);
     auto *ctrl = new UdpSetTosCommand();
     ctrl->setTos(tos);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Referenced by inet::UdpVideoStreamServer::handleStartOperation(), inet::VoipStreamSender::initialize(), inet::UdpBasicBurst::processStart(), inet::UdpSocketIo::setSocketOptions(), and inet::UdpBasicApp::setSocketOptions().
setUserData()
void inet::UdpSocket::setUserData (void * userData) inline
 { this->userData = userData; }
unblockMulticastSources()
void inet::UdpSocket::unblockMulticastSources (int interfaceId, const L3Address & multicastAddr, const std::vector< L3Address > & sourceList)
Unblocks the multicast traffic of the specified group address from the specified sources.
Use this method only if the traffic was previously blocked by calling blockMulticastSources().
 {
     auto request = new Request("unblockMulticastSources", UDP_C_SETOPTION);
     UdpUnblockMulticastSourcesCommand *ctrl = new UdpUnblockMulticastSourcesCommand();
     ctrl->setInterfaceId(interfaceId);
     ctrl->setMulticastAddr(multicastAddr);
     ctrl->setSourceListArraySize(sourceList.size());
     for (size_t i = 0; i < sourceList.size(); ++i)
         ctrl->setSourceList(i, sourceList[i]);
     request->setControlInfo(ctrl);
     sendToUDP(request);
 }
Member Data Documentation
cb
ICallback* inet::UdpSocket::cb = nullptr protected
Referenced by processMessage(), and setCallback().
gateToUdp
cGate* inet::UdpSocket::gateToUdp = nullptr protected
Referenced by destroy(), and sendToUDP().
socketId
int inet::UdpSocket::socketId protected
Referenced by belongsToSocket(), sendToUDP(), and UdpSocket().
sockState
State inet::UdpSocket::sockState = CLOSED protected
Referenced by bind(), close(), connect(), processMessage(), send(), and sendTo().
userData
void* inet::UdpSocket::userData = nullptr protected
The documentation for this class was generated from the following files:
UdpSocket.h
UdpSocket.cc