INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpNeighborTable< IPAddress > Class Template Reference
inet::eigrp::EigrpNeighborTable< IPAddress > Class Template Reference
Class represents EIGRP Neighbor Table.
#include <EigrpNeighborTable.h>
Public Member Functions
EigrpNeighborTable ()
virtual ~EigrpNeighborTable ()
int addNeighbor (EigrpNeighbor< IPAddress > *neighbor)
Adds neighbor to the table.
EigrpNeighbor< IPAddress > * findNeighbor (const IPAddress &ipAddress)
Finds neighbor by IP address.
EigrpNeighbor< IPAddress > * findNeighborById (int id)
Finds neighbor by ID.
EigrpNeighbor< IPAddress > * removeNeighbor (EigrpNeighbor< IPAddress > *neighbor)
Removes neighbor form the table, but the record still exists.
EigrpNeighbor< IPAddress > * getFirstNeighborOnIf (int ifaceId)
Returns first neighbor that resides on specified interface.
int getNumNeighbors () const
EigrpNeighbor< IPAddress > * getNeighbor (int k) const
int setAckOnIface (int ifaceId, uint32_t ackNum)
int getStubCount () const
void incStubCount ()
void decStubCount ()
Protected Types
typedef std::vector< EigrpNeighbor< IPAddress > * > NeighborVector
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *msg) override
virtual int numInitStages () const override
Protected Attributes
NeighborVector neighborVec
Table with neighbors.
int neighborCounter
For unique ID of neighbor.
int stubCount
Number of stub neighbors for optimization.
Detailed Description
template<typename IPAddress>
class inet::eigrp::EigrpNeighborTable< IPAddress >
Class represents EIGRP Neighbor Table.
Member Typedef Documentation
NeighborVector
template<typename IPAddress > typedef std::vector<EigrpNeighbor<IPAddress> *> inet::eigrp::EigrpNeighborTable< IPAddress >::NeighborVector protected
Constructor & Destructor Documentation
EigrpNeighborTable()
template<typename IPAddress > inet::eigrp::EigrpNeighborTable< IPAddress >::EigrpNeighborTable () inline
 { neighborCounter = 1; stubCount = 0; }
~EigrpNeighborTable()
template<typename IPAddress > inet::eigrp::EigrpNeighborTable< IPAddress >::~EigrpNeighborTable virtual
 {
 /*
     int cnt = neighborVec.size();
     EigrpNeighbor<IPAddress> *neigh;
     for (int i = 0; i < cnt; i++)
     {
         neigh = neighborVec[i];
 //        cancelHoldTimer(neigh);
         delete neigh;
     }
     neighborVec.clear();
 */
 }
Member Function Documentation
addNeighbor()
template<typename IPAddress > int inet::eigrp::EigrpNeighborTable< IPAddress >::addNeighbor (EigrpNeighbor< IPAddress > * neighbor)
Adds neighbor to the table.
 {
     neighbor->setNeighborId(neighborCounter);
     this->neighborVec.push_back(neighbor);
     return neighborCounter++;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::createNeighbor(), and inet::eigrp::EigrpIpv6Pdm::createNeighbor().
decStubCount()
template<typename IPAddress > void inet::eigrp::EigrpNeighborTable< IPAddress >::decStubCount () inline
 { stubCount--; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
findNeighbor()
template<typename IPAddress > EigrpNeighbor< IPAddress > * inet::eigrp::EigrpNeighborTable< IPAddress >::findNeighbor (const IPAddress & ipAddress)
Finds neighbor by IP address.
Returns null if neighbor is not found.
 {
     typename NeighborVector::iterator it;
     EigrpNeighbor<IPAddress> *neigh;
     for (it = neighborVec.begin(); it != neighborVec.end(); it++) {
         neigh = *it;
         if (neigh->getIPAddress() == ipAddress) {
             return neigh;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::processInterRoute(), inet::eigrp::EigrpIpv6Pdm::processInterRoute(), inet::eigrp::EigrpIpv4Pdm::processMsgFromNetwork(), and inet::eigrp::EigrpIpv6Pdm::processMsgFromNetwork().
findNeighborById()
template<typename IPAddress > EigrpNeighbor< IPAddress > * inet::eigrp::EigrpNeighborTable< IPAddress >::findNeighborById (int id)
Finds neighbor by ID.
 {
     typename NeighborVector::iterator it;
     for (it = neighborVec.begin(); it != neighborVec.end(); it++) {
         if ((*it)->getNeighborId() == id) {
             return *it;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::getDestIpAddress(), inet::eigrp::EigrpIpv6Pdm::getDestIpAddress(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::setDelayedRemove(), and inet::eigrp::EigrpIpv6Pdm::setDelayedRemove().
getFirstNeighborOnIf()
template<typename IPAddress > EigrpNeighbor< IPAddress > * inet::eigrp::EigrpNeighborTable< IPAddress >::getFirstNeighborOnIf (int ifaceId)
Returns first neighbor that resides on specified interface.
 {
     typename NeighborVector::iterator it;
     for (it = neighborVec.begin(); it != neighborVec.end(); ++it) {
         if ((*it)->getIfaceId() == ifaceId)
             return *it;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::msgToIface(), and inet::eigrp::EigrpIpv6Pdm::msgToIface().
getNeighbor()
template<typename IPAddress > EigrpNeighbor<IPAddress>* inet::eigrp::EigrpNeighborTable< IPAddress >::getNeighbor (int k) const inline
 { return neighborVec[k]; }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
getNumNeighbors()
template<typename IPAddress > int inet::eigrp::EigrpNeighborTable< IPAddress >::getNumNeighbors () const inline
 { return neighborVec.size(); }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
getStubCount()
template<typename IPAddress > int inet::eigrp::EigrpNeighborTable< IPAddress >::getStubCount () const inline
 { return stubCount; }
Referenced by inet::eigrp::EigrpIpv4Pdm::sendQuery(), inet::eigrp::EigrpIpv6Pdm::sendQuery(), inet::eigrp::EigrpIpv4Pdm::sendUpdateToStubs(), inet::eigrp::EigrpIpv6Pdm::sendUpdateToStubs(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
handleMessage()
template<typename IPAddress > void inet::eigrp::EigrpNeighborTable< IPAddress >::handleMessage (cMessage * msg) override protected virtual
 {
     throw cRuntimeError("This module does not process messages");
 }
incStubCount()
template<typename IPAddress > void inet::eigrp::EigrpNeighborTable< IPAddress >::incStubCount () inline
 { stubCount++; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), and inet::eigrp::EigrpIpv6Pdm::processNewNeighbor().
initialize()
template<typename IPAddress > void inet::eigrp::EigrpNeighborTable< IPAddress >::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_ROUTING_PROTOCOLS) {
         WATCH_PTRVECTOR(neighborVec);
     }
 }
numInitStages()
template<typename IPAddress > virtual int inet::eigrp::EigrpNeighborTable< IPAddress >::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
removeNeighbor()
template<typename IPAddress > EigrpNeighbor< IPAddress > * inet::eigrp::EigrpNeighborTable< IPAddress >::removeNeighbor (EigrpNeighbor< IPAddress > * neighbor)
Removes neighbor form the table, but the record still exists.
 {
     typename NeighborVector::iterator it;
     for (it = neighborVec.begin(); it != neighborVec.end(); ++it) {
         if (*it == neighbor) {
             neighborVec.erase(it);
             return neighbor;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
setAckOnIface()
template<typename IPAddress > int inet::eigrp::EigrpNeighborTable< IPAddress >::setAckOnIface (int ifaceId, uint32_t ackNum)
 {
     typename NeighborVector::iterator it;
     int neighCnt = 0;
     for (it = neighborVec.begin(); it != neighborVec.end(); ++it) {
         if ((*it)->getIfaceId() == ifaceId) {
             neighCnt++;
             (*it)->setAck(ackNum);
         }
     }
     return neighCnt;
 }
Member Data Documentation
neighborCounter
template<typename IPAddress > int inet::eigrp::EigrpNeighborTable< IPAddress >::neighborCounter protected
For unique ID of neighbor.
Referenced by inet::eigrp::EigrpNeighborTable< Ipv4Address >::EigrpNeighborTable().
neighborVec
template<typename IPAddress > NeighborVector inet::eigrp::EigrpNeighborTable< IPAddress >::neighborVec protected
Table with neighbors.
Referenced by inet::eigrp::EigrpNeighborTable< Ipv4Address >::getNeighbor(), and inet::eigrp::EigrpNeighborTable< Ipv4Address >::getNumNeighbors().
stubCount
template<typename IPAddress > int inet::eigrp::EigrpNeighborTable< IPAddress >::stubCount protected
Number of stub neighbors for optimization.
Referenced by inet::eigrp::EigrpNeighborTable< Ipv4Address >::decStubCount(), inet::eigrp::EigrpNeighborTable< Ipv4Address >::EigrpNeighborTable(), inet::eigrp::EigrpNeighborTable< Ipv4Address >::getStubCount(), and inet::eigrp::EigrpNeighborTable< Ipv4Address >::incStubCount().
The documentation for this class was generated from the following files:
EigrpNeighborTable.h
EigrpNeighborTable.cc