INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3IntraAreaPrefixLsa Class Reference
inet::ospfv3::Ospfv3IntraAreaPrefixLsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:293 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3IntraAreaPrefixLsa ()
Ospfv3IntraAreaPrefixLsa (const Ospfv3IntraAreaPrefixLsa &other)
virtual ~Ospfv3IntraAreaPrefixLsa ()
Ospfv3IntraAreaPrefixLsa & operator= (const Ospfv3IntraAreaPrefixLsa &other)
virtual Ospfv3IntraAreaPrefixLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getNumPrefixes () const
virtual void setNumPrefixes (unsigned short numPrefixes)
virtual unsigned short getReferencedLSType () const
virtual void setReferencedLSType (unsigned short referencedLSType)
virtual const ::inet::Ipv4Address & getReferencedLSID () const
virtual ::inet::Ipv4Address & getReferencedLSIDForUpdate ()
virtual void setReferencedLSID (const ::inet::Ipv4Address &referencedLSID)
virtual const ::inet::Ipv4Address & getReferencedAdvRtr () const
virtual ::inet::Ipv4Address & getReferencedAdvRtrForUpdate ()
virtual void setReferencedAdvRtr (const ::inet::Ipv4Address &referencedAdvRtr)
virtual void setPrefixesArraySize (size_t size)
virtual size_t getPrefixesArraySize () const
virtual const Ospfv3LsaPrefixMetric & getPrefixes (size_t k) const
virtual Ospfv3LsaPrefixMetric & getPrefixesForUpdate (size_t k)
virtual void setPrefixes (size_t k, const Ospfv3LsaPrefixMetric &prefixes)
virtual void insertPrefixes (size_t k, const Ospfv3LsaPrefixMetric &prefixes)
void insertPrefixes (const Ospfv3LsaPrefixMetric &prefixes)
virtual void appendPrefixes (const Ospfv3LsaPrefixMetric &prefixes)
virtual void erasePrefixes (size_t k)
Public Member Functions inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3IntraAreaPrefixLsa &)=delete
Protected Member Functions inherited from inet::ospfv3::Ospfv3Lsa
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
unsigned short numPrefixes = 0
unsigned short referencedLSType = 0
::inet::Ipv4Address referencedLSID
::inet::Ipv4Address referencedAdvRtr
Ospfv3LsaPrefixMetric * prefixes = nullptr
size_t prefixes_arraysize = 0
Protected Attributes inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3IntraAreaPrefixLsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:293 by opp_msgtool.
// Intra-Area-Prefix-LSAs
class Ospfv3IntraAreaPrefixLsa extends Ospfv3Lsa
{
    unsigned short numPrefixes;
    unsigned short referencedLSType;
    Ipv4Address referencedLSID;
    Ipv4Address referencedAdvRtr;
    Ospfv3LsaPrefixMetric prefixes[];
}
Constructor & Destructor Documentation
Ospfv3IntraAreaPrefixLsa() [1/2]
inet::ospfv3::Ospfv3IntraAreaPrefixLsa::Ospfv3IntraAreaPrefixLsa ()
Ospfv3IntraAreaPrefixLsa() [2/2]
inet::ospfv3::Ospfv3IntraAreaPrefixLsa::Ospfv3IntraAreaPrefixLsa (const Ospfv3IntraAreaPrefixLsa & other)
~Ospfv3IntraAreaPrefixLsa()
virtual inet::ospfv3::Ospfv3IntraAreaPrefixLsa::~Ospfv3IntraAreaPrefixLsa () virtual
Member Function Documentation
appendPrefixes()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::appendPrefixes (const Ospfv3LsaPrefixMetric & prefixes) virtual
copy()
void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::copy (const Ospfv3IntraAreaPrefixLsa & other) private
dup()
virtual Ospfv3IntraAreaPrefixLsa* inet::ospfv3::Ospfv3IntraAreaPrefixLsa::dup () const inline override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
 {return new Ospfv3IntraAreaPrefixLsa(*this);}
erasePrefixes()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::erasePrefixes (size_t k) virtual
getNumPrefixes()
virtual unsigned short inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getNumPrefixes () const virtual
Referenced by inet::ospfv3::calculateLSASize(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom().
getPrefixes()
virtual const Ospfv3LsaPrefixMetric& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getPrefixes (size_t k) const virtual
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::calculateLSASize(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::IntraAreaPrefixLSAAlreadyExists(), inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getPrefixesArraySize()
virtual size_t inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getPrefixesArraySize () const virtual
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::IntraAreaPrefixLSAAlreadyExists(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getPrefixesForUpdate()
virtual Ospfv3LsaPrefixMetric& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getPrefixesForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv3LsaPrefixMetric&>(const_cast<Ospfv3IntraAreaPrefixLsa*>(this)->getPrefixes(k));}
Referenced by inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA().
getReferencedAdvRtr()
virtual const ::inet::Ipv4Address& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getReferencedAdvRtr () const virtual
Referenced by inet::ospfv3::Ospfv3Area::deleteRouterLSA(), and inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom().
getReferencedAdvRtrForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getReferencedAdvRtrForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv3IntraAreaPrefixLsa*>(this)->getReferencedAdvRtr());}
getReferencedLSID()
virtual const ::inet::Ipv4Address& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getReferencedLSID () const virtual
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Area::deleteRouterLSA(), and inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom().
getReferencedLSIDForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getReferencedLSIDForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv3IntraAreaPrefixLsa*>(this)->getReferencedLSID());}
getReferencedLSType()
virtual unsigned short inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getReferencedLSType () const virtual
Referenced by inet::ospfv3::Ospfv3Area::deleteRouterLSA(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::IntraAreaPrefixLSAAlreadyExists(), and inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom().
insertPrefixes() [1/2]
void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::insertPrefixes (const Ospfv3LsaPrefixMetric & prefixes) inline
 {appendPrefixes(prefixes);}
insertPrefixes() [2/2]
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::insertPrefixes (size_t k, const Ospfv3LsaPrefixMetric & prefixes) virtual
operator=()
Ospfv3IntraAreaPrefixLsa& inet::ospfv3::Ospfv3IntraAreaPrefixLsa::operator= (const Ospfv3IntraAreaPrefixLsa & other)
operator==()
bool inet::ospfv3::Ospfv3IntraAreaPrefixLsa::operator== (const Ospfv3IntraAreaPrefixLsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setNumPrefixes()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::setNumPrefixes (unsigned short numPrefixes) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
setPrefixes()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::setPrefixes (size_t k, const Ospfv3LsaPrefixMetric & prefixes) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
setPrefixesArraySize()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::setPrefixesArraySize (size_t size) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
setReferencedAdvRtr()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::setReferencedAdvRtr (const ::inet::Ipv4Address & referencedAdvRtr) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
setReferencedLSID()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::setReferencedLSID (const ::inet::Ipv4Address & referencedLSID) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
setReferencedLSType()
virtual void inet::ospfv3::Ospfv3IntraAreaPrefixLsa::setReferencedLSType (unsigned short referencedLSType) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
Member Data Documentation
numPrefixes
unsigned short inet::ospfv3::Ospfv3IntraAreaPrefixLsa::numPrefixes = 0 protected
prefixes
Ospfv3LsaPrefixMetric* inet::ospfv3::Ospfv3IntraAreaPrefixLsa::prefixes = nullptr protected
prefixes_arraysize
size_t inet::ospfv3::Ospfv3IntraAreaPrefixLsa::prefixes_arraysize = 0 protected
referencedAdvRtr
::inet::Ipv4Address inet::ospfv3::Ospfv3IntraAreaPrefixLsa::referencedAdvRtr protected
referencedLSID
::inet::Ipv4Address inet::ospfv3::Ospfv3IntraAreaPrefixLsa::referencedLSID protected
referencedLSType
unsigned short inet::ospfv3::Ospfv3IntraAreaPrefixLsa::referencedLSType = 0 protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h