INET Framework for OMNeT++/OMNEST: inet::sctp::SctpHeader Class Reference
inet::sctp::SctpHeader Class Reference
Represents an SCTP Message.
#include <SctpHeader.h>
Public Member Functions
SctpHeader ()
SctpHeader (const SctpHeader &other)
~SctpHeader ()
SctpHeader & operator= (const SctpHeader &other)
virtual SctpHeader * dup () const override
virtual void setSctpChunksArraySize (size_t size) override
virtual void setSctpChunks (size_t k, SctpChunk *sctpChunks) override
virtual size_t getSctpChunksArraySize () const override
Returns the number of chunks in this SCTP packet.
virtual const SctpChunk * getSctpChunks (size_t k) const override
Returns the kth chunk in this SCTP packet.
virtual void appendSctpChunks (SctpChunk *sctpChunks) override
Adds a message object to the SCTP packet.
virtual void insertSctpChunks (size_t k, SctpChunk *sctpChunks) override
virtual void eraseSctpChunks (size_t k) override
virtual void replaceSctpChunk (SctpChunk *msg, uint32_t k)
virtual SctpChunk * removeFirstChunk ()
Removes and returns the first message object in this SCTP packet.
virtual SctpChunk * removeLastChunk ()
virtual SctpChunk * peekFirstChunk () const
virtual SctpChunk * peekLastChunk () const
virtual unsigned int getSourcePort () const override
virtual void setSourcePort (unsigned int port) override
virtual unsigned int getDestinationPort () const override
virtual void setDestinationPort (unsigned int port) override
virtual void insertSctpChunks (size_t k, SctpChunk *sctpChunks)=0
void insertSctpChunks (SctpChunk *sctpChunks)
Public Member Functions inherited from inet::sctp::SctpHeader_Base
virtual ~SctpHeader_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getSrcPort () const
virtual void setSrcPort (uint16_t srcPort)
virtual uint16_t getDestPort () const
virtual void setDestPort (uint16_t destPort)
virtual uint32_t getVTag () const
virtual void setVTag (uint32_t vTag)
virtual bool getChecksumOk () const
virtual void setChecksumOk (bool checksumOk)
virtual uint32_t getCrc () const
virtual void setCrc (uint32_t crc)
virtual ::inet::CrcMode getCrcMode () const
virtual void setCrcMode (::inet::CrcMode crcMode)
virtual unsigned short getHeaderLength () const
virtual void setHeaderLength (unsigned short headerLength)
virtual SctpChunk * getSctpChunksForUpdate (size_t k)
void insertSctpChunks (SctpChunk *sctpChunks)
Public Member Functions inherited from inet::FieldsChunk
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Types
typedef std::vector< SctpChunk * > SctpChunkList
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Protected Attributes
SctpChunkList sctpChunkList
Protected Attributes inherited from inet::sctp::SctpHeader_Base
uint16_t srcPort = 0
uint16_t destPort = 0
uint32_t vTag = 0
bool checksumOk = false
uint32_t crc = 0
::inet::CrcMode crcMode = CRC_MODE_UNDEFINED
unsigned short headerLength = 12
Protected Attributes inherited from inet::FieldsChunk
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Private Member Functions
void copy (const SctpHeader &other)
void clean ()
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Member Functions inherited from inet::sctp::SctpHeader_Base
bool operator== (const SctpHeader_Base &)=delete
SctpHeader_Base ()
SctpHeader_Base (const SctpHeader_Base &other)
SctpHeader_Base & operator= (const SctpHeader_Base &other)
Protected Member Functions inherited from inet::FieldsChunk
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Static Protected Member Functions inherited from inet::FieldsChunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
Represents an SCTP Message.
More info in the SctpHeader.msg file (and the documentation generated from it).
Member Typedef Documentation
SctpChunkList
typedef std::vector<SctpChunk *> inet::sctp::SctpHeader::SctpChunkList protected
Constructor & Destructor Documentation
SctpHeader() [1/2]
inet::sctp::SctpHeader::SctpHeader () inline
 : SctpHeader_Base() {}
SctpHeader() [2/2]
inet::sctp::SctpHeader::SctpHeader (const SctpHeader & other) inline
 : SctpHeader_Base(other) { copy(other); }
~SctpHeader()
inet::sctp::SctpHeader::~SctpHeader ()
 {
     clean();
 }
Member Function Documentation
appendSctpChunks()
void inet::sctp::SctpHeader::appendSctpChunks (SctpChunk * sctpChunks) override virtual
Adds a message object to the SCTP packet.
The packet length will be adjusted
Implements inet::sctp::SctpHeader_Base.
 {
     handleChange();
     sctpChunkList.push_back(chunk);
     take(chunk);
     headerLength += ADD_PADDING(chunk->getByteLength());
     setChunkLength(B(headerLength));
 }
Referenced by inet::sctp::SctpAssociation::processPacketDropArrived(), inet::sctp::SctpNatHook::sendBackError(), and inet::sctp::SctpAssociation::sendPacketDrop().
clean()
void inet::sctp::SctpHeader::clean () private
 {
 //    handleChange();
     if (this->getSctpChunksArraySize() > 0) {
         auto iterator = sctpChunkList.begin();
         while (iterator != sctpChunkList.end()) {
 //            SctpChunk *chunk = (*iterator);
             sctpChunkList.erase(iterator);
 //            delete chunk;
         }
     }
     /* sctpChunkList.clear();
      setHeaderLength(SCTP_COMMON_HEADER);
      setChunkLength(B(SCTP_COMMON_HEADER));*/
 }
Referenced by operator=(), and ~SctpHeader().
copy()
void inet::sctp::SctpHeader::copy (const SctpHeader & other) private
 {
 //    handleChange();
     setVTag(other.getVTag());
     setSrcPort(other.getSrcPort());
     setDestPort(other.getDestPort());
     setChecksumOk(other.getChecksumOk());
     for (const auto& elem : other.sctpChunkList) {
         SctpChunk *chunk = (elem)->dup();
         take(chunk);
         sctpChunkList.push_back(chunk);
     }
     ASSERT(B(getChunkLength()).get() == B(other.getChunkLength()).get());
 }
Referenced by operator=().
dup()
virtual SctpHeader* inet::sctp::SctpHeader::dup () const inline override virtual
Reimplemented from inet::sctp::SctpHeader_Base.
 { return new SctpHeader(*this); }
Referenced by copy(), and inet::sctp::Sctp::handleMessage().
eraseSctpChunks()
virtual void inet::sctp::SctpHeader::eraseSctpChunks (size_t k) inline override virtual
Implements inet::sctp::SctpHeader_Base.
 {}
getDestinationPort()
virtual unsigned int inet::sctp::SctpHeader::getDestinationPort () const inline override virtual
Implements inet::TransportHeaderBase.
 { return SctpHeader_Base::getDestPort(); }
getSctpChunks()
virtual const SctpChunk* inet::sctp::SctpHeader::getSctpChunks (size_t k) const inline override virtual
Returns the kth chunk in this SCTP packet.
Implements inet::sctp::SctpHeader_Base.
 { return sctpChunkList.at(k); }
Referenced by inet::sctp::Sctp::handleMessage(), and inet::sctp::SctpAssociation::sendPacketDrop().
getSctpChunksArraySize()
size_t inet::sctp::SctpHeader::getSctpChunksArraySize () const override virtual
Returns the number of chunks in this SCTP packet.
Implements inet::sctp::SctpHeader_Base.
 {
     return sctpChunkList.size();
 }
Referenced by clean(), inet::sctp::SctpAssociation::disposeOf(), inet::sctp::Sctp::handleMessage(), inet::sctp::SctpAssociation::process_RCV_Message(), and inet::sctp::SctpAssociation::sendPacketDrop().
getSourcePort()
virtual unsigned int inet::sctp::SctpHeader::getSourcePort () const inline override virtual
Implements inet::TransportHeaderBase.
 { return SctpHeader_Base::getSrcPort(); }
insertSctpChunks() [1/3]
void inet::sctp::SctpHeader_Base::insertSctpChunks inline
 {appendSctpChunks(sctpChunks);}
insertSctpChunks() [2/3]
void inet::sctp::SctpHeader::insertSctpChunks (size_t k, SctpChunk * sctpChunks) override virtual
Implements inet::sctp::SctpHeader_Base.
 {
     handleChange();
     sctpChunkList.insert(sctpChunkList.begin() + k, chunk);
     take(chunk);
     headerLength += ADD_PADDING(chunk->getByteLength());
     setChunkLength(B(headerLength));
 }
insertSctpChunks() [3/3]
virtual void inet::sctp::SctpHeader_Base::insertSctpChunks
operator=()
SctpHeader & inet::sctp::SctpHeader::operator= (const SctpHeader & other)
 {
     if (this == &other)
         return *this;
     clean();
     SctpHeader_Base::operator=(other);
     copy(other);
     return *this;
 }
peekFirstChunk()
SctpChunk * inet::sctp::SctpHeader::peekFirstChunk () const virtual
 {
     if (sctpChunkList.empty())
         return nullptr;
     SctpChunk *msg = sctpChunkList.front();
     return msg;
 }
peekLastChunk()
SctpChunk * inet::sctp::SctpHeader::peekLastChunk () const virtual
 {
     if (sctpChunkList.empty())
         return nullptr;
     SctpChunk *msg = sctpChunkList.back();
     return msg;
 }
removeFirstChunk()
SctpChunk * inet::sctp::SctpHeader::removeFirstChunk () virtual
Removes and returns the first message object in this SCTP packet.
 {
     handleChange();
     if (sctpChunkList.empty())
         return nullptr;
     SctpChunk *msg = sctpChunkList.front();
     headerLength -= ADD_PADDING(msg->getByteLength());
     sctpChunkList.erase(sctpChunkList.begin());
     drop(msg);
     setChunkLength(B(headerLength));
     return msg;
 }
Referenced by inet::sctp::SctpAssociation::disposeOf(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::removeFirstChunk(), and inet::sctp::SctpNatHook::sendBackError().
removeLastChunk()
SctpChunk * inet::sctp::SctpHeader::removeLastChunk () virtual
 {
     handleChange();
     if (sctpChunkList.empty())
         return nullptr;
     SctpChunk *msg = sctpChunkList.back();
     sctpChunkList.pop_back();
     drop(msg);
     this->addChunkLength(B(ADD_PADDING(msg->getByteLength())));
     return msg;
 }
Referenced by inet::sctp::SctpAssociation::sendPacketDrop().
replaceSctpChunk()
void inet::sctp::SctpHeader::replaceSctpChunk (SctpChunk * msg, uint32_t k) virtual
 {
     setSctpChunks(k, chunk);
 }
setDestinationPort()
virtual void inet::sctp::SctpHeader::setDestinationPort (unsigned int port) inline override virtual
Implements inet::TransportHeaderBase.
 { SctpHeader_Base::setDestPort(port); }
setSctpChunks()
void inet::sctp::SctpHeader::setSctpChunks (size_t k, SctpChunk * sctpChunks) override virtual
Implements inet::sctp::SctpHeader_Base.
 {
     handleChange();
     SctpChunk *tmp = sctpChunkList.at(k);
     if (tmp == chunk)
         return;
     headerLength -= ADD_PADDING(tmp->getByteLength());
     dropAndDelete(tmp);
     sctpChunkList[k] = chunk;
     take(chunk);
     headerLength += ADD_PADDING(chunk->getByteLength());
     setChunkLength(B(headerLength));
 }
Referenced by replaceSctpChunk().
setSctpChunksArraySize()
void inet::sctp::SctpHeader::setSctpChunksArraySize (size_t size) override virtual
Implements inet::sctp::SctpHeader_Base.
 {
     throw cException(this, "setSctpChunkArraySize() not supported, use appendSctpChunks()");
 }
setSourcePort()
virtual void inet::sctp::SctpHeader::setSourcePort (unsigned int port) inline override virtual
Implements inet::TransportHeaderBase.
 { SctpHeader_Base::setSrcPort(port); }
Member Data Documentation
sctpChunkList
SctpChunkList inet::sctp::SctpHeader::sctpChunkList protected
Referenced by appendSctpChunks(), clean(), copy(), getSctpChunksArraySize(), insertSctpChunks(), peekFirstChunk(), peekLastChunk(), removeFirstChunk(), removeLastChunk(), and setSctpChunks().
The documentation for this class was generated from the following files:
SctpHeader.h
SctpHeader.cc