INET Framework for OMNeT++/OMNEST: inet::PimInterface Class Reference
inet::PimInterface Class Reference
An entry of PimInterfaceTable holding PIM specific parameters and state of the interface.
#include <PimInterfaceTable.h>
Public Types
enum PimMode { DenseMode = 1, SparseMode = 2 }
Public Member Functions
PimInterface (NetworkInterface *ie, PimMode mode, bool stateRefreshFlag)
virtual std::string str () const override
int getInterfaceId () const
NetworkInterface * getInterfacePtr () const
PimMode getMode () const
bool getSR () const
Ipv4Address getDRAddress () const
void setDRAddress (Ipv4Address address)
Protected Attributes
NetworkInterface * ie
PimMode mode
bool stateRefreshFlag
Ipv4Address drAddress
Detailed Description
An entry of PimInterfaceTable holding PIM specific parameters and state of the interface.
Member Enumeration Documentation
PimMode
enum inet::PimInterface::PimMode
Enumerator
DenseMode
SparseMode
                  {
         DenseMode  = 1,
         SparseMode = 2
     };
Constructor & Destructor Documentation
PimInterface()
inet::PimInterface::PimInterface (NetworkInterface * ie, PimMode mode, bool stateRefreshFlag) inline
         : ie(ie), mode(mode), stateRefreshFlag(stateRefreshFlag) { ASSERT(ie); }
Member Function Documentation
getDRAddress()
Ipv4Address inet::PimInterface::getDRAddress () const inline
 { return drAddress; }
Referenced by inet::PimSm::IamDR(), and inet::PimSm::updateDesignatedRouterAddress().
getInterfaceId()
int inet::PimInterface::getInterfaceId () const inline
 { return ie->getInterfaceId(); }
Referenced by inet::PimInterfaceTable::getInterfaceById(), inet::PimDm::receiveSignal(), inet::PimSm::receiveSignal(), inet::PimBase::sendHelloPacket(), and inet::PimDm::unroutableMulticastPacketArrived().
getInterfacePtr()
NetworkInterface* inet::PimInterface::getInterfacePtr () const inline
 { return ie; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::PimBase::handleStartOperation(), inet::PimDm::receiveSignal(), inet::PimBase::sendHelloPacket(), and inet::PimDm::unroutableMulticastPacketArrived().
getMode()
PimMode inet::PimInterface::getMode () const inline
 { return mode; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::PimBase::handleStartOperation(), inet::PimSplitter::processPIMPacket(), inet::PimDm::receiveSignal(), inet::PimSm::receiveSignal(), inet::PimBase::sendHelloPackets(), inet::PimDm::unroutableMulticastPacketArrived(), and inet::PimSm::unroutableMulticastPacketArrived().
getSR()
bool inet::PimInterface::getSR () const inline
 { return stateRefreshFlag; }
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), and inet::PimDm::unroutableMulticastPacketArrived().
setDRAddress()
void inet::PimInterface::setDRAddress (Ipv4Address address) inline
 { drAddress = address; }
Referenced by inet::PimSm::updateDesignatedRouterAddress().
str()
std::string inet::PimInterface::str () const override virtual
 {
     std::stringstream out;
     out << this;
     return out.str();
 }
Member Data Documentation
drAddress
Ipv4Address inet::PimInterface::drAddress protected
ie
NetworkInterface* inet::PimInterface::ie protected
mode
PimMode inet::PimInterface::mode protected
stateRefreshFlag
bool inet::PimInterface::stateRefreshFlag protected
The documentation for this class was generated from the following files:
PimInterfaceTable.h
PimInterfaceTable.cc