INET Framework for OMNeT++/OMNEST: inet::physicalenvironment::IMaterial Class Reference
inet::physicalenvironment::IMaterial Class Reference abstract
#include <IMaterial.h>
Public Member Functions
virtual Ohmm getResistivity () const =0
virtual double getRelativePermittivity () const =0
virtual double getRelativePermeability () const =0
virtual double getDielectricLossTangent (Hz frequency) const =0
virtual double getRefractiveIndex () const =0
virtual mps getPropagationSpeed () const =0
Member Function Documentation
getDielectricLossTangent()
virtual double inet::physicalenvironment::IMaterial::getDielectricLossTangent (Hz frequency) const pure virtual
Implemented in inet::physicalenvironment::Material.
Referenced by inet::physicallayer::DielectricObstacleLoss::computeDielectricLoss().
getPropagationSpeed()
virtual mps inet::physicalenvironment::IMaterial::getPropagationSpeed () const pure virtual
Implemented in inet::physicalenvironment::Material.
Referenced by inet::physicallayer::DielectricObstacleLoss::computeDielectricLoss().
getRefractiveIndex()
virtual double inet::physicalenvironment::IMaterial::getRefractiveIndex () const pure virtual
Implemented in inet::physicalenvironment::Material.
Referenced by inet::physicallayer::DielectricObstacleLoss::computeReflectionLoss().
getRelativePermeability()
virtual double inet::physicalenvironment::IMaterial::getRelativePermeability () const pure virtual
Implemented in inet::physicalenvironment::Material.
getRelativePermittivity()
virtual double inet::physicalenvironment::IMaterial::getRelativePermittivity () const pure virtual
Implemented in inet::physicalenvironment::Material.
getResistivity()
virtual Ohmm inet::physicalenvironment::IMaterial::getResistivity () const pure virtual
Implemented in inet::physicalenvironment::Material.
The documentation for this class was generated from the following file:
IMaterial.h