INET Framework for OMNeT++/OMNEST: inet::Macho::_Initializer Class Reference
inet::Macho::_Initializer Class Reference abstract
#include <Macho.h>
Public Member Functions
virtual ~_Initializer ()
virtual _Initializer * clone ()=0
virtual void destroy ()
virtual Key adapt (Key key)
virtual void execute (_StateInstance &instance)=0
Constructor & Destructor Documentation
~_Initializer()
virtual inet::Macho::_Initializer::~_Initializer () inline virtual
 {}
Member Function Documentation
adapt()
virtual Key inet::Macho::_Initializer::adapt (Key key) inline virtual
Reimplemented in inet::Macho::_AdaptingInitializer.
 { return key; }
Referenced by inet::Macho::Alias::key().
clone()
virtual _Initializer* inet::Macho::_Initializer::clone () pure virtual
Implemented in inet::Macho::_Initializer6< S, P1, P2, P3, P4, P5, P6 >, inet::Macho::_Initializer5< S, P1, P2, P3, P4, P5 >, inet::Macho::_Initializer4< S, P1, P2, P3, P4 >, inet::Macho::_Initializer3< S, P1, P2, P3 >, inet::Macho::_Initializer2< S, P1, P2 >, inet::Macho::_Initializer1< S, P1 >, inet::Macho::_AdaptingInitializer, and inet::Macho::_StaticInitializer.
Referenced by inet::Macho::Alias::operator=(), and inet::Macho::Alias::setState().
destroy()
virtual void inet::Macho::_Initializer::destroy () inline virtual
Reimplemented in inet::Macho::_StaticInitializer.
 { delete this; }
Referenced by inet::Macho::Alias::operator=(), inet::Macho::_MachineBase::rattleOn(), and inet::Macho::Alias::~Alias().
execute()
virtual void inet::Macho::_Initializer::execute (_StateInstance & instance) pure virtual
Implemented in inet::Macho::_Initializer6< S, P1, P2, P3, P4, P5, P6 >, inet::Macho::_Initializer5< S, P1, P2, P3, P4, P5 >, inet::Macho::_Initializer4< S, P1, P2, P3, P4 >, inet::Macho::_Initializer3< S, P1, P2, P3 >, inet::Macho::_Initializer2< S, P1, P2 >, inet::Macho::_Initializer1< S, P1 >, inet::Macho::_AdaptingInitializer, inet::Macho::_HistoryInitializer, and inet::Macho::_DefaultInitializer.
Referenced by inet::Macho::_MachineBase::rattleOn().
The documentation for this class was generated from the following file:
Macho.h