INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmPreambleMode Class Reference
inet::physicallayer::Ieee80211OfdmPreambleMode Class Reference
#include <Ieee80211OfdmMode.h>
Public Member Functions
Ieee80211OfdmPreambleMode (Hz channelSpacing)
virtual ~Ieee80211OfdmPreambleMode ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
const simtime_t getTrainingSymbolGIDuration () const
const simtime_t getShortTrainingSequenceDuration () const
const simtime_t getLongTrainingSequenceDuration () const
virtual const simtime_t getDuration () const override
virtual Ptr< Ieee80211PhyPreamble > createPreamble () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing)
Hz getSubcarrierFrequencySpacing () const
const simtime_t getFFTTransformPeriod () const
const simtime_t getGIDuration () const
const simtime_t getSymbolInterval () const
const Hz getChannelSpacing () const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Hz channelSpacing
Constructor & Destructor Documentation
Ieee80211OfdmPreambleMode()
inet::physicallayer::Ieee80211OfdmPreambleMode::Ieee80211OfdmPreambleMode (Hz channelSpacing)
                                                                       :
     Ieee80211OfdmTimingRelatedParametersBase(channelSpacing)
 {
 }
~Ieee80211OfdmPreambleMode()
virtual inet::physicallayer::Ieee80211OfdmPreambleMode::~Ieee80211OfdmPreambleMode () inline virtual
 {}
Member Function Documentation
createPreamble()
virtual Ptr<Ieee80211PhyPreamble> inet::physicallayer::Ieee80211OfdmPreambleMode::createPreamble () const inline override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 { return makeShared<Ieee80211OfdmPhyPreamble>(); }
getDuration()
virtual const simtime_t inet::physicallayer::Ieee80211OfdmPreambleMode::getDuration () const inline override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 { return getShortTrainingSequenceDuration() + getLongTrainingSequenceDuration(); }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211OfdmMode::getDuration(), and inet::physicallayer::Ieee80211OfdmMode::getPreambleLength().
getLongTrainingSequenceDuration()
const simtime_t inet::physicallayer::Ieee80211OfdmPreambleMode::getLongTrainingSequenceDuration () const inline
 { return getTrainingSymbolGIDuration() + 2 * getFFTTransformPeriod(); }
getShortTrainingSequenceDuration()
const simtime_t inet::physicallayer::Ieee80211OfdmPreambleMode::getShortTrainingSequenceDuration () const inline
 { return 10 * getFFTTransformPeriod() / 4; }
getTrainingSymbolGIDuration()
const simtime_t inet::physicallayer::Ieee80211OfdmPreambleMode::getTrainingSymbolGIDuration () const inline
 { return getFFTTransformPeriod() / 2; }
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmPreambleMode::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     return stream << "Ieee80211OfdmPreambleMode";
 }
The documentation for this class was generated from the following files:
Ieee80211OfdmMode.h
Ieee80211OfdmMode.cc