INET Framework for OMNeT++/OMNEST: inet::ieee80211::IOriginatorQoSAckPolicy Class Reference
inet::ieee80211::IOriginatorQoSAckPolicy Class Reference abstract
#include <IOriginatorQoSAckPolicy.h>
Public Member Functions
virtual ~IOriginatorQoSAckPolicy ()
virtual bool isAckNeeded (const Ptr< const Ieee80211MgmtHeader > &header) const =0
virtual AckPolicy computeAckPolicy (Packet *packet, const Ptr< const Ieee80211DataHeader > &header, OriginatorBlockAckAgreement *agreement) const =0
virtual bool isBlockAckReqNeeded (InProgressFrames *inProgressFrames, TxopProcedure *txopProcedure) const =0
virtual bool isBlockAckPolicyEligibleFrame (Packet *packet, const Ptr< const Ieee80211DataHeader > &header) const =0
virtual std::tuple< MacAddress, SequenceNumberCyclic, Tid > computeBlockAckReqParameters (InProgressFrames *inProgressFrames, TxopProcedure *txopProcedure) const =0
virtual simtime_t getAckTimeout (Packet *packet, const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader) const =0
virtual simtime_t getBlockAckTimeout (Packet *packet, const Ptr< const Ieee80211BlockAckReq > &blockAckReq) const =0
Constructor & Destructor Documentation
~IOriginatorQoSAckPolicy()
virtual inet::ieee80211::IOriginatorQoSAckPolicy::~IOriginatorQoSAckPolicy () inline virtual
 {}
Member Function Documentation
computeAckPolicy()
virtual AckPolicy inet::ieee80211::IOriginatorQoSAckPolicy::computeAckPolicy (Packet * packet, const Ptr< const Ieee80211DataHeader > & header, OriginatorBlockAckAgreement * agreement) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
Referenced by inet::ieee80211::TxOpFs::selectTxOpSequence().
computeBlockAckReqParameters()
virtual std::tuple<MacAddress, SequenceNumberCyclic, Tid> inet::ieee80211::IOriginatorQoSAckPolicy::computeBlockAckReqParameters (InProgressFrames * inProgressFrames, TxopProcedure * txopProcedure) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
Referenced by inet::ieee80211::BlockAckReqBlockAckFs::prepareStep().
getAckTimeout()
virtual simtime_t inet::ieee80211::IOriginatorQoSAckPolicy::getAckTimeout (Packet * packet, const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
Referenced by inet::ieee80211::FrameSequenceContext::getAckTimeout().
getBlockAckTimeout()
virtual simtime_t inet::ieee80211::IOriginatorQoSAckPolicy::getBlockAckTimeout (Packet * packet, const Ptr< const Ieee80211BlockAckReq > & blockAckReq) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
Referenced by inet::ieee80211::BlockAckReqBlockAckFs::prepareStep().
isAckNeeded()
virtual bool inet::ieee80211::IOriginatorQoSAckPolicy::isAckNeeded (const Ptr< const Ieee80211MgmtHeader > & header) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
isBlockAckPolicyEligibleFrame()
virtual bool inet::ieee80211::IOriginatorQoSAckPolicy::isBlockAckPolicyEligibleFrame (Packet * packet, const Ptr< const Ieee80211DataHeader > & header) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementPolicy::isAddbaReqNeeded().
isBlockAckReqNeeded()
virtual bool inet::ieee80211::IOriginatorQoSAckPolicy::isBlockAckReqNeeded (InProgressFrames * inProgressFrames, TxopProcedure * txopProcedure) const pure virtual
Implemented in inet::ieee80211::OriginatorQosAckPolicy.
Referenced by inet::ieee80211::TxOpFs::selectTxOpSequence().
The documentation for this class was generated from the following file:
IOriginatorQoSAckPolicy.h