INET Framework for OMNeT++/OMNEST: inet::RsbTimeoutMsg Class Reference
inet::RsbTimeoutMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:86 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
RsbTimeoutMsg (const char *name=nullptr, short kind=0)
RsbTimeoutMsg (const RsbTimeoutMsg &other)
virtual ~RsbTimeoutMsg ()
RsbTimeoutMsg & operator= (const RsbTimeoutMsg &other)
virtual RsbTimeoutMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getId () const
virtual void setId (int id)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const RsbTimeoutMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
int id = 0
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const RsbTimeoutMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:86 by opp_msgtool.
//
// FIXME missing documentation
//
message RsbTimeoutMsg extends SignallingMsg
{
    int id;
    command = MSG_RSB_TIMEOUT;
}
Constructor & Destructor Documentation
RsbTimeoutMsg() [1/2]
inet::RsbTimeoutMsg::RsbTimeoutMsg (const char * name = nullptr, short kind = 0)
RsbTimeoutMsg() [2/2]
inet::RsbTimeoutMsg::RsbTimeoutMsg (const RsbTimeoutMsg & other)
~RsbTimeoutMsg()
virtual inet::RsbTimeoutMsg::~RsbTimeoutMsg () virtual
Member Function Documentation
copy()
void inet::RsbTimeoutMsg::copy (const RsbTimeoutMsg & other) private
dup()
virtual RsbTimeoutMsg* inet::RsbTimeoutMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new RsbTimeoutMsg(*this);}
getId()
virtual int inet::RsbTimeoutMsg::getId () const virtual
Referenced by inet::RsvpTe::processRSB_TIMEOUT().
operator=()
RsbTimeoutMsg& inet::RsbTimeoutMsg::operator= (const RsbTimeoutMsg & other)
operator==()
bool inet::RsbTimeoutMsg::operator== (const RsbTimeoutMsg &) protected delete
parsimPack()
virtual void inet::RsbTimeoutMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::RsbTimeoutMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setId()
virtual void inet::RsbTimeoutMsg::setId (int id) virtual
Referenced by inet::RsvpTe::createEgressRSB(), and inet::RsvpTe::createRSB().
Member Data Documentation
id
int inet::RsbTimeoutMsg::id = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h