INET Framework for OMNeT++/OMNEST: inet::rtp::RtpCiSenderControl Class Reference
inet::rtp::RtpCiSenderControl Class Reference
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:74 by opp_msgtool.
#include <RtpInterfacePacket_m.h>
Public Member Functions
RtpCiSenderControl ()
RtpCiSenderControl (const RtpCiSenderControl &other)
virtual ~RtpCiSenderControl ()
RtpCiSenderControl & operator= (const RtpCiSenderControl &other)
virtual RtpCiSenderControl * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual RtpSenderControlMessageCommands getCommand () const
virtual void setCommand (RtpSenderControlMessageCommands command)
virtual float getCommandParameter1 () const
virtual void setCommandParameter1 (float commandParameter1)
virtual float getCommandParameter2 () const
virtual void setCommandParameter2 (float commandParameter2)
Public Member Functions inherited from inet::rtp::RtpSessionControlInfo
RtpSessionControlInfo ()
RtpSessionControlInfo (const RtpSessionControlInfo &other)
virtual ~RtpSessionControlInfo ()
RtpSessionControlInfo & operator= (const RtpSessionControlInfo &other)
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
Public Member Functions inherited from inet::rtp::RtpControlInfo
RtpControlInfo ()
RtpControlInfo (const RtpControlInfo &other)
virtual ~RtpControlInfo ()
RtpControlInfo & operator= (const RtpControlInfo &other)
virtual RtpIfpType getType () const
virtual void setType (RtpIfpType type)
Protected Member Functions
bool operator== (const RtpCiSenderControl &)=delete
Protected Member Functions inherited from inet::rtp::RtpSessionControlInfo
bool operator== (const RtpSessionControlInfo &)=delete
Protected Member Functions inherited from inet::rtp::RtpControlInfo
bool operator== (const RtpControlInfo &)=delete
Protected Attributes
RtpSenderControlMessageCommands command = static_cast<inet::rtp::RtpSenderControlMessageCommands>(-1)
float commandParameter1 = 0
float commandParameter2 = 0
Protected Attributes inherited from inet::rtp::RtpSessionControlInfo
uint32_t ssrc = 0
Protected Attributes inherited from inet::rtp::RtpControlInfo
RtpIfpType type = static_cast<inet::rtp::RtpIfpType>(-1)
Private Member Functions
void copy (const RtpCiSenderControl &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:74 by opp_msgtool.
// App to ~Rtp
class RtpCiSenderControl extends RtpSessionControlInfo
{
    type = RTP_IFP_SENDER_CONTROL;
    // from ~RtpSenderControlMessage:
    RtpSenderControlMessageCommands command;
    float commandParameter1;
    float commandParameter2;
}
Constructor & Destructor Documentation
RtpCiSenderControl() [1/2]
inet::rtp::RtpCiSenderControl::RtpCiSenderControl ()
RtpCiSenderControl() [2/2]
inet::rtp::RtpCiSenderControl::RtpCiSenderControl (const RtpCiSenderControl & other)
~RtpCiSenderControl()
virtual inet::rtp::RtpCiSenderControl::~RtpCiSenderControl () virtual
Member Function Documentation
copy()
void inet::rtp::RtpCiSenderControl::copy (const RtpCiSenderControl & other) private
dup()
virtual RtpCiSenderControl* inet::rtp::RtpCiSenderControl::dup () const inline override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
 {return new RtpCiSenderControl(*this);}
getCommand()
virtual RtpSenderControlMessageCommands inet::rtp::RtpCiSenderControl::getCommand () const virtual
Referenced by inet::rtp::Rtp::senderModuleControl().
getCommandParameter1()
virtual float inet::rtp::RtpCiSenderControl::getCommandParameter1 () const virtual
Referenced by inet::rtp::Rtp::senderModuleControl().
getCommandParameter2()
virtual float inet::rtp::RtpCiSenderControl::getCommandParameter2 () const virtual
Referenced by inet::rtp::Rtp::senderModuleControl().
operator=()
RtpCiSenderControl& inet::rtp::RtpCiSenderControl::operator= (const RtpCiSenderControl & other)
operator==()
bool inet::rtp::RtpCiSenderControl::operator== (const RtpCiSenderControl &) protected delete
parsimPack()
virtual void inet::rtp::RtpCiSenderControl::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpCiSenderControl::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimUnpacking().
setCommand()
virtual void inet::rtp::RtpCiSenderControl::setCommand (RtpSenderControlMessageCommands command) virtual
setCommandParameter1()
virtual void inet::rtp::RtpCiSenderControl::setCommandParameter1 (float commandParameter1) virtual
setCommandParameter2()
virtual void inet::rtp::RtpCiSenderControl::setCommandParameter2 (float commandParameter2) virtual
Member Data Documentation
command
RtpSenderControlMessageCommands inet::rtp::RtpCiSenderControl::command = static_cast<inet::rtp::RtpSenderControlMessageCommands>(-1) protected
commandParameter1
float inet::rtp::RtpCiSenderControl::commandParameter1 = 0 protected
commandParameter2
float inet::rtp::RtpCiSenderControl::commandParameter2 = 0 protected
The documentation for this class was generated from the following file:
RtpInterfacePacket_m.h