INET Framework for OMNeT++/OMNEST: inet::IIpv4RoutingTable Class Reference
inet::IIpv4RoutingTable Class Reference abstract
A C++ interface to abstract the functionality of IIpv4RoutingTable.
#include <IIpv4RoutingTable.h>
Public Member Functions
virtual ~IIpv4RoutingTable ()
virtual void printMulticastRoutingTable () const =0
For debugging.
virtual cModule * getHostModule ()=0
Returns the host or router this routing table lives in.
Interfaces
virtual NetworkInterface * getInterfaceByAddress (const Ipv4Address &address) const =0
Returns an interface given by its address.
virtual Ipv4Address getRouterId () const =0
Returns routerId.
virtual void setRouterId (Ipv4Address a)=0
Sets routerId.
virtual NetworkInterface * getInterfaceByAddress (const L3Address &address) const=0
Returns an interface given by its address.
Routing functions (query the route table)
virtual bool isLocalAddress (const Ipv4Address &dest) const =0
Checks if the address is a local one, i.e.
virtual bool isLocalBroadcastAddress (const Ipv4Address &dest) const =0
Checks if the address is a local network broadcast address, i.e.
virtual NetworkInterface * findInterfaceByLocalBroadcastAddress (const Ipv4Address &dest) const =0
Returns the interface entry having the specified address as its local broadcast address.
virtual Ipv4Route * findBestMatchingRoute (const Ipv4Address &dest) const =0
The routing function.
virtual NetworkInterface * getInterfaceForDestAddr (const Ipv4Address &dest) const =0
Convenience function based on findBestMatchingRoute().
virtual Ipv4Address getGatewayForDestAddr (const Ipv4Address &dest) const =0
Convenience function based on findBestMatchingRoute().
virtual bool isLocalAddress (const L3Address &dest) const=0
Checks if the address is a local one, i.e.
virtual IRoute * findBestMatchingRoute (const L3Address &dest) const=0
The routing function.
Multicast routing functions
virtual bool isLocalMulticastAddress (const Ipv4Address &dest) const =0
Checks if the address is in one of the local multicast group address list.
virtual const Ipv4MulticastRoute * findBestMatchingMulticastRoute (const Ipv4Address &origin, const Ipv4Address &group) const =0
Returns route for a multicast origin and group.
virtual bool isLocalMulticastAddress (const L3Address &dest) const=0
Checks if the address is in one of the local multicast group address list.
virtual IMulticastRoute * findBestMatchingMulticastRoute (const L3Address &origin, const L3Address &group) const=0
Returns route for a multicast origin and group.
Route table manipulation
virtual Ipv4Route * getRoute (int k) const override=0
Returns the kth route.
virtual Ipv4Route * getDefaultRoute () const override=0
Finds and returns the default route, or nullptr if it doesn't exist.
virtual void addRoute (Ipv4Route *entry)=0
Adds a route to the routing table.
virtual Ipv4Route * removeRoute (Ipv4Route *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (Ipv4Route *entry)=0
Deletes the given route from the routing table.
virtual Ipv4MulticastRoute * getMulticastRoute (int k) const override=0
Returns the kth multicast route.
virtual void addMulticastRoute (Ipv4MulticastRoute *entry)=0
Adds a multicast route to the routing table.
virtual Ipv4MulticastRoute * removeMulticastRoute (Ipv4MulticastRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (Ipv4MulticastRoute *entry)=0
Deletes the given multicast route from the routing table.
virtual void purge ()=0
Deletes invalid routes from the routing table.
virtual std::vector< Ipv4Address > gatherAddresses () const =0
Utility function: Returns a vector of all addresses of the node.
virtual void routeChanged (Ipv4Route *entry, int fieldCode)=0
To be called from route objects whenever a field changes.
virtual void multicastRouteChanged (Ipv4MulticastRoute *entry, int fieldCode)=0
To be called from multicast route objects whenever a field changes.
virtual void addRoute (IRoute *entry)=0
Adds a route to the routing table.
virtual IRoute * removeRoute (IRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (IRoute *entry)=0
Deletes the given route from the routing table.
virtual void addMulticastRoute (IMulticastRoute *entry)=0
Adds a multicast route to the routing table.
virtual IMulticastRoute * removeMulticastRoute (IMulticastRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (IMulticastRoute *entry)=0
Deletes the given multicast route from the routing table.
Public Member Functions inherited from inet::IRoutingTable
virtual ~IRoutingTable ()
virtual bool isForwardingEnabled () const =0
Forwarding on/off.
virtual bool isAdminDistEnabled () const =0
Administrative distance on/off.
virtual bool isMulticastForwardingEnabled () const =0
Multicast forwarding on/off.
virtual L3Address getRouterIdAsGeneric () const =0
Returns routerId.
virtual bool isLocalAddress (const L3Address &dest) const =0
Checks if the address is a local one, i.e.
virtual NetworkInterface * getInterfaceByAddress (const L3Address &address) const =0
Returns an interface given by its address.
virtual void printRoutingTable () const =0
Prints the routing table.
virtual IRoute * findBestMatchingRoute (const L3Address &dest) const =0
The routing function.
virtual NetworkInterface * getOutputInterfaceForDestination (const L3Address &dest) const =0
Convenience function based on findBestMatchingRoute().
virtual L3Address getNextHopForDestination (const L3Address &dest) const =0
Convenience function based on findBestMatchingRoute().
virtual bool isLocalMulticastAddress (const L3Address &dest) const =0
Checks if the address is in one of the local multicast group address list.
virtual IMulticastRoute * findBestMatchingMulticastRoute (const L3Address &origin, const L3Address &group) const =0
Returns route for a multicast origin and group.
virtual int getNumRoutes () const =0
Returns the total number of unicast routes.
virtual void addRoute (IRoute *entry)=0
Adds a route to the routing table.
virtual IRoute * removeRoute (IRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (IRoute *entry)=0
Deletes the given route from the routing table.
virtual int getNumMulticastRoutes () const =0
Returns the total number of multicast routes.
virtual void addMulticastRoute (IMulticastRoute *entry)=0
Adds a multicast route to the routing table.
virtual IMulticastRoute * removeMulticastRoute (IMulticastRoute *entry)=0
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (IMulticastRoute *entry)=0
Deletes the given multicast route from the routing table.
virtual IRoute * createRoute ()=0
Detailed Description
A C++ interface to abstract the functionality of IIpv4RoutingTable.
Referring to IIpv4RoutingTable via this interface makes it possible to transparently replace IIpv4RoutingTable with a different implementation, without any change to the base INET.
See also
IIpv4RoutingTable, Ipv4Route
Constructor & Destructor Documentation
~IIpv4RoutingTable()
virtual inet::IIpv4RoutingTable::~IIpv4RoutingTable () inline virtual
 {}
Member Function Documentation
addMulticastRoute() [1/2]
virtual void inet::IRoutingTable::addMulticastRoute
Adds a multicast route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
addMulticastRoute() [2/2]
virtual void inet::IIpv4RoutingTable::addMulticastRoute (Ipv4MulticastRoute * entry) pure virtual
Adds a multicast route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implemented in inet::Ipv4RoutingTable.
addRoute() [1/2]
virtual void inet::IIpv4RoutingTable::addRoute (Ipv4Route * entry) pure virtual
Adds a route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::Ipv4FlatNetworkConfigurator::addDefaultRoutes(), inet::ospfv2::Router::addExternalRouteInIPTable(), inet::bgp::BgpRouter::decisionProcess(), inet::Ipv4FlatNetworkConfigurator::fillRoutingTables(), inet::RoutingTableParser::parseRouting(), inet::ospfv2::Router::rebuildRoutingTable(), and inet::ospfv2::Router::updateExternalRoute().
addRoute() [2/2]
virtual void inet::IRoutingTable::addRoute
Adds a route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
deleteMulticastRoute() [1/2]
virtual bool inet::IRoutingTable::deleteMulticastRoute
Deletes the given multicast route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
deleteMulticastRoute() [2/2]
virtual bool inet::IIpv4RoutingTable::deleteMulticastRoute (Ipv4MulticastRoute * entry) pure virtual
Deletes the given multicast route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implemented in inet::Ipv4RoutingTable.
deleteRoute() [1/2]
virtual bool inet::IIpv4RoutingTable::deleteRoute (Ipv4Route * entry) pure virtual
Deletes the given route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::bgp::BgpRouter::deleteBGPRoutingEntry(), and inet::ospfv2::Router::rebuildRoutingTable().
deleteRoute() [2/2]
virtual bool inet::IRoutingTable::deleteRoute
Deletes the given route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
findBestMatchingMulticastRoute() [1/2]
virtual const Ipv4MulticastRoute* inet::IIpv4RoutingTable::findBestMatchingMulticastRoute (const Ipv4Address & origin, const Ipv4Address & group) const pure virtual
Returns route for a multicast origin and group.
Implemented in inet::Ipv4RoutingTable.
findBestMatchingMulticastRoute() [2/2]
virtual IMulticastRoute* inet::IRoutingTable::findBestMatchingMulticastRoute
Returns route for a multicast origin and group.
findBestMatchingRoute() [1/2]
virtual Ipv4Route* inet::IIpv4RoutingTable::findBestMatchingRoute (const Ipv4Address & dest) const pure virtual
The routing function.
Performs longest prefix match for the given destination address, and returns the resulting route. Returns nullptr if there is no matching route.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::visualizer::RoutingTableVisualizerBase::addRouteVisualizations().
findBestMatchingRoute() [2/2]
virtual IRoute* inet::IRoutingTable::findBestMatchingRoute
The routing function.
Performs longest prefix match for the given destination address, and returns the resulting route. Returns nullptr if there is no matching route.
findInterfaceByLocalBroadcastAddress()
virtual NetworkInterface* inet::IIpv4RoutingTable::findInterfaceByLocalBroadcastAddress (const Ipv4Address & dest) const pure virtual
Returns the interface entry having the specified address as its local broadcast address.
Implemented in inet::Ipv4RoutingTable.
gatherAddresses()
virtual std::vector<Ipv4Address> inet::IIpv4RoutingTable::gatherAddresses () const pure virtual
Utility function: Returns a vector of all addresses of the node.
Implemented in inet::Ipv4RoutingTable.
getDefaultRoute()
virtual Ipv4Route* inet::IIpv4RoutingTable::getDefaultRoute () const override pure virtual
Finds and returns the default route, or nullptr if it doesn't exist.
Implements inet::IRoutingTable.
Implemented in inet::Ipv4RoutingTable.
getGatewayForDestAddr()
virtual Ipv4Address inet::IIpv4RoutingTable::getGatewayForDestAddr (const Ipv4Address & dest) const pure virtual
Convenience function based on findBestMatchingRoute().
Returns the gateway for the destination address. Returns the unspecified address if the destination is not in routing table or the gateway field is not filled in in the route.
Implemented in inet::Ipv4RoutingTable.
getHostModule()
virtual cModule* inet::IIpv4RoutingTable::getHostModule () pure virtual
Returns the host or router this routing table lives in.
Implemented in inet::Ipv4RoutingTable.
getInterfaceByAddress() [1/2]
virtual NetworkInterface* inet::IIpv4RoutingTable::getInterfaceByAddress (const Ipv4Address & address) const pure virtual
Returns an interface given by its address.
Returns nullptr if not found.
Implemented in inet::Ipv4RoutingTable.
getInterfaceByAddress() [2/2]
virtual NetworkInterface* inet::IRoutingTable::getInterfaceByAddress
Returns an interface given by its address.
Returns nullptr if not found.
getInterfaceForDestAddr()
virtual NetworkInterface* inet::IIpv4RoutingTable::getInterfaceForDestAddr (const Ipv4Address & dest) const pure virtual
Convenience function based on findBestMatchingRoute().
Returns the output interface for the packets with dest as destination address, or nullptr if the destination is not in routing table.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::bgp::BgpRouter::createEbgpSession(), inet::bgp::BgpRouter::findNextSession(), inet::bgp::BgpRouter::isExternalAddress(), inet::bgp::BgpRouter::openTCPConnectionToPeer(), and inet::rtp::Rtp::resolveMTU().
getMulticastRoute()
virtual Ipv4MulticastRoute* inet::IIpv4RoutingTable::getMulticastRoute (int k) const override pure virtual
Returns the kth multicast route.
Implements inet::IRoutingTable.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::Ipv4NetworkConfigurator::dumpConfig().
getRoute()
virtual Ipv4Route* inet::IIpv4RoutingTable::getRoute (int k) const override pure virtual
Returns the kth route.
Implements inet::IRoutingTable.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::ospfv2::Router::addExternalRouteInIPTable(), inet::bgp::BgpRouter::addToAdvertiseList(), inet::bgp::BgpRouter::decisionProcess(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::ospfv2::Router::getDefaultRoute(), inet::ospfv3::Ospfv3Process::isInRoutingTable(), inet::bgp::BgpRouter::isInRoutingTable(), inet::bgp::BgpRouter::isReachable(), inet::bgp::BgpRouter::ospfExist(), inet::ospfv2::Router::rebuildRoutingTable(), and inet::ospfv2::Router::updateExternalRoute().
getRouterId()
virtual Ipv4Address inet::IIpv4RoutingTable::getRouterId () const pure virtual
Returns routerId.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::visualizer::RoutingTableVisualizerBase::addRouteVisualization(), inet::bgp::BgpRouter::createEbgpSession(), inet::bgp::BgpRouter::createIbgpSession(), inet::bgp::BgpRouter::getRouterId(), inet::visualizer::RoutingTableVisualizerBase::getRouteVisualization(), inet::RsvpClassifier::initialize(), inet::LinkStateRouting::initialize(), inet::Ted::initializeTED(), inet::visualizer::RoutingTableVisualizerBase::removeRouteVisualization(), and inet::L3AddressResolver::routerIdOf().
isLocalAddress() [1/2]
virtual bool inet::IIpv4RoutingTable::isLocalAddress (const Ipv4Address & dest) const pure virtual
Checks if the address is a local one, i.e.
one of the host's.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::visualizer::RoutingTableVisualizerBase::addRouteVisualizations().
isLocalAddress() [2/2]
virtual bool inet::IRoutingTable::isLocalAddress
Checks if the address is a local one, i.e.
one of the host's.
isLocalBroadcastAddress()
virtual bool inet::IIpv4RoutingTable::isLocalBroadcastAddress (const Ipv4Address & dest) const pure virtual
Checks if the address is a local network broadcast address, i.e.
one of the broadcast addresses derived from the interface addresses and netmasks.
Implemented in inet::Ipv4RoutingTable.
isLocalMulticastAddress() [1/2]
virtual bool inet::IIpv4RoutingTable::isLocalMulticastAddress (const Ipv4Address & dest) const pure virtual
Checks if the address is in one of the local multicast group address list.
Implemented in inet::Ipv4RoutingTable.
isLocalMulticastAddress() [2/2]
virtual bool inet::IRoutingTable::isLocalMulticastAddress
Checks if the address is in one of the local multicast group address list.
multicastRouteChanged()
virtual void inet::IIpv4RoutingTable::multicastRouteChanged (Ipv4MulticastRoute * entry, int fieldCode) pure virtual
To be called from multicast route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::Ipv4MulticastRoute::changed().
printMulticastRoutingTable()
virtual void inet::IIpv4RoutingTable::printMulticastRoutingTable () const pure virtual
For debugging.
Implemented in inet::Ipv4RoutingTable.
purge()
virtual void inet::IIpv4RoutingTable::purge () pure virtual
Deletes invalid routes from the routing table.
Invalid routes are those where the isValid() method returns false.
Implemented in inet::Ipv4RoutingTable.
removeMulticastRoute() [1/2]
virtual IMulticastRoute* inet::IRoutingTable::removeMulticastRoute
Removes the given route from the routing table, and returns it.
nullptr is returned of the route was not in the routing table.
removeMulticastRoute() [2/2]
virtual Ipv4MulticastRoute* inet::IIpv4RoutingTable::removeMulticastRoute (Ipv4MulticastRoute * entry) pure virtual
Removes the given route from the routing table, and returns it.
nullptr is returned of the route was not in the routing table.
Implemented in inet::Ipv4RoutingTable.
removeRoute() [1/2]
virtual Ipv4Route* inet::IIpv4RoutingTable::removeRoute (Ipv4Route * entry) pure virtual
Removes the given route from the routing table, and returns it.
nullptr is returned of the route was not in the routing table.
Implemented in inet::Ipv4RoutingTable.
removeRoute() [2/2]
virtual IRoute* inet::IRoutingTable::removeRoute
Removes the given route from the routing table, and returns it.
nullptr is returned if the route was not in the routing table.
routeChanged()
virtual void inet::IIpv4RoutingTable::routeChanged (Ipv4Route * entry, int fieldCode) pure virtual
To be called from route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
Implemented in inet::Ipv4RoutingTable.
Referenced by inet::Ipv4Route::changed().
setRouterId()
virtual void inet::IIpv4RoutingTable::setRouterId (Ipv4Address a) pure virtual
Sets routerId.
Implemented in inet::Ipv4RoutingTable.
The documentation for this class was generated from the following file:
IIpv4RoutingTable.h