INET Framework for OMNeT++/OMNEST: inet::physicallayer::IDecoder Class Reference
inet::physicallayer::IDecoder Class Reference abstract
#include <IDecoder.h>
Public Member Functions
virtual const IReceptionPacketModel * decode (const IReceptionBitModel *bitModel) const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
decode()
virtual const IReceptionPacketModel* inet::physicallayer::IDecoder::decode (const IReceptionBitModel * bitModel) const pure virtual
Implemented in inet::physicallayer::Ieee80211OfdmDecoder, inet::physicallayer::Ieee80211OfdmDecoderModule, and inet::physicallayer::ApskDecoder.
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldPacketModel(), inet::physicallayer::ApskLayeredReceiver::createPacketModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldPacketModel().
The documentation for this class was generated from the following file:
IDecoder.h