INET Framework for OMNeT++/OMNEST: inet::Z3GateScheduleConfigurator Class Reference
inet::Z3GateScheduleConfigurator Class Reference
#include <Z3GateScheduleConfigurator.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual Output * computeGateScheduling (const Input &input) const override
virtual void addAssert (const expr &expr) const
virtual std::shared_ptr< expr > getVariable (std::string variableName) const
virtual std::string getFullPath (cObject *object) const
virtual int getPacketCount (const Input::Flow *flow) const
virtual std::shared_ptr< expr > getGateCycleDurationVariable () const
virtual std::shared_ptr< expr > getInterframeGapVariable (const Input::Port *port) const
virtual std::shared_ptr< expr > getApplicationStartTimeVariable (const Input::Application *application) const
virtual std::shared_ptr< expr > getApplicationPacketIntervalVariable (const Input::Application *application) const
virtual std::shared_ptr< expr > getPropagationTimeVariable (const Input::Port *port) const
virtual std::shared_ptr< expr > getTransmissionDurationVariable (const Input::Flow *flow, const Input::Port *port) const
virtual std::shared_ptr< expr > getTransmissionStartTimeVariable (const Input::Flow *flow, int packetIndex, const Input::Port *port, int gateIndex) const
virtual std::shared_ptr< expr > getTransmissionEndTimeVariable (const Input::Flow *flow, int packetIndex, const Input::Port *port, int gateIndex) const
virtual std::shared_ptr< expr > getReceptionStartTimeVariable (const Input::Flow *flow, int packetIndex, const Input::Port *port, int gateIndex) const
virtual std::shared_ptr< expr > getReceptionEndTimeVariable (const Input::Flow *flow, int packetIndex, const Input::Port *port, int gateIndex) const
virtual std::shared_ptr< expr > getMaxEndToEndDelayVariable (const Input::Flow *flow) const
virtual std::shared_ptr< expr > getMaxJitterVariable (const Input::Flow *flow) const
virtual std::shared_ptr< expr > getEndToEndDelayVariable (const Input::Flow *flow, int packetIndex) const
virtual std::shared_ptr< expr > getTotalEndToEndDelayVariable () const
virtual std::shared_ptr< expr > getAverageEndToEndDelayVariable (const Input::Flow *flow) const
virtual std::vector< std::shared_ptr< expr > > getTimeVariables (const Input::Port *port, int gateIndex, std::string suffix) const
virtual std::vector< std::shared_ptr< expr > > getTransmissionStartTimeVariables (const Input::Port *port, int gateIndex=-1) const
virtual std::vector< std::shared_ptr< expr > > getTransmissionEndTimeVariables (const Input::Port *port, int gateIndex=-1) const
virtual std::vector< std::shared_ptr< expr > > getReceptionStartTimeVariables (const Input::Port *port, int gateIndex=-1) const
virtual std::vector< std::shared_ptr< expr > > getReceptionEndTimeVariables (const Input::Port *port, int gateIndex=-1) const
virtual double getVariableValue (const model &model, const std::shared_ptr< expr > expr) const
Protected Member Functions inherited from inet::GateScheduleConfiguratorBase
virtual void handleParameterChange (const char *name) override
virtual void handleMessage (cMessage *msg) override
virtual void clearConfiguration ()
virtual void computeConfiguration ()
virtual Input * createGateSchedulingInput () const
virtual void addDevices (Input &input) const
virtual void addSwitches (Input &input) const
virtual void addPorts (Input &input) const
virtual void addFlows (Input &input) const
virtual void configureGateScheduling ()
virtual void configureGateScheduling (cModule *networkNode, cModule *gate, Interface *interface)
virtual void configureApplicationOffsets ()
Protected Member Functions inherited from inet::NetworkConfiguratorBase
virtual ~NetworkConfiguratorBase ()
virtual int numInitStages () const override
virtual void extractTopology (Topology &topology)
Extracts network topology by walking through the module hierarchy.
virtual std::vector< Node * > computeShortestNodePath (Node *source, Node *destination) const
virtual std::vector< Link * > computeShortestLinkPath (Node *source, Node *destination) const
virtual bool isBridgeNode (Node *node) const
virtual Link * findLinkIn (const Node *node, const char *neighbor) const
virtual Link * findLinkOut (const Node *node, const char *neighbor) const
virtual Link * findLinkOut (const Node *node, const Node *neighbor) const
virtual Link * findLinkOut (const Interface *interface) const
virtual Topology::Link * findLinkOut (const Node *node, int gateId) const
virtual Interface * findInterface (const Node *node, NetworkInterface *networkInterface) const
Protected Attributes
bool labelAsserts = false
bool optimizeSchedule = true
context * ctx = nullptr
solver * solver = nullptr
optimize * optimizer = nullptr
std::map< std::string, std::shared_ptr< expr > > variables
Protected Attributes inherited from inet::GateScheduleConfiguratorBase
simtime_t gateCycleDuration
cValueArray * configuration = nullptr
Input * gateSchedulingInput = nullptr
Output * gateSchedulingOutput = nullptr
Protected Attributes inherited from inet::NetworkConfiguratorBase
Topology * topology = nullptr
Additional Inherited Members
Public Member Functions inherited from inet::GateScheduleConfiguratorBase
virtual ~GateScheduleConfiguratorBase ()
Member Function Documentation
addAssert()
void inet::Z3GateScheduleConfigurator::addAssert (const expr & expr) const protected virtual
 {
     static int assertionCount = 0;
     if (optimizeSchedule) {
         if (labelAsserts)
             optimizer->add(expr, (std::string("a") + std::to_string(assertionCount++)).c_str());
         else
             optimizer->add(expr);
     }
     else {
         if (labelAsserts)
             solver->add(expr, (std::string("a") + std::to_string(assertionCount++)).c_str());
         else
             solver->add(expr);
     }
 }
Referenced by computeGateScheduling().
computeGateScheduling()
Z3GateScheduleConfigurator::Output * inet::Z3GateScheduleConfigurator::computeGateScheduling (const Input & input) const override protected virtual
Implements inet::GateScheduleConfiguratorBase.
 {
     config cfg;
     cfg.set("model", "true");
     ctx = new context(cfg);
     solver = !optimizeSchedule ? new z3::solver(*ctx) : nullptr;
     optimizer = optimizeSchedule ? new optimize(*ctx) : nullptr;
     auto gateCycleDurationVariable = getGateCycleDurationVariable();
     addAssert(gateCycleDurationVariable == ctx->real_val(gateCycleDuration.str().c_str()));
     auto totalEndToEndDelayVariable = getTotalEndToEndDelayVariable();
     auto totalEndToEndDelayValue = ctx->real_val(0);
     // 1. add application start time constraints
     for (auto application : input.applications) {
         auto applicationStartTimeVariable = getApplicationStartTimeVariable(application);
         addAssert(expr(ctx->real_val(0)) <= applicationStartTimeVariable);
         addAssert(applicationStartTimeVariable < gateCycleDurationVariable);
     }
     // 2. add transmission start/end time, reception start/end time, transmission duration, propagation time constraints
     for (auto flow : input.flows) {
         for (int packetIndex = 0; packetIndex < getPacketCount(flow); packetIndex++) {
             for (auto pathFragment : flow->pathFragments) {
                 for (int nodeIndex = 0; nodeIndex < pathFragment->networkNodes.size() - 1; nodeIndex++) {
                     auto transmissionPort = pathFragment->outputPorts[nodeIndex];
                     auto transmissionDurationVariable = getTransmissionDurationVariable(flow, transmissionPort);
                     simtime_t transmissionDuration = s(flow->startApplication->packetLength / transmissionPort->datarate).get();
                     addAssert(transmissionDurationVariable == ctx->real_val(transmissionDuration.str().c_str()));
                     auto transmissionStartTimeVariable = getTransmissionStartTimeVariable(flow, packetIndex, transmissionPort, flow->gateIndex);
                     auto transmissionEndTimeVariable = getTransmissionEndTimeVariable(flow, packetIndex, transmissionPort, flow->gateIndex);
                     addAssert(transmissionStartTimeVariable + transmissionDurationVariable == transmissionEndTimeVariable);
                     addAssert(expr(ctx->real_val(0)) <= transmissionStartTimeVariable);
                     addAssert(transmissionStartTimeVariable < gateCycleDurationVariable);
                     auto receptionPort = pathFragment->inputPorts[nodeIndex];
                     auto receptionStartTimeVariable = getReceptionStartTimeVariable(flow, packetIndex, receptionPort, flow->gateIndex);
                     auto receptionEndTimeVariable = getReceptionEndTimeVariable(flow, packetIndex, receptionPort, flow->gateIndex);
                     addAssert(receptionStartTimeVariable + transmissionDurationVariable == receptionEndTimeVariable);
                     auto propagationTimeVariable = getPropagationTimeVariable(transmissionPort);
                     addAssert(propagationTimeVariable == ctx->real_val(transmissionPort->propagationTime.str().c_str()));
                     addAssert(transmissionStartTimeVariable + propagationTimeVariable == receptionStartTimeVariable);
                 }
             }
         }
     }
     // 3. add chained reception end time, transmission start time and end-to-end delay constraints
     for (auto flow : input.flows) {
         auto maxEndToEndDelayVariable = flow->startApplication->maxLatency > 0 ? getMaxEndToEndDelayVariable(flow) : nullptr;
         auto applicationStartTimeVariable = getApplicationStartTimeVariable(flow->startApplication);
         auto packetIntervalVariable = getApplicationPacketIntervalVariable(flow->startApplication);
         auto packetInterval = flow->startApplication->packetInterval;
         addAssert(packetIntervalVariable == ctx->real_val(packetInterval.str().c_str()));
         for (int packetIndex = 0; packetIndex < getPacketCount(flow); packetIndex++) {
             std::shared_ptr<expr> firstTransmissionStartTimeVariable;
             std::shared_ptr<expr> previousReceptionEndTimeVariable;
             for (auto pathFragment : flow->pathFragments) {
                 for (int nodeIndex = 0; nodeIndex < pathFragment->networkNodes.size() - 1; nodeIndex++) {
                     auto transmissionPort = pathFragment->outputPorts[nodeIndex];
                     auto transmissionStartTimeVariable = getTransmissionStartTimeVariable(flow, packetIndex, transmissionPort, flow->gateIndex);
                     if (firstTransmissionStartTimeVariable == nullptr)
                         firstTransmissionStartTimeVariable = transmissionStartTimeVariable;
                     auto receptionPort = pathFragment->inputPorts[nodeIndex];
                     auto receptionEndTimeVariable = getReceptionEndTimeVariable(flow, packetIndex, receptionPort, flow->gateIndex);
                     if (nodeIndex == 0)
                         addAssert(applicationStartTimeVariable + packetIntervalVariable * ctx->real_val(packetIndex) == transmissionStartTimeVariable);
                     else if (previousReceptionEndTimeVariable)
                         addAssert(transmissionStartTimeVariable >= previousReceptionEndTimeVariable);
                     previousReceptionEndTimeVariable = receptionEndTimeVariable;
                 }
             }
             auto endToEndDelayVariable = getEndToEndDelayVariable(flow, packetIndex);
             addAssert(endToEndDelayVariable == previousReceptionEndTimeVariable - firstTransmissionStartTimeVariable);
             totalEndToEndDelayValue = totalEndToEndDelayValue + endToEndDelayVariable;
             if (maxEndToEndDelayVariable)
                 addAssert(endToEndDelayVariable <= maxEndToEndDelayVariable);
         }
         if (maxEndToEndDelayVariable)
             addAssert(maxEndToEndDelayVariable == ctx->real_val(flow->startApplication->maxLatency.str().c_str()));
     }
     addAssert(totalEndToEndDelayVariable == totalEndToEndDelayValue);
     // 4. add jitter constraints
     for (auto flow : input.flows) {
         int count = getPacketCount(flow);
         auto maxJitterVariable = getMaxJitterVariable(flow);
         auto averageEndToEndDelayVariable = getAverageEndToEndDelayVariable(flow);
         auto averageEndToEndDelayValue = ctx->real_val(0);
         for (int packetIndex = 0; packetIndex < count; packetIndex++) {
             auto endToEndDelayVariable = getEndToEndDelayVariable(flow, packetIndex);
             averageEndToEndDelayValue = averageEndToEndDelayValue + endToEndDelayVariable;
         }
         addAssert(averageEndToEndDelayVariable == averageEndToEndDelayValue / ctx->real_val(count));
         for (int packetIndex = 0; packetIndex < count; packetIndex++) {
             auto endToEndDelayVariable = getEndToEndDelayVariable(flow, packetIndex);
             addAssert(averageEndToEndDelayVariable - endToEndDelayVariable <= maxJitterVariable);
         }
         addAssert(maxJitterVariable == ctx->real_val(0));
     }
     // 5. add one transmission per port at a time constraints
     for (auto port : input.ports) {
         simtime_t interframeGap = s(b(96) / port->datarate).get();
         auto interframeGapVariable = getInterframeGapVariable(port);
         addAssert(interframeGapVariable == ctx->real_val(interframeGap.str().c_str()));
         auto transmissionStartTimeVariables = getTransmissionStartTimeVariables(port);
         auto transmissionEndTimeVariables = getTransmissionEndTimeVariables(port);
         for (int i = 0; i < transmissionStartTimeVariables.size(); i++) {
             auto transmissionStartTimeVariableI = transmissionStartTimeVariables[i];
             auto transmissionEndTimeVariableI = transmissionEndTimeVariables[i];
             for (int j = i + 1; j < transmissionStartTimeVariables.size(); j++) {
                 auto transmissionStartTimeVariableJ = transmissionStartTimeVariables[j];
                 auto transmissionEndTimeVariableJ = transmissionEndTimeVariables[j];
                 addAssert(transmissionEndTimeVariableI + interframeGapVariable <= transmissionStartTimeVariableJ ||
                           transmissionEndTimeVariableJ + interframeGapVariable <= transmissionStartTimeVariableI);
             }
         }
     }
     // 6. add queueing constraints to prevent reordering packets
     for (auto port : input.ports) {
         for (int gateIndex = 0; gateIndex < port->numGates; gateIndex++) {
             auto transmissionStartTimeVariables = getTransmissionStartTimeVariables(port, gateIndex);
             auto transmissionEndTimeVariables = getTransmissionEndTimeVariables(port, gateIndex);
             auto receptionStartTimeVariables = getReceptionStartTimeVariables(port, gateIndex);
             auto receptionEndTimeVariables = getReceptionEndTimeVariables(port, gateIndex);
             for (int i = 0; i < transmissionStartTimeVariables.size(); i++) {
                 auto transmissionEndTimeVariableI = transmissionEndTimeVariables[i];
                 auto receptionEndTimeVariableI = receptionEndTimeVariables[i];
                 for (int j = i + 1; j < transmissionStartTimeVariables.size(); j++) {
                     auto transmissionEndTimeVariableJ = transmissionEndTimeVariables[j];
                     auto receptionEndTimeVariableJ = receptionEndTimeVariables[j];
                     addAssert(receptionEndTimeVariableI < receptionEndTimeVariableJ == transmissionEndTimeVariableI < transmissionEndTimeVariableJ);
                 }
             }
         }
     }
     // 7. add traffic class constraints to prevent lower priority to transmit first
     for (auto port : input.ports) {
         for (int gateIndexI = 0; gateIndexI < port->numGates; gateIndexI++) {
             auto transmissionStartTimeVariablesI = getTransmissionStartTimeVariables(port, gateIndexI);
             auto receptionEndTimeVariablesI = getReceptionEndTimeVariables(port, gateIndexI);
             for (int gateIndexJ = gateIndexI + 1; gateIndexJ < port->numGates; gateIndexJ++) {
                 auto transmissionStartTimeVariablesJ = getTransmissionStartTimeVariables(port, gateIndexJ);
                 for (int i = 0; i < receptionEndTimeVariablesI.size(); i++) {
                     auto transmissionStartTimeVariableI = transmissionStartTimeVariablesI[i];
                     auto receptionEndTimeVariableI = receptionEndTimeVariablesI[i];
                     for (int j = 0; j < transmissionStartTimeVariablesJ.size(); j++) {
                         auto transmissionStartTimeVariableJ = transmissionStartTimeVariablesJ[j];
                         addAssert(transmissionStartTimeVariableJ <= receptionEndTimeVariableI || transmissionStartTimeVariableJ >= transmissionStartTimeVariableI);
                     }
                 }
             }
         }
     }
     // 8. add minimization goal if requested
     if (optimizeSchedule)
         // TODO add weights for the end-to-end delay and jitter of individual flows
         optimizer->minimize(*totalEndToEndDelayVariable.get());
     // print what we have
     EV_INFO << "Goal:" << std::endl;
     if (optimizeSchedule)
         EV_INFO << *optimizer << std::endl;
     else
         EV_INFO << *solver << std::endl;
     // solve
     if ((optimizeSchedule ? optimizer->check() : solver->check()) == sat) {
         model model = optimizeSchedule ? optimizer->get_model() : solver->get_model();
         EV_INFO << "Solution:" << std::endl << model << std::endl;
         auto output = new Output();
         // 1. fill application start times
         for (auto application : input.applications)
             output->applicationStartTimes[application] = getVariableValue(model, getApplicationStartTimeVariable(application));
         // 2. print some detailed results
         for (auto flow : input.flows) {
             for (int packetIndex = 0; packetIndex < getPacketCount(flow); packetIndex++) {
                 for (auto pathFragment : flow->pathFragments) {
                     for (int nodeIndex = 0; nodeIndex < pathFragment->networkNodes.size() - 1; nodeIndex++) {
                         auto transmissionPort = pathFragment->outputPorts[nodeIndex];
                         double transmissionStartTime = getVariableValue(model, getTransmissionStartTimeVariable(flow, packetIndex, transmissionPort, flow->gateIndex));
                         double transmissionEndTime = getVariableValue(model, getTransmissionEndTimeVariable(flow, packetIndex, transmissionPort, flow->gateIndex));
                         EV_DEBUG << "Transmission: " << flow->name << ".packet" << std::to_string(packetIndex) << transmissionPort->module->getFullPath() << ", start = " << transmissionStartTime << ", end = " << transmissionEndTime << std::endl;
                     }
                 }
                 EV_DEBUG << "End-to-end delay: " << getVariableValue(model, getEndToEndDelayVariable(flow, packetIndex)) << std::endl;
             }
         }
         // 3. fill gate schedules
         for (auto port : input.ports) {
             auto& schedules = output->gateSchedules[port];
             for (int gateIndex = 0; gateIndex < port->numGates; gateIndex++) {
                 EV_DEBUG << "Computing schedule, port = " << port->module->getFullPath() << ", gateIndex = " << gateIndex << std::endl;
                 auto schedule = new Output::Schedule();
                 schedule->port = port;
                 schedule->gateIndex = gateIndex;
                 schedule->cycleStart = 0;
                 schedule->cycleDuration = gateCycleDuration;
                 auto transmissionStartTimeVariables = getTransmissionStartTimeVariables(port, gateIndex);
                 auto transmissionEndTimeVariables = getTransmissionEndTimeVariables(port, gateIndex);
                 for (int i = 0; i < transmissionStartTimeVariables.size(); i++) {
                     simtime_t slotStart = getVariableValue(model, transmissionStartTimeVariables[i]);
                     simtime_t slotEnd = getVariableValue(model, transmissionEndTimeVariables[i]);
                     simtime_t slotDuration = slotEnd - slotStart;
                     EV_DEBUG << "Adding slot, start time = " << slotStart << ", end time = " << slotEnd << std::endl;
                     if (slotStart < gateCycleDuration && slotEnd > gateCycleDuration) {
                         Output::Slot scheduleSlot;
                         scheduleSlot.start = slotStart;
                         scheduleSlot.duration = gateCycleDuration - slotStart;
                         schedule->slots.push_back(scheduleSlot);
                         scheduleSlot.start = 0;
                         scheduleSlot.duration = slotDuration - scheduleSlot.duration;
                         schedule->slots.push_back(scheduleSlot);
                     }
                     else {
                         Output::Slot scheduleSlot;
                         scheduleSlot.start = SimTime::fromRaw(slotStart.raw() % gateCycleDuration.raw());
                         scheduleSlot.duration = slotDuration;
                         schedule->slots.push_back(scheduleSlot);
                     }
                 }
                 auto& slots = schedule->slots;
                 std::sort(slots.begin(), slots.end(), [] (const Output::Slot& slot1, const Output::Slot& slot2) {
                     return slot1.start < slot2.start;
                 });
                 for (auto slot : slots)
                     EV_DEBUG << "Added slot, start time = " << slot.start << ", duration = " << slot.duration << std::endl;
                 schedules.push_back(schedule);
             }
         }
         delete solver;
         return output;
     }
     else {
         EV_WARN << "No solution found, unsatisfiable core:" << std::endl << (optimizeSchedule ? solver->unsat_core() : optimizer->unsat_core()) << std::endl;
         throw cRuntimeError("The specified constraints might not be satisfiable.");
     }
 }
getApplicationPacketIntervalVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getApplicationPacketIntervalVariable (const Input::Application * application) const inline protected virtual
{
         std::string variableName = getFullPath(application->module) + ".packetInterval";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getApplicationStartTimeVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getApplicationStartTimeVariable (const Input::Application * application) const inline protected virtual
{
         std::string variableName = getFullPath(application->module) + ".startTime";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getAverageEndToEndDelayVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getAverageEndToEndDelayVariable (const Input::Flow * flow) const inline protected virtual
{
         std::string variableName = flow->name + ".averageEndToEndDelay";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getEndToEndDelayVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getEndToEndDelayVariable (const Input::Flow * flow, int packetIndex) const inline protected virtual
{
         std::string variableName = flow->name + ".packet" + std::to_string(packetIndex) + ".endToEndDelay";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getFullPath()
virtual std::string inet::Z3GateScheduleConfigurator::getFullPath (cObject * object) const inline protected virtual
{
         std::string fullPath = object->getFullPath();
         return fullPath.substr(fullPath.find('.') + 1);
     }
getGateCycleDurationVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getGateCycleDurationVariable () const inline protected virtual
{
         return getVariable("gateCycleDuration");
     }
Referenced by computeGateScheduling().
getInterframeGapVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getInterframeGapVariable (const Input::Port * port) const inline protected virtual
{
         std::string variableName = getFullPath(port->module) + ".interframeGap";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getMaxEndToEndDelayVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getMaxEndToEndDelayVariable (const Input::Flow * flow) const inline protected virtual
{
         std::string variableName = flow->name + ".maxEndToEndDelay";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getMaxJitterVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getMaxJitterVariable (const Input::Flow * flow) const inline protected virtual
{
         std::string variableName = flow->name + ".maxJitter";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getPacketCount()
virtual int inet::Z3GateScheduleConfigurator::getPacketCount (const Input::Flow * flow) const inline protected virtual
{
         auto packetInterval = flow->startApplication->packetInterval;
         int count = gateCycleDuration / packetInterval;
         if (gateCycleDuration != count * packetInterval)
             throw cRuntimeError("Gate cycle duration must be a multiple of the application packet interval");
         return count;
     }
Referenced by computeGateScheduling().
getPropagationTimeVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getPropagationTimeVariable (const Input::Port * port) const inline protected virtual
{
         std::string variableName = getFullPath(port->module) + ".propagationTime";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getReceptionEndTimeVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getReceptionEndTimeVariable (const Input::Flow * flow, int packetIndex, const Input::Port * port, int gateIndex) const inline protected virtual
{
         std::string variableName = flow->name + ".packet" + std::to_string(packetIndex) + "." + getFullPath(port->module) + ".gate" + std::to_string(gateIndex) + ".receptionEndTime";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getReceptionEndTimeVariables()
virtual std::vector<std::shared_ptr<expr> > inet::Z3GateScheduleConfigurator::getReceptionEndTimeVariables (const Input::Port * port, int gateIndex = -1) const inline protected virtual
{
         return getTimeVariables(port, gateIndex, "transmissionEndTime");
     }
Referenced by computeGateScheduling().
getReceptionStartTimeVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getReceptionStartTimeVariable (const Input::Flow * flow, int packetIndex, const Input::Port * port, int gateIndex) const inline protected virtual
{
         std::string variableName = flow->name + ".packet" + std::to_string(packetIndex) + "." + getFullPath(port->module) + ".gate" + std::to_string(gateIndex) + ".receptionStartTime";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getReceptionStartTimeVariables()
virtual std::vector<std::shared_ptr<expr> > inet::Z3GateScheduleConfigurator::getReceptionStartTimeVariables (const Input::Port * port, int gateIndex = -1) const inline protected virtual
{
         return getTimeVariables(port, gateIndex, "transmissionStartTime");
     }
Referenced by computeGateScheduling().
getTimeVariables()
virtual std::vector<std::shared_ptr<expr> > inet::Z3GateScheduleConfigurator::getTimeVariables (const Input::Port * port, int gateIndex, std::string suffix) const inline protected virtual
{
         std::vector<std::shared_ptr<expr>> result;
         for (auto it : variables) {
             auto variableName = it.first;
             if (variableName.find(suffix) != std::string::npos &&
                 variableName.find(getFullPath(port->module)) != std::string::npos &&
                 (gateIndex == -1 || variableName.find(std::string("gate") + std::to_string(gateIndex)) != std::string::npos))
             {
                 result.push_back(it.second);
             }
         }
         std::sort(result.begin(), result.end(), [&] (const auto& expr1, const auto& expr2) { return expr1->to_string() < expr2->to_string(); });
         return result;
     }
getTotalEndToEndDelayVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getTotalEndToEndDelayVariable () const inline protected virtual
{
         return getVariable("totalEndToEndDelay");
     }
Referenced by computeGateScheduling().
getTransmissionDurationVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getTransmissionDurationVariable (const Input::Flow * flow, const Input::Port * port) const inline protected virtual
{
         std::string variableName = flow->name + "." + getFullPath(port->module) + ".transmissionDuration";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getTransmissionEndTimeVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getTransmissionEndTimeVariable (const Input::Flow * flow, int packetIndex, const Input::Port * port, int gateIndex) const inline protected virtual
{
         std::string variableName = flow->name + ".packet" + std::to_string(packetIndex) + "." + getFullPath(port->module) + ".gate" + std::to_string(gateIndex) + ".transmissionEndTime";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getTransmissionEndTimeVariables()
virtual std::vector<std::shared_ptr<expr> > inet::Z3GateScheduleConfigurator::getTransmissionEndTimeVariables (const Input::Port * port, int gateIndex = -1) const inline protected virtual
{
         return getTimeVariables(port, gateIndex, "transmissionEndTime");
     }
Referenced by computeGateScheduling().
getTransmissionStartTimeVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getTransmissionStartTimeVariable (const Input::Flow * flow, int packetIndex, const Input::Port * port, int gateIndex) const inline protected virtual
{
         std::string variableName = flow->name + ".packet" + std::to_string(packetIndex) + "." + getFullPath(port->module) + ".gate" + std::to_string(gateIndex) + ".transmissionStartTime";
         return getVariable(variableName);
     }
Referenced by computeGateScheduling().
getTransmissionStartTimeVariables()
virtual std::vector<std::shared_ptr<expr> > inet::Z3GateScheduleConfigurator::getTransmissionStartTimeVariables (const Input::Port * port, int gateIndex = -1) const inline protected virtual
{
         return getTimeVariables(port, gateIndex, "transmissionStartTime");
     }
Referenced by computeGateScheduling().
getVariable()
virtual std::shared_ptr<expr> inet::Z3GateScheduleConfigurator::getVariable (std::string variableName) const inline protected virtual
{
         auto it = variables.find(variableName);
         if (it != variables.end())
             return it->second;
         else {
             auto variable = std::make_shared<expr>(ctx->real_const(variableName.c_str()));
             variables[variableName] = variable;
             return variable;
         }
     }
getVariableValue()
double inet::Z3GateScheduleConfigurator::getVariableValue (const model & model, const std::shared_ptr< expr > expr) const protected virtual
 {
     auto str = model.eval(*expr.get(), false).to_string();
     int index = str.find('/');
     if (index != std::string::npos) {
         str = str.substr(3, str.length() - 1);
         index = str.find(' ');
         double val1 = atof(str.substr(0, index).c_str());
         double val2 = atof(str.substr(index + 1).c_str());
         return val1 / val2;
     }
     else
         return atof(str.c_str());
 }
Referenced by computeGateScheduling().
initialize()
void inet::Z3GateScheduleConfigurator::initialize (int stage) override protected virtual
Reimplemented from inet::GateScheduleConfiguratorBase.
 {
     GateScheduleConfiguratorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         labelAsserts = par("labelAsserts");
         optimizeSchedule = par("optimizeSchedule");
     }
 }
Member Data Documentation
ctx
context* inet::Z3GateScheduleConfigurator::ctx = nullptr mutable protected
Referenced by computeGateScheduling().
labelAsserts
bool inet::Z3GateScheduleConfigurator::labelAsserts = false protected
Referenced by addAssert(), and initialize().
optimizer
optimize* inet::Z3GateScheduleConfigurator::optimizer = nullptr mutable protected
Referenced by addAssert(), and computeGateScheduling().
optimizeSchedule
bool inet::Z3GateScheduleConfigurator::optimizeSchedule = true protected
Referenced by addAssert(), computeGateScheduling(), and initialize().
solver
solver* inet::Z3GateScheduleConfigurator::solver = nullptr mutable protected
Referenced by addAssert(), and computeGateScheduling().
variables
std::map<std::string, std::shared_ptr<expr> > inet::Z3GateScheduleConfigurator::variables mutable protected
The documentation for this class was generated from the following files:
Z3GateScheduleConfigurator.h
Z3GateScheduleConfigurator.cc