INET Framework for OMNeT++/OMNEST: inet::PathNotifyMsg Class Reference
inet::PathNotifyMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:116 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
PathNotifyMsg (const char *name=nullptr, short kind=0)
PathNotifyMsg (const PathNotifyMsg &other)
virtual ~PathNotifyMsg ()
PathNotifyMsg & operator= (const PathNotifyMsg &other)
virtual PathNotifyMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const SessionObj & getSession () const
virtual SessionObj & getSessionForUpdate ()
virtual void setSession (const SessionObj &session)
virtual const SenderTemplateObj & getSender () const
virtual SenderTemplateObj & getSenderForUpdate ()
virtual void setSender (const SenderTemplateObj &sender)
virtual int getStatus () const
virtual void setStatus (int status)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const PathNotifyMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
SessionObj session
SenderTemplateObj sender
int status = 0
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const PathNotifyMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:116 by opp_msgtool.
//
// FIXME missing documentation
//
message PathNotifyMsg extends SignallingMsg
{
    SessionObj session;
    SenderTemplateObj sender;
    int status;
    command = MSG_PATH_NOTIFY;
}
Constructor & Destructor Documentation
PathNotifyMsg() [1/2]
inet::PathNotifyMsg::PathNotifyMsg (const char * name = nullptr, short kind = 0)
PathNotifyMsg() [2/2]
inet::PathNotifyMsg::PathNotifyMsg (const PathNotifyMsg & other)
~PathNotifyMsg()
virtual inet::PathNotifyMsg::~PathNotifyMsg () virtual
Member Function Documentation
copy()
void inet::PathNotifyMsg::copy (const PathNotifyMsg & other) private
dup()
virtual PathNotifyMsg* inet::PathNotifyMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new PathNotifyMsg(*this);}
getSender()
virtual const SenderTemplateObj& inet::PathNotifyMsg::getSender () const virtual
Referenced by inet::RsvpTe::processPATH_NOTIFY().
getSenderForUpdate()
virtual SenderTemplateObj& inet::PathNotifyMsg::getSenderForUpdate () inline virtual
 { return const_cast<SenderTemplateObj&>(const_cast<PathNotifyMsg*>(this)->getSender());}
getSession()
virtual const SessionObj& inet::PathNotifyMsg::getSession () const virtual
Referenced by inet::RsvpTe::processPATH_NOTIFY().
getSessionForUpdate()
virtual SessionObj& inet::PathNotifyMsg::getSessionForUpdate () inline virtual
 { return const_cast<SessionObj&>(const_cast<PathNotifyMsg*>(this)->getSession());}
getStatus()
virtual int inet::PathNotifyMsg::getStatus () const virtual
Referenced by inet::RsvpTe::processPATH_NOTIFY().
operator=()
PathNotifyMsg& inet::PathNotifyMsg::operator= (const PathNotifyMsg & other)
operator==()
bool inet::PathNotifyMsg::operator== (const PathNotifyMsg &) protected delete
parsimPack()
virtual void inet::PathNotifyMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::PathNotifyMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setSender()
virtual void inet::PathNotifyMsg::setSender (const SenderTemplateObj & sender) virtual
Referenced by inet::RsvpTe::sendPathNotify().
setSession()
virtual void inet::PathNotifyMsg::setSession (const SessionObj & session) virtual
Referenced by inet::RsvpTe::sendPathNotify().
setStatus()
virtual void inet::PathNotifyMsg::setStatus (int status) virtual
Referenced by inet::RsvpTe::sendPathNotify().
Member Data Documentation
sender
SenderTemplateObj inet::PathNotifyMsg::sender protected
session
SessionObj inet::PathNotifyMsg::session protected
status
int inet::PathNotifyMsg::status = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h