INET Framework for OMNeT++/OMNEST: inet::physicallayer::IListening Class Reference
inet::physicallayer::IListening Class Reference abstract
This interface represents how a receiver is listening on the radio channel.
#include <IListening.h>
Public Member Functions
virtual const IRadio * getReceiver () const =0
virtual const simtime_t getStartTime () const =0
virtual const simtime_t getEndTime () const =0
virtual const Coord & getStartPosition () const =0
virtual const Coord & getEndPosition () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents how a receiver is listening on the radio channel.
Member Function Documentation
getEndPosition()
virtual const Coord& inet::physicallayer::IListening::getEndPosition () const pure virtual
Implemented in inet::physicallayer::ListeningBase.
Referenced by inet::physicallayer::RadioMedium::isInterferingTransmission().
getEndTime()
virtual const simtime_t inet::physicallayer::IListening::getEndTime () const pure virtual
Implemented in inet::physicallayer::ListeningBase.
Referenced by inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::FlatReceiverBase::computeListeningDecision(), inet::physicallayer::ApskLayeredReceiver::computeListeningDecision(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeListeningDecision(), inet::physicallayer::UnitDiskAnalogModel::computeNoise(), inet::physicallayer::IsotropicScalarBackgroundNoise::computeNoise(), inet::physicallayer::IsotropicDimensionalBackgroundNoise::computeNoise(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), inet::physicallayer::DimensionalBackgroundNoise::computeNoise(), inet::physicallayer::ReceiverBase::computeSignalPower(), and inet::physicallayer::RadioMedium::isInterferingTransmission().
getReceiver()
virtual const IRadio* inet::physicallayer::IListening::getReceiver () const pure virtual
Implemented in inet::physicallayer::ListeningBase.
Referenced by inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::FlatReceiverBase::computeListeningDecision(), inet::physicallayer::ApskLayeredReceiver::computeListeningDecision(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeListeningDecision(), inet::physicallayer::RadioMedium::isInterferingTransmission(), and inet::physicallayer::RadioMedium::receiveSignal().
getStartPosition()
virtual const Coord& inet::physicallayer::IListening::getStartPosition () const pure virtual
Implemented in inet::physicallayer::ListeningBase.
Referenced by inet::physicallayer::RadioMedium::isInterferingTransmission().
getStartTime()
virtual const simtime_t inet::physicallayer::IListening::getStartTime () const pure virtual
Implemented in inet::physicallayer::ListeningBase.
Referenced by inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::FlatReceiverBase::computeListeningDecision(), inet::physicallayer::ApskLayeredReceiver::computeListeningDecision(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeListeningDecision(), inet::physicallayer::UnitDiskAnalogModel::computeNoise(), inet::physicallayer::IsotropicScalarBackgroundNoise::computeNoise(), inet::physicallayer::IsotropicDimensionalBackgroundNoise::computeNoise(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), inet::physicallayer::DimensionalBackgroundNoise::computeNoise(), inet::physicallayer::ReceiverBase::computeSignalPower(), and inet::physicallayer::RadioMedium::isInterferingTransmission().
The documentation for this class was generated from the following file:
IListening.h