INET Framework for OMNeT++/OMNEST: inet::visualizer::NetworkNodeVisualizerBase Class Reference
inet::visualizer::NetworkNodeVisualizerBase Class Reference abstract
#include <NetworkNodeVisualizerBase.h>
Classes
class NetworkNodeVisualization
Public Member Functions
virtual NetworkNodeVisualization * findNetworkNodeVisualization (const cModule *networkNode) const =0
virtual NetworkNodeVisualization * getNetworkNodeVisualization (const cModule *networkNode) const
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual NetworkNodeVisualization * createNetworkNodeVisualization (cModule *networkNode) const =0
virtual void addNetworkNodeVisualization (NetworkNodeVisualization *networkNodeVisualization)=0
virtual void removeNetworkNodeVisualization (NetworkNodeVisualization *networkNodeVisualization)=0
virtual void destroyNetworkNodeVisualization (NetworkNodeVisualization *networkNodeVisualization)=0
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes
NetworkNodeFilter nodeFilter
double annotationSpacing
double placementPenalty
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addNetworkNodeVisualization()
virtual void inet::visualizer::NetworkNodeVisualizerBase::addNetworkNodeVisualization (NetworkNodeVisualization * networkNodeVisualization) protected pure virtual
Implemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
Referenced by receiveSignal().
createNetworkNodeVisualization()
virtual NetworkNodeVisualization* inet::visualizer::NetworkNodeVisualizerBase::createNetworkNodeVisualization (cModule * networkNode) const protected pure virtual
Implemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
Referenced by receiveSignal().
destroyNetworkNodeVisualization()
virtual void inet::visualizer::NetworkNodeVisualizerBase::destroyNetworkNodeVisualization (NetworkNodeVisualization * networkNodeVisualization) protected pure virtual
Implemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
Referenced by receiveSignal().
findNetworkNodeVisualization()
virtual NetworkNodeVisualization* inet::visualizer::NetworkNodeVisualizerBase::findNetworkNodeVisualization (const cModule * networkNode) const pure virtual
Implemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
Referenced by getNetworkNodeVisualization().
getNetworkNodeVisualization()
NetworkNodeVisualizerBase::NetworkNodeVisualization * inet::visualizer::NetworkNodeVisualizerBase::getNetworkNodeVisualization (const cModule * networkNode) const virtual
Reimplemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
 {
     auto visualization = findNetworkNodeVisualization(networkNode);
     if (visualization == nullptr)
         throw cRuntimeError("Network node visualization is not found for '%s'", networkNode->getFullPath().c_str());
     else
         return visualization;
 }
Referenced by inet::visualizer::NetworkNodeCanvasVisualizer::getNetworkNodeVisualization(), inet::visualizer::NetworkNodeOsgVisualizer::getNetworkNodeVisualization(), and receiveSignal().
handleParameterChange()
void inet::visualizer::NetworkNodeVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "nodeFilter"))
             nodeFilter.setPattern(par("nodeFilter"));
         // TODO
     }
 }
initialize()
void inet::visualizer::NetworkNodeVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         nodeFilter.setPattern(par("nodeFilter"));
         annotationSpacing = par("annotationSpacing");
         placementPenalty = par("placementPenalty");
         visualizationSubjectModule->subscribe(POST_MODEL_CHANGE, this);
         visualizationSubjectModule->subscribe(PRE_MODEL_CHANGE, this);
     }
 }
Referenced by inet::visualizer::NetworkNodeCanvasVisualizer::initialize(), and inet::visualizer::NetworkNodeOsgVisualizer::initialize().
receiveSignal()
void inet::visualizer::NetworkNodeVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == POST_MODEL_CHANGE) {
         if (auto moduleInit = dynamic_cast<cPreModuleInitNotification *>(object)) {
             auto module = moduleInit->module;
             if (isNetworkNode(module) && nodeFilter.matches(module)) {
                 auto visualization = createNetworkNodeVisualization(module);
                 addNetworkNodeVisualization(visualization);
             }
         }
     }
     else if (signal == PRE_MODEL_CHANGE) {
         if (auto moduleDelete = dynamic_cast<cPreModuleDeleteNotification *>(object)) {
             auto module = moduleDelete->module;
             if (isNetworkNode(module) && nodeFilter.matches(module)) {
                 auto visualization = getNetworkNodeVisualization(module);
                 removeNetworkNodeVisualization(visualization);
                 destroyNetworkNodeVisualization(visualization);
             }
         }
     }
     else
         throw cRuntimeError("Unknown signal");
 }
removeNetworkNodeVisualization()
virtual void inet::visualizer::NetworkNodeVisualizerBase::removeNetworkNodeVisualization (NetworkNodeVisualization * networkNodeVisualization) protected pure virtual
Implemented in inet::visualizer::NetworkNodeCanvasVisualizer, and inet::visualizer::NetworkNodeOsgVisualizer.
Referenced by receiveSignal().
Member Data Documentation
annotationSpacing
double inet::visualizer::NetworkNodeVisualizerBase::annotationSpacing protected
Referenced by inet::visualizer::NetworkNodeCanvasVisualizer::createNetworkNodeVisualization(), and initialize().
nodeFilter
NetworkNodeFilter inet::visualizer::NetworkNodeVisualizerBase::nodeFilter protected
Referenced by handleParameterChange(), inet::visualizer::NetworkNodeCanvasVisualizer::initialize(), inet::visualizer::NetworkNodeOsgVisualizer::initialize(), initialize(), and receiveSignal().
placementPenalty
double inet::visualizer::NetworkNodeVisualizerBase::placementPenalty protected
Referenced by inet::visualizer::NetworkNodeCanvasVisualizer::createNetworkNodeVisualization(), and initialize().
The documentation for this class was generated from the following files:
NetworkNodeVisualizerBase.h
NetworkNodeVisualizerBase.cc