INET Framework for OMNeT++/OMNEST: inet::visualizer::InterfaceTableVisualizerBase Class Reference
inet::visualizer::InterfaceTableVisualizerBase Class Reference abstract
#include <InterfaceTableVisualizerBase.h>
Classes
class DirectiveResolver
class InterfaceVisualization
Parameters
bool displayInterfaceTables = false
bool displayWiredInterfacesAtConnections = false
bool displayBackground = false
NetworkNodeFilter nodeFilter
InterfaceFilter interfaceFilter
StringFormat format
Placement placementHint
double placementPriority
cFigure::Font font
cFigure::Color textColor
cFigure::Color backgroundColor
double opacity = NaN
std::map< std::pair< int, int >, const InterfaceVisualization * > interfaceVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual cModule * getNetworkNode (const InterfaceVisualization *interfaceVisualization)
virtual cGate * getOutputGate (cModule *networkNode, NetworkInterface *networkInterface)
virtual cGate * getOutputGate (const InterfaceVisualization *interfaceVisualization)
virtual InterfaceVisualization * createInterfaceVisualization (cModule *networkNode, NetworkInterface *networkInterface)=0
virtual const InterfaceVisualization * getInterfaceVisualization (cModule *networkNode, NetworkInterface *networkInterface)
virtual void addInterfaceVisualization (const InterfaceVisualization *interfaceVisualization)
virtual void addAllInterfaceVisualizations ()
virtual void removeInterfaceVisualization (const InterfaceVisualization *interfaceVisualization)
virtual void removeAllInterfaceVisualizations ()
virtual void updateAllInterfaceVisualizations ()
virtual std::string getVisualizationText (const NetworkInterface *networkInterface)
virtual void refreshInterfaceVisualization (const InterfaceVisualization *interfaceVisualization, const NetworkInterface *networkInterface)=0
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addAllInterfaceVisualizations()
void inet::visualizer::InterfaceTableVisualizerBase::addAllInterfaceVisualizations () protected virtual
 {
     for (cModule::SubmoduleIterator it(visualizationSubjectModule); !it.end(); it++) {
         auto networkNode = *it;
         if (isNetworkNode(networkNode) && nodeFilter.matches(networkNode)) {
             L3AddressResolver addressResolver;
             auto interfaceTable = addressResolver.findInterfaceTableOf(networkNode);
             if (interfaceTable != nullptr) {
                 for (int i = 0; i < interfaceTable->getNumInterfaces(); i++) {
                     auto networkInterface = interfaceTable->getInterface(i);
                     if (networkInterface != nullptr && interfaceFilter.matches(networkInterface)) {
                         auto interfaceVisualization = createInterfaceVisualization(networkNode, networkInterface);
                         addInterfaceVisualization(interfaceVisualization);
                     }
                 }
             }
         }
     }
 }
Referenced by updateAllInterfaceVisualizations().
addInterfaceVisualization()
void inet::visualizer::InterfaceTableVisualizerBase::addInterfaceVisualization (const InterfaceVisualization * interfaceVisualization) protected virtual
Reimplemented in inet::visualizer::InterfaceTableCanvasVisualizer, and inet::visualizer::InterfaceTableOsgVisualizer.
 {
     auto key = std::pair<int, int>(interfaceVisualization->networkNodeId, interfaceVisualization->interfaceId);
     interfaceVisualizations[key] = interfaceVisualization;
 }
Referenced by addAllInterfaceVisualizations(), inet::visualizer::InterfaceTableOsgVisualizer::addInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::addInterfaceVisualization(), and receiveSignal().
createInterfaceVisualization()
virtual InterfaceVisualization* inet::visualizer::InterfaceTableVisualizerBase::createInterfaceVisualization (cModule * networkNode, NetworkInterface * networkInterface) protected pure virtual
Implemented in inet::visualizer::InterfaceTableCanvasVisualizer, and inet::visualizer::InterfaceTableOsgVisualizer.
Referenced by addAllInterfaceVisualizations(), and receiveSignal().
getInterfaceVisualization()
const InterfaceTableVisualizerBase::InterfaceVisualization * inet::visualizer::InterfaceTableVisualizerBase::getInterfaceVisualization (cModule * networkNode, NetworkInterface * networkInterface) protected virtual
 {
     auto key = std::pair<int, int>(networkNode->getId(), networkInterface->getInterfaceId());
     auto it = interfaceVisualizations.find(key);
     return it == interfaceVisualizations.end() ? nullptr : it->second;
 }
Referenced by receiveSignal().
getNetworkNode()
cModule * inet::visualizer::InterfaceTableVisualizerBase::getNetworkNode (const InterfaceVisualization * interfaceVisualization) protected virtual
 {
     return getSimulation()->getModule(interfaceVisualization->networkNodeId);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::getNetworkInterface(), and getOutputGate().
getOutputGate() [1/2]
cGate * inet::visualizer::InterfaceTableVisualizerBase::getOutputGate (cModule * networkNode, NetworkInterface * networkInterface) protected virtual
 {
     if (networkInterface->getNodeOutputGateId() == -1)
         return nullptr;
     cGate *outputGate = networkNode->gate(networkInterface->getNodeOutputGateId());
     if (outputGate == nullptr || outputGate->getChannel() == nullptr)
         return nullptr;
     else
         return outputGate;
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::addInterfaceVisualization(), inet::visualizer::InterfaceTableOsgVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::refreshInterfaceVisualization(), and inet::visualizer::InterfaceTableCanvasVisualizer::removeInterfaceVisualization().
getOutputGate() [2/2]
cGate * inet::visualizer::InterfaceTableVisualizerBase::getOutputGate (const InterfaceVisualization * interfaceVisualization) protected virtual
 {
     if (interfaceVisualization->networkNodeGateId == -1)
         return nullptr;
     else {
         auto networkNode = getNetworkNode(interfaceVisualization);
         return networkNode != nullptr ? networkNode->gate(interfaceVisualization->networkNodeGateId) : nullptr;
     }
 }
getVisualizationText()
std::string inet::visualizer::InterfaceTableVisualizerBase::getVisualizationText (const NetworkInterface * networkInterface) protected virtual
 {
     DirectiveResolver directiveResolver(networkInterface);
     return format.formatString(&directiveResolver);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::addInterfaceVisualization(), inet::visualizer::InterfaceTableOsgVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableOsgVisualizer::refreshInterfaceVisualization(), and inet::visualizer::InterfaceTableCanvasVisualizer::refreshInterfaceVisualization().
handleParameterChange()
void inet::visualizer::InterfaceTableVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "nodeFilter"))
             nodeFilter.setPattern(par("nodeFilter"));
         else if (!strcmp(name, "interfaceFilter"))
             interfaceFilter.setPattern(par("interfaceFilter"));
         else if (!strcmp(name, "format"))
             format.parseFormat(par("format"));
         updateAllInterfaceVisualizations();
     }
 }
initialize()
void inet::visualizer::InterfaceTableVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::InterfaceTableCanvasVisualizer, and inet::visualizer::InterfaceTableOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayInterfaceTables = par("displayInterfaceTables");
         displayWiredInterfacesAtConnections = par("displayWiredInterfacesAtConnections");
         displayBackground = par("displayBackground");
         nodeFilter.setPattern(par("nodeFilter"));
         interfaceFilter.setPattern(par("interfaceFilter"));
         format.parseFormat(par("format"));
         placementHint = parsePlacement(par("placementHint"));
         placementPriority = par("placementPriority");
         font = cFigure::parseFont(par("font"));
         textColor = cFigure::parseColor(par("textColor"));
         backgroundColor = cFigure::parseColor(par("backgroundColor"));
         opacity = par("opacity");
         if (displayInterfaceTables)
             subscribe();
     }
 }
Referenced by inet::visualizer::InterfaceTableOsgVisualizer::initialize(), and inet::visualizer::InterfaceTableCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::InterfaceTableVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayInterfaceTables) {
         unsubscribe();
         removeAllInterfaceVisualizations();
     }
 }
receiveSignal()
void inet::visualizer::InterfaceTableVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == interfaceCreatedSignal) {
         auto networkNode = getContainingNode(static_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode)) {
             auto networkInterface = static_cast<NetworkInterface *>(object);
             if (networkInterface->getInterfaceId() != -1 && interfaceFilter.matches(networkInterface)) {
                 auto interfaceVisualization = createInterfaceVisualization(networkNode, networkInterface);
                 addInterfaceVisualization(interfaceVisualization);
             }
         }
     }
     else if (signal == interfaceDeletedSignal) {
         auto networkNode = getContainingNode(static_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode)) {
             auto networkInterface = static_cast<NetworkInterface *>(object);
             if (networkInterface->getInterfaceId() != -1 && interfaceFilter.matches(networkInterface)) {
                 auto interfaceVisualization = getInterfaceVisualization(networkNode, networkInterface);
                 removeInterfaceVisualization(interfaceVisualization);
                 delete interfaceVisualization;
             }
         }
     }
     else if (signal == interfaceConfigChangedSignal || signal == interfaceIpv4ConfigChangedSignal || signal == interfaceStateChangedSignal) {
         auto networkNode = getContainingNode(static_cast<cModule *>(source));
         if (object != nullptr && nodeFilter.matches(networkNode)) {
             auto networkInterfaceDetails = static_cast<NetworkInterfaceChangeDetails *>(object);
             auto networkInterface = networkInterfaceDetails->getNetworkInterface();
             auto fieldId = networkInterfaceDetails->getFieldId();
             if ((signal == interfaceConfigChangedSignal && fieldId == NetworkInterface::F_IPV4_DATA)
 #ifdef INET_WITH_IPv4
                     || (signal == interfaceIpv4ConfigChangedSignal && (fieldId == Ipv4InterfaceData::F_IP_ADDRESS || fieldId == Ipv4InterfaceData::F_NETMASK))
 #endif // INET_WITH_IPv4
                     || (signal == interfaceStateChangedSignal && (fieldId == NetworkInterface::F_STATE || fieldId == NetworkInterface::F_CARRIER)))
             {
                 if (networkInterface->getInterfaceId() != -1 && interfaceFilter.matches(networkInterface)) {
                     auto interfaceVisualization = getInterfaceVisualization(networkNode, networkInterface);
                     if (interfaceVisualization == nullptr) {
                         interfaceVisualization = createInterfaceVisualization(networkNode, networkInterface);
                         addInterfaceVisualization(interfaceVisualization);
                     }
                     else
                         refreshInterfaceVisualization(interfaceVisualization, networkInterface);
                 }
             }
         }
     }
     else
         throw cRuntimeError("Unknown signal");
 }
refreshInterfaceVisualization()
virtual void inet::visualizer::InterfaceTableVisualizerBase::refreshInterfaceVisualization (const InterfaceVisualization * interfaceVisualization, const NetworkInterface * networkInterface) protected pure virtual
Implemented in inet::visualizer::InterfaceTableCanvasVisualizer, and inet::visualizer::InterfaceTableOsgVisualizer.
Referenced by receiveSignal().
removeAllInterfaceVisualizations()
void inet::visualizer::InterfaceTableVisualizerBase::removeAllInterfaceVisualizations () protected virtual
 {
     std::vector<const InterfaceVisualization *> removedIntefaceVisualizations;
     for (auto it : interfaceVisualizations)
         removedIntefaceVisualizations.push_back(it.second);
     for (auto it : removedIntefaceVisualizations) {
         removeInterfaceVisualization(it);
         delete it;
     }
 }
Referenced by preDelete(), and updateAllInterfaceVisualizations().
removeInterfaceVisualization()
void inet::visualizer::InterfaceTableVisualizerBase::removeInterfaceVisualization (const InterfaceVisualization * interfaceVisualization) protected virtual
Reimplemented in inet::visualizer::InterfaceTableCanvasVisualizer, and inet::visualizer::InterfaceTableOsgVisualizer.
 {
     auto key = std::pair<int, int>(interfaceVisualization->networkNodeId, interfaceVisualization->interfaceId);
     interfaceVisualizations.erase(interfaceVisualizations.find(key));
 }
Referenced by receiveSignal(), removeAllInterfaceVisualizations(), inet::visualizer::InterfaceTableOsgVisualizer::removeInterfaceVisualization(), and inet::visualizer::InterfaceTableCanvasVisualizer::removeInterfaceVisualization().
subscribe()
void inet::visualizer::InterfaceTableVisualizerBase::subscribe () protected virtual
 {
     visualizationSubjectModule->subscribe(interfaceCreatedSignal, this);
     visualizationSubjectModule->subscribe(interfaceDeletedSignal, this);
     visualizationSubjectModule->subscribe(interfaceConfigChangedSignal, this);
     visualizationSubjectModule->subscribe(interfaceStateChangedSignal, this);
     visualizationSubjectModule->subscribe(interfaceIpv4ConfigChangedSignal, this);
 }
Referenced by initialize().
unsubscribe()
void inet::visualizer::InterfaceTableVisualizerBase::unsubscribe () protected virtual
 {
     // NOTE: lookup the module again because it may have been deleted first
     auto visualizationSubjectModule = findModuleFromPar<cModule>(par("visualizationSubjectModule"), this);
     if (visualizationSubjectModule != nullptr) {
         visualizationSubjectModule->unsubscribe(interfaceCreatedSignal, this);
         visualizationSubjectModule->unsubscribe(interfaceDeletedSignal, this);
         visualizationSubjectModule->unsubscribe(interfaceConfigChangedSignal, this);
         visualizationSubjectModule->unsubscribe(interfaceStateChangedSignal, this);
         visualizationSubjectModule->unsubscribe(interfaceIpv4ConfigChangedSignal, this);
     }
 }
Referenced by preDelete().
updateAllInterfaceVisualizations()
void inet::visualizer::InterfaceTableVisualizerBase::updateAllInterfaceVisualizations () protected virtual
 {
     removeAllInterfaceVisualizations();
     addAllInterfaceVisualizations();
 }
Referenced by handleParameterChange().
Member Data Documentation
backgroundColor
cFigure::Color inet::visualizer::InterfaceTableVisualizerBase::backgroundColor protected
Referenced by inet::visualizer::InterfaceTableOsgVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and initialize().
displayBackground
bool inet::visualizer::InterfaceTableVisualizerBase::displayBackground = false protected
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and initialize().
displayInterfaceTables
bool inet::visualizer::InterfaceTableVisualizerBase::displayInterfaceTables = false protected
Referenced by initialize(), and preDelete().
displayWiredInterfacesAtConnections
bool inet::visualizer::InterfaceTableVisualizerBase::displayWiredInterfacesAtConnections = false protected
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and initialize().
font
cFigure::Font inet::visualizer::InterfaceTableVisualizerBase::font protected
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and initialize().
format
StringFormat inet::visualizer::InterfaceTableVisualizerBase::format protected
Referenced by getVisualizationText(), handleParameterChange(), and initialize().
interfaceFilter
InterfaceFilter inet::visualizer::InterfaceTableVisualizerBase::interfaceFilter protected
Referenced by addAllInterfaceVisualizations(), handleParameterChange(), initialize(), and receiveSignal().
interfaceVisualizations
std::map<std::pair<int, int>, const InterfaceVisualization *> inet::visualizer::InterfaceTableVisualizerBase::interfaceVisualizations protected
Referenced by addInterfaceVisualization(), getInterfaceVisualization(), removeAllInterfaceVisualizations(), and removeInterfaceVisualization().
nodeFilter
NetworkNodeFilter inet::visualizer::InterfaceTableVisualizerBase::nodeFilter protected
Referenced by addAllInterfaceVisualizations(), handleParameterChange(), initialize(), and receiveSignal().
opacity
double inet::visualizer::InterfaceTableVisualizerBase::opacity = NaN protected
Referenced by inet::visualizer::InterfaceTableOsgVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and initialize().
placementHint
Placement inet::visualizer::InterfaceTableVisualizerBase::placementHint protected
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::addInterfaceVisualization(), and initialize().
placementPriority
double inet::visualizer::InterfaceTableVisualizerBase::placementPriority protected
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::addInterfaceVisualization(), and initialize().
textColor
cFigure::Color inet::visualizer::InterfaceTableVisualizerBase::textColor protected
Referenced by inet::visualizer::InterfaceTableOsgVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and initialize().
The documentation for this class was generated from the following files:
InterfaceTableVisualizerBase.h
InterfaceTableVisualizerBase.cc