INET Framework for OMNeT++/OMNEST: inet::sctp::SctpGapList Class Reference
inet::sctp::SctpGapList Class Reference
#include <SctpGapList.h>
Public Types
enum GapType { GT_Any = 0, GT_Revokable = 1, GT_NonRevokable = 2 }
Public Member Functions
SctpGapList ()
~SctpGapList ()
void setInitialCumAckTsn (const uint32_t cumAckTsn)
uint32_t getCumAckTsn () const
uint32_t getHighestTsnReceived () const
uint32_t getNumGaps (const GapType type) const
bool tsnInGapList (const uint32_t tsn) const
bool tsnIsRevokable (const uint32_t tsn) const
bool tsnIsNonRevokable (const uint32_t tsn) const
uint32_t getGapStart (const GapType type, const uint32_t index) const
uint32_t getGapStop (const GapType type, const uint32_t index) const
void check () const
void print (std::ostream &os) const
void forwardCumAckTsn (const uint32_t cumAckTsn)
bool tryToAdvanceCumAckTsn ()
void removeFromGapList (const uint32_t removedTsn)
bool updateGapList (const uint32_t receivedTsn, bool &newChunkReceived, bool tsnIsRevokable=true)
void resetGaps (const uint32_t newCumAck)
Private Attributes
uint32_t CumAckTsn
SctpSimpleGapList RevokableGapList
SctpSimpleGapList NonRevokableGapList
SctpSimpleGapList CombinedGapList
Member Enumeration Documentation
GapType
enum inet::sctp::SctpGapList::GapType
Enumerator
GT_Any
GT_Revokable
GT_NonRevokable
                  {
         GT_Any          = 0,
         GT_Revokable    = 1,
         GT_NonRevokable = 2
     };
Constructor & Destructor Documentation
SctpGapList()
inet::sctp::SctpGapList::SctpGapList ()
 {
     CumAckTsn = 0;
 }
~SctpGapList()
inet::sctp::SctpGapList::~SctpGapList ()
 {
 }
Member Function Documentation
check()
void inet::sctp::SctpGapList::check () const
 {
     CombinedGapList.check(CumAckTsn);
     RevokableGapList.check(CumAckTsn);
     NonRevokableGapList.check(CumAckTsn);
 }
forwardCumAckTsn()
void inet::sctp::SctpGapList::forwardCumAckTsn (const uint32_t cumAckTsn)
 {
     CumAckTsn = cumAckTsn;
     CombinedGapList.forwardCumAckTsn(CumAckTsn);
     RevokableGapList.forwardCumAckTsn(CumAckTsn);
     NonRevokableGapList.forwardCumAckTsn(CumAckTsn);
 }
Referenced by inet::sctp::SctpAssociation::processResetResponseArrived(), and inet::sctp::SctpAssociation::sendInitAck().
getCumAckTsn()
uint32_t inet::sctp::SctpGapList::getCumAckTsn () const inline
     {
         return CumAckTsn;
     }
Referenced by inet::sctp::SctpAssociation::createSack(), inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::processDataArrived(), inet::sctp::SctpAssociation::processForwardTsnArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::processTimer(), and inet::sctp::SctpAssociation::sendShutdown().
getGapStart()
uint32_t inet::sctp::SctpGapList::getGapStart (const GapType type, const uint32_t index) const inline
     {
         if (type == GT_Revokable) {
             return RevokableGapList.getGapStart(index);
         }
         else if (type == GT_NonRevokable) {
             return NonRevokableGapList.getGapStart(index);
         }
         else {
             return CombinedGapList.getGapStart(index);
         }
     }
Referenced by inet::sctp::SctpAssociation::processSackArrived().
getGapStop()
uint32_t inet::sctp::SctpGapList::getGapStop (const GapType type, const uint32_t index) const inline
     {
         if (type == GT_Revokable) {
             return RevokableGapList.getGapStop(index);
         }
         else if (type == GT_NonRevokable) {
             return NonRevokableGapList.getGapStop(index);
         }
         else {
             return CombinedGapList.getGapStop(index);
         }
     }
Referenced by inet::sctp::SctpAssociation::processSackArrived().
getHighestTsnReceived()
uint32_t inet::sctp::SctpGapList::getHighestTsnReceived () const inline
     {
         if (CombinedGapList.getNumGaps() > 0) {
             return CombinedGapList.getGapStop(CombinedGapList.getNumGaps() - 1);
         }
         else {
             return CumAckTsn;
         }
     }
Referenced by inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::sctp::SctpAssociation::processDataArrived(), inet::sctp::SctpAssociation::processInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processOutgoingResetRequestArrived(), inet::sctp::SctpAssociation::processTimer(), inet::sctp::SctpAssociation::resetGapLists(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
getNumGaps()
uint32_t inet::sctp::SctpGapList::getNumGaps (const GapType type) const inline
     {
         if (type == GT_Revokable) {
             return RevokableGapList.getNumGaps();
         }
         else if (type == GT_NonRevokable) {
             return NonRevokableGapList.getNumGaps();
         }
         else {
             return CombinedGapList.getNumGaps();
         }
     }
Referenced by inet::sctp::SctpAssociation::createSack(), inet::sctp::SctpAssociation::processSackArrived(), inet::sctp::SctpAssociation::processTimer(), and inet::sctp::SctpAssociation::timeForSack().
print()
void inet::sctp::SctpGapList::print (std::ostream & os) const
 {
     os << "CumAck=" << CumAckTsn;
     os << "   Combined-Gaps=" << CombinedGapList;
     os << "   R-Gaps=" << RevokableGapList;
     os << "   NR-Gaps=" << NonRevokableGapList;
 }
Referenced by inet::sctp::operator<<().
removeFromGapList()
void inet::sctp::SctpGapList::removeFromGapList (const uint32_t removedTsn)
 {
     RevokableGapList.removeFromGapList(removedTsn);
     NonRevokableGapList.removeFromGapList(removedTsn);
     CombinedGapList.removeFromGapList(removedTsn);
 }
Referenced by inet::sctp::SctpAssociation::makeRoomForTsn().
resetGaps()
void inet::sctp::SctpGapList::resetGaps (const uint32_t newCumAck)
 {
     CumAckTsn = newCumAck;
     RevokableGapList.resetGaps();
     NonRevokableGapList.resetGaps();
     CombinedGapList.resetGaps();
 }
Referenced by inet::sctp::SctpAssociation::resetGapLists().
setInitialCumAckTsn()
void inet::sctp::SctpGapList::setInitialCumAckTsn (const uint32_t cumAckTsn) inline
     {
         assert(CombinedGapList.getNumGaps() == 0);
         CumAckTsn = cumAckTsn;
     }
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpAssociation::processSackArrived().
tryToAdvanceCumAckTsn()
bool inet::sctp::SctpGapList::tryToAdvanceCumAckTsn ()
 {
     if (CombinedGapList.tryToAdvanceCumAckTsn(CumAckTsn)) {
         RevokableGapList.forwardCumAckTsn(CumAckTsn);
         NonRevokableGapList.forwardCumAckTsn(CumAckTsn);
         return true;
     }
     return false;
 }
Referenced by inet::sctp::SctpAssociation::processDataArrived(), and inet::sctp::SctpAssociation::processForwardTsnArrived().
tsnInGapList()
bool inet::sctp::SctpGapList::tsnInGapList (const uint32_t tsn) const inline
     {
         return CombinedGapList.tsnInGapList(tsn);
     }
Referenced by inet::sctp::SctpAssociation::processForwardTsnArrived(), and inet::sctp::SctpAssociation::tsnIsDuplicate().
tsnIsNonRevokable()
bool inet::sctp::SctpGapList::tsnIsNonRevokable (const uint32_t tsn) const inline
     {
         return NonRevokableGapList.tsnInGapList(tsn);
     }
Referenced by inet::sctp::SctpAssociation::processSackArrived().
tsnIsRevokable()
bool inet::sctp::SctpGapList::tsnIsRevokable (const uint32_t tsn) const inline
     {
         return RevokableGapList.tsnInGapList(tsn);
     }
Referenced by inet::sctp::SctpAssociation::processSackArrived(), and updateGapList().
updateGapList()
bool inet::sctp::SctpGapList::updateGapList (const uint32_t receivedTsn, bool & newChunkReceived, bool tsnIsRevokable = true)
 {
     uint32_t oldCumAckTsn = CumAckTsn;
     if (tsnIsRevokable) {
         // Once a TSN become non-revokable, it cannot become revokable again!
         // However, if the list became too long, updateGapList() may be called
         // again when the chunk is received again.
         RevokableGapList.updateGapList(receivedTsn, oldCumAckTsn, newChunkReceived);
     }
     else {
         if (NonRevokableGapList.updateGapList(receivedTsn, oldCumAckTsn, newChunkReceived) == true) {
             // TSN has moved from revokable to non-revokable!
             RevokableGapList.removeFromGapList(receivedTsn);
         }
     }
     // Finally, add TSN to combined list and set CumAckTSN.
     oldCumAckTsn = CumAckTsn;
     const bool newChunk = CombinedGapList.updateGapList(receivedTsn, CumAckTsn, newChunkReceived);
     if (oldCumAckTsn != CumAckTsn) {
         RevokableGapList.forwardCumAckTsn(CumAckTsn);
         NonRevokableGapList.forwardCumAckTsn(CumAckTsn);
     }
     return newChunk;
 }
Referenced by inet::sctp::SctpAssociation::processDataArrived(), inet::sctp::SctpAssociation::processForwardTsnArrived(), and inet::sctp::SctpAssociation::processSackArrived().
Member Data Documentation
CombinedGapList
SctpSimpleGapList inet::sctp::SctpGapList::CombinedGapList private
Referenced by check(), forwardCumAckTsn(), print(), removeFromGapList(), resetGaps(), tryToAdvanceCumAckTsn(), and updateGapList().
CumAckTsn
uint32_t inet::sctp::SctpGapList::CumAckTsn private
Referenced by check(), forwardCumAckTsn(), print(), resetGaps(), SctpGapList(), tryToAdvanceCumAckTsn(), and updateGapList().
NonRevokableGapList
SctpSimpleGapList inet::sctp::SctpGapList::NonRevokableGapList private
Referenced by check(), forwardCumAckTsn(), print(), removeFromGapList(), resetGaps(), tryToAdvanceCumAckTsn(), and updateGapList().
RevokableGapList
SctpSimpleGapList inet::sctp::SctpGapList::RevokableGapList private
Referenced by check(), forwardCumAckTsn(), print(), removeFromGapList(), resetGaps(), tryToAdvanceCumAckTsn(), and updateGapList().
The documentation for this class was generated from the following files:
SctpGapList.h
SctpGapList.cc