INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211HtDataMode Class Reference
inet::physicallayer::Ieee80211HtDataMode Class Reference
#include <Ieee80211HtMode.h>
Public Member Functions
Ieee80211HtDataMode (const Ieee80211Htmcs *modulationAndCodingScheme, const Hz bandwidth, GuardIntervalType guardIntervalType)
b getServiceFieldLength () const
b getTailFieldLength () const
virtual Hz getBandwidth () const override
virtual int getNumberOfSpatialStreams () const override
virtual b getPaddingLength (b dataLength) const override
virtual b getCompleteLength (b dataLength) const override
virtual const simtime_t getDuration (b dataLength) const override
virtual bps getNetBitrate () const override
virtual bps getGrossBitrate () const override
virtual const Ieee80211Htmcs * getModulationAndCodingScheme () const
virtual const Ieee80211HtCode * getCode () const
virtual const Ieee80211OfdmModulation * getModulation () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211HtModeBase
Ieee80211HtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
virtual int getNumberOfDataSubcarriers () const
virtual int getNumberOfPilotSubcarriers () const
virtual int getNumberOfTotalSubcarriers () const
virtual GuardIntervalType getGuardIntervalType () const
virtual unsigned int getMcsIndex () const
Public Member Functions inherited from inet::physicallayer::Ieee80211HtTimingRelatedParametersBase
const simtime_t getDFTPeriod () const
const simtime_t getGIDuration () const
const simtime_t getShortGIDuration () const
const simtime_t getSymbolInterval () const
const simtime_t getShortGISymbolInterval () const
Protected Member Functions
bps computeGrossBitrate () const override
bps computeNetBitrate () const override
unsigned int computeNumberOfSpatialStreams (const Ieee80211OfdmModulation *stream1Modulation, const Ieee80211OfdmModulation *stream2Modulation, const Ieee80211OfdmModulation *stream3Modulation, const Ieee80211OfdmModulation *stream4Modulation) const
unsigned int computeNumberOfCodedBitsPerSubcarrierSum () const
unsigned int computeNumberOfBccEncoders () const
Protected Attributes
const Ieee80211Htmcs * modulationAndCodingScheme
const unsigned int numberOfBccEncoders
Protected Attributes inherited from inet::physicallayer::Ieee80211HtModeBase
const Hz bandwidth
const GuardIntervalType guardIntervalType
const unsigned int mcsIndex
const unsigned int numberOfSpatialStreams
bps netBitrate
bps grossBitrate
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Types inherited from inet::physicallayer::Ieee80211HtModeBase
enum GuardIntervalType { HT_GUARD_INTERVAL_SHORT, HT_GUARD_INTERVAL_LONG }
Constructor & Destructor Documentation
Ieee80211HtDataMode()
inet::physicallayer::Ieee80211HtDataMode::Ieee80211HtDataMode (const Ieee80211Htmcs * modulationAndCodingScheme, const Hz bandwidth, GuardIntervalType guardIntervalType)
                                                                                                                                                  :
     Ieee80211HtModeBase(modulationAndCodingScheme->getMcsIndex(), computeNumberOfSpatialStreams(modulationAndCodingScheme->getModulation(), modulationAndCodingScheme->getStreamExtension1Modulation(), modulationAndCodingScheme->getStreamExtension2Modulation(), modulationAndCodingScheme->getStreamExtension3Modulation()), bandwidth, guardIntervalType),
     modulationAndCodingScheme(modulationAndCodingScheme),
     numberOfBccEncoders(computeNumberOfBccEncoders())
 {
 }
Member Function Documentation
computeGrossBitrate()
bps inet::physicallayer::Ieee80211HtDataMode::computeGrossBitrate () const override protected virtual
Implements inet::physicallayer::Ieee80211HtModeBase.
 {
     unsigned int numberOfCodedBitsPerSubcarrierSum = computeNumberOfCodedBitsPerSubcarrierSum();
     unsigned int numberOfCodedBitsPerSymbol = numberOfCodedBitsPerSubcarrierSum * getNumberOfDataSubcarriers();
     if (guardIntervalType == HT_GUARD_INTERVAL_LONG)
         return bps(numberOfCodedBitsPerSymbol / getSymbolInterval());
     else if (guardIntervalType == HT_GUARD_INTERVAL_SHORT)
         return bps(numberOfCodedBitsPerSymbol / getShortGISymbolInterval());
     else
         throw cRuntimeError("Unknown guard interval type");
 }
computeNetBitrate()
bps inet::physicallayer::Ieee80211HtDataMode::computeNetBitrate () const override protected virtual
Implements inet::physicallayer::Ieee80211HtModeBase.
 {
     return getGrossBitrate() * getCode()->getForwardErrorCorrection()->getCodeRate();
 }
computeNumberOfBccEncoders()
unsigned int inet::physicallayer::Ieee80211HtDataMode::computeNumberOfBccEncoders () const protected
 {
     // When the BCC FEC encoder is used, a single encoder is used, except that two encoders
     // are used when the selected MCS has a PHY rate greater than 300 Mb/s (see 20.6).
     return getGrossBitrate() > Mbps(300) ? 2 : 1;
 }
computeNumberOfCodedBitsPerSubcarrierSum()
unsigned int inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum () const protected
 {
     return (modulationAndCodingScheme->getModulation() ? modulationAndCodingScheme->getModulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension1Modulation() ? modulationAndCodingScheme->getStreamExtension1Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension2Modulation() ? modulationAndCodingScheme->getStreamExtension2Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension3Modulation() ? modulationAndCodingScheme->getStreamExtension3Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0);
 }
Referenced by computeGrossBitrate(), and getDuration().
computeNumberOfSpatialStreams()
unsigned int inet::physicallayer::Ieee80211HtDataMode::computeNumberOfSpatialStreams (const Ieee80211OfdmModulation * stream1Modulation, const Ieee80211OfdmModulation * stream2Modulation, const Ieee80211OfdmModulation * stream3Modulation, const Ieee80211OfdmModulation * stream4Modulation) const protected
 {
     return (stream1Modulation ? 1 : 0) + (stream2Modulation ? 1 : 0) +
            (stream3Modulation ? 1 : 0) + (stream4Modulation ? 1 : 0);
 }
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211HtDataMode::getBandwidth () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211HtModeBase.
 { return bandwidth; }
getCode()
virtual const Ieee80211HtCode* inet::physicallayer::Ieee80211HtDataMode::getCode () const inline virtual
 { return modulationAndCodingScheme->getCode(); }
Referenced by computeNetBitrate(), and getDuration().
getCompleteLength()
b inet::physicallayer::Ieee80211HtDataMode::getCompleteLength (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     return getServiceFieldLength() + getTailFieldLength() + dataLength; // TODO padding?
 }
Referenced by getDuration().
getDuration()
const simtime_t inet::physicallayer::Ieee80211HtDataMode::getDuration (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     unsigned int numberOfCodedBitsPerSubcarrierSum = computeNumberOfCodedBitsPerSubcarrierSum();
     unsigned int numberOfCodedBitsPerSymbol = numberOfCodedBitsPerSubcarrierSum * getNumberOfDataSubcarriers();
     const IForwardErrorCorrection *forwardErrorCorrection = getCode() ? getCode()->getForwardErrorCorrection() : nullptr;
     unsigned int dataBitsPerSymbol = forwardErrorCorrection ? forwardErrorCorrection->getDecodedLength(numberOfCodedBitsPerSymbol) : numberOfCodedBitsPerSymbol;
     int numberOfSymbols = lrint(ceil((double)getCompleteLength(dataLength).get() / dataBitsPerSymbol)); // TODO getBitLength(dataLength) should be divisible by dataBitsPerSymbol
     return numberOfSymbols * getSymbolInterval();
 }
Referenced by inet::physicallayer::Ieee80211HtMode::getDuration().
getGrossBitrate()
virtual bps inet::physicallayer::Ieee80211HtDataMode::getGrossBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211HtModeBase.
 { return Ieee80211HtModeBase::getGrossBitrate(); }
Referenced by computeNetBitrate(), and computeNumberOfBccEncoders().
getModulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211HtDataMode::getModulation () const inline override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 { return modulationAndCodingScheme->getModulation(); }
getModulationAndCodingScheme()
virtual const Ieee80211Htmcs* inet::physicallayer::Ieee80211HtDataMode::getModulationAndCodingScheme () const inline virtual
 { return modulationAndCodingScheme; }
getNetBitrate()
virtual bps inet::physicallayer::Ieee80211HtDataMode::getNetBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211HtModeBase.
 { return Ieee80211HtModeBase::getNetBitrate(); }
getNumberOfSpatialStreams()
virtual int inet::physicallayer::Ieee80211HtDataMode::getNumberOfSpatialStreams () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211HtModeBase.
 { return Ieee80211HtModeBase::getNumberOfSpatialStreams(); }
Referenced by inet::physicallayer::Ieee80211HtCompliantModes::getCompliantMode().
getPaddingLength()
virtual b inet::physicallayer::Ieee80211HtDataMode::getPaddingLength (b dataLength) const inline override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 { return b(0); }
getServiceFieldLength()
b inet::physicallayer::Ieee80211HtDataMode::getServiceFieldLength () const inline
 { return b(16); }
Referenced by getCompleteLength().
getTailFieldLength()
b inet::physicallayer::Ieee80211HtDataMode::getTailFieldLength () const inline
 { return b(6) * numberOfBccEncoders; }
Referenced by getCompleteLength().
Member Data Documentation
modulationAndCodingScheme
const Ieee80211Htmcs* inet::physicallayer::Ieee80211HtDataMode::modulationAndCodingScheme protected
Referenced by computeNumberOfCodedBitsPerSubcarrierSum().
numberOfBccEncoders
const unsigned int inet::physicallayer::Ieee80211HtDataMode::numberOfBccEncoders protected
The documentation for this class was generated from the following files:
Ieee80211HtMode.h
Ieee80211HtMode.cc