INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2Interface Class Reference
inet::ospfv2::Ospfv2Interface Class Reference
#include <Ospfv2Interface.h>
Public Types
enum Ospfv2InterfaceType {
UNKNOWN_TYPE = 0, POINTTOPOINT = 1, BROADCAST = 2, NBMA = 3,
POINTTOMULTIPOINT = 4, VIRTUAL = 5
}
enum Ospfv2InterfaceEventType {
INTERFACE_UP = 0, HELLO_TIMER = 1, WAIT_TIMER = 2, ACKNOWLEDGEMENT_TIMER = 3,
BACKUP_SEEN = 4, NEIGHBOR_CHANGE = 5, LOOP_INDICATION = 6, UNLOOP_INDICATION = 7,
INTERFACE_DOWN = 8
}
enum Ospfv2InterfaceStateType {
DOWN_STATE = 0, LOOPBACK_STATE = 1, WAITING_STATE = 2, POINTTOPOINT_STATE = 3,
NOT_DESIGNATED_ROUTER_STATE = 4, BACKUP_STATE = 5, DESIGNATED_ROUTER_STATE = 6
}
enum Ospfv2InterfaceMode { ACTIVE = 0, PASSIVE = 1, NO_OSPF = 2 }
Public Member Functions
Ospfv2Interface (Ospfv2InterfaceType ifType=UNKNOWN_TYPE)
virtual ~Ospfv2Interface ()
void processEvent (Ospfv2InterfaceEventType event)
void reset ()
void sendHelloPacket (Ipv4Address destination, short ttl=1)
void sendLsAcknowledgement (const Ospfv2LsaHeader *lsaHeader, Ipv4Address destination)
Neighbor * getNeighborById (RouterId neighborID)
Neighbor * getNeighborByAddress (Ipv4Address address)
void addNeighbor (Neighbor *neighbor)
Ospfv2InterfaceStateType getState () const
bool hasAnyNeighborInStates (int states) const
void removeFromAllRetransmissionLists (LsaKeyType lsaKey)
bool isOnAnyRetransmissionList (LsaKeyType lsaKey) const
bool floodLsa (const Ospfv2Lsa *lsa, Ospfv2Interface *intf=nullptr, Neighbor *neighbor=nullptr)
void addDelayedAcknowledgement (const Ospfv2LsaHeader &lsaHeader)
void sendDelayedAcknowledgements ()
void ageTransmittedLsaLists ()
Packet * createUpdatePacket (const Ospfv2Lsa *lsa)
void setType (Ospfv2InterfaceType ifType)
Ospfv2InterfaceType getType () const
Ospfv2InterfaceMode getMode () const
void setMode (Ospfv2InterfaceMode intfMode)
CrcMode getCrcMode () const
void setCrcMode (CrcMode crcMode)
void setIfIndex (IInterfaceTable *ift, int index)
int getIfIndex () const
void setInterfaceName (std::string ifName)
std::string getInterfaceName () const
void setMtu (unsigned short ifMTU)
unsigned short getMtu () const
void setAreaId (AreaId areaId)
AreaId getAreaId () const
void setTransitAreaId (AreaId areaId)
AreaId getTransitAreaId () const
void setOutputCost (Metric cost)
Metric getOutputCost () const
void setRetransmissionInterval (short interval)
short getRetransmissionInterval () const
void setTransmissionDelay (short delay)
short getTransmissionDelay () const
void setAcknowledgementDelay (short delay)
short getAcknowledgementDelay () const
void setRouterPriority (unsigned char priority)
unsigned char getRouterPriority () const
void setHelloInterval (short interval)
short getHelloInterval () const
void setPollInterval (short interval)
short getPollInterval () const
void setRouterDeadInterval (short interval)
short getRouterDeadInterval () const
void setAuthenticationType (AuthenticationType type)
AuthenticationType getAuthenticationType () const
void setAuthenticationKey (AuthenticationKeyType key)
AuthenticationKeyType getAuthenticationKey () const
void setAddressRange (Ipv4AddressRange range)
Ipv4AddressRange getAddressRange () const
cMessage * getHelloTimer ()
cMessage * getWaitTimer ()
cMessage * getAcknowledgementTimer ()
DesignatedRouterId getDesignatedRouter () const
DesignatedRouterId getBackupDesignatedRouter () const
unsigned long getNeighborCount () const
Neighbor * getNeighbor (unsigned long i)
const Neighbor * getNeighbor (unsigned long i) const
void setArea (Ospfv2Area *area)
Ospfv2Area * getArea ()
const Ospfv2Area * getArea () const
Static Public Member Functions
static const char * getStateString (Ospfv2InterfaceStateType stateType)
static const char * getTypeString (Ospfv2InterfaceType intfType)
static const char * getModeString (Ospfv2InterfaceMode intfMode)
Private Member Functions
void changeState (Ospfv2InterfaceState *newState, Ospfv2InterfaceState *currentState)
Private Attributes
Ospfv2InterfaceType interfaceType
Ospfv2InterfaceMode interfaceMode
CrcMode crcMode
Ospfv2InterfaceState * state
Ospfv2InterfaceState * previousState
std::string interfaceName
int ifIndex
unsigned short mtu
Ipv4AddressRange interfaceAddressRange
AreaId areaID
AreaId transitAreaID
short helloInterval
short pollInterval
short routerDeadInterval
short interfaceTransmissionDelay
unsigned char routerPriority
cMessage * helloTimer
cMessage * waitTimer
cMessage * acknowledgementTimer
std::map< RouterId, Neighbor * > neighboringRoutersByID
std::map< Ipv4Address, Neighbor * > neighboringRoutersByAddress
std::vector< Neighbor * > neighboringRouters
std::map< Ipv4Address, std::list< Ospfv2LsaHeader > > delayedAcknowledgements
DesignatedRouterId designatedRouter
DesignatedRouterId backupDesignatedRouter
Metric interfaceOutputCost
short retransmissionInterval
short acknowledgementDelay
AuthenticationType authenticationType
AuthenticationKeyType authenticationKey
Ospfv2Area * parentArea
Friends
class Ospfv2InterfaceState
std::ostream & operator<< (std::ostream &stream, const Ospfv2Interface &intf)
Member Enumeration Documentation
Ospfv2InterfaceEventType
enum inet::ospfv2::Ospfv2Interface::Ospfv2InterfaceEventType
Enumerator
INTERFACE_UP
HELLO_TIMER
WAIT_TIMER
ACKNOWLEDGEMENT_TIMER
BACKUP_SEEN
NEIGHBOR_CHANGE
LOOP_INDICATION
UNLOOP_INDICATION
INTERFACE_DOWN
{
         INTERFACE_UP          = 0,
         HELLO_TIMER           = 1,
         WAIT_TIMER            = 2,
         ACKNOWLEDGEMENT_TIMER = 3,
         BACKUP_SEEN           = 4,
         NEIGHBOR_CHANGE       = 5,
         LOOP_INDICATION       = 6,
         UNLOOP_INDICATION     = 7,
         INTERFACE_DOWN        = 8
     };
Ospfv2InterfaceMode
enum inet::ospfv2::Ospfv2Interface::Ospfv2InterfaceMode
Enumerator
ACTIVE
PASSIVE
NO_OSPF
{
         ACTIVE  = 0,
         PASSIVE = 1,
         NO_OSPF = 2,
     };
Ospfv2InterfaceStateType
enum inet::ospfv2::Ospfv2Interface::Ospfv2InterfaceStateType
Enumerator
DOWN_STATE
LOOPBACK_STATE
WAITING_STATE
POINTTOPOINT_STATE
NOT_DESIGNATED_ROUTER_STATE
BACKUP_STATE
DESIGNATED_ROUTER_STATE
{
         DOWN_STATE                  = 0,
         LOOPBACK_STATE              = 1,
         WAITING_STATE               = 2,
         POINTTOPOINT_STATE          = 3,
         NOT_DESIGNATED_ROUTER_STATE = 4,
         BACKUP_STATE                = 5,
         DESIGNATED_ROUTER_STATE     = 6
     };
Ospfv2InterfaceType
enum inet::ospfv2::Ospfv2Interface::Ospfv2InterfaceType
Enumerator
UNKNOWN_TYPE
POINTTOPOINT
BROADCAST
NBMA
POINTTOMULTIPOINT
VIRTUAL
{
         UNKNOWN_TYPE      = 0,
         POINTTOPOINT      = 1,
         BROADCAST         = 2,
         NBMA              = 3,
         POINTTOMULTIPOINT = 4,
         VIRTUAL           = 5
     };
Constructor & Destructor Documentation
Ospfv2Interface()
inet::ospfv2::Ospfv2Interface::Ospfv2Interface (Ospfv2Interface::Ospfv2InterfaceType ifType = UNKNOWN_TYPE)
                                                                           :
     interfaceType(ifType),
     interfaceMode(ACTIVE),
     crcMode(CRC_MODE_UNDEFINED),
     interfaceName(""),
     ifIndex(0),
     mtu(0),
     interfaceAddressRange(NULL_IPV4ADDRESSRANGE),
     areaID(BACKBONE_AREAID),
     transitAreaID(BACKBONE_AREAID),
     helloInterval(10),
     pollInterval(120),
     routerDeadInterval(40),
     interfaceTransmissionDelay(1),
     routerPriority(0),
     designatedRouter(NULL_DESIGNATEDROUTERID),
     backupDesignatedRouter(NULL_DESIGNATEDROUTERID),
     interfaceOutputCost(1),
     retransmissionInterval(5),
     acknowledgementDelay(1),
     authenticationType(NULL_TYPE),
     parentArea(nullptr)
 {
     state = new InterfaceStateDown;
     previousState = nullptr;
     helloTimer = new cMessage("Interface::InterfaceHelloTimer", INTERFACE_HELLO_TIMER);
     helloTimer->setContextPointer(this);
     waitTimer = new cMessage("Interface::InterfaceWaitTimer", INTERFACE_WAIT_TIMER);
     waitTimer->setContextPointer(this);
     acknowledgementTimer = new cMessage("Interface::InterfaceAcknowledgementTimer", INTERFACE_ACKNOWLEDGEMENT_TIMER);
     acknowledgementTimer->setContextPointer(this);
     memset(authenticationKey.bytes, 0, sizeof(authenticationKey.bytes));
 }
~Ospfv2Interface()
inet::ospfv2::Ospfv2Interface::~Ospfv2Interface () virtual
 {
     if (parentArea) {
         MessageHandler *messageHandler = parentArea->getRouter()->getMessageHandler();
         messageHandler->clearTimer(helloTimer);
         messageHandler->clearTimer(waitTimer);
         messageHandler->clearTimer(acknowledgementTimer);
     }
     delete helloTimer;
     delete waitTimer;
     delete acknowledgementTimer;
     if (previousState)
         delete previousState;
     delete state;
     for (uint32_t i = 0; i < neighboringRouters.size(); i++)
         delete neighboringRouters[i];
 }
Member Function Documentation
addDelayedAcknowledgement()
void inet::ospfv2::Ospfv2Interface::addDelayedAcknowledgement (const Ospfv2LsaHeader & lsaHeader)
 {
     if (interfaceType == Ospfv2Interface::BROADCAST) {
         if ((getState() == Ospfv2Interface::DESIGNATED_ROUTER_STATE) ||
             (getState() == Ospfv2Interface::BACKUP_STATE) ||
             (designatedRouter == NULL_DESIGNATEDROUTERID))
         {
             delayedAcknowledgements[Ipv4Address::ALL_OSPF_ROUTERS_MCAST].push_back(lsaHeader);
         }
         else {
             delayedAcknowledgements[Ipv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST].push_back(lsaHeader);
         }
     }
     else {
         long neighborCount = neighboringRouters.size();
         for (long i = 0; i < neighborCount; i++) {
             if (neighboringRouters[i]->getState() >= Neighbor::EXCHANGE_STATE) {
                 delayedAcknowledgements[neighboringRouters[i]->getAddress()].push_back(lsaHeader);
             }
         }
     }
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA().
addNeighbor()
void inet::ospfv2::Ospfv2Interface::addNeighbor (Neighbor * neighbor)
 {
     neighboringRoutersByID[neighbor->getNeighborID()] = neighbor;
     neighboringRoutersByAddress[neighbor->getAddress()] = neighbor;
     neighbor->setInterface(this);
     neighboringRouters.push_back(neighbor);
 }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink(), and inet::ospfv2::HelloHandler::processPacket().
ageTransmittedLsaLists()
void inet::ospfv2::Ospfv2Interface::ageTransmittedLsaLists ()
 {
     long neighborCount = neighboringRouters.size();
     for (long i = 0; i < neighborCount; i++) {
         neighboringRouters[i]->ageTransmittedLSAList();
     }
 }
changeState()
void inet::ospfv2::Ospfv2Interface::changeState (Ospfv2InterfaceState * newState, Ospfv2InterfaceState * currentState) private
 {
     EV_INFO << "Changing the state of interface " << this->getIfIndex()
             << " from '" << getStateString(currentState->getState())
             << "' to '" << getStateString(newState->getState()) << "'" << std::endl;
     if (previousState != nullptr) {
         delete previousState;
     }
     state = newState;
     previousState = currentState;
 }
Referenced by inet::ospfv2::Ospfv2InterfaceState::changeState().
createUpdatePacket()
Packet * inet::ospfv2::Ospfv2Interface::createUpdatePacket (const Ospfv2Lsa * lsa)
 {
     Ospfv2LsaType lsaType = lsa->getHeader().getLsType();
     const auto& updatePacket = makeShared<Ospfv2LinkStateUpdatePacket>();
     B packetLength = OSPFv2_HEADER_LENGTH + B(sizeof(uint32_t)); // OSPF header + place for number of advertisements
     updatePacket->setType(LINKSTATE_UPDATE_PACKET);
     updatePacket->setRouterID(Ipv4Address(parentArea->getRouter()->getRouterID()));
     updatePacket->setAreaID(Ipv4Address(areaID));
     updatePacket->setAuthenticationType(authenticationType);
     switch (lsaType) {
         case ROUTERLSA_TYPE:
         case NETWORKLSA_TYPE:
         case SUMMARYLSA_NETWORKS_TYPE:
         case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
         case AS_EXTERNAL_LSA_TYPE: {
             updatePacket->setOspfLSAsArraySize(1);
             updatePacket->setOspfLSAs(0, lsa->dup());
             auto lsa = updatePacket->getOspfLSAsForUpdate(0);
             auto& lsaHeader = lsa->getHeaderForUpdate();
             unsigned short lsAge = lsaHeader.getLsAge();
             if (lsAge < MAX_AGE - interfaceTransmissionDelay) {
                 lsAge += interfaceTransmissionDelay;
             }
             else {
                 lsAge = MAX_AGE;
             }
             lsaHeader.setLsAge(lsAge);
             auto lsaSize = calculateLSASize(lsa);
             ASSERT(lsaSize == B(lsaHeader.getLsaLength()));
             setLsaCrc(*lsa, crcMode);
             packetLength += lsaSize;
         }
         break;
         default:
             throw cRuntimeError("Invalid LSA type: %d", lsaType);
     }
     updatePacket->setPacketLengthField(B(packetLength).get());
     updatePacket->setChunkLength(packetLength);
     for (int j = 0; j < 8; j++) {
         updatePacket->setAuthentication(j, authenticationKey.bytes[j]);
     }
     setOspfCrc(updatePacket, crcMode);
     Packet *pk = new Packet();
     pk->insertAtBack(updatePacket);
     return pk;
 }
Referenced by floodLsa(), inet::ospfv2::LinkStateRequestHandler::processPacket(), and inet::ospfv2::LinkStateUpdateHandler::processPacket().
floodLsa()
bool inet::ospfv2::Ospfv2Interface::floodLsa (const Ospfv2Lsa * lsa, Ospfv2Interface * intf = nullptr, Neighbor * neighbor = nullptr)
See also
RFC2328 Section 13.3.
 {
     bool floodedBackOut = false;
     if (
         (
             (lsa->getHeader().getLsType() == AS_EXTERNAL_LSA_TYPE) &&
             (interfaceType != Ospfv2Interface::VIRTUAL) &&
             (parentArea->getExternalRoutingCapability())
         ) ||
         (
             (lsa->getHeader().getLsType() != AS_EXTERNAL_LSA_TYPE) &&
             (
                 (
                     (areaID != BACKBONE_AREAID) &&
                     (interfaceType != Ospfv2Interface::VIRTUAL)
                 ) ||
                 (areaID == BACKBONE_AREAID)
             )
         )
         )
     {
         long neighborCount = neighboringRouters.size();
         bool lsaAddedToRetransmissionList = false;
         LinkStateId linkStateID = lsa->getHeader().getLinkStateID();
         LsaKeyType lsaKey;
         lsaKey.linkStateID = linkStateID;
         lsaKey.advertisingRouter = lsa->getHeader().getAdvertisingRouter();
         for (long i = 0; i < neighborCount; i++) { // (1)
             if (neighboringRouters[i]->getState() < Neighbor::EXCHANGE_STATE) { // (1) (a)
                 continue;
             }
             if (neighboringRouters[i]->getState() < Neighbor::FULL_STATE) { // (1) (b)
                 Ospfv2LsaHeader *requestLSAHeader = neighboringRouters[i]->findOnRequestList(lsaKey);
                 if (requestLSAHeader != nullptr) {
                     // operator< and operator== on OSPFLSAHeaders determines which one is newer(less means older)
                     if (lsa->getHeader() < (*requestLSAHeader)) {
                         continue;
                     }
                     if (operator==(lsa->getHeader(), (*requestLSAHeader))) {
                         neighboringRouters[i]->removeFromRequestList(lsaKey);
                         continue;
                     }
                     neighboringRouters[i]->removeFromRequestList(lsaKey);
                 }
             }
             if (neighbor == neighboringRouters[i]) { // (1) (c)
                 continue;
             }
             neighboringRouters[i]->addToRetransmissionList(lsa); // (1) (d)
             lsaAddedToRetransmissionList = true;
         }
         if (lsaAddedToRetransmissionList) { // (2)
             if ((intf != this) ||
                 ((neighbor != nullptr) &&
                  (neighbor->getNeighborID() != designatedRouter.routerID) &&
                  (neighbor->getNeighborID() != backupDesignatedRouter.routerID))) // (3)
             {
                 if ((intf != this) || (getState() != Ospfv2Interface::BACKUP_STATE)) { // (4)
                     Packet *updatePacket = createUpdatePacket(lsa); // (5)
                     if (updatePacket != nullptr) {
                         int ttl = (interfaceType == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
                         MessageHandler *messageHandler = parentArea->getRouter()->getMessageHandler();
                         if (interfaceType == Ospfv2Interface::BROADCAST) {
                             if ((getState() == Ospfv2Interface::DESIGNATED_ROUTER_STATE) ||
                                 (getState() == Ospfv2Interface::BACKUP_STATE) ||
                                 (designatedRouter == NULL_DESIGNATEDROUTERID))
{
                                 messageHandler->sendPacket(updatePacket, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, this, ttl);
                                 for (long k = 0; k < neighborCount; k++) {
                                     neighboringRouters[k]->addToTransmittedLSAList(lsaKey);
                                     if (!neighboringRouters[k]->isUpdateRetransmissionTimerActive()) {
                                         neighboringRouters[k]->startUpdateRetransmissionTimer();
                                     }
                                 }
                             }
                             else {
                                 messageHandler->sendPacket(updatePacket, Ipv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST, this, ttl);
                                 Neighbor *dRouter = getNeighborById(designatedRouter.routerID);
                                 Neighbor *backupDRouter = getNeighborById(backupDesignatedRouter.routerID);
                                 if (dRouter != nullptr) {
                                     dRouter->addToTransmittedLSAList(lsaKey);
                                     if (!dRouter->isUpdateRetransmissionTimerActive()) {
                                         dRouter->startUpdateRetransmissionTimer();
                                     }
                                 }
                                 if (backupDRouter != nullptr) {
                                     backupDRouter->addToTransmittedLSAList(lsaKey);
                                     if (!backupDRouter->isUpdateRetransmissionTimerActive()) {
                                         backupDRouter->startUpdateRetransmissionTimer();
                                     }
                                 }
                             }
                         }
                         else {
                             if (interfaceType == Ospfv2Interface::POINTTOPOINT) {
                                 messageHandler->sendPacket(updatePacket, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, this, ttl);
                                 if (neighborCount > 0) {
                                     neighboringRouters[0]->addToTransmittedLSAList(lsaKey);
                                     if (!neighboringRouters[0]->isUpdateRetransmissionTimerActive()) {
                                         neighboringRouters[0]->startUpdateRetransmissionTimer();
                                     }
                                 }
                             }
                             else {
                                 for (long m = 0; m < neighborCount; m++) {
                                     if (neighboringRouters[m]->getState() >= Neighbor::EXCHANGE_STATE) {
                                         messageHandler->sendPacket(updatePacket, neighboringRouters[m]->getAddress(), this, ttl);
                                         neighboringRouters[m]->addToTransmittedLSAList(lsaKey);
                                         if (!neighboringRouters[m]->isUpdateRetransmissionTimerActive()) {
                                             neighboringRouters[m]->startUpdateRetransmissionTimer();
                                         }
                                     }
                                 }
                             }
                         }
                         if (intf == this) {
                             floodedBackOut = true;
                         }
                     }
                 }
             }
         }
     }
     return floodedBackOut;
 }
getAcknowledgementDelay()
short inet::ospfv2::Ospfv2Interface::getAcknowledgementDelay () const inline
 { return acknowledgementDelay; }
Referenced by inet::ospfv2::InterfaceStateDown::processEvent().
getAcknowledgementTimer()
cMessage* inet::ospfv2::Ospfv2Interface::getAcknowledgementTimer () inline
 { return acknowledgementTimer; }
Referenced by inet::ospfv2::InterfaceStateDown::processEvent().
getAddressRange()
Ipv4AddressRange inet::ospfv2::Ospfv2Interface::getAddressRange () const inline
 { return interfaceAddressRange; }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::HelloHandler::processPacket(), and inet::ospfv2::NeighborState::updateLsa().
getArea() [1/2]
Ospfv2Area* inet::ospfv2::Ospfv2Interface::getArea () inline
 { return parentArea; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::NeighborState::changeState(), inet::ospfv2::Neighbor::clearRequestRetransmissionTimer(), inet::ospfv2::Neighbor::clearUpdateRetransmissionTimer(), inet::ospfv2::Neighbor::createDatabaseSummary(), inet::ospfv2::Neighbor::needAdjacency(), inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateDown::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::Neighbor::reset(), inet::ospfv2::Neighbor::retransmitDatabaseDescriptionPacket(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), inet::ospfv2::Neighbor::sendLinkStateRequestPacket(), inet::ospfv2::Neighbor::startRequestRetransmissionTimer(), inet::ospfv2::Neighbor::startUpdateRetransmissionTimer(), inet::ospfv2::NeighborState::updateLsa(), and inet::ospfv2::Neighbor::~Neighbor().
getArea() [2/2]
const Ospfv2Area* inet::ospfv2::Ospfv2Interface::getArea () const inline
 { return parentArea; }
getAreaId()
AreaId inet::ospfv2::Ospfv2Interface::getAreaId () const inline
 { return areaID; }
Referenced by inet::ospfv2::Ospfv2Area::originateSummaryLSA().
getAuthenticationKey()
AuthenticationKeyType inet::ospfv2::Ospfv2Interface::getAuthenticationKey () const inline
 { return authenticationKey; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
getAuthenticationType()
AuthenticationType inet::ospfv2::Ospfv2Interface::getAuthenticationType () const inline
 { return authenticationType; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
getBackupDesignatedRouter()
DesignatedRouterId inet::ospfv2::Ospfv2Interface::getBackupDesignatedRouter () const inline
 { return backupDesignatedRouter; }
Referenced by inet::ospfv2::Neighbor::needAdjacency(), and inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent().
getCrcMode()
CrcMode inet::ospfv2::Ospfv2Interface::getCrcMode () const inline
 { return crcMode; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
getDesignatedRouter()
DesignatedRouterId inet::ospfv2::Ospfv2Interface::getDesignatedRouter () const inline
 { return designatedRouter; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Neighbor::needAdjacency(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::LinkStateRequestHandler::processPacket(), and inet::ospfv2::LinkStateUpdateHandler::processPacket().
getHelloInterval()
short inet::ospfv2::Ospfv2Interface::getHelloInterval () const inline
 { return helloInterval; }
Referenced by inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
getHelloTimer()
cMessage* inet::ospfv2::Ospfv2Interface::getHelloTimer () inline
 { return helloTimer; }
Referenced by inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), and inet::ospfv2::InterfaceStateDesignatedRouter::processEvent().
getIfIndex()
int inet::ospfv2::Ospfv2Interface::getIfIndex () const inline
 { return ifIndex; }
Referenced by changeState(), inet::ospfv2::Ospfv2::handleInterfaceDown(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2InterfaceState::printElectionResult(), inet::ospfv2::MessageHandler::printEvent(), and inet::ospfv2::MessageHandler::sendPacket().
getInterfaceName()
std::string inet::ospfv2::Ospfv2Interface::getInterfaceName () const inline
 { return interfaceName; }
Referenced by inet::ospfv2::operator<<().
getMode()
Ospfv2InterfaceMode inet::ospfv2::Ospfv2Interface::getMode () const inline
 { return interfaceMode; }
Referenced by inet::ospfv2::MessageHandler::sendPacket().
getModeString()
const char * inet::ospfv2::Ospfv2Interface::getModeString (Ospfv2InterfaceMode intfMode) static
 {
     switch (intfMode) {
         case ACTIVE:
             return "Active";
         case PASSIVE:
             return "Passive";
         case NO_OSPF:
             return "NoOSPF";
         default:
             ASSERT(false);
             break;
     }
     return "";
 }
Referenced by inet::ospfv2::operator<<().
getMtu()
unsigned short inet::ospfv2::Ospfv2Interface::getMtu () const inline
 { return mtu; }
Referenced by inet::ospfv2::DatabaseDescriptionHandler::processPacket(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
getNeighbor() [1/2]
Neighbor* inet::ospfv2::Ospfv2Interface::getNeighbor (unsigned long i) inline
 { return neighboringRouters[i]; }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
getNeighbor() [2/2]
const Neighbor* inet::ospfv2::Ospfv2Interface::getNeighbor (unsigned long i) const inline
 { return neighboringRouters[i]; }
getNeighborByAddress()
Neighbor * inet::ospfv2::Ospfv2Interface::getNeighborByAddress (Ipv4Address address)
 {
     auto neighborIt = neighboringRoutersByAddress.find(address);
     return (neighborIt != neighboringRoutersByAddress.end()) ? neighborIt->second : nullptr;
 }
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::HelloHandler::processPacket(), and inet::ospfv2::MessageHandler::processPacket().
getNeighborById()
Neighbor * inet::ospfv2::Ospfv2Interface::getNeighborById (RouterId neighborID)
 {
     auto neighborIt = neighboringRoutersByID.find(neighborID);
     return (neighborIt != neighboringRoutersByID.end()) ? neighborIt->second : nullptr;
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), floodLsa(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::ospfv2::HelloHandler::processPacket(), and inet::ospfv2::MessageHandler::processPacket().
getNeighborCount()
unsigned long inet::ospfv2::Ospfv2Interface::getNeighborCount () const inline
 { return neighboringRouters.size(); }
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
getOutputCost()
Metric inet::ospfv2::Ospfv2Interface::getOutputCost () const inline
 { return interfaceOutputCost; }
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
getPollInterval()
short inet::ospfv2::Ospfv2Interface::getPollInterval () const inline
 { return pollInterval; }
Referenced by inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), and inet::ospfv2::NeighborStateDown::processEvent().
getRetransmissionInterval()
short inet::ospfv2::Ospfv2Interface::getRetransmissionInterval () const inline
 { return retransmissionInterval; }
Referenced by inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::Neighbor::startRequestRetransmissionTimer(), and inet::ospfv2::Neighbor::startUpdateRetransmissionTimer().
getRouterDeadInterval()
short inet::ospfv2::Ospfv2Interface::getRouterDeadInterval () const inline
 { return routerDeadInterval; }
Referenced by inet::ospfv2::InterfaceStateDown::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
getRouterPriority()
unsigned char inet::ospfv2::Ospfv2Interface::getRouterPriority () const inline
 { return routerPriority; }
Referenced by inet::ospfv2::InterfaceStateDown::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
getState()
Ospfv2Interface::Ospfv2InterfaceStateType inet::ospfv2::Ospfv2Interface::getState () const
 {
     return state->getState();
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), addDelayedAcknowledgement(), inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), floodLsa(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2InterfaceState::printElectionResult(), inet::ospfv2::MessageHandler::printEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::MessageHandler::processPacket(), sendDelayedAcknowledgements(), sendHelloPacket(), and inet::ospfv2::NeighborState::updateLsa().
getStateString()
const char * inet::ospfv2::Ospfv2Interface::getStateString (Ospfv2Interface::Ospfv2InterfaceStateType stateType) static
 {
     switch (stateType) {
         case DOWN_STATE:
             return "Down";
         case LOOPBACK_STATE:
             return "Loopback";
         case WAITING_STATE:
             return "Waiting";
         case POINTTOPOINT_STATE:
             return "PointToPoint";
         case NOT_DESIGNATED_ROUTER_STATE:
             return "NotDesignatedRouter";
         case BACKUP_STATE:
             return "Backup";
         case DESIGNATED_ROUTER_STATE:
             return "DesignatedRouter";
         default:
             ASSERT(false);
             break;
     }
     return "";
 }
Referenced by changeState(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2InterfaceState::printElectionResult(), and inet::ospfv2::MessageHandler::printEvent().
getTransitAreaId()
AreaId inet::ospfv2::Ospfv2Interface::getTransitAreaId () const inline
 { return transitAreaID; }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink(), and inet::ospfv2::MessageHandler::processPacket().
getTransmissionDelay()
short inet::ospfv2::Ospfv2Interface::getTransmissionDelay () const inline
 { return interfaceTransmissionDelay; }
Referenced by inet::ospfv2::Neighbor::retransmitUpdatePacket().
getType()
Ospfv2InterfaceType inet::ospfv2::Ospfv2Interface::getType () const inline
 { return interfaceType; }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Neighbor::createDatabaseSummary(), inet::ospfv2::Neighbor::needAdjacency(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2InterfaceState::printElectionResult(), inet::ospfv2::MessageHandler::printEvent(), inet::ospfv2::NeighborStateDown::processEvent(), inet::ospfv2::NeighborStateAttempt::processEvent(), inet::ospfv2::NeighborStateExchangeStart::processEvent(), inet::ospfv2::NeighborStateInit::processEvent(), inet::ospfv2::NeighborStateTwoWay::processEvent(), inet::ospfv2::NeighborStateLoading::processEvent(), inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), inet::ospfv2::NeighborStateExchange::processEvent(), inet::ospfv2::NeighborStateFull::processEvent(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::MessageHandler::processPacket(), inet::ospfv2::Neighbor::retransmitDatabaseDescriptionPacket(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
getTypeString()
const char * inet::ospfv2::Ospfv2Interface::getTypeString (Ospfv2InterfaceType intfType) static
 {
     switch (intfType) {
         case UNKNOWN_TYPE:
             return "Unknown";
         case POINTTOPOINT:
             return "PointToPoint";
         case BROADCAST:
             return "Broadcast";
         case NBMA:
             return "NBMA";
         case POINTTOMULTIPOINT:
             return "PointToMultiPoint";
         case VIRTUAL:
             return "Virtual";
         default:
             ASSERT(false);
             break;
     }
     return "";
 }
Referenced by inet::ospfv2::operator<<().
getWaitTimer()
cMessage* inet::ospfv2::Ospfv2Interface::getWaitTimer () inline
 { return waitTimer; }
Referenced by inet::ospfv2::InterfaceStateDown::processEvent().
hasAnyNeighborInStates()
bool inet::ospfv2::Ospfv2Interface::hasAnyNeighborInStates (int states) const
 {
     for (uint32_t i = 0; i < neighboringRouters.size(); i++) {
         Neighbor::NeighborStateType neighborState = neighboringRouters[i]->getState();
         if (neighborState & states)
             return true;
     }
     return false;
 }
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
isOnAnyRetransmissionList()
bool inet::ospfv2::Ospfv2Interface::isOnAnyRetransmissionList (LsaKeyType lsaKey) const
 {
     for (uint32_t i = 0; i < neighboringRouters.size(); i++) {
         if (neighboringRouters[i]->isLinkStateRequestListEmpty(lsaKey))
             return true;
     }
     return false;
 }
processEvent()
void inet::ospfv2::Ospfv2Interface::processEvent (Ospfv2Interface::Ospfv2InterfaceEventType event)
 {
     state->processEvent(this, event);
 }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2::handleInterfaceDown(), inet::ospfv2::MessageHandler::handleTimer(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::NeighborStateFull::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
removeFromAllRetransmissionLists()
void inet::ospfv2::Ospfv2Interface::removeFromAllRetransmissionLists (LsaKeyType lsaKey)
 {
     for (uint32_t i = 0; i < neighboringRouters.size(); i++)
         neighboringRouters[i]->removeFromRetransmissionList(lsaKey);
 }
reset()
void inet::ospfv2::Ospfv2Interface::reset ()
 {
     MessageHandler *messageHandler = parentArea->getRouter()->getMessageHandler();
     messageHandler->clearTimer(helloTimer);
     messageHandler->clearTimer(waitTimer);
     messageHandler->clearTimer(acknowledgementTimer);
     designatedRouter = NULL_DESIGNATEDROUTERID;
     backupDesignatedRouter = NULL_DESIGNATEDROUTERID;
     long neighborCount = neighboringRouters.size();
     for (long i = 0; i < neighborCount; i++) {
         neighboringRouters[i]->processEvent(Neighbor::KILL_NEIGHBOR);
     }
 }
Referenced by inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateLoopback::processEvent(), inet::ospfv2::InterfaceStateDown::processEvent(), and inet::ospfv2::InterfaceStateDesignatedRouter::processEvent().
sendDelayedAcknowledgements()
void inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements ()
 {
     MessageHandler *messageHandler = parentArea->getRouter()->getMessageHandler();
     B maxPacketSize = ((IPv4_MAX_HEADER_LENGTH + OSPFv2_HEADER_LENGTH + OSPFv2_LSA_HEADER_LENGTH) > B(mtu)) ? IPV4_DATAGRAM_LENGTH : B(mtu);
     for (auto& elem : delayedAcknowledgements) {
         int ackCount = elem.second.size();
         if (ackCount > 0) {
             while (!(elem.second.empty())) {
                 const auto& ackPacket = makeShared<Ospfv2LinkStateAcknowledgementPacket>();
                 B packetSize = IPv4_MAX_HEADER_LENGTH + OSPFv2_HEADER_LENGTH;
                 ackPacket->setType(LINKSTATE_ACKNOWLEDGEMENT_PACKET);
                 ackPacket->setRouterID(Ipv4Address(parentArea->getRouter()->getRouterID()));
                 ackPacket->setAreaID(Ipv4Address(areaID));
                 ackPacket->setAuthenticationType(authenticationType);
                 while ((!(elem.second.empty())) && (packetSize <= (maxPacketSize - OSPFv2_LSA_HEADER_LENGTH))) {
                     unsigned long headerCount = ackPacket->getLsaHeadersArraySize();
                     ackPacket->setLsaHeadersArraySize(headerCount + 1);
                     ackPacket->setLsaHeaders(headerCount, *(elem.second.begin()));
                     elem.second.pop_front();
                     packetSize += OSPFv2_LSA_HEADER_LENGTH;
                 }
                 ackPacket->setPacketLengthField(B(packetSize - IPv4_MAX_HEADER_LENGTH).get());
                 ackPacket->setChunkLength(B(ackPacket->getPacketLengthField()));
                 for (int i = 0; i < 8; i++) {
                     ackPacket->setAuthentication(i, authenticationKey.bytes[i]);
                 }
                 setOspfCrc(ackPacket, crcMode);
                 Packet *pk = new Packet();
                 pk->insertAtBack(ackPacket);
                 int ttl = (interfaceType == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
                 if (interfaceType == Ospfv2Interface::BROADCAST) {
                     if ((getState() == Ospfv2Interface::DESIGNATED_ROUTER_STATE) ||
                         (getState() == Ospfv2Interface::BACKUP_STATE) ||
                         (designatedRouter == NULL_DESIGNATEDROUTERID))
                     {
                         messageHandler->sendPacket(pk, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, this, ttl);
                     }
                     else {
                         messageHandler->sendPacket(pk, Ipv4Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST, this, ttl);
                     }
                 }
                 else {
                     if (interfaceType == Ospfv2Interface::POINTTOPOINT) {
                         messageHandler->sendPacket(pk, Ipv4Address::ALL_OSPF_ROUTERS_MCAST, this, ttl);
                     }
                     else {
                         messageHandler->sendPacket(pk, elem.first, this, ttl);
                     }
                 }
             }
         }
     }
     messageHandler->startTimer(acknowledgementTimer, acknowledgementDelay);
 }
Referenced by inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), and inet::ospfv2::InterfaceStateDesignatedRouter::processEvent().
sendHelloPacket()
void inet::ospfv2::Ospfv2Interface::sendHelloPacket (Ipv4Address destination, short ttl = 1)
 {
     const auto& helloPacket = makeShared<Ospfv2HelloPacket>();
     std::vector<Ipv4Address> neighbors;
     helloPacket->setRouterID(Ipv4Address(parentArea->getRouter()->getRouterID()));
     helloPacket->setAreaID(Ipv4Address(parentArea->getAreaID()));
     helloPacket->setAuthenticationType(authenticationType);
     if (((interfaceType == POINTTOPOINT) &&
          (interfaceAddressRange.address == NULL_IPV4ADDRESS)) ||
         (interfaceType == VIRTUAL))
     {
         helloPacket->setNetworkMask(NULL_IPV4ADDRESS);
     }
     else {
         helloPacket->setNetworkMask(interfaceAddressRange.mask);
     }
     Ospfv2Options options;
     options.E_ExternalRoutingCapability = parentArea->getExternalRoutingCapability();
     helloPacket->setOptions(options);
     helloPacket->setHelloInterval(helloInterval);
     helloPacket->setRouterPriority(routerPriority);
     helloPacket->setRouterDeadInterval(routerDeadInterval);
     helloPacket->setDesignatedRouter(designatedRouter.ipInterfaceAddress);
     helloPacket->setBackupDesignatedRouter(backupDesignatedRouter.ipInterfaceAddress);
     long neighborCount = neighboringRouters.size();
     for (long j = 0; j < neighborCount; j++) {
         if (neighboringRouters[j]->getState() >= Neighbor::INIT_STATE) {
             neighbors.push_back(neighboringRouters[j]->getAddress());
         }
     }
     unsigned int initedNeighborCount = neighbors.size();
     helloPacket->setNeighborArraySize(initedNeighborCount);
     for (unsigned int k = 0; k < initedNeighborCount; k++) {
         helloPacket->setNeighbor(k, neighbors[k]);
     }
     helloPacket->setPacketLengthField(B(OSPFv2_HEADER_LENGTH + OSPFv2_HELLO_HEADER_LENGTH + B(initedNeighborCount * 4)).get());
     helloPacket->setChunkLength(B(helloPacket->getPacketLengthField()));
     for (int i = 0; i < 8; i++) {
         helloPacket->setAuthentication(i, authenticationKey.bytes[i]);
     }
     setOspfCrc(helloPacket, crcMode);
     Packet *pk = new Packet();
     pk->insertAtBack(helloPacket);
     parentArea->getRouter()->getMessageHandler()->sendPacket(pk, destination, this, ttl);
 }
Referenced by inet::ospfv2::InterfaceStateBackup::processEvent(), inet::ospfv2::NeighborStateDown::processEvent(), inet::ospfv2::InterfaceStateWaiting::processEvent(), inet::ospfv2::InterfaceStatePointToPoint::processEvent(), inet::ospfv2::InterfaceStateNotDesignatedRouter::processEvent(), inet::ospfv2::InterfaceStateDesignatedRouter::processEvent(), and inet::ospfv2::HelloHandler::processPacket().
sendLsAcknowledgement()
void inet::ospfv2::Ospfv2Interface::sendLsAcknowledgement (const Ospfv2LsaHeader * lsaHeader, Ipv4Address destination)
 {
     Ospfv2Options options;
     const auto& lsAckPacket = makeShared<Ospfv2LinkStateAcknowledgementPacket>();
     lsAckPacket->setType(LINKSTATE_ACKNOWLEDGEMENT_PACKET);
     lsAckPacket->setRouterID(Ipv4Address(parentArea->getRouter()->getRouterID()));
     lsAckPacket->setAreaID(Ipv4Address(parentArea->getAreaID()));
     lsAckPacket->setAuthenticationType(authenticationType);
     lsAckPacket->setLsaHeadersArraySize(1);
     lsAckPacket->setLsaHeaders(0, *lsaHeader);
     lsAckPacket->setPacketLengthField(B(OSPFv2_HEADER_LENGTH + OSPFv2_LSA_HEADER_LENGTH).get());
     lsAckPacket->setChunkLength(B(lsAckPacket->getPacketLengthField()));
     for (int i = 0; i < 8; i++) {
         lsAckPacket->setAuthentication(i, authenticationKey.bytes[i]);
     }
     setOspfCrc(lsAckPacket, crcMode);
     Packet *pk = new Packet();
     pk->insertAtBack(lsAckPacket);
     int ttl = (interfaceType == Ospfv2Interface::VIRTUAL) ? VIRTUAL_LINK_TTL : 1;
     parentArea->getRouter()->getMessageHandler()->sendPacket(pk, destination, this, ttl);
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::processPacket().
setAcknowledgementDelay()
void inet::ospfv2::Ospfv2Interface::setAcknowledgementDelay (short delay) inline
 { acknowledgementDelay = delay; }
setAddressRange()
void inet::ospfv2::Ospfv2Interface::setAddressRange (Ipv4AddressRange range) inline
 { interfaceAddressRange = range; }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree().
setArea()
void inet::ospfv2::Ospfv2Interface::setArea (Ospfv2Area * area) inline
 { parentArea = area; }
Referenced by inet::ospfv2::Ospfv2Area::addInterface().
setAreaId()
void inet::ospfv2::Ospfv2Interface::setAreaId (AreaId areaId) inline
 { areaID = areaId; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters().
setAuthenticationKey()
void inet::ospfv2::Ospfv2Interface::setAuthenticationKey (AuthenticationKeyType key) inline
 { authenticationKey = key; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadAuthenticationConfig().
setAuthenticationType()
void inet::ospfv2::Ospfv2Interface::setAuthenticationType (AuthenticationType type) inline
 { authenticationType = type; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadAuthenticationConfig().
setCrcMode()
void inet::ospfv2::Ospfv2Interface::setCrcMode (CrcMode crcMode) inline
 { this->crcMode = crcMode; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setHelloInterval()
void inet::ospfv2::Ospfv2Interface::setHelloInterval (short interval) inline
 { helloInterval = interval; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setIfIndex()
void inet::ospfv2::Ospfv2Interface::setIfIndex (IInterfaceTable * ift, int index)
 {
     ifIndex = index;
     if (interfaceType == Ospfv2Interface::UNKNOWN_TYPE) {
         NetworkInterface *routingInterface = ift->getInterfaceById(ifIndex);
         interfaceAddressRange.address = routingInterface->getProtocolData<Ipv4InterfaceData>()->getIPAddress();
         interfaceAddressRange.mask = routingInterface->getProtocolData<Ipv4InterfaceData>()->getNetmask();
         mtu = routingInterface->getMtu();
     }
 }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), and inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters().
setInterfaceName()
void inet::ospfv2::Ospfv2Interface::setInterfaceName (std::string ifName) inline
 { this->interfaceName = ifName; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setMode()
void inet::ospfv2::Ospfv2Interface::setMode (Ospfv2InterfaceMode intfMode) inline
 { interfaceMode = intfMode; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters().
setMtu()
void inet::ospfv2::Ospfv2Interface::setMtu (unsigned short ifMTU) inline
 { mtu = ifMTU; }
setOutputCost()
void inet::ospfv2::Ospfv2Interface::setOutputCost (Metric cost) inline
 { interfaceOutputCost = cost; }
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), and inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters().
setPollInterval()
void inet::ospfv2::Ospfv2Interface::setPollInterval (short interval) inline
 { pollInterval = interval; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters().
setRetransmissionInterval()
void inet::ospfv2::Ospfv2Interface::setRetransmissionInterval (short interval) inline
 { retransmissionInterval = interval; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setRouterDeadInterval()
void inet::ospfv2::Ospfv2Interface::setRouterDeadInterval (short interval) inline
 { routerDeadInterval = interval; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setRouterPriority()
void inet::ospfv2::Ospfv2Interface::setRouterPriority (unsigned char priority) inline
 { routerPriority = priority; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters().
setTransitAreaId()
void inet::ospfv2::Ospfv2Interface::setTransitAreaId (AreaId areaId) inline
 { transitAreaID = areaId; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setTransmissionDelay()
void inet::ospfv2::Ospfv2Interface::setTransmissionDelay (short delay) inline
 { interfaceTransmissionDelay = delay; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
setType()
void inet::ospfv2::Ospfv2Interface::setType (Ospfv2InterfaceType ifType) inline
 { interfaceType = ifType; }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & stream, const Ospfv2Interface & intf) friend
 {
     std::string neighbors = "";
     for (auto& neighbor : intf.neighboringRoutersByID) {
         std::string neighborState = Neighbor::getStateString((neighbor.second)->getState());
         neighbors = neighbors + (neighbor.first).str() + "(" + neighborState + ") ";
     }
     return stream << "name: " << intf.getInterfaceName() << " "
                   << "index: " << intf.ifIndex << " "
                   << "type: '" << intf.getTypeString(intf.interfaceType) << "' "
                   << "MTU: " << intf.mtu << " "
                   << "state: '" << intf.getStateString(intf.state->getState()) << "' "
                   << "mode: '" << intf.getModeString(intf.interfaceMode) << "' "
                   << "cost: " << intf.interfaceOutputCost << " "
                   << "area: " << intf.areaID.str(false) << " "
                   << "transitArea: " << intf.transitAreaID.str(false) << " "
                   << "helloInterval: " << intf.helloInterval << " "
                   << "pollInterval: " << intf.pollInterval << " "
                   << "routerDeadInterval: " << intf.routerDeadInterval << " "
                   << "retransmissionInterval: " << intf.retransmissionInterval << " "
                   << "acknowledgementDelay: " << intf.acknowledgementDelay << " "
                   << "interfaceTransmissionDelay: " << intf.interfaceTransmissionDelay << " "
                   << "neighboringRouters: " << ((neighbors == "") ? "<none>(down)" : neighbors) << " "
                   << "routerPriority: " << (int)(intf.routerPriority) << " "
                   << "designatedRouterID: " << intf.designatedRouter.routerID << " "
                   << "designatedRouterInterface: " << intf.designatedRouter.ipInterfaceAddress << " "
                   << "backupDesignatedRouterID: " << intf.backupDesignatedRouter.routerID << " "
                   << "backupDesignatedRouterInterface: " << intf.backupDesignatedRouter.ipInterfaceAddress;
 }
Ospfv2InterfaceState
friend class Ospfv2InterfaceState friend
Member Data Documentation
acknowledgementDelay
short inet::ospfv2::Ospfv2Interface::acknowledgementDelay private
Referenced by inet::ospfv2::operator<<(), and sendDelayedAcknowledgements().
acknowledgementTimer
cMessage* inet::ospfv2::Ospfv2Interface::acknowledgementTimer private
Referenced by Ospfv2Interface(), reset(), sendDelayedAcknowledgements(), and ~Ospfv2Interface().
areaID
AreaId inet::ospfv2::Ospfv2Interface::areaID private
Referenced by createUpdatePacket(), floodLsa(), inet::ospfv2::operator<<(), and sendDelayedAcknowledgements().
authenticationKey
AuthenticationKeyType inet::ospfv2::Ospfv2Interface::authenticationKey private
Referenced by createUpdatePacket(), Ospfv2Interface(), sendDelayedAcknowledgements(), sendHelloPacket(), and sendLsAcknowledgement().
authenticationType
AuthenticationType inet::ospfv2::Ospfv2Interface::authenticationType private
Referenced by createUpdatePacket(), sendDelayedAcknowledgements(), sendHelloPacket(), and sendLsAcknowledgement().
backupDesignatedRouter
DesignatedRouterId inet::ospfv2::Ospfv2Interface::backupDesignatedRouter private
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), floodLsa(), inet::ospfv2::operator<<(), reset(), and sendHelloPacket().
crcMode
CrcMode inet::ospfv2::Ospfv2Interface::crcMode private
Referenced by createUpdatePacket(), sendDelayedAcknowledgements(), sendHelloPacket(), and sendLsAcknowledgement().
delayedAcknowledgements
std::map<Ipv4Address, std::list<Ospfv2LsaHeader> > inet::ospfv2::Ospfv2Interface::delayedAcknowledgements private
Referenced by addDelayedAcknowledgement(), and sendDelayedAcknowledgements().
designatedRouter
DesignatedRouterId inet::ospfv2::Ospfv2Interface::designatedRouter private
Referenced by addDelayedAcknowledgement(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), floodLsa(), inet::ospfv2::operator<<(), reset(), sendDelayedAcknowledgements(), and sendHelloPacket().
helloInterval
short inet::ospfv2::Ospfv2Interface::helloInterval private
Referenced by inet::ospfv2::operator<<(), and sendHelloPacket().
helloTimer
cMessage* inet::ospfv2::Ospfv2Interface::helloTimer private
Referenced by Ospfv2Interface(), reset(), and ~Ospfv2Interface().
ifIndex
int inet::ospfv2::Ospfv2Interface::ifIndex private
Referenced by inet::ospfv2::operator<<(), and setIfIndex().
interfaceAddressRange
Ipv4AddressRange inet::ospfv2::Ospfv2Interface::interfaceAddressRange private
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), sendHelloPacket(), and setIfIndex().
interfaceMode
Ospfv2InterfaceMode inet::ospfv2::Ospfv2Interface::interfaceMode private
Referenced by inet::ospfv2::operator<<().
interfaceName
std::string inet::ospfv2::Ospfv2Interface::interfaceName private
interfaceOutputCost
Metric inet::ospfv2::Ospfv2Interface::interfaceOutputCost private
Referenced by inet::ospfv2::operator<<().
interfaceTransmissionDelay
short inet::ospfv2::Ospfv2Interface::interfaceTransmissionDelay private
Referenced by createUpdatePacket(), and inet::ospfv2::operator<<().
interfaceType
Ospfv2InterfaceType inet::ospfv2::Ospfv2Interface::interfaceType private
Referenced by addDelayedAcknowledgement(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), floodLsa(), inet::ospfv2::operator<<(), sendDelayedAcknowledgements(), sendHelloPacket(), sendLsAcknowledgement(), and setIfIndex().
mtu
unsigned short inet::ospfv2::Ospfv2Interface::mtu private
Referenced by inet::ospfv2::operator<<(), sendDelayedAcknowledgements(), and setIfIndex().
neighboringRouters
std::vector<Neighbor *> inet::ospfv2::Ospfv2Interface::neighboringRouters private
Referenced by addDelayedAcknowledgement(), addNeighbor(), ageTransmittedLsaLists(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), floodLsa(), hasAnyNeighborInStates(), isOnAnyRetransmissionList(), removeFromAllRetransmissionLists(), reset(), sendHelloPacket(), and ~Ospfv2Interface().
neighboringRoutersByAddress
std::map<Ipv4Address, Neighbor *> inet::ospfv2::Ospfv2Interface::neighboringRoutersByAddress private
Referenced by addNeighbor(), and getNeighborByAddress().
neighboringRoutersByID
std::map<RouterId, Neighbor *> inet::ospfv2::Ospfv2Interface::neighboringRoutersByID private
Referenced by addNeighbor(), getNeighborById(), and inet::ospfv2::operator<<().
parentArea
Ospfv2Area* inet::ospfv2::Ospfv2Interface::parentArea private
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), createUpdatePacket(), floodLsa(), reset(), sendDelayedAcknowledgements(), sendHelloPacket(), sendLsAcknowledgement(), and ~Ospfv2Interface().
pollInterval
short inet::ospfv2::Ospfv2Interface::pollInterval private
Referenced by inet::ospfv2::operator<<().
previousState
Ospfv2InterfaceState* inet::ospfv2::Ospfv2Interface::previousState private
Referenced by changeState(), Ospfv2Interface(), and ~Ospfv2Interface().
retransmissionInterval
short inet::ospfv2::Ospfv2Interface::retransmissionInterval private
Referenced by inet::ospfv2::operator<<().
routerDeadInterval
short inet::ospfv2::Ospfv2Interface::routerDeadInterval private
Referenced by inet::ospfv2::operator<<(), and sendHelloPacket().
routerPriority
unsigned char inet::ospfv2::Ospfv2Interface::routerPriority private
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::operator<<(), and sendHelloPacket().
state
Ospfv2InterfaceState* inet::ospfv2::Ospfv2Interface::state private
Referenced by changeState(), getState(), inet::ospfv2::operator<<(), Ospfv2Interface(), processEvent(), and ~Ospfv2Interface().
transitAreaID
AreaId inet::ospfv2::Ospfv2Interface::transitAreaID private
Referenced by inet::ospfv2::operator<<().
waitTimer
cMessage* inet::ospfv2::Ospfv2Interface::waitTimer private
Referenced by Ospfv2Interface(), reset(), and ~Ospfv2Interface().
The documentation for this class was generated from the following files:
Ospfv2Interface.h
Ospfv2Interface.cc