INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211TransmitterBase Class Reference
inet::physicallayer::Ieee80211TransmitterBase Class Reference
#include <Ieee80211TransmitterBase.h>
Public Member Functions
Ieee80211TransmitterBase ()
virtual ~Ieee80211TransmitterBase ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IIeee80211Mode * computeTransmissionMode (const Packet *packet) const
virtual const Ieee80211Channel * computeTransmissionChannel (const Packet *packet) const
virtual void setModeSet (const Ieee80211ModeSet *modeSet)
virtual void setMode (const IIeee80211Mode *mode)
virtual void setBand (const IIeee80211Band *band)
virtual void setChannel (const Ieee80211Channel *channel)
virtual void setChannelNumber (int channelNumber)
Public Member Functions inherited from inet::physicallayer::FlatTransmitterBase
FlatTransmitterBase ()
virtual b getHeaderLength () const
virtual void setHeaderLength (b headerLength)
virtual bps getBitrate () const
virtual void setBitrate (bps bitrate)
virtual W getMaxPower () const override
Returns the maximum transmission power above which no transmission is ever transmitted.
virtual W getPower () const
virtual void setPower (W power)
Public Member Functions inherited from inet::physicallayer::NarrowbandTransmitterBase
NarrowbandTransmitterBase ()
virtual const IModulation * getModulation () const
virtual void setModulation (const IModulation *modulation)
virtual Hz getCenterFrequency () const
virtual void setCenterFrequency (Hz centerFrequency)
virtual Hz getBandwidth () const
virtual void setBandwidth (Hz bandwidth)
Public Member Functions inherited from inet::physicallayer::TransmitterBase
virtual m getMaxCommunicationRange () const override
Returns the maximum communication range.
virtual m getMaxInterferenceRange () const override
Returns the maximum interference range.
Public Member Functions inherited from inet::physicallayer::ITransmitter
virtual const ITransmission * createTransmission (const IRadio *transmitter, const Packet *packet, const simtime_t startTime) const =0
Returns a transmission which describes the radio signal corresponding to the provided packet.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
Protected Member Functions inherited from inet::physicallayer::FlatTransmitterBase
virtual bps computeTransmissionPreambleBitrate (const Packet *packet) const
virtual bps computeTransmissionHeaderBitrate (const Packet *packet) const
virtual bps computeTransmissionDataBitrate (const Packet *packet) const
virtual W computeTransmissionPower (const Packet *packet) const
Protected Member Functions inherited from inet::physicallayer::NarrowbandTransmitterBase
virtual Hz computeCenterFrequency (const Packet *packet) const
virtual Hz computeBandwidth (const Packet *packet) const
Protected Member Functions inherited from inet::physicallayer::TransmitterBase
virtual int numInitStages () const override
Protected Attributes
const Ieee80211ModeSet * modeSet
const IIeee80211Mode * mode
const IIeee80211Band * band
const Ieee80211Channel * channel
Protected Attributes inherited from inet::physicallayer::FlatTransmitterBase
simtime_t preambleDuration
b headerLength
bps bitrate
W power
Protected Attributes inherited from inet::physicallayer::NarrowbandTransmitterBase
const IModulation * modulation
Hz centerFrequency
Hz bandwidth
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211TransmitterBase()
inet::physicallayer::Ieee80211TransmitterBase::Ieee80211TransmitterBase ()
                                                    :
     modeSet(nullptr),
     mode(nullptr),
     band(nullptr),
     channel(nullptr)
 {
 }
~Ieee80211TransmitterBase()
inet::physicallayer::Ieee80211TransmitterBase::~Ieee80211TransmitterBase () virtual
 {
     delete channel;
 }
Member Function Documentation
computeTransmissionChannel()
const Ieee80211Channel * inet::physicallayer::Ieee80211TransmitterBase::computeTransmissionChannel (const Packet * packet) const virtual
 {
     const Ieee80211Channel *transmissionChannel;
     const auto& channelReq = const_cast<Packet *>(packet)->findTag<Ieee80211ChannelReq>();
     transmissionChannel = channelReq != nullptr ? channelReq->getChannel() : channel;
     if (transmissionChannel == nullptr)
         throw cRuntimeError("Transmission channel is undefined");
     return transmissionChannel;
 }
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), and inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission().
computeTransmissionMode()
const IIeee80211Mode * inet::physicallayer::Ieee80211TransmitterBase::computeTransmissionMode (const Packet * packet) const virtual
 {
     const IIeee80211Mode *transmissionMode;
     const auto& modeReq = const_cast<Packet *>(packet)->findTag<Ieee80211ModeReq>();
     const auto& bitrateReq = const_cast<Packet *>(packet)->findTag<SignalBitrateReq>();
     if (modeReq != nullptr) {
         if (modeSet != nullptr && !modeSet->containsMode(modeReq->getMode()))
             throw cRuntimeError("Unsupported mode requested");
         transmissionMode = modeReq->getMode();
     }
     else if (modeSet != nullptr && bitrateReq != nullptr)
         transmissionMode = modeSet->getMode(bitrateReq->getDataBitrate());
     else
         transmissionMode = mode;
     if (transmissionMode == nullptr)
         throw cRuntimeError("Transmission mode is undefined");
     return transmissionMode;
 }
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
initialize()
void inet::physicallayer::Ieee80211TransmitterBase::initialize (int stage) override protected virtual
Reimplemented from inet::physicallayer::FlatTransmitterBase.
Reimplemented in inet::physicallayer::Ieee80211UnitDiskTransmitter, and inet::physicallayer::Ieee80211DimensionalTransmitter.
 {
     FlatTransmitterBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         const char *opMode = par("opMode");
         setModeSet(*opMode ? Ieee80211ModeSet::getModeSet(opMode) : nullptr);
         const char *bandName = par("bandName");
         setBand(*bandName != '\0' ? Ieee80211CompliantBands::getBand(bandName) : nullptr);
         setMode(modeSet != nullptr ? (bitrate != bps(-1) ? modeSet->getMode(bitrate, bandwidth) : modeSet->getFastestMode()) : nullptr);
         int channelNumber = par("channelNumber");
         if (channelNumber != -1)
             setChannelNumber(channelNumber);
     }
 }
Referenced by inet::physicallayer::Ieee80211DimensionalTransmitter::initialize(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::initialize().
printToStream()
std::ostream & inet::physicallayer::Ieee80211TransmitterBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::physicallayer::FlatTransmitterBase.
Reimplemented in inet::physicallayer::Ieee80211UnitDiskTransmitter, inet::physicallayer::Ieee80211DimensionalTransmitter, and inet::physicallayer::Ieee80211ScalarTransmitter.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(modeSet, printFieldToString(modeSet, level + 1, evFlags))
                << EV_FIELD(band, printFieldToString(band, level + 1, evFlags));
     if (level <= PRINT_LEVEL_INFO)
         stream << EV_FIELD(mode, printFieldToString(mode, level + 1, evFlags))
                << EV_FIELD(channel, printFieldToString(channel, level + 1, evFlags));
     return FlatTransmitterBase::printToStream(stream, level);
 }
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::printToStream(), inet::physicallayer::Ieee80211DimensionalTransmitter::printToStream(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::printToStream().
setBand()
void inet::physicallayer::Ieee80211TransmitterBase::setBand (const IIeee80211Band * band) virtual
 {
     if (this->band != band) {
         this->band = band;
         if (channel != nullptr)
             setChannel(new Ieee80211Channel(band, channel->getChannelNumber()));
     }
 }
Referenced by initialize(), and inet::physicallayer::Ieee80211Radio::setBand().
setChannel()
void inet::physicallayer::Ieee80211TransmitterBase::setChannel (const Ieee80211Channel * channel) virtual
 {
     if (this->channel != channel) {
         delete this->channel;
         this->channel = channel;
         setCenterFrequency(channel->getCenterFrequency());
     }
 }
Referenced by setBand(), inet::physicallayer::Ieee80211Radio::setChannel(), and setChannelNumber().
setChannelNumber()
void inet::physicallayer::Ieee80211TransmitterBase::setChannelNumber (int channelNumber) virtual
 {
     if (channel == nullptr || channelNumber != channel->getChannelNumber())
         setChannel(new Ieee80211Channel(band, channelNumber));
 }
Referenced by initialize(), and inet::physicallayer::Ieee80211Radio::setChannelNumber().
setMode()
void inet::physicallayer::Ieee80211TransmitterBase::setMode (const IIeee80211Mode * mode) virtual
 {
     if (this->mode != mode) {
         if (modeSet->findMode(mode->getDataMode()->getNetBitrate(), mode->getDataMode()->getBandwidth()) == nullptr)
             throw cRuntimeError("Invalid mode");
         this->mode = mode;
     }
 }
Referenced by initialize(), and inet::physicallayer::Ieee80211Radio::setMode().
setModeSet()
void inet::physicallayer::Ieee80211TransmitterBase::setModeSet (const Ieee80211ModeSet * modeSet) virtual
 {
     if (this->modeSet != modeSet) {
         this->modeSet = modeSet;
         if (mode != nullptr)
             mode = modeSet != nullptr ? modeSet->getMode(mode->getDataMode()->getNetBitrate()) : nullptr;
     }
 }
Referenced by initialize(), and inet::physicallayer::Ieee80211Radio::setModeSet().
Member Data Documentation
band
const IIeee80211Band* inet::physicallayer::Ieee80211TransmitterBase::band protected
Referenced by printToStream(), setBand(), and setChannelNumber().
channel
const Ieee80211Channel* inet::physicallayer::Ieee80211TransmitterBase::channel protected
Referenced by computeTransmissionChannel(), inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission(), printToStream(), setBand(), setChannel(), setChannelNumber(), and ~Ieee80211TransmitterBase().
mode
const IIeee80211Mode* inet::physicallayer::Ieee80211TransmitterBase::mode protected
Referenced by computeTransmissionMode(), printToStream(), setMode(), and setModeSet().
modeSet
const Ieee80211ModeSet* inet::physicallayer::Ieee80211TransmitterBase::modeSet protected
Referenced by computeTransmissionMode(), initialize(), printToStream(), setMode(), and setModeSet().
The documentation for this class was generated from the following files:
Ieee80211TransmitterBase.h
Ieee80211TransmitterBase.cc