INET Framework for OMNeT++/OMNEST: inet::ChunkBuffer::Region Class Reference
inet::ChunkBuffer::Region Class Reference
#include <ChunkBuffer.h>
Public Member Functions
Region (b offset, const Ptr< const Chunk > &data)
Region (const Region &other)
b getStartOffset () const
b getEndOffset () const
Static Public Member Functions
static bool compareStartOffset (const Region &a, const Region &b)
static bool compareEndOffset (const Region &a, const Region &b)
Public Attributes
b offset
Ptr< const Chunk > data
This chunk is always immutable to allow arbitrary peeking.
Protected Member Functions
const Chunk * getData () const
Friends
class ChunkBuffer__RegionDescriptor
Constructor & Destructor Documentation
Region() [1/2]
inet::ChunkBuffer::Region::Region (b offset, const Ptr< const Chunk > & data) inline
 : offset(offset), data(data) {}
Region() [2/2]
inet::ChunkBuffer::Region::Region (const Region & other) inline
 : offset(other.offset), data(other.data) {}
Member Function Documentation
compareEndOffset()
static bool inet::ChunkBuffer::Region::compareEndOffset (const Region & a, const Region & b) inline static
 { return a.getEndOffset() < b.getEndOffset(); }
Referenced by inet::ChunkBuffer::sliceRegions().
compareStartOffset()
static bool inet::ChunkBuffer::Region::compareStartOffset (const Region & a, const Region & b) inline static
 { return a.getStartOffset() < b.getStartOffset(); }
Referenced by inet::ChunkBuffer::replace(), and inet::ChunkBuffer::sliceRegions().
getData()
const Chunk* inet::ChunkBuffer::Region::getData () const inline protected
 { return data.get(); } // only for class descriptor
getEndOffset()
b inet::ChunkBuffer::Region::getEndOffset () const inline
 { return offset + data->getChunkLength(); }
Referenced by compareEndOffset(), inet::ChunkBuffer::mergeRegions(), and inet::ChunkBuffer::sliceRegions().
getStartOffset()
b inet::ChunkBuffer::Region::getStartOffset () const inline
 { return offset; }
Referenced by compareStartOffset(), inet::ChunkBuffer::mergeRegions(), and inet::ChunkBuffer::sliceRegions().
Friends And Related Function Documentation
ChunkBuffer__RegionDescriptor
friend class ChunkBuffer__RegionDescriptor friend
Member Data Documentation
data
Ptr<const Chunk> inet::ChunkBuffer::Region::data
This chunk is always immutable to allow arbitrary peeking.
Nevertheless it's reused if possible to allow efficient merging with newly added chunks.
Referenced by inet::ChunkBuffer::eraseEmptyRegions(), inet::ChunkBuffer::mergeRegions(), and inet::ChunkBuffer::sliceRegions().
offset
b inet::ChunkBuffer::Region::offset
Referenced by inet::ChunkBuffer::mergeRegions(), and inet::ChunkBuffer::sliceRegions().
The documentation for this class was generated from the following file:
ChunkBuffer.h