INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAuthenticationChunk Class Reference
inet::sctp::SctpAuthenticationChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:294 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpAuthenticationChunk (const char *name=nullptr)
SctpAuthenticationChunk (const SctpAuthenticationChunk &other)
virtual ~SctpAuthenticationChunk ()
SctpAuthenticationChunk & operator= (const SctpAuthenticationChunk &other)
virtual SctpAuthenticationChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getSharedKey () const
virtual void setSharedKey (uint16_t sharedKey)
virtual uint16_t getHMacIdentifier () const
virtual void setHMacIdentifier (uint16_t hMacIdentifier)
virtual bool getHMacOk () const
virtual void setHMacOk (bool hMacOk)
virtual void setHMACArraySize (size_t size)
virtual size_t getHMACArraySize () const
virtual uint32_t getHMAC (size_t k) const
virtual void setHMAC (size_t k, uint32_t HMAC)
virtual void insertHMAC (size_t k, uint32_t HMAC)
void insertHMAC (uint32_t HMAC)
virtual void appendHMAC (uint32_t HMAC)
virtual void eraseHMAC (size_t k)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpAuthenticationChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint16_t sharedKey = 0
uint16_t hMacIdentifier = 0
bool hMacOk = false
uint32_t * HMAC = nullptr
size_t HMAC_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpAuthenticationChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:294 by opp_msgtool.
class SctpAuthenticationChunk extends SctpChunk
{
    uint16_t sharedKey;
    uint16_t hMacIdentifier;
    bool hMacOk;
    uint32_t HMAC[];
}
Constructor & Destructor Documentation
SctpAuthenticationChunk() [1/2]
inet::sctp::SctpAuthenticationChunk::SctpAuthenticationChunk (const char * name = nullptr)
SctpAuthenticationChunk() [2/2]
inet::sctp::SctpAuthenticationChunk::SctpAuthenticationChunk (const SctpAuthenticationChunk & other)
~SctpAuthenticationChunk()
virtual inet::sctp::SctpAuthenticationChunk::~SctpAuthenticationChunk () virtual
Member Function Documentation
appendHMAC()
virtual void inet::sctp::SctpAuthenticationChunk::appendHMAC (uint32_t HMAC) virtual
copy()
void inet::sctp::SctpAuthenticationChunk::copy (const SctpAuthenticationChunk & other) private
dup()
virtual SctpAuthenticationChunk* inet::sctp::SctpAuthenticationChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpAuthenticationChunk(*this);}
eraseHMAC()
virtual void inet::sctp::SctpAuthenticationChunk::eraseHMAC (size_t k) virtual
getHMAC()
virtual uint32_t inet::sctp::SctpAuthenticationChunk::getHMAC (size_t k) const virtual
getHMACArraySize()
virtual size_t inet::sctp::SctpAuthenticationChunk::getHMACArraySize () const virtual
getHMacIdentifier()
virtual uint16_t inet::sctp::SctpAuthenticationChunk::getHMacIdentifier () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getHMacOk()
virtual bool inet::sctp::SctpAuthenticationChunk::getHMacOk () const virtual
getSharedKey()
virtual uint16_t inet::sctp::SctpAuthenticationChunk::getSharedKey () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
insertHMAC() [1/2]
virtual void inet::sctp::SctpAuthenticationChunk::insertHMAC (size_t k, uint32_t HMAC) virtual
insertHMAC() [2/2]
void inet::sctp::SctpAuthenticationChunk::insertHMAC (uint32_t HMAC) inline
 {appendHMAC(HMAC);}
operator=()
SctpAuthenticationChunk& inet::sctp::SctpAuthenticationChunk::operator= (const SctpAuthenticationChunk & other)
operator==()
bool inet::sctp::SctpAuthenticationChunk::operator== (const SctpAuthenticationChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpAuthenticationChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpAuthenticationChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setHMAC()
virtual void inet::sctp::SctpAuthenticationChunk::setHMAC (size_t k, uint32_t HMAC) virtual
Referenced by inet::sctp::SctpAssociation::createAuthChunk().
setHMACArraySize()
virtual void inet::sctp::SctpAuthenticationChunk::setHMACArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::createAuthChunk().
setHMacIdentifier()
virtual void inet::sctp::SctpAuthenticationChunk::setHMacIdentifier (uint16_t hMacIdentifier) virtual
Referenced by inet::sctp::SctpAssociation::createAuthChunk().
setHMacOk()
virtual void inet::sctp::SctpAuthenticationChunk::setHMacOk (bool hMacOk) virtual
Referenced by inet::sctp::SctpAssociation::createAuthChunk().
setSharedKey()
virtual void inet::sctp::SctpAuthenticationChunk::setSharedKey (uint16_t sharedKey) virtual
Referenced by inet::sctp::SctpAssociation::createAuthChunk().
Member Data Documentation
HMAC
uint32_t* inet::sctp::SctpAuthenticationChunk::HMAC = nullptr protected
HMAC_arraysize
size_t inet::sctp::SctpAuthenticationChunk::HMAC_arraysize = 0 protected
hMacIdentifier
uint16_t inet::sctp::SctpAuthenticationChunk::hMacIdentifier = 0 protected
hMacOk
bool inet::sctp::SctpAuthenticationChunk::hMacOk = false protected
sharedKey
uint16_t inet::sctp::SctpAuthenticationChunk::sharedKey = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h