INET Framework for OMNeT++/OMNEST: inet::NetworkProtocolInd Class Reference
inet::NetworkProtocolInd Class Reference
Class generated from inet/common/ProtocolTag.msg:198 by opp_msgtool.
#include <ProtocolTag_m.h>
Public Member Functions
NetworkProtocolInd ()
NetworkProtocolInd (const NetworkProtocolInd &other)
virtual ~NetworkProtocolInd ()
NetworkProtocolInd & operator= (const NetworkProtocolInd &other)
virtual NetworkProtocolInd * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ChunkPtr & getNetworkProtocolHeader () const
virtual ChunkPtr & getNetworkProtocolHeaderForUpdate ()
virtual void setNetworkProtocolHeader (const ChunkPtr &networkProtocolHeader)
Public Member Functions inherited from inet::ProtocolTagBase
ProtocolTagBase ()
ProtocolTagBase (const ProtocolTagBase &other)
virtual ~ProtocolTagBase ()
ProtocolTagBase & operator= (const ProtocolTagBase &other)
virtual const Protocol * findProtocol () const
virtual void setProtocol (const Protocol *protocol)
const Protocol * getProtocol () const
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const NetworkProtocolInd &)=delete
Protected Member Functions inherited from inet::ProtocolTagBase
bool operator== (const ProtocolTagBase &)=delete
Protected Attributes
ChunkPtr networkProtocolHeader
Protected Attributes inherited from inet::ProtocolTagBase
const Protocol * protocol = nullptr
Private Member Functions
void copy (const NetworkProtocolInd &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/common/ProtocolTag.msg:198 by opp_msgtool.
//
// This indication specifies the network protocol that was used to receive the
// packet. It may be present from the network protocol to the application.
//
class NetworkProtocolInd extends ProtocolTagBase
{
    ChunkPtr networkProtocolHeader;
}
Constructor & Destructor Documentation
NetworkProtocolInd() [1/2]
inet::NetworkProtocolInd::NetworkProtocolInd ()
NetworkProtocolInd() [2/2]
inet::NetworkProtocolInd::NetworkProtocolInd (const NetworkProtocolInd & other)
~NetworkProtocolInd()
virtual inet::NetworkProtocolInd::~NetworkProtocolInd () virtual
Member Function Documentation
copy()
void inet::NetworkProtocolInd::copy (const NetworkProtocolInd & other) private
dup()
virtual NetworkProtocolInd* inet::NetworkProtocolInd::dup () const inline override virtual
Reimplemented from inet::ProtocolTagBase.
 {return new NetworkProtocolInd(*this);}
getNetworkProtocolHeader()
virtual const ChunkPtr& inet::NetworkProtocolInd::getNetworkProtocolHeader () const virtual
Referenced by inet::findNetworkProtocolHeader(), and inet::Udp::processUndeliverablePacket().
getNetworkProtocolHeaderForUpdate()
virtual ChunkPtr& inet::NetworkProtocolInd::getNetworkProtocolHeaderForUpdate () inline virtual
 { return const_cast<ChunkPtr&>(const_cast<NetworkProtocolInd*>(this)->getNetworkProtocolHeader());}
operator=()
NetworkProtocolInd& inet::NetworkProtocolInd::operator= (const NetworkProtocolInd & other)
operator==()
bool inet::NetworkProtocolInd::operator== (const NetworkProtocolInd &) protected delete
parsimPack()
virtual void inet::NetworkProtocolInd::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ProtocolTagBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::NetworkProtocolInd::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ProtocolTagBase.
Referenced by inet::doParsimUnpacking().
setNetworkProtocolHeader()
virtual void inet::NetworkProtocolInd::setNetworkProtocolHeader (const ChunkPtr & networkProtocolHeader) virtual
Member Data Documentation
networkProtocolHeader
ChunkPtr inet::NetworkProtocolInd::networkProtocolHeader protected
The documentation for this class was generated from the following file:
ProtocolTag_m.h