INET Framework for OMNeT++/OMNEST: inet::physicallayer::IWirelessSignal Class Reference
inet::physicallayer::IWirelessSignal Class Reference abstract
This purely virtual interface provides an abstraction for different signals.
#include <IWirelessSignal.h>
Public Member Functions
virtual const ITransmission * getTransmission () const =0
Returns the radio signal transmission that this signal represents.
virtual const IArrival * getArrival () const =0
This function may return nullptr if this is not yet computed.
virtual const IListening * getListening () const =0
This function may return nullptr if this is not yet computed.
virtual const IReception * getReception () const =0
This function may return nullptr if this is not yet computed.
Public Member Functions inherited from inet::IPhysicalLayerFrame
virtual ~IPhysicalLayerFrame ()
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This purely virtual interface provides an abstraction for different signals.
Member Function Documentation
getArrival()
virtual const IArrival* inet::physicallayer::IWirelessSignal::getArrival () const pure virtual
This function may return nullptr if this is not yet computed.
Implemented in inet::physicallayer::WirelessSignal.
getListening()
virtual const IListening* inet::physicallayer::IWirelessSignal::getListening () const pure virtual
This function may return nullptr if this is not yet computed.
Implemented in inet::physicallayer::WirelessSignal.
getReception()
virtual const IReception* inet::physicallayer::IWirelessSignal::getReception () const pure virtual
This function may return nullptr if this is not yet computed.
Implemented in inet::physicallayer::WirelessSignal.
Referenced by inet::physicallayer::CommunicationLog::writeReception().
getTransmission()
virtual const ITransmission* inet::physicallayer::IWirelessSignal::getTransmission () const pure virtual
Returns the radio signal transmission that this signal represents.
This function never returns nullptr.
Implemented in inet::physicallayer::WirelessSignal.
Referenced by inet::physicallayer::RadioMedium::receivePacket(), inet::physicallayer::RadioMedium::sendToRadio(), inet::physicallayer::CommunicationLog::writeReception(), and inet::physicallayer::CommunicationLog::writeTransmission().
The documentation for this class was generated from the following file:
IWirelessSignal.h