INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211VhtDataMode Class Reference
inet::physicallayer::Ieee80211VhtDataMode Class Reference
#include <Ieee80211VhtMode.h>
Public Member Functions
Ieee80211VhtDataMode (const Ieee80211Vhtmcs *modulationAndCodingScheme, const Hz bandwidth, GuardIntervalType guardIntervalType)
b getServiceFieldLength () const
b getTailFieldLength () const
virtual int getNumberOfSpatialStreams () const override
virtual Hz getBandwidth () const override
virtual b getPaddingLength (b dataLength) const override
virtual b getCompleteLength (b dataLength) const override
virtual const simtime_t getDuration (b dataLength) const override
virtual bps getNetBitrate () const override
virtual bps getGrossBitrate () const override
virtual const Ieee80211Vhtmcs * getModulationAndCodingScheme () const
virtual const Ieee80211VhtCode * getCode () const
virtual const Ieee80211OfdmModulation * getModulation () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211VhtModeBase
Ieee80211VhtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
virtual int getNumberOfDataSubcarriers () const
virtual int getNumberOfPilotSubcarriers () const
virtual int getNumberOfTotalSubcarriers () const
virtual GuardIntervalType getGuardIntervalType () const
virtual unsigned int getMcsIndex () const
Public Member Functions inherited from inet::physicallayer::Ieee80211HtTimingRelatedParametersBase
const simtime_t getDFTPeriod () const
const simtime_t getGIDuration () const
const simtime_t getShortGIDuration () const
const simtime_t getSymbolInterval () const
const simtime_t getShortGISymbolInterval () const
Protected Member Functions
bps computeGrossBitrate () const override
bps computeNetBitrate () const override
unsigned int computeNumberOfSpatialStreams (const Ieee80211Vhtmcs *) const
unsigned int computeNumberOfCodedBitsPerSubcarrierSum () const
unsigned int computeNumberOfBccEncoders () const
unsigned int getNumberOfBccEncoders20MHz () const
unsigned int getNumberOfBccEncoders40MHz () const
unsigned int getNumberOfBccEncoders80MHz () const
unsigned int getNumberOfBccEncoders160MHz () const
Protected Attributes
const Ieee80211Vhtmcs * modulationAndCodingScheme
const unsigned int numberOfBccEncoders
Protected Attributes inherited from inet::physicallayer::Ieee80211VhtModeBase
const Hz bandwidth
const GuardIntervalType guardIntervalType
const unsigned int mcsIndex
const unsigned int numberOfSpatialStreams
bps netBitrate
bps grossBitrate
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Types inherited from inet::physicallayer::Ieee80211VhtModeBase
enum GuardIntervalType { HT_GUARD_INTERVAL_SHORT, HT_GUARD_INTERVAL_LONG }
Constructor & Destructor Documentation
Ieee80211VhtDataMode()
inet::physicallayer::Ieee80211VhtDataMode::Ieee80211VhtDataMode (const Ieee80211Vhtmcs * modulationAndCodingScheme, const Hz bandwidth, GuardIntervalType guardIntervalType)
                                                                                                                                                     :
     Ieee80211VhtModeBase(modulationAndCodingScheme->getMcsIndex(), computeNumberOfSpatialStreams(modulationAndCodingScheme), bandwidth, guardIntervalType),
     modulationAndCodingScheme(modulationAndCodingScheme),
     numberOfBccEncoders(computeNumberOfBccEncoders())
 {
 }
Member Function Documentation
computeGrossBitrate()
bps inet::physicallayer::Ieee80211VhtDataMode::computeGrossBitrate () const override protected virtual
Implements inet::physicallayer::Ieee80211VhtModeBase.
 {
     unsigned int numberOfCodedBitsPerSubcarrierSum = computeNumberOfCodedBitsPerSubcarrierSum();
     unsigned int numberOfCodedBitsPerSymbol = numberOfCodedBitsPerSubcarrierSum * getNumberOfDataSubcarriers();
     if (guardIntervalType == HT_GUARD_INTERVAL_LONG)
         return bps(numberOfCodedBitsPerSymbol / getSymbolInterval());
     else if (guardIntervalType == HT_GUARD_INTERVAL_SHORT)
         return bps(numberOfCodedBitsPerSymbol / getShortGISymbolInterval());
     else
         throw cRuntimeError("Unknown guard interval type");
 }
computeNetBitrate()
bps inet::physicallayer::Ieee80211VhtDataMode::computeNetBitrate () const override protected virtual
Implements inet::physicallayer::Ieee80211VhtModeBase.
 {
     return getGrossBitrate() * getCode()->getForwardErrorCorrection()->getCodeRate();
 }
computeNumberOfBccEncoders()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfBccEncoders () const protected
 {
     // When the BCC FEC encoder is used, a single encoder is used, except that two encoders
     // are used when the selected MCS has a PHY rate greater than 300 Mb/s (see 20.6).
     if (getBandwidth() == MHz(20)) {
         return getNumberOfBccEncoders20MHz();
     }
     else if (getBandwidth() == MHz(40)) {
         return getNumberOfBccEncoders40MHz();
     }
     else if (getBandwidth() == MHz(80)) {
         return getNumberOfBccEncoders80MHz();
     }
     else if (getBandwidth() == MHz(160)) {
         return getNumberOfBccEncoders160MHz();
     }
     else
         throw cRuntimeError("Invalid bandwidth evaluating  NumberOfBccEncoders");
 }
computeNumberOfCodedBitsPerSubcarrierSum()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum () const protected
 {
     return (modulationAndCodingScheme->getModulation() ? modulationAndCodingScheme->getModulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension1Modulation() ? modulationAndCodingScheme->getStreamExtension1Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension2Modulation() ? modulationAndCodingScheme->getStreamExtension2Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension3Modulation() ? modulationAndCodingScheme->getStreamExtension3Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension4Modulation() ? modulationAndCodingScheme->getStreamExtension4Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension5Modulation() ? modulationAndCodingScheme->getStreamExtension5Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension6Modulation() ? modulationAndCodingScheme->getStreamExtension6Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0) +
            (modulationAndCodingScheme->getStreamExtension7Modulation() ? modulationAndCodingScheme->getStreamExtension7Modulation()->getSubcarrierModulation()->getCodeWordSize() : 0);
 }
Referenced by computeGrossBitrate(), and getDuration().
computeNumberOfSpatialStreams()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfSpatialStreams (const Ieee80211Vhtmcs * vhtmcs) const protected
 {
     if (vhtmcs == nullptr)
         throw cRuntimeError("Invalid MCS mode");
     return vhtmcs->getNumNss();
 }
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211VhtDataMode::getBandwidth () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211VhtModeBase.
 { return bandwidth; }
Referenced by computeNumberOfBccEncoders().
getCode()
virtual const Ieee80211VhtCode* inet::physicallayer::Ieee80211VhtDataMode::getCode () const inline virtual
 { return modulationAndCodingScheme->getCode(); }
Referenced by computeNetBitrate(), and getDuration().
getCompleteLength()
b inet::physicallayer::Ieee80211VhtDataMode::getCompleteLength (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     return getServiceFieldLength() + getTailFieldLength() + dataLength; // TODO padding?
 }
Referenced by getDuration().
getDuration()
const simtime_t inet::physicallayer::Ieee80211VhtDataMode::getDuration (b dataLength) const override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 {
     unsigned int numberOfCodedBitsPerSubcarrierSum = computeNumberOfCodedBitsPerSubcarrierSum();
     unsigned int numberOfCodedBitsPerSymbol = numberOfCodedBitsPerSubcarrierSum * getNumberOfDataSubcarriers();
     const IForwardErrorCorrection *forwardErrorCorrection = getCode() ? getCode()->getForwardErrorCorrection() : nullptr;
     unsigned int dataBitsPerSymbol = forwardErrorCorrection ? forwardErrorCorrection->getDecodedLength(numberOfCodedBitsPerSymbol) : numberOfCodedBitsPerSymbol;
     int numberOfSymbols = lrint(ceil((double)getCompleteLength(dataLength).get() / dataBitsPerSymbol)); // TODO getBitLength(dataBitLength) should be divisible by dataBitsPerSymbol
     return numberOfSymbols * getSymbolInterval();
 }
Referenced by inet::physicallayer::Ieee80211VhtMode::getDuration().
getGrossBitrate()
virtual bps inet::physicallayer::Ieee80211VhtDataMode::getGrossBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211VhtModeBase.
 { return Ieee80211VhtModeBase::getGrossBitrate(); }
Referenced by computeNetBitrate().
getModulation()
virtual const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211VhtDataMode::getModulation () const inline override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 { return modulationAndCodingScheme->getModulation(); }
getModulationAndCodingScheme()
virtual const Ieee80211Vhtmcs* inet::physicallayer::Ieee80211VhtDataMode::getModulationAndCodingScheme () const inline virtual
 { return modulationAndCodingScheme; }
getNetBitrate()
virtual bps inet::physicallayer::Ieee80211VhtDataMode::getNetBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211VhtModeBase.
 { return Ieee80211VhtModeBase::getNetBitrate(); }
getNumberOfBccEncoders160MHz()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders160MHz () const protected
 {
     switch (getNumberOfSpatialStreams()) {
         case 1:
             if (getMcsIndex() > 6)
                 return 2;
             else
                 return 1;
             break;
             break;
         case 2:
             if (getMcsIndex() < 4)
                 return 1;
             else if (getMcsIndex() < 7)
                 return 2;
             else
                 return 3;
             break;
         case 3:
             if (getMcsIndex() < 3)
                 return 1;
             else if (getMcsIndex() < 5)
                 return 2;
             else if (getMcsIndex() < 7)
                 return 3;
             else
                 return 4;
             break;
         case 4:
             if (getMcsIndex() < 2)
                 return 1;
             else if (getMcsIndex() < 4)
                 return 2;
             else if (getMcsIndex() < 5)
                 return 3;
             else if (getMcsIndex() < 7)
                 return 4;
             else
                 return 6;
             break;
         case 5:
             if (getMcsIndex() < 1)
                 return 1;
             else if (getMcsIndex() < 3)
                 return 2;
             else if (getMcsIndex() < 4)
                 return 3;
             else if (getMcsIndex() < 5)
                 return 4;
             else if (getMcsIndex() < 7)
                 return 5;
             else if (getMcsIndex() < 8)
                 return 6;
             else
                 return 8;
             break;
         case 6:
             if (getMcsIndex() < 1)
                 return 1;
             else if (getMcsIndex() < 3)
                 return 2;
             else if (getMcsIndex() < 4)
                 return 3;
             else if (getMcsIndex() < 5)
                 return 4;
             else if (getMcsIndex() < 7)
                 return 6;
             else if (getMcsIndex() < 9)
                 return 8;
             else
                 return 9;
             break;
         case 7:
             if (getMcsIndex() < 1)
                 return 1;
             else if (getMcsIndex() < 2)
                 return 2;
             else if (getMcsIndex() < 3)
                 return 3;
             else if (getMcsIndex() < 4)
                 return 4;
             else if (getMcsIndex() < 5)
                 return 6;
             else if (getMcsIndex() < 7)
                 return 7;
             else if (getMcsIndex() < 8)
                 return 9;
             else
                 return 12;
             break;
         case 8:
             if (getMcsIndex() < 1)
                 return 1;
             else if (getMcsIndex() < 2)
                 return 2;
             else if (getMcsIndex() < 3)
                 return 3;
             else if (getMcsIndex() < 4)
                 return 4;
             else if (getMcsIndex() < 5)
                 return 6;
             else if (getMcsIndex() < 7)
                 return 8;
             else if (getMcsIndex() < 8)
                 return 9;
             else
                 return 12;
         default:
             throw cRuntimeError("Invalid MCS mode");
     }
 }
Referenced by computeNumberOfBccEncoders().
getNumberOfBccEncoders20MHz()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders20MHz () const protected
 {
     if (getNumberOfSpatialStreams() < 7)
         return 1;
     else {
         if (getMcsIndex() > 7)
             return 2;
         else
             return 1;
     }
 }
Referenced by computeNumberOfBccEncoders().
getNumberOfBccEncoders40MHz()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders40MHz () const protected
 {
     switch (getNumberOfSpatialStreams()) {
         case 1:
         case 2:
         case 3:
             return 1;
             break;
         case 4:
             if (getMcsIndex() > 7)
                 return 2;
             else
                 return 1;
             break;
         case 5:
             if (getMcsIndex() > 5)
                 return 2;
             else
                 return 1;
             break;
         case 6:
             if (getMcsIndex() > 4)
                 return 2;
             else
                 return 1;
             break;
         case 7:
         case 8:
             if (getMcsIndex() < 4)
                 return 1;
             else if (getMcsIndex() < 8)
                 return 2;
             else
                 return 3;
             break;
         default:
             throw cRuntimeError("Invalid MCS mode");
     }
 }
Referenced by computeNumberOfBccEncoders().
getNumberOfBccEncoders80MHz()
unsigned int inet::physicallayer::Ieee80211VhtDataMode::getNumberOfBccEncoders80MHz () const protected
 {
     switch (getNumberOfSpatialStreams()) {
         case 1:
             return 1;
             break;
         case 2:
             if (getMcsIndex() > 6)
                 return 2;
             else
                 return 1;
             break;
         case 3:
             if (getMcsIndex() < 5)
                 return 1;
             else if (getMcsIndex() < 9)
                 return 2;
             else
                 return 3;
             break;
         case 4:
             if (getMcsIndex() < 4)
                 return 1;
             else if (getMcsIndex() < 7)
                 return 2;
             else
                 return 3;
             break;
         case 5:
             if (getMcsIndex() < 3)
                 return 1;
             else if (getMcsIndex() < 5)
                 return 2;
             else if (getMcsIndex() < 8)
                 return 3;
             else
                 return 4;
             break;
         case 6:
             if (getMcsIndex() < 3)
                 return 1;
             else if (getMcsIndex() < 4)
                 return 2;
             else if (getMcsIndex() < 7)
                 return 3;
             else
                 return 4;
             break;
         case 7:
             if (getMcsIndex() < 2)
                 return 1;
             else if (getMcsIndex() == 3)
                 return 2;
             else if (getMcsIndex() < 5)
                 return 3;
             else if (getMcsIndex() == 5)
                 return 4;
             else
                 return 6;
             break;
         case 8:
             if (getMcsIndex() < 3)
                 return 1;
             else if (getMcsIndex() < 4)
                 return 2;
             else if (getMcsIndex() < 5)
                 return 3;
             else if (getMcsIndex() < 7)
                 return 4;
             else
                 return 6;
             break;
         default:
             throw cRuntimeError("Invalid MCS mode");
     }
 }
Referenced by computeNumberOfBccEncoders().
getNumberOfSpatialStreams()
virtual int inet::physicallayer::Ieee80211VhtDataMode::getNumberOfSpatialStreams () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211VhtModeBase.
 { return Ieee80211VhtModeBase::getNumberOfSpatialStreams(); }
Referenced by inet::physicallayer::Ieee80211VhtCompliantModes::getCompliantMode(), getNumberOfBccEncoders160MHz(), getNumberOfBccEncoders20MHz(), getNumberOfBccEncoders40MHz(), and getNumberOfBccEncoders80MHz().
getPaddingLength()
virtual b inet::physicallayer::Ieee80211VhtDataMode::getPaddingLength (b dataLength) const inline override virtual
Implements inet::physicallayer::IIeee80211DataMode.
 { return b(0); }
getServiceFieldLength()
b inet::physicallayer::Ieee80211VhtDataMode::getServiceFieldLength () const inline
 { return b(16); }
Referenced by getCompleteLength().
getTailFieldLength()
b inet::physicallayer::Ieee80211VhtDataMode::getTailFieldLength () const inline
 { return b(6) * numberOfBccEncoders; }
Referenced by getCompleteLength().
Member Data Documentation
modulationAndCodingScheme
const Ieee80211Vhtmcs* inet::physicallayer::Ieee80211VhtDataMode::modulationAndCodingScheme protected
Referenced by computeNumberOfCodedBitsPerSubcarrierSum().
numberOfBccEncoders
const unsigned int inet::physicallayer::Ieee80211VhtDataMode::numberOfBccEncoders protected
The documentation for this class was generated from the following files:
Ieee80211VhtMode.h
Ieee80211VhtMode.cc