INET Framework for OMNeT++/OMNEST: inet::MacForwardingTableConfigurator Class Reference
inet::MacForwardingTableConfigurator Class Reference
#include <MacForwardingTableConfigurator.h>
Public Member Functions
virtual ~MacForwardingTableConfigurator ()
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Protected Member Functions
virtual void initialize (int stage) override
virtual void computeConfiguration ()
Computes the network configuration for all nodes in the network.
virtual void extendConfiguration (Node *destinationNode, Interface *destinationInterface, MacAddress macAddress)
virtual void computeMacForwardingTables ()
virtual void configureMacForwardingTables () const
virtual cValueMap * findForwardingRule (cValueArray *configuration, MacAddress macAddress, std::string interfaceName)
Protected Member Functions inherited from inet::NetworkConfiguratorBase
virtual ~NetworkConfiguratorBase ()
virtual int numInitStages () const override
virtual void handleMessage (cMessage *msg) override
virtual void extractTopology (Topology &topology)
Extracts network topology by walking through the module hierarchy.
virtual std::vector< Node * > computeShortestNodePath (Node *source, Node *destination) const
virtual std::vector< Link * > computeShortestLinkPath (Node *source, Node *destination) const
virtual bool isBridgeNode (Node *node) const
virtual Link * findLinkIn (const Node *node, const char *neighbor) const
virtual Link * findLinkOut (const Node *node, const char *neighbor) const
virtual Link * findLinkOut (const Node *node, const Node *neighbor) const
virtual Link * findLinkOut (const Interface *interface) const
virtual Topology::Link * findLinkOut (const Node *node, int gateId) const
virtual Interface * findInterface (const Node *node, NetworkInterface *networkInterface) const
Protected Attributes
std::map< int, cValueArray * > configurations
Protected Attributes inherited from inet::NetworkConfiguratorBase
Topology * topology = nullptr
Constructor & Destructor Documentation
~MacForwardingTableConfigurator()
inet::MacForwardingTableConfigurator::~MacForwardingTableConfigurator () virtual
 {
     for (auto it : configurations)
         delete it.second;
 }
Member Function Documentation
computeConfiguration()
void inet::MacForwardingTableConfigurator::computeConfiguration () protected virtual
Computes the network configuration for all nodes in the network.
The result of the computation is only stored in the configurator.
 {
     long initializeStartTime = clock();
     delete topology;
     topology = new Topology();
     TIME(extractTopology(*topology))
     TIME(computeMacForwardingTables());
     printElapsedTime("initialize", initializeStartTime);
 }
Referenced by initialize().
computeMacForwardingTables()
void inet::MacForwardingTableConfigurator::computeMacForwardingTables () protected virtual
 {
     // for each network node as destination
     //   for each network interface of destination
     //   find shortest path from all sources to destination passing through the network interface
     //     for each switch as source
     //       store first outgoing interface of the switch in the MAC forwarding table of the switch
     //       towards the MAC address of the network interface of the destination
     for (int i = 0; i < topology->getNumNodes(); i++) {
         Node *destinationNode = (Node *)topology->getNode(i);
         if (!isBridgeNode(destinationNode)) {
             for (auto destinationInterface : destinationNode->interfaces) {
                 if (!destinationInterface->networkInterface->isLoopback() &&
                     !destinationInterface->networkInterface->getMacAddress().isUnspecified())
                 {
                     extendConfiguration(destinationNode, destinationInterface, destinationInterface->networkInterface->getMacAddress());
                 }
             }
         }
     }
 }
Referenced by computeConfiguration().
configureMacForwardingTables()
void inet::MacForwardingTableConfigurator::configureMacForwardingTables () const protected virtual
 {
     for (auto it : configurations) {
         auto macForwardingTable = getSimulation()->getModule(it.first);
         macForwardingTable->par("forwardingTable") = it.second->dup();
     }
 }
Referenced by initialize(), and receiveSignal().
extendConfiguration()
void inet::MacForwardingTableConfigurator::extendConfiguration (Node * destinationNode, Interface * destinationInterface, MacAddress macAddress) protected virtual
 {
     for (int j = 0; j < destinationNode->getNumInLinks(); j++) {
         auto link = (Link *)destinationNode->getLinkIn(j);
         link->setWeight(link->destinationInterface != destinationInterface ? std::numeric_limits<double>::infinity() : 1);
     }
     topology->calculateWeightedSingleShortestPathsTo(destinationNode);
     for (int j = 0; j < topology->getNumNodes(); j++) {
         Node *sourceNode = (Node *)topology->getNode(j);
         if (sourceNode != destinationNode && isBridgeNode(sourceNode) && sourceNode->getNumPaths() != 0) {
             auto firstLink = (Link *)sourceNode->getPath(0);
             auto firstInterface = static_cast<Interface *>(firstLink->sourceInterface);
             auto interfaceName = firstInterface->networkInterface->getInterfaceName();
             auto moduleId = sourceNode->module->getSubmodule("macTable")->getId();
             auto it = configurations.find(moduleId);
             if (it == configurations.end())
                 configurations[moduleId] = new cValueArray();
             else if (findForwardingRule(it->second, macAddress, interfaceName) != nullptr)
                 continue;
             else {
                 auto rule = new cValueMap();
                 rule->set("address", macAddress.str());
                 rule->set("interface", interfaceName);
                 it->second->add(rule);
             }
         }
     }
 }
Referenced by computeMacForwardingTables(), and receiveSignal().
findForwardingRule()
cValueMap * inet::MacForwardingTableConfigurator::findForwardingRule (cValueArray * configuration, MacAddress macAddress, std::string interfaceName) protected virtual
 {
     for (int i = 0; i < configuration->size(); i++) {
         auto rule = check_and_cast<cValueMap *>(configuration->get(i).objectValue());
         if (rule->get("address").stdstringValue() == macAddress.str() &&
             rule->get("interface").stdstringValue() == interfaceName)
         {
             return rule;
         }
     }
     return nullptr;
 }
Referenced by extendConfiguration().
initialize()
void inet::MacForwardingTableConfigurator::initialize (int stage) override protected virtual
 {
     NetworkConfiguratorBase::initialize(stage);
     if (stage == INITSTAGE_NETWORK_CONFIGURATION) {
         computeConfiguration();
         configureMacForwardingTables();
         getParentModule()->subscribe(ipv4MulticastChangeSignal, this);
     }
 }
receiveSignal()
void inet::MacForwardingTableConfigurator::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     if (signal == ipv4MulticastChangeSignal) {
         auto sourceInfo = check_and_cast<Ipv4MulticastGroupSourceInfo *>(object);
         auto node = static_cast<Node *>(topology->getNodeFor(getContainingNode(sourceInfo->ie)));
         auto interface = findInterface(node, sourceInfo->ie);
         extendConfiguration(node, interface, sourceInfo->groupAddress.mapToMulticastMacAddress());
         configureMacForwardingTables();
     }
 }
Member Data Documentation
configurations
std::map<int, cValueArray *> inet::MacForwardingTableConfigurator::configurations protected
Referenced by configureMacForwardingTables(), extendConfiguration(), and ~MacForwardingTableConfigurator().
The documentation for this class was generated from the following files:
MacForwardingTableConfigurator.h
MacForwardingTableConfigurator.cc