INET Framework for OMNeT++/OMNEST: inet::math::FunctionBase< R, D > Class Template Reference
inet::math::FunctionBase< R, D > Class Template Reference
Useful base class for most IFunction implementations with some default behavior.
#include <FunctionBase.h>
Public Member Functions
virtual void partition (const typename D::I &i, const std::function< void(const typename D::I &, const IFunction< R, D > *)> callback) const override
Subdivides the provided domain and calls back f with the subdomains and the corresponding potentially simpler domain limited functions.
virtual Interval< R > getRange () const override
Returns the valid range of the function as an interval.
virtual Interval< R > getRange (const typename D::I &i) const override
Returns the valid range of the function as an interval for the given domain.
virtual D::I getDomain () const override
Returns the valid domain of the function as an interval.
virtual bool isFinite () const override
Returns true if the function value is finite in the whole domain.
virtual bool isFinite (const typename D::I &i) const override
Returns true if the function value is finite in the given domain.
virtual bool isNonZero () const override
Returns true if the function value is non-zero in the whole domain.
virtual bool isNonZero (const typename D::I &i) const override
Returns true if the function value is non-zero in the given domain.
virtual R getMin () const override
Returns the minimum value for the whole domain.
virtual R getMin (const typename D::I &i) const override
Returns the minimum value for the given domain.
virtual R getMax () const override
Returns the maximum value for the whole domain.
virtual R getMax (const typename D::I &i) const override
Returns the maximum value for the given domain.
virtual R getMean () const override
Returns the mean value for the whole domain.
virtual R getMean (const typename D::I &i) const override
Returns the mean value for the given domain.
virtual R getIntegral () const override
Returns the integral value for the whole domain.
virtual R getIntegral (const typename D::I &i) const override
Returns the integral value for the given domain.
virtual const Ptr< const IFunction< R, D > > add (const Ptr< const IFunction< R, D >> &o) const override
Adds the provided function to this function.
virtual const Ptr< const IFunction< R, D > > subtract (const Ptr< const IFunction< R, D >> &o) const override
Substracts the provided function from this function.
virtual const Ptr< const IFunction< R, D > > multiply (const Ptr< const IFunction< double, D >> &o) const override
Multiplies the provided function with this function.
virtual const Ptr< const IFunction< double, D > > divide (const Ptr< const IFunction< R, D >> &o) const override
Divides this function with the provided function.
virtual std::ostream & printOn (std::ostream &os) const override
virtual void print (std::ostream &os, int level=0) const override
Prints this function in human readable form to the provided stream for the whole domain.
virtual void print (std::ostream &os, const typename D::I &i, int level=0) const override
Prints this function in a human readable form to the provided stream for the given domain.
virtual void printPartitioning (std::ostream &os, const typename D::I &i, int level) const override
Prints the partitioning of this function in a human readable form to the provided stream for the given domain.
virtual void printPartition (std::ostream &os, const typename D::I &i, int level=0) const override
Prints a single partition of this function in a human readable form to the provided stream for the given domain.
virtual void printStructure (std::ostream &os, int level=0) const override
Prints the internal data structure of this function in a human readable form to the provided stream.
Public Member Functions inherited from inet::math::IFunction< R, D >
virtual ~IFunction ()
virtual R getValue (const typename D::P &p) const =0
Returns the value of the function at the given point.
Detailed Description
template<typename R, typename D>
class inet::math::FunctionBase< R, D >
Useful base class for most IFunction implementations with some default behavior.
Member Function Documentation
add()
template<typename R , typename D > virtual const Ptr<const IFunction<R, D> > inet::math::FunctionBase< R, D >::add (const Ptr< const IFunction< R, D >> & o) const inline override virtual
Adds the provided function to this function.
Implements inet::math::IFunction< R, D >.
{
         return makeShared<AddedFunction<R, D>>(const_cast<FunctionBase<R, D> *>(this)->shared_from_this(), o);
     }
divide()
template<typename R , typename D > virtual const Ptr<const IFunction<double, D> > inet::math::FunctionBase< R, D >::divide (const Ptr< const IFunction< R, D >> & o) const inline override virtual
Divides this function with the provided function.
Implements inet::math::IFunction< R, D >.
{
         return makeShared<DividedFunction<R, D>>(const_cast<FunctionBase<R, D> *>(this)->shared_from_this(), o);
     }
getDomain()
template<typename R , typename D > virtual D::I inet::math::FunctionBase< R, D >::getDomain () const inline override virtual
Returns the valid domain of the function as an interval.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::SummedFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, and inet::math::AddedFunction< R, D >.
{
         return typename D::I(D::P::getLowerBounds(), D::P::getUpperBounds(), 0b0, 0b0, 0b0);
     }
getIntegral() [1/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getIntegral () const inline override virtual
Returns the integral value for the whole domain.
Implements inet::math::IFunction< R, D >.
 { return getIntegral(getDomain()); }
Referenced by inet::math::FunctionBase< R, Domain< X > >::getIntegral().
getIntegral() [2/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getIntegral (const typename D::I & i) const inline override virtual
Returns the integral value for the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::UnireciprocalFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         R result(0);
         this->partition(i, [&] (const typename D::I& i1, const IFunction<R, D> *f1) {
             double volume = i1.getVolume();
             R value = f1->getMean(i1);
             if (!(value == R(0) && std::isinf(volume)))
                 result += volume * value;
         });
         return result;
     }
getMax() [1/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getMax () const inline override virtual
Returns the maximum value for the whole domain.
Implements inet::math::IFunction< R, D >.
 { return getMax(getDomain()); }
Referenced by inet::math::FunctionBase< R, Domain< X > >::getMax().
getMax() [2/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getMax (const typename D::I & i) const inline override virtual
Returns the maximum value for the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         R result(getLowerBound<R>());
         this->partition(i, [&] (const typename D::I& i1, const IFunction<R, D> *f1) {
             result = math::maxnan(f1->getMax(i1), result);
         });
         return result;
     }
getMean() [1/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getMean () const inline override virtual
Returns the mean value for the whole domain.
Implements inet::math::IFunction< R, D >.
 { return getMean(getDomain()); }
Referenced by inet::math::FunctionBase< R, Domain< X > >::getMean().
getMean() [2/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getMean (const typename D::I & i) const inline override virtual
Returns the mean value for the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         return getIntegral(i) / i.getVolume();
     }
getMin() [1/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getMin () const inline override virtual
Returns the minimum value for the whole domain.
Implements inet::math::IFunction< R, D >.
 { return getMin(getDomain()); }
Referenced by inet::math::FunctionBase< R, Domain< X > >::getMin().
getMin() [2/2]
template<typename R , typename D > virtual R inet::math::FunctionBase< R, D >::getMin (const typename D::I & i) const inline override virtual
Returns the minimum value for the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         R result(getUpperBound<R>());
         this->partition(i, [&] (const typename D::I& i1, const IFunction<R, D> *f1) {
             result = math::minnan(f1->getMin(i1), result);
         });
         return result;
     }
getRange() [1/2]
template<typename R , typename D > virtual Interval<R> inet::math::FunctionBase< R, D >::getRange () const inline override virtual
Returns the valid range of the function as an interval.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         return getRange(getDomain());
     }
getRange() [2/2]
template<typename R , typename D > virtual Interval<R> inet::math::FunctionBase< R, D >::getRange (const typename D::I & i) const inline override virtual
Returns the valid range of the function as an interval for the given domain.
Implements inet::math::IFunction< R, D >.
{
         return Interval<R>(getLowerBound<R>(), getUpperBound<R>(), 0b1, 0b1, 0b0);
     }
isFinite() [1/2]
template<typename R , typename D > virtual bool inet::math::FunctionBase< R, D >::isFinite () const inline override virtual
Returns true if the function value is finite in the whole domain.
Implements inet::math::IFunction< R, D >.
 { return isFinite(getDomain()); }
Referenced by inet::math::FunctionBase< R, Domain< X > >::isFinite().
isFinite() [2/2]
template<typename R , typename D > virtual bool inet::math::FunctionBase< R, D >::isFinite (const typename D::I & i) const inline override virtual
Returns true if the function value is finite in the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::ApproximatedFunction< R, D, DIMENSION, X >, inet::math::SummedFunction< R, D >, inet::math::DividedFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::AddedFunction< R, D >, inet::math::UnilinearFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         bool result = true;
         this->partition(i, [&] (const typename D::I& i1, const IFunction<R, D> *f1) {
             result &= f1->isFinite(i1);
         });
         return result;
     }
isNonZero() [1/2]
template<typename R , typename D > virtual bool inet::math::FunctionBase< R, D >::isNonZero () const inline override virtual
Returns true if the function value is non-zero in the whole domain.
Implements inet::math::IFunction< R, D >.
 { return isNonZero(getDomain()); }
Referenced by inet::math::FunctionBase< R, Domain< X > >::isNonZero().
isNonZero() [2/2]
template<typename R , typename D > virtual bool inet::math::FunctionBase< R, D >::isNonZero (const typename D::I & i) const inline override virtual
Returns true if the function value is non-zero in the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         bool result = true;
         this->partition(i, [&] (const typename D::I& i1, const IFunction<R, D> *f1) {
             result &= f1->isNonZero(i1);
         });
         return result;
     }
multiply()
template<typename R , typename D > virtual const Ptr<const IFunction<R, D> > inet::math::FunctionBase< R, D >::multiply (const Ptr< const IFunction< double, D >> & o) const inline override virtual
Multiplies the provided function with this function.
Implements inet::math::IFunction< R, D >.
{
         return makeShared<MultipliedFunction<R, D>>(const_cast<FunctionBase<R, D> *>(this)->shared_from_this(), o);
     }
partition()
template<typename R , typename D > virtual void inet::math::FunctionBase< R, D >::partition (const typename D::I & i, const std::function< void(const typename D::I &, const IFunction< R, D > *)> f) const inline override virtual
Subdivides the provided domain and calls back f with the subdomains and the corresponding potentially simpler domain limited functions.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::LeftCurryingFunction< R, C, DIMSC, D, DIMSD, E >, inet::math::SummedFunction< R, D >, inet::math::UnireciprocalFunction< R, D >, inet::math::MultipliedFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::SubtractedFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::UnilinearFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, inet::math::AddedFunction< R, D >, inet::math::ConstantFunction< R, D >, and inet::math::DividedFunction< R, D >.
{
         auto m = (1 << std::tuple_size<typename D::P::type>::value) - 1;
         if (i.getFixed() == m) {
             ASSERT(i.getLower() == i.getUpper());
             ConstantFunction<R, D> g(this->getValue(i.getLower()));
             callback(i, &g);
         }
         else
             throw cRuntimeError("Cannot partition %s, interval = %s", this->getClassName(), i.str().c_str());
     }
Referenced by inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::partition(), inet::physicallayer::SpaceDependentAttenuationFunction::partition(), inet::physicallayer::BackgroundNoisePowerFunction::partition(), and inet::physicallayer::PropagatedTransmissionPowerFunction::partition().
print() [1/2]
template<typename R , typename D > virtual void inet::math::FunctionBase< R, D >::print (std::ostream & os, const typename D::I & i, int level = 0) const inline override virtual
Prints this function in a human readable form to the provided stream for the given domain.
Implements inet::math::IFunction< R, D >.
{
         os << std::string(level, ' ') << "function" << D() << "  ";
         printUnit(os, R());
         os << std::string(level, ' ') << " {\n  domain = " << i << "  range = " << getRange() << "\n";
         os << std::string(level, ' ') << "  structure =\n    ";
         printStructure(os, level + 4);
         os << std::string(level, ' ') << "\n";
         os << std::string(level, ' ') << "  partitioning = {\n";
         printPartitioning(os, i, level + 4);
         os << std::string(level, ' ') << "  } min = " << getMin(i) << ", max = " << getMax(i) << ", mean = " << getMean(i) << "\n}\n";
     }
print() [2/2]
template<typename R , typename D > virtual void inet::math::FunctionBase< R, D >::print (std::ostream & os, int level = 0) const inline override virtual
Prints this function in human readable form to the provided stream for the whole domain.
Implements inet::math::IFunction< R, D >.
{
         print(os, getDomain(), level);
     }
printOn()
template<typename R , typename D > virtual std::ostream& inet::math::FunctionBase< R, D >::printOn (std::ostream & os) const inline override virtual
{
         print(os);
         return os;
     }
printPartition()
template<typename R , typename D > virtual void inet::math::FunctionBase< R, D >::printPartition (std::ostream & os, const typename D::I & i, int level = 0) const inline override virtual
Prints a single partition of this function in a human readable form to the provided stream for the given domain.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::UnireciprocalFunction< R, D >, inet::math::BilinearFunction< R, D >, inet::math::UnilinearFunction< R, D >, and inet::math::ConstantFunction< R, D >.
{
         os << "over " << i << "  {";
         iterateCorners(i, std::function<void(const typename D::P&)>([&] (const typename D::P& p) {
             os << "\n" << std::string(level + 2, ' ') << "at " << p << "  " << this->getValue(p);
         }));
         os << "\n" << std::string(level, ' ') << "} min = " << getMin(i) << ", max = " << getMax(i) << ", mean = " << getMean(i) << "\n";
     }
printPartitioning()
template<typename R , typename D > virtual void inet::math::FunctionBase< R, D >::printPartitioning (std::ostream & os, const typename D::I & i, int level) const inline override virtual
Prints the partitioning of this function in a human readable form to the provided stream for the given domain.
Implements inet::math::IFunction< R, D >.
{
         this->partition(i, [&] (const typename D::I& i1, const IFunction<R, D> *f1) {
             os << std::string(level, ' ');
             f1->printPartition(os, i1, level);
         });
     }
printStructure()
template<typename R , typename D > virtual void inet::math::FunctionBase< R, D >::printStructure (std::ostream & os, int level = 0) const inline override virtual
Prints the internal data structure of this function in a human readable form to the provided stream.
Implements inet::math::IFunction< R, D >.
Reimplemented in inet::math::IntegratedFunction< R, D, DIMS, RI, DI >, inet::math::Interpolated1DFunction< R, X >, inet::math::Extruded2DFunction< R, X, Y >, inet::math::ApproximatedFunction< R, D, DIMENSION, X >, inet::math::Boxcar2DFunction< R, X, Y >, inet::math::SummedFunction< R, D >, inet::physicallayer::ObstacleLossFunction, inet::math::Boxcar1DFunction< R, X >, inet::physicallayer::PathLossFunction, inet::physicallayer::PropagatedTransmissionPowerFunction, inet::math::DividedFunction< R, D >, inet::physicallayer::BackgroundNoisePowerFunction, inet::math::Combined2DFunction< R, X, Y >, inet::math::MultipliedFunction< R, D >, inet::physicallayer::SpaceDependentAttenuationFunction, inet::math::SubtractedFunction< R, D >, inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction, inet::math::UnilinearFunction< R, D >, inet::math::DomainShiftedFunction< R, D >, inet::math::AddedFunction< R, D >, inet::math::DomainLimitedFunction< R, D >, inet::physicallayer::FrequencyDependentAttenuationFunction, and inet::math::ConstantFunction< R, D >.
{
         auto className = this->getClassName();
         if (!strncmp(className, "inet::math::", 12))
             className += 12;
         else if (!strncmp(className, "inet::", 6))
             className += 6;
         os << className;
     }
subtract()
template<typename R , typename D > virtual const Ptr<const IFunction<R, D> > inet::math::FunctionBase< R, D >::subtract (const Ptr< const IFunction< R, D >> & o) const inline override virtual
Substracts the provided function from this function.
Implements inet::math::IFunction< R, D >.
{
         return makeShared<SubtractedFunction<R, D>>(const_cast<FunctionBase<R, D> *>(this)->shared_from_this(), o);
     }
The documentation for this class was generated from the following file:
FunctionBase.h