INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_AssociateRequest Class Reference
inet::ieee80211::Ieee80211Prim_AssociateRequest Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:165 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AssociateRequest ()
Ieee80211Prim_AssociateRequest (const Ieee80211Prim_AssociateRequest &other)
virtual ~Ieee80211Prim_AssociateRequest ()
Ieee80211Prim_AssociateRequest & operator= (const Ieee80211Prim_AssociateRequest &other)
virtual Ieee80211Prim_AssociateRequest * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::MacAddress & getAddress () const
virtual ::inet::MacAddress & getAddressForUpdate ()
virtual void setAddress (const ::inet::MacAddress &address)
virtual ::omnetpp::simtime_t getTimeout () const
virtual void setTimeout (::omnetpp::simtime_t timeout)
Public Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
Ieee80211PrimRequest ()
Ieee80211PrimRequest (const Ieee80211PrimRequest &other)
virtual ~Ieee80211PrimRequest ()
Ieee80211PrimRequest & operator= (const Ieee80211PrimRequest &other)
Protected Member Functions
bool operator== (const Ieee80211Prim_AssociateRequest &)=delete
Protected Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
bool operator== (const Ieee80211PrimRequest &)=delete
Protected Attributes
::inet::MacAddress address
::omnetpp::simtime_t timeout = SIMTIME_ZERO
Private Member Functions
void copy (const Ieee80211Prim_AssociateRequest &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:165 by opp_msgtool.
//
// Losely based on MLME-ASSOCIATE.request
//
class Ieee80211Prim_AssociateRequest extends Ieee80211PrimRequest
{
    MacAddress address;
    simtime_t timeout;
}
Constructor & Destructor Documentation
Ieee80211Prim_AssociateRequest() [1/2]
inet::ieee80211::Ieee80211Prim_AssociateRequest::Ieee80211Prim_AssociateRequest ()
Ieee80211Prim_AssociateRequest() [2/2]
inet::ieee80211::Ieee80211Prim_AssociateRequest::Ieee80211Prim_AssociateRequest (const Ieee80211Prim_AssociateRequest & other)
~Ieee80211Prim_AssociateRequest()
virtual inet::ieee80211::Ieee80211Prim_AssociateRequest::~Ieee80211Prim_AssociateRequest () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211Prim_AssociateRequest::copy (const Ieee80211Prim_AssociateRequest & other) private
dup()
virtual Ieee80211Prim_AssociateRequest* inet::ieee80211::Ieee80211Prim_AssociateRequest::dup () const inline override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Reimplemented in inet::ieee80211::Ieee80211Prim_ReassociateRequest.
 {return new Ieee80211Prim_AssociateRequest(*this);}
getAddress()
virtual const ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_AssociateRequest::getAddress () const virtual
getAddressForUpdate()
virtual ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_AssociateRequest::getAddressForUpdate () inline
 { return const_cast<::inet::MacAddress&>(const_cast<Ieee80211Prim_AssociateRequest*>(this)->getAddress());}
getTimeout()
virtual ::omnetpp::simtime_t inet::ieee80211::Ieee80211Prim_AssociateRequest::getTimeout () const
operator=()
Ieee80211Prim_AssociateRequest& inet::ieee80211::Ieee80211Prim_AssociateRequest::operator= (const Ieee80211Prim_AssociateRequest & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_AssociateRequest::operator== (const Ieee80211Prim_AssociateRequest &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_AssociateRequest::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Reimplemented in inet::ieee80211::Ieee80211Prim_ReassociateRequest.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_AssociateRequest::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Reimplemented in inet::ieee80211::Ieee80211Prim_ReassociateRequest.
Referenced by inet::ieee80211::doParsimUnpacking().
setAddress()
virtual void inet::ieee80211::Ieee80211Prim_AssociateRequest::setAddress (const ::inet::MacAddress & address) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendAssociateRequest(), and inet::ieee80211::Ieee80211AgentSta::sendReassociateRequest().
setTimeout()
virtual void inet::ieee80211::Ieee80211Prim_AssociateRequest::setTimeout (::omnetpp::simtime_t timeout) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendAssociateRequest(), and inet::ieee80211::Ieee80211AgentSta::sendReassociateRequest().
Member Data Documentation
address
::inet::MacAddress inet::ieee80211::Ieee80211Prim_AssociateRequest::address protected
timeout
::omnetpp::simtime_t inet::ieee80211::Ieee80211Prim_AssociateRequest::timeout = SIMTIME_ZERO protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h