INET Framework for OMNeT++/OMNEST: inet::sctp::SctpSendStream Class Reference
inet::sctp::SctpSendStream Class Reference
#include <SctpSendStream.h>
Public Member Functions
SctpSendStream (SctpAssociation *assoc, const uint16_t id)
~SctpSendStream ()
cPacketQueue * getStreamQ () const
cPacketQueue * getUnorderedStreamQ () const
uint32_t getNextStreamSeqNum ()
uint32_t getBytesInFlight () const
void setNextStreamSeqNum (const uint16_t num)
void setBytesInFlight (const uint32_t bytes)
bool getFragInProgress () const
void setFragInProgress (const bool frag)
uint16_t getStreamId () const
void setStreamId (const uint16_t id)
void deleteQueue ()
Protected Attributes
SctpAssociation * assoc
uint16_t streamId
uint16_t nextStreamSeqNum
uint32_t bytesInFlight
bool resetRequested
bool fragInProgress
cPacketQueue * streamQ
cPacketQueue * uStreamQ
Constructor & Destructor Documentation
SctpSendStream()
inet::sctp::SctpSendStream::SctpSendStream (SctpAssociation * assoc, const uint16_t id)
 {
     assoc = assoc_;
     streamId = id;
     nextStreamSeqNum = 0;
     bytesInFlight = 0;
     resetRequested = false;
     fragInProgress = false;
     char queueName[64];
     snprintf(queueName, sizeof(queueName), "OrderedSendQueue ID %d", id);
     streamQ = new cPacketQueue(queueName);
     snprintf(queueName, sizeof(queueName), "UnorderedSendQueue ID %d", id);
     uStreamQ = new cPacketQueue(queueName);
 }
~SctpSendStream()
inet::sctp::SctpSendStream::~SctpSendStream ()
 {
     deleteQueue();
 }
Member Function Documentation
deleteQueue()
void inet::sctp::SctpSendStream::deleteQueue ()
 {
     SctpDataMsg *datMsg;
     SctpSimpleMessage *smsg;
     int32_t count = streamQ->getLength();
     while (!streamQ->isEmpty()) {
         datMsg = check_and_cast<SctpDataMsg *>(streamQ->pop());
         smsg = check_and_cast<SctpSimpleMessage *>(datMsg->decapsulate());
         delete smsg;
         delete datMsg;
         count--;
     }
     while (!uStreamQ->isEmpty()) {
         datMsg = check_and_cast<SctpDataMsg *>(uStreamQ->pop());
         smsg = check_and_cast<SctpSimpleMessage *>(datMsg->decapsulate());
         delete smsg;
         delete datMsg;
     }
     delete streamQ;
     delete uStreamQ;
 }
Referenced by ~SctpSendStream().
getBytesInFlight()
uint32_t inet::sctp::SctpSendStream::getBytesInFlight () const inline
 { return bytesInFlight; };
Referenced by inet::sctp::SctpAssociation::decreaseOutstandingBytes(), and inet::sctp::SctpAssociation::increaseOutstandingBytes().
getFragInProgress()
bool inet::sctp::SctpSendStream::getFragInProgress () const inline
 { return fragInProgress; };
getNextStreamSeqNum()
uint32_t inet::sctp::SctpSendStream::getNextStreamSeqNum ()
{
     return nextStreamSeqNum;
 };
Referenced by inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
getStreamId()
uint16_t inet::sctp::SctpSendStream::getStreamId () const inline
 { return streamId; };
getStreamQ()
cPacketQueue* inet::sctp::SctpSendStream::getStreamQ () const inline
 { return streamQ; };
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::generateSendQueueAbatedIndication(), inet::sctp::SctpAssociation::nextChunkFitsIntoPacket(), inet::sctp::SctpAssociation::nonRenegablyAckChunk(), and inet::sctp::SctpAssociation::process_SEND().
getUnorderedStreamQ()
cPacketQueue* inet::sctp::SctpSendStream::getUnorderedStreamQ () const inline
 { return uStreamQ; };
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), inet::sctp::SctpAssociation::fragmentOutboundDataMsgs(), inet::sctp::SctpAssociation::generateSendQueueAbatedIndication(), inet::sctp::SctpAssociation::nextChunkFitsIntoPacket(), inet::sctp::SctpAssociation::nonRenegablyAckChunk(), and inet::sctp::SctpAssociation::process_SEND().
setBytesInFlight()
void inet::sctp::SctpSendStream::setBytesInFlight (const uint32_t bytes) inline
 { bytesInFlight = bytes; }
Referenced by inet::sctp::SctpAssociation::decreaseOutstandingBytes(), and inet::sctp::SctpAssociation::increaseOutstandingBytes().
setFragInProgress()
void inet::sctp::SctpSendStream::setFragInProgress (const bool frag) inline
 { fragInProgress = frag; }
setNextStreamSeqNum()
void inet::sctp::SctpSendStream::setNextStreamSeqNum (const uint16_t num)
{
     nextStreamSeqNum = num;
 };
Referenced by inet::sctp::SctpAssociation::makeDataVarFromDataMsg().
setStreamId()
void inet::sctp::SctpSendStream::setStreamId (const uint16_t id) inline
 { streamId = id; }
Member Data Documentation
assoc
SctpAssociation* inet::sctp::SctpSendStream::assoc protected
Referenced by SctpSendStream().
bytesInFlight
uint32_t inet::sctp::SctpSendStream::bytesInFlight protected
Referenced by SctpSendStream().
fragInProgress
bool inet::sctp::SctpSendStream::fragInProgress protected
Referenced by SctpSendStream().
nextStreamSeqNum
uint16_t inet::sctp::SctpSendStream::nextStreamSeqNum protected
Referenced by getNextStreamSeqNum(), SctpSendStream(), and setNextStreamSeqNum().
resetRequested
bool inet::sctp::SctpSendStream::resetRequested protected
Referenced by SctpSendStream().
streamId
uint16_t inet::sctp::SctpSendStream::streamId protected
Referenced by SctpSendStream().
streamQ
cPacketQueue* inet::sctp::SctpSendStream::streamQ protected
Referenced by deleteQueue(), and SctpSendStream().
uStreamQ
cPacketQueue* inet::sctp::SctpSendStream::uStreamQ protected
Referenced by deleteQueue(), and SctpSendStream().
The documentation for this class was generated from the following files:
SctpSendStream.h
SctpSendStream.cc