INET Framework for OMNeT++/OMNEST: inet::tcp::TcpOptionWindowScale Class Reference
inet::tcp::TcpOptionWindowScale Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:128 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
TcpOptionWindowScale ()
TcpOptionWindowScale (const TcpOptionWindowScale &other)
virtual ~TcpOptionWindowScale ()
TcpOptionWindowScale & operator= (const TcpOptionWindowScale &other)
virtual TcpOptionWindowScale * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getWindowScale () const
virtual void setWindowScale (unsigned short windowScale)
Public Member Functions inherited from inet::tcp::TcpOption
TcpOption ()
TcpOption (const TcpOption &other)
virtual ~TcpOption ()
TcpOption & operator= (const TcpOption &other)
virtual TcpOptionNumbers getKind () const
virtual void setKind (TcpOptionNumbers kind)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const TcpOptionWindowScale &)=delete
Protected Member Functions inherited from inet::tcp::TcpOption
bool operator== (const TcpOption &)=delete
Protected Attributes
unsigned short windowScale = 0
Protected Attributes inherited from inet::tcp::TcpOption
TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1)
unsigned short length = 1
Private Member Functions
void copy (const TcpOptionWindowScale &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:128 by opp_msgtool.
class TcpOptionWindowScale extends TcpOption
{
    kind = TCPOPTION_WINDOW_SCALE;
    length = 3;
    unsigned short windowScale;   // uint8_t
}
Constructor & Destructor Documentation
TcpOptionWindowScale() [1/2]
inet::tcp::TcpOptionWindowScale::TcpOptionWindowScale ()
TcpOptionWindowScale() [2/2]
inet::tcp::TcpOptionWindowScale::TcpOptionWindowScale (const TcpOptionWindowScale & other)
~TcpOptionWindowScale()
virtual inet::tcp::TcpOptionWindowScale::~TcpOptionWindowScale () virtual
Member Function Documentation
copy()
void inet::tcp::TcpOptionWindowScale::copy (const TcpOptionWindowScale & other) private
dup()
virtual TcpOptionWindowScale* inet::tcp::TcpOptionWindowScale::dup () const inline override virtual
Reimplemented from inet::tcp::TcpOption.
 {return new TcpOptionWindowScale(*this);}
getWindowScale()
virtual unsigned short inet::tcp::TcpOptionWindowScale::getWindowScale () const virtual
Referenced by inet::tcp::TcpConnection::processWSOption(), and inet::tcp::TcpConnection::writeHeaderOptions().
operator=()
TcpOptionWindowScale& inet::tcp::TcpOptionWindowScale::operator= (const TcpOptionWindowScale & other)
operator==()
bool inet::tcp::TcpOptionWindowScale::operator== (const TcpOptionWindowScale &) protected delete
parsimPack()
virtual void inet::tcp::TcpOptionWindowScale::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::TcpOptionWindowScale::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimUnpacking().
setWindowScale()
virtual void inet::tcp::TcpOptionWindowScale::setWindowScale (unsigned short windowScale) virtual
Referenced by inet::tcp::TcpConnection::writeHeaderOptions().
Member Data Documentation
windowScale
unsigned short inet::tcp::TcpOptionWindowScale::windowScale = 0 protected
The documentation for this class was generated from the following file:
TcpHeader_m.h