INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3Instance Class Reference
inet::ospfv3::Ospfv3Instance Class Reference
#include <Ospfv3Instance.h>
Public Member Functions
Ospfv3Instance (int instanceId, Ospfv3Process *parentProcess, int addressFamily)
virtual ~Ospfv3Instance ()
int getInstanceID ()
int getAddressFamily ()
Ospfv3Process * getProcess () const
void init ()
bool hasArea (Ipv4Address)
void addArea (Ospfv3Area *)
Ospfv3Area * getAreaById (Ipv4Address areaId)
Ospfv3Area * getArea (int i)
void debugDump ()
Ipv4Address getNewInterAreaPrefixLinkStateID ()
void subtractInterAreaPrefixLinkStateID ()
void processPacket (Packet *pk)
int getUniqueId ()
int getAreaCount ()
void removeFromAllRetransmissionLists (LSAKeyType lsaKey)
std::string detailedInfo () const
Public Attributes
IInterfaceTable * ift = nullptr
Private Attributes
int addressFamily
int instanceID
Ospfv3Process * containingProcess
std::vector< Ospfv3Area * > areas
cModule * containingModule = nullptr
std::map< Ipv4Address, Ospfv3Area * > areasById
int ospfv3IfIndex = 0
Ipv4Address interAreaPrefixLsID = Ipv4Address::UNSPECIFIED_ADDRESS
Constructor & Destructor Documentation
Ospfv3Instance()
inet::ospfv3::Ospfv3Instance::Ospfv3Instance (int instanceId, Ospfv3Process * parentProcess, int addressFamily)
 {
     this->instanceID = instanceId;
     this->containingProcess = parentProcess;
     this->addressFamily = addressFamily;
     this->containingModule = findContainingNode(this->containingProcess);
     this->ift = check_and_cast<IInterfaceTable *>(containingModule->getSubmodule("interfaceTable"));
 }
~Ospfv3Instance()
inet::ospfv3::Ospfv3Instance::~Ospfv3Instance () virtual
 {
     long areaCount = areas.size();
     for (long i = 0; i < areaCount; i++) {
         delete areas[i];
     }
 }
Member Function Documentation
addArea()
void inet::ospfv3::Ospfv3Instance::addArea (Ospfv3Area * newArea)
 {
     this->areas.push_back(newArea);
     this->areasById[newArea->getAreaID()] = newArea;
 } // addArea
Referenced by inet::ospfv3::Ospfv3Process::parseConfig().
debugDump()
void inet::ospfv3::Ospfv3Instance::debugDump ()
 {
     EV_DEBUG << "Instance " << this->getInstanceID() << "\n";
     for (auto it = this->areas.begin(); it != this->areas.end(); it++) {
         EV_DEBUG << "\tArea id " << (*it)->getAreaID() << " has these interfaces:\n";
         (*it)->debugDump();
     }
 } // debugDump
detailedInfo()
std::string inet::ospfv3::Ospfv3Instance::detailedInfo () const
 {
     std::stringstream out;
     int processID = this->getProcess()->getProcessID();
     Ipv4Address routerID = this->getProcess()->getRouterID();
     out << "Ospfv3 " << processID << " address-family ";
     if (this->addressFamily == IPV4INSTANCE)
         out << "IPv4 (router-id " << routerID << ")\n\n";
     else
         out << "IPv6 (router-id " << routerID << ")\n\n";
     out << "Neighbor ID\tPri\tState\t\tDead Time\tInterface ID\tInterface\n";
     for (auto it = this->areas.begin(); it != this->areas.end(); it++) {
         int intfCount = (*it)->getInterfaceCount();
         for (int i = 0; i < intfCount; i++) {
             Ospfv3Interface *intf = (*it)->getInterface(i);
             int neiCount = intf->getNeighborCount();
             for (int n = 0; n < neiCount; n++) {
                 Ospfv3Neighbor *neighbor = intf->getNeighbor(n);
                 out << neighbor->getNeighborID() << "\t";
                 out << neighbor->getNeighborPriority() << "\t";
                 switch (neighbor->getState()) {
                     case Ospfv3Neighbor::DOWN_STATE:
                         out << "DOWN\t\t";
                         break;
                     case Ospfv3Neighbor::ATTEMPT_STATE:
                         out << "ATTEMPT\t\t";
                         break;
                     case Ospfv3Neighbor::INIT_STATE:
                         out << "INIT\t\t";
                         break;
                     case Ospfv3Neighbor::TWOWAY_STATE:
                         if (intf->getDesignatedID() == Ipv4Address::UNSPECIFIED_ADDRESS)
                             out << "2WAY\t\t";
                         else
                             out << "2WAY/DROTHER\t";
                         break;
                     case Ospfv3Neighbor::EXCHANGE_START_STATE:
                         out << "EXSTART\t\t";
                         break;
                     case Ospfv3Neighbor::EXCHANGE_STATE:
                         out << "EXCHANGE\t\t";
                         break;
                     case Ospfv3Neighbor::LOADING_STATE:
                         out << "LOADING\t\t";
                         break;
                     case Ospfv3Neighbor::FULL_STATE:
                         if (neighbor->getNeighborID() == intf->getDesignatedID())
                             out << "FULL/DR\t\t";
                         else if (neighbor->getNeighborID() == intf->getBackupID())
                             out << "FULL/BDR\t\t";
                         else
                             out << "FULL/DROTHER\t";
                         break;
                 }
                 int dead = intf->getDeadInterval() - ((int)simTime().dbl() - neighbor->getLastHelloTime());
                 if (dead < 0)
                     dead = 0;
                 out << dead << "\t\t"; // "00:00:40\t\t";
                 out << neighbor->getNeighborInterfaceID() << "\t\t";
                 out << intf->getIntName() << "\n";
             }
         }
     }
     return out.str();
 }
Referenced by inet::ospfv3::operator<<().
getAddressFamily()
int inet::ospfv3::Ospfv3Instance::getAddressFamily () inline
 { return this->addressFamily; }
Referenced by inet::ospfv3::Ospfv3Interface::detailedInfo(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
getArea()
Ospfv3Area* inet::ospfv3::Ospfv3Instance::getArea (int i) inline
 { return this->areas.at(i); }
Referenced by inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3Process::floodLSA(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
getAreaById()
Ospfv3Area * inet::ospfv3::Ospfv3Instance::getAreaById (Ipv4Address areaId)
 {
     auto areaIt = this->areasById.find(areaId);
     return (areaIt == this->areasById.end()) ? nullptr : areaIt->second;
 }
Referenced by inet::ospfv3::Ospfv3Process::findLSA(), inet::ospfv3::Ospfv3Process::floodLSA(), inet::ospfv3::Ospfv3Process::installLSA(), inet::ospfv3::Ospfv3Process::parseConfig(), processPacket(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
getAreaCount()
int inet::ospfv3::Ospfv3Instance::getAreaCount () inline
 { return this->areas.size(); }
Referenced by inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3Process::floodLSA(), inet::ospfv3::Ospfv3Interface::processLSU(), processPacket(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
getInstanceID()
int inet::ospfv3::Ospfv3Instance::getInstanceID () inline
 { return this->instanceID; }
Referenced by inet::ospfv3::Ospfv3Process::addInstance(), debugDump(), and inet::ospfv3::Ospfv3Interface::detailedInfo().
getNewInterAreaPrefixLinkStateID()
Ipv4Address inet::ospfv3::Ospfv3Instance::getNewInterAreaPrefixLinkStateID ()
 {
     Ipv4Address currIP = this->interAreaPrefixLsID;
     int newIP = currIP.getInt() + 1;
     this->interAreaPrefixLsID = Ipv4Address(newIP);
     return currIP;
 }
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA().
getProcess()
Ospfv3Process* inet::ospfv3::Ospfv3Instance::getProcess () const inline
 { return this->containingProcess; }
Referenced by inet::ospfv3::Ospfv3Interface::acknowledgeLSA(), inet::ospfv3::Ospfv3Interface::addDelayedAcknowledgement(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3InterfaceState::calculateDesignatedRouter(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Neighbor::clearRequestRetransmissionTimer(), inet::ospfv3::Ospfv3Neighbor::clearUpdateRetransmissionTimer(), detailedInfo(), inet::ospfv3::Ospfv3Interface::detailedInfo(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::ospfv3::Ospfv3Neighbor::needAdjacency(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Interface::processDDPacket(), inet::ospfv3::Ospfv3InterfaceStateDown::processEvent(), inet::ospfv3::Ospfv3NeighborStateAttempt::processEvent(), inet::ospfv3::Ospfv3NeighborStateFull::processEvent(), inet::ospfv3::Ospfv3NeighborStateLoading::processEvent(), inet::ospfv3::Ospfv3NeighborState2Way::processEvent(), inet::ospfv3::Ospfv3NeighborStateDown::processEvent(), inet::ospfv3::Ospfv3NeighborStateExchange::processEvent(), inet::ospfv3::Ospfv3NeighborStateInit::processEvent(), inet::ospfv3::Ospfv3InterfaceStateDrOther::processEvent(), inet::ospfv3::Ospfv3NeighborStateExStart::processEvent(), inet::ospfv3::Ospfv3InterfaceStateDr::processEvent(), inet::ospfv3::Ospfv3InterfaceStateWaiting::processEvent(), inet::ospfv3::Ospfv3InterfaceStatePointToPoint::processEvent(), inet::ospfv3::Ospfv3InterfaceStateBackup::processEvent(), inet::ospfv3::Ospfv3Interface::processHelloPacket(), inet::ospfv3::Ospfv3Interface::processLSR(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Neighbor::reset(), inet::ospfv3::Ospfv3Neighbor::retransmitDatabaseDescriptionPacket(), inet::ospfv3::Ospfv3Neighbor::retransmitUpdatePacket(), inet::ospfv3::Ospfv3Neighbor::sendDDPacket(), inet::ospfv3::Ospfv3Interface::sendDelayedAcknowledgements(), inet::ospfv3::Ospfv3Neighbor::sendLinkStateRequestPacket(), inet::ospfv3::Ospfv3Interface::sendLSAcknowledgement(), inet::ospfv3::Ospfv3Neighbor::startRequestRetransmissionTimer(), inet::ospfv3::Ospfv3Neighbor::startUpdateRetransmissionTimer(), inet::ospfv3::Ospfv3Interface::~Ospfv3Interface(), and inet::ospfv3::Ospfv3Neighbor::~Ospfv3Neighbor().
getUniqueId()
int inet::ospfv3::Ospfv3Instance::getUniqueId () inline
 { return ospfv3IfIndex++; }
hasArea()
bool inet::ospfv3::Ospfv3Instance::hasArea (Ipv4Address areaId)
 {
     return containsKey(this->areasById, areaId);
 } // hasArea
Referenced by inet::ospfv3::Ospfv3Process::parseConfig().
init()
void inet::ospfv3::Ospfv3Instance::init ()
 {
     for (auto it = this->areas.begin(); it != this->areas.end(); it++)
         (*it)->init();
     WATCH_PTRVECTOR(this->areas);
 } // init
processPacket()
void inet::ospfv3::Ospfv3Instance::processPacket (Packet * pk)
 {
     const auto& packet = pk->peekAtFront<Ospfv3Packet>();
     EV_INFO << "Process " << this->containingProcess->getProcessID() << " received packet: (" << packet->getClassName() << ")" << packet->getName() << "\n";
     if (packet->getVersion() != 3) {
         delete pk;
         return;
     }
     int intfId = pk->getTag<InterfaceInd>()->getInterfaceId();
     Ipv4Address areaId = packet->getAreaID();
     Ospfv3Area *area = this->getAreaById(packet->getAreaID());
     if (area != nullptr) {
         Ospfv3Interface *intf = area->getInterfaceById(intfId);
         if (intf == nullptr) {
             EV_DEBUG << "Interface is null in instance::processPacket\n";
             // it must be the backbone area and...
             if (areaId == Ipv4Address::UNSPECIFIED_ADDRESS) {
                 if (this->getAreaCount() > 1) {
                     // it must be a virtual link and the source router's router ID must be the endpoint of this virtual link and...
                     intf = area->findVirtualLink(packet->getRouterID());
                     if (intf != nullptr) {
                         Ospfv3Area *virtualLinkTransitArea = this->getAreaById(intf->getTransitAreaID());
                         if (virtualLinkTransitArea != nullptr) {
                             // the receiving interface must attach to the virtual link's configured transit area
                             Ospfv3Interface *virtualLinkInterface = virtualLinkTransitArea->getInterfaceById(intfId);
                             //
                             if (virtualLinkInterface == nullptr) {
                                 intf = nullptr;
                             }
                         }
                         else {
                             intf = nullptr;
                         }
                     }
                 }
             }
         }
         if (intf != nullptr) {
             Ipv6Address destinationAddress = pk->getTag<L3AddressInd>()->getDestAddress().toIpv6();
             Ipv6Address allDRouters = Ipv6Address::ALL_OSPF_DESIGNATED_ROUTERS_MCAST;
             Ospfv3Interface::Ospfv3InterfaceFaState interfaceState = intf->getState();
             // if destination address is ALL_D_ROUTERS the receiving interface must be in DesignatedRouter or Backup state
             if (((destinationAddress == allDRouters) &&
                  ((interfaceState == Ospfv3Interface::INTERFACE_STATE_DESIGNATED) ||
                   (interfaceState == Ospfv3Interface::INTERFACE_STATE_BACKUP))) ||
                 (destinationAddress != allDRouters))
             {
                 // packet authentication
                 ospf::OspfPacketType packetType = static_cast<ospf::OspfPacketType>(packet->getType());
                 Ospfv3Neighbor *neighbor = nullptr;
                 // all packets except HelloPackets are sent only along adjacencies, so a Neighbor must exist
                 if (packetType != ospf::OspfPacketType::HELLO_PACKET)
                     neighbor = intf->getNeighborById(packet->getRouterID());
                 switch (packetType) {
                     case ospf::OspfPacketType::HELLO_PACKET:
                         intf->processHelloPacket(pk);
                         break;
                     case ospf::OspfPacketType::DATABASE_DESCRIPTION_PACKET:
                         if (neighbor != nullptr) {
                             EV_DEBUG << "Instance is sending packet to interface\n";
                             intf->processDDPacket(pk);
                         }
                         break;
                     case ospf::OspfPacketType::LINKSTATE_REQUEST_PACKET:
                         if (neighbor != nullptr) {
                             intf->processLSR(pk, neighbor);
                         }
                         break;
                     case ospf::OspfPacketType::LINKSTATE_UPDATE_PACKET:
                         if (neighbor != nullptr) {
                             intf->processLSU(pk, neighbor);
                         }
                         break;
                     case ospf::OspfPacketType::LINKSTATE_ACKNOWLEDGEMENT_PACKET:
                         if (neighbor != nullptr) {
                             intf->processLSAck(pk, neighbor);
                         }
                         break;
                     default:
                         break;
                 }
             }
             else {
                 delete pk;
             }
         }
     }
 } // processPacket
Referenced by inet::ospfv3::Ospfv3Process::handleMessage().
removeFromAllRetransmissionLists()
void inet::ospfv3::Ospfv3Instance::removeFromAllRetransmissionLists (LSAKeyType lsaKey)
 {
     long areaCount = areas.size();
     for (long i = 0; i < areaCount; i++) {
         areas.at(i)->removeFromAllRetransmissionLists(lsaKey);
     }
 }
Referenced by inet::ospfv3::Ospfv3Interface::processLSU().
subtractInterAreaPrefixLinkStateID()
void inet::ospfv3::Ospfv3Instance::subtractInterAreaPrefixLinkStateID ()
 {
     Ipv4Address currIP = this->interAreaPrefixLsID;
     int newIP = currIP.getInt() - 1;
     this->interAreaPrefixLsID = Ipv4Address(newIP);
 }
Member Data Documentation
addressFamily
int inet::ospfv3::Ospfv3Instance::addressFamily private
Referenced by detailedInfo(), and Ospfv3Instance().
areas
std::vector<Ospfv3Area *> inet::ospfv3::Ospfv3Instance::areas private
Referenced by addArea(), debugDump(), detailedInfo(), init(), removeFromAllRetransmissionLists(), and ~Ospfv3Instance().
areasById
std::map<Ipv4Address, Ospfv3Area *> inet::ospfv3::Ospfv3Instance::areasById private
Referenced by addArea(), getAreaById(), and hasArea().
containingModule
cModule* inet::ospfv3::Ospfv3Instance::containingModule = nullptr private
Referenced by Ospfv3Instance().
containingProcess
Ospfv3Process* inet::ospfv3::Ospfv3Instance::containingProcess private
Referenced by Ospfv3Instance(), and processPacket().
ift
IInterfaceTable* inet::ospfv3::Ospfv3Instance::ift = nullptr
Referenced by Ospfv3Instance().
instanceID
int inet::ospfv3::Ospfv3Instance::instanceID private
Referenced by Ospfv3Instance().
interAreaPrefixLsID
Ipv4Address inet::ospfv3::Ospfv3Instance::interAreaPrefixLsID = Ipv4Address::UNSPECIFIED_ADDRESS private
Referenced by getNewInterAreaPrefixLinkStateID(), and subtractInterAreaPrefixLinkStateID().
ospfv3IfIndex
int inet::ospfv3::Ospfv3Instance::ospfv3IfIndex = 0 private
The documentation for this class was generated from the following files:
Ospfv3Instance.h
Ospfv3Instance.cc