INET Framework for OMNeT++/OMNEST: inet::Ipv4SocketConnectCommand Class Reference
inet::Ipv4SocketConnectCommand Class Reference
Class generated from inet/networklayer/contract/ipv4/Ipv4SocketCommand.msg:37 by opp_msgtool.
#include <Ipv4SocketCommand_m.h>
Public Member Functions
Ipv4SocketConnectCommand ()
Ipv4SocketConnectCommand (const Ipv4SocketConnectCommand &other)
virtual ~Ipv4SocketConnectCommand ()
Ipv4SocketConnectCommand & operator= (const Ipv4SocketConnectCommand &other)
virtual Ipv4SocketConnectCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ipv4Address & getRemoteAddress () const
virtual Ipv4Address & getRemoteAddressForUpdate ()
virtual void setRemoteAddress (const Ipv4Address &remoteAddress)
Public Member Functions inherited from inet::Ipv4SocketCommandBase
Ipv4SocketCommandBase ()
Ipv4SocketCommandBase (const Ipv4SocketCommandBase &other)
virtual ~Ipv4SocketCommandBase ()
Ipv4SocketCommandBase & operator= (const Ipv4SocketCommandBase &other)
Protected Member Functions
bool operator== (const Ipv4SocketConnectCommand &)=delete
Protected Member Functions inherited from inet::Ipv4SocketCommandBase
bool operator== (const Ipv4SocketCommandBase &)=delete
Protected Attributes
Ipv4Address remoteAddress
Private Member Functions
void copy (const Ipv4SocketConnectCommand &other)
Detailed Description
Class generated from inet/networklayer/contract/ipv4/Ipv4SocketCommand.msg:37 by opp_msgtool.
class Ipv4SocketConnectCommand extends Ipv4SocketCommandBase
{
    Ipv4Address remoteAddress;
}
Constructor & Destructor Documentation
Ipv4SocketConnectCommand() [1/2]
inet::Ipv4SocketConnectCommand::Ipv4SocketConnectCommand ()
Ipv4SocketConnectCommand() [2/2]
inet::Ipv4SocketConnectCommand::Ipv4SocketConnectCommand (const Ipv4SocketConnectCommand & other)
~Ipv4SocketConnectCommand()
virtual inet::Ipv4SocketConnectCommand::~Ipv4SocketConnectCommand () virtual
Member Function Documentation
copy()
void inet::Ipv4SocketConnectCommand::copy (const Ipv4SocketConnectCommand & other) private
dup()
virtual Ipv4SocketConnectCommand* inet::Ipv4SocketConnectCommand::dup () const inline override virtual
Reimplemented from inet::Ipv4SocketCommandBase.
 {return new Ipv4SocketConnectCommand(*this);}
getRemoteAddress()
virtual const Ipv4Address& inet::Ipv4SocketConnectCommand::getRemoteAddress () const virtual
getRemoteAddressForUpdate()
virtual Ipv4Address& inet::Ipv4SocketConnectCommand::getRemoteAddressForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<Ipv4SocketConnectCommand*>(this)->getRemoteAddress());}
operator=()
Ipv4SocketConnectCommand& inet::Ipv4SocketConnectCommand::operator= (const Ipv4SocketConnectCommand & other)
operator==()
bool inet::Ipv4SocketConnectCommand::operator== (const Ipv4SocketConnectCommand &) protected delete
parsimPack()
virtual void inet::Ipv4SocketConnectCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::Ipv4SocketCommandBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv4SocketConnectCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::Ipv4SocketCommandBase.
Referenced by inet::doParsimUnpacking().
setRemoteAddress()
virtual void inet::Ipv4SocketConnectCommand::setRemoteAddress (const Ipv4Address & remoteAddress) virtual
Referenced by inet::Ipv4Socket::connect().
Member Data Documentation
remoteAddress
Ipv4Address inet::Ipv4SocketConnectCommand::remoteAddress protected
The documentation for this class was generated from the following file:
Ipv4SocketCommand_m.h