INET Framework for OMNeT++/OMNEST: inet::L3AddressTagBase Class Reference
inet::L3AddressTagBase Class Reference
Class generated from inet/networklayer/common/L3AddressTag.msg:14 by opp_msgtool.
#include <L3AddressTag_m.h>
Public Member Functions
L3AddressTagBase ()
L3AddressTagBase (const L3AddressTagBase &other)
virtual ~L3AddressTagBase ()
L3AddressTagBase & operator= (const L3AddressTagBase &other)
virtual L3AddressTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const L3Address & getSrcAddress () const
virtual L3Address & getSrcAddressForUpdate ()
virtual void setSrcAddress (const L3Address &srcAddress)
virtual const L3Address & getDestAddress () const
virtual L3Address & getDestAddressForUpdate ()
virtual void setDestAddress (const L3Address &destAddress)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const L3AddressTagBase &)=delete
Protected Attributes
L3Address srcAddress
L3Address destAddress
Private Member Functions
void copy (const L3AddressTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/networklayer/common/L3AddressTag.msg:14 by opp_msgtool.
class L3AddressTagBase extends TagBase
{
    L3Address srcAddress;      // may be unspecified
    L3Address destAddress; // always specified
}
Constructor & Destructor Documentation
L3AddressTagBase() [1/2]
inet::L3AddressTagBase::L3AddressTagBase ()
L3AddressTagBase() [2/2]
inet::L3AddressTagBase::L3AddressTagBase (const L3AddressTagBase & other)
~L3AddressTagBase()
virtual inet::L3AddressTagBase::~L3AddressTagBase () virtual
Member Function Documentation
copy()
void inet::L3AddressTagBase::copy (const L3AddressTagBase & other) private
dup()
virtual L3AddressTagBase* inet::L3AddressTagBase::dup () const inline override virtual
Reimplemented in inet::L3AddressInd, and inet::L3AddressReq.
 {return new L3AddressTagBase(*this);}
getDestAddress()
virtual const L3Address& inet::L3AddressTagBase::getDestAddress () const virtual
Referenced by inet::Ipv6NeighbourDiscovery::validateNaPacket(), and inet::Ipv6NeighbourDiscovery::validateNsPacket().
getDestAddressForUpdate()
virtual L3Address& inet::L3AddressTagBase::getDestAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<L3AddressTagBase*>(this)->getDestAddress());}
getSrcAddress()
virtual const L3Address& inet::L3AddressTagBase::getSrcAddress () const virtual
Referenced by inet::PimSm::processAssertPacket(), inet::ospfv3::Ospfv3Interface::processHelloPacket(), inet::Ipv6NeighbourDiscovery::processNsForNonTentativeAddress(), inet::Igmpv3::processQuery(), inet::Udp::processUDPPacket(), inet::Ipv6NeighbourDiscovery::sendSolicitedNa(), inet::Ipv6NeighbourDiscovery::validateNsPacket(), inet::Ipv6NeighbourDiscovery::validateRsPacket(), inet::Pim::verifyCrc(), and inet::Udp::verifyCrc().
getSrcAddressForUpdate()
virtual L3Address& inet::L3AddressTagBase::getSrcAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<L3AddressTagBase*>(this)->getSrcAddress());}
operator=()
L3AddressTagBase& inet::L3AddressTagBase::operator= (const L3AddressTagBase & other)
operator==()
bool inet::L3AddressTagBase::operator== (const L3AddressTagBase &) protected delete
parsimPack()
virtual void inet::L3AddressTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::L3AddressInd, and inet::L3AddressReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::L3AddressTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::L3AddressInd, and inet::L3AddressReq.
Referenced by inet::doParsimUnpacking().
setDestAddress()
virtual void inet::L3AddressTagBase::setDestAddress (const L3Address & destAddress) virtual
Referenced by inet::Dsdv::handleMessageWhenUp(), inet::Dsdv::handleSelfMessage(), inet::EchoProtocol::processEchoRequest(), inet::Icmpv6::processEchoRequest(), inet::Ipv6Socket::sendTo(), inet::Ipv4Socket::sendTo(), inet::L3Socket::sendTo(), inet::UdpSocket::sendTo(), and inet::sctp::SctpAssociation::sendToIP().
setSrcAddress()
virtual void inet::L3AddressTagBase::setSrcAddress (const L3Address & srcAddress) virtual
Referenced by inet::Ipv4Encap::decapsulate(), inet::NextHopForwarding::decapsulate(), inet::Flooding::decapsulate(), inet::Ipv6::decapsulate(), inet::Ipv4::decapsulate(), inet::Ipv6Tunneling::encapsulateDatagram(), inet::PimSm::forwardMulticastData(), inet::EchoProtocol::processEchoRequest(), inet::Icmp::processEchoRequest(), inet::sctp::Sctp::sendAbortFromMain(), inet::Gpsr::sendBeacon(), inet::Ipv6NeighbourDiscovery::sendPacketToIpv6Module(), inet::PingApp::sendPingRequest(), inet::sctp::Sctp::sendShutdownCompleteFromMain(), inet::PimDm::sendToIP(), inet::tcp::TcpConnection::sendToIP(), and inet::Udp::sendUpErrorIndication().
Member Data Documentation
destAddress
L3Address inet::L3AddressTagBase::destAddress protected
srcAddress
L3Address inet::L3AddressTagBase::srcAddress protected
The documentation for this class was generated from the following file:
L3AddressTag_m.h