INET Framework for OMNeT++/OMNEST: inet::physicallayer::AntennaBase Class Reference
inet::physicallayer::AntennaBase Class Reference
#include <AntennaBase.h>
Public Member Functions
AntennaBase ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual bool isDirectional () const override
Returns true if the antenna has directional selectivity (i.e.
virtual IMobility * getMobility () const override
Returns the mobility of this antenna that describes its position and orientation over time.
virtual int getNumAntennas () const override
Returns the number of antennas in the array.
Public Member Functions inherited from inet::physicallayer::IAntenna
virtual Ptr< const IAntennaGain > getGain () const =0
Returns the antenna's gain calculator for directional selectivity.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
Protected Attributes
opp_component_ptr< IMobility > mobility
int numAntennas
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
AntennaBase()
inet::physicallayer::AntennaBase::AntennaBase ()
                          :
     mobility(nullptr),
     numAntennas(-1)
 {
 }
Member Function Documentation
getMobility()
virtual IMobility* inet::physicallayer::AntennaBase::getMobility () const inline override virtual
Returns the mobility of this antenna that describes its position and orientation over time.
Implements inet::physicallayer::IAntenna.
 { return mobility; }
getNumAntennas()
virtual int inet::physicallayer::AntennaBase::getNumAntennas () const inline override virtual
Returns the number of antennas in the array.
Implements inet::physicallayer::IAntenna.
 { return numAntennas; }
initialize()
void inet::physicallayer::AntennaBase::initialize (int stage) override protected virtual
Reimplemented in inet::physicallayer::InterpolatingAntenna, inet::physicallayer::AxiallySymmetricAntenna, inet::physicallayer::ParabolicAntenna, inet::physicallayer::ConstantGainAntenna, inet::physicallayer::CosineAntenna, and inet::physicallayer::DipoleAntenna.
 {
     if (stage == INITSTAGE_LOCAL) {
         mobility = check_and_cast_nullable<IMobility *>(getSubmodule("mobility"));
         if (mobility == nullptr)
             mobility = getModuleFromPar<IMobility>(par("mobilityModule"), this);
         numAntennas = par("numAntennas");
     }
 }
Referenced by inet::physicallayer::ConstantGainAntenna::initialize(), inet::physicallayer::DipoleAntenna::initialize(), inet::physicallayer::CosineAntenna::initialize(), inet::physicallayer::ParabolicAntenna::initialize(), inet::physicallayer::AxiallySymmetricAntenna::initialize(), and inet::physicallayer::InterpolatingAntenna::initialize().
isDirectional()
virtual bool inet::physicallayer::AntennaBase::isDirectional () const inline override virtual
Returns true if the antenna has directional selectivity (i.e.
the gain is not always 1).
Implements inet::physicallayer::IAntenna.
 { return getGain()->getMinGain() != 1 || getGain()->getMaxGain() != 1; }
printToStream()
std::ostream & inet::physicallayer::AntennaBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::InterpolatingAntenna, inet::physicallayer::AxiallySymmetricAntenna, inet::physicallayer::ParabolicAntenna, inet::physicallayer::CosineAntenna, inet::physicallayer::DipoleAntenna, inet::physicallayer::ConstantGainAntenna, and inet::physicallayer::IsotropicAntenna.
 {
     return stream;
 }
Referenced by inet::physicallayer::IsotropicAntenna::printToStream(), inet::physicallayer::ConstantGainAntenna::printToStream(), inet::physicallayer::DipoleAntenna::printToStream(), inet::physicallayer::CosineAntenna::printToStream(), inet::physicallayer::ParabolicAntenna::printToStream(), inet::physicallayer::AxiallySymmetricAntenna::printToStream(), and inet::physicallayer::InterpolatingAntenna::printToStream().
Member Data Documentation
mobility
opp_component_ptr<IMobility> inet::physicallayer::AntennaBase::mobility protected
Referenced by initialize().
numAntennas
int inet::physicallayer::AntennaBase::numAntennas protected
Referenced by initialize().
The documentation for this class was generated from the following files:
AntennaBase.h
AntennaBase.cc