INET Framework for OMNeT++/OMNEST: inet::PacketTransmitterBase Class Reference
inet::PacketTransmitterBase Class Reference
#include <PacketTransmitterBase.h>
Public Member Functions
virtual ~PacketTransmitterBase ()
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::ClockUserModuleMixin< OperationalMixin< PacketProcessorBase > >
virtual void scheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void scheduleClockEventAfter (clocktime_t delay, ClockEvent *msg)
virtual cMessage * cancelClockEvent (ClockEvent *msg)
virtual void cancelAndDeleteClockEvent (ClockEvent *msg)
virtual void rescheduleClockEventAt (clocktime_t time, ClockEvent *msg)
virtual void rescheduleClockEventAfter (clocktime_t time, ClockEvent *msg)
virtual clocktime_t computeClockTimeFromSimTime (simtime_t time) const
virtual simtime_t computeSimTimeFromClockTime (clocktime_t time) const
virtual clocktime_t getClockTime () const
virtual clocktime_t getArrivalClockTime (ClockEvent *msg) const
Public Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
virtual void pushPacket (Packet *packet, cGate *gate)=0
Pushes the packet into the packet sink at the given gate.
Protected Member Functions
virtual void initialize (int stage) override
virtual void finish () override
virtual void handleMessageWhenUp (cMessage *message) override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual Signal * encodePacket (Packet *packet)
virtual void prepareSignal (Signal *signal)
virtual void sendSignalStart (Signal *signal, int transmissionId)
virtual void sendSignalProgress (Signal *signal, int transmissionId, b bitPosition, clocktime_t timePosition)
virtual void sendSignalEnd (Signal *signal, int transmissionId)
virtual clocktime_t calculateClockTimeDuration (const Packet *packet) const
virtual simtime_t calculateDuration (clocktime_t clockTimeDuration) const
virtual bool isTransmitting () const
Protected Member Functions inherited from inet::OperationalMixin< PacketProcessorBase >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void handleStopOperation (LifecycleOperation *operation)=0
virtual void handleCrashOperation (LifecycleOperation *operation)=0
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
cPar * dataratePar = nullptr
cGate * inputGate = nullptr
cGate * outputGate = nullptr
ModuleRef< IActivePacketSource > producer
bps txDatarate = bps(NaN)
Signal * txSignal = nullptr
ClockEvent * txEndTimer = nullptr
simtime_t txStartTime = -1
clocktime_t txStartClockTime = -1
clocktime_t txDurationClockTime = -1
Protected Attributes inherited from inet::OperationalMixin< PacketProcessorBase >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::OperationalMixin< PacketProcessorBase >
enum State
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Constructor & Destructor Documentation
~PacketTransmitterBase()
inet::PacketTransmitterBase::~PacketTransmitterBase () virtual
 {
     cancelAndDeleteClockEvent(txEndTimer);
     txEndTimer = nullptr;
     delete txSignal;
     txSignal = nullptr;
 }
Member Function Documentation
calculateClockTimeDuration()
clocktime_t inet::PacketTransmitterBase::calculateClockTimeDuration (const Packet * packet) const protected virtual
 {
     s duration = packet->getTotalLength() / txDatarate;
     EV_TRACE << "Calculating signal duration" << EV_FIELD(packet) << EV_FIELD(duration, simsec(duration)) << EV_ENDL;
     return duration.get();
 }
Referenced by encodePacket().
calculateDuration()
simtime_t inet::PacketTransmitterBase::calculateDuration (clocktime_t clockTimeDuration) const protected virtual
 {
     return computeSimTimeFromClockTime(txStartClockTime + clockTimeDuration) - txStartTime;
 }
Referenced by encodePacket().
canPushPacket()
virtual bool inet::PacketTransmitterBase::canPushPacket (Packet * packet, cGate * gate) const inline override virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
 { return canPushSomePacket(gate); }
canPushSomePacket()
virtual bool inet::PacketTransmitterBase::canPushSomePacket (cGate * gate) const inline override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::StreamingTransmitterBase.
 { return !txEndTimer->isScheduled(); } // TODO: add hasCarrier
Referenced by inet::StreamingTransmitterBase::canPushSomePacket().
encodePacket()
Signal * inet::PacketTransmitterBase::encodePacket (Packet * packet) protected virtual
 {
     txDurationClockTime = calculateClockTimeDuration(packet);
     // TODO: this is just a weak approximation which ignores the past and future drift and drift rate changes of the clock
     simtime_t packetTransmissionTime = CLOCKTIME_AS_SIMTIME(txDurationClockTime);
     simtime_t bitTransmissionTime = packet->getBitLength() != 0 ? CLOCKTIME_AS_SIMTIME(txDurationClockTime / packet->getBitLength()) : 0;
     auto packetEvent = new PacketTransmittedEvent();
     packetEvent->setDatarate(packet->getTotalLength() / s(txDurationClockTime.dbl()));
     insertPacketEvent(this, packet, PEK_TRANSMITTED, bitTransmissionTime, packetEvent);
     increaseTimeTag<TransmissionTimeTag>(packet, bitTransmissionTime, packetTransmissionTime);
     if (auto channel = dynamic_cast<cDatarateChannel *>(outputGate->findTransmissionChannel())) {
         insertPacketEvent(this, packet, PEK_PROPAGATED, channel->getDelay());
         increaseTimeTag<PropagationTimeTag>(packet, channel->getDelay(), channel->getDelay());
     }
     auto signal = new Signal(packet->getName());
     signal->encapsulate(packet);
     signal->setDuration(calculateDuration(txDurationClockTime));
     return signal;
 }
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::StreamThroughTransmitter::progressTx(), inet::StreamingTransmitter::startTx(), inet::PacketTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
finish()
void inet::PacketTransmitterBase::finish () override protected virtual
 {
     if (auto channel = dynamic_cast<cDatarateChannel *>(outputGate->findTransmissionChannel()))
         recordScalar("propagationTime", channel->getDelay());
 }
handleMessageWhenUp()
void inet::PacketTransmitterBase::handleMessageWhenUp (cMessage * message) override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
Reimplemented in inet::StreamThroughTransmitter, inet::PacketTransmitter, and inet::StreamingTransmitter.
 {
     auto packet = check_and_cast<Packet *>(message);
     pushPacket(packet, packet->getArrivalGate());
 }
Referenced by inet::PacketTransmitter::handleMessageWhenUp(), inet::StreamingTransmitter::handleMessageWhenUp(), and inet::StreamThroughTransmitter::handleMessageWhenUp().
handleStartOperation()
void inet::PacketTransmitterBase::handleStartOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 {
     if (producer != nullptr)
         producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
 }
initialize()
void inet::PacketTransmitterBase::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< PacketProcessorBase >.
Reimplemented in inet::StreamThroughTransmitter, and inet::StreamingTransmitterBase.
 {
     ClockUserModuleMixin::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         dataratePar = &par("datarate");
         txDatarate = bps(*dataratePar);
         inputGate = gate("in");
         outputGate = gate("out");
         producer.reference(inputGate, false);
         txEndTimer = new ClockEvent("TxEndTimer");
     }
     else if (stage == INITSTAGE_QUEUEING) {
         checkPacketOperationSupport(inputGate);
         if (producer != nullptr)
             producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
     }
 }
Referenced by inet::StreamingTransmitterBase::initialize().
isInitializeStage()
virtual bool inet::PacketTransmitterBase::isInitializeStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 { return stage == INITSTAGE_LINK_LAYER; }
isModuleStartStage()
virtual bool inet::PacketTransmitterBase::isModuleStartStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 { return stage == ModuleStartOperation::STAGE_LINK_LAYER; }
isModuleStopStage()
virtual bool inet::PacketTransmitterBase::isModuleStopStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< PacketProcessorBase >.
 { return stage == ModuleStopOperation::STAGE_LINK_LAYER; }
isTransmitting()
virtual bool inet::PacketTransmitterBase::isTransmitting () const inline protected virtual
 { return txSignal != nullptr; }
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::PacketTransmitter::endTx(), inet::StreamingTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), inet::PacketTransmitter::handleCrashOperation(), inet::StreamingTransmitter::handleCrashOperation(), inet::StreamThroughTransmitter::handleCrashOperation(), inet::PacketTransmitter::handleStopOperation(), inet::StreamingTransmitter::handleStopOperation(), inet::StreamThroughTransmitter::handleStopOperation(), inet::StreamThroughTransmitter::progressTx(), inet::StreamThroughTransmitter::pushPacketProgress(), inet::StreamingTransmitterBase::receiveSignal(), inet::StreamingTransmitter::startTx(), inet::PacketTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
prepareSignal()
void inet::PacketTransmitterBase::prepareSignal (Signal * signal) protected virtual
 {
     auto packet = check_and_cast<Packet *>(signal->getEncapsulatedPacket());
     auto oldPacketProtocolTag = packet->removeTagIfPresent<PacketProtocolTag>();
     packet->clearTags();
     if (oldPacketProtocolTag != nullptr) {
         auto newPacketProtocolTag = packet->addTag<PacketProtocolTag>();
         *newPacketProtocolTag = *oldPacketProtocolTag;
     }
 }
Referenced by sendSignalEnd(), sendSignalProgress(), sendSignalStart(), and inet::PacketTransmitter::startTx().
pushPacketEnd()
virtual void inet::PacketTransmitterBase::pushPacketEnd (Packet * packet, cGate * gate) inline override virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::StreamThroughTransmitter.
 { throw cRuntimeError("Invalid operation"); }
pushPacketProgress()
virtual void inet::PacketTransmitterBase::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) inline override virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::StreamThroughTransmitter, and inet::PacketTransmitter.
 { throw cRuntimeError("Invalid operation"); }
pushPacketStart()
virtual void inet::PacketTransmitterBase::pushPacketStart (Packet * packet, cGate * gate, bps datarate) inline override virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::StreamThroughTransmitter.
 { throw cRuntimeError("Invalid operation"); }
sendSignalEnd()
void inet::PacketTransmitterBase::sendSignalEnd (Signal * signal, int transmissionId) protected virtual
 {
     EV_INFO << "Transmitting signal end to channel" << EV_FIELD(signal) << EV_FIELD(transmissionId) << EV_ENDL;
     prepareSignal(signal);
     send(signal, SendOptions().duration(signal->getDuration()).finishTx(transmissionId), outputGate);
 }
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::StreamingTransmitter::endTx(), and inet::StreamThroughTransmitter::endTx().
sendSignalProgress()
void inet::PacketTransmitterBase::sendSignalProgress (Signal * signal, int transmissionId, b bitPosition, clocktime_t timePosition) protected virtual
 {
     simtime_t remainingDuration = signal->getDuration() - CLOCKTIME_AS_SIMTIME(timePosition);
     EV_INFO << "Transmitting signal progress to channel" << EV_FIELD(signal) << EV_FIELD(transmissionId) << EV_FIELD(remainingDuration, simsec(remainingDuration)) << EV_ENDL;
     prepareSignal(signal);
     send(signal, SendOptions().duration(signal->getDuration()).updateTx(transmissionId, remainingDuration), outputGate);
 }
Referenced by inet::StreamThroughTransmitter::progressTx(), and inet::StreamingTransmitterBase::scheduleAt().
sendSignalStart()
void inet::PacketTransmitterBase::sendSignalStart (Signal * signal, int transmissionId) protected virtual
 {
     EV_INFO << "Transmitting signal start to channel" << EV_FIELD(signal) << EV_ENDL;
     prepareSignal(signal);
     send(signal, SendOptions().duration(signal->getDuration()).transmissionId(transmissionId), outputGate);
 }
Referenced by inet::StreamingTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
supportsPacketPulling()
virtual bool inet::PacketTransmitterBase::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return false; }
supportsPacketPushing()
virtual bool inet::PacketTransmitterBase::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return inputGate == gate; }
Member Data Documentation
dataratePar
cPar* inet::PacketTransmitterBase::dataratePar = nullptr protected
Referenced by initialize(), inet::PacketTransmitter::startTx(), inet::StreamingTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
inputGate
cGate* inet::PacketTransmitterBase::inputGate = nullptr protected
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::PacketTransmitter::endTx(), inet::StreamingTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), handleStartOperation(), initialize(), and inet::StreamingTransmitterBase::receiveSignal().
outputGate
cGate* inet::PacketTransmitterBase::outputGate = nullptr protected
Referenced by encodePacket(), finish(), inet::StreamingTransmitterBase::initialize(), initialize(), inet::StreamingTransmitterBase::receiveSignal(), sendSignalEnd(), sendSignalProgress(), sendSignalStart(), and inet::PacketTransmitter::startTx().
producer
ModuleRef<IActivePacketSource> inet::PacketTransmitterBase::producer protected
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::PacketTransmitter::endTx(), inet::StreamingTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), handleStartOperation(), initialize(), and inet::StreamingTransmitterBase::receiveSignal().
txDatarate
bps inet::PacketTransmitterBase::txDatarate = bps(NaN) protected
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), calculateClockTimeDuration(), inet::StreamingTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), initialize(), inet::StreamThroughTransmitter::progressTx(), inet::StreamingTransmitterBase::scheduleAt(), inet::StreamThroughTransmitter::scheduleBufferUnderrunTimer(), inet::StreamingTransmitter::startTx(), inet::PacketTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
txDurationClockTime
clocktime_t inet::PacketTransmitterBase::txDurationClockTime = -1 protected
Referenced by encodePacket(), and inet::StreamingTransmitterBase::scheduleTxEndTimer().
txEndTimer
ClockEvent* inet::PacketTransmitterBase::txEndTimer = nullptr protected
Referenced by inet::PacketTransmitter::handleMessageWhenUp(), inet::StreamingTransmitter::handleMessageWhenUp(), inet::StreamThroughTransmitter::handleMessageWhenUp(), initialize(), inet::StreamingTransmitterBase::scheduleAt(), inet::PacketTransmitter::scheduleTxEndTimer(), inet::StreamingTransmitterBase::scheduleTxEndTimer(), and ~PacketTransmitterBase().
txSignal
Signal* inet::PacketTransmitterBase::txSignal = nullptr protected
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), inet::StreamingTransmitter::endTx(), inet::PacketTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), inet::StreamThroughTransmitter::progressTx(), inet::StreamThroughTransmitter::pushPacketEnd(), inet::StreamingTransmitterBase::scheduleAt(), inet::PacketTransmitter::startTx(), inet::StreamingTransmitter::startTx(), inet::StreamThroughTransmitter::startTx(), and ~PacketTransmitterBase().
txStartClockTime
clocktime_t inet::PacketTransmitterBase::txStartClockTime = -1 protected
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), calculateDuration(), inet::StreamingTransmitter::endTx(), inet::PacketTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), inet::StreamThroughTransmitter::progressTx(), inet::StreamingTransmitterBase::scheduleAt(), inet::StreamingTransmitterBase::scheduleTxEndTimer(), inet::StreamingTransmitter::startTx(), inet::PacketTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
txStartTime
simtime_t inet::PacketTransmitterBase::txStartTime = -1 protected
Referenced by inet::StreamingTransmitter::abortTx(), inet::StreamThroughTransmitter::abortTx(), calculateDuration(), inet::StreamingTransmitter::endTx(), inet::PacketTransmitter::endTx(), inet::StreamThroughTransmitter::endTx(), inet::StreamingTransmitterBase::scheduleAt(), inet::StreamingTransmitter::startTx(), inet::PacketTransmitter::startTx(), and inet::StreamThroughTransmitter::startTx().
The documentation for this class was generated from the following files:
PacketTransmitterBase.h
PacketTransmitterBase.cc