INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRecipientBlockAckAgreementPolicy Class Reference
inet::ieee80211::IRecipientBlockAckAgreementPolicy Class Reference abstract
#include <IRecipientBlockAckAgreementPolicy.h>
Public Member Functions
virtual ~IRecipientBlockAckAgreementPolicy ()
virtual bool isAddbaReqAccepted (const Ptr< const Ieee80211AddbaRequest > &addbaReq)=0
virtual bool isDelbaAccepted (const Ptr< const Ieee80211Delba > &delba)=0
virtual simtime_t getBlockAckTimeoutValue () const =0
virtual bool aMsduSupported () const =0
virtual bool delayedBlockAckPolicySupported () const =0
virtual int getMaximumAllowedBufferSize () const =0
Constructor & Destructor Documentation
~IRecipientBlockAckAgreementPolicy()
virtual inet::ieee80211::IRecipientBlockAckAgreementPolicy::~IRecipientBlockAckAgreementPolicy () inline virtual
 {}
Member Function Documentation
aMsduSupported()
virtual bool inet::ieee80211::IRecipientBlockAckAgreementPolicy::aMsduSupported () const pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementPolicy.
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::buildAddbaResponse().
delayedBlockAckPolicySupported()
virtual bool inet::ieee80211::IRecipientBlockAckAgreementPolicy::delayedBlockAckPolicySupported () const pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementPolicy.
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::buildAddbaResponse().
getBlockAckTimeoutValue()
virtual simtime_t inet::ieee80211::IRecipientBlockAckAgreementPolicy::getBlockAckTimeoutValue () const pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementPolicy.
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::buildAddbaResponse().
getMaximumAllowedBufferSize()
virtual int inet::ieee80211::IRecipientBlockAckAgreementPolicy::getMaximumAllowedBufferSize () const pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementPolicy.
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::buildAddbaResponse().
isAddbaReqAccepted()
virtual bool inet::ieee80211::IRecipientBlockAckAgreementPolicy::isAddbaReqAccepted (const Ptr< const Ieee80211AddbaRequest > & addbaReq) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementPolicy.
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::processReceivedAddbaRequest().
isDelbaAccepted()
virtual bool inet::ieee80211::IRecipientBlockAckAgreementPolicy::isDelbaAccepted (const Ptr< const Ieee80211Delba > & delba) pure virtual
Implemented in inet::ieee80211::RecipientBlockAckAgreementPolicy.
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::processReceivedDelba().
The documentation for this class was generated from the following file:
IRecipientBlockAckAgreementPolicy.h