INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_AuthenticateRequest Class Reference
inet::ieee80211::Ieee80211Prim_AuthenticateRequest Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:134 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AuthenticateRequest ()
Ieee80211Prim_AuthenticateRequest (const Ieee80211Prim_AuthenticateRequest &other)
virtual ~Ieee80211Prim_AuthenticateRequest ()
Ieee80211Prim_AuthenticateRequest & operator= (const Ieee80211Prim_AuthenticateRequest &other)
virtual Ieee80211Prim_AuthenticateRequest * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::MacAddress & getAddress () const
virtual ::inet::MacAddress & getAddressForUpdate ()
virtual void setAddress (const ::inet::MacAddress &address)
virtual ::omnetpp::simtime_t getTimeout () const
virtual void setTimeout (::omnetpp::simtime_t timeout)
Public Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
Ieee80211PrimRequest ()
Ieee80211PrimRequest (const Ieee80211PrimRequest &other)
virtual ~Ieee80211PrimRequest ()
Ieee80211PrimRequest & operator= (const Ieee80211PrimRequest &other)
Protected Member Functions
bool operator== (const Ieee80211Prim_AuthenticateRequest &)=delete
Protected Member Functions inherited from inet::ieee80211::Ieee80211PrimRequest
bool operator== (const Ieee80211PrimRequest &)=delete
Protected Attributes
::inet::MacAddress address
::omnetpp::simtime_t timeout = SIMTIME_ZERO
Private Member Functions
void copy (const Ieee80211Prim_AuthenticateRequest &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:134 by opp_msgtool.
//
// Losely based on MLME-AUTHENTICATE.request.
//
// Note: the "authType" parameter (Open System, Shared Key, etc) is omitted.
// The authentication procedure is simulated by this model by exchanging
// a number of "dummy" authentication frames without real contents,
// and it is configured in the AP how many authentication steps it requires.
//
class Ieee80211Prim_AuthenticateRequest extends Ieee80211PrimRequest
{
    MacAddress address;
    simtime_t timeout;
}
Constructor & Destructor Documentation
Ieee80211Prim_AuthenticateRequest() [1/2]
inet::ieee80211::Ieee80211Prim_AuthenticateRequest::Ieee80211Prim_AuthenticateRequest ()
Ieee80211Prim_AuthenticateRequest() [2/2]
inet::ieee80211::Ieee80211Prim_AuthenticateRequest::Ieee80211Prim_AuthenticateRequest (const Ieee80211Prim_AuthenticateRequest & other)
~Ieee80211Prim_AuthenticateRequest()
virtual inet::ieee80211::Ieee80211Prim_AuthenticateRequest::~Ieee80211Prim_AuthenticateRequest () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211Prim_AuthenticateRequest::copy (const Ieee80211Prim_AuthenticateRequest & other) private
dup()
virtual Ieee80211Prim_AuthenticateRequest* inet::ieee80211::Ieee80211Prim_AuthenticateRequest::dup () const inline override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
 {return new Ieee80211Prim_AuthenticateRequest(*this);}
getAddress()
virtual const ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_AuthenticateRequest::getAddress () const virtual
getAddressForUpdate()
virtual ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_AuthenticateRequest::getAddressForUpdate () inline
 { return const_cast<::inet::MacAddress&>(const_cast<Ieee80211Prim_AuthenticateRequest*>(this)->getAddress());}
getTimeout()
virtual ::omnetpp::simtime_t inet::ieee80211::Ieee80211Prim_AuthenticateRequest::getTimeout () const
operator=()
Ieee80211Prim_AuthenticateRequest& inet::ieee80211::Ieee80211Prim_AuthenticateRequest::operator= (const Ieee80211Prim_AuthenticateRequest & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_AuthenticateRequest::operator== (const Ieee80211Prim_AuthenticateRequest &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateRequest::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateRequest::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimRequest.
Referenced by inet::ieee80211::doParsimUnpacking().
setAddress()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateRequest::setAddress (const ::inet::MacAddress & address) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendAuthenticateRequest().
setTimeout()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateRequest::setTimeout (::omnetpp::simtime_t timeout) virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::sendAuthenticateRequest().
Member Data Documentation
address
::inet::MacAddress inet::ieee80211::Ieee80211Prim_AuthenticateRequest::address protected
timeout
::omnetpp::simtime_t inet::ieee80211::Ieee80211Prim_AuthenticateRequest::timeout = SIMTIME_ZERO protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h