INET Framework for OMNeT++/OMNEST: inet::SnirInd Class Reference
inet::SnirInd Class Reference
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/SignalTag.msg:104 by opp_msgtool.
#include <SignalTag_m.h>
Public Member Functions
SnirInd ()
SnirInd (const SnirInd &other)
virtual ~SnirInd ()
SnirInd & operator= (const SnirInd &other)
virtual SnirInd * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual double getMinimumSnir () const
virtual void setMinimumSnir (double minimumSnir)
virtual double getMaximumSnir () const
virtual void setMaximumSnir (double maximumSnir)
virtual double getAverageSnir () const
virtual void setAverageSnir (double averageSnir)
Public Member Functions inherited from inet::SignalTagBase
SignalTagBase ()
SignalTagBase (const SignalTagBase &other)
virtual ~SignalTagBase ()
SignalTagBase & operator= (const SignalTagBase &other)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SnirInd &)=delete
Protected Member Functions inherited from inet::SignalTagBase
bool operator== (const SignalTagBase &)=delete
Protected Attributes
double minimumSnir = NaN
double maximumSnir = NaN
double averageSnir = NaN
Private Member Functions
void copy (const SnirInd &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/SignalTag.msg:104 by opp_msgtool.
//
// This indication specifies the signal to noise ratio that was detected during receiving the packet.
// It may be present on a packet from the phyiscal layer to the application.
//
class SnirInd extends SignalTagBase
{
    double minimumSnir = NaN; // minimum signal to noise plus interference ratio in the range (0, +infinity) or NaN if unknown.
    double maximumSnir = NaN; // maximum signal to noise plus interference ratio in the range (0, +infinity) or NaN if unknown.
    double averageSnir = NaN; // average signal to noise plus interference ratio in the range (0, +infinity) or NaN if unknown.
}
Constructor & Destructor Documentation
SnirInd() [1/2]
inet::SnirInd::SnirInd ()
SnirInd() [2/2]
inet::SnirInd::SnirInd (const SnirInd & other)
~SnirInd()
virtual inet::SnirInd::~SnirInd () virtual
Member Function Documentation
copy()
void inet::SnirInd::copy (const SnirInd & other) private
dup()
virtual SnirInd* inet::SnirInd::dup () const inline override virtual
Reimplemented from inet::SignalTagBase.
 {return new SnirInd(*this);}
getAverageSnir()
virtual double inet::SnirInd::getAverageSnir () const virtual
getMaximumSnir()
virtual double inet::SnirInd::getMaximumSnir () const virtual
getMinimumSnir()
virtual double inet::SnirInd::getMinimumSnir () const virtual
operator=()
SnirInd& inet::SnirInd::operator= (const SnirInd & other)
operator==()
bool inet::SnirInd::operator== (const SnirInd &) protected delete
parsimPack()
virtual void inet::SnirInd::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignalTagBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SnirInd::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignalTagBase.
Referenced by inet::doParsimUnpacking().
setAverageSnir()
virtual void inet::SnirInd::setAverageSnir (double averageSnir) virtual
setMaximumSnir()
virtual void inet::SnirInd::setMaximumSnir (double maximumSnir) virtual
setMinimumSnir()
virtual void inet::SnirInd::setMinimumSnir (double minimumSnir) virtual
Referenced by inet::physicallayer::ReceiverBase::computeReceptionResult(), inet::physicallayer::ApskLayeredReceiver::computeReceptionResult(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
Member Data Documentation
averageSnir
double inet::SnirInd::averageSnir = NaN protected
maximumSnir
double inet::SnirInd::maximumSnir = NaN protected
minimumSnir
double inet::SnirInd::minimumSnir = NaN protected
The documentation for this class was generated from the following file:
SignalTag_m.h