INET Framework for OMNeT++/OMNEST: inet::EigrpRouteSource< IPAddress > Class Template Reference
inet::EigrpRouteSource< IPAddress > Class Template Reference
Class represents EIGRP route to a destination network.
#include <EigrpRoute.h>
Public Member Functions
EigrpRouteSource (int interfaceId, const char *ifaceName, int nextHopId, int routeId, EigrpRoute< IPAddress > *routeInfo)
virtual ~EigrpRouteSource ()
bool operator== (const EigrpRouteSource< IPAddress > &source) const
uint64_t getRd () const
void setRd (uint64_t rd)
bool isInternal () const
void setInternal (bool internal)
uint64_t getMetric () const
void setMetric (uint64_t metric)
IPAddress getNextHop () const
void setNextHop (IPAddress &nextHop)
EigrpWideMetricPar getMetricParams () const
void setMetricParams (EigrpWideMetricPar &par)
EigrpWideMetricPar getRdParams () const
void setRdParams (const EigrpWideMetricPar &rdParams)
bool isSuccessor () const
void setSuccessor (bool successor)
int getNexthopId () const
void setNexthopId (int nextHopId)
int getIfaceId () const
void setIfaceId (int interfaceId)
EigrpRoute< IPAddress > * getRouteInfo () const
void setRouteInfo (EigrpRoute< IPAddress > *routeInfo)
int getRouteId () const
void setRouteId (int routeId)
int getSourceId () const
void setSourceId (int sourceId)
Ipv4Address getOriginator () const
void setOriginator (const Ipv4Address &originator)
bool isValid () const
void setValid (bool valid)
bool isUnreachable () const
void setUnreachableMetric ()
Sets metric and RD to infinity.
int getDelayedRemove () const
void setDelayedRemove (int neighID)
const char * getIfaceName () const
bool isRedistributed () const
void setRedistributed (bool redistributed)
bool isSummary () const
void setSummary (bool summary)
Protected Attributes
int sourceId
int routeId
Unique ID of source.
Ipv4Address originator
Unique ID of route (same as in EigrpRoute)
int nextHopId
Id of next hop neighbor (usually same as sourceId, 0 -> connected)
IPAddress nextHop
IP address of next hop router (0.0.0.0 -> connected), only informational.
int interfaceId
const char * interfaceName
ID of outgoing interface for next hop.
bool internal
Source of the route (internal or external)
uint64_t rd
Reported distance from neighbor (RDkj)
uint64_t metric
Actual metric value via that next Hop (not Dij - shortest distance)
EigrpWideMetricPar metricParams
Parameters for metric computation.
EigrpWideMetricPar rdParams
Parameters from neighbor.
bool successor
Source is successor for route.
bool summary
Summarized route.
bool redistributed
Redistributed route.
bool valid
Invalid sources will be deleted.
int delayedRemoveNID
Source will be deleted after receiving Ack from neighbor with ID equal to NID.
EigrpRoute< IPAddress > * routeInfo
Pointer to route.
Detailed Description
template<typename IPAddress>
class inet::EigrpRouteSource< IPAddress >
Class represents EIGRP route to a destination network.
Constructor & Destructor Documentation
EigrpRouteSource()
template<typename IPAddress > inet::EigrpRouteSource< IPAddress >::EigrpRouteSource (int interfaceId, const char * ifaceName, int nextHopId, int routeId, EigrpRoute< IPAddress > * routeInfo)
                                                                                                                                                   :
     routeId(routeId), nextHopId(nextHopId), interfaceId(interfaceId), interfaceName(ifaceName), routeInfo(routeInfo)
 {
     metric = eigrp::EigrpMetricHelper::METRIC_INF;
     rd = 0;
     internal = true;
     successor = false;
     sourceId = 0;
     valid = true;
     delayedRemoveNID = 0;
     summary = false;
     redistributed = false;
     routeInfo->incrementRefCnt();
 }
~EigrpRouteSource()
template<typename IPAddress > inet::EigrpRouteSource< IPAddress >::~EigrpRouteSource virtual
 {
 }
Member Function Documentation
getDelayedRemove()
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::getDelayedRemove () const inline
 { return delayedRemoveNID; }
Referenced by inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getIfaceId()
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::getIfaceId () const inline
 { return interfaceId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applySplitHorizon(), inet::eigrp::EigrpIpv6Pdm::applySplitHorizon(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::operator<<(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), and inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange().
getIfaceName()
template<typename IPAddress > const char* inet::EigrpRouteSource< IPAddress >::getIfaceName () const inline
 { return interfaceName; }
Referenced by inet::operator<<().
getMetric()
template<typename IPAddress > uint64_t inet::EigrpRouteSource< IPAddress >::getMetric () const inline
 { return metric; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getBestSuccessor(), inet::eigrp::EigrpIpv4Pdm::installRouteToRT(), inet::eigrp::EigrpIpv6Pdm::installRouteToRT(), inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition10(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition9(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getMetricParams()
template<typename IPAddress > EigrpWideMetricPar inet::EigrpRouteSource< IPAddress >::getMetricParams () const inline
 { return metricParams; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processInterRoute(), inet::eigrp::EigrpIpv6Pdm::processInterRoute(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition3(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4().
getNextHop()
template<typename IPAddress > IPAddress inet::EigrpRouteSource< IPAddress >::getNextHop () const inline
 { return nextHop; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getBestSuccessor(), inet::eigrp::EigrpIpv4Pdm::installRouteToRT(), inet::eigrp::EigrpIpv6Pdm::installRouteToRT(), inet::eigrp::EigrpDual< inet::Ipv4Address >::invalidateRoute(), inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::removeRouteFromRT(), inet::eigrp::EigrpIpv6Pdm::removeRouteFromRT(), inet::eigrp::EigrpIpv4Pdm::setDelayedRemove(), inet::eigrp::EigrpIpv6Pdm::setDelayedRemove(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getNexthopId()
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::getNexthopId () const inline
 { return nextHopId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applyStubToUpdate(), inet::eigrp::EigrpIpv6Pdm::applyStubToUpdate(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition13(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition14(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition15(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition16(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition2().
getOriginator()
template<typename IPAddress > Ipv4Address inet::EigrpRouteSource< IPAddress >::getOriginator () const inline
 { return originator; }
Referenced by inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::sendReply(), and inet::eigrp::EigrpIpv6Pdm::sendReply().
getRd()
template<typename IPAddress > uint64_t inet::EigrpRouteSource< IPAddress >::getRd () const inline
 { return rd; }
Referenced by inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getRdParams()
template<typename IPAddress > EigrpWideMetricPar inet::EigrpRouteSource< IPAddress >::getRdParams () const inline
 { return rdParams; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
getRouteId()
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::getRouteId () const inline
 { return routeId; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::addRoute(), inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getRouteInfo()
template<typename IPAddress > EigrpRoute<IPAddress>* inet::EigrpRouteSource< IPAddress >::getRouteInfo () const inline
 { return routeInfo; }
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv6Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpIpv4Pdm::processQueryPacket(), inet::eigrp::EigrpIpv6Pdm::processQueryPacket(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::removeRouteFromRT(), and inet::eigrp::EigrpIpv6Pdm::removeRouteFromRT().
getSourceId()
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::getSourceId () const inline
 { return sourceId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::sendReply(), and inet::eigrp::EigrpIpv6Pdm::sendReply().
isInternal()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::isInternal () const inline
 { return internal; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createRTRoute(), and inet::eigrp::EigrpIpv6Pdm::createRTRoute().
isRedistributed()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::isRedistributed () const inline
 { return redistributed; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applyStubToUpdate(), and inet::eigrp::EigrpIpv6Pdm::applyStubToUpdate().
isSuccessor()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::isSuccessor () const inline
 { return successor; }
Referenced by inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo0(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo1Active(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo1Passive(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo2(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo3(), inet::eigrp::EigrpIpv4Pdm::processRTRouteDel(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition6(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
isSummary()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::isSummary () const inline
 { return summary; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applyStubToUpdate(), and inet::eigrp::EigrpIpv6Pdm::applyStubToUpdate().
isUnreachable()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::isUnreachable () const inline
 { return metric == eigrp::EigrpMetricHelper::METRIC_INF; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition1(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition13(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition14(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition15(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition16(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition18(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition2(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition8(), inet::eigrp::EigrpIpv4Pdm::sendUpdateToStubs(), inet::eigrp::EigrpIpv6Pdm::sendUpdateToStubs(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
isValid()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::isValid () const inline
 { return valid; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::invalidateRoute(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
operator==()
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::operator== (const EigrpRouteSource< IPAddress > & source) const inline
     {
         return sourceId == source.getSourceId();
     }
setDelayedRemove()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setDelayedRemove (int neighID) inline
 { this->delayedRemoveNID = neighID; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition1(), inet::eigrp::EigrpIpv4Pdm::setDelayedRemove(), and inet::eigrp::EigrpIpv6Pdm::setDelayedRemove().
setIfaceId()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setIfaceId (int interfaceId) inline
 { this->interfaceId = interfaceId; }
setInternal()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setInternal (bool internal) inline
 { this->internal = internal; }
setMetric()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setMetric (uint64_t metric) inline
 { this->metric = metric; }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
setMetricParams()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setMetricParams (EigrpWideMetricPar & par) inline
 { this->metricParams = par; }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
setNextHop()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setNextHop (IPAddress & nextHop) inline
 { this->nextHop = nextHop; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
setNexthopId()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setNexthopId (int nextHopId) inline
 { this->nextHopId = nextHopId; }
setOriginator()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setOriginator (const Ipv4Address & originator) inline
 { this->originator = originator; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::findOrCreateRoute().
setRd()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setRd (uint64_t rd) inline
 { this->rd = rd; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
setRdParams()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setRdParams (const EigrpWideMetricPar & rdParams) inline
 { this->rdParams = rdParams; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
setRedistributed()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setRedistributed (bool redistributed) inline
 { this->redistributed = redistributed; }
setRouteId()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setRouteId (int routeId) inline
 { this->routeId = routeId; }
setRouteInfo()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setRouteInfo (EigrpRoute< IPAddress > * routeInfo) inline
 { this->routeInfo = routeInfo; }
setSourceId()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setSourceId (int sourceId) inline
 { this->sourceId = sourceId; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::addRoute().
setSuccessor()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setSuccessor (bool successor) inline
 { this->successor = successor; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeOldSuccessor(), inet::eigrp::EigrpIpv6Pdm::removeOldSuccessor(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
setSummary()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setSummary (bool summary) inline
 { this->summary = summary; }
setUnreachableMetric()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setUnreachableMetric () inline
Sets metric and RD to infinity.
     {
         metric = eigrp::EigrpMetricHelper::METRIC_INF;
         metricParams.bandwidth = eigrp::EigrpMetricHelper::BANDWIDTH_INF;
         metricParams.delay = eigrp::EigrpMetricHelper::DELAY_INF;
         rd = eigrp::EigrpMetricHelper::METRIC_INF;
         rdParams.bandwidth = eigrp::EigrpMetricHelper::BANDWIDTH_INF;
         rdParams.delay = eigrp::EigrpMetricHelper::DELAY_INF;
     }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent().
setValid()
template<typename IPAddress > void inet::EigrpRouteSource< IPAddress >::setValid (bool valid) inline
 { this->valid = valid; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::invalidateRoute(), inet::eigrp::EigrpIpv4Pdm::setDelayedRemove(), inet::eigrp::EigrpIpv6Pdm::setDelayedRemove(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
Member Data Documentation
delayedRemoveNID
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::delayedRemoveNID protected
Source will be deleted after receiving Ack from neighbor with ID equal to NID.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getDelayedRemove().
interfaceId
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::interfaceId protected
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getIfaceId(), and inet::EigrpRouteSource< inet::Ipv4Address >::setIfaceId().
interfaceName
template<typename IPAddress > const char* inet::EigrpRouteSource< IPAddress >::interfaceName protected
ID of outgoing interface for next hop.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getIfaceName().
internal
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::internal protected
Source of the route (internal or external)
metric
template<typename IPAddress > uint64_t inet::EigrpRouteSource< IPAddress >::metric protected
Actual metric value via that next Hop (not Dij - shortest distance)
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getMetric(), inet::EigrpRouteSource< inet::Ipv4Address >::isUnreachable(), inet::EigrpRouteSource< inet::Ipv4Address >::setMetric(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
metricParams
template<typename IPAddress > EigrpWideMetricPar inet::EigrpRouteSource< IPAddress >::metricParams protected
Parameters for metric computation.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getMetricParams(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
nextHop
template<typename IPAddress > IPAddress inet::EigrpRouteSource< IPAddress >::nextHop protected
IP address of next hop router (0.0.0.0 -> connected), only informational.
It does not correspond to the sourceId (next hop may not be source of the route).
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getNextHop(), and inet::EigrpRouteSource< inet::Ipv4Address >::setNextHop().
nextHopId
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::nextHopId protected
Id of next hop neighbor (usually same as sourceId, 0 -> connected)
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getNexthopId(), and inet::EigrpRouteSource< inet::Ipv4Address >::setNexthopId().
originator
template<typename IPAddress > Ipv4Address inet::EigrpRouteSource< IPAddress >::originator protected
Unique ID of route (same as in EigrpRoute)
IP of originating router
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getOriginator(), and inet::EigrpRouteSource< inet::Ipv4Address >::setOriginator().
rd
template<typename IPAddress > uint64_t inet::EigrpRouteSource< IPAddress >::rd protected
Reported distance from neighbor (RDkj)
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getRd(), inet::EigrpRouteSource< inet::Ipv4Address >::setRd(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
rdParams
template<typename IPAddress > EigrpWideMetricPar inet::EigrpRouteSource< IPAddress >::rdParams protected
Parameters from neighbor.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getRdParams(), inet::EigrpRouteSource< inet::Ipv4Address >::setRdParams(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
redistributed
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::redistributed protected
Redistributed route.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::isRedistributed(), and inet::EigrpRouteSource< inet::Ipv4Address >::setRedistributed().
routeId
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::routeId protected
Unique ID of source.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getRouteId(), and inet::EigrpRouteSource< inet::Ipv4Address >::setRouteId().
routeInfo
template<typename IPAddress > EigrpRoute<IPAddress>* inet::EigrpRouteSource< IPAddress >::routeInfo protected
Pointer to route.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getRouteInfo(), and inet::EigrpRouteSource< inet::Ipv4Address >::setRouteInfo().
sourceId
template<typename IPAddress > int inet::EigrpRouteSource< IPAddress >::sourceId protected
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::getSourceId(), inet::EigrpRouteSource< inet::Ipv4Address >::operator==(), and inet::EigrpRouteSource< inet::Ipv4Address >::setSourceId().
successor
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::successor protected
Source is successor for route.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::isSuccessor(), and inet::EigrpRouteSource< inet::Ipv4Address >::setSuccessor().
summary
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::summary protected
Summarized route.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::isSummary(), and inet::EigrpRouteSource< inet::Ipv4Address >::setSummary().
valid
template<typename IPAddress > bool inet::EigrpRouteSource< IPAddress >::valid protected
Invalid sources will be deleted.
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::isValid(), and inet::EigrpRouteSource< inet::Ipv4Address >::setValid().
The documentation for this class was generated from the following file:
EigrpRoute.h