INET Framework for OMNeT++/OMNEST: inet::physicallayer::ConfigureRadioCommand Class Reference
inet::physicallayer::ConfigureRadioCommand Class Reference
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/RadioControlInfo.msg:25 by opp_msgtool.
#include <RadioControlInfo_m.h>
Public Member Functions
ConfigureRadioCommand ()
ConfigureRadioCommand (const ConfigureRadioCommand &other)
virtual ~ConfigureRadioCommand ()
ConfigureRadioCommand & operator= (const ConfigureRadioCommand &other)
virtual ConfigureRadioCommand * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getRadioMode () const
virtual void setRadioMode (int radioMode)
virtual ::inet::W getPower () const
virtual void setPower (::inet::W power)
virtual ::inet::bps getBitrate () const
virtual void setBitrate (::inet::bps bitrate)
virtual const IModulation * getModulation () const
virtual IModulation * getModulationForUpdate ()
virtual void setModulation (IModulation *modulation)
virtual ::inet::Hz getCenterFrequency () const
virtual void setCenterFrequency (::inet::Hz centerFrequency)
virtual ::inet::Hz getBandwidth () const
virtual void setBandwidth (::inet::Hz bandwidth)
Protected Member Functions
bool operator== (const ConfigureRadioCommand &)=delete
Protected Attributes
int radioMode = -1
::inet::W power = W(NaN)
::inet::bps bitrate = bps(NaN)
IModulation * modulation = nullptr
::inet::Hz centerFrequency = Hz(NaN)
::inet::Hz bandwidth = Hz(NaN)
Private Member Functions
void copy (const ConfigureRadioCommand &other)
Detailed Description
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/RadioControlInfo.msg:25 by opp_msgtool.
//
// Control info attached to a configure command that is sent to the ~Radio.
//
class ConfigureRadioCommand extends cObject
{
    int radioMode = -1;                  // new radio mode or -1 if not set.
    W power = W(NaN);                    // new default transmission power in the range (0, +infinity) or NaN if not set.
    bps bitrate = bps(NaN);              // new default bitrate in the range (0, +infinity) or NaN if not set.
    IModulation *modulation;             // new default modulation or nullptr if not set.
    Hz centerFrequency = Hz(NaN);       // new default carrier frequency in the range (0, +infinity) or NaN if not set.
    Hz bandwidth = Hz(NaN);              // new default bandwidth in the rage (0, +infinity) or NaN if not set.
}
Constructor & Destructor Documentation
ConfigureRadioCommand() [1/2]
inet::physicallayer::ConfigureRadioCommand::ConfigureRadioCommand ()
ConfigureRadioCommand() [2/2]
inet::physicallayer::ConfigureRadioCommand::ConfigureRadioCommand (const ConfigureRadioCommand & other)
~ConfigureRadioCommand()
virtual inet::physicallayer::ConfigureRadioCommand::~ConfigureRadioCommand () virtual
Member Function Documentation
copy()
void inet::physicallayer::ConfigureRadioCommand::copy (const ConfigureRadioCommand & other) private
dup()
virtual ConfigureRadioCommand* inet::physicallayer::ConfigureRadioCommand::dup () const inline override virtual
Reimplemented in inet::physicallayer::Ieee80211ConfigureRadioCommand.
 {return new ConfigureRadioCommand(*this);}
getBandwidth()
virtual ::inet::Hz inet::physicallayer::ConfigureRadioCommand::getBandwidth () const
Referenced by inet::physicallayer::NarrowbandRadioBase::handleUpperCommand().
getBitrate()
virtual ::inet::bps inet::physicallayer::ConfigureRadioCommand::getBitrate () const
Referenced by inet::physicallayer::FlatRadioBase::handleUpperCommand(), and inet::ieee80211::Ieee80211Mac::handleUpperCommand().
getCenterFrequency()
virtual ::inet::Hz inet::physicallayer::ConfigureRadioCommand::getCenterFrequency () const
Referenced by inet::physicallayer::NarrowbandRadioBase::handleUpperCommand().
getModulation()
virtual const IModulation* inet::physicallayer::ConfigureRadioCommand::getModulation () const virtual
Referenced by inet::physicallayer::NarrowbandRadioBase::handleUpperCommand().
getModulationForUpdate()
virtual IModulation* inet::physicallayer::ConfigureRadioCommand::getModulationForUpdate () inline virtual
 { return const_cast<IModulation *>(const_cast<ConfigureRadioCommand*>(this)->getModulation());}
getPower()
virtual ::inet::W inet::physicallayer::ConfigureRadioCommand::getPower () const
Referenced by inet::physicallayer::FlatRadioBase::handleUpperCommand().
getRadioMode()
virtual int inet::physicallayer::ConfigureRadioCommand::getRadioMode () const virtual
Referenced by inet::physicallayer::Radio::handleUpperCommand().
operator=()
ConfigureRadioCommand& inet::physicallayer::ConfigureRadioCommand::operator= (const ConfigureRadioCommand & other)
operator==()
bool inet::physicallayer::ConfigureRadioCommand::operator== (const ConfigureRadioCommand &) protected delete
parsimPack()
virtual void inet::physicallayer::ConfigureRadioCommand::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::physicallayer::Ieee80211ConfigureRadioCommand.
Referenced by inet::physicallayer::doParsimPacking().
parsimUnpack()
virtual void inet::physicallayer::ConfigureRadioCommand::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::physicallayer::Ieee80211ConfigureRadioCommand.
Referenced by inet::physicallayer::doParsimUnpacking().
setBandwidth()
virtual void inet::physicallayer::ConfigureRadioCommand::setBandwidth (::inet::Hz bandwidth) virtual
setBitrate()
virtual void inet::physicallayer::ConfigureRadioCommand::setBitrate (::inet::bps bitrate) virtual
Referenced by inet::ieee80211::Ieee80211Mac::handleUpperCommand().
setCenterFrequency()
virtual void inet::physicallayer::ConfigureRadioCommand::setCenterFrequency (::inet::Hz centerFrequency) virtual
setModulation()
virtual void inet::physicallayer::ConfigureRadioCommand::setModulation (IModulation * modulation) virtual
setPower()
virtual void inet::physicallayer::ConfigureRadioCommand::setPower (::inet::W power) virtual
setRadioMode()
virtual void inet::physicallayer::ConfigureRadioCommand::setRadioMode (int radioMode) virtual
Referenced by inet::ieee80211::Ieee80211Mac::configureRadioMode().
Member Data Documentation
bandwidth
::inet::Hz inet::physicallayer::ConfigureRadioCommand::bandwidth = Hz(NaN) protected
bitrate
::inet::bps inet::physicallayer::ConfigureRadioCommand::bitrate = bps(NaN) protected
centerFrequency
::inet::Hz inet::physicallayer::ConfigureRadioCommand::centerFrequency = Hz(NaN) protected
modulation
IModulation* inet::physicallayer::ConfigureRadioCommand::modulation = nullptr protected
power
::inet::W inet::physicallayer::ConfigureRadioCommand::power = W(NaN) protected
radioMode
int inet::physicallayer::ConfigureRadioCommand::radioMode = -1 protected
The documentation for this class was generated from the following file:
RadioControlInfo_m.h