INET Framework for OMNeT++/OMNEST: inet::ProtocolListTagBase Class Reference
inet::ProtocolListTagBase Class Reference
Class generated from inet/common/ProtocolTag.msg:45 by opp_msgtool.
#include <ProtocolTag_m.h>
Public Member Functions
ProtocolListTagBase ()
ProtocolListTagBase (const ProtocolListTagBase &other)
virtual ~ProtocolListTagBase ()
ProtocolListTagBase & operator= (const ProtocolListTagBase &other)
virtual ProtocolListTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setProtocolArraySize (size_t size)
virtual size_t getProtocolArraySize () const
virtual const Protocol * getProtocol (size_t k) const
virtual void setProtocol (size_t k, const Protocol *protocol)
virtual void insertProtocol (size_t k, const Protocol *protocol)
void insertProtocol (const Protocol *protocol)
virtual void appendProtocol (const Protocol *protocol)
virtual void eraseProtocol (size_t k)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const ProtocolListTagBase &)=delete
Protected Attributes
const Protocol ** protocol = nullptr
size_t protocol_arraysize = 0
Private Member Functions
void copy (const ProtocolListTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/common/ProtocolTag.msg:45 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class ProtocolListTagBase extends TagBase
{
    const Protocol *protocol[]; // specifies a list of protocols (internal class with an artificial identifier)
}
Constructor & Destructor Documentation
ProtocolListTagBase() [1/2]
inet::ProtocolListTagBase::ProtocolListTagBase ()
ProtocolListTagBase() [2/2]
inet::ProtocolListTagBase::ProtocolListTagBase (const ProtocolListTagBase & other)
~ProtocolListTagBase()
virtual inet::ProtocolListTagBase::~ProtocolListTagBase () virtual
Member Function Documentation
appendProtocol()
virtual void inet::ProtocolListTagBase::appendProtocol (const Protocol * protocol) virtual
Referenced by inet::RelayInterfaceSelector::sendPacket().
copy()
void inet::ProtocolListTagBase::copy (const ProtocolListTagBase & other) private
dup()
virtual ProtocolListTagBase* inet::ProtocolListTagBase::dup () const inline override virtual
Reimplemented in inet::EncapsulationProtocolInd, and inet::EncapsulationProtocolReq.
 {return new ProtocolListTagBase(*this);}
eraseProtocol()
virtual void inet::ProtocolListTagBase::eraseProtocol (size_t k) virtual
getProtocol()
virtual const Protocol* inet::ProtocolListTagBase::getProtocol (size_t k) const virtual
getProtocolArraySize()
virtual size_t inet::ProtocolListTagBase::getProtocolArraySize () const virtual
insertProtocol() [1/2]
void inet::ProtocolListTagBase::insertProtocol (const Protocol * protocol) inline
 {appendProtocol(protocol);}
insertProtocol() [2/2]
virtual void inet::ProtocolListTagBase::insertProtocol (size_t k, const Protocol * protocol) virtual
Referenced by inet::queueing::PacketTaggerBase::markPacket(), and inet::StreamEncoder::processPacket().
operator=()
ProtocolListTagBase& inet::ProtocolListTagBase::operator= (const ProtocolListTagBase & other)
operator==()
bool inet::ProtocolListTagBase::operator== (const ProtocolListTagBase &) protected delete
parsimPack()
virtual void inet::ProtocolListTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::EncapsulationProtocolInd, and inet::EncapsulationProtocolReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::ProtocolListTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::EncapsulationProtocolInd, and inet::EncapsulationProtocolReq.
Referenced by inet::doParsimUnpacking().
setProtocol()
virtual void inet::ProtocolListTagBase::setProtocol (size_t k, const Protocol * protocol) virtual
setProtocolArraySize()
virtual void inet::ProtocolListTagBase::setProtocolArraySize (size_t size) virtual
Member Data Documentation
protocol
const Protocol* * inet::ProtocolListTagBase::protocol = nullptr protected
protocol_arraysize
size_t inet::ProtocolListTagBase::protocol_arraysize = 0 protected
The documentation for this class was generated from the following file:
ProtocolTag_m.h