INET Framework for OMNeT++/OMNEST: inet::ieee80211::RateSelection Class Reference
inet::ieee80211::RateSelection Class Reference
#include <RateSelection.h>
Public Member Functions
virtual const physicallayer::IIeee80211Mode * computeResponseCtsFrameMode (Packet *packet, const Ptr< const Ieee80211RtsFrame > &rtsFrame) override
virtual const physicallayer::IIeee80211Mode * computeResponseAckFrameMode (Packet *packet, const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader) override
virtual const physicallayer::IIeee80211Mode * computeMode (Packet *packet, const Ptr< const Ieee80211MacHeader > &header) override
virtual void frameTransmitted (Packet *packet, const Ptr< const Ieee80211MacHeader > &header)
Public Member Functions inherited from inet::ieee80211::IRateSelection
virtual ~IRateSelection ()
Static Public Member Functions
static void setFrameMode (Packet *packet, const Ptr< const Ieee80211MacHeader > &header, const physicallayer::IIeee80211Mode *mode)
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual const physicallayer::IIeee80211Mode * getMode (Packet *packet, const Ptr< const Ieee80211MacHeader > &header)
virtual const physicallayer::IIeee80211Mode * computeControlFrameMode (const Ptr< const Ieee80211MacHeader > &header)
virtual const physicallayer::IIeee80211Mode * computeDataOrMgmtFrameMode (const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader)
Protected Attributes
IRateControl * dataOrMgmtRateControl = nullptr
const physicallayer::IIeee80211Mode * fastestMandatoryMode = nullptr
const physicallayer::Ieee80211ModeSet * modeSet = nullptr
std::map< MacAddress, const physicallayer::IIeee80211Mode * > lastTransmittedFrameMode
const physicallayer::IIeee80211Mode * multicastFrameMode = nullptr
const physicallayer::IIeee80211Mode * dataFrameMode = nullptr
const physicallayer::IIeee80211Mode * mgmtFrameMode = nullptr
const physicallayer::IIeee80211Mode * controlFrameMode = nullptr
const physicallayer::IIeee80211Mode * responseAckFrameMode = nullptr
const physicallayer::IIeee80211Mode * responseCtsFrameMode = nullptr
Additional Inherited Members
Static Public Attributes inherited from inet::ieee80211::IRateSelection
static simsignal_t datarateSelectedSignal = cComponent::registerSignal("datarateSelected")
Member Function Documentation
computeControlFrameMode()
const IIeee80211Mode * inet::ieee80211::RateSelection::computeControlFrameMode (const Ptr< const Ieee80211MacHeader > & header) protected virtual
 {
     // TODO BSSBasicRateSet
     return fastestMandatoryMode;
 }
computeDataOrMgmtFrameMode()
const IIeee80211Mode * inet::ieee80211::RateSelection::computeDataOrMgmtFrameMode (const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) protected virtual
 {
     if (dataOrMgmtHeader->getReceiverAddress().isMulticast() && multicastFrameMode)
         return multicastFrameMode;
     if (dynamicPtrCast<const Ieee80211DataHeader>(dataOrMgmtHeader) && dataFrameMode)
         return dataFrameMode;
     if (dynamicPtrCast<const Ieee80211MgmtHeader>(dataOrMgmtHeader) && mgmtFrameMode)
         return mgmtFrameMode;
     if (dataOrMgmtRateControl)
         return dataOrMgmtRateControl->getRate();
     else
         return fastestMandatoryMode;
 }
computeMode()
const IIeee80211Mode * inet::ieee80211::RateSelection::computeMode (Packet * packet, const Ptr< const Ieee80211MacHeader > & header) override virtual
Implements inet::ieee80211::IRateSelection.
 {
     if (auto dataOrMgmtHeader = dynamicPtrCast<const Ieee80211DataOrMgmtHeader>(header))
         return computeDataOrMgmtFrameMode(dataOrMgmtHeader);
     else
         return computeControlFrameMode(header);
 }
computeResponseAckFrameMode()
const IIeee80211Mode * inet::ieee80211::RateSelection::computeResponseAckFrameMode (Packet * packet, const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) override virtual
Implements inet::ieee80211::IRateSelection.
 {
     if (responseAckFrameMode)
         return responseAckFrameMode;
     else {
         auto mode = getMode(packet, dataOrMgmtHeader);
         ASSERT(modeSet->containsMode(mode));
         return modeSet->getIsMandatory(mode) ? mode : modeSet->getSlowerMandatoryMode(mode); // TODO BSSBasicRateSet
     }
 }
computeResponseCtsFrameMode()
const IIeee80211Mode * inet::ieee80211::RateSelection::computeResponseCtsFrameMode (Packet * packet, const Ptr< const Ieee80211RtsFrame > & rtsFrame) override virtual
Implements inet::ieee80211::IRateSelection.
 {
     if (responseCtsFrameMode)
         return responseCtsFrameMode;
     else {
         auto mode = getMode(packet, rtsFrame);
         ASSERT(modeSet->containsMode(mode));
         return modeSet->getIsMandatory(mode) ? mode : modeSet->getSlowerMandatoryMode(mode); // TODO BSSBasicRateSet
     }
 }
frameTransmitted()
void inet::ieee80211::RateSelection::frameTransmitted (Packet * packet, const Ptr< const Ieee80211MacHeader > & header) virtual
 {
     auto receiverAddr = header->getReceiverAddress();
     lastTransmittedFrameMode[receiverAddr] = getMode(packet, header);
 }
getMode()
const IIeee80211Mode * inet::ieee80211::RateSelection::getMode (Packet * packet, const Ptr< const Ieee80211MacHeader > & header) protected virtual
 {
     const auto& modeReqTag = packet->findTag<Ieee80211ModeReq>();
     if (modeReqTag)
         return modeReqTag->getMode();
     const auto& modeIndTag = packet->findTag<Ieee80211ModeInd>();
     if (modeIndTag)
         return modeIndTag->getMode();
     throw cRuntimeError("Missing mode");
 }
initialize()
void inet::ieee80211::RateSelection::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         getContainingNicModule(this)->subscribe(modesetChangedSignal, this);
     }
     else if (stage == INITSTAGE_LINK_LAYER) {
         dataOrMgmtRateControl = dynamic_cast<IRateControl *>(findModuleByPath(par("rateControlModule")));
         double multicastFrameBitrate = par("multicastFrameBitrate");
         multicastFrameMode = (multicastFrameBitrate == -1) ? nullptr : modeSet->getMode(bps(multicastFrameBitrate));
         double dataFrameBitrate = par("dataFrameBitrate");
         dataFrameMode = (dataFrameBitrate == -1) ? nullptr : modeSet->getMode(bps(dataFrameBitrate), Hz(par("dataFrameBandwidth")), par("dataFrameNumSpatialStreams"));
         double mgmtFrameBitrate = par("mgmtFrameBitrate");
         mgmtFrameMode = (mgmtFrameBitrate == -1) ? nullptr : modeSet->getMode(bps(mgmtFrameBitrate));
         double controlFrameBitrate = par("controlFrameBitrate");
         controlFrameMode = (controlFrameBitrate == -1) ? nullptr : modeSet->getMode(bps(controlFrameBitrate));
         double responseAckFrameBitrate = par("responseAckFrameBitrate");
         responseAckFrameMode = (responseAckFrameBitrate == -1) ? nullptr : modeSet->getMode(bps(responseAckFrameBitrate));
         double responseCtsFrameBitrate = par("responseCtsFrameBitrate");
         responseCtsFrameMode = (responseCtsFrameBitrate == -1) ? nullptr : modeSet->getMode(bps(responseCtsFrameBitrate));
         fastestMandatoryMode = modeSet->getFastestMandatoryMode();
 //        WATCH_PTR(dataOrMgmtRateControl);
 //        WATCH_PTR(*((cObject**)&fastestMandatoryMode));
 //        WATCH_PTR(*((cObject**)&modeSet));
         WATCH_MAP(lastTransmittedFrameMode);
 //        WATCH_PTR(*((cObject**)&multicastFrameMode));
 //        WATCH_PTR(*((cObject**)&dataFrameMode));
 //        WATCH_PTR(*((cObject**)&mgmtFrameMode));
 //        WATCH_PTR(*((cObject**)&controlFrameMode));
 //        WATCH_PTR(*((cObject**)&responseAckFrameMode));
 //        WATCH_PTR(*((cObject**)&responseCtsFrameMode));
 //        WATCH_PTR();
 //        WATCH_PTR();
 //        WATCH_PTR();
 //        WATCH_PTR();
     }
 }
numInitStages()
virtual int inet::ieee80211::RateSelection::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
receiveSignal()
void inet::ieee80211::RateSelection::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     if (signalID == modesetChangedSignal) {
         modeSet = check_and_cast<Ieee80211ModeSet *>(obj);
         fastestMandatoryMode = modeSet->getFastestMandatoryMode();
     }
 }
setFrameMode()
void inet::ieee80211::RateSelection::setFrameMode (Packet * packet, const Ptr< const Ieee80211MacHeader > & header, const physicallayer::IIeee80211Mode * mode) static
 {
     ASSERT(mode != nullptr);
     packet->addTagIfAbsent<Ieee80211ModeReq>()->setMode(mode);
 }
Referenced by inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField(), inet::ieee80211::Dcf::transmitControlResponseFrame(), and inet::ieee80211::Dcf::transmitFrame().
Member Data Documentation
controlFrameMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::controlFrameMode = nullptr protected
dataFrameMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::dataFrameMode = nullptr protected
dataOrMgmtRateControl
IRateControl* inet::ieee80211::RateSelection::dataOrMgmtRateControl = nullptr protected
fastestMandatoryMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::fastestMandatoryMode = nullptr protected
lastTransmittedFrameMode
std::map<MacAddress, const physicallayer::IIeee80211Mode *> inet::ieee80211::RateSelection::lastTransmittedFrameMode protected
mgmtFrameMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::mgmtFrameMode = nullptr protected
modeSet
const physicallayer::Ieee80211ModeSet* inet::ieee80211::RateSelection::modeSet = nullptr protected
multicastFrameMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::multicastFrameMode = nullptr protected
responseAckFrameMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::responseAckFrameMode = nullptr protected
responseCtsFrameMode
const physicallayer::IIeee80211Mode* inet::ieee80211::RateSelection::responseCtsFrameMode = nullptr protected
The documentation for this class was generated from the following files:
RateSelection.h
RateSelection.cc