INET Framework for OMNeT++/OMNEST: inet::CanvasProjection Class Reference
inet::CanvasProjection Class Reference
#include <CanvasProjection.h>
Public Member Functions
CanvasProjection ()
CanvasProjection (RotationMatrix rotation, cFigure::Point translation)
virtual ~CanvasProjection ()
const RotationMatrix & getRotation () const
void setRotation (const RotationMatrix &rotation)
const cFigure::Point & getScale () const
void setScale (const cFigure::Point &scale)
const cFigure::Point & getTranslation () const
void setTranslation (const cFigure::Point &translation)
cFigure::Point computeCanvasPoint (const Coord &point) const
cFigure::Point computeCanvasPoint (const Coord &point, double &depth) const
Coord computeCanvasPointInverse (const cFigure::Point &point, double depth) const
Static Public Member Functions
static CanvasProjection * getCanvasProjection (const cCanvas *canvas)
static void dropCanvasProjections ()
Protected Attributes
RotationMatrix rotation
cFigure::Point scale
cFigure::Point translation
Static Protected Attributes
static std::map< const cCanvas *, CanvasProjection * > canvasProjections
Constructor & Destructor Documentation
CanvasProjection() [1/2]
inet::CanvasProjection::CanvasProjection () inline
 : scale(cFigure::Point(1, 1)) {}
Referenced by getCanvasProjection().
CanvasProjection() [2/2]
inet::CanvasProjection::CanvasProjection (RotationMatrix rotation, cFigure::Point translation)
                                                                                     :
     rotation(rotation),
     scale(cFigure::Point(1, 1)),
     translation(translation)
 {
 }
~CanvasProjection()
inet::CanvasProjection::~CanvasProjection () virtual
 {
 }
Member Function Documentation
computeCanvasPoint() [1/2]
cFigure::Point inet::CanvasProjection::computeCanvasPoint (const Coord & point) const
 {
     double depth;
     return computeCanvasPoint(point, depth);
 }
Referenced by inet::visualizer::LinkBreakCanvasVisualizer::createLinkBreakVisualization(), inet::visualizer::NetworkConnectionCanvasVisualizer::createNetworkConnectionVisualization(), inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization(), inet::visualizer::PacketDropCanvasVisualizer::createPacketDropVisualization(), inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe(), inet::visualizer::SceneCanvasVisualizer::refreshAxis(), inet::visualizer::NetworkNodeCanvasVisualizer::refreshDisplay(), inet::visualizer::LinkBreakCanvasVisualizer::refreshDisplay(), inet::visualizer::LinkCanvasVisualizerBase::refreshDisplay(), inet::visualizer::TreeCanvasVisualizerBase::refreshDisplay(), inet::visualizer::PathCanvasVisualizerBase::refreshDisplay(), inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay(), inet::visualizer::MobilityCanvasVisualizer::refreshDisplay(), inet::visualizer::PacketDropCanvasVisualizer::setAlpha(), inet::MobilityBase::updateDisplayStringFromMobilityState(), and inet::StationaryMobility::updateMobilityStateFromDisplayString().
computeCanvasPoint() [2/2]
cFigure::Point inet::CanvasProjection::computeCanvasPoint (const Coord & point, double & depth) const
 {
     Coord rotatedPoint = rotation.rotateVector(point);
     depth = rotatedPoint.z;
     return cFigure::Point(rotatedPoint.x * scale.x + translation.x, rotatedPoint.y * scale.y + translation.y);
 }
computeCanvasPointInverse()
Coord inet::CanvasProjection::computeCanvasPointInverse (const cFigure::Point & point, double depth) const
 {
     Coord p((point.x - translation.x) / scale.x, (point.y - translation.y) / scale.y, depth);
     return rotation.rotateVectorInverse(p);
 }
Referenced by inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe(), inet::MobilityBase::setInitialPosition(), inet::MobilityBase::updateDisplayStringFromMobilityState(), and inet::StationaryMobility::updateMobilityStateFromDisplayString().
dropCanvasProjections()
void inet::CanvasProjection::dropCanvasProjections () static
 {
     for (auto it : canvasProjections)
         delete it.second;
     canvasProjections.clear();
 }
getCanvasProjection()
CanvasProjection * inet::CanvasProjection::getCanvasProjection (const cCanvas * canvas) static
 {
     auto it = canvasProjections.find(canvas);
     if (it == canvasProjections.end())
         return canvasProjections[canvas] = new CanvasProjection();
     else
         return it->second;
 }
Referenced by inet::visualizer::NetworkConnectionCanvasVisualizer::initialize(), inet::visualizer::SceneCanvasVisualizer::initialize(), inet::visualizer::NetworkNodeCanvasVisualizer::initialize(), inet::visualizer::OpenStreetMapSceneCanvasVisualizer::initialize(), inet::visualizer::LinkBreakCanvasVisualizer::initialize(), inet::visualizer::PathCanvasVisualizerBase::initialize(), inet::visualizer::TreeCanvasVisualizerBase::initialize(), inet::visualizer::LinkCanvasVisualizerBase::initialize(), inet::visualizer::RoutingTableCanvasVisualizer::initialize(), inet::visualizer::MobilityCanvasVisualizer::initialize(), inet::visualizer::TransportConnectionCanvasVisualizer::initialize(), inet::visualizer::PacketDropCanvasVisualizer::initialize(), inet::visualizer::RadioCanvasVisualizer::initialize(), inet::visualizer::PhysicalEnvironmentCanvasVisualizer::initialize(), inet::visualizer::TracingObstacleLossCanvasVisualizer::initialize(), and inet::MobilityBase::initialize().
getRotation()
const RotationMatrix& inet::CanvasProjection::getRotation () const inline
 { return rotation; }
getScale()
const cFigure::Point& inet::CanvasProjection::getScale () const inline
 { return scale; }
getTranslation()
const cFigure::Point& inet::CanvasProjection::getTranslation () const inline
 { return translation; }
setRotation()
void inet::CanvasProjection::setRotation (const RotationMatrix & rotation) inline
 { this->rotation = rotation; }
Referenced by inet::visualizer::SceneCanvasVisualizer::handleParameterChange(), and inet::visualizer::SceneCanvasVisualizer::initialize().
setScale()
void inet::CanvasProjection::setScale (const cFigure::Point & scale) inline
 { this->scale = scale; }
Referenced by inet::visualizer::SceneCanvasVisualizer::handleParameterChange(), and inet::visualizer::SceneCanvasVisualizer::initialize().
setTranslation()
void inet::CanvasProjection::setTranslation (const cFigure::Point & translation) inline
 { this->translation = translation; }
Referenced by inet::visualizer::SceneCanvasVisualizer::handleParameterChange(), and inet::visualizer::SceneCanvasVisualizer::initialize().
Member Data Documentation
canvasProjections
std::map< const cCanvas *, CanvasProjection * > inet::CanvasProjection::canvasProjections static protected
Referenced by dropCanvasProjections(), and getCanvasProjection().
rotation
RotationMatrix inet::CanvasProjection::rotation protected
Referenced by computeCanvasPoint(), and computeCanvasPointInverse().
scale
cFigure::Point inet::CanvasProjection::scale protected
Referenced by computeCanvasPoint(), and computeCanvasPointInverse().
translation
cFigure::Point inet::CanvasProjection::translation protected
Referenced by computeCanvasPoint(), and computeCanvasPointInverse().
The documentation for this class was generated from the following files:
CanvasProjection.h
CanvasProjection.cc