INET Framework for OMNeT++/OMNEST: inet::ieee80211::RecipientBlockAckAgreement Class Reference
inet::ieee80211::RecipientBlockAckAgreement Class Reference
#include <RecipientBlockAckAgreement.h>
Public Member Functions
RecipientBlockAckAgreement (MacAddress originatorAddress, Tid tid, SequenceNumberCyclic startingSequenceNumber, int bufferSize, simtime_t blockAckTimeoutValue)
virtual ~RecipientBlockAckAgreement ()
virtual void blockAckPolicyFrameReceived (const Ptr< const Ieee80211DataHeader > &header)
virtual BlockAckRecord * getBlockAckRecord () const
virtual simtime_t getBlockAckTimeoutValue () const
virtual int getBufferSize () const
virtual SequenceNumberCyclic getStartingSequenceNumber () const
virtual void addbaResposneSent ()
virtual void calculateExpirationTime ()
virtual simtime_t getExpirationTime ()
Protected Attributes
BlockAckRecord * blockAckRecord = nullptr
SequenceNumberCyclic startingSequenceNumber
int bufferSize = -1
simtime_t blockAckTimeoutValue = 0
bool isAddbaResponseSent = false
simtime_t expirationTime = -1
Friends
std::ostream & operator<< (std::ostream &os, const RecipientBlockAckAgreement &agreement)
Constructor & Destructor Documentation
RecipientBlockAckAgreement()
inet::ieee80211::RecipientBlockAckAgreement::RecipientBlockAckAgreement (MacAddress originatorAddress, Tid tid, SequenceNumberCyclic startingSequenceNumber, int bufferSize, simtime_t blockAckTimeoutValue)
                                                                                                                                                                                  :
     startingSequenceNumber(startingSequenceNumber),
     bufferSize(bufferSize),
     blockAckTimeoutValue(lastUsedTime)
 {
     calculateExpirationTime();
     blockAckRecord = new BlockAckRecord(originatorAddress, tid);
 }
~RecipientBlockAckAgreement()
virtual inet::ieee80211::RecipientBlockAckAgreement::~RecipientBlockAckAgreement () inline virtual
 { delete blockAckRecord; }
Member Function Documentation
addbaResposneSent()
virtual void inet::ieee80211::RecipientBlockAckAgreement::addbaResposneSent () inline virtual
 { isAddbaResponseSent = true; }
Referenced by inet::ieee80211::RecipientBlockAckAgreementHandler::updateAgreement().
blockAckPolicyFrameReceived()
void inet::ieee80211::RecipientBlockAckAgreement::blockAckPolicyFrameReceived (const Ptr< const Ieee80211DataHeader > & header) virtual
 {
     ASSERT(header->getAckPolicy() == BLOCK_ACK);
     blockAckRecord->blockAckPolicyFrameReceived(header);
 }
Referenced by inet::ieee80211::BlockAckReordering::processReceivedQoSFrame().
calculateExpirationTime()
virtual void inet::ieee80211::RecipientBlockAckAgreement::calculateExpirationTime () inline virtual
 { expirationTime = blockAckTimeoutValue == 0 ? SIMTIME_MAX : simTime() + blockAckTimeoutValue; }
Referenced by RecipientBlockAckAgreement().
getBlockAckRecord()
virtual BlockAckRecord* inet::ieee80211::RecipientBlockAckAgreement::getBlockAckRecord () const inline virtual
 { return blockAckRecord; }
Referenced by inet::ieee80211::RecipientBlockAckProcedure::buildBlockAck(), inet::ieee80211::BlockAckReordering::createReceiveBufferIfNecessary(), and inet::ieee80211::BlockAckReordering::passedUp().
getBlockAckTimeoutValue()
virtual simtime_t inet::ieee80211::RecipientBlockAckAgreement::getBlockAckTimeoutValue () const inline virtual
 { return blockAckTimeoutValue; }
getBufferSize()
virtual int inet::ieee80211::RecipientBlockAckAgreement::getBufferSize () const inline virtual
 { return bufferSize; }
Referenced by inet::ieee80211::BlockAckReordering::createReceiveBufferIfNecessary().
getExpirationTime()
virtual simtime_t inet::ieee80211::RecipientBlockAckAgreement::getExpirationTime () inline virtual
 { return expirationTime; }
getStartingSequenceNumber()
virtual SequenceNumberCyclic inet::ieee80211::RecipientBlockAckAgreement::getStartingSequenceNumber () const inline virtual
 { return startingSequenceNumber; }
Referenced by inet::ieee80211::BlockAckReordering::createReceiveBufferIfNecessary().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & os, const RecipientBlockAckAgreement & agreement) friend
 {
     os << "originator address = " << agreement.blockAckRecord->getOriginatorAddress() << ", "
        << "tid = " << agreement.blockAckRecord->getTid() << ", "
        << "starting sequence number = " << agreement.startingSequenceNumber << ", "
        << "buffer size = " << agreement.bufferSize << ", "
        << "block ack timeout value = " << agreement.blockAckTimeoutValue;
     return os;
 }
Member Data Documentation
blockAckRecord
BlockAckRecord* inet::ieee80211::RecipientBlockAckAgreement::blockAckRecord = nullptr protected
Referenced by blockAckPolicyFrameReceived(), inet::ieee80211::operator<<(), and RecipientBlockAckAgreement().
blockAckTimeoutValue
simtime_t inet::ieee80211::RecipientBlockAckAgreement::blockAckTimeoutValue = 0 protected
Referenced by inet::ieee80211::operator<<().
bufferSize
int inet::ieee80211::RecipientBlockAckAgreement::bufferSize = -1 protected
Referenced by inet::ieee80211::operator<<().
expirationTime
simtime_t inet::ieee80211::RecipientBlockAckAgreement::expirationTime = -1 protected
isAddbaResponseSent
bool inet::ieee80211::RecipientBlockAckAgreement::isAddbaResponseSent = false protected
startingSequenceNumber
SequenceNumberCyclic inet::ieee80211::RecipientBlockAckAgreement::startingSequenceNumber protected
Referenced by inet::ieee80211::operator<<().
The documentation for this class was generated from the following files:
RecipientBlockAckAgreement.h
RecipientBlockAckAgreement.cc