INET Framework for OMNeT++/OMNEST: inet::physicalenvironment::IPhysicalObject Class Reference
inet::physicalenvironment::IPhysicalObject Class Reference abstract
#include <IPhysicalObject.h>
Public Member Functions
virtual const Coord & getPosition () const =0
virtual const Quaternion & getOrientation () const =0
virtual const ShapeBase * getShape () const =0
virtual const IMaterial * getMaterial () const =0
virtual double getLineWidth () const =0
virtual const cFigure::Color & getLineColor () const =0
virtual const cFigure::Color & getFillColor () const =0
virtual double getOpacity () const =0
virtual const char * getTexture () const =0
virtual const char * getTags () const =0
Member Function Documentation
getFillColor()
virtual const cFigure::Color& inet::physicalenvironment::IPhysicalObject::getFillColor () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::visualizer::PhysicalEnvironmentCanvasVisualizer::computeFacePoints(), and inet::visualizer::PhysicalEnvironmentOsgVisualizer::refreshDisplay().
getLineColor()
virtual const cFigure::Color& inet::physicalenvironment::IPhysicalObject::getLineColor () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::visualizer::PhysicalEnvironmentCanvasVisualizer::computeFacePoints().
getLineWidth()
virtual double inet::physicalenvironment::IPhysicalObject::getLineWidth () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::visualizer::PhysicalEnvironmentCanvasVisualizer::computeFacePoints().
getMaterial()
virtual const IMaterial* inet::physicalenvironment::IPhysicalObject::getMaterial () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
getOpacity()
virtual double inet::physicalenvironment::IPhysicalObject::getOpacity () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::visualizer::PhysicalEnvironmentCanvasVisualizer::computeFacePoints().
getOrientation()
virtual const Quaternion& inet::physicalenvironment::IPhysicalObject::getOrientation () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
getPosition()
virtual const Coord& inet::physicalenvironment::IPhysicalObject::getPosition () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::BvhTree::computeBoundingBox(), inet::visualizer::PhysicalEnvironmentCanvasVisualizer::ObjectPositionComparator::operator()(), and inet::BvhTree::AxisComparator::operator()().
getShape()
virtual const ShapeBase* inet::physicalenvironment::IPhysicalObject::getShape () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::BvhTree::computeBoundingBox(), and inet::BvhTree::AxisComparator::operator()().
getTags()
virtual const char* inet::physicalenvironment::IPhysicalObject::getTags () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
Referenced by inet::visualizer::PhysicalEnvironmentCanvasVisualizer::computeFacePoints().
getTexture()
virtual const char* inet::physicalenvironment::IPhysicalObject::getTexture () const pure virtual
Implemented in inet::physicalenvironment::PhysicalObject.
The documentation for this class was generated from the following file:
IPhysicalObject.h