INET Framework for OMNeT++/OMNEST: inet::power::IEpEnergyStorage Class Reference
inet::power::IEpEnergyStorage Class Reference abstract
TODO.
#include <IEpEnergyStorage.h>
Public Member Functions
virtual J getNominalEnergyCapacity () const =0
Returns the nominal energy capacity in the range [0, +infinity].
virtual J getResidualEnergyCapacity () const =0
Returns the residual energy capacity in the range [0, nominalCapacity].
Public Member Functions inherited from inet::power::IEpEnergySource
virtual W getTotalPowerConsumption () const =0
Returns the total power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
virtual int getNumEnergyConsumers () const =0
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const =0
Returns the energy consumer for the provided index.
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer)=0
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer)=0
Removes a previously added energy consumer from this energy source.
Public Member Functions inherited from inet::power::IEpEnergySink
virtual W getTotalPowerGeneration () const =0
Returns the total power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
virtual int getNumEnergyGenerators () const =0
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const =0
Returns the energy generator for the provided index.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator)=0
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator)=0
Removes a previously added energy generator from this energy sink.
Static Public Attributes
static simsignal_t residualEnergyCapacityChangedSignal = cComponent::registerSignal("residualEnergyCapacityChanged")
The signal that is used to publish residual energy capacity changes also including when the energy storage becomes completely depleted or charged.
Static Public Attributes inherited from inet::power::IEpEnergySource
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Static Public Attributes inherited from inet::power::IEpEnergySink
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Detailed Description
TODO.
See the corresponding NED file for more details.
Member Function Documentation
getNominalEnergyCapacity()
virtual J inet::power::IEpEnergyStorage::getNominalEnergyCapacity () const pure virtual
Returns the nominal energy capacity in the range [0, +infinity].
It specifies the maximum amount of energy that the energy storage can contain.
Implemented in inet::power::SimpleEpEnergyStorage, and inet::power::IdealEpEnergyStorage.
getResidualEnergyCapacity()
virtual J inet::power::IEpEnergyStorage::getResidualEnergyCapacity () const pure virtual
Returns the residual energy capacity in the range [0, nominalCapacity].
It specifies the amount of energy that the energy storage contains at the moment.
Implemented in inet::power::SimpleEpEnergyStorage, and inet::power::IdealEpEnergyStorage.
Referenced by inet::power::SimpleEpEnergyManagement::getEstimatedEnergyCapacity().
Member Data Documentation
residualEnergyCapacityChangedSignal
simsignal_t inet::power::IEpEnergyStorage::residualEnergyCapacityChangedSignal = cComponent::registerSignal("residualEnergyCapacityChanged") static
The signal that is used to publish residual energy capacity changes also including when the energy storage becomes completely depleted or charged.
Referenced by inet::power::SimpleEpEnergyStorage::setResidualCapacity(), and inet::power::IdealEpEnergyStorage::updateEnergyBalance().
The documentation for this class was generated from the following files:
IEpEnergyStorage.h
IEpEnergyStorage.cc