INET Framework for OMNeT++/OMNEST: inet::IL3AddressType Class Reference
inet::IL3AddressType Class Reference abstract
This class provides the abstract interface for different address types.
#include <IL3AddressType.h>
Public Member Functions
IL3AddressType ()
virtual ~IL3AddressType ()
int getAddressByteLength () const
virtual int getAddressBitLength () const =0
virtual int getMaxPrefixLength () const =0
virtual L3Address getUnspecifiedAddress () const =0
virtual L3Address getBroadcastAddress () const =0
virtual L3Address getLinkLocalManetRoutersMulticastAddress () const =0
virtual L3Address getLinkLocalRIPRoutersMulticastAddress () const =0
virtual const Protocol * getNetworkProtocol () const =0
virtual L3Address getLinkLocalAddress (const NetworkInterface *ie) const =0
Returns the first valid link-local address of the interface, or UNSPECIFIED_ADDRESS if there's none.
Detailed Description
This class provides the abstract interface for different address types.
Constructor & Destructor Documentation
IL3AddressType()
inet::IL3AddressType::IL3AddressType () inline
 {}
~IL3AddressType()
virtual inet::IL3AddressType::~IL3AddressType () inline virtual
 {}
Member Function Documentation
getAddressBitLength()
virtual int inet::IL3AddressType::getAddressBitLength () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
getAddressByteLength()
int inet::IL3AddressType::getAddressByteLength () const inline
 { return (getAddressBitLength() + 7) / 8; };
Referenced by inet::Gpsr::computeOptionLength().
getBroadcastAddress()
virtual L3Address inet::IL3AddressType::getBroadcastAddress () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::ProbabilisticBroadcast::encapsulate(), inet::Flooding::encapsulate(), inet::aodv::Aodv::forwardRREQ(), inet::aodv::Aodv::handleLinkBreakSendRERR(), inet::aodv::Aodv::handleRERR(), inet::aodv::Aodv::handleWaitForRREP(), inet::aodv::Aodv::sendHelloMessagesIfNeeded(), inet::aodv::Aodv::sendRERRWhenNoRouteToForward(), and inet::aodv::Aodv::startRouteDiscovery().
getLinkLocalAddress()
virtual L3Address inet::IL3AddressType::getLinkLocalAddress (const NetworkInterface * ie) const pure virtual
Returns the first valid link-local address of the interface, or UNSPECIFIED_ADDRESS if there's none.
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::Rip::sendPacket().
getLinkLocalManetRoutersMulticastAddress()
virtual L3Address inet::IL3AddressType::getLinkLocalManetRoutersMulticastAddress () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::Gpsr::configureInterfaces(), inet::dymo::Dymo::configureInterfaces(), inet::Gpsr::sendBeacon(), inet::dymo::Dymo::sendRerr(), inet::dymo::Dymo::sendRrep(), and inet::dymo::Dymo::sendRreq().
getLinkLocalRIPRoutersMulticastAddress()
virtual L3Address inet::IL3AddressType::getLinkLocalRIPRoutersMulticastAddress () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::Rip::handleStopOperation(), inet::Rip::processUpdate(), inet::Rip::sendRIPRequest(), and inet::Rip::startRIPRouting().
getMaxPrefixLength()
virtual int inet::IL3AddressType::getMaxPrefixLength () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::dymo::Dymo::addSelfNode(), inet::dymo::Dymo::createRerr(), inet::aodv::Aodv::createRoute(), inet::dymo::Dymo::createRreq(), inet::dymo::Dymo::initialize(), and inet::Rip::isValidResponse().
getNetworkProtocol()
virtual const Protocol* inet::IL3AddressType::getNetworkProtocol () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::tcp::TcpLwip::ip_output(), inet::sctp::Sctp::sendAbortFromMain(), inet::Gpsr::sendBeacon(), inet::dymo::Dymo::sendDymoPacket(), inet::IpvxTrafGen::sendPacket(), inet::sctp::Sctp::sendShutdownCompleteFromMain(), inet::tcp::TcpSpoof::sendToIP(), inet::tcp::TcpConnection::sendToIP(), and inet::sctp::SctpAssociation::sendToIP().
getUnspecifiedAddress()
virtual L3Address inet::IL3AddressType::getUnspecifiedAddress () const pure virtual
Implemented in inet::CLNSAddressType, inet::Ipv4AddressType, inet::Ipv6AddressType, inet::MacAddressType, inet::ModuleIdAddressType, and inet::ModulePathAddressType.
Referenced by inet::Rip::sendRoutes().
The documentation for this class was generated from the following file:
IL3AddressType.h