INET Framework for OMNeT++/OMNEST: inet::queueing::IPacketCollection Class Reference
inet::queueing::IPacketCollection Class Reference abstract
This class defines the interface for packet collections.
#include <IPacketCollection.h>
Public Member Functions
virtual int getMaxNumPackets () const =0
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const =0
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const =0
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const =0
Returns the total length of all packets in the collection in the range [0, inf).
virtual Packet * getPacket (int index) const =0
Returns the packet at the given index.
virtual bool isEmpty () const =0
Returns true if there are no packets available in the collection.
virtual void removePacket (Packet *packet)=0
Removes a packet from the collection.
virtual void removeAllPackets ()=0
Removes all packets from the collection.
Detailed Description
This class defines the interface for packet collections.
Member Function Documentation
getMaxNumPackets()
virtual int inet::queueing::IPacketCollection::getMaxNumPackets () const pure virtual
Returns maximum allowed number of packets in the collection.
The value -1 means no such limit.
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
getMaxTotalLength()
virtual b inet::queueing::IPacketCollection::getMaxTotalLength () const pure virtual
Returns maximum allowed total length of all packets in the collection.
The value -1 means no such limit.
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
getNumPackets()
virtual int inet::queueing::IPacketCollection::getNumPackets () const pure virtual
Returns the number of available packets in the collection in the range [0, inf).
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
Referenced by inet::ieee80211::BasicMsduAggregationPolicy::computeAggregateFrames(), inet::queueing::CompoundPacketQueueBase::getNumPackets(), inet::queueing::PacketBufferBase::resolveDirective(), and inet::queueing::PacketQueueBase::resolveDirective().
getPacket()
virtual Packet* inet::queueing::IPacketCollection::getPacket (int index) const pure virtual
Returns the packet at the given index.
Throws error when the index is out of range.
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::WrrScheduler, inet::queueing::PacketBuffer, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
Referenced by inet::ieee80211::BasicMsduAggregationPolicy::computeAggregateFrames(), inet::queueing::CompoundPacketQueueBase::getPacket(), and inet::queueing::PacketQueueBase::resolveDirective().
getTotalLength()
virtual b inet::queueing::IPacketCollection::getTotalLength () const pure virtual
Returns the total length of all packets in the collection in the range [0, inf).
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
Referenced by inet::queueing::CompoundPacketQueueBase::getTotalLength(), inet::queueing::PacketBufferBase::resolveDirective(), and inet::queueing::PacketQueueBase::resolveDirective().
isEmpty()
virtual bool inet::queueing::IPacketCollection::isEmpty () const pure virtual
Returns true if there are no packets available in the collection.
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
Referenced by inet::ieee80211::BasicMsduAggregationPolicy::computeAggregateFrames(), inet::ieee80211::OriginatorMacDataService::extractFramesToTransmit(), inet::ieee80211::OriginatorQosMacDataService::extractFramesToTransmit(), inet::queueing::CompoundPacketQueueBase::isEmpty(), and inet::queueing::PacketQueueBase::resolveDirective().
removeAllPackets()
virtual void inet::queueing::IPacketCollection::removeAllPackets () pure virtual
Removes all packets from the collection.
Implemented in inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
Referenced by inet::queueing::CompoundPacketQueueBase::removeAllPackets(), and inet::queueing::PacketQueue::removeAllPackets().
removePacket()
virtual void inet::queueing::IPacketCollection::removePacket (Packet * packet) pure virtual
Removes a packet from the collection.
The collection must contain the packet.
Implemented in inet::queueing::IPacketBuffer, inet::queueing::PacketFlowBase, inet::queueing::PacketQueue, inet::queueing::CompoundPacketQueueBase, inet::queueing::PacketBuffer, inet::queueing::WrrScheduler, inet::queueing::LabelScheduler, and inet::queueing::PriorityScheduler.
Referenced by inet::ieee80211::OriginatorQosMacDataService::aMsduAggregateIfNeeded(), and inet::queueing::CompoundPacketQueueBase::removePacket().
The documentation for this class was generated from the following file:
IPacketCollection.h