INET Framework for OMNeT++/OMNEST: inet::visualizer::ModuleFilter Class Reference
inet::visualizer::ModuleFilter Class Reference
This class provides a generic filter for modules.
#include <ModuleFilter.h>
Public Member Functions
void setPattern (const char *pattern)
bool matches (const cModule *module) const
Protected Attributes
cMatchExpression matchExpression
Detailed Description
This class provides a generic filter for modules.
The filter is expressed as a pattern using the cMatchExpression format.
Member Function Documentation
matches()
bool inet::visualizer::ModuleFilter::matches (const cModule * module) const
 {
     MatchableObject matchableObject(MatchableObject::ATTRIBUTE_FULLPATH, module);
     return matchExpression.matches(&matchableObject);
 }
Referenced by inet::visualizer::EnergyStorageVisualizerBase::addEnergyStorageVisualizations(), inet::visualizer::InfoVisualizerBase::addInfoVisualizations(), inet::visualizer::StatisticVisualizerBase::processSignal(), inet::visualizer::MobilityVisualizerBase::receiveSignal(), and inet::visualizer::RadioVisualizerBase::receiveSignal().
setPattern()
void inet::visualizer::ModuleFilter::setPattern (const char * pattern)
 {
     matchExpression.setPattern(pattern, true, true, true);
 }
Referenced by inet::visualizer::InfoVisualizerBase::handleParameterChange(), inet::visualizer::RadioVisualizerBase::handleParameterChange(), inet::visualizer::MobilityVisualizerBase::handleParameterChange(), inet::visualizer::StatisticVisualizerBase::handleParameterChange(), inet::visualizer::EnergyStorageVisualizerBase::initialize(), inet::visualizer::InfoVisualizerBase::initialize(), inet::visualizer::RadioVisualizerBase::initialize(), inet::visualizer::MobilityVisualizerBase::initialize(), and inet::visualizer::StatisticVisualizerBase::initialize().
Member Data Documentation
matchExpression
cMatchExpression inet::visualizer::ModuleFilter::matchExpression protected
Referenced by matches(), and setPattern().
The documentation for this class was generated from the following files:
ModuleFilter.h
ModuleFilter.cc