INET Framework for OMNeT++/OMNEST: inet::physicallayer::IAntenna Class Reference
inet::physicallayer::IAntenna Class Reference abstract
This interface represents a physical device (a part of the radio) which converts electric signals into radio waves, and vice versa.
#include <IAntenna.h>
Public Member Functions
virtual IMobility * getMobility () const =0
Returns the mobility of this antenna that describes its position and orientation over time.
virtual bool isDirectional () const =0
Returns true if the antenna has directional selectivity (i.e.
virtual Ptr< const IAntennaGain > getGain () const =0
Returns the antenna's gain calculator for directional selectivity.
virtual int getNumAntennas () const =0
Returns the number of antennas in the array.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents a physical device (a part of the radio) which converts electric signals into radio waves, and vice versa.
Member Function Documentation
getGain()
virtual Ptr<const IAntennaGain> inet::physicallayer::IAntenna::getGain () const pure virtual
Returns the antenna's gain calculator for directional selectivity.
This object may be copied as needed, i.e. IAntennaGain objects are expected to have no reference to other objects.
Implemented in inet::physicallayer::InterpolatingAntenna, inet::physicallayer::AxiallySymmetricAntenna, inet::physicallayer::ParabolicAntenna, inet::physicallayer::CosineAntenna, inet::physicallayer::DipoleAntenna, inet::physicallayer::ConstantGainAntenna, and inet::physicallayer::IsotropicAntenna.
Referenced by inet::physicallayer::DimensionalAnalogModelBase::computeReceptionPower(), inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower(), and inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe().
getMobility()
virtual IMobility* inet::physicallayer::IAntenna::getMobility () const pure virtual
Returns the mobility of this antenna that describes its position and orientation over time.
Implemented in inet::physicallayer::AntennaBase.
Referenced by inet::physicallayer::GridNeighborCache::addRadio(), inet::physicallayer::QuadTreeNeighborCache::addRadio(), inet::physicallayer::RadioMedium::addRadio(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::physicallayer::ApskScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter::createTransmission(), inet::physicallayer::ApskDimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), inet::physicallayer::NoiseDimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission(), inet::physicallayer::UnitDiskTransmitter::createTransmission(), inet::physicallayer::Ieee802154UwbIrTransmitter::createTransmission(), inet::physicallayer::ApskLayeredTransmitter::createTransmission(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createTransmission(), inet::physicallayer::GridNeighborCache::fillCubeVector(), inet::physicallayer::Radio::isListeningPossible(), inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe(), inet::physicallayer::GridNeighborCache::sendToNeighbors(), inet::physicallayer::QuadTreeNeighborCache::sendToNeighbors(), and inet::physicallayer::NeighborListNeighborCache::updateNeighborList().
getNumAntennas()
virtual int inet::physicallayer::IAntenna::getNumAntennas () const pure virtual
Returns the number of antennas in the array.
Implemented in inet::physicallayer::AntennaBase.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
isDirectional()
virtual bool inet::physicallayer::IAntenna::isDirectional () const pure virtual
Returns true if the antenna has directional selectivity (i.e.
the gain is not always 1).
Implemented in inet::physicallayer::AntennaBase.
The documentation for this class was generated from the following file:
IAntenna.h