INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpInterface Class Reference
inet::eigrp::EigrpInterface Class Reference
#include <EigrpInterfaceTable.h>
Public Member Functions
EigrpInterface (NetworkInterface *iface, int networkId, bool enabled)
~EigrpInterface ()
bool operator== (const EigrpInterface &iface) const
void setInterfaceId (int id)
int getInterfaceId () const
void setHelloTimerPtr (EigrpTimer *timer)
EigrpTimer * getHelloTimer () const
void setHelloInt (int helloInt)
int getHelloInt () const
void setHoldInt (int holdInt)
int getHoldInt () const
void setEnabling (bool enabled)
bool isEnabled () const
void setNetworkId (int netId)
int getNetworkId () const
void decNumOfNeighbors ()
void incNumOfNeighbors ()
int getNumOfNeighbors () const
void decNumOfStubs ()
void incNumOfStubs ()
int getNumOfStubs () const
void setBandwidth (uint64_t bw)
uint64_t getBandwidth () const
void setInterfaceDatarate (double datarate)
double getInterfaceDatarate () const
void setDelay (uint64_t dly)
uint64_t getDelay () const
void setReliability (int rel)
int getReliability () const
void setLoad (int load)
int getLoad () const
void setMtu (int mtu)
int getMtu () const
bool isMulticastAllowedOnIface (NetworkInterface *iface)
void setSplitHorizon (bool shEnabled)
bool isSplitHorizonEn () const
void setRelMsgs (int cnt)
int getRelMsgs () const
void setPendingMsgs (int cnt)
int getPendingMsgs () const
void incPendingMsgs ()
void decPendingMsgs ()
void setPassive (bool passive)
bool isPassive () const
const char * getInterfaceName () const
std::set< int >::iterator getNetworksIdsBegin ()
Get networkIds set .begin()
std::set< int >::iterator getNetworksIdsEnd ()
Get networksIds set .end()
std::pair< std::set< int >::iterator, bool > insertToNetworksIds (int netId)
Insert networkID into set.
void clearNetworkIds ()
Clears networksIds set.
Protected Attributes
int interfaceId
ID of interface.
const char * interfaceName
Name of interface.
int networkId
ID of network in RoutingOfNetworks table.
std::set< int > networksIds
IDs of IPv6 networks in RoutingOfNetworks table.
int helloInt
Hello interval in seconds (<1-65535>)
int holdInt
Router's hold interval in seconds (<1-65535>)
EigrpTimer * hellot
pointer to hello timer
bool enabled
EIGRP is enabled on interface.
bool splitHorizon
Split horizon rule enabled.
bool passive
Interface is passive.
double interfaceDatarate
Datarate of NetworkInterface interface.
uint64_t bandwidth
Bandwidth in Kbps (<1-10 000 000>)
uint64_t delay
Delay in us (<1-16 777 215>)
int reliability
Reliability in percent (<1-255>)
int load
Load in percent (<1-255>)
int mtu
MTU of interface in B.
int relMsgs
Number of messages waiting for sending on the interface.
int pendingMsgs
Number of reliable sent messages but not acknowledged.
int neighborCount
Number of neighbors on interface.
int stubCount
Number of stub neighbors on interface.
Constructor & Destructor Documentation
EigrpInterface()
inet::eigrp::EigrpInterface::EigrpInterface (NetworkInterface * iface, int networkId, bool enabled)
                                                                                    :
                interfaceId(iface->getInterfaceId()), networkId(networkId), enabled(enabled)
 {
     hellot = nullptr;
     neighborCount = 0;
     stubCount = 0;
     splitHorizon = true;
     passive = false;
     mtu = iface->getMtu();
     this->setInterfaceDatarate(iface->getDatarate());
     load = 1;
     reliability = 255;
     interfaceName = iface->getInterfaceName();
     relMsgs = 0;
     pendingMsgs = 0;
     if (!iface->isMulticast() && bandwidth <= 1544) { // Non-broadcast Multi Access interface (no multicast) with bandwidth equal or lower than T1 link
         helloInt = 60;
         holdInt = 180;
     }
     else {
         helloInt = 5;
         holdInt = 15;
     }
 }
~EigrpInterface()
inet::eigrp::EigrpInterface::~EigrpInterface ()
 {
     hellot = nullptr;
 }
Member Function Documentation
clearNetworkIds()
void inet::eigrp::EigrpInterface::clearNetworkIds () inline
Clears networksIds set.
 { networksIds.clear(); }
Referenced by inet::eigrp::EigrpIpv6Pdm::disableInterface().
decNumOfNeighbors()
void inet::eigrp::EigrpInterface::decNumOfNeighbors () inline
 { this->neighborCount--; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
decNumOfStubs()
void inet::eigrp::EigrpInterface::decNumOfStubs () inline
 { this->stubCount--; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), and inet::eigrp::EigrpIpv6Pdm::removeNeighbor().
decPendingMsgs()
void inet::eigrp::EigrpInterface::decPendingMsgs () inline
 { this->pendingMsgs--; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::processHeader().
getBandwidth()
uint64_t inet::eigrp::EigrpInterface::getBandwidth () const inline
 { return bandwidth; }
Referenced by inet::eigrp::EigrpMetricHelper::getParam().
getDelay()
uint64_t inet::eigrp::EigrpInterface::getDelay () const inline
 { return delay; }
Referenced by inet::eigrp::EigrpMetricHelper::getParam().
getHelloInt()
int inet::eigrp::EigrpInterface::getHelloInt () const inline
 { return this->helloInt; }
Referenced by inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), inet::eigrp::EigrpIpv6Pdm::processHelloPacket(), inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv6Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv4Pdm::processTimer(), and inet::eigrp::EigrpIpv6Pdm::processTimer().
getHelloTimer()
EigrpTimer* inet::eigrp::EigrpInterface::getHelloTimer () const inline
 { return this->hellot; }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv6Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), inet::eigrp::EigrpIpv6Pdm::processHelloPacket(), inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv6Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv4Pdm::processTimer(), inet::eigrp::EigrpIpv6Pdm::processTimer(), inet::eigrp::EigrpIpv4Pdm::setPassive(), inet::eigrp::EigrpIpv6Pdm::setPassive(), inet::eigrp::EigrpIpv4Pdm::startHelloTimer(), and inet::eigrp::EigrpIpv6Pdm::startHelloTimer().
getHoldInt()
int inet::eigrp::EigrpInterface::getHoldInt () const inline
 { return this->holdInt; }
Referenced by inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), and inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp().
getInterfaceDatarate()
double inet::eigrp::EigrpInterface::getInterfaceDatarate () const inline
 { return interfaceDatarate; }
Referenced by inet::eigrp::EigrpIpv6Pdm::receiveSignal(), and inet::eigrp::EigrpIpv4Pdm::receiveSignal().
getInterfaceId()
int inet::eigrp::EigrpInterface::getInterfaceId () const inline
 { return interfaceId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applySplitHorizon(), inet::eigrp::EigrpIpv6Pdm::applySplitHorizon(), inet::eigrp::EigrpIpv4Pdm::createNeighbor(), inet::eigrp::EigrpIpv6Pdm::createNeighbor(), inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpDisabledInterfaces::findInterface(), inet::eigrp::EigrpInterfaceTable::findInterfaceById(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::findOrCreateRoute(), inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::eigrp::operator<<(), operator==(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processTimer(), and inet::eigrp::EigrpIpv6Pdm::processTimer().
getInterfaceName()
const char* inet::eigrp::EigrpInterface::getInterfaceName () const inline
 { return this->interfaceName; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createNeighbor(), inet::eigrp::EigrpIpv6Pdm::createNeighbor(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::findOrCreateRoute(), and inet::eigrp::operator<<().
getLoad()
int inet::eigrp::EigrpInterface::getLoad () const inline
 { return load; }
Referenced by inet::eigrp::EigrpMetricHelper::getParam().
getMtu()
int inet::eigrp::EigrpInterface::getMtu () const inline
 { return mtu; }
Referenced by inet::eigrp::EigrpMetricHelper::getParam().
getNetworkId()
int inet::eigrp::EigrpInterface::getNetworkId () const inline
 { return this->networkId; }
getNetworksIdsBegin()
std::set<int>::iterator inet::eigrp::EigrpInterface::getNetworksIdsBegin () inline
Get networkIds set .begin()
 { return networksIds.begin(); }
Referenced by inet::eigrp::EigrpIpv6Pdm::disableInterface().
getNetworksIdsEnd()
std::set<int>::iterator inet::eigrp::EigrpInterface::getNetworksIdsEnd () inline
Get networksIds set .end()
 { return networksIds.end(); }
Referenced by inet::eigrp::EigrpIpv6Pdm::disableInterface().
getNumOfNeighbors()
int inet::eigrp::EigrpInterface::getNumOfNeighbors () const inline
 { return this->neighborCount; }
Referenced by inet::eigrp::EigrpIpv4Pdm::hasNeighborForUpdate(), inet::eigrp::EigrpIpv6Pdm::hasNeighborForUpdate(), isMulticastAllowedOnIface(), inet::eigrp::EigrpIpv4Pdm::msgToAllIfaces(), inet::eigrp::EigrpIpv6Pdm::msgToAllIfaces(), and inet::eigrp::operator<<().
getNumOfStubs()
int inet::eigrp::EigrpInterface::getNumOfStubs () const inline
 { return this->stubCount; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applyStubToQuery(), inet::eigrp::EigrpIpv6Pdm::applyStubToQuery(), inet::eigrp::EigrpIpv4Pdm::msgToAllIfaces(), and inet::eigrp::EigrpIpv6Pdm::msgToAllIfaces().
getPendingMsgs()
int inet::eigrp::EigrpInterface::getPendingMsgs () const inline
 { return pendingMsgs; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::scheduleNextMsg().
getReliability()
int inet::eigrp::EigrpInterface::getReliability () const inline
 { return reliability; }
Referenced by inet::eigrp::EigrpMetricHelper::getParam().
getRelMsgs()
int inet::eigrp::EigrpInterface::getRelMsgs () const inline
 { return relMsgs; }
incNumOfNeighbors()
void inet::eigrp::EigrpInterface::incNumOfNeighbors () inline
 { this->neighborCount++; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createNeighbor(), and inet::eigrp::EigrpIpv6Pdm::createNeighbor().
incNumOfStubs()
void inet::eigrp::EigrpInterface::incNumOfStubs () inline
 { this->stubCount++; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), and inet::eigrp::EigrpIpv6Pdm::processNewNeighbor().
incPendingMsgs()
void inet::eigrp::EigrpInterface::incPendingMsgs () inline
 { this->pendingMsgs++; }
Referenced by inet::eigrp::EigrpRtpT< Ipv4Address >::sendRelMsg().
insertToNetworksIds()
std::pair<std::set<int>::iterator, bool> inet::eigrp::EigrpInterface::insertToNetworksIds (int netId) inline
Insert networkID into set.
 { return networksIds.insert(netId); }
Referenced by inet::eigrp::EigrpIpv6Pdm::enableInterface().
isEnabled()
bool inet::eigrp::EigrpInterface::isEnabled () const inline
 { return this->enabled; }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::receiveSignal(), inet::eigrp::EigrpIpv4Pdm::receiveSignal(), inet::eigrp::EigrpIpv4Pdm::setPassive(), and inet::eigrp::EigrpIpv6Pdm::setPassive().
isMulticastAllowedOnIface()
bool inet::eigrp::EigrpInterface::isMulticastAllowedOnIface (NetworkInterface * iface)
 {
     if (iface->isMulticast())
         if (getNumOfNeighbors() > 1)
             return true;
     return false;
 }
isPassive()
bool inet::eigrp::EigrpInterface::isPassive () const inline
 { return this->passive; }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::processMsgFromNetwork(), inet::eigrp::EigrpIpv6Pdm::processMsgFromNetwork(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv4Pdm::startHelloTimer(), and inet::eigrp::EigrpIpv6Pdm::startHelloTimer().
isSplitHorizonEn()
bool inet::eigrp::EigrpInterface::isSplitHorizonEn () const inline
 { return this->splitHorizon; }
Referenced by inet::eigrp::EigrpIpv4Pdm::msgToIface(), inet::eigrp::EigrpIpv6Pdm::msgToIface(), inet::eigrp::operator<<(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
operator==()
bool inet::eigrp::EigrpInterface::operator== (const EigrpInterface & iface) const inline
     {
         return interfaceId == iface.getInterfaceId();
     }
setBandwidth()
void inet::eigrp::EigrpInterface::setBandwidth (uint64_t bw) inline
 { this->bandwidth = bw; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setBandwidth(), and inet::eigrp::EigrpIpv6Pdm::setBandwidth().
setDelay()
void inet::eigrp::EigrpInterface::setDelay (uint64_t dly) inline
 { this->delay = dly; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setDelay(), and inet::eigrp::EigrpIpv6Pdm::setDelay().
setEnabling()
void inet::eigrp::EigrpInterface::setEnabling (bool enabled) inline
 { this->enabled = enabled; }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::enableInterface(), and inet::eigrp::EigrpIpv6Pdm::enableInterface().
setHelloInt()
void inet::eigrp::EigrpInterface::setHelloInt (int helloInt) inline
 { this->helloInt = helloInt; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setHelloInt(), and inet::eigrp::EigrpIpv6Pdm::setHelloInt().
setHelloTimerPtr()
void inet::eigrp::EigrpInterface::setHelloTimerPtr (EigrpTimer * timer) inline
 { this->hellot = timer; }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv6Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv4Pdm::setPassive(), inet::eigrp::EigrpIpv6Pdm::setPassive(), inet::eigrp::EigrpIpv4Pdm::startHelloTimer(), and inet::eigrp::EigrpIpv6Pdm::startHelloTimer().
setHoldInt()
void inet::eigrp::EigrpInterface::setHoldInt (int holdInt) inline
 { this->holdInt = holdInt; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setHoldInt(), and inet::eigrp::EigrpIpv6Pdm::setHoldInt().
setInterfaceDatarate()
void inet::eigrp::EigrpInterface::setInterfaceDatarate (double datarate)
{
     interfaceDatarate = datarate;
     switch ((long)datarate) {
         case 64000: // 56k modem
             delay = 20000;
             break;
         case 56000: // 56k modem
             delay = 20000;
             break;
         case 1544000: // T1
             delay = 20000;
             break;
         case 10000000: // Eth10
             delay = 1000;
             break;
         default: // >Eth10
             delay = 100;
             break;
     }
     bandwidth = datarate / 1000;
 }
Referenced by EigrpInterface(), inet::eigrp::EigrpIpv6Pdm::receiveSignal(), and inet::eigrp::EigrpIpv4Pdm::receiveSignal().
setInterfaceId()
void inet::eigrp::EigrpInterface::setInterfaceId (int id) inline
 { interfaceId = id; }
setLoad()
void inet::eigrp::EigrpInterface::setLoad (int load) inline
 { this->load = load; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setLoad(), and inet::eigrp::EigrpIpv6Pdm::setLoad().
setMtu()
void inet::eigrp::EigrpInterface::setMtu (int mtu) inline
 { this->mtu = mtu; }
setNetworkId()
void inet::eigrp::EigrpInterface::setNetworkId (int netId) inline
 { this->networkId = netId; }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface().
setPassive()
void inet::eigrp::EigrpInterface::setPassive (bool passive) inline
 { this->passive = passive; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setPassive(), and inet::eigrp::EigrpIpv6Pdm::setPassive().
setPendingMsgs()
void inet::eigrp::EigrpInterface::setPendingMsgs (int cnt) inline
 { this->pendingMsgs = cnt; }
setReliability()
void inet::eigrp::EigrpInterface::setReliability (int rel) inline
 { this->reliability = rel; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setReliability(), and inet::eigrp::EigrpIpv6Pdm::setReliability().
setRelMsgs()
void inet::eigrp::EigrpInterface::setRelMsgs (int cnt) inline
 { this->relMsgs = cnt; }
setSplitHorizon()
void inet::eigrp::EigrpInterface::setSplitHorizon (bool shEnabled) inline
 { this->splitHorizon = shEnabled; }
Referenced by inet::eigrp::EigrpIpv4Pdm::setSplitHorizon(), and inet::eigrp::EigrpIpv6Pdm::setSplitHorizon().
Member Data Documentation
bandwidth
uint64_t inet::eigrp::EigrpInterface::bandwidth protected
Bandwidth in Kbps (<1-10 000 000>)
Referenced by EigrpInterface(), getBandwidth(), and setInterfaceDatarate().
delay
uint64_t inet::eigrp::EigrpInterface::delay protected
Delay in us (<1-16 777 215>)
Referenced by getDelay(), and setInterfaceDatarate().
enabled
bool inet::eigrp::EigrpInterface::enabled protected
EIGRP is enabled on interface.
Referenced by isEnabled(), and setEnabling().
helloInt
int inet::eigrp::EigrpInterface::helloInt protected
Hello interval in seconds (<1-65535>)
Referenced by EigrpInterface(), getHelloInt(), and setHelloInt().
hellot
EigrpTimer* inet::eigrp::EigrpInterface::hellot protected
pointer to hello timer
Referenced by EigrpInterface(), getHelloTimer(), and ~EigrpInterface().
holdInt
int inet::eigrp::EigrpInterface::holdInt protected
Router's hold interval in seconds (<1-65535>)
Referenced by EigrpInterface(), getHoldInt(), and setHoldInt().
interfaceDatarate
double inet::eigrp::EigrpInterface::interfaceDatarate protected
Datarate of NetworkInterface interface.
Referenced by getInterfaceDatarate(), and setInterfaceDatarate().
interfaceId
int inet::eigrp::EigrpInterface::interfaceId protected
ID of interface.
Referenced by getInterfaceId(), operator==(), and setInterfaceId().
interfaceName
const char* inet::eigrp::EigrpInterface::interfaceName protected
Name of interface.
Referenced by EigrpInterface(), and getInterfaceName().
load
int inet::eigrp::EigrpInterface::load protected
Load in percent (<1-255>)
Referenced by EigrpInterface(), getLoad(), and setLoad().
mtu
int inet::eigrp::EigrpInterface::mtu protected
MTU of interface in B.
Referenced by EigrpInterface(), getMtu(), and setMtu().
neighborCount
int inet::eigrp::EigrpInterface::neighborCount protected
Number of neighbors on interface.
Referenced by EigrpInterface(), and getNumOfNeighbors().
networkId
int inet::eigrp::EigrpInterface::networkId protected
ID of network in RoutingOfNetworks table.
Referenced by getNetworkId().
networksIds
std::set<int> inet::eigrp::EigrpInterface::networksIds protected
IDs of IPv6 networks in RoutingOfNetworks table.
Referenced by clearNetworkIds(), getNetworksIdsBegin(), getNetworksIdsEnd(), and insertToNetworksIds().
passive
bool inet::eigrp::EigrpInterface::passive protected
Interface is passive.
Referenced by EigrpInterface(), isPassive(), and setPassive().
pendingMsgs
int inet::eigrp::EigrpInterface::pendingMsgs protected
Number of reliable sent messages but not acknowledged.
Referenced by EigrpInterface(), and getPendingMsgs().
reliability
int inet::eigrp::EigrpInterface::reliability protected
Reliability in percent (<1-255>)
Referenced by EigrpInterface(), and getReliability().
relMsgs
int inet::eigrp::EigrpInterface::relMsgs protected
Number of messages waiting for sending on the interface.
Referenced by EigrpInterface(), and getRelMsgs().
splitHorizon
bool inet::eigrp::EigrpInterface::splitHorizon protected
Split horizon rule enabled.
Referenced by EigrpInterface(), and isSplitHorizonEn().
stubCount
int inet::eigrp::EigrpInterface::stubCount protected
Number of stub neighbors on interface.
Referenced by EigrpInterface(), and getNumOfStubs().
The documentation for this class was generated from the following files:
EigrpInterfaceTable.h
EigrpInterfaceTable.cc