INET Framework for OMNeT++/OMNEST: inet::sctp::SctpParameter Class Reference
inet::sctp::SctpParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:228 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual SctpParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:228 by opp_msgtool.
class SctpParameter extends cPacket
{
    @packetData;
    uint16_t parameterType;
}
Constructor & Destructor Documentation
SctpParameter() [1/2]
inet::sctp::SctpParameter::SctpParameter (const char * name = nullptr)
SctpParameter() [2/2]
inet::sctp::SctpParameter::SctpParameter (const SctpParameter & other)
~SctpParameter()
virtual inet::sctp::SctpParameter::~SctpParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpParameter::copy (const SctpParameter & other) private
dup()
virtual SctpParameter* inet::sctp::SctpParameter::dup () const inline override virtual
Reimplemented in inet::sctp::SctpSuccessIndication, inet::sctp::SctpSimpleErrorCauseParameter, inet::sctp::SctpErrorCauseParameter, inet::sctp::SctpSupportedExtensionsParameter, inet::sctp::SctpSetPrimaryIPParameter, inet::sctp::SctpDeleteIPParameter, inet::sctp::SctpAddIPParameter, inet::sctp::SctpAddStreamsRequestParameter, inet::sctp::SctpStreamResetResponseParameter, inet::sctp::SctpSsnTsnResetRequestParameter, inet::sctp::SctpIncomingSsnResetRequestParameter_Base, inet::sctp::SctpOutgoingSsnResetRequestParameter, and inet::sctp::SctpIncomingSsnResetRequestParameter.
 {return new SctpParameter(*this);}
Referenced by inet::sctp::SctpAssociation::checkStreamsToReset(), inet::sctp::SctpAssociation::processIncomingResetRequestArrived(), and inet::sctp::SctpAssociation::processStreamResetArrived().
getParameterType()
virtual uint16_t inet::sctp::SctpParameter::getParameterType () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::processErrorArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpParameter& inet::sctp::SctpParameter::operator= (const SctpParameter & other)
operator==()
bool inet::sctp::SctpParameter::operator== (const SctpParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::sctp::SctpSuccessIndication, inet::sctp::SctpSimpleErrorCauseParameter, inet::sctp::SctpErrorCauseParameter, inet::sctp::SctpSupportedExtensionsParameter, inet::sctp::SctpSetPrimaryIPParameter, inet::sctp::SctpDeleteIPParameter, inet::sctp::SctpAddIPParameter, inet::sctp::SctpAddStreamsRequestParameter, inet::sctp::SctpStreamResetResponseParameter, inet::sctp::SctpSsnTsnResetRequestParameter, inet::sctp::SctpIncomingSsnResetRequestParameter_Base, and inet::sctp::SctpOutgoingSsnResetRequestParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::sctp::SctpSuccessIndication, inet::sctp::SctpSimpleErrorCauseParameter, inet::sctp::SctpErrorCauseParameter, inet::sctp::SctpSupportedExtensionsParameter, inet::sctp::SctpSetPrimaryIPParameter, inet::sctp::SctpDeleteIPParameter, inet::sctp::SctpAddIPParameter, inet::sctp::SctpAddStreamsRequestParameter, inet::sctp::SctpStreamResetResponseParameter, inet::sctp::SctpSsnTsnResetRequestParameter, inet::sctp::SctpIncomingSsnResetRequestParameter_Base, and inet::sctp::SctpOutgoingSsnResetRequestParameter.
Referenced by inet::sctp::doParsimUnpacking().
setParameterType()
virtual void inet::sctp::SctpParameter::setParameterType (uint16_t parameterType) virtual
Referenced by inet::sctp::SctpAssociation::createSuccessIndication(), inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::makeAddStreamsRequestParameter(), inet::sctp::SctpAssociation::makeIncomingStreamResetParameter(), inet::sctp::SctpAssociation::makeOutgoingStreamResetParameter(), inet::sctp::SctpAssociation::makeSsnTsnResetParameter(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::sendAddOutgoingStreamsRequest(), inet::sctp::SctpAssociation::sendAsconf(), inet::sctp::SctpNatHook::sendBackError(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendDoubleStreamResetResponse(), inet::sctp::SctpAssociation::sendHMacError(), inet::sctp::SctpAssociation::sendInvalidStreamError(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), inet::sctp::SctpAssociation::sendOutgoingResetRequest(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
Member Data Documentation
parameterType
uint16_t inet::sctp::SctpParameter::parameterType = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h