INET Framework for OMNeT++/OMNEST: inet::queueing::ITokenStorage Class Reference
inet::queueing::ITokenStorage Class Reference abstract
This class defines the interface for token storages.
#include <ITokenStorage.h>
Public Member Functions
virtual ~ITokenStorage ()
virtual double getNumTokens () const =0
virtual void addTokens (double numTokens)=0
virtual void removeTokens (double numTokens)=0
virtual void addTokenProductionRate (double tokenRate)=0
virtual void removeTokenProductionRate (double tokenRate)=0
Detailed Description
This class defines the interface for token storages.
Constructor & Destructor Documentation
~ITokenStorage()
virtual inet::queueing::ITokenStorage::~ITokenStorage () inline virtual
 {}
Member Function Documentation
addTokenProductionRate()
virtual void inet::queueing::ITokenStorage::addTokenProductionRate (double tokenRate) pure virtual
Implemented in inet::queueing::MultiTokenBucketMixin< T >, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucketMixin< T >, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::TokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucket, and inet::queueing::TokenBasedServer.
Referenced by inet::queueing::TokenBucket::addTokenProductionRate(), and inet::queueing::TokenBucket::addTokens().
addTokens()
virtual void inet::queueing::ITokenStorage::addTokens (double numTokens) pure virtual
Implemented in inet::queueing::TokenBasedServer, inet::queueing::MultiTokenBucketMixin< T >, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucketMixin< T >, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::TokenBucketMixin< PacketClassifierBase >, and inet::queueing::TokenBucket.
Referenced by inet::queueing::TokenBucket::addTokens().
getNumTokens()
virtual double inet::queueing::ITokenStorage::getNumTokens () const pure virtual
Implemented in inet::queueing::MultiTokenBucketMixin< T >, inet::queueing::TokenBucketMixin< T >, inet::queueing::TokenBucket, and inet::queueing::TokenBasedServer.
removeTokenProductionRate()
virtual void inet::queueing::ITokenStorage::removeTokenProductionRate (double tokenRate) pure virtual
Implemented in inet::queueing::MultiTokenBucketMixin< T >, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucketMixin< T >, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::TokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucket, and inet::queueing::TokenBasedServer.
Referenced by inet::queueing::TokenBucket::removeTokenProductionRate(), and inet::queueing::TokenBucket::removeTokens().
removeTokens()
virtual void inet::queueing::ITokenStorage::removeTokens (double numTokens) pure virtual
Implemented in inet::queueing::TokenBasedServer, inet::queueing::MultiTokenBucketMixin< T >, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::queueing::TokenBucketMixin< T >, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::TokenBucketMixin< PacketClassifierBase >, and inet::queueing::TokenBucket.
The documentation for this class was generated from the following file:
ITokenStorage.h