INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2RouterLsa Class Reference
inet::ospfv2::Ospfv2RouterLsa Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:144 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2RouterLsa ()
Ospfv2RouterLsa (const Ospfv2RouterLsa &other)
virtual ~Ospfv2RouterLsa ()
Ospfv2RouterLsa & operator= (const Ospfv2RouterLsa &other)
virtual Ospfv2RouterLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual unsigned short getReserved1 () const
virtual void setReserved1 (unsigned short reserved1)
virtual bool getV_VirtualLinkEndpoint () const
virtual void setV_VirtualLinkEndpoint (bool V_VirtualLinkEndpoint)
virtual bool getE_ASBoundaryRouter () const
virtual void setE_ASBoundaryRouter (bool E_ASBoundaryRouter)
virtual bool getB_AreaBorderRouter () const
virtual void setB_AreaBorderRouter (bool B_AreaBorderRouter)
virtual unsigned short getReserved2 () const
virtual void setReserved2 (unsigned short reserved2)
virtual unsigned short getNumberOfLinks () const
virtual void setNumberOfLinks (unsigned short numberOfLinks)
virtual void setLinksArraySize (size_t size)
virtual size_t getLinksArraySize () const
virtual const Ospfv2Link & getLinks (size_t k) const
virtual Ospfv2Link & getLinksForUpdate (size_t k)
virtual void setLinks (size_t k, const Ospfv2Link &links)
virtual void insertLinks (size_t k, const Ospfv2Link &links)
void insertLinks (const Ospfv2Link &links)
virtual void appendLinks (const Ospfv2Link &links)
virtual void eraseLinks (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv2RouterLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes
unsigned short reserved1 = 0
bool V_VirtualLinkEndpoint = false
bool E_ASBoundaryRouter = false
bool B_AreaBorderRouter = false
unsigned short reserved2 = 0
unsigned short numberOfLinks = 0
Ospfv2Link * links = nullptr
size_t links_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Private Member Functions
void copy (const Ospfv2RouterLsa &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:144 by opp_msgtool.
//
// Represents an OSPF Router LSA (RFC 1583 Section A.4.2.)
//
class Ospfv2RouterLsa extends Ospfv2Lsa
{
    // header.lsType = ROUTERLSA_TYPE;
    unsigned short reserved1 = 0;   // 5 bit
    bool V_VirtualLinkEndpoint = false;
    bool E_ASBoundaryRouter = false;
    bool B_AreaBorderRouter = false;
    unsigned short reserved2 = 0;   // 8 bit
    unsigned short numberOfLinks = 0;
    Ospfv2Link links[];
}
Constructor & Destructor Documentation
Ospfv2RouterLsa() [1/2]
inet::ospfv2::Ospfv2RouterLsa::Ospfv2RouterLsa ()
Ospfv2RouterLsa() [2/2]
inet::ospfv2::Ospfv2RouterLsa::Ospfv2RouterLsa (const Ospfv2RouterLsa & other)
~Ospfv2RouterLsa()
virtual inet::ospfv2::Ospfv2RouterLsa::~Ospfv2RouterLsa () virtual
Member Function Documentation
appendLinks()
virtual void inet::ospfv2::Ospfv2RouterLsa::appendLinks (const Ospfv2Link & links) virtual
copy()
void inet::ospfv2::Ospfv2RouterLsa::copy (const Ospfv2RouterLsa & other) private
dup()
virtual Ospfv2RouterLsa* inet::ospfv2::Ospfv2RouterLsa::dup () const inline override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
 {return new Ospfv2RouterLsa(*this);}
eraseLinks()
virtual void inet::ospfv2::Ospfv2RouterLsa::eraseLinks (size_t k) virtual
getB_AreaBorderRouter()
virtual bool inet::ospfv2::Ospfv2RouterLsa::getB_AreaBorderRouter () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
getE_ASBoundaryRouter()
virtual bool inet::ospfv2::Ospfv2RouterLsa::getE_ASBoundaryRouter () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
getLinks()
virtual const Ospfv2Link& inet::ospfv2::Ospfv2RouterLsa::getLinks (size_t k) const virtual
Referenced by inet::ospfv2::calculateLsaSize(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::Ospfv2Area::printLSDB(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
getLinksArraySize()
virtual size_t inet::ospfv2::Ospfv2RouterLsa::getLinksArraySize () const virtual
Referenced by inet::ospfv2::calculateLsaSize(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2Area::printLSDB().
getLinksForUpdate()
virtual Ospfv2Link& inet::ospfv2::Ospfv2RouterLsa::getLinksForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv2Link&>(const_cast<Ospfv2RouterLsa*>(this)->getLinks(k));}
getNumberOfLinks()
virtual unsigned short inet::ospfv2::Ospfv2RouterLsa::getNumberOfLinks () const virtual
Referenced by inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::operator<<(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
getReserved1()
virtual unsigned short inet::ospfv2::Ospfv2RouterLsa::getReserved1 () const virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
getReserved2()
virtual unsigned short inet::ospfv2::Ospfv2RouterLsa::getReserved2 () const virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
getV_VirtualLinkEndpoint()
virtual bool inet::ospfv2::Ospfv2RouterLsa::getV_VirtualLinkEndpoint () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeRouterLsa().
insertLinks() [1/2]
void inet::ospfv2::Ospfv2RouterLsa::insertLinks (const Ospfv2Link & links) inline
 {appendLinks(links);}
insertLinks() [2/2]
virtual void inet::ospfv2::Ospfv2RouterLsa::insertLinks (size_t k, const Ospfv2Link & links) virtual
operator=()
Ospfv2RouterLsa& inet::ospfv2::Ospfv2RouterLsa::operator= (const Ospfv2RouterLsa & other)
operator==()
bool inet::ospfv2::Ospfv2RouterLsa::operator== (const Ospfv2RouterLsa &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2RouterLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2RouterLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimUnpacking().
setB_AreaBorderRouter()
virtual void inet::ospfv2::Ospfv2RouterLsa::setB_AreaBorderRouter (bool B_AreaBorderRouter) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
setE_ASBoundaryRouter()
virtual void inet::ospfv2::Ospfv2RouterLsa::setE_ASBoundaryRouter (bool E_ASBoundaryRouter) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
setLinks()
virtual void inet::ospfv2::Ospfv2RouterLsa::setLinks (size_t k, const Ospfv2Link & links) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
setLinksArraySize()
virtual void inet::ospfv2::Ospfv2RouterLsa::setLinksArraySize (size_t size) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
setNumberOfLinks()
virtual void inet::ospfv2::Ospfv2RouterLsa::setNumberOfLinks (unsigned short numberOfLinks) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
setReserved1()
virtual void inet::ospfv2::Ospfv2RouterLsa::setReserved1 (unsigned short reserved1) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa().
setReserved2()
virtual void inet::ospfv2::Ospfv2RouterLsa::setReserved2 (unsigned short reserved2) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa().
setV_VirtualLinkEndpoint()
virtual void inet::ospfv2::Ospfv2RouterLsa::setV_VirtualLinkEndpoint (bool V_VirtualLinkEndpoint) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeRouterLsa(), and inet::ospfv2::Ospfv2Area::originateRouterLSA().
Member Data Documentation
B_AreaBorderRouter
bool inet::ospfv2::Ospfv2RouterLsa::B_AreaBorderRouter = false protected
E_ASBoundaryRouter
bool inet::ospfv2::Ospfv2RouterLsa::E_ASBoundaryRouter = false protected
links
Ospfv2Link* inet::ospfv2::Ospfv2RouterLsa::links = nullptr protected
links_arraysize
size_t inet::ospfv2::Ospfv2RouterLsa::links_arraysize = 0 protected
Referenced by inet::ospfv2::RouterLsa::differsFrom().
numberOfLinks
unsigned short inet::ospfv2::Ospfv2RouterLsa::numberOfLinks = 0 protected
reserved1
unsigned short inet::ospfv2::Ospfv2RouterLsa::reserved1 = 0 protected
reserved2
unsigned short inet::ospfv2::Ospfv2RouterLsa::reserved2 = 0 protected
V_VirtualLinkEndpoint
bool inet::ospfv2::Ospfv2RouterLsa::V_VirtualLinkEndpoint = false protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h