INET Framework for OMNeT++/OMNEST: inet::sctp::SctpSuccessIndication Class Reference
inet::sctp::SctpSuccessIndication Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:352 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpSuccessIndication (const char *name=nullptr)
SctpSuccessIndication (const SctpSuccessIndication &other)
virtual ~SctpSuccessIndication ()
SctpSuccessIndication & operator= (const SctpSuccessIndication &other)
virtual SctpSuccessIndication * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getResponseCorrelationId () const
virtual void setResponseCorrelationId (uint32_t responseCorrelationId)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpSuccessIndication &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t responseCorrelationId = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpSuccessIndication &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:352 by opp_msgtool.
class SctpSuccessIndication extends SctpParameter
{
    uint32_t responseCorrelationId;
}
Constructor & Destructor Documentation
SctpSuccessIndication() [1/2]
inet::sctp::SctpSuccessIndication::SctpSuccessIndication (const char * name = nullptr)
SctpSuccessIndication() [2/2]
inet::sctp::SctpSuccessIndication::SctpSuccessIndication (const SctpSuccessIndication & other)
~SctpSuccessIndication()
virtual inet::sctp::SctpSuccessIndication::~SctpSuccessIndication () virtual
Member Function Documentation
copy()
void inet::sctp::SctpSuccessIndication::copy (const SctpSuccessIndication & other) private
dup()
virtual SctpSuccessIndication* inet::sctp::SctpSuccessIndication::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpSuccessIndication(*this);}
getResponseCorrelationId()
virtual uint32_t inet::sctp::SctpSuccessIndication::getResponseCorrelationId () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpSuccessIndication& inet::sctp::SctpSuccessIndication::operator= (const SctpSuccessIndication & other)
operator==()
bool inet::sctp::SctpSuccessIndication::operator== (const SctpSuccessIndication &) protected delete
parsimPack()
virtual void inet::sctp::SctpSuccessIndication::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpSuccessIndication::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setResponseCorrelationId()
virtual void inet::sctp::SctpSuccessIndication::setResponseCorrelationId (uint32_t responseCorrelationId) virtual
Referenced by inet::sctp::SctpAssociation::createSuccessIndication(), and inet::sctp::SctpHeaderSerializer::deserialize().
Member Data Documentation
responseCorrelationId
uint32_t inet::sctp::SctpSuccessIndication::responseCorrelationId = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h