INET Framework for OMNeT++/OMNEST: inet::ErrorRateInd Class Reference
inet::ErrorRateInd Class Reference
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/SignalTag.msg:115 by opp_msgtool.
#include <SignalTag_m.h>
Public Member Functions
ErrorRateInd ()
ErrorRateInd (const ErrorRateInd &other)
virtual ~ErrorRateInd ()
ErrorRateInd & operator= (const ErrorRateInd &other)
virtual ErrorRateInd * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual double getPacketErrorRate () const
virtual void setPacketErrorRate (double packetErrorRate)
virtual double getBitErrorRate () const
virtual void setBitErrorRate (double bitErrorRate)
virtual double getSymbolErrorRate () const
virtual void setSymbolErrorRate (double symbolErrorRate)
Public Member Functions inherited from inet::SignalTagBase
SignalTagBase ()
SignalTagBase (const SignalTagBase &other)
virtual ~SignalTagBase ()
SignalTagBase & operator= (const SignalTagBase &other)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const ErrorRateInd &)=delete
Protected Member Functions inherited from inet::SignalTagBase
bool operator== (const SignalTagBase &)=delete
Protected Attributes
double packetErrorRate = NaN
double bitErrorRate = NaN
double symbolErrorRate = NaN
Private Member Functions
void copy (const ErrorRateInd &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/SignalTag.msg:115 by opp_msgtool.
//
// This indication specifies various error rates that was computed during receiving the packet.
// It may be present on a packet from the phyiscal layer to the application.
//
class ErrorRateInd extends SignalTagBase
{
    double packetErrorRate = NaN; // packet error rate (probability) in the range [0, 1] or NaN if unknown.
    double bitErrorRate = NaN;    // bit error rate (probability) in the range [0, 1] or NaN if unknown.
    double symbolErrorRate = NaN; // symbol error rate (probability) in the range [0, 1] or NaN if unknown.
}
Constructor & Destructor Documentation
ErrorRateInd() [1/2]
inet::ErrorRateInd::ErrorRateInd ()
ErrorRateInd() [2/2]
inet::ErrorRateInd::ErrorRateInd (const ErrorRateInd & other)
~ErrorRateInd()
virtual inet::ErrorRateInd::~ErrorRateInd () virtual
Member Function Documentation
copy()
void inet::ErrorRateInd::copy (const ErrorRateInd & other) private
dup()
virtual ErrorRateInd* inet::ErrorRateInd::dup () const inline override virtual
Reimplemented from inet::SignalTagBase.
 {return new ErrorRateInd(*this);}
getBitErrorRate()
virtual double inet::ErrorRateInd::getBitErrorRate () const virtual
getPacketErrorRate()
virtual double inet::ErrorRateInd::getPacketErrorRate () const virtual
getSymbolErrorRate()
virtual double inet::ErrorRateInd::getSymbolErrorRate () const virtual
operator=()
ErrorRateInd& inet::ErrorRateInd::operator= (const ErrorRateInd & other)
operator==()
bool inet::ErrorRateInd::operator== (const ErrorRateInd &) protected delete
parsimPack()
virtual void inet::ErrorRateInd::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignalTagBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::ErrorRateInd::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignalTagBase.
Referenced by inet::doParsimUnpacking().
setBitErrorRate()
virtual void inet::ErrorRateInd::setBitErrorRate (double bitErrorRate) virtual
setPacketErrorRate()
virtual void inet::ErrorRateInd::setPacketErrorRate (double packetErrorRate) virtual
setSymbolErrorRate()
virtual void inet::ErrorRateInd::setSymbolErrorRate (double symbolErrorRate) virtual
Referenced by inet::physicallayer::ApskLayeredReceiver::computeReceptionResult(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
Member Data Documentation
bitErrorRate
double inet::ErrorRateInd::bitErrorRate = NaN protected
packetErrorRate
double inet::ErrorRateInd::packetErrorRate = NaN protected
symbolErrorRate
double inet::ErrorRateInd::symbolErrorRate = NaN protected
The documentation for this class was generated from the following file:
SignalTag_m.h