INET Framework for OMNeT++/OMNEST: inet::PsbTimeoutMsg Class Reference
inet::PsbTimeoutMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:56 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
PsbTimeoutMsg (const char *name=nullptr, short kind=0)
PsbTimeoutMsg (const PsbTimeoutMsg &other)
virtual ~PsbTimeoutMsg ()
PsbTimeoutMsg & operator= (const PsbTimeoutMsg &other)
virtual PsbTimeoutMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getId () const
virtual void setId (int id)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const PsbTimeoutMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
int id = 0
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const PsbTimeoutMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:56 by opp_msgtool.
//
// FIXME missing documentation
//
message PsbTimeoutMsg extends SignallingMsg
{
    int id;
    command = MSG_PSB_TIMEOUT;
}
Constructor & Destructor Documentation
PsbTimeoutMsg() [1/2]
inet::PsbTimeoutMsg::PsbTimeoutMsg (const char * name = nullptr, short kind = 0)
PsbTimeoutMsg() [2/2]
inet::PsbTimeoutMsg::PsbTimeoutMsg (const PsbTimeoutMsg & other)
~PsbTimeoutMsg()
virtual inet::PsbTimeoutMsg::~PsbTimeoutMsg () virtual
Member Function Documentation
copy()
void inet::PsbTimeoutMsg::copy (const PsbTimeoutMsg & other) private
dup()
virtual PsbTimeoutMsg* inet::PsbTimeoutMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new PsbTimeoutMsg(*this);}
getId()
virtual int inet::PsbTimeoutMsg::getId () const virtual
Referenced by inet::RsvpTe::processPSB_TIMEOUT().
operator=()
PsbTimeoutMsg& inet::PsbTimeoutMsg::operator= (const PsbTimeoutMsg & other)
operator==()
bool inet::PsbTimeoutMsg::operator== (const PsbTimeoutMsg &) protected delete
parsimPack()
virtual void inet::PsbTimeoutMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::PsbTimeoutMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setId()
virtual void inet::PsbTimeoutMsg::setId (int id) virtual
Referenced by inet::RsvpTe::createIngressPSB(), and inet::RsvpTe::createPSB().
Member Data Documentation
id
int inet::PsbTimeoutMsg::id = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h