INET Framework for OMNeT++/OMNEST: inet::power::CcEnergySinkBase Class Reference
inet::power::CcEnergySinkBase Class Reference
#include <CcEnergySinkBase.h>
Public Member Functions
virtual A getTotalCurrentGeneration () const override
Returns the total current generation in the range [0, +infinity).
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Protected Member Functions
virtual A computeTotalCurrentGeneration () const
virtual void updateTotalCurrentGeneration ()
Protected Attributes
A totalCurrentGeneration = A(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Additional Inherited Members
Static Public Attributes inherited from inet::power::ICcEnergySink
static simsignal_t currentGenerationChangedSignal = cComponent::registerSignal("currentGenerationChanged")
The signal that is used to publish current generation changes.
Member Function Documentation
addEnergyGenerator()
void inet::power::CcEnergySinkBase::addEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Adds a new energy generator to the energy sink.
The energyGenerator parameter must not be nullptr.
Reimplemented from inet::power::EnergySinkBase.
Reimplemented in inet::power::CcEnergyStorageBase.
 {
     EnergySinkBase::addEnergyGenerator(energyGenerator);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyGenerator));
     module->subscribe(ICcEnergyGenerator::currentGenerationChangedSignal, this);
     updateTotalCurrentGeneration();
 }
Referenced by inet::power::CcEnergyStorageBase::addEnergyGenerator().
computeTotalCurrentGeneration()
A inet::power::CcEnergySinkBase::computeTotalCurrentGeneration () const protected virtual
 {
     A totalCurrentGeneration = A(0);
     for (auto energyGenerator : energyGenerators)
         totalCurrentGeneration += check_and_cast<const ICcEnergyGenerator *>(energyGenerator)->getCurrentGeneration();
     return totalCurrentGeneration;
 }
Referenced by inet::power::CcEnergyStorageBase::initialize(), and updateTotalCurrentGeneration().
getTotalCurrentGeneration()
virtual A inet::power::CcEnergySinkBase::getTotalCurrentGeneration () const inline override virtual
Returns the total current generation in the range [0, +infinity).
Implements inet::power::ICcEnergySink.
Reimplemented in inet::power::SimpleCcBattery.
 { return totalCurrentGeneration; }
removeEnergyGenerator()
void inet::power::CcEnergySinkBase::removeEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Removes a previously added energy generator from this energy sink.
This functions throws an exception if the generator is not found.
Reimplemented from inet::power::EnergySinkBase.
Reimplemented in inet::power::CcEnergyStorageBase.
 {
     EnergySinkBase::removeEnergyGenerator(energyGenerator);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyGenerator));
     module->unsubscribe(ICcEnergyGenerator::currentGenerationChangedSignal, this);
     updateTotalCurrentGeneration();
 }
Referenced by inet::power::CcEnergyStorageBase::removeEnergyGenerator().
updateTotalCurrentGeneration()
void inet::power::CcEnergySinkBase::updateTotalCurrentGeneration () protected virtual
Reimplemented in inet::power::SimpleCcBattery, and inet::power::CcEnergyStorageBase.
 {
     totalCurrentGeneration = computeTotalCurrentGeneration();
 }
Referenced by addEnergyGenerator(), removeEnergyGenerator(), and inet::power::CcEnergyStorageBase::updateTotalCurrentGeneration().
Member Data Documentation
totalCurrentGeneration
A inet::power::CcEnergySinkBase::totalCurrentGeneration = A(NaN) protected
Referenced by computeTotalCurrentGeneration(), inet::power::CcEnergyStorageBase::initialize(), inet::power::SimpleCcBattery::updateResidualCapacity(), inet::power::CcEnergyStorageBase::updateTotalCurrentGeneration(), and updateTotalCurrentGeneration().
The documentation for this class was generated from the following files:
CcEnergySinkBase.h
CcEnergySinkBase.cc