INET Framework for OMNeT++/OMNEST: inet::DispatchProtocolReq Class Reference
inet::DispatchProtocolReq Class Reference
Class generated from inet/common/ProtocolTag.msg:66 by opp_msgtool.
#include <ProtocolTag_m.h>
Public Member Functions
DispatchProtocolReq ()
DispatchProtocolReq (const DispatchProtocolReq &other)
virtual ~DispatchProtocolReq ()
DispatchProtocolReq & operator= (const DispatchProtocolReq &other)
virtual DispatchProtocolReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual ServicePrimitive getServicePrimitive () const
virtual void setServicePrimitive (ServicePrimitive servicePrimitive)
Public Member Functions inherited from inet::ProtocolTagBase
ProtocolTagBase ()
ProtocolTagBase (const ProtocolTagBase &other)
virtual ~ProtocolTagBase ()
ProtocolTagBase & operator= (const ProtocolTagBase &other)
virtual const Protocol * findProtocol () const
virtual void setProtocol (const Protocol *protocol)
const Protocol * getProtocol () const
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const DispatchProtocolReq &)=delete
Protected Member Functions inherited from inet::ProtocolTagBase
bool operator== (const ProtocolTagBase &)=delete
Protected Attributes
ServicePrimitive servicePrimitive = static_cast<inet::ServicePrimitive>(-1)
Protected Attributes inherited from inet::ProtocolTagBase
const Protocol * protocol = nullptr
Private Member Functions
void copy (const DispatchProtocolReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/common/ProtocolTag.msg:66 by opp_msgtool.
//
// This request determines the destination protocol of the message or packet
// when it's sent from one protocol module to another using the ~MessageDispatcher.
//
class DispatchProtocolReq extends ProtocolTagBase
{
    ServicePrimitive servicePrimitive;
}
Constructor & Destructor Documentation
DispatchProtocolReq() [1/2]
inet::DispatchProtocolReq::DispatchProtocolReq ()
DispatchProtocolReq() [2/2]
inet::DispatchProtocolReq::DispatchProtocolReq (const DispatchProtocolReq & other)
~DispatchProtocolReq()
virtual inet::DispatchProtocolReq::~DispatchProtocolReq () virtual
Member Function Documentation
copy()
void inet::DispatchProtocolReq::copy (const DispatchProtocolReq & other) private
dup()
virtual DispatchProtocolReq* inet::DispatchProtocolReq::dup () const inline override virtual
Reimplemented from inet::ProtocolTagBase.
 {return new DispatchProtocolReq(*this);}
getServicePrimitive()
virtual ServicePrimitive inet::DispatchProtocolReq::getServicePrimitive () const virtual
Referenced by inet::MessageDispatcher::handleMessage().
operator=()
DispatchProtocolReq& inet::DispatchProtocolReq::operator= (const DispatchProtocolReq & other)
operator==()
bool inet::DispatchProtocolReq::operator== (const DispatchProtocolReq &) protected delete
parsimPack()
virtual void inet::DispatchProtocolReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ProtocolTagBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::DispatchProtocolReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ProtocolTagBase.
Referenced by inet::doParsimUnpacking().
setServicePrimitive()
virtual void inet::DispatchProtocolReq::setServicePrimitive (ServicePrimitive servicePrimitive) virtual
Referenced by inet::Icmp::processIcmpMessage(), and inet::Icmpv6::processICMPv6Message().
Member Data Documentation
servicePrimitive
ServicePrimitive inet::DispatchProtocolReq::servicePrimitive = static_cast<inet::ServicePrimitive>(-1) protected
The documentation for this class was generated from the following file:
ProtocolTag_m.h