INET Framework for OMNeT++/OMNEST: inet::sctp::SctpSsnTsnResetRequestParameter Class Reference
inet::sctp::SctpSsnTsnResetRequestParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:266 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpSsnTsnResetRequestParameter (const char *name=nullptr)
SctpSsnTsnResetRequestParameter (const SctpSsnTsnResetRequestParameter &other)
virtual ~SctpSsnTsnResetRequestParameter ()
SctpSsnTsnResetRequestParameter & operator= (const SctpSsnTsnResetRequestParameter &other)
virtual SctpSsnTsnResetRequestParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSrReqSn () const
virtual void setSrReqSn (uint32_t srReqSn)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpSsnTsnResetRequestParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t srReqSn = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpSsnTsnResetRequestParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:266 by opp_msgtool.
class SctpSsnTsnResetRequestParameter extends SctpParameter
{
    uint32_t srReqSn; //Stream Reset Request Sequence Number
}
Constructor & Destructor Documentation
SctpSsnTsnResetRequestParameter() [1/2]
inet::sctp::SctpSsnTsnResetRequestParameter::SctpSsnTsnResetRequestParameter (const char * name = nullptr)
SctpSsnTsnResetRequestParameter() [2/2]
inet::sctp::SctpSsnTsnResetRequestParameter::SctpSsnTsnResetRequestParameter (const SctpSsnTsnResetRequestParameter & other)
~SctpSsnTsnResetRequestParameter()
virtual inet::sctp::SctpSsnTsnResetRequestParameter::~SctpSsnTsnResetRequestParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpSsnTsnResetRequestParameter::copy (const SctpSsnTsnResetRequestParameter & other) private
dup()
virtual SctpSsnTsnResetRequestParameter* inet::sctp::SctpSsnTsnResetRequestParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpSsnTsnResetRequestParameter(*this);}
Referenced by inet::sctp::SctpAssociation::processSsnTsnResetRequestArrived().
getSrReqSn()
virtual uint32_t inet::sctp::SctpSsnTsnResetRequestParameter::getSrReqSn () const virtual
Referenced by inet::sctp::SctpAssociation::processSsnTsnResetRequestArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), inet::sctp::SctpAssociation::sendStreamResetResponse(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpSsnTsnResetRequestParameter& inet::sctp::SctpSsnTsnResetRequestParameter::operator= (const SctpSsnTsnResetRequestParameter & other)
operator==()
bool inet::sctp::SctpSsnTsnResetRequestParameter::operator== (const SctpSsnTsnResetRequestParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpSsnTsnResetRequestParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpSsnTsnResetRequestParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setSrReqSn()
virtual void inet::sctp::SctpSsnTsnResetRequestParameter::setSrReqSn (uint32_t srReqSn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::makeSsnTsnResetParameter().
Member Data Documentation
srReqSn
uint32_t inet::sctp::SctpSsnTsnResetRequestParameter::srReqSn = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h