INET Framework for OMNeT++/OMNEST: inet::LengthBasedFragmenterPolicy Class Reference
inet::LengthBasedFragmenterPolicy Class Reference
#include <LengthBasedFragmenterPolicy.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual std::vector< b > computeFragmentLengths (Packet *packet) const override
Protected Attributes
b minFragmentLength = b(-1)
b maxFragmentLength = b(-1)
b roundingLength = b(-1)
b fragmentHeaderLength = b(-1)
Additional Inherited Members
Member Function Documentation
computeFragmentLengths()
std::vector< b > inet::LengthBasedFragmenterPolicy::computeFragmentLengths (Packet * packet) const override protected virtual
Implements inet::IFragmenterPolicy.
 {
     Enter_Method("computeFragmentLengths");
     std::vector<b> fragmentLengths;
     if (maxFragmentLength >= packet->getTotalLength())
         fragmentLengths.push_back(packet->getTotalLength());
     else {
         b remainingLength = packet->getTotalLength();
         for (int i = 0; fragmentHeaderLength + remainingLength > maxFragmentLength; i++) {
             auto fragmentLength = maxFragmentLength - fragmentHeaderLength;
             fragmentLengths.push_back(fragmentLength);
             remainingLength -= fragmentLength;
         }
         if (remainingLength != b(0))
             fragmentLengths.push_back(remainingLength);
     }
     return fragmentLengths;
 }
initialize()
void inet::LengthBasedFragmenterPolicy::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         minFragmentLength = b(par("minFragmentLength"));
         maxFragmentLength = b(par("maxFragmentLength"));
         roundingLength = b(par("roundingLength"));
         fragmentHeaderLength = b(par("fragmentHeaderLength"));
     }
 }
Member Data Documentation
fragmentHeaderLength
b inet::LengthBasedFragmenterPolicy::fragmentHeaderLength = b(-1) protected
Referenced by computeFragmentLengths(), and initialize().
maxFragmentLength
b inet::LengthBasedFragmenterPolicy::maxFragmentLength = b(-1) protected
Referenced by computeFragmentLengths(), and initialize().
minFragmentLength
b inet::LengthBasedFragmenterPolicy::minFragmentLength = b(-1) protected
Referenced by initialize().
roundingLength
b inet::LengthBasedFragmenterPolicy::roundingLength = b(-1) protected
Referenced by initialize().
The documentation for this class was generated from the following files:
LengthBasedFragmenterPolicy.h
LengthBasedFragmenterPolicy.cc