INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAsconfAckChunk_Base Class Reference
inet::sctp::SctpAsconfAckChunk_Base Class Reference abstract
Class generated from inet/transportlayer/sctp/SctpHeader.msg:311 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
virtual ~SctpAsconfAckChunk_Base ()
virtual SctpAsconfAckChunk_Base * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSerialNumber () const
virtual void setSerialNumber (uint32_t serialNumber)
virtual void setAsconfResponseArraySize (size_t size)=0
virtual size_t getAsconfResponseArraySize () const =0
virtual const SctpParameter * getAsconfResponse (size_t k) const =0
virtual SctpParameter * getAsconfResponseForUpdate (size_t k)
virtual void setAsconfResponse (size_t k, SctpParameter *asconfResponse)=0
virtual void insertAsconfResponse (size_t k, SctpParameter *asconfResponse)=0
void insertAsconfResponse (SctpParameter *asconfResponse)
virtual void appendAsconfResponse (SctpParameter *asconfResponse)=0
virtual void eraseAsconfResponse (size_t k)=0
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpAsconfAckChunk_Base &)=delete
SctpAsconfAckChunk_Base (const char *name=nullptr)
SctpAsconfAckChunk_Base (const SctpAsconfAckChunk_Base &other)
SctpAsconfAckChunk_Base & operator= (const SctpAsconfAckChunk_Base &other)
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint32_t serialNumber = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpAsconfAckChunk_Base &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:311 by opp_msgtool.
class SctpAsconfAckChunk extends SctpChunk
{
    @customize;
    uint32_t serialNumber;
    abstract SctpParameter *asconfResponse[];
}
SctpAsconfAckChunk_Base is only useful if it gets subclassed, and SctpAsconfAckChunk is derived from it. The minimum code to be written for SctpAsconfAckChunk is the following:
class INET_API SctpAsconfAckChunk : public SctpAsconfAckChunk_Base
{
  private:
    void copy(const SctpAsconfAckChunk& other) { ... }
  public:
    SctpAsconfAckChunk(const char *name=nullptr) : SctpAsconfAckChunk_Base(name) {}
    SctpAsconfAckChunk(const SctpAsconfAckChunk& other) : SctpAsconfAckChunk_Base(other) {copy(other);}
    SctpAsconfAckChunk& operator=(const SctpAsconfAckChunk& other) {if (this==&other) return *this; SctpAsconfAckChunk_Base::operator=(other); copy(other); return *this;}
    virtual SctpAsconfAckChunk *dup() const override {return new SctpAsconfAckChunk(*this);}
    // ADD CODE HERE to redefine and implement pure virtual functions from SctpAsconfAckChunk_Base
};
The following should go into a .cc (.cpp) file:
Register_Class(SctpAsconfAckChunk)
Constructor & Destructor Documentation
SctpAsconfAckChunk_Base() [1/2]
inet::sctp::SctpAsconfAckChunk_Base::SctpAsconfAckChunk_Base (const char * name = nullptr) protected
SctpAsconfAckChunk_Base() [2/2]
inet::sctp::SctpAsconfAckChunk_Base::SctpAsconfAckChunk_Base (const SctpAsconfAckChunk_Base & other) protected
~SctpAsconfAckChunk_Base()
virtual inet::sctp::SctpAsconfAckChunk_Base::~SctpAsconfAckChunk_Base () virtual
Member Function Documentation
appendAsconfResponse()
virtual void inet::sctp::SctpAsconfAckChunk_Base::appendAsconfResponse (SctpParameter * asconfResponse) pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
copy()
void inet::sctp::SctpAsconfAckChunk_Base::copy (const SctpAsconfAckChunk_Base & other) private
dup()
virtual SctpAsconfAckChunk_Base* inet::sctp::SctpAsconfAckChunk_Base::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
Reimplemented in inet::sctp::SctpAsconfAckChunk.
 {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class SctpAsconfAckChunk");}
eraseAsconfResponse()
virtual void inet::sctp::SctpAsconfAckChunk_Base::eraseAsconfResponse (size_t k) pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
getAsconfResponse()
virtual const SctpParameter* inet::sctp::SctpAsconfAckChunk_Base::getAsconfResponse (size_t k) const pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
getAsconfResponseArraySize()
virtual size_t inet::sctp::SctpAsconfAckChunk_Base::getAsconfResponseArraySize () const pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
getAsconfResponseForUpdate()
virtual SctpParameter* inet::sctp::SctpAsconfAckChunk_Base::getAsconfResponseForUpdate (size_t k) inline virtual
 { return const_cast<SctpParameter *>(const_cast<SctpAsconfAckChunk_Base*>(this)->getAsconfResponse(k));}
getSerialNumber()
virtual uint32_t inet::sctp::SctpAsconfAckChunk_Base::getSerialNumber () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
insertAsconfResponse() [1/2]
void inet::sctp::SctpAsconfAckChunk_Base::insertAsconfResponse (SctpParameter * asconfResponse) inline
 {appendAsconfResponse(asconfResponse);}
insertAsconfResponse() [2/2]
virtual void inet::sctp::SctpAsconfAckChunk_Base::insertAsconfResponse (size_t k, SctpParameter * asconfResponse) pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
operator=()
SctpAsconfAckChunk_Base& inet::sctp::SctpAsconfAckChunk_Base::operator= (const SctpAsconfAckChunk_Base & other) protected
Referenced by inet::sctp::SctpAsconfAckChunk::operator=().
operator==()
bool inet::sctp::SctpAsconfAckChunk_Base::operator== (const SctpAsconfAckChunk_Base &) protected delete
parsimPack()
virtual void inet::sctp::SctpAsconfAckChunk_Base::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
parsimUnpack()
virtual void inet::sctp::SctpAsconfAckChunk_Base::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
setAsconfResponse()
virtual void inet::sctp::SctpAsconfAckChunk_Base::setAsconfResponse (size_t k, SctpParameter * asconfResponse) pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
setAsconfResponseArraySize()
virtual void inet::sctp::SctpAsconfAckChunk_Base::setAsconfResponseArraySize (size_t size) pure virtual
Implemented in inet::sctp::SctpAsconfAckChunk.
setSerialNumber()
virtual void inet::sctp::SctpAsconfAckChunk_Base::setSerialNumber (uint32_t serialNumber) virtual
Referenced by inet::sctp::SctpAssociation::createAsconfAckChunk(), and inet::sctp::SctpAssociation::sendAsconfAck().
Member Data Documentation
serialNumber
uint32_t inet::sctp::SctpAsconfAckChunk_Base::serialNumber = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h