INET Framework for OMNeT++/OMNEST: inet::visualizer::TracingObstacleLossVisualizerBase Class Reference
inet::visualizer::TracingObstacleLossVisualizerBase Class Reference abstract
#include <TracingObstacleLossVisualizerBase.h>
Classes
class ObstacleLossVisualization
Parameters
bool displayIntersections = false
cFigure::Color intersectionLineColor
cFigure::LineStyle intersectionLineStyle
double intersectionLineWidth = NaN
bool displayFaceNormalVectors = false
cFigure::Color faceNormalLineColor
cFigure::LineStyle faceNormalLineStyle
double faceNormalLineWidth = NaN
const char * fadeOutMode = nullptr
double fadeOutTime = NaN
double fadeOutAnimationSpeed = NaN
std::vector< const ObstacleLossVisualization * > obstacleLossVisualizations
virtual void initialize (int stage) override
virtual void refreshDisplay () const override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual const ObstacleLossVisualization * createObstacleLossVisualization (const physicallayer::ITracingObstacleLoss::ObstaclePenetratedEvent *obstaclePenetratedEvent) const =0
virtual void addObstacleLossVisualization (const ObstacleLossVisualization *obstacleLossVisualization)
virtual void removeObstacleLossVisualization (const ObstacleLossVisualization *obstacleLossVisualization)
virtual void removeAllObstacleLossVisualizations ()
virtual void setAlpha (const ObstacleLossVisualization *obstacleLossVisualization, double alpha) const =0
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addObstacleLossVisualization()
void inet::visualizer::TracingObstacleLossVisualizerBase::addObstacleLossVisualization (const ObstacleLossVisualization * obstacleLossVisualization) protected virtual
Reimplemented in inet::visualizer::TracingObstacleLossCanvasVisualizer, and inet::visualizer::TracingObstacleLossOsgVisualizer.
 {
     obstacleLossVisualizations.push_back(obstacleLossVisualization);
 }
Referenced by inet::visualizer::TracingObstacleLossOsgVisualizer::addObstacleLossVisualization(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::addObstacleLossVisualization().
createObstacleLossVisualization()
virtual const ObstacleLossVisualization* inet::visualizer::TracingObstacleLossVisualizerBase::createObstacleLossVisualization (const physicallayer::ITracingObstacleLoss::ObstaclePenetratedEvent * obstaclePenetratedEvent) const protected pure virtual
Implemented in inet::visualizer::TracingObstacleLossCanvasVisualizer, and inet::visualizer::TracingObstacleLossOsgVisualizer.
initialize()
void inet::visualizer::TracingObstacleLossVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::TracingObstacleLossCanvasVisualizer, and inet::visualizer::TracingObstacleLossOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayIntersections = par("displayIntersections");
         intersectionLineColor = cFigure::parseColor(par("intersectionLineColor"));
         intersectionLineStyle = cFigure::parseLineStyle(par("intersectionLineStyle"));
         intersectionLineWidth = par("intersectionLineWidth");
         displayFaceNormalVectors = par("displayFaceNormalVectors");
         faceNormalLineColor = cFigure::parseColor(par("faceNormalLineColor"));
         faceNormalLineStyle = cFigure::parseLineStyle(par("faceNormalLineStyle"));
         faceNormalLineWidth = par("faceNormalLineWidth");
         fadeOutMode = par("fadeOutMode");
         fadeOutTime = par("fadeOutTime");
         fadeOutAnimationSpeed = par("fadeOutAnimationSpeed");
         if (displayIntersections)
             subscribe();
     }
 }
Referenced by inet::visualizer::TracingObstacleLossOsgVisualizer::initialize(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::TracingObstacleLossVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayIntersections) {
         unsubscribe();
         removeAllObstacleLossVisualizations();
     }
 }
receiveSignal()
void inet::visualizer::TracingObstacleLossVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == ITracingObstacleLoss::obstaclePenetratedSignal) {
         if (displayIntersections || displayFaceNormalVectors) {
             auto event = static_cast<ITracingObstacleLoss::ObstaclePenetratedEvent *>(object);
             auto obstacleLossVisualization = createObstacleLossVisualization(event);
             addObstacleLossVisualization(obstacleLossVisualization);
         }
     }
     else
         throw cRuntimeError("Unknown signal");
 }
refreshDisplay()
void inet::visualizer::TracingObstacleLossVisualizerBase::refreshDisplay () const override protected virtual
Reimplemented in inet::visualizer::TracingObstacleLossCanvasVisualizer, and inet::visualizer::TracingObstacleLossOsgVisualizer.
 {
     AnimationPosition currentAnimationPosition;
     std::vector<const ObstacleLossVisualization *> removedObstacleLossVisualizations;
     for (auto obstacleLossVisualization : obstacleLossVisualizations) {
         double delta;
         if (!strcmp(fadeOutMode, "simulationTime"))
             delta = (currentAnimationPosition.getSimulationTime() - obstacleLossVisualization->obstacleLossAnimationPosition.getSimulationTime()).dbl();
         else if (!strcmp(fadeOutMode, "animationTime"))
             delta = currentAnimationPosition.getAnimationTime() - obstacleLossVisualization->obstacleLossAnimationPosition.getAnimationTime();
         else if (!strcmp(fadeOutMode, "realTime"))
             delta = currentAnimationPosition.getRealTime() - obstacleLossVisualization->obstacleLossAnimationPosition.getRealTime();
         else
             throw cRuntimeError("Unknown fadeOutMode: %s", fadeOutMode);
         if (delta > fadeOutTime)
             removedObstacleLossVisualizations.push_back(obstacleLossVisualization);
         else
             setAlpha(obstacleLossVisualization, 1 - delta / fadeOutTime);
     }
     for (auto obstacleLossVisualization : removedObstacleLossVisualizations) {
         const_cast<TracingObstacleLossVisualizerBase *>(this)->removeObstacleLossVisualization(obstacleLossVisualization);
         delete obstacleLossVisualization;
     }
 }
Referenced by inet::visualizer::TracingObstacleLossOsgVisualizer::refreshDisplay(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::refreshDisplay().
removeAllObstacleLossVisualizations()
void inet::visualizer::TracingObstacleLossVisualizerBase::removeAllObstacleLossVisualizations () protected virtual
 {
     std::vector<const ObstacleLossVisualization *> removedObstacleLossVisualizations;
     for (auto it : obstacleLossVisualizations)
         removedObstacleLossVisualizations.push_back(it);
     for (auto it : removedObstacleLossVisualizations) {
         removeObstacleLossVisualization(it);
         delete it;
     }
 }
removeObstacleLossVisualization()
void inet::visualizer::TracingObstacleLossVisualizerBase::removeObstacleLossVisualization (const ObstacleLossVisualization * obstacleLossVisualization) protected virtual
Reimplemented in inet::visualizer::TracingObstacleLossCanvasVisualizer, and inet::visualizer::TracingObstacleLossOsgVisualizer.
 {
     obstacleLossVisualizations.erase(std::remove(obstacleLossVisualizations.begin(), obstacleLossVisualizations.end(), obstacleLossVisualization), obstacleLossVisualizations.end());
 }
Referenced by inet::visualizer::TracingObstacleLossOsgVisualizer::removeObstacleLossVisualization(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::removeObstacleLossVisualization().
setAlpha()
virtual void inet::visualizer::TracingObstacleLossVisualizerBase::setAlpha (const ObstacleLossVisualization * obstacleLossVisualization, double alpha) const protected pure virtual
Implemented in inet::visualizer::TracingObstacleLossCanvasVisualizer, and inet::visualizer::TracingObstacleLossOsgVisualizer.
subscribe()
void inet::visualizer::TracingObstacleLossVisualizerBase::subscribe () protected virtual
 {
     visualizationSubjectModule->subscribe(ITracingObstacleLoss::obstaclePenetratedSignal, this);
 }
unsubscribe()
void inet::visualizer::TracingObstacleLossVisualizerBase::unsubscribe () protected virtual
 {
     // NOTE: lookup the module again because it may have been deleted first
     auto visualizationSubjectModule = findModuleFromPar<cModule>(par("visualizationSubjectModule"), this);
     if (visualizationSubjectModule != nullptr)
         visualizationSubjectModule->unsubscribe(ITracingObstacleLoss::obstaclePenetratedSignal, this);
 }
Member Data Documentation
displayFaceNormalVectors
bool inet::visualizer::TracingObstacleLossVisualizerBase::displayFaceNormalVectors = false protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::addObstacleLossVisualization(), inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization(), inet::visualizer::TracingObstacleLossCanvasVisualizer::removeObstacleLossVisualization(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::setAlpha().
displayIntersections
bool inet::visualizer::TracingObstacleLossVisualizerBase::displayIntersections = false protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::addObstacleLossVisualization(), inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization(), inet::visualizer::TracingObstacleLossCanvasVisualizer::removeObstacleLossVisualization(), and inet::visualizer::TracingObstacleLossCanvasVisualizer::setAlpha().
faceNormalLineColor
cFigure::Color inet::visualizer::TracingObstacleLossVisualizerBase::faceNormalLineColor protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
faceNormalLineStyle
cFigure::LineStyle inet::visualizer::TracingObstacleLossVisualizerBase::faceNormalLineStyle protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
faceNormalLineWidth
double inet::visualizer::TracingObstacleLossVisualizerBase::faceNormalLineWidth = NaN protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
fadeOutAnimationSpeed
double inet::visualizer::TracingObstacleLossVisualizerBase::fadeOutAnimationSpeed = NaN protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::refreshDisplay().
fadeOutMode
const char* inet::visualizer::TracingObstacleLossVisualizerBase::fadeOutMode = nullptr protected
fadeOutTime
double inet::visualizer::TracingObstacleLossVisualizerBase::fadeOutTime = NaN protected
intersectionLineColor
cFigure::Color inet::visualizer::TracingObstacleLossVisualizerBase::intersectionLineColor protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
intersectionLineStyle
cFigure::LineStyle inet::visualizer::TracingObstacleLossVisualizerBase::intersectionLineStyle protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
intersectionLineWidth
double inet::visualizer::TracingObstacleLossVisualizerBase::intersectionLineWidth = NaN protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::createObstacleLossVisualization().
obstacleLossVisualizations
std::vector<const ObstacleLossVisualization *> inet::visualizer::TracingObstacleLossVisualizerBase::obstacleLossVisualizations protected
Referenced by inet::visualizer::TracingObstacleLossCanvasVisualizer::refreshDisplay().
The documentation for this class was generated from the following files:
TracingObstacleLossVisualizerBase.h
TracingObstacleLossVisualizerBase.cc