INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211TransmissionBase Class Reference
inet::physicallayer::Ieee80211TransmissionBase Class Reference
#include <Ieee80211TransmissionBase.h>
Public Member Functions
Ieee80211TransmissionBase (const IIeee80211Mode *mode, const Ieee80211Channel *channel)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IIeee80211Mode * getMode () const
virtual const Ieee80211Channel * getChannel () const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const IIeee80211Mode * mode
const Ieee80211Channel * channel
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211TransmissionBase()
inet::physicallayer::Ieee80211TransmissionBase::Ieee80211TransmissionBase (const IIeee80211Mode * mode, const Ieee80211Channel * channel)
                                                                                                                 :
     mode(mode),
     channel(channel)
 {
 }
Member Function Documentation
getChannel()
virtual const Ieee80211Channel* inet::physicallayer::Ieee80211TransmissionBase::getChannel () const inline virtual
 { return channel; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
getMode()
virtual const IIeee80211Mode* inet::physicallayer::Ieee80211TransmissionBase::getMode () const inline virtual
 { return mode; }
Referenced by inet::physicallayer::Ieee80211DimensionalReceiver::computeIsReceptionPossible(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
printToStream()
std::ostream & inet::physicallayer::Ieee80211TransmissionBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::Ieee80211UnitDiskTransmission, inet::physicallayer::Ieee80211LayeredTransmission, inet::physicallayer::Ieee80211DimensionalTransmission, and inet::physicallayer::Ieee80211ScalarTransmission.
 {
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(mode, printFieldToString(mode, level + 1, evFlags))
                << EV_FIELD(channel, printFieldToString(channel, level + 1, evFlags));
     return stream;
 }
Referenced by inet::physicallayer::Ieee80211DimensionalTransmission::printToStream(), inet::physicallayer::Ieee80211LayeredTransmission::printToStream(), inet::physicallayer::Ieee80211ScalarTransmission::printToStream(), and inet::physicallayer::Ieee80211UnitDiskTransmission::printToStream().
Member Data Documentation
channel
const Ieee80211Channel* inet::physicallayer::Ieee80211TransmissionBase::channel protected
Referenced by printToStream().
mode
const IIeee80211Mode* inet::physicallayer::Ieee80211TransmissionBase::mode protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
Ieee80211TransmissionBase.h
Ieee80211TransmissionBase.cc