INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211ChannelTagBase Class Reference
inet::physicallayer::Ieee80211ChannelTagBase Class Reference
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:42 by opp_msgtool.
#include <Ieee80211Tag_m.h>
Public Member Functions
Ieee80211ChannelTagBase ()
Ieee80211ChannelTagBase (const Ieee80211ChannelTagBase &other)
virtual ~Ieee80211ChannelTagBase ()
Ieee80211ChannelTagBase & operator= (const Ieee80211ChannelTagBase &other)
virtual Ieee80211ChannelTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ieee80211Channel * getChannel () const
virtual void setChannel (const Ieee80211Channel *channel)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ieee80211ChannelTagBase &)=delete
Protected Attributes
const Ieee80211Channel * channel = nullptr
Private Member Functions
void copy (const Ieee80211ChannelTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:42 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class Ieee80211ChannelTagBase extends TagBase
{
    const Ieee80211Channel *channel; // IEEE 802.11 band and channel
}
Constructor & Destructor Documentation
Ieee80211ChannelTagBase() [1/2]
inet::physicallayer::Ieee80211ChannelTagBase::Ieee80211ChannelTagBase ()
Ieee80211ChannelTagBase() [2/2]
inet::physicallayer::Ieee80211ChannelTagBase::Ieee80211ChannelTagBase (const Ieee80211ChannelTagBase & other)
~Ieee80211ChannelTagBase()
virtual inet::physicallayer::Ieee80211ChannelTagBase::~Ieee80211ChannelTagBase () virtual
Member Function Documentation
copy()
void inet::physicallayer::Ieee80211ChannelTagBase::copy (const Ieee80211ChannelTagBase & other) private
dup()
virtual Ieee80211ChannelTagBase* inet::physicallayer::Ieee80211ChannelTagBase::dup () const inline override virtual
Reimplemented in inet::physicallayer::Ieee80211ChannelInd, and inet::physicallayer::Ieee80211ChannelReq.
 {return new Ieee80211ChannelTagBase(*this);}
getChannel()
virtual const Ieee80211Channel* inet::physicallayer::Ieee80211ChannelTagBase::getChannel () const virtual
operator=()
Ieee80211ChannelTagBase& inet::physicallayer::Ieee80211ChannelTagBase::operator= (const Ieee80211ChannelTagBase & other)
operator==()
bool inet::physicallayer::Ieee80211ChannelTagBase::operator== (const Ieee80211ChannelTagBase &) protected delete
parsimPack()
virtual void inet::physicallayer::Ieee80211ChannelTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::physicallayer::Ieee80211ChannelInd, and inet::physicallayer::Ieee80211ChannelReq.
Referenced by inet::physicallayer::doParsimPacking().
parsimUnpack()
virtual void inet::physicallayer::Ieee80211ChannelTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::physicallayer::Ieee80211ChannelInd, and inet::physicallayer::Ieee80211ChannelReq.
Referenced by inet::physicallayer::doParsimUnpacking().
setChannel()
virtual void inet::physicallayer::Ieee80211ChannelTagBase::setChannel (const Ieee80211Channel * channel) virtual
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult().
Member Data Documentation
channel
const Ieee80211Channel* inet::physicallayer::Ieee80211ChannelTagBase::channel = nullptr protected
The documentation for this class was generated from the following file:
Ieee80211Tag_m.h