INET Framework for OMNeT++/OMNEST: inet::Ipv4NodeConfigurator Class Reference
inet::Ipv4NodeConfigurator Class Reference
This module provides the static configuration for the Ipv4RoutingTable and the Ipv4 network interfaces of a particular node in the network.
#include <Ipv4NodeConfigurator.h>
Public Member Functions
Ipv4NodeConfigurator ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Protected Member Functions
virtual int numInitStages () const override
virtual void handleMessage (cMessage *msg) override
virtual void initialize (int stage) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void prepareAllInterfaces ()
virtual void prepareInterface (NetworkInterface *networkInterface)
virtual void configureAllInterfaces ()
virtual void configureRoutingTable ()
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Called by the signal handler whenever a change of a category occurs to which this client has subscribed.
Protected Attributes
opp_component_ptr< NodeStatus > nodeStatus
ModuleRefByPar< IInterfaceTable > interfaceTable
ModuleRefByPar< IIpv4RoutingTable > routingTable
ModuleRefByPar< Ipv4NetworkConfigurator > networkConfigurator
Detailed Description
This module provides the static configuration for the Ipv4RoutingTable and the Ipv4 network interfaces of a particular node in the network.
For more info please see the NED file.
Constructor & Destructor Documentation
Ipv4NodeConfigurator()
inet::Ipv4NodeConfigurator::Ipv4NodeConfigurator ()
 {
 }
Member Function Documentation
configureAllInterfaces()
void inet::Ipv4NodeConfigurator::configureAllInterfaces () protected virtual
 {
     ASSERT(networkConfigurator);
     for (int i = 0; i < interfaceTable->getNumInterfaces(); i++)
         networkConfigurator->configureInterface(interfaceTable->getInterface(i));
 }
Referenced by handleOperationStage(), and initialize().
configureRoutingTable()
void inet::Ipv4NodeConfigurator::configureRoutingTable () protected virtual
 {
     ASSERT(networkConfigurator);
     if (par("configureRoutingTable"))
         networkConfigurator->configureRoutingTable(routingTable);
 }
Referenced by handleOperationStage(), and initialize().
handleMessage()
virtual void inet::Ipv4NodeConfigurator::handleMessage (cMessage * msg) inline override protected virtual
 { throw cRuntimeError("this module doesn't handle messages, it runs only in initialize()"); }
handleOperationStage()
bool inet::Ipv4NodeConfigurator::handleOperationStage (LifecycleOperation * operation, IDoneCallback * doneCallback) override protected virtual
Perform one stage of a lifecycle operation.
Processing may be done entirely within this method, or may be a longer process that involves nonzero simulation time or several events, and is triggered by this method call.
Return value: true = "done"; false = "not yet done, will invoke doneCallback when done"
Implements inet::ILifecycle.
 {
     Enter_Method("handleOperationStage");
     int stage = operation->getCurrentStage();
     if (dynamic_cast<ModuleStartOperation *>(operation)) {
         if (static_cast<ModuleStartOperation::Stage>(stage) == ModuleStartOperation::STAGE_LINK_LAYER)
             prepareAllInterfaces();
         else if (static_cast<ModuleStartOperation::Stage>(stage) == ModuleStartOperation::STAGE_NETWORK_LAYER) {
             if (networkConfigurator != nullptr) {
                 configureAllInterfaces();
                 configureRoutingTable();
             }
             cModule *node = getContainingNode(this);
             node->subscribe(interfaceCreatedSignal, this);
             node->subscribe(interfaceDeletedSignal, this);
             node->subscribe(interfaceStateChangedSignal, this);
         }
     }
     else if (dynamic_cast<ModuleStopOperation *>(operation)) {
         if (static_cast<ModuleStopOperation::Stage>(stage) == ModuleStopOperation::STAGE_LOCAL) {
             cModule *node = getContainingNode(this);
             node->unsubscribe(interfaceCreatedSignal, this);
             node->unsubscribe(interfaceDeletedSignal, this);
             node->unsubscribe(interfaceStateChangedSignal, this);
         }
     }
     else if (dynamic_cast<ModuleCrashOperation *>(operation)) {
         cModule *node = getContainingNode(this);
         node->unsubscribe(interfaceCreatedSignal, this);
         node->unsubscribe(interfaceDeletedSignal, this);
         node->unsubscribe(interfaceStateChangedSignal, this);
     }
     else
         throw cRuntimeError("Unsupported lifecycle operation '%s'", operation->getClassName());
     return true;
 }
initialize()
void inet::Ipv4NodeConfigurator::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         cModule *node = getContainingNode(this);
         const char *networkConfiguratorPath = par("networkConfiguratorModule");
         nodeStatus = dynamic_cast<NodeStatus *>(node->getSubmodule("status"));
         interfaceTable.reference(this, "interfaceTableModule", true);
         routingTable.reference(this, "routingTableModule", true);
         if (networkConfiguratorPath[0])
             networkConfigurator.reference(this, "networkConfiguratorModule", false);
     }
     else if (stage == INITSTAGE_NETWORK_CONFIGURATION) {
         if (!nodeStatus || nodeStatus->getState() == NodeStatus::UP)
             prepareAllInterfaces();
     }
     else if (stage == INITSTAGE_NETWORK_ADDRESS_ASSIGNMENT) {
         if ((!nodeStatus || nodeStatus->getState() == NodeStatus::UP) && networkConfigurator)
             configureAllInterfaces();
     }
     else if (stage == INITSTAGE_STATIC_ROUTING) {
         if ((!nodeStatus || nodeStatus->getState() == NodeStatus::UP) && networkConfigurator) {
             configureRoutingTable();
             cModule *node = getContainingNode(this);
             // get a pointer to the host module and IInterfaceTable
             node->subscribe(interfaceCreatedSignal, this);
             node->subscribe(interfaceDeletedSignal, this);
             node->subscribe(interfaceStateChangedSignal, this);
         }
     }
 }
numInitStages()
virtual int inet::Ipv4NodeConfigurator::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
prepareAllInterfaces()
void inet::Ipv4NodeConfigurator::prepareAllInterfaces () protected virtual
 {
     for (int i = 0; i < interfaceTable->getNumInterfaces(); i++)
         prepareInterface(interfaceTable->getInterface(i));
 }
Referenced by handleOperationStage(), and initialize().
prepareInterface()
void inet::Ipv4NodeConfigurator::prepareInterface (NetworkInterface * networkInterface) protected virtual
 {
 //    ASSERT(!networkInterface->getProtocolData<Ipv4InterfaceData>());
     auto interfaceData = networkInterface->addProtocolData<Ipv4InterfaceData>();
     if (networkInterface->isLoopback()) {
         // we may reconfigure later it to be the routerId
         interfaceData->setIPAddress(Ipv4Address::LOOPBACK_ADDRESS);
         interfaceData->setNetmask(Ipv4Address::LOOPBACK_NETMASK);
         interfaceData->setMetric(1);
     }
     else {
         auto datarate = networkInterface->getDatarate();
         // KLUDGE how do we set the metric correctly for both wired and wireless interfaces even if datarate is unknown
         if (datarate == 0)
             interfaceData->setMetric(1);
         else
             // metric: some hints: OSPF cost (2e9/bps value), MS KB article Q299540, ...
             interfaceData->setMetric((int)ceil(2e9 / datarate)); // use OSPF cost as default
         if (networkInterface->isMulticast()) {
             interfaceData->joinMulticastGroup(Ipv4Address::ALL_HOSTS_MCAST);
             if (routingTable->isForwardingEnabled())
                 interfaceData->joinMulticastGroup(Ipv4Address::ALL_ROUTERS_MCAST);
         }
     }
 }
Referenced by prepareAllInterfaces(), and receiveSignal().
receiveSignal()
void inet::Ipv4NodeConfigurator::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
Called by the signal handler whenever a change of a category occurs to which this client has subscribed.
 {
     if (getSimulation()->getContextType() == CTX_INITIALIZE)
         return; // ignore notifications during initialize
     Enter_Method("%s", cComponent::getSignalName(signalID));
     printSignalBanner(signalID, obj, details);
     if (signalID == interfaceCreatedSignal) {
         auto *entry = check_and_cast<NetworkInterface *>(obj);
         prepareInterface(entry);
         // TODO
     }
     else if (signalID == interfaceDeletedSignal) {
         // The RoutingTable deletes routing entries of interface
     }
     else if (signalID == interfaceStateChangedSignal) {
         const auto *ieChangeDetails = check_and_cast<const NetworkInterfaceChangeDetails *>(obj);
         auto fieldId = ieChangeDetails->getFieldId();
         if (fieldId == NetworkInterface::F_STATE || fieldId == NetworkInterface::F_CARRIER) {
             auto *entry = ieChangeDetails->getNetworkInterface();
             if (entry->isUp() && networkConfigurator) {
                 networkConfigurator->configureInterface(entry);
                 if (par("configureRoutingTable"))
                     networkConfigurator->configureRoutingTable(routingTable, entry);
             }
             // otherwise the RoutingTable deletes routing entries of interface entry
         }
     }
 }
Member Data Documentation
interfaceTable
ModuleRefByPar<IInterfaceTable> inet::Ipv4NodeConfigurator::interfaceTable protected
Referenced by configureAllInterfaces(), initialize(), and prepareAllInterfaces().
networkConfigurator
ModuleRefByPar<Ipv4NetworkConfigurator> inet::Ipv4NodeConfigurator::networkConfigurator protected
Referenced by configureAllInterfaces(), configureRoutingTable(), handleOperationStage(), initialize(), and receiveSignal().
nodeStatus
opp_component_ptr<NodeStatus> inet::Ipv4NodeConfigurator::nodeStatus protected
Referenced by initialize().
routingTable
ModuleRefByPar<IIpv4RoutingTable> inet::Ipv4NodeConfigurator::routingTable protected
Referenced by configureRoutingTable(), initialize(), prepareInterface(), and receiveSignal().
The documentation for this class was generated from the following files:
Ipv4NodeConfigurator.h
Ipv4NodeConfigurator.cc