INET Framework for OMNeT++/OMNEST: inet::IVisitor Class Reference
inet::IVisitor Class Reference abstract
#include <IVisitor.h>
Public Member Functions
virtual void visit (const cObject *) const =0
virtual ~IVisitor ()
Constructor & Destructor Documentation
~IVisitor()
virtual inet::IVisitor::~IVisitor () inline virtual
 {}
Member Function Documentation
visit()
virtual void inet::IVisitor::visit (const cObject *) const pure virtual
Implemented in inet::physicallayer::GridNeighborCache::GridNeighborCacheVisitor, inet::physicallayer::QuadTreeNeighborCache::QuadTreeNeighborCacheVisitor, inet::physicallayer::DielectricObstacleLoss::TotalObstacleLossComputation, inet::physicallayer::IdealObstacleLoss::TotalObstacleLossComputation, and inet::BvhTree::BvhTreeVisitor.
Referenced by inet::BvhTree::lineSegmentQuery(), inet::SpatialGrid::lineSegmentQuery(), inet::QuadTree::rangeQuery(), inet::SpatialGrid::rangeQuery(), inet::QuadTree::strictRangeQuery(), and inet::physicalenvironment::PhysicalEnvironment::visitObjects().
The documentation for this class was generated from the following file:
IVisitor.h