INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2NetworkLsa Class Reference
inet::ospfv2::Ospfv2NetworkLsa Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:159 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2NetworkLsa ()
Ospfv2NetworkLsa (const Ospfv2NetworkLsa &other)
virtual ~Ospfv2NetworkLsa ()
Ospfv2NetworkLsa & operator= (const Ospfv2NetworkLsa &other)
virtual Ospfv2NetworkLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getNetworkMask () const
virtual ::inet::Ipv4Address & getNetworkMaskForUpdate ()
virtual void setNetworkMask (const ::inet::Ipv4Address &networkMask)
virtual void setAttachedRoutersArraySize (size_t size)
virtual size_t getAttachedRoutersArraySize () const
virtual const ::inet::Ipv4Address & getAttachedRouters (size_t k) const
virtual ::inet::Ipv4Address & getAttachedRoutersForUpdate (size_t k)
virtual void setAttachedRouters (size_t k, const ::inet::Ipv4Address &attachedRouters)
virtual void insertAttachedRouters (size_t k, const ::inet::Ipv4Address &attachedRouters)
void insertAttachedRouters (const ::inet::Ipv4Address &attachedRouters)
virtual void appendAttachedRouters (const ::inet::Ipv4Address &attachedRouters)
virtual void eraseAttachedRouters (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv2NetworkLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes
::inet::Ipv4Address networkMask
::inet::Ipv4Address * attachedRouters = nullptr
size_t attachedRouters_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Private Member Functions
void copy (const Ospfv2NetworkLsa &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:159 by opp_msgtool.
//
// Represents an OSPF Network LSA
//
class Ospfv2NetworkLsa extends Ospfv2Lsa
{
    // header.lsType = NETWORKLSA_TYPE;
    Ipv4Address networkMask;
    Ipv4Address attachedRouters[];
}
Constructor & Destructor Documentation
Ospfv2NetworkLsa() [1/2]
inet::ospfv2::Ospfv2NetworkLsa::Ospfv2NetworkLsa ()
Ospfv2NetworkLsa() [2/2]
inet::ospfv2::Ospfv2NetworkLsa::Ospfv2NetworkLsa (const Ospfv2NetworkLsa & other)
~Ospfv2NetworkLsa()
virtual inet::ospfv2::Ospfv2NetworkLsa::~Ospfv2NetworkLsa () virtual
Member Function Documentation
appendAttachedRouters()
virtual void inet::ospfv2::Ospfv2NetworkLsa::appendAttachedRouters (const ::inet::Ipv4Address & attachedRouters) virtual
copy()
void inet::ospfv2::Ospfv2NetworkLsa::copy (const Ospfv2NetworkLsa & other) private
dup()
virtual Ospfv2NetworkLsa* inet::ospfv2::Ospfv2NetworkLsa::dup () const inline override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
 {return new Ospfv2NetworkLsa(*this);}
eraseAttachedRouters()
virtual void inet::ospfv2::Ospfv2NetworkLsa::eraseAttachedRouters (size_t k) virtual
getAttachedRouters()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2NetworkLsa::getAttachedRouters (size_t k) const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::Ospfv2Area::printLSDB(), and inet::ospfv2::Ospfv2PacketSerializer::serializeNetworkLsa().
getAttachedRoutersArraySize()
virtual size_t inet::ospfv2::Ospfv2NetworkLsa::getAttachedRoutersArraySize () const virtual
Referenced by inet::ospfv2::calculateLsaSize(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::Ospfv2Area::printLSDB(), and inet::ospfv2::Ospfv2PacketSerializer::serializeNetworkLsa().
getAttachedRoutersForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2NetworkLsa::getAttachedRoutersForUpdate (size_t k) inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2NetworkLsa*>(this)->getAttachedRouters(k));}
getNetworkMask()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2NetworkLsa::getNetworkMask () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2PacketSerializer::serializeNetworkLsa().
getNetworkMaskForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2NetworkLsa::getNetworkMaskForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2NetworkLsa*>(this)->getNetworkMask());}
insertAttachedRouters() [1/2]
void inet::ospfv2::Ospfv2NetworkLsa::insertAttachedRouters (const ::inet::Ipv4Address & attachedRouters) inline
 {appendAttachedRouters(attachedRouters);}
insertAttachedRouters() [2/2]
virtual void inet::ospfv2::Ospfv2NetworkLsa::insertAttachedRouters (size_t k, const ::inet::Ipv4Address & attachedRouters) virtual
operator=()
Ospfv2NetworkLsa& inet::ospfv2::Ospfv2NetworkLsa::operator= (const Ospfv2NetworkLsa & other)
operator==()
bool inet::ospfv2::Ospfv2NetworkLsa::operator== (const Ospfv2NetworkLsa &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2NetworkLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2NetworkLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv2::Ospfv2Lsa.
Referenced by inet::ospfv2::doParsimUnpacking().
setAttachedRouters()
virtual void inet::ospfv2::Ospfv2NetworkLsa::setAttachedRouters (size_t k, const ::inet::Ipv4Address & attachedRouters) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), and inet::ospfv2::Ospfv2Area::originateNetworkLSA().
setAttachedRoutersArraySize()
virtual void inet::ospfv2::Ospfv2NetworkLsa::setAttachedRoutersArraySize (size_t size) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), and inet::ospfv2::Ospfv2Area::originateNetworkLSA().
setNetworkMask()
virtual void inet::ospfv2::Ospfv2NetworkLsa::setNetworkMask (const ::inet::Ipv4Address & networkMask) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), and inet::ospfv2::Ospfv2Area::originateNetworkLSA().
Member Data Documentation
attachedRouters
::inet::Ipv4Address* inet::ospfv2::Ospfv2NetworkLsa::attachedRouters = nullptr protected
attachedRouters_arraysize
size_t inet::ospfv2::Ospfv2NetworkLsa::attachedRouters_arraysize = 0 protected
Referenced by inet::ospfv2::NetworkLsa::differsFrom().
networkMask
::inet::Ipv4Address inet::ospfv2::Ospfv2NetworkLsa::networkMask protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h