INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmModeBase Class Reference
inet::physicallayer::Ieee80211OfdmModeBase Class Reference
#include <Ieee80211OfdmMode.h>
Public Member Functions
Ieee80211OfdmModeBase (const Ieee80211OfdmModulation *modulation, const Ieee80211OfdmCode *code, Hz channelSpacing, Hz bandwidth)
virtual ~Ieee80211OfdmModeBase ()
int getNumberOfDataSubcarriers () const
int getNumberOfPilotSubcarriers () const
int getNumberOfTotalSubcarriers () const
virtual bps getGrossBitrate () const
virtual bps getNetBitrate () const
virtual Hz getBandwidth () const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing)
Hz getSubcarrierFrequencySpacing () const
const simtime_t getFFTTransformPeriod () const
const simtime_t getGIDuration () const
const simtime_t getSymbolInterval () const
const Hz getChannelSpacing () const
Protected Member Functions
bps computeGrossBitrate (const Ieee80211OfdmModulation *modulation) const
bps computeNetBitrate (bps grossBitrate, const Ieee80211OfdmCode *code) const
Protected Attributes
const Ieee80211OfdmModulation * modulation
const Ieee80211OfdmCode * code
const Hz bandwidth
bps netBitrate
bps grossBitrate
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Hz channelSpacing
Constructor & Destructor Documentation
Ieee80211OfdmModeBase()
inet::physicallayer::Ieee80211OfdmModeBase::Ieee80211OfdmModeBase (const Ieee80211OfdmModulation * modulation, const Ieee80211OfdmCode * code, Hz channelSpacing, Hz bandwidth)
                                                                                                                                                       :
     Ieee80211OfdmTimingRelatedParametersBase(channelSpacing),
     modulation(modulation),
     code(code),
     bandwidth(bandwidth),
     netBitrate(bps(NaN)),
     grossBitrate(bps(NaN))
 {
 }
~Ieee80211OfdmModeBase()
virtual inet::physicallayer::Ieee80211OfdmModeBase::~Ieee80211OfdmModeBase () inline virtual
 {}
Member Function Documentation
computeGrossBitrate()
bps inet::physicallayer::Ieee80211OfdmModeBase::computeGrossBitrate (const Ieee80211OfdmModulation * modulation) const protected
 {
     int codedBitsPerOFDMSymbol = modulation->getSubcarrierModulation()->getCodeWordSize() * getNumberOfDataSubcarriers();
     return bps(codedBitsPerOFDMSymbol / getSymbolInterval());
 }
Referenced by getGrossBitrate().
computeNetBitrate()
bps inet::physicallayer::Ieee80211OfdmModeBase::computeNetBitrate (bps grossBitrate, const Ieee80211OfdmCode * code) const protected
 {
     const ConvolutionalCode *convolutionalCode = code ? code->getConvolutionalCode() : nullptr;
     if (convolutionalCode)
         return grossBitrate * convolutionalCode->getCodeRatePuncturingK() / convolutionalCode->getCodeRatePuncturingN();
     return grossBitrate;
 }
Referenced by getNetBitrate().
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211OfdmModeBase::getBandwidth () const inline virtual
Reimplemented in inet::physicallayer::Ieee80211OfdmDataMode.
 { return bandwidth; }
getGrossBitrate()
bps inet::physicallayer::Ieee80211OfdmModeBase::getGrossBitrate () const virtual
Reimplemented in inet::physicallayer::Ieee80211OfdmDataMode, and inet::physicallayer::Ieee80211OfdmSignalMode.
 {
     if (std::isnan(grossBitrate.get()))
         grossBitrate = computeGrossBitrate(modulation);
     return grossBitrate;
 }
Referenced by inet::physicallayer::Ieee80211OfdmSignalMode::getGrossBitrate(), inet::physicallayer::Ieee80211OfdmDataMode::getGrossBitrate(), and getNetBitrate().
getNetBitrate()
bps inet::physicallayer::Ieee80211OfdmModeBase::getNetBitrate () const virtual
Reimplemented in inet::physicallayer::Ieee80211OfdmDataMode, and inet::physicallayer::Ieee80211OfdmSignalMode.
 {
     if (std::isnan(netBitrate.get()))
         netBitrate = computeNetBitrate(getGrossBitrate(), code);
     return netBitrate;
 }
Referenced by inet::physicallayer::Ieee80211OfdmSignalMode::getNetBitrate(), and inet::physicallayer::Ieee80211OfdmDataMode::getNetBitrate().
getNumberOfDataSubcarriers()
int inet::physicallayer::Ieee80211OfdmModeBase::getNumberOfDataSubcarriers () const inline
 { return 48; }
Referenced by computeGrossBitrate(), and inet::physicallayer::Ieee80211OfdmDataMode::getDuration().
getNumberOfPilotSubcarriers()
int inet::physicallayer::Ieee80211OfdmModeBase::getNumberOfPilotSubcarriers () const inline
 { return 4; }
getNumberOfTotalSubcarriers()
int inet::physicallayer::Ieee80211OfdmModeBase::getNumberOfTotalSubcarriers () const inline
 { return getNumberOfDataSubcarriers() + getNumberOfPilotSubcarriers(); }
Member Data Documentation
bandwidth
const Hz inet::physicallayer::Ieee80211OfdmModeBase::bandwidth protected
code
const Ieee80211OfdmCode* inet::physicallayer::Ieee80211OfdmModeBase::code protected
Referenced by computeNetBitrate(), inet::physicallayer::Ieee80211OfdmDataMode::getDuration(), getNetBitrate(), and inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength().
grossBitrate
bps inet::physicallayer::Ieee80211OfdmModeBase::grossBitrate mutable protected
Referenced by computeNetBitrate(), and getGrossBitrate().
modulation
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmModeBase::modulation protected
Referenced by computeGrossBitrate(), inet::physicallayer::Ieee80211OfdmDataMode::getDuration(), getGrossBitrate(), and inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength().
netBitrate
bps inet::physicallayer::Ieee80211OfdmModeBase::netBitrate mutable protected
Referenced by getNetBitrate(), and inet::physicallayer::Ieee80211OfdmDataMode::printToStream().
The documentation for this class was generated from the following files:
Ieee80211OfdmMode.h
Ieee80211OfdmMode.cc