INET Framework for OMNeT++/OMNEST: inet::visualizer::RoutingTableVisualizerBase Class Reference
inet::visualizer::RoutingTableVisualizerBase Class Reference abstract
#include <RoutingTableVisualizerBase.h>
Classes
class DirectiveResolver
class RouteVisualization
Parameters
bool displayRoutingTables = false
bool displayRoutesIndividually = false
bool displayLabels = false
NetworkNodeFilter destinationFilter
NetworkNodeFilter nodeFilter
cFigure::Color lineColor
cFigure::LineStyle lineStyle
double lineShift = NaN
const char * lineShiftMode = nullptr
double lineWidth = NaN
double lineContactSpacing = NaN
const char * lineContactMode = nullptr
StringFormat labelFormat
cFigure::Font labelFont
cFigure::Color labelColor
LineManager * lineManager = nullptr
std::map< std::tuple< Ipv4Address, int, int >, const RouteVisualization * > routeVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual const RouteVisualization * createRouteVisualization (Ipv4Route *route, cModule *node, cModule *nextHop) const =0
virtual const RouteVisualization * getRouteVisualization (Ipv4Route *route, int nodeModuleId, int nextHopModuleId)
virtual void addRouteVisualization (const RouteVisualization *routeVisualization)
virtual void removeRouteVisualization (const RouteVisualization *routeVisualization)
virtual std::vector< Ipv4Address > getDestinations ()
virtual void addRouteVisualizations (IIpv4RoutingTable *routingTable)
virtual void removeRouteVisualizations (IIpv4RoutingTable *routingTable)
virtual void removeAllRouteVisualizations ()
virtual void updateRouteVisualizations (IIpv4RoutingTable *routingTable)
virtual void updateAllRouteVisualizations ()
virtual std::string getRouteVisualizationText (const Ipv4Route *route) const
virtual void refreshRouteVisualization (const RouteVisualization *routeVisualization) const =0
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *obj, cObject *details) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addRouteVisualization()
void inet::visualizer::RoutingTableVisualizerBase::addRouteVisualization (const RouteVisualization * routeVisualization) protected virtual
Reimplemented in inet::visualizer::RoutingTableCanvasVisualizer, and inet::visualizer::RoutingTableOsgVisualizer.
 {
     Ipv4Address routerId;
     if (routeVisualization->route != nullptr)
         routerId = routeVisualization->route->getRoutingTable()->getRouterId();
     auto key = std::make_tuple(routerId, routeVisualization->sourceModuleId, routeVisualization->destinationModuleId);
     routeVisualizations[key] = routeVisualization;
 }
Referenced by inet::visualizer::RoutingTableOsgVisualizer::addRouteVisualization(), inet::visualizer::RoutingTableCanvasVisualizer::addRouteVisualization(), and addRouteVisualizations().
addRouteVisualizations()
void inet::visualizer::RoutingTableVisualizerBase::addRouteVisualizations (IIpv4RoutingTable * routingTable) protected virtual
 {
     L3AddressResolver addressResolver;
     auto node = getContainingNode(check_and_cast<cModule *>(routingTable));
     for (auto destination : getDestinations()) {
         if (!routingTable->isLocalAddress(destination)) {
             auto route = routingTable->findBestMatchingRoute(destination);
             if (route != nullptr) {
                 auto gateway = route->getGateway();
                 auto nextHop = addressResolver.findHostWithAddress(gateway.isUnspecified() ? destination : gateway);
                 if (nextHop != nullptr) {
                     auto routeVisualization = getRouteVisualization(displayRoutesIndividually ? route : nullptr, node->getId(), nextHop->getId());
                     if (routeVisualization == nullptr)
                         addRouteVisualization(createRouteVisualization(displayRoutesIndividually ? route : nullptr, node, nextHop));
                     else {
                         routeVisualization->numRoutes++;
                         refreshRouteVisualization(routeVisualization);
                     }
                 }
             }
         }
     }
 }
Referenced by updateAllRouteVisualizations(), and updateRouteVisualizations().
createRouteVisualization()
virtual const RouteVisualization* inet::visualizer::RoutingTableVisualizerBase::createRouteVisualization (Ipv4Route * route, cModule * node, cModule * nextHop) const protected pure virtual
Implemented in inet::visualizer::RoutingTableCanvasVisualizer, and inet::visualizer::RoutingTableOsgVisualizer.
Referenced by addRouteVisualizations().
getDestinations()
std::vector< Ipv4Address > inet::visualizer::RoutingTableVisualizerBase::getDestinations () protected virtual
 {
     L3AddressResolver addressResolver;
     std::vector<Ipv4Address> destinations;
     for (cModule::SubmoduleIterator it(visualizationSubjectModule); !it.end(); it++) {
         auto networkNode = *it;
         if (isNetworkNode(networkNode) && destinationFilter.matches(networkNode)) {
             auto interfaceTable = addressResolver.findInterfaceTableOf(networkNode);
             for (int i = 0; i < interfaceTable->getNumInterfaces(); i++) {
                 auto interface = interfaceTable->getInterface(i);
                 auto address = interface->getIpv4Address();
                 if (!address.isUnspecified())
                     destinations.push_back(address);
             }
         }
     }
     return destinations;
 }
Referenced by addRouteVisualizations().
getRouteVisualization()
const RoutingTableVisualizerBase::RouteVisualization * inet::visualizer::RoutingTableVisualizerBase::getRouteVisualization (Ipv4Route * route, int nodeModuleId, int nextHopModuleId) protected virtual
 {
     Ipv4Address routerId;
     if (route != nullptr)
         routerId = route->getRoutingTable()->getRouterId();
     auto key = std::make_tuple(routerId, nodeModuleId, nextHopModuleId);
     auto it = routeVisualizations.find(key);
     return it == routeVisualizations.end() ? nullptr : it->second;
 }
Referenced by addRouteVisualizations().
getRouteVisualizationText()
std::string inet::visualizer::RoutingTableVisualizerBase::getRouteVisualizationText (const Ipv4Route * route) const protected virtual
 {
     DirectiveResolver directiveResolver(route);
     return labelFormat.formatString(&directiveResolver);
 }
Referenced by inet::visualizer::RoutingTableCanvasVisualizer::refreshRouteVisualization().
handleParameterChange()
void inet::visualizer::RoutingTableVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "destinationFilter"))
             destinationFilter.setPattern(par("destinationFilter"));
         else if (!strcmp(name, "nodeFilter"))
             nodeFilter.setPattern(par("nodeFilter"));
         else if (!strcmp(name, "labelFormat"))
             labelFormat.parseFormat(par("labelFormat"));
         updateAllRouteVisualizations();
     }
 }
initialize()
void inet::visualizer::RoutingTableVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::RoutingTableCanvasVisualizer, and inet::visualizer::RoutingTableOsgVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayRoutingTables = par("displayRoutingTables");
         displayRoutesIndividually = par("displayRoutesIndividually");
         displayLabels = par("displayLabels");
         destinationFilter.setPattern(par("destinationFilter"));
         nodeFilter.setPattern(par("nodeFilter"));
         lineColor = cFigure::Color(par("lineColor"));
         lineStyle = cFigure::parseLineStyle(par("lineStyle"));
         lineWidth = par("lineWidth");
         lineShift = par("lineShift");
         lineShiftMode = par("lineShiftMode");
         lineContactSpacing = par("lineContactSpacing");
         lineContactMode = par("lineContactMode");
         labelFormat.parseFormat(par("labelFormat"));
         labelFont = cFigure::parseFont(par("labelFont"));
         labelColor = cFigure::Color(par("labelColor"));
         if (displayRoutingTables)
             subscribe();
     }
 }
Referenced by inet::visualizer::RoutingTableOsgVisualizer::initialize(), and inet::visualizer::RoutingTableCanvasVisualizer::initialize().
preDelete()
void inet::visualizer::RoutingTableVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayRoutingTables) {
         unsubscribe();
         removeAllRouteVisualizations();
     }
 }
receiveSignal()
void inet::visualizer::RoutingTableVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * obj, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == routeAddedSignal || signal == routeDeletedSignal || signal == routeChangedSignal) {
         auto routingTable = check_and_cast<IIpv4RoutingTable *>(source);
         auto networkNode = getContainingNode(check_and_cast<cModule *>(source));
         if (nodeFilter.matches(networkNode))
             updateRouteVisualizations(routingTable);
     }
     else if (signal == interfaceIpv4ConfigChangedSignal)
         updateAllRouteVisualizations();
     else
         throw cRuntimeError("Unknown signal");
 }
refreshRouteVisualization()
virtual void inet::visualizer::RoutingTableVisualizerBase::refreshRouteVisualization (const RouteVisualization * routeVisualization) const protected pure virtual
Implemented in inet::visualizer::RoutingTableCanvasVisualizer, and inet::visualizer::RoutingTableOsgVisualizer.
Referenced by addRouteVisualizations().
removeAllRouteVisualizations()
void inet::visualizer::RoutingTableVisualizerBase::removeAllRouteVisualizations () protected virtual
 {
     std::vector<const RouteVisualization *> removedRouteVisualizations;
     for (auto it : routeVisualizations)
         removedRouteVisualizations.push_back(it.second);
     for (auto it : removedRouteVisualizations) {
         removeRouteVisualization(it);
         delete it;
     }
 }
Referenced by preDelete(), and updateAllRouteVisualizations().
removeRouteVisualization()
void inet::visualizer::RoutingTableVisualizerBase::removeRouteVisualization (const RouteVisualization * routeVisualization) protected virtual
Reimplemented in inet::visualizer::RoutingTableCanvasVisualizer, and inet::visualizer::RoutingTableOsgVisualizer.
 {
     Ipv4Address routerId;
     if (routeVisualization->route != nullptr)
         routerId = routeVisualization->route->getRoutingTable()->getRouterId();
     auto key = std::make_tuple(routerId, routeVisualization->sourceModuleId, routeVisualization->destinationModuleId);
     routeVisualizations.erase(routeVisualizations.find(key));
 }
Referenced by removeAllRouteVisualizations(), inet::visualizer::RoutingTableOsgVisualizer::removeRouteVisualization(), inet::visualizer::RoutingTableCanvasVisualizer::removeRouteVisualization(), and removeRouteVisualizations().
removeRouteVisualizations()
void inet::visualizer::RoutingTableVisualizerBase::removeRouteVisualizations (IIpv4RoutingTable * routingTable) protected virtual
 {
     auto networkNode = getContainingNode(check_and_cast<cModule *>(routingTable));
     std::vector<const RouteVisualization *> removedRouteVisualizations;
     for (auto it : routeVisualizations)
         if (std::get<1>(it.first) == networkNode->getId() && it.second)
             removedRouteVisualizations.push_back(it.second);
     for (auto it : removedRouteVisualizations) {
         removeRouteVisualization(it);
         delete it;
     }
 }
Referenced by updateRouteVisualizations().
subscribe()
void inet::visualizer::RoutingTableVisualizerBase::subscribe () protected virtual
 {
     visualizationSubjectModule->subscribe(routeAddedSignal, this);
     visualizationSubjectModule->subscribe(routeDeletedSignal, this);
     visualizationSubjectModule->subscribe(routeChangedSignal, this);
     visualizationSubjectModule->subscribe(interfaceIpv4ConfigChangedSignal, this);
 }
Referenced by initialize().
unsubscribe()
void inet::visualizer::RoutingTableVisualizerBase::unsubscribe () protected virtual
 {
     // NOTE: lookup the module again because it may have been deleted first
     auto visualizationSubjectModule = findModuleFromPar<cModule>(par("visualizationSubjectModule"), this);
     if (visualizationSubjectModule != nullptr) {
         visualizationSubjectModule->unsubscribe(routeAddedSignal, this);
         visualizationSubjectModule->unsubscribe(routeDeletedSignal, this);
         visualizationSubjectModule->unsubscribe(routeChangedSignal, this);
         visualizationSubjectModule->unsubscribe(interfaceIpv4ConfigChangedSignal, this);
     }
 }
Referenced by preDelete().
updateAllRouteVisualizations()
void inet::visualizer::RoutingTableVisualizerBase::updateAllRouteVisualizations () protected virtual
 {
     removeAllRouteVisualizations();
     for (cModule::SubmoduleIterator it(visualizationSubjectModule); !it.end(); it++) {
         auto networkNode = *it;
         if (isNetworkNode(networkNode) && nodeFilter.matches(networkNode)) {
             L3AddressResolver addressResolver;
             auto routingTable = addressResolver.findIpv4RoutingTableOf(networkNode);
             if (routingTable != nullptr)
                 addRouteVisualizations(routingTable);
         }
     }
 }
Referenced by handleParameterChange(), and receiveSignal().
updateRouteVisualizations()
void inet::visualizer::RoutingTableVisualizerBase::updateRouteVisualizations (IIpv4RoutingTable * routingTable) protected virtual
 {
     removeRouteVisualizations(routingTable);
     addRouteVisualizations(routingTable);
 }
Referenced by receiveSignal().
Member Data Documentation
destinationFilter
NetworkNodeFilter inet::visualizer::RoutingTableVisualizerBase::destinationFilter protected
Referenced by getDestinations(), handleParameterChange(), and initialize().
displayLabels
bool inet::visualizer::RoutingTableVisualizerBase::displayLabels = false protected
Referenced by inet::visualizer::RoutingTableCanvasVisualizer::createRouteVisualization(), and initialize().
displayRoutesIndividually
bool inet::visualizer::RoutingTableVisualizerBase::displayRoutesIndividually = false protected
Referenced by addRouteVisualizations(), initialize(), and inet::visualizer::RoutingTableCanvasVisualizer::refreshRouteVisualization().
displayRoutingTables
bool inet::visualizer::RoutingTableVisualizerBase::displayRoutingTables = false protected
Referenced by initialize(), and preDelete().
labelColor
cFigure::Color inet::visualizer::RoutingTableVisualizerBase::labelColor protected
Referenced by inet::visualizer::RoutingTableCanvasVisualizer::createRouteVisualization(), and initialize().
labelFont
cFigure::Font inet::visualizer::RoutingTableVisualizerBase::labelFont protected
Referenced by inet::visualizer::RoutingTableCanvasVisualizer::createRouteVisualization(), and initialize().
labelFormat
StringFormat inet::visualizer::RoutingTableVisualizerBase::labelFormat protected
Referenced by getRouteVisualizationText(), handleParameterChange(), and initialize().
lineColor
cFigure::Color inet::visualizer::RoutingTableVisualizerBase::lineColor protected
Referenced by inet::visualizer::RoutingTableOsgVisualizer::createRouteVisualization(), inet::visualizer::RoutingTableCanvasVisualizer::createRouteVisualization(), and initialize().
lineContactMode
const char* inet::visualizer::RoutingTableVisualizerBase::lineContactMode = nullptr protected
Referenced by initialize(), and inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay().
lineContactSpacing
double inet::visualizer::RoutingTableVisualizerBase::lineContactSpacing = NaN protected
Referenced by initialize(), and inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay().
lineManager
LineManager* inet::visualizer::RoutingTableVisualizerBase::lineManager = nullptr protected
Referenced by inet::visualizer::RoutingTableCanvasVisualizer::addRouteVisualization(), inet::visualizer::RoutingTableOsgVisualizer::initialize(), inet::visualizer::RoutingTableCanvasVisualizer::initialize(), inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay(), and inet::visualizer::RoutingTableCanvasVisualizer::removeRouteVisualization().
lineShift
double inet::visualizer::RoutingTableVisualizerBase::lineShift = NaN protected
Referenced by initialize(), and inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay().
lineShiftMode
const char* inet::visualizer::RoutingTableVisualizerBase::lineShiftMode = nullptr protected
Referenced by initialize(), and inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay().
lineStyle
cFigure::LineStyle inet::visualizer::RoutingTableVisualizerBase::lineStyle protected
Referenced by inet::visualizer::RoutingTableCanvasVisualizer::createRouteVisualization(), and initialize().
lineWidth
double inet::visualizer::RoutingTableVisualizerBase::lineWidth = NaN protected
Referenced by inet::visualizer::RoutingTableOsgVisualizer::createRouteVisualization(), inet::visualizer::RoutingTableCanvasVisualizer::createRouteVisualization(), and initialize().
nodeFilter
NetworkNodeFilter inet::visualizer::RoutingTableVisualizerBase::nodeFilter protected
Referenced by handleParameterChange(), initialize(), receiveSignal(), and updateAllRouteVisualizations().
routeVisualizations
std::map<std::tuple<Ipv4Address, int, int>, const RouteVisualization *> inet::visualizer::RoutingTableVisualizerBase::routeVisualizations protected
Referenced by addRouteVisualization(), getRouteVisualization(), inet::visualizer::RoutingTableCanvasVisualizer::refreshDisplay(), removeAllRouteVisualizations(), removeRouteVisualization(), and removeRouteVisualizations().
The documentation for this class was generated from the following files:
RoutingTableVisualizerBase.h
RoutingTableVisualizerBase.cc