INET Framework for OMNeT++/OMNEST: inet::PositionTable Class Reference
inet::PositionTable Class Reference
This class provides a mapping between node addresses and their positions.
#include <PositionTable.h>
Public Member Functions
PositionTable ()
std::vector< L3Address > getAddresses () const
bool hasPosition (const L3Address &address) const
Coord getPosition (const L3Address &address) const
void setPosition (const L3Address &address, const Coord &coord)
void removePosition (const L3Address &address)
void removeOldPositions (simtime_t timestamp)
void clear ()
simtime_t getOldestPosition () const
Private Types
typedef std::pair< simtime_t, Coord > AddressToPositionMapValue
typedef std::map< L3Address, AddressToPositionMapValue > AddressToPositionMap
Private Attributes
AddressToPositionMap addressToPositionMap
Friends
std::ostream & operator<< (std::ostream &o, const PositionTable &t)
Detailed Description
This class provides a mapping between node addresses and their positions.
Member Typedef Documentation
AddressToPositionMap
typedef std::map<L3Address, AddressToPositionMapValue> inet::PositionTable::AddressToPositionMap private
AddressToPositionMapValue
typedef std::pair<simtime_t, Coord> inet::PositionTable::AddressToPositionMapValue private
Constructor & Destructor Documentation
PositionTable()
inet::PositionTable::PositionTable () inline
 {}
Member Function Documentation
clear()
void inet::PositionTable::clear ()
 {
     addressToPositionMap.clear();
 }
Referenced by inet::Gpsr::handleCrashOperation(), inet::Gpsr::handleStopOperation(), and inet::Gpsr::initialize().
getAddresses()
std::vector< L3Address > inet::PositionTable::getAddresses () const
 {
     std::vector<L3Address> addresses;
     for (const auto& elem : addressToPositionMap)
         addresses.push_back(elem.first);
     return addresses;
 }
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::getPlanarNeighbors().
getOldestPosition()
simtime_t inet::PositionTable::getOldestPosition () const
 {
     simtime_t oldestPosition = SimTime::getMaxTime();
     for (const auto& elem : addressToPositionMap) {
         const simtime_t& time = elem.second.first;
         if (time < oldestPosition)
             oldestPosition = time;
     }
     return oldestPosition;
 }
Referenced by inet::Gpsr::getNextNeighborExpiration().
getPosition()
Coord inet::PositionTable::getPosition (const L3Address & address) const
 {
     auto it = addressToPositionMap.find(address);
     return (it == addressToPositionMap.end()) ? Coord(NaN, NaN, NaN) : it->second.second;
 }
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), inet::Gpsr::getNeighborPosition(), inet::Gpsr::getPlanarNeighbors(), and inet::Gpsr::lookupPositionInGlobalRegistry().
hasPosition()
bool inet::PositionTable::hasPosition (const L3Address & address) const
 {
     return containsKey(addressToPositionMap, address);
 }
removeOldPositions()
void inet::PositionTable::removeOldPositions (simtime_t timestamp)
 {
     for (auto it = addressToPositionMap.begin(); it != addressToPositionMap.end();)
         if (it->second.first <= timestamp)
             addressToPositionMap.erase(it++);
         else
             it++;
 }
Referenced by inet::Gpsr::purgeNeighbors().
removePosition()
void inet::PositionTable::removePosition (const L3Address & address)
 {
     auto it = addressToPositionMap.find(address);
     addressToPositionMap.erase(it);
 }
setPosition()
void inet::PositionTable::setPosition (const L3Address & address, const Coord & coord)
 {
     ASSERT(!address.isUnspecified());
     addressToPositionMap[address] = AddressToPositionMapValue(simTime(), coord);
 }
Referenced by inet::Gpsr::processBeacon(), and inet::Gpsr::storePositionInGlobalRegistry().
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & o, const PositionTable & t) friend
 {
     o << "{ ";
     for (auto elem : t.addressToPositionMap) {
         o << elem.first << ":(" << elem.second.first << ";" << elem.second.second << ") ";
     }
     o << "}";
     return o;
 }
Member Data Documentation
addressToPositionMap
AddressToPositionMap inet::PositionTable::addressToPositionMap private
Referenced by clear(), getAddresses(), getOldestPosition(), getPosition(), hasPosition(), inet::operator<<(), removeOldPositions(), removePosition(), and setPosition().
The documentation for this class was generated from the following files:
PositionTable.h
PositionTable.cc