INET Framework for OMNeT++/OMNEST: inet::sctp::SctpStreamResetResponseParameter Class Reference
inet::sctp::SctpStreamResetResponseParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:271 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpStreamResetResponseParameter (const char *name=nullptr)
SctpStreamResetResponseParameter (const SctpStreamResetResponseParameter &other)
virtual ~SctpStreamResetResponseParameter ()
SctpStreamResetResponseParameter & operator= (const SctpStreamResetResponseParameter &other)
virtual SctpStreamResetResponseParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSrResSn () const
virtual void setSrResSn (uint32_t srResSn)
virtual uint32_t getResult () const
virtual void setResult (uint32_t result)
virtual uint32_t getSendersNextTsn () const
virtual void setSendersNextTsn (uint32_t sendersNextTsn)
virtual uint32_t getReceiversNextTsn () const
virtual void setReceiversNextTsn (uint32_t receiversNextTsn)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpStreamResetResponseParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t srResSn = 0
uint32_t result = 0
uint32_t sendersNextTsn = 0
uint32_t receiversNextTsn = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpStreamResetResponseParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:271 by opp_msgtool.
class SctpStreamResetResponseParameter extends SctpParameter
{
    uint32_t srResSn; //Stream Reset Response Sequence Number
    uint32_t result;
    uint32_t sendersNextTsn = 0;
    uint32_t receiversNextTsn = 0;
}
Constructor & Destructor Documentation
SctpStreamResetResponseParameter() [1/2]
inet::sctp::SctpStreamResetResponseParameter::SctpStreamResetResponseParameter (const char * name = nullptr)
SctpStreamResetResponseParameter() [2/2]
inet::sctp::SctpStreamResetResponseParameter::SctpStreamResetResponseParameter (const SctpStreamResetResponseParameter & other)
~SctpStreamResetResponseParameter()
virtual inet::sctp::SctpStreamResetResponseParameter::~SctpStreamResetResponseParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpStreamResetResponseParameter::copy (const SctpStreamResetResponseParameter & other) private
dup()
virtual SctpStreamResetResponseParameter* inet::sctp::SctpStreamResetResponseParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpStreamResetResponseParameter(*this);}
getReceiversNextTsn()
virtual uint32_t inet::sctp::SctpStreamResetResponseParameter::getReceiversNextTsn () const virtual
Referenced by inet::sctp::SctpAssociation::processResetResponseArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getResult()
virtual uint32_t inet::sctp::SctpStreamResetResponseParameter::getResult () const virtual
Referenced by inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processResetResponseArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSendersNextTsn()
virtual uint32_t inet::sctp::SctpStreamResetResponseParameter::getSendersNextTsn () const virtual
Referenced by inet::sctp::SctpAssociation::processResetResponseArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSrResSn()
virtual uint32_t inet::sctp::SctpStreamResetResponseParameter::getSrResSn () const virtual
Referenced by inet::sctp::SctpAssociation::processOutAndResponseArrived(), inet::sctp::SctpAssociation::processResetResponseArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpStreamResetResponseParameter& inet::sctp::SctpStreamResetResponseParameter::operator= (const SctpStreamResetResponseParameter & other)
operator==()
bool inet::sctp::SctpStreamResetResponseParameter::operator== (const SctpStreamResetResponseParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpStreamResetResponseParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpStreamResetResponseParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setReceiversNextTsn()
virtual void inet::sctp::SctpStreamResetResponseParameter::setReceiversNextTsn (uint32_t receiversNextTsn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
setResult()
virtual void inet::sctp::SctpStreamResetResponseParameter::setResult (uint32_t result) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendDoubleStreamResetResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
setSendersNextTsn()
virtual void inet::sctp::SctpStreamResetResponseParameter::setSendersNextTsn (uint32_t sendersNextTsn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
setSrResSn()
virtual void inet::sctp::SctpStreamResetResponseParameter::setSrResSn (uint32_t srResSn) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpAssociation::processAddInAndOutResetRequestArrived(), inet::sctp::SctpAssociation::sendBundledOutgoingResetAndResponse(), inet::sctp::SctpAssociation::sendDoubleStreamResetResponse(), inet::sctp::SctpAssociation::sendOutgoingRequestAndResponse(), and inet::sctp::SctpAssociation::sendStreamResetResponse().
Member Data Documentation
receiversNextTsn
uint32_t inet::sctp::SctpStreamResetResponseParameter::receiversNextTsn = 0 protected
result
uint32_t inet::sctp::SctpStreamResetResponseParameter::result = 0 protected
sendersNextTsn
uint32_t inet::sctp::SctpStreamResetResponseParameter::sendersNextTsn = 0 protected
srResSn
uint32_t inet::sctp::SctpStreamResetResponseParameter::srResSn = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h