INET Framework for OMNeT++/OMNEST: inet::SocketMap Class Reference
inet::SocketMap Class Reference
Small utility class for managing a large number of ISocket objects.
#include <SocketMap.h>
Public Member Functions
SocketMap ()
~SocketMap ()
Destructor does NOT delete the socket objects.
ISocket * findSocketFor (cMessage *msg)
Finds the socket for the given message.
void addSocket (ISocket *socket)
Adds the given socket.
ISocket * removeSocket (ISocket *socket)
Removes the given socket.
unsigned int size () const
Returns the number of sockets stored.
std::map< int, ISocket * > & getMap ()
Returns the socket map.
ISocket * getSocketById (unsigned int socketId)
Returns the socket specified by socketId.
void deleteSockets ()
Deletes the socket objects.
void addWatch ()
Protected Attributes
std::map< int, ISocket * > socketMap
Detailed Description
Small utility class for managing a large number of ISocket objects.
Constructor & Destructor Documentation
SocketMap()
inet::SocketMap::SocketMap () inline
 {}
~SocketMap()
inet::SocketMap::~SocketMap () inline
Destructor does NOT delete the socket objects.
 {}
Member Function Documentation
addSocket()
void inet::SocketMap::addSocket (ISocket * socket)
Adds the given socket.
 {
     ASSERT(!containsKey(socketMap, socket->getSocketId()));
     socketMap[socket->getSocketId()] = socket;
 }
Referenced by inet::PingApp::handleSelfMessage(), inet::TunnelApp::initialize(), inet::bgp::BgpRouter::listenConnectionFromPeer(), inet::bgp::BgpRouter::openTCPConnectionToPeer(), inet::Ldp::openTCPConnectionToPeer(), inet::bgp::BgpRouter::processMessageFromTCP(), inet::TcpServerHostApp::socketAvailable(), and inet::Ldp::socketAvailable().
addWatch()
void inet::SocketMap::addWatch ()
 {
     WATCH_PTRMAP(socketMap);
 }
Referenced by inet::bgp::BgpRouter::addWatches().
deleteSockets()
void inet::SocketMap::deleteSockets ()
Deletes the socket objects.
 {
     for (auto& elem : socketMap)
         delete elem.second;
     socketMap.clear();
 }
Referenced by inet::TunnelApp::handleCrashOperation(), inet::PingApp::handleCrashOperation(), inet::TunnelApp::handleMessageWhenUp(), inet::Ldp::handleMessageWhenUp(), inet::PingApp::~PingApp(), and inet::TcpServerHostApp::~TcpServerHostApp().
findSocketFor()
ISocket * inet::SocketMap::findSocketFor (cMessage * msg)
Finds the socket for the given message.
 {
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     int connId = tags.getTag<SocketInd>()->getSocketId();
     auto i = socketMap.find(connId);
     ASSERT(i == socketMap.end() || i->first == i->second->getSocketId());
     return (i == socketMap.end()) ? nullptr : i->second;
 }
Referenced by inet::TcpServerHostApp::handleMessageWhenUp(), inet::TunnelApp::handleMessageWhenUp(), inet::PingApp::handleMessageWhenUp(), inet::Ldp::handleMessageWhenUp(), and inet::bgp::BgpRouter::processMessageFromTCP().
getMap()
std::map<int, ISocket *>& inet::SocketMap::getMap () inline
Returns the socket map.
 { return socketMap; }
Referenced by inet::TunnelApp::handleCrashOperation(), inet::PingApp::handleCrashOperation(), inet::Ldp::handleCrashOperation(), inet::TunnelApp::handleMessageWhenUp(), inet::Ldp::handleMessageWhenUp(), inet::PingApp::handleSelfMessage(), inet::TunnelApp::handleStopOperation(), inet::PingApp::handleStopOperation(), and inet::Ldp::handleStopOperation().
getSocketById()
ISocket* inet::SocketMap::getSocketById (unsigned int socketId) inline
Returns the socket specified by socketId.
 { return socketMap.at(socketId); }
removeSocket()
ISocket * inet::SocketMap::removeSocket (ISocket * socket)
Removes the given socket.
Returns removed socket or returns nullptr when socket not found in the map
 {
     auto i = socketMap.find(socket->getSocketId());
     if (i != socketMap.end()) {
         socketMap.erase(i);
         return socket;
     }
     return nullptr;
 }
Referenced by inet::bgp::BgpRouter::listenConnectionFromPeer(), inet::bgp::BgpRouter::openTCPConnectionToPeer(), inet::bgp::BgpRouter::processMessageFromTCP(), inet::TcpServerHostApp::removeThread(), inet::PingApp::socketClosed(), inet::TcpServerHostApp::socketDeleted(), and inet::TcpServerHostApp::threadClosed().
size()
unsigned int inet::SocketMap::size () const inline
Returns the number of sockets stored.
 { return socketMap.size(); }
Referenced by inet::PingApp::handleMessageWhenUp(), inet::PingApp::handleStopOperation(), inet::TcpSinkApp::refreshDisplay(), inet::TcpEchoApp::refreshDisplay(), and inet::TcpServerHostApp::refreshDisplay().
Member Data Documentation
socketMap
std::map<int, ISocket *> inet::SocketMap::socketMap protected
Referenced by addSocket(), addWatch(), deleteSockets(), findSocketFor(), and removeSocket().
The documentation for this class was generated from the following files:
SocketMap.h
SocketMap.cc