INET Framework for OMNeT++/OMNEST: inet::queueing::IPacketFilter Class Reference
inet::queueing::IPacketFilter Class Reference abstract
This class defines the interface for packet filters.
#include <IPacketFilter.h>
Public Member Functions
virtual bool matchesPacket (const Packet *packet) const =0
Returns true if the filter matches the given packet.
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
virtual bool canPushSomePacket (cGate *gate) const =0
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const =0
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate)=0
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate)=0
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate)=0
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0))=0
Progresses pushing the packet into the packet sink at the given gate.
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
virtual IPassivePacketSource * getProvider (cGate *gate)=0
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual void handleCanPullPacketChanged (cGate *gate)=0
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful)=0
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
virtual bool canPullSomePacket (cGate *gate) const =0
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const =0
Returns the packet that can be pulled at the given gate.
virtual Packet * pullPacket (cGate *gate)=0
Pulls the packet from the packet source at the given gate.
virtual Packet * pullPacketStart (cGate *gate, bps datarate)=0
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate)=0
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength)=0
Progresses pulling the packet from the packet source at the given gate.
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
virtual IPassivePacketSink * getConsumer (cGate *gate)=0
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual void handleCanPushPacketChanged (cGate *gate)=0
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful)=0
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
Detailed Description
This class defines the interface for packet filters.
Member Function Documentation
matchesPacket()
virtual bool inet::queueing::IPacketFilter::matchesPacket (const Packet * packet) const pure virtual
Returns true if the filter matches the given packet.
Implemented in inet::queueing::RedDropper, inet::queueing::OrdinalBasedDropper, inet::VlanIndFilter, inet::VlanReqFilter, inet::Ieee8021qTagEpdHeaderChecker, inet::EthernetAddressChecker, inet::EthernetMacHeaderChecker, inet::EthernetFragmentFcsChecker, inet::ProtocolChecker, inet::StreamMerger, inet::Ieee8021qTagTpidHeaderChecker, inet::Ieee8021rTagEpdHeaderChecker, inet::EligibilityTimeFilter, inet::Ieee8022SnapChecker, inet::CrcHeaderChecker, inet::FcsHeaderChecker, inet::ReceiveAtL3Address, inet::queueing::LabelFilter, inet::queueing::StatisticalRateLimiter, inet::Ieee8022LlcChecker, inet::ReceiveAtMacAddress, inet::ReceiveAtPort, inet::physicallayer::EthernetFragmentPhyHeaderChecker, inet::physicallayer::EthernetPhyHeaderChecker, inet::EthernetFcsChecker, inet::StreamFilter, inet::queueing::PacketFilter, inet::EthernetTypeOrLengthChecker, inet::Ieee8021aeTagEpdHeaderChecker, inet::ReceiveWithHopLimit, and inet::queueing::ContentBasedFilter.
Referenced by inet::queueing::PacketFilterBase::canPullPacket(), inet::queueing::PacketFilterBase::canPushPacket(), inet::queueing::PacketFilterBase::pullPacket(), inet::queueing::PacketFilterBase::pushPacket(), inet::queueing::PacketFilterBase::pushPacketEnd(), inet::queueing::PacketFilterBase::pushPacketProgress(), and inet::queueing::PacketFilterBase::pushPacketStart().
The documentation for this class was generated from the following file:
IPacketFilter.h