INET Framework for OMNeT++/OMNEST: inet::GaugeFigure Class Reference
inet::GaugeFigure Class Reference
#include <GaugeFigure.h>
Public Member Functions
GaugeFigure (const char *name=nullptr)
virtual ~GaugeFigure ()
virtual const Point getSize () const override
virtual void setValue (int series, simtime_t timestamp, double value) override
const Rectangle & getBounds () const
void setBounds (const Rectangle &rect)
const Color & getBackgroundColor () const
void setBackgroundColor (const Color &color)
const Color & getNeedleColor () const
void setNeedleColor (const Color &color)
const char * getLabel () const
void setLabel (const char *text)
int getLabelOffset () const
void setLabelOffset (int offset)
const Font & getLabelFont () const
void setLabelFont (const Font &font)
const Color & getLabelColor () const
void setLabelColor (const Color &color)
double getMinValue () const
void setMinValue (double value)
double getMaxValue () const
void setMaxValue (double value)
double getTickSize () const
void setTickSize (double value)
const char * getColorStrip () const
void setColorStrip (const char *colorStrip)
Public Member Functions inherited from inet::IIndicatorFigure
virtual ~IIndicatorFigure ()
virtual int getNumSeries () const
virtual void refreshDisplay ()
Protected Member Functions
virtual void parse (cProperty *property) override
virtual const char ** getAllowedPropertyKeys () const override
void addChildren ()
void setColorCurve (const cFigure::Color &curveColor, double startAngle, double endAngle, cArcFigure *arc)
void setCurveGeometry (cArcFigure *curve)
void setTickGeometry (cLineFigure *tick, int index)
void setNumberGeometry (cTextFigure *number, int index)
void setNeedleGeometry ()
void setNeedleTransform ()
void redrawTicks ()
void redrawCurves ()
void layout ()
void refresh ()
Private Attributes
cPathFigure * needle
cTextFigure * valueFigure
cTextFigure * labelFigure
cOvalFigure * backgroundFigure
std::vector< cArcFigure * > curveFigures
std::vector< cLineFigure * > tickFigures
std::vector< cTextFigure * > numberFigures
const char * colorStrip = ""
double min = 0
double max = 100
double tickSize = 10
double value = NaN
int numTicks = 0
double shifting = 0
int curvesOnCanvas = 0
int labelOffset = 10
Constructor & Destructor Documentation
GaugeFigure()
inet::GaugeFigure::GaugeFigure (const char * name = nullptr)
                                          : cGroupFigure(name)
 {
     addChildren();
 }
~GaugeFigure()
inet::GaugeFigure::~GaugeFigure () virtual
 {
     // delete figures which is not in canvas
     for (size_t i = curvesOnCanvas; i < curveFigures.size(); ++i)
         dropAndDelete(curveFigures[i]);
     for (size_t i = numTicks; i < tickFigures.size(); ++i) {
         dropAndDelete(tickFigures[i]);
         dropAndDelete(numberFigures[i]);
     }
 }
Member Function Documentation
addChildren()
void inet::GaugeFigure::addChildren () protected
 {
     backgroundFigure = new cOvalFigure("background");
     needle = new cPathFigure("needle");
     valueFigure = new cTextFigure("value");
     labelFigure = new cTextFigure("label");
     backgroundFigure->setFilled(true);
     backgroundFigure->setFillColor(Color("#b8afa6"));
     needle->setFilled(true);
     needle->setFillColor(cFigure::Color("#dba672"));
     valueFigure->setAnchor(cFigure::ANCHOR_CENTER);
     labelFigure->setAnchor(cFigure::ANCHOR_N);
     addFigure(backgroundFigure);
     addFigure(needle);
     addFigure(valueFigure);
     addFigure(labelFigure);
 }
Referenced by GaugeFigure().
getAllowedPropertyKeys()
const char ** inet::GaugeFigure::getAllowedPropertyKeys () const override protected virtual
 {
     static const char *keys[32];
     if (!keys[0]) {
         const char *localKeys[] = {
             PKEY_BACKGROUND_COLOR, PKEY_NEEDLE_COLOR, PKEY_LABEL, PKEY_LABEL_FONT,
             PKEY_LABEL_COLOR, PKEY_MIN_VALUE, PKEY_MAX_VALUE, PKEY_TICK_SIZE,
             PKEY_COLOR_STRIP, PKEY_INITIAL_VALUE, PKEY_POS, PKEY_SIZE, PKEY_ANCHOR,
             PKEY_BOUNDS, PKEY_LABEL_OFFSET, nullptr
         };
         concatArrays(keys, cGroupFigure::getAllowedPropertyKeys(), localKeys);
     }
     return keys;
 }
getBackgroundColor()
const cFigure::Color & inet::GaugeFigure::getBackgroundColor () const
 {
     return backgroundFigure->getFillColor();
 }
getBounds()
const cFigure::Rectangle & inet::GaugeFigure::getBounds () const
 {
     return backgroundFigure->getBounds();
 }
Referenced by layout(), parse(), setCurveGeometry(), setLabelOffset(), setNeedleGeometry(), setNeedleTransform(), setNumberGeometry(), and setTickGeometry().
getColorStrip()
const char * inet::GaugeFigure::getColorStrip () const
 {
     return colorStrip;
 }
getLabel()
const char * inet::GaugeFigure::getLabel () const
 {
     return labelFigure->getText();
 }
getLabelColor()
const cFigure::Color & inet::GaugeFigure::getLabelColor () const
 {
     return labelFigure->getColor();
 }
getLabelFont()
const cFigure::Font & inet::GaugeFigure::getLabelFont () const
 {
     return labelFigure->getFont();
 }
getLabelOffset()
int inet::GaugeFigure::getLabelOffset () const
 {
     return labelOffset;
 }
getMaxValue()
double inet::GaugeFigure::getMaxValue () const
 {
     return max;
 }
getMinValue()
double inet::GaugeFigure::getMinValue () const
 {
     return min;
 }
getNeedleColor()
const cFigure::Color & inet::GaugeFigure::getNeedleColor () const
 {
     return needle->getFillColor();
 }
getSize()
virtual const Point inet::GaugeFigure::getSize () const inline override virtual
Implements inet::IIndicatorFigure.
 { return getBounds().getSize(); }
getTickSize()
double inet::GaugeFigure::getTickSize () const
 {
     return tickSize;
 }
layout()
void inet::GaugeFigure::layout () protected
 {
     backgroundFigure->setLineWidth(zeroToOne(getBounds().width * BORDER_WIDTH_PERCENT));
     for (cArcFigure *item : curveFigures)
         setCurveGeometry(item);
     for (int i = 0; i < numTicks; ++i) {
         setTickGeometry(tickFigures[i], i);
         setNumberGeometry(numberFigures[i], i);
     }
     setNeedleGeometry();
     valueFigure->setFont(Font("", getBounds().width * FONT_SIZE_PERCENT, 0));
     valueFigure->setPosition(Point(getBounds().getCenter().x, getBounds().y + getBounds().height * VALUE_Y_PERCENT));
     labelFigure->setPosition(Point(getBounds().getCenter().x, getBounds().y + getBounds().height + labelOffset));
 }
Referenced by setBounds().
parse()
void inet::GaugeFigure::parse (cProperty * property) override protected virtual
 {
     cGroupFigure::parse(property);
     const char *s;
     setBounds(parseBounds(property, getBounds()));
     // Set default
     redrawTicks();
     if ((s = property->getValue(PKEY_BACKGROUND_COLOR)) != nullptr)
         setBackgroundColor(parseColor(s));
     if ((s = property->getValue(PKEY_NEEDLE_COLOR)) != nullptr)
         setNeedleColor(parseColor(s));
     if ((s = property->getValue(PKEY_LABEL)) != nullptr)
         setLabel(s);
     if ((s = property->getValue(PKEY_LABEL_OFFSET)) != nullptr)
         setLabelOffset(atoi(s));
     if ((s = property->getValue(PKEY_LABEL_FONT)) != nullptr)
         setLabelFont(parseFont(s));
     if ((s = property->getValue(PKEY_LABEL_COLOR)) != nullptr)
         setLabelColor(parseColor(s));
     // This must be initialize before min and max because it is possible to be too much unnecessary tick and number
     if ((s = property->getValue(PKEY_TICK_SIZE)) != nullptr)
         setTickSize(atof(s));
     if ((s = property->getValue(PKEY_MIN_VALUE)) != nullptr)
         setMinValue(atof(s));
     if ((s = property->getValue(PKEY_MAX_VALUE)) != nullptr)
         setMaxValue(atof(s));
     if ((s = property->getValue(PKEY_COLOR_STRIP)) != nullptr)
         setColorStrip(s);
     if ((s = property->getValue(PKEY_INITIAL_VALUE)) != nullptr)
         setValue(0, simTime(), utils::atod(s));
 }
redrawCurves()
void inet::GaugeFigure::redrawCurves () protected
 {
     // create color strips
     cStringTokenizer signalTokenizer(colorStrip, " ,");
     double lastStop = 0.0;
     double newStop = 0.0;
     Color color;
     size_t index = 0;
     const double deg270InRad = 6 * M_PI / 4;
     while (signalTokenizer.hasMoreTokens()) {
         const char *token = signalTokenizer.nextToken();
         newStop = atof(token);
         if (newStop > lastStop) {
             if (index == curveFigures.size()) {
                 cArcFigure *arc = new cArcFigure("colorStrip");
                 take(arc);
                 arc->setZoomLineWidth(true);
                 curveFigures.push_back(arc);
             }
             setColorCurve(color, M_PI - (deg270InRad * newStop), M_PI - (deg270InRad * lastStop), curveFigures[index]);
             ++index;
             lastStop = newStop;
         }
         if (newStop == 0.0)
             color = Color(token);
     }
     if (lastStop < 1.0) {
         if (index == curveFigures.size()) {
             cArcFigure *arc = new cArcFigure("colorStrip");
             take(arc);
             arc->setZoomLineWidth(true);
             curveFigures.push_back(arc);
         }
         setColorCurve(color, M_PI - deg270InRad, M_PI - (deg270InRad * lastStop), curveFigures[index]);
         ++index;
     }
     int prevCurvesOnCanvas = curvesOnCanvas;
     curvesOnCanvas = index;
     // Add or remove figures from canvas according to previous number of curves
     for (int i = prevCurvesOnCanvas; i < curvesOnCanvas; ++i) {
         drop(curveFigures[i]);
         curveFigures[i]->insertBelow(needle);
     }
     for (int i = curvesOnCanvas; i < prevCurvesOnCanvas; ++i) {
         removeFigure(curveFigures[index]);
         take(curveFigures[index]);
     }
 }
Referenced by setColorStrip().
redrawTicks()
void inet::GaugeFigure::redrawTicks () protected
 {
     ASSERT(tickFigures.size() == numberFigures.size());
     double fraction = std::abs(fmod(min / tickSize, 1));
     shifting = tickSize * (min < 0 ? fraction : 1 - fraction);
     // if fraction == 0 then shifting == tickSize therefore don't have to shift the ticks
     if (shifting == tickSize)
         shifting = 0;
     int prevNumTicks = numTicks;
     numTicks = std::max(0.0, std::abs(max - min - shifting) / tickSize + 1);
     // Allocate ticks and numbers if needed
     if ((size_t)numTicks > tickFigures.size())
         while ((size_t)numTicks > tickFigures.size()) {
             cLineFigure *tick = new cLineFigure();
             cTextFigure *number = new cTextFigure();
             take(tick);
             take(number);
             number->setAnchor(cFigure::ANCHOR_CENTER);
             tickFigures.push_back(tick);
             numberFigures.push_back(number);
         }
     // Add or remove figures from canvas according to previous number of ticks
     for (int i = numTicks; i < prevNumTicks; ++i) {
         removeFigure(tickFigures[i]);
         removeFigure(numberFigures[i]);
         take(tickFigures[i]);
         take(numberFigures[i]);
     }
     for (int i = prevNumTicks; i < numTicks; ++i) {
         drop(tickFigures[i]);
         drop(numberFigures[i]);
         addFigure(tickFigures[i]);
         numberFigures[i]->insertBelow(needle);
     }
     for (int i = 0; i < numTicks; ++i) {
         setTickGeometry(tickFigures[i], i);
         char buf[32];
         double number = min + i * tickSize + shifting;
         if (std::abs(number) < tickSize / 2)
             number = 0;
         sprintf(buf, "%g", number);
         numberFigures[i]->setText(buf);
         setNumberGeometry(numberFigures[i], i);
     }
 }
Referenced by parse(), setMaxValue(), setMinValue(), and setTickSize().
refresh()
void inet::GaugeFigure::refresh () protected
 {
     setNeedleTransform();
     // update displayed number
     if (std::isnan(value))
         valueFigure->setText("");
     else {
         char buf[32];
         sprintf(buf, "%g", value);
         valueFigure->setText(buf);
     }
 }
Referenced by setMaxValue(), setMinValue(), setTickSize(), and setValue().
setBackgroundColor()
void inet::GaugeFigure::setBackgroundColor (const Color & color)
 {
     backgroundFigure->setFillColor(color);
 }
Referenced by parse().
setBounds()
void inet::GaugeFigure::setBounds (const Rectangle & rect)
 {
     backgroundFigure->setBounds(rect);
     layout();
 }
Referenced by parse().
setColorCurve()
void inet::GaugeFigure::setColorCurve (const cFigure::Color & curveColor, double startAngle, double endAngle, cArcFigure * arc) protected
 {
     arc->setLineColor(curveColor);
     arc->setStartAngle(startAngle);
     arc->setEndAngle(endAngle);
     setCurveGeometry(arc);
 }
Referenced by redrawCurves().
setColorStrip()
void inet::GaugeFigure::setColorStrip (const char * colorStrip)
 {
     if (strcmp(this->colorStrip, colorStrip) != 0) {
         this->colorStrip = colorStrip;
         redrawCurves();
     }
 }
Referenced by parse().
setCurveGeometry()
void inet::GaugeFigure::setCurveGeometry (cArcFigure * curve) protected
 {
     double lineWidth = getBounds().width * CURVE_WIDTH_PERCENT;
     Rectangle arcBounds = getBounds();
     double offset = lineWidth + backgroundFigure->getLineWidth();
     arcBounds.height -= offset;
     arcBounds.width -= offset;
     arcBounds.x += offset / 2;
     arcBounds.y += offset / 2;
     curve->setBounds(arcBounds);
     curve->setLineWidth(lineWidth);
     Transform trans;
     trans.rotate(-M_PI / 4, getBounds().getCenter());
     curve->setTransform(trans);
 }
Referenced by layout(), and setColorCurve().
setLabel()
void inet::GaugeFigure::setLabel (const char * text)
 {
     labelFigure->setText(text);
 }
Referenced by parse().
setLabelColor()
void inet::GaugeFigure::setLabelColor (const Color & color)
 {
     labelFigure->setColor(color);
 }
Referenced by parse().
setLabelFont()
void inet::GaugeFigure::setLabelFont (const Font & font)
 {
     labelFigure->setFont(font);
 }
Referenced by parse().
setLabelOffset()
void inet::GaugeFigure::setLabelOffset (int offset)
 {
     if (labelOffset != offset) {
         labelOffset = offset;
         labelFigure->setPosition(Point(getBounds().getCenter().x, getBounds().y + getBounds().height + labelOffset));
     }
 }
Referenced by parse().
setMaxValue()
void inet::GaugeFigure::setMaxValue (double value)
 {
     if (max != value) {
         max = value;
         redrawTicks();
         refresh();
     }
 }
Referenced by parse().
setMinValue()
void inet::GaugeFigure::setMinValue (double value)
 {
     if (min != value) {
         min = value;
         redrawTicks();
         refresh();
     }
 }
Referenced by parse().
setNeedleColor()
void inet::GaugeFigure::setNeedleColor (const Color & color)
 {
     needle->setFillColor(color);
 }
Referenced by parse().
setNeedleGeometry()
void inet::GaugeFigure::setNeedleGeometry () protected
 {
     double cx = getBounds().getCenter().x;
     double cy = getBounds().getCenter().y;
     double w = getBounds().width;
     // draw needle in horizontal position, pointing 9:00 hours
     double needleHalfWidth = w * NEEDLE_WIDTH_PERCENT / 2;
     double needleLength = w * NEEDLE_HEIGHT_PERCENT;
     needle->clearPath();
     needle->addMoveTo(cx + needleHalfWidth, cy);
     needle->addLineTo(cx, cy - needleHalfWidth);
     needle->addLineTo(cx - needleLength, cy);
     needle->addLineTo(cx, cy + needleHalfWidth);
     needle->addClosePath();
     setNeedleTransform();
 }
Referenced by layout().
setNeedleTransform()
void inet::GaugeFigure::setNeedleTransform () protected
 {
     double angle;
     const double offset = NEEDLE_OFFSET_IN_DEGREE * M_PI / 180;
     needle->setVisible(true);
     if (value < min)
         angle = -offset;
     else if (value > max)
         angle = (END_ANGLE - START_ANGLE) + offset;
     else if (std::isnan(value)) {
         needle->setVisible(false);
         return;
     }
     else
         angle = (value - min) / (max - min) * (END_ANGLE - START_ANGLE);
     cFigure::Transform t;
     t.rotate(angle, getBounds().getCenter()).rotate(-M_PI / 4, getBounds().getCenter());
     needle->setTransform(t);
 }
Referenced by refresh(), and setNeedleGeometry().
setNumberGeometry()
void inet::GaugeFigure::setNumberGeometry (cTextFigure * number, int index) protected
 {
     ASSERT(tickFigures.size() > 0);
     double distanceToBorder = tickFigures[0]->getStart().distanceTo(tickFigures[0]->getEnd());
     number->setFont(cFigure::Font("", getBounds().width * FONT_SIZE_PERCENT, 0));
     Point textPos = Point(getBounds().x + distanceToBorder + number->getFont().pointSize, getBounds().getCenter().y);
     number->setPosition(textPos);
     Transform trans;
     trans.rotate(-(M_PI + M_PI / 2) * (index * tickSize + shifting) / (max - min), textPos).
             rotate(M_PI / 4, textPos).
             rotate((M_PI + M_PI / 2) * (index * tickSize + shifting) / (max - min), getBounds().getCenter()).
             rotate(-M_PI / 4, getBounds().getCenter());
     number->setTransform(trans);
 }
Referenced by layout(), and redrawTicks().
setTickGeometry()
void inet::GaugeFigure::setTickGeometry (cLineFigure * tick, int index) protected
 {
     tick->setStart(Point(getBounds().x, getBounds().getCenter().y));
     Point endPos = getBounds().getCenter();
     endPos.x -= !(index % 3) ? getBounds().width * TICK_BIG_LENGTH_PERCENT :
         getBounds().width * TICK_SMALL_LENGTH_PERCENT;
     tick->setEnd(endPos);
     tick->setLineWidth(zeroToOne(getBounds().width * TICK_LINE_WIDTH_PERCENT));
     Transform trans;
     trans.rotate((M_PI + M_PI / 2) * (index * tickSize + shifting) / (max - min), getBounds().getCenter()).
             rotate(-M_PI / 4, getBounds().getCenter());
     tick->setTransform(trans);
 }
Referenced by layout(), and redrawTicks().
setTickSize()
void inet::GaugeFigure::setTickSize (double value)
 {
     if (tickSize != value) {
         tickSize = value;
         redrawTicks();
         refresh();
     }
 }
Referenced by parse().
setValue()
void inet::GaugeFigure::setValue (int series, simtime_t timestamp, double value) override virtual
Implements inet::IIndicatorFigure.
 {
     ASSERT(series == 0);
     // Note: we currently ignore timestamp
     if (value != newValue) {
         value = newValue;
         refresh();
     }
 }
Referenced by parse().
Member Data Documentation
backgroundFigure
cOvalFigure* inet::GaugeFigure::backgroundFigure private
Referenced by addChildren(), getBackgroundColor(), getBounds(), layout(), setBackgroundColor(), setBounds(), and setCurveGeometry().
colorStrip
const char* inet::GaugeFigure::colorStrip = "" private
Referenced by getColorStrip(), redrawCurves(), and setColorStrip().
curveFigures
std::vector<cArcFigure *> inet::GaugeFigure::curveFigures private
Referenced by layout(), redrawCurves(), and ~GaugeFigure().
curvesOnCanvas
int inet::GaugeFigure::curvesOnCanvas = 0 private
Referenced by redrawCurves(), and ~GaugeFigure().
labelFigure
cTextFigure* inet::GaugeFigure::labelFigure private
Referenced by addChildren(), getLabel(), getLabelColor(), getLabelFont(), layout(), setLabel(), setLabelColor(), setLabelFont(), and setLabelOffset().
labelOffset
int inet::GaugeFigure::labelOffset = 10 private
Referenced by getLabelOffset(), layout(), and setLabelOffset().
max
double inet::GaugeFigure::max = 100 private
Referenced by getMaxValue(), redrawTicks(), setMaxValue(), setNeedleTransform(), setNumberGeometry(), and setTickGeometry().
min
double inet::GaugeFigure::min = 0 private
Referenced by getMinValue(), redrawTicks(), setMinValue(), setNeedleTransform(), setNumberGeometry(), and setTickGeometry().
needle
cPathFigure* inet::GaugeFigure::needle private
Referenced by addChildren(), getNeedleColor(), redrawCurves(), redrawTicks(), setNeedleColor(), setNeedleGeometry(), and setNeedleTransform().
numberFigures
std::vector<cTextFigure *> inet::GaugeFigure::numberFigures private
Referenced by layout(), redrawTicks(), and ~GaugeFigure().
numTicks
int inet::GaugeFigure::numTicks = 0 private
Referenced by layout(), redrawTicks(), and ~GaugeFigure().
shifting
double inet::GaugeFigure::shifting = 0 private
Referenced by redrawTicks(), setNumberGeometry(), and setTickGeometry().
tickFigures
std::vector<cLineFigure *> inet::GaugeFigure::tickFigures private
Referenced by layout(), redrawTicks(), setNumberGeometry(), and ~GaugeFigure().
tickSize
double inet::GaugeFigure::tickSize = 10 private
Referenced by getTickSize(), redrawTicks(), setNumberGeometry(), setTickGeometry(), and setTickSize().
value
double inet::GaugeFigure::value = NaN private
Referenced by refresh(), setMaxValue(), setMinValue(), setNeedleTransform(), setTickSize(), and setValue().
valueFigure
cTextFigure* inet::GaugeFigure::valueFigure private
Referenced by addChildren(), layout(), and refresh().
The documentation for this class was generated from the following files:
GaugeFigure.h
GaugeFigure.cc