INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211Prim_AuthenticateConfirm Class Reference
inet::ieee80211::Ieee80211Prim_AuthenticateConfirm Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:144 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211Prim_AuthenticateConfirm ()
Ieee80211Prim_AuthenticateConfirm (const Ieee80211Prim_AuthenticateConfirm &other)
virtual ~Ieee80211Prim_AuthenticateConfirm ()
Ieee80211Prim_AuthenticateConfirm & operator= (const Ieee80211Prim_AuthenticateConfirm &other)
virtual Ieee80211Prim_AuthenticateConfirm * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::MacAddress & getAddress () const
virtual ::inet::MacAddress & getAddressForUpdate ()
virtual void setAddress (const ::inet::MacAddress &address)
Public Member Functions inherited from inet::ieee80211::Ieee80211PrimConfirm
Ieee80211PrimConfirm ()
Ieee80211PrimConfirm (const Ieee80211PrimConfirm &other)
virtual ~Ieee80211PrimConfirm ()
Ieee80211PrimConfirm & operator= (const Ieee80211PrimConfirm &other)
virtual Ieee80211PrimResultCode getResultCode () const
virtual void setResultCode (Ieee80211PrimResultCode resultCode)
Protected Member Functions
bool operator== (const Ieee80211Prim_AuthenticateConfirm &)=delete
Protected Member Functions inherited from inet::ieee80211::Ieee80211PrimConfirm
bool operator== (const Ieee80211PrimConfirm &)=delete
Protected Attributes
::inet::MacAddress address
Protected Attributes inherited from inet::ieee80211::Ieee80211PrimConfirm
Ieee80211PrimResultCode resultCode = static_cast<inet::ieee80211::Ieee80211PrimResultCode>(-1)
Private Member Functions
void copy (const Ieee80211Prim_AuthenticateConfirm &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:144 by opp_msgtool.
//
// Losely based on MLME-AUTHENTICATE.confirm.
// Possible result codes: SUCCESS, INVALID_PARAMETERS, TIMEOUT, TOO_MANY_SIMULTANEOUS_REQUESTS, REFUSED
//
class Ieee80211Prim_AuthenticateConfirm extends Ieee80211PrimConfirm
{
    MacAddress address;
}
Constructor & Destructor Documentation
Ieee80211Prim_AuthenticateConfirm() [1/2]
inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::Ieee80211Prim_AuthenticateConfirm ()
Ieee80211Prim_AuthenticateConfirm() [2/2]
inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::Ieee80211Prim_AuthenticateConfirm (const Ieee80211Prim_AuthenticateConfirm & other)
~Ieee80211Prim_AuthenticateConfirm()
virtual inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::~Ieee80211Prim_AuthenticateConfirm () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::copy (const Ieee80211Prim_AuthenticateConfirm & other) private
dup()
virtual Ieee80211Prim_AuthenticateConfirm* inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::dup () const inline override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimConfirm.
 {return new Ieee80211Prim_AuthenticateConfirm(*this);}
getAddress()
virtual const ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::getAddress () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::processAuthenticateConfirm().
getAddressForUpdate()
virtual ::inet::MacAddress& inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::getAddressForUpdate () inline
 { return const_cast<::inet::MacAddress&>(const_cast<Ieee80211Prim_AuthenticateConfirm*>(this)->getAddress());}
operator=()
Ieee80211Prim_AuthenticateConfirm& inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::operator= (const Ieee80211Prim_AuthenticateConfirm & other)
operator==()
bool inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::operator== (const Ieee80211Prim_AuthenticateConfirm &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimConfirm.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ieee80211::Ieee80211PrimConfirm.
Referenced by inet::ieee80211::doParsimUnpacking().
setAddress()
virtual void inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::setAddress (const ::inet::MacAddress & address) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendAuthenticationConfirm().
Member Data Documentation
address
::inet::MacAddress inet::ieee80211::Ieee80211Prim_AuthenticateConfirm::address protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h