INET Framework for OMNeT++/OMNEST: inet::dymo::PacketJitterTimer Class Reference
inet::dymo::PacketJitterTimer Class Reference
Class generated from inet/routing/dymo/Dymo.msg:72 by opp_msgtool.
#include <Dymo_m.h>
Public Member Functions
PacketJitterTimer (const char *name=nullptr, short kind=0)
PacketJitterTimer (const PacketJitterTimer &other)
virtual ~PacketJitterTimer ()
PacketJitterTimer & operator= (const PacketJitterTimer &other)
virtual PacketJitterTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::omnetpp::cPacket * getJitteredPacket () const
virtual ::omnetpp::cPacket * getJitteredPacketForUpdate ()
virtual void setJitteredPacket (::omnetpp::cPacket *jitteredPacket)
virtual ::omnetpp::cPacket * removeJitteredPacket ()
::omnetpp::cPacket * dropJitteredPacket ()
Protected Member Functions
bool operator== (const PacketJitterTimer &)=delete
Protected Attributes
::omnetpp::cPacket * jitteredPacket = nullptr
Private Member Functions
void copy (const PacketJitterTimer &other)
Detailed Description
Class generated from inet/routing/dymo/Dymo.msg:72 by opp_msgtool.
message PacketJitterTimer
{
    cPacket *jitteredPacket @owned;
}
//
// Dymo packets
//
Constructor & Destructor Documentation
PacketJitterTimer() [1/2]
inet::dymo::PacketJitterTimer::PacketJitterTimer (const char * name = nullptr, short kind = 0)
PacketJitterTimer() [2/2]
inet::dymo::PacketJitterTimer::PacketJitterTimer (const PacketJitterTimer & other)
~PacketJitterTimer()
virtual inet::dymo::PacketJitterTimer::~PacketJitterTimer () virtual
Member Function Documentation
copy()
void inet::dymo::PacketJitterTimer::copy (const PacketJitterTimer & other) private
dropJitteredPacket()
::omnetpp::cPacket* inet::dymo::PacketJitterTimer::dropJitteredPacket () inline
 {return removeJitteredPacket();}
dup()
virtual PacketJitterTimer* inet::dymo::PacketJitterTimer::dup () const inline override virtual
 {return new PacketJitterTimer(*this);}
getJitteredPacket()
virtual const ::omnetpp::cPacket* inet::dymo::PacketJitterTimer::getJitteredPacket () const virtual
getJitteredPacketForUpdate()
virtual ::omnetpp::cPacket* inet::dymo::PacketJitterTimer::getJitteredPacketForUpdate () inline
 { return const_cast<::omnetpp::cPacket *>(const_cast<PacketJitterTimer*>(this)->getJitteredPacket());}
operator=()
PacketJitterTimer& inet::dymo::PacketJitterTimer::operator= (const PacketJitterTimer & other)
operator==()
bool inet::dymo::PacketJitterTimer::operator== (const PacketJitterTimer &) protected delete
parsimPack()
virtual void inet::dymo::PacketJitterTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::dymo::doParsimPacking().
parsimUnpack()
virtual void inet::dymo::PacketJitterTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::dymo::doParsimUnpacking().
removeJitteredPacket()
virtual ::omnetpp::cPacket* inet::dymo::PacketJitterTimer::removeJitteredPacket ()
Referenced by inet::dymo::Dymo::processJitterTimerPacket().
setJitteredPacket()
virtual void inet::dymo::PacketJitterTimer::setJitteredPacket (::omnetpp::cPacket * jitteredPacket) virtual
Referenced by inet::dymo::Dymo::scheduleJitterTimerPacket().
Member Data Documentation
jitteredPacket
::omnetpp::cPacket* inet::dymo::PacketJitterTimer::jitteredPacket = nullptr protected
The documentation for this class was generated from the following file:
Dymo_m.h