INET Framework for OMNeT++/OMNEST: inet::rtp::RtpSenderControlMessage Class Reference
inet::rtp::RtpSenderControlMessage Class Reference
Class generated from inet/transportlayer/rtp/RtpSenderControlMessage.msg:41 by opp_msgtool.
#include <RtpSenderControlMessage_m.h>
Public Member Functions
RtpSenderControlMessage (const char *name=nullptr, short kind=0)
RtpSenderControlMessage (const RtpSenderControlMessage &other)
virtual ~RtpSenderControlMessage ()
RtpSenderControlMessage & operator= (const RtpSenderControlMessage &other)
virtual RtpSenderControlMessage * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual RtpSenderControlMessageCommands getCommand () const
virtual void setCommand (RtpSenderControlMessageCommands command)
virtual float getCommandParameter1 () const
virtual void setCommandParameter1 (float commandParameter1)
virtual float getCommandParameter2 () const
virtual void setCommandParameter2 (float commandParameter2)
Protected Member Functions
bool operator== (const RtpSenderControlMessage &)=delete
Protected Attributes
RtpSenderControlMessageCommands command = static_cast<inet::rtp::RtpSenderControlMessageCommands>(-1)
float commandParameter1 = 0
float commandParameter2 = 0
Private Member Functions
void copy (const RtpSenderControlMessage &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpSenderControlMessage.msg:41 by opp_msgtool.
packet RtpSenderControlMessage
{
    RtpSenderControlMessageCommands command;
    float commandParameter1;
    float commandParameter2;
}
Constructor & Destructor Documentation
RtpSenderControlMessage() [1/2]
inet::rtp::RtpSenderControlMessage::RtpSenderControlMessage (const char * name = nullptr, short kind = 0)
RtpSenderControlMessage() [2/2]
inet::rtp::RtpSenderControlMessage::RtpSenderControlMessage (const RtpSenderControlMessage & other)
~RtpSenderControlMessage()
virtual inet::rtp::RtpSenderControlMessage::~RtpSenderControlMessage () virtual
Member Function Documentation
copy()
void inet::rtp::RtpSenderControlMessage::copy (const RtpSenderControlMessage & other) private
dup()
virtual RtpSenderControlMessage* inet::rtp::RtpSenderControlMessage::dup () const inline override virtual
 {return new RtpSenderControlMessage(*this);}
getCommand()
virtual RtpSenderControlMessageCommands inet::rtp::RtpSenderControlMessage::getCommand () const virtual
Referenced by inet::rtp::RtpPayloadSender::handleMessage().
getCommandParameter1()
virtual float inet::rtp::RtpSenderControlMessage::getCommandParameter1 () const virtual
Referenced by inet::rtp::RtpPayloadSender::handleMessage().
getCommandParameter2()
virtual float inet::rtp::RtpSenderControlMessage::getCommandParameter2 () const virtual
operator=()
RtpSenderControlMessage& inet::rtp::RtpSenderControlMessage::operator= (const RtpSenderControlMessage & other)
operator==()
bool inet::rtp::RtpSenderControlMessage::operator== (const RtpSenderControlMessage &) protected delete
parsimPack()
virtual void inet::rtp::RtpSenderControlMessage::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpSenderControlMessage::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::rtp::doParsimUnpacking().
setCommand()
virtual void inet::rtp::RtpSenderControlMessage::setCommand (RtpSenderControlMessageCommands command) virtual
Referenced by inet::rtp::Rtp::senderModuleControl().
setCommandParameter1()
virtual void inet::rtp::RtpSenderControlMessage::setCommandParameter1 (float commandParameter1) virtual
Referenced by inet::rtp::Rtp::senderModuleControl().
setCommandParameter2()
virtual void inet::rtp::RtpSenderControlMessage::setCommandParameter2 (float commandParameter2) virtual
Referenced by inet::rtp::Rtp::senderModuleControl().
Member Data Documentation
command
RtpSenderControlMessageCommands inet::rtp::RtpSenderControlMessage::command = static_cast<inet::rtp::RtpSenderControlMessageCommands>(-1) protected
commandParameter1
float inet::rtp::RtpSenderControlMessage::commandParameter1 = 0 protected
commandParameter2
float inet::rtp::RtpSenderControlMessage::commandParameter2 = 0 protected
The documentation for this class was generated from the following file:
RtpSenderControlMessage_m.h