INET Framework for OMNeT++/OMNEST: inet::tcp::TcpOptionSack Class Reference
inet::tcp::TcpOptionSack Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:141 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
TcpOptionSack ()
TcpOptionSack (const TcpOptionSack &other)
virtual ~TcpOptionSack ()
TcpOptionSack & operator= (const TcpOptionSack &other)
virtual TcpOptionSack * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setSackItemArraySize (size_t size)
virtual size_t getSackItemArraySize () const
virtual const SackItem & getSackItem (size_t k) const
virtual SackItem & getSackItemForUpdate (size_t k)
virtual void setSackItem (size_t k, const SackItem &sackItem)
virtual void insertSackItem (size_t k, const SackItem &sackItem)
void insertSackItem (const SackItem &sackItem)
virtual void appendSackItem (const SackItem &sackItem)
virtual void eraseSackItem (size_t k)
Public Member Functions inherited from inet::tcp::TcpOption
TcpOption ()
TcpOption (const TcpOption &other)
virtual ~TcpOption ()
TcpOption & operator= (const TcpOption &other)
virtual TcpOptionNumbers getKind () const
virtual void setKind (TcpOptionNumbers kind)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const TcpOptionSack &)=delete
Protected Member Functions inherited from inet::tcp::TcpOption
bool operator== (const TcpOption &)=delete
Protected Attributes
SackItem * sackItem = nullptr
size_t sackItem_arraysize = 0
Protected Attributes inherited from inet::tcp::TcpOption
TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1)
unsigned short length = 1
Private Member Functions
void copy (const TcpOptionSack &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:141 by opp_msgtool.
class TcpOptionSack extends TcpOption
{
    kind = TCPOPTION_SACK;
    length = 2;     // 2 + getSackArraySize() * 8
    SackItem sackItem[];
}
Constructor & Destructor Documentation
TcpOptionSack() [1/2]
inet::tcp::TcpOptionSack::TcpOptionSack ()
TcpOptionSack() [2/2]
inet::tcp::TcpOptionSack::TcpOptionSack (const TcpOptionSack & other)
~TcpOptionSack()
virtual inet::tcp::TcpOptionSack::~TcpOptionSack () virtual
Member Function Documentation
appendSackItem()
virtual void inet::tcp::TcpOptionSack::appendSackItem (const SackItem & sackItem) virtual
copy()
void inet::tcp::TcpOptionSack::copy (const TcpOptionSack & other) private
dup()
virtual TcpOptionSack* inet::tcp::TcpOptionSack::dup () const inline override virtual
Reimplemented from inet::tcp::TcpOption.
 {return new TcpOptionSack(*this);}
eraseSackItem()
virtual void inet::tcp::TcpOptionSack::eraseSackItem (size_t k) virtual
getSackItem()
virtual const SackItem& inet::tcp::TcpOptionSack::getSackItem (size_t k) const virtual
Referenced by inet::tcp::TcpConnection::addSacks(), and inet::tcp::TcpConnection::processSACKOption().
getSackItemArraySize()
virtual size_t inet::tcp::TcpOptionSack::getSackItemArraySize () const virtual
Referenced by inet::tcp::TcpConnection::processSACKOption().
getSackItemForUpdate()
virtual SackItem& inet::tcp::TcpOptionSack::getSackItemForUpdate (size_t k) inline virtual
 { return const_cast<SackItem&>(const_cast<TcpOptionSack*>(this)->getSackItem(k));}
insertSackItem() [1/2]
void inet::tcp::TcpOptionSack::insertSackItem (const SackItem & sackItem) inline
 {appendSackItem(sackItem);}
insertSackItem() [2/2]
virtual void inet::tcp::TcpOptionSack::insertSackItem (size_t k, const SackItem & sackItem) virtual
operator=()
TcpOptionSack& inet::tcp::TcpOptionSack::operator= (const TcpOptionSack & other)
operator==()
bool inet::tcp::TcpOptionSack::operator== (const TcpOptionSack &) protected delete
parsimPack()
virtual void inet::tcp::TcpOptionSack::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::TcpOptionSack::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimUnpacking().
setSackItem()
virtual void inet::tcp::TcpOptionSack::setSackItem (size_t k, const SackItem & sackItem) virtual
Referenced by inet::tcp::TcpConnection::addSacks().
setSackItemArraySize()
virtual void inet::tcp::TcpOptionSack::setSackItemArraySize (size_t size) virtual
Referenced by inet::tcp::TcpConnection::addSacks().
Member Data Documentation
sackItem
SackItem* inet::tcp::TcpOptionSack::sackItem = nullptr protected
sackItem_arraysize
size_t inet::tcp::TcpOptionSack::sackItem_arraysize = 0 protected
The documentation for this class was generated from the following file:
TcpHeader_m.h