INET Framework for OMNeT++/OMNEST: inet::LifecycleOperation Class Reference
inet::LifecycleOperation Class Reference abstract
Base class for operations used by the ILifecycle interface.
#include <LifecycleOperation.h>
Public Types
typedef std::map< std::string, std::string > StringMap
Public Member Functions
LifecycleOperation ()
virtual void initialize (cModule *module, StringMap &params)
Initialize the operation using the parameters provided in the string map.
cModule * getRootModule () const
Returns the module the operation is initiated on.
virtual int getNumStages () const =0
Returns the number of stages required by this operation.
int getCurrentStage () const
Returns the current stage, an integer in 0..numStages-1.
Private Attributes
cModule * rootModule = nullptr
int currentStage = 0
std::vector< IDoneCallback * > pendingList
bool insideInitiateOperation = false
IDoneCallback * operationCompletionCallback = nullptr
Friends
class LifecycleController
Detailed Description
Base class for operations used by the ILifecycle interface.
Subclasses represent "operations" like shutdown, suspend, failure, restart, etc.
See also
LifecycleController, ILifecycle
Member Typedef Documentation
StringMap
typedef std::map<std::string, std::string> inet::LifecycleOperation::StringMap
Constructor & Destructor Documentation
LifecycleOperation()
inet::LifecycleOperation::LifecycleOperation () inline
                          :
         rootModule(nullptr), currentStage(0), insideInitiateOperation(false), operationCompletionCallback(nullptr) {}
Member Function Documentation
getCurrentStage()
int inet::LifecycleOperation::getCurrentStage () const inline
Returns the current stage, an integer in 0..numStages-1.
 { return currentStage; }
Referenced by inet::L2NodeConfigurator::handleOperationStage(), inet::Ipv4NodeConfigurator::handleOperationStage(), inet::NodeStatus::handleOperationStage(), inet::OperationalMixin< cSimpleModule >::handleOperationStage(), inet::Ipv4RoutingTable::handleOperationStage(), inet::Ipv6RoutingTable::handleOperationStage(), and inet::NetworkInterface::handleOperationStage().
getNumStages()
virtual int inet::LifecycleOperation::getNumStages () const pure virtual
Returns the number of stages required by this operation.
Implemented in inet::ModuleCrashOperation, inet::ModuleStopOperation, inet::ModuleStartOperation, inet::InterfaceOperationBase, and inet::ApplicationOperationBase.
Referenced by inet::NodeStatus::handleOperationStage(), and inet::LifecycleController::resumeOperation().
getRootModule()
cModule* inet::LifecycleOperation::getRootModule () const inline
Returns the module the operation is initiated on.
 { return rootModule; }
Referenced by inet::TcpServerListener::handleCrashOperation(), inet::UdpEchoApp::handleCrashOperation(), inet::TelnetApp::handleCrashOperation(), inet::EtherAppServer::handleCrashOperation(), inet::TcpBasicClientApp::handleCrashOperation(), inet::UdpVideoStreamClient::handleCrashOperation(), inet::TcpSessionApp::handleCrashOperation(), inet::TcpServerHostApp::handleCrashOperation(), inet::UdpSink::handleCrashOperation(), inet::EtherTrafGen::handleCrashOperation(), inet::UdpVideoStreamServer::handleCrashOperation(), inet::EtherAppClient::handleCrashOperation(), inet::UdpBasicBurst::handleCrashOperation(), inet::PingApp::handleCrashOperation(), inet::DhcpServer::handleCrashOperation(), and inet::DhcpClient::handleCrashOperation().
initialize()
virtual void inet::LifecycleOperation::initialize (cModule * module, StringMap & params) inline virtual
Initialize the operation using the parameters provided in the string map.
The implementation should destructively modify the map, removing from it the parameters it understands. Ideally, the map should be empty when this method returns; if it is not, the caller should treat that as an error, and report the remaining parameters as unrecognized by the operation.
Reimplemented in inet::InterfaceOperationBase, and inet::ApplicationOperationBase.
{
         cProperties *props = module->getProperties();
         if (props && (props->getAsBool("networkNode") || props->getAsBool("lifecycleSupport")))
             rootModule = module;
         else
             throw cRuntimeError("LifecycleOperation not accepted directly by '(%s)%s' module", module->getClassName(), module->getFullPath().c_str());
     }
Referenced by inet::power::SimpleEpEnergyManagement::executeNodeOperation(), inet::power::SimpleCcBattery::executeNodeOperation(), inet::power::SimpleEpEnergyStorage::executeNodeOperation(), inet::ApplicationOperationBase::initialize(), inet::InterfaceOperationBase::initialize(), and inet::ScenarioManager::processLifecycleCommand().
Friends And Related Function Documentation
LifecycleController
friend class LifecycleController friend
Member Data Documentation
currentStage
int inet::LifecycleOperation::currentStage = 0 private
Referenced by inet::LifecycleController::initiateOperation(), inet::LifecycleController::moduleOperationStageCompleted(), and inet::LifecycleController::resumeOperation().
insideInitiateOperation
bool inet::LifecycleOperation::insideInitiateOperation = false private
Referenced by inet::LifecycleController::initiateOperation(), inet::LifecycleController::moduleOperationStageCompleted(), and inet::LifecycleController::resumeOperation().
operationCompletionCallback
IDoneCallback* inet::LifecycleOperation::operationCompletionCallback = nullptr private
Referenced by inet::LifecycleController::initiateOperation(), and inet::LifecycleController::resumeOperation().
pendingList
std::vector<IDoneCallback *> inet::LifecycleOperation::pendingList private
Referenced by inet::LifecycleController::doOneStage(), inet::LifecycleController::moduleOperationStageCompleted(), and inet::LifecycleController::resumeOperation().
rootModule
cModule* inet::LifecycleOperation::rootModule = nullptr private
Referenced by inet::LifecycleController::resumeOperation().
The documentation for this class was generated from the following file:
LifecycleOperation.h