INET Framework for OMNeT++/OMNEST: inet::IProtocolRegistrationListener Class Reference
inet::IProtocolRegistrationListener Class Reference abstract
This interface defines methods that are called during protocol service primitve registration.
#include <IProtocolRegistrationListener.h>
Public Member Functions
virtual void handleRegisterService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive)=0
virtual void handleRegisterProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive)=0
virtual void handleRegisterServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive)=0
virtual void handleRegisterProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive)=0
virtual void handleRegisterAnyService (cGate *gate, ServicePrimitive servicePrimitive)=0
virtual void handleRegisterAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive)=0
Detailed Description
This interface defines methods that are called during protocol service primitve registration.
Member Function Documentation
handleRegisterAnyProtocol()
virtual void inet::IProtocolRegistrationListener::handleRegisterAnyProtocol (cGate * gate, ServicePrimitive servicePrimitive) pure virtual
Implemented in inet::TransparentProtocolRegistrationListener, inet::MessageDispatcher, inet::DefaultProtocolRegistrationListener, and inet::EthernetEncapsulation.
Referenced by inet::registerAnyProtocol().
handleRegisterAnyService()
virtual void inet::IProtocolRegistrationListener::handleRegisterAnyService (cGate * gate, ServicePrimitive servicePrimitive) pure virtual
Implemented in inet::TransparentProtocolRegistrationListener, inet::MessageDispatcher, and inet::DefaultProtocolRegistrationListener.
Referenced by inet::registerAnyService().
handleRegisterProtocol()
virtual void inet::IProtocolRegistrationListener::handleRegisterProtocol (const Protocol & protocol, cGate * gate, ServicePrimitive servicePrimitive) pure virtual
Implemented in inet::Ipv4, inet::Ipv6, inet::Igmpv2, inet::NextHopForwarding, inet::TransparentProtocolRegistrationListener, inet::MessageDispatcher, inet::Icmpv6, inet::DefaultProtocolRegistrationListener, inet::Mpls, inet::EthernetEncapsulation, inet::NetworkProtocolBase, inet::Ieee8022Llc, inet::Icmp, inet::QosClassifier, inet::ProtocolChecker, inet::SendWithProtocol, inet::RandomQosClassifier, and inet::ExampleQosClassifier.
Referenced by inet::registerProtocol().
handleRegisterProtocolGroup()
virtual void inet::IProtocolRegistrationListener::handleRegisterProtocolGroup (const ProtocolGroup & protocolGroup, cGate * gate, ServicePrimitive servicePrimitive) pure virtual
Implemented in inet::TransparentProtocolRegistrationListener, and inet::DefaultProtocolRegistrationListener.
Referenced by inet::registerProtocolGroup().
handleRegisterService()
virtual void inet::IProtocolRegistrationListener::handleRegisterService (const Protocol & protocol, cGate * gate, ServicePrimitive servicePrimitive) pure virtual
Implemented in inet::Ipv4, inet::Ipv6, inet::Igmpv2, inet::NextHopForwarding, inet::TransparentProtocolRegistrationListener, inet::MessageDispatcher, inet::Icmpv6, inet::DefaultProtocolRegistrationListener, inet::Mpls, inet::EthernetEncapsulation, inet::NetworkProtocolBase, inet::Ieee8022Llc, inet::Icmp, inet::QosClassifier, inet::SendWithProtocol, inet::RandomQosClassifier, and inet::ExampleQosClassifier.
Referenced by inet::registerService().
handleRegisterServiceGroup()
virtual void inet::IProtocolRegistrationListener::handleRegisterServiceGroup (const ProtocolGroup & protocolGroup, cGate * gate, ServicePrimitive servicePrimitive) pure virtual
Implemented in inet::TransparentProtocolRegistrationListener, and inet::DefaultProtocolRegistrationListener.
Referenced by inet::registerServiceGroup().
The documentation for this class was generated from the following file:
IProtocolRegistrationListener.h