INET Framework for OMNeT++/OMNEST: inet::power::IdealEpEnergyStorage Class Reference
inet::power::IdealEpEnergyStorage Class Reference
This class implements an ideal energy storage.
#include <IdealEpEnergyStorage.h>
Public Member Functions
virtual J getNominalEnergyCapacity () const override
Returns the nominal energy capacity in the range [0, +infinity].
virtual J getResidualEnergyCapacity () const override
Returns the residual energy capacity in the range [0, nominalCapacity].
virtual J getEnergyBalance ()
Public Member Functions inherited from inet::power::EpEnergyStorageBase
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
virtual void receiveSignal (cComponent *source, simsignal_t signal, double value, cObject *details) override
Public Member Functions inherited from inet::power::EpEnergySourceBase
virtual W getTotalPowerConsumption () const override
Returns the total power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Public Member Functions inherited from inet::power::EpEnergySinkBase
virtual W getTotalPowerGeneration () const override
Returns the total power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void updateTotalPowerConsumption () override
virtual void updateTotalPowerGeneration () override
virtual void updateEnergyBalance ()
Protected Member Functions inherited from inet::power::EpEnergySourceBase
virtual W computeTotalPowerConsumption () const
Protected Member Functions inherited from inet::power::EpEnergySinkBase
virtual W computeTotalPowerGeneration () const
Protected Attributes
J energyBalance = J(NaN)
simtime_t lastEnergyBalanceUpdate = -1
Protected Attributes inherited from inet::power::EpEnergySourceBase
W totalPowerConsumption = W(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Protected Attributes inherited from inet::power::EpEnergySinkBase
W totalPowerGeneration = W(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergySource
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Static Public Attributes inherited from inet::power::IEpEnergySink
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Static Public Attributes inherited from inet::power::IEpEnergyStorage
static simsignal_t residualEnergyCapacityChangedSignal = cComponent::registerSignal("residualEnergyCapacityChanged")
The signal that is used to publish residual energy capacity changes also including when the energy storage becomes completely depleted or charged.
Detailed Description
This class implements an ideal energy storage.
See the corresponding NED file for more details.
Member Function Documentation
getEnergyBalance()
virtual J inet::power::IdealEpEnergyStorage::getEnergyBalance () inline virtual
 { return energyBalance; }
getNominalEnergyCapacity()
virtual J inet::power::IdealEpEnergyStorage::getNominalEnergyCapacity () const inline override virtual
Returns the nominal energy capacity in the range [0, +infinity].
It specifies the maximum amount of energy that the energy storage can contain.
Implements inet::power::IEpEnergyStorage.
 { return J(INFINITY); }
getResidualEnergyCapacity()
virtual J inet::power::IdealEpEnergyStorage::getResidualEnergyCapacity () const inline override virtual
Returns the residual energy capacity in the range [0, nominalCapacity].
It specifies the amount of energy that the energy storage contains at the moment.
Implements inet::power::IEpEnergyStorage.
 { return J(INFINITY); }
initialize()
void inet::power::IdealEpEnergyStorage::initialize (int stage) override protected virtual
Reimplemented from inet::power::EpEnergyStorageBase.
 {
     EpEnergyStorageBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         energyBalance = J(0);
         lastEnergyBalanceUpdate = 0;
         WATCH(energyBalance);
     }
 }
updateEnergyBalance()
void inet::power::IdealEpEnergyStorage::updateEnergyBalance () protected virtual
 {
     simtime_t currentSimulationTime = simTime();
     if (currentSimulationTime != lastEnergyBalanceUpdate) {
         energyBalance += s((currentSimulationTime - lastEnergyBalanceUpdate).dbl()) * (totalPowerGeneration - totalPowerConsumption);
         lastEnergyBalanceUpdate = currentSimulationTime;
         emit(residualEnergyCapacityChangedSignal, energyBalance.get());
     }
 }
Referenced by updateTotalPowerConsumption(), and updateTotalPowerGeneration().
updateTotalPowerConsumption()
void inet::power::IdealEpEnergyStorage::updateTotalPowerConsumption () override protected virtual
Reimplemented from inet::power::EpEnergyStorageBase.
 {
     updateEnergyBalance();
     EpEnergyStorageBase::updateTotalPowerConsumption();
 }
updateTotalPowerGeneration()
void inet::power::IdealEpEnergyStorage::updateTotalPowerGeneration () override protected virtual
Reimplemented from inet::power::EpEnergyStorageBase.
 {
     updateEnergyBalance();
     EpEnergyStorageBase::updateTotalPowerGeneration();
 }
Member Data Documentation
energyBalance
J inet::power::IdealEpEnergyStorage::energyBalance = J(NaN) protected
Referenced by initialize(), and updateEnergyBalance().
lastEnergyBalanceUpdate
simtime_t inet::power::IdealEpEnergyStorage::lastEnergyBalanceUpdate = -1 protected
Referenced by initialize(), and updateEnergyBalance().
The documentation for this class was generated from the following files:
IdealEpEnergyStorage.h
IdealEpEnergyStorage.cc