INET Framework for OMNeT++/OMNEST: inet::SctpOpenReq Class Reference
inet::SctpOpenReq Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:139 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpOpenReq ()
SctpOpenReq (const SctpOpenReq &other)
virtual ~SctpOpenReq ()
SctpOpenReq & operator= (const SctpOpenReq &other)
virtual SctpOpenReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const AddressVector & getLocalAddresses () const
virtual AddressVector & getLocalAddressesForUpdate ()
virtual void setLocalAddresses (const AddressVector &localAddresses)
virtual const AddressVector & getRemoteAddresses () const
virtual AddressVector & getRemoteAddressesForUpdate ()
virtual void setRemoteAddresses (const AddressVector &remoteAddresses)
virtual bool getFork () const
virtual void setFork (bool fork)
virtual const char * getQueueClass () const
virtual void setQueueClass (const char *queueClass)
virtual const char * getSctpAlgorithmClass () const
virtual void setSctpAlgorithmClass (const char *sctpAlgorithmClass)
virtual uint32_t getInboundStreams () const
virtual void setInboundStreams (uint32_t inboundStreams)
virtual uint32_t getOutboundStreams () const
virtual void setOutboundStreams (uint32_t outboundStreams)
virtual bool getStreamReset () const
virtual void setStreamReset (bool streamReset)
virtual bool getAppLimited () const
virtual void setAppLimited (bool appLimited)
virtual int getPrMethod () const
virtual void setPrMethod (int prMethod)
virtual uint32_t getNumRequests () const
virtual void setNumRequests (uint32_t numRequests)
virtual uint32_t getMessagesToPush () const
virtual void setMessagesToPush (uint32_t messagesToPush)
Public Member Functions inherited from inet::SctpCommandReq
SctpCommandReq ()
SctpCommandReq (const SctpCommandReq &other)
virtual ~SctpCommandReq ()
SctpCommandReq & operator= (const SctpCommandReq &other)
virtual int getSocketId () const
virtual void setSocketId (int socketId)
virtual int getSid () const
virtual void setSid (int sid)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs)
virtual int getSsn () const
virtual void setSsn (int ssn)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered)
virtual double getPrValue () const
virtual void setPrValue (double prValue)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getGate () const
virtual void setGate (int gate)
virtual int getFd () const
virtual void setFd (int fd)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SctpOpenReq &)=delete
Protected Member Functions inherited from inet::SctpCommandReq
bool operator== (const SctpCommandReq &)=delete
Protected Attributes
AddressVector localAddresses
AddressVector remoteAddresses
bool fork = false
::omnetpp::opp_string queueClass = "SctpQueue"
::omnetpp::opp_string sctpAlgorithmClass
uint32_t inboundStreams = 0
uint32_t outboundStreams = 0
bool streamReset = false
bool appLimited = false
int prMethod = 0
uint32_t numRequests = 0
uint32_t messagesToPush = 0
Protected Attributes inherited from inet::SctpCommandReq
int socketId = -1
int sid = -1
int numMsgs = 1
int ssn = -1
unsigned short sendUnordered = false
double prValue = 0
L3Address localAddr
L3Address remoteAddr
int localPort = -1
int remotePort = -1
int gate = -1
int fd = -1
Private Member Functions
void copy (const SctpOpenReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:139 by opp_msgtool.
class SctpOpenReq extends SctpCommandReq
{
    AddressVector localAddresses;
    AddressVector remoteAddresses;
    bool fork = false;               // used only for passive open
    string queueClass = "SctpQueue"; // may be left empty
    string sctpAlgorithmClass;       // may be left empty
    uint32_t inboundStreams;
    uint32_t outboundStreams;
    bool streamReset;
    bool appLimited;
    int prMethod;
    uint32_t numRequests;
    uint32_t messagesToPush;
}
Constructor & Destructor Documentation
SctpOpenReq() [1/2]
inet::SctpOpenReq::SctpOpenReq ()
SctpOpenReq() [2/2]
inet::SctpOpenReq::SctpOpenReq (const SctpOpenReq & other)
~SctpOpenReq()
virtual inet::SctpOpenReq::~SctpOpenReq () virtual
Member Function Documentation
copy()
void inet::SctpOpenReq::copy (const SctpOpenReq & other) private
dup()
virtual SctpOpenReq* inet::SctpOpenReq::dup () const inline override virtual
Reimplemented from inet::SctpCommandReq.
 {return new SctpOpenReq(*this);}
getAppLimited()
virtual bool inet::SctpOpenReq::getAppLimited () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE().
getFork()
virtual bool inet::SctpOpenReq::getFork () const virtual
Referenced by inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getInboundStreams()
virtual uint32_t inet::SctpOpenReq::getInboundStreams () const virtual
Referenced by inet::sctp::SctpAssociation::initAssociation(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getLocalAddresses()
virtual const AddressVector& inet::SctpOpenReq::getLocalAddresses () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getLocalAddressesForUpdate()
virtual AddressVector& inet::SctpOpenReq::getLocalAddressesForUpdate () inline virtual
 { return const_cast<AddressVector&>(const_cast<SctpOpenReq*>(this)->getLocalAddresses());}
getMessagesToPush()
virtual uint32_t inet::SctpOpenReq::getMessagesToPush () const virtual
Referenced by inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getNumRequests()
virtual uint32_t inet::SctpOpenReq::getNumRequests () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getOutboundStreams()
virtual uint32_t inet::SctpOpenReq::getOutboundStreams () const virtual
Referenced by inet::sctp::SctpAssociation::initAssociation(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getPrMethod()
virtual int inet::SctpOpenReq::getPrMethod () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE().
getQueueClass()
virtual const char* inet::SctpOpenReq::getQueueClass () const virtual
Referenced by inet::sctp::SctpAssociation::initAssociation().
getRemoteAddresses()
virtual const AddressVector& inet::SctpOpenReq::getRemoteAddresses () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE().
getRemoteAddressesForUpdate()
virtual AddressVector& inet::SctpOpenReq::getRemoteAddressesForUpdate () inline virtual
 { return const_cast<AddressVector&>(const_cast<SctpOpenReq*>(this)->getRemoteAddresses());}
getSctpAlgorithmClass()
virtual const char* inet::SctpOpenReq::getSctpAlgorithmClass () const virtual
Referenced by inet::sctp::SctpAssociation::initAssociation().
getStreamReset()
virtual bool inet::SctpOpenReq::getStreamReset () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
operator=()
SctpOpenReq& inet::SctpOpenReq::operator= (const SctpOpenReq & other)
operator==()
bool inet::SctpOpenReq::operator== (const SctpOpenReq &) protected delete
parsimPack()
virtual void inet::SctpOpenReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpOpenReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SctpCommandReq.
Referenced by inet::doParsimUnpacking().
setAppLimited()
virtual void inet::SctpOpenReq::setAppLimited (bool appLimited) virtual
setFork()
virtual void inet::SctpOpenReq::setFork (bool fork) virtual
setInboundStreams()
virtual void inet::SctpOpenReq::setInboundStreams (uint32_t inboundStreams) virtual
setLocalAddresses()
virtual void inet::SctpOpenReq::setLocalAddresses (const AddressVector & localAddresses) virtual
Referenced by inet::SctpSocket::listen().
setMessagesToPush()
virtual void inet::SctpOpenReq::setMessagesToPush (uint32_t messagesToPush) virtual
setNumRequests()
virtual void inet::SctpOpenReq::setNumRequests (uint32_t numRequests) virtual
setOutboundStreams()
virtual void inet::SctpOpenReq::setOutboundStreams (uint32_t outboundStreams) virtual
setPrMethod()
virtual void inet::SctpOpenReq::setPrMethod (int prMethod) virtual
setQueueClass()
virtual void inet::SctpOpenReq::setQueueClass (const char * queueClass) virtual
setRemoteAddresses()
virtual void inet::SctpOpenReq::setRemoteAddresses (const AddressVector & remoteAddresses) virtual
setSctpAlgorithmClass()
virtual void inet::SctpOpenReq::setSctpAlgorithmClass (const char * sctpAlgorithmClass) virtual
setStreamReset()
virtual void inet::SctpOpenReq::setStreamReset (bool streamReset) virtual
Member Data Documentation
appLimited
bool inet::SctpOpenReq::appLimited = false protected
fork
bool inet::SctpOpenReq::fork = false protected
inboundStreams
uint32_t inet::SctpOpenReq::inboundStreams = 0 protected
localAddresses
AddressVector inet::SctpOpenReq::localAddresses protected
messagesToPush
uint32_t inet::SctpOpenReq::messagesToPush = 0 protected
numRequests
uint32_t inet::SctpOpenReq::numRequests = 0 protected
outboundStreams
uint32_t inet::SctpOpenReq::outboundStreams = 0 protected
prMethod
int inet::SctpOpenReq::prMethod = 0 protected
queueClass
::omnetpp::opp_string inet::SctpOpenReq::queueClass = "SctpQueue" protected
remoteAddresses
AddressVector inet::SctpOpenReq::remoteAddresses protected
sctpAlgorithmClass
::omnetpp::opp_string inet::SctpOpenReq::sctpAlgorithmClass protected
streamReset
bool inet::SctpOpenReq::streamReset = false protected
The documentation for this class was generated from the following file:
SctpCommand_m.h