INET Framework for OMNeT++/OMNEST: inet::visualizer::NetworkNodeFilter Class Reference
inet::visualizer::NetworkNodeFilter Class Reference
This class provides a generic filter for network nodes.
#include <NetworkNodeFilter.h>
Public Member Functions
void setPattern (const char *pattern)
bool matches (const cModule *module) const
Protected Attributes
cMatchExpression matchExpression
Detailed Description
This class provides a generic filter for network nodes.
The filter is expressed as a pattern using the cMatchExpression format.
Member Function Documentation
matches()
bool inet::visualizer::NetworkNodeFilter::matches (const cModule * module) const
 {
     MatchableObject matchableObject(MatchableObject::ATTRIBUTE_FULLNAME, module);
     return matchExpression.matches(&matchableObject);
 }
Referenced by inet::visualizer::InterfaceTableVisualizerBase::addAllInterfaceVisualizations(), inet::visualizer::RoutingTableVisualizerBase::getDestinations(), inet::visualizer::NetworkNodeOsgVisualizer::initialize(), inet::visualizer::NetworkConnectionVisualizerBase::initialize(), inet::visualizer::NetworkNodeCanvasVisualizer::initialize(), inet::visualizer::NetworkNodeVisualizerBase::receiveSignal(), inet::visualizer::Ieee80211VisualizerBase::receiveSignal(), inet::visualizer::LinkBreakVisualizerBase::receiveSignal(), inet::visualizer::TransportConnectionVisualizerBase::receiveSignal(), inet::visualizer::InterfaceTableVisualizerBase::receiveSignal(), inet::visualizer::RoutingTableVisualizerBase::receiveSignal(), inet::visualizer::LinkVisualizerBase::receiveSignal(), inet::visualizer::PacketDropVisualizerBase::receiveSignal(), inet::visualizer::PathVisualizerBase::receiveSignal(), and inet::visualizer::RoutingTableVisualizerBase::updateAllRouteVisualizations().
setPattern()
void inet::visualizer::NetworkNodeFilter::setPattern (const char * pattern)
 {
     matchExpression.setPattern(pattern, false, true, true);
 }
Referenced by inet::visualizer::NetworkConnectionVisualizerBase::handleParameterChange(), inet::visualizer::NetworkNodeVisualizerBase::handleParameterChange(), inet::visualizer::Ieee80211VisualizerBase::handleParameterChange(), inet::visualizer::LinkBreakVisualizerBase::handleParameterChange(), inet::visualizer::TransportConnectionVisualizerBase::handleParameterChange(), inet::visualizer::InterfaceTableVisualizerBase::handleParameterChange(), inet::visualizer::RoutingTableVisualizerBase::handleParameterChange(), inet::visualizer::LinkVisualizerBase::handleParameterChange(), inet::visualizer::PathVisualizerBase::handleParameterChange(), inet::visualizer::PacketDropVisualizerBase::handleParameterChange(), inet::visualizer::NetworkConnectionVisualizerBase::initialize(), inet::visualizer::NetworkNodeVisualizerBase::initialize(), inet::visualizer::Ieee80211VisualizerBase::initialize(), inet::visualizer::LinkBreakVisualizerBase::initialize(), inet::visualizer::TransportConnectionVisualizerBase::initialize(), inet::visualizer::InterfaceTableVisualizerBase::initialize(), inet::visualizer::RoutingTableVisualizerBase::initialize(), inet::visualizer::LinkVisualizerBase::initialize(), inet::visualizer::PathVisualizerBase::initialize(), and inet::visualizer::PacketDropVisualizerBase::initialize().
Member Data Documentation
matchExpression
cMatchExpression inet::visualizer::NetworkNodeFilter::matchExpression protected
Referenced by matches(), and setPattern().
The documentation for this class was generated from the following files:
NetworkNodeFilter.h
NetworkNodeFilter.cc