INET Framework for OMNeT++/OMNEST: inet::ProtocolDissector::ICallback Class Reference
inet::ProtocolDissector::ICallback Class Reference abstract
#include <ProtocolDissector.h>
Public Member Functions
virtual void startProtocolDataUnit (const Protocol *protocol)=0
Notifies about the start of a new protocol data unit (PDU).
virtual void endProtocolDataUnit (const Protocol *protocol)=0
Notifies about the end of the current protocol data unit (PDU).
virtual void markIncorrect ()=0
Marks the current protocol data unit as incorrect (e.g.
virtual void visitChunk (const Ptr< const Chunk > &chunk, const Protocol *protocol)=0
Notifies about a new chunk in the current protocol data unit (PDU).
virtual void dissectPacket (Packet *packet, const Protocol *protocol)=0
Requests the dissection of the data part of packet according to the given protocol.
Member Function Documentation
dissectPacket()
virtual void inet::ProtocolDissector::ICallback::dissectPacket (Packet * packet, const Protocol * protocol) pure virtual
Requests the dissection of the data part of packet according to the given protocol.
Implemented in inet::PacketDissector::ProtocolDissectorCallback.
Referenced by inet::Ieee802EpdProtocolDissector::dissect(), inet::XMacProtocolDissector::dissect(), inet::WiseRouteProtocolDissector::dissect(), inet::UnitDiskProtocolDissector::dissect(), inet::UdpProtocolDissector::dissect(), inet::AckingMacProtocolDissector::dissect(), inet::ApskProtocolDissector::dissect(), inet::CsmaCaMacProtocolDissector::dissect(), inet::Ieee802LlcDissector::dissect(), inet::ProbabilisticProtocolDissector::dissect(), inet::PppProtocolDissector::dissect(), inet::PimProtocolDissector::dissect(), inet::NextHopProtocolDissector::dissect(), inet::FloodingProtocolDissector::dissect(), inet::ManetProtocolDissector::dissect(), inet::LMacProtocolDissector::dissect(), inet::IcmpProtocolDissector::dissect(), inet::Ipv4ProtocolDissector::dissect(), inet::Ipv6ProtocolDissector::dissect(), inet::EchoProtocolDissector::dissect(), inet::TcpProtocolDissector::dissect(), inet::ShortcutPhyProtocolDissector::dissect(), inet::Ieee802154ProtocolDissector::dissect(), inet::Ieee80211PhyProtocolDissector::dissect(), inet::Icmpv6ProtocolDissector::dissect(), inet::MplsProtocolDissector::dissect(), inet::BMacProtocolDissector::dissect(), inet::EthernetMacProtocolDissector::dissect(), inet::ShortcutMacProtocolDissector::dissect(), inet::sctp::SctpProtocolDissector::dissect(), inet::physicallayer::Ieee8021rTagEpdProtocolDissector::dissect(), inet::physicallayer::EthernetPhyProtocolDissector::dissect(), inet::physicallayer::Ieee8021qTagEpdProtocolDissector::dissect(), and inet::Ieee80211MacProtocolDissector::dissect().
endProtocolDataUnit()
virtual void inet::ProtocolDissector::ICallback::endProtocolDataUnit (const Protocol * protocol) pure virtual
Notifies about the end of the current protocol data unit (PDU).
Implemented in inet::PacketDissector::ProtocolDissectorCallback.
Referenced by inet::Ieee802EpdProtocolDissector::dissect(), inet::XMacProtocolDissector::dissect(), inet::WiseRouteProtocolDissector::dissect(), inet::UnitDiskProtocolDissector::dissect(), inet::UdpProtocolDissector::dissect(), inet::AckingMacProtocolDissector::dissect(), inet::StpProtocolDissector::dissect(), inet::ShortcutPhyProtocolDissector::dissect(), inet::BMacProtocolDissector::dissect(), inet::Ieee802154ProtocolDissector::dissect(), inet::ProbabilisticProtocolDissector::dissect(), inet::RipProtocolDissector::dissect(), inet::RsvpProtocolDissector::dissect(), inet::FloodingProtocolDissector::dissect(), inet::PppProtocolDissector::dissect(), inet::PimProtocolDissector::dissect(), inet::ShortcutMacProtocolDissector::dissect(), inet::NextHopProtocolDissector::dissect(), inet::MplsProtocolDissector::dissect(), inet::Ieee802LlcDissector::dissect(), inet::LsrProtocolDissector::dissect(), inet::LMacProtocolDissector::dissect(), inet::Ipv6ProtocolDissector::dissect(), inet::Ipv4ProtocolDissector::dissect(), inet::IgmpProtocolDissector::dissect(), inet::ApskProtocolDissector::dissect(), inet::CsmaCaMacProtocolDissector::dissect(), inet::TcpProtocolDissector::dissect(), inet::IcmpProtocolDissector::dissect(), inet::ArpProtocolDissector::dissect(), inet::Ieee80211PhyProtocolDissector::dissect(), inet::Ieee80211MgmtProtocolDissector::dissect(), inet::ManetProtocolDissector::dissect(), inet::EchoProtocolDissector::dissect(), inet::Icmpv6ProtocolDissector::dissect(), inet::EthernetMacProtocolDissector::dissect(), inet::ospf::OspfProtocolDissector::dissect(), inet::sctp::SctpProtocolDissector::dissect(), inet::physicallayer::Ieee8021rTagEpdProtocolDissector::dissect(), inet::physicallayer::EthernetPhyProtocolDissector::dissect(), inet::physicallayer::Ieee8021qTagEpdProtocolDissector::dissect(), inet::physicallayer::GptpProtocolDissector::dissect(), inet::Ieee80211MacProtocolDissector::dissect(), and inet::DefaultProtocolDissector::dissect().
markIncorrect()
virtual void inet::ProtocolDissector::ICallback::markIncorrect () pure virtual
Marks the current protocol data unit as incorrect (e.g.
bad CRC/FCS, incorrect length field, bit error).
Implemented in inet::PacketDissector::ProtocolDissectorCallback.
Referenced by inet::Icmpv6ProtocolDissector::dissect(), inet::UdpProtocolDissector::dissect(), inet::ProbabilisticProtocolDissector::dissect(), inet::Ipv6ProtocolDissector::dissect(), inet::Ipv4ProtocolDissector::dissect(), and inet::Ieee80211PhyProtocolDissector::dissect().
startProtocolDataUnit()
virtual void inet::ProtocolDissector::ICallback::startProtocolDataUnit (const Protocol * protocol) pure virtual
Notifies about the start of a new protocol data unit (PDU).
Implemented in inet::PacketDissector::ProtocolDissectorCallback.
Referenced by inet::Ieee802EpdProtocolDissector::dissect(), inet::XMacProtocolDissector::dissect(), inet::WiseRouteProtocolDissector::dissect(), inet::UnitDiskProtocolDissector::dissect(), inet::UdpProtocolDissector::dissect(), inet::AckingMacProtocolDissector::dissect(), inet::StpProtocolDissector::dissect(), inet::ShortcutPhyProtocolDissector::dissect(), inet::BMacProtocolDissector::dissect(), inet::Ieee802154ProtocolDissector::dissect(), inet::ProbabilisticProtocolDissector::dissect(), inet::RipProtocolDissector::dissect(), inet::RsvpProtocolDissector::dissect(), inet::FloodingProtocolDissector::dissect(), inet::PppProtocolDissector::dissect(), inet::PimProtocolDissector::dissect(), inet::ShortcutMacProtocolDissector::dissect(), inet::NextHopProtocolDissector::dissect(), inet::MplsProtocolDissector::dissect(), inet::Ieee802LlcDissector::dissect(), inet::LsrProtocolDissector::dissect(), inet::LMacProtocolDissector::dissect(), inet::Ipv6ProtocolDissector::dissect(), inet::Ipv4ProtocolDissector::dissect(), inet::IgmpProtocolDissector::dissect(), inet::ApskProtocolDissector::dissect(), inet::CsmaCaMacProtocolDissector::dissect(), inet::TcpProtocolDissector::dissect(), inet::IcmpProtocolDissector::dissect(), inet::ArpProtocolDissector::dissect(), inet::Ieee80211PhyProtocolDissector::dissect(), inet::Ieee80211MgmtProtocolDissector::dissect(), inet::ManetProtocolDissector::dissect(), inet::EchoProtocolDissector::dissect(), inet::Icmpv6ProtocolDissector::dissect(), inet::EthernetMacProtocolDissector::dissect(), inet::ospf::OspfProtocolDissector::dissect(), inet::sctp::SctpProtocolDissector::dissect(), inet::physicallayer::Ieee8021rTagEpdProtocolDissector::dissect(), inet::physicallayer::EthernetPhyProtocolDissector::dissect(), inet::physicallayer::Ieee8021qTagEpdProtocolDissector::dissect(), inet::physicallayer::GptpProtocolDissector::dissect(), inet::Ieee80211MacProtocolDissector::dissect(), and inet::DefaultProtocolDissector::dissect().
visitChunk()
virtual void inet::ProtocolDissector::ICallback::visitChunk (const Ptr< const Chunk > & chunk, const Protocol * protocol) pure virtual
Notifies about a new chunk in the current protocol data unit (PDU).
Implemented in inet::PacketDissector::ProtocolDissectorCallback.
Referenced by inet::Ieee802EpdProtocolDissector::dissect(), inet::XMacProtocolDissector::dissect(), inet::WiseRouteProtocolDissector::dissect(), inet::UnitDiskProtocolDissector::dissect(), inet::AckingMacProtocolDissector::dissect(), inet::TcpProtocolDissector::dissect(), inet::StpProtocolDissector::dissect(), inet::ShortcutPhyProtocolDissector::dissect(), inet::BMacProtocolDissector::dissect(), inet::Ieee802154ProtocolDissector::dissect(), inet::RipProtocolDissector::dissect(), inet::RsvpProtocolDissector::dissect(), inet::FloodingProtocolDissector::dissect(), inet::ProbabilisticProtocolDissector::dissect(), inet::PppProtocolDissector::dissect(), inet::PimProtocolDissector::dissect(), inet::ShortcutMacProtocolDissector::dissect(), inet::NextHopProtocolDissector::dissect(), inet::Ieee802LlcDissector::dissect(), inet::LsrProtocolDissector::dissect(), inet::LMacProtocolDissector::dissect(), inet::Ipv6ProtocolDissector::dissect(), inet::Ipv4ProtocolDissector::dissect(), inet::IgmpProtocolDissector::dissect(), inet::ApskProtocolDissector::dissect(), inet::CsmaCaMacProtocolDissector::dissect(), inet::UdpProtocolDissector::dissect(), inet::IcmpProtocolDissector::dissect(), inet::ArpProtocolDissector::dissect(), inet::Ieee80211PhyProtocolDissector::dissect(), inet::Ieee80211MgmtProtocolDissector::dissect(), inet::MplsProtocolDissector::dissect(), inet::EchoProtocolDissector::dissect(), inet::Icmpv6ProtocolDissector::dissect(), inet::EthernetMacProtocolDissector::dissect(), inet::ospf::OspfProtocolDissector::dissect(), inet::sctp::SctpProtocolDissector::dissect(), inet::physicallayer::Ieee8021rTagEpdProtocolDissector::dissect(), inet::physicallayer::Ieee8021qTagEpdProtocolDissector::dissect(), inet::physicallayer::EthernetPhyProtocolDissector::dissect(), inet::physicallayer::GptpProtocolDissector::dissect(), inet::Ieee80211MacProtocolDissector::dissect(), and inet::DefaultProtocolDissector::dissect().
The documentation for this class was generated from the following file:
ProtocolDissector.h