INET Framework for OMNeT++/OMNEST: inet::power::SimpleEpEnergyStorage Class Reference
inet::power::SimpleEpEnergyStorage Class Reference
This class implements a simple total power integrating energy storage.
#include <SimpleEpEnergyStorage.h>
Public Member Functions
virtual ~SimpleEpEnergyStorage ()
virtual J getNominalEnergyCapacity () const override
Returns the nominal energy capacity in the range [0, +infinity].
virtual J getResidualEnergyCapacity () const override
Returns the residual energy capacity in the range [0, nominalCapacity].
Public Member Functions inherited from inet::power::EpEnergyStorageBase
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
virtual void receiveSignal (cComponent *source, simsignal_t signal, double value, cObject *details) override
Public Member Functions inherited from inet::power::EpEnergySourceBase
virtual W getTotalPowerConsumption () const override
Returns the total power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Public Member Functions inherited from inet::power::EpEnergySinkBase
virtual W getTotalPowerGeneration () const override
Returns the total power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Public Member Functions inherited from inet::LifecycleController
LifecycleController ()
virtual ~LifecycleController ()
virtual bool initiateOperation (LifecycleOperation *operation, IDoneCallback *completionCallback=nullptr)
Initiate an operation.
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void refreshDisplay () const override
virtual void updateDisplayString () const
virtual const char * resolveDirective (char directive) const override
virtual void updateTotalPowerConsumption () override
virtual void updateTotalPowerGeneration () override
virtual void executeNodeOperation (J newResidualCapacity)
virtual void setResidualCapacity (J newResidualCapacity)
virtual void updateResidualCapacity ()
virtual void scheduleTimer ()
Protected Member Functions inherited from inet::power::EpEnergySourceBase
virtual W computeTotalPowerConsumption () const
Protected Member Functions inherited from inet::power::EpEnergySinkBase
virtual W computeTotalPowerGeneration () const
Protected Member Functions inherited from inet::LifecycleController
virtual bool resumeOperation (LifecycleOperation *operation)
virtual void doOneStage (LifecycleOperation *operation, cModule *submodule)
virtual void moduleOperationStageCompleted (Callback *callback)
Protected Attributes
J nominalCapacity = J(NaN)
The nominal capacity is in the range [0, +infinity).
J residualCapacity = J(NaN)
The residual capacity is in the range [0, nominalCapacity].
J printCapacityStep = J(NaN)
Specifies the amount of capacity change which will be reported.
simtime_t lastResidualCapacityUpdate = -1
The simulation time when the residual capacity was last updated.
cMessage * timer = nullptr
The timer that is scheduled to the earliest time when the energy storage will be depleted, the energy storage will be charged.
J targetCapacity = J(NaN)
The capacity that will be set when the timer expires.
cModule * networkNode = nullptr
The containing node module.
NodeStatus * nodeStatus = nullptr
The status of the node.
Protected Attributes inherited from inet::power::EpEnergySourceBase
W totalPowerConsumption = W(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Protected Attributes inherited from inet::power::EpEnergySinkBase
W totalPowerGeneration = W(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Protected Attributes inherited from inet::LifecycleController
Callback * spareCallback = nullptr
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergySource
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Static Public Attributes inherited from inet::power::IEpEnergySink
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Static Public Attributes inherited from inet::power::IEpEnergyStorage
static simsignal_t residualEnergyCapacityChangedSignal = cComponent::registerSignal("residualEnergyCapacityChanged")
The signal that is used to publish residual energy capacity changes also including when the energy storage becomes completely depleted or charged.
Detailed Description
This class implements a simple total power integrating energy storage.
It maintains its residual capacity by repeatedly scheduling a single timer to the next capacity update. The next update happens when either the storage becomes completely depleted, completely charged, or the next capacity report is done. Besides, it immediately updates the capacity when the total absorbed or provided power changes, and it also reschedules the timer.
See the corresponding NED file for more details.
Constructor & Destructor Documentation
~SimpleEpEnergyStorage()
inet::power::SimpleEpEnergyStorage::~SimpleEpEnergyStorage () virtual
 {
     cancelAndDelete(timer);
 }
Member Function Documentation
executeNodeOperation()
void inet::power::SimpleEpEnergyStorage::executeNodeOperation (J newResidualCapacity) protected virtual
 {
     if (newResidualCapacity <= J(0) && nodeStatus->getState() == NodeStatus::UP) {
         EV_WARN << "Energy storage failed" << endl;
         LifecycleOperation::StringMap params;
         ModuleCrashOperation *operation = new ModuleCrashOperation();
         operation->initialize(networkNode, params);
         initiateOperation(operation);
     }
 }
Referenced by setResidualCapacity().
getNominalEnergyCapacity()
virtual J inet::power::SimpleEpEnergyStorage::getNominalEnergyCapacity () const inline override virtual
Returns the nominal energy capacity in the range [0, +infinity].
It specifies the maximum amount of energy that the energy storage can contain.
Implements inet::power::IEpEnergyStorage.
 { return nominalCapacity; }
Referenced by resolveDirective().
getResidualEnergyCapacity()
J inet::power::SimpleEpEnergyStorage::getResidualEnergyCapacity () const override virtual
Returns the residual energy capacity in the range [0, nominalCapacity].
It specifies the amount of energy that the energy storage contains at the moment.
Implements inet::power::IEpEnergyStorage.
 {
     const_cast<SimpleEpEnergyStorage *>(this)->updateResidualCapacity();
     return residualCapacity;
 }
Referenced by resolveDirective().
handleMessage()
void inet::power::SimpleEpEnergyStorage::handleMessage (cMessage * message) override protected virtual
 {
     if (message == timer) {
         setResidualCapacity(targetCapacity);
         scheduleTimer();
         EV_INFO << "Residual capacity = " << residualCapacity.get() << " (" << (int)round(unit(residualCapacity / nominalCapacity).get() * 100) << "%)" << endl;
     }
     else
         throw cRuntimeError("Unknown message");
 }
initialize()
void inet::power::SimpleEpEnergyStorage::initialize (int stage) override protected virtual
Reimplemented from inet::power::EpEnergyStorageBase.
 {
     EpEnergyStorageBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         nominalCapacity = J(par("nominalCapacity"));
         printCapacityStep = J(par("printCapacityStep"));
         timer = new cMessage("timer");
         networkNode = findContainingNode(this);
         if (networkNode != nullptr) {
             nodeStatus = dynamic_cast<NodeStatus *>(networkNode->getSubmodule("status"));
             if (!nodeStatus)
                 throw cRuntimeError("Cannot find node status");
         }
         setResidualCapacity(J(par("initialCapacity")));
         scheduleTimer();
         WATCH(residualCapacity);
     }
 }
refreshDisplay()
void inet::power::SimpleEpEnergyStorage::refreshDisplay () const override protected virtual
 {
     updateDisplayString();
 }
resolveDirective()
const char * inet::power::SimpleEpEnergyStorage::resolveDirective (char directive) const override protected virtual
Implements inet::StringFormat::IDirectiveResolver.
 {
     static std::string result;
     switch (directive) {
         case 'c':
             result = getResidualEnergyCapacity().str();
             break;
         case 'p':
             result = std::to_string((int)std::round(100 * unit(getResidualEnergyCapacity() / getNominalEnergyCapacity()).get())) + "%";
             break;
         default:
             throw cRuntimeError("Unknown directive: %c", directive);
     }
     return result.c_str();
 }
scheduleTimer()
void inet::power::SimpleEpEnergyStorage::scheduleTimer () protected virtual
 {
     W totalPower = totalPowerGeneration - totalPowerConsumption;
     targetCapacity = residualCapacity;
     if (totalPower > W(0)) {
         targetCapacity = std::isnan(printCapacityStep.get()) ? nominalCapacity : ceil(unit(residualCapacity / printCapacityStep).get()) * printCapacityStep;
         // NOTE: make sure capacity will change over time despite double arithmetic
         simtime_t remainingTime = unit((targetCapacity - residualCapacity) / totalPower / s(1)).get();
         if (remainingTime == 0)
             targetCapacity += printCapacityStep;
     }
     else if (totalPower < W(0)) {
         targetCapacity = std::isnan(printCapacityStep.get()) ? J(0) : floor(unit(residualCapacity / printCapacityStep).get()) * printCapacityStep;
         // make sure capacity will change over time despite double arithmetic
         simtime_t remainingTime = unit((targetCapacity - residualCapacity) / totalPower / s(1)).get();
         if (remainingTime == 0)
             targetCapacity -= printCapacityStep;
     }
     // enforce target capacity to be in range
     if (targetCapacity < J(0))
         targetCapacity = J(0);
     else if (targetCapacity > nominalCapacity)
         targetCapacity = nominalCapacity;
     if (timer->isScheduled())
         cancelEvent(timer);
     // don't schedule if there's no progress
     if (totalPower != W(0)) {
         simtime_t remainingTime = unit((targetCapacity - residualCapacity) / totalPower / s(1)).get();
         if (remainingTime > 0)
             scheduleAfter(remainingTime, timer);
     }
 }
Referenced by handleMessage(), initialize(), updateTotalPowerConsumption(), and updateTotalPowerGeneration().
setResidualCapacity()
void inet::power::SimpleEpEnergyStorage::setResidualCapacity (J newResidualCapacity) protected virtual
 {
     residualCapacity = newResidualCapacity;
     lastResidualCapacityUpdate = simTime();
     if (residualCapacity == J(0))
         EV_WARN << "Energy storage depleted" << endl;
     else if (residualCapacity == nominalCapacity)
         EV_INFO << "Energy storage charged" << endl;
     if (networkNode != nullptr)
         executeNodeOperation(newResidualCapacity);
     emit(residualEnergyCapacityChangedSignal, residualCapacity.get());
 }
Referenced by handleMessage(), initialize(), and updateResidualCapacity().
updateDisplayString()
void inet::power::SimpleEpEnergyStorage::updateDisplayString () const protected virtual
 {
     if (getEnvir()->isGUI()) {
         auto text = StringFormat::formatString(par("displayStringTextFormat"), this);
         getDisplayString().setTagArg("t", 0, text);
     }
 }
Referenced by refreshDisplay().
updateResidualCapacity()
void inet::power::SimpleEpEnergyStorage::updateResidualCapacity () protected virtual
 {
     simtime_t currentSimulationTime = simTime();
     if (currentSimulationTime != lastResidualCapacityUpdate) {
         J newResidualCapacity = residualCapacity + s((currentSimulationTime - lastResidualCapacityUpdate).dbl()) * (totalPowerGeneration - totalPowerConsumption);
         if (newResidualCapacity < J(0))
             newResidualCapacity = J(0);
         else if (newResidualCapacity > nominalCapacity)
             newResidualCapacity = nominalCapacity;
         setResidualCapacity(newResidualCapacity);
     }
 }
Referenced by getResidualEnergyCapacity(), updateTotalPowerConsumption(), and updateTotalPowerGeneration().
updateTotalPowerConsumption()
void inet::power::SimpleEpEnergyStorage::updateTotalPowerConsumption () override protected virtual
Reimplemented from inet::power::EpEnergyStorageBase.
 {
     updateResidualCapacity();
     EpEnergyStorageBase::updateTotalPowerConsumption();
     scheduleTimer();
 }
updateTotalPowerGeneration()
void inet::power::SimpleEpEnergyStorage::updateTotalPowerGeneration () override protected virtual
Reimplemented from inet::power::EpEnergyStorageBase.
 {
     updateResidualCapacity();
     EpEnergyStorageBase::updateTotalPowerGeneration();
     scheduleTimer();
 }
Member Data Documentation
lastResidualCapacityUpdate
simtime_t inet::power::SimpleEpEnergyStorage::lastResidualCapacityUpdate = -1 protected
The simulation time when the residual capacity was last updated.
Referenced by setResidualCapacity(), and updateResidualCapacity().
networkNode
cModule* inet::power::SimpleEpEnergyStorage::networkNode = nullptr protected
The containing node module.
Referenced by executeNodeOperation(), initialize(), and setResidualCapacity().
nodeStatus
NodeStatus* inet::power::SimpleEpEnergyStorage::nodeStatus = nullptr protected
The status of the node.
Referenced by executeNodeOperation(), and initialize().
nominalCapacity
J inet::power::SimpleEpEnergyStorage::nominalCapacity = J(NaN) protected
The nominal capacity is in the range [0, +infinity).
Referenced by handleMessage(), initialize(), scheduleTimer(), setResidualCapacity(), and updateResidualCapacity().
printCapacityStep
J inet::power::SimpleEpEnergyStorage::printCapacityStep = J(NaN) protected
Specifies the amount of capacity change which will be reported.
Referenced by initialize(), and scheduleTimer().
residualCapacity
J inet::power::SimpleEpEnergyStorage::residualCapacity = J(NaN) protected
The residual capacity is in the range [0, nominalCapacity].
Referenced by getResidualEnergyCapacity(), handleMessage(), initialize(), scheduleTimer(), setResidualCapacity(), and updateResidualCapacity().
targetCapacity
J inet::power::SimpleEpEnergyStorage::targetCapacity = J(NaN) protected
The capacity that will be set when the timer expires.
Referenced by handleMessage(), and scheduleTimer().
timer
cMessage* inet::power::SimpleEpEnergyStorage::timer = nullptr protected
The timer that is scheduled to the earliest time when the energy storage will be depleted, the energy storage will be charged.
Referenced by handleMessage(), initialize(), scheduleTimer(), and ~SimpleEpEnergyStorage().
The documentation for this class was generated from the following files:
SimpleEpEnergyStorage.h
SimpleEpEnergyStorage.cc