INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211AgentSta Class Reference
inet::ieee80211::Ieee80211AgentSta Class Reference
Used in 802.11 infrastructure mode: in a station (STA), this module controls channel scanning, association and handovers, by sending commands (e.g.
#include <Ieee80211AgentSta.h>
Public Member Functions
Ieee80211AgentSta ()
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int) override
virtual void handleMessage (cMessage *msg) override
Overridden cSimpleModule method.
virtual void handleTimer (cMessage *msg)
Handle timers.
virtual void handleResponse (cMessage *msg)
Handle responses from mgmgt.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Redefined from cListener; called by signal handler.
virtual void sendRequest (Ieee80211PrimRequest *req)
virtual void sendScanRequest ()
Sending of Request primitives.
virtual void sendAuthenticateRequest (const MacAddress &address)
virtual void sendDeauthenticateRequest (const MacAddress &address, Ieee80211ReasonCode reasonCode)
virtual void sendAssociateRequest (const MacAddress &address)
virtual void sendReassociateRequest (const MacAddress &address)
virtual void sendDisassociateRequest (const MacAddress &address, Ieee80211ReasonCode reasonCode)
virtual void processScanConfirm (Ieee80211Prim_ScanConfirm *resp)
Processing Confirm primitives.
virtual void processAuthenticateConfirm (Ieee80211Prim_AuthenticateConfirm *resp)
virtual void processAssociateConfirm (Ieee80211Prim_AssociateConfirm *resp)
virtual void processReassociateConfirm (Ieee80211Prim_ReassociateConfirm *resp)
virtual int chooseBSS (Ieee80211Prim_ScanConfirm *resp)
Choose one AP from the list to associate with.
virtual void dumpAPList (Ieee80211Prim_ScanConfirm *resp)
Protected Attributes
NetworkInterface * myIface = nullptr
MacAddress prevAP
bool activeScan = false
std::vector< int > channelsToScan
simtime_t probeDelay
simtime_t minChannelTime
simtime_t maxChannelTime
simtime_t authenticationTimeout
simtime_t associationTimeout
std::string defaultSsid
Static Protected Attributes
static simsignal_t sentRequestSignal = registerSignal("sentRequest")
static simsignal_t acceptConfirmSignal = registerSignal("acceptConfirm")
static simsignal_t dropConfirmSignal = registerSignal("dropConfirm")
Detailed Description
Used in 802.11 infrastructure mode: in a station (STA), this module controls channel scanning, association and handovers, by sending commands (e.g.
Ieee80211Prim_ScanRequest) to the management module (Ieee80211MgmtSta).
See corresponding NED file for a detailed description.
Constructor & Destructor Documentation
Ieee80211AgentSta()
inet::ieee80211::Ieee80211AgentSta::Ieee80211AgentSta () inline
 {}
Member Function Documentation
chooseBSS()
int inet::ieee80211::Ieee80211AgentSta::chooseBSS (Ieee80211Prim_ScanConfirm * resp) protected virtual
Choose one AP from the list to associate with.
 {
     if (resp->getBssListArraySize() == 0)
         return -1;
     // here, just choose the one with the greatest receive power
     // TODO and which supports a good data rate we support
     int bestIndex = 0;
     for (size_t i = 0; i < resp->getBssListArraySize(); i++)
         if (resp->getBssList(i).getRxPower() > resp->getBssList(bestIndex).getRxPower())
             bestIndex = i;
     return bestIndex;
 }
Referenced by processScanConfirm().
dumpAPList()
void inet::ieee80211::Ieee80211AgentSta::dumpAPList (Ieee80211Prim_ScanConfirm * resp) protected virtual
 {
     EV << "Received AP list:\n";
     for (size_t i = 0; i < resp->getBssListArraySize(); i++) {
         const Ieee80211Prim_BssDescription& bssDesc = resp->getBssList(i);
         EV << "    " << i << ". "
            << " address=" << bssDesc.getBSSID()
            << " channel=" << bssDesc.getChannelNumber()
            << " SSID=" << bssDesc.getSSID()
            << " beaconIntvl=" << bssDesc.getBeaconInterval()
            << " rxPower=" << bssDesc.getRxPower()
            << endl;
         // later: supportedRates
     }
 }
Referenced by processScanConfirm().
handleMessage()
void inet::ieee80211::Ieee80211AgentSta::handleMessage (cMessage * msg) override protected virtual
Overridden cSimpleModule method.
 {
     if (msg->isSelfMessage())
         handleTimer(msg);
     else
         handleResponse(msg);
 }
handleResponse()
void inet::ieee80211::Ieee80211AgentSta::handleResponse (cMessage * msg) protected virtual
Handle responses from mgmgt.
 {
     cObject *ctrl = msg->removeControlInfo();
     delete msg;
     EV << "Processing confirmation from mgmt: " << ctrl->getClassName() << "\n";
     if (auto ptr = dynamic_cast<Ieee80211Prim_ScanConfirm *>(ctrl))
         processScanConfirm(ptr);
     else if (auto ptr = dynamic_cast<Ieee80211Prim_AuthenticateConfirm *>(ctrl))
         processAuthenticateConfirm(ptr);
     else if (auto ptr = dynamic_cast<Ieee80211Prim_AssociateConfirm *>(ctrl))
         processAssociateConfirm(ptr);
     else if (auto ptr = dynamic_cast<Ieee80211Prim_ReassociateConfirm *>(ctrl))
         processReassociateConfirm(ptr);
     else if (ctrl)
         throw cRuntimeError("handleResponse(): unrecognized control info class `%s'", ctrl->getClassName());
     else
         throw cRuntimeError("handleResponse(): control info is nullptr");
     delete ctrl;
 }
Referenced by handleMessage().
handleTimer()
void inet::ieee80211::Ieee80211AgentSta::handleTimer (cMessage * msg) protected virtual
Handle timers.
 {
     if (msg->getKind() == MK_STARTUP) {
         EV << "Starting up\n";
         sendScanRequest();
         delete msg;
     }
     else {
         throw cRuntimeError("internal error: unrecognized timer '%s'", msg->getName());
     }
 }
Referenced by handleMessage().
initialize()
void inet::ieee80211::Ieee80211AgentSta::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         // read parameters
         activeScan = par("activeScan");
         probeDelay = par("probeDelay");
         minChannelTime = par("minChannelTime");
         maxChannelTime = par("maxChannelTime");
         authenticationTimeout = par("authenticationTimeout");
         associationTimeout = par("associationTimeout");
         cStringTokenizer tokenizer(par("channelsToScan"));
         const char *token;
         while ((token = tokenizer.nextToken()) != nullptr)
             channelsToScan.push_back(atoi(token));
         cModule *host = getContainingNode(this);
         host->subscribe(l2BeaconLostSignal, this);
         // JcM add: get the default ssid, if there is one.
         defaultSsid = par("defaultSsid").stdstringValue();
         // start up: send scan request
         simtime_t startingTime = par("startingTime");
         if (startingTime < SIMTIME_ZERO)
             startingTime = uniform(SIMTIME_ZERO, maxChannelTime);
         scheduleAfter(startingTime, new cMessage("startUp", MK_STARTUP));
         myIface = nullptr;
     }
     else if (stage == INITSTAGE_LINK_LAYER) {
         IInterfaceTable *ift = findModuleFromPar<IInterfaceTable>(par("interfaceTableModule"), this);
         if (ift) {
             myIface = getContainingNicModule(this);
         }
     }
 }
numInitStages()
virtual int inet::ieee80211::Ieee80211AgentSta::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
processAssociateConfirm()
void inet::ieee80211::Ieee80211AgentSta::processAssociateConfirm (Ieee80211Prim_AssociateConfirm * resp) protected virtual
 {
     if (resp->getResultCode() != PRC_SUCCESS) {
         EV << "Association error\n";
         emit(dropConfirmSignal, PR_ASSOCIATE_CONFIRM);
         // try scanning again, maybe we'll have better luck next time, possibly with a different AP
         EV << "Going back to scanning\n";
         sendScanRequest();
     }
     else {
         EV << "Association successful\n";
         emit(acceptConfirmSignal, PR_ASSOCIATE_CONFIRM);
         // we are happy!
         getContainingNode(this)->bubble("Associated with AP");
         if (prevAP.isUnspecified() || prevAP != resp->getAddress()) {
             emit(l2AssociatedNewApSignal, myIface); // TODO detail: NetworkInterface?
             prevAP = resp->getAddress();
         }
         else
             emit(l2AssociatedOldApSignal, myIface);
     }
 }
Referenced by handleResponse().
processAuthenticateConfirm()
void inet::ieee80211::Ieee80211AgentSta::processAuthenticateConfirm (Ieee80211Prim_AuthenticateConfirm * resp) protected virtual
 {
     if (resp->getResultCode() != PRC_SUCCESS) {
         EV << "Authentication error\n";
         emit(dropConfirmSignal, PR_AUTHENTICATE_CONFIRM);
         // try scanning again, maybe we'll have better luck next time, possibly with a different AP
         EV << "Going back to scanning\n";
         sendScanRequest();
     }
     else {
         EV << "Authentication successful, let's try to associate\n";
         emit(acceptConfirmSignal, PR_AUTHENTICATE_CONFIRM);
         sendAssociateRequest(resp->getAddress());
     }
 }
Referenced by handleResponse().
processReassociateConfirm()
void inet::ieee80211::Ieee80211AgentSta::processReassociateConfirm (Ieee80211Prim_ReassociateConfirm * resp) protected virtual
 {
     // treat the same way as AssociateConfirm
     if (resp->getResultCode() != PRC_SUCCESS) {
         EV << "Reassociation error\n";
         emit(dropConfirmSignal, PR_REASSOCIATE_CONFIRM);
         EV << "Going back to scanning\n";
         sendScanRequest();
     }
     else {
         EV << "Reassociation successful\n";
         emit(l2AssociatedOldApSignal, myIface); // TODO detail: NetworkInterface?
         emit(acceptConfirmSignal, PR_REASSOCIATE_CONFIRM);
         // we are happy!
     }
 }
Referenced by handleResponse().
processScanConfirm()
void inet::ieee80211::Ieee80211AgentSta::processScanConfirm (Ieee80211Prim_ScanConfirm * resp) protected virtual
Processing Confirm primitives.
 {
     // choose best AP
     int bssIndex = -1;
     if (this->defaultSsid == "") {
         // no default ssid, so pick the best one
         bssIndex = chooseBSS(resp);
     }
     else {
         // search if the defaultSsid is in the list, otherwise
         // keep searching.
         for (size_t i = 0; i < resp->getBssListArraySize(); i++) {
             std::string resp_ssid = resp->getBssList(i).getSSID();
             if (resp_ssid == this->defaultSsid) {
                 EV << "found default SSID " << resp_ssid << endl;
                 bssIndex = i;
                 break;
             }
         }
     }
     if (bssIndex == -1) {
         EV << "No (suitable) AP found, continue scanning\n";
         emit(dropConfirmSignal, PR_SCAN_CONFIRM);
         sendScanRequest();
         return;
     }
     dumpAPList(resp);
     emit(acceptConfirmSignal, PR_SCAN_CONFIRM);
     const Ieee80211Prim_BssDescription& bssDesc = resp->getBssList(bssIndex);
     EV << "Chosen AP address=" << bssDesc.getBSSID() << " from list, starting authentication\n";
     sendAuthenticateRequest(bssDesc.getBSSID());
 }
Referenced by handleResponse().
receiveSignal()
void inet::ieee80211::Ieee80211AgentSta::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
Redefined from cListener; called by signal handler.
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     printSignalBanner(signalID, obj, details);
     if (signalID == l2BeaconLostSignal) {
         // TODO should check details if it's about this NIC
         EV << "beacon lost, starting scanning again\n";
         getContainingNode(this)->bubble("Beacon lost!");
 //        sendDisassociateRequest();
         sendScanRequest();
         emit(l2DisassociatedSignal, myIface);
     }
 }
sendAssociateRequest()
void inet::ieee80211::Ieee80211AgentSta::sendAssociateRequest (const MacAddress & address) protected virtual
 {
     EV << "Sending AssociateRequest primitive to mgmt\n";
     Ieee80211Prim_AssociateRequest *req = new Ieee80211Prim_AssociateRequest();
     req->setAddress(address);
     req->setTimeout(associationTimeout);
     emit(sentRequestSignal, PR_ASSOCIATE_REQUEST);
     sendRequest(req);
 }
Referenced by processAuthenticateConfirm().
sendAuthenticateRequest()
void inet::ieee80211::Ieee80211AgentSta::sendAuthenticateRequest (const MacAddress & address) protected virtual
 {
     EV << "Sending AuthenticateRequest primitive to mgmt\n";
     Ieee80211Prim_AuthenticateRequest *req = new Ieee80211Prim_AuthenticateRequest();
     req->setAddress(address);
     req->setTimeout(authenticationTimeout);
     emit(sentRequestSignal, PR_AUTHENTICATE_REQUEST);
     sendRequest(req);
 }
Referenced by processScanConfirm().
sendDeauthenticateRequest()
void inet::ieee80211::Ieee80211AgentSta::sendDeauthenticateRequest (const MacAddress & address, Ieee80211ReasonCode reasonCode) protected virtual
 {
     EV << "Sending DeauthenticateRequest primitive to mgmt\n";
     Ieee80211Prim_DeauthenticateRequest *req = new Ieee80211Prim_DeauthenticateRequest();
     req->setAddress(address);
     req->setReasonCode(reasonCode);
     emit(sentRequestSignal, PR_DEAUTHENTICATE_REQUEST);
     sendRequest(req);
 }
sendDisassociateRequest()
void inet::ieee80211::Ieee80211AgentSta::sendDisassociateRequest (const MacAddress & address, Ieee80211ReasonCode reasonCode) protected virtual
 {
     EV << "Sending DisassociateRequest primitive to mgmt\n";
     Ieee80211Prim_DisassociateRequest *req = new Ieee80211Prim_DisassociateRequest();
     req->setAddress(address);
     req->setReasonCode(reasonCode);
     emit(sentRequestSignal, PR_DISASSOCIATE_REQUEST);
     sendRequest(req);
 }
sendReassociateRequest()
void inet::ieee80211::Ieee80211AgentSta::sendReassociateRequest (const MacAddress & address) protected virtual
 {
     EV << "Sending ReassociateRequest primitive to mgmt\n";
     Ieee80211Prim_ReassociateRequest *req = new Ieee80211Prim_ReassociateRequest();
     req->setAddress(address);
     req->setTimeout(associationTimeout);
     emit(sentRequestSignal, PR_REASSOCIATE_REQUEST);
     sendRequest(req);
 }
sendRequest()
void inet::ieee80211::Ieee80211AgentSta::sendRequest (Ieee80211PrimRequest * req) protected virtual
 {
     cMessage *msg = new cMessage(req->getClassName());
     msg->setControlInfo(req);
     send(msg, "mgmtOut");
 }
Referenced by sendAssociateRequest(), sendAuthenticateRequest(), sendDeauthenticateRequest(), sendDisassociateRequest(), sendReassociateRequest(), and sendScanRequest().
sendScanRequest()
void inet::ieee80211::Ieee80211AgentSta::sendScanRequest () protected virtual
Sending of Request primitives.
 {
     EV << "Sending ScanRequest primitive to mgmt\n";
     Ieee80211Prim_ScanRequest *req = new Ieee80211Prim_ScanRequest();
     req->setBSSType(BSSTYPE_INFRASTRUCTURE);
     req->setActiveScan(activeScan);
     req->setProbeDelay(probeDelay);
     req->setMinChannelTime(minChannelTime);
     req->setMaxChannelTime(maxChannelTime);
     req->setChannelListArraySize(channelsToScan.size());
     for (size_t i = 0; i < channelsToScan.size(); i++)
         req->setChannelList(i, channelsToScan[i]);
     // TODO BSSID, SSID are left at default ("any")
     emit(sentRequestSignal, PR_SCAN_REQUEST);
     sendRequest(req);
 }
Referenced by handleTimer(), processAssociateConfirm(), processAuthenticateConfirm(), processReassociateConfirm(), processScanConfirm(), and receiveSignal().
Member Data Documentation
acceptConfirmSignal
simsignal_t inet::ieee80211::Ieee80211AgentSta::acceptConfirmSignal = registerSignal("acceptConfirm") static protected
Referenced by processAssociateConfirm(), processAuthenticateConfirm(), processReassociateConfirm(), and processScanConfirm().
activeScan
bool inet::ieee80211::Ieee80211AgentSta::activeScan = false protected
Referenced by initialize(), and sendScanRequest().
associationTimeout
simtime_t inet::ieee80211::Ieee80211AgentSta::associationTimeout protected
Referenced by initialize(), sendAssociateRequest(), and sendReassociateRequest().
authenticationTimeout
simtime_t inet::ieee80211::Ieee80211AgentSta::authenticationTimeout protected
Referenced by initialize(), and sendAuthenticateRequest().
channelsToScan
std::vector<int> inet::ieee80211::Ieee80211AgentSta::channelsToScan protected
Referenced by initialize(), and sendScanRequest().
defaultSsid
std::string inet::ieee80211::Ieee80211AgentSta::defaultSsid protected
Referenced by initialize(), and processScanConfirm().
dropConfirmSignal
simsignal_t inet::ieee80211::Ieee80211AgentSta::dropConfirmSignal = registerSignal("dropConfirm") static protected
Referenced by processAssociateConfirm(), processAuthenticateConfirm(), processReassociateConfirm(), and processScanConfirm().
maxChannelTime
simtime_t inet::ieee80211::Ieee80211AgentSta::maxChannelTime protected
Referenced by initialize(), and sendScanRequest().
minChannelTime
simtime_t inet::ieee80211::Ieee80211AgentSta::minChannelTime protected
Referenced by initialize(), and sendScanRequest().
myIface
NetworkInterface* inet::ieee80211::Ieee80211AgentSta::myIface = nullptr protected
Referenced by initialize(), processAssociateConfirm(), processReassociateConfirm(), and receiveSignal().
prevAP
MacAddress inet::ieee80211::Ieee80211AgentSta::prevAP protected
Referenced by processAssociateConfirm().
probeDelay
simtime_t inet::ieee80211::Ieee80211AgentSta::probeDelay protected
Referenced by initialize(), and sendScanRequest().
sentRequestSignal
simsignal_t inet::ieee80211::Ieee80211AgentSta::sentRequestSignal = registerSignal("sentRequest") static protected
Referenced by sendAssociateRequest(), sendAuthenticateRequest(), sendDeauthenticateRequest(), sendDisassociateRequest(), sendReassociateRequest(), and sendScanRequest().
The documentation for this class was generated from the following files:
Ieee80211AgentSta.h
Ieee80211AgentSta.cc