INET Framework for OMNeT++/OMNEST: inet::IGeographicCoordinateSystem Class Reference
inet::IGeographicCoordinateSystem Class Reference abstract
#include <GeographicCoordinateSystem.h>
Public Member Functions
virtual GeoCoord getScenePosition () const =0
virtual Quaternion getSceneOrientation () const =0
virtual Coord computeSceneCoordinate (const GeoCoord &geographicCoordinate) const =0
virtual GeoCoord computeGeographicCoordinate (const Coord &sceneCoordinate) const =0
Member Function Documentation
computeGeographicCoordinate()
virtual GeoCoord inet::IGeographicCoordinateSystem::computeGeographicCoordinate (const Coord & sceneCoordinate) const pure virtual
Implemented in inet::SimpleGeographicCoordinateSystem.
Referenced by inet::physicalenvironment::PhysicalEnvironment::convertPoints().
computeSceneCoordinate()
virtual Coord inet::IGeographicCoordinateSystem::computeSceneCoordinate (const GeoCoord & geographicCoordinate) const pure virtual
Implemented in inet::SimpleGeographicCoordinateSystem.
Referenced by inet::physicalenvironment::PhysicalEnvironment::convertPoints(), and inet::physicalenvironment::PhysicalEnvironment::parseObjects().
getSceneOrientation()
virtual Quaternion inet::IGeographicCoordinateSystem::getSceneOrientation () const pure virtual
Implemented in inet::SimpleGeographicCoordinateSystem.
getScenePosition()
virtual GeoCoord inet::IGeographicCoordinateSystem::getScenePosition () const pure virtual
Implemented in inet::SimpleGeographicCoordinateSystem.
The documentation for this class was generated from the following file:
GeographicCoordinateSystem.h