INET Framework for OMNeT++/OMNEST: inet::sctp::SctpShutdownAckChunk Class Reference
inet::sctp::SctpShutdownAckChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:211 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpShutdownAckChunk (const char *name=nullptr)
SctpShutdownAckChunk (const SctpShutdownAckChunk &other)
virtual ~SctpShutdownAckChunk ()
SctpShutdownAckChunk & operator= (const SctpShutdownAckChunk &other)
virtual SctpShutdownAckChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpShutdownAckChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Private Member Functions
void copy (const SctpShutdownAckChunk &other)
Additional Inherited Members
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:211 by opp_msgtool.
class SctpShutdownAckChunk extends SctpChunk
{
}
Constructor & Destructor Documentation
SctpShutdownAckChunk() [1/2]
inet::sctp::SctpShutdownAckChunk::SctpShutdownAckChunk (const char * name = nullptr)
SctpShutdownAckChunk() [2/2]
inet::sctp::SctpShutdownAckChunk::SctpShutdownAckChunk (const SctpShutdownAckChunk & other)
~SctpShutdownAckChunk()
virtual inet::sctp::SctpShutdownAckChunk::~SctpShutdownAckChunk () virtual
Member Function Documentation
copy()
void inet::sctp::SctpShutdownAckChunk::copy (const SctpShutdownAckChunk & other) private
dup()
virtual SctpShutdownAckChunk* inet::sctp::SctpShutdownAckChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpShutdownAckChunk(*this);}
Referenced by inet::sctp::SctpAssociation::retransmitShutdownAck(), and inet::sctp::SctpAssociation::sendShutdownAck().
operator=()
SctpShutdownAckChunk& inet::sctp::SctpShutdownAckChunk::operator= (const SctpShutdownAckChunk & other)
operator==()
bool inet::sctp::SctpShutdownAckChunk::operator== (const SctpShutdownAckChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpShutdownAckChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpShutdownAckChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
The documentation for this class was generated from the following file:
SctpHeader_m.h