INET Framework for OMNeT++/OMNEST: inet::NodeStatus Class Reference
inet::NodeStatus Class Reference
Keeps track of the status of network node (up, down, etc.) for other modules, and also displays it as a small overlay icon on this module and on the module of the network node.
#include <NodeStatus.h>
Public Types
enum State { UP, DOWN, GOING_UP, GOING_DOWN }
Public Member Functions
virtual State getState () const
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Static Public Attributes
static simsignal_t nodeStatusChangedSignal = registerSignal("nodeStatusChanged")
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *msg) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void setState (State state)
virtual void refreshDisplay () const override
Static Protected Member Functions
static State getStateByName (const char *name)
Private Attributes
State state
Detailed Description
Keeps track of the status of network node (up, down, etc.) for other modules, and also displays it as a small overlay icon on this module and on the module of the network node.
Other modules can obtain the network node's status by calling the getState() method.
See NED file for more information.
Member Enumeration Documentation
State
enum inet::NodeStatus::State
Enumerator
UP
DOWN
GOING_UP
GOING_DOWN
 { UP, DOWN, GOING_UP, GOING_DOWN };
Member Function Documentation
getState()
virtual State inet::NodeStatus::getState () const inline virtual
 { return state; }
Referenced by inet::Define_Module(), inet::power::SimpleEpEnergyManagement::executeNodeOperation(), inet::power::SimpleCcBattery::executeNodeOperation(), inet::power::SimpleEpEnergyStorage::executeNodeOperation(), inet::OperationalMixin< cSimpleModule >::getInitialOperationalState(), handleOperationStage(), inet::rtp::Rtp::initialize(), inet::bgp::Bgp::initialize(), inet::TcpGenericServerApp::initialize(), inet::tcp::TcpLwip::initialize(), inet::VoipStreamReceiver::initialize(), inet::rtp::Rtcp::initialize(), inet::VoipStreamSender::initialize(), inet::SimpleVoipSender::initialize(), inet::Icmpv6::initialize(), inet::SctpClient::initialize(), inet::SctpServer::initialize(), inet::SctpPeer::initialize(), inet::SimpleVoipReceiver::initialize(), inet::Ipv6Tunneling::initialize(), inet::Ipv4RoutingTable::initialize(), inet::Ipv6NeighbourDiscovery::initialize(), inet::NetworkInterface::initialize(), inet::Ipv6::initialize(), and inet::power::SimpleEpEnergyManagement::scheduleLifecycleOperationTimer().
getStateByName()
NodeStatus::State inet::NodeStatus::getStateByName (const char * name) static protected
 {
     std::string temp = name;
     std::transform(temp.begin(), temp.end(), temp.begin(), ::toupper);
     cEnum *e = cEnum::get("inet::NodeStatus");
     int state = e->lookup(temp.c_str(), -1);
     if (state == -1)
         throw cRuntimeError("Invalid state name '%s'", name);
     return static_cast<State>(state);
 }
Referenced by initialize().
handleMessage()
virtual void inet::NodeStatus::handleMessage (cMessage * msg) inline override protected virtual
 { throw cRuntimeError("This module doesn't handle messages"); }
handleOperationStage()
bool inet::NodeStatus::handleOperationStage (LifecycleOperation * operation, IDoneCallback * doneCallback) override protected virtual
Perform one stage of a lifecycle operation.
Processing may be done entirely within this method, or may be a longer process that involves nonzero simulation time or several events, and is triggered by this method call.
Return value: true = "done"; false = "not yet done, will invoke doneCallback when done"
Implements inet::ILifecycle.
 {
     Enter_Method("handleOperationStage");
     int opStage = operation->getCurrentStage();
     cModule *node = getContainingNode(this);
     if (dynamic_cast<ModuleStartOperation *>(operation)) {
         if (opStage == 0) {
             EV << node->getFullPath() << " starting up" << endl;
             if (getState() != DOWN)
                 throw cRuntimeError("Current node status is not 'down' at ModuleStartOperation");
             setState(GOING_UP);
         }
         // NOTE: this is not an 'else if' so that it works if there's only 1 stage
         if (opStage == operation->getNumStages() - 1) {
             ASSERT(getState() == GOING_UP);
             setState(UP);
             EV << node->getFullPath() << " started" << endl;
             node->bubble("Node started");
         }
     }
     else if (dynamic_cast<ModuleStopOperation *>(operation)) {
         if (opStage == 0) {
             EV << node->getFullPath() << " shutting down" << endl;
             if (getState() != UP)
                 throw cRuntimeError("Current node status is not 'up' at ModuleStopOperation");
             setState(GOING_DOWN);
         }
         // NOTE: this is not an 'else if' so that it works if there's only 1 stage
         if (opStage == operation->getNumStages() - 1) {
             ASSERT(getState() == GOING_DOWN);
             setState(DOWN);
             EV << node->getFullPath() << " shut down" << endl;
             node->bubble("Node shut down");
         }
     }
     else if (dynamic_cast<ModuleCrashOperation *>(operation)) {
         if (opStage == 0) {
             EV << node->getFullPath() << " crashing" << endl;
             if (getState() != UP)
                 throw cRuntimeError("Current node status is not 'up' at ModuleCrashOperation");
             setState(GOING_DOWN);
         }
         // NOTE: this is not an 'else if' so that it works if there's only 1 stage
         if (opStage == operation->getNumStages() - 1) {
             ASSERT(getState() == GOING_DOWN);
             setState(DOWN);
             EV << node->getFullPath() << " crashed" << endl;
             node->bubble("Node crashed");
         }
     }
     return true;
 }
initialize()
void inet::NodeStatus::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         state = getStateByName(par("initialStatus"));
         WATCH(state);
     }
 }
numInitStages()
virtual int inet::NodeStatus::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
refreshDisplay()
void inet::NodeStatus::refreshDisplay () const override protected virtual
 {
     const char *icon;
     const char *text;
     switch (state) {
         case UP:
             icon = "";
             text = "up";
             break;
         case DOWN:
             icon = "status/cross";
             text = "down";
             break;
         case GOING_UP:
             icon = "status/execute";
             text = "going up";
             break;
         case GOING_DOWN:
             icon = "status/execute";
             text = "going down";
             break;
         default:
             throw cRuntimeError("Unknown status");
     }
     auto& displayString = getDisplayString();
     displayString.setTagArg("t", 0, text);
     cModule *node = getContainingNode(this);
     if (*icon) {
         displayString.setTagArg("i2", 0, icon);
         node->getDisplayString().setTagArg("i2", 0, icon);
     }
     else {
         displayString.removeTag("i2");
         node->getDisplayString().removeTag("i2");
     }
 }
setState()
void inet::NodeStatus::setState (State state) protected virtual
 {
     state = s;
     emit(nodeStatusChangedSignal, this);
 }
Referenced by handleOperationStage().
Member Data Documentation
nodeStatusChangedSignal
simsignal_t inet::NodeStatus::nodeStatusChangedSignal = registerSignal("nodeStatusChanged") static
Referenced by setState().
state
State inet::NodeStatus::state private
Referenced by getStateByName(), initialize(), refreshDisplay(), and setState().
The documentation for this class was generated from the following files:
NodeStatus.h
NodeStatus.cc