INET Framework for OMNeT++/OMNEST: inet::bgp::BgpUpdatePathAttributesAggregator Class Reference
inet::bgp::BgpUpdatePathAttributesAggregator Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:185 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpUpdatePathAttributesAggregator ()
BgpUpdatePathAttributesAggregator (const BgpUpdatePathAttributesAggregator &other)
virtual ~BgpUpdatePathAttributesAggregator ()
BgpUpdatePathAttributesAggregator & operator= (const BgpUpdatePathAttributesAggregator &other)
virtual BgpUpdatePathAttributesAggregator * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getAsNumber () const
virtual void setAsNumber (uint16_t asNumber)
virtual const ::inet::Ipv4Address & getBgpSpeaker () const
virtual ::inet::Ipv4Address & getBgpSpeakerForUpdate ()
virtual void setBgpSpeaker (const ::inet::Ipv4Address &bgpSpeaker)
Public Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
BgpUpdatePathAttributes ()
BgpUpdatePathAttributes (const BgpUpdatePathAttributes &other)
virtual ~BgpUpdatePathAttributes ()
BgpUpdatePathAttributes & operator= (const BgpUpdatePathAttributes &other)
virtual bool getOptionalBit () const
virtual void setOptionalBit (bool optionalBit)
virtual bool getTransitiveBit () const
virtual void setTransitiveBit (bool transitiveBit)
virtual bool getPartialBit () const
virtual void setPartialBit (bool partialBit)
virtual bool getExtendedLengthBit () const
virtual void setExtendedLengthBit (bool extendedLengthBit)
virtual unsigned short getReserved () const
virtual void setReserved (unsigned short reserved)
virtual BgpUpdateAttributeTypeCode getTypeCode () const
virtual void setTypeCode (BgpUpdateAttributeTypeCode typeCode)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const BgpUpdatePathAttributesAggregator &)=delete
Protected Member Functions inherited from inet::bgp::BgpUpdatePathAttributes
bool operator== (const BgpUpdatePathAttributes &)=delete
Protected Attributes
uint16_t asNumber = 0
::inet::Ipv4Address bgpSpeaker
Protected Attributes inherited from inet::bgp::BgpUpdatePathAttributes
bool optionalBit = false
bool transitiveBit = false
bool partialBit = false
bool extendedLengthBit = false
unsigned short reserved = 0
BgpUpdateAttributeTypeCode typeCode = static_cast<inet::bgp::BgpUpdateAttributeTypeCode>(-1)
unsigned short length = 0
Private Member Functions
void copy (const BgpUpdatePathAttributesAggregator &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:185 by opp_msgtool.
class BgpUpdatePathAttributesAggregator extends BgpUpdatePathAttributes
{
    typeCode = AGGREGATOR;
    optionalBit = true;
    transitiveBit = true;
    length = 6;
    uint16_t asNumber;
    Ipv4Address bgpSpeaker;
}
Constructor & Destructor Documentation
BgpUpdatePathAttributesAggregator() [1/2]
inet::bgp::BgpUpdatePathAttributesAggregator::BgpUpdatePathAttributesAggregator ()
BgpUpdatePathAttributesAggregator() [2/2]
inet::bgp::BgpUpdatePathAttributesAggregator::BgpUpdatePathAttributesAggregator (const BgpUpdatePathAttributesAggregator & other)
~BgpUpdatePathAttributesAggregator()
virtual inet::bgp::BgpUpdatePathAttributesAggregator::~BgpUpdatePathAttributesAggregator () virtual
Member Function Documentation
copy()
void inet::bgp::BgpUpdatePathAttributesAggregator::copy (const BgpUpdatePathAttributesAggregator & other) private
dup()
virtual BgpUpdatePathAttributesAggregator* inet::bgp::BgpUpdatePathAttributesAggregator::dup () const inline override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
 {return new BgpUpdatePathAttributesAggregator(*this);}
getAsNumber()
virtual uint16_t inet::bgp::BgpUpdatePathAttributesAggregator::getAsNumber () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getBgpSpeaker()
virtual const ::inet::Ipv4Address& inet::bgp::BgpUpdatePathAttributesAggregator::getBgpSpeaker () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getBgpSpeakerForUpdate()
virtual ::inet::Ipv4Address& inet::bgp::BgpUpdatePathAttributesAggregator::getBgpSpeakerForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<BgpUpdatePathAttributesAggregator*>(this)->getBgpSpeaker());}
operator=()
BgpUpdatePathAttributesAggregator& inet::bgp::BgpUpdatePathAttributesAggregator::operator= (const BgpUpdatePathAttributesAggregator & other)
operator==()
bool inet::bgp::BgpUpdatePathAttributesAggregator::operator== (const BgpUpdatePathAttributesAggregator &) protected delete
parsimPack()
virtual void inet::bgp::BgpUpdatePathAttributesAggregator::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimPacking().
parsimUnpack()
virtual void inet::bgp::BgpUpdatePathAttributesAggregator::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::bgp::BgpUpdatePathAttributes.
Referenced by inet::bgp::doParsimUnpacking().
setAsNumber()
virtual void inet::bgp::BgpUpdatePathAttributesAggregator::setAsNumber (uint16_t asNumber) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setBgpSpeaker()
virtual void inet::bgp::BgpUpdatePathAttributesAggregator::setBgpSpeaker (const ::inet::Ipv4Address & bgpSpeaker) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
asNumber
uint16_t inet::bgp::BgpUpdatePathAttributesAggregator::asNumber = 0 protected
bgpSpeaker
::inet::Ipv4Address inet::bgp::BgpUpdatePathAttributesAggregator::bgpSpeaker protected
The documentation for this class was generated from the following file:
BgpHeader_m.h