INET Framework for OMNeT++/OMNEST: inet::physicallayer::ITransmitter Class Reference
inet::physicallayer::ITransmitter Class Reference abstract
This interface represents a physical device (a part of the radio) which converts packets into electric signals.
#include <ITransmitter.h>
Public Member Functions
virtual W getMaxPower () const =0
Returns the maximum transmission power above which no transmission is ever transmitted.
virtual m getMaxCommunicationRange () const =0
Returns the maximum communication range.
virtual m getMaxInterferenceRange () const =0
Returns the maximum interference range.
virtual const ITransmission * createTransmission (const IRadio *transmitter, const Packet *packet, const simtime_t startTime) const =0
Returns a transmission which describes the radio signal corresponding to the provided packet.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents a physical device (a part of the radio) which converts packets into electric signals.
Member Function Documentation
createTransmission()
virtual const ITransmission* inet::physicallayer::ITransmitter::createTransmission (const IRadio * transmitter, const Packet * packet, const simtime_t startTime) const pure virtual
Returns a transmission which describes the radio signal corresponding to the provided packet.
This function never returns nullptr.
Implemented in inet::physicallayer::Ieee802154UwbIrTransmitter, inet::physicallayer::Ieee80211UnitDiskTransmitter, inet::physicallayer::NoiseDimensionalTransmitter, inet::physicallayer::Ieee80211DimensionalTransmitter, inet::physicallayer::Ieee80211ScalarTransmitter, inet::physicallayer::Ieee80211LayeredOfdmTransmitter, inet::physicallayer::ApskLayeredTransmitter, inet::physicallayer::UnitDiskTransmitter, inet::physicallayer::ApskDimensionalTransmitter, inet::physicallayer::Ieee802154NarrowbandDimensionalTransmitter, inet::physicallayer::ApskScalarTransmitter, and inet::physicallayer::Ieee802154NarrowbandScalarTransmitter.
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), and inet::physicallayer::RadioMedium::createTransmitterSignal().
getMaxCommunicationRange()
virtual m inet::physicallayer::ITransmitter::getMaxCommunicationRange () const pure virtual
Returns the maximum communication range.
Returns a value in the range [0, +infinity] or NaN if unspecified.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmTransmitter, inet::physicallayer::ApskLayeredTransmitter, inet::physicallayer::UnitDiskTransmitter, inet::physicallayer::Ieee80211UnitDiskTransmitter, and inet::physicallayer::TransmitterBase.
Referenced by inet::physicallayer::MediumLimitCache::getMaxCommunicationRange().
getMaxInterferenceRange()
virtual m inet::physicallayer::ITransmitter::getMaxInterferenceRange () const pure virtual
Returns the maximum interference range.
Returns a value in the range [0, +infinity] or NaN if unspecified.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmTransmitter, inet::physicallayer::ApskLayeredTransmitter, inet::physicallayer::UnitDiskTransmitter, inet::physicallayer::Ieee80211UnitDiskTransmitter, and inet::physicallayer::TransmitterBase.
Referenced by inet::physicallayer::MediumLimitCache::getMaxInterferenceRange().
getMaxPower()
virtual W inet::physicallayer::ITransmitter::getMaxPower () const pure virtual
Returns the maximum transmission power above which no transmission is ever transmitted.
Returns a value in the range [0, +infinity] or NaN if unspecified.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmTransmitter, inet::physicallayer::ApskLayeredTransmitter, inet::physicallayer::FlatTransmitterBase, and inet::physicallayer::TransmitterBase.
Referenced by inet::physicallayer::MediumLimitCache::getMaxCommunicationRange(), and inet::physicallayer::MediumLimitCache::getMaxInterferenceRange().
The documentation for this class was generated from the following file:
ITransmitter.h