INET Framework for OMNeT++/OMNEST: inet::sctp::SctpInitChunk Class Reference
inet::sctp::SctpInitChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:43 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpInitChunk (const char *name=nullptr)
SctpInitChunk (const SctpInitChunk &other)
virtual ~SctpInitChunk ()
SctpInitChunk & operator= (const SctpInitChunk &other)
virtual SctpInitChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getInitTag () const
virtual void setInitTag (uint32_t initTag)
virtual uint32_t getA_rwnd () const
virtual void setA_rwnd (uint32_t a_rwnd)
virtual uint16_t getNoOutStreams () const
virtual void setNoOutStreams (uint16_t noOutStreams)
virtual uint16_t getNoInStreams () const
virtual void setNoInStreams (uint16_t noInStreams)
virtual uint32_t getInitTsn () const
virtual void setInitTsn (uint32_t initTsn)
virtual bool getForwardTsn () const
virtual void setForwardTsn (bool forwardTsn)
virtual bool getIpv4Supported () const
virtual void setIpv4Supported (bool ipv4Supported)
virtual bool getIpv6Supported () const
virtual void setIpv6Supported (bool ipv6Supported)
virtual void setAddressesArraySize (size_t size)
virtual size_t getAddressesArraySize () const
virtual const ::inet::L3Address & getAddresses (size_t k) const
virtual ::inet::L3Address & getAddressesForUpdate (size_t k)
virtual void setAddresses (size_t k, const ::inet::L3Address &addresses)
virtual void insertAddresses (size_t k, const ::inet::L3Address &addresses)
void insertAddresses (const ::inet::L3Address &addresses)
virtual void appendAddresses (const ::inet::L3Address &addresses)
virtual void eraseAddresses (size_t k)
virtual void setUnrecognizedParametersArraySize (size_t size)
virtual size_t getUnrecognizedParametersArraySize () const
virtual uint8_t getUnrecognizedParameters (size_t k) const
virtual void setUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters)
virtual void insertUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters)
void insertUnrecognizedParameters (uint8_t unrecognizedParameters)
virtual void appendUnrecognizedParameters (uint8_t unrecognizedParameters)
virtual void eraseUnrecognizedParameters (size_t k)
virtual uint32_t getMsg_rwnd () const
virtual void setMsg_rwnd (uint32_t msg_rwnd)
virtual void setSctpChunkTypesArraySize (size_t size)
virtual size_t getSctpChunkTypesArraySize () const
virtual uint16_t getSctpChunkTypes (size_t k) const
virtual void setSctpChunkTypes (size_t k, uint16_t sctpChunkTypes)
virtual void insertSctpChunkTypes (size_t k, uint16_t sctpChunkTypes)
void insertSctpChunkTypes (uint16_t sctpChunkTypes)
virtual void appendSctpChunkTypes (uint16_t sctpChunkTypes)
virtual void eraseSctpChunkTypes (size_t k)
virtual void setSepChunksArraySize (size_t size)
virtual size_t getSepChunksArraySize () const
virtual uint16_t getSepChunks (size_t k) const
virtual void setSepChunks (size_t k, uint16_t sepChunks)
virtual void insertSepChunks (size_t k, uint16_t sepChunks)
void insertSepChunks (uint16_t sepChunks)
virtual void appendSepChunks (uint16_t sepChunks)
virtual void eraseSepChunks (size_t k)
virtual void setHmacTypesArraySize (size_t size)
virtual size_t getHmacTypesArraySize () const
virtual uint16_t getHmacTypes (size_t k) const
virtual void setHmacTypes (size_t k, uint16_t hmacTypes)
virtual void insertHmacTypes (size_t k, uint16_t hmacTypes)
void insertHmacTypes (uint16_t hmacTypes)
virtual void appendHmacTypes (uint16_t hmacTypes)
virtual void eraseHmacTypes (size_t k)
virtual void setRandomArraySize (size_t size)
virtual size_t getRandomArraySize () const
virtual uint8_t getRandom (size_t k) const
virtual void setRandom (size_t k, uint8_t random)
virtual void insertRandom (size_t k, uint8_t random)
void insertRandom (uint8_t random)
virtual void appendRandom (uint8_t random)
virtual void eraseRandom (size_t k)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpInitChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
uint32_t initTag = 0
uint32_t a_rwnd = 0
uint16_t noOutStreams = 0
uint16_t noInStreams = 0
uint32_t initTsn = 0
bool forwardTsn = false
bool ipv4Supported = false
bool ipv6Supported = false
::inet::L3Address * addresses = nullptr
size_t addresses_arraysize = 0
uint8_t * unrecognizedParameters = nullptr
size_t unrecognizedParameters_arraysize = 0
uint32_t msg_rwnd = 0
uint16_t * sctpChunkTypes = nullptr
size_t sctpChunkTypes_arraysize = 0
uint16_t * sepChunks = nullptr
size_t sepChunks_arraysize = 0
uint16_t * hmacTypes = nullptr
size_t hmacTypes_arraysize = 0
uint8_t * random = nullptr
size_t random_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpInitChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:43 by opp_msgtool.
class SctpInitChunk extends SctpChunk
{
    // Initiate Tag
    uint32_t initTag;
    // Advertised Receiver Window
    uint32_t a_rwnd;
    // Number of Outbound Streams
    uint16_t noOutStreams;
    // Number of Inbound Streams
    uint16_t noInStreams;
    // Initial TSN
    uint32_t initTsn;
    bool forwardTsn;
    bool ipv4Supported;
    bool ipv6Supported;
    L3Address addresses[];
    uint8_t unrecognizedParameters[]; //Will be filled by the Parser, if unrecognized Parameters arrive.
    uint32_t msg_rwnd;
    uint16_t sctpChunkTypes[]; //Chunk list parameter, i.e. for SCTP AUTH
    uint16_t sepChunks[]; //Supported extensions parameter, i.e. for StreamReset
    uint16_t hmacTypes[]; //HMAC Identifier for HMAC algorithm parameter
    uint8_t random[]; //Random Parameter for SCTP AUTH
}
Constructor & Destructor Documentation
SctpInitChunk() [1/2]
inet::sctp::SctpInitChunk::SctpInitChunk (const char * name = nullptr)
SctpInitChunk() [2/2]
inet::sctp::SctpInitChunk::SctpInitChunk (const SctpInitChunk & other)
~SctpInitChunk()
virtual inet::sctp::SctpInitChunk::~SctpInitChunk () virtual
Member Function Documentation
appendAddresses()
virtual void inet::sctp::SctpInitChunk::appendAddresses (const ::inet::L3Address & addresses) virtual
appendHmacTypes()
virtual void inet::sctp::SctpInitChunk::appendHmacTypes (uint16_t hmacTypes) virtual
appendRandom()
virtual void inet::sctp::SctpInitChunk::appendRandom (uint8_t random) virtual
appendSctpChunkTypes()
virtual void inet::sctp::SctpInitChunk::appendSctpChunkTypes (uint16_t sctpChunkTypes) virtual
appendSepChunks()
virtual void inet::sctp::SctpInitChunk::appendSepChunks (uint16_t sepChunks) virtual
appendUnrecognizedParameters()
virtual void inet::sctp::SctpInitChunk::appendUnrecognizedParameters (uint8_t unrecognizedParameters) virtual
copy()
void inet::sctp::SctpInitChunk::copy (const SctpInitChunk & other) private
dup()
virtual SctpInitChunk* inet::sctp::SctpInitChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpInitChunk(*this);}
Referenced by inet::sctp::SctpAssociation::retransmitInit(), and inet::sctp::SctpAssociation::sendInit().
eraseAddresses()
virtual void inet::sctp::SctpInitChunk::eraseAddresses (size_t k) virtual
eraseHmacTypes()
virtual void inet::sctp::SctpInitChunk::eraseHmacTypes (size_t k) virtual
eraseRandom()
virtual void inet::sctp::SctpInitChunk::eraseRandom (size_t k) virtual
eraseSctpChunkTypes()
virtual void inet::sctp::SctpInitChunk::eraseSctpChunkTypes (size_t k) virtual
eraseSepChunks()
virtual void inet::sctp::SctpInitChunk::eraseSepChunks (size_t k) virtual
eraseUnrecognizedParameters()
virtual void inet::sctp::SctpInitChunk::eraseUnrecognizedParameters (size_t k) virtual
getA_rwnd()
virtual uint32_t inet::sctp::SctpInitChunk::getA_rwnd () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddresses()
virtual const ::inet::L3Address& inet::sctp::SctpInitChunk::getAddresses (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressesArraySize()
virtual size_t inet::sctp::SctpInitChunk::getAddressesArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressesForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpInitChunk::getAddressesForUpdate (size_t k) inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpInitChunk*>(this)->getAddresses(k));}
getForwardTsn()
virtual bool inet::sctp::SctpInitChunk::getForwardTsn () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getHmacTypes()
virtual uint16_t inet::sctp::SctpInitChunk::getHmacTypes (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getHmacTypesArraySize()
virtual size_t inet::sctp::SctpInitChunk::getHmacTypesArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getInitTag()
virtual uint32_t inet::sctp::SctpInitChunk::getInitTag () const virtual
Referenced by inet::sctp::SctpNatHook::datagramForwardHook(), inet::sctp::SctpNatHook::datagramPreRoutingHook(), inet::sctp::SctpAssociation::processInitArrived(), inet::sctp::Sctp::sendAbortFromMain(), inet::sctp::SctpAssociation::sendInit(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getInitTsn()
virtual uint32_t inet::sctp::SctpInitChunk::getInitTsn () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), inet::sctp::SctpAssociation::sendInit(), inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getIpv4Supported()
virtual bool inet::sctp::SctpInitChunk::getIpv4Supported () const virtual
Referenced by inet::sctp::SctpAssociation::sendInit(), and inet::sctp::SctpHeaderSerializer::serialize().
getIpv6Supported()
virtual bool inet::sctp::SctpInitChunk::getIpv6Supported () const virtual
Referenced by inet::sctp::SctpAssociation::sendInit(), and inet::sctp::SctpHeaderSerializer::serialize().
getMsg_rwnd()
virtual uint32_t inet::sctp::SctpInitChunk::getMsg_rwnd () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived().
getNoInStreams()
virtual uint16_t inet::sctp::SctpInitChunk::getNoInStreams () const virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getNoOutStreams()
virtual uint16_t inet::sctp::SctpInitChunk::getNoOutStreams () const virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck(), and inet::sctp::SctpHeaderSerializer::serialize().
getRandom()
virtual uint8_t inet::sctp::SctpInitChunk::getRandom (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::sendInit(), and inet::sctp::SctpHeaderSerializer::serialize().
getRandomArraySize()
virtual size_t inet::sctp::SctpInitChunk::getRandomArraySize () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getSctpChunkTypes()
virtual uint16_t inet::sctp::SctpInitChunk::getSctpChunkTypes (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSctpChunkTypesArraySize()
virtual size_t inet::sctp::SctpInitChunk::getSctpChunkTypesArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), inet::sctp::SctpAssociation::sendInit(), and inet::sctp::SctpHeaderSerializer::serialize().
getSepChunks()
virtual uint16_t inet::sctp::SctpInitChunk::getSepChunks (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSepChunksArraySize()
virtual size_t inet::sctp::SctpInitChunk::getSepChunksArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::processInitArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getUnrecognizedParameters()
virtual uint8_t inet::sctp::SctpInitChunk::getUnrecognizedParameters (size_t k) const virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
getUnrecognizedParametersArraySize()
virtual size_t inet::sctp::SctpInitChunk::getUnrecognizedParametersArraySize () const virtual
Referenced by inet::sctp::SctpAssociation::sendInitAck().
insertAddresses() [1/2]
void inet::sctp::SctpInitChunk::insertAddresses (const ::inet::L3Address & addresses) inline
 {appendAddresses(addresses);}
insertAddresses() [2/2]
virtual void inet::sctp::SctpInitChunk::insertAddresses (size_t k, const ::inet::L3Address & addresses) virtual
insertHmacTypes() [1/2]
virtual void inet::sctp::SctpInitChunk::insertHmacTypes (size_t k, uint16_t hmacTypes) virtual
insertHmacTypes() [2/2]
void inet::sctp::SctpInitChunk::insertHmacTypes (uint16_t hmacTypes) inline
 {appendHmacTypes(hmacTypes);}
insertRandom() [1/2]
virtual void inet::sctp::SctpInitChunk::insertRandom (size_t k, uint8_t random) virtual
insertRandom() [2/2]
void inet::sctp::SctpInitChunk::insertRandom (uint8_t random) inline
 {appendRandom(random);}
insertSctpChunkTypes() [1/2]
virtual void inet::sctp::SctpInitChunk::insertSctpChunkTypes (size_t k, uint16_t sctpChunkTypes) virtual
insertSctpChunkTypes() [2/2]
void inet::sctp::SctpInitChunk::insertSctpChunkTypes (uint16_t sctpChunkTypes) inline
 {appendSctpChunkTypes(sctpChunkTypes);}
insertSepChunks() [1/2]
virtual void inet::sctp::SctpInitChunk::insertSepChunks (size_t k, uint16_t sepChunks) virtual
insertSepChunks() [2/2]
void inet::sctp::SctpInitChunk::insertSepChunks (uint16_t sepChunks) inline
 {appendSepChunks(sepChunks);}
insertUnrecognizedParameters() [1/2]
virtual void inet::sctp::SctpInitChunk::insertUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters) virtual
insertUnrecognizedParameters() [2/2]
void inet::sctp::SctpInitChunk::insertUnrecognizedParameters (uint8_t unrecognizedParameters) inline
 {appendUnrecognizedParameters(unrecognizedParameters);}
operator=()
SctpInitChunk& inet::sctp::SctpInitChunk::operator= (const SctpInitChunk & other)
operator==()
bool inet::sctp::SctpInitChunk::operator== (const SctpInitChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpInitChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpInitChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setA_rwnd()
virtual void inet::sctp::SctpInitChunk::setA_rwnd (uint32_t a_rwnd) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setAddresses()
virtual void inet::sctp::SctpInitChunk::setAddresses (size_t k, const ::inet::L3Address & addresses) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setAddressesArraySize()
virtual void inet::sctp::SctpInitChunk::setAddressesArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setForwardTsn()
virtual void inet::sctp::SctpInitChunk::setForwardTsn (bool forwardTsn) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setHmacTypes()
virtual void inet::sctp::SctpInitChunk::setHmacTypes (size_t k, uint16_t hmacTypes) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setHmacTypesArraySize()
virtual void inet::sctp::SctpInitChunk::setHmacTypesArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setInitTag()
virtual void inet::sctp::SctpInitChunk::setInitTag (uint32_t initTag) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setInitTsn()
virtual void inet::sctp::SctpInitChunk::setInitTsn (uint32_t initTsn) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setIpv4Supported()
virtual void inet::sctp::SctpInitChunk::setIpv4Supported (bool ipv4Supported) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setIpv6Supported()
virtual void inet::sctp::SctpInitChunk::setIpv6Supported (bool ipv6Supported) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setMsg_rwnd()
virtual void inet::sctp::SctpInitChunk::setMsg_rwnd (uint32_t msg_rwnd) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setNoInStreams()
virtual void inet::sctp::SctpInitChunk::setNoInStreams (uint16_t noInStreams) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setNoOutStreams()
virtual void inet::sctp::SctpInitChunk::setNoOutStreams (uint16_t noOutStreams) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setRandom()
virtual void inet::sctp::SctpInitChunk::setRandom (size_t k, uint8_t random) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setRandomArraySize()
virtual void inet::sctp::SctpInitChunk::setRandomArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setSctpChunkTypes()
virtual void inet::sctp::SctpInitChunk::setSctpChunkTypes (size_t k, uint16_t sctpChunkTypes) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setSctpChunkTypesArraySize()
virtual void inet::sctp::SctpInitChunk::setSctpChunkTypesArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setSepChunks()
virtual void inet::sctp::SctpInitChunk::setSepChunks (size_t k, uint16_t sepChunks) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setSepChunksArraySize()
virtual void inet::sctp::SctpInitChunk::setSepChunksArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendInit().
setUnrecognizedParameters()
virtual void inet::sctp::SctpInitChunk::setUnrecognizedParameters (size_t k, uint8_t unrecognizedParameters) virtual
setUnrecognizedParametersArraySize()
virtual void inet::sctp::SctpInitChunk::setUnrecognizedParametersArraySize (size_t size) virtual
Member Data Documentation
a_rwnd
uint32_t inet::sctp::SctpInitChunk::a_rwnd = 0 protected
addresses
::inet::L3Address* inet::sctp::SctpInitChunk::addresses = nullptr protected
addresses_arraysize
size_t inet::sctp::SctpInitChunk::addresses_arraysize = 0 protected
forwardTsn
bool inet::sctp::SctpInitChunk::forwardTsn = false protected
hmacTypes
uint16_t* inet::sctp::SctpInitChunk::hmacTypes = nullptr protected
hmacTypes_arraysize
size_t inet::sctp::SctpInitChunk::hmacTypes_arraysize = 0 protected
initTag
uint32_t inet::sctp::SctpInitChunk::initTag = 0 protected
initTsn
uint32_t inet::sctp::SctpInitChunk::initTsn = 0 protected
ipv4Supported
bool inet::sctp::SctpInitChunk::ipv4Supported = false protected
ipv6Supported
bool inet::sctp::SctpInitChunk::ipv6Supported = false protected
msg_rwnd
uint32_t inet::sctp::SctpInitChunk::msg_rwnd = 0 protected
noInStreams
uint16_t inet::sctp::SctpInitChunk::noInStreams = 0 protected
noOutStreams
uint16_t inet::sctp::SctpInitChunk::noOutStreams = 0 protected
random
uint8_t* inet::sctp::SctpInitChunk::random = nullptr protected
random_arraysize
size_t inet::sctp::SctpInitChunk::random_arraysize = 0 protected
sctpChunkTypes
uint16_t* inet::sctp::SctpInitChunk::sctpChunkTypes = nullptr protected
sctpChunkTypes_arraysize
size_t inet::sctp::SctpInitChunk::sctpChunkTypes_arraysize = 0 protected
sepChunks
uint16_t* inet::sctp::SctpInitChunk::sepChunks = nullptr protected
sepChunks_arraysize
size_t inet::sctp::SctpInitChunk::sepChunks_arraysize = 0 protected
unrecognizedParameters
uint8_t* inet::sctp::SctpInitChunk::unrecognizedParameters = nullptr protected
unrecognizedParameters_arraysize
size_t inet::sctp::SctpInitChunk::unrecognizedParameters_arraysize = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h