INET Framework for OMNeT++/OMNEST: inet::math::IInterpolator< X, Y > Class Template Reference
inet::math::IInterpolator< X, Y > Class Template Reference abstract
This interface represents interpolation of values (y) between two points x1 and x2.
#include <IInterpolator.h>
Public Member Functions
virtual ~IInterpolator ()
virtual Y getValue (const X x1, const Y y1, const X x2, const Y y2, const X x) const =0
Returns the interpolated value for the given x.
virtual Y getMin (const X x1, const Y y1, const X x2, const Y y2) const =0
Returns the minimum interpolated value in the closed interval of [x1, x2].
virtual Y getMax (const X x1, const Y y1, const X x2, const Y y2) const =0
Returns the maximum interpolated value in the closed interval of [x1, x2].
virtual Y getMean (const X x1, const Y y1, const X x2, const Y y2) const =0
Returns the mean interpolated value in the closed interval of [x1, x2].
Detailed Description
template<typename X, typename Y>
class inet::math::IInterpolator< X, Y >
This interface represents interpolation of values (y) between two points x1 and x2.
The types X and Y represent scalar values (double, simtime_t, or some quantity with unit).
Constructor & Destructor Documentation
~IInterpolator()
template<typename X , typename Y > virtual inet::math::IInterpolator< X, Y >::~IInterpolator () inline virtual
 {}
Member Function Documentation
getMax()
template<typename X , typename Y > virtual Y inet::math::IInterpolator< X, Y >::getMax (const X x1, const Y y1, const X x2, const Y y2) const pure virtual
Returns the maximum interpolated value in the closed interval of [x1, x2].
Implemented in inet::math::InterpolatorBase< X, Y >.
getMean()
template<typename X , typename Y > virtual Y inet::math::IInterpolator< X, Y >::getMean (const X x1, const Y y1, const X x2, const Y y2) const pure virtual
Returns the mean interpolated value in the closed interval of [x1, x2].
Implemented in inet::math::LineardbInterpolator< X, Y >, inet::math::LinearInterpolator< X, Y >, inet::math::CloserInterpolator< X, Y >, and inet::math::ConstantInterpolatorBase< X, Y >.
getMin()
template<typename X , typename Y > virtual Y inet::math::IInterpolator< X, Y >::getMin (const X x1, const Y y1, const X x2, const Y y2) const pure virtual
Returns the minimum interpolated value in the closed interval of [x1, x2].
Implemented in inet::math::InterpolatorBase< X, Y >.
getValue()
template<typename X , typename Y > virtual Y inet::math::IInterpolator< X, Y >::getValue (const X x1, const Y y1, const X x2, const Y y2, const X x) const pure virtual
Returns the interpolated value for the given x.
The value of x must fall into the closed interval [x1, x2].
Implemented in inet::math::LineardbInterpolator< X, Y >, inet::math::LinearInterpolator< X, Y >, inet::math::CloserInterpolator< X, Y >, inet::math::MaximumInterpolator< X, Y >, inet::math::MinimumInterpolator< X, Y >, inet::math::AverageInterpolator< X, Y >, inet::math::RightInterpolator< X, Y >, inet::math::LeftInterpolator< X, Y >, and inet::math::EitherInterpolator< X, Y >.
Referenced by inet::math::ApproximatedFunction< R, D, DIMENSION, X >::getValue(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::getValue(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::getValue(), inet::math::Interpolated1DFunction< R, X >::getValue(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::getValueInterpolatedAlongX(), and inet::math::Interpolated1DFunction< R, X >::partition().
The documentation for this class was generated from the following file:
IInterpolator.h