INET Framework for OMNeT++/OMNEST: inet::RsbCommitTimerMsg Class Reference
inet::RsbCommitTimerMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:76 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
RsbCommitTimerMsg (const char *name=nullptr, short kind=0)
RsbCommitTimerMsg (const RsbCommitTimerMsg &other)
virtual ~RsbCommitTimerMsg ()
RsbCommitTimerMsg & operator= (const RsbCommitTimerMsg &other)
virtual RsbCommitTimerMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getId () const
virtual void setId (int id)
Public Member Functions inherited from inet::SignallingMsg
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const RsbCommitTimerMsg &)=delete
Protected Member Functions inherited from inet::SignallingMsg
bool operator== (const SignallingMsg &)=delete
Protected Attributes
int id = 0
Protected Attributes inherited from inet::SignallingMsg
int command = 0
Private Member Functions
void copy (const RsbCommitTimerMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:76 by opp_msgtool.
//
// FIXME missing documentation
//
message RsbCommitTimerMsg extends SignallingMsg
{
    int id;
    command = MSG_RSB_COMMIT_TIMER;
}
Constructor & Destructor Documentation
RsbCommitTimerMsg() [1/2]
inet::RsbCommitTimerMsg::RsbCommitTimerMsg (const char * name = nullptr, short kind = 0)
RsbCommitTimerMsg() [2/2]
inet::RsbCommitTimerMsg::RsbCommitTimerMsg (const RsbCommitTimerMsg & other)
~RsbCommitTimerMsg()
virtual inet::RsbCommitTimerMsg::~RsbCommitTimerMsg () virtual
Member Function Documentation
copy()
void inet::RsbCommitTimerMsg::copy (const RsbCommitTimerMsg & other) private
dup()
virtual RsbCommitTimerMsg* inet::RsbCommitTimerMsg::dup () const inline override virtual
Reimplemented from inet::SignallingMsg.
 {return new RsbCommitTimerMsg(*this);}
getId()
virtual int inet::RsbCommitTimerMsg::getId () const virtual
Referenced by inet::RsvpTe::processRSB_COMMIT_TIMER().
operator=()
RsbCommitTimerMsg& inet::RsbCommitTimerMsg::operator= (const RsbCommitTimerMsg & other)
operator==()
bool inet::RsbCommitTimerMsg::operator== (const RsbCommitTimerMsg &) protected delete
parsimPack()
virtual void inet::RsbCommitTimerMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::RsbCommitTimerMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::SignallingMsg.
Referenced by inet::doParsimUnpacking().
setId()
virtual void inet::RsbCommitTimerMsg::setId (int id) virtual
Referenced by inet::RsvpTe::createEgressRSB(), and inet::RsvpTe::createRSB().
Member Data Documentation
id
int inet::RsbCommitTimerMsg::id = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h