INET Framework for OMNeT++/OMNEST: inet::rtp::RtpParticipantInfo Class Reference
inet::rtp::RtpParticipantInfo Class Reference
This class is a super class for classes intended for storing information about RTP end systems.
#include <RtpParticipantInfo.h>
Public Member Functions
RtpParticipantInfo (uint32_t ssrc=0)
Default constructor.
RtpParticipantInfo (const RtpParticipantInfo &participantInfo)
Copy constructor.
virtual ~RtpParticipantInfo ()
Destructor.
RtpParticipantInfo & operator= (const RtpParticipantInfo &participantInfo)
Assignment operator.
virtual RtpParticipantInfo * dup () const override
Duplicates this RtpParticipantInfo by calling the copy constructor.
virtual void processRTPPacket (Packet *packet, int id, simtime_t arrivalTime)
This method should be extended by a subclass for extracting information about the originating endsystem of an RTP packet.
virtual void processSenderReport (const SenderReport &report, simtime_t arrivalTime)
This method extracts information about an RTP endsystem as provided by the given SenderReport.
virtual void processReceptionReport (const ReceptionReport &report, simtime_t arrivalTime)
This method extracts information of the given ReceptionReport.
virtual void processSDESChunk (const SdesChunk *sdesChunk, simtime_t arrivalTime)
This method extracts sdes information of the given sdes chunk.and stores it.
virtual SdesChunk * getSDESChunk () const
Returns a copy of the sdes chunk used for storing source description items about this system.
virtual void addSDESItem (SdesItem *sdesItem)
Adds this sdes item to the sdes chunk of this participant.
virtual ReceptionReport * receptionReport (simtime_t now)
This method is intended to be overwritten by subclasses.
virtual SenderReport * senderReport (simtime_t now)
This method is intended to be overwritten by subclasses which are used for storing information about itself.
virtual void nextInterval (simtime_t now)
This method should be called by the rtcp module which uses this class for storing information every time an rtcp packet is sent.
virtual bool toBeDeleted (simtime_t now)
Returns true if the end system does no longer participate in the RTP session.
virtual bool isSender () const
Returns true if this endsystem has sent at least one RTP data packet during the last two rtcp intervals (including the current one).
virtual uint32_t getSsrc () const override
Returns the ssrc identifier of the RTP endsystem.
virtual void setSsrc (uint32_t ssrc) override
Sets the ssrc identifier.
virtual void addSDESItem (SdesItem::SdesItemType type, const char *content)
Creates a new SdesItem and adds it to the SdesChunk stored in this RtpParticipantInfo.
virtual void parsimPack (cCommBuffer *b) const override
virtual void parsimUnpack (cCommBuffer *b) override
Public Member Functions inherited from inet::rtp::RtpParticipantInfo_Base
virtual ~RtpParticipantInfo_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getAddress () const
virtual ::inet::Ipv4Address & getAddressForUpdate ()
virtual void setAddress (const ::inet::Ipv4Address &address)
virtual int getRTPPort () const
virtual void setRTPPort (int RTPPort)
virtual int getRTCPPort () const
virtual void setRTCPPort (int RTCPPort)
Static Public Member Functions
static std::string ssrcToName (uint32_t ssrc)
This method returns the given 32 bit ssrc identifier as an 8 character hexadecimal number which is used as name of an RtpParticipantInfo object.
Protected Attributes
SdesChunk _sdesChunk
Used for storing sdes information about this RTP endsystem.
int _silentIntervals
Stores the number of rtcp intervals (including the current one) during which this RTP endsystem hasn't sent any RTP data packets.
Protected Attributes inherited from inet::rtp::RtpParticipantInfo_Base
::inet::Ipv4Address address = Ipv4Address::UNSPECIFIED_ADDRESS
int RTPPort = PORT_UNDEF
int RTCPPort = PORT_UNDEF
Private Member Functions
void copy (const RtpParticipantInfo &other)
Additional Inherited Members
Protected Member Functions inherited from inet::rtp::RtpParticipantInfo_Base
bool operator== (const RtpParticipantInfo_Base &)=delete
RtpParticipantInfo_Base (const char *name=nullptr)
RtpParticipantInfo_Base (const RtpParticipantInfo_Base &other)
RtpParticipantInfo_Base & operator= (const RtpParticipantInfo_Base &other)
Detailed Description
This class is a super class for classes intended for storing information about RTP end systems.
It has two subclasses: RTPReceiverInformation which is used for storing information about other system participating in an RTP session. RTPSenderInformation is used by an RTP endsystem for storing information about itself.
See also
RTPReceiverInformation
RTPSenderInformation
Constructor & Destructor Documentation
RtpParticipantInfo() [1/2]
inet::rtp::RtpParticipantInfo::RtpParticipantInfo (uint32_t ssrc = 0)
Default constructor.
                                                     :
     RtpParticipantInfo_Base(),
     _sdesChunk("SdesChunk", ssrc)
 {
     setName(ssrcToName(ssrc).c_str());
     // because there haven't been sent any RTP packets
     // by this endsystem at all, the number of silent
     // intervals would be undefined; to calculate with
     // it but not to regard this endsystem as a sender
     // it is set to 3; see isSender() for details
     _silentIntervals = 3;
 }
Referenced by dup().
RtpParticipantInfo() [2/2]
inet::rtp::RtpParticipantInfo::RtpParticipantInfo (const RtpParticipantInfo & participantInfo)
Copy constructor.
                                                                       : RtpParticipantInfo_Base(other)
 {
     copy(other);
 }
~RtpParticipantInfo()
inet::rtp::RtpParticipantInfo::~RtpParticipantInfo () virtual
Destructor.
 {
 }
Member Function Documentation
addSDESItem() [1/2]
void inet::rtp::RtpParticipantInfo::addSDESItem (SdesItem * sdesItem) virtual
Adds this sdes item to the sdes chunk of this participant.
 {
     _sdesChunk.addSDESItem(sdesItem);
 }
Referenced by inet::rtp::Rtcp::handleInitializeRTCP(), and processSDESChunk().
addSDESItem() [2/2]
void inet::rtp::RtpParticipantInfo::addSDESItem (SdesItem::SdesItemType type, const char * content) virtual
Creates a new SdesItem and adds it to the SdesChunk stored in this RtpParticipantInfo.
 {
     _sdesChunk.addSDESItem(new SdesItem(type, content));
 }
copy()
void inet::rtp::RtpParticipantInfo::copy (const RtpParticipantInfo & other) inline private
 {
     _sdesChunk = other._sdesChunk;
     _silentIntervals = other._silentIntervals;
 }
Referenced by operator=(), and RtpParticipantInfo().
dup()
RtpParticipantInfo * inet::rtp::RtpParticipantInfo::dup () const override virtual
Duplicates this RtpParticipantInfo by calling the copy constructor.
Reimplemented from inet::rtp::RtpParticipantInfo_Base.
Reimplemented in inet::rtp::RtpReceiverInfo, and inet::rtp::RtpSenderInfo.
 {
     return new RtpParticipantInfo(*this);
 }
getSDESChunk()
SdesChunk * inet::rtp::RtpParticipantInfo::getSDESChunk () const virtual
Returns a copy of the sdes chunk used for storing source description items about this system.
 {
     return new SdesChunk(_sdesChunk);
 }
Referenced by inet::rtp::Rtcp::createPacket().
getSsrc()
uint32_t inet::rtp::RtpParticipantInfo::getSsrc () const override virtual
Returns the ssrc identifier of the RTP endsystem.
Implements inet::rtp::RtpParticipantInfo_Base.
 {
     return _sdesChunk.getSsrc();
 }
Referenced by inet::rtp::Rtcp::createPacket(), inet::rtp::Rtcp::handleSelfMessage(), inet::rtp::Rtcp::processIncomingRTCPReceiverReportPacket(), inet::rtp::Rtcp::processIncomingRTCPSenderReportPacket(), and inet::rtp::RtpReceiverInfo::receptionReport().
isSender()
bool inet::rtp::RtpParticipantInfo::isSender () const virtual
Returns true if this endsystem has sent at least one RTP data packet during the last two rtcp intervals (including the current one).
 {
     return _silentIntervals <= 1;
 }
Referenced by inet::rtp::Rtcp::createPacket(), inet::rtp::RtpReceiverInfo::receptionReport(), inet::rtp::Rtcp::scheduleInterval(), and inet::rtp::RtpSenderInfo::senderReport().
nextInterval()
void inet::rtp::RtpParticipantInfo::nextInterval (simtime_t now) virtual
This method should be called by the rtcp module which uses this class for storing information every time an rtcp packet is sent.
Some behaviour of RTP and rtcp (and this class) depend on how many rtcp intervals have passed, for example an RTP end system is marked as inactive if there haven't been received packets from it for a certain number of rtpc intervals. Call getSenderReport() and createReceptionReport() before calling this method.
See also
getSenderReport()
createReceptionReport()
Reimplemented in inet::rtp::RtpReceiverInfo.
 {
     _silentIntervals++;
 }
Referenced by inet::rtp::Rtcp::createPacket(), and inet::rtp::RtpReceiverInfo::nextInterval().
operator=()
RtpParticipantInfo & inet::rtp::RtpParticipantInfo::operator= (const RtpParticipantInfo & participantInfo)
Assignment operator.
 {
     if (this == &other)
         return *this;
     RtpParticipantInfo_Base::operator=(other);
     copy(other);
     return *this;
 }
Referenced by inet::rtp::RtpSenderInfo::copy(), inet::rtp::RtpSenderInfo::operator=(), and inet::rtp::RtpReceiverInfo::operator=().
parsimPack()
virtual void inet::rtp::RtpParticipantInfo::parsimPack (cCommBuffer * b) const inline override virtual
 { throw cRuntimeError(this, "parsimPack() not implemented"); }
parsimUnpack()
virtual void inet::rtp::RtpParticipantInfo::parsimUnpack (cCommBuffer * b) inline override virtual
 { throw cRuntimeError("The parsimUnpack() not implemented."); }
processReceptionReport()
void inet::rtp::RtpParticipantInfo::processReceptionReport (const ReceptionReport & report, simtime_t arrivalTime) virtual
This method extracts information of the given ReceptionReport.
 {
     // useful code can be found in subclasses
 }
processRTPPacket()
void inet::rtp::RtpParticipantInfo::processRTPPacket (Packet * packet, int id, simtime_t arrivalTime) virtual
This method should be extended by a subclass for extracting information about the originating endsystem of an RTP packet.
This method sets _silentInterval to 0 so that the sender of this RTP packet is regarded as an active sender.
Reimplemented in inet::rtp::RtpReceiverInfo, and inet::rtp::RtpSenderInfo.
 {
     packet->peekAtFront<RtpHeader>();
     _silentIntervals = 0;
     delete packet;
 }
Referenced by inet::rtp::Rtcp::processIncomingRTPPacket(), inet::rtp::RtpSenderInfo::processRTPPacket(), and inet::rtp::RtpReceiverInfo::processRTPPacket().
processSDESChunk()
void inet::rtp::RtpParticipantInfo::processSDESChunk (const SdesChunk * sdesChunk, simtime_t arrivalTime) virtual
This method extracts sdes information of the given sdes chunk.and stores it.
Reimplemented in inet::rtp::RtpReceiverInfo.
 {
     for (int i = 0; i < sdesChunk->size(); i++) {
         if (sdesChunk->exist(i)) {
             const SdesItem *sdesItem = check_and_cast<const SdesItem *>(sdesChunk->get(i));
             addSDESItem(sdesItem->dup());
         }
     }
 }
Referenced by inet::rtp::Rtcp::processIncomingRTCPSDESPacket(), and inet::rtp::RtpReceiverInfo::processSDESChunk().
processSenderReport()
void inet::rtp::RtpParticipantInfo::processSenderReport (const SenderReport & report, simtime_t arrivalTime) virtual
This method extracts information about an RTP endsystem as provided by the given SenderReport.
 {
     // useful code can be found in subclasses
 }
Referenced by inet::rtp::Rtcp::processIncomingRTCPSenderReportPacket().
receptionReport()
ReceptionReport * inet::rtp::RtpParticipantInfo::receptionReport (simtime_t now) virtual
This method is intended to be overwritten by subclasses.
It should return a receiver report if there have been received RTP packets from that endsystem and nullptr otherwise.
Reimplemented in inet::rtp::RtpReceiverInfo.
 {
     return nullptr;
 }
senderReport()
SenderReport * inet::rtp::RtpParticipantInfo::senderReport (simtime_t now) virtual
This method is intended to be overwritten by subclasses which are used for storing information about itself.
It should return a sender report if there have been sent RTP packets recently or nullptr otherwise. The implementation for this class always returns nullptr.
Reimplemented in inet::rtp::RtpSenderInfo.
 {
     return nullptr;
 }
setSsrc()
void inet::rtp::RtpParticipantInfo::setSsrc (uint32_t ssrc) override virtual
Sets the ssrc identifier.
Implements inet::rtp::RtpParticipantInfo_Base.
 {
     _sdesChunk.setSsrc(ssrc);
 }
Referenced by inet::rtp::Rtcp::chooseSSRC().
ssrcToName()
std::string inet::rtp::RtpParticipantInfo::ssrcToName (uint32_t ssrc) static
This method returns the given 32 bit ssrc identifier as an 8 character hexadecimal number which is used as name of an RtpParticipantInfo object.
 {
     char name[9];
     sprintf(name, "%08x", ssrc);
     return name;
 }
Referenced by inet::rtp::Rtcp::findParticipantInfo(), and RtpParticipantInfo().
toBeDeleted()
bool inet::rtp::RtpParticipantInfo::toBeDeleted (simtime_t now) virtual
Returns true if the end system does no longer participate in the RTP session.
The implementation in this class always returns false.
Reimplemented in inet::rtp::RtpReceiverInfo.
 {
     return false;
 }
Referenced by inet::rtp::Rtcp::createPacket().
Member Data Documentation
_sdesChunk
SdesChunk inet::rtp::RtpParticipantInfo::_sdesChunk protected
Used for storing sdes information about this RTP endsystem.
The ssrc identifier is also stored here.
Referenced by addSDESItem(), copy(), getSDESChunk(), getSsrc(), and setSsrc().
_silentIntervals
int inet::rtp::RtpParticipantInfo::_silentIntervals protected
Stores the number of rtcp intervals (including the current one) during which this RTP endsystem hasn't sent any RTP data packets.
When an RTP data packet is received it is reset to 0.
Referenced by copy(), isSender(), nextInterval(), processRTPPacket(), and RtpParticipantInfo().
The documentation for this class was generated from the following files:
RtpParticipantInfo.h
RtpParticipantInfo.cc