INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRecoveryProcedure::ICwCalculator Class Reference
inet::ieee80211::IRecoveryProcedure::ICwCalculator Class Reference abstract
#include <IRecoveryProcedure.h>
Public Member Functions
virtual ~ICwCalculator ()
virtual void incrementCw ()=0
virtual void resetCw ()=0
virtual int getCw ()=0
Constructor & Destructor Documentation
~ICwCalculator()
virtual inet::ieee80211::IRecoveryProcedure::ICwCalculator::~ICwCalculator () inline virtual
 {}
Member Function Documentation
getCw()
virtual int inet::ieee80211::IRecoveryProcedure::ICwCalculator::getCw () pure virtual
Implemented in inet::ieee80211::Edcaf, and inet::ieee80211::Dcaf.
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementContentionWindow(), inet::ieee80211::QosRecoveryProcedure::incrementContentionWindow(), inet::ieee80211::NonQosRecoveryProcedure::initialize(), inet::ieee80211::QosRecoveryProcedure::initialize(), inet::ieee80211::NonQosRecoveryProcedure::resetContentionWindow(), and inet::ieee80211::QosRecoveryProcedure::resetContentionWindow().
incrementCw()
virtual void inet::ieee80211::IRecoveryProcedure::ICwCalculator::incrementCw () pure virtual
Implemented in inet::ieee80211::Edcaf, and inet::ieee80211::Dcaf.
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementContentionWindow(), and inet::ieee80211::QosRecoveryProcedure::incrementContentionWindow().
resetCw()
virtual void inet::ieee80211::IRecoveryProcedure::ICwCalculator::resetCw () pure virtual
Implemented in inet::ieee80211::Edcaf, and inet::ieee80211::Dcaf.
Referenced by inet::ieee80211::NonQosRecoveryProcedure::resetContentionWindow(), and inet::ieee80211::QosRecoveryProcedure::resetContentionWindow().
The documentation for this class was generated from the following file:
IRecoveryProcedure.h