INET Framework for OMNeT++/OMNEST: inet::rtp::RtpSessionControlInfo Class Reference
inet::rtp::RtpSessionControlInfo Class Reference
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:51 by opp_msgtool.
#include <RtpInterfacePacket_m.h>
Public Member Functions
RtpSessionControlInfo ()
RtpSessionControlInfo (const RtpSessionControlInfo &other)
virtual ~RtpSessionControlInfo ()
RtpSessionControlInfo & operator= (const RtpSessionControlInfo &other)
virtual RtpSessionControlInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
Public Member Functions inherited from inet::rtp::RtpControlInfo
RtpControlInfo ()
RtpControlInfo (const RtpControlInfo &other)
virtual ~RtpControlInfo ()
RtpControlInfo & operator= (const RtpControlInfo &other)
virtual RtpIfpType getType () const
virtual void setType (RtpIfpType type)
Protected Member Functions
bool operator== (const RtpSessionControlInfo &)=delete
Protected Member Functions inherited from inet::rtp::RtpControlInfo
bool operator== (const RtpControlInfo &)=delete
Protected Attributes
uint32_t ssrc = 0
Protected Attributes inherited from inet::rtp::RtpControlInfo
RtpIfpType type = static_cast<inet::rtp::RtpIfpType>(-1)
Private Member Functions
void copy (const RtpSessionControlInfo &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:51 by opp_msgtool.
// base class
class RtpSessionControlInfo extends RtpControlInfo
{
    uint32_t ssrc;
}
Constructor & Destructor Documentation
RtpSessionControlInfo() [1/2]
inet::rtp::RtpSessionControlInfo::RtpSessionControlInfo ()
RtpSessionControlInfo() [2/2]
inet::rtp::RtpSessionControlInfo::RtpSessionControlInfo (const RtpSessionControlInfo & other)
~RtpSessionControlInfo()
virtual inet::rtp::RtpSessionControlInfo::~RtpSessionControlInfo () virtual
Member Function Documentation
copy()
void inet::rtp::RtpSessionControlInfo::copy (const RtpSessionControlInfo & other) private
dup()
virtual RtpSessionControlInfo* inet::rtp::RtpSessionControlInfo::dup () const inline override virtual
Reimplemented from inet::rtp::RtpControlInfo.
Reimplemented in inet::rtp::RtpCiSenderModuleDeleted, inet::rtp::RtpCiDeleteSenderModule, inet::rtp::RtpCiSenderModuleCreated, inet::rtp::RtpCiCreateSenderModule, inet::rtp::RtpCiSenderStatus, inet::rtp::RtpCiSenderControl, and inet::rtp::RtpCiSessionEntered.
 {return new RtpSessionControlInfo(*this);}
getSsrc()
virtual uint32_t inet::rtp::RtpSessionControlInfo::getSsrc () const virtual
Referenced by inet::rtp::Rtp::createSenderModule(), and inet::rtp::Rtp::deleteSenderModule().
operator=()
RtpSessionControlInfo& inet::rtp::RtpSessionControlInfo::operator= (const RtpSessionControlInfo & other)
operator==()
bool inet::rtp::RtpSessionControlInfo::operator== (const RtpSessionControlInfo &) protected delete
parsimPack()
virtual void inet::rtp::RtpSessionControlInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::rtp::RtpControlInfo.
Reimplemented in inet::rtp::RtpCiSenderModuleDeleted, inet::rtp::RtpCiDeleteSenderModule, inet::rtp::RtpCiSenderModuleCreated, inet::rtp::RtpCiCreateSenderModule, inet::rtp::RtpCiSenderStatus, inet::rtp::RtpCiSenderControl, and inet::rtp::RtpCiSessionEntered.
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpSessionControlInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::rtp::RtpControlInfo.
Reimplemented in inet::rtp::RtpCiSenderModuleDeleted, inet::rtp::RtpCiDeleteSenderModule, inet::rtp::RtpCiSenderModuleCreated, inet::rtp::RtpCiCreateSenderModule, inet::rtp::RtpCiSenderStatus, inet::rtp::RtpCiSenderControl, and inet::rtp::RtpCiSessionEntered.
Referenced by inet::rtp::doParsimUnpacking().
setSsrc()
virtual void inet::rtp::RtpSessionControlInfo::setSsrc (uint32_t ssrc) virtual
Referenced by inet::rtp::Rtp::rtcpInitialized(), inet::rtp::Rtp::senderModuleCreated(), inet::rtp::Rtp::senderModuleDeleted(), and inet::rtp::Rtp::senderModuleStatus().
Member Data Documentation
ssrc
uint32_t inet::rtp::RtpSessionControlInfo::ssrc = 0 protected
The documentation for this class was generated from the following file:
RtpInterfacePacket_m.h