INET Framework for OMNeT++/OMNEST: inet::Ipv4InterfaceData Class Reference
inet::Ipv4InterfaceData Class Reference
Ipv4-specific data in an NetworkInterface.
#include <Ipv4InterfaceData.h>
Classes
struct HostMulticastData
struct HostMulticastGroupData
struct RouterMulticastData
struct RouterMulticastGroupData
Public Types
enum {
F_IP_ADDRESS, F_NETMASK, F_METRIC, F_MULTICAST_TTL_THRESHOLD,
F_MULTICAST_ADDRESSES, F_MULTICAST_LISTENERS
}
typedef std::vector< Ipv4Address > Ipv4AddressVector
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
Ipv4InterfaceData ()
virtual ~Ipv4InterfaceData ()
virtual std::string str () const override
virtual std::string detailedInfo () const
Getters
Ipv4Address getIPAddress () const
Ipv4Address getNetmask () const
Ipv4Address getNetworkBroadcastAddress () const
int getMetric () const
int getMulticastTtlThreshold () const
int getNumOfJoinedMulticastGroups () const
Ipv4Address getJoinedMulticastGroup (int index) const
const Ipv4MulticastSourceList & getJoinedMulticastSources (int index)
int getNumOfReportedMulticastGroups () const
Ipv4Address getReportedMulticastGroup (int index) const
const Ipv4MulticastSourceList & getReportedMulticastSources (int index) const
bool isMemberOfMulticastGroup (const Ipv4Address &multicastAddress) const
bool hasMulticastListener (Ipv4Address multicastAddress) const
bool hasMulticastListener (Ipv4Address multicastAddress, Ipv4Address sourceAddress) const
Setters
virtual void setIPAddress (Ipv4Address a)
virtual void setNetmask (Ipv4Address m)
virtual void setMetric (int m)
virtual void setMulticastTtlThreshold (int threshold)
virtual void joinMulticastGroup (const Ipv4Address &multicastAddress)
virtual void leaveMulticastGroup (const Ipv4Address &multicastAddress)
virtual void changeMulticastGroupMembership (Ipv4Address multicastAddress, McastSourceFilterMode oldFilterMode, const Ipv4AddressVector &oldSourceList, McastSourceFilterMode newFilterMode, const Ipv4AddressVector &newSourceList)
This method is called by sockets to register their multicast group membership changes in the interface.
virtual void addMulticastListener (const Ipv4Address &multicastAddress)
virtual void addMulticastListener (Ipv4Address multicastAddress, Ipv4Address sourceAddress)
virtual void removeMulticastListener (const Ipv4Address &multicastAddress)
virtual void removeMulticastListener (Ipv4Address multicastAddress, Ipv4Address sourceAddress)
virtual void setMulticastListeners (Ipv4Address multicastAddress, McastSourceFilterMode filterMode, const Ipv4AddressVector &sourceList)
Public Member Functions inherited from inet::InterfaceProtocolData
InterfaceProtocolData (int id)
NetworkInterface * getNetworkInterface () const
Returns the NetworkInterface that contains this data object, or nullptr.
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Types
typedef std::vector< HostMulticastGroupData * > HostMulticastGroupVector
typedef std::vector< RouterMulticastGroupData * > RouterMulticastGroupVector
Protected Member Functions
void changed1 (int fieldId)
HostMulticastData * getHostData ()
const HostMulticastData * getHostData () const
HostMulticastGroupData * findHostGroupData (Ipv4Address multicastAddress)
bool removeHostGroupData (Ipv4Address multicastAddress)
RouterMulticastData * getRouterData ()
const RouterMulticastData * getRouterData () const
RouterMulticastGroupData * findRouterGroupData (Ipv4Address multicastAddress) const
bool removeRouterGroupData (Ipv4Address multicastAddress)
Protected Member Functions inherited from inet::InterfaceProtocolData
virtual void changed (simsignal_t signalID, int fieldId)
Protected Attributes
Ipv4Address inetAddr
Ipv4 address of interface.
Ipv4Address netmask
netmask
int metric
link "cost"; see e.g. MS KB article Q299540
HostMulticastData * hostData
RouterMulticastData * routerData
Protected Attributes inherited from inet::InterfaceProtocolData
NetworkInterface * ownerp = nullptr
int id
Private Member Functions
Ipv4InterfaceData (const Ipv4InterfaceData &obj)
Ipv4InterfaceData & operator= (const Ipv4InterfaceData &obj)
Detailed Description
Ipv4-specific data in an NetworkInterface.
Stores interface Ipv4 address, netmask, metric, etc.
See also
NetworkInterface
Member Typedef Documentation
HostMulticastGroupVector
typedef std::vector<HostMulticastGroupData *> inet::Ipv4InterfaceData::HostMulticastGroupVector protected
Ipv4AddressVector
typedef std::vector<Ipv4Address> inet::Ipv4InterfaceData::Ipv4AddressVector
RouterMulticastGroupVector
typedef std::vector<RouterMulticastGroupData *> inet::Ipv4InterfaceData::RouterMulticastGroupVector protected
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
F_IP_ADDRESS
F_NETMASK
F_METRIC
F_MULTICAST_TTL_THRESHOLD
F_MULTICAST_ADDRESSES
F_MULTICAST_LISTENERS
 { F_IP_ADDRESS, F_NETMASK, F_METRIC, F_MULTICAST_TTL_THRESHOLD, F_MULTICAST_ADDRESSES, F_MULTICAST_LISTENERS };
Constructor & Destructor Documentation
Ipv4InterfaceData() [1/2]
inet::Ipv4InterfaceData::Ipv4InterfaceData (const Ipv4InterfaceData & obj) private
Ipv4InterfaceData() [2/2]
inet::Ipv4InterfaceData::Ipv4InterfaceData ()
     : InterfaceProtocolData(NetworkInterface::F_IPV4_DATA)
 {
     netmask = Ipv4Address::ALLONES_ADDRESS;
     metric = 0;
     hostData = nullptr;
     routerData = nullptr;
 }
~Ipv4InterfaceData()
inet::Ipv4InterfaceData::~Ipv4InterfaceData () virtual
 {
     delete hostData;
     delete routerData;
 }
Member Function Documentation
addMulticastListener() [1/2]
void inet::Ipv4InterfaceData::addMulticastListener (const Ipv4Address & multicastAddress) virtual
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv4InterfaceData::addMulticastListener(): multicast address expected, received %s.", multicastAddress.str().c_str());
     RouterMulticastGroupData *groupData = findRouterGroupData(multicastAddress);
     if (!groupData) {
         groupData = new RouterMulticastGroupData(multicastAddress);
         getRouterData()->reportedMulticastGroups.push_back(groupData);
         Ipv4MulticastGroupInfo info(getNetworkInterface(), multicastAddress);
         check_and_cast<cModule *>(getNetworkInterface()->getInterfaceTable())->emit(ipv4MulticastGroupRegisteredSignal, &info);
     }
     if (!groupData->sourceList.containsAll()) {
         groupData->sourceList = Ipv4MulticastSourceList::ALL_SOURCES;
         changed1(F_MULTICAST_LISTENERS);
     }
 }
addMulticastListener() [2/2]
void inet::Ipv4InterfaceData::addMulticastListener (Ipv4Address multicastAddress, Ipv4Address sourceAddress) virtual
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv4InterfaceData::addMulticastListener(): multicast address expected, received %s.", multicastAddress.str().c_str());
     RouterMulticastGroupData *groupData = findRouterGroupData(multicastAddress);
     if (!groupData) {
         groupData = new RouterMulticastGroupData(multicastAddress);
         getRouterData()->reportedMulticastGroups.push_back(groupData);
         Ipv4MulticastGroupInfo info(getNetworkInterface(), multicastAddress);
         check_and_cast<cModule *>(getNetworkInterface()->getInterfaceTable())->emit(ipv4MulticastGroupRegisteredSignal, &info);
     }
     if (!groupData->sourceList.contains(sourceAddress)) {
         groupData->sourceList.add(sourceAddress);
         changed1(F_MULTICAST_LISTENERS);
     }
 }
changed1()
void inet::Ipv4InterfaceData::changed1 (int fieldId) inline protected
 { changed(interfaceIpv4ConfigChangedSignal, fieldId); }
Referenced by addMulticastListener(), changeMulticastGroupMembership(), removeMulticastListener(), and setMulticastListeners().
changeMulticastGroupMembership()
void inet::Ipv4InterfaceData::changeMulticastGroupMembership (Ipv4Address multicastAddress, McastSourceFilterMode oldFilterMode, const Ipv4AddressVector & oldSourceList, McastSourceFilterMode newFilterMode, const Ipv4AddressVector & newSourceList) virtual
This method is called by sockets to register their multicast group membership changes in the interface.
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv4InterfaceData::changeMulticastGroupMembership(): multicast address expected, received %s.", multicastAddress.str().c_str());
     HostMulticastGroupData *entry = findHostGroupData(multicastAddress);
     if (!entry) {
         ASSERT(oldFilterMode == MCAST_INCLUDE_SOURCES && oldSourceList.empty());
         HostMulticastData *data = getHostData();
         data->joinedMulticastGroups.push_back(new HostMulticastGroupData(multicastAddress));
         entry = data->joinedMulticastGroups.back();
     }
     std::map<Ipv4Address, int> *counts = oldFilterMode == MCAST_INCLUDE_SOURCES ? &entry->includeCounts : &entry->excludeCounts;
     for (const auto& elem : oldSourceList) {
         auto count = counts->find(elem);
         if (count == counts->end())
             throw cRuntimeError("Inconsistent reference counts in Ipv4InterfaceData.");
         else if (count->second == 1)
             counts->erase(count);
         else
             count->second--;
     }
     counts = newFilterMode == MCAST_INCLUDE_SOURCES ? &entry->includeCounts : &entry->excludeCounts;
     for (const auto& elem : newSourceList) {
         auto count = counts->find(elem);
         if (count == counts->end())
             (*counts)[elem] = 1;
         else
             count->second++;
     }
     // update number of EXCLUDE mode sockets
     if (oldFilterMode == MCAST_INCLUDE_SOURCES && newFilterMode == MCAST_EXCLUDE_SOURCES)
         entry->numOfExcludeModeSockets++;
     else if (oldFilterMode == MCAST_EXCLUDE_SOURCES && newFilterMode == MCAST_INCLUDE_SOURCES)
         entry->numOfExcludeModeSockets--;
     // compute filterMode and sourceList
     bool changed = entry->updateSourceList();
     if (changed) {
         changed1(F_MULTICAST_ADDRESSES);
         cModule *m = ownerp ? dynamic_cast<cModule *>(ownerp->getInterfaceTable()) : nullptr;
         if (m) {
             Ipv4MulticastGroupSourceInfo info(ownerp, multicastAddress, entry->sourceList);
             m->emit(ipv4MulticastChangeSignal, &info);
         }
         // Legacy notifications
         if (oldFilterMode != newFilterMode && oldSourceList.empty() && newSourceList.empty()) {
             cModule *m = ownerp ? dynamic_cast<cModule *>(ownerp->getInterfaceTable()) : nullptr;
             if (m) {
                 Ipv4MulticastGroupInfo info2(ownerp, multicastAddress);
                 m->emit(newFilterMode == MCAST_EXCLUDE_SOURCES ? ipv4MulticastGroupJoinedSignal : ipv4MulticastGroupLeftSignal, &info2);
             }
         }
         // remove group data if it is INCLUDE(empty)
         if (entry->sourceList.isEmpty()) {
             removeHostGroupData(multicastAddress);
         }
     }
 }
Referenced by joinMulticastGroup(), and leaveMulticastGroup().
detailedInfo()
std::string inet::Ipv4InterfaceData::detailedInfo () const virtual
 {
     std::stringstream out;
     out << "inet addr:" << getIPAddress() << "\tMask: " << getNetmask() << "\n";
     out << "Metric: " << getMetric() << "\n";
     if (hostData)
         out << hostData->detailedInfo();
     if (routerData)
         out << routerData->detailedInfo();
     return out.str();
 }
findHostGroupData()
Ipv4InterfaceData::HostMulticastGroupData * inet::Ipv4InterfaceData::findHostGroupData (Ipv4Address multicastAddress) protected
 {
     ASSERT(multicastAddress.isMulticast());
     HostMulticastGroupVector& entries = getHostData()->joinedMulticastGroups;
     for (auto& entrie : entries)
         if ((entrie)->multicastGroup == multicastAddress)
             return entrie;
     return nullptr;
 }
Referenced by changeMulticastGroupMembership().
findRouterGroupData()
Ipv4InterfaceData::RouterMulticastGroupData * inet::Ipv4InterfaceData::findRouterGroupData (Ipv4Address multicastAddress) const protected
 {
     ASSERT(multicastAddress.isMulticast());
     const RouterMulticastGroupVector& entries = getRouterData()->reportedMulticastGroups;
     for (const auto& entrie : entries)
         if ((entrie)->multicastGroup == multicastAddress)
             return entrie;
     return nullptr;
 }
Referenced by addMulticastListener(), hasMulticastListener(), and setMulticastListeners().
getHostData() [1/2]
HostMulticastData* inet::Ipv4InterfaceData::getHostData () inline protected
 { if (!hostData) hostData = new HostMulticastData(); return hostData; }
Referenced by changeMulticastGroupMembership(), findHostGroupData(), isMemberOfMulticastGroup(), and removeHostGroupData().
getHostData() [2/2]
const HostMulticastData* inet::Ipv4InterfaceData::getHostData () const inline protected
 { return const_cast<Ipv4InterfaceData *>(this)->getHostData(); }
Referenced by getHostData().
getIPAddress()
Ipv4Address inet::Ipv4InterfaceData::getIPAddress () const inline
 { return inetAddr; }
Referenced by inet::DhcpClient::chooseInterface(), inet::Ipv4RoutingTable::configureRouterId(), inet::sctp::SctpNatHook::datagramForwardHook(), detailedInfo(), inet::ospfv3::Ospfv3Interface::detailedInfo(), inet::bgp::BgpConfigReader::findMyAS(), inet::Ipv4::fragmentPostRouting(), inet::Ipv4RoutingTable::gatherAddresses(), inet::Dsdv::handleMessageWhenUp(), inet::LinkStateRouting::initialize(), inet::Ted::initializeTED(), inet::bgp::BgpConfigReader::isInInterfaceTable(), inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimSm::multicastPacketArrivedOnNonRpfInterface(), inet::bgp::BgpRouter::openTCPConnectionToPeer(), inet::Icmp::possiblyLocalBroadcast(), inet::Ipv4::preroutingFinish(), inet::Ipv4RoutingTable::printRoutingTable(), inet::PimDm::processAssert(), inet::PimSm::processAssertG(), inet::PimSm::processAssertSG(), inet::DhcpServer::processDhcpMessage(), inet::PimDm::processGraftAckPacket(), inet::PimDm::processJoin(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::PimDm::processPrune(), inet::PimSm::processPruneG(), inet::PimSm::processPruneSG(), inet::Igmpv3::processQuery(), inet::DhcpServer::sendAck(), inet::DhcpServer::sendNak(), inet::DhcpServer::sendOffer(), inet::RsvpTe::setupHello(), str(), inet::InterfaceTable::updateLinkDisplayString(), and inet::bgp::BgpRouter::updateSendProcess().
getJoinedMulticastGroup()
Ipv4Address inet::Ipv4InterfaceData::getJoinedMulticastGroup (int index) const inline
 { return getHostData()->joinedMulticastGroups[index]->multicastGroup; }
getJoinedMulticastSources()
const Ipv4MulticastSourceList& inet::Ipv4InterfaceData::getJoinedMulticastSources (int index) inline
 { return getHostData()->joinedMulticastGroups[index]->sourceList; }
getMetric()
int inet::Ipv4InterfaceData::getMetric () const inline
 { return metric; }
Referenced by detailedInfo(), and inet::Ted::initializeTED().
getMulticastTtlThreshold()
int inet::Ipv4InterfaceData::getMulticastTtlThreshold () const inline
 { return getRouterData()->multicastTtlThreshold; }
getNetmask()
Ipv4Address inet::Ipv4InterfaceData::getNetmask () const inline
 { return netmask; }
Referenced by detailedInfo(), inet::Ipv4RoutingTable::findInterfaceByLocalBroadcastAddress(), inet::Ipv4RoutingTable::isLocalBroadcastAddress(), inet::Ipv4::routeLocalBroadcastPacket(), and str().
getNetworkBroadcastAddress()
Ipv4Address inet::Ipv4InterfaceData::getNetworkBroadcastAddress () const inline
 { return inetAddr.makeBroadcastAddress(netmask); }
Referenced by inet::Ipv4::resolveNextHopMacAddress().
getNumOfJoinedMulticastGroups()
int inet::Ipv4InterfaceData::getNumOfJoinedMulticastGroups () const inline
 { return getHostData()->joinedMulticastGroups.size(); }
Referenced by inet::InterfaceTable::collectMulticastGroups(), and inet::Ipv4NetworkConfigurator::dumpConfig().
getNumOfReportedMulticastGroups()
int inet::Ipv4InterfaceData::getNumOfReportedMulticastGroups () const inline
 { return getRouterData()->reportedMulticastGroups.size(); }
getReportedMulticastGroup()
Ipv4Address inet::Ipv4InterfaceData::getReportedMulticastGroup (int index) const inline
 { return getRouterData()->reportedMulticastGroups[index]->multicastGroup; }
getReportedMulticastSources()
const Ipv4MulticastSourceList& inet::Ipv4InterfaceData::getReportedMulticastSources (int index) const inline
 { return getRouterData()->reportedMulticastGroups[index]->sourceList; }
getRouterData() [1/2]
RouterMulticastData* inet::Ipv4InterfaceData::getRouterData () inline protected
 { if (!routerData) routerData = new RouterMulticastData(); return routerData; }
Referenced by addMulticastListener(), findRouterGroupData(), removeMulticastListener(), removeRouterGroupData(), and setMulticastListeners().
getRouterData() [2/2]
const RouterMulticastData* inet::Ipv4InterfaceData::getRouterData () const inline protected
 { return const_cast<Ipv4InterfaceData *>(this)->getRouterData(); }
Referenced by getRouterData().
hasMulticastListener() [1/2]
bool inet::Ipv4InterfaceData::hasMulticastListener (Ipv4Address multicastAddress) const
 {
     RouterMulticastGroupData *groupData = findRouterGroupData(multicastAddress);
     return groupData && !groupData->sourceList.isEmpty();
 }
Referenced by inet::Ipv4::forwardMulticastPacket().
hasMulticastListener() [2/2]
bool inet::Ipv4InterfaceData::hasMulticastListener (Ipv4Address multicastAddress, Ipv4Address sourceAddress) const
 {
     RouterMulticastGroupData *groupData = findRouterGroupData(multicastAddress);
     return groupData && !groupData->sourceList.contains(sourceAddress);
 }
isMemberOfMulticastGroup()
bool inet::Ipv4InterfaceData::isMemberOfMulticastGroup (const Ipv4Address & multicastAddress) const
 {
     HostMulticastGroupVector groups = getHostData()->joinedMulticastGroups;
     for (HostMulticastGroupVector::const_iterator it = groups.begin(); it != groups.end(); ++it)
         if ((*it)->multicastGroup == multicastAddress)
             return true;
     return false;
 }
Referenced by inet::Ipv4RoutingTable::isLocalMulticastAddress(), and inet::Ipv4::preroutingFinish().
joinMulticastGroup()
void inet::Ipv4InterfaceData::joinMulticastGroup (const Ipv4Address & multicastAddress) virtual
 {
     Ipv4AddressVector empty;
     changeMulticastGroupMembership(multicastAddress, MCAST_INCLUDE_SOURCES, empty, MCAST_EXCLUDE_SOURCES, empty);
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), and inet::ospfv2::Ospfv2ConfigReader::joinMulticastGroups().
leaveMulticastGroup()
void inet::Ipv4InterfaceData::leaveMulticastGroup (const Ipv4Address & multicastAddress) virtual
 {
     Ipv4AddressVector empty;
     changeMulticastGroupMembership(multicastAddress, MCAST_EXCLUDE_SOURCES, empty, MCAST_INCLUDE_SOURCES, empty);
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), and inet::eigrp::EigrpIpv4Pdm::setPassive().
operator=()
Ipv4InterfaceData& inet::Ipv4InterfaceData::operator= (const Ipv4InterfaceData & obj) private
removeHostGroupData()
bool inet::Ipv4InterfaceData::removeHostGroupData (Ipv4Address multicastAddress) protected
 {
     ASSERT(multicastAddress.isMulticast());
     HostMulticastGroupVector& entries = getHostData()->joinedMulticastGroups;
     for (auto it = entries.begin(); it != entries.end(); ++it)
         if ((*it)->multicastGroup == multicastAddress) {
             delete *it;
             entries.erase(it);
             return true;
         }
     return false;
 }
Referenced by changeMulticastGroupMembership().
removeMulticastListener() [1/2]
void inet::Ipv4InterfaceData::removeMulticastListener (const Ipv4Address & multicastAddress) virtual
 {
     RouterMulticastGroupVector& multicastGroups = getRouterData()->reportedMulticastGroups;
     int n = multicastGroups.size();
     int i;
     for (i = 0; i < n; i++)
         if (multicastGroups[i]->multicastGroup == multicastAddress)
             break;
     if (i != n) {
         delete multicastGroups[i];
         multicastGroups.erase(multicastGroups.begin() + i);
         changed1(F_MULTICAST_LISTENERS);
         Ipv4MulticastGroupInfo info(getNetworkInterface(), multicastAddress);
         check_and_cast<cModule *>(getNetworkInterface()->getInterfaceTable())->emit(ipv4MulticastGroupUnregisteredSignal, &info);
     }
 }
removeMulticastListener() [2/2]
void inet::Ipv4InterfaceData::removeMulticastListener (Ipv4Address multicastAddress, Ipv4Address sourceAddress) virtual
 {
     RouterMulticastGroupVector& multicastGroups = getRouterData()->reportedMulticastGroups;
     int n = multicastGroups.size();
     int i;
     for (i = 0; i < n; i++)
         if (multicastGroups[i]->multicastGroup == multicastAddress)
             break;
     if (i != n) {
         multicastGroups[i]->sourceList.remove(sourceAddress);
         if (multicastGroups[i]->sourceList.isEmpty()) {
             delete multicastGroups[i];
             multicastGroups.erase(multicastGroups.begin() + i);
             Ipv4MulticastGroupInfo info(getNetworkInterface(), multicastAddress);
             check_and_cast<cModule *>(getNetworkInterface()->getInterfaceTable())->emit(ipv4MulticastGroupUnregisteredSignal, &info);
         }
         changed1(F_MULTICAST_LISTENERS);
     }
 }
removeRouterGroupData()
bool inet::Ipv4InterfaceData::removeRouterGroupData (Ipv4Address multicastAddress) protected
 {
     ASSERT(multicastAddress.isMulticast());
     RouterMulticastGroupVector& entries = getRouterData()->reportedMulticastGroups;
     for (auto it = entries.begin(); it != entries.end(); ++it)
         if ((*it)->multicastGroup == multicastAddress) {
             delete *it;
             entries.erase(it);
             return true;
         }
     return false;
 }
Referenced by setMulticastListeners().
setIPAddress()
virtual void inet::Ipv4InterfaceData::setIPAddress (Ipv4Address a) inline virtual
 { inetAddr = a; changed1(F_IP_ADDRESS); }
Referenced by inet::Ipv4FlatNetworkConfigurator::assignAddresses(), inet::DhcpClient::bindLease(), inet::Ipv4RoutingTable::configureRouterId(), inet::Ipv4NodeConfigurator::prepareInterface(), and inet::HostAutoConfigurator::setupNetworkLayer().
setMetric()
virtual void inet::Ipv4InterfaceData::setMetric (int m) inline virtual
 { metric = m; changed1(F_METRIC); }
setMulticastListeners()
void inet::Ipv4InterfaceData::setMulticastListeners (Ipv4Address multicastAddress, McastSourceFilterMode filterMode, const Ipv4AddressVector & sourceList) virtual
 {
     if (!multicastAddress.isMulticast())
         throw cRuntimeError("Ipv4InterfaceData::setMulticastListeners(): multicast address expected, received %s.", multicastAddress.str().c_str());
     RouterMulticastGroupData *groupData = findRouterGroupData(multicastAddress);
     if (!groupData) {
         groupData = new RouterMulticastGroupData(multicastAddress);
         getRouterData()->reportedMulticastGroups.push_back(groupData);
     }
     if (filterMode != groupData->sourceList.filterMode || sourceList != groupData->sourceList.sources) {
         if (filterMode != MCAST_INCLUDE_SOURCES || !sourceList.empty()) {
             groupData->sourceList.filterMode = filterMode;
             groupData->sourceList.sources = sourceList;
         }
         else
             removeRouterGroupData(multicastAddress);
         changed1(F_MULTICAST_LISTENERS);
     }
 }
setMulticastTtlThreshold()
virtual void inet::Ipv4InterfaceData::setMulticastTtlThreshold (int threshold) inline virtual
 { getRouterData()->multicastTtlThreshold = threshold; changed1(F_MULTICAST_TTL_THRESHOLD); }
setNetmask()
virtual void inet::Ipv4InterfaceData::setNetmask (Ipv4Address m) inline virtual
 { netmask = m; changed1(F_NETMASK); }
str()
std::string inet::Ipv4InterfaceData::str () const override virtual
Reimplemented from inet::TagBase.
 {
     std::stringstream out;
     out << "Ipv4:{inet_addr:" << getIPAddress() << "/" << getNetmask().getNetmaskLength();
     if (hostData)
         out << hostData->str();
     if (routerData)
         out << routerData->str();
     out << "}";
     return out.str();
 }
Member Data Documentation
hostData
HostMulticastData* inet::Ipv4InterfaceData::hostData protected
Referenced by detailedInfo(), Ipv4InterfaceData(), str(), and ~Ipv4InterfaceData().
inetAddr
Ipv4Address inet::Ipv4InterfaceData::inetAddr protected
Ipv4 address of interface.
metric
int inet::Ipv4InterfaceData::metric protected
link "cost"; see e.g. MS KB article Q299540
Referenced by Ipv4InterfaceData().
netmask
Ipv4Address inet::Ipv4InterfaceData::netmask protected
netmask
Referenced by Ipv4InterfaceData().
routerData
RouterMulticastData* inet::Ipv4InterfaceData::routerData protected
Referenced by detailedInfo(), Ipv4InterfaceData(), str(), and ~Ipv4InterfaceData().
The documentation for this class was generated from the following files:
Ipv4InterfaceData.h
Ipv4InterfaceData.cc