INET Framework for OMNeT++/OMNEST: inet::Ieee80211SubtypeTagBase Class Reference
inet::Ieee80211SubtypeTagBase Class Reference
Class generated from inet/linklayer/ieee80211/mac/Ieee80211SubtypeTag.msg:13 by opp_msgtool.
#include <Ieee80211SubtypeTag_m.h>
Public Member Functions
Ieee80211SubtypeTagBase ()
Ieee80211SubtypeTagBase (const Ieee80211SubtypeTagBase &other)
virtual ~Ieee80211SubtypeTagBase ()
Ieee80211SubtypeTagBase & operator= (const Ieee80211SubtypeTagBase &other)
virtual Ieee80211SubtypeTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getSubtype () const
virtual void setSubtype (int subtype)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ieee80211SubtypeTagBase &)=delete
Protected Attributes
int subtype = 0
Private Member Functions
void copy (const Ieee80211SubtypeTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/ieee80211/mac/Ieee80211SubtypeTag.msg:13 by opp_msgtool.
class Ieee80211SubtypeTagBase extends TagBase
{
    int subtype;
}
Constructor & Destructor Documentation
Ieee80211SubtypeTagBase() [1/2]
inet::Ieee80211SubtypeTagBase::Ieee80211SubtypeTagBase ()
Ieee80211SubtypeTagBase() [2/2]
inet::Ieee80211SubtypeTagBase::Ieee80211SubtypeTagBase (const Ieee80211SubtypeTagBase & other)
~Ieee80211SubtypeTagBase()
virtual inet::Ieee80211SubtypeTagBase::~Ieee80211SubtypeTagBase () virtual
Member Function Documentation
copy()
void inet::Ieee80211SubtypeTagBase::copy (const Ieee80211SubtypeTagBase & other) private
dup()
virtual Ieee80211SubtypeTagBase* inet::Ieee80211SubtypeTagBase::dup () const inline override virtual
Reimplemented in inet::Ieee80211SubtypeInd, and inet::Ieee80211SubtypeReq.
 {return new Ieee80211SubtypeTagBase(*this);}
getSubtype()
virtual int inet::Ieee80211SubtypeTagBase::getSubtype () const virtual
Referenced by inet::ieee80211::Ieee80211Mac::handleMgmtPacket().
operator=()
Ieee80211SubtypeTagBase& inet::Ieee80211SubtypeTagBase::operator= (const Ieee80211SubtypeTagBase & other)
operator==()
bool inet::Ieee80211SubtypeTagBase::operator== (const Ieee80211SubtypeTagBase &) protected delete
parsimPack()
virtual void inet::Ieee80211SubtypeTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::Ieee80211SubtypeInd, and inet::Ieee80211SubtypeReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ieee80211SubtypeTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::Ieee80211SubtypeInd, and inet::Ieee80211SubtypeReq.
Referenced by inet::doParsimUnpacking().
setSubtype()
virtual void inet::Ieee80211SubtypeTagBase::setSubtype (int subtype) virtual
Member Data Documentation
subtype
int inet::Ieee80211SubtypeTagBase::subtype = 0 protected
The documentation for this class was generated from the following file:
Ieee80211SubtypeTag_m.h