INET Framework for OMNeT++/OMNEST: inet::tcp::TcpSendQueue Class Reference
inet::tcp::TcpSendQueue Class Reference
Send queue that manages Chunks.
#include <TcpSendQueue.h>
Public Member Functions
TcpSendQueue ()
Ctor.
virtual ~TcpSendQueue ()
Virtual dtor.
virtual ChunkQueue & getDataBuffer ()
virtual void setConnection (TcpConnection *_conn)
Set the connection that owns this queue.
virtual void init (uint32_t startSeq)
Initialize the object.
virtual std::string str () const override
Returns a string with the region stored.
virtual void enqueueAppData (Packet *msg)
Called on SEND app command, it inserts in the queue the data the user wants to send.
virtual uint32_t getBufferStartSeq () const
Returns the sequence number of the first byte stored in the buffer.
virtual uint32_t getBufferEndSeq () const
Returns the sequence number of the last byte stored in the buffer plus one.
virtual uint32_t getBytesAvailable (uint32_t fromSeq) const
Utility function: returns how many bytes are available in the queue, from (and including) the given sequence number.
virtual Packet * createSegmentWithBytes (uint32_t fromSeq, uint32_t numBytes)
Called when the TCP wants to send or retransmit data, it constructs a TCP segment which contains the data from the requested sequence number range.
virtual void discardUpTo (uint32_t seqNum)
Tells the queue that bytes up to (but NOT including) seqNum have been transmitted and ACKed, so they can be removed from the queue.
Protected Attributes
TcpConnection * conn = nullptr
uint32_t begin = 0
uint32_t end = 0
ChunkQueue dataBuffer
Detailed Description
Send queue that manages Chunks.
See also
TCPRcvQueue
Constructor & Destructor Documentation
TcpSendQueue()
inet::tcp::TcpSendQueue::TcpSendQueue ()
Ctor.
 {
 }
~TcpSendQueue()
inet::tcp::TcpSendQueue::~TcpSendQueue () virtual
Virtual dtor.
 {
 }
Member Function Documentation
createSegmentWithBytes()
Packet * inet::tcp::TcpSendQueue::createSegmentWithBytes (uint32_t fromSeq, uint32_t numBytes) virtual
Called when the TCP wants to send or retransmit data, it constructs a TCP segment which contains the data from the requested sequence number range.
The actually returned segment may contain less than maxNumBytes bytes if the subclass wants to reproduce the original segment boundaries when retransmitting.
 {
     ASSERT(seqLE(begin, fromSeq) && seqLE(fromSeq + numBytes, end));
     char msgname[32];
     sprintf(msgname, "tcpseg(l=%u)", (unsigned int)numBytes);
     Packet *tcpSegment = new Packet(msgname);
     const auto& payload = dataBuffer.peekAt(B(fromSeq - begin), B(numBytes)); // get data from buffer
     tcpSegment->insertAtBack(payload);
     return tcpSegment;
 }
Referenced by inet::tcp::TcpConnection::sendSegment().
discardUpTo()
void inet::tcp::TcpSendQueue::discardUpTo (uint32_t seqNum) virtual
Tells the queue that bytes up to (but NOT including) seqNum have been transmitted and ACKed, so they can be removed from the queue.
 {
     ASSERT(seqLE(begin, seqNum) && seqLE(seqNum, end));
     if (seqNum != begin) {
         dataBuffer.pop(B(seqNum - begin));
         begin = seqNum;
     }
 }
Referenced by inet::tcp::TcpConnection::processAckInEstabEtc(), inet::tcp::TcpConnection::processRstInSynReceived(), and inet::tcp::TcpConnection::processSegmentInSynSent().
enqueueAppData()
void inet::tcp::TcpSendQueue::enqueueAppData (Packet * msg) virtual
Called on SEND app command, it inserts in the queue the data the user wants to send.
Implementations of this abstract class will decide what this means: copying actual bytes, just increasing the "last byte queued" variable, or storing cMessage object(s). The msg object should not be referenced after this point (sendQueue may delete it.)
 {
     dataBuffer.push(msg->peekDataAt(B(0), msg->getDataLength()));
     end += msg->getByteLength();
     if (seqLess(end, begin))
         throw cRuntimeError("Send queue is full");
     delete msg;
 }
Referenced by inet::tcp::TcpConnection::process_SEND().
getBufferEndSeq()
uint32_t inet::tcp::TcpSendQueue::getBufferEndSeq () const virtual
Returns the sequence number of the last byte stored in the buffer plus one.
(The first byte of the next send operation would get this sequence number.)
 {
     return end;
 }
Referenced by inet::tcp::TcpConnection::process_CLOSE(), inet::tcp::TcpConnection::processRstInSynReceived(), inet::tcp::TcpConnection::retransmitData(), and inet::tcp::TcpConnection::retransmitOneSegment().
getBufferStartSeq()
uint32_t inet::tcp::TcpSendQueue::getBufferStartSeq () const virtual
Returns the sequence number of the first byte stored in the buffer.
 {
     return begin;
 }
Referenced by inet::tcp::TcpConnection::sendSegment().
getBytesAvailable()
uint32_t inet::tcp::TcpSendQueue::getBytesAvailable (uint32_t fromSeq) const virtual
Utility function: returns how many bytes are available in the queue, from (and including) the given sequence number.
 {
     return seqLess(fromSeq, end) ? end - fromSeq : 0;
 }
Referenced by inet::tcp::TcpConnection::isSendQueueEmpty(), inet::tcp::TcpConnection::nextSeg(), inet::tcp::TcpConnection::process_SEND(), inet::tcp::TcpConnection::retransmitData(), inet::tcp::TcpConnection::retransmitOneSegment(), inet::tcp::TcpConnection::sendData(), inet::tcp::TcpConnection::sendOneNewSegment(), inet::tcp::TcpConnection::sendProbe(), and inet::tcp::TcpConnection::sendSegment().
getDataBuffer()
virtual ChunkQueue& inet::tcp::TcpSendQueue::getDataBuffer () inline virtual
 { return dataBuffer; }
init()
void inet::tcp::TcpSendQueue::init (uint32_t startSeq) virtual
Initialize the object.
The startSeq parameter tells what sequence number the first byte of app data should get. This is usually ISS + 1 because SYN consumes one byte in the sequence number space.
init() may be called more than once; every call flushes the existing contents of the queue.
 {
     begin = startSeq;
     end = startSeq;
     dataBuffer.clear(); // clear dataBuffer
 }
Referenced by inet::tcp::TcpConnection::selectInitialSeqNum().
setConnection()
virtual void inet::tcp::TcpSendQueue::setConnection (TcpConnection * _conn) inline virtual
Set the connection that owns this queue.
 { conn = _conn; }
Referenced by inet::tcp::TcpConnection::initClonedConnection(), and inet::tcp::TcpConnection::initConnection().
str()
std::string inet::tcp::TcpSendQueue::str () const override virtual
Returns a string with the region stored.
 {
     std::stringstream out;
     out << "[" << begin << ".." << end << ")" << dataBuffer;
     return out.str();
 }
Member Data Documentation
begin
uint32_t inet::tcp::TcpSendQueue::begin = 0 protected
Referenced by createSegmentWithBytes(), discardUpTo(), enqueueAppData(), getBufferStartSeq(), init(), and str().
conn
TcpConnection* inet::tcp::TcpSendQueue::conn = nullptr protected
dataBuffer
ChunkQueue inet::tcp::TcpSendQueue::dataBuffer protected
Referenced by createSegmentWithBytes(), discardUpTo(), enqueueAppData(), init(), and str().
end
uint32_t inet::tcp::TcpSendQueue::end = 0 protected
Referenced by createSegmentWithBytes(), discardUpTo(), enqueueAppData(), getBufferEndSeq(), getBytesAvailable(), init(), and str().
The documentation for this class was generated from the following files:
TcpSendQueue.h
TcpSendQueue.cc