INET Framework for OMNeT++/OMNEST: inet::rtp::RtpCiSenderStatus Class Reference
inet::rtp::RtpCiSenderStatus Class Reference
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:84 by opp_msgtool.
#include <RtpInterfacePacket_m.h>
Public Member Functions
RtpCiSenderStatus ()
RtpCiSenderStatus (const RtpCiSenderStatus &other)
virtual ~RtpCiSenderStatus ()
RtpCiSenderStatus & operator= (const RtpCiSenderStatus &other)
virtual RtpCiSenderStatus * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual RtpSenderStatus getStatus () const
virtual void setStatus (RtpSenderStatus status)
virtual uint32_t getTimeStamp () const
virtual void setTimeStamp (uint32_t timeStamp)
Public Member Functions inherited from inet::rtp::RtpSessionControlInfo
RtpSessionControlInfo ()
RtpSessionControlInfo (const RtpSessionControlInfo &other)
virtual ~RtpSessionControlInfo ()
RtpSessionControlInfo & operator= (const RtpSessionControlInfo &other)
virtual uint32_t getSsrc () const
virtual void setSsrc (uint32_t ssrc)
Public Member Functions inherited from inet::rtp::RtpControlInfo
RtpControlInfo ()
RtpControlInfo (const RtpControlInfo &other)
virtual ~RtpControlInfo ()
RtpControlInfo & operator= (const RtpControlInfo &other)
virtual RtpIfpType getType () const
virtual void setType (RtpIfpType type)
Protected Member Functions
bool operator== (const RtpCiSenderStatus &)=delete
Protected Member Functions inherited from inet::rtp::RtpSessionControlInfo
bool operator== (const RtpSessionControlInfo &)=delete
Protected Member Functions inherited from inet::rtp::RtpControlInfo
bool operator== (const RtpControlInfo &)=delete
Protected Attributes
RtpSenderStatus status = static_cast<inet::rtp::RtpSenderStatus>(-1)
uint32_t timeStamp = 0
Protected Attributes inherited from inet::rtp::RtpSessionControlInfo
uint32_t ssrc = 0
Protected Attributes inherited from inet::rtp::RtpControlInfo
RtpIfpType type = static_cast<inet::rtp::RtpIfpType>(-1)
Private Member Functions
void copy (const RtpCiSenderStatus &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:84 by opp_msgtool.
// ~Rtp to App
class RtpCiSenderStatus extends RtpSessionControlInfo
{
    type = RTP_IFP_SENDER_STATUS;
    // from ~RtpSenderStatusMessage:
    RtpSenderStatus status;
    uint32_t timeStamp;
}
Constructor & Destructor Documentation
RtpCiSenderStatus() [1/2]
inet::rtp::RtpCiSenderStatus::RtpCiSenderStatus ()
RtpCiSenderStatus() [2/2]
inet::rtp::RtpCiSenderStatus::RtpCiSenderStatus (const RtpCiSenderStatus & other)
~RtpCiSenderStatus()
virtual inet::rtp::RtpCiSenderStatus::~RtpCiSenderStatus () virtual
Member Function Documentation
copy()
void inet::rtp::RtpCiSenderStatus::copy (const RtpCiSenderStatus & other) private
dup()
virtual RtpCiSenderStatus* inet::rtp::RtpCiSenderStatus::dup () const inline override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
 {return new RtpCiSenderStatus(*this);}
getStatus()
virtual RtpSenderStatus inet::rtp::RtpCiSenderStatus::getStatus () const virtual
getTimeStamp()
virtual uint32_t inet::rtp::RtpCiSenderStatus::getTimeStamp () const virtual
operator=()
RtpCiSenderStatus& inet::rtp::RtpCiSenderStatus::operator= (const RtpCiSenderStatus & other)
operator==()
bool inet::rtp::RtpCiSenderStatus::operator== (const RtpCiSenderStatus &) protected delete
parsimPack()
virtual void inet::rtp::RtpCiSenderStatus::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpCiSenderStatus::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::rtp::RtpSessionControlInfo.
Referenced by inet::rtp::doParsimUnpacking().
setStatus()
virtual void inet::rtp::RtpCiSenderStatus::setStatus (RtpSenderStatus status) virtual
Referenced by inet::rtp::Rtp::senderModuleStatus().
setTimeStamp()
virtual void inet::rtp::RtpCiSenderStatus::setTimeStamp (uint32_t timeStamp) virtual
Referenced by inet::rtp::Rtp::senderModuleStatus().
Member Data Documentation
status
RtpSenderStatus inet::rtp::RtpCiSenderStatus::status = static_cast<inet::rtp::RtpSenderStatus>(-1) protected
timeStamp
uint32_t inet::rtp::RtpCiSenderStatus::timeStamp = 0 protected
The documentation for this class was generated from the following file:
RtpInterfacePacket_m.h