INET Framework for OMNeT++/OMNEST: inet::NextHopRoutingTable Class Reference
inet::NextHopRoutingTable Class Reference
A C++ interface to abstract the functionality of a routing table, regardless of address type.
#include <NextHopRoutingTable.h>
Public Member Functions
NextHopRoutingTable ()
virtual ~NextHopRoutingTable ()
Miscellaneous functions
virtual bool isForwardingEnabled () const override
Forwarding on/off.
virtual bool isAdminDistEnabled () const override
Administrative distance on/off.
virtual bool isMulticastForwardingEnabled () const override
Multicast forwarding on/off.
virtual L3Address getRouterIdAsGeneric () const override
Returns routerId.
virtual bool isLocalAddress (const L3Address &dest) const override
Checks if the address is a local one, i.e.
virtual NetworkInterface * getInterfaceByAddress (const L3Address &address) const override
Returns an interface given by its address.
virtual void routeChanged (NextHopRoute *entry, int fieldCode)
To be called from route objects whenever a field changes.
Routing functions (query the route table)
virtual NextHopRoute * findBestMatchingRoute (const L3Address &dest) const override
The routing function.
virtual NetworkInterface * getOutputInterfaceForDestination (const L3Address &dest) const override
Convenience function based on findBestMatchingRoute().
virtual L3Address getNextHopForDestination (const L3Address &dest) const override
Convenience function based on findBestMatchingRoute().
Multicast routing functions
virtual bool isLocalMulticastAddress (const L3Address &dest) const override
Checks if the address is in one of the local multicast group address list.
virtual IMulticastRoute * findBestMatchingMulticastRoute (const L3Address &origin, const L3Address &group) const override
Returns route for a multicast origin and group.
Route table manipulation
virtual int getNumRoutes () const override
Returns the total number of unicast routes.
virtual IRoute * getRoute (int k) const override
Returns the kth route.
virtual IRoute * getDefaultRoute () const override
Finds and returns the default route, or nullptr if it doesn't exist.
virtual void addRoute (IRoute *entry) override
Adds a route to the routing table.
virtual IRoute * removeRoute (IRoute *entry) override
Removes the given route from the routing table, and returns it.
virtual bool deleteRoute (IRoute *entry) override
Deletes the given route from the routing table.
virtual int getNumMulticastRoutes () const override
Returns the total number of multicast routes.
virtual IMulticastRoute * getMulticastRoute (int k) const override
Returns the kth multicast route.
virtual void addMulticastRoute (IMulticastRoute *entry) override
Adds a multicast route to the routing table.
virtual IMulticastRoute * removeMulticastRoute (IMulticastRoute *entry) override
Removes the given route from the routing table, and returns it.
virtual bool deleteMulticastRoute (IMulticastRoute *entry) override
Deletes the given multicast route from the routing table.
virtual IRoute * createRoute () override
virtual void printRoutingTable () const override
Prints routing table.
Public Member Functions inherited from inet::IRoutingTable
virtual ~IRoutingTable ()
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *) override
Raises an error.
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Called by the signal handler whenever a change of a category occurs to which this client has subscribed.
virtual void configureRouterId ()
virtual void refreshDisplay () const override
virtual void configureInterface (NetworkInterface *ie)
virtual void configureLoopback ()
void internalAddRoute (NextHopRoute *route)
NextHopRoute * internalRemoveRoute (NextHopRoute *route)
Static Protected Member Functions
static bool routeLessThan (const NextHopRoute *a, const NextHopRoute *b)
Private Types
typedef std::vector< NextHopRoute * > RouteVector
typedef std::vector< NextHopMulticastRoute * > MulticastRouteVector
Private Attributes
ModuleRefByPar< IInterfaceTable > ift
L3Address routerId
L3Address::AddressType addressType = L3Address::NONE
bool forwarding = false
bool multicastForwarding = false
RouteVector routes
MulticastRouteVector multicastRoutes
Detailed Description
A C++ interface to abstract the functionality of a routing table, regardless of address type.
Member Typedef Documentation
MulticastRouteVector
typedef std::vector<NextHopMulticastRoute *> inet::NextHopRoutingTable::MulticastRouteVector private
RouteVector
typedef std::vector<NextHopRoute *> inet::NextHopRoutingTable::RouteVector private
Constructor & Destructor Documentation
NextHopRoutingTable()
inet::NextHopRoutingTable::NextHopRoutingTable ()
 {
 }
~NextHopRoutingTable()
inet::NextHopRoutingTable::~NextHopRoutingTable () virtual
 {
     for (auto& elem : routes)
         delete elem;
     for (auto& elem : multicastRoutes)
         delete elem;
 }
Member Function Documentation
addMulticastRoute()
void inet::NextHopRoutingTable::addMulticastRoute (IMulticastRoute * entry) override virtual
Adds a multicast route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implements inet::IRoutingTable.
 {
     Enter_Method("addMulticastRoute(...)");
     // TODO
 }
addRoute()
void inet::NextHopRoutingTable::addRoute (IRoute * entry) override virtual
Adds a route to the routing table.
Routes are allowed to be modified while in the routing table. (There is a notification mechanism that allows routing table internals to be updated on a routing entry change.)
Implements inet::IRoutingTable.
 {
     Enter_Method("addRoute(...)");
     NextHopRoute *entry = check_and_cast<NextHopRoute *>(route);
     // check that the interface exists
     if (!entry->getInterface())
         throw cRuntimeError("addRoute(): interface cannot be nullptr");
     internalAddRoute(entry);
     emit(routeAddedSignal, entry);
 }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes().
configureInterface()
void inet::NextHopRoutingTable::configureInterface (NetworkInterface * ie) protected virtual
 {
     int metric = (int)(ceil(2e9 / ie->getDatarate())); // use OSPF cost as default
     int interfaceModuleId = ie->getId();
     // mac
     auto d = ie->addProtocolData<NextHopInterfaceData>();
     d->setMetric(metric);
     if (addressType == L3Address::MAC)
         d->setAddress(ie->getMacAddress());
     else if (ie && addressType == L3Address::MODULEPATH)
         d->setAddress(ModulePathAddress(interfaceModuleId));
     else if (ie && addressType == L3Address::MODULEID)
         d->setAddress(ModuleIdAddress(interfaceModuleId));
 }
Referenced by initialize().
configureLoopback()
void inet::NextHopRoutingTable::configureLoopback () protected virtual
 {
 //TODO needed???
 //    NetworkInterface *ie = ift->getFirstLoopbackInterface()
 //    // add Ipv4 info. Set 127.0.0.1/8 as address by default --
 //    // we may reconfigure later it to be the routerId
 //    Ipv4InterfaceData *d = new Ipv4InterfaceData();
 //    d->setIPAddress(Ipv4Address::LOOPBACK_ADDRESS);
 //    d->setNetmask(Ipv4Address::LOOPBACK_NETMASK);
 //    d->setMetric(1);
 //    ie->setIPv4Data(d);
 }
Referenced by initialize().
configureRouterId()
void inet::NextHopRoutingTable::configureRouterId () protected virtual
 {
     if (routerId.isUnspecified()) { // not yet configured
         const char *routerIdStr = par("routerId");
         if (!strcmp(routerIdStr, "auto")) { // non-"auto" cases already handled in earlier stage
             // choose highest interface address as routerId
             for (int i = 0; i < ift->getNumInterfaces(); ++i) {
                 NetworkInterface *ie = ift->getInterface(i);
                 if (!ie->isLoopback()) {
                     L3Address interfaceAddr = ie->getProtocolData<NextHopInterfaceData>()->getAddress();
                     if (routerId.isUnspecified() || routerId < interfaceAddr)
                         routerId = interfaceAddr;
                 }
             }
         }
     }
 //    else // already configured
 //    {
 //        // if there is no interface with routerId yet, assign it to the loopback address;
 //        // TODO find out if this is a good practice, in which situations it is useful etc.
 //        if (getInterfaceByAddress(routerId)==nullptr)
 //        {
 //            NetworkInterface *lo0 = ift->getFirstLoopbackInterface();
 //            lo0->getNextHopProtocolData()->setAddress(routerId);
 //        }
 //    }
 }
Referenced by initialize().
createRoute()
IRoute * inet::NextHopRoutingTable::createRoute () override virtual
Implements inet::IRoutingTable.
 {
     return new NextHopRoute();
 }
deleteMulticastRoute()
bool inet::NextHopRoutingTable::deleteMulticastRoute (IMulticastRoute * entry) override virtual
Deletes the given multicast route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implements inet::IRoutingTable.
 {
     Enter_Method("deleteMulticastRoute(...)");
     return false; // TODO
 }
deleteRoute()
bool inet::NextHopRoutingTable::deleteRoute (IRoute * entry) override virtual
Deletes the given route from the routing table.
Returns true if the route was deleted, and false if it was not in the routing table.
Implements inet::IRoutingTable.
 {
     Enter_Method("deleteRoute(...)");
     NextHopRoute *entry = internalRemoveRoute(check_and_cast<NextHopRoute *>(route));
     if (entry != nullptr) {
         EV_INFO << "remove route " << entry->str() << "\n";
         emit(routeDeletedSignal, entry);
         delete entry;
     }
     return entry != nullptr;
 }
findBestMatchingMulticastRoute()
IMulticastRoute * inet::NextHopRoutingTable::findBestMatchingMulticastRoute (const L3Address & origin, const L3Address & group) const override virtual
Returns route for a multicast origin and group.
Implements inet::IRoutingTable.
 {
     Enter_Method("findBestMatchingMulticastRoute(%s, %s)", origin.str().c_str(), group.str().c_str());
     return nullptr; // TODO
 }
findBestMatchingRoute()
NextHopRoute * inet::NextHopRoutingTable::findBestMatchingRoute (const L3Address & dest) const override virtual
The routing function.
Performs longest prefix match for the given destination address, and returns the resulting route. Returns nullptr if there is no matching route.
Implements inet::IRoutingTable.
 {
     Enter_Method("findBestMatchingRoute(%s)", dest.str().c_str());
     // find best match (one with longest prefix)
     // default route has zero prefix length, so (if exists) it'll be selected as last resort
     NextHopRoute *bestRoute = nullptr;
     for (auto e : routes) {
         if (dest.matches(e->getDestinationAsGeneric(), e->getPrefixLength())) {
             bestRoute = const_cast<NextHopRoute *>(e);
             break;
         }
     }
     return bestRoute;
 }
Referenced by getNextHopForDestination(), and getOutputInterfaceForDestination().
getDefaultRoute()
IRoute * inet::NextHopRoutingTable::getDefaultRoute () const override virtual
Finds and returns the default route, or nullptr if it doesn't exist.
Implements inet::IRoutingTable.
 {
     // if there is a default route entry, it is the last valid entry
     auto i = routes.rbegin();
     if (i != routes.rend() && (*i)->getPrefixLength() == 0)
         return *i;
     return nullptr;
 }
getInterfaceByAddress()
NetworkInterface * inet::NextHopRoutingTable::getInterfaceByAddress (const L3Address & address) const override virtual
Returns an interface given by its address.
Returns nullptr if not found.
Implements inet::IRoutingTable.
 {
     Enter_Method("getInterfaceByAddress(%s)", address.str().c_str());
     return ift->findInterfaceByAddress(address);
 }
getMulticastRoute()
IMulticastRoute * inet::NextHopRoutingTable::getMulticastRoute (int k) const override virtual
Returns the kth multicast route.
Implements inet::IRoutingTable.
 {
     return nullptr; // TODO
 }
getNextHopForDestination()
L3Address inet::NextHopRoutingTable::getNextHopForDestination (const L3Address & dest) const override virtual
Convenience function based on findBestMatchingRoute().
Returns the gateway for the destination address. Returns the unspecified address if the destination is not in routing table or the gateway field is not filled in in the route.
Implements inet::IRoutingTable.
 {
     Enter_Method("getGatewayForDestAddr(%s)", dest.str().c_str());
     const IRoute *e = findBestMatchingRoute(dest);
     return e ? e->getNextHopAsGeneric() : L3Address();
 }
getNumMulticastRoutes()
int inet::NextHopRoutingTable::getNumMulticastRoutes () const override virtual
Returns the total number of multicast routes.
Implements inet::IRoutingTable.
 {
     return 0; // TODO
 }
getNumRoutes()
int inet::NextHopRoutingTable::getNumRoutes () const override virtual
Returns the total number of unicast routes.
Implements inet::IRoutingTable.
 {
     return routes.size();
 }
getOutputInterfaceForDestination()
NetworkInterface * inet::NextHopRoutingTable::getOutputInterfaceForDestination (const L3Address & dest) const override virtual
Convenience function based on findBestMatchingRoute().
Returns the output interface for the packets with dest as destination address, or nullptr if the destination is not in routing table.
Implements inet::IRoutingTable.
 {
     Enter_Method("getInterfaceForDestAddr(%s)", dest.str().c_str());
     const IRoute *e = findBestMatchingRoute(dest);
     return e ? e->getInterface() : nullptr;
 }
getRoute()
IRoute * inet::NextHopRoutingTable::getRoute (int k) const override virtual
Returns the kth route.
Implements inet::IRoutingTable.
 {
     ASSERT(k >= 0 && (unsigned int)k < routes.size());
     return routes[k];
 }
getRouterIdAsGeneric()
L3Address inet::NextHopRoutingTable::getRouterIdAsGeneric () const override virtual
Returns routerId.
Implements inet::IRoutingTable.
 {
     return routerId;
 }
handleMessage()
void inet::NextHopRoutingTable::handleMessage (cMessage * msg) override protected virtual
Raises an error.
 {
     throw cRuntimeError("This module doesn't process messages");
 }
initialize()
void inet::NextHopRoutingTable::initialize (int stage) override protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         // get a pointer to the IInterfaceTable
         ift.reference(this, "interfaceTableModule", true);
         const char *addressTypeString = par("addressType");
         if (!strcmp(addressTypeString, "mac"))
             addressType = L3Address::MAC;
         else if (!strcmp(addressTypeString, "modulepath"))
             addressType = L3Address::MODULEPATH;
         else if (!strcmp(addressTypeString, "moduleid"))
             addressType = L3Address::MODULEID;
         else
             throw cRuntimeError("Unknown address type");
         forwarding = par("forwarding");
         multicastForwarding = par("multicastForwarding");
         WATCH_PTRVECTOR(routes);
         WATCH_PTRVECTOR(multicastRoutes);
         WATCH(forwarding);
         WATCH(multicastForwarding);
         WATCH(routerId);
         cModule *host = getContainingNode(this);
         host->subscribe(interfaceCreatedSignal, this);
         host->subscribe(interfaceDeletedSignal, this);
         host->subscribe(interfaceStateChangedSignal, this);
         host->subscribe(interfaceConfigChangedSignal, this);
         host->subscribe(interfaceIpv4ConfigChangedSignal, this);
     }
     // TODO INITSTAGE
     else if (stage == INITSTAGE_LINK_LAYER) {
         // At this point, all L2 modules have registered themselves (added their
         // interface entries). Create the per-interface Ipv4 data structures.
         IInterfaceTable *interfaceTable = getModuleFromPar<IInterfaceTable>(par("interfaceTableModule"), this);
         for (int i = 0; i < interfaceTable->getNumInterfaces(); ++i)
             configureInterface(interfaceTable->getInterface(i));
     }
     else if (stage == INITSTAGE_NETWORK_LAYER) {
         configureLoopback();
         // read routing table file (and interface configuration)
 //        RoutingTableParser parser(ift, this);
 //        if (*filename && parser.readRoutingTableFromFile(filename)==-1)
 //            throw cRuntimeError("Error reading routing table file %s", filename);
         // TODO
         // set routerId if param is not "" (==no routerId) or "auto" (in which case we'll
         // do it later in a later stage, after network configurators configured the interfaces)
 //        const char *routerIdStr = par("routerId");
 //        if (strcmp(routerIdStr, "") && strcmp(routerIdStr, "auto"))
 //            routerId = Ipv4Address(routerIdStr);
         // routerID selection must be after network autoconfiguration assigned interface addresses
         configureRouterId();
         // we don't use notifications during initialize(), so we do it manually.
 //        updateNetmaskRoutes();
 //        printRoutingTable();
     }
 }
internalAddRoute()
void inet::NextHopRoutingTable::internalAddRoute (NextHopRoute * route) protected
 {
     ASSERT(route->getRoutingTableAsGeneric() == nullptr);
     // add to tables
     // we keep entries sorted, so that we can stop at the first match when doing the longest prefix matching
     auto pos = upper_bound(routes.begin(), routes.end(), route, routeLessThan);
     routes.insert(pos, route);
     route->setRoutingTable(this);
 }
Referenced by addRoute(), and routeChanged().
internalRemoveRoute()
NextHopRoute * inet::NextHopRoutingTable::internalRemoveRoute (NextHopRoute * route) protected
 {
     auto i = find(routes, route);
     if (i != routes.end()) {
         ASSERT(route->getRoutingTableAsGeneric() == this);
         routes.erase(i);
         return route;
     }
     return nullptr;
 }
Referenced by deleteRoute(), removeRoute(), and routeChanged().
isAdminDistEnabled()
virtual bool inet::NextHopRoutingTable::isAdminDistEnabled () const inline override virtual
Administrative distance on/off.
Implements inet::IRoutingTable.
 { return false; }
isForwardingEnabled()
bool inet::NextHopRoutingTable::isForwardingEnabled () const override virtual
Forwarding on/off.
Implements inet::IRoutingTable.
 {
     return forwarding;
 }
isLocalAddress()
bool inet::NextHopRoutingTable::isLocalAddress (const L3Address & dest) const override virtual
Checks if the address is a local one, i.e.
one of the host's.
Implements inet::IRoutingTable.
 {
     Enter_Method("isLocalAddress(%s)", dest.str().c_str());
     return ift->isLocalAddress(dest);
 }
isLocalMulticastAddress()
bool inet::NextHopRoutingTable::isLocalMulticastAddress (const L3Address & dest) const override virtual
Checks if the address is in one of the local multicast group address list.
Implements inet::IRoutingTable.
 {
     Enter_Method("isLocalMulticastAddress(%s)", dest.str().c_str());
     return dest.isMulticast(); // TODO
 }
isMulticastForwardingEnabled()
bool inet::NextHopRoutingTable::isMulticastForwardingEnabled () const override virtual
Multicast forwarding on/off.
Implements inet::IRoutingTable.
 {
     return multicastForwarding;
 }
numInitStages()
virtual int inet::NextHopRoutingTable::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
printRoutingTable()
void inet::NextHopRoutingTable::printRoutingTable () const override virtual
Prints routing table.
Implements inet::IRoutingTable.
 {
     for (const auto& elem : routes)
         EV_INFO << (elem)->getInterface()->getInterfaceFullPath() << " -> " << (elem)->getDestinationAsGeneric().str() << " as " << (elem)->str() << endl;
 }
receiveSignal()
void inet::NextHopRoutingTable::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
Called by the signal handler whenever a change of a category occurs to which this client has subscribed.
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
     // TODO
 }
refreshDisplay()
void inet::NextHopRoutingTable::refreshDisplay () const override protected virtual
 {
 // TODO
 //    char buf[80];
 //    if (routerId.isUnspecified())
 //        sprintf(buf, "%d+%d routes", (int)routes.size(), (int)multicastRoutes.size());
 //    else
 //        sprintf(buf, "routerId: %s\n%d+%d routes", routerId.str().c_str(), (int)routes.size(), (int)multicastRoutes.size());
 //    getDisplayString().setTagArg("t", 0, buf);
 }
removeMulticastRoute()
IMulticastRoute * inet::NextHopRoutingTable::removeMulticastRoute (IMulticastRoute * entry) override virtual
Removes the given route from the routing table, and returns it.
nullptr is returned of the route was not in the routing table.
Implements inet::IRoutingTable.
 {
     Enter_Method("removeMulticastRoute(...)");
     return nullptr; // TODO
 }
removeRoute()
IRoute * inet::NextHopRoutingTable::removeRoute (IRoute * entry) override virtual
Removes the given route from the routing table, and returns it.
nullptr is returned if the route was not in the routing table.
Implements inet::IRoutingTable.
 {
     Enter_Method("removeRoute(...)");
     NextHopRoute *entry = internalRemoveRoute(check_and_cast<NextHopRoute *>(route));
     if (entry != nullptr) {
         EV_INFO << "remove route " << entry->str() << "\n";
         emit(routeDeletedSignal, entry);
         entry->setRoutingTable(nullptr);
     }
     return entry;
 }
routeChanged()
void inet::NextHopRoutingTable::routeChanged (NextHopRoute * entry, int fieldCode) virtual
To be called from route objects whenever a field changes.
Used for maintaining internal data structures and firing "routing table changed" notifications.
 {
     if (fieldCode == IRoute::F_DESTINATION || fieldCode == IRoute::F_PREFIX_LENGTH || fieldCode == IRoute::F_METRIC) { // our data structures depend on these fields
         entry = internalRemoveRoute(entry);
         ASSERT(entry != nullptr); // failure means inconsistency: route was not found in this routing table
         internalAddRoute(entry);
 //        invalidateCache();
     }
     emit(routeChangedSignal, entry); // TODO include fieldCode in the notification
 }
Referenced by inet::NextHopRoute::changed().
routeLessThan()
bool inet::NextHopRoutingTable::routeLessThan (const NextHopRoute * a, const NextHopRoute * b) static protected
 {
     // helper for sort() in addRoute(). We want routes with longer
     // prefixes to be at front, so we compare them as "less".
     // For metric, a smaller value is better (we report that as "less").
     if (a->getPrefixLength() != b->getPrefixLength())
         return a->getPrefixLength() > b->getPrefixLength();
     if (a->getDestinationAsGeneric() != b->getDestinationAsGeneric())
         return a->getDestinationAsGeneric() < b->getDestinationAsGeneric();
     return a->getMetric() < b->getMetric();
 }
Referenced by internalAddRoute().
Member Data Documentation
addressType
L3Address::AddressType inet::NextHopRoutingTable::addressType = L3Address::NONE private
Referenced by configureInterface(), and initialize().
forwarding
bool inet::NextHopRoutingTable::forwarding = false private
Referenced by initialize(), and isForwardingEnabled().
ift
ModuleRefByPar<IInterfaceTable> inet::NextHopRoutingTable::ift private
Referenced by configureRouterId(), getInterfaceByAddress(), initialize(), and isLocalAddress().
multicastForwarding
bool inet::NextHopRoutingTable::multicastForwarding = false private
Referenced by initialize(), and isMulticastForwardingEnabled().
multicastRoutes
MulticastRouteVector inet::NextHopRoutingTable::multicastRoutes private
Referenced by initialize(), and ~NextHopRoutingTable().
routerId
L3Address inet::NextHopRoutingTable::routerId private
Referenced by configureRouterId(), getRouterIdAsGeneric(), and initialize().
routes
RouteVector inet::NextHopRoutingTable::routes private
Referenced by findBestMatchingRoute(), getDefaultRoute(), getNumRoutes(), getRoute(), initialize(), internalAddRoute(), internalRemoveRoute(), printRoutingTable(), and ~NextHopRoutingTable().
The documentation for this class was generated from the following files:
NextHopRoutingTable.h
NextHopRoutingTable.cc