INET Framework for OMNeT++/OMNEST: inet::physicallayer::IInterleaver Class Reference
inet::physicallayer::IInterleaver Class Reference abstract
#include <IInterleaver.h>
Public Member Functions
virtual BitVector interleave (const BitVector &bits) const =0
virtual BitVector deinterleave (const BitVector &bits) const =0
virtual const IInterleaving * getInterleaving () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
deinterleave()
virtual BitVector inet::physicallayer::IInterleaver::deinterleave (const BitVector & bits) const pure virtual
Implemented in inet::physicallayer::Ieee80211OfdmInterleaver, and inet::physicallayer::Ieee80211OfdmInterleaverModule.
Referenced by inet::physicallayer::ApskDecoder::decode(), and inet::physicallayer::Ieee80211OfdmDecoder::decode().
getInterleaving()
virtual const IInterleaving* inet::physicallayer::IInterleaver::getInterleaving () const pure virtual
Implemented in inet::physicallayer::Ieee80211OfdmInterleaver, and inet::physicallayer::Ieee80211OfdmInterleaverModule.
Referenced by inet::physicallayer::Ieee80211OfdmDecoder::decode(), inet::physicallayer::Ieee80211OfdmEncoder::encode(), inet::physicallayer::ApskEncoder::encode(), inet::physicallayer::ApskDecoder::initialize(), inet::physicallayer::Ieee80211OfdmEncoderModule::initialize(), inet::physicallayer::Ieee80211OfdmDecoderModule::initialize(), and inet::physicallayer::ApskEncoder::initialize().
interleave()
virtual BitVector inet::physicallayer::IInterleaver::interleave (const BitVector & bits) const pure virtual
Implemented in inet::physicallayer::Ieee80211OfdmInterleaver, and inet::physicallayer::Ieee80211OfdmInterleaverModule.
Referenced by inet::physicallayer::Ieee80211OfdmEncoder::encode(), and inet::physicallayer::ApskEncoder::encode().
The documentation for this class was generated from the following file:
IInterleaver.h