INET Framework for OMNeT++/OMNEST: inet::Ieee802SapTagBase Class Reference
inet::Ieee802SapTagBase Class Reference
Class generated from inet/linklayer/common/Ieee802SapTag.msg:29 by opp_msgtool.
#include <Ieee802SapTag_m.h>
Public Member Functions
Ieee802SapTagBase ()
Ieee802SapTagBase (const Ieee802SapTagBase &other)
virtual ~Ieee802SapTagBase ()
Ieee802SapTagBase & operator= (const Ieee802SapTagBase &other)
virtual Ieee802SapTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getSsap () const
virtual void setSsap (int ssap)
virtual int getDsap () const
virtual void setDsap (int dsap)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ieee802SapTagBase &)=delete
Protected Attributes
int ssap = -1
int dsap = -1
Private Member Functions
void copy (const Ieee802SapTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/common/Ieee802SapTag.msg:29 by opp_msgtool.
class Ieee802SapTagBase extends TagBase
{
    int ssap = -1;        // used with IEEE 802 LLC (see ~EtherFrameWithLlc)
    int dsap = -1;        // used with IEEE 802 LLC (see ~EtherFrameWithLlc)
}
Constructor & Destructor Documentation
Ieee802SapTagBase() [1/2]
inet::Ieee802SapTagBase::Ieee802SapTagBase ()
Ieee802SapTagBase() [2/2]
inet::Ieee802SapTagBase::Ieee802SapTagBase (const Ieee802SapTagBase & other)
~Ieee802SapTagBase()
virtual inet::Ieee802SapTagBase::~Ieee802SapTagBase () virtual
Member Function Documentation
copy()
void inet::Ieee802SapTagBase::copy (const Ieee802SapTagBase & other) private
dup()
virtual Ieee802SapTagBase* inet::Ieee802SapTagBase::dup () const inline override virtual
Reimplemented in inet::Ieee802SapInd, and inet::Ieee802SapReq.
 {return new Ieee802SapTagBase(*this);}
getDsap()
virtual int inet::Ieee802SapTagBase::getDsap () const virtual
getSsap()
virtual int inet::Ieee802SapTagBase::getSsap () const virtual
operator=()
Ieee802SapTagBase& inet::Ieee802SapTagBase::operator= (const Ieee802SapTagBase & other)
operator==()
bool inet::Ieee802SapTagBase::operator== (const Ieee802SapTagBase &) protected delete
parsimPack()
virtual void inet::Ieee802SapTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::Ieee802SapInd, and inet::Ieee802SapReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ieee802SapTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::Ieee802SapInd, and inet::Ieee802SapReq.
Referenced by inet::doParsimUnpacking().
setDsap()
virtual void inet::Ieee802SapTagBase::setDsap (int dsap) virtual
Referenced by inet::Ieee8022LlcSocket::sendOut().
setSsap()
virtual void inet::Ieee802SapTagBase::setSsap (int ssap) virtual
Referenced by inet::Ieee8022LlcInserter::processPacket(), inet::EtherTrafGen::sendBurstPackets(), inet::Ieee8022LlcSocket::sendOut(), inet::EtherAppServer::sendPacket(), and inet::EtherAppClient::sendPacket().
Member Data Documentation
dsap
int inet::Ieee802SapTagBase::dsap = -1 protected
ssap
int inet::Ieee802SapTagBase::ssap = -1 protected
The documentation for this class was generated from the following file:
Ieee802SapTag_m.h