INET Framework for OMNeT++/OMNEST: inet::math::Interval< T > Class Template Reference
inet::math::Interval< T > Class Template Reference
N-dimensional interval (cuboid), given by its two opposite corners.
#include <Interval.h>
Public Member Functions
Interval (const Point< T ... > &lower, const Point< T ... > &upper, unsigned char lowerClosed, unsigned char upperClosed, unsigned char fixed)
const Point< T ... > & getLower () const
const Point< T ... > & getUpper () const
unsigned char getLowerClosed () const
unsigned char getUpperClosed () const
unsigned char getFixed () const
template<typename X , int DIMENSION>
Interval< X > get () const
template<typename X , int DIMENSION>
void set (const Interval< X > &ix)
bool contains (const Point< T ... > &p) const
double getVolume () const
Returns the volume in the dimensions denoted by the 1 bits of dims.
bool isEmpty () const
Returns true iff getVolume() == 0.
Interval< T ... > getIntersected (const Interval< T ... > &o) const
Interval< T ... > getShifted (const Point< T ... > &p) const
template<typename X , int DIMENSION>
Interval< T ... > getReplaced (Interval< X > ix) const
template<typename X , int DIMENSION>
Interval< T ... > getFixed (X x) const
std::string str () const
Protected Member Functions
template<size_t ... IS>
void checkImpl (std::integer_sequence< size_t, IS... >) const
template<size_t ... IS>
bool containsImpl (const Point< T ... > &p, std::integer_sequence< size_t, IS... >) const
template<size_t ... IS>
Interval< T ... > intersectImpl (const Interval< T ... > &o, std::integer_sequence< size_t, IS... >) const
template<size_t ... IS>
double getVolumeImpl (std::integer_sequence< size_t, IS... >) const
template<size_t ... IS>
bool isEmptyImpl (std::integer_sequence< size_t, IS... >) const
Protected Attributes
Point< T ... > lower
Point< T ... > upper
unsigned char lowerClosed
unsigned char upperClosed
unsigned char fixed
Detailed Description
template<typename... T>
class inet::math::Interval< T >
N-dimensional interval (cuboid), given by its two opposite corners.
Constructor & Destructor Documentation
Interval()
template<typename... T> inet::math::Interval< T >::Interval (const Point< T ... > & lower, const Point< T ... > & upper, unsigned char lowerClosed, unsigned char upperClosed, unsigned char fixed) inline
                                                                                                                                               :
         lower(lower), upper(upper), lowerClosed(lowerClosed), upperClosed(upperClosed), fixed(fixed) {
 #ifndef NDEBUG
         checkImpl(std::index_sequence_for<T ...>{});
 #endif
     }
Member Function Documentation
checkImpl()
template<typename... T> template<size_t ... IS> void inet::math::Interval< T >::checkImpl (std::integer_sequence< size_t, IS... >) const inline protected
{
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         bool check = true;
         std::initializer_list<bool> l1{ check &= std::get<IS>(lower) <= std::get<IS>(upper) ... };
         (void)l1;
         if (!check)
             throw cRuntimeError("Invalid lower or upper arguments");
         check = true;
         std::initializer_list<bool> l2{ check &= (fixed & (b >> IS) ? lowerClosed & upperClosed & (b >> IS) && std::get<IS>(lower) == std::get<IS>(upper) : true) ... };
         (void)l2;
         if (!check)
             throw cRuntimeError("Invalid fixed argument, interval = %s, fixed = %d", str().c_str(), fixed);
         auto m = (1 << std::tuple_size<std::tuple<T ...>>::value) - 1;
         if (lowerClosed != (lowerClosed & m))
             throw cRuntimeError("Invalid lowerClosed argument");
         if (upperClosed != (upperClosed & m))
             throw cRuntimeError("Invalid upperClosed argument");
         if (fixed != (fixed & m))
             throw cRuntimeError("Invalid fixed argument");
         if (fixed != (lowerClosed & fixed))
             throw cRuntimeError("Invalid combination of fixed and lowerClosed arguments");
         if (fixed != (upperClosed & fixed))
             throw cRuntimeError("Invalid combination of fixed and upperClosed arguments");
     }
contains()
template<typename... T> bool inet::math::Interval< T >::contains (const Point< T ... > & p) const inline
{
         return containsImpl(p, std::index_sequence_for<T ...>{});
     }
containsImpl()
template<typename... T> template<size_t ... IS> bool inet::math::Interval< T >::containsImpl (const Point< T ... > & p, std::integer_sequence< size_t, IS... >) const inline protected
{
         bool result = true;
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         (void)std::initializer_list<bool>{ result &= ((lowerClosed & (b >> IS)) ? std::get<IS>(lower) <= std::get<IS>(p) : std::get<IS>(lower) < std::get<IS>(p)) ... };
         (void)std::initializer_list<bool>{ result &= ((upperClosed & (b >> IS)) ? std::get<IS>(p) <= std::get<IS>(upper) : std::get<IS>(p) < std::get<IS>(upper)) ... };
         return result;
     }
get()
template<typename... T> template<typename X , int DIMENSION> Interval<X> inet::math::Interval< T >::get () const inline
{
         unsigned char s = std::tuple_size<std::tuple<T ...>>::value - DIMENSION - 1;
         return Interval<X>(std::get<DIMENSION>(lower), std::get<DIMENSION>(upper), (lowerClosed >> s) & 0b1, (upperClosed >> s) & 0b1, (fixed >> s) & 0b1);
     }
getFixed() [1/2]
template<typename... T> unsigned char inet::math::Interval< T >::getFixed () const inline
 { return fixed; }
Referenced by inet::math::Interval< R >::intersectImpl(), inet::math::iterateCorners(), inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::partition(), inet::physicallayer::SpaceDependentAttenuationFunction::partition(), inet::math::Combined2DFunction< R, X, Y >::partition(), inet::physicallayer::BackgroundNoisePowerFunction::partition(), inet::physicallayer::PropagatedTransmissionPowerFunction::partition(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::partition(), inet::math::internal::print(), and inet::math::Interval< R >::set().
getFixed() [2/2]
template<typename... T> template<typename X , int DIMENSION> Interval<T ...> inet::math::Interval< T >::getFixed (X x) const inline
{
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         auto m = (b >> DIMENSION);
         Point<T ...> pl = lower;
         Point<T ...> pu = upper;
         std::get<DIMENSION>(pl) = x;
         std::get<DIMENSION>(pu) = x;
         return Interval<T ...>(pl, pu, lowerClosed | m, upperClosed | m, fixed | m);
     }
getIntersected()
template<typename... T> Interval<T ...> inet::math::Interval< T >::getIntersected (const Interval< T ... > & o) const inline
{
         return intersectImpl(o, std::index_sequence_for<T ...>{});
     }
Referenced by inet::math::Boxcar1DFunction< R, X >::partition(), inet::math::Boxcar2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::partition(), inet::math::Rasterized2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::partition(), and inet::math::Interpolated1DFunction< R, X >::partition().
getLower()
template<typename... T> const Point<T ...>& inet::math::Interval< T >::getLower () const inline
 { return lower; }
Referenced by inet::math::Extruded2DFunction< R, X, Y >::isFinite(), inet::math::Boxcar1DFunction< R, X >::isNonZero(), inet::math::Boxcar2DFunction< R, X, Y >::isNonZero(), inet::math::iterateCorners(), inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::partition(), inet::physicallayer::SpaceDependentAttenuationFunction::partition(), inet::math::Combined2DFunction< R, X, Y >::partition(), inet::physicallayer::BackgroundNoisePowerFunction::partition(), inet::physicallayer::PropagatedTransmissionPowerFunction::partition(), inet::math::Extruded2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::partition(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::partition(), inet::math::Interpolated1DFunction< R, X >::partition(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::partition(), inet::math::internal::print(), and inet::math::Interval< R >::set().
getLowerClosed()
template<typename... T> unsigned char inet::math::Interval< T >::getLowerClosed () const inline
 { return lowerClosed; }
Referenced by inet::math::iterateCorners(), inet::math::Combined2DFunction< R, X, Y >::partition(), inet::physicallayer::BackgroundNoisePowerFunction::partition(), inet::physicallayer::PropagatedTransmissionPowerFunction::partition(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::partition(), inet::math::internal::print(), and inet::math::Interval< R >::set().
getReplaced()
template<typename... T> template<typename X , int DIMENSION> Interval<T ...> inet::math::Interval< T >::getReplaced (Interval< X > ix) const inline
{
         Interval<T ...> i = *this;
         i.template set<X, DIMENSION>(ix);
         return i;
     }
getShifted()
template<typename... T> Interval<T ...> inet::math::Interval< T >::getShifted (const Point< T ... > & p) const inline
{
         return Interval<T ...>(lower + p, upper + p, lowerClosed, upperClosed, fixed);
     }
getUpper()
template<typename... T> const Point<T ...>& inet::math::Interval< T >::getUpper () const inline
 { return upper; }
Referenced by inet::math::Extruded2DFunction< R, X, Y >::isFinite(), inet::math::Boxcar1DFunction< R, X >::isNonZero(), inet::math::Boxcar2DFunction< R, X, Y >::isNonZero(), inet::math::iterateCorners(), inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::partition(), inet::physicallayer::SpaceDependentAttenuationFunction::partition(), inet::math::Combined2DFunction< R, X, Y >::partition(), inet::physicallayer::BackgroundNoisePowerFunction::partition(), inet::physicallayer::PropagatedTransmissionPowerFunction::partition(), inet::math::Extruded2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::partition(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::partition(), inet::math::Interpolated1DFunction< R, X >::partition(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::partition(), inet::math::internal::print(), and inet::math::Interval< R >::set().
getUpperClosed()
template<typename... T> unsigned char inet::math::Interval< T >::getUpperClosed () const inline
 { return upperClosed; }
Referenced by inet::math::Extruded2DFunction< R, X, Y >::isFinite(), inet::math::iterateCorners(), inet::math::Combined2DFunction< R, X, Y >::partition(), inet::physicallayer::BackgroundNoisePowerFunction::partition(), inet::physicallayer::PropagatedTransmissionPowerFunction::partition(), inet::math::Extruded2DFunction< R, X, Y >::partition(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::partition(), inet::math::internal::print(), and inet::math::Interval< R >::set().
getVolume()
template<typename... T> double inet::math::Interval< T >::getVolume () const inline
Returns the volume in the dimensions denoted by the 1 bits of dims.
{
         return getVolumeImpl(std::index_sequence_for<T ...>{});
     }
getVolumeImpl()
template<typename... T> template<size_t ... IS> double inet::math::Interval< T >::getVolumeImpl (std::integer_sequence< size_t, IS... >) const inline protected
{
         double result = 1;
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         (void)std::initializer_list<double>{ result *= ((fixed & (b >> IS)) ? 1 : toDouble(std::get<IS>(upper) - std::get<IS>(lower))) ... };
         return result;
     }
intersectImpl()
template<typename... T> template<size_t ... IS> Interval<T ...> inet::math::Interval< T >::intersectImpl (const Interval< T ... > & o, std::integer_sequence< size_t, IS... >) const inline protected
{
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         Point<T ...> l(math::maxnan(std::get<IS>(lower), std::get<IS>(o.lower)) ...);
         (void)l;
         Point<T ...> u(math::minnan(std::get<IS>(upper), std::get<IS>(o.upper)) ...);
         (void)u;
         unsigned char lc = 0;
         unsigned char uc = 0;
         (void)std::initializer_list<unsigned char>{ lc += ((b >> IS) & (std::get<IS>(upper) < std::get<IS>(l) || std::get<IS>(lower) > std::get<IS>(u) ? 0 :
                                                                          (std::get<IS>(lower) == std::get<IS>(o.lower) ? (lowerClosed & o.lowerClosed) :
                                                                           (std::get<IS>(lower) > std::get<IS>(o.lower) ? lowerClosed : o.lowerClosed)))) ... };
         (void)std::initializer_list<unsigned char>{ uc += ((b >> IS) & (std::get<IS>(lower) > std::get<IS>(u) || std::get<IS>(upper) < std::get<IS>(l) ? 0 :
                                                                          (std::get<IS>(upper) == std::get<IS>(o.upper) ? (upperClosed & o.upperClosed) :
                                                                           (std::get<IS>(upper) < std::get<IS>(o.upper) ? upperClosed : o.upperClosed)))) ... };
         Point<T ...> l1(math::minnan(std::get<IS>(upper), std::get<IS>(l)) ...);
         Point<T ...> u1(math::maxnan(std::get<IS>(lower), std::get<IS>(u)) ...);
         return Interval<T ...>(l1, u1, lc, uc, (fixed | o.getFixed()) & lc & uc);
     }
isEmpty()
template<typename... T> bool inet::math::Interval< T >::isEmpty () const inline
Returns true iff getVolume() == 0.
{
         return isEmptyImpl(std::index_sequence_for<T ...>{});
     }
Referenced by inet::math::Boxcar2DFunction< R, X, Y >::call(), inet::math::Rasterized2DFunction< R, X, Y >::call(), and inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::call().
isEmptyImpl()
template<typename... T> template<size_t ... IS> bool inet::math::Interval< T >::isEmptyImpl (std::integer_sequence< size_t, IS... >) const inline protected
{
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         bool result = false;
         (void)std::initializer_list<bool>{ result |= ((fixed & (b >> IS)) ? false : std::get<IS>(lower) == std::get<IS>(upper)) ... };
         return result;
     }
set()
template<typename... T> template<typename X , int DIMENSION> void inet::math::Interval< T >::set (const Interval< X > & ix) inline
{
         unsigned char s = std::tuple_size<std::tuple<T ...>>::value - DIMENSION - 1;
         unsigned char b = 1 << std::tuple_size<std::tuple<T ...>>::value >> 1;
         auto m = (b >> DIMENSION);
         std::get<DIMENSION>(lower) = std::get<0>(ix.getLower());
         std::get<DIMENSION>(upper) = std::get<0>(ix.getUpper());
         lowerClosed = (lowerClosed & ~m) | (ix.getLowerClosed() << s);
         upperClosed = (upperClosed & ~m) | (ix.getUpperClosed() << s);
         fixed = (fixed & ~m) | (ix.getFixed() << s);
     }
str()
template<typename... T> std::string inet::math::Interval< T >::str () const inline
{
         std::stringstream os;
         os << *this;
         return os.str();
     }
Member Data Documentation
fixed
template<typename... T> unsigned char inet::math::Interval< T >::fixed protected
lower
template<typename... T> Point<T ...> inet::math::Interval< T >::lower protected
Referenced by inet::math::Interval< R >::intersectImpl().
lowerClosed
template<typename... T> unsigned char inet::math::Interval< T >::lowerClosed protected
Referenced by inet::math::Interval< R >::intersectImpl().
upper
template<typename... T> Point<T ...> inet::math::Interval< T >::upper protected
Referenced by inet::math::Interval< R >::intersectImpl().
upperClosed
template<typename... T> unsigned char inet::math::Interval< T >::upperClosed protected
Referenced by inet::math::Interval< R >::intersectImpl().
The documentation for this class was generated from the following file:
Interval.h