INET Framework for OMNeT++/OMNEST: inet::power::AlternatingEpEnergyGenerator Class Reference
inet::power::AlternatingEpEnergyGenerator Class Reference
This class implements a simple power based alternating energy generator.
#include <AlternatingEpEnergyGenerator.h>
Public Member Functions
virtual ~AlternatingEpEnergyGenerator ()
virtual IEnergySink * getEnergySink () const override
Returns the energy sink that absorbs energy from this energy generator.
virtual W getPowerGeneration () const override
Returns the power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergyGenerator
virtual ~IEnergyGenerator ()
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void updatePowerGeneration ()
virtual void scheduleIntervalTimer ()
Protected Attributes
IEpEnergySink * energySink = nullptr
cMessage * timer = nullptr
bool isSleeping = false
W powerGeneration = W(NaN)
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergyGenerator
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Detailed Description
This class implements a simple power based alternating energy generator.
See the corresponding NED file for more details.
Constructor & Destructor Documentation
~AlternatingEpEnergyGenerator()
inet::power::AlternatingEpEnergyGenerator::~AlternatingEpEnergyGenerator () virtual
 {
     cancelAndDelete(timer);
 }
Member Function Documentation
getEnergySink()
virtual IEnergySink* inet::power::AlternatingEpEnergyGenerator::getEnergySink () const inline override virtual
Returns the energy sink that absorbs energy from this energy generator.
This function never returns nullptr.
Implements inet::power::IEnergyGenerator.
 { return energySink; }
getPowerGeneration()
virtual W inet::power::AlternatingEpEnergyGenerator::getPowerGeneration () const inline override virtual
Returns the power generation in the range [0, +infinity).
Implements inet::power::IEpEnergyGenerator.
 { return powerGeneration; }
handleMessage()
void inet::power::AlternatingEpEnergyGenerator::handleMessage (cMessage * message) override protected virtual
 {
     if (message == timer) {
         isSleeping = !isSleeping;
         updatePowerGeneration();
         scheduleIntervalTimer();
     }
     else
         throw cRuntimeError("Unknown message");
 }
initialize()
void inet::power::AlternatingEpEnergyGenerator::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         const char *energySinkModule = par("energySinkModule");
         energySink = dynamic_cast<IEpEnergySink *>(getModuleByPath(energySinkModule));
         if (!energySink)
             throw cRuntimeError("Energy sink module '%s' not found", energySinkModule);
         timer = new cMessage("timer");
         updatePowerGeneration();
         scheduleIntervalTimer();
         WATCH(isSleeping);
         WATCH(powerGeneration);
     }
     else if (stage == INITSTAGE_POWER)
         energySink->addEnergyGenerator(this);
 }
numInitStages()
virtual int inet::power::AlternatingEpEnergyGenerator::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
scheduleIntervalTimer()
void inet::power::AlternatingEpEnergyGenerator::scheduleIntervalTimer () protected virtual
 {
     scheduleAfter((isSleeping ? par("sleepInterval") : par("generationInterval")), timer);
 }
Referenced by handleMessage(), and initialize().
updatePowerGeneration()
void inet::power::AlternatingEpEnergyGenerator::updatePowerGeneration () protected virtual
 {
     powerGeneration = isSleeping ? W(0) : W(par("powerGeneration"));
     emit(IEpEnergySink::powerGenerationChangedSignal, powerGeneration.get());
     auto text = "power: " + powerGeneration.str();
     getDisplayString().setTagArg("t", 0, text.c_str());
 }
Referenced by handleMessage(), and initialize().
Member Data Documentation
energySink
IEpEnergySink* inet::power::AlternatingEpEnergyGenerator::energySink = nullptr protected
Referenced by initialize().
isSleeping
bool inet::power::AlternatingEpEnergyGenerator::isSleeping = false protected
Referenced by handleMessage(), initialize(), scheduleIntervalTimer(), and updatePowerGeneration().
powerGeneration
W inet::power::AlternatingEpEnergyGenerator::powerGeneration = W(NaN) protected
Referenced by initialize(), and updatePowerGeneration().
timer
cMessage* inet::power::AlternatingEpEnergyGenerator::timer = nullptr protected
Referenced by handleMessage(), initialize(), scheduleIntervalTimer(), and ~AlternatingEpEnergyGenerator().
The documentation for this class was generated from the following files:
AlternatingEpEnergyGenerator.h
AlternatingEpEnergyGenerator.cc