INET Framework for OMNeT++/OMNEST: inet::bgp::BgpOptionalParameterBase Class Reference
inet::bgp::BgpOptionalParameterBase Class Reference
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:72 by opp_msgtool.
#include <BgpHeader_m.h>
Public Member Functions
BgpOptionalParameterBase ()
BgpOptionalParameterBase (const BgpOptionalParameterBase &other)
virtual ~BgpOptionalParameterBase ()
BgpOptionalParameterBase & operator= (const BgpOptionalParameterBase &other)
virtual void parsimPack (omnetpp::cCommBuffer *b) const
virtual void parsimUnpack (omnetpp::cCommBuffer *b)
virtual short getParameterType () const
virtual void setParameterType (short parameterType)
virtual unsigned short getParameterValueLength () const
virtual void setParameterValueLength (unsigned short parameterValueLength)
Protected Member Functions
bool operator== (const BgpOptionalParameterBase &)=delete
Protected Attributes
short parameterType = 0
unsigned short parameterValueLength = 0
Private Member Functions
void copy (const BgpOptionalParameterBase &other)
Detailed Description
Class generated from inet/routing/bgpv4/bgpmessage/BgpHeader.msg:72 by opp_msgtool.
class BgpOptionalParameterBase
{
    @packetData;
    short parameterType;
    unsigned short parameterValueLength;
}
//TODO add accepted BgpOptionalParameter variants
Constructor & Destructor Documentation
BgpOptionalParameterBase() [1/2]
inet::bgp::BgpOptionalParameterBase::BgpOptionalParameterBase ()
BgpOptionalParameterBase() [2/2]
inet::bgp::BgpOptionalParameterBase::BgpOptionalParameterBase (const BgpOptionalParameterBase & other)
~BgpOptionalParameterBase()
virtual inet::bgp::BgpOptionalParameterBase::~BgpOptionalParameterBase () virtual
Member Function Documentation
copy()
void inet::bgp::BgpOptionalParameterBase::copy (const BgpOptionalParameterBase & other) private
getParameterType()
virtual short inet::bgp::BgpOptionalParameterBase::getParameterType () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
getParameterValueLength()
virtual unsigned short inet::bgp::BgpOptionalParameterBase::getParameterValueLength () const virtual
Referenced by inet::bgp::BgpHeaderSerializer::serialize().
operator=()
BgpOptionalParameterBase& inet::bgp::BgpOptionalParameterBase::operator= (const BgpOptionalParameterBase & other)
operator==()
bool inet::bgp::BgpOptionalParameterBase::operator== (const BgpOptionalParameterBase &) protected delete
parsimPack()
virtual void inet::bgp::BgpOptionalParameterBase::parsimPack (omnetpp::cCommBuffer * b) const virtual
Reimplemented in inet::bgp::BgpOptionalParameterRaw.
parsimUnpack()
virtual void inet::bgp::BgpOptionalParameterBase::parsimUnpack (omnetpp::cCommBuffer * b) virtual
Reimplemented in inet::bgp::BgpOptionalParameterRaw.
setParameterType()
virtual void inet::bgp::BgpOptionalParameterBase::setParameterType (short parameterType) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
setParameterValueLength()
virtual void inet::bgp::BgpOptionalParameterBase::setParameterValueLength (unsigned short parameterValueLength) virtual
Referenced by inet::bgp::BgpHeaderSerializer::deserialize().
Member Data Documentation
parameterType
short inet::bgp::BgpOptionalParameterBase::parameterType = 0 protected
parameterValueLength
unsigned short inet::bgp::BgpOptionalParameterBase::parameterValueLength = 0 protected
The documentation for this class was generated from the following file:
BgpHeader_m.h