INET Framework for OMNeT++/OMNEST: inet::Topology::Link Class Reference
inet::Topology::Link Class Reference
Supporting class for Topology, represents a link in the graph.
#include <Topology.h>
Public Member Functions
Link (double weight=1)
Constructor.
virtual ~Link ()
double getWeight () const
Returns the weight of this link.
void setWeight (double d)
Sets the weight of this link.
bool isEnabled () const
Returns true of this link is enabled.
void enable ()
Enables this link.
void disable ()
Disables this link.
Node * getLinkInRemoteNode () const
Returns the node at the remote end of this connection.
Node * getLinkInLocalNode () const
Returns the node at the local end of this connection.
int getLinkInRemoteGateId () const
Returns the gate ID at the remote end of this connection.
int getLinkInLocalGateId () const
Returns the gate ID at the local end of this connection.
cGate * getLinkInRemoteGate () const
Returns the gate at the remote end of this connection.
cGate * getLinkInLocalGate () const
Returns the gate at the local end of this connection.
Node * getLinkOutRemoteNode () const
Returns the node at the remote end of this connection.
Node * getLinkOutLocalNode () const
Returns the node at the local end of this connection.
int getLinkOutRemoteGateId () const
Returns the gate ID at the remote end of this connection.
int getLinkOutLocalGateId () const
Returns the gate ID at the local end of this connection.
cGate * getLinkOutRemoteGate () const
Returns the gate at the remote end of this connection.
cGate * getLinkOutLocalGate () const
Returns the gate at the local end of this connection.
Protected Attributes
Node * srcNode
int srcGateId
Node * destNode
int destGateId
double weight
bool enabled
Friends
class Topology
Detailed Description
Supporting class for Topology, represents a link in the graph.
Constructor & Destructor Documentation
Link()
inet::Topology::Link::Link (double weight = 1) inline
Constructor.
 { srcNode = destNode = nullptr; srcGateId = destGateId = -1; this->weight = weight; enabled = true; }
~Link()
virtual inet::Topology::Link::~Link () inline virtual
 {}
Member Function Documentation
disable()
void inet::Topology::Link::disable () inline
Disables this link.
This has significance with the shortest path finder methods of Topology.
 { enabled = false; }
enable()
void inet::Topology::Link::enable () inline
Enables this link.
This has significance with the shortest path finder methods of Topology.
 { enabled = true; }
getLinkInLocalGate()
cGate* inet::Topology::Link::getLinkInLocalGate () const inline
Returns the gate at the local end of this connection.
 { return destNode->getModule()->gate(destGateId); }
getLinkInLocalGateId()
int inet::Topology::Link::getLinkInLocalGateId () const inline
Returns the gate ID at the local end of this connection.
 { return destGateId; }
getLinkInLocalNode()
Node* inet::Topology::Link::getLinkInLocalNode () const inline
Returns the node at the local end of this connection.
 { return destNode; }
Referenced by inet::L3NetworkConfiguratorBase::dumpTopology().
getLinkInRemoteGate()
cGate* inet::Topology::Link::getLinkInRemoteGate () const inline
Returns the gate at the remote end of this connection.
 { return srcNode->getModule()->gate(srcGateId); }
getLinkInRemoteGateId()
int inet::Topology::Link::getLinkInRemoteGateId () const inline
Returns the gate ID at the remote end of this connection.
 { return srcGateId; }
getLinkInRemoteNode()
Node* inet::Topology::Link::getLinkInRemoteNode () const inline
Returns the node at the remote end of this connection.
 { return srcNode; }
Referenced by inet::Topology::calculateWeightedSingleShortestPathsTo(), inet::L3NetworkConfiguratorBase::dumpTopology(), and inet::NetworkConfiguratorBase::findLinkIn().
getLinkOutLocalGate()
cGate* inet::Topology::Link::getLinkOutLocalGate () const inline
Returns the gate at the local end of this connection.
 { return srcNode->getModule()->gate(srcGateId); }
Referenced by inet::L3NetworkConfiguratorBase::computeWiredLinkWeight().
getLinkOutLocalGateId()
int inet::Topology::Link::getLinkOutLocalGateId () const inline
Returns the gate ID at the local end of this connection.
 { return srcGateId; }
Referenced by inet::NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::NetworkConfiguratorBase::findLinkOut(), inet::L2NetworkConfigurator::findLinkOut(), and inet::L3NetworkConfiguratorBase::findLinkOut().
getLinkOutLocalNode()
Node* inet::Topology::Link::getLinkOutLocalNode () const inline
Returns the node at the local end of this connection.
 { return srcNode; }
Referenced by inet::L3NetworkConfiguratorBase::dumpTopology(), inet::NetworkConfiguratorBase::extractTopology(), and inet::L3NetworkConfiguratorBase::extractTopology().
getLinkOutRemoteGate()
cGate* inet::Topology::Link::getLinkOutRemoteGate () const inline
Returns the gate at the remote end of this connection.
 { return destNode->getModule()->gate(destGateId); }
Referenced by inet::StpTester::dfsVisit().
getLinkOutRemoteGateId()
int inet::Topology::Link::getLinkOutRemoteGateId () const inline
Returns the gate ID at the remote end of this connection.
 { return destGateId; }
Referenced by inet::NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), and inet::L3NetworkConfiguratorBase::extractWiredNeighbors().
getLinkOutRemoteNode()
Node* inet::Topology::Link::getLinkOutRemoteNode () const inline
Returns the node at the remote end of this connection.
 { return destNode; }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::FailureProtectionConfigurator::collectAllPaths(), inet::NetworkConfiguratorBase::computeShortestLinkPath(), inet::NetworkConfiguratorBase::computeShortestNodePath(), inet::StpTester::dfsVisit(), inet::L3NetworkConfiguratorBase::dumpTopology(), inet::NetworkConfiguratorBase::extractTopology(), inet::L2NetworkConfigurator::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::extractWiredNeighbors(), and inet::NetworkConfiguratorBase::findLinkOut().
getWeight()
double inet::Topology::Link::getWeight () const inline
Returns the weight of this link.
Weight is used with the weighted shortest path finder methods of Topology.
 { return weight; }
Referenced by inet::Topology::calculateWeightedSingleShortestPathsTo().
isEnabled()
bool inet::Topology::Link::isEnabled () const inline
Returns true of this link is enabled.
This has significance with the shortest path finder methods of Topology.
 { return enabled; }
Referenced by inet::Topology::calculateWeightedSingleShortestPathsTo().
setWeight()
void inet::Topology::Link::setWeight (double d) inline
Sets the weight of this link.
Weight is used with the weighted shortest path finder methods of Topology.
 { weight = d; }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), and inet::MacForwardingTableConfigurator::extendConfiguration().
Friends And Related Function Documentation
Topology
friend class Topology friend
Member Data Documentation
destGateId
int inet::Topology::Link::destGateId protected
Referenced by inet::Topology::addLink(), and inet::Topology::extractFromNetwork().
destNode
Node* inet::Topology::Link::destNode protected
Referenced by inet::Topology::addLink(), inet::Topology::extractFromNetwork(), and inet::Topology::unlinkFromDestNode().
enabled
bool inet::Topology::Link::enabled protected
srcGateId
int inet::Topology::Link::srcGateId protected
Referenced by inet::Topology::addLink(), and inet::Topology::extractFromNetwork().
srcNode
Node* inet::Topology::Link::srcNode protected
Referenced by inet::Topology::addLink(), inet::Topology::extractFromNetwork(), and inet::Topology::unlinkFromSourceNode().
weight
double inet::Topology::Link::weight protected
The documentation for this class was generated from the following file:
Topology.h