INET Framework for OMNeT++/OMNEST: inet::physicallayer::INarrowbandSignal Class Reference
inet::physicallayer::INarrowbandSignal Class Reference abstract
#include <IRadioSignal.h>
Public Member Functions
virtual Hz getCenterFrequency () const =0
virtual Hz getBandwidth () const =0
virtual W computeMinPower (simtime_t startTime, simtime_t endTime) const =0
Member Function Documentation
computeMinPower()
virtual W inet::physicallayer::INarrowbandSignal::computeMinPower (simtime_t startTime, simtime_t endTime) const pure virtual
Implemented in inet::physicallayer::DimensionalSignalAnalogModel, inet::physicallayer::DimensionalReception, inet::physicallayer::ScalarSignalAnalogModel, inet::physicallayer::ScalarReception, inet::physicallayer::FlatReceptionBase, inet::physicallayer::DimensionalTransmission, and inet::physicallayer::ScalarTransmission.
Referenced by inet::physicallayer::ApskLayeredReceiver::computeIsReceptionPossible(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeIsReceptionPossible().
getBandwidth()
virtual Hz inet::physicallayer::INarrowbandSignal::getBandwidth () const pure virtual
Implemented in inet::physicallayer::NarrowbandSignalAnalogModel, inet::physicallayer::NarrowbandTransmissionBase, and inet::physicallayer::NarrowbandReceptionBase.
Referenced by inet::physicallayer::ScalarAnalogModelBase::computeNoise(), and inet::physicallayer::ScalarAnalogModel::computeReception().
getCenterFrequency()
virtual Hz inet::physicallayer::INarrowbandSignal::getCenterFrequency () const pure virtual
Implemented in inet::physicallayer::NarrowbandSignalAnalogModel, inet::physicallayer::NarrowbandTransmissionBase, and inet::physicallayer::NarrowbandReceptionBase.
Referenced by inet::physicallayer::ScalarAnalogModelBase::computeNoise(), inet::physicallayer::ScalarAnalogModel::computeReception(), and inet::physicallayer::ScalarAnalogModelBase::computeReceptionPower().
The documentation for this class was generated from the following file:
IRadioSignal.h