INET Framework for OMNeT++/OMNEST: inet::ieee80211::IFrameSequenceHandler Class Reference
inet::ieee80211::IFrameSequenceHandler Class Reference abstract
#include <IFrameSequenceHandler.h>
Classes
class ICallback
Public Member Functions
virtual ~IFrameSequenceHandler ()
virtual const FrameSequenceContext * getContext () const =0
virtual const IFrameSequence * getFrameSequence () const =0
virtual void startFrameSequence (IFrameSequence *frameSequence, FrameSequenceContext *context, ICallback *callback)=0
virtual void processResponse (Packet *frame)=0
virtual void transmissionComplete ()=0
virtual bool isSequenceRunning ()=0
virtual void handleStartRxTimeout ()=0
Static Public Attributes
static simsignal_t frameSequenceStartedSignal = cComponent::registerSignal("frameSequenceStarted")
static simsignal_t frameSequenceFinishedSignal = cComponent::registerSignal("frameSequenceFinished")
Constructor & Destructor Documentation
~IFrameSequenceHandler()
virtual inet::ieee80211::IFrameSequenceHandler::~IFrameSequenceHandler () inline virtual
 {}
Member Function Documentation
getContext()
virtual const FrameSequenceContext* inet::ieee80211::IFrameSequenceHandler::getContext () const pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
getFrameSequence()
virtual const IFrameSequence* inet::ieee80211::IFrameSequenceHandler::getFrameSequence () const pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
handleStartRxTimeout()
virtual void inet::ieee80211::IFrameSequenceHandler::handleStartRxTimeout () pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
isSequenceRunning()
virtual bool inet::ieee80211::IFrameSequenceHandler::isSequenceRunning () pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
processResponse()
virtual void inet::ieee80211::IFrameSequenceHandler::processResponse (Packet * frame) pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
startFrameSequence()
virtual void inet::ieee80211::IFrameSequenceHandler::startFrameSequence (IFrameSequence * frameSequence, FrameSequenceContext * context, ICallback * callback) pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
transmissionComplete()
virtual void inet::ieee80211::IFrameSequenceHandler::transmissionComplete () pure virtual
Implemented in inet::ieee80211::FrameSequenceHandler.
Member Data Documentation
frameSequenceFinishedSignal
simsignal_t inet::ieee80211::IFrameSequenceHandler::frameSequenceFinishedSignal = cComponent::registerSignal("frameSequenceFinished") static
Referenced by inet::ieee80211::Dcf::frameSequenceFinished(), and inet::ieee80211::Hcf::frameSequenceFinished().
frameSequenceStartedSignal
simsignal_t inet::ieee80211::IFrameSequenceHandler::frameSequenceStartedSignal = cComponent::registerSignal("frameSequenceStarted") static
Referenced by inet::ieee80211::Dcf::channelGranted(), and inet::ieee80211::Hcf::startFrameSequence().
The documentation for this class was generated from the following files:
IFrameSequenceHandler.h
IFrameSequenceHandler.cc