INET Framework for OMNeT++/OMNEST: inet::TcpConnectInfo Class Reference
inet::TcpConnectInfo Class Reference
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:176 by opp_msgtool.
#include <TcpCommand_m.h>
Public Member Functions
TcpConnectInfo ()
TcpConnectInfo (const TcpConnectInfo &other)
virtual ~TcpConnectInfo ()
TcpConnectInfo & operator= (const TcpConnectInfo &other)
virtual TcpConnectInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
Public Member Functions inherited from inet::TcpCommand
TcpCommand ()
TcpCommand (const TcpCommand &other)
virtual ~TcpCommand ()
TcpCommand & operator= (const TcpCommand &other)
virtual int getUserId () const
virtual void setUserId (int userId)
Protected Member Functions
bool operator== (const TcpConnectInfo &)=delete
Protected Member Functions inherited from inet::TcpCommand
bool operator== (const TcpCommand &)=delete
Protected Attributes
L3Address localAddr
L3Address remoteAddr
int localPort = 0
int remotePort = 0
Protected Attributes inherited from inet::TcpCommand
int userId = -1
Private Member Functions
void copy (const TcpConnectInfo &other)
Detailed Description
Class generated from inet/transportlayer/contract/tcp/TcpCommand.msg:176 by opp_msgtool.
//
// Sent with message kind TCP_I_ESTABLISHED, to let the app know
// about the local and remote IP address and port.
//
// @see ~TcpCommandCode, ~ITcp
//
class TcpConnectInfo extends TcpCommand
{
    L3Address localAddr;
    L3Address remoteAddr;
    int localPort;
    int remotePort;
}
Constructor & Destructor Documentation
TcpConnectInfo() [1/2]
inet::TcpConnectInfo::TcpConnectInfo ()
TcpConnectInfo() [2/2]
inet::TcpConnectInfo::TcpConnectInfo (const TcpConnectInfo & other)
~TcpConnectInfo()
virtual inet::TcpConnectInfo::~TcpConnectInfo () virtual
Member Function Documentation
copy()
void inet::TcpConnectInfo::copy (const TcpConnectInfo & other) private
dup()
virtual TcpConnectInfo* inet::TcpConnectInfo::dup () const inline override virtual
Reimplemented from inet::TcpCommand.
 {return new TcpConnectInfo(*this);}
getLocalAddr()
virtual const L3Address& inet::TcpConnectInfo::getLocalAddr () const virtual
Referenced by inet::TcpSocket::processMessage(), and inet::TcpSocket::TcpSocket().
getLocalAddrForUpdate()
virtual L3Address& inet::TcpConnectInfo::getLocalAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<TcpConnectInfo*>(this)->getLocalAddr());}
getLocalPort()
virtual int inet::TcpConnectInfo::getLocalPort () const virtual
Referenced by inet::TcpSocket::processMessage(), and inet::TcpSocket::TcpSocket().
getRemoteAddr()
virtual const L3Address& inet::TcpConnectInfo::getRemoteAddr () const virtual
Referenced by inet::TcpSocket::processMessage(), and inet::TcpSocket::TcpSocket().
getRemoteAddrForUpdate()
virtual L3Address& inet::TcpConnectInfo::getRemoteAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<TcpConnectInfo*>(this)->getRemoteAddr());}
getRemotePort()
virtual int inet::TcpConnectInfo::getRemotePort () const virtual
Referenced by inet::TcpSocket::processMessage(), and inet::TcpSocket::TcpSocket().
operator=()
TcpConnectInfo& inet::TcpConnectInfo::operator= (const TcpConnectInfo & other)
operator==()
bool inet::TcpConnectInfo::operator== (const TcpConnectInfo &) protected delete
parsimPack()
virtual void inet::TcpConnectInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::TcpCommand.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TcpConnectInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::TcpCommand.
Referenced by inet::doParsimUnpacking().
setLocalAddr()
virtual void inet::TcpConnectInfo::setLocalAddr (const L3Address & localAddr) virtual
Referenced by inet::tcp::TcpConnection::sendEstabIndicationToApp(), and inet::tcp::TcpLwipConnection::sendEstablishedMsg().
setLocalPort()
virtual void inet::TcpConnectInfo::setLocalPort (int localPort) virtual
Referenced by inet::tcp::TcpConnection::sendEstabIndicationToApp(), and inet::tcp::TcpLwipConnection::sendEstablishedMsg().
setRemoteAddr()
virtual void inet::TcpConnectInfo::setRemoteAddr (const L3Address & remoteAddr) virtual
Referenced by inet::tcp::TcpConnection::sendEstabIndicationToApp(), and inet::tcp::TcpLwipConnection::sendEstablishedMsg().
setRemotePort()
virtual void inet::TcpConnectInfo::setRemotePort (int remotePort) virtual
Referenced by inet::tcp::TcpConnection::sendEstabIndicationToApp(), and inet::tcp::TcpLwipConnection::sendEstablishedMsg().
Member Data Documentation
localAddr
L3Address inet::TcpConnectInfo::localAddr protected
localPort
int inet::TcpConnectInfo::localPort = 0 protected
remoteAddr
L3Address inet::TcpConnectInfo::remoteAddr protected
remotePort
int inet::TcpConnectInfo::remotePort = 0 protected
The documentation for this class was generated from the following file:
TcpCommand_m.h