INET Framework for OMNeT++/OMNEST: inet::queueing::PacketClassifierBase Class Reference
inet::queueing::PacketClassifierBase Class Reference abstract
#include <PacketClassifierBase.h>
Public Member Functions
virtual IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
virtual bool canPullSomePacket (cGate *gate) const override
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const override
Returns the packet that can be pulled at the given gate.
virtual Packet * pullPacket (cGate *gate) override
Pulls the packet from the packet source at the given gate.
virtual Packet * pullPacketStart (cGate *gate, bps datarate) override
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate) override
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength) override
Progresses pulling the packet from the packet source at the given gate.
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::TransparentProtocolRegistrationListener
virtual cGate * getRegistrationForwardingGate (cGate *gate)
virtual bool isForwardingProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingProtocol (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingAnyService (cGate *gate, ServicePrimitive servicePrimitive) const
virtual bool isForwardingService (cGate *gate, ServicePrimitive servicePrimitive) const
virtual void handleRegisterService (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocol (const Protocol &protocol, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterServiceGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterProtocolGroup (const ProtocolGroup &protocolGroup, cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyService (cGate *gate, ServicePrimitive servicePrimitive) override
virtual void handleRegisterAnyProtocol (cGate *gate, ServicePrimitive servicePrimitive) override
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void mapRegistrationForwardingGates (cGate *gate, std::function< void(cGate *)> f) override
virtual size_t getOutputGateIndex (size_t i) const
virtual int classifyPacket (Packet *packet)=0
virtual int callClassifyPacket (Packet *packet) const
virtual bool isStreamingPacket () const
virtual void startPacketStreaming (Packet *packet)
virtual void endPacketStreaming (Packet *packet)
virtual void checkPacketStreaming (Packet *packet)
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
bool reverseOrder = false
cGate * inputGate = nullptr
IActivePacketSource * producer = nullptr
IPassivePacketSource * provider = nullptr
std::vector< cGate * > outputGates
std::vector< IPassivePacketSink * > consumers
std::vector< IActivePacketSink * > collectors
int inProgressStreamId = -1
int inProgressGateIndex = -1
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
callClassifyPacket()
int inet::queueing::PacketClassifierBase::callClassifyPacket (Packet * packet) const protected virtual
 {
     // KLUDGE
     int index = const_cast<PacketClassifierBase *>(this)->classifyPacket(packet);
     if (index < 0 || static_cast<unsigned int>(index) >= outputGates.size())
         throw cRuntimeError("Classified packet to invalid output gate: %d", index);
     return index;
 }
Referenced by canPullPacket(), handleCanPullPacketChanged(), pullPacket(), pushPacket(), and startPacketStreaming().
canPullPacket()
Packet * inet::queueing::PacketClassifierBase::canPullPacket (cGate * gate) const override virtual
Returns the packet that can be pulled at the given gate.
The returned value is nullptr if there is no such packet.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::MarkovClassifier.
 {
     auto packet = provider->canPullPacket(inputGate->getPathStartGate());
     if (packet == nullptr)
         return nullptr;
     else {
         int index = callClassifyPacket(packet);
         return index == gate->getIndex() ? packet : nullptr;
     }
 }
Referenced by canPullSomePacket().
canPullSomePacket()
bool inet::queueing::PacketClassifierBase::canPullSomePacket (cGate * gate) const override virtual
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
The gate must be a valid gate of this module and it must support pulling packets.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::MarkovClassifier.
 {
     return canPullPacket(gate) != nullptr;
 }
canPushPacket()
bool inet::queueing::PacketClassifierBase::canPushPacket (Packet * packet, cGate * gate) const override virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::queueing::PriorityClassifier.
 {
     return canPushSomePacket(gate);
 }
canPushSomePacket()
bool inet::queueing::PacketClassifierBase::canPushSomePacket (cGate * gate) const override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::queueing::PriorityClassifier.
 {
     for (int i = 0; i < (int)outputGates.size(); i++)
         if (!consumers[i]->canPushSomePacket(outputGates[i]->getPathEndGate()))
             return false;
     return true;
 }
Referenced by canPushPacket(), and inet::queueing::WrrClassifier::classifyPacket().
checkPacketStreaming()
void inet::queueing::PacketClassifierBase::checkPacketStreaming (Packet * packet) protected virtual
 {
     if (inProgressStreamId != -1 && (packet == nullptr || packet->getTreeId() != inProgressStreamId))
         throw cRuntimeError("Another packet streaming operation is already in progress");
 }
Referenced by pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
classifyPacket()
virtual int inet::queueing::PacketClassifierBase::classifyPacket (Packet * packet) protected pure virtual
Implemented in inet::MultiFieldClassifier, inet::BehaviorAggregateClassifier, inet::queueing::MarkovClassifier, inet::queueing::WrrClassifier, inet::EthernetFrameClassifier, inet::queueing::DynamicClassifier, inet::StreamClassifier, inet::queueing::ContentBasedClassifier, inet::queueing::PacketClassifier, inet::PcpClassifier, inet::PcpTrafficClassClassifier, inet::queueing::LabelClassifier, inet::queueing::MultiTokenBucketClassifier, inet::queueing::TokenBucketClassifier, and inet::queueing::PriorityClassifier.
Referenced by callClassifyPacket().
endPacketStreaming()
void inet::queueing::PacketClassifierBase::endPacketStreaming (Packet * packet) protected virtual
 {
     emit(packetPushedSignal, packet);
     handlePacketProcessed(packet);
     inProgressStreamId = -1;
     inProgressGateIndex = -1;
 }
Referenced by pushPacketEnd(), and pushPacketProgress().
getConsumer()
virtual IPassivePacketSink* inet::queueing::PacketClassifierBase::getConsumer (cGate * gate) inline override virtual
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
 { return consumers[gate->getIndex()]; }
getOutputGateIndex()
virtual size_t inet::queueing::PacketClassifierBase::getOutputGateIndex (size_t i) const inline protected virtual
 { return reverseOrder ? outputGates.size() - i - 1 : i; }
Referenced by inet::queueing::PriorityClassifier::classifyPacket(), and inet::queueing::PacketClassifier::classifyPacket().
getProvider()
virtual IPassivePacketSource* inet::queueing::PacketClassifierBase::getProvider (cGate * gate) inline override virtual
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
Reimplemented in inet::queueing::MarkovClassifier.
 { return provider; }
handleCanPullPacketChanged()
void inet::queueing::PacketClassifierBase::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
Reimplemented in inet::queueing::MarkovClassifier.
 {
     auto packet = provider->canPullPacket(inputGate->getPathStartGate());
     if (packet != nullptr) {
         int index = callClassifyPacket(packet);
         auto collector = collectors[index];
         if (collector != nullptr)
             collector->handleCanPullPacketChanged(outputGates[index]->getPathEndGate());
     }
 }
handleCanPushPacketChanged()
void inet::queueing::PacketClassifierBase::handleCanPushPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
This method is called, for example, when a new packet can be inserted into a queue. It allows the source to push a new packet into the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
 {
     Enter_Method("handleCanPushPacketChanged");
     if (producer != nullptr)
         producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
 }
handleMessage()
void inet::queueing::PacketClassifierBase::handleMessage (cMessage * message) override protected virtual
Reimplemented in inet::queueing::TokenBucketMixin< PacketClassifierBase >, and inet::queueing::MarkovClassifier.
 {
     auto packet = check_and_cast<Packet *>(message);
     pushPacket(packet, packet->getArrivalGate());
 }
handlePullPacketProcessed()
virtual void inet::queueing::PacketClassifierBase::handlePullPacketProcessed (Packet * packet, cGate * gate, bool successful) inline override virtual
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pulled packet is failed to be processed successfully. It allows the sink to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSink.
Reimplemented in inet::queueing::MarkovClassifier.
 { throw cRuntimeError("TODO"); }
handlePushPacketProcessed()
void inet::queueing::PacketClassifierBase::handlePushPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pushed packet is failed to be processed successfully. It allows the source to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSource.
 {
     producer->handlePushPacketProcessed(packet, inputGate->getPathStartGate(), successful);
 }
initialize()
void inet::queueing::PacketClassifierBase::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
Reimplemented in inet::MultiFieldClassifier, inet::BehaviorAggregateClassifier, inet::queueing::MultiTokenBucketMixin< PacketClassifierBase >, inet::queueing::MarkovClassifier, inet::queueing::WrrClassifier, inet::queueing::TokenBucketMixin< PacketClassifierBase >, inet::queueing::DynamicClassifier, inet::StreamClassifier, inet::queueing::ContentBasedClassifier, inet::queueing::TokenBucketClassifierMixin< TokenBucketMixin< PacketClassifierBase > >, inet::queueing::TokenBucketClassifierMixin< MultiTokenBucketMixin< PacketClassifierBase > >, inet::PcpClassifier, inet::PcpTrafficClassClassifier, inet::queueing::LabelClassifier, inet::queueing::PacketClassifier, inet::queueing::MultiTokenBucketClassifier, and inet::queueing::TokenBucketClassifier.
 {
     PacketProcessorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         reverseOrder = par("reverseOrder");
         inputGate = gate("in");
         producer = findConnectedModule<IActivePacketSource>(inputGate);
         provider = findConnectedModule<IPassivePacketSource>(inputGate);
         for (int i = 0; i < gateSize("out"); i++) {
             auto outputGate = gate("out", i);
             outputGates.push_back(outputGate);
             auto consumer = findConnectedModule<IPassivePacketSink>(outputGate);
             consumers.push_back(consumer);
             auto collector = findConnectedModule<IActivePacketSink>(outputGate);
             collectors.push_back(collector);
         }
     }
     else if (stage == INITSTAGE_QUEUEING) {
         for (int i = 0; i < gateSize("out"); i++)
             checkPacketOperationSupport(outputGates[i]);
         checkPacketOperationSupport(inputGate);
     }
 }
Referenced by inet::queueing::LabelClassifier::initialize(), inet::queueing::PacketClassifier::initialize(), inet::PcpClassifier::initialize(), inet::PcpTrafficClassClassifier::initialize(), inet::StreamClassifier::initialize(), inet::queueing::ContentBasedClassifier::initialize(), inet::queueing::WrrClassifier::initialize(), inet::BehaviorAggregateClassifier::initialize(), and inet::MultiFieldClassifier::initialize().
isStreamingPacket()
virtual bool inet::queueing::PacketClassifierBase::isStreamingPacket () const inline protected virtual
 { return inProgressStreamId != -1; }
Referenced by pushPacketEnd(), and pushPacketProgress().
mapRegistrationForwardingGates()
void inet::queueing::PacketClassifierBase::mapRegistrationForwardingGates (cGate * gate, std::function< void(cGate *)> f) override protected virtual
Reimplemented from inet::TransparentProtocolRegistrationListener.
Reimplemented in inet::MultiFieldClassifier.
 {
     if (gate == inputGate) {
         for (auto outputGate : outputGates)
             f(outputGate);
     }
     else if (std::find(outputGates.begin(), outputGates.end(), gate) != outputGates.end())
         f(inputGate);
     else
         throw cRuntimeError("Unknown gate");
 }
Referenced by inet::MultiFieldClassifier::mapRegistrationForwardingGates().
pullPacket()
Packet * inet::queueing::PacketClassifierBase::pullPacket (cGate * gate) override virtual
Pulls the packet from the packet source at the given gate.
This operation pulls the packet as a whole. The onwership of the packet is transferred to the sink.
The source must not be empty at the given gate. The returned packet must not be nullptr. The gate must be a valid gate of this module and it must support pulling and passing packets.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::MarkovClassifier.
 {
     auto packet = provider->pullPacket(inputGate->getPathStartGate());
     int index = callClassifyPacket(packet);
     if (index != gate->getIndex())
         throw cRuntimeError("Classified packet to wrong output gate");
     return packet;
 }
pullPacketEnd()
virtual Packet* inet::queueing::PacketClassifierBase::pullPacketEnd (cGate * gate) inline override virtual
Ends pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet from the the source.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::MarkovClassifier.
 { throw cRuntimeError("TODO"); }
pullPacketProgress()
virtual Packet* inet::queueing::PacketClassifierBase::pullPacketProgress (cGate * gate, bps datarate, b position, b extraProcessableLength) inline override virtual
Progresses pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the source about a change in the packet data when a preemption occurs.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::MarkovClassifier.
 { throw cRuntimeError("TODO"); }
pullPacketStart()
virtual Packet* inet::queueing::PacketClassifierBase::pullPacketStart (cGate * gate, bps datarate) inline override virtual
Starts pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet from the source.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::MarkovClassifier.
 { throw cRuntimeError("TODO"); }
pushPacket()
void inet::queueing::PacketClassifierBase::pushPacket (Packet * packet, cGate * gate) override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::MultiFieldClassifier, and inet::BehaviorAggregateClassifier.
 {
     Enter_Method("pushPacket");
     take(packet);
     checkPacketStreaming(nullptr);
     EV_INFO << "Classifying packet" << EV_FIELD(packet) << EV_ENDL;
     int index = callClassifyPacket(packet);
     handlePacketProcessed(packet);
     emit(packetPushedSignal, packet);
     pushOrSendPacket(packet, outputGates[index], consumers[index]);
     updateDisplayString();
 }
Referenced by handleMessage().
pushPacketEnd()
void inet::queueing::PacketClassifierBase::pushPacketEnd (Packet * packet, cGate * gate) override virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketEnd");
     take(packet);
     if (!isStreamingPacket())
         startPacketStreaming(packet);
     else
         checkPacketStreaming(packet);
     auto outputGate = outputGates[inProgressGateIndex];
     auto consumer = consumers[inProgressGateIndex];
     endPacketStreaming(packet);
     pushOrSendPacketEnd(packet, outputGate, consumer, packet->getTransmissionId());
     updateDisplayString();
 }
pushPacketProgress()
void inet::queueing::PacketClassifierBase::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) override virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketProgress");
     take(packet);
     if (!isStreamingPacket())
         startPacketStreaming(packet);
     else
         checkPacketStreaming(packet);
     auto outputGate = outputGates[inProgressGateIndex];
     auto consumer = consumers[inProgressGateIndex];
     if (packet->getTotalLength() == position + extraProcessableLength)
         endPacketStreaming(packet);
     pushOrSendPacketProgress(packet, outputGate, consumer, datarate, position, extraProcessableLength, packet->getTransmissionId());
     updateDisplayString();
 }
pushPacketStart()
void inet::queueing::PacketClassifierBase::pushPacketStart (Packet * packet, cGate * gate, bps datarate) override virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketStart");
     take(packet);
     checkPacketStreaming(packet);
     startPacketStreaming(packet);
     pushOrSendPacketStart(packet, outputGates[inProgressGateIndex], consumers[inProgressGateIndex], datarate, packet->getTransmissionId());
     updateDisplayString();
 }
startPacketStreaming()
void inet::queueing::PacketClassifierBase::startPacketStreaming (Packet * packet) protected virtual
 {
     EV_INFO << "Classifying packet" << EV_FIELD(packet) << EV_ENDL;
     inProgressStreamId = packet->getTreeId();
     inProgressGateIndex = callClassifyPacket(packet);
 }
Referenced by pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
supportsPacketPulling()
virtual bool inet::queueing::PacketClassifierBase::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::queueing::MarkovClassifier.
 { return true; }
supportsPacketPushing()
virtual bool inet::queueing::PacketClassifierBase::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::queueing::MarkovClassifier.
 { return true; }
supportsPacketStreaming()
virtual bool inet::queueing::PacketClassifierBase::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return true; }
Member Data Documentation
collectors
std::vector<IActivePacketSink *> inet::queueing::PacketClassifierBase::collectors protected
Referenced by handleCanPullPacketChanged(), and initialize().
consumers
std::vector<IPassivePacketSink *> inet::queueing::PacketClassifierBase::consumers protected
Referenced by inet::queueing::PriorityClassifier::canPushPacket(), inet::queueing::PriorityClassifier::canPushSomePacket(), canPushSomePacket(), inet::queueing::PriorityClassifier::classifyPacket(), inet::queueing::DynamicClassifier::classifyPacket(), inet::queueing::WrrClassifier::classifyPacket(), inet::queueing::WrrClassifier::initialize(), initialize(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
inProgressGateIndex
int inet::queueing::PacketClassifierBase::inProgressGateIndex = -1 protected
Referenced by endPacketStreaming(), pushPacketEnd(), pushPacketProgress(), pushPacketStart(), and startPacketStreaming().
inProgressStreamId
int inet::queueing::PacketClassifierBase::inProgressStreamId = -1 protected
Referenced by checkPacketStreaming(), endPacketStreaming(), and startPacketStreaming().
inputGate
cGate* inet::queueing::PacketClassifierBase::inputGate = nullptr protected
Referenced by inet::queueing::MarkovClassifier::canPullPacket(), canPullPacket(), handleCanPullPacketChanged(), handleCanPushPacketChanged(), handlePushPacketProcessed(), inet::queueing::MarkovClassifier::initialize(), initialize(), mapRegistrationForwardingGates(), inet::queueing::MarkovClassifier::pullPacket(), and pullPacket().
outputGates
std::vector<cGate *> inet::queueing::PacketClassifierBase::outputGates protected
Referenced by callClassifyPacket(), inet::queueing::PriorityClassifier::canPushPacket(), inet::queueing::PriorityClassifier::canPushSomePacket(), canPushSomePacket(), inet::queueing::PriorityClassifier::classifyPacket(), inet::queueing::MultiTokenBucketClassifier::classifyPacket(), inet::queueing::DynamicClassifier::classifyPacket(), inet::queueing::WrrClassifier::classifyPacket(), inet::queueing::MarkovClassifier::handleCanPullPacketChanged(), handleCanPullPacketChanged(), inet::queueing::MarkovClassifier::handleMessage(), inet::queueing::MarkovClassifier::handlePullPacketProcessed(), inet::queueing::TokenBucketClassifier::initialize(), inet::queueing::MultiTokenBucketClassifier::initialize(), inet::queueing::MarkovClassifier::initialize(), initialize(), mapRegistrationForwardingGates(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
producer
IActivePacketSource* inet::queueing::PacketClassifierBase::producer = nullptr protected
Referenced by handleCanPushPacketChanged(), handlePushPacketProcessed(), and initialize().
provider
IPassivePacketSource* inet::queueing::PacketClassifierBase::provider = nullptr protected
Referenced by canPullPacket(), handleCanPullPacketChanged(), initialize(), and pullPacket().
reverseOrder
bool inet::queueing::PacketClassifierBase::reverseOrder = false protected
Referenced by initialize().
The documentation for this class was generated from the following files:
PacketClassifierBase.h
PacketClassifierBase.cc