INET Framework for OMNeT++/OMNEST: inet::rtp::RtpPayloadReceiver Class Reference
inet::rtp::RtpPayloadReceiver Class Reference
The class RtpPayloadReceiver acts as a base class for modules processing incoming RTP data packets.
#include <RtpPayloadReceiver.h>
Public Member Functions
virtual ~RtpPayloadReceiver ()
Destructor.
Protected Member Functions
virtual void initialize () override
Initializes the receiver module, opens the output file and creates a queue for incoming packets.
virtual void handleMessage (cMessage *msg) override
Method for handling incoming packets.
virtual void processRtpPacket (Packet *packet)
Writes contents of this RtpPacket into the output file.
virtual void openOutputFile (const char *fileName)
This method is called by initialize and opens the output file stream.
virtual void closeOutputFile ()
Closes the output file stream.
Protected Attributes
std::ofstream _outputFileStream
The output file stream.
std::ofstream _outputLogLoss
The output file stream.
int _payloadType
The payload type this RtpPayloadReceiver module processes.
Static Protected Attributes
static simsignal_t rcvdPkRtpTimestampSignal = registerSignal("rcvdPkRtpTimestamp")
An output signal used to store arrival of rtp data packets.
Detailed Description
The class RtpPayloadReceiver acts as a base class for modules processing incoming RTP data packets.
Constructor & Destructor Documentation
~RtpPayloadReceiver()
inet::rtp::RtpPayloadReceiver::~RtpPayloadReceiver () virtual
Destructor.
Disposes the queue object and closes the output file.
 {
     closeOutputFile();
 }
Member Function Documentation
closeOutputFile()
void inet::rtp::RtpPayloadReceiver::closeOutputFile () protected virtual
Closes the output file stream.
 {
     if (_outputFileStream.is_open())
         _outputFileStream.close();
     if (_outputLogLoss.is_open())
         _outputLogLoss.close();
 }
Referenced by ~RtpPayloadReceiver().
handleMessage()
void inet::rtp::RtpPayloadReceiver::handleMessage (cMessage * msg) override protected virtual
Method for handling incoming packets.
At the moment only RTPInnerPackets containing an encapsulated RtpPacket are handled.
 {
     RtpInnerPacket *rinp = check_and_cast<RtpInnerPacket *>(msg);
     if (rinp->getType() == RTP_INP_DATA_IN) {
         auto packet = check_and_cast<Packet *>(rinp->decapsulate());
         processRtpPacket(packet);
         delete rinp;
     }
     else {
 //        delete rinp;
         throw cRuntimeError("RtpInnerPacket of wrong type received");
     }
 }
initialize()
void inet::rtp::RtpPayloadReceiver::initialize () override protected virtual
Initializes the receiver module, opens the output file and creates a queue for incoming packets.
Subclasses must overwrite it (but should call this method too)
Reimplemented in inet::rtp::RtpAvProfilePayload32Receiver.
 {
     const char *fileName = par("outputFileName");
     const char *logFileName = par("outputLogFileName");
     if (strcmp(fileName, ""))
         openOutputFile(fileName);
     if (strcmp(logFileName, "")) {
         char logName[200];
         sprintf(logName, logFileName, getId());
         _outputLogLoss.open(logName);
     }
 }
Referenced by inet::rtp::RtpAvProfilePayload32Receiver::initialize().
openOutputFile()
void inet::rtp::RtpPayloadReceiver::openOutputFile (const char * fileName) protected virtual
This method is called by initialize and opens the output file stream.
For most payload receivers this method works well, only when using a library for a payload type which provides an own open method it must
 {
     _outputFileStream.open(fileName);
 }
Referenced by initialize().
processRtpPacket()
void inet::rtp::RtpPayloadReceiver::processRtpPacket (Packet * packet) protected virtual
Writes contents of this RtpPacket into the output file.
Must be overwritten by subclasses.
Reimplemented in inet::rtp::RtpAvProfilePayload32Receiver.
 {
     const auto& rtpHeader = packet->peekAtFront<RtpHeader>();
     emit(rcvdPkRtpTimestampSignal, (double)(rtpHeader->getTimeStamp()));
 }
Referenced by handleMessage().
Member Data Documentation
_outputFileStream
std::ofstream inet::rtp::RtpPayloadReceiver::_outputFileStream protected
The output file stream.
Referenced by closeOutputFile(), openOutputFile(), and inet::rtp::RtpAvProfilePayload32Receiver::processRtpPacket().
_outputLogLoss
std::ofstream inet::rtp::RtpPayloadReceiver::_outputLogLoss protected
The output file stream.
Referenced by closeOutputFile(), initialize(), and inet::rtp::RtpAvProfilePayload32Receiver::processRtpPacket().
_payloadType
int inet::rtp::RtpPayloadReceiver::_payloadType protected
The payload type this RtpPayloadReceiver module processes.
Referenced by inet::rtp::RtpAvProfilePayload32Receiver::initialize().
rcvdPkRtpTimestampSignal
simsignal_t inet::rtp::RtpPayloadReceiver::rcvdPkRtpTimestampSignal = registerSignal("rcvdPkRtpTimestamp") static protected
An output signal used to store arrival of rtp data packets.
Referenced by processRtpPacket().
The documentation for this class was generated from the following files:
RtpPayloadReceiver.h
RtpPayloadReceiver.cc