INET Framework for OMNeT++/OMNEST: inet::Macho::_StateSpecification Class Reference
inet::Macho::_StateSpecification Class Reference
#include <Macho.h>
Public Member Functions
virtual ~_StateSpecification ()
Static Public Member Functions
static bool isChild (Key key)
Protected Member Functions
_StateSpecification (_StateInstance &instance)
template<class S >
void setState ()
template<class S , class P1 >
void setState (const P1 &p1)
template<class S , class P1 , class P2 >
void setState (const P1 &p1, const P2 &p2)
template<class S , class P1 , class P2 , class P3 >
void setState (const P1 &p1, const P2 &p2, const P3 &p3)
template<class S , class P1 , class P2 , class P3 , class P4 >
void setState (const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4)
template<class S , class P1 , class P2 , class P3 , class P4 , class P5 >
void setState (const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5)
template<class S , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 >
void setState (const P1 &p1, const P2 &p2, const P3 &p3, const P4 &p4, const P5 &p5, const P6 &p6)
template<class S >
void setStateHistory ()
void setState (const class Alias &state)
template<class S >
void setStateBox (typename S::Box *box=0)
template<class S >
void setStateDirect (typename S::Box *box=0)
virtual void _restore (_StateInstance &current)
void setState (_StateInstance &current)
virtual void _shutdown ()
virtual void _setHistorySuper (_StateInstance &self, _StateInstance &deep)
Private Member Functions
virtual void exit ()
virtual void entry ()
virtual void init ()
virtual void _deleteBox (_StateInstance &instance)
virtual void _saveHistory (_StateInstance &self, _StateInstance &shallow, _StateInstance &deep)
Static Private Member Functions
static _StateInstance & _getInstance (_MachineBase &machine)
Private Attributes
_StateInstance & _myStateInstance
Friends
template<class T >
class TopBase
template<class C , class P >
class MachoLink
class _StateInstance
class _RootInstance
class _MachineBase
Constructor & Destructor Documentation
~_StateSpecification()
virtual inet::Macho::_StateSpecification::~_StateSpecification () inline virtual
 {}
_StateSpecification()
inet::Macho::_StateSpecification::_StateSpecification (_StateInstance & instance) inline protected
         : _myStateInstance(instance)
     {}
Member Function Documentation
_deleteBox()
virtual void inet::Macho::_StateSpecification::_deleteBox (_StateInstance & instance) inline private virtual
 {}
Referenced by inet::Macho::_StateInstance::exit().
_getInstance()
_StateInstance & inet::_StateSpecification::_getInstance (_MachineBase & machine) static private
 {
     // Look first in machine for existing StateInstance.
     _StateInstance *& instance = machine.getInstance(0);
     if (!instance)
         instance = new _RootInstance(machine, nullptr);
     return *instance;
 }
Referenced by inet::Macho::_MachineBase::shutdown(), and inet::Macho::_MachineBase::start().
_restore()
void inet::_StateSpecification::_restore (_StateInstance & current) protected virtual
 {
     _myStateInstance.machine().myCurrentState = &current;
 }
Referenced by inet::Macho::_StateInstance::restore().
_saveHistory()
virtual void inet::Macho::_StateSpecification::_saveHistory (_StateInstance & self, _StateInstance & shallow, _StateInstance & deep) inline private virtual
 {}
Referenced by inet::Macho::_StateInstance::saveHistory().
_setHistorySuper()
virtual void inet::Macho::_StateSpecification::_setHistorySuper (_StateInstance & self, _StateInstance & deep) inline protected virtual
 {}
_shutdown()
void inet::_StateSpecification::_shutdown () protected virtual
 {
     _myStateInstance.machine().shutdown();
 }
Referenced by inet::Macho::_StateInstance::shutdown().
entry()
virtual void inet::Macho::_StateSpecification::entry () inline private virtual
 {}
Referenced by inet::Macho::_StateInstance::entry().
exit()
virtual void inet::Macho::_StateSpecification::exit () inline private virtual
 {}
Referenced by inet::Macho::_StateInstance::exit().
init()
virtual void inet::Macho::_StateSpecification::init () inline private virtual
 {}
Referenced by inet::Macho::_StateInstance::init().
isChild()
static bool inet::Macho::_StateSpecification::isChild (Key key) inline static
     {
         return false;
     }
setState() [1/9]
template<class S > void inet::Macho::_StateSpecification::setState inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, &_theDefaultInitializer);
 }
setState() [2/9]
void inet::Macho::_StateSpecification::setState (_StateInstance & current) protected
setState() [3/9]
void inet::Macho::_StateSpecification::setState (const class Alias & state) protected
setState() [4/9]
template<class S , class P1 > void inet::Macho::_StateSpecification::setState (const P1 & p1) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, new _Initializer1<S, P1>(p1));
 }
setState() [5/9]
template<class S , class P1 , class P2 > void inet::Macho::_StateSpecification::setState (const P1 & p1, const P2 & p2) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, new _Initializer2<S, P1, P2>(p1, p2));
 }
setState() [6/9]
template<class S , class P1 , class P2 , class P3 > void inet::Macho::_StateSpecification::setState (const P1 & p1, const P2 & p2, const P3 & p3) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, new _Initializer3<S, P1, P2, P3>(p1, p2, p3));
 }
setState() [7/9]
template<class S , class P1 , class P2 , class P3 , class P4 > void inet::Macho::_StateSpecification::setState (const P1 & p1, const P2 & p2, const P3 & p3, const P4 & p4) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, new _Initializer4<S, P1, P2, P3, P4>(p1, p2, p3, p4));
 }
setState() [8/9]
template<class S , class P1 , class P2 , class P3 , class P4 , class P5 > void inet::Macho::_StateSpecification::setState (const P1 & p1, const P2 & p2, const P3 & p3, const P4 & p4, const P5 & p5) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, new _Initializer5<S, P1, P2, P3, P4, P5>(p1, p2, p3, p4, p5));
 }
setState() [9/9]
template<class S , class P1 , class P2 , class P3 , class P4 , class P5 , class P6 > void inet::Macho::_StateSpecification::setState (const P1 & p1, const P2 & p2, const P3 & p3, const P4 & p4, const P5 & p5, const P6 & p6) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, new _Initializer6<S, P1, P2, P3, P4, P5, P6>(p1, p2, p3, p4, p5, p6));
 }
setStateBox()
template<class S > void inet::Macho::_StateSpecification::setStateBox (typename S::Box * box = 0) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.myPendingBox = box;
     m.setPendingState(instance, &_theHistoryInitializer);
 }
setStateDirect()
template<class S > void inet::Macho::_StateSpecification::setStateDirect (typename S::Box * box = 0) inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.myPendingBox = box;
     m.setPendingState(instance, &_theDefaultInitializer);
 }
setStateHistory()
template<class S > void inet::Macho::_StateSpecification::setStateHistory inline protected
 {
     _MachineBase& m = _myStateInstance.machine();
     _StateInstance& instance = S::_getInstance(m);
     m.setPendingState(instance, &_theHistoryInitializer);
 }
Friends And Related Function Documentation
_MachineBase
friend class _MachineBase friend
_RootInstance
friend class _RootInstance friend
Referenced by _getInstance().
_StateInstance
friend class _StateInstance friend
MachoLink
template<class C , class P > friend class MachoLink friend
TopBase
template<class T > friend class TopBase friend
Member Data Documentation
_myStateInstance
_StateInstance& inet::Macho::_StateSpecification::_myStateInstance private
Referenced by _restore(), _shutdown(), setState(), setStateBox(), setStateDirect(), and setStateHistory().
The documentation for this class was generated from the following files:
Macho.h
Macho.cc