INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211HtModeBase Class Reference
inet::physicallayer::Ieee80211HtModeBase Class Reference abstract
#include <Ieee80211HtMode.h>
Public Types
enum GuardIntervalType { HT_GUARD_INTERVAL_SHORT, HT_GUARD_INTERVAL_LONG }
Public Member Functions
Ieee80211HtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
virtual int getNumberOfDataSubcarriers () const
virtual int getNumberOfPilotSubcarriers () const
virtual int getNumberOfTotalSubcarriers () const
virtual GuardIntervalType getGuardIntervalType () const
virtual int getNumberOfSpatialStreams () const
virtual unsigned int getMcsIndex () const
virtual Hz getBandwidth () const
virtual bps getNetBitrate () const
virtual bps getGrossBitrate () const
Protected Member Functions
virtual bps computeGrossBitrate () const =0
virtual bps computeNetBitrate () const =0
Protected Attributes
const Hz bandwidth
const GuardIntervalType guardIntervalType
const unsigned int mcsIndex
const unsigned int numberOfSpatialStreams
bps netBitrate
bps grossBitrate
Member Enumeration Documentation
GuardIntervalType
enum inet::physicallayer::Ieee80211HtModeBase::GuardIntervalType
Enumerator
HT_GUARD_INTERVAL_SHORT
HT_GUARD_INTERVAL_LONG
{
         HT_GUARD_INTERVAL_SHORT, // 400 ns
         HT_GUARD_INTERVAL_LONG // 800 ns
     };
Constructor & Destructor Documentation
Ieee80211HtModeBase()
inet::physicallayer::Ieee80211HtModeBase::Ieee80211HtModeBase (unsigned int modulationAndCodingScheme, unsigned int numberOfSpatialStreams, const Hz bandwidth, GuardIntervalType guardIntervalType)
                                                                                                                                                                              :
     bandwidth(bandwidth),
     guardIntervalType(guardIntervalType),
     mcsIndex(modulationAndCodingScheme),
     numberOfSpatialStreams(numberOfSpatialStreams),
     netBitrate(bps(NaN)),
     grossBitrate(bps(NaN))
 {
 }
Member Function Documentation
computeGrossBitrate()
virtual bps inet::physicallayer::Ieee80211HtModeBase::computeGrossBitrate () const protected pure virtual
Implemented in inet::physicallayer::Ieee80211HtDataMode, and inet::physicallayer::Ieee80211HtSignalMode.
Referenced by getGrossBitrate().
computeNetBitrate()
virtual bps inet::physicallayer::Ieee80211HtModeBase::computeNetBitrate () const protected pure virtual
Implemented in inet::physicallayer::Ieee80211HtDataMode, and inet::physicallayer::Ieee80211HtSignalMode.
Referenced by getNetBitrate().
getBandwidth()
virtual Hz inet::physicallayer::Ieee80211HtModeBase::getBandwidth () const inline virtual
Reimplemented in inet::physicallayer::Ieee80211HtDataMode.
 { return bandwidth; }
getGrossBitrate()
bps inet::physicallayer::Ieee80211HtModeBase::getGrossBitrate () const virtual
Reimplemented in inet::physicallayer::Ieee80211HtDataMode, and inet::physicallayer::Ieee80211HtSignalMode.
 {
     if (std::isnan(grossBitrate.get()))
         grossBitrate = computeGrossBitrate();
     return grossBitrate;
 }
Referenced by inet::physicallayer::Ieee80211HtSignalMode::getGrossBitrate(), and inet::physicallayer::Ieee80211HtDataMode::getGrossBitrate().
getGuardIntervalType()
virtual GuardIntervalType inet::physicallayer::Ieee80211HtModeBase::getGuardIntervalType () const inline virtual
 { return guardIntervalType; }
getMcsIndex()
virtual unsigned int inet::physicallayer::Ieee80211HtModeBase::getMcsIndex () const inline virtual
 { return mcsIndex; }
getNetBitrate()
bps inet::physicallayer::Ieee80211HtModeBase::getNetBitrate () const virtual
Reimplemented in inet::physicallayer::Ieee80211HtDataMode, and inet::physicallayer::Ieee80211HtSignalMode.
 {
     if (std::isnan(netBitrate.get()))
         netBitrate = computeNetBitrate();
     return netBitrate;
 }
Referenced by inet::physicallayer::Ieee80211HtSignalMode::getNetBitrate(), and inet::physicallayer::Ieee80211HtDataMode::getNetBitrate().
getNumberOfDataSubcarriers()
int inet::physicallayer::Ieee80211HtModeBase::getNumberOfDataSubcarriers () const virtual
 {
     if (bandwidth == MHz(20))
         return 52;
     else if (bandwidth == MHz(40))
         // It is a special case, see Table 20-38—MCS parameters for
         // optional 40 MHz MCS 32 format, N SS = 1, N ES = 1
         return mcsIndex == 32 ? 48 : 108;
     else
         throw cRuntimeError("Unsupported bandwidth");
 }
Referenced by inet::physicallayer::Ieee80211HtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeGrossBitrate(), and inet::physicallayer::Ieee80211HtDataMode::getDuration().
getNumberOfPilotSubcarriers()
int inet::physicallayer::Ieee80211HtModeBase::getNumberOfPilotSubcarriers () const virtual
 {
     if (bandwidth == MHz(20))
         return 4;
     else if (bandwidth == MHz(40))
         // It is a spacial case, see the comment above.
         return mcsIndex == 32 ? 4 : 6;
     else
         throw cRuntimeError("Unsupported bandwidth");
 }
getNumberOfSpatialStreams()
virtual int inet::physicallayer::Ieee80211HtModeBase::getNumberOfSpatialStreams () const inline virtual
Reimplemented in inet::physicallayer::Ieee80211HtDataMode.
 { return numberOfSpatialStreams; }
Referenced by inet::physicallayer::Ieee80211HtDataMode::getNumberOfSpatialStreams().
getNumberOfTotalSubcarriers()
virtual int inet::physicallayer::Ieee80211HtModeBase::getNumberOfTotalSubcarriers () const inline virtual
 { return getNumberOfDataSubcarriers() + getNumberOfPilotSubcarriers(); }
Member Data Documentation
bandwidth
const Hz inet::physicallayer::Ieee80211HtModeBase::bandwidth protected
Referenced by getNumberOfDataSubcarriers(), and getNumberOfPilotSubcarriers().
grossBitrate
bps inet::physicallayer::Ieee80211HtModeBase::grossBitrate mutable protected
Referenced by getGrossBitrate().
guardIntervalType
const GuardIntervalType inet::physicallayer::Ieee80211HtModeBase::guardIntervalType protected
Referenced by inet::physicallayer::Ieee80211HtSignalMode::computeGrossBitrate(), and inet::physicallayer::Ieee80211HtDataMode::computeGrossBitrate().
mcsIndex
const unsigned int inet::physicallayer::Ieee80211HtModeBase::mcsIndex protected
Referenced by getNumberOfDataSubcarriers(), and getNumberOfPilotSubcarriers().
netBitrate
bps inet::physicallayer::Ieee80211HtModeBase::netBitrate mutable protected
Referenced by getNetBitrate().
numberOfSpatialStreams
const unsigned int inet::physicallayer::Ieee80211HtModeBase::numberOfSpatialStreams protected
The documentation for this class was generated from the following files:
Ieee80211HtMode.h
Ieee80211HtMode.cc