INET Framework for OMNeT++/OMNEST: inet::ieee80211::AckHandler Class Reference
inet::ieee80211::AckHandler Class Reference
#include <AckHandler.h>
Public Types
enum Status {
Status::FRAME_NOT_YET_TRANSMITTED, Status::NO_ACK_REQUIRED, Status::WAITING_FOR_ACK, Status::ACK_NOT_ARRIVED,
Status::ACK_ARRIVED
}
Public Member Functions
virtual ~AckHandler ()
virtual void processReceivedAck (const Ptr< const Ieee80211AckFrame > &ack, const Ptr< const Ieee80211DataOrMgmtHeader > &ackedHeader)
virtual void frameGotInProgress (const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader) override
virtual void processTransmittedDataOrMgmtFrame (const Ptr< const Ieee80211DataOrMgmtHeader > &header)
virtual Status getAckStatus (const Ptr< const Ieee80211DataOrMgmtHeader > &header)
virtual bool isEligibleToTransmit (const Ptr< const Ieee80211DataOrMgmtHeader > &header) override
virtual bool isOutstandingFrame (const Ptr< const Ieee80211DataOrMgmtHeader > &header) override
virtual void processFailedFrame (const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader)
virtual void dropFrame (const Ptr< const Ieee80211DataOrMgmtHeader > &dataOrMgmtHeader)
Public Member Functions inherited from inet::ieee80211::IAckHandler
virtual ~IAckHandler ()
Static Public Member Functions
static std::string getStatusString (Status status)
Protected Member Functions
virtual void initialize (int stage) override
virtual Status getAckStatus (SequenceControlField id)
void printAckStatuses ()
Protected Attributes
std::map< SequenceControlField, Status > ackStatuses
Member Enumeration Documentation
Status
enum inet::ieee80211::AckHandler::Status strong
Enumerator
FRAME_NOT_YET_TRANSMITTED
NO_ACK_REQUIRED
WAITING_FOR_ACK
ACK_NOT_ARRIVED
ACK_ARRIVED
                       {
         FRAME_NOT_YET_TRANSMITTED,
         NO_ACK_REQUIRED,
         WAITING_FOR_ACK,
         ACK_NOT_ARRIVED,
         ACK_ARRIVED,
     };
Constructor & Destructor Documentation
~AckHandler()
virtual inet::ieee80211::AckHandler::~AckHandler () inline virtual
 {}
Member Function Documentation
dropFrame()
void inet::ieee80211::AckHandler::dropFrame (const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) virtual
 {
     auto id = SequenceControlField(dataOrMgmtHeader->getSequenceNumber().get(), dataOrMgmtHeader->getFragmentNumber());
     ackStatuses.erase(id);
 }
frameGotInProgress()
void inet::ieee80211::AckHandler::frameGotInProgress (const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) override virtual
Implements inet::ieee80211::IAckHandler.
 {
     auto id = SequenceControlField(dataOrMgmtHeader->getSequenceNumber().get(), dataOrMgmtHeader->getFragmentNumber());
     auto status = getAckStatus(id);
     ASSERT(status != Status::WAITING_FOR_ACK);
     ackStatuses[id] = Status::FRAME_NOT_YET_TRANSMITTED;
 }
getAckStatus() [1/2]
AckHandler::Status inet::ieee80211::AckHandler::getAckStatus (const Ptr< const Ieee80211DataOrMgmtHeader > & header) virtual
 {
     auto id = SequenceControlField(header->getSequenceNumber().get(), header->getFragmentNumber());
     return getAckStatus(id);
 }
getAckStatus() [2/2]
AckHandler::Status inet::ieee80211::AckHandler::getAckStatus (SequenceControlField id) protected virtual
 {
     auto it = ackStatuses.find(id);
     return (it != ackStatuses.end()) ? it->second : Status::FRAME_NOT_YET_TRANSMITTED;
 }
Referenced by frameGotInProgress(), getAckStatus(), isEligibleToTransmit(), processFailedFrame(), and processReceivedAck().
getStatusString()
std::string inet::ieee80211::AckHandler::getStatusString (Status status) static
 {
     switch (status) {
         case Status::FRAME_NOT_YET_TRANSMITTED: return "FRAME_NOT_YET_TRANSMITTED";
         case Status::NO_ACK_REQUIRED: return "NO_ACK_REQUIRED";
         case Status::WAITING_FOR_ACK: return "WAITING_FOR_NORMAL_ACK";
         case Status::ACK_NOT_ARRIVED: return "NORMAL_ACK_NOT_ARRIVED";
         case Status::ACK_ARRIVED: return "NORMAL_ACK_ARRIVED";
         default: throw cRuntimeError("Unknown status");
     }
 }
Referenced by inet::ieee80211::operator<<(), and printAckStatuses().
initialize()
void inet::ieee80211::AckHandler::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         WATCH_MAP(ackStatuses);
     }
 }
isEligibleToTransmit()
bool inet::ieee80211::AckHandler::isEligibleToTransmit (const Ptr< const Ieee80211DataOrMgmtHeader > & header) override virtual
Implements inet::ieee80211::IAckHandler.
 {
     auto status = getAckStatus(header);
     return status == AckHandler::Status::NO_ACK_REQUIRED ||
            status == AckHandler::Status::ACK_NOT_ARRIVED ||
            status == AckHandler::Status::FRAME_NOT_YET_TRANSMITTED;
 }
isOutstandingFrame()
bool inet::ieee80211::AckHandler::isOutstandingFrame (const Ptr< const Ieee80211DataOrMgmtHeader > & header) override virtual
Implements inet::ieee80211::IAckHandler.
 {
     return false;
 }
printAckStatuses()
void inet::ieee80211::AckHandler::printAckStatuses () protected
 {
     for (auto ackStatus : ackStatuses) {
         std::cout << "Seq Num = " << ackStatus.first.getSequenceNumber() << " " << "Frag Num = " << (int)ackStatus.first.getFragmentNumber() << std::endl;
         std::cout << "Status = " << getStatusString(ackStatus.second) << std::endl;
     }
     std::cout << "=========================================" << std::endl;
 }
processFailedFrame()
void inet::ieee80211::AckHandler::processFailedFrame (const Ptr< const Ieee80211DataOrMgmtHeader > & dataOrMgmtHeader) virtual
 {
     if (auto dataHeader = dynamicPtrCast<const Ieee80211DataHeader>(dataOrMgmtHeader)) {
         if (dataHeader->getAckPolicy() == NORMAL_ACK) {
             ASSERT(getAckStatus(dataOrMgmtHeader) == Status::WAITING_FOR_ACK);
             auto id = SequenceControlField(dataOrMgmtHeader->getSequenceNumber().get(), dataOrMgmtHeader->getFragmentNumber());
             ackStatuses[id] = Status::ACK_NOT_ARRIVED;
         }
     }
 }
processReceivedAck()
void inet::ieee80211::AckHandler::processReceivedAck (const Ptr< const Ieee80211AckFrame > & ack, const Ptr< const Ieee80211DataOrMgmtHeader > & ackedHeader) virtual
 {
     auto id = SequenceControlField(ackedHeader->getSequenceNumber().get(), ackedHeader->getFragmentNumber());
     auto status = getAckStatus(id);
     if (status == Status::FRAME_NOT_YET_TRANSMITTED)
         throw cRuntimeError("ackedFrame = %s is not yet transmitted", ackedHeader->getName());
     ackStatuses[id] = Status::ACK_ARRIVED;
 }
processTransmittedDataOrMgmtFrame()
void inet::ieee80211::AckHandler::processTransmittedDataOrMgmtFrame (const Ptr< const Ieee80211DataOrMgmtHeader > & header) virtual
 {
     auto id = SequenceControlField(header->getSequenceNumber().get(), header->getFragmentNumber());
     if (auto dataHeader = dynamicPtrCast<const Ieee80211DataHeader>(header)) {
         if (dataHeader->getAckPolicy() == NORMAL_ACK)
             ackStatuses[id] = Status::WAITING_FOR_ACK;
         else
             ackStatuses[id] = Status::NO_ACK_REQUIRED;
     }
     else
         ackStatuses[id] = Status::NO_ACK_REQUIRED;
 }
Member Data Documentation
ackStatuses
std::map<SequenceControlField, Status> inet::ieee80211::AckHandler::ackStatuses protected
Referenced by dropFrame(), frameGotInProgress(), getAckStatus(), initialize(), printAckStatuses(), processFailedFrame(), processReceivedAck(), and processTransmittedDataOrMgmtFrame().
The documentation for this class was generated from the following files:
AckHandler.h
AckHandler.cc