INET Framework for OMNeT++/OMNEST: inet::power::ICcEnergySource Class Reference
inet::power::ICcEnergySource Class Reference abstract
TODO.
#include <ICcEnergySource.h>
Public Member Functions
virtual V getNominalVoltage () const =0
Returns the open circuit voltage in the range [0, +infinity).
virtual V getOutputVoltage () const =0
Returns the output voltage in the ragne [0, +infinity).
virtual A getTotalCurrentConsumption () const =0
Returns the total current consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
virtual int getNumEnergyConsumers () const =0
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const =0
Returns the energy consumer for the provided index.
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer)=0
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer)=0
Removes a previously added energy consumer from this energy source.
Static Public Attributes
static simsignal_t currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged")
The signal that is used to publish current consumption changes.
Detailed Description
TODO.
See the corresponding NED file for more details.
Member Function Documentation
getNominalVoltage()
virtual V inet::power::ICcEnergySource::getNominalVoltage () const pure virtual
Returns the open circuit voltage in the range [0, +infinity).
Implemented in inet::power::SimpleCcBattery.
getOutputVoltage()
virtual V inet::power::ICcEnergySource::getOutputVoltage () const pure virtual
Returns the output voltage in the ragne [0, +infinity).
Implemented in inet::power::SimpleCcBattery.
getTotalCurrentConsumption()
virtual A inet::power::ICcEnergySource::getTotalCurrentConsumption () const pure virtual
Returns the total current consumption in the range [0, +infinity).
Implemented in inet::power::SimpleCcBattery, and inet::power::CcEnergySourceBase.
Member Data Documentation
currentConsumptionChangedSignal
simsignal_t inet::power::ICcEnergySource::currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged") static
The signal that is used to publish current consumption changes.
Referenced by inet::physicallayer::StateBasedCcEnergyConsumer::initialize(), inet::physicallayer::StateBasedCcEnergyConsumer::receiveSignal(), and inet::power::CcEnergyStorageBase::updateTotalCurrentConsumption().
The documentation for this class was generated from the following files:
ICcEnergySource.h
ICcEnergySource.cc