INET Framework for OMNeT++/OMNEST: inet::physicallayer::LayeredErrorModelBase Class Reference
inet::physicallayer::LayeredErrorModelBase Class Reference
#include <LayeredErrorModelBase.h>
Protected Member Functions
virtual const IReceptionPacketModel * computePacketModel (const LayeredTransmission *transmission, double packetErrorRate) const
virtual const IReceptionBitModel * computeBitModel (const LayeredTransmission *transmission, double bitErrorRate) const
virtual const IReceptionSymbolModel * computeSymbolModel (const LayeredTransmission *transmission, double symbolErrorRate) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions inherited from inet::physicallayer::ILayeredErrorModel
virtual const IReceptionPacketModel * computePacketModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the packet domain representation at the receiver using a simplified model for the underlying domains.
virtual const IReceptionBitModel * computeBitModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the bit domain representation at the receiver using a simplified model for the underlying domains.
virtual const IReceptionSymbolModel * computeSymbolModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the symbol domain representation at the receiver using a simplified model for the underlying domains.
virtual const IReceptionSampleModel * computeSampleModel (const LayeredTransmission *transmission, const ISnir *snir) const =0
Computes the sample domain representation at the receiver using a simplified model for the underlying domains.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Member Function Documentation
computeBitModel()
const IReceptionBitModel * inet::physicallayer::LayeredErrorModelBase::computeBitModel (const LayeredTransmission * transmission, double bitErrorRate) const protected virtual
 {
     const TransmissionBitModel *transmissionBitModel = check_and_cast<const TransmissionBitModel *>(transmission->getBitModel());
     if (bitErrorRate == 0)
         return new ReceptionBitModel(transmissionBitModel->getHeaderLength(), transmissionBitModel->getHeaderBitRate(), transmissionBitModel->getDataLength(), transmissionBitModel->getDataBitRate(), new BitVector(*transmissionBitModel->getBits()), bitErrorRate);
     else {
         BitVector *receivedBits = new BitVector(*transmissionBitModel->getBits());
         for (unsigned int i = 0; i < receivedBits->getSize(); i++) {
             if (uniform(0, 1) < bitErrorRate)
                 receivedBits->toggleBit(i);
         }
         return new ReceptionBitModel(transmissionBitModel->getHeaderLength(), transmissionBitModel->getHeaderBitRate(), transmissionBitModel->getDataLength(), transmissionBitModel->getDataBitRate(), receivedBits, bitErrorRate);
     }
 }
Referenced by inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), and inet::physicallayer::StochasticLayeredErrorModel::computeBitModel().
computePacketModel()
const IReceptionPacketModel * inet::physicallayer::LayeredErrorModelBase::computePacketModel (const LayeredTransmission * transmission, double packetErrorRate) const protected virtual
 {
     auto transmissionPacketModel = check_and_cast<const TransmissionPacketModel *>(transmission->getPacketModel());
     auto transmittedPacket = transmissionPacketModel->getPacket();
     auto receivedPacket = transmittedPacket->dup();
     if (packetErrorRate != 0 && uniform(0, 1) < packetErrorRate)
         receivedPacket->setBitError(true);
     receivedPacket->addTagIfAbsent<ErrorRateInd>()->setPacketErrorRate(packetErrorRate);
     return new ReceptionPacketModel(receivedPacket, transmissionPacketModel->getBitrate(), packetErrorRate);
 }
Referenced by inet::physicallayer::ApskLayeredErrorModel::computePacketModel().
computeSymbolModel()
const IReceptionSymbolModel * inet::physicallayer::LayeredErrorModelBase::computeSymbolModel (const LayeredTransmission * transmission, double symbolErrorRate) const protected virtual
 {
     if (symbolErrorRate == 0) {
         const TransmissionSymbolModel *transmissionSymbolModel = check_and_cast<const TransmissionSymbolModel *>(transmission->getSymbolModel());
         return new ReceptionSymbolModel(transmissionSymbolModel->getHeaderSymbolLength(), transmissionSymbolModel->getHeaderSymbolRate(), transmissionSymbolModel->getPayloadSymbolLength(), transmissionSymbolModel->getPayloadSymbolRate(), new std::vector<const ISymbol *>(*transmissionSymbolModel->getSymbols()), symbolErrorRate);
     }
     else {
         const TransmissionSymbolModel *transmissionSymbolModel = check_and_cast<const TransmissionSymbolModel *>(transmission->getSymbolModel());
         const ApskModulationBase *modulation = check_and_cast<const ApskModulationBase *>(transmissionSymbolModel->getPayloadModulation());
         const std::vector<const ISymbol *> *transmittedSymbols = transmissionSymbolModel->getSymbols();
         std::vector<const ISymbol *> *receivedSymbols = new std::vector<const ISymbol *>();
         for (auto& transmittedSymbols_i : *transmittedSymbols) {
             if (uniform(0, 1) < symbolErrorRate) {
                 const ApskSymbol *transmittedSymbol = check_and_cast<const ApskSymbol *>(transmittedSymbols_i);
                 ShortBitVector bits = modulation->demapToBitRepresentation(transmittedSymbol);
                 int errorIndex = intuniform(0, bits.getSize() - 1);
                 bits.setBit(errorIndex, !bits.getBit(errorIndex));
                 const ApskSymbol *receivedSymbol = modulation->mapToConstellationDiagram(bits);
                 receivedSymbols->push_back(receivedSymbol);
             }
             else
                 receivedSymbols->push_back(transmittedSymbols_i);
         }
         return new ReceptionSymbolModel(transmissionSymbolModel->getHeaderSymbolLength(), transmissionSymbolModel->getHeaderSymbolRate(), transmissionSymbolModel->getPayloadSymbolLength(), transmissionSymbolModel->getPayloadSymbolRate(), receivedSymbols, symbolErrorRate);
     }
 }
Referenced by inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel(), and inet::physicallayer::StochasticLayeredErrorModel::computeSymbolModel().
The documentation for this class was generated from the following files:
LayeredErrorModelBase.h
LayeredErrorModelBase.cc