INET Framework for OMNeT++/OMNEST: inet::SocketBase Class Reference
inet::SocketBase Class Reference
#include <SocketBase.h>
Public Member Functions
SocketBase ()
virtual ~SocketBase ()
Setting up a socket
void setOutputGate (cGate *gate)
Sets the gate on which to send messages.
int getSocketId () const override
Returns the internal socket Id.
Opening and closing connections, sending data
virtual void send (Packet *packet) override
Sends a data packet to the address and port specified previously in a connect() call.
virtual bool isOpen () const override
Returns true if the socket is open.
virtual void close () override
Unbinds the socket.
virtual void destroy () override
Notify the protocol that the owner of ISocket has destroyed the socket.
Handling of messages
virtual bool belongsToSocket (cMessage *msg) const override
Returns true if the message belongs to this socket instance.
User data
void * getUserData () const
void setUserData (void *userData)
Public Member Functions inherited from inet::ISocket
virtual ~ISocket ()
virtual void processMessage (cMessage *msg)=0
Examines the message, takes ownership, and updates socket state.
Protected Member Functions
virtual void sendOut (cMessage *msg)
Protected Attributes
cGate * outputGate = nullptr
int socketId = -1
bool isOpen_ = false
void * userData = nullptr
Constructor & Destructor Documentation
SocketBase()
inet::SocketBase::SocketBase ()
 {
     // don't allow user-specified socketIds because they may conflict with
     // automatically assigned ones.
     socketId = getEnvir()->getUniqueNumber();
     outputGate = nullptr;
 }
~SocketBase()
virtual inet::SocketBase::~SocketBase () inline virtual
 {}
Member Function Documentation
belongsToSocket()
bool inet::SocketBase::belongsToSocket (cMessage * msg) const override virtual
Returns true if the message belongs to this socket instance.
Implements inet::ISocket.
 {
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     const auto& socketInd = tags.findTag<SocketInd>();
     return socketInd != nullptr && socketInd->getSocketId() == socketId;
 }
Referenced by inet::EthernetSocketIo::handleMessageWhenUp(), inet::Ieee8022LlcSocketIo::handleMessageWhenUp(), inet::Ieee8022LlcSocket::processMessage(), inet::EthernetSocket::processMessage(), and inet::Ieee8021qSocket::processMessage().
close()
void inet::SocketBase::close () override virtual
Unbinds the socket.
Once closed, a closed socket may be bound to another (or the same) port, and reused.
Implements inet::ISocket.
 {
     auto request = new Request("CLOSE", SOCKET_C_CLOSE);
     auto *ctrl = new SocketCloseCommand();
     request->setControlInfo(ctrl);
     isOpen_ = true;
     sendOut(request);
 }
Referenced by inet::EthernetSocketIo::handleStopOperation(), inet::EtherAppServer::handleStopOperation(), inet::Ieee8022LlcSocketIo::handleStopOperation(), inet::EtherTrafGen::handleStopOperation(), and inet::EtherAppClient::handleStopOperation().
destroy()
void inet::SocketBase::destroy () override virtual
Notify the protocol that the owner of ISocket has destroyed the socket.
Typically used when the owner of ISocket has crashed.
Implements inet::ISocket.
 {
     auto request = new Request("destroy", SOCKET_C_DESTROY);
     auto *ctrl = new SocketDestroyCommand();
     request->setControlInfo(ctrl);
     sendOut(request);
     isOpen_ = false;
 }
Referenced by inet::EthernetSocketIo::handleCrashOperation(), inet::EtherAppServer::handleCrashOperation(), inet::Ieee8022LlcSocketIo::handleCrashOperation(), inet::EtherTrafGen::handleCrashOperation(), and inet::EtherAppClient::handleCrashOperation().
getSocketId()
int inet::SocketBase::getSocketId () const inline override virtual
Returns the internal socket Id.
Implements inet::ISocket.
 { return socketId; }
getUserData()
void* inet::SocketBase::getUserData () const inline
 { return userData; }
isOpen()
virtual bool inet::SocketBase::isOpen () const inline override virtual
Returns true if the socket is open.
Implements inet::ISocket.
 { return isOpen_; }
Referenced by inet::EtherAppServer::socketClosed(), and inet::EtherAppClient::socketClosed().
send()
void inet::SocketBase::send (Packet * packet) override virtual
Sends a data packet to the address and port specified previously in a connect() call.
Implements inet::ISocket.
 {
     packet->setKind(SOCKET_C_DATA);
     isOpen_ = true;
     sendOut(packet);
 }
Referenced by inet::EthernetSocketIo::handleMessageWhenUp(), inet::Ieee8022LlcSocketIo::handleMessageWhenUp(), inet::EtherAppServer::sendPacket(), and inet::EtherAppClient::sendPacket().
sendOut()
void inet::SocketBase::sendOut (cMessage * msg) protected virtual
Reimplemented in inet::Ieee8021qSocket, inet::EthernetSocket, and inet::Ieee8022LlcSocket.
 {
     if (!isOpen_)
         throw cRuntimeError("Socket is closed");
     if (!outputGate)
         throw cRuntimeError("Socket output gate is not set");
     EV_DEBUG << "Sending message" << EV_FIELD(msg) << EV_ENDL;
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     tags.addTagIfAbsent<SocketReq>()->setSocketId(socketId);
     check_and_cast<cSimpleModule *>(outputGate->getOwnerModule())->send(msg, outputGate);
 }
Referenced by close(), destroy(), send(), inet::Ieee8022LlcSocket::sendOut(), inet::EthernetSocket::sendOut(), and inet::Ieee8021qSocket::sendOut().
setOutputGate()
void inet::SocketBase::setOutputGate (cGate * gate) inline
Sets the gate on which to send messages.
Must be invoked before socket can be used. Example: socket.setOutputGate(gate("out"));
 { this->outputGate = gate; }
Referenced by inet::EthernetSocketIo::handleStartOperation(), inet::Ieee8022LlcSocketIo::handleStartOperation(), inet::EtherAppServer::initialize(), inet::EtherAppClient::initialize(), and inet::EtherTrafGen::initialize().
setUserData()
void inet::SocketBase::setUserData (void * userData) inline
 { this->userData = userData; }
Member Data Documentation
isOpen_
bool inet::SocketBase::isOpen_ = false protected
Referenced by inet::EthernetSocket::bind(), inet::Ieee8021qSocket::bind(), close(), destroy(), inet::Ieee8022LlcSocket::open(), inet::Ieee8022LlcSocket::processMessage(), inet::EthernetSocket::processMessage(), inet::Ieee8021qSocket::processMessage(), send(), and sendOut().
outputGate
cGate* inet::SocketBase::outputGate = nullptr protected
Referenced by sendOut(), and SocketBase().
socketId
int inet::SocketBase::socketId = -1 protected
Referenced by belongsToSocket(), sendOut(), and SocketBase().
userData
void* inet::SocketBase::userData = nullptr protected
The documentation for this class was generated from the following files:
SocketBase.h
SocketBase.cc