INET Framework for OMNeT++/OMNEST: inet::ospfv3::LSATrackingInfo Class Reference
inet::ospfv3::LSATrackingInfo Class Reference
#include <Ospfv3Lsa.h>
Public Types
enum InstallSource { ORIGINATED = 0, FLOODED = 1 }
Public Member Functions
LSATrackingInfo ()
LSATrackingInfo (const LSATrackingInfo &info)
void setSource (InstallSource installSource)
InstallSource getSource () const
void incrementInstallTime ()
void resetInstallTime ()
unsigned long getInstallTime () const
Private Attributes
InstallSource source
unsigned long installTime
Member Enumeration Documentation
InstallSource
enum inet::ospfv3::LSATrackingInfo::InstallSource
Enumerator
ORIGINATED
FLOODED
{
         ORIGINATED = 0,
         FLOODED    = 1
     };
Constructor & Destructor Documentation
LSATrackingInfo() [1/2]
inet::ospfv3::LSATrackingInfo::LSATrackingInfo () inline
 : source(FLOODED), installTime(0) {}
LSATrackingInfo() [2/2]
inet::ospfv3::LSATrackingInfo::LSATrackingInfo (const LSATrackingInfo & info) inline
 : source(info.source), installTime(info.installTime) {}
Member Function Documentation
getInstallTime()
unsigned long inet::ospfv3::LSATrackingInfo::getInstallTime () const inline
 { return installTime; }
Referenced by inet::ospfv3::Ospfv3Interface::processLSU().
getSource()
InstallSource inet::ospfv3::LSATrackingInfo::getSource () const inline
 { return source; }
incrementInstallTime()
void inet::ospfv3::LSATrackingInfo::incrementInstallTime () inline
 { installTime++; }
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3NeighborState::changeState(), and inet::ospfv3::Ospfv3InterfaceState::changeState().
resetInstallTime()
void inet::ospfv3::LSATrackingInfo::resetInstallTime () inline
 { installTime = 0; }
Referenced by inet::ospfv3::Ospfv3Area::updateInterAreaPrefixLSA().
setSource()
void inet::ospfv3::LSATrackingInfo::setSource (InstallSource installSource) inline
 { source = installSource; }
Member Data Documentation
installTime
unsigned long inet::ospfv3::LSATrackingInfo::installTime private
source
InstallSource inet::ospfv3::LSATrackingInfo::source private
The documentation for this class was generated from the following file:
Ospfv3Lsa.h