INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3Lsa Class Reference
inet::ospfv3::Ospfv3Lsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:96 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual Ospfv3Lsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3Lsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:96 by opp_msgtool.
class Ospfv3Lsa extends cObject
{
    @packetData;
    Ospfv3LsaHeader header;
}
Constructor & Destructor Documentation
Ospfv3Lsa() [1/2]
inet::ospfv3::Ospfv3Lsa::Ospfv3Lsa ()
Ospfv3Lsa() [2/2]
inet::ospfv3::Ospfv3Lsa::Ospfv3Lsa (const Ospfv3Lsa & other)
~Ospfv3Lsa()
virtual inet::ospfv3::Ospfv3Lsa::~Ospfv3Lsa () virtual
Member Function Documentation
copy()
void inet::ospfv3::Ospfv3Lsa::copy (const Ospfv3Lsa & other) private
dup()
virtual Ospfv3Lsa* inet::ospfv3::Ospfv3Lsa::dup () const inline override virtual
Reimplemented in inet::ospfv3::Ospfv3IntraAreaPrefixLsa, inet::ospfv3::Ospfv3LinkLsa, inet::ospfv3::Ospfv3NssaLsa, inet::ospfv3::Ospfv3AsExternalLsa, inet::ospfv3::Ospfv3InterAreaRouterLsa, inet::ospfv3::Ospfv3InterAreaPrefixLsa, inet::ospfv3::Ospfv3NetworkLsa, and inet::ospfv3::Ospfv3RouterLsa.
 {return new Ospfv3Lsa(*this);}
Referenced by inet::ospfv3::Ospfv3Neighbor::addToRetransmissionList(), inet::ospfv3::Ospfv3Interface::floodLSA(), and inet::ospfv3::Ospfv3Interface::processLSU().
getHeader()
virtual const Ospfv3LsaHeader& inet::ospfv3::Ospfv3Lsa::getHeader () const virtual
Referenced by inet::ospfv3::Ospfv3Neighbor::addToRetransmissionList(), inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateNextHops(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Neighbor::createDatabaseSummary(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::deleteRouterLSA(), inet::ospfv3::Ospfv3Area::findLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::Ospfv3Process::floodLSA(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::ospfv3::Ospfv3Area::hasLink(), inet::ospfv3::Ospfv3Area::installInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::installIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::installLinkLSA(), inet::ospfv3::Ospfv3Process::installLSA(), inet::ospfv3::Ospfv3Area::installNetworkLSA(), inet::ospfv3::Ospfv3Area::installRouterLSA(), inet::ospfv3::Ospfv3Area::InterAreaPrefixLSAAlreadyExists(), inet::ospfv3::Ospfv3Area::interAreaPrefixLSADiffersFrom(), inet::ospfv3::Ospfv3Area::IntraAreaPrefixLSAAlreadyExists(), inet::ospfv3::Ospfv3Area::intraAreaPrefixLSADiffersFrom(), inet::ospfv3::Ospfv3Interface::linkLSADiffersFrom(), inet::ospfv3::Ospfv3Area::networkLSADiffersFrom(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3SpfVertex::Ospfv3SpfVertex(), inet::ospfv3::Ospfv3Interface::prepareUpdatePacket(), inet::ospfv3::Ospfv3Interface::processLSAck(), inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::ospfv3::Ospfv3Area::routerLSAAlreadyExists(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getHeaderForUpdate()
virtual Ospfv3LsaHeader& inet::ospfv3::Ospfv3Lsa::getHeaderForUpdate () inline virtual
 { return const_cast<Ospfv3LsaHeader&>(const_cast<Ospfv3Lsa*>(this)->getHeader());}
Referenced by inet::ospfv3::Ospfv3Area::ageDatabase(), inet::ospfv3::Ospfv3Interface::ageDatabase(), inet::ospfv3::Ospfv3Area::calculateNextHops(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::ospfv3::Ospfv3Area::deleteRouterLSA(), inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), inet::ospfv3::Ospfv3Area::originateRouterLSA(), and inet::ospfv3::Ospfv3Interface::processLSU().
operator=()
Ospfv3Lsa& inet::ospfv3::Ospfv3Lsa::operator= (const Ospfv3Lsa & other)
operator==()
bool inet::ospfv3::Ospfv3Lsa::operator== (const Ospfv3Lsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3Lsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::ospfv3::Ospfv3IntraAreaPrefixLsa, inet::ospfv3::Ospfv3LinkLsa, inet::ospfv3::Ospfv3NssaLsa, inet::ospfv3::Ospfv3AsExternalLsa, inet::ospfv3::Ospfv3InterAreaRouterLsa, inet::ospfv3::Ospfv3InterAreaPrefixLsa, inet::ospfv3::Ospfv3NetworkLsa, and inet::ospfv3::Ospfv3RouterLsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3Lsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::ospfv3::Ospfv3IntraAreaPrefixLsa, inet::ospfv3::Ospfv3LinkLsa, inet::ospfv3::Ospfv3NssaLsa, inet::ospfv3::Ospfv3AsExternalLsa, inet::ospfv3::Ospfv3InterAreaRouterLsa, inet::ospfv3::Ospfv3InterAreaPrefixLsa, inet::ospfv3::Ospfv3NetworkLsa, and inet::ospfv3::Ospfv3RouterLsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setHeader()
virtual void inet::ospfv3::Ospfv3Lsa::setHeader (const Ospfv3LsaHeader & header) virtual
Member Data Documentation
header
Ospfv3LsaHeader inet::ospfv3::Ospfv3Lsa::header protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h