INET Framework for OMNeT++/OMNEST: inet::Ipv6NeighbourCache::DefaultRouterList Class Reference
inet::Ipv6NeighbourCache::DefaultRouterList Class Reference
#include <Ipv6NeighbourCache.h>
Classes
class iterator
Public Member Functions
DefaultRouterList ()
void clear ()
Neighbour * getHead () const
void setHead (Neighbour &router)
void add (Neighbour &router)
void remove (Neighbour &router)
iterator begin ()
iterator end ()
Private Attributes
Neighbour * head
Constructor & Destructor Documentation
DefaultRouterList()
inet::Ipv6NeighbourCache::DefaultRouterList::DefaultRouterList () inline
 : head(nullptr) {}
Member Function Documentation
add()
void inet::Ipv6NeighbourCache::DefaultRouterList::add (Neighbour & router)
 {
     ASSERT(router.isRouter);
     ASSERT(!router.nextDefaultRouter);
     ASSERT(!router.prevDefaultRouter);
     if (head) {
         // insert before head
         head->prevDefaultRouter->nextDefaultRouter = &router;
         router.prevDefaultRouter = head;
         head->prevDefaultRouter = &router;
         router.nextDefaultRouter = head;
     }
     else {
         head = router.nextDefaultRouter = router.prevDefaultRouter = &router;
     }
 }
Referenced by inet::Ipv6NeighbourCache::addRouter().
begin()
iterator inet::Ipv6NeighbourCache::DefaultRouterList::begin () inline
 { return iterator(head); }
Referenced by inet::Ipv6NeighbourDiscovery::selectDefaultRouter().
clear()
void inet::Ipv6NeighbourCache::DefaultRouterList::clear () inline
 { head = nullptr; }
Referenced by inet::Ipv6NeighbourCache::invalidateAllEntries().
end()
iterator inet::Ipv6NeighbourCache::DefaultRouterList::end () inline
 { return iterator(nullptr); }
Referenced by inet::Ipv6NeighbourDiscovery::selectDefaultRouter().
getHead()
Neighbour* inet::Ipv6NeighbourCache::DefaultRouterList::getHead () const inline
 { return head; }
Referenced by inet::Ipv6NeighbourDiscovery::selectDefaultRouter().
remove()
void inet::Ipv6NeighbourCache::DefaultRouterList::remove (Neighbour & router)
 {
     ASSERT(router.isDefaultRouter());
     if (router.nextDefaultRouter == &router) {
         head = nullptr;
     }
     else {
         if (head == &router)
             head = router.nextDefaultRouter;
         router.nextDefaultRouter->prevDefaultRouter = router.prevDefaultRouter;
         router.prevDefaultRouter->nextDefaultRouter = router.nextDefaultRouter;
     }
     router.nextDefaultRouter = router.prevDefaultRouter = nullptr;
 }
Referenced by inet::Ipv6NeighbourDiscovery::processNaForIncompleteNceState(), inet::Ipv6NeighbourDiscovery::processNaForOtherNceStates(), and inet::Ipv6NeighbourCache::remove().
setHead()
void inet::Ipv6NeighbourCache::DefaultRouterList::setHead (Neighbour & router) inline
 { ASSERT(router.isDefaultRouter()); head = &router; }
Referenced by inet::Ipv6NeighbourDiscovery::selectDefaultRouter().
Member Data Documentation
head
Neighbour* inet::Ipv6NeighbourCache::DefaultRouterList::head private
Referenced by add().
The documentation for this class was generated from the following files:
Ipv6NeighbourCache.h
Ipv6NeighbourCache.cc