INET Framework for OMNeT++/OMNEST: inet::INetworkSocket::ICallback Class Reference
inet::INetworkSocket::ICallback Class Reference abstract
#include <INetworkSocket.h>
Public Member Functions
virtual ~ICallback ()
virtual void socketDataArrived (INetworkSocket *socket, Packet *packet)=0
virtual void socketClosed (INetworkSocket *socket)=0
Constructor & Destructor Documentation
~ICallback()
virtual inet::INetworkSocket::ICallback::~ICallback () inline virtual
 {}
Member Function Documentation
socketClosed()
virtual void inet::INetworkSocket::ICallback::socketClosed (INetworkSocket * socket) pure virtual
Implemented in inet::PingApp, inet::Ipv4Socket::ICallback, inet::L3Socket::ICallback, and inet::Ipv6Socket::ICallback.
Referenced by inet::Ipv6Socket::processMessage(), inet::Ipv4Socket::processMessage(), and inet::L3Socket::processMessage().
socketDataArrived()
virtual void inet::INetworkSocket::ICallback::socketDataArrived (INetworkSocket * socket, Packet * packet) pure virtual
Implemented in inet::PingApp, inet::Ipv4Socket::ICallback, inet::L3Socket::ICallback, and inet::Ipv6Socket::ICallback.
Referenced by inet::Ipv6Socket::processMessage(), inet::Ipv4Socket::processMessage(), and inet::L3Socket::processMessage().
The documentation for this class was generated from the following file:
INetworkSocket.h