INET Framework for OMNeT++/OMNEST: inet::SignallingMsg Class Reference
inet::SignallingMsg Class Reference
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:38 by opp_msgtool.
#include <SignallingMsg_m.h>
Public Member Functions
SignallingMsg (const char *name=nullptr, short kind=0)
SignallingMsg (const SignallingMsg &other)
virtual ~SignallingMsg ()
SignallingMsg & operator= (const SignallingMsg &other)
virtual SignallingMsg * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getCommand () const
virtual void setCommand (int command)
Protected Member Functions
bool operator== (const SignallingMsg &)=delete
Protected Attributes
int command = 0
Private Member Functions
void copy (const SignallingMsg &other)
Detailed Description
Class generated from inet/networklayer/rsvpte/SignallingMsg.msg:38 by opp_msgtool.
//
// FIXME missing documentation
//
message SignallingMsg
{
    int command = 0;
}
Constructor & Destructor Documentation
SignallingMsg() [1/2]
inet::SignallingMsg::SignallingMsg (const char * name = nullptr, short kind = 0)
SignallingMsg() [2/2]
inet::SignallingMsg::SignallingMsg (const SignallingMsg & other)
~SignallingMsg()
virtual inet::SignallingMsg::~SignallingMsg () virtual
Member Function Documentation
copy()
void inet::SignallingMsg::copy (const SignallingMsg & other) private
dup()
virtual SignallingMsg* inet::SignallingMsg::dup () const inline override virtual
Reimplemented in inet::PathNotifyMsg, inet::HelloTimeoutMsg, inet::HelloTimerMsg, inet::RsbTimeoutMsg, inet::RsbCommitTimerMsg, inet::RsbRefreshTimerMsg, inet::PsbTimeoutMsg, and inet::PsbTimerMsg.
 {return new SignallingMsg(*this);}
getCommand()
virtual int inet::SignallingMsg::getCommand () const virtual
Referenced by inet::RsvpTe::processSignallingMessage().
operator=()
SignallingMsg& inet::SignallingMsg::operator= (const SignallingMsg & other)
operator==()
bool inet::SignallingMsg::operator== (const SignallingMsg &) protected delete
parsimPack()
virtual void inet::SignallingMsg::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::PathNotifyMsg, inet::HelloTimeoutMsg, inet::HelloTimerMsg, inet::RsbTimeoutMsg, inet::RsbCommitTimerMsg, inet::RsbRefreshTimerMsg, inet::PsbTimeoutMsg, and inet::PsbTimerMsg.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SignallingMsg::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::PathNotifyMsg, inet::HelloTimeoutMsg, inet::HelloTimerMsg, inet::RsbTimeoutMsg, inet::RsbCommitTimerMsg, inet::RsbRefreshTimerMsg, inet::PsbTimeoutMsg, and inet::PsbTimerMsg.
Referenced by inet::doParsimUnpacking().
setCommand()
virtual void inet::SignallingMsg::setCommand (int command) virtual
Member Data Documentation
command
int inet::SignallingMsg::command = 0 protected
The documentation for this class was generated from the following file:
SignallingMsg_m.h