INET Framework for OMNeT++/OMNEST: inet::physicallayer::ISignalAnalogModel Class Reference
inet::physicallayer::ISignalAnalogModel Class Reference abstract
This purely virtual interface provides an abstraction for different radio signal models in the analog domain.
#include <ISignalAnalogModel.h>
Public Member Functions
virtual const simtime_t getDuration () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This purely virtual interface provides an abstraction for different radio signal models in the analog domain.
Member Function Documentation
getDuration()
virtual const simtime_t inet::physicallayer::ISignalAnalogModel::getDuration () const pure virtual
Implemented in inet::physicallayer::TransmissionBase, inet::physicallayer::ReceptionBase, and inet::physicallayer::SignalAnalogModel.
Referenced by inet::physicallayer::ScalarAnalogDigitalConverter::convertAnalogToDigital(), inet::physicallayer::ApskLayeredTransmitter::createTransmission(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createTransmission().
The documentation for this class was generated from the following file:
ISignalAnalogModel.h