INET Framework for OMNeT++/OMNEST: inet::IPcapWriter Class Reference
inet::IPcapWriter Class Reference abstract
#include <IPcapWriter.h>
Public Member Functions
virtual ~IPcapWriter ()
virtual void open (const char *filename, unsigned int snaplen)=0
virtual void close ()=0
virtual bool isOpen () const =0
virtual void setFlush (bool flush)=0
virtual void writePacket (simtime_t time, const Packet *packet, Direction direction, NetworkInterface *ie, PcapLinkType linkType)=0
Constructor & Destructor Documentation
~IPcapWriter()
virtual inet::IPcapWriter::~IPcapWriter () inline virtual
 {}
Member Function Documentation
close()
virtual void inet::IPcapWriter::close () pure virtual
Implemented in inet::PcapWriter, and inet::PcapngWriter.
Referenced by inet::PcapRecorder::finish().
isOpen()
virtual bool inet::IPcapWriter::isOpen () const pure virtual
Implemented in inet::PcapWriter, and inet::PcapngWriter.
Referenced by inet::PcapRecorder::receiveSignal().
open()
virtual void inet::IPcapWriter::open (const char * filename, unsigned int snaplen) pure virtual
Implemented in inet::PcapWriter, and inet::PcapngWriter.
Referenced by inet::PcapRecorder::initialize().
setFlush()
virtual void inet::IPcapWriter::setFlush (bool flush) pure virtual
Implemented in inet::PcapWriter, and inet::PcapngWriter.
Referenced by inet::PcapRecorder::initialize().
writePacket()
virtual void inet::IPcapWriter::writePacket (simtime_t time, const Packet * packet, Direction direction, NetworkInterface * ie, PcapLinkType linkType) pure virtual
Implemented in inet::PcapWriter, and inet::PcapngWriter.
Referenced by inet::PcapRecorder::recordPacket().
The documentation for this class was generated from the following file:
IPcapWriter.h