INET Framework for OMNeT++/OMNEST: inet::physicallayer::IIeee80211DataMode Class Reference
inet::physicallayer::IIeee80211DataMode Class Reference abstract
#include <IIeee80211Mode.h>
Public Member Functions
virtual Hz getBandwidth () const =0
virtual bps getNetBitrate () const =0
virtual bps getGrossBitrate () const =0
virtual b getPaddingLength (b dataLength) const =0
virtual b getCompleteLength (b dataLength) const =0
virtual const simtime_t getDuration (b dataLength) const =0
virtual const IModulation * getModulation () const =0
virtual int getNumberOfSpatialStreams () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
getBandwidth()
virtual Hz inet::physicallayer::IIeee80211DataMode::getBandwidth () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211TransmitterBase::setMode().
getCompleteLength()
virtual b inet::physicallayer::IIeee80211DataMode::getCompleteLength (b dataLength) const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), and inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission().
getDuration()
virtual const simtime_t inet::physicallayer::IIeee80211DataMode::getDuration (b dataLength) const pure virtual
Implemented in inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, inet::physicallayer::Ieee80211FhssDataMode, inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, and inet::physicallayer::Ieee80211OfdmDataMode.
getGrossBitrate()
virtual bps inet::physicallayer::IIeee80211DataMode::getGrossBitrate () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
getModulation()
virtual const IModulation* inet::physicallayer::IIeee80211DataMode::getModulation () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
getNetBitrate()
virtual bps inet::physicallayer::IIeee80211DataMode::getNetBitrate () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), inet::physicallayer::Ieee80211ModeSet::EntryNetBitrateComparator::operator()(), inet::physicallayer::Ieee80211TransmitterBase::setMode(), inet::physicallayer::Ieee80211TransmitterBase::setModeSet(), inet::ieee80211::Dcf::transmitControlResponseFrame(), and inet::ieee80211::Hcf::transmitControlResponseFrame().
getNumberOfSpatialStreams()
virtual int inet::physicallayer::IIeee80211DataMode::getNumberOfSpatialStreams () const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
getPaddingLength()
virtual b inet::physicallayer::IIeee80211DataMode::getPaddingLength (b dataLength) const pure virtual
Implemented in inet::physicallayer::Ieee80211VhtDataMode, inet::physicallayer::Ieee80211HtDataMode, inet::physicallayer::Ieee80211OfdmDataMode, inet::physicallayer::Ieee80211HrDsssDataMode, inet::physicallayer::Ieee80211IrDataMode, inet::physicallayer::Ieee80211DsssDataMode, and inet::physicallayer::Ieee80211FhssDataMode.
The documentation for this class was generated from the following file:
IIeee80211Mode.h