INET Framework for OMNeT++/OMNEST: inet::power::EpEnergySinkBase Class Reference
inet::power::EpEnergySinkBase Class Reference
#include <EpEnergySinkBase.h>
Public Member Functions
virtual W getTotalPowerGeneration () const override
Returns the total power generation in the range [0, +infinity).
virtual void addEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Adds a new energy generator to the energy sink.
virtual void removeEnergyGenerator (const IEnergyGenerator *energyGenerator) override
Removes a previously added energy generator from this energy sink.
Public Member Functions inherited from inet::power::EnergySinkBase
virtual int getNumEnergyGenerators () const override
Returns the number of energy generators in the range [0, +infinity).
virtual const IEnergyGenerator * getEnergyGenerator (int index) const override
Returns the energy generator for the provided index.
Public Member Functions inherited from inet::power::IEnergySink
virtual ~IEnergySink ()
Protected Member Functions
virtual W computeTotalPowerGeneration () const
virtual void updateTotalPowerGeneration ()
Protected Attributes
W totalPowerGeneration = W(NaN)
Protected Attributes inherited from inet::power::EnergySinkBase
std::vector< const IEnergyGenerator * > energyGenerators
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergySink
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Member Function Documentation
addEnergyGenerator()
void inet::power::EpEnergySinkBase::addEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Adds a new energy generator to the energy sink.
The energyGenerator parameter must not be nullptr.
Reimplemented from inet::power::EnergySinkBase.
Reimplemented in inet::power::EpEnergyStorageBase.
 {
     EnergySinkBase::addEnergyGenerator(energyGenerator);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyGenerator));
     module->subscribe(IEpEnergyGenerator::powerGenerationChangedSignal, this);
     updateTotalPowerGeneration();
 }
Referenced by inet::power::EpEnergyStorageBase::addEnergyGenerator().
computeTotalPowerGeneration()
W inet::power::EpEnergySinkBase::computeTotalPowerGeneration () const protected virtual
 {
     W totalPowerGeneration = W(0);
     for (auto energyGenerator : energyGenerators)
         totalPowerGeneration += check_and_cast<const IEpEnergyGenerator *>(energyGenerator)->getPowerGeneration();
     return totalPowerGeneration;
 }
Referenced by inet::power::EpEnergyStorageBase::initialize(), and updateTotalPowerGeneration().
getTotalPowerGeneration()
virtual W inet::power::EpEnergySinkBase::getTotalPowerGeneration () const inline override virtual
Returns the total power generation in the range [0, +infinity).
Implements inet::power::IEpEnergySink.
 { return totalPowerGeneration; }
removeEnergyGenerator()
void inet::power::EpEnergySinkBase::removeEnergyGenerator (const IEnergyGenerator * energyGenerator) override virtual
Removes a previously added energy generator from this energy sink.
This functions throws an exception if the generator is not found.
Reimplemented from inet::power::EnergySinkBase.
Reimplemented in inet::power::EpEnergyStorageBase.
 {
     EnergySinkBase::removeEnergyGenerator(energyGenerator);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyGenerator));
     module->unsubscribe(IEpEnergyGenerator::powerGenerationChangedSignal, this);
     updateTotalPowerGeneration();
 }
Referenced by inet::power::EpEnergyStorageBase::removeEnergyGenerator().
updateTotalPowerGeneration()
void inet::power::EpEnergySinkBase::updateTotalPowerGeneration () protected virtual
Reimplemented in inet::power::SimpleEpEnergyStorage, inet::power::IdealEpEnergyStorage, and inet::power::EpEnergyStorageBase.
 {
     totalPowerGeneration = computeTotalPowerGeneration();
 }
Referenced by addEnergyGenerator(), removeEnergyGenerator(), and inet::power::EpEnergyStorageBase::updateTotalPowerGeneration().
Member Data Documentation
totalPowerGeneration
W inet::power::EpEnergySinkBase::totalPowerGeneration = W(NaN) protected
Referenced by computeTotalPowerGeneration(), inet::power::EpEnergyStorageBase::initialize(), inet::power::SimpleEpEnergyStorage::scheduleTimer(), inet::power::IdealEpEnergyStorage::updateEnergyBalance(), inet::power::SimpleEpEnergyStorage::updateResidualCapacity(), inet::power::EpEnergyStorageBase::updateTotalPowerGeneration(), and updateTotalPowerGeneration().
The documentation for this class was generated from the following files:
EpEnergySinkBase.h
EpEnergySinkBase.cc