INET Framework for OMNeT++/OMNEST: inet::Ieee8022LlcSocket Class Reference
inet::Ieee8022LlcSocket Class Reference
#include <Ieee8022LlcSocket.h>
Classes
class ICallback
Public Member Functions
void setCallback (ICallback *callback)
Sets a callback object, to be used with processMessage().
virtual int getInterfaceId () const
Returns the interface Id.
virtual int getLocalSap () const
Returns the local SAP.
virtual int getRemoteSap () const
Returns the remote SAP.
virtual void open (int interfaceId, int localSap, int remoteSap)
virtual void processMessage (cMessage *msg) override
Examines the message, takes ownership, and updates socket state.
Public Member Functions inherited from inet::SocketBase
SocketBase ()
virtual ~SocketBase ()
void setOutputGate (cGate *gate)
Sets the gate on which to send messages.
int getSocketId () const override
Returns the internal socket Id.
virtual void send (Packet *packet) override
Sends a data packet to the address and port specified previously in a connect() call.
virtual bool isOpen () const override
Returns true if the socket is open.
virtual void close () override
Unbinds the socket.
virtual void destroy () override
Notify the protocol that the owner of ISocket has destroyed the socket.
virtual bool belongsToSocket (cMessage *msg) const override
Returns true if the message belongs to this socket instance.
void * getUserData () const
void setUserData (void *userData)
Public Member Functions inherited from inet::ISocket
virtual ~ISocket ()
Protected Member Functions
virtual void sendOut (cMessage *msg) override
Protected Attributes
int interfaceId = -1
int localSap = -1
int remoteSap = -1
ICallback * callback = nullptr
Protected Attributes inherited from inet::SocketBase
cGate * outputGate = nullptr
int socketId = -1
bool isOpen_ = false
void * userData = nullptr
Member Function Documentation
getInterfaceId()
virtual int inet::Ieee8022LlcSocket::getInterfaceId () const inline virtual
Returns the interface Id.
 { return interfaceId; }
getLocalSap()
virtual int inet::Ieee8022LlcSocket::getLocalSap () const inline virtual
Returns the local SAP.
 { return localSap; }
getRemoteSap()
virtual int inet::Ieee8022LlcSocket::getRemoteSap () const inline virtual
Returns the remote SAP.
 { return remoteSap; }
open()
void inet::Ieee8022LlcSocket::open (int interfaceId, int localSap, int remoteSap) virtual
 {
     if (localSap < -1 || localSap > 255)
         throw cRuntimeError("Invalid localSap value: %d", localSap);
     if (remoteSap < -1 || remoteSap > 255)
         throw cRuntimeError("Invalid remoteSap value: %d", remoteSap);
     this->interfaceId = interfaceId;
     this->localSap = localSap;
     this->remoteSap = remoteSap;
     auto request = new Request("LLC_OPEN", SOCKET_C_OPEN);
     Ieee8022LlcSocketOpenCommand *command = new Ieee8022LlcSocketOpenCommand();
     command->setLocalSap(localSap);
     request->setControlInfo(command);
     isOpen_ = true;
     sendOut(request);
 }
Referenced by inet::EtherAppClient::handleMessageWhenUp(), inet::EtherTrafGen::handleMessageWhenUp(), inet::Ieee8022LlcSocketIo::handleStartOperation(), and inet::EtherAppServer::registerDsap().
processMessage()
void inet::Ieee8022LlcSocket::processMessage (cMessage * msg) override virtual
Examines the message, takes ownership, and updates socket state.
Implements inet::ISocket.
 {
     ASSERT(belongsToSocket(msg));
     switch (msg->getKind()) {
         case SOCKET_I_DATA:
             if (callback)
                 callback->socketDataArrived(this, check_and_cast<Packet *>(msg));
             else
                 delete msg;
             break;
         case SOCKET_I_CLOSED:
             isOpen_ = false;
             if (callback)
                 callback->socketClosed(this);
             delete msg;
             break;
         default:
             throw cRuntimeError("Ieee8022LlcSocket: invalid msg kind %d, one of the SOCKET_I_xxx constants expected", msg->getKind());
             break;
     }
 }
Referenced by inet::Ieee8022LlcSocketIo::handleMessageWhenUp(), inet::EtherAppServer::handleMessageWhenUp(), and inet::EtherAppClient::handleMessageWhenUp().
sendOut()
void inet::Ieee8022LlcSocket::sendOut (cMessage * msg) override protected virtual
Reimplemented from inet::SocketBase.
 {
     auto& tags = check_and_cast<ITaggedObject *>(msg)->getTags();
     tags.addTagIfAbsent<DispatchProtocolReq>()->setProtocol(&Protocol::ieee8022llc);
     if (localSap != -1) {
         auto& sapReq = tags.addTagIfAbsent<Ieee802SapReq>();
         if (sapReq->getSsap() == -1)
             sapReq->setSsap(localSap);
     }
     if (remoteSap != -1) {
         auto& sapReq = tags.addTagIfAbsent<Ieee802SapReq>();
         if (sapReq->getDsap() == -1)
             sapReq->setDsap(remoteSap);
     }
     if (interfaceId != -1) {
         auto& interfaceReq = tags.addTagIfAbsent<InterfaceReq>();
         if (interfaceReq->getInterfaceId() == -1)
             interfaceReq->setInterfaceId(interfaceId);
     }
     SocketBase::sendOut(msg);
 }
Referenced by open().
setCallback()
void inet::Ieee8022LlcSocket::setCallback (ICallback * callback) inline
Sets a callback object, to be used with processMessage().
This callback object may be your simple module itself (if it multiply inherits from ICallback too, that is you declared it as
class MyAppModule : public cSimpleModule, public LlcSocket::ICallback
and redefined the necessary virtual functions; or you may use dedicated class (and objects) for this purpose.
LlcSocket doesn't delete the callback object in the destructor or on any other occasion.
 { this->callback = callback; }
Referenced by inet::EtherAppServer::initialize(), inet::EtherAppClient::initialize(), and inet::Ieee8022LlcSocketIo::setSocketOptions().
Member Data Documentation
callback
ICallback* inet::Ieee8022LlcSocket::callback = nullptr protected
Referenced by processMessage().
interfaceId
int inet::Ieee8022LlcSocket::interfaceId = -1 protected
Referenced by open(), and sendOut().
localSap
int inet::Ieee8022LlcSocket::localSap = -1 protected
Referenced by open(), and sendOut().
remoteSap
int inet::Ieee8022LlcSocket::remoteSap = -1 protected
Referenced by open(), and sendOut().
The documentation for this class was generated from the following files:
Ieee8022LlcSocket.h
Ieee8022LlcSocket.cc