INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211PrimConfirm Class Reference
inet::ieee80211::Ieee80211PrimConfirm Class Reference
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:86 by opp_msgtool.
#include <Ieee80211Primitives_m.h>
Public Member Functions
Ieee80211PrimConfirm ()
Ieee80211PrimConfirm (const Ieee80211PrimConfirm &other)
virtual ~Ieee80211PrimConfirm ()
Ieee80211PrimConfirm & operator= (const Ieee80211PrimConfirm &other)
virtual Ieee80211PrimConfirm * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual Ieee80211PrimResultCode getResultCode () const
virtual void setResultCode (Ieee80211PrimResultCode resultCode)
Protected Member Functions
bool operator== (const Ieee80211PrimConfirm &)=delete
Protected Attributes
Ieee80211PrimResultCode resultCode = static_cast<inet::ieee80211::Ieee80211PrimResultCode>(-1)
Private Member Functions
void copy (const Ieee80211PrimConfirm &other)
Detailed Description
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:86 by opp_msgtool.
//
// Base class for confirm primitives
//
class Ieee80211PrimConfirm extends cObject
{
    Ieee80211PrimResultCode resultCode;
}
Constructor & Destructor Documentation
Ieee80211PrimConfirm() [1/2]
inet::ieee80211::Ieee80211PrimConfirm::Ieee80211PrimConfirm ()
Ieee80211PrimConfirm() [2/2]
inet::ieee80211::Ieee80211PrimConfirm::Ieee80211PrimConfirm (const Ieee80211PrimConfirm & other)
~Ieee80211PrimConfirm()
virtual inet::ieee80211::Ieee80211PrimConfirm::~Ieee80211PrimConfirm () virtual
Member Function Documentation
copy()
void inet::ieee80211::Ieee80211PrimConfirm::copy (const Ieee80211PrimConfirm & other) private
dup()
virtual Ieee80211PrimConfirm* inet::ieee80211::Ieee80211PrimConfirm::dup () const inline override virtual
Reimplemented in inet::ieee80211::Ieee80211Prim_ReassociateConfirm, inet::ieee80211::Ieee80211Prim_AssociateConfirm, inet::ieee80211::Ieee80211Prim_AuthenticateConfirm, and inet::ieee80211::Ieee80211Prim_ScanConfirm.
 {return new Ieee80211PrimConfirm(*this);}
getResultCode()
virtual Ieee80211PrimResultCode inet::ieee80211::Ieee80211PrimConfirm::getResultCode () const virtual
Referenced by inet::ieee80211::Ieee80211AgentSta::processAssociateConfirm(), inet::ieee80211::Ieee80211AgentSta::processAuthenticateConfirm(), and inet::ieee80211::Ieee80211AgentSta::processReassociateConfirm().
operator=()
Ieee80211PrimConfirm& inet::ieee80211::Ieee80211PrimConfirm::operator= (const Ieee80211PrimConfirm & other)
operator==()
bool inet::ieee80211::Ieee80211PrimConfirm::operator== (const Ieee80211PrimConfirm &) protected delete
parsimPack()
virtual void inet::ieee80211::Ieee80211PrimConfirm::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::ieee80211::Ieee80211Prim_ReassociateConfirm, inet::ieee80211::Ieee80211Prim_AssociateConfirm, inet::ieee80211::Ieee80211Prim_AuthenticateConfirm, and inet::ieee80211::Ieee80211Prim_ScanConfirm.
Referenced by inet::ieee80211::doParsimPacking().
parsimUnpack()
virtual void inet::ieee80211::Ieee80211PrimConfirm::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::ieee80211::Ieee80211Prim_ReassociateConfirm, inet::ieee80211::Ieee80211Prim_AssociateConfirm, inet::ieee80211::Ieee80211Prim_AuthenticateConfirm, and inet::ieee80211::Ieee80211Prim_ScanConfirm.
Referenced by inet::ieee80211::doParsimUnpacking().
setResultCode()
virtual void inet::ieee80211::Ieee80211PrimConfirm::setResultCode (Ieee80211PrimResultCode resultCode) virtual
Referenced by inet::ieee80211::Ieee80211MgmtSta::sendConfirm().
Member Data Documentation
resultCode
Ieee80211PrimResultCode inet::ieee80211::Ieee80211PrimConfirm::resultCode = static_cast<inet::ieee80211::Ieee80211PrimResultCode>(-1) protected
The documentation for this class was generated from the following file:
Ieee80211Primitives_m.h