INET Framework for OMNeT++/OMNEST: inet::physicallayer::IReception Class Reference
inet::physicallayer::IReception Class Reference abstract
This interface represents the reception of a transmission at a receiver.
#include <IReception.h>
Public Member Functions
virtual const IRadio * getReceiver () const =0
Returns the receiver that received the corresponding transmission from the radio medium.
virtual const ITransmission * getTransmission () const =0
Returns the transmission that corresponds to this reception at the receiver.
virtual const simtime_t getStartTime () const =0
Returns the time when the receiver started to receive the corresponding transmission.
virtual const simtime_t getEndTime () const =0
Returns the time when the receiver ended to receive the corresponding transmission.
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const =0
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const =0
virtual const simtime_t getPreambleStartTime () const =0
virtual const simtime_t getPreambleEndTime () const =0
virtual const simtime_t getHeaderStartTime () const =0
virtual const simtime_t getHeaderEndTime () const =0
virtual const simtime_t getDataStartTime () const =0
virtual const simtime_t getDataEndTime () const =0
virtual const simtime_t getDuration () const =0
Returns the total length of this reception.
virtual const simtime_t getDuration (IRadioSignal::SignalPart part) const =0
Returns the length of the provided part of this reception.
virtual const simtime_t getPreambleDuration () const =0
Returns the length of the preamble part of this reception.
virtual const simtime_t getHeaderDuration () const =0
Returns the length of the header part of this reception.
virtual const simtime_t getDataDuration () const =0
Returns the length of the data part of this reception.
virtual const Coord & getStartPosition () const =0
Returns the antenna's position when the receiver started to receive the corresponding transmission.
virtual const Coord & getEndPosition () const =0
Returns the antenna's position when the receiver ended to receive the corresponding transmission.
virtual const Quaternion & getStartOrientation () const =0
Returns the antenna's orientation when the receiver started to receive the corresponding transmission.
virtual const Quaternion & getEndOrientation () const =0
Returns the antenna's orientation when the receiver ended to receive the corresponding transmission.
virtual const IReceptionAnalogModel * getAnalogModel () const =0
Returns the analog model of the received signal.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents the reception of a transmission at a receiver.
There's one instance per transmission of this interface for each receiver.
This interface is strictly immutable to safely support parallel computation.
Member Function Documentation
getAnalogModel()
virtual const IReceptionAnalogModel* inet::physicallayer::IReception::getAnalogModel () const pure virtual
Returns the analog model of the received signal.
Implemented in inet::physicallayer::ReceptionBase, and inet::physicallayer::LayeredReception.
Referenced by inet::physicallayer::ScalarAnalogModelBase::addReception(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeIsReceptionPossible(), inet::physicallayer::ScalarSnir::computeMax(), and inet::physicallayer::ScalarSnir::computeMin().
getDataDuration()
virtual const simtime_t inet::physicallayer::IReception::getDataDuration () const pure virtual
Returns the length of the data part of this reception.
Implemented in inet::physicallayer::ReceptionBase.
getDataEndTime()
virtual const simtime_t inet::physicallayer::IReception::getDataEndTime () const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getDataStartTime()
virtual const simtime_t inet::physicallayer::IReception::getDataStartTime () const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getDuration() [1/2]
virtual const simtime_t inet::physicallayer::IReception::getDuration () const pure virtual
Returns the total length of this reception.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::StochasticErrorModel::computePacketErrorRate().
getDuration() [2/2]
virtual const simtime_t inet::physicallayer::IReception::getDuration (IRadioSignal::SignalPart part) const pure virtual
Returns the length of the provided part of this reception.
Implemented in inet::physicallayer::ReceptionBase.
getEndOrientation()
virtual const Quaternion& inet::physicallayer::IReception::getEndOrientation () const pure virtual
Returns the antenna's orientation when the receiver ended to receive the corresponding transmission.
Implemented in inet::physicallayer::ReceptionBase.
getEndPosition()
virtual const Coord& inet::physicallayer::IReception::getEndPosition () const pure virtual
Returns the antenna's position when the receiver ended to receive the corresponding transmission.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::RadioMedium::isInterferingTransmission(), and inet::physicallayer::CommunicationLog::writeReception().
getEndTime() [1/2]
virtual const simtime_t inet::physicallayer::IReception::getEndTime () const pure virtual
Returns the time when the receiver ended to receive the corresponding transmission.
It is the end of the last bit's reception.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::ScalarAnalogModelBase::addReception(), inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::FlatReceiverBase::computeIsReceptionPossible(), inet::physicallayer::ApskLayeredReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeIsReceptionPossible(), inet::physicallayer::UnitDiskReceiver::computeIsReceptionSuccessful(), inet::physicallayer::ScalarSnir::computeMax(), inet::physicallayer::DimensionalSnir::computeMax(), inet::physicallayer::DimensionalSnir::computeMean(), inet::physicallayer::ScalarSnir::computeMin(), inet::physicallayer::DimensionalSnir::computeMin(), inet::physicallayer::UnitDiskAnalogModel::computeNoise(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), inet::physicallayer::ReceiverBase::computeReceptionResult(), inet::physicallayer::Ieee802154UwbIrReceiver::decode(), inet::physicallayer::RadioMedium::isInterferingTransmission(), and inet::physicallayer::CommunicationLog::writeReception().
getEndTime() [2/2]
virtual const simtime_t inet::physicallayer::IReception::getEndTime (IRadioSignal::SignalPart part) const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getHeaderDuration()
virtual const simtime_t inet::physicallayer::IReception::getHeaderDuration () const pure virtual
Returns the length of the header part of this reception.
Implemented in inet::physicallayer::ReceptionBase.
getHeaderEndTime()
virtual const simtime_t inet::physicallayer::IReception::getHeaderEndTime () const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getHeaderStartTime()
virtual const simtime_t inet::physicallayer::IReception::getHeaderStartTime () const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getPreambleDuration()
virtual const simtime_t inet::physicallayer::IReception::getPreambleDuration () const pure virtual
Returns the length of the preamble part of this reception.
Implemented in inet::physicallayer::ReceptionBase.
getPreambleEndTime()
virtual const simtime_t inet::physicallayer::IReception::getPreambleEndTime () const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getPreambleStartTime()
virtual const simtime_t inet::physicallayer::IReception::getPreambleStartTime () const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getReceiver()
virtual const IRadio* inet::physicallayer::IReception::getReceiver () const pure virtual
Returns the receiver that received the corresponding transmission from the radio medium.
This function never returns nullptr.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::ReceiverBase::computeIsReceptionAttempted(), inet::physicallayer::RadioMedium::isInterferingTransmission(), and inet::physicallayer::CommunicationLog::writeReception().
getStartOrientation()
virtual const Quaternion& inet::physicallayer::IReception::getStartOrientation () const pure virtual
Returns the antenna's orientation when the receiver started to receive the corresponding transmission.
Implemented in inet::physicallayer::ReceptionBase.
getStartPosition()
virtual const Coord& inet::physicallayer::IReception::getStartPosition () const pure virtual
Returns the antenna's position when the receiver started to receive the corresponding transmission.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::RadioMedium::isInterferingTransmission(), and inet::physicallayer::CommunicationLog::writeReception().
getStartTime() [1/2]
virtual const simtime_t inet::physicallayer::IReception::getStartTime () const pure virtual
Returns the time when the receiver started to receive the corresponding transmission.
It is the start of the first bit's reception.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::ScalarAnalogModelBase::addReception(), inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::ReceiverBase::computeIsReceptionAttempted(), inet::physicallayer::FlatReceiverBase::computeIsReceptionPossible(), inet::physicallayer::ApskLayeredReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeIsReceptionPossible(), inet::physicallayer::UnitDiskReceiver::computeIsReceptionSuccessful(), inet::physicallayer::ScalarSnir::computeMax(), inet::physicallayer::DimensionalSnir::computeMax(), inet::physicallayer::DimensionalSnir::computeMean(), inet::physicallayer::ScalarSnir::computeMin(), inet::physicallayer::DimensionalSnir::computeMin(), inet::physicallayer::UnitDiskAnalogModel::computeNoise(), inet::physicallayer::DimensionalAnalogModelBase::computeNoise(), inet::physicallayer::ReceiverBase::computeReceptionResult(), inet::physicallayer::Ieee802154UwbIrReceiver::decode(), inet::physicallayer::RadioMedium::isInterferingTransmission(), and inet::physicallayer::CommunicationLog::writeReception().
getStartTime() [2/2]
virtual const simtime_t inet::physicallayer::IReception::getStartTime (IRadioSignal::SignalPart part) const pure virtual
Implemented in inet::physicallayer::ReceptionBase.
getTransmission()
virtual const ITransmission* inet::physicallayer::IReception::getTransmission () const pure virtual
Returns the transmission that corresponds to this reception at the receiver.
This function never returns nullptr.
Implemented in inet::physicallayer::ReceptionBase.
Referenced by inet::physicallayer::ApskErrorModel::computeBitErrorRate(), inet::physicallayer::ErrorModelBase::computeCorruptedPacket(), inet::physicallayer::RadioMedium::computeInterferingReceptions(), inet::physicallayer::ReceiverBase::computeIsReceptionAttempted(), inet::physicallayer::Ieee80211DimensionalReceiver::computeIsReceptionPossible(), inet::physicallayer::ApskScalarReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211ScalarReceiver::computeIsReceptionPossible(), inet::physicallayer::ApskDimensionalReceiver::computeIsReceptionPossible(), inet::physicallayer::Ieee80211UnitDiskReceiver::computeIsReceptionPossible(), inet::physicallayer::ApskErrorModel::computePacketErrorRate(), inet::physicallayer::Ieee80211BerTableErrorModel::computePacketErrorRate(), inet::physicallayer::StochasticErrorModel::computePacketErrorRate(), inet::physicallayer::Ieee80211ErrorModelBase::computePacketErrorRate(), inet::physicallayer::ReceiverBase::computeReceivedPacket(), inet::physicallayer::Ieee80211UnitDiskReceiver::computeReceptionResult(), inet::physicallayer::Ieee80211ReceiverBase::computeReceptionResult(), inet::physicallayer::ApskLayeredReceiver::computeReceptionResult(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::computeReceptionResult(), inet::physicallayer::ReceiverBase::computeSignalPower(), and inet::physicallayer::ApskErrorModel::computeSymbolErrorRate().
The documentation for this class was generated from the following file:
IReception.h