INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2Lsa Class Reference
inet::ospfv2::Ospfv2Lsa Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:107 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual Ospfv2Lsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv2Lsa &)=delete
Protected Attributes
Ospfv2LsaHeader header
Private Member Functions
void copy (const Ospfv2Lsa &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:107 by opp_msgtool.
//
// common ancestor type for all LSAs
//
class Ospfv2Lsa extends cObject
{
    @packetData;
    Ospfv2LsaHeader header;
}
Constructor & Destructor Documentation
Ospfv2Lsa() [1/2]
inet::ospfv2::Ospfv2Lsa::Ospfv2Lsa ()
Ospfv2Lsa() [2/2]
inet::ospfv2::Ospfv2Lsa::Ospfv2Lsa (const Ospfv2Lsa & other)
~Ospfv2Lsa()
virtual inet::ospfv2::Ospfv2Lsa::~Ospfv2Lsa () virtual
Member Function Documentation
copy()
void inet::ospfv2::Ospfv2Lsa::copy (const Ospfv2Lsa & other) private
dup()
virtual Ospfv2Lsa* inet::ospfv2::Ospfv2Lsa::dup () const inline override virtual
Reimplemented in inet::ospfv2::Ospfv2AsExternalLsa, inet::ospfv2::Ospfv2SummaryLsa, inet::ospfv2::Ospfv2NetworkLsa, and inet::ospfv2::Ospfv2RouterLsa.
 {return new Ospfv2Lsa(*this);}
Referenced by inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), and inet::ospfv2::Neighbor::retransmitUpdatePacket().
getHeader()
virtual const Ospfv2LsaHeader& inet::ospfv2::Ospfv2Lsa::getHeader () const virtual
Referenced by inet::ospfv2::Neighbor::addToRetransmissionList(), inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::calculateLSASize(), inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Ospfv2::checkExternalRoute(), inet::ospfv2::Neighbor::createDatabaseSummary(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), inet::ospfv2::RouterLsa::differsFrom(), inet::ospfv2::NetworkLsa::differsFrom(), inet::ospfv2::SummaryLsa::differsFrom(), inet::ospfv2::AsExternalLsa::differsFrom(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Router::floodLSA(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Ospfv2Area::hasLink(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Router::installLSA(), inet::ospfv2::Ospfv2Area::installNetworkLSA(), inet::ospfv2::Ospfv2Area::installRouterLSA(), inet::ospfv2::Ospfv2Area::installSummaryLSA(), inet::ospfv2::Router::isDestinationUnreachable(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Router::printAsExternalLsa(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), inet::ospfv2::Ospfv2Area::printLSDB(), inet::ospfv2::Ospfv2Area::printSummaryLsa(), inet::ospfv2::DatabaseDescriptionHandler::processDDPacket(), inet::ospfv2::LinkStateAcknowledgementHandler::processPacket(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::ospfv2::Ospfv2PacketSerializer::serializeLsa(), and inet::ospfv2::NeighborState::updateLsa().
getHeaderForUpdate()
virtual Ospfv2LsaHeader& inet::ospfv2::Ospfv2Lsa::getHeaderForUpdate () inline virtual
 { return const_cast<Ospfv2LsaHeader&>(const_cast<Ospfv2Lsa*>(this)->getHeader());}
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase(), inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Ospfv2InterfaceState::changeState(), inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Ospfv2Area::getUniqueLinkStateID(), inet::ospfv2::Router::getUniqueLinkStateID(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::Router::originateASExternalLSA(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), inet::ospfv2::HelloHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::setLsaCrc(), inet::ospfv2::Router::updateExternalRoute(), and inet::ospfv2::NeighborState::updateLsa().
operator=()
Ospfv2Lsa& inet::ospfv2::Ospfv2Lsa::operator= (const Ospfv2Lsa & other)
operator==()
bool inet::ospfv2::Ospfv2Lsa::operator== (const Ospfv2Lsa &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2Lsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::ospfv2::Ospfv2AsExternalLsa, inet::ospfv2::Ospfv2SummaryLsa, inet::ospfv2::Ospfv2NetworkLsa, and inet::ospfv2::Ospfv2RouterLsa.
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2Lsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::ospfv2::Ospfv2AsExternalLsa, inet::ospfv2::Ospfv2SummaryLsa, inet::ospfv2::Ospfv2NetworkLsa, and inet::ospfv2::Ospfv2RouterLsa.
Referenced by inet::ospfv2::doParsimUnpacking().
setHeader()
virtual void inet::ospfv2::Ospfv2Lsa::setHeader (const Ospfv2LsaHeader & header) virtual
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserializeLsa().
Member Data Documentation
header
Ospfv2LsaHeader inet::ospfv2::Ospfv2Lsa::header protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h