INET Framework for OMNeT++/OMNEST: inet::tcp::TcpLwipReceiveQueue Class Reference
inet::tcp::TcpLwipReceiveQueue Class Reference
TcpLwip receive queue.
#include <TcpLwipQueues.h>
Public Member Functions
TcpLwipReceiveQueue ()
virtual ~TcpLwipReceiveQueue ()
virtual void setConnection (TcpLwipConnection *connP)
Add a connection queue.
virtual void notifyAboutIncomingSegmentProcessing (Packet *packet, uint32_t seqNo, const void *bufferP, size_t bufferLengthP)
Called when a TCP segment arrives, it should extract the payload from the segment and store it in the receive queue.
virtual void enqueueTcpLayerData (void *dataP, unsigned int dataLengthP)
The method called when data received from LWIP The method should set status of the data in queue to received called after socket->read_data() successfull.
virtual unsigned long getExtractableBytesUpTo () const
virtual Packet * extractBytesUpTo ()
Should create a packet to be passed up to the app, up to (but NOT including) the given sequence no (usually rcv_nxt).
virtual uint32_t getAmountOfBufferedBytes () const
Returns the number of bytes (out-of-order-segments) currently buffered in queue.
virtual uint32_t getQueueLength () const
Returns the number of blocks currently buffered in queue.
virtual void getQueueStatus () const
Shows current queue status.
virtual void notifyAboutSending (const TcpHeader *tcpsegP)
notify the queue about output messages
Protected Attributes
TcpLwipConnection * connM = nullptr
ChunkQueue dataBuffer
Detailed Description
TcpLwip receive queue.
Constructor & Destructor Documentation
TcpLwipReceiveQueue()
inet::tcp::TcpLwipReceiveQueue::TcpLwipReceiveQueue ()
 {
 }
~TcpLwipReceiveQueue()
inet::tcp::TcpLwipReceiveQueue::~TcpLwipReceiveQueue () virtual
 {
     // nothing to do here
 }
Member Function Documentation
enqueueTcpLayerData()
void inet::tcp::TcpLwipReceiveQueue::enqueueTcpLayerData (void * dataP, unsigned int dataLengthP) virtual
The method called when data received from LWIP The method should set status of the data in queue to received called after socket->read_data() successfull.
 {
     dataBuffer.push(makeShared<BytesChunk>(static_cast<uint8_t *>(dataP), dataLengthP));
 }
Referenced by inet::tcp::TcpLwip::tcp_event_recv().
extractBytesUpTo()
Packet * inet::tcp::TcpLwipReceiveQueue::extractBytesUpTo () virtual
Should create a packet to be passed up to the app, up to (but NOT including) the given sequence no (usually rcv_nxt).
It should return nullptr if there's no more data to be passed up – this method is called several times until it returns nullptr.
called after socket->read_data() successfull
 {
     ASSERT(connM);
     Packet *dataMsg = nullptr;
     b queueLength = dataBuffer.getLength();
     if (queueLength > b(0)) {
         dataMsg = new Packet("DATA", TCP_I_DATA);
         const auto& data = dataBuffer.pop<Chunk>(queueLength);
         dataMsg->insertAtBack(data);
     }
     return dataMsg;
 }
Referenced by inet::tcp::TcpLwipConnection::sendUpData().
getAmountOfBufferedBytes()
uint32_t inet::tcp::TcpLwipReceiveQueue::getAmountOfBufferedBytes () const virtual
Returns the number of bytes (out-of-order-segments) currently buffered in queue.
 {
     return B(dataBuffer.getLength()).get();
 }
getExtractableBytesUpTo()
unsigned long inet::tcp::TcpLwipReceiveQueue::getExtractableBytesUpTo () const virtual
 {
     return B(dataBuffer.getLength()).get();
 }
getQueueLength()
uint32_t inet::tcp::TcpLwipReceiveQueue::getQueueLength () const virtual
Returns the number of blocks currently buffered in queue.
 {
     return B(dataBuffer.getLength()).get();
 }
getQueueStatus()
void inet::tcp::TcpLwipReceiveQueue::getQueueStatus () const virtual
Shows current queue status.
 {
     // TODO
 }
notifyAboutIncomingSegmentProcessing()
void inet::tcp::TcpLwipReceiveQueue::notifyAboutIncomingSegmentProcessing (Packet * packet, uint32_t seqNo, const void * bufferP, size_t bufferLengthP) virtual
Called when a TCP segment arrives, it should extract the payload from the segment and store it in the receive queue.
The segment object should not be deleted. //FIXME revise this comment
 {
     ASSERT(packet);
     ASSERT(bufferP);
 }
Referenced by inet::tcp::TcpLwip::notifyAboutIncomingSegmentProcessing().
notifyAboutSending()
void inet::tcp::TcpLwipReceiveQueue::notifyAboutSending (const TcpHeader * tcpsegP) virtual
notify the queue about output messages
called when connM send out a packet. for read AckNo, if have
 {
     // nothing to do
 }
Referenced by inet::tcp::TcpLwipConnection::notifyAboutSending().
setConnection()
void inet::tcp::TcpLwipReceiveQueue::setConnection (TcpLwipConnection * connP) virtual
Add a connection queue.
 {
     ASSERT(connP);
     ASSERT(connM == nullptr);
     dataBuffer.clear();
     connM = connP;
 }
Referenced by inet::tcp::TcpLwipConnection::initConnection().
Member Data Documentation
connM
TcpLwipConnection* inet::tcp::TcpLwipReceiveQueue::connM = nullptr protected
Referenced by extractBytesUpTo(), and setConnection().
dataBuffer
ChunkQueue inet::tcp::TcpLwipReceiveQueue::dataBuffer protected
Referenced by enqueueTcpLayerData(), extractBytesUpTo(), getAmountOfBufferedBytes(), getExtractableBytesUpTo(), getQueueLength(), and setConnection().
The documentation for this class was generated from the following files:
TcpLwipQueues.h
TcpLwipQueues.cc