INET Framework for OMNeT++/OMNEST: inet::sctp::SctpErrorChunk_Base Class Reference
inet::sctp::SctpErrorChunk_Base Class Reference abstract
Class generated from inet/transportlayer/sctp/SctpHeader.msg:220 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
virtual ~SctpErrorChunk_Base ()
virtual SctpErrorChunk_Base * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getTBit () const
virtual void setTBit (bool TBit)
virtual bool getMBit () const
virtual void setMBit (bool MBit)
virtual void setParametersArraySize (size_t size)=0
virtual size_t getParametersArraySize () const =0
virtual const SctpParameter * getParameters (size_t k) const =0
virtual SctpParameter * getParametersForUpdate (size_t k)
virtual void setParameters (size_t k, SctpParameter *parameters)=0
virtual void insertParameters (size_t k, SctpParameter *parameters)=0
void insertParameters (SctpParameter *parameters)
virtual void appendParameters (SctpParameter *parameters)=0
virtual void eraseParameters (size_t k)=0
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpErrorChunk_Base &)=delete
SctpErrorChunk_Base (const char *name=nullptr)
SctpErrorChunk_Base (const SctpErrorChunk_Base &other)
SctpErrorChunk_Base & operator= (const SctpErrorChunk_Base &other)
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
bool TBit = 0
bool MBit = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpErrorChunk_Base &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:220 by opp_msgtool.
class SctpErrorChunk extends SctpChunk
{
    @customize;
    bool TBit = 0;
    bool MBit = 0;
    abstract SctpParameter *parameters[];
}
SctpErrorChunk_Base is only useful if it gets subclassed, and SctpErrorChunk is derived from it. The minimum code to be written for SctpErrorChunk is the following:
class INET_API SctpErrorChunk : public SctpErrorChunk_Base
{
  private:
    void copy(const SctpErrorChunk& other) { ... }
  public:
    SctpErrorChunk(const char *name=nullptr) : SctpErrorChunk_Base(name) {}
    SctpErrorChunk(const SctpErrorChunk& other) : SctpErrorChunk_Base(other) {copy(other);}
    SctpErrorChunk& operator=(const SctpErrorChunk& other) {if (this==&other) return *this; SctpErrorChunk_Base::operator=(other); copy(other); return *this;}
    virtual SctpErrorChunk *dup() const override {return new SctpErrorChunk(*this);}
    // ADD CODE HERE to redefine and implement pure virtual functions from SctpErrorChunk_Base
};
The following should go into a .cc (.cpp) file:
Register_Class(SctpErrorChunk)
Constructor & Destructor Documentation
SctpErrorChunk_Base() [1/2]
inet::sctp::SctpErrorChunk_Base::SctpErrorChunk_Base (const char * name = nullptr) protected
SctpErrorChunk_Base() [2/2]
inet::sctp::SctpErrorChunk_Base::SctpErrorChunk_Base (const SctpErrorChunk_Base & other) protected
~SctpErrorChunk_Base()
virtual inet::sctp::SctpErrorChunk_Base::~SctpErrorChunk_Base () virtual
Member Function Documentation
appendParameters()
virtual void inet::sctp::SctpErrorChunk_Base::appendParameters (SctpParameter * parameters) pure virtual
Implemented in inet::sctp::SctpErrorChunk.
copy()
void inet::sctp::SctpErrorChunk_Base::copy (const SctpErrorChunk_Base & other) private
dup()
virtual SctpErrorChunk_Base* inet::sctp::SctpErrorChunk_Base::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
Reimplemented in inet::sctp::SctpErrorChunk.
 {throw omnetpp::cRuntimeError("You forgot to manually add a dup() function to class SctpErrorChunk");}
eraseParameters()
virtual void inet::sctp::SctpErrorChunk_Base::eraseParameters (size_t k) pure virtual
Implemented in inet::sctp::SctpErrorChunk.
getMBit()
virtual bool inet::sctp::SctpErrorChunk_Base::getMBit () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getParameters()
virtual const SctpParameter* inet::sctp::SctpErrorChunk_Base::getParameters (size_t k) const pure virtual
Implemented in inet::sctp::SctpErrorChunk.
getParametersArraySize()
virtual size_t inet::sctp::SctpErrorChunk_Base::getParametersArraySize () const pure virtual
Implemented in inet::sctp::SctpErrorChunk.
getParametersForUpdate()
virtual SctpParameter* inet::sctp::SctpErrorChunk_Base::getParametersForUpdate (size_t k) inline virtual
 { return const_cast<SctpParameter *>(const_cast<SctpErrorChunk_Base*>(this)->getParameters(k));}
getTBit()
virtual bool inet::sctp::SctpErrorChunk_Base::getTBit () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
insertParameters() [1/2]
void inet::sctp::SctpErrorChunk_Base::insertParameters (SctpParameter * parameters) inline
 {appendParameters(parameters);}
insertParameters() [2/2]
virtual void inet::sctp::SctpErrorChunk_Base::insertParameters (size_t k, SctpParameter * parameters) pure virtual
Implemented in inet::sctp::SctpErrorChunk.
operator=()
SctpErrorChunk_Base& inet::sctp::SctpErrorChunk_Base::operator= (const SctpErrorChunk_Base & other) protected
Referenced by inet::sctp::SctpErrorChunk::operator=().
operator==()
bool inet::sctp::SctpErrorChunk_Base::operator== (const SctpErrorChunk_Base &) protected delete
parsimPack()
virtual void inet::sctp::SctpErrorChunk_Base::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
parsimUnpack()
virtual void inet::sctp::SctpErrorChunk_Base::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
setMBit()
virtual void inet::sctp::SctpErrorChunk_Base::setMBit (bool MBit) virtual
Referenced by inet::sctp::SctpNatHook::sendBackError().
setParameters()
virtual void inet::sctp::SctpErrorChunk_Base::setParameters (size_t k, SctpParameter * parameters) pure virtual
Implemented in inet::sctp::SctpErrorChunk.
setParametersArraySize()
virtual void inet::sctp::SctpErrorChunk_Base::setParametersArraySize (size_t size) pure virtual
Implemented in inet::sctp::SctpErrorChunk.
setTBit()
virtual void inet::sctp::SctpErrorChunk_Base::setTBit (bool TBit) virtual
Referenced by inet::sctp::SctpNatHook::sendBackError().
Member Data Documentation
MBit
bool inet::sctp::SctpErrorChunk_Base::MBit = 0 protected
TBit
bool inet::sctp::SctpErrorChunk_Base::TBit = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h