INET Framework for OMNeT++/OMNEST: inet::ieee80211::QosRecoveryProcedure Class Reference
inet::ieee80211::QosRecoveryProcedure Class Reference
#include <QosRecoveryProcedure.h>
Public Member Functions
virtual void multicastFrameTransmitted ()
virtual void ctsFrameReceived ()
virtual void ackFrameReceived (Packet *packet, const Ptr< const Ieee80211DataHeader > &ackedHeader)
virtual void blockAckFrameReceived ()
virtual void rtsFrameTransmissionFailed (const Ptr< const Ieee80211DataHeader > &protectedHeader)
virtual void dataFrameTransmissionFailed (Packet *packet, const Ptr< const Ieee80211DataHeader > &failedHeader)
virtual bool isRetryLimitReached (Packet *packet, const Ptr< const Ieee80211DataHeader > &failedHeader)
virtual int getRetryCount (Packet *packet, const Ptr< const Ieee80211DataHeader > &header)
virtual bool isRtsFrameRetryLimitReached (Packet *packet, const Ptr< const Ieee80211DataHeader > &protectedHeader)
virtual void retryLimitReached (Packet *packet, const Ptr< const Ieee80211DataHeader > &header)
virtual int getLongRetryLimit ()
virtual int getShortRetryLimit ()
Public Member Functions inherited from inet::ieee80211::IRecoveryProcedure
virtual ~IRecoveryProcedure ()
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
void incrementCounter (const Ptr< const Ieee80211DataHeader > &header, std::map< std::pair< Tid, SequenceControlField >, int > &retryCounter)
void incrementStationSrc ()
void incrementStationLrc ()
void resetStationSrc ()
void resetStationLrc ()
void incrementContentionWindow ()
void resetContentionWindow ()
int doubleCw (int cw)
int getRc (Packet *packet, const Ptr< const Ieee80211DataHeader > &header, std::map< std::pair< Tid, SequenceControlField >, int > &retryCounter)
bool isMulticastFrame (Packet *packet, const Ptr< const Ieee80211MacHeader > &header)
Protected Attributes
ICwCalculator * cwCalculator = nullptr
std::map< std::pair< Tid, SequenceControlField >, int > shortRetryCounter
std::map< std::pair< Tid, SequenceControlField >, int > longRetryCounter
int stationLongRetryCounter = 0
int stationShortRetryCounter = 0
int shortRetryLimit = -1
int longRetryLimit = -1
int rtsThreshold = -1
Additional Inherited Members
Static Public Attributes inherited from inet::ieee80211::IRecoveryProcedure
static simsignal_t contentionWindowChangedSignal = cComponent::registerSignal("contentionWindowChanged")
static simsignal_t retryLimitReachedSignal = cComponent::registerSignal("retryLimitReached")
Member Function Documentation
ackFrameReceived()
void inet::ieee80211::QosRecoveryProcedure::ackFrameReceived (Packet * packet, const Ptr< const Ieee80211DataHeader > & ackedHeader) virtual
 {
     auto id = std::make_pair(ackedHeader->getTid(), SequenceControlField(ackedHeader->getSequenceNumber().get(), ackedHeader->getFragmentNumber()));
     if (packet->getByteLength() >= rtsThreshold) {
         resetStationLrc();
         auto it = longRetryCounter.find(id);
         if (it != longRetryCounter.end())
             longRetryCounter.erase(it);
     }
     else {
         auto it = shortRetryCounter.find(id);
         resetStationSrc();
         if (it != shortRetryCounter.end())
             shortRetryCounter.erase(it);
     }
     //
     // The CW shall be reset to aCWmin after every successful attempt to transmit a frame containing
     // all or part of an MSDU or MMPDU
     //
     resetContentionWindow();
 }
blockAckFrameReceived()
void inet::ieee80211::QosRecoveryProcedure::blockAckFrameReceived () virtual
 {
     resetStationSrc();
 }
ctsFrameReceived()
void inet::ieee80211::QosRecoveryProcedure::ctsFrameReceived () virtual
 {
     resetStationSrc();
 }
dataFrameTransmissionFailed()
void inet::ieee80211::QosRecoveryProcedure::dataFrameTransmissionFailed (Packet * packet, const Ptr< const Ieee80211DataHeader > & failedHeader) virtual
 {
     if (packet->getByteLength() >= rtsThreshold) {
         incrementStationLrc();
         incrementCounter(failedHeader, longRetryCounter);
     }
     else {
         incrementStationSrc();
         incrementCounter(failedHeader, shortRetryCounter);
     }
 }
doubleCw()
int inet::ieee80211::QosRecoveryProcedure::doubleCw (int cw) protected
getLongRetryLimit()
virtual int inet::ieee80211::QosRecoveryProcedure::getLongRetryLimit () inline virtual
 { return longRetryLimit; }
getRc()
int inet::ieee80211::QosRecoveryProcedure::getRc (Packet * packet, const Ptr< const Ieee80211DataHeader > & header, std::map< std::pair< Tid, SequenceControlField >, int > & retryCounter) protected
 {
     auto id = std::make_pair(header->getTid(), SequenceControlField(header->getSequenceNumber().get(), header->getFragmentNumber()));
     auto it = retryCounter.find(id);
     if (it != retryCounter.end())
         return it->second;
     else
         throw cRuntimeError("The retry counter entry doesn't exist for message id: %ld", packet->getId());
 }
Referenced by getRetryCount(), isRetryLimitReached(), and isRtsFrameRetryLimitReached().
getRetryCount()
int inet::ieee80211::QosRecoveryProcedure::getRetryCount (Packet * packet, const Ptr< const Ieee80211DataHeader > & header) virtual
 {
     if (packet->getByteLength() >= rtsThreshold)
         return getRc(packet, header, longRetryCounter);
     else
         return getRc(packet, header, shortRetryCounter);
 }
getShortRetryLimit()
virtual int inet::ieee80211::QosRecoveryProcedure::getShortRetryLimit () inline virtual
 { return shortRetryLimit; }
incrementContentionWindow()
void inet::ieee80211::QosRecoveryProcedure::incrementContentionWindow () protected
 {
     auto oldCw = cwCalculator->getCw();
     cwCalculator->incrementCw();
     auto newCw = cwCalculator->getCw();
     if (oldCw != newCw)
         emit(contentionWindowChangedSignal, cwCalculator->getCw());
 }
Referenced by incrementStationLrc(), and incrementStationSrc().
incrementCounter()
void inet::ieee80211::QosRecoveryProcedure::incrementCounter (const Ptr< const Ieee80211DataHeader > & header, std::map< std::pair< Tid, SequenceControlField >, int > & retryCounter) protected
 {
     auto id = std::make_pair((Tid)header->getTid(), SequenceControlField(header->getSequenceNumber().get(), header->getFragmentNumber()));
     if (containsKey(retryCounter, id))
         retryCounter[id]++;
     else
         retryCounter[id] = 1;
 }
Referenced by dataFrameTransmissionFailed(), and rtsFrameTransmissionFailed().
incrementStationLrc()
void inet::ieee80211::QosRecoveryProcedure::incrementStationLrc () protected
 {
     stationLongRetryCounter++;
     EV_INFO << "Incremented station LRC: stationLongRetryCounter = " << stationLongRetryCounter << ".\n";
     if (stationLongRetryCounter == longRetryLimit) // 9.3.3 Random backoff time
         resetContentionWindow();
     else
         incrementContentionWindow();
 }
Referenced by dataFrameTransmissionFailed().
incrementStationSrc()
void inet::ieee80211::QosRecoveryProcedure::incrementStationSrc () protected
 {
     stationShortRetryCounter++;
     EV_INFO << "Incremented station SRC: stationShortRetryCounter = " << stationShortRetryCounter << ".\n";
     if (stationShortRetryCounter == shortRetryLimit) // 9.3.3 Random backoff time
         resetContentionWindow();
     else
         incrementContentionWindow();
 }
Referenced by dataFrameTransmissionFailed(), and rtsFrameTransmissionFailed().
initialize()
void inet::ieee80211::QosRecoveryProcedure::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LAST) {
         auto rtsPolicy = check_and_cast<IRtsPolicy *>(getModuleByPath(par("rtsPolicyModule")));
         cwCalculator = check_and_cast<ICwCalculator *>(getModuleByPath(par("cwCalculatorModule")));
         rtsThreshold = rtsPolicy->getRtsThreshold();
         shortRetryLimit = par("shortRetryLimit");
         longRetryLimit = par("longRetryLimit");
         emit(contentionWindowChangedSignal, cwCalculator->getCw());
         WATCH(stationLongRetryCounter);
         WATCH(stationShortRetryCounter);
         WATCH_MAP(shortRetryCounter);
         WATCH_MAP(longRetryCounter);
     }
 }
isMulticastFrame()
bool inet::ieee80211::QosRecoveryProcedure::isMulticastFrame (Packet * packet, const Ptr< const Ieee80211MacHeader > & header) protected
 {
     if (auto oneAddressHeader = dynamicPtrCast<const Ieee80211OneAddressHeader>(header))
         return oneAddressHeader->getReceiverAddress().isMulticast();
     return false;
 }
isRetryLimitReached()
bool inet::ieee80211::QosRecoveryProcedure::isRetryLimitReached (Packet * packet, const Ptr< const Ieee80211DataHeader > & failedHeader) virtual
 {
     if (packet->getByteLength() >= rtsThreshold)
         return getRc(packet, failedHeader, longRetryCounter) >= longRetryLimit;
     else
         return getRc(packet, failedHeader, shortRetryCounter) >= shortRetryLimit;
 }
isRtsFrameRetryLimitReached()
bool inet::ieee80211::QosRecoveryProcedure::isRtsFrameRetryLimitReached (Packet * packet, const Ptr< const Ieee80211DataHeader > & protectedHeader) virtual
 {
     return getRc(packet, protectedHeader, shortRetryCounter) >= shortRetryLimit;
 }
multicastFrameTransmitted()
void inet::ieee80211::QosRecoveryProcedure::multicastFrameTransmitted () virtual
 {
     resetStationLrc();
     resetStationSrc();
 }
numInitStages()
virtual int inet::ieee80211::QosRecoveryProcedure::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
resetContentionWindow()
void inet::ieee80211::QosRecoveryProcedure::resetContentionWindow () protected
 {
     auto oldCw = cwCalculator->getCw();
     cwCalculator->resetCw();
     auto newCw = cwCalculator->getCw();
     if (oldCw != newCw)
         emit(contentionWindowChangedSignal, newCw);
 }
Referenced by ackFrameReceived(), incrementStationLrc(), and incrementStationSrc().
resetStationLrc()
void inet::ieee80211::QosRecoveryProcedure::resetStationLrc () inline protected
 { stationLongRetryCounter = 0; }
Referenced by ackFrameReceived(), and multicastFrameTransmitted().
resetStationSrc()
void inet::ieee80211::QosRecoveryProcedure::resetStationSrc () inline protected
 { stationShortRetryCounter = 0; }
Referenced by ackFrameReceived(), blockAckFrameReceived(), ctsFrameReceived(), and multicastFrameTransmitted().
retryLimitReached()
void inet::ieee80211::QosRecoveryProcedure::retryLimitReached (Packet * packet, const Ptr< const Ieee80211DataHeader > & header) virtual
 {
     EV_WARN << "Retry limit reached for " << *packet << ".\n";
     auto id = std::make_pair(header->getTid(), SequenceControlField(header->getSequenceNumber().get(), header->getFragmentNumber()));
     if (packet->getByteLength() >= rtsThreshold) {
         auto it = longRetryCounter.find(id);
         if (it != longRetryCounter.end())
             longRetryCounter.erase(it);
     }
     else {
         auto it = shortRetryCounter.find(id);
         if (it != shortRetryCounter.end())
             shortRetryCounter.erase(it);
     }
     emit(retryLimitReachedSignal, packet);
 }
rtsFrameTransmissionFailed()
void inet::ieee80211::QosRecoveryProcedure::rtsFrameTransmissionFailed (const Ptr< const Ieee80211DataHeader > & protectedHeader) virtual
 {
     incrementStationSrc();
     incrementCounter(protectedHeader, shortRetryCounter);
 }
Member Data Documentation
cwCalculator
ICwCalculator* inet::ieee80211::QosRecoveryProcedure::cwCalculator = nullptr protected
Referenced by incrementContentionWindow(), initialize(), and resetContentionWindow().
longRetryCounter
std::map<std::pair<Tid, SequenceControlField>, int> inet::ieee80211::QosRecoveryProcedure::longRetryCounter protected
Referenced by ackFrameReceived(), dataFrameTransmissionFailed(), getRetryCount(), initialize(), isRetryLimitReached(), and retryLimitReached().
longRetryLimit
int inet::ieee80211::QosRecoveryProcedure::longRetryLimit = -1 protected
Referenced by incrementStationLrc(), initialize(), and isRetryLimitReached().
rtsThreshold
int inet::ieee80211::QosRecoveryProcedure::rtsThreshold = -1 protected
Referenced by ackFrameReceived(), dataFrameTransmissionFailed(), getRetryCount(), initialize(), isRetryLimitReached(), and retryLimitReached().
shortRetryCounter
std::map<std::pair<Tid, SequenceControlField>, int> inet::ieee80211::QosRecoveryProcedure::shortRetryCounter protected
Referenced by ackFrameReceived(), dataFrameTransmissionFailed(), getRetryCount(), initialize(), isRetryLimitReached(), isRtsFrameRetryLimitReached(), retryLimitReached(), and rtsFrameTransmissionFailed().
shortRetryLimit
int inet::ieee80211::QosRecoveryProcedure::shortRetryLimit = -1 protected
Referenced by incrementStationSrc(), initialize(), isRetryLimitReached(), and isRtsFrameRetryLimitReached().
stationLongRetryCounter
int inet::ieee80211::QosRecoveryProcedure::stationLongRetryCounter = 0 protected
Referenced by incrementStationLrc(), and initialize().
stationShortRetryCounter
int inet::ieee80211::QosRecoveryProcedure::stationShortRetryCounter = 0 protected
Referenced by incrementStationSrc(), and initialize().
The documentation for this class was generated from the following files:
QosRecoveryProcedure.h
QosRecoveryProcedure.cc