INET Framework for OMNeT++/OMNEST: inet::physicallayer::ApskModulationBase Class Reference
inet::physicallayer::ApskModulationBase Class Reference
Base class for modulations using various amplitude and phase-shift keying.
#include <ApskModulationBase.h>
Public Member Functions
ApskModulationBase (const std::vector< ApskSymbol > *constellation)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const std::vector< ApskSymbol > * getConstellation () const
virtual unsigned int getConstellationSize () const override
virtual unsigned int getCodeWordSize () const override
virtual const ApskSymbol * mapToConstellationDiagram (const ShortBitVector &symbol) const
virtual ShortBitVector demapToBitRepresentation (const ApskSymbol *symbol) const
Public Member Functions inherited from inet::physicallayer::IModulation
virtual double calculateBER (double snir, Hz bandwidth, bps bitrate) const =0
Returns the bit error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
virtual double calculateSER (double snir, Hz bandwidth, bps bitrate) const =0
Returns the symbol error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Member Functions
const static ApskModulationBase * findModulation (const char *name)
Protected Attributes
const std::vector< ApskSymbol > * constellation
const unsigned int codeWordSize
const unsigned int constellationSize
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Base class for modulations using various amplitude and phase-shift keying.
Constructor & Destructor Documentation
ApskModulationBase()
inet::physicallayer::ApskModulationBase::ApskModulationBase (const std::vector< ApskSymbol > * constellation)
                                                                                  :
     constellation(constellation),
     codeWordSize(log2(constellation->size())),
     constellationSize(constellation->size())
 {
 }
Member Function Documentation
demapToBitRepresentation()
ShortBitVector inet::physicallayer::ApskModulationBase::demapToBitRepresentation (const ApskSymbol * symbol) const virtual
 {
     // TODO Complete implementation: http://eprints.soton.ac.uk/354719/1/tvt-hanzo-2272640-proof.pdf
     double symbolQ = symbol->real();
     double symbolI = symbol->imag();
     double minDist = DBL_MAX;
     int nearestNeighborIndex = -1;
     for (unsigned int i = 0; i < constellationSize; i++) {
         const ApskSymbol *constellationSymbol = &constellation->at(i);
         double cQ = constellationSymbol->real();
         double cI = constellationSymbol->imag();
         double dist = (symbolQ - cQ) * (symbolQ - cQ) + (symbolI - cI) * (symbolI - cI);
         if (dist < minDist) {
             minDist = dist;
             nearestNeighborIndex = i;
         }
     }
     ASSERT(nearestNeighborIndex != -1);
     return ShortBitVector(nearestNeighborIndex, codeWordSize);
 }
Referenced by inet::physicallayer::LayeredErrorModelBase::computeSymbolModel(), inet::physicallayer::ApskDemodulator::demodulate(), and inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol().
findModulation()
const ApskModulationBase * inet::physicallayer::ApskModulationBase::findModulation (const char * name) static
 {
     if (!strcmp("BPSK", modulation))
         return &BpskModulation::singleton;
     else if (!strcmp("QPSK", modulation))
         return &QpskModulation::singleton;
     else if (!strcmp("QAM-16", modulation))
         return &Qam16Modulation::singleton;
     else if (!strcmp("QAM-64", modulation))
         return &Qam64Modulation::singleton;
     else if (!strcmp("QAM-256", modulation))
         return &Qam256Modulation::singleton;
     else if (!strncmp("MQAM-", modulation, 5))
         // TODO avoid allocation
         return new MqamModulation(atoi(modulation + 5));
     else if (!strncmp("MPSK-", modulation, 5))
         // TODO avoid allocation
         return new MpskModulation(atoi(modulation + 5));
     else if (!strcmp(modulation, "DSSS-OQPSK-16"))
         return &DsssOqpsk16Modulation::singleton;
     else
         throw cRuntimeError("Unknown modulation = %s", modulation);
 }
Referenced by inet::physicallayer::Ieee80211OfdmModulatorModule::initialize(), inet::physicallayer::Ieee80211OfdmDemodulatorModule::initialize(), inet::physicallayer::NarrowbandTransmitterBase::initialize(), inet::physicallayer::NarrowbandReceiverBase::initialize(), inet::physicallayer::ApskDemodulator::initialize(), and inet::physicallayer::ApskModulator::initialize().
getCodeWordSize()
virtual unsigned int inet::physicallayer::ApskModulationBase::getCodeWordSize () const inline override virtual
Implements inet::physicallayer::IApskModulation.
 { return codeWordSize; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::calculatePadding(), inet::physicallayer::Ieee80211OfdmModeBase::computeGrossBitrate(), inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeNumberOfCodedBitsPerSubcarrierSum(), inet::physicallayer::Ieee80211VhtDataMode::computeNumberOfCodedBitsPerSubcarrierSum(), inet::physicallayer::ApskRadio::computePaddingLength(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211VhtCompliantCodes::getCompliantCode(), inet::physicallayer::Ieee80211HtCompliantCodes::getCompliantCode(), inet::physicallayer::Ieee80211OfdmDataMode::getDuration(), inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength(), inet::physicallayer::ApskModulator::modulate(), and inet::physicallayer::Ieee80211OfdmModulator::modulate().
getConstellation()
virtual const std::vector<ApskSymbol>* inet::physicallayer::ApskModulationBase::getConstellation () const inline virtual
 { return constellation; }
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::corruptOfdmSymbol().
getConstellationSize()
virtual unsigned int inet::physicallayer::ApskModulationBase::getConstellationSize () const inline override virtual
Implements inet::physicallayer::IApskModulation.
 { return constellationSize; }
mapToConstellationDiagram()
const ApskSymbol * inet::physicallayer::ApskModulationBase::mapToConstellationDiagram (const ShortBitVector & symbol) const virtual
 {
     unsigned int decimalSymbol = symbol.toDecimal();
     if (decimalSymbol >= constellationSize)
         throw cRuntimeError("Unknown input: %d", decimalSymbol);
     return &constellation->at(decimalSymbol);
 }
Referenced by inet::physicallayer::LayeredErrorModelBase::computeSymbolModel(), inet::physicallayer::ApskModulator::modulate(), and inet::physicallayer::Ieee80211OfdmModulator::modulate().
printToStream()
std::ostream & inet::physicallayer::ApskModulationBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::Qam1024Modulation, inet::physicallayer::Qam16Modulation, inet::physicallayer::Qam256Modulation, inet::physicallayer::Qam64Modulation, inet::physicallayer::BpskModulation, inet::physicallayer::QpskModulation, inet::physicallayer::MaskModulation, inet::physicallayer::MpskModulation, and inet::physicallayer::MqamModulation.
 {
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(constellationSize)
                << EV_FIELD(codeWordSize);
     return stream;
 }
Referenced by inet::physicallayer::MaskModulation::printToStream(), inet::physicallayer::MqamModulation::printToStream(), and inet::physicallayer::MpskModulation::printToStream().
Member Data Documentation
codeWordSize
const unsigned int inet::physicallayer::ApskModulationBase::codeWordSize protected
Referenced by inet::physicallayer::MpskModulation::calculateBER(), inet::physicallayer::MqamModulationBase::calculateBER(), demapToBitRepresentation(), and printToStream().
constellation
const std::vector<ApskSymbol>* inet::physicallayer::ApskModulationBase::constellation protected
Referenced by demapToBitRepresentation(), mapToConstellationDiagram(), inet::physicallayer::DsssOqpsk16Modulation::~DsssOqpsk16Modulation(), inet::physicallayer::MaskModulation::~MaskModulation(), inet::physicallayer::MpskModulation::~MpskModulation(), and inet::physicallayer::MqamModulation::~MqamModulation().
constellationSize
const unsigned int inet::physicallayer::ApskModulationBase::constellationSize protected
Referenced by inet::physicallayer::MpskModulation::calculateBER(), inet::physicallayer::MqamModulationBase::calculateBER(), inet::physicallayer::MqamModulationBase::calculateSER(), inet::physicallayer::MpskModulation::calculateSER(), demapToBitRepresentation(), mapToConstellationDiagram(), and printToStream().
The documentation for this class was generated from the following files:
ApskModulationBase.h
ApskModulationBase.cc