INET Framework for OMNeT++/OMNEST: inet::queueing::PacketFlowBase Class Reference
inet::queueing::PacketFlowBase Class Reference abstract
#include <PacketFlowBase.h>
Public Member Functions
virtual IPassivePacketSink * getConsumer (cGate *gate) override
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
virtual IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
virtual void handleCanPushPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
virtual void handlePushPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
virtual bool canPullSomePacket (cGate *gate) const override
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
virtual Packet * canPullPacket (cGate *gate) const override
Returns the packet that can be pulled at the given gate.
virtual Packet * pullPacket (cGate *gate) override
Pulls the packet from the packet source at the given gate.
virtual Packet * pullPacketStart (cGate *gate, bps datarate) override
Starts pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketEnd (cGate *gate) override
Ends pulling the packet from the packet source at the given gate.
virtual Packet * pullPacketProgress (cGate *gate, bps datarate, b position, b extraProcessableLength) override
Progresses pulling the packet from the packet source at the given gate.
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
virtual int getMaxNumPackets () const override
Returns maximum allowed number of packets in the collection.
virtual int getNumPackets () const override
Returns the number of available packets in the collection in the range [0, inf).
virtual b getMaxTotalLength () const override
Returns maximum allowed total length of all packets in the collection.
virtual b getTotalLength () const override
Returns the total length of all packets in the collection in the range [0, inf).
virtual Packet * getPacket (int index) const override
Returns the packet at the given index.
virtual bool isEmpty () const override
Returns true if there are no packets available in the collection.
virtual void removePacket (Packet *packet) override
Removes a packet from the collection.
virtual void removeAllPackets () override
Removes all packets from the collection.
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Public Member Functions inherited from inet::queueing::IPassivePacketSource
virtual ~IPassivePacketSource ()
Public Member Functions inherited from inet::queueing::IActivePacketSource
virtual ~IActivePacketSource ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void processPacket (Packet *packet)=0
virtual bool isStreamingPacket () const
virtual void startPacketStreaming (Packet *packet)
virtual void endPacketStreaming (Packet *packet)
virtual void checkPacketStreaming (Packet *packet)
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
cGate * inputGate = nullptr
ModuleRef< IActivePacketSource > producer
ModuleRef< IPassivePacketSource > provider
ModuleRef< IPacketCollection > collection
cGate * outputGate = nullptr
ModuleRef< IPassivePacketSink > consumer
ModuleRef< IActivePacketSink > collector
int inProgressStreamId = -1
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
canPullPacket()
Packet * inet::queueing::PacketFlowBase::canPullPacket (cGate * gate) const override virtual
Returns the packet that can be pulled at the given gate.
The returned value is nullptr if there is no such packet.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::PacketGateBase.
 {
     return provider->canPullPacket(inputGate->getPathStartGate());
 }
Referenced by inet::queueing::PacketGateBase::canPullPacket(), and inet::queueing::PacketGateBase::canPullSomePacket().
canPullSomePacket()
bool inet::queueing::PacketFlowBase::canPullSomePacket (cGate * gate) const override virtual
Returns false if the packet source is empty at the given gate and no more packets can be pulled from it without raising an error.
The gate must be a valid gate of this module and it must support pulling packets.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::queueing::PacketGateBase.
 {
     return provider->canPullSomePacket(inputGate->getPathStartGate());
 }
Referenced by inet::queueing::PacketGateBase::canPullSomePacket().
canPushPacket()
bool inet::queueing::PacketFlowBase::canPushPacket (Packet * packet, cGate * gate) const override virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::queueing::PacketGateBase, and inet::SendToMacAddress.
 {
     return consumer == nullptr || consumer->canPushPacket(packet, outputGate->getPathEndGate());
 }
Referenced by inet::queueing::PacketGateBase::canPushPacket().
canPushSomePacket()
bool inet::queueing::PacketFlowBase::canPushSomePacket (cGate * gate) const override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::queueing::PacketGateBase, and inet::SendToMacAddress.
 {
     return consumer == nullptr || consumer->canPushSomePacket(outputGate->getPathEndGate());
 }
Referenced by inet::queueing::PacketGateBase::canPushSomePacket().
checkPacketStreaming()
void inet::queueing::PacketFlowBase::checkPacketStreaming (Packet * packet) protected virtual
 {
     if (inProgressStreamId != -1 && (packet == nullptr || packet->getTreeId() != inProgressStreamId))
         throw cRuntimeError("Another packet streaming operation is already in progress");
 }
Referenced by pullPacket(), pullPacketEnd(), pullPacketProgress(), pullPacketStart(), pushPacket(), pushPacketEnd(), pushPacketProgress(), inet::physicallayer::EthernetPhyHeaderInserter::pushPacketStart(), inet::physicallayer::EthernetFragmentPhyHeaderInserter::pushPacketStart(), and pushPacketStart().
endPacketStreaming()
void inet::queueing::PacketFlowBase::endPacketStreaming (Packet * packet) protected virtual
 {
     handlePacketProcessed(packet);
     inProgressStreamId = -1;
 }
Referenced by handlePullPacketProcessed(), handlePushPacketProcessed(), pullPacketEnd(), pullPacketProgress(), pushPacketEnd(), and pushPacketProgress().
getConsumer()
virtual IPassivePacketSink* inet::queueing::PacketFlowBase::getConsumer (cGate * gate) inline override virtual
Returns the passive packet sink where packets are pushed or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
Reimplemented in inet::queueing::PacketGateBase, and inet::SendToMacAddress.
 { return this; }
getMaxNumPackets()
virtual int inet::queueing::PacketFlowBase::getMaxNumPackets () const inline override virtual
Returns maximum allowed number of packets in the collection.
The value -1 means no such limit.
Implements inet::queueing::IPacketCollection.
 { return collection->getMaxNumPackets(); }
getMaxTotalLength()
virtual b inet::queueing::PacketFlowBase::getMaxTotalLength () const inline override virtual
Returns maximum allowed total length of all packets in the collection.
The value -1 means no such limit.
Implements inet::queueing::IPacketCollection.
 { return collection->getMaxTotalLength(); }
getNumPackets()
virtual int inet::queueing::PacketFlowBase::getNumPackets () const inline override virtual
Returns the number of available packets in the collection in the range [0, inf).
Implements inet::queueing::IPacketCollection.
 { return collection->getNumPackets(); }
getPacket()
virtual Packet* inet::queueing::PacketFlowBase::getPacket (int index) const inline override virtual
Returns the packet at the given index.
Throws error when the index is out of range.
Implements inet::queueing::IPacketCollection.
 { return collection->getPacket(index); }
getProvider()
virtual IPassivePacketSource* inet::queueing::PacketFlowBase::getProvider (cGate * gate) inline override virtual
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
Reimplemented in inet::queueing::PacketGateBase.
 { return this; }
getTotalLength()
virtual b inet::queueing::PacketFlowBase::getTotalLength () const inline override virtual
Returns the total length of all packets in the collection in the range [0, inf).
Implements inet::queueing::IPacketCollection.
 { return collection->getTotalLength(); }
handleCanPullPacketChanged()
void inet::queueing::PacketFlowBase::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
Reimplemented in inet::queueing::PacketGateBase, inet::queueing::CreditBasedGate, and inet::EligibilityTimeGate.
 {
     Enter_Method("handleCanPullPacketChanged");
     if (collector != nullptr)
         collector->handleCanPullPacketChanged(outputGate->getPathEndGate());
 }
Referenced by inet::queueing::PacketGateBase::handleCanPullPacketChanged().
handleCanPushPacketChanged()
void inet::queueing::PacketFlowBase::handleCanPushPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pushing some packet into the passive packet sink at the given gate.
This method is called, for example, when a new packet can be inserted into a queue. It allows the source to push a new packet into the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSource.
Reimplemented in inet::queueing::PacketGateBase, and inet::SendToMacAddress.
 {
     Enter_Method("handleCanPushPacketChanged");
     if (producer != nullptr)
         producer->handleCanPushPacketChanged(inputGate->getPathStartGate());
 }
Referenced by inet::queueing::PacketGateBase::handleCanPushPacketChanged().
handleMessage()
void inet::queueing::PacketFlowBase::handleMessage (cMessage * message) override protected virtual
Reimplemented in inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::queueing::CreditBasedGate, inet::EligibilityTimeGate, inet::queueing::PeriodicGate, inet::SendWithAcknowledge, inet::queueing::PacketGate, inet::EthernetSocketCommandProcessor, inet::Ieee8021qSocketCommandProcessor, and inet::Ieee8022LlcSocketCommandProcessor.
 {
     auto packet = check_and_cast<Packet *>(message);
     pushPacket(packet, packet->getArrivalGate());
 }
Referenced by inet::EthernetSocketCommandProcessor::handleMessage(), inet::Ieee8021qSocketCommandProcessor::handleMessage(), inet::Ieee8022LlcSocketCommandProcessor::handleMessage(), and inet::SendToMacAddress::pushPacket().
handlePullPacketProcessed()
void inet::queueing::PacketFlowBase::handlePullPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pulled packet is failed to be processed successfully. It allows the sink to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handlePullPacketProcessed");
     endPacketStreaming(packet);
     if (collector != nullptr)
         collector->handlePullPacketProcessed(packet, outputGate->getPathStartGate(), successful);
 }
handlePushPacketProcessed()
void inet::queueing::PacketFlowBase::handlePushPacketProcessed (Packet * packet, cGate * gate, bool successful) override virtual
Notifies about the completion of the packet processing for a packet that was pushed earlier independently whether the packet is passed or streamed.
This method is called, for example, when a previously pushed packet is failed to be processed successfully. It allows the source to retry the operation.
The gate parameter must be a valid gate of this module. The packet must not be nullptr.
Implements inet::queueing::IActivePacketSource.
Reimplemented in inet::PacketEmitter, and inet::SendToMacAddress.
 {
     Enter_Method("handlePushPacketProcessed");
     endPacketStreaming(packet);
     if (producer != nullptr)
         producer->handlePushPacketProcessed(packet, inputGate->getPathStartGate(), successful);
 }
Referenced by inet::PacketEmitter::handlePushPacketProcessed().
initialize()
void inet::queueing::PacketFlowBase::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
Reimplemented in inet::StreamDecoder, inet::queueing::CreditBasedGate, inet::queueing::FlowMeasurementRecorder, inet::queueing::MultiTokenBucketMixin< PacketMeterBase >, inet::queueing::PacketGateBase, inet::queueing::FlowMeasurementStarter, inet::StreamEncoder, inet::EligibilityTimeGate, inet::PacketEmitter, inet::queueing::PacketTaggerBase, inet::queueing::PeriodicGate, inet::RelayInterfaceLearner, inet::Ieee8021qTagEpdHeaderInserter, inet::Ieee8021qTagTpidHeaderInserter, inet::queueing::SlidingWindowRateMeter, inet::queueing::TokenBucketMixin< PacketMeterBase >, inet::VlanReqMapper, inet::StreamIdentifier, inet::queueing::ExponentialRateMeter, inet::queueing::TokenBucketMeterMixin< MultiTokenBucketMixin< PacketMeterBase > >, inet::queueing::TokenBucketMeterMixin< TokenBucketMixin< PacketMeterBase > >, inet::SendWithAcknowledge, inet::PaddingInserter, inet::queueing::PacketGate, inet::EthernetAddressInserter, inet::EthernetMacHeaderInserter, inet::EthernetSocketCommandProcessor, inet::Ieee8021qSocketCommandProcessor, inet::Ieee8022LlcSocketCommandProcessor, inet::Ieee8021rTagEpdHeaderInserter, inet::CrcInserterBase, inet::FcsInserterBase, inet::CrcHeaderInserter, inet::FcsHeaderInserter, inet::FragmentNumberHeaderChecker, inet::FragmentNumberHeaderInserter, inet::SendToL3Address, inet::SendToMacAddress, inet::queueing::MultiTokenBucketMeter, inet::queueing::TokenBucketMeter, inet::Ieee8022SnapInserter, inet::SendWithHopLimit, inet::SendToPort, inet::queueing::PacketLabelerBase, inet::queueing::ContentBasedLabeler, inet::queueing::ContentBasedTagger, inet::queueing::PacketLabeler, inet::queueing::PacketTagger, inet::Ieee8022LlcInserter, inet::PacketDirectionReverser, inet::EthernetTypeOrLengthInserter, inet::Ieee8021aeTagEpdHeaderInserter, and inet::queueing::InteractiveGate.
 {
     PacketProcessorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         inputGate = gate("in");
         outputGate = gate("out");
         producer.reference(inputGate, false);
         consumer.reference(outputGate, false);
         provider.reference(inputGate, false);
         collector.reference(outputGate, false);
         collection.reference(inputGate, false);
     }
     else if (stage == INITSTAGE_QUEUEING) {
         checkPacketOperationSupport(inputGate);
         checkPacketOperationSupport(outputGate);
     }
 }
Referenced by inet::EthernetTypeOrLengthInserter::initialize(), inet::PacketDirectionReverser::initialize(), inet::Ieee8021aeTagEpdHeaderInserter::initialize(), inet::Ieee8022LlcInserter::initialize(), inet::Ieee8022SnapInserter::initialize(), inet::queueing::PacketLabelerBase::initialize(), inet::SendToPort::initialize(), inet::SendWithHopLimit::initialize(), inet::Ieee8021rTagEpdHeaderInserter::initialize(), inet::CrcInserterBase::initialize(), inet::FragmentNumberHeaderChecker::initialize(), inet::FragmentNumberHeaderInserter::initialize(), inet::FcsInserterBase::initialize(), inet::SendToL3Address::initialize(), inet::SendToMacAddress::initialize(), inet::EthernetSocketCommandProcessor::initialize(), inet::Ieee8022LlcSocketCommandProcessor::initialize(), inet::EthernetAddressInserter::initialize(), inet::Ieee8021qSocketCommandProcessor::initialize(), inet::EthernetMacHeaderInserter::initialize(), inet::PaddingInserter::initialize(), inet::SendWithAcknowledge::initialize(), inet::StreamIdentifier::initialize(), inet::VlanReqMapper::initialize(), inet::queueing::ExponentialRateMeter::initialize(), inet::queueing::SlidingWindowRateMeter::initialize(), inet::Ieee8021qTagEpdHeaderInserter::initialize(), inet::RelayInterfaceLearner::initialize(), inet::Ieee8021qTagTpidHeaderInserter::initialize(), inet::PacketEmitter::initialize(), inet::queueing::PacketTaggerBase::initialize(), inet::StreamEncoder::initialize(), inet::queueing::FlowMeasurementStarter::initialize(), inet::queueing::PacketGateBase::initialize(), inet::queueing::FlowMeasurementRecorder::initialize(), and inet::StreamDecoder::initialize().
isEmpty()
virtual bool inet::queueing::PacketFlowBase::isEmpty () const inline override virtual
Returns true if there are no packets available in the collection.
Implements inet::queueing::IPacketCollection.
 { return collection->isEmpty(); }
isStreamingPacket()
virtual bool inet::queueing::PacketFlowBase::isStreamingPacket () const inline protected virtual
 { return inProgressStreamId != -1; }
Referenced by pushPacketEnd(), and pushPacketProgress().
processPacket()
virtual void inet::queueing::PacketFlowBase::processPacket (Packet * packet) protected pure virtual
Implemented in inet::queueing::FlowMeasurementRecorder, inet::queueing::FlowMeasurementStarter, inet::queueing::CreditBasedGate, inet::StreamDecoder, inet::queueing::PacketGateBase, inet::StreamEncoder, inet::RelayInterfaceLearner, inet::PacketEmitter, inet::Ieee8021qTagEpdHeaderInserter, inet::Ieee8021qTagTpidHeaderInserter, inet::PaddingInserter, inet::StreamIdentifier, inet::EthernetSocketCommandProcessor, inet::Ieee8021qSocketCommandProcessor, inet::Ieee8022LlcSocketCommandProcessor, inet::VlanReqMapper, inet::SendWithAcknowledge, inet::FragmentNumberHeaderChecker, inet::EthernetAddressInserter, inet::EthernetFragmentFcsInserter, inet::EthernetMacHeaderInserter, inet::physicallayer::EthernetFragmentPhyHeaderInserter, inet::Ieee8021rTagEpdHeaderInserter, inet::CrcHeaderInserter, inet::FcsHeaderInserter, inet::FragmentNumberHeaderInserter, inet::SendToL3Address, inet::SendToMacAddress, inet::Ieee8022SnapInserter, inet::SendWithHopLimit, inet::SendToPort, inet::Ieee8022LlcInserter, inet::SequenceNumbering, inet::queueing::PacketMeterBase, inet::physicallayer::EthernetPhyHeaderInserter, inet::PacketDirectionReverser, inet::EthernetFcsInserter, inet::EthernetTypeOrLengthInserter, inet::Ieee8021aeTagEpdHeaderInserter, inet::SendWithProtocol, inet::PacketDeserializer, inet::PacketSerializer, and inet::queueing::PacketMarkerBase.
Referenced by pullPacket(), pullPacketEnd(), pullPacketProgress(), pullPacketStart(), pushPacket(), pushPacketEnd(), pushPacketProgress(), and pushPacketStart().
pullPacket()
Packet * inet::queueing::PacketFlowBase::pullPacket (cGate * gate) override virtual
Pulls the packet from the packet source at the given gate.
This operation pulls the packet as a whole. The onwership of the packet is transferred to the sink.
The source must not be empty at the given gate. The returned packet must not be nullptr. The gate must be a valid gate of this module and it must support pulling and passing packets.
Implements inet::queueing::IPassivePacketSource.
Reimplemented in inet::EligibilityTimeGate.
 {
     Enter_Method("pullPacket");
     checkPacketStreaming(nullptr);
     auto packet = provider->pullPacket(inputGate->getPathStartGate());
     take(packet);
     emit(packetPulledInSignal, packet);
     processPacket(packet);
     handlePacketProcessed(packet);
     emit(packetPulledOutSignal, packet);
     animatePullPacket(packet, outputGate);
     updateDisplayString();
     return packet;
 }
Referenced by inet::EligibilityTimeGate::pullPacket().
pullPacketEnd()
Packet * inet::queueing::PacketFlowBase::pullPacketEnd (cGate * gate) override virtual
Ends pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet from the the source.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacketEnd");
     auto packet = provider->pullPacketEnd(inputGate->getPathStartGate());
     take(packet);
     checkPacketStreaming(packet);
     emit(packetPulledInSignal, packet);
     processPacket(packet);
     inProgressStreamId = packet->getTreeId();
     emit(packetPulledOutSignal, packet);
     endPacketStreaming(packet);
     animatePullPacketEnd(packet, outputGate, packet->getTransmissionId());
     updateDisplayString();
     return packet;
 }
pullPacketProgress()
Packet * inet::queueing::PacketFlowBase::pullPacketProgress (cGate * gate, bps datarate, b position, b extraProcessableLength) override virtual
Progresses pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the source about a change in the packet data when a preemption occurs.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacketProgress");
     auto packet = provider->pullPacketProgress(inputGate->getPathStartGate(), datarate, position, extraProcessableLength);
     take(packet);
     checkPacketStreaming(packet);
     inProgressStreamId = packet->getTreeId();
     bool isPacketEnd = packet->getTotalLength() == position + extraProcessableLength;
     processPacket(packet);
     if (isPacketEnd) {
         emit(packetPulledOutSignal, packet);
         endPacketStreaming(packet);
     }
     animatePullPacketProgress(packet, outputGate, datarate, position, extraProcessableLength, packet->getTransmissionId());
     updateDisplayString();
     return packet;
 }
pullPacketStart()
Packet * inet::queueing::PacketFlowBase::pullPacketStart (cGate * gate, bps datarate) override virtual
Starts pulling the packet from the packet source at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet from the source.
The source must not be empty at the gate and no other packet streaming can be in progress. The gate must be a valid gate of this module and it must support pulling and streaming packets. The returned packet must not be nullptr.
Implements inet::queueing::IPassivePacketSource.
 {
     Enter_Method("pullPacketStart");
     checkPacketStreaming(nullptr);
     auto packet = provider->pullPacketStart(inputGate->getPathStartGate(), datarate);
     take(packet);
     emit(packetPulledInSignal, packet);
     inProgressStreamId = packet->getTreeId();
     processPacket(packet);
     emit(packetPulledOutSignal, packet);
     animatePullPacketStart(packet, outputGate, datarate, packet->getTransmissionId());
     updateDisplayString();
     return packet;
 }
pushPacket()
void inet::queueing::PacketFlowBase::pushPacket (Packet * packet, cGate * gate) override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::PacketEmitter, and inet::SendToMacAddress.
 {
     Enter_Method("pushPacket");
     take(packet);
     checkPacketStreaming(nullptr);
     emit(packetPushedInSignal, packet);
     processPacket(packet);
     handlePacketProcessed(packet);
     emit(packetPushedOutSignal, packet);
     pushOrSendPacket(packet, outputGate, consumer);
     updateDisplayString();
 }
Referenced by handleMessage(), and inet::PacketEmitter::pushPacket().
pushPacketEnd()
void inet::queueing::PacketFlowBase::pushPacketEnd (Packet * packet, cGate * gate) override virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::PacketEmitter.
 {
     Enter_Method("pushPacketEnd");
     take(packet);
     if (!isStreamingPacket())
         startPacketStreaming(packet);
     else
         checkPacketStreaming(packet);
     processPacket(packet);
     emit(packetPushedOutSignal, packet);
     endPacketStreaming(packet);
     pushOrSendPacketEnd(packet, outputGate, consumer, packet->getTransmissionId());
     updateDisplayString();
 }
Referenced by inet::PacketEmitter::pushPacketEnd().
pushPacketProgress()
void inet::queueing::PacketFlowBase::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) override virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacketProgress");
     take(packet);
     if (!isStreamingPacket())
         startPacketStreaming(packet);
     else
         checkPacketStreaming(packet);
     bool isPacketEnd = packet->getTotalLength() == position + extraProcessableLength;
     processPacket(packet);
     if (isPacketEnd) {
         emit(packetPushedOutSignal, packet);
         endPacketStreaming(packet);
         pushOrSendPacketEnd(packet, outputGate, consumer, packet->getTransmissionId());
     }
     else
         pushOrSendPacketProgress(packet, outputGate, consumer, datarate, position, extraProcessableLength, packet->getTransmissionId());
     updateDisplayString();
 }
pushPacketStart()
void inet::queueing::PacketFlowBase::pushPacketStart (Packet * packet, cGate * gate, bps datarate) override virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::physicallayer::EthernetFragmentPhyHeaderInserter, and inet::physicallayer::EthernetPhyHeaderInserter.
 {
     Enter_Method("pushPacketStart");
     take(packet);
     checkPacketStreaming(packet);
     emit(packetPushedInSignal, packet);
     startPacketStreaming(packet);
     processPacket(packet);
     pushOrSendPacketStart(packet, outputGate, consumer, datarate, packet->getTransmissionId());
     updateDisplayString();
 }
removeAllPackets()
virtual void inet::queueing::PacketFlowBase::removeAllPackets () inline override virtual
Removes all packets from the collection.
Implements inet::queueing::IPacketCollection.
 { collection->removeAllPackets(); }
removePacket()
virtual void inet::queueing::PacketFlowBase::removePacket (Packet * packet) inline override virtual
Removes a packet from the collection.
The collection must contain the packet.
Implements inet::queueing::IPacketCollection.
 { collection->removePacket(packet); }
startPacketStreaming()
void inet::queueing::PacketFlowBase::startPacketStreaming (Packet * packet) protected virtual
 {
     inProgressStreamId = packet->getTreeId();
 }
Referenced by pushPacketEnd(), pushPacketProgress(), inet::physicallayer::EthernetPhyHeaderInserter::pushPacketStart(), inet::physicallayer::EthernetFragmentPhyHeaderInserter::pushPacketStart(), and pushPacketStart().
supportsPacketPulling()
virtual bool inet::queueing::PacketFlowBase::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::queueing::PacketGateBase.
 { return true; }
supportsPacketPushing()
virtual bool inet::queueing::PacketFlowBase::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
Reimplemented in inet::queueing::PacketGateBase.
 { return true; }
supportsPacketStreaming()
virtual bool inet::queueing::PacketFlowBase::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return true; }
Member Data Documentation
collection
ModuleRef<IPacketCollection> inet::queueing::PacketFlowBase::collection protected
Referenced by initialize().
collector
ModuleRef<IActivePacketSink> inet::queueing::PacketFlowBase::collector protected
Referenced by inet::queueing::PacketGateBase::close(), handleCanPullPacketChanged(), handlePullPacketProcessed(), initialize(), and inet::queueing::PacketGateBase::open().
consumer
ModuleRef<IPassivePacketSink> inet::queueing::PacketFlowBase::consumer protected
Referenced by canPushPacket(), canPushSomePacket(), initialize(), inet::SendWithHopLimit::processPacket(), pushPacket(), pushPacketEnd(), pushPacketProgress(), inet::physicallayer::EthernetPhyHeaderInserter::pushPacketStart(), inet::physicallayer::EthernetFragmentPhyHeaderInserter::pushPacketStart(), and pushPacketStart().
inProgressStreamId
int inet::queueing::PacketFlowBase::inProgressStreamId = -1 protected
Referenced by checkPacketStreaming(), endPacketStreaming(), pullPacketEnd(), pullPacketProgress(), pullPacketStart(), and startPacketStreaming().
inputGate
cGate* inet::queueing::PacketFlowBase::inputGate = nullptr protected
Referenced by canPullPacket(), canPullSomePacket(), inet::queueing::PacketGateBase::close(), inet::EligibilityTimeGate::emitEligibilityTimeChangedSignal(), inet::queueing::PacketMeterBase::getRegistrationForwardingGate(), inet::VlanReqMapper::getRegistrationForwardingGate(), inet::EthernetSocketCommandProcessor::getRegistrationForwardingGate(), inet::Ieee8021qSocketCommandProcessor::getRegistrationForwardingGate(), inet::Ieee8022LlcSocketCommandProcessor::getRegistrationForwardingGate(), inet::StreamIdentifier::getRegistrationForwardingGate(), inet::RelayInterfaceLearner::getRegistrationForwardingGate(), inet::queueing::PacketGateBase::getRegistrationForwardingGate(), inet::StreamEncoder::getRegistrationForwardingGate(), inet::StreamDecoder::getRegistrationForwardingGate(), inet::SendToMacAddress::handleCanPushPacketChanged(), handleCanPushPacketChanged(), inet::SendWithAcknowledge::handleMessage(), handlePushPacketProcessed(), inet::SendWithProtocol::handleRegisterService(), inet::PacketDirectionReverser::initialize(), inet::Ieee8021aeTagEpdHeaderInserter::initialize(), inet::EthernetTypeOrLengthInserter::initialize(), inet::Ieee8022LlcInserter::initialize(), inet::SendToPort::initialize(), inet::SendWithHopLimit::initialize(), inet::Ieee8022SnapInserter::initialize(), inet::SendToL3Address::initialize(), inet::FragmentNumberHeaderChecker::initialize(), inet::Ieee8021rTagEpdHeaderInserter::initialize(), inet::SendToMacAddress::initialize(), inet::CrcHeaderInserter::initialize(), inet::FcsHeaderInserter::initialize(), inet::EthernetMacHeaderInserter::initialize(), inet::SendWithAcknowledge::initialize(), inet::Ieee8021qTagEpdHeaderInserter::initialize(), initialize(), inet::queueing::PacketGateBase::open(), inet::SendWithAcknowledge::processPacket(), pullPacket(), pullPacketEnd(), pullPacketProgress(), pullPacketStart(), and inet::EligibilityTimeGate::updateOpen().
outputGate
cGate* inet::queueing::PacketFlowBase::outputGate = nullptr protected
Referenced by canPushPacket(), canPushSomePacket(), inet::queueing::PacketGateBase::close(), inet::queueing::PacketMeterBase::getRegistrationForwardingGate(), inet::Ieee8022LlcSocketCommandProcessor::getRegistrationForwardingGate(), inet::VlanReqMapper::getRegistrationForwardingGate(), inet::Ieee8021qSocketCommandProcessor::getRegistrationForwardingGate(), inet::EthernetSocketCommandProcessor::getRegistrationForwardingGate(), inet::StreamIdentifier::getRegistrationForwardingGate(), inet::RelayInterfaceLearner::getRegistrationForwardingGate(), inet::queueing::PacketGateBase::getRegistrationForwardingGate(), inet::StreamEncoder::getRegistrationForwardingGate(), inet::StreamDecoder::getRegistrationForwardingGate(), handleCanPullPacketChanged(), handlePullPacketProcessed(), inet::SendWithProtocol::handleRegisterProtocol(), inet::PacketDirectionReverser::initialize(), inet::Ieee8022LlcInserter::initialize(), inet::SendToPort::initialize(), inet::SendWithHopLimit::initialize(), inet::Ieee8022SnapInserter::initialize(), inet::CrcHeaderInserter::initialize(), inet::FcsHeaderInserter::initialize(), inet::SendToMacAddress::initialize(), inet::FragmentNumberHeaderChecker::initialize(), inet::SendToL3Address::initialize(), inet::SendWithAcknowledge::initialize(), initialize(), inet::queueing::PacketGateBase::open(), inet::SendWithHopLimit::processPacket(), pullPacket(), pullPacketEnd(), pullPacketProgress(), pullPacketStart(), pushPacket(), pushPacketEnd(), pushPacketProgress(), inet::physicallayer::EthernetPhyHeaderInserter::pushPacketStart(), inet::physicallayer::EthernetFragmentPhyHeaderInserter::pushPacketStart(), and pushPacketStart().
producer
ModuleRef<IActivePacketSource> inet::queueing::PacketFlowBase::producer protected
Referenced by inet::queueing::PacketGateBase::close(), inet::SendToMacAddress::handleCanPushPacketChanged(), handleCanPushPacketChanged(), inet::SendWithAcknowledge::handleMessage(), inet::SendToMacAddress::handlePushPacketProcessed(), handlePushPacketProcessed(), initialize(), inet::queueing::PacketGateBase::open(), and inet::SendWithAcknowledge::processPacket().
provider
ModuleRef<IPassivePacketSource> inet::queueing::PacketFlowBase::provider protected
Referenced by canPullPacket(), canPullSomePacket(), inet::EligibilityTimeGate::emitEligibilityTimeChangedSignal(), initialize(), pullPacket(), pullPacketEnd(), pullPacketProgress(), pullPacketStart(), and inet::EligibilityTimeGate::updateOpen().
The documentation for this class was generated from the following files:
PacketFlowBase.h
PacketFlowBase.cc