INET Framework for OMNeT++/OMNEST: inet::sctp::SctpIncomingSsnResetRequestParameter Class Reference
inet::sctp::SctpIncomingSsnResetRequestParameter Class Reference
#include <SctpHeader.h>
Public Member Functions
SctpIncomingSsnResetRequestParameter (const char *name=nullptr, int kind=0)
SctpIncomingSsnResetRequestParameter (const SctpIncomingSsnResetRequestParameter &other)
SctpIncomingSsnResetRequestParameter & operator= (const SctpIncomingSsnResetRequestParameter &other)
virtual SctpIncomingSsnResetRequestParameter * dup () const override
Public Member Functions inherited from inet::sctp::SctpIncomingSsnResetRequestParameter_Base
virtual ~SctpIncomingSsnResetRequestParameter_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSrReqSn () const
virtual void setSrReqSn (uint32_t srReqSn)
virtual void setStreamNumbersArraySize (size_t size)
virtual size_t getStreamNumbersArraySize () const
virtual uint16_t getStreamNumbers (size_t k) const
virtual void setStreamNumbers (size_t k, uint16_t streamNumbers)
virtual void insertStreamNumbers (size_t k, uint16_t streamNumbers)
void insertStreamNumbers (uint16_t streamNumbers)
virtual void appendStreamNumbers (uint16_t streamNumbers)
virtual void eraseStreamNumbers (size_t k)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Private Member Functions
void copy (const SctpIncomingSsnResetRequestParameter &other)
Additional Inherited Members
Protected Member Functions inherited from inet::sctp::SctpIncomingSsnResetRequestParameter_Base
bool operator== (const SctpIncomingSsnResetRequestParameter_Base &)=delete
SctpIncomingSsnResetRequestParameter_Base (const char *name=nullptr)
SctpIncomingSsnResetRequestParameter_Base (const SctpIncomingSsnResetRequestParameter_Base &other)
SctpIncomingSsnResetRequestParameter_Base & operator= (const SctpIncomingSsnResetRequestParameter_Base &other)
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes inherited from inet::sctp::SctpIncomingSsnResetRequestParameter_Base
uint32_t srReqSn = 0
uint16_t * streamNumbers = nullptr
size_t streamNumbers_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Constructor & Destructor Documentation
SctpIncomingSsnResetRequestParameter() [1/2]
inet::sctp::SctpIncomingSsnResetRequestParameter::SctpIncomingSsnResetRequestParameter (const char * name = nullptr, int kind = 0) inline
 : SctpIncomingSsnResetRequestParameter_Base() {}
Referenced by dup().
SctpIncomingSsnResetRequestParameter() [2/2]
inet::sctp::SctpIncomingSsnResetRequestParameter::SctpIncomingSsnResetRequestParameter (const SctpIncomingSsnResetRequestParameter & other) inline
 : SctpIncomingSsnResetRequestParameter_Base(other) { copy(other); }
Member Function Documentation
copy()
void inet::sctp::SctpIncomingSsnResetRequestParameter::copy (const SctpIncomingSsnResetRequestParameter & other) private
 {
     setSrReqSn(other.getSrReqSn());
     setStreamNumbersArraySize(other.getStreamNumbersArraySize());
     for (uint16_t i = 0; i < other.getStreamNumbersArraySize(); i++) {
         setStreamNumbers(i, other.getStreamNumbers(i));
     }
 }
Referenced by operator=(), and SctpIncomingSsnResetRequestParameter().
dup()
virtual SctpIncomingSsnResetRequestParameter* inet::sctp::SctpIncomingSsnResetRequestParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpIncomingSsnResetRequestParameter_Base.
 { return new SctpIncomingSsnResetRequestParameter(*this); }
operator=()
SctpIncomingSsnResetRequestParameter& inet::sctp::SctpIncomingSsnResetRequestParameter::operator= (const SctpIncomingSsnResetRequestParameter & other) inline
 { if (this == &other) return *this; SctpIncomingSsnResetRequestParameter_Base::operator=(other); copy(other); return *this; }
The documentation for this class was generated from the following files:
SctpHeader.h
SctpHeader.cc