INET Framework for OMNeT++/OMNEST: inet::physicallayer::IsotropicDimensionalBackgroundNoise Class Reference
inet::physicallayer::IsotropicDimensionalBackgroundNoise Class Reference
#include <IsotropicDimensionalBackgroundNoise.h>
Public Member Functions
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const INoise * computeNoise (const IListening *listening) const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
Protected Attributes
WpHz powerSpectralDensity = WpHz(NaN)
W power = W(NaN)
Hz bandwidth = Hz(NaN)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
computeNoise()
const INoise * inet::physicallayer::IsotropicDimensionalBackgroundNoise::computeNoise (const IListening * listening) const override virtual
Implements inet::physicallayer::IBackgroundNoise.
 {
     const BandListening *bandListening = check_and_cast<const BandListening *>(listening);
     Hz centerFrequency = bandListening->getCenterFrequency();
     Hz listeningBandwidth = bandListening->getBandwidth();
     WpHz noisePowerSpectralDensity;
     if (!std::isnan(powerSpectralDensity.get()))
         noisePowerSpectralDensity = powerSpectralDensity;
     else {
         if (std::isnan(bandwidth.get()))
             bandwidth = listeningBandwidth;
         else if (bandwidth != listeningBandwidth)
             throw cRuntimeError("The powerSpectralDensity parameter is not specified and the power parameter cannot be used, because background noise bandwidth doesn't match listening bandwidth");
         // NOTE: dividing by the bandwidth here makes sure the total background noise power in the listening band is the given power
         noisePowerSpectralDensity = power / bandwidth;
     }
     const Ptr<const IFunction<WpHz, Domain<simsec, Hz>>>& powerFunction = makeShared<ConstantFunction<WpHz, Domain<simsec, Hz>>>(noisePowerSpectralDensity);
     const simtime_t startTime = listening->getStartTime();
     const simtime_t endTime = listening->getEndTime();
     return new DimensionalNoise(startTime, endTime, centerFrequency, bandwidth, makeFirstQuadrantLimitedFunction(powerFunction));
 }
initialize()
void inet::physicallayer::IsotropicDimensionalBackgroundNoise::initialize (int stage) override protected virtual
 {
     cModule::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         powerSpectralDensity = WpHz(dBmWpMHz2WpHz(par("powerSpectralDensity")));
         power = mW(dBmW2mW(par("power")));
         bandwidth = Hz(par("bandwidth"));
         if (std::isnan(powerSpectralDensity.get()) && std::isnan(power.get()))
             throw cRuntimeError("One of powerSpectralDensity or power parameters must be specified");
         if (!std::isnan(powerSpectralDensity.get()) && !std::isnan(power.get()))
             throw cRuntimeError("Both of powerSpectralDensity and power parameters cannot be specified");
     }
 }
printToStream()
std::ostream & inet::physicallayer::IsotropicDimensionalBackgroundNoise::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "IsotropicDimensionalBackgroundNoise";
     if (level <= PRINT_LEVEL_DETAIL) {
         if (!std::isnan(powerSpectralDensity.get()))
             stream << EV_FIELD(powerSpectralDensity);
         else {
             stream << EV_FIELD(power);
             stream << EV_FIELD(bandwidth);
         }
     }
     return stream;
 }
Member Data Documentation
bandwidth
Hz inet::physicallayer::IsotropicDimensionalBackgroundNoise::bandwidth = Hz(NaN) mutable protected
Referenced by computeNoise(), initialize(), and printToStream().
power
W inet::physicallayer::IsotropicDimensionalBackgroundNoise::power = W(NaN) protected
Referenced by computeNoise(), initialize(), and printToStream().
powerSpectralDensity
WpHz inet::physicallayer::IsotropicDimensionalBackgroundNoise::powerSpectralDensity = WpHz(NaN) protected
Referenced by computeNoise(), initialize(), and printToStream().
The documentation for this class was generated from the following files:
IsotropicDimensionalBackgroundNoise.h
IsotropicDimensionalBackgroundNoise.cc