INET Framework for OMNeT++/OMNEST: inet::sctp::SctpSetPrimaryIPParameter Class Reference
inet::sctp::SctpSetPrimaryIPParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:330 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpSetPrimaryIPParameter (const char *name=nullptr)
SctpSetPrimaryIPParameter (const SctpSetPrimaryIPParameter &other)
virtual ~SctpSetPrimaryIPParameter ()
SctpSetPrimaryIPParameter & operator= (const SctpSetPrimaryIPParameter &other)
virtual SctpSetPrimaryIPParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getRequestCorrelationId () const
virtual void setRequestCorrelationId (uint32_t requestCorrelationId)
virtual const ::inet::L3Address & getAddressParam () const
virtual ::inet::L3Address & getAddressParamForUpdate ()
virtual void setAddressParam (const ::inet::L3Address &addressParam)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpSetPrimaryIPParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint32_t requestCorrelationId = 0
::inet::L3Address addressParam
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpSetPrimaryIPParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:330 by opp_msgtool.
class SctpSetPrimaryIPParameter extends SctpParameter
{
    uint32_t requestCorrelationId; //assigned by the sender to identify each request parameter
    L3Address addressParam;
}
Constructor & Destructor Documentation
SctpSetPrimaryIPParameter() [1/2]
inet::sctp::SctpSetPrimaryIPParameter::SctpSetPrimaryIPParameter (const char * name = nullptr)
SctpSetPrimaryIPParameter() [2/2]
inet::sctp::SctpSetPrimaryIPParameter::SctpSetPrimaryIPParameter (const SctpSetPrimaryIPParameter & other)
~SctpSetPrimaryIPParameter()
virtual inet::sctp::SctpSetPrimaryIPParameter::~SctpSetPrimaryIPParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpSetPrimaryIPParameter::copy (const SctpSetPrimaryIPParameter & other) private
dup()
virtual SctpSetPrimaryIPParameter* inet::sctp::SctpSetPrimaryIPParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpSetPrimaryIPParameter(*this);}
getAddressParam()
virtual const ::inet::L3Address& inet::sctp::SctpSetPrimaryIPParameter::getAddressParam () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfArrived(), inet::sctp::SctpAssociation::sendAsconf(), and inet::sctp::SctpHeaderSerializer::serialize().
getAddressParamForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpSetPrimaryIPParameter::getAddressParamForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpSetPrimaryIPParameter*>(this)->getAddressParam());}
getRequestCorrelationId()
virtual uint32_t inet::sctp::SctpSetPrimaryIPParameter::getRequestCorrelationId () const virtual
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpSetPrimaryIPParameter& inet::sctp::SctpSetPrimaryIPParameter::operator= (const SctpSetPrimaryIPParameter & other)
operator==()
bool inet::sctp::SctpSetPrimaryIPParameter::operator== (const SctpSetPrimaryIPParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpSetPrimaryIPParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpSetPrimaryIPParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setAddressParam()
virtual void inet::sctp::SctpSetPrimaryIPParameter::setAddressParam (const ::inet::L3Address & addressParam) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendAsconf().
setRequestCorrelationId()
virtual void inet::sctp::SctpSetPrimaryIPParameter::setRequestCorrelationId (uint32_t requestCorrelationId) virtual
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), and inet::sctp::SctpAssociation::sendAsconf().
Member Data Documentation
addressParam
::inet::L3Address inet::sctp::SctpSetPrimaryIPParameter::addressParam protected
requestCorrelationId
uint32_t inet::sctp::SctpSetPrimaryIPParameter::requestCorrelationId = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h