INET Framework for OMNeT++/OMNEST: inet::Box Class Reference
inet::Box Class Reference
#include <Box.h>
Public Member Functions
Box (const Coord &min, const Coord &max)
const Coord & getMin () const
const Coord & getMax () const
Coord getSize () const
Coord getCenter () const
virtual bool isNil () const override
Returns true if this geometric object is the same as the unspecified singleton instance of this type.
virtual bool isUnspecified () const override
Returns true if this geometric object is not completely specified.
Public Member Functions inherited from inet::GeometricObjectBase
GeometricObjectBase ()
virtual ~GeometricObjectBase ()
Static Public Member Functions
static Box computeBoundingBox (const std::vector< Coord > &points)
Static Public Attributes
static const Box NIL = Box(Coord::NIL, Coord::NIL)
Protected Attributes
Coord min
Coord max
Constructor & Destructor Documentation
Box()
inet::Box::Box (const Coord & min, const Coord & max)
                                            :
     min(min),
     max(max)
 {
 }
Referenced by computeBoundingBox().
Member Function Documentation
computeBoundingBox()
Box inet::Box::computeBoundingBox (const std::vector< Coord > & points) static
 {
     Coord min = Coord::NIL;
     Coord max = Coord::NIL;
     if (points.begin() != points.end()) {
         min = *points.begin();
         max = min;
     }
     for (const auto& point : points) {
         min = min.min(point);
         max = max.max(point);
     }
     return Box(min, max);
 }
Referenced by inet::physicalenvironment::PhysicalEnvironment::convertPoints(), and inet::physicalenvironment::PhysicalEnvironment::parseObjects().
getCenter()
Coord inet::Box::getCenter () const inline
 { return (min + max) / 2; }
Referenced by inet::physicalenvironment::PhysicalEnvironment::convertPoints().
getMax()
const Coord& inet::Box::getMax () const inline
 { return max; }
Referenced by inet::visualizer::SceneOsgVisualizerBase::initializeSceneFloor().
getMin()
const Coord& inet::Box::getMin () const inline
 { return min; }
Referenced by inet::visualizer::SceneOsgVisualizerBase::initializeSceneFloor().
getSize()
Coord inet::Box::getSize () const inline
 { return max - min; }
Referenced by inet::physicalenvironment::PhysicalEnvironment::parseObjects().
isNil()
virtual bool inet::Box::isNil () const inline override virtual
Returns true if this geometric object is the same as the unspecified singleton instance of this type.
Implements inet::GeometricObjectBase.
 { return this == &NIL; }
isUnspecified()
virtual bool inet::Box::isUnspecified () const inline override virtual
Returns true if this geometric object is not completely specified.
Implements inet::GeometricObjectBase.
 { return min.isUnspecified() || max.isUnspecified(); }
Member Data Documentation
max
Coord inet::Box::max protected
Referenced by computeBoundingBox().
min
Coord inet::Box::min protected
Referenced by computeBoundingBox().
NIL
const Box inet::Box::NIL = Box(Coord::NIL, Coord::NIL) static
The documentation for this class was generated from the following files:
Box.h
Box.cc