INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2Link Class Reference
inet::ospfv2::Ospfv2Link Class Reference
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:130 by opp_msgtool.
#include <Ospfv2Packet_m.h>
Public Member Functions
Ospfv2Link ()
Ospfv2Link (const Ospfv2Link &other)
virtual ~Ospfv2Link ()
Ospfv2Link & operator= (const Ospfv2Link &other)
virtual Ospfv2Link * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getLinkID () const
virtual ::inet::Ipv4Address & getLinkIDForUpdate ()
virtual void setLinkID (const ::inet::Ipv4Address &linkID)
virtual unsigned long getLinkData () const
virtual void setLinkData (unsigned long linkData)
virtual LinkType getType () const
virtual void setType (LinkType type)
virtual unsigned char getNumberOfTOS () const
virtual void setNumberOfTOS (unsigned char numberOfTOS)
virtual unsigned long getLinkCost () const
virtual void setLinkCost (unsigned long linkCost)
virtual void setTosDataArraySize (size_t size)
virtual size_t getTosDataArraySize () const
virtual const Ospfv2TosData & getTosData (size_t k) const
virtual Ospfv2TosData & getTosDataForUpdate (size_t k)
virtual void setTosData (size_t k, const Ospfv2TosData &tosData)
virtual void insertTosData (size_t k, const Ospfv2TosData &tosData)
void insertTosData (const Ospfv2TosData &tosData)
virtual void appendTosData (const Ospfv2TosData &tosData)
virtual void eraseTosData (size_t k)
Protected Member Functions
bool operator== (const Ospfv2Link &)=delete
Protected Attributes
::inet::Ipv4Address linkID
unsigned long linkData = 0
LinkType type = POINTTOPOINT_LINK
unsigned char numberOfTOS = 0
unsigned long linkCost = 1
Ospfv2TosData * tosData = nullptr
size_t tosData_arraysize = 0
Private Member Functions
void copy (const Ospfv2Link &other)
Detailed Description
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:130 by opp_msgtool.
// Router LSA Link section (RFC 1583 Section A.4.2.)
class Ospfv2Link extends cObject
{
    @packetData;
    Ipv4Address linkID;
    unsigned long linkData = 0;
    LinkType type = POINTTOPOINT_LINK;
    unsigned char numberOfTOS = 0;
    unsigned long linkCost = 1;     // TOS 0 metric
    Ospfv2TosData tosData[];
}
Constructor & Destructor Documentation
Ospfv2Link() [1/2]
inet::ospfv2::Ospfv2Link::Ospfv2Link ()
Ospfv2Link() [2/2]
inet::ospfv2::Ospfv2Link::Ospfv2Link (const Ospfv2Link & other)
~Ospfv2Link()
virtual inet::ospfv2::Ospfv2Link::~Ospfv2Link () virtual
Member Function Documentation
appendTosData()
virtual void inet::ospfv2::Ospfv2Link::appendTosData (const Ospfv2TosData & tosData) virtual
copy()
void inet::ospfv2::Ospfv2Link::copy (const Ospfv2Link & other) private
dup()
virtual Ospfv2Link* inet::ospfv2::Ospfv2Link::dup () const inline override virtual
 {return new Ospfv2Link(*this);}
eraseTosData()
virtual void inet::ospfv2::Ospfv2Link::eraseTosData (size_t k) virtual
getLinkCost()
virtual unsigned long inet::ospfv2::Ospfv2Link::getLinkCost () const virtual
Referenced by inet::ospfv2::operator<<().
getLinkData()
virtual unsigned long inet::ospfv2::Ospfv2Link::getLinkData () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateNextHops(), and inet::ospfv2::operator<<().
getLinkID()
virtual const ::inet::Ipv4Address& inet::ospfv2::Ospfv2Link::getLinkID () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::operator<<(), inet::ospfv2::MessageHandler::printLinkStateUpdatePacket(), and inet::ospfv2::Ospfv2Area::printLSDB().
getLinkIDForUpdate()
virtual ::inet::Ipv4Address& inet::ospfv2::Ospfv2Link::getLinkIDForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<Ospfv2Link*>(this)->getLinkID());}
getNumberOfTOS()
virtual unsigned char inet::ospfv2::Ospfv2Link::getNumberOfTOS () const virtual
getTosData()
virtual const Ospfv2TosData& inet::ospfv2::Ospfv2Link::getTosData (size_t k) const virtual
Referenced by inet::ospfv2::operator<<().
getTosDataArraySize()
virtual size_t inet::ospfv2::Ospfv2Link::getTosDataArraySize () const virtual
Referenced by inet::ospfv2::RouterLsa::differsFrom(), and inet::ospfv2::operator<<().
getTosDataForUpdate()
virtual Ospfv2TosData& inet::ospfv2::Ospfv2Link::getTosDataForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv2TosData&>(const_cast<Ospfv2Link*>(this)->getTosData(k));}
getType()
virtual LinkType inet::ospfv2::Ospfv2Link::getType () const virtual
Referenced by inet::ospfv2::Ospfv2Area::calculateNextHops(), and inet::ospfv2::operator<<().
insertTosData() [1/2]
void inet::ospfv2::Ospfv2Link::insertTosData (const Ospfv2TosData & tosData) inline
 {appendTosData(tosData);}
insertTosData() [2/2]
virtual void inet::ospfv2::Ospfv2Link::insertTosData (size_t k, const Ospfv2TosData & tosData) virtual
operator=()
Ospfv2Link& inet::ospfv2::Ospfv2Link::operator= (const Ospfv2Link & other)
operator==()
bool inet::ospfv2::Ospfv2Link::operator== (const Ospfv2Link &) protected delete
parsimPack()
virtual void inet::ospfv2::Ospfv2Link::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::ospfv2::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv2::Ospfv2Link::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::ospfv2::doParsimUnpacking().
setLinkCost()
virtual void inet::ospfv2::Ospfv2Link::setLinkCost (unsigned long linkCost) virtual
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
setLinkData()
virtual void inet::ospfv2::Ospfv2Link::setLinkData (unsigned long linkData) virtual
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
setLinkID()
virtual void inet::ospfv2::Ospfv2Link::setLinkID (const ::inet::Ipv4Address & linkID) virtual
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
setNumberOfTOS()
virtual void inet::ospfv2::Ospfv2Link::setNumberOfTOS (unsigned char numberOfTOS) virtual
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
setTosData()
virtual void inet::ospfv2::Ospfv2Link::setTosData (size_t k, const Ospfv2TosData & tosData) virtual
setTosDataArraySize()
virtual void inet::ospfv2::Ospfv2Link::setTosDataArraySize (size_t size) virtual
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
setType()
virtual void inet::ospfv2::Ospfv2Link::setType (LinkType type) virtual
Referenced by inet::ospfv2::Ospfv2Area::originateRouterLSA().
Member Data Documentation
linkCost
unsigned long inet::ospfv2::Ospfv2Link::linkCost = 1 protected
linkData
unsigned long inet::ospfv2::Ospfv2Link::linkData = 0 protected
linkID
::inet::Ipv4Address inet::ospfv2::Ospfv2Link::linkID protected
numberOfTOS
unsigned char inet::ospfv2::Ospfv2Link::numberOfTOS = 0 protected
tosData
Ospfv2TosData* inet::ospfv2::Ospfv2Link::tosData = nullptr protected
tosData_arraysize
size_t inet::ospfv2::Ospfv2Link::tosData_arraysize = 0 protected
type
LinkType inet::ospfv2::Ospfv2Link::type = POINTTOPOINT_LINK protected
The documentation for this class was generated from the following file:
Ospfv2Packet_m.h