INET Framework for OMNeT++/OMNEST: inet::GaussMarkovMobility Class Reference
inet::GaussMarkovMobility Class Reference
Gauss Markov movement model.
#include <GaussMarkovMobility.h>
Public Member Functions
virtual double getMaxSpeed () const override
Returns the maximum possible speed at any future time.
GaussMarkovMobility ()
Public Member Functions inherited from inet::LineSegmentsMobilityBase
LineSegmentsMobilityBase ()
Public Member Functions inherited from inet::MovingMobilityBase
virtual const Coord & getCurrentPosition () override
Returns the position at the current simulation time.
virtual const Coord & getCurrentVelocity () override
Returns the velocity at the current simulation time.
virtual const Coord & getCurrentAcceleration () override
Returns the acceleration at the current simulation time.
virtual const Quaternion & getCurrentAngularPosition () override
Returns the angular position at the current simulation time.
virtual const Quaternion & getCurrentAngularVelocity () override
Returns the angular velocity at the current simulation time.
virtual const Quaternion & getCurrentAngularAcceleration () override
Returns the angular acceleration at the current simulation time.
Public Member Functions inherited from inet::MobilityBase
virtual const Coord & getConstraintAreaMax () const override
Returns the maximum position along each axes for.
virtual const Coord & getConstraintAreaMin () const override
Returns the minimum position along each axes for.
Public Member Functions inherited from inet::IMobility
virtual ~IMobility ()
Protected Member Functions
virtual int numInitStages () const override
Returns the required number of initialize stages.
virtual void initialize (int stage) override
Initializes mobility model parameters.
void preventBorderHugging ()
If the host is too close to the border it is repelled.
virtual void move () override
Move the host.
virtual void setTargetPosition () override
Calculate a new target position to move to.
Protected Member Functions inherited from inet::LineSegmentsMobilityBase
virtual void initializePosition () override
Initializes mobility position.
Protected Member Functions inherited from inet::MovingMobilityBase
MovingMobilityBase ()
virtual ~MovingMobilityBase ()
virtual void handleSelfMessage (cMessage *message) override
Called upon arrival of a self messages, subclasses must override.
void scheduleUpdate ()
Schedules the move timer that will update the mobility state.
void moveAndUpdate ()
Moves and notifies listeners.
virtual void orient ()
Protected Member Functions inherited from inet::MobilityBase
MobilityBase ()
virtual int getId () const override
virtual void setInitialPosition ()
Initializes the position from the display string or from module parameters.
virtual void checkPosition ()
Checks whether the position is valid or not.
virtual void initializeOrientation ()
Initializes the orientation from module parameters.
virtual void refreshDisplay () const override
Moves the visual representation module's icon to the new position on the screen.
virtual void updateDisplayStringFromMobilityState () const
virtual void handleParameterChange (const char *name) override
Allows changing parameters from the GUI.
virtual void handleMessage (cMessage *msg) override
This modules should only receive self-messages.
virtual void emitMobilityStateChangedSignal ()
Emits a signal with the updated mobility state.
virtual Coord getRandomPosition ()
Returns a new random position satisfying the constraint area.
virtual cModule * findSubjectModule ()
Returns the module that represents the object moved by this mobility module.
virtual bool isOutside ()
Returns true if the mobility is outside of the constraint area.
virtual void reflectIfOutside (Coord &targetPosition, Coord &velocity, rad &angle, rad &elevation, Quaternion &quaternion)
Utility function to reflect the node if it goes outside the constraint area.
virtual void wrapIfOutside (Coord &targetPosition)
Utility function to wrap the node to the opposite edge (torus) if it goes outside the constraint area.
virtual void placeRandomlyIfOutside (Coord &targetPosition)
Utility function to place the node randomly if it goes outside the constraint area.
virtual void raiseErrorIfOutside ()
Utility function to raise an error if the node gets outside the constraint area.
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity)
Invokes one of reflectIfOutside(), wrapIfOutside() and placeRandomlyIfOutside(), depending on the given border policy.
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity, rad &heading)
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity, rad &heading, rad &elevation)
virtual void handleIfOutside (BorderPolicy policy, Coord &targetPosition, Coord &velocity, rad &heading, rad &elevation, Quaternion &quaternion)
Protected Attributes
double speed = 0.0
speed of the host
double speedMean = 0.0
speed mean
double speedStdDev = 0.0
speed standard deviation
rad angle = rad(0.0)
angle of linear motion
rad angleMean = rad(0.0)
angle mean
rad angleStdDev = rad(0.0)
angle standard deviation
double alpha = 0.0
alpha parameter in [0;1] interval
double margin = 0.0
margin at which the host gets repelled from the border
Protected Attributes inherited from inet::LineSegmentsMobilityBase
Coord targetPosition
End position of current linear movement.
Protected Attributes inherited from inet::MovingMobilityBase
cMessage * moveTimer
The message used for mobility state changes.
simtime_t updateInterval
The simulation time interval used to regularly signal mobility state changes.
bool stationary
A mobility model may decide to become stationary at any time.
Coord lastVelocity
The last velocity that was reported at lastUpdate.
Quaternion lastAngularVelocity
The last angular velocity that was reported at lastUpdate.
simtime_t lastUpdate
The simulation time when the mobility state was last updated.
simtime_t nextChange
The next simulation time when the mobility module needs to update its internal state.
bool faceForward
Protected Attributes inherited from inet::MobilityBase
cModule * subjectModule
Pointer to visual representation module, to speed up repeated access.
const CanvasProjection * canvasProjection
The 2D projection used on the canvas.
Coord constraintAreaMin
3 dimensional position and size of the constraint area (in meters).
Coord constraintAreaMax
Coord lastPosition
The last position that was reported.
Quaternion lastOrientation
The last orientation that was reported.
StringFormat format
Additional Inherited Members
Public Types inherited from inet::MobilityBase
enum BorderPolicy { REFLECT, WRAP, PLACERANDOMLY, RAISEERROR }
Selects how a mobility module should behave if it reaches the edge of the constraint area.
Static Public Attributes inherited from inet::IMobility
static simsignal_t mobilityStateChangedSignal = cComponent::registerSignal("mobilityStateChanged")
A signal used to publish mobility state changes.
Detailed Description
Gauss Markov movement model.
See NED file for more info.
Author
Marcin Kosiba
Constructor & Destructor Documentation
GaussMarkovMobility()
inet::GaussMarkovMobility::GaussMarkovMobility ()
 {
 }
Member Function Documentation
getMaxSpeed()
virtual double inet::GaussMarkovMobility::getMaxSpeed () const inline override virtual
Returns the maximum possible speed at any future time.
Reimplemented from inet::MobilityBase.
 { return speed; }
initialize()
void inet::GaussMarkovMobility::initialize (int stage) override protected virtual
Initializes mobility model parameters.
Reimplemented from inet::MovingMobilityBase.
 {
     LineSegmentsMobilityBase::initialize(stage);
     EV_TRACE << "initializing GaussMarkovMobility stage " << stage << endl;
     if (stage == INITSTAGE_LOCAL) {
         speedMean = par("speed");
         speedStdDev = par("speedStdDev");
         angleMean = deg(fmod(deg(par("angle")).get(), 360.0));
         angleStdDev = deg(par("angleStdDev"));
         alpha = par("alpha");
         if (alpha < 0.0 || alpha > 1.0)
             throw cRuntimeError("The parameter 'alpha' is out of [0;1] interval");
         // constrain alpha to [0.0;1.0]
         margin = par("margin");
         speed = speedMean;
         angle = angleMean;
         stationary = (speed == 0);
     }
 }
move()
void inet::GaussMarkovMobility::move () override protected virtual
Move the host.
Reimplemented from inet::LineSegmentsMobilityBase.
 {
     preventBorderHugging();
     LineSegmentsMobilityBase::move();
     handleIfOutside(REFLECT, lastPosition, lastVelocity, angle);
 }
numInitStages()
virtual int inet::GaussMarkovMobility::numInitStages () const inline override protected virtual
Returns the required number of initialize stages.
Reimplemented from inet::MobilityBase.
 { return NUM_INIT_STAGES; }
preventBorderHugging()
void inet::GaussMarkovMobility::preventBorderHugging () protected
If the host is too close to the border it is repelled.
 {
     bool left = (lastPosition.x < constraintAreaMin.x + margin);
     bool right = (lastPosition.x >= constraintAreaMax.x - margin);
     bool top = (lastPosition.y < constraintAreaMin.y + margin);
     bool bottom = (lastPosition.y >= constraintAreaMax.y - margin);
     if (top || bottom) {
         angleMean = bottom ? deg(270.0) : deg(90.0);
         if (right)
             angleMean -= deg(45.0);
         else if (left)
             angleMean += deg(45.0);
     }
     else if (left)
         angleMean = deg(0.0);
     else if (right)
         angleMean = deg(180.0);
 }
Referenced by move().
setTargetPosition()
void inet::GaussMarkovMobility::setTargetPosition () override protected virtual
Calculate a new target position to move to.
Implements inet::LineSegmentsMobilityBase.
 {
     // calculate new speed and direction based on the model
     speed = alpha * speed
         + (1.0 - alpha) * speedMean
         + sqrt(1.0 - alpha * alpha) * normal(0.0, 1.0) * speedStdDev;
     angle = alpha * angle
         + (1.0 - alpha) * angleMean
         + rad(sqrt(1.0 - alpha * alpha) * normal(0.0, 1.0) * angleStdDev);
     Coord direction(cos(rad(angle).get()), sin(rad(angle).get()));
     nextChange = simTime() + updateInterval;
     targetPosition = lastPosition + direction * (speed * updateInterval.dbl());
     EV_DEBUG << " speed = " << speed << " angle = " << angle << endl;
     EV_DEBUG << " mspeed = " << speedMean << " mangle = " << angleMean << endl;
 }
Member Data Documentation
alpha
double inet::GaussMarkovMobility::alpha = 0.0 protected
alpha parameter in [0;1] interval
Referenced by initialize(), and setTargetPosition().
angle
rad inet::GaussMarkovMobility::angle = rad(0.0) protected
angle of linear motion
Referenced by initialize(), move(), and setTargetPosition().
angleMean
rad inet::GaussMarkovMobility::angleMean = rad(0.0) protected
angle mean
Referenced by initialize(), preventBorderHugging(), and setTargetPosition().
angleStdDev
rad inet::GaussMarkovMobility::angleStdDev = rad(0.0) protected
angle standard deviation
Referenced by initialize(), and setTargetPosition().
margin
double inet::GaussMarkovMobility::margin = 0.0 protected
margin at which the host gets repelled from the border
Referenced by initialize(), and preventBorderHugging().
speed
double inet::GaussMarkovMobility::speed = 0.0 protected
speed of the host
Referenced by initialize(), and setTargetPosition().
speedMean
double inet::GaussMarkovMobility::speedMean = 0.0 protected
speed mean
Referenced by initialize(), and setTargetPosition().
speedStdDev
double inet::GaussMarkovMobility::speedStdDev = 0.0 protected
speed standard deviation
Referenced by initialize(), and setTargetPosition().
The documentation for this class was generated from the following files:
GaussMarkovMobility.h
GaussMarkovMobility.cc