INET Framework for OMNeT++/OMNEST: inet::IdentityTag Class Reference
inet::IdentityTag Class Reference
Class generated from inet/common/IdentityTag.msg:25 by opp_msgtool.
#include <IdentityTag_m.h>
Public Member Functions
IdentityTag ()
IdentityTag (const IdentityTag &other)
virtual ~IdentityTag ()
IdentityTag & operator= (const IdentityTag &other)
virtual IdentityTag * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint64_t getIdentityStart () const
virtual void setIdentityStart (uint64_t identityStart)
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const override
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Static Public Member Functions
static int64_t getNextIdentityStart (b length)
Static Public Attributes
static int64_t nextIdentityStart
Protected Member Functions
bool operator== (const IdentityTag &)=delete
Protected Attributes
uint64_t identityStart = -1
Private Member Functions
void copy (const IdentityTag &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/common/IdentityTag.msg:25 by opp_msgtool.
//
// This tag provides a bit level identity for binary data. It must attached to
// a packet or chunk as a region tag. The identity of a bit in the region can be
// calculated by adding the offset of said bit to the identityStart field of the
// tag.
//
// The tag is split and merged automatically when the data is split or merged.
// This allows one to have an effective globally unique identity for each bit
// in the simulation. This tag allows following the bits in the network through
// the whole lifetime of the simulation.
//
class IdentityTag extends TagBase
{
    uint64_t identityStart = -1;
}
Constructor & Destructor Documentation
IdentityTag() [1/2]
inet::IdentityTag::IdentityTag ()
IdentityTag() [2/2]
inet::IdentityTag::IdentityTag (const IdentityTag & other)
~IdentityTag()
virtual inet::IdentityTag::~IdentityTag () virtual
Member Function Documentation
changeRegion()
virtual const Ptr<TagBase> inet::IdentityTag::changeRegion (b offsetDelta, b lengthDelta) const inline override virtual
Reimplemented from inet::TagBase.
{
         if (offsetDelta == b(0))
             return const_cast<IdentityTag *>(this)->shared_from_this();
         else {
             const auto& result = staticPtrCast<IdentityTag>(dupShared());
             result->identityStart += b(offsetDelta).get();
             return result;
         }
     }
copy()
void inet::IdentityTag::copy (const IdentityTag & other) private
dup()
virtual IdentityTag* inet::IdentityTag::dup () const inline override virtual
 {return new IdentityTag(*this);}
getIdentityStart()
virtual uint64_t inet::IdentityTag::getIdentityStart () const virtual
getNextIdentityStart()
static int64_t inet::IdentityTag::getNextIdentityStart (b length) inline static
 { auto result = nextIdentityStart; nextIdentityStart += b(length).get(); return result; }
Referenced by inet::queueing::PacketSourceBase::createPacket().
operator=()
IdentityTag& inet::IdentityTag::operator= (const IdentityTag & other)
operator==()
bool inet::IdentityTag::operator== (const IdentityTag &) protected delete
parsimPack()
virtual void inet::IdentityTag::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::IdentityTag::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setIdentityStart()
virtual void inet::IdentityTag::setIdentityStart (uint64_t identityStart) virtual
Member Data Documentation
identityStart
uint64_t inet::IdentityTag::identityStart = -1 protected
nextIdentityStart
int64_t inet::IdentityTag::nextIdentityStart static
The documentation for this class was generated from the following file:
IdentityTag_m.h