INET Framework for OMNeT++/OMNEST: inet::EligibilityTimeTag Class Reference
inet::EligibilityTimeTag Class Reference
Class generated from inet/protocolelement/shaper/EligibilityTimeTag.msg:22 by opp_msgtool.
#include <EligibilityTimeTag_m.h>
Public Member Functions
EligibilityTimeTag ()
EligibilityTimeTag (const EligibilityTimeTag &other)
virtual ~EligibilityTimeTag ()
EligibilityTimeTag & operator= (const EligibilityTimeTag &other)
virtual EligibilityTimeTag * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual clocktime_t getEligibilityTime () const
virtual void setEligibilityTime (clocktime_t eligibilityTime)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const EligibilityTimeTag &)=delete
Protected Attributes
clocktime_t eligibilityTime = CLOCKTIME_ZERO
Private Member Functions
void copy (const EligibilityTimeTag &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/protocolelement/shaper/EligibilityTimeTag.msg:22 by opp_msgtool.
//
// This tag specifies the simulation time after which the packet becomes eligible
// for transmission according to the asynchronous shaper.
//
// This tag is used by the asynchronous shaper infrastructure.
//
// @see ~EligibilityTimeGate, ~EligibilityTimeFilter, ~EligibilityTimeMeter, ~EligibilityTimeQueue
//
class EligibilityTimeTag extends TagBase
{
    clocktime_t eligibilityTime; // the simulation time after which the packet is eligible for transmission
}
Constructor & Destructor Documentation
EligibilityTimeTag() [1/2]
inet::EligibilityTimeTag::EligibilityTimeTag ()
EligibilityTimeTag() [2/2]
inet::EligibilityTimeTag::EligibilityTimeTag (const EligibilityTimeTag & other)
~EligibilityTimeTag()
virtual inet::EligibilityTimeTag::~EligibilityTimeTag () virtual
Member Function Documentation
copy()
void inet::EligibilityTimeTag::copy (const EligibilityTimeTag & other) private
dup()
virtual EligibilityTimeTag* inet::EligibilityTimeTag::dup () const inline override virtual
 {return new EligibilityTimeTag(*this);}
getEligibilityTime()
virtual clocktime_t inet::EligibilityTimeTag::getEligibilityTime () const virtual
Referenced by inet::EligibilityTimeGate::emitEligibilityTimeChangedSignal(), and inet::EligibilityTimeGate::updateOpen().
operator=()
EligibilityTimeTag& inet::EligibilityTimeTag::operator= (const EligibilityTimeTag & other)
operator==()
bool inet::EligibilityTimeTag::operator== (const EligibilityTimeTag &) protected delete
parsimPack()
virtual void inet::EligibilityTimeTag::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::EligibilityTimeTag::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setEligibilityTime()
virtual void inet::EligibilityTimeTag::setEligibilityTime (clocktime_t eligibilityTime) virtual
Member Data Documentation
eligibilityTime
clocktime_t inet::EligibilityTimeTag::eligibilityTime = CLOCKTIME_ZERO protected
The documentation for this class was generated from the following file:
EligibilityTimeTag_m.h