INET Framework for OMNeT++/OMNEST: inet::VoipStreamSender::Buffer Class Reference
inet::VoipStreamSender::Buffer Class Reference
#include <VoipStreamSender.h>
Public Types
enum { BUFSIZE = 48000 * 2 * 2 }
Public Member Functions
Buffer ()
~Buffer ()
void clear (int framesize)
int length () const
bool empty () const
char * readPtr ()
char * writePtr ()
int availableSpace () const
void notifyRead (int length)
void notifyWrote (int length)
void align ()
Protected Attributes
char * samples
int bufferSize
int readOffset
int writeOffset
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
BUFSIZE
 { BUFSIZE = 48000 * 2 * 2 }; // 1 second of two channel 48kHz 16bit audio
Constructor & Destructor Documentation
Buffer()
inet::VoipStreamSender::Buffer::Buffer ()
                                :
     samples(nullptr),
     bufferSize(0),
     readOffset(0),
     writeOffset(0)
 {
 }
~Buffer()
inet::VoipStreamSender::Buffer::~Buffer ()
 {
     delete[] samples;
 }
Member Function Documentation
align()
void inet::VoipStreamSender::Buffer::align ()
 {
     if (readOffset) {
         if (length())
             memcpy(samples, samples + readOffset, length());
         writeOffset -= readOffset;
         readOffset = 0;
     }
 }
Referenced by inet::VoipStreamSender::readFrame().
availableSpace()
int inet::VoipStreamSender::Buffer::availableSpace () const inline
 { return bufferSize - writeOffset; }
Referenced by inet::VoipStreamSender::readFrame().
clear()
void inet::VoipStreamSender::Buffer::clear (int framesize)
 {
     int newsize = BUFSIZE + framesize;
     if (bufferSize != newsize) {
         delete[] samples;
         bufferSize = newsize;
         samples = new char[bufferSize];
     }
     readOffset = 0;
     writeOffset = 0;
 }
Referenced by inet::VoipStreamSender::initialize(), and inet::VoipStreamSender::openSoundFile().
empty()
bool inet::VoipStreamSender::Buffer::empty () const inline
 { return writeOffset <= readOffset; }
Referenced by inet::VoipStreamSender::generatePacket().
length()
int inet::VoipStreamSender::Buffer::length () const inline
 { return writeOffset - readOffset; }
Referenced by inet::VoipStreamSender::generatePacket(), and inet::VoipStreamSender::readFrame().
notifyRead()
void inet::VoipStreamSender::Buffer::notifyRead (int length) inline
 { readOffset += length; ASSERT(readOffset <= writeOffset); }
Referenced by inet::VoipStreamSender::generatePacket().
notifyWrote()
void inet::VoipStreamSender::Buffer::notifyWrote (int length) inline
 { writeOffset += length; ASSERT(writeOffset <= bufferSize); }
Referenced by inet::VoipStreamSender::readFrame().
readPtr()
char* inet::VoipStreamSender::Buffer::readPtr () inline
 { return samples + readOffset; }
Referenced by inet::VoipStreamSender::generatePacket().
writePtr()
char* inet::VoipStreamSender::Buffer::writePtr () inline
 { return samples + writeOffset; }
Referenced by inet::VoipStreamSender::readFrame().
Member Data Documentation
bufferSize
int inet::VoipStreamSender::Buffer::bufferSize protected
readOffset
int inet::VoipStreamSender::Buffer::readOffset protected
samples
char* inet::VoipStreamSender::Buffer::samples protected
writeOffset
int inet::VoipStreamSender::Buffer::writeOffset protected
The documentation for this class was generated from the following files:
VoipStreamSender.h
VoipStreamSender.cc