INET Framework for OMNeT++/OMNEST: inet::power::AlternatingEpEnergyConsumer Class Reference
inet::power::AlternatingEpEnergyConsumer Class Reference
This class implements a simple power based alternating energy consumer.
#include <AlternatingEpEnergyConsumer.h>
Public Member Functions
virtual ~AlternatingEpEnergyConsumer ()
virtual IEnergySource * getEnergySource () const override
Returns the energy source that provides energy for this energy consumer.
virtual W getPowerConsumption () const override
Returns the power consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergyConsumer
virtual ~IEnergyConsumer ()
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleMessage (cMessage *message) override
virtual void updatePowerConsumption ()
virtual void scheduleIntervalTimer ()
Protected Attributes
IEpEnergySource * energySource = nullptr
cMessage * timer = nullptr
bool isSleeping = false
W powerConsumption = W(NaN)
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergyConsumer
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Detailed Description
This class implements a simple power based alternating energy consumer.
See the corresponding NED file for more details.
Constructor & Destructor Documentation
~AlternatingEpEnergyConsumer()
inet::power::AlternatingEpEnergyConsumer::~AlternatingEpEnergyConsumer () virtual
 {
     cancelAndDelete(timer);
 }
Member Function Documentation
getEnergySource()
virtual IEnergySource* inet::power::AlternatingEpEnergyConsumer::getEnergySource () const inline override virtual
Returns the energy source that provides energy for this energy consumer.
This function never returns nullptr.
Implements inet::power::IEnergyConsumer.
 { return energySource; }
getPowerConsumption()
virtual W inet::power::AlternatingEpEnergyConsumer::getPowerConsumption () const inline override virtual
Returns the power consumption in the range [0, +infinity).
Implements inet::power::IEpEnergyConsumer.
 { return powerConsumption; }
handleMessage()
void inet::power::AlternatingEpEnergyConsumer::handleMessage (cMessage * message) override protected virtual
 {
     if (message == timer) {
         isSleeping = !isSleeping;
         updatePowerConsumption();
         scheduleIntervalTimer();
     }
     else
         throw cRuntimeError("Unknown message");
 }
initialize()
void inet::power::AlternatingEpEnergyConsumer::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         const char *energySourceModule = par("energySourceModule");
         energySource = dynamic_cast<IEpEnergySource *>(getModuleByPath(energySourceModule));
         if (!energySource)
             throw cRuntimeError("Energy source module '%s' not found", energySourceModule);
         timer = new cMessage("timer");
         updatePowerConsumption();
         scheduleIntervalTimer();
         WATCH(isSleeping);
         WATCH(powerConsumption);
     }
     else if (stage == INITSTAGE_POWER)
         energySource->addEnergyConsumer(this);
 }
numInitStages()
virtual int inet::power::AlternatingEpEnergyConsumer::numInitStages () const inline override protected virtual
 { return NUM_INIT_STAGES; }
scheduleIntervalTimer()
void inet::power::AlternatingEpEnergyConsumer::scheduleIntervalTimer () protected virtual
 {
     scheduleAfter((isSleeping ? par("sleepInterval") : par("consumptionInterval")), timer);
 }
Referenced by handleMessage(), and initialize().
updatePowerConsumption()
void inet::power::AlternatingEpEnergyConsumer::updatePowerConsumption () protected virtual
 {
     powerConsumption = isSleeping ? W(0) : W(par("powerConsumption"));
     emit(IEpEnergySource::powerConsumptionChangedSignal, powerConsumption.get());
 }
Referenced by handleMessage(), and initialize().
Member Data Documentation
energySource
IEpEnergySource* inet::power::AlternatingEpEnergyConsumer::energySource = nullptr protected
Referenced by initialize().
isSleeping
bool inet::power::AlternatingEpEnergyConsumer::isSleeping = false protected
Referenced by handleMessage(), initialize(), scheduleIntervalTimer(), and updatePowerConsumption().
powerConsumption
W inet::power::AlternatingEpEnergyConsumer::powerConsumption = W(NaN) protected
Referenced by initialize(), and updatePowerConsumption().
timer
cMessage* inet::power::AlternatingEpEnergyConsumer::timer = nullptr protected
Referenced by handleMessage(), initialize(), scheduleIntervalTimer(), and ~AlternatingEpEnergyConsumer().
The documentation for this class was generated from the following files:
AlternatingEpEnergyConsumer.h
AlternatingEpEnergyConsumer.cc