INET Framework for OMNeT++/OMNEST: inet::VlanTagBase Class Reference
inet::VlanTagBase Class Reference
Class generated from inet/linklayer/common/VlanTag.msg:16 by opp_msgtool.
#include <VlanTag_m.h>
Public Member Functions
VlanTagBase ()
VlanTagBase (const VlanTagBase &other)
virtual ~VlanTagBase ()
VlanTagBase & operator= (const VlanTagBase &other)
virtual VlanTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getVlanId () const
virtual void setVlanId (int vlanId)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const VlanTagBase &)=delete
Protected Attributes
int vlanId = -1
Private Member Functions
void copy (const VlanTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/common/VlanTag.msg:16 by opp_msgtool.
//
// This is an abstract base class that should not be directly added as a tag.
//
class VlanTagBase extends TagBase
{
    int vlanId = -1;
}
Constructor & Destructor Documentation
VlanTagBase() [1/2]
inet::VlanTagBase::VlanTagBase ()
VlanTagBase() [2/2]
inet::VlanTagBase::VlanTagBase (const VlanTagBase & other)
~VlanTagBase()
virtual inet::VlanTagBase::~VlanTagBase () virtual
Member Function Documentation
copy()
void inet::VlanTagBase::copy (const VlanTagBase & other) private
dup()
virtual VlanTagBase* inet::VlanTagBase::dup () const inline override virtual
Reimplemented in inet::VlanInd, and inet::VlanReq.
 {return new VlanTagBase(*this);}
getVlanId()
virtual int inet::VlanTagBase::getVlanId () const virtual
Referenced by inet::VlanIndFilter::matchesPacket(), inet::VlanReqFilter::matchesPacket(), inet::VlanReqMapper::processPacket(), inet::Ieee8021qTagEpdHeaderInserter::processPacket(), inet::Ieee8021qTagTpidHeaderInserter::processPacket(), inet::Ieee8021qSocketPacketProcessor::pushPacket(), and inet::RelayInterfaceSelector::pushPacket().
operator=()
VlanTagBase& inet::VlanTagBase::operator= (const VlanTagBase & other)
operator==()
bool inet::VlanTagBase::operator== (const VlanTagBase &) protected delete
parsimPack()
virtual void inet::VlanTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::VlanInd, and inet::VlanReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::VlanTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::VlanInd, and inet::VlanReq.
Referenced by inet::doParsimUnpacking().
setVlanId()
virtual void inet::VlanTagBase::setVlanId (int vlanId) virtual
Member Data Documentation
vlanId
int inet::VlanTagBase::vlanId = -1 protected
The documentation for this class was generated from the following file:
VlanTag_m.h