INET Framework for OMNeT++/OMNEST: inet::power::ICcEnergyConsumer Class Reference
inet::power::ICcEnergyConsumer Class Reference abstract
TODO.
#include <ICcEnergyConsumer.h>
Public Member Functions
virtual A getCurrentConsumption () const =0
Returns the current consumption in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergyConsumer
virtual ~IEnergyConsumer ()
virtual IEnergySource * getEnergySource () const =0
Returns the energy source that provides energy for this energy consumer.
Static Public Attributes
static simsignal_t currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged")
The signal that is used to publish current consumption changes.
Detailed Description
TODO.
See the corresponding NED file for more details.
Member Function Documentation
getCurrentConsumption()
virtual A inet::power::ICcEnergyConsumer::getCurrentConsumption () const pure virtual
Returns the current consumption in the range [0, +infinity).
Implemented in inet::physicallayer::StateBasedCcEnergyConsumer.
Member Data Documentation
currentConsumptionChangedSignal
simsignal_t inet::power::ICcEnergyConsumer::currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged") static
The signal that is used to publish current consumption changes.
Referenced by inet::power::CcEnergySourceBase::addEnergyConsumer(), inet::power::CcEnergyStorageBase::receiveSignal(), and inet::power::CcEnergySourceBase::removeEnergyConsumer().
The documentation for this class was generated from the following files:
ICcEnergyConsumer.h
ICcEnergyConsumer.cc