INET Framework for OMNeT++/OMNEST: inet::power::CcEnergySourceBase Class Reference
inet::power::CcEnergySourceBase Class Reference
#include <CcEnergySourceBase.h>
Public Member Functions
virtual A getTotalCurrentConsumption () const override
Returns the total current consumption in the range [0, +infinity).
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Public Member Functions inherited from inet::power::ICcEnergySource
virtual V getNominalVoltage () const =0
Returns the open circuit voltage in the range [0, +infinity).
virtual V getOutputVoltage () const =0
Returns the output voltage in the ragne [0, +infinity).
Protected Member Functions
virtual A computeTotalCurrentConsumption () const
virtual void updateTotalCurrentConsumption ()
Protected Attributes
A totalCurrentConsumption = A(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Additional Inherited Members
Static Public Attributes inherited from inet::power::ICcEnergySource
static simsignal_t currentConsumptionChangedSignal = cComponent::registerSignal("currentConsumptionChanged")
The signal that is used to publish current consumption changes.
Member Function Documentation
addEnergyConsumer()
void inet::power::CcEnergySourceBase::addEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Adds a new energy consumer to the energy source.
The energyConsumer parameter must not be nullptr.
Reimplemented from inet::power::EnergySourceBase.
Reimplemented in inet::power::CcEnergyStorageBase.
 {
     EnergySourceBase::addEnergyConsumer(energyConsumer);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyConsumer));
     module->subscribe(ICcEnergyConsumer::currentConsumptionChangedSignal, this);
     updateTotalCurrentConsumption();
 }
Referenced by inet::power::CcEnergyStorageBase::addEnergyConsumer().
computeTotalCurrentConsumption()
A inet::power::CcEnergySourceBase::computeTotalCurrentConsumption () const protected virtual
 {
     A totalCurrentConsumption = A(0);
     for (auto energyConsumer : energyConsumers)
         totalCurrentConsumption += check_and_cast<const ICcEnergyConsumer *>(energyConsumer)->getCurrentConsumption();
     return totalCurrentConsumption;
 }
Referenced by inet::power::CcEnergyStorageBase::initialize(), and updateTotalCurrentConsumption().
getTotalCurrentConsumption()
virtual A inet::power::CcEnergySourceBase::getTotalCurrentConsumption () const inline override virtual
Returns the total current consumption in the range [0, +infinity).
Implements inet::power::ICcEnergySource.
Reimplemented in inet::power::SimpleCcBattery.
 { return totalCurrentConsumption; }
removeEnergyConsumer()
void inet::power::CcEnergySourceBase::removeEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Removes a previously added energy consumer from this energy source.
This functions throws an exception if the consumer is not found.
Reimplemented from inet::power::EnergySourceBase.
Reimplemented in inet::power::CcEnergyStorageBase.
 {
     EnergySourceBase::removeEnergyConsumer(energyConsumer);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyConsumer));
     module->unsubscribe(ICcEnergyConsumer::currentConsumptionChangedSignal, this);
     updateTotalCurrentConsumption();
 }
Referenced by inet::power::CcEnergyStorageBase::removeEnergyConsumer().
updateTotalCurrentConsumption()
void inet::power::CcEnergySourceBase::updateTotalCurrentConsumption () protected virtual
Reimplemented in inet::power::SimpleCcBattery, and inet::power::CcEnergyStorageBase.
 {
     totalCurrentConsumption = computeTotalCurrentConsumption();
 }
Referenced by addEnergyConsumer(), removeEnergyConsumer(), and inet::power::CcEnergyStorageBase::updateTotalCurrentConsumption().
Member Data Documentation
totalCurrentConsumption
A inet::power::CcEnergySourceBase::totalCurrentConsumption = A(NaN) protected
Referenced by computeTotalCurrentConsumption(), inet::power::CcEnergyStorageBase::initialize(), inet::power::SimpleCcBattery::updateResidualCapacity(), inet::power::CcEnergyStorageBase::updateTotalCurrentConsumption(), and updateTotalCurrentConsumption().
The documentation for this class was generated from the following files:
CcEnergySourceBase.h
CcEnergySourceBase.cc