INET Framework for OMNeT++/OMNEST: inet::physicallayer::ConvolutionalCode Class Reference
inet::physicallayer::ConvolutionalCode Class Reference
#include <ConvolutionalCode.h>
Public Member Functions
ConvolutionalCode (const char *transferFunctionMatrix, const char *puncturingMatrix, const char *constraintLengthVector, int codeRatePuncturingK, int codeRatePuncturingN, const char *mode)
int getCodeRatePuncturingK () const
int getCodeRatePuncturingN () const
const char * getConstraintLengthVector () const
const char * getMode () const
const char * getPuncturingMatrix () const
const char * getTransferFunctionMatrix () const
std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual double getCodeRate () const override
virtual int getEncodedLength (int decodedLength) const override
virtual int getDecodedLength (int encodedLength) const override
virtual double computeNetBitErrorRate (double grossBitErrorRate) const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const char * transferFunctionMatrix
const char * puncturingMatrix
const char * constraintLengthVector
int codeRatePuncturingK
int codeRatePuncturingN
int memory
const char * mode
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
ConvolutionalCode()
inet::physicallayer::ConvolutionalCode::ConvolutionalCode (const char * transferFunctionMatrix, const char * puncturingMatrix, const char * constraintLengthVector, int codeRatePuncturingK, int codeRatePuncturingN, const char * mode)
                                                                                                                                                                                                              :
     transferFunctionMatrix(transferFunctionMatrix),
     puncturingMatrix(puncturingMatrix),
     constraintLengthVector(constraintLengthVector),
     codeRatePuncturingK(codeRatePuncturingK),
     codeRatePuncturingN(codeRatePuncturingN),
     memory(0),
     mode(mode)
 {
     cStringTokenizer tokenizer(constraintLengthVector);
     while (tokenizer.hasMoreTokens())
         memory = std::max(memory, atoi(tokenizer.nextToken()) - 1);
 }
Member Function Documentation
computeNetBitErrorRate()
double inet::physicallayer::ConvolutionalCode::computeNetBitErrorRate (double grossBitErrorRate) const override virtual
Implements inet::physicallayer::IForwardErrorCorrection.
 {
     double p = grossBitErrorRate;
     double netBitErrorRate;
     if (codeRatePuncturingK == 1 && codeRatePuncturingN == 2) {
         if (memory == 1)
             netBitErrorRate = pow(p, 2) * (14 - 23 * p + 16 * pow(p, 2) + 2 * pow(p, 3) - 16 * pow(p, 4) + 8 * pow(p, 5))
                 / ((1 + 3 * pow(p, 2) - 2 * pow(p, 3)) * (2 - p + 4 * pow(p, 2) - 4 * pow(p, 3)));
         else if (memory == 2)
             netBitErrorRate = 44 * pow(p, 3) + 3519.0 / 8.0 * pow(p, 4) - 14351.0 / 32.0 * pow(p, 5) - 1267079.0 / 64.0 * pow(p, 6) - 31646405.0 / 512.0 * pow(p, 7) + 978265739.0 / 2048.0 * pow(p, 8) + 3931764263.0 / 1024.0 * pow(p, 9) - 48978857681.0 / 32768.0 * pow(p, 10);
         else
             throw cRuntimeError("Not yet implemented");
     }
     else
         throw cRuntimeError("Not yet implemented");
     return math::maxnan(math::minnan(netBitErrorRate, 1.0), 0.0);
 }
getCodeRate()
double inet::physicallayer::ConvolutionalCode::getCodeRate () const override virtual
Implements inet::physicallayer::IForwardErrorCorrection.
 {
     return (double)codeRatePuncturingK / codeRatePuncturingN;
 }
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::computeNetBitrate(), inet::physicallayer::Ieee80211HtSignalMode::computeNetBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeNetBitrate(), inet::physicallayer::Ieee80211VhtDataMode::computeNetBitrate(), and inet::physicallayer::ApskLayeredTransmitter::createBitModel().
getCodeRatePuncturingK()
int inet::physicallayer::ConvolutionalCode::getCodeRatePuncturingK () const inline
 { return codeRatePuncturingK; }
Referenced by inet::physicallayer::Ieee80211OfdmDecoder::calculatePadding(), inet::physicallayer::Ieee80211OfdmModeBase::computeNetBitrate(), inet::physicallayer::ApskRadio::computePaddingLength(), inet::physicallayer::ConvolutionalCoder::ConvolutionalCoder(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::getCodeRateFromDecoderModule(), inet::physicallayer::Ieee80211NistErrorModel::getOFDMAndERPOFDMChunkSuccessRate(), and inet::physicallayer::Ieee80211YansErrorModel::getOFDMAndERPOFDMChunkSuccessRate().
getCodeRatePuncturingN()
int inet::physicallayer::ConvolutionalCode::getCodeRatePuncturingN () const inline
 { return codeRatePuncturingN; }
Referenced by inet::physicallayer::Ieee80211OfdmDecoder::calculatePadding(), inet::physicallayer::Ieee80211OfdmModeBase::computeNetBitrate(), inet::physicallayer::ConvolutionalCoder::ConvolutionalCoder(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::getCodeRateFromDecoderModule(), inet::physicallayer::Ieee80211NistErrorModel::getOFDMAndERPOFDMChunkSuccessRate(), and inet::physicallayer::Ieee80211YansErrorModel::getOFDMAndERPOFDMChunkSuccessRate().
getConstraintLengthVector()
const char* inet::physicallayer::ConvolutionalCode::getConstraintLengthVector () const inline
 { return constraintLengthVector; }
Referenced by inet::physicallayer::ConvolutionalCoder::ConvolutionalCoder().
getDecodedLength()
int inet::physicallayer::ConvolutionalCode::getDecodedLength (int encodedLength) const override virtual
Implements inet::physicallayer::IForwardErrorCorrection.
 {
     ASSERT(encodedLength % codeRatePuncturingN == 0);
     return encodedLength * codeRatePuncturingK / codeRatePuncturingN;
 }
Referenced by inet::physicallayer::Ieee80211OfdmDataMode::getDuration(), and inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength().
getEncodedLength()
int inet::physicallayer::ConvolutionalCode::getEncodedLength (int decodedLength) const override virtual
Implements inet::physicallayer::IForwardErrorCorrection.
 {
     ASSERT(decodedLength % codeRatePuncturingK == 0);
     return decodedLength * codeRatePuncturingN / codeRatePuncturingK;
 }
Referenced by inet::physicallayer::ApskLayeredTransmitter::createBitModel(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel().
getMode()
const char* inet::physicallayer::ConvolutionalCode::getMode () const inline
 { return mode; }
Referenced by inet::physicallayer::ConvolutionalCoder::ConvolutionalCoder().
getPuncturingMatrix()
const char* inet::physicallayer::ConvolutionalCode::getPuncturingMatrix () const inline
 { return puncturingMatrix; }
Referenced by inet::physicallayer::ConvolutionalCoder::ConvolutionalCoder().
getTransferFunctionMatrix()
const char* inet::physicallayer::ConvolutionalCode::getTransferFunctionMatrix () const inline
 { return transferFunctionMatrix; }
Referenced by inet::physicallayer::ConvolutionalCoder::ConvolutionalCoder().
printToStream()
std::ostream & inet::physicallayer::ConvolutionalCode::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "ConvolutionalCode";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(codeRatePuncturingK)
                << EV_FIELD(codeRatePuncturingN);
     return stream;
 }
Member Data Documentation
codeRatePuncturingK
int inet::physicallayer::ConvolutionalCode::codeRatePuncturingK protected
Referenced by computeNetBitErrorRate(), getCodeRate(), getDecodedLength(), getEncodedLength(), inet::physicallayer::Ieee80211ConvolutionalCode::Ieee80211ConvolutionalCode(), and printToStream().
codeRatePuncturingN
int inet::physicallayer::ConvolutionalCode::codeRatePuncturingN protected
Referenced by computeNetBitErrorRate(), getCodeRate(), getDecodedLength(), getEncodedLength(), inet::physicallayer::Ieee80211ConvolutionalCode::Ieee80211ConvolutionalCode(), and printToStream().
constraintLengthVector
const char* inet::physicallayer::ConvolutionalCode::constraintLengthVector protected
Referenced by ConvolutionalCode().
memory
int inet::physicallayer::ConvolutionalCode::memory protected
Referenced by computeNetBitErrorRate(), and ConvolutionalCode().
mode
const char* inet::physicallayer::ConvolutionalCode::mode protected
puncturingMatrix
const char* inet::physicallayer::ConvolutionalCode::puncturingMatrix protected
Referenced by inet::physicallayer::Ieee80211ConvolutionalCode::Ieee80211ConvolutionalCode().
transferFunctionMatrix
const char* inet::physicallayer::ConvolutionalCode::transferFunctionMatrix protected
The documentation for this class was generated from the following files:
ConvolutionalCode.h
ConvolutionalCode.cc