INET Framework for OMNeT++/OMNEST: inet::HoldtimeOption Class Reference
inet::HoldtimeOption Class Reference
Class generated from inet/routing/pim/PimPacket.msg:84 by opp_msgtool.
#include <PimPacket_m.h>
Public Member Functions
HoldtimeOption ()
HoldtimeOption (const HoldtimeOption &other)
virtual ~HoldtimeOption ()
HoldtimeOption & operator= (const HoldtimeOption &other)
virtual HoldtimeOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getHoldTime () const
virtual void setHoldTime (uint16_t holdTime)
Public Member Functions inherited from inet::HelloOption
HelloOption ()
HelloOption (const HelloOption &other)
virtual ~HelloOption ()
HelloOption & operator= (const HelloOption &other)
virtual PimHelloOptionType getType () const
virtual void setType (PimHelloOptionType type)
Protected Member Functions
bool operator== (const HoldtimeOption &)=delete
Protected Member Functions inherited from inet::HelloOption
bool operator== (const HelloOption &)=delete
Protected Attributes
uint16_t holdTime = 0
Protected Attributes inherited from inet::HelloOption
PimHelloOptionType type = static_cast<inet::PimHelloOptionType>(-1)
Private Member Functions
void copy (const HoldtimeOption &other)
Detailed Description
Class generated from inet/routing/pim/PimPacket.msg:84 by opp_msgtool.
class HoldtimeOption extends HelloOption
{
    type = Holdtime;
    uint16_t holdTime; // (in seconds)
}
Constructor & Destructor Documentation
HoldtimeOption() [1/2]
inet::HoldtimeOption::HoldtimeOption ()
HoldtimeOption() [2/2]
inet::HoldtimeOption::HoldtimeOption (const HoldtimeOption & other)
~HoldtimeOption()
virtual inet::HoldtimeOption::~HoldtimeOption () virtual
Member Function Documentation
copy()
void inet::HoldtimeOption::copy (const HoldtimeOption & other) private
dup()
virtual HoldtimeOption* inet::HoldtimeOption::dup () const inline override virtual
Reimplemented from inet::HelloOption.
 {return new HoldtimeOption(*this);}
getHoldTime()
virtual uint16_t inet::HoldtimeOption::getHoldTime () const virtual
Referenced by inet::PimPacketSerializer::serialize().
operator=()
HoldtimeOption& inet::HoldtimeOption::operator= (const HoldtimeOption & other)
operator==()
bool inet::HoldtimeOption::operator== (const HoldtimeOption &) protected delete
parsimPack()
virtual void inet::HoldtimeOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::HoldtimeOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::HelloOption.
Referenced by inet::doParsimUnpacking().
setHoldTime()
virtual void inet::HoldtimeOption::setHoldTime (uint16_t holdTime) virtual
Referenced by inet::PimPacketSerializer::deserialize(), and inet::PimBase::sendHelloPacket().
Member Data Documentation
holdTime
uint16_t inet::HoldtimeOption::holdTime = 0 protected
The documentation for this class was generated from the following file:
PimPacket_m.h