INET Framework for OMNeT++/OMNEST: inet::physicallayer::IReceiver Class Reference
inet::physicallayer::IReceiver Class Reference abstract
This interface represents a physical device (a part of the radio) which converts electric signals into packets.
#include <IReceiver.h>
Public Member Functions
virtual W getMinInterferencePower () const =0
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
virtual W getMinReceptionPower () const =0
Returns the minimum reception power below which successful reception is definitely not possible.
virtual const IListening * createListening (const IRadio *radio, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition) const =0
Returns a description of how the receiver is listening on the medium.
virtual const IListeningDecision * computeListeningDecision (const IListening *listening, const IInterference *interference) const =0
Returns the result of the listening process specifying the reception state of the receiver.
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const =0
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const =0
Returns whether the reception of the provided part is possible or not.
virtual bool computeIsReceptionAttempted (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference) const =0
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
virtual bool computeIsReceptionSuccessful (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const =0
Returns whether the reception of the provided part is actually successful or failed by the receiver.
virtual const IReceptionDecision * computeReceptionDecision (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const =0
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
virtual const IReceptionResult * computeReceptionResult (const IListening *listening, const IReception *reception, const IInterference *interference, const ISnir *snir, const std::vector< const IReceptionDecision * > *decisions) const =0
Returns the complete result of the reception process for the provided reception.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents a physical device (a part of the radio) which converts electric signals into packets.
The receiver interface supports optimistic parallel computation of reception results. For this reason some functions are marked to be purely functional. Unfortunately this cannot be enforced by the compiler in C++. We really need to be very careful regarding this, because it's pretty easy to break the purely functional API just be reading a non-const member variable. As a rule of thumb these functions must be qualified with const and all of their parameters must also be qualified with const. Moreover they are forbidden to access any state that can change over time to avoid non-deterministic behavior. These functions may be called from background threads running parallel with the main simulation thread. They may also be called several times due to cache invalidation before the actual result is needed. This process is controlled by the medium.
Member Function Documentation
computeIsReceptionAttempted()
virtual bool inet::physicallayer::IReceiver::computeIsReceptionAttempted (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference) const pure virtual
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
For example, it might check that the radio is not already receiving another signal.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::Ieee802154UwbIrReceiver, and inet::physicallayer::ReceiverBase.
Referenced by inet::physicallayer::RadioMedium::isReceptionAttempted(), and inet::physicallayer::RadioMedium::isReceptionPossible().
computeIsReceptionPossible() [1/2]
virtual bool inet::physicallayer::IReceiver::computeIsReceptionPossible (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part) const pure virtual
Returns whether the reception of the provided part is possible or not.
For example, it might check if the reception power is above sensitivity.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::ReceiverBase, inet::physicallayer::UnitDiskReceiver, inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee80211UnitDiskReceiver, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
computeIsReceptionPossible() [2/2]
virtual bool inet::physicallayer::IReceiver::computeIsReceptionPossible (const IListening * listening, const ITransmission * transmission) const pure virtual
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
For example, it might check if the carrier frequency and the modulation of the transmission matches how the receiver is listening on the medium.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::NarrowbandReceiverBase, inet::physicallayer::ReceiverBase, inet::physicallayer::Ieee80211UnitDiskReceiver, inet::physicallayer::ApskDimensionalReceiver, inet::physicallayer::ApskScalarReceiver, inet::physicallayer::Ieee80211DimensionalReceiver, and inet::physicallayer::Ieee80211ScalarReceiver.
Referenced by inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), and inet::physicallayer::RadioMedium::isPotentialReceiver().
computeIsReceptionSuccessful()
virtual bool inet::physicallayer::IReceiver::computeIsReceptionSuccessful (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const pure virtual
Returns whether the reception of the provided part is actually successful or failed by the receiver.
For example, it might compute the error rate and draw a random number to make the decision.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::Ieee802154UwbIrReceiver, inet::physicallayer::SnirReceiverBase, inet::physicallayer::UnitDiskReceiver, and inet::physicallayer::FlatReceiverBase.
Referenced by inet::physicallayer::ReceiverBase::computeReceptionDecision(), and inet::physicallayer::RadioMedium::isReceptionSuccessful().
computeListeningDecision()
virtual const IListeningDecision* inet::physicallayer::IReceiver::computeListeningDecision (const IListening * listening, const IInterference * interference) const pure virtual
Returns the result of the listening process specifying the reception state of the receiver.
This function must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::FlatReceiverBase, inet::physicallayer::Ieee802154UwbIrReceiver, and inet::physicallayer::UnitDiskReceiver.
Referenced by inet::physicallayer::RadioMedium::computeListeningDecision().
computeReceptionDecision()
virtual const IReceptionDecision* inet::physicallayer::IReceiver::computeReceptionDecision (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const pure virtual
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::Ieee802154UwbIrReceiver, inet::physicallayer::NarrowbandReceiverBase, and inet::physicallayer::ReceiverBase.
Referenced by inet::physicallayer::RadioMedium::computeReceptionDecision().
computeReceptionResult()
virtual const IReceptionResult* inet::physicallayer::IReceiver::computeReceptionResult (const IListening * listening, const IReception * reception, const IInterference * interference, const ISnir * snir, const std::vector< const IReceptionDecision * > * decisions) const pure virtual
Returns the complete result of the reception process for the provided reception.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::FlatReceiverBase, inet::physicallayer::ReceiverBase, inet::physicallayer::UnitDiskReceiver, inet::physicallayer::Ieee80211ReceiverBase, and inet::physicallayer::Ieee80211UnitDiskReceiver.
Referenced by inet::physicallayer::RadioMedium::computeReceptionResult(), and inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight().
createListening()
virtual const IListening* inet::physicallayer::IReceiver::createListening (const IRadio * radio, const simtime_t startTime, const simtime_t endTime, const Coord & startPosition, const Coord & endPosition) const pure virtual
Returns a description of how the receiver is listening on the medium.
Implemented in inet::physicallayer::Ieee80211LayeredOfdmReceiver, inet::physicallayer::ApskLayeredReceiver, inet::physicallayer::Ieee802154UwbIrReceiver, inet::physicallayer::UnitDiskReceiver, and inet::physicallayer::NarrowbandReceiverBase.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), and inet::physicallayer::Radio::isListeningPossible().
getMinInterferencePower()
virtual W inet::physicallayer::IReceiver::getMinInterferencePower () const pure virtual
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
Returns a value in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::ReceiverBase, inet::physicallayer::Ieee802154NarrowbandDimensionalReceiver, and inet::physicallayer::Ieee802154NarrowbandScalarReceiver.
getMinReceptionPower()
virtual W inet::physicallayer::IReceiver::getMinReceptionPower () const pure virtual
Returns the minimum reception power below which successful reception is definitely not possible.
Returns a value in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::FlatReceiverBase, and inet::physicallayer::ReceiverBase.
The documentation for this class was generated from the following file:
IReceiver.h