INET Framework for OMNeT++/OMNEST: inet::DhcpOptions Class Reference
inet::DhcpOptions Class Reference
Class generated from inet/applications/dhcp/DhcpMessage.msg:72 by opp_msgtool.
#include <DhcpMessage_m.h>
Public Member Functions
DhcpOptions ()
DhcpOptions (const DhcpOptions &other)
virtual ~DhcpOptions ()
DhcpOptions & operator= (const DhcpOptions &other)
virtual DhcpOptions * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual DhcpMessageType getMessageType () const
virtual void setMessageType (DhcpMessageType messageType)
virtual const char * getHostName () const
virtual void setHostName (const char *hostName)
virtual void setParameterRequestListArraySize (size_t size)
virtual size_t getParameterRequestListArraySize () const
virtual DhcpOptionCode getParameterRequestList (size_t k) const
virtual void setParameterRequestList (size_t k, DhcpOptionCode parameterRequestList)
virtual void insertParameterRequestList (size_t k, DhcpOptionCode parameterRequestList)
void insertParameterRequestList (DhcpOptionCode parameterRequestList)
virtual void appendParameterRequestList (DhcpOptionCode parameterRequestList)
virtual void eraseParameterRequestList (size_t k)
virtual const MacAddress & getClientIdentifier () const
virtual MacAddress & getClientIdentifierForUpdate ()
virtual void setClientIdentifier (const MacAddress &clientIdentifier)
virtual const Ipv4Address & getRequestedIp () const
virtual Ipv4Address & getRequestedIpForUpdate ()
virtual void setRequestedIp (const Ipv4Address &requestedIp)
virtual const Ipv4Address & getSubnetMask () const
virtual Ipv4Address & getSubnetMaskForUpdate ()
virtual void setSubnetMask (const Ipv4Address &subnetMask)
virtual void setRouterArraySize (size_t size)
virtual size_t getRouterArraySize () const
virtual const Ipv4Address & getRouter (size_t k) const
virtual Ipv4Address & getRouterForUpdate (size_t k)
virtual void setRouter (size_t k, const Ipv4Address &router)
virtual void insertRouter (size_t k, const Ipv4Address &router)
void insertRouter (const Ipv4Address &router)
virtual void appendRouter (const Ipv4Address &router)
virtual void eraseRouter (size_t k)
virtual void setDnsArraySize (size_t size)
virtual size_t getDnsArraySize () const
virtual const Ipv4Address & getDns (size_t k) const
virtual Ipv4Address & getDnsForUpdate (size_t k)
virtual void setDns (size_t k, const Ipv4Address &dns)
virtual void insertDns (size_t k, const Ipv4Address &dns)
void insertDns (const Ipv4Address &dns)
virtual void appendDns (const Ipv4Address &dns)
virtual void eraseDns (size_t k)
virtual void setNtpArraySize (size_t size)
virtual size_t getNtpArraySize () const
virtual const Ipv4Address & getNtp (size_t k) const
virtual Ipv4Address & getNtpForUpdate (size_t k)
virtual void setNtp (size_t k, const Ipv4Address &ntp)
virtual void insertNtp (size_t k, const Ipv4Address &ntp)
void insertNtp (const Ipv4Address &ntp)
virtual void appendNtp (const Ipv4Address &ntp)
virtual void eraseNtp (size_t k)
virtual const Ipv4Address & getServerIdentifier () const
virtual Ipv4Address & getServerIdentifierForUpdate ()
virtual void setServerIdentifier (const Ipv4Address &serverIdentifier)
virtual ::omnetpp::simtime_t getRenewalTime () const
virtual void setRenewalTime (::omnetpp::simtime_t renewalTime)
virtual ::omnetpp::simtime_t getRebindingTime () const
virtual void setRebindingTime (::omnetpp::simtime_t rebindingTime)
virtual ::omnetpp::simtime_t getLeaseTime () const
virtual void setLeaseTime (::omnetpp::simtime_t leaseTime)
Protected Member Functions
bool operator== (const DhcpOptions &)=delete
Protected Attributes
DhcpMessageType messageType = static_cast<inet::DhcpMessageType>(-1)
::omnetpp::opp_string hostName
DhcpOptionCode * parameterRequestList = nullptr
size_t parameterRequestList_arraysize = 0
MacAddress clientIdentifier
Ipv4Address requestedIp
Ipv4Address subnetMask
Ipv4Address * router = nullptr
size_t router_arraysize = 0
Ipv4Address * dns = nullptr
size_t dns_arraysize = 0
Ipv4Address * ntp = nullptr
size_t ntp_arraysize = 0
Ipv4Address serverIdentifier
::omnetpp::simtime_t renewalTime = SIMTIME_ZERO
::omnetpp::simtime_t rebindingTime = SIMTIME_ZERO
::omnetpp::simtime_t leaseTime = SIMTIME_ZERO
Private Member Functions
void copy (const DhcpOptions &other)
Detailed Description
Class generated from inet/applications/dhcp/DhcpMessage.msg:72 by opp_msgtool.
//
// Represents options in a DHCP message. In the DHCP protocol, options are
// added to the message as tagged data items. In the simulation, this DhcpOptions
// class statically holds the union of all options actually used by the DHCP
// protocol models. Options absent from a packet are represented by empty/unfilled
// DhcpOptions fields.
//
// @see DhcpMessage, DhcpClient, DhcpServer
//
class DhcpOptions extends cObject
{
    @packetData;
    DhcpMessageType messageType; // to convey the type of the DHCP message
    string hostName; // name of the client
    DhcpOptionCode parameterRequestList[]; // used by a DHCP client to request values for specified configuration parameters
    MacAddress clientIdentifier; // used by DHCP clients to specify their unique identifier
    Ipv4Address requestedIp; // used in a client request (DHCPDISCOVER) to allow the client to request that a particular IP address be assigned
    Ipv4Address subnetMask; // client's subnet mask
    Ipv4Address router[]; // IP addresses for routers on the client's subnet
    Ipv4Address dns[]; // list of DNSs available to the client
    Ipv4Address ntp[]; // list of IP addresses indicating NTP servers available to the client
    Ipv4Address serverIdentifier; // client use this field as the destination address for any unicast DHCP messages to the server
    simtime_t renewalTime; // time interval (T1) from address assignment until the client transitions to the RENEWING state
    simtime_t rebindingTime; // time interval (T2) from address assignment until the client transitions to the REBINDING state
    simtime_t leaseTime; // request for lease time (client), offered lease time (server)
}
Constructor & Destructor Documentation
DhcpOptions() [1/2]
inet::DhcpOptions::DhcpOptions ()
DhcpOptions() [2/2]
inet::DhcpOptions::DhcpOptions (const DhcpOptions & other)
~DhcpOptions()
virtual inet::DhcpOptions::~DhcpOptions () virtual
Member Function Documentation
appendDns()
virtual void inet::DhcpOptions::appendDns (const Ipv4Address & dns) virtual
appendNtp()
virtual void inet::DhcpOptions::appendNtp (const Ipv4Address & ntp) virtual
appendParameterRequestList()
virtual void inet::DhcpOptions::appendParameterRequestList (DhcpOptionCode parameterRequestList) virtual
appendRouter()
virtual void inet::DhcpOptions::appendRouter (const Ipv4Address & router) virtual
copy()
void inet::DhcpOptions::copy (const DhcpOptions & other) private
dup()
virtual DhcpOptions* inet::DhcpOptions::dup () const inline override virtual
 {return new DhcpOptions(*this);}
eraseDns()
virtual void inet::DhcpOptions::eraseDns (size_t k) virtual
eraseNtp()
virtual void inet::DhcpOptions::eraseNtp (size_t k) virtual
eraseParameterRequestList()
virtual void inet::DhcpOptions::eraseParameterRequestList (size_t k) virtual
eraseRouter()
virtual void inet::DhcpOptions::eraseRouter (size_t k) virtual
getClientIdentifier()
virtual const MacAddress& inet::DhcpOptions::getClientIdentifier () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getClientIdentifierForUpdate()
virtual MacAddress& inet::DhcpOptions::getClientIdentifierForUpdate () inline virtual
 { return const_cast<MacAddress&>(const_cast<DhcpOptions*>(this)->getClientIdentifier());}
getDns()
virtual const Ipv4Address& inet::DhcpOptions::getDns (size_t k) const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getDnsArraySize()
virtual size_t inet::DhcpOptions::getDnsArraySize () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getDnsForUpdate()
virtual Ipv4Address& inet::DhcpOptions::getDnsForUpdate (size_t k) inline virtual
 { return const_cast<Ipv4Address&>(const_cast<DhcpOptions*>(this)->getDns(k));}
getHostName()
virtual const char* inet::DhcpOptions::getHostName () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getLeaseTime()
virtual ::omnetpp::simtime_t inet::DhcpOptions::getLeaseTime () const
Referenced by inet::DhcpMessageSerializer::serialize().
getMessageType()
virtual DhcpMessageType inet::DhcpOptions::getMessageType () const virtual
Referenced by inet::DhcpClient::handleDhcpMessage(), and inet::DhcpMessageSerializer::serialize().
getNtp()
virtual const Ipv4Address& inet::DhcpOptions::getNtp (size_t k) const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getNtpArraySize()
virtual size_t inet::DhcpOptions::getNtpArraySize () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getNtpForUpdate()
virtual Ipv4Address& inet::DhcpOptions::getNtpForUpdate (size_t k) inline virtual
 { return const_cast<Ipv4Address&>(const_cast<DhcpOptions*>(this)->getNtp(k));}
getParameterRequestList()
virtual DhcpOptionCode inet::DhcpOptions::getParameterRequestList (size_t k) const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getParameterRequestListArraySize()
virtual size_t inet::DhcpOptions::getParameterRequestListArraySize () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getRebindingTime()
virtual ::omnetpp::simtime_t inet::DhcpOptions::getRebindingTime () const
Referenced by inet::DhcpMessageSerializer::serialize().
getRenewalTime()
virtual ::omnetpp::simtime_t inet::DhcpOptions::getRenewalTime () const
Referenced by inet::DhcpMessageSerializer::serialize().
getRequestedIp()
virtual const Ipv4Address& inet::DhcpOptions::getRequestedIp () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getRequestedIpForUpdate()
virtual Ipv4Address& inet::DhcpOptions::getRequestedIpForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<DhcpOptions*>(this)->getRequestedIp());}
getRouter()
virtual const Ipv4Address& inet::DhcpOptions::getRouter (size_t k) const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getRouterArraySize()
virtual size_t inet::DhcpOptions::getRouterArraySize () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getRouterForUpdate()
virtual Ipv4Address& inet::DhcpOptions::getRouterForUpdate (size_t k) inline virtual
 { return const_cast<Ipv4Address&>(const_cast<DhcpOptions*>(this)->getRouter(k));}
getServerIdentifier()
virtual const Ipv4Address& inet::DhcpOptions::getServerIdentifier () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getServerIdentifierForUpdate()
virtual Ipv4Address& inet::DhcpOptions::getServerIdentifierForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<DhcpOptions*>(this)->getServerIdentifier());}
getSubnetMask()
virtual const Ipv4Address& inet::DhcpOptions::getSubnetMask () const virtual
Referenced by inet::DhcpMessageSerializer::serialize().
getSubnetMaskForUpdate()
virtual Ipv4Address& inet::DhcpOptions::getSubnetMaskForUpdate () inline virtual
 { return const_cast<Ipv4Address&>(const_cast<DhcpOptions*>(this)->getSubnetMask());}
insertDns() [1/2]
void inet::DhcpOptions::insertDns (const Ipv4Address & dns) inline
 {appendDns(dns);}
insertDns() [2/2]
virtual void inet::DhcpOptions::insertDns (size_t k, const Ipv4Address & dns) virtual
insertNtp() [1/2]
void inet::DhcpOptions::insertNtp (const Ipv4Address & ntp) inline
 {appendNtp(ntp);}
insertNtp() [2/2]
virtual void inet::DhcpOptions::insertNtp (size_t k, const Ipv4Address & ntp) virtual
insertParameterRequestList() [1/2]
void inet::DhcpOptions::insertParameterRequestList (DhcpOptionCode parameterRequestList) inline
 {appendParameterRequestList(parameterRequestList);}
insertParameterRequestList() [2/2]
virtual void inet::DhcpOptions::insertParameterRequestList (size_t k, DhcpOptionCode parameterRequestList) virtual
insertRouter() [1/2]
void inet::DhcpOptions::insertRouter (const Ipv4Address & router) inline
 {appendRouter(router);}
insertRouter() [2/2]
virtual void inet::DhcpOptions::insertRouter (size_t k, const Ipv4Address & router) virtual
operator=()
DhcpOptions& inet::DhcpOptions::operator= (const DhcpOptions & other)
operator==()
bool inet::DhcpOptions::operator== (const DhcpOptions &) protected delete
parsimPack()
virtual void inet::DhcpOptions::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::DhcpOptions::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setClientIdentifier()
virtual void inet::DhcpOptions::setClientIdentifier (const MacAddress & clientIdentifier) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setDns()
virtual void inet::DhcpOptions::setDns (size_t k, const Ipv4Address & dns) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setDnsArraySize()
virtual void inet::DhcpOptions::setDnsArraySize (size_t size) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setHostName()
virtual void inet::DhcpOptions::setHostName (const char * hostName) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setLeaseTime()
virtual void inet::DhcpOptions::setLeaseTime (::omnetpp::simtime_t leaseTime) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setMessageType()
virtual void inet::DhcpOptions::setMessageType (DhcpMessageType messageType) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setNtp()
virtual void inet::DhcpOptions::setNtp (size_t k, const Ipv4Address & ntp) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setNtpArraySize()
virtual void inet::DhcpOptions::setNtpArraySize (size_t size) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setParameterRequestList()
virtual void inet::DhcpOptions::setParameterRequestList (size_t k, DhcpOptionCode parameterRequestList) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setParameterRequestListArraySize()
virtual void inet::DhcpOptions::setParameterRequestListArraySize (size_t size) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setRebindingTime()
virtual void inet::DhcpOptions::setRebindingTime (::omnetpp::simtime_t rebindingTime) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setRenewalTime()
virtual void inet::DhcpOptions::setRenewalTime (::omnetpp::simtime_t renewalTime) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setRequestedIp()
virtual void inet::DhcpOptions::setRequestedIp (const Ipv4Address & requestedIp) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setRouter()
virtual void inet::DhcpOptions::setRouter (size_t k, const Ipv4Address & router) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setRouterArraySize()
virtual void inet::DhcpOptions::setRouterArraySize (size_t size) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setServerIdentifier()
virtual void inet::DhcpOptions::setServerIdentifier (const Ipv4Address & serverIdentifier) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
setSubnetMask()
virtual void inet::DhcpOptions::setSubnetMask (const Ipv4Address & subnetMask) virtual
Referenced by inet::DhcpMessageSerializer::deserialize().
Member Data Documentation
clientIdentifier
MacAddress inet::DhcpOptions::clientIdentifier protected
dns
Ipv4Address* inet::DhcpOptions::dns = nullptr protected
dns_arraysize
size_t inet::DhcpOptions::dns_arraysize = 0 protected
hostName
::omnetpp::opp_string inet::DhcpOptions::hostName protected
leaseTime
::omnetpp::simtime_t inet::DhcpOptions::leaseTime = SIMTIME_ZERO protected
messageType
DhcpMessageType inet::DhcpOptions::messageType = static_cast<inet::DhcpMessageType>(-1) protected
ntp
Ipv4Address* inet::DhcpOptions::ntp = nullptr protected
ntp_arraysize
size_t inet::DhcpOptions::ntp_arraysize = 0 protected
parameterRequestList
DhcpOptionCode* inet::DhcpOptions::parameterRequestList = nullptr protected
parameterRequestList_arraysize
size_t inet::DhcpOptions::parameterRequestList_arraysize = 0 protected
rebindingTime
::omnetpp::simtime_t inet::DhcpOptions::rebindingTime = SIMTIME_ZERO protected
renewalTime
::omnetpp::simtime_t inet::DhcpOptions::renewalTime = SIMTIME_ZERO protected
requestedIp
Ipv4Address inet::DhcpOptions::requestedIp protected
router
Ipv4Address* inet::DhcpOptions::router = nullptr protected
router_arraysize
size_t inet::DhcpOptions::router_arraysize = 0 protected
serverIdentifier
Ipv4Address inet::DhcpOptions::serverIdentifier protected
subnetMask
Ipv4Address inet::DhcpOptions::subnetMask protected
The documentation for this class was generated from the following file:
DhcpMessage_m.h