INET Framework for OMNeT++/OMNEST: inet::sctp::SctpHeartbeatAckChunk Class Reference
inet::sctp::SctpHeartbeatAckChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:199 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpHeartbeatAckChunk (const char *name=nullptr)
SctpHeartbeatAckChunk (const SctpHeartbeatAckChunk &other)
virtual ~SctpHeartbeatAckChunk ()
SctpHeartbeatAckChunk & operator= (const SctpHeartbeatAckChunk &other)
virtual SctpHeartbeatAckChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::L3Address & getRemoteAddr () const
virtual ::inet::L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const ::inet::L3Address &remoteAddr)
virtual ::omnetpp::simtime_t getTimeField () const
virtual void setTimeField (::omnetpp::simtime_t timeField)
virtual void setInfoArraySize (size_t size)
virtual size_t getInfoArraySize () const
virtual char getInfo (size_t k) const
virtual void setInfo (size_t k, char info)
virtual void insertInfo (size_t k, char info)
void insertInfo (char info)
virtual void appendInfo (char info)
virtual void eraseInfo (size_t k)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpHeartbeatAckChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
::inet::L3Address remoteAddr
::omnetpp::simtime_t timeField = SIMTIME_ZERO
char * info = nullptr
size_t info_arraysize = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpHeartbeatAckChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:199 by opp_msgtool.
class SctpHeartbeatAckChunk extends SctpChunk
{
    L3Address remoteAddr;
    simtime_t timeField;
    char info[];
}
Constructor & Destructor Documentation
SctpHeartbeatAckChunk() [1/2]
inet::sctp::SctpHeartbeatAckChunk::SctpHeartbeatAckChunk (const char * name = nullptr)
SctpHeartbeatAckChunk() [2/2]
inet::sctp::SctpHeartbeatAckChunk::SctpHeartbeatAckChunk (const SctpHeartbeatAckChunk & other)
~SctpHeartbeatAckChunk()
virtual inet::sctp::SctpHeartbeatAckChunk::~SctpHeartbeatAckChunk () virtual
Member Function Documentation
appendInfo()
virtual void inet::sctp::SctpHeartbeatAckChunk::appendInfo (char info) virtual
copy()
void inet::sctp::SctpHeartbeatAckChunk::copy (const SctpHeartbeatAckChunk & other) private
dup()
virtual SctpHeartbeatAckChunk* inet::sctp::SctpHeartbeatAckChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpHeartbeatAckChunk(*this);}
eraseInfo()
virtual void inet::sctp::SctpHeartbeatAckChunk::eraseInfo (size_t k) virtual
getInfo()
virtual char inet::sctp::SctpHeartbeatAckChunk::getInfo (size_t k) const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getInfoArraySize()
virtual size_t inet::sctp::SctpHeartbeatAckChunk::getInfoArraySize () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getRemoteAddr()
virtual const ::inet::L3Address& inet::sctp::SctpHeartbeatAckChunk::getRemoteAddr () const virtual
Referenced by inet::sctp::SctpAssociation::processHeartbeatAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getRemoteAddrForUpdate()
virtual ::inet::L3Address& inet::sctp::SctpHeartbeatAckChunk::getRemoteAddrForUpdate () inline
 { return const_cast<::inet::L3Address&>(const_cast<SctpHeartbeatAckChunk*>(this)->getRemoteAddr());}
getTimeField()
virtual ::omnetpp::simtime_t inet::sctp::SctpHeartbeatAckChunk::getTimeField () const
Referenced by inet::sctp::SctpAssociation::processHeartbeatAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
insertInfo() [1/2]
void inet::sctp::SctpHeartbeatAckChunk::insertInfo (char info) inline
 {appendInfo(info);}
insertInfo() [2/2]
virtual void inet::sctp::SctpHeartbeatAckChunk::insertInfo (size_t k, char info) virtual
operator=()
SctpHeartbeatAckChunk& inet::sctp::SctpHeartbeatAckChunk::operator= (const SctpHeartbeatAckChunk & other)
operator==()
bool inet::sctp::SctpHeartbeatAckChunk::operator== (const SctpHeartbeatAckChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpHeartbeatAckChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpHeartbeatAckChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setInfo()
virtual void inet::sctp::SctpHeartbeatAckChunk::setInfo (size_t k, char info) virtual
Referenced by inet::sctp::SctpAssociation::sendHeartbeatAck().
setInfoArraySize()
virtual void inet::sctp::SctpHeartbeatAckChunk::setInfoArraySize (size_t size) virtual
Referenced by inet::sctp::SctpAssociation::sendHeartbeatAck().
setRemoteAddr()
virtual void inet::sctp::SctpHeartbeatAckChunk::setRemoteAddr (const ::inet::L3Address & remoteAddr) virtual
Referenced by inet::sctp::SctpAssociation::sendHeartbeatAck().
setTimeField()
virtual void inet::sctp::SctpHeartbeatAckChunk::setTimeField (::omnetpp::simtime_t timeField) virtual
Referenced by inet::sctp::SctpAssociation::sendHeartbeatAck().
Member Data Documentation
info
char* inet::sctp::SctpHeartbeatAckChunk::info = nullptr protected
info_arraysize
size_t inet::sctp::SctpHeartbeatAckChunk::info_arraysize = 0 protected
remoteAddr
::inet::L3Address inet::sctp::SctpHeartbeatAckChunk::remoteAddr protected
timeField
::omnetpp::simtime_t inet::sctp::SctpHeartbeatAckChunk::timeField = SIMTIME_ZERO protected
The documentation for this class was generated from the following file:
SctpHeader_m.h