INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAsconfChunk Class Reference
inet::sctp::SctpAsconfChunk Class Reference
#include <SctpHeader.h>
Public Member Functions
SctpAsconfChunk (const char *name=nullptr, int32_t kind=0)
SctpAsconfChunk (const SctpAsconfChunk &other)
SctpAsconfChunk & operator= (const SctpAsconfChunk &other)
virtual SctpAsconfChunk * dup () const override
virtual void setAsconfParamsArraySize (size_t size) override
virtual size_t getAsconfParamsArraySize () const override
virtual const SctpParameter * getAsconfParams (size_t k) const override
Returns the kth parameter in this SCTP Reset Chunk.
virtual void setAsconfParams (size_t k, SctpParameter *asconfParams) override
Generated but unused method, should not be called.
virtual void appendAsconfParams (SctpParameter *asconfParams) override
virtual void insertAsconfParams (size_t k, SctpParameter *asconfParams) override
virtual void eraseAsconfParams (size_t k) override
virtual void addAsconfParam (SctpParameter *msg)
Adds a message object to the SCTP packet.
virtual SctpParameter * removeAsconfParam ()
Removes and returns the first message object in this SCTP packet.
virtual void insertAsconfParams (size_t k, SctpParameter *asconfParams)=0
void insertAsconfParams (SctpParameter *asconfParams)
Public Member Functions inherited from inet::sctp::SctpAsconfChunk_Base
virtual ~SctpAsconfChunk_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSerialNumber () const
virtual void setSerialNumber (uint32_t serialNumber)
virtual const ::inet::L3Address & getAddressParam () const
virtual ::inet::L3Address & getAddressParamForUpdate ()
virtual void setAddressParam (const ::inet::L3Address &addressParam)
virtual uint32_t getPeerVTag () const
virtual void setPeerVTag (uint32_t peerVTag)
virtual SctpParameter * getAsconfParamsForUpdate (size_t k)
void insertAsconfParams (SctpParameter *asconfParams)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Attributes
std::vector< SctpParameter * > parameterList
Protected Attributes inherited from inet::sctp::SctpAsconfChunk_Base
uint32_t serialNumber = 0
::inet::L3Address addressParam
uint32_t peerVTag = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Additional Inherited Members
Protected Member Functions inherited from inet::sctp::SctpAsconfChunk_Base
bool operator== (const SctpAsconfChunk_Base &)=delete
SctpAsconfChunk_Base (const char *name=nullptr)
SctpAsconfChunk_Base (const SctpAsconfChunk_Base &other)
SctpAsconfChunk_Base & operator= (const SctpAsconfChunk_Base &other)
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Constructor & Destructor Documentation
SctpAsconfChunk() [1/2]
inet::sctp::SctpAsconfChunk::SctpAsconfChunk (const char * name = nullptr, int32_t kind = 0) inline
 : SctpAsconfChunk_Base() {};
SctpAsconfChunk() [2/2]
inet::sctp::SctpAsconfChunk::SctpAsconfChunk (const SctpAsconfChunk & other) inline
 : SctpAsconfChunk_Base(other) { operator=(other); };
Member Function Documentation
addAsconfParam()
void inet::sctp::SctpAsconfChunk::addAsconfParam (SctpParameter * msg) virtual
Adds a message object to the SCTP packet.
The packet length will be adjusted
 {
     take(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     parameterList.push_back(msg);
 }
Referenced by operator=(), and inet::sctp::SctpAssociation::sendAsconf().
appendAsconfParams()
virtual void inet::sctp::SctpAsconfChunk::appendAsconfParams (SctpParameter * asconfParams) inline override virtual
Implements inet::sctp::SctpAsconfChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
dup()
virtual SctpAsconfChunk* inet::sctp::SctpAsconfChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpAsconfChunk_Base.
 { return new SctpAsconfChunk(*this); }
Referenced by operator=(), inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::retransmitAsconf(), and inet::sctp::SctpAssociation::sendAsconf().
eraseAsconfParams()
virtual void inet::sctp::SctpAsconfChunk::eraseAsconfParams (size_t k) inline override virtual
Implements inet::sctp::SctpAsconfChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
getAsconfParams()
const SctpParameter * inet::sctp::SctpAsconfChunk::getAsconfParams (size_t k) const override virtual
Returns the kth parameter in this SCTP Reset Chunk.
Implements inet::sctp::SctpAsconfChunk_Base.
 {
     return parameterList.at(k);
 }
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
getAsconfParamsArraySize()
size_t inet::sctp::SctpAsconfChunk::getAsconfParamsArraySize () const override virtual
Implements inet::sctp::SctpAsconfChunk_Base.
 {
     return parameterList.size();
 }
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), inet::sctp::SctpAssociation::processAsconfArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
insertAsconfParams() [1/3]
void inet::sctp::SctpAsconfChunk_Base::insertAsconfParams inline
 {appendAsconfParams(asconfParams);}
insertAsconfParams() [2/3]
virtual void inet::sctp::SctpAsconfChunk::insertAsconfParams (size_t k, SctpParameter * asconfParams) inline override virtual
Implements inet::sctp::SctpAsconfChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
insertAsconfParams() [3/3]
virtual void inet::sctp::SctpAsconfChunk_Base::insertAsconfParams
operator=()
SctpAsconfChunk & inet::sctp::SctpAsconfChunk::operator= (const SctpAsconfChunk & other)
 {
     SctpAsconfChunk_Base::operator=(other);
     this->setByteLength(SCTP_ADD_IP_CHUNK_LENGTH + 8);
     this->setAddressParam(other.getAddressParam());
     for (const auto& elem : other.parameterList)
         addAsconfParam((elem)->dup());
     return *this;
 }
removeAsconfParam()
SctpParameter * inet::sctp::SctpAsconfChunk::removeAsconfParam () virtual
Removes and returns the first message object in this SCTP packet.
 {
     if (parameterList.empty())
         return nullptr;
     SctpParameter *msg = parameterList.front();
     parameterList.erase(parameterList.begin());
     drop(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     return msg;
 }
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpAssociation::processAsconfArrived().
setAsconfParams()
void inet::sctp::SctpAsconfChunk::setAsconfParams (size_t k, SctpParameter * asconfParams) override virtual
Generated but unused method, should not be called.
Implements inet::sctp::SctpAsconfChunk_Base.
 {
     throw cException(this, "setAsconfParams() not supported, use addAsconfParam()");
 }
setAsconfParamsArraySize()
void inet::sctp::SctpAsconfChunk::setAsconfParamsArraySize (size_t size) override virtual
Implements inet::sctp::SctpAsconfChunk_Base.
 {
     throw cException(this, "setAsconfParamsArraySize() not supported, use addAsconfParam()");
 }
Member Data Documentation
parameterList
std::vector<SctpParameter *> inet::sctp::SctpAsconfChunk::parameterList protected
Referenced by addAsconfParam(), getAsconfParams(), getAsconfParamsArraySize(), operator=(), and removeAsconfParam().
The documentation for this class was generated from the following files:
SctpHeader.h
SctpHeader.cc