INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRecoveryProcedure Class Reference
inet::ieee80211::IRecoveryProcedure Class Reference
#include <IRecoveryProcedure.h>
Classes
class ICwCalculator
Public Member Functions
virtual ~IRecoveryProcedure ()
Static Public Attributes
static simsignal_t contentionWindowChangedSignal = cComponent::registerSignal("contentionWindowChanged")
static simsignal_t retryLimitReachedSignal = cComponent::registerSignal("retryLimitReached")
Constructor & Destructor Documentation
~IRecoveryProcedure()
virtual inet::ieee80211::IRecoveryProcedure::~IRecoveryProcedure () inline virtual
 {}
Member Data Documentation
contentionWindowChangedSignal
simsignal_t inet::ieee80211::IRecoveryProcedure::contentionWindowChangedSignal = cComponent::registerSignal("contentionWindowChanged") static
Referenced by inet::ieee80211::NonQosRecoveryProcedure::incrementContentionWindow(), inet::ieee80211::QosRecoveryProcedure::incrementContentionWindow(), inet::ieee80211::NonQosRecoveryProcedure::initialize(), inet::ieee80211::QosRecoveryProcedure::initialize(), inet::ieee80211::NonQosRecoveryProcedure::resetContentionWindow(), and inet::ieee80211::QosRecoveryProcedure::resetContentionWindow().
retryLimitReachedSignal
simsignal_t inet::ieee80211::IRecoveryProcedure::retryLimitReachedSignal = cComponent::registerSignal("retryLimitReached") static
Referenced by inet::ieee80211::NonQosRecoveryProcedure::retryLimitReached(), and inet::ieee80211::QosRecoveryProcedure::retryLimitReached().
The documentation for this class was generated from the following files:
IRecoveryProcedure.h
IRecoveryProcedure.cc