INET Framework for OMNeT++/OMNEST: inet::queueing::QueueBasedTokenGenerator Class Reference
inet::queueing::QueueBasedTokenGenerator Class Reference
#include <QueueBasedTokenGenerator.h>
Public Member Functions
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *object, cObject *details) override
Public Member Functions inherited from inet::queueing::TokenGeneratorBase
virtual const char * resolveDirective (char directive) const override
Public Member Functions inherited from inet::queueing::PacketProcessorBase
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Protected Member Functions
virtual void initialize (int stage) override
virtual void generateTokens ()
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
virtual void updateDisplayString () const
Protected Attributes
int minNumPackets = -1
b minTotalLength = b(-1)
ModuleRefByPar< IPacketQueue > queue
cPar * numTokensParameter = nullptr
Protected Attributes inherited from inet::queueing::TokenGeneratorBase
ModuleRefByPar< ITokenStorage > storage
int numTokensGenerated = -1
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Additional Inherited Members
Static Public Attributes inherited from inet::queueing::TokenGeneratorBase
static simsignal_t tokensCreatedSignal = cComponent::registerSignal("tokensCreated")
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Member Function Documentation
generateTokens()
void inet::queueing::QueueBasedTokenGenerator::generateTokens () protected virtual
 {
     auto numTokens = numTokensParameter->doubleValue();
     numTokensGenerated += numTokens;
     emit(tokensCreatedSignal, numTokens);
     storage->addTokens(numTokens);
     updateDisplayString();
 }
Referenced by initialize(), and receiveSignal().
initialize()
void inet::queueing::QueueBasedTokenGenerator::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::TokenGeneratorBase.
 {
     TokenGeneratorBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         minNumPackets = par("minNumPackets");
         minTotalLength = b(par("minTotalLength"));
         queue.reference(this, "queueModule", true);
         check_and_cast<cSimpleModule *>(queue.get())->subscribe(packetPulledSignal, this);
         numTokensParameter = &par("numTokens");
     }
     else if (stage == INITSTAGE_QUEUEING)
         if (queue->getNumPackets() < minNumPackets || queue->getTotalLength() < minTotalLength)
             generateTokens();
 }
receiveSignal()
void inet::queueing::QueueBasedTokenGenerator::receiveSignal (cComponent * source, simsignal_t signal, cObject * object, cObject * details) override virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == packetPulledSignal) {
         Enter_Method("packetPulled");
         if (queue->getNumPackets() < minNumPackets || queue->getTotalLength() < minTotalLength)
             generateTokens();
     }
     else
         throw cRuntimeError("Unknown signal");
 }
supportsPacketPulling()
virtual bool inet::queueing::QueueBasedTokenGenerator::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Reimplemented from inet::queueing::TokenGeneratorBase.
 { return false; }
supportsPacketPushing()
virtual bool inet::queueing::QueueBasedTokenGenerator::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Reimplemented from inet::queueing::TokenGeneratorBase.
 { return false; }
Member Data Documentation
minNumPackets
int inet::queueing::QueueBasedTokenGenerator::minNumPackets = -1 protected
Referenced by initialize(), and receiveSignal().
minTotalLength
b inet::queueing::QueueBasedTokenGenerator::minTotalLength = b(-1) protected
Referenced by initialize(), and receiveSignal().
numTokensParameter
cPar* inet::queueing::QueueBasedTokenGenerator::numTokensParameter = nullptr protected
Referenced by generateTokens(), and initialize().
queue
ModuleRefByPar<IPacketQueue> inet::queueing::QueueBasedTokenGenerator::queue protected
Referenced by initialize(), and receiveSignal().
The documentation for this class was generated from the following files:
QueueBasedTokenGenerator.h
QueueBasedTokenGenerator.cc