INET Framework for OMNeT++/OMNEST: EigrpTimer Class Reference
EigrpTimer Class Reference
Class generated from inet/routing/eigrp/EigrpTimer.msg:22 by opp_msgtool.
#include <EigrpTimer_m.h>
Public Member Functions
EigrpTimer (const char *name=nullptr, short kind=0)
EigrpTimer (const EigrpTimer &other)
virtual ~EigrpTimer ()
EigrpTimer & operator= (const EigrpTimer &other)
virtual EigrpTimer * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual char getTimerKind () const
virtual void setTimerKind (char timerKind)
Protected Member Functions
bool operator== (const EigrpTimer &)=delete
Protected Attributes
char timerKind = 0
Private Member Functions
void copy (const EigrpTimer &other)
Detailed Description
Class generated from inet/routing/eigrp/EigrpTimer.msg:22 by opp_msgtool.
// general timer structure
message EigrpTimer
{
    char timerKind @enum(EigrpTimerType);
}
Constructor & Destructor Documentation
EigrpTimer() [1/2]
EigrpTimer::EigrpTimer (const char * name = nullptr, short kind = 0)
EigrpTimer() [2/2]
EigrpTimer::EigrpTimer (const EigrpTimer & other)
~EigrpTimer()
virtual EigrpTimer::~EigrpTimer () virtual
Member Function Documentation
copy()
void EigrpTimer::copy (const EigrpTimer & other) private
dup()
virtual EigrpTimer* EigrpTimer::dup () const inline override virtual
 {return new EigrpTimer(*this);}
getTimerKind()
virtual char EigrpTimer::getTimerKind () const virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::processTimer(), and inet::eigrp::EigrpIpv6Pdm::processTimer().
operator=()
EigrpTimer& EigrpTimer::operator= (const EigrpTimer & other)
operator==()
bool EigrpTimer::operator== (const EigrpTimer &) protected delete
parsimPack()
virtual void EigrpTimer::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by doParsimPacking().
parsimUnpack()
virtual void EigrpTimer::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by doParsimUnpacking().
setTimerKind()
virtual void EigrpTimer::setTimerKind (char timerKind) virtual
Referenced by inet::eigrp::EigrpIpv4Pdm::createTimer(), and inet::eigrp::EigrpIpv6Pdm::createTimer().
Member Data Documentation
timerKind
char EigrpTimer::timerKind = 0 protected
The documentation for this class was generated from the following file:
EigrpTimer_m.h