INET Framework for OMNeT++/OMNEST: inet::LengthBasedAggregatorPolicy Class Reference
inet::LengthBasedAggregatorPolicy Class Reference
#include <LengthBasedAggregatorPolicy.h>
Public Member Functions
virtual bool isAggregatablePacket (Packet *aggregatedPacket, std::vector< Packet * > &aggregatedSubpackets, Packet *newSubpacket) override
Protected Member Functions
virtual void initialize (int stage) override
Protected Attributes
int minNumSubpackets = -1
int maxNumSubpackets = -1
b minAggregatedLength = b(-1)
b maxAggregatedLength = b(-1)
Member Function Documentation
initialize()
void inet::LengthBasedAggregatorPolicy::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         minNumSubpackets = par("minNumSubpackets");
         maxNumSubpackets = par("maxNumSubpackets");
         minAggregatedLength = b(par("minAggregatedLength"));
         maxAggregatedLength = b(par("maxAggregatedLength"));
     }
 }
isAggregatablePacket()
bool inet::LengthBasedAggregatorPolicy::isAggregatablePacket (Packet * aggregatedPacket, std::vector< Packet * > & aggregatedSubpackets, Packet * newSubpacket) override virtual
Implements inet::IAggregatorPolicy.
 {
 //    b aggregatedLength = aggregatedPacket == nullptr ? b(0) : aggregatedPacket->getTotalLength();
     return (int)aggregatedSubpackets.size() < minNumSubpackets ||
            aggregatedPacket->getTotalLength() < minAggregatedLength ||
            ((int)aggregatedSubpackets.size() + 1 <= maxNumSubpackets &&
             aggregatedPacket->getTotalLength() + newSubpacket->getTotalLength() <= maxAggregatedLength);
 }
Member Data Documentation
maxAggregatedLength
b inet::LengthBasedAggregatorPolicy::maxAggregatedLength = b(-1) protected
Referenced by initialize(), and isAggregatablePacket().
maxNumSubpackets
int inet::LengthBasedAggregatorPolicy::maxNumSubpackets = -1 protected
Referenced by initialize(), and isAggregatablePacket().
minAggregatedLength
b inet::LengthBasedAggregatorPolicy::minAggregatedLength = b(-1) protected
Referenced by initialize(), and isAggregatablePacket().
minNumSubpackets
int inet::LengthBasedAggregatorPolicy::minNumSubpackets = -1 protected
Referenced by initialize(), and isAggregatablePacket().
The documentation for this class was generated from the following files:
LengthBasedAggregatorPolicy.h
LengthBasedAggregatorPolicy.cc