INET Framework for OMNeT++/OMNEST: inet::visualizer::StatisticVisualizerBase Class Reference
inet::visualizer::StatisticVisualizerBase Class Reference abstract
#include <StatisticVisualizerBase.h>
Classes
class DirectiveResolver
class LastValueRecorder
class StatisticVisualization
Parameters
bool displayStatistics = false
ModuleFilter sourceFilter
const char * signalName = nullptr
const char * statisticName = nullptr
const char * statisticUnit = nullptr
const char * statisticExpression = nullptr
StringFormat format
std::vector< std::string > units
cFigure::Font font
cFigure::Color textColor
cFigure::Color backgroundColor
double opacity = NaN
Placement placementHint
double placementPriority
std::map< std::pair< int, simsignal_t >, const StatisticVisualization * > statisticVisualizations
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void preDelete (cComponent *root) override
virtual void subscribe ()
virtual void unsubscribe ()
virtual void addResultRecorder (cComponent *source, simsignal_t signal)
virtual LastValueRecorder * getResultRecorder (cComponent *source, simsignal_t signal)
virtual LastValueRecorder * findResultRecorder (cResultListener *resultListener)
virtual std::string getText (const StatisticVisualization *statisticVisualization)
virtual const char * getUnit (cComponent *source)
virtual std::string getRecordingMode ()
virtual StatisticVisualization * createStatisticVisualization (cComponent *source, simsignal_t signal)=0
virtual const StatisticVisualization * getStatisticVisualization (cComponent *source, simsignal_t signal)
virtual void addStatisticVisualization (const StatisticVisualization *statisticVisualization)
virtual void removeStatisticVisualization (const StatisticVisualization *statisticVisualization)
virtual void removeAllStatisticVisualizations ()
virtual void refreshStatisticVisualization (const StatisticVisualization *statisticVisualization)
virtual void processSignal (cComponent *source, simsignal_t signal, std::function< void(cIListener *)> receiveSignal)
virtual void receiveSignal (cComponent *source, simsignal_t signal, bool b, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, intval_t l, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, uintval_t l, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, double d, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, const SimTime &t, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, const char *s, cObject *details) override
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *obj, cObject *details) override
Additional Inherited Members
Protected Member Functions inherited from inet::visualizer::VisualizerBase
virtual int numInitStages () const override
virtual Coord getPosition (const cModule *networkNode) const
virtual Coord getContactPosition (const cModule *networkNode, const Coord &fromPosition, const char *contactMode, double contactSpacing) const
virtual Quaternion getOrientation (const cModule *networkNode) const
virtual void mapChunks (const Ptr< const Chunk > &chunk, const std::function< void(const Ptr< const Chunk > &, int)> &thunk) const
Protected Attributes inherited from inet::visualizer::VisualizerBase
cModule * visualizationTargetModule = nullptr
cModule * visualizationSubjectModule = nullptr
const char * tags = nullptr
Member Function Documentation
addResultRecorder()
void inet::visualizer::StatisticVisualizerBase::addResultRecorder (cComponent * source, simsignal_t signal) protected virtual
 {
     cStatisticBuilder statisticBuilder(getEnvir()->getConfig());
     cProperty statisticTemplateProperty;
     auto recordingMode = getRecordingMode();
     statisticTemplateProperty.addKey("record");
     statisticTemplateProperty.setValue("record", 0, recordingMode.c_str());
     statisticBuilder.addResultRecorders(source, signal, statisticName, &statisticTemplateProperty);
 }
Referenced by processSignal().
addStatisticVisualization()
void inet::visualizer::StatisticVisualizerBase::addStatisticVisualization (const StatisticVisualization * statisticVisualization) protected virtual
Reimplemented in inet::visualizer::StatisticOsgVisualizer, and inet::visualizer::StatisticCanvasVisualizer.
 {
     auto key = std::pair<int, simsignal_t>(statisticVisualization->moduleId, statisticVisualization->signal);
     statisticVisualizations[key] = statisticVisualization;
 }
Referenced by inet::visualizer::StatisticCanvasVisualizer::addStatisticVisualization(), inet::visualizer::StatisticOsgVisualizer::addStatisticVisualization(), and processSignal().
createStatisticVisualization()
virtual StatisticVisualization* inet::visualizer::StatisticVisualizerBase::createStatisticVisualization (cComponent * source, simsignal_t signal) protected pure virtual
Implemented in inet::visualizer::StatisticOsgVisualizer, and inet::visualizer::StatisticCanvasVisualizer.
Referenced by processSignal().
findResultRecorder()
StatisticVisualizerBase::LastValueRecorder * inet::visualizer::StatisticVisualizerBase::findResultRecorder (cResultListener * resultListener) protected virtual
 {
     if (auto resultRecorder = dynamic_cast<StatisticVisualizerBase::LastValueRecorder *>(resultListener)) {
         if (getRecordingMode() == resultRecorder->getRecordingMode() && !strcmp(statisticName, resultRecorder->getStatisticName()))
             return resultRecorder;
         else
             return nullptr;
     }
     else if (auto resultFilter = dynamic_cast<cResultFilter *>(resultListener)) {
         auto delegates = resultFilter->getDelegates();
         for (auto delegate : delegates) {
             auto foundResultFilter = findResultRecorder(delegate);
             if (foundResultFilter != nullptr)
                 return foundResultFilter;
         }
     }
     return nullptr;
 }
Referenced by getResultRecorder().
getRecordingMode()
std::string inet::visualizer::StatisticVisualizerBase::getRecordingMode () protected virtual
 {
     if (*statisticExpression == '\0')
         return "statisticVisualizerLastValueRecorder";
     else
         return std::string("statisticVisualizerLastValueRecorder(") + statisticExpression + std::string(")");
 }
Referenced by addResultRecorder(), and findResultRecorder().
getResultRecorder()
StatisticVisualizerBase::LastValueRecorder * inet::visualizer::StatisticVisualizerBase::getResultRecorder (cComponent * source, simsignal_t signal) protected virtual
 {
     auto listeners = source->getLocalSignalListeners(signal);
     for (auto listener : listeners) {
         if (auto resultListener = dynamic_cast<cResultListener *>(listener)) {
             auto foundResultFilter = findResultRecorder(resultListener);
             if (foundResultFilter != nullptr)
                 return foundResultFilter;
         }
     }
     throw cRuntimeError("Recorder not found for signal '%s'", signalName);
 }
Referenced by processSignal().
getStatisticVisualization()
const StatisticVisualizerBase::StatisticVisualization * inet::visualizer::StatisticVisualizerBase::getStatisticVisualization (cComponent * source, simsignal_t signal) protected virtual
 {
     auto key = std::pair<int, simsignal_t>(source->getId(), signal);
     auto it = statisticVisualizations.find(key);
     return (it == statisticVisualizations.end()) ? nullptr : it->second;
 }
Referenced by processSignal().
getText()
std::string inet::visualizer::StatisticVisualizerBase::getText (const StatisticVisualization * statisticVisualization) protected virtual
 {
     DirectiveResolver directiveResolver(this, statisticVisualization);
     return format.formatString(&directiveResolver);
 }
Referenced by inet::visualizer::StatisticCanvasVisualizer::refreshStatisticVisualization(), and inet::visualizer::StatisticOsgVisualizer::refreshStatisticVisualization().
getUnit()
const char * inet::visualizer::StatisticVisualizerBase::getUnit (cComponent * source) protected virtual
 {
     auto properties = source->getProperties();
     for (int i = 0; i < properties->getNumProperties(); i++) {
         auto property = properties->get(i);
         if (!strcmp(property->getName(), "statistic") && !strcmp(property->getIndex(), statisticName)) {
             auto unit = property->getValue("unit", 0);
             if (unit != nullptr)
                 return unit;
         }
     }
     return statisticUnit;
 }
Referenced by inet::visualizer::StatisticCanvasVisualizer::createStatisticVisualization(), and inet::visualizer::StatisticOsgVisualizer::createStatisticVisualization().
handleParameterChange()
void inet::visualizer::StatisticVisualizerBase::handleParameterChange (const char * name) override protected virtual
 {
     if (!hasGUI()) return;
     if (name != nullptr) {
         if (!strcmp(name, "sourceFilter"))
             sourceFilter.setPattern(par("sourceFilter"));
         else if (!strcmp(name, "format"))
             format.parseFormat(par("format"));
         removeAllStatisticVisualizations();
     }
 }
initialize()
void inet::visualizer::StatisticVisualizerBase::initialize (int stage) override protected virtual
Reimplemented from inet::visualizer::VisualizerBase.
Reimplemented in inet::visualizer::StatisticOsgVisualizer, and inet::visualizer::StatisticCanvasVisualizer.
 {
     VisualizerBase::initialize(stage);
     if (!hasGUI()) return;
     if (stage == INITSTAGE_LOCAL) {
         displayStatistics = par("displayStatistics");
         sourceFilter.setPattern(par("sourceFilter"));
         signalName = par("signalName");
         statisticName = par("statisticName");
         statisticUnit = par("statisticUnit");
         statisticExpression = par("statisticExpression");
         format.parseFormat(par("format"));
         cStringTokenizer tokenizer(par("unit"));
         while (tokenizer.hasMoreTokens())
             units.push_back(tokenizer.nextToken());
         font = cFigure::parseFont(par("font"));
         textColor = cFigure::Color(par("textColor"));
         backgroundColor = cFigure::Color(par("backgroundColor"));
         opacity = par("opacity");
         placementHint = parsePlacement(par("placementHint"));
         placementPriority = par("placementPriority");
         if (displayStatistics)
             subscribe();
     }
 }
Referenced by inet::visualizer::StatisticCanvasVisualizer::initialize(), and inet::visualizer::StatisticOsgVisualizer::initialize().
preDelete()
void inet::visualizer::StatisticVisualizerBase::preDelete (cComponent * root) override protected virtual
 {
     if (displayStatistics) {
         unsubscribe();
         removeAllStatisticVisualizations();
     }
 }
processSignal()
void inet::visualizer::StatisticVisualizerBase::processSignal (cComponent * source, simsignal_t signal, std::function< void(cIListener *)> receiveSignal) protected virtual
 {
     auto statisticVisualization = getStatisticVisualization(source, signal);
     if (statisticVisualization != nullptr)
         refreshStatisticVisualization(statisticVisualization);
     else {
         if (sourceFilter.matches(check_and_cast<cModule *>(source))) {
             auto statisticVisualization = createStatisticVisualization(source, signal);
             addResultRecorder(source, signal);
             statisticVisualization->recorder = getResultRecorder(source, signal);
             auto listeners = source->getLocalSignalListeners(signal);
             receiveSignal(listeners[listeners.size() - 1]);
             addStatisticVisualization(statisticVisualization);
             refreshStatisticVisualization(statisticVisualization);
         }
     }
 }
receiveSignal() [1/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, bool b, cObject * details) inline override virtual
 { PROCESS_SIGNAL(b); }
Referenced by processSignal().
receiveSignal() [2/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, cObject * obj, cObject * details) inline override virtual
 { PROCESS_SIGNAL(obj); }
receiveSignal() [3/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, const char * s, cObject * details) inline override virtual
 { PROCESS_SIGNAL(s); }
receiveSignal() [4/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, const SimTime & t, cObject * details) inline override virtual
 { PROCESS_SIGNAL(t); }
receiveSignal() [5/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, double d, cObject * details) inline override virtual
 { PROCESS_SIGNAL(d); }
receiveSignal() [6/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, intval_t l, cObject * details) inline override virtual
 { PROCESS_SIGNAL(l); }
receiveSignal() [7/7]
virtual void inet::visualizer::StatisticVisualizerBase::receiveSignal (cComponent * source, simsignal_t signal, uintval_t l, cObject * details) inline override virtual
 { PROCESS_SIGNAL(l); }
refreshStatisticVisualization()
void inet::visualizer::StatisticVisualizerBase::refreshStatisticVisualization (const StatisticVisualization * statisticVisualization) protected virtual
Reimplemented in inet::visualizer::StatisticOsgVisualizer, and inet::visualizer::StatisticCanvasVisualizer.
 {
     double value = statisticVisualization->recorder->getLastValue();
     if (std::isnan(value) || units.empty()) {
         statisticVisualization->printValue = value;
         statisticVisualization->printUnit = statisticVisualization->unit == nullptr ? "" : statisticVisualization->unit;
     }
     else {
         for (auto& unit : units) {
             statisticVisualization->printUnit = unit.c_str();
             statisticVisualization->printValue = cNEDValue::convertUnit(value, statisticVisualization->unit, statisticVisualization->printUnit);
             if (statisticVisualization->printValue > 1)
                 break;
         }
     }
 }
Referenced by processSignal(), inet::visualizer::StatisticCanvasVisualizer::refreshStatisticVisualization(), and inet::visualizer::StatisticOsgVisualizer::refreshStatisticVisualization().
removeAllStatisticVisualizations()
void inet::visualizer::StatisticVisualizerBase::removeAllStatisticVisualizations () protected virtual
 {
     std::vector<const StatisticVisualization *> removedStatisticVisualizations;
     for (auto it : statisticVisualizations)
         removedStatisticVisualizations.push_back(it.second);
     for (auto it : removedStatisticVisualizations) {
         removeStatisticVisualization(it);
         delete it;
     }
 }
Referenced by handleParameterChange(), and preDelete().
removeStatisticVisualization()
void inet::visualizer::StatisticVisualizerBase::removeStatisticVisualization (const StatisticVisualization * statisticVisualization) protected virtual
Reimplemented in inet::visualizer::StatisticOsgVisualizer, and inet::visualizer::StatisticCanvasVisualizer.
 {
     auto key = std::pair<int, simsignal_t>(statisticVisualization->moduleId, statisticVisualization->signal);
     statisticVisualizations.erase(statisticVisualizations.find(key));
 }
Referenced by removeAllStatisticVisualizations(), inet::visualizer::StatisticCanvasVisualizer::removeStatisticVisualization(), and inet::visualizer::StatisticOsgVisualizer::removeStatisticVisualization().
subscribe()
void inet::visualizer::StatisticVisualizerBase::subscribe () protected virtual
 {
     if (*signalName != '\0')
         visualizationSubjectModule->subscribe(registerSignal(signalName), this);
 }
Referenced by initialize().
unsubscribe()
void inet::visualizer::StatisticVisualizerBase::unsubscribe () protected virtual
 {
     // NOTE: lookup the module again because it may have been deleted first
     auto visualizationSubjectModule = findModuleFromPar<cModule>(par("visualizationSubjectModule"), this);
     if (visualizationSubjectModule != nullptr) {
         if (*signalName != '\0')
             visualizationSubjectModule->unsubscribe(registerSignal(signalName), this);
     }
 }
Referenced by preDelete().
Member Data Documentation
backgroundColor
cFigure::Color inet::visualizer::StatisticVisualizerBase::backgroundColor protected
Referenced by inet::visualizer::StatisticCanvasVisualizer::createStatisticVisualization(), inet::visualizer::StatisticOsgVisualizer::createStatisticVisualization(), and initialize().
displayStatistics
bool inet::visualizer::StatisticVisualizerBase::displayStatistics = false protected
Referenced by initialize(), and preDelete().
font
cFigure::Font inet::visualizer::StatisticVisualizerBase::font protected
Referenced by inet::visualizer::StatisticCanvasVisualizer::createStatisticVisualization(), and initialize().
format
StringFormat inet::visualizer::StatisticVisualizerBase::format protected
Referenced by getText(), handleParameterChange(), and initialize().
opacity
double inet::visualizer::StatisticVisualizerBase::opacity = NaN protected
Referenced by inet::visualizer::StatisticCanvasVisualizer::createStatisticVisualization(), and initialize().
placementHint
Placement inet::visualizer::StatisticVisualizerBase::placementHint protected
Referenced by inet::visualizer::StatisticCanvasVisualizer::addStatisticVisualization(), and initialize().
placementPriority
double inet::visualizer::StatisticVisualizerBase::placementPriority protected
Referenced by inet::visualizer::StatisticCanvasVisualizer::addStatisticVisualization(), and initialize().
signalName
const char* inet::visualizer::StatisticVisualizerBase::signalName = nullptr protected
Referenced by getResultRecorder(), initialize(), subscribe(), and unsubscribe().
sourceFilter
ModuleFilter inet::visualizer::StatisticVisualizerBase::sourceFilter protected
Referenced by handleParameterChange(), initialize(), and processSignal().
statisticExpression
const char* inet::visualizer::StatisticVisualizerBase::statisticExpression = nullptr protected
Referenced by getRecordingMode(), and initialize().
statisticName
const char* inet::visualizer::StatisticVisualizerBase::statisticName = nullptr protected
Referenced by addResultRecorder(), findResultRecorder(), getUnit(), and initialize().
statisticUnit
const char* inet::visualizer::StatisticVisualizerBase::statisticUnit = nullptr protected
Referenced by getUnit(), and initialize().
statisticVisualizations
std::map<std::pair<int, simsignal_t>, const StatisticVisualization *> inet::visualizer::StatisticVisualizerBase::statisticVisualizations protected
Referenced by addStatisticVisualization(), getStatisticVisualization(), removeAllStatisticVisualizations(), and removeStatisticVisualization().
textColor
cFigure::Color inet::visualizer::StatisticVisualizerBase::textColor protected
Referenced by inet::visualizer::StatisticCanvasVisualizer::createStatisticVisualization(), inet::visualizer::StatisticOsgVisualizer::createStatisticVisualization(), and initialize().
units
std::vector<std::string> inet::visualizer::StatisticVisualizerBase::units protected
Referenced by initialize(), and refreshStatisticVisualization().
The documentation for this class was generated from the following files:
StatisticVisualizerBase.h
StatisticVisualizerBase.cc