INET Framework for OMNeT++/OMNEST: inet::SctpCommandReq Class Reference
inet::SctpCommandReq Class Reference
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:114 by opp_msgtool.
#include <SctpCommand_m.h>
Public Member Functions
SctpCommandReq ()
SctpCommandReq (const SctpCommandReq &other)
virtual ~SctpCommandReq ()
SctpCommandReq & operator= (const SctpCommandReq &other)
virtual SctpCommandReq * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getSocketId () const
virtual void setSocketId (int socketId)
virtual int getSid () const
virtual void setSid (int sid)
virtual int getNumMsgs () const
virtual void setNumMsgs (int numMsgs)
virtual int getSsn () const
virtual void setSsn (int ssn)
virtual unsigned short getSendUnordered () const
virtual void setSendUnordered (unsigned short sendUnordered)
virtual double getPrValue () const
virtual void setPrValue (double prValue)
virtual const L3Address & getLocalAddr () const
virtual L3Address & getLocalAddrForUpdate ()
virtual void setLocalAddr (const L3Address &localAddr)
virtual const L3Address & getRemoteAddr () const
virtual L3Address & getRemoteAddrForUpdate ()
virtual void setRemoteAddr (const L3Address &remoteAddr)
virtual int getLocalPort () const
virtual void setLocalPort (int localPort)
virtual int getRemotePort () const
virtual void setRemotePort (int remotePort)
virtual int getGate () const
virtual void setGate (int gate)
virtual int getFd () const
virtual void setFd (int fd)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const SctpCommandReq &)=delete
Protected Attributes
int socketId = -1
int sid = -1
int numMsgs = 1
int ssn = -1
unsigned short sendUnordered = false
double prValue = 0
L3Address localAddr
L3Address remoteAddr
int localPort = -1
int remotePort = -1
int gate = -1
int fd = -1
Private Member Functions
void copy (const SctpCommandReq &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/transportlayer/contract/sctp/SctpCommand.msg:114 by opp_msgtool.
class SctpCommandReq extends TagBase
{
    int socketId = -1;   // identifies the socket within the application
    int sid = -1;
    int numMsgs = 1;
    int ssn = -1;
    unsigned short sendUnordered = false;
    double prValue = 0;
    L3Address localAddr;
    L3Address remoteAddr;
    int localPort = -1;
    int remotePort = -1;
    int gate = -1;
    int fd = -1;
}
Constructor & Destructor Documentation
SctpCommandReq() [1/2]
inet::SctpCommandReq::SctpCommandReq ()
SctpCommandReq() [2/2]
inet::SctpCommandReq::SctpCommandReq (const SctpCommandReq & other)
~SctpCommandReq()
virtual inet::SctpCommandReq::~SctpCommandReq () virtual
Member Function Documentation
copy()
void inet::SctpCommandReq::copy (const SctpCommandReq & other) private
dup()
virtual SctpCommandReq* inet::SctpCommandReq::dup () const inline override virtual
Reimplemented in inet::SctpSendQueueAbatedReq, inet::SctpRtoReq, inet::SctpPathInfoReq, inet::SctpInfoReq, inet::SctpResetReq, inet::SctpStatusReq, inet::SctpRcvReq, inet::SctpConnectReq, inet::SctpAvailableReq, inet::SctpOpenReq, and inet::SctpSendReq.
 {return new SctpCommandReq(*this);}
getFd()
virtual int inet::SctpCommandReq::getFd () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE(), inet::sctp::SctpAssociation::process_OPEN_PASSIVE(), and inet::sctp::SctpAssociation::processAppCommand().
getGate()
virtual int inet::SctpCommandReq::getGate () const virtual
Referenced by inet::sctp::Sctp::handleMessage().
getLocalAddr()
virtual const L3Address& inet::SctpCommandReq::getLocalAddr () const virtual
getLocalAddrForUpdate()
virtual L3Address& inet::SctpCommandReq::getLocalAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<SctpCommandReq*>(this)->getLocalAddr());}
getLocalPort()
virtual int inet::SctpCommandReq::getLocalPort () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE(), and inet::sctp::SctpAssociation::process_OPEN_PASSIVE().
getNumMsgs()
virtual int inet::SctpCommandReq::getNumMsgs () const virtual
Referenced by inet::SctpServer::makeAbortNotification(), and inet::sctp::SctpAssociation::process_RECEIVE_REQUEST().
getPrValue()
virtual double inet::SctpCommandReq::getPrValue () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
getRemoteAddr()
virtual const L3Address& inet::SctpCommandReq::getRemoteAddr () const virtual
Referenced by inet::sctp::Sctp::handleMessage(), inet::sctp::SctpAssociation::process_ASSOCIATE(), and inet::sctp::SctpAssociation::process_SEND().
getRemoteAddrForUpdate()
virtual L3Address& inet::SctpCommandReq::getRemoteAddrForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<SctpCommandReq*>(this)->getRemoteAddr());}
getRemotePort()
virtual int inet::SctpCommandReq::getRemotePort () const virtual
Referenced by inet::sctp::SctpAssociation::process_ASSOCIATE().
getSendUnordered()
virtual unsigned short inet::SctpCommandReq::getSendUnordered () const virtual
Referenced by inet::sctp::SctpAssociation::process_SEND().
getSid()
virtual int inet::SctpCommandReq::getSid () const virtual
Referenced by inet::SctpServer::makeAbortNotification(), inet::sctp::SctpAssociation::process_RECEIVE_REQUEST(), inet::sctp::SctpAssociation::process_SEND(), and inet::NetPerfMeter::receiveMessage().
getSocketId()
virtual int inet::SctpCommandReq::getSocketId () const virtual
Referenced by inet::SctpNatServer::handleMessage(), inet::SctpServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), and inet::SctpServer::makeAbortNotification().
getSsn()
virtual int inet::SctpCommandReq::getSsn () const virtual
operator=()
SctpCommandReq& inet::SctpCommandReq::operator= (const SctpCommandReq & other)
operator==()
bool inet::SctpCommandReq::operator== (const SctpCommandReq &) protected delete
parsimPack()
virtual void inet::SctpCommandReq::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::SctpSendQueueAbatedReq, inet::SctpRtoReq, inet::SctpPathInfoReq, inet::SctpInfoReq, inet::SctpResetReq, inet::SctpStatusReq, inet::SctpRcvReq, inet::SctpConnectReq, inet::SctpAvailableReq, inet::SctpOpenReq, and inet::SctpSendReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::SctpCommandReq::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::SctpSendQueueAbatedReq, inet::SctpRtoReq, inet::SctpPathInfoReq, inet::SctpInfoReq, inet::SctpResetReq, inet::SctpStatusReq, inet::SctpRcvReq, inet::SctpConnectReq, inet::SctpAvailableReq, inet::SctpOpenReq, and inet::SctpSendReq.
Referenced by inet::doParsimUnpacking().
setFd()
virtual void inet::SctpCommandReq::setFd (int fd) virtual
setGate()
virtual void inet::SctpCommandReq::setGate (int gate) virtual
setLocalAddr()
virtual void inet::SctpCommandReq::setLocalAddr (const L3Address & localAddr) virtual
setLocalPort()
virtual void inet::SctpCommandReq::setLocalPort (int localPort) virtual
Referenced by inet::SctpSocket::accept().
setNumMsgs()
virtual void inet::SctpCommandReq::setNumMsgs (int numMsgs) virtual
setPrValue()
virtual void inet::SctpCommandReq::setPrValue (double prValue) virtual
setRemoteAddr()
virtual void inet::SctpCommandReq::setRemoteAddr (const L3Address & remoteAddr) virtual
setRemotePort()
virtual void inet::SctpCommandReq::setRemotePort (int remotePort) virtual
setSendUnordered()
virtual void inet::SctpCommandReq::setSendUnordered (unsigned short sendUnordered) virtual
Referenced by inet::SctpNatPeer::handleMessage().
setSid()
virtual void inet::SctpCommandReq::setSid (int sid) virtual
setSocketId()
virtual void inet::SctpCommandReq::setSocketId (int socketId) virtual
Referenced by inet::SctpSocket::abort(), inet::SctpSocket::close(), inet::SctpSocket::connect(), inet::SctpSocket::destroy(), inet::SctpNatServer::generateAndSend(), inet::sctp::SctpAssociation::generateSendQueueAbatedIndication(), inet::SctpSocket::getSocketOptions(), inet::NetPerfMeter::handleMessage(), inet::SctpNatServer::handleMessage(), inet::SctpServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::sctp::Sctp::handleMessage(), inet::SctpServer::makeDefaultReceive(), inet::SctpServer::makeReceiveRequest(), inet::SctpSocket::requestStatus(), inet::SctpSocket::send(), inet::sctp::SctpAssociation::sendAvailableIndicationToApp(), inet::sctp::SctpAssociation::sendDataArrivedNotification(), inet::sctp::SctpAssociation::sendEstabIndicationToApp(), inet::sctp::SctpAssociation::sendIndicationToApp(), inet::SctpNatServer::sendInfo(), inet::SctpClient::sendStreamResetNotification(), inet::SctpSocket::setRtoInfo(), inet::SctpSocket::setStreamPriority(), inet::SctpSocket::shutdown(), inet::SctpClient::shutdownReceivedArrived(), inet::SctpPeer::shutdownReceivedArrived(), inet::SctpNatPeer::shutdownReceivedArrived(), inet::SctpClient::socketDataNotificationArrived(), inet::SctpPeer::socketDataNotificationArrived(), inet::SctpNatPeer::socketDataNotificationArrived(), inet::SctpNatPeer::socketEstablished(), and inet::NetPerfMeter::transmitFrame().
setSsn()
virtual void inet::SctpCommandReq::setSsn (int ssn) virtual
Member Data Documentation
fd
int inet::SctpCommandReq::fd = -1 protected
gate
int inet::SctpCommandReq::gate = -1 protected
localAddr
L3Address inet::SctpCommandReq::localAddr protected
localPort
int inet::SctpCommandReq::localPort = -1 protected
numMsgs
int inet::SctpCommandReq::numMsgs = 1 protected
prValue
double inet::SctpCommandReq::prValue = 0 protected
remoteAddr
L3Address inet::SctpCommandReq::remoteAddr protected
remotePort
int inet::SctpCommandReq::remotePort = -1 protected
sendUnordered
unsigned short inet::SctpCommandReq::sendUnordered = false protected
sid
int inet::SctpCommandReq::sid = -1 protected
socketId
int inet::SctpCommandReq::socketId = -1 protected
ssn
int inet::SctpCommandReq::ssn = -1 protected
The documentation for this class was generated from the following file:
SctpCommand_m.h