INET Framework for OMNeT++/OMNEST: inet::physicallayer::IIeee80211HeaderMode Class Reference
inet::physicallayer::IIeee80211HeaderMode Class Reference abstract
#include <IIeee80211Mode.h>
Public Member Functions
virtual bps getNetBitrate () const =0
virtual bps getGrossBitrate () const =0
virtual b getLength () const =0
virtual const simtime_t getDuration () const =0
virtual const IModulation * getModulation () const =0
virtual Ptr< Ieee80211PhyHeader > createHeader () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
createHeader()
virtual Ptr<Ieee80211PhyHeader> inet::physicallayer::IIeee80211HeaderMode::createHeader () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtSignalMode, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::Ieee80211VhtSignalMode, inet::physicallayer::Ieee80211HrDsssHeaderMode, inet::physicallayer::Ieee80211IrHeaderMode, inet::physicallayer::Ieee80211DsssHeaderMode, and inet::physicallayer::Ieee80211FhssHeaderMode.
getDuration()
virtual const simtime_t inet::physicallayer::IIeee80211HeaderMode::getDuration () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtSignalMode, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::Ieee80211VhtSignalMode, inet::physicallayer::Ieee80211HrDsssHeaderMode, inet::physicallayer::Ieee80211IrHeaderMode, inet::physicallayer::Ieee80211DsssHeaderMode, and inet::physicallayer::Ieee80211FhssHeaderMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
getGrossBitrate()
virtual bps inet::physicallayer::IIeee80211HeaderMode::getGrossBitrate () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtSignalMode, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::Ieee80211VhtSignalMode, inet::physicallayer::Ieee80211HrDsssHeaderMode, inet::physicallayer::Ieee80211IrHeaderMode, inet::physicallayer::Ieee80211DsssHeaderMode, and inet::physicallayer::Ieee80211FhssHeaderMode.
getLength()
virtual b inet::physicallayer::IIeee80211HeaderMode::getLength () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtSignalMode, inet::physicallayer::Ieee80211VhtSignalMode, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::Ieee80211HrDsssHeaderMode, inet::physicallayer::Ieee80211IrHeaderMode, inet::physicallayer::Ieee80211DsssHeaderMode, and inet::physicallayer::Ieee80211FhssHeaderMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), and inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission().
getModulation()
virtual const IModulation* inet::physicallayer::IIeee80211HeaderMode::getModulation () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtSignalMode, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::Ieee80211VhtSignalMode, inet::physicallayer::Ieee80211HrDsssHeaderMode, inet::physicallayer::Ieee80211IrHeaderMode, inet::physicallayer::Ieee80211DsssHeaderMode, and inet::physicallayer::Ieee80211FhssHeaderMode.
getNetBitrate()
virtual bps inet::physicallayer::IIeee80211HeaderMode::getNetBitrate () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtSignalMode, inet::physicallayer::Ieee80211OfdmSignalMode, inet::physicallayer::Ieee80211VhtSignalMode, inet::physicallayer::Ieee80211HrDsssHeaderMode, inet::physicallayer::Ieee80211IrHeaderMode, inet::physicallayer::Ieee80211DsssHeaderMode, and inet::physicallayer::Ieee80211FhssHeaderMode.
The documentation for this class was generated from the following file:
IIeee80211Mode.h