INET Framework for OMNeT++/OMNEST: inet::ShapeBase Class Reference
inet::ShapeBase Class Reference abstract
This class represents a 3 dimensional geometric shape independently of its position and orientation.
#include <ShapeBase.h>
Public Member Functions
ShapeBase ()
virtual ~ShapeBase ()
virtual Coord computeBoundingBoxSize () const =0
Computes the 3 dimensional size of the shapes's bounding box.
virtual bool computeIntersection (const LineSegment &lineSegment, Coord &intersection1, Coord &intersection2, Coord &normal1, Coord &normal2) const =0
Computes the intersection with the given line segment in the shape's coordinate system.
Detailed Description
This class represents a 3 dimensional geometric shape independently of its position and orientation.
Moving a shape around, rotating it, or reflecting it in a mirror is the same shape as the original, and not a distinct shape.
Constructor & Destructor Documentation
ShapeBase()
inet::ShapeBase::ShapeBase () inline
 {}
~ShapeBase()
virtual inet::ShapeBase::~ShapeBase () inline virtual
 {}
Member Function Documentation
computeBoundingBoxSize()
virtual Coord inet::ShapeBase::computeBoundingBoxSize () const pure virtual
Computes the 3 dimensional size of the shapes's bounding box.
Implemented in inet::Polyhedron, inet::Prism, inet::Cuboid, and inet::Sphere.
Referenced by inet::BvhTree::computeBoundingBox(), and inet::BvhTree::AxisComparator::operator()().
computeIntersection()
virtual bool inet::ShapeBase::computeIntersection (const LineSegment & lineSegment, Coord & intersection1, Coord & intersection2, Coord & normal1, Coord & normal2) const pure virtual
Computes the intersection with the given line segment in the shape's coordinate system.
Implemented in inet::Polyhedron, inet::Prism, inet::Cuboid, and inet::Sphere.
Referenced by inet::physicallayer::DielectricObstacleLoss::computeObjectLoss(), and inet::physicallayer::IdealObstacleLoss::isObstacle().
The documentation for this class was generated from the following file:
ShapeBase.h