INET Framework for OMNeT++/OMNEST: inet::physicallayer::ISignalSymbolModel Class Reference
inet::physicallayer::ISignalSymbolModel Class Reference abstract
This purely virtual interface provides an abstraction for different radio signal models in the waveform or symbol domain.
#include <ISignalSymbolModel.h>
Public Member Functions
virtual int getPayloadSymbolLength () const =0
virtual double getPayloadSymbolRate () const =0
virtual int getHeaderSymbolLength () const =0
virtual double getHeaderSymbolRate () const =0
virtual const std::vector< const ISymbol * > * getSymbols () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This purely virtual interface provides an abstraction for different radio signal models in the waveform or symbol domain.
Member Function Documentation
getHeaderSymbolLength()
virtual int inet::physicallayer::ISignalSymbolModel::getHeaderSymbolLength () const pure virtual
Implemented in inet::physicallayer::SignalSymbolModel.
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteSymbolModel().
getHeaderSymbolRate()
virtual double inet::physicallayer::ISignalSymbolModel::getHeaderSymbolRate () const pure virtual
Implemented in inet::physicallayer::SignalSymbolModel.
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteSymbolModel(), and inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldSymbolModel().
getPayloadSymbolLength()
virtual int inet::physicallayer::ISignalSymbolModel::getPayloadSymbolLength () const pure virtual
Implemented in inet::physicallayer::SignalSymbolModel.
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteSymbolModel(), and inet::physicallayer::PulseShaper::shape().
getPayloadSymbolRate()
virtual double inet::physicallayer::ISignalSymbolModel::getPayloadSymbolRate () const pure virtual
Implemented in inet::physicallayer::SignalSymbolModel.
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldSymbolModel(), and inet::physicallayer::PulseShaper::shape().
getSymbols()
virtual const std::vector<const ISymbol *>* inet::physicallayer::ISignalSymbolModel::getSymbols () const pure virtual
Implemented in inet::physicallayer::SignalSymbolModel.
Referenced by inet::physicallayer::Ieee80211LayeredOfdmReceiver::createCompleteSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createSignalFieldSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::ApskDemodulator::demodulate(), and inet::physicallayer::Ieee80211OfdmDemodulator::demodulate().
The documentation for this class was generated from the following file:
ISignalSymbolModel.h