INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAsconfAckChunk Class Reference
inet::sctp::SctpAsconfAckChunk Class Reference
#include <SctpHeader.h>
Public Member Functions
SctpAsconfAckChunk (const char *name=nullptr, int32_t kind=0)
SctpAsconfAckChunk (const SctpAsconfAckChunk &other)
SctpAsconfAckChunk & operator= (const SctpAsconfAckChunk &other)
virtual SctpAsconfAckChunk * dup () const override
virtual void setAsconfResponseArraySize (size_t size) override
virtual size_t getAsconfResponseArraySize () const override
virtual void setAsconfResponse (size_t k, SctpParameter *asconfResponse) override
Generated but unused method, should not be called.
virtual void appendAsconfResponse (SctpParameter *asconfResponse) override
virtual void insertAsconfResponse (size_t k, SctpParameter *asconfResponse) override
virtual void eraseAsconfResponse (size_t k) override
virtual SctpParameter * getAsconfResponse (size_t k) const override
Returns the kth parameter in this SCTP Reset Chunk.
virtual void addAsconfResponse (SctpParameter *msg)
Adds a message object to the SCTP packet.
virtual SctpParameter * removeAsconfResponse ()
Removes and returns the first message object in this SCTP packet.
virtual void insertAsconfResponse (size_t k, SctpParameter *asconfResponse)=0
void insertAsconfResponse (SctpParameter *asconfResponse)
Public Member Functions inherited from inet::sctp::SctpAsconfAckChunk_Base
virtual ~SctpAsconfAckChunk_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint32_t getSerialNumber () const
virtual void setSerialNumber (uint32_t serialNumber)
virtual SctpParameter * getAsconfResponseForUpdate (size_t k)
void insertAsconfResponse (SctpParameter *asconfResponse)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Attributes
std::vector< SctpParameter * > parameterList
Protected Attributes inherited from inet::sctp::SctpAsconfAckChunk_Base
uint32_t serialNumber = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Additional Inherited Members
Protected Member Functions inherited from inet::sctp::SctpAsconfAckChunk_Base
bool operator== (const SctpAsconfAckChunk_Base &)=delete
SctpAsconfAckChunk_Base (const char *name=nullptr)
SctpAsconfAckChunk_Base (const SctpAsconfAckChunk_Base &other)
SctpAsconfAckChunk_Base & operator= (const SctpAsconfAckChunk_Base &other)
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Constructor & Destructor Documentation
SctpAsconfAckChunk() [1/2]
inet::sctp::SctpAsconfAckChunk::SctpAsconfAckChunk (const char * name = nullptr, int32_t kind = 0) inline
 : SctpAsconfAckChunk_Base() {};
SctpAsconfAckChunk() [2/2]
inet::sctp::SctpAsconfAckChunk::SctpAsconfAckChunk (const SctpAsconfAckChunk & other) inline
 : SctpAsconfAckChunk_Base(other) { operator=(other); };
Member Function Documentation
addAsconfResponse()
void inet::sctp::SctpAsconfAckChunk::addAsconfResponse (SctpParameter * msg) virtual
Adds a message object to the SCTP packet.
The packet length will be adjusted
 {
     take(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     parameterList.push_back(msg);
 }
Referenced by operator=(), and inet::sctp::SctpAssociation::processAsconfArrived().
appendAsconfResponse()
virtual void inet::sctp::SctpAsconfAckChunk::appendAsconfResponse (SctpParameter * asconfResponse) inline override virtual
Implements inet::sctp::SctpAsconfAckChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
dup()
virtual SctpAsconfAckChunk* inet::sctp::SctpAsconfAckChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpAsconfAckChunk_Base.
 { return new SctpAsconfAckChunk(*this); }
Referenced by operator=().
eraseAsconfResponse()
virtual void inet::sctp::SctpAsconfAckChunk::eraseAsconfResponse (size_t k) inline override virtual
Implements inet::sctp::SctpAsconfAckChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
getAsconfResponse()
SctpParameter * inet::sctp::SctpAsconfAckChunk::getAsconfResponse (size_t k) const override virtual
Returns the kth parameter in this SCTP Reset Chunk.
Implements inet::sctp::SctpAsconfAckChunk_Base.
 {
     return parameterList.at(k);
 }
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getAsconfResponseArraySize()
size_t inet::sctp::SctpAsconfAckChunk::getAsconfResponseArraySize () const override virtual
Implements inet::sctp::SctpAsconfAckChunk_Base.
 {
     return parameterList.size();
 }
Referenced by inet::sctp::SctpAssociation::processAsconfAckArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
insertAsconfResponse() [1/3]
void inet::sctp::SctpAsconfAckChunk_Base::insertAsconfResponse inline
 {appendAsconfResponse(asconfResponse);}
insertAsconfResponse() [2/3]
virtual void inet::sctp::SctpAsconfAckChunk::insertAsconfResponse (size_t k, SctpParameter * asconfResponse) inline override virtual
Implements inet::sctp::SctpAsconfAckChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
insertAsconfResponse() [3/3]
virtual void inet::sctp::SctpAsconfAckChunk_Base::insertAsconfResponse
operator=()
SctpAsconfAckChunk & inet::sctp::SctpAsconfAckChunk::operator= (const SctpAsconfAckChunk & other)
 {
     SctpAsconfAckChunk_Base::operator=(other);
     this->setByteLength(SCTP_ADD_IP_CHUNK_LENGTH);
     for (const auto& elem : other.parameterList)
         addAsconfResponse((elem)->dup());
     return *this;
 }
removeAsconfResponse()
SctpParameter * inet::sctp::SctpAsconfAckChunk::removeAsconfResponse () virtual
Removes and returns the first message object in this SCTP packet.
 {
     if (parameterList.empty())
         return nullptr;
     SctpParameter *msg = parameterList.front();
     parameterList.erase(parameterList.begin());
     drop(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     return msg;
 }
setAsconfResponse()
void inet::sctp::SctpAsconfAckChunk::setAsconfResponse (size_t k, SctpParameter * asconfResponse) override virtual
Generated but unused method, should not be called.
Implements inet::sctp::SctpAsconfAckChunk_Base.
 {
     throw cException(this, "setAsconfresponse() not supported, use addAsconfResponse()");
 }
setAsconfResponseArraySize()
void inet::sctp::SctpAsconfAckChunk::setAsconfResponseArraySize (size_t size) override virtual
Implements inet::sctp::SctpAsconfAckChunk_Base.
 {
     throw cException(this, "setAsconfResponseArraySize() not supported, use addAsconfResponse()");
 }
Member Data Documentation
parameterList
std::vector<SctpParameter *> inet::sctp::SctpAsconfAckChunk::parameterList protected
Referenced by addAsconfResponse(), getAsconfResponse(), getAsconfResponseArraySize(), operator=(), and removeAsconfResponse().
The documentation for this class was generated from the following files:
SctpHeader.h
SctpHeader.cc