INET Framework for OMNeT++/OMNEST: inet::power::EpEnergySourceBase Class Reference
inet::power::EpEnergySourceBase Class Reference
#include <EpEnergySourceBase.h>
Public Member Functions
virtual W getTotalPowerConsumption () const override
Returns the total power consumption in the range [0, +infinity).
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
Public Member Functions inherited from inet::power::EnergySourceBase
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Protected Member Functions
virtual W computeTotalPowerConsumption () const
virtual void updateTotalPowerConsumption ()
Protected Attributes
W totalPowerConsumption = W(NaN)
Protected Attributes inherited from inet::power::EnergySourceBase
std::vector< const IEnergyConsumer * > energyConsumers
Additional Inherited Members
Static Public Attributes inherited from inet::power::IEpEnergySource
static simsignal_t powerConsumptionChangedSignal = cComponent::registerSignal("powerConsumptionChanged")
The signal that is used to publish power consumption changes.
Member Function Documentation
addEnergyConsumer()
void inet::power::EpEnergySourceBase::addEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Adds a new energy consumer to the energy source.
The energyConsumer parameter must not be nullptr.
Reimplemented from inet::power::EnergySourceBase.
Reimplemented in inet::power::EpEnergyStorageBase.
 {
     EnergySourceBase::addEnergyConsumer(energyConsumer);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyConsumer));
     module->subscribe(IEpEnergyConsumer::powerConsumptionChangedSignal, this);
     updateTotalPowerConsumption();
 }
Referenced by inet::power::EpEnergyStorageBase::addEnergyConsumer().
computeTotalPowerConsumption()
W inet::power::EpEnergySourceBase::computeTotalPowerConsumption () const protected virtual
 {
     W totalPowerConsumption = W(0);
     for (auto energyConsumer : energyConsumers)
         totalPowerConsumption += check_and_cast<const IEpEnergyConsumer *>(energyConsumer)->getPowerConsumption();
     return totalPowerConsumption;
 }
Referenced by inet::power::EpEnergyStorageBase::initialize(), and updateTotalPowerConsumption().
getTotalPowerConsumption()
virtual W inet::power::EpEnergySourceBase::getTotalPowerConsumption () const inline override virtual
Returns the total power consumption in the range [0, +infinity).
Implements inet::power::IEpEnergySource.
 { return totalPowerConsumption; }
removeEnergyConsumer()
void inet::power::EpEnergySourceBase::removeEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Removes a previously added energy consumer from this energy source.
This functions throws an exception if the consumer is not found.
Reimplemented from inet::power::EnergySourceBase.
Reimplemented in inet::power::EpEnergyStorageBase.
 {
     EnergySourceBase::removeEnergyConsumer(energyConsumer);
     auto module = const_cast<cModule *>(check_and_cast<const cModule *>(energyConsumer));
     module->unsubscribe(IEpEnergyConsumer::powerConsumptionChangedSignal, this);
     updateTotalPowerConsumption();
 }
Referenced by inet::power::EpEnergyStorageBase::removeEnergyConsumer().
updateTotalPowerConsumption()
void inet::power::EpEnergySourceBase::updateTotalPowerConsumption () protected virtual
Reimplemented in inet::power::SimpleEpEnergyStorage, inet::power::IdealEpEnergyStorage, and inet::power::EpEnergyStorageBase.
 {
     totalPowerConsumption = computeTotalPowerConsumption();
 }
Referenced by addEnergyConsumer(), removeEnergyConsumer(), and inet::power::EpEnergyStorageBase::updateTotalPowerConsumption().
Member Data Documentation
totalPowerConsumption
W inet::power::EpEnergySourceBase::totalPowerConsumption = W(NaN) protected
Referenced by computeTotalPowerConsumption(), inet::power::EpEnergyStorageBase::initialize(), inet::power::SimpleEpEnergyStorage::scheduleTimer(), inet::power::IdealEpEnergyStorage::updateEnergyBalance(), inet::power::SimpleEpEnergyStorage::updateResidualCapacity(), inet::power::EpEnergyStorageBase::updateTotalPowerConsumption(), and updateTotalPowerConsumption().
The documentation for this class was generated from the following files:
EpEnergySourceBase.h
EpEnergySourceBase.cc