INET Framework for OMNeT++/OMNEST: inet::TedChangeInfo Class Reference
inet::TedChangeInfo Class Reference
Class generated from inet/networklayer/ted/Ted.msg:42 by opp_msgtool.
#include <Ted_m.h>
Public Member Functions
TedChangeInfo ()
TedChangeInfo (const TedChangeInfo &other)
virtual ~TedChangeInfo ()
TedChangeInfo & operator= (const TedChangeInfo &other)
virtual TedChangeInfo * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setTedLinkIndicesArraySize (size_t size)
virtual size_t getTedLinkIndicesArraySize () const
virtual int getTedLinkIndices (size_t k) const
virtual void setTedLinkIndices (size_t k, int tedLinkIndices)
virtual void insertTedLinkIndices (size_t k, int tedLinkIndices)
void insertTedLinkIndices (int tedLinkIndices)
virtual void appendTedLinkIndices (int tedLinkIndices)
virtual void eraseTedLinkIndices (size_t k)
Protected Member Functions
bool operator== (const TedChangeInfo &)=delete
Protected Attributes
int * tedLinkIndices = nullptr
size_t tedLinkIndices_arraysize = 0
Private Member Functions
void copy (const TedChangeInfo &other)
Detailed Description
Class generated from inet/networklayer/ted/Ted.msg:42 by opp_msgtool.
//
// Data structure supplied with NF_TED_CHANGE signal.
// This triggers the link state protocol to send out up-to-date link state info
// about the given links.
//
class TedChangeInfo extends cObject
{
    int tedLinkIndices[];
}
Constructor & Destructor Documentation
TedChangeInfo() [1/2]
inet::TedChangeInfo::TedChangeInfo ()
TedChangeInfo() [2/2]
inet::TedChangeInfo::TedChangeInfo (const TedChangeInfo & other)
~TedChangeInfo()
virtual inet::TedChangeInfo::~TedChangeInfo () virtual
Member Function Documentation
appendTedLinkIndices()
virtual void inet::TedChangeInfo::appendTedLinkIndices (int tedLinkIndices) virtual
copy()
void inet::TedChangeInfo::copy (const TedChangeInfo & other) private
dup()
virtual TedChangeInfo* inet::TedChangeInfo::dup () const inline override virtual
 {return new TedChangeInfo(*this);}
eraseTedLinkIndices()
virtual void inet::TedChangeInfo::eraseTedLinkIndices (size_t k) virtual
getTedLinkIndices()
virtual int inet::TedChangeInfo::getTedLinkIndices (size_t k) const virtual
Referenced by inet::LinkStateRouting::receiveSignal().
getTedLinkIndicesArraySize()
virtual size_t inet::TedChangeInfo::getTedLinkIndicesArraySize () const virtual
Referenced by inet::LinkStateRouting::receiveSignal().
insertTedLinkIndices() [1/2]
void inet::TedChangeInfo::insertTedLinkIndices (int tedLinkIndices) inline
 {appendTedLinkIndices(tedLinkIndices);}
insertTedLinkIndices() [2/2]
virtual void inet::TedChangeInfo::insertTedLinkIndices (size_t k, int tedLinkIndices) virtual
operator=()
TedChangeInfo& inet::TedChangeInfo::operator= (const TedChangeInfo & other)
operator==()
bool inet::TedChangeInfo::operator== (const TedChangeInfo &) protected delete
parsimPack()
virtual void inet::TedChangeInfo::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::TedChangeInfo::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setTedLinkIndices()
virtual void inet::TedChangeInfo::setTedLinkIndices (size_t k, int tedLinkIndices) virtual
Referenced by inet::Ldp::announceLinkChange(), and inet::RsvpTe::announceLinkChange().
setTedLinkIndicesArraySize()
virtual void inet::TedChangeInfo::setTedLinkIndicesArraySize (size_t size) virtual
Referenced by inet::Ldp::announceLinkChange(), and inet::RsvpTe::announceLinkChange().
Member Data Documentation
tedLinkIndices
int* inet::TedChangeInfo::tedLinkIndices = nullptr protected
tedLinkIndices_arraysize
size_t inet::TedChangeInfo::tedLinkIndices_arraysize = 0 protected
The documentation for this class was generated from the following file:
Ted_m.h