INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpInterfaceTable Class Reference
inet::eigrp::EigrpInterfaceTable Class Reference
#include <EigrpInterfaceTable.h>
Public Member Functions
~EigrpInterfaceTable ()
void addInterface (EigrpInterface *interface)
Adds interface to table.
EigrpInterface * removeInterface (EigrpInterface *iface)
Removes interface from table.
EigrpInterface * findInterfaceById (int ifaceId)
Gets interface from table by interface ID.
int getNumInterfaces () const
Returns number of interfaces in the table.
EigrpInterface * getInterface (int k) const
Returns interface by its position in the table.
Protected Types
typedef std::vector< EigrpInterface * > InterfaceVector
Protected Member Functions
virtual void initialize (int stage)
virtual void handleMessage (cMessage *msg)
virtual int numInitStages () const
Protected Attributes
InterfaceVector eigrpInterfaces
Member Typedef Documentation
InterfaceVector
typedef std::vector<EigrpInterface *> inet::eigrp::EigrpInterfaceTable::InterfaceVector protected
Constructor & Destructor Documentation
~EigrpInterfaceTable()
inet::eigrp::EigrpInterfaceTable::~EigrpInterfaceTable ()
 {
     int cnt = eigrpInterfaces.size();
     EigrpInterface *iface;
     for (int i = 0; i < cnt; i++) {
         iface = eigrpInterfaces[i];
         eigrpInterfaces[i] = nullptr;
         delete iface;
     }
     eigrpInterfaces.clear();
 }
Member Function Documentation
addInterface()
void inet::eigrp::EigrpInterfaceTable::addInterface (EigrpInterface * interface)
Adds interface to table.
 {
     // TODO check duplicity
     eigrpInterfaces.push_back(interface);
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), and inet::eigrp::EigrpIpv6Pdm::enableInterface().
findInterfaceById()
EigrpInterface * inet::eigrp::EigrpInterfaceTable::findInterfaceById (int ifaceId)
Gets interface from table by interface ID.
 {
     InterfaceVector::iterator it;
     EigrpInterface *iface;
     for (it = eigrpInterfaces.begin(); it != eigrpInterfaces.end(); it++) {
         iface = *it;
         if (iface->getInterfaceId() == ifaceId) {
             return iface;
         }
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::checkNeighborshipRules(), inet::eigrp::EigrpIpv6Pdm::checkNeighborshipRules(), inet::eigrp::EigrpIpv4Pdm::flushMsgRequests(), inet::eigrp::EigrpIpv6Pdm::flushMsgRequests(), inet::eigrp::EigrpIpv4Pdm::getInterfaceById(), inet::eigrp::EigrpIpv6Pdm::getInterfaceById(), inet::eigrp::EigrpIpv4Pdm::processAckPacket(), inet::eigrp::EigrpIpv6Pdm::processAckPacket(), inet::eigrp::EigrpIpv4Pdm::processHelloPacket(), inet::eigrp::EigrpIpv6Pdm::processHelloPacket(), inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv4Pdm::processMsgFromNetwork(), inet::eigrp::EigrpIpv6Pdm::processMsgFromNetwork(), inet::eigrp::EigrpIpv4Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv6Pdm::processMsgFromRtp(), inet::eigrp::EigrpIpv4Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv6Pdm::processNewNeighbor(), inet::eigrp::EigrpIpv4Pdm::processQueryPacket(), inet::eigrp::EigrpIpv6Pdm::processQueryPacket(), inet::eigrp::EigrpIpv4Pdm::processReplyPacket(), inet::eigrp::EigrpIpv6Pdm::processReplyPacket(), inet::eigrp::EigrpIpv4Pdm::processTimer(), inet::eigrp::EigrpIpv6Pdm::processTimer(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), inet::eigrp::EigrpIpv6Pdm::processUpdatePacket(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::setBandwidth(), inet::eigrp::EigrpIpv6Pdm::setBandwidth(), inet::eigrp::EigrpIpv4Pdm::setDelay(), inet::eigrp::EigrpIpv6Pdm::setDelay(), inet::eigrp::EigrpIpv4Pdm::setLoad(), inet::eigrp::EigrpIpv6Pdm::setLoad(), inet::eigrp::EigrpIpv4Pdm::setReliability(), inet::eigrp::EigrpIpv6Pdm::setReliability(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable(), inet::eigrp::EigrpIpv4Pdm::updateInterface(), and inet::eigrp::EigrpIpv6Pdm::updateInterface().
getInterface()
EigrpInterface* inet::eigrp::EigrpInterfaceTable::getInterface (int k) const inline
Returns interface by its position in the table.
 { return eigrpInterfaces[k]; }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv6Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv4Pdm::hasNeighborForUpdate(), inet::eigrp::EigrpIpv6Pdm::hasNeighborForUpdate(), inet::eigrp::EigrpIpv4Pdm::msgToAllIfaces(), and inet::eigrp::EigrpIpv6Pdm::msgToAllIfaces().
getNumInterfaces()
int inet::eigrp::EigrpInterfaceTable::getNumInterfaces () const inline
Returns number of interfaces in the table.
 { return eigrpInterfaces.size(); }
Referenced by inet::eigrp::EigrpIpv4Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv6Pdm::cancelHelloTimers(), inet::eigrp::EigrpIpv4Pdm::hasNeighborForUpdate(), inet::eigrp::EigrpIpv6Pdm::hasNeighborForUpdate(), inet::eigrp::EigrpIpv4Pdm::msgToAllIfaces(), and inet::eigrp::EigrpIpv6Pdm::msgToAllIfaces().
handleMessage()
void inet::eigrp::EigrpInterfaceTable::handleMessage (cMessage * msg) protected virtual
 {
     // TODO - Generated method body
 }
initialize()
void inet::eigrp::EigrpInterfaceTable::initialize (int stage) protected virtual
 {
     cSimpleModule::initialize(stage);
     if (stage == INITSTAGE_ROUTING_PROTOCOLS) {
         WATCH_PTRVECTOR(eigrpInterfaces);
     }
 }
numInitStages()
virtual int inet::eigrp::EigrpInterfaceTable::numInitStages () const inline protected virtual
 { return NUM_INIT_STAGES; }
removeInterface()
EigrpInterface * inet::eigrp::EigrpInterfaceTable::removeInterface (EigrpInterface * iface)
Removes interface from table.
 {
     InterfaceVector::iterator it;
     it = find(eigrpInterfaces, iface);
     if (it != eigrpInterfaces.end()) {
         eigrpInterfaces.erase(it);
         return iface;
     }
     return nullptr;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::disableInterface(), and inet::eigrp::EigrpIpv6Pdm::disableInterface().
Member Data Documentation
eigrpInterfaces
InterfaceVector inet::eigrp::EigrpInterfaceTable::eigrpInterfaces protected
Referenced by addInterface(), findInterfaceById(), getInterface(), getNumInterfaces(), initialize(), removeInterface(), and ~EigrpInterfaceTable().
The documentation for this class was generated from the following files:
EigrpInterfaceTable.h
EigrpInterfaceTable.cc