INET Framework for OMNeT++/OMNEST: inet::physicallayer::IMediumLimitCache Class Reference
inet::physicallayer::IMediumLimitCache Class Reference abstract
This interface is used to cache various medium limits among the radios.
#include <IMediumLimitCache.h>
Public Member Functions
virtual void addRadio (const IRadio *radio)=0
Notifies the cache when a radio is added to the medium.
virtual void removeRadio (const IRadio *radio)=0
Notifies the cache when a radio is removed from the medium.
virtual Coord getMinConstraintArea () const =0
Returns the minimum possible position among the radios, the coordinate values are in the range (-infinity, +infinity) or NaN if unspecified.
virtual Coord getMaxConstraintArea () const =0
Returns the maximum possible position among the radios, the coordinate values are in the range (-infinity, +infinity) or NaN if unspecified.
virtual mps getMaxSpeed () const =0
Returns the maximum possible speed among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual W getMaxTransmissionPower () const =0
Returns the maximum possible transmission power among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual W getMinInterferencePower () const =0
Returns the minimum possible interference power among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual W getMinReceptionPower () const =0
Returns the minimum possible reception power among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual double getMaxAntennaGain () const =0
Returns the maximum possible antenna gain among the radios, the value is in the range [1, +infinity) or NaN if unspecified.
virtual const simtime_t & getMinInterferenceTime () const =0
Returns the minimum required signal interference time among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual const simtime_t & getMaxTransmissionDuration () const =0
Returns the maximum possible transmission durations among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual m getMaxCommunicationRange () const =0
Returns the maximum possible communication range among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual m getMaxInterferenceRange () const =0
Returns the maximum possible interference range among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
virtual m getMaxCommunicationRange (const IRadio *radio) const =0
Returns the maximum possible communication range for a given radio, the value is in the range [0, +infinity) or NaN if unspecified.
virtual m getMaxInterferenceRange (const IRadio *radio) const =0
Returns the maximum possible interference range for a given radio, the value is in the range [0, +infinity) or NaN if unspecified.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface is used to cache various medium limits among the radios.
Member Function Documentation
addRadio()
virtual void inet::physicallayer::IMediumLimitCache::addRadio (const IRadio * radio) pure virtual
Notifies the cache when a radio is added to the medium.
Implemented in inet::physicallayer::MediumLimitCache.
Referenced by inet::physicallayer::RadioMedium::addRadio().
getMaxAntennaGain()
virtual double inet::physicallayer::IMediumLimitCache::getMaxAntennaGain () const pure virtual
Returns the maximum possible antenna gain among the radios, the value is in the range [1, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMaxCommunicationRange() [1/2]
virtual m inet::physicallayer::IMediumLimitCache::getMaxCommunicationRange () const pure virtual
Returns the maximum possible communication range among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
Referenced by inet::physicallayer::RadioMedium::isInCommunicationRange(), and inet::physicallayer::RadioMedium::sendToAffectedRadios().
getMaxCommunicationRange() [2/2]
virtual m inet::physicallayer::IMediumLimitCache::getMaxCommunicationRange (const IRadio * radio) const pure virtual
Returns the maximum possible communication range for a given radio, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMaxConstraintArea()
virtual Coord inet::physicallayer::IMediumLimitCache::getMaxConstraintArea () const pure virtual
Returns the maximum possible position among the radios, the coordinate values are in the range (-infinity, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMaxInterferenceRange() [1/2]
virtual m inet::physicallayer::IMediumLimitCache::getMaxInterferenceRange () const pure virtual
Returns the maximum possible interference range among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
Referenced by inet::physicallayer::RadioMedium::isInInterferenceRange(), and inet::physicallayer::RadioMedium::sendToAffectedRadios().
getMaxInterferenceRange() [2/2]
virtual m inet::physicallayer::IMediumLimitCache::getMaxInterferenceRange (const IRadio * radio) const pure virtual
Returns the maximum possible interference range for a given radio, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMaxSpeed()
virtual mps inet::physicallayer::IMediumLimitCache::getMaxSpeed () const pure virtual
Returns the maximum possible speed among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMaxTransmissionDuration()
virtual const simtime_t& inet::physicallayer::IMediumLimitCache::getMaxTransmissionDuration () const pure virtual
Returns the maximum possible transmission durations among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
Referenced by inet::physicallayer::RadioMedium::addTransmission(), and inet::physicallayer::RadioMedium::createTransmitterSignal().
getMaxTransmissionPower()
virtual W inet::physicallayer::IMediumLimitCache::getMaxTransmissionPower () const pure virtual
Returns the maximum possible transmission power among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMinConstraintArea()
virtual Coord inet::physicallayer::IMediumLimitCache::getMinConstraintArea () const pure virtual
Returns the minimum possible position among the radios, the coordinate values are in the range (-infinity, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMinInterferencePower()
virtual W inet::physicallayer::IMediumLimitCache::getMinInterferencePower () const pure virtual
Returns the minimum possible interference power among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
getMinInterferenceTime()
virtual const simtime_t& inet::physicallayer::IMediumLimitCache::getMinInterferenceTime () const pure virtual
Returns the minimum required signal interference time among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
Referenced by inet::physicallayer::RadioMedium::isInterferingTransmission().
getMinReceptionPower()
virtual W inet::physicallayer::IMediumLimitCache::getMinReceptionPower () const pure virtual
Returns the minimum possible reception power among the radios, the value is in the range [0, +infinity) or NaN if unspecified.
Implemented in inet::physicallayer::MediumLimitCache.
removeRadio()
virtual void inet::physicallayer::IMediumLimitCache::removeRadio (const IRadio * radio) pure virtual
Notifies the cache when a radio is removed from the medium.
Implemented in inet::physicallayer::MediumLimitCache.
Referenced by inet::physicallayer::RadioMedium::removeRadio().
The documentation for this class was generated from the following file:
IMediumLimitCache.h