INET Framework for OMNeT++/OMNEST: inet::power::EnergySourceBase Class Reference
inet::power::EnergySourceBase Class Reference
#include <EnergySourceBase.h>
Public Member Functions
virtual int getNumEnergyConsumers () const override
Returns the number of energy consumers in the range [0, +infinity).
virtual const IEnergyConsumer * getEnergyConsumer (int index) const override
Returns the energy consumer for the provided index.
virtual void addEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Adds a new energy consumer to the energy source.
virtual void removeEnergyConsumer (const IEnergyConsumer *energyConsumer) override
Removes a previously added energy consumer from this energy source.
Public Member Functions inherited from inet::power::IEnergySource
virtual ~IEnergySource ()
Protected Attributes
std::vector< const IEnergyConsumer * > energyConsumers
Member Function Documentation
addEnergyConsumer()
void inet::power::EnergySourceBase::addEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Adds a new energy consumer to the energy source.
The energyConsumer parameter must not be nullptr.
Implements inet::power::IEnergySource.
Reimplemented in inet::power::CcEnergySourceBase, inet::power::EpEnergySourceBase, inet::power::CcEnergyStorageBase, and inet::power::EpEnergyStorageBase.
 {
     energyConsumers.push_back(energyConsumer);
 }
Referenced by inet::power::CcEnergySourceBase::addEnergyConsumer(), and inet::power::EpEnergySourceBase::addEnergyConsumer().
getEnergyConsumer()
const IEnergyConsumer * inet::power::EnergySourceBase::getEnergyConsumer (int index) const override virtual
Returns the energy consumer for the provided index.
This functions throws an exception if the index is out of range, and it never returns nullptr.
Implements inet::power::IEnergySource.
 {
     return energyConsumers[index];
 }
getNumEnergyConsumers()
virtual int inet::power::EnergySourceBase::getNumEnergyConsumers () const inline override virtual
Returns the number of energy consumers in the range [0, +infinity).
Implements inet::power::IEnergySource.
 { return energyConsumers.size(); }
removeEnergyConsumer()
void inet::power::EnergySourceBase::removeEnergyConsumer (const IEnergyConsumer * energyConsumer) override virtual
Removes a previously added energy consumer from this energy source.
This functions throws an exception if the consumer is not found.
Implements inet::power::IEnergySource.
Reimplemented in inet::power::CcEnergySourceBase, inet::power::EpEnergySourceBase, inet::power::CcEnergyStorageBase, and inet::power::EpEnergyStorageBase.
 {
     auto it = find(energyConsumers, energyConsumer);
     if (it == energyConsumers.end())
         throw cRuntimeError("Energy consumer not found");
     else
         energyConsumers.erase(it);
 }
Referenced by inet::power::CcEnergySourceBase::removeEnergyConsumer(), and inet::power::EpEnergySourceBase::removeEnergyConsumer().
Member Data Documentation
energyConsumers
std::vector<const IEnergyConsumer *> inet::power::EnergySourceBase::energyConsumers protected
Referenced by addEnergyConsumer(), inet::power::CcEnergySourceBase::computeTotalCurrentConsumption(), inet::power::EpEnergySourceBase::computeTotalPowerConsumption(), getEnergyConsumer(), and removeEnergyConsumer().
The documentation for this class was generated from the following files:
EnergySourceBase.h
EnergySourceBase.cc