INET Framework for OMNeT++/OMNEST: inet::MacAddress Class Reference
inet::MacAddress Class Reference
Stores an IEEE 802 MAC address (6 octets = 48 bits).
#include <MacAddress.h>
Public Member Functions
MacAddress ()
Default constructor initializes address bytes to zero.
MacAddress (uint64_t bits)
Initializes the address from the lower 48 bits of the 64-bit argument.
MacAddress (const char *hexstr)
Constructor which accepts a hex string (12 hex digits, may also contain spaces, hyphens and colons)
MacAddress (const MacAddress &other)
Copy constructor.
MacAddress & operator= (const MacAddress &other)
Assignment.
unsigned int getAddressSize () const
Returns the address size in bytes, that is, 6.
unsigned char getAddressByte (unsigned int k) const
Returns the kth byte of the address.
void setAddressByte (unsigned int k, unsigned char addrbyte)
Sets the kth byte of the address.
bool tryParse (const char *hexstr)
Sets the address and returns true if the syntax of the string is correct.
void setAddress (const char *hexstr)
Converts address value from hex string (12 hex digits, may also contain spaces, hyphens and colons)
void getAddressBytes (unsigned char *addrbytes) const
Copies the address to the given pointer (array of 6 unsigned chars).
void getAddressBytes (char *addrbytes) const
void setAddressBytes (unsigned char *addrbytes)
Sets address bytes.
void setAddressBytes (char *addrbytes)
void setBroadcast ()
Sets the address to the broadcast address (hex ff:ff:ff:ff:ff:ff).
bool isBroadcast () const
Returns true if this is the broadcast address (hex ff:ff:ff:ff:ff:ff).
bool isMulticast () const
Returns true if this is a multicast logical address (first byte's lsb is 1).
bool isLocal () const
Returns true if this is a local address (first byte's second less significant bit is 1).
bool isUnspecified () const
Returns true if all address bytes are zero.
std::string str () const
Converts address to a hex string.
uint64_t getInt () const
Converts address to 48 bits integer.
bool equals (const MacAddress &other) const
Returns true if the two addresses are equal.
bool operator== (const MacAddress &other) const
Returns true if the two addresses are equal.
bool operator!= (const MacAddress &other) const
Returns true if the two addresses are not equal.
int compareTo (const MacAddress &other) const
Returns -1, 0 or 1 as result of comparison of 2 addresses.
InterfaceToken formInterfaceIdentifier () const
Create interface identifier (IEEE EUI-64) which can be used by IPv6 stateless address autoconfiguration.
bool operator< (const MacAddress &other) const
bool operator> (const MacAddress &other) const
Static Public Member Functions
static MacAddress generateAutoAddress ()
Generates a unique address which begins with 0a:aa and ends in a unique suffix.
Static Public Attributes
static const MacAddress UNSPECIFIED_ADDRESS
The unspecified MAC address, 00:00:00:00:00:00.
static const MacAddress BROADCAST_ADDRESS
The broadcast MAC address, ff:ff:ff:ff:ff:ff.
static const MacAddress MULTICAST_PAUSE_ADDRESS
The special multicast PAUSE MAC address, 01:80:C2:00:00:01.
static const MacAddress STP_MULTICAST_ADDRESS
The spanning tree protocol bridge's multicast address, 01:80:C2:00:00:00.
static const MacAddress CDP_MULTICAST_ADDRESS
The Cisco discovery protocol bridge's multicast address, 01:00:0C:CC:CC:CC.
static const MacAddress LLDP_MULTICAST_ADDRESS
The Local link discovery protocol bridge's multicast address, 01:80:C2:00:00:0E.
Private Attributes
uint64_t address
Detailed Description
Stores an IEEE 802 MAC address (6 octets = 48 bits).
Constructor & Destructor Documentation
MacAddress() [1/4]
inet::MacAddress::MacAddress () inline
Default constructor initializes address bytes to zero.
 { address = 0; }
Referenced by generateAutoAddress().
MacAddress() [2/4]
inet::MacAddress::MacAddress (uint64_t bits) inline explicit
Initializes the address from the lower 48 bits of the 64-bit argument.
 { address = bits & MAC_ADDRESS_MASK; }
MacAddress() [3/4]
inet::MacAddress::MacAddress (const char * hexstr) inline explicit
Constructor which accepts a hex string (12 hex digits, may also contain spaces, hyphens and colons)
 { setAddress(hexstr); }
MacAddress() [4/4]
inet::MacAddress::MacAddress (const MacAddress & other) inline
Copy constructor.
 { address = other.address; }
Member Function Documentation
compareTo()
int inet::MacAddress::compareTo (const MacAddress & other) const
Returns -1, 0 or 1 as result of comparison of 2 addresses.
 {
     return (address < other.address) ? -1 : (address == other.address) ? 0 : 1; // note: "return address-other.address" is not OK because 64-bit result does not fit into the return type
 }
Referenced by inet::Stp::compareBridgeIDs(), inet::Rstp::compareRSTPData(), inet::Rstp::handleIncomingFrame(), inet::ieee80211::Ieee80211MgmtAp::MacCompare::operator()(), and inet::MacForwardingTable::MacCompare::operator()().
equals()
bool inet::MacAddress::equals (const MacAddress & other) const inline
Returns true if the two addresses are equal.
 { return address == other.address; }
Referenced by inet::Ipv6NeighbourDiscovery::processNaForOtherNceStates(), inet::Ipv6NeighbourDiscovery::processNsWithSpecifiedSrcAddr(), and inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates().
formInterfaceIdentifier()
InterfaceToken inet::MacAddress::formInterfaceIdentifier () const
Create interface identifier (IEEE EUI-64) which can be used by IPv6 stateless address autoconfiguration.
 {
     uint32_t high = ((address >> 16) | 0xff) ^ 0x02000000;
     uint32_t low = (0xfe << 24) | (address & 0xffffff);
     return InterfaceToken(low, high, 64);
 }
Referenced by inet::ShortcutMac::configureNetworkInterface(), inet::AckingMac::configureNetworkInterface(), inet::XMac::configureNetworkInterface(), inet::CsmaCaMac::configureNetworkInterface(), inet::LMac::configureNetworkInterface(), inet::BMac::configureNetworkInterface(), inet::Ieee802154Mac::configureNetworkInterface(), inet::VirtualTunnel::initialize(), and inet::NetworkInterface::initialize().
generateAutoAddress()
MacAddress inet::MacAddress::generateAutoAddress () static
Generates a unique address which begins with 0a:aa and ends in a unique suffix.
 {
     static SimulationRunUniqueNumberGenerator<uint64_t> counter;
     uint64_t raw = 0x0AAA00000000ULL + (counter.getNextValue() & 0xffffffffUL) + getEnvir()->getParsimProcId() * 0x000100000000ULL;
     return MacAddress(raw);
 }
Referenced by inet::VirtualTunnel::initialize(), inet::NetworkInterface::initialize(), and inet::MacProtocolBase::parseMacAddressParameter().
getAddressByte()
unsigned char inet::MacAddress::getAddressByte (unsigned int k) const
Returns the kth byte of the address.
 {
     if (k >= MAC_ADDRESS_SIZE)
         throw cRuntimeError("Array of size 6 indexed with %d", k);
     int offset = (MAC_ADDRESS_SIZE - k - 1) * 8;
     return 0xff & (address >> offset);
 }
Referenced by getAddressBytes(), str(), and inet::MemoryOutputStream::writeMacAddress().
getAddressBytes() [1/2]
void inet::MacAddress::getAddressBytes (char * addrbytes) const inline
 { getAddressBytes(reinterpret_cast<unsigned char *>(addrbytes)); }
Referenced by getAddressBytes().
getAddressBytes() [2/2]
void inet::MacAddress::getAddressBytes (unsigned char * addrbytes) const
Copies the address to the given pointer (array of 6 unsigned chars).
 {
     for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
         addrbytes[i] = getAddressByte(i);
 }
getAddressSize()
unsigned int inet::MacAddress::getAddressSize () const inline
Returns the address size in bytes, that is, 6.
 { return MAC_ADDRESS_SIZE; }
getInt()
uint64_t inet::MacAddress::getInt () const inline
Converts address to 48 bits integer.
 { return address; }
Referenced by inet::doParsimPacking(), and inet::L3Address::set().
isBroadcast()
bool inet::MacAddress::isBroadcast () const inline
Returns true if this is the broadcast address (hex ff:ff:ff:ff:ff:ff).
 { return address == MAC_ADDRESS_MASK; }
Referenced by inet::AckingMac::encapsulate(), inet::L3AddressResolver::findInterfaceWithMacAddress(), inet::EthernetSocketTable::findSockets(), inet::Ieee802154Mac::handleLowerPacket(), inet::XMac::handleSelfMessage(), inet::LMac::handleSelfMessage(), inet::L3Address::isBroadcast(), inet::CsmaCaMac::isBroadcast(), inet::L3Address::isUnicast(), inet::NetworkInterface::matchesMacAddress(), inet::physicallayer::RadioMedium::matchesMacAddressFilter(), and inet::AckingMac::startTransmitting().
isLocal()
bool inet::MacAddress::isLocal () const inline
Returns true if this is a local address (first byte's second less significant bit is 1).
 { return getAddressByte(0) & 0x02; };
isMulticast()
bool inet::MacAddress::isMulticast () const inline
Returns true if this is a multicast logical address (first byte's lsb is 1).
 { return getAddressByte(0) & 0x01; };
Referenced by inet::MacForwardingTable::addMulticastAddressForwardingInterface(), inet::AckingMac::encapsulate(), inet::L3AddressResolver::findInterfaceWithMacAddress(), inet::ieee80211::QoSSequenceNumberAssignment::getCacheType(), inet::MacForwardingTable::getMulticastAddressForwardingInterfaces(), inet::MacForwardingTable::getUnicastAddressForwardingInterface(), inet::Ieee802154Mac::handleLowerPacket(), inet::L3Address::isMulticast(), inet::L3Address::isUnicast(), inet::MacForwardingTable::learnUnicastAddressForwardingInterface(), inet::NetworkInterface::matchesMacAddress(), inet::physicallayer::RadioMedium::matchesMacAddressFilter(), inet::NetworkInterface::matchesMulticastMacAddress(), inet::MacForwardingTable::parseForwardingTableParameter(), inet::MacForwardingTable::removeMulticastAddressForwardingInterface(), inet::MacForwardingTable::removeUnicastAddressForwardingInterface(), inet::MacForwardingTable::setUnicastAddressForwardingInterface(), inet::AckingMac::startTransmitting(), and inet::MacRelayUnitBase::updatePeerAddress().
isUnspecified()
bool inet::MacAddress::isUnspecified () const inline
Returns true if all address bytes are zero.
 { return address == 0; }
Referenced by inet::AckingMac::encapsulate(), inet::L3AddressResolver::findInterfaceWithMacAddress(), inet::L3AddressResolver::getInterfaceMacAddress(), inet::GlobalArp::getL3AddressFor(), inet::Arp::getL3AddressFor(), inet::EtherAppClient::handleMessageWhenUp(), inet::EtherTrafGen::handleMessageWhenUp(), inet::EthernetPauseCommandProcessor::handleSendPause(), inet::EthernetEncapsulation::handleSendPause(), inet::L3Address::isUnspecified(), inet::EthernetEncapsulation::Socket::matches(), inet::Arp::processArpPacket(), inet::ieee80211::Ieee80211AgentSta::processAssociateConfirm(), inet::Ipv6NeighbourDiscovery::processNaForIncompleteNceState(), inet::Ipv6NeighbourDiscovery::processNaForOtherNceStates(), inet::Ipv6NeighbourDiscovery::processNsWithSpecifiedSrcAddr(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6::resolveMACAddressAndSendPacket(), inet::Arp::sendArpGratuitous(), inet::Arp::sendArpProbe(), inet::Arp::sendArpRequest(), inet::Ipv4::sendDatagramToOutput(), inet::Ipv6NeighbourDiscovery::sendSolicitedNa(), inet::DhcpMessageSerializer::serialize(), inet::ieee80211::MsduAggregation::setSubframeAddress(), inet::AckingMac::startTransmitting(), inet::NetworkInterface::str(), inet::Ipv6NeighbourDiscovery::validateNsPacket(), and inet::Ipv6NeighbourDiscovery::validateRsPacket().
operator!=()
bool inet::MacAddress::operator!= (const MacAddress & other) const inline
Returns true if the two addresses are not equal.
 { return address != other.address; }
operator<()
bool inet::MacAddress::operator< (const MacAddress & other) const inline
 { return address < other.address; }
operator=()
MacAddress& inet::MacAddress::operator= (const MacAddress & other) inline
Assignment.
 { address = other.address; return *this; }
operator==()
bool inet::MacAddress::operator== (const MacAddress & other) const inline
Returns true if the two addresses are equal.
 { return address == other.address; }
operator>()
bool inet::MacAddress::operator> (const MacAddress & other) const inline
 { return address > other.address; }
setAddress()
void inet::MacAddress::setAddress (const char * hexstr)
Converts address value from hex string (12 hex digits, may also contain spaces, hyphens and colons)
 {
     if (!tryParse(hexstr))
         throw cRuntimeError("MacAddress: wrong address syntax '%s': 12 hex digits expected, with optional embedded spaces, hyphens or colons", hexstr);
 }
Referenced by inet::MacProtocolBase::parseMacAddressParameter().
setAddressByte()
void inet::MacAddress::setAddressByte (unsigned int k, unsigned char addrbyte)
Sets the kth byte of the address.
 {
     if (k >= MAC_ADDRESS_SIZE)
         throw cRuntimeError("Array of size 6 indexed with %d", k);
     int offset = (MAC_ADDRESS_SIZE - k - 1) * 8;
     address = (address & (~(((uint64_t)0xff) << offset))) | (((uint64_t)addrbyte) << offset);
 }
Referenced by inet::L3Address::mapToMulticastMacAddress(), inet::Ipv6Address::mapToMulticastMacAddress(), inet::Ipv4Address::mapToMulticastMacAddress(), inet::MemoryInputStream::readMacAddress(), setAddressBytes(), and tryParse().
setAddressBytes() [1/2]
void inet::MacAddress::setAddressBytes (char * addrbytes) inline
 { setAddressBytes(reinterpret_cast<unsigned char *>(addrbytes)); }
Referenced by setAddressBytes().
setAddressBytes() [2/2]
void inet::MacAddress::setAddressBytes (unsigned char * addrbytes)
Sets address bytes.
The argument should point to an array of 6 unsigned chars.
 {
     address = 0; // clear top 16 bits too that setAddressByte() calls skip
     for (int i = 0; i < MAC_ADDRESS_SIZE; i++)
         setAddressByte(i, addrbytes[i]);
 }
setBroadcast()
void inet::MacAddress::setBroadcast () inline
Sets the address to the broadcast address (hex ff:ff:ff:ff:ff:ff).
 { address = MAC_ADDRESS_MASK; }
str()
std::string inet::MacAddress::str () const
Converts address to a hex string.
 {
     char buf[20];
     char *s = buf;
     for (int i = 0; i < MAC_ADDRESS_SIZE; i++, s += 3)
         sprintf(s, "%2.2X-", getAddressByte(i));
     *(s - 1) = '\0';
     return std::string(buf);
 }
Referenced by inet::NetworkInterface::addMulticastMacAddress(), inet::PacketFilter::DynamicExpressionResolver::callMethod(), inet::MacForwardingTableConfigurator::extendConfiguration(), inet::MacForwardingTableConfigurator::findForwardingRule(), inet::operator<<(), inet::Rstp::printState(), inet::ieee80211::Ieee80211MgmtSta::processAssociateCommand(), inet::ieee80211::Ieee80211MgmtSta::processAuthenticateCommand(), inet::ieee80211::Ieee80211MgmtSta::processDeauthenticateCommand(), inet::Ipv6NeighbourDiscovery::processNudTimeout(), inet::ieee80211::Ieee80211Mib::refreshDisplay(), inet::NetworkInterface::removeMulticastMacAddress(), inet::NetworkInterface::resolveDirective(), inet::ieee80211::Ieee80211MgmtSta::startAssociation(), inet::ieee80211::Ieee80211MgmtSta::startAuthentication(), inet::L3Address::str(), and inet::ArpPacket::str().
tryParse()
bool inet::MacAddress::tryParse (const char * hexstr)
Sets the address and returns true if the syntax of the string is correct.
(See setAddress() for the syntax.)
 {
     if (!hexstr)
         return false;
     // check syntax
     int numHexDigits = 0;
     for (const char *s = hexstr; *s; s++) {
         if (isxdigit(*s))
             numHexDigits++;
         else if (*s != ' ' && *s != ':' && *s != '-')
             return false; // wrong syntax
     }
     if (numHexDigits != 2 * MAC_ADDRESS_SIZE)
         return false;
     // Converts hex string into the address
     // if hext string is shorter, address is filled with zeros;
     // Non-hex characters are discarded before conversion.
     address = 0; // clear top 16 bits too that setAddressByte() calls skip
     int k = 0;
     const char *s = hexstr;
     for (int pos = 0; pos < MAC_ADDRESS_SIZE; pos++) {
         if (!s || !*s) {
             setAddressByte(pos, 0);
         }
         else {
             while (*s && !isxdigit(*s))
                 s++;
             if (!*s) {
                 setAddressByte(pos, 0);
                 continue;
             }
             unsigned char d = isdigit(*s) ? (*s - '0') : islower(*s) ? (*s - 'a' + 10) : (*s - 'A' + 10);
             d = d << 4;
             s++;
             while (*s && !isxdigit(*s))
                 s++;
             if (!*s) {
                 setAddressByte(pos, 0);
                 continue;
             }
             d += isdigit(*s) ? (*s - '0') : islower(*s) ? (*s - 'a' + 10) : (*s - 'A' + 10);
             s++;
             setAddressByte(pos, d);
             k++;
         }
     }
     return true;
 }
Referenced by inet::EtherAppClient::resolveDestMacAddress(), setAddress(), inet::L3Address::tryParse(), and inet::L3AddressResolver::tryParse().
Member Data Documentation
address
uint64_t inet::MacAddress::address private
Referenced by compareTo(), equals(), formInterfaceIdentifier(), getAddressByte(), inet::ieee80211::Ieee80211MgmtSta::handleDisassociationFrame(), MacAddress(), operator!=(), operator<(), operator=(), operator==(), operator>(), inet::ieee80211::Ieee80211MgmtSta::processDisassociateCommand(), setAddressByte(), setAddressBytes(), inet::ieee80211::Ieee80211MgmtSta::storeAPInfo(), and tryParse().
BROADCAST_ADDRESS
const MacAddress inet::MacAddress::BROADCAST_ADDRESS static
The broadcast MAC address, ff:ff:ff:ff:ff:ff.
Referenced by inet::Ipv6::datagramLocalOut(), inet::ProbabilisticBroadcast::encapsulate(), inet::Flooding::encapsulate(), inet::MacAddressType::getBroadcastAddress(), inet::ProbabilisticBroadcast::handleLowerPacket(), inet::Flooding::handleLowerPacket(), inet::BMac::handleSelfMessage(), inet::ProbabilisticBroadcast::handleSelfMessage(), inet::BMac::initialize(), inet::XMac::initialize(), inet::ieee80211::Ieee80211MgmtSta::processScanCommand(), inet::GlobalArp::resolveL3Address(), inet::Ipv4::resolveNextHopMacAddress(), inet::Ipv6::routeMulticastPacket(), inet::Arp::sendArpGratuitous(), inet::Arp::sendArpProbe(), inet::Arp::sendArpRequest(), inet::ieee80211::Ieee80211MgmtAp::sendBeacon(), and inet::BMac::sendPreamble().
CDP_MULTICAST_ADDRESS
const MacAddress inet::MacAddress::CDP_MULTICAST_ADDRESS static
The Cisco discovery protocol bridge's multicast address, 01:00:0C:CC:CC:CC.
LLDP_MULTICAST_ADDRESS
const MacAddress inet::MacAddress::LLDP_MULTICAST_ADDRESS static
The Local link discovery protocol bridge's multicast address, 01:80:C2:00:00:0E.
MULTICAST_PAUSE_ADDRESS
const MacAddress inet::MacAddress::MULTICAST_PAUSE_ADDRESS static
The special multicast PAUSE MAC address, 01:80:C2:00:00:01.
Referenced by inet::EthernetMacBase::dropFrameNotForUs(), inet::EthernetPauseCommandProcessor::handleSendPause(), and inet::EthernetEncapsulation::handleSendPause().
STP_MULTICAST_ADDRESS
const MacAddress inet::MacAddress::STP_MULTICAST_ADDRESS static
The spanning tree protocol bridge's multicast address, 01:80:C2:00:00:00.
Referenced by inet::Stp::generateTCN(), inet::Stp::handleBPDU(), inet::Rstp::initialize(), inet::Stp::initialize(), inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
UNSPECIFIED_ADDRESS
const MacAddress inet::MacAddress::UNSPECIFIED_ADDRESS static
The unspecified MAC address, 00:00:00:00:00:00.
Referenced by inet::ieee80211::OriginatorQosAckPolicy::computeBlockAckReqParameters(), inet::MacAddressType::getLinkLocalAddress(), inet::EthernetMacBase::getMacAddress(), inet::MacAddressType::getUnspecifiedAddress(), inet::Arp::initiateArpResolution(), inet::ieee80211::Ieee80211Mac::isInterfaceRegistered(), inet::GlobalArp::mapUnicastAddress(), inet::Ipv6NeighbourDiscovery::processIpv6Datagram(), inet::Arp::requestTimedOut(), inet::Arp::resolveL3Address(), inet::Ipv6NeighbourDiscovery::resolveNeighbour(), inet::Arp::sendArpProbe(), and inet::NextHopForwarding::sendDatagramToOutput().
The documentation for this class was generated from the following files:
MacAddress.h
MacAddress.cc