INET Framework for OMNeT++/OMNEST: inet::ieee80211::IFrameSequenceHandler::ICallback Class Reference
inet::ieee80211::IFrameSequenceHandler::ICallback Class Reference abstract
#include <IFrameSequenceHandler.h>
Public Member Functions
virtual ~ICallback ()
virtual void transmitFrame (Packet *packet, simtime_t ifs)=0
virtual void originatorProcessRtsProtectionFailed (Packet *packet)=0
virtual void originatorProcessTransmittedFrame (Packet *packet)=0
virtual void originatorProcessReceivedFrame (Packet *packet, Packet *lastTransmittedFrame)=0
virtual void originatorProcessFailedFrame (Packet *packet)=0
virtual void frameSequenceFinished ()=0
virtual void scheduleStartRxTimer (simtime_t timeout)=0
Constructor & Destructor Documentation
~ICallback()
virtual inet::ieee80211::IFrameSequenceHandler::ICallback::~ICallback () inline virtual
 {}
Member Function Documentation
frameSequenceFinished()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::frameSequenceFinished () pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::abortFrameSequence(), and inet::ieee80211::FrameSequenceHandler::finishFrameSequence().
originatorProcessFailedFrame()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::originatorProcessFailedFrame (Packet * packet) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::abortFrameSequence().
originatorProcessReceivedFrame()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::originatorProcessReceivedFrame (Packet * packet, Packet * lastTransmittedFrame) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep().
originatorProcessRtsProtectionFailed()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::originatorProcessRtsProtectionFailed (Packet * packet) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::abortFrameSequence().
originatorProcessTransmittedFrame()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::originatorProcessTransmittedFrame (Packet * packet) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep().
scheduleStartRxTimer()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::scheduleStartRxTimer (simtime_t timeout) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::startFrameSequenceStep().
transmitFrame()
virtual void inet::ieee80211::IFrameSequenceHandler::ICallback::transmitFrame (Packet * packet, simtime_t ifs) pure virtual
Implemented in inet::ieee80211::Hcf, and inet::ieee80211::Dcf.
Referenced by inet::ieee80211::FrameSequenceHandler::startFrameSequenceStep().
The documentation for this class was generated from the following file:
IFrameSequenceHandler.h