INET Framework for OMNeT++/OMNEST: inet::physicallayer::Arrival Class Reference
inet::physicallayer::Arrival Class Reference
#include <Arrival.h>
Public Member Functions
Arrival (const simtime_t startPropagationTime, const simtime_t endPropagationTime, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const simtime_t getStartPropagationTime () const override
virtual const simtime_t getEndPropagationTime () const override
virtual const simtime_t getStartTime () const override
virtual const simtime_t getEndTime () const override
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getPreambleStartTime () const override
virtual const simtime_t getPreambleEndTime () const override
virtual const simtime_t getHeaderStartTime () const override
virtual const simtime_t getHeaderEndTime () const override
virtual const simtime_t getDataStartTime () const override
virtual const simtime_t getDataEndTime () const override
virtual const Coord & getStartPosition () const override
virtual const Coord & getEndPosition () const override
virtual const Quaternion & getStartOrientation () const override
virtual const Quaternion & getEndOrientation () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const simtime_t startPropagationTime
const simtime_t endPropagationTime
const simtime_t startTime
const simtime_t endTime
const simtime_t preambleDuration
const simtime_t headerDuration
const simtime_t dataDuration
const Coord startPosition
const Coord endPosition
const Quaternion startOrientation
const Quaternion endOrientation
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Arrival()
inet::physicallayer::Arrival::Arrival (const simtime_t startPropagationTime, const simtime_t endPropagationTime, const simtime_t startTime, const simtime_t endTime, const simtime_t preambleDuration, const simtime_t headerDuration, const simtime_t dataDuration, const Coord & startPosition, const Coord & endPosition, const Quaternion & startOrientation, const Quaternion & endOrientation)
                                                                                                                                                                                                                                                                                                                                                                          :
     startPropagationTime(startPropagationTime),
     endPropagationTime(endPropagationTime),
     startTime(startTime),
     endTime(endTime),
     preambleDuration(preambleDuration),
     headerDuration(headerDuration),
     dataDuration(dataDuration),
     startPosition(startPosition),
     endPosition(endPosition),
     startOrientation(startOrientation),
     endOrientation(endOrientation)
 {
 }
Member Function Documentation
getDataEndTime()
virtual const simtime_t inet::physicallayer::Arrival::getDataEndTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endTime; }
Referenced by getEndTime().
getDataStartTime()
virtual const simtime_t inet::physicallayer::Arrival::getDataStartTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endTime - dataDuration; }
Referenced by getStartTime().
getEndOrientation()
virtual const Quaternion& inet::physicallayer::Arrival::getEndOrientation () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endOrientation; }
getEndPosition()
virtual const Coord& inet::physicallayer::Arrival::getEndPosition () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endPosition; }
getEndPropagationTime()
virtual const simtime_t inet::physicallayer::Arrival::getEndPropagationTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endPropagationTime; }
getEndTime() [1/2]
virtual const simtime_t inet::physicallayer::Arrival::getEndTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endTime; }
Referenced by getEndTime().
getEndTime() [2/2]
const simtime_t inet::physicallayer::Arrival::getEndTime (IRadioSignal::SignalPart part) const override virtual
Implements inet::physicallayer::IArrival.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getEndTime();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleEndTime();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderEndTime();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataEndTime();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getHeaderEndTime()
virtual const simtime_t inet::physicallayer::Arrival::getHeaderEndTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return endTime - dataDuration; }
Referenced by getEndTime().
getHeaderStartTime()
virtual const simtime_t inet::physicallayer::Arrival::getHeaderStartTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startTime + preambleDuration; }
Referenced by getStartTime().
getPreambleEndTime()
virtual const simtime_t inet::physicallayer::Arrival::getPreambleEndTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startTime + preambleDuration; }
Referenced by getEndTime().
getPreambleStartTime()
virtual const simtime_t inet::physicallayer::Arrival::getPreambleStartTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startTime; }
Referenced by getStartTime().
getStartOrientation()
virtual const Quaternion& inet::physicallayer::Arrival::getStartOrientation () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startOrientation; }
getStartPosition()
virtual const Coord& inet::physicallayer::Arrival::getStartPosition () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startPosition; }
getStartPropagationTime()
virtual const simtime_t inet::physicallayer::Arrival::getStartPropagationTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startPropagationTime; }
getStartTime() [1/2]
virtual const simtime_t inet::physicallayer::Arrival::getStartTime () const inline override virtual
Implements inet::physicallayer::IArrival.
 { return startTime; }
Referenced by getStartTime().
getStartTime() [2/2]
const simtime_t inet::physicallayer::Arrival::getStartTime (IRadioSignal::SignalPart part) const override virtual
Implements inet::physicallayer::IArrival.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getStartTime();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleStartTime();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderStartTime();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataStartTime();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
printToStream()
std::ostream & inet::physicallayer::Arrival::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "Arrival";
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(startPropagationTime)
                << EV_FIELD(endPropagationTime)
                << EV_FIELD(startTime)
                << EV_FIELD(endTime)
                << EV_FIELD(preambleDuration)
                << EV_FIELD(headerDuration)
                << EV_FIELD(dataDuration)
                << EV_FIELD(startPosition)
                << EV_FIELD(endPosition)
                << EV_FIELD(startOrientation)
                << EV_FIELD(endOrientation);
     return stream;
 }
Member Data Documentation
dataDuration
const simtime_t inet::physicallayer::Arrival::dataDuration protected
Referenced by printToStream().
endOrientation
const Quaternion inet::physicallayer::Arrival::endOrientation protected
Referenced by printToStream().
endPosition
const Coord inet::physicallayer::Arrival::endPosition protected
Referenced by printToStream().
endPropagationTime
const simtime_t inet::physicallayer::Arrival::endPropagationTime protected
Referenced by printToStream().
endTime
const simtime_t inet::physicallayer::Arrival::endTime protected
Referenced by printToStream().
headerDuration
const simtime_t inet::physicallayer::Arrival::headerDuration protected
Referenced by printToStream().
preambleDuration
const simtime_t inet::physicallayer::Arrival::preambleDuration protected
Referenced by printToStream().
startOrientation
const Quaternion inet::physicallayer::Arrival::startOrientation protected
Referenced by printToStream().
startPosition
const Coord inet::physicallayer::Arrival::startPosition protected
Referenced by printToStream().
startPropagationTime
const simtime_t inet::physicallayer::Arrival::startPropagationTime protected
Referenced by printToStream().
startTime
const simtime_t inet::physicallayer::Arrival::startTime protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
Arrival.h
Arrival.cc