INET Framework for OMNeT++/OMNEST: inet::sctp::SctpSimpleErrorCauseParameter Class Reference
inet::sctp::SctpSimpleErrorCauseParameter Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:347 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpSimpleErrorCauseParameter (const char *name=nullptr)
SctpSimpleErrorCauseParameter (const SctpSimpleErrorCauseParameter &other)
virtual ~SctpSimpleErrorCauseParameter ()
SctpSimpleErrorCauseParameter & operator= (const SctpSimpleErrorCauseParameter &other)
virtual SctpSimpleErrorCauseParameter * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual uint16_t getValue () const
virtual void setValue (uint16_t value)
Public Member Functions inherited from inet::sctp::SctpParameter
SctpParameter (const char *name=nullptr)
SctpParameter (const SctpParameter &other)
virtual ~SctpParameter ()
SctpParameter & operator= (const SctpParameter &other)
virtual uint16_t getParameterType () const
virtual void setParameterType (uint16_t parameterType)
Protected Member Functions
bool operator== (const SctpSimpleErrorCauseParameter &)=delete
Protected Member Functions inherited from inet::sctp::SctpParameter
bool operator== (const SctpParameter &)=delete
Protected Attributes
uint16_t value = 0
Protected Attributes inherited from inet::sctp::SctpParameter
uint16_t parameterType = 0
Private Member Functions
void copy (const SctpSimpleErrorCauseParameter &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:347 by opp_msgtool.
class SctpSimpleErrorCauseParameter extends SctpParameter
{
    uint16_t value;
}
Constructor & Destructor Documentation
SctpSimpleErrorCauseParameter() [1/2]
inet::sctp::SctpSimpleErrorCauseParameter::SctpSimpleErrorCauseParameter (const char * name = nullptr)
SctpSimpleErrorCauseParameter() [2/2]
inet::sctp::SctpSimpleErrorCauseParameter::SctpSimpleErrorCauseParameter (const SctpSimpleErrorCauseParameter & other)
~SctpSimpleErrorCauseParameter()
virtual inet::sctp::SctpSimpleErrorCauseParameter::~SctpSimpleErrorCauseParameter () virtual
Member Function Documentation
copy()
void inet::sctp::SctpSimpleErrorCauseParameter::copy (const SctpSimpleErrorCauseParameter & other) private
dup()
virtual SctpSimpleErrorCauseParameter* inet::sctp::SctpSimpleErrorCauseParameter::dup () const inline override virtual
Reimplemented from inet::sctp::SctpParameter.
 {return new SctpSimpleErrorCauseParameter(*this);}
getValue()
virtual uint16_t inet::sctp::SctpSimpleErrorCauseParameter::getValue () const virtual
Referenced by inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpSimpleErrorCauseParameter& inet::sctp::SctpSimpleErrorCauseParameter::operator= (const SctpSimpleErrorCauseParameter & other)
operator==()
bool inet::sctp::SctpSimpleErrorCauseParameter::operator== (const SctpSimpleErrorCauseParameter &) protected delete
parsimPack()
virtual void inet::sctp::SctpSimpleErrorCauseParameter::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpSimpleErrorCauseParameter::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpParameter.
Referenced by inet::sctp::doParsimUnpacking().
setValue()
virtual void inet::sctp::SctpSimpleErrorCauseParameter::setValue (uint16_t value) virtual
Referenced by inet::sctp::SctpAssociation::sendHMacError(), and inet::sctp::SctpAssociation::sendInvalidStreamError().
Member Data Documentation
value
uint16_t inet::sctp::SctpSimpleErrorCauseParameter::value = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h