INET Framework for OMNeT++/OMNEST: inet::EigrpRoute< IPAddress > Class Template Reference
inet::EigrpRoute< IPAddress > Class Template Reference
Network destination, it contains state for DUAL.
#include <EigrpRoute.h>
Public Member Functions
EigrpRoute (const IPAddress &address, const IPAddress &mask)
virtual ~EigrpRoute ()
bool operator== (const EigrpRoute< IPAddress > &route) const
int decrementRefCnt ()
void incrementRefCnt ()
int getRefCnt ()
int getRouteId () const
void setRouteId (int routeId)
uint64_t getFd () const
void setFd (uint64_t fd)
EigrpWideMetricPar getRdPar () const
void setRdPar (EigrpWideMetricPar rd)
uint64_t getDij () const
void setDij (uint64_t Dij)
int getQueryOrigin () const
void setQueryOrigin (int queryOrigin)
int getReplyStatusSum () const
bool getReplyStatus (int neighborId)
void setReplyStatus (int neighborId)
bool unsetReplyStatus (int neighborId)
Clear handle for specified neighbor in Reply Status table.
IPAddress getRouteAddress () const
void setRouteAddress (IPAddress routeAddress)
IPAddress getRouteMask () const
void setRouteMask (IPAddress routeMask)
bool isActive () const
EigrpRouteSource< IPAddress > * getSuccessor () const
void setSuccessor (EigrpRouteSource< IPAddress > *successor)
void setNumSucc (int numSuccessors)
int getNumSucc () const
void setUnreachable ()
bool isUpdateSent () const
void setUpdateSent (bool updateSent)
void setNumSentMsgs (int num)
int getNumSentMsgs () const
Protected Attributes
int routeId
IPAddress routeAddress
Unique ID of route.
IPAddress routeMask
Mask of destination.
int queryOrigin
State of DUAL.
std::vector< int > replyStatusTable
Reply status for each neighbor.
uint64_t fd
Feasible distance.
EigrpWideMetricPar rd
Parameters for computation of reported distance that belongs to this router.
uint64_t Dij
Shortest distance (Dij)
EigrpRouteSource< IPAddress > * successor
Actual successor for route reported to neighbors of router.
int numSuccessors
Number of successors for the route.
bool updateSent
Sent update with the route.
int numOfMsgsSent
Number of sent messages with the route.
int referenceCounter
Counts amount of references to this object.
Detailed Description
template<typename IPAddress>
class inet::EigrpRoute< IPAddress >
Network destination, it contains state for DUAL.
Constructor & Destructor Documentation
EigrpRoute()
template<typename IPAddress > inet::EigrpRoute< IPAddress >::EigrpRoute (const IPAddress & address, const IPAddress & mask)
                                                                                  :
     routeId(0), routeAddress(address), routeMask(mask)
 {
     fd = Dij = eigrp::EigrpMetricHelper::METRIC_INF;
     rd.delay = eigrp::EigrpMetricHelper::METRIC_INF;
     successor = nullptr;
     queryOrigin = 1;
     numSuccessors = 0;
     referenceCounter = 0;
     updateSent = false;
     numOfMsgsSent = 0;
 }
~EigrpRoute()
template<typename IPAddress > inet::EigrpRoute< IPAddress >::~EigrpRoute virtual
 {
 }
Member Function Documentation
decrementRefCnt()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::decrementRefCnt () inline
 { return --referenceCounter; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::unlockRoutes(), and inet::eigrp::EigrpIpv6Pdm::unlockRoutes().
getDij()
template<typename IPAddress > uint64_t inet::EigrpRoute< IPAddress >::getDij () const inline
 { return Dij; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::getBestSuccessorByIf(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition13(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition14(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition15(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition16(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition2(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition3(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4().
getFd()
template<typename IPAddress > uint64_t inet::EigrpRoute< IPAddress >::getFd () const inline
 { return fd; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::hasFeasibleSuccessor(), inet::operator<<(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getNumSentMsgs()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::getNumSentMsgs () const inline
 { return numOfMsgsSent; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::sendUpdateToStubs(), and inet::eigrp::EigrpIpv6Pdm::sendUpdateToStubs().
getNumSucc()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::getNumSucc () const inline
 { return numSuccessors; }
Referenced by inet::eigrp::EigrpIpv4Pdm::applySplitHorizon(), inet::eigrp::EigrpIpv6Pdm::applySplitHorizon(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo1Passive().
getQueryOrigin()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::getQueryOrigin () const inline
 { return queryOrigin; }
Referenced by inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition17(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition18(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition5(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition6(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition7(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition8().
getRdPar()
template<typename IPAddress > EigrpWideMetricPar inet::EigrpRoute< IPAddress >::getRdPar () const inline
 { return rd; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createRouteTlv(), and inet::eigrp::EigrpIpv6Pdm::createRouteTlv().
getRefCnt()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::getRefCnt () inline
 { return referenceCounter; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::unlockRoutes(), and inet::eigrp::EigrpIpv6Pdm::unlockRoutes().
getReplyStatus()
template<typename IPAddress > bool inet::EigrpRoute< IPAddress >::getReplyStatus (int neighborId)
 {
     return contains(replyStatusTable, neighborId);
 }
getReplyStatusSum()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::getReplyStatusSum () const inline
 { return replyStatusTable.size(); }
Referenced by inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo0(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo1Active(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo2(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo3(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition10(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition9(), inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
getRouteAddress()
template<typename IPAddress > IPAddress inet::EigrpRoute< IPAddress >::getRouteAddress () const inline
 { return routeAddress; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createRouteTlv(), inet::eigrp::EigrpIpv6Pdm::createRouteTlv(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::findRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::hasFeasibleSuccessor(), inet::eigrp::EigrpIpv4Pdm::installRouteToRT(), inet::eigrp::EigrpIpv6Pdm::installRouteToRT(), inet::eigrp::EigrpIpv4Pdm::isRTSafeForAdd(), inet::eigrp::EigrpIpv6Pdm::isRTSafeForAdd(), inet::operator<<(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processEvent(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::removeRouteFromRT(), inet::eigrp::EigrpIpv6Pdm::removeRouteFromRT(), inet::eigrp::EigrpIpv4Pdm::sendQuery(), inet::eigrp::EigrpIpv6Pdm::sendQuery(), inet::eigrp::EigrpIpv4Pdm::sendReply(), inet::eigrp::EigrpIpv6Pdm::sendReply(), inet::eigrp::EigrpIpv4Pdm::sendUpdate(), inet::eigrp::EigrpIpv6Pdm::sendUpdate(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getRouteId()
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::getRouteId () const inline
 { return routeId; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::findOrCreateRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::findRouteDMin(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getBestSuccessor(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getBestSuccessorByIf(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::hasFeasibleSuccessor(), inet::operator<<(), inet::EigrpRoute< inet::Ipv4Address >::operator==(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getRouteMask()
template<typename IPAddress > IPAddress inet::EigrpRoute< IPAddress >::getRouteMask () const inline
 { return routeMask; }
Referenced by inet::eigrp::EigrpIpv4Pdm::createRouteTlv(), inet::eigrp::EigrpIpv6Pdm::createRouteTlv(), inet::eigrp::EigrpIpv4Pdm::createRTRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::findRoute(), inet::eigrp::EigrpIpv4Pdm::isRTSafeForAdd(), inet::eigrp::EigrpIpv6Pdm::isRTSafeForAdd(), inet::operator<<(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpIpv4Pdm::removeRouteFromRT(), inet::eigrp::EigrpIpv6Pdm::removeRouteFromRT(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
getSuccessor()
template<typename IPAddress > EigrpRouteSource<IPAddress>* inet::EigrpRoute< IPAddress >::getSuccessor () const inline
 { return this->successor; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeOldSuccessor(), and inet::eigrp::EigrpIpv6Pdm::removeOldSuccessor().
incrementRefCnt()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::incrementRefCnt () inline
 { ++referenceCounter; }
Referenced by inet::EigrpRouteSource< inet::Ipv4Address >::EigrpRouteSource().
isActive()
template<typename IPAddress > bool inet::EigrpRoute< IPAddress >::isActive () const inline
 { return replyStatusTable.size() > 0; }
Referenced by inet::operator<<(), inet::eigrp::EigrpIpv4Pdm::removeNeighbor(), inet::eigrp::EigrpIpv6Pdm::removeNeighbor(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::removeRoute(), inet::eigrp::EigrpIpv4Pdm::sendAllEigrpPaths(), and inet::eigrp::EigrpIpv6Pdm::sendAllEigrpPaths().
isUpdateSent()
template<typename IPAddress > bool inet::EigrpRoute< IPAddress >::isUpdateSent () const inline
 { return updateSent; }
operator==()
template<typename IPAddress > bool inet::EigrpRoute< IPAddress >::operator== (const EigrpRoute< IPAddress > & route) const inline
     {
         return routeId == route.getRouteId();
     }
setDij()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setDij (uint64_t Dij) inline
 { this->Dij = Dij; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition10(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition9(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
setFd()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setFd (uint64_t fd) inline
 { this->fd = fd; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo1Passive(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition13(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition15(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition3(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
setNumSentMsgs()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setNumSentMsgs (int num) inline
 { this->numOfMsgsSent = num; }
Referenced by inet::eigrp::EigrpIpv4Pdm::sendUpdateToStubs(), and inet::eigrp::EigrpIpv6Pdm::sendUpdateToStubs().
setNumSucc()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setNumSucc (int numSuccessors) inline
 { this->numSuccessors = numSuccessors; }
Referenced by inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
setQueryOrigin()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setQueryOrigin (int queryOrigin) inline
 { this->queryOrigin = queryOrigin; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition10(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition11(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition12(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition13(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition14(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition16(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition3(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition5(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition9().
setRdPar()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setRdPar (EigrpWideMetricPar rd) inline
 { this->rd = rd; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition3(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
setReplyStatus()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setReplyStatus (int neighborId) inline
 { replyStatusTable.push_back(neighborId); }
Referenced by inet::eigrp::EigrpIpv4Pdm::setReplyStatusTable(), and inet::eigrp::EigrpIpv6Pdm::setReplyStatusTable().
setRouteAddress()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setRouteAddress (IPAddress routeAddress) inline
 { this->routeAddress = routeAddress; }
setRouteId()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setRouteId (int routeId) inline
 { this->routeId = routeId; }
Referenced by inet::eigrp::EigrpTopologyTable< Ipv4Address >::addRouteInfo().
setRouteMask()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setRouteMask (IPAddress routeMask) inline
 { this->routeMask = routeMask; }
setSuccessor()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setSuccessor (EigrpRouteSource< IPAddress > * successor) inline
 { this->successor = successor; }
Referenced by inet::eigrp::EigrpIpv4Pdm::removeOldSuccessor(), inet::eigrp::EigrpIpv6Pdm::removeOldSuccessor(), inet::eigrp::EigrpIpv4Pdm::updateRoute(), and inet::eigrp::EigrpIpv6Pdm::updateRoute().
setUnreachable()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setUnreachable () inline
 { Dij = eigrp::EigrpMetricHelper::METRIC_INF; rd.delay = eigrp::EigrpMetricHelper::DELAY_INF; rd.bandwidth = eigrp::EigrpMetricHelper::BANDWIDTH_INF; }
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition4().
setUpdateSent()
template<typename IPAddress > void inet::EigrpRoute< IPAddress >::setUpdateSent (bool updateSent) inline
 { this->updateSent = updateSent; }
Referenced by inet::eigrp::EigrpIpv4Pdm::sendUpdateToStubs(), and inet::eigrp::EigrpIpv6Pdm::sendUpdateToStubs().
unsetReplyStatus()
template<typename IPAddress > bool inet::EigrpRoute< IPAddress >::unsetReplyStatus (int neighborId)
Clear handle for specified neighbor in Reply Status table.
 {
     auto it = find(replyStatusTable, neighborId);
     if (it != replyStatusTable.end()) {
         replyStatusTable.erase(it);
         return true;
     }
     return false;
 } // eigrp
Referenced by inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo0(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo1Active(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo2(), and inet::eigrp::EigrpDual< inet::Ipv4Address >::processQo3().
Member Data Documentation
Dij
template<typename IPAddress > uint64_t inet::EigrpRoute< IPAddress >::Dij protected
Shortest distance (Dij)
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getDij(), inet::EigrpRoute< inet::Ipv4Address >::setDij(), and inet::EigrpRoute< inet::Ipv4Address >::setUnreachable().
fd
template<typename IPAddress > uint64_t inet::EigrpRoute< IPAddress >::fd protected
Feasible distance.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getFd(), and inet::EigrpRoute< inet::Ipv4Address >::setFd().
numOfMsgsSent
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::numOfMsgsSent protected
Number of sent messages with the route.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getNumSentMsgs().
numSuccessors
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::numSuccessors protected
Number of successors for the route.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getNumSucc(), and inet::EigrpRoute< inet::Ipv4Address >::setNumSucc().
queryOrigin
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::queryOrigin protected
State of DUAL.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getQueryOrigin(), and inet::EigrpRoute< inet::Ipv4Address >::setQueryOrigin().
rd
template<typename IPAddress > EigrpWideMetricPar inet::EigrpRoute< IPAddress >::rd protected
Parameters for computation of reported distance that belongs to this router.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getRdPar(), inet::EigrpRoute< inet::Ipv4Address >::setRdPar(), and inet::EigrpRoute< inet::Ipv4Address >::setUnreachable().
referenceCounter
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::referenceCounter protected
Counts amount of references to this object.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::decrementRefCnt(), inet::EigrpRoute< inet::Ipv4Address >::getRefCnt(), and inet::EigrpRoute< inet::Ipv4Address >::incrementRefCnt().
replyStatusTable
template<typename IPAddress > std::vector<int> inet::EigrpRoute< IPAddress >::replyStatusTable protected
Reply status for each neighbor.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getReplyStatusSum(), inet::EigrpRoute< inet::Ipv4Address >::isActive(), and inet::EigrpRoute< inet::Ipv4Address >::setReplyStatus().
routeAddress
template<typename IPAddress > IPAddress inet::EigrpRoute< IPAddress >::routeAddress protected
Unique ID of route.
IP address of destination
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getRouteAddress(), and inet::EigrpRoute< inet::Ipv4Address >::setRouteAddress().
routeId
template<typename IPAddress > int inet::EigrpRoute< IPAddress >::routeId protected
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getRouteId(), inet::EigrpRoute< inet::Ipv4Address >::operator==(), and inet::EigrpRoute< inet::Ipv4Address >::setRouteId().
routeMask
template<typename IPAddress > IPAddress inet::EigrpRoute< IPAddress >::routeMask protected
Mask of destination.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getRouteMask(), and inet::EigrpRoute< inet::Ipv4Address >::setRouteMask().
successor
template<typename IPAddress > EigrpRouteSource<IPAddress>* inet::EigrpRoute< IPAddress >::successor protected
Actual successor for route reported to neighbors of router.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::getSuccessor(), and inet::EigrpRoute< inet::Ipv4Address >::setSuccessor().
updateSent
template<typename IPAddress > bool inet::EigrpRoute< IPAddress >::updateSent protected
Sent update with the route.
Referenced by inet::EigrpRoute< inet::Ipv4Address >::isUpdateSent(), and inet::EigrpRoute< inet::Ipv4Address >::setUpdateSent().
The documentation for this class was generated from the following file:
EigrpRoute.h