INET Framework for OMNeT++/OMNEST: inet::power::IEpEnergyGenerator Class Reference
inet::power::IEpEnergyGenerator Class Reference abstract
TODO.
#include <IEpEnergyGenerator.h>
Public Member Functions
virtual W getPowerGeneration () const =0
Returns the power generation in the range [0, +infinity).
Public Member Functions inherited from inet::power::IEnergyGenerator
virtual ~IEnergyGenerator ()
virtual IEnergySink * getEnergySink () const =0
Returns the energy sink that absorbs energy from this energy generator.
Static Public Attributes
static simsignal_t powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged")
The signal that is used to publish power generation changes.
Detailed Description
TODO.
See the corresponding NED file for more details.
Member Function Documentation
getPowerGeneration()
virtual W inet::power::IEpEnergyGenerator::getPowerGeneration () const pure virtual
Returns the power generation in the range [0, +infinity).
Implemented in inet::power::AlternatingEpEnergyGenerator.
Member Data Documentation
powerGenerationChangedSignal
simsignal_t inet::power::IEpEnergyGenerator::powerGenerationChangedSignal = cComponent::registerSignal("powerGenerationChanged") static
The signal that is used to publish power generation changes.
Referenced by inet::power::EpEnergySinkBase::addEnergyGenerator(), inet::power::EpEnergyStorageBase::receiveSignal(), and inet::power::EpEnergySinkBase::removeEnergyGenerator().
The documentation for this class was generated from the following files:
IEpEnergyGenerator.h
IEpEnergyGenerator.cc