INET Framework for OMNeT++/OMNEST: inet::MacAddressTagBase Class Reference
inet::MacAddressTagBase Class Reference
Class generated from inet/linklayer/common/MacAddressTag.msg:14 by opp_msgtool.
#include <MacAddressTag_m.h>
Public Member Functions
MacAddressTagBase ()
MacAddressTagBase (const MacAddressTagBase &other)
virtual ~MacAddressTagBase ()
MacAddressTagBase & operator= (const MacAddressTagBase &other)
virtual MacAddressTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const MacAddress & getSrcAddress () const
virtual MacAddress & getSrcAddressForUpdate ()
virtual void setSrcAddress (const MacAddress &srcAddress)
virtual const MacAddress & getDestAddress () const
virtual MacAddress & getDestAddressForUpdate ()
virtual void setDestAddress (const MacAddress &destAddress)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const MacAddressTagBase &)=delete
Protected Attributes
MacAddress srcAddress
MacAddress destAddress
Private Member Functions
void copy (const MacAddressTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/common/MacAddressTag.msg:14 by opp_msgtool.
class MacAddressTagBase extends TagBase
{
    MacAddress srcAddress;      // may be unspecified
    MacAddress destAddress; // always specified
}
Constructor & Destructor Documentation
MacAddressTagBase() [1/2]
inet::MacAddressTagBase::MacAddressTagBase ()
MacAddressTagBase() [2/2]
inet::MacAddressTagBase::MacAddressTagBase (const MacAddressTagBase & other)
~MacAddressTagBase()
virtual inet::MacAddressTagBase::~MacAddressTagBase () virtual
Member Function Documentation
copy()
void inet::MacAddressTagBase::copy (const MacAddressTagBase & other) private
dup()
virtual MacAddressTagBase* inet::MacAddressTagBase::dup () const inline override virtual
Reimplemented in inet::MacAddressInd, and inet::MacAddressReq.
 {return new MacAddressTagBase(*this);}
getDestAddress()
virtual const MacAddress& inet::MacAddressTagBase::getDestAddress () const virtual
Referenced by inet::ieee80211::Ieee80211Portal::decapsulate(), inet::ieee80211::Ieee80211Mac::encapsulate(), inet::CsmaCaMac::encapsulate(), inet::ieee80211::Ieee80211Mac::handleMgmtPacket(), inet::Ieee8021dRelay::handleUpperPacket(), and inet::SendToMacAddress::processPacket().
getDestAddressForUpdate()
virtual MacAddress& inet::MacAddressTagBase::getDestAddressForUpdate () inline virtual
 { return const_cast<MacAddress&>(const_cast<MacAddressTagBase*>(this)->getDestAddress());}
getSrcAddress()
virtual const MacAddress& inet::MacAddressTagBase::getSrcAddress () const virtual
Referenced by inet::ieee80211::Ieee80211Portal::decapsulate(), inet::MacRelayUnit::handleLowerPacket(), inet::Ieee8021dRelay::handleLowerPacket(), inet::EthernetAddressInserter::processPacket(), inet::EthernetMacHeaderInserter::processPacket(), and inet::EthernetEncapsulation::processPacketFromHigherLayer().
getSrcAddressForUpdate()
virtual MacAddress& inet::MacAddressTagBase::getSrcAddressForUpdate () inline virtual
 { return const_cast<MacAddress&>(const_cast<MacAddressTagBase*>(this)->getSrcAddress());}
operator=()
MacAddressTagBase& inet::MacAddressTagBase::operator= (const MacAddressTagBase & other)
operator==()
bool inet::MacAddressTagBase::operator== (const MacAddressTagBase &) protected delete
parsimPack()
virtual void inet::MacAddressTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::MacAddressInd, and inet::MacAddressReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::MacAddressTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::MacAddressInd, and inet::MacAddressReq.
Referenced by inet::doParsimUnpacking().
setDestAddress()
virtual void inet::MacAddressTagBase::setDestAddress (const MacAddress & destAddress) virtual
Referenced by inet::EthernetSocketIo::handleMessageWhenUp(), and inet::Ieee8022LlcSocketIo::handleMessageWhenUp().
setSrcAddress()
virtual void inet::MacAddressTagBase::setSrcAddress (const MacAddress & srcAddress) virtual
Referenced by inet::ieee80211::Ieee80211Mac::decapsulate(), inet::CsmaCaMac::decapsulate(), inet::AckingMac::encapsulate(), inet::CsmaCaMac::encapsulate(), inet::Stp::generateBPDU(), inet::Stp::generateTCN(), inet::MacRelayUnit::handleLowerPacket(), inet::Ieee8021dRelay::handleLowerPacket(), inet::Stp::handleTCN(), inet::PacketDirectionReverser::processPacket(), inet::EthernetMac::processReceivedDataFrame(), inet::CsmaCaMac::sendAckFrame(), inet::Arp::sendArpGratuitous(), inet::Arp::sendArpProbe(), inet::Rstp::sendBPDU(), and inet::Rstp::sendTCNtoRoot().
Member Data Documentation
destAddress
MacAddress inet::MacAddressTagBase::destAddress protected
srcAddress
MacAddress inet::MacAddressTagBase::srcAddress protected
The documentation for this class was generated from the following file:
MacAddressTag_m.h