INET Framework for OMNeT++/OMNEST: inet::sctp::SctpDataChunk Class Reference
inet::sctp::SctpDataChunk Class Reference
Class generated from inet/transportlayer/sctp/SctpHeader.msg:135 by opp_msgtool.
#include <SctpHeader_m.h>
Public Member Functions
SctpDataChunk (const char *name=nullptr)
SctpDataChunk (const SctpDataChunk &other)
virtual ~SctpDataChunk ()
SctpDataChunk & operator= (const SctpDataChunk &other)
virtual SctpDataChunk * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getEBit () const
virtual void setEBit (bool eBit)
virtual bool getBBit () const
virtual void setBBit (bool bBit)
virtual bool getUBit () const
virtual void setUBit (bool uBit)
virtual bool getIBit () const
virtual void setIBit (bool iBit)
virtual uint32_t getTsn () const
virtual void setTsn (uint32_t tsn)
virtual uint16_t getSid () const
virtual void setSid (uint16_t sid)
virtual uint16_t getSsn () const
virtual void setSsn (uint16_t ssn)
virtual uint32_t getPpid () const
virtual void setPpid (uint32_t ppid)
virtual ::omnetpp::simtime_t getEnqueuingTime () const
virtual void setEnqueuingTime (::omnetpp::simtime_t enqueuingTime)
virtual ::omnetpp::simtime_t getFirstSendTime () const
virtual void setFirstSendTime (::omnetpp::simtime_t firstSendTime)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Member Functions
bool operator== (const SctpDataChunk &)=delete
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Protected Attributes
bool eBit = 0
bool bBit = 0
bool uBit = 0
bool iBit = 0
uint32_t tsn = 0
uint16_t sid = 0
uint16_t ssn = 0
uint32_t ppid = 0
::omnetpp::simtime_t enqueuingTime = SIMTIME_ZERO
::omnetpp::simtime_t firstSendTime = SIMTIME_ZERO
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpDataChunk &other)
Detailed Description
Class generated from inet/transportlayer/sctp/SctpHeader.msg:135 by opp_msgtool.
class SctpDataChunk extends SctpChunk
{
    // Chunk Flags
    bool eBit = 0;
    bool bBit = 0;
    bool uBit = 0;
    bool iBit = 0;
    // Transmission Sequence Number
    uint32_t tsn;
    // Stream identifier
    uint16_t sid;
    // Stream Sequence Number
    uint16_t ssn;
    // Payload Protocol Identifier
    uint32_t ppid;
    simtime_t enqueuingTime;
    simtime_t firstSendTime;
}
Constructor & Destructor Documentation
SctpDataChunk() [1/2]
inet::sctp::SctpDataChunk::SctpDataChunk (const char * name = nullptr)
SctpDataChunk() [2/2]
inet::sctp::SctpDataChunk::SctpDataChunk (const SctpDataChunk & other)
~SctpDataChunk()
virtual inet::sctp::SctpDataChunk::~SctpDataChunk () virtual
Member Function Documentation
copy()
void inet::sctp::SctpDataChunk::copy (const SctpDataChunk & other) private
dup()
virtual SctpDataChunk* inet::sctp::SctpDataChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpChunk.
 {return new SctpDataChunk(*this);}
getBBit()
virtual bool inet::sctp::SctpDataChunk::getBBit () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), and inet::sctp::SctpHeaderSerializer::serialize().
getEBit()
virtual bool inet::sctp::SctpDataChunk::getEBit () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), and inet::sctp::SctpHeaderSerializer::serialize().
getEnqueuingTime()
virtual ::omnetpp::simtime_t inet::sctp::SctpDataChunk::getEnqueuingTime () const
getFirstSendTime()
virtual ::omnetpp::simtime_t inet::sctp::SctpDataChunk::getFirstSendTime () const
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg().
getIBit()
virtual bool inet::sctp::SctpDataChunk::getIBit () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), inet::sctp::SctpAssociation::processDataArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getPpid()
virtual uint32_t inet::sctp::SctpDataChunk::getPpid () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), and inet::sctp::SctpHeaderSerializer::serialize().
getSid()
virtual uint16_t inet::sctp::SctpDataChunk::getSid () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), inet::sctp::SctpAssociation::processDataArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getSsn()
virtual uint16_t inet::sctp::SctpDataChunk::getSsn () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), inet::sctp::SctpAssociation::sendOnPath(), and inet::sctp::SctpHeaderSerializer::serialize().
getTsn()
virtual uint32_t inet::sctp::SctpDataChunk::getTsn () const virtual
Referenced by inet::sctp::SctpAssociation::loadPacket(), inet::sctp::SctpAssociation::makeVarFromMsg(), inet::sctp::SctpAssociation::processDataArrived(), inet::sctp::SctpAssociation::processPacketDropArrived(), inet::sctp::SctpAssociation::sendOnPath(), inet::sctp::SctpHeaderSerializer::serialize(), and inet::sctp::SctpAssociation::storePacket().
getUBit()
virtual bool inet::sctp::SctpDataChunk::getUBit () const virtual
Referenced by inet::sctp::SctpAssociation::makeVarFromMsg(), inet::sctp::SctpAssociation::processDataArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
operator=()
SctpDataChunk& inet::sctp::SctpDataChunk::operator= (const SctpDataChunk & other)
operator==()
bool inet::sctp::SctpDataChunk::operator== (const SctpDataChunk &) protected delete
parsimPack()
virtual void inet::sctp::SctpDataChunk::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimPacking().
parsimUnpack()
virtual void inet::sctp::SctpDataChunk::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::sctp::SctpChunk.
Referenced by inet::sctp::doParsimUnpacking().
setBBit()
virtual void inet::sctp::SctpDataChunk::setBBit (bool bBit) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setEBit()
virtual void inet::sctp::SctpDataChunk::setEBit (bool eBit) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setEnqueuingTime()
virtual void inet::sctp::SctpDataChunk::setEnqueuingTime (::omnetpp::simtime_t enqueuingTime) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setFirstSendTime()
virtual void inet::sctp::SctpDataChunk::setFirstSendTime (::omnetpp::simtime_t firstSendTime) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setIBit()
virtual void inet::sctp::SctpDataChunk::setIBit (bool iBit) virtual
Referenced by inet::sctp::SctpAssociation::sendOnPath(), and inet::sctp::SctpAssociation::transformDataChunk().
setPpid()
virtual void inet::sctp::SctpDataChunk::setPpid (uint32_t ppid) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setSid()
virtual void inet::sctp::SctpDataChunk::setSid (uint16_t sid) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setSsn()
virtual void inet::sctp::SctpDataChunk::setSsn (uint16_t ssn) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setTsn()
virtual void inet::sctp::SctpDataChunk::setTsn (uint32_t tsn) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
setUBit()
virtual void inet::sctp::SctpDataChunk::setUBit (bool uBit) virtual
Referenced by inet::sctp::SctpAssociation::transformDataChunk().
Member Data Documentation
bBit
bool inet::sctp::SctpDataChunk::bBit = 0 protected
eBit
bool inet::sctp::SctpDataChunk::eBit = 0 protected
enqueuingTime
::omnetpp::simtime_t inet::sctp::SctpDataChunk::enqueuingTime = SIMTIME_ZERO protected
firstSendTime
::omnetpp::simtime_t inet::sctp::SctpDataChunk::firstSendTime = SIMTIME_ZERO protected
iBit
bool inet::sctp::SctpDataChunk::iBit = 0 protected
ppid
uint32_t inet::sctp::SctpDataChunk::ppid = 0 protected
sid
uint16_t inet::sctp::SctpDataChunk::sid = 0 protected
ssn
uint16_t inet::sctp::SctpDataChunk::ssn = 0 protected
tsn
uint32_t inet::sctp::SctpDataChunk::tsn = 0 protected
uBit
bool inet::sctp::SctpDataChunk::uBit = 0 protected
The documentation for this class was generated from the following file:
SctpHeader_m.h