INET Framework for OMNeT++/OMNEST: inet::ieee80211::IFrameSequence Class Reference
inet::ieee80211::IFrameSequence Class Reference abstract
#include <IFrameSequence.h>
Public Member Functions
virtual ~IFrameSequence ()
virtual void startSequence (FrameSequenceContext *context, int step)=0
virtual IFrameSequenceStep * prepareStep (FrameSequenceContext *context)=0
virtual bool completeStep (FrameSequenceContext *context)=0
virtual std::string getHistory () const =0
Constructor & Destructor Documentation
~IFrameSequence()
virtual inet::ieee80211::IFrameSequence::~IFrameSequence () inline virtual
 {}
Member Function Documentation
completeStep()
virtual bool inet::ieee80211::IFrameSequence::completeStep (FrameSequenceContext * context) pure virtual
Implemented in inet::ieee80211::BlockAckReqBlockAckFs, inet::ieee80211::LastFrameAckFs, inet::ieee80211::FragFrameAckFs, inet::ieee80211::CtsFs, inet::ieee80211::RtsFs, inet::ieee80211::AlternativesFs, inet::ieee80211::RtsCtsFs, inet::ieee80211::RepeatingFs, inet::ieee80211::AckFs, inet::ieee80211::ManagementFs, inet::ieee80211::OptionalFs, inet::ieee80211::ManagementAckFs, inet::ieee80211::DataFs, inet::ieee80211::SequentialFs, and inet::ieee80211::SelfCtsFs.
Referenced by inet::ieee80211::OptionalFs::completeStep(), inet::ieee80211::RepeatingFs::completeStep(), and inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep().
getHistory()
virtual std::string inet::ieee80211::IFrameSequence::getHistory () const pure virtual
Implemented in inet::ieee80211::BlockAckReqBlockAckFs, inet::ieee80211::LastFrameAckFs, inet::ieee80211::FragFrameAckFs, inet::ieee80211::CtsFs, inet::ieee80211::RtsFs, inet::ieee80211::AlternativesFs, inet::ieee80211::RtsCtsFs, inet::ieee80211::RepeatingFs, inet::ieee80211::AckFs, inet::ieee80211::ManagementFs, inet::ieee80211::OptionalFs, inet::ieee80211::ManagementAckFs, inet::ieee80211::DataFs, inet::ieee80211::SequentialFs, and inet::ieee80211::SelfCtsFs.
Referenced by inet::ieee80211::RepeatingFs::completeStep(), inet::ieee80211::FrameSequenceHandler::finishFrameSequenceStep(), inet::ieee80211::OptionalFs::getHistory(), inet::ieee80211::RepeatingFs::repeatSequence(), inet::ieee80211::FrameSequenceHandler::startFrameSequenceStep(), and inet::ieee80211::RepeatingFs::startSequence().
prepareStep()
virtual IFrameSequenceStep* inet::ieee80211::IFrameSequence::prepareStep (FrameSequenceContext * context) pure virtual
Implemented in inet::ieee80211::BlockAckReqBlockAckFs, inet::ieee80211::LastFrameAckFs, inet::ieee80211::FragFrameAckFs, inet::ieee80211::CtsFs, inet::ieee80211::RtsFs, inet::ieee80211::AlternativesFs, inet::ieee80211::RtsCtsFs, inet::ieee80211::RepeatingFs, inet::ieee80211::AckFs, inet::ieee80211::ManagementFs, inet::ieee80211::OptionalFs, inet::ieee80211::ManagementAckFs, inet::ieee80211::DataFs, inet::ieee80211::SequentialFs, and inet::ieee80211::SelfCtsFs.
Referenced by inet::ieee80211::OptionalFs::prepareStep(), inet::ieee80211::RepeatingFs::prepareStep(), and inet::ieee80211::FrameSequenceHandler::startFrameSequenceStep().
startSequence()
virtual void inet::ieee80211::IFrameSequence::startSequence (FrameSequenceContext * context, int step) pure virtual
Implemented in inet::ieee80211::BlockAckReqBlockAckFs, inet::ieee80211::LastFrameAckFs, inet::ieee80211::FragFrameAckFs, inet::ieee80211::CtsFs, inet::ieee80211::RtsFs, inet::ieee80211::AlternativesFs, inet::ieee80211::RtsCtsFs, inet::ieee80211::RepeatingFs, inet::ieee80211::AckFs, inet::ieee80211::ManagementFs, inet::ieee80211::OptionalFs, inet::ieee80211::ManagementAckFs, inet::ieee80211::DataFs, inet::ieee80211::SequentialFs, and inet::ieee80211::SelfCtsFs.
Referenced by inet::ieee80211::RepeatingFs::repeatSequence(), inet::ieee80211::FrameSequenceHandler::startFrameSequence(), inet::ieee80211::OptionalFs::startSequence(), and inet::ieee80211::RepeatingFs::startSequence().
The documentation for this class was generated from the following file:
IFrameSequence.h