INET Framework for OMNeT++/OMNEST: inet::ieee80211::IOriginatorBlockAckAgreementPolicy Class Reference
inet::ieee80211::IOriginatorBlockAckAgreementPolicy Class Reference abstract
#include <IOriginatorBlockAckAgreementPolicy.h>
Public Member Functions
virtual ~IOriginatorBlockAckAgreementPolicy ()
virtual bool isAddbaReqNeeded (Packet *packet, const Ptr< const Ieee80211DataHeader > &header)=0
virtual bool isAddbaReqAccepted (const Ptr< const Ieee80211AddbaResponse > &addbaResp, OriginatorBlockAckAgreement *agreement)=0
virtual bool isDelbaAccepted (const Ptr< const Ieee80211Delba > &delba)=0
virtual bool isMsduSupported () const =0
virtual simtime_t computeAddbaFailureTimeout () const =0
virtual simtime_t getBlockAckTimeoutValue () const =0
virtual bool isDelayedAckPolicySupported () const =0
virtual int getMaximumAllowedBufferSize () const =0
Constructor & Destructor Documentation
~IOriginatorBlockAckAgreementPolicy()
virtual inet::ieee80211::IOriginatorBlockAckAgreementPolicy::~IOriginatorBlockAckAgreementPolicy () inline virtual
 {}
Member Function Documentation
computeAddbaFailureTimeout()
virtual simtime_t inet::ieee80211::IOriginatorBlockAckAgreementPolicy::computeAddbaFailureTimeout () const pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
getBlockAckTimeoutValue()
virtual simtime_t inet::ieee80211::IOriginatorBlockAckAgreementPolicy::getBlockAckTimeoutValue () const pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::buildAddbaRequest().
getMaximumAllowedBufferSize()
virtual int inet::ieee80211::IOriginatorBlockAckAgreementPolicy::getMaximumAllowedBufferSize () const pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::buildAddbaRequest().
isAddbaReqAccepted()
virtual bool inet::ieee80211::IOriginatorBlockAckAgreementPolicy::isAddbaReqAccepted (const Ptr< const Ieee80211AddbaResponse > & addbaResp, OriginatorBlockAckAgreement * agreement) pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::processReceivedAddbaResp().
isAddbaReqNeeded()
virtual bool inet::ieee80211::IOriginatorBlockAckAgreementPolicy::isAddbaReqNeeded (Packet * packet, const Ptr< const Ieee80211DataHeader > & header) pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::processTransmittedDataFrame().
isDelayedAckPolicySupported()
virtual bool inet::ieee80211::IOriginatorBlockAckAgreementPolicy::isDelayedAckPolicySupported () const pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::buildAddbaRequest().
isDelbaAccepted()
virtual bool inet::ieee80211::IOriginatorBlockAckAgreementPolicy::isDelbaAccepted (const Ptr< const Ieee80211Delba > & delba) pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::processReceivedDelba().
isMsduSupported()
virtual bool inet::ieee80211::IOriginatorBlockAckAgreementPolicy::isMsduSupported () const pure virtual
Implemented in inet::ieee80211::OriginatorBlockAckAgreementPolicy.
Referenced by inet::ieee80211::OriginatorBlockAckAgreementHandler::buildAddbaRequest().
The documentation for this class was generated from the following file:
IOriginatorBlockAckAgreementPolicy.h