INET Framework for OMNeT++/OMNEST: inet::ospfv2::Ospfv2RoutingTableEntry Class Reference
inet::ospfv2::Ospfv2RoutingTableEntry Class Reference
#include <Ospfv2RoutingTableEntry.h>
Public Types
enum RoutingPathType { INTRAAREA = 0, INTERAREA = 1, TYPE1_EXTERNAL = 2, TYPE2_EXTERNAL = 3 }
typedef unsigned char RoutingDestinationType
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Public Member Functions
Ospfv2RoutingTableEntry (IInterfaceTable *ift)
Ospfv2RoutingTableEntry (const Ospfv2RoutingTableEntry &entry)
virtual ~Ospfv2RoutingTableEntry ()
bool operator== (const Ospfv2RoutingTableEntry &entry) const
bool operator!= (const Ospfv2RoutingTableEntry &entry) const
void setDestinationType (RoutingDestinationType type)
RoutingDestinationType getDestinationType () const
void setOptionalCapabilities (Ospfv2Options options)
Ospfv2Options getOptionalCapabilities () const
void setArea (AreaId source)
AreaId getArea () const
void setPathType (RoutingPathType type)
RoutingPathType getPathType () const
Metric getCost () const
void setCost (Metric cost)
void setType2Cost (Metric type2Cost)
Metric getType2Cost () const
void setLinkStateOrigin (const Ospfv2Lsa *lsa)
const Ospfv2Lsa * getLinkStateOrigin () const
void addNextHop (NextHop hop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
virtual std::string str () const
Public Member Functions inherited from inet::Ipv4Route
Ipv4Route ()
virtual ~Ipv4Route ()
virtual std::string detailedInfo () const
bool operator== (const Ipv4Route &route) const
bool operator!= (const Ipv4Route &route) const
bool equals (const Ipv4Route &route) const
virtual void setRoutingTable (IIpv4RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
IIpv4RoutingTable * getRoutingTable () const
virtual bool isValid () const
test validity of route entry, e.g.
virtual void setDestination (Ipv4Address _dest)
virtual void setNetmask (Ipv4Address _netmask)
virtual void setGateway (Ipv4Address _gateway)
virtual void setInterface (NetworkInterface *_interfacePtr) override
virtual void setSourceType (SourceType _source) override
const char * getSourceTypeAbbreviation () const
virtual void setAdminDist (unsigned int _adminDist) override
virtual void setMetric (int _metric) override
const Ipv4Address & getDestination () const
Destination address prefix to match.
const Ipv4Address & getNetmask () const
Represents length of prefix to match.
const Ipv4Address & getGateway () const
Next hop address.
NetworkInterface * getInterface () const override
Next hop interface.
const char * getInterfaceName () const
Convenience method.
SourceType getSourceType () const override
Source of route.
unsigned int getAdminDist () const
Route source specific preference value.
int getMetric () const override
"Cost" to reach the destination
void setSource (cObject *_source) override
cObject * getSource () const override
Source of route.
cObject * getProtocolData () const override
void setProtocolData (cObject *protocolData) override
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int len) override
virtual void setNextHop (const L3Address &nextHop) override
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
virtual void setSourceType (SourceType type)=0
Static Public Member Functions
static const char * getDestinationTypeString (RoutingDestinationType destType)
static const char * getPathTypeString (RoutingPathType pathType)
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Static Public Attributes
static const unsigned char NETWORK_DESTINATION = 0
static const unsigned char AREA_BORDER_ROUTER_DESTINATION = 1
static const unsigned char AS_BOUNDARY_ROUTER_DESTINATION = 2
Private Attributes
IInterfaceTable * ift = nullptr
RoutingDestinationType destinationType = 0
Ospfv2Options optionalCapabilities
AreaId area
RoutingPathType pathType = static_cast<RoutingPathType>(-1)
Metric cost = 0
Metric type2Cost = 0
const Ospfv2Lsa * linkStateOrigin = nullptr
std::vector< NextHop > nextHops
Additional Inherited Members
Protected Member Functions inherited from inet::Ipv4Route
void changed (int fieldCode)
Member Typedef Documentation
RoutingDestinationType
typedef unsigned char inet::ospfv2::Ospfv2RoutingTableEntry::RoutingDestinationType
Member Enumeration Documentation
RoutingPathType
enum inet::ospfv2::Ospfv2RoutingTableEntry::RoutingPathType
Enumerator
INTRAAREA
INTERAREA
TYPE1_EXTERNAL
TYPE2_EXTERNAL
{
         INTRAAREA      = 0,
         INTERAREA      = 1,
         TYPE1_EXTERNAL = 2,
         TYPE2_EXTERNAL = 3
     };
Constructor & Destructor Documentation
Ospfv2RoutingTableEntry() [1/2]
inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry (IInterfaceTable * ift)
                                                                       :
     ift(_ift),
     destinationType(Ospfv2RoutingTableEntry::NETWORK_DESTINATION),
     area(BACKBONE_AREAID),
     pathType(Ospfv2RoutingTableEntry::INTRAAREA)
 {
     setNetmask(Ipv4Address::ALLONES_ADDRESS);
     setSourceType(IRoute::OSPF);
     setAdminDist(Ipv4Route::dOSPF);
 }
Ospfv2RoutingTableEntry() [2/2]
inet::ospfv2::Ospfv2RoutingTableEntry::Ospfv2RoutingTableEntry (const Ospfv2RoutingTableEntry & entry)
                                                                                      :
     ift(entry.ift),
     destinationType(entry.destinationType),
     optionalCapabilities(entry.optionalCapabilities),
     area(entry.area),
     pathType(entry.pathType),
     cost(entry.cost),
     type2Cost(entry.type2Cost),
     linkStateOrigin(entry.linkStateOrigin),
     nextHops(entry.nextHops)
 {
     setDestination(entry.getDestination());
     setNetmask(entry.getNetmask());
     setInterface(entry.getInterface());
     setGateway(entry.getGateway());
     setSourceType(entry.getSourceType());
     setMetric(entry.getMetric());
     setAdminDist(entry.getAdminDist());
 }
~Ospfv2RoutingTableEntry()
virtual inet::ospfv2::Ospfv2RoutingTableEntry::~Ospfv2RoutingTableEntry () inline virtual
 {}
Member Function Documentation
addNextHop()
void inet::ospfv2::Ospfv2RoutingTableEntry::addNextHop (NextHop hop)
 {
     if (nextHops.size() == 0) {
         NetworkInterface *routingInterface = ift->getInterfaceById(hop.ifIndex);
         setInterface(routingInterface);
         // TODO this used to be commented out, but it seems we need it
         // otherwise gateways will never be filled in and gateway is needed for broadcast networks
         setGateway(hop.hopAddress);
     }
     else {
         for (size_t i = 0; i < nextHops.size(); i++) {
             if (hop.ifIndex == nextHops.at(i).ifIndex && hop.hopAddress == nextHops.at(i).hopAddress)
                 return;
         }
     }
     nextHops.push_back(hop);
 }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::Router::getPreferredEntry(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
clearNextHops()
void inet::ospfv2::Ospfv2RoutingTableEntry::clearNextHops () inline
 { nextHops.clear(); }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Router::getPreferredEntry(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
getArea()
AreaId inet::ospfv2::Ospfv2RoutingTableEntry::getArea () const inline
 { return area; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), and inet::ospfv2::Router::selectLeastCostRoutingEntry().
getCost()
Metric inet::ospfv2::Ospfv2RoutingTableEntry::getCost () const inline
 { return cost; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), and inet::ospfv2::Router::selectLeastCostRoutingEntry().
getDestinationType()
RoutingDestinationType inet::ospfv2::Ospfv2RoutingTableEntry::getDestinationType () const inline
 { return destinationType; }
Referenced by inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
getDestinationTypeString()
const char * inet::ospfv2::Ospfv2RoutingTableEntry::getDestinationTypeString (RoutingDestinationType destType) static
 {
     switch (destType) {
         case Ospfv2RoutingTableEntry::NETWORK_DESTINATION:
             return "Network";
         case Ospfv2RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION:
             return "AreaBorderRouter";
         case Ospfv2RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION:
             return "ASBoundaryRouter";
         case Ospfv2RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION | Ospfv2RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION:
             return "AreaBorderRouter+ASBoundaryRouter";
         default:
             return "Unknown";
     }
 }
Referenced by inet::ospfv2::operator<<(), and str().
getLinkStateOrigin()
const Ospfv2Lsa* inet::ospfv2::Ospfv2RoutingTableEntry::getLinkStateOrigin () const inline
 { return linkStateOrigin; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::operator<<(), and inet::ospfv2::Ospfv2Area::originateSummaryLSA().
getNextHop()
NextHop inet::ospfv2::Ospfv2RoutingTableEntry::getNextHop (unsigned int index) const inline
 { return nextHops[index]; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
getNextHopCount()
unsigned int inet::ospfv2::Ospfv2RoutingTableEntry::getNextHopCount () const inline
 { return nextHops.size(); }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
getOptionalCapabilities()
Ospfv2Options inet::ospfv2::Ospfv2RoutingTableEntry::getOptionalCapabilities () const inline
 { return optionalCapabilities; }
getPathType()
RoutingPathType inet::ospfv2::Ospfv2RoutingTableEntry::getPathType () const inline
 { return pathType; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Router::getPreferredEntry(), inet::ospfv2::operator<<(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
getPathTypeString()
const char * inet::ospfv2::Ospfv2RoutingTableEntry::getPathTypeString (RoutingPathType pathType) static
 {
     switch (pathType) {
         case Ospfv2RoutingTableEntry::INTRAAREA:
             return "IntraArea";
         case Ospfv2RoutingTableEntry::INTERAREA:
             return "InterArea";
         case Ospfv2RoutingTableEntry::TYPE1_EXTERNAL:
             return "Type1External";
         case Ospfv2RoutingTableEntry::TYPE2_EXTERNAL:
             return "Type2External";
         default:
             return "Unknown";
     }
 }
Referenced by inet::ospfv2::operator<<(), and str().
getType2Cost()
Metric inet::ospfv2::Ospfv2RoutingTableEntry::getType2Cost () const inline
 { return type2Cost; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), and inet::ospfv2::operator<<().
operator!=()
bool inet::ospfv2::Ospfv2RoutingTableEntry::operator!= (const Ospfv2RoutingTableEntry & entry) const inline
 { return !((*this) == entry); }
operator==()
bool inet::ospfv2::Ospfv2RoutingTableEntry::operator== (const Ospfv2RoutingTableEntry & entry) const
 {
     unsigned int hopCount = nextHops.size();
     unsigned int i = 0;
     if (hopCount != entry.nextHops.size()) {
         return false;
     }
     for (i = 0; i < hopCount; i++) {
         if ((nextHops[i] != entry.nextHops[i])) {
             return false;
         }
     }
     return (destinationType == entry.destinationType) &&
            (getDestination() == entry.getDestination()) &&
            (getNetmask() == entry.getNetmask()) &&
            (optionalCapabilities == entry.optionalCapabilities) &&
            (area == entry.area) &&
            (pathType == entry.pathType) &&
            (cost == entry.cost) &&
            (type2Cost == entry.type2Cost) &&
            (linkStateOrigin == entry.linkStateOrigin);
 }
setArea()
void inet::ospfv2::Ospfv2RoutingTableEntry::setArea (AreaId source) inline
 { area = source; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), and inet::ospfv2::Router::lookup().
setCost()
void inet::ospfv2::Ospfv2RoutingTableEntry::setCost (Metric cost) inline
 { this->cost = cost; setMetric(cost); }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), and inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA().
setDestinationType()
void inet::ospfv2::Ospfv2RoutingTableEntry::setDestinationType (RoutingDestinationType type) inline
 { destinationType = type; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), and inet::ospfv2::Router::lookup().
setLinkStateOrigin()
void inet::ospfv2::Ospfv2RoutingTableEntry::setLinkStateOrigin (const Ospfv2Lsa * lsa) inline
 { linkStateOrigin = lsa; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), and inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA().
setOptionalCapabilities()
void inet::ospfv2::Ospfv2RoutingTableEntry::setOptionalCapabilities (Ospfv2Options options) inline
 { optionalCapabilities = options; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), and inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA().
setPathType()
void inet::ospfv2::Ospfv2RoutingTableEntry::setPathType (RoutingPathType type) inline
 { pathType = type; }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), and inet::ospfv2::Router::lookup().
setType2Cost()
void inet::ospfv2::Ospfv2RoutingTableEntry::setType2Cost (Metric type2Cost) inline
 { this->type2Cost = type2Cost; setMetric(type2Cost); }
Referenced by inet::ospfv2::Router::calculateASExternalRoutes().
str()
std::string inet::ospfv2::Ospfv2RoutingTableEntry::str () const virtual
Reimplemented from inet::Ipv4Route.
 {
     std::ostringstream out;
     out << getSourceTypeAbbreviation();
     out << " ";
     if (getDestination().isUnspecified())
         out << "0.0.0.0";
     else
         out << getDestination();
     out << "/";
     if (getNetmask().isUnspecified())
         out << "0";
     else
         out << getNetmask().getNetmaskLength();
     out << " gw:";
     if (getGateway().isUnspecified())
         out << "*  ";
     else
         out << getGateway() << "  ";
     if (getRoutingTable() && getRoutingTable()->isAdminDistEnabled())
         out << "AD:" << getAdminDist() << "  ";
     out << "metric:" << getMetric() << "  ";
     out << "if:";
     if (!getInterface())
         out << "*";
     else
         out << getInterfaceName();
     out << " destType:" << Ospfv2RoutingTableEntry::getDestinationTypeString(destinationType)
         << " pathType:" << Ospfv2RoutingTableEntry::getPathTypeString(pathType)
         << " area:" << area.str(false);
     return out.str();
 }
Member Data Documentation
area
AreaId inet::ospfv2::Ospfv2RoutingTableEntry::area private
Referenced by operator==(), and str().
AREA_BORDER_ROUTER_DESTINATION
const unsigned char inet::ospfv2::Ospfv2RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION = 1 static
Referenced by inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), getDestinationTypeString(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
AS_BOUNDARY_ROUTER_DESTINATION
const unsigned char inet::ospfv2::Ospfv2RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION = 2 static
Referenced by inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), getDestinationTypeString(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
cost
Metric inet::ospfv2::Ospfv2RoutingTableEntry::cost = 0 private
Referenced by operator==().
destinationType
RoutingDestinationType inet::ospfv2::Ospfv2RoutingTableEntry::destinationType = 0 private
Referenced by operator==(), and str().
ift
IInterfaceTable* inet::ospfv2::Ospfv2RoutingTableEntry::ift = nullptr private
Referenced by addNextHop().
linkStateOrigin
const Ospfv2Lsa* inet::ospfv2::Ospfv2RoutingTableEntry::linkStateOrigin = nullptr private
Referenced by operator==().
NETWORK_DESTINATION
const unsigned char inet::ospfv2::Ospfv2RoutingTableEntry::NETWORK_DESTINATION = 0 static
Referenced by inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateInterAreaRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Area::createRoutingTableEntryFromSummaryLSA(), inet::ospfv2::Ospfv2Area::findSameOrWorseCostRoute(), getDestinationTypeString(), inet::ospfv2::Router::lookup(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Router::rebuildRoutingTable(), and inet::ospfv2::Ospfv2Area::recheckSummaryLSAs().
nextHops
std::vector<NextHop> inet::ospfv2::Ospfv2RoutingTableEntry::nextHops private
Referenced by addNextHop(), and operator==().
optionalCapabilities
Ospfv2Options inet::ospfv2::Ospfv2RoutingTableEntry::optionalCapabilities private
Referenced by operator==().
pathType
RoutingPathType inet::ospfv2::Ospfv2RoutingTableEntry::pathType = static_cast<RoutingPathType>(-1) private
Referenced by getPathTypeString(), operator==(), and str().
type2Cost
Metric inet::ospfv2::Ospfv2RoutingTableEntry::type2Cost = 0 private
Referenced by operator==().
The documentation for this class was generated from the following files:
Ospfv2RoutingTableEntry.h
Ospfv2RoutingTableEntry.cc