INET Framework for OMNeT++/OMNEST: inet::GpsrOption Class Reference
inet::GpsrOption Class Reference
Class generated from inet/routing/gpsr/Gpsr.msg:46 by opp_msgtool.
#include <Gpsr_m.h>
Public Member Functions
GpsrOption ()
GpsrOption (const GpsrOption &other)
virtual ~GpsrOption ()
GpsrOption & operator= (const GpsrOption &other)
virtual GpsrOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual GpsrForwardingMode getRoutingMode () const
virtual void setRoutingMode (GpsrForwardingMode routingMode)
virtual const Coord & getDestinationPosition () const
virtual Coord & getDestinationPositionForUpdate ()
virtual void setDestinationPosition (const Coord &destinationPosition)
virtual const Coord & getPerimeterRoutingStartPosition () const
virtual Coord & getPerimeterRoutingStartPositionForUpdate ()
virtual void setPerimeterRoutingStartPosition (const Coord &perimeterRoutingStartPosition)
virtual const Coord & getPerimeterRoutingForwardPosition () const
virtual Coord & getPerimeterRoutingForwardPositionForUpdate ()
virtual void setPerimeterRoutingForwardPosition (const Coord &perimeterRoutingForwardPosition)
virtual const L3Address & getCurrentFaceFirstSenderAddress () const
virtual L3Address & getCurrentFaceFirstSenderAddressForUpdate ()
virtual void setCurrentFaceFirstSenderAddress (const L3Address &currentFaceFirstSenderAddress)
virtual const L3Address & getCurrentFaceFirstReceiverAddress () const
virtual L3Address & getCurrentFaceFirstReceiverAddressForUpdate ()
virtual void setCurrentFaceFirstReceiverAddress (const L3Address &currentFaceFirstReceiverAddress)
virtual const L3Address & getSenderAddress () const
virtual L3Address & getSenderAddressForUpdate ()
virtual void setSenderAddress (const L3Address &senderAddress)
Public Member Functions inherited from inet::TlvOptionBase
TlvOptionBase ()
TlvOptionBase (const TlvOptionBase &other)
virtual ~TlvOptionBase ()
TlvOptionBase & operator= (const TlvOptionBase &other)
virtual short getType () const
virtual void setType (short type)
virtual short getLength () const
virtual void setLength (short length)
Protected Member Functions
bool operator== (const GpsrOption &)=delete
Protected Member Functions inherited from inet::TlvOptionBase
bool operator== (const TlvOptionBase &)=delete
Protected Attributes
GpsrForwardingMode routingMode = static_cast<inet::GpsrForwardingMode>(-1)
Coord destinationPosition
Coord perimeterRoutingStartPosition
Coord perimeterRoutingForwardPosition
L3Address currentFaceFirstSenderAddress
L3Address currentFaceFirstReceiverAddress
L3Address senderAddress
Protected Attributes inherited from inet::TlvOptionBase
short type = -1
short length = 0
Private Member Functions
void copy (const GpsrOption &other)
Detailed Description
Class generated from inet/routing/gpsr/Gpsr.msg:46 by opp_msgtool.
//
// The GPSROption is used to add extra routing information for network datagrams.
//
// For more information, see the GPSR paper
// http://www.eecs.harvard.edu/~htk/publication/2000-mobi-karp-kung.pdf
//
class GpsrOption extends TlvOptionBase
{
    GpsrForwardingMode routingMode;
    Coord destinationPosition;               // D
    Coord perimeterRoutingStartPosition;     // Lp
    Coord perimeterRoutingForwardPosition;   // Lf
    L3Address currentFaceFirstSenderAddress;   // e0
    L3Address currentFaceFirstReceiverAddress; // e0
    L3Address senderAddress; // TODO this field is not strictly needed by GPSR (should be eliminated)
}
Constructor & Destructor Documentation
GpsrOption() [1/2]
inet::GpsrOption::GpsrOption ()
GpsrOption() [2/2]
inet::GpsrOption::GpsrOption (const GpsrOption & other)
~GpsrOption()
virtual inet::GpsrOption::~GpsrOption () virtual
Member Function Documentation
copy()
void inet::GpsrOption::copy (const GpsrOption & other) private
dup()
virtual GpsrOption* inet::GpsrOption::dup () const inline override virtual
Reimplemented from inet::TlvOptionBase.
 {return new GpsrOption(*this);}
getCurrentFaceFirstReceiverAddress()
virtual const L3Address& inet::GpsrOption::getCurrentFaceFirstReceiverAddress () const virtual
Referenced by inet::Gpsr::findPerimeterRoutingNextHop().
getCurrentFaceFirstReceiverAddressForUpdate()
virtual L3Address& inet::GpsrOption::getCurrentFaceFirstReceiverAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<GpsrOption*>(this)->getCurrentFaceFirstReceiverAddress());}
getCurrentFaceFirstSenderAddress()
virtual const L3Address& inet::GpsrOption::getCurrentFaceFirstSenderAddress () const virtual
Referenced by inet::Gpsr::findPerimeterRoutingNextHop().
getCurrentFaceFirstSenderAddressForUpdate()
virtual L3Address& inet::GpsrOption::getCurrentFaceFirstSenderAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<GpsrOption*>(this)->getCurrentFaceFirstSenderAddress());}
getDestinationPosition()
virtual const Coord& inet::GpsrOption::getDestinationPosition () const virtual
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::findPerimeterRoutingNextHop().
getDestinationPositionForUpdate()
virtual Coord& inet::GpsrOption::getDestinationPositionForUpdate () inline virtual
 { return const_cast<Coord&>(const_cast<GpsrOption*>(this)->getDestinationPosition());}
getPerimeterRoutingForwardPosition()
virtual const Coord& inet::GpsrOption::getPerimeterRoutingForwardPosition () const virtual
getPerimeterRoutingForwardPositionForUpdate()
virtual Coord& inet::GpsrOption::getPerimeterRoutingForwardPositionForUpdate () inline virtual
 { return const_cast<Coord&>(const_cast<GpsrOption*>(this)->getPerimeterRoutingForwardPosition());}
getPerimeterRoutingStartPosition()
virtual const Coord& inet::GpsrOption::getPerimeterRoutingStartPosition () const virtual
Referenced by inet::Gpsr::findPerimeterRoutingNextHop().
getPerimeterRoutingStartPositionForUpdate()
virtual Coord& inet::GpsrOption::getPerimeterRoutingStartPositionForUpdate () inline virtual
 { return const_cast<Coord&>(const_cast<GpsrOption*>(this)->getPerimeterRoutingStartPosition());}
getRoutingMode()
virtual GpsrForwardingMode inet::GpsrOption::getRoutingMode () const virtual
Referenced by inet::Gpsr::findNextHop().
getSenderAddress()
virtual const L3Address& inet::GpsrOption::getSenderAddress () const virtual
Referenced by inet::Gpsr::findPerimeterRoutingNextHop(), and inet::Gpsr::getSenderNeighborAddress().
getSenderAddressForUpdate()
virtual L3Address& inet::GpsrOption::getSenderAddressForUpdate () inline virtual
 { return const_cast<L3Address&>(const_cast<GpsrOption*>(this)->getSenderAddress());}
operator=()
GpsrOption& inet::GpsrOption::operator= (const GpsrOption & other)
operator==()
bool inet::GpsrOption::operator== (const GpsrOption &) protected delete
parsimPack()
virtual void inet::GpsrOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::TlvOptionBase.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::GpsrOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::TlvOptionBase.
Referenced by inet::doParsimUnpacking().
setCurrentFaceFirstReceiverAddress()
virtual void inet::GpsrOption::setCurrentFaceFirstReceiverAddress (const L3Address & currentFaceFirstReceiverAddress) virtual
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::findPerimeterRoutingNextHop().
setCurrentFaceFirstSenderAddress()
virtual void inet::GpsrOption::setCurrentFaceFirstSenderAddress (const L3Address & currentFaceFirstSenderAddress) virtual
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::findPerimeterRoutingNextHop().
setDestinationPosition()
virtual void inet::GpsrOption::setDestinationPosition (const Coord & destinationPosition) virtual
Referenced by inet::Gpsr::createGpsrOption().
setPerimeterRoutingForwardPosition()
virtual void inet::GpsrOption::setPerimeterRoutingForwardPosition (const Coord & perimeterRoutingForwardPosition) virtual
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::findPerimeterRoutingNextHop().
setPerimeterRoutingStartPosition()
virtual void inet::GpsrOption::setPerimeterRoutingStartPosition (const Coord & perimeterRoutingStartPosition) virtual
Referenced by inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::findPerimeterRoutingNextHop().
setRoutingMode()
virtual void inet::GpsrOption::setRoutingMode (GpsrForwardingMode routingMode) virtual
Referenced by inet::Gpsr::createGpsrOption(), inet::Gpsr::findGreedyRoutingNextHop(), and inet::Gpsr::findPerimeterRoutingNextHop().
setSenderAddress()
virtual void inet::GpsrOption::setSenderAddress (const L3Address & senderAddress) virtual
Referenced by inet::Gpsr::routeDatagram().
Member Data Documentation
currentFaceFirstReceiverAddress
L3Address inet::GpsrOption::currentFaceFirstReceiverAddress protected
currentFaceFirstSenderAddress
L3Address inet::GpsrOption::currentFaceFirstSenderAddress protected
destinationPosition
Coord inet::GpsrOption::destinationPosition protected
perimeterRoutingForwardPosition
Coord inet::GpsrOption::perimeterRoutingForwardPosition protected
perimeterRoutingStartPosition
Coord inet::GpsrOption::perimeterRoutingStartPosition protected
routingMode
GpsrForwardingMode inet::GpsrOption::routingMode = static_cast<inet::GpsrForwardingMode>(-1) protected
senderAddress
L3Address inet::GpsrOption::senderAddress protected
The documentation for this class was generated from the following file:
Gpsr_m.h