INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3RouterLsa Class Reference
inet::ospfv3::Ospfv3RouterLsa Class Reference
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:207 by opp_msgtool.
#include <Ospfv3Packet_m.h>
Public Member Functions
Ospfv3RouterLsa ()
Ospfv3RouterLsa (const Ospfv3RouterLsa &other)
virtual ~Ospfv3RouterLsa ()
Ospfv3RouterLsa & operator= (const Ospfv3RouterLsa &other)
virtual Ospfv3RouterLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getNtBit () const
virtual void setNtBit (bool ntBit)
virtual bool getXBit () const
virtual void setXBit (bool xBit)
virtual bool getVBit () const
virtual void setVBit (bool vBit)
virtual bool getEBit () const
virtual void setEBit (bool eBit)
virtual bool getBBit () const
virtual void setBBit (bool bBit)
virtual const Ospfv3Options & getOspfOptions () const
virtual Ospfv3Options & getOspfOptionsForUpdate ()
virtual void setOspfOptions (const Ospfv3Options &ospfOptions)
virtual void setRoutersArraySize (size_t size)
virtual size_t getRoutersArraySize () const
virtual const Ospfv3RouterLsaBody & getRouters (size_t k) const
virtual Ospfv3RouterLsaBody & getRoutersForUpdate (size_t k)
virtual void setRouters (size_t k, const Ospfv3RouterLsaBody &routers)
virtual void insertRouters (size_t k, const Ospfv3RouterLsaBody &routers)
void insertRouters (const Ospfv3RouterLsaBody &routers)
virtual void appendRouters (const Ospfv3RouterLsaBody &routers)
virtual void eraseRouters (size_t k)
Public Member Functions inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3Lsa ()
Ospfv3Lsa (const Ospfv3Lsa &other)
virtual ~Ospfv3Lsa ()
Ospfv3Lsa & operator= (const Ospfv3Lsa &other)
virtual const Ospfv3LsaHeader & getHeader () const
virtual Ospfv3LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv3LsaHeader &header)
Protected Member Functions
bool operator== (const Ospfv3RouterLsa &)=delete
Protected Member Functions inherited from inet::ospfv3::Ospfv3Lsa
bool operator== (const Ospfv3Lsa &)=delete
Protected Attributes
bool ntBit = false
bool xBit = false
bool vBit = false
bool eBit = false
bool bBit = false
Ospfv3Options ospfOptions
Ospfv3RouterLsaBody * routers = nullptr
size_t routers_arraysize = 0
Protected Attributes inherited from inet::ospfv3::Ospfv3Lsa
Ospfv3LsaHeader header
Private Member Functions
void copy (const Ospfv3RouterLsa &other)
Detailed Description
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:207 by opp_msgtool.
class Ospfv3RouterLsa extends Ospfv3Lsa
{
    bool ntBit;
    bool xBit;
    bool vBit;
    bool eBit;
    bool bBit;
    Ospfv3Options ospfOptions;
    Ospfv3RouterLsaBody routers[];
}
Constructor & Destructor Documentation
Ospfv3RouterLsa() [1/2]
inet::ospfv3::Ospfv3RouterLsa::Ospfv3RouterLsa ()
Ospfv3RouterLsa() [2/2]
inet::ospfv3::Ospfv3RouterLsa::Ospfv3RouterLsa (const Ospfv3RouterLsa & other)
~Ospfv3RouterLsa()
virtual inet::ospfv3::Ospfv3RouterLsa::~Ospfv3RouterLsa () virtual
Member Function Documentation
appendRouters()
virtual void inet::ospfv3::Ospfv3RouterLsa::appendRouters (const Ospfv3RouterLsaBody & routers) virtual
copy()
void inet::ospfv3::Ospfv3RouterLsa::copy (const Ospfv3RouterLsa & other) private
dup()
virtual Ospfv3RouterLsa* inet::ospfv3::Ospfv3RouterLsa::dup () const inline override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
 {return new Ospfv3RouterLsa(*this);}
eraseRouters()
virtual void inet::ospfv3::Ospfv3RouterLsa::eraseRouters (size_t k) virtual
getBBit()
virtual bool inet::ospfv3::Ospfv3RouterLsa::getBBit () const virtual
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getEBit()
virtual bool inet::ospfv3::Ospfv3RouterLsa::getEBit () const virtual
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getNtBit()
virtual bool inet::ospfv3::Ospfv3RouterLsa::getNtBit () const virtual
Referenced by inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getOspfOptions()
virtual const Ospfv3Options& inet::ospfv3::Ospfv3RouterLsa::getOspfOptions () const virtual
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry().
getOspfOptionsForUpdate()
virtual Ospfv3Options& inet::ospfv3::Ospfv3RouterLsa::getOspfOptionsForUpdate () inline virtual
 { return const_cast<Ospfv3Options&>(const_cast<Ospfv3RouterLsa*>(this)->getOspfOptions());}
getRouters()
virtual const Ospfv3RouterLsaBody& inet::ospfv3::Ospfv3RouterLsa::getRouters (size_t k) const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::ospfv3::Ospfv3Area::routerLSAAlreadyExists(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getRoutersArraySize()
virtual size_t inet::ospfv3::Ospfv3RouterLsa::getRoutersArraySize () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::calculateLSASize(), inet::ospfv3::Ospfv3Area::calculateNextHops(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::hasLink(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::ospfv3::Ospfv3Area::routerLSAAlreadyExists(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getRoutersForUpdate()
virtual Ospfv3RouterLsaBody& inet::ospfv3::Ospfv3RouterLsa::getRoutersForUpdate (size_t k) inline virtual
 { return const_cast<Ospfv3RouterLsaBody&>(const_cast<Ospfv3RouterLsa*>(this)->getRouters(k));}
Referenced by inet::ospfv3::Ospfv3Area::calculateNextHops(), and inet::ospfv3::Ospfv3Area::hasLink().
getVBit()
virtual bool inet::ospfv3::Ospfv3RouterLsa::getVBit () const virtual
Referenced by inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
getXBit()
virtual bool inet::ospfv3::Ospfv3RouterLsa::getXBit () const virtual
Referenced by inet::ospfv3::Ospfv3Area::routerLSADiffersFrom().
insertRouters() [1/2]
void inet::ospfv3::Ospfv3RouterLsa::insertRouters (const Ospfv3RouterLsaBody & routers) inline
 {appendRouters(routers);}
insertRouters() [2/2]
virtual void inet::ospfv3::Ospfv3RouterLsa::insertRouters (size_t k, const Ospfv3RouterLsaBody & routers) virtual
operator=()
Ospfv3RouterLsa& inet::ospfv3::Ospfv3RouterLsa::operator= (const Ospfv3RouterLsa & other)
operator==()
bool inet::ospfv3::Ospfv3RouterLsa::operator== (const Ospfv3RouterLsa &) protected delete
parsimPack()
virtual void inet::ospfv3::Ospfv3RouterLsa::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimPacking().
parsimUnpack()
virtual void inet::ospfv3::Ospfv3RouterLsa::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::ospfv3::Ospfv3Lsa.
Referenced by inet::ospfv3::doParsimUnpacking().
setBBit()
virtual void inet::ospfv3::Ospfv3RouterLsa::setBBit (bool bBit) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateRouterLSA().
setEBit()
virtual void inet::ospfv3::Ospfv3RouterLsa::setEBit (bool eBit) virtual
setNtBit()
virtual void inet::ospfv3::Ospfv3RouterLsa::setNtBit (bool ntBit) virtual
setOspfOptions()
virtual void inet::ospfv3::Ospfv3RouterLsa::setOspfOptions (const Ospfv3Options & ospfOptions) virtual
setRouters()
virtual void inet::ospfv3::Ospfv3RouterLsa::setRouters (size_t k, const Ospfv3RouterLsaBody & routers) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateRouterLSA().
setRoutersArraySize()
virtual void inet::ospfv3::Ospfv3RouterLsa::setRoutersArraySize (size_t size) virtual
Referenced by inet::ospfv3::Ospfv3Area::originateRouterLSA().
setVBit()
virtual void inet::ospfv3::Ospfv3RouterLsa::setVBit (bool vBit) virtual
setXBit()
virtual void inet::ospfv3::Ospfv3RouterLsa::setXBit (bool xBit) virtual
Member Data Documentation
bBit
bool inet::ospfv3::Ospfv3RouterLsa::bBit = false protected
eBit
bool inet::ospfv3::Ospfv3RouterLsa::eBit = false protected
ntBit
bool inet::ospfv3::Ospfv3RouterLsa::ntBit = false protected
ospfOptions
Ospfv3Options inet::ospfv3::Ospfv3RouterLsa::ospfOptions protected
routers
Ospfv3RouterLsaBody* inet::ospfv3::Ospfv3RouterLsa::routers = nullptr protected
routers_arraysize
size_t inet::ospfv3::Ospfv3RouterLsa::routers_arraysize = 0 protected
vBit
bool inet::ospfv3::Ospfv3RouterLsa::vBit = false protected
xBit
bool inet::ospfv3::Ospfv3RouterLsa::xBit = false protected
The documentation for this class was generated from the following file:
Ospfv3Packet_m.h