INET Framework for OMNeT++/OMNEST: inet::BoxedLabelFigure Class Reference
inet::BoxedLabelFigure Class Reference
#include <BoxedLabelFigure.h>
Public Member Functions
BoxedLabelFigure (const char *name=nullptr)
cLabelFigure * getLabelFigure () const
cRectangleFigure * getRectangleFigure () const
double getInset () const
void setInset (double inset)
void setTags (const char *tags)
void setTooltip (const char *tooltip)
void setAssociatedObject (cObject *object)
const cFigure::Rectangle & getBounds () const
const cFigure::Font & getFont () const
void setFont (cFigure::Font font)
const cFigure::Color & getLabelColor () const
void setLabelColor (cFigure::Color color)
const cFigure::Color & getBackgroundColor () const
void setBackgroundColor (cFigure::Color color)
const char * getText () const
void setText (const char *text)
double getOpacity () const
void setOpacity (double opacity)
Protected Attributes
double inset = 3
cLabelFigure * labelFigure
cRectangleFigure * rectangleFigure
Constructor & Destructor Documentation
BoxedLabelFigure()
inet::BoxedLabelFigure::BoxedLabelFigure (const char * name = nullptr)
                                                    :
     cGroupFigure(name)
 {
     labelFigure = new cLabelFigure("label");
     rectangleFigure = new cRectangleFigure("box");
     rectangleFigure->setFilled(true);
     rectangleFigure->setLineColor(cFigure::BLACK);
     addFigure(rectangleFigure);
     addFigure(labelFigure);
     setInset(inset);
     setText(" "); // TODO empty string causes negative width/height in Tkenv
 }
Member Function Documentation
getBackgroundColor()
const cFigure::Color & inet::BoxedLabelFigure::getBackgroundColor () const
 {
     return rectangleFigure->getFillColor();
 }
getBounds()
const cFigure::Rectangle & inet::BoxedLabelFigure::getBounds () const
 {
     return rectangleFigure->getBounds();
 }
getFont()
const cFigure::Font & inet::BoxedLabelFigure::getFont () const
 {
     return labelFigure->getFont();
 }
getInset()
double inet::BoxedLabelFigure::getInset () const inline
 { return inset; }
getLabelColor()
const cFigure::Color & inet::BoxedLabelFigure::getLabelColor () const
 {
     return labelFigure->getColor();
 }
getLabelFigure()
cLabelFigure* inet::BoxedLabelFigure::getLabelFigure () const inline
 { return labelFigure; }
getOpacity()
double inet::BoxedLabelFigure::getOpacity () const
 {
     return rectangleFigure->getFillOpacity();
 }
getRectangleFigure()
cRectangleFigure* inet::BoxedLabelFigure::getRectangleFigure () const inline
 { return rectangleFigure; }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
getText()
const char * inet::BoxedLabelFigure::getText () const
 {
     return labelFigure->getText();
 }
setAssociatedObject()
void inet::BoxedLabelFigure::setAssociatedObject (cObject * object)
 {
     labelFigure->setAssociatedObject(object);
     rectangleFigure->setAssociatedObject(object);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setBackgroundColor()
void inet::BoxedLabelFigure::setBackgroundColor (cFigure::Color color)
 {
     rectangleFigure->setFillColor(color);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setFont()
void inet::BoxedLabelFigure::setFont (cFigure::Font font)
 {
     labelFigure->setFont(font);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setInset()
void inet::BoxedLabelFigure::setInset (double inset)
 {
     this->inset = inset;
     labelFigure->setPosition(cFigure::Point(inset, inset));
     rectangleFigure->setCornerRx(inset);
     rectangleFigure->setCornerRy(inset);
 }
Referenced by BoxedLabelFigure(), and inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setLabelColor()
void inet::BoxedLabelFigure::setLabelColor (cFigure::Color color)
 {
     labelFigure->setColor(color);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setOpacity()
void inet::BoxedLabelFigure::setOpacity (double opacity)
 {
     rectangleFigure->setFillOpacity(opacity);
     rectangleFigure->setLineOpacity(opacity);
     labelFigure->setOpacity(opacity);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setTags()
void inet::BoxedLabelFigure::setTags (const char * tags)
 {
     labelFigure->setTags(tags);
     rectangleFigure->setTags(tags);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
setText()
void inet::BoxedLabelFigure::setText (const char * text)
 {
     double width, height, ascent;
     getSimulation()->getEnvir()->getTextExtent(labelFigure->getFont(), text, width, height, ascent);
     rectangleFigure->setBounds(cFigure::Rectangle(0, 0, width + inset * 2, height + inset * 2));
     labelFigure->setText(text);
 }
Referenced by BoxedLabelFigure(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), and inet::visualizer::InfoCanvasVisualizer::refreshInfoVisualization().
setTooltip()
void inet::BoxedLabelFigure::setTooltip (const char * tooltip)
 {
     labelFigure->setTooltip(tooltip);
     rectangleFigure->setTooltip(tooltip);
 }
Referenced by inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization().
Member Data Documentation
inset
double inet::BoxedLabelFigure::inset = 3 protected
Referenced by BoxedLabelFigure(), setInset(), and setText().
labelFigure
cLabelFigure* inet::BoxedLabelFigure::labelFigure protected
Referenced by BoxedLabelFigure(), getFont(), getLabelColor(), getText(), setAssociatedObject(), setFont(), setInset(), setLabelColor(), setOpacity(), setTags(), setText(), and setTooltip().
rectangleFigure
cRectangleFigure* inet::BoxedLabelFigure::rectangleFigure protected
Referenced by BoxedLabelFigure(), getBackgroundColor(), getBounds(), getOpacity(), setAssociatedObject(), setBackgroundColor(), setInset(), setOpacity(), setTags(), setText(), and setTooltip().
The documentation for this class was generated from the following files:
BoxedLabelFigure.h
BoxedLabelFigure.cc