INET Framework for OMNeT++/OMNEST: inet::StringFormat Class Reference
inet::StringFormat Class Reference
#include <StringFormat.h>
Classes
class IDirectiveResolver
Public Member Functions
void parseFormat (const char *format)
const char * formatString (IDirectiveResolver *resolver) const
const char * formatString (std::function< const char *(char)> &resolver) const
Static Public Member Functions
static const char * formatString (const char *format, const IDirectiveResolver *resolver)
static const char * formatString (const char *format, const std::function< const char *(char)> resolver)
Protected Attributes
std::string format
Member Function Documentation
formatString() [1/4]
const char * inet::StringFormat::formatString (const char * format, const IDirectiveResolver * resolver) static
 {
     return formatString(format, [&] (char directive) { return resolver->resolveDirective(directive); });
 }
formatString() [2/4]
const char * inet::StringFormat::formatString (const char * format, const std::function< const char *(char)> resolver) static
 {
     static std::string result;
     result.clear();
     int current = 0;
     int previous = current;
     while (true) {
         char ch = format[current];
         if (ch == '\0') {
             if (previous != current)
                 result.append(format + previous, current - previous);
             break;
         }
         else if (ch == '%') {
             if (previous != current)
                 result.append(format + previous, current - previous);
             previous = current;
             current++;
             ch = format[current];
             if (ch == '%')
                 result.append(format + previous, current - previous);
             else
                 result.append(resolver(ch));
             previous = current + 1;
         }
         current++;
     }
     return result.c_str();
 }
formatString() [3/4]
const char * inet::StringFormat::formatString (IDirectiveResolver * resolver) const
 {
     return formatString(format.c_str(), resolver);
 }
Referenced by inet::queueing::PacketSourceBase::createPacketName(), formatString(), inet::visualizer::GateScheduleVisualizerBase::getGateScheduleVisualizationText(), inet::visualizer::InfoVisualizerBase::getInfoVisualizationText(), inet::visualizer::LinkVisualizerBase::getLinkVisualizationText(), inet::visualizer::PacketDropVisualizerBase::getPacketDropVisualizationText(), inet::visualizer::PathVisualizerBase::getPathVisualizationText(), inet::visualizer::RoutingTableVisualizerBase::getRouteVisualizationText(), inet::visualizer::StatisticVisualizerBase::getText(), inet::visualizer::InterfaceTableVisualizerBase::getVisualizationText(), inet::PacketPrinter::printPacket(), inet::StationaryMobility::refreshDisplay(), inet::Ppp::refreshDisplay(), inet::MobilityBase::refreshDisplay(), inet::EthernetMacBase::refreshDisplay(), inet::Ipv4NetworkLayer::updateDisplayString(), inet::OscillatorBase::updateDisplayString(), inet::ClockBase::updateDisplayString(), inet::MacRelayUnitBase::updateDisplayString(), inet::power::SimpleCcBattery::updateDisplayString(), inet::PcapRecorder::updateDisplayString(), inet::MacForwardingTable::updateDisplayString(), inet::queueing::PacketProcessorBase::updateDisplayString(), inet::power::SimpleEpEnergyStorage::updateDisplayString(), and inet::NetworkInterface::updateDisplayString().
formatString() [4/4]
const char * inet::StringFormat::formatString (std::function< const char *(char)> & resolver) const
 {
     return formatString(format.c_str(), resolver);
 }
parseFormat()
void inet::StringFormat::parseFormat (const char * format)
 {
     this->format = format;
 }
Referenced by inet::FacingMobility::handleParameterChange(), inet::visualizer::InfoVisualizerBase::handleParameterChange(), inet::visualizer::InterfaceTableVisualizerBase::handleParameterChange(), inet::visualizer::RoutingTableVisualizerBase::handleParameterChange(), inet::visualizer::StatisticVisualizerBase::handleParameterChange(), inet::visualizer::PacketDropVisualizerBase::handleParameterChange(), inet::MobilityBase::handleParameterChange(), inet::FacingMobility::initialize(), inet::visualizer::GateScheduleCanvasVisualizer::initialize(), inet::visualizer::InfoVisualizerBase::initialize(), inet::visualizer::InterfaceTableVisualizerBase::initialize(), inet::visualizer::RoutingTableVisualizerBase::initialize(), inet::visualizer::StatisticVisualizerBase::initialize(), inet::visualizer::LinkVisualizerBase::initialize(), inet::MobilityBase::initialize(), inet::visualizer::PathVisualizerBase::initialize(), inet::visualizer::PacketDropVisualizerBase::initialize(), and inet::PacketPrinter::printPacket().
Member Data Documentation
format
std::string inet::StringFormat::format protected
Referenced by formatString(), and parseFormat().
The documentation for this class was generated from the following files:
StringFormat.h
StringFormat.cc