INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee802154UwbIrTransmitter Class Reference
inet::physicallayer::Ieee802154UwbIrTransmitter Class Reference
This generates pulse-level representation of an IEEE 802.15.4A UWB PHY frame using the mandatory mode (high PRF).
#include <Ieee802154UwbIrTransmitter.h>
Public Member Functions
Ieee802154UwbIrTransmitter ()
virtual const ITransmission * createTransmission (const IRadio *transmitter, const Packet *packet, const simtime_t startTime) const override
Returns a transmission which describes the radio signal corresponding to the provided packet.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
Public Member Functions inherited from inet::physicallayer::TransmitterBase
virtual W getMaxPower () const override
Returns the maximum transmission power above which no transmission is ever transmitted.
virtual m getMaxCommunicationRange () const override
Returns the maximum communication range.
virtual m getMaxInterferenceRange () const override
Returns the maximum interference range.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
simtime_t getFrameDuration (int psduLength) const
simtime_t getMaxFrameDuration () const
simtime_t getPhyMaxFrameDuration () const
simtime_t getThdr () const
virtual void generateSyncPreamble (std::map< simsec, WpHz > &data, simtime_t &time, const simtime_t startTime) const
virtual void generateSFD (std::map< simsec, WpHz > &data, simtime_t &time, const simtime_t startTime) const
virtual void generatePhyHeader (std::map< simsec, WpHz > &data, simtime_t &time, const simtime_t startTime) const
virtual void generateBurst (std::map< simsec, WpHz > &data, simtime_t &time, const simtime_t startTime, const simtime_t burstStart, short polarity) const
virtual void generatePulse (std::map< simsec, WpHz > &data, simtime_t &time, const simtime_t startTime, short polarity, double peak, const simtime_t chip) const
virtual Ptr< const IFunction< WpHz, Domain< simsec, Hz > > > generateIEEE802154AUWBSignal (const simtime_t startTime, std::vector< bool > *bits) const
Protected Member Functions inherited from inet::physicallayer::TransmitterBase
virtual int numInitStages () const override
Protected Attributes
Ieee802154UwbIrMode cfg
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This generates pulse-level representation of an IEEE 802.15.4A UWB PHY frame using the mandatory mode (high PRF).
Constructor & Destructor Documentation
Ieee802154UwbIrTransmitter()
inet::physicallayer::Ieee802154UwbIrTransmitter::Ieee802154UwbIrTransmitter ()
 {
 }
Member Function Documentation
createTransmission()
const ITransmission * inet::physicallayer::Ieee802154UwbIrTransmitter::createTransmission (const IRadio * transmitter, const Packet * packet, const simtime_t startTime) const override virtual
Returns a transmission which describes the radio signal corresponding to the provided packet.
This function never returns nullptr.
Implements inet::physicallayer::ITransmitter.
 {
     int bitLength = packet->getBitLength();
     // KLUDGE generate random bits until serializer is implemented
     std::vector<bool> *bits = new std::vector<bool>();
     for (int i = 0; i < bitLength; i++) {
         bool bitValue = intuniform(0, 1, 0);
         EV_INFO << "Transmitted bit at " << i << " is " << (int)bitValue << endl;
         bits->push_back(bitValue);
     }
     // KLUDGE add a fake CRC
     for (int i = 0; i < 8; i++) {
         bits->push_back(0);
         for (int j = 0; j + i < bitLength; j += 8)
             bits->at(bitLength + i) = bits->at(bitLength + i) ^ bits->at(j + i);
     }
     const simtime_t duration = getFrameDuration(bits->size() / 8);
     const simtime_t endTime = startTime + duration;
     IMobility *mobility = transmitter->getAntenna()->getMobility();
     const Coord& startPosition = mobility->getCurrentPosition();
     const Coord& endPosition = mobility->getCurrentPosition();
     const Quaternion& startOrientation = mobility->getCurrentAngularPosition();
     const Quaternion& endOrientation = mobility->getCurrentAngularPosition();
     const Ptr<const IFunction<WpHz, Domain<simsec, Hz>>>& powerFunction = generateIEEE802154AUWBSignal(startTime, bits);
     return new DimensionalTransmission(transmitter, packet, startTime, endTime, -1, -1, -1, startPosition, endPosition, startOrientation, endOrientation, nullptr, packet->getTotalLength(), b(-1), cfg.centerFrequency, cfg.bandwidth, cfg.bitrate, powerFunction);
 }
generateBurst()
void inet::physicallayer::Ieee802154UwbIrTransmitter::generateBurst (std::map< simsec, WpHz > & data, simtime_t & time, const simtime_t startTime, const simtime_t burstStart, short polarity) const protected virtual
 {
 //    ASSERT(burstStart < cfg.preambleLength + (psduLength * 8 + 48 + 2) * cfg.data_symbol_duration);
     // 1. Start point = zeros
     simtime_t offset = burstStart;
     for (int pulse = 0; pulse < cfg.nbPulsesPerBurst; pulse++) {
         time = offset;
         generatePulse(data, time, startTime, 1, Ieee802154UwbIrMode::maxPulse, cfg.pulse_duration);
         offset = offset + cfg.pulse_duration;
     }
 }
Referenced by generateIEEE802154AUWBSignal().
generateIEEE802154AUWBSignal()
Ptr< const IFunction< WpHz, Domain< simsec, Hz > > > inet::physicallayer::Ieee802154UwbIrTransmitter::generateIEEE802154AUWBSignal (const simtime_t startTime, std::vector< bool > * bits) const protected virtual
 {
     // 48 R-S parity bits, the 2 symbols phy header is not modeled as it includes its own parity bits
     // and is thus very robust
     unsigned int bitLength = bits->size() + 48;
     // data start time relative to signal->getReceptionStart();
     simtime_t dataStart = cfg.preambleLength; // = Tsync + Tsfd
     std::map<simsec, WpHz> data;
     data[getLowerBound<simsec>()] = WpHz(0);
     data[getUpperBound<simsec>()] = WpHz(0);
     simtime_t time = 0;
     generateSyncPreamble(data, time, startTime);
     generateSFD(data, time, startTime);
 //    generatePhyHeader(data, time, startTime);
     // generate bit values and modulates them according to
     // the IEEE 802.15.4A specification
     simtime_t symbolStart = dataStart;
     simtime_t burstPos;
     for (unsigned int burst = 0; burst < bitLength; burst++) {
         int bit = burst < bits->size() ? bits->at(burst) : intuniform(0, 1, 0);
         burstPos = symbolStart + bit * cfg.shift_duration + cfg.getHoppingPos(burst) * cfg.burst_duration;
         generateBurst(data, time, startTime, burstPos, +1);
         symbolStart = symbolStart + cfg.data_symbol_duration;
     }
     auto timeFunction = makeShared<Interpolated1DFunction<WpHz, simsec>>(data, &LinearInterpolator<simsec, WpHz>::singleton);
     auto frequencyFunction = makeShared<Boxcar1DFunction<double, Hz>>(GHz(3.1), GHz(10.6), 1);
     return makeShared<Combined2DFunction<WpHz, simsec, Hz>>(timeFunction, frequencyFunction);
 }
Referenced by createTransmission().
generatePhyHeader()
void inet::physicallayer::Ieee802154UwbIrTransmitter::generatePhyHeader (std::map< simsec, WpHz > & data, simtime_t & time, const simtime_t startTime) const protected virtual
 {
     // not implemented
 }
generatePulse()
void inet::physicallayer::Ieee802154UwbIrTransmitter::generatePulse (std::map< simsec, WpHz > & data, simtime_t & time, const simtime_t startTime, short polarity, double peak, const simtime_t chip) const protected virtual
 {
     ASSERT(polarity == -1 || polarity == +1);
     time += startTime; // adjust argument so that we use absolute time values in function
     data[simsec(time)] = WpHz(0);
     time += chip / 2;
     // Maximum point at symbol half (triangular pulse)
     // TODO polarity doesn't really make sense this way!?
     data[simsec(time)] = W(peak * polarity) / GHz(10.6 - 3.1);
     time += chip / 2;
     data[simsec(time)] = WpHz(0);
 }
Referenced by generateBurst(), generateSFD(), and generateSyncPreamble().
generateSFD()
void inet::physicallayer::Ieee802154UwbIrTransmitter::generateSFD (std::map< simsec, WpHz > & data, simtime_t & time, const simtime_t startTime) const protected virtual
 {
     const simtime_t sfdStart = cfg.NSync * cfg.sync_symbol_duration;
     for (short n = 0; n < 8; n = n + 1) {
         if (Ieee802154UwbIrMode::shortSFD[n] != 0) {
             for (short pos = 0; pos < cfg.CLength; pos = pos + 1) {
                 if (Ieee802154UwbIrMode::C31[Ieee802154UwbIrMode::Ci - 1][pos] != 0) {
                     time = sfdStart + n * cfg.sync_symbol_duration + pos * cfg.spreadingdL * cfg.pulse_duration;
                     // generatePulse(data, time, startTime, C31[Ci - 1][pos] * shortSFD[n]); // change pulse polarity
                     generatePulse(data, time, startTime, 1, Ieee802154UwbIrMode::maxPulse, cfg.pulse_duration); // always positive polarity
                 }
             }
         }
     }
 }
Referenced by generateIEEE802154AUWBSignal().
generateSyncPreamble()
void inet::physicallayer::Ieee802154UwbIrTransmitter::generateSyncPreamble (std::map< simsec, WpHz > & data, simtime_t & time, const simtime_t startTime) const protected virtual
 {
     // NSync repetitions of the Si symbol
     for (short n = 0; n < cfg.NSync; n = n + 1) {
         for (short pos = 0; pos < cfg.CLength; pos = pos + 1) {
             if (Ieee802154UwbIrMode::C31[Ieee802154UwbIrMode::Ci - 1][pos] != 0) {
                 if (n == 0 && pos == 0)
                     // we slide the first pulse slightly in time to get the first point "inside" the signal
                     time = 1E-12 + n * cfg.sync_symbol_duration + pos * cfg.spreadingdL * cfg.pulse_duration;
                 else
                     time = n * cfg.sync_symbol_duration + pos * cfg.spreadingdL * cfg.pulse_duration;
 //                generatePulse(data, time, startTime, C31[Ci - 1][pos], IEEE802154A::maxPulse, IEEE802154A::mandatory_pulse);
                 generatePulse(data, time, startTime, 1, Ieee802154UwbIrMode::maxPulse, cfg.pulse_duration); // always positive polarity
             }
         }
     }
 }
Referenced by generateIEEE802154AUWBSignal().
getFrameDuration()
simtime_t inet::physicallayer::Ieee802154UwbIrTransmitter::getFrameDuration (int psduLength) const protected
 {
     return cfg.preambleLength + (psduLength * 8 + 48) * cfg.data_symbol_duration;
 }
Referenced by createTransmission().
getMaxFrameDuration()
simtime_t inet::physicallayer::Ieee802154UwbIrTransmitter::getMaxFrameDuration () const protected
 {
     return cfg.preambleLength + Ieee802154UwbIrMode::MaxPSDULength * cfg.data_symbol_duration;
 }
getPhyMaxFrameDuration()
simtime_t inet::physicallayer::Ieee802154UwbIrTransmitter::getPhyMaxFrameDuration () const protected
 {
     simtime_t phyMaxFrameDuration = 0;
     simtime_t TSHR, TPHR, TPSDU, TCCApreamble;
     TSHR = getThdr();
     TPHR = getThdr();
     phyMaxFrameDuration = phyMaxFrameDuration + TSHR;
     return phyMaxFrameDuration;
 }
getThdr()
simtime_t inet::physicallayer::Ieee802154UwbIrTransmitter::getThdr () const protected
 {
     switch (cfg.channel) {
         default:
             switch (cfg.prf) {
                 case Ieee802154UwbIrMode::NOMINAL_4_M:
 //                    throw cRuntimeError("This optional mode is not implemented.");
                     return 0;
                     break;
                 case Ieee802154UwbIrMode::NOMINAL_16_M:
                     return 16.4E-6;
                 case Ieee802154UwbIrMode::NOMINAL_64_M:
                     return 16.8E-6;
                 case Ieee802154UwbIrMode::PRF_OFF:
                     return 0;
             }
             break;
     }
     return 0;
 }
Referenced by getPhyMaxFrameDuration().
initialize()
void inet::physicallayer::Ieee802154UwbIrTransmitter::initialize (int stage) override protected virtual
 {
     if (stage == INITSTAGE_LOCAL) {
         cfg = Ieee802154UwbIrMode::cfg_mandatory_16M;
     }
 }
printToStream()
std::ostream & inet::physicallayer::Ieee802154UwbIrTransmitter::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     return stream << "Ieee802154UwbIrTransmitter";
 }
Member Data Documentation
cfg
Ieee802154UwbIrMode inet::physicallayer::Ieee802154UwbIrTransmitter::cfg protected
Referenced by createTransmission(), generateBurst(), generateIEEE802154AUWBSignal(), generateSFD(), generateSyncPreamble(), getFrameDuration(), getMaxFrameDuration(), getThdr(), and initialize().
The documentation for this class was generated from the following files:
Ieee802154UwbIrTransmitter.h
Ieee802154UwbIrTransmitter.cc