INET Framework for OMNeT++/OMNEST: inet::tcp::TcpOptionUnknown Class Reference
inet::tcp::TcpOptionUnknown Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:156 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
TcpOptionUnknown ()
TcpOptionUnknown (const TcpOptionUnknown &other)
virtual ~TcpOptionUnknown ()
TcpOptionUnknown & operator= (const TcpOptionUnknown &other)
virtual TcpOptionUnknown * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setBytesArraySize (size_t size)
virtual size_t getBytesArraySize () const
virtual uint8_t getBytes (size_t k) const
virtual void setBytes (size_t k, uint8_t bytes)
virtual void insertBytes (size_t k, uint8_t bytes)
void insertBytes (uint8_t bytes)
virtual void appendBytes (uint8_t bytes)
virtual void eraseBytes (size_t k)
Public Member Functions inherited from inet::tcp::TcpOption
TcpOption ()
TcpOption (const TcpOption &other)
virtual ~TcpOption ()
TcpOption & operator= (const TcpOption &other)
virtual TcpOptionNumbers getKind () const
virtual void setKind (TcpOptionNumbers kind)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const TcpOptionUnknown &)=delete
Protected Member Functions inherited from inet::tcp::TcpOption
bool operator== (const TcpOption &)=delete
Protected Attributes
uint8_t * bytes = nullptr
size_t bytes_arraysize = 0
Protected Attributes inherited from inet::tcp::TcpOption
TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1)
unsigned short length = 1
Private Member Functions
void copy (const TcpOptionUnknown &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:156 by opp_msgtool.
class TcpOptionUnknown extends TcpOption
{
    kind = static_cast<TcpOptionNumbers>(-1);
    uint8_t bytes[];
}
Constructor & Destructor Documentation
TcpOptionUnknown() [1/2]
inet::tcp::TcpOptionUnknown::TcpOptionUnknown ()
TcpOptionUnknown() [2/2]
inet::tcp::TcpOptionUnknown::TcpOptionUnknown (const TcpOptionUnknown & other)
~TcpOptionUnknown()
virtual inet::tcp::TcpOptionUnknown::~TcpOptionUnknown () virtual
Member Function Documentation
appendBytes()
virtual void inet::tcp::TcpOptionUnknown::appendBytes (uint8_t bytes) virtual
copy()
void inet::tcp::TcpOptionUnknown::copy (const TcpOptionUnknown & other) private
dup()
virtual TcpOptionUnknown* inet::tcp::TcpOptionUnknown::dup () const inline override virtual
Reimplemented from inet::tcp::TcpOption.
 {return new TcpOptionUnknown(*this);}
eraseBytes()
virtual void inet::tcp::TcpOptionUnknown::eraseBytes (size_t k) virtual
getBytes()
virtual uint8_t inet::tcp::TcpOptionUnknown::getBytes (size_t k) const virtual
getBytesArraySize()
virtual size_t inet::tcp::TcpOptionUnknown::getBytesArraySize () const virtual
Referenced by inet::tcp::TcpHeaderSerializer::serializeOption().
insertBytes() [1/2]
virtual void inet::tcp::TcpOptionUnknown::insertBytes (size_t k, uint8_t bytes) virtual
insertBytes() [2/2]
void inet::tcp::TcpOptionUnknown::insertBytes (uint8_t bytes) inline
 {appendBytes(bytes);}
operator=()
TcpOptionUnknown& inet::tcp::TcpOptionUnknown::operator= (const TcpOptionUnknown & other)
operator==()
bool inet::tcp::TcpOptionUnknown::operator== (const TcpOptionUnknown &) protected delete
parsimPack()
virtual void inet::tcp::TcpOptionUnknown::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::TcpOptionUnknown::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::tcp::TcpOption.
Referenced by inet::tcp::doParsimUnpacking().
setBytes()
virtual void inet::tcp::TcpOptionUnknown::setBytes (size_t k, uint8_t bytes) virtual
setBytesArraySize()
virtual void inet::tcp::TcpOptionUnknown::setBytesArraySize (size_t size) virtual
Member Data Documentation
bytes
uint8_t* inet::tcp::TcpOptionUnknown::bytes = nullptr protected
bytes_arraysize
size_t inet::tcp::TcpOptionUnknown::bytes_arraysize = 0 protected
The documentation for this class was generated from the following file:
TcpHeader_m.h