INET Framework for OMNeT++/OMNEST: inet::NetworkInterface Class Reference
inet::NetworkInterface Class Reference
Interface entry for the interface table in IInterfaceTable.
#include <NetworkInterface.h>
Classes
class LocalGate
Public Types
enum State { UP, DOWN, GOING_UP, GOING_DOWN }
enum {
F_CARRIER, F_STATE, F_NAME, F_NODE_IN_GATEID,
F_NODE_OUT_GATEID, F_NETW_GATEIDX, F_LOOPBACK, F_BROADCAST,
F_MULTICAST, F_POINTTOPOINT, F_DATARATE, F_MTU,
F_MACADDRESS, F_TOKEN, F_IPV4_DATA, F_IPV6_DATA,
F_NEXTHOP_DATA, F_ISIS_DATA, F_TRILL_DATA, F_IEEE8021D_DATA,
F_CLNS_DATA
}
Public Member Functions
virtual void setInterfaceId (int id)
virtual void resetInterface ()
NetworkInterface ()
virtual ~NetworkInterface ()
virtual std::string str () const override
virtual std::string getInterfaceFullPath () const
virtual bool supportsPacketSending (cGate *gate) const override
Returns true if the processor supports sending packets at the given gate.
virtual bool supportsPacketPushing (cGate *gate) const override
Returns true if the processor supports pushing packets at the given gate.
virtual bool supportsPacketPulling (cGate *gate) const override
Returns true if the processor supports pulling packets at the given gate.
virtual bool supportsPacketPassing (cGate *gate) const override
Returns true if the processor supports passing packets as a whole at the given gate.
virtual bool supportsPacketStreaming (cGate *gate) const override
Returns true if the processor supports streaming packets at the given gate.
virtual bool canPushSomePacket (cGate *gate) const override
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
virtual bool canPushPacket (Packet *packet, cGate *gate) const override
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
virtual void pushPacket (Packet *packet, cGate *gate) override
Pushes the packet into the packet sink at the given gate.
virtual void pushPacketStart (Packet *packet, cGate *gate, bps datarate) override
Starts pushing the packet into the packet sink at the given gate.
virtual void pushPacketEnd (Packet *packet, cGate *gate) override
Ends pushing the packet into the packet sink at the given gate.
virtual void pushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength=b(0)) override
Progresses pushing the packet into the packet sink at the given gate.
IInterfaceTable * getInterfaceTable () const
Returns the IInterfaceTable this interface is in, or nullptr.
State getState () const
Returns the requested state of this interface.
cChannel * getRxTransmissionChannel ()
cChannel * getTxTransmissionChannel ()
bool isUp () const
Returns the combined state of the carrier and the interface requested state.
bool isDown () const
void setHasModuleIdAddress (bool value)
void setHasModulePathAddress (bool value)
const ModuleIdAddress getModuleIdAddress () const
const ModulePathAddress getModulePathAddress () const
const L3Address getNetworkAddress () const
virtual bool hasNetworkAddress (const L3Address &address) const
Field getters. Note they are non-virtual and inline, for performance reasons.
const Protocol * getProtocol () const
int getInterfaceId () const
const char * getInterfaceName () const
int getNodeOutputGateId () const
int getNodeInputGateId () const
int getMtu () const
bool hasCarrier () const
bool isBroadcast () const
bool isMulticast () const
bool isPointToPoint () const
bool isLoopback () const
bool isWired () const
bool isWireless () const
double getDatarate () const
const MacAddress & getMacAddress () const
const InterfaceToken & getInterfaceToken () const
Field setters
virtual void setProtocol (const Protocol *protocol)
virtual void setInterfaceName (const char *s)
virtual void setNodeOutputGateId (int i)
virtual void setNodeInputGateId (int i)
virtual void setMtu (int m)
virtual void setState (State s)
virtual void setCarrier (bool b)
virtual void setBroadcast (bool b)
virtual void setMulticast (bool b)
virtual void setPointToPoint (bool b)
virtual void setLoopback (bool b)
virtual void setDatarate (double d)
virtual void setMacAddress (const MacAddress &addr)
virtual void setInterfaceToken (const InterfaceToken &t)
bool matchesMacAddress (const MacAddress &address) const
Multicast MacAddress related functions
void addMulticastMacAddress (const MacAddress &address)
void removeMulticastMacAddress (const MacAddress &address)
bool matchesMulticastMacAddress (const MacAddress &address) const
Tag related functions
int getNumProtocolData () const
Returns the number of protocol data structures.
const InterfaceProtocolData * getProtocolData (int index) const
Returns the protocol data at the given index.
void clearProtocolDataSet ()
Clears the set of protocol data objects.
template<typename T >
const T * findProtocolData () const
Returns the protocol data for the provided type or returns nullptr if no such protocol data is found.
template<typename T >
T * findProtocolDataForUpdate ()
Returns the protocol data for the provided type or returns nullptr if no such protocol data is found.
template<typename T >
const T * getProtocolData () const
Returns the protocol data for the provided type or throws an exception if no such protocol data is found.
template<typename T >
T * getProtocolDataForUpdate ()
Returns the protocol data for the provided type or throws an exception if no such protocol data is found.
template<typename T >
T * addProtocolData ()
Returns a newly added protocol data for the provided type, or throws an exception if such a protocol data is already present.
template<typename T >
T * addProtocolDataIfAbsent ()
Returns a newly added protocol data for the provided type if absent, or returns the protocol data that is already present.
template<typename T >
T * removeProtocolData ()
Removes the protocol data for the provided type, or throws an exception if no such protocol data is found.
template<typename T >
T * removeProtocolDataIfPresent ()
Removes the protocol data for the provided type if present, or returns nullptr if no such protocol data is found.
Accessing protocol-specific interface data. Note methods are non-virtual, for performance reasons.
Ipv4Address getIpv4Address () const
Ipv4Address getIpv4Netmask () const
virtual void joinMulticastGroup (const L3Address &address)
virtual void changeMulticastGroupMembership (const L3Address &multicastAddress, McastSourceFilterMode oldFilterMode, const std::vector< L3Address > &oldSourceList, McastSourceFilterMode newFilterMode, const std::vector< L3Address > &newSourceList)
access to the cost process estimation
virtual bool setEstimateCostProcess (int, MacEstimateCostProcess *p)
virtual MacEstimateCostProcess * getEstimateCostProcess (int)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void handleStartOperation (LifecycleOperation *operation)
virtual void handleStopOperation (LifecycleOperation *operation)
virtual void handleCrashOperation (LifecycleOperation *operation)
Public Member Functions inherited from inet::queueing::IPacketProcessor
virtual ~IPacketProcessor ()
Public Member Functions inherited from inet::queueing::IPassivePacketSink
virtual ~IPassivePacketSink ()
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Protected Member Functions
virtual void configChanged (int fieldId)
virtual void stateChanged (int fieldId)
virtual void changed (simsignal_t signalID, int fieldId)
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void handleParameterChange (const char *name) override
virtual void refreshDisplay () const override
virtual void updateDisplayString () const override
virtual const char * resolveDirective (char directive) const override
virtual void receiveSignal (cComponent *source, simsignal_t signal, cObject *obj, cObject *details) override
virtual cGate * createGateObject (cGate::Type type) override
virtual double computeDatarate () const
virtual bool computeCarrier () const
virtual std::string getFullPath () const override
virtual const char * getName () const override
virtual void arrived (cMessage *message, cGate *gate, const SendOptions &options, simtime_t time) override
Protected Member Functions inherited from inet::queueing::PacketProcessorBase
virtual void handlePacketProcessed (Packet *packet)
virtual void checkPacketOperationSupport (cGate *gate) const
virtual void checkPacketOperationSupport (cGate *startGate, cGate *endGate) const
virtual void animate (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacket (Packet *packet, cGate *gate, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId, Action action) const
virtual void animatePacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, long transmissionId, Action action) const
virtual void animatePacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId, Action action) const
virtual void animatePacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions, Action action) const
virtual void pushOrSendPacket (Packet *packet, cGate *gate, IPassivePacketSink *consumer)
virtual void pushOrSendPacketStart (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, int transmissionId)
virtual void pushOrSendPacketEnd (Packet *packet, cGate *gate, IPassivePacketSink *consumer, int transmissionId)
virtual void pushOrSendPacketProgress (Packet *packet, cGate *gate, IPassivePacketSink *consumer, bps datarate, b position, b extraProcessableLength, int transmissionId)
virtual void animatePush (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacket (Packet *packet, cGate *gate) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePushPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePushPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePushPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void animatePull (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacket (Packet *packet, cGate *gate) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, long transmissionId) const
virtual void animatePullPacketStart (Packet *packet, cGate *gate, bps datarate, const SendOptions &sendOptions) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, long transmissionId) const
virtual void animatePullPacketEnd (Packet *packet, cGate *gate, const SendOptions &sendOptions) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, long transmissionId) const
virtual void animatePullPacketProgress (Packet *packet, cGate *gate, bps datarate, b position, b extraProcessableLength, const SendOptions &sendOptions) const
virtual void dropPacket (Packet *packet, PacketDropReason reason, int limit=-1)
Protected Attributes
cGate * upperLayerIn = nullptr
cGate * upperLayerOut = nullptr
cGate * rxIn = nullptr
cGate * txOut = nullptr
cChannel * rxTransmissionChannel = nullptr
cChannel * txTransmissionChannel = nullptr
queueing::IPassivePacketSink * upperLayerInConsumer = nullptr
queueing::IPassivePacketSink * upperLayerOutConsumer = nullptr
const Protocol * protocol = nullptr
ModuleRefByPar< IInterfaceTable > interfaceTable
IInterfaceTable that contains this interface, or nullptr.
int interfaceId = -1
identifies the interface in the IInterfaceTable
std::string interfaceName
int nodeOutputGateId = -1
id of the output gate of this host/router (or -1 if this is a virtual interface)
int nodeInputGateId = -1
id of the input gate of this host/router (or -1 if this is a virtual interface)
int mtu = 0
Maximum Transmission Unit (e.g. 1500 on Ethernet); 0 means infinite (i.e. never fragment)
State state = DOWN
requested interface state, similar to Linux ifup/ifdown
bool carrier = false
presence of the physical or virtual carrier
bool broadcast = false
interface supports broadcast
bool multicast = false
interface supports multicast
bool pointToPoint = false
interface is point-to-point link
bool loopback = false
interface is loopback interface
bool hasModuleIdAddress = false
bool hasModulePathAddress = false
double datarate = 0
data rate in bit/s
MacAddress macAddr
link-layer address (for now, only IEEE 802 MAC addresses are supported)
InterfaceToken token
for Ipv6 stateless autoconfig (RFC 1971), interface identifier (RFC 2462)
std::vector< MacAddress > multicastAddresses
TagSet protocolDataSet
std::vector< MacEstimateCostProcess * > estimateCostProcessArray
Protected Attributes inherited from inet::queueing::PacketProcessorBase
const char * displayStringTextFormat = nullptr
int numProcessedPackets = -1
b processedTotalLength = b(-1)
Private Member Functions
NetworkInterface (const NetworkInterface &obj)
NetworkInterface & operator= (const NetworkInterface &obj)
Friends
class InterfaceProtocolData
Additional Inherited Members
Protected Types inherited from inet::queueing::PacketProcessorBase
enum Action { PUSH, PULL }
Detailed Description
Interface entry for the interface table in IInterfaceTable.
See also
IInterfaceTable
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
F_CARRIER
F_STATE
F_NAME
F_NODE_IN_GATEID
F_NODE_OUT_GATEID
F_NETW_GATEIDX
F_LOOPBACK
F_BROADCAST
F_MULTICAST
F_POINTTOPOINT
F_DATARATE
F_MTU
F_MACADDRESS
F_TOKEN
F_IPV4_DATA
F_IPV6_DATA
F_NEXTHOP_DATA
F_ISIS_DATA
F_TRILL_DATA
F_IEEE8021D_DATA
F_CLNS_DATA
          {
         F_CARRIER, F_STATE,
         F_NAME, F_NODE_IN_GATEID, F_NODE_OUT_GATEID, F_NETW_GATEIDX,
         F_LOOPBACK, F_BROADCAST, F_MULTICAST, F_POINTTOPOINT,
         F_DATARATE, F_MTU, F_MACADDRESS, F_TOKEN,
         F_IPV4_DATA, F_IPV6_DATA, F_NEXTHOP_DATA, F_ISIS_DATA, F_TRILL_DATA, F_IEEE8021D_DATA, F_CLNS_DATA
     };
State
enum inet::NetworkInterface::State
Enumerator
UP
DOWN
GOING_UP
GOING_DOWN
 { UP, DOWN, GOING_UP, GOING_DOWN };
Constructor & Destructor Documentation
NetworkInterface() [1/2]
inet::NetworkInterface::NetworkInterface (const NetworkInterface & obj) private
NetworkInterface() [2/2]
inet::NetworkInterface::NetworkInterface ()
 {
 }
~NetworkInterface()
inet::NetworkInterface::~NetworkInterface () virtual
 {
     resetInterface();
 }
Member Function Documentation
addMulticastMacAddress()
void inet::NetworkInterface::addMulticastMacAddress (const MacAddress & address)
 {
     if (contains(multicastAddresses, address))
         throw cRuntimeError("Multicast MacAddress already added: '%s'", address.str().c_str());
     multicastAddresses.push_back(address);
 }
addProtocolData()
template<typename T > T* inet::NetworkInterface::addProtocolData () inline
Returns a newly added protocol data for the provided type, or throws an exception if such a protocol data is already present.
{
         auto t = protocolDataSet.addTag<T>();
         auto ipd = static_cast<InterfaceProtocolData *>(t);
         ipd->ownerp = this;
         changed(interfaceConfigChangedSignal, ipd->id);
         return t;
     }
Referenced by inet::NextHopRoutingTable::configureInterface(), inet::Ipv6RoutingTable::configureInterfaceForIpv6(), inet::L2NodeConfigurator::prepareInterface(), and inet::Ipv4NodeConfigurator::prepareInterface().
addProtocolDataIfAbsent()
template<typename T > T* inet::NetworkInterface::addProtocolDataIfAbsent () inline
Returns a newly added protocol data for the provided type if absent, or returns the protocol data that is already present.
{
         auto t = protocolDataSet.addTagIfAbsent<T>();
         auto ipd = static_cast<InterfaceProtocolData *>(t);
         if (ipd->ownerp != this) {
             ipd->ownerp = this;
             changed(interfaceConfigChangedSignal, ipd->id);
         }
         return t;
     }
arrived()
void inet::NetworkInterface::arrived (cMessage * message, cGate * gate, const SendOptions & options, simtime_t time) override protected virtual
 {
     if (gate == upperLayerOut && message->isPacket()) {
         auto packet = check_and_cast<Packet *>(message);
         packet->addTagIfAbsent<InterfaceInd>()->setInterfaceId(interfaceId);
     }
     cModule::arrived(message, gate, options, time);
 }
canPushPacket()
virtual bool inet::NetworkInterface::canPushPacket (Packet * packet, cGate * gate) const inline override virtual
Returns true if the given packet can be pushed at the given gate into the packet sink without raising an error.
The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
 { return true; }
canPushSomePacket()
virtual bool inet::NetworkInterface::canPushSomePacket (cGate * gate) const inline override virtual
Returns false if the packet sink is full at the given gate and no more packets can be pushed into it without raising an error.
The gate must be a valid gate of this module and it must support pushing packets.
Implements inet::queueing::IPassivePacketSink.
 { return true; }
changed()
void inet::NetworkInterface::changed (simsignal_t signalID, int fieldId) protected virtual
 {
     if (interfaceTable) {
         NetworkInterfaceChangeDetails details(this, fieldId);
         interfaceTable->interfaceChanged(signalID, &details);
     }
 }
Referenced by inet::InterfaceProtocolData::changed(), and clearProtocolDataSet().
changeMulticastGroupMembership()
void inet::NetworkInterface::changeMulticastGroupMembership (const L3Address & multicastAddress, McastSourceFilterMode oldFilterMode, const std::vector< L3Address > & oldSourceList, McastSourceFilterMode newFilterMode, const std::vector< L3Address > & newSourceList) virtual
 {
     switch (multicastAddress.getType()) {
 #ifdef INET_WITH_IPv4
         case L3Address::IPv4: {
             std::vector<Ipv4Address> oldIPv4SourceList, newIPv4SourceList;
             toIpv4AddressVector(oldSourceList, oldIPv4SourceList);
             toIpv4AddressVector(newSourceList, newIPv4SourceList);
             getProtocolDataForUpdate<Ipv4InterfaceData>()->changeMulticastGroupMembership(multicastAddress.toIpv4(),
                     oldFilterMode, oldIPv4SourceList, newFilterMode, newIPv4SourceList);
             break;
         }
 #endif // ifdef INET_WITH_IPv4
 #ifdef INET_WITH_IPv6
         case L3Address::IPv6:
             // TODO
             throw cRuntimeError("changeMulticastGroupMembership() not implemented for type %s", L3Address::getTypeName(multicastAddress.getType()));
             break;
 #endif // ifdef INET_WITH_IPv6
         case L3Address::MAC:
         case L3Address::MODULEID:
         case L3Address::MODULEPATH:
             // TODO
             throw cRuntimeError("changeMulticastGroupMembership() not implemented for type %s", L3Address::getTypeName(multicastAddress.getType()));
             break;
         default:
             throw cRuntimeError("Unknown address type");
     }
 }
Referenced by inet::Udp::blockMulticastSources(), inet::Udp::joinMulticastSources(), inet::Udp::leaveMulticastGroups(), inet::Udp::leaveMulticastSources(), inet::Udp::setMulticastSourceFilter(), and inet::Udp::unblockMulticastSources().
clearProtocolDataSet()
void inet::NetworkInterface::clearProtocolDataSet ()
Clears the set of protocol data objects.
 {
     std::vector<int> ids;
     int n = protocolDataSet.getNumTags();
     ids.reserve(n);
     for (int i = 0; i < n; i++)
         ids[i] = static_cast<const InterfaceProtocolData *>(protocolDataSet.getTag(i))->id;
     protocolDataSet.clearTags();
     for (int i = 0; i < n; i++)
         changed(interfaceConfigChangedSignal, ids[i]);
 }
computeCarrier()
bool inet::NetworkInterface::computeCarrier () const protected virtual
 {
     if (isWireless())
         return true;
     else {
         bool connected = rxTransmissionChannel != nullptr && txTransmissionChannel != nullptr;
         bool disabled = !connected || rxTransmissionChannel->isDisabled() || txTransmissionChannel->isDisabled();
         return connected && !disabled;
     }
 }
Referenced by initialize(), and receiveSignal().
computeDatarate()
double inet::NetworkInterface::computeDatarate () const protected virtual
 {
     double moduleDatarate = 0;
     if (hasPar("bitrate"))
         moduleDatarate = par("bitrate");
     double channelDatarate = 0;
     if (txTransmissionChannel != nullptr && txTransmissionChannel->hasPar("datarate"))
         channelDatarate = txTransmissionChannel->par("datarate");
     if (moduleDatarate != 0 && channelDatarate != 0 && moduleDatarate != channelDatarate)
         throw cRuntimeError("Wired network interface datarate is set on both the network interface module and on the corresponding transmission channel and the two values are different");
     return moduleDatarate != 0 ? moduleDatarate : channelDatarate;
 }
Referenced by handleParameterChange(), initialize(), and receiveSignal().
configChanged()
virtual void inet::NetworkInterface::configChanged (int fieldId) inline protected virtual
 { changed(interfaceConfigChangedSignal, fieldId); }
createGateObject()
virtual cGate* inet::NetworkInterface::createGateObject (cGate::Type type) inline override protected virtual
{
         return type == cGate::INPUT ? new LocalGate(this) : cModule::createGateObject(type);
     }
findProtocolData()
template<typename T > const T* inet::NetworkInterface::findProtocolData () const inline
Returns the protocol data for the provided type or returns nullptr if no such protocol data is found.
{
         return protocolDataSet.findTag<T>();
     }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::InterfaceTable::collectMulticastGroups(), inet::Ipv4RoutingTable::configureRouterId(), inet::InterfaceTable::findInterfaceByAddress(), inet::PingApp::getAllAddresses(), inet::L3AddressResolver::getInterfaceIpv6Address(), inet::L3AddressResolver::getInterfaceModuleIdAddress(), inet::L3AddressResolver::getInterfaceModulePathAddress(), inet::Ipv6AddressType::getLinkLocalAddress(), inet::Gpsr::getSelfAddress(), inet::GlobalArp::initialize(), inet::Igmpv2::initialize(), inet::ospfv2::Router::isDirectRoute(), inet::StpTester::isForwarding(), inet::Ieee8021dRelay::isForwardingInterface(), inet::ospfv3::Ospfv3Process::isInInterfaceTable(), inet::InterfaceTable::isNeighborAddress(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::RoutingTableParser::parseInterfaces(), inet::Icmp::possiblyLocalBroadcast(), inet::sctp::SctpAssociation::processInitArrived(), inet::Ldp::rebuildFecList(), inet::GlobalArp::receiveSignal(), inet::RoutingTableRecorder::recordInterfaceChange(), inet::sctp::SctpAssociation::sendInit(), inet::NextHopRoute::str(), inet::InterfaceTable::updateLinkDisplayString(), inet::Ipv4RoutingTable::updateNetmaskRoutes(), and inet::Ieee8021dRelay::updatePeerAddress().
findProtocolDataForUpdate()
template<typename T > T* inet::NetworkInterface::findProtocolDataForUpdate () inline
Returns the protocol data for the provided type or returns nullptr if no such protocol data is found.
{
         return protocolDataSet.findTagForUpdate<T>();
     }
Referenced by inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes(), inet::Ipv4NetworkConfigurator::createInterfaceInfo(), inet::Igmpv3::initialize(), and inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaces6Config().
getDatarate()
double inet::NetworkInterface::getDatarate () const inline
 { return datarate; }
Referenced by inet::NextHopRoutingTable::configureInterface(), inet::eigrp::EigrpInterface::EigrpInterface(), inet::DiffservUtil::getInterfaceDatarate(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::Ipv4NodeConfigurator::prepareInterface(), inet::eigrp::EigrpIpv6Pdm::receiveSignal(), and inet::eigrp::EigrpIpv4Pdm::receiveSignal().
getEstimateCostProcess()
MacEstimateCostProcess * inet::NetworkInterface::getEstimateCostProcess (int position) virtual
 {
     ASSERT(position >= 0);
     if ((size_t)position < estimateCostProcessArray.size()) {
         return estimateCostProcessArray[position];
     }
     return nullptr;
 }
getFullPath()
virtual std::string inet::NetworkInterface::getFullPath () const inline override protected virtual
 { return cModule::getFullPath(); }
getInterfaceFullPath()
std::string inet::NetworkInterface::getInterfaceFullPath () const virtual
 {
     return !interfaceTable ? getInterfaceName() : interfaceTable->getHostModule()->getFullPath() + "." + getInterfaceName();
 }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::assignAddresses(), inet::Ipv4NetworkConfigurator::collectCompatibleInterfaces(), inet::InterfaceTable::discoverConnectingGates(), inet::Ipv4NetworkConfigurator::dumpLinks(), inet::ospfv2::Ospfv2ConfigReader::findMatchingConfig(), inet::NetworkConfiguratorBase::Interface::getFullPath(), inet::L2NetworkConfigurator::InterfaceInfo::getFullPath(), inet::L3NetworkConfiguratorBase::InterfaceInfo::getFullPath(), inet::ospfv2::Ospfv2ConfigReader::getInterfaceByXMLAttributesOf(), inet::Ipv4::preroutingFinish(), and inet::PcapngWriter::writeInterface().
getInterfaceId()
int inet::NetworkInterface::getInterfaceId () const inline
 { return interfaceId; }
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::Ipv6FlatNetworkConfigurator::addOwnAdvPrefixRoutes(), inet::Ipv6FlatNetworkConfigurator::addStaticRoutes(), inet::Ipv4::arpResolutionCompleted(), inet::Udp::blockMulticastSources(), inet::InterfaceTable::collectMulticastGroups(), inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes(), inet::Ipv6RoutingTable::configureInterfaceForIpv6(), inet::xMIPv6::createAndSendBAMessage(), inet::xMIPv6::createAndSendBRRMessage(), inet::xMIPv6::createAndSendBUMessage(), inet::Ipv6NeighbourDiscovery::createAndSendNsPacket(), inet::Ipv6NeighbourDiscovery::createAndSendRaPacket(), inet::Ipv6NeighbourDiscovery::createAndSendRsPacket(), inet::xMIPv6::createBCEntryExpiryTimer(), inet::xMIPv6::createBRRTimer(), inet::xMIPv6::createBULEntryExpiryTimer(), inet::xMIPv6::createBUTimer(), inet::visualizer::Ieee80211OsgVisualizer::createIeee80211Visualization(), inet::visualizer::Ieee80211CanvasVisualizer::createIeee80211Visualization(), inet::visualizer::InterfaceTableOsgVisualizer::createInterfaceVisualization(), inet::visualizer::InterfaceTableCanvasVisualizer::createInterfaceVisualization(), inet::Ipv6NeighbourDiscovery::createRaTimer(), inet::xMIPv6::createTestInitTimer(), inet::xMIPv6::createTokenEntryExpiryTimer(), inet::Ipv4::datagramLocalOut(), inet::NextHopForwarding::decapsulate(), inet::bgp::BgpRouter::decisionProcess(), inet::PacketReceiverBase::decodePacket(), inet::InterfaceTable::deleteInterface(), inet::Ipv6NeighbourDiscovery::determineNextHop(), inet::Ipv6::determineOutputInterface(), inet::Ipv6NeighbourDiscovery::fetchAdvIfEntry(), inet::xMIPv6::fetchBUTransmitIfEntry(), inet::Ipv6NeighbourDiscovery::fetchRdEntry(), inet::Ipv4::forwardMulticastPacket(), inet::Igmpv2::getHostInterfaceData(), inet::Igmpv3::getHostInterfaceData(), inet::visualizer::Ieee80211VisualizerBase::getIeee80211Visualization(), inet::PimDm::getIncomingInterface(), inet::PimSm::getIncomingInterface(), inet::PimInterface::getInterfaceId(), inet::PimNeighbor::getInterfaceId(), inet::Rip::getInterfaceMetric(), inet::visualizer::InterfaceTableVisualizerBase::getInterfaceVisualization(), inet::ospfv2::Router::getPreferredEntry(), inet::Igmpv2::getRouterInterfaceData(), inet::Igmpv3::getRouterInterfaceData(), inet::ospfv2::Router::getRoutesToASBoundaryRouter(), inet::xMIPv6::handleBCExpiry(), inet::xMIPv6::handleBULExpiry(), inet::ospfv2::Ospfv2::handleInterfaceDown(), inet::EthernetCutthroughSource::handleMessage(), inet::Dsdv::handleMessageWhenUp(), inet::MessageDispatcher::handleRegisterInterface(), inet::Dsdv::handleSelfMessage(), inet::Ieee8022LlcSocketIo::handleStartOperation(), inet::xMIPv6::handleTokenExpiry(), inet::ospfv2::Router::hasRouteToASBoundaryRouter(), inet::PimSm::IamDR(), inet::TunLoopbackApp::initialize(), inet::TunnelApp::initialize(), inet::Ipv6RoutingTable::initialize(), inet::Ldp::initialize(), inet::Ipv6NeighbourDiscovery::initiateDad(), inet::Ipv6NeighbourDiscovery::initiateRouterDiscovery(), inet::Udp::joinMulticastSources(), inet::Udp::leaveMulticastSources(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfaces6Config(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpInterfacesConfig(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpIPv4Networks(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcesses6Config(), inet::eigrp::EigrpDeviceConfigurator::loadEigrpProcessesConfig(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::Ospfv2ConfigReader::loadLoopbackParameters(), inet::PimSm::multicastPacketForwarded(), inet::PimDm::multicastReceiverAdded(), inet::PimSm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), inet::PimSm::multicastReceiverRemoved(), inet::ospfv3::Ospfv3Interface::Ospfv3Interface(), inet::Ipv4::preroutingFinish(), inet::Arp::processArpPacket(), inet::PimDm::processAssert(), inet::DhcpServer::processDhcpMessage(), inet::PimDm::processGraftPacket(), inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::Mpls::processMplsPacketFromL2(), inet::Ipv6NeighbourDiscovery::processNaPacket(), inet::Ipv6NeighbourDiscovery::processNsWithSpecifiedSrcAddr(), inet::PimSm::processPruneG(), inet::PimSm::processPruneSG(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfo(), inet::dymo::Dymo::processRerr(), inet::EthernetCutthroughSource::pushPacketEnd(), inet::Ipv4::reassembleAndDeliverFinish(), inet::eigrp::EigrpIpv6Pdm::receiveSignal(), inet::Gptp::receiveSignal(), inet::Rip::receiveSignal(), inet::Ipv6RoutingTable::receiveSignal(), inet::PimDm::receiveSignal(), inet::Igmpv2::receiveSignal(), inet::PimSm::receiveSignal(), inet::Igmpv3::receiveSignal(), inet::eigrp::EigrpIpv4Pdm::receiveSignal(), inet::PimSm::restartExpiryTimer(), inet::xMIPv6::returningHome(), inet::Ipv4::routeLocalBroadcastPacket(), inet::Ipv6::routePacket(), inet::Ipv4::routeUnicastPacket(), inet::PimDm::rpfInterfaceHasChanged(), inet::Arp::sendArpGratuitous(), inet::Arp::sendArpProbe(), inet::Arp::sendArpRequest(), inet::PimDm::sendAssertPacket(), inet::NextHopForwarding::sendDatagramToOutput(), inet::Ipv6::sendDatagramToOutput(), inet::NetworkProtocolBase::sendDown(), inet::dymo::Dymo::sendDymoPacket(), inet::bgp::BgpSession::sendKeepAliveMessage(), inet::bgp::BgpSession::sendOpenMessage(), inet::EthernetSocket::sendOut(), inet::Ieee8021qSocket::sendOut(), inet::RelayInterfaceSelector::sendPacket(), inet::MacRelayUnitBase::sendPacket(), inet::ospfv3::Ospfv3Process::sendPacket(), inet::Rip::sendPacket(), inet::xMIPv6::sendPeriodicBRR(), inet::PimSm::sendPIMAssert(), inet::PimSm::sendPIMJoin(), inet::PimSm::sendPIMPrune(), inet::PimSm::sendPIMRegisterNull(), inet::PimSm::sendPIMRegisterStop(), inet::Igmpv3::sendQueryToIP(), inet::Igmpv3::sendReportToIP(), inet::Ipv6NeighbourDiscovery::sendSolicitedNa(), inet::xMIPv6::sendTestInit(), inet::Igmpv2::sendToIP(), inet::DhcpServer::sendToUDP(), inet::DhcpClient::sendToUdp(), inet::Ipv6NeighbourDiscovery::sendUnsolicitedNa(), inet::bgp::BgpSession::sendUpdateMessage(), inet::Udp::setMulticastSourceFilter(), inet::UdpSocketIo::setSocketOptions(), inet::UdpBasicApp::setSocketOptions(), inet::Rip::startRIPRouting(), str(), inet::Udp::unblockMulticastSources(), inet::PimDm::unroutableMulticastPacketArrived(), inet::PimSm::unroutableMulticastPacketArrived(), inet::PimSm::updateDesignatedRouterAddress(), and inet::MacRelayUnitBase::updatePeerAddress().
getInterfaceName()
const char* inet::NetworkInterface::getInterfaceName () const inline
 { return interfaceName.c_str(); }
Referenced by inet::InterfaceTable::addInterface(), inet::Arp::addressRecognized(), inet::DhcpClient::bindLease(), inet::DhcpClient::chooseInterface(), inet::RsvpTe::commitResv(), inet::Igmpv3::configureInterface(), inet::Gpsr::configureInterfaces(), inet::dymo::Dymo::configureInterfaces(), inet::PimInterfaceTable::createInterface(), inet::InterfaceTable::deleteInterface(), inet::Ipv4::determineOutgoingInterfaceForMulticastDatagram(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::eigrp::EigrpInterface::EigrpInterface(), inet::MacForwardingTableConfigurator::extendConfiguration(), inet::Ipv4FlatNetworkConfigurator::fillRoutingTables(), inet::Ldp::findInterfaceFromPeerAddr(), inet::ospfv2::Ospfv2ConfigReader::findMatchingConfig(), inet::Ipv4::forwardMulticastPacket(), inet::ospfv2::Ospfv2ConfigReader::getInterfaceByXMLAttributesOf(), getInterfaceFullPath(), inet::Ipv4Route::getInterfaceName(), inet::L3NetworkConfiguratorBase::getWirelessId(), inet::ospfv3::Ospfv3Splitter::handleMessage(), inet::NextHopForwarding::handlePacketFromNetwork(), inet::Ted::initializeTED(), inet::bgp::BgpConfigReader::isInInterfaceTable(), inet::L3NetworkConfiguratorBase::isWirelessInterface(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::Ospfv2ConfigReader::loadLoopbackParameters(), inet::Ldp::locateNextHop(), inet::L3NetworkConfiguratorBase::InterfaceMatcher::matches(), inet::PimSm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), inet::PimSm::multicastReceiverRemoved(), inet::Igmpv3::multicastSourceListChanged(), inet::Ipv4::preroutingFinish(), inet::Ipv4RoutingTable::printMulticastRoutingTable(), inet::Ipv4RoutingTable::printRoutingTable(), inet::PimDm::processAssertPacket(), inet::PimDm::processAssertTimer(), inet::PimBase::processHelloPacket(), inet::Igmpv3::processHostGeneralQueryTimer(), inet::Igmpv3::processHostGroupQueryTimer(), inet::Igmpv2::processHostGroupTimer(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::Igmpv2::processLeave(), inet::Igmpv2::processLeaveTimer(), inet::Mpls::processMplsPacketFromL2(), inet::PimSm::processPruneG(), inet::PimSm::processPruneSG(), inet::Igmpv2::processQuery(), inet::Igmpv3::processQuery(), inet::Igmpv2::processQueryTimer(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf(), inet::Igmpv3::processReport(), inet::Igmpv2::processRexmtTimer(), inet::Igmpv3::processRouterGeneralQueryTimer(), inet::Igmpv3::processRouterGroupTimer(), inet::Igmpv3::processRouterSourceTimer(), inet::Igmpv2::processV2Report(), inet::L2NetworkConfigurator::readInterfaceConfiguration(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration(), inet::RoutingTableRecorder::recordInterfaceChange(), inet::Arp::resolveL3Address(), inet::NextHopForwarding::routePacket(), inet::Ipv4::routeUnicastPacket(), inet::Ipv4::routeUnicastPacketFinish(), inet::PimDm::rpfInterfaceHasChanged(), inet::PimDm::sendAssertPacket(), inet::NextHopForwarding::sendDatagramToOutput(), inet::Igmpv3::sendGroupReport(), inet::PimBase::sendHelloPacket(), inet::bgp::BgpSession::sendKeepAliveMessage(), inet::Igmpv2::sendLeave(), inet::bgp::BgpSession::sendOpenMessage(), inet::PimSm::sendPIMAssert(), inet::Igmpv2::sendQuery(), inet::Igmpv2::sendReport(), inet::Rip::sendRIPRequest(), inet::bgp::BgpSession::sendUpdateMessage(), inet::Dsdv::start(), inet::Igmpv2::startHostTimer(), inet::PimNeighbor::str(), inet::NextHopRoute::str(), inet::RipRoute::str(), inet::Ipv6Route::str(), inet::Ipv4MulticastRoute::str(), str(), inet::DhcpClient::unbindLease(), and inet::PcapngWriter::writeInterface().
getInterfaceTable()
IInterfaceTable* inet::NetworkInterface::getInterfaceTable () const inline
Returns the IInterfaceTable this interface is in, or nullptr.
 { return interfaceTable; }
Referenced by inet::Ipv4InterfaceData::changeMulticastGroupMembership(), inet::L3AddressResolver::findHostWithMacAddress(), inet::Ipv4NetworkConfigurator::findInterfaceOnLinkByNode(), inet::L3NetworkConfiguratorBase::getWirelessId(), inet::Ipv6InterfaceData::joinMulticastGroup(), inet::Ipv6InterfaceData::leaveMulticastGroup(), inet::InterfaceMatcher::linkContainsMatchingHost(), inet::Ipv4NetworkConfigurator::linkContainsMatchingHostExcept(), inet::InterfaceMatcher::Selector::matches(), inet::L3NetworkConfiguratorBase::InterfaceMatcher::matches(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), and inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration().
getInterfaceToken()
const InterfaceToken& inet::NetworkInterface::getInterfaceToken () const inline
 { return token; }
Referenced by inet::Ipv6NeighbourDiscovery::assignLinkLocalAddress(), inet::Ipv6RoutingTable::assignRequiredNodeAddresses(), and inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes().
getIpv4Address()
Ipv4Address inet::NetworkInterface::getIpv4Address () const
{
 #ifdef INET_WITH_IPv4
     auto ipv4data = findProtocolData<Ipv4InterfaceData>();
     return ipv4data == nullptr ? Ipv4Address::UNSPECIFIED_ADDRESS : ipv4data->getIPAddress();
 #else
     return Ipv4Address::UNSPECIFIED_ADDRESS;
 #endif // ifdef INET_WITH_IPv4
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::addInterfaceToEigrp(), inet::eigrp::EigrpIpv4Pdm::checkNeighborshipRules(), inet::L3AddressResolver::getInterfaceIpv4Address(), inet::ospfv2::Ospfv2ConfigReader::loadLoopbackParameters(), and inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange().
getIpv4Netmask()
Ipv4Address inet::NetworkInterface::getIpv4Netmask () const
{
 #ifdef INET_WITH_IPv4
     auto ipv4data = findProtocolData<Ipv4InterfaceData>();
     return ipv4data == nullptr ? Ipv4Address::UNSPECIFIED_ADDRESS : ipv4data->getNetmask();
 #else
     return Ipv4Address::UNSPECIFIED_ADDRESS;
 #endif // ifdef INET_WITH_IPv4
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::addInterfaceToEigrp(), inet::eigrp::EigrpIpv4Pdm::checkNeighborshipRules(), inet::L3AddressResolver::getInterfaceIpv4Address(), and inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange().
getMacAddress()
const MacAddress& inet::NetworkInterface::getMacAddress () const inline
 { return macAddr; }
Referenced by inet::NextHopRoutingTable::configureInterface(), inet::Ipv6NeighbourDiscovery::createAndSendNsPacket(), inet::Ipv6NeighbourDiscovery::createAndSendRaPacket(), inet::Ipv6NeighbourDiscovery::createAndSendRsPacket(), inet::InterfaceTable::findInterfaceByAddress(), inet::L3AddressResolver::findInterfaceWithMacAddress(), inet::L3AddressResolver::getInterfaceMacAddress(), inet::VirtualTunnel::handleMessage(), inet::Ieee8021dRelay::handleStartOperation(), inet::DhcpClient::handleStartOperation(), hasNetworkAddress(), inet::VirtualTunnel::initialize(), initialize(), inet::EthernetEncapsulation::processPacketFromHigherLayer(), inet::Arp::resolveMacAddressForArpReply(), inet::Arp::sendArpRequest(), inet::Ipv4::sendDatagramToOutput(), inet::Ipv6NeighbourDiscovery::sendSolicitedNa(), inet::Ipv6NeighbourDiscovery::sendUnsolicitedNa(), and str().
getModuleIdAddress()
const ModuleIdAddress inet::NetworkInterface::getModuleIdAddress () const inline
 { return hasModuleIdAddress ? ModuleIdAddress(getId()) : ModuleIdAddress(0); }
Referenced by inet::InterfaceTable::findInterfaceByAddress(), inet::L3AddressResolver::getInterfaceModuleIdAddress(), getNetworkAddress(), and hasNetworkAddress().
getModulePathAddress()
const ModulePathAddress inet::NetworkInterface::getModulePathAddress () const inline
 { return hasModulePathAddress ? ModulePathAddress(getId()) : ModulePathAddress(0); }
Referenced by inet::InterfaceTable::findInterfaceByAddress(), inet::L3AddressResolver::getInterfaceModulePathAddress(), getNetworkAddress(), and hasNetworkAddress().
getMtu()
int inet::NetworkInterface::getMtu () const inline
 { return mtu; }
Referenced by inet::L3NetworkConfiguratorBase::computeWiredLinkWeight(), inet::L3NetworkConfiguratorBase::computeWirelessLinkWeight(), inet::eigrp::EigrpInterface::EigrpInterface(), inet::Ipv6::fragmentAndSend(), inet::Ipv4::fragmentAndSend(), inet::ospfv3::Ospfv3Interface::getInterfaceMTU(), inet::sctp::SctpAssociation::pmStartPathManagement(), inet::rtp::Rtp::resolveMTU(), inet::sctp::SctpPathVariables::SctpPathVariables(), inet::NextHopForwarding::sendDatagramToOutput(), inet::Rip::sendRoutes(), inet::ospfv2::Ospfv2Interface::setIfIndex(), and str().
getName()
virtual const char* inet::NetworkInterface::getName () const inline override protected virtual
 { return cModule::getName(); }
getNetworkAddress()
const L3Address inet::NetworkInterface::getNetworkAddress () const
 {
 #ifdef INET_WITH_IPv4
     if (auto ipv4data = findProtocolData<Ipv4InterfaceData>())
         return ipv4data->getIPAddress();
 #endif // ifdef INET_WITH_IPv4
 #ifdef INET_WITH_IPv6
     if (auto ipv6data = findProtocolData<Ipv6InterfaceData>())
         return ipv6data->getPreferredAddress();
 #endif // ifdef INET_WITH_IPv6
 #ifdef INET_WITH_NEXTHOP
     if (auto nextHopData = findProtocolData<NextHopInterfaceData>())
         return nextHopData->getAddress();
 #endif // ifdef INET_WITH_NEXTHOP
     if (hasModuleIdAddress)
         return getModuleIdAddress();
     if (hasModulePathAddress)
         return getModulePathAddress();
     return L3Address();
 }
Referenced by resolveDirective().
getNodeInputGateId()
int inet::NetworkInterface::getNodeInputGateId () const inline
 { return nodeInputGateId; }
Referenced by inet::InterfaceTable::findInterfaceByInterfaceModule(), inet::MatrixCloudDelayer::getPathOfConnectedNodeOnIfaceID(), and inet::L2NetworkConfigurator::readInterfaceConfiguration().
getNodeOutputGateId()
int inet::NetworkInterface::getNodeOutputGateId () const inline
 { return nodeOutputGateId; }
Referenced by inet::L3AddressResolver::addressOf(), inet::L3NetworkConfiguratorBase::extractDeviceNeighbors(), inet::NetworkConfiguratorBase::extractTopology(), inet::L2NetworkConfigurator::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::InterfaceTable::findInterfaceByInterfaceModule(), inet::ospfv2::Ospfv2ConfigReader::findMatchingConfig(), inet::ospfv2::Ospfv2ConfigReader::getInterfaceByXMLAttributesOf(), inet::visualizer::InterfaceTableVisualizerBase::getOutputGate(), inet::MatrixCloudDelayer::getPathOfConnectedNodeOnIfaceID(), inet::Ted::initializeTED(), inet::InterfaceMatcher::linkContainsMatchingHost(), and inet::InterfaceTable::updateLinkDisplayString().
getNumProtocolData()
int inet::NetworkInterface::getNumProtocolData () const inline
Returns the number of protocol data structures.
{
         return protocolDataSet.getNumTags();
     }
getProtocol()
const Protocol* inet::NetworkInterface::getProtocol () const inline
 { return protocol; }
Referenced by inet::Arp::processArpPacket(), inet::Arp::sendArpGratuitous(), inet::Arp::sendArpProbe(), inet::Arp::sendArpRequest(), inet::NextHopForwarding::sendDatagramToOutput(), inet::Ipv6::sendDatagramToOutput(), inet::NetworkProtocolBase::sendDown(), inet::RelayInterfaceSelector::sendPacket(), and inet::MacRelayUnitBase::sendPacket().
getProtocolData() [1/2]
template<typename T > const T* inet::NetworkInterface::getProtocolData () const inline
Returns the protocol data for the provided type or throws an exception if no such protocol data is found.
{
         return protocolDataSet.getTag<T>();
     }
getProtocolData() [2/2]
const InterfaceProtocolData* inet::NetworkInterface::getProtocolData (int index) const inline
Returns the protocol data at the given index.
{
         return static_cast<const InterfaceProtocolData *>(protocolDataSet.getTag(index));
     }
Referenced by inet::Ipv6FlatNetworkConfigurator::addOwnAdvPrefixRoutes(), inet::Ipv6FlatNetworkConfigurator::addStaticRoutes(), inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::Ipv6NeighbourDiscovery::assignLinkLocalAddress(), inet::xMIPv6::cancelEntries(), inet::DhcpClient::chooseInterface(), inet::NextHopRoutingTable::configureRouterId(), inet::xMIPv6::createAndSendBRRMessage(), inet::xMIPv6::createAndSendBUMessage(), inet::Ipv6NeighbourDiscovery::createAndSendRaPacket(), inet::Ipv6NeighbourDiscovery::createAndSendRsPacket(), inet::xMIPv6::createBUTimer(), inet::xMIPv6::createDeregisterBUTimer(), inet::bgp::BgpRouter::createEbgpSession(), inet::Ipv6NeighbourDiscovery::createRaTimer(), inet::xMIPv6::createTestInitTimer(), inet::Ipv6Tunneling::decapsulateDatagram(), inet::ospfv3::Ospfv3Interface::detailedInfo(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::RsvpTe::evalNextHopInterface(), inet::Ipv4RoutingTable::findInterfaceByLocalBroadcastAddress(), inet::bgp::BgpConfigReader::findMyAS(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv6::fragmentAndSend(), inet::Ipv6::fragmentPostRouting(), inet::Ipv4::fragmentPostRouting(), inet::StpBase::getPortInterfaceData(), inet::xMIPv6::handleBULExpiry(), inet::Dsdv::handleMessageWhenUp(), inet::Dsdv::handleSelfMessage(), inet::DhcpServer::handleStartOperation(), inet::xMIPv6::handleTokenExpiry(), inet::PimSm::IamDR(), inet::Ipv6RoutingTable::initialize(), inet::Ipv6NeighbourDiscovery::initialize(), inet::Ted::initializeTED(), inet::Ipv6NeighbourDiscovery::initiateAddressResolution(), inet::Ipv6NeighbourDiscovery::initiateDad(), inet::xMIPv6::initiateMipv6Protocol(), inet::Ipv6NeighbourDiscovery::initiateNeighbourUnreachabilityDetection(), inet::Ipv6NeighbourDiscovery::initiateRouterDiscovery(), inet::BindingUpdateList::isCareOfTokenAvailable(), inet::eigrp::EigrpDeviceConfigurator::isEigrpInterface(), inet::BindingUpdateList::isHomeTokenAvailable(), inet::bgp::BgpConfigReader::isInInterfaceTable(), inet::ospfv3::Ospfv3Process::isInInterfaceTable6(), inet::Ipv6RoutingTable::isLocalAddress(), inet::Ipv4RoutingTable::isLocalBroadcastAddress(), inet::Ipv4RoutingTable::isLocalMulticastAddress(), inet::bgp::BgpRouter::listenConnectionFromPeer(), inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent(), inet::bgp::BgpRouter::openTCPConnectionToPeer(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::Ospfv3Interface(), inet::Ipv4::preroutingFinish(), inet::Ipv4RoutingTable::printRoutingTable(), inet::Arp::processArpPacket(), inet::Ipv6NeighbourDiscovery::processArTimeout(), inet::PimDm::processAssert(), inet::xMIPv6::processCoTMessage(), inet::Ipv6NeighbourDiscovery::processDadTimeout(), inet::DhcpServer::processDhcpMessage(), inet::PimDm::processGraftPacket(), inet::xMIPv6::processHoTMessage(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::Ipv6NeighbourDiscovery::processNaForIncompleteNceState(), inet::Ipv6NeighbourDiscovery::processNaForOtherNceStates(), inet::Ipv6NeighbourDiscovery::processNaPacket(), inet::Ipv6NeighbourDiscovery::processNsPacket(), inet::Ipv6NeighbourDiscovery::processNudTimeout(), inet::PimSm::processPruneG(), inet::PimSm::processPruneSG(), inet::Igmpv3::processQuery(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf(), inet::Ipv6NeighbourDiscovery::processRdTimeout(), inet::Ipv6NeighbourDiscovery::processRsPacket(), inet::GlobalArp::receiveSignal(), inet::BindingUpdateList::recentlySentCOTI(), inet::BindingUpdateList::recentlySentHOTI(), inet::xMIPv6::resetBUIfEntry(), inet::Ipv4::resolveNextHopMacAddress(), inet::xMIPv6::returningHome(), inet::Ipv4::routeLocalBroadcastPacket(), inet::NextHopForwarding::routePacket(), inet::DhcpServer::sendAck(), inet::Arp::sendArpRequest(), inet::DhcpServer::sendNak(), inet::DhcpServer::sendOffer(), inet::ospfv3::Ospfv3Process::sendPacket(), inet::xMIPv6::sendPeriodicBU(), inet::Ipv6NeighbourDiscovery::sendPeriodicRa(), inet::Ipv6NeighbourDiscovery::sendSolicitedNa(), inet::xMIPv6::sendTestInit(), inet::Ipv6NeighbourDiscovery::sendUnsolicitedNa(), inet::ospfv2::Ospfv2Interface::setIfIndex(), inet::xMIPv6::triggerRouteOptimization(), inet::PimDm::unroutableMulticastPacketArrived(), inet::PimSm::updateDesignatedRouterAddress(), inet::bgp::BgpRouter::updateSendProcess(), and inet::xMIPv6::validateCoTMessage().
getProtocolDataForUpdate()
template<typename T > T* inet::NetworkInterface::getProtocolDataForUpdate () inline
Returns the protocol data for the provided type or throws an exception if no such protocol data is found.
{
         return protocolDataSet.getTagForUpdate<T>();
     }
Referenced by inet::Udp::addMulticastAddressToInterface(), inet::Ipv4FlatNetworkConfigurator::assignAddresses(), inet::Ipv6NeighbourDiscovery::assignLinkLocalAddress(), inet::Ipv6RoutingTable::assignRequiredNodeAddresses(), inet::DhcpClient::bindLease(), inet::ospfv3::Ospfv3InterfaceState::changeState(), inet::L2NetworkConfigurator::configureInterface(), inet::Ipv4NetworkConfigurator::configureInterface(), inet::Ipv6RoutingTable::configureInterfaceFromXml(), inet::Ipv4RoutingTable::configureRouterId(), inet::Ipv6NeighbourDiscovery::createRaTimer(), inet::eigrp::EigrpIpv4Pdm::disableInterface(), inet::eigrp::EigrpIpv6Pdm::disableInterface(), inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::StpBase::getPortInterfaceDataForUpdate(), inet::PimBase::handleStartOperation(), inet::Igmpv3::initialize(), inet::Ipv6NeighbourDiscovery::initiateDad(), inet::ospfv2::Ospfv2ConfigReader::joinMulticastGroups(), inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent(), inet::ospfv3::Ospfv3Splitter::parseConfig(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::RoutingTableParser::parseInterfaces(), inet::RoutingTableParser::parseMulticastGroups(), inet::Icmpv6::processEchoRequest(), inet::Igmpv2::processLeaveTimer(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Ipv6NeighbourDiscovery::processRaPrefixInfoForAddrAutoConf(), inet::Igmpv3::processReport(), inet::Igmpv3::processRouterGroupTimer(), inet::Igmpv3::processRouterSourceTimer(), inet::Igmpv2::processV2Report(), inet::eigrp::EigrpIpv4Pdm::setPassive(), inet::eigrp::EigrpIpv6Pdm::setPassive(), inet::HostAutoConfigurator::setupNetworkLayer(), inet::Dsdv::start(), and inet::DhcpClient::unbindLease().
getRxTransmissionChannel()
cChannel* inet::NetworkInterface::getRxTransmissionChannel () inline
 { return rxTransmissionChannel; }
getState()
State inet::NetworkInterface::getState () const inline
Returns the requested state of this interface.
 { return state; }
getTxTransmissionChannel()
cChannel* inet::NetworkInterface::getTxTransmissionChannel () inline
 { return txTransmissionChannel; }
handleCrashOperation()
void inet::NetworkInterface::handleCrashOperation (LifecycleOperation * operation) virtual
 {
     setState(State::DOWN);
     // TODO carrier and UP/DOWN state is independent
     setCarrier(false);
 }
Referenced by handleOperationStage().
handleOperationStage()
bool inet::NetworkInterface::handleOperationStage (LifecycleOperation * operation, IDoneCallback * doneCallback) override virtual
Perform one stage of a lifecycle operation.
Processing may be done entirely within this method, or may be a longer process that involves nonzero simulation time or several events, and is triggered by this method call.
Return value: true = "done"; false = "not yet done, will invoke doneCallback when done"
Implements inet::ILifecycle.
 {
     Enter_Method("handleOperationStage");
     int stage = operation->getCurrentStage();
     if (dynamic_cast<ModuleStartOperation *>(operation)) {
         if (stage == ModuleStartOperation::STAGE_LINK_LAYER) {
             handleStartOperation(operation);
             return true;
         }
     }
     else if (dynamic_cast<ModuleStopOperation *>(operation)) {
         if (stage == ModuleStopOperation::STAGE_LINK_LAYER) {
             handleStopOperation(operation);
             return true;
         }
     }
     else if (dynamic_cast<ModuleCrashOperation *>(operation)) {
         if (stage == ModuleCrashOperation::STAGE_CRASH) {
             handleCrashOperation(operation);
             return true;
         }
     }
     else
         throw cRuntimeError("unaccepted Lifecycle operation: (%s)%s", operation->getClassName(), operation->getName());
     return true;
 }
handleParameterChange()
void inet::NetworkInterface::handleParameterChange (const char * name) override protected virtual
 {
     if (name != nullptr && !strcmp(name, "bitrate"))
         setDatarate(computeDatarate());
 }
handleStartOperation()
void inet::NetworkInterface::handleStartOperation (LifecycleOperation * operation) virtual
 {
     setState(State::UP);
     // TODO carrier and UP/DOWN state is independent
     setCarrier(true);
 }
Referenced by handleOperationStage().
handleStopOperation()
void inet::NetworkInterface::handleStopOperation (LifecycleOperation * operation) virtual
 {
     setState(State::DOWN);
     // TODO carrier and UP/DOWN state is independent
     setCarrier(false);
 }
Referenced by handleOperationStage().
hasCarrier()
bool inet::NetworkInterface::hasCarrier () const inline
 { return carrier; }
Referenced by inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), pushPacket(), pushPacketEnd(), pushPacketStart(), inet::Rstp::receiveSignal(), and str().
hasNetworkAddress()
bool inet::NetworkInterface::hasNetworkAddress (const L3Address & address) const virtual
 {
     switch(address.getType()) {
     case L3Address::NONE:
         return false;
     case L3Address::IPv4: {
 #ifdef INET_WITH_IPv4
         auto ipv4data = findProtocolData<Ipv4InterfaceData>();
         return ipv4data != nullptr && ipv4data->getIPAddress() == address.toIpv4();
 #else
         return false;
 #endif // ifdef INET_WITH_IPv4
     }
     case L3Address::IPv6: {
 #ifdef INET_WITH_IPv6
         auto ipv6data = findProtocolData<Ipv6InterfaceData>();
         return ipv6data != nullptr && ipv6data->hasAddress(address.toIpv6());
 #else
         return false;
 #endif // ifdef INET_WITH_IPv6
     }
     case L3Address::MAC: {
         return getMacAddress() == address.toMac();
     }
     case L3Address::MODULEID: {
 #ifdef INET_WITH_NEXTHOP
         auto nextHopData = findProtocolData<NextHopInterfaceData>();
         if (nextHopData != nullptr && nextHopData->getAddress() == address)
             return true;
 #endif // ifdef INET_WITH_NEXTHOP
         if (hasModuleIdAddress)
             return getModuleIdAddress() == address.toModuleId();
         return false;
     }
     case L3Address::MODULEPATH: {
 #ifdef INET_WITH_NEXTHOP
         auto nextHopData = findProtocolData<NextHopInterfaceData>();
         if (nextHopData != nullptr && nextHopData->getAddress() == address)
             return true;
 #endif // ifdef INET_WITH_NEXTHOP
         if (hasModulePathAddress)
             return getModulePathAddress() == address.toModulePath();
         return false;
     }
     default:
         break;
     }
     return false;
 }
initialize()
void inet::NetworkInterface::initialize (int stage) override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
Reimplemented in inet::ExtInterface, and inet::EthernetCutthroughInterface.
 {
     if (stage == INITSTAGE_LOCAL) {
         upperLayerIn = gate("upperLayerIn");
         upperLayerOut = gate("upperLayerOut");
         subscribe(POST_MODEL_CHANGE, this);
         if (hasGate("phys$i")) {
             rxIn = gate("phys$i")->getPathEndGate();
             rxTransmissionChannel = rxIn->findIncomingTransmissionChannel();
             if (rxTransmissionChannel != nullptr)
                 rxTransmissionChannel->subscribe(POST_MODEL_CHANGE, this);
         }
         if (hasGate("phys$o")) {
             txOut = gate("phys$o")->getPathStartGate();
             txTransmissionChannel = txOut->findTransmissionChannel();
             if (txTransmissionChannel != nullptr)
                 txTransmissionChannel->subscribe(POST_MODEL_CHANGE, this);
         }
         upperLayerInConsumer = findConnectedModule<IPassivePacketSink>(upperLayerIn, 1);
         upperLayerOutConsumer = findConnectedModule<IPassivePacketSink>(upperLayerOut, 1);
         interfaceTable.reference(this, "interfaceTableModule", false);
         setInterfaceName(utils::stripnonalnum(getFullName()).c_str());
         setCarrier(computeCarrier());
         setDatarate(computeDatarate());
         WATCH(mtu);
         WATCH(state);
         WATCH(carrier);
         WATCH(broadcast);
         WATCH(multicast);
         WATCH(pointToPoint);
         WATCH(loopback);
         WATCH(datarate);
         WATCH(macAddr);
         cModule *node = findContainingNode(this);
         NodeStatus *nodeStatus = node ? check_and_cast_nullable<NodeStatus *>(node->getSubmodule("status")) : nullptr;
         if (!nodeStatus || nodeStatus->getState() == NodeStatus::UP) {
             state = UP;
             carrier = true;
         }
     }
     else if (stage == INITSTAGE_NETWORK_INTERFACE_CONFIGURATION) {
         if (hasPar("protocol")) {
             const char *protocolName = par("protocol");
             if (*protocolName != '\0')
                 protocol = Protocol::getProtocol(protocolName);
         }
         if (hasPar("address")) {
             const char *address = par("address");
             if (!strcmp(address, "auto")) {
                 setMacAddress(MacAddress::generateAutoAddress());
                 par("address").setStringValue(getMacAddress().str());
             }
             else
                 setMacAddress(MacAddress(address));
             setInterfaceToken(macAddr.formInterfaceIdentifier());
         }
         if (hasPar("broadcast"))
             setBroadcast(par("broadcast"));
         if (hasPar("multicast"))
             setMulticast(par("multicast"));
         if (hasPar("mtu"))
             setMtu(par("mtu"));
         if (hasPar("pointToPoint"))
             setPointToPoint(par("pointToPoint"));
         if (interfaceTable)
             interfaceTable->addInterface(this);
         inet::registerInterface(*this, gate("upperLayerIn"), gate("upperLayerOut"));
     }
     else if (stage == INITSTAGE_LAST)
         layoutSubmodulesWithoutGates(this);
 }
Referenced by inet::EthernetCutthroughInterface::initialize().
isBroadcast()
bool inet::NetworkInterface::isBroadcast () const inline
 { return broadcast; }
Referenced by inet::Ipv4RoutingTable::findInterfaceByLocalBroadcastAddress(), inet::VirtualTunnel::initialize(), inet::RelayInterfaceSelector::isForwardingInterface(), inet::MacRelayUnitBase::isForwardingInterface(), inet::Ipv4RoutingTable::isLocalBroadcastAddress(), inet::Ipv4::routeUnicastPacket(), inet::NextHopForwarding::sendDatagramToOutput(), inet::Ipv4::sendDatagramToOutput(), and str().
isDown()
bool inet::NetworkInterface::isDown () const inline
 { return getState() != UP; }
Referenced by inet::NetworkInterface::LocalGate::deliver(), pushPacket(), pushPacketEnd(), and pushPacketStart().
isLoopback()
bool inet::NetworkInterface::isLoopback () const inline
 { return loopback; }
Referenced by inet::Ipv4FlatNetworkConfigurator::addDefaultRoutes(), inet::Ipv6FlatNetworkConfigurator::addOwnAdvPrefixRoutes(), inet::Ipv6FlatNetworkConfigurator::addStaticRoutes(), inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Ipv4FlatNetworkConfigurator::assignAddresses(), inet::Ipv6NeighbourDiscovery::assignLinkLocalAddress(), inet::Ipv6RoutingTable::assignRequiredNodeAddresses(), inet::StpBase::chooseInterface(), inet::DhcpServer::chooseInterface(), inet::DhcpClient::chooseInterface(), inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes(), inet::Ipv6RoutingTable::configureInterfaceForIpv6(), inet::PimInterfaceTable::configureInterfaces(), inet::NextHopRoutingTable::configureRouterId(), inet::Ipv4RoutingTable::configureRouterId(), inet::Ipv4::datagramLocalOut(), inet::L3NetworkConfiguratorBase::determineGatewayForLink(), inet::L3NetworkConfiguratorBase::extractDeviceNeighbors(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::extractWirelessNeighbors(), inet::PingApp::getAllAddresses(), inet::L3AddressResolver::getIpv4AddressFrom(), inet::L3AddressResolver::getIpv6AddressFrom(), inet::L3AddressResolver::getMacAddressFrom(), inet::L3AddressResolver::getModuleIdAddressFrom(), inet::L3AddressResolver::getModulePathAddressFrom(), inet::Gpsr::getSelfAddress(), inet::GlobalArp::initialize(), inet::Ipv6RoutingTable::initialize(), inet::Ipv6NeighbourDiscovery::initialize(), inet::Ted::initializeTED(), inet::xMIPv6::initiateMipv6Protocol(), inet::ospfv2::Router::isDirectRoute(), inet::RelayInterfaceSelector::isForwardingInterface(), inet::MacRelayUnitBase::isForwardingInterface(), inet::Rip::isLocalInterfaceRoute(), inet::Rip::isLoopbackInterfaceRoute(), inet::bgp::BgpRouter::isRouteExcluded(), inet::ospfv2::Ospfv2ConfigReader::loadConfigFromXML(), inet::Ipv6NeighbourDiscovery::makeTentativeAddressPermanent(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::Ipv4NodeConfigurator::prepareInterface(), inet::Ipv4::preroutingFinish(), inet::ospfv2::Ospfv2::receiveSignal(), inet::GlobalArp::receiveSignal(), inet::PimInterfaceTable::receiveSignal(), inet::Rip::receiveSignal(), inet::RipNetworkInterface::RipNetworkInterface(), inet::NextHopForwarding::routeMulticastPacket(), inet::Ipv6::routeMulticastPacket(), inet::NetworkProtocolBase::sendDown(), inet::HostAutoConfigurator::setupNetworkLayer(), inet::Rip::startRIPRouting(), and str().
isMulticast()
bool inet::NetworkInterface::isMulticast () const inline
 { return multicast; }
Referenced by inet::Udp::addMulticastAddressToInterface(), inet::Udp::blockMulticastSources(), inet::Ipv6RoutingTable::configureInterfaceForIpv6(), inet::PimInterfaceTable::configureInterfaces(), inet::Gpsr::configureInterfaces(), inet::dymo::Dymo::configureInterfaces(), inet::eigrp::EigrpInterface::EigrpInterface(), inet::VirtualTunnel::initialize(), inet::Ldp::initialize(), inet::Igmpv2::initialize(), inet::Igmpv3::initialize(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), inet::eigrp::EigrpInterface::isMulticastAllowedOnIface(), inet::ospfv2::Ospfv2ConfigReader::joinMulticastGroups(), inet::Udp::joinMulticastGroups(), inet::Udp::joinMulticastSources(), inet::Udp::leaveMulticastGroups(), inet::Udp::leaveMulticastSources(), inet::Igmpv2::multicastGroupJoined(), inet::Igmpv2::multicastGroupLeft(), inet::Ipv4NodeConfigurator::prepareInterface(), inet::Igmpv2::processLeave(), inet::Igmpv2::processQuery(), inet::Igmpv3::processQuery(), inet::Igmpv3::processReport(), inet::Igmpv2::processV2Report(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::ospfv2::Ospfv2::receiveSignal(), inet::PimInterfaceTable::receiveSignal(), inet::Rip::receiveSignal(), inet::Igmpv2::receiveSignal(), inet::Igmpv3::receiveSignal(), inet::RipNetworkInterface::RipNetworkInterface(), inet::Igmpv3::sendQueryToIP(), inet::Igmpv3::sendReportToIP(), inet::Igmpv2::sendToIP(), inet::Udp::setMulticastSourceFilter(), inet::Rip::startRIPRouting(), str(), and inet::Udp::unblockMulticastSources().
isPointToPoint()
bool inet::NetworkInterface::isPointToPoint () const inline
 { return pointToPoint; }
Referenced by inet::VirtualTunnel::initialize(), inet::Ipv6NeighbourDiscovery::processIpv6Datagram(), and str().
isUp()
bool inet::NetworkInterface::isUp () const inline
Returns the combined state of the carrier and the interface requested state.
 { return getState() == UP && hasCarrier(); }
Referenced by inet::eigrp::EigrpIpv4Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::ospfv2::Ospfv2::receiveSignal(), inet::Rip::receiveSignal(), inet::Ipv6RoutingTable::receiveSignal(), inet::PimDm::rpfInterfaceHasChanged(), and inet::Ipv4RoutingTable::updateNetmaskRoutes().
isWired()
bool inet::NetworkInterface::isWired () const inline
 { return rxIn != nullptr && txOut != nullptr; }
isWireless()
bool inet::NetworkInterface::isWireless () const inline
 { return !isWired(); }
Referenced by computeCarrier().
joinMulticastGroup()
void inet::NetworkInterface::joinMulticastGroup (const L3Address & address) virtual
 {
     switch (address.getType()) {
 #ifdef INET_WITH_IPv4
         case L3Address::IPv4:
             getProtocolDataForUpdate<Ipv4InterfaceData>()->joinMulticastGroup(address.toIpv4());
             break;
 #endif // ifdef INET_WITH_IPv4
 #ifdef INET_WITH_IPv6
         case L3Address::IPv6:
             getProtocolDataForUpdate<Ipv6InterfaceData>()->joinMulticastGroup(address.toIpv6());
             break;
 #endif // ifdef INET_WITH_IPv6
 #ifdef INET_WITH_NEXTHOP
         case L3Address::MAC:
         case L3Address::MODULEID:
         case L3Address::MODULEPATH:
             getProtocolDataForUpdate<NextHopInterfaceData>()->joinMulticastGroup(address);
             break;
 #endif // ifdef INET_WITH_NEXTHOP
         default:
             throw cRuntimeError("Unknown address type");
     }
 }
Referenced by inet::Udp::addMulticastAddressToInterface(), inet::Gpsr::configureInterfaces(), and inet::dymo::Dymo::configureInterfaces().
matchesMacAddress()
bool inet::NetworkInterface::matchesMacAddress (const MacAddress & address) const
 {
     return address.isBroadcast()
             || (address.isMulticast() && matchesMulticastMacAddress(address))
             || macAddr == address;
 }
matchesMulticastMacAddress()
bool inet::NetworkInterface::matchesMulticastMacAddress (const MacAddress & address) const
 {
     return address.isMulticast() && contains(multicastAddresses, address);
 }
Referenced by matchesMacAddress().
numInitStages()
virtual int inet::NetworkInterface::numInitStages () const inline override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
Reimplemented in inet::ExtInterface.
 { return NUM_INIT_STAGES; }
operator=()
NetworkInterface& inet::NetworkInterface::operator= (const NetworkInterface & obj) private
pushPacket()
void inet::NetworkInterface::pushPacket (Packet * packet, cGate * gate) override virtual
Pushes the packet into the packet sink at the given gate.
This operation pushes the packet as a whole. The onwership of the packet is transferred to the sink.
This method is called, for example, when a packet source module pushes a packet into a queue module.
The sink must not be full at the gate. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and passing packets.
Implements inet::queueing::IPassivePacketSink.
 {
     Enter_Method("pushPacket");
     take(packet);
     if (gate == upperLayerIn) {
         if (isDown()) {
             EV_WARN << "Network interface is down, dropping packet" << EV_FIELD(packet) << EV_ENDL;
             dropPacket(packet, INTERFACE_DOWN);
         }
         else if (!hasCarrier()) {
             EV_WARN << "Network interface has no carrier, dropping packet" << EV_FIELD(packet) << EV_ENDL;
             dropPacket(packet, NO_CARRIER);
         }
         else
             pushOrSendPacket(packet, upperLayerIn, upperLayerInConsumer);
     }
     else if (gate == upperLayerOut) {
         packet->addTagIfAbsent<InterfaceInd>()->setInterfaceId(interfaceId);
         pushOrSendPacket(packet, upperLayerOut, upperLayerOutConsumer);
     }
     else
         throw cRuntimeError("Unknown gate: %s", gate->getName());
 }
pushPacketEnd()
void inet::NetworkInterface::pushPacketEnd (Packet * packet, cGate * gate) override virtual
Ends pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module ends streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::EthernetCutthroughInterface.
 {
     Enter_Method("pushPacketEnd");
     take(packet);
     if (gate == upperLayerIn) {
         if (isDown()) {
             EV_WARN << "Network interface is down, dropping packet" << EV_FIELD(packet) << EV_ENDL;
             dropPacket(packet, INTERFACE_DOWN);
         }
         else if (!hasCarrier()) {
             EV_WARN << "Network interface has no carrier, dropping packet" << EV_FIELD(packet) << EV_ENDL;
             dropPacket(packet, NO_CARRIER);
         }
         else
             pushOrSendPacketEnd(packet, upperLayerIn, upperLayerInConsumer, packet->getTransmissionId());
     }
     else if (gate == upperLayerOut) {
         packet->addTagIfAbsent<InterfaceInd>()->setInterfaceId(interfaceId);
         pushOrSendPacketEnd(packet, upperLayerOut, upperLayerOutConsumer, packet->getTransmissionId());
     }
     else
         throw cRuntimeError("Unknown gate: %s", gate->getName());
 }
Referenced by inet::EthernetCutthroughInterface::pushPacketEnd().
pushPacketProgress()
virtual void inet::NetworkInterface::pushPacketProgress (Packet * packet, cGate * gate, bps datarate, b position, b extraProcessableLength = b(0)) inline override virtual
Progresses pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The position specifies where the packet streaming is at the moment. The extra length parameter partially fixes the future of the packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, to notify the sink about a change in the packet data when a preemption occurs.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
 { throw cRuntimeError("Invalid operation"); }
pushPacketStart()
void inet::NetworkInterface::pushPacketStart (Packet * packet, cGate * gate, bps datarate) override virtual
Starts pushing the packet into the packet sink at the given gate.
This is a packet streaming operation. The onwership of the packet is transferred to the sink.
Packet streaming can be started with any of the streaming operations, and ends when the streaming position plus the extra processable packet length equals to the total packet length.
This method is called, for example, when a preemption supporting server module starts streaming a packet to the sink.
The sink must not be full at the gate and no other packet streaming can be in progress. The packet must not be nullptr. The gate must be a valid gate of this module and it must support pushing and streaming packets.
Implements inet::queueing::IPassivePacketSink.
Reimplemented in inet::EthernetCutthroughInterface.
 {
     Enter_Method("pushPacket");
     take(packet);
     if (gate == upperLayerIn) {
         if (isDown()) {
             EV_WARN << "Network interface is down, dropping packet" << EV_FIELD(packet) << EV_ENDL;
             dropPacket(packet, INTERFACE_DOWN);
         }
         else if (!hasCarrier()) {
             EV_WARN << "Network interface has no carrier, dropping packet" << EV_FIELD(packet) << EV_ENDL;
             dropPacket(packet, NO_CARRIER);
         }
         else
             pushOrSendPacketStart(packet, upperLayerIn, upperLayerInConsumer, datarate, packet->getTransmissionId());
     }
     else if (gate == upperLayerOut) {
         packet->addTagIfAbsent<InterfaceInd>()->setInterfaceId(interfaceId);
         pushOrSendPacketStart(packet, upperLayerOut, upperLayerOutConsumer, datarate, packet->getTransmissionId());
     }
     else
         throw cRuntimeError("Unknown gate: %s", gate->getName());
 }
Referenced by inet::EthernetCutthroughInterface::pushPacketStart().
receiveSignal()
void inet::NetworkInterface::receiveSignal (cComponent * source, simsignal_t signal, cObject * obj, cObject * details) override protected virtual
 {
     Enter_Method("%s", cComponent::getSignalName(signal));
     if (signal == POST_MODEL_CHANGE) {
         if (auto notification = dynamic_cast<cPostPathCreateNotification *>(obj)) {
             if (rxIn == notification->pathEndGate || txOut == notification->pathStartGate) {
                 rxTransmissionChannel = rxIn->findIncomingTransmissionChannel();
                 txTransmissionChannel = txOut->findTransmissionChannel();
                 if (rxTransmissionChannel != nullptr && !rxTransmissionChannel->isSubscribed(POST_MODEL_CHANGE, this))
                     rxTransmissionChannel->subscribe(POST_MODEL_CHANGE, this);
                 if (txTransmissionChannel != nullptr && !txTransmissionChannel->isSubscribed(POST_MODEL_CHANGE, this))
                     txTransmissionChannel->subscribe(POST_MODEL_CHANGE, this);
                 setCarrier(computeCarrier());
             }
         }
         else if (auto notification = dynamic_cast<cPostPathCutNotification *>(obj)) {
             if (rxIn == notification->pathEndGate || txOut == notification->pathStartGate) {
                 rxTransmissionChannel = nullptr;
                 txTransmissionChannel = nullptr;
                 setCarrier(computeCarrier());
             }
         }
         else if (auto notification = dynamic_cast<cPostParameterChangeNotification *>(obj)) {
             auto owner = notification->par->getOwner();
             if (owner == rxTransmissionChannel || owner == txTransmissionChannel) {
                 setCarrier(computeCarrier());
                 setDatarate(computeDatarate());
             }
         }
     }
 }
refreshDisplay()
void inet::NetworkInterface::refreshDisplay () const override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     updateDisplayString();
 }
removeMulticastMacAddress()
void inet::NetworkInterface::removeMulticastMacAddress (const MacAddress & address)
 {
     auto it = find(multicastAddresses, address);
     if (it == multicastAddresses.end())
         throw cRuntimeError("Multicast MacAddress not found: '%s'", address.str().c_str());
     multicastAddresses.erase(it);
 }
removeProtocolData()
template<typename T > T* inet::NetworkInterface::removeProtocolData () inline
Removes the protocol data for the provided type, or throws an exception if no such protocol data is found.
{
         auto t = protocolDataSet.removeTag<T>();
         check_and_cast<InterfaceProtocolData *>(t)->ownerp = nullptr;
         changed(interfaceConfigChangedSignal, t->id);
         return t;
     }
removeProtocolDataIfPresent()
template<typename T > T* inet::NetworkInterface::removeProtocolDataIfPresent () inline
Removes the protocol data for the provided type if present, or returns nullptr if no such protocol data is found.
{
         auto t = protocolDataSet.removeTagIfPresent<T>();
         if (t != nullptr) {
             check_and_cast<InterfaceProtocolData *>(t)->ownerp = nullptr;
             changed(interfaceConfigChangedSignal, t->id);
         }
         return t;
     }
resetInterface()
void inet::NetworkInterface::resetInterface () virtual
 {
     protocolDataSet.clearTags();
 }
Referenced by ~NetworkInterface().
resolveDirective()
const char * inet::NetworkInterface::resolveDirective (char directive) const override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     static std::string result;
     switch (directive) {
         case 'i':
             result = std::to_string(interfaceId);
             break;
         case 'm':
             result = macAddr.str();
             break;
         case 'n':
             result = interfaceName;
             break;
         case 'a':
             result = getNetworkAddress().str();
             break;
         default:
             throw cRuntimeError("Unknown directive: %c", directive);
     }
     return result.c_str();
 }
setBroadcast()
virtual void inet::NetworkInterface::setBroadcast (bool b) inline virtual
 { if (broadcast != b) { broadcast = b; configChanged(F_BROADCAST); } }
Referenced by inet::VirtualTunnel::initialize(), initialize(), inet::RoutingTableParser::parseInterfaces(), and inet::HostAutoConfigurator::setupNetworkLayer().
setCarrier()
void inet::NetworkInterface::setCarrier (bool b) virtual
 {
     if (carrier != b) {
         carrier = b;
         stateChanged(F_CARRIER);
     }
 }
Referenced by handleCrashOperation(), handleStartOperation(), handleStopOperation(), initialize(), receiveSignal(), and setState().
setDatarate()
virtual void inet::NetworkInterface::setDatarate (double d) inline virtual
 { if (datarate != d) { datarate = d; configChanged(F_DATARATE); } }
Referenced by handleParameterChange(), initialize(), and receiveSignal().
setEstimateCostProcess()
bool inet::NetworkInterface::setEstimateCostProcess (int position, MacEstimateCostProcess * p) virtual
 {
     ASSERT(position >= 0);
     if (estimateCostProcessArray.size() <= (size_t)position) {
         estimateCostProcessArray.resize(position + 1, nullptr);
     }
     if (estimateCostProcessArray[position] != nullptr)
         return false;
     estimateCostProcessArray[position] = p;
     return true;
 }
setHasModuleIdAddress()
void inet::NetworkInterface::setHasModuleIdAddress (bool value) inline
 { hasModuleIdAddress = value; }
setHasModulePathAddress()
void inet::NetworkInterface::setHasModulePathAddress (bool value) inline
 { hasModulePathAddress = value; }
setInterfaceId()
virtual void inet::NetworkInterface::setInterfaceId (int id) inline virtual
 { interfaceId = id; }
Referenced by inet::InterfaceTable::addInterface(), arrived(), pushPacket(), inet::EthernetCutthroughInterface::pushPacketEnd(), pushPacketEnd(), inet::EthernetCutthroughInterface::pushPacketStart(), and pushPacketStart().
setInterfaceName()
virtual void inet::NetworkInterface::setInterfaceName (const char * s) inline virtual
 { interfaceName = s; configChanged(F_NAME); }
Referenced by initialize().
setInterfaceToken()
virtual void inet::NetworkInterface::setInterfaceToken (const InterfaceToken & t) inline virtual
 { token = t; configChanged(F_TOKEN); }
Referenced by inet::VirtualTunnel::initialize(), and initialize().
setLoopback()
virtual void inet::NetworkInterface::setLoopback (bool b) inline virtual
 { if (loopback != b) { loopback = b; configChanged(F_LOOPBACK); } }
setMacAddress()
virtual void inet::NetworkInterface::setMacAddress (const MacAddress & addr) inline virtual
 { if (macAddr != addr) { macAddr = addr; configChanged(F_MACADDRESS); } }
Referenced by inet::ReceiveAtMacAddress::initialize(), inet::VirtualTunnel::initialize(), and initialize().
setMtu()
virtual void inet::NetworkInterface::setMtu (int m) inline virtual
 { if (mtu != m) { mtu = m; configChanged(F_MTU); } }
Referenced by inet::Ipv4NetworkConfigurator::configureInterface(), initialize(), and inet::RoutingTableParser::parseInterfaces().
setMulticast()
virtual void inet::NetworkInterface::setMulticast (bool b) inline virtual
 { if (multicast != b) { multicast = b; configChanged(F_MULTICAST); } }
Referenced by inet::VirtualTunnel::initialize(), initialize(), and inet::RoutingTableParser::parseInterfaces().
setNodeInputGateId()
virtual void inet::NetworkInterface::setNodeInputGateId (int i) inline virtual
 { if (nodeInputGateId != i) { nodeInputGateId = i; configChanged(F_NODE_IN_GATEID); } }
Referenced by inet::InterfaceTable::discoverConnectingGates().
setNodeOutputGateId()
virtual void inet::NetworkInterface::setNodeOutputGateId (int i) inline virtual
 { if (nodeOutputGateId != i) { nodeOutputGateId = i; configChanged(F_NODE_OUT_GATEID); } }
Referenced by inet::InterfaceTable::discoverConnectingGates().
setPointToPoint()
virtual void inet::NetworkInterface::setPointToPoint (bool b) inline virtual
 { if (pointToPoint != b) { pointToPoint = b; configChanged(F_POINTTOPOINT); } }
Referenced by inet::VirtualTunnel::initialize(), initialize(), and inet::RoutingTableParser::parseInterfaces().
setProtocol()
virtual void inet::NetworkInterface::setProtocol (const Protocol * protocol) inline virtual
 { this->protocol = protocol; }
setState()
void inet::NetworkInterface::setState (State s) virtual
 {
     if (state != s) {
         state = s;
         // TODO carrier and UP/DOWN state is independent
         if (state == DOWN)
             setCarrier(false);
         stateChanged(F_STATE);
     }
 }
Referenced by handleCrashOperation(), handleStartOperation(), and handleStopOperation().
stateChanged()
virtual void inet::NetworkInterface::stateChanged (int fieldId) inline protected virtual
 { changed(interfaceStateChangedSignal, fieldId); }
Referenced by setCarrier(), and setState().
str()
std::string inet::NetworkInterface::str () const override virtual
 {
     std::stringstream out;
     out << getInterfaceName();
     out << " ID:" << getInterfaceId();
     out << " MTU:" << getMtu();
     out << ((state == DOWN) ? " DOWN" : " UP");
     if (isLoopback())
         out << " LOOPBACK";
     if (isBroadcast())
         out << " BROADCAST";
     out << (hasCarrier() ? " CARRIER" : " NOCARRIER");
     if (isMulticast())
         out << " MULTICAST";
     if (isPointToPoint())
         out << " POINTTOPOINT";
     out << " macAddr:";
     if (getMacAddress().isUnspecified())
         out << "n/a";
     else
         out << getMacAddress();
     for (int i = 0; i < protocolDataSet.getNumTags(); i++)
         out << " " << protocolDataSet.getTag(i)->str();
     return out.str();
 }
Referenced by inet::Ipv4NetworkConfigurator::dumpAddresses(), inet::MessageDispatcher::handleRegisterInterface(), initialize(), and inet::NetworkInterfaceChangeDetails::str().
supportsPacketPassing()
virtual bool inet::NetworkInterface::supportsPacketPassing (cGate * gate) const inline override virtual
Returns true if the processor supports passing packets as a whole at the given gate.
A passed packet is handed over from one module to another by either the standard OMNeT++ handleMessage() mechanism, or by directly calling pushPacket() or pullPacket().
For example, packets are passed as a whole to and from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pass) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return true; }
supportsPacketPulling()
virtual bool inet::NetworkInterface::supportsPacketPulling (cGate * gate) const inline override virtual
Returns true if the processor supports pulling packets at the given gate.
Pulling a packet is a synchronous operation that is initiated by the sink module. A pulled packet can be passed as a whole using pullPacket(), or it can be streamed from the source to the sink using pullPacketStart(), pullPacketEnd(), and pullPacketProgress().
For output gates, true means that the connected module can pull packets from this module. For input gates, true means that this module can pull packets from the connected module. For example, a packet server module can pull packets from a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(pull) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return false; }
supportsPacketPushing()
virtual bool inet::NetworkInterface::supportsPacketPushing (cGate * gate) const inline override virtual
Returns true if the processor supports pushing packets at the given gate.
Pushing a packet is a synchronous operation that is initiated by the source module. A pushed packet can be passed as a whole using pushPacket(), or it can be streamed from the source to the sink using pushPacketStart(), pushPacketEnd(), and pushPacketProgress().
For output gates, true means that this module can push packets into the connected module. For input gates, true means that the connected module can push packets into this module. For example, a packet generator module can push packets into a queue module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(push) in the NED file.
Implements inet::queueing::IPacketProcessor.
 { return true; }
supportsPacketSending()
virtual bool inet::NetworkInterface::supportsPacketSending (cGate * gate) const inline override virtual
Returns true if the processor supports sending packets at the given gate.
Sending a packet is an asynchronous operation that is initiated by the source module. A sent packet is always passed as a whole using standard handleMessage().
For output gates, true means that this module can send packets into the connected module. For input gates, true means that the connected module can send packets into this module. For example, a standard OMNeT++ module can send packets to an INET packet processor module, or an INET packet processor module can send packets to a standard OMNeT++ module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(send) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return true; }
supportsPacketStreaming()
virtual bool inet::NetworkInterface::supportsPacketStreaming (cGate * gate) const inline override virtual
Returns true if the processor supports streaming packets at the given gate.
A streamed packet is handed over from one module to another using several method calls and potentially exending to a non-zero simulation duration.
For example, packets are streamed to a preemptable signal transmitter module.
Connecting incompatible gates raises an error during initialize. The gate parameter must be a valid gate of this module. The gate should be marked with @labels(stream) in the NED file.
Reimplemented from inet::queueing::PacketProcessorBase.
 { return false; }
updateDisplayString()
void inet::NetworkInterface::updateDisplayString () const override protected virtual
Reimplemented from inet::queueing::PacketProcessorBase.
 {
     if (getEnvir()->isGUI()) {
         auto text = StringFormat::formatString(par("displayStringTextFormat"), this);
         getDisplayString().setTagArg("t", 0, text);
     }
 }
Referenced by refreshDisplay().
Friends And Related Function Documentation
InterfaceProtocolData
friend class InterfaceProtocolData friend
Member Data Documentation
broadcast
bool inet::NetworkInterface::broadcast = false protected
interface supports broadcast
Referenced by initialize().
carrier
bool inet::NetworkInterface::carrier = false protected
presence of the physical or virtual carrier
Referenced by initialize(), and setCarrier().
datarate
double inet::NetworkInterface::datarate = 0 protected
data rate in bit/s
Referenced by initialize(), inet::EthernetCutthroughInterface::pushPacketStart(), and pushPacketStart().
estimateCostProcessArray
std::vector<MacEstimateCostProcess *> inet::NetworkInterface::estimateCostProcessArray protected
Referenced by getEstimateCostProcess(), and setEstimateCostProcess().
hasModuleIdAddress
bool inet::NetworkInterface::hasModuleIdAddress = false protected
Referenced by getNetworkAddress(), and hasNetworkAddress().
hasModulePathAddress
bool inet::NetworkInterface::hasModulePathAddress = false protected
Referenced by getNetworkAddress(), and hasNetworkAddress().
interfaceId
int inet::NetworkInterface::interfaceId = -1 protected
identifies the interface in the IInterfaceTable
Referenced by arrived(), pushPacket(), inet::EthernetCutthroughInterface::pushPacketEnd(), pushPacketEnd(), inet::EthernetCutthroughInterface::pushPacketStart(), pushPacketStart(), and resolveDirective().
interfaceName
std::string inet::NetworkInterface::interfaceName protected
Referenced by resolveDirective().
interfaceTable
ModuleRefByPar<IInterfaceTable> inet::NetworkInterface::interfaceTable protected
IInterfaceTable that contains this interface, or nullptr.
Referenced by changed(), getInterfaceFullPath(), and initialize().
loopback
bool inet::NetworkInterface::loopback = false protected
interface is loopback interface
Referenced by initialize().
macAddr
MacAddress inet::NetworkInterface::macAddr protected
link-layer address (for now, only IEEE 802 MAC addresses are supported)
Referenced by initialize(), matchesMacAddress(), and resolveDirective().
mtu
int inet::NetworkInterface::mtu = 0 protected
Maximum Transmission Unit (e.g. 1500 on Ethernet); 0 means infinite (i.e. never fragment)
Referenced by initialize().
multicast
bool inet::NetworkInterface::multicast = false protected
interface supports multicast
Referenced by initialize().
multicastAddresses
std::vector<MacAddress> inet::NetworkInterface::multicastAddresses protected
Referenced by addMulticastMacAddress(), matchesMulticastMacAddress(), and removeMulticastMacAddress().
nodeInputGateId
int inet::NetworkInterface::nodeInputGateId = -1 protected
id of the input gate of this host/router (or -1 if this is a virtual interface)
nodeOutputGateId
int inet::NetworkInterface::nodeOutputGateId = -1 protected
id of the output gate of this host/router (or -1 if this is a virtual interface)
pointToPoint
bool inet::NetworkInterface::pointToPoint = false protected
interface is point-to-point link
Referenced by initialize().
protocol
const Protocol* inet::NetworkInterface::protocol = nullptr protected
Referenced by initialize().
protocolDataSet
TagSet inet::NetworkInterface::protocolDataSet protected
Referenced by clearProtocolDataSet(), resetInterface(), and str().
rxIn
cGate* inet::NetworkInterface::rxIn = nullptr protected
Referenced by initialize(), and receiveSignal().
rxTransmissionChannel
cChannel* inet::NetworkInterface::rxTransmissionChannel = nullptr protected
Referenced by computeCarrier(), initialize(), and receiveSignal().
state
State inet::NetworkInterface::state = DOWN protected
requested interface state, similar to Linux ifup/ifdown
Referenced by initialize(), setState(), and str().
token
InterfaceToken inet::NetworkInterface::token protected
for Ipv6 stateless autoconfig (RFC 1971), interface identifier (RFC 2462)
txOut
cGate* inet::NetworkInterface::txOut = nullptr protected
Referenced by initialize(), and receiveSignal().
txTransmissionChannel
cChannel* inet::NetworkInterface::txTransmissionChannel = nullptr protected
Referenced by computeCarrier(), computeDatarate(), initialize(), and receiveSignal().
upperLayerIn
cGate* inet::NetworkInterface::upperLayerIn = nullptr protected
Referenced by inet::NetworkInterface::LocalGate::deliver(), initialize(), pushPacket(), pushPacketEnd(), and pushPacketStart().
upperLayerInConsumer
queueing::IPassivePacketSink* inet::NetworkInterface::upperLayerInConsumer = nullptr protected
Referenced by initialize(), pushPacket(), pushPacketEnd(), and pushPacketStart().
upperLayerOut
cGate* inet::NetworkInterface::upperLayerOut = nullptr protected
Referenced by arrived(), initialize(), pushPacket(), pushPacketEnd(), and pushPacketStart().
upperLayerOutConsumer
queueing::IPassivePacketSink* inet::NetworkInterface::upperLayerOutConsumer = nullptr protected
Referenced by initialize(), pushPacket(), pushPacketEnd(), and pushPacketStart().
The documentation for this class was generated from the following files:
NetworkInterface.h
NetworkInterface.cc