INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRtsPolicy Class Reference
inet::ieee80211::IRtsPolicy Class Reference abstract
#include <IRtsPolicy.h>
Public Member Functions
virtual ~IRtsPolicy ()
virtual bool isRtsNeeded (Packet *packet, const Ptr< const Ieee80211MacHeader > &protectedHeader) const =0
virtual simtime_t getCtsTimeout (Packet *packet, const Ptr< const Ieee80211RtsFrame > &rtsFrame) const =0
virtual int getRtsThreshold () const =0
Constructor & Destructor Documentation
~IRtsPolicy()
virtual inet::ieee80211::IRtsPolicy::~IRtsPolicy () inline virtual
 {}
Member Function Documentation
getCtsTimeout()
virtual simtime_t inet::ieee80211::IRtsPolicy::getCtsTimeout (Packet * packet, const Ptr< const Ieee80211RtsFrame > & rtsFrame) const pure virtual
Implemented in inet::ieee80211::QosRtsPolicy, and inet::ieee80211::RtsPolicy.
Referenced by inet::ieee80211::FrameSequenceContext::getCtsTimeout().
getRtsThreshold()
virtual int inet::ieee80211::IRtsPolicy::getRtsThreshold () const pure virtual
Implemented in inet::ieee80211::QosRtsPolicy, and inet::ieee80211::RtsPolicy.
isRtsNeeded()
virtual bool inet::ieee80211::IRtsPolicy::isRtsNeeded (Packet * packet, const Ptr< const Ieee80211MacHeader > & protectedHeader) const pure virtual
Implemented in inet::ieee80211::QosRtsPolicy, and inet::ieee80211::RtsPolicy.
Referenced by inet::ieee80211::TxOpFs::isRtsCtsNeeded(), and inet::ieee80211::DcfFs::isRtsCtsNeeded().
The documentation for this class was generated from the following file:
IRtsPolicy.h