INET Framework for OMNeT++/OMNEST: inet::rtp::RtpCiEnterSession Class Reference
inet::rtp::RtpCiEnterSession Class Reference
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:57 by opp_msgtool.
#include <RtpInterfacePacket_m.h>
Public Member Functions
RtpCiEnterSession ()
RtpCiEnterSession (const RtpCiEnterSession &other)
virtual ~RtpCiEnterSession ()
RtpCiEnterSession & operator= (const RtpCiEnterSession &other)
virtual RtpCiEnterSession * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const char * getCommonName () const
virtual void setCommonName (const char *commonName)
virtual const char * getProfileName () const
virtual void setProfileName (const char *profileName)
virtual int getBandwidth () const
virtual void setBandwidth (int bandwidth)
virtual const ::inet::Ipv4Address & getDestinationAddress () const
virtual ::inet::Ipv4Address & getDestinationAddressForUpdate ()
virtual void setDestinationAddress (const ::inet::Ipv4Address &destinationAddress)
virtual int getPort () const
virtual void setPort (int port)
Public Member Functions inherited from inet::rtp::RtpControlInfo
RtpControlInfo ()
RtpControlInfo (const RtpControlInfo &other)
virtual ~RtpControlInfo ()
RtpControlInfo & operator= (const RtpControlInfo &other)
virtual RtpIfpType getType () const
virtual void setType (RtpIfpType type)
Protected Member Functions
bool operator== (const RtpCiEnterSession &)=delete
Protected Member Functions inherited from inet::rtp::RtpControlInfo
bool operator== (const RtpControlInfo &)=delete
Protected Attributes
::omnetpp::opp_string commonName
::omnetpp::opp_string profileName
int bandwidth = 0
::inet::Ipv4Address destinationAddress
int port = 0
Protected Attributes inherited from inet::rtp::RtpControlInfo
RtpIfpType type = static_cast<inet::rtp::RtpIfpType>(-1)
Private Member Functions
void copy (const RtpCiEnterSession &other)
Detailed Description
Class generated from inet/transportlayer/rtp/RtpInterfacePacket.msg:57 by opp_msgtool.
// App to ~Rtp
class RtpCiEnterSession extends RtpControlInfo
{
    type = RTP_IFP_ENTER_SESSION;
    string commonName;
    string profileName;
    int bandwidth;
    Ipv4Address destinationAddress;
    int port;
}
Constructor & Destructor Documentation
RtpCiEnterSession() [1/2]
inet::rtp::RtpCiEnterSession::RtpCiEnterSession ()
RtpCiEnterSession() [2/2]
inet::rtp::RtpCiEnterSession::RtpCiEnterSession (const RtpCiEnterSession & other)
~RtpCiEnterSession()
virtual inet::rtp::RtpCiEnterSession::~RtpCiEnterSession () virtual
Member Function Documentation
copy()
void inet::rtp::RtpCiEnterSession::copy (const RtpCiEnterSession & other) private
dup()
virtual RtpCiEnterSession* inet::rtp::RtpCiEnterSession::dup () const inline override virtual
Reimplemented from inet::rtp::RtpControlInfo.
 {return new RtpCiEnterSession(*this);}
getBandwidth()
virtual int inet::rtp::RtpCiEnterSession::getBandwidth () const virtual
Referenced by inet::rtp::Rtp::enterSession().
getCommonName()
virtual const char* inet::rtp::RtpCiEnterSession::getCommonName () const virtual
Referenced by inet::rtp::Rtp::enterSession().
getDestinationAddress()
virtual const ::inet::Ipv4Address& inet::rtp::RtpCiEnterSession::getDestinationAddress () const virtual
Referenced by inet::rtp::Rtp::enterSession().
getDestinationAddressForUpdate()
virtual ::inet::Ipv4Address& inet::rtp::RtpCiEnterSession::getDestinationAddressForUpdate () inline
 { return const_cast<::inet::Ipv4Address&>(const_cast<RtpCiEnterSession*>(this)->getDestinationAddress());}
getPort()
virtual int inet::rtp::RtpCiEnterSession::getPort () const virtual
Referenced by inet::rtp::Rtp::enterSession().
getProfileName()
virtual const char* inet::rtp::RtpCiEnterSession::getProfileName () const virtual
Referenced by inet::rtp::Rtp::enterSession().
operator=()
RtpCiEnterSession& inet::rtp::RtpCiEnterSession::operator= (const RtpCiEnterSession & other)
operator==()
bool inet::rtp::RtpCiEnterSession::operator== (const RtpCiEnterSession &) protected delete
parsimPack()
virtual void inet::rtp::RtpCiEnterSession::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented from inet::rtp::RtpControlInfo.
Referenced by inet::rtp::doParsimPacking().
parsimUnpack()
virtual void inet::rtp::RtpCiEnterSession::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented from inet::rtp::RtpControlInfo.
Referenced by inet::rtp::doParsimUnpacking().
setBandwidth()
virtual void inet::rtp::RtpCiEnterSession::setBandwidth (int bandwidth) virtual
setCommonName()
virtual void inet::rtp::RtpCiEnterSession::setCommonName (const char * commonName) virtual
setDestinationAddress()
virtual void inet::rtp::RtpCiEnterSession::setDestinationAddress (const ::inet::Ipv4Address & destinationAddress) virtual
setPort()
virtual void inet::rtp::RtpCiEnterSession::setPort (int port) virtual
setProfileName()
virtual void inet::rtp::RtpCiEnterSession::setProfileName (const char * profileName) virtual
Member Data Documentation
bandwidth
int inet::rtp::RtpCiEnterSession::bandwidth = 0 protected
commonName
::omnetpp::opp_string inet::rtp::RtpCiEnterSession::commonName protected
destinationAddress
::inet::Ipv4Address inet::rtp::RtpCiEnterSession::destinationAddress protected
port
int inet::rtp::RtpCiEnterSession::port = 0 protected
profileName
::omnetpp::opp_string inet::rtp::RtpCiEnterSession::profileName protected
The documentation for this class was generated from the following file:
RtpInterfacePacket_m.h