INET Framework for OMNeT++/OMNEST: inet::physicallayer::EthernetSignalBase Class Reference
inet::physicallayer::EthernetSignalBase Class Reference
Class generated from inet/physicallayer/wired/ethernet/EthernetSignal.msg:21 by opp_msgtool.
#include <EthernetSignal_m.h>
Public Member Functions
EthernetSignalBase (const char *name=nullptr, short kind=0)
EthernetSignalBase (const EthernetSignalBase &other)
virtual ~EthernetSignalBase ()
EthernetSignalBase & operator= (const EthernetSignalBase &other)
virtual EthernetSignalBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getSrcMacFullDuplex () const
virtual void setSrcMacFullDuplex (bool srcMacFullDuplex)
virtual double getBitrate () const
virtual void setBitrate (double bitrate)
Public Member Functions inherited from inet::physicallayer::Signal
Signal (const char *name=nullptr, short kind=0, int64_t bitLength=0)
Signal (const Signal &other)
virtual const char * getFullName () const override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const EthernetSignalBase &)=delete
Protected Attributes
bool srcMacFullDuplex = false
double bitrate = 0
Private Member Functions
void copy (const EthernetSignalBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/physicallayer/wired/ethernet/EthernetSignal.msg:21 by opp_msgtool.
//
// Abstract base class for various Ethernet traffic types:
// EtherJam, EtherFilledIfg and EtherPhyFrame.
//
packet EthernetSignalBase extends Signal
{
    bool srcMacFullDuplex;  // meta-info, for detecting model misconfiguration
    double bitrate;  // meta-info, for detecting model misconfiguration
}
Constructor & Destructor Documentation
EthernetSignalBase() [1/2]
inet::physicallayer::EthernetSignalBase::EthernetSignalBase (const char * name = nullptr, short kind = 0)
EthernetSignalBase() [2/2]
inet::physicallayer::EthernetSignalBase::EthernetSignalBase (const EthernetSignalBase & other)
~EthernetSignalBase()
virtual inet::physicallayer::EthernetSignalBase::~EthernetSignalBase () virtual
Member Function Documentation
copy()
void inet::physicallayer::EthernetSignalBase::copy (const EthernetSignalBase & other) private
dup()
virtual EthernetSignalBase* inet::physicallayer::EthernetSignalBase::dup () const inline override virtual
Reimplemented from inet::physicallayer::Signal.
Reimplemented in inet::physicallayer::EthernetFilledIfgSignal, inet::physicallayer::EthernetJamSignal, and inet::physicallayer::EthernetSignal.
 {return new EthernetSignalBase(*this);}
Referenced by inet::EthernetCsmaMac::sendSignal(), and inet::EthernetMac::startFrameTransmission().
getBitrate()
virtual double inet::physicallayer::EthernetSignalBase::getBitrate () const virtual
Referenced by inet::EthernetMacBase::cutEthernetSignalEnd().
getSrcMacFullDuplex()
virtual bool inet::physicallayer::EthernetSignalBase::getSrcMacFullDuplex () const virtual
Referenced by inet::EthernetCsmaMac::frameReceptionComplete(), and inet::EthernetMac::processMsgFromNetwork().
operator=()
EthernetSignalBase& inet::physicallayer::EthernetSignalBase::operator= (const EthernetSignalBase & other)
operator==()
bool inet::physicallayer::EthernetSignalBase::operator== (const EthernetSignalBase &) protected delete
parsimPack()
virtual void inet::physicallayer::EthernetSignalBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::physicallayer::EthernetFilledIfgSignal, inet::physicallayer::EthernetJamSignal, and inet::physicallayer::EthernetSignal.
Referenced by inet::physicallayer::doParsimPacking().
parsimUnpack()
virtual void inet::physicallayer::EthernetSignalBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::physicallayer::EthernetFilledIfgSignal, inet::physicallayer::EthernetJamSignal, and inet::physicallayer::EthernetSignal.
Referenced by inet::physicallayer::doParsimUnpacking().
setBitrate()
virtual void inet::physicallayer::EthernetSignalBase::setBitrate (double bitrate) virtual
Referenced by inet::EthernetCsmaMac::fillIFGInBurst(), and inet::EthernetCsmaMac::sendJamSignal().
setSrcMacFullDuplex()
virtual void inet::physicallayer::EthernetSignalBase::setSrcMacFullDuplex (bool srcMacFullDuplex) virtual
Member Data Documentation
bitrate
double inet::physicallayer::EthernetSignalBase::bitrate = 0 protected
srcMacFullDuplex
bool inet::physicallayer::EthernetSignalBase::srcMacFullDuplex = false protected
The documentation for this class was generated from the following file:
EthernetSignal_m.h