INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211ErrorModelBase Class Reference
inet::physicallayer::Ieee80211ErrorModelBase Class Reference abstract
#include <Ieee80211ErrorModelBase.h>
Public Member Functions
Ieee80211ErrorModelBase ()
virtual double computePacketErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the packet error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeBitErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the bit error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
virtual double computeSymbolErrorRate (const ISnir *snir, IRadioSignal::SignalPart part) const override
Returns the symbol error rate based on SNIR, modulation, and any other physical layer characteristics.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual double getHeaderSuccessRate (const IIeee80211Mode *mode, unsigned int bitLength, double snir) const =0
virtual double getDataSuccessRate (const IIeee80211Mode *mode, unsigned int bitLength, double snir) const =0
virtual Packet * computeCorruptedPacket (const Packet *packet, double ber) const override
virtual double getDsssDbpskSuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskSuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskCck5_5SuccessRate (unsigned int bitLength, double snir) const
virtual double getDsssDqpskCck11SuccessRate (unsigned int bitLength, double snir) const
Protected Member Functions inherited from inet::physicallayer::ErrorModelBase
virtual void initialize (int stage) override
virtual double getScalarSnir (const ISnir *snir) const
virtual bool hasProbabilisticError (b length, double ber) const
virtual Packet * corruptBits (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptBytes (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptChunks (const Packet *packet, double ber, bool &isCorrupted) const
virtual Packet * corruptPacket (const Packet *packet, bool &isCorrupted) const
virtual Packet * computeCorruptedPacket (const ISnir *snir) const override
Protected Attributes
double spectralEfficiency1bit = 2000000.0 / 1000000.0
double spectralEfficiency2bit = 2000000.0 / 1000000.0 / 2.0
double sirPerfect = 10.0
double sirImpossible = 0.1
Protected Attributes inherited from inet::physicallayer::ErrorModelBase
CorruptionMode corruptionMode = CorruptionMode::CM_UNDEFINED
SnirMode snirMode = SnirMode::SM_UNDEFINED
double snirOffset = NaN
Additional Inherited Members
Public Types inherited from inet::physicallayer::ErrorModelBase
enum CorruptionMode {
CorruptionMode::CM_UNDEFINED = -1, CorruptionMode::CM_PACKET, CorruptionMode::CM_CHUNK, CorruptionMode::CM_BYTE,
CorruptionMode::CM_BIT
}
enum SnirMode { SnirMode::SM_UNDEFINED = -1, SnirMode::SM_MIN, SnirMode::SM_MEAN }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211ErrorModelBase()
inet::physicallayer::Ieee80211ErrorModelBase::Ieee80211ErrorModelBase ()
 {
 }
Member Function Documentation
computeBitErrorRate()
double inet::physicallayer::Ieee80211ErrorModelBase::computeBitErrorRate (const ISnir * snir, IRadioSignal::SignalPart part) const override virtual
Returns the bit error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
Implements inet::physicallayer::IErrorModel.
 {
     Enter_Method("computeBitErrorRate");
     return NaN;
 }
computeCorruptedPacket()
Packet * inet::physicallayer::Ieee80211ErrorModelBase::computeCorruptedPacket (const Packet * packet, double ber) const override protected virtual
Reimplemented from inet::physicallayer::ErrorModelBase.
 {
     if (corruptionMode == CorruptionMode::CM_PACKET)
         return ErrorModelBase::computeCorruptedPacket(packet, ber);
     else
         throw cRuntimeError("Unimplemented corruption mode");
 }
computePacketErrorRate()
double inet::physicallayer::Ieee80211ErrorModelBase::computePacketErrorRate (const ISnir * snir, IRadioSignal::SignalPart part) const override virtual
Returns the packet error rate based on SNIR, modulation, FEC encoding and any other physical layer characteristics.
Implements inet::physicallayer::IErrorModel.
 {
     Enter_Method("computePacketErrorRate");
     auto transmission = snir->getReception()->getTransmission();
     auto flatTransmission = dynamic_cast<const FlatTransmissionBase *>(transmission);
     auto ieee80211Transmission = check_and_cast<const Ieee80211TransmissionBase *>(transmission);
     auto mode = ieee80211Transmission->getMode();
     auto headerLength = flatTransmission != nullptr ? flatTransmission->getHeaderLength() : mode->getHeaderMode()->getLength();
     auto dataLength = flatTransmission != nullptr ? flatTransmission->getDataLength() : mode->getDataMode()->getCompleteLength(transmission->getPacket()->getTotalLength() - headerLength);
     // TODO check header length and data length for OFDM (signal) field
     double headerSuccessRate = getHeaderSuccessRate(mode, b(headerLength).get(), getScalarSnir(snir));
     double dataSuccessRate = getDataSuccessRate(mode, b(dataLength).get(), getScalarSnir(snir));
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return 1.0 - headerSuccessRate * dataSuccessRate;
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return 0;
         case IRadioSignal::SIGNAL_PART_HEADER:
             return 1.0 - headerSuccessRate;
         case IRadioSignal::SIGNAL_PART_DATA:
             return 1.0 - dataSuccessRate;
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
Referenced by inet::physicallayer::Ieee80211OfdmErrorModel::computePacketModel().
computeSymbolErrorRate()
double inet::physicallayer::Ieee80211ErrorModelBase::computeSymbolErrorRate (const ISnir * snir, IRadioSignal::SignalPart part) const override virtual
Returns the symbol error rate based on SNIR, modulation, and any other physical layer characteristics.
Implements inet::physicallayer::IErrorModel.
 {
     Enter_Method("computeSymbolErrorRate");
     return NaN;
 }
getDataSuccessRate()
virtual double inet::physicallayer::Ieee80211ErrorModelBase::getDataSuccessRate (const IIeee80211Mode * mode, unsigned int bitLength, double snir) const protected pure virtual
Implemented in inet::physicallayer::Ieee80211YansErrorModel, and inet::physicallayer::Ieee80211NistErrorModel.
Referenced by computePacketErrorRate().
getDsssDbpskSuccessRate()
double inet::physicallayer::Ieee80211ErrorModelBase::getDsssDbpskSuccessRate (unsigned int bitLength, double snir) const protected virtual
 {
     double EbN0 = snir * spectralEfficiency1bit; // 1 bit per symbol with 1 MSPS
     double bitErrorRate = 0.5 * exp(-EbN0);
     return pow((1.0 - bitErrorRate), (int)bitLength);
 }
Referenced by inet::physicallayer::Ieee80211NistErrorModel::getDSSSAndHrDSSSChunkSuccessRate(), and inet::physicallayer::Ieee80211YansErrorModel::getDSSSAndHrDSSSChunkSuccessRate().
getDsssDqpskCck11SuccessRate()
double inet::physicallayer::Ieee80211ErrorModelBase::getDsssDqpskCck11SuccessRate (unsigned int bitLength, double snir) const protected virtual
 {
     double bitErrorRate;
     if (snir > sirPerfect)
         bitErrorRate = 0.0;
     else if (snir < sirImpossible)
         bitErrorRate = 0.5;
     else {
         double a1 = 7.9056742265333456e-003;
         double a2 = -1.8397449399176360e-001;
         double a3 = 1.0740689468707241e+000;
         double a4 = 1.0523316904502553e+000;
         double a5 = 3.0552298746496687e-001;
         double a6 = 2.2032715128698435e+000;
         bitErrorRate = (a1 * snir * snir + a2 * snir + a3) / (snir * snir * snir + a4 * snir * snir + a5 * snir + a6);
     }
     return pow((1.0 - bitErrorRate), (int)bitLength);
 }
Referenced by inet::physicallayer::Ieee80211NistErrorModel::getDSSSAndHrDSSSChunkSuccessRate(), and inet::physicallayer::Ieee80211YansErrorModel::getDSSSAndHrDSSSChunkSuccessRate().
getDsssDqpskCck5_5SuccessRate()
double inet::physicallayer::Ieee80211ErrorModelBase::getDsssDqpskCck5_5SuccessRate (unsigned int bitLength, double snir) const protected virtual
 {
     double bitErrorRate;
     if (snir > sirPerfect)
         bitErrorRate = 0.0;
     else if (snir < sirImpossible)
         bitErrorRate = 0.5;
     else {
         double a1 = 5.3681634344056195e-001;
         double a2 = 3.3092430025608586e-003;
         double a3 = 4.1654372361004000e-001;
         double a4 = 1.0288981434358866e+000;
         bitErrorRate = a1 * exp(-(pow((snir - a2) / a3, a4)));
     }
     return pow((1.0 - bitErrorRate), (int)bitLength);
 }
Referenced by inet::physicallayer::Ieee80211NistErrorModel::getDSSSAndHrDSSSChunkSuccessRate(), and inet::physicallayer::Ieee80211YansErrorModel::getDSSSAndHrDSSSChunkSuccessRate().
getDsssDqpskSuccessRate()
double inet::physicallayer::Ieee80211ErrorModelBase::getDsssDqpskSuccessRate (unsigned int bitLength, double snir) const protected virtual
 {
     double EbN0 = snir * spectralEfficiency2bit; // 2 bits per symbol, 1 MSPS
     double bitErrorRate = ((sqrt(2.0) + 1.0) / sqrt(8.0 * 3.1415926 * sqrt(2.0))) * (1.0 / sqrt(EbN0)) * exp(-(2.0 - sqrt(2.0)) * EbN0);
     return pow((1.0 - bitErrorRate), (int)bitLength);
 }
Referenced by inet::physicallayer::Ieee80211NistErrorModel::getDSSSAndHrDSSSChunkSuccessRate(), and inet::physicallayer::Ieee80211YansErrorModel::getDSSSAndHrDSSSChunkSuccessRate().
getHeaderSuccessRate()
virtual double inet::physicallayer::Ieee80211ErrorModelBase::getHeaderSuccessRate (const IIeee80211Mode * mode, unsigned int bitLength, double snir) const protected pure virtual
Implemented in inet::physicallayer::Ieee80211NistErrorModel, and inet::physicallayer::Ieee80211YansErrorModel.
Referenced by computePacketErrorRate().
Member Data Documentation
sirImpossible
double inet::physicallayer::Ieee80211ErrorModelBase::sirImpossible = 0.1 protected
Referenced by getDsssDqpskCck11SuccessRate(), and getDsssDqpskCck5_5SuccessRate().
sirPerfect
double inet::physicallayer::Ieee80211ErrorModelBase::sirPerfect = 10.0 protected
Referenced by getDsssDqpskCck11SuccessRate(), and getDsssDqpskCck5_5SuccessRate().
spectralEfficiency1bit
double inet::physicallayer::Ieee80211ErrorModelBase::spectralEfficiency1bit = 2000000.0 / 1000000.0 protected
Referenced by getDsssDbpskSuccessRate().
spectralEfficiency2bit
double inet::physicallayer::Ieee80211ErrorModelBase::spectralEfficiency2bit = 2000000.0 / 1000000.0 / 2.0 protected
Referenced by getDsssDqpskSuccessRate().
The documentation for this class was generated from the following files:
Ieee80211ErrorModelBase.h
Ieee80211ErrorModelBase.cc