INET Framework for OMNeT++/OMNEST: inet::sctp::SctpErrorChunk Class Reference
inet::sctp::SctpErrorChunk Class Reference
#include <SctpHeader.h>
Public Member Functions
SctpErrorChunk (const char *name=nullptr, int32_t kind=0)
SctpErrorChunk (const SctpErrorChunk &other)
SctpErrorChunk & operator= (const SctpErrorChunk &other)
~SctpErrorChunk ()
virtual SctpErrorChunk * dup () const override
virtual void setParametersArraySize (size_t size) override
virtual size_t getParametersArraySize () const override
virtual void setParameters (size_t k, SctpParameter *parameters) override
Generated but unused method, should not be called.
virtual void appendParameters (SctpParameter *parameters) override
virtual void insertParameters (size_t k, SctpParameter *parameters) override
virtual void eraseParameters (size_t k) override
virtual SctpParameter * getParameters (size_t k) const override
Returns the kth parameter in this SCTP Error Chunk.
virtual void addParameters (SctpParameter *msg)
Adds a message object to the SCTP packet.
virtual SctpParameter * removeParameter ()
Removes and returns the first message object in this SCTP packet.
virtual void insertParameters (size_t k, SctpParameter *parameters)=0
void insertParameters (SctpParameter *parameters)
Public Member Functions inherited from inet::sctp::SctpErrorChunk_Base
virtual ~SctpErrorChunk_Base ()
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getTBit () const
virtual void setTBit (bool TBit)
virtual bool getMBit () const
virtual void setMBit (bool MBit)
virtual SctpParameter * getParametersForUpdate (size_t k)
void insertParameters (SctpParameter *parameters)
Public Member Functions inherited from inet::sctp::SctpChunk
SctpChunk (const char *name=nullptr)
SctpChunk (const SctpChunk &other)
virtual ~SctpChunk ()
SctpChunk & operator= (const SctpChunk &other)
virtual uint8_t getSctpChunkType () const
virtual void setSctpChunkType (uint8_t sctpChunkType)
virtual uint32_t getFlags () const
virtual void setFlags (uint32_t flags)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
virtual void setChunkNameArraySize (size_t size)
virtual size_t getChunkNameArraySize () const
virtual char getChunkName (size_t k) const
virtual void setChunkName (size_t k, char chunkName)
virtual void insertChunkName (size_t k, char chunkName)
void insertChunkName (char chunkName)
virtual void appendChunkName (char chunkName)
virtual void eraseChunkName (size_t k)
Protected Attributes
std::vector< SctpParameter * > parameterList
Protected Attributes inherited from inet::sctp::SctpErrorChunk_Base
bool TBit = 0
bool MBit = 0
Protected Attributes inherited from inet::sctp::SctpChunk
uint8_t sctpChunkType = 0
uint32_t flags = 0
unsigned short length = 0
char * chunkName = nullptr
size_t chunkName_arraysize = 0
Private Member Functions
void copy (const SctpErrorChunk &other)
void clean ()
Additional Inherited Members
Protected Member Functions inherited from inet::sctp::SctpErrorChunk_Base
bool operator== (const SctpErrorChunk_Base &)=delete
SctpErrorChunk_Base (const char *name=nullptr)
SctpErrorChunk_Base (const SctpErrorChunk_Base &other)
SctpErrorChunk_Base & operator= (const SctpErrorChunk_Base &other)
Protected Member Functions inherited from inet::sctp::SctpChunk
bool operator== (const SctpChunk &)=delete
Constructor & Destructor Documentation
SctpErrorChunk() [1/2]
inet::sctp::SctpErrorChunk::SctpErrorChunk (const char * name = nullptr, int32_t kind = 0) inline
 : SctpErrorChunk_Base() {};
SctpErrorChunk() [2/2]
inet::sctp::SctpErrorChunk::SctpErrorChunk (const SctpErrorChunk & other) inline
 : SctpErrorChunk_Base(other) { copy(other); };
~SctpErrorChunk()
inet::sctp::SctpErrorChunk::~SctpErrorChunk ()
 {
     clean();
 }
Member Function Documentation
addParameters()
void inet::sctp::SctpErrorChunk::addParameters (SctpParameter * msg) virtual
Adds a message object to the SCTP packet.
The packet length will be adjusted
 {
     take(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     parameterList.push_back(msg);
 }
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::sctp::SctpNatHook::sendBackError(), inet::sctp::SctpAssociation::sendHMacError(), and inet::sctp::SctpAssociation::sendInvalidStreamError().
appendParameters()
virtual void inet::sctp::SctpErrorChunk::appendParameters (SctpParameter * parameters) inline override virtual
Implements inet::sctp::SctpErrorChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
clean()
void inet::sctp::SctpErrorChunk::clean () private
 {
     while (!parameterList.empty()) {
         cPacket *msg = parameterList.front();
         parameterList.erase(parameterList.begin());
         dropAndDelete(msg);
     }
 }
Referenced by operator=(), and ~SctpErrorChunk().
copy()
void inet::sctp::SctpErrorChunk::copy (const SctpErrorChunk & other) private
 {
     for (const auto& elem : other.parameterList) {
         SctpParameter *param = (elem)->dup();
         take(param);
         parameterList.push_back(param);
     }
 }
Referenced by operator=().
dup()
virtual SctpErrorChunk* inet::sctp::SctpErrorChunk::dup () const inline override virtual
Reimplemented from inet::sctp::SctpErrorChunk_Base.
 { return new SctpErrorChunk(*this); }
Referenced by copy().
eraseParameters()
virtual void inet::sctp::SctpErrorChunk::eraseParameters (size_t k) inline override virtual
Implements inet::sctp::SctpErrorChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
getParameters()
SctpParameter * inet::sctp::SctpErrorChunk::getParameters (size_t k) const override virtual
Returns the kth parameter in this SCTP Error Chunk.
Implements inet::sctp::SctpErrorChunk_Base.
 {
     return parameterList.at(k);
 }
Referenced by inet::sctp::SctpAssociation::processErrorArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
getParametersArraySize()
size_t inet::sctp::SctpErrorChunk::getParametersArraySize () const override virtual
Implements inet::sctp::SctpErrorChunk_Base.
 {
     return parameterList.size();
 }
Referenced by inet::sctp::SctpAssociation::processErrorArrived(), and inet::sctp::SctpHeaderSerializer::serialize().
insertParameters() [1/3]
void inet::sctp::SctpErrorChunk_Base::insertParameters inline
 {appendParameters(parameters);}
insertParameters() [2/3]
virtual void inet::sctp::SctpErrorChunk::insertParameters (size_t k, SctpParameter * parameters) inline override virtual
Implements inet::sctp::SctpErrorChunk_Base.
 { throw cRuntimeError("Unimplemented function"); }
insertParameters() [3/3]
virtual void inet::sctp::SctpErrorChunk_Base::insertParameters
operator=()
SctpErrorChunk & inet::sctp::SctpErrorChunk::operator= (const SctpErrorChunk & other)
 {
     if (this == &other)
         return *this;
     clean();
     SctpErrorChunk_Base::operator=(other);
     copy(other);
     return *this;
 }
removeParameter()
SctpParameter * inet::sctp::SctpErrorChunk::removeParameter () virtual
Removes and returns the first message object in this SCTP packet.
 {
     if (parameterList.empty())
         return nullptr;
     SctpParameter *msg = parameterList.front();
     parameterList.erase(parameterList.begin());
     drop(msg);
     this->setByteLength(this->getByteLength() + ADD_PADDING(msg->getByteLength()));
     return msg;
 }
setParameters()
void inet::sctp::SctpErrorChunk::setParameters (size_t k, SctpParameter * parameters) override virtual
Generated but unused method, should not be called.
Implements inet::sctp::SctpErrorChunk_Base.
 {
     throw cException(this, "setParameter() not supported, use addParameter()");
 }
setParametersArraySize()
void inet::sctp::SctpErrorChunk::setParametersArraySize (size_t size) override virtual
Implements inet::sctp::SctpErrorChunk_Base.
 {
     throw cException(this, "setParametersArraySize() not supported, use addParameter()");
 }
Member Data Documentation
parameterList
std::vector<SctpParameter *> inet::sctp::SctpErrorChunk::parameterList protected
Referenced by addParameters(), clean(), copy(), getParameters(), getParametersArraySize(), and removeParameter().
The documentation for this class was generated from the following files:
SctpHeader.h
SctpHeader.cc