INET Framework for OMNeT++/OMNEST: inet::MacProtocolBase Class Reference
inet::MacProtocolBase Class Reference abstract
#include <MacProtocolBase.h>
Protected Member Functions
MacProtocolBase ()
virtual ~MacProtocolBase ()
virtual void initialize (int stage) override
virtual void registerInterface ()
virtual void configureNetworkInterface ()=0
virtual MacAddress parseMacAddressParameter (const char *addrstr)
virtual void deleteCurrentTxFrame ()
virtual void dropCurrentTxFrame (PacketDropDetails &details)
virtual void handleMessageWhenDown (cMessage *msg) override
virtual void sendUp (cMessage *message)
virtual void sendDown (cMessage *message)
virtual bool isUpperMessage (cMessage *message) const override
virtual bool isLowerMessage (cMessage *message) const override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void flushQueue (PacketDropDetails &details)
should clear queue and emit signal "packetDropped" with entire packets
virtual void clearQueue ()
should clear queue silently
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
queueing::IPacketQueue * getQueue (cGate *gate) const
virtual bool canDequeuePacket () const
virtual Packet * dequeuePacket ()
Protected Member Functions inherited from inet::LayeredProtocolBase
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleSelfMessage (cMessage *message)
virtual void handleUpperMessage (cMessage *message)
virtual void handleLowerMessage (cMessage *message)
virtual void handleUpperCommand (cMessage *message)
virtual void handleLowerCommand (cMessage *message)
virtual void handleUpperPacket (Packet *packet)
virtual void handleLowerPacket (Packet *packet)
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
int upperLayerInGateId = -1
Gate ids.
int upperLayerOutGateId = -1
int lowerLayerInGateId = -1
int lowerLayerOutGateId = -1
opp_component_ptr< NetworkInterface > networkInterface
opp_component_ptr< cModule > hostModule
Packet * currentTxFrame = nullptr
Currently transmitted frame if any.
opp_component_ptr< queueing::IPacketQueue > txQueue
Messages received from upper layer and to be transmitted later.
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Additional Inherited Members
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Constructor & Destructor Documentation
MacProtocolBase()
inet::MacProtocolBase::MacProtocolBase () protected
 {
 }
~MacProtocolBase()
inet::MacProtocolBase::~MacProtocolBase () protected virtual
 {
     delete currentTxFrame;
 }
Member Function Documentation
canDequeuePacket()
bool inet::MacProtocolBase::canDequeuePacket () const protected virtual
 {
     return txQueue && txQueue->canPullSomePacket(gate(upperLayerInGateId)->getPathStartGate());
 }
Referenced by clearQueue(), flushQueue(), inet::EthernetMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleCanPullPacketChanged(), inet::Ppp::handleCanPullPacketChanged(), inet::EthernetMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetMac::handleEndPausePeriod(), inet::EthernetCsmaMac::handleRetransmission(), inet::Ppp::handleSelfMessage(), inet::EthernetMacBase::processConnectDisconnect(), and inet::Ppp::refreshOutGateConnection().
clearQueue()
void inet::MacProtocolBase::clearQueue () protected virtual
should clear queue silently
 {
     if (txQueue)
         while (canDequeuePacket())
             delete dequeuePacket();
 }
Referenced by handleCrashOperation().
configureNetworkInterface()
virtual void inet::MacProtocolBase::configureNetworkInterface () protected pure virtual
Implemented in inet::Ieee802154Mac, inet::EthernetMacBase, inet::BMac, inet::LMac, inet::CsmaCaMac, inet::XMac, inet::ieee80211::Ieee80211Mac, inet::Ppp, inet::AckingMac, inet::ShortcutMac, inet::Loopback, and inet::Tun.
Referenced by registerInterface().
deleteCurrentTxFrame()
void inet::MacProtocolBase::deleteCurrentTxFrame () protected virtual
 {
     delete currentTxFrame;
     currentTxFrame = nullptr;
 }
Referenced by handleCrashOperation(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), and inet::Ppp::handleSelfMessage().
dequeuePacket()
Packet * inet::MacProtocolBase::dequeuePacket () protected virtual
 {
     Packet *packet = txQueue->dequeuePacket();
     take(packet);
     packet->setArrival(getId(), upperLayerInGateId, simTime());
     return packet;
 }
Referenced by clearQueue(), flushQueue(), inet::EthernetMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleCanPullPacketChanged(), inet::EthernetMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetMac::handleEndPausePeriod(), inet::EthernetCsmaMac::handleRetransmission(), inet::EthernetMacBase::processConnectDisconnect(), and inet::Ppp::processUpperPacket().
dropCurrentTxFrame()
void inet::MacProtocolBase::dropCurrentTxFrame (PacketDropDetails & details) protected virtual
Reimplemented in inet::EthernetCsmaMac.
 {
     emit(packetDroppedSignal, currentTxFrame, &details);
     delete currentTxFrame;
     currentTxFrame = nullptr;
 }
Referenced by inet::EthernetCsmaMac::dropCurrentTxFrame(), handleStopOperation(), and inet::EthernetMacBase::processConnectDisconnect().
flushQueue()
void inet::MacProtocolBase::flushQueue (PacketDropDetails & details) protected virtual
should clear queue and emit signal "packetDropped" with entire packets
 {
     // code would look slightly nicer with a pop() function that returns nullptr if empty
     if (txQueue)
         while (canDequeuePacket()) {
             auto packet = dequeuePacket();
             emit(packetDroppedSignal, packet, &details); // FIXME this signal lumps together packets from the network and packets from higher layers! separate them
             delete packet;
         }
 }
Referenced by handleStopOperation(), and inet::Ppp::refreshOutGateConnection().
getQueue()
queueing::IPacketQueue * inet::MacProtocolBase::getQueue (cGate * gate) const protected
 {
     // TODO use findConnectedModule() when the function is updated
     for (auto g = gate->getPreviousGate(); g != nullptr; g = g->getPreviousGate()) {
         if (g->getType() == cGate::OUTPUT) {
             auto m = dynamic_cast<queueing::IPacketQueue *>(g->getOwnerModule());
             if (m)
                 return m;
         }
     }
     throw cRuntimeError("Gate %s is not connected to a module of type queueing::IPacketQueue", gate->getFullPath().c_str());
 }
Referenced by inet::Ppp::initialize(), and inet::EthernetMacBase::initialize().
handleCrashOperation()
void inet::MacProtocolBase::handleCrashOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::Ieee802154Mac, inet::CsmaCaMac, inet::EthernetMacBase, inet::ieee80211::Ieee80211Mac, and inet::AckingMac.
 {
     deleteCurrentTxFrame();
     clearQueue();
     networkInterface->setCarrier(false);
     networkInterface->setState(NetworkInterface::State::DOWN);
 }
Referenced by inet::AckingMac::handleCrashOperation(), inet::CsmaCaMac::handleCrashOperation(), and inet::Ieee802154Mac::handleCrashOperation().
handleMessageWhenDown()
void inet::MacProtocolBase::handleMessageWhenDown (cMessage * msg) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
 {
     if (!msg->isSelfMessage() && msg->getArrivalGateId() == lowerLayerInGateId) {
         EV << "Interface is turned off, dropping packet\n";
         delete msg;
     }
     else
         LayeredProtocolBase::handleMessageWhenDown(msg);
 }
handleStartOperation()
void inet::MacProtocolBase::handleStartOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::Ieee802154Mac, inet::EthernetMacBase, inet::ieee80211::Ieee80211Mac, and inet::AckingMac.
 {
     networkInterface->setState(NetworkInterface::State::UP);
     networkInterface->setCarrier(true);
 }
Referenced by inet::Ieee802154Mac::handleStartOperation().
handleStopOperation()
void inet::MacProtocolBase::handleStopOperation (LifecycleOperation * operation) override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::Ieee802154Mac, inet::CsmaCaMac, inet::EthernetMacBase, inet::ieee80211::Ieee80211Mac, inet::Ppp, and inet::AckingMac.
 {
     PacketDropDetails details;
     details.setReason(INTERFACE_DOWN);
     if (currentTxFrame)
         dropCurrentTxFrame(details);
     flushQueue(details);
     networkInterface->setCarrier(false);
     networkInterface->setState(NetworkInterface::State::DOWN);
 }
Referenced by inet::AckingMac::handleStopOperation(), inet::CsmaCaMac::handleStopOperation(), and inet::Ieee802154Mac::handleStopOperation().
initialize()
void inet::MacProtocolBase::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::LMac, inet::Ieee802154Mac, inet::XMac, inet::BMac, inet::ieee80211::Ieee80211Mac, inet::EthernetMacBase, inet::CsmaCaMac, inet::AckingMac, inet::Ppp, inet::Loopback, inet::EthernetCsmaMac, inet::ShortcutMac, inet::EthernetMac, and inet::Tun.
 {
     LayeredProtocolBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         upperLayerInGateId = findGate("upperLayerIn");
         upperLayerOutGateId = findGate("upperLayerOut");
         lowerLayerInGateId = findGate("lowerLayerIn");
         lowerLayerOutGateId = findGate("lowerLayerOut");
         currentTxFrame = nullptr;
         hostModule = findContainingNode(this);
     }
     else if (stage == INITSTAGE_NETWORK_INTERFACE_CONFIGURATION)
         registerInterface();
 }
Referenced by inet::Tun::initialize(), inet::ShortcutMac::initialize(), inet::Loopback::initialize(), inet::ieee80211::Ieee80211Mac::initialize(), inet::BMac::initialize(), inet::Ppp::initialize(), inet::AckingMac::initialize(), inet::XMac::initialize(), inet::Ieee802154Mac::initialize(), inet::LMac::initialize(), inet::CsmaCaMac::initialize(), and inet::EthernetMacBase::initialize().
isInitializeStage()
virtual bool inet::MacProtocolBase::isInitializeStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == INITSTAGE_LINK_LAYER; }
isLowerMessage()
bool inet::MacProtocolBase::isLowerMessage (cMessage * message) const override protected virtual
Implements inet::LayeredProtocolBase.
 {
     return message->getArrivalGateId() == lowerLayerInGateId;
 }
isModuleStartStage()
virtual bool inet::MacProtocolBase::isModuleStartStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStartOperation::STAGE_LINK_LAYER; }
isModuleStopStage()
virtual bool inet::MacProtocolBase::isModuleStopStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStopOperation::STAGE_LINK_LAYER; }
isUpperMessage()
bool inet::MacProtocolBase::isUpperMessage (cMessage * message) const override protected virtual
Implements inet::LayeredProtocolBase.
 {
     return message->getArrivalGateId() == upperLayerInGateId;
 }
parseMacAddressParameter()
MacAddress inet::MacProtocolBase::parseMacAddressParameter (const char * addrstr) protected virtual
 {
     MacAddress address;
     if (!strcmp(addrstr, "auto"))
         // assign automatic address
         address = MacAddress::generateAutoAddress();
     else
         address.setAddress(addrstr);
     return address;
 }
Referenced by inet::ShortcutMac::configureNetworkInterface().
receiveSignal()
void inet::MacProtocolBase::receiveSignal (cComponent * source, simsignal_t signalID, cObject * obj, cObject * details) override protected virtual
Reimplemented in inet::EthernetMacBase, and inet::Ppp.
 {
     Enter_Method("%s", cComponent::getSignalName(signalID));
 }
Referenced by inet::Ppp::receiveSignal(), and inet::EthernetMacBase::receiveSignal().
registerInterface()
void inet::MacProtocolBase::registerInterface () protected virtual
 {
     ASSERT(networkInterface == nullptr);
     networkInterface = getContainingNicModule(this);
     configureNetworkInterface();
 }
Referenced by initialize().
sendDown()
void inet::MacProtocolBase::sendDown (cMessage * message) protected virtual
 {
     if (message->isPacket())
         emit(packetSentToLowerSignal, message);
     send(message, lowerLayerOutGateId);
 }
sendUp()
void inet::MacProtocolBase::sendUp (cMessage * message) protected virtual
Reimplemented in inet::ieee80211::Ieee80211Mac.
 {
     if (message->isPacket())
         emit(packetSentToUpperSignal, message);
     send(message, upperLayerOutGateId);
 }
Referenced by inet::ShortcutMac::receiveFromPeer(), and inet::ieee80211::Ieee80211Mac::sendUp().
Member Data Documentation
currentTxFrame
Packet* inet::MacProtocolBase::currentTxFrame = nullptr protected
Currently transmitted frame if any.
Referenced by inet::EthernetMac::beginSendFrames(), inet::EthernetCsmaMac::beginSendFrames(), deleteCurrentTxFrame(), dropCurrentTxFrame(), inet::EthernetMac::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleCanPullPacketChanged(), inet::Ppp::handleCanPullPacketChanged(), inet::EthernetCsmaMac::handleEndBackoffPeriod(), inet::EthernetMac::handleEndIFGPeriod(), inet::EthernetCsmaMac::handleEndIFGPeriod(), inet::EthernetMac::handleEndPausePeriod(), inet::EthernetMac::handleEndTxPeriod(), inet::EthernetCsmaMac::handleEndTxPeriod(), handleStopOperation(), inet::EthernetMacBase::handleStopOperation(), inet::EthernetMac::handleUpperPacket(), inet::Ppp::handleUpperPacket(), inet::EthernetCsmaMac::handleUpperPacket(), initialize(), inet::EthernetMacBase::processAtHandleMessageFinished(), inet::EthernetMacBase::processConnectDisconnect(), inet::EthernetMac::processMsgFromNetwork(), inet::Ppp::refreshOutGateConnection(), inet::EthernetMac::scheduleEndIFGPeriod(), inet::EthernetMac::scheduleEndPausePeriod(), inet::EthernetMac::startFrameTransmission(), inet::EthernetCsmaMac::startFrameTransmission(), inet::Ppp::startTransmitting(), and ~MacProtocolBase().
hostModule
opp_component_ptr<cModule> inet::MacProtocolBase::hostModule protected
Referenced by initialize().
lowerLayerInGateId
int inet::MacProtocolBase::lowerLayerInGateId = -1 protected
Referenced by handleMessageWhenDown(), inet::Tun::initialize(), inet::Loopback::initialize(), initialize(), inet::Ppp::initialize(), inet::EthernetMacBase::initialize(), and isLowerMessage().
lowerLayerOutGateId
int inet::MacProtocolBase::lowerLayerOutGateId = -1 protected
Referenced by inet::Tun::initialize(), inet::Loopback::initialize(), initialize(), inet::Ppp::initialize(), inet::EthernetMacBase::initialize(), and sendDown().
networkInterface
opp_component_ptr<NetworkInterface> inet::MacProtocolBase::networkInterface protected
Referenced by inet::Tun::configureNetworkInterface(), inet::Loopback::configureNetworkInterface(), inet::ShortcutMac::configureNetworkInterface(), inet::Ppp::configureNetworkInterface(), inet::EthernetMacBase::configureNetworkInterface(), inet::Ppp::decapsulate(), handleCrashOperation(), inet::EthernetMacBase::handleCrashOperation(), inet::Ppp::handleMessageWhenUp(), handleStartOperation(), inet::EthernetMacBase::handleStartOperation(), inet::Ppp::handleStopOperation(), handleStopOperation(), inet::EthernetMacBase::handleStopOperation(), inet::Tun::handleUpperPacket(), inet::Loopback::handleUpperPacket(), inet::EthernetMacBase::processAtHandleMessageFinished(), inet::EthernetMac::processReceivedDataFrame(), inet::EthernetCsmaMac::processReceivedDataFrame(), inet::EthernetMacBase::readChannelParameters(), inet::ShortcutMac::receiveFromPeer(), inet::Ppp::refreshOutGateConnection(), and registerInterface().
txQueue
opp_component_ptr<queueing::IPacketQueue> inet::MacProtocolBase::txQueue protected
Messages received from upper layer and to be transmitted later.
Referenced by inet::EthernetCsmaMac::canContinueBurst(), canDequeuePacket(), clearQueue(), dequeuePacket(), flushQueue(), inet::Ppp::getProvider(), inet::EthernetMacBase::getProvider(), inet::Ppp::handleMessageWhenUp(), inet::Ppp::handleStopOperation(), inet::EthernetMacBase::handleStopOperation(), inet::Ppp::initialize(), inet::EthernetMacBase::initialize(), inet::EthernetCsmaMac::printState(), inet::EthernetMacBase::processAtHandleMessageFinished(), inet::Ppp::refreshDisplay(), and inet::EthernetMacBase::refreshDisplay().
upperLayerInGateId
int inet::MacProtocolBase::upperLayerInGateId = -1 protected
Gate ids.
Referenced by inet::EthernetCsmaMac::canContinueBurst(), canDequeuePacket(), dequeuePacket(), inet::Ppp::getProvider(), inet::EthernetMacBase::getProvider(), inet::EthernetMac::handleMessageWhenUp(), inet::EthernetCsmaMac::handleMessageWhenUp(), initialize(), inet::Ppp::initialize(), inet::EthernetMacBase::initialize(), and isUpperMessage().
upperLayerOutGateId
int inet::MacProtocolBase::upperLayerOutGateId = -1 protected
Referenced by inet::Loopback::handleUpperPacket(), initialize(), inet::EthernetMac::processReceivedDataFrame(), and sendUp().
The documentation for this class was generated from the following files:
MacProtocolBase.h
MacProtocolBase.cc