INET Framework for OMNeT++/OMNEST: inet::physicallayer::CommunicationLog Class Reference
inet::physicallayer::CommunicationLog Class Reference
#include <CommunicationLog.h>
Public Member Functions
virtual void open ()
virtual void close ()
virtual void writeTransmission (const IRadio *transmitter, const IWirelessSignal *signal)
virtual void writeReception (const IRadio *receiver, const IWirelessSignal *signal)
Protected Attributes
std::ofstream output
Member Function Documentation
close()
void inet::physicallayer::CommunicationLog::close () virtual
 {
     output.close();
 }
Referenced by inet::physicallayer::RadioMedium::~RadioMedium().
open()
void inet::physicallayer::CommunicationLog::open () virtual
 {
     output.open(getEnvir()->getConfig()->substituteVariables("${resultdir}/${configname}-${runnumber}.tlog"));
 }
Referenced by inet::physicallayer::RadioMedium::initialize().
writeReception()
void inet::physicallayer::CommunicationLog::writeReception (const IRadio * receiver, const IWirelessSignal * signal) virtual
 {
     const ITransmission *transmission = signal->getTransmission();
     const IReception *reception = signal->getReception();
     const Radio *receiverRadio = check_and_cast<const Radio *>(receiver);
     output << "R " << receiverRadio->getFullPath() << " " << reception->getReceiver()->getId() << " "
            << "M " << check_and_cast<const WirelessSignal *>(signal)->getName() << " " << transmission->getId() << " "
            << "S " << reception->getStartTime() << " " << reception->getStartPosition() << " -> "
            << "E " << reception->getEndTime() << " " << reception->getEndPosition() << endl;
 }
Referenced by inet::physicallayer::RadioMedium::receivePacket().
writeTransmission()
void inet::physicallayer::CommunicationLog::writeTransmission (const IRadio * transmitter, const IWirelessSignal * signal) virtual
 {
     const ITransmission *transmission = signal->getTransmission();
     const Radio *transmitterRadio = check_and_cast<const Radio *>(transmitter);
     output << "T " << transmitterRadio->getFullPath() << " " << transmitterRadio->getId() << " "
            << "M " << check_and_cast<const WirelessSignal *>(signal)->getName() << " " << transmission->getId() << " "
            << "S " << transmission->getStartTime() << " " << transmission->getStartPosition() << " -> "
            << "E " << transmission->getEndTime() << " " << transmission->getEndPosition() << endl;
 }
Referenced by inet::physicallayer::RadioMedium::transmitPacket().
Member Data Documentation
output
std::ofstream inet::physicallayer::CommunicationLog::output protected
Referenced by close(), open(), writeReception(), and writeTransmission().
The documentation for this class was generated from the following files:
CommunicationLog.h
CommunicationLog.cc