INET Framework for OMNeT++/OMNEST: inet::InterfaceTagBase Class Reference
inet::InterfaceTagBase Class Reference
Class generated from inet/linklayer/common/InterfaceTag.msg:13 by opp_msgtool.
#include <InterfaceTag_m.h>
Public Member Functions
InterfaceTagBase ()
InterfaceTagBase (const InterfaceTagBase &other)
virtual ~InterfaceTagBase ()
InterfaceTagBase & operator= (const InterfaceTagBase &other)
virtual InterfaceTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual int getInterfaceId () const
virtual void setInterfaceId (int interfaceId)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const InterfaceTagBase &)=delete
Protected Attributes
int interfaceId = -1
Private Member Functions
void copy (const InterfaceTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/linklayer/common/InterfaceTag.msg:13 by opp_msgtool.
class InterfaceTagBase extends TagBase
{
    int interfaceId = -1; // a locally unique (network node) identifier that determines the interface registered in the ~InterfaceTable
}
Constructor & Destructor Documentation
InterfaceTagBase() [1/2]
inet::InterfaceTagBase::InterfaceTagBase ()
InterfaceTagBase() [2/2]
inet::InterfaceTagBase::InterfaceTagBase (const InterfaceTagBase & other)
~InterfaceTagBase()
virtual inet::InterfaceTagBase::~InterfaceTagBase () virtual
Member Function Documentation
copy()
void inet::InterfaceTagBase::copy (const InterfaceTagBase & other) private
dup()
virtual InterfaceTagBase* inet::InterfaceTagBase::dup () const inline override virtual
Reimplemented in inet::InterfaceInd, and inet::InterfaceReq.
 {return new InterfaceTagBase(*this);}
getInterfaceId()
virtual int inet::InterfaceTagBase::getInterfaceId () const virtual
Referenced by inet::CloudDelayerBase::datagramForwardHook(), inet::NetfilterInfoHook::datagramForwardHook(), inet::NetfilterInfoHook::datagramPostRoutingHook(), inet::NetfilterInfoHook::datagramPreRoutingHook(), inet::Ipv6Tunneling::decapsulateDatagram(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv4::fragmentAndSend(), inet::Ipv6::fragmentPostRouting(), inet::Ipv4::fragmentPostRouting(), inet::MacRelayUnit::handleLowerPacket(), inet::Ieee8021dRelay::handleLowerPacket(), inet::ospfv3::Ospfv3Splitter::handleMessage(), inet::MessageDispatcher::handleMessage(), inet::MessageDispatcher::handlePacket(), inet::NextHopForwarding::handlePacketFromNetwork(), inet::Ipv4::preroutingFinish(), inet::Arp::processArpPacket(), inet::xMIPv6::processCoTMessage(), inet::Icmpv6::processEchoRequest(), inet::PimDm::processGraftPacket(), inet::Igmpv2::processIgmpMessage(), inet::PimSm::processJoinPrunePacket(), inet::Ipv6NeighbourDiscovery::processNaPacket(), inet::Ipv6NeighbourDiscovery::processNsPacket(), inet::RelayInterfaceLearner::processPacket(), inet::Gptp::processPdelayReq(), inet::PimSplitter::processPIMPacket(), inet::Igmpv3::processQuery(), inet::Ipv6NeighbourDiscovery::processRaForRouterUpdates(), inet::Ipv6NeighbourDiscovery::processRaPacket(), inet::Igmpv3::processReport(), inet::Ipv6NeighbourDiscovery::processRsPacket(), inet::Ipv4::sendDatagramToOutput(), inet::PimDm::sendGraftAckPacket(), inet::Ipv4::sendPacketToNIC(), and inet::xMIPv6::validateCoTMessage().
operator=()
InterfaceTagBase& inet::InterfaceTagBase::operator= (const InterfaceTagBase & other)
operator==()
bool inet::InterfaceTagBase::operator== (const InterfaceTagBase &) protected delete
parsimPack()
virtual void inet::InterfaceTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::InterfaceInd, and inet::InterfaceReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::InterfaceTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::InterfaceInd, and inet::InterfaceReq.
Referenced by inet::doParsimUnpacking().
setInterfaceId()
virtual void inet::InterfaceTagBase::setInterfaceId (int interfaceId) virtual
Referenced by inet::NextHopForwarding::decapsulate(), and inet::Ieee8022LlcSocket::sendOut().
Member Data Documentation
interfaceId
int inet::InterfaceTagBase::interfaceId = -1 protected
The documentation for this class was generated from the following file:
InterfaceTag_m.h