INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase Class Reference
inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase Class Reference
#include <Ieee80211OfdmMode.h>
Public Member Functions
Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing)
Hz getSubcarrierFrequencySpacing () const
const simtime_t getFFTTransformPeriod () const
const simtime_t getGIDuration () const
const simtime_t getSymbolInterval () const
const Hz getChannelSpacing () const
Protected Attributes
Hz channelSpacing
Constructor & Destructor Documentation
Ieee80211OfdmTimingRelatedParametersBase()
inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing) inline
 : channelSpacing(channelSpacing) {}
Member Function Documentation
getChannelSpacing()
const Hz inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::getChannelSpacing () const inline
 { return channelSpacing; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::getCarrierSpacing().
getFFTTransformPeriod()
const simtime_t inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::getFFTTransformPeriod () const inline
 { return simtime_t(1 / getSubcarrierFrequencySpacing().get()); }
getGIDuration()
const simtime_t inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::getGIDuration () const inline
 { return getFFTTransformPeriod() / 4; }
getSubcarrierFrequencySpacing()
Hz inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::getSubcarrierFrequencySpacing () const inline
 { return channelSpacing / 64; }
getSymbolInterval()
const simtime_t inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::getSymbolInterval () const inline
 { return getGIDuration() + getFFTTransformPeriod(); }
Referenced by inet::physicallayer::Ieee80211OfdmModeBase::computeGrossBitrate(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), and inet::physicallayer::Ieee80211OfdmDataMode::getDuration().
Member Data Documentation
channelSpacing
Hz inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase::channelSpacing protected
Referenced by inet::physicallayer::Ieee80211OfdmMode::getCcaTime(), inet::physicallayer::Ieee80211OfdmMode::getPhyRxStartDelay(), inet::physicallayer::Ieee80211OfdmMode::getSifsTime(), and inet::physicallayer::Ieee80211OfdmMode::getSlotTime().
The documentation for this class was generated from the following file:
Ieee80211OfdmMode.h