INET Framework for OMNeT++/OMNEST: inet::Ipv6ExtHeaderTagBase Class Reference
inet::Ipv6ExtHeaderTagBase Class Reference
Class generated from inet/networklayer/ipv6/Ipv6ExtHeaderTag.msg:18 by opp_msgtool.
#include <Ipv6ExtHeaderTag_m.h>
Public Member Functions
Ipv6ExtHeaderTagBase ()
Ipv6ExtHeaderTagBase (const Ipv6ExtHeaderTagBase &other)
virtual ~Ipv6ExtHeaderTagBase ()
Ipv6ExtHeaderTagBase & operator= (const Ipv6ExtHeaderTagBase &other)
virtual Ipv6ExtHeaderTagBase * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual void setExtensionHeaderArraySize (size_t size)
virtual size_t getExtensionHeaderArraySize () const
virtual const Ipv6ExtensionHeader * getExtensionHeader (size_t k) const
virtual Ipv6ExtensionHeader * getExtensionHeaderForUpdate (size_t k)
virtual void setExtensionHeader (size_t k, Ipv6ExtensionHeader *extensionHeader)
virtual Ipv6ExtensionHeader * removeExtensionHeader (size_t k)
Ipv6ExtensionHeader * dropExtensionHeader (size_t k)
virtual void insertExtensionHeader (size_t k, Ipv6ExtensionHeader *extensionHeader)
void insertExtensionHeader (Ipv6ExtensionHeader *extensionHeader)
virtual void appendExtensionHeader (Ipv6ExtensionHeader *extensionHeader)
virtual void eraseExtensionHeader (size_t k)
Ipv6ExtensionHeader * removeFirstExtensionHeader ()
Remove the first extension header and return it.
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const Ipv6ExtHeaderTagBase &)=delete
Protected Attributes
Ipv6ExtensionHeader ** extensionHeader = nullptr
size_t extensionHeader_arraysize = 0
Private Member Functions
void copy (const Ipv6ExtHeaderTagBase &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/networklayer/ipv6/Ipv6ExtHeaderTag.msg:18 by opp_msgtool.
class Ipv6ExtHeaderTagBase extends TagBase
{
    Ipv6ExtensionHeader *extensionHeader[] @owned; // array of extension headers, subclassed from ~IPv6ExtensionHeader   //TODO IPv6ExtensionHeadersTag
}
Constructor & Destructor Documentation
Ipv6ExtHeaderTagBase() [1/2]
inet::Ipv6ExtHeaderTagBase::Ipv6ExtHeaderTagBase ()
Ipv6ExtHeaderTagBase() [2/2]
inet::Ipv6ExtHeaderTagBase::Ipv6ExtHeaderTagBase (const Ipv6ExtHeaderTagBase & other)
~Ipv6ExtHeaderTagBase()
virtual inet::Ipv6ExtHeaderTagBase::~Ipv6ExtHeaderTagBase () virtual
Member Function Documentation
appendExtensionHeader()
virtual void inet::Ipv6ExtHeaderTagBase::appendExtensionHeader (Ipv6ExtensionHeader * extensionHeader) virtual
copy()
void inet::Ipv6ExtHeaderTagBase::copy (const Ipv6ExtHeaderTagBase & other) private
dropExtensionHeader()
Ipv6ExtensionHeader* inet::Ipv6ExtHeaderTagBase::dropExtensionHeader (size_t k) inline
 {return removeExtensionHeader(k);}
dup()
virtual Ipv6ExtHeaderTagBase* inet::Ipv6ExtHeaderTagBase::dup () const inline override virtual
Reimplemented in inet::Ipv6ExtHeaderInd, and inet::Ipv6ExtHeaderReq.
 {return new Ipv6ExtHeaderTagBase(*this);}
eraseExtensionHeader()
virtual void inet::Ipv6ExtHeaderTagBase::eraseExtensionHeader (size_t k) virtual
Referenced by removeFirstExtensionHeader().
getExtensionHeader()
virtual const Ipv6ExtensionHeader* inet::Ipv6ExtHeaderTagBase::getExtensionHeader (size_t k) const virtual
getExtensionHeaderArraySize()
virtual size_t inet::Ipv6ExtHeaderTagBase::getExtensionHeaderArraySize () const virtual
getExtensionHeaderForUpdate()
virtual Ipv6ExtensionHeader* inet::Ipv6ExtHeaderTagBase::getExtensionHeaderForUpdate (size_t k) inline virtual
 { return const_cast<Ipv6ExtensionHeader *>(const_cast<Ipv6ExtHeaderTagBase*>(this)->getExtensionHeader(k));}
insertExtensionHeader() [1/2]
void inet::Ipv6ExtHeaderTagBase::insertExtensionHeader (Ipv6ExtensionHeader * extensionHeader) inline
 {appendExtensionHeader(extensionHeader);}
insertExtensionHeader() [2/2]
virtual void inet::Ipv6ExtHeaderTagBase::insertExtensionHeader (size_t k, Ipv6ExtensionHeader * extensionHeader) virtual
operator=()
Ipv6ExtHeaderTagBase& inet::Ipv6ExtHeaderTagBase::operator= (const Ipv6ExtHeaderTagBase & other)
operator==()
bool inet::Ipv6ExtHeaderTagBase::operator== (const Ipv6ExtHeaderTagBase &) protected delete
parsimPack()
virtual void inet::Ipv6ExtHeaderTagBase::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::Ipv6ExtHeaderInd, and inet::Ipv6ExtHeaderReq.
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::Ipv6ExtHeaderTagBase::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::Ipv6ExtHeaderInd, and inet::Ipv6ExtHeaderReq.
Referenced by inet::doParsimUnpacking().
removeExtensionHeader()
virtual Ipv6ExtensionHeader* inet::Ipv6ExtHeaderTagBase::removeExtensionHeader (size_t k) virtual
Referenced by removeFirstExtensionHeader().
removeFirstExtensionHeader()
Ipv6ExtensionHeader * inet::Ipv6ExtHeaderTagBase::removeFirstExtensionHeader ()
Remove the first extension header and return it.
 {
     if (extensionHeader_arraysize == 0)
         return nullptr;
     Ipv6ExtensionHeader *ret = removeExtensionHeader(0);
     this->eraseExtensionHeader(0);
     return ret;
 }
setExtensionHeader()
virtual void inet::Ipv6ExtHeaderTagBase::setExtensionHeader (size_t k, Ipv6ExtensionHeader * extensionHeader) virtual
setExtensionHeaderArraySize()
virtual void inet::Ipv6ExtHeaderTagBase::setExtensionHeaderArraySize (size_t size) virtual
Member Data Documentation
extensionHeader
Ipv6ExtensionHeader* * inet::Ipv6ExtHeaderTagBase::extensionHeader = nullptr protected
extensionHeader_arraysize
size_t inet::Ipv6ExtHeaderTagBase::extensionHeader_arraysize = 0 protected
Referenced by removeFirstExtensionHeader().
The documentation for this class was generated from the following files:
Ipv6ExtHeaderTag_m.h
Ipv6ExtHeaderTagBase.cc