INET Framework for OMNeT++/OMNEST: inet::tcp::TcpOption Class Reference
inet::tcp::TcpOption Class Reference
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:102 by opp_msgtool.
#include <TcpHeader_m.h>
Public Member Functions
TcpOption ()
TcpOption (const TcpOption &other)
virtual ~TcpOption ()
TcpOption & operator= (const TcpOption &other)
virtual TcpOption * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual TcpOptionNumbers getKind () const
virtual void setKind (TcpOptionNumbers kind)
virtual unsigned short getLength () const
virtual void setLength (unsigned short length)
Protected Member Functions
bool operator== (const TcpOption &)=delete
Protected Attributes
TcpOptionNumbers kind = static_cast<inet::tcp::TcpOptionNumbers>(-1)
unsigned short length = 1
Private Member Functions
void copy (const TcpOption &other)
Detailed Description
Class generated from inet/transportlayer/tcp_common/TcpHeader.msg:102 by opp_msgtool.
// Header Options (optional):
class TcpOption extends cObject
{
    @packetData;
    TcpOptionNumbers kind;            // option kind
    unsigned short length = 1;                    // option length
}
Constructor & Destructor Documentation
TcpOption() [1/2]
inet::tcp::TcpOption::TcpOption ()
TcpOption() [2/2]
inet::tcp::TcpOption::TcpOption (const TcpOption & other)
~TcpOption()
virtual inet::tcp::TcpOption::~TcpOption () virtual
Member Function Documentation
copy()
void inet::tcp::TcpOption::copy (const TcpOption & other) private
dup()
virtual TcpOption* inet::tcp::TcpOption::dup () const inline override virtual
Reimplemented in inet::tcp::TcpOptionUnknown, inet::tcp::TcpOptionTimestamp, inet::tcp::TcpOptionSack, inet::tcp::TcpOptionSackPermitted, inet::tcp::TcpOptionWindowScale, inet::tcp::TcpOptionMaxSegmentSize, inet::tcp::TcpOptionNop, and inet::tcp::TcpOptionEnd.
 {return new TcpOption(*this);}
getKind()
virtual TcpOptionNumbers inet::tcp::TcpOption::getKind () const virtual
Referenced by inet::tcp::TcpConnection::getTSecr(), inet::tcp::TcpConnection::getTSval(), inet::tcp::TcpConnection::printSegmentBrief(), inet::tcp::TcpConnection::readHeaderOptions(), and inet::tcp::TcpHeaderSerializer::serializeOption().
getLength()
virtual unsigned short inet::tcp::TcpOption::getLength () const virtual
Referenced by inet::tcp::TcpHeader::getHeaderOptionArrayLength(), inet::tcp::TcpConnection::processMSSOption(), inet::tcp::TcpConnection::processSACKOption(), inet::tcp::TcpConnection::processSACKPermittedOption(), inet::tcp::TcpConnection::processTSOption(), inet::tcp::TcpConnection::processWSOption(), inet::tcp::TcpConnection::readHeaderOptions(), inet::tcp::TcpHeaderSerializer::serialize(), and inet::tcp::TcpHeaderSerializer::serializeOption().
operator=()
TcpOption& inet::tcp::TcpOption::operator= (const TcpOption & other)
operator==()
bool inet::tcp::TcpOption::operator== (const TcpOption &) protected delete
parsimPack()
virtual void inet::tcp::TcpOption::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Reimplemented in inet::tcp::TcpOptionUnknown, inet::tcp::TcpOptionTimestamp, inet::tcp::TcpOptionSack, inet::tcp::TcpOptionSackPermitted, inet::tcp::TcpOptionWindowScale, inet::tcp::TcpOptionMaxSegmentSize, inet::tcp::TcpOptionNop, and inet::tcp::TcpOptionEnd.
Referenced by inet::tcp::doParsimPacking().
parsimUnpack()
virtual void inet::tcp::TcpOption::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Reimplemented in inet::tcp::TcpOptionUnknown, inet::tcp::TcpOptionTimestamp, inet::tcp::TcpOptionSack, inet::tcp::TcpOptionSackPermitted, inet::tcp::TcpOptionWindowScale, inet::tcp::TcpOptionMaxSegmentSize, inet::tcp::TcpOptionNop, and inet::tcp::TcpOptionEnd.
Referenced by inet::tcp::doParsimUnpacking().
setKind()
virtual void inet::tcp::TcpOption::setKind (TcpOptionNumbers kind) virtual
setLength()
virtual void inet::tcp::TcpOption::setLength (unsigned short length) virtual
Referenced by inet::tcp::TcpConnection::addSacks().
Member Data Documentation
kind
TcpOptionNumbers inet::tcp::TcpOption::kind = static_cast<inet::tcp::TcpOptionNumbers>(-1) protected
length
unsigned short inet::tcp::TcpOption::length = 1 protected
The documentation for this class was generated from the following file:
TcpHeader_m.h