INET Framework for OMNeT++/OMNEST: inet::ospfv3::Ospfv3RoutingTableEntry Class Reference
inet::ospfv3::Ospfv3RoutingTableEntry Class Reference
#include <Ospfv3RoutingTableEntry.h>
Public Types
enum RoutingPathType { INTRAAREA = 0, INTERAREA = 1, TYPE1_EXTERNAL = 2, TYPE2_EXTERNAL = 3 }
typedef unsigned char RoutingDestinationType
Public Types inherited from inet::Ipv6Route
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances (includes Ipv4 protocols)
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Public Member Functions
Ospfv3RoutingTableEntry (const Ospfv3RoutingTableEntry &entry, Ipv6Address destPrefix, int prefixLength, SourceType sourceType)
Ospfv3RoutingTableEntry (IInterfaceTable *ift, Ipv6Address destPrefix, int prefixLength, SourceType sourceType)
virtual ~Ospfv3RoutingTableEntry ()
bool operator== (const Ospfv3RoutingTableEntry &entry) const
bool operator!= (const Ospfv3RoutingTableEntry &entry) const
void setDestinationType (RoutingDestinationType type)
RoutingDestinationType getDestinationType () const
void setOptionalCapabilities (Ospfv3Options options)
Ospfv3Options getOptionalCapabilities () const
void setArea (AreaID source)
AreaID getArea () const
void setPathType (RoutingPathType type)
RoutingPathType getPathType () const
void setCost (Metric pathCost)
Metric getCost () const
void setType2Cost (Metric pathCost)
Metric getType2Cost () const
void setLinkStateOrigin (const Ospfv3Lsa *lsa)
const Ospfv3Lsa * getLinkStateOrigin () const
void addNextHop (NextHop hop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
Public Member Functions inherited from inet::Ipv6Route
Ipv6Route (Ipv6Address destPrefix, int prefixLength, SourceType sourceType)
Constructor.
virtual ~Ipv6Route ()
virtual std::string str () const override
virtual std::string detailedInfo () const
virtual void setRoutingTable (Ipv6RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
Ipv6RoutingTable * getRoutingTable () const
void setNextHop (const Ipv6Address &nextHop)
void setExpiryTime (simtime_t expiryTime)
void setMetric (int metric) override
void setAdminDist (unsigned int adminDist) override
const Ipv6Address & getDestPrefix () const
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual SourceType getSourceType () const override
Source type of the route.
const Ipv6Address & getNextHop () const
simtime_t getExpiryTime () const
virtual int getMetric () const override
Cost to reach the destination.
unsigned int getAdminDist () const
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int prefixLength) override
virtual void setNextHop (const L3Address &nextHop) override
virtual void setSource (cObject *source) override
virtual void setSourceType (SourceType type) override
const char * getSourceTypeAbbreviation () const
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
virtual NetworkInterface * getInterface () const override
Next hop interface.
virtual void setInterface (NetworkInterface *ie) override
virtual cObject * getSource () const override
Source of route.
virtual cObject * getProtocolData () const override
virtual void setProtocolData (cObject *protocolData) override
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
Static Public Attributes
static const unsigned char NETWORK_DESTINATION = 0
static const unsigned char AREA_BORDER_ROUTER_DESTINATION = 1
static const unsigned char AS_BOUNDARY_ROUTER_DESTINATION = 2
Private Attributes
IInterfaceTable * ift = nullptr
RoutingDestinationType destinationType = 0
Ospfv3Options optionalCapabilities
AreaID area
RoutingPathType pathType = (RoutingPathType) - 1
Metric cost = 0
Metric type2Cost = 0
const Ospfv3Lsa * linkStateOrigin = nullptr
std::vector< NextHop > nextHops
Additional Inherited Members
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Protected Member Functions inherited from inet::Ipv6Route
void changed (int fieldCode)
Routing Protocol specific data.
Protected Attributes inherited from inet::Ipv6Route
Ipv6RoutingTable * _rt
Ipv6Address _destPrefix
short _prefixLength
SourceType _sourceType
NetworkInterface * _interfacePtr
Ipv6Address _nextHop
simtime_t _expiryTime
int _metric
unsigned int _adminDist
cObject * _source
cObject * _protocolData
Object identifying the source.
Member Typedef Documentation
RoutingDestinationType
typedef unsigned char inet::ospfv3::Ospfv3RoutingTableEntry::RoutingDestinationType
Member Enumeration Documentation
RoutingPathType
enum inet::ospfv3::Ospfv3RoutingTableEntry::RoutingPathType
Enumerator
INTRAAREA
INTERAREA
TYPE1_EXTERNAL
TYPE2_EXTERNAL
{
         INTRAAREA      = 0,
         INTERAREA      = 1,
         TYPE1_EXTERNAL = 2,
         TYPE2_EXTERNAL = 3
     };
Constructor & Destructor Documentation
Ospfv3RoutingTableEntry() [1/2]
inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry (const Ospfv3RoutingTableEntry & entry, Ipv6Address destPrefix, int prefixLength, SourceType sourceType)
                                                                                                                                                       :
     Ipv6Route(destPrefix, prefixLength, sourceType),
     destinationType(entry.destinationType),
     optionalCapabilities(entry.optionalCapabilities),
     area(entry.area),
     pathType(entry.pathType),
     cost(entry.cost),
     type2Cost(entry.type2Cost),
     linkStateOrigin(entry.linkStateOrigin),
     nextHops(entry.nextHops)
 {
     this->setDestination(entry.getDestinationAsGeneric());
     this->setPrefixLength(prefixLength);
     this->setInterface(entry.getInterface());
     this->setSourceType(entry.getSourceType());
     this->setMetric(entry.getMetric());
 }
Ospfv3RoutingTableEntry() [2/2]
inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry (IInterfaceTable * ift, Ipv6Address destPrefix, int prefixLength, SourceType sourceType)
                                                                                                                                       :
     Ipv6Route(destPrefix, prefixLength, sourceType),
     ift(ift),
     area(BACKBONE_AREAID),
     pathType(Ospfv3RoutingTableEntry::INTRAAREA)
 {
     this->setPrefixLength(prefixLength);
     this->setSourceType(IRoute::OSPF);
 }
~Ospfv3RoutingTableEntry()
virtual inet::ospfv3::Ospfv3RoutingTableEntry::~Ospfv3RoutingTableEntry () inline virtual
 {}
Member Function Documentation
addNextHop()
void inet::ospfv3::Ospfv3RoutingTableEntry::addNextHop (NextHop hop)
 {
     if (nextHops.size() == 0) {
         NetworkInterface *routingInterface = ift->getInterfaceById(hop.ifIndex);
         setInterface(routingInterface);
         // TODO this used to be commented out, but it seems we need it
         // otherwise gateways will never be filled in and gateway is needed for broadcast networks
 //        setGateway(hop.hopAddress);
     }
     nextHops.push_back(hop);
 }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
clearNextHops()
void inet::ospfv3::Ospfv3RoutingTableEntry::clearNextHops () inline
 { nextHops.clear(); }
Referenced by inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getArea()
AreaID inet::ospfv3::Ospfv3RoutingTableEntry::getArea () const inline
 { return area; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getCost()
Metric inet::ospfv3::Ospfv3RoutingTableEntry::getCost () const inline
 { return cost; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getDestinationType()
RoutingDestinationType inet::ospfv3::Ospfv3RoutingTableEntry::getDestinationType () const inline
 { return destinationType; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getLinkStateOrigin()
const Ospfv3Lsa* inet::ospfv3::Ospfv3RoutingTableEntry::getLinkStateOrigin () const inline
 { return linkStateOrigin; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::operator<<().
getNextHop()
NextHop inet::ospfv3::Ospfv3RoutingTableEntry::getNextHop (unsigned int index) const inline
 { return nextHops[index]; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getNextHopCount()
unsigned int inet::ospfv3::Ospfv3RoutingTableEntry::getNextHopCount () const inline
 { return nextHops.size(); }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getOptionalCapabilities()
Ospfv3Options inet::ospfv3::Ospfv3RoutingTableEntry::getOptionalCapabilities () const inline
 { return optionalCapabilities; }
getPathType()
RoutingPathType inet::ospfv3::Ospfv3RoutingTableEntry::getPathType () const inline
 { return pathType; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
getType2Cost()
Metric inet::ospfv3::Ospfv3RoutingTableEntry::getType2Cost () const inline
 { return type2Cost; }
Referenced by inet::ospfv3::operator<<().
operator!=()
bool inet::ospfv3::Ospfv3RoutingTableEntry::operator!= (const Ospfv3RoutingTableEntry & entry) const inline
 { return !((*this) == entry); }
operator==()
bool inet::ospfv3::Ospfv3RoutingTableEntry::operator== (const Ospfv3RoutingTableEntry & entry) const
 {
     unsigned int hopCount = nextHops.size();
     unsigned int i = 0;
     if (hopCount != entry.nextHops.size()) {
         return false;
     }
     for (i = 0; i < hopCount; i++) {
         if ((nextHops[i] != entry.nextHops[i])) {
             return false;
         }
     }
     return (this->destinationType == entry.destinationType) &&
            (this->getDestinationAsGeneric() == entry.getDestinationAsGeneric()) &&
            (this->getPrefixLength() == entry.getPrefixLength()) &&
            (this->optionalCapabilities == entry.optionalCapabilities) &&
            (this->area == entry.area) &&
            (this->pathType == entry.pathType) &&
            (this->cost == entry.cost) &&
            (this->type2Cost == entry.type2Cost) &&
            (this->linkStateOrigin == entry.linkStateOrigin);
 }
setArea()
void inet::ospfv3::Ospfv3RoutingTableEntry::setArea (AreaID source) inline
 { area = source; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setCost()
void inet::ospfv3::Ospfv3RoutingTableEntry::setCost (Metric pathCost)
 {
     cost = pathCost;
     // FIXME this is a hack. But the correct way to do it is to implement a separate IIPv4RoutingTable module for OSPF...
     if (pathType == Ospfv3RoutingTableEntry::TYPE2_EXTERNAL) {
         setMetric(cost + type2Cost * 1000);
     }
     else {
         setMetric(cost);
     }
 }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setDestinationType()
void inet::ospfv3::Ospfv3RoutingTableEntry::setDestinationType (RoutingDestinationType type) inline
 { destinationType = type; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setLinkStateOrigin()
void inet::ospfv3::Ospfv3RoutingTableEntry::setLinkStateOrigin (const Ospfv3Lsa * lsa) inline
 { linkStateOrigin = lsa; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setOptionalCapabilities()
void inet::ospfv3::Ospfv3RoutingTableEntry::setOptionalCapabilities (Ospfv3Options options) inline
 { optionalCapabilities = options; }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), and inet::ospfv3::Ospfv3Area::calculateShortestPathTree().
setPathType()
void inet::ospfv3::Ospfv3RoutingTableEntry::setPathType (RoutingPathType type)
 {
     pathType = type;
     // FIXME this is a hack. But the correct way to do it is to implement a separate IIPv4RoutingTable module for OSPF...
     if (pathType == Ospfv3RoutingTableEntry::TYPE2_EXTERNAL) {
         setMetric(cost + type2Cost * 1000);
     }
     else {
         setMetric(cost);
     }
 }
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), and inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA().
setType2Cost()
void inet::ospfv3::Ospfv3RoutingTableEntry::setType2Cost (Metric pathCost)
 {
     type2Cost = pathCost;
     // FIXME this is a hack. But the correct way to do it is to implement a separate IIPv4RoutingTable module for OSPF...
     if (pathType == Ospfv3RoutingTableEntry::TYPE2_EXTERNAL) {
         setMetric(cost + type2Cost * 1000);
     }
     else {
         setMetric(cost);
     }
 }
Member Data Documentation
area
AreaID inet::ospfv3::Ospfv3RoutingTableEntry::area private
Referenced by operator==().
AREA_BORDER_ROUTER_DESTINATION
const unsigned char inet::ospfv3::Ospfv3RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION = 1 static
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
AS_BOUNDARY_ROUTER_DESTINATION
const unsigned char inet::ospfv3::Ospfv3RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION = 2 static
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
cost
Metric inet::ospfv3::Ospfv3RoutingTableEntry::cost = 0 private
Referenced by operator==(), setCost(), setPathType(), and setType2Cost().
destinationType
RoutingDestinationType inet::ospfv3::Ospfv3RoutingTableEntry::destinationType = 0 private
Referenced by operator==().
ift
IInterfaceTable* inet::ospfv3::Ospfv3RoutingTableEntry::ift = nullptr private
Referenced by addNextHop().
linkStateOrigin
const Ospfv3Lsa* inet::ospfv3::Ospfv3RoutingTableEntry::linkStateOrigin = nullptr private
Referenced by operator==().
NETWORK_DESTINATION
const unsigned char inet::ospfv3::Ospfv3RoutingTableEntry::NETWORK_DESTINATION = 0 static
Referenced by inet::ospfv3::Ospfv3Area::addRouterEntry(), inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::createRoutingTableEntryFromInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
nextHops
std::vector<NextHop> inet::ospfv3::Ospfv3RoutingTableEntry::nextHops private
Referenced by addNextHop(), and operator==().
optionalCapabilities
Ospfv3Options inet::ospfv3::Ospfv3RoutingTableEntry::optionalCapabilities private
Referenced by operator==().
pathType
RoutingPathType inet::ospfv3::Ospfv3RoutingTableEntry::pathType = (RoutingPathType) - 1 private
Referenced by operator==(), setCost(), setPathType(), and setType2Cost().
type2Cost
Metric inet::ospfv3::Ospfv3RoutingTableEntry::type2Cost = 0 private
Referenced by operator==(), setCost(), setPathType(), and setType2Cost().
The documentation for this class was generated from the following files:
Ospfv3RoutingTableEntry.h
Ospfv3RoutingTableEntry.cc