INET Framework for OMNeT++/OMNEST: inet::ieee80211::TxopProcedure Class Reference
inet::ieee80211::TxopProcedure Class Reference
#include <TxopProcedure.h>
Public Types
enum ProtectionMechanism { SINGLE_PROTECTION, MULTIPLE_PROTECTION, UNDEFINED_PROTECTION }
Public Member Functions
virtual void startTxop (AccessCategory ac)
virtual void endTxop ()
virtual simtime_t getStart () const
virtual simtime_t getLimit () const
virtual simtime_t getRemaining () const
virtual simtime_t getDuration () const
virtual bool isFinalFragment (const Ptr< const Ieee80211MacHeader > &header) const
virtual bool isTxopInitiator (const Ptr< const Ieee80211MacHeader > &header) const
virtual bool isTxopTerminator (const Ptr< const Ieee80211MacHeader > &header) const
virtual ProtectionMechanism getProtectionMechanism () const
Static Public Attributes
static simsignal_t txopStartedSignal = cComponent::registerSignal("txopStarted")
static simsignal_t txopEndedSignal = cComponent::registerSignal("txopEnded")
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual s getTxopLimit (const physicallayer::IIeee80211Mode *mode, AccessCategory ac)
virtual ProtectionMechanism selectProtectionMechanism (AccessCategory ac) const
Protected Member Functions inherited from inet::ieee80211::ModeSetListener
virtual void receiveSignal (cComponent *source, simsignal_t signalID, cObject *obj, cObject *details) override
Protected Attributes
simtime_t start = -1
simtime_t limit = -1
ProtectionMechanism protectionMechanism = ProtectionMechanism::UNDEFINED_PROTECTION
Protected Attributes inherited from inet::ieee80211::ModeSetListener
physicallayer::Ieee80211ModeSet * modeSet = nullptr
Member Enumeration Documentation
ProtectionMechanism
enum inet::ieee80211::TxopProcedure::ProtectionMechanism
Enumerator
SINGLE_PROTECTION
MULTIPLE_PROTECTION
UNDEFINED_PROTECTION
{
         SINGLE_PROTECTION,
         MULTIPLE_PROTECTION,
         UNDEFINED_PROTECTION
     };
Member Function Documentation
endTxop()
void inet::ieee80211::TxopProcedure::endTxop () virtual
 {
     Enter_Method("endTxop");
     emit(txopEndedSignal, this);
     start = -1;
     protectionMechanism = ProtectionMechanism::UNDEFINED_PROTECTION;
     EV_INFO << "Txop ended.\n";
 }
getDuration()
simtime_t inet::ieee80211::TxopProcedure::getDuration () const virtual
 {
     if (start == -1)
         throw cRuntimeError("Txop has not started yet");
     return simTime() - start;
 }
getLimit()
simtime_t inet::ieee80211::TxopProcedure::getLimit () const virtual
 {
     return limit;
 }
getProtectionMechanism()
virtual ProtectionMechanism inet::ieee80211::TxopProcedure::getProtectionMechanism () const inline virtual
 { return protectionMechanism; }
getRemaining()
simtime_t inet::ieee80211::TxopProcedure::getRemaining () const virtual
 {
     if (start == -1)
         throw cRuntimeError("Txop has not started yet");
     auto now = simTime();
     return now > start + limit ? 0 : now - start;
 }
Referenced by inet::ieee80211::HcfFs::hasMoreTxOps().
getStart()
simtime_t inet::ieee80211::TxopProcedure::getStart () const virtual
 {
     return start;
 }
getTxopLimit()
s inet::ieee80211::TxopProcedure::getTxopLimit (const physicallayer::IIeee80211Mode * mode, AccessCategory ac) protected virtual
 {
     switch (ac) {
         case AC_BK: return s(0);
         case AC_BE: return s(0);
         case AC_VI:
             if (dynamic_cast<const Ieee80211DsssMode *>(mode) || dynamic_cast<const Ieee80211HrDsssMode *>(mode)) return ms(6.016);
             else if (dynamic_cast<const Ieee80211HtMode *>(mode) || dynamic_cast<const Ieee80211OfdmMode *>(mode)) return ms(3.008);
             else return s(0);
         case AC_VO:
             if (dynamic_cast<const Ieee80211DsssMode *>(mode) || dynamic_cast<const Ieee80211HrDsssMode *>(mode)) return ms(3.264);
             else if (dynamic_cast<const Ieee80211HtMode *>(mode) || dynamic_cast<const Ieee80211OfdmMode *>(mode)) return ms(1.504);
             else return s(0);
         default: throw cRuntimeError("Unknown access category = %d", ac);
     }
 }
initialize()
void inet::ieee80211::TxopProcedure::initialize (int stage) override protected virtual
Reimplemented from inet::ieee80211::ModeSetListener.
 {
     ModeSetListener::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         limit = par("txopLimit");
         WATCH(start);
         WATCH(protectionMechanism);
     }
 }
isFinalFragment()
bool inet::ieee80211::TxopProcedure::isFinalFragment (const Ptr< const Ieee80211MacHeader > & header) const virtual
 {
     return false;
 }
Referenced by inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField().
isTxopInitiator()
bool inet::ieee80211::TxopProcedure::isTxopInitiator (const Ptr< const Ieee80211MacHeader > & header) const virtual
 {
     return false;
 }
Referenced by inet::ieee80211::QosRateSelection::computeControlFrameMode(), and inet::ieee80211::QosRateSelection::isControlResponseFrame().
isTxopTerminator()
bool inet::ieee80211::TxopProcedure::isTxopTerminator (const Ptr< const Ieee80211MacHeader > & header) const virtual
 {
     return false;
 }
Referenced by inet::ieee80211::QosRateSelection::computeControlFrameMode().
numInitStages()
virtual int inet::ieee80211::TxopProcedure::numInitStages () const inline override protected virtual
Reimplemented from inet::ieee80211::ModeSetListener.
 { return NUM_INIT_STAGES; }
selectProtectionMechanism()
TxopProcedure::ProtectionMechanism inet::ieee80211::TxopProcedure::selectProtectionMechanism (AccessCategory ac) const protected virtual
 {
     return ProtectionMechanism::SINGLE_PROTECTION;
 }
startTxop()
void inet::ieee80211::TxopProcedure::startTxop (AccessCategory ac) virtual
 {
     Enter_Method("startTxop");
     if (start != -1)
         throw cRuntimeError("Txop is already running");
     if (limit == -1) {
         auto referenceMode = modeSet->getSlowestMandatoryMode();
         limit = getTxopLimit(referenceMode, ac).get();
     }
     // The STA selects between single and multiple protection when it transmits the first frame of a TXOP.
     // All subsequent frames transmitted by the STA in the same TXOP use the same class of duration settings.
     protectionMechanism = selectProtectionMechanism(ac);
     start = simTime();
     emit(txopStartedSignal, this);
     EV_INFO << "Txop started: limit = " << limit << ".\n";
 }
Member Data Documentation
limit
simtime_t inet::ieee80211::TxopProcedure::limit = -1 protected
protectionMechanism
ProtectionMechanism inet::ieee80211::TxopProcedure::protectionMechanism = ProtectionMechanism::UNDEFINED_PROTECTION protected
start
simtime_t inet::ieee80211::TxopProcedure::start = -1 protected
txopEndedSignal
simsignal_t inet::ieee80211::TxopProcedure::txopEndedSignal = cComponent::registerSignal("txopEnded") static
txopStartedSignal
simsignal_t inet::ieee80211::TxopProcedure::txopStartedSignal = cComponent::registerSignal("txopStarted") static
The documentation for this class was generated from the following files:
TxopProcedure.h
TxopProcedure.cc