INET Framework for OMNeT++/OMNEST: inet::physicallayer::IModulation Class Reference
inet::physicallayer::IModulation Class Reference abstract
This interface represents the process of varying one or more physical properties of a periodic waveform, called the carrier signal, with a modulating signal that typically contains information to be transmitted.
#include <IModulation.h>
Public Member Functions
virtual double calculateBER (double snir, Hz bandwidth, bps bitrate) const =0
Returns the bit error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
virtual double calculateSER (double snir, Hz bandwidth, bps bitrate) const =0
Returns the symbol error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface represents the process of varying one or more physical properties of a periodic waveform, called the carrier signal, with a modulating signal that typically contains information to be transmitted.
Member Function Documentation
calculateBER()
virtual double inet::physicallayer::IModulation::calculateBER (double snir, Hz bandwidth, bps bitrate) const pure virtual
Returns the bit error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
Implemented in inet::physicallayer::BpskModulation, inet::physicallayer::QbpskModulation, inet::physicallayer::MfskModulation, inet::physicallayer::MqamModulationBase, inet::physicallayer::MaskModulation, inet::physicallayer::MpskModulation, inet::physicallayer::DsssOqpsk16Modulation, inet::physicallayer::DpskModulationBase, inet::physicallayer::GfskModulationBase, inet::physicallayer::PpmModulationBase, and inet::physicallayer::Ieee80211OfdmModulation.
Referenced by inet::physicallayer::Ieee80211OfdmModulation::calculateBER(), inet::physicallayer::ApskErrorModel::computeBitErrorRate(), inet::physicallayer::ApskLayeredErrorModel::computeBitModel(), and inet::physicallayer::ApskLayeredErrorModel::computePacketModel().
calculateSER()
virtual double inet::physicallayer::IModulation::calculateSER (double snir, Hz bandwidth, bps bitrate) const pure virtual
Returns the symbol error rate as a function of the signal to noise and interference ratio, the bandwidth, and the gross (physical) bitrate.
Implemented in inet::physicallayer::BpskModulation, inet::physicallayer::QbpskModulation, inet::physicallayer::MfskModulation, inet::physicallayer::MaskModulation, inet::physicallayer::MpskModulation, inet::physicallayer::MqamModulationBase, inet::physicallayer::DsssOqpsk16Modulation, inet::physicallayer::DpskModulationBase, inet::physicallayer::GfskModulationBase, inet::physicallayer::PpmModulationBase, and inet::physicallayer::Ieee80211OfdmModulation.
Referenced by inet::physicallayer::Ieee80211OfdmModulation::calculateSER(), inet::physicallayer::ApskErrorModel::computeSymbolErrorRate(), and inet::physicallayer::ApskLayeredErrorModel::computeSymbolModel().
The documentation for this class was generated from the following file:
IModulation.h