INET Framework for OMNeT++/OMNEST: inet::FragmentTag Class Reference
inet::FragmentTag Class Reference
Class generated from inet/protocolelement/fragmentation/tag/FragmentTag.msg:13 by opp_msgtool.
#include <FragmentTag_m.h>
Public Member Functions
FragmentTag ()
FragmentTag (const FragmentTag &other)
virtual ~FragmentTag ()
FragmentTag & operator= (const FragmentTag &other)
virtual FragmentTag * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual bool getFirstFragment () const
virtual void setFirstFragment (bool firstFragment)
virtual bool getLastFragment () const
virtual void setLastFragment (bool lastFragment)
virtual int getFragmentNumber () const
virtual void setFragmentNumber (int fragmentNumber)
virtual int getNumFragments () const
virtual void setNumFragments (int numFragments)
Public Member Functions inherited from inet::TagBase
virtual const Ptr< TagBase > dupShared () const
virtual const Ptr< TagBase > changeRegion (b offsetDelta, b lengthDelta) const
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags) const override
Prints this object to the provided output stream.
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags) const
virtual std::string str () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
bool operator== (const FragmentTag &)=delete
Protected Attributes
bool firstFragment = true
bool lastFragment = true
int fragmentNumber = 0
int numFragments = 1
Private Member Functions
void copy (const FragmentTag &other)
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Class generated from inet/protocolelement/fragmentation/tag/FragmentTag.msg:13 by opp_msgtool.
class FragmentTag extends TagBase
{
    bool firstFragment = true;
    bool lastFragment = true;
    int fragmentNumber = 0; // -1 means unspecified
    int numFragments = 1;   // -1 means unspecified
}
Constructor & Destructor Documentation
FragmentTag() [1/2]
inet::FragmentTag::FragmentTag ()
FragmentTag() [2/2]
inet::FragmentTag::FragmentTag (const FragmentTag & other)
~FragmentTag()
virtual inet::FragmentTag::~FragmentTag () virtual
Member Function Documentation
copy()
void inet::FragmentTag::copy (const FragmentTag & other) private
dup()
virtual FragmentTag* inet::FragmentTag::dup () const inline override virtual
 {return new FragmentTag(*this);}
getFirstFragment()
virtual bool inet::FragmentTag::getFirstFragment () const virtual
Referenced by inet::FragmentTagBasedDefragmenter::pushPacket().
getFragmentNumber()
virtual int inet::FragmentTag::getFragmentNumber () const virtual
Referenced by inet::FragmentNumberHeaderChecker::processPacket().
getLastFragment()
virtual bool inet::FragmentTag::getLastFragment () const virtual
Referenced by inet::FragmentNumberHeaderChecker::processPacket().
getNumFragments()
virtual int inet::FragmentTag::getNumFragments () const virtual
operator=()
FragmentTag& inet::FragmentTag::operator= (const FragmentTag & other)
operator==()
bool inet::FragmentTag::operator== (const FragmentTag &) protected delete
parsimPack()
virtual void inet::FragmentTag::parsimPack (omnetpp::cCommBuffer * b) const override virtual
Referenced by inet::doParsimPacking().
parsimUnpack()
virtual void inet::FragmentTag::parsimUnpack (omnetpp::cCommBuffer * b) override virtual
Referenced by inet::doParsimUnpacking().
setFirstFragment()
virtual void inet::FragmentTag::setFirstFragment (bool firstFragment) virtual
Referenced by inet::FragmentTagBasedFragmenter::createFragmentPacket(), inet::PreemptableStreamer::pullPacketEnd(), and inet::PreemptableStreamer::pullPacketStart().
setFragmentNumber()
virtual void inet::FragmentTag::setFragmentNumber (int fragmentNumber) virtual
Referenced by inet::FragmentNumberHeaderInserter::processPacket(), and inet::physicallayer::EthernetFragmentPhyHeaderInserter::processPacket().
setLastFragment()
virtual void inet::FragmentTag::setLastFragment (bool lastFragment) virtual
Referenced by inet::FragmentNumberHeaderInserter::processPacket(), and inet::PreemptableStreamer::pullPacketEnd().
setNumFragments()
virtual void inet::FragmentTag::setNumFragments (int numFragments) virtual
Member Data Documentation
firstFragment
bool inet::FragmentTag::firstFragment = true protected
fragmentNumber
int inet::FragmentTag::fragmentNumber = 0 protected
lastFragment
bool inet::FragmentTag::lastFragment = true protected
numFragments
int inet::FragmentTag::numFragments = 1 protected
The documentation for this class was generated from the following file:
FragmentTag_m.h