INET Framework for OMNeT++/OMNEST: inet::Ipv6Route Class Reference
inet::Ipv6Route Class Reference
Represents a route in the route table.
#include <Ipv6Route.h>
Public Types
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances (includes Ipv4 protocols)
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Public Member Functions
Ipv6Route (Ipv6Address destPrefix, int prefixLength, SourceType sourceType)
Constructor.
virtual ~Ipv6Route ()
virtual std::string str () const override
virtual std::string detailedInfo () const
virtual void setRoutingTable (Ipv6RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
Ipv6RoutingTable * getRoutingTable () const
void setNextHop (const Ipv6Address &nextHop)
void setExpiryTime (simtime_t expiryTime)
void setMetric (int metric) override
void setAdminDist (unsigned int adminDist) override
const Ipv6Address & getDestPrefix () const
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual SourceType getSourceType () const override
Source type of the route.
const Ipv6Address & getNextHop () const
simtime_t getExpiryTime () const
virtual int getMetric () const override
Cost to reach the destination.
unsigned int getAdminDist () const
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int prefixLength) override
virtual void setNextHop (const L3Address &nextHop) override
virtual void setSource (cObject *source) override
virtual void setSourceType (SourceType type) override
const char * getSourceTypeAbbreviation () const
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
virtual NetworkInterface * getInterface () const override
Next hop interface.
virtual void setInterface (NetworkInterface *ie) override
virtual cObject * getSource () const override
Source of route.
virtual cObject * getProtocolData () const override
virtual void setProtocolData (cObject *protocolData) override
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
Protected Member Functions
void changed (int fieldCode)
Routing Protocol specific data.
Protected Attributes
Ipv6RoutingTable * _rt
Ipv6Address _destPrefix
short _prefixLength
SourceType _sourceType
NetworkInterface * _interfacePtr
Ipv6Address _nextHop
simtime_t _expiryTime
int _metric
unsigned int _adminDist
cObject * _source
cObject * _protocolData
Object identifying the source.
Additional Inherited Members
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Detailed Description
Represents a route in the route table.
Routes with sourceType=ROUTER_ADVERTISEMENT represent on-link prefixes advertised by routers.
Member Enumeration Documentation
RouteAdminDist
enum inet::Ipv6Route::RouteAdminDist
Cisco like administrative distances (includes Ipv4 protocols)
Enumerator
dDirectlyConnected
dStatic
dEIGRPSummary
dBGPExternal
dEIGRPInternal
dIGRP
dOSPF
dISIS
dRIP
dEGP
dODR
dEIGRPExternal
dBGPInternal
dDHCPlearned
dBABEL
dLISP
dUnknown
{
         dDirectlyConnected = 0,
         dStatic            = 1,
         dEIGRPSummary      = 5,
         dBGPExternal       = 20,
         dEIGRPInternal     = 90,
         dIGRP              = 100,
         dOSPF              = 110,
         dISIS              = 115,
         dRIP               = 120,
         dEGP               = 140,
         dODR               = 160,
         dEIGRPExternal     = 170,
         dBGPInternal       = 200,
         dDHCPlearned       = 254,
         dBABEL             = 125,
         dLISP              = 210,
         dUnknown           = 255
     };
Constructor & Destructor Documentation
Ipv6Route()
inet::Ipv6Route::Ipv6Route (Ipv6Address destPrefix, int prefixLength, SourceType sourceType) inline
Constructor.
The destination prefix and the route source is passed to the constructor and cannot be changed afterwards.
     {
         _rt = nullptr;
         _destPrefix = destPrefix;
         _prefixLength = prefixLength;
         _sourceType = sourceType;
         _interfacePtr = nullptr;
         _expiryTime = 0;
         _metric = 0;
         _adminDist = dUnknown;
         _source = nullptr;
         _protocolData = nullptr;
     }
~Ipv6Route()
virtual inet::Ipv6Route::~Ipv6Route () inline virtual
 { delete _protocolData; }
Member Function Documentation
changed()
void inet::Ipv6Route::changed (int fieldCode) protected
Routing Protocol specific data.
 {
     if (_rt)
         _rt->routeChanged(this, fieldCode);
 }
detailedInfo()
std::string inet::Ipv6Route::detailedInfo () const virtual
 {
     return std::string();
 }
getAdminDist()
unsigned int inet::Ipv6Route::getAdminDist () const inline
 { return _adminDist; }
Referenced by getSourceTypeAbbreviation(), inet::eigrp::EigrpIpv6Pdm::isRTSafeForAdd(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), inet::Ipv6RoutingTable::routeLessThan(), and str().
getDestinationAsGeneric()
virtual L3Address inet::Ipv6Route::getDestinationAsGeneric () const inline override virtual
Destination address prefix to match.
Implements inet::IRoute.
 { return getDestPrefix(); } // TODO rename Ipv6 method
Referenced by inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3RoutingTableEntry::operator==(), and inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry().
getDestPrefix()
const Ipv6Address& inet::Ipv6Route::getDestPrefix () const inline
 { return _destPrefix; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), getSourceTypeAbbreviation(), inet::ospfv3::Ospfv3Process::isInRoutingTable6(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), and str().
getExpiryTime()
simtime_t inet::Ipv6Route::getExpiryTime () const inline
 { return _expiryTime; }
Referenced by inet::Ipv6NeighbourDiscovery::determineNextHop(), and inet::Ipv6::determineOutputInterface().
getInterface()
virtual NetworkInterface* inet::Ipv6Route::getInterface () const inline override virtual
Next hop interface.
Implements inet::IRoute.
 { return _interfacePtr; }
Referenced by inet::Ipv6RoutingTable::deleteInterfaceRoutes(), inet::Ipv6NeighbourDiscovery::determineNextHop(), inet::Ipv6::determineOutputInterface(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), and str().
getMetric()
virtual int inet::Ipv6Route::getMetric () const inline override virtual
Cost to reach the destination.
Implements inet::IRoute.
 { return _metric; }
Referenced by inet::eigrp::EigrpIpv6Pdm::installRouteToRT(), inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry(), inet::Ipv6RoutingTable::routeLessThan(), and str().
getNextHop()
const Ipv6Address& inet::Ipv6Route::getNextHop () const inline
 { return _nextHop; }
Referenced by inet::Ipv6NeighbourDiscovery::determineNextHop(), inet::Ipv6::determineOutputInterface(), inet::eigrp::EigrpIpv6Pdm::processIfaceStateChange(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), and str().
getNextHopAsGeneric()
virtual L3Address inet::Ipv6Route::getNextHopAsGeneric () const inline override virtual
Next hop address.
Implements inet::IRoute.
 { return getNextHop(); }
getPrefixLength()
virtual int inet::Ipv6Route::getPrefixLength () const inline override virtual
Represents length of prefix to match.
Implements inet::IRoute.
 { return _prefixLength; }
Referenced by inet::ospfv3::Ospfv3Area::calculateInterAreaRoutes(), inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute(), inet::ospfv3::Ospfv3Process::isInRoutingTable6(), inet::ospfv3::operator<<(), inet::ospfv3::Ospfv3RoutingTableEntry::operator==(), inet::eigrp::EigrpIpv6Pdm::processRTRouteDel(), inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs(), inet::Ipv6RoutingTable::routeLessThan(), and str().
getProtocolData()
virtual cObject* inet::Ipv6Route::getProtocolData () const inline override virtual
Implements inet::IRoute.
 { return _protocolData; }
getRoutingTable()
Ipv6RoutingTable* inet::Ipv6Route::getRoutingTable () const inline
 { return _rt; }
Referenced by getRoutingTableAsGeneric(), inet::Ipv6RoutingTable::internalAddRoute(), and inet::Ipv6RoutingTable::internalRemoveRoute().
getRoutingTableAsGeneric()
IRoutingTable * inet::Ipv6Route::getRoutingTableAsGeneric () const override virtual
The routing table in which this route is inserted, or nullptr.
Implements inet::IRoute.
 {
     return getRoutingTable();
 }
getSource()
virtual cObject* inet::Ipv6Route::getSource () const inline override virtual
Source of route.
Implements inet::IRoute.
 { return _source; }
getSourceType()
virtual SourceType inet::Ipv6Route::getSourceType () const inline override virtual
Source type of the route.
Implements inet::IRoute.
 { return _sourceType; }
Referenced by inet::eigrp::EigrpIpv6Pdm::installRouteToRT(), inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), and inet::eigrp::EigrpIpv6Pdm::removeRouteFromRT().
getSourceTypeAbbreviation()
const char * inet::Ipv6Route::getSourceTypeAbbreviation () const
{
     switch (_sourceType) {
         case IFACENETMASK:
             return "C";
         case MANUAL:
             return getDestPrefix().isUnspecified() ? "S*" : "S";
         case ROUTER_ADVERTISEMENT:
             return "ra";
         case RIP:
             return "R";
         case OSPF:
             return "O";
         case BGP:
             return "B";
         case EIGRP:
             return getAdminDist() < Ipv6Route::dEIGRPExternal ? "D" : "D EX";
         case LISP:
             return "l";
         case BABEL:
             return "ba";
         case ODR:
             return "o";
         default:
             return "???";
     }
 }
Referenced by str().
setAdminDist()
void inet::Ipv6Route::setAdminDist (unsigned int adminDist) inline override virtual
Implements inet::IRoute.
 { if (_adminDist != adminDist) { _adminDist = adminDist; changed(F_ADMINDIST); } }
Referenced by inet::Ipv6RoutingTable::addDefaultRoute(), inet::Ipv6RoutingTable::addOrUpdateOnLinkPrefix(), inet::Ipv6RoutingTable::addOrUpdateOwnAdvPrefix(), inet::Ipv6RoutingTable::addStaticRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::ospfv3::Ospfv3Process::parseConfig(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
setDestination()
virtual void inet::Ipv6Route::setDestination (const L3Address & dest) inline override virtual
Implements inet::IRoute.
 { if (_destPrefix != dest.toIpv6()) { _destPrefix = dest.toIpv6(); changed(F_DESTINATION); } }
Referenced by inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry().
setExpiryTime()
void inet::Ipv6Route::setExpiryTime (simtime_t expiryTime) inline
 { if (expiryTime != _expiryTime) { _expiryTime = expiryTime; changed(F_EXPIRYTIME); } }
Referenced by inet::Ipv6RoutingTable::addDefaultRoute(), inet::Ipv6RoutingTable::addOrUpdateOnLinkPrefix(), inet::Ipv6RoutingTable::addOrUpdateOwnAdvPrefix(), inet::ospfv3::Ospfv3Process::parseConfig(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
setInterface()
virtual void inet::Ipv6Route::setInterface (NetworkInterface * ie) inline override virtual
Implements inet::IRoute.
 { if (_interfacePtr != ie) { _interfacePtr = ie; changed(F_IFACE); } }
Referenced by inet::Ipv6RoutingTable::addDefaultRoute(), inet::ospfv3::Ospfv3RoutingTableEntry::addNextHop(), inet::Ipv6RoutingTable::addOrUpdateOnLinkPrefix(), inet::Ipv6RoutingTable::addOrUpdateOwnAdvPrefix(), inet::Ipv6RoutingTable::addStaticRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
setMetric()
void inet::Ipv6Route::setMetric (int metric) inline override virtual
Implements inet::IRoute.
 { if (_metric != metric) { _metric = metric; changed(F_METRIC); } }
Referenced by inet::Ipv6RoutingTable::addDefaultRoute(), inet::Ipv6RoutingTable::addOrUpdateOnLinkPrefix(), inet::Ipv6RoutingTable::addOrUpdateOwnAdvPrefix(), inet::Ipv6RoutingTable::addStaticRoute(), inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry(), inet::ospfv3::Ospfv3Process::parseConfig(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::ospfv3::Ospfv3RoutingTableEntry::setCost(), inet::ospfv3::Ospfv3RoutingTableEntry::setPathType(), inet::eigrp::EigrpIpv6Pdm::setRTRouteMetric(), and inet::ospfv3::Ospfv3RoutingTableEntry::setType2Cost().
setNextHop() [1/2]
void inet::Ipv6Route::setNextHop (const Ipv6Address & nextHop) inline
 { if (_nextHop != nextHop) { _nextHop = nextHop; changed(F_NEXTHOP); } }
Referenced by inet::Ipv6RoutingTable::addDefaultRoute(), inet::Ipv6RoutingTable::addStaticRoute(), inet::eigrp::EigrpIpv6Pdm::createRTRoute(), and inet::ospfv3::Ospfv3Process::rebuildRoutingTable().
setNextHop() [2/2]
virtual void inet::Ipv6Route::setNextHop (const L3Address & nextHop) inline override virtual
Implements inet::IRoute.
 { if (_nextHop != nextHop.toIpv6()) { _nextHop = nextHop.toIpv6(); changed(F_NEXTHOP); } }
setPrefixLength()
virtual void inet::Ipv6Route::setPrefixLength (int prefixLength) inline override virtual
Implements inet::IRoute.
 { if (_prefixLength != prefixLength) { _prefixLength = prefixLength; changed(F_PREFIX_LENGTH); } }
Referenced by inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry().
setProtocolData()
virtual void inet::Ipv6Route::setProtocolData (cObject * protocolData) inline override virtual
Implements inet::IRoute.
 { _protocolData = protocolData; }
setRoutingTable()
virtual void inet::Ipv6Route::setRoutingTable (Ipv6RoutingTable * rt) inline virtual
To be called by the routing table when this route is added or removed from it.
 { _rt = rt; }
Referenced by inet::Ipv6RoutingTable::internalAddRoute(), and inet::Ipv6RoutingTable::internalRemoveRoute().
setSource()
virtual void inet::Ipv6Route::setSource (cObject * source) inline override virtual
Implements inet::IRoute.
 { if (_source != source) { _source = source; changed(F_SOURCE); } }
setSourceType()
virtual void inet::Ipv6Route::setSourceType (SourceType type) inline override virtual
Implements inet::IRoute.
 { if (_sourceType != type) { _sourceType = type; changed(F_TYPE); } }
Referenced by inet::ospfv3::Ospfv3RoutingTableEntry::Ospfv3RoutingTableEntry().
str()
std::string inet::Ipv6Route::str () const override virtual
 {
     std::stringstream out;
     out << getSourceTypeAbbreviation();
     if (getDestPrefix().isUnspecified())
         out << " ::";
     else
         out << " " << getDestPrefix();
     out << "/" << getPrefixLength();
     if (getNextHop().isUnspecified()) {
         out << " is directly connected";
     }
     else {
         out << " [" << getAdminDist() << "/" << getMetric() << "]";
         out << " via ";
         out << getNextHop();
     }
     out << ", " << getInterface()->getInterfaceName();
     return out.str();
 }
Member Data Documentation
_adminDist
unsigned int inet::Ipv6Route::_adminDist protected
_destPrefix
Ipv6Address inet::Ipv6Route::_destPrefix protected
_expiryTime
simtime_t inet::Ipv6Route::_expiryTime protected
_interfacePtr
NetworkInterface* inet::Ipv6Route::_interfacePtr protected
_metric
int inet::Ipv6Route::_metric protected
_nextHop
Ipv6Address inet::Ipv6Route::_nextHop protected
_prefixLength
short inet::Ipv6Route::_prefixLength protected
_protocolData
cObject* inet::Ipv6Route::_protocolData protected
Object identifying the source.
_rt
Ipv6RoutingTable* inet::Ipv6Route::_rt protected
Referenced by changed().
_source
cObject* inet::Ipv6Route::_source protected
_sourceType
SourceType inet::Ipv6Route::_sourceType protected
Referenced by getSourceTypeAbbreviation().
The documentation for this class was generated from the following files:
Ipv6Route.h
Ipv6Route.cc