INET Framework for OMNeT++/OMNEST: inet::NetworkInterfaceChangeDetails Class Reference
inet::NetworkInterfaceChangeDetails Class Reference
#include <NetworkInterface.h>
Public Member Functions
NetworkInterfaceChangeDetails (NetworkInterface *ie, int field)
NetworkInterface * getNetworkInterface () const
int getFieldId () const
virtual std::string str () const override
Private Attributes
NetworkInterface * ie
int field
Constructor & Destructor Documentation
NetworkInterfaceChangeDetails()
inet::NetworkInterfaceChangeDetails::NetworkInterfaceChangeDetails (NetworkInterface * ie, int field) inline
 : ie(ie), field(field) { ASSERT(ie); }
Member Function Documentation
getFieldId()
int inet::NetworkInterfaceChangeDetails::getFieldId () const inline
 { return field; }
Referenced by inet::ospfv2::Ospfv2::receiveSignal(), and inet::Rip::receiveSignal().
getNetworkInterface()
NetworkInterface* inet::NetworkInterfaceChangeDetails::getNetworkInterface () const inline
 { return ie; }
Referenced by inet::ospfv2::Ospfv2::receiveSignal(), inet::GlobalArp::receiveSignal(), inet::visualizer::InterfaceTableVisualizerBase::receiveSignal(), inet::eigrp::EigrpIpv6Pdm::receiveSignal(), inet::Rip::receiveSignal(), and inet::eigrp::EigrpIpv4Pdm::receiveSignal().
str()
std::string inet::NetworkInterfaceChangeDetails::str () const override virtual
 {
     std::stringstream out;
     out << ie->str() << " changed field: " << field << "\n";
     return out.str();
 }
Member Data Documentation
field
int inet::NetworkInterfaceChangeDetails::field private
Referenced by str().
ie
NetworkInterface* inet::NetworkInterfaceChangeDetails::ie private
Referenced by str().
The documentation for this class was generated from the following files:
NetworkInterface.h
NetworkInterface.cc