INET Framework for OMNeT++/OMNEST: inet::Topology::Node Class Reference
inet::Topology::Node Class Reference
Supporting class for Topology, represents a node in the graph.
#include <Topology.h>
Public Member Functions
Node (int moduleId=-1)
Constructor.
virtual ~Node ()
Node attributes: weight, enabled state, correspondence to modules.
int getModuleId () const
Returns the ID of the network module to which this node corresponds.
cModule * getModule () const
Returns the pointer to the network module to which this node corresponds.
double getWeight () const
Returns the weight of this node.
void setWeight (double d)
Sets the weight of this node.
double getNetworkId () const
Returns the ID of the network to which this node corresponds.
void setNetworkId (int g)
Sets the ID of the network to which this node corresponds.
bool isVisited () const
Returns true if the node has been visited before in a traversal,.
void setVisited (bool v)
Marks this node as visited or not visited in a traversal.
bool isEnabled () const
Returns true of this node is enabled.
void enable ()
Enable this node.
void disable ()
Disable this node.
Node connectivity.
int getNumInLinks () const
Returns the number of incoming links to this graph node.
Link * getLinkIn (int i) const
Returns ith incoming link of graph node.
int getNumOutLinks () const
Returns the number of outgoing links from this graph node.
Link * getLinkOut (int i) const
Returns ith outgoing link of graph node.
Result of shortest path extraction.
double getDistanceToTarget () const
Returns the distance of this node to the target node.
int getNumPaths () const
Returns the number of shortest paths towards the target node.
Link * getPath (int i) const
Returns the next link in the ith shortest paths towards the target node.
Protected Attributes
int moduleId
double weight
bool enabled
bool visited
int networkId
std::vector< Link * > inLinks
std::vector< Link * > outLinks
double dist
std::vector< Link * > outPaths
Friends
class Topology
Detailed Description
Supporting class for Topology, represents a node in the graph.
Constructor & Destructor Documentation
Node()
inet::Topology::Node::Node (int moduleId = -1) inline
Constructor.
{
             this->moduleId = moduleId;
             weight = 0;
             enabled = true;
             visited = false;
             networkId = 0;
             dist = INFINITY;
         }
~Node()
virtual inet::Topology::Node::~Node () inline virtual
Reimplemented in inet::L2NetworkConfigurator::Node, inet::Ipv4NetworkConfigurator::Node, inet::L3NetworkConfiguratorBase::Node, and inet::NetworkConfiguratorBase::Node.
 {}
Member Function Documentation
disable()
void inet::Topology::Node::disable () inline
Disable this node.
This has significance with the shortest path finder methods of Topology.
 { enabled = false; }
enable()
void inet::Topology::Node::enable () inline
Enable this node.
This has significance with the shortest path finder methods of Topology.
 { enabled = true; }
getDistanceToTarget()
double inet::Topology::Node::getDistanceToTarget () const inline
Returns the distance of this node to the target node.
 { return dist; }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), and inet::Ipv4NetworkConfigurator::addStaticRoutes().
getLinkIn()
Topology::Link * inet::Topology::Node::getLinkIn (int i) const
Returns ith incoming link of graph node.
 {
     if (i < 0 || i >= (int)inLinks.size())
         throw cRuntimeError("Topology::Node::getLinkIn: invalid link index %d", i);
     return inLinks[i];
 }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Topology::calculateWeightedSingleShortestPathsTo(), inet::L3NetworkConfiguratorBase::dumpTopology(), inet::MacForwardingTableConfigurator::extendConfiguration(), and inet::NetworkConfiguratorBase::findLinkIn().
getLinkOut()
Topology::Link * inet::Topology::Node::getLinkOut (int i) const
Returns ith outgoing link of graph node.
 {
     if (i < 0 || i >= (int)outLinks.size())
         throw cRuntimeError("Topology::Node::getLinkOut: invalid index %d", i);
     return outLinks[i];
 }
Referenced by inet::StpTester::dfsVisit(), inet::L3NetworkConfiguratorBase::dumpTopology(), inet::L3NetworkConfiguratorBase::extractDeviceNeighbors(), inet::NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::FailureProtectionConfigurator::findConnectedNode(), inet::NetworkConfiguratorBase::findLinkOut(), inet::L2NetworkConfigurator::findLinkOut(), and inet::L3NetworkConfiguratorBase::findLinkOut().
getModule()
cModule* inet::Topology::Node::getModule () const inline
Returns the pointer to the network module to which this node corresponds.
 { return getSimulation()->getModule(moduleId); }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::StpTester::dfsVisit(), inet::NetworkConfiguratorBase::extractTopology(), inet::L2NetworkConfigurator::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::NetworkConfiguratorBase::findLinkIn(), inet::NetworkConfiguratorBase::findLinkOut(), inet::Topology::Link::getLinkInLocalGate(), inet::Topology::Link::getLinkInRemoteGate(), inet::Topology::Link::getLinkOutLocalGate(), inet::Topology::Link::getLinkOutRemoteGate(), and inet::StpTester::isForwarding().
getModuleId()
int inet::Topology::Node::getModuleId () const inline
Returns the ID of the network module to which this node corresponds.
 { return moduleId; }
getNetworkId()
double inet::Topology::Node::getNetworkId () const inline
Returns the ID of the network to which this node corresponds.
All nodes that belong to a connected network have the same network id.
 { return networkId; }
Referenced by inet::L3NetworkConfiguratorBase::extractTopology(), and inet::Topology::findNetworks().
getNumInLinks()
int inet::Topology::Node::getNumInLinks () const inline
Returns the number of incoming links to this graph node.
 { return inLinks.size(); }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::Topology::calculateWeightedSingleShortestPathsTo(), inet::L3NetworkConfiguratorBase::dumpTopology(), inet::MacForwardingTableConfigurator::extendConfiguration(), and inet::NetworkConfiguratorBase::findLinkIn().
getNumOutLinks()
int inet::Topology::Node::getNumOutLinks () const inline
Returns the number of outgoing links from this graph node.
 { return outLinks.size(); }
Referenced by inet::StpTester::dfsVisit(), inet::L3NetworkConfiguratorBase::dumpTopology(), inet::L3NetworkConfiguratorBase::extractDeviceNeighbors(), inet::NetworkConfiguratorBase::extractTopology(), inet::L3NetworkConfiguratorBase::extractTopology(), inet::NetworkConfiguratorBase::findLinkOut(), inet::L2NetworkConfigurator::findLinkOut(), and inet::L3NetworkConfiguratorBase::findLinkOut().
getNumPaths()
int inet::Topology::Node::getNumPaths () const inline
Returns the number of shortest paths towards the target node.
(There may be several paths with the same length.)
 { return outPaths.size(); }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::FailureProtectionConfigurator::collectAllPaths(), and inet::MacForwardingTableConfigurator::extendConfiguration().
getPath()
Link* inet::Topology::Node::getPath (int i) const inline
Returns the next link in the ith shortest paths towards the target node.
(There may be several paths with the same length.)
 { return outPaths.at(i); }
Referenced by inet::NextHopNetworkConfigurator::addStaticRoutes(), inet::Ipv4NetworkConfigurator::addStaticRoutes(), inet::FailureProtectionConfigurator::collectAllPaths(), inet::NetworkConfiguratorBase::computeShortestLinkPath(), inet::NetworkConfiguratorBase::computeShortestNodePath(), and inet::MacForwardingTableConfigurator::extendConfiguration().
getWeight()
double inet::Topology::Node::getWeight () const inline
Returns the weight of this node.
Weight is used with the weighted shortest path finder methods of Topology.
 { return weight; }
Referenced by inet::Topology::calculateWeightedSingleShortestPathsTo().
isEnabled()
bool inet::Topology::Node::isEnabled () const inline
Returns true of this node is enabled.
This has significance with the shortest path finder methods of Topology.
 { return enabled; }
Referenced by inet::Topology::calculateWeightedSingleShortestPathsTo().
isVisited()
bool inet::Topology::Node::isVisited () const inline
Returns true if the node has been visited before in a traversal,.
 { return visited; }
Referenced by inet::Topology::findNetworks().
setNetworkId()
void inet::Topology::Node::setNetworkId (int g) inline
Sets the ID of the network to which this node corresponds.
All nodes that belong to a connected network have the same network id.
 { networkId = g; }
Referenced by inet::Topology::extractFromNetwork(), and inet::Topology::findNetworks().
setVisited()
void inet::Topology::Node::setVisited (bool v) inline
Marks this node as visited or not visited in a traversal.
 { visited = v; }
Referenced by inet::Topology::findNetworks().
setWeight()
void inet::Topology::Node::setWeight (double d) inline
Sets the weight of this node.
Weight is used with the weighted shortest path finder methods of Topology.
 { weight = d; }
Referenced by inet::Ipv4NetworkConfigurator::addStaticRoutes().
Friends And Related Function Documentation
Topology
friend class Topology friend
Member Data Documentation
dist
double inet::Topology::Node::dist protected
Referenced by inet::Topology::calculateUnweightedSingleShortestPathsTo(), and inet::Topology::calculateWeightedSingleShortestPathsTo().
enabled
bool inet::Topology::Node::enabled protected
Referenced by inet::Topology::calculateUnweightedSingleShortestPathsTo().
inLinks
std::vector<Link *> inet::Topology::Node::inLinks protected
Referenced by inet::Topology::addLink(), inet::Topology::calculateUnweightedSingleShortestPathsTo(), inet::Topology::calculateWeightedSingleShortestPathsTo(), inet::Topology::deleteNode(), inet::Topology::extractFromNetwork(), getLinkIn(), and inet::Topology::unlinkFromDestNode().
moduleId
int inet::Topology::Node::moduleId protected
Referenced by inet::Topology::addNode(), inet::Topology::extractFromNetwork(), inet::Topology::findNetworks(), inet::Topology::isModuleIdLess(), and inet::Topology::lessByModuleId().
networkId
int inet::Topology::Node::networkId protected
outLinks
std::vector<Link *> inet::Topology::Node::outLinks protected
Referenced by inet::Topology::addLink(), inet::Topology::deleteNode(), inet::Topology::extractFromNetwork(), and inet::Topology::unlinkFromSourceNode().
outPaths
std::vector<Link *> inet::Topology::Node::outPaths protected
Referenced by inet::Topology::calculateUnweightedSingleShortestPathsTo(), and inet::Topology::calculateWeightedSingleShortestPathsTo().
visited
bool inet::Topology::Node::visited protected
weight
double inet::Topology::Node::weight protected
The documentation for this class was generated from the following files:
Topology.h
Topology.cc