INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211HtTimingRelatedParametersBase Class Reference
inet::physicallayer::Ieee80211HtTimingRelatedParametersBase Class Reference
#include <Ieee80211HtMode.h>
Public Member Functions
const simtime_t getDFTPeriod () const
const simtime_t getGIDuration () const
const simtime_t getShortGIDuration () const
const simtime_t getSymbolInterval () const
const simtime_t getShortGISymbolInterval () const
Member Function Documentation
getDFTPeriod()
const simtime_t inet::physicallayer::Ieee80211HtTimingRelatedParametersBase::getDFTPeriod () const inline
 { return 3.2E-6; } // DFT
getGIDuration()
const simtime_t inet::physicallayer::Ieee80211HtTimingRelatedParametersBase::getGIDuration () const inline
 { return getDFTPeriod() / 4; } // GI
getShortGIDuration()
const simtime_t inet::physicallayer::Ieee80211HtTimingRelatedParametersBase::getShortGIDuration () const inline
 { return getDFTPeriod() / 8; } // GIS
getShortGISymbolInterval()
const simtime_t inet::physicallayer::Ieee80211HtTimingRelatedParametersBase::getShortGISymbolInterval () const inline
 { return getDFTPeriod() + getShortGIDuration(); } // SYMS
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeGrossBitrate(), and inet::physicallayer::Ieee80211VhtDataMode::computeGrossBitrate().
getSymbolInterval()
const simtime_t inet::physicallayer::Ieee80211HtTimingRelatedParametersBase::getSymbolInterval () const inline
 { return getDFTPeriod() + getGIDuration(); } // SYM
Referenced by inet::physicallayer::Ieee80211VhtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtSignalMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtDataMode::computeGrossBitrate(), inet::physicallayer::Ieee80211VhtDataMode::computeGrossBitrate(), inet::physicallayer::Ieee80211HtDataMode::getDuration(), and inet::physicallayer::Ieee80211VhtDataMode::getDuration().
The documentation for this class was generated from the following file:
Ieee80211HtMode.h