INET Framework for OMNeT++/OMNEST: inet::EthernetMac Class Reference
inet::EthernetMac Class Reference
A simplified version of EthernetCsmaMac.
#include <EthernetMac.h>
Public Member Functions
EthernetMac ()
virtual void handleCanPullPacketChanged (cGate *gate) override
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
Public Member Functions inherited from inet::EthernetMacBase
EthernetMacBase ()
virtual ~EthernetMacBase ()
virtual MacAddress getMacAddress ()
double getTxRate ()
bool isActive ()
MacTransmitState getTransmitState ()
MacReceiveState getReceiveState ()
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual void processAtHandleMessageFinished ()
void addPaddingAndSetFcs (Packet *packet, B requiredMinByteLength=MIN_ETHERNET_FRAME_BYTES) const
Inserts padding in front of FCS and calculate FCS.
virtual queueing::IPassivePacketSource * getProvider (cGate *gate) override
Returns the passive packet source from where packets are pulled or nullptr if the connected module doesn't implement the interface.
virtual void handlePullPacketProcessed (Packet *packet, cGate *gate, bool successful) override
Notifies about the completion of the packet processing for a packet that was pulled earlier independently whether the packet is passed or streamed.
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::queueing::IActivePacketSink
virtual ~IActivePacketSink ()
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int stage) override
virtual void initializeStatistics () override
virtual void initializeFlags () override
virtual void handleMessageWhenUp (cMessage *msg) override
virtual void finish () override
virtual void handleEndIFGPeriod ()
virtual void handleEndTxPeriod ()
virtual void handleEndPausePeriod ()
virtual void handleSelfMessage (cMessage *msg) override
virtual void startFrameTransmission ()
virtual void handleUpperPacket (Packet *pk) override
virtual void processMsgFromNetwork (EthernetSignalBase *signal)
virtual void processReceivedDataFrame (Packet *packet, const Ptr< const EthernetMacHeader > &frame)
virtual void processPauseCommand (int pauseUnits)
virtual void scheduleEndIFGPeriod ()
virtual void scheduleEndPausePeriod (int pauseUnits)
virtual void beginSendFrames ()
Protected Member Functions inherited from inet::EthernetMacBase
virtual bool dropFrameNotForUs (Packet *packet, const Ptr< const EthernetMacHeader > &frame)
Checks destination address and drops the frame when frame is not for us; returns true if frame is dropped.
virtual void readChannelParameters (bool errorWhenAsymmetric)
Calculates datarates, etc.
virtual void printParameters ()
virtual void processConnectDisconnect ()
virtual void encapsulate (Packet *packet)
virtual void decapsulate (Packet *packet)
bool verifyCrcAndLength (Packet *packet)
Verify ethernet packet: check FCS and payload length.
virtual void configureNetworkInterface () override
virtual void refreshDisplay () const override
virtual void receiveSignal (cComponent *src, simsignal_t signalId, cObject *obj, cObject *details) override
virtual void refreshConnection ()
void changeTransmissionState (MacTransmitState newState)
void changeReceptionState (MacReceiveState newState)
virtual void cutEthernetSignalEnd (EthernetSignalBase *signal, simtime_t duration)
virtual void txFinished ()
Protected Member Functions inherited from inet::MacProtocolBase
MacProtocolBase ()
virtual ~MacProtocolBase ()
virtual void registerInterface ()
virtual MacAddress parseMacAddressParameter (const char *addrstr)
virtual void deleteCurrentTxFrame ()
virtual void dropCurrentTxFrame (PacketDropDetails &details)
virtual void handleMessageWhenDown (cMessage *msg) override
virtual void sendUp (cMessage *message)
virtual void sendDown (cMessage *message)
virtual bool isUpperMessage (cMessage *message) const override
virtual bool isLowerMessage (cMessage *message) const override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void flushQueue (PacketDropDetails &details)
should clear queue and emit signal "packetDropped" with entire packets
virtual void clearQueue ()
should clear queue silently
queueing::IPacketQueue * getQueue (cGate *gate) const
virtual bool canDequeuePacket () const
virtual Packet * dequeuePacket ()
Protected Member Functions inherited from inet::LayeredProtocolBase
virtual void handleUpperMessage (cMessage *message)
virtual void handleLowerMessage (cMessage *message)
virtual void handleUpperCommand (cMessage *message)
virtual void handleLowerCommand (cMessage *message)
virtual void handleLowerPacket (Packet *packet)
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
simtime_t totalSuccessfulRxTime
Protected Attributes inherited from inet::EthernetMacBase
const char * displayStringTextFormat = nullptr
bool sendRawBytes = false
FcsMode fcsMode = FCS_MODE_UNDEFINED
const EtherDescr * curEtherDescr = nullptr
bool connected = false
bool promiscuous = false
bool duplexMode = false
bool frameBursting = false
cChannel * transmissionChannel = nullptr
cGate * physInGate = nullptr
cGate * physOutGate = nullptr
bool channelsDiffer = false
MacTransmitState transmitState = static_cast<MacTransmitState>(-1)
MacReceiveState receiveState = static_cast<MacReceiveState>(-1)
simtime_t lastTxFinishTime
int pauseUnitsRequested = 0
cMessage * endTxTimer = nullptr
cMessage * endIfgTimer = nullptr
cMessage * endPauseTimer = nullptr
EthernetSignalBase * curTxSignal = nullptr
unsigned long numFramesSent = 0
unsigned long numFramesReceivedOK = 0
unsigned long numBytesSent = 0
unsigned long numBytesReceivedOK = 0
unsigned long numFramesFromHL = 0
unsigned long numDroppedPkFromHLIfaceDown = 0
unsigned long numDroppedIfaceDown = 0
unsigned long numDroppedBitError = 0
unsigned long numDroppedNotForUs = 0
unsigned long numFramesPassedToHL = 0
unsigned long numPauseFramesRcvd = 0
unsigned long numPauseFramesSent = 0
Protected Attributes inherited from inet::MacProtocolBase
int upperLayerInGateId = -1
Gate ids.
int upperLayerOutGateId = -1
int lowerLayerInGateId = -1
int lowerLayerOutGateId = -1
opp_component_ptr< NetworkInterface > networkInterface
opp_component_ptr< cModule > hostModule
Packet * currentTxFrame = nullptr
Currently transmitted frame if any.
opp_component_ptr< queueing::IPacketQueue > txQueue
Messages received from upper layer and to be transmitted later.
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Additional Inherited Members
Public Types inherited from inet::EthernetMacBase
enum MacTransmitState {
TX_IDLE_STATE = 1, WAIT_IFG_STATE, SEND_IFG_STATE, TRANSMITTING_STATE,
JAMMING_STATE, BACKOFF_STATE, PAUSE_STATE
}
enum MacReceiveState { RX_IDLE_STATE = 1, RECEIVING_STATE, RX_COLLISION_STATE, RX_RECONNECT_STATE }
Static Public Attributes inherited from inet::EthernetMacBase
static const double SPEED_OF_LIGHT_IN_CABLE = 200000000.0
Protected Types inherited from inet::EthernetMacBase
enum SelfMsgKindValues {
ENDIFG = 100, ENDRECEPTION, ENDBACKOFF, ENDTRANSMISSION,
ENDJAMMING, ENDPAUSE
}
enum { NUM_OF_ETHERDESCRS = 11 }
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Static Protected Attributes inherited from inet::EthernetMacBase
static const EtherDescr etherDescrs [NUM_OF_ETHERDESCRS]
static const EtherDescr nullEtherDescr
static simsignal_t rxPkOkSignal = registerSignal("rxPkOk")
static simsignal_t txPausePkUnitsSignal = registerSignal("txPausePkUnits")
static simsignal_t rxPausePkUnitsSignal = registerSignal("rxPausePkUnits")
static simsignal_t transmissionStateChangedSignal = registerSignal("transmissionStateChanged")
static simsignal_t receptionStateChangedSignal = registerSignal("receptionStateChanged")
Detailed Description
A simplified version of EthernetCsmaMac.
Since modern Ethernets typically operate over duplex links where's no contention, the original CSMA/CD algorithm is no longer needed. This simplified implementation doesn't contain CSMA/CD, frames are just simply queued up and sent out one by one.
Constructor & Destructor Documentation
EthernetMac()
inet::EthernetMac::EthernetMac ()
 {
 }
Member Function Documentation
beginSendFrames()
void inet::EthernetMac::beginSendFrames () protected virtual
 {
     if (currentTxFrame) {
         // Other frames are queued, transmit next frame
         EV_DETAIL << "Transmit next frame in output queue\n";
         startFrameTransmission();
     }
     else {
         // No more frames set transmitter to idle
         changeTransmissionState(TX_IDLE_STATE);
         EV_DETAIL << "No more frames to send, transmitter set to idle\n";
     }
 }
Referenced by initialize().
finish()
void inet::EthernetMac::finish () override protected virtual
Reimplemented from inet::EthernetMacBase.
 {
     EthernetMacBase::finish();
     simtime_t t = simTime();
     simtime_t totalRxChannelIdleTime = t - totalSuccessfulRxTime;
     recordScalar("rx channel idle (%)", 100 * (totalRxChannelIdleTime / t));
     recordScalar("rx channel utilization (%)", 100 * (totalSuccessfulRxTime / t));
 }
handleCanPullPacketChanged()
void inet::EthernetMac::handleCanPullPacketChanged (cGate * gate) override virtual
Notifies about a change in the possibility of pulling some packet from the passive packet source at the given gate.
This method is called, for example, when a new packet is inserted into a queue. It allows the sink to pull a new packet from the queue.
The gate parameter must be a valid gate of this module.
Implements inet::queueing::IActivePacketSink.
 {
     Enter_Method("handleCanPullPacketChanged");
     if (currentTxFrame == nullptr && transmitState == TX_IDLE_STATE && canDequeuePacket()) {
         Packet *packet = dequeuePacket();
         handleUpperPacket(packet);
     }
 }
handleEndIFGPeriod()
void inet::EthernetMac::handleEndIFGPeriod () protected virtual
 {
     ASSERT(nullptr == currentTxFrame);
     if (transmitState != WAIT_IFG_STATE)
         throw cRuntimeError("Not in WAIT_IFG_STATE at the end of IFG period");
     // End of IFG period, okay to transmit
     EV_DETAIL << "IFG elapsed" << endl;
     changeTransmissionState(TX_IDLE_STATE);
     if (canDequeuePacket()) {
         Packet *packet = dequeuePacket();
         handleUpperPacket(packet);
     }
 }
Referenced by handleSelfMessage().
handleEndPausePeriod()
void inet::EthernetMac::handleEndPausePeriod () protected virtual
 {
     ASSERT(nullptr == currentTxFrame);
     if (transmitState != PAUSE_STATE)
         throw cRuntimeError("End of PAUSE event occurred when not in PAUSE_STATE!");
     EV_DETAIL << "Pause finished, resuming transmissions\n";
     changeTransmissionState(TX_IDLE_STATE);
     if (canDequeuePacket()) {
         Packet *packet = dequeuePacket();
         handleUpperPacket(packet);
     }
 }
Referenced by handleSelfMessage().
handleEndTxPeriod()
void inet::EthernetMac::handleEndTxPeriod () protected virtual
 {
     // we only get here if transmission has finished successfully
     if (transmitState != TRANSMITTING_STATE)
         throw cRuntimeError("Model error: End of transmission, and incorrect state detected");
     if (nullptr == currentTxFrame)
         throw cRuntimeError("Model error: Frame under transmission cannot be found");
     numFramesSent++;
     numBytesSent += currentTxFrame->getByteLength();
     emit(packetSentToLowerSignal, currentTxFrame); // consider: emit with start time of frame
     emit(transmissionEndedSignal, curTxSignal);
     txFinished();
     const auto& header = currentTxFrame->peekAtFront<EthernetMacHeader>();
     if (header->getTypeOrLength() == ETHERTYPE_FLOW_CONTROL) {
         const auto& controlFrame = currentTxFrame->peekDataAt<EthernetControlFrameBase>(header->getChunkLength(), b(-1));
         if (controlFrame->getOpCode() == ETHERNET_CONTROL_PAUSE) {
             const auto& pauseFrame = CHK(dynamicPtrCast<const EthernetPauseFrame>(controlFrame));
             numPauseFramesSent++;
             emit(txPausePkUnitsSignal, pauseFrame->getPauseTime());
         }
     }
     EV_INFO << "Transmission of " << currentTxFrame << " successfully completed.\n";
     deleteCurrentTxFrame();
     lastTxFinishTime = simTime();
     if (pauseUnitsRequested > 0) {
         // if we received a PAUSE frame recently, go into PAUSE state
         EV_DETAIL << "Going to PAUSE mode for " << pauseUnitsRequested << " time units\n";
         scheduleEndPausePeriod(pauseUnitsRequested);
         pauseUnitsRequested = 0;
     }
     else {
         EV_DETAIL << "Start IFG period\n";
         scheduleEndIFGPeriod();
     }
 }
Referenced by handleSelfMessage().
handleMessageWhenUp()
void inet::EthernetMac::handleMessageWhenUp (cMessage * msg) override protected virtual
Reimplemented from inet::LayeredProtocolBase.
 {
     if (channelsDiffer)
         readChannelParameters(true);
     if (msg->isSelfMessage())
         handleSelfMessage(msg);
     else if (msg->getArrivalGateId() == upperLayerInGateId)
         handleUpperPacket(check_and_cast<Packet *>(msg));
     else if (msg->getArrivalGate() == physInGate)
         processMsgFromNetwork(check_and_cast<EthernetSignalBase *>(msg));
     else
         throw cRuntimeError("Message received from unknown gate!");
     processAtHandleMessageFinished();
 }
handleSelfMessage()
void inet::EthernetMac::handleSelfMessage (cMessage * msg) override protected virtual
Reimplemented from inet::LayeredProtocolBase.
 {
     EV_TRACE << "Self-message " << msg << " received\n";
     if (msg == endTxTimer)
         handleEndTxPeriod();
     else if (msg == endIfgTimer)
         handleEndIFGPeriod();
     else if (msg == endPauseTimer)
         handleEndPausePeriod();
     else
         throw cRuntimeError("Unknown self message received!");
 }
Referenced by handleMessageWhenUp().
handleUpperPacket()
void inet::EthernetMac::handleUpperPacket (Packet * pk) override protected virtual
Reimplemented from inet::LayeredProtocolBase.
 {
     //ASSERT2(false, "using EthernetMac");
     EV_INFO << "Received " << packet << " from upper layer." << endl;
     numFramesFromHL++;
     emit(packetReceivedFromUpperSignal, packet);
     auto frame = packet->peekAtFront<EthernetMacHeader>();
     if (frame->getDest().equals(getMacAddress())) {
         throw cRuntimeError("logic error: frame %s from higher layer has local MAC address as dest (%s)",
                 packet->getFullName(), frame->getDest().str().c_str());
     }
     if (packet->getDataLength() > MAX_ETHERNET_FRAME_BYTES) { // FIXME two MAX FRAME BYTES in specif...
         throw cRuntimeError("packet from higher layer (%s) exceeds maximum Ethernet frame size (%s)",
                 B(packet->getByteLength()).str().c_str(), MAX_ETHERNET_FRAME_BYTES.str().c_str());
     }
     if (!connected) {
         EV_WARN << "Interface is not connected -- dropping packet " << packet << endl;
         PacketDropDetails details;
         details.setReason(INTERFACE_DOWN);
         emit(packetDroppedSignal, packet, &details);
         numDroppedPkFromHLIfaceDown++;
         delete packet;
         return;
     }
     // fill in src address if not set
     if (frame->getSrc().isUnspecified()) {
         frame = nullptr; // drop shared ptr
         auto newFrame = packet->removeAtFront<EthernetMacHeader>();
         newFrame->setSrc(getMacAddress());
         packet->insertAtFront(newFrame);
         frame = newFrame;
     }
     if (transmitState != TX_IDLE_STATE)
         throw cRuntimeError("EthernetMac not in TX_IDLE_STATE when packet arrived from upper layer");
     if (currentTxFrame != nullptr)
         throw cRuntimeError("EthernetMac already has a transmit packet when packet arrived from upper layer");
     addPaddingAndSetFcs(packet, MIN_ETHERNET_FRAME_BYTES);
     currentTxFrame = packet;
     startFrameTransmission();
 }
Referenced by handleCanPullPacketChanged(), handleEndIFGPeriod(), handleEndPausePeriod(), and handleMessageWhenUp().
initialize()
void inet::EthernetMac::initialize (int stage) override protected virtual
Reimplemented from inet::EthernetMacBase.
 {
     EthernetMacBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         if (!par("duplexMode"))
             throw cRuntimeError("Half duplex operation is not supported by EthernetMac, use the EthernetCsmaMac module for that! (Please enable csmacdSupport on EthernetInterface)");
     }
     else if (stage == INITSTAGE_LINK_LAYER) {
         beginSendFrames(); // FIXME choose an another stage for it
     }
 }
initializeFlags()
void inet::EthernetMac::initializeFlags () override protected virtual
Reimplemented from inet::EthernetMacBase.
 {
     EthernetMacBase::initializeFlags();
     duplexMode = true;
     physInGate->setDeliverImmediately(false);
 }
initializeStatistics()
void inet::EthernetMac::initializeStatistics () override protected virtual
Reimplemented from inet::EthernetMacBase.
 {
     EthernetMacBase::initializeStatistics();
     // initialize statistics
     totalSuccessfulRxTime = 0.0;
 }
numInitStages()
virtual int inet::EthernetMac::numInitStages () const inline override protected virtual
Reimplemented from inet::EthernetMacBase.
 { return NUM_INIT_STAGES; }
processMsgFromNetwork()
void inet::EthernetMac::processMsgFromNetwork (EthernetSignalBase * signal) protected virtual
 {
     EV_INFO << signal << " received." << endl;
     if (!connected) {
         EV_WARN << "Interface is not connected -- dropping signal " << signal << endl;
         if (dynamic_cast<EthernetSignal *>(signal)) { // do not count JAM and IFG packets
             auto packet = check_and_cast<Packet *>(signal->decapsulate());
             delete signal;
             decapsulate(packet);
             PacketDropDetails details;
             details.setReason(INTERFACE_DOWN);
             emit(packetDroppedSignal, packet, &details);
             delete packet;
             numDroppedIfaceDown++;
         }
         else
             delete signal;
         return;
     }
     emit(receptionEndedSignal, signal);
     totalSuccessfulRxTime += signal->getDuration();
     if (signal->getSrcMacFullDuplex() != duplexMode)
         throw cRuntimeError("Ethernet misconfiguration: MACs on the same link must be all in full duplex mode, or all in half-duplex mode");
     if (dynamic_cast<EthernetFilledIfgSignal *>(signal))
         throw cRuntimeError("There is no burst mode in full-duplex operation: EtherFilledIfg is unexpected");
     if (dynamic_cast<EthernetJamSignal *>(signal))
         throw cRuntimeError("There is no JAM signal in full-duplex operation: EthernetJamSignal is unexpected");
     bool hasBitError = signal->hasBitError();
     auto packet = check_and_cast<Packet *>(signal->decapsulate());
     delete signal;
     decapsulate(packet);
     emit(packetReceivedFromLowerSignal, packet);
     if (hasBitError || !verifyCrcAndLength(packet)) {
         EV_WARN << "Bit error/CRC error in incoming packet -- dropping packet " << EV_FIELD(packet) << EV_ENDL;
         numDroppedBitError++;
         PacketDropDetails details;
         details.setReason(INCORRECTLY_RECEIVED);
         emit(packetDroppedSignal, packet, &details);
         delete packet;
         return;
     }
     const auto& frame = packet->peekAtFront<EthernetMacHeader>();
     if (dropFrameNotForUs(packet, frame))
         return;
     if (frame->getTypeOrLength() == ETHERTYPE_FLOW_CONTROL) {
         const auto& controlFrame = currentTxFrame->peekDataAt<EthernetControlFrameBase>(frame->getChunkLength(), b(-1));
         if (controlFrame->getOpCode() == ETHERNET_CONTROL_PAUSE) {
             auto pauseFrame = check_and_cast<const EthernetPauseFrame *>(controlFrame.get());
             int pauseUnits = pauseFrame->getPauseTime();
             EV_INFO << "Reception of PAUSE frame " << packet << " successfully completed." << endl;
             delete packet;
             numPauseFramesRcvd++;
             emit(rxPausePkUnitsSignal, pauseUnits);
             processPauseCommand(pauseUnits);
         }
         else {
             EV_INFO << "Received unknown ethernet flow control frame " << EV_FIELD(packet) << ", dropped." << endl;
             delete packet;
         }
     }
     else {
         EV_INFO << "Reception of " << EV_FIELD(packet) << " successfully completed." << endl;
         processReceivedDataFrame(packet, frame);
     }
 }
Referenced by handleMessageWhenUp().
processPauseCommand()
void inet::EthernetMac::processPauseCommand (int pauseUnits) protected virtual
 {
     if (transmitState == TX_IDLE_STATE) {
         EV_DETAIL << "PAUSE frame received, pausing for " << pauseUnitsRequested << " time units\n";
         if (pauseUnits > 0)
             scheduleEndPausePeriod(pauseUnits);
     }
     else if (transmitState == PAUSE_STATE) {
         EV_DETAIL << "PAUSE frame received, pausing for " << pauseUnitsRequested
                   << " more time units from now\n";
         cancelEvent(endPauseTimer);
         // Terminate PAUSE if pauseUnits == 0; Extend PAUSE if pauseUnits > 0
         scheduleEndPausePeriod(pauseUnits);
     }
     else {
         // transmitter busy -- wait until it finishes with current frame (endTx)
         // and then it'll go to PAUSE state
         EV_DETAIL << "PAUSE frame received, storing pause request\n";
         pauseUnitsRequested = pauseUnits;
     }
 }
Referenced by processMsgFromNetwork().
processReceivedDataFrame()
void inet::EthernetMac::processReceivedDataFrame (Packet * packet, const Ptr< const EthernetMacHeader > & frame) protected virtual
 {
     // statistics
     unsigned long curBytes = packet->getByteLength();
     numFramesReceivedOK++;
     numBytesReceivedOK += curBytes;
     emit(rxPkOkSignal, packet);
     const auto macAddressInd = packet->addTagIfAbsent<MacAddressInd>();
     macAddressInd->setSrcAddress(frame->getSrc());
     macAddressInd->setDestAddress(frame->getDest());
     packet->addTagIfAbsent<DispatchProtocolReq>()->setProtocol(&Protocol::ethernetMac);
     packet->addTagIfAbsent<PacketProtocolTag>()->setProtocol(&Protocol::ethernetMac);
     if (networkInterface)
         packet->addTagIfAbsent<InterfaceInd>()->setInterfaceId(networkInterface->getInterfaceId());
     numFramesPassedToHL++;
     emit(packetSentToUpperSignal, packet);
     // pass up to upper layer
     EV_INFO << "Sending " << packet << " to upper layer.\n";
     send(packet, upperLayerOutGateId);
 }
Referenced by processMsgFromNetwork().
scheduleEndIFGPeriod()
void inet::EthernetMac::scheduleEndIFGPeriod () protected virtual
 {
     ASSERT(nullptr == currentTxFrame);
     changeTransmissionState(WAIT_IFG_STATE);
     simtime_t endIFGTime = simTime() + (b(INTERFRAME_GAP_BITS).get() / curEtherDescr->txrate);
     scheduleAt(endIFGTime, endIfgTimer);
 }
Referenced by handleEndTxPeriod().
scheduleEndPausePeriod()
void inet::EthernetMac::scheduleEndPausePeriod (int pauseUnits) protected virtual
 {
     ASSERT(nullptr == currentTxFrame);
     // length is interpreted as 512-bit-time units
     simtime_t pausePeriod = ((pauseUnits * PAUSE_UNIT_BITS) / curEtherDescr->txrate);
     scheduleAfter(pausePeriod, endPauseTimer);
     changeTransmissionState(PAUSE_STATE);
 }
Referenced by handleEndTxPeriod(), and processPauseCommand().
startFrameTransmission()
void inet::EthernetMac::startFrameTransmission () protected virtual
 {
     ASSERT(currentTxFrame);
     EV_DETAIL << "Transmitting a copy of frame " << currentTxFrame << endl;
     Packet *frame = currentTxFrame->dup(); // note: we need to duplicate the frame because we emit a signal with it in endTxPeriod()
     const auto& hdr = frame->peekAtFront<EthernetMacHeader>(); // note: we need to duplicate the frame because we emit a signal with it in endTxPeriod()
     ASSERT(hdr);
     ASSERT(!hdr->getSrc().isUnspecified());
     // add preamble and SFD (Starting Frame Delimiter), then send out
     encapsulate(frame);
     // send
     auto& oldPacketProtocolTag = frame->removeTag<PacketProtocolTag>();
     frame->clearTags();
     auto newPacketProtocolTag = frame->addTag<PacketProtocolTag>();
     *newPacketProtocolTag = *oldPacketProtocolTag;
     EV_INFO << "Transmission of " << frame << " started.\n";
     auto signal = new EthernetSignal(frame->getName());
     signal->setSrcMacFullDuplex(duplexMode);
     signal->setBitrate(curEtherDescr->txrate);
     if (sendRawBytes) {
         auto bytes = frame->peekDataAsBytes();
         frame->eraseAll();
         frame->insertAtFront(bytes);
     }
     signal->encapsulate(frame);
     ASSERT(curTxSignal == nullptr);
     curTxSignal = signal->dup();
     emit(transmissionStartedSignal, signal);
     send(signal, physOutGate);
     scheduleAt(transmissionChannel->getTransmissionFinishTime(), endTxTimer);
     changeTransmissionState(TRANSMITTING_STATE);
 }
Referenced by beginSendFrames(), and handleUpperPacket().
Member Data Documentation
totalSuccessfulRxTime
simtime_t inet::EthernetMac::totalSuccessfulRxTime protected
Referenced by finish(), initializeStatistics(), and processMsgFromNetwork().
The documentation for this class was generated from the following files:
EthernetMac.h
EthernetMac.cc