INET Framework for OMNeT++/OMNEST: inet::ospfv2::SummaryLsa Class Reference
inet::ospfv2::SummaryLsa Class Reference
#include <Lsa.h>
Public Member Functions
SummaryLsa ()
SummaryLsa (const Ospfv2SummaryLsa &lsa)
SummaryLsa (const SummaryLsa &lsa)
virtual ~SummaryLsa ()
bool getPurgeable () const
void setPurgeable (bool purge=true)
bool validateLSChecksum () const
bool update (const Ospfv2SummaryLsa *lsa)
bool differsFrom (const Ospfv2SummaryLsa *summaryLSA) const
Public Member Functions inherited from inet::ospfv2::Ospfv2SummaryLsa
Ospfv2SummaryLsa ()
Ospfv2SummaryLsa (const Ospfv2SummaryLsa &other)
virtual ~Ospfv2SummaryLsa ()
Ospfv2SummaryLsa & operator= (const Ospfv2SummaryLsa &other)
virtual Ospfv2SummaryLsa * dup () const override
virtual void parsimPack (omnetpp::cCommBuffer *b) const override
virtual void parsimUnpack (omnetpp::cCommBuffer *b) override
virtual const ::inet::Ipv4Address & getNetworkMask () const
virtual ::inet::Ipv4Address & getNetworkMaskForUpdate ()
virtual void setNetworkMask (const ::inet::Ipv4Address &networkMask)
virtual unsigned long getRouteCost () const
virtual void setRouteCost (unsigned long routeCost)
virtual void setTosDataArraySize (size_t size)
virtual size_t getTosDataArraySize () const
virtual const Ospfv2TosData & getTosData (size_t k) const
virtual Ospfv2TosData & getTosDataForUpdate (size_t k)
virtual void setTosData (size_t k, const Ospfv2TosData &tosData)
virtual void insertTosData (size_t k, const Ospfv2TosData &tosData)
void insertTosData (const Ospfv2TosData &tosData)
virtual void appendTosData (const Ospfv2TosData &tosData)
virtual void eraseTosData (size_t k)
Public Member Functions inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2Lsa ()
Ospfv2Lsa (const Ospfv2Lsa &other)
virtual ~Ospfv2Lsa ()
Ospfv2Lsa & operator= (const Ospfv2Lsa &other)
virtual const Ospfv2LsaHeader & getHeader () const
virtual Ospfv2LsaHeader & getHeaderForUpdate ()
virtual void setHeader (const Ospfv2LsaHeader &header)
Public Member Functions inherited from inet::ospfv2::RoutingInfo
RoutingInfo ()
RoutingInfo (const RoutingInfo &routingInfo)
virtual ~RoutingInfo ()
void addNextHop (NextHop nextHop)
void clearNextHops ()
unsigned int getNextHopCount () const
NextHop getNextHop (unsigned int index) const
void setDistance (unsigned long d)
unsigned long getDistance () const
void setParent (Ospfv2Lsa *p)
Ospfv2Lsa * getParent () const
Public Member Functions inherited from inet::ospfv2::LsaTrackingInfo
LsaTrackingInfo ()
LsaTrackingInfo (const LsaTrackingInfo &info)
void setSource (InstallSource installSource)
InstallSource getSource () const
void incrementInstallTime ()
void resetInstallTime ()
unsigned long getInstallTime () const
Protected Attributes
bool purgeable
Protected Attributes inherited from inet::ospfv2::Ospfv2SummaryLsa
::inet::Ipv4Address networkMask
unsigned long routeCost = 1
Ospfv2TosData * tosData = nullptr
size_t tosData_arraysize = 0
Protected Attributes inherited from inet::ospfv2::Ospfv2Lsa
Ospfv2LsaHeader header
Additional Inherited Members
Public Types inherited from inet::ospfv2::LsaTrackingInfo
enum InstallSource { ORIGINATED = 0, FLOODED = 1 }
Protected Member Functions inherited from inet::ospfv2::Ospfv2SummaryLsa
bool operator== (const Ospfv2SummaryLsa &)=delete
Protected Member Functions inherited from inet::ospfv2::Ospfv2Lsa
bool operator== (const Ospfv2Lsa &)=delete
Constructor & Destructor Documentation
SummaryLsa() [1/3]
inet::ospfv2::SummaryLsa::SummaryLsa () inline
 : Ospfv2SummaryLsa(), RoutingInfo(), LsaTrackingInfo(), purgeable(false) {}
SummaryLsa() [2/3]
inet::ospfv2::SummaryLsa::SummaryLsa (const Ospfv2SummaryLsa & lsa) inline
 : Ospfv2SummaryLsa(lsa), RoutingInfo(), LsaTrackingInfo(), purgeable(false) {}
SummaryLsa() [3/3]
inet::ospfv2::SummaryLsa::SummaryLsa (const SummaryLsa & lsa) inline
 : Ospfv2SummaryLsa(lsa), RoutingInfo(lsa), LsaTrackingInfo(lsa), purgeable(lsa.purgeable) {}
~SummaryLsa()
virtual inet::ospfv2::SummaryLsa::~SummaryLsa () inline virtual
 {}
Member Function Documentation
differsFrom()
bool inet::ospfv2::SummaryLsa::differsFrom (const Ospfv2SummaryLsa * summaryLSA) const
 {
     const Ospfv2LsaHeader& thisHeader = getHeader();
     const Ospfv2LsaHeader& lsaHeader = summaryLSA->getHeader();
     bool differentHeader = ((thisHeader.getLsOptions() != lsaHeader.getLsOptions()) ||
                             ((thisHeader.getLsAge() == MAX_AGE) && (lsaHeader.getLsAge() != MAX_AGE)) ||
                             ((thisHeader.getLsAge() != MAX_AGE) && (lsaHeader.getLsAge() == MAX_AGE)) ||
                             (thisHeader.getLsaLength() != lsaHeader.getLsaLength()));
     bool differentBody = false;
     if (!differentHeader) {
         differentBody = ((getNetworkMask() != summaryLSA->getNetworkMask()) ||
                          (getRouteCost() != summaryLSA->getRouteCost()) ||
                          (getTosDataArraySize() != summaryLSA->getTosDataArraySize()));
         if (!differentBody) {
             unsigned int tosCount = tosData_arraysize;
             for (unsigned int i = 0; i < tosCount; i++) {
                 auto thisTosData = getTosData(i);
                 auto lsaTosData = summaryLSA->getTosData(i);
                 if ((thisTosData.tos != summaryLSA->getTosData(i).tos) ||
                     (thisTosData.tosMetric != lsaTosData.tosMetric))
                 {
                     differentBody = true;
                     break;
                 }
             }
         }
     }
     return differentHeader || differentBody;
 }
Referenced by update().
getPurgeable()
bool inet::ospfv2::SummaryLsa::getPurgeable () const inline
 { return purgeable; }
setPurgeable()
void inet::ospfv2::SummaryLsa::setPurgeable (bool purge = true) inline
 { purgeable = purge; }
update()
bool inet::ospfv2::SummaryLsa::update (const Ospfv2SummaryLsa * lsa)
 {
     bool different = differsFrom(lsa);
     (*this) = (*lsa);
     resetInstallTime();
     if (different) {
         clearNextHops();
         return true;
     }
     else {
         return false;
     }
 }
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase().
validateLSChecksum()
bool inet::ospfv2::SummaryLsa::validateLSChecksum () const inline
 { return true; } // not implemented
Referenced by inet::ospfv2::Ospfv2Area::ageDatabase().
Member Data Documentation
purgeable
bool inet::ospfv2::SummaryLsa::purgeable protected
The documentation for this class was generated from the following files:
Lsa.h
SummaryLsa.cc