INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211VhtPreambleMode Class Reference
inet::physicallayer::Ieee80211VhtPreambleMode Class Reference
#include <Ieee80211VhtMode.h>
Public Types
enum HighTroughputPreambleFormat { HT_PREAMBLE_MIXED, HT_PREAMBLE_GREENFIELD }
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Public Member Functions
Ieee80211VhtPreambleMode (const Ieee80211VhtSignalMode *highThroughputSignalMode, const Ieee80211OfdmSignalMode *legacySignalMode, HighTroughputPreambleFormat preambleFormat, unsigned int numberOfSpatialStream)
virtual ~Ieee80211VhtPreambleMode ()
HighTroughputPreambleFormat getPreambleFormat () const
virtual const Ieee80211VhtSignalMode * getSignalMode () const
virtual const Ieee80211OfdmSignalMode * getLegacySignalMode () const
virtual const Ieee80211VhtSignalMode * getHighThroughputSignalMode () const
virtual const simtime_t getDoubleGIDuration () const
virtual const simtime_t getLSIGDuration () const
virtual const simtime_t getNonHTShortTrainingSequenceDuration () const
virtual const simtime_t getHTGreenfieldShortTrainingFieldDuration () const
virtual const simtime_t getNonHTLongTrainingFieldDuration () const
virtual const simtime_t getNonHTSignalField () const
virtual const simtime_t getVHTSignalFieldA () const
virtual const simtime_t getVHTShortTrainingFieldDuration () const
virtual const simtime_t getVHTSignalFieldB () const
virtual const simtime_t getFirstHTLongTrainingFieldDuration () const
virtual const simtime_t getSecondAndSubsequentHTLongTrainingFielDuration () const
virtual unsigned int getNumberOfHtLongTrainings () const
virtual const simtime_t getDuration () const override
virtual Ptr< Ieee80211PhyPreamble > createPreamble () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211HtTimingRelatedParametersBase
const simtime_t getDFTPeriod () const
const simtime_t getGIDuration () const
const simtime_t getShortGIDuration () const
const simtime_t getSymbolInterval () const
const simtime_t getShortGISymbolInterval () const
Protected Member Functions
virtual unsigned int computeNumberOfSpaceTimeStreams (unsigned int numberOfSpatialStreams) const
virtual unsigned int computeNumberOfHTLongTrainings (unsigned int numberOfSpaceTimeStreams) const
Protected Attributes
const Ieee80211VhtSignalMode * highThroughputSignalMode
const Ieee80211OfdmSignalMode * legacySignalMode
const HighTroughputPreambleFormat preambleFormat
const unsigned int numberOfHTLongTrainings
Member Enumeration Documentation
HighTroughputPreambleFormat
enum inet::physicallayer::Ieee80211VhtPreambleMode::HighTroughputPreambleFormat
Enumerator
HT_PREAMBLE_MIXED
HT_PREAMBLE_GREENFIELD
{
         HT_PREAMBLE_MIXED, // can be received by non-HT STAs compliant with Clause 18 or Clause 19
         HT_PREAMBLE_GREENFIELD // all of the non-HT fields are omitted
     };
Constructor & Destructor Documentation
Ieee80211VhtPreambleMode()
inet::physicallayer::Ieee80211VhtPreambleMode::Ieee80211VhtPreambleMode (const Ieee80211VhtSignalMode * highThroughputSignalMode, const Ieee80211OfdmSignalMode * legacySignalMode, HighTroughputPreambleFormat preambleFormat, unsigned int numberOfSpatialStream)
                                                                                                                                                                                                                                           :
     highThroughputSignalMode(highThroughputSignalMode),
     legacySignalMode(legacySignalMode),
     preambleFormat(preambleFormat),
     numberOfHTLongTrainings(computeNumberOfHTLongTrainings(computeNumberOfSpaceTimeStreams(numberOfSpatialStream)))
 {
 }
~Ieee80211VhtPreambleMode()
virtual inet::physicallayer::Ieee80211VhtPreambleMode::~Ieee80211VhtPreambleMode () inline virtual
 { delete highThroughputSignalMode; }
Member Function Documentation
computeNumberOfHTLongTrainings()
unsigned int inet::physicallayer::Ieee80211VhtPreambleMode::computeNumberOfHTLongTrainings (unsigned int numberOfSpaceTimeStreams) const protected virtual
 {
     // If the transmitter is providing training for exactly the space-time
     // streams (spatial mapper inputs) used for the transmission of the PSDU,
     // the number of training symbols, N_LTF, is equal to the number of space-time
     // streams, N STS, except that for three space-time streams, four training symbols
     // are required.
     return numberOfSpaceTimeStreams == 3 ? 4 : numberOfSpaceTimeStreams;
 }
computeNumberOfSpaceTimeStreams()
unsigned int inet::physicallayer::Ieee80211VhtPreambleMode::computeNumberOfSpaceTimeStreams (unsigned int numberOfSpatialStreams) const protected virtual
 {
     // Table 20-12—Determining the number of space-time streams
     return numberOfSpatialStreams + highThroughputSignalMode->getSTBC();
 }
createPreamble()
virtual Ptr<Ieee80211PhyPreamble> inet::physicallayer::Ieee80211VhtPreambleMode::createPreamble () const inline override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 { return makeShared<Ieee80211VhtPhyPreamble>(); }
getDoubleGIDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getDoubleGIDuration () const inline virtual
 { return 2 * getGIDuration(); } // GI2
getDuration()
const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getDuration () const override virtual
Implements inet::physicallayer::IIeee80211PreambleMode.
 {
     // 21.3.4 Mathematical description of signals
     simtime_t sumOfHTLTFs = getSecondAndSubsequentHTLongTrainingFielDuration() * numberOfHTLongTrainings;
     return getNonHTShortTrainingSequenceDuration() + getNonHTLongTrainingFieldDuration() + getLSIGDuration() + getVHTSignalFieldA() + getVHTShortTrainingFieldDuration() + sumOfHTLTFs + getVHTSignalFieldB();
 }
Referenced by inet::physicallayer::Ieee80211VhtMode::getDuration().
getFirstHTLongTrainingFieldDuration()
const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getFirstHTLongTrainingFieldDuration () const virtual
 {
     return simtime_t(8E-6);
 }
getHighThroughputSignalMode()
virtual const Ieee80211VhtSignalMode* inet::physicallayer::Ieee80211VhtPreambleMode::getHighThroughputSignalMode () const inline virtual
 { return highThroughputSignalMode; }
getHTGreenfieldShortTrainingFieldDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getHTGreenfieldShortTrainingFieldDuration () const inline virtual
 { return 10 * getDFTPeriod() / 4; } // HT-GF-STF
getLegacySignalMode()
virtual const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211VhtPreambleMode::getLegacySignalMode () const inline virtual
 { return legacySignalMode; }
Referenced by inet::physicallayer::Ieee80211VhtMode::getLegacySignalMode().
getLSIGDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getLSIGDuration () const inline virtual
 { return getSymbolInterval(); } // L-SIG
Referenced by getDuration().
getNonHTLongTrainingFieldDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getNonHTLongTrainingFieldDuration () const inline virtual
 { return 2 * getDFTPeriod() + getDoubleGIDuration(); } // L-LTF
Referenced by getDuration().
getNonHTShortTrainingSequenceDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getNonHTShortTrainingSequenceDuration () const inline virtual
 { return 10 * getDFTPeriod() / 4; } // L-STF
Referenced by getDuration().
getNonHTSignalField()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getNonHTSignalField () const inline virtual
 { return 4E-6; } // L-SIG
getNumberOfHtLongTrainings()
virtual unsigned int inet::physicallayer::Ieee80211VhtPreambleMode::getNumberOfHtLongTrainings () const inline virtual
 { return numberOfHTLongTrainings; }
getPreambleFormat()
HighTroughputPreambleFormat inet::physicallayer::Ieee80211VhtPreambleMode::getPreambleFormat () const inline
 { return preambleFormat; }
getSecondAndSubsequentHTLongTrainingFielDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getSecondAndSubsequentHTLongTrainingFielDuration () const inline virtual
 { return 4E-6; } // HT-LTFs, s = 2,3,..,n
Referenced by getDuration().
getSignalMode()
virtual const Ieee80211VhtSignalMode* inet::physicallayer::Ieee80211VhtPreambleMode::getSignalMode () const inline virtual
 { return highThroughputSignalMode; }
Referenced by inet::physicallayer::Ieee80211VhtMode::getHeaderMode().
getVHTShortTrainingFieldDuration()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getVHTShortTrainingFieldDuration () const inline virtual
 { return 4E-6; } // VHT-STF
Referenced by getDuration().
getVHTSignalFieldA()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getVHTSignalFieldA () const inline virtual
 { return 8E-6; } // VHT-SIG-A
Referenced by getDuration().
getVHTSignalFieldB()
virtual const simtime_t inet::physicallayer::Ieee80211VhtPreambleMode::getVHTSignalFieldB () const inline virtual
 { return 4E-6; } // VHT-SIG-A
Referenced by getDuration().
Member Data Documentation
highThroughputSignalMode
const Ieee80211VhtSignalMode* inet::physicallayer::Ieee80211VhtPreambleMode::highThroughputSignalMode protected
Referenced by computeNumberOfSpaceTimeStreams().
legacySignalMode
const Ieee80211OfdmSignalMode* inet::physicallayer::Ieee80211VhtPreambleMode::legacySignalMode protected
numberOfHTLongTrainings
const unsigned int inet::physicallayer::Ieee80211VhtPreambleMode::numberOfHTLongTrainings protected
Referenced by getDuration().
preambleFormat
const HighTroughputPreambleFormat inet::physicallayer::Ieee80211VhtPreambleMode::preambleFormat protected
The documentation for this class was generated from the following files:
Ieee80211VhtMode.h
Ieee80211VhtMode.cc