INET Framework for OMNeT++/OMNEST: inet::IMulticastRoute::OutInterface Class Reference
inet::IMulticastRoute::OutInterface Class Reference
#include <IRoute.h>
Public Member Functions
OutInterface (const NetworkInterface *ie, bool isLeaf=false)
OutInterface (const OutInterface &other)
virtual ~OutInterface ()
const NetworkInterface * getInterface () const
bool isLeaf () const
virtual bool isEnabled ()
Protected Attributes
const NetworkInterface * ie
bool _isLeaf
Constructor & Destructor Documentation
OutInterface() [1/2]
inet::IMulticastRoute::OutInterface::OutInterface (const NetworkInterface * ie, bool isLeaf = false) inline
 : ie(ie), _isLeaf(isLeaf) { ASSERT(ie); }
OutInterface() [2/2]
inet::IMulticastRoute::OutInterface::OutInterface (const OutInterface & other) inline
 : ie(other.ie), _isLeaf(other._isLeaf) {}
~OutInterface()
virtual inet::IMulticastRoute::OutInterface::~OutInterface () inline virtual
 {}
Member Function Documentation
getInterface()
const NetworkInterface* inet::IMulticastRoute::OutInterface::getInterface () const inline
 { return ie; }
Referenced by inet::Ipv4MulticastRoute::addOutInterface(), inet::Ipv4NetworkConfigurator::configureRoutingTable(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::Ipv4::forwardMulticastPacket(), inet::Ipv4RoutingTable::internalAddMulticastRoute(), and inet::Ipv4RoutingTable::printMulticastRoutingTable().
isEnabled()
virtual bool inet::IMulticastRoute::OutInterface::isEnabled () inline virtual
Reimplemented in inet::PimDm::PimDmOutInterface, and inet::PimSm::PimSmOutInterface.
 { return true; }
Referenced by inet::Ipv4::forwardMulticastPacket().
isLeaf()
bool inet::IMulticastRoute::OutInterface::isLeaf () const inline
 { return _isLeaf; }
Referenced by inet::Ipv4::forwardMulticastPacket().
Member Data Documentation
_isLeaf
bool inet::IMulticastRoute::OutInterface::_isLeaf protected
ie
const NetworkInterface* inet::IMulticastRoute::OutInterface::ie protected
The documentation for this class was generated from the following file:
IRoute.h