INET Framework for OMNeT++/OMNEST: inet::visualizer::PortFilter Class Reference
inet::visualizer::PortFilter Class Reference
This class provides a generic filter for ports.
#include <PortFilter.h>
Public Member Functions
void setPattern (const char *pattern)
bool matches (int value) const
Protected Attributes
cMatchExpression matchExpression
Detailed Description
This class provides a generic filter for ports.
The filter is expressed as a pattern using the cMatchExpression format.
Member Function Documentation
matches()
bool inet::visualizer::PortFilter::matches (int value) const
 {
     std::string text = std::to_string(value);
     cMatchableString matchableString(text.c_str());
     return matchExpression.matches(&matchableString);
 }
Referenced by inet::visualizer::TransportConnectionVisualizerBase::receiveSignal().
setPattern()
void inet::visualizer::PortFilter::setPattern (const char * pattern)
 {
     matchExpression.setPattern(pattern, false, true, true);
 }
Referenced by inet::visualizer::TransportConnectionVisualizerBase::handleParameterChange(), and inet::visualizer::TransportConnectionVisualizerBase::initialize().
Member Data Documentation
matchExpression
cMatchExpression inet::visualizer::PortFilter::matchExpression protected
Referenced by matches(), and setPattern().
The documentation for this class was generated from the following files:
PortFilter.h
PortFilter.cc