INET Framework for OMNeT++/OMNEST: inet::eigrp::EigrpMetricHelper Class Reference
inet::eigrp::EigrpMetricHelper Class Reference
Class for EIGRP metric computation.
#include <EigrpMetricHelper.h>
Public Member Functions
EigrpMetricHelper ()
virtual ~EigrpMetricHelper ()
EigrpWideMetricPar getParam (EigrpInterface *eigrpIface)
Sets parameters from interface for metric computation.
EigrpWideMetricPar adjustParam (const EigrpWideMetricPar &ifParam, const EigrpWideMetricPar &neighParam)
Adjust parameters of metric by interface parameters.
uint64_t computeClassicMetric (const EigrpWideMetricPar &par, const EigrpKValues &kValues)
Computes classic metric.
uint64_t computeWideMetric (const EigrpWideMetricPar &par, const EigrpKValues &kValues)
Computes wide metric.
bool compareParameters (const EigrpWideMetricPar &par1, const EigrpWideMetricPar &par2, EigrpKValues &kValues)
Compares metric enabled parameters.
bool isParamMaximal (const EigrpWideMetricPar &par)
Returns true, if parameters are set to infinite, otherwise false.
Static Public Attributes
static const uint64_t DELAY_INF = 0xFFFFFFFFFFFF
static const uint64_t BANDWIDTH_INF = 0xFFFFFFFFFFFF
static const uint64_t METRIC_INF = 0xFFFFFFFFFFFFFF
Private Member Functions
unsigned int getMin (unsigned int p1, unsigned int p2)
Returns smaller of two parameters.
unsigned int getMax (unsigned int p1, unsigned int p2)
Returns greater of two parameters.
Private Attributes
const uint32_t DELAY_PICO
const uint32_t BANDWIDTH
const uint32_t CLASSIC_SCALE
const uint32_t WIDE_SCALE
Detailed Description
Class for EIGRP metric computation.
Constructor & Destructor Documentation
EigrpMetricHelper()
inet::eigrp::EigrpMetricHelper::EigrpMetricHelper ()
                                      :
     DELAY_PICO(1000000), BANDWIDTH(10000000), CLASSIC_SCALE(256), WIDE_SCALE(65536)
 {
 }
~EigrpMetricHelper()
inet::eigrp::EigrpMetricHelper::~EigrpMetricHelper () virtual
 {
 }
Member Function Documentation
adjustParam()
EigrpWideMetricPar inet::eigrp::EigrpMetricHelper::adjustParam (const EigrpWideMetricPar & ifParam, const EigrpWideMetricPar & neighParam)
Adjust parameters of metric by interface parameters.
 {
     EigrpWideMetricPar newMetricPar;
     newMetricPar.load = getMax(ifParam.load, neighParam.delay);
     newMetricPar.reliability = getMin(ifParam.reliability, neighParam.reliability);
     newMetricPar.mtu = getMin(ifParam.mtu, neighParam.mtu);
     newMetricPar.hopCount = neighParam.hopCount + 1;
     if (isParamMaximal(neighParam)) {
         newMetricPar.delay = DELAY_INF;
         newMetricPar.bandwidth = BANDWIDTH_INF;
     }
     else {
         newMetricPar.delay = ifParam.delay + neighParam.delay;
         newMetricPar.bandwidth = getMin(ifParam.bandwidth, neighParam.bandwidth);
     }
     return newMetricPar;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
compareParameters()
bool inet::eigrp::EigrpMetricHelper::compareParameters (const EigrpWideMetricPar & par1, const EigrpWideMetricPar & par2, EigrpKValues & kValues)
Compares metric enabled parameters.
 {
     if (kValues.K1 && par1.bandwidth != par2.bandwidth)
         return false;
     if (kValues.K2 && par1.load != par2.load)
         return false;
     if (kValues.K3 && par1.delay != par2.delay)
         return false;
     if (kValues.K5 && par1.reliability != par2.reliability)
         return false;
     return true;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
computeClassicMetric()
uint64_t inet::eigrp::EigrpMetricHelper::computeClassicMetric (const EigrpWideMetricPar & par, const EigrpKValues & kValues)
Computes classic metric.
 {
     uint32_t metric;
     uint32_t classicDelay = 0, classicBw = 0;
     if (isParamMaximal(par))
         return METRIC_INF;
     // Adjust delay and bandwidth
     if (kValues.K3) { // Note: delay is in pico seconds and must be converted to micro seconds for classic metric
         classicDelay = par.delay / 10000000;
         classicDelay = classicDelay * CLASSIC_SCALE;
     }
     ASSERT(par.bandwidth > 0);
     if (kValues.K1)
         classicBw = BANDWIDTH / par.bandwidth * CLASSIC_SCALE;
     metric = kValues.K1 * classicBw + kValues.K2 * classicBw / (256 - par.load) + kValues.K3 * classicDelay;
     if (kValues.K5 != 0)
         metric = metric * kValues.K5 / (par.reliability + kValues.K4);
     return metric;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
computeWideMetric()
uint64_t inet::eigrp::EigrpMetricHelper::computeWideMetric (const EigrpWideMetricPar & par, const EigrpKValues & kValues)
Computes wide metric.
 {
     uint64_t metric, throughput, latency;
     if (isParamMaximal(par))
         return METRIC_INF;
     // TODO compute delay from bandwidth if bandwidth is greater than 1 Gb/s
     // TODO include also additional parameters associated with K6
     throughput = (BANDWIDTH * WIDE_SCALE) / par.bandwidth;
     latency = (par.delay * WIDE_SCALE) / DELAY_PICO;
     metric = kValues.K1 * throughput + kValues.K2 * kValues.K1 * throughput / (256 - par.load) + kValues.K3 * latency /*+ kValues.K6*extAttr*/;
     if (kValues.K5 != 0)
         metric = metric * kValues.K5 / (par.reliability + kValues.K4);
     return metric;
 }
getMax()
unsigned int inet::eigrp::EigrpMetricHelper::getMax (unsigned int p1, unsigned int p2) inline private
Returns greater of two parameters.
 { return (p1 < p2) ? p2 : p1; }
Referenced by adjustParam().
getMin()
unsigned int inet::eigrp::EigrpMetricHelper::getMin (unsigned int p1, unsigned int p2) inline private
Returns smaller of two parameters.
 { return (p1 < p2) ? p1 : p2; }
Referenced by adjustParam().
getParam()
EigrpWideMetricPar inet::eigrp::EigrpMetricHelper::getParam (EigrpInterface * eigrpIface)
Sets parameters from interface for metric computation.
 {
     EigrpWideMetricPar newMetricPar;
     newMetricPar.bandwidth = eigrpIface->getBandwidth();
     newMetricPar.delay = eigrpIface->getDelay() * DELAY_PICO;
     newMetricPar.load = eigrpIface->getLoad();
     newMetricPar.reliability = eigrpIface->getReliability();
     newMetricPar.hopCount = 0;
     newMetricPar.mtu = eigrpIface->getMtu();
     return newMetricPar;
 }
Referenced by inet::eigrp::EigrpIpv4Pdm::enableInterface(), inet::eigrp::EigrpIpv6Pdm::enableInterface(), inet::eigrp::EigrpIpv4Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv6Pdm::processIfaceConfigChange(), inet::eigrp::EigrpIpv4Pdm::processInterRoute(), and inet::eigrp::EigrpIpv6Pdm::processInterRoute().
isParamMaximal()
bool inet::eigrp::EigrpMetricHelper::isParamMaximal (const EigrpWideMetricPar & par) inline
Returns true, if parameters are set to infinite, otherwise false.
 { return par.delay == DELAY_INF; }
Referenced by inet::eigrp::EigrpIpv4Pdm::addRoutesToMsg(), inet::eigrp::EigrpIpv6Pdm::addRoutesToMsg(), adjustParam(), computeClassicMetric(), computeWideMetric(), inet::eigrp::EigrpIpv4Pdm::processUpdatePacket(), and inet::eigrp::EigrpIpv6Pdm::processUpdatePacket().
Member Data Documentation
BANDWIDTH
const uint32_t inet::eigrp::EigrpMetricHelper::BANDWIDTH private
Referenced by computeClassicMetric(), and computeWideMetric().
BANDWIDTH_INF
const uint64_t inet::eigrp::EigrpMetricHelper::BANDWIDTH_INF = 0xFFFFFFFFFFFF static
Referenced by adjustParam(), inet::eigrp::EigrpIpv4Pdm::createRouteTlv(), inet::eigrp::EigrpIpv6Pdm::createRouteTlv(), inet::EigrpRoute< inet::Ipv4Address >::setUnreachable(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
CLASSIC_SCALE
const uint32_t inet::eigrp::EigrpMetricHelper::CLASSIC_SCALE private
Referenced by computeClassicMetric().
DELAY_INF
const uint64_t inet::eigrp::EigrpMetricHelper::DELAY_INF = 0xFFFFFFFFFFFF static
Referenced by adjustParam(), inet::eigrp::EigrpIpv4Pdm::createRouteTlv(), inet::eigrp::EigrpIpv6Pdm::createRouteTlv(), isParamMaximal(), inet::EigrpRoute< inet::Ipv4Address >::setUnreachable(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
DELAY_PICO
const uint32_t inet::eigrp::EigrpMetricHelper::DELAY_PICO private
Referenced by computeWideMetric(), and getParam().
METRIC_INF
const uint64_t inet::eigrp::EigrpMetricHelper::METRIC_INF = 0xFFFFFFFFFFFFFF static
Referenced by computeClassicMetric(), computeWideMetric(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::findRouteDMin(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::hasFeasibleSuccessor(), inet::EigrpRouteSource< inet::Ipv4Address >::isUnreachable(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition13(), inet::eigrp::EigrpDual< inet::Ipv4Address >::processTransition15(), inet::EigrpRoute< inet::Ipv4Address >::setUnreachable(), and inet::EigrpRouteSource< inet::Ipv4Address >::setUnreachableMetric().
WIDE_SCALE
const uint32_t inet::eigrp::EigrpMetricHelper::WIDE_SCALE private
Referenced by computeWideMetric().
The documentation for this class was generated from the following files:
EigrpMetricHelper.h
EigrpMetricHelper.cc