INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmSignalMode Class Reference
inet::physicallayer::Ieee80211OfdmSignalMode Class Reference
#include <Ieee80211OfdmMode.h>
Public Member Functions
Ieee80211OfdmSignalMode (const Ieee80211OfdmCode *code, const Ieee80211OfdmModulation *modulation, Hz channelSpacing, Hz bandwidth, unsigned int rate)
virtual ~Ieee80211OfdmSignalMode ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
unsigned int getRate () const
b getRateFieldLength () const
b getReservedFieldLength () const
b getLengthFieldLength () const
b getParityFieldLength () const
b getTailFieldLength () const
b getServiceFieldLength () const
virtual b getLength () const override
virtual const simtime_t getDuration () const override
const Ieee80211OfdmCode * getCode () const
const Ieee80211OfdmModulation * getModulation () const override
virtual bps getGrossBitrate () const override
virtual bps getNetBitrate () const override
virtual Ptr< Ieee80211PhyHeader > createHeader () const override
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmModeBase
Ieee80211OfdmModeBase (const Ieee80211OfdmModulation *modulation, const Ieee80211OfdmCode *code, Hz channelSpacing, Hz bandwidth)
virtual ~Ieee80211OfdmModeBase ()
int getNumberOfDataSubcarriers () const
int getNumberOfPilotSubcarriers () const
int getNumberOfTotalSubcarriers () const
virtual Hz getBandwidth () const
Public Member Functions inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Ieee80211OfdmTimingRelatedParametersBase (Hz channelSpacing)
Hz getSubcarrierFrequencySpacing () const
const simtime_t getFFTTransformPeriod () const
const simtime_t getGIDuration () const
const simtime_t getSymbolInterval () const
const Hz getChannelSpacing () const
Protected Attributes
unsigned int rate
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmModeBase
const Ieee80211OfdmModulation * modulation
const Ieee80211OfdmCode * code
const Hz bandwidth
bps netBitrate
bps grossBitrate
Protected Attributes inherited from inet::physicallayer::Ieee80211OfdmTimingRelatedParametersBase
Hz channelSpacing
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Protected Member Functions inherited from inet::physicallayer::Ieee80211OfdmModeBase
bps computeGrossBitrate (const Ieee80211OfdmModulation *modulation) const
bps computeNetBitrate (bps grossBitrate, const Ieee80211OfdmCode *code) const
Constructor & Destructor Documentation
Ieee80211OfdmSignalMode()
inet::physicallayer::Ieee80211OfdmSignalMode::Ieee80211OfdmSignalMode (const Ieee80211OfdmCode * code, const Ieee80211OfdmModulation * modulation, Hz channelSpacing, Hz bandwidth, unsigned int rate)
                                                                                                                                                                              :
     Ieee80211OfdmModeBase(modulation, code, channelSpacing, bandwidth),
     rate(rate)
 {
 }
~Ieee80211OfdmSignalMode()
virtual inet::physicallayer::Ieee80211OfdmSignalMode::~Ieee80211OfdmSignalMode () inline virtual
 {}
Member Function Documentation
createHeader()
virtual Ptr<Ieee80211PhyHeader> inet::physicallayer::Ieee80211OfdmSignalMode::createHeader () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return makeShared<Ieee80211OfdmPhyHeader>(); }
getCode()
const Ieee80211OfdmCode* inet::physicallayer::Ieee80211OfdmSignalMode::getCode () const inline
 { return code; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate().
getDuration()
virtual const simtime_t inet::physicallayer::Ieee80211OfdmSignalMode::getDuration () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return getSymbolInterval(); }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::Ieee80211OfdmMode::getDuration(), inet::physicallayer::Ieee80211HtPreambleMode::getDuration(), and inet::physicallayer::Ieee80211OfdmMode::getPlcpHeaderLength().
getGrossBitrate()
virtual bps inet::physicallayer::Ieee80211OfdmSignalMode::getGrossBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211OfdmModeBase.
 { return Ieee80211OfdmModeBase::getGrossBitrate(); }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createBitModel().
getLength()
virtual b inet::physicallayer::Ieee80211OfdmSignalMode::getLength () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return getRateFieldLength() + getReservedFieldLength() + getLengthFieldLength() + getParityFieldLength() + getTailFieldLength() + getServiceFieldLength(); }
getLengthFieldLength()
b inet::physicallayer::Ieee80211OfdmSignalMode::getLengthFieldLength () const inline
 { return b(12); }
getModulation()
const Ieee80211OfdmModulation* inet::physicallayer::Ieee80211OfdmSignalMode::getModulation () const inline override virtual
Implements inet::physicallayer::IIeee80211HeaderMode.
 { return modulation; }
Referenced by inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createSymbolModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::encodeAndModulate(), and inet::physicallayer::Ieee80211LayeredOfdmTransmitter::~Ieee80211LayeredOfdmTransmitter().
getNetBitrate()
virtual bps inet::physicallayer::Ieee80211OfdmSignalMode::getNetBitrate () const inline override virtual
Reimplemented from inet::physicallayer::Ieee80211OfdmModeBase.
 { return Ieee80211OfdmModeBase::getNetBitrate(); }
getParityFieldLength()
b inet::physicallayer::Ieee80211OfdmSignalMode::getParityFieldLength () const inline
 { return b(1); }
getRate()
unsigned int inet::physicallayer::Ieee80211OfdmSignalMode::getRate () const inline
 { return rate; }
getRateFieldLength()
b inet::physicallayer::Ieee80211OfdmSignalMode::getRateFieldLength () const inline
 { return b(4); }
getReservedFieldLength()
b inet::physicallayer::Ieee80211OfdmSignalMode::getReservedFieldLength () const inline
 { return b(1); }
getServiceFieldLength()
b inet::physicallayer::Ieee80211OfdmSignalMode::getServiceFieldLength () const inline
 { return b(16); }
getTailFieldLength()
b inet::physicallayer::Ieee80211OfdmSignalMode::getTailFieldLength () const inline
 { return b(6); }
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmSignalMode::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     return stream << "Ieee80211OfdmSignalMode";
 }
Member Data Documentation
rate
unsigned int inet::physicallayer::Ieee80211OfdmSignalMode::rate protected
The documentation for this class was generated from the following files:
Ieee80211OfdmMode.h
Ieee80211OfdmMode.cc