INET Framework for OMNeT++/OMNEST: inet::ShortBitVector Class Reference
inet::ShortBitVector Class Reference
Optimized version of the BitVector class to store short bit vectors.
#include <ShortBitVector.h>
Public Member Functions
ShortBitVector ()
ShortBitVector (const char *bitString)
ShortBitVector (unsigned int bits)
ShortBitVector (unsigned int bits, unsigned int size)
ShortBitVector (const ShortBitVector &other)
unsigned int toDecimal () const
unsigned int reverseToDecimal () const
void rightShift (int with)
void leftShift (int with)
void appendBit (bool value)
void appendBit (bool value, int n)
bool getBit (unsigned int pos) const
void setBit (unsigned int pos, bool value)
void toggleBit (unsigned int pos)
bool isEmpty () const
unsigned int getSize () const
unsigned int computeHammingDistance (const ShortBitVector &u) const
ShortBitVector & operator= (const ShortBitVector &other)
bool operator== (const ShortBitVector &rhs) const
bool operator!= (const ShortBitVector &rhs) const
std::string toString () const
Private Member Functions
void copy (const ShortBitVector &other)
Private Attributes
unsigned int bits
unsigned int size
Friends
std::ostream & operator<< (std::ostream &out, const ShortBitVector &bitVector)
Detailed Description
Optimized version of the BitVector class to store short bit vectors.
Constructor & Destructor Documentation
ShortBitVector() [1/5]
inet::ShortBitVector::ShortBitVector ()
 {
     size = 0;
     bits = 0;
 }
ShortBitVector() [2/5]
inet::ShortBitVector::ShortBitVector (const char * bitString)
 {
     size = 0;
     bits = 0;
     int strSize = strlen(bitString);
     for (int i = 0; i < strSize; i++) {
         if (bitString[i] == '1')
             appendBit(true);
         else if (bitString[i] == '0')
             appendBit(false);
         else
             throw cRuntimeError("str must represent a binary number");
     }
 }
ShortBitVector() [3/5]
inet::ShortBitVector::ShortBitVector (unsigned int bits)
 {
     if (num == 0)
         size = 1;
     else
         size = (int)(log(num) / log(2)) + 1;
     bits = num;
 }
ShortBitVector() [4/5]
inet::ShortBitVector::ShortBitVector (unsigned int bits, unsigned int size)
 {
     if (size > sizeof(unsigned int) * 8)
         throw cRuntimeError("size = %u must be less than %lu", size, sizeof(unsigned int) * 8);
     this->size = size;
     this->bits = bits;
 }
ShortBitVector() [5/5]
inet::ShortBitVector::ShortBitVector (const ShortBitVector & other) inline
 { copy(other); }
Member Function Documentation
appendBit() [1/2]
void inet::ShortBitVector::appendBit (bool value) inline
 { setBit(size, value); }
Referenced by inet::physicallayer::ConvolutionalCoder::convertToShortBitVectorMatrix(), inet::physicallayer::ConvolutionalCoder::decode(), inet::physicallayer::ConvolutionalCoder::encode(), inet::physicallayer::Ieee80211OfdmDecoder::getSignalFieldLength(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::getSignalFieldLength(), inet::physicallayer::Ieee80211OfdmDecoder::getSignalFieldRate(), inet::physicallayer::ConvolutionalCoder::giveNextOutputSymbol(), inet::physicallayer::ConvolutionalCoder::inputSymbolToOutputSymbol(), inet::physicallayer::ConvolutionalCoder::setTransferFunctionMatrix(), and ShortBitVector().
appendBit() [2/2]
void inet::ShortBitVector::appendBit (bool value, int n) inline
 { while (n--) appendBit(value); }
Referenced by appendBit().
computeHammingDistance()
unsigned int inet::ShortBitVector::computeHammingDistance (const ShortBitVector & u) const inline
     {
 #ifndef NDEBUG
         if (getSize() != u.getSize())
             throw cRuntimeError("You can't compute Hamming distance between two vectors with different sizes");
 #endif
         unsigned int hammingDistance = bits ^ u.toDecimal();
         hammingDistance = hammingDistance - ((hammingDistance >> 1) & 0x55555555);
         hammingDistance = (hammingDistance & 0x33333333) + ((hammingDistance >> 2) & 0x33333333);
         return (((hammingDistance + (hammingDistance >> 4)) & 0x0F0F0F0F) * 0x01010101) >> 24;
     }
copy()
void inet::ShortBitVector::copy (const ShortBitVector & other) inline private
     {
         size = other.size;
         bits = other.bits;
     }
getBit()
bool inet::ShortBitVector::getBit (unsigned int pos) const inline
     {
 #ifndef NDEBUG
         if (pos >= size)
             throw cRuntimeError("Out of range with bit position %d", pos);
 #endif
         return bits & (1 << pos);
     }
Referenced by inet::physicallayer::ConvolutionalCoder::computeStateTransitions(), inet::physicallayer::LayeredErrorModelBase::computeSymbolModel(), inet::physicallayer::ApskDemodulator::demodulate(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol(), inet::physicallayer::ConvolutionalCoder::encode(), inet::physicallayer::AdditiveScrambler::generateScramblingSequence(), inet::physicallayer::ConvolutionalCoder::inputSymbolToOutputSymbol(), inet::physicallayer::ConvolutionalCoder::modulo2Adder(), inet::operator<<(), inet::physicallayer::ConvolutionalCoder::setTransferFunctionMatrix(), toString(), and inet::physicallayer::ConvolutionalCoder::traversePath().
getSize()
unsigned int inet::ShortBitVector::getSize () const inline
 { return size; }
Referenced by inet::physicallayer::ConvolutionalCoder::computeHammingDistance(), computeHammingDistance(), inet::physicallayer::ConvolutionalCoder::computeStateTransitions(), inet::physicallayer::LayeredErrorModelBase::computeSymbolModel(), inet::physicallayer::ApskDemodulator::demodulate(), inet::physicallayer::Ieee80211OfdmDemodulator::demodulateSymbol(), inet::physicallayer::ConvolutionalCoder::encode(), inet::physicallayer::AdditiveScrambler::generateScramblingSequence(), inet::physicallayer::ConvolutionalCoder::inputSymbolToOutputSymbol(), inet::physicallayer::ConvolutionalCoder::modulo2Adder(), inet::operator<<(), inet::physicallayer::ConvolutionalCoder::setTransferFunctionMatrix(), toString(), and inet::physicallayer::ConvolutionalCoder::traversePath().
isEmpty()
bool inet::ShortBitVector::isEmpty () const inline
 { return size == 0; }
Referenced by inet::physicallayer::ConvolutionalCoder::computeHammingDistance(), and inet::physicallayer::ConvolutionalCoder::decode().
leftShift()
void inet::ShortBitVector::leftShift (int with) inline
 { bits = bits << with; }
Referenced by inet::physicallayer::ConvolutionalCoder::computeStateTransitions(), and inet::physicallayer::AdditiveScrambler::generateScramblingSequence().
operator!=()
bool inet::ShortBitVector::operator!= (const ShortBitVector & rhs) const inline
 { return !(rhs == *this); }
operator=()
ShortBitVector& inet::ShortBitVector::operator= (const ShortBitVector & other) inline
     {
         if (this == &other)
             return *this;
         copy(other);
         return *this;
     }
operator==()
bool inet::ShortBitVector::operator== (const ShortBitVector & rhs) const inline
 { return rhs.bits == bits; }
reverseToDecimal()
unsigned int inet::ShortBitVector::reverseToDecimal () const inline
     {
         unsigned int decimal = 0;
         unsigned int powerOfTwo = 1;
         for (int i = getSize() - 1; i >= 0; i--) {
             if (getBit(i))
                 decimal += powerOfTwo;
             powerOfTwo *= 2;
         }
         return decimal;
     }
Referenced by inet::physicallayer::ConvolutionalCoder::computeDecimalToOutputSymbolVector(), inet::physicallayer::ConvolutionalCoder::computeOutputAndInputSymbols(), inet::physicallayer::ConvolutionalCoder::computeStateTransitions(), inet::physicallayer::ConvolutionalCoder::encode(), and inet::physicallayer::ConvolutionalCoder::printOutputs().
rightShift()
void inet::ShortBitVector::rightShift (int with) inline
 { bits = bits >> with; }
setBit()
void inet::ShortBitVector::setBit (unsigned int pos, bool value) inline
     {
 #ifndef NDEBUG
         if (pos >= sizeof(unsigned int) * 8)
             throw cRuntimeError("Out of range with bit position: %d", pos);
 #endif
         if (pos + 1 > size)
             size = pos + 1;
         if (value)
             bits |= 1 << pos;
         else
             bits &= ~(1 << pos);
     }
Referenced by inet::physicallayer::ConvolutionalCoder::computeStateTransitions(), inet::physicallayer::LayeredErrorModelBase::computeSymbolModel(), inet::physicallayer::AdditiveScrambler::generateScramblingSequence(), inet::physicallayer::ConvolutionalCoder::giveNextOutputSymbol(), inet::physicallayer::ConvolutionalCoder::inputSymbolToOutputSymbol(), inet::physicallayer::ApskModulator::modulate(), and inet::physicallayer::Ieee80211OfdmModulator::modulate().
toDecimal()
unsigned int inet::ShortBitVector::toDecimal () const inline
 { return bits; }
Referenced by inet::physicallayer::ConvolutionalCoder::computeHammingDistance(), computeHammingDistance(), inet::physicallayer::Ieee80211OfdmDecoder::getSignalFieldLength(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::getSignalFieldLength(), and inet::physicallayer::ApskModulationBase::mapToConstellationDiagram().
toggleBit()
void inet::ShortBitVector::toggleBit (unsigned int pos) inline
     {
 #ifndef NDEBUG
         if (pos >= size)
             throw cRuntimeError("Out of range with bit position %d", pos);
 #endif
         bits ^= 1 << pos;
     }
toString()
std::string inet::ShortBitVector::toString () const
 {
     std::string str;
     for (unsigned int i = 0; i < getSize(); i++) {
         if (getBit(i))
             str += "1";
         else
             str += "0";
     }
     return str;
 }
Friends And Related Function Documentation
operator<<
std::ostream& operator<< (std::ostream & out, const ShortBitVector & bitVector) friend
 {
     for (unsigned int i = 0; i < bitVector.getSize(); i++) {
         if (i != 0)
             out << " ";
         if (bitVector.getBit(i))
             out << "1";
         else
             out << "0";
     }
     return out;
 }
Member Data Documentation
bits
unsigned int inet::ShortBitVector::bits private
Referenced by copy(), operator==(), and ShortBitVector().
size
unsigned int inet::ShortBitVector::size private
Referenced by copy(), and ShortBitVector().
The documentation for this class was generated from the following files:
ShortBitVector.h
ShortBitVector.cc