INET Framework for OMNeT++/OMNEST: inet::physicallayer::ICommunicationCache Class Reference
inet::physicallayer::ICommunicationCache Class Reference abstract
This interface is used to store the radios and transmissions of the medium.
#include <ICommunicationCache.h>
Public Member Functions
virtual ~ICommunicationCache ()
Radio cache
virtual void addRadio (const IRadio *radio)=0
virtual void removeRadio (const IRadio *radio)=0
virtual const IRadio * getRadio (int id) const =0
virtual void mapRadios (std::function< void(const IRadio *)> f) const =0
virtual int getNumRadios () const =0
Transmission cache
virtual void addTransmission (const ITransmission *transmission)=0
virtual void removeTransmission (const ITransmission *transmission)=0
virtual const ITransmission * getTransmission (int id) const =0
virtual void mapTransmissions (std::function< void(const ITransmission *)> f) const =0
virtual int getNumTransmissions () const =0
Interference cache
virtual std::vector< const ITransmission * > * computeInterferingTransmissions (const IRadio *radio, const simtime_t startTime, const simtime_t endTime)=0
virtual void removeNonInterferingTransmissions (std::function< void(const ITransmission *transmission)> f)=0
virtual const simtime_t getCachedInterferenceEndTime (const ITransmission *transmission)=0
virtual void setCachedInterferenceEndTime (const ITransmission *transmission, const simtime_t interferenceEndTime)=0
virtual void removeCachedInterferenceEndTime (const ITransmission *transmission)=0
virtual const IWirelessSignal * getCachedSignal (const ITransmission *transmission)=0
virtual void setCachedSignal (const ITransmission *transmission, const IWirelessSignal *signal)=0
virtual void removeCachedSignal (const ITransmission *transmission)=0
Reception Cache
virtual const IArrival * getCachedArrival (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedArrival (const IRadio *receiver, const ITransmission *transmission, const IArrival *arrival)=0
virtual void removeCachedArrival (const IRadio *receiver, const ITransmission *transmission)=0
virtual const IntervalTree::Interval * getCachedInterval (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedInterval (const IRadio *receiver, const ITransmission *transmission, const IntervalTree::Interval *interval)=0
virtual void removeCachedInterval (const IRadio *receiver, const ITransmission *transmission)=0
virtual const IListening * getCachedListening (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedListening (const IRadio *receiver, const ITransmission *transmission, const IListening *listening)=0
virtual void removeCachedListening (const IRadio *receiver, const ITransmission *transmission)=0
virtual const IReception * getCachedReception (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedReception (const IRadio *receiver, const ITransmission *transmission, const IReception *reception)=0
virtual void removeCachedReception (const IRadio *receiver, const ITransmission *transmission)=0
virtual const IInterference * getCachedInterference (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedInterference (const IRadio *receiver, const ITransmission *transmission, const IInterference *interference)=0
virtual void removeCachedInterference (const IRadio *receiver, const ITransmission *transmission)=0
virtual const INoise * getCachedNoise (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedNoise (const IRadio *receiver, const ITransmission *transmission, const INoise *noise)=0
virtual void removeCachedNoise (const IRadio *receiver, const ITransmission *transmission)=0
virtual const ISnir * getCachedSNIR (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedSNIR (const IRadio *receiver, const ITransmission *transmission, const ISnir *snir)=0
virtual void removeCachedSNIR (const IRadio *receiver, const ITransmission *transmission)=0
virtual const IReceptionDecision * getCachedReceptionDecision (const IRadio *receiver, const ITransmission *transmission, IRadioSignal::SignalPart part)=0
virtual void setCachedReceptionDecision (const IRadio *receiver, const ITransmission *transmission, IRadioSignal::SignalPart part, const IReceptionDecision *receptionDecision)=0
virtual void removeCachedReceptionDecision (const IRadio *receiver, const ITransmission *transmission, IRadioSignal::SignalPart part)=0
virtual const IReceptionResult * getCachedReceptionResult (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedReceptionResult (const IRadio *receiver, const ITransmission *transmission, const IReceptionResult *receptionResult)=0
virtual void removeCachedReceptionResult (const IRadio *receiver, const ITransmission *transmission)=0
virtual const IWirelessSignal * getCachedSignal (const IRadio *receiver, const ITransmission *transmission)=0
virtual void setCachedSignal (const IRadio *receiver, const ITransmission *transmission, const IWirelessSignal *signal)=0
virtual void removeCachedSignal (const IRadio *receiver, const ITransmission *transmission)=0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
This interface is used to store the radios and transmissions of the medium.
It also provides caching for various intermediate computation results related to the communication on the medium.
Constructor & Destructor Documentation
~ICommunicationCache()
virtual inet::physicallayer::ICommunicationCache::~ICommunicationCache () inline virtual
 {}
Member Function Documentation
addRadio()
virtual void inet::physicallayer::ICommunicationCache::addRadio (const IRadio * radio) pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::addRadio().
addTransmission()
virtual void inet::physicallayer::ICommunicationCache::addTransmission (const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::addTransmission().
computeInterferingTransmissions()
virtual std::vector<const ITransmission *>* inet::physicallayer::ICommunicationCache::computeInterferingTransmissions (const IRadio * radio, const simtime_t startTime, const simtime_t endTime) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::computeInterferingReceptions().
getCachedArrival()
virtual const IArrival* inet::physicallayer::ICommunicationCache::getCachedArrival (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::getArrival().
getCachedInterference()
virtual const IInterference* inet::physicallayer::ICommunicationCache::getCachedInterference (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getInterference().
getCachedInterferenceEndTime()
virtual const simtime_t inet::physicallayer::ICommunicationCache::getCachedInterferenceEndTime (const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::addTransmission(), and inet::physicallayer::RadioMedium::removeNonInterferingTransmissions().
getCachedInterval()
virtual const IntervalTree::Interval* inet::physicallayer::ICommunicationCache::getCachedInterval (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
getCachedListening()
virtual const IListening* inet::physicallayer::ICommunicationCache::getCachedListening (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::getInterference(), inet::physicallayer::RadioMedium::getListening(), inet::physicallayer::RadioMedium::getNoise(), inet::physicallayer::RadioMedium::receivePacket(), and inet::physicallayer::RadioMedium::receiveSignal().
getCachedNoise()
virtual const INoise* inet::physicallayer::ICommunicationCache::getCachedNoise (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getNoise().
getCachedReception()
virtual const IReception* inet::physicallayer::ICommunicationCache::getCachedReception (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getReception().
getCachedReceptionDecision()
virtual const IReceptionDecision* inet::physicallayer::ICommunicationCache::getCachedReceptionDecision (const IRadio * receiver, const ITransmission * transmission, IRadioSignal::SignalPart part) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::getReceptionDecision().
getCachedReceptionResult()
virtual const IReceptionResult* inet::physicallayer::ICommunicationCache::getCachedReceptionResult (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::getReceptionResult().
getCachedSignal() [1/2]
virtual const IWirelessSignal* inet::physicallayer::ICommunicationCache::getCachedSignal (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
getCachedSignal() [2/2]
virtual const IWirelessSignal* inet::physicallayer::ICommunicationCache::getCachedSignal (const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::pickUpSignals().
getCachedSNIR()
virtual const ISnir* inet::physicallayer::ICommunicationCache::getCachedSNIR (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getSNIR().
getNumRadios()
virtual int inet::physicallayer::ICommunicationCache::getNumRadios () const pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
getNumTransmissions()
virtual int inet::physicallayer::ICommunicationCache::getNumTransmissions () const pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
getRadio()
virtual const IRadio* inet::physicallayer::ICommunicationCache::getRadio (int id) const pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getRadio().
getTransmission()
virtual const ITransmission* inet::physicallayer::ICommunicationCache::getTransmission (int id) const pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getTransmission().
mapRadios()
virtual void inet::physicallayer::ICommunicationCache::mapRadios (std::function< void(const IRadio *)> f) const pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::addTransmission(), inet::physicallayer::CommunicationCacheBase::getNumRadios(), and inet::physicallayer::RadioMedium::sendToAllRadios().
mapTransmissions()
virtual void inet::physicallayer::ICommunicationCache::mapTransmissions (std::function< void(const ITransmission *)> f) const pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::addRadio(), inet::physicallayer::CommunicationCacheBase::getNumTransmissions(), inet::physicallayer::RadioMedium::pickUpSignals(), inet::physicallayer::RadioMedium::receiveSignal(), and inet::physicallayer::RadioMedium::removeNonInterferingTransmissions().
removeCachedArrival()
virtual void inet::physicallayer::ICommunicationCache::removeCachedArrival (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedInterference()
virtual void inet::physicallayer::ICommunicationCache::removeCachedInterference (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedInterferenceEndTime()
virtual void inet::physicallayer::ICommunicationCache::removeCachedInterferenceEndTime (const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedInterval()
virtual void inet::physicallayer::ICommunicationCache::removeCachedInterval (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedListening()
virtual void inet::physicallayer::ICommunicationCache::removeCachedListening (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedNoise()
virtual void inet::physicallayer::ICommunicationCache::removeCachedNoise (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedReception()
virtual void inet::physicallayer::ICommunicationCache::removeCachedReception (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedReceptionDecision()
virtual void inet::physicallayer::ICommunicationCache::removeCachedReceptionDecision (const IRadio * receiver, const ITransmission * transmission, IRadioSignal::SignalPart part) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedReceptionResult()
virtual void inet::physicallayer::ICommunicationCache::removeCachedReceptionResult (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::receivePacket().
removeCachedSignal() [1/2]
virtual void inet::physicallayer::ICommunicationCache::removeCachedSignal (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedSignal() [2/2]
virtual void inet::physicallayer::ICommunicationCache::removeCachedSignal (const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeCachedSNIR()
virtual void inet::physicallayer::ICommunicationCache::removeCachedSNIR (const IRadio * receiver, const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
removeNonInterferingTransmissions()
virtual void inet::physicallayer::ICommunicationCache::removeNonInterferingTransmissions (std::function< void(const ITransmission *transmission)> f) pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::removeNonInterferingTransmissions().
removeRadio()
virtual void inet::physicallayer::ICommunicationCache::removeRadio (const IRadio * radio) pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::removeRadio().
removeTransmission()
virtual void inet::physicallayer::ICommunicationCache::removeTransmission (const ITransmission * transmission) pure virtual
Implemented in inet::physicallayer::VectorCommunicationCache, inet::physicallayer::MapCommunicationCache, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::removeTransmission().
setCachedArrival()
virtual void inet::physicallayer::ICommunicationCache::setCachedArrival (const IRadio * receiver, const ITransmission * transmission, const IArrival * arrival) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::addRadio().
setCachedInterference()
virtual void inet::physicallayer::ICommunicationCache::setCachedInterference (const IRadio * receiver, const ITransmission * transmission, const IInterference * interference) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getInterference().
setCachedInterferenceEndTime()
virtual void inet::physicallayer::ICommunicationCache::setCachedInterferenceEndTime (const ITransmission * transmission, const simtime_t interferenceEndTime) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::addTransmission().
setCachedInterval()
virtual void inet::physicallayer::ICommunicationCache::setCachedInterval (const IRadio * receiver, const ITransmission * transmission, const IntervalTree::Interval * interval) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
setCachedListening()
virtual void inet::physicallayer::ICommunicationCache::setCachedListening (const IRadio * receiver, const ITransmission * transmission, const IListening * listening) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::addRadio(), and inet::physicallayer::RadioMedium::receiveSignal().
setCachedNoise()
virtual void inet::physicallayer::ICommunicationCache::setCachedNoise (const IRadio * receiver, const ITransmission * transmission, const INoise * noise) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getNoise().
setCachedReception()
virtual void inet::physicallayer::ICommunicationCache::setCachedReception (const IRadio * receiver, const ITransmission * transmission, const IReception * reception) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getReception().
setCachedReceptionDecision()
virtual void inet::physicallayer::ICommunicationCache::setCachedReceptionDecision (const IRadio * receiver, const ITransmission * transmission, IRadioSignal::SignalPart part, const IReceptionDecision * receptionDecision) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::getReceptionDecision().
setCachedReceptionResult()
virtual void inet::physicallayer::ICommunicationCache::setCachedReceptionResult (const IRadio * receiver, const ITransmission * transmission, const IReceptionResult * receptionResult) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::getReceptionResult().
setCachedSignal() [1/2]
virtual void inet::physicallayer::ICommunicationCache::setCachedSignal (const IRadio * receiver, const ITransmission * transmission, const IWirelessSignal * signal) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
setCachedSignal() [2/2]
virtual void inet::physicallayer::ICommunicationCache::setCachedSignal (const ITransmission * transmission, const IWirelessSignal * signal) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase.
Referenced by inet::physicallayer::RadioMedium::pickUpSignals(), inet::physicallayer::RadioMedium::sendToRadio(), and inet::physicallayer::RadioMedium::transmitPacket().
setCachedSNIR()
virtual void inet::physicallayer::ICommunicationCache::setCachedSNIR (const IRadio * receiver, const ITransmission * transmission, const ISnir * snir) pure virtual
Implemented in inet::physicallayer::CommunicationCacheBase, and inet::physicallayer::ReferenceCommunicationCache.
Referenced by inet::physicallayer::RadioMedium::getSNIR().
The documentation for this class was generated from the following file:
ICommunicationCache.h