INET Framework for OMNeT++/OMNEST: inet::FieldsChunk Class Reference
inet::FieldsChunk Class Reference
This is a base class for classes that represent data using various fields.
#include <FieldsChunk.h>
Public Member Functions
Constructors, destructors and duplication related functions
FieldsChunk ()
FieldsChunk (const FieldsChunk &other)
virtual ~FieldsChunk ()
virtual void parsimPack (cCommBuffer *buffer) const override
virtual void parsimUnpack (cCommBuffer *buffer) override
virtual void handleChange () override
Overridden chunk functions
virtual ChunkType getChunkType () const override
Returns the type of this chunk as an enum member.
virtual bool containsSameData (const Chunk &other) const override
Returns true if the two chunks represent the same binary data.
virtual b getChunkLength () const override
Returns the length of data represented by this chunk.
virtual void setChunkLength (b chunkLength)
virtual void addChunkLength (b chunkLength)
virtual std::ostream & printFieldsToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Public Member Functions inherited from inet::Chunk
Chunk ()
Chunk (const Chunk &other)
virtual const Ptr< Chunk > dupShared () const
Returns a mutable copy of this chunk in a shared pointer.
virtual void forEachChild (cVisitor *v) override
virtual bool isMutable () const
virtual bool isImmutable () const
virtual void markImmutable ()
void markMutableIfExclusivelyOwned ()
virtual bool isComplete () const
virtual bool isIncomplete () const
virtual void markIncomplete ()
virtual bool isCorrect () const
virtual bool isIncorrect () const
virtual void markIncorrect ()
virtual bool isProperlyRepresented () const
virtual bool isImproperlyRepresented () const
virtual void markImproperlyRepresented ()
virtual void moveIterator (Iterator &iterator, b length) const
virtual void seekIterator (Iterator &iterator, b position) const
virtual bool canInsertAtFront (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAtBack (const Ptr< const Chunk > &chunk) const
Returns true if this chunk is capable of representing the result.
virtual bool canInsertAt (const Ptr< const Chunk > &chunk, b offset) const
Returns true if this chunk is capable of representing the result.
void insertAtFront (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the beginning of this chunk.
void insertAtBack (const Ptr< const Chunk > &chunk)
Inserts the provided chunk at the end of this chunk.
void insertAt (const Ptr< const Chunk > &chunk, b offset)
Inserts the provided chunk into this chunk.
virtual bool canRemoveAtFront (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAtBack (b length) const
Returns true if this chunk is capable of representing the result.
virtual bool canRemoveAt (b offset, b length) const
Returns true if this chunk is capable of representing the result.
void removeAtFront (b length)
Removes the requested part from the beginning of this chunk.
void removeAtBack (b length)
Removes the requested part from the end of this chunk.
void removeAt (b offset, b length)
Removes the requested part from this chunk.
int getChunkId () const
Returns the sequentially assigned id.
virtual bool isEmpty () const
Returns true if this chunk contains no data.
const Ptr< Chunk > simplify () const
Returns the simplified representation of this chunk eliminating all potential redundancies.
const Ptr< Chunk > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in its default representation.
template<typename T >
bool has (const Iterator &iterator, b length=unspecifiedLength) const
Returns whether if the designated part of the data is available in the requested representation.
template<typename T >
const Ptr< T > peek (const Iterator &iterator, b length=unspecifiedLength, int flags=0) const
Returns the designated part of the data represented by this chunk in the requested representation.
virtual SharingRegionTagSet & getRegionTags () override
Returns all region tags.
int getNumTags () const
Returns the number of chunk tags.
const Ptr< const TagBase > getTag (int index) const
Returns the chunk tag at the given index.
void clearTags (b offset=b(0), b length=b(-1))
Clears the set of chunk tags in the given region.
void copyTags (const Chunk &source, b sourceOffset=b(0), b offset=b(0), b length=b(-1))
Copies the set of chunk tags from the source region to the provided region.
template<typename T >
const Ptr< const T > findTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or returns nullptr if no such chunk tag is found.
template<typename T >
const Ptr< const T > getTag (b offset=b(0), b length=b(-1)) const
Returns the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
void mapAllTags (b offset, b length, std::function< void(b, b, const Ptr< const T > &)> f) const
Maps all tags in the provided range to to the function.
template<typename T >
void mapAllTagsForUpdate (b offset, b length, std::function< void(b, b, const Ptr< T > &)> f)
Maps all tags in the provided range to to the function.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< const T > > getAllTags (b offset=b(0), b length=b(-1)) const
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > getAllTagsForUpdate (b offset=b(0), b length=b(-1))
Returns all chunk tags for the provided type and range in a detached vector of region tags.
template<typename T >
const Ptr< T > addTag (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range, or throws an exception if such a chunk tag is already present.
template<typename T >
const Ptr< T > addTagIfAbsent (b offset=b(0), b length=b(-1))
Returns a newly added chunk tag for the provided type and range if absent, or returns the chunk tag that is already present.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > addTagsWhereAbsent (b offset=b(0), b length=b(-1))
Returns the newly added chunk tags for the provided type and range where the tag is absent.
template<typename T >
const Ptr< T > removeTag (b offset, b length)
Removes the chunk tag for the provided type and range, or throws an exception if no such chunk tag is found.
template<typename T >
const Ptr< T > removeTagIfPresent (b offset, b length)
Removes the chunk tag for the provided type and range if present, or returns nullptr if no such chunk tag is found.
template<typename T >
std::vector< SharingRegionTagSet::RegionTag< T > > removeTagsWherePresent (b offset, b length)
Removes and returns all chunk tags for the provided type and range.
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints an optinally formatted human readable string representation of the data present in this chunk to the given stream.
virtual std::string str () const override
Returns a human readable string representation of the data present in this chunk.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
b chunkLength
const std::vector< uint8_t > * serializedBytes
The serialized representation of this chunk or nullptr if not available.
Protected Attributes inherited from inet::Chunk
int id
The id is automatically assigned sequentially during construction.
int flags
The boolean chunk flags are merged into a single integer.
SharingRegionTagSet regionTags
The set of region tags attached to the data represented by this chunk.
const typedef Ptr< Chunk >(* PeekConverter)(const Ptr< Chunk > &chunk, const Chunk::Iterator &iterator, b length, int flags)
Friends
class Chunk
class FieldsChunkSerializer
Field accessor functions
const std::vector< uint8_t > * getSerializedBytes () const
void setSerializedBytes (const std::vector< uint8_t > *bytes) const
virtual const Ptr< Chunk > peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator &iterator, b length, int flags) const override
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Additional Inherited Members
Public Types inherited from inet::Chunk
enum ChunkType {
CT_EMPTY, CT_BITCOUNT, CT_BITS, CT_BYTECOUNT,
CT_BYTES, CT_SLICE, CT_ENCRYPTED, CT_CPACKET,
CT_SEQUENCE, CT_FIELDS
}
This enum is used to avoid std::dynamic_cast and dynamicPtrCast.
enum PeekFlag {
PF_ALLOW_NULLPTR = (1 << 0), PF_ALLOW_EMPTY = (1 << 1), PF_ALLOW_INCOMPLETE = (1 << 2), PF_ALLOW_INCORRECT = (1 << 3),
PF_ALLOW_IMPROPERLY_REPRESENTED = (1 << 4), PF_ALLOW_SERIALIZATION = (1 << 5), PF_ALLOW_ALL = -1
}
This enum specifies bitmasks for the flags argument of various peek functions.
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Static Public Member Functions inherited from inet::Chunk
static void serialize (MemoryOutputStream &stream, const Ptr< const Chunk > &chunk, b offset=b(0), b length=b(-1))
Serializes a chunk into the given stream.
static const Ptr< Chunk > deserialize (MemoryInputStream &stream, const std::type_info &typeInfo)
Deserializes a chunk from the given stream.
Static Public Attributes inherited from inet::Chunk
static const b unspecifiedLength = b(-std::numeric_limits<int64_t>::max())
static bool enableImplicitChunkSerialization = false
Peeking some part into a chunk that requires automatic serialization will throw an exception when implicit chunk serialization is disabled.
static int nextId = 0
Protected Types inherited from inet::Chunk
enum ChunkFlag { CF_IMMUTABLE = (1 << 0), CF_INCOMPLETE = (1 << 1), CF_INCORRECT = (1 << 2), CF_IMPROPERLY_REPRESENTED = (1 << 3) }
This enum specifies bitmasks for the flags field of Chunk.
typedef bool(* PeekPredicate) (const Ptr< Chunk > &)
Protected Member Functions inherited from inet::Chunk
int getBinDumpNumLines () const
int getHexDumpNumLines () const
const char * getBinDumpLine (int index)
const char * getHexDumpLine (int index)
const SharingRegionTagSet::RegionTag< TagBase > & _getTag (int index) const
void checkMutable () const
virtual void doInsertAtFront (const Ptr< const Chunk > &chunk)
virtual void doInsertAtBack (const Ptr< const Chunk > &chunk)
virtual void doInsertAt (const Ptr< const Chunk > &chunk, b offset)
virtual void doRemoveAtFront (b length)
virtual void doRemoveAtBack (b length)
virtual void doRemoveAt (b offset, b length)
template<typename T >
const Ptr< T > peekConverted (const Iterator &iterator, b length, int flags) const
template<typename T >
const Ptr< T > checkPeekResult (const Ptr< T > &chunk, int flags) const
Static Protected Member Functions inherited from inet::Chunk
static const Ptr< Chunk > convertChunk (const std::type_info &typeInfo, const Ptr< Chunk > &chunk, b offset, b length, int flags)
Creates a new chunk of the given type that represents the designated part of the provided chunk.
Detailed Description
This is a base class for classes that represent data using various fields.
These classes are most often generated by the omnetpp message compiler.
Constructor & Destructor Documentation
FieldsChunk() [1/2]
inet::FieldsChunk::FieldsChunk ()
                          :
     Chunk(),
     chunkLength(b(-1)),
     serializedBytes(nullptr)
 {
 }
FieldsChunk() [2/2]
inet::FieldsChunk::FieldsChunk (const FieldsChunk & other)
                                                  :
     Chunk(other),
     chunkLength(other.chunkLength),
     serializedBytes(other.serializedBytes != nullptr ? new std::vector<uint8_t>(*other.serializedBytes) : nullptr)
 {
 }
~FieldsChunk()
inet::FieldsChunk::~FieldsChunk () virtual
 {
     delete serializedBytes;
 }
Member Function Documentation
addChunkLength()
virtual void inet::FieldsChunk::addChunkLength (b chunkLength) inline virtual
 { handleChange(); this->chunkLength += chunkLength; }
Referenced by inet::rtp::RtcpReceiverReportPacket::addReceptionReport(), inet::rtp::RtcpSdesPacket::addSDESChunk(), and inet::sctp::SctpHeader::removeLastChunk().
containsSameData()
bool inet::FieldsChunk::containsSameData (const Chunk & other) const override virtual
Returns true if the two chunks represent the same binary data.
The two chunks are compared without serialization, and the method is allowed to return false if the result cannot be determined correctly. Tags and other metadata are ignored in the comparison.
Reimplemented from inet::Chunk.
 {
     if (&other == this)
         return true;
     else if (!Chunk::containsSameData(other))
         return false;
     else {
         // KLUDGE should we generate this method from the MSG compiler?
         // this implementation returns false if it cannot determine the result correctly
         auto thisDescriptor = getDescriptor();
         auto otherDescriptor = other.getDescriptor();
         if (thisDescriptor != otherDescriptor)
             return false;
         auto thisVoidPtr = toAnyPtr(this);
         auto otherVoidPtr = toAnyPtr(static_cast<const FieldsChunk *>(&other));
         for (int field = 0; field < thisDescriptor->getFieldCount(); field++) {
             auto declaredOn = thisDescriptor->getFieldDeclaredOn(field);
             if (!strcmp(declaredOn, "omnetpp::cObject") || !strcmp(declaredOn, "inet::Chunk") || !strcmp(declaredOn, "inet::FieldsChunk"))
                 continue;
             auto flags = thisDescriptor->getFieldTypeFlags(field);
             if ((flags & cClassDescriptor::FD_ISARRAY) || (flags & cClassDescriptor::FD_ISCOMPOUND) || (flags & cClassDescriptor::FD_ISPOINTER))
                 return false;
             auto thisValue = thisDescriptor->getFieldValueAsString(thisVoidPtr, field, 0);
             auto otherValue = otherDescriptor->getFieldValueAsString(otherVoidPtr, field, 0);
             if (thisValue != otherValue)
                 return false;
         }
         return true;
     }
 }
convertChunk()
static const Ptr<Chunk> inet::FieldsChunk::convertChunk (const std::type_info & typeInfo, const Ptr< Chunk > & chunk, b offset, b length, int flags) inline static protected
{
         return Chunk::convertChunk(typeInfo, chunk, offset, length, flags);
     }
getChunkLength()
virtual b inet::FieldsChunk::getChunkLength () const inline override virtual
Returns the length of data represented by this chunk.
Implements inet::Chunk.
 { CHUNK_CHECK_IMPLEMENTATION(chunkLength >= b(0)); return chunkLength; }
Referenced by inet::Ipv6FragBuf::addFragment(), inet::ieee80211::MsduAggregation::aggregateFrames(), inet::Ipv6Header::calculateFragmentLength(), inet::ieee80211::BasicFragmentationPolicy::computeFragmentSizes(), inet::sctp::SctpHeader::copy(), inet::ieee80211::MpduDeaggregation::deaggregateFrame(), inet::ieee80211::MsduDeaggregation::deaggregateFrame(), inet::sctp::Sctp::handleMessage(), inet::rtp::RtcpPacket::paddingAndSetLength(), peekUnchecked(), inet::sctp::SctpAssociation::process_RCV_Message(), inet::EthernetFcsChecker::processPacket(), inet::physicallayer::EthernetFragmentPhyHeaderChecker::processPacket(), inet::Gptp::receiveSignal(), inet::sctp::SctpAssociation::sendPacketDrop(), inet::sctp::SctpHeaderSerializer::serialize(), inet::tcp::TcpHeader::str(), and inet::EthernetMacBase::verifyCrcAndLength().
getChunkType()
virtual ChunkType inet::FieldsChunk::getChunkType () const inline override virtual
Returns the type of this chunk as an enum member.
This can be used to avoid expensive std::dynamic_cast and dynamicPtrCast operators.
Implements inet::Chunk.
 { return CT_FIELDS; }
getSerializedBytes()
const std::vector<uint8_t>* inet::FieldsChunk::getSerializedBytes () const inline protected
 { return serializedBytes; }
handleChange()
void inet::FieldsChunk::handleChange () override virtual
Reimplemented from inet::Chunk.
 {
     Chunk::handleChange();
     delete serializedBytes;
     serializedBytes = nullptr;
 }
Referenced by inet::Ipv4Header::addOption(), inet::rtp::RtcpReceiverReportPacket::addReceptionReport(), inet::rtp::RtcpSdesPacket::addSDESChunk(), inet::sctp::SctpHeader::appendSctpChunks(), inet::Ipv6Header::findExtensionHeaderByTypeForUpdate(), inet::Ipv4Header::findMutableOptionByType(), inet::sctp::SctpHeader::insertSctpChunks(), inet::rtp::RtcpPacket::paddingAndSetLength(), inet::Ipv6Header::removeExtensionHeader(), inet::sctp::SctpHeader::removeFirstChunk(), inet::Ipv6Header::removeFirstExtensionHeader(), inet::sctp::SctpHeader::removeLastChunk(), and inet::sctp::SctpHeader::setSctpChunks().
parsimPack()
void inet::FieldsChunk::parsimPack (cCommBuffer * buffer) const override virtual
Reimplemented from inet::Chunk.
 {
     Chunk::parsimPack(buffer);
     buffer->pack(chunkLength.get());
 }
parsimUnpack()
void inet::FieldsChunk::parsimUnpack (cCommBuffer * buffer) override virtual
Reimplemented from inet::Chunk.
 {
     Chunk::parsimUnpack(buffer);
     int64_t l;
     buffer->unpack(l);
     chunkLength = b(l);
     delete serializedBytes;
     serializedBytes = nullptr;
 }
peekUnchecked()
const Ptr< Chunk > inet::FieldsChunk::peekUnchecked (PeekPredicate predicate, PeekConverter converter, const Iterator & iterator, b length, int flags) const override protected virtual
Implements inet::Chunk.
 {
     b chunkLength = getChunkLength();
     CHUNK_CHECK_USAGE(b(0) <= iterator.getPosition() && iterator.getPosition() <= chunkLength, "iterator is out of range");
     // 1. peeking an empty part returns nullptr
     if (length == b(0) || (iterator.getPosition() == chunkLength && length < b(0))) {
         if (predicate == nullptr || predicate(nullptr))
             return EmptyChunk::getEmptyChunk(flags);
     }
     // 2. peeking the whole part returns this chunk
     if (iterator.getPosition() == b(0) && (-length >= chunkLength || length == chunkLength)) {
         auto result = const_cast<FieldsChunk *>(this)->shared_from_this();
         if (predicate == nullptr || predicate(result))
             return result;
     }
     // 3. peeking a part from the beginning without conversion returns an incomplete copy of this chunk
     if (predicate != nullptr && predicate(const_cast<FieldsChunk *>(this)->shared_from_this()) && iterator.getPosition() == b(0)) {
         auto copy = staticPtrCast<FieldsChunk>(dupShared());
         copy->setChunkLength(length);
         copy->regionTags.copyTags(regionTags, iterator.getPosition(), b(0), length);
         copy->markIncomplete();
         return copy;
     }
     // 4. peeking without conversion returns a SliceChunk
     if (converter == nullptr)
         return peekConverted<SliceChunk>(iterator, length, flags);
     // 5. peeking with conversion
     return converter(const_cast<FieldsChunk *>(this)->shared_from_this(), iterator, length, flags);
 }
printFieldsToStream()
std::ostream & inet::FieldsChunk::printFieldsToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints an optinally formatted human readable string representation of the feilds of this chunk to the given stream.
Reimplemented from inet::Chunk.
 {
     auto className = getClassName();
     auto descriptor = getDescriptor();
     // TODO make this more sophisticated, e.g. add properties to fields to control what is printed
     if (level <= PRINT_LEVEL_DETAIL)
         for (int i = 0; i < descriptor->getFieldCount(); i++)
             if (!descriptor->getFieldIsArray(i) && !strcmp(className, descriptor->getFieldDeclaredOn(i)))
                 stream << ", " << EV_BOLD << descriptor->getFieldName(i) << EV_NORMAL << " = " << descriptor->getFieldValueAsString(toAnyPtr(this), i, 0);
     return stream;
 }
setChunkLength()
virtual void inet::FieldsChunk::setChunkLength (b chunkLength) inline virtual
 { handleChange(); this->chunkLength = chunkLength; }
Referenced by inet::sctp::SctpHeader::appendSctpChunks(), inet::tcp::TcpHeader::dropHeaderOptions(), inet::sctp::SctpHeader::insertSctpChunks(), inet::rtp::RtcpPacket::paddingAndSetLength(), inet::sctp::SctpAssociation::processPacketDropArrived(), inet::sctp::SctpHeader::removeFirstChunk(), inet::sctp::SctpNatHook::sendBackError(), and inet::sctp::SctpHeader::setSctpChunks().
setSerializedBytes()
void inet::FieldsChunk::setSerializedBytes (const std::vector< uint8_t > * bytes) const inline protected
 { CHUNK_CHECK_IMPLEMENTATION(B(bytes->size()) == chunkLength); this->serializedBytes = bytes; }
Friends And Related Function Documentation
Chunk
friend class Chunk friend
FieldsChunkSerializer
friend class FieldsChunkSerializer friend
Member Data Documentation
chunkLength
b inet::FieldsChunk::chunkLength protected
Referenced by parsimPack(), parsimUnpack(), and peekUnchecked().
serializedBytes
const std::vector<uint8_t>* inet::FieldsChunk::serializedBytes mutable protected
The serialized representation of this chunk or nullptr if not available.
When a chunk is serialized, the result is stored here for fast subsequent serializations. Moreover, if a chunk is created by deserialization, then the original bytes are also stored here. The serialized representation is deleted if a chunk is modified.
Referenced by handleChange(), parsimUnpack(), and ~FieldsChunk().
The documentation for this class was generated from the following files:
FieldsChunk.h
FieldsChunk.cc