INET Framework for OMNeT++/OMNEST: inet::TagSet Class Reference
inet::TagSet Class Reference
This class maintains a set of tags.
#include <TagSet.h>
Public Member Functions
TagSet ()
TagSet (const TagSet &other)
TagSet (TagSet &&other)
~TagSet ()
TagSet & operator= (const TagSet &other)
TagSet & operator= (TagSet &&other)
int getNumTags () const
Returns the number of tags.
cObject * getTag (int index) const
Returns the tag at the given index.
void clearTags ()
Clears the set of tags.
void copyTags (const TagSet &other)
Copies the set of tags from the other set.
template<typename T >
const T * findTag () const
Returns the tag for the provided type, or returns nullptr if no such tag is present.
template<typename T >
T * findTagForUpdate ()
Returns the tag of the provided type for update, or returns nullptr if no such tag is present.
template<typename T >
const T * getTag () const
Returns the tag for the provided type, or throws an exception if no such tag is present.
template<typename T >
T * getTagForUpdate ()
Returns the tag of the provided type for update, or throws an exception if no such tag is present.
template<typename T >
T * addTag ()
Returns a newly added tag for the provided type, or throws an exception if such a tag is already present.
template<typename T >
T * addTagIfAbsent ()
Returns a newly added tag for the provided type if absent, or returns the tag that is already present.
template<typename T >
T * removeTag ()
Removes the tag for the provided type, or throws an exception if no such tag is present.
template<typename T >
T * removeTagIfPresent ()
Removes the tag for the provided type if present, or returns nullptr if no such tag is present.
Protected Member Functions
void ensureAllocated ()
void addTag (cObject *tag)
cObject * removeTag (int index)
int getTagIndex (const std::type_info &typeInfo) const
template<typename T >
int getTagIndex () const
Protected Attributes
std::vector< cObject * > * tags
Detailed Description
This class maintains a set of tags.
Tags are usually small data strcutures that hold some relevant information. Tags are identified by their type, which means that this class supports adding the same tag type only once. Added tags are exclusively owned by this class and they get deleted with it.
Constructor & Destructor Documentation
TagSet() [1/3]
inet::TagSet::TagSet ()
                :
     tags(nullptr)
 {
 }
TagSet() [2/3]
inet::TagSet::TagSet (const TagSet & other)
                                   :
     tags(nullptr)
 {
     operator=(other);
 }
TagSet() [3/3]
inet::TagSet::TagSet (TagSet && other)
                              :
     tags(other.tags)
 {
     other.tags = nullptr;
 }
~TagSet()
inet::TagSet::~TagSet ()
 {
     clearTags();
 }
Member Function Documentation
addTag() [1/2]
template<typename T > T * inet::TagSet::addTag inline
Returns a newly added tag for the provided type, or throws an exception if such a tag is already present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index != -1)
         throw cRuntimeError("Tag '%s' is present", opp_typename(typeid(T)));
     T *tag = new T();
     addTag(tag);
     return tag;
 }
Referenced by addTagIfAbsent(), and operator=().
addTag() [2/2]
void inet::TagSet::addTag (cObject * tag) protected
 {
     ensureAllocated();
     tags->push_back(tag);
     if (tag->isOwnedObject())
         take(static_cast<cOwnedObject *>(tag));
 }
Referenced by inet::NetworkInterface::addProtocolData().
addTagIfAbsent()
template<typename T > T * inet::TagSet::addTagIfAbsent inline
Returns a newly added tag for the provided type if absent, or returns the tag that is already present.
 {
     SELFDOC_FUNCTION_T;
     T *tag = findTagForUpdate<T>();
     if (tag == nullptr)
         addTag(tag = new T());
     return tag;
 }
Referenced by inet::NetworkInterface::addProtocolDataIfAbsent().
clearTags()
void inet::TagSet::clearTags ()
Clears the set of tags.
 {
 #ifdef INET_WITH_SELFDOC
     selfDoc(__FUNCTION__, "");
     SelfDocTempOff;
 #endif // INET_WITH_SELFDOC
     if (tags != nullptr) {
         int numTags = tags->size();
         for (int index = 0; index < numTags; index++) {
             cObject *tag = (*tags)[index];
             if (tag->isOwnedObject())
                 drop(static_cast<cOwnedObject *>(tag));
             delete tag;
         }
         delete tags;
         tags = nullptr;
     }
 }
Referenced by inet::NetworkInterface::clearProtocolDataSet(), copyTags(), operator=(), inet::NetworkInterface::resetInterface(), and ~TagSet().
copyTags()
void inet::TagSet::copyTags (const TagSet & other)
Copies the set of tags from the other set.
 {
     clearTags();
     if (source.tags != nullptr) {
         int numTags = source.tags->size();
         tags = new std::vector<cObject *>(numTags);
         for (int index = 0; index < numTags; index++) {
             cObject *tag = (*source.tags)[index]->dup();
             if (tag->isOwnedObject())
                 take(static_cast<cOwnedObject *>(tag));
             (*tags)[index] = tag;
         }
     }
 }
ensureAllocated()
void inet::TagSet::ensureAllocated () protected
 {
     if (tags == nullptr) {
         tags = new std::vector<cObject *>();
         tags->reserve(16);
     }
 }
Referenced by addTag(), and operator=().
findTag()
template<typename T > const T * inet::TagSet::findTag inline
Returns the tag for the provided type, or returns nullptr if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     return index == -1 ? nullptr : static_cast<T *>((*tags)[index]);
 }
Referenced by inet::NetworkInterface::findProtocolData().
findTagForUpdate()
template<typename T > T * inet::TagSet::findTagForUpdate inline
Returns the tag of the provided type for update, or returns nullptr if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     return const_cast<T *>(findTag<T>());
 }
Referenced by inet::NetworkInterface::findProtocolDataForUpdate().
getNumTags()
int inet::TagSet::getNumTags () const inline
Returns the number of tags.
 {
     return tags == nullptr ? 0 : tags->size();
 }
Referenced by inet::NetworkInterface::clearProtocolDataSet(), inet::NetworkInterface::getNumProtocolData(), and inet::NetworkInterface::str().
getTag() [1/2]
template<typename T > const T * inet::TagSet::getTag inline
Returns the tag for the provided type, or throws an exception if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return static_cast<T *>((*tags)[index]);
 }
getTag() [2/2]
cObject * inet::TagSet::getTag (int index) const inline
Returns the tag at the given index.
The index must be in the range [0, getNumTags()).
 {
     return tags->at(index);
 }
Referenced by inet::NetworkInterface::clearProtocolDataSet(), inet::NetworkInterface::getProtocolData(), and inet::NetworkInterface::str().
getTagForUpdate()
template<typename T > T * inet::TagSet::getTagForUpdate inline
Returns the tag of the provided type for update, or throws an exception if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     return const_cast<T *>(getTag<T>());
 }
Referenced by inet::NetworkInterface::getProtocolDataForUpdate().
getTagIndex() [1/2]
template<typename T > int inet::TagSet::getTagIndex inline protected
 {
     return getTagIndex(typeid(T));
 }
getTagIndex() [2/2]
int inet::TagSet::getTagIndex (const std::type_info & typeInfo) const protected
 {
     if (tags == nullptr)
         return -1;
     else {
         int numTags = tags->size();
         for (int index = 0; index < numTags; index++) {
             cObject *tag = (*tags)[index];
             if (typeInfo == typeid(*tag))
                 return index;
         }
         return -1;
     }
 }
operator=() [1/2]
TagSet & inet::TagSet::operator= (const TagSet & other)
 {
     if (this != &other) {
         clearTags();
         if (other.tags == nullptr)
             tags = nullptr;
         else {
             ensureAllocated();
             for (auto tag : *other.tags)
                 addTag(tag->dup());
         }
     }
     return *this;
 }
Referenced by TagSet().
operator=() [2/2]
TagSet & inet::TagSet::operator= (TagSet && other)
 {
     if (this != &other) {
         clearTags();
         tags = other.tags;
         other.tags = nullptr;
     }
     return *this;
 }
removeTag() [1/2]
template<typename T > T * inet::TagSet::removeTag inline
Removes the tag for the provided type, or throws an exception if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     if (index == -1)
         throw cRuntimeError("Tag '%s' is absent", opp_typename(typeid(T)));
     return static_cast<T *>(removeTag(index));
 }
Referenced by removeTagIfPresent().
removeTag() [2/2]
cObject * inet::TagSet::removeTag (int index) protected
 {
     cObject *tag = (*tags)[index];
     if (tag->isOwnedObject())
         drop(static_cast<cOwnedObject *>(tag));
     tags->erase(tags->begin() + index);
     if (tags->size() == 0) {
         delete tags;
         tags = nullptr;
     }
     return tag;
 }
Referenced by inet::NetworkInterface::removeProtocolData().
removeTagIfPresent()
template<typename T > T * inet::TagSet::removeTagIfPresent inline
Removes the tag for the provided type if present, or returns nullptr if no such tag is present.
 {
     SELFDOC_FUNCTION_T;
     int index = getTagIndex<T>();
     return index == -1 ? nullptr : static_cast<T *>(removeTag(index));
 }
Referenced by inet::NetworkInterface::removeProtocolDataIfPresent().
Member Data Documentation
tags
std::vector<cObject *>* inet::TagSet::tags protected
Referenced by addTag(), clearTags(), copyTags(), ensureAllocated(), getNumTags(), getTag(), getTagIndex(), operator=(), and removeTag().
The documentation for this class was generated from the following files:
TagSet.h
TagSet.cc