INET Framework for OMNeT++/OMNEST: inet::ieee80211::Ieee80211MgmtBase Class Reference
inet::ieee80211::Ieee80211MgmtBase Class Reference abstract
Abstract base class for 802.11 infrastructure mode management components.
#include <Ieee80211MgmtBase.h>
Protected Member Functions
virtual int numInitStages () const override
virtual void initialize (int) override
virtual void handleMessageWhenUp (cMessage *msg) override
Dispatches incoming messages to handleTimer(), handleUpperMessage() or processFrame().
virtual void handleTimer (cMessage *frame)=0
Should be redefined to deal with self-messages.
virtual void handleCommand (int msgkind, cObject *ctrl)=0
Should be redefined to handle commands from the "agent" (if present)
virtual void sendDown (Packet *frame)
Utility method for implementing handleUpperMessage(): send message to MAC.
virtual void dropManagementFrame (Packet *frame)
Utility method to dispose of an unhandled frame.
virtual void processFrame (Packet *packet, const Ptr< const Ieee80211DataOrMgmtHeader > &header)
Dispatch to frame processing methods according to frame type.
Processing of different frame types
virtual void handleAuthenticationFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleDeauthenticationFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleAssociationRequestFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleAssociationResponseFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleReassociationRequestFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleReassociationResponseFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleDisassociationFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleBeaconFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleProbeRequestFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual void handleProbeResponseFrame (Packet *packet, const Ptr< const Ieee80211MgmtHeader > &header)=0
virtual bool isInitializeStage (int stage) const override
lifecycle support
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
virtual void handleStartOperation (LifecycleOperation *operation) override
virtual void handleStopOperation (LifecycleOperation *operation) override
virtual void handleCrashOperation (LifecycleOperation *operation) override
virtual void start ()
virtual void stop ()
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
ModuleRefByPar< Ieee80211Mib > mib
ModuleRefByPar< IInterfaceTable > interfaceTable
NetworkInterface * myIface = nullptr
long numMgmtFramesReceived
long numMgmtFramesDropped
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Additional Inherited Members
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Detailed Description
Abstract base class for 802.11 infrastructure mode management components.
Member Function Documentation
dropManagementFrame()
void inet::ieee80211::Ieee80211MgmtBase::dropManagementFrame (Packet * frame) protected virtual
Utility method to dispose of an unhandled frame.
 {
     EV << "ignoring management frame: " << (cMessage *)frame << "\n";
     delete frame;
     numMgmtFramesDropped++;
 }
Referenced by inet::ieee80211::Ieee80211MgmtAdhoc::handleAssociationRequestFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleAssociationRequestFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleAssociationRequestFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleAssociationResponseFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleAssociationResponseFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleAssociationResponseFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleAuthenticationFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleAuthenticationFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleAuthenticationFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleBeaconFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleBeaconFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleBeaconFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleDeauthenticationFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleDeauthenticationFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleDeauthenticationFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleDisassociationFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleDisassociationFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleDisassociationFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleProbeRequestFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleProbeRequestFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleProbeRequestFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleProbeResponseFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleProbeResponseFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleProbeResponseFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleReassociationRequestFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleReassociationRequestFrame(), inet::ieee80211::Ieee80211MgmtStaSimplified::handleReassociationRequestFrame(), inet::ieee80211::Ieee80211MgmtApSimplified::handleReassociationResponseFrame(), inet::ieee80211::Ieee80211MgmtAdhoc::handleReassociationResponseFrame(), and inet::ieee80211::Ieee80211MgmtStaSimplified::handleReassociationResponseFrame().
handleAssociationRequestFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleAssociationRequestFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleAssociationResponseFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleAssociationResponseFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleAuthenticationFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleAuthenticationFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleBeaconFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleBeaconFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleCommand()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleCommand (int msgkind, cObject * ctrl) protected pure virtual
Should be redefined to handle commands from the "agent" (if present)
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleCrashOperation()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleCrashOperation (LifecycleOperation * operation) inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { stop(); }
handleDeauthenticationFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleDeauthenticationFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleDisassociationFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleDisassociationFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleMessageWhenUp()
void inet::ieee80211::Ieee80211MgmtBase::handleMessageWhenUp (cMessage * msg) override protected virtual
Dispatches incoming messages to handleTimer(), handleUpperMessage() or processFrame().
Implements inet::OperationalMixin< cSimpleModule >.
 {
     if (msg->isSelfMessage()) {
         // process timers
         EV << "Timer expired: " << msg << "\n";
         handleTimer(msg);
     }
     else if (msg->arrivedOn("macIn")) {
         // process incoming frame
         EV << "Frame arrived from MAC: " << msg << "\n";
         auto packet = check_and_cast<Packet *>(msg);
         const Ptr<const Ieee80211DataOrMgmtHeader>& header = packet->peekAt<Ieee80211DataOrMgmtHeader>(packet->getFrontOffset() - B(24));
         processFrame(packet, header);
     }
     else if (msg->arrivedOn("agentIn")) {
         // process command from agent
         EV << "Command arrived from agent: " << msg << "\n";
         int msgkind = msg->getKind();
         cObject *ctrl = msg->removeControlInfo();
         delete msg;
         handleCommand(msgkind, ctrl);
     }
     else
         throw cRuntimeError("Unknown message");
 }
handleProbeRequestFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleProbeRequestFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleProbeResponseFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleProbeResponseFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleReassociationRequestFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleReassociationRequestFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleReassociationResponseFrame()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleReassociationResponseFrame (Packet * packet, const Ptr< const Ieee80211MgmtHeader > & header) protected pure virtual
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
handleStartOperation()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleStartOperation (LifecycleOperation * operation) inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { start(); }
handleStopOperation()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleStopOperation (LifecycleOperation * operation) inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { stop(); }
handleTimer()
virtual void inet::ieee80211::Ieee80211MgmtBase::handleTimer (cMessage * frame) protected pure virtual
Should be redefined to deal with self-messages.
Implemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtApSimplified.
initialize()
void inet::ieee80211::Ieee80211MgmtBase::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtApBase, inet::ieee80211::Ieee80211MgmtStaSimplified, inet::ieee80211::Ieee80211MgmtAdhoc, and inet::ieee80211::Ieee80211MgmtSta.
 {
     OperationalBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         mib.reference(this, "mibModule", true);
         interfaceTable.reference(this, "interfaceTableModule", true);
         myIface = getContainingNicModule(this);
         numMgmtFramesReceived = 0;
         numMgmtFramesDropped = 0;
         WATCH(numMgmtFramesReceived);
         WATCH(numMgmtFramesDropped);
     }
 }
Referenced by inet::ieee80211::Ieee80211MgmtAdhoc::initialize(), inet::ieee80211::Ieee80211MgmtStaSimplified::initialize(), inet::ieee80211::Ieee80211MgmtApBase::initialize(), and inet::ieee80211::Ieee80211MgmtSta::initialize().
isInitializeStage()
virtual bool inet::ieee80211::Ieee80211MgmtBase::isInitializeStage (int stage) const inline override protected virtual
lifecycle support
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == INITSTAGE_NETWORK_INTERFACE_CONFIGURATION; } // TODO INITSTAGE
isModuleStartStage()
virtual bool inet::ieee80211::Ieee80211MgmtBase::isModuleStartStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStartOperation::STAGE_PHYSICAL_LAYER; }
isModuleStopStage()
virtual bool inet::ieee80211::Ieee80211MgmtBase::isModuleStopStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStopOperation::STAGE_PHYSICAL_LAYER; }
numInitStages()
virtual int inet::ieee80211::Ieee80211MgmtBase::numInitStages () const inline override protected virtual
Reimplemented in inet::ieee80211::Ieee80211MgmtSta, inet::ieee80211::Ieee80211MgmtAp, inet::ieee80211::Ieee80211MgmtApBase, inet::ieee80211::Ieee80211MgmtApSimplified, inet::ieee80211::Ieee80211MgmtStaSimplified, and inet::ieee80211::Ieee80211MgmtAdhoc.
 { return NUM_INIT_STAGES; }
processFrame()
void inet::ieee80211::Ieee80211MgmtBase::processFrame (Packet * packet, const Ptr< const Ieee80211DataOrMgmtHeader > & header) protected virtual
Dispatch to frame processing methods according to frame type.
 {
     switch (header->getType()) {
         case ST_AUTHENTICATION:
             numMgmtFramesReceived++;
             handleAuthenticationFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_DEAUTHENTICATION:
             numMgmtFramesReceived++;
             handleDeauthenticationFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_ASSOCIATIONREQUEST:
             numMgmtFramesReceived++;
             handleAssociationRequestFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_ASSOCIATIONRESPONSE:
             numMgmtFramesReceived++;
             handleAssociationResponseFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_REASSOCIATIONREQUEST:
             numMgmtFramesReceived++;
             handleReassociationRequestFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_REASSOCIATIONRESPONSE:
             numMgmtFramesReceived++;
             handleReassociationResponseFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_DISASSOCIATION:
             numMgmtFramesReceived++;
             handleDisassociationFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_BEACON:
             numMgmtFramesReceived++;
             handleBeaconFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_PROBEREQUEST:
             numMgmtFramesReceived++;
             handleProbeRequestFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         case ST_PROBERESPONSE:
             numMgmtFramesReceived++;
             handleProbeResponseFrame(packet, dynamicPtrCast<const Ieee80211MgmtHeader>(header));
             break;
         default:
             throw cRuntimeError("Unexpected frame type (%s)%s", packet->getClassName(), packet->getName());
     }
 }
sendDown()
void inet::ieee80211::Ieee80211MgmtBase::sendDown (Packet * frame) protected virtual
Utility method for implementing handleUpperMessage(): send message to MAC.
 {
     ASSERT(isUp());
     frame->addTagIfAbsent<PacketProtocolTag>()->setProtocol(&Protocol::ieee80211Mgmt);
     send(frame, "macOut");
 }
start()
void inet::ieee80211::Ieee80211MgmtBase::start () protected virtual
Reimplemented in inet::ieee80211::Ieee80211MgmtAp.
 {
 }
Referenced by inet::ieee80211::Ieee80211MgmtAp::start().
stop()
void inet::ieee80211::Ieee80211MgmtBase::stop () protected virtual
Reimplemented in inet::ieee80211::Ieee80211MgmtAp.
 {
 }
Referenced by inet::ieee80211::Ieee80211MgmtAp::stop().
Member Data Documentation
interfaceTable
ModuleRefByPar<IInterfaceTable> inet::ieee80211::Ieee80211MgmtBase::interfaceTable protected
Referenced by inet::ieee80211::Ieee80211MgmtStaSimplified::initialize().
mib
ModuleRefByPar<Ieee80211Mib> inet::ieee80211::Ieee80211MgmtBase::mib protected
Referenced by inet::ieee80211::Ieee80211MgmtAdhoc::initialize(), inet::ieee80211::Ieee80211MgmtStaSimplified::initialize(), and inet::ieee80211::Ieee80211MgmtApBase::initialize().
myIface
NetworkInterface* inet::ieee80211::Ieee80211MgmtBase::myIface = nullptr protected
numMgmtFramesDropped
long inet::ieee80211::Ieee80211MgmtBase::numMgmtFramesDropped protected
numMgmtFramesReceived
long inet::ieee80211::Ieee80211MgmtBase::numMgmtFramesReceived protected
The documentation for this class was generated from the following files:
Ieee80211MgmtBase.h
Ieee80211MgmtBase.cc