INET Framework for OMNeT++/OMNEST: inet::ieee80211::IOriginatorMacDataService Class Reference
inet::ieee80211::IOriginatorMacDataService Class Reference abstract
#include <IOriginatorMacDataService.h>
Public Member Functions
virtual ~IOriginatorMacDataService ()
virtual std::vector< Packet * > * extractFramesToTransmit (queueing::IPacketQueue *pendingQueue)=0
Static Public Attributes
static simsignal_t packetFragmentedSignal = cComponent::registerSignal("packetFragmented")
static simsignal_t packetAggregatedSignal = cComponent::registerSignal("packetAggregated")
Constructor & Destructor Documentation
~IOriginatorMacDataService()
virtual inet::ieee80211::IOriginatorMacDataService::~IOriginatorMacDataService () inline virtual
 {}
Member Function Documentation
extractFramesToTransmit()
virtual std::vector<Packet *>* inet::ieee80211::IOriginatorMacDataService::extractFramesToTransmit (queueing::IPacketQueue * pendingQueue) pure virtual
Implemented in inet::ieee80211::OriginatorQosMacDataService, and inet::ieee80211::OriginatorMacDataService.
Referenced by inet::ieee80211::InProgressFrames::ensureHasFrameToTransmit(), and inet::ieee80211::InProgressFrames::getPendingFrameFor().
Member Data Documentation
packetAggregatedSignal
simsignal_t inet::ieee80211::IOriginatorMacDataService::packetAggregatedSignal = cComponent::registerSignal("packetAggregated") static
Referenced by inet::ieee80211::OriginatorQosMacDataService::aMpduAggregateIfNeeded(), and inet::ieee80211::OriginatorQosMacDataService::aMsduAggregateIfNeeded().
packetFragmentedSignal
simsignal_t inet::ieee80211::IOriginatorMacDataService::packetFragmentedSignal = cComponent::registerSignal("packetFragmented") static
Referenced by inet::ieee80211::OriginatorMacDataService::fragmentIfNeeded(), and inet::ieee80211::OriginatorQosMacDataService::fragmentIfNeeded().
The documentation for this class was generated from the following files:
IOriginatorMacDataService.h
IOriginatorMacDataService.cc