INET Framework for OMNeT++/OMNEST: inet::physicallayer::ReceptionBase Class Reference
inet::physicallayer::ReceptionBase Class Reference
#include <ReceptionBase.h>
Public Member Functions
ReceptionBase (const IRadio *receiver, const ITransmission *transmission, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition, const Quaternion &startOrientation, const Quaternion &endOrientation)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual const IRadio * getReceiver () const override
Returns the receiver that received the corresponding transmission from the radio medium.
virtual const ITransmission * getTransmission () const override
Returns the transmission that corresponds to this reception at the receiver.
virtual const simtime_t getStartTime () const override
Returns the time when the receiver started to receive the corresponding transmission.
virtual const simtime_t getEndTime () const override
Returns the time when the receiver ended to receive the corresponding transmission.
virtual const simtime_t getStartTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getEndTime (IRadioSignal::SignalPart part) const override
virtual const simtime_t getPreambleStartTime () const override
virtual const simtime_t getPreambleEndTime () const override
virtual const simtime_t getHeaderStartTime () const override
virtual const simtime_t getHeaderEndTime () const override
virtual const simtime_t getDataStartTime () const override
virtual const simtime_t getDataEndTime () const override
virtual const simtime_t getDuration () const override
Returns the total length of this reception.
virtual const simtime_t getDuration (IRadioSignal::SignalPart part) const override
Returns the length of the provided part of this reception.
virtual const simtime_t getPreambleDuration () const override
Returns the length of the preamble part of this reception.
virtual const simtime_t getHeaderDuration () const override
Returns the length of the header part of this reception.
virtual const simtime_t getDataDuration () const override
Returns the length of the data part of this reception.
virtual const Coord & getStartPosition () const override
Returns the antenna's position when the receiver started to receive the corresponding transmission.
virtual const Coord & getEndPosition () const override
Returns the antenna's position when the receiver ended to receive the corresponding transmission.
virtual const Quaternion & getStartOrientation () const override
Returns the antenna's orientation when the receiver started to receive the corresponding transmission.
virtual const Quaternion & getEndOrientation () const override
Returns the antenna's orientation when the receiver ended to receive the corresponding transmission.
virtual const IReceptionAnalogModel * getAnalogModel () const override
Returns the analog model of the received signal.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const IRadio * receiver
const ITransmission * transmission
const simtime_t startTime
const simtime_t endTime
const simtime_t preambleDuration
const simtime_t headerDuration
const simtime_t dataDuration
const Coord startPosition
const Coord endPosition
const Quaternion startOrientation
const Quaternion endOrientation
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
ReceptionBase()
inet::physicallayer::ReceptionBase::ReceptionBase (const IRadio * receiver, const ITransmission * transmission, const simtime_t startTime, const simtime_t endTime, const Coord & startPosition, const Coord & endPosition, const Quaternion & startOrientation, const Quaternion & endOrientation)
                                                                                                                                                                                                                                                                       :
     receiver(receiver),
     transmission(transmission),
     startTime(startTime),
     endTime(endTime),
     preambleDuration(transmission->getPreambleDuration()),
     headerDuration(transmission->getHeaderDuration()),
     dataDuration(transmission->getDataDuration()),
     startPosition(startPosition),
     endPosition(endPosition),
     startOrientation(startOrientation),
     endOrientation(endOrientation)
 {
 }
Member Function Documentation
getAnalogModel()
virtual const IReceptionAnalogModel* inet::physicallayer::ReceptionBase::getAnalogModel () const inline override virtual
Returns the analog model of the received signal.
Implements inet::physicallayer::IReception.
Reimplemented in inet::physicallayer::LayeredReception.
 { return check_and_cast<const IReceptionAnalogModel *>(this); }
getDataDuration()
virtual const simtime_t inet::physicallayer::ReceptionBase::getDataDuration () const inline override virtual
Returns the length of the data part of this reception.
Implements inet::physicallayer::IReception.
 { return dataDuration; }
Referenced by getDuration().
getDataEndTime()
virtual const simtime_t inet::physicallayer::ReceptionBase::getDataEndTime () const inline override virtual
Implements inet::physicallayer::IReception.
 { return endTime; }
Referenced by getEndTime().
getDataStartTime()
virtual const simtime_t inet::physicallayer::ReceptionBase::getDataStartTime () const inline override virtual
Implements inet::physicallayer::IReception.
 { return endTime - dataDuration; }
Referenced by getStartTime().
getDuration() [1/2]
virtual const simtime_t inet::physicallayer::ReceptionBase::getDuration () const inline override virtual
Returns the total length of this reception.
Implements inet::physicallayer::IReception.
 { return endTime - startTime; }
Referenced by getDuration().
getDuration() [2/2]
const simtime_t inet::physicallayer::ReceptionBase::getDuration (IRadioSignal::SignalPart part) const override virtual
Returns the length of the provided part of this reception.
Implements inet::physicallayer::IReception.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getDuration();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleDuration();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderDuration();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataDuration();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getEndOrientation()
virtual const Quaternion& inet::physicallayer::ReceptionBase::getEndOrientation () const inline override virtual
Returns the antenna's orientation when the receiver ended to receive the corresponding transmission.
Implements inet::physicallayer::IReception.
 { return endOrientation; }
getEndPosition()
virtual const Coord& inet::physicallayer::ReceptionBase::getEndPosition () const inline override virtual
Returns the antenna's position when the receiver ended to receive the corresponding transmission.
Implements inet::physicallayer::IReception.
 { return endPosition; }
getEndTime() [1/2]
virtual const simtime_t inet::physicallayer::ReceptionBase::getEndTime () const inline override virtual
Returns the time when the receiver ended to receive the corresponding transmission.
It is the end of the last bit's reception.
Implements inet::physicallayer::IReception.
 { return endTime; }
Referenced by getEndTime().
getEndTime() [2/2]
const simtime_t inet::physicallayer::ReceptionBase::getEndTime (IRadioSignal::SignalPart part) const override virtual
Implements inet::physicallayer::IReception.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getEndTime();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleEndTime();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderEndTime();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataEndTime();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getHeaderDuration()
virtual const simtime_t inet::physicallayer::ReceptionBase::getHeaderDuration () const inline override virtual
Returns the length of the header part of this reception.
Implements inet::physicallayer::IReception.
 { return headerDuration; }
Referenced by getDuration().
getHeaderEndTime()
virtual const simtime_t inet::physicallayer::ReceptionBase::getHeaderEndTime () const inline override virtual
Implements inet::physicallayer::IReception.
 { return endTime - dataDuration; }
Referenced by getEndTime().
getHeaderStartTime()
virtual const simtime_t inet::physicallayer::ReceptionBase::getHeaderStartTime () const inline override virtual
Implements inet::physicallayer::IReception.
 { return startTime + preambleDuration; }
Referenced by getStartTime().
getPreambleDuration()
virtual const simtime_t inet::physicallayer::ReceptionBase::getPreambleDuration () const inline override virtual
Returns the length of the preamble part of this reception.
Implements inet::physicallayer::IReception.
 { return preambleDuration; }
Referenced by getDuration().
getPreambleEndTime()
virtual const simtime_t inet::physicallayer::ReceptionBase::getPreambleEndTime () const inline override virtual
Implements inet::physicallayer::IReception.
 { return startTime + preambleDuration; }
Referenced by getEndTime().
getPreambleStartTime()
virtual const simtime_t inet::physicallayer::ReceptionBase::getPreambleStartTime () const inline override virtual
Implements inet::physicallayer::IReception.
 { return startTime; }
Referenced by getStartTime().
getReceiver()
virtual const IRadio* inet::physicallayer::ReceptionBase::getReceiver () const inline override virtual
Returns the receiver that received the corresponding transmission from the radio medium.
This function never returns nullptr.
Implements inet::physicallayer::IReception.
 { return receiver; }
getStartOrientation()
virtual const Quaternion& inet::physicallayer::ReceptionBase::getStartOrientation () const inline override virtual
Returns the antenna's orientation when the receiver started to receive the corresponding transmission.
Implements inet::physicallayer::IReception.
 { return startOrientation; }
getStartPosition()
virtual const Coord& inet::physicallayer::ReceptionBase::getStartPosition () const inline override virtual
Returns the antenna's position when the receiver started to receive the corresponding transmission.
Implements inet::physicallayer::IReception.
 { return startPosition; }
getStartTime() [1/2]
virtual const simtime_t inet::physicallayer::ReceptionBase::getStartTime () const inline override virtual
Returns the time when the receiver started to receive the corresponding transmission.
It is the start of the first bit's reception.
Implements inet::physicallayer::IReception.
 { return startTime; }
Referenced by getStartTime().
getStartTime() [2/2]
const simtime_t inet::physicallayer::ReceptionBase::getStartTime (IRadioSignal::SignalPart part) const override virtual
Implements inet::physicallayer::IReception.
 {
     switch (part) {
         case IRadioSignal::SIGNAL_PART_WHOLE:
             return getStartTime();
         case IRadioSignal::SIGNAL_PART_PREAMBLE:
             return getPreambleStartTime();
         case IRadioSignal::SIGNAL_PART_HEADER:
             return getHeaderStartTime();
         case IRadioSignal::SIGNAL_PART_DATA:
             return getDataStartTime();
         default:
             throw cRuntimeError("Unknown signal part: '%s'", IRadioSignal::getSignalPartName(part));
     }
 }
getTransmission()
virtual const ITransmission* inet::physicallayer::ReceptionBase::getTransmission () const inline override virtual
Returns the transmission that corresponds to this reception at the receiver.
This function never returns nullptr.
Implements inet::physicallayer::IReception.
 { return transmission; }
printToStream()
std::ostream & inet::physicallayer::ReceptionBase::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::UnitDiskReception, inet::physicallayer::LayeredReception, inet::physicallayer::NarrowbandReceptionBase, and inet::physicallayer::ScalarReception.
 {
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(transmissionId, transmission->getId());
     if (level <= PRINT_LEVEL_TRACE)
         stream << EV_FIELD(receiverId, receiver->getId())
                << EV_FIELD(startTime)
                << EV_FIELD(endTime)
                << EV_FIELD(preambleDuration)
                << EV_FIELD(headerDuration)
                << EV_FIELD(dataDuration)
                << EV_FIELD(startPosition)
                << EV_FIELD(endPosition)
                << EV_FIELD(startOrientation)
                << EV_FIELD(endOrientation);
     return stream;
 }
Referenced by inet::physicallayer::NarrowbandReceptionBase::printToStream(), inet::physicallayer::LayeredReception::printToStream(), and inet::physicallayer::UnitDiskReception::printToStream().
Member Data Documentation
dataDuration
const simtime_t inet::physicallayer::ReceptionBase::dataDuration protected
Referenced by printToStream().
endOrientation
const Quaternion inet::physicallayer::ReceptionBase::endOrientation protected
Referenced by printToStream().
endPosition
const Coord inet::physicallayer::ReceptionBase::endPosition protected
Referenced by printToStream().
endTime
const simtime_t inet::physicallayer::ReceptionBase::endTime protected
Referenced by inet::physicallayer::DimensionalReception::computeMinPower(), and printToStream().
headerDuration
const simtime_t inet::physicallayer::ReceptionBase::headerDuration protected
Referenced by printToStream().
preambleDuration
const simtime_t inet::physicallayer::ReceptionBase::preambleDuration protected
Referenced by printToStream().
receiver
const IRadio* inet::physicallayer::ReceptionBase::receiver protected
Referenced by printToStream().
startOrientation
const Quaternion inet::physicallayer::ReceptionBase::startOrientation protected
Referenced by printToStream().
startPosition
const Coord inet::physicallayer::ReceptionBase::startPosition protected
Referenced by printToStream().
startTime
const simtime_t inet::physicallayer::ReceptionBase::startTime protected
Referenced by inet::physicallayer::DimensionalReception::computeMinPower(), and printToStream().
transmission
const ITransmission* inet::physicallayer::ReceptionBase::transmission protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
ReceptionBase.h
ReceptionBase.cc