INET Framework for OMNeT++/OMNEST: inet::physicallayer::UnitDiskReceiver Class Reference
inet::physicallayer::UnitDiskReceiver Class Reference
Implements the UnitDiskReceiver model, see the NED file for details.
#include <UnitDiskReceiver.h>
Public Member Functions
UnitDiskReceiver ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
virtual bool computeIsReceptionPossible (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part) const override
Returns whether the reception of the provided part is possible or not.
virtual bool computeIsReceptionSuccessful (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns whether the reception of the provided part is actually successful or failed by the receiver.
virtual const IListening * createListening (const IRadio *radio, const simtime_t startTime, const simtime_t endTime, const Coord &startPosition, const Coord &endPosition) const override
Returns a description of how the receiver is listening on the medium.
virtual const IListeningDecision * computeListeningDecision (const IListening *listening, const IInterference *interference) const override
Returns the result of the listening process specifying the reception state of the receiver.
virtual const IReceptionResult * computeReceptionResult (const IListening *listening, const IReception *reception, const IInterference *interference, const ISnir *snir, const std::vector< const IReceptionDecision * > *decisions) const override
Returns the complete result of the reception process for the provided reception.
Public Member Functions inherited from inet::physicallayer::ReceiverBase
ReceiverBase ()
virtual W getMinInterferencePower () const override
Returns the minimum interference power below which receptions are to be ignored while computing the interference.
virtual W getMinReceptionPower () const override
Returns the minimum reception power below which successful reception is definitely not possible.
virtual bool computeIsReceptionPossible (const IListening *listening, const ITransmission *transmission) const override
Returns whether the reception of the provided transmission is possible or not independently of the reception conditions.
virtual bool computeIsReceptionAttempted (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference) const override
Returns whether the reception of the provided part is actually attempted or ignored by the receiver.
virtual const IReceptionDecision * computeReceptionDecision (const IListening *listening, const IReception *reception, IRadioSignal::SignalPart part, const IInterference *interference, const ISnir *snir) const override
Returns the reception decision for the transmission part that specifies whether the reception is possible, attempted, and successful.
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Member Functions
virtual void initialize (int stage) override
Protected Member Functions inherited from inet::physicallayer::ReceiverBase
virtual int numInitStages () const override
virtual W computeSignalPower (const IListening *listening, const ISnir *snir, const IInterference *interference) const
virtual Packet * computeReceivedPacket (const ISnir *snir, bool isReceptionSuccessful) const
Protected Attributes
bool ignoreInterference
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Detailed Description
Implements the UnitDiskReceiver model, see the NED file for details.
Constructor & Destructor Documentation
UnitDiskReceiver()
inet::physicallayer::UnitDiskReceiver::UnitDiskReceiver ()
                                    :
     ReceiverBase(),
     ignoreInterference(false)
 {
 }
Member Function Documentation
computeIsReceptionPossible()
bool inet::physicallayer::UnitDiskReceiver::computeIsReceptionPossible (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part) const override virtual
Returns whether the reception of the provided part is possible or not.
For example, it might check if the reception power is above sensitivity.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::ReceiverBase.
Reimplemented in inet::physicallayer::Ieee80211UnitDiskReceiver.
 {
     auto power = check_and_cast<const UnitDiskReception *>(reception)->getPower();
     return power == UnitDiskReception::POWER_RECEIVABLE;
 }
Referenced by inet::physicallayer::Ieee80211UnitDiskReceiver::computeIsReceptionPossible().
computeIsReceptionSuccessful()
bool inet::physicallayer::UnitDiskReceiver::computeIsReceptionSuccessful (const IListening * listening, const IReception * reception, IRadioSignal::SignalPart part, const IInterference * interference, const ISnir * snir) const override virtual
Returns whether the reception of the provided part is actually successful or failed by the receiver.
For example, it might compute the error rate and draw a random number to make the decision.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
 {
     auto power = check_and_cast<const UnitDiskReception *>(reception)->getPower();
     if (power == UnitDiskReception::POWER_RECEIVABLE) {
         if (ignoreInterference)
             return true;
         else {
             auto startTime = reception->getStartTime(part);
             auto endTime = reception->getEndTime(part);
             auto interferingReceptions = interference->getInterferingReceptions();
             for (auto interferingReception : *interferingReceptions) {
                 auto interferingPower = check_and_cast<const UnitDiskReception *>(interferingReception)->getPower();
                 if (interferingPower >= UnitDiskReception::POWER_INTERFERING && startTime <= interferingReception->getEndTime() && endTime >= interferingReception->getStartTime())
                     return false;
             }
             return true;
         }
     }
     else
         return false;
 }
computeListeningDecision()
const IListeningDecision * inet::physicallayer::UnitDiskReceiver::computeListeningDecision (const IListening * listening, const IInterference * interference) const override virtual
Returns the result of the listening process specifying the reception state of the receiver.
This function must be purely functional and support optimistic parallel computation.
Implements inet::physicallayer::IReceiver.
 {
     auto interferingReceptions = interference->getInterferingReceptions();
     for (auto interferingReception : *interferingReceptions) {
         auto interferingPower = check_and_cast<const UnitDiskReception *>(interferingReception)->getPower();
         if (interferingPower != UnitDiskReception::POWER_UNDETECTABLE)
             return new ListeningDecision(listening, true);
     }
     return new ListeningDecision(listening, false);
 }
computeReceptionResult()
const IReceptionResult * inet::physicallayer::UnitDiskReceiver::computeReceptionResult (const IListening * listening, const IReception * reception, const IInterference * interference, const ISnir * snir, const std::vector< const IReceptionDecision * > * decisions) const override virtual
Returns the complete result of the reception process for the provided reception.
This function may be called before the reception actually starts at the receiver, thus it must be purely functional and support optimistic parallel computation.
Reimplemented from inet::physicallayer::ReceiverBase.
Reimplemented in inet::physicallayer::Ieee80211UnitDiskReceiver.
 {
     auto noise = check_and_cast_nullable<const UnitDiskNoise *>(snir->getNoise());
     double errorRate = check_and_cast<const UnitDiskReception *>(reception)->getPower() == UnitDiskReception::POWER_RECEIVABLE && (noise == nullptr || !noise->isInterfering()) ? 0 : 1;
     auto receptionResult = ReceiverBase::computeReceptionResult(listening, reception, interference, snir, decisions);
     auto errorRateInd = const_cast<Packet *>(receptionResult->getPacket())->addTagIfAbsent<ErrorRateInd>();
     errorRateInd->setSymbolErrorRate(errorRate);
     errorRateInd->setBitErrorRate(errorRate);
     errorRateInd->setPacketErrorRate(errorRate);
     return receptionResult;
 }
Referenced by inet::physicallayer::Ieee80211UnitDiskReceiver::computeReceptionResult().
createListening()
const IListening * inet::physicallayer::UnitDiskReceiver::createListening (const IRadio * radio, const simtime_t startTime, const simtime_t endTime, const Coord & startPosition, const Coord & endPosition) const override virtual
Returns a description of how the receiver is listening on the medium.
Implements inet::physicallayer::IReceiver.
 {
     return new UnitDiskListening(radio, startTime, endTime, startPosition, endPosition);
 }
initialize()
void inet::physicallayer::UnitDiskReceiver::initialize (int stage) override protected virtual
Reimplemented in inet::physicallayer::Ieee80211UnitDiskReceiver.
 {
     ReceiverBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL)
         ignoreInterference = par("ignoreInterference");
 }
printToStream()
std::ostream & inet::physicallayer::UnitDiskReceiver::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
Reimplemented in inet::physicallayer::Ieee80211UnitDiskReceiver.
 {
     stream << "UnitDiskReceiver";
     if (level <= PRINT_LEVEL_INFO)
         stream << (ignoreInterference ? ", ignoring interference" : ", considering interference");
     return stream;
 }
Referenced by inet::physicallayer::Ieee80211UnitDiskReceiver::printToStream().
Member Data Documentation
ignoreInterference
bool inet::physicallayer::UnitDiskReceiver::ignoreInterference protected
Referenced by computeIsReceptionSuccessful(), initialize(), and printToStream().
The documentation for this class was generated from the following files:
UnitDiskReceiver.h
UnitDiskReceiver.cc