INET Framework for OMNeT++/OMNEST: inet::ieee80211::IRx Class Reference
inet::ieee80211::IRx Class Reference abstract
Abstract interface for Rx processes.
#include <IRx.h>
Public Member Functions
virtual ~IRx ()
virtual bool isReceptionInProgress () const =0
virtual bool isMediumFree () const =0
virtual void frameTransmitted (simtime_t durationField)=0
virtual void registerContention (IContention *contention)=0
virtual void receptionStateChanged (physicallayer::IRadio::ReceptionState state)=0
virtual void transmissionStateChanged (physicallayer::IRadio::TransmissionState state)=0
virtual void receivedSignalPartChanged (physicallayer::IRadioSignal::SignalPart part)=0
virtual bool lowerFrameReceived (Packet *packet)=0
Detailed Description
Abstract interface for Rx processes.
The Rx process checks received frames for errors, manages the NAV, and notifies Tx processes about the channel state (free or busy). The channel is free only if it is free according to both the physical (CCA) and the virtual (NAV-based) carrier sense algorithms. Correctly received frames are sent up to UpperMac (see IUpperMac), corrupted frames are discarded. Tx processes are also notified about corrupted and correctly received frames. so they can switch between using DIFS/AIFS and EIFS according to the channel access procedure.
Constructor & Destructor Documentation
~IRx()
virtual inet::ieee80211::IRx::~IRx () inline virtual
 {}
Member Function Documentation
frameTransmitted()
virtual void inet::ieee80211::IRx::frameTransmitted (simtime_t durationField) pure virtual
Implemented in inet::ieee80211::Rx.
Referenced by inet::ieee80211::Tx::radioTransmissionFinished().
isMediumFree()
virtual bool inet::ieee80211::IRx::isMediumFree () const pure virtual
Implemented in inet::ieee80211::Rx.
Referenced by inet::ieee80211::QosCtsPolicy::isCtsNeeded(), and inet::ieee80211::CtsPolicy::isCtsNeeded().
isReceptionInProgress()
virtual bool inet::ieee80211::IRx::isReceptionInProgress () const pure virtual
Implemented in inet::ieee80211::Rx.
lowerFrameReceived()
virtual bool inet::ieee80211::IRx::lowerFrameReceived (Packet * packet) pure virtual
Implemented in inet::ieee80211::Rx.
receivedSignalPartChanged()
virtual void inet::ieee80211::IRx::receivedSignalPartChanged (physicallayer::IRadioSignal::SignalPart part) pure virtual
Implemented in inet::ieee80211::Rx.
receptionStateChanged()
virtual void inet::ieee80211::IRx::receptionStateChanged (physicallayer::IRadio::ReceptionState state) pure virtual
Implemented in inet::ieee80211::Rx.
registerContention()
virtual void inet::ieee80211::IRx::registerContention (IContention * contention) pure virtual
Implemented in inet::ieee80211::Rx.
transmissionStateChanged()
virtual void inet::ieee80211::IRx::transmissionStateChanged (physicallayer::IRadio::TransmissionState state) pure virtual
Implemented in inet::ieee80211::Rx.
The documentation for this class was generated from the following file:
IRx.h