INET Framework for OMNeT++/OMNEST: inet::physicallayer::Ieee80211OfdmCode Class Reference
inet::physicallayer::Ieee80211OfdmCode Class Reference
#include <Ieee80211OfdmCode.h>
Public Member Functions
Ieee80211OfdmCode (const ConvolutionalCode *convolutionalCode, const Ieee80211OfdmInterleaving *interleaving, const AdditiveScrambling *scrambling)
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const override
Prints this object to the provided output stream.
const ConvolutionalCode * getConvolutionalCode () const
const Ieee80211OfdmInterleaving * getInterleaving () const
const AdditiveScrambling * getScrambling () const
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Protected Attributes
const ConvolutionalCode * convolutionalCode
const Ieee80211OfdmInterleaving * interleaving
const AdditiveScrambling * scrambling
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Constructor & Destructor Documentation
Ieee80211OfdmCode()
inet::physicallayer::Ieee80211OfdmCode::Ieee80211OfdmCode (const ConvolutionalCode * convolutionalCode, const Ieee80211OfdmInterleaving * interleaving, const AdditiveScrambling * scrambling)
                                                                                                                                                                     :
     convolutionalCode(convolutionalCode),
     interleaving(interleaving),
     scrambling(scrambling)
 {
 }
Member Function Documentation
getConvolutionalCode()
const ConvolutionalCode* inet::physicallayer::Ieee80211OfdmCode::getConvolutionalCode () const inline
 { return convolutionalCode; }
Referenced by inet::physicallayer::Ieee80211OfdmModeBase::computeNetBitrate(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::createDataFieldBitModel(), inet::physicallayer::Ieee80211LayeredOfdmTransmitter::createScalarAnalogModel(), inet::physicallayer::Ieee80211LayeredOfdmReceiver::getCodeRateFromDecoderModule(), inet::physicallayer::Ieee80211OfdmDataMode::getDuration(), inet::physicallayer::Ieee80211OfdmDataMode::getPaddingLength(), inet::physicallayer::Ieee80211OfdmDecoder::Ieee80211OfdmDecoder(), and inet::physicallayer::Ieee80211OfdmEncoder::Ieee80211OfdmEncoder().
getInterleaving()
const Ieee80211OfdmInterleaving* inet::physicallayer::Ieee80211OfdmCode::getInterleaving () const inline
 { return interleaving; }
Referenced by inet::physicallayer::Ieee80211OfdmDecoder::Ieee80211OfdmDecoder(), and inet::physicallayer::Ieee80211OfdmEncoder::Ieee80211OfdmEncoder().
getScrambling()
const AdditiveScrambling* inet::physicallayer::Ieee80211OfdmCode::getScrambling () const inline
 { return scrambling; }
Referenced by inet::physicallayer::Ieee80211OfdmDecoder::Ieee80211OfdmDecoder(), and inet::physicallayer::Ieee80211OfdmEncoder::Ieee80211OfdmEncoder().
printToStream()
std::ostream & inet::physicallayer::Ieee80211OfdmCode::printToStream (std::ostream & stream, int level, int evFlags = 0) const override virtual
Prints this object to the provided output stream.
Reimplemented from inet::IPrintableObject.
 {
     stream << "ApskCode";
     if (level <= PRINT_LEVEL_DETAIL)
         stream << EV_FIELD(convolutionalCode, printFieldToString(convolutionalCode, level + 1, evFlags))
                << EV_FIELD(interleaving, printFieldToString(interleaving, level + 1, evFlags))
                << EV_FIELD(scrambling, printFieldToString(scrambling, level + 1, evFlags));
     return stream;
 }
Member Data Documentation
convolutionalCode
const ConvolutionalCode* inet::physicallayer::Ieee80211OfdmCode::convolutionalCode protected
Referenced by printToStream().
interleaving
const Ieee80211OfdmInterleaving* inet::physicallayer::Ieee80211OfdmCode::interleaving protected
Referenced by printToStream().
scrambling
const AdditiveScrambling* inet::physicallayer::Ieee80211OfdmCode::scrambling protected
Referenced by printToStream().
The documentation for this class was generated from the following files:
Ieee80211OfdmCode.h
Ieee80211OfdmCode.cc