INET Framework for OMNeT++/OMNEST: inet::sctp::SctpReceiveStream Class Reference
inet::sctp::SctpReceiveStream Class Reference
#include <SctpReceiveStream.h>
Public Member Functions
uint32_t enqueueNewDataChunk (SctpDataVariables *dchunk)
SctpReceiveStream (SctpAssociation *assoc)
Ctor.
int32_t getExpectedStreamSeqNum ()
void setExpectedStreamSeqNum (int32_t num)
~SctpReceiveStream ()
Virtual dtor.
SctpQueue * getDeliveryQ () const
SctpQueue * getOrderedQ () const
SctpQueue * getUnorderedQ () const
int32_t getStreamId () const
void setStreamId (const uint16_t id)
Protected Member Functions
uint32_t reassemble (SctpQueue *queue, uint32_t tsn)
Protected Attributes
SctpAssociation * assoc
uint16_t streamId
int32_t expectedStreamSeqNum
SctpQueue * deliveryQ
SctpQueue * orderedQ
SctpQueue * unorderedQ
Constructor & Destructor Documentation
SctpReceiveStream()
inet::sctp::SctpReceiveStream::SctpReceiveStream (SctpAssociation * assoc)
Ctor.
 {
     streamId = 0;
     expectedStreamSeqNum = 0;
     deliveryQ = new SctpQueue();
     orderedQ = new SctpQueue();
     unorderedQ = new SctpQueue();
     assoc = assoc_;
 }
~SctpReceiveStream()
inet::sctp::SctpReceiveStream::~SctpReceiveStream ()
Virtual dtor.
 {
     delete deliveryQ;
     delete orderedQ;
     delete unorderedQ;
 }
Member Function Documentation
enqueueNewDataChunk()
uint32_t inet::sctp::SctpReceiveStream::enqueueNewDataChunk (SctpDataVariables * dchunk)
 {
     uint32_t delivery = 0; // 0:orderedQ=false && deliveryQ=false; 1:orderedQ=true && deliveryQ=false; 2:oderedQ=true && deliveryQ=true; 3:fragment
     SctpDataVariables *chunk;
     /* Enqueueing NEW data chunk. Append it to the respective queue */
     // ====== Unordered delivery =============================================
     if (!dchunk->ordered) {
         if (dchunk->bbit && dchunk->ebit) {
             /* put message into deliveryQ */
             if (deliveryQ->checkAndInsertChunk(dchunk->tsn, dchunk)) {
                 delivery = 2;
             }
         }
         else {
             if (unorderedQ->checkAndInsertChunk(dchunk->tsn, dchunk)) {
                 delivery = 3;
             }
             /* try to reassemble here */
             uint32_t reassembled = reassemble(unorderedQ, dchunk->tsn);
             if ((unorderedQ->getChunk(reassembled))->bbit && (unorderedQ->getChunk(reassembled))->bbit) { // FIXME There are identical sub-expressions '(unorderedQ->getChunk(reassembled))->bbit' to the left and to the right of the '&&' operator.
                 /* put message into deliveryQ */
                 if (deliveryQ->checkAndInsertChunk(reassembled, unorderedQ->getAndExtractChunk(reassembled))) {
                     delivery = 2;
                 }
             }
         }
     }
     // ====== Ordered delivery ===============================================
     else if (dchunk->ordered) {
         /* put message into orderedQ */
         if (orderedQ->checkAndInsertChunk(dchunk->tsn, dchunk))
             delivery = 1;
         if (!dchunk->bbit || !dchunk->ebit) {
             delivery = 3;
             /* try to reassemble */
             reassemble(orderedQ, dchunk->tsn);
         }
         if (orderedQ->getQueueSize() > 0) {
             /* dequeue first from orderedQ */
             chunk = orderedQ->dequeueChunkBySSN(expectedStreamSeqNum);
             if (chunk) {
                 if (deliveryQ->checkAndInsertChunk(chunk->tsn, chunk)) {
                     ++expectedStreamSeqNum;
                     if (expectedStreamSeqNum > 65535)
                         expectedStreamSeqNum = 0;
                     delivery = 2;
                 }
             }
         }
     }
     return delivery;
 }
getDeliveryQ()
SctpQueue* inet::sctp::SctpReceiveStream::getDeliveryQ () const inline
 { return deliveryQ; };
Referenced by inet::sctp::SctpAssociation::calculateRcvBuffer(), inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::pushUlp(), and inet::sctp::SctpAssociation::putInDeliveryQ().
getExpectedStreamSeqNum()
int32_t inet::sctp::SctpReceiveStream::getExpectedStreamSeqNum ()
{
     return expectedStreamSeqNum;
 }
Referenced by inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::processForwardTsnArrived(), and inet::sctp::SctpAssociation::putInDeliveryQ().
getOrderedQ()
SctpQueue* inet::sctp::SctpReceiveStream::getOrderedQ () const inline
 { return orderedQ; };
Referenced by inet::sctp::SctpAssociation::calculateRcvBuffer(), inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::processForwardTsnArrived(), and inet::sctp::SctpAssociation::putInDeliveryQ().
getStreamId()
int32_t inet::sctp::SctpReceiveStream::getStreamId () const inline
 { return streamId; };
Referenced by inet::sctp::SctpAssociation::makeRoomForTsn().
getUnorderedQ()
SctpQueue* inet::sctp::SctpReceiveStream::getUnorderedQ () const inline
 { return unorderedQ; };
Referenced by inet::sctp::SctpAssociation::calculateRcvBuffer(), and inet::sctp::SctpAssociation::makeRoomForTsn().
reassemble()
uint32_t inet::sctp::SctpReceiveStream::reassemble (SctpQueue * queue, uint32_t tsn) protected
 {
     uint32_t begintsn = tsn, endtsn = 0;
     EV_INFO << "Trying to reassemble message..." << endl;
     /* test if we have all fragments down to the first */
     while (queue->getChunk(begintsn) && !(queue->getChunk(begintsn))->bbit)
         begintsn--;
     if (queue->getChunk(begintsn)) {
         endtsn = begintsn;
         /* test if we have all fragments up to the end */
         while (queue->getChunk(endtsn) && !(queue->getChunk(endtsn))->ebit)
             endtsn++;
         if (queue->getChunk(endtsn)) {
             EV_INFO << "All fragments found, now reassembling..." << endl;
             SctpDataVariables *firstVar = queue->getChunk(begintsn), *processVar;
             SctpSimpleMessage *firstSimple = check_and_cast<SctpSimpleMessage *>(firstVar->userData);
             EV_INFO << "First fragment has " << firstVar->len / 8 << " bytes." << endl;
             while (++begintsn <= endtsn) {
                 processVar = queue->getAndExtractChunk(begintsn);
                 SctpSimpleMessage *processSimple = check_and_cast<SctpSimpleMessage *>(processVar->userData);
                 EV_INFO << "Adding fragment with " << processVar->len / 8 << " bytes." << endl;
                 if ((firstSimple->getDataArraySize() > 0) && (processSimple->getDataArraySize() > 0)) {
                     firstSimple->setDataArraySize(firstSimple->getDataArraySize() + processSimple->getDataArraySize());
                     firstSimple->setDataLen(firstSimple->getDataLen() + processSimple->getDataLen());
                     firstSimple->setByteLength(firstSimple->getByteLength() + processSimple->getByteLength());
                     /* copy data */
                     for (uint32_t i = 0; i < (processVar->len / 8); i++)
                         firstSimple->setData(i + (firstVar->len / 8), processSimple->getData(i));
                 }
                 firstVar->len += processVar->len;
                 delete processVar->userData;
                 delete processVar;
             }
             firstVar->ebit = 1;
             EV_INFO << "Reassembly done. Length=" << firstVar->len << "\n";
             return firstVar->tsn;
         }
     }
     return tsn;
 }
Referenced by enqueueNewDataChunk().
setExpectedStreamSeqNum()
void inet::sctp::SctpReceiveStream::setExpectedStreamSeqNum (int32_t num)
{
     expectedStreamSeqNum = seqNum;
 }
Referenced by inet::sctp::SctpAssociation::makeRoomForTsn(), inet::sctp::SctpAssociation::processForwardTsnArrived(), and inet::sctp::SctpAssociation::putInDeliveryQ().
setStreamId()
void inet::sctp::SctpReceiveStream::setStreamId (const uint16_t id) inline
 { streamId = id; }
Referenced by inet::sctp::SctpAssociation::initStreams().
Member Data Documentation
assoc
SctpAssociation* inet::sctp::SctpReceiveStream::assoc protected
Referenced by SctpReceiveStream().
deliveryQ
SctpQueue* inet::sctp::SctpReceiveStream::deliveryQ protected
Referenced by enqueueNewDataChunk(), SctpReceiveStream(), and ~SctpReceiveStream().
expectedStreamSeqNum
int32_t inet::sctp::SctpReceiveStream::expectedStreamSeqNum protected
Referenced by enqueueNewDataChunk(), getExpectedStreamSeqNum(), SctpReceiveStream(), and setExpectedStreamSeqNum().
orderedQ
SctpQueue* inet::sctp::SctpReceiveStream::orderedQ protected
Referenced by enqueueNewDataChunk(), SctpReceiveStream(), and ~SctpReceiveStream().
streamId
uint16_t inet::sctp::SctpReceiveStream::streamId protected
Referenced by SctpReceiveStream().
unorderedQ
SctpQueue* inet::sctp::SctpReceiveStream::unorderedQ protected
Referenced by enqueueNewDataChunk(), SctpReceiveStream(), and ~SctpReceiveStream().
The documentation for this class was generated from the following files:
SctpReceiveStream.h
SctpReceiveStream.cc