INET Framework for OMNeT++/OMNEST: inet::physicallayer::PhysicalLayerBase Class Reference
inet::physicallayer::PhysicalLayerBase Class Reference
#include <PhysicalLayerBase.h>
Protected Member Functions
virtual void initialize (int stage) override
virtual void handleSignal (WirelessSignal *signal)
virtual void handleLowerMessage (cMessage *message) override
virtual void sendUp (cMessage *message)
virtual bool isUpperMessage (cMessage *message) const override
virtual bool isLowerMessage (cMessage *message) const override
virtual bool isInitializeStage (int stage) const override
virtual bool isModuleStartStage (int stage) const override
virtual bool isModuleStopStage (int stage) const override
Protected Member Functions inherited from inet::LayeredProtocolBase
virtual void handleMessageWhenUp (cMessage *message) override
virtual void handleSelfMessage (cMessage *message)
virtual void handleUpperMessage (cMessage *message)
virtual void handleUpperCommand (cMessage *message)
virtual void handleLowerCommand (cMessage *message)
virtual void handleUpperPacket (Packet *packet)
virtual void handleLowerPacket (Packet *packet)
Protected Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual int numInitStages () const override
virtual void refreshDisplay () const override
virtual void handleMessage (cMessage *msg) override
virtual void handleMessageWhenDown (cMessage *msg)
virtual bool handleOperationStage (LifecycleOperation *operation, IDoneCallback *doneCallback) override
Perform one stage of a lifecycle operation.
virtual void handleStartOperation (LifecycleOperation *operation)=0
virtual void handleStopOperation (LifecycleOperation *operation)=0
virtual void handleCrashOperation (LifecycleOperation *operation)=0
virtual State getInitialOperationalState () const
Returns initial operational state: OPERATING or NOT_OPERATING.
virtual void handleActiveOperationTimeout (cMessage *message)
virtual bool isUp () const
utility functions
virtual bool isDown () const
virtual void setOperationalState (State newState)
virtual void scheduleOperationTimeout (simtime_t timeout)
virtual void setupActiveOperation (LifecycleOperation *operation, IDoneCallback *doneCallback, State)
virtual void delayActiveOperationFinish (simtime_t timeout)
virtual void startActiveOperationExtraTime (simtime_t delay=SIMTIME_ZERO)
virtual void startActiveOperationExtraTimeOrFinish (simtime_t extraTime)
virtual void finishActiveOperation ()
Protected Attributes
int upperLayerInGateId = -1
int upperLayerOutGateId = -1
int radioInGateId = -1
Protected Attributes inherited from inet::OperationalMixin< cSimpleModule >
State operationalState
simtime_t lastChange
Operation activeOperation
cMessage * activeOperationTimeout
cMessage * activeOperationExtraTimer
Additional Inherited Members
Public Member Functions inherited from inet::OperationalMixin< cSimpleModule >
virtual ~OperationalMixin ()
}@
Public Member Functions inherited from inet::ILifecycle
virtual ~ILifecycle ()
Public Member Functions inherited from inet::IPhysicalLayer
virtual ~IPhysicalLayer ()
Protected Types inherited from inet::OperationalMixin< cSimpleModule >
enum State
Member Function Documentation
handleLowerMessage()
void inet::physicallayer::PhysicalLayerBase::handleLowerMessage (cMessage * message) override protected virtual
Reimplemented from inet::LayeredProtocolBase.
 {
     if (!message->isPacket())
         handleLowerCommand(message);
     else {
         emit(packetReceivedFromLowerSignal, message);
         handleSignal(check_and_cast<WirelessSignal *>(message));
     }
 }
handleSignal()
void inet::physicallayer::PhysicalLayerBase::handleSignal (WirelessSignal * signal) protected virtual
Reimplemented in inet::physicallayer::Radio.
 {
     throw cRuntimeError("Signal '%s' is not handled.", signal->getName());
 }
Referenced by handleLowerMessage().
initialize()
void inet::physicallayer::PhysicalLayerBase::initialize (int stage) override protected virtual
Reimplemented from inet::OperationalMixin< cSimpleModule >.
Reimplemented in inet::physicallayer::Radio, inet::physicallayer::Ieee80211Radio, inet::physicallayer::ShortcutRadio, and inet::physicallayer::ApskRadio.
 {
     LayeredProtocolBase::initialize(stage);
     if (stage == INITSTAGE_LOCAL) {
         upperLayerInGateId = findGate("upperLayerIn");
         upperLayerOutGateId = findGate("upperLayerOut");
         radioInGateId = findGate("radioIn");
     }
 }
Referenced by inet::physicallayer::ShortcutRadio::initialize(), and inet::physicallayer::Radio::initialize().
isInitializeStage()
virtual bool inet::physicallayer::PhysicalLayerBase::isInitializeStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == INITSTAGE_PHYSICAL_LAYER; }
isLowerMessage()
bool inet::physicallayer::PhysicalLayerBase::isLowerMessage (cMessage * message) const override protected virtual
Implements inet::LayeredProtocolBase.
 {
     return message->getArrivalGateId() == radioInGateId;
 }
isModuleStartStage()
virtual bool inet::physicallayer::PhysicalLayerBase::isModuleStartStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStartOperation::STAGE_PHYSICAL_LAYER; }
isModuleStopStage()
virtual bool inet::physicallayer::PhysicalLayerBase::isModuleStopStage (int stage) const inline override protected virtual
Implements inet::OperationalMixin< cSimpleModule >.
 { return stage == ModuleStopOperation::STAGE_PHYSICAL_LAYER; }
isUpperMessage()
bool inet::physicallayer::PhysicalLayerBase::isUpperMessage (cMessage * message) const override protected virtual
Implements inet::LayeredProtocolBase.
 {
     return message->getArrivalGateId() == upperLayerInGateId;
 }
sendUp()
void inet::physicallayer::PhysicalLayerBase::sendUp (cMessage * message) protected virtual
 {
     if (message->isPacket())
         emit(packetSentToUpperSignal, message);
     send(message, upperLayerOutGateId);
 }
Member Data Documentation
radioInGateId
int inet::physicallayer::PhysicalLayerBase::radioInGateId = -1 protected
Referenced by initialize(), and isLowerMessage().
upperLayerInGateId
int inet::physicallayer::PhysicalLayerBase::upperLayerInGateId = -1 protected
Referenced by initialize(), and isUpperMessage().
upperLayerOutGateId
int inet::physicallayer::PhysicalLayerBase::upperLayerOutGateId = -1 protected
Referenced by initialize(), and sendUp().
The documentation for this class was generated from the following files:
PhysicalLayerBase.h
PhysicalLayerBase.cc