INET Framework for OMNeT++/OMNEST: inet::physicallayer::IIeee80211PreambleMode Class Reference
inet::physicallayer::IIeee80211PreambleMode Class Reference abstract
#include <IIeee80211Mode.h>
Public Member Functions
virtual const simtime_t getDuration () const =0
virtual Ptr< Ieee80211PhyPreamble > createPreamble () const =0
Public Member Functions inherited from inet::IPrintableObject
virtual ~IPrintableObject ()
virtual std::ostream & printToStream (std::ostream &stream, int level, int evFlags=0) const
Prints this object to the provided output stream.
virtual std::string printToString () const
virtual std::string printToString (int level, int evFlags=0) const
virtual std::string getInfoStringRepresentation (int evFlags=0) const
virtual std::string getDetailStringRepresentation (int evFlags=0) const
virtual std::string getDebugStringRepresentation (int evFlags=0) const
virtual std::string getTraceStringRepresentation (int evFlags=0) const
virtual std::string getCompleteStringRepresentation (int evFlags=0) const
Additional Inherited Members
Public Types inherited from inet::IPrintableObject
enum PrintLevel {
PRINT_LEVEL_TRACE, PRINT_LEVEL_DEBUG, PRINT_LEVEL_DETAIL, PRINT_LEVEL_INFO,
PRINT_LEVEL_COMPLETE = INT_MIN
}
enum PrintFlag { PRINT_FLAG_FORMATTED = (1 << 0), PRINT_FLAG_MULTILINE = (1 << 1) }
Member Function Documentation
createPreamble()
virtual Ptr<Ieee80211PhyPreamble> inet::physicallayer::IIeee80211PreambleMode::createPreamble () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtPreambleMode, inet::physicallayer::Ieee80211VhtPreambleMode, inet::physicallayer::Ieee80211OfdmPreambleMode, inet::physicallayer::Ieee80211HrDsssPreambleMode, inet::physicallayer::Ieee80211DsssPreambleMode, inet::physicallayer::Ieee80211IrPreambleMode, and inet::physicallayer::Ieee80211FhssPreambleMode.
getDuration()
virtual const simtime_t inet::physicallayer::IIeee80211PreambleMode::getDuration () const pure virtual
Implemented in inet::physicallayer::Ieee80211HtPreambleMode, inet::physicallayer::Ieee80211VhtPreambleMode, inet::physicallayer::Ieee80211OfdmPreambleMode, inet::physicallayer::Ieee80211HrDsssPreambleMode, inet::physicallayer::Ieee80211DsssPreambleMode, inet::physicallayer::Ieee80211IrPreambleMode, and inet::physicallayer::Ieee80211FhssPreambleMode.
Referenced by inet::physicallayer::Ieee80211ScalarTransmitter::createTransmission(), inet::physicallayer::Ieee80211DimensionalTransmitter::createTransmission(), and inet::physicallayer::Ieee80211UnitDiskTransmitter::createTransmission().
The documentation for this class was generated from the following file:
IIeee80211Mode.h