INET Framework for OMNeT++/OMNEST: inet::ReassemblyBuffer Class Reference
inet::ReassemblyBuffer Class Reference
This class provides functionality for reassembling out of order data chunks for protocols supporting fragmentation.
#include <ReassemblyBuffer.h>
Public Member Functions
ReassemblyBuffer (b expectedLength=b(-1))
ReassemblyBuffer (const ReassemblyBuffer &other)
b getExpectedLength () const
Returns the expected data length.
void setExpectedLength (b expectedLength)
Changes the expected data length.
bool isComplete () const
Returns true if all data is present for reassembling the data chunk.
const Ptr< const Chunk > getReassembledData () const
Returns the reassembled data chunk if all data is present in the buffer, otherwise throws an exception.
Public Member Functions inherited from inet::ChunkBuffer
ChunkBuffer (const char *name=nullptr)
ChunkBuffer (const ChunkBuffer &other)
virtual ChunkBuffer * dup () const override
bool isEmpty () const
Returns true if the buffer is completely empty.
int getNumRegions () const
Returns the number non-overlapping, non-connecting but continuous regions.
b getRegionLength (int index) const
Returns the length of the given region.
b getRegionStartOffset (int index) const
Returns the start offset of the given region.
b getRegionEndOffset (int index) const
Returns the end offset of the given region.
const Ptr< const Chunk > & getRegionData (int index) const
Returns the data of the given region in its current representation.
void replace (b offset, const Ptr< const Chunk > &chunk)
Replaces the stored data at the provided offset with the data in the chunk.
void clear (b offset, b length)
Erases the stored data at the provided offset and length.
void clear ()
Erases all of the stored data.
virtual std::string str () const override
Returns a human readable string representation.
Protected Attributes
b expectedLength
The total length of the reassembled data chunk.
Protected Attributes inherited from inet::ChunkBuffer
std::vector< Region > regions
The list of non-overlapping, non-connecting but continuous regions.
Additional Inherited Members
Protected Member Functions inherited from inet::ChunkBuffer
Region * getRegion (int i) const
void eraseEmptyRegions (std::vector< Region >::iterator begin, std::vector< Region >::iterator end)
void sliceRegions (Region &newRegion)
void mergeRegions (Region &previousRegion, Region &nextRegion)
Detailed Description
This class provides functionality for reassembling out of order data chunks for protocols supporting fragmentation.
The reassembling algorithm requires the expected length of the non-fragmented data chunk. It assumes that the non-fragmented data chunk starts at 0 offset. If all data becomes available up to the expected length, then the defragmentation is considered complete.
Constructor & Destructor Documentation
ReassemblyBuffer() [1/2]
inet::ReassemblyBuffer::ReassemblyBuffer (b expectedLength = b(-1)) inline
 : expectedLength(expectedLength) {}
ReassemblyBuffer() [2/2]
inet::ReassemblyBuffer::ReassemblyBuffer (const ReassemblyBuffer & other) inline
 : ChunkBuffer(other), expectedLength(other.expectedLength) {}
Member Function Documentation
getExpectedLength()
b inet::ReassemblyBuffer::getExpectedLength () const inline
Returns the expected data length.
 { return expectedLength; }
getReassembledData()
const Ptr<const Chunk> inet::ReassemblyBuffer::getReassembledData () const inline
Returns the reassembled data chunk if all data is present in the buffer, otherwise throws an exception.
{
         if (!isComplete())
             throw cRuntimeError("Reassembly is incomplete");
         else
             return regions[0].data;
     }
Referenced by inet::Ipv4FragBuf::addFragment(), and inet::Ipv6FragBuf::addFragment().
isComplete()
bool inet::ReassemblyBuffer::isComplete () const inline
Returns true if all data is present for reassembling the data chunk.
{
         return regions.size() == 1 && regions[0].offset == b(0) && regions[0].data->getChunkLength() == expectedLength;
     }
Referenced by inet::Ipv4FragBuf::addFragment(), and inet::Ipv6FragBuf::addFragment().
setExpectedLength()
void inet::ReassemblyBuffer::setExpectedLength (b expectedLength) inline
Changes the expected data length.
 { this->expectedLength = expectedLength; }
Referenced by inet::Ipv4FragBuf::addFragment(), and inet::Ipv6FragBuf::addFragment().
Member Data Documentation
expectedLength
b inet::ReassemblyBuffer::expectedLength protected
The total length of the reassembled data chunk.
The documentation for this class was generated from the following file:
ReassemblyBuffer.h