INET Framework for OMNeT++/OMNEST: inet::ReorderBuffer Class Reference
inet::ReorderBuffer Class Reference
This class provides functionality for reordering out of order data chunks for reliable connection oriented protocols.
#include <ReorderBuffer.h>
Public Member Functions
ReorderBuffer (b expectedOffset=b(-1))
ReorderBuffer (const ReorderBuffer &other)
b getExpectedOffset () const
Returns the offset of the next expected data chunk.
void setExpectedOffset (b expectedOffset)
Changes the offset of the next expected data chunk.
b getAvailableDataLength () const
Returns the length of the largest next available data chunk starting at the expected offset.
const Ptr< const Chunk > popAvailableData (b length=b(-1))
Returns the largest next available data chunk starting at the expected offset.
Public Member Functions inherited from inet::ChunkBuffer
ChunkBuffer (const char *name=nullptr)
ChunkBuffer (const ChunkBuffer &other)
virtual ChunkBuffer * dup () const override
bool isEmpty () const
Returns true if the buffer is completely empty.
int getNumRegions () const
Returns the number non-overlapping, non-connecting but continuous regions.
b getRegionLength (int index) const
Returns the length of the given region.
b getRegionStartOffset (int index) const
Returns the start offset of the given region.
b getRegionEndOffset (int index) const
Returns the end offset of the given region.
const Ptr< const Chunk > & getRegionData (int index) const
Returns the data of the given region in its current representation.
void replace (b offset, const Ptr< const Chunk > &chunk)
Replaces the stored data at the provided offset with the data in the chunk.
void clear (b offset, b length)
Erases the stored data at the provided offset and length.
void clear ()
Erases all of the stored data.
virtual std::string str () const override
Returns a human readable string representation.
Protected Attributes
b expectedOffset
The offset of the next expected data chunk.
Protected Attributes inherited from inet::ChunkBuffer
std::vector< Region > regions
The list of non-overlapping, non-connecting but continuous regions.
Additional Inherited Members
Protected Member Functions inherited from inet::ChunkBuffer
Region * getRegion (int i) const
void eraseEmptyRegions (std::vector< Region >::iterator begin, std::vector< Region >::iterator end)
void sliceRegions (Region &newRegion)
void mergeRegions (Region &previousRegion, Region &nextRegion)
Detailed Description
This class provides functionality for reordering out of order data chunks for reliable connection oriented protocols.
The reordering algorithm takes the expected offset of the next data chunk. It provides reordered data as a continuous data chunk at the expected offset as soon as it becomes available.
Constructor & Destructor Documentation
ReorderBuffer() [1/2]
inet::ReorderBuffer::ReorderBuffer (b expectedOffset = b(-1)) inline
 : expectedOffset(expectedOffset) {}
ReorderBuffer() [2/2]
inet::ReorderBuffer::ReorderBuffer (const ReorderBuffer & other) inline
 : ChunkBuffer(other), expectedOffset(other.expectedOffset) {}
Member Function Documentation
getAvailableDataLength()
b inet::ReorderBuffer::getAvailableDataLength () const
Returns the length of the largest next available data chunk starting at the expected offset.
 {
     if (regions.size() > 0 && regions[0].offset == expectedOffset)
         return regions[0].data->getChunkLength();
     else
         return b(0);
 }
getExpectedOffset()
b inet::ReorderBuffer::getExpectedOffset () const inline
Returns the offset of the next expected data chunk.
 { return expectedOffset; }
Referenced by inet::tcp::TcpReceiveQueue::extractBytesUpTo(), inet::tcp::TcpReceiveQueue::insertBytesFromSegment(), and inet::tcp::TcpReceiveQueue::seqToOffset().
popAvailableData()
const Ptr< const Chunk > inet::ReorderBuffer::popAvailableData (b length = b(-1))
Returns the largest next available data chunk starting at the expected offset.
The returned data chunk is automatically removed from the buffer. If there's no available data at the expected offset, then it returns a nullptr and the buffer is not modified.
 {
     if (regions.size() > 0 && regions[0].offset == expectedOffset) {
         auto data = regions[0].data;
         b dataLength = data->getChunkLength();
         if (length != b(-1)) {
             data = data->peek(Chunk::ForwardIterator(b(0)), length);
             dataLength = length;
         }
         clear(expectedOffset, dataLength);
         expectedOffset += dataLength;
         return data;
     }
     else
         return nullptr;
 }
Referenced by inet::tcp::TcpReceiveQueue::extractBytesUpTo().
setExpectedOffset()
void inet::ReorderBuffer::setExpectedOffset (b expectedOffset) inline
Changes the offset of the next expected data chunk.
 { this->expectedOffset = expectedOffset; }
Referenced by inet::tcp::TcpReceiveQueue::init().
Member Data Documentation
expectedOffset
b inet::ReorderBuffer::expectedOffset protected
The offset of the next expected data chunk.
Referenced by getAvailableDataLength(), and popAvailableData().
The documentation for this class was generated from the following files:
ReorderBuffer.h
ReorderBuffer.cc