INET Framework for OMNeT++/OMNEST: inet::bgp::BgpRoutingTableEntry Class Reference
inet::bgp::BgpRoutingTableEntry Class Reference
#include <BgpRoutingTableEntry.h>
Public Member Functions
BgpRoutingTableEntry (void)
BgpRoutingTableEntry (const Ipv4Route *entry)
virtual ~BgpRoutingTableEntry (void)
void setPathType (RoutingPathType type)
RoutingPathType getPathType (void) const
void addAS (AsId newAS)
unsigned int getASCount (void) const
AsId getAS (unsigned int index) const
int getLocalPreference (void) const
void setLocalPreference (int l)
bool isIBgpLearned (void)
void setIBgpLearned (bool i)
virtual std::string str () const
Public Member Functions inherited from inet::Ipv4Route
Ipv4Route ()
virtual ~Ipv4Route ()
virtual std::string detailedInfo () const
bool operator== (const Ipv4Route &route) const
bool operator!= (const Ipv4Route &route) const
bool equals (const Ipv4Route &route) const
virtual void setRoutingTable (IIpv4RoutingTable *rt)
To be called by the routing table when this route is added or removed from it.
IIpv4RoutingTable * getRoutingTable () const
virtual bool isValid () const
test validity of route entry, e.g.
virtual void setDestination (Ipv4Address _dest)
virtual void setNetmask (Ipv4Address _netmask)
virtual void setGateway (Ipv4Address _gateway)
virtual void setInterface (NetworkInterface *_interfacePtr) override
virtual void setSourceType (SourceType _source) override
const char * getSourceTypeAbbreviation () const
virtual void setAdminDist (unsigned int _adminDist) override
virtual void setMetric (int _metric) override
const Ipv4Address & getDestination () const
Destination address prefix to match.
const Ipv4Address & getNetmask () const
Represents length of prefix to match.
const Ipv4Address & getGateway () const
Next hop address.
NetworkInterface * getInterface () const override
Next hop interface.
const char * getInterfaceName () const
Convenience method.
SourceType getSourceType () const override
Source of route.
unsigned int getAdminDist () const
Route source specific preference value.
int getMetric () const override
"Cost" to reach the destination
void setSource (cObject *_source) override
cObject * getSource () const override
Source of route.
cObject * getProtocolData () const override
void setProtocolData (cObject *protocolData) override
virtual IRoutingTable * getRoutingTableAsGeneric () const override
The routing table in which this route is inserted, or nullptr.
virtual void setDestination (const L3Address &dest) override
virtual void setPrefixLength (int len) override
virtual void setNextHop (const L3Address &nextHop) override
virtual L3Address getDestinationAsGeneric () const override
Destination address prefix to match.
virtual int getPrefixLength () const override
Represents length of prefix to match.
virtual L3Address getNextHopAsGeneric () const override
Next hop address.
Public Member Functions inherited from inet::IRoute
virtual ~IRoute ()
virtual void setSourceType (SourceType type)=0
Static Public Member Functions
static const std::string getPathTypeString (RoutingPathType type)
Static Public Member Functions inherited from inet::IRoute
static const char * sourceTypeName (SourceType sourceType)
Private Types
typedef unsigned char RoutingPathType
Private Attributes
RoutingPathType _pathType = INCOMPLETE
std::vector< AsId > _ASList
int localPreference = 0
bool IBGP_learned = false
Additional Inherited Members
Public Types inherited from inet::IRoute
enum SourceType {
MANUAL, IFACENETMASK, ROUTER_ADVERTISEMENT, OWN_ADV_PREFIX,
ICMP_REDIRECT, RIP, OSPF, BGP,
ZEBRA, MANET, MANET2, DYMO,
AODV, EIGRP, LISP, BABEL,
ODR, UNKNOWN, ISIS
}
Specifies where the route comes from.
enum ChangeCodes {
F_DESTINATION, F_PREFIX_LENGTH, F_NEXTHOP, F_IFACE,
F_SOURCE, F_TYPE, F_ADMINDIST, F_METRIC,
F_EXPIRYTIME, F_LAST
}
Field codes for NB_ROUTE_CHANGED notifications.
enum RouteAdminDist {
dDirectlyConnected = 0, dStatic = 1, dEIGRPSummary = 5, dBGPExternal = 20,
dEIGRPInternal = 90, dIGRP = 100, dOSPF = 110, dISIS = 115,
dRIP = 120, dEGP = 140, dODR = 160, dEIGRPExternal = 170,
dBGPInternal = 200, dDHCPlearned = 254, dBABEL = 125, dLISP = 210,
dUnknown = 255
}
Cisco like administrative distances.
Protected Member Functions inherited from inet::Ipv4Route
void changed (int fieldCode)
Member Typedef Documentation
RoutingPathType
typedef unsigned char inet::bgp::BgpRoutingTableEntry::RoutingPathType private
Constructor & Destructor Documentation
BgpRoutingTableEntry() [1/2]
inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry (void) inline
 {
     setNetmask(Ipv4Address::ALLONES_ADDRESS);
     setMetric(DEFAULT_COST);
     setSourceType(IRoute::BGP);
 }
BgpRoutingTableEntry() [2/2]
inet::bgp::BgpRoutingTableEntry::BgpRoutingTableEntry (const Ipv4Route * entry) inline
 {
     setDestination(entry->getDestination());
     setNetmask(entry->getNetmask());
     setGateway(entry->getGateway());
     setInterface(entry->getInterface());
     setMetric(DEFAULT_COST);
     setSourceType(IRoute::BGP);
     setAdminDist(dBGPExternal);
 }
~BgpRoutingTableEntry()
virtual inet::bgp::BgpRoutingTableEntry::~BgpRoutingTableEntry (void) inline virtual
 {}
Member Function Documentation
addAS()
void inet::bgp::BgpRoutingTableEntry::addAS (AsId newAS) inline
 { _ASList.push_back(newAS); }
Referenced by inet::bgp::BgpRouter::addToAdvertiseList(), inet::bgp::BgpRouter::decisionProcess(), and inet::bgp::BgpRouter::processMessage().
getAS()
AsId inet::bgp::BgpRoutingTableEntry::getAS (unsigned int index) const inline
 { return _ASList[index]; }
Referenced by inet::bgp::BgpRouter::asLoopDetection(), inet::bgp::BgpRouter::isInASList(), inet::bgp::operator<<(), and inet::bgp::BgpRouter::updateSendProcess().
getASCount()
unsigned int inet::bgp::BgpRoutingTableEntry::getASCount (void) const inline
 { return _ASList.size(); }
Referenced by inet::bgp::BgpRouter::asLoopDetection(), inet::bgp::BgpRouter::isInASList(), inet::bgp::operator<<(), inet::bgp::BgpRouter::tieBreakingProcess(), and inet::bgp::BgpRouter::updateSendProcess().
getLocalPreference()
int inet::bgp::BgpRoutingTableEntry::getLocalPreference (void) const inline
 { return localPreference; }
Referenced by inet::bgp::BgpRouter::decisionProcess(), inet::bgp::operator<<(), str(), and inet::bgp::BgpRouter::tieBreakingProcess().
getPathType()
RoutingPathType inet::bgp::BgpRoutingTableEntry::getPathType (void) const inline
 { return _pathType; }
Referenced by inet::bgp::operator<<(), inet::bgp::BgpRouter::tieBreakingProcess(), and inet::bgp::BgpRouter::updateSendProcess().
getPathTypeString()
const std::string inet::bgp::BgpRoutingTableEntry::getPathTypeString (RoutingPathType type) inline static
 {
     if (type == IGP)
         return "IGP";
     else if (type == EGP)
         return "EGP";
     else if (type == INCOMPLETE)
         return "INCOMPLETE";
     return "Unknown";
 }
Referenced by inet::bgp::operator<<(), and str().
isIBgpLearned()
bool inet::bgp::BgpRoutingTableEntry::isIBgpLearned (void) inline
 { return IBGP_learned; }
Referenced by inet::bgp::operator<<(), and inet::bgp::BgpRouter::updateSendProcess().
setIBgpLearned()
void inet::bgp::BgpRoutingTableEntry::setIBgpLearned (bool i) inline
 { IBGP_learned = i; }
Referenced by inet::bgp::BgpRouter::decisionProcess().
setLocalPreference()
void inet::bgp::BgpRoutingTableEntry::setLocalPreference (int l) inline
 { localPreference = l; }
Referenced by inet::bgp::BgpRouter::addToAdvertiseList(), inet::bgp::BgpRouter::decisionProcess(), and inet::bgp::BgpRouter::processMessage().
setPathType()
void inet::bgp::BgpRoutingTableEntry::setPathType (RoutingPathType type) inline
 { _pathType = type; }
Referenced by inet::bgp::BgpRouter::addToAdvertiseList(), and inet::bgp::BgpRouter::decisionProcess().
str()
std::string inet::bgp::BgpRoutingTableEntry::str () const inline virtual
Reimplemented from inet::Ipv4Route.
 {
     std::stringstream out;
     out << getSourceTypeAbbreviation();
     out << " ";
     if (getDestination().isUnspecified())
         out << "0.0.0.0";
     else
         out << getDestination();
     out << "/";
     if (getNetmask().isUnspecified())
         out << "0";
     else
         out << getNetmask().getNetmaskLength();
     out << " gw:";
     if (getGateway().isUnspecified())
         out << "*  ";
     else
         out << getGateway() << "  ";
     if (getRoutingTable() && getRoutingTable()->isAdminDistEnabled())
         out << "AD:" << getAdminDist() << "  ";
     out << "metric:" << getMetric() << "  ";
     out << "if:";
     if (!getInterface())
         out << "*";
     else
         out << getInterfaceName();
     out << " origin: " << BgpRoutingTableEntry::getPathTypeString(_pathType);
     if (IBGP_learned)
         out << " localPref: " << getLocalPreference();
     out << " ASlist: ";
     for (auto& element : _ASList)
         out << element << ' ';
     return out.str();
 }
Member Data Documentation
_ASList
std::vector<AsId> inet::bgp::BgpRoutingTableEntry::_ASList private
Referenced by str().
_pathType
RoutingPathType inet::bgp::BgpRoutingTableEntry::_pathType = INCOMPLETE private
Referenced by str().
IBGP_learned
bool inet::bgp::BgpRoutingTableEntry::IBGP_learned = false private
Referenced by str().
localPreference
int inet::bgp::BgpRoutingTableEntry::localPreference = 0 private
The documentation for this class was generated from the following file:
BgpRoutingTableEntry.h