INET Framework for OMNeT++/OMNEST: inet.h.txt File Reference
inet.h.txt File Reference
#include "lwip/opt.h"
#include "lwip/pbuf.h"
#include "lwip/ip_addr.h"
Macros
#define __LWIP_INET_H__
Functions
u16_t inet_chksum (void *data, u16_t len)
u16_t inet_chksum_pbuf (struct pbuf *p)
u16_t inet_chksum_pseudo (struct pbuf *p, struct ip_addr *src, struct ip_addr *dest, u8_t proto, u32_t proto_len)
u32_t inet_addr (const char *cp)
s8_t inet_aton (const char *cp, struct in_addr *addr)
u16_t htons (u16_t n)
u16_t ntohs (u16_t n)
u32_t htonl (u32_t n)
u32_t ntohl (u32_t n)
Macro Definition Documentation
__LWIP_INET_H__
#define __LWIP_INET_H__
Function Documentation
htonl()
u32_t htonl (u32_t n)
Referenced by inet::ExtLowerUdp::bind(), inet::sctp::SctpChecksum::checksum(), inet::ExtLowerUdp::connect(), inet::ExtLowerUdp::processPacketFromUpper(), inet::sctp::SctpHeaderSerializer::serialize(), inet::Ipv4HeaderSerializer::serialize(), and inet::tcp::TcpHeaderSerializer::serialize().
htons()
u16_t htons (u16_t n)
Referenced by inet::ExtLowerUdp::bind(), inet::ExtLowerUdp::connect(), inet::sctp::SctpHeaderSerializer::deserialize(), inet::ExtLowerUdp::processPacketFromUpper(), inet::sctp::SctpHeaderSerializer::serialize(), inet::Ipv4HeaderSerializer::serialize(), and inet::tcp::TcpHeaderSerializer::serialize().
inet_addr()
u32_t inet_addr (const char * cp)
inet_aton()
s8_t inet_aton (const char * cp, struct in_addr * addr)
inet_chksum()
u16_t inet_chksum (void * data, u16_t len)
inet_chksum_pbuf()
u16_t inet_chksum_pbuf (struct pbuf * p)
inet_chksum_pseudo()
u16_t inet_chksum_pseudo (struct pbuf * p, struct ip_addr * src, struct ip_addr * dest, u8_t proto, u32_t proto_len)
ntohl()
u32_t ntohl (u32_t n)
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::Ipv4HeaderSerializer::deserialize(), inet::tcp::TcpHeaderSerializer::deserialize(), and inet::ExtLowerUdp::processPacketFromLower().
ntohs()
u16_t ntohs (u16_t n)
Referenced by inet::sctp::SctpHeaderSerializer::deserialize(), inet::Ipv4HeaderSerializer::deserialize(), inet::tcp::TcpHeaderSerializer::deserialize(), inet::ExtLowerUdp::processPacketFromLower(), and inet::sctp::SctpHeaderSerializer::serialize().