INET Framework for OMNeT++/OMNEST: mem.h File Reference
mem.h File Reference
#include "lwip/opt.h"
Macros
#define LWIP_MEM_ALIGN_SIZE(size) (((size) + MEM_ALIGNMENT - 1) & ~(MEM_ALIGNMENT-1))
#define LWIP_MEM_ALIGN(addr) ((void *)(((mem_ptr_t)(addr) + MEM_ALIGNMENT - 1) & ~(mem_ptr_t)(MEM_ALIGNMENT-1)))
Typedefs
typedef u16_t mem_size_t
Functions
void mem_init (void)
void * mem_realloc (void *mem, mem_size_t size)
void * mem_malloc (mem_size_t size)
void * mem_calloc (mem_size_t count, mem_size_t size)
void mem_free (void *mem)
Macro Definition Documentation
LWIP_MEM_ALIGN
#define LWIP_MEM_ALIGN (addr) ((void *)(((mem_ptr_t)(addr) + MEM_ALIGNMENT - 1) & ~(mem_ptr_t)(MEM_ALIGNMENT-1)))
LWIP_MEM_ALIGN_SIZE
#define LWIP_MEM_ALIGN_SIZE (size) (((size) + MEM_ALIGNMENT - 1) & ~(MEM_ALIGNMENT-1))
Typedef Documentation
mem_size_t
typedef u16_t mem_size_t
Function Documentation
mem_calloc()
void* mem_calloc (mem_size_t count, mem_size_t size)
mem_free()
void mem_free (void * mem)
Referenced by inet::tcp::pbuf_free().
mem_init()
void mem_init (void)
mem_malloc()
void* mem_malloc (mem_size_t size)
Referenced by inet::tcp::pbuf_alloc().
mem_realloc()
void* mem_realloc (void * mem, mem_size_t size)
Referenced by inet::tcp::pbuf_realloc().