INET Framework for OMNeT++/OMNEST: inet::xmlutils Namespace Reference
inet::xmlutils Namespace Reference
Functions
const cXMLElement * getUniqueChild (const cXMLElement *node, const char *name)
const cXMLElement * getUniqueChildIfExists (const cXMLElement *node, const char *name)
bool parseBool (const char *text)
void checkTags (const cXMLElement *node, const char *allowed)
const char * getParameterStrValue (const cXMLElement *ptr, const char *name, const char *def)
bool getParameterBoolValue (const cXMLElement *ptr, const char *name, bool def)
bool getParameterBoolValue (const cXMLElement *ptr, const char *name)
const char * getParameterStrValue (const cXMLElement *ptr, const char *name)
int getParameterIntValue (const cXMLElement *ptr, const char *name, int def)
int getParameterIntValue (const cXMLElement *ptr, const char *name)
Ipv4Address getParameterIPAddressValue (const cXMLElement *ptr, const char *name, Ipv4Address def)
Ipv4Address getParameterIPAddressValue (const cXMLElement *ptr, const char *name)
double getParameterDoubleValue (const cXMLElement *ptr, const char *name, double def)
double getParameterDoubleValue (const cXMLElement *ptr, const char *name)
const char * getMandatoryAttribute (const cXMLElement &node, const char *attr)
const char * getMandatoryFilledAttribute (const cXMLElement &node, const char *attr)
bool getAttributeBoolValue (const cXMLElement *node, const char *attrName, bool defVal)
bool getAttributeBoolValue (const cXMLElement *node, const char *attrName)
Function Documentation
checkTags()
INET_API void inet::xmlutils::checkTags (const cXMLElement * node, const char * allowed)
 {
     std::vector<const char *> tags;
     cStringTokenizer st(allowed, " ");
     const char *nt;
     while ((nt = st.nextToken()) != nullptr)
         tags.push_back(nt);
     for (cXMLElement *child = node->getFirstChild(); child; child = child->getNextSibling()) {
         unsigned int i;
         for (i = 0; i < tags.size(); i++)
             if (!strcmp(child->getTagName(), tags[i]))
                 break;
         if (i == tags.size())
             throw cRuntimeError("Subtag <%s> not expected in <%s>",
                     child->getTagName(), node->getTagName());
     }
 }
Referenced by inet::RsvpTe::delSession(), inet::RsvpClassifier::readItemFromXML(), inet::LibTable::readTableFromXML(), inet::RsvpClassifier::readTableFromXML(), inet::RsvpTe::readTrafficFromXML(), inet::RsvpTe::readTrafficRouteFromXML(), and inet::RsvpTe::readTrafficSessionFromXML().
getAttributeBoolValue() [1/2]
INET_API bool inet::xmlutils::getAttributeBoolValue (const cXMLElement * node, const char * attrName)
 {
     const char *attrStr = getMandatoryFilledAttribute(*node, attrName);
     return parseBool(attrStr);
 }
getAttributeBoolValue() [2/2]
INET_API bool inet::xmlutils::getAttributeBoolValue (const cXMLElement * node, const char * attrName, bool defVal)
 {
     const char *attrStr = node->getAttribute(attrName);
     if (attrStr && *attrStr)
         return parseBool(attrStr);
     return defVal;
 }
Referenced by inet::MatrixCloudDelayer::initialize(), inet::MatrixCloudDelayer::MatrixEntry::MatrixEntry(), inet::SettableClock::processCommand(), inet::ScenarioManager::processCreateModuleCommand(), and inet::Ipv4NetworkConfigurator::readInterfaceConfiguration().
getMandatoryAttribute()
const INET_API char * inet::xmlutils::getMandatoryAttribute (const cXMLElement & node, const char * attr)
 {
     const char *s = node.getAttribute(attr);
     if (s == nullptr)
         throw cRuntimeError("required attribute %s of <%s> missing at %s",
                 attr, node.getTagName(), node.getSourceLocation());
     return s;
 }
Referenced by inet::MultiFieldClassifier::configureFilters(), inet::ScenarioManager::createConnection(), getMandatoryFilledAttribute(), inet::ScenarioManager::processSetChannelParamCommand(), inet::ScenarioManager::processSetParamCommand(), and inet::Ipv4NetworkConfigurator::readManualRouteConfiguration().
getMandatoryFilledAttribute()
const INET_API char * inet::xmlutils::getMandatoryFilledAttribute (const cXMLElement & node, const char * attr)
 {
     const char *s = getMandatoryAttribute(node, attr);
     if (*s == '\0')
         throw cRuntimeError("required attribute %s of <%s> is empty at %s",
                 attr, node.getTagName(), node.getSourceLocation());
     return s;
 }
Referenced by inet::ScenarioManager::createConnection(), inet::ospfv2::Ospfv2ConfigReader::findMatchingConfig(), getAttributeBoolValue(), inet::ScenarioManager::getConnection(), inet::ospfv2::Ospfv2ConfigReader::getInterfaceByXMLAttributesOf(), inet::ScenarioManager::getRequiredModule(), inet::ospfv2::Ospfv2ConfigReader::loadAreaFromXML(), inet::ospfv2::Ospfv2ConfigReader::loadConfigFromXML(), inet::ospfv2::Ospfv2ConfigReader::loadExternalRoute(), inet::ospfv2::Ospfv2ConfigReader::loadHostRoute(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink(), inet::SettableClock::processCommand(), inet::ScenarioManager::processConnectCommand(), inet::ScenarioManager::processCreateModuleCommand(), inet::ScenarioManager::processDeleteModuleCommand(), inet::ScenarioManager::processSetChannelParamCommand(), inet::ScenarioManager::processSetParamCommand(), and inet::Ipv4NetworkConfigurator::readManualRouteConfiguration().
getParameterBoolValue() [1/2]
INET_API bool inet::xmlutils::getParameterBoolValue (const cXMLElement * ptr, const char * name)
 {
     const cXMLElement *xvalue = getUniqueChild(ptr, name);
     return parseBool(xvalue->getNodeValue());
 }
getParameterBoolValue() [2/2]
INET_API bool inet::xmlutils::getParameterBoolValue (const cXMLElement * ptr, const char * name, bool def)
 {
     const cXMLElement *xvalue = getUniqueChildIfExists(ptr, name);
     if (xvalue)
         return parseBool(xvalue->getNodeValue());
     else
         return def;
 }
Referenced by inet::RsvpTe::readTrafficSessionFromXML().
getParameterDoubleValue() [1/2]
INET_API double inet::xmlutils::getParameterDoubleValue (const cXMLElement * ptr, const char * name)
 {
     const cXMLElement *xvalue = getUniqueChild(ptr, name);
     return strtod(xvalue->getNodeValue(), nullptr);
 }
getParameterDoubleValue() [2/2]
INET_API double inet::xmlutils::getParameterDoubleValue (const cXMLElement * ptr, const char * name, double def)
 {
     const cXMLElement *xvalue = getUniqueChildIfExists(ptr, name);
     if (xvalue)
         return strtod(xvalue->getNodeValue(), nullptr);
     else
         return def;
 }
Referenced by inet::RsvpTe::readTrafficSessionFromXML().
getParameterIntValue() [1/2]
INET_API int inet::xmlutils::getParameterIntValue (const cXMLElement * ptr, const char * name)
 {
     const cXMLElement *xvalue = getUniqueChild(ptr, name);
     return atoi(xvalue->getNodeValue());
 }
getParameterIntValue() [2/2]
INET_API int inet::xmlutils::getParameterIntValue (const cXMLElement * ptr, const char * name, int def)
 {
     const cXMLElement *xvalue = getUniqueChildIfExists(ptr, name);
     if (xvalue)
         return atoi(xvalue->getNodeValue());
     else
         return def;
 }
Referenced by inet::RsvpTe::delSession(), inet::RsvpClassifier::readItemFromXML(), inet::LibTable::readTableFromXML(), and inet::RsvpTe::readTrafficSessionFromXML().
getParameterIPAddressValue() [1/2]
INET_API Ipv4Address inet::xmlutils::getParameterIPAddressValue (const cXMLElement * ptr, const char * name)
 {
     const cXMLElement *xvalue = getUniqueChild(ptr, name);
     return L3AddressResolver().resolve(xvalue->getNodeValue()).toIpv4();
 }
getParameterIPAddressValue() [2/2]
INET_API Ipv4Address inet::xmlutils::getParameterIPAddressValue (const cXMLElement * ptr, const char * name, Ipv4Address def)
 {
     const cXMLElement *xvalue = getUniqueChildIfExists(ptr, name);
     if (xvalue)
         return L3AddressResolver().resolve(xvalue->getNodeValue()).toIpv4();
     else
         return def;
 }
Referenced by inet::RsvpTe::delSession(), inet::RsvpClassifier::readItemFromXML(), and inet::RsvpTe::readTrafficSessionFromXML().
getParameterStrValue() [1/2]
const INET_API char * inet::xmlutils::getParameterStrValue (const cXMLElement * ptr, const char * name)
 {
     const cXMLElement *xvalue = getUniqueChild(ptr, name);
     return xvalue->getNodeValue();
 }
getParameterStrValue() [2/2]
const INET_API char * inet::xmlutils::getParameterStrValue (const cXMLElement * ptr, const char * name, const char * def)
 {
     const cXMLElement *xvalue = getUniqueChildIfExists(ptr, name);
     if (xvalue)
         return xvalue->getNodeValue();
     else
         return def;
 }
Referenced by inet::LibTable::readTableFromXML(), and inet::RsvpTe::readTrafficSessionFromXML().
getUniqueChild()
const INET_API cXMLElement * inet::xmlutils::getUniqueChild (const cXMLElement * node, const char * name)
 {
     const cXMLElement *child = getUniqueChildIfExists(node, name);
     if (!child)
         throw cRuntimeError("XML error: exactly one %s element expected", name);
     return child;
 }
Referenced by getParameterBoolValue(), getParameterDoubleValue(), getParameterIntValue(), getParameterIPAddressValue(), getParameterStrValue(), inet::MatrixCloudDelayer::initialize(), inet::LibTable::readTableFromXML(), and inet::RsvpTe::readTrafficSessionFromXML().
getUniqueChildIfExists()
const INET_API cXMLElement * inet::xmlutils::getUniqueChildIfExists (const cXMLElement * node, const char * name)
 {
     cXMLElementList list = node->getChildrenByTagName(name);
     if (list.size() > 1)
         throw cRuntimeError("XML error: at most one %s element expected", name);
     else if (list.size() == 1)
         return *list.begin();
     else
         return nullptr;
 }
Referenced by inet::RsvpTe::delSession(), getParameterBoolValue(), getParameterDoubleValue(), getParameterIntValue(), getParameterIPAddressValue(), getParameterStrValue(), getUniqueChild(), inet::RsvpClassifier::readItemFromXML(), and inet::RsvpTe::readTrafficSessionFromXML().
parseBool()
INET_API bool inet::xmlutils::parseBool (const char * text)
 {
     if (!strcasecmp(text, "down"))
         return false;
     else if (!strcasecmp(text, "off"))
         return false;
     else if (!strcasecmp(text, "false"))
         return false;
     else if (!strcasecmp(text, "no"))
         return false;
     else if (!strcasecmp(text, "0"))
         return false;
     else if (!strcasecmp(text, "up"))
         return true;
     else if (!strcasecmp(text, "on"))
         return true;
     else if (!strcasecmp(text, "true"))
         return true;
     else if (!strcasecmp(text, "yes"))
         return true;
     else if (!strcasecmp(text, "1"))
         return true;
     else
         throw cRuntimeError("Unknown bool constant: %s", text);
 }
Referenced by getAttributeBoolValue(), and getParameterBoolValue().