INET Framework for OMNeT++/OMNEST: inet::ieee80211 Namespace Reference
inet::ieee80211 Namespace Reference
Classes
class AarfRateControl
Implements the ARF and AARF rate control algorithms.
class AckFs
class AckHandler
class AlternativesFs
class BasicFragmentationPolicy
class BasicMpduAggregationPolicy
class BasicMsduAggregationPolicy
class BasicReassembly
class BlockAckRecord
class BlockAckReordering
class BlockAckReqBlockAckFs
class Contention
The default implementation of IContention.
class CtsFs
class CtsPolicy
class CtsProcedure
class DataFs
class Dcaf
class Dcf
Implements IEEE 802.11 Distributed Coordination Function.
class DcfFs
class DcfReceiveLifetimeHandler
class DcfTransmitLifetimeHandler
class Defragmentation
class Ds
The default implementation of IDs.
class Edca
Implements IEEE 802.11 Enhanced Distributed Channel Access.
class EdcaCollisionController
class Edcaf
Implements IEEE 802.11 Enhanced Distributed Channel Access Function.
class EdcaTransmitLifetimeHandler
class FragFrameAckFs
class Fragmentation
class FrameSequenceContext
class FrameSequenceDurationFilter
class FrameSequenceHandler
class FrameSequenceNumPacketsFilter
class Hcca
Implements IEEE 802.11 Hybrid coordination function (HCF) Controlled Channel Access.
class Hcf
Implements IEEE 802.11 Hybrid Coordination Function.
class HcfFs
class HtTxOpFs
class IAckHandler
class IBlockAckAgreementHandlerCallback
class IChannelAccess
class IContention
Abstract interface for processes that implement contention-based channel access.
class ICoordinationFunction
Interface for IEEE 802.11 Coordination Functions.
class ICtsPolicy
class ICtsProcedure
class IDefragmentation
class IDs
Abstract interface for distribution service.
class IDuplicateRemoval
class IEdcaCollisionController
class Ieee80211AckFrame
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:152 by opp_msgtool.
class Ieee80211ActionFrame
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:234 by opp_msgtool.
class Ieee80211AddbaRequest
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:260 by opp_msgtool.
class Ieee80211AddbaResponse
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:289 by opp_msgtool.
class Ieee80211AgentSta
Used in 802.11 infrastructure mode: in a station (STA), this module controls channel scanning, association and handovers, by sending commands (e.g.
class Ieee80211AssociationRequestFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:177 by opp_msgtool.
class Ieee80211AssociationResponseFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:194 by opp_msgtool.
class Ieee80211AuthenticationFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:139 by opp_msgtool.
class Ieee80211BasicBlockAck
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:417 by opp_msgtool.
class Ieee80211BasicBlockAckReq
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:346 by opp_msgtool.
class Ieee80211BeaconFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:211 by opp_msgtool.
class Ieee80211BlockAck
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:399 by opp_msgtool.
class Ieee80211BlockAckReq
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:334 by opp_msgtool.
class Ieee80211BroadcastFilter
struct Ieee80211CapabilityInformation
Struct generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:26 by opp_msgtool.
class Ieee80211CompressedBlockAck
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:445 by opp_msgtool.
class Ieee80211CompressedBlockAckReq
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:363 by opp_msgtool.
class Ieee80211CtsFrame
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:179 by opp_msgtool.
class Ieee80211DataHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:199 by opp_msgtool.
class Ieee80211DataOrMgmtHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:188 by opp_msgtool.
class Ieee80211DeauthenticationFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:150 by opp_msgtool.
class Ieee80211Delba
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:313 by opp_msgtool.
class Ieee80211DisassociationFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:159 by opp_msgtool.
struct Ieee80211HandoverParameters
Struct generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:41 by opp_msgtool.
class Ieee80211LlcEpd
class Ieee80211LlcLpd
class Ieee80211Mac
Implements the IEEE 802.11 MAC.
class Ieee80211MacHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:115 by opp_msgtool.
class Ieee80211MacHeaderSerializer
Converts between Ieee80211MacHeader and binary network byte order IEEE 802.11 mac header.
class Ieee80211MacProtocolPrinter
class Ieee80211MacTrailer
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:100 by opp_msgtool.
class Ieee80211MacTrailerSerializer
class Ieee80211MgmtAdhoc
Used in 802.11 ad-hoc mode.
class Ieee80211MgmtAp
Used in 802.11 infrastructure mode: handles management frames for an access point (AP).
class Ieee80211MgmtApBase
Used in 802.11 infrastructure mode: abstract base class for management frame handling for access points (APs).
class Ieee80211MgmtApSimplified
Used in 802.11 infrastructure mode: handles management frames for an access point (AP).
class Ieee80211MgmtBase
Abstract base class for 802.11 infrastructure mode management components.
class Ieee80211MgmtFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:125 by opp_msgtool.
class Ieee80211MgmtFrameSerializer
Converts between Ieee80211MgmtFrame and binary network byte order IEEE 802.11 mgmt frame.
class Ieee80211MgmtHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:229 by opp_msgtool.
class Ieee80211MgmtProtocolPrinter
class Ieee80211MgmtSta
Used in 802.11 infrastructure mode: handles management frames for a station (STA).
class Ieee80211MgmtStaSimplified
Used in 802.11 infrastructure mode: handles management frames for a station (STA).
class Ieee80211Mib
class Ieee80211MpduSubframeHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:251 by opp_msgtool.
class Ieee80211MpduSubframeHeaderSerializer
Converts between Ieee80211MpduSubframeHeader and binary network byte order IEEE 802.11 Mpdu header.
class Ieee80211MsduSubframeHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:243 by opp_msgtool.
class Ieee80211MsduSubframeHeaderSerializer
Converts between Ieee80211MsduSubframeHeader and binary network byte order IEEE 802.11 Msdu header.
class Ieee80211MulticastFilter
class Ieee80211MultiTidBlockAck
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:466 by opp_msgtool.
class Ieee80211MultiTidBlockAckReq
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:381 by opp_msgtool.
class Ieee80211NotRetryFilter
class Ieee80211OneAddressHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:145 by opp_msgtool.
class Ieee80211Portal
class Ieee80211Prim_AssociateConfirm
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:175 by opp_msgtool.
class Ieee80211Prim_AssociateRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:165 by opp_msgtool.
class Ieee80211Prim_AuthenticateConfirm
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:144 by opp_msgtool.
class Ieee80211Prim_AuthenticateRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:134 by opp_msgtool.
class Ieee80211Prim_BssDescription
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:106 by opp_msgtool.
class Ieee80211Prim_DeauthenticateRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:156 by opp_msgtool.
class Ieee80211Prim_DisassociateRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:201 by opp_msgtool.
class Ieee80211Prim_ReassociateConfirm
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:190 by opp_msgtool.
class Ieee80211Prim_ReassociateRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:183 by opp_msgtool.
class Ieee80211Prim_ScanConfirm
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:121 by opp_msgtool.
class Ieee80211Prim_ScanRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:94 by opp_msgtool.
class Ieee80211PrimConfirm
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:86 by opp_msgtool.
class Ieee80211PrimRequest
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:79 by opp_msgtool.
class Ieee80211ProbeRequestFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:168 by opp_msgtool.
class Ieee80211ProbeResponseFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:223 by opp_msgtool.
class Ieee80211ReassociationRequestFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:186 by opp_msgtool.
class Ieee80211ReassociationResponseFrame
Class generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:204 by opp_msgtool.
class Ieee80211RetryFilter
class Ieee80211RtsFrame
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:170 by opp_msgtool.
struct Ieee80211SupportedRatesElement
Struct generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:116 by opp_msgtool.
class Ieee80211TwoAddressHeader
Class generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:161 by opp_msgtool.
class Ieee80211UnicastFilter
class IFragmentation
class IFragmentationPolicy
class IFrameSequence
class IFrameSequenceHandler
class IFrameSequenceStep
class IIeee80211Llc
class IMpduAggregation
class IMpduAggregationPolicy
class IMpduDeaggregation
class IMsduAggregation
class IMsduAggregationPolicy
class IMsduDeaggregation
class InProgressFrames
class IOriginatorAckPolicy
class IOriginatorBlockAckAgreementHandler
class IOriginatorBlockAckAgreementPolicy
class IOriginatorBlockAckProcedure
class IOriginatorMacDataService
class IOriginatorQoSAckPolicy
class IProcedureCallback
class IQosRateSelection
Abstract interface for rate selection.
class IRateControl
Abstract interface for auto rate control algorithms.
class IRateSelection
Abstract interface for rate selection.
class IReassembly
Abstract interface for classes that encapsulate the functionality of reassembling frames from fragments.
class IReceiveStep
class IRecipientAckPolicy
class IRecipientAckProcedure
class IRecipientBlockAckAgreementHandler
class IRecipientBlockAckAgreementPolicy
class IRecipientBlockAckProcedure
class IRecipientMacDataService
class IRecipientQosAckPolicy
class IRecipientQosMacDataService
class IRecoveryProcedure
class IRtsPolicy
class IRtsProcedure
class IRx
Abstract interface for Rx processes.
class ISequenceNumberAssignment
class ITransmitLifetimeHandler
class ITransmitStep
class ITx
Abstract interface for unconditionally transmitting a frame immediately or after waiting for a specified inter-frame space (usually SIFS).
class LastFrameAckFs
class LegacyDuplicateRemoval
class LegacySequenceNumberAssignment
class LlcProtocolTag
Class generated from inet/linklayer/ieee80211/llc/LlcProtocolTag.msg:35 by opp_msgtool.
class ManagementAckFs
class ManagementFs
class Mcf
Implements IEEE 802.11 Mesh Coordination Function.
class McfFs
class ModeSetListener
class MpduAggregation
class MpduDeaggregation
class MsduAggregation
class MsduDeaggregation
class NonQoSContext
class NonQosRecoveryProcedure
class NonQoSSequenceNumberAssignment
class OnoeRateControl
Implements the Onoe rate control algorithms.
class OptionalFs
class OriginatorAckPolicy
class OriginatorBlockAckAgreement
class OriginatorBlockAckAgreementHandler
class OriginatorBlockAckAgreementPolicy
class OriginatorBlockAckProcedure
class OriginatorMacDataService
class OriginatorProtectionMechanism
class OriginatorQosAckPolicy
class OriginatorQosMacDataService
class Pcf
Implements IEEE 802.11 Point Coordination Function.
class PcfFs
class QosAckHandler
class QoSContext
class QosCtsPolicy
class QoSDuplicateRemoval
class QosRateSelection
class QosRecoveryProcedure
class QosRtsPolicy
class QoSSequenceNumberAssignment
class RateControlBase
class RateSelection
class ReceiveBuffer
class ReceiveStep
class RecipientAckPolicy
class RecipientAckProcedure
class RecipientBlockAckAgreement
class RecipientBlockAckAgreementHandler
class RecipientBlockAckAgreementPolicy
class RecipientBlockAckProcedure
class RecipientMacDataService
class RecipientQosAckPolicy
class RecipientQosMacDataService
class RepeatingFs
class RtsCtsFs
class RtsFs
class RtsPolicy
class RtsProcedure
class RtsTransmitStep
class Rx
The default implementation of IRx.
class SelfCtsFs
class SequenceControlField
8.2.4.4.1 Sequence Control field structure The Sequence Control field is 16 bits in length and consists of two subfields, the Sequence Number and the Fragment Number.
struct SequenceNumberCyclic
class SequentialFs
class SingleProtectionMechanism
class StationRetryCounters
class TransmitStep
class Tx
The default implementation of ITx.
class TxopDurationFilter
class TxOpFs
class TxopProcedure
Typedefs
typedef int8_t FragmentNumber
typedef int8_t Tid
typedef int16_t SequenceNumber
Enumerations
enum LlcProtocolId { LPD = 0, EPD = 1 }
Enum generated from inet/linklayer/ieee80211/llc/LlcProtocolTag.msg:25 by opp_msgtool.
enum AccessCategory {
AC_BK = 0, AC_BE = 1, AC_VI = 2, AC_VO = 3,
AC_NUMCATEGORIES
}
IEEE 802.11e QoS (EDCA) access categories.
enum Ieee80211FrameType {
ST_ASSOCIATIONREQUEST = 0x00, ST_ASSOCIATIONRESPONSE = 0x01, ST_REASSOCIATIONREQUEST = 0x02, ST_REASSOCIATIONRESPONSE = 0x03,
ST_PROBEREQUEST = 0x04, ST_PROBERESPONSE = 0x05, ST_BEACON = 0x08, ST_ATIM = 0x09,
ST_DISASSOCIATION = 0x0a, ST_AUTHENTICATION = 0x0b, ST_DEAUTHENTICATION = 0x0c, ST_ACTION = 0x0d,
ST_NOACKACTION = 0x0e, ST_PSPOLL = 0x1a, ST_RTS = 0x1b, ST_CTS = 0x1c,
ST_ACK = 0x1d, ST_BLOCKACK_REQ = 0x18, ST_BLOCKACK = 0x19, ST_DATA = 0x20,
ST_DATA_WITH_QOS = 0x28, ST_LBMS_REQUEST = 0x30, ST_LBMS_REPORT = 0x31
}
Enum generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:56 by opp_msgtool.
enum AckPolicy { NORMAL_ACK = 0, NO_ACK = 1, NO_EXPLICIT_ACK = 2, BLOCK_ACK = 3 }
Enum generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:92 by opp_msgtool.
enum Ieee80211ReasonCode {
RC_UNSPECIFIED = 1, RC_PREV_AUTH_EXPIRED = 2, RC_DEAUTH_MS_LEAVING = 3, RC_DISASS_INACTIVITY = 4,
RC_DISASS_TOO_MANY_MS = 5, RC_NONAUTH_CLASS2 = 6, RC_NONASS_CLASS3 = 7, RC_DIASS_MS_LEAVING = 8,
RC_NONAUTH_ASS_REQUEST = 9, RC_MESH_PEERING_CANCELLED = 52, RC_MESH_MAX_PEERS = 53, RC_MESH_CONFIGURATION_POLICY_VIOLATION = 54,
RC_MESH_CLOSE_RCVD = 55, RC_MESH_MAX_RETRIES = 56, RC_MESH_CONFIRM_TIMEOUT = 57, RC_MESH_INVALID_GTK = 58,
RC_MESH_INCONSISTENT_PARAMETERS = 59, RC_MESH_INVALID_SECURITY_CAPABILITY = 60, RC_MESH_PATH_ERROR_NO_PROXY_INFORMATION = 61, RC_MESH_PATH_ERROR_NO_FORWARDING_INFORMATION = 60,
RC_MESH_PATH_ERROR_DESTINATION_UNREACHABLE = 63, RC_MAC_ADDRESS_ALREADY_EXISTS_IN_MBSS = 64, RC_MESH_CHANNEL_SWITCH_REGULATORY_REQUIREMENTS = 65, RC_MESH_CHANNEL_SWITCH_UNSPECIFIED = 66
}
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:53 by opp_msgtool.
enum Ieee80211StatusCode {
SC_SUCCESSFUL = 0, SC_UNSPECIFIED = 1, SC_UNSUP_CAP = 10, SC_REASS_DENIED = 11,
SC_ASS_DENIED_UNKNOWN = 12, SC_AUTH_ALG0_UNSUP = 13, SC_AUTH_OUT_OF_SEQ = 14, SC_AUTH_CHALLENGE_FAIL = 15,
SC_AUTH_TIMEOUT = 16, SC_ASS_TOO_MANY_MS = 17, SC_DATARATE_UNSUP = 18, SC_AUTH_REJECT_ANTI_CLOGING = 76,
SC_AUTH_REJECT_FINITE_CYC_GROUP_UNS = 77, SC_TBTT_REQUEST = 78
}
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:85 by opp_msgtool.
enum Ieee80211HwmpCode {
IE11S_GANN = 125, IE11S_RANN = 126, IE11S_PREQ = 130, IE11S_PREP = 131,
IE11S_PERR = 132
}
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:104 by opp_msgtool.
enum Ieee80211PrimRequestCode {
PR_SCAN_REQUEST = 1, PR_AUTHENTICATE_REQUEST = 2, PR_DEAUTHENTICATE_REQUEST = 3, PR_ASSOCIATE_REQUEST = 4,
PR_REASSOCIATE_REQUEST = 5, PR_DISASSOCIATE_REQUEST = 6
}
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:23 by opp_msgtool.
enum Ieee80211PrimConfirmCode {
PR_SCAN_CONFIRM = 1, PR_AUTHENTICATE_CONFIRM = 2, PR_DEAUTHENTICATE_CONFIRM = 3, PR_ASSOCIATE_CONFIRM = 4,
PR_REASSOCIATE_CONFIRM = 5, PR_DISASSOCIATE_CONFIRM = 6
}
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:41 by opp_msgtool.
enum Ieee80211BssType { BSSTYPE_ANY = 0, BSSTYPE_INFRASTRUCTURE = 1, BSSTYPE_INDEPENDENT = 2 }
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:52 by opp_msgtool.
enum Ieee80211PrimResultCode {
PRC_SUCCESS = 0, PRC_INVALID_PARAMETERS = 1, PRC_TIMEOUT = 2, PRC_TOO_MANY_SIMULTANEOUS_REQUESTS = 3,
PRC_REFUSED = 4
}
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:66 by opp_msgtool.
Functions
Define_Module (Ieee80211LlcEpd)
Define_Module (Ieee80211LlcLpd)
void doParsimPacking (omnetpp::cCommBuffer *b, const LlcProtocolId &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, LlcProtocolId &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const LlcProtocolTag &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, LlcProtocolTag &obj)
Define_Module (BasicMpduAggregationPolicy)
Define_Module (BasicMsduAggregationPolicy)
Register_Class (MpduAggregation)
Register_Class (MpduDeaggregation)
Register_Class (MsduAggregation)
Register_Class (MsduDeaggregation)
Define_Module (OriginatorBlockAckAgreementPolicy)
std::ostream & operator<< (std::ostream &os, const RecipientBlockAckAgreement &agreement)
Define_Module (RecipientBlockAckAgreementPolicy)
Define_Module (Dcaf)
Define_Module (Edca)
Define_Module (Edcaf)
double fallback (double a, double b)
simtime_t fallback (simtime_t a, simtime_t b)
Define_Module (Hcca)
std::string printAccessCategory (AccessCategory ac)
std::ostream & operator<< (std::ostream &os, const SequenceNumberCyclic &sequenceNumber)
Register_ResultFilter ("ieee80211Unicast", Ieee80211UnicastFilter)
Register_ResultFilter ("ieee80211Multicast", Ieee80211MulticastFilter)
Register_ResultFilter ("ieee80211Broadcast", Ieee80211BroadcastFilter)
Register_ResultFilter ("ieee80211Retry", Ieee80211RetryFilter)
Register_ResultFilter ("ieee80211NotRetry", Ieee80211NotRetryFilter)
std::ostream & operator<< (std::ostream &os, const SequenceControlField &field)
Register_Enum (Contention::State,(Contention::IDLE, Contention::DEFER, Contention::IFS_AND_BACKOFF))
Define_Module (Contention)
Define_Module (EdcaCollisionController)
Define_Module (Dcf)
Define_Module (Hcf)
Define_Module (Mcf)
Define_Module (Pcf)
Define_Module (Ds)
Define_Module (BasicFragmentationPolicy)
Register_Class (BasicReassembly)
Register_Class (Defragmentation)
Register_Class (Fragmentation)
Register_ResultFilter ("frameSequenceDuration", FrameSequenceDurationFilter)
Register_ResultFilter ("frameSequenceNumPackets", FrameSequenceNumPacketsFilter)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211FrameType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211FrameType &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const AckPolicy &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, AckPolicy &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MacTrailer &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MacTrailer &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MacHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MacHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211OneAddressHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211OneAddressHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211AckFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211AckFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211TwoAddressHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211TwoAddressHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211RtsFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211RtsFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211CtsFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211CtsFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211DataOrMgmtHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211DataOrMgmtHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211DataHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211DataHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MgmtHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MgmtHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ActionFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ActionFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MsduSubframeHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MsduSubframeHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MpduSubframeHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MpduSubframeHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211AddbaRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211AddbaRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211AddbaResponse &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211AddbaResponse &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Delba &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Delba &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211BlockAckReq &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211BlockAckReq &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211BasicBlockAckReq &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211BasicBlockAckReq &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211CompressedBlockAckReq &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211CompressedBlockAckReq &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MultiTidBlockAckReq &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MultiTidBlockAckReq &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211BlockAck &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211BlockAck &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211BasicBlockAck &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211BasicBlockAck &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211CompressedBlockAck &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211CompressedBlockAck &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MultiTidBlockAck &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MultiTidBlockAck &obj)
Define_Module (Ieee80211Mac)
Register_Serializer (Ieee80211MacHeader, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211DataOrMgmtHeader, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211DataHeader, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211MgmtHeader, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211AckFrame, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211RtsFrame, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211CtsFrame, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211BasicBlockAckReq, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211CompressedBlockAckReq, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211MultiTidBlockAckReq, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211BasicBlockAck, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211CompressedBlockAck, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211MultiTidBlockAck, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211ActionFrame, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211AddbaRequest, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211AddbaResponse, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211Delba, Ieee80211MacHeaderSerializer)
Register_Serializer (Ieee80211MacTrailer, Ieee80211MacTrailerSerializer)
Register_Serializer (Ieee80211MsduSubframeHeader, Ieee80211MsduSubframeHeaderSerializer)
Register_Serializer (Ieee80211MpduSubframeHeader, Ieee80211MpduSubframeHeaderSerializer)
Define_Module (AckHandler)
std::ostream & operator<< (std::ostream &os, const AckHandler::Status &status)
Define_Module (NonQosRecoveryProcedure)
Define_Module (OriginatorAckPolicy)
Define_Module (OriginatorMacDataService)
Define_Module (OriginatorQosAckPolicy)
Define_Module (OriginatorQosMacDataService)
Define_Module (QosAckHandler)
std::ostream & operator<< (std::ostream &os, const Tid tid)
std::ostream & operator<< (std::ostream &os, const QosAckHandler::Status &status)
template<typename K , typename V >
std::ostream & operator<< (std::ostream &os, const std::pair< K, V > &pair)
Define_Module (QosRecoveryProcedure)
std::ostream & operator<< (std::ostream &os, const std::pair< Tid, SequenceControlField > &p)
Define_Module (QosRtsPolicy)
Define_Module (RtsPolicy)
Define_Module (TxopProcedure)
Register_ResultFilter ("txopDuration", TxopDurationFilter)
Define_Module (OriginatorProtectionMechanism)
Define_Module (SingleProtectionMechanism)
Define_Module (InProgressFrames)
Register_Packet_Comparator_Function (MgmtOverDataComparator, compareMgmtOverData)
Register_Packet_Comparator_Function (MgmtOverMulticastOverUnicastComparator, compareMgmtOverMulticastOverUnicast)
Register_Packet_Classifier_Function (MgmtOverDataClassifier, classifyMgmtOverData)
Register_Packet_Classifier_Function (MgmtOverMulticastOverUnicastClassifier, classifyMgmtOverMulticastOverUnicast)
Define_Module (AarfRateControl)
Define_Module (OnoeRateControl)
Define_Module (QosRateSelection)
Define_Module (RateSelection)
Define_Module (CtsPolicy)
Define_Module (QosCtsPolicy)
Define_Module (RecipientAckPolicy)
Define_Module (RecipientMacDataService)
Define_Module (RecipientQosAckPolicy)
Define_Module (RecipientQosMacDataService)
Define_Module (Rx)
Define_Module (Tx)
Define_Module (Ieee80211AgentSta)
Define_Module (Ieee80211MgmtAdhoc)
Define_Module (Ieee80211MgmtAp)
Register_Class (Ieee80211MgmtAp::NotificationInfoSta)
Define_Module (Ieee80211MgmtApSimplified)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ieee80211CapabilityInformation &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ieee80211CapabilityInformation &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211CapabilityInformation &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211CapabilityInformation &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ieee80211HandoverParameters &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ieee80211HandoverParameters &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211HandoverParameters &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211HandoverParameters &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ReasonCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ReasonCode &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211StatusCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211StatusCode &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211HwmpCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211HwmpCode &e)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ieee80211SupportedRatesElement &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ieee80211SupportedRatesElement &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211SupportedRatesElement &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211SupportedRatesElement &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211MgmtFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211MgmtFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211AuthenticationFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211AuthenticationFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211DeauthenticationFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211DeauthenticationFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211DisassociationFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211DisassociationFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ProbeRequestFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ProbeRequestFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211AssociationRequestFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211AssociationRequestFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ReassociationRequestFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ReassociationRequestFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211AssociationResponseFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211AssociationResponseFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ReassociationResponseFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ReassociationResponseFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211BeaconFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211BeaconFrame &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ProbeResponseFrame &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ProbeResponseFrame &obj)
Register_Serializer (Ieee80211AssociationRequestFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211AssociationResponseFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211AuthenticationFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211BeaconFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211DeauthenticationFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211DisassociationFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211ProbeRequestFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211ProbeResponseFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211ReassociationRequestFrame, Ieee80211MgmtFrameSerializer)
Register_Serializer (Ieee80211ReassociationResponseFrame, Ieee80211MgmtFrameSerializer)
Define_Module (Ieee80211MgmtSta)
std::ostream & operator<< (std::ostream &os, const Ieee80211MgmtSta::ScanningInfo &scanning)
std::ostream & operator<< (std::ostream &os, const Ieee80211MgmtSta::ApInfo &ap)
std::ostream & operator<< (std::ostream &os, const Ieee80211MgmtSta::AssociatedApInfo &assocAP)
Define_Module (Ieee80211MgmtStaSimplified)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PrimRequestCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PrimRequestCode &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PrimConfirmCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PrimConfirmCode &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211BssType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211BssType &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PrimResultCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PrimResultCode &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PrimRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PrimRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PrimConfirm &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PrimConfirm &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_ScanRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_ScanRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_BssDescription &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_BssDescription &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_ScanConfirm &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_ScanConfirm &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_AuthenticateRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_AuthenticateRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_AuthenticateConfirm &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_AuthenticateConfirm &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_DeauthenticateRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_DeauthenticateRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_AssociateRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_AssociateRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_AssociateConfirm &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_AssociateConfirm &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_ReassociateRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_ReassociateRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_ReassociateConfirm &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_ReassociateConfirm &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211Prim_DisassociateRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211Prim_DisassociateRequest &obj)
Define_Module (Ieee80211Mib)
Define_Module (Ieee80211Portal)
Variables
const b LENGTH_RTS = b(160)
const b LENGTH_CTS = b(112)
const b LENGTH_ACK = b(112)
const b LENGTH_MGMT = B(28)
const b LENGTH_ADDBAREQ = LENGTH_MGMT + B(9)
const b LENGTH_ADDBARESP = LENGTH_MGMT + B(9)
const b LENGTH_DELBA = LENGTH_MGMT + B(6)
const b LENGTH_BASIC_BLOCKACK = B(16 + 2 + (2 + 128) + 4)
const b DATAFRAME_HEADER_MINLENGTH = B(2 + 2 + 3 * 6 + 2)
const b QOSCONTROL_PART_LENGTH = b(2 * 8)
const short int MAX_NUM_FRAGMENTS = 16
const b LENGTH_A_MSDU_SUBFRAME_HEADER = B(14)
const b LENGTH_A_MPDU_SUBFRAME_HEADER = b(4 + 12 + 8 + 8)
Typedef Documentation
FragmentNumber
typedef int8_t inet::ieee80211::FragmentNumber
SequenceNumber
typedef int16_t inet::ieee80211::SequenceNumber
Tid
typedef int8_t inet::ieee80211::Tid
Enumeration Type Documentation
AccessCategory
enum inet::ieee80211::AccessCategory
IEEE 802.11e QoS (EDCA) access categories.
Enumerator
AC_BK
AC_BE
AC_VI
AC_VO
AC_NUMCATEGORIES
                     {
     AC_BK = 0,
     AC_BE = 1,
     AC_VI = 2,
     AC_VO = 3,
     AC_NUMCATEGORIES
 };
AckPolicy
enum inet::ieee80211::AckPolicy
Enum generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:92 by opp_msgtool.
//
// Ack policy values for the 802.11 QoS control field
//
enum AckPolicy
{
    NORMAL_ACK = 0;
    NO_ACK = 1;
    NO_EXPLICIT_ACK = 2;
    BLOCK_ACK = 3;
}
Enumerator
NORMAL_ACK
NO_ACK
NO_EXPLICIT_ACK
BLOCK_ACK
                {
     NORMAL_ACK = 0,
     NO_ACK = 1,
     NO_EXPLICIT_ACK = 2,
     BLOCK_ACK = 3
 };
Ieee80211BssType
enum inet::ieee80211::Ieee80211BssType
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:52 by opp_msgtool.
enum Ieee80211BssType
{
    BSSTYPE_ANY = 0;
    BSSTYPE_INFRASTRUCTURE = 1;
    BSSTYPE_INDEPENDENT = 2;
}
Enumerator
BSSTYPE_ANY
BSSTYPE_INFRASTRUCTURE
BSSTYPE_INDEPENDENT
                       {
     BSSTYPE_ANY = 0,
     BSSTYPE_INFRASTRUCTURE = 1,
     BSSTYPE_INDEPENDENT = 2
 };
Ieee80211FrameType
enum inet::ieee80211::Ieee80211FrameType
Enum generated from inet/linklayer/ieee80211/mac/Ieee80211Frame.msg:56 by opp_msgtool.
//
// 802.11 frame type constants (type+subtype), for the "type" field of
// Ieee80211FrameControl
//
enum Ieee80211FrameType
{
    // management:
    ST_ASSOCIATIONREQUEST = 0x00;
    ST_ASSOCIATIONRESPONSE = 0x01;
    ST_REASSOCIATIONREQUEST = 0x02;
    ST_REASSOCIATIONRESPONSE = 0x03;
    ST_PROBEREQUEST = 0x04;
    ST_PROBERESPONSE = 0x05;
    ST_BEACON = 0x08;
    ST_ATIM = 0x09;
    ST_DISASSOCIATION = 0x0a;
    ST_AUTHENTICATION = 0x0b;
    ST_DEAUTHENTICATION = 0x0c;
    ST_ACTION = 0x0d;
    ST_NOACKACTION = 0x0e;
    // control (CFEND/CFEND_CFACK omitted):
    ST_PSPOLL = 0x1a;
    ST_RTS = 0x1b;
    ST_CTS = 0x1c;
    ST_ACK = 0x1d;
    ST_BLOCKACK_REQ = 0x18;
    ST_BLOCKACK = 0x19;
    // data (CFPOLL/CFACK subtypes omitted):
    ST_DATA = 0x20;
    ST_DATA_WITH_QOS = 0x28;
    //Feedback frame for multicast tramsmission
    ST_LBMS_REQUEST = 0x30;
    ST_LBMS_REPORT = 0x31;
}
Enumerator
ST_ASSOCIATIONREQUEST
ST_ASSOCIATIONRESPONSE
ST_REASSOCIATIONREQUEST
ST_REASSOCIATIONRESPONSE
ST_PROBEREQUEST
ST_PROBERESPONSE
ST_BEACON
ST_ATIM
ST_DISASSOCIATION
ST_AUTHENTICATION
ST_DEAUTHENTICATION
ST_ACTION
ST_NOACKACTION
ST_PSPOLL
ST_RTS
ST_CTS
ST_ACK
ST_BLOCKACK_REQ
ST_BLOCKACK
ST_DATA
ST_DATA_WITH_QOS
ST_LBMS_REQUEST
ST_LBMS_REPORT
{
     ST_ASSOCIATIONREQUEST = 0x00,
     ST_ASSOCIATIONRESPONSE = 0x01,
     ST_REASSOCIATIONREQUEST = 0x02,
     ST_REASSOCIATIONRESPONSE = 0x03,
     ST_PROBEREQUEST = 0x04,
     ST_PROBERESPONSE = 0x05,
     ST_BEACON = 0x08,
     ST_ATIM = 0x09,
     ST_DISASSOCIATION = 0x0a,
     ST_AUTHENTICATION = 0x0b,
     ST_DEAUTHENTICATION = 0x0c,
     ST_ACTION = 0x0d,
     ST_NOACKACTION = 0x0e,
     ST_PSPOLL = 0x1a,
     ST_RTS = 0x1b,
     ST_CTS = 0x1c,
     ST_ACK = 0x1d,
     ST_BLOCKACK_REQ = 0x18,
     ST_BLOCKACK = 0x19,
     ST_DATA = 0x20,
     ST_DATA_WITH_QOS = 0x28,
     ST_LBMS_REQUEST = 0x30,
     ST_LBMS_REPORT = 0x31
 };
Ieee80211HwmpCode
enum inet::ieee80211::Ieee80211HwmpCode
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:104 by opp_msgtool.
enum Ieee80211HwmpCode
{
    IE11S_GANN = 125;
    IE11S_RANN = 126;
    IE11S_PREQ = 130;
    IE11S_PREP = 131;
    IE11S_PERR = 132;
}
Enumerator
IE11S_GANN
IE11S_RANN
IE11S_PREQ
IE11S_PREP
IE11S_PERR
{
     IE11S_GANN = 125,
     IE11S_RANN = 126,
     IE11S_PREQ = 130,
     IE11S_PREP = 131,
     IE11S_PERR = 132
 };
Ieee80211PrimConfirmCode
enum inet::ieee80211::Ieee80211PrimConfirmCode
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:41 by opp_msgtool.
//
// IEEE 802.11 confirm codes, sent by the management entity to the agent,
// in response to the agents's requests.
// These constants should be set as message kind on the messages.
//
// @see ~Ieee80211PrimRequestCode, ~Ieee80211MgmtSta, ~Ieee80211AgentSta
//
enum Ieee80211PrimConfirmCode
{
    PR_SCAN_CONFIRM = 1;
    PR_AUTHENTICATE_CONFIRM = 2;
    PR_DEAUTHENTICATE_CONFIRM = 3;
    PR_ASSOCIATE_CONFIRM = 4;
    PR_REASSOCIATE_CONFIRM = 5;
    PR_DISASSOCIATE_CONFIRM = 6;
}
Enumerator
PR_SCAN_CONFIRM
PR_AUTHENTICATE_CONFIRM
PR_DEAUTHENTICATE_CONFIRM
PR_ASSOCIATE_CONFIRM
PR_REASSOCIATE_CONFIRM
PR_DISASSOCIATE_CONFIRM
{
     PR_SCAN_CONFIRM = 1,
     PR_AUTHENTICATE_CONFIRM = 2,
     PR_DEAUTHENTICATE_CONFIRM = 3,
     PR_ASSOCIATE_CONFIRM = 4,
     PR_REASSOCIATE_CONFIRM = 5,
     PR_DISASSOCIATE_CONFIRM = 6
 };
Ieee80211PrimRequestCode
enum inet::ieee80211::Ieee80211PrimRequestCode
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:23 by opp_msgtool.
//
// IEEE 802.11 command codes, sent by the agent to the management entity.
// These constants should be set as message kind on the messages.
//
// @see ~Ieee80211PrimConfirmCode, ~Ieee80211MgmtSta, ~Ieee80211AgentSta
//
enum Ieee80211PrimRequestCode
{
    PR_SCAN_REQUEST = 1;
    PR_AUTHENTICATE_REQUEST = 2;
    PR_DEAUTHENTICATE_REQUEST = 3;
    PR_ASSOCIATE_REQUEST = 4;
    PR_REASSOCIATE_REQUEST = 5;
    PR_DISASSOCIATE_REQUEST = 6;
}
Enumerator
PR_SCAN_REQUEST
PR_AUTHENTICATE_REQUEST
PR_DEAUTHENTICATE_REQUEST
PR_ASSOCIATE_REQUEST
PR_REASSOCIATE_REQUEST
PR_DISASSOCIATE_REQUEST
{
     PR_SCAN_REQUEST = 1,
     PR_AUTHENTICATE_REQUEST = 2,
     PR_DEAUTHENTICATE_REQUEST = 3,
     PR_ASSOCIATE_REQUEST = 4,
     PR_REASSOCIATE_REQUEST = 5,
     PR_DISASSOCIATE_REQUEST = 6
 };
Ieee80211PrimResultCode
enum inet::ieee80211::Ieee80211PrimResultCode
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211Primitives.msg:66 by opp_msgtool.
//
// Values for the resultCode field in confirm primitives, sent from
// the management entity to the agent.
//
// @see ~Ieee80211PrimConfirmCode, ~Ieee80211MgmtSta, ~Ieee80211AgentSta
//
enum Ieee80211PrimResultCode
{
    PRC_SUCCESS = 0;
    PRC_INVALID_PARAMETERS = 1;
    PRC_TIMEOUT = 2;
    PRC_TOO_MANY_SIMULTANEOUS_REQUESTS = 3;
    PRC_REFUSED = 4;
}
Enumerator
PRC_SUCCESS
PRC_INVALID_PARAMETERS
PRC_TIMEOUT
PRC_TOO_MANY_SIMULTANEOUS_REQUESTS
PRC_REFUSED
{
     PRC_SUCCESS = 0,
     PRC_INVALID_PARAMETERS = 1,
     PRC_TIMEOUT = 2,
     PRC_TOO_MANY_SIMULTANEOUS_REQUESTS = 3,
     PRC_REFUSED = 4
 };
Ieee80211ReasonCode
enum inet::ieee80211::Ieee80211ReasonCode
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:53 by opp_msgtool.
//
// 802.11 reason code; values correspond to the standard.
//
enum Ieee80211ReasonCode
{
    RC_UNSPECIFIED = 1;
    RC_PREV_AUTH_EXPIRED = 2;
    RC_DEAUTH_MS_LEAVING = 3;
    RC_DISASS_INACTIVITY = 4;
    RC_DISASS_TOO_MANY_MS = 5;
    RC_NONAUTH_CLASS2 = 6;
    RC_NONASS_CLASS3 = 7;
    RC_DIASS_MS_LEAVING = 8;
    RC_NONAUTH_ASS_REQUEST = 9;
    RC_MESH_PEERING_CANCELLED = 52;
    RC_MESH_MAX_PEERS = 53;
    RC_MESH_CONFIGURATION_POLICY_VIOLATION = 54;
    RC_MESH_CLOSE_RCVD = 55;
    RC_MESH_MAX_RETRIES = 56;
    RC_MESH_CONFIRM_TIMEOUT = 57;
    RC_MESH_INVALID_GTK = 58;
    RC_MESH_INCONSISTENT_PARAMETERS = 59;
    RC_MESH_INVALID_SECURITY_CAPABILITY = 60;
    RC_MESH_PATH_ERROR_NO_PROXY_INFORMATION = 61;
    RC_MESH_PATH_ERROR_NO_FORWARDING_INFORMATION = 60;
    RC_MESH_PATH_ERROR_DESTINATION_UNREACHABLE = 63;
    RC_MAC_ADDRESS_ALREADY_EXISTS_IN_MBSS = 64;
    RC_MESH_CHANNEL_SWITCH_REGULATORY_REQUIREMENTS = 65;
    RC_MESH_CHANNEL_SWITCH_UNSPECIFIED = 66;
}
Enumerator
RC_UNSPECIFIED
RC_PREV_AUTH_EXPIRED
RC_DEAUTH_MS_LEAVING
RC_DISASS_INACTIVITY
RC_DISASS_TOO_MANY_MS
RC_NONAUTH_CLASS2
RC_NONASS_CLASS3
RC_DIASS_MS_LEAVING
RC_NONAUTH_ASS_REQUEST
RC_MESH_PEERING_CANCELLED
RC_MESH_MAX_PEERS
RC_MESH_CONFIGURATION_POLICY_VIOLATION
RC_MESH_CLOSE_RCVD
RC_MESH_MAX_RETRIES
RC_MESH_CONFIRM_TIMEOUT
RC_MESH_INVALID_GTK
RC_MESH_INCONSISTENT_PARAMETERS
RC_MESH_INVALID_SECURITY_CAPABILITY
RC_MESH_PATH_ERROR_NO_PROXY_INFORMATION
RC_MESH_PATH_ERROR_NO_FORWARDING_INFORMATION
RC_MESH_PATH_ERROR_DESTINATION_UNREACHABLE
RC_MAC_ADDRESS_ALREADY_EXISTS_IN_MBSS
RC_MESH_CHANNEL_SWITCH_REGULATORY_REQUIREMENTS
RC_MESH_CHANNEL_SWITCH_UNSPECIFIED
{
     RC_UNSPECIFIED = 1,
     RC_PREV_AUTH_EXPIRED = 2,
     RC_DEAUTH_MS_LEAVING = 3,
     RC_DISASS_INACTIVITY = 4,
     RC_DISASS_TOO_MANY_MS = 5,
     RC_NONAUTH_CLASS2 = 6,
     RC_NONASS_CLASS3 = 7,
     RC_DIASS_MS_LEAVING = 8,
     RC_NONAUTH_ASS_REQUEST = 9,
     RC_MESH_PEERING_CANCELLED = 52,
     RC_MESH_MAX_PEERS = 53,
     RC_MESH_CONFIGURATION_POLICY_VIOLATION = 54,
     RC_MESH_CLOSE_RCVD = 55,
     RC_MESH_MAX_RETRIES = 56,
     RC_MESH_CONFIRM_TIMEOUT = 57,
     RC_MESH_INVALID_GTK = 58,
     RC_MESH_INCONSISTENT_PARAMETERS = 59,
     RC_MESH_INVALID_SECURITY_CAPABILITY = 60,
     RC_MESH_PATH_ERROR_NO_PROXY_INFORMATION = 61,
     RC_MESH_PATH_ERROR_NO_FORWARDING_INFORMATION = 60,
     RC_MESH_PATH_ERROR_DESTINATION_UNREACHABLE = 63,
     RC_MAC_ADDRESS_ALREADY_EXISTS_IN_MBSS = 64,
     RC_MESH_CHANNEL_SWITCH_REGULATORY_REQUIREMENTS = 65,
     RC_MESH_CHANNEL_SWITCH_UNSPECIFIED = 66
 };
Ieee80211StatusCode
enum inet::ieee80211::Ieee80211StatusCode
Enum generated from inet/linklayer/ieee80211/mgmt/Ieee80211MgmtFrame.msg:85 by opp_msgtool.
//
// 802.11 status code; values correspond to the standard.
//
enum Ieee80211StatusCode
{
    SC_SUCCESSFUL = 0;
    SC_UNSPECIFIED = 1;
    SC_UNSUP_CAP = 10;
    SC_REASS_DENIED = 11;
    SC_ASS_DENIED_UNKNOWN = 12;
    SC_AUTH_ALG0_UNSUP = 13;
    SC_AUTH_OUT_OF_SEQ = 14;
    SC_AUTH_CHALLENGE_FAIL = 15;
    SC_AUTH_TIMEOUT = 16;
    SC_ASS_TOO_MANY_MS = 17;
    SC_DATARATE_UNSUP = 18;
    SC_AUTH_REJECT_ANTI_CLOGING = 76;
    SC_AUTH_REJECT_FINITE_CYC_GROUP_UNS = 77;
    SC_TBTT_REQUEST = 78;
}
Enumerator
SC_SUCCESSFUL
SC_UNSPECIFIED
SC_UNSUP_CAP
SC_REASS_DENIED
SC_ASS_DENIED_UNKNOWN
SC_AUTH_ALG0_UNSUP
SC_AUTH_OUT_OF_SEQ
SC_AUTH_CHALLENGE_FAIL
SC_AUTH_TIMEOUT
SC_ASS_TOO_MANY_MS
SC_DATARATE_UNSUP
SC_AUTH_REJECT_ANTI_CLOGING
SC_AUTH_REJECT_FINITE_CYC_GROUP_UNS
SC_TBTT_REQUEST
{
     SC_SUCCESSFUL = 0,
     SC_UNSPECIFIED = 1,
     SC_UNSUP_CAP = 10,
     SC_REASS_DENIED = 11,
     SC_ASS_DENIED_UNKNOWN = 12,
     SC_AUTH_ALG0_UNSUP = 13,
     SC_AUTH_OUT_OF_SEQ = 14,
     SC_AUTH_CHALLENGE_FAIL = 15,
     SC_AUTH_TIMEOUT = 16,
     SC_ASS_TOO_MANY_MS = 17,
     SC_DATARATE_UNSUP = 18,
     SC_AUTH_REJECT_ANTI_CLOGING = 76,
     SC_AUTH_REJECT_FINITE_CYC_GROUP_UNS = 77,
     SC_TBTT_REQUEST = 78
 };
LlcProtocolId
enum inet::ieee80211::LlcProtocolId
Enum generated from inet/linklayer/ieee80211/llc/LlcProtocolTag.msg:25 by opp_msgtool.
enum LlcProtocolId
{
    LPD = 0; // IEEE 802.2 LLC header (with SNAP)
    EPD = 1; // plain EtherType header
}
Enumerator
LPD
EPD
                    {
     LPD = 0,
     EPD = 1
 };
Function Documentation
__doPacking() [1/3]
void INET_API inet::ieee80211::__doPacking (omnetpp::cCommBuffer * b, const Ieee80211CapabilityInformation & a)
Referenced by doParsimPacking().
__doPacking() [2/3]
void INET_API inet::ieee80211::__doPacking (omnetpp::cCommBuffer * b, const Ieee80211HandoverParameters & a)
__doPacking() [3/3]
void INET_API inet::ieee80211::__doPacking (omnetpp::cCommBuffer * b, const Ieee80211SupportedRatesElement & a)
__doUnpacking() [1/3]
void INET_API inet::ieee80211::__doUnpacking (omnetpp::cCommBuffer * b, Ieee80211CapabilityInformation & a)
Referenced by doParsimUnpacking().
__doUnpacking() [2/3]
void INET_API inet::ieee80211::__doUnpacking (omnetpp::cCommBuffer * b, Ieee80211HandoverParameters & a)
__doUnpacking() [3/3]
void INET_API inet::ieee80211::__doUnpacking (omnetpp::cCommBuffer * b, Ieee80211SupportedRatesElement & a)
Define_Module() [1/53]
inet::ieee80211::Define_Module (AarfRateControl)
Define_Module() [2/53]
inet::ieee80211::Define_Module (AckHandler)
Define_Module() [3/53]
inet::ieee80211::Define_Module (BasicFragmentationPolicy)
Define_Module() [4/53]
inet::ieee80211::Define_Module (BasicMpduAggregationPolicy)
Define_Module() [5/53]
inet::ieee80211::Define_Module (BasicMsduAggregationPolicy)
Define_Module() [6/53]
inet::ieee80211::Define_Module (Contention)
Define_Module() [7/53]
inet::ieee80211::Define_Module (CtsPolicy)
Define_Module() [8/53]
inet::ieee80211::Define_Module (Dcaf)
Define_Module() [9/53]
inet::ieee80211::Define_Module (Dcf)
Define_Module() [10/53]
inet::ieee80211::Define_Module (Ds)
Define_Module() [11/53]
inet::ieee80211::Define_Module (Edca)
Define_Module() [12/53]
inet::ieee80211::Define_Module (EdcaCollisionController)
Define_Module() [13/53]
inet::ieee80211::Define_Module (Edcaf)
Define_Module() [14/53]
inet::ieee80211::Define_Module (Hcca)
Define_Module() [15/53]
inet::ieee80211::Define_Module (Hcf)
Define_Module() [16/53]
inet::ieee80211::Define_Module (Ieee80211AgentSta)
Define_Module() [17/53]
inet::ieee80211::Define_Module (Ieee80211LlcEpd)
Define_Module() [18/53]
inet::ieee80211::Define_Module (Ieee80211LlcLpd)
Define_Module() [19/53]
inet::ieee80211::Define_Module (Ieee80211Mac)
Define_Module() [20/53]
inet::ieee80211::Define_Module (Ieee80211MgmtAdhoc)
Define_Module() [21/53]
inet::ieee80211::Define_Module (Ieee80211MgmtAp)
Define_Module() [22/53]
inet::ieee80211::Define_Module (Ieee80211MgmtApSimplified)
Define_Module() [23/53]
inet::ieee80211::Define_Module (Ieee80211MgmtSta)
Define_Module() [24/53]
inet::ieee80211::Define_Module (Ieee80211MgmtStaSimplified)
Define_Module() [25/53]
inet::ieee80211::Define_Module (Ieee80211Mib)
Define_Module() [26/53]
inet::ieee80211::Define_Module (Ieee80211Portal)
Define_Module() [27/53]
inet::ieee80211::Define_Module (InProgressFrames)
Define_Module() [28/53]
inet::ieee80211::Define_Module (Mcf)
Define_Module() [29/53]
inet::ieee80211::Define_Module (NonQosRecoveryProcedure)
Define_Module() [30/53]
inet::ieee80211::Define_Module (OnoeRateControl)
Define_Module() [31/53]
inet::ieee80211::Define_Module (OriginatorAckPolicy)
Define_Module() [32/53]
inet::ieee80211::Define_Module (OriginatorBlockAckAgreementPolicy)
Define_Module() [33/53]
inet::ieee80211::Define_Module (OriginatorMacDataService)
Define_Module() [34/53]
inet::ieee80211::Define_Module (OriginatorProtectionMechanism)
Define_Module() [35/53]
inet::ieee80211::Define_Module (OriginatorQosAckPolicy)
Define_Module() [36/53]
inet::ieee80211::Define_Module (OriginatorQosMacDataService)
Define_Module() [37/53]
inet::ieee80211::Define_Module (Pcf)
Define_Module() [38/53]
inet::ieee80211::Define_Module (QosAckHandler)
Define_Module() [39/53]
inet::ieee80211::Define_Module (QosCtsPolicy)
Define_Module() [40/53]
inet::ieee80211::Define_Module (QosRateSelection)
Define_Module() [41/53]
inet::ieee80211::Define_Module (QosRecoveryProcedure)
Define_Module() [42/53]
inet::ieee80211::Define_Module (QosRtsPolicy)
Define_Module() [43/53]
inet::ieee80211::Define_Module (RateSelection)
Define_Module() [44/53]
inet::ieee80211::Define_Module (RecipientAckPolicy)
Define_Module() [45/53]
inet::ieee80211::Define_Module (RecipientBlockAckAgreementPolicy)
Define_Module() [46/53]
inet::ieee80211::Define_Module (RecipientMacDataService)
Define_Module() [47/53]
inet::ieee80211::Define_Module (RecipientQosAckPolicy)
Define_Module() [48/53]
inet::ieee80211::Define_Module (RecipientQosMacDataService)
Define_Module() [49/53]
inet::ieee80211::Define_Module (RtsPolicy)
Define_Module() [50/53]
inet::ieee80211::Define_Module (Rx)
Define_Module() [51/53]
inet::ieee80211::Define_Module (SingleProtectionMechanism)
Define_Module() [52/53]
inet::ieee80211::Define_Module (Tx)
Define_Module() [53/53]
inet::ieee80211::Define_Module (TxopProcedure)
doParsimPacking() [1/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const AckPolicy & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [2/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211AckFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [3/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ActionFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [4/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211AddbaRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [5/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211AddbaResponse & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [6/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211AssociationRequestFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [7/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211AssociationResponseFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [8/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211AuthenticationFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [9/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211BasicBlockAck & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [10/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211BasicBlockAckReq & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [11/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211BeaconFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [12/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211BlockAck & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [13/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211BlockAckReq & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [14/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211BssType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [15/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211CapabilityInformation & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [16/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211CompressedBlockAck & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [17/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211CompressedBlockAckReq & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [18/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211CtsFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [19/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211DataHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [20/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211DataOrMgmtHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [21/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211DeauthenticationFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [22/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Delba & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [23/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211DisassociationFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [24/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211FrameType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [25/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211HandoverParameters & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [26/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211HwmpCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [27/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MacHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [28/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MacTrailer & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [29/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MgmtFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [30/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MgmtHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [31/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MpduSubframeHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [32/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MsduSubframeHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [33/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MultiTidBlockAck & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [34/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211MultiTidBlockAckReq & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [35/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211OneAddressHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [36/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_AssociateConfirm & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [37/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_AssociateRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [38/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_AuthenticateConfirm & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [39/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_AuthenticateRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [40/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_BssDescription & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [41/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_DeauthenticateRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [42/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_DisassociateRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [43/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_ReassociateConfirm & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [44/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_ReassociateRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [45/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_ScanConfirm & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [46/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211Prim_ScanRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [47/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PrimConfirm & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [48/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PrimConfirmCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [49/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PrimRequest & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [50/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PrimRequestCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [51/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PrimResultCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [52/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ProbeRequestFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [53/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ProbeResponseFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [54/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ReasonCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [55/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ReassociationRequestFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [56/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ReassociationResponseFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [57/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211RtsFrame & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [58/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211StatusCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [59/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211SupportedRatesElement & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [60/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211TwoAddressHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [61/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const LlcProtocolId & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [62/62]
void inet::ieee80211::doParsimPacking (omnetpp::cCommBuffer * b, const LlcProtocolTag & obj) inline
 {obj.parsimPack(b);}
doParsimUnpacking() [1/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, AckPolicy & e) inline
 { int n; b->unpack(n); e = static_cast<AckPolicy>(n); }
doParsimUnpacking() [2/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211AckFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [3/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ActionFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [4/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211AddbaRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [5/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211AddbaResponse & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [6/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211AssociationRequestFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [7/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211AssociationResponseFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [8/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211AuthenticationFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [9/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211BasicBlockAck & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [10/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211BasicBlockAckReq & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [11/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211BeaconFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [12/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211BlockAck & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [13/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211BlockAckReq & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [14/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211BssType & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211BssType>(n); }
doParsimUnpacking() [15/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211CapabilityInformation & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [16/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211CompressedBlockAck & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [17/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211CompressedBlockAckReq & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [18/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211CtsFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [19/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211DataHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [20/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211DataOrMgmtHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [21/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211DeauthenticationFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [22/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Delba & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [23/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211DisassociationFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [24/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211FrameType & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211FrameType>(n); }
doParsimUnpacking() [25/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211HandoverParameters & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [26/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211HwmpCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211HwmpCode>(n); }
doParsimUnpacking() [27/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MacHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [28/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MacTrailer & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [29/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MgmtFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [30/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MgmtHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [31/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MpduSubframeHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [32/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MsduSubframeHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [33/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MultiTidBlockAck & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [34/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211MultiTidBlockAckReq & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [35/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211OneAddressHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [36/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_AssociateConfirm & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [37/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_AssociateRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [38/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_AuthenticateConfirm & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [39/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_AuthenticateRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [40/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_BssDescription & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [41/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_DeauthenticateRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [42/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_DisassociateRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [43/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_ReassociateConfirm & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [44/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_ReassociateRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [45/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_ScanConfirm & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [46/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211Prim_ScanRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [47/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PrimConfirm & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [48/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PrimConfirmCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211PrimConfirmCode>(n); }
doParsimUnpacking() [49/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PrimRequest & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [50/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PrimRequestCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211PrimRequestCode>(n); }
doParsimUnpacking() [51/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PrimResultCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211PrimResultCode>(n); }
doParsimUnpacking() [52/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ProbeRequestFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [53/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ProbeResponseFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [54/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ReasonCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211ReasonCode>(n); }
doParsimUnpacking() [55/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ReassociationRequestFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [56/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ReassociationResponseFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [57/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211RtsFrame & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [58/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211StatusCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ieee80211StatusCode>(n); }
doParsimUnpacking() [59/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211SupportedRatesElement & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [60/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211TwoAddressHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [61/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, LlcProtocolId & e) inline
 { int n; b->unpack(n); e = static_cast<LlcProtocolId>(n); }
doParsimUnpacking() [62/62]
void inet::ieee80211::doParsimUnpacking (omnetpp::cCommBuffer * b, LlcProtocolTag & obj) inline
 {obj.parsimUnpack(b);}
fallback() [1/2]
double inet::ieee80211::fallback (double a, double b) inline
 { return a != -1 ? a : b; }
Referenced by inet::ieee80211::Edcaf::calculateTimingParameters().
fallback() [2/2]
simtime_t inet::ieee80211::fallback (simtime_t a, simtime_t b) inline
 { return a != -1 ? a : b; }
operator<<() [1/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const AckHandler::Status & status)
 { return os << AckHandler::getStatusString(status); }
operator<<() [2/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const Ieee80211MgmtSta::ApInfo & ap)
 {
     os << "AP addr=" << ap.address
        << " chan=" << ap.channel
        << " ssid=" << ap.ssid
         // TODO supportedRates
        << " beaconIntvl=" << ap.beaconInterval
        << " rxPower=" << ap.rxPower
        << " authSeqExpected=" << ap.authSeqExpected
        << " isAuthenticated=" << ap.isAuthenticated;
     return os;
 }
operator<<() [3/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const Ieee80211MgmtSta::AssociatedApInfo & assocAP)
 {
     os << "AP addr=" << assocAP.address
        << " chan=" << assocAP.channel
        << " ssid=" << assocAP.ssid
        << " beaconIntvl=" << assocAP.beaconInterval
        << " receiveSeq=" << assocAP.receiveSequence
        << " rxPower=" << assocAP.rxPower;
     return os;
 }
operator<<() [4/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const Ieee80211MgmtSta::ScanningInfo & scanning)
 {
     os << "activeScan=" << scanning.activeScan
        << " probeDelay=" << scanning.probeDelay
        << " curChan=";
     if (scanning.channelList.empty())
         os << "<none>";
     else
         os << scanning.channelList[scanning.currentChannelIndex];
     os << " minChanTime=" << scanning.minChannelTime
        << " maxChanTime=" << scanning.maxChannelTime;
     os << " chanList={";
     for (size_t i = 0; i < scanning.channelList.size(); i++)
         os << (i == 0 ? "" : " ") << scanning.channelList[i];
     os << "}";
     return os;
 }
operator<<() [5/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const QosAckHandler::Status & status)
 { return os << QosAckHandler::getStatusString(status); }
operator<<() [6/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const RecipientBlockAckAgreement & agreement)
 {
     os << "originator address = " << agreement.blockAckRecord->getOriginatorAddress() << ", "
        << "tid = " << agreement.blockAckRecord->getTid() << ", "
        << "starting sequence number = " << agreement.startingSequenceNumber << ", "
        << "buffer size = " << agreement.bufferSize << ", "
        << "block ack timeout value = " << agreement.blockAckTimeoutValue;
     return os;
 }
operator<<() [7/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const SequenceControlField & field) inline
 { return os << field.getSequenceNumber() << ":" << (int)field.getFragmentNumber(); }
operator<<() [8/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const SequenceNumberCyclic & sequenceNumber) inline
 {
     os << sequenceNumber.get();
     return os;
 }
operator<<() [9/11]
template<typename K , typename V > std::ostream& inet::ieee80211::operator<< (std::ostream & os, const std::pair< K, V > & pair)
 { return os << "(" << pair.first << ", " << pair.second << ")"; }
operator<<() [10/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const std::pair< Tid, SequenceControlField > & p) inline
 { return os << p.first << "#" << p.second; }
operator<<() [11/11]
std::ostream& inet::ieee80211::operator<< (std::ostream & os, const Tid tid)
 { return os << (int)tid; }
printAccessCategory()
std::string inet::ieee80211::printAccessCategory (AccessCategory ac) inline
 {
     switch (ac) {
         case AC_BK: return "Background";
         case AC_BE: return "Best effort";
         case AC_VI: return "Video";
         case AC_VO: return "Voice";
         default: throw cRuntimeError("Unknown access category");
     }
 }
Referenced by inet::ieee80211::Hcf::channelGranted(), inet::ieee80211::EdcaCollisionController::expectedChannelAccess(), inet::ieee80211::Hcf::handleInternalCollision(), inet::ieee80211::Hcf::processUpperFrame(), and inet::ieee80211::Edcaf::refreshDisplay().
Register_Class() [1/8]
inet::ieee80211::Register_Class (BasicReassembly)
Register_Class() [2/8]
inet::ieee80211::Register_Class (Defragmentation)
Register_Class() [3/8]
inet::ieee80211::Register_Class (Fragmentation)
Register_Class() [4/8]
inet::ieee80211::Register_Class (Ieee80211MgmtAp::NotificationInfoSta)
Register_Class() [5/8]
inet::ieee80211::Register_Class (MpduAggregation)
Register_Class() [6/8]
inet::ieee80211::Register_Class (MpduDeaggregation)
Register_Class() [7/8]
inet::ieee80211::Register_Class (MsduAggregation)
Register_Class() [8/8]
inet::ieee80211::Register_Class (MsduDeaggregation)
Register_Enum()
inet::ieee80211::Register_Enum (Contention::State , (Contention::IDLE, Contention::DEFER, Contention::IFS_AND_BACKOFF))
Register_Packet_Classifier_Function() [1/2]
inet::ieee80211::Register_Packet_Classifier_Function (MgmtOverDataClassifier , classifyMgmtOverData)
Register_Packet_Classifier_Function() [2/2]
inet::ieee80211::Register_Packet_Classifier_Function (MgmtOverMulticastOverUnicastClassifier , classifyMgmtOverMulticastOverUnicast)
Register_Packet_Comparator_Function() [1/2]
inet::ieee80211::Register_Packet_Comparator_Function (MgmtOverDataComparator , compareMgmtOverData)
Register_Packet_Comparator_Function() [2/2]
inet::ieee80211::Register_Packet_Comparator_Function (MgmtOverMulticastOverUnicastComparator , compareMgmtOverMulticastOverUnicast)
Register_ResultFilter() [1/8]
inet::ieee80211::Register_ResultFilter ("frameSequenceDuration" , FrameSequenceDurationFilter)
Register_ResultFilter() [2/8]
inet::ieee80211::Register_ResultFilter ("frameSequenceNumPackets" , FrameSequenceNumPacketsFilter)
Register_ResultFilter() [3/8]
inet::ieee80211::Register_ResultFilter ("ieee80211Broadcast" , Ieee80211BroadcastFilter)
Register_ResultFilter() [4/8]
inet::ieee80211::Register_ResultFilter ("ieee80211Multicast" , Ieee80211MulticastFilter)
Register_ResultFilter() [5/8]
inet::ieee80211::Register_ResultFilter ("ieee80211NotRetry" , Ieee80211NotRetryFilter)
Register_ResultFilter() [6/8]
inet::ieee80211::Register_ResultFilter ("ieee80211Retry" , Ieee80211RetryFilter)
Register_ResultFilter() [7/8]
inet::ieee80211::Register_ResultFilter ("ieee80211Unicast" , Ieee80211UnicastFilter)
Register_ResultFilter() [8/8]
inet::ieee80211::Register_ResultFilter ("txopDuration" , TxopDurationFilter)
Register_Serializer() [1/30]
inet::ieee80211::Register_Serializer (Ieee80211AckFrame , Ieee80211MacHeaderSerializer)
Register_Serializer() [2/30]
inet::ieee80211::Register_Serializer (Ieee80211ActionFrame , Ieee80211MacHeaderSerializer)
Register_Serializer() [3/30]
inet::ieee80211::Register_Serializer (Ieee80211AddbaRequest , Ieee80211MacHeaderSerializer)
Register_Serializer() [4/30]
inet::ieee80211::Register_Serializer (Ieee80211AddbaResponse , Ieee80211MacHeaderSerializer)
Register_Serializer() [5/30]
inet::ieee80211::Register_Serializer (Ieee80211AssociationRequestFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [6/30]
inet::ieee80211::Register_Serializer (Ieee80211AssociationResponseFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [7/30]
inet::ieee80211::Register_Serializer (Ieee80211AuthenticationFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [8/30]
inet::ieee80211::Register_Serializer (Ieee80211BasicBlockAck , Ieee80211MacHeaderSerializer)
Register_Serializer() [9/30]
inet::ieee80211::Register_Serializer (Ieee80211BasicBlockAckReq , Ieee80211MacHeaderSerializer)
Register_Serializer() [10/30]
inet::ieee80211::Register_Serializer (Ieee80211BeaconFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [11/30]
inet::ieee80211::Register_Serializer (Ieee80211CompressedBlockAck , Ieee80211MacHeaderSerializer)
Register_Serializer() [12/30]
inet::ieee80211::Register_Serializer (Ieee80211CompressedBlockAckReq , Ieee80211MacHeaderSerializer)
Register_Serializer() [13/30]
inet::ieee80211::Register_Serializer (Ieee80211CtsFrame , Ieee80211MacHeaderSerializer)
Register_Serializer() [14/30]
inet::ieee80211::Register_Serializer (Ieee80211DataHeader , Ieee80211MacHeaderSerializer)
Register_Serializer() [15/30]
inet::ieee80211::Register_Serializer (Ieee80211DataOrMgmtHeader , Ieee80211MacHeaderSerializer)
Register_Serializer() [16/30]
inet::ieee80211::Register_Serializer (Ieee80211DeauthenticationFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [17/30]
inet::ieee80211::Register_Serializer (Ieee80211Delba , Ieee80211MacHeaderSerializer)
Register_Serializer() [18/30]
inet::ieee80211::Register_Serializer (Ieee80211DisassociationFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [19/30]
inet::ieee80211::Register_Serializer (Ieee80211MacHeader , Ieee80211MacHeaderSerializer)
Register_Serializer() [20/30]
inet::ieee80211::Register_Serializer (Ieee80211MacTrailer , Ieee80211MacTrailerSerializer)
Register_Serializer() [21/30]
inet::ieee80211::Register_Serializer (Ieee80211MgmtHeader , Ieee80211MacHeaderSerializer)
Register_Serializer() [22/30]
inet::ieee80211::Register_Serializer (Ieee80211MpduSubframeHeader , Ieee80211MpduSubframeHeaderSerializer)
Register_Serializer() [23/30]
inet::ieee80211::Register_Serializer (Ieee80211MsduSubframeHeader , Ieee80211MsduSubframeHeaderSerializer)
Register_Serializer() [24/30]
inet::ieee80211::Register_Serializer (Ieee80211MultiTidBlockAck , Ieee80211MacHeaderSerializer)
Register_Serializer() [25/30]
inet::ieee80211::Register_Serializer (Ieee80211MultiTidBlockAckReq , Ieee80211MacHeaderSerializer)
Register_Serializer() [26/30]
inet::ieee80211::Register_Serializer (Ieee80211ProbeRequestFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [27/30]
inet::ieee80211::Register_Serializer (Ieee80211ProbeResponseFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [28/30]
inet::ieee80211::Register_Serializer (Ieee80211ReassociationRequestFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [29/30]
inet::ieee80211::Register_Serializer (Ieee80211ReassociationResponseFrame , Ieee80211MgmtFrameSerializer)
Register_Serializer() [30/30]
inet::ieee80211::Register_Serializer (Ieee80211RtsFrame , Ieee80211MacHeaderSerializer)
Variable Documentation
DATAFRAME_HEADER_MINLENGTH
const b inet::ieee80211::DATAFRAME_HEADER_MINLENGTH = B(2 + 2 + 3 * 6 + 2)
LENGTH_A_MPDU_SUBFRAME_HEADER
const b inet::ieee80211::LENGTH_A_MPDU_SUBFRAME_HEADER = b(4 + 12 + 8 + 8)
LENGTH_A_MSDU_SUBFRAME_HEADER
const b inet::ieee80211::LENGTH_A_MSDU_SUBFRAME_HEADER = B(14)
Referenced by inet::ieee80211::BasicMsduAggregationPolicy::computeAggregateFrames(), and inet::ieee80211::BasicMsduAggregationPolicy::isEligible().
LENGTH_ACK
const b inet::ieee80211::LENGTH_ACK = b(112)
Referenced by inet::ieee80211::Dcaf::calculateTimingParameters(), inet::ieee80211::Edcaf::calculateTimingParameters(), inet::ieee80211::RecipientAckPolicy::computeAckDuration(), inet::ieee80211::RecipientQosAckPolicy::computeAckDuration(), inet::ieee80211::OriginatorProtectionMechanism::computeDataFrameDurationField(), inet::ieee80211::SingleProtectionMechanism::computeDataOrMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeMgmtFrameDurationField(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), and inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField().
LENGTH_ADDBAREQ
const b inet::ieee80211::LENGTH_ADDBAREQ = LENGTH_MGMT + B(9)
LENGTH_ADDBARESP
const b inet::ieee80211::LENGTH_ADDBARESP = LENGTH_MGMT + B(9)
LENGTH_BASIC_BLOCKACK
const b inet::ieee80211::LENGTH_BASIC_BLOCKACK = B(16 + 2 + (2 + 128) + 4)
Referenced by inet::ieee80211::RecipientQosAckPolicy::computeBasicBlockAckDuration(), and inet::ieee80211::SingleProtectionMechanism::computeBlockAckReqDurationField().
LENGTH_CTS
const b inet::ieee80211::LENGTH_CTS = b(112)
Referenced by inet::ieee80211::QosCtsPolicy::computeCtsDuration(), inet::ieee80211::CtsPolicy::computeCtsDuration(), inet::ieee80211::OriginatorProtectionMechanism::computeRtsDurationField(), and inet::ieee80211::SingleProtectionMechanism::computeRtsDurationField().
LENGTH_DELBA
const b inet::ieee80211::LENGTH_DELBA = LENGTH_MGMT + B(6)
LENGTH_MGMT
const b inet::ieee80211::LENGTH_MGMT = B(28)
LENGTH_RTS
const b inet::ieee80211::LENGTH_RTS = b(160)
MAX_NUM_FRAGMENTS
const short int inet::ieee80211::MAX_NUM_FRAGMENTS = 16
Referenced by inet::ieee80211::BasicReassembly::addFragment(), and inet::ieee80211::BasicFragmentationPolicy::computeFragmentSizes().
QOSCONTROL_PART_LENGTH
const b inet::ieee80211::QOSCONTROL_PART_LENGTH = b(2 * 8)
Referenced by inet::ieee80211::MsduAggregation::aggregateFrames(), inet::ieee80211::MsduDeaggregation::deaggregateFrame(), and inet::ieee80211::Ieee80211Mac::encapsulate().