INET Framework for OMNeT++/OMNEST: inet::sctp Namespace Reference
inet::sctp Namespace Reference
Classes
struct abort_chunk
struct add_ip_parameter
struct add_streams_request_parameter
struct asconf_ack_chunk
struct asconf_chunk
struct auth_chunk
struct chunk
struct common_header
struct cookie_ack_chunk
struct cookie_echo_chunk
struct cookie_parameter
struct data_chunk
struct data_vector
struct error_cause
struct error_cause_with_int
struct error_chunk
struct forward_tsn_chunk
struct forward_tsn_streams
struct forward_tsn_supported_parameter
struct heartbeat_ack_chunk
struct heartbeat_chunk
struct heartbeat_info
struct HighSpeedCwndAdjustmentEntry
struct hmac_algo
struct incoming_reset_request_parameter
struct init_ack_chunk
struct init_chunk
struct init_cookie_parameter
struct init_ipv4_address_parameter
struct init_ipv6_address_parameter
class NatMessage
Class generated from inet/transportlayer/sctp/SctpHeader.msg:357 by opp_msgtool.
struct nr_sack_chunk
struct outgoing_reset_request_parameter
struct pktdrop_chunk
struct random_parameter
struct sack_chunk
struct sack_duptsn
struct sack_gap
class Sctp
Implements the SCTP protocol.
class SctpAbortChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:186 by opp_msgtool.
class SctpAddIPParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:318 by opp_msgtool.
class SctpAddStreamsRequestParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:279 by opp_msgtool.
class SctpAlg
class SctpAlgorithm
Abstract base class for SCTP algorithms which encapsulate all behaviour during data transfer state: flavour of congestion control, fast retransmit/recovery, selective acknowledgement etc.
class SctpAlgStateVariables
State variables for SctpAlg.
class SctpAsconfAckChunk
class SctpAsconfAckChunk_Base
Class generated from inet/transportlayer/sctp/SctpHeader.msg:311 by opp_msgtool.
class SctpAsconfChunk
class SctpAsconfChunk_Base
Class generated from inet/transportlayer/sctp/SctpHeader.msg:302 by opp_msgtool.
class SctpAssociation
class SctpAuthenticationChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:294 by opp_msgtool.
class SctpChecksum
Calculates checksum.
class SctpChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:33 by opp_msgtool.
class SctpCookie
Class generated from inet/transportlayer/sctp/SctpHeader.msg:100 by opp_msgtool.
class SctpCookieAckChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:110 by opp_msgtool.
class SctpCookieEchoChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:93 by opp_msgtool.
class SctpCrcInsertion
class SctpDataChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:135 by opp_msgtool.
class SctpDataMsg
Class generated from inet/transportlayer/sctp/SctpHeader.msg:114 by opp_msgtool.
class SctpDataVariables
class SctpDeleteIPParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:324 by opp_msgtool.
class SctpErrorCauseParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:341 by opp_msgtool.
class SctpErrorChunk
class SctpErrorChunk_Base
Class generated from inet/transportlayer/sctp/SctpHeader.msg:220 by opp_msgtool.
class SctpForwardTsnChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:154 by opp_msgtool.
class SctpGapList
class SctpHeader
Represents an SCTP Message.
class SctpHeader_Base
Class generated from inet/transportlayer/sctp/SctpHeader.msg:17 by opp_msgtool.
class SctpHeaderSerializer
Converts between SCTPMessage and binary (network byte order) SCTP header.
class SctpHeartbeatAckChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:199 by opp_msgtool.
class SctpHeartbeatChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:192 by opp_msgtool.
class SctpIncomingSsnResetRequestParameter
class SctpIncomingSsnResetRequestParameter_Base
Class generated from inet/transportlayer/sctp/SctpHeader.msg:259 by opp_msgtool.
class SctpInitAckChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:67 by opp_msgtool.
class SctpInitChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:43 by opp_msgtool.
class SctpNatEntry
class SctpNatHook
class SctpNatTable
class SctpOutgoingSsnResetRequestParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:251 by opp_msgtool.
class SctpPacketDropChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:234 by opp_msgtool.
class SctpParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:228 by opp_msgtool.
class SctpPathVariables
class SctpProtocolDissector
class SctpProtocolPrinter
class SctpQueue
Abstract base class for SCTP receive queues.
class SctpReceiveStream
class SctpResetTimer
Class generated from inet/transportlayer/sctp/SctpHeader.msg:286 by opp_msgtool.
class SctpSackChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:161 by opp_msgtool.
class SctpSendStream
class SctpSetPrimaryIPParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:330 by opp_msgtool.
class SctpShutdownAckChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:211 by opp_msgtool.
class SctpShutdownChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:206 by opp_msgtool.
class SctpShutdownCompleteChunk
Class generated from inet/transportlayer/sctp/SctpHeader.msg:215 by opp_msgtool.
class SctpSimpleErrorCauseParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:347 by opp_msgtool.
class SctpSimpleGapList
class SctpSsnTsnResetRequestParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:266 by opp_msgtool.
class SctpStateVariables
class SctpStreamResetChunk
class SctpStreamResetChunk_Base
Class generated from inet/transportlayer/sctp/SctpHeader.msg:245 by opp_msgtool.
class SctpStreamResetResponseParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:271 by opp_msgtool.
class SctpSuccessIndication
Class generated from inet/transportlayer/sctp/SctpHeader.msg:352 by opp_msgtool.
class SctpSupportedExtensionsParameter
Class generated from inet/transportlayer/sctp/SctpHeader.msg:336 by opp_msgtool.
class SctpUdpHook
struct shutdown_ack_chunk
struct shutdown_chunk
struct shutdown_complete_chunk
struct ssn_tsn_reset_request_parameter
struct stream_reset_chunk
struct stream_reset_response_parameter
struct supported_address_types_parameter
struct supported_extensions_parameter
struct tlv
Typedefs
typedef std::vector< L3Address > AddressVector
Enumerations
enum SctpState {
SCTP_S_CLOSED = 0, SCTP_S_COOKIE_WAIT = FSM_Steady(1), SCTP_S_COOKIE_ECHOED = FSM_Steady(2), SCTP_S_ESTABLISHED = FSM_Steady(3),
SCTP_S_SHUTDOWN_PENDING = FSM_Steady(4), SCTP_S_SHUTDOWN_SENT = FSM_Steady(5), SCTP_S_SHUTDOWN_RECEIVED = FSM_Steady(6), SCTP_S_SHUTDOWN_ACK_SENT = FSM_Steady(7)
}
enum SctpEventCode {
SCTP_E_ASSOCIATE, SCTP_E_OPEN_PASSIVE, SCTP_E_ABORT, SCTP_E_SHUTDOWN,
SCTP_E_CLOSE, SCTP_E_SEND, SCTP_E_RCV_INIT, SCTP_E_RCV_ABORT,
SCTP_E_RCV_VALID_COOKIE_ECHO, SCTP_E_RCV_INIT_ACK, SCTP_E_RCV_COOKIE_ACK, SCTP_E_RCV_SHUTDOWN,
SCTP_E_RCV_SHUTDOWN_ACK, SCTP_E_RCV_SHUTDOWN_COMPLETE, SCTP_E_NO_MORE_OUTSTANDING, SCTP_E_TIMEOUT_INIT_TIMER,
SCTP_E_TIMEOUT_SHUTDOWN_TIMER, SCTP_E_TIMEOUT_RTX_TIMER, SCTP_E_TIMEOUT_HEARTBEAT_TIMER, SCTP_E_IGNORE,
SCTP_E_RECEIVE, SCTP_E_DUP_RECEIVED, SCTP_E_PRIMARY, SCTP_E_DELIVERED,
SCTP_E_QUEUE_MSGS_LIMIT, SCTP_E_QUEUE_BYTES_LIMIT, SCTP_E_SEND_QUEUE_LIMIT, SCTP_E_SEND_SHUTDOWN_ACK,
SCTP_E_STOP_SENDING, SCTP_E_STREAM_RESET, SCTP_E_RESET_ASSOC, SCTP_E_ADD_STREAMS,
SCTP_E_SEND_ASCONF, SCTP_E_SET_STREAM_PRIO, SCTP_E_ACCEPT, SCTP_E_SET_RTO_INFO,
SCTP_E_ACCEPT_SOCKET_ID
}
enum SCTPChunkTypes {
DATA = 0, INIT = 1, INIT_ACK = 2, SACK = 3,
HEARTBEAT = 4, HEARTBEAT_ACK = 5, ABORT = 6, SHUTDOWN = 7,
SHUTDOWN_ACK = 8, ERRORTYPE = 9, COOKIE_ECHO = 10, COOKIE_ACK = 11,
SHUTDOWN_COMPLETE = 14, AUTH = 15, NR_SACK = 16, ASCONF_ACK = 128,
PKTDROP = 129, RE_CONFIG = 130, FORWARD_TSN = 192, ASCONF = 193,
IFORWARD_TSN = 194
}
enum SctpPrMethods {
PR_NONE = 0, PR_TTL = 1, PR_RTX = 2, PR_PRIO = 3,
PR_STRRST = 4
}
enum SctpStreamResetConstants {
NOTHING_TO_DO = 0, PERFORMED = 1, DENIED = 2, WRONG_SSN = 3,
REQUEST_IN_PROGRESS = 4, NO_RESET = 5, DEFERRED = 6, RESET_OUTGOING = 7,
RESET_INCOMING = 8, RESET_BOTH = 9, SSN_TSN = 10, ADD_INCOMING = 11,
ADD_OUTGOING = 12, OUTGOING_RESET_REQUEST_PARAMETER = 13, INCOMING_RESET_REQUEST_PARAMETER = 14, SSN_TSN_RESET_REQUEST_PARAMETER = 15,
STREAM_RESET_RESPONSE_PARAMETER = 16, ADD_OUTGOING_STREAMS_REQUEST_PARAMETER = 17, ADD_INCOMING_STREAMS_REQUEST_PARAMETER = 18, ADD_BOTH = 19,
PERFORMED_WITH_OPTION = 20, PERFORMED_WITH_ADDOUT = 21
}
enum SctpAddIPCorrelatedTypes {
SET_PRIMARY_ADDRESS = 49156, ADAPTATION_LAYER_INDICATION = 49158, SUPPORTED_EXTENSIONS = 32776, ADD_IP_ADDRESS = 49153,
DELETE_IP_ADDRESS = 49154, ERROR_CAUSE_INDICATION = 49155, SUCCESS_INDICATION = 49157, ERROR_DELETE_LAST_IP_ADDRESS = 160,
ERROR_DELETE_SOURCE_ADDRESS = 162
}
enum SctpParameterTypes {
UNRECOGNIZED_PARAMETER = 8, SUPPORTED_ADDRESS_TYPES = 12, FORWARD_TSN_SUPPORTED_PARAMETER = 49152, RANDOM = 32770,
CHUNKS = 32771, HMAC_ALGO = 32772
}
enum SctpErrorCauses { INVALID_STREAM_IDENTIFIER = 1, NO_USER_DATA = 9, UNSUPPORTED_HMAC = 261, MISSING_NAT_ENTRY = 177 }
enum SctpCcModules { RFC4960 = 0 }
enum SctpStreamSchedulers {
ROUND_ROBIN = 0, ROUND_ROBIN_PACKET = 1, RANDOM_SCHEDULE = 2, RANDOM_SCHEDULE_PACKET = 3,
FAIR_BANDWITH = 4, FAIR_BANDWITH_PACKET = 5, PRIORITY = 6, FCFS = 7,
PATH_MANUAL = 8, PATH_MAP_TO_PATH = 9
}
Functions
Define_Module (Sctp)
Register_Class (SctpAlg)
double min (const double a, const double b)
Returns the minimum of a and b.
double max (const double a, const double b)
Returns the maximum of a and b.
Define_Module (SctpCrcInsertion)
std::ostream & operator<< (std::ostream &ostr, const SctpSimpleGapList &gapList)
std::ostream & operator<< (std::ostream &ostr, const SctpGapList &gapList)
Register_Class (SctpHeader)
Register_Class (SctpErrorChunk)
Register_Class (SctpStreamResetChunk)
Register_Class (SctpIncomingSsnResetRequestParameter)
Register_Class (SctpAsconfChunk)
Register_Class (SctpAsconfAckChunk)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpInitChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpInitChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpInitAckChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpInitAckChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpCookieEchoChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpCookieEchoChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpCookie &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpCookie &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpCookieAckChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpCookieAckChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpDataMsg &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpDataMsg &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpDataChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpDataChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpForwardTsnChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpForwardTsnChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpSackChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpSackChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpAbortChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpAbortChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpHeartbeatChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpHeartbeatChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpHeartbeatAckChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpHeartbeatAckChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpShutdownChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpShutdownChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpShutdownAckChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpShutdownAckChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpShutdownCompleteChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpShutdownCompleteChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpPacketDropChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpPacketDropChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpOutgoingSsnResetRequestParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpOutgoingSsnResetRequestParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpSsnTsnResetRequestParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpSsnTsnResetRequestParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpStreamResetResponseParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpStreamResetResponseParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpAddStreamsRequestParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpAddStreamsRequestParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpResetTimer &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpResetTimer &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpAuthenticationChunk &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpAuthenticationChunk &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpAddIPParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpAddIPParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpDeleteIPParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpDeleteIPParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpSetPrimaryIPParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpSetPrimaryIPParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpSupportedExtensionsParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpSupportedExtensionsParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpErrorCauseParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpErrorCauseParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpSimpleErrorCauseParameter &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpSimpleErrorCauseParameter &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const SctpSuccessIndication &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, SctpSuccessIndication &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const NatMessage &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, NatMessage &obj)
Register_Serializer (SctpHeader, SctpHeaderSerializer)
Define_Module (SctpNatHook)
Define_Module (SctpNatTable)
Register_Class (SctpQueue)
Define_Module (SctpUdpHook)
Variables
struct inet::sctp::common_header __PACKED__
Typedef Documentation
AddressVector
typedef std::vector<L3Address> inet::sctp::AddressVector
Enumeration Type Documentation
SctpAddIPCorrelatedTypes
enum inet::sctp::SctpAddIPCorrelatedTypes
Enumerator
SET_PRIMARY_ADDRESS
ADAPTATION_LAYER_INDICATION
SUPPORTED_EXTENSIONS
ADD_IP_ADDRESS
DELETE_IP_ADDRESS
ERROR_CAUSE_INDICATION
SUCCESS_INDICATION
ERROR_DELETE_LAST_IP_ADDRESS
ERROR_DELETE_SOURCE_ADDRESS
{
     SET_PRIMARY_ADDRESS          = 49156,
     ADAPTATION_LAYER_INDICATION  = 49158,
     SUPPORTED_EXTENSIONS         = 32776,
     ADD_IP_ADDRESS               = 49153,
     DELETE_IP_ADDRESS            = 49154,
     ERROR_CAUSE_INDICATION       = 49155,
     SUCCESS_INDICATION           = 49157,
     ERROR_DELETE_LAST_IP_ADDRESS = 160,
     ERROR_DELETE_SOURCE_ADDRESS  = 162
 };
SctpCcModules
enum inet::sctp::SctpCcModules
Enumerator
RFC4960
                    {
     RFC4960 = 0
 };
SCTPChunkTypes
enum inet::sctp::SCTPChunkTypes
Enumerator
DATA
INIT
INIT_ACK
SACK
HEARTBEAT
HEARTBEAT_ACK
ABORT
SHUTDOWN
SHUTDOWN_ACK
ERRORTYPE
COOKIE_ECHO
COOKIE_ACK
SHUTDOWN_COMPLETE
AUTH
NR_SACK
ASCONF_ACK
PKTDROP
RE_CONFIG
FORWARD_TSN
ASCONF
IFORWARD_TSN
                     {
     DATA              = 0,
     INIT              = 1,
     INIT_ACK          = 2,
     SACK              = 3,
     HEARTBEAT         = 4,
     HEARTBEAT_ACK     = 5,
     ABORT             = 6,
     SHUTDOWN          = 7,
     SHUTDOWN_ACK      = 8,
     ERRORTYPE         = 9,
     COOKIE_ECHO       = 10,
     COOKIE_ACK        = 11,
     SHUTDOWN_COMPLETE = 14,
     AUTH              = 15,
     NR_SACK           = 16,
     ASCONF_ACK        = 128,
     PKTDROP           = 129,
     RE_CONFIG         = 130,
     FORWARD_TSN       = 192,
     ASCONF            = 193,
     IFORWARD_TSN      = 194
 };
SctpErrorCauses
enum inet::sctp::SctpErrorCauses
Enumerator
INVALID_STREAM_IDENTIFIER
NO_USER_DATA
UNSUPPORTED_HMAC
MISSING_NAT_ENTRY
                      {
     INVALID_STREAM_IDENTIFIER = 1,
     NO_USER_DATA              = 9,
     UNSUPPORTED_HMAC          = 261,
     MISSING_NAT_ENTRY         = 177
 };
SctpEventCode
enum inet::sctp::SctpEventCode
Enumerator
SCTP_E_ASSOCIATE
SCTP_E_OPEN_PASSIVE
SCTP_E_ABORT
SCTP_E_SHUTDOWN
SCTP_E_CLOSE
SCTP_E_SEND
SCTP_E_RCV_INIT
SCTP_E_RCV_ABORT
SCTP_E_RCV_VALID_COOKIE_ECHO
SCTP_E_RCV_INIT_ACK
SCTP_E_RCV_COOKIE_ACK
SCTP_E_RCV_SHUTDOWN
SCTP_E_RCV_SHUTDOWN_ACK
SCTP_E_RCV_SHUTDOWN_COMPLETE
SCTP_E_NO_MORE_OUTSTANDING
SCTP_E_TIMEOUT_INIT_TIMER
SCTP_E_TIMEOUT_SHUTDOWN_TIMER
SCTP_E_TIMEOUT_RTX_TIMER
SCTP_E_TIMEOUT_HEARTBEAT_TIMER
SCTP_E_IGNORE
SCTP_E_RECEIVE
SCTP_E_DUP_RECEIVED
SCTP_E_PRIMARY
SCTP_E_DELIVERED
SCTP_E_QUEUE_MSGS_LIMIT
SCTP_E_QUEUE_BYTES_LIMIT
SCTP_E_SEND_QUEUE_LIMIT
SCTP_E_SEND_SHUTDOWN_ACK
SCTP_E_STOP_SENDING
SCTP_E_STREAM_RESET
SCTP_E_RESET_ASSOC
SCTP_E_ADD_STREAMS
SCTP_E_SEND_ASCONF
SCTP_E_SET_STREAM_PRIO
SCTP_E_ACCEPT
SCTP_E_SET_RTO_INFO
SCTP_E_ACCEPT_SOCKET_ID
                    {
     SCTP_E_ASSOCIATE,
     SCTP_E_OPEN_PASSIVE,
     SCTP_E_ABORT,
     SCTP_E_SHUTDOWN,
     SCTP_E_CLOSE,
     SCTP_E_SEND,
     SCTP_E_RCV_INIT,
     SCTP_E_RCV_ABORT,
     SCTP_E_RCV_VALID_COOKIE_ECHO,
     SCTP_E_RCV_INIT_ACK,
     SCTP_E_RCV_COOKIE_ACK,
     SCTP_E_RCV_SHUTDOWN,
     SCTP_E_RCV_SHUTDOWN_ACK,
     SCTP_E_RCV_SHUTDOWN_COMPLETE,
     SCTP_E_NO_MORE_OUTSTANDING,
     SCTP_E_TIMEOUT_INIT_TIMER,
     SCTP_E_TIMEOUT_SHUTDOWN_TIMER,
     SCTP_E_TIMEOUT_RTX_TIMER,
     SCTP_E_TIMEOUT_HEARTBEAT_TIMER,
     SCTP_E_IGNORE,
     SCTP_E_RECEIVE,
     SCTP_E_DUP_RECEIVED,
     SCTP_E_PRIMARY,
     SCTP_E_DELIVERED,
     SCTP_E_QUEUE_MSGS_LIMIT,
     SCTP_E_QUEUE_BYTES_LIMIT,
     SCTP_E_SEND_QUEUE_LIMIT,
     SCTP_E_SEND_SHUTDOWN_ACK,
     SCTP_E_STOP_SENDING,
     SCTP_E_STREAM_RESET,
     SCTP_E_RESET_ASSOC,
     SCTP_E_ADD_STREAMS,
     SCTP_E_SEND_ASCONF,
     SCTP_E_SET_STREAM_PRIO,
     SCTP_E_ACCEPT,
     SCTP_E_SET_RTO_INFO,
     SCTP_E_ACCEPT_SOCKET_ID
 };
SctpParameterTypes
enum inet::sctp::SctpParameterTypes
Enumerator
UNRECOGNIZED_PARAMETER
SUPPORTED_ADDRESS_TYPES
FORWARD_TSN_SUPPORTED_PARAMETER
RANDOM
CHUNKS
HMAC_ALGO
{
     UNRECOGNIZED_PARAMETER          = 8,
     SUPPORTED_ADDRESS_TYPES         = 12,
     FORWARD_TSN_SUPPORTED_PARAMETER = 49152,
     RANDOM                          = 32770,
     CHUNKS                          = 32771,
     HMAC_ALGO                       = 32772
 };
SctpPrMethods
enum inet::sctp::SctpPrMethods
Enumerator
PR_NONE
PR_TTL
PR_RTX
PR_PRIO
PR_STRRST
                    {
     PR_NONE   = 0,
     PR_TTL    = 1,
     PR_RTX    = 2,
     PR_PRIO   = 3,
     PR_STRRST = 4
 };
SctpState
enum inet::sctp::SctpState
Enumerator
SCTP_S_CLOSED
SCTP_S_COOKIE_WAIT
SCTP_S_COOKIE_ECHOED
SCTP_S_ESTABLISHED
SCTP_S_SHUTDOWN_PENDING
SCTP_S_SHUTDOWN_SENT
SCTP_S_SHUTDOWN_RECEIVED
SCTP_S_SHUTDOWN_ACK_SENT
                {
     SCTP_S_CLOSED            = 0,
     SCTP_S_COOKIE_WAIT       = FSM_Steady(1),
     SCTP_S_COOKIE_ECHOED     = FSM_Steady(2),
     SCTP_S_ESTABLISHED       = FSM_Steady(3),
     SCTP_S_SHUTDOWN_PENDING  = FSM_Steady(4),
     SCTP_S_SHUTDOWN_SENT     = FSM_Steady(5),
     SCTP_S_SHUTDOWN_RECEIVED = FSM_Steady(6),
     SCTP_S_SHUTDOWN_ACK_SENT = FSM_Steady(7)
 };
SctpStreamResetConstants
enum inet::sctp::SctpStreamResetConstants
Enumerator
NOTHING_TO_DO
PERFORMED
DENIED
WRONG_SSN
REQUEST_IN_PROGRESS
NO_RESET
DEFERRED
RESET_OUTGOING
RESET_INCOMING
RESET_BOTH
SSN_TSN
ADD_INCOMING
ADD_OUTGOING
OUTGOING_RESET_REQUEST_PARAMETER
INCOMING_RESET_REQUEST_PARAMETER
SSN_TSN_RESET_REQUEST_PARAMETER
STREAM_RESET_RESPONSE_PARAMETER
ADD_OUTGOING_STREAMS_REQUEST_PARAMETER
ADD_INCOMING_STREAMS_REQUEST_PARAMETER
ADD_BOTH
PERFORMED_WITH_OPTION
PERFORMED_WITH_ADDOUT
{
     NOTHING_TO_DO                          = 0,
     PERFORMED                              = 1,
     DENIED                                 = 2,
     WRONG_SSN                              = 3,
     REQUEST_IN_PROGRESS                    = 4,
     NO_RESET                               = 5,
     DEFERRED                               = 6,
     RESET_OUTGOING                         = 7,
     RESET_INCOMING                         = 8,
     RESET_BOTH                             = 9,
     SSN_TSN                                = 10,
     ADD_INCOMING                           = 11,
     ADD_OUTGOING                           = 12,
     OUTGOING_RESET_REQUEST_PARAMETER       = 13,
     INCOMING_RESET_REQUEST_PARAMETER       = 14,
     SSN_TSN_RESET_REQUEST_PARAMETER        = 15,
     STREAM_RESET_RESPONSE_PARAMETER        = 16,
     ADD_OUTGOING_STREAMS_REQUEST_PARAMETER = 17,
     ADD_INCOMING_STREAMS_REQUEST_PARAMETER = 18,
     ADD_BOTH                               = 19,
     PERFORMED_WITH_OPTION                  = 20,
     PERFORMED_WITH_ADDOUT                  = 21
 };
SctpStreamSchedulers
enum inet::sctp::SctpStreamSchedulers
Enumerator
ROUND_ROBIN
ROUND_ROBIN_PACKET
RANDOM_SCHEDULE
RANDOM_SCHEDULE_PACKET
FAIR_BANDWITH
FAIR_BANDWITH_PACKET
PRIORITY
FCFS
PATH_MANUAL
PATH_MAP_TO_PATH
{
     ROUND_ROBIN            = 0,
     ROUND_ROBIN_PACKET     = 1,
     RANDOM_SCHEDULE        = 2,
     RANDOM_SCHEDULE_PACKET = 3,
     FAIR_BANDWITH          = 4,
     FAIR_BANDWITH_PACKET   = 5,
     PRIORITY               = 6,
     FCFS                   = 7,
     PATH_MANUAL            = 8,
     PATH_MAP_TO_PATH       = 9
 };
Function Documentation
Define_Module() [1/5]
inet::sctp::Define_Module (Sctp)
Define_Module() [2/5]
inet::sctp::Define_Module (SctpCrcInsertion)
Define_Module() [3/5]
inet::sctp::Define_Module (SctpNatHook)
Define_Module() [4/5]
inet::sctp::Define_Module (SctpNatTable)
Define_Module() [5/5]
inet::sctp::Define_Module (SctpUdpHook)
doParsimPacking() [1/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const NatMessage & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [2/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpAbortChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [3/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpAddIPParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [4/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpAddStreamsRequestParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [5/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpAuthenticationChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [6/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [7/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpCookie & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [8/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpCookieAckChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [9/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpCookieEchoChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [10/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpDataChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [11/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpDataMsg & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [12/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpDeleteIPParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [13/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpErrorCauseParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [14/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpForwardTsnChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [15/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpHeartbeatAckChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [16/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpHeartbeatChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [17/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpInitAckChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [18/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpInitChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [19/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpOutgoingSsnResetRequestParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [20/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpPacketDropChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [21/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [22/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpResetTimer & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [23/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpSackChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [24/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpSetPrimaryIPParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [25/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpShutdownAckChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [26/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpShutdownChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [27/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpShutdownCompleteChunk & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [28/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpSimpleErrorCauseParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [29/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpSsnTsnResetRequestParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [30/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpStreamResetResponseParameter & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [31/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpSuccessIndication & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [32/32]
void inet::sctp::doParsimPacking (omnetpp::cCommBuffer * b, const SctpSupportedExtensionsParameter & obj) inline
 {obj.parsimPack(b);}
doParsimUnpacking() [1/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, NatMessage & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [2/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpAbortChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [3/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpAddIPParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [4/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpAddStreamsRequestParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [5/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpAuthenticationChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [6/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [7/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpCookie & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [8/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpCookieAckChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [9/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpCookieEchoChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [10/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpDataChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [11/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpDataMsg & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [12/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpDeleteIPParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [13/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpErrorCauseParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [14/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpForwardTsnChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [15/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpHeartbeatAckChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [16/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpHeartbeatChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [17/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpInitAckChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [18/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpInitChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [19/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpOutgoingSsnResetRequestParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [20/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpPacketDropChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [21/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [22/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpResetTimer & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [23/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpSackChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [24/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpSetPrimaryIPParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [25/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpShutdownAckChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [26/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpShutdownChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [27/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpShutdownCompleteChunk & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [28/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpSimpleErrorCauseParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [29/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpSsnTsnResetRequestParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [30/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpStreamResetResponseParameter & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [31/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpSuccessIndication & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [32/32]
void inet::sctp::doParsimUnpacking (omnetpp::cCommBuffer * b, SctpSupportedExtensionsParameter & obj) inline
 {obj.parsimUnpack(b);}
max()
double inet::sctp::max (const double a, const double b) inline
Returns the maximum of a and b.
 { return (a < b) ? b : a; }
Referenced by inet::HeatMapPlotFigure::bakeValues(), inet::EthernetCsmaMac::canContinueBurst(), inet::VoipStreamSender::checkSilence(), inet::sctp::SctpAssociation::choosePathForRetransmission(), inet::queueing::DynamicClassifier::classifyPacket(), inet::BvhTree::computeBoundingBox(), inet::Prism::computeBoundingBoxSize(), inet::Polyhedron::computeBoundingBoxSize(), inet::Polygon::computeSize(), inet::physicallayer::ConvolutionalCode::ConvolutionalCode(), inet::osg::createQuadGeometry(), inet::visualizer::SceneOsgVisualizerBase::createSceneFloor(), inet::sctp::SctpAssociation::cwndUpdateAfterRtxTimeout(), inet::sctp::SctpAssociation::cwndUpdateAfterSack(), inet::sctp::SctpAssociation::cwndUpdateBeforeSack(), inet::tcp::TcpBaseAlg::established(), inet::SimpleVoipReceiver::evaluateTalkspurt(), inet::IntervalTree::fixupMaxHigh(), inet::LabeledIconFigure::getBounds(), inet::Box::getCenter(), inet::visualizer::RadioCanvasVisualizer::getGainRadius(), inet::sctp::SctpAssociation::getInitialCwnd(), inet::Box::getMax(), inet::visualizer::SceneOsgVisualizerBase::getNetworkBoundingSphere(), inet::Gpsr::getPlanarNeighbors(), inet::visualizer::SceneVisualizerBase::getSceneBounds(), inet::Box::getSize(), inet::aodv::Aodv::handleHelloMessage(), inet::RandomDriftOscillator::handleMessage(), inet::aodv::Aodv::handleRREP(), inet::aodv::Aodv::handleRREQ(), inet::TelnetApp::handleStartOperation(), inet::TcpBasicClientApp::handleStartOperation(), inet::UdpVideoStreamClient::handleStartOperation(), inet::UdpSink::handleStartOperation(), inet::UdpBasicApp::handleStartOperation(), inet::UdpBasicBurst::handleStartOperation(), inet::DhcpServer::handleStartOperation(), inet::DhcpClient::handleStartOperation(), inet::physicallayer::Ieee80211OfdmInterleaver::Ieee80211OfdmInterleaver(), inet::OperationalMixin< cSimpleModule >::initialize(), inet::Box::isUnspecified(), inet::layoutSubmodulesWithGates(), inet::IntervalTree::leftRotate(), inet::SpatialGrid::LineSegmentIterator::LineSegmentIterator(), inet::queueing::StatisticalRateLimiter::matchesPacket(), inet::tcp::memp_init(), inet::EligibilityTimeMeter::meterPacket(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::physicallayer::DimensionalTransmitterBase::normalize(), inet::physicalenvironment::PhysicalEnvironment::parseObjects(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::partition(), inet::math::Rasterized2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::partition(), inet::sctp::SctpAssociation::pmRttMeasurement(), inet::Rip::processResponse(), inet::tcp::TcpNewReno::recalculateSlowStartThreshold(), inet::tcp::TcpReno::recalculateSlowStartThreshold(), inet::tcp::TcpTahoe::recalculateSlowStartThreshold(), inet::tcp::TcpVegas::recalculateSlowStartThreshold(), inet::tcp::TcpReno::receivedDataAck(), inet::tcp::DcTcp::receivedDataAck(), inet::utils::filters::MaxPerGroupFilter::receiveSignal(), inet::LinearGaugeFigure::redrawTicks(), inet::ThermometerFigure::redrawTicks(), inet::GaugeFigure::redrawTicks(), inet::ProgressMeterFigure::refresh(), inet::CounterFigure::refresh(), inet::SignalFigure::refresh(), inet::BarFigure::refreshDisplay(), inet::visualizer::GateScheduleCanvasVisualizer::refreshGateVisualization(), inet::IntervalTree::rightRotate(), inet::Ipv4NetworkConfigurator::routesCanBeNeighbors(), inet::TcpSessionApp::sendData(), inet::tcp::TcpBaseAlg::sendData(), inet::tcp::TcpSegmentTransmitInfoList::set(), inet::HeatMapPlotFigure::setPixelSafe(), inet::Posture::setPostureSpeed(), inet::SctpSocket::setRtoInfo(), inet::TcpSessionApp::socketEstablished(), inet::queueing::CreditBasedGate::updateCurrentCredit(), and inet::aodv::Aodv::updateValidRouteLifeTime().
min()
double inet::sctp::min (const double a, const double b) inline
Returns the minimum of a and b.
 { return (a < b) ? a : b; }
Referenced by inet::RealTimeScheduler::advanceSimTime(), inet::Ipv4NetworkConfigurator::assignAddresses(), inet::sctp::SctpAssociation::bytesAllowedToSend(), inet::Prism::computeBoundingBoxSize(), inet::Polyhedron::computeBoundingBoxSize(), inet::ieee80211::OriginatorBlockAckAgreementHandler::computeEarliestExpirationTime(), inet::ieee80211::RecipientBlockAckAgreementHandler::computeEarliestExpirationTime(), inet::Polygon::computeSize(), inet::BitsChunk::convertChunk(), inet::BitCountChunk::convertChunk(), inet::ByteCountChunk::convertChunk(), inet::BytesChunk::convertChunk(), inet::SliceChunk::convertChunk(), inet::SequenceChunk::convertChunk(), inet::Chunk::convertChunk(), inet::SpatialGrid::coordToMatrixIndices(), inet::osg::createQuadGeometry(), inet::sctp::SctpAssociation::createSack(), inet::visualizer::SceneOsgVisualizerBase::createSceneFloor(), inet::sctp::SctpAssociation::cwndUpdateBytesAcked(), inet::physicallayer::Ieee80211OfdmRadio::decapsulate(), inet::tcp::TcpBaseAlg::established(), inet::CsmaCaMac::generateBackoffPeriod(), inet::VoipStreamSender::generatePacket(), inet::Chunk::getBinDumpLine(), inet::LabeledIconFigure::getBounds(), inet::Box::getCenter(), inet::Chunk::getHexDumpLine(), inet::ieee80211::SequentialFs::getHistory(), inet::sctp::SctpAssociation::getInitialCwnd(), inet::Box::getMin(), inet::visualizer::SceneVisualizerBase::getSceneBounds(), inet::Box::getSize(), inet::RandomDriftOscillator::handleMessage(), inet::Box::isUnspecified(), inet::physicalenvironment::PhysicalEnvironment::parseObjects(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::partition(), inet::math::Rasterized2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::partition(), inet::ByteCountChunk::peekUnchecked(), inet::BitsChunk::peekUnchecked(), inet::BytesChunk::peekUnchecked(), inet::BitCountChunk::peekUnchecked(), inet::SliceChunk::peekUnchecked(), inet::PlotFigure::plot(), inet::sctp::SctpAssociation::pmRttMeasurement(), inet::sctp::SctpAssociation::process_TIMEOUT_ASCONF(), inet::sctp::SctpAssociation::process_TIMEOUT_HEARTBEAT(), inet::sctp::SctpAssociation::process_TIMEOUT_RESET(), inet::sctp::SctpAssociation::process_TIMEOUT_RTX(), inet::tcp::TcpConnection::processMSSOption(), inet::Igmpv3::processQuery(), inet::Rip::processResponse(), inet::tcp::TcpNewReno::recalculateSlowStartThreshold(), inet::tcp::TcpReno::recalculateSlowStartThreshold(), inet::tcp::TcpTahoe::recalculateSlowStartThreshold(), inet::tcp::TcpVegas::recalculateSlowStartThreshold(), inet::tcp::TcpNewReno::receivedDataAck(), inet::tcp::DcTcp::receivedDataAck(), inet::tcp::TcpVegas::receivedDataAck(), inet::tcp::TcpVegas::receivedDuplicateAck(), inet::queueing::CreditBasedGate::receiveSignal(), inet::ProgressMeterFigure::refresh(), inet::SignalFigure::refresh(), inet::BarFigure::refreshDisplay(), inet::visualizer::GateScheduleCanvasVisualizer::refreshGateVisualization(), inet::sctp::SctpSimpleGapList::removeFromGapList(), inet::tcp::TcpConnection::retransmitData(), inet::tcp::TcpConnection::retransmitOneSegment(), inet::Ipv4NetworkConfigurator::routesCanBeNeighbors(), inet::Ieee802154Mac::scheduleBackoff(), inet::ieee80211::Contention::scheduleTransmissionRequest(), inet::tcp::TcpBaseAlg::sendData(), inet::tcp::TcpConnection::sendData(), inet::Icmpv6::sendErrorMessage(), inet::Icmp::sendErrorMessage(), inet::sctp::SctpAssociation::sendInitAck(), inet::tcp::TcpConnection::sendOneNewSegment(), inet::Icmp::sendPtbMessage(), inet::sctp::SctpHeaderSerializer::serialize(), inet::tcp::TcpSegmentTransmitInfoList::set(), inet::HeatMapPlotFigure::setPixelSafe(), inet::Posture::setPostureSpeed(), inet::SctpSocket::setRtoInfo(), inet::queueing::CreditBasedGate::updateCurrentCredit(), inet::sctp::SctpSimpleGapList::updateGapList(), and inet::sctp::SctpAssociation::updateOLIA().
operator<<() [1/2]
std::ostream& inet::sctp::operator<< (std::ostream & ostr, const SctpGapList & gapList) inline
 { gapList.print(ostr); return ostr; }
operator<<() [2/2]
std::ostream& inet::sctp::operator<< (std::ostream & ostr, const SctpSimpleGapList & gapList) inline
 { gapList.print(ostr); return ostr; }
Register_Class() [1/8]
inet::sctp::Register_Class (SctpAlg)
Register_Class() [2/8]
inet::sctp::Register_Class (SctpAsconfAckChunk)
Register_Class() [3/8]
inet::sctp::Register_Class (SctpAsconfChunk)
Register_Class() [4/8]
inet::sctp::Register_Class (SctpErrorChunk)
Register_Class() [5/8]
inet::sctp::Register_Class (SctpHeader)
Register_Class() [6/8]
inet::sctp::Register_Class (SctpIncomingSsnResetRequestParameter)
Register_Class() [7/8]
inet::sctp::Register_Class (SctpQueue)
Register_Class() [8/8]
inet::sctp::Register_Class (SctpStreamResetChunk)
Register_Serializer()
inet::sctp::Register_Serializer (SctpHeader , SctpHeaderSerializer)
Variable Documentation
__PACKED__
struct inet::sctp::data_vector inet::sctp::__PACKED__