INET Framework for OMNeT++/OMNEST: inet::ospfv3 Namespace Reference
inet::ospfv3 Namespace Reference
Classes
class ASExternalLSA
class InterAreaPrefixLSA
class InterAreaRouterLSA
class IntraAreaPrefixLSA
struct Ipv4AddressRange
struct Ipv6AddressRange
class LinkLSA
struct LSAKeyType
class LSATrackingInfo
class NetworkLSA
struct NextHop
class NssaLSA
class Ospfv3Area
class Ospfv3AsExternalLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:244 by opp_msgtool.
class Ospfv3DatabaseDescriptionPacket
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:316 by opp_msgtool.
struct Ospfv3DdOptions
Struct generated from inet/routing/ospfv3/Ospfv3Packet.msg:304 by opp_msgtool.
struct Ospfv3DdPacketId
class Ospfv3HelloPacket
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:56 by opp_msgtool.
class Ospfv3Instance
class Ospfv3InterAreaPrefixLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:228 by opp_msgtool.
class Ospfv3InterAreaRouterLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:236 by opp_msgtool.
class Ospfv3Interface
class Ospfv3InterfacePassive
class Ospfv3InterfaceState
class Ospfv3InterfaceStateBackup
class Ospfv3InterfaceStateDown
class Ospfv3InterfaceStateDr
class Ospfv3InterfaceStateDrOther
class Ospfv3InterfaceStateLoopback
class Ospfv3InterfaceStatePointToPoint
class Ospfv3InterfaceStateWaiting
class Ospfv3IntraAreaPrefixLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:293 by opp_msgtool.
class Ospfv3Ipv4RoutingTableEntry
class Ospfv3LinkLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:281 by opp_msgtool.
class Ospfv3LinkStateAcknowledgementPacket
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:370 by opp_msgtool.
class Ospfv3LinkStateRequestPacket
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:342 by opp_msgtool.
class Ospfv3LinkStateUpdatePacket
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:352 by opp_msgtool.
class Ospfv3Lsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:96 by opp_msgtool.
class Ospfv3LsaHeader
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:82 by opp_msgtool.
struct Ospfv3LsaPrefix0
Struct generated from inet/routing/ospfv3/Ospfv3Packet.msg:153 by opp_msgtool.
struct Ospfv3LsaPrefixMetric
Struct generated from inet/routing/ospfv3/Ospfv3Packet.msg:117 by opp_msgtool.
struct Ospfv3LsRequest
Struct generated from inet/routing/ospfv3/Ospfv3Packet.msg:333 by opp_msgtool.
class Ospfv3Neighbor
class Ospfv3NeighborState
class Ospfv3NeighborState2Way
class Ospfv3NeighborStateAttempt
class Ospfv3NeighborStateDown
class Ospfv3NeighborStateExchange
class Ospfv3NeighborStateExStart
class Ospfv3NeighborStateFull
class Ospfv3NeighborStateInit
class Ospfv3NeighborStateLoading
class Ospfv3NetworkLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:220 by opp_msgtool.
class Ospfv3NssaLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:263 by opp_msgtool.
struct Ospfv3Options
Struct generated from inet/routing/ospfv3/Ospfv3Packet.msg:39 by opp_msgtool.
class Ospfv3Packet
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:17 by opp_msgtool.
class Ospfv3Process
class Ospfv3RouterLsa
Class generated from inet/routing/ospfv3/Ospfv3Packet.msg:207 by opp_msgtool.
struct Ospfv3RouterLsaBody
Struct generated from inet/routing/ospfv3/Ospfv3Packet.msg:196 by opp_msgtool.
class Ospfv3RoutingTableEntry
class Ospfv3SpfVertex
class Ospfv3Splitter
class RouterLSA
class RoutingInfo
struct VertexID
struct VertexLSA
Typedefs
typedef Ipv4Address AreaID
typedef unsigned int Metric
Enumerations
enum InstallSource { ORIGINATED = 0, FLOODED = 1 }
enum Ospfv3LsaFunctionCode {
ROUTER_LSA = 1, NETWORK_LSA = 2, INTER_AREA_PREFIX_LSA = 3, INTER_AREA_ROUTER_LSA = 4,
AS_EXTERNAL_LSA = 5, DEPRECATED = 6, NSSA_LSA = 7, LINK_LSA = 8,
INTRA_AREA_PREFIX_LSA = 9
}
Enum generated from inet/routing/ospfv3/Ospfv3Packet.msg:103 by opp_msgtool.
enum Ospfv3RouterLsaType { POINT_TO_POINT = 1, TRANSIT_NETWORK = 2, RESERVED = 3, VIRTUAL_LINK = 4 }
Enum generated from inet/routing/ospfv3/Ospfv3Packet.msg:188 by opp_msgtool.
enum Ospfv3Timers {
INIT_PROCESS = 0, HELLO_TIMER = 1, WAIT_TIMER = 2, NEIGHBOR_INACTIVITY_TIMER = 3,
NEIGHBOR_POLL_TIMER = 4, NEIGHBOR_DD_RETRANSMISSION_TIMER = 5, NEIGHBOR_UPDATE_RETRANSMISSION_TIMER = 6, NEIGHBOR_REQUEST_RETRANSMISSION_TIMER = 7,
ACKNOWLEDGEMENT_TIMER = 8, DATABASE_AGE_TIMER = 9, HELLO_TIMER_INIT = 10
}
enum Ospfv3AreaType {
NORMAL = 0, STUB, TOTALLY_STUBBY, NSSA,
NSSA_TOTALLY_STUB
}
Functions
std::ostream & operator<< (std::ostream &ostr, const Ospfv3Interface &interface)
const Ipv4Address NULL_ROUTERID (0, 0, 0, 0)
const Ipv4Address BACKBONE_AREAID (0, 0, 0, 0)
const Ipv4Address NULL_LINKSTATEID (0, 0, 0, 0)
const Ipv4Address NULL_IPV4ADDRESS (0, 0, 0, 0)
const Ipv6AddressRange NULL_IPV6ADDRESSRANGE (Ipv6Address(0, 0, 0, 0), 0)
bool isSameNetwork (Ipv6Address address1, int prefixLen1, Ipv6Address address2, int prefixLen2)
const Ipv4AddressRange NULL_IPV4ADDRESSRANGE (Ipv4Address(0, 0, 0, 0), Ipv4Address(0, 0, 0, 0))
Ipv4Address operator& (Ipv4Address address, Ipv4Address mask)
Ipv4Address operator| (Ipv4Address address, Ipv4Address match)
bool isSameNetwork (Ipv4Address address1, Ipv4Address mask1, Ipv4Address address2, Ipv4Address mask2)
bool operator== (const VertexID &leftID, const VertexID &rightID)
bool operator== (const NextHop &leftHop, const NextHop &rightHop)
bool operator!= (const NextHop &leftHop, const NextHop &rightHop)
bool operator!= (Ospfv3DdOptions leftID, Ospfv3DdOptions rightID)
bool operator== (Ospfv3Options leftID, Ospfv3Options rightID)
bool operator!= (Ospfv3Options leftID, Ospfv3Options rightID)
bool operator!= (Ospfv3DdPacketId leftID, Ospfv3DdPacketId rightID)
bool operator< (Ospfv3LsaHeader &leftLSA, Ospfv3LsaHeader &rightLSA)
bool operator< (const Ospfv3LsaHeader &leftLSA, const Ospfv3LsaHeader &rightLSA)
bool operator== (Ospfv3LsaHeader &leftLSA, Ospfv3LsaHeader &rightLSA)
bool operator== (const Ospfv3LsaHeader &leftLSA, const Ospfv3LsaHeader &rightLSA)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3Packet &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3Packet &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv3Options &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv3Options &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3Options &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3Options &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3HelloPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3HelloPacket &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LsaHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsaHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3Lsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3Lsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LsaFunctionCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsaFunctionCode &e)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv3LsaPrefixMetric &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsaPrefixMetric &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LsaPrefixMetric &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsaPrefixMetric &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv3LsaPrefix0 &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsaPrefix0 &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LsaPrefix0 &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsaPrefix0 &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3RouterLsaType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3RouterLsaType &e)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv3RouterLsaBody &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv3RouterLsaBody &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3RouterLsaBody &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3RouterLsaBody &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3RouterLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3RouterLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3NetworkLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3NetworkLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3InterAreaPrefixLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3InterAreaPrefixLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3InterAreaRouterLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3InterAreaRouterLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3AsExternalLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3AsExternalLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3NssaLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3NssaLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LinkLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LinkLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3IntraAreaPrefixLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3IntraAreaPrefixLsa &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv3DdOptions &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv3DdOptions &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3DdOptions &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3DdOptions &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3DatabaseDescriptionPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3DatabaseDescriptionPacket &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv3LsRequest &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsRequest &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LsRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LsRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LinkStateRequestPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LinkStateRequestPacket &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LinkStateUpdatePacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LinkStateUpdatePacket &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv3LinkStateAcknowledgementPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv3LinkStateAcknowledgementPacket &obj)
Define_Module (Ospfv3Splitter)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3Area &area)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3Instance &instance)
B calculateLSASize (const Ospfv3RouterLsa *routerLSA)
B calculateLSASize (const Ospfv3NetworkLsa *networkLSA)
B calculateLSASize (const Ospfv3InterAreaPrefixLsa *prefixLSA)
B calculateLSASize (const Ospfv3LinkLsa *linkLSA)
B calculateLSASize (const Ospfv3IntraAreaPrefixLsa *prefixLSA)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3LsaHeader &lsaHeader)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3NetworkLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3RouterLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3InterAreaPrefixLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3AsExternalLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv3Lsa &lsa)
Define_Module (Ospfv3Process)
std::ostream & operator<< (std::ostream &out, const Ospfv3RoutingTableEntry &entry)
std::ostream & operator<< (std::ostream &out, const Ospfv3Ipv4RoutingTableEntry &entry)
Variables
const B IPV6_DATAGRAM_LENGTH = B(65535)
const B OSPFV3_HEADER_LENGTH = B(16)
const B OSPFV3_DD_HEADER_LENGTH = B(12)
const B OSPFV3_LSA_HEADER_LENGTH = B(20)
const B OSPFV3_LSR_LENGTH = B(12)
const B OSPFV3_ROUTER_LSA_HEADER_LENGTH = B(4)
const B OSPFV3_ROUTER_LSA_BODY_LENGTH = B(16)
const B OSPFV3_NETWORK_LSA_HEADER_LENGTH = B(4)
const B OSPFV3_NETWORK_LSA_ATTACHED_LENGTH = B(4)
const B OSPFV3_INTER_AREA_PREFIX_LSA_HEADER_LENGTH = B(4)
const B OSPFV3_INTER_AREA_PREFIX_LSA_BODY_LENGTH = B(24)
const B OSPFV3_INTRA_AREA_PREFIX_LSA_HEADER_LENGTH = B(12)
const B OSPFV3_INTRA_AREA_PREFIX_LSA_PREFIX_LENGTH = B(20)
const B OSPFV3_LINK_LSA_BODY_LENGTH = B(24)
const B OSPFV3_LINK_LSA_PREFIX_LENGTH = B(20)
const B OSPFV3_LSA_PREFIX_HEADER_LENGTH = B(4)
int ospfv3InterfaceIndex = 1
Typedef Documentation
AreaID
typedef Ipv4Address inet::ospfv3::AreaID
Metric
typedef unsigned int inet::ospfv3::Metric
Enumeration Type Documentation
InstallSource
enum inet::ospfv3::InstallSource
Enumerator
ORIGINATED
FLOODED
                    {
     ORIGINATED = 0,
     FLOODED    = 1
 };
Ospfv3AreaType
enum inet::ospfv3::Ospfv3AreaType
Enumerator
NORMAL
STUB
TOTALLY_STUBBY
NSSA
NSSA_TOTALLY_STUB
                     {
     NORMAL = 0,
     STUB,
     TOTALLY_STUBBY,
     NSSA,
     NSSA_TOTALLY_STUB
 };
Ospfv3LsaFunctionCode
enum inet::ospfv3::Ospfv3LsaFunctionCode
Enum generated from inet/routing/ospfv3/Ospfv3Packet.msg:103 by opp_msgtool.
//LSA Function Code
enum Ospfv3LsaFunctionCode
{
    ROUTER_LSA = 1;
    NETWORK_LSA = 2;
    INTER_AREA_PREFIX_LSA = 3;
    INTER_AREA_ROUTER_LSA = 4;
    AS_EXTERNAL_LSA = 5;
    DEPRECATED = 6;
    NSSA_LSA = 7;
    LINK_LSA = 8;
    INTRA_AREA_PREFIX_LSA = 9;
}
Enumerator
ROUTER_LSA
NETWORK_LSA
INTER_AREA_PREFIX_LSA
INTER_AREA_ROUTER_LSA
AS_EXTERNAL_LSA
DEPRECATED
NSSA_LSA
LINK_LSA
INTRA_AREA_PREFIX_LSA
{
     ROUTER_LSA = 1,
     NETWORK_LSA = 2,
     INTER_AREA_PREFIX_LSA = 3,
     INTER_AREA_ROUTER_LSA = 4,
     AS_EXTERNAL_LSA = 5,
     DEPRECATED = 6,
     NSSA_LSA = 7,
     LINK_LSA = 8,
     INTRA_AREA_PREFIX_LSA = 9
 };
Ospfv3RouterLsaType
enum inet::ospfv3::Ospfv3RouterLsaType
Enum generated from inet/routing/ospfv3/Ospfv3Packet.msg:188 by opp_msgtool.
//Router LSA
enum Ospfv3RouterLsaType
{
    POINT_TO_POINT = 1;
    TRANSIT_NETWORK = 2;
    RESERVED = 3;
    VIRTUAL_LINK = 4;
}
Enumerator
POINT_TO_POINT
TRANSIT_NETWORK
RESERVED
VIRTUAL_LINK
{
     POINT_TO_POINT = 1,
     TRANSIT_NETWORK = 2,
     RESERVED = 3,
     VIRTUAL_LINK = 4
 };
Ospfv3Timers
enum inet::ospfv3::Ospfv3Timers
Enumerator
INIT_PROCESS
HELLO_TIMER
WAIT_TIMER
NEIGHBOR_INACTIVITY_TIMER
NEIGHBOR_POLL_TIMER
NEIGHBOR_DD_RETRANSMISSION_TIMER
NEIGHBOR_UPDATE_RETRANSMISSION_TIMER
NEIGHBOR_REQUEST_RETRANSMISSION_TIMER
ACKNOWLEDGEMENT_TIMER
DATABASE_AGE_TIMER
HELLO_TIMER_INIT
                   {
     INIT_PROCESS                          = 0,
     HELLO_TIMER                           = 1,
     WAIT_TIMER                            = 2,
     NEIGHBOR_INACTIVITY_TIMER             = 3,
     NEIGHBOR_POLL_TIMER                   = 4,
     NEIGHBOR_DD_RETRANSMISSION_TIMER      = 5,
     NEIGHBOR_UPDATE_RETRANSMISSION_TIMER  = 6,
     NEIGHBOR_REQUEST_RETRANSMISSION_TIMER = 7,
     ACKNOWLEDGEMENT_TIMER                 = 8,
     DATABASE_AGE_TIMER                    = 9,
     HELLO_TIMER_INIT                      = 10 // timer set by process, for initialisation of hello msgs
 };
Function Documentation
__doPacking() [1/6]
void INET_API inet::ospfv3::__doPacking (omnetpp::cCommBuffer * b, const Ospfv3DdOptions & a)
__doPacking() [2/6]
void INET_API inet::ospfv3::__doPacking (omnetpp::cCommBuffer * b, const Ospfv3LsaPrefix0 & a)
__doPacking() [3/6]
void INET_API inet::ospfv3::__doPacking (omnetpp::cCommBuffer * b, const Ospfv3LsaPrefixMetric & a)
__doPacking() [4/6]
void INET_API inet::ospfv3::__doPacking (omnetpp::cCommBuffer * b, const Ospfv3LsRequest & a)
__doPacking() [5/6]
void INET_API inet::ospfv3::__doPacking (omnetpp::cCommBuffer * b, const Ospfv3Options & a)
Referenced by doParsimPacking().
__doPacking() [6/6]
void INET_API inet::ospfv3::__doPacking (omnetpp::cCommBuffer * b, const Ospfv3RouterLsaBody & a)
__doUnpacking() [1/6]
void INET_API inet::ospfv3::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv3DdOptions & a)
__doUnpacking() [2/6]
void INET_API inet::ospfv3::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsaPrefix0 & a)
__doUnpacking() [3/6]
void INET_API inet::ospfv3::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsaPrefixMetric & a)
__doUnpacking() [4/6]
void INET_API inet::ospfv3::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsRequest & a)
__doUnpacking() [5/6]
void INET_API inet::ospfv3::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv3Options & a)
Referenced by doParsimUnpacking().
__doUnpacking() [6/6]
void INET_API inet::ospfv3::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv3RouterLsaBody & a)
BACKBONE_AREAID()
const Ipv4Address inet::ospfv3::BACKBONE_AREAID (0 , 0 , 0 , 0)
Referenced by inet::ospfv3::Ospfv3Interface::processLSU(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), and inet::ospfv3::Ospfv3Area::recheckInterAreaPrefixLSAs().
calculateLSASize() [1/5]
B inet::ospfv3::calculateLSASize (const Ospfv3InterAreaPrefixLsa * prefixLSA)
 {
 //    return OSPFV3_LSA_HEADER_LENGTH + OSPFV3_INTER_AREA_PREFIX_LSA_HEADER_LENGTH + OSPFV3_INTER_AREA_PREFIX_LSA_BODY_LENGTH;
     return OSPFV3_LSA_HEADER_LENGTH + OSPFV3_INTER_AREA_PREFIX_LSA_HEADER_LENGTH + OSPFV3_LSA_PREFIX_HEADER_LENGTH + B(((prefixLSA->getPrefix().prefixLen + 31) / 32) * 4);
 }
calculateLSASize() [2/5]
B inet::ospfv3::calculateLSASize (const Ospfv3IntraAreaPrefixLsa * prefixLSA)
 {
     B lsaLength = OSPFV3_LSA_HEADER_LENGTH + OSPFV3_INTRA_AREA_PREFIX_LSA_HEADER_LENGTH;
     uint32_t prefixCount = prefixLSA->getNumPrefixes();
     for (uint32_t i = 0; i < prefixCount; i++) {
         lsaLength += OSPFV3_LSA_PREFIX_HEADER_LENGTH;
         lsaLength += B(((prefixLSA->getPrefixes(i).prefixLen + 31) / 32) * 4);
     }
     return lsaLength;
 }
calculateLSASize() [3/5]
B inet::ospfv3::calculateLSASize (const Ospfv3LinkLsa * linkLSA)
 {
     B lsaLength = OSPFV3_LSA_HEADER_LENGTH + OSPFV3_LINK_LSA_BODY_LENGTH;
     uint32_t prefixCount = linkLSA->getNumPrefixes();
     for (uint32_t i = 0; i < prefixCount; i++) {
         lsaLength += OSPFV3_LSA_PREFIX_HEADER_LENGTH;
         lsaLength += B(((linkLSA->getPrefixes(i).prefixLen + 31) / 32) * 4);
     }
     return lsaLength;
 }
calculateLSASize() [4/5]
B inet::ospfv3::calculateLSASize (const Ospfv3NetworkLsa * networkLSA)
 {
     return OSPFV3_LSA_HEADER_LENGTH + OSPFV3_NETWORK_LSA_HEADER_LENGTH +
            (OSPFV3_NETWORK_LSA_ATTACHED_LENGTH * networkLSA->getAttachedRouterArraySize());
 }
calculateLSASize() [5/5]
B inet::ospfv3::calculateLSASize (const Ospfv3RouterLsa * routerLSA)
 {
     return OSPFV3_LSA_HEADER_LENGTH + OSPFV3_ROUTER_LSA_HEADER_LENGTH +
            (OSPFV3_ROUTER_LSA_BODY_LENGTH * routerLSA->getRoutersArraySize());
 }
Referenced by inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::prepareUpdatePacket(), and inet::ospfv3::Ospfv3Neighbor::retransmitUpdatePacket().
Define_Module() [1/2]
inet::ospfv3::Define_Module (Ospfv3Process)
Define_Module() [2/2]
inet::ospfv3::Define_Module (Ospfv3Splitter)
doParsimPacking() [1/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3AsExternalLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [2/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3DatabaseDescriptionPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [3/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3DdOptions & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [4/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3HelloPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [5/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3InterAreaPrefixLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [6/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3InterAreaRouterLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [7/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3IntraAreaPrefixLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [8/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LinkLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [9/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LinkStateAcknowledgementPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [10/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LinkStateRequestPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [11/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LinkStateUpdatePacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [12/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3Lsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [13/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LsaFunctionCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [14/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LsaHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [15/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LsaPrefix0 & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [16/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LsaPrefixMetric & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [17/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3LsRequest & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [18/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3NetworkLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [19/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3NssaLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [20/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3Options & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [21/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3Packet & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [22/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3RouterLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [23/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3RouterLsaBody & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [24/24]
void inet::ospfv3::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv3RouterLsaType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimUnpacking() [1/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3AsExternalLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [2/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3DatabaseDescriptionPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [3/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3DdOptions & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [4/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3HelloPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [5/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3InterAreaPrefixLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [6/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3InterAreaRouterLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [7/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3IntraAreaPrefixLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [8/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LinkLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [9/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LinkStateAcknowledgementPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [10/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LinkStateRequestPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [11/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LinkStateUpdatePacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [12/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3Lsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [13/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsaFunctionCode & e) inline
 { int n; b->unpack(n); e = static_cast<Ospfv3LsaFunctionCode>(n); }
doParsimUnpacking() [14/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsaHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [15/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsaPrefix0 & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [16/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsaPrefixMetric & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [17/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3LsRequest & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [18/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3NetworkLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [19/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3NssaLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [20/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3Options & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [21/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3Packet & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [22/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3RouterLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [23/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3RouterLsaBody & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [24/24]
void inet::ospfv3::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv3RouterLsaType & e) inline
 { int n; b->unpack(n); e = static_cast<Ospfv3RouterLsaType>(n); }
isSameNetwork() [1/2]
bool inet::ospfv3::isSameNetwork (Ipv4Address address1, Ipv4Address mask1, Ipv4Address address2, Ipv4Address mask2) inline
 {
     return (mask1 == mask2) && ((address1 & mask1) == (address2 & mask2));
 }
isSameNetwork() [2/2]
bool inet::ospfv3::isSameNetwork (Ipv6Address address1, int prefixLen1, Ipv6Address address2, int prefixLen2) inline
 {
     return (prefixLen1 == prefixLen2) && (address1.getPrefix(prefixLen1) == address2.getPrefix(prefixLen2));
 }
Referenced by inet::ospfv3::Ospfv3Area::findSameOrWorseCostRoute().
NULL_IPV4ADDRESS()
const Ipv4Address inet::ospfv3::NULL_IPV4ADDRESS (0 , 0 , 0 , 0)
Referenced by inet::ospfv3::Ospfv3InterfaceState::calculateDesignatedRouter(), inet::ospfv3::Ospfv3Neighbor::needAdjacency(), inet::ospfv3::Ospfv3Neighbor::Ospfv3Neighbor(), and inet::ospfv3::Ospfv3Interface::processHelloPacket().
NULL_IPV4ADDRESSRANGE()
const Ipv4AddressRange inet::ospfv3::NULL_IPV4ADDRESSRANGE (Ipv4Address(0, 0, 0, 0) , Ipv4Address(0, 0, 0, 0))
Referenced by inet::ospfv3::Ospfv3Area::addAddressRange().
NULL_IPV6ADDRESSRANGE()
const Ipv6AddressRange inet::ospfv3::NULL_IPV6ADDRESSRANGE (Ipv6Address(0, 0, 0, 0) , 0)
Referenced by inet::ospfv3::Ospfv3Area::addAddressRange().
NULL_LINKSTATEID()
const Ipv4Address inet::ospfv3::NULL_LINKSTATEID (0 , 0 , 0 , 0)
NULL_ROUTERID()
const Ipv4Address inet::ospfv3::NULL_ROUTERID (0 , 0 , 0 , 0)
operator!=() [1/4]
bool inet::ospfv3::operator!= (const NextHop & leftHop, const NextHop & rightHop) inline
 {
     return !(leftHop == rightHop);
 }
operator!=() [2/4]
bool inet::ospfv3::operator!= (Ospfv3DdOptions leftID, Ospfv3DdOptions rightID) inline
 {
     return (leftID.iBit != rightID.iBit) ||
            (leftID.mBit != rightID.mBit) ||
            (leftID.msBit != rightID.msBit);
 }
operator!=() [3/4]
bool inet::ospfv3::operator!= (Ospfv3DdPacketId leftID, Ospfv3DdPacketId rightID) inline
 {
     return (leftID.ddOptions.iBit != rightID.ddOptions.iBit) ||
            (leftID.ddOptions.mBit != rightID.ddOptions.mBit) ||
            (leftID.ddOptions.msBit != rightID.ddOptions.msBit) ||
            (leftID.options.dcBit != rightID.options.dcBit) ||
            (leftID.options.eBit != rightID.options.eBit) ||
            (leftID.options.nBit != rightID.options.nBit) ||
            (leftID.options.rBit != rightID.options.rBit) ||
            (leftID.options.v6Bit != rightID.options.v6Bit) ||
            (leftID.options.xBit != rightID.options.xBit) ||
            (leftID.sequenceNumber != rightID.sequenceNumber);
 }
operator!=() [4/4]
bool inet::ospfv3::operator!= (Ospfv3Options leftID, Ospfv3Options rightID) inline
 {
     return !(leftID == rightID);
 }
operator&()
Ipv4Address inet::ospfv3::operator& (Ipv4Address address, Ipv4Address mask) inline
 {
     Ipv4Address maskedAddress;
     maskedAddress.set(address.getInt() & mask.getInt());
     return maskedAddress;
 }
operator<() [1/2]
bool inet::ospfv3::operator< (const Ospfv3LsaHeader & leftLSA, const Ospfv3LsaHeader & rightLSA) inline
 {
     long leftSequenceNumber = leftLSA.getLsaSequenceNumber();
     long rightSequenceNumber = rightLSA.getLsaSequenceNumber();
     if (leftSequenceNumber < rightSequenceNumber) {
         return true;
     }
     if (leftSequenceNumber == rightSequenceNumber) {
         unsigned short leftAge = leftLSA.getLsaAge();
         unsigned short rightAge = rightLSA.getLsaAge();
         if ((leftAge != MAX_AGE) && (rightAge == MAX_AGE)) {
             return true;
         }
         if ((leftAge == MAX_AGE) && (rightAge != MAX_AGE)) {
             return false;
         }
         if ((abs(leftAge - rightAge) > MAX_AGE_DIFF) && (leftAge > rightAge)) {
             return true;
         }
     }
     return false;
 }
operator<() [2/2]
bool inet::ospfv3::operator< (Ospfv3LsaHeader & leftLSA, Ospfv3LsaHeader & rightLSA) inline
 {
     long leftSequenceNumber = leftLSA.getLsaSequenceNumber();
     long rightSequenceNumber = rightLSA.getLsaSequenceNumber();
     if (leftSequenceNumber < rightSequenceNumber) {
         return true;
     }
     if (leftSequenceNumber == rightSequenceNumber) {
         unsigned short leftAge = leftLSA.getLsaAge();
         unsigned short rightAge = rightLSA.getLsaAge();
         if ((leftAge != MAX_AGE) && (rightAge == MAX_AGE)) {
             return true;
         }
         if ((leftAge == MAX_AGE) && (rightAge != MAX_AGE)) {
             return false;
         }
         if ((abs(leftAge - rightAge) > MAX_AGE_DIFF) && (leftAge > rightAge)) {
             return true;
         }
     }
     return false;
 }
operator<<() [1/11]
std::ostream& inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3Area & area) inline
 {
     ostr << area.detailedInfo();
     return ostr;
 }
operator<<() [2/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3AsExternalLsa & lsa)
 {
     if (lsa.getEBit())
         ostr << "E, ";
     if (lsa.getTBit())
         ostr << "T, ";
     if (lsa.getFBit())
         ostr << "F, ";
     ostr << "Referenced LSA Type: " << lsa.getReferencedLSType()
          << ", Cost: " << lsa.getMetric()
          << ", Forward: " << lsa.getForwardingAddress()
          << ", ExtRouteTag: " << lsa.getExternalRouteTag()
          << ", Referenced LSID: " << lsa.getReferencedLSID()
          << ", ";
     ostr << lsa.getHeader();
     return ostr;
 }
operator<<() [3/11]
std::ostream& inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3Instance & instance) inline
 {
     ostr << instance.detailedInfo();
     return ostr;
 }
operator<<() [4/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3InterAreaPrefixLsa & lsa)
 {
     ostr << "Mask: " << lsa.getPrefix().prefixLen
          << ", Cost: " << lsa.getMetric() << ", ";
     ostr << lsa.getHeader();
     return ostr;
 }
operator<<() [5/11]
std::ostream& inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3Interface & interface) inline
 {
     ostr << interface.detailedInfo();
     return ostr;
 }
operator<<() [6/11]
std::ostream& inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3Lsa & lsa) inline
 { ostr << lsa.getHeader(); return ostr; }
operator<<() [7/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3LsaHeader & lsaHeader)
 {
     ostr << "LSAHeader: age=" << lsaHeader.getLsaAge()
          << ", type=";
     switch (lsaHeader.getLsaType()) {
         case ROUTER_LSA:
             ostr << "RouterLSA";
             break;
         case NETWORK_LSA:
             ostr << "NetworkLSA";
             break;
         case INTER_AREA_PREFIX_LSA:
             ostr << "InterAreaPrefixLSA";
             break;
         case INTER_AREA_ROUTER_LSA:
             ostr << "InterAreaRouterLSA";
             break;
         case AS_EXTERNAL_LSA:
             ostr << "ASExternalLSA";
             break;
         case LINK_LSA:
             ostr << "LinkLSA";
             break;
         case INTRA_AREA_PREFIX_LSA:
             ostr << "IntraAreaPrefixLSA";
             break;
         default:
             ostr << "Unknown";
             break;
     }
     ostr << ", LSID=" << lsaHeader.getLinkStateID().str(false)
          << ", advertisingRouter=" << lsaHeader.getAdvertisingRouter().str(false)
          << ", seqNumber=" << lsaHeader.getLsaSequenceNumber()
          << endl;
     return ostr;
 }
operator<<() [8/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3NetworkLsa & lsa)
 {
     unsigned int cnt = lsa.getAttachedRouterArraySize();
     if (cnt) {
         ostr << ", Attached routers:";
         for (unsigned int i = 0; i < cnt; i++) {
             ostr << " " << lsa.getAttachedRouter(i);
         }
     }
     ostr << ", " << lsa.getHeader();
     return ostr;
 }
operator<<() [9/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & ostr, const Ospfv3RouterLsa & lsa)
 {
     if (lsa.getVBit())
         ostr << "V, ";
     if (lsa.getEBit())
         ostr << "E, ";
     if (lsa.getBBit())
         ostr << "B, ";
     ostr << "numberOfLinks: " << lsa.getRoutersArraySize() << ", ";
     unsigned int cnt = lsa.getRoutersArraySize();
     if (cnt) {
         ostr << "Links: {";
         for (unsigned int i = 0; i < cnt; i++) {
             ostr << " {" << lsa.getRouters(i).neighborRouterID << "}";
         }
         ostr << "}, ";
     }
     ostr << lsa.getHeader();
     return ostr;
 }
operator<<() [10/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & out, const Ospfv3Ipv4RoutingTableEntry & entry)
 {
     out << "Destination: " << entry.getDestinationAsGeneric() << "/" << entry.getPrefixLength() << " (";
     if (entry.getDestinationType() == Ospfv3Ipv4RoutingTableEntry::NETWORK_DESTINATION) {
         out << "Network";
     }
     else {
         if ((entry.getDestinationType() & Ospfv3Ipv4RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION) != 0) {
             out << "AreaBorderRouter";
         }
         if ((entry.getDestinationType() & Ospfv3Ipv4RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION) != 0) {
             if ((entry.getDestinationType() & Ospfv3Ipv4RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION) != 0) {
                 out << "+";
             }
             out << "ASBoundaryRouter";
         }
     }
     out << "), Area: "
         << entry.getArea().str(false)
         << ", PathType: ";
     switch (entry.getPathType()) {
         case Ospfv3Ipv4RoutingTableEntry::INTRAAREA:
             out << "IntraArea";
             break;
         case Ospfv3Ipv4RoutingTableEntry::INTERAREA:
             out << "InterArea";
             break;
         case Ospfv3Ipv4RoutingTableEntry::TYPE1_EXTERNAL:
             out << "Type1External";
             break;
         case Ospfv3Ipv4RoutingTableEntry::TYPE2_EXTERNAL:
             out << "Type2External";
             break;
         default:
             out << "Unknown";
             break;
     }
     out << ", iface: " << entry.getInterface()->getNedTypeName();
     out << ", Cost: " << entry.getCost()
         << ", Type2Cost: " << entry.getType2Cost()
         << ", Origin: ["; // << entry.getLinkStateOrigin()->getHeader().getLinkStateID()
     Ospfv3LsaHeader lsaHeader = entry.getLinkStateOrigin()->getHeader();
     out << "LSAHeader: age=" << lsaHeader.getLsaAge()
         << ", type=";
     switch (lsaHeader.getLsaType()) {
         case ROUTER_LSA:
             out << "RouterLSA";
             break;
         case NETWORK_LSA:
             out << "NetworkLSA";
             break;
         case INTER_AREA_PREFIX_LSA:
             out << "InterAreaPrefixLSA_Networks";
             break;
         case INTER_AREA_ROUTER_LSA:
             out << "InterAreaRouterLSA_ASBoundaryRouters";
             break;
         case AS_EXTERNAL_LSA:
             out << "ASExternalLSA";
             break;
         default:
             out << "Unknown";
             break;
     }
     out << ", LSID=" << lsaHeader.getLinkStateID().str(false)
         << ", advertisingRouter=" << lsaHeader.getAdvertisingRouter().str(false)
         << ", seqNumber=" << lsaHeader.getLsaSequenceNumber()
         << endl
         << "], NextHops: ";
     unsigned int hopCount = entry.getNextHopCount();
     for (unsigned int i = 0; i < hopCount; i++) {
         out << entry.getNextHop(i).hopAddress << "/" << entry.getNextHop(i).advertisingRouter << "/" << entry.getNextHop(i).ifIndex << "  ";
     }
     return out;
 }
operator<<() [11/11]
std::ostream & inet::ospfv3::operator<< (std::ostream & out, const Ospfv3RoutingTableEntry & entry)
 {
     out << "Destination: " << entry.getDestinationAsGeneric() << "/" << entry.getPrefixLength() << " (";
     if (entry.getDestinationType() == Ospfv3RoutingTableEntry::NETWORK_DESTINATION) {
         out << "Network";
     }
     else {
         if ((entry.getDestinationType() & Ospfv3RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION) != 0) {
             out << "AreaBorderRouter";
         }
         if ((entry.getDestinationType() & Ospfv3RoutingTableEntry::AS_BOUNDARY_ROUTER_DESTINATION) != 0) {
             if ((entry.getDestinationType() & Ospfv3RoutingTableEntry::AREA_BORDER_ROUTER_DESTINATION) != 0) {
                 out << "+";
             }
             out << "ASBoundaryRouter";
         }
     }
     out << "), Area: "
         << entry.getArea().str(false)
         << ", PathType: ";
     switch (entry.getPathType()) {
         case Ospfv3RoutingTableEntry::INTRAAREA:
             out << "IntraArea";
             break;
         case Ospfv3RoutingTableEntry::INTERAREA:
             out << "InterArea";
             break;
         case Ospfv3RoutingTableEntry::TYPE1_EXTERNAL:
             out << "Type1External";
             break;
         case Ospfv3RoutingTableEntry::TYPE2_EXTERNAL:
             out << "Type2External";
             break;
         default:
             out << "Unknown";
             break;
     }
     out << ", iface: " << entry.getInterface()->getNedTypeName();
     out << ", Cost: " << entry.getCost()
         << ", Type2Cost: " << entry.getType2Cost()
         << ", Origin: ["; // << entry.getLinkStateOrigin()->getHeader().getLinkStateID()
     Ospfv3LsaHeader lsaHeader = entry.getLinkStateOrigin()->getHeader();
     out << "LSAHeader: age=" << lsaHeader.getLsaAge()
         << ", type=";
     switch (lsaHeader.getLsaType()) {
         case ROUTER_LSA:
             out << "RouterLSA";
             break;
         case NETWORK_LSA:
             out << "NetworkLSA";
             break;
         case INTER_AREA_PREFIX_LSA:
             out << "InterAreaPrefixLSA_Networks";
             break;
         case INTER_AREA_ROUTER_LSA:
             out << "InterAreaRouterLSA_ASBoundaryRouters";
             break;
         case AS_EXTERNAL_LSA:
             out << "ASExternalLSA";
             break;
         default:
             out << "Unknown";
             break;
     }
     out << ", LSID=" << lsaHeader.getLinkStateID().str(false)
         << ", advertisingRouter=" << lsaHeader.getAdvertisingRouter().str(false)
         << ", seqNumber=" << lsaHeader.getLsaSequenceNumber()
         << endl
         << "], NextHops: ";
     unsigned int hopCount = entry.getNextHopCount();
     for (unsigned int i = 0; i < hopCount; i++) {
         out << entry.getNextHop(i).hopAddress << "/" << entry.getNextHop(i).advertisingRouter << "/" << entry.getNextHop(i).ifIndex << "  ";
     }
     return out;
 }
operator==() [1/5]
bool inet::ospfv3::operator== (const NextHop & leftHop, const NextHop & rightHop) inline
 {
     return (leftHop.ifIndex == rightHop.ifIndex) &&
            (leftHop.hopAddress == rightHop.hopAddress) &&
            (leftHop.advertisingRouter == rightHop.advertisingRouter);
 }
operator==() [2/5]
bool inet::ospfv3::operator== (const Ospfv3LsaHeader & leftLSA, const Ospfv3LsaHeader & rightLSA) inline
 {
     long leftSequenceNumber = leftLSA.getLsaSequenceNumber();
     long rightSequenceNumber = rightLSA.getLsaSequenceNumber();
     unsigned short leftAge = leftLSA.getLsaAge();
     unsigned short rightAge = rightLSA.getLsaAge();
     if ((leftSequenceNumber == rightSequenceNumber) &&
         (((leftAge == MAX_AGE) && (rightAge == MAX_AGE)) ||
          (((leftAge != MAX_AGE) && (rightAge != MAX_AGE)) &&
           (abs(leftAge - rightAge) <= MAX_AGE_DIFF))))
     {
         return true;
     }
     else {
         return false;
     }
 }
operator==() [3/5]
bool inet::ospfv3::operator== (const VertexID & leftID, const VertexID & rightID) inline
 {
     return (leftID.interfaceID == rightID.interfaceID)
            && (leftID.routerID == rightID.routerID);
 }
Referenced by inet::ospfv3::Ospfv3Interface::processLSU().
operator==() [4/5]
bool inet::ospfv3::operator== (Ospfv3LsaHeader & leftLSA, Ospfv3LsaHeader & rightLSA) inline
 {
     long leftSequenceNumber = leftLSA.getLsaSequenceNumber();
     long rightSequenceNumber = rightLSA.getLsaSequenceNumber();
     unsigned short leftAge = leftLSA.getLsaAge();
     unsigned short rightAge = rightLSA.getLsaAge();
     if ((leftSequenceNumber == rightSequenceNumber) &&
         (((leftAge == MAX_AGE) && (rightAge == MAX_AGE)) ||
          (((leftAge != MAX_AGE) && (rightAge != MAX_AGE)) &&
           (abs(leftAge - rightAge) <= MAX_AGE_DIFF))))
     {
         return true;
     }
     else {
         return false;
     }
 }
operator==() [5/5]
bool inet::ospfv3::operator== (Ospfv3Options leftID, Ospfv3Options rightID) inline
 {
     return (leftID.dcBit == rightID.dcBit) ||
            (leftID.eBit == rightID.eBit) ||
            (leftID.nBit == rightID.nBit) ||
            (leftID.rBit == rightID.rBit) ||
            (leftID.v6Bit == rightID.v6Bit) ||
            (leftID.xBit == rightID.xBit);
 }
operator|()
Ipv4Address inet::ospfv3::operator| (Ipv4Address address, Ipv4Address match) inline
 {
     Ipv4Address matchAddress;
     matchAddress.set(address.getInt() | match.getInt());
     return matchAddress;
 }
Variable Documentation
IPV6_DATAGRAM_LENGTH
const B inet::ospfv3::IPV6_DATAGRAM_LENGTH = B(65535)
Referenced by inet::ospfv3::Ospfv3Neighbor::retransmitUpdatePacket().
OSPFV3_DD_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_DD_HEADER_LENGTH = B(12)
Referenced by inet::ospfv3::Ospfv3Neighbor::sendDDPacket().
OSPFV3_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_HEADER_LENGTH = B(16)
Referenced by inet::ospfv3::Ospfv3Interface::acknowledgeLSA(), inet::ospfv3::Ospfv3Interface::prepareLSUHeader(), inet::ospfv3::Ospfv3Interface::prepareUpdatePacket(), inet::ospfv3::Ospfv3Neighbor::retransmitUpdatePacket(), inet::ospfv3::Ospfv3Neighbor::sendDDPacket(), inet::ospfv3::Ospfv3Interface::sendDelayedAcknowledgements(), inet::ospfv3::Ospfv3Neighbor::sendLinkStateRequestPacket(), and inet::ospfv3::Ospfv3Interface::sendLSAcknowledgement().
OSPFV3_INTER_AREA_PREFIX_LSA_BODY_LENGTH
const B inet::ospfv3::OSPFV3_INTER_AREA_PREFIX_LSA_BODY_LENGTH = B(24)
OSPFV3_INTER_AREA_PREFIX_LSA_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_INTER_AREA_PREFIX_LSA_HEADER_LENGTH = B(4)
Referenced by calculateLSASize(), and inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA().
OSPFV3_INTRA_AREA_PREFIX_LSA_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_INTRA_AREA_PREFIX_LSA_HEADER_LENGTH = B(12)
Referenced by calculateLSASize(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
OSPFV3_INTRA_AREA_PREFIX_LSA_PREFIX_LENGTH
const B inet::ospfv3::OSPFV3_INTRA_AREA_PREFIX_LSA_PREFIX_LENGTH = B(20)
OSPFV3_LINK_LSA_BODY_LENGTH
const B inet::ospfv3::OSPFV3_LINK_LSA_BODY_LENGTH = B(24)
Referenced by calculateLSASize(), and inet::ospfv3::Ospfv3Interface::originateLinkLSA().
OSPFV3_LINK_LSA_PREFIX_LENGTH
const B inet::ospfv3::OSPFV3_LINK_LSA_PREFIX_LENGTH = B(20)
OSPFV3_LSA_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_LSA_HEADER_LENGTH = B(20)
Referenced by inet::ospfv3::Ospfv3Interface::acknowledgeLSA(), calculateLSASize(), inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Interface::originateLinkLSA(), inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateNetworkLSA(), inet::ospfv3::Ospfv3Neighbor::retransmitUpdatePacket(), inet::ospfv3::Ospfv3Neighbor::sendDDPacket(), inet::ospfv3::Ospfv3Interface::sendDelayedAcknowledgements(), and inet::ospfv3::Ospfv3Interface::sendLSAcknowledgement().
OSPFV3_LSA_PREFIX_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_LSA_PREFIX_HEADER_LENGTH = B(4)
Referenced by calculateLSASize(), inet::ospfv3::Ospfv3Area::originateDefaultInterAreaPrefixLSA(), inet::ospfv3::Ospfv3Area::originateIntraAreaPrefixLSA(), and inet::ospfv3::Ospfv3Area::originateNetIntraAreaPrefixLSA().
OSPFV3_LSR_LENGTH
const B inet::ospfv3::OSPFV3_LSR_LENGTH = B(12)
Referenced by inet::ospfv3::Ospfv3Neighbor::sendLinkStateRequestPacket().
OSPFV3_NETWORK_LSA_ATTACHED_LENGTH
const B inet::ospfv3::OSPFV3_NETWORK_LSA_ATTACHED_LENGTH = B(4)
Referenced by calculateLSASize().
OSPFV3_NETWORK_LSA_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_NETWORK_LSA_HEADER_LENGTH = B(4)
Referenced by calculateLSASize().
OSPFV3_ROUTER_LSA_BODY_LENGTH
const B inet::ospfv3::OSPFV3_ROUTER_LSA_BODY_LENGTH = B(16)
Referenced by calculateLSASize().
OSPFV3_ROUTER_LSA_HEADER_LENGTH
const B inet::ospfv3::OSPFV3_ROUTER_LSA_HEADER_LENGTH = B(4)
Referenced by calculateLSASize().
ospfv3InterfaceIndex
int inet::ospfv3::ospfv3InterfaceIndex = 1