INET Framework for OMNeT++/OMNEST: inet::osm Namespace Reference
inet::osm Namespace Reference
Classes
struct Bounds
class Member
class Node
class OpenStreetMap
Represents OpenStreetMap map data, as loaded from an OSM file.
class Relation
class Tags
class Way
Typedefs
typedef int64_t id_t
Functions
double parseDouble (const char *s)
id_t parseId (const char *s)
Typedef Documentation
id_t
typedef int64_t inet::osm::id_t
Function Documentation
parseDouble()
double inet::osm::parseDouble (const char * s) inline
 {
     return std::strtod(s, nullptr);
 }
Referenced by inet::osm::OpenStreetMap::from(), inet::utils::filters::UtilizationFilter::init(), and inet::utils::filters::ThroughputFilter::init().
parseId()
id_t inet::osm::parseId (const char * s) inline
 {
     return std::strtoll(s, nullptr, 10);
 }
Referenced by inet::osm::OpenStreetMap::from().