INET Framework for OMNeT++/OMNEST: omnetpp Namespace Reference
omnetpp Namespace Reference
Functions
template<>
inet::ApplicationPacket * fromAnyPtr (any_ptr ptr)
any_ptr toAnyPtr (const inet::ClockTime *p)
any_ptr toAnyPtr (const inet::IClock *p)
any_ptr toAnyPtr (const inet::Coord *p)
any_ptr toAnyPtr (const inet::EulerAngles *p)
any_ptr toAnyPtr (const inet::Quaternion *p)
any_ptr toAnyPtr (const inet::ChunkBuffer::Region *p)
any_ptr toAnyPtr (const inet::Protocol *p)
any_ptr toAnyPtr (const inet::ChunkPtr *p)
any_ptr toAnyPtr (const inet::b *p)
any_ptr toAnyPtr (const inet::MacAddress *p)
any_ptr toAnyPtr (const inet::ieee80211::IFrameSequenceStep *p)
any_ptr toAnyPtr (const inet::BitVector *p)
any_ptr toAnyPtr (const inet::ieee80211::SequenceNumberCyclic *p)
any_ptr toAnyPtr (const inet::ieee80211::Ieee80211CapabilityInformation *p)
any_ptr toAnyPtr (const inet::ieee80211::Ieee80211HandoverParameters *p)
any_ptr toAnyPtr (const inet::ieee80211::Ieee80211SupportedRatesElement *p)
any_ptr toAnyPtr (const inet::PortIdentity *p)
any_ptr toAnyPtr (const inet::GptpTlv *p)
any_ptr toAnyPtr (const inet::L3Address *p)
any_ptr toAnyPtr (const inet::NetworkInterface *p)
any_ptr toAnyPtr (const inet::ClnsAddress *p)
any_ptr toAnyPtr (const inet::Ipv4Address *p)
any_ptr toAnyPtr (const inet::Ipv4AddressVector *p)
any_ptr toAnyPtr (const inet::Ipv6Address *p)
any_ptr toAnyPtr (const inet::GroupRecord *p)
any_ptr toAnyPtr (const inet::FecTlv *p)
any_ptr toAnyPtr (const inet::EroVector *p)
any_ptr toAnyPtr (const inet::FlowDescriptorVector *p)
any_ptr toAnyPtr (const inet::SessionObj *p)
any_ptr toAnyPtr (const inet::RsvpHopObj *p)
any_ptr toAnyPtr (const inet::SenderTemplateObj *p)
any_ptr toAnyPtr (const inet::SenderTspecObj *p)
any_ptr toAnyPtr (const inet::LabelRequestObj *p)
any_ptr toAnyPtr (const inet::SenderDescriptor_t *p)
any_ptr toAnyPtr (const inet::EroObj *p)
any_ptr toAnyPtr (const inet::FlowDescriptor_t *p)
any_ptr toAnyPtr (const inet::TeLinkStateInfo *p)
any_ptr toAnyPtr (const inet::physicallayer::IModulation *p)
any_ptr toAnyPtr (const inet::physicallayer::IApskModulation *p)
any_ptr toAnyPtr (const inet::physicallayer::BandListening *p)
any_ptr toAnyPtr (const inet::physicallayer::Arrival *p)
any_ptr toAnyPtr (const inet::physicallayer::ITransmission *p)
any_ptr toAnyPtr (const inet::physicallayer::IArrival *p)
any_ptr toAnyPtr (const inet::physicallayer::IListening *p)
any_ptr toAnyPtr (const inet::physicallayer::IReception *p)
any_ptr toAnyPtr (const inet::physicallayer::IIeee80211Band *p)
any_ptr toAnyPtr (const inet::physicallayer::Ieee80211Channel *p)
any_ptr toAnyPtr (const inet::physicallayer::IIeee80211PreambleMode *p)
any_ptr toAnyPtr (const inet::physicallayer::IIeee80211HeaderMode *p)
any_ptr toAnyPtr (const inet::physicallayer::IIeee80211DataMode *p)
any_ptr toAnyPtr (const inet::aodv::UnreachableNode *p)
any_ptr toAnyPtr (const inet::bgp::BgpOptionalParameterBase *p)
any_ptr toAnyPtr (const inet::bgp::BgpUpdateWithdrawnRoutes *p)
any_ptr toAnyPtr (const inet::bgp::BgpUpdateNlri *p)
any_ptr toAnyPtr (const inet::dymo::DymoSequenceNumber *p)
any_ptr toAnyPtr (const inet::EigrpKValues *p)
any_ptr toAnyPtr (const inet::EigrpRouteFlags *p)
any_ptr toAnyPtr (const inet::EigrpWideMetricPar *p)
any_ptr toAnyPtr (const inet::EigrpStub *p)
any_ptr toAnyPtr (const inet::EigrpTlvStub *p)
any_ptr toAnyPtr (const inet::EigrpTlvParameter *p)
any_ptr toAnyPtr (const inet::EigrpMpIpv4Internal *p)
any_ptr toAnyPtr (const inet::EigrpMpIpv6Internal *p)
any_ptr toAnyPtr (const inet::EigrpMsgRoute *p)
any_ptr toAnyPtr (const inet::ospfv2::Ospfv2Options *p)
any_ptr toAnyPtr (const inet::ospfv2::Ospfv2TosData *p)
any_ptr toAnyPtr (const inet::ospfv2::Ospfv2ExternalTosInfo *p)
any_ptr toAnyPtr (const inet::ospfv2::Ospfv2DdOptions *p)
any_ptr toAnyPtr (const inet::ospfv2::Ospfv2LsaRequest *p)
any_ptr toAnyPtr (const inet::ospfv3::Ospfv3Options *p)
any_ptr toAnyPtr (const inet::ospfv3::Ospfv3LsaPrefixMetric *p)
any_ptr toAnyPtr (const inet::ospfv3::Ospfv3LsaPrefix0 *p)
any_ptr toAnyPtr (const inet::ospfv3::Ospfv3RouterLsaBody *p)
any_ptr toAnyPtr (const inet::ospfv3::Ospfv3DdOptions *p)
any_ptr toAnyPtr (const inet::ospfv3::Ospfv3LsRequest *p)
any_ptr toAnyPtr (const inet::EncodedUnicastAddress *p)
any_ptr toAnyPtr (const inet::EncodedGroupAddress *p)
any_ptr toAnyPtr (const inet::EncodedSourceAddress *p)
any_ptr toAnyPtr (const inet::RipEntry *p)
any_ptr toAnyPtr (const inet::AddressVector *p)
any_ptr toAnyPtr (const inet::tcp::TcpSackRexmitQueue *p)
any_ptr toAnyPtr (const inet::tcp::TcpStateVariables *p)
Function Documentation
fromAnyPtr()
template<> inet::visualizer::PacketDrop * omnetpp::fromAnyPtr (any_ptr ptr) inline
 { return check_and_cast<inet::ApplicationPacket*>(ptr.get<cObject>()); }
toAnyPtr() [1/82]
any_ptr omnetpp::toAnyPtr (const inet::AddressVector * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [2/82]
any_ptr omnetpp::toAnyPtr (const inet::aodv::UnreachableNode * p) inline
 {return any_ptr(p);}
toAnyPtr() [3/82]
any_ptr omnetpp::toAnyPtr (const inet::b * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [4/82]
any_ptr omnetpp::toAnyPtr (const inet::bgp::BgpOptionalParameterBase * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [5/82]
any_ptr omnetpp::toAnyPtr (const inet::bgp::BgpUpdateNlri * p) inline
 {return any_ptr(p);}
toAnyPtr() [6/82]
any_ptr omnetpp::toAnyPtr (const inet::bgp::BgpUpdateWithdrawnRoutes * p) inline
 {return any_ptr(p);}
toAnyPtr() [7/82]
any_ptr omnetpp::toAnyPtr (const inet::BitVector * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [8/82]
any_ptr omnetpp::toAnyPtr (const inet::ChunkBuffer::Region * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [9/82]
any_ptr omnetpp::toAnyPtr (const inet::ChunkPtr * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [10/82]
any_ptr omnetpp::toAnyPtr (const inet::ClnsAddress * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [11/82]
any_ptr omnetpp::toAnyPtr (const inet::ClockTime * p) inline
 {return any_ptr(p);}
Referenced by inet::MessageChecker::checkMessage(), inet::FieldsChunk::containsSameData(), inet::TemporarySharedPtrClassDescriptor< inet::units::value >::doesSupport(), inet::MatchableObject::getAsString(), inet::TemporarySharedPtrClassDescriptor< inet::units::value >::getObjectPointer(), inet::TagBase::printFieldsToStream(), inet::FieldsChunk::printFieldsToStream(), inet::ObjectPrinter::printObjectToStream(), inet::PacketFilter::DynamicExpressionResolver::readMember(), and inet::PacketFilter::DynamicExpressionResolver::readVariable().
toAnyPtr() [12/82]
any_ptr omnetpp::toAnyPtr (const inet::Coord * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [13/82]
any_ptr omnetpp::toAnyPtr (const inet::dymo::DymoSequenceNumber * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [14/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpKValues * p) inline
 {return any_ptr(p);}
toAnyPtr() [15/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpMpIpv4Internal * p) inline
 {return any_ptr(p);}
toAnyPtr() [16/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpMpIpv6Internal * p) inline
 {return any_ptr(p);}
toAnyPtr() [17/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpMsgRoute * p) inline
 {return any_ptr(p);}
toAnyPtr() [18/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpRouteFlags * p) inline
 {return any_ptr(p);}
toAnyPtr() [19/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpStub * p) inline
 {return any_ptr(p);}
toAnyPtr() [20/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpTlvParameter * p) inline
 {return any_ptr(p);}
toAnyPtr() [21/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpTlvStub * p) inline
 {return any_ptr(p);}
toAnyPtr() [22/82]
any_ptr omnetpp::toAnyPtr (const inet::EigrpWideMetricPar * p) inline
 {return any_ptr(p);}
toAnyPtr() [23/82]
any_ptr omnetpp::toAnyPtr (const inet::EncodedGroupAddress * p) inline
 {return any_ptr(p);}
toAnyPtr() [24/82]
any_ptr omnetpp::toAnyPtr (const inet::EncodedSourceAddress * p) inline
 {return any_ptr(p);}
toAnyPtr() [25/82]
any_ptr omnetpp::toAnyPtr (const inet::EncodedUnicastAddress * p) inline
 {return any_ptr(p);}
toAnyPtr() [26/82]
any_ptr omnetpp::toAnyPtr (const inet::EroObj * p) inline
 {return any_ptr(p);}
toAnyPtr() [27/82]
any_ptr omnetpp::toAnyPtr (const inet::EroVector * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [28/82]
any_ptr omnetpp::toAnyPtr (const inet::EulerAngles * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [29/82]
any_ptr omnetpp::toAnyPtr (const inet::FecTlv * p) inline
 {return any_ptr(p);}
toAnyPtr() [30/82]
any_ptr omnetpp::toAnyPtr (const inet::FlowDescriptor_t * p) inline
 {return any_ptr(p);}
toAnyPtr() [31/82]
any_ptr omnetpp::toAnyPtr (const inet::FlowDescriptorVector * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [32/82]
any_ptr omnetpp::toAnyPtr (const inet::GptpTlv * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [33/82]
any_ptr omnetpp::toAnyPtr (const inet::GroupRecord * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [34/82]
any_ptr omnetpp::toAnyPtr (const inet::IClock * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [35/82]
any_ptr omnetpp::toAnyPtr (const inet::ieee80211::Ieee80211CapabilityInformation * p) inline
 {return any_ptr(p);}
toAnyPtr() [36/82]
any_ptr omnetpp::toAnyPtr (const inet::ieee80211::Ieee80211HandoverParameters * p) inline
 {return any_ptr(p);}
toAnyPtr() [37/82]
any_ptr omnetpp::toAnyPtr (const inet::ieee80211::Ieee80211SupportedRatesElement * p) inline
 {return any_ptr(p);}
toAnyPtr() [38/82]
any_ptr omnetpp::toAnyPtr (const inet::ieee80211::IFrameSequenceStep * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [39/82]
any_ptr omnetpp::toAnyPtr (const inet::ieee80211::SequenceNumberCyclic * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [40/82]
any_ptr omnetpp::toAnyPtr (const inet::Ipv4Address * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [41/82]
any_ptr omnetpp::toAnyPtr (const inet::Ipv4AddressVector * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [42/82]
any_ptr omnetpp::toAnyPtr (const inet::Ipv6Address * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [43/82]
any_ptr omnetpp::toAnyPtr (const inet::L3Address * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [44/82]
any_ptr omnetpp::toAnyPtr (const inet::LabelRequestObj * p) inline
 {return any_ptr(p);}
toAnyPtr() [45/82]
any_ptr omnetpp::toAnyPtr (const inet::MacAddress * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [46/82]
any_ptr omnetpp::toAnyPtr (const inet::NetworkInterface * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [47/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv2::Ospfv2DdOptions * p) inline
 {return any_ptr(p);}
toAnyPtr() [48/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv2::Ospfv2ExternalTosInfo * p) inline
 {return any_ptr(p);}
toAnyPtr() [49/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv2::Ospfv2LsaRequest * p) inline
 {return any_ptr(p);}
toAnyPtr() [50/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv2::Ospfv2Options * p) inline
 {return any_ptr(p);}
toAnyPtr() [51/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv2::Ospfv2TosData * p) inline
 {return any_ptr(p);}
toAnyPtr() [52/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv3::Ospfv3DdOptions * p) inline
 {return any_ptr(p);}
toAnyPtr() [53/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv3::Ospfv3LsaPrefix0 * p) inline
 {return any_ptr(p);}
toAnyPtr() [54/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv3::Ospfv3LsaPrefixMetric * p) inline
 {return any_ptr(p);}
toAnyPtr() [55/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv3::Ospfv3LsRequest * p) inline
 {return any_ptr(p);}
toAnyPtr() [56/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv3::Ospfv3Options * p) inline
 {return any_ptr(p);}
toAnyPtr() [57/82]
any_ptr omnetpp::toAnyPtr (const inet::ospfv3::Ospfv3RouterLsaBody * p) inline
 {return any_ptr(p);}
toAnyPtr() [58/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::Arrival * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [59/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::BandListening * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [60/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IApskModulation * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [61/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IArrival * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [62/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::Ieee80211Channel * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [63/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IIeee80211Band * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [64/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IIeee80211DataMode * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [65/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IIeee80211HeaderMode * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [66/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IIeee80211PreambleMode * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [67/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IListening * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [68/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IModulation * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [69/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::IReception * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [70/82]
any_ptr omnetpp::toAnyPtr (const inet::physicallayer::ITransmission * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [71/82]
any_ptr omnetpp::toAnyPtr (const inet::PortIdentity * p) inline
 {return any_ptr(p);}
toAnyPtr() [72/82]
any_ptr omnetpp::toAnyPtr (const inet::Protocol * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [73/82]
any_ptr omnetpp::toAnyPtr (const inet::Quaternion * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [74/82]
any_ptr omnetpp::toAnyPtr (const inet::RipEntry * p) inline
 {return any_ptr(p);}
toAnyPtr() [75/82]
any_ptr omnetpp::toAnyPtr (const inet::RsvpHopObj * p) inline
 {return any_ptr(p);}
toAnyPtr() [76/82]
any_ptr omnetpp::toAnyPtr (const inet::SenderDescriptor_t * p) inline
 {return any_ptr(p);}
toAnyPtr() [77/82]
any_ptr omnetpp::toAnyPtr (const inet::SenderTemplateObj * p) inline
 {return any_ptr(p);}
toAnyPtr() [78/82]
any_ptr omnetpp::toAnyPtr (const inet::SenderTspecObj * p) inline
 {return any_ptr(p);}
toAnyPtr() [79/82]
any_ptr omnetpp::toAnyPtr (const inet::SessionObj * p) inline
 {return any_ptr(p);}
toAnyPtr() [80/82]
any_ptr omnetpp::toAnyPtr (const inet::tcp::TcpSackRexmitQueue * p) inline
 {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
toAnyPtr() [81/82]
any_ptr omnetpp::toAnyPtr (const inet::tcp::TcpStateVariables * p) inline
 {return any_ptr(p);}
toAnyPtr() [82/82]
any_ptr omnetpp::toAnyPtr (const inet::TeLinkStateInfo * p) inline
 {return any_ptr(p);}