INET Framework for OMNeT++/OMNEST: inet::units Namespace Reference
inet::units Namespace Reference
Namespaces
constants
internal
units
values
Classes
struct compose
struct fscale
struct intscale
struct output_unit
struct pow
struct scale
struct translate
class value
Typedefs
typedef pow< internal::none, 0 > unit
Functions
template<typename Value , typename Unit >
value< Value, pow< Unit, -1 > > operator/ (const Value &a, const value< Value, Unit > &b)
template<typename Value , typename Unit >
value< Value, Unit > operator* (const Value &a, const value< Value, Unit > &b)
template<typename Value , typename Unit >
value< Value, pow< Unit, 1, 2 > > sqrt (const value< Value, Unit > &a)
template<int Num, int Den, typename Value , typename Unit >
value< Value, pow< Unit, Num, Den > > raise (const value< Value, Unit > &a)
template<typename Value , typename Units >
void doParsimPacking (cCommBuffer *buffer, const value< Value, Units > &a)
template<typename Value , typename Units >
void doParsimUnpacking (cCommBuffer *buffer, value< Value, Units > &a)
UNIT_DISPLAY_NAME (unit, "1")
template<typename Value , typename Unit >
std::ostream & operator<< (std::ostream &os, const value< Value, Unit > &value)
UNIT_DISPLAY_NAME (units::m, "m")
UNIT_DISPLAY_NAME (units::kg, "kg")
UNIT_DISPLAY_NAME (units::s, "s")
UNIT_DISPLAY_NAME (units::K, "K")
UNIT_DISPLAY_NAME (units::A, "A")
UNIT_DISPLAY_NAME (units::mol, "mol")
UNIT_DISPLAY_NAME (units::cd, "cd")
UNIT_DISPLAY_NAME (units::b, "b")
UNIT_DISPLAY_NAME (units::rad, "rad")
UNIT_DISPLAY_NAME (units::sr, "sr")
UNIT_DISPLAY_NAME (units::Hz, "Hz")
UNIT_DISPLAY_NAME (units::N, "N")
UNIT_DISPLAY_NAME (units::Pa, "Pa")
UNIT_DISPLAY_NAME (units::J, "J")
UNIT_DISPLAY_NAME (units::W, "W")
UNIT_DISPLAY_NAME (units::WpHz, "WpHz")
UNIT_DISPLAY_NAME (units::C, "C")
UNIT_DISPLAY_NAME (units::V, "V")
UNIT_DISPLAY_NAME (units::F, "F")
UNIT_DISPLAY_NAME (units::Ohm, "Ohm")
UNIT_DISPLAY_NAME (units::S, "S")
UNIT_DISPLAY_NAME (units::Wb, "Wb")
UNIT_DISPLAY_NAME (units::T, "T")
UNIT_DISPLAY_NAME (units::H, "H")
UNIT_DISPLAY_NAME (units::lx, "lx")
UNIT_DISPLAY_NAME (units::Gy, "Gy")
UNIT_DISPLAY_NAME (units::kat, "kat")
UNIT_DISPLAY_NAME (units::cm, "cm")
UNIT_DISPLAY_NAME (units::mm, "mm")
UNIT_DISPLAY_NAME (units::km, "km")
UNIT_DISPLAY_NAME (units::ps, "ps")
UNIT_DISPLAY_NAME (units::lb, "lb")
UNIT_DISPLAY_NAME (units::oz, "oz")
UNIT_DISPLAY_NAME (units::tonne, "tonnes")
UNIT_DISPLAY_NAME (units::Celsius, "'C")
UNIT_DISPLAY_NAME (units::Fahrenheit, "'F")
UNIT_DISPLAY_NAME (units::minute, "minutes")
UNIT_DISPLAY_NAME (units::hour, "hours")
UNIT_DISPLAY_NAME (units::day, "days")
UNIT_DISPLAY_NAME (units::week, "weeks")
UNIT_DISPLAY_NAME (units::month, "months")
UNIT_DISPLAY_NAME (units::year, "years")
UNIT_DISPLAY_NAME (units::century, "centuries")
UNIT_DISPLAY_NAME (units::millennium, "millennia")
UNIT_DISPLAY_NAME (units::inch, "inches")
UNIT_DISPLAY_NAME (units::foot, "foot")
UNIT_DISPLAY_NAME (units::yard, "yards")
UNIT_DISPLAY_NAME (units::mile, "miles")
UNIT_DISPLAY_NAME (units::nautical_mile, "nautical miles")
UNIT_DISPLAY_NAME (units::hectare, "ha")
UNIT_DISPLAY_NAME (units::are, "are")
UNIT_DISPLAY_NAME (units::acre, "acres")
UNIT_DISPLAY_NAME (units::ml, "ml")
UNIT_DISPLAY_NAME (units::liter, "l")
UNIT_DISPLAY_NAME (units::dl, "dl")
UNIT_DISPLAY_NAME (units::cl, "cl")
UNIT_DISPLAY_NAME (units::mph, "mph")
UNIT_DISPLAY_NAME (units::mps, "mps")
UNIT_DISPLAY_NAME (units::kph, "km/h")
UNIT_DISPLAY_NAME (units::knot, "knots")
UNIT_DISPLAY_NAME (units::mach, "mach")
UNIT_DISPLAY_NAME (units::deg, "deg")
UNIT_DISPLAY_NAME (units::deg_min, "'")
UNIT_DISPLAY_NAME (units::deg_sec, "\"")
UNIT_DISPLAY_NAME (units::kPa, "kPa")
UNIT_DISPLAY_NAME (units::psi, "PSI")
UNIT_DISPLAY_NAME (units::millibar, "millibars")
UNIT_DISPLAY_NAME (units::B, "B")
UNIT_DISPLAY_NAME (units::bps, "bps")
UNIT_DISPLAY_NAME (units::percent, "%")
UNIT_DISPLAY_NAME (units::rpm, "rpm")
UNIT_DISPLAY_NAME (units::dozen, "dozen")
UNIT_DISPLAY_NAME (units::bakers_dozen, "bakers dozen")
template<typename Value >
std::ostream & operator<< (std::ostream &os, const value< Value, units::b > &value)
template<typename Value >
std::ostream & operator<< (std::ostream &os, const value< Value, units::W > &value)
template<typename Value >
std::ostream & operator<< (std::ostream &os, const value< Value, units::Hz > &value)
template<typename Value >
std::ostream & operator<< (std::ostream &os, const value< Value, units::bps > &value)
std::ostream & operator<< (std::ostream &os, const value< double, units::s > &value)
std::ostream & operator<< (std::ostream &os, const value< simtime_t, units::s > &value)
template<typename Value , typename Unit >
Value sin (const value< Value, Unit > &angle)
template<typename Value , typename Unit >
Value cos (const value< Value, Unit > &angle)
template<typename Value , typename Unit >
Value tan (const value< Value, Unit > &angle)
Typedef Documentation
unit
typedef pow<internal::none, 0> inet::units::unit
Function Documentation
cos()
template<typename Value , typename Unit > Value inet::units::cos (const value< Value, Unit > & angle)
 {
     return std::cos(value<Value, units::rad>(angle).get());
 }
Referenced by inet::physicallayer::CosineAntenna::AntennaGain::computeGain(), inet::SimpleGeographicCoordinateSystem::computeGeographicCoordinate(), inet::physicallayer::DielectricObstacleLoss::computeReflectionLoss(), inet::SimpleGeographicCoordinateSystem::computeSceneCoordinate(), inet::physicallayer::TwoRayInterference::computeTwoRayInterference(), inet::osg::createAnnulusVertices(), inet::osg::createCircleVertices(), inet::VehicleMobility::move(), inet::CircleMobility::move(), inet::Quaternion::Quaternion(), inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe(), inet::StaticConcentricMobility::setInitialPosition(), inet::StaticLinearMobility::setInitialPosition(), inet::VehicleMobility::setInitialPosition(), and inet::GaussMarkovMobility::setTargetPosition().
doParsimPacking()
template<typename Value , typename Units > void inet::units::doParsimPacking (cCommBuffer * buffer, const value< Value, Units > & a) inline
 {
     buffer->pack(a.get());
 }
doParsimUnpacking()
template<typename Value , typename Units > void inet::units::doParsimUnpacking (cCommBuffer * buffer, value< Value, Units > & a) inline
 {
     Value v;
     buffer->unpack(v);
     a.set(v);
 }
operator*()
template<typename Value , typename Unit > value<Value, Unit> inet::units::operator* (const Value & a, const value< Value, Unit > & b)
 {
     return value<Value, Unit>(a * b.get());
 }
operator/()
template<typename Value , typename Unit > value<Value, pow<Unit, -1> > inet::units::operator/ (const Value & a, const value< Value, Unit > & b)
 {
     return value<Value, pow<Unit, -1>>(a / b.get());
 }
operator<<() [1/7]
std::ostream& inet::units::operator<< (std::ostream & os, const value< double, units::s > & value) inline
 {
     if (value == values::s(0))
         os << "0 s";
     else if (value.get() == INFINITY)
         os << "inf s";
     else if (value.get() == -INFINITY)
         os << "-inf s";
     else if (value > values::ps(-1000.0) && value < values::ps(1000.0))
         os << values::ps(value);
     else if (value > values::ns(-1000.0) && value < values::ns(1000.0))
         os << values::ns(value);
     else if (value > values::us(-1000.0) && value < values::us(1000.0))
         os << values::us(value);
     else if (value > values::ms(-1000.0) && value < values::ms(1000.0))
         os << values::ms(value);
     else {
         os << value.get() << ' ';
         output_unit<units::s>::fn(os);
     }
     return os;
 }
operator<<() [2/7]
std::ostream& inet::units::operator<< (std::ostream & os, const value< simtime_t, units::s > & value) inline
 {
     // KLUDGE there's no direct infinity support in simtime_t
     static auto positiveInfinity = SimTime::getMaxTime() / 2;
     static auto negativeInfinity = -SimTime::getMaxTime() / 2;
     if (value == values::s(0))
         os << "0 s";
     else if (value.get() == positiveInfinity)
         os << "inf s";
     else if (value.get() == negativeInfinity)
         os << "-inf s";
     else if (value > values::psimsec(-1000) && value < values::psimsec(1000))
         os << values::psimsec(value);
     else if (value > values::nsimsec(-1000) && value < values::nsimsec(1000))
         os << values::nsimsec(value);
     else if (value > values::usimsec(-1000) && value < values::usimsec(1000))
         os << values::usimsec(value);
     else if (value > values::msimsec(-1000) && value < values::msimsec(1000))
         os << values::msimsec(value);
     else {
         os << value.get() << ' ';
         output_unit<units::s>::fn(os);
     }
     return os;
 }
operator<<() [3/7]
template<typename Value , typename Unit > std::ostream& inet::units::operator<< (std::ostream & os, const value< Value, Unit > & value)
 {
     os << value.get() << ' ';
     output_unit<Unit>::fn(os);
     return os;
 }
operator<<() [4/7]
template<typename Value > std::ostream& inet::units::operator<< (std::ostream & os, const value< Value, units::b > & value)
 {
     if (value.get() % 8 == 0)
         os << values::B(value);
     else {
         os << value.get() << ' ';
         output_unit<units::b>::fn(os);
     }
     return os;
 }
operator<<() [5/7]
template<typename Value > std::ostream& inet::units::operator<< (std::ostream & os, const value< Value, units::bps > & value)
 {
     if (value >= values::Gbps(1.0))
         os << values::Gbps(value);
     else if (value >= values::Mbps(1.0))
         os << values::Mbps(value);
     else if (value >= values::kbps(1.0))
         os << values::kbps(value);
     else {
         os << value.get() << ' ';
         output_unit<units::bps>::fn(os);
     }
     return os;
 }
operator<<() [6/7]
template<typename Value > std::ostream& inet::units::operator<< (std::ostream & os, const value< Value, units::Hz > & value)
 {
     if (value >= values::GHz(1.0))
         os << values::GHz(value);
     else if (value >= values::MHz(1.0))
         os << values::MHz(value);
     else if (value >= values::kHz(1.0))
         os << values::kHz(value);
     else {
         os << value.get() << ' ';
         output_unit<units::Hz>::fn(os);
     }
     return os;
 }
operator<<() [7/7]
template<typename Value > std::ostream& inet::units::operator<< (std::ostream & os, const value< Value, units::W > & value)
 {
     if (value == values::W(0))
         os << "0 W";
     else if (value > values::pW(-1000.0) && value < values::pW(1000.0))
         os << values::pW(value);
     else if (value > values::nW(-1000.0) && value < values::nW(1000.0))
         os << values::nW(value);
     else if (value > values::uW(-1000.0) && value < values::uW(1000.0))
         os << values::uW(value);
     else if (value > values::mW(-1000.0) && value < values::mW(1000.0))
         os << values::mW(value);
     else {
         os << value.get() << ' ';
         output_unit<units::W>::fn(os);
     }
     return os;
 }
raise()
template<int Num, int Den, typename Value , typename Unit > value<Value, pow<Unit, Num, Den> > inet::units::raise (const value< Value, Unit > & a)
 {
     return value<Value, pow<Unit, Num, Den>>(internal::fixed_power<Num, Den>::pow(a.get()));
 }
sin()
template<typename Value , typename Unit > Value inet::units::sin (const value< Value, Unit > & angle)
 {
     return std::sin(value<Value, units::rad>(angle).get());
 }
Referenced by inet::physicallayer::MpskModulation::calculateBER(), inet::physicallayer::MpskModulation::calculateSER(), inet::physicallayer::DipoleAntenna::AntennaGain::computeGain(), inet::physicallayer::DielectricObstacleLoss::computeReflectionLoss(), inet::physicallayer::TwoRayInterference::computeTwoRayInterference(), inet::osg::createAnnulusVertices(), inet::osg::createCircleVertices(), inet::Quaternion::getRotationAxisAndAngle(), inet::VehicleMobility::move(), inet::CircleMobility::move(), inet::Quaternion::Quaternion(), inet::visualizer::RadioCanvasVisualizer::refreshAntennaLobe(), inet::StaticConcentricMobility::setInitialPosition(), inet::StaticLinearMobility::setInitialPosition(), inet::VehicleMobility::setInitialPosition(), inet::GaussMarkovMobility::setTargetPosition(), and inet::Quaternion::slerp().
sqrt()
template<typename Value , typename Unit > value<Value, pow<Unit, 1, 2> > inet::units::sqrt (const value< Value, Unit > & a)
 {
     return value<Value, pow<Unit, 1, 2>>(std::sqrt(a.get()));
 }
Referenced by inet::physicallayer::MpskModulation::calculateBER(), inet::physicallayer::MqamModulationBase::calculateBER(), inet::physicallayer::Ieee80211NistErrorModel::calculatePe(), inet::physicallayer::MqamModulationBase::calculateSER(), inet::physicallayer::MpskModulation::calculateSER(), inet::physicallayer::QbpskModulation::calculateSER(), inet::physicallayer::BpskModulation::calculateSER(), inet::Sphere::computeIntersection(), inet::physicallayer::DielectricObstacleLoss::computeReflectionLoss(), inet::physicallayer::TwoRayInterference::computeTwoRayInterference(), inet::physicallayer::Ieee80211OfdmErrorModel::corruptOfdmSymbol(), inet::visualizer::SceneOsgVisualizerBase::createSceneFloor(), inet::physicallayer::Ieee80211NistErrorModel::get1024QamBer(), inet::physicallayer::Ieee80211NistErrorModel::get16QamBer(), inet::physicallayer::Ieee80211NistErrorModel::get256QamBer(), inet::physicallayer::Ieee80211NistErrorModel::get64QamBer(), inet::physicallayer::Ieee80211NistErrorModel::getBpskBer(), inet::physicallayer::Ieee80211YansErrorModel::getBpskBer(), inet::visualizer::VisualizerBase::getContactPosition(), inet::physicallayer::Ieee80211ErrorModelBase::getDsssDqpskSuccessRate(), inet::physicallayer::Ieee80211YansErrorModel::getQamBer(), inet::physicallayer::Ieee80211NistErrorModel::getQpskBer(), inet::physicalenvironment::Material::getRefractiveIndex(), inet::physicallayer::SpaceAndFrequencyDependentAttenuationFunction::getValue(), inet::physicallayer::SpaceDependentAttenuationFunction::getValue(), inet::physicallayer::PropagatedTransmissionPowerFunction::getValue(), inet::math::GaussFunction< R, X >::getValue(), inet::physicallayer::Ieee802154UwbIrReceiver::integrateWindow(), inet::Quaternion::length(), inet::Coord::length(), inet::physicallayer::PropagatedTransmissionPowerFunction::partition(), inet::utils::filters::StddevFilter::process(), inet::physicallayer::TwoRayInterference::reflectionCoefficient(), inet::Quaternion::rotationFromTo(), inet::GaussMarkovMobility::setTargetPosition(), inet::RotationMatrix::toEulerAngles(), and inet::RotationMatrix::toQuaternion().
tan()
template<typename Value , typename Unit > Value inet::units::tan (const value< Value, Unit > & angle)
 {
     return std::tan(value<Value, units::rad>(angle).get());
 }
UNIT_DISPLAY_NAME() [1/74]
inet::units::UNIT_DISPLAY_NAME (unit , "1")
UNIT_DISPLAY_NAME() [2/74]
inet::units::UNIT_DISPLAY_NAME (units::A , "A")
UNIT_DISPLAY_NAME() [3/74]
inet::units::UNIT_DISPLAY_NAME (units::acre , "acres")
UNIT_DISPLAY_NAME() [4/74]
inet::units::UNIT_DISPLAY_NAME (units::are , "are")
UNIT_DISPLAY_NAME() [5/74]
inet::units::UNIT_DISPLAY_NAME (units::b , "b")
UNIT_DISPLAY_NAME() [6/74]
inet::units::UNIT_DISPLAY_NAME (units::B , "B")
UNIT_DISPLAY_NAME() [7/74]
inet::units::UNIT_DISPLAY_NAME (units::bakers_dozen , "bakers dozen")
UNIT_DISPLAY_NAME() [8/74]
inet::units::UNIT_DISPLAY_NAME (units::bps , "bps")
UNIT_DISPLAY_NAME() [9/74]
inet::units::UNIT_DISPLAY_NAME (units::C , "C")
UNIT_DISPLAY_NAME() [10/74]
inet::units::UNIT_DISPLAY_NAME (units::cd , "cd")
UNIT_DISPLAY_NAME() [11/74]
inet::units::UNIT_DISPLAY_NAME (units::Celsius , "'C")
UNIT_DISPLAY_NAME() [12/74]
inet::units::UNIT_DISPLAY_NAME (units::century , "centuries")
UNIT_DISPLAY_NAME() [13/74]
inet::units::UNIT_DISPLAY_NAME (units::cl , "cl")
UNIT_DISPLAY_NAME() [14/74]
inet::units::UNIT_DISPLAY_NAME (units::cm , "cm")
UNIT_DISPLAY_NAME() [15/74]
inet::units::UNIT_DISPLAY_NAME (units::day , "days")
UNIT_DISPLAY_NAME() [16/74]
inet::units::UNIT_DISPLAY_NAME (units::deg , "deg")
UNIT_DISPLAY_NAME() [17/74]
inet::units::UNIT_DISPLAY_NAME (units::deg_min , "'")
UNIT_DISPLAY_NAME() [18/74]
inet::units::UNIT_DISPLAY_NAME (units::deg_sec , "\"")
UNIT_DISPLAY_NAME() [19/74]
inet::units::UNIT_DISPLAY_NAME (units::dl , "dl")
UNIT_DISPLAY_NAME() [20/74]
inet::units::UNIT_DISPLAY_NAME (units::dozen , "dozen")
UNIT_DISPLAY_NAME() [21/74]
inet::units::UNIT_DISPLAY_NAME (units::F , "F")
UNIT_DISPLAY_NAME() [22/74]
inet::units::UNIT_DISPLAY_NAME (units::Fahrenheit , "'F")
UNIT_DISPLAY_NAME() [23/74]
inet::units::UNIT_DISPLAY_NAME (units::foot , "foot")
UNIT_DISPLAY_NAME() [24/74]
inet::units::UNIT_DISPLAY_NAME (units::Gy , "Gy")
UNIT_DISPLAY_NAME() [25/74]
inet::units::UNIT_DISPLAY_NAME (units::H , "H")
UNIT_DISPLAY_NAME() [26/74]
inet::units::UNIT_DISPLAY_NAME (units::hectare , "ha")
UNIT_DISPLAY_NAME() [27/74]
inet::units::UNIT_DISPLAY_NAME (units::hour , "hours")
UNIT_DISPLAY_NAME() [28/74]
inet::units::UNIT_DISPLAY_NAME (units::Hz , "Hz")
UNIT_DISPLAY_NAME() [29/74]
inet::units::UNIT_DISPLAY_NAME (units::inch , "inches")
UNIT_DISPLAY_NAME() [30/74]
inet::units::UNIT_DISPLAY_NAME (units::J , "J")
UNIT_DISPLAY_NAME() [31/74]
inet::units::UNIT_DISPLAY_NAME (units::K , "K")
UNIT_DISPLAY_NAME() [32/74]
inet::units::UNIT_DISPLAY_NAME (units::kat , "kat")
UNIT_DISPLAY_NAME() [33/74]
inet::units::UNIT_DISPLAY_NAME (units::kg , "kg")
UNIT_DISPLAY_NAME() [34/74]
inet::units::UNIT_DISPLAY_NAME (units::km , "km")
UNIT_DISPLAY_NAME() [35/74]
inet::units::UNIT_DISPLAY_NAME (units::knot , "knots")
UNIT_DISPLAY_NAME() [36/74]
inet::units::UNIT_DISPLAY_NAME (units::kPa , "kPa")
UNIT_DISPLAY_NAME() [37/74]
inet::units::UNIT_DISPLAY_NAME (units::kph , "km/h")
UNIT_DISPLAY_NAME() [38/74]
inet::units::UNIT_DISPLAY_NAME (units::lb , "lb")
UNIT_DISPLAY_NAME() [39/74]
inet::units::UNIT_DISPLAY_NAME (units::liter , "l")
UNIT_DISPLAY_NAME() [40/74]
inet::units::UNIT_DISPLAY_NAME (units::lx , "lx")
UNIT_DISPLAY_NAME() [41/74]
inet::units::UNIT_DISPLAY_NAME (units::m , "m")
UNIT_DISPLAY_NAME() [42/74]
inet::units::UNIT_DISPLAY_NAME (units::mach , "mach")
UNIT_DISPLAY_NAME() [43/74]
inet::units::UNIT_DISPLAY_NAME (units::mile , "miles")
UNIT_DISPLAY_NAME() [44/74]
inet::units::UNIT_DISPLAY_NAME (units::millennium , "millennia")
UNIT_DISPLAY_NAME() [45/74]
inet::units::UNIT_DISPLAY_NAME (units::millibar , "millibars")
UNIT_DISPLAY_NAME() [46/74]
inet::units::UNIT_DISPLAY_NAME (units::minute , "minutes")
UNIT_DISPLAY_NAME() [47/74]
inet::units::UNIT_DISPLAY_NAME (units::ml , "ml")
UNIT_DISPLAY_NAME() [48/74]
inet::units::UNIT_DISPLAY_NAME (units::mm , "mm")
UNIT_DISPLAY_NAME() [49/74]
inet::units::UNIT_DISPLAY_NAME (units::mol , "mol")
UNIT_DISPLAY_NAME() [50/74]
inet::units::UNIT_DISPLAY_NAME (units::month , "months")
UNIT_DISPLAY_NAME() [51/74]
inet::units::UNIT_DISPLAY_NAME (units::mph , "mph")
UNIT_DISPLAY_NAME() [52/74]
inet::units::UNIT_DISPLAY_NAME (units::mps , "mps")
UNIT_DISPLAY_NAME() [53/74]
inet::units::UNIT_DISPLAY_NAME (units::N , "N")
UNIT_DISPLAY_NAME() [54/74]
inet::units::UNIT_DISPLAY_NAME (units::nautical_mile , "nautical miles")
UNIT_DISPLAY_NAME() [55/74]
inet::units::UNIT_DISPLAY_NAME (units::Ohm , "Ohm")
UNIT_DISPLAY_NAME() [56/74]
inet::units::UNIT_DISPLAY_NAME (units::oz , "oz")
UNIT_DISPLAY_NAME() [57/74]
inet::units::UNIT_DISPLAY_NAME (units::Pa , "Pa")
UNIT_DISPLAY_NAME() [58/74]
inet::units::UNIT_DISPLAY_NAME (units::percent , "%")
UNIT_DISPLAY_NAME() [59/74]
inet::units::UNIT_DISPLAY_NAME (units::ps , "ps")
UNIT_DISPLAY_NAME() [60/74]
inet::units::UNIT_DISPLAY_NAME (units::psi , "PSI")
UNIT_DISPLAY_NAME() [61/74]
inet::units::UNIT_DISPLAY_NAME (units::rad , "rad")
UNIT_DISPLAY_NAME() [62/74]
inet::units::UNIT_DISPLAY_NAME (units::rpm , "rpm")
UNIT_DISPLAY_NAME() [63/74]
inet::units::UNIT_DISPLAY_NAME (units::s , "s")
UNIT_DISPLAY_NAME() [64/74]
inet::units::UNIT_DISPLAY_NAME (units::S , "S")
UNIT_DISPLAY_NAME() [65/74]
inet::units::UNIT_DISPLAY_NAME (units::sr , "sr")
UNIT_DISPLAY_NAME() [66/74]
inet::units::UNIT_DISPLAY_NAME (units::T , "T")
UNIT_DISPLAY_NAME() [67/74]
inet::units::UNIT_DISPLAY_NAME (units::tonne , "tonnes")
UNIT_DISPLAY_NAME() [68/74]
inet::units::UNIT_DISPLAY_NAME (units::V , "V")
UNIT_DISPLAY_NAME() [69/74]
inet::units::UNIT_DISPLAY_NAME (units::W , "W")
UNIT_DISPLAY_NAME() [70/74]
inet::units::UNIT_DISPLAY_NAME (units::Wb , "Wb")
UNIT_DISPLAY_NAME() [71/74]
inet::units::UNIT_DISPLAY_NAME (units::week , "weeks")
UNIT_DISPLAY_NAME() [72/74]
inet::units::UNIT_DISPLAY_NAME (units::WpHz , "WpHz")
UNIT_DISPLAY_NAME() [73/74]
inet::units::UNIT_DISPLAY_NAME (units::yard , "yards")
UNIT_DISPLAY_NAME() [74/74]
inet::units::UNIT_DISPLAY_NAME (units::year , "years")