INET Framework for OMNeT++/OMNEST: inet::units::constants Namespace Reference
inet::units::constants Namespace Reference
Functions
const value< double, compose< units::J, pow< units::K, -1 > > > k (1.3806504e-23)
const value< double, units::kg > mu (1.660538782e-27)
const value< double, pow< units::mol, -1 > > NA (6.02214179e23)
const value< double, units::s > G0 (7.7480917004e-5)
const value< double, compose< units::F, pow< units::m, -1 > > > e0 (8.854187817e-12)
const value< double, units::kg > me (9.10938215e-31)
const value< double, units::J > eV (1.602176487e-19)
const value< double, units::C > e (1.602176487e-19)
const value< double, units::F > F (96485.3399)
const value< double, units::unit > alpha (7.2973525376e-3)
const value< double, units::unit > inv_alpha (137.035999679)
const value< double, compose< units::N, pow< units::A, -2 > > > u0 (12.566370614e-7)
const value< double, units::Wb > phi0 (2.067833667e-15)
const value< double, compose< units::J, compose< pow< units::mol, -1 >, pow< units::kg, -1 > > > > R (8.314472)
const value< double, compose< pow< units::m, 3 >, compose< pow< units::kg, -1 >, pow< units::s, -2 > > > > G (6.67428e-11)
const value< double, compose< units::J, units::s > > h (6.62606896e-34)
const value< double, compose< units::J, units::s > > h_bar (1.054571628e-34)
const value< double, units::kg > mp (1.672621637e-27)
const value< double, unit > mpme (1836.15267247)
const value< double, pow< units::m, -1 > > Rinf (10973731.568527)
const value< double, compose< units::m, pow< units::s, -1 > > > c (299792458)
const value< double, compose< units::W, compose< pow< units::m, -1 >, pow< units::K, -4 > > > > rho (5.6704e-8)
const value< double, units::rad > pi (3.141592653589793)
const value< double, units::m > lightyear (9.4605284e15)
const value< double, compose< units::m, pow< units::s, -2 > > > g (9.80665)
Function Documentation
alpha()
const value<double, units::unit> inet::units::constants::alpha (7.2973525376e- 3)
Referenced by inet::physicallayer::ParabolicAntenna::AntennaGain::computeGain(), inet::physicallayer::AxiallySymmetricAntenna::AntennaGain::computeGain(), inet::physicallayer::InterpolatingAntenna::AntennaGain::computeGain(), inet::EulerAngles::copy(), inet::EligibilityTimeMeter::emitNumTokenChangedSignal(), inet::physicallayer::AdditiveScrambler::eXOR(), inet::physicallayer::ConvolutionalCoder::eXOR(), inet::EulerAngles::getAlpha(), inet::FacingMobility::getCurrentAngularPosition(), inet::SuperpositioningMobility::getCurrentAngularPosition(), inet::visualizer::AnimationSpeedInterpolator::getCurrentAnimationSpeed(), inet::math::UnilinearFunction< R, D >::getValue(), inet::math::BilinearFunction< R, D >::getValue(), inet::AttachedMobility::initialize(), inet::MobilityBase::initializeOrientation(), inet::EulerAngles::isUnspecified(), inet::MassMobility::move(), inet::EulerAngles::normalize(), inet::EulerAngles::operator*(), inet::EulerAngles::operator+(), inet::EulerAngles::operator-(), inet::MovingMobilityBase::orient(), inet::physicalenvironment::PhysicalEnvironment::parseObjects(), inet::visualizer::SceneCanvasVisualizer::parseViewAngle(), inet::BarFigure::refreshDisplay(), inet::visualizer::PacketDropOsgVisualizer::setAlpha(), inet::visualizer::LinkBreakOsgVisualizer::setAlpha(), inet::visualizer::PathOsgVisualizerBase::setAlpha(), inet::visualizer::LinkOsgVisualizerBase::setAlpha(), inet::visualizer::TracingObstacleLossOsgVisualizer::setAlpha(), inet::visualizer::LinkBreakCanvasVisualizer::setAlpha(), inet::visualizer::PathCanvasVisualizerBase::setAlpha(), inet::visualizer::LinkCanvasVisualizerBase::setAlpha(), inet::EulerAngles::setAlpha(), inet::visualizer::PacketDropCanvasVisualizer::setAlpha(), inet::visualizer::TracingObstacleLossCanvasVisualizer::setAlpha(), inet::HeatMapPlotFigure::setLinearValue(), inet::LabeledLineFigure::updateLabelPosition(), and inet::LabeledPolylineFigure::updateLabelPosition().
c()
const value<double, compose<units::m, pow<units::s, -1> > > inet::units::constants::c (299792458)
Referenced by inet::AudioOutFile::addAudioStream(), inet::HeatMapPlotFigure::bakeValues(), inet::Rstp::compareRSTPData(), inet::Sphere::computeIntersection(), inet::Gpsr::computeIntersectionInsideLineSegments(), inet::HeatMapPlotFigure::getHeatColor(), inet::math::UnireciprocalFunction< R, D >::getIntegralFunctionValue(), inet::math::UnireciprocalFunction< R, D >::getMax(), inet::math::UnireciprocalFunction< R, D >::getMin(), inet::math::UnireciprocalFunction< R, D >::getValue(), inet::math::GaussFunction< R, X >::getValue(), inet::PatternMatcher::isInSet(), inet::utils::nedf_firstAvailableOrEmpty(), inet::utils::nedf_hasModule(), inet::AudioOutFile::open(), inet::Ipv6RoutingTable::RouteLessThan::operator()(), inet::Ipv4RoutingTable::RouteLessThan::operator()(), inet::opp_isdigit(), inet::opp_toupper(), inet::visualizer::SceneCanvasVisualizer::parseViewAngle(), inet::sctp::SctpAssociation::processAsconfArrived(), inet::MoBanCoordinator::readMobilityPatternFile(), inet::RoutingTableParser::readRoutingTableFromFile(), inet::RsvpTe::refreshResv(), inet::Quaternion::rotationFromTo(), inet::HeatMapPlotFigure::setBilinearValue(), inet::HeatMapPlotFigure::setConstantValue(), inet::HeatMapPlotFigure::setLinearValue(), inet::HeatMapPlotFigure::setPixelSafe(), inet::HeatMapPlotFigure::setValue(), inet::tcp::TcpLwip::tcp_event_recv(), inet::Int128::toString(), inet::L3AddressResolver::tryResolve(), and inet::AudioOutFile::write().
e()
const value<double, units::C> inet::units::constants::e (1.602176487e- 19)
Referenced by inet::Ipv4FlatNetworkConfigurator::addDefaultRoutes(), inet::utils::atod(), inet::utils::atoul(), inet::DhcpClient::bindLease(), inet::BvhTree::buildHierarchy(), inet::StreamRedundancyConfigurator::computeStreamSendersAndReceivers(), inet::MultiFieldClassifier::configureFilters(), inet::osg::createArrowheadGeometry(), inet::PatternMatcher::debugStrFrom(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::PatternMatcher::doMatch(), doParsimPacking(), inet::bgp::doParsimPacking(), inet::doParsimPacking(), inet::ospf::doParsimPacking(), inet::dymo::doParsimPacking(), inet::aodv::doParsimPacking(), inet::tcp::doParsimPacking(), inet::rtp::doParsimPacking(), inet::ospfv2::doParsimPacking(), inet::physicallayer::doParsimPacking(), inet::ieee80211::doParsimPacking(), inet::ospfv3::doParsimPacking(), doParsimUnpacking(), inet::bgp::doParsimUnpacking(), inet::doParsimUnpacking(), inet::ospf::doParsimUnpacking(), inet::dymo::doParsimUnpacking(), inet::aodv::doParsimUnpacking(), inet::tcp::doParsimUnpacking(), inet::rtp::doParsimUnpacking(), inet::ospfv2::doParsimUnpacking(), inet::physicallayer::doParsimUnpacking(), inet::ieee80211::doParsimUnpacking(), inet::ospfv3::doParsimUnpacking(), inet::Ipv4FlatNetworkConfigurator::fillRoutingTables(), inet::Ipv4RoutingTable::findBestMatchingMulticastRoute(), inet::NextHopRoutingTable::findBestMatchingRoute(), inet::Ipv4RoutingTable::findBestMatchingRoute(), inet::Chunk::getBinDumpLine(), inet::Ipv4RoutingTable::getGatewayForDestAddr(), inet::Chunk::getHexDumpLine(), inet::Ipv4RoutingTable::getInterfaceForDestAddr(), inet::NextHopRoutingTable::getNextHopForDestination(), inet::Ipv6RoutingTable::getNextHopForDestination(), inet::NextHopRoutingTable::getOutputInterfaceForDestination(), inet::Ipv6RoutingTable::getOutputInterfaceForDestination(), inet::NodeStatus::getStateByName(), inet::TurtleMobility::getValue(), inet::L3NetworkConfiguratorBase::getWirelessId(), inet::Dsdv::handleMessageWhenUp(), inet::InterfaceMatcher::InterfaceMatcher(), inet::ieee80211::Ieee80211Mac::isInterfaceRegistered(), inet::SelfDoc::kindToStr(), inet::PatternMatcher::matches(), inet::MatrixCloudDelayer::MatrixEntry::MatrixEntry(), inet::operator<<(), inet::DiffservUtil::parseInformationRate(), inet::PatternMatcher::parseLiteralString(), inet::RoutingTableParser::parseRouting(), inet::PatternMatcher::parseSet(), inet::PatternMatcher::patternPrefixMatches(), inet::PacketPrinter::printPacket(), inet::ScenarioManager::processCommand(), inet::L2NetworkConfigurator::readInterfaceConfiguration(), inet::Ipv4NetworkConfigurator::readInterfaceConfiguration(), inet::Ipv4NetworkConfigurator::readManualMulticastRouteConfiguration(), inet::Ipv4NetworkConfigurator::readManualRouteConfiguration(), inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration(), inet::DhcpMessageSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::PatternMatcher::setPattern(), inet::RealTimeScheduler::takeNextEvent(), and inet::Ipv6Address::tryParseAddrWithPrefix().
e0()
const value<double, compose<units::F, pow<units::m, -1> > > inet::units::constants::e0 (8.854187817e- 12)
Referenced by inet::physicalenvironment::Material::getDielectricLossTangent().
eV()
const value<double, units::J> inet::units::constants::eV (1.602176487e- 19)
F()
const value<double, units::F> inet::units::constants::F (96485. 3399)
Referenced by inet::units::internal::convert2< fscale< T, F >, U >::fn(), inet::units::internal::convert3< T, fscale< U, F > >::fn(), inet::units::internal::scaling_factor< fscale< U, F > >::fn(), and inet::units::internal::output_unit2< fscale< Unit, F > >::fn().
G()
const value<double, compose<pow<units::m, 3>, compose<pow<units::kg, -1>, pow<units::s, -2> > > > inet::units::constants::G (6.67428e- 11)
g()
const value<double, compose<units::m, pow<units::s, -2> > > inet::units::constants::g (9. 80665)
G0()
const value<double, units::s> inet::units::constants::G0 (7.7480917004e- 5)
h()
const value<double, compose<units::J, units::s> > inet::units::constants::h (6.62606896e- 34)
Referenced by inet::sctp::SctpChecksum::checksum(), inet::RsvpTe::evalNextHopInterface(), inet::operator<<(), inet::ieee80211::Dcf::originatorProcessFailedFrame(), inet::ieee80211::Hcf::originatorProcessFailedFrame(), inet::math::Rasterized2DFunction< R, X, Y >::partition(), inet::math::LeftCurryingFunction< R, C, DIMSC, D, DIMSD, E >::partition(), inet::math::RightCurryingFunction< R, C, DIMSC, D, DIMSD, E >::partition(), inet::tcp::pbuf_cat(), inet::tcp::pbuf_chain(), inet::RsvpTe::processHELLO_TIMER(), inet::RsvpTe::processHelloMsg(), inet::RsvpTe::readTrafficRouteFromXML(), inet::RsvpTe::removeHello(), inet::RsvpTe::setupHello(), and inet::RsvpTe::startHello().
h_bar()
const value<double, compose<units::J, units::s> > inet::units::constants::h_bar (1.054571628e- 34)
inv_alpha()
const value<double, units::unit> inet::units::constants::inv_alpha (137. 035999679)
k()
const value<double, compose<units::J, pow<units::K, -1> > > inet::units::constants::k (1.3806504e- 23)
lightyear()
const value<double, units::m> inet::units::constants::lightyear (9. 4605284e15)
me()
const value<double, units::kg> inet::units::constants::me (9.10938215e- 31)
mp()
const value<double, units::kg> inet::units::constants::mp (1.672621637e- 27)
mpme()
const value<double, unit> inet::units::constants::mpme (1836. 15267247)
mu()
const value<double, units::kg> inet::units::constants::mu (1.660538782e- 27)
NA()
const value<double, pow<units::mol, -1> > inet::units::constants::NA (6. 02214179e23)
phi0()
const value<double, units::Wb> inet::units::constants::phi0 (2.067833667e- 15)
pi()
const value<double, units::rad> inet::units::constants::pi (3. 141592653589793)
Referenced by inet::serializeIpv6NdOptions().
R()
const value<double, compose<units::J, compose<pow<units::mol, -1>, pow<units::kg, -1> > > > inet::units::constants::R (8. 314472)
Referenced by inet::math::Boxcar1DFunction< R, X >::Boxcar1DFunction(), inet::math::Boxcar2DFunction< R, X, Y >::Boxcar2DFunction(), inet::math::Rasterized2DFunction< R, X, Y >::call(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::call(), inet::math::ConstantFunction< R, D >::getIntegral(), inet::math::FunctionBase< R, Domain< X > >::getIntegral(), inet::math::UnireciprocalFunction< R, D >::getIntegral(), inet::math::FunctionBase< R, Domain< X > >::getMax(), inet::math::FunctionBase< R, Domain< X > >::getMin(), inet::math::Boxcar1DFunction< R, X >::getRange(), inet::math::Boxcar2DFunction< R, X, Y >::getRange(), inet::math::MemoizedFunction< R, D >::getValue(), inet::math::BilinearFunction< R, D >::getValue(), inet::math::UnireciprocalFunction< R, D >::getValue(), inet::math::ApproximatedFunction< R, D, DIMENSION, X >::getValue(), inet::math::SummedFunction< R, D >::getValue(), inet::math::Boxcar1DFunction< R, X >::getValue(), inet::math::Boxcar2DFunction< R, X, Y >::getValue(), inet::math::GaussFunction< R, X >::getValue(), inet::math::SawtoothFunction< R, X >::getValue(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::getValue(), inet::math::Rasterized2DFunction< R, X, Y >::getValue(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::getValue(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::getValue(), inet::math::IntegratedFunction< R, D, DIMS, RI, DI >::getValue(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::getValueInterpolatedAlongX(), inet::math::ConstantFunction< R, D >::isNonZero(), inet::math::UnilinearFunction< R, D >::isNonZero(), inet::math::BilinearFunction< R, D >::isNonZero(), inet::math::Boxcar1DFunction< R, X >::isNonZero(), inet::math::Boxcar2DFunction< R, X, Y >::isNonZero(), inet::math::AddedFunction< R, D >::partition(), inet::math::Combined2DFunction< R, X, Y >::partition(), inet::math::SummedFunction< R, D >::partition(), inet::math::Boxcar1DFunction< R, X >::partition(), inet::math::Boxcar2DFunction< R, X, Y >::partition(), inet::math::Extruded2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated1DFunction< R, X >::partition(), inet::math::Rasterized2DFunction< R, X, Y >::partition(), inet::math::PeriodicallyInterpolated2DFunction< R, X, Y >::partition(), inet::math::IntegratedFunction< R, Domain< X, Y >, DIMS, RI, Domain< X > >::partition(), and inet::math::FunctionBase< R, Domain< X > >::print().
rho()
const value<double, compose<units::W, compose<pow<units::m, -1>, pow<units::K, -4> > > > inet::units::constants::rho (5.6704e- 8)
Rinf()
const value<double, pow<units::m, -1> > inet::units::constants::Rinf (10973731. 568527)
u0()
const value<double, compose<units::N, pow<units::A, -2> > > inet::units::constants::u0 (12.566370614e- 7)