INET Framework for OMNeT++/OMNEST: inet::ospfv2 Namespace Reference
inet::ospfv2 Namespace Reference
Classes
class AsExternalLsa
struct AuthenticationKeyType
class DatabaseDescriptionHandler
struct DesignatedRouterId
class HelloHandler
struct HostRouteParameters
class IMessageHandler
class InterfaceStateBackup
class InterfaceStateDesignatedRouter
class InterfaceStateDown
class InterfaceStateLoopback
class InterfaceStateNotDesignatedRouter
class InterfaceStatePointToPoint
class InterfaceStateWaiting
struct Ipv4AddressRange
class LinkStateAcknowledgementHandler
class LinkStateRequestHandler
class LinkStateUpdateHandler
struct LsaKeyType
class LsaKeyType_Less
class LsaProcessingMarker
class LsaTrackingInfo
class MessageHandler
class Neighbor
class NeighborState
class NeighborStateAttempt
class NeighborStateDown
class NeighborStateExchange
class NeighborStateExchangeStart
class NeighborStateFull
class NeighborStateInit
class NeighborStateLoading
class NeighborStateTwoWay
class NetworkLsa
struct NextHop
class Ospfv2
Implements the OSPFv2 routing protocol.
class Ospfv2Area
class Ospfv2AsExternalLsa
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:201 by opp_msgtool.
class Ospfv2AsExternalLsaContents
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:191 by opp_msgtool.
class Ospfv2ConfigReader
Configuration reader for the OSPF module.
class Ospfv2DatabaseDescriptionPacket
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:220 by opp_msgtool.
struct Ospfv2DdOptions
Struct generated from inet/routing/ospfv2/Ospfv2Packet.msg:208 by opp_msgtool.
struct Ospfv2ExternalTosInfo
Struct generated from inet/routing/ospfv2/Ospfv2Packet.msg:177 by opp_msgtool.
class Ospfv2HelloPacket
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:61 by opp_msgtool.
class Ospfv2Interface
class Ospfv2InterfaceState
class Ospfv2Link
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:130 by opp_msgtool.
class Ospfv2LinkStateAcknowledgementPacket
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:256 by opp_msgtool.
class Ospfv2LinkStateRequestPacket
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:240 by opp_msgtool.
class Ospfv2LinkStateUpdatePacket
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:248 by opp_msgtool.
class Ospfv2Lsa
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:107 by opp_msgtool.
class Ospfv2LsaHeader
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:90 by opp_msgtool.
struct Ospfv2LsaRequest
Struct generated from inet/routing/ospfv2/Ospfv2Packet.msg:229 by opp_msgtool.
class Ospfv2NetworkLsa
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:159 by opp_msgtool.
struct Ospfv2Options
Struct generated from inet/routing/ospfv2/Ospfv2Packet.msg:33 by opp_msgtool.
class Ospfv2Packet
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:49 by opp_msgtool.
class Ospfv2PacketSerializer
Converts between Ospfv2Packet and binary (network byte order) OSPF data.
class Ospfv2RouterLsa
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:144 by opp_msgtool.
class Ospfv2RoutingTableEntry
class Ospfv2SummaryLsa
Class generated from inet/routing/ospfv2/Ospfv2Packet.msg:169 by opp_msgtool.
struct Ospfv2TosData
Struct generated from inet/routing/ospfv2/Ospfv2Packet.msg:122 by opp_msgtool.
class Router
All OSPF classes are in this namespace.
class RouterLsa
class RoutingInfo
class SummaryLsa
Typedefs
typedef unsigned long Metric
typedef Ipv4Address RouterId
typedef Ipv4Address AreaId
typedef Ipv4Address LinkStateId
Enumerations
enum Ospfv2TimerType {
INTERFACE_HELLO_TIMER = 0, INTERFACE_WAIT_TIMER = 1, INTERFACE_ACKNOWLEDGEMENT_TIMER = 3, NEIGHBOR_INACTIVITY_TIMER = 4,
NEIGHBOR_POLL_TIMER = 5, NEIGHBOR_DD_RETRANSMISSION_TIMER = 6, NEIGHBOR_UPDATE_RETRANSMISSION_TIMER = 7, NEIGHBOR_REQUEST_RETRANSMISSION_TIMER = 8,
DATABASE_AGE_TIMER = 9
}
Enum generated from inet/routing/ospfv2/Ospfv2Packet.msg:19 by opp_msgtool.
enum Ospfv2LsaType {
ROUTERLSA_TYPE = 1, NETWORKLSA_TYPE = 2, SUMMARYLSA_NETWORKS_TYPE = 3, SUMMARYLSA_ASBOUNDARYROUTERS_TYPE = 4,
AS_EXTERNAL_LSA_TYPE = 5
}
Enum generated from inet/routing/ospfv2/Ospfv2Packet.msg:78 by opp_msgtool.
enum LinkType { POINTTOPOINT_LINK = 1, TRANSIT_LINK = 2, STUB_LINK = 3, VIRTUAL_LINK = 4 }
Enum generated from inet/routing/ospfv2/Ospfv2Packet.msg:113 by opp_msgtool.
enum AuthenticationType { NULL_TYPE = 0, SIMPLE_PASSWORD_TYPE = 1, CRYTOGRAPHIC_TYPE = 2 }
Functions
std::ostream & operator<< (std::ostream &stream, const Ospfv2Interface &intf)
bool operator== (Neighbor::DdPacketId leftID, Neighbor::DdPacketId rightID)
bool operator!= (Neighbor::DdPacketId leftID, Neighbor::DdPacketId rightID)
Define_Module (Ospfv2)
void setOspfCrc (const Ptr< Ospfv2Packet > &ospfPacket, CrcMode crcMode)
void setLsaCrc (Ospfv2Lsa &lsa, CrcMode crcMode)
void setLsaHeaderCrc (Ospfv2LsaHeader &lsaHeader, CrcMode crcMode)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2TimerType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2TimerType &e)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv2Options &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv2Options &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2Options &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2Options &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2Packet &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2Packet &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2HelloPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2HelloPacket &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2LsaType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2LsaType &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2LsaHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2LsaHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2Lsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2Lsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const LinkType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, LinkType &e)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv2TosData &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv2TosData &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2TosData &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2TosData &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2Link &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2Link &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2RouterLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2RouterLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2NetworkLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2NetworkLsa &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2SummaryLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2SummaryLsa &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv2ExternalTosInfo &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv2ExternalTosInfo &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2ExternalTosInfo &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2ExternalTosInfo &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2AsExternalLsaContents &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2AsExternalLsaContents &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2AsExternalLsa &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2AsExternalLsa &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv2DdOptions &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv2DdOptions &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2DdOptions &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2DdOptions &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2DatabaseDescriptionPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2DatabaseDescriptionPacket &obj)
void INET_API __doPacking (omnetpp::cCommBuffer *b, const Ospfv2LsaRequest &a)
void INET_API __doUnpacking (omnetpp::cCommBuffer *b, Ospfv2LsaRequest &a)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2LsaRequest &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2LsaRequest &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2LinkStateRequestPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2LinkStateRequestPacket &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2LinkStateUpdatePacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2LinkStateUpdatePacket &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ospfv2LinkStateAcknowledgementPacket &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ospfv2LinkStateAcknowledgementPacket &obj)
Register_Serializer (Ospfv2Packet, Ospfv2PacketSerializer)
Register_Serializer (Ospfv2HelloPacket, Ospfv2PacketSerializer)
Register_Serializer (Ospfv2DatabaseDescriptionPacket, Ospfv2PacketSerializer)
Register_Serializer (Ospfv2LinkStateRequestPacket, Ospfv2PacketSerializer)
Register_Serializer (Ospfv2LinkStateUpdatePacket, Ospfv2PacketSerializer)
Register_Serializer (Ospfv2LinkStateAcknowledgementPacket, Ospfv2PacketSerializer)
bool operator< (const Ospfv2LsaHeader &leftLSA, const Ospfv2LsaHeader &rightLSA)
Returns true if leftLSA is older than rightLSA.
bool operator== (const Ospfv2LsaHeader &leftLSA, const Ospfv2LsaHeader &rightLSA)
Returns true if leftLSA is the same age as rightLSA.
bool operator== (const Ospfv2Options &leftOptions, const Ospfv2Options &rightOptions)
B calculateLSASize (const Ospfv2Lsa *lsa)
B calculateLsaSize (const Ospfv2RouterLsa &lsa)
B calculateLsaSize (const Ospfv2NetworkLsa &lsa)
B calculateLsaSize (const Ospfv2SummaryLsa &lsa)
B calculateLsaSize (const Ospfv2AsExternalLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2LsaRequest &request)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2LsaHeader &lsaHeader)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2NetworkLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2TosData &tos)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2Link &link)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2RouterLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2SummaryLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2ExternalTosInfo &tos)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2AsExternalLsaContents &contents)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2AsExternalLsa &lsa)
std::ostream & operator<< (std::ostream &ostr, const Ospfv2Lsa &lsa)
bool operator!= (const Ospfv2Options &leftOptions, const Ospfv2Options &rightOptions)
bool operator== (const NextHop &leftHop, const NextHop &rightHop)
bool operator!= (const NextHop &leftHop, const NextHop &rightHop)
std::ostream & operator<< (std::ostream &ostr, Ospfv2Area &area)
const RouterId NULL_ROUTERID (0, 0, 0, 0)
const AreaId BACKBONE_AREAID (0, 0, 0, 0)
const LinkStateId NULL_LINKSTATEID (0, 0, 0, 0)
const Ipv4Address NULL_IPV4ADDRESS (0, 0, 0, 0)
const Ipv4AddressRange NULL_IPV4ADDRESSRANGE (Ipv4Address(0, 0, 0, 0), Ipv4Address(0, 0, 0, 0))
Ipv4Address operator& (Ipv4Address address, Ipv4Address mask)
Ipv4Address operator| (Ipv4Address address, Ipv4Address match)
bool isSameNetwork (Ipv4Address address1, Ipv4Address mask1, Ipv4Address address2, Ipv4Address mask2)
bool operator== (DesignatedRouterId leftID, DesignatedRouterId rightID)
bool operator!= (DesignatedRouterId leftID, DesignatedRouterId rightID)
Ipv4Address ipv4AddressFromAddressString (const char *charForm)
Ipv4Address ipv4NetmaskFromAddressString (const char *charForm)
char hexCharToByte (char hex)
char hexPairToByte (char upperHex, char lowerHex)
std::ostream & operator<< (std::ostream &out, const Ospfv2RoutingTableEntry &entry)
Variables
const B IPV4_DATAGRAM_LENGTH = B(65536)
const B OSPFv2_HEADER_LENGTH = B(24)
const B OSPFv2_LSA_HEADER_LENGTH = B(20)
const B OSPFv2_HELLO_HEADER_LENGTH = B(20)
const B OSPFv2_DD_HEADER_LENGTH = B(8)
const B OSPFv2_REQUEST_LENGTH = B(12)
const B OSPFv2_ROUTERLSA_HEADER_LENGTH = B(4)
const B OSPFv2_LINK_HEADER_LENGTH = B(12)
const B OSPFv2_TOS_LENGTH = B(4)
const B OSPFv2_NETWORKLSA_MASK_LENGTH = B(4)
const B OSPFv2_NETWORKLSA_ADDRESS_LENGTH = B(4)
const B OSPFv2_SUMMARYLSA_HEADER_LENGTH = B(8)
const B OSPFv2_ASEXTERNALLSA_HEADER_LENGTH = B(4)
const B OSPFv2_ASEXTERNALLSA_TOS_INFO_LENGTH = B(12)
const DesignatedRouterId NULL_DESIGNATEDROUTERID
Typedef Documentation
AreaId
typedef Ipv4Address inet::ospfv2::AreaId
LinkStateId
typedef Ipv4Address inet::ospfv2::LinkStateId
Metric
typedef unsigned long inet::ospfv2::Metric
RouterId
typedef Ipv4Address inet::ospfv2::RouterId
Enumeration Type Documentation
AuthenticationType
enum inet::ospfv2::AuthenticationType
Enumerator
NULL_TYPE
SIMPLE_PASSWORD_TYPE
CRYTOGRAPHIC_TYPE
{
     NULL_TYPE            = 0,
     SIMPLE_PASSWORD_TYPE = 1,
     CRYTOGRAPHIC_TYPE    = 2
 };
LinkType
enum inet::ospfv2::LinkType
Enum generated from inet/routing/ospfv2/Ospfv2Packet.msg:113 by opp_msgtool.
enum LinkType
{
    POINTTOPOINT_LINK = 1;
    TRANSIT_LINK = 2;
    STUB_LINK = 3;
    VIRTUAL_LINK = 4;
}
Enumerator
POINTTOPOINT_LINK
TRANSIT_LINK
STUB_LINK
VIRTUAL_LINK
               {
     POINTTOPOINT_LINK = 1,
     TRANSIT_LINK = 2,
     STUB_LINK = 3,
     VIRTUAL_LINK = 4
 };
Ospfv2LsaType
enum inet::ospfv2::Ospfv2LsaType
Enum generated from inet/routing/ospfv2/Ospfv2Packet.msg:78 by opp_msgtool.
enum Ospfv2LsaType
{
    ROUTERLSA_TYPE = 1;
    NETWORKLSA_TYPE = 2;
    SUMMARYLSA_NETWORKS_TYPE = 3;
    SUMMARYLSA_ASBOUNDARYROUTERS_TYPE = 4;
    AS_EXTERNAL_LSA_TYPE = 5;
}
Enumerator
ROUTERLSA_TYPE
NETWORKLSA_TYPE
SUMMARYLSA_NETWORKS_TYPE
SUMMARYLSA_ASBOUNDARYROUTERS_TYPE
AS_EXTERNAL_LSA_TYPE
                    {
     ROUTERLSA_TYPE = 1,
     NETWORKLSA_TYPE = 2,
     SUMMARYLSA_NETWORKS_TYPE = 3,
     SUMMARYLSA_ASBOUNDARYROUTERS_TYPE = 4,
     AS_EXTERNAL_LSA_TYPE = 5
 };
Ospfv2TimerType
enum inet::ospfv2::Ospfv2TimerType
Enum generated from inet/routing/ospfv2/Ospfv2Packet.msg:19 by opp_msgtool.
enum Ospfv2TimerType
{
    INTERFACE_HELLO_TIMER = 0;
    INTERFACE_WAIT_TIMER = 1;
    INTERFACE_ACKNOWLEDGEMENT_TIMER = 3;
    NEIGHBOR_INACTIVITY_TIMER = 4;
    NEIGHBOR_POLL_TIMER = 5;
    NEIGHBOR_DD_RETRANSMISSION_TIMER = 6;
    NEIGHBOR_UPDATE_RETRANSMISSION_TIMER = 7;
    NEIGHBOR_REQUEST_RETRANSMISSION_TIMER = 8;
    DATABASE_AGE_TIMER = 9;
}
Enumerator
INTERFACE_HELLO_TIMER
INTERFACE_WAIT_TIMER
INTERFACE_ACKNOWLEDGEMENT_TIMER
NEIGHBOR_INACTIVITY_TIMER
NEIGHBOR_POLL_TIMER
NEIGHBOR_DD_RETRANSMISSION_TIMER
NEIGHBOR_UPDATE_RETRANSMISSION_TIMER
NEIGHBOR_REQUEST_RETRANSMISSION_TIMER
DATABASE_AGE_TIMER
                      {
     INTERFACE_HELLO_TIMER = 0,
     INTERFACE_WAIT_TIMER = 1,
     INTERFACE_ACKNOWLEDGEMENT_TIMER = 3,
     NEIGHBOR_INACTIVITY_TIMER = 4,
     NEIGHBOR_POLL_TIMER = 5,
     NEIGHBOR_DD_RETRANSMISSION_TIMER = 6,
     NEIGHBOR_UPDATE_RETRANSMISSION_TIMER = 7,
     NEIGHBOR_REQUEST_RETRANSMISSION_TIMER = 8,
     DATABASE_AGE_TIMER = 9
 };
Function Documentation
__doPacking() [1/5]
void INET_API inet::ospfv2::__doPacking (omnetpp::cCommBuffer * b, const Ospfv2DdOptions & a)
__doPacking() [2/5]
void INET_API inet::ospfv2::__doPacking (omnetpp::cCommBuffer * b, const Ospfv2ExternalTosInfo & a)
__doPacking() [3/5]
void INET_API inet::ospfv2::__doPacking (omnetpp::cCommBuffer * b, const Ospfv2LsaRequest & a)
__doPacking() [4/5]
void INET_API inet::ospfv2::__doPacking (omnetpp::cCommBuffer * b, const Ospfv2Options & a)
Referenced by doParsimPacking().
__doPacking() [5/5]
void INET_API inet::ospfv2::__doPacking (omnetpp::cCommBuffer * b, const Ospfv2TosData & a)
__doUnpacking() [1/5]
void INET_API inet::ospfv2::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv2DdOptions & a)
__doUnpacking() [2/5]
void INET_API inet::ospfv2::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv2ExternalTosInfo & a)
__doUnpacking() [3/5]
void INET_API inet::ospfv2::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv2LsaRequest & a)
__doUnpacking() [4/5]
void INET_API inet::ospfv2::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv2Options & a)
Referenced by doParsimUnpacking().
__doUnpacking() [5/5]
void INET_API inet::ospfv2::__doUnpacking (omnetpp::cCommBuffer * b, Ospfv2TosData & a)
BACKBONE_AREAID()
const AreaId inet::ospfv2::BACKBONE_AREAID (0 , 0 , 0 , 0)
Referenced by inet::ospfv2::Router::ageDatabase(), inet::ospfv2::Router::calculateASExternalRoutes(), inet::ospfv2::Ospfv2Area::calculateShortestPathTree(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::Ospfv2Area::hasVirtualLink(), inet::ospfv2::Router::installASExternalLSA(), inet::ospfv2::Ospfv2ConfigReader::loadAreaFromXML(), inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::MessageHandler::processPacket(), inet::ospfv2::Router::pruneASBoundaryRouterEntries(), inet::ospfv2::Router::rebuildRoutingTable(), inet::ospfv2::Ospfv2Area::recheckSummaryLSAs(), inet::ospfv2::Router::removeExternalRoute(), and inet::ospfv2::Router::updateExternalRoute().
calculateLsaSize() [1/4]
B inet::ospfv2::calculateLsaSize (const Ospfv2AsExternalLsa & lsa)
 {
     return OSPFv2_LSA_HEADER_LENGTH + OSPFv2_ASEXTERNALLSA_HEADER_LENGTH
            + (OSPFv2_ASEXTERNALLSA_TOS_INFO_LENGTH * lsa.getContents().getExternalTOSInfoArraySize());
 }
calculateLSASize()
B inet::ospfv2::calculateLSASize (const Ospfv2Lsa * lsa)
 {
     switch (lsa->getHeader().getLsType()) {
         case Ospfv2LsaType::ROUTERLSA_TYPE: {
             auto routerLsa = check_and_cast<const Ospfv2RouterLsa *>(lsa);
             return calculateLsaSize(*routerLsa);
         }
         case Ospfv2LsaType::NETWORKLSA_TYPE: {
             auto networkLsa = check_and_cast<const Ospfv2NetworkLsa *>(lsa);
             return calculateLsaSize(*networkLsa);
         }
         case Ospfv2LsaType::SUMMARYLSA_NETWORKS_TYPE:
         case Ospfv2LsaType::SUMMARYLSA_ASBOUNDARYROUTERS_TYPE: {
             auto summaryLsa = check_and_cast<const Ospfv2SummaryLsa *>(lsa);
             return calculateLsaSize(*summaryLsa);
         }
         case Ospfv2LsaType::AS_EXTERNAL_LSA_TYPE: {
             auto asExternalLsa = check_and_cast<const Ospfv2AsExternalLsa *>(lsa);
             return calculateLsaSize(*asExternalLsa);
         }
         default:
             throw cRuntimeError("Unknown LsaType value: %d", (int)lsa->getHeader().getLsType());
             break;
     }
 }
Referenced by inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), and inet::ospfv2::Neighbor::retransmitUpdatePacket().
calculateLsaSize() [2/4]
B inet::ospfv2::calculateLsaSize (const Ospfv2NetworkLsa & lsa)
 {
     return OSPFv2_LSA_HEADER_LENGTH + OSPFv2_NETWORKLSA_MASK_LENGTH
            + (OSPFv2_NETWORKLSA_ADDRESS_LENGTH * lsa.getAttachedRoutersArraySize());
 }
calculateLsaSize() [3/4]
B inet::ospfv2::calculateLsaSize (const Ospfv2RouterLsa & lsa)
 {
     B lsaLength = OSPFv2_LSA_HEADER_LENGTH + OSPFv2_ROUTERLSA_HEADER_LENGTH;
     for (uint32_t i = 0; i < lsa.getLinksArraySize(); i++) {
         const auto& link = lsa.getLinks(i);
         lsaLength += OSPFv2_LINK_HEADER_LENGTH + (OSPFv2_TOS_LENGTH * link.getTosDataArraySize());
     }
     return lsaLength;
 }
Referenced by calculateLSASize(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Router::updateExternalRoute().
calculateLsaSize() [4/4]
B inet::ospfv2::calculateLsaSize (const Ospfv2SummaryLsa & lsa)
 {
     return OSPFv2_LSA_HEADER_LENGTH + OSPFv2_SUMMARYLSA_HEADER_LENGTH
            + (OSPFv2_TOS_LENGTH * lsa.getTosDataArraySize());
 }
Define_Module()
inet::ospfv2::Define_Module (Ospfv2)
doParsimPacking() [1/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const LinkType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [2/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2AsExternalLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [3/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2AsExternalLsaContents & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [4/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2DatabaseDescriptionPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [5/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2DdOptions & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [6/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2ExternalTosInfo & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [7/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2HelloPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [8/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2Link & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [9/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2LinkStateAcknowledgementPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [10/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2LinkStateRequestPacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [11/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2LinkStateUpdatePacket & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [12/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2Lsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [13/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2LsaHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [14/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2LsaRequest & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [15/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2LsaType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [16/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2NetworkLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [17/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2Options & obj) inline
 { __doPacking(b, obj); }
doParsimPacking() [18/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2Packet & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [19/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2RouterLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [20/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2SummaryLsa & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [21/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2TimerType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [22/22]
void inet::ospfv2::doParsimPacking (omnetpp::cCommBuffer * b, const Ospfv2TosData & obj) inline
 { __doPacking(b, obj); }
doParsimUnpacking() [1/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, LinkType & e) inline
 { int n; b->unpack(n); e = static_cast<LinkType>(n); }
doParsimUnpacking() [2/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2AsExternalLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [3/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2AsExternalLsaContents & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [4/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2DatabaseDescriptionPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [5/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2DdOptions & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [6/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2ExternalTosInfo & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [7/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2HelloPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [8/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2Link & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [9/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2LinkStateAcknowledgementPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [10/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2LinkStateRequestPacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [11/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2LinkStateUpdatePacket & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [12/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2Lsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [13/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2LsaHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [14/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2LsaRequest & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [15/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2LsaType & e) inline
 { int n; b->unpack(n); e = static_cast<Ospfv2LsaType>(n); }
doParsimUnpacking() [16/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2NetworkLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [17/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2Options & obj) inline
 { __doUnpacking(b, obj); }
doParsimUnpacking() [18/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2Packet & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [19/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2RouterLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [20/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2SummaryLsa & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [21/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2TimerType & e) inline
 { int n; b->unpack(n); e = static_cast<Ospfv2TimerType>(n); }
doParsimUnpacking() [22/22]
void inet::ospfv2::doParsimUnpacking (omnetpp::cCommBuffer * b, Ospfv2TosData & obj) inline
 { __doUnpacking(b, obj); }
hexCharToByte()
char inet::ospfv2::hexCharToByte (char hex) inline
 {
     switch (hex) {
         case '0':
             return 0;
         case '1':
             return 1;
         case '2':
             return 2;
         case '3':
             return 3;
         case '4':
             return 4;
         case '5':
             return 5;
         case '6':
             return 6;
         case '7':
             return 7;
         case '8':
             return 8;
         case '9':
             return 9;
         case 'A':
             return 10;
         case 'B':
             return 11;
         case 'C':
             return 12;
         case 'D':
             return 13;
         case 'E':
             return 14;
         case 'F':
             return 15;
         case 'a':
             return 10;
         case 'b':
             return 11;
         case 'c':
             return 12;
         case 'd':
             return 13;
         case 'e':
             return 14;
         case 'f':
             return 15;
         default:
             break;
     }
     return 0;
 }
Referenced by hexPairToByte().
hexPairToByte()
char inet::ospfv2::hexPairToByte (char upperHex, char lowerHex) inline
 {
     return (hexCharToByte(upperHex) << 4) & (hexCharToByte(lowerHex));
 }
Referenced by inet::ospfv2::Ospfv2ConfigReader::loadAuthenticationConfig().
ipv4AddressFromAddressString()
Ipv4Address inet::ospfv2::ipv4AddressFromAddressString (const char * charForm) inline
 {
     return L3AddressResolver().resolve(charForm, L3AddressResolver::ADDR_IPv4).toIpv4();
 }
Referenced by inet::ospfv2::Ospfv2ConfigReader::initiateDefaultRouteDistribution(), inet::ospfv2::Ospfv2ConfigReader::loadAreaFromXML(), inet::ospfv2::Ospfv2ConfigReader::loadExternalRoute(), inet::ospfv2::Ospfv2ConfigReader::loadHostRoute(), inet::ospfv2::Ospfv2ConfigReader::loadInterfaceParameters(), inet::ospfv2::Ospfv2ConfigReader::loadLoopbackParameters(), and inet::ospfv2::Ospfv2ConfigReader::loadVirtualLink().
ipv4NetmaskFromAddressString()
Ipv4Address inet::ospfv2::ipv4NetmaskFromAddressString (const char * charForm) inline
 {
     return L3AddressResolver().resolve(charForm, L3AddressResolver::ADDR_IPv4 | L3AddressResolver::ADDR_MASK).toIpv4();
 }
Referenced by inet::ospfv2::Ospfv2ConfigReader::initiateDefaultRouteDistribution(), inet::ospfv2::Ospfv2ConfigReader::loadAreaFromXML(), and inet::ospfv2::Ospfv2ConfigReader::loadExternalRoute().
isSameNetwork()
bool inet::ospfv2::isSameNetwork (Ipv4Address address1, Ipv4Address mask1, Ipv4Address address2, Ipv4Address mask2) inline
 {
     return (mask1 == mask2) && ((address1 & mask1) == (address2 & mask2));
 }
Referenced by inet::ospfv2::Ospfv2Area::calculateNextHops(), and inet::ospfv2::Ospfv2Area::originateSummaryLSA().
NULL_IPV4ADDRESS()
const Ipv4Address inet::ospfv2::NULL_IPV4ADDRESS (0 , 0 , 0 , 0)
Referenced by inet::ospfv2::Ospfv2Area::calculateNextHops(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::HelloHandler::processPacket(), and inet::ospfv2::Ospfv2Interface::sendHelloPacket().
NULL_IPV4ADDRESSRANGE()
const Ipv4AddressRange inet::ospfv2::NULL_IPV4ADDRESSRANGE (Ipv4Address(0, 0, 0, 0) , Ipv4Address(0, 0, 0, 0))
Referenced by inet::ospfv2::Ospfv2Area::addAddressRange(), inet::ospfv2::Ospfv2Area::getContainingAddressRange(), inet::ospfv2::Router::getContainingAddressRange(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), and inet::ospfv2::Ospfv2Area::originateSummaryLSA().
NULL_LINKSTATEID()
const LinkStateId inet::ospfv2::NULL_LINKSTATEID (0 , 0 , 0 , 0)
NULL_ROUTERID()
const RouterId inet::ospfv2::NULL_ROUTERID (0 , 0 , 0 , 0)
Referenced by inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter().
operator!=() [1/4]
bool inet::ospfv2::operator!= (const NextHop & leftHop, const NextHop & rightHop) inline
 {
     return !(leftHop == rightHop);
 }
operator!=() [2/4]
bool inet::ospfv2::operator!= (const Ospfv2Options & leftOptions, const Ospfv2Options & rightOptions) inline
 {
     return !(leftOptions == rightOptions);
 }
operator!=() [3/4]
bool inet::ospfv2::operator!= (DesignatedRouterId leftID, DesignatedRouterId rightID) inline
 {
     return !(leftID == rightID);
 }
operator!=() [4/4]
bool inet::ospfv2::operator!= (Neighbor::DdPacketId leftID, Neighbor::DdPacketId rightID) inline
 {
     return !(leftID == rightID);
 }
operator&()
Ipv4Address inet::ospfv2::operator& (Ipv4Address address, Ipv4Address mask) inline
 {
     Ipv4Address maskedAddress;
     maskedAddress.set(address.getInt() & mask.getInt());
     return maskedAddress;
 }
operator<()
bool inet::ospfv2::operator< (const Ospfv2LsaHeader & leftLSA, const Ospfv2LsaHeader & rightLSA)
Returns true if leftLSA is older than rightLSA.
 {
     long leftSequenceNumber = leftLSA.getLsSequenceNumber();
     long rightSequenceNumber = rightLSA.getLsSequenceNumber();
     if (leftSequenceNumber > rightSequenceNumber)
         return false;
     else if (leftSequenceNumber < rightSequenceNumber)
         return true;
     else {
         // TODO checksum comparison should be added here
         unsigned short leftAge = leftLSA.getLsAge();
         unsigned short rightAge = rightLSA.getLsAge();
         if ((leftAge != MAX_AGE) && (rightAge == MAX_AGE))
             return true;
         else if ((leftAge == MAX_AGE) && (rightAge != MAX_AGE))
             return false;
         else if ((abs(leftAge - rightAge) > MAX_AGE_DIFF) && (leftAge > rightAge))
             return true;
     }
     return false;
 }
operator<<() [1/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2AsExternalLsa & lsa)
 {
     ostr << lsa.getHeader() << lsa.getContents();
     return ostr;
 }
operator<<() [2/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2AsExternalLsaContents & contents)
 {
     ostr << "Mask: " << contents.getNetworkMask()
          << ", ";
     unsigned int cnt = contents.getExternalTOSInfoArraySize();
     if (cnt) {
         ostr << ", tosData: {";
         for (unsigned int i = 0; i < cnt; i++) {
             if (i)
                 ostr << ", ";
             ostr << contents.getExternalTOSInfo(i);
         }
         ostr << "}";
     }
     return ostr;
 }
operator<<() [3/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2ExternalTosInfo & tos)
 {
     ostr << "Tos: {" << tos.tos
          << "}, MetricType: " << tos.E_ExternalMetricType
          << ", fwAddr: " << tos.forwardingAddress
          << ", extRouteTag: " << tos.externalRouteTag;
     return ostr;
 }
operator<<() [4/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2Link & link)
 {
     ostr << "ID: " << link.getLinkID().str(false)
          << ", data: ";
     unsigned long data = link.getLinkData();
     if ((data & 0xFF000000) != 0)
         ostr << Ipv4Address(data);
     else
         ostr << data;
     ostr << ", type=";
     switch (link.getType()) {
         case POINTTOPOINT_LINK:
             ostr << "PointToPoint";
             break;
         case TRANSIT_LINK:
             ostr << "Transit";
             break;
         case STUB_LINK:
             ostr << "Stub";
             break;
         case VIRTUAL_LINK:
             ostr << "Virtual";
             break;
         default:
             ostr << "Unknown";
             break;
     }
     ostr << ", cost: " << link.getLinkCost();
     unsigned int cnt = link.getTosDataArraySize();
     if (cnt) {
         ostr << ", tos: {";
         for (unsigned int i = 0; i < cnt; i++) {
             if (i)
                 ostr << ", ";
             ostr << link.getTosData(i);
         }
         ostr << "}";
     }
     return ostr;
 }
operator<<() [5/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2Lsa & lsa)
 {
     ASSERT(lsa.getHeader().getLsCrcMode() != CrcMode::CRC_MODE_UNDEFINED);
     ASSERT(lsa.getHeader().getLsaLength() != 0);
     switch (lsa.getHeader().getLsType()) {
         case ROUTERLSA_TYPE:
             ostr << *check_and_cast<const RouterLsa *>(&lsa);
             break;
         case NETWORKLSA_TYPE:
             ostr << *check_and_cast<const NetworkLsa *>(&lsa);
             break;
         case SUMMARYLSA_NETWORKS_TYPE:
         case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
             ostr << *check_and_cast<const SummaryLsa *>(&lsa);
             break;
         case AS_EXTERNAL_LSA_TYPE:
             ostr << *check_and_cast<const AsExternalLsa *>(&lsa);
             break;
         default:
             ostr << lsa.getHeader();
             ostr << ", Unknown";
             break;
     }
     return ostr;
 }
operator<<() [6/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2LsaHeader & lsaHeader)
 {
     ostr << "LSAHeader (age: " << lsaHeader.getLsAge()
          << ", type: ";
     switch (lsaHeader.getLsType()) {
         case ROUTERLSA_TYPE:
             ostr << "RouterLsa";
             break;
         case NETWORKLSA_TYPE:
             ostr << "NetworkLsa";
             break;
         case SUMMARYLSA_NETWORKS_TYPE:
             ostr << "SummaryLSA_Networks";
             break;
         case SUMMARYLSA_ASBOUNDARYROUTERS_TYPE:
             ostr << "SummaryLSA_ASBoundaryRouters";
             break;
         case AS_EXTERNAL_LSA_TYPE:
             ostr << "AsExternalLsa";
             break;
         default:
             ostr << "Unknown";
             break;
     }
     ostr << ", LSID: " << lsaHeader.getLinkStateID().str(false)
          << ", advertisingRouter: " << lsaHeader.getAdvertisingRouter().str(false)
          << ", seqNumber: " << lsaHeader.getLsSequenceNumber();
     ostr << ")";
     return ostr;
 }
operator<<() [7/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2LsaRequest & request)
 {
     ostr << "type=" << request.lsType
          << ", LSID=" << request.linkStateID
          << ", advertisingRouter=" << request.advertisingRouter;
     return ostr;
 }
operator<<() [8/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2NetworkLsa & lsa)
 {
     unsigned int cnt = lsa.getAttachedRoutersArraySize();
     ostr << lsa.getHeader();
     ostr << ", numAttachedRouters: " << cnt;
     if (cnt) {
         ostr << ", Attached routers: {";
         for (unsigned int i = 0; i < cnt; i++) {
             if (i)
                 ostr << ", ";
             ostr << lsa.getAttachedRouters(i);
         }
         ostr << "}";
     }
     ostr << ", Mask: " << lsa.getNetworkMask();
     return ostr;
 }
operator<<() [9/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2RouterLsa & lsa)
 {
     ostr << lsa.getHeader()
          << ", flags: "
          << (lsa.getV_VirtualLinkEndpoint() ? "V" : "_")
          << (lsa.getE_ASBoundaryRouter() ? "E" : "_")
          << (lsa.getB_AreaBorderRouter() ? "B" : "_")
          << ", numberOfLinks: " << lsa.getNumberOfLinks() << ", ";
     unsigned int cnt = lsa.getLinksArraySize();
     if (cnt) {
         ostr << "Links: {";
         for (unsigned int i = 0; i < cnt; i++) {
             if (i)
                 ostr << ",";
             ostr << " {" << lsa.getLinks(i) << "}";
         }
         ostr << "}";
     }
     return ostr;
 }
operator<<() [10/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2SummaryLsa & lsa)
 {
     ostr << lsa.getHeader();
     ostr << ", Mask: " << lsa.getNetworkMask().str(false)
          << ", Cost: " << lsa.getRouteCost() << ", ";
     unsigned int cnt = lsa.getTosDataArraySize();
     if (cnt) {
         ostr << ", tosData: {";
         for (unsigned int i = 0; i < cnt; i++) {
             if (i)
                 ostr << ", ";
             ostr << lsa.getTosData(i);
         }
         ostr << "}";
     }
     return ostr;
 }
operator<<() [11/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & ostr, const Ospfv2TosData & tos)
 {
     ostr << "tos: " << (int)tos.tos
          << "metric: " << tos.tosMetric;
     return ostr;
 }
operator<<() [12/14]
std::ostream& inet::ospfv2::operator<< (std::ostream & ostr, Ospfv2Area & area) inline
 {
     ostr << area.info();
     return ostr;
 }
operator<<() [13/14]
std::ostream & inet::ospfv2::operator<< (std::ostream & out, const Ospfv2RoutingTableEntry & entry)
 {
     if (entry.getDestination().isUnspecified())
         out << "0.0.0.0";
     else
         out << entry.getDestination();
     out << "/";
     if (entry.getNetmask().isUnspecified())
         out << "0";
     else
         out << entry.getNetmask().getNetmaskLength();
     out << " nextHops: ";
     for (unsigned int i = 0; i < entry.getNextHopCount(); i++) {
         Ipv4Address gateway = entry.getNextHop(i).hopAddress;
         if (gateway.isUnspecified())
             out << "*  ";
         else
             out << gateway << "  ";
     }
     out << "cost: " << entry.getCost() << " ";
     if (entry.getPathType() == Ospfv2RoutingTableEntry::TYPE2_EXTERNAL)
         out << "type2Cost: " << entry.getType2Cost() << " ";
     out << "if: " << entry.getInterfaceName() << " ";
     out << "destType: " << Ospfv2RoutingTableEntry::getDestinationTypeString(entry.getDestinationType());
     out << " area: " << entry.getArea().str(false) << " ";
     out << "pathType: " << Ospfv2RoutingTableEntry::getPathTypeString(entry.getPathType()) << " ";
     out << "Origin: [" << entry.getLinkStateOrigin()->getHeader() << "] ";
     return out;
 }
operator<<() [14/14]
std::ostream& inet::ospfv2::operator<< (std::ostream & stream, const Ospfv2Interface & intf)
 {
     std::string neighbors = "";
     for (auto& neighbor : intf.neighboringRoutersByID) {
         std::string neighborState = Neighbor::getStateString((neighbor.second)->getState());
         neighbors = neighbors + (neighbor.first).str() + "(" + neighborState + ") ";
     }
     return stream << "name: " << intf.getInterfaceName() << " "
                   << "index: " << intf.ifIndex << " "
                   << "type: '" << intf.getTypeString(intf.interfaceType) << "' "
                   << "MTU: " << intf.mtu << " "
                   << "state: '" << intf.getStateString(intf.state->getState()) << "' "
                   << "mode: '" << intf.getModeString(intf.interfaceMode) << "' "
                   << "cost: " << intf.interfaceOutputCost << " "
                   << "area: " << intf.areaID.str(false) << " "
                   << "transitArea: " << intf.transitAreaID.str(false) << " "
                   << "helloInterval: " << intf.helloInterval << " "
                   << "pollInterval: " << intf.pollInterval << " "
                   << "routerDeadInterval: " << intf.routerDeadInterval << " "
                   << "retransmissionInterval: " << intf.retransmissionInterval << " "
                   << "acknowledgementDelay: " << intf.acknowledgementDelay << " "
                   << "interfaceTransmissionDelay: " << intf.interfaceTransmissionDelay << " "
                   << "neighboringRouters: " << ((neighbors == "") ? "<none>(down)" : neighbors) << " "
                   << "routerPriority: " << (int)(intf.routerPriority) << " "
                   << "designatedRouterID: " << intf.designatedRouter.routerID << " "
                   << "designatedRouterInterface: " << intf.designatedRouter.ipInterfaceAddress << " "
                   << "backupDesignatedRouterID: " << intf.backupDesignatedRouter.routerID << " "
                   << "backupDesignatedRouterInterface: " << intf.backupDesignatedRouter.ipInterfaceAddress;
 }
operator==() [1/5]
bool inet::ospfv2::operator== (const NextHop & leftHop, const NextHop & rightHop) inline
 {
     return (leftHop.ifIndex == rightHop.ifIndex) &&
            (leftHop.hopAddress == rightHop.hopAddress) &&
            (leftHop.advertisingRouter == rightHop.advertisingRouter);
 }
operator==() [2/5]
bool inet::ospfv2::operator== (const Ospfv2LsaHeader & leftLSA, const Ospfv2LsaHeader & rightLSA)
Returns true if leftLSA is the same age as rightLSA.
 {
     long leftSequenceNumber = leftLSA.getLsSequenceNumber();
     long rightSequenceNumber = rightLSA.getLsSequenceNumber();
     unsigned short leftAge = leftLSA.getLsAge();
     unsigned short rightAge = rightLSA.getLsAge();
     if ((leftSequenceNumber == rightSequenceNumber) &&
         (((leftAge == MAX_AGE) && (rightAge == MAX_AGE)) ||
          (((leftAge != MAX_AGE) && (rightAge != MAX_AGE)) &&
           (abs(leftAge - rightAge) <= MAX_AGE_DIFF))))
     {
         return true;
     }
     else {
         return false;
     }
 }
operator==() [3/5]
bool inet::ospfv2::operator== (const Ospfv2Options & leftOptions, const Ospfv2Options & rightOptions)
 {
     return (leftOptions.E_ExternalRoutingCapability == rightOptions.E_ExternalRoutingCapability) &&
            (leftOptions.MC_MulticastForwarding == rightOptions.MC_MulticastForwarding) &&
            (leftOptions.NP_Type7LSA == rightOptions.NP_Type7LSA) &&
            (leftOptions.EA_ForwardExternalLSAs == rightOptions.EA_ForwardExternalLSAs) &&
            (leftOptions.DC_DemandCircuits == rightOptions.DC_DemandCircuits);
 }
operator==() [4/5]
bool inet::ospfv2::operator== (DesignatedRouterId leftID, DesignatedRouterId rightID) inline
 {
     return leftID.routerID == rightID.routerID &&
            leftID.ipInterfaceAddress == rightID.ipInterfaceAddress;
 }
operator==() [5/5]
bool inet::ospfv2::operator== (Neighbor::DdPacketId leftID, Neighbor::DdPacketId rightID) inline
 {
     return (leftID.ddOptions.I_Init == rightID.ddOptions.I_Init) &&
            (leftID.ddOptions.M_More == rightID.ddOptions.M_More) &&
            (leftID.ddOptions.MS_MasterSlave == rightID.ddOptions.MS_MasterSlave) &&
            (leftID.options == rightID.options) &&
            (leftID.sequenceNumber == rightID.sequenceNumber);
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::processPacket().
operator|()
Ipv4Address inet::ospfv2::operator| (Ipv4Address address, Ipv4Address match) inline
 {
     Ipv4Address matchAddress;
     matchAddress.set(address.getInt() | match.getInt());
     return matchAddress;
 }
Register_Serializer() [1/6]
inet::ospfv2::Register_Serializer (Ospfv2DatabaseDescriptionPacket , Ospfv2PacketSerializer)
Register_Serializer() [2/6]
inet::ospfv2::Register_Serializer (Ospfv2HelloPacket , Ospfv2PacketSerializer)
Register_Serializer() [3/6]
inet::ospfv2::Register_Serializer (Ospfv2LinkStateAcknowledgementPacket , Ospfv2PacketSerializer)
Register_Serializer() [4/6]
inet::ospfv2::Register_Serializer (Ospfv2LinkStateRequestPacket , Ospfv2PacketSerializer)
Register_Serializer() [5/6]
inet::ospfv2::Register_Serializer (Ospfv2LinkStateUpdatePacket , Ospfv2PacketSerializer)
Register_Serializer() [6/6]
inet::ospfv2::Register_Serializer (Ospfv2Packet , Ospfv2PacketSerializer)
setLsaCrc()
INET_API void inet::ospfv2::setLsaCrc (Ospfv2Lsa & lsa, CrcMode crcMode)
 {
     auto& lsaHeader = lsa.getHeaderForUpdate();
     lsaHeader.setLsCrcMode(crcMode);
     switch (crcMode) {
         case CrcMode::CRC_DECLARED_CORRECT:
             lsaHeader.setLsCrc(0xC00D);
             break;
         case CrcMode::CRC_DECLARED_INCORRECT:
             lsaHeader.setLsCrc(0xBAAD);
             break;
         case CrcMode::CRC_COMPUTED: {
             lsaHeader.setLsCrc(0);
             MemoryOutputStream stream;
             auto lsAge = lsaHeader.getLsAge();
             lsaHeader.setLsAge(0); // disable lsAge from CRC
             Ospfv2PacketSerializer::serializeLsa(stream, lsa);
             uint16_t crc = TcpIpChecksum::checksum(stream.getData());
             lsaHeader.setLsAge(lsAge); // restore lsAge
             lsaHeader.setLsCrc(crc);
             break;
         }
         default:
             throw cRuntimeError("Unknown CRC mode: %d", (int)crcMode);
     }
 }
Referenced by inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Ospfv2Area::originateNetworkLSA(), inet::ospfv2::Ospfv2Area::originateRouterLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA(), inet::ospfv2::Ospfv2Area::originateSummaryLSA_Stub(), and inet::ospfv2::Neighbor::retransmitUpdatePacket().
setLsaHeaderCrc()
INET_API void inet::ospfv2::setLsaHeaderCrc (Ospfv2LsaHeader & lsaHeader, CrcMode crcMode)
 {
     lsaHeader.setLsCrcMode(crcMode);
     switch (crcMode) {
         case CrcMode::CRC_DECLARED_CORRECT:
             lsaHeader.setLsCrc(0xC00D);
             break;
         case CrcMode::CRC_DECLARED_INCORRECT:
             lsaHeader.setLsCrc(0xBAAD);
             break;
         case CrcMode::CRC_COMPUTED: {
             lsaHeader.setLsCrc(0);
             MemoryOutputStream stream;
             auto lsAge = lsaHeader.getLsAge();
             lsaHeader.setLsAge(0); // disable lsAge from CRC
             Ospfv2PacketSerializer::serializeLsaHeader(stream, lsaHeader);
             uint16_t crc = TcpIpChecksum::checksum(stream.getData());
             lsaHeader.setLsAge(lsAge); // restore lsAge
             lsaHeader.setLsCrc(crc);
             break;
         }
         default:
             throw cRuntimeError("Unknown CRC mode: %d", (int)crcMode);
     }
 }
Referenced by inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket().
setOspfCrc()
INET_API void inet::ospfv2::setOspfCrc (const Ptr< Ospfv2Packet > & ospfPacket, CrcMode crcMode)
 {
     ospfPacket->setCrcMode(crcMode);
     switch (crcMode) {
         case CrcMode::CRC_DECLARED_CORRECT:
             ospfPacket->setCrc(0xC00D);
             break;
         case CrcMode::CRC_DECLARED_INCORRECT:
             ospfPacket->setCrc(0xBAAD);
             break;
         case CrcMode::CRC_COMPUTED: {
             AuthenticationKeyType authenticationKey;
             ospfPacket->setCrc(0);
             // RFC 2328: OSPF checksum is calculated over the entire OSPF packet, excluding the 64-bit authentication field.
             for (int i = 0; i < 8; i++) {
                 authenticationKey.bytes[i] = ospfPacket->getAuthentication(i);
                 ospfPacket->setAuthentication(i, 0);
             }
             MemoryOutputStream stream;
             Chunk::serialize(stream, ospfPacket);
             uint16_t crc = TcpIpChecksum::checksum(stream.getData());
             for (int i = 0; i < 8; i++) {
                 ospfPacket->setAuthentication(i, authenticationKey.bytes[i]);
             }
             ospfPacket->setCrc(crc);
             break;
         }
         default:
             throw cRuntimeError("Unknown CRC mode: %d", (int)crcMode);
     }
 }
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements(), inet::ospfv2::Ospfv2Interface::sendHelloPacket(), inet::ospfv2::Neighbor::sendLinkStateRequestPacket(), and inet::ospfv2::Ospfv2Interface::sendLsAcknowledgement().
Variable Documentation
IPV4_DATAGRAM_LENGTH
const B inet::ospfv2::IPV4_DATAGRAM_LENGTH = B(65536)
Referenced by inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
NULL_DESIGNATEDROUTERID
const DesignatedRouterId inet::ospfv2::NULL_DESIGNATEDROUTERID
Initial value:
= {
    Ipv4Address(0, 0, 0, 0), Ipv4Address(0, 0, 0, 0)
}
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2Interface::addDelayedAcknowledgement(), inet::ospfv2::Ospfv2InterfaceState::calculateDesignatedRouter(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv2::LinkStateRequestHandler::processPacket(), inet::ospfv2::LinkStateUpdateHandler::processPacket(), inet::ospfv2::Ospfv2Interface::reset(), and inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements().
OSPFv2_ASEXTERNALLSA_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_ASEXTERNALLSA_HEADER_LENGTH = B(4)
Referenced by calculateLsaSize(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa().
OSPFv2_ASEXTERNALLSA_TOS_INFO_LENGTH
const B inet::ospfv2::OSPFv2_ASEXTERNALLSA_TOS_INFO_LENGTH = B(12)
Referenced by calculateLsaSize(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa().
OSPFv2_DD_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_DD_HEADER_LENGTH = B(8)
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserialize(), and inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket().
OSPFv2_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_HEADER_LENGTH = B(24)
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), inet::ospfv2::Ospfv2Interface::createUpdatePacket(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::ospfv2::Neighbor::retransmitUpdatePacket(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements(), inet::ospfv2::Ospfv2Interface::sendHelloPacket(), inet::ospfv2::Neighbor::sendLinkStateRequestPacket(), and inet::ospfv2::Ospfv2Interface::sendLsAcknowledgement().
OSPFv2_HELLO_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_HELLO_HEADER_LENGTH = B(20)
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserialize(), and inet::ospfv2::Ospfv2Interface::sendHelloPacket().
OSPFv2_LINK_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_LINK_HEADER_LENGTH = B(12)
Referenced by calculateLsaSize().
OSPFv2_LSA_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_LSA_HEADER_LENGTH = B(20)
Referenced by inet::ospfv2::LinkStateUpdateHandler::acknowledgeLSA(), calculateLsaSize(), inet::ospfv2::Ospfv2PacketSerializer::deserialize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeAsExternalLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa(), inet::ospfv2::Neighbor::sendDatabaseDescriptionPacket(), inet::ospfv2::Ospfv2Interface::sendDelayedAcknowledgements(), and inet::ospfv2::Ospfv2Interface::sendLsAcknowledgement().
OSPFv2_NETWORKLSA_ADDRESS_LENGTH
const B inet::ospfv2::OSPFv2_NETWORKLSA_ADDRESS_LENGTH = B(4)
Referenced by calculateLsaSize(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa().
OSPFv2_NETWORKLSA_MASK_LENGTH
const B inet::ospfv2::OSPFv2_NETWORKLSA_MASK_LENGTH = B(4)
Referenced by calculateLsaSize(), inet::ospfv2::Ospfv2PacketSerializer::deserializeNetworkLsa(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa().
OSPFv2_REQUEST_LENGTH
const B inet::ospfv2::OSPFv2_REQUEST_LENGTH = B(12)
Referenced by inet::ospfv2::Ospfv2PacketSerializer::deserialize(), and inet::ospfv2::Neighbor::sendLinkStateRequestPacket().
OSPFv2_ROUTERLSA_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_ROUTERLSA_HEADER_LENGTH = B(4)
Referenced by calculateLsaSize().
OSPFv2_SUMMARYLSA_HEADER_LENGTH
const B inet::ospfv2::OSPFv2_SUMMARYLSA_HEADER_LENGTH = B(8)
Referenced by calculateLsaSize().
OSPFv2_TOS_LENGTH
const B inet::ospfv2::OSPFv2_TOS_LENGTH = B(4)
Referenced by calculateLsaSize(), and inet::ospfv2::Ospfv2PacketSerializer::deserializeSummaryLsa().