INET Framework for OMNeT++/OMNEST: inet::utils Namespace Reference
inet::utils Namespace Reference
Namespaces
filters
Functions
std::string ltostr (long i)
Converts an integer to string.
std::string dtostr (double d)
Converts a double to string.
std::string hex (uint16_t l)
std::string hex (int16_t l)
std::string hex (uint32_t l)
std::string hex (int32_t l)
std::string hex (uint64_t l)
std::string hex (int64_t l)
long hex (const char *s)
unsigned long uhex (const char *s)
double atod (const char *s)
Converts string to double.
unsigned long atoul (const char *s)
Converts string to unsigned long.
std::string stripnonalnum (const char *s)
Removes non-alphanumeric characters from the given string.
std::string stringf (const char *fmt,...)
Accepts a printf-like argument list, and returns the result in a string.
std::string vstringf (const char *fmt, va_list &args)
Accepts a vprintf-like argument list, and returns the result in a string.
cObject * createOneIfClassIsKnown (const char *className, const char *defaultNamespace=getSimulation() ->getContext() ->getClassName())
Like cObjectFactory::createOneIfClassIsKnown(), except it starts searching for the class in the given namespace.
cObject * createOne (const char *className, const char *defaultNamespace=getSimulation() ->getContext() ->getClassName())
Like cObjectFactory::createOne(), except it starts searching for the class in the given namespace.
bool fileExists (const char *pathname)
void splitFileName (const char *pathname, std::string &dir, std::string &fnameonly)
void makePath (const char *pathname)
void makePathForFile (const char *filename)
int roundUp (int numToRound, int multiple)
Rounding up to the nearest multiple of a number.
template<typename T >
T * dupPacketAndControlInfo (T *packet)
Duplicate a packet together with its control info.
cNEDValue nedf_hasModule (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_hasModule, "bool hasModule(string nedTypeName)", "string", "Returns true if the given NED type exists")
cNEDValue nedf_haveClass (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_haveClass, "bool haveClass(string className)", "string", "Returns true if the given C++ class exists")
cNEDValue nedf_moduleListByPath (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_moduleListByPath, "string moduleListByPath(string modulePath,...)", "string", "Returns a space-separated list of the modules at the given path(s). " "See cTopology::extractByModulePath().")
cNEDValue nedf_moduleListByNedType (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_moduleListByNedType, "string moduleListByNedType(string nedTypeName,...)", "string", "Returns a space-separated list of the modules with the given NED type(s). " "See cTopology::extractByNedTypeName().")
cNEDValue nedf_select (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_select, "any select(int index, ...)", "misc", "Returns the <index>th item from the rest of the argument list; numbering starts from 0.")
cNEDValue nedf_absPath (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_absPath, "string absPath(string modulePath)", "string", "Returns absolute path of given module")
cNEDValue nedf_firstAvailableOrEmpty (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_firstAvailableOrEmpty, "string firstAvailableOrEmpty(...)", "misc", "Accepts any number of strings, interprets them as NED type names " "(qualified or unqualified), and returns the first one that exists and " "its C++ implementation class is also available. Returns empty string if " "none of the types are available.")
cNEDValue nedf_nanToZero (cComponent *context, cNEDValue argv[], int argc)
Define_NED_Function2 (nedf_nanToZero, "quantity nanToZero(quantity x)", "math", "Returns the argument if it is not NaN, otherwise returns 0.")
Define_NED_Function2 (nedf_intWithUnit, "intquantity intWithUnit(any x)", "conversion", "Converts x to an integer (C++ long), and returns the result. A boolean argument becomes 0 or 1; a double is converted using floor(); a string or an XML argument causes an error.")
cNedValue nedf_xmlattr (cComponent *contextComponent, cNedValue argv[], int argc)
Define_NED_Function2 (nedf_xmlattr, "string xmlattr(xml xmlNode, string attributeName, string defaultValue?)", "xml", "Returns the value of the specified XML attribute of xmlNode. " "It returns the defaultValue (or throws an error) if the attribute does not exists.") cNEDValue nedf_findArrayObjectElement(cComponent *context
for (int index=0;index< array->size();index++)
return cNEDValue ((cObject *) nullptr)
Define_NED_Function2 (nedf_findArrayObjectElement, "bool findArrayObjectElement(any array, string key, any value, ...)", "misc", "Returns the first object from the array that matches the given set of key-value pairs")
cValue nedf_getId (cComponent *contextComponent, cValue argv[], int argc)
Variables
cNEDValue argv []
cNEDValue int argc
Function Documentation
atod()
INET_API double inet::utils::atod (const char * s)
Converts string to double.
 {
     char *e;
     double d = ::strtod(s, &e);
     if (*e)
         throw cRuntimeError("Invalid cast: '%s' cannot be interpreted as a double", s);
     return d;
 }
Referenced by inet::IndicatorLabelFigure::parse(), inet::IndicatorTextFigure::parse(), inet::IndexedImageFigure::parse(), inet::ProgressMeterFigure::parse(), inet::LinearGaugeFigure::parse(), inet::ThermometerFigure::parse(), inet::CounterFigure::parse(), and inet::GaugeFigure::parse().
atoul()
INET_API unsigned long inet::utils::atoul (const char * s)
Converts string to unsigned long.
 {
     char *e;
     unsigned long d = ::strtoul(s, &e, 10);
     if (*e)
         throw cRuntimeError("Invalid cast: '%s' cannot be interpreted as an unsigned long", s);
     return d;
 }
Referenced by inet::Ipv6RoutingTable::configureInterfaceFromXml(), inet::FigureRecorder::init(), inet::queueing::WrrClassifier::initialize(), and inet::queueing::WrrScheduler::initialize().
cNEDValue()
return inet::utils::cNEDValue ((cObject *) nullptr)
Referenced by nedf_nanToZero().
createOne()
INET_API cObject * inet::utils::createOne (const char * className, const char * defaultNamespace)
Like cObjectFactory::createOne(), except it starts searching for the class in the given namespace.
 {
     cObject *ret = createOneIfClassIsKnown(className, defaultNamespace);
     if (!ret)
         throw cRuntimeError("Class \"%s\" not found -- perhaps its code was not linked in, "
                             "or the class wasn't registered with Register_Class(), or in the case of "
                             "modules and channels, with Define_Module()/Define_Channel()", className);
     return ret;
 }
Referenced by inet::sctp::SctpAssociation::cloneAssociation(), inet::AggregatorBase::createAggregatorPolicy(), inet::queueing::PacketClassifier::createClassifierFunction(), inet::queueing::PacketQueue::createComparatorFunction(), inet::queueing::PacketBuffer::createDropperFunction(), inet::queueing::CompoundPacketQueueBase::createDropperFunction(), inet::queueing::PacketQueue::createDropperFunction(), inet::queueing::PacketTagger::createFilterFunction(), inet::queueing::PacketFilter::createFilterFunction(), inet::queueing::PacketLabeler::createFilterFunction(), inet::FragmenterBase::createFragmenterPolicy(), inet::queueing::PacketScheduler::createSchedulerFunction(), inet::sctp::SctpAssociation::initAssociation(), inet::tcp::TcpConnection::initClonedConnection(), inet::tcp::TcpLwipConnection::initConnection(), inet::tcp::TcpConnection::initConnection(), inet::PcapRecorder::initialize(), and inet::ScenarioManager::processLifecycleCommand().
createOneIfClassIsKnown()
INET_API cObject * inet::utils::createOneIfClassIsKnown (const char * className, const char * defaultNamespace)
Like cObjectFactory::createOneIfClassIsKnown(), except it starts searching for the class in the given namespace.
 {
     std::string ns = defaultNamespace;
     do {
         std::string::size_type found = ns.rfind("::");
         if (found == std::string::npos)
             found = 0;
         ns.erase(found);
         std::string cn = found ? ns + "::" + className : className;
         cObject *ret = cObjectFactory::createOneIfClassIsKnown(cn.c_str());
         if (ret)
             return ret;
     } while (!ns.empty());
     return nullptr;
 }
Referenced by createOne(), and inet::visualizer::StatisticCanvasVisualizer::createStatisticVisualization().
Define_NED_Function2() [1/11]
inet::utils::Define_NED_Function2 (nedf_absPath , "string absPath(string modulePath)" , "string" , "Returns absolute path of given module")
Define_NED_Function2() [2/11]
inet::utils::Define_NED_Function2 (nedf_findArrayObjectElement , "bool findArrayObjectElement(any array, string key, any value, ...)" , "misc" , "Returns the first object from the array that matches the given set of key-value pairs")
Define_NED_Function2() [3/11]
inet::utils::Define_NED_Function2 (nedf_firstAvailableOrEmpty , "string firstAvailableOrEmpty(...)" , "misc" , "Accepts any number of strings, interprets them as NED type names " " qualified or unqualified, and returns the first one that exists and " "its C++implementation class is also available. Returns empty string if " "none of the types are available.")
Define_NED_Function2() [4/11]
inet::utils::Define_NED_Function2 (nedf_hasModule , "bool hasModule(string nedTypeName)" , "string" , "Returns true if the given NED type exists")
Define_NED_Function2() [5/11]
inet::utils::Define_NED_Function2 (nedf_haveClass , "bool haveClass(string className)" , "string" , "Returns true if the given C++ class exists")
Define_NED_Function2() [6/11]
inet::utils::Define_NED_Function2 (nedf_intWithUnit , "intquantity intWithUnit(any x)" , "conversion" , "Converts x to an integer C++ long, and returns the result. A boolean argument becomes 0 or 1;a double is converted using floor();a string or an XML argument causes an error.")
Define_NED_Function2() [7/11]
inet::utils::Define_NED_Function2 (nedf_moduleListByNedType , "string moduleListByNedType(string nedTypeName,...)" , "string" , "Returns a space-separated list of the modules with the given NED type(s). " "See cTopology::extractByNedTypeName().")
Define_NED_Function2() [8/11]
inet::utils::Define_NED_Function2 (nedf_moduleListByPath , "string moduleListByPath(string modulePath,...)" , "string" , "Returns a space-separated list of the modules at the given path(s). " "See cTopology::extractByModulePath().")
Define_NED_Function2() [9/11]
inet::utils::Define_NED_Function2 (nedf_nanToZero , "quantity nanToZero(quantity x)" , "math" , "Returns the argument if it is not NaN, otherwise returns 0.")
Define_NED_Function2() [10/11]
inet::utils::Define_NED_Function2 (nedf_select , "any select(int index, ...)" , "misc" , "Returns the <index>th item from the rest of the argument list; numbering starts from 0.")
Define_NED_Function2() [11/11]
inet::utils::Define_NED_Function2 (nedf_xmlattr , "string xmlattr(xml xmlNode, string attributeName, string defaultValue?)" , "xml" , "Returns the value of the specified XML attribute of xmlNode. " "It returns the defaultValue (or throws an error) if the attribute does not exists.")
dtostr()
INET_API std::string inet::utils::dtostr (double d)
Converts a double to string.
 {
     std::ostringstream os;
     os << d;
     return os.str();
 }
dupPacketAndControlInfo()
template<typename T > T* inet::utils::dupPacketAndControlInfo (T * packet)
Duplicate a packet together with its control info.
(cPacket's dup() ignores the control info, it will be nullptr in the returned copy).
{
     T *copy = packet->dup();
     if (cObject *ctrl = packet->getControlInfo())
         copy->setControlInfo(ctrl->dup());
     return copy;
 }
Referenced by inet::NetworkProtocolBase::sendDown().
fileExists()
INET_API bool inet::utils::fileExists (const char * pathname)
 {
     // Note: stat("foo/") ==> error, even when "foo" exists and is a directory!
     struct stat statbuf;
     return stat(pathname, &statbuf) == 0;
 }
Referenced by makePath().
for()
inet::utils::for (int index = 0; index < array->size(); index++)
{
         cValueMap *map = check_and_cast<cValueMap *>(array->get(index).objectValue());
         for (int i = 1; i < argc; i += 2)
             if (map->get(argv[i].stringValue()).intValue() != argv[i + 1].intValue())
                 goto next;
         return map;
         next:;
     }
Referenced by inet::sctp::SctpAssociation::calculateAssocSharedKey(), inet::sctp::SctpAssociation::chunkReschedulingControl(), and inet::ospfv3::Ospfv3Splitter::parseConfig().
hex() [1/7]
INET_API long inet::utils::hex (const char * s)
 {
     return strtol(s, nullptr, 16);
 }
Referenced by hex().
hex() [2/7]
INET_API std::string inet::utils::hex (int16_t l)
 {
     std::ostringstream os;
     os << std::hex << l;
     return os.str();
 }
hex() [3/7]
INET_API std::string inet::utils::hex (int32_t l)
 {
     std::ostringstream os;
     os << std::hex << l;
     return os.str();
 }
hex() [4/7]
INET_API std::string inet::utils::hex (int64_t l)
 {
     std::ostringstream os;
     os << std::hex << l;
     return os.str();
 }
hex() [5/7]
INET_API std::string inet::utils::hex (uint16_t l)
 {
     std::ostringstream os;
     os << std::hex << l;
     return os.str();
 }
Referenced by inet::ospfv3::Ospfv3Area::detailedInfo(), inet::ospfv2::hexCharToByte(), inet::ClnsAddress::str(), and inet::Ipv6Address::str().
hex() [6/7]
INET_API std::string inet::utils::hex (uint32_t l)
 {
     std::ostringstream os;
     os << std::hex << l;
     return os.str();
 }
hex() [7/7]
INET_API std::string inet::utils::hex (uint64_t l)
 {
     std::ostringstream os;
     os << std::hex << l;
     return os.str();
 }
ltostr()
INET_API std::string inet::utils::ltostr (long i)
Converts an integer to string.
 {
     std::ostringstream os;
     os << i;
     return os.str();
 }
Referenced by inet::DiffservUtil::colorToString(), and inet::DiffservUtil::dscpToString().
makePath()
INET_API void inet::utils::makePath (const char * pathname)
 {
     if (!fileExists(pathname)) {
         std::string pathprefix, dummy;
         splitFileName(pathname, pathprefix, dummy);
         makePath(pathprefix.c_str());
         // note: anomaly with slash-terminated dirnames: stat("foo/") says
         // it does not exist, and mkdir("foo/") says cannot create (EEXIST):
         if (opp_mkdir(pathname, 0755) != 0 && errno != EEXIST)
             throw cRuntimeError("Cannot create directory '%s': %s", pathname, strerror(errno));
     }
 }
Referenced by makePathForFile().
makePathForFile()
INET_API void inet::utils::makePathForFile (const char * filename)
 {
     std::string pathprefix, dummy;
     splitFileName(filename, pathprefix, dummy);
     makePath(pathprefix.c_str());
 }
Referenced by inet::Ipv4NetworkConfigurator::dumpConfig(), inet::RoutingTableRecorder::ensureRoutingLogFileOpen(), inet::MoBanCoordinator::initialize(), inet::PcapngWriter::open(), inet::PcapWriter::open(), and inet::PcapReader::openPcap().
nedf_absPath()
cNEDValue inet::utils::nedf_absPath (cComponent * context, cNEDValue argv[], int argc)
 {
     if (argc != 1)
         throw cRuntimeError("absPath(): must be one argument instead of %d argument(s)", argc);
     const char *path = argv[0].stringValue();
     switch (*path) {
         case '.':
             return context->getFullPath() + path;
         case '^':
             return context->getFullPath() + '.' + path;
         default:
             return argv[0];
     }
 }
nedf_firstAvailableOrEmpty()
cNEDValue inet::utils::nedf_firstAvailableOrEmpty (cComponent * context, cNEDValue argv[], int argc)
 {
     cRegistrationList *types = omnetpp::internal::componentTypes.getInstance();
     for (int i = 0; i < argc; i++) {
         if (argv[i].getType() != cNEDValue::STRING)
             throw cRuntimeError("firstAvailable(): string arguments expected");
         const char *name = argv[i].stringValue();
         cComponentType *c;
         c = dynamic_cast<cComponentType *>(types->lookup(name)); // by qualified name
         if (c && c->isAvailable())
             return argv[i];
         c = dynamic_cast<cComponentType *>(types->find(name)); // by simple name
         if (c && c->isAvailable())
             return argv[i];
     }
     return "";
 }
nedf_getId()
cValue inet::utils::nedf_getId (cComponent * contextComponent, cValue argv[], int argc)
 {
     return contextComponent->getId();
 }
nedf_hasModule()
cNEDValue inet::utils::nedf_hasModule (cComponent * context, cNEDValue argv[], int argc)
 {
     cRegistrationList *types = omnetpp::internal::componentTypes.getInstance();
     if (argv[0].getType() != cNEDValue::STRING)
         throw cRuntimeError("hasModule(): string arguments expected");
     const char *name = argv[0].stringValue();
     cComponentType *c;
     c = dynamic_cast<cComponentType *>(types->lookup(name)); // by qualified name
     if (c && c->isAvailable())
         return true;
     c = dynamic_cast<cComponentType *>(types->find(name)); // by simple name
     if (c && c->isAvailable())
         return true;
     return false;
 }
nedf_haveClass()
cNEDValue inet::utils::nedf_haveClass (cComponent * context, cNEDValue argv[], int argc)
 {
     return omnetpp::internal::classes.getInstance()->lookup(argv[0].stringValue()) != nullptr;
 }
nedf_moduleListByNedType()
cNEDValue inet::utils::nedf_moduleListByNedType (cComponent * context, cNEDValue argv[], int argc)
 {
     std::string modulenames;
     cTopology topo;
     std::vector<std::string> paths;
     for (int i = 0; i < argc; i++)
         paths.push_back(argv[i].stdstringValue());
     topo.extractByNedTypeName(paths);
     for (int i = 0; i < topo.getNumNodes(); i++) {
         std::string path = topo.getNode(i)->getModule()->getFullPath();
         if (modulenames.length() > 0)
             modulenames = modulenames + " " + path;
         else
             modulenames = path;
     }
     return modulenames;
 }
nedf_moduleListByPath()
cNEDValue inet::utils::nedf_moduleListByPath (cComponent * context, cNEDValue argv[], int argc)
 {
     std::string modulenames;
     cTopology topo;
     std::vector<std::string> paths;
     for (int i = 0; i < argc; i++)
         paths.push_back(argv[i].stdstringValue());
     topo.extractByModulePath(paths);
     for (int i = 0; i < topo.getNumNodes(); i++) {
         std::string path = topo.getNode(i)->getModule()->getFullPath();
         if (modulenames.length() > 0)
             modulenames = modulenames + " " + path;
         else
             modulenames = path;
     }
     return modulenames;
 }
nedf_nanToZero()
cNEDValue inet::utils::nedf_nanToZero (cComponent * context, cNEDValue argv[], int argc)
 {
     double x = argv[0].doubleValueRaw();
     const char *unit = argv[0].getUnit();
     return std::isnan(x) ? cNEDValue(0.0, unit) : argv[0];
 }
nedf_select()
cNEDValue inet::utils::nedf_select (cComponent * context, cNEDValue argv[], int argc)
 {
     long index = argv[0];
     if (index < 0)
         throw cRuntimeError("select(): negative index %ld", index);
     if (index >= argc - 1)
         throw cRuntimeError("select(): index=%ld is too large, max value is %d", index, argc - 1);
     return argv[index + 1];
 }
nedf_xmlattr()
cNedValue inet::utils::nedf_xmlattr (cComponent * contextComponent, cNedValue argv[], int argc)
 {
     if (argv[0].getType() != cNedValue::OBJECT)
         throw cRuntimeError("xmlattr(): xmlNode argument must be an xml node");
     if (argv[1].getType() != cNEDValue::STRING)
         throw cRuntimeError("xmlattr(): attributeName argument must be a string");
     cXMLElement *node = argv[0].xmlValue();
     const char *attr = node->getAttribute(argv[1].stdstringValue().c_str());
     if (attr != nullptr)
         return cNedValue(attr);
     if (argc < 3)
         throw cRuntimeError("Attribute '%s' not found in xml '%s'", argv[1].stdstringValue().c_str(), argv[0].stdstringValue().c_str());
     return argv[2];
 }
roundUp()
int inet::utils::roundUp (int numToRound, int multiple) inline
Rounding up to the nearest multiple of a number.
 { return ((numToRound + multiple - 1) / multiple) * multiple; }
Referenced by inet::Ipv4Header::calculateHeaderByteLength(), and inet::Gpsr::setGpsrOptionOnNetworkDatagram().
splitFileName()
INET_API void inet::utils::splitFileName (const char * pathname, std::string & dir, std::string & fnameonly)
 {
     if (!pathname || !*pathname) {
         dir = ".";
         fnameonly = "";
         return;
     }
     // find last "/" or "\"
     const char *s = pathname + strlen(pathname) - 1;
     s--; // ignore potential trailing "/"
     while (s > pathname && *s != '\\' && *s != '/')
         s--;
     const char *sep = s <= pathname ? nullptr : s;
     // split along that
     if (!sep) {
         // no slash or colon
         if (strchr(pathname, ':') || strcmp(pathname, ".") == 0 || strcmp(pathname, "..") == 0) {
             fnameonly = "";
             dir = pathname;
         }
         else {
             fnameonly = pathname;
             dir = ".";
         }
     }
     else {
         fnameonly = s + 1;
         dir = std::string(pathname, s - pathname + 1);
     }
 }
Referenced by makePath(), and makePathForFile().
stringf()
INET_API std::string inet::utils::stringf (const char * fmt, ...)
Accepts a printf-like argument list, and returns the result in a string.
The limit is 1024 chars.
 {
     char buf[BUFLEN];
     va_list va;
     va_start(va, fmt);
     vsnprintf(buf, BUFLEN, fmt, va);
     buf[BUFLEN - 1] = '\0';
     va_end(va);
     return buf;
 }
Referenced by inet::Ipv4RoutingTable::printMulticastRoutingTable(), and inet::Ipv4RoutingTable::printRoutingTable().
stripnonalnum()
INET_API std::string inet::utils::stripnonalnum (const char * s)
Removes non-alphanumeric characters from the given string.
 {
     std::string result;
     for (; *s; s++)
         if (isalnum(*s))
             result += *s;
     return result;
 }
Referenced by inet::NetworkInterface::initialize(), and inet::ieee80211::Ieee80211Mac::isInterfaceRegistered().
uhex()
INET_API unsigned long inet::utils::uhex (const char * s)
 {
     return strtoul(s, nullptr, 16);
 }
vstringf()
INET_API std::string inet::utils::vstringf (const char * fmt, va_list & args)
Accepts a vprintf-like argument list, and returns the result in a string.
The limit is 1024 chars.
 {
     char buf[BUFLEN];
     vsnprintf(buf, BUFLEN, fmt, args);
     buf[BUFLEN - 1] = '\0';
     return buf;
 }
Variable Documentation
argc
cNEDValue int inet::utils::argc
Initial value:
{
    cValueArray *array = check_and_cast<cValueArray *>(argv[0].objectValue())
Referenced by inet::PacketFilter::DynamicExpressionResolver::callFunction(), inet::PacketFilter::DynamicExpressionResolver::callMethod(), for(), nedf_absPath(), nedf_firstAvailableOrEmpty(), nedf_moduleListByNedType(), nedf_moduleListByPath(), nedf_select(), and nedf_xmlattr().
argv
cNEDValue inet::utils::argv[]
Referenced by inet::PacketFilter::DynamicExpressionResolver::callFunction(), inet::PacketFilter::DynamicExpressionResolver::callMethod(), for(), nedf_absPath(), nedf_firstAvailableOrEmpty(), nedf_hasModule(), nedf_haveClass(), nedf_moduleListByNedType(), nedf_moduleListByPath(), nedf_nanToZero(), nedf_select(), and nedf_xmlattr().