INET Framework for OMNeT++/OMNEST: inet::visualizer Namespace Reference
inet::visualizer Namespace Reference
Classes
class AnimationPosition
class AnimationSpeedInterpolator
class ColorSet
class DataLinkCanvasVisualizer
class DataLinkOsgVisualizer
class EnergyStorageCanvasVisualizer
class EnergyStorageOsgVisualizer
class EnergyStorageVisualizerBase
class FailureProtectionConfigurationCanvasVisualizer
class GateFilter
This class provides a generic filter for gates.
class GateScheduleCanvasVisualizer
class GateScheduleOsgVisualizer
class GateScheduleVisualizerBase
class Ieee80211CanvasVisualizer
class Ieee80211OsgVisualizer
class Ieee80211VisualizerBase
class InfoCanvasVisualizer
class InfoOsgVisualizer
class InfoVisualizerBase
class InterfaceFilter
This class provides a generic filter for interfaces.
class InterfaceTableCanvasVisualizer
class InterfaceTableOsgVisualizer
class InterfaceTableVisualizerBase
class LineManager
class LinkBreakCanvasVisualizer
class LinkBreakOsgVisualizer
class LinkBreakVisualizerBase
class LinkCanvasVisualizerBase
class LinkOsgVisualizerBase
class LinkVisualizerBase
class MediumCanvasVisualizer
class MediumOsgVisualizer
class MediumVisualizerBase
class MobilityCanvasVisualizer
class MobilityOsgVisualizer
class MobilityVisualizerBase
class ModuleFilter
This class provides a generic filter for modules.
class NetworkConnectionCanvasVisualizer
class NetworkConnectionOsgVisualizer
class NetworkConnectionVisualizerBase
class NetworkNodeCanvasVisualization
class NetworkNodeCanvasVisualizer
class NetworkNodeFilter
This class provides a generic filter for network nodes.
class NetworkNodeOsgVisualization
class NetworkNodeOsgVisualizer
class NetworkNodeVisualizerBase
class NetworkRouteCanvasVisualizer
class NetworkRouteOsgVisualizer
class OpenStreetMapSceneCanvasVisualizer
class PacketDrop
class PacketDropCanvasVisualizer
class PacketDropOsgVisualizer
class PacketDropVisualizerBase
class PacketFlowCanvasVisualizer
class PacketFlowOsgVisualizer
class PathCanvasVisualizerBase
class PathOsgVisualizerBase
class PathVisualizerBase
class PhysicalEnvironmentCanvasVisualizer
class PhysicalEnvironmentOsgVisualizer
class PhysicalEnvironmentVisualizerBase
class PhysicalLinkCanvasVisualizer
class PhysicalLinkOsgVisualizer
class PortFilter
This class provides a generic filter for ports.
class QueueCanvasVisualizer
class QueueFilter
This class provides a generic filter for queues.
class QueueOsgVisualizer
class QueueVisualizerBase
class RadioCanvasVisualizer
class RadioOsgVisualizer
class RadioVisualizerBase
class RoutingTableCanvasVisualizer
class RoutingTableOsgVisualizer
class RoutingTableVisualizerBase
class SceneCanvasVisualizer
class SceneOsgEarthVisualizer
class SceneOsgVisualizer
class SceneOsgVisualizerBase
class SceneVisualizerBase
class StatisticCanvasVisualizer
class StatisticOsgVisualizer
class StatisticVisualizerBase
class StreamRedundancyConfigurationCanvasVisualizer
class TracingObstacleLossCanvasVisualizer
class TracingObstacleLossOsgVisualizer
class TracingObstacleLossVisualizerBase
class TransportConnectionCanvasVisualizer
class TransportConnectionOsgVisualizer
class TransportConnectionVisualizerBase
class TransportRouteCanvasVisualizer
class TransportRouteOsgVisualizer
class TreeCanvasVisualizerBase
class TreeVisualizerBase
class VisualizerBase
Enumerations
enum Placement {
PLACEMENT_NONE = 0x0000, PLACEMENT_TOP_LEFT = 0x0001, PLACEMENT_TOP_CENTER = 0x0002, PLACEMENT_TOP_RIGHT = 0x0004,
PLACEMENT_CENTER_LEFT = 0x0008, PLACEMENT_CENTER_CENTER = 0x0010, PLACEMENT_CENTER_RIGHT = 0x0020, PLACEMENT_BOTTOM_LEFT = 0x0040,
PLACEMENT_BOTTOM_CENTER = 0x0080, PLACEMENT_BOTTOM_RIGHT = 0x0100, PLACEMENT_ANY = 0xFFFF
}
Functions
Register_ResultRecorder ("statisticVisualizerLastValueRecorder", StatisticVisualizerBase::LastValueRecorder)
bool isEmpty (const char *s)
bool isNotEmpty (const char *s)
Define_Module (GateScheduleCanvasVisualizer)
Define_Module (InfoCanvasVisualizer)
Define_Module (PacketDropCanvasVisualizer)
Define_Module (QueueCanvasVisualizer)
Define_Module (StatisticCanvasVisualizer)
Define_Module (FailureProtectionConfigurationCanvasVisualizer)
Define_Module (StreamRedundancyConfigurationCanvasVisualizer)
Define_Module (PhysicalEnvironmentCanvasVisualizer)
Define_Module (PacketFlowCanvasVisualizer)
Define_Module (DataLinkCanvasVisualizer)
Define_Module (Ieee80211CanvasVisualizer)
Define_Module (InterfaceTableCanvasVisualizer)
Define_Module (LinkBreakCanvasVisualizer)
Define_Module (MobilityCanvasVisualizer)
Define_Module (NetworkRouteCanvasVisualizer)
Define_Module (RoutingTableCanvasVisualizer)
Define_Module (MediumCanvasVisualizer)
Define_Module (PhysicalLinkCanvasVisualizer)
Define_Module (RadioCanvasVisualizer)
Define_Module (TracingObstacleLossCanvasVisualizer)
Define_Module (EnergyStorageCanvasVisualizer)
Define_Module (NetworkConnectionCanvasVisualizer)
Define_Module (NetworkNodeCanvasVisualizer)
Define_Module (OpenStreetMapSceneCanvasVisualizer)
Define_Module (SceneCanvasVisualizer)
Define_Module (TransportConnectionCanvasVisualizer)
Define_Module (TransportRouteCanvasVisualizer)
Define_Module (GateScheduleOsgVisualizer)
Define_Module (InfoOsgVisualizer)
Define_Module (PacketDropOsgVisualizer)
Define_Module (QueueOsgVisualizer)
Define_Module (StatisticOsgVisualizer)
Define_Module (PhysicalEnvironmentOsgVisualizer)
Define_Module (PacketFlowOsgVisualizer)
Define_Module (DataLinkOsgVisualizer)
Define_Module (Ieee80211OsgVisualizer)
Define_Module (InterfaceTableOsgVisualizer)
Define_Module (LinkBreakOsgVisualizer)
Define_Module (MobilityOsgVisualizer)
Define_Module (NetworkRouteOsgVisualizer)
Define_Module (RoutingTableOsgVisualizer)
Define_Module (MediumOsgVisualizer)
Define_Module (PhysicalLinkOsgVisualizer)
Define_Module (RadioOsgVisualizer)
Define_Module (TracingObstacleLossOsgVisualizer)
Define_Module (EnergyStorageOsgVisualizer)
Define_Module (NetworkConnectionOsgVisualizer)
Define_Module (NetworkNodeOsgVisualizer)
Define_Module (SceneOsgEarthVisualizer)
Define_Module (SceneOsgVisualizer)
Define_Module (TransportConnectionOsgVisualizer)
Define_Module (TransportRouteOsgVisualizer)
Placement parsePlacement (const char *s)
Enumeration Type Documentation
Placement
enum inet::visualizer::Placement
Enumerator
PLACEMENT_NONE
PLACEMENT_TOP_LEFT
PLACEMENT_TOP_CENTER
PLACEMENT_TOP_RIGHT
PLACEMENT_CENTER_LEFT
PLACEMENT_CENTER_CENTER
PLACEMENT_CENTER_RIGHT
PLACEMENT_BOTTOM_LEFT
PLACEMENT_BOTTOM_CENTER
PLACEMENT_BOTTOM_RIGHT
PLACEMENT_ANY
                {
     PLACEMENT_NONE          = 0x0000,
     PLACEMENT_TOP_LEFT      = 0x0001,
     PLACEMENT_TOP_CENTER    = 0x0002,
     PLACEMENT_TOP_RIGHT     = 0x0004,
     PLACEMENT_CENTER_LEFT   = 0x0008,
     PLACEMENT_CENTER_CENTER = 0x0010,
     PLACEMENT_CENTER_RIGHT  = 0x0020,
     PLACEMENT_BOTTOM_LEFT   = 0x0040,
     PLACEMENT_BOTTOM_CENTER = 0x0080,
     PLACEMENT_BOTTOM_RIGHT  = 0x0100,
     PLACEMENT_ANY           = 0xFFFF
 };
Function Documentation
Define_Module() [1/52]
inet::visualizer::Define_Module (DataLinkCanvasVisualizer)
Define_Module() [2/52]
inet::visualizer::Define_Module (DataLinkOsgVisualizer)
Define_Module() [3/52]
inet::visualizer::Define_Module (EnergyStorageCanvasVisualizer)
Define_Module() [4/52]
inet::visualizer::Define_Module (EnergyStorageOsgVisualizer)
Define_Module() [5/52]
inet::visualizer::Define_Module (FailureProtectionConfigurationCanvasVisualizer)
Define_Module() [6/52]
inet::visualizer::Define_Module (GateScheduleCanvasVisualizer)
Define_Module() [7/52]
inet::visualizer::Define_Module (GateScheduleOsgVisualizer)
Define_Module() [8/52]
inet::visualizer::Define_Module (Ieee80211CanvasVisualizer)
Define_Module() [9/52]
inet::visualizer::Define_Module (Ieee80211OsgVisualizer)
Define_Module() [10/52]
inet::visualizer::Define_Module (InfoCanvasVisualizer)
Define_Module() [11/52]
inet::visualizer::Define_Module (InfoOsgVisualizer)
Define_Module() [12/52]
inet::visualizer::Define_Module (InterfaceTableCanvasVisualizer)
Define_Module() [13/52]
inet::visualizer::Define_Module (InterfaceTableOsgVisualizer)
Define_Module() [14/52]
inet::visualizer::Define_Module (LinkBreakCanvasVisualizer)
Define_Module() [15/52]
inet::visualizer::Define_Module (LinkBreakOsgVisualizer)
Define_Module() [16/52]
inet::visualizer::Define_Module (MediumCanvasVisualizer)
Define_Module() [17/52]
inet::visualizer::Define_Module (MediumOsgVisualizer)
Define_Module() [18/52]
inet::visualizer::Define_Module (MobilityCanvasVisualizer)
Define_Module() [19/52]
inet::visualizer::Define_Module (MobilityOsgVisualizer)
Define_Module() [20/52]
inet::visualizer::Define_Module (NetworkConnectionCanvasVisualizer)
Define_Module() [21/52]
inet::visualizer::Define_Module (NetworkConnectionOsgVisualizer)
Define_Module() [22/52]
inet::visualizer::Define_Module (NetworkNodeCanvasVisualizer)
Define_Module() [23/52]
inet::visualizer::Define_Module (NetworkNodeOsgVisualizer)
Define_Module() [24/52]
inet::visualizer::Define_Module (NetworkRouteCanvasVisualizer)
Define_Module() [25/52]
inet::visualizer::Define_Module (NetworkRouteOsgVisualizer)
Define_Module() [26/52]
inet::visualizer::Define_Module (OpenStreetMapSceneCanvasVisualizer)
Define_Module() [27/52]
inet::visualizer::Define_Module (PacketDropCanvasVisualizer)
Define_Module() [28/52]
inet::visualizer::Define_Module (PacketDropOsgVisualizer)
Define_Module() [29/52]
inet::visualizer::Define_Module (PacketFlowCanvasVisualizer)
Define_Module() [30/52]
inet::visualizer::Define_Module (PacketFlowOsgVisualizer)
Define_Module() [31/52]
inet::visualizer::Define_Module (PhysicalEnvironmentCanvasVisualizer)
Define_Module() [32/52]
inet::visualizer::Define_Module (PhysicalEnvironmentOsgVisualizer)
Define_Module() [33/52]
inet::visualizer::Define_Module (PhysicalLinkCanvasVisualizer)
Define_Module() [34/52]
inet::visualizer::Define_Module (PhysicalLinkOsgVisualizer)
Define_Module() [35/52]
inet::visualizer::Define_Module (QueueCanvasVisualizer)
Define_Module() [36/52]
inet::visualizer::Define_Module (QueueOsgVisualizer)
Define_Module() [37/52]
inet::visualizer::Define_Module (RadioCanvasVisualizer)
Define_Module() [38/52]
inet::visualizer::Define_Module (RadioOsgVisualizer)
Define_Module() [39/52]
inet::visualizer::Define_Module (RoutingTableCanvasVisualizer)
Define_Module() [40/52]
inet::visualizer::Define_Module (RoutingTableOsgVisualizer)
Define_Module() [41/52]
inet::visualizer::Define_Module (SceneCanvasVisualizer)
Define_Module() [42/52]
inet::visualizer::Define_Module (SceneOsgEarthVisualizer)
Define_Module() [43/52]
inet::visualizer::Define_Module (SceneOsgVisualizer)
Define_Module() [44/52]
inet::visualizer::Define_Module (StatisticCanvasVisualizer)
Define_Module() [45/52]
inet::visualizer::Define_Module (StatisticOsgVisualizer)
Define_Module() [46/52]
inet::visualizer::Define_Module (StreamRedundancyConfigurationCanvasVisualizer)
Define_Module() [47/52]
inet::visualizer::Define_Module (TracingObstacleLossCanvasVisualizer)
Define_Module() [48/52]
inet::visualizer::Define_Module (TracingObstacleLossOsgVisualizer)
Define_Module() [49/52]
inet::visualizer::Define_Module (TransportConnectionCanvasVisualizer)
Define_Module() [50/52]
inet::visualizer::Define_Module (TransportConnectionOsgVisualizer)
Define_Module() [51/52]
inet::visualizer::Define_Module (TransportRouteCanvasVisualizer)
Define_Module() [52/52]
inet::visualizer::Define_Module (TransportRouteOsgVisualizer)
isEmpty()
bool inet::visualizer::isEmpty (const char * s) inline
 { return !s || !s[0]; }
Referenced by inet::queueing::PacketQueue::canPullPacket(), inet::queueing::PacketQueue::canPullSomePacket(), and inet::queueing::WrrClassifier::classifyPacket().
isNotEmpty()
bool inet::visualizer::isNotEmpty (const char * s) inline
 { return s && s[0]; }
parsePlacement()
Placement inet::visualizer::parsePlacement (const char * s)
 {
     int placement = PLACEMENT_NONE;
     cStringTokenizer tokenizer(s);
     while (tokenizer.hasMoreTokens()) {
         auto token = tokenizer.nextToken();
         if (!strcmp("left", token))
             placement |= PLACEMENT_TOP_LEFT | PLACEMENT_CENTER_LEFT | PLACEMENT_BOTTOM_LEFT;
         else if (!strcmp("right", token))
             placement |= PLACEMENT_TOP_RIGHT | PLACEMENT_CENTER_RIGHT | PLACEMENT_BOTTOM_RIGHT;
         else if (!strcmp("top", token))
             placement |= PLACEMENT_TOP_LEFT | PLACEMENT_TOP_CENTER | PLACEMENT_TOP_RIGHT;
         else if (!strcmp("bottom", token))
             placement |= PLACEMENT_BOTTOM_LEFT | PLACEMENT_BOTTOM_CENTER | PLACEMENT_BOTTOM_RIGHT;
         else if (!strcmp("topLeft", token))
             placement |= PLACEMENT_TOP_LEFT;
         else if (!strcmp("topCenter", token))
             placement |= PLACEMENT_TOP_CENTER;
         else if (!strcmp("topRight", token))
             placement |= PLACEMENT_TOP_RIGHT;
         else if (!strcmp("centerLeft", token))
             placement |= PLACEMENT_CENTER_LEFT;
         else if (!strcmp("centerCenter", token))
             placement |= PLACEMENT_CENTER_CENTER;
         else if (!strcmp("centerRight", token))
             placement |= PLACEMENT_CENTER_RIGHT;
         else if (!strcmp("bottomLeft", token))
             placement |= PLACEMENT_BOTTOM_LEFT;
         else if (!strcmp("bottomCenter", token))
             placement |= PLACEMENT_BOTTOM_CENTER;
         else if (!strcmp("bottomRight", token))
             placement |= PLACEMENT_BOTTOM_RIGHT;
         else if (!strcmp("any", token))
             placement |= PLACEMENT_ANY;
         else
             throw cRuntimeError("Unknown placement: %s", token);
     }
     return static_cast<Placement>(placement);
 }
Referenced by inet::visualizer::EnergyStorageVisualizerBase::initialize(), inet::visualizer::Ieee80211VisualizerBase::initialize(), inet::visualizer::QueueVisualizerBase::initialize(), inet::visualizer::InfoVisualizerBase::initialize(), inet::visualizer::TransportConnectionVisualizerBase::initialize(), inet::visualizer::InterfaceTableVisualizerBase::initialize(), inet::visualizer::RadioVisualizerBase::initialize(), inet::visualizer::GateScheduleVisualizerBase::initialize(), and inet::visualizer::StatisticVisualizerBase::initialize().
Register_ResultRecorder()
inet::visualizer::Register_ResultRecorder ("statisticVisualizerLastValueRecorder" , StatisticVisualizerBase::LastValueRecorder)