INET Framework for OMNeT++/OMNEST: inet::osg Namespace Reference
inet::osg Namespace Reference
Classes
class FindNodesVisitor
class LineNode
class SimulationScene
This class is used for the root of the OSG nodes of all kinds of simulation visualization.
class TopLevelScene
This class is used for the topmost node in the OSG node hierarchy.
Functions
Vec3Array * createCircleVertices (const Coord &center, double radius, int polygonSize)
Vec3Array * createAnnulusVertices (const Coord &center, double outerRadius, double innerRadius, int polygonSize)
Geometry * createLineGeometry (const Coord &start, const Coord &end)
Geometry * createArrowheadGeometry (const Coord &start, const Coord &end, double width, double height)
Geometry * createPolylineGeometry (const std::vector< Coord > &coords)
Geometry * createCircleGeometry (const Coord &center, double radius, int polygonSize)
Geometry * createAnnulusGeometry (const Coord &center, double outerRadius, double innerRadius, int polygonSize)
Geometry * createQuadGeometry (const Coord &min, const Coord &max)
Geometry * createPolygonGeometry (const std::vector< Coord > &points, const Coord &translation)
osg::Node * createArrowhead (const Coord &start, const Coord &end, double width, double height)
osg::Node * createLine (const Coord &start, const Coord &end, cFigure::Arrowhead startArrowhead, cFigure::Arrowhead endArrowhead)
osg::Node * createPolyline (const std::vector< Coord > &coords, cFigure::Arrowhead startArrowhead, cFigure::Arrowhead endArrowhead)
osgText::Text * createText (const char *string, const Coord &position, const cFigure::Color &color)
AutoTransform * createAutoTransform (Drawable *drawable, AutoTransform::AutoRotateMode mode, bool autoScaleToScreen, const Coord &position)
PositionAttitudeTransform * createPositionAttitudeTransform (const Coord &position, const Quaternion &orientation)
std::string resolveImageResource (const char *imageName, cComponent *context)
osg::Image * createImage (const char *fileName)
osg::Image * createImageFromResource (const char *imageName)
Texture2D * createTexture (const char *fileName, bool repeat)
Texture2D * createTextureFromResource (const char *imageName, bool repeat)
StateSet * createStateSet (const cFigure::Color &color, double opacity, bool cullBackFace)
StateSet * createLineStateSet (const cFigure::Color &color, const cFigure::LineStyle &style, double width, bool overlay)
Vec3d toVec3d (const Coord &coord)
Coord toCoord (const Vec3d &vec3d)
Function Documentation
createAnnulusGeometry()
Geometry * inet::osg::createAnnulusGeometry (const Coord & center, double outerRadius, double innerRadius, int polygonSize)
 {
     auto geometry = new Geometry();
     geometry->setVertexArray(createAnnulusVertices(center, outerRadius, innerRadius, polygonSize));
     geometry->addPrimitiveSet(new DrawArrays(PrimitiveSet::TRIANGLE_STRIP, 0, 2 * polygonSize + 2));
     return geometry;
 }
createAnnulusVertices()
Vec3Array * inet::osg::createAnnulusVertices (const Coord & center, double outerRadius, double innerRadius, int polygonSize)
 {
     auto vertices = new Vec3Array();
     if (outerRadius > 0) {
         double theta, px, py;
         for (int i = 0; i <= polygonSize; i++) {
             theta = 2.0 * M_PI / polygonSize * i;
             px = center.x + outerRadius * cos(theta);
             py = center.y + outerRadius * sin(theta);
             vertices->push_back(Vec3d(px, py, center.z));
             px = center.x + innerRadius * cos(theta);
             py = center.y + innerRadius * sin(theta);
             vertices->push_back(Vec3d(px, py, center.z));
         }
     }
     else {
         vertices->push_back(Vec3d(0.0, 0.0, 0.0));
         vertices->push_back(Vec3d(0.0, 0.0, 0.0));
     }
     return vertices;
 }
Referenced by createAnnulusGeometry().
createArrowhead()
Node * inet::osg::createArrowhead (const Coord & start, const Coord & end, double width, double height)
 {
     auto direction = start - end;
     auto arrowhead = inet::osg::createArrowheadGeometry(direction, Coord::ZERO, width, height);
     auto autoTransform = inet::osg::createAutoTransform(arrowhead, osg::AutoTransform::ROTATE_TO_AXIS, true, end);
     auto vertexArray = static_cast<osg::Vec3Array *>(arrowhead->getVertexArray());
     auto normal = (vertexArray->at(0) - vertexArray->at(1)) ^ (vertexArray->at(0) - vertexArray->at(2));
     autoTransform->setNormal(normal);
     autoTransform->setAxis(toVec3d(direction));
     return autoTransform;
 }
Referenced by createLine(), createPolyline(), inet::osg::LineNode::LineNode(), inet::osg::LineNode::setEnd(), and inet::osg::LineNode::setStart().
createArrowheadGeometry()
Geometry * inet::osg::createArrowheadGeometry (const Coord & start, const Coord & end, double width, double height)
 {
     auto geometry = new Geometry();
     auto vertices = new Vec3Array();
     Coord direction = end - start;
     Vec3 e = Vec3(end.x, end.y, end.z);
     Vec3 v = Vec3(direction.x, direction.y, direction.z);
     v.normalize();
     Vec3 d = v * height;
     Vec3 zero;
     // NOTE: make sure the normal is not parallel with the rotation vector
     auto cpX = v ^ X_AXIS;
     auto cpY = v ^ Y_AXIS;
     auto cpZ = v ^ Z_AXIS;
     if (cpX != zero)
         v = cpX;
     else if (cpY != zero)
         v = cpY;
     else if (cpZ != zero)
         v = cpZ;
     else
         ASSERT(false);
     v *= width / 2;
     vertices->push_back(e);
     vertices->push_back(e - d + v);
     vertices->push_back(e - d - v);
     auto drawArrays = new DrawArrays(PrimitiveSet::TRIANGLES);
     drawArrays->setFirst(0);
     drawArrays->setCount(3);
     geometry->setVertexArray(vertices);
     geometry->addPrimitiveSet(drawArrays);
     return geometry;
 }
Referenced by createArrowhead().
createAutoTransform()
AutoTransform * inet::osg::createAutoTransform (Drawable * drawable, AutoTransform::AutoRotateMode mode, bool autoScaleToScreen, const Coord & position)
 {
     auto geode = new Geode();
     geode->addDrawable(drawable);
     auto autoTransform = new AutoTransform();
     autoTransform->setAutoScaleToScreen(autoScaleToScreen);
     autoTransform->setAutoRotateMode(mode);
     autoTransform->setPosition(Vec3(position.x, position.y, position.z));
     autoTransform->addChild(geode);
     return autoTransform;
 }
Referenced by createArrowhead(), inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), and inet::visualizer::SceneOsgVisualizerBase::initializeAxis().
createCircleGeometry()
Geometry * inet::osg::createCircleGeometry (const Coord & center, double radius, int polygonSize)
 {
     auto geometry = new Geometry();
     geometry->setVertexArray(createCircleVertices(center, radius, polygonSize));
     geometry->addPrimitiveSet(new DrawArrays(PrimitiveSet::LINE_LOOP, 0, polygonSize));
     return geometry;
 }
createCircleVertices()
Vec3Array * inet::osg::createCircleVertices (const Coord & center, double radius, int polygonSize)
 {
     auto vertices = new Vec3Array();
     double theta, px, py;
     for (int i = 1; i <= polygonSize; i++) {
         theta = 2.0 * M_PI / polygonSize * i;
         px = center.x + radius * cos(theta);
         py = center.y + radius * sin(theta);
         vertices->push_back(Vec3d(px, py, center.z));
     }
     return vertices;
 }
Referenced by createCircleGeometry().
createImage()
Image * inet::osg::createImage (const char * fileName)
 {
     auto image = osgDB::readImageFile(fileName);
     if (image == nullptr)
         throw cRuntimeError("Cannot load image '%s'", fileName);
     return image;
 }
Referenced by inet::visualizer::Ieee80211OsgVisualizer::createIeee80211Visualization(), createImageFromResource(), and createTexture().
createImageFromResource()
Image * inet::osg::createImageFromResource (const char * imageName)
 {
     return createImage(resolveImageResource(imageName).c_str());
 }
Referenced by inet::visualizer::TransportConnectionOsgVisualizer::createConnectionEndNode(), inet::visualizer::LinkBreakOsgVisualizer::createLinkBreakVisualization(), inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), and inet::visualizer::SceneOsgVisualizerBase::initializeSceneFloor().
createLine()
Node * inet::osg::createLine (const Coord & start, const Coord & end, cFigure::Arrowhead startArrowhead, cFigure::Arrowhead endArrowhead)
 {
     auto line = inet::osg::createLineGeometry(start, end);
     auto geode = new osg::Geode();
     geode->addDrawable(line);
     auto group = new osg::Group();
     group->addChild(geode);
     if (startArrowhead)
         group->addChild(createArrowhead(end, start));
     if (endArrowhead)
         group->addChild(createArrowhead(start, end));
     return group;
 }
Referenced by inet::visualizer::RoutingTableOsgVisualizer::createRouteVisualization(), and inet::visualizer::SceneOsgVisualizerBase::initializeAxis().
createLineGeometry()
Geometry * inet::osg::createLineGeometry (const Coord & start, const Coord & end)
 {
     auto geometry = new Geometry();
     auto vertices = new Vec3Array();
     vertices->push_back(Vec3(start.x, start.y, start.z));
     vertices->push_back(Vec3(end.x, end.y, end.z));
     auto drawArrays = new DrawArrays(PrimitiveSet::LINE_STRIP);
     drawArrays->setFirst(0);
     drawArrays->setCount(vertices->size());
     geometry->setVertexArray(vertices);
     geometry->addPrimitiveSet(drawArrays);
     return geometry;
 }
Referenced by createLine(), inet::visualizer::NetworkConnectionOsgVisualizer::createNetworkConnectionVisualization(), inet::visualizer::TracingObstacleLossOsgVisualizer::createObstacleLossVisualization(), inet::visualizer::MobilityOsgVisualizer::extendMovementTrail(), and inet::osg::LineNode::LineNode().
createLineStateSet()
StateSet * inet::osg::createLineStateSet (const cFigure::Color & color, const cFigure::LineStyle & style, double width, bool overlay)
 {
     auto stateSet = new StateSet();
     auto material = new Material();
     Vec4 colorVec((double)color.red / 255.0, (double)color.green / 255.0, (double)color.blue / 255.0, 1.0);
     material->setAmbient(Material::FRONT_AND_BACK, colorVec);
     material->setDiffuse(Material::FRONT_AND_BACK, colorVec);
     stateSet->setAttribute(material);
     stateSet->setMode(GL_BLEND, StateAttribute::ON);
     stateSet->setMode(GL_DEPTH_TEST, overlay ? StateAttribute::OFF : StateAttribute::ON);
     stateSet->setMode(GL_LIGHTING, osg::StateAttribute::OFF);
     if (overlay)
         stateSet->setRenderingHint(StateSet::TRANSPARENT_BIN);
     if (width != 1.0) {
         auto lineWidth = new osg::LineWidth();
         lineWidth->setWidth(width);
         stateSet->setAttributeAndModes(lineWidth, osg::StateAttribute::ON);
     }
     if (style != cFigure::LINE_SOLID) {
         auto lineStipple = new osg::LineStipple();
         switch (style) {
             case cFigure::LINE_DOTTED:
                 lineStipple->setPattern(0xAAAA);
                 break;
             case cFigure::LINE_DASHED:
                 lineStipple->setPattern(0xF0F0);
                 break;
             default:
                 throw cRuntimeError("Unknown line style");
         }
         stateSet->setAttributeAndModes(lineStipple, osg::StateAttribute::ON);
     }
     return stateSet;
 }
Referenced by inet::visualizer::LinkOsgVisualizerBase::createLinkVisualization(), inet::visualizer::NetworkConnectionOsgVisualizer::createNetworkConnectionVisualization(), inet::visualizer::TracingObstacleLossOsgVisualizer::createObstacleLossVisualization(), and inet::visualizer::PathOsgVisualizerBase::createPathVisualization().
createPolygonGeometry()
Geometry * inet::osg::createPolygonGeometry (const std::vector< Coord > & points, const Coord & translation)
 {
     auto geometry = new Geometry();
     auto vertices = new Vec3Array();
     for (auto point : points)
         vertices->push_back(Vec3d(point.x + translation.x, point.y + translation.y, point.z + translation.z));
     geometry->setVertexArray(vertices);
     geometry->addPrimitiveSet(new DrawArrays(PrimitiveSet::POLYGON, 0, vertices->size()));
     return geometry;
 }
Referenced by inet::visualizer::PhysicalEnvironmentOsgVisualizer::refreshDisplay().
createPolyline()
Node * inet::osg::createPolyline (const std::vector< Coord > & coords, cFigure::Arrowhead startArrowhead, cFigure::Arrowhead endArrowhead)
 {
     auto line = inet::osg::createPolylineGeometry(coords);
     auto geode = new osg::Geode();
     geode->addDrawable(line);
     auto group = new osg::Group();
     group->addChild(geode);
     if (startArrowhead)
         group->addChild(createArrowhead(coords[1], coords[0]));
     if (endArrowhead)
         group->addChild(createArrowhead(coords[coords.size() - 2], coords[coords.size() - 1]));
     return group;
 }
Referenced by inet::visualizer::PathOsgVisualizerBase::createPathVisualization().
createPolylineGeometry()
Geometry * inet::osg::createPolylineGeometry (const std::vector< Coord > & coords)
 {
     auto geometry = new Geometry();
     auto vertices = new Vec3Array();
     for (auto coord : coords)
         vertices->push_back(Vec3(coord.x, coord.y, coord.z));
     auto drawArrays = new DrawArrays(PrimitiveSet::LINE_STRIP);
     drawArrays->setFirst(0);
     drawArrays->setCount(vertices->size());
     geometry->setVertexArray(vertices);
     geometry->addPrimitiveSet(drawArrays);
     return geometry;
 }
Referenced by createPolyline().
createPositionAttitudeTransform()
PositionAttitudeTransform * inet::osg::createPositionAttitudeTransform (const Coord & position, const Quaternion & orientation)
 {
     auto pat = new PositionAttitudeTransform();
     pat->setPosition(Vec3d(position.x, position.y, position.z));
     pat->setAttitude(osg::Quat(osg::Vec4d(orientation.v.x, orientation.v.y, orientation.v.z, orientation.s)));
     return pat;
 }
Referenced by inet::visualizer::PacketDropOsgVisualizer::createPacketDropVisualization(), and inet::visualizer::PhysicalEnvironmentOsgVisualizer::refreshDisplay().
createQuadGeometry()
Geometry * inet::osg::createQuadGeometry (const Coord & min, const Coord & max)
 {
     auto geometry = new Geometry();
     auto vertices = new Vec3Array();
     vertices->push_back(Vec3(min.x, min.y, min.z));
     vertices->push_back(Vec3(min.x, max.y, min.z));
     vertices->push_back(Vec3(max.x, max.y, min.z));
     vertices->push_back(Vec3(max.x, min.y, min.z));
     geometry->setVertexArray(vertices);
     geometry->addPrimitiveSet(new DrawArrays(PrimitiveSet::QUADS, 0, 4));
     return geometry;
 }
Referenced by inet::visualizer::SceneOsgVisualizerBase::createSceneFloor().
createStateSet()
StateSet * inet::osg::createStateSet (const cFigure::Color & color, double opacity, bool cullBackFace)
 {
     auto stateSet = new StateSet();
     auto material = new Material();
     Vec4 colorVec((double)color.red / 255.0, (double)color.green / 255.0, (double)color.blue / 255.0, opacity);
     material->setAmbient(Material::FRONT_AND_BACK, colorVec);
     material->setDiffuse(Material::FRONT_AND_BACK, colorVec);
     material->setAlpha(Material::FRONT_AND_BACK, opacity);
     stateSet->setAttribute(material);
     stateSet->setMode(GL_BLEND, StateAttribute::ON);
     stateSet->setMode(GL_DEPTH_TEST, StateAttribute::ON);
     stateSet->setRenderingHint(opacity == 1.0 ? StateSet::OPAQUE_BIN : StateSet::TRANSPARENT_BIN);
     if (cullBackFace) {
         auto cullFace = new CullFace();
         cullFace->setMode(CullFace::BACK);
         stateSet->setAttributeAndModes(cullFace, StateAttribute::ON);
     }
     return stateSet;
 }
Referenced by inet::visualizer::MobilityOsgVisualizer::createMobilityVisualization(), inet::visualizer::RoutingTableOsgVisualizer::createRouteVisualization(), inet::visualizer::SceneOsgVisualizerBase::createSceneFloor(), inet::visualizer::SceneOsgVisualizerBase::initializeAxis(), and inet::visualizer::PhysicalEnvironmentOsgVisualizer::refreshDisplay().
createText()
osgText::Text * inet::osg::createText (const char * string, const Coord & position, const cFigure::Color & color)
 {
     auto text = new osgText::Text();
     text->setColor(Vec4(color.red, color.green, color.blue, 1.0));
     text->setCharacterSize(18);
     text->setText(string);
     text->setPosition(Vec3(position.x, position.y, position.z));
     return text;
 }
Referenced by inet::visualizer::SceneOsgVisualizerBase::initializeAxis().
createTexture()
Texture2D * inet::osg::createTexture (const char * fileName, bool repeat)
 {
     auto image = createImage(fileName);
     auto texture = new Texture2D();
     texture->setImage(image);
     if (repeat) {
         texture->setWrap(Texture2D::WRAP_S, Texture2D::REPEAT);
         texture->setWrap(Texture2D::WRAP_T, Texture2D::REPEAT);
         texture->setWrap(Texture2D::WRAP_R, Texture2D::REPEAT);
     }
     return texture;
 }
Referenced by createTextureFromResource().
createTextureFromResource()
Texture2D * inet::osg::createTextureFromResource (const char * imageName, bool repeat)
 {
     return createTexture(resolveImageResource(imageName).c_str(), repeat);
 }
resolveImageResource()
std::string inet::osg::resolveImageResource (const char * imageName, cComponent * context)
 {
     if (context == nullptr)
         context = getSimulation()->getContextModule();
     std::string path;
     for (auto ext : { "", ".png", ".gif", ".jpg" }) {
         path = context->resolveResourcePath((std::string(imageName) + ext).c_str());
         if (!path.empty())
             return path;
     }
     throw cRuntimeError("Image '%s' not found", imageName);
 }
Referenced by createImageFromResource(), and createTextureFromResource().
toCoord()
Coord inet::osg::toCoord (const Vec3d & vec3d) inline
 { return Coord(vec3d.x(), vec3d.y(), vec3d.z()); }
Referenced by inet::osg::LineNode::setEnd(), and inet::osg::LineNode::setStart().
toVec3d()
Vec3d inet::osg::toVec3d (const Coord & coord) inline
 { return Vec3d(coord.x, coord.y, coord.z); }
Referenced by createArrowhead(), inet::osg::LineNode::setEnd(), and inet::osg::LineNode::setStart().