INET Framework for OMNeT++/OMNEST: inet::physicallayer Namespace Reference
inet::physicallayer Namespace Reference
Classes
class _16PpmModulation
class _2GfskModulation
class _4GfskModulation
class _4PpmModulation
class AdditiveScrambler
class AdditiveScramblerModule
class AdditiveScrambling
class AnalogModelBase
class AntennaBase
class AntennaGainFunction
This mathematical function provides the antenna gain over orientation.
class ApskCode
class ApskDecoder
class ApskDemodulator
class ApskDimensionalReceiver
class ApskDimensionalTransmission
class ApskDimensionalTransmitter
class ApskEncoder
class ApskErrorModel
Implements the ApskErrorModel model, see the NED file for details.
class ApskLayeredErrorModel
class ApskLayeredReceiver
class ApskLayeredTransmitter
class ApskModulationBase
Base class for modulations using various amplitude and phase-shift keying.
class ApskModulator
class ApskPhyHeaderSerializer
class ApskRadio
class ApskScalarReceiver
class ApskScalarTransmission
class ApskScalarTransmitter
class ApskSymbol
class Arrival
class AxiallySymmetricAntenna
class BackgroundNoisePowerFunction
This mathematical function provides the background noise power over space, time, and frequency.
class BandListening
class BerParseFile
Radio model for IEEE 802.11.
class BpskModulation
This class implements binary phase-shift keying.
class BreakpointPathLoss
Implementation of a breakpoint path loss model.
class CommunicationCacheBase
class CommunicationLog
class ConfigureRadioCommand
Class generated from inet/physicallayer/wireless/common/contract/packetlevel/RadioControlInfo.msg:25 by opp_msgtool.
class ConstantGainAntenna
class ConstantSpeedPropagation
class ConstantTimePropagation
class ConvolutionalCode
class ConvolutionalCoder
class ConvolutionalCoderModule
class CosineAntenna
class DbpskModulation
class DielectricObstacleLoss
This class computes obstacle loss based on the actual straight path that the radio signal travels from the transmitter to the receiver.
class DimensionalAnalogModel
class DimensionalAnalogModelBase
class DimensionalBackgroundNoise
class DimensionalNoise
class DimensionalReception
class DimensionalReceptionSignalAnalogModel
class DimensionalSignalAnalogModel
class DimensionalSnir
class DimensionalTransmission
class DimensionalTransmissionSignalAnalogModel
class DimensionalTransmitterBase
class DipoleAntenna
class DpskModulationBase
class DqpskModulation
class DsssOqpsk16Modulation
class ErrorModelBase
class EthernetFilledIfgSignal
Class generated from inet/physicallayer/wired/ethernet/EthernetSignal.msg:47 by opp_msgtool.
class EthernetFragmentPhyHeader
Class generated from inet/physicallayer/wired/ethernet/EthernetPhyHeader.msg:71 by opp_msgtool.
class EthernetFragmentPhyHeaderChecker
class EthernetFragmentPhyHeaderInserter
class EthernetFragmentPhyHeaderSerializer
Converts between EtherFragmentPhyHeader and binary (network byte order) Ethernet fragment PHY header.
class EthernetJamSignal
Class generated from inet/physicallayer/wired/ethernet/EthernetSignal.msg:37 by opp_msgtool.
class EthernetPhy
class EthernetPhyHeader
Class generated from inet/physicallayer/wired/ethernet/EthernetPhyHeader.msg:35 by opp_msgtool.
class EthernetPhyHeaderBase
Class generated from inet/physicallayer/wired/ethernet/EthernetPhyHeader.msg:18 by opp_msgtool.
class EthernetPhyHeaderBaseSerializer
Converts between EthernetPhyHeaderBase and binary (network byte order) Ethernet PHY header.
class EthernetPhyHeaderChecker
class EthernetPhyHeaderInserter
class EthernetPhyHeaderSerializer
Converts between EthernetPhyHeader and binary (network byte order) Ethernet PHY header.
class EthernetPhyProtocolDissector
class EthernetSignal
Class generated from inet/physicallayer/wired/ethernet/EthernetSignal.msg:30 by opp_msgtool.
class EthernetSignalBase
Class generated from inet/physicallayer/wired/ethernet/EthernetSignal.msg:21 by opp_msgtool.
class FlatRadioBase
class FlatReceiverBase
class FlatReceptionBase
class FlatTransmissionBase
class FlatTransmitterBase
class FreeSpacePathLoss
This class implements the deterministic free space path loss model.
class FrequencyDependentAttenuationFunction
This mathematical function provides the signal attenuation for any given time and frequency coordinates.
class GfskModulationBase
class GptpProtocolDissector
class GridNeighborCache
class IAnalogDigitalConverter
class IAnalogModel
This interface models how a radio signal attenuates during propagation.
class IAntenna
This interface represents a physical device (a part of the radio) which converts electric signals into radio waves, and vice versa.
class IAntennaGain
This interface represents the directional selectivity of an antenna.
class IApskModulation
class IArrival
This interface represents the space and time coordinates of a transmission arriving at a receiver.
class IBackgroundNoise
This interface models a source which provides background noise over space and time.
class ICode
class ICommunicationCache
This interface is used to store the radios and transmissions of the medium.
class IdealObstacleLoss
class IDecoder
class IDemodulator
class IDigitalAnalogConverter
class IDimensionalSignal
class Ieee80211ArithmeticalBand
class Ieee80211BandBase
class Ieee80211BerTableErrorModel
class Ieee80211Channel
class Ieee80211ChannelInd
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:59 by opp_msgtool.
class Ieee80211ChannelReq
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:51 by opp_msgtool.
class Ieee80211ChannelTagBase
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:42 by opp_msgtool.
class Ieee80211CompliantBands
class Ieee80211ConfigureRadioCommand
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211ControlInfo.msg:19 by opp_msgtool.
class Ieee80211ConvolutionalCode
class Ieee80211DimensionalReceiver
class Ieee80211DimensionalTransmission
class Ieee80211DimensionalTransmitter
class Ieee80211DsssChunkMode
class Ieee80211DsssCompliantModes
Provides the compliant Direct Sequence Spread Spectrum PHY modes as described in the IEEE 802.11-2012 specification clause 16.
class Ieee80211DsssDataMode
class Ieee80211DsssHeaderMode
class Ieee80211DsssMode
Represents a Direct Sequence Spread Spectrum PHY mode as described in IEEE 802.11-2012 specification clause 16.
class Ieee80211DsssOfdmMode
Represents a Direct Sequence Spread Spectrum with Orthogonal Frequency Division Multiplexing PHY mode as described in IEEE 802.11-2012 specification subclause 19.3.2.6.
class Ieee80211DsssPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:63 by opp_msgtool.
class Ieee80211DsssPhyHeaderSerializer
Converts between Ieee80211DsssPhyHeader and binary network byte order IEEE 802.11 DSSS PHY header.
class Ieee80211DsssPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:58 by opp_msgtool.
class Ieee80211DsssPreambleMode
class Ieee80211EnumeratedBand
class Ieee80211ErpOfdmCompliantModes
class Ieee80211ErpOfdmMode
class Ieee80211ErpOfdmPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:127 by opp_msgtool.
class Ieee80211ErpOfdmPhyHeaderSerializer
Converts between Ieee80211ErpOfdmPhyHeader and binary network byte order IEEE 802.11 ERP OFDM PHY header.
class Ieee80211ErpOfdmPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:123 by opp_msgtool.
class Ieee80211ErrorModelBase
class Ieee80211FhssCompliantModes
Provides the compliant Frequency-Hopping Spread Spectrum PHY modes as described in the IEEE 802.11-2012 specification clause 14.
class Ieee80211FhssDataMode
class Ieee80211FhssHeaderMode
class Ieee80211FhssMode
Represents a Frequency-Hopping Spread Spectrum PHY mode as described in IEEE 802.11-2012 specification clause 14.
class Ieee80211FhssPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:32 by opp_msgtool.
class Ieee80211FhssPhyHeaderSerializer
Converts between Ieee80211FhssPhyHeader and binary network byte order IEEE 802.11 FHSS PHY header.
class Ieee80211FhssPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:27 by opp_msgtool.
class Ieee80211FhssPreambleMode
class Ieee80211HrDsssCompliantModes
Provides the compliant High Rate Direct Sequence Spread Spectrum PHY modes as described in the IEEE 802.11-2012 specification clause 17.
class Ieee80211HrDsssDataMode
class Ieee80211HrDsssHeaderMode
class Ieee80211HrDsssMode
Represents a High Rate Direct Sequence Spread Spectrum PHY mode as described in the IEEE 802.11-2012 specification clause 17.
class Ieee80211HrDsssPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:80 by opp_msgtool.
class Ieee80211HrDsssPhyHeaderSerializer
Converts between Ieee80211HrDsssPhyHeader and binary network byte order IEEE 802.11 HR/DSSS PHY header.
class Ieee80211HrDsssPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:76 by opp_msgtool.
class Ieee80211HrDsssPreambleMode
class Ieee80211HtCode
class Ieee80211HtCompliantCodes
class Ieee80211HtCompliantModes
class Ieee80211HtDataMode
class Ieee80211HtInterleaving
class Ieee80211Htmcs
class Ieee80211HtmcsTable
class Ieee80211HtMode
class Ieee80211HtModeBase
class Ieee80211HtPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:138 by opp_msgtool.
class Ieee80211HtPhyHeaderSerializer
Converts between Ieee80211HtPhyHeader and binary network byte order IEEE 802.11 HT PHY header.
class Ieee80211HtPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:134 by opp_msgtool.
class Ieee80211HtPreambleMode
class Ieee80211HtSignalMode
class Ieee80211HtTimingRelatedParametersBase
class Ieee80211IrCompliantModes
Provides the compliant Infrared PHY modes as described in the IEEE 802.11-2012 specification clause 15.
class Ieee80211IrDataMode
class Ieee80211IrHeaderMode
class Ieee80211IrMode
Represents an Infrared PHY mode as described in IEEE 802.11-2012 specification clause 15.
class Ieee80211IrPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:48 by opp_msgtool.
class Ieee80211IrPhyHeaderSerializer
Converts between Ieee80211IrPhyHeader and binary network byte order IEEE 802.11 IR PHY header.
class Ieee80211IrPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:44 by opp_msgtool.
class Ieee80211IrPreambleMode
class Ieee80211LayeredOfdmReceiver
class Ieee80211LayeredOfdmTransmitter
class Ieee80211LayeredTransmission
class Ieee80211ModeBase
class Ieee80211ModeInd
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:35 by opp_msgtool.
class Ieee80211ModeReq
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:27 by opp_msgtool.
class Ieee80211ModeSet
class Ieee80211ModeTagBase
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211Tag.msg:18 by opp_msgtool.
class Ieee80211NistErrorModel
A model for the error rate for different modulations.
class Ieee80211OfdmCode
class Ieee80211OfdmCompliantCodes
class Ieee80211OfdmCompliantModes
class Ieee80211OfdmCompliantModulations
class Ieee80211OfdmDataMode
class Ieee80211OfdmDecoder
class Ieee80211OfdmDecoderModule
class Ieee80211OfdmDemodulator
class Ieee80211OfdmDemodulatorModule
class Ieee80211OfdmEncoder
class Ieee80211OfdmEncoderModule
class Ieee80211OfdmErrorModel
class Ieee80211OfdmInterleaver
class Ieee80211OfdmInterleaverModule
class Ieee80211OfdmInterleaving
class Ieee80211OfdmMode
class Ieee80211OfdmModeBase
class Ieee80211OfdmModulation
class Ieee80211OfdmModulator
class Ieee80211OfdmModulatorModule
class Ieee80211OfdmPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:107 by opp_msgtool.
class Ieee80211OfdmPhyHeaderSerializer
Converts between Ieee80211OfdmPhyHeader and binary network byte order IEEE 802.11 OFDM PHY header.
class Ieee80211OfdmPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:87 by opp_msgtool.
class Ieee80211OfdmPreambleMode
class Ieee80211OfdmRadio
class Ieee80211OfdmReceptionSymbolModel
class Ieee80211OfdmSignalMode
class Ieee80211OfdmSymbol
class Ieee80211OfdmTimingRelatedParametersBase
class Ieee80211OfdmTransmissionSymbolModel
class Ieee80211PhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:18 by opp_msgtool.
class Ieee80211PhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:14 by opp_msgtool.
class Ieee80211PhyProtocolPrinter
class Ieee80211Radio
class Ieee80211ReceiverBase
class Ieee80211ScalarReceiver
class Ieee80211ScalarTransmission
class Ieee80211ScalarTransmitter
class Ieee80211TransmissionBase
class Ieee80211TransmitterBase
class Ieee80211UnitDiskReceiver
class Ieee80211UnitDiskTransmission
class Ieee80211UnitDiskTransmitter
class Ieee80211VhtCode
class Ieee80211VhtCompliantCodes
class Ieee80211VhtCompliantModes
class Ieee80211VhtDataMode
class Ieee80211VhtInterleaving
class Ieee80211Vhtmcs
class Ieee80211VhtmcsTable
class Ieee80211VhtMode
class Ieee80211VhtModeBase
class Ieee80211VhtPhyHeader
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:148 by opp_msgtool.
class Ieee80211VhtPhyHeaderSerializer
Converts between Ieee80211VhtPhyHeader and binary network byte order IEEE 802.11 VHT PHY header.
class Ieee80211VhtPhyPreamble
Class generated from inet/physicallayer/wireless/ieee80211/packetlevel/Ieee80211PhyHeader.msg:144 by opp_msgtool.
class Ieee80211VhtPreambleMode
class Ieee80211VhtSignalMode
class Ieee80211YansErrorModel
Model the error rate for different modulations.
class Ieee802154NarrowbandDimensionalReceiver
class Ieee802154NarrowbandDimensionalTransmitter
class Ieee802154NarrowbandScalarReceiver
class Ieee802154NarrowbandScalarTransmitter
class Ieee802154UwbIrMode
class Ieee802154UwbIrReceiver
class Ieee802154UwbIrTransmitter
This generates pulse-level representation of an IEEE 802.15.4A UWB PHY frame using the mandatory mode (high PRF).
class Ieee8021qTagEpdProtocolDissector
class Ieee8021rTagEpdProtocolDissector
class IEncoder
class IErrorModel
The error model describes how the signal to noise ratio affects the amount of errors at the receiver.
class IFecCoder
class IForwardErrorCorrection
class IIeee80211Band
class IIeee80211DataMode
class IIeee80211HeaderMode
class IIeee80211Mode
class IIeee80211PreambleMode
class IInterference
This interface represents the interference related to a reception.
class IInterleaver
class IInterleaving
class ILayeredErrorModel
The layered error model computes the erroneous bits, symbols, or samples based on the SNIR and a simplified model of the signal processing.
class IListening
This interface represents how a receiver is listening on the radio channel.
class IListeningDecision
This interface represents the result of a receiver's listening process.
class IMediumLimitCache
This interface is used to cache various medium limits among the radios.
class IModulation
This interface represents the process of varying one or more physical properties of a periodic waveform, called the carrier signal, with a modulating signal that typically contains information to be transmitted.
class IModulator
class INarrowbandSignal
class INeighborCache
This interface keeps track of neighbor relationships between radios.
class INoise
This interface represents a meaningless radio signal.
class Interference
class InterpolatingAntenna
TODO refactor to use Delaunay triangulation on unit sphere, i.e.
class IObstacleLoss
This interface models obstacle loss that is the reduction in power density of a radio signal as it propagates through physical objects present in space.
class IPathLoss
This interface models path loss (or path attenuation) that is the reduction in power density of a radio signal as it propagates through space.
class IPropagation
This interface models how a radio signal propagates through space over time.
class IPulseFilter
class IPulseShaper
class IRadio
This interface represents a physical device that is capable of transmitting and receiving radio signals.
class IRadioMedium
This interface represents the whole medium.
class IRadioSignal
class IReceiver
This interface represents a physical device (a part of the radio) which converts electric signals into packets.
class IReception
This interface represents the reception of a transmission at a receiver.
class IReceptionAnalogModel
class IReceptionBitModel
class IReceptionDecision
This interface represents the decisions of a receiver's reception process.
class IReceptionPacketModel
class IReceptionResult
This interface represents the result of a receiver's reception process.
class IReceptionSampleModel
class IReceptionSymbolModel
class IScalarSignal
class IScrambler
class IScrambling
class ISignalAnalogModel
This purely virtual interface provides an abstraction for different radio signal models in the analog domain.
class ISignalBitModel
This purely virtual interface provides an abstraction for different radio signal models in the bit domain.
class ISignalPacketModel
This purely virtual interface provides an abstraction for different radio signal models in the packet domain.
class ISignalSampleModel
This purely virtual interface provides an abstraction for different radio signal models in the waveform or sample domain.
class ISignalSymbolModel
This purely virtual interface provides an abstraction for different radio signal models in the waveform or symbol domain.
class ISnir
class IsotropicAntenna
class IsotropicDimensionalBackgroundNoise
class IsotropicScalarBackgroundNoise
class ISymbol
class ITracingObstacleLoss
class ITransmission
This interface represents the transmission of a radio signal.
class ITransmissionAnalogModel
class ITransmissionBitModel
class ITransmissionPacketModel
class ITransmissionSampleModel
class ITransmissionSymbolModel
class ITransmitter
This interface represents a physical device (a part of the radio) which converts packets into electric signals.
class IWirelessSignal
This purely virtual interface provides an abstraction for different signals.
class LayeredDimensionalAnalogModel
class LayeredErrorModelBase
class LayeredReception
class LayeredReceptionResult
class LayeredScalarAnalogModel
class LayeredTransmission
class ListeningBase
class ListeningDecision
class LogNormalShadowing
This class implements the log normal shadowing model.
class MapCommunicationCache
class MaskModulation
This class implements parameterized amplitude-shift keying that arranges symbols evenly on the x axis.
class MediumLimitCache
class MfskModulation
This modulation implements parameterized frequency-shift keying.
class MpskModulation
This modulation implements parameterized phase-shift keying that arranges symbols evenly on a circle.
class MqamModulation
This class implements gray coded rectangular quadrature amplitude modulation that arranges symbols evenly.
class MqamModulationBase
Base class for gray coded rectangular quadrature amplitude modulations.
class NakagamiFading
This class implements the Nakagami fading model.
class NarrowbandNoiseBase
class NarrowbandRadioBase
class NarrowbandReceiverBase
class NarrowbandReceptionBase
class NarrowbandSignalAnalogModel
class NarrowbandTransmissionBase
class NarrowbandTransmitterBase
class NeighborListNeighborCache
class NoiseBase
class NoiseDimensionalTransmitter
class NoiseSource
class ObstacleLossFunction
This mathematical function provides the obstacle loss over frequency based on a straight path from start to end.
class ParabolicAntenna
class PathLossBase
class PathLossFunction
This mathematical function provides the path loss over space and frequency.
class PhysicalLayerBase
class PpmModulationBase
class PropagatedTransmissionPowerFunction
This mathematical function provides the signal power of a transmission over space, time and frequency.
class PropagationBase
class PulseFilter
class PulseShaper
class Qam1024Modulation
This modulation implements gray coded rectangular quadrature amplitude modulation with 256 symbols.
class Qam16Modulation
This modulation implements gray coded rectangular quadrature amplitude modulation with 16 symbols.
class Qam256Modulation
This modulation implements gray coded rectangular quadrature amplitude modulation with 256 symbols.
class Qam64Modulation
This modulation implements gray coded rectangular quadrature amplitude modulation with 64 symbols.
class QbpskModulation
This class implements quadrature binary phase-shift keying defined in 20.3.9.4.3 HT-SIG definition.
class QpskModulation
This modulation implements quadrature phase-shift keying.
class QuadTreeNeighborCache
class Radio
This class is the default implementation of the IRadio interface.
class RadioMedium
The default implementation of the radio medium interface.
class RayleighFading
This class implements the probabilistic Rayleigh fading model, see Rappaport for more details.
class ReceiverBase
class ReceptionBase
class ReceptionBitModel
class ReceptionDecision
class ReceptionPacketModel
class ReceptionResult
class ReceptionSampleModel
class ReceptionSymbolModel
class ReferenceCommunicationCache
class RicianFading
This class implements the stochastic Rician fading model.
class ScalarAnalogDigitalConverter
class ScalarAnalogModel
class ScalarAnalogModelBase
class ScalarDigitalAnalogConverter
class ScalarNoise
class ScalarReception
class ScalarReceptionSignalAnalogModel
class ScalarSignalAnalogModel
class ScalarSnir
class ScalarTransmission
class ScalarTransmissionSignalAnalogModel
class ShortcutRadio
class Signal
class SignalAnalogModel
class SignalBitModel
class SignalPacketModel
class SignalSampleModel
class SignalSymbolModel
class SnirBase
class SnirReceiverBase
class SpaceAndFrequencyDependentAttenuationFunction
This mathematical function provides the transmission signal attenuation for any given space, time, and frequency coordinates.
class SpaceDependentAttenuationFunction
This mathematical function provides the transmission signal attenuation for any given space, time, and frequency coordinates.
class StateBasedCcEnergyConsumer
This is a simple radio energy consumer model.
class StateBasedEpEnergyConsumer
This is a simple radio power consumer model.
class StochasticErrorModel
Implements the StochasticErrorModel model, see the NED file for details.
class StochasticLayeredErrorModel
class SuiPathLoss
This class implements the empirical Stanford University Interim path loss model.
class TracingObstacleLossBase
class TransmissionBase
class TransmissionBitModel
class TransmissionPacketModel
class TransmissionSampleModel
class TransmissionSymbolModel
class TransmitterBase
class TwoRayGroundReflection
This class implements the two ray ground radio path loss model.
class TwoRayInterference
Two-Ray interference model borrowed from Veins (default parameterization)
class UnitDiskAnalogModel
Implements the UnitDiskAnalogModel model, see the NED file for details.
class UnitDiskListening
This model doesn't specify any listening properties.
class UnitDiskNoise
class UnitDiskRadio
class UnitDiskReceiver
Implements the UnitDiskReceiver model, see the NED file for details.
class UnitDiskReception
This model characterizes receptions with a simplified reception power that falls into one of the categories: receivable, interfering, detectable, and undetectable.
class UnitDiskSnir
class UnitDiskTransmission
This model characterizes transmissions with the communication range, interference range, and detection range.
class UnitDiskTransmitter
Implements the UnitDiskTransmitter model, see the NED file for details.
class UwbIrStochasticPathLoss
Implements the Ghassmezadeh stochastic UWB channel path loss model.
class VectorCommunicationCache
class WireJunction
Models a wiring hub.
class WirelessSignal
Enumerations
enum EthernetPhyHeaderType {
SFD = 1, SMD_E = SFD, SMD_Verify = 2, SMD_Respond = 3,
SMD_Sx = 4, SMD_Cx = 5
}
Enum generated from inet/physicallayer/wired/ethernet/EthernetPhyHeader.msg:41 by opp_msgtool.
enum RadioCommandCode { RADIO_C_CONFIGURE = 1 }
Enum generated from inet/physicallayer/wireless/common/contract/packetlevel/RadioControlInfo.msg:17 by opp_msgtool.
enum Ieee80211HrDsssPreambleType { IEEE80211_HRDSSS_PREAMBLE_TYPE_SHORT, IEEE80211_HRDSSS_PREAMBLE_TYPE_LONG }
Functions
Register_Class (Signal)
Define_Module (WireJunction)
std::ostream & operator<< (std::ostream &os, cMessage *msg)
Define_Module (EthernetFragmentPhyHeaderChecker)
Define_Module (EthernetFragmentPhyHeaderInserter)
Define_Module (EthernetPhy)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetPhyHeaderBase &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetPhyHeaderBase &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetPhyHeaderType &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetPhyHeaderType &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetFragmentPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetFragmentPhyHeader &obj)
Define_Module (EthernetPhyHeaderChecker)
Define_Module (EthernetPhyHeaderInserter)
Register_Serializer (EthernetPhyHeaderBase, EthernetPhyHeaderBaseSerializer)
Register_Serializer (EthernetPhyHeader, EthernetPhyHeaderSerializer)
Register_Serializer (EthernetFragmentPhyHeader, EthernetFragmentPhyHeaderSerializer)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetSignalBase &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetSignalBase &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetSignal &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetSignal &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetJamSignal &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetJamSignal &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const EthernetFilledIfgSignal &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, EthernetFilledIfgSignal &obj)
Define_Module (ApskDecoder)
Define_Module (ApskDemodulator)
Define_Module (ApskEncoder)
Define_Module (ApskLayeredReceiver)
Define_Module (ApskLayeredTransmitter)
Define_Module (ApskModulator)
Register_Serializer (ApskPhyHeader, ApskPhyHeaderSerializer)
Define_Module (ApskLayeredErrorModel)
Define_Module (ApskDimensionalReceiver)
Define_Module (ApskDimensionalTransmitter)
Define_Module (ApskRadio)
Define_Module (ApskScalarReceiver)
Define_Module (ApskScalarTransmitter)
Define_Module (ApskErrorModel)
Define_Module (LayeredDimensionalAnalogModel)
Define_Module (LayeredScalarAnalogModel)
Define_Module (DimensionalAnalogModel)
Define_Module (ScalarAnalogModel)
Define_Module (AxiallySymmetricAntenna)
Define_Module (ConstantGainAntenna)
Define_Module (CosineAntenna)
Define_Module (DipoleAntenna)
Define_Module (InterpolatingAntenna)
Define_Module (IsotropicAntenna)
Define_Module (ParabolicAntenna)
Define_Module (DimensionalBackgroundNoise)
Define_Module (IsotropicDimensionalBackgroundNoise)
Define_Module (IsotropicScalarBackgroundNoise)
Define_Module (FlatRadioBase)
Define_Module (NarrowbandRadioBase)
Define_Module (MapCommunicationCache)
Define_Module (ReferenceCommunicationCache)
Define_Module (VectorCommunicationCache)
Register_Enum (inet::physicallayer::IRadio::RadioMode,(IRadio::RADIO_MODE_OFF, IRadio::RADIO_MODE_SLEEP, IRadio::RADIO_MODE_RECEIVER, IRadio::RADIO_MODE_TRANSMITTER, IRadio::RADIO_MODE_TRANSCEIVER, IRadio::RADIO_MODE_SWITCHING))
Register_Enum (inet::physicallayer::IRadio::ReceptionState,(IRadio::RECEPTION_STATE_UNDEFINED, IRadio::RECEPTION_STATE_IDLE, IRadio::RECEPTION_STATE_BUSY, IRadio::RECEPTION_STATE_RECEIVING))
Register_Enum (inet::physicallayer::IRadio::TransmissionState,(IRadio::TRANSMISSION_STATE_UNDEFINED, IRadio::TRANSMISSION_STATE_IDLE, IRadio::TRANSMISSION_STATE_TRANSMITTING))
Register_Enum (inet::physicallayer::IRadioSignal::SignalPart,(IRadioSignal::SIGNAL_PART_NONE, IRadioSignal::SIGNAL_PART_WHOLE, IRadioSignal::SIGNAL_PART_PREAMBLE, IRadioSignal::SIGNAL_PART_HEADER, IRadioSignal::SIGNAL_PART_DATA))
void doParsimPacking (omnetpp::cCommBuffer *b, const RadioCommandCode &e)
void doParsimUnpacking (omnetpp::cCommBuffer *b, RadioCommandCode &e)
void doParsimPacking (omnetpp::cCommBuffer *b, const ConfigureRadioCommand &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, ConfigureRadioCommand &obj)
Define_Module (StateBasedCcEnergyConsumer)
Define_Module (StateBasedEpEnergyConsumer)
Define_Module (StochasticLayeredErrorModel)
Define_Module (StochasticErrorModel)
Define_Module (MediumLimitCache)
template<typename T >
T minIgnoreNaN (T a, T b)
template<typename T >
T maxIgnoreNaN (T a, T b)
double maxIgnoreNaN (double a, double b)
Define_Module (RadioMedium)
Define_Module (GridNeighborCache)
Define_Module (NeighborListNeighborCache)
Define_Module (QuadTreeNeighborCache)
Define_Module (DielectricObstacleLoss)
Define_Module (IdealObstacleLoss)
Define_Module (BreakpointPathLoss)
Define_Module (FreeSpacePathLoss)
Define_Module (LogNormalShadowing)
Define_Module (NakagamiFading)
Define_Module (RayleighFading)
Define_Module (RicianFading)
Define_Module (SuiPathLoss)
Define_Module (TwoRayGroundReflection)
Define_Module (TwoRayInterference)
Define_Module (ConstantSpeedPropagation)
Define_Module (ConstantTimePropagation)
Define_Module (AdditiveScramblerModule)
Define_Module (ConvolutionalCoderModule)
Define_Module (Radio)
Define_Module (Ieee80211OfdmErrorModel)
Define_Module (Ieee80211LayeredOfdmReceiver)
Define_Module (Ieee80211LayeredOfdmTransmitter)
Define_Module (Ieee80211OfdmDecoderModule)
Define_Module (Ieee80211OfdmDemodulatorModule)
Define_Module (Ieee80211OfdmEncoderModule)
Define_Module (Ieee80211OfdmInterleaverModule)
Define_Module (Ieee80211OfdmModulatorModule)
Define_Module (Ieee80211OfdmRadio)
std::ostream & operator<< (std::ostream &out, const Ieee80211OfdmSymbol &symbol)
Register_Abstract_Class (Ieee80211ModeSet)
Define_Module (Ieee80211BerTableErrorModel)
Define_Module (Ieee80211NistErrorModel)
Define_Module (Ieee80211YansErrorModel)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ConfigureRadioCommand &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ConfigureRadioCommand &obj)
Define_Module (Ieee80211DimensionalReceiver)
Define_Module (Ieee80211DimensionalTransmitter)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211PhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211PhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211FhssPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211FhssPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211FhssPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211FhssPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211IrPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211IrPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211IrPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211IrPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211DsssPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211DsssPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211DsssPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211DsssPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211HrDsssPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211HrDsssPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211HrDsssPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211HrDsssPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211OfdmPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211OfdmPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211OfdmPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211OfdmPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ErpOfdmPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ErpOfdmPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ErpOfdmPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ErpOfdmPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211HtPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211HtPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211HtPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211HtPhyHeader &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211VhtPhyPreamble &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211VhtPhyPreamble &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211VhtPhyHeader &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211VhtPhyHeader &obj)
Register_Serializer (Ieee80211FhssPhyHeader, Ieee80211FhssPhyHeaderSerializer)
Register_Serializer (Ieee80211IrPhyHeader, Ieee80211IrPhyHeaderSerializer)
Register_Serializer (Ieee80211DsssPhyHeader, Ieee80211DsssPhyHeaderSerializer)
Register_Serializer (Ieee80211HrDsssPhyHeader, Ieee80211HrDsssPhyHeaderSerializer)
Register_Serializer (Ieee80211OfdmPhyHeader, Ieee80211OfdmPhyHeaderSerializer)
Register_Serializer (Ieee80211ErpOfdmPhyHeader, Ieee80211ErpOfdmPhyHeaderSerializer)
Register_Serializer (Ieee80211HtPhyHeader, Ieee80211HtPhyHeaderSerializer)
Register_Serializer (Ieee80211VhtPhyHeader, Ieee80211VhtPhyHeaderSerializer)
Define_Module (Ieee80211Radio)
Define_Module (Ieee80211ScalarReceiver)
Define_Module (Ieee80211ScalarTransmitter)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ModeTagBase &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ModeTagBase &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ModeReq &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ModeReq &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ModeInd &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ModeInd &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ChannelTagBase &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ChannelTagBase &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ChannelReq &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ChannelReq &obj)
void doParsimPacking (omnetpp::cCommBuffer *b, const Ieee80211ChannelInd &obj)
void doParsimUnpacking (omnetpp::cCommBuffer *b, Ieee80211ChannelInd &obj)
Define_Module (Ieee80211UnitDiskReceiver)
Define_Module (Ieee80211UnitDiskTransmitter)
Define_Module (Ieee802154UwbIrReceiver)
Define_Module (Ieee802154UwbIrTransmitter)
Define_Module (Ieee802154NarrowbandDimensionalReceiver)
Define_Module (Ieee802154NarrowbandDimensionalTransmitter)
Define_Module (Ieee802154NarrowbandScalarReceiver)
Define_Module (Ieee802154NarrowbandScalarTransmitter)
Define_Module (NoiseDimensionalTransmitter)
Define_Module (NoiseSource)
Define_Module (ShortcutRadio)
Define_Module (UnitDiskAnalogModel)
Define_Module (UnitDiskRadio)
Define_Module (UnitDiskReceiver)
Register_Enum (inet::physicallayer::UnitDiskReception::Power,(UnitDiskReception::POWER_UNDETECTABLE, UnitDiskReception::POWER_DETECTABLE, UnitDiskReception::POWER_INTERFERING, UnitDiskReception::POWER_RECEIVABLE))
Define_Module (UnitDiskTransmitter)
Variables
const B ETHERNET_PHY_HEADER_LEN = B(8)
const double k = 1 / sqrt(682)
Enumeration Type Documentation
EthernetPhyHeaderType
enum inet::physicallayer::EthernetPhyHeaderType
Enum generated from inet/physicallayer/wired/ethernet/EthernetPhyHeader.msg:41 by opp_msgtool.
//
// http://www.enodenetworks.com/assets/docs/8023br.pdf
//
enum EthernetPhyHeaderType
{
    SFD = 1;         // 0xD5
    SMD_E = SFD;
    SMD_Verify = 2;  // 0x07
    SMD_Respond = 3; // 0x19
    SMD_Sx = 4;      // 0xE6, 0x4C, 0x7F or 0xB3, see smdNumber in EthernetPhyHeader
    SMD_Cx = 5;      // 0x61, 0x52, 0x9E or 0x2A, see smdNumber in EthernetPhyHeader
}
Enumerator
SFD
SMD_E
SMD_Verify
SMD_Respond
SMD_Sx
SMD_Cx
{
     SFD = 1,
     SMD_E = SFD,
     SMD_Verify = 2,
     SMD_Respond = 3,
     SMD_Sx = 4,
     SMD_Cx = 5
 };
Ieee80211HrDsssPreambleType
enum inet::physicallayer::Ieee80211HrDsssPreambleType
Enumerator
IEEE80211_HRDSSS_PREAMBLE_TYPE_SHORT
IEEE80211_HRDSSS_PREAMBLE_TYPE_LONG
{
     IEEE80211_HRDSSS_PREAMBLE_TYPE_SHORT,
     IEEE80211_HRDSSS_PREAMBLE_TYPE_LONG,
 };
RadioCommandCode
enum inet::physicallayer::RadioCommandCode
Enum generated from inet/physicallayer/wireless/common/contract/packetlevel/RadioControlInfo.msg:17 by opp_msgtool.
//
// Message kinds for sending commands to the radio.
//
enum RadioCommandCode
{
    RADIO_C_CONFIGURE = 1;
}
Enumerator
RADIO_C_CONFIGURE
                       {
     RADIO_C_CONFIGURE = 1
 };
Function Documentation
Define_Module() [1/95]
inet::physicallayer::Define_Module (AdditiveScramblerModule)
Define_Module() [2/95]
inet::physicallayer::Define_Module (ApskDecoder)
Define_Module() [3/95]
inet::physicallayer::Define_Module (ApskDemodulator)
Define_Module() [4/95]
inet::physicallayer::Define_Module (ApskDimensionalReceiver)
Define_Module() [5/95]
inet::physicallayer::Define_Module (ApskDimensionalTransmitter)
Define_Module() [6/95]
inet::physicallayer::Define_Module (ApskEncoder)
Define_Module() [7/95]
inet::physicallayer::Define_Module (ApskErrorModel)
Define_Module() [8/95]
inet::physicallayer::Define_Module (ApskLayeredErrorModel)
Define_Module() [9/95]
inet::physicallayer::Define_Module (ApskLayeredReceiver)
Define_Module() [10/95]
inet::physicallayer::Define_Module (ApskLayeredTransmitter)
Define_Module() [11/95]
inet::physicallayer::Define_Module (ApskModulator)
Define_Module() [12/95]
inet::physicallayer::Define_Module (ApskRadio)
Define_Module() [13/95]
inet::physicallayer::Define_Module (ApskScalarReceiver)
Define_Module() [14/95]
inet::physicallayer::Define_Module (ApskScalarTransmitter)
Define_Module() [15/95]
inet::physicallayer::Define_Module (AxiallySymmetricAntenna)
Define_Module() [16/95]
inet::physicallayer::Define_Module (BreakpointPathLoss)
Define_Module() [17/95]
inet::physicallayer::Define_Module (ConstantGainAntenna)
Define_Module() [18/95]
inet::physicallayer::Define_Module (ConstantSpeedPropagation)
Define_Module() [19/95]
inet::physicallayer::Define_Module (ConstantTimePropagation)
Define_Module() [20/95]
inet::physicallayer::Define_Module (ConvolutionalCoderModule)
Define_Module() [21/95]
inet::physicallayer::Define_Module (CosineAntenna)
Define_Module() [22/95]
inet::physicallayer::Define_Module (DielectricObstacleLoss)
Define_Module() [23/95]
inet::physicallayer::Define_Module (DimensionalAnalogModel)
Define_Module() [24/95]
inet::physicallayer::Define_Module (DimensionalBackgroundNoise)
Define_Module() [25/95]
inet::physicallayer::Define_Module (DipoleAntenna)
Define_Module() [26/95]
inet::physicallayer::Define_Module (EthernetFragmentPhyHeaderChecker)
Define_Module() [27/95]
inet::physicallayer::Define_Module (EthernetFragmentPhyHeaderInserter)
Define_Module() [28/95]
inet::physicallayer::Define_Module (EthernetPhy)
Define_Module() [29/95]
inet::physicallayer::Define_Module (EthernetPhyHeaderChecker)
Define_Module() [30/95]
inet::physicallayer::Define_Module (EthernetPhyHeaderInserter)
Define_Module() [31/95]
inet::physicallayer::Define_Module (FlatRadioBase)
Define_Module() [32/95]
inet::physicallayer::Define_Module (FreeSpacePathLoss)
Define_Module() [33/95]
inet::physicallayer::Define_Module (GridNeighborCache)
Define_Module() [34/95]
inet::physicallayer::Define_Module (IdealObstacleLoss)
Define_Module() [35/95]
inet::physicallayer::Define_Module (Ieee80211BerTableErrorModel)
Define_Module() [36/95]
inet::physicallayer::Define_Module (Ieee80211DimensionalReceiver)
Define_Module() [37/95]
inet::physicallayer::Define_Module (Ieee80211DimensionalTransmitter)
Define_Module() [38/95]
inet::physicallayer::Define_Module (Ieee80211LayeredOfdmReceiver)
Define_Module() [39/95]
inet::physicallayer::Define_Module (Ieee80211LayeredOfdmTransmitter)
Define_Module() [40/95]
inet::physicallayer::Define_Module (Ieee80211NistErrorModel)
Define_Module() [41/95]
inet::physicallayer::Define_Module (Ieee80211OfdmDecoderModule)
Define_Module() [42/95]
inet::physicallayer::Define_Module (Ieee80211OfdmDemodulatorModule)
Define_Module() [43/95]
inet::physicallayer::Define_Module (Ieee80211OfdmEncoderModule)
Define_Module() [44/95]
inet::physicallayer::Define_Module (Ieee80211OfdmErrorModel)
Define_Module() [45/95]
inet::physicallayer::Define_Module (Ieee80211OfdmInterleaverModule)
Define_Module() [46/95]
inet::physicallayer::Define_Module (Ieee80211OfdmModulatorModule)
Define_Module() [47/95]
inet::physicallayer::Define_Module (Ieee80211OfdmRadio)
Define_Module() [48/95]
inet::physicallayer::Define_Module (Ieee80211Radio)
Define_Module() [49/95]
inet::physicallayer::Define_Module (Ieee80211ScalarReceiver)
Define_Module() [50/95]
inet::physicallayer::Define_Module (Ieee80211ScalarTransmitter)
Define_Module() [51/95]
inet::physicallayer::Define_Module (Ieee80211UnitDiskReceiver)
Define_Module() [52/95]
inet::physicallayer::Define_Module (Ieee80211UnitDiskTransmitter)
Define_Module() [53/95]
inet::physicallayer::Define_Module (Ieee80211YansErrorModel)
Define_Module() [54/95]
inet::physicallayer::Define_Module (Ieee802154NarrowbandDimensionalReceiver)
Define_Module() [55/95]
inet::physicallayer::Define_Module (Ieee802154NarrowbandDimensionalTransmitter)
Define_Module() [56/95]
inet::physicallayer::Define_Module (Ieee802154NarrowbandScalarReceiver)
Define_Module() [57/95]
inet::physicallayer::Define_Module (Ieee802154NarrowbandScalarTransmitter)
Define_Module() [58/95]
inet::physicallayer::Define_Module (Ieee802154UwbIrReceiver)
Define_Module() [59/95]
inet::physicallayer::Define_Module (Ieee802154UwbIrTransmitter)
Define_Module() [60/95]
inet::physicallayer::Define_Module (InterpolatingAntenna)
Define_Module() [61/95]
inet::physicallayer::Define_Module (IsotropicAntenna)
Define_Module() [62/95]
inet::physicallayer::Define_Module (IsotropicDimensionalBackgroundNoise)
Define_Module() [63/95]
inet::physicallayer::Define_Module (IsotropicScalarBackgroundNoise)
Define_Module() [64/95]
inet::physicallayer::Define_Module (LayeredDimensionalAnalogModel)
Define_Module() [65/95]
inet::physicallayer::Define_Module (LayeredScalarAnalogModel)
Define_Module() [66/95]
inet::physicallayer::Define_Module (LogNormalShadowing)
Define_Module() [67/95]
inet::physicallayer::Define_Module (MapCommunicationCache)
Define_Module() [68/95]
inet::physicallayer::Define_Module (MediumLimitCache)
Define_Module() [69/95]
inet::physicallayer::Define_Module (NakagamiFading)
Define_Module() [70/95]
inet::physicallayer::Define_Module (NarrowbandRadioBase)
Define_Module() [71/95]
inet::physicallayer::Define_Module (NeighborListNeighborCache)
Define_Module() [72/95]
inet::physicallayer::Define_Module (NoiseDimensionalTransmitter)
Define_Module() [73/95]
inet::physicallayer::Define_Module (NoiseSource)
Define_Module() [74/95]
inet::physicallayer::Define_Module (ParabolicAntenna)
Define_Module() [75/95]
inet::physicallayer::Define_Module (QuadTreeNeighborCache)
Define_Module() [76/95]
inet::physicallayer::Define_Module (Radio)
Define_Module() [77/95]
inet::physicallayer::Define_Module (RadioMedium)
Define_Module() [78/95]
inet::physicallayer::Define_Module (RayleighFading)
Define_Module() [79/95]
inet::physicallayer::Define_Module (ReferenceCommunicationCache)
Define_Module() [80/95]
inet::physicallayer::Define_Module (RicianFading)
Define_Module() [81/95]
inet::physicallayer::Define_Module (ScalarAnalogModel)
Define_Module() [82/95]
inet::physicallayer::Define_Module (ShortcutRadio)
Define_Module() [83/95]
inet::physicallayer::Define_Module (StateBasedCcEnergyConsumer)
Define_Module() [84/95]
inet::physicallayer::Define_Module (StateBasedEpEnergyConsumer)
Define_Module() [85/95]
inet::physicallayer::Define_Module (StochasticErrorModel)
Define_Module() [86/95]
inet::physicallayer::Define_Module (StochasticLayeredErrorModel)
Define_Module() [87/95]
inet::physicallayer::Define_Module (SuiPathLoss)
Define_Module() [88/95]
inet::physicallayer::Define_Module (TwoRayGroundReflection)
Define_Module() [89/95]
inet::physicallayer::Define_Module (TwoRayInterference)
Define_Module() [90/95]
inet::physicallayer::Define_Module (UnitDiskAnalogModel)
Define_Module() [91/95]
inet::physicallayer::Define_Module (UnitDiskRadio)
Define_Module() [92/95]
inet::physicallayer::Define_Module (UnitDiskReceiver)
Define_Module() [93/95]
inet::physicallayer::Define_Module (UnitDiskTransmitter)
Define_Module() [94/95]
inet::physicallayer::Define_Module (VectorCommunicationCache)
Define_Module() [95/95]
inet::physicallayer::Define_Module (WireJunction)
doParsimPacking() [1/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const ConfigureRadioCommand & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [2/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetFilledIfgSignal & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [3/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetFragmentPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [4/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetJamSignal & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [5/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [6/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetPhyHeaderBase & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [7/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetPhyHeaderType & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimPacking() [8/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetSignal & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [9/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const EthernetSignalBase & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [10/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ChannelInd & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [11/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ChannelReq & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [12/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ChannelTagBase & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [13/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ConfigureRadioCommand & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [14/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211DsssPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [15/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211DsssPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [16/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ErpOfdmPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [17/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ErpOfdmPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [18/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211FhssPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [19/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211FhssPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [20/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211HrDsssPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [21/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211HrDsssPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [22/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211HtPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [23/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211HtPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [24/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211IrPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [25/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211IrPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [26/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ModeInd & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [27/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ModeReq & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [28/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211ModeTagBase & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [29/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211OfdmPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [30/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211OfdmPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [31/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [32/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211PhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [33/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211VhtPhyHeader & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [34/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const Ieee80211VhtPhyPreamble & obj) inline
 {obj.parsimPack(b);}
doParsimPacking() [35/35]
void inet::physicallayer::doParsimPacking (omnetpp::cCommBuffer * b, const RadioCommandCode & e) inline
 { b->pack(static_cast<int>(e)); }
doParsimUnpacking() [1/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, ConfigureRadioCommand & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [2/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetFilledIfgSignal & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [3/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetFragmentPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [4/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetJamSignal & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [5/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [6/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetPhyHeaderBase & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [7/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetPhyHeaderType & e) inline
 { int n; b->unpack(n); e = static_cast<EthernetPhyHeaderType>(n); }
doParsimUnpacking() [8/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetSignal & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [9/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, EthernetSignalBase & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [10/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ChannelInd & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [11/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ChannelReq & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [12/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ChannelTagBase & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [13/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ConfigureRadioCommand & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [14/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211DsssPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [15/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211DsssPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [16/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ErpOfdmPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [17/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ErpOfdmPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [18/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211FhssPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [19/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211FhssPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [20/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211HrDsssPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [21/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211HrDsssPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [22/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211HtPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [23/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211HtPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [24/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211IrPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [25/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211IrPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [26/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ModeInd & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [27/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ModeReq & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [28/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211ModeTagBase & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [29/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211OfdmPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [30/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211OfdmPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [31/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [32/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211PhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [33/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211VhtPhyHeader & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [34/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, Ieee80211VhtPhyPreamble & obj) inline
 {obj.parsimUnpack(b);}
doParsimUnpacking() [35/35]
void inet::physicallayer::doParsimUnpacking (omnetpp::cCommBuffer * b, RadioCommandCode & e) inline
 { int n; b->unpack(n); e = static_cast<RadioCommandCode>(n); }
maxIgnoreNaN() [1/2]
double inet::physicallayer::maxIgnoreNaN (double a, double b) inline
 {
     if (std::isnan(a))
         return b;
     else if (std::isnan(b))
         return a;
     else if (a > b)
         return a;
     else
         return b;
 }
maxIgnoreNaN() [2/2]
template<typename T > T inet::physicallayer::maxIgnoreNaN (T a, T b) inline
 {
     if (std::isnan(a.get()))
         return b;
     else if (std::isnan(b.get()))
         return a;
     else if (a > b)
         return a;
     else
         return b;
 }
Referenced by inet::physicallayer::MediumLimitCache::computeMaxAntennaGain(), inet::physicallayer::MediumLimitCache::computeMaxCommunicationRange(), inet::physicallayer::MediumLimitCache::computeMaxInterferenceRange(), inet::physicallayer::MediumLimitCache::computeMaxSpeed(), and inet::physicallayer::MediumLimitCache::computeMaxTransmissionPower().
minIgnoreNaN()
template<typename T > T inet::physicallayer::minIgnoreNaN (T a, T b) inline
 {
     if (std::isnan(a.get()))
         return b;
     else if (std::isnan(b.get()))
         return a;
     else if (a < b)
         return a;
     else
         return b;
 }
Referenced by inet::physicallayer::MediumLimitCache::computeMinInterferencePower(), and inet::physicallayer::MediumLimitCache::computeMinReceptionPower().
operator<<() [1/2]
std::ostream& inet::physicallayer::operator<< (std::ostream & os, cMessage * msg) inline
 {
     os << "(" << msg->getClassName() << ")" << msg->getFullName();
     return os;
 }
operator<<() [2/2]
std::ostream& inet::physicallayer::operator<< (std::ostream & out, const Ieee80211OfdmSymbol & symbol)
 {
     if (symbol.subcarrierSymbols[0])
         out << *symbol.subcarrierSymbols[0];
     else
         out << "UNDEFINED SYMBOL";
     for (unsigned int i = 1; i < symbol.subcarrierSymbols.size(); i++)
         if (symbol.subcarrierSymbols[i])
             out << " " << *symbol.subcarrierSymbols[i];
         else
             out << " UNDEFINED SYMBOL";
     return out;
 }
Register_Abstract_Class()
inet::physicallayer::Register_Abstract_Class (Ieee80211ModeSet)
Register_Class()
inet::physicallayer::Register_Class (Signal)
Register_Enum() [1/5]
inet::physicallayer::Register_Enum (inet::physicallayer::IRadio::RadioMode , (IRadio::RADIO_MODE_OFF, IRadio::RADIO_MODE_SLEEP, IRadio::RADIO_MODE_RECEIVER, IRadio::RADIO_MODE_TRANSMITTER, IRadio::RADIO_MODE_TRANSCEIVER, IRadio::RADIO_MODE_SWITCHING))
Register_Enum() [2/5]
inet::physicallayer::Register_Enum (inet::physicallayer::IRadio::ReceptionState , (IRadio::RECEPTION_STATE_UNDEFINED, IRadio::RECEPTION_STATE_IDLE, IRadio::RECEPTION_STATE_BUSY, IRadio::RECEPTION_STATE_RECEIVING))
Register_Enum() [3/5]
inet::physicallayer::Register_Enum (inet::physicallayer::IRadio::TransmissionState , (IRadio::TRANSMISSION_STATE_UNDEFINED, IRadio::TRANSMISSION_STATE_IDLE, IRadio::TRANSMISSION_STATE_TRANSMITTING))
Register_Enum() [4/5]
inet::physicallayer::Register_Enum (inet::physicallayer::IRadioSignal::SignalPart , (IRadioSignal::SIGNAL_PART_NONE, IRadioSignal::SIGNAL_PART_WHOLE, IRadioSignal::SIGNAL_PART_PREAMBLE, IRadioSignal::SIGNAL_PART_HEADER, IRadioSignal::SIGNAL_PART_DATA))
Register_Enum() [5/5]
inet::physicallayer::Register_Enum (inet::physicallayer::UnitDiskReception::Power , (UnitDiskReception::POWER_UNDETECTABLE, UnitDiskReception::POWER_DETECTABLE, UnitDiskReception::POWER_INTERFERING, UnitDiskReception::POWER_RECEIVABLE))
Register_Serializer() [1/12]
inet::physicallayer::Register_Serializer (ApskPhyHeader , ApskPhyHeaderSerializer)
Register_Serializer() [2/12]
inet::physicallayer::Register_Serializer (EthernetFragmentPhyHeader , EthernetFragmentPhyHeaderSerializer)
Register_Serializer() [3/12]
inet::physicallayer::Register_Serializer (EthernetPhyHeader , EthernetPhyHeaderSerializer)
Register_Serializer() [4/12]
inet::physicallayer::Register_Serializer (EthernetPhyHeaderBase , EthernetPhyHeaderBaseSerializer)
Register_Serializer() [5/12]
inet::physicallayer::Register_Serializer (Ieee80211DsssPhyHeader , Ieee80211DsssPhyHeaderSerializer)
Register_Serializer() [6/12]
inet::physicallayer::Register_Serializer (Ieee80211ErpOfdmPhyHeader , Ieee80211ErpOfdmPhyHeaderSerializer)
Register_Serializer() [7/12]
inet::physicallayer::Register_Serializer (Ieee80211FhssPhyHeader , Ieee80211FhssPhyHeaderSerializer)
Register_Serializer() [8/12]
inet::physicallayer::Register_Serializer (Ieee80211HrDsssPhyHeader , Ieee80211HrDsssPhyHeaderSerializer)
Register_Serializer() [9/12]
inet::physicallayer::Register_Serializer (Ieee80211HtPhyHeader , Ieee80211HtPhyHeaderSerializer)
Register_Serializer() [10/12]
inet::physicallayer::Register_Serializer (Ieee80211IrPhyHeader , Ieee80211IrPhyHeaderSerializer)
Register_Serializer() [11/12]
inet::physicallayer::Register_Serializer (Ieee80211OfdmPhyHeader , Ieee80211OfdmPhyHeaderSerializer)
Register_Serializer() [12/12]
inet::physicallayer::Register_Serializer (Ieee80211VhtPhyHeader , Ieee80211VhtPhyHeaderSerializer)
Variable Documentation
ETHERNET_PHY_HEADER_LEN
const B inet::physicallayer::ETHERNET_PHY_HEADER_LEN = B(8)
k
const double inet::physicallayer::k = 1 / sqrt(682)
Referenced by inet::osm::Tags::add(), inet::Ipv4FlatNetworkConfigurator::addDefaultRoutes(), inet::GateScheduleConfiguratorBase::addFlows(), inet::Ipv4FlatNetworkConfigurator::assignAddresses(), inet::physicallayer::Ieee80211YansErrorModel::binomialCoefficient(), inet::physicallayer::DsssOqpsk16Modulation::calculateBER(), inet::ospfv3::Ospfv3Area::calculateShortestPathTree(), inet::ospfv3::Ospfv3NeighborState::changeState(), inet::FailureProtectionConfigurator::checkLinkFailureProtection(), inet::FailureProtectionConfigurator::checkNodeFailureProtection(), inet::IpvxTrafGen::chooseDestAddr(), inet::UdpBasicApp::chooseDestAddr(), inet::UdpBasicBurst::chooseDestAddr(), inet::physicallayer::ConvolutionalCoder::computeHammingDistanceLookupTable(), inet::Cuboid::computeIntersection(), inet::physicallayer::DielectricObstacleLoss::computeReflectionLoss(), inet::StreamRedundancyConfigurator::computeStreamEncodings(), inet::StreamRedundancyConfigurator::computeStreamSendersAndReceivers(), inet::Ipv6FlatNetworkConfigurator::configureAdvPrefixes(), inet::PimInterfaceTable::configureInterfaces(), inet::TSNschedGateScheduleConfigurator::convertInputToJson(), inet::TSNschedGateScheduleConfigurator::convertJsonToOutput(), inet::ospfv2::Neighbor::createDatabaseSummary(), inet::PatternMatcher::debugStrFrom(), inet::SpatialGrid::decodeRowMajorIndex(), inet::PimPacketSerializer::deserialize(), inet::IgmpHeaderSerializer::deserialize(), inet::bgp::BgpHeaderSerializer::deserialize(), inet::sctp::SctpHeaderSerializer::deserialize(), inet::RsvpTe::doCACCheck(), inet::PatternMatcher::doMatch(), inet::Ipv6ExtHeaderTagBase::dropExtensionHeader(), inet::Ipv6Header::dropExtensionHeader(), inet::tcp::TcpHeader::dropHeaderOption(), inet::Ipv4OptionsTagBase::dropOption(), inet::Ipv6NdOptions::dropOption(), inet::bgp::BgpOpenMessage::dropOptionalParameter(), inet::PimHello::dropOptions(), inet::ospfv2::Ospfv2LinkStateUpdatePacket::dropOspfLSAs(), inet::bgp::BgpUpdateMessage::dropPathAttributes(), inet::TlvOptions::dropTlvOption(), inet::Ipv4NetworkConfigurator::dumpConfig(), inet::PostureTransition::extractMatrixFromSteadyState(), inet::physicallayer::Ieee80211YansErrorModel::factorial(), inet::Ldp::findPeerAddrFromInterface(), inet::ospfv2::Ospfv2Interface::floodLsa(), inet::ospfv3::Ospfv3Interface::floodLSA(), inet::osm::Tags::get(), inet::dymo::RteMsg::getAddedNodeForUpdate(), inet::MacAddress::getAddressByte(), inet::sctp::SctpInitChunk::getAddressesForUpdate(), inet::sctp::SctpInitAckChunk::getAddressesForUpdate(), inet::Ipv6RoutingHeader::getAddressForUpdate(), inet::PingApp::getAllAddresses(), inet::sctp::SctpAsconfChunk::getAsconfParams(), inet::sctp::SctpAsconfChunk_Base::getAsconfParamsForUpdate(), inet::sctp::SctpAsconfAckChunk::getAsconfResponse(), inet::sctp::SctpAsconfAckChunk_Base::getAsconfResponseForUpdate(), inet::ospfv3::Ospfv3NetworkLsa::getAttachedRouterForUpdate(), inet::ospfv2::Ospfv2NetworkLsa::getAttachedRoutersForUpdate(), inet::ieee80211::Ieee80211BasicBlockAck::getBlockAckBitmapForUpdate(), inet::ieee80211::Ieee80211Prim_ScanConfirm::getBssListForUpdate(), inet::DhcpOptions::getDnsForUpdate(), inet::RipPacket::getEntryForUpdate(), inet::Ipv6ExtHeaderTagBase::getExtensionHeaderForUpdate(), inet::Ipv6Header::getExtensionHeaderForUpdate(), inet::ospfv2::Ospfv2AsExternalLsaContents::getExternalTOSInfoForUpdate(), inet::Igmpv3Report::getGroupRecordForUpdate(), inet::tcp::TcpHeader::getHeaderOptionForUpdate(), inet::ospfv3::Ospfv3LinkStateUpdatePacket::getInterAreaPrefixLSAsForUpdate(), inet::eigrp::EigrpDisabledInterfaces::getInterface(), inet::PimInterfaceTable::getInterface(), inet::InterfaceTable::getInterface(), inet::eigrp::EigrpInterfaceTable::getInterface(), inet::EigrpIpv4Message::getInterRoutesForUpdate(), inet::EigrpIpv6Message::getInterRoutesForUpdate(), inet::ospfv3::Ospfv3LinkStateUpdatePacket::getIntraAreaPrefixLSAsForUpdate(), inet::JoinPruneGroup::getJoinedSourceAddressForUpdate(), inet::PimJoinPrune::getJoinPruneGroupsForUpdate(), inet::LinkStateMsg::getLinkInfoForUpdate(), inet::ospfv3::Ospfv3LinkStateUpdatePacket::getLinkLSAsForUpdate(), inet::ospfv2::Ospfv2RouterLsa::getLinksForUpdate(), inet::ospfv2::Ospfv2DatabaseDescriptionPacket::getLsaHeadersForUpdate(), inet::ospfv2::Ospfv2LinkStateAcknowledgementPacket::getLsaHeadersForUpdate(), inet::ospfv3::Ospfv3DatabaseDescriptionPacket::getLsaHeadersForUpdate(), inet::ospfv3::Ospfv3LinkStateAcknowledgementPacket::getLsaHeadersForUpdate(), inet::UdpJoinMulticastGroupsCommand::getMulticastAddrForUpdate(), inet::UdpLeaveMulticastGroupsCommand::getMulticastAddrForUpdate(), inet::Ipv4RoutingTable::getMulticastRoute(), inet::eigrp::EigrpNeighborTable< Ipv4Address >::getNeighbor(), inet::ospfv2::Ospfv2HelloPacket::getNeighborForUpdate(), inet::ospfv3::Ospfv3HelloPacket::getNeighborIDForUpdate(), inet::ospfv3::Ospfv3LinkStateUpdatePacket::getNetworkLSAsForUpdate(), inet::bgp::BgpUpdateMessage::getNLRIForUpdate(), inet::DhcpOptions::getNtpForUpdate(), inet::LMacHeaderBase::getOccupiedSlotsForUpdate(), inet::Ipv4Header::getOption(), inet::bgp::BgpOpenMessage::getOptionalParameterForUpdate(), inet::Ipv4OptionsTagBase::getOptionForUpdate(), inet::Ipv6NdOptions::getOptionForUpdate(), inet::Ipv4Header::getOptionForUpdate(), inet::PimHello::getOptionsForUpdate(), inet::ospfv2::Ospfv2LinkStateUpdatePacket::getOspfLSAsForUpdate(), inet::Ipv4MulticastRoute::getOutInterface(), inet::PacketEventTag::getPacketEventsForUpdate(), inet::sctp::SctpErrorChunk::getParameters(), inet::sctp::SctpStreamResetChunk::getParameters(), inet::sctp::SctpErrorChunk_Base::getParametersForUpdate(), inet::sctp::SctpStreamResetChunk_Base::getParametersForUpdate(), inet::bgp::BgpUpdateMessage::getPathAttributesForUpdate(), inet::StreamRedundancyConfigurator::getPathFragments(), inet::sctp::NatMessage::getPeer1AddressesForUpdate(), inet::sctp::NatMessage::getPeer2AddressesForUpdate(), inet::ospfv3::Ospfv3LinkLsa::getPrefixesForUpdate(), inet::ospfv3::Ospfv3IntraAreaPrefixLsa::getPrefixesForUpdate(), inet::JoinPruneGroup::getPrunedSourceAddressForUpdate(), inet::Ipv4OptionRecordRoute::getRecordAddressForUpdate(), inet::Ipv4OptionTimestamp::getRecordAddressForUpdate(), inet::ospfv2::Ospfv2LinkStateRequestPacket::getRequestsForUpdate(), inet::ospfv3::Ospfv3LinkStateRequestPacket::getRequestsForUpdate(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getRoute(), inet::NextHopRoutingTable::getRoute(), inet::Ipv4RoutingTable::getRoute(), inet::eigrp::EigrpTopologyTable< Ipv4Address >::getRouteInfo(), inet::DhcpOptions::getRouterForUpdate(), inet::ospfv3::Ospfv3LinkStateUpdatePacket::getRouterLSAsForUpdate(), inet::ospfv3::Ospfv3RouterLsa::getRoutersForUpdate(), inet::EigrpMsgReq_Base::getRoutesForUpdate(), inet::tcp::TcpOptionSack::getSackItemForUpdate(), inet::sctp::SctpHeader::getSctpChunks(), inet::sctp::SctpHeader_Base::getSctpChunksForUpdate(), inet::AddressListOption::getSecondaryAddressesForUpdate(), inet::UdpBlockMulticastSourcesCommand::getSourceListForUpdate(), inet::UdpUnblockMulticastSourcesCommand::getSourceListForUpdate(), inet::UdpJoinMulticastSourcesCommand::getSourceListForUpdate(), inet::UdpLeaveMulticastSourcesCommand::getSourceListForUpdate(), inet::UdpSetMulticastSourceFilterCommand::getSourceListForUpdate(), inet::osm::Node::getTag(), inet::osm::Way::getTag(), inet::osm::Relation::getTag(), inet::TlvOptions::getTlvOptionForUpdate(), inet::ospfv2::Ospfv2Link::getTosDataForUpdate(), inet::ospfv2::Ospfv2SummaryLsa::getTosDataForUpdate(), inet::dymo::Rerr::getUnreachableNodeForUpdate(), inet::aodv::Rerr::getUnreachableNodesForUpdate(), inet::bgp::BgpUpdatePathAttributesAsPath::getValueForUpdate(), inet::bgp::BgpUpdateMessage::getWithdrawnRoutesForUpdate(), inet::SctpServer::handleMessage(), inet::SctpPeer::handleMessage(), inet::SctpNatPeer::handleMessage(), inet::physicallayer::ConvolutionalCoder::inputSymbolToOutputSymbol(), inet::SpatialGrid::insertObject(), inet::sctp::SctpHeader::insertSctpChunks(), inet::Macho::Alias::isChild(), inet::Macho::Alias::isParent(), inet::Ipv6InterfaceData::isTentativeAddress(), inet::Udp::joinMulticastGroups(), inet::Macho::MachoLink< C, P >::key(), inet::visualizer::NetworkNodeCanvasVisualization::layout(), inet::math::n_choose_k(), inet::ospfv2::Router::notifyAboutRoutingTableChanges(), inet::osm::OpenStreetMap::parseTags(), inet::Ipv6InterfaceData::permanentlyAssign(), inet::ospfv3::Ospfv3Interface::prepareHello(), inet::bgp::BgpRouter::printUpdateMessage(), inet::bgp::BgpRouter::processMessage(), inet::SpatialGrid::rangeQuery(), inet::MoBanCoordinator::readConfigurationFile(), inet::Ipv4NetworkConfigurator::readMulticastGroupConfiguration(), inet::ospfv3::Ospfv3Process::rebuildRoutingTable(), inet::LinkStateRouting::receiveSignal(), inet::Ipv6InterfaceData::removeAddress(), inet::sctp::SctpHeader::replaceSctpChunk(), inet::SpatialGrid::rowMajorIndex(), inet::FailureProtectionConfigurator::selectBestTreeSubset(), inet::ospfv2::Ospfv2Interface::sendHelloPacket(), inet::sctp::SctpAssociation::sendInit(), inet::sctp::SctpAssociation::sendInitAck(), inet::Rip::sendRoutes(), inet::PimPacketSerializer::serialize(), inet::bgp::BgpHeaderSerializer::serialize(), inet::sctp::SctpHeaderSerializer::serialize(), inet::MacAddress::setAddressByte(), inet::sctp::SctpHeader::setSctpChunks(), inet::physicallayer::ConvolutionalCoder::setTransferFunctionMatrix(), inet::EtherAppServer::socketDataArrived(), inet::Rip::startRIPRouting(), inet::MacAddress::tryParse(), inet::Ipv4NetworkConfigurator::tryToMergeTwoRoutes(), inet::AdaptiveProbabilisticBroadcast::updateBeta(), inet::Ipv4RoutingTable::updateNetmaskRoutes(), inet::ospfv3::Ospfv3Area::~Ospfv3Area(), inet::ospfv3::Ospfv3Process::~Ospfv3Process(), and inet::ospfv2::Router::~Router().