INET Framework for OMNeT++/OMNEST: inet::PimSm::Route Struct Reference
inet::PimSm::Route Struct Reference
Public Types
enum Flags {
PRUNED = 0x01, REGISTER = 0x02, SPT_BIT = 0x04, JOIN_DESIRED = 0x08,
SOURCE_DIRECTLY_CONNECTED = 0x10
}
enum RegisterState { RS_NO_INFO, RS_JOIN, RS_PRUNE, RS_JOIN_PENDING }
Public Member Functions
Route (PimSm *owner, RouteType type, Ipv4Address origin, Ipv4Address group)
virtual ~Route ()
PimSm * pimsm () const
void addDownstreamInterface (DownstreamInterface *outInterface)
void removeDownstreamInterface (unsigned int i)
DownstreamInterface * findDownstreamInterfaceByInterfaceId (int interfaceId)
DownstreamInterface * getDownstreamInterfaceByInterfaceId (int interfaceId)
int findDownstreamInterface (NetworkInterface *ie)
bool isImmediateOlistNull ()
bool isInheritedOlistNull ()
bool joinDesired () const
bool isSourceDirectlyConnected () const
void startKeepAliveTimer (double keepAlivePeriod)
void startRegisterStopTimer (double interval)
void startJoinTimer (double joinPrunePeriod)
Public Attributes
RouteType type
Ipv4Address rpAddr
Route * rpRoute
Route * gRoute
Route * sgrptRoute
unsigned int sequencenumber
simtime_t installtime
cMessage * keepAliveTimer
cMessage * joinTimer
RegisterState registerState
cMessage * registerStopTimer
UpstreamInterface * upstreamInterface
DownstreamInterfaceVector downstreamInterfaces
Out interfaces (downstream)
Member Enumeration Documentation
Flags
enum inet::PimSm::Route::Flags
Enumerator
PRUNED
REGISTER
SPT_BIT
JOIN_DESIRED
SOURCE_DIRECTLY_CONNECTED
                    {
             PRUNED                    = 0x01, // UpstreamJPState
             REGISTER                  = 0x02, // Register flag
             SPT_BIT                   = 0x04, // used to distinguish whether to forward on (*,*,RP)/(*,G) or on (S,G) state
             JOIN_DESIRED              = 0x08,
             SOURCE_DIRECTLY_CONNECTED = 0x10
         };
RegisterState
enum inet::PimSm::Route::RegisterState
Enumerator
RS_NO_INFO
RS_JOIN
RS_PRUNE
RS_JOIN_PENDING
 { RS_NO_INFO, RS_JOIN, RS_PRUNE, RS_JOIN_PENDING };
Constructor & Destructor Documentation
Route()
inet::PimSm::Route::Route (PimSm * owner, RouteType type, Ipv4Address origin, Ipv4Address group)
     : RouteEntry(owner, origin, group), type(type), rpAddr(Ipv4Address::UNSPECIFIED_ADDRESS),
     rpRoute(nullptr), gRoute(nullptr), sgrptRoute(nullptr),
     sequencenumber(0), keepAliveTimer(nullptr), joinTimer(nullptr), registerState(RS_NO_INFO), registerStopTimer(nullptr),
     upstreamInterface(nullptr)
 {
 }
~Route()
inet::PimSm::Route::~Route () virtual
 {
     owner->cancelAndDelete(keepAliveTimer);
     owner->cancelAndDelete(registerStopTimer);
     owner->cancelAndDelete(joinTimer);
     delete upstreamInterface;
     for (auto& elem : downstreamInterfaces)
         delete elem;
 }
Member Function Documentation
addDownstreamInterface()
void inet::PimSm::Route::addDownstreamInterface (DownstreamInterface * outInterface)
 {
     ASSERT(outInterface);
     auto it = downstreamInterfaces.begin();
     for (; it != downstreamInterfaces.end(); ++it) {
         if ((*it)->ie == outInterface->ie)
             break;
     }
     if (it != downstreamInterfaces.end()) {
         delete *it;
         *it = outInterface;
     }
     else {
         downstreamInterfaces.push_back(outInterface);
     }
 }
Referenced by inet::PimSm::addNewRouteG(), and inet::PimSm::addNewRouteSG().
findDownstreamInterface()
int inet::PimSm::Route::findDownstreamInterface (NetworkInterface * ie)
 {
     for (unsigned int i = 0; i < downstreamInterfaces.size(); i++) {
         DownstreamInterface *downstream = downstreamInterfaces[i];
         if (downstream->ie == ie)
             return i;
     }
     return -1;
 }
findDownstreamInterfaceByInterfaceId()
PimSm::DownstreamInterface * inet::PimSm::Route::findDownstreamInterfaceByInterfaceId (int interfaceId)
 {
     for (auto& elem : downstreamInterfaces) {
         DownstreamInterface *downstream = elem;
         if (downstream->getInterfaceId() == interfaceId)
             return downstream;
     }
     return nullptr;
 }
Referenced by inet::PimSm::DownstreamInterface::isInInheritedOlist(), inet::PimSm::multicastPacketArrivedOnNonRpfInterface(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::PimSm::processPruneG(), and inet::PimSm::processPruneSG().
getDownstreamInterfaceByInterfaceId()
PimSm::DownstreamInterface * inet::PimSm::Route::getDownstreamInterfaceByInterfaceId (int interfaceId)
 {
     DownstreamInterface *downstream = findDownstreamInterfaceByInterfaceId(interfaceId);
     if (!downstream)
         throw cRuntimeError("getDownstreamInterfaceByInterfaceId(): interface %d not found", interfaceId);
     return downstream;
 }
Referenced by inet::PimSm::multicastReceiverAdded(), inet::PimSm::multicastReceiverRemoved(), and inet::PimSm::processAssertPacket().
isImmediateOlistNull()
bool inet::PimSm::Route::isImmediateOlistNull ()
 {
     for (auto& elem : downstreamInterfaces)
         if (elem->isInImmediateOlist())
             return false;
     return true;
 }
Referenced by inet::PimSm::updateJoinDesired().
isInheritedOlistNull()
bool inet::PimSm::Route::isInheritedOlistNull ()
 {
     for (auto& elem : downstreamInterfaces)
         if (elem->isInInheritedOlist())
             return false;
     return true;
 }
Referenced by inet::PimSm::multicastPacketArrivedOnRpfInterface(), inet::PimSm::processJoinTimer(), inet::PimSm::processRegisterPacket(), and inet::PimSm::updateJoinDesired().
isSourceDirectlyConnected()
bool inet::PimSm::Route::isSourceDirectlyConnected () const inline
 { return isFlagSet(SOURCE_DIRECTLY_CONNECTED); }
Referenced by inet::PimSm::joinDesiredChanged().
joinDesired()
bool inet::PimSm::Route::joinDesired () const inline
 { return isFlagSet(JOIN_DESIRED); }
Referenced by inet::PimSm::joinDesiredChanged(), and inet::PimSm::updateJoinDesired().
pimsm()
PimSm* inet::PimSm::Route::pimsm () const inline
 { return check_and_cast<PimSm *>(owner); }
removeDownstreamInterface()
void inet::PimSm::Route::removeDownstreamInterface (unsigned int i)
 {
     // remove corresponding out interface from the Ipv4 route,
     // because it refers to the downstream interface to be deleted
     Ipv4MulticastRoute *ipv4Route = pimsm()->findIpv4Route(source, group);
     ipv4Route->removeOutInterface(i);
     DownstreamInterface *outInterface = downstreamInterfaces[i];
     downstreamInterfaces.erase(downstreamInterfaces.begin() + i);
     delete outInterface;
 }
startJoinTimer()
void inet::PimSm::Route::startJoinTimer (double joinPrunePeriod)
 {
     joinTimer = new cMessage("PIMJoinTimer", JoinTimer);
     joinTimer->setContextPointer(this);
     owner->scheduleAfter(joinPrunePeriod, joinTimer);
 }
Referenced by inet::PimSm::joinDesiredChanged().
startKeepAliveTimer()
void inet::PimSm::Route::startKeepAliveTimer (double keepAlivePeriod)
 {
     ASSERT(this->type == SG);
     keepAliveTimer = new cMessage("PIMKeepAliveTimer", KeepAliveTimer);
     keepAliveTimer->setContextPointer(this);
     owner->scheduleAfter(keepAlivePeriod, keepAliveTimer);
 }
Referenced by inet::PimSm::multicastPacketArrivedOnRpfInterface(), inet::PimSm::processJoinSG(), inet::PimSm::processRegisterPacket(), and inet::PimSm::unroutableMulticastPacketArrived().
startRegisterStopTimer()
void inet::PimSm::Route::startRegisterStopTimer (double interval)
 {
     registerStopTimer = new cMessage("PIMRegisterStopTimer", RegisterStopTimer);
     registerStopTimer->setContextPointer(this);
     owner->scheduleAfter(interval, registerStopTimer);
 }
Referenced by inet::PimSm::processRegisterStopPacket(), and inet::PimSm::processRegisterStopTimer().
Member Data Documentation
downstreamInterfaces
DownstreamInterfaceVector inet::PimSm::Route::downstreamInterfaces
Out interfaces (downstream)
Referenced by inet::PimSm::createIpv4Route(), inet::operator<<(), inet::PimSm::processRegisterPacket(), and inet::PimSm::restartExpiryTimer().
gRoute
Route* inet::PimSm::Route::gRoute
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), and inet::PimSm::DownstreamInterface::isInInheritedOlist().
installtime
simtime_t inet::PimSm::Route::installtime
joinTimer
cMessage* inet::PimSm::Route::joinTimer
Referenced by inet::PimSm::joinDesiredChanged(), and inet::PimSm::processJoinTimer().
keepAliveTimer
cMessage* inet::PimSm::Route::keepAliveTimer
Referenced by inet::PimSm::multicastPacketArrivedOnRpfInterface(), inet::PimSm::multicastPacketForwarded(), inet::PimSm::processKeepAliveTimer(), inet::PimSm::processRegisterPacket(), and inet::PimSm::updateJoinDesired().
registerState
RegisterState inet::PimSm::Route::registerState
Referenced by inet::PimSm::multicastPacketForwarded(), inet::PimSm::processRegisterStopPacket(), inet::PimSm::processRegisterStopTimer(), and inet::PimSm::unroutableMulticastPacketArrived().
registerStopTimer
cMessage* inet::PimSm::Route::registerStopTimer
Referenced by inet::PimSm::processRegisterStopPacket(), and inet::PimSm::processRegisterStopTimer().
rpAddr
Ipv4Address inet::PimSm::Route::rpAddr
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::PimSm::joinDesiredChanged(), inet::PimSm::multicastPacketForwarded(), inet::operator<<(), inet::PimSm::processJoinTimer(), and inet::PimSm::processPrunePendingTimer().
rpRoute
Route* inet::PimSm::Route::rpRoute
Referenced by inet::PimSm::DownstreamInterface::isInInheritedOlist().
sequencenumber
unsigned int inet::PimSm::Route::sequencenumber
sgrptRoute
Route* inet::PimSm::Route::sgrptRoute
Referenced by inet::PimSm::addNewRouteSG(), and inet::PimSm::DownstreamInterface::isInInheritedOlist().
type
RouteType inet::PimSm::Route::type
Referenced by inet::PimSm::deleteMulticastRoute(), inet::PimSm::DownstreamInterface::isInInheritedOlist(), inet::PimSm::joinDesiredChanged(), inet::PimSm::multicastPacketArrivedOnNonRpfInterface(), inet::PimSm::multicastPacketArrivedOnRpfInterface(), inet::PimSm::processAssertTimer(), inet::PimSm::processJoinTimer(), inet::PimSm::processKeepAliveTimer(), inet::PimSm::processPrunePendingTimer(), inet::PimSm::processRegisterStopTimer(), inet::PimSm::removeRoute(), and inet::PimSm::updateJoinDesired().
upstreamInterface
UpstreamInterface* inet::PimSm::Route::upstreamInterface
Referenced by inet::PimSm::addNewRouteG(), inet::PimSm::addNewRouteSG(), inet::PimSm::createIpv4Route(), inet::PimSm::joinDesiredChanged(), inet::operator<<(), inet::PimSm::processAssertPacket(), inet::PimSm::processJoinG(), inet::PimSm::processJoinTimer(), inet::PimSm::processRegisterPacket(), and inet::PimSm::restartExpiryTimer().
The documentation for this struct was generated from the following files:
PimSm.h
PimSm.cc