INET Framework for OMNeT++/OMNEST: inet::units::internal::convert< T1, T2 > Struct Template Reference
inet::units::internal::convert< T1, T2 > Struct Template Reference
#include <Units.h>
Static Public Member Functions
template<typename V >
static V fn (const V &v)
Public Attributes
legacy_static_assert< convertible< T1, T2 >::value > check_convertible
Member Function Documentation
fn()
template<typename T1 , typename T2 > template<typename V > static V inet::units::internal::convert< T1, T2 >::fn (const V & v) inline static
     {
         return convert2<T1, T2>::fn(v);
     }
Referenced by inet::units::internal::convert2< scale< T, Num, Den >, U >::fn(), inet::units::internal::convert2< fscale< T, F >, U >::fn(), inet::units::internal::convert3< T, fscale< U, F > >::fn(), inet::units::internal::convert2< intscale< T, Num, Den >, U >::fn(), inet::units::internal::convert3< T, intscale< U, Num, Den > >::fn(), inet::units::internal::convert2< translate< T, Num, Den >, U >::fn(), and inet::units::internal::convert3< T, translate< U, Num, Den > >::fn().
Member Data Documentation
check_convertible
template<typename T1 , typename T2 > legacy_static_assert<convertible<T1, T2>::value> inet::units::internal::convert< T1, T2 >::check_convertible
The documentation for this struct was generated from the following file:
Units.h