INET Framework for OMNeT++/OMNEST: inet::ieee80211::SequenceNumberCyclic Struct Reference
inet::ieee80211::SequenceNumberCyclic Struct Reference
#include <Ieee80211Defs.h>
Public Member Functions
SequenceNumberCyclic ()
SequenceNumberCyclic (SequenceNumber value)
SequenceNumberCyclic (const SequenceNumberCyclic &other)
SequenceNumber get () const
SequenceNumberCyclic & operator= (const SequenceNumberCyclic &other)
bool operator== (const SequenceNumberCyclic &other) const
bool operator!= (const SequenceNumberCyclic &other) const
SequenceNumberCyclic operator- (int other) const
SequenceNumberCyclic operator+ (int other) const
bool operator< (const SequenceNumberCyclic &other) const
bool operator<= (const SequenceNumberCyclic &other) const
bool operator> (const SequenceNumberCyclic &other) const
bool operator>= (const SequenceNumberCyclic &other) const
Private Member Functions
SequenceNumber modulo4096 (SequenceNumber value) const
SequenceNumber distance4096 (SequenceNumber other) const
Private Attributes
SequenceNumber value
Constructor & Destructor Documentation
SequenceNumberCyclic() [1/3]
inet::ieee80211::SequenceNumberCyclic::SequenceNumberCyclic () inline
 : value(-1) {}
SequenceNumberCyclic() [2/3]
inet::ieee80211::SequenceNumberCyclic::SequenceNumberCyclic (SequenceNumber value) inline explicit
 : value(value) { ASSERT(0 <= value && value < 4096); }
SequenceNumberCyclic() [3/3]
inet::ieee80211::SequenceNumberCyclic::SequenceNumberCyclic (const SequenceNumberCyclic & other) inline
 : value(other.value) { ASSERT(other.value != -1); }
Member Function Documentation
distance4096()
SequenceNumber inet::ieee80211::SequenceNumberCyclic::distance4096 (SequenceNumber other) const inline private
 { ASSERT(0 <= other && other < 4096); return (value - other + 4096) % 4096; }
get()
SequenceNumber inet::ieee80211::SequenceNumberCyclic::get () const inline
 { ASSERT(value != -1); return value; }
Referenced by inet::ieee80211::BlockAckReordering::addMsduIfComplete(), inet::ieee80211::BlockAckRecord::blockAckPolicyFrameReceived(), inet::ieee80211::BlockAckRecord::getAckState(), inet::ieee80211::operator<<(), and inet::ieee80211::ReceiveBuffer::removeFrame().
modulo4096()
SequenceNumber inet::ieee80211::SequenceNumberCyclic::modulo4096 (SequenceNumber value) const inline private
 { ASSERT(value != -1); return (value % 4096 + 4096) % 4096; } // always returns positive result
Referenced by operator+(), and operator-().
operator!=()
bool inet::ieee80211::SequenceNumberCyclic::operator!= (const SequenceNumberCyclic & other) const inline
 { ASSERT(value != -1 && other.value != -1); return value != other.value; }
operator+()
SequenceNumberCyclic inet::ieee80211::SequenceNumberCyclic::operator+ (int other) const inline
 { ASSERT(value != -1); SequenceNumberCyclic result; result.value = modulo4096(value + other); return result; }
operator-()
SequenceNumberCyclic inet::ieee80211::SequenceNumberCyclic::operator- (int other) const inline
 { ASSERT(value != -1); SequenceNumberCyclic result; result.value = modulo4096(value - other); return result; }
operator<()
bool inet::ieee80211::SequenceNumberCyclic::operator< (const SequenceNumberCyclic & other) const inline
{
         ASSERT(value != -1 && other.value != -1);
         SequenceNumber d = (other.value - value + 4096) % 4096;
         return 0 < d && d < 2048;
     }
operator<=()
bool inet::ieee80211::SequenceNumberCyclic::operator<= (const SequenceNumberCyclic & other) const inline
 { return *this == other || *this < other; }
operator=()
SequenceNumberCyclic& inet::ieee80211::SequenceNumberCyclic::operator= (const SequenceNumberCyclic & other) inline
 { ASSERT(other.value != -1 || value == other.value); value = other.value; return *this; }
operator==()
bool inet::ieee80211::SequenceNumberCyclic::operator== (const SequenceNumberCyclic & other) const inline
 { ASSERT(value != -1 && other.value != -1); return value == other.value; }
operator>()
bool inet::ieee80211::SequenceNumberCyclic::operator> (const SequenceNumberCyclic & other) const inline
 { return other < *this; }
operator>=()
bool inet::ieee80211::SequenceNumberCyclic::operator>= (const SequenceNumberCyclic & other) const inline
 { return *this == other || *this > other; }
Member Data Documentation
value
SequenceNumber inet::ieee80211::SequenceNumberCyclic::value private
Referenced by distance4096(), get(), modulo4096(), operator!=(), operator+(), operator-(), operator<(), operator=(), operator==(), and SequenceNumberCyclic().
The documentation for this struct was generated from the following file:
Ieee80211Defs.h