INET Framework for OMNeT++/OMNEST: inet::PimDm::DownstreamInterface Struct Reference
inet::PimDm::DownstreamInterface Struct Reference
Public Types
enum Flags { HAS_CONNECTED_RECEIVERS = 0x01 }
enum PruneState { NO_INFO, PRUNE_PENDING, PRUNED }
Public Member Functions
DownstreamInterface (Route *owner, NetworkInterface *ie)
~DownstreamInterface ()
Route * route () const
PimDm * pimdm () const
PruneState getPruneState ()
cMessage * getPruneTimer () const
cMessage * getPrunePendingTimer () const
bool hasConnectedReceivers () const
void setHasConnectedReceivers (bool value)
bool isInOlist () const
void startPruneTimer (double holdTime)
The method is used to create PIMPrune timer.
void stopPruneTimer ()
void startPrunePendingTimer (double overrideInterval)
void stopPrunePendingTimer ()
Public Attributes
PruneState pruneState
cMessage * pruneTimer
cMessage * prunePendingTimer
Member Enumeration Documentation
Flags
enum inet::PimDm::DownstreamInterface::Flags
Enumerator
HAS_CONNECTED_RECEIVERS
                    {
             HAS_CONNECTED_RECEIVERS = 0x01
         };
PruneState
enum inet::PimDm::DownstreamInterface::PruneState
Enumerator
NO_INFO
PRUNE_PENDING
PRUNED
{
             NO_INFO,          // no prune info, neither pruneTimer or prunePendingTimer is running
             PRUNE_PENDING,    // received a prune from a downstream neighbor, waiting for an override
             PRUNED            // received a prune from a downstream neighbor and it was not overridden
         };
Constructor & Destructor Documentation
DownstreamInterface()
inet::PimDm::DownstreamInterface::DownstreamInterface (Route * owner, NetworkInterface * ie) inline
             : Interface(owner, ie),
             pruneState(NO_INFO), pruneTimer(nullptr), prunePendingTimer(nullptr)
         { ASSERT(owner), ASSERT(ie); }
~DownstreamInterface()
inet::PimDm::DownstreamInterface::~DownstreamInterface ()
 {
     owner->owner->cancelAndDelete(pruneTimer);
     owner->owner->cancelAndDelete(prunePendingTimer);
 }
Member Function Documentation
getPrunePendingTimer()
cMessage* inet::PimDm::DownstreamInterface::getPrunePendingTimer () const inline
 { return prunePendingTimer; }
getPruneState()
PruneState inet::PimDm::DownstreamInterface::getPruneState () inline
 { return pruneState; }
getPruneTimer()
cMessage* inet::PimDm::DownstreamInterface::getPruneTimer () const inline
 { return pruneTimer; }
hasConnectedReceivers()
bool inet::PimDm::DownstreamInterface::hasConnectedReceivers () const inline
 { return isFlagSet(HAS_CONNECTED_RECEIVERS); }
isInOlist()
bool inet::PimDm::DownstreamInterface::isInOlist () const
 {
     // TODO check boundary
     bool hasNeighbors = pimdm()->pimNbt->getNumNeighbors(ie->getInterfaceId()) > 0;
     return ((hasNeighbors && pruneState != PRUNED) || hasConnectedReceivers()) && assertState != I_LOST_ASSERT;
 }
Referenced by inet::PimDm::PimDmOutInterface::isEnabled(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), and inet::PimDm::processGraft().
pimdm()
PimDm* inet::PimDm::DownstreamInterface::pimdm () const inline
 { return check_and_cast<PimDm *>(owner->owner); }
route()
Route* inet::PimDm::DownstreamInterface::route () const inline
 { return check_and_cast<Route *>(owner); }
Referenced by inet::PimDm::processPrunePendingTimer(), and inet::PimDm::processPruneTimer().
setHasConnectedReceivers()
void inet::PimDm::DownstreamInterface::setHasConnectedReceivers (bool value) inline
 { setFlag(HAS_CONNECTED_RECEIVERS, value); }
Referenced by inet::PimDm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), and inet::PimDm::unroutableMulticastPacketArrived().
startPrunePendingTimer()
void inet::PimDm::DownstreamInterface::startPrunePendingTimer (double overrideInterval)
 {
     ASSERT(!prunePendingTimer);
     cMessage *timer = new cMessage("PimPrunePendingTimer", PrunePendingTimer);
     timer->setContextPointer(this);
     owner->owner->scheduleAfter(overrideInterval, timer);
     prunePendingTimer = timer;
 }
Referenced by inet::PimDm::processPrune().
startPruneTimer()
void inet::PimDm::DownstreamInterface::startPruneTimer (double holdTime)
The method is used to create PIMPrune timer.
The timer is set when outgoing interface goes to pruned state. After expiration (usually 3min) interface goes back to forwarding state. It is set to (S,G,I).
 {
     cMessage *timer = new cMessage("PimPruneTimer", PruneTimer);
     timer->setContextPointer(this);
     owner->owner->scheduleAfter(holdTime, timer);
     pruneTimer = timer;
 }
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), and inet::PimDm::processPrunePendingTimer().
stopPrunePendingTimer()
void inet::PimDm::DownstreamInterface::stopPrunePendingTimer ()
 {
     if (prunePendingTimer) {
         if (prunePendingTimer->isScheduled())
             owner->owner->cancelEvent(prunePendingTimer);
         delete prunePendingTimer;
         prunePendingTimer = nullptr;
     }
 }
Referenced by inet::PimDm::processGraft(), and inet::PimDm::processJoin().
stopPruneTimer()
void inet::PimDm::DownstreamInterface::stopPruneTimer ()
 {
     if (pruneTimer) {
         if (pruneTimer->isScheduled())
             owner->owner->cancelEvent(pruneTimer);
         delete pruneTimer;
         pruneTimer = nullptr;
     }
 }
Referenced by inet::PimDm::processGraft(), inet::PimDm::processJoin(), and inet::PimDm::processPruneTimer().
Member Data Documentation
prunePendingTimer
cMessage* inet::PimDm::DownstreamInterface::prunePendingTimer
Referenced by inet::PimDm::processPrunePendingTimer().
pruneState
PruneState inet::PimDm::DownstreamInterface::pruneState
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::processGraft(), inet::PimDm::processJoin(), inet::PimDm::processPrune(), inet::PimDm::processPrunePendingTimer(), inet::PimDm::processPruneTimer(), inet::PimDm::processStateRefreshPacket(), inet::PimDm::processStateRefreshTimer(), and inet::PimDm::sendStateRefreshPacket().
pruneTimer
cMessage* inet::PimDm::DownstreamInterface::pruneTimer
Referenced by inet::PimDm::processPrune(), inet::PimDm::processPruneTimer(), inet::PimDm::processStateRefreshPacket(), and inet::PimDm::processStateRefreshTimer().
The documentation for this struct was generated from the following files:
PimDm.h
PimDm.cc