INET Framework for OMNeT++/OMNEST: inet::PimSm::PimsmInterface Struct Reference
inet::PimSm::PimsmInterface Struct Reference
Public Types
enum Flags { RECEIVER_INCLUDE = 1 << 0, RECEIVER_EXCLUDE = 1 << 1, COULD_ASSERT = 1 << 2, ASSERT_TRACKING_DESIRED = 1 << 3 }
Public Member Functions
PimsmInterface (Route *owner, NetworkInterface *ie)
virtual ~PimsmInterface ()
Route * route () const
PimSm * pimsm () const
void startExpiryTimer (double holdTime)
bool localReceiverInclude () const
void setLocalReceiverInclude (bool value)
bool localReceiverExclude () const
void setLocalReceiverExclude (bool value)
bool couldAssert () const
void setCouldAssert (bool value)
bool assertTrackingDesired () const
void setAssertTrackingDesired (bool value)
bool pimInclude () const
bool pimExclude () const
Public Attributes
cMessage * expiryTimer
Member Enumeration Documentation
Flags
enum inet::PimSm::PimsmInterface::Flags
Enumerator
RECEIVER_INCLUDE
RECEIVER_EXCLUDE
COULD_ASSERT
ASSERT_TRACKING_DESIRED
                    {
             RECEIVER_INCLUDE        = 1 << 0, // local_receiver_include(S,G,I) or local_receiver_include(*,G,I)
             RECEIVER_EXCLUDE        = 1 << 1, // local_receiver_exclude(S,G,I)
             COULD_ASSERT            = 1 << 2, // CouldAssert(S,G,I)
             ASSERT_TRACKING_DESIRED = 1 << 3, // AssertTrackingDesired(S,G,I)
         };
Constructor & Destructor Documentation
PimsmInterface()
inet::PimSm::PimsmInterface::PimsmInterface (Route * owner, NetworkInterface * ie)
     : Interface(owner, ie), expiryTimer(nullptr)
 {
 }
~PimsmInterface()
inet::PimSm::PimsmInterface::~PimsmInterface () virtual
 {
     pimsm()->cancelAndDelete(expiryTimer);
     pimsm()->cancelAndDelete(assertTimer);
 }
Member Function Documentation
assertTrackingDesired()
bool inet::PimSm::PimsmInterface::assertTrackingDesired () const inline
 { return isFlagSet(ASSERT_TRACKING_DESIRED); }
Referenced by inet::PimSm::processAssertG(), and inet::PimSm::processAssertSG().
couldAssert()
bool inet::PimSm::PimsmInterface::couldAssert () const inline
 { return isFlagSet(COULD_ASSERT); }
Referenced by inet::PimSm::multicastPacketArrivedOnNonRpfInterface(), inet::PimSm::processAssertG(), and inet::PimSm::processAssertSG().
localReceiverExclude()
bool inet::PimSm::PimsmInterface::localReceiverExclude () const inline
 { return isFlagSet(RECEIVER_EXCLUDE); }
localReceiverInclude()
bool inet::PimSm::PimsmInterface::localReceiverInclude () const inline
 { return isFlagSet(RECEIVER_INCLUDE); }
pimExclude()
bool inet::PimSm::PimsmInterface::pimExclude () const inline
         {
             return localReceiverExclude() &&
                    (( /*I_am_DR AND*/ assertState != I_LOST_ASSERT) || assertState == I_WON_ASSERT);
         }
pimInclude()
bool inet::PimSm::PimsmInterface::pimInclude () const inline
         {
             return localReceiverInclude() &&
                    (( /*I_am_DR AND*/ assertState != I_LOST_ASSERT) || assertState == I_WON_ASSERT);
         }
Referenced by inet::PimSm::DownstreamInterface::isInInheritedOlist().
pimsm()
PimSm* inet::PimSm::PimsmInterface::pimsm () const inline
 { return check_and_cast<PimSm *>(owner->owner); }
route()
Route* inet::PimSm::PimsmInterface::route () const inline
 { return check_and_cast<Route *>(owner); }
Referenced by inet::PimSm::processAssertG(), inet::PimSm::processAssertSG(), inet::PimSm::processAssertTimer(), and inet::PimSm::processPrunePendingTimer().
setAssertTrackingDesired()
void inet::PimSm::PimsmInterface::setAssertTrackingDesired (bool value) inline
 { setFlag(ASSERT_TRACKING_DESIRED, value); }
setCouldAssert()
void inet::PimSm::PimsmInterface::setCouldAssert (bool value) inline
 { setFlag(COULD_ASSERT, value); }
setLocalReceiverExclude()
void inet::PimSm::PimsmInterface::setLocalReceiverExclude (bool value) inline
 { setFlag(RECEIVER_EXCLUDE, value); }
setLocalReceiverInclude()
void inet::PimSm::PimsmInterface::setLocalReceiverInclude (bool value) inline
 { setFlag(RECEIVER_INCLUDE, value); }
Referenced by inet::PimSm::multicastReceiverAdded(), and inet::PimSm::multicastReceiverRemoved().
startExpiryTimer()
void inet::PimSm::PimsmInterface::startExpiryTimer (double holdTime)
 {
     expiryTimer = new cMessage("PIMExpiryTimer", ExpiryTimer);
     expiryTimer->setContextPointer(this);
     pimsm()->scheduleAfter(holdTime, expiryTimer);
 }
Referenced by inet::PimSm::processJoinG(), and inet::PimSm::processJoinSG().
Member Data Documentation
expiryTimer
cMessage* inet::PimSm::PimsmInterface::expiryTimer
Referenced by inet::PimSm::processExpiryTimer(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::PimSm::processPrunePendingTimer(), and inet::PimSm::restartExpiryTimer().
The documentation for this struct was generated from the following files:
PimSm.h
PimSm.cc