INET Framework for OMNeT++/OMNEST: inet::PimDm::UpstreamInterface Struct Reference
inet::PimDm::UpstreamInterface Struct Reference
Public Types
enum Flags { SOURCE_DIRECTLY_CONNECTED = 0x01 }
enum GraftPruneState { FORWARDING, PRUNED, ACK_PENDING }
enum OriginatorState { NOT_ORIGINATOR, ORIGINATOR }
Public Member Functions
UpstreamInterface (Route *owner, NetworkInterface *ie, Ipv4Address neighbor, bool isSourceDirectlyConnected)
virtual ~UpstreamInterface ()
Route * route () const
PimDm * pimdm () const
int getInterfaceId () const
Ipv4Address rpfNeighbor ()
GraftPruneState getGraftPruneState () const
cMessage * getGraftRetryTimer () const
cMessage * getOverrideTimer () const
simtime_t getLastPruneSentTime () const
bool isSourceDirectlyConnected () const
OriginatorState getOriginatorState () const
cMessage * getSourceActiveTimer () const
cMessage * getStateRefreshTimer () const
unsigned short getMaxTtlSeen () const
void startGraftRetryTimer ()
The method is used to create PIMGraftRetry timer.
void startOverrideTimer ()
void startSourceActiveTimer ()
The method is used to create PIMSourceActive timer.
void startStateRefreshTimer ()
The method is used to create PimStateRefresh timer.
void startPruneLimitTimer ()
void stopPruneLimitTimer ()
bool isPruneLimitTimerRunning ()
Public Attributes
Ipv4Address nextHop
GraftPruneState graftPruneState
cMessage * graftRetryTimer
cMessage * overrideTimer
simtime_t lastPruneSentTime
OriginatorState originatorState
cMessage * sourceActiveTimer
cMessage * stateRefreshTimer
unsigned short maxTtlSeen
Member Enumeration Documentation
Flags
enum inet::PimDm::UpstreamInterface::Flags
Enumerator
SOURCE_DIRECTLY_CONNECTED
                    {
             SOURCE_DIRECTLY_CONNECTED = 0x01
         };
GraftPruneState
enum inet::PimDm::UpstreamInterface::GraftPruneState
Enumerator
FORWARDING
PRUNED
ACK_PENDING
{
             FORWARDING,  // oiflist != nullptr
             PRUNED,      // olist is empty
             ACK_PENDING  // waiting for a Graft Ack
         };
OriginatorState
enum inet::PimDm::UpstreamInterface::OriginatorState
Enumerator
NOT_ORIGINATOR
ORIGINATOR
 { NOT_ORIGINATOR, ORIGINATOR };
Constructor & Destructor Documentation
UpstreamInterface()
inet::PimDm::UpstreamInterface::UpstreamInterface (Route * owner, NetworkInterface * ie, Ipv4Address neighbor, bool isSourceDirectlyConnected) inline
             : Interface(owner, ie), nextHop(neighbor),
             graftPruneState(FORWARDING), graftRetryTimer(nullptr), overrideTimer(nullptr), lastPruneSentTime(0.0),
             originatorState(NOT_ORIGINATOR), sourceActiveTimer(nullptr), stateRefreshTimer(nullptr), maxTtlSeen(0)
         { setFlag(SOURCE_DIRECTLY_CONNECTED, isSourceDirectlyConnected); }
~UpstreamInterface()
inet::PimDm::UpstreamInterface::~UpstreamInterface () virtual
 {
     owner->owner->cancelAndDelete(stateRefreshTimer);
     owner->owner->cancelAndDelete(graftRetryTimer);
     owner->owner->cancelAndDelete(sourceActiveTimer);
     owner->owner->cancelAndDelete(overrideTimer);
 }
Member Function Documentation
getGraftPruneState()
GraftPruneState inet::PimDm::UpstreamInterface::getGraftPruneState () const inline
 { return graftPruneState; }
Referenced by inet::operator<<().
getGraftRetryTimer()
cMessage* inet::PimDm::UpstreamInterface::getGraftRetryTimer () const inline
 { return graftRetryTimer; }
Referenced by inet::operator<<().
getInterfaceId()
int inet::PimDm::UpstreamInterface::getInterfaceId () const inline
 { return ie->getInterfaceId(); }
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::processAssertPacket(), inet::PimDm::processGraft(), inet::PimDm::processGraftRetryTimer(), inet::PimDm::processJoin(), inet::PimDm::processOlistEmptyEvent(), inet::PimDm::processOlistNonEmptyEvent(), inet::PimDm::processOverrideTimer(), inet::PimDm::processPrune(), and inet::PimDm::processStateRefreshPacket().
getLastPruneSentTime()
simtime_t inet::PimDm::UpstreamInterface::getLastPruneSentTime () const inline
 { return lastPruneSentTime; }
Referenced by inet::operator<<().
getMaxTtlSeen()
unsigned short inet::PimDm::UpstreamInterface::getMaxTtlSeen () const inline
 { return maxTtlSeen; }
Referenced by inet::operator<<().
getOriginatorState()
OriginatorState inet::PimDm::UpstreamInterface::getOriginatorState () const inline
 { return originatorState; }
Referenced by inet::operator<<().
getOverrideTimer()
cMessage* inet::PimDm::UpstreamInterface::getOverrideTimer () const inline
 { return overrideTimer; }
Referenced by inet::operator<<().
getSourceActiveTimer()
cMessage* inet::PimDm::UpstreamInterface::getSourceActiveTimer () const inline
 { return sourceActiveTimer; }
Referenced by inet::operator<<().
getStateRefreshTimer()
cMessage* inet::PimDm::UpstreamInterface::getStateRefreshTimer () const inline
 { return stateRefreshTimer; }
Referenced by inet::operator<<().
isPruneLimitTimerRunning()
bool inet::PimDm::UpstreamInterface::isPruneLimitTimerRunning () inline
 { return lastPruneSentTime > 0.0 && simTime() < lastPruneSentTime + pimdm()->pruneLimitInterval; }
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), and inet::PimDm::processStateRefreshPacket().
isSourceDirectlyConnected()
bool inet::PimDm::UpstreamInterface::isSourceDirectlyConnected () const inline
 { return isFlagSet(SOURCE_DIRECTLY_CONNECTED); }
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::processOlistEmptyEvent(), inet::PimDm::processOlistNonEmptyEvent(), inet::PimDm::processPrune(), and inet::PimDm::rpfInterfaceHasChanged().
pimdm()
PimDm* inet::PimDm::UpstreamInterface::pimdm () const inline
 { return check_and_cast<PimDm *>(owner->owner); }
route()
Route* inet::PimDm::UpstreamInterface::route () const inline
 { return check_and_cast<Route *>(owner); }
Referenced by inet::PimDm::processGraftRetryTimer(), inet::PimDm::processOverrideTimer(), inet::PimDm::processSourceActiveTimer(), and inet::PimDm::processStateRefreshTimer().
rpfNeighbor()
Ipv4Address inet::PimDm::UpstreamInterface::rpfNeighbor () inline
 { return assertState == I_LOST_ASSERT ? winnerMetric.address : nextHop; }
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::operator<<(), inet::PimDm::processGraftRetryTimer(), inet::PimDm::processOlistEmptyEvent(), inet::PimDm::processOlistNonEmptyEvent(), inet::PimDm::processOverrideTimer(), inet::PimDm::processStateRefreshPacket(), and inet::PimDm::rpfInterfaceHasChanged().
startGraftRetryTimer()
void inet::PimDm::UpstreamInterface::startGraftRetryTimer ()
The method is used to create PIMGraftRetry timer.
The timer is set when router wants to join to multicast tree again and send PIM Prune message to upstream. Router waits for Graft Retry Timer (3 s) for PIM PruneAck message from upstream. If timer expires, router will send PIM Prune message again. It is set to (S,G).
 {
     graftRetryTimer = new cMessage("PIMGraftRetryTimer", GraftRetryTimer);
     graftRetryTimer->setContextPointer(this);
     pimdm()->scheduleAfter(pimdm()->graftRetryInterval, graftRetryTimer);
 }
Referenced by inet::PimDm::processOlistNonEmptyEvent(), and inet::PimDm::rpfInterfaceHasChanged().
startOverrideTimer()
void inet::PimDm::UpstreamInterface::startOverrideTimer ()
 {
     overrideTimer = new cMessage("PIMOverrideTimer", UpstreamOverrideTimer);
     overrideTimer->setContextPointer(this);
     pimdm()->scheduleAfter(pimdm()->overrideInterval, overrideTimer);
 }
Referenced by inet::PimDm::processPrune(), and inet::PimDm::processStateRefreshPacket().
startPruneLimitTimer()
void inet::PimDm::UpstreamInterface::startPruneLimitTimer () inline
 { lastPruneSentTime = simTime(); }
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::processOlistEmptyEvent(), and inet::PimDm::processStateRefreshPacket().
startSourceActiveTimer()
void inet::PimDm::UpstreamInterface::startSourceActiveTimer ()
The method is used to create PIMSourceActive timer.
The timer is set when source of multicast is connected directly to the router. If timer expires, router will remove the route from multicast routing table. It is set to (S,G).
 {
     sourceActiveTimer = new cMessage("PIMSourceActiveTimer", SourceActiveTimer);
     sourceActiveTimer->setContextPointer(this);
     pimdm()->scheduleAfter(pimdm()->sourceActiveInterval, sourceActiveTimer);
 }
Referenced by inet::PimDm::unroutableMulticastPacketArrived().
startStateRefreshTimer()
void inet::PimDm::UpstreamInterface::startStateRefreshTimer ()
The method is used to create PimStateRefresh timer.
The timer is set when source of multicast is connected directly to the router. If timer expires, router will send StateRefresh message, which will propagate through all network and wil reset Prune Timer. It is set to (S,G).
 {
     stateRefreshTimer = new cMessage("PIMStateRefreshTimer", StateRefreshTimer);
     sourceActiveTimer->setContextPointer(this);
     pimdm()->scheduleAfter(pimdm()->stateRefreshInterval, stateRefreshTimer);
 }
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), and inet::PimDm::unroutableMulticastPacketArrived().
stopPruneLimitTimer()
void inet::PimDm::UpstreamInterface::stopPruneLimitTimer () inline
 { lastPruneSentTime = 0; }
Referenced by inet::PimDm::processOlistNonEmptyEvent(), and inet::PimDm::rpfInterfaceHasChanged().
Member Data Documentation
graftPruneState
GraftPruneState inet::PimDm::UpstreamInterface::graftPruneState
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::processAssert(), inet::PimDm::processAssertTimer(), inet::PimDm::processGraftAckPacket(), inet::PimDm::processGraftRetryTimer(), inet::PimDm::processJoin(), inet::PimDm::processOlistEmptyEvent(), inet::PimDm::processOlistNonEmptyEvent(), inet::PimDm::processOverrideTimer(), inet::PimDm::processPrune(), inet::PimDm::processStateRefreshPacket(), inet::PimDm::rpfInterfaceHasChanged(), and inet::PimDm::unroutableMulticastPacketArrived().
graftRetryTimer
cMessage* inet::PimDm::UpstreamInterface::graftRetryTimer
Referenced by inet::PimDm::processGraftAckPacket(), inet::PimDm::processGraftRetryTimer(), inet::PimDm::processOlistEmptyEvent(), inet::PimDm::processStateRefreshPacket(), and inet::PimDm::rpfInterfaceHasChanged().
lastPruneSentTime
simtime_t inet::PimDm::UpstreamInterface::lastPruneSentTime
maxTtlSeen
unsigned short inet::PimDm::UpstreamInterface::maxTtlSeen
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::processStateRefreshTimer(), and inet::PimDm::unroutableMulticastPacketArrived().
nextHop
Ipv4Address inet::PimDm::UpstreamInterface::nextHop
originatorState
OriginatorState inet::PimDm::UpstreamInterface::originatorState
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::processSourceActiveTimer(), inet::PimDm::processStateRefreshTimer(), and inet::PimDm::unroutableMulticastPacketArrived().
overrideTimer
cMessage* inet::PimDm::UpstreamInterface::overrideTimer
Referenced by inet::PimDm::processJoin(), inet::PimDm::processOverrideTimer(), inet::PimDm::processPrune(), and inet::PimDm::processStateRefreshPacket().
sourceActiveTimer
cMessage* inet::PimDm::UpstreamInterface::sourceActiveTimer
Referenced by inet::PimDm::multicastPacketArrivedOnRpfInterface(), and inet::PimDm::processSourceActiveTimer().
stateRefreshTimer
cMessage* inet::PimDm::UpstreamInterface::stateRefreshTimer
Referenced by inet::PimDm::processSourceActiveTimer(), and inet::PimDm::processStateRefreshTimer().
The documentation for this struct was generated from the following files:
PimDm.h
PimDm.cc