INET Framework for OMNeT++/OMNEST: inet::PimSm::UpstreamInterface Struct Reference
inet::PimSm::UpstreamInterface Struct Reference
Public Member Functions
UpstreamInterface (Route *owner, NetworkInterface *ie, Ipv4Address nextHop)
int getInterfaceId () const
Ipv4Address rpfNeighbor ()
Public Member Functions inherited from inet::PimSm::PimsmInterface
PimsmInterface (Route *owner, NetworkInterface *ie)
virtual ~PimsmInterface ()
Route * route () const
PimSm * pimsm () const
void startExpiryTimer (double holdTime)
bool localReceiverInclude () const
void setLocalReceiverInclude (bool value)
bool localReceiverExclude () const
void setLocalReceiverExclude (bool value)
bool couldAssert () const
void setCouldAssert (bool value)
bool assertTrackingDesired () const
void setAssertTrackingDesired (bool value)
bool pimInclude () const
bool pimExclude () const
Public Attributes
Ipv4Address nextHop
Public Attributes inherited from inet::PimSm::PimsmInterface
cMessage * expiryTimer
Additional Inherited Members
Public Types inherited from inet::PimSm::PimsmInterface
enum Flags { RECEIVER_INCLUDE = 1 << 0, RECEIVER_EXCLUDE = 1 << 1, COULD_ASSERT = 1 << 2, ASSERT_TRACKING_DESIRED = 1 << 3 }
Constructor & Destructor Documentation
UpstreamInterface()
inet::PimSm::UpstreamInterface::UpstreamInterface (Route * owner, NetworkInterface * ie, Ipv4Address nextHop) inline
             : PimsmInterface(owner, ie), nextHop(nextHop) {}
Member Function Documentation
getInterfaceId()
int inet::PimSm::UpstreamInterface::getInterfaceId () const inline
 { return ie->getInterfaceId(); }
Referenced by inet::PimSm::processAssertPacket().
rpfNeighbor()
Ipv4Address inet::PimSm::UpstreamInterface::rpfNeighbor () inline
 { return assertState == I_LOST_ASSERT ? winnerMetric.address : nextHop; }
Referenced by inet::PimSm::joinDesiredChanged(), inet::operator<<(), and inet::PimSm::processRegisterPacket().
Member Data Documentation
nextHop
Ipv4Address inet::PimSm::UpstreamInterface::nextHop
Referenced by inet::PimSm::processJoinTimer().
The documentation for this struct was generated from the following file:
PimSm.h