INET Framework for OMNeT++/OMNEST: inet::PimSm::DownstreamInterface Struct Reference
inet::PimSm::DownstreamInterface Struct Reference
Public Types
enum JoinPruneState { NO_INFO, JOIN, PRUNE_PENDING }
States of each outgoing interface.
Public Types inherited from inet::PimSm::PimsmInterface
enum Flags { RECEIVER_INCLUDE = 1 << 0, RECEIVER_EXCLUDE = 1 << 1, COULD_ASSERT = 1 << 2, ASSERT_TRACKING_DESIRED = 1 << 3 }
Public Member Functions
DownstreamInterface (Route *owner, NetworkInterface *ie, JoinPruneState joinPruneState, bool show=true)
virtual ~DownstreamInterface ()
int getInterfaceId () const
bool isInImmediateOlist () const
bool isInInheritedOlist () const
void startPrunePendingTimer (double joinPruneOverrideInterval)
Public Member Functions inherited from inet::PimSm::PimsmInterface
PimsmInterface (Route *owner, NetworkInterface *ie)
virtual ~PimsmInterface ()
Route * route () const
PimSm * pimsm () const
void startExpiryTimer (double holdTime)
bool localReceiverInclude () const
void setLocalReceiverInclude (bool value)
bool localReceiverExclude () const
void setLocalReceiverExclude (bool value)
bool couldAssert () const
void setCouldAssert (bool value)
bool assertTrackingDesired () const
void setAssertTrackingDesired (bool value)
bool pimInclude () const
bool pimExclude () const
Public Attributes
JoinPruneState joinPruneState
cMessage * prunePendingTimer
Public Attributes inherited from inet::PimSm::PimsmInterface
cMessage * expiryTimer
Member Enumeration Documentation
JoinPruneState
enum inet::PimSm::DownstreamInterface::JoinPruneState
States of each outgoing interface.
Enumerator
NO_INFO
JOIN
PRUNE_PENDING
 { NO_INFO, JOIN, PRUNE_PENDING };
Constructor & Destructor Documentation
DownstreamInterface()
inet::PimSm::DownstreamInterface::DownstreamInterface (Route * owner, NetworkInterface * ie, JoinPruneState joinPruneState, bool show = true) inline
             : PimsmInterface(owner, ie), joinPruneState(joinPruneState), prunePendingTimer(nullptr) {}
~DownstreamInterface()
inet::PimSm::DownstreamInterface::~DownstreamInterface () virtual
 {
     pimsm()->cancelAndDelete(prunePendingTimer);
 }
Member Function Documentation
getInterfaceId()
int inet::PimSm::DownstreamInterface::getInterfaceId () const inline
 { return ie->getInterfaceId(); }
Referenced by inet::PimSm::Route::findDownstreamInterfaceByInterfaceId(), inet::PimSm::processPrunePendingTimer(), inet::PimSm::processRegisterPacket(), and inet::PimSm::restartExpiryTimer().
isInImmediateOlist()
bool inet::PimSm::DownstreamInterface::isInImmediateOlist () const
 {
     // immediate_olist(*,*,RP) = joins(*,*,RP)
     // immediate_olist(*,G) = joins(*,G) (+) pim_include(*,G) (-) lost_assert(*,G)
     // immediate_olist(S,G) = joins(S,G) (+) pim_include(S,G) (-) lost_assert(S,G)
     switch (route()->type) {
         case RP:
             return joinPruneState != NO_INFO;
         case G:
             return assertState != I_LOST_ASSERT && (joinPruneState != NO_INFO || pimInclude());
         case SG:
             return assertState != I_LOST_ASSERT && (joinPruneState != NO_INFO || pimInclude());
         case SGrpt:
             ASSERT(false);
             break;
     }
     return false;
 }
isInInheritedOlist()
bool inet::PimSm::DownstreamInterface::isInInheritedOlist () const
 {
     // inherited_olist(S,G,rpt) = ( joins(*,*,RP(G)) (+) joins(*,G) (-) prunes(S,G,rpt) )
     //                            (+) ( pim_include(*,G) (-) pim_exclude(S,G))
     //                            (-) ( lost_assert(*,G) (+) lost_assert(S,G,rpt) )
     // inherited_olist(S,G) = inherited_olist(S,G,rpt) (+)
     //                        joins(S,G) (+) pim_include(S,G) (-) lost_assert(S,G)
     Route *route = this->route();
     int interfaceId = ie->getInterfaceId();
     bool include = false;
     switch (route->type) {
         case RP:
             // joins(*,*,RP(G))
             include |= joinPruneState != NO_INFO;
             break;
         case G: // inherited_olist(S,G,rpt) when there is not (S,G,rpt) state
             // joins(*,*,RP(G))
             if (route->rpRoute) {
                 DownstreamInterface *downstream = route->rpRoute->findDownstreamInterfaceByInterfaceId(interfaceId);
                 include |= downstream && downstream->joinPruneState != NO_INFO;
             }
             include |= joinPruneState != NO_INFO;
             include |= pimInclude();
             include &= assertState != I_LOST_ASSERT;
             break;
         case SGrpt:
             // joins(*,*,RP(G)
             if (route->rpRoute) {
                 DownstreamInterface *downstream = route->rpRoute->findDownstreamInterfaceByInterfaceId(interfaceId);
                 include |= downstream && downstream->joinPruneState != NO_INFO;
             }
             // (+) joins(*,G)
             if (route->gRoute) {
                 DownstreamInterface *downstream = route->gRoute->findDownstreamInterfaceByInterfaceId(interfaceId);
                 include |= downstream && downstream->joinPruneState != NO_INFO;
             }
             // TODO (-) prunes(S,G,prt)
             if (route->gRoute) {
                 DownstreamInterface *downstream = route->gRoute->findDownstreamInterfaceByInterfaceId(interfaceId);
                 // (+) ( pim_include(*,G) (-) pim_exclude(S,G))
                 include |= (downstream && downstream->pimInclude()) && !pimExclude();
                 // (-) lost_assert(*,G)
                 include &= !downstream || downstream->assertState != I_LOST_ASSERT;
             }
             // (-) lost_assert(S,G)
             include &= assertState != I_LOST_ASSERT;
             break;
         case SG:
             // inherited_olist(S,G,rpt)
             if (route->sgrptRoute) {
                 DownstreamInterface *downstream = route->sgrptRoute->findDownstreamInterfaceByInterfaceId(interfaceId);
                 include |= downstream && downstream->isInInheritedOlist();
             }
             else if (route->gRoute) {
                 DownstreamInterface *downstream = route->gRoute->findDownstreamInterfaceByInterfaceId(interfaceId);
                 include |= downstream && downstream->isInInheritedOlist();
             }
             // (+) joins(S,G)
             include |= joinPruneState != NO_INFO;
             // (+) pim_include(S,G)
             include |= pimInclude();
             // (-) lost_assert(S,G)
             include &= assertState != I_LOST_ASSERT;
             break;
     }
     return include;
 }
Referenced by inet::PimSm::PimSmOutInterface::isEnabled(), isInInheritedOlist(), and inet::PimSm::processRegisterPacket().
startPrunePendingTimer()
void inet::PimSm::DownstreamInterface::startPrunePendingTimer (double joinPruneOverrideInterval)
 {
     ASSERT(!prunePendingTimer);
     prunePendingTimer = new cMessage("PIMPrunePendingTimer", PrunePendingTimer);
     prunePendingTimer->setContextPointer(this);
     pimsm()->scheduleAfter(joinPruneOverrideInterval, prunePendingTimer);
 }
Referenced by inet::PimSm::processPruneG(), and inet::PimSm::processPruneSG().
Member Data Documentation
joinPruneState
JoinPruneState inet::PimSm::DownstreamInterface::joinPruneState
Referenced by isInInheritedOlist(), inet::PimSm::processExpiryTimer(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), inet::PimSm::processPruneG(), inet::PimSm::processPrunePendingTimer(), and inet::PimSm::processPruneSG().
prunePendingTimer
cMessage* inet::PimSm::DownstreamInterface::prunePendingTimer
Referenced by inet::PimSm::processExpiryTimer(), inet::PimSm::processJoinG(), inet::PimSm::processJoinSG(), and inet::PimSm::processPrunePendingTimer().
The documentation for this struct was generated from the following files:
PimSm.h
PimSm.cc