INET Framework for OMNeT++/OMNEST: inet::sctp::SctpAssociation::SSFunctions Struct Reference
inet::sctp::SctpAssociation::SSFunctions Struct Reference
#include <SctpAssociation.h>
Public Attributes
void(SctpAssociation::* ssInitStreams)(uint32_t inStreams, uint32_t outStreams)
void(SctpAssociation::* ssAddInStreams)(uint32_t inStreams)
void(SctpAssociation::* ssAddOutStreams)(uint32_t outStreams)
int32_t(SctpAssociation::* ssGetNextSid)(SctpPathVariables *path, bool peek)
int32_t(SctpAssociation::* ssUsableStreams)()
Member Data Documentation
ssAddInStreams
void(SctpAssociation::* inet::sctp::SctpAssociation::SSFunctions::ssAddInStreams) (uint32_t inStreams)
Referenced by inet::sctp::SctpAssociation::processResetResponseArrived(), inet::sctp::SctpAssociation::processStreamResetArrived(), and inet::sctp::SctpAssociation::SctpAssociation().
ssAddOutStreams
void(SctpAssociation::* inet::sctp::SctpAssociation::SSFunctions::ssAddOutStreams) (uint32_t outStreams)
Referenced by inet::sctp::SctpAssociation::processResetResponseArrived(), and inet::sctp::SctpAssociation::SctpAssociation().
ssGetNextSid
int32_t(SctpAssociation::* inet::sctp::SctpAssociation::SSFunctions::ssGetNextSid) (SctpPathVariables *path, bool peek)
Referenced by inet::sctp::SctpAssociation::dequeueOutboundDataMsg(), inet::sctp::SctpAssociation::nextChunkFitsIntoPacket(), and inet::sctp::SctpAssociation::SctpAssociation().
ssInitStreams
void(SctpAssociation::* inet::sctp::SctpAssociation::SSFunctions::ssInitStreams) (uint32_t inStreams, uint32_t outStreams)
Referenced by inet::sctp::SctpAssociation::processInitAckArrived(), inet::sctp::SctpAssociation::SctpAssociation(), and inet::sctp::SctpAssociation::sendInitAck().
ssUsableStreams
int32_t(SctpAssociation::* inet::sctp::SctpAssociation::SSFunctions::ssUsableStreams) ()
Referenced by inet::sctp::SctpAssociation::SctpAssociation().
The documentation for this struct was generated from the following file:
SctpAssociation.h