INET Framework for OMNeT++/OMNEST: inet::PimDm::Route Struct Reference
inet::PimDm::Route Struct Reference
Public Member Functions
Route (PimDm *owner, Ipv4Address source, Ipv4Address group)
virtual ~Route ()
DownstreamInterface * findDownstreamInterfaceByInterfaceId (int interfaceId) const
DownstreamInterface * createDownstreamInterface (NetworkInterface *ie)
DownstreamInterface * removeDownstreamInterface (int interfaceId)
bool isOilistNull ()
Public Attributes
UpstreamInterface * upstreamInterface
std::vector< DownstreamInterface * > downstreamInterfaces
Constructor & Destructor Documentation
Route()
inet::PimDm::Route::Route (PimDm * owner, Ipv4Address source, Ipv4Address group) inline
             : RouteEntry(owner, source, group), upstreamInterface(nullptr) {}
~Route()
inet::PimDm::Route::~Route () virtual
 {
     delete upstreamInterface;
     for (auto& elem : downstreamInterfaces)
         delete elem;
     downstreamInterfaces.clear();
 }
Member Function Documentation
createDownstreamInterface()
PimDm::DownstreamInterface * inet::PimDm::Route::createDownstreamInterface (NetworkInterface * ie)
 {
     DownstreamInterface *downstream = new DownstreamInterface(this, ie);
     downstreamInterfaces.push_back(downstream);
     return downstream;
 }
Referenced by inet::PimDm::multicastReceiverAdded(), inet::PimDm::rpfInterfaceHasChanged(), and inet::PimDm::unroutableMulticastPacketArrived().
findDownstreamInterfaceByInterfaceId()
PimDm::DownstreamInterface * inet::PimDm::Route::findDownstreamInterfaceByInterfaceId (int interfaceId) const
 {
     for (auto& elem : downstreamInterfaces)
         if (elem->ie->getInterfaceId() == interfaceId)
             return elem;
     return nullptr;
 }
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastReceiverAdded(), inet::PimDm::multicastReceiverRemoved(), inet::PimDm::processAssertPacket(), inet::PimDm::processGraft(), and inet::PimDm::processJoin().
isOilistNull()
bool inet::PimDm::Route::isOilistNull ()
 {
     for (auto& elem : downstreamInterfaces) {
         if (elem->isInOlist())
             return false;
     }
     return true;
 }
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::multicastReceiverRemoved(), inet::PimDm::processAssert(), inet::PimDm::processAssertTimer(), inet::PimDm::processJoin(), and inet::PimDm::rpfInterfaceHasChanged().
removeDownstreamInterface()
PimDm::DownstreamInterface * inet::PimDm::Route::removeDownstreamInterface (int interfaceId)
 {
     for (auto it = downstreamInterfaces.begin(); it != downstreamInterfaces.end(); ++it) {
         DownstreamInterface *downstream = *it;
         if (downstream->ie->getInterfaceId() == interfaceId) {
             downstreamInterfaces.erase(it);
             return downstream;
         }
     }
     return nullptr;
 }
Referenced by inet::PimDm::rpfInterfaceHasChanged().
Member Data Documentation
downstreamInterfaces
std::vector<DownstreamInterface *> inet::PimDm::Route::downstreamInterfaces
Referenced by inet::operator<<(), inet::PimDm::processStateRefreshPacket(), inet::PimDm::unroutableMulticastPacketArrived(), and ~Route().
upstreamInterface
UpstreamInterface* inet::PimDm::Route::upstreamInterface
Referenced by inet::PimDm::multicastPacketArrivedOnNonRpfInterface(), inet::PimDm::multicastPacketArrivedOnRpfInterface(), inet::PimDm::multicastReceiverAdded(), inet::operator<<(), inet::PimDm::processAssert(), inet::PimDm::processAssertPacket(), inet::PimDm::processAssertTimer(), inet::PimDm::processGraft(), inet::PimDm::processGraftAckPacket(), inet::PimDm::processJoin(), inet::PimDm::processOlistEmptyEvent(), inet::PimDm::processOlistNonEmptyEvent(), inet::PimDm::processStateRefreshPacket(), inet::PimDm::rpfInterfaceHasChanged(), inet::PimDm::unroutableMulticastPacketArrived(), and ~Route().
The documentation for this struct was generated from the following files:
PimDm.h
PimDm.cc